ug4: ugbase/common/assert.cpp File Reference
assert.cpp File Reference
#include "common/log.h"
#include "common/profiler/profiler.h"
#include "assert.h"
#include <stdlib.h>
#include <string>
#include <sstream>
#include "pcl/pcl_base.h"
Functions
void gcc_backtrace ()
string get_gcc_backtrace ()
void lua_backtrace ()
void shiny_backtrace ()
void ug_assert_failed ()
called whenever UG_ASSERT is called.
void ug_assert_or_error ()
void ug_backtrace ()
void ug_throw_error ()
called whenever UG_THROW or UG_THROW_REGISTRY_ERROR is called.
Function Documentation
gcc_backtrace()
void gcc_backtrace ()
References get_gcc_backtrace(), and UG_LOG.
Referenced by ug_backtrace().
get_gcc_backtrace()
string get_gcc_backtrace ()
References ug::demangle_block().
Referenced by gcc_backtrace().
lua_backtrace()
void lua_backtrace ()
References ug::script::IsLUADebug(), ug::bridge::LuaStackTraceString(), and UG_LOG.
Referenced by ug_backtrace().
shiny_backtrace()
void shiny_backtrace ()
References UG_LOG.
Referenced by ug_backtrace().
ug_assert_or_error()
void ug_assert_or_error ()
put a breakpoint here to break on UG_ASSERT or UG_THROW b ug_assert_or_error
Referenced by ug_assert_failed(), and ug_throw_error().
ug_backtrace()
void ug_backtrace ()
References gcc_backtrace(), lua_backtrace(), and shiny_backtrace().
Referenced by ug::bridge::RegisterBridge_Misc(), and ug_assert_failed().