ug4: ugbase/bindings/vrl/bindings_vrl.cpp File Reference
bindings_vrl.cpp File Reference
#include <string>
#include <vector>
#include "ug.h"
#include "ugbase.h"
#include "registry/registry.h"
#include "registry/class.h"
#include "common/util/path_provider.h"
#include "bridge/util.h"
#include "common/common.h"
#include "common/authors.h"
#include "common/util/string_util.h"
#include "messaging.h"
#include "invocation.h"
#include "threading.h"
#include "type_converter.h"
#include "canvas.h"
#include "bindings_vrl.h"
#include "bindings_vrl_native.h"
#include "compile_info/compile_info.h"
#include "vrl_bridge.h"
Namespaces
ug
the ug namespace
ug::vrl
Functions
JavaVM * ug::vrl::getJavaVM ()
void ug::vrl::initJavaVM (JNIEnv *env)
JNIEXPORT jobject JNICALL Java_edu_gcsc_vrl_ug_UG__1convertRegistryInfo (JNIEnv *env, jobject obj)
JNIEXPORT void JNICALL Java_edu_gcsc_vrl_ug_UG__1delete (JNIEnv *env, jclass cls, jlong objPtr, jlong exportedClsPtr)
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getAuthors (JNIEnv *env, jobject obj)
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getBinaryLicense (JNIEnv *env, jobject obj)
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getCompileDate (JNIEnv *env, jobject obj)
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getDefaultClassNameFromGroup (JNIEnv *env, jobject obj, jstring grpName)
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getDescription (JNIEnv *env, jobject obj)
JNIEXPORT jlong JNICALL Java_edu_gcsc_vrl_ug_UG__1getExportedClassPtrByName (JNIEnv *env, jobject obj, jstring name, jboolean classGrp)
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getSvnRevision (JNIEnv *env, jobject obj)
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getUGVersion (JNIEnv *env, jobject obj)
JNIEXPORT void JNICALL Java_edu_gcsc_vrl_ug_UG__1invalidate (JNIEnv *env, jclass cls, jobject smartPtr)
JNIEXPORT jobject JNICALL Java_edu_gcsc_vrl_ug_UG__1invokeFunction (JNIEnv *env, jobject obj, jstring fName, jboolean readOnly, jobjectArray params)
JNIEXPORT jobject JNICALL Java_edu_gcsc_vrl_ug_UG__1invokeMethod (JNIEnv *env, jobject obj, jstring exportedClassName, jlong objPtr, jboolean readOnly, jstring methodName, jobjectArray params)
JNIEXPORT jobject JNICALL Java_edu_gcsc_vrl_ug_UG__1newInstance (JNIEnv *env, jobject obj, jlong exportedClassPointer, jobjectArray params)
JNIEXPORT jint JNICALL Java_edu_gcsc_vrl_ug_UG__1ugInit (JNIEnv *env, jclass cls, jobjectArray args)
void ug::vrl::SetVRLRegistry (ug::bridge::Registry *pReg)
Variables
static JavaVM * ug::vrl::javaVM = NULL
static ug::bridge::Registry * ug::vrl::vrlRegistry = NULL
Function Documentation
Java_edu_gcsc_vrl_ug_UG__1convertRegistryInfo()
JNIEXPORT jobject JNICALL Java_edu_gcsc_vrl_ug_UG__1convertRegistryInfo (JNIEnv * env, jobject obj)
References ug::vrl::registry2NativeAPI(), and ug::vrl::vrlRegistry.
Java_edu_gcsc_vrl_ug_UG__1delete()
JNIEXPORT void JNICALL Java_edu_gcsc_vrl_ug_UG__1delete (JNIEnv * env, jclass cls, jlong objPtr, jlong exportedClsPtr)
References ug::bridge::IExportedClass::destroy().
Java_edu_gcsc_vrl_ug_UG__1getAuthors()
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getAuthors (JNIEnv * env, jobject obj)
References ug::vrl::stringC2J(), and ug::UG_AUTHORS.
Java_edu_gcsc_vrl_ug_UG__1getBinaryLicense()
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getBinaryLicense (JNIEnv * env, jobject obj)
References ug::vrl::isJObjectAnArray(), ug::vrl::stringC2J(), ug::vrl::stringJ2C(), and ug::UG_BINARY_LICENSE.
Java_edu_gcsc_vrl_ug_UG__1getCompileDate()
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getCompileDate (JNIEnv * env, jobject obj)
References ug::vrl::stringC2J(), and ug::UGCompileDate().
Java_edu_gcsc_vrl_ug_UG__1getDefaultClassNameFromGroup()
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getDefaultClassNameFromGroup (JNIEnv * env, jobject obj, jstring grpName)
References ex, ug::bridge::Registry::get_class_group(), ug::bridge::ClassGroupDesc::get_default_class(), ug::bridge::IExportedClass::name(), ug::vrl::stringC2J(), ug::vrl::stringJ2C(), ug::vrl::throwUgErrorAsJavaException(), and ug::vrl::vrlRegistry.
Java_edu_gcsc_vrl_ug_UG__1getDescription()
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getDescription (JNIEnv * env, jobject obj)
References ug::vrl::stringC2J().
Java_edu_gcsc_vrl_ug_UG__1getExportedClassPtrByName()
JNIEXPORT jlong JNICALL Java_edu_gcsc_vrl_ug_UG__1getExportedClassPtrByName (JNIEnv * env, jobject obj, jstring name, jboolean classGrp)
References ug::vrl::boolJ2C(), ex, ug::bridge::Registry::get_class_group(), ug::bridge::ClassGroupDesc::get_default_class(), ug::vrl::invocation::getExportedClassPtrByName(), ug::vrl::stringJ2C(), ug::vrl::throwUgErrorAsJavaException(), and ug::vrl::vrlRegistry.
Java_edu_gcsc_vrl_ug_UG__1getSvnRevision()
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getSvnRevision (JNIEnv * env, jobject obj)
References ug::vrl::stringC2J(), and ug::vrl::svnRevision().
Java_edu_gcsc_vrl_ug_UG__1getUGVersion()
JNIEXPORT jstring JNICALL Java_edu_gcsc_vrl_ug_UG__1getUGVersion (JNIEnv * env, jobject obj)
References ug::vrl::stringC2J(), and ug::UGGetVersionString().
Java_edu_gcsc_vrl_ug_UG__1invalidate()
JNIEXPORT void JNICALL Java_edu_gcsc_vrl_ug_UG__1invalidate (JNIEnv * env, jclass cls, jobject smartPtr)
References ug::vrl::invalidateJConstSmartPointer(), ug::vrl::invalidateJSmartPointer(), and ug::vrl::isJSmartPointerConst().
Java_edu_gcsc_vrl_ug_UG__1invokeFunction()
JNIEXPORT jobject JNICALL Java_edu_gcsc_vrl_ug_UG__1invokeFunction (JNIEnv * env, jobject obj, jstring fName, jboolean readOnly, jobjectArray params)
References EMPHASIZE_BEGIN, EMPHASIZE_END, ex, ug::bridge::ExportedFunction::execute(), func(), ug::vrl::invocation::getFunctionBySignature(), ug::vrl::getParamTypesAsString(), ug::vrl::jobjectArray2ParamStack(), ug::bridge::UGError_ClassCastFailed::m_from, ug::bridge::UGError_ClassCastFailed::m_to, ug::bridge::ExportedFunctionBase::name(), ug::vrl::param2JObject(), ug::bridge::ExportedFunctionBase::params_in(), ug::bridge::ParameterInfo::size(), ug::vrl::stringJ2C(), ug::vrl::throwUgErrorAsJavaException(), and ug::vrl::vrlRegistry.
Java_edu_gcsc_vrl_ug_UG__1invokeMethod()
JNIEXPORT jobject JNICALL Java_edu_gcsc_vrl_ug_UG__1invokeMethod (JNIEnv * env, jobject obj, jstring exportedClassName, jlong objPtr, jboolean readOnly, jstring methodName, jobjectArray params)
References ug::vrl::boolJ2C(), ug::bridge::ClassCastProvider::cast_to_base_class(), ug::bridge::ExportedMethod::class_name(), EMPHASIZE_BEGIN, EMPHASIZE_END, ex, ug::bridge::ExportedMethod::execute(), ug::vrl::invocation::getClassNodePtrByName(), ug::vrl::invocation::getExportedClassPtrByName(), ug::vrl::invocation::getMethodBySignature(), ug::vrl::getParamTypesAsString(), ug::vrl::jobjectArray2ParamStack(), ug::bridge::UGError_ClassCastFailed::m_from, ug::bridge::UGError_ClassCastFailed::m_to, ug::bridge::IExportedClass::name(), ug::vrl::param2JObject(), ug::bridge::ExportedFunctionBase::params_in(), ug::bridge::ParameterInfo::size(), ug::vrl::stringJ2C(), ug::vrl::throwUgErrorAsJavaException(), UG_LOG, and ug::vrl::vrlRegistry.
Java_edu_gcsc_vrl_ug_UG__1newInstance()
JNIEXPORT jobject JNICALL Java_edu_gcsc_vrl_ug_UG__1newInstance (JNIEnv * env, jobject obj, jlong exportedClassPointer, jobjectArray params)
References ug::bridge::IExportedClass::construct_as_smart_pointer(), ug::bridge::ExportedConstructor::create(), EMPHASIZE_BEGIN, EMPHASIZE_END, ex, ug::bridge::IExportedClass::get_delete_function(), ug::vrl::invocation::getConstructorBySignature(), ug::vrl::getParamTypesAsString(), ug::vrl::jobjectArray2ParamStack(), ug::bridge::UGError_ClassCastFailed::m_from, ug::bridge::UGError_ClassCastFailed::m_to, ug::bridge::IExportedClass::name(), ug::bridge::ExportedConstructor::params_in(), ug::vrl::pointer2JObject(), ug::vrl::smartPointer2JObject(), ug::vrl::throwUgErrorAsJavaException(), and ug::vrl::vrlRegistry.
Java_edu_gcsc_vrl_ug_UG__1ugInit()
JNIEXPORT jint JNICALL Java_edu_gcsc_vrl_ug_UG__1ugInit (JNIEnv * env, jclass cls, jobjectArray args)
References ug::bridge::Registry::check_consistency(), ug::LogAssistant::flush_error_log(), ug::GetLogAssistant(), ug::bridge::GetUGRegistry(), ug::vrl::invocation::initClasses(), ug::vrl::initJavaVM(), ug::PLUGIN_PATH, ug::vrl::RegisterVRLFunctionality(), ug::PathProvider::set_path(), ug::vrl::SetVRLRegistry(), ug::vrl::stringArrayJ2C(), UG_LOG, ug::UGInit(), and ug::vrl::vrlRegistry.