ug4: ugbase/lib_algebra/interface/blas_mat_interface.h File Reference
blas_mat_interface.h File Reference
Functions
template<typename vector_t , typename matrix_t >
bool MatMult (vector_t &dest, const matrix_t &A1, const vector_t &w1)
calculates dest = A1 * w1;
template<typename vector_t , typename matrix_t >
bool MatMultAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const matrix_t &A1, const vector_t &w1)
calculates dest = alpha1*v1 + beta1 * A1 *w1;
template<typename vector_t , typename matrix_t >
bool MatMultAddRow (typename vector_t::value_type &dest, const number &alpha1, const vector_t &v1, const number &beta1, const matrix_t &A1, const vector_t &w1)
calculates dest += beta1 * A1[row] *w1;
template<typename vector_t , typename matrix_t >
bool MatMultAppend (vector_t &dest, const matrix_t &A1, const vector_t &w1)
calculates dest += A1*w1
template<typename vector_t , typename matrix_t >
bool MatMultScale (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1)
calculates dest = beta1 * A1 * w1;
template<typename vector_t , typename matrix_t >
bool MatMultScaleTransposed (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1)
calculates dest = beta1 * A1^T *w1;
template<typename vector_t , typename matrix_t >
bool MatMultScaleTransposed (vector_t &dest, const matrix_t &A1, const vector_t &w1)
calculates dest = A1^T *w1;
template<typename vector_t , typename matrix_t >
bool MatMultTransposedScaledAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const matrix_t &A1, const vector_t &w1)
calculates dest = alpha1*v1 + beta1 * A1^T *w1;
Function Documentation
MatMult()
template<typename vector_t , typename matrix_t > bool MatMult (vector_t & dest, const matrix_t & A1, const vector_t & w1) inline
calculates dest = A1 * w1;
Referenced by ug::ActiveSet< TDomain, TAlgebra >::check_inequ(), and ug::ActiveSet< TDomain, TAlgebra >::residual_lagrange_mult().
MatMultAdd()
template<typename vector_t , typename matrix_t > bool MatMultAdd (vector_t & dest, const number & alpha1, const vector_t & v1, const number & beta1, const matrix_t & A1, const vector_t & w1) inline
calculates dest = alpha1*v1 + beta1 * A1 *w1;
References ug::MatMultAdd().
Referenced by ug::ComponentGaussSeidel< TDomain, TAlgebra >::apply_blocks(), ug::ComponentGaussSeidel< TDomain, TAlgebra >::apply_blocks_weighted(), ug::SparseMatrix< TValueType >::apply_ignore_zero_rows(), ug::ILUTPreconditioner< ug::CPUAlgebra >::applyLU(), ug::MapSparseMatrix< TValueType >::axpy(), ug::SparseMatrix< TValueType >::axpy(), ug::AxpyCommonSparseMatrix(), ug::backward_gs_step(), ug::Diag_Vanka_step(), ug::ElementGaussSeidelStep(), ug::LocalIndexSubspace< TDomain, TAlgebra, Vertex >::extract_rhs(), ug::LocalDoFSubspace< TDomain, TAlgebra, Vertex >::extract_rhs(), ug::forward_gs_step(), ug::gs_step_LL(), ug::gs_step_UR(), ug::invert_L(), ug::invert_U(), ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), ug::LineVanka< TDomain, TAlgebra >::linevanka_step(), ug::MapSparseMatrix< TValueType >::mat_mult_add_row(), ug::SparseMatrix< TValueType >::mat_mult_add_row(), ug::GPUSparseMatrix< TValueType >::mat_mult_add_row(), ug::MatMult(), MatMultAdd(), ug::MatMultAdd(), ug::MatMultAddDirect(), MatMultAddRow(), ug::ILUTPreconditioner< ug::CPUAlgebra >::multi_apply(), ug::PILUTPreconditioner< TAlgebra >::step(), ug::Vanka_step(), and ug::VectorAssign().
MatMultAddRow()
template<typename vector_t , typename matrix_t > bool MatMultAddRow (typename vector_t::value_type & dest, const number & alpha1, const vector_t & v1, const number & beta1, const matrix_t & A1, const vector_t & w1) inline
calculates dest += beta1 * A1[row] *w1;
References MatMultAdd().
MatMultAppend()
template<typename vector_t , typename matrix_t > bool MatMultAppend (vector_t & dest, const matrix_t & A1, const vector_t & w1) inline
calculates dest += A1*w1
MatMultScale()
template<typename vector_t , typename matrix_t > bool MatMultScale (vector_t & dest, const number & beta1, const matrix_t & A1, const vector_t & w1) inline
calculates dest = beta1 * A1 * w1;
MatMultScaleTransposed() [1/2]
template<typename vector_t , typename matrix_t > bool MatMultScaleTransposed (vector_t & dest, const number & beta1, const matrix_t & A1, const vector_t & w1) inline
calculates dest = beta1 * A1^T *w1;
MatMultScaleTransposed() [2/2]
template<typename vector_t , typename matrix_t > bool MatMultScaleTransposed (vector_t & dest, const matrix_t & A1, const vector_t & w1) inline
calculates dest = A1^T *w1;
MatMultTransposedScaledAdd()
template<typename vector_t , typename matrix_t > bool MatMultTransposedScaledAdd (vector_t & dest, const number & alpha1, const vector_t & v1, const number & beta1, const matrix_t & A1, const vector_t & w1) inline
calculates dest = alpha1*v1 + beta1 * A1^T *w1;
References ug::MatMultTransposedAdd().