ug4: ugbase/lib_algebra/interface/blas_vec_interface.h File Reference
blas_vec_interface.h File Reference
Functions
template<typename vector_t >
void VecAdd (vector_t &dest, vector_t &v)
calculates dest = dest + v
template<typename vector_t >
void VecAssign (vector_t &dest, const vector_t &v1)
calculates dest = v1
template<typename vector_t >
double VecNormSquared (const vector_t &a, const vector_t &b)
returns norm_2^2(a)
template<typename vector_t >
void VecNormSquaredAdd (const vector_t &a, const vector_t &b, double &sum)
calculates s += norm_2^2(a)
template<typename vector_t >
double VecProd (const vector_t &a, const vector_t &b)
returns scal<a, b>
template<typename vector_t >
void VecProdAdd (const vector_t &a, const vector_t &b, double &sum)
calculates s += scal<a, b>
template<typename vector_t >
void VecScaleAdd (vector_t &dest, double alpha1, const vector_t &v1, double alpha2, const vector_t &v2)
calculates dest = alpha1*v1 + alpha2*v2
template<typename vector_t >
void VecScaleAdd (vector_t &dest, double alpha1, const vector_t &v1, double alpha2, const vector_t &v2, double alpha3, const vector_t &v3)
calculates dest = alpha1*v1 + alpha2*v2 + alpha3*v3
void VecScaleAssign (double &dest, double alpha1, const double &v1)
calculates dest = alpha1*v1. for doubles
template<typename vector_t >
void VecScaleAssign (vector_t &dest, double alpha1, const vector_t &v1)
calculates dest = alpha1*v1
template<typename vector_t >
void VecSubstract (vector_t &dest, vector_t &v)
calculates dest = dest - v
Function Documentation
VecAdd()
template<typename vector_t > void VecAdd (vector_t & dest, vector_t & v) inline
calculates dest = dest + v
VecAssign()
template<typename vector_t > void VecAssign (vector_t & dest, const vector_t & v1) inline
calculates dest = v1
VecNormSquared()
template<typename vector_t > double VecNormSquared (const vector_t & a, const vector_t & b) inline
returns norm_2^2(a)
References VecNormSquaredAdd().
VecNormSquaredAdd()
template<typename vector_t > void VecNormSquaredAdd (const vector_t & a, const vector_t & b, double & sum) inline
calculates s += norm_2^2(a)
Referenced by VecNormSquared().
VecProd()
template<typename vector_t > double VecProd (const vector_t & a, const vector_t & b) inline
returns scal<a, b>
References VecProdAdd().
VecProdAdd()
template<typename vector_t > void VecProdAdd (const vector_t & a, const vector_t & b, double & sum) inline
calculates s += scal<a, b>
Referenced by VecProd().
VecScaleAdd() [1/2]
template<typename vector_t > void VecScaleAdd (vector_t & dest, double alpha1, const vector_t & v1, double alpha2, const vector_t & v2) inline
calculates dest = alpha1*v1 + alpha2*v2
VecScaleAdd() [2/2]
template<typename vector_t > void VecScaleAdd (vector_t & dest, double alpha1, const vector_t & v1, double alpha2, const vector_t & v2, double alpha3, const vector_t & v3) inline
calculates dest = alpha1*v1 + alpha2*v2 + alpha3*v3
VecScaleAssign() [1/2]
void VecScaleAssign (double & dest, double alpha1, const double & v1) inline
calculates dest = alpha1*v1. for doubles
Referenced by VecScaleAssign().
VecScaleAssign() [2/2]
template<typename vector_t > void VecScaleAssign (vector_t & dest, double alpha1, const vector_t & v1) inline
calculates dest = alpha1*v1
References VecScaleAssign().
VecSubstract()
template<typename vector_t > void VecSubstract (vector_t & dest, vector_t & v) inline
calculates dest = dest - v