ug4: ug::PrismDescriptor Class Reference
ug::PrismDescriptor Class Reference
only used to initialize a prism. for all other tasks you should use VolumeDescripor.
#include <grid_objects_3d.h>
Public Member Functions
uint num_vertices () const
PrismDescriptor ()
PrismDescriptor (const PrismDescriptor &td)
PrismDescriptor (const VolumeVertices &vv)
PrismDescriptor (Vertex *v1, Vertex *v2, Vertex *v3, Vertex *v4, Vertex *v5, Vertex *v6)
Vertex * vertex (size_t index) const
Protected Attributes
Vertex * m_vertex [6]
Detailed Description
only used to initialize a prism. for all other tasks you should use VolumeDescripor.
please be sure to pass the vertices in the correct order: v1, v2, v3: bottom-vertices in counterclockwise order (if viewed from the top). v4, v5, v6: top-vertices in counterclockwise order (if viewed from the top).
Constructor & Destructor Documentation
PrismDescriptor() [1/4]
ug::PrismDescriptor::PrismDescriptor () inline
PrismDescriptor() [2/4]
ug::PrismDescriptor::PrismDescriptor (const PrismDescriptor & td)
References vertex().
PrismDescriptor() [3/4]
ug::PrismDescriptor::PrismDescriptor (const VolumeVertices & vv)
References ug::VolumeVertices::num_vertices(), and ug::VolumeVertices::vertex().
PrismDescriptor() [4/4]
ug::PrismDescriptor::PrismDescriptor (Vertex * v1, Vertex * v2, Vertex * v3, Vertex * v4, Vertex * v5, Vertex * v6)
Member Function Documentation
num_vertices()
uint ug::PrismDescriptor::num_vertices () const inline
vertex()
Vertex* ug::PrismDescriptor::vertex (size_t index) const inline
Referenced by ug::Prism::Prism(), and PrismDescriptor().
Member Data Documentation
m_vertex
Vertex* ug::PrismDescriptor::m_vertex[6] protected
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid_objects/grid_objects_3d.h
ugbase/lib_grid/grid_objects/grid_objects_3d.cpp