ug4: FreqAdaptValues Class Reference
FreqAdaptValues Class Reference
#include <freq_adapt.h>
Classes
struct FreqAdaptPoint
Static Public Member Functions
static void adjust_freq (unsigned long freq)
static unsigned long freq (const char *file, const int line)
static void set_freqs (std::string csvFile)
Static Protected Member Functions
static void * freqAdaptWorker (void *This)
Static Protected Attributes
static pthread_cond_t freqAdapt_condVar = pthread_cond_t()
static pthread_mutex_t freqAdapt_mutex = pthread_mutex_t()
static pthread_t freqAdaptWorkerThread = pthread_t()
static pthread_attr_t freqAdaptWorkerThreadAttr = pthread_attr_t()
static unsigned long newFreq = 0
static cpu_set_t processor_mask = cpu_set_t()
Private Member Functions
unsigned long find_freq (const char *file, const int line)
FreqAdaptValues ()
FreqAdaptValues (const FreqAdaptValues &)
FreqAdaptValues & operator= (const FreqAdaptValues &)
~FreqAdaptValues ()
Static Private Member Functions
static FreqAdaptValues & inst ()
Static Private Attributes
static std::vector< FreqAdaptPoint > m_pos
Friends
class AutoFreqAdaptNode
Constructor & Destructor Documentation
FreqAdaptValues() [1/2]
FreqAdaptValues::FreqAdaptValues () inline private
FreqAdaptValues() [2/2]
FreqAdaptValues::FreqAdaptValues (const FreqAdaptValues &) private
~FreqAdaptValues()
FreqAdaptValues::~FreqAdaptValues () inline private
Member Function Documentation
adjust_freq()
void FreqAdaptValues::adjust_freq (unsigned long freq) static
References freq(), freqAdapt_condVar, freqAdapt_mutex, newFreq, and UG_THROW.
Referenced by AutoFreqAdaptNode::AutoFreqAdaptNode(), and AutoFreqAdaptNode::release().
find_freq()
unsigned long FreqAdaptValues::find_freq (const char * file, const int line) private
References m_pos.
Referenced by freq().
freq()
static unsigned long FreqAdaptValues::freq (const char * file, const int line) inline static
References find_freq(), and inst().
Referenced by adjust_freq(), freqAdaptWorker(), and set_freqs().
freqAdaptWorker()
void * FreqAdaptValues::freqAdaptWorker (void * This) static protected
References freq(), freqAdapt_condVar, freqAdapt_mutex, newFreq, and UG_THROW.
Referenced by set_freqs().
inst()
FreqAdaptValues & FreqAdaptValues::inst () static private
Referenced by freq().
operator=()
FreqAdaptValues& FreqAdaptValues::operator= (const FreqAdaptValues &) private
set_freqs()
void FreqAdaptValues::set_freqs (std::string csvFile) static
References freq(), freqAdapt_condVar, freqAdapt_mutex, freqAdaptWorker(), freqAdaptWorkerThread, freqAdaptWorkerThreadAttr, m_pos, newFreq, processor_mask, ug::TrimString(), and UG_THROW.
Referenced by ug::SetFrequency().
Friends And Related Function Documentation
AutoFreqAdaptNode
friend class AutoFreqAdaptNode friend
Member Data Documentation
freqAdapt_condVar
pthread_cond_t FreqAdaptValues::freqAdapt_condVar = pthread_cond_t() static protected
Referenced by adjust_freq(), freqAdaptWorker(), and set_freqs().
freqAdapt_mutex
pthread_mutex_t FreqAdaptValues::freqAdapt_mutex = pthread_mutex_t() static protected
Referenced by adjust_freq(), freqAdaptWorker(), and set_freqs().
freqAdaptWorkerThread
pthread_t FreqAdaptValues::freqAdaptWorkerThread = pthread_t() static protected
Referenced by set_freqs().
freqAdaptWorkerThreadAttr
pthread_attr_t FreqAdaptValues::freqAdaptWorkerThreadAttr = pthread_attr_t() static protected
Referenced by set_freqs().
m_pos
std::vector< FreqAdaptValues::FreqAdaptPoint > FreqAdaptValues::m_pos static private
Initial value:
=
    std::vector<FreqAdaptValues::FreqAdaptPoint>()
Referenced by find_freq(), and set_freqs().
newFreq
unsigned long FreqAdaptValues::newFreq = 0 static protected
Referenced by adjust_freq(), AutoFreqAdaptNode::AutoFreqAdaptNode(), freqAdaptWorker(), and set_freqs().
processor_mask
cpu_set_t FreqAdaptValues::processor_mask = cpu_set_t() static protected
Referenced by set_freqs().
The documentation for this class was generated from the following files:
ugbase/common/profiler/freq_adapt.h
ugbase/common/profiler/freq_adapt.cpp