ug4: ug::SCCOrdering< TAlgebra, O_t > Class Template Reference
ug::SCCOrdering< TAlgebra, O_t > Class Template Reference
Public Types
typedef boost::graph_traits< G_t >::adjacency_iterator adj_iter
typedef IOrderingAlgorithm< TAlgebra, O_t > baseclass
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::directedS > G_t
typedef boost::graph_traits< G_t >::in_edge_iterator inedge_iter
typedef TAlgebra::matrix_type M_t
typedef boost::graph_traits< G_t >::adjacency_iterator nIt_t
typedef IOrderingAlgorithm< TAlgebra, ordering_container_type > ordering_algo_type
typedef std::vector< size_t > ordering_container_type
typedef TAlgebra::vector_type V_t
typedef boost::graph_traits< G_t >::vertex_descriptor vd_t
typedef boost::graph_traits< G_t >::vertex_iterator vIt_t
Public Types inherited from ug::IOrderingAlgorithm< TAlgebra, O_t >
typedef TAlgebra::matrix_type M_t
typedef TAlgebra::vector_type V_t
Public Member Functions
void check ()
SmartPtr< IOrderingAlgorithm< TAlgebra, O_t > > clone ()
void compute ()
void init (M_t *, const O_t &)
void init (M_t *, const V_t &, const O_t &)
void init (M_t *A)
void init (M_t *A, const V_t &)
virtual const char * name () const
O_t & ordering ()
SCCOrdering ()
SCCOrdering (const SCCOrdering< TAlgebra, O_t > &parent)
clone constructor
void set_ordering_subalgorithm (SmartPtr< ordering_algo_type > ordering_subalgo)
sets an ordering algorithm
Public Member Functions inherited from ug::IOrderingAlgorithm< TAlgebra, O_t >
virtual void init (M_t *, const std::vector< size_t > &)=0
virtual void init (M_t *, const V_t &, const std::vector< size_t > &)=0
IOrderingAlgorithm ()
virtual ~IOrderingAlgorithm ()
Private Attributes
G_t g
M_t * m
SmartPtr< ordering_algo_type > m_spOrderingSubAlgo
O_t o
G_t scc_g
Member Typedef Documentation
adj_iter
template<typename TAlgebra , typename O_t > typedef boost::graph_traits<G_t>::adjacency_iterator ug::SCCOrdering< TAlgebra, O_t >::adj_iter
baseclass
template<typename TAlgebra , typename O_t > typedef IOrderingAlgorithm<TAlgebra, O_t> ug::SCCOrdering< TAlgebra, O_t >::baseclass
G_t
template<typename TAlgebra , typename O_t > typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::directedS> ug::SCCOrdering< TAlgebra, O_t >::G_t
inedge_iter
template<typename TAlgebra , typename O_t > typedef boost::graph_traits<G_t>::in_edge_iterator ug::SCCOrdering< TAlgebra, O_t >::inedge_iter
M_t
template<typename TAlgebra , typename O_t > typedef TAlgebra::matrix_type ug::SCCOrdering< TAlgebra, O_t >::M_t
nIt_t
template<typename TAlgebra , typename O_t > typedef boost::graph_traits<G_t>::adjacency_iterator ug::SCCOrdering< TAlgebra, O_t >::nIt_t
ordering_algo_type
template<typename TAlgebra , typename O_t > typedef IOrderingAlgorithm<TAlgebra, ordering_container_type> ug::SCCOrdering< TAlgebra, O_t >::ordering_algo_type
ordering_container_type
template<typename TAlgebra , typename O_t > typedef std::vector<size_t> ug::SCCOrdering< TAlgebra, O_t >::ordering_container_type
V_t
template<typename TAlgebra , typename O_t > typedef TAlgebra::vector_type ug::SCCOrdering< TAlgebra, O_t >::V_t
vd_t
template<typename TAlgebra , typename O_t > typedef boost::graph_traits<G_t>::vertex_descriptor ug::SCCOrdering< TAlgebra, O_t >::vd_t
vIt_t
template<typename TAlgebra , typename O_t > typedef boost::graph_traits<G_t>::vertex_iterator ug::SCCOrdering< TAlgebra, O_t >::vIt_t
Constructor & Destructor Documentation
SCCOrdering() [1/2]
template<typename TAlgebra , typename O_t > ug::SCCOrdering< TAlgebra, O_t >::SCCOrdering () inline
SCCOrdering() [2/2]
template<typename TAlgebra , typename O_t > ug::SCCOrdering< TAlgebra, O_t >::SCCOrdering (const SCCOrdering< TAlgebra, O_t > & parent) inline
clone constructor
Member Function Documentation
check()
template<typename TAlgebra , typename O_t > void ug::SCCOrdering< TAlgebra, O_t >::check () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::is_permutation(), ug::SCCOrdering< TAlgebra, O_t >::name(), ug::SCCOrdering< TAlgebra, O_t >::o, and UG_COND_THROW.
Referenced by ug::SCCOrdering< TAlgebra, O_t >::compute().
clone()
template<typename TAlgebra , typename O_t > SmartPtr<IOrderingAlgorithm<TAlgebra, O_t> > ug::SCCOrdering< TAlgebra, O_t >::clone () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References make_sp().
compute()
template<typename TAlgebra , typename O_t > void ug::SCCOrdering< TAlgebra, O_t >::compute () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References boost::adjacent_vertices(), ug::SCCOrdering< TAlgebra, O_t >::check(), ug::SCCOrdering< TAlgebra, O_t >::g, boost::get(), ug::GetInversePermutation(), ug::SCCOrdering< TAlgebra, O_t >::m, ug::SCCOrdering< TAlgebra, O_t >::m_spOrderingSubAlgo, ug::SCCOrdering< TAlgebra, O_t >::name(), boost::num_vertices(), ug::SCCOrdering< TAlgebra, O_t >::o, ug::SCCOrdering< TAlgebra, O_t >::scc_g, ug::topological_ordering_core_directed(), UG_COND_THROW, UG_LOG, and UG_THROW.
init() [1/4]
template<typename TAlgebra , typename O_t > void ug::SCCOrdering< TAlgebra, O_t >::init (M_t * , const O_t &) inline
References ug::SCCOrdering< TAlgebra, O_t >::name(), and UG_THROW.
init() [2/4]
template<typename TAlgebra , typename O_t > void ug::SCCOrdering< TAlgebra, O_t >::init (M_t * , const V_t & , const O_t &) inline
References ug::SCCOrdering< TAlgebra, O_t >::name(), and UG_THROW.
init() [3/4]
template<typename TAlgebra , typename O_t > void ug::SCCOrdering< TAlgebra, O_t >::init (M_t * A) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::SCCOrdering< TAlgebra, O_t >::g, ug::SCCOrdering< TAlgebra, O_t >::m, ug::SCCOrdering< TAlgebra, O_t >::name(), and UG_LOG.
init() [4/4]
template<typename TAlgebra , typename O_t > void ug::SCCOrdering< TAlgebra, O_t >::init (M_t * A, const V_t &) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
name()
template<typename TAlgebra , typename O_t > virtual const char* ug::SCCOrdering< TAlgebra, O_t >::name () const inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
Referenced by ug::SCCOrdering< TAlgebra, O_t >::check(), ug::SCCOrdering< TAlgebra, O_t >::compute(), and ug::SCCOrdering< TAlgebra, O_t >::init().
ordering()
template<typename TAlgebra , typename O_t > O_t& ug::SCCOrdering< TAlgebra, O_t >::ordering () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::SCCOrdering< TAlgebra, O_t >::o.
set_ordering_subalgorithm()
template<typename TAlgebra , typename O_t > void ug::SCCOrdering< TAlgebra, O_t >::set_ordering_subalgorithm (SmartPtr< ordering_algo_type > ordering_subalgo) inline
sets an ordering algorithm
References ug::SCCOrdering< TAlgebra, O_t >::m_spOrderingSubAlgo.
Member Data Documentation
g
template<typename TAlgebra , typename O_t > G_t ug::SCCOrdering< TAlgebra, O_t >::g private
Referenced by ug::SCCOrdering< TAlgebra, O_t >::compute(), and ug::SCCOrdering< TAlgebra, O_t >::init().
m
template<typename TAlgebra , typename O_t > M_t* ug::SCCOrdering< TAlgebra, O_t >::m private
Referenced by ug::SCCOrdering< TAlgebra, O_t >::compute(), and ug::SCCOrdering< TAlgebra, O_t >::init().
m_spOrderingSubAlgo
template<typename TAlgebra , typename O_t > SmartPtr<ordering_algo_type> ug::SCCOrdering< TAlgebra, O_t >::m_spOrderingSubAlgo private
Referenced by ug::SCCOrdering< TAlgebra, O_t >::compute(), and ug::SCCOrdering< TAlgebra, O_t >::set_ordering_subalgorithm().
o
template<typename TAlgebra , typename O_t > O_t ug::SCCOrdering< TAlgebra, O_t >::o private
Referenced by ug::SCCOrdering< TAlgebra, O_t >::check(), ug::SCCOrdering< TAlgebra, O_t >::compute(), and ug::SCCOrdering< TAlgebra, O_t >::ordering().
scc_g
template<typename TAlgebra , typename O_t > G_t ug::SCCOrdering< TAlgebra, O_t >::scc_g private
Referenced by ug::SCCOrdering< TAlgebra, O_t >::compute().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/ordering_strategies/algorithms/SCC_ordering.cpp