ug4: ug::bridge::ParameterInfo Class Reference
ug::bridge::ParameterInfo Class Reference
ugbase » Bridge » Registry
a stack holding parameter infos about a parameter stack
#include <parameter_stack.h>
Classes
struct EntryType
structure to store a data entry with additional information
struct PushType
struct PushType< bool >
struct PushType< const char * >
struct PushType< const std::string & >
struct PushType< const std::vector< bool > & >
struct PushType< const std::vector< const char * > & >
struct PushType< const std::vector< const TClass * > & >
struct PushType< const std::vector< ConstSmartPtr< TClass > > & >
struct PushType< const std::vector< double > & >
struct PushType< const std::vector< float > & >
struct PushType< const std::vector< int > & >
struct PushType< const std::vector< size_t > & >
struct PushType< const std::vector< SmartPtr< TClass > > & >
struct PushType< const std::vector< std::string > & >
struct PushType< const std::vector< TClass * > & >
struct PushType< const TClass & >
struct PushType< const TClass * >
struct PushType< ConstSmartPtr< TClass > >
struct PushType< double >
struct PushType< float >
struct PushType< int >
struct PushType< size_t >
struct PushType< SmartPtr< TClass > >
struct PushType< std::string >
struct PushType< std::vector< bool > >
struct PushType< std::vector< const char * > >
struct PushType< std::vector< const TClass * > >
struct PushType< std::vector< ConstSmartPtr< TClass > > >
struct PushType< std::vector< double > >
struct PushType< std::vector< float > >
struct PushType< std::vector< int > >
struct PushType< std::vector< size_t > >
struct PushType< std::vector< SmartPtr< TClass > > >
struct PushType< std::vector< std::string > >
struct PushType< std::vector< TClass * > >
struct PushType< TClass & >
struct PushType< TClass * >
Public Member Functions
const char * class_name (int index) const
returns the class name for an element in the param stack
const ClassNameNode * class_name_node (int index) const
returns the class name node for an element in the param stack
bool is_vector (int index) const
returns if index is a std::vector
bool parameter_named (int index) const
returns true if a parameter of the stack has been named by user
ParameterInfo ()
default constructor
template<typename T >
void push_type ()
pushes a type to the parameter stack
int size () const
returns number of parameters in the param stack
Variant::Type type (int index) const
returns ParameterType enum of data type for a stack entry
Protected Member Functions
template<typename TType , typename TNode >
void _push_type ()
template<typename TNative >
void _push_type ()
template<typename TType , typename TNode >
void _push_vector_type ()
template<typename TNative >
void _push_vector_type ()
Static Protected Member Functions
static int ARRAY_INDEX_TO_STACK_INDEX (int index, int stackSize)
help function to compute correct parameter index
Protected Attributes
int m_numEntries
number of currently stored entries
EntryType m_vEntryType [PARAMETER_STACK_MAX_SIZE]
Static Protected Attributes
static const int PARAMETER_STACK_MAX_SIZE = UG_REGISTRY_MAX_NUM_ARGS
maximal number of parameter in a parameter list
Detailed Description
a stack holding parameter infos about a parameter stack
This class is used to store type informations about the entries in a parameter list.
Note that the maximal number of parameters is specified by the constant PARAMETER_STACK_MAX_SIZE. Please note, that this value should not be unnecessarily high. The appropriate choice is UG_REGISTRY_MAX_NUM_ARGS, since the template-method-wrappers can't take any more parameters.
Supported types are bool, integer, number, const char*, std::string, reference, pointer and smart-pointer. References and pointers are stored in a void*. The user is responsible to associate the correct types.
Constructor & Destructor Documentation
ParameterInfo()
ug::bridge::ParameterInfo::ParameterInfo () inline
default constructor
Member Function Documentation
_push_type() [1/2]
template<typename TType , typename TNode > void ug::bridge::ParameterInfo::_push_type () inline protected
References ug::bridge::ParameterInfo::EntryType::bVector, ug::bridge::ClassNameProvider< TClass >::class_name_node(), m_numEntries, m_vEntryType, ug::bridge::ParameterInfo::EntryType::pClassNameNode, and ug::bridge::ParameterInfo::EntryType::type.
Referenced by ug::bridge::ParameterInfo::PushType< bool >::push(), ug::bridge::ParameterInfo::PushType< int >::push(), ug::bridge::ParameterInfo::PushType< size_t >::push(), ug::bridge::ParameterInfo::PushType< float >::push(), ug::bridge::ParameterInfo::PushType< double >::push(), ug::bridge::ParameterInfo::PushType< const char * >::push(), ug::bridge::ParameterInfo::PushType< std::string >::push(), ug::bridge::ParameterInfo::PushType< const std::string & >::push(), ug::bridge::ParameterInfo::PushType< TClass * >::push(), ug::bridge::ParameterInfo::PushType< const TClass * >::push(), ug::bridge::ParameterInfo::PushType< TClass & >::push(), ug::bridge::ParameterInfo::PushType< const TClass & >::push(), ug::bridge::ParameterInfo::PushType< SmartPtr< TClass > >::push(), and ug::bridge::ParameterInfo::PushType< ConstSmartPtr< TClass > >::push().
_push_type() [2/2]
template<typename TNative > void ug::bridge::ParameterInfo::_push_type () inline protected
_push_vector_type() [1/2]
template<typename TType , typename TNode > void ug::bridge::ParameterInfo::_push_vector_type () inline protected
References ug::bridge::ParameterInfo::EntryType::bVector, ug::bridge::ClassNameProvider< TClass >::class_name_node(), m_numEntries, m_vEntryType, ug::bridge::ParameterInfo::EntryType::pClassNameNode, and ug::bridge::ParameterInfo::EntryType::type.
Referenced by ug::bridge::ParameterInfo::PushType< std::vector< bool > >::push(), ug::bridge::ParameterInfo::PushType< std::vector< int > >::push(), ug::bridge::ParameterInfo::PushType< std::vector< size_t > >::push(), ug::bridge::ParameterInfo::PushType< std::vector< float > >::push(), ug::bridge::ParameterInfo::PushType< std::vector< double > >::push(), ug::bridge::ParameterInfo::PushType< std::vector< const char * > >::push(), ug::bridge::ParameterInfo::PushType< std::vector< std::string > >::push(), ug::bridge::ParameterInfo::PushType< const std::vector< bool > & >::push(), ug::bridge::ParameterInfo::PushType< const std::vector< int > & >::push(), ug::bridge::ParameterInfo::PushType< const std::vector< size_t > & >::push(), ug::bridge::ParameterInfo::PushType< const std::vector< float > & >::push(), ug::bridge::ParameterInfo::PushType< const std::vector< double > & >::push(), ug::bridge::ParameterInfo::PushType< const std::vector< const char * > & >::push(), ug::bridge::ParameterInfo::PushType< const std::vector< std::string > & >::push(), ug::bridge::ParameterInfo::PushType< std::vector< TClass * > >::push(), ug::bridge::ParameterInfo::PushType< const std::vector< TClass * > & >::push(), ug::bridge::ParameterInfo::PushType< std::vector< const TClass * > >::push(), ug::bridge::ParameterInfo::PushType< const std::vector< const TClass * > & >::push(), ug::bridge::ParameterInfo::PushType< std::vector< SmartPtr< TClass > > >::push(), ug::bridge::ParameterInfo::PushType< const std::vector< SmartPtr< TClass > > & >::push(), ug::bridge::ParameterInfo::PushType< std::vector< ConstSmartPtr< TClass > > >::push(), and ug::bridge::ParameterInfo::PushType< const std::vector< ConstSmartPtr< TClass > > & >::push().
_push_vector_type() [2/2]
template<typename TNative > void ug::bridge::ParameterInfo::_push_vector_type () inline protected
ARRAY_INDEX_TO_STACK_INDEX()
static int ug::bridge::ParameterInfo::ARRAY_INDEX_TO_STACK_INDEX (int index, int stackSize) inline static protected
help function to compute correct parameter index
References UG_THROW.
Referenced by ug::bridge::ParameterStack::_to_native(), ug::bridge::ParameterStack::_to_native_vector(), ug::bridge::ParameterStack::_to_pointer(), ug::bridge::ParameterStack::_to_pointer_vector(), ug::bridge::ParameterStack::_to_void_pointer_vector(), class_name_node(), is_vector(), and type().
class_name()
const char* ug::bridge::ParameterInfo::class_name (int index) const inline
returns the class name for an element in the param stack
References class_name_node(), and ug::bridge::ClassNameNode::name().
Referenced by ug::vrl::compareParamTypes(), ug::bridge::IsClassInParameters(), ug::bridge::LuaStackToParams(), ug::bridge::ParameterToString(), ug::vrl::params2NativeParams(), ug::bridge::ParamStackPointerEntryToLuaStack(), ug::vrl::retVal2NativeParam(), and ug::bridge::WriteLUAObject2().
class_name_node()
const ClassNameNode* ug::bridge::ParameterInfo::class_name_node (int index) const inline
returns the class name node for an element in the param stack
References ARRAY_INDEX_TO_STACK_INDEX(), m_numEntries, m_vEntryType, ug::bridge::ParameterInfo::EntryType::pClassNameNode, and UG_THROW.
Referenced by class_name(), ug::bridge::IsClassInParameters(), parameter_named(), ug::vrl::params2NativeParams(), and ug::vrl::retVal2NativeParam().
is_vector()
bool ug::bridge::ParameterInfo::is_vector (int index) const inline
returns if index is a std::vector
References ARRAY_INDEX_TO_STACK_INDEX(), ug::bridge::ParameterInfo::EntryType::bVector, m_numEntries, and m_vEntryType.
Referenced by ug::vrl::compareParamTypes(), ug::vrl::jobjectArray2ParamStack(), ug::bridge::LuaStackToParams(), ug::vrl::param2JObject(), ug::bridge::ParameterToString(), ug::vrl::params2NativeParams(), ug::bridge::ParamsToLuaStack(), and ug::vrl::retVal2NativeParam().
parameter_named()
bool ug::bridge::ParameterInfo::parameter_named (int index) const inline
returns true if a parameter of the stack has been named by user
References class_name_node(), and ug::bridge::ClassNameNode::named().
Referenced by ug::bridge::ExportedConstructor::check_consistency(), and ug::bridge::ExportedFunctionBase::check_consistency().
push_type()
template<typename T > void ug::bridge::ParameterInfo::push_type () inline
pushes a type to the parameter stack
References ug::bridge::ParameterInfo::PushType< T >::push().
Referenced by ug::bridge::CreateParameterInfo< TTypeList >::create().
size()
int ug::bridge::ParameterInfo::size () const inline
returns number of parameters in the param stack
References m_numEntries.
Referenced by ug::bridge::ExportedConstructor::check_consistency(), ug::bridge::ExportedFunctionBase::check_consistency(), ug::vrl::compareParamTypes(), ug::bridge::lua::GetTypeMismatchString(), ug::bridge::IsClassInParameters(), Java_edu_gcsc_vrl_ug_UG__1invokeFunction(), Java_edu_gcsc_vrl_ug_UG__1invokeMethod(), ug::vrl::jobjectArray2ParamStack(), ug::bridge::LuaStackToParams(), ug::bridge::ParamsToLuaStack(), and ug::bridge::PrintParametersOut().
type()
Variant::Type ug::bridge::ParameterInfo::type (int index) const inline
returns ParameterType enum of data type for a stack entry
References ARRAY_INDEX_TO_STACK_INDEX(), m_numEntries, m_vEntryType, and ug::bridge::ParameterInfo::EntryType::type.
Referenced by ug::vrl::compareParamTypes(), ug::bridge::IsClassInParameters(), ug::vrl::jobjectArray2ParamStack(), ug::bridge::LuaStackToParams(), ug::vrl::param2JObject(), ug::bridge::ParameterToString(), ug::vrl::params2NativeParams(), ug::bridge::ParamsToLuaStack(), and ug::vrl::paramType2Int().
Member Data Documentation
m_numEntries
int ug::bridge::ParameterInfo::m_numEntries protected
number of currently stored entries
Referenced by ug::bridge::ParameterStack::_push_native(), ug::bridge::ParameterStack::_push_pointer(), _push_type(), ug::bridge::ParameterStack::_push_vector(), _push_vector_type(), ug::bridge::ParameterStack::_push_void_pointer(), ug::bridge::ParameterStack::_push_void_pointer_vector(), ug::bridge::ParameterStack::_to_native(), ug::bridge::ParameterStack::_to_native_vector(), ug::bridge::ParameterStack::_to_pointer(), ug::bridge::ParameterStack::_to_pointer_vector(), ug::bridge::ParameterStack::_to_void_pointer_vector(), class_name_node(), is_vector(), size(), and type().
m_vEntryType
EntryType ug::bridge::ParameterInfo::m_vEntryType[PARAMETER_STACK_MAX_SIZE] protected
Referenced by _push_type(), _push_vector_type(), ug::bridge::ParameterStack::_push_void_pointer(), ug::bridge::ParameterStack::_push_void_pointer_vector(), ug::bridge::ParameterStack::_to_pointer(), class_name_node(), is_vector(), and type().
PARAMETER_STACK_MAX_SIZE
const int ug::bridge::ParameterInfo::PARAMETER_STACK_MAX_SIZE = UG_REGISTRY_MAX_NUM_ARGS static protected
maximal number of parameter in a parameter list
The documentation for this class was generated from the following file:
ugbase/registry/parameter_stack.h