ug4: ug::StdLagrangeElemTransfer< TDomain > Class Template Reference
ug::StdLagrangeElemTransfer< TDomain > Class Template Reference
#include <local_transfer.h>
Public Member Functions
template<typename TElem >
void do_restrict (TElem *parent, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent)
virtual void do_restrict (Vertex *parent)
virtual bool perform_prolongation_on (GridBaseObjectId gbo)
virtual bool perform_restriction_on (GridBaseObjectId gbo)
template<typename TElem >
void prolongate (TElem *parent, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent)
template<typename TParent , typename TChild >
void prolongate (TParent *parent, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent, const LocalShapeFunctionSet< TParent::dim > &lsfs, const std::vector< MathVector< dim > > &vCornerParent, const ReferenceObjectID parentRoid)
virtual void prolongate (Vertex *parent)
StdLagrangeElemTransfer (const LFEID &lfeid)
Public Member Functions inherited from ug::ElemProlongationBase< TDomain, StdLagrangeElemTransfer< TDomain > >
virtual void prolongate (Edge *parent)
virtual void prolongate (Face *parent)
virtual void prolongate (Volume *parent)
Public Member Functions inherited from ug::IElemProlongation< TDomain >
virtual void init (ConstSmartPtr< TDomain > spDomain, SmartPtr< TransferValueAccessor > vValueChild, SmartPtr< TransferValueAccessor > vValueParent)
virtual ~IElemProlongation ()
Public Member Functions inherited from ug::ElemRestrictionBase< TDomain, StdLagrangeElemTransfer< TDomain > >
virtual void do_restrict (Edge *parent)
virtual void do_restrict (Face *parent)
virtual void do_restrict (Volume *parent)
Public Member Functions inherited from ug::IElemRestriction< TDomain >
virtual void init (ConstSmartPtr< TDomain > spDomain, SmartPtr< TransferValueAccessor > vValueChild, SmartPtr< TransferValueAccessor > vValueParent)
virtual ~IElemRestriction ()
Static Public Attributes
static const int dim = TDomain::dim
world dimension
Protected Attributes
LFEID m_lfeid
Protected Attributes inherited from ug::IElemProlongation< TDomain >
ConstSmartPtr< TDomain > m_spDomain
ConstSmartPtr< MultiGrid > m_spGrid
SmartPtr< TransferValueAccessor > m_vValueChild
SmartPtr< TransferValueAccessor > m_vValueParent
Protected Attributes inherited from ug::IElemRestriction< TDomain >
ConstSmartPtr< TDomain > m_spDomain
ConstSmartPtr< MultiGrid > m_spGrid
SmartPtr< TransferValueAccessor > m_vValueChild
SmartPtr< TransferValueAccessor > m_vValueParent
Additional Inherited Members
Protected Member Functions inherited from ug::ElemProlongationBase< TDomain, StdLagrangeElemTransfer< TDomain > >
StdLagrangeElemTransfer< TDomain > & getImpl ()
access to implementation
const StdLagrangeElemTransfer< TDomain > & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::ElemRestrictionBase< TDomain, StdLagrangeElemTransfer< TDomain > >
StdLagrangeElemTransfer< TDomain > & getImpl ()
access to implementation
const StdLagrangeElemTransfer< TDomain > & getImpl () const
const access to implementation
Constructor & Destructor Documentation
StdLagrangeElemTransfer()
template<typename TDomain > ug::StdLagrangeElemTransfer< TDomain >::StdLagrangeElemTransfer (const LFEID & lfeid) inline
Member Function Documentation
do_restrict() [1/2]
template<typename TDomain > template<typename TElem > void ug::StdLagrangeElemTransfer< TDomain >::do_restrict (TElem * parent, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent) inline
References ug::TransferValueAccessor::access_closure(), ug::TransferValueAccessor::access_inner(), ug::DoFPosition(), ug::MultiGrid::get_child(), ug::InnerDoFPosition(), ug::StdLagrangeElemTransfer< TDomain >::m_lfeid, ug::MultiGrid::num_children(), UG_THROW, and ug::VecDistanceSq().
do_restrict() [2/2]
template<typename TDomain > virtual void ug::StdLagrangeElemTransfer< TDomain >::do_restrict (Vertex * parent) inline virtual
Reimplemented from ug::ElemRestrictionBase< TDomain, StdLagrangeElemTransfer< TDomain > >.
References ug::TransferValueAccessor::access_inner(), ug::MultiGrid::get_child(), ug::MultiGrid::num_children(), and UG_THROW.
perform_prolongation_on()
template<typename TDomain > virtual bool ug::StdLagrangeElemTransfer< TDomain >::perform_prolongation_on (GridBaseObjectId gbo) inline virtual
Implements ug::IElemProlongation< TDomain >.
References ug::LFEID::dim(), ug::StdLagrangeElemTransfer< TDomain >::m_lfeid, ug::LFEID::order(), and ug::VERTEX.
perform_restriction_on()
template<typename TDomain > virtual bool ug::StdLagrangeElemTransfer< TDomain >::perform_restriction_on (GridBaseObjectId gbo) inline virtual
Implements ug::IElemRestriction< TDomain >.
References ug::LFEID::dim(), and ug::StdLagrangeElemTransfer< TDomain >::m_lfeid.
prolongate() [1/3]
template<typename TDomain > template<typename TElem > void ug::StdLagrangeElemTransfer< TDomain >::prolongate (TElem * parent, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent) inline
References ug::TransferValueAccessor::access_closure(), ug::CollectCornerCoordinates(), dim, ug::StdLagrangeElemTransfer< TDomain >::m_lfeid, and UG_THROW.
prolongate() [2/3]
template<typename TDomain > template<typename TParent , typename TChild > void ug::StdLagrangeElemTransfer< TDomain >::prolongate (TParent * parent, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent, const LocalShapeFunctionSet< TParent::dim > & lsfs, const std::vector< MathVector< dim > > & vCornerParent, const ReferenceObjectID parentRoid) inline
References ug::TransferValueAccessor::access_inner(), dim, ug::MultiGrid::get_child(), ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::InnerDoFPosition(), ug::StdLagrangeElemTransfer< TDomain >::m_lfeid, ug::MultiGrid::num_children(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), and ug::TransferValueAccessor::size().
prolongate() [3/3]
template<typename TDomain > virtual void ug::StdLagrangeElemTransfer< TDomain >::prolongate (Vertex * parent) inline virtual
Reimplemented from ug::ElemProlongationBase< TDomain, StdLagrangeElemTransfer< TDomain > >.
References ug::TransferValueAccessor::access_closure(), ug::TransferValueAccessor::access_inner(), ug::MultiGrid::get_child(), ug::MultiGrid::num_children(), and UG_THROW.
Member Data Documentation
dim
template<typename TDomain > const int ug::StdLagrangeElemTransfer< TDomain >::dim = TDomain::dim static
world dimension
m_lfeid
template<typename TDomain > LFEID ug::StdLagrangeElemTransfer< TDomain >::m_lfeid protected
Referenced by ug::StdLagrangeElemTransfer< TDomain >::do_restrict(), ug::StdLagrangeElemTransfer< TDomain >::perform_prolongation_on(), ug::StdLagrangeElemTransfer< TDomain >::perform_restriction_on(), and ug::StdLagrangeElemTransfer< TDomain >::prolongate().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/local_transfer.h