ug4: ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra > Class Template Reference
ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra > Class Template Reference
Public Member Functions
bool evaluate (const std::vector< number > &pos, number &result, SmartPtr< TGridFunction > u, number time)
number evaluateLua (const std::vector< number > &pos, SmartPtr< TGridFunction > u, number time)
NumberValuedUserDataEvaluator (SmartPtr< UserData< number, dim > > userData)
Private Types
typedef TGridFunction::template dim_traits< dim >::grid_base_object TElem
typedef GridFunction< TDomain, TAlgebra > TGridFunction
typedef lg_ntree< dim, dim, TElem > tree_t
Private Member Functions
bool evaluateOnThisProcess (const std::vector< number > &pos, number &result, SmartPtr< TGridFunction > u, number time)
void initialize (SmartPtr< TGridFunction > u)
Private Attributes
bool m_initialized = false
SmartPtr< tree_t > m_tree
SmartPtr< UserData< number, dim > > m_userData
Static Private Attributes
static const int dim = TDomain::dim
Member Typedef Documentation
TElem
template<typename TDomain , typename TAlgebra > typedef TGridFunction::template dim_traits<dim>::grid_base_object ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::TElem private
TGridFunction
template<typename TDomain , typename TAlgebra > typedef GridFunction<TDomain, TAlgebra> ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::TGridFunction private
tree_t
template<typename TDomain , typename TAlgebra > typedef lg_ntree<dim, dim, TElem> ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::tree_t private
Constructor & Destructor Documentation
NumberValuedUserDataEvaluator()
template<typename TDomain , typename TAlgebra > ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::NumberValuedUserDataEvaluator (SmartPtr< UserData< number, dim > > userData) inline
Member Function Documentation
evaluate()
template<typename TDomain , typename TAlgebra > bool ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::evaluate (const std::vector< number > & pos, number & result, SmartPtr< TGridFunction > u, number time) inline
References pcl::ProcessCommunicator::allreduce(), and PCL_RO_SUM.
evaluateLua()
template<typename TDomain , typename TAlgebra > number ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::evaluateLua (const std::vector< number > & pos, SmartPtr< TGridFunction > u, number time) inline
evaluateOnThisProcess()
template<typename TDomain , typename TAlgebra > bool ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::evaluateOnThisProcess (const std::vector< number > & pos, number & result, SmartPtr< TGridFunction > u, number time) inline private
References ug::CollectCornerCoordinates(), dim, ug::FindContainingElement(), ug::GetLocalVector(), ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::LocalVector::resize(), UG_CATCH_THROW, and ug::VecSet().
initialize()
template<typename TDomain , typename TAlgebra > void ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::initialize (SmartPtr< TGridFunction > u) inline private
References make_sp().
Member Data Documentation
dim
template<typename TDomain , typename TAlgebra > const int ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::dim = TDomain::dim static private
m_initialized
template<typename TDomain , typename TAlgebra > bool ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::m_initialized = false private
m_tree
template<typename TDomain , typename TAlgebra > SmartPtr<tree_t> ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::m_tree private
m_userData
template<typename TDomain , typename TAlgebra > SmartPtr<UserData<number, dim> > ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::m_userData private
The documentation for this class was generated from the following file:
ugbase/bridge/disc_bridges/evaluate_at_position_bridge.cpp