ug4: ug::SmoothProjector Class Reference
ug::SmoothProjector Class Reference
Smoothes vertices during refinement.
#include <smooth_projector.h>
Public Member Functions
number change_rate () const
int iterations () const
virtual number new_vertex (Vertex *vrt, Edge *parent)
called when a new vertex was created from an old edge.
virtual number new_vertex (Vertex *vrt, Face *parent)
called when a new vertex was created from an old face.
virtual number new_vertex (Vertex *vrt, Volume *parent)
called when a new vertex was created from an old volume.
virtual void refinement_begins (const ISubGrid *sg)
called before refinement begins
virtual void refinement_ends ()
called when refinement is done.
void set_change_rate (number changeRate)
void set_iterations (int iterations)
SmoothProjector ()
SmoothProjector (int iterations, number changeRate)
SmoothProjector (SPIGeometry3d geometry, int iterations, number changeRate)
Public Member Functions inherited from ug::RefinementProjector
virtual SPIGeometry3d geometry () const
virtual number new_vertex (Vertex *vrt, Vertex *parent)
called when a new vertex was created from an old vertex.
virtual bool refinement_begins_requires_subgrid () const
RefinementProjector ()
RefinementProjector (SPIGeometry3d geometry)
RefinementProjector (SPElementCallback cb)
RefinementProjector (SPIGeometry3d geometry, SPElementCallback concernedElems)
virtual void set_concerned_elements (SPElementCallback cb)
virtual void set_geometry (SPIGeometry3d geometry)
virtual ~RefinementProjector ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
number m_changeRate
int m_iterations
std::vector< Vertex * > m_newVrts
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from ug::RefinementProjector
IGeometry3d & geom ()
const IGeometry3d & geom () const
template<class TElem >
bool is_concerned (TElem *e)
vector3 pos (Vertex *v) const
void set_pos (Vertex *v, const vector3 &p)
Detailed Description
Smoothes vertices during refinement.
Constructor & Destructor Documentation
SmoothProjector() [1/3]
ug::SmoothProjector::SmoothProjector () inline
SmoothProjector() [2/3]
ug::SmoothProjector::SmoothProjector (int iterations, number changeRate) inline
SmoothProjector() [3/3]
ug::SmoothProjector::SmoothProjector (SPIGeometry3d geometry, int iterations, number changeRate) inline
See also
ug::RefinementProjector::RefinementProjector
Member Function Documentation
change_rate()
number ug::SmoothProjector::change_rate () const inline
References m_changeRate.
iterations()
int ug::SmoothProjector::iterations () const inline
References m_iterations.
Referenced by set_iterations().
new_vertex() [1/3]
virtual number ug::SmoothProjector::new_vertex (Vertex * vrt, Edge * parent) inline virtual
called when a new vertex was created from an old edge.
Reimplemented from ug::RefinementProjector.
References m_newVrts, and ug::RefinementProjector::new_vertex().
new_vertex() [2/3]
virtual number ug::SmoothProjector::new_vertex (Vertex * vrt, Face * parent) inline virtual
called when a new vertex was created from an old face.
Reimplemented from ug::RefinementProjector.
References m_newVrts, and ug::RefinementProjector::new_vertex().
new_vertex() [3/3]
virtual number ug::SmoothProjector::new_vertex (Vertex * vrt, Volume * parent) inline virtual
called when a new vertex was created from an old volume.
Reimplemented from ug::RefinementProjector.
References m_newVrts, and ug::RefinementProjector::new_vertex().
refinement_begins()
virtual void ug::SmoothProjector::refinement_begins (const ISubGrid * sg) inline virtual
called before refinement begins
Reimplemented from ug::RefinementProjector.
References m_newVrts, ug::RefinementProjector::refinement_begins(), and refinement_ends().
refinement_ends()
void ug::SmoothProjector::refinement_ends () virtual
called when refinement is done.
The actual smoothing is performed here
Reimplemented from ug::RefinementProjector.
References ug::Grid::associated_elements(), ug::Grid::begin_marking(), end_for, ug::Grid::end_marking(), for_each_in_vec, ug::RefinementProjector::geom(), ug::IGeometry< dim >::grid(), ug::Grid::is_marked(), m_changeRate, m_iterations, m_newVrts, ug::Grid::mark(), ug::EdgeVertices::num_vertices(), ug::FaceVertices::num_vertices(), ug::VolumeVertices::num_vertices(), ug::RefinementProjector::pos(), ug::RefinementProjector::set_pos(), ug::PointerConstArray< TPtr >::size(), ug::EdgeVertices::vertex(), ug::FaceVertices::vertex(), and ug::VolumeVertices::vertex().
Referenced by refinement_begins().
serialize()
template<class Archive > void ug::SmoothProjector::serialize (Archive & ar, const unsigned int version) inline private
References m_changeRate, m_iterations, and UG_EMPTY_BASE_CLASS_SERIALIZATION.
set_change_rate()
void ug::SmoothProjector::set_change_rate (number changeRate) inline
References m_changeRate.
set_iterations()
void ug::SmoothProjector::set_iterations (int iterations) inline
References iterations(), and m_iterations.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_changeRate
number ug::SmoothProjector::m_changeRate private
Referenced by change_rate(), refinement_ends(), serialize(), and set_change_rate().
m_iterations
int ug::SmoothProjector::m_iterations private
Referenced by iterations(), refinement_ends(), serialize(), and set_iterations().
m_newVrts
std::vector<Vertex*> ug::SmoothProjector::m_newVrts private
Referenced by new_vertex(), refinement_begins(), and refinement_ends().
The documentation for this class was generated from the following files:
ugbase/lib_grid/refinement/projectors/smooth_projector.h
ugbase/lib_grid/refinement/projectors/smooth_projector.cpp