ug4: ug::Field< T > Class Template Reference
ug::Field< T > Class Template Reference
#include <field.h>
Public Member Functions
T & at (size_t x, size_t y)
const T & at (size_t x, size_t y) const
size_t capacity () const
void copy (size_t x, size_t y, const Field &f)
T * data ()
const T * data () const
Field ()
Field (size_t width, size_t height)
Field (size_t width, size_t height, const T &value)
Field (const Field &f)
void fill (size_t x, size_t y, size_t w, size_t h, const T &value)
void fill_all (const T &value)
size_t height () const
T & operator= (const Field &field)
void resize_no_copy (size_t width, size_t height)
size_t size () const
void swap (Field &f)
size_t width () const
~Field ()
Private Member Functions
size_t array_index (size_t x, size_t y) const
Private Attributes
size_t m_capacity
T * m_data
size_t m_height
size_t m_width
Constructor & Destructor Documentation
template<class T > ug::Field< T >::Field ()
Referenced by ug::Field< T >::Field().
template<class T > ug::Field< T >::Field (size_t width, size_t height)
References ug::Field< T >::Field(), ug::Field< T >::m_capacity, ug::Field< T >::m_data, ug::Field< T >::m_height, and ug::Field< T >::m_width.
template<class T> ug::Field< T >::Field (size_t width, size_t height, const T & value)
References ug::Field< T >::Field(), ug::Field< T >::fill_all(), ug::Field< T >::m_capacity, ug::Field< T >::m_data, ug::Field< T >::m_height, and ug::Field< T >::m_width.
template<class T> ug::Field< T >::Field (const Field< T > & f)
References ug::Field< T >::data(), ug::Field< T >::height(), ug::Field< T >::m_capacity, ug::Field< T >::m_data, ug::Field< T >::m_height, ug::Field< T >::m_width, ug::Field< T >::width(), and ug::Field< T >::~Field().
template<class T > ug::Field< T >::~Field ()
References ug::Field< T >::m_data, and ug::Field< T >::operator=().
Referenced by ug::Field< T >::Field().
Member Function Documentation
template<class T > size_t ug::Field< T >::array_index (size_t x, size_t y) const inline private
References ug::Field< T >::m_width.
Referenced by ug::Field< T >::at(), ug::Field< T >::copy(), ug::Field< number >::data(), ug::Field< T >::fill(), and ug::Field< T >::swap().
template<class T > T & ug::Field< T >::at (size_t x, size_t y) inline
References ug::Field< T >::array_index(), and ug::Field< T >::m_data.
Referenced by ug::FileReaderASC::at(), ug::BlurField(), ug::Field< T >::copy(), ug::CreateGridFromField(), ug::CreateGridFromFieldBoundary(), ug::EliminateInvalidCells(), ug::Heightfield::interpolate(), ug::RasterLayers::invalidate_flat_cells(), ug::InvalidateSmallLenses(), ug::FileReaderASC::load_file(), ug::RasterLayers::remove_small_holes(), ug::Field< T >::resize_no_copy(), and ug::RasterLayers::snap_cells_to_higher_layers().
template<class T > const T & ug::Field< T >::at (size_t x, size_t y) const inline
References ug::Field< T >::array_index(), ug::Field< T >::fill(), and ug::Field< T >::m_data.
template<class T> size_t ug::Field< T >::capacity () const inline
template<class T > void ug::Field< T >::copy (size_t x, size_t y, const Field< T > & f)
References ug::Field< T >::array_index(), ug::Field< T >::at(), ug::Field< T >::height(), ug::Field< T >::m_data, ug::Field< T >::m_height, ug::Field< T >::m_width, ug::Field< T >::swap(), and ug::Field< T >::width().
Referenced by ug::Field< number >::data(), and ug::Field< T >::fill_all().
template<class T> T* ug::Field< T >::data () inline
Referenced by ug::Field< T >::Field(), and ug::Field< T >::operator=().
template<class T> const T* ug::Field< T >::data () const inline
template<class T> void ug::Field< T >::fill (size_t x, size_t y, size_t w, size_t h, const T & value)
References ug::Field< T >::array_index(), ug::Field< T >::fill_all(), ug::Field< T >::m_data, ug::Field< T >::m_height, and ug::Field< T >::m_width.
Referenced by ug::Field< T >::at(), and ug::Field< number >::data().
template<class T> void ug::Field< T >::fill_all (const T & value)
References ug::Field< T >::copy(), ug::Field< T >::m_data, and ug::Field< T >::size().
Referenced by ug::CreateGridFromField(), ug::CreateGridFromFieldBoundary(), ug::Field< number >::data(), ug::Field< T >::Field(), ug::Field< T >::fill(), and ug::RasterLayers::remove_small_holes().
template<class T> size_t ug::Field< T >::height () const inline
Referenced by ug::BlurField(), ug::Field< T >::copy(), ug::CreateGridFromField(), ug::CreateGridFromFieldBoundary(), ug::EliminateInvalidCells(), ug::Heightfield::extent(), ug::Field< T >::Field(), ug::Heightfield::interpolate(), ug::RasterLayers::invalidate_flat_cells(), ug::InvalidateSmallLenses(), ug::FileReaderASC::num_rows(), ug::RasterLayers::remove_small_holes(), ug::Field< T >::resize_no_copy(), and ug::RasterLayers::snap_cells_to_higher_layers().
template<class T > T & ug::Field< T >::operator= (const Field< T > & field)
References ug::Field< T >::data(), ug::Field< T >::m_capacity, ug::Field< T >::m_data, ug::Field< T >::m_height, ug::Field< T >::m_width, and ug::Field< T >::resize_no_copy().
Referenced by ug::Field< T >::~Field().
template<class T > void ug::Field< T >::resize_no_copy (size_t width, size_t height)
References ug::Field< T >::at(), ug::Field< T >::height(), ug::Field< T >::m_capacity, ug::Field< T >::m_data, ug::Field< T >::m_height, ug::Field< T >::m_width, and ug::Field< T >::width().
Referenced by ug::FileReaderASC::load_file(), ug::Field< T >::operator=(), and ug::RasterLayers::remove_small_holes().
template<class T> size_t ug::Field< T >::size () const inline
Referenced by ug::Field< T >::fill_all(), and ug::InvalidateSmallLenses().
template<class T > void ug::Field< T >::swap (Field< T > & f)
References ug::Field< T >::array_index(), ug::Field< T >::m_capacity, ug::Field< T >::m_data, ug::Field< T >::m_height, and ug::Field< T >::m_width.
Referenced by ug::Field< T >::copy(), and ug::Field< number >::data().
template<class T> size_t ug::Field< T >::width () const inline
Referenced by ug::BlurField(), ug::Field< T >::copy(), ug::CreateGridFromField(), ug::CreateGridFromFieldBoundary(), ug::EliminateInvalidCells(), ug::Heightfield::extent(), ug::Field< T >::Field(), ug::Heightfield::interpolate(), ug::RasterLayers::invalidate_flat_cells(), ug::InvalidateSmallLenses(), ug::FileReaderASC::num_columns(), ug::RasterLayers::remove_small_holes(), ug::Field< T >::resize_no_copy(), and ug::RasterLayers::snap_cells_to_higher_layers().
Member Data Documentation
template<class T> size_t ug::Field< T >::m_capacity private
Referenced by ug::Field< number >::capacity(), ug::Field< T >::Field(), ug::Field< T >::operator=(), ug::Field< T >::resize_no_copy(), and ug::Field< T >::swap().
template<class T> T* ug::Field< T >::m_data private
Referenced by ug::Field< T >::at(), ug::Field< T >::copy(), ug::Field< number >::data(), ug::Field< T >::Field(), ug::Field< T >::fill(), ug::Field< T >::fill_all(), ug::Field< T >::operator=(), ug::Field< T >::resize_no_copy(), ug::Field< T >::swap(), and ug::Field< T >::~Field().
template<class T> size_t ug::Field< T >::m_height private
Referenced by ug::Field< T >::copy(), ug::Field< T >::Field(), ug::Field< T >::fill(), ug::Field< number >::height(), ug::Field< T >::operator=(), ug::Field< T >::resize_no_copy(), ug::Field< number >::size(), and ug::Field< T >::swap().
template<class T> size_t ug::Field< T >::m_width private
Referenced by ug::Field< T >::array_index(), ug::Field< T >::copy(), ug::Field< T >::Field(), ug::Field< T >::fill(), ug::Field< T >::operator=(), ug::Field< T >::resize_no_copy(), ug::Field< number >::size(), ug::Field< T >::swap(), and ug::Field< number >::width().
The documentation for this class was generated from the following files:
ugbase/common/util/field.h
ugbase/common/util/field_impl.hpp