ug4: ug::LocalVectorTimeSeries Class Reference
ug::LocalVectorTimeSeries Class Reference
time series of local vectors
#include <solution_time_series.h>
Public Member Functions
void access_by_map (const FunctionIndexMapping &funcMap)
access dofs by map
LocalVectorTimeSeries ()
constructor
template<typename TVector >
void read_times (ConstSmartPtr< VectorTimeSeries< TVector > > vecTimeSeries)
extract time points
template<typename TVector >
void read_values (ConstSmartPtr< VectorTimeSeries< TVector > > vecTimeSeries, LocalIndices &ind)
extract local values from global vectors
size_t size () const
returns number of time points
LocalVector & solution (size_t i)
returns the local vector for the i'th time point
const LocalVector & solution (size_t i) const
returns the local vector for the i'th time point
number time (size_t i) const
returns time point i
const std::vector< number > & times () const
returns time points
Protected Attributes
std::vector< LocalVector > m_vLocalVector
vector of local vectors (one for each time point)
std::vector< number > m_vTime
time series
Detailed Description
time series of local vectors
Constructor & Destructor Documentation
LocalVectorTimeSeries()
ug::LocalVectorTimeSeries::LocalVectorTimeSeries () inline
constructor
Member Function Documentation
access_by_map()
void ug::LocalVectorTimeSeries::access_by_map (const FunctionIndexMapping & funcMap) inline
access dofs by map
References ug::LocalVector::access_by_map(), size(), and solution().
read_times()
template<typename TVector > void ug::LocalVectorTimeSeries::read_times (ConstSmartPtr< VectorTimeSeries< TVector > > vecTimeSeries) inline
extract time points
References m_vTime.
Referenced by ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleDefect(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleDefect(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleErrorEstimator(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleJacobian(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleJacobian(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleLinear(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleLinear(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleRhs(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::FinishTimestep(), ug::StdGlobAssembler< TDomain, TAlgebra >::FinishTimestep(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::FinishTimestepElem(), ug::StdGlobAssembler< TDomain, TAlgebra >::FinishTimestepElem(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::PrepareTimestep(), ug::StdGlobAssembler< TDomain, TAlgebra >::PrepareTimestep(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::PrepareTimestepElem(), and ug::StdGlobAssembler< TDomain, TAlgebra >::PrepareTimestepElem().
read_values()
template<typename TVector > void ug::LocalVectorTimeSeries::read_values (ConstSmartPtr< VectorTimeSeries< TVector > > vecTimeSeries, LocalIndices & ind) inline
extract local values from global vectors
References ug::GetLocalVector(), and m_vLocalVector.
Referenced by ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleDefect(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleDefect(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleErrorEstimator(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleJacobian(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleJacobian(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleLinear(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleLinear(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleRhs(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::FinishTimestepElem(), ug::StdGlobAssembler< TDomain, TAlgebra >::FinishTimestepElem(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::PrepareTimestepElem(), and ug::StdGlobAssembler< TDomain, TAlgebra >::PrepareTimestepElem().
size()
size_t ug::LocalVectorTimeSeries::size () const inline
returns number of time points
References m_vLocalVector.
Referenced by access_by_map(), and ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleJacobian().
solution() [1/2]
LocalVector& ug::LocalVectorTimeSeries::solution (size_t i) inline
returns the local vector for the i'th time point
References m_vLocalVector.
solution() [2/2]
const LocalVector& ug::LocalVectorTimeSeries::solution (size_t i) const inline
returns the local vector for the i'th time point
References m_vLocalVector.
Referenced by access_by_map(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleDefect(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleDefect(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleErrorEstimator(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleJacobian(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleLinear(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleLinear(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleRhs(), ug::StdExplicitGridFunctionData< TImpl, TData, TGridFunction >::eval(), ug::StdDataLinker< TImpl, TData, dim >::eval_deriv(), and ug::StdDependentUserData< TImpl, TData, dim >::eval_deriv().
time()
number ug::LocalVectorTimeSeries::time (size_t i) const inline
returns time point i
References m_vTime.
Referenced by ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::FinishTimestepElem(), ug::StdGlobAssembler< TDomain, TAlgebra >::FinishTimestepElem(), and ug::IElemDiscBase< TDomain >::time().
times()
const std::vector<number>& ug::LocalVectorTimeSeries::times () const inline
returns time points
References m_vTime.
Member Data Documentation
m_vLocalVector
std::vector<LocalVector> ug::LocalVectorTimeSeries::m_vLocalVector protected
vector of local vectors (one for each time point)
Referenced by read_values(), size(), and solution().
m_vTime
std::vector<number> ug::LocalVectorTimeSeries::m_vTime protected
time series
Referenced by read_times(), time(), and times().
The documentation for this class was generated from the following file:
ugbase/lib_disc/time_disc/solution_time_series.h