ug4: ug::GridMessage_MultiGridChanged Class Reference
ug::GridMessage_MultiGridChanged Class Reference
A message sent by the MultiGrid, if something special happened.
#include <lib_grid_messages.h>
Public Member Functions
GridMessage_MultiGridChanged (GridMessageMultiGridChangedType msgType, int numLevels)
GridMessageMultiGridChangedType message_type () const
returns the type of the message
int num_levels_in_grid () const
returns the current number of levels in the multigrid, which did send the message.
Public Member Functions inherited from ug::MessageHub::IMessage
IMessage ()
virtual ~IMessage ()
Private Attributes
GridMessageMultiGridChangedType m_msgType
int m_numLevels
Detailed Description
A message sent by the MultiGrid, if something special happened.
Constructor & Destructor Documentation
GridMessage_MultiGridChanged()
ug::GridMessage_MultiGridChanged::GridMessage_MultiGridChanged (GridMessageMultiGridChangedType msgType, int numLevels) inline
Member Function Documentation
message_type()
GridMessageMultiGridChangedType ug::GridMessage_MultiGridChanged::message_type () const inline
returns the type of the message
References m_msgType.
Referenced by ug::MGSelector::multigrid_changed(), and ug::MultiGridSubsetHandler::multigrid_changed().
num_levels_in_grid()
int ug::GridMessage_MultiGridChanged::num_levels_in_grid () const inline
returns the current number of levels in the multigrid, which did send the message.
References m_numLevels.
Referenced by ug::MGSelector::multigrid_changed(), and ug::MultiGridSubsetHandler::multigrid_changed().
Member Data Documentation
m_msgType
GridMessageMultiGridChangedType ug::GridMessage_MultiGridChanged::m_msgType private
Referenced by message_type().
m_numLevels
int ug::GridMessage_MultiGridChanged::m_numLevels private
Referenced by num_levels_in_grid().
The documentation for this class was generated from the following file:
ugbase/lib_grid/lib_grid_messages.h