ug4: boost::SM_adjacency_iterator< T > Class Template Reference
boost::SM_adjacency_iterator< T > Class Template Reference
#include <sparsematrix_boost.h>
Public Types
typedef intmax_t difference_type
typedef size_t reference
typedef iter_t * value_type
Public Member Functions
reference dereference () const
size_t idx () const
bool operator!= (const SM_adjacency_iterator &other) const
SM_adjacency_iterator & operator= (const SM_adjacency_iterator &other)
SM_adjacency_iterator & operator= (SM_adjacency_iterator &&other)=delete
bool operator== (const SM_adjacency_iterator &other) const
int row () const
SM_adjacency_iterator ()
SM_adjacency_iterator (SM_adjacency_iterator &&p)=delete
SM_adjacency_iterator (SM_adjacency_iterator const &p)
SM_adjacency_iterator (value_type p, value_type e)
T const & value () const
~SM_adjacency_iterator ()
Private Types
typedef iterator_facade< SM_adjacency_iterator< T >, typename ug::SparseMatrix< T >::const_row_iterator, std::input_iterator_tag, size_t, std::intmax_t > base_class
typedef M::const_row_iterator iter_t
typedef ug::SparseMatrix< T > M
Private Member Functions
void decrement ()
bool equal (SM_adjacency_iterator const &other) const
void increment ()
void skip_zeroes ()
Private Attributes
value_type _base
value_type _end
Friends
class iterator_core_access
Member Typedef Documentation
base_class
template<class T > typedef iterator_facade< SM_adjacency_iterator<T>, typename ug::SparseMatrix<T>::const_row_iterator, std::input_iterator_tag, size_t, std::intmax_t > boost::SM_adjacency_iterator< T >::base_class private
difference_type
template<class T > typedef intmax_t boost::SM_adjacency_iterator< T >::difference_type
iter_t
template<class T > typedef M::const_row_iterator boost::SM_adjacency_iterator< T >::iter_t private
M
template<class T > typedef ug::SparseMatrix<T> boost::SM_adjacency_iterator< T >::M private
reference
template<class T > typedef size_t boost::SM_adjacency_iterator< T >::reference
value_type
template<class T > typedef iter_t* boost::SM_adjacency_iterator< T >::value_type
Constructor & Destructor Documentation
SM_adjacency_iterator() [1/4]
template<class T > boost::SM_adjacency_iterator< T >::SM_adjacency_iterator () inline
SM_adjacency_iterator() [2/4]
template<class T > boost::SM_adjacency_iterator< T >::SM_adjacency_iterator (SM_adjacency_iterator< T > && p) delete
SM_adjacency_iterator() [3/4]
template<class T > boost::SM_adjacency_iterator< T >::SM_adjacency_iterator (SM_adjacency_iterator< T > const & p) inline
References p.
SM_adjacency_iterator() [4/4]
template<class T > boost::SM_adjacency_iterator< T >::SM_adjacency_iterator (value_type p, value_type e) inline
References boost::SM_adjacency_iterator< T >::_base, boost::SM_adjacency_iterator< T >::_end, p, and boost::SM_adjacency_iterator< T >::skip_zeroes().
~SM_adjacency_iterator()
template<class T > boost::SM_adjacency_iterator< T >::~SM_adjacency_iterator () inline
References boost::SM_adjacency_iterator< T >::_base, and boost::SM_adjacency_iterator< T >::_end.
Member Function Documentation
decrement()
template<class T > void boost::SM_adjacency_iterator< T >::decrement () inline private
References boost::SM_adjacency_iterator< T >::_base, and untested.
dereference()
template<class T > reference boost::SM_adjacency_iterator< T >::dereference () const inline
References boost::SM_adjacency_iterator< T >::_base, and ug::SparseMatrix< TValueType >::const_row_iterator::index().
equal()
template<class T > bool boost::SM_adjacency_iterator< T >::equal (SM_adjacency_iterator< T > const & other) const inline private
References boost::SM_adjacency_iterator< T >::_base, and untested.
idx()
template<class T > size_t boost::SM_adjacency_iterator< T >::idx () const inline
References boost::SM_adjacency_iterator< T >::_base, ug::SparseMatrix< TValueType >::const_row_iterator::idx(), and untested.
increment()
template<class T > void boost::SM_adjacency_iterator< T >::increment () inline private
References boost::SM_adjacency_iterator< T >::_base, boost::SM_adjacency_iterator< T >::_end, and boost::SM_adjacency_iterator< T >::skip_zeroes().
operator!=()
template<class T > bool boost::SM_adjacency_iterator< T >::operator!= (const SM_adjacency_iterator< T > & other) const inline
References boost::SM_adjacency_iterator< T >::_base.
operator=() [1/2]
template<class T > SM_adjacency_iterator& boost::SM_adjacency_iterator< T >::operator= (const SM_adjacency_iterator< T > & other) inline
References boost::SM_adjacency_iterator< T >::_base, boost::SM_adjacency_iterator< T >::_end, and untested.
operator=() [2/2]
template<class T > SM_adjacency_iterator& boost::SM_adjacency_iterator< T >::operator= (SM_adjacency_iterator< T > && other) delete
operator==()
template<class T > bool boost::SM_adjacency_iterator< T >::operator== (const SM_adjacency_iterator< T > & other) const inline
References boost::SM_adjacency_iterator< T >::_base.
row()
template<class T > int boost::SM_adjacency_iterator< T >::row () const inline
References boost::SM_adjacency_iterator< T >::_base.
skip_zeroes()
template<class T > void boost::SM_adjacency_iterator< T >::skip_zeroes () inline private
References boost::SM_adjacency_iterator< T >::_base, boost::SM_adjacency_iterator< T >::_end, ug::iszero(), and ug::SparseMatrix< TValueType >::const_row_iterator::value().
Referenced by boost::SM_adjacency_iterator< T >::increment(), and boost::SM_adjacency_iterator< T >::SM_adjacency_iterator().
value()
template<class T > T const& boost::SM_adjacency_iterator< T >::value () const inline
References boost::SM_adjacency_iterator< T >::_base, and ug::SparseMatrix< TValueType >::const_row_iterator::value().
Referenced by boost::SM_out_edge_iterator< T, out >::dereference().
Friends And Related Function Documentation
iterator_core_access
template<class T > friend class iterator_core_access friend
Member Data Documentation
_base
template<class T > value_type boost::SM_adjacency_iterator< T >::_base private
Referenced by boost::SM_adjacency_iterator< T >::decrement(), boost::SM_adjacency_iterator< T >::dereference(), boost::SM_adjacency_iterator< T >::equal(), boost::SM_adjacency_iterator< T >::idx(), boost::SM_adjacency_iterator< T >::increment(), boost::SM_adjacency_iterator< T >::operator!=(), boost::SM_adjacency_iterator< T >::operator=(), boost::SM_adjacency_iterator< T >::operator==(), boost::SM_adjacency_iterator< T >::row(), boost::SM_adjacency_iterator< T >::skip_zeroes(), boost::SM_adjacency_iterator< T >::SM_adjacency_iterator(), boost::SM_adjacency_iterator< T >::value(), and boost::SM_adjacency_iterator< T >::~SM_adjacency_iterator().
_end
template<class T > value_type boost::SM_adjacency_iterator< T >::_end private
Referenced by boost::SM_adjacency_iterator< T >::increment(), boost::SM_adjacency_iterator< T >::operator=(), boost::SM_adjacency_iterator< T >::skip_zeroes(), boost::SM_adjacency_iterator< T >::SM_adjacency_iterator(), and boost::SM_adjacency_iterator< T >::~SM_adjacency_iterator().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/graph_interface/sparsematrix_boost.h