ug4: ug::bridge::ExportedFunctionGroup Class Reference
ug::bridge::ExportedFunctionGroup Class Reference
ugbase » Bridge » Registry
Groups of Functions - useful to realize overloaded functions.
#include <global_function.h>
Classes
struct Overload
Public Member Functions
template<class TFunc >
ExportedFunction * add_overload (TFunc f, ExportedFunction::ProxyFunc pf, const std::string &funcOptions, const std::string &group, const std::string &retValInfos, const std::string &paramInfos, const std::string &tooltip, const std::string &help)
adds an overload. Returns false if the overload already existed.
ExportedFunctionGroup (const std::string &name)
constructor
ExportedFunction * get_overload (size_t index)
const ExportedFunction * get_overload (size_t index) const
template<class TType >
ExportedFunction * get_overload_by_type ()
template<class TType >
const ExportedFunction * get_overload_by_type () const
ExportedFunction * get_overload_by_type_id (size_t typeID)
const ExportedFunction * get_overload_by_type_id (size_t typeID) const
size_t get_overload_type_id (size_t index) const
const std::string & name () const
name of function group
size_t num_overloads () const
~ExportedFunctionGroup ()
destructor
Private Attributes
std::string m_name
std::vector< Overload > m_overloads
Detailed Description
Groups of Functions - useful to realize overloaded functions.
Constructor & Destructor Documentation
ExportedFunctionGroup()
ug::bridge::ExportedFunctionGroup::ExportedFunctionGroup (const std::string & name) inline
constructor
~ExportedFunctionGroup()
ug::bridge::ExportedFunctionGroup::~ExportedFunctionGroup () inline
destructor
Member Function Documentation
add_overload()
template<class TFunc > ExportedFunction* ug::bridge::ExportedFunctionGroup::add_overload (TFunc f, ExportedFunction::ProxyFunc pf, const std::string & funcOptions, const std::string & group, const std::string & retValInfos, const std::string & paramInfos, const std::string & tooltip, const std::string & help) inline
adds an overload. Returns false if the overload already existed.
References func().
Referenced by ug::bridge::Registry::add_and_get_function().
get_overload() [1/2]
ExportedFunction* ug::bridge::ExportedFunctionGroup::get_overload (size_t index) inline
References ug::bridge::ExportedFunction::m_func.
Referenced by ug::bridge::Registry::check_consistency(), ug::vrl::functions2NativeGroups(), ug::vrl::invocation::getFunctionBySignature(), ug::bridge::lua::LuaProxyFunction(), and ug::bridge::WriteLUAObject2().
get_overload() [2/2]
const ExportedFunction* ug::bridge::ExportedFunctionGroup::get_overload (size_t index) const inline
References ug::bridge::ExportedFunction::m_func.
get_overload_by_type() [1/2]
template<class TType > ExportedFunction* ug::bridge::ExportedFunctionGroup::get_overload_by_type () inline
get_overload_by_type() [2/2]
template<class TType > const ExportedFunction* ug::bridge::ExportedFunctionGroup::get_overload_by_type () const inline
get_overload_by_type_id() [1/2]
ExportedFunction* ug::bridge::ExportedFunctionGroup::get_overload_by_type_id (size_t typeID) inline
References ug::bridge::ExportedFunction::m_func.
get_overload_by_type_id() [2/2]
const ExportedFunction* ug::bridge::ExportedFunctionGroup::get_overload_by_type_id (size_t typeID) const inline
References ug::bridge::ExportedFunction::m_func.
get_overload_type_id()
size_t ug::bridge::ExportedFunctionGroup::get_overload_type_id (size_t index) const inline
name()
const std::string& ug::bridge::ExportedFunctionGroup::name () const inline
name of function group
Referenced by ug::bridge::Registry::check_consistency(), ug::bridge::lua::CreateBindings_LUA(), and ug::bridge::lua::LuaProxyFunction().
num_overloads()
size_t ug::bridge::ExportedFunctionGroup::num_overloads () const inline
Referenced by ug::bridge::Registry::check_consistency(), ug::vrl::functions2NativeGroups(), ug::vrl::invocation::getFunctionBySignature(), ug::bridge::lua::LuaProxyFunction(), and ug::bridge::WriteLUAObject2().
Member Data Documentation
m_name
std::string ug::bridge::ExportedFunctionGroup::m_name private
m_overloads
std::vector<Overload> ug::bridge::ExportedFunctionGroup::m_overloads private
The documentation for this class was generated from the following file:
ugbase/registry/global_function.h