ug4: ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t > Class Template Reference
ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t > Class Template Reference
Public Types
typedef IOrderingAlgorithm< TAlgebra, O_t > baseclass
typedef Graph_t G_t
typedef TAlgebra::matrix_type M_t
typedef TAlgebra::vector_type V_t
typedef boost::graph_traits< G_t >::vertex_descriptor Vertex_t
Public Types inherited from ug::IOrderingAlgorithm< TAlgebra, std::vector< size_t > >
typedef TAlgebra::matrix_type M_t
typedef TAlgebra::vector_type V_t
Public Member Functions
BoostCuthillMcKeeOrdering ()
BoostCuthillMcKeeOrdering (const BoostCuthillMcKeeOrdering< TAlgebra, O_t > &parent)
clone constructor
void check ()
SmartPtr< IOrderingAlgorithm< TAlgebra, O_t > > clone ()
void compute ()
void init (M_t *A)
void init (M_t *A, const O_t &inv_map)
void init (M_t *A, const V_t &)
void init (M_t *A, const V_t &, const O_t &inv_map)
virtual const char * name () const
O_t & ordering ()
void set_reverse (bool b)
Public Member Functions inherited from ug::IOrderingAlgorithm< TAlgebra, std::vector< size_t > >
virtual void init (M_t *, const std::vector< size_t > &)=0
virtual void init (M_t *, const V_t &, const std::vector< size_t > &)=0
IOrderingAlgorithm ()
virtual ~IOrderingAlgorithm ()
Private Attributes
G_t g
bool m_bReverse
O_t o
Member Typedef Documentation
baseclass
template<typename TAlgebra , typename O_t = std::vector<size_t>> typedef IOrderingAlgorithm<TAlgebra, O_t> ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::baseclass
G_t
template<typename TAlgebra , typename O_t = std::vector<size_t>> typedef Graph_t ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::G_t
M_t
template<typename TAlgebra , typename O_t = std::vector<size_t>> typedef TAlgebra::matrix_type ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::M_t
V_t
template<typename TAlgebra , typename O_t = std::vector<size_t>> typedef TAlgebra::vector_type ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::V_t
Vertex_t
template<typename TAlgebra , typename O_t = std::vector<size_t>> typedef boost::graph_traits<G_t>::vertex_descriptor ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::Vertex_t
Constructor & Destructor Documentation
BoostCuthillMcKeeOrdering() [1/2]
template<typename TAlgebra , typename O_t = std::vector<size_t>> ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::BoostCuthillMcKeeOrdering () inline
BoostCuthillMcKeeOrdering() [2/2]
template<typename TAlgebra , typename O_t = std::vector<size_t>> ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::BoostCuthillMcKeeOrdering (const BoostCuthillMcKeeOrdering< TAlgebra, O_t > & parent) inline
clone constructor
Member Function Documentation
check()
template<typename TAlgebra , typename O_t = std::vector<size_t>> void ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::check () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, std::vector< size_t > >.
References ug::is_permutation(), ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::name(), ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::o, and UG_COND_THROW.
Referenced by ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::compute().
clone()
template<typename TAlgebra , typename O_t = std::vector<size_t>> SmartPtr<IOrderingAlgorithm<TAlgebra, O_t> > ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::clone () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, std::vector< size_t > >.
References make_sp().
compute()
template<typename TAlgebra , typename O_t = std::vector<size_t>> void ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::compute () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, std::vector< size_t > >.
References ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::check(), ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::g, boost::get(), ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::m_bReverse, boost::make_degree_map(), ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::name(), boost::num_vertices(), ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::o, and UG_COND_THROW.
init() [1/4]
template<typename TAlgebra , typename O_t = std::vector<size_t>> void ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::init (M_t * A) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, std::vector< size_t > >.
References ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::g, ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::name(), and UG_LOG.
init() [2/4]
template<typename TAlgebra , typename O_t = std::vector<size_t>> void ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::init (M_t * A, const O_t & inv_map) inline
References ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::g, ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::name(), and UG_LOG.
init() [3/4]
template<typename TAlgebra , typename O_t = std::vector<size_t>> void ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::init (M_t * A, const V_t &) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, std::vector< size_t > >.
Referenced by ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::init().
init() [4/4]
template<typename TAlgebra , typename O_t = std::vector<size_t>> void ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::init (M_t * A, const V_t & , const O_t & inv_map) inline
References ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::init().
name()
template<typename TAlgebra , typename O_t = std::vector<size_t>> virtual const char* ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::name () const inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, std::vector< size_t > >.
References ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::m_bReverse.
Referenced by ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::check(), ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::compute(), and ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::init().
ordering()
template<typename TAlgebra , typename O_t = std::vector<size_t>> O_t& ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::ordering () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, std::vector< size_t > >.
References ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::o.
set_reverse()
template<typename TAlgebra , typename O_t = std::vector<size_t>> void ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::set_reverse (bool b) inline
References ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::m_bReverse.
Member Data Documentation
g
template<typename TAlgebra , typename O_t = std::vector<size_t>> G_t ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::g private
Referenced by ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::compute(), and ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::init().
m_bReverse
template<typename TAlgebra , typename O_t = std::vector<size_t>> bool ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::m_bReverse private
Referenced by ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::compute(), ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::name(), and ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::set_reverse().
o
template<typename TAlgebra , typename O_t = std::vector<size_t>> O_t ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::o private
Referenced by ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::check(), ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::compute(), and ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::ordering().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/ordering_strategies/algorithms/boost_cuthill_mckee_ordering.cpp