ug4: SmallObjectAllocator< maxObjSize, maxChunkSize > Class Template Reference
SmallObjectAllocator< maxObjSize, maxChunkSize > Class Template Reference
#include <small_object_allocator.h>
Public Member Functions
void * allocate (std::size_t numBytes)
if numBytes > maxObjSize, allocate will directly call new.
void deallocate (void *p, std::size_t size)
make sure that size exactly specifies the number of bytes of the object to which p points.
Static Public Member Functions
static SmallObjectAllocator & inst ()
returns an instance to this singleton
Private Member Functions
SmallObjectAllocator ()
Private Attributes
std::vector< FixedAllocator > m_allocators
Detailed Description
template<std::size_t maxObjSize = 64, std::size_t maxChunkSize = 4096>
class SmallObjectAllocator< maxObjSize, maxChunkSize >
A singleton that can be used to allocate small objects.
Constructor & Destructor Documentation
template<std::size_t maxObjSize, std::size_t maxChunkSize> SmallObjectAllocator< maxObjSize, maxChunkSize >::SmallObjectAllocator () private
Referenced by SmallObjectAllocator< maxObjSize, maxChunkSize >::deallocate().
Member Function Documentation
template<std::size_t maxObjSize, std::size_t maxChunkSize> void * SmallObjectAllocator< maxObjSize, maxChunkSize >::allocate (std::size_t numBytes)
if numBytes > maxObjSize, allocate will directly call new.
References SmallObjectAllocator< maxObjSize, maxChunkSize >::deallocate().
Referenced by SmallObjectAllocator< maxObjSize, maxChunkSize >::inst(), and SmallObject< maxObjSize, maxChunkSize >::operator new().
template<std::size_t maxObjSize, std::size_t maxChunkSize> void SmallObjectAllocator< maxObjSize, maxChunkSize >::deallocate (void * p, std::size_t size)
make sure that size exactly specifies the number of bytes of the object to which p points.
References SmallObjectAllocator< maxObjSize, maxChunkSize >::SmallObjectAllocator().
Referenced by SmallObjectAllocator< maxObjSize, maxChunkSize >::allocate(), and SmallObject< maxObjSize, maxChunkSize >::operator delete().
template<std::size_t maxObjSize, std::size_t maxChunkSize> SmallObjectAllocator< maxObjSize, maxChunkSize > & SmallObjectAllocator< maxObjSize, maxChunkSize >::inst () static
returns an instance to this singleton
References SmallObjectAllocator< maxObjSize, maxChunkSize >::allocate().
Referenced by SmallObject< maxObjSize, maxChunkSize >::operator delete(), and SmallObject< maxObjSize, maxChunkSize >::operator new().
Member Data Documentation
template<std::size_t maxObjSize = 64, std::size_t maxChunkSize = 4096> std::vector<FixedAllocator> SmallObjectAllocator< maxObjSize, maxChunkSize >::m_allocators private
The documentation for this class was generated from the following files:
ugbase/common/allocators/small_object_allocator.h
ugbase/common/allocators/small_object_allocator_impl.h