ug4: ug::Raster< T, TDIM >::Coordinate Class Reference
ug::Raster< T, TDIM >::Coordinate Class Reference
#include <raster.h>
Public Member Functions
Coordinate ()
Coordinate (number c)
Coordinate (const MathVector< TDIM, number > &v)
const int dim () const
Coordinate & operator*= (number s)
Coordinate & operator+= (const Coordinate &c)
Coordinate & operator-= (const Coordinate &c)
number & operator[] (int d)
number operator[] (int d) const
void set (number c)
Private Attributes
number m_coord [TDIM]
Friends
std::ostream & operator<< (std::ostream &o, const Coordinate &coord)
Constructor & Destructor Documentation
Coordinate() [1/3]
template<class T , int TDIM> ug::Raster< T, TDIM >::Coordinate::Coordinate ()
Referenced by ug::Raster< T, TDIM >::Coordinate::Coordinate(), and ug::Raster< T, TDIM >::MultiIndex::operator[]().
Coordinate() [2/3]
template<class T , int TDIM> ug::Raster< T, TDIM >::Coordinate::Coordinate (number c)
References ug::Raster< T, TDIM >::Coordinate::Coordinate().
Coordinate() [3/3]
template<class T , int TDIM> ug::Raster< T, TDIM >::Coordinate::Coordinate (const MathVector< TDIM, number > & v)
References ug::Raster< T, TDIM >::Coordinate::dim().
Member Function Documentation
dim()
template<class T , int TDIM> const int ug::Raster< T, TDIM >::Coordinate::dim () const
References ug::Raster< T, TDIM >::Coordinate::set().
Referenced by ug::Raster< T, TDIM >::Coordinate::Coordinate().
operator*=()
template<class T , int TDIM> Raster< T, TDIM >::Coordinate & ug::Raster< T, TDIM >::Coordinate::operator*= (number s)
References ug::Raster< T, TDIM >::Raster().
Referenced by ug::Raster< T, TDIM >::Coordinate::operator-=().
operator+=()
template<class T , int TDIM> Raster< T, TDIM >::Coordinate & ug::Raster< T, TDIM >::Coordinate::operator+= (const Coordinate & c)
References ug::Raster< T, TDIM >::Coordinate::operator-=().
Referenced by ug::Raster< T, TDIM >::Coordinate::operator[]().
operator-=()
template<class T , int TDIM> Raster< T, TDIM >::Coordinate & ug::Raster< T, TDIM >::Coordinate::operator-= (const Coordinate & c)
References ug::Raster< T, TDIM >::Coordinate::operator*=().
Referenced by ug::Raster< T, TDIM >::Coordinate::operator+=().
operator[]() [1/2]
template<class T , int TDIM> number & ug::Raster< T, TDIM >::Coordinate::operator[] (int d)
Referenced by ug::Raster< T, TDIM >::Coordinate::set().
operator[]() [2/2]
template<class T , int TDIM> number ug::Raster< T, TDIM >::Coordinate::operator[] (int d) const
References ug::Raster< T, TDIM >::Coordinate::operator+=().
set()
template<class T , int TDIM> void ug::Raster< T, TDIM >::Coordinate::set (number c)
References ug::Raster< T, TDIM >::Coordinate::operator[]().
Referenced by ug::Raster< T, TDIM >::Coordinate::dim().
Friends And Related Function Documentation
operator<<
template<class T, int TDIM> std::ostream& operator<< (std::ostream & o, const Coordinate & coord) friend
Member Data Documentation
m_coord
template<class T, int TDIM> number ug::Raster< T, TDIM >::Coordinate::m_coord[TDIM] private
The documentation for this class was generated from the following files:
ugbase/common/util/raster.h
ugbase/common/util/raster_impl.hpp