ug4: ug::bridge::ExportedConstructor Class Reference
ug::bridge::ExportedConstructor Class Reference
ugbase » Bridge » Registry
describing information for constructor
#include <class.h>
Public Types
typedef void *(* ProxyFunc) (const ParameterStack &in)
Public Member Functions
bool check_consistency (std::string classname) const
returns true if all parameters of the function are correctly declared
void * create (const ParameterStack &paramsIn) const
executes the function
template<typename TFunc >
void create_parameter_stack ()
ExportedConstructor (ProxyFunc pf, const std::string &className, const std::string &options, const std::string &paramInfos, const std::string &tooltip, const std::string &help)
const std::string & help () const
help informations
size_t num_infos (size_t i) const
number of info strings for one parameter
size_t num_parameter () const
number of parameters.
const std::string & options () const
options
const std::string & parameter_info (size_t i, size_t j) const
type info of all parameters
const std::string & parameter_info_string () const
whole string of all type infos for of all parameters
const std::vector< std::string > & parameter_info_vec (size_t i) const
type info of i th parameters
const std::string & parameter_name (size_t i) const
name of parameter i
ParameterInfo & params_in ()
non-const export of param list
const ParameterInfo & params_in () const
parameter list for input values
const std::string & tooltip () const
gives some information to the exported functions
Protected Member Functions
void tokenize (const std::string &str, std::vector< std::string > &tokens, const char delimiter)
Private Attributes
std::string m_className
name of class constructed
std::string m_help
std::string m_options
options
std::string m_paramInfos
string with Infos about parameter
ParameterInfo m_paramsIn
ProxyFunc m_proxy_func
proxy function to call method
std::string m_tooltip
std::vector< std::vector< std::string > > m_vvParamInfo
tokenized strings for each Parameter and each Info (name | style | options | ...)
Detailed Description
describing information for constructor
Member Typedef Documentation
ProxyFunc
typedef void*(* ug::bridge::ExportedConstructor::ProxyFunc) (const ParameterStack &in)
Constructor & Destructor Documentation
ExportedConstructor()
ug::bridge::ExportedConstructor::ExportedConstructor (ProxyFunc pf, const std::string & className, const std::string & options, const std::string & paramInfos, const std::string & tooltip, const std::string & help)
References m_paramInfos, m_vvParamInfo, and tokenize().
Member Function Documentation
check_consistency()
bool ug::bridge::ExportedConstructor::check_consistency (std::string classname) const
returns true if all parameters of the function are correctly declared
References ug::bridge::ParameterInfo::parameter_named(), params_in(), ug::bridge::ParameterInfo::size(), and UG_ERR_LOG.
Referenced by ug::bridge::Registry::check_consistency().
create()
void* ug::bridge::ExportedConstructor::create (const ParameterStack & paramsIn) const inline
executes the function
Referenced by Java_edu_gcsc_vrl_ug_UG__1newInstance(), and ug::bridge::lua::LuaConstructor().
create_parameter_stack()
template<typename TFunc > void ug::bridge::ExportedConstructor::create_parameter_stack () inline
References ug::bridge::CreateParameterInfo< TTypeList >::create().
Referenced by ug::bridge::ExportedClass< TClass >::add_constructor().
help()
const std::string& ug::bridge::ExportedConstructor::help () const inline
help informations
Referenced by ug::vrl::constructor2NativeConstructor().
num_infos()
size_t ug::bridge::ExportedConstructor::num_infos (size_t i) const inline
number of info strings for one parameter
num_parameter()
size_t ug::bridge::ExportedConstructor::num_parameter () const inline
number of parameters.
Referenced by ug::vrl::params2NativeParams().
options()
const std::string& ug::bridge::ExportedConstructor::options () const inline
options
Referenced by ug::vrl::constructor2NativeConstructor().
parameter_info()
const std::string& ug::bridge::ExportedConstructor::parameter_info (size_t i, size_t j) const inline
type info of all parameters
parameter_info_string()
const std::string& ug::bridge::ExportedConstructor::parameter_info_string () const inline
whole string of all type infos for of all parameters
parameter_info_vec()
const std::vector<std::string>& ug::bridge::ExportedConstructor::parameter_info_vec (size_t i) const inline
type info of i th parameters
Referenced by ug::vrl::params2NativeParams().
parameter_name()
const std::string& ug::bridge::ExportedConstructor::parameter_name (size_t i) const inline
name of parameter i
params_in() [1/2]
ParameterInfo& ug::bridge::ExportedConstructor::params_in () inline
non-const export of param list
params_in() [2/2]
const ParameterInfo& ug::bridge::ExportedConstructor::params_in () const inline
parameter list for input values
Referenced by check_consistency(), ug::vrl::invocation::getConstructorBySignature(), Java_edu_gcsc_vrl_ug_UG__1newInstance(), ug::bridge::lua::LuaConstructor(), and ug::vrl::params2NativeParams().
tokenize()
void ug::bridge::ExportedConstructor::tokenize (const std::string & str, std::vector< std::string > & tokens, const char delimiter) protected
References ug::TrimString().
Referenced by ExportedConstructor().
tooltip()
const std::string& ug::bridge::ExportedConstructor::tooltip () const inline
gives some information to the exported functions
Referenced by ug::vrl::constructor2NativeConstructor().
Member Data Documentation
m_className
std::string ug::bridge::ExportedConstructor::m_className private
name of class constructed
m_help
std::string ug::bridge::ExportedConstructor::m_help private
m_options
std::string ug::bridge::ExportedConstructor::m_options private
options
m_paramInfos
std::string ug::bridge::ExportedConstructor::m_paramInfos private
string with Infos about parameter
Referenced by ExportedConstructor().
m_paramsIn
ParameterInfo ug::bridge::ExportedConstructor::m_paramsIn private
m_proxy_func
ProxyFunc ug::bridge::ExportedConstructor::m_proxy_func private
proxy function to call method
m_tooltip
std::string ug::bridge::ExportedConstructor::m_tooltip private
m_vvParamInfo
std::vector<std::vector<std::string> > ug::bridge::ExportedConstructor::m_vvParamInfo private
tokenized strings for each Parameter and each Info (name | style | options | ...)
Referenced by ExportedConstructor().
The documentation for this class was generated from the following files:
ugbase/registry/class.h
ugbase/registry/class.cpp