ug4: ug::bridge::IExportedClass Class Reference
ug::bridge::IExportedClass Class Reference abstract
ugbase » Bridge » Registry
Base class for exported Classes.
#include <class.h>
Public Types
typedef void(* DeleteFunction) (const void *)
Public Member Functions
virtual bool check_consistency () const
returns false is consistency-check failed
virtual const ClassNameNode & class_name_node () const =0
name node of class
virtual const std::vector< const char * > * class_names () const =0
name-list of class hierarchy
virtual bool construct_as_smart_pointer () const =0
true if the class shall be wrapped in a SmartPtr on construction
virtual void destroy (void *obj) const =0
destructur for object
virtual const ExportedMethodGroup * get_const_exported_method_group (const std::string &name) const =0
virtual const ExportedMethod & get_const_method (size_t i) const =0
get exported const-method
virtual const ExportedMethodGroup & get_const_method_group (size_t ind) const =0
returns the i-th method group (all overloads of the i-th function)
virtual const ExportedMethod & get_const_overload (size_t funcInd, size_t oInd) const =0
returns the i-th overload of a const method
virtual const ExportedConstructor & get_constructor (size_t i) const =0
get exported constructor
virtual DeleteFunction get_delete_function () const =0
returns a function which will call delete on the object
virtual const ExportedMethodGroup * get_exported_method_group (const std::string &name) const =0
virtual const boost::optional< ExportedConstructor & > get_json_constructor () const =0
get constructor for construction from json
virtual const ExportedMethod & get_method (size_t i) const =0
get exported method
virtual const ExportedMethodGroup & get_method_group (size_t ind) const =0
returns the i-th method group (all overloads of the i-th function)
virtual const ExportedMethod & get_overload (size_t funcInd, size_t oInd) const =0
returns the i-th overload of a method
virtual const std::string & group () const =0
get groups
virtual bool is_instantiable () const =0
virtual bool is_json_constructible () const =0
get constructor for construction from json
virtual const std::string & name () const =0
name of class
virtual size_t num_const_methods () const =0
number of registered const-methods
virtual size_t num_const_overloads (size_t funcInd) const =0
returns the number of overloads of a const method
virtual size_t num_constructors () const =0
number of registered constructors
virtual size_t num_methods () const =0
number of method of the class
virtual size_t num_overloads (size_t funcInd) const =0
returns the number of overloads of a method
virtual const std::string & tooltip () const =0
get tooltip
virtual ~IExportedClass ()
virtual destructor
Detailed Description
Base class for exported Classes.
Member Typedef Documentation
DeleteFunction
typedef void(* ug::bridge::IExportedClass::DeleteFunction) (const void *)
Constructor & Destructor Documentation
~IExportedClass()
virtual ug::bridge::IExportedClass::~IExportedClass () inline virtual
virtual destructor
Member Function Documentation
check_consistency()
bool ug::bridge::IExportedClass::check_consistency () const virtual
returns false is consistency-check failed
References ug::baseName(), class_names(), name(), and UG_ERR_LOG.
Referenced by ug::bridge::Registry::check_consistency().
class_name_node()
virtual const ClassNameNode& ug::bridge::IExportedClass::class_name_node () const pure virtual
name node of class
Implemented in ug::bridge::ExportedClass< TClass >.
Referenced by ug::bridge::lua::CreateBindings_LUA().
class_names()
virtual const std::vector<const char*>* ug::bridge::IExportedClass::class_names () const pure virtual
name-list of class hierarchy
Implemented in ug::bridge::ExportedClass< TClass >.
Referenced by check_consistency(), ug::vrl::classes2NativeClasses(), ug::bridge::ClassHierarchyString(), ug::bridge::ClassUsage(), ug::bridge::lua::CreateBindings_LUA(), ug::bridge::lua::GetBestMatchingMember(), ug::vrl::getParentClasses(), ug::bridge::ClassHierarchy::insert_class(), and ug::bridge::UGTypeInfo().
construct_as_smart_pointer()
virtual bool ug::bridge::IExportedClass::construct_as_smart_pointer () const pure virtual
true if the class shall be wrapped in a SmartPtr on construction
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::bridge::Registry::check_consistency(), Java_edu_gcsc_vrl_ug_UG__1newInstance(), and ug::bridge::lua::LuaConstructor().
destroy()
virtual void ug::bridge::IExportedClass::destroy (void * obj) const pure virtual
destructur for object
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by Java_edu_gcsc_vrl_ug_UG__1delete().
get_const_exported_method_group()
virtual const ExportedMethodGroup* ug::bridge::IExportedClass::get_const_exported_method_group (const std::string & name) const pure virtual
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::vrl::invocation::getMethodBySignature().
get_const_method()
virtual const ExportedMethod& ug::bridge::IExportedClass::get_const_method (size_t i) const pure virtual
get exported const-method
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::bridge::Registry::check_consistency(), ug::bridge::ClassInfo(), ug::bridge::ClassUsageExact(), ug::bridge::lua::GetBestMatchingMember(), ug::bridge::GetMemberFunctionCompletitions(), and ug::bridge::GetMemberFunctionInfo().
get_const_method_group()
virtual const ExportedMethodGroup& ug::bridge::IExportedClass::get_const_method_group (size_t ind) const pure virtual
returns the i-th method group (all overloads of the i-th function)
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::bridge::lua::CreateBindings_LUA().
get_const_overload()
virtual const ExportedMethod& ug::bridge::IExportedClass::get_const_overload (size_t funcInd, size_t oInd) const pure virtual
returns the i-th overload of a const method
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::vrl::methods2NativeGroups().
get_constructor()
virtual const ExportedConstructor& ug::bridge::IExportedClass::get_constructor (size_t i) const pure virtual
get exported constructor
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::bridge::Registry::check_consistency(), ug::vrl::constructors2NativeConstructors(), ug::vrl::invocation::getConstructorBySignature(), and ug::bridge::lua::LuaConstructor().
get_delete_function()
virtual DeleteFunction ug::bridge::IExportedClass::get_delete_function () const pure virtual
returns a function which will call delete on the object
Implemented in ug::bridge::ExportedClass< TClass >.
Referenced by Java_edu_gcsc_vrl_ug_UG__1newInstance(), and ug::bridge::lua::LuaConstructor().
get_exported_method_group()
virtual const ExportedMethodGroup* ug::bridge::IExportedClass::get_exported_method_group (const std::string & name) const pure virtual
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::vrl::invocation::getMethodBySignature().
get_json_constructor()
virtual const boost::optional<ExportedConstructor&> ug::bridge::IExportedClass::get_json_constructor () const pure virtual
get constructor for construction from json
Implemented in ug::bridge::ExportedClassBaseImpl.
get_method()
virtual const ExportedMethod& ug::bridge::IExportedClass::get_method (size_t i) const pure virtual
get exported method
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::bridge::Registry::check_consistency(), ug::bridge::ClassInfo(), ug::bridge::ClassUsageExact(), ug::bridge::lua::GetBestMatchingMember(), ug::bridge::GetMemberFunctionCompletitions(), and ug::bridge::GetMemberFunctionInfo().
get_method_group()
virtual const ExportedMethodGroup& ug::bridge::IExportedClass::get_method_group (size_t ind) const pure virtual
returns the i-th method group (all overloads of the i-th function)
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::bridge::lua::CreateBindings_LUA().
get_overload()
virtual const ExportedMethod& ug::bridge::IExportedClass::get_overload (size_t funcInd, size_t oInd) const pure virtual
returns the i-th overload of a method
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::vrl::methods2NativeGroups().
group()
virtual const std::string& ug::bridge::IExportedClass::group () const pure virtual
get groups
Implemented in ug::bridge::ExportedClass< TClass >.
Referenced by ug::vrl::classes2NativeClasses(), ug::bridge::ClassHierarchy::insert_class(), and ug::script::UGGetClassGroup().
is_instantiable()
virtual bool ug::bridge::IExportedClass::is_instantiable () const pure virtual
can we create instances of this class (i.e. the class does not contain pure virtual functions)
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::bridge::Registry::check_consistency(), ug::vrl::classes2NativeClasses(), ug::bridge::ClassInfo(), and ug::bridge::lua::CreateBindings_LUA().
is_json_constructible()
virtual bool ug::bridge::IExportedClass::is_json_constructible () const pure virtual
get constructor for construction from json
Implemented in ug::bridge::ExportedClass< TClass >.
Referenced by ug::bridge::ExportedClassBaseImpl::get_json_constructor().
name()
virtual const std::string& ug::bridge::IExportedClass::name () const pure virtual
name of class
Implemented in ug::bridge::ExportedClass< TClass >.
Referenced by ug::bridge::Registry::check_consistency(), check_consistency(), ug::vrl::classes2NativeClasses(), ug::vrl::classGroups2NativeClassGroups(), ug::bridge::ClassInfo(), ug::bridge::ClassUsageExact(), ug::bridge::ExportedClassBaseImpl::constmethodname_registered(), ug::bridge::lua::CreateBindings_LUA(), ug::bridge::ExportedClassBaseImpl::get_const_exported_method_group(), ug::bridge::ExportedClassBaseImpl::get_exported_method_group(), ug::bridge::GetClassesCompletitions(), ug::vrl::invocation::initClasses(), Java_edu_gcsc_vrl_ug_UG__1getDefaultClassNameFromGroup(), Java_edu_gcsc_vrl_ug_UG__1invokeMethod(), Java_edu_gcsc_vrl_ug_UG__1newInstance(), ug::bridge::lua::LuaConstructor(), ug::bridge::LuaList_classes(), ug::bridge::lua::LuaToStringDefault(), ug::bridge::ExportedClassBaseImpl::methodname_registered(), and ug::bridge::UGTypeInfo().
num_const_methods()
virtual size_t ug::bridge::IExportedClass::num_const_methods () const pure virtual
number of registered const-methods
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::bridge::Registry::check_consistency(), ug::bridge::ClassInfo(), ug::bridge::ClassUsageExact(), ug::bridge::lua::CreateBindings_LUA(), ug::bridge::lua::GetBestMatchingMember(), ug::bridge::GetMemberFunctionCompletitions(), ug::bridge::GetMemberFunctionInfo(), and ug::vrl::methods2NativeGroups().
num_const_overloads()
virtual size_t ug::bridge::IExportedClass::num_const_overloads (size_t funcInd) const pure virtual
returns the number of overloads of a const method
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::vrl::methods2NativeGroups().
num_constructors()
virtual size_t ug::bridge::IExportedClass::num_constructors () const pure virtual
number of registered constructors
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::bridge::Registry::check_consistency(), ug::vrl::constructors2NativeConstructors(), ug::vrl::invocation::getConstructorBySignature(), and ug::bridge::lua::LuaConstructor().
num_methods()
virtual size_t ug::bridge::IExportedClass::num_methods () const pure virtual
number of method of the class
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::bridge::Registry::check_consistency(), ug::bridge::ClassInfo(), ug::bridge::ClassUsageExact(), ug::bridge::lua::CreateBindings_LUA(), ug::bridge::lua::GetBestMatchingMember(), ug::bridge::GetMemberFunctionCompletitions(), ug::bridge::GetMemberFunctionInfo(), and ug::vrl::methods2NativeGroups().
num_overloads()
virtual size_t ug::bridge::IExportedClass::num_overloads (size_t funcInd) const pure virtual
returns the number of overloads of a method
Implemented in ug::bridge::ExportedClassBaseImpl.
Referenced by ug::vrl::methods2NativeGroups().
tooltip()
virtual const std::string& ug::bridge::IExportedClass::tooltip () const pure virtual
get tooltip
Implemented in ug::bridge::ExportedClassBaseImpl.
The documentation for this class was generated from the following files:
ugbase/registry/class.h
ugbase/registry/class.cpp