ug4: ug::AnisotropicBalanceWeights< dim > Class Template Reference
ug::AnisotropicBalanceWeights< dim > Class Template Reference
The higher the volume, the higher the weight when anisotropic refinement is used...
#include <load_balancer_util.h>
Public Types
typedef GeomObjBaseTypeByDim< dim >::base_obj_type elem_t
typedef Attachment< MathVector< dim > > position_attachment_t
Public Member Functions
AnisotropicBalanceWeights ()
virtual number get_weight (Edge *e)
virtual number get_weight (Face *e)
virtual number get_weight (Vertex *e)
virtual number get_weight (Volume *e)
virtual void refresh_weights (int baseLevel)
virtual void set_grid (MultiGrid *mg, Attachment< MathVector< dim > > aPos)
virtual void set_weight_factor (number weightFactor)
virtual number weight_factor () const
virtual ~AnisotropicBalanceWeights ()
Public Member Functions inherited from ug::IBalanceWeights
virtual number get_refined_weight (Edge *e)
virtual number get_refined_weight (Face *e)
todo: use a more sophisticated implementation
virtual number get_refined_weight (Vertex *e)
virtual number get_refined_weight (Volume *e)
todo: use a more sophisticated implementation
virtual bool has_level_offsets ()
virtual ~IBalanceWeights ()
virtual bool consider_in_level_above (Vertex *)
Relative indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Edge *)
Relative indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Face *)
Relative indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Volume *)
Relative indicator in which level the specifed elements should be partitioned.
Private Member Functions
number get_weight_impl (elem_t *e)
number get_weight_impl (GridObject *e)
Private Attributes
Grid::VertexAttachmentAccessor< position_attachment_t > m_aaPos
number m_weightFactor
Detailed Description
template<int dim>
class ug::AnisotropicBalanceWeights< dim >
The higher the volume, the higher the weight when anisotropic refinement is used...
Member Typedef Documentation
elem_t
template<int dim> typedef GeomObjBaseTypeByDim<dim>::base_obj_type ug::AnisotropicBalanceWeights< dim >::elem_t
position_attachment_t
template<int dim> typedef Attachment<MathVector<dim> > ug::AnisotropicBalanceWeights< dim >::position_attachment_t
Constructor & Destructor Documentation
AnisotropicBalanceWeights()
template<int dim> ug::AnisotropicBalanceWeights< dim >::AnisotropicBalanceWeights () inline
~AnisotropicBalanceWeights()
template<int dim> virtual ug::AnisotropicBalanceWeights< dim >::~AnisotropicBalanceWeights () inline virtual
Member Function Documentation
get_weight() [1/4]
template<int dim> virtual number ug::AnisotropicBalanceWeights< dim >::get_weight (Edge * e) inline virtual
Reimplemented from ug::IBalanceWeights.
References ug::AnisotropicBalanceWeights< dim >::get_weight_impl().
get_weight() [2/4]
template<int dim> virtual number ug::AnisotropicBalanceWeights< dim >::get_weight (Face * e) inline virtual
Reimplemented from ug::IBalanceWeights.
References ug::AnisotropicBalanceWeights< dim >::get_weight_impl().
get_weight() [3/4]
template<int dim> virtual number ug::AnisotropicBalanceWeights< dim >::get_weight (Vertex * e) inline virtual
Reimplemented from ug::IBalanceWeights.
get_weight() [4/4]
template<int dim> virtual number ug::AnisotropicBalanceWeights< dim >::get_weight (Volume * e) inline virtual
Reimplemented from ug::IBalanceWeights.
References ug::AnisotropicBalanceWeights< dim >::get_weight_impl().
get_weight_impl() [1/2]
template<int dim> number ug::AnisotropicBalanceWeights< dim >::get_weight_impl (elem_t * e) inline private
References ug::CalculateVolume(), ug::AnisotropicBalanceWeights< dim >::m_aaPos, and ug::AnisotropicBalanceWeights< dim >::m_weightFactor.
Referenced by ug::AnisotropicBalanceWeights< dim >::get_weight().
get_weight_impl() [2/2]
template<int dim> number ug::AnisotropicBalanceWeights< dim >::get_weight_impl (GridObject * e) inline private
refresh_weights()
template<int dim> virtual void ug::AnisotropicBalanceWeights< dim >::refresh_weights (int baseLevel) inline virtual
Reimplemented from ug::IBalanceWeights.
set_grid()
template<int dim> virtual void ug::AnisotropicBalanceWeights< dim >::set_grid (MultiGrid * mg, Attachment< MathVector< dim > > aPos) inline virtual
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), and ug::AnisotropicBalanceWeights< dim >::m_aaPos.
set_weight_factor()
template<int dim> virtual void ug::AnisotropicBalanceWeights< dim >::set_weight_factor (number weightFactor) inline virtual
References ug::AnisotropicBalanceWeights< dim >::m_weightFactor.
weight_factor()
template<int dim> virtual number ug::AnisotropicBalanceWeights< dim >::weight_factor () const inline virtual
References ug::AnisotropicBalanceWeights< dim >::m_weightFactor.
Member Data Documentation
m_aaPos
template<int dim> Grid::VertexAttachmentAccessor<position_attachment_t> ug::AnisotropicBalanceWeights< dim >::m_aaPos private
Referenced by ug::AnisotropicBalanceWeights< dim >::get_weight_impl(), and ug::AnisotropicBalanceWeights< dim >::set_grid().
m_weightFactor
template<int dim> number ug::AnisotropicBalanceWeights< dim >::m_weightFactor private
Referenced by ug::AnisotropicBalanceWeights< dim >::get_weight_impl(), ug::AnisotropicBalanceWeights< dim >::set_weight_factor(), and ug::AnisotropicBalanceWeights< dim >::weight_factor().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/load_balancer_util.h