ug4: ug::ConstrainedFace Class Reference
ug::ConstrainedFace Class Reference
This class stores the constraining object.
#include <grid_objects_2d.h>
Public Member Functions
ConstrainedFace ()
GridObject * get_constraining_object ()
int get_parent_base_object_id ()
virtual bool is_constrained () const
returns true if the object is constrained by other objects.
virtual void remove_constraint_link (const Face *f)
removes a constraint link to the grid object.
void set_constraining_object (GridObject *pObj)
void set_parent_base_object_id (int id)
virtual ~ConstrainedFace ()
Public Member Functions inherited from ug::Face
virtual int base_object_id () const
virtual bool collapse_edge (std::vector< Face * > &vNewFacesOut, int edgeIndex, Vertex *newVertex, Vertex **pSubstituteVertices=NULL)
virtual bool collapse_edges (std::vector< Face * > &vNewFacesOut, std::vector< Vertex * > &vNewEdgeVertices, Vertex **pSubstituteVertices=NULL)
virtual int container_section () const
virtual Edge * create_edge (int index)
create the edge with index i and return it.
virtual void create_faces_by_edge_split (int splitEdgeIndex, Vertex *newVertex, std::vector< Face * > &vNewFacesOut, Vertex **pSubstituteVertices=NULL)
virtual EdgeDescriptor edge_desc (int index) const
returns the i-th edge of the face.
virtual void edge_desc (int index, EdgeDescriptor &edOut) const
returns the i-th edge of the face.
int get_local_side_index (EdgeVertices *e) const
returns the local index of the specified edge.
virtual std::pair< GridBaseObjectId, int > get_opposing_object (Vertex *vrt) const
returns an index to the obbject, which lies on the opposite side of the face to the given vertex.
virtual bool get_opposing_side (EdgeVertices *e, EdgeDescriptor &edOut) const
retrieves the edge-descriptor for the opposing side to the specified one.
virtual bool is_regular_ref_rule (int edgeMarks) const
returns true if the specified edgeMarks would lead to a regular refinement
uint num_edges () const
uint num_sides () const
virtual ReferenceObjectID reference_object_id () const
virtual bool refine (std::vector< Face * > &vNewFacesOut, Vertex **newFaceVertexOut, Vertex **newEdgeVertices, Vertex *newFaceVertex=NULL, Vertex **pSubstituteVertices=NULL, int snapPointIndex=-1)
virtual ~Face ()
Public Member Functions inherited from ug::GridObject
virtual GridObject * create_empty_instance () const
create an instance of the derived type
uint grid_data_index () const
Returns the grid attachment data index of a geometric object.
virtual bool is_constraining () const
returns the id of the reference-object.
virtual ~GridObject ()
virtual void remove_constraint_link (const Vertex *vrt)
removes a constraint link to the grid object.
virtual void remove_constraint_link (const Edge *e)
removes a constraint link to the grid object.
Public Member Functions inherited from ug::FaceVertices
virtual size_t num_vertices () const
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual Vertex * vertex (size_t index) const
virtual ConstVertexArray vertices () const
virtual ~FaceVertices ()
Public Member Functions inherited from ug::IVertexGroup
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~IVertexGroup ()
Static Public Member Functions
static bool type_match (GridObject *pObj)
Static Public Member Functions inherited from ug::Face
static bool type_match (GridObject *pObj)
Protected Attributes
int m_parentBaseObjectId
GridObject * m_pConstrainingObject
Protected Attributes inherited from ug::GridObject
uint m_gridDataIndex
Additional Inherited Members
Public Types inherited from ug::Face
typedef Face grid_base_object
typedef Volume higher_dim_base_object
typedef Edge lower_dim_base_object
typedef Edge side
typedef Volume sideof
Public Types inherited from ug::IVertexGroup
typedef Vertex *const * ConstVertexArray
Static Public Attributes inherited from ug::Face
static const int BASE_OBJECT_ID = FACE
static const bool CAN_BE_SIDE = true
static const int dim = 2
reference dimension
static const bool HAS_SIDES = true
Protected Member Functions inherited from ug::Face
virtual void set_vertex (uint index, Vertex *pVrt)
Protected Member Functions inherited from ug::GridObject
void set_grid_data_index (uint index)
ATTENTION: Use this method with extreme care!
Detailed Description
This class stores the constraining object.
Please note, that the user is has to link and unlink constraining objects manually.
Constructor & Destructor Documentation
ConstrainedFace()
ug::ConstrainedFace::ConstrainedFace () inline
~ConstrainedFace()
virtual ug::ConstrainedFace::~ConstrainedFace () inline virtual
Member Function Documentation
get_constraining_object()
GridObject* ug::ConstrainedFace::get_constraining_object () inline
Referenced by ug::CheckHangingNodeConsistency(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_face(), and ug::SerializeMultiGridElements().
get_parent_base_object_id()
int ug::ConstrainedFace::get_parent_base_object_id () inline
Referenced by ug::HangingNodeRefinerBase< TSelector >::process_constrained_face(), and ug::SerializeMultiGridElements().
is_constrained()
virtual bool ug::ConstrainedFace::is_constrained () const inline virtual
returns true if the object is constrained by other objects.
This is normally only the case for special constrained objects. The default implementation returns false.
Reimplemented from ug::GridObject.
remove_constraint_link()
virtual void ug::ConstrainedFace::remove_constraint_link (const Face * f) inline virtual
removes a constraint link to the grid object.
This method is e.g. called on the constraining edges of a constrained vertex as soon as the constrained vertex is deleted.
Reimplemented from ug::GridObject.
set_constraining_object()
void ug::ConstrainedFace::set_constraining_object (GridObject * pObj) inline
References ug::GridObject::base_object_id().
Referenced by ug::DeserializeMultiGridElements(), ug::GridReaderUGX::grid(), ug::HangingNodeRefiner_MultiGrid::perform_coarsening(), and ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex().
set_parent_base_object_id()
void ug::ConstrainedFace::set_parent_base_object_id (int id) inline
References UG_THROW.
Referenced by ug::DeserializeMultiGridElements(), and ug::HangingNodeRefiner_MultiGrid::perform_coarsening().
type_match()
static bool ug::ConstrainedFace::type_match (GridObject * pObj) inline static
Member Data Documentation
m_parentBaseObjectId
int ug::ConstrainedFace::m_parentBaseObjectId protected
m_pConstrainingObject
GridObject* ug::ConstrainedFace::m_pConstrainingObject protected
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid_objects/grid_objects_2d.h