ug4: ug::MGHNodeAdjuster Class Reference
ug::MGHNodeAdjuster Class Reference
Makes sure that that hierarchical dependencies are considered during hnode refinement.
#include <mg_hnode_adjuster.h>
Public Member Functions
virtual void ref_marks_changed (IRefiner &ref, const std::vector< Vertex * > &vrts, const std::vector< Edge * > &edges, const std::vector< Face * > &faces, const std::vector< Volume * > &vols)
virtual ~MGHNodeAdjuster ()
Public Member Functions inherited from ug::IRefMarkAdjuster
virtual void coarsen_marks_changed (IRefiner &ref, const std::vector< Vertex * > &vrts, const std::vector< Edge * > &edges, const std::vector< Face * > &faces, const std::vector< Volume * > &vols)
virtual void enable (bool enable)
virtual bool enabled () const
IRefMarkAdjuster ()
virtual ~IRefMarkAdjuster ()
void enable_node_dependency_order_1 (bool bEnable)
enables or disables node-dependency-order-1.
bool node_dependency_order_1_enabled ()
enables or disables node-dependency-order-1.
Static Public Member Functions
static SPMGHNodeAdjuster create ()
Detailed Description
Makes sure that that hierarchical dependencies are considered during hnode refinement.
This adjuster regards the grid as a serial grid. If the grid represents a part of a distributed grid, then the additional use of a parallel adjuster is required.
Constructor & Destructor Documentation
~MGHNodeAdjuster()
virtual ug::MGHNodeAdjuster::~MGHNodeAdjuster () inline virtual
Member Function Documentation
create()
static SPMGHNodeAdjuster ug::MGHNodeAdjuster::create () inline static
Referenced by ug::HangingNodeRefiner_MultiGrid::HangingNodeRefiner_MultiGrid().
ref_marks_changed()
void ug::MGHNodeAdjuster::ref_marks_changed (IRefiner & ref, const std::vector< Vertex * > & vrts, const std::vector< Edge * > & edges, const std::vector< Face * > & faces, const std::vector< Volume * > & vols) virtual
Reimplemented from ug::IRefMarkAdjuster.
References ug::Grid::associated_elements(), ug::IRefiner::get_mark(), ug::MultiGrid::get_parent(), ug::IRefiner::grid(), ug::MultiGrid::has_children(), ug::GridObject::is_constrained(), ug::IRefiner::mark(), ug::MultiGrid::num_child_vertices(), ug::EdgeVertices::num_vertices(), ug::FaceVertices::num_vertices(), ug::VolumeVertices::num_vertices(), ug::RM_DUMMY, ug::RM_NONE, ug::PointerConstArray< TPtr >::size(), UG_ASSERT, ug::EdgeVertices::vertex(), ug::FaceVertices::vertex(), and ug::VolumeVertices::vertex().
The documentation for this class was generated from the following files:
ugbase/lib_grid/refinement/ref_mark_adjusters/mg_hnode_adjuster.h
ugbase/lib_grid/refinement/ref_mark_adjusters/mg_hnode_adjuster.cpp