ug4: ug::HorizontalAnisotropyAdjuster< TAPos > Class Template Reference
ug::HorizontalAnisotropyAdjuster< TAPos > Class Template Reference
Selects additional edges to preserve layers in a grid with horizontal anisotropies.
#include <horizontal_anisotropy_adjuster.h>
Public Types
typedef Grid::VertexAttachmentAccessor< TAPos > position_accessor_t
typedef TAPos position_attachment_t
Public Member Functions
HorizontalAnisotropyAdjuster (TAPos aPos)
virtual void ref_marks_changed (IRefiner &ref, const std::vector< Vertex * > &vrts, const std::vector< Edge * > &edges, const std::vector< Face * > &faces, const std::vector< Volume * > &vols)
virtual ~HorizontalAnisotropyAdjuster ()
Public Member Functions inherited from ug::IRefMarkAdjuster
virtual void coarsen_marks_changed (IRefiner &ref, const std::vector< Vertex * > &vrts, const std::vector< Edge * > &edges, const std::vector< Face * > &faces, const std::vector< Volume * > &vols)
virtual void enable (bool enable)
virtual bool enabled () const
IRefMarkAdjuster ()
virtual ~IRefMarkAdjuster ()
void enable_node_dependency_order_1 (bool bEnable)
enables or disables node-dependency-order-1.
bool node_dependency_order_1_enabled ()
enables or disables node-dependency-order-1.
Private Attributes
TAPos m_aPos
Detailed Description
template<class TAPos>
class ug::HorizontalAnisotropyAdjuster< TAPos >
Selects additional edges to preserve layers in a grid with horizontal anisotropies.
Selects additional edges to preserve layers in a grid with horizontal anisotropies and builds a closure so that no hanging nodes are generated.
Note
This adjuster regards the grid as a serial grid. If the grid represents a part of a distributed grid, then the additional use of a parallel adjuster is required.
Member Typedef Documentation
position_accessor_t
template<class TAPos > typedef Grid::VertexAttachmentAccessor<TAPos> ug::HorizontalAnisotropyAdjuster< TAPos >::position_accessor_t
position_attachment_t
template<class TAPos > typedef TAPos ug::HorizontalAnisotropyAdjuster< TAPos >::position_attachment_t
Constructor & Destructor Documentation
HorizontalAnisotropyAdjuster()
template<class TAPos > ug::HorizontalAnisotropyAdjuster< TAPos >::HorizontalAnisotropyAdjuster (TAPos aPos) inline
~HorizontalAnisotropyAdjuster()
template<class TAPos > virtual ug::HorizontalAnisotropyAdjuster< TAPos >::~HorizontalAnisotropyAdjuster () inline virtual
Member Function Documentation
ref_marks_changed()
template<class TAPos > void ug::HorizontalAnisotropyAdjuster< TAPos >::ref_marks_changed (IRefiner & ref, const std::vector< Vertex * > & vrts, const std::vector< Edge * > & edges, const std::vector< Face * > & faces, const std::vector< Volume * > & vols) virtual
Reimplemented from ug::IRefMarkAdjuster.
References ug::Grid::associated_elements(), end_for, for_each_in_vec, ug::IRefiner::get_mark(), ug::IRefiner::grid(), ug::IsVertical(), ug::IRefiner::mark(), ug::NotVertical(), ug::Grid::num_faces(), ug::Grid::num_volumes(), ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_REFINE, UG_COND_THROW, and ug::EdgeVertices::vertex().
Member Data Documentation
m_aPos
template<class TAPos > TAPos ug::HorizontalAnisotropyAdjuster< TAPos >::m_aPos private
The documentation for this class was generated from the following files:
ugbase/lib_grid/refinement/ref_mark_adjusters/horizontal_anisotropy_adjuster.h
ugbase/lib_grid/refinement/ref_mark_adjusters/horizontal_anisotropy_adjuster.cpp