ug4: ug::ComPol_NewConstrainedVerticals< TLayout > Class Template Reference
ug::ComPol_NewConstrainedVerticals< TLayout > Class Template Reference
Classes
struct Entry
Public Types
typedef Layout::Element Element
typedef Layout::Type GeomObj
typedef Layout::Interface Interface
typedef Interface::const_iterator InterfaceIter
typedef TLayout Layout
Public Types inherited from pcl::ICommunicationPolicy< TLayout >
typedef Layout::Interface Interface
typedef TLayout Layout
Public Member Functions
virtual bool collect (ug::BinaryBuffer &buff, const Interface &interface)
should write data which is associated with the interface elements to the buffer.
ComPol_NewConstrainedVerticals (DistributedGridManager *dgm, std::vector< GeomObj * > &newConstrained)
void create_initial_hash_entry (GeomObj *e)
void exchange_data ()
virtual bool extract (ug::BinaryBuffer &buff, const Interface &interface)
extract data from the buffer and assigns it to the interface-elements.
std::pair< int, int > get_h_master_info (GeomObj *o)
virtual int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
std::vector< int > & other_v_masters (GeomObj *o)
virtual ~ComPol_NewConstrainedVerticals ()
Public Member Functions inherited from pcl::ICommunicationPolicy< TLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual ~ICommunicationPolicy ()
Private Attributes
DistributedGridManager * m_dgm
bool m_exchangeVMasterRanks
Hash< GeomObj *, Entry > m_hash
bool m_initialHandshake
int m_localHMasterCount
std::vector< GeomObj * > & m_newConstrained
Member Typedef Documentation
Element
template<class TLayout > typedef Layout::Element ug::ComPol_NewConstrainedVerticals< TLayout >::Element
GeomObj
template<class TLayout > typedef Layout::Type ug::ComPol_NewConstrainedVerticals< TLayout >::GeomObj
Interface
template<class TLayout > typedef Layout::Interface ug::ComPol_NewConstrainedVerticals< TLayout >::Interface
InterfaceIter
template<class TLayout > typedef Interface::const_iterator ug::ComPol_NewConstrainedVerticals< TLayout >::InterfaceIter
Layout
template<class TLayout > typedef TLayout ug::ComPol_NewConstrainedVerticals< TLayout >::Layout
Constructor & Destructor Documentation
ComPol_NewConstrainedVerticals()
template<class TLayout > ug::ComPol_NewConstrainedVerticals< TLayout >::ComPol_NewConstrainedVerticals (DistributedGridManager * dgm, std::vector< GeomObj * > & newConstrained) inline
Note that a reference to newConstrained is passed to the constructor and that its content may be changed by some methods in this class.
References ug::ComPol_NewConstrainedVerticals< TLayout >::create_initial_hash_entry(), and ug::ComPol_NewConstrainedVerticals< TLayout >::m_hash.
~ComPol_NewConstrainedVerticals()
template<class TLayout > virtual ug::ComPol_NewConstrainedVerticals< TLayout >::~ComPol_NewConstrainedVerticals () inline virtual
Member Function Documentation
collect()
template<class TLayout > virtual bool ug::ComPol_NewConstrainedVerticals< TLayout >::collect (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
should write data which is associated with the interface elements to the buffer.
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::DistributedGridManager::collect_interface_entries(), ug::DistributedGridManager::contains_status(), ug::ES_V_SLAVE, ug::ComPol_NewConstrainedVerticals< TLayout >::Entry::hmasterProcInfo, ug::ComPol_NewConstrainedVerticals< TLayout >::m_dgm, ug::ComPol_NewConstrainedVerticals< TLayout >::m_exchangeVMasterRanks, ug::ComPol_NewConstrainedVerticals< TLayout >::m_hash, ug::ComPol_NewConstrainedVerticals< TLayout >::m_initialHandshake, ug::Serialize(), and UG_ASSERT.
create_initial_hash_entry()
template<class TLayout > void ug::ComPol_NewConstrainedVerticals< TLayout >::create_initial_hash_entry (GeomObj * e) inline
References ug::DistributedGridManager::collect_interface_entries(), ug::DistributedGridManager::contains_status(), ug::ES_H_MASTER, ug::ES_H_SLAVE, ug::ES_V_MASTER, ug::DistributedGridManager::get_assigned_grid(), ug::GetGridObjectCenter(), ug::ComPol_NewConstrainedVerticals< TLayout >::m_dgm, ug::ComPol_NewConstrainedVerticals< TLayout >::m_hash, ug::ComPol_NewConstrainedVerticals< TLayout >::m_localHMasterCount, pcl::ProcRank(), and UG_ASSERT.
Referenced by ug::ComPol_NewConstrainedVerticals< TLayout >::ComPol_NewConstrainedVerticals(), and ug::ComPol_NewConstrainedVerticals< TLayout >::extract().
exchange_data()
template<class TLayout > void ug::ComPol_NewConstrainedVerticals< TLayout >::exchange_data () inline
References pcl::InterfaceCommunicator< TLayout >::communicate(), ug::DistributedGridManager::contains_status(), ug::ES_H_SLAVE, pcl::InterfaceCommunicator< TLayout >::exchange_data(), ug::DistributedGridManager::grid_layout_map(), ug::ComPol_NewConstrainedVerticals< TLayout >::Entry::hmasterProcInfo, ug::INT_V_MASTER, ug::INT_V_SLAVE, ug::LIB_GRID, ug::ComPol_NewConstrainedVerticals< TLayout >::m_dgm, ug::ComPol_NewConstrainedVerticals< TLayout >::m_exchangeVMasterRanks, ug::ComPol_NewConstrainedVerticals< TLayout >::m_hash, ug::ComPol_NewConstrainedVerticals< TLayout >::m_initialHandshake, ug::ComPol_NewConstrainedVerticals< TLayout >::m_localHMasterCount, ug::ComPol_NewConstrainedVerticals< TLayout >::m_newConstrained, pcl::ProcRank(), and UG_DLOG.
Referenced by ug::DistributedGridManager::create_missing_constrained_h_interfaces().
extract()
template<class TLayout > virtual bool ug::ComPol_NewConstrainedVerticals< TLayout >::extract (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
extract data from the buffer and assigns it to the interface-elements.
If this method is called between calls to begin_layout_extraction and end_layout_extraction, the interface that is passed to this method belongs to the layout.
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::DistributedGridManager::contains_status(), ug::ComPol_NewConstrainedVerticals< TLayout >::create_initial_hash_entry(), ug::Deserialize(), ug::ElementDebugInfo(), ug::ES_V_MASTER, ug::DistributedGridManager::get_assigned_grid(), ug::ComPol_NewConstrainedVerticals< TLayout >::Entry::hmasterProcInfo, ug::ComPol_NewConstrainedVerticals< TLayout >::m_dgm, ug::ComPol_NewConstrainedVerticals< TLayout >::m_exchangeVMasterRanks, ug::ComPol_NewConstrainedVerticals< TLayout >::m_hash, ug::ComPol_NewConstrainedVerticals< TLayout >::m_initialHandshake, ug::ComPol_NewConstrainedVerticals< TLayout >::m_newConstrained, ug::ComPol_NewConstrainedVerticals< TLayout >::Entry::otherVMasterRanks, pcl::ProcRank(), and UG_ASSERT.
get_h_master_info()
template<class TLayout > std::pair<int, int> ug::ComPol_NewConstrainedVerticals< TLayout >::get_h_master_info (GeomObj * o) inline
returns a std::pair<int, int> where 'first' represents the h-master rank and where 'second' defines the order in which entries have to be added to the h-interface.
References ug::ComPol_NewConstrainedVerticals< TLayout >::m_hash.
Referenced by ug::DistributedGridManager::create_missing_constrained_h_interfaces().
get_required_buffer_size()
template<class TLayout > virtual int ug::ComPol_NewConstrainedVerticals< TLayout >::get_required_buffer_size (const Interface & interface) inline virtual
returns the size of the buffer in bytes, that will be required for interface-communication.
Determines the size of the buffer on which the extract and receive methods for the given interface will operate. If the buffer-size can't be calculated on both sides (sender and receiver) this method should return -1. This will lead to an additional communication step in which buffer-sizes will be exchanged. If the buffer-size can be calculated on both sides, it makes sense to do so, since this leads to less communication and overall improved performance. The buffer-size has to exactly match the size of required memory. Make sure that you completely fill the buffer during collect(...) and that you read all data during extract(...). The default implementation returns -1.
Reimplemented from pcl::ICommunicationPolicy< TLayout >.
other_v_masters()
template<class TLayout > std::vector<int>& ug::ComPol_NewConstrainedVerticals< TLayout >::other_v_masters (GeomObj * o) inline
returns the array of other v-master procs which build an interface to the local proc, if the local proc will be the new h-master proc and if it is also a v-master proc.
References ug::ComPol_NewConstrainedVerticals< TLayout >::m_hash.
Referenced by ug::DistributedGridManager::create_missing_constrained_h_interfaces().
Member Data Documentation
m_dgm
template<class TLayout > DistributedGridManager* ug::ComPol_NewConstrainedVerticals< TLayout >::m_dgm private
Referenced by ug::ComPol_NewConstrainedVerticals< TLayout >::collect(), ug::ComPol_NewConstrainedVerticals< TLayout >::create_initial_hash_entry(), ug::ComPol_NewConstrainedVerticals< TLayout >::exchange_data(), and ug::ComPol_NewConstrainedVerticals< TLayout >::extract().
m_exchangeVMasterRanks
template<class TLayout > bool ug::ComPol_NewConstrainedVerticals< TLayout >::m_exchangeVMasterRanks private
Referenced by ug::ComPol_NewConstrainedVerticals< TLayout >::collect(), ug::ComPol_NewConstrainedVerticals< TLayout >::exchange_data(), and ug::ComPol_NewConstrainedVerticals< TLayout >::extract().
m_hash
template<class TLayout > Hash<GeomObj*, Entry> ug::ComPol_NewConstrainedVerticals< TLayout >::m_hash private
Referenced by ug::ComPol_NewConstrainedVerticals< TLayout >::collect(), ug::ComPol_NewConstrainedVerticals< TLayout >::ComPol_NewConstrainedVerticals(), ug::ComPol_NewConstrainedVerticals< TLayout >::create_initial_hash_entry(), ug::ComPol_NewConstrainedVerticals< TLayout >::exchange_data(), ug::ComPol_NewConstrainedVerticals< TLayout >::extract(), ug::ComPol_NewConstrainedVerticals< TLayout >::get_h_master_info(), and ug::ComPol_NewConstrainedVerticals< TLayout >::other_v_masters().
m_initialHandshake
template<class TLayout > bool ug::ComPol_NewConstrainedVerticals< TLayout >::m_initialHandshake private
Referenced by ug::ComPol_NewConstrainedVerticals< TLayout >::collect(), ug::ComPol_NewConstrainedVerticals< TLayout >::exchange_data(), and ug::ComPol_NewConstrainedVerticals< TLayout >::extract().
m_localHMasterCount
template<class TLayout > int ug::ComPol_NewConstrainedVerticals< TLayout >::m_localHMasterCount private
Referenced by ug::ComPol_NewConstrainedVerticals< TLayout >::create_initial_hash_entry(), and ug::ComPol_NewConstrainedVerticals< TLayout >::exchange_data().
m_newConstrained
template<class TLayout > std::vector<GeomObj*>& ug::ComPol_NewConstrainedVerticals< TLayout >::m_newConstrained private
Referenced by ug::ComPol_NewConstrainedVerticals< TLayout >::exchange_data(), and ug::ComPol_NewConstrainedVerticals< TLayout >::extract().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/distributed_grid.cpp