ug4: ug::LocalDoFSubspace< TDomain, TAlgebra, TObject > Class Template Reference
ug::LocalDoFSubspace< TDomain, TAlgebra, TObject > Class Template Reference abstract
Abstract definition for subspace V_k (based on DoFIndex)
#include <sequential_subspace_correction.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef std::vector< DoFIndex > index_vector
Local data.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef DenseMatrix< VariableArray2< number > > matrix_type_local
typedef TAlgebra::vector_type vector_type
Vector type.
typedef DenseVector< VariableArray1< number > > vector_type_local
Public Types inherited from ug::ILocalSubspace< TDomain, TAlgebra, TObject >
typedef TAlgebra algebra_type
Algebra type.
typedef GridFunction< TDomain, TAlgebra > grid_function_type
Grid function type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef DenseMatrix< VariableArray2< number > > matrix_type_local
typedef TAlgebra::vector_type vector_type
Vector type.
typedef DenseVector< VariableArray1< number > > vector_type_local
Public Member Functions
bool check (void *obj) const
virtual void extract_matrix (const matrix_type &A)
Extract matrix (on local index set)
virtual void extract_rhs (const vector_type &d)
Extract rhs (on local index set) for parallel subspace correction.
virtual void extract_rhs (const vector_type &d, const matrix_type &A, const vector_type &c)
Extract rhs (on local index set) for sequential subspace correction.
virtual void init (TObject *, const vector_type &)=0
Extract local data (based on group obj)
virtual size_t size ()
virtual void update_solution (vector_type &u, double omega=1.0)
u = u + ck
virtual ~LocalDoFSubspace ()
virtual DTOR
Public Member Functions inherited from ug::ILocalSubspace< TDomain, TAlgebra, TObject >
virtual bool preprocess (const vector_type &c)
Called once.
virtual ~ILocalSubspace ()
virtual DTOR
Protected Attributes
matrix_type_local m_Aloc
vector_type_local m_dloc
vector_type_local m_uloc
std::vector< DoFIndex > m_vInd
Algebraic indices.
Detailed Description
template<typename TDomain, typename TAlgebra, typename TObject>
class ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >
Abstract definition for subspace V_k (based on DoFIndex)
Member Typedef Documentation
algebra_type
template<typename TDomain , typename TAlgebra , typename TObject > typedef TAlgebra ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::algebra_type
Algebra type.
index_vector
template<typename TDomain , typename TAlgebra , typename TObject > typedef std::vector<DoFIndex> ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::index_vector
Local data.
matrix_type
template<typename TDomain , typename TAlgebra , typename TObject > typedef TAlgebra::matrix_type ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::matrix_type
Matrix type.
matrix_type_local
template<typename TDomain , typename TAlgebra , typename TObject > typedef DenseMatrix< VariableArray2<number> > ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::matrix_type_local
vector_type
template<typename TDomain , typename TAlgebra , typename TObject > typedef TAlgebra::vector_type ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::vector_type
Vector type.
vector_type_local
template<typename TDomain , typename TAlgebra , typename TObject > typedef DenseVector< VariableArray1<number> > ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::vector_type_local
Constructor & Destructor Documentation
~LocalDoFSubspace()
template<typename TDomain , typename TAlgebra , typename TObject > virtual ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::~LocalDoFSubspace () inline virtual
virtual DTOR
Member Function Documentation
check()
template<typename TDomain , typename TAlgebra , typename TObject > bool ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::check (void * obj) const inline
extract_matrix()
template<typename TDomain , typename TAlgebra , typename TObject > virtual void ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::extract_matrix (const matrix_type & A) inline virtual
Extract matrix (on local index set)
Implements ug::ILocalSubspace< TDomain, TAlgebra, TObject >.
References ug::DoFRef(), ug::DenseMatrix< TStorage >::entry(), ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_Aloc, ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_vInd, ug::VariableArray2< T, T_ordering >::resize(), and ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::size().
extract_rhs() [1/2]
template<typename TDomain , typename TAlgebra , typename TObject > virtual void ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::extract_rhs (const vector_type & d) inline virtual
Extract rhs (on local index set) for parallel subspace correction.
Implements ug::ILocalSubspace< TDomain, TAlgebra, TObject >.
References ug::DoFRef(), ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_dloc, ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_vInd, ug::VariableArray1< T >::resize(), and ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::size().
extract_rhs() [2/2]
template<typename TDomain , typename TAlgebra , typename TObject > virtual void ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::extract_rhs (const vector_type & d, const matrix_type & A, const vector_type & c) inline virtual
Extract rhs (on local index set) for sequential subspace correction.
Implements ug::ILocalSubspace< TDomain, TAlgebra, TObject >.
References ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_dloc, ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_vInd, ug::MatMultAdd(), ug::VariableArray1< T >::resize(), ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::size(), and ug::DenseVector< TStorage >::subassign().
init()
template<typename TDomain , typename TAlgebra , typename TObject > virtual void ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::init (TObject * , const vector_type &) pure virtual
Extract local data (based on group obj)
Implements ug::ILocalSubspace< TDomain, TAlgebra, TObject >.
Implemented in ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >.
size()
template<typename TDomain , typename TAlgebra , typename TObject > virtual size_t ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::size () inline virtual
Reimplemented from ug::ILocalSubspace< TDomain, TAlgebra, TObject >.
References ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_vInd.
Referenced by ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::extract_matrix(), ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::extract_rhs(), and ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::update_solution().
update_solution()
template<typename TDomain , typename TAlgebra , typename TObject > virtual void ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::update_solution (vector_type & u, double omega = 1.0) inline virtual
u = u + ck
Implements ug::ILocalSubspace< TDomain, TAlgebra, TObject >.
References ug::DoFRef(), ug::InverseMatMult(), ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_Aloc, ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_dloc, ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_uloc, ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_vInd, omega, ug::VariableArray1< T >::resize(), and ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::size().
Member Data Documentation
m_Aloc
template<typename TDomain , typename TAlgebra , typename TObject > matrix_type_local ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_Aloc protected
Referenced by ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::extract_matrix(), and ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::update_solution().
m_dloc
template<typename TDomain , typename TAlgebra , typename TObject > vector_type_local ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_dloc protected
Referenced by ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::extract_rhs(), and ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::update_solution().
m_uloc
template<typename TDomain , typename TAlgebra , typename TObject > vector_type_local ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_uloc protected
Referenced by ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::update_solution().
m_vInd
template<typename TDomain , typename TAlgebra , typename TObject > std::vector<DoFIndex> ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::m_vInd protected
Algebraic indices.
Referenced by ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::extract_matrix(), ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::extract_rhs(), ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::size(), and ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::update_solution().
The documentation for this class was generated from the following file:
ugbase/lib_disc/operator/linear_operator/subspace_correction/sequential_subspace_correction.h