ug4: ug::BalanceWeightsRefMarks Class Reference
ug::BalanceWeightsRefMarks Class Reference
#include <balance_weights_ref_marks.h>
Public Member Functions
BalanceWeightsRefMarks (IRefiner *refiner)
virtual number get_refined_weight (Edge *e)
virtual number get_refined_weight (Face *e)
todo: use a more sophisticated implementation
virtual number get_refined_weight (Vertex *e)
virtual number get_refined_weight (Volume *e)
todo: use a more sophisticated implementation
virtual bool has_level_offsets ()
virtual bool consider_in_level_above (Vertex *e)
Indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Edge *e)
Indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Face *e)
Indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Volume *e)
Indicator in which level the specifed elements should be partitioned.
Public Member Functions inherited from ug::IBalanceWeights
virtual number get_weight (Edge *)
virtual number get_weight (Face *)
virtual number get_weight (Vertex *)
virtual number get_weight (Volume *)
virtual void refresh_weights (int baseLevel)
virtual ~IBalanceWeights ()
Private Member Functions
template<class TElem >
bool consider_in_level_above_impl (TElem *e)
Private Attributes
IRefiner * m_refiner
Constructor & Destructor Documentation
BalanceWeightsRefMarks()
ug::BalanceWeightsRefMarks::BalanceWeightsRefMarks (IRefiner * refiner) inline
Member Function Documentation
consider_in_level_above() [1/4]
virtual bool ug::BalanceWeightsRefMarks::consider_in_level_above (Edge * e) inline virtual
Indicator in which level the specifed elements should be partitioned.
This will only have effect if the given element does not have any children
Reimplemented from ug::IBalanceWeights.
References consider_in_level_above_impl().
consider_in_level_above() [2/4]
virtual bool ug::BalanceWeightsRefMarks::consider_in_level_above (Face * e) inline virtual
Indicator in which level the specifed elements should be partitioned.
This will only have effect if the given element does not have any children
Reimplemented from ug::IBalanceWeights.
References consider_in_level_above_impl().
consider_in_level_above() [3/4]
virtual bool ug::BalanceWeightsRefMarks::consider_in_level_above (Vertex * e) inline virtual
Indicator in which level the specifed elements should be partitioned.
This will only have effect if the given element does not have any children
Reimplemented from ug::IBalanceWeights.
References consider_in_level_above_impl().
consider_in_level_above() [4/4]
virtual bool ug::BalanceWeightsRefMarks::consider_in_level_above (Volume * e) inline virtual
Indicator in which level the specifed elements should be partitioned.
This will only have effect if the given element does not have any children
Reimplemented from ug::IBalanceWeights.
References consider_in_level_above_impl().
consider_in_level_above_impl()
template<class TElem > bool ug::BalanceWeightsRefMarks::consider_in_level_above_impl (TElem * e) inline private
References ug::IRefiner::get_mark(), m_refiner, ug::RM_ANISOTROPIC, and ug::RM_REFINE.
Referenced by consider_in_level_above().
get_refined_weight() [1/4]
virtual number ug::BalanceWeightsRefMarks::get_refined_weight (Edge * e) inline virtual
Reimplemented from ug::IBalanceWeights.
References ug::IRefiner::get_mark(), ug::IBalanceWeights::get_weight(), m_refiner, ug::RM_ANISOTROPIC, and ug::RM_REFINE.
get_refined_weight() [2/4]
virtual number ug::BalanceWeightsRefMarks::get_refined_weight (Face * e) inline virtual
todo: use a more sophisticated implementation
Reimplemented from ug::IBalanceWeights.
References ug::IRefiner::get_mark(), ug::IBalanceWeights::get_weight(), m_refiner, ug::RM_ANISOTROPIC, and ug::RM_REFINE.
get_refined_weight() [3/4]
virtual number ug::BalanceWeightsRefMarks::get_refined_weight (Vertex * e) inline virtual
Reimplemented from ug::IBalanceWeights.
References ug::IRefiner::get_mark(), ug::IBalanceWeights::get_weight(), m_refiner, ug::RM_ANISOTROPIC, and ug::RM_REFINE.
get_refined_weight() [4/4]
virtual number ug::BalanceWeightsRefMarks::get_refined_weight (Volume * e) inline virtual
todo: use a more sophisticated implementation
Reimplemented from ug::IBalanceWeights.
References ug::IRefiner::get_mark(), ug::IBalanceWeights::get_weight(), m_refiner, ug::RM_ANISOTROPIC, and ug::RM_REFINE.
has_level_offsets()
virtual bool ug::BalanceWeightsRefMarks::has_level_offsets () inline virtual
Reimplemented from ug::IBalanceWeights.
Member Data Documentation
m_refiner
IRefiner* ug::BalanceWeightsRefMarks::m_refiner private
Referenced by consider_in_level_above_impl(), and get_refined_weight().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/balance_weights_ref_marks.h