ug4: ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF Class Reference
ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF Class Reference
#include <hfv1_geom.h>
Public Member Functions
number detJ () const
Determinante of Jacobian in integration point.
size_t from () const
index of SubControlVolume on one side of the scvf
const MathVector< worldDim > & global_corner (size_t co) const
return glbal corner number i
const MathVector< worldDim > & global_grad (size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector () const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip () const
global integration point of scvf
const MathMatrix< worldDim, dim > & JTInv () const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector () const
vector of local gradients in ip point
const MathVector< dim > & local_ip () const
local integration point of scvf
const MathVector< worldDim > & normal () const
normal on scvf (points direction "from"->"to"). Norm is equal to area
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points on scvf
size_t num_sh () const
number of shape functions
SCVF ()
number shape (size_t sh) const
value of shape function i in integration point
size_t to () const
index of SubControlVolume on one side of the scvf
Static Public Attributes
static const int dim = TDim
dimension of reference element
static const int worldDim = TWorldDim
dimension of world
Private Attributes
number detj
std::vector< MathVector< worldDim > > globalGrad
MathVector< worldDim > globalIP
MathMatrix< worldDim, dim > JtInv
std::vector< MathVector< dim > > localGrad
MathVector< dim > localIP
size_t m_from
MidID m_midId [m_numCorners]
size_t m_to
MathVector< worldDim > m_vGloPos [m_numCorners]
MathVector< dim > m_vLocPos [m_numCorners]
MathVector< worldDim > Normal
std::vector< number > vShape
Static Private Attributes
static const size_t m_numCorners = traits::NumCornersOfSCVF
Number of corners of scvf.
static const size_t m_numIP = 1
number of integration points
Friends
class DimHFV1Geometry< TDim, TWorldDim >
let outer class access private members
Constructor & Destructor Documentation
SCVF()
template<int TDim, int TWorldDim = TDim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::SCVF () inline
Member Function Documentation
detJ()
template<int TDim, int TWorldDim = TDim> number ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::detJ () const inline
Determinante of Jacobian in integration point.
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::detj.
from()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::from () const inline
index of SubControlVolume on one side of the scvf
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_from.
global_corner()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_corner (size_t co) const inline
return glbal corner number i
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_vGloPos, ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_corners(), and UG_ASSERT.
global_grad()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_grad (size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::globalGrad, ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_sh(), and UG_ASSERT.
global_grad_vector()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_grad_vector () const inline
vector of global gradients in ip point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::globalGrad.
global_ip()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_ip () const inline
global integration point of scvf
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::globalIP.
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::update().
JTInv()
template<int TDim, int TWorldDim = TDim> const MathMatrix<worldDim,dim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::JTInv () const inline
Transposed Inverse of Jacobian in integration point.
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::JtInv.
local_corner()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_corner (size_t co) const inline
return local corner number i
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_vLocPos, ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_corners(), and UG_ASSERT.
local_grad()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_grad (size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::localGrad, ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_sh(), and UG_ASSERT.
local_grad_vector()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>* ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_grad_vector () const inline
vector of local gradients in ip point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::localGrad.
local_ip()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_ip () const inline
local integration point of scvf
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::localIP.
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::update().
normal()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::normal () const inline
normal on scvf (points direction "from"->"to"). Norm is equal to area
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::Normal.
num_corners()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_corners () const inline
number of corners, that bound the scvf
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_numCorners.
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::copy_global_corners(), ug::DimHFV1Geometry< TDim, TWorldDim >::copy_local_corners(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_corner(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_corner().
num_ip()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_ip () const inline
number of integration points on scvf
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_numIP.
num_sh()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_sh () const inline
number of shape functions
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::vShape.
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_grad(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_grad(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::shape().
shape()
template<int TDim, int TWorldDim = TDim> number ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::shape (size_t sh) const inline
value of shape function i in integration point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_sh(), UG_ASSERT, and ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::vShape.
to()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::to () const inline
index of SubControlVolume on one side of the scvf
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_to.
Friends And Related Function Documentation
DimHFV1Geometry< TDim, TWorldDim >
template<int TDim, int TWorldDim = TDim> friend class DimHFV1Geometry< TDim, TWorldDim > friend
let outer class access private members
Member Data Documentation
detj
template<int TDim, int TWorldDim = TDim> number ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::detj private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::detJ().
dim
template<int TDim, int TWorldDim = TDim> const int ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::dim = TDim static
dimension of reference element
globalGrad
template<int TDim, int TWorldDim = TDim> std::vector<MathVector<worldDim> > ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::globalGrad private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_grad(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_grad_vector().
globalIP
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::globalIP private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_ip().
JtInv
template<int TDim, int TWorldDim = TDim> MathMatrix<worldDim,dim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::JtInv private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::JTInv().
localGrad
template<int TDim, int TWorldDim = TDim> std::vector<MathVector<dim> > ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::localGrad private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_grad(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_grad_vector().
localIP
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::localIP private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_ip().
m_from
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_from private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::from().
m_midId
template<int TDim, int TWorldDim = TDim> MidID ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_midId[m_numCorners] private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::copy_global_corners(), and ug::DimHFV1Geometry< TDim, TWorldDim >::copy_local_corners().
m_numCorners
template<int TDim, int TWorldDim = TDim> const size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_numCorners = traits::NumCornersOfSCVF static private
Number of corners of scvf.
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_corners().
m_numIP
template<int TDim, int TWorldDim = TDim> const size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_numIP = 1 static private
number of integration points
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_ip().
m_to
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_to private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::to().
m_vGloPos
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_vGloPos[m_numCorners] private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::copy_global_corners(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_corner().
m_vLocPos
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_vLocPos[m_numCorners] private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::copy_local_corners(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_corner().
Normal
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::Normal private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::normal().
vShape
template<int TDim, int TWorldDim = TDim> std::vector<number> ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::vShape private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_sh(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::shape().
worldDim
template<int TDim, int TWorldDim = TDim> const int ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::worldDim = TWorldDim static
dimension of world
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/hfv1_geom.h