ug4: pcl::MultiLevelLayout< TInterface > Class Template Reference
pcl::MultiLevelLayout< TInterface > Class Template Reference
ugbase » PCL
the standard multi-level-layout implementation
#include <pcl_communication_structs.h>
Public Types
typedef layout_tags::multi_level_layout_tag category_tag
Layout category.
typedef LevelLayout::const_iterator const_iterator
typedef Interface::Element Element
Element type.
typedef TInterface Interface
Interface type.
typedef LevelLayout::iterator iterator
An iterator that allows to iterate over the interfaces stored in the layout.
typedef SingleLevelLayout< TInterface > LevelLayout
on each level a single-level-layout is used
typedef Interface::Type Type
Type.
Public Member Functions
iterator begin (size_t level)
returns the iterator to the first interface of the layout in the given level.
const_iterator begin (size_t level) const
void clear ()
deletes all levels.
bool empty () const
returns true if the layout has no interfaces.
bool empty (size_t level)
returns true if the layout has no interfaces on the given level.
bool empty (size_t level) const
iterator end (size_t level)
returns the iterator to the last interface of the layout in the given level.
const_iterator end (size_t level) const
iterator erase (iterator iter, size_t level)
erases the interface at the given iterator on the given level.
bool has_interface_elements () const
returns true if the layout contains any interface entries
const Interface & interface (const_iterator iter) const
Interface & interface (int procID, size_t level)
returns the interface to the given process.
const Interface & interface (int procID, size_t level) const
Interface & interface (iterator iter)
returns the interface to the given iterator.
bool interface_exists (int procID)
returns true if an interface to the given procID already exists.
bool interface_exists (int procID) const
bool interface_exists (int procID, size_t level)
returns true if an interface to the given procID on the given level already exists.
bool interface_exists (int procID, size_t level) const
LevelLayout & layout_on_level (int level)
returns the layout at the given level.
const LevelLayout & layout_on_level (int level) const
MultiLevelLayout ()
MultiLevelLayout (const MultiLevelLayout &mll)
size_t num_interface_elements () const
returns the sum of the interface sizes
size_t num_interfaces (size_t level) const
returns the number of interfaces in the layout
size_t num_levels () const
returns the number of levels.
MultiLevelLayout & operator= (const MultiLevelLayout &mll)
int proc_id (const_iterator iter) const
returns the interface to the given iterator.
template<class TCompare >
void sort_interface_entries (TCompare cmp)
sort the entries in all interfaces of this layout
~MultiLevelLayout ()
Protected Member Functions
void assign_layout (const MultiLevelLayout &mll)
clears this layout and then copies all levels from the given layout
void new_levels (size_t num)
adds num new levels.
void require_level (size_t level)
if the required level doesn't exist yet, it will created.
void require_level (size_t level) const
Protected Attributes
std::vector< LevelLayout * > m_vLayouts
Detailed Description
template<class TInterface>
class pcl::MultiLevelLayout< TInterface >
the standard multi-level-layout implementation
A MultiLevelLayout is a collection of interfaces, which are grouped in different levels.
Each interface is associated with a process-id. If the localSrcID of this layout == -1 then, when a new level is created, it's local srcID is automatically initialized with the level index. localSrcIDs of interfaces created on those levels are then initialised with the level index, too.
If the localSrcID >= 0 it is simply passed on to the level-layouts.
This layout type supports the requirements of the pcl::layout_tags::multi_level_layout_tag category.
Additionally it features methods that allow to add new interfaces.
Member Typedef Documentation
category_tag
template<class TInterface > typedef layout_tags::multi_level_layout_tag pcl::MultiLevelLayout< TInterface >::category_tag
Layout category.
const_iterator
template<class TInterface > typedef LevelLayout::const_iterator pcl::MultiLevelLayout< TInterface >::const_iterator
Element
template<class TInterface > typedef Interface::Element pcl::MultiLevelLayout< TInterface >::Element
Element type.
Interface
template<class TInterface > typedef TInterface pcl::MultiLevelLayout< TInterface >::Interface
Interface type.
iterator
template<class TInterface > typedef LevelLayout::iterator pcl::MultiLevelLayout< TInterface >::iterator
An iterator that allows to iterate over the interfaces stored in the layout.
LevelLayout
template<class TInterface > typedef SingleLevelLayout<TInterface> pcl::MultiLevelLayout< TInterface >::LevelLayout
on each level a single-level-layout is used
Type
template<class TInterface > typedef Interface::Type pcl::MultiLevelLayout< TInterface >::Type
Type.
Constructor & Destructor Documentation
MultiLevelLayout() [1/2]
template<class TInterface > pcl::MultiLevelLayout< TInterface >::MultiLevelLayout () inline
MultiLevelLayout() [2/2]
template<class TInterface > pcl::MultiLevelLayout< TInterface >::MultiLevelLayout (const MultiLevelLayout< TInterface > & mll) inline
References pcl::MultiLevelLayout< TInterface >::assign_layout().
~MultiLevelLayout()
template<class TInterface > pcl::MultiLevelLayout< TInterface >::~MultiLevelLayout () inline
References pcl::MultiLevelLayout< TInterface >::clear().
Member Function Documentation
assign_layout()
template<class TInterface > void pcl::MultiLevelLayout< TInterface >::assign_layout (const MultiLevelLayout< TInterface > & mll) inline protected
clears this layout and then copies all levels from the given layout
References pcl::MultiLevelLayout< TInterface >::clear(), and pcl::MultiLevelLayout< TInterface >::m_vLayouts.
Referenced by pcl::MultiLevelLayout< TInterface >::MultiLevelLayout(), and pcl::MultiLevelLayout< TInterface >::operator=().
begin() [1/2]
template<class TInterface > iterator pcl::MultiLevelLayout< TInterface >::begin (size_t level) inline
returns the iterator to the first interface of the layout in the given level.
You should access the values of this iterator using the methods Layout::interface and Layout::proc_id. Make sure that the level matches the level in the associated end() call.
References pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::require_level().
Referenced by pcl::MultiLevelLayout< TInterface >::empty(), pcl::MultiLevelLayout< TInterface >::has_interface_elements(), pcl::MultiLevelLayout< TInterface >::num_interface_elements(), and pcl::InterfaceCommunicator< pcl::MultiLevelLayout >::receive_raw().
begin() [2/2]
template<class TInterface > const_iterator pcl::MultiLevelLayout< TInterface >::begin (size_t level) const inline
References pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::require_level().
clear()
template<class TInterface > void pcl::MultiLevelLayout< TInterface >::clear () inline
deletes all levels.
References pcl::MultiLevelLayout< TInterface >::m_vLayouts.
Referenced by pcl::MultiLevelLayout< TInterface >::assign_layout(), and pcl::MultiLevelLayout< TInterface >::~MultiLevelLayout().
empty() [1/3]
template<class TInterface > bool pcl::MultiLevelLayout< TInterface >::empty () const inline
returns true if the layout has no interfaces.
Note that this method only tells whether there are interfaces or not. To check whether there are any elements use has_interface_elements.
References pcl::MultiLevelLayout< TInterface >::empty(), and pcl::MultiLevelLayout< TInterface >::num_levels().
Referenced by pcl::MultiLevelLayout< TInterface >::empty().
empty() [2/3]
template<class TInterface > bool pcl::MultiLevelLayout< TInterface >::empty (size_t level) inline
returns true if the layout has no interfaces on the given level.
Note that this method only tells whether there are interfaces or not. To check whether there are any elements use has_interface_elements.
References pcl::MultiLevelLayout< TInterface >::begin(), and pcl::MultiLevelLayout< TInterface >::end().
empty() [3/3]
template<class TInterface > bool pcl::MultiLevelLayout< TInterface >::empty (size_t level) const inline
References pcl::MultiLevelLayout< TInterface >::begin(), and pcl::MultiLevelLayout< TInterface >::end().
end() [1/2]
template<class TInterface > iterator pcl::MultiLevelLayout< TInterface >::end (size_t level) inline
returns the iterator to the last interface of the layout in the given level.
You should access the values of this iterator using the methods Layout::interface and Layout::proc_id. Make sure that the level matches the level in the associated begin() call.
References pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::require_level().
Referenced by pcl::MultiLevelLayout< TInterface >::empty(), pcl::MultiLevelLayout< TInterface >::has_interface_elements(), pcl::MultiLevelLayout< TInterface >::num_interface_elements(), and pcl::InterfaceCommunicator< pcl::MultiLevelLayout >::receive_raw().
end() [2/2]
template<class TInterface > const_iterator pcl::MultiLevelLayout< TInterface >::end (size_t level) const inline
References pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::require_level().
erase()
template<class TInterface > iterator pcl::MultiLevelLayout< TInterface >::erase (iterator iter, size_t level) inline
erases the interface at the given iterator on the given level.
returns an iterator to the next interface.
References pcl::MultiLevelLayout< TInterface >::m_vLayouts.
has_interface_elements()
template<class TInterface > bool pcl::MultiLevelLayout< TInterface >::has_interface_elements () const inline
returns true if the layout contains any interface entries
References pcl::MultiLevelLayout< TInterface >::begin(), pcl::MultiLevelLayout< TInterface >::end(), pcl::MultiLevelLayout< TInterface >::interface(), and pcl::MultiLevelLayout< TInterface >::num_levels().
interface() [1/4]
template<class TInterface > const Interface& pcl::MultiLevelLayout< TInterface >::interface (const_iterator iter) const inline
interface() [2/4]
template<class TInterface > Interface& pcl::MultiLevelLayout< TInterface >::interface (int procID, size_t level) inline
returns the interface to the given process.
if the interface doesn't exist yet, it will be created.
References pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::require_level().
interface() [3/4]
template<class TInterface > const Interface& pcl::MultiLevelLayout< TInterface >::interface (int procID, size_t level) const inline
References pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::require_level().
interface() [4/4]
template<class TInterface > Interface& pcl::MultiLevelLayout< TInterface >::interface (iterator iter) inline
returns the interface to the given iterator.
Referenced by pcl::MultiLevelLayout< TInterface >::has_interface_elements(), pcl::MultiLevelLayout< TInterface >::num_interface_elements(), and pcl::InterfaceCommunicator< pcl::MultiLevelLayout >::receive_raw().
interface_exists() [1/4]
template<class TInterface > bool pcl::MultiLevelLayout< TInterface >::interface_exists (int procID) inline
returns true if an interface to the given procID already exists.
References pcl::MultiLevelLayout< TInterface >::interface_exists(), pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::num_levels().
Referenced by pcl::MultiLevelLayout< TInterface >::interface_exists().
interface_exists() [2/4]
template<class TInterface > bool pcl::MultiLevelLayout< TInterface >::interface_exists (int procID) const inline
References pcl::MultiLevelLayout< TInterface >::interface_exists(), pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::num_levels().
Referenced by pcl::MultiLevelLayout< TInterface >::interface_exists().
interface_exists() [3/4]
template<class TInterface > bool pcl::MultiLevelLayout< TInterface >::interface_exists (int procID, size_t level) inline
returns true if an interface to the given procID on the given level already exists.
References pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::require_level().
interface_exists() [4/4]
template<class TInterface > bool pcl::MultiLevelLayout< TInterface >::interface_exists (int procID, size_t level) const inline
References pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::require_level().
layout_on_level() [1/2]
template<class TInterface > LevelLayout& pcl::MultiLevelLayout< TInterface >::layout_on_level (int level) inline
returns the layout at the given level.
If level >= num_levels() then the layouts in between will be automatically created.
References pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::require_level().
Referenced by pcl::MultiLevelLayout< TInterface >::sort_interface_entries(), and ug::TestGridLayoutMap().
layout_on_level() [2/2]
template<class TInterface > const LevelLayout& pcl::MultiLevelLayout< TInterface >::layout_on_level (int level) const inline
References pcl::MultiLevelLayout< TInterface >::m_vLayouts, and pcl::MultiLevelLayout< TInterface >::require_level().
new_levels()
template<class TInterface > void pcl::MultiLevelLayout< TInterface >::new_levels (size_t num) inline protected
adds num new levels.
References pcl::MultiLevelLayout< TInterface >::m_vLayouts.
Referenced by pcl::MultiLevelLayout< TInterface >::require_level().
num_interface_elements()
template<class TInterface > size_t pcl::MultiLevelLayout< TInterface >::num_interface_elements () const inline
returns the sum of the interface sizes
References pcl::MultiLevelLayout< TInterface >::begin(), pcl::MultiLevelLayout< TInterface >::end(), pcl::MultiLevelLayout< TInterface >::interface(), and pcl::MultiLevelLayout< TInterface >::num_levels().
num_interfaces()
template<class TInterface > size_t pcl::MultiLevelLayout< TInterface >::num_interfaces (size_t level) const inline
returns the number of interfaces in the layout
References pcl::MultiLevelLayout< TInterface >::m_vLayouts.
num_levels()
template<class TInterface > size_t pcl::MultiLevelLayout< TInterface >::num_levels () const inline
returns the number of levels.
References pcl::MultiLevelLayout< TInterface >::m_vLayouts.
Referenced by pcl::MultiLevelLayout< TInterface >::empty(), pcl::MultiLevelLayout< TInterface >::has_interface_elements(), pcl::MultiLevelLayout< TInterface >::interface_exists(), pcl::MultiLevelLayout< TInterface >::num_interface_elements(), pcl::InterfaceCommunicator< pcl::MultiLevelLayout >::receive_raw(), pcl::MultiLevelLayout< TInterface >::require_level(), pcl::MultiLevelLayout< TInterface >::sort_interface_entries(), and ug::TestGridLayoutMap().
operator=()
template<class TInterface > MultiLevelLayout& pcl::MultiLevelLayout< TInterface >::operator= (const MultiLevelLayout< TInterface > & mll) inline
References pcl::MultiLevelLayout< TInterface >::assign_layout().
proc_id()
template<class TInterface > int pcl::MultiLevelLayout< TInterface >::proc_id (const_iterator iter) const inline
returns the interface to the given iterator.
Referenced by pcl::InterfaceCommunicator< pcl::MultiLevelLayout >::receive_raw().
require_level() [1/2]
template<class TInterface > void pcl::MultiLevelLayout< TInterface >::require_level (size_t level) inline protected
if the required level doesn't exist yet, it will created.
References pcl::MultiLevelLayout< TInterface >::new_levels(), and pcl::MultiLevelLayout< TInterface >::num_levels().
Referenced by pcl::MultiLevelLayout< TInterface >::begin(), pcl::MultiLevelLayout< TInterface >::end(), pcl::MultiLevelLayout< TInterface >::interface(), pcl::MultiLevelLayout< TInterface >::interface_exists(), and pcl::MultiLevelLayout< TInterface >::layout_on_level().
require_level() [2/2]
template<class TInterface > void pcl::MultiLevelLayout< TInterface >::require_level (size_t level) const inline protected
References pcl::MultiLevelLayout< TInterface >::num_levels(), and UG_THROW.
sort_interface_entries()
template<class TInterface > template<class TCompare > void pcl::MultiLevelLayout< TInterface >::sort_interface_entries (TCompare cmp) inline
sort the entries in all interfaces of this layout
References pcl::MultiLevelLayout< TInterface >::layout_on_level(), pcl::MultiLevelLayout< TInterface >::num_levels(), and pcl::SingleLevelLayout< TInterface >::sort_interface_entries().
Member Data Documentation
m_vLayouts
template<class TInterface > std::vector<LevelLayout*> pcl::MultiLevelLayout< TInterface >::m_vLayouts protected
Referenced by pcl::MultiLevelLayout< TInterface >::assign_layout(), pcl::MultiLevelLayout< TInterface >::begin(), pcl::MultiLevelLayout< TInterface >::clear(), pcl::MultiLevelLayout< TInterface >::end(), pcl::MultiLevelLayout< TInterface >::erase(), pcl::MultiLevelLayout< TInterface >::interface(), pcl::MultiLevelLayout< TInterface >::interface_exists(), pcl::MultiLevelLayout< TInterface >::layout_on_level(), pcl::MultiLevelLayout< TInterface >::new_levels(), pcl::MultiLevelLayout< TInterface >::num_interfaces(), and pcl::MultiLevelLayout< TInterface >::num_levels().
The documentation for this class was generated from the following file:
ugbase/pcl/pcl_communication_structs.h