ug4: ug::H1EnergyDistIntegrand< TGridFunction > Class Template Reference
ug::H1EnergyDistIntegrand< TGridFunction > Class Template Reference
Integrand for the distance of two grid functions - evaluated in the norm \(|D \nabla u|^2 \).
#include <integrate.h>
Public Types
typedef H1SemiIntegrand< TGridFunction >::weight_type weight_type
Public Types inherited from ug::StdIntegrand< number, TGridFunction::dim, H1EnergyDistIntegrand< TGridFunction > >
typedef number data_type
data type
Public Types inherited from ug::IIntegrand< TData, TWorldDim >
typedef TData data_type
data type
Public Member Functions
template<int elemDim>
void evaluate (number vValue[], const MathVector< worldDim > vFineGlobIP[], GridObject *pFineElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vFineLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP)
returns the values of the integrand for a bunch of ips
H1EnergyDistIntegrand (TGridFunction &fineGridFct, size_t fineCmp, TGridFunction &coarseGridFct, size_t coarseCmp)
constructor
H1EnergyDistIntegrand (TGridFunction &fineGridFct, size_t fineCmp, TGridFunction &coarseGridFct, size_t coarseCmp, ConstSmartPtr< weight_type > spWeight)
constructor
virtual void set_subset (int si)
sets subset
virtual ~H1EnergyDistIntegrand ()
Public Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, H1EnergyDistIntegrand< TGridFunction > >
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)
Public Member Functions inherited from ug::IIntegrand< TData, TWorldDim >
int subset () const
returns the subset
virtual ~IIntegrand ()
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
Static Public Attributes
static const int worldDim = TGridFunction::dim
world dimension of grid function
Static Public Attributes inherited from ug::StdIntegrand< number, TGridFunction::dim, H1EnergyDistIntegrand< TGridFunction > >
static const int worldDim
world dimension
Static Public Attributes inherited from ug::IIntegrand< TData, TWorldDim >
static const int worldDim = TWorldDim
world dimension
Private Attributes
ScalarGridFunctionData< TGridFunction > m_coarseData
const int m_coarseTopLevel
ScalarGridFunctionData< TGridFunction > m_fineData
const int m_fineTopLevel
SmartPtr< MultiGrid > m_spMG
multigrid
ConstSmartPtr< weight_type > m_spWeight
scalar weight (optional)
Additional Inherited Members
Protected Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, H1EnergyDistIntegrand< TGridFunction > >
H1EnergyDistIntegrand< TGridFunction > & getImpl ()
access to implementation
const H1EnergyDistIntegrand< TGridFunction > & getImpl () const
const access to implementation
Protected Attributes inherited from ug::IIntegrand< TData, TWorldDim >
int m_si
subset
Detailed Description
template<typename TGridFunction>
class ug::H1EnergyDistIntegrand< TGridFunction >
Integrand for the distance of two grid functions - evaluated in the norm \(|D \nabla u|^2 \).
Member Typedef Documentation
weight_type
template<typename TGridFunction > typedef H1SemiIntegrand<TGridFunction>::weight_type ug::H1EnergyDistIntegrand< TGridFunction >::weight_type
Constructor & Destructor Documentation
H1EnergyDistIntegrand() [1/2]
template<typename TGridFunction > ug::H1EnergyDistIntegrand< TGridFunction >::H1EnergyDistIntegrand (TGridFunction & fineGridFct, size_t fineCmp, TGridFunction & coarseGridFct, size_t coarseCmp) inline
constructor
References ug::H1EnergyDistIntegrand< TGridFunction >::m_coarseData, ug::H1EnergyDistIntegrand< TGridFunction >::m_coarseTopLevel, ug::H1EnergyDistIntegrand< TGridFunction >::m_fineData, ug::H1EnergyDistIntegrand< TGridFunction >::m_fineTopLevel, and UG_THROW.
H1EnergyDistIntegrand() [2/2]
template<typename TGridFunction > ug::H1EnergyDistIntegrand< TGridFunction >::H1EnergyDistIntegrand (TGridFunction & fineGridFct, size_t fineCmp, TGridFunction & coarseGridFct, size_t coarseCmp, ConstSmartPtr< weight_type > spWeight) inline
constructor
References ug::H1EnergyDistIntegrand< TGridFunction >::m_coarseData, ug::H1EnergyDistIntegrand< TGridFunction >::m_coarseTopLevel, ug::H1EnergyDistIntegrand< TGridFunction >::m_fineData, ug::H1EnergyDistIntegrand< TGridFunction >::m_fineTopLevel, and UG_THROW.
~H1EnergyDistIntegrand()
template<typename TGridFunction > virtual ug::H1EnergyDistIntegrand< TGridFunction >::~H1EnergyDistIntegrand () inline virtual
Member Function Documentation
evaluate()
template<typename TGridFunction > template<int elemDim> void ug::H1EnergyDistIntegrand< TGridFunction >::evaluate (number vValue[], const MathVector< worldDim > vFineGlobIP[], GridObject * pFineElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vFineLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP) inline
returns the values of the integrand for a bunch of ips
Parameters
vValue[out] the value of the integrand at the ips
vGlobIP[in] global integration point positions
pElem[in] the element to integrate
vCornerCoords[in] corner coordinates of the element
vLocIP[in] local integration point positions
vJT[in] jacobian transposed at integration point
numIP[in] number of integration points
References ug::CollectCornerCoordinates(), ug::DoFRef(), ug::GetLocalVector(), ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::Inverse(), ug::DimReferenceMapping< TDim, TWorldDim >::jacobian_transposed_inverse(), ug::H1EnergyDistIntegrand< TGridFunction >::m_coarseData, ug::H1EnergyDistIntegrand< TGridFunction >::m_coarseTopLevel, ug::H1EnergyDistIntegrand< TGridFunction >::m_fineData, ug::H1EnergyDistIntegrand< TGridFunction >::m_fineTopLevel, ug::H1EnergyDistIntegrand< TGridFunction >::m_spMG, ug::H1EnergyDistIntegrand< TGridFunction >::m_spWeight, ug::MatVecMult(), ug::GridObject::reference_object_id(), ug::UserData< TData, dim, TRet >::requires_grid_fct(), ug::LocalVector::resize(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shape(), ug::IIntegrand< TData, TWorldDim >::subset(), UG_ASSERT, UG_CATCH_THROW, ConstSmartPtr< T, FreePolicy >::valid(), ug::VecDistanceSq(), ug::VecScaleAppend(), and ug::VecSet().
set_subset()
template<typename TGridFunction > virtual void ug::H1EnergyDistIntegrand< TGridFunction >::set_subset (int si) inline virtual
sets subset
Reimplemented from ug::IIntegrand< TData, TWorldDim >.
References ug::H1EnergyDistIntegrand< TGridFunction >::m_coarseData, ug::H1EnergyDistIntegrand< TGridFunction >::m_fineData, ug::IIntegrand< TData, TWorldDim >::set_subset(), and UG_THROW.
Member Data Documentation
m_coarseData
template<typename TGridFunction > ScalarGridFunctionData<TGridFunction> ug::H1EnergyDistIntegrand< TGridFunction >::m_coarseData private
Referenced by ug::H1EnergyDistIntegrand< TGridFunction >::evaluate(), ug::H1EnergyDistIntegrand< TGridFunction >::H1EnergyDistIntegrand(), and ug::H1EnergyDistIntegrand< TGridFunction >::set_subset().
m_coarseTopLevel
template<typename TGridFunction > const int ug::H1EnergyDistIntegrand< TGridFunction >::m_coarseTopLevel private
Referenced by ug::H1EnergyDistIntegrand< TGridFunction >::evaluate(), and ug::H1EnergyDistIntegrand< TGridFunction >::H1EnergyDistIntegrand().
m_fineData
template<typename TGridFunction > ScalarGridFunctionData<TGridFunction> ug::H1EnergyDistIntegrand< TGridFunction >::m_fineData private
Referenced by ug::H1EnergyDistIntegrand< TGridFunction >::evaluate(), ug::H1EnergyDistIntegrand< TGridFunction >::H1EnergyDistIntegrand(), and ug::H1EnergyDistIntegrand< TGridFunction >::set_subset().
m_fineTopLevel
template<typename TGridFunction > const int ug::H1EnergyDistIntegrand< TGridFunction >::m_fineTopLevel private
Referenced by ug::H1EnergyDistIntegrand< TGridFunction >::evaluate(), and ug::H1EnergyDistIntegrand< TGridFunction >::H1EnergyDistIntegrand().
m_spMG
template<typename TGridFunction > SmartPtr<MultiGrid> ug::H1EnergyDistIntegrand< TGridFunction >::m_spMG private
multigrid
Referenced by ug::H1EnergyDistIntegrand< TGridFunction >::evaluate().
m_spWeight
template<typename TGridFunction > ConstSmartPtr<weight_type> ug::H1EnergyDistIntegrand< TGridFunction >::m_spWeight private
scalar weight (optional)
Referenced by ug::H1EnergyDistIntegrand< TGridFunction >::evaluate().
worldDim
template<typename TGridFunction > const int ug::H1EnergyDistIntegrand< TGridFunction >::worldDim = TGridFunction::dim static
world dimension of grid function
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/integrate.h