ug4: ug::NeumannBoundaryFV1< TDomain > Class Template Reference
ug::NeumannBoundaryFV1< TDomain > Class Template Reference
#include <neumann_boundary_fv1.h>
Classes
struct BNDNumberData
Conditional scalar user data.
struct NumberData
Unconditional scalar user data.
struct VectorData
Unconditional vector user data.
Public Member Functions
NeumannBoundaryFV1 (const char *function)
default constructor
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegularGrid)
type of trial space for each function used
void add (SmartPtr< CplUserData< number, dim > > data, const char *BndSubsets, const char *InnerSubsets)
void add (SmartPtr< CplUserData< number, dim, bool > > user, const char *BndSubsets, const char *InnerSubsets)
void add (SmartPtr< CplUserData< MathVector< dim >, dim > > user, const char *BndSubsets, const char *InnerSubsets)
Public Member Functions inherited from ug::NeumannBoundaryBase< TDomain >
NeumannBoundaryBase (const char *function)
default constructor
virtual int type () const
returns the type of elem disc
void add (SmartPtr< CplUserData< number, dim > > data, const std::vector< std::string > &BndSubsets, const std::vector< std::string > &InnerSubsets)
void add (SmartPtr< CplUserData< number, dim, bool > > user, const std::vector< std::string > &BndSubsets, const std::vector< std::string > &InnerSubsets)
void add (SmartPtr< CplUserData< MathVector< dim >, dim > > user, const std::vector< std::string > &BndSubsets, const std::vector< std::string > &InnerSubsets)
void add (number val, const char *BndSubsets, const char *InnerSubsets)
void add (number val, const std::vector< std::string > &BndSubsets, const std::vector< std::string > &InnerSubsets)
void add (const std::vector< number > &val, const char *BndSubsets, const char *InnerSubsets)
void add (const std::vector< number > &val, const std::vector< std::string > &BndSubsets, const std::vector< std::string > &InnerSubsets)
Public Member Functions inherited from ug::IElemDisc< TDomain >
virtual void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
defect for explicit terms
void add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier)
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
returns approximation space
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
returns approximation space
void check_setup (bool bNonRegularGrid)
checks the setup of the elem disc
void clear_imports ()
removes all imports
virtual void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual compute the error estimator (stiffness part) contribution for one element
virtual void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual compute the error estimator (mass part) contribution for one element
SmartPtr< TDomain > domain ()
returns the domain
ConstSmartPtr< TDomain > domain () const
returns the domain
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
returns the pointer to the error estimator data object (or NULL)
bool err_est_enabled () const
find out whether or not a posteriori error estimation is to be performed for this disc
virtual void fsh_timestep (number time, VectorProxyBase *u)
finish the time step
virtual void fsh_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual finish the time step element-wise
const FunctionGroup & function_group () const
returns the current function group
ConstSmartPtr< FunctionPattern > function_pattern () const
returns the current function pattern
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > & get_elem_modifier ()
IDataImport< dim > & get_import (size_t i)
returns an import
IElemDisc (const char *functions="", const char *subsets="")
Constructor.
IElemDisc (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Constructor.
bool is_time_dependent () const
returns if assembling is time-dependent
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
returns the local time solutions
const FunctionIndexMapping & map () const
returns the current function index mapping
size_t num_fct () const
number of functions this discretization handles
size_t num_imports () const
returns number of imports
size_t num_subsets () const
number of subsets this discretization handles
virtual void post_assemble_loop ()
virtual prepares the loop over all elements of one type
virtual void prep_assemble_loop ()
virtual prepares the loop over all elements of one type
virtual void prep_timestep (number time, VectorProxyBase *u)
prepare the time step
virtual void prep_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
prepare the time step element-wise
void register_import (IDataImport< dim > &Imp)
registers a data import
virtual bool requests_local_time_series ()
returns if local time series needed by assembling
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
sets the approximation space
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
sets the pointer to an error estimator data object (or NULL)
void set_functions (const std::string &functions)
sets functions by name list, divided by ','
void set_functions (const std::vector< std::string > &functions)
sets functions by vector of names
void set_roid (ReferenceObjectID id, int discType)
sets the geometric object type
void set_stationary (bool bStationaryForced=true)
sets that the assembling is always stationary (even in instationary case)
void set_stationary ()
void set_subsets (const std::string &subsets)
sets subset(s) by name list, divided by ','
void set_subsets (const std::vector< std::string > &subsets)
sets subset(s) by name list, divided by ','
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
sets if assembling should be time-dependent and the local time series
void set_time_independent ()
sets that the assembling is time independent
void set_time_point (const size_t timePoint)
sets the current time point
TDomain::subset_handler_type & subset_handler ()
returns the subset handler
const TDomain::subset_handler_type & subset_handler () const
returns the subset handler
const std::vector< std::string > & symb_fcts () const
returns the symbolic functions
const std::vector< std::string > & symb_subsets () const
returns the symbolic subsets
number time () const
returns currently set timepoint
size_t time_point () const
returns the currently considered time point of the time-disc scheme
virtual bool use_hanging () const
returns if discretization acts on hanging nodes if present
virtual ~IElemDisc ()
Virtual destructor.
const std::vector< number > & mass_scales () const
const std::vector< number > & stiff_scales () const
number mass_scale (const size_t timePoint) const
number stiff_scale (const size_t timePoint) const
number mass_scale () const
number stiff_scale () const
void do_prep_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_fsh_elem_loop ()
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_err_est_elem_loop ()
Static Public Attributes
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::NeumannBoundaryBase< TDomain >
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::IElemDisc< TDomain >
static const int dim = TDomain::dim
World dimension.
Protected Member Functions
void update_subset_groups ()
template<typename TElem , typename TFVGeom >
void prep_elem_loop (const ReferenceObjectID roid, const int si)
template<typename TElem , typename TFVGeom >
void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFVGeom >
void fsh_elem_loop ()
template<typename TElem , typename TFVGeom >
void add_rhs_elem (LocalVector &d, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFVGeom >
void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
prepares the loop over all elements of one type for the computation of the error estimator
template<typename TElem , typename TFVGeom >
void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
prepares the element for assembling the error estimator
template<typename TElem , typename TFVGeom >
void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
computes the error estimator contribution for one element
template<typename TElem , typename TFVGeom >
void fsh_err_est_elem_loop ()
postprocesses the loop over all elements of one type in the computation of the error estimator
Protected Member Functions inherited from ug::NeumannBoundaryBase< TDomain >
void add_inner_subsets (const char *InnerSubsets)
adds subsets to the looped inner subsets
void update_subset_groups (Data &userData)
method used to extract subsets id
template<typename TElem , typename TFVGeom >
void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFVGeom >
void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFVGeom >
void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFVGeom >
void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
Protected Member Functions inherited from ug::IElemDisc< TDomain >
virtual void approximation_space_changed ()
callback invoked, when approximation space is changed
void clear_add_fct (ReferenceObjectID id)
sets all assemble functions to NULL for a given ReferenceObjectID
void clear_add_fct ()
sets all assemble functions to NULL (for all ReferenceObjectID's)
void remove_add_def_A_elem_fct (ReferenceObjectID id)
void remove_add_def_A_expl_elem_fct (ReferenceObjectID id)
void remove_add_def_M_elem_fct (ReferenceObjectID id)
void remove_add_jac_A_elem_fct (ReferenceObjectID id)
void remove_add_jac_M_elem_fct (ReferenceObjectID id)
void remove_add_rhs_elem_fct (ReferenceObjectID id)
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_elem_loop_fct (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_fsh_timestep_elem_fct (ReferenceObjectID id)
void remove_fsh_timestep_fct (size_t algebra_id)
void remove_prep_elem_fct (ReferenceObjectID id)
void remove_prep_elem_loop_fct (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_timestep_elem_fct (ReferenceObjectID id)
void remove_prep_timestep_fct (size_t algebra_id)
template<typename TAssFunc >
void set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
sets all assemble functions to the corresponding virtual ones
template<typename TAssFunc >
void set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_fsh_timestep_fct (size_t algebra_id, TAssFunc func)
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
sets current function pattern
template<typename TAssFunc >
void set_prep_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_prep_timestep_fct (size_t algebra_id, TAssFunc func)
void update_function_index_mapping ()
updates the function index mapping
Protected Attributes
int m_si
current inner subset
std::vector< BNDNumberData > m_vBNDNumberData
std::vector< NumberData > m_vNumberData
std::vector< VectorData > m_vVectorData
Protected Attributes inherited from ug::IElemDisc< TDomain >
bool m_bStationaryForced
flag if stationary assembling is to be used even in instationary assembling
FunctionGroup m_fctGrp
current function group
FunctionIndexMapping m_fctIndexMap
current function index mapping
ReferenceObjectID m_id
current Geometric Object
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
list of local vectors for all solutions of the time series
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
Approximation Space.
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > m_spElemModifier
Approximation Space.
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
error estimation object associated to the element discretization
ConstSmartPtr< FunctionPattern > m_spFctPattern
current function pattern
size_t m_timePoint
time point
std::vector< std::string > m_vFct
vector holding name of all symbolic functions
std::vector< IDataImport< dim > * > m_vIImport
data imports
std::vector< std::string > m_vSubset
vector holding name of all symbolic subsets
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
Static Protected Attributes
static const int _C_ = 0
Private Types
typedef NeumannBoundaryBase< TDomain > base_type
Base class type.
typedef SideAndElemErrEstData< TDomain > err_est_type
error estimator type
typedef NeumannBoundaryFV1< TDomain > this_type
Base class type.
Private Member Functions
void register_all_funcs (bool bHang)
template<typename TElem , typename TFVGeom >
void register_func ()
Additional Inherited Members
Public Types inherited from ug::IElemDisc< TDomain >
typedef TDomain domain_type
Domain type.
typedef TDomain::position_type position_type
Position type.
Member Typedef Documentation
base_type
template<typename TDomain > typedef NeumannBoundaryBase<TDomain> ug::NeumannBoundaryFV1< TDomain >::base_type private
Base class type.
err_est_type
template<typename TDomain > typedef SideAndElemErrEstData<TDomain> ug::NeumannBoundaryFV1< TDomain >::err_est_type private
error estimator type
this_type
template<typename TDomain > typedef NeumannBoundaryFV1<TDomain> ug::NeumannBoundaryFV1< TDomain >::this_type private
Base class type.
Constructor & Destructor Documentation
NeumannBoundaryFV1()
template<typename TDomain > ug::NeumannBoundaryFV1< TDomain >::NeumannBoundaryFV1 (const char * function)
default constructor
References ug::NeumannBoundaryFV1< TDomain >::prepare_setting(), and ug::NeumannBoundaryFV1< TDomain >::register_all_funcs().
Member Function Documentation
add() [1/3]
template<typename TDomain > void ug::NeumannBoundaryFV1< TDomain >::add (SmartPtr< CplUserData< number, dim > > data, const char * BndSubsets, const char * InnerSubsets) virtual
add a boundary value
Implements ug::NeumannBoundaryBase< TDomain >.
References ug::NeumannBoundaryBase< TDomain >::add_inner_subsets(), and ug::NeumannBoundaryFV1< TDomain >::m_vNumberData.
Referenced by ug::NeumannBoundaryFV1< TDomain >::add(), and ug::NeumannBoundaryFV1< TDomain >::prepare_setting().
add() [2/3]
template<typename TDomain > void ug::NeumannBoundaryFV1< TDomain >::add (SmartPtr< CplUserData< number, dim, bool > > user, const char * BndSubsets, const char * InnerSubsets) virtual
add a boundary value
Implements ug::NeumannBoundaryBase< TDomain >.
References ug::NeumannBoundaryFV1< TDomain >::add(), ug::NeumannBoundaryBase< TDomain >::add_inner_subsets(), and ug::NeumannBoundaryFV1< TDomain >::m_vBNDNumberData.
add() [3/3]
template<typename TDomain > void ug::NeumannBoundaryFV1< TDomain >::add (SmartPtr< CplUserData< MathVector< dim >, dim > > user, const char * BndSubsets, const char * InnerSubsets) virtual
add a boundary value
Implements ug::NeumannBoundaryBase< TDomain >.
References ug::NeumannBoundaryBase< TDomain >::add_inner_subsets(), and ug::NeumannBoundaryFV1< TDomain >::m_vVectorData.
add_rhs_elem()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NeumannBoundaryFV1< TDomain >::add_rhs_elem (LocalVector & d, GridObject * elem, const MathVector< dim > vCornerCoords[]) protected virtual
assembling functions for fv1
Reimplemented from ug::IElemDisc< TDomain >.
References ug::NeumannBoundaryFV1< TDomain >::_C_, ug::NeumannBoundaryFV1< TDomain >::fsh_elem_loop(), ug::GeomProvider< TGeom >::get(), ug::NeumannBoundaryFV1< TDomain >::m_si, ug::NeumannBoundaryFV1< TDomain >::m_vBNDNumberData, ug::NeumannBoundaryFV1< TDomain >::m_vNumberData, ug::NeumannBoundaryFV1< TDomain >::m_vVectorData, ug::IElemDisc< TDomain >::time(), and ug::VecDot().
Referenced by ug::NeumannBoundaryFV1< TDomain >::prep_elem().
compute_err_est_rhs_elem()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem (GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) protected virtual
computes the error estimator contribution for one element
Reimplemented from ug::IElemDisc< TDomain >.
References ug::SideAndElemErrEstData< TDomain >::all_side_global_ips(), ug::Grid::associated_elements_sorted(), ug::IElemDisc< TDomain >::err_est_data(), ug::SideAndElemErrEstData< TDomain >::first_side_ips(), ug::NeumannBoundaryFV1< TDomain >::fsh_err_est_elem_loop(), ug::NeumannBoundaryFV1< TDomain >::m_si, ug::IElemDisc< TDomain >::m_spErrEstData, ug::NeumannBoundaryFV1< TDomain >::m_vBNDNumberData, ug::NeumannBoundaryFV1< TDomain >::m_vNumberData, ug::NeumannBoundaryFV1< TDomain >::m_vVectorData, ug::SideAndElemErrEstData< TDomain >::num_side_ips(), ug::SideAndElemErrEstData< TDomain >::surface_view(), ug::IElemDisc< TDomain >::time(), UG_THROW, ug::VecDot(), and ug::VecNormalize().
Referenced by ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem().
fsh_elem_loop()
template<typename TDomain > template<typename TElem , typename TGeom > void ug::NeumannBoundaryFV1< TDomain >::fsh_elem_loop () protected virtual
assembling functions for fv1
Reimplemented from ug::IElemDisc< TDomain >.
References ug::GeomProvider< TGeom >::get(), ug::NeumannBoundaryFV1< TDomain >::m_si, ug::NeumannBoundaryFV1< TDomain >::m_vBNDNumberData, ug::NeumannBoundaryFV1< TDomain >::m_vNumberData, ug::NeumannBoundaryFV1< TDomain >::m_vVectorData, and ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem_loop().
Referenced by ug::NeumannBoundaryFV1< TDomain >::add_rhs_elem().
fsh_err_est_elem_loop()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NeumannBoundaryFV1< TDomain >::fsh_err_est_elem_loop () protected virtual
postprocesses the loop over all elements of one type in the computation of the error estimator
Reimplemented from ug::IElemDisc< TDomain >.
References ug::NeumannBoundaryFV1< TDomain >::NumberData::lin_def().
Referenced by ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem().
prep_elem()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NeumannBoundaryFV1< TDomain >::prep_elem (const LocalVector & u, GridObject * elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[]) protected virtual
assembling functions for fv1
Reimplemented from ug::IElemDisc< TDomain >.
References ug::NeumannBoundaryFV1< TDomain >::add_rhs_elem(), ug::GeomProvider< TGeom >::get(), ug::NeumannBoundaryFV1< TDomain >::m_si, ug::NeumannBoundaryFV1< TDomain >::m_vNumberData, ug::IElemDisc< TDomain >::subset_handler(), and UG_CATCH_THROW.
Referenced by ug::NeumannBoundaryFV1< TDomain >::prep_elem_loop().
prep_elem_loop()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NeumannBoundaryFV1< TDomain >::prep_elem_loop (const ReferenceObjectID roid, const int si) protected virtual
assembling functions for fv1
Reimplemented from ug::IElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::clear_imports(), ug::GeomProvider< TGeom >::get(), ug::NeumannBoundaryFV1< TDomain >::m_si, ug::NeumannBoundaryFV1< TDomain >::m_vBNDNumberData, ug::NeumannBoundaryFV1< TDomain >::m_vNumberData, ug::NeumannBoundaryFV1< TDomain >::m_vVectorData, ug::NeumannBoundaryFV1< TDomain >::prep_elem(), ug::IElemDisc< TDomain >::register_import(), and ug::NeumannBoundaryFV1< TDomain >::update_subset_groups().
Referenced by ug::NeumannBoundaryFV1< TDomain >::update_subset_groups().
prep_err_est_elem()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) protected virtual
prepares the element for assembling the error estimator
Reimplemented from ug::IElemDisc< TDomain >.
References ug::SideAndElemErrEstData< TDomain >::all_side_global_ips(), ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem(), ug::IElemDisc< TDomain >::err_est_data(), ug::NeumannBoundaryFV1< TDomain >::m_si, ug::IElemDisc< TDomain >::m_spErrEstData, ug::NeumannBoundaryFV1< TDomain >::m_vNumberData, ug::SideAndElemErrEstData< TDomain >::num_all_side_ips(), ug::GridObject::reference_object_id(), and UG_CATCH_THROW.
Referenced by ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem_loop().
prep_err_est_elem_loop()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem_loop (const ReferenceObjectID roid, const int si) protected virtual
prepares the loop over all elements of one type for the computation of the error estimator
Reimplemented from ug::IElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::clear_imports(), dim, ug::IElemDisc< TDomain >::err_est_data(), ug::NeumannBoundaryFV1< TDomain >::m_si, ug::IElemDisc< TDomain >::m_spErrEstData, ug::NeumannBoundaryFV1< TDomain >::m_vNumberData, ug::SideAndElemErrEstData< TDomain >::num_all_side_ips(), ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem(), ug::IElemDisc< TDomain >::register_import(), UG_CATCH_THROW, UG_THROW, and ug::NeumannBoundaryFV1< TDomain >::update_subset_groups().
Referenced by ug::NeumannBoundaryFV1< TDomain >::fsh_elem_loop().
prepare_setting()
template<typename TDomain > void ug::NeumannBoundaryFV1< TDomain >::prepare_setting (const std::vector< LFEID > & vLfeID, bool bNonRegularGrid) virtual
type of trial space for each function used
Implements ug::IElemDisc< TDomain >.
References ug::NeumannBoundaryFV1< TDomain >::add(), dim, ug::LFEID::LAGRANGE, UG_COND_THROW, and UG_THROW.
Referenced by ug::NeumannBoundaryFV1< TDomain >::NeumannBoundaryFV1().
register_all_funcs()
template<typename TDomain > void ug::NeumannBoundaryFV1< TDomain >::register_all_funcs (bool bHang) private
Referenced by ug::NeumannBoundaryFV1< TDomain >::NumberData::local_ips(), and ug::NeumannBoundaryFV1< TDomain >::NeumannBoundaryFV1().
register_func()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NeumannBoundaryFV1< TDomain >::register_func () private
References ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::set_add_def_A_elem_fct(), ug::IElemDisc< TDomain >::set_add_def_M_elem_fct(), ug::IElemDisc< TDomain >::set_add_jac_A_elem_fct(), ug::IElemDisc< TDomain >::set_add_jac_M_elem_fct(), ug::IElemDisc< TDomain >::set_add_rhs_elem_fct(), ug::IElemDisc< TDomain >::set_compute_err_est_rhs_elem(), ug::IElemDisc< TDomain >::set_fsh_elem_loop_fct(), ug::IElemDisc< TDomain >::set_fsh_err_est_elem_loop(), ug::IElemDisc< TDomain >::set_prep_elem_fct(), ug::IElemDisc< TDomain >::set_prep_elem_loop_fct(), ug::IElemDisc< TDomain >::set_prep_err_est_elem(), and ug::IElemDisc< TDomain >::set_prep_err_est_elem_loop().
update_subset_groups()
template<typename TDomain > void ug::NeumannBoundaryFV1< TDomain >::update_subset_groups () protected
References ug::NeumannBoundaryFV1< TDomain >::m_vBNDNumberData, ug::NeumannBoundaryFV1< TDomain >::m_vNumberData, ug::NeumannBoundaryFV1< TDomain >::m_vVectorData, and ug::NeumannBoundaryFV1< TDomain >::prep_elem_loop().
Referenced by ug::NeumannBoundaryFV1< TDomain >::prep_elem_loop(), and ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem_loop().
Member Data Documentation
_C_
template<typename TDomain > const int ug::NeumannBoundaryFV1< TDomain >::_C_ = 0 static protected
Referenced by ug::NeumannBoundaryFV1< TDomain >::add_rhs_elem(), and ug::NeumannBoundaryFV1< TDomain >::NumberData::lin_def().
dim
template<typename TDomain > const int ug::NeumannBoundaryFV1< TDomain >::dim = base_type::dim static
World dimension.
m_si
template<typename TDomain > int ug::NeumannBoundaryFV1< TDomain >::m_si protected
current inner subset
Referenced by ug::NeumannBoundaryFV1< TDomain >::add_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::fsh_elem_loop(), ug::NeumannBoundaryFV1< TDomain >::prep_elem(), ug::NeumannBoundaryFV1< TDomain >::prep_elem_loop(), ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem(), and ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem_loop().
m_vBNDNumberData
template<typename TDomain > std::vector<BNDNumberData> ug::NeumannBoundaryFV1< TDomain >::m_vBNDNumberData protected
Referenced by ug::NeumannBoundaryFV1< TDomain >::add(), ug::NeumannBoundaryFV1< TDomain >::add_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::fsh_elem_loop(), ug::NeumannBoundaryFV1< TDomain >::prep_elem_loop(), and ug::NeumannBoundaryFV1< TDomain >::update_subset_groups().
m_vNumberData
template<typename TDomain > std::vector<NumberData> ug::NeumannBoundaryFV1< TDomain >::m_vNumberData protected
Referenced by ug::NeumannBoundaryFV1< TDomain >::add(), ug::NeumannBoundaryFV1< TDomain >::add_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::fsh_elem_loop(), ug::NeumannBoundaryFV1< TDomain >::prep_elem(), ug::NeumannBoundaryFV1< TDomain >::prep_elem_loop(), ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem(), ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem_loop(), and ug::NeumannBoundaryFV1< TDomain >::update_subset_groups().
m_vVectorData
template<typename TDomain > std::vector<VectorData> ug::NeumannBoundaryFV1< TDomain >::m_vVectorData protected
Referenced by ug::NeumannBoundaryFV1< TDomain >::add(), ug::NeumannBoundaryFV1< TDomain >::add_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::fsh_elem_loop(), ug::NeumannBoundaryFV1< TDomain >::prep_elem_loop(), and ug::NeumannBoundaryFV1< TDomain >::update_subset_groups().
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/elem_disc/neumann_boundary/fv1/neumann_boundary_fv1.h
ugbase/lib_disc/spatial_disc/elem_disc/neumann_boundary/fv1/neumann_boundary_fv1.cpp