ug4: pcl::OrderedInterface< TType, TContainer, TAlloc > Class Template Reference
pcl::OrderedInterface< TType, TContainer, TAlloc > Class Template Reference
ugbase » PCL
You may add elements to this interface and iterate over them.
#include <pcl_communication_structs.h>
Classes
struct InterfaceEntry
struct InterfaceEntryCmp
Public Types
typedef interface_tags::ordered_interface_tag category_tag
typedef ElemContainer::const_iterator const_iterator
typedef type_traits< TType >::Elem Element
typedef ElemContainer::iterator iterator
typedef TType Type
Public Member Functions
iterator begin ()
const_iterator begin () const
bool empty () const
iterator end ()
const_iterator end () const
iterator erase (iterator iter)
template<class TCompare >
iterator find_insert_pos_sorted (const Element e, TCompare cmp)
find insertion position for an element to be inserted
const Element & get_element (const_iterator iter) const
Element & get_element (iterator iter)
size_t get_local_id (const_iterator iter) const
size_t get_local_id (iterator iter)
int get_target_proc () const
iterator insert (const Element &elem, iterator insertBefore)
Insert an element before the passed iterator.
OrderedInterface (int targetProc=-1)
iterator push_back (const Element &elem)
size_t size () const
returns the number of elements that are stored in the interface.
template<class TCompare >
void sort (TCompare cmp)
sort the entries in this interface.
void swap (OrderedInterface &interface)
swaps the content of two interfaces.
Static Public Member Functions
static bool cmp (iterator iter1, iterator iter2, const std::input_iterator_tag &)
returns true if iter1 < iter2.
Protected Types
typedef TContainer< InterfaceEntry, TAlloc< InterfaceEntry > > ElemContainer
typedef type_traits< TType >::Elem TElem
Protected Member Functions
size_t get_free_id ()
returns a free id in each call.
Protected Attributes
ElemContainer m_elements
size_t m_idCounter
size_t m_size
int m_targetProc
Detailed Description
template<class TType, template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator>
class pcl::OrderedInterface< TType, TContainer, TAlloc >
You may add elements to this interface and iterate over them.
You may retrieve a localID for each element in the interface
Member Typedef Documentation
category_tag
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> typedef interface_tags::ordered_interface_tag pcl::OrderedInterface< TType, TContainer, TAlloc >::category_tag
const_iterator
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> typedef ElemContainer::const_iterator pcl::OrderedInterface< TType, TContainer, TAlloc >::const_iterator
ElemContainer
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> typedef TContainer<InterfaceEntry, TAlloc<InterfaceEntry> > pcl::OrderedInterface< TType, TContainer, TAlloc >::ElemContainer protected
Element
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> typedef type_traits<TType>::Elem pcl::OrderedInterface< TType, TContainer, TAlloc >::Element
iterator
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> typedef ElemContainer::iterator pcl::OrderedInterface< TType, TContainer, TAlloc >::iterator
TElem
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> typedef type_traits<TType>::Elem pcl::OrderedInterface< TType, TContainer, TAlloc >::TElem protected
Type
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> typedef TType pcl::OrderedInterface< TType, TContainer, TAlloc >::Type
Constructor & Destructor Documentation
OrderedInterface()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> pcl::OrderedInterface< TType, TContainer, TAlloc >::OrderedInterface (int targetProc = -1) inline
Member Function Documentation
begin() [1/2]
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> iterator pcl::OrderedInterface< TType, TContainer, TAlloc >::begin () inline
References pcl::OrderedInterface< TType, TContainer, TAlloc >::m_elements.
Referenced by ug::ComPol_VecCopy< TVector >::collect(), ug::ComPol_VecScaleCopy< TVector >::collect(), ug::ComPol_VecAdd< TVector >::collect(), ug::ComPol_VecScaleAdd< TVector >::collect(), ug::ComPol_VecAddSetZero< TVector >::collect(), ug::ComPol_VecSubtract< TVector >::collect(), ug::ComPol_CheckConsistency< TVector >::collect(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::collect(), ug::ComPol_MatDistributeDiag< TAlgebra >::collect(), ug::ComPol_MatAddRowsOverlap0< TMatrix >::collect(), ug::ComPol_MatCopyRowsOverlap0< TMatrix >::collect(), ug::ComPol_MatAddSetZeroInnerInterfaceCouplings< TMatrix >::collect(), ug::CommunicationScheme< TDerived, TValue >::collect(), ug::CommunicationScheme< TDerived, bool >::collect(), ug::ComPol_MatCopyDiag< TMatrix >::collect(), ug::ComPol_MatCreateOverlap< TMatrix >::collect(), ug::ComPol_VecCopy< TVector >::extract(), ug::ComPol_VecScaleCopy< TVector >::extract(), ug::ComPol_VecAdd< TVector >::extract(), ug::ComPol_VecScaleAdd< TVector >::extract(), ug::ComPol_VecAddSetZero< TVector >::extract(), ug::ComPol_VecSubtract< TVector >::extract(), ug::ComPol_CheckConsistency< TVector >::extract(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::extract(), ug::ComPol_MatDistributeDiag< TAlgebra >::extract(), ug::ComPol_MatAddRowsOverlap0< TMatrix >::extract(), ug::ComPol_MatCopyRowsOverlap0< TMatrix >::extract(), ug::ComPol_MatAddSetZeroInnerInterfaceCouplings< TMatrix >::extract(), ug::CommunicationScheme< TDerived, TValue >::extract(), ug::CommunicationScheme< TDerived, bool >::extract(), ug::ComPol_MatCopyDiag< TMatrix >::extract(), ug::ComPol_MatCreateOverlap< TMatrix >::extract(), pcl::OrderedInterface< TType, TContainer, TAlloc >::get_free_id(), ug::SlicingData< TVec, N >::replace_indices_in_layout(), ug::SerializeInterface(), and ug::SetInterfaceValues().
begin() [2/2]
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> const_iterator pcl::OrderedInterface< TType, TContainer, TAlloc >::begin () const inline
References pcl::OrderedInterface< TType, TContainer, TAlloc >::m_elements.
cmp()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> static bool pcl::OrderedInterface< TType, TContainer, TAlloc >::cmp (iterator iter1, iterator iter2, const std::input_iterator_tag &) inline static
returns true if iter1 < iter2.
Referenced by pcl::OrderedInterface< TType, TContainer, TAlloc >::find_insert_pos_sorted(), and pcl::OrderedInterface< TType, TContainer, TAlloc >::sort().
empty()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> bool pcl::OrderedInterface< TType, TContainer, TAlloc >::empty () const inline
References pcl::OrderedInterface< TType, TContainer, TAlloc >::size().
end() [1/2]
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> iterator pcl::OrderedInterface< TType, TContainer, TAlloc >::end () inline
References pcl::OrderedInterface< TType, TContainer, TAlloc >::m_elements.
Referenced by ug::ComPol_VecCopy< TVector >::collect(), ug::ComPol_VecScaleCopy< TVector >::collect(), ug::ComPol_VecAdd< TVector >::collect(), ug::ComPol_VecScaleAdd< TVector >::collect(), ug::ComPol_VecAddSetZero< TVector >::collect(), ug::ComPol_VecSubtract< TVector >::collect(), ug::ComPol_CheckConsistency< TVector >::collect(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::collect(), ug::ComPol_MatDistributeDiag< TAlgebra >::collect(), ug::ComPol_MatAddRowsOverlap0< TMatrix >::collect(), ug::ComPol_MatCopyRowsOverlap0< TMatrix >::collect(), ug::ComPol_MatAddSetZeroInnerInterfaceCouplings< TMatrix >::collect(), ug::CommunicationScheme< TDerived, TValue >::collect(), ug::CommunicationScheme< TDerived, bool >::collect(), ug::ComPol_MatCopyDiag< TMatrix >::collect(), ug::ComPol_MatCreateOverlap< TMatrix >::collect(), ug::ComPol_VecCopy< TVector >::extract(), ug::ComPol_VecScaleCopy< TVector >::extract(), ug::ComPol_VecAdd< TVector >::extract(), ug::ComPol_VecScaleAdd< TVector >::extract(), ug::ComPol_VecAddSetZero< TVector >::extract(), ug::ComPol_VecSubtract< TVector >::extract(), ug::ComPol_CheckConsistency< TVector >::extract(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::extract(), ug::ComPol_MatDistributeDiag< TAlgebra >::extract(), ug::ComPol_MatAddRowsOverlap0< TMatrix >::extract(), ug::ComPol_MatCopyRowsOverlap0< TMatrix >::extract(), ug::ComPol_MatAddSetZeroInnerInterfaceCouplings< TMatrix >::extract(), ug::CommunicationScheme< TDerived, TValue >::extract(), ug::CommunicationScheme< TDerived, bool >::extract(), ug::ComPol_MatCopyDiag< TMatrix >::extract(), ug::ComPol_MatCreateOverlap< TMatrix >::extract(), pcl::OrderedInterface< TType, TContainer, TAlloc >::get_free_id(), pcl::OrderedInterface< TType, TContainer, TAlloc >::insert(), ug::SlicingData< TVec, N >::replace_indices_in_layout(), ug::SerializeInterface(), and ug::SetInterfaceValues().
end() [2/2]
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> const_iterator pcl::OrderedInterface< TType, TContainer, TAlloc >::end () const inline
References pcl::OrderedInterface< TType, TContainer, TAlloc >::m_elements.
erase()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> iterator pcl::OrderedInterface< TType, TContainer, TAlloc >::erase (iterator iter) inline
References pcl::OrderedInterface< TType, TContainer, TAlloc >::m_elements, and pcl::OrderedInterface< TType, TContainer, TAlloc >::m_size.
Referenced by ug::SlicingData< TVec, N >::replace_indices_in_layout().
find_insert_pos_sorted()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> template<class TCompare > iterator pcl::OrderedInterface< TType, TContainer, TAlloc >::find_insert_pos_sorted (const Element e, TCompare cmp) inline
find insertion position for an element to be inserted
Returns
iterator to insertion position if found; end-iterator otherwise
Warning
This method implicitly requires the interface to be sorted w.r.t. the passed compare object. If it is not, the position might not be correct.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::cmp(), and pcl::OrderedInterface< TType, TContainer, TAlloc >::m_elements.
get_element() [1/2]
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> const Element& pcl::OrderedInterface< TType, TContainer, TAlloc >::get_element (const_iterator iter) const inline
get_element() [2/2]
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> Element& pcl::OrderedInterface< TType, TContainer, TAlloc >::get_element (iterator iter) inline
Referenced by ug::DoFDistribution::add_indices_from_layouts(), ug::AddEntriesToIndexLayout_DomainDecomposition(), ug::AddEntriesToSurfaceIndexLayout(), ug::ParallelVector< TVector >::check_storage_type(), ug::ComPol_VecCopy< TVector >::collect(), ug::ComPol_VecScaleCopy< TVector >::collect(), ug::ComPol_VecAdd< TVector >::collect(), ug::ComPol_VecScaleAdd< TVector >::collect(), ug::ComPol_VecAddSetZero< TVector >::collect(), ug::ComPol_VecSubtract< TVector >::collect(), ug::ComPol_CheckConsistency< TVector >::collect(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::collect(), ug::ComPol_MatDistributeDiag< TAlgebra >::collect(), ug::ComPol_MatAddRowsOverlap0< TMatrix >::collect(), ug::ComPol_MatCopyRowsOverlap0< TMatrix >::collect(), ug::ComPol_MatAddSetZeroInnerInterfaceCouplings< TMatrix >::collect(), ug::CommunicationScheme< TDerived, TValue >::collect(), ug::CommunicationScheme< TDerived, bool >::collect(), ug::ComPol_MatCopyDiag< TMatrix >::collect(), ug::ComPol_MatCreateOverlap< TMatrix >::collect(), ug::CopyInterfaceEntrysToDomainDecompositionLayouts(), ug::ComPol_VecCopy< TVector >::extract(), ug::ComPol_VecScaleCopy< TVector >::extract(), ug::ComPol_VecAdd< TVector >::extract(), ug::ComPol_VecScaleAdd< TVector >::extract(), ug::ComPol_VecAddSetZero< TVector >::extract(), ug::ComPol_VecSubtract< TVector >::extract(), ug::ComPol_CheckConsistency< TVector >::extract(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::extract(), ug::ComPol_MatDistributeDiag< TAlgebra >::extract(), ug::ComPol_MatAddRowsOverlap0< TMatrix >::extract(), ug::ComPol_MatCopyRowsOverlap0< TMatrix >::extract(), ug::ComPol_MatAddSetZeroInnerInterfaceCouplings< TMatrix >::extract(), ug::CommunicationScheme< TDerived, TValue >::extract(), ug::CommunicationScheme< TDerived, bool >::extract(), ug::ComPol_MatCopyDiag< TMatrix >::extract(), ug::ComPol_MatCreateOverlap< TMatrix >::extract(), ug::GetHighestReferencedIndex(), ug::MatExtractDiagOnLayout(), ug::MatWriteDiagOnLayout(), ug::PermuteIndicesInIndexLayout(), ug::SlicingData< TVec, N >::replace_indices_in_layout(), ug::ScaleLayoutValues(), ug::SerializeInterface(), ug::SetInterfaceValues(), and ug::SetLayoutValues().
get_free_id()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> size_t pcl::OrderedInterface< TType, TContainer, TAlloc >::get_free_id () inline protected
returns a free id in each call.
Those ids are not necessarily aligned.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::begin(), pcl::OrderedInterface< TType, TContainer, TAlloc >::end(), and pcl::OrderedInterface< TType, TContainer, TAlloc >::m_idCounter.
Referenced by pcl::OrderedInterface< TType, TContainer, TAlloc >::insert(), and pcl::OrderedInterface< TType, TContainer, TAlloc >::push_back().
get_local_id() [1/2]
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> size_t pcl::OrderedInterface< TType, TContainer, TAlloc >::get_local_id (const_iterator iter) const inline
get_local_id() [2/2]
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> size_t pcl::OrderedInterface< TType, TContainer, TAlloc >::get_local_id (iterator iter) inline
get_target_proc()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> int pcl::OrderedInterface< TType, TContainer, TAlloc >::get_target_proc () const inline
References pcl::OrderedInterface< TType, TContainer, TAlloc >::m_targetProc.
Referenced by ug::CommunicationScheme< TDerived, TValue >::collect(), ug::CommunicationScheme< TDerived, bool >::collect(), ug::CommunicationScheme< TDerived, TValue >::extract(), ug::CommunicationScheme< TDerived, bool >::extract(), ug::ComPol_MatCreateOverlap< TMatrix >::extract(), and ug::ComPol_MatCreateOverlap< TMatrix >::post_process().
insert()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> iterator pcl::OrderedInterface< TType, TContainer, TAlloc >::insert (const Element & elem, iterator insertBefore) inline
Insert an element before the passed iterator.
The insertion iterator is best determined using the find_insert_pos_sorted() method designed for this purpose.
Returns
iterator to inserted element
Note
The method is intended for manipulation of the interface after it has been ordered and only suited for a small number of insertions (typically a single insertion). For more insertions, consider push_back() and re-ordering.
Warning
This method is highly experimental. Use with extreme caution!
References pcl::OrderedInterface< TType, TContainer, TAlloc >::end(), pcl::OrderedInterface< TType, TContainer, TAlloc >::get_free_id(), pcl::OrderedInterface< TType, TContainer, TAlloc >::m_elements, and pcl::OrderedInterface< TType, TContainer, TAlloc >::m_size.
push_back()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> iterator pcl::OrderedInterface< TType, TContainer, TAlloc >::push_back (const Element & elem) inline
References pcl::OrderedInterface< TType, TContainer, TAlloc >::get_free_id(), pcl::OrderedInterface< TType, TContainer, TAlloc >::m_elements, and pcl::OrderedInterface< TType, TContainer, TAlloc >::m_size.
Referenced by ug::DistributedGridManager::add_element_to_interface(), ug::AddConnectionsBetweenSlaves(), ug::AddExtraProcessEntriesToSubdomainLayout(), ug::AddLayoutFromGlobalLayout(), ug::BuildOneToManyLayout(), ug::DeserializeInterface(), ug::ComPol_MatCreateOverlap< TMatrix >::post_process(), ug::ReceiveMatrix(), and ug::SendMatrix().
size()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> size_t pcl::OrderedInterface< TType, TContainer, TAlloc >::size () const inline
returns the number of elements that are stored in the interface.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::m_size.
Referenced by ug::ComPol_MatAddSetZeroInnerInterfaceCouplings< TMatrix >::collect(), pcl::OrderedInterface< TType, TContainer, TAlloc >::empty(), ug::ComPol_MatAddSetZeroInnerInterfaceCouplings< TMatrix >::extract(), ug::ComPol_VecCopy< TVector >::get_required_buffer_size(), ug::ComPol_VecScaleCopy< TVector >::get_required_buffer_size(), ug::ComPol_VecAdd< TVector >::get_required_buffer_size(), ug::ComPol_VecScaleAdd< TVector >::get_required_buffer_size(), ug::ComPol_VecAddSetZero< TVector >::get_required_buffer_size(), ug::ComPol_VecSubtract< TVector >::get_required_buffer_size(), ug::ComPol_CheckConsistency< TVector >::get_required_buffer_size(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::get_required_buffer_size(), ug::ComPol_MatDistributeDiag< TAlgebra >::get_required_buffer_size(), ug::CommunicationScheme< TDerived, TValue >::get_required_buffer_size(), ug::CommunicationScheme< TDerived, bool >::get_required_buffer_size(), ug::ComPol_MatCopyDiag< TMatrix >::get_required_buffer_size(), ug::NumIndices(), ug::BGLParallelMatrix< T >::refresh(), and ug::SerializeInterface().
sort()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> template<class TCompare > void pcl::OrderedInterface< TType, TContainer, TAlloc >::sort (TCompare cmp) inline
sort the entries in this interface.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::cmp(), pcl::OrderedInterface< TType, TContainer, TAlloc >::m_elements, and pcl::OrderedInterface< TType, TContainer, TAlloc >::m_idCounter.
swap()
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> void pcl::OrderedInterface< TType, TContainer, TAlloc >::swap (OrderedInterface< TType, TContainer, TAlloc > & interface) inline
swaps the content of two interfaces.
m_elements, m_size, m_targetProc and m_idCounter are swapped.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::m_elements, pcl::OrderedInterface< TType, TContainer, TAlloc >::m_idCounter, pcl::OrderedInterface< TType, TContainer, TAlloc >::m_size, and pcl::OrderedInterface< TType, TContainer, TAlloc >::m_targetProc.
Member Data Documentation
m_elements
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> ElemContainer pcl::OrderedInterface< TType, TContainer, TAlloc >::m_elements protected
Referenced by pcl::OrderedInterface< TType, TContainer, TAlloc >::begin(), pcl::OrderedInterface< TType, TContainer, TAlloc >::end(), pcl::OrderedInterface< TType, TContainer, TAlloc >::erase(), pcl::OrderedInterface< TType, TContainer, TAlloc >::find_insert_pos_sorted(), pcl::OrderedInterface< TType, TContainer, TAlloc >::insert(), pcl::OrderedInterface< TType, TContainer, TAlloc >::push_back(), pcl::OrderedInterface< TType, TContainer, TAlloc >::sort(), and pcl::OrderedInterface< TType, TContainer, TAlloc >::swap().
m_idCounter
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> size_t pcl::OrderedInterface< TType, TContainer, TAlloc >::m_idCounter protected
Referenced by pcl::OrderedInterface< TType, TContainer, TAlloc >::get_free_id(), pcl::OrderedInterface< TType, TContainer, TAlloc >::sort(), and pcl::OrderedInterface< TType, TContainer, TAlloc >::swap().
m_size
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> size_t pcl::OrderedInterface< TType, TContainer, TAlloc >::m_size protected
Referenced by pcl::OrderedInterface< TType, TContainer, TAlloc >::erase(), pcl::OrderedInterface< TType, TContainer, TAlloc >::insert(), pcl::OrderedInterface< TType, TContainer, TAlloc >::push_back(), pcl::OrderedInterface< TType, TContainer, TAlloc >::size(), and pcl::OrderedInterface< TType, TContainer, TAlloc >::swap().
m_targetProc
template<class TType , template< class T, class Alloc > class TContainer = std::vector, template< class T > class TAlloc = std::allocator> int pcl::OrderedInterface< TType, TContainer, TAlloc >::m_targetProc protected
Referenced by pcl::OrderedInterface< TType, TContainer, TAlloc >::get_target_proc(), and pcl::OrderedInterface< TType, TContainer, TAlloc >::swap().
The documentation for this class was generated from the following file:
ugbase/pcl/pcl_communication_structs.h