ug4: ug::Hexahedron Class Reference
ug::Hexahedron Class Reference
lib_grid » geometric objects
A volume element with 6 quadrilateral sides.
#include <grid_objects_3d.h>
Public Types
typedef Volume BaseClass
Public Types inherited from ug::Volume
typedef Volume grid_base_object
typedef void higher_dim_base_object
typedef Face lower_dim_base_object
typedef Face side
typedef Volume sideof
Public Types inherited from ug::IVertexGroup
typedef Vertex *const * ConstVertexArray
Public Member Functions
virtual bool collapse_edge (std::vector< Volume * > &vNewVolumesOut, int edgeIndex, Vertex *newVertex, std::vector< Vertex * > *pvSubstituteVertices=NULL)
virtual int container_section () const
virtual Edge * create_edge (int index)
create the edge with index i and return it.
virtual GridObject * create_empty_instance () const
create an instance of the derived type
virtual Face * create_face (int index)
create the face with index i and return it.
virtual EdgeDescriptor edge_desc (int index) const
virtual void edge_desc (int index, EdgeDescriptor &edOut) const
virtual FaceDescriptor face_desc (int index) const
virtual void face_desc (int index, FaceDescriptor &fdOut) const
virtual void get_flipped_orientation (VolumeDescriptor &vdOut) const
virtual std::pair< GridBaseObjectId, int > get_opposing_object (Vertex *vrt) const
returns an index to the obbject, which lies on the opposite side of the volume to the given vertex.
virtual bool get_opposing_side (FaceVertices *f, FaceDescriptor &fdOut) const
retrieves the face-descriptor for the opposing side to the specified one.
Hexahedron ()
Hexahedron (const HexahedronDescriptor &td)
Hexahedron (Vertex *v1, Vertex *v2, Vertex *v3, Vertex *v4, Vertex *v5, Vertex *v6, Vertex *v7, Vertex *v8)
virtual uint num_edges () const
virtual uint num_faces () const
virtual size_t num_vertices () const
virtual ReferenceObjectID reference_object_id () const
virtual bool refine (std::vector< Volume * > &vNewVolumesOut, Vertex **ppNewVertexOut, Vertex **newEdgeVertices, Vertex **newFaceVertices, Vertex *newVolumeVertex, const Vertex &prototypeVertex, Vertex **pSubstituteVertices=NULL, vector3 *corners=NULL)
see Volume::refine for a detailed description.
virtual Vertex * vertex (size_t index) const
virtual ConstVertexArray vertices () const
Public Member Functions inherited from ug::Volume
virtual int base_object_id () const
int get_local_side_index (FaceVertices *f) const
returns the local index of the given face or -1, if the face is not part of the volume.
virtual void get_local_vertex_indices_of_edge (size_t &ind1Out, size_t &ind2Out, size_t edgeInd) const
returns the local indices of an edge of the volume.
virtual void get_local_vertex_indices_of_face (std::vector< size_t > &indsOut, size_t side) const
returns the local indices of a face of the volume.
uint num_sides () const
virtual ~Volume ()
Public Member Functions inherited from ug::GridObject
uint grid_data_index () const
Returns the grid attachment data index of a geometric object.
virtual bool is_constrained () const
returns true if the object is constrained by other objects.
virtual bool is_constraining () const
returns the id of the reference-object.
virtual ~GridObject ()
Public Member Functions inherited from ug::VolumeVertices
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~VolumeVertices ()
Public Member Functions inherited from ug::IVertexGroup
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~IVertexGroup ()
Static Public Member Functions
static bool type_match (GridObject *pObj)
Static Public Member Functions inherited from ug::Volume
static bool type_match (GridObject *pObj)
Static Public Attributes
static const size_t NUM_VERTICES = 8
Static Public Attributes inherited from ug::Volume
static const int BASE_OBJECT_ID = VOLUME
static const bool CAN_BE_SIDE = false
static const int dim = 3
reference dimension
static const bool HAS_SIDES = true
Protected Member Functions
virtual void set_vertex (uint index, Vertex *pVrt)
Protected Member Functions inherited from ug::GridObject
void set_grid_data_index (uint index)
ATTENTION: Use this method with extreme care!
Protected Attributes
Vertex * m_vertices [8]
Protected Attributes inherited from ug::GridObject
uint m_gridDataIndex
Detailed Description
A volume element with 6 quadrilateral sides.
Order of vertices should be the same as described in
See also
HexahedronDescriptor
Member Typedef Documentation
typedef Volume ug::Hexahedron::BaseClass
Constructor & Destructor Documentation
ug::Hexahedron::Hexahedron () inline
ug::Hexahedron::Hexahedron (const HexahedronDescriptor & td)
References ug::HexahedronDescriptor::vertex().
ug::Hexahedron::Hexahedron (Vertex * v1, Vertex * v2, Vertex * v3, Vertex * v4, Vertex * v5, Vertex * v6, Vertex * v7, Vertex * v8)
Member Function Documentation
bool ug::Hexahedron::collapse_edge (std::vector< Volume * > & vNewVolumesOut, int edgeIndex, Vertex * newVertex, std::vector< Vertex * > * pvSubstituteVertices = NULL) virtual
The collapse_edge method creates new geometric objects by collapsing the specified edge. The user that calls this function is responsible to either register the new faces with a grid (the grid from which the vertices are), or to take responsibility for deletion of the acquired memory (delete each element in vNewFacesOut).
edgeIndex specifies the edge which shall be collapsed. edgeIndex has to lie between 0 and this->num_edges().
Vertices adjacent to the collapsed edge will be replaced by newVertex.
If you specify pvSubstituteVertices, the created faces will reference the vertices in pvSubstituteVertices. Note that pvSubstituteVertices has to contain exactly as many vertices as the face in which you collapse the edge. Vertices with the same index correlate.
Reimplemented from ug::Volume.
References UG_LOG.
virtual int ug::Hexahedron::container_section () const inline virtual
Reimplemented from ug::Volume.
References ug::CSVOL_HEXAHEDRON.
Edge * ug::Hexahedron::create_edge (int index) virtual
create the edge with index i and return it.
Reimplemented from ug::Volume.
References ug::hex_rules::EDGE_VRT_INDS, and ug::hex_rules::NUM_EDGES.
virtual GridObject* ug::Hexahedron::create_empty_instance () const inline virtual
create an instance of the derived type
Make sure to overload this method in derivates of this class!
Reimplemented from ug::GridObject.
Face * ug::Hexahedron::create_face (int index) virtual
create the face with index i and return it.
Reimplemented from ug::Volume.
References ug::hex_rules::FACE_VRT_INDS, and ug::hex_rules::NUM_FACES.
EdgeDescriptor ug::Hexahedron::edge_desc (int index) const virtual
Reimplemented from ug::Volume.
void ug::Hexahedron::edge_desc (int index, EdgeDescriptor & edOut) const virtual
Reimplemented from ug::Volume.
References ug::hex_rules::EDGE_VRT_INDS, ug::hex_rules::NUM_EDGES, and ug::EdgeDescriptor::set_vertices().
FaceDescriptor ug::Hexahedron::face_desc (int index) const virtual
Reimplemented from ug::Volume.
void ug::Hexahedron::face_desc (int index, FaceDescriptor & fdOut) const virtual
Reimplemented from ug::Volume.
References ug::hex_rules::FACE_VRT_INDS, ug::hex_rules::NUM_FACES, ug::FaceDescriptor::set_num_vertices(), and ug::FaceDescriptor::set_vertex().
void ug::Hexahedron::get_flipped_orientation (VolumeDescriptor & vdOut) const virtual
Writes vertices to the volume-descriptor so that it defines a volume with flipped orientation. If you want to flip the orientation of a volume in a grid, please consider using the grids flip_orientation method.
Please note: The default implementation returns the original volume and has to be reimplemented by derived classes.
Reimplemented from ug::Volume.
References ug::VolumeDescriptor::set_num_vertices(), and ug::VolumeDescriptor::set_vertex().
std::pair< GridBaseObjectId, int > ug::Hexahedron::get_opposing_object (Vertex * vrt) const virtual
returns an index to the obbject, which lies on the opposite side of the volume to the given vertex.
The method returs a pair <GridBaseObjectId, int>, where GridBaseObjectId is either VERTEX, EDGE, or FACE and where the second entry specifies the local index of the object in the given volume.
Reimplemented from ug::Volume.
References ug::hex_rules::NUM_VERTICES, ug::hex_rules::OPPOSED_OBJECT, and UG_THROW.
bool ug::Hexahedron::get_opposing_side (FaceVertices * f, FaceDescriptor & fdOut) const virtual
retrieves the face-descriptor for the opposing side to the specified one.
If no opposing side exists false is returned. If an opposing side exists, the method returns true and fills the specified descriptor.
Reimplemented from ug::Volume.
References ug::hex_rules::OPPOSED_FACE.
uint ug::Hexahedron::num_edges () const virtual
Reimplemented from ug::Volume.
uint ug::Hexahedron::num_faces () const virtual
Reimplemented from ug::Volume.
virtual size_t ug::Hexahedron::num_vertices () const inline virtual
Reimplemented from ug::VolumeVertices.
virtual ReferenceObjectID ug::Hexahedron::reference_object_id () const inline virtual
A reference object represents a class of geometric objects. Tetrahedrons, Triangles etc are such classes. Reference ids should be defined in the file in which concrete geometric objects are defined.
Reimplemented from ug::Volume.
References ug::ROID_HEXAHEDRON.
bool ug::Hexahedron::refine (std::vector< Volume * > & vNewVolumesOut, Vertex ** ppNewVertexOut, Vertex ** newEdgeVertices, Vertex ** newFaceVertices, Vertex * newVolumeVertex, const Vertex & prototypeVertex, Vertex ** pSubstituteVertices = NULL, vector3 * corners = NULL) virtual
see Volume::refine for a detailed description.
Reimplemented from ug::Volume.
References ug::Refine().
virtual void ug::Hexahedron::set_vertex (uint index, Vertex * pVrt) inline protected virtual
creates the volumes that result from the splitting of the edge with index 'splitEdgeIndex'. creates the volumes that result from the collapsing of the edge with index 'splitEdgeIndex'.
Reimplemented from ug::Volume.
static bool ug::Hexahedron::type_match (GridObject * pObj) inline static
virtual Vertex* ug::Hexahedron::vertex (size_t index) const inline virtual
Reimplemented from ug::VolumeVertices.
Referenced by ug::CalculateVolume(), ug::SerializeGridElements(), and ug::SerializeMultiGridElements().
virtual ConstVertexArray ug::Hexahedron::vertices () const inline virtual
Reimplemented from ug::VolumeVertices.
Member Data Documentation
Vertex* ug::Hexahedron::m_vertices[8] protected
const size_t ug::Hexahedron::NUM_VERTICES = 8 static
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid_objects/grid_objects_3d.h
ugbase/lib_grid/grid_objects/grid_objects_3d.cpp