ug4: ug::HFV1Geometry< TElem, TWorldDim >::SCV Class Reference
ug::HFV1Geometry< TElem, TWorldDim >::SCV Class Reference
#include <hfv1_geom.h>
Public Member Functions
const MathVector< worldDim > & global_corner (size_t co) const
return global corner number i
const MathVector< worldDim > & global_ip () const
global integration point
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_ip () const
local integration point of scv
size_t node_id () const
node id that this scv is associated to
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points
SCV ()
number volume () const
volume of scv
Private Types
typedef hfv1_traits< ref_elem_type, TWorldDim >::scv_type scv_type
type of element the subcontrol volume represents
Private Attributes
MidID m_midId [m_maxNumCorners]
size_t m_numCorners
MathVector< worldDim > m_vGloPos [m_maxNumCorners]
MathVector< dim > m_vLocPos [m_maxNumCorners]
size_t nodeId
number vol
Static Private Attributes
static const size_t m_maxNumCorners = hfv1_traits<ref_elem_type, TWorldDim>::MaxNumCornersOfSCV
Number of corners of scvf.
static const size_t m_numIP = 1
number of integration points
Friends
class HFV1Geometry< TElem, TWorldDim >
Member Typedef Documentation
scv_type
template<typename TElem , int TWorldDim> typedef hfv1_traits<ref_elem_type, TWorldDim>::scv_type ug::HFV1Geometry< TElem, TWorldDim >::SCV::scv_type private
type of element the subcontrol volume represents
Constructor & Destructor Documentation
SCV()
template<typename TElem , int TWorldDim> ug::HFV1Geometry< TElem, TWorldDim >::SCV::SCV () inline
Member Function Documentation
global_corner()
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::HFV1Geometry< TElem, TWorldDim >::SCV::global_corner (size_t co) const inline
return global corner number i
References ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_vGloPos, ug::HFV1Geometry< TElem, TWorldDim >::SCV::num_corners(), and UG_ASSERT.
global_ip()
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::HFV1Geometry< TElem, TWorldDim >::SCV::global_ip () const inline
global integration point
References ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_vGloPos.
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::update().
local_corner()
template<typename TElem , int TWorldDim> const MathVector<dim>& ug::HFV1Geometry< TElem, TWorldDim >::SCV::local_corner (size_t co) const inline
return local corner number i
References ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_vLocPos, ug::HFV1Geometry< TElem, TWorldDim >::SCV::num_corners(), and UG_ASSERT.
local_ip()
template<typename TElem , int TWorldDim> const MathVector<dim>& ug::HFV1Geometry< TElem, TWorldDim >::SCV::local_ip () const inline
local integration point of scv
References ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_vLocPos.
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::update().
node_id()
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::SCV::node_id () const inline
node id that this scv is associated to
References ug::HFV1Geometry< TElem, TWorldDim >::SCV::nodeId.
num_corners()
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::SCV::num_corners () const inline
number of corners, that bound the scvf
References ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_numCorners.
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::copy_global_corners(), ug::HFV1Geometry< TElem, TWorldDim >::copy_local_corners(), ug::HFV1Geometry< TElem, TWorldDim >::SCV::global_corner(), and ug::HFV1Geometry< TElem, TWorldDim >::SCV::local_corner().
num_ip()
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::SCV::num_ip () const inline
number of integration points
References ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_numIP.
volume()
template<typename TElem , int TWorldDim> number ug::HFV1Geometry< TElem, TWorldDim >::SCV::volume () const inline
volume of scv
References ug::HFV1Geometry< TElem, TWorldDim >::SCV::vol.
Friends And Related Function Documentation
HFV1Geometry< TElem, TWorldDim >
template<typename TElem , int TWorldDim> friend class HFV1Geometry< TElem, TWorldDim > friend
Member Data Documentation
m_maxNumCorners
template<typename TElem , int TWorldDim> const size_t ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_maxNumCorners = hfv1_traits<ref_elem_type, TWorldDim>::MaxNumCornersOfSCV static private
Number of corners of scvf.
m_midId
template<typename TElem , int TWorldDim> MidID ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_midId[m_maxNumCorners] private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::copy_global_corners(), and ug::HFV1Geometry< TElem, TWorldDim >::copy_local_corners().
m_numCorners
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_numCorners private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::SCV::num_corners().
m_numIP
template<typename TElem , int TWorldDim> const size_t ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_numIP = 1 static private
number of integration points
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::SCV::num_ip().
m_vGloPos
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_vGloPos[m_maxNumCorners] private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::copy_global_corners(), ug::HFV1Geometry< TElem, TWorldDim >::SCV::global_corner(), and ug::HFV1Geometry< TElem, TWorldDim >::SCV::global_ip().
m_vLocPos
template<typename TElem , int TWorldDim> MathVector<dim> ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_vLocPos[m_maxNumCorners] private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::copy_local_corners(), ug::HFV1Geometry< TElem, TWorldDim >::SCV::local_corner(), and ug::HFV1Geometry< TElem, TWorldDim >::SCV::local_ip().
nodeId
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::SCV::nodeId private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::SCV::node_id().
vol
template<typename TElem , int TWorldDim> number ug::HFV1Geometry< TElem, TWorldDim >::SCV::vol private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::SCV::volume().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/hfv1_geom.h