ug4: ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF Class Reference
ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF Class Reference
boundary face
#include <fvho_geom.h>
Public Member Functions
BF ()
number detJ (size_t ip) const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_corner (size_t co) const
return glbal corner number i
const MathVector< worldDim > & global_grad (size_t ip, size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector (size_t ip) const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip (size_t ip) const
global integration point of scvf
const MathMatrix< worldDim, dim > & JTInv (size_t ip) const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t ip, size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector (size_t ip) const
vector of local gradients in ip point
const MathVector< dim > & local_ip (size_t ip) const
local integration point of scvf
size_t node_id () const
index of SubControlVolume of the bf
const MathVector< worldDim > & normal () const
outer normal on bf. Norm is equal to area
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points on scvf
size_t num_sh () const
number of shape functions
number shape (size_t ip, size_t sh) const
value of shape function i in integration point
const number * shape_vector (size_t ip) const
vector of shape functions in ip point
number volume () const
volume of bf
number weight (size_t ip) const
integration weight
Static Public Attributes
static const size_t nip = scvf_quad_rule_type::nip
number of integration points
static const size_t numCo = traits::NumCornersOfSCVF
Number of corners of bf.
Private Attributes
size_t nodeId
MathVector< worldDim > Normal
number vDetJ [nip]
MathVector< worldDim > vGlobalIP [nip]
MathVector< worldDim > vGloPos [numCo]
MathMatrix< worldDim, dim > vJtInv [nip]
MathVector< dim > vLocalIP [nip]
MathVector< dim > vLocPos [numCo]
MidID vMidID [numCo]
number Vol
MathVector< worldDim > vvGlobalGrad [nip][nsh]
MathVector< dim > vvLocalGrad [nip][nsh]
number vvShape [nip][nsh]
const number * vWeight
Friends
class FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >
let outer class access private members
Detailed Description
template<int TOrder, typename TElem, int TWorldDim, int TQuadOrder = TOrder + 1>
class ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF
boundary face
Constructor & Destructor Documentation
BF()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::BF () inline
Member Function Documentation
detJ()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::detJ (size_t ip) const inline
Determinant of Jacobian in integration point.
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vDetJ.
global_corner()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_corner (size_t co) const inline
return glbal corner number i
global_grad()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad (size_t ip, size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_sh(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvGlobalGrad.
global_grad_vector()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad_vector (size_t ip) const inline
vector of global gradients in ip point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvGlobalGrad.
global_ip()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_ip (size_t ip) const inline
global integration point of scvf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vGlobalIP.
JTInv()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathMatrix<worldDim,dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::JTInv (size_t ip) const inline
Transposed Inverse of Jacobian in integration point.
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vJtInv.
local_corner()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_corner (size_t co) const inline
return local corner number i
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_corners(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vLocPos.
local_grad()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad (size_t ip, size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_sh(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvLocalGrad.
local_grad_vector()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad_vector (size_t ip) const inline
vector of local gradients in ip point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvLocalGrad.
local_ip()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_ip (size_t ip) const inline
local integration point of scvf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vLocalIP.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
node_id()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::node_id () const inline
index of SubControlVolume of the bf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::nodeId.
normal()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::normal () const inline
outer normal on bf. Norm is equal to area
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::Normal.
num_corners()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_corners () const inline
number of corners, that bound the scvf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::numCo.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_corner(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
num_ip()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip () const inline
number of integration points on scvf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::nip.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::detJ(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::JTInv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::shape(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::shape_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::weight().
num_sh()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_sh () const inline
number of shape functions
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::nsh.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
shape()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::shape (size_t ip, size_t sh) const inline
value of shape function i in integration point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvShape.
shape_vector()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const number* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::shape_vector (size_t ip) const inline
vector of shape functions in ip point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvShape.
volume()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::volume () const inline
volume of bf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::Vol.
weight()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::weight (size_t ip) const inline
integration weight
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vWeight.
Friends And Related Function Documentation
FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> friend class FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder > friend
let outer class access private members
Member Data Documentation
nip
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::nip = scvf_quad_rule_type::nip static
number of integration points
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip().
nodeId
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::nodeId private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::node_id(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
Normal
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::Normal private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::normal(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
numCo
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::numCo = traits::NumCornersOfSCVF static
Number of corners of bf.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_corners().
vDetJ
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vDetJ[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::detJ(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
vGlobalIP
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vGlobalIP[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_ip(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
vGloPos
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vGloPos[numCo] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
vJtInv
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathMatrix<worldDim,dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vJtInv[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::JTInv(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
vLocalIP
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vLocalIP[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_ip(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
vLocPos
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vLocPos[numCo] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_corner(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
vMidID
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MidID ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vMidID[numCo] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
Vol
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::Vol private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::volume().
vvGlobalGrad
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvGlobalGrad[nip][nsh] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad_vector(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
vvLocalGrad
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvLocalGrad[nip][nsh] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad_vector(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
vvShape
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvShape[nip][nsh] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::shape(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::shape_vector(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
vWeight
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const number* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vWeight private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::weight().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fvho_geom.h