ug4: ug::DenseVector< TStorage > Class Template Reference
ug::DenseVector< TStorage > Class Template Reference
lib_algebra » Small Algebra
#include <densevector.h>
Public Types
enum { is_static = storage_traits1<TStorage>::is_static }
enum { static_size = storage_traits1<TStorage>::static_size }
typedef TStorage base
typedef TStorage::size_type size_type
typedef DenseVector< TStorage > this_type
typedef TStorage::value_type value_type
Public Member Functions
template<typename Type >
DenseVector< TStorage > & assign (const Type &t)
DenseVector (const DenseVector< TStorage > &rhs)
DenseVector (double alpha=0.0)
value_type & entry (size_t i)
const value_type & entry (size_t i) const
void maple_print (const char *name)
size_t num_cols () const
size_t num_rows () const
bool operator!= (double d) const
value_type & operator() (size_t r, size_t c)
const value_type & operator() (size_t r, size_t c) const
this_type operator* (double alpha) const
template<typename T >
this_type & operator*= (const T &alpha)
template<typename T >
DenseVector< TStorage > & operator*= (const T &alpha)
this_type operator+ (const this_type &other) const
this_type & operator+= (const this_type &rhs)
this_type & operator+= (const value_type &alpha)
this_type operator- () const
this_type operator- (const this_type &other) const
this_type & operator-= (const this_type &rhs)
this_type & operator-= (const value_type &alpha)
this_type & operator/= (const value_type &alpha)
bool operator< (double d) const
bool operator<= (double d) const
template<typename T >
this_type & operator= (const double &alpha)
template<typename T >
this_type & operator= (const T &alpha)
template<typename T >
DenseVector< TStorage > & operator= (const T &alpha)
this_type & operator= (const this_type &rhs)
bool operator== (double d) const
bool operator> (double d) const
bool operator>= (double d) const
template<typename T2 >
void subassign (size_t i, const T2 &t)
void subassign (size_t i, const value_type &t)
Detailed Description
template<typename TStorage>
class ug::DenseVector< TStorage >
DenseVector is a one-dimensional mathematical vector of objects TStorage::value_type. Use DenseVector with FixedArray1, VariableArray1 or stl::vector. Depending on TStorage, DenseVector is of fixed size or variable size, and inheritates the interface or TStorage.
Parameters
TStorage storage policy with interface of VariableArray1.
See also
FixedArray1, VariableArray1
Member Typedef Documentation
base
template<typename TStorage > typedef TStorage ug::DenseVector< TStorage >::base
size_type
template<typename TStorage > typedef TStorage::size_type ug::DenseVector< TStorage >::size_type
this_type
template<typename TStorage > typedef DenseVector<TStorage> ug::DenseVector< TStorage >::this_type
value_type
template<typename TStorage > typedef TStorage::value_type ug::DenseVector< TStorage >::value_type
Member Enumeration Documentation
anonymous enum
template<typename TStorage > anonymous enum
Enumerator
is_static
anonymous enum
template<typename TStorage > anonymous enum
Enumerator
static_size
Constructor & Destructor Documentation
DenseVector() [1/2]
template<typename TStorage > ug::DenseVector< TStorage >::DenseVector (double alpha = 0.0)
References alpha.
DenseVector() [2/2]
template<typename TStorage > ug::DenseVector< TStorage >::DenseVector (const DenseVector< TStorage > & rhs)
Member Function Documentation
assign()
template<typename TStorage > template<typename Type > DenseVector< TStorage > & ug::DenseVector< TStorage >::assign (const Type & t)
References ug::VectorAssign().
entry() [1/2]
template<typename TStorage > value_type& ug::DenseVector< TStorage >::entry (size_t i) inline
entry() [2/2]
template<typename TStorage > const value_type& ug::DenseVector< TStorage >::entry (size_t i) const inline
Referenced by ug::DenseVector< TStorage >::operator!=(), ug::DenseVector< TStorage >::operator()(), ug::DenseVector< TStorage >::operator*(), ug::DenseVector< TStorage >::operator+(), ug::DenseVector< TStorage >::operator-(), ug::DenseVector< TStorage >::operator<(), ug::DenseVector< TStorage >::operator<=(), ug::DenseVector< TStorage >::operator=(), ug::DenseVector< TStorage >::operator==(), ug::DenseVector< TStorage >::operator>(), ug::DenseVector< TStorage >::operator>=(), and ug::DenseVector< TStorage >::subassign().
maple_print()
template<typename TStorage > void ug::DenseVector< TStorage >::maple_print (const char * name)
References name, and UG_LOG.
Referenced by ug::SolveDeficit().
num_cols()
template<typename TStorage > size_t ug::DenseVector< TStorage >::num_cols () const inline
num_rows()
template<typename TStorage > size_t ug::DenseVector< TStorage >::num_rows () const inline
operator!=()
template<typename TStorage > bool ug::DenseVector< TStorage >::operator!= (double d) const inline
References ug::DenseVector< TStorage >::entry().
operator()() [1/2]
template<typename TStorage > value_type& ug::DenseVector< TStorage >::operator() (size_t r, size_t c) inline
References ug::DenseVector< TStorage >::entry(), and UG_ASSERT.
operator()() [2/2]
template<typename TStorage > const value_type& ug::DenseVector< TStorage >::operator() (size_t r, size_t c) const inline
References ug::DenseVector< TStorage >::entry(), and UG_ASSERT.
operator*()
template<typename TStorage > this_type ug::DenseVector< TStorage >::operator* (double alpha) const inline
References alpha, and ug::DenseVector< TStorage >::entry().
operator*=() [1/2]
template<typename TStorage > template<typename T > this_type& ug::DenseVector< TStorage >::operator*= (const T & alpha) inline
operator*=() [2/2]
template<typename TStorage > template<typename T > DenseVector<TStorage>& ug::DenseVector< TStorage >::operator*= (const T & alpha)
operator+()
template<typename TStorage > this_type ug::DenseVector< TStorage >::operator+ (const this_type & other) const inline
References ug::DenseVector< TStorage >::entry(), and UG_ASSERT.
operator+=() [1/2]
template<typename TStorage > DenseVector< TStorage > & ug::DenseVector< TStorage >::operator+= (const this_type & rhs) inline
operator+=() [2/2]
template<typename TStorage > this_type& ug::DenseVector< TStorage >::operator+= (const value_type & alpha) inline
operator-() [1/2]
template<typename TStorage > this_type ug::DenseVector< TStorage >::operator- () const inline
operator-() [2/2]
template<typename TStorage > this_type ug::DenseVector< TStorage >::operator- (const this_type & other) const inline
References ug::DenseVector< TStorage >::entry(), and UG_ASSERT.
operator-=() [1/2]
template<typename TStorage > DenseVector< TStorage > & ug::DenseVector< TStorage >::operator-= (const this_type & rhs) inline
operator-=() [2/2]
template<typename TStorage > this_type& ug::DenseVector< TStorage >::operator-= (const value_type & alpha) inline
operator/=()
template<typename TStorage > DenseVector< TStorage > & ug::DenseVector< TStorage >::operator/= (const value_type & alpha) inline
References alpha.
operator<()
template<typename TStorage > bool ug::DenseVector< TStorage >::operator< (double d) const inline
References ug::DenseVector< TStorage >::entry().
operator<=()
template<typename TStorage > bool ug::DenseVector< TStorage >::operator<= (double d) const inline
References ug::DenseVector< TStorage >::entry().
operator=() [1/4]
template<typename TStorage > template<typename T > this_type& ug::DenseVector< TStorage >::operator= (const double & alpha) inline
References alpha, and ug::DenseVector< TStorage >::entry().
operator=() [2/4]
template<typename TStorage > template<typename T > this_type& ug::DenseVector< TStorage >::operator= (const T & alpha) inline
operator=() [3/4]
template<typename TStorage > template<typename T > DenseVector<TStorage>& ug::DenseVector< TStorage >::operator= (const T & alpha)
References alpha.
operator=() [4/4]
template<typename TStorage > DenseVector< TStorage > & ug::DenseVector< TStorage >::operator= (const this_type & rhs) inline
References resize().
operator==()
template<typename TStorage > bool ug::DenseVector< TStorage >::operator== (double d) const inline
References ug::DenseVector< TStorage >::entry().
operator>()
template<typename TStorage > bool ug::DenseVector< TStorage >::operator> (double d) const inline
References ug::DenseVector< TStorage >::entry().
operator>=()
template<typename TStorage > bool ug::DenseVector< TStorage >::operator>= (double d) const inline
References ug::DenseVector< TStorage >::entry().
subassign() [1/2]
template<typename TStorage > template<typename T2 > void ug::DenseVector< TStorage >::subassign (size_t i, const T2 & t) inline
References ug::DenseVector< TStorage >::entry(), and UG_ASSERT.
subassign() [2/2]
template<typename TStorage > void ug::DenseVector< TStorage >::subassign (size_t i, const value_type & t) inline
References ug::DenseVector< TStorage >::entry().
Referenced by ug::LocalIndexSubspace< TDomain, TAlgebra, TObject >::extract_rhs(), and ug::LocalDoFSubspace< TDomain, TAlgebra, TObject >::extract_rhs().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/small_algebra/small_matrix/densevector.h
ugbase/lib_algebra/small_algebra/small_matrix/densevector_impl.h