ug4: ug::GlobalGridFunctionGradientData< TGridFunction > Class Template Reference
ug::GlobalGridFunctionGradientData< TGridFunction > Class Template Reference
#include <grid_function_global_user_data.h>
Public Types
typedef TGridFunction::element_type element_t
Public Types inherited from ug::CplUserData< TData, dim, void >
typedef ICplUserData< dim > base_type
type of base class
Public Types inherited from ug::UserData< TData, dim, void >
typedef TData data_type
typedef void return_type
Public Member Functions
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
bool evaluate (MathVector< dim > &value, const MathVector< dim > &x) const
evaluates the data at a given point, returns false if point not found
void evaluate (MathVector< dim > &value, const MathVector< dim > &x, number time, int si) const
to full-fill UserData-Interface
void evaluate_global (MathVector< dim > &value, const MathVector< dim > &x) const
evaluate value on all procs
std::vector< number > evaluate_global (std::vector< number > vPos)
GlobalGridFunctionGradientData (SmartPtr< TGridFunction > spGridFct, const char *cmp)
constructor
virtual ~GlobalGridFunctionGradientData ()
Public Member Functions inherited from ug::StdGlobPosData< GlobalGridFunctionGradientData< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
implement as a UserData
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
implement as a UserData
virtual bool constant () const
returns if data is constant
void evaluate (MathVector< TGridFunction::dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
virtual void operator() (MathVector< TGridFunction::dim > &value, const MathVector< dim > &globIP, number time, int si) const
returns value for a global position
virtual void operator() (MathVector< TGridFunction::dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
returns value for global positions
virtual bool requires_grid_fct () const
returns if grid function is needed for evaluation
Public Member Functions inherited from ug::StdUserData< TImpl, TData, dim, TRet, TBase >
virtual TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const =0
returns value for a global position
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const =0
returns value for global positions
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
Public Member Functions inherited from ug::CplUserData< TData, dim, void >
bool defined (size_t s, size_t ip) const
returns flag, if data is evaluated (for conditional data)
size_t num_ip (size_t s) const
returns the number of integration points
size_t num_series () const
explicitly forward some functions
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
register external callback, invoked when data storage changed
void unregister_storage_callback (DataImport< TData, dim > *obj)
register all callbacks registered by class
TData & value (size_t s, size_t ip)
returns the value at ip
const TData & value (size_t s, size_t ip) const
returns the value at ip
TData * values (size_t s)
returns all values for a series
const TData * values (size_t s) const
returns all values for a series
~CplUserData ()
destructor
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
returns true iff the time point specification is equal to the current one, or not specified
virtual void check_setup () const
returns if the dependent data is ready for evaluation
void clear ()
clear all data
int dim_local_ips () const
returns current local ip dimension
ICplUserData ()
default constructor
const MathVector< dim > & ip (size_t s, size_t ip) const
returns global ip
const MathVector< dim > * ips (size_t s) const
returns global ips
template<int ldim>
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
returns local ip
template<int ldim>
const MathVector< ldim > * local_ips (size_t s) const
returns local ips
virtual SmartPtr< ICplUserData > needed_data (size_t i)
return needed data
size_t num_ip (size_t s) const
returns the number of integration points
virtual size_t num_needed_data () const
number of other Data this data depends on
size_t num_series () const
returns the number of ip series
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
set local positions without the specification of the time point, returns series id
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
set local positions, returns series id
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
set global positions
template<int ldim>
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
sets new local ip positions for a local ip series
void set_subset (int si)
set the subset of evaluation
void set_time_point (const size_t seriesId, const int timePointSpec)
sets a new time point for a local ip series
void set_time_point (size_t timePoint)
sets the current time point
void set_times (const std::vector< number > &vTime)
set evaluation time
int subset () const
returns the subset of evaluation
number time () const
get the current evaluation time
number time (size_t s) const
get the specified evaluation time
size_t time_point ()
returns the current time point
size_t time_point (size_t s) const
returns the time point specification (in particular, the current one, if the own one not specified)
int time_point_specification (size_t s) const
returns the time point specification (note: it may be -1, i.e. not specified)
virtual void update_dof_sizes (const LocalIndices &ind)
resize arrays
virtual bool zero_derivative () const
returns if data depends on solution
virtual ~ICplUserData ()
virtual desctructor
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
Function Group of functions.
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
sets the function pattern for a possibly needed grid function
virtual ~UserDataInfo ()
virtual destructor
Public Member Functions inherited from ug::UserData< TData, dim, void >
int get_dim () const
returns dimension
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, Vertex *vrt) const
returns a value at a vertex
std::string type () const
returns type of data as string (e.g. "Number", "Vector", "Matrix")
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
Static Public Attributes
static const int dim = TGridFunction::dim
world dimension of grid function
Private Types
typedef lg_ntree< dim, dim, element_t > tree_t
Private Attributes
size_t m_fct
component of function
LFEID m_lfeID
local finite element id
SmartPtr< TGridFunction > m_spGridFct
grid function
tree_t m_tree
Additional Inherited Members
Protected Member Functions inherited from ug::StdGlobPosData< GlobalGridFunctionGradientData< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >
GlobalGridFunctionGradientData< TGridFunction > & getImpl ()
access to implementation
const GlobalGridFunctionGradientData< TGridFunction > & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::StdUserData< TImpl, TData, dim, TRet, TBase >
TImpl & getImpl ()
access to implementation
const TImpl & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::CplUserData< TData, dim, void >
void call_storage_callback () const
calls are registered external storage callbacks
void check_series (size_t s) const
checks in debug mode the correct index
void check_series_ip (size_t s, size_t ip) const
checks in debug mode the correct index
virtual void local_ip_series_added (const size_t seriesID)
resizes the data field, when local ip changed signaled
virtual void local_ip_series_to_be_cleared ()
free the data field memory and set series to zero
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
implement callback, called when local IPs changed
virtual void value_storage_changed (const size_t seriesID)
callback, invoked when storage of data has changed for a series
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
checks in debug mode the correct usage of indices
void check_s_ip (size_t s, size_t ip) const
checks in debug mode the correct usage of indices
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
help function to get local ips
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
callback invoked after global ips have been changed
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
default time point (or -1 if not specified)
int m_locPosDim
dimension of local position (-1 indicates no dim set)
std::vector< const MathVector< 1 > * > m_pvLocIP1d
local ips of dimension 1d-3d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
subset for evaluation
size_t m_timePoint
current time point (used if no explicit specification for series)
std::vector< bool > m_vMayChange
flags if local ips may change
std::vector< size_t > m_vNumIP
number of evaluation points (-1 indicates no ips set)
std::vector< number > m_vTime
time for evaluation
std::vector< int > m_vTimePoint
time points for the series
std::vector< const MathVector< dim > * > m_vvGlobPos
global ips
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Member Typedef Documentation
element_t
template<typename TGridFunction > typedef TGridFunction::element_type ug::GlobalGridFunctionGradientData< TGridFunction >::element_t
tree_t
template<typename TGridFunction > typedef lg_ntree<dim, dim, element_t> ug::GlobalGridFunctionGradientData< TGridFunction >::tree_t private
Constructor & Destructor Documentation
GlobalGridFunctionGradientData()
template<typename TGridFunction > ug::GlobalGridFunctionGradientData< TGridFunction >::GlobalGridFunctionGradientData (SmartPtr< TGridFunction > spGridFct, const char * cmp) inline
constructor
References ug::SubsetGroup::add_all(), ug::lg_ntree< tree_dim, world_dim, grid_elem_t >::create_tree(), ug::GlobalGridFunctionGradientData< TGridFunction >::m_fct, ug::GlobalGridFunctionGradientData< TGridFunction >::m_lfeID, ug::GlobalGridFunctionGradientData< TGridFunction >::m_spGridFct, ug::GlobalGridFunctionGradientData< TGridFunction >::m_tree, ug::SubsetGroup::size(), and UG_THROW.
~GlobalGridFunctionGradientData()
template<typename TGridFunction > virtual ug::GlobalGridFunctionGradientData< TGridFunction >::~GlobalGridFunctionGradientData () inline virtual
Member Function Documentation
continuous()
template<typename TGridFunction > virtual bool ug::GlobalGridFunctionGradientData< TGridFunction >::continuous () const inline virtual
returns if provided data is continuous over geometric object boundaries
Reimplemented from ug::StdGlobPosData< GlobalGridFunctionGradientData< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >.
evaluate() [1/2]
template<typename TGridFunction > bool ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate (MathVector< dim > & value, const MathVector< dim > & x) const inline
evaluates the data at a given point, returns false if point not found
References ug::CollectCornerCoordinates(), ug::GlobalGridFunctionGradientData< TGridFunction >::dim, ug::DoFRef(), ug::ElementDebugInfo(), ug::FindContainingElement(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::DimReferenceMapping< TDim, TWorldDim >::jacobian_transposed(), ug::GlobalGridFunctionGradientData< TGridFunction >::m_fct, ug::GlobalGridFunctionGradientData< TGridFunction >::m_lfeID, ug::GlobalGridFunctionGradientData< TGridFunction >::m_spGridFct, ug::GlobalGridFunctionGradientData< TGridFunction >::m_tree, ug::UserDataInfo::map(), ug::MatVecMult(), ug::RightInverse(), UG_CATCH_THROW, ug::CplUserData< TData, dim, void >::value(), ug::VecScaleAppend(), and ug::VecSet().
evaluate() [2/2]
template<typename TGridFunction > void ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate (MathVector< dim > & value, const MathVector< dim > & x, number time, int si) const inline
to full-fill UserData-Interface
References ug::GlobalGridFunctionGradientData< TGridFunction >::m_fct, UG_THROW, and ug::CplUserData< TData, dim, void >::value().
Referenced by ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate_global().
evaluate_global() [1/2]
template<typename TGridFunction > void ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate_global (MathVector< dim > & value, const MathVector< dim > & x) const inline
evaluate value on all procs
References ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate(), and UG_THROW.
Referenced by ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate_global().
evaluate_global() [2/2]
template<typename TGridFunction > std::vector<number> ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate_global (std::vector< number > vPos) inline
References ug::GlobalGridFunctionGradientData< TGridFunction >::dim, ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate_global(), UG_THROW, and ug::CplUserData< TData, dim, void >::value().
Member Data Documentation
dim
template<typename TGridFunction > const int ug::GlobalGridFunctionGradientData< TGridFunction >::dim = TGridFunction::dim static
world dimension of grid function
Referenced by ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate(), and ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate_global().
m_fct
template<typename TGridFunction > size_t ug::GlobalGridFunctionGradientData< TGridFunction >::m_fct private
component of function
Referenced by ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate(), and ug::GlobalGridFunctionGradientData< TGridFunction >::GlobalGridFunctionGradientData().
m_lfeID
template<typename TGridFunction > LFEID ug::GlobalGridFunctionGradientData< TGridFunction >::m_lfeID private
local finite element id
Referenced by ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate(), and ug::GlobalGridFunctionGradientData< TGridFunction >::GlobalGridFunctionGradientData().
m_spGridFct
template<typename TGridFunction > SmartPtr<TGridFunction> ug::GlobalGridFunctionGradientData< TGridFunction >::m_spGridFct private
grid function
Referenced by ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate(), and ug::GlobalGridFunctionGradientData< TGridFunction >::GlobalGridFunctionGradientData().
m_tree
template<typename TGridFunction > tree_t ug::GlobalGridFunctionGradientData< TGridFunction >::m_tree private
Referenced by ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate(), and ug::GlobalGridFunctionGradientData< TGridFunction >::GlobalGridFunctionGradientData().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/grid_function_global_user_data.h