ug4: ug::LocalIndices Class Reference
ug::LocalIndices Class Reference
#include <local_algebra.h>
Public Types
typedef index_type comp_type
Component type used by algebra.
typedef size_t index_type
Index type used by algebra.
Public Member Functions
void clear ()
clears all fct
void clear_dof (size_t fct)
clears the dofs of a function
comp_type & comp (size_t fct, size_t dof)
algebra comp for (fct, dof)
comp_type comp (size_t fct, size_t dof) const
algebra comp for (fct, dof)
bool contains_index (index_type ind)
checks if the local index object references a given index
index_type & index (size_t fct, size_t dof)
global algebra index for (fct, dof)
index_type index (size_t fct, size_t dof) const
global algebra index for (fct, dof)
const LFEID & local_finite_element_id (size_t fct) const
returns the local finite element id of a function
LocalIndices ()
Default Constructor.
const DoFIndex & multi_index (size_t fct, size_t dof) const
global algebra multi-index for (fct, dof)
size_t num_dof () const
number of dofs of all accessible (sum)
size_t num_dof (size_t fct) const
number of dofs for accessible function
size_t num_fct () const
number of functions
void push_back_index (size_t fct, size_t index)
adds an index (increases size)
void push_back_multi_index (size_t fct, size_t index, size_t comp)
adds an index (increases size)
void reserve_dof (size_t fct, size_t numDoF)
reserves memory for the number of dofs
void resize_dof (size_t fct, size_t numDoF)
sets the number of dofs of a function
void resize_fct (size_t numFct)
sets the number of functions
void set_lfeID (size_t fct, const LFEID &lfeID)
sets the local finite element id for a function
Protected Member Functions
void check_dof (size_t fct, size_t dof) const
checks correct dof index in debug mode
void check_fct (size_t fct) const
checks correct fct index in debug mode
Protected Attributes
std::vector< LFEID > m_vLFEID
std::vector< std::vector< DoFIndex > > m_vvIndex
Member Typedef Documentation
comp_type
typedef index_type ug::LocalIndices::comp_type
Component type used by algebra.
index_type
typedef size_t ug::LocalIndices::index_type
Index type used by algebra.
Constructor & Destructor Documentation
LocalIndices()
ug::LocalIndices::LocalIndices () inline
Default Constructor.
Member Function Documentation
check_dof()
void ug::LocalIndices::check_dof (size_t fct, size_t dof) const inline protected
checks correct dof index in debug mode
References check_fct(), num_dof(), and UG_LOCALALGEBRA_ASSERT.
Referenced by comp(), index(), and multi_index().
check_fct()
void ug::LocalIndices::check_fct (size_t fct) const inline protected
checks correct fct index in debug mode
References num_fct(), and UG_LOCALALGEBRA_ASSERT.
Referenced by check_dof(), num_dof(), push_back_multi_index(), reserve_dof(), and resize_dof().
clear()
void ug::LocalIndices::clear () inline
clears all fct
References m_vvIndex.
clear_dof()
void ug::LocalIndices::clear_dof (size_t fct) inline
clears the dofs of a function
References resize_dof().
Referenced by ug::DoFDistribution::_indices().
comp() [1/2]
comp_type& ug::LocalIndices::comp (size_t fct, size_t dof) inline
algebra comp for (fct, dof)
References check_dof(), and m_vvIndex.
comp() [2/2]
comp_type ug::LocalIndices::comp (size_t fct, size_t dof) const inline
algebra comp for (fct, dof)
References check_dof(), and m_vvIndex.
Referenced by ug::ActiveSet< TDomain, TAlgebra >::active_index_elem(), ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_mat_to_global(), ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_vec_to_global(), ug::AddLocalMatrixToGlobal(), ug::AddLocalVector(), ug::GetLocalVector(), and push_back_multi_index().
contains_index()
bool ug::LocalIndices::contains_index (index_type ind) inline
checks if the local index object references a given index
References m_vvIndex, num_dof(), and num_fct().
index() [1/2]
index_type& ug::LocalIndices::index (size_t fct, size_t dof) inline
global algebra index for (fct, dof)
References check_dof(), and m_vvIndex.
index() [2/2]
index_type ug::LocalIndices::index (size_t fct, size_t dof) const inline
global algebra index for (fct, dof)
References check_dof(), and m_vvIndex.
Referenced by ug::ActiveSet< TDomain, TAlgebra >::active_index_elem(), ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_mat_to_global(), ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_vec_to_global(), ug::AddLocalMatrixToGlobal(), ug::AddLocalVector(), ug::GetLocalVector(), ug::NLGaussSeidelSolver< TDomain, TAlgebra >::prepare(), push_back_index(), and push_back_multi_index().
local_finite_element_id()
const LFEID& ug::LocalIndices::local_finite_element_id (size_t fct) const inline
returns the local finite element id of a function
References m_vLFEID, and UG_ASSERT.
Referenced by ug::LocalVector::local_finite_element_id().
multi_index()
const DoFIndex& ug::LocalIndices::multi_index (size_t fct, size_t dof) const inline
global algebra multi-index for (fct, dof)
References check_dof(), and m_vvIndex.
Referenced by ug::FV1InnerBoundaryElemDisc< TImpl, TDomain >::prep_elem().
num_dof() [1/2]
size_t ug::LocalIndices::num_dof () const inline
number of dofs of all accessible (sum)
References num_fct().
Referenced by check_dof(), and contains_index().
num_dof() [2/2]
size_t ug::LocalIndices::num_dof (size_t fct) const inline
number of dofs for accessible function
References check_fct(), and m_vvIndex.
Referenced by ug::ActiveSet< TDomain, TAlgebra >::active_index_elem(), ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::calc_error(), ug::ActiveSet< TDomain, TAlgebra >::check_conv_elem(), ug::LocalVector::operator=(), ug::LocalVector::resize(), ug::LocalMatrix::resize(), and ug::DependentUserData< TData, dim >::update_dof_sizes().
num_fct()
size_t ug::LocalIndices::num_fct () const inline
number of functions
References m_vvIndex.
Referenced by ug::LocalVector::access_all(), ug::LocalMatrix::access_all(), ug::ActiveSet< TDomain, TAlgebra >::active_index_elem(), ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::calc_error(), ug::ActiveSet< TDomain, TAlgebra >::check_conv_elem(), check_fct(), contains_index(), num_dof(), ug::LocalVector::operator=(), ug::LocalVector::resize(), and ug::LocalMatrix::resize().
push_back_index()
void ug::LocalIndices::push_back_index (size_t fct, size_t index) inline
adds an index (increases size)
References index(), and push_back_multi_index().
Referenced by ug::DoFDistribution::constrained_edge_indices(), ug::DoFDistribution::constrained_face_indices(), ug::DoFDistribution::constrained_vertex_indices(), ug::DoFDistribution::indices(), and ug::DoFDistribution::indices_on_vertex().
push_back_multi_index()
void ug::LocalIndices::push_back_multi_index (size_t fct, size_t index, size_t comp) inline
adds an index (increases size)
References check_fct(), comp(), index(), and m_vvIndex.
Referenced by ug::DoFDistribution::constrained_edge_indices(), ug::DoFDistribution::constrained_face_indices(), ug::DoFDistribution::constrained_vertex_indices(), ug::DoFDistribution::indices(), ug::DoFDistribution::indices_on_vertex(), and push_back_index().
reserve_dof()
void ug::LocalIndices::reserve_dof (size_t fct, size_t numDoF) inline
reserves memory for the number of dofs
References check_fct(), and m_vvIndex.
resize_dof()
void ug::LocalIndices::resize_dof (size_t fct, size_t numDoF) inline
sets the number of dofs of a function
References check_fct(), and m_vvIndex.
Referenced by clear_dof().
resize_fct()
void ug::LocalIndices::resize_fct (size_t numFct) inline
sets the number of functions
References m_vLFEID, and m_vvIndex.
Referenced by ug::DoFDistribution::_indices().
set_lfeID()
void ug::LocalIndices::set_lfeID (size_t fct, const LFEID & lfeID) inline
sets the local finite element id for a function
References m_vLFEID, and UG_ASSERT.
Member Data Documentation
m_vLFEID
std::vector<LFEID> ug::LocalIndices::m_vLFEID protected
Referenced by local_finite_element_id(), resize_fct(), and set_lfeID().
m_vvIndex
std::vector<std::vector<DoFIndex> > ug::LocalIndices::m_vvIndex protected
Referenced by clear(), comp(), contains_index(), index(), multi_index(), num_dof(), num_fct(), push_back_multi_index(), reserve_dof(), resize_dof(), and resize_fct().
The documentation for this class was generated from the following file:
ugbase/lib_disc/common/local_algebra.h