ug4: ug::ElementGaussSeidel< TDomain, TAlgebra > Class Template Reference
ug::ElementGaussSeidel< TDomain, TAlgebra > Class Template Reference
ElementGaussSeidel Preconditioner.
#include <element_gauss_seidel.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef IPreconditioner< TAlgebra > base_type
Base type.
typedef IPreconditioner< TAlgebra >::matrix_operator_type matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual SmartPtr< ILinearIterator< vector_type > > clone ()
Clone.
ElementGaussSeidel ()
default constructor
ElementGaussSeidel (number relax)
constructor setting relaxation
ElementGaussSeidel (const std::string &type)
constructor setting type
ElementGaussSeidel (number relax, const std::string &type)
constructor setting relaxation and type
void set_relax (number omega)
set relaxation parameter
void set_type (const std::string &type)
set type
virtual bool supports_parallel () const
returns if parallel solving is supported
virtual ~ElementGaussSeidel ()
Destructor.
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
virtual std::string config_string () const
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
void set_damp (number factor)
sets the damping to a constant factor
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
DebugWritingObject ()
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
virtual const char * name () const
Name of preconditioner.
virtual bool postprocess ()
Postprocess routine.
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
Preprocess routine.
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
computes a new correction c = B*d
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
virtual void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void write_debug (const vector_type &vec, std::string filename)
virtual void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
Protected Attributes
matrix_type m_A
number m_relax
std::string m_type
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Detailed Description
template<typename TDomain, typename TAlgebra>
class ug::ElementGaussSeidel< TDomain, TAlgebra >
ElementGaussSeidel Preconditioner.
Member Typedef Documentation
template<typename TDomain , typename TAlgebra > typedef TAlgebra ug::ElementGaussSeidel< TDomain, TAlgebra >::algebra_type
Algebra type.
template<typename TDomain , typename TAlgebra > typedef IPreconditioner<TAlgebra> ug::ElementGaussSeidel< TDomain, TAlgebra >::base_type
Base type.
template<typename TDomain , typename TAlgebra > typedef IPreconditioner<TAlgebra>::matrix_operator_type ug::ElementGaussSeidel< TDomain, TAlgebra >::matrix_operator_type
Matrix Operator type.
template<typename TDomain , typename TAlgebra > typedef TAlgebra::matrix_type ug::ElementGaussSeidel< TDomain, TAlgebra >::matrix_type
Matrix type.
template<typename TDomain , typename TAlgebra > typedef TAlgebra::vector_type ug::ElementGaussSeidel< TDomain, TAlgebra >::vector_type
Vector type.
Constructor & Destructor Documentation
template<typename TDomain , typename TAlgebra > ug::ElementGaussSeidel< TDomain, TAlgebra >::ElementGaussSeidel () inline
default constructor
template<typename TDomain , typename TAlgebra > ug::ElementGaussSeidel< TDomain, TAlgebra >::ElementGaussSeidel (number relax) inline
constructor setting relaxation
template<typename TDomain , typename TAlgebra > ug::ElementGaussSeidel< TDomain, TAlgebra >::ElementGaussSeidel (const std::string & type) inline
constructor setting type
template<typename TDomain , typename TAlgebra > ug::ElementGaussSeidel< TDomain, TAlgebra >::ElementGaussSeidel (number relax, const std::string & type) inline
constructor setting relaxation and type
template<typename TDomain , typename TAlgebra > virtual ug::ElementGaussSeidel< TDomain, TAlgebra >::~ElementGaussSeidel () inline virtual
Destructor.
Member Function Documentation
template<typename TDomain , typename TAlgebra > virtual SmartPtr<ILinearIterator<vector_type> > ug::ElementGaussSeidel< TDomain, TAlgebra >::clone () inline virtual
Clone.
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References ug::ILinearIterator< TAlgebra::vector_type >::damping(), ug::DebugWritingObject< TAlgebra >::debug_writer(), ug::ElementGaussSeidel< TDomain, TAlgebra >::m_relax, and ug::ElementGaussSeidel< TDomain, TAlgebra >::m_type.
template<typename TDomain , typename TAlgebra > virtual const char* ug::ElementGaussSeidel< TDomain, TAlgebra >::name () const inline protected virtual
Name of preconditioner.
Implements ug::IPreconditioner< TAlgebra >.
template<typename TDomain , typename TAlgebra > virtual bool ug::ElementGaussSeidel< TDomain, TAlgebra >::postprocess () inline protected virtual
Postprocess routine.
Implements ug::IPreconditioner< TAlgebra >.
template<typename TDomain , typename TAlgebra > virtual bool ug::ElementGaussSeidel< TDomain, TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) inline protected virtual
Preprocess routine.
Implements ug::IPreconditioner< TAlgebra >.
References ug::ElementGaussSeidel< TDomain, TAlgebra >::m_A, ug::MakeConsistent(), and pcl::NumProcs().
template<typename TDomain , typename TAlgebra > void ug::ElementGaussSeidel< TDomain, TAlgebra >::set_relax (number omega) inline
set relaxation parameter
References ug::ElementGaussSeidel< TDomain, TAlgebra >::m_relax, and omega.
template<typename TDomain , typename TAlgebra > void ug::ElementGaussSeidel< TDomain, TAlgebra >::set_type (const std::string & type) inline
set type
References ug::ElementGaussSeidel< TDomain, TAlgebra >::m_type.
template<typename TDomain , typename TAlgebra > virtual bool ug::ElementGaussSeidel< TDomain, TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) inline protected virtual
computes a new correction c = B*d
This method computes a new correction c = B*d. It can only be called, when the preprocess has been done.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
[out] c correction
[in] d defect
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::ElementGaussSeidel< TDomain, TAlgebra >::m_A, ug::ElementGaussSeidel< TDomain, TAlgebra >::m_relax, ug::ElementGaussSeidel< TDomain, TAlgebra >::m_type, pcl::NumProcs(), ug::PST_CONSISTENT, ug::PST_UNIQUE, and UG_THROW.
template<typename TDomain , typename TAlgebra > virtual bool ug::ElementGaussSeidel< TDomain, TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearIterator< TAlgebra::vector_type >.
Member Data Documentation
template<typename TDomain , typename TAlgebra > matrix_type ug::ElementGaussSeidel< TDomain, TAlgebra >::m_A protected
Referenced by ug::ElementGaussSeidel< TDomain, TAlgebra >::preprocess(), and ug::ElementGaussSeidel< TDomain, TAlgebra >::step().
template<typename TDomain , typename TAlgebra > number ug::ElementGaussSeidel< TDomain, TAlgebra >::m_relax protected
Referenced by ug::ElementGaussSeidel< TDomain, TAlgebra >::clone(), ug::ElementGaussSeidel< TDomain, TAlgebra >::set_relax(), and ug::ElementGaussSeidel< TDomain, TAlgebra >::step().
template<typename TDomain , typename TAlgebra > std::string ug::ElementGaussSeidel< TDomain, TAlgebra >::m_type protected
Referenced by ug::ElementGaussSeidel< TDomain, TAlgebra >::clone(), ug::ElementGaussSeidel< TDomain, TAlgebra >::set_type(), and ug::ElementGaussSeidel< TDomain, TAlgebra >::step().
The documentation for this class was generated from the following file:
ugbase/lib_disc/operator/linear_operator/element_gauss_seidel/element_gauss_seidel.h