ug4: ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF Class Reference
ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF Class Reference
Sub-Control Volume Face structure.
#include <fvho_geom.h>
Public Member Functions
number detJ (size_t ip) const
Determinant of Jacobian in integration point.
size_t from () const
index of SubControlVolume on one side of the scvf
const MathVector< worldDim > & global_corner (size_t co) const
return global corner number i
const MathVector< worldDim > & global_grad (size_t ip, size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector (size_t ip) const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip (size_t ip) const
global integration point of scvf
const MathMatrix< worldDim, dim > & JTInv (size_t ip) const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t ip, size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector (size_t ip) const
vector of local gradients in ip point
const MathVector< dim > & local_ip (size_t ip) const
local integration point of scvf
const MathVector< worldDim > & normal () const
normal on scvf (points direction "from"->"to"), normalized
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points on scvf
size_t num_sh () const
number of shape functions
SCVF ()
number shape (size_t ip, size_t sh) const
value of shape function i in integration point
const number * shape_vector (size_t ip) const
vector of shape functions in ip point
size_t to () const
index of SubControlVolume on one side of the scvf
number weight (size_t ip) const
integration weight
Static Public Attributes
static const size_t nip = scvf_quad_rule_type::nip
Number of integration points.
static const size_t numCo = traits::NumCornersOfSCVF
Number of corners of scvf.
Private Attributes
size_t From
MathVector< worldDim > Normal
size_t To
number vDetJ [nip]
number vDetJMap [nip]
MathVector< worldDim > vGlobalIP [nip]
MathVector< worldDim > vGloPos [numCo]
MathMatrix< worldDim, dim > vJtInv [nip]
MathVector< dim > vLocalIP [nip]
MathVector< dim > vLocPos [numCo]
MidID vMidID [numCo]
MathVector< worldDim > vvGlobalGrad [nip][nsh]
MathVector< dim > vvLocalGrad [nip][nsh]
number vvShape [nip][nsh]
const number * vWeight
Friends
class FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >
Detailed Description
template<int TOrder, typename TElem, int TWorldDim, int TQuadOrder = TOrder + 1>
class ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF
Sub-Control Volume Face structure.
Constructor & Destructor Documentation
SCVF()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::SCVF () inline
Member Function Documentation
detJ()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::detJ (size_t ip) const inline
Determinant of Jacobian in integration point.
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vDetJ.
from()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::from () const inline
index of SubControlVolume on one side of the scvf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::From.
global_corner()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_corner (size_t co) const inline
return global corner number i
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_corners(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vGloPos.
global_grad()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_grad (size_t ip, size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_sh(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vvGlobalGrad.
global_grad_vector()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_grad_vector (size_t ip) const inline
vector of global gradients in ip point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vvGlobalGrad.
global_ip()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_ip (size_t ip) const inline
global integration point of scvf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vGlobalIP.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update().
JTInv()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathMatrix<worldDim,dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::JTInv (size_t ip) const inline
Transposed Inverse of Jacobian in integration point.
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vJtInv.
local_corner()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_corner (size_t co) const inline
return local corner number i
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_corners(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vLocPos.
local_grad()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_grad (size_t ip, size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_sh(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vvLocalGrad.
local_grad_vector()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_grad_vector (size_t ip) const inline
vector of local gradients in ip point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vvLocalGrad.
local_ip()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_ip (size_t ip) const inline
local integration point of scvf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vLocalIP.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
normal()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::normal () const inline
normal on scvf (points direction "from"->"to"), normalized
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::Normal.
num_corners()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_corners () const inline
number of corners, that bound the scvf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::numCo.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_corner(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_corner(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_corner(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_corner(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_corner(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_corner(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_corner(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_corner(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_corner(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_corner(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_corner(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_corner(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update().
num_ip()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip () const inline
number of integration points on scvf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::nip.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::detJ(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::detJ(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::detJ(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::detJ(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::detJ(), ug::DimFVGeometry< TWorldDim, TDim >::BF::detJ(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_ip(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::JTInv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::JTInv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::JTInv(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::JTInv(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::JTInv(), ug::DimFVGeometry< TWorldDim, TDim >::BF::JTInv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_ip(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::shape(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::shape(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::shape(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::shape(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::shape(), ug::DimFVGeometry< TWorldDim, TDim >::BF::shape(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::shape_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::shape_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::shape_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::shape_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::shape_vector(), ug::DimFVGeometry< TWorldDim, TDim >::BF::shape_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::weight(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::weight(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::weight(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::weight(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::weight(), and ug::DimFVGeometry< TWorldDim, TDim >::BF::weight().
num_sh()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_sh () const inline
number of shape functions
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::nsh.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad(), and ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad().
shape()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::shape (size_t ip, size_t sh) const inline
value of shape function i in integration point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vvShape.
shape_vector()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const number* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::shape_vector (size_t ip) const inline
vector of shape functions in ip point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vvShape.
to()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::to () const inline
index of SubControlVolume on one side of the scvf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::To.
weight()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::weight (size_t ip) const inline
integration weight
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), UG_ASSERT, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vDetJMap, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vWeight.
Friends And Related Function Documentation
FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> friend class FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder > friend
Member Data Documentation
From
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::From private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::from(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::from(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
nip
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::nip = scvf_quad_rule_type::nip static
Number of integration points.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), and ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip().
Normal
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::Normal private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::normal(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::normal(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::normal(), and ug::DimFVGeometry< TWorldDim, TDim >::BF::normal().
numCo
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::numCo = traits::NumCornersOfSCVF static
Number of corners of scvf.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_corners(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_corners(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_corners(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_corners(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_corners(), ug::DimFVGeometry< TWorldDim, TDim >::BF::num_corners(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
To
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::To private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::to(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::to(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
vDetJ
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vDetJ[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::detJ(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::detJ(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::detJ(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::detJ(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::detJ(), ug::DimFVGeometry< TWorldDim, TDim >::BF::detJ(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update().
vDetJMap
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vDetJMap[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::weight(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::weight(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::weight(), and ug::DimFVGeometry< TWorldDim, TDim >::SCV::weight().
vGlobalIP
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vGlobalIP[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_ip(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_ip(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update().
vGloPos
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vGloPos[numCo] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_corner(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_corner(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_corner(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_corner(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_corner(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_corner(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update().
vJtInv
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathMatrix<worldDim,dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vJtInv[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::JTInv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::JTInv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::JTInv(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::JTInv(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::JTInv(), ug::DimFVGeometry< TWorldDim, TDim >::BF::JTInv(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update().
vLocalIP
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vLocalIP[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_ip(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_ip(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
vLocPos
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vLocPos[numCo] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_corner(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_corner(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_corner(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_corner(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_corner(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_corner(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
vMidID
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MidID ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vMidID[numCo] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
vvGlobalGrad
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vvGlobalGrad[nip][nsh] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::global_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_grad_vector(), and ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad_vector().
vvLocalGrad
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vvLocalGrad[nip][nsh] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad_vector(), and ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad_vector().
vvShape
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vvShape[nip][nsh] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::shape(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::shape(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::shape(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::shape(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::shape(), ug::DimFVGeometry< TWorldDim, TDim >::BF::shape(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::shape_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::shape_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::shape_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::shape_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::shape_vector(), and ug::DimFVGeometry< TWorldDim, TDim >::BF::shape_vector().
vWeight
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const number* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vWeight private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::weight(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::weight(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::weight(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::weight(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::weight(), and ug::DimFVGeometry< TWorldDim, TDim >::BF::weight().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fvho_geom.h