ug4: ug::hash_iterator< TKey, TValue, TEntry > Class Template Reference
ug::hash_iterator< TKey, TValue, TEntry > Class Template Reference
this iterator is used by the hash class to provide access to the elements of a given key
#include <hash_iterator.h>
Public Types
typedef size_t difference_type
typedef TEntry entry_t
typedef std::forward_iterator_tag iterator_category
typedef TKey key_t
typedef TValue * pointer
typedef TValue & reference
typedef hash_iterator this_type
typedef TValue value_t
typedef TValue value_type
Public Member Functions
hash_iterator ()
hash_iterator (const key_t &key, const entry_t *entries, size_t entryInd)
bool operator!= (const this_type &iter) const
value_type & operator* ()
this_type operator++ ()
this_type operator++ (int unused)
bool operator== (const this_type &iter) const
Private Member Functions
bool equal (const this_type &other) const
void increment ()
Private Attributes
const entry_t * m_entries
size_t m_entryInd
key_t m_key
Static Private Attributes
static const size_t s_invalidIndex = -1
marks an index as invalid
Detailed Description
template<class TKey, class TValue, class TEntry>
class ug::hash_iterator< TKey, TValue, TEntry >
this iterator is used by the hash class to provide access to the elements of a given key
Member Typedef Documentation
difference_type
template<class TKey , class TValue , class TEntry > typedef size_t ug::hash_iterator< TKey, TValue, TEntry >::difference_type
entry_t
template<class TKey , class TValue , class TEntry > typedef TEntry ug::hash_iterator< TKey, TValue, TEntry >::entry_t
iterator_category
template<class TKey , class TValue , class TEntry > typedef std::forward_iterator_tag ug::hash_iterator< TKey, TValue, TEntry >::iterator_category
key_t
template<class TKey , class TValue , class TEntry > typedef TKey ug::hash_iterator< TKey, TValue, TEntry >::key_t
pointer
template<class TKey , class TValue , class TEntry > typedef TValue* ug::hash_iterator< TKey, TValue, TEntry >::pointer
reference
template<class TKey , class TValue , class TEntry > typedef TValue& ug::hash_iterator< TKey, TValue, TEntry >::reference
this_type
template<class TKey , class TValue , class TEntry > typedef hash_iterator ug::hash_iterator< TKey, TValue, TEntry >::this_type
value_t
template<class TKey , class TValue , class TEntry > typedef TValue ug::hash_iterator< TKey, TValue, TEntry >::value_t
value_type
template<class TKey , class TValue , class TEntry > typedef TValue ug::hash_iterator< TKey, TValue, TEntry >::value_type
Constructor & Destructor Documentation
hash_iterator() [1/2]
template<class TKey , class TValue , class TEntry > ug::hash_iterator< TKey, TValue, TEntry >::hash_iterator () inline
hash_iterator() [2/2]
template<class TKey , class TValue , class TEntry > ug::hash_iterator< TKey, TValue, TEntry >::hash_iterator (const key_t & key, const entry_t * entries, size_t entryInd) inline
Member Function Documentation
equal()
template<class TKey , class TValue , class TEntry > bool ug::hash_iterator< TKey, TValue, TEntry >::equal (const this_type & other) const inline private
References ug::hash_iterator< TKey, TValue, TEntry >::m_entryInd.
Referenced by ug::hash_iterator< TKey, TValue, TEntry >::operator!=(), and ug::hash_iterator< TKey, TValue, TEntry >::operator==().
increment()
template<class TKey , class TValue , class TEntry > void ug::hash_iterator< TKey, TValue, TEntry >::increment () inline private
References ug::hash_iterator< TKey, TValue, TEntry >::m_entries, ug::hash_iterator< TKey, TValue, TEntry >::m_entryInd, ug::hash_iterator< TKey, TValue, TEntry >::m_key, and ug::hash_iterator< TKey, TValue, TEntry >::s_invalidIndex.
Referenced by ug::hash_iterator< TKey, TValue, TEntry >::operator++().
operator!=()
template<class TKey , class TValue , class TEntry > bool ug::hash_iterator< TKey, TValue, TEntry >::operator!= (const this_type & iter) const inline
References ug::hash_iterator< TKey, TValue, TEntry >::equal().
operator*()
template<class TKey , class TValue , class TEntry > value_type& ug::hash_iterator< TKey, TValue, TEntry >::operator* () inline
References ug::hash_iterator< TKey, TValue, TEntry >::m_entries, ug::hash_iterator< TKey, TValue, TEntry >::m_entryInd, and ug::hash_iterator< TKey, TValue, TEntry >::s_invalidIndex.
operator++() [1/2]
template<class TKey , class TValue , class TEntry > this_type ug::hash_iterator< TKey, TValue, TEntry >::operator++ () inline
References ug::hash_iterator< TKey, TValue, TEntry >::increment().
operator++() [2/2]
template<class TKey , class TValue , class TEntry > this_type ug::hash_iterator< TKey, TValue, TEntry >::operator++ (int unused) inline
References ug::hash_iterator< TKey, TValue, TEntry >::increment().
operator==()
template<class TKey , class TValue , class TEntry > bool ug::hash_iterator< TKey, TValue, TEntry >::operator== (const this_type & iter) const inline
References ug::hash_iterator< TKey, TValue, TEntry >::equal().
Member Data Documentation
m_entries
template<class TKey , class TValue , class TEntry > const entry_t* ug::hash_iterator< TKey, TValue, TEntry >::m_entries private
Referenced by ug::hash_iterator< TKey, TValue, TEntry >::increment(), and ug::hash_iterator< TKey, TValue, TEntry >::operator*().
m_entryInd
template<class TKey , class TValue , class TEntry > size_t ug::hash_iterator< TKey, TValue, TEntry >::m_entryInd private
Referenced by ug::hash_iterator< TKey, TValue, TEntry >::equal(), ug::hash_iterator< TKey, TValue, TEntry >::increment(), and ug::hash_iterator< TKey, TValue, TEntry >::operator*().
m_key
template<class TKey , class TValue , class TEntry > key_t ug::hash_iterator< TKey, TValue, TEntry >::m_key private
Referenced by ug::hash_iterator< TKey, TValue, TEntry >::increment().
s_invalidIndex
template<class TKey , class TValue , class TEntry > const size_t ug::hash_iterator< TKey, TValue, TEntry >::s_invalidIndex = -1 static private
marks an index as invalid
Referenced by ug::hash_iterator< TKey, TValue, TEntry >::increment(), and ug::hash_iterator< TKey, TValue, TEntry >::operator*().
The documentation for this class was generated from the following file:
ugbase/common/util/hash_iterator.h