ug4: ug::node_tree::CollisionEdgesNode Class Reference
ug::node_tree::CollisionEdgesNode Class Reference
holds index pairs defining edges.
#include <collision_edges_node.h>
Public Member Functions
virtual void add_edge (int ind1, int ind2)
virtual void add_edge (int ind1, int ind2, CollisionElementID edgeID)
virtual void add_edges (int *pIndices, CollisionElementID *pEdgeIDs, int numEdges)
pIndices has to be of size numEdges*2
virtual void add_edges (int *pIndices, int numEdges)
pIndices has to be of size numEdges*2
virtual void get_edge (int index, int &ind1Out, int &ind2Out) const
virtual CollisionElementID get_edge_id (int edgeIndex)
if no identifier has been set for an edge -1 is returned.
virtual const int * get_edges () const
virtual int num_edges () const
virtual void set_edge_id (int edgeIndex, CollisionElementID edgeID)
virtual ~CollisionEdgesNode ()
Public Member Functions inherited from ug::node_tree::Node
virtual ~Node ()
Public Member Functions inherited from ug::node_tree::Object
unsigned int getObjectCode ()
virtual ~Object ()
Static Public Member Functions
static SPCollisionEdgesNode create ()
Protected Types
typedef std::vector< CollisionElementID > IDVec
typedef std::vector< int > IndexVec
Protected Member Functions
CollisionEdgesNode ()
Protected Member Functions inherited from ug::node_tree::Node
Node ()
Protected Member Functions inherited from ug::node_tree::Object
Object ()
Object (const Object &obj)
Protected Attributes
bool m_bEdgeIDsSupplied
IDVec m_vEdgeIDs
IndexVec m_vEdges
Protected Attributes inherited from ug::node_tree::Object
unsigned int m_objectCode
Detailed Description
holds index pairs defining edges.
An identifier can be stored with each edge. Normally appears as a subordinate of CollisionTreeRootNode.
Member Typedef Documentation
IDVec
typedef std::vector<CollisionElementID> ug::node_tree::CollisionEdgesNode::IDVec protected
IndexVec
typedef std::vector<int> ug::node_tree::CollisionEdgesNode::IndexVec protected
Constructor & Destructor Documentation
~CollisionEdgesNode()
ug::node_tree::CollisionEdgesNode::~CollisionEdgesNode () virtual
CollisionEdgesNode()
ug::node_tree::CollisionEdgesNode::CollisionEdgesNode () protected
References m_bEdgeIDsSupplied.
Referenced by create().
Member Function Documentation
add_edge() [1/2]
void ug::node_tree::CollisionEdgesNode::add_edge (int ind1, int ind2) virtual
References add_edge(), m_bEdgeIDsSupplied, and m_vEdges.
Referenced by add_edge().
add_edge() [2/2]
void ug::node_tree::CollisionEdgesNode::add_edge (int ind1, int ind2, CollisionElementID edgeID) virtual
References m_bEdgeIDsSupplied, m_vEdgeIDs, m_vEdges, and num_edges().
add_edges() [1/2]
void ug::node_tree::CollisionEdgesNode::add_edges (int * pIndices, CollisionElementID * pEdgeIDs, int numEdges) virtual
pIndices has to be of size numEdges*2
References m_bEdgeIDsSupplied, m_vEdgeIDs, and m_vEdges.
add_edges() [2/2]
void ug::node_tree::CollisionEdgesNode::add_edges (int * pIndices, int numEdges) virtual
pIndices has to be of size numEdges*2
References m_bEdgeIDsSupplied, m_vEdgeIDs, and m_vEdges.
create()
SPCollisionEdgesNode ug::node_tree::CollisionEdgesNode::create () static
References CollisionEdgesNode(), ug::node_tree::Object::m_objectCode, and ug::node_tree::OC_COLLISION_EDGES_NODE.
get_edge()
void ug::node_tree::CollisionEdgesNode::get_edge (int index, int & ind1Out, int & ind2Out) const virtual
References m_vEdges.
get_edge_id()
CollisionElementID ug::node_tree::CollisionEdgesNode::get_edge_id (int edgeIndex) virtual
if no identifier has been set for an edge -1 is returned.
References m_bEdgeIDsSupplied, and m_vEdgeIDs.
Referenced by ug::node_tree::Traverser_ProjectPoint::handle_collision_edges().
get_edges()
const int * ug::node_tree::CollisionEdgesNode::get_edges () const virtual
References m_vEdges.
Referenced by ug::node_tree::Traverser_ProjectPoint::handle_collision_edges().
num_edges()
int ug::node_tree::CollisionEdgesNode::num_edges () const virtual
References m_vEdges.
Referenced by add_edge(), ug::node_tree::Traverser_ProjectPoint::handle_collision_edges(), and set_edge_id().
set_edge_id()
void ug::node_tree::CollisionEdgesNode::set_edge_id (int edgeIndex, CollisionElementID edgeID) virtual
References m_bEdgeIDsSupplied, m_vEdgeIDs, and num_edges().
Member Data Documentation
m_bEdgeIDsSupplied
bool ug::node_tree::CollisionEdgesNode::m_bEdgeIDsSupplied protected
Referenced by add_edge(), add_edges(), CollisionEdgesNode(), get_edge_id(), and set_edge_id().
m_vEdgeIDs
IDVec ug::node_tree::CollisionEdgesNode::m_vEdgeIDs protected
Referenced by add_edge(), add_edges(), get_edge_id(), and set_edge_id().
m_vEdges
IndexVec ug::node_tree::CollisionEdgesNode::m_vEdges protected
Referenced by add_edge(), add_edges(), get_edge(), get_edges(), and num_edges().
The documentation for this class was generated from the following files:
ugbase/common/node_tree/collision_edges_node.h
ugbase/common/node_tree/collision_edges_node.cpp