ug4: ug::ComPol_VecSubtractOnlyOneSlave< TVector > Class Template Reference
ug::ComPol_VecSubtractOnlyOneSlave< TVector > Class Template Reference
lib_algebra » Parallel Algebra » Parallel Algebra Communication Policies
Communication Policy to subtract only one slave value per master of a vector.
#include <communication_policies.h>
Public Member Functions
void clear ()
clear processed flag
virtual bool collect (ug::BinaryBuffer &buff, const Interface &interface)
writes the interface values into a buffer that will be sent
ComPol_VecSubtractOnlyOneSlave ()
Default constructor.
ComPol_VecSubtractOnlyOneSlave (TVector *pVec)
Constructor setting the values.
virtual bool extract (ug::BinaryBuffer &buff, const Interface &interface)
subtracts values of a buffer to the interface values
virtual int get_required_buffer_size (const Interface &interface)
returns the buffer size
void set_vector (TVector *pVec)
sets the vector used in communication
Public Member Functions inherited from pcl::ICommunicationPolicy< IndexLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual ~ICommunicationPolicy ()
Private Attributes
TVector * m_pVec
std::vector< bool > m_vProcessed
Additional Inherited Members
Public Types inherited from pcl::ICommunicationPolicy< IndexLayout >
typedef Layout::Interface Interface
typedef IndexLayout Layout
Detailed Description
template<class TVector>
class ug::ComPol_VecSubtractOnlyOneSlave< TVector >
Communication Policy to subtract only one slave value per master of a vector.
This class is used as a policy to subtract values on the interfaces of a parallel vector. The collecting interfaces - supposed to consist of slave dofs - pack the values on the interface into a stream. The extracting interfaces - supposed to consist of master dofs - receive the stream and subtracts only one slave value (the first) per master.
Template Parameters
TVector Vector type
Constructor & Destructor Documentation
ComPol_VecSubtractOnlyOneSlave() [1/2]
template<class TVector > ug::ComPol_VecSubtractOnlyOneSlave< TVector >::ComPol_VecSubtractOnlyOneSlave () inline
Default constructor.
ComPol_VecSubtractOnlyOneSlave() [2/2]
template<class TVector > ug::ComPol_VecSubtractOnlyOneSlave< TVector >::ComPol_VecSubtractOnlyOneSlave (TVector * pVec) inline
Constructor setting the values.
References ug::ComPol_VecSubtractOnlyOneSlave< TVector >::set_vector().
Member Function Documentation
clear()
template<class TVector > void ug::ComPol_VecSubtractOnlyOneSlave< TVector >::clear () inline
clear processed flag
References ug::ComPol_VecSubtractOnlyOneSlave< TVector >::m_pVec, and ug::ComPol_VecSubtractOnlyOneSlave< TVector >::m_vProcessed.
collect()
template<class TVector > virtual bool ug::ComPol_VecSubtractOnlyOneSlave< TVector >::collect (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
writes the interface values into a buffer that will be sent
This function collects all entries of the vector into a buffer that are part of the interface.
Parameters
[out] buff Buffer
[in] interface Interface that will communicate
Implements pcl::ICommunicationPolicy< IndexLayout >.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::begin(), pcl::OrderedInterface< TType, TContainer, TAlloc >::end(), pcl::OrderedInterface< TType, TContainer, TAlloc >::get_element(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::m_pVec, PROFILE_BEGIN_GROUP, and ug::Serialize().
extract()
template<class TVector > virtual bool ug::ComPol_VecSubtractOnlyOneSlave< TVector >::extract (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
subtracts values of a buffer to the interface values
This function subtracts the buffer values to the vector values.
Parameters
[out] buff Buffer
[in] interface Interface that communicates
Implements pcl::ICommunicationPolicy< IndexLayout >.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::begin(), ug::Deserialize(), pcl::OrderedInterface< TType, TContainer, TAlloc >::end(), pcl::OrderedInterface< TType, TContainer, TAlloc >::get_element(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::m_pVec, ug::ComPol_VecSubtractOnlyOneSlave< TVector >::m_vProcessed, and PROFILE_BEGIN_GROUP.
get_required_buffer_size()
template<class TVector > virtual int ug::ComPol_VecSubtractOnlyOneSlave< TVector >::get_required_buffer_size (const Interface & interface) inline virtual
returns the buffer size
This function returns the size of the buffer needed for the communication of passed interface. If the vector has fixed size entries this is just the number of interface entries times the size of the entry. In case of a variable size entry type a negative value is returned to indicate that no buffer size can be determined in advanced.
Parameters
[in] interface Interface that will communicate
Reimplemented from pcl::ICommunicationPolicy< IndexLayout >.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::size().
set_vector()
template<class TVector > void ug::ComPol_VecSubtractOnlyOneSlave< TVector >::set_vector (TVector * pVec) inline
sets the vector used in communication
References ug::ComPol_VecSubtractOnlyOneSlave< TVector >::m_pVec, and ug::ComPol_VecSubtractOnlyOneSlave< TVector >::m_vProcessed.
Referenced by ug::ComPol_VecSubtractOnlyOneSlave< TVector >::ComPol_VecSubtractOnlyOneSlave().
Member Data Documentation
m_pVec
template<class TVector > TVector* ug::ComPol_VecSubtractOnlyOneSlave< TVector >::m_pVec private
Referenced by ug::ComPol_VecSubtractOnlyOneSlave< TVector >::clear(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::collect(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::extract(), and ug::ComPol_VecSubtractOnlyOneSlave< TVector >::set_vector().
m_vProcessed
template<class TVector > std::vector<bool> ug::ComPol_VecSubtractOnlyOneSlave< TVector >::m_vProcessed private
Referenced by ug::ComPol_VecSubtractOnlyOneSlave< TVector >::clear(), ug::ComPol_VecSubtractOnlyOneSlave< TVector >::extract(), and ug::ComPol_VecSubtractOnlyOneSlave< TVector >::set_vector().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/parallelization/communication_policies.h