ug4: ug::ILUTPreconditioner< TAlgebra > Class Template Reference
ug::ILUTPreconditioner< TAlgebra > Class Template Reference
#include <ilut.h>
Public Types
typedef TAlgebra algebra_type
typedef matrix_type::const_row_iterator const_matrix_row_iterator
typedef matrix_type::connection matrix_connection
typedef IPreconditioner< TAlgebra >::matrix_operator_type matrix_operator_type
Matrix Operator type.
typedef matrix_type::row_iterator matrix_row_iterator
typedef TAlgebra::matrix_type matrix_type
typedef IOrderingAlgorithm< TAlgebra, ordering_container_type > ordering_algo_type
typedef std::vector< size_t > ordering_container_type
Ordering type.
typedef TAlgebra::vector_type vector_type
typedef vector_type::value_type vector_value
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual bool applyLU (vector_type &c, const vector_type &d)
virtual SmartPtr< ILinearIterator< vector_type > > clone ()
Clone.
virtual std::string config_string () const
ILUTPreconditioner (const ILUTPreconditioner< TAlgebra > &parent)
clone constructor
ILUTPreconditioner (double eps=1e-6)
Constructor.
virtual bool multi_apply (std::vector< vector_type > &vc, const std::vector< vector_type > &vd)
virtual bool postprocess ()
cleans the operator
virtual bool preprocess_mat (matrix_type &mat)
virtual bool preprocess_mat2 (matrix_type &mat)
void set_info (bool info)
sets storage information output to true or false
void set_ordering_algorithm (SmartPtr< ordering_algo_type > ordering_algo)
sets an ordering algorithm
void set_show_progress (bool s)
set whether the progress meter should be shown
void set_sort (bool b)
set cuthill-mckee sort on/off
void set_threshold (number thresh)
sets threshold for incomplete LU factorisation (added 01122010ih)
virtual bool solve (vector_type &c, const vector_type &d)
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
computes a new correction c = B*d
virtual bool supports_parallel () const
returns if parallel solving is supported
virtual ~ILUTPreconditioner ()
Destructor.
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
returns true if the debug writer is set
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Types
typedef matrix_type::value_type block_type
Protected Member Functions
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< ILinearOperator< vector_type > > L)
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
virtual const char * name () const
returns the name of iterator
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
initializes the preconditioner
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
void enter_debug_writer_section (const char *secDir)
enters a debugging section
void enter_debug_writer_section (std::string secDir)
enters a debugging section
void leave_debug_writer_section ()
leaves a debugging section
void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
void write_debug (const matrix_type &mat, std::string name)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
vector_type c2
bool m_bSortIsIdentity
double m_eps
bool m_info
matrix_type m_L
ordering_container_type m_old_ordering
ordering_container_type m_ordering
bool m_show_progress
SmartPtr< ordering_algo_type > m_spOrderingAlgo
for ordering algorithms
matrix_type m_U
const vector_type * m_u
std::vector< size_t > newIndex
std::vector< size_t > oldIndex
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Static Protected Attributes
static const number m_small = 1e-8
Private Types
typedef IPreconditioner< TAlgebra > base_type
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::ILUTPreconditioner< TAlgebra >::algebra_type
base_type
template<typename TAlgebra > typedef IPreconditioner<TAlgebra> ug::ILUTPreconditioner< TAlgebra >::base_type private
block_type
template<typename TAlgebra > typedef matrix_type::value_type ug::ILUTPreconditioner< TAlgebra >::block_type protected
const_matrix_row_iterator
template<typename TAlgebra > typedef matrix_type::const_row_iterator ug::ILUTPreconditioner< TAlgebra >::const_matrix_row_iterator
matrix_connection
template<typename TAlgebra > typedef matrix_type::connection ug::ILUTPreconditioner< TAlgebra >::matrix_connection
matrix_operator_type
template<typename TAlgebra > typedef IPreconditioner<TAlgebra>::matrix_operator_type ug::ILUTPreconditioner< TAlgebra >::matrix_operator_type
Matrix Operator type.
matrix_row_iterator
template<typename TAlgebra > typedef matrix_type::row_iterator ug::ILUTPreconditioner< TAlgebra >::matrix_row_iterator
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::ILUTPreconditioner< TAlgebra >::matrix_type
ordering_algo_type
template<typename TAlgebra > typedef IOrderingAlgorithm<TAlgebra, ordering_container_type> ug::ILUTPreconditioner< TAlgebra >::ordering_algo_type
ordering_container_type
template<typename TAlgebra > typedef std::vector<size_t> ug::ILUTPreconditioner< TAlgebra >::ordering_container_type
Ordering type.
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::ILUTPreconditioner< TAlgebra >::vector_type
vector_value
template<typename TAlgebra > typedef vector_type::value_type ug::ILUTPreconditioner< TAlgebra >::vector_value
Constructor & Destructor Documentation
ILUTPreconditioner() [1/2]
template<typename TAlgebra > ug::ILUTPreconditioner< TAlgebra >::ILUTPreconditioner (double eps = 1e-6) inline
Constructor.
References ug::ILUTPreconditioner< TAlgebra >::m_spOrderingAlgo, and make_sp().
ILUTPreconditioner() [2/2]
template<typename TAlgebra > ug::ILUTPreconditioner< TAlgebra >::ILUTPreconditioner (const ILUTPreconditioner< TAlgebra > & parent) inline
clone constructor
References ug::ILUTPreconditioner< TAlgebra >::m_bSortIsIdentity, ug::ILUTPreconditioner< TAlgebra >::m_eps, ug::ILUTPreconditioner< TAlgebra >::m_info, and ug::ILUTPreconditioner< TAlgebra >::set_info().
~ILUTPreconditioner()
template<typename TAlgebra > virtual ug::ILUTPreconditioner< TAlgebra >::~ILUTPreconditioner () inline virtual
Destructor.
Member Function Documentation
applyLU()
template<typename TAlgebra > virtual bool ug::ILUTPreconditioner< TAlgebra >::applyLU (vector_type & c, const vector_type & d) inline virtual
References ug::BlockNorm(), ug::InverseMatMult(), ug::ILUTPreconditioner< TAlgebra >::m_eps, ug::ILUTPreconditioner< TAlgebra >::m_L, ug::ILUTPreconditioner< TAlgebra >::m_small, ug::ILUTPreconditioner< TAlgebra >::m_U, ug::MatMultAdd(), PROFILE_BEGIN_GROUP, s, UG_ASSERT, and UG_LOG.
Referenced by ug::ILUTPreconditioner< TAlgebra >::solve().
clone()
template<typename TAlgebra > virtual SmartPtr<ILinearIterator<vector_type> > ug::ILUTPreconditioner< TAlgebra >::clone () inline virtual
Clone.
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References make_sp().
config_string()
template<typename TAlgebra > virtual std::string ug::ILUTPreconditioner< TAlgebra >::config_string () const inline virtual
Reimplemented from ug::ILinearIterator< TAlgebra::vector_type >.
References ug::ILUTPreconditioner< TAlgebra >::m_eps, and ug::ILUTPreconditioner< TAlgebra >::m_spOrderingAlgo.
init() [1/3]
template<typename TAlgebra > virtual bool ug::ILUTPreconditioner< TAlgebra >::init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type & u) inline protected virtual
implements the ILinearIterator-interface for matrix based preconditioner
This method implements the ILinearIterator interface. It check if the passed linear operator is matrix based (otherwise this preconditioner can not be used for the linear operator). Then the request is forwarded to the implementation of matrix based operators.
Parameters
[in] J linear operator
[in] u linearization point
Returns
bool success flag
Reimplemented from ug::IPreconditioner< TAlgebra >.
References ug::IPreconditioner< TAlgebra >::init(), SmartPtr< T, FreePolicy >::invalid(), ug::ILUTPreconditioner< TAlgebra >::m_u, ug::ILUTPreconditioner< TAlgebra >::name(), and UG_THROW.
init() [2/3]
template<typename TAlgebra > bool ug::ILUTPreconditioner< TAlgebra >::init (SmartPtr< ILinearOperator< vector_type > > L) inline protected
References ug::IPreconditioner< TAlgebra >::init(), SmartPtr< T, FreePolicy >::invalid(), ug::ILUTPreconditioner< TAlgebra >::m_u, ug::ILUTPreconditioner< TAlgebra >::name(), and UG_THROW.
init() [3/3]
template<typename TAlgebra > bool ug::ILUTPreconditioner< TAlgebra >::init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op) inline protected
References ug::IPreconditioner< TAlgebra >::init(), and ug::ILUTPreconditioner< TAlgebra >::m_u.
multi_apply()
template<typename TAlgebra > virtual bool ug::ILUTPreconditioner< TAlgebra >::multi_apply (std::vector< vector_type > & vc, const std::vector< vector_type > & vd) inline virtual
References ug::BlockNorm(), ug::InverseMatMult(), ug::ILUTPreconditioner< TAlgebra >::m_eps, ug::ILUTPreconditioner< TAlgebra >::m_L, ug::ILUTPreconditioner< TAlgebra >::m_small, ug::ILUTPreconditioner< TAlgebra >::m_U, ug::MatMultAdd(), PROFILE_BEGIN_GROUP, s, UG_ASSERT, and UG_LOG.
name()
template<typename TAlgebra > virtual const char* ug::ILUTPreconditioner< TAlgebra >::name () const inline protected virtual
returns the name of iterator
This method returns the name of the iterator operator. This function is typically needed, when the iterator operator is used inside of another operator and some debug output should be printed
Returns
const char* name of inverse operator
Implements ug::IPreconditioner< TAlgebra >.
Referenced by ug::ILUTPreconditioner< TAlgebra >::init().
postprocess()
template<typename TAlgebra > virtual bool ug::ILUTPreconditioner< TAlgebra >::postprocess () inline virtual
cleans the operator
Implements ug::IPreconditioner< TAlgebra >.
preprocess()
template<typename TAlgebra > virtual bool ug::ILUTPreconditioner< TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) inline protected virtual
initializes the preconditioner
This method is used to initialize the preconditioner. Usually, here are performed computationally expensive operations, that should only be computed once for an underlying matrix (e.g. LU factorization), while the preconditioner will by applied (using 'step'-method) several times.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::ILUTPreconditioner< TAlgebra >::preprocess_mat().
preprocess_mat()
template<typename TAlgebra > virtual bool ug::ILUTPreconditioner< TAlgebra >::preprocess_mat (matrix_type & mat) inline virtual
References pcl::CollectUniqueElements(), ug::MatAddSlaveRowsToMasterRowOverlap0(), ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2(), ug::SetDirichletRow(), and UG_LOG_ALL_PROCS.
Referenced by ug::ILUTPreconditioner< TAlgebra >::preprocess().
preprocess_mat2()
template<typename TAlgebra > virtual bool ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2 (matrix_type & mat) inline virtual
References ug::BlockMatrixFiniteAndNotTooBig(), ug::BlockNorm(), ug::GetInversePermutation(), ug::ILUTPreconditioner< TAlgebra >::m_bSortIsIdentity, ug::ILUTPreconditioner< TAlgebra >::m_eps, ug::ILUTPreconditioner< TAlgebra >::m_info, ug::ILUTPreconditioner< TAlgebra >::m_L, ug::ILUTPreconditioner< TAlgebra >::m_old_ordering, ug::ILUTPreconditioner< TAlgebra >::m_ordering, ug::ILUTPreconditioner< TAlgebra >::m_show_progress, ug::ILUTPreconditioner< TAlgebra >::m_spOrderingAlgo, ug::ILUTPreconditioner< TAlgebra >::m_U, ug::ILUTPreconditioner< TAlgebra >::m_u, PROFILE_BEGIN_GROUP, PROGRESS_FINISH, PROGRESS_START_WITH, PROGRESS_UPDATE, ug::reset_floats(), ug::SetMatrixAsPermutation(), STATIC_ASSERT, UG_COND_THROW, UG_LOG, and ug::DebugWritingObject< TAlgebra >::write_debug().
Referenced by ug::ILUTPreconditioner< TAlgebra >::preprocess_mat().
set_info()
template<typename TAlgebra > void ug::ILUTPreconditioner< TAlgebra >::set_info (bool info) inline
sets storage information output to true or false
References ug::ILUTPreconditioner< TAlgebra >::m_info.
Referenced by ug::ILUTPreconditioner< TAlgebra >::ILUTPreconditioner().
set_ordering_algorithm()
template<typename TAlgebra > void ug::ILUTPreconditioner< TAlgebra >::set_ordering_algorithm (SmartPtr< ordering_algo_type > ordering_algo) inline
sets an ordering algorithm
References ug::ILUTPreconditioner< TAlgebra >::m_spOrderingAlgo.
set_show_progress()
template<typename TAlgebra > void ug::ILUTPreconditioner< TAlgebra >::set_show_progress (bool s) inline
set whether the progress meter should be shown
References ug::ILUTPreconditioner< TAlgebra >::m_show_progress, and s.
set_sort()
template<typename TAlgebra > void ug::ILUTPreconditioner< TAlgebra >::set_sort (bool b) inline
set cuthill-mckee sort on/off
References ug::ILUTPreconditioner< TAlgebra >::m_spOrderingAlgo, make_sp(), SPNULL, and UG_LOG.
set_threshold()
template<typename TAlgebra > void ug::ILUTPreconditioner< TAlgebra >::set_threshold (number thresh) inline
sets threshold for incomplete LU factorisation (added 01122010ih)
References ug::ILUTPreconditioner< TAlgebra >::m_eps.
solve()
template<typename TAlgebra > virtual bool ug::ILUTPreconditioner< TAlgebra >::solve (vector_type & c, const vector_type & d) inline virtual
References ug::ILUTPreconditioner< TAlgebra >::applyLU(), ug::ILUTPreconditioner< TAlgebra >::c2, ug::ILUTPreconditioner< TAlgebra >::m_bSortIsIdentity, ug::ILUTPreconditioner< TAlgebra >::m_old_ordering, ug::ILUTPreconditioner< TAlgebra >::m_ordering, ug::ILUTPreconditioner< TAlgebra >::m_spOrderingAlgo, PROFILE_BEGIN_GROUP, and ug::SetVectorAsPermutation().
Referenced by ug::ILUTPreconditioner< TAlgebra >::step().
step()
template<typename TAlgebra > virtual bool ug::ILUTPreconditioner< TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) inline virtual
computes a new correction c = B*d
This method computes a new correction c = B*d. It can only be called, when the preprocess has been done.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
[out] c correction
[in] d defect
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::PST_UNIQUE, and ug::ILUTPreconditioner< TAlgebra >::solve().
supports_parallel()
template<typename TAlgebra > virtual bool ug::ILUTPreconditioner< TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearIterator< TAlgebra::vector_type >.
Member Data Documentation
c2
template<typename TAlgebra > vector_type ug::ILUTPreconditioner< TAlgebra >::c2 protected
Referenced by ug::ILUTPreconditioner< TAlgebra >::solve().
m_bSortIsIdentity
template<typename TAlgebra > bool ug::ILUTPreconditioner< TAlgebra >::m_bSortIsIdentity protected
Referenced by ug::ILUTPreconditioner< TAlgebra >::ILUTPreconditioner(), ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2(), and ug::ILUTPreconditioner< TAlgebra >::solve().
m_eps
template<typename TAlgebra > double ug::ILUTPreconditioner< TAlgebra >::m_eps protected
Referenced by ug::ILUTPreconditioner< TAlgebra >::applyLU(), ug::ILUTPreconditioner< TAlgebra >::config_string(), ug::ILUTPreconditioner< TAlgebra >::ILUTPreconditioner(), ug::ILUTPreconditioner< TAlgebra >::multi_apply(), ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2(), and ug::ILUTPreconditioner< TAlgebra >::set_threshold().
m_info
template<typename TAlgebra > bool ug::ILUTPreconditioner< TAlgebra >::m_info protected
Referenced by ug::ILUTPreconditioner< TAlgebra >::ILUTPreconditioner(), ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2(), and ug::ILUTPreconditioner< TAlgebra >::set_info().
m_L
template<typename TAlgebra > matrix_type ug::ILUTPreconditioner< TAlgebra >::m_L protected
Referenced by ug::ILUTPreconditioner< TAlgebra >::applyLU(), ug::ILUTPreconditioner< TAlgebra >::multi_apply(), and ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2().
m_old_ordering
template<typename TAlgebra > ordering_container_type ug::ILUTPreconditioner< TAlgebra >::m_old_ordering protected
Referenced by ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2(), and ug::ILUTPreconditioner< TAlgebra >::solve().
m_ordering
template<typename TAlgebra > ordering_container_type ug::ILUTPreconditioner< TAlgebra >::m_ordering protected
Referenced by ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2(), and ug::ILUTPreconditioner< TAlgebra >::solve().
m_show_progress
template<typename TAlgebra > bool ug::ILUTPreconditioner< TAlgebra >::m_show_progress protected
Referenced by ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2(), and ug::ILUTPreconditioner< TAlgebra >::set_show_progress().
m_small
template<typename TAlgebra > const number ug::ILUTPreconditioner< TAlgebra >::m_small = 1e-8 static protected
Referenced by ug::ILUTPreconditioner< TAlgebra >::applyLU(), and ug::ILUTPreconditioner< TAlgebra >::multi_apply().
m_spOrderingAlgo
template<typename TAlgebra > SmartPtr<ordering_algo_type> ug::ILUTPreconditioner< TAlgebra >::m_spOrderingAlgo protected
for ordering algorithms
Referenced by ug::ILUTPreconditioner< TAlgebra >::config_string(), ug::ILUTPreconditioner< TAlgebra >::ILUTPreconditioner(), ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2(), ug::ILUTPreconditioner< TAlgebra >::set_ordering_algorithm(), ug::ILUTPreconditioner< TAlgebra >::set_sort(), and ug::ILUTPreconditioner< TAlgebra >::solve().
m_U
template<typename TAlgebra > matrix_type ug::ILUTPreconditioner< TAlgebra >::m_U protected
Referenced by ug::ILUTPreconditioner< TAlgebra >::applyLU(), ug::ILUTPreconditioner< TAlgebra >::multi_apply(), and ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2().
m_u
template<typename TAlgebra > const vector_type* ug::ILUTPreconditioner< TAlgebra >::m_u protected
Referenced by ug::ILUTPreconditioner< TAlgebra >::init(), and ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2().
newIndex
template<typename TAlgebra > std::vector<size_t> ug::ILUTPreconditioner< TAlgebra >::newIndex protected
oldIndex
template<typename TAlgebra > std::vector<size_t> ug::ILUTPreconditioner< TAlgebra >::oldIndex protected
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/preconditioner/ilut.h