ug4: ug::ApproximationSpace< TDomain > Class Template Reference
ug::ApproximationSpace< TDomain > Class Template Reference
base class for approximation spaces without type of algebra or dof distribution
#include <approximation_space.h>
Public Types
typedef TDomain domain_type
Domain type.
typedef domain_type::subset_handler_type subset_handler_type
Subset Handler type.
Public Types inherited from ug::IApproximationSpace
typedef MultiGrid grid_type
Type of Subset Handler.
typedef MGSubsetHandler subset_handler_type
Type of Subset Handler.
Public Member Functions
ApproximationSpace (SmartPtr< TDomain > domain)
constructor
ApproximationSpace (SmartPtr< TDomain > domain, const AlgebraType &algebraType)
constructor passing requested algebra type
SmartPtr< TDomain > domain ()
Return the domain.
ConstSmartPtr< TDomain > domain () const
Return the domain.
int get_dim () const
Public Member Functions inherited from ug::IApproximationSpace
void add (const char *name, const char *type)
adds function using string to indicate finite element type
void add (const char *name, const char *type, const char *subsets)
adds function using string to indicate finite element type
void add (const char *name, const char *type, int order)
adds function using string to indicate finite element type
void add (const char *name, const char *type, int order, const char *subsets)
adds function using string to indicate finite element type
void add (const std::vector< std::string > &vName, const char *type)
adds function using string to indicate finite element type
void add (const std::vector< std::string > &vName, const char *type, const std::vector< std::string > &vSubsets)
adds function using string to indicate finite element type
void add (const std::vector< std::string > &vName, const char *type, int order)
adds function using string to indicate finite element type
void add (const std::vector< std::string > &vName, const char *type, int order, const std::vector< std::string > &vSubsets)
adds function using string to indicate finite element type
void add (const std::vector< std::string > &vName, LFEID id)
add single solutions of LocalShapeFunctionSetID to the entire domain
void add (const std::vector< std::string > &vName, LFEID id, const std::vector< std::string > &vSubset)
add single solutions of LocalShapeFunctionSetID to selected subsets
void clear ()
clears functions
std::vector< SmartPtr< DoFDistribution > > dof_distributions () const
returns all currently created dof distributions
bool grouped () const
returns if dofs are grouped
IApproximationSpace (SmartPtr< subset_handler_type > spMGSH, SmartPtr< grid_type > spMG)
Constructor.
IApproximationSpace (SmartPtr< subset_handler_type > spMGSH, SmartPtr< grid_type >, const AlgebraType &algebraType)
Constructor setting the grouping flag.
void init_levels ()
initializes all level dof distributions
void init_surfaces ()
initializes all surface dof distributions
void init_top_surface ()
initializes all top surface dof distributions
bool might_contain_ghosts () const
returns if ghosts might be present on any level
bool might_contain_ghosts (int lvl) const
returns if ghosts might be present on a level
size_t num_levels () const
returns the number of level
void print_layout_statistic () const
prints statistic on layouts
void print_statistic () const
prints statistic about DoF Distribution
void print_statistic (std::string flags) const
prints statistic about DoF Distribution
const RevisionCounter & revision () const
returns the current revision
ConstSmartPtr< MGSubsetHandler > subset_handler () const
get underlying subset handler
ConstSmartPtr< SurfaceView > surface_view () const
returns the approximation space
~IApproximationSpace ()
Destructor.
SmartPtr< DoFDistribution > dof_distribution (const GridLevel &gl, bool bCreate=true)
SmartPtr< DoFDistribution > dd (const GridLevel &gl, bool bCreate=true)
ConstSmartPtr< DoFDistribution > dof_distribution (const GridLevel &gl, bool bCreate=true) const
ConstSmartPtr< DoFDistribution > dd (const GridLevel &gl, bool bCreate=true) const
ConstSmartPtr< DoFDistributionInfo > ddinfo () const
ConstSmartPtr< DoFDistributionInfo > dof_distribution_info () const
Public Member Functions inherited from ug::DoFDistributionInfoProvider
SubsetGroup all_subsets_grp_except_for (const char *names) const
returns subset group of all the subsets except for (by name)
int dim (size_t fct) const
returns the dimension in which solution lives
int dim_subset (int si) const
returns dimension of subset
ConstSmartPtr< DoFDistributionInfo > dof_distribution_info () const
returns underlying info
DoFDistributionInfoProvider ()
constructor
DoFDistributionInfoProvider (ConstSmartPtr< DoFDistributionInfo > spDDI)
constructor
FunctionGroup fct_grp_by_name (const char *names) const
returns a function group to a string of functions
size_t fct_id_by_name (const char *name) const
returns fct id by name
ConstSmartPtr< FunctionPattern > function_pattern () const
returns the function pattern
bool is_def_everywhere (size_t fct) const
returns true if the discrete function nr_fct is defined everywhere
bool is_def_in_subset (size_t fct, int si) const
returns if a function is defined on a subset
size_t max_dofs (const GridBaseObjectId gbo) const
returns the maximum number of dofs on a grid base object type
size_t max_dofs (const GridBaseObjectId gbo, const int si) const
returns the maximum number of dofs on a grid base object on a subset
size_t max_dofs (const int dim) const
returns the maximum number of dofs on grid objects in a dimension
size_t max_dofs (const int dim, const int si) const
returns the maximum number of dofs in a dimension on a subset
size_t max_dofs (const ReferenceObjectID roid) const
returns the maximum number of dofs on reference object type
size_t max_fct_dofs (const size_t fct, const GridBaseObjectId gbo) const
returns the maximal number of dofs on a base object type for a function component
size_t max_fct_dofs (const size_t fct, const GridBaseObjectId gbo, const int si) const
returns the maximum number of dofs on a grid base object on a subset for a function component
size_t max_fct_dofs (const size_t fct, const int dim, const int si) const
returns the maximum number of dofs in a dimension on a subset for a function component
size_t max_fct_dofs (const size_t fct, const ReferenceObjectID roid) const
returns the number of dofs on a reference object for a function component
size_t max_fct_dofs (const size_t fct, int dim) const
returns the maximal number of dofs on a dimension for a function component
std::string name (size_t fct) const
returns the name of the discrete function nr_fct
std::vector< std::string > names () const
returns the names of the discrete functions
size_t num_dofs (const ReferenceObjectID roid, const int si) const
returns the number of dofs on a Reference Object on a subset
size_t num_fct () const
number of discrete functions on subset si
size_t num_fct (int si) const
number of discrete functions on subset si
size_t num_fct_dofs (const size_t fct, const ReferenceObjectID roid, const int si) const
returns the number of dofs on a Reference Object on a subset for a function component
int num_subsets () const
returns number of subsets
size_t offset (const ReferenceObjectID roid, const int si, const size_t fct) const
returns the offset for reference element, subset and function
void print_local_dof_statistic () const
prints statistic on local dof distribution
void print_local_dof_statistic (int verboseLev) const
prints informations
void set_dof_distribution_info (ConstSmartPtr< DoFDistributionInfo > spDDI)
sets the dd info
SubsetGroup subset_grp_by_name (const char *names) const
returns subset group by name
ConstSmartPtr< ISubsetHandler > subset_handler () const
returns the subset handler
int subset_id_by_name (const char *name) const
returns the subset id
std::string subset_name (int si) const
returns subset name
const LFEID & local_finite_element_id (size_t fct) const
const LFEID & lfeid (size_t fct) const
Static Public Attributes
static const int dim = domain_type::dim
World Dimension.
Protected Attributes
SmartPtr< TDomain > m_spDomain
Domain, where solution lives.
Protected Attributes inherited from ug::IApproximationSpace
AlgebraType m_algebraType
suitable algebra type for the index distribution pattern
bool m_bAdaptionIsActive
bool m_bGrouped
flag if DoFs should be grouped
RevisionCounter m_RevCnt
revision counter
SmartPtr< DoFDistributionInfo > m_spDoFDistributionInfo
DofDistributionInfo.
MessageHub::SPCallbackId m_spGridAdaptionCallbackID
message hub id
MessageHub::SPCallbackId m_spGridDistributionCallbackID
SmartPtr< MultiGrid > m_spMG
multigrid, where elements are stored
SmartPtr< MGSubsetHandler > m_spMGSH
subsethandler, where elements are stored
SmartPtr< SurfaceView > m_spSurfaceView
Surface View.
std::vector< SmartPtr< DoFDistribution > > m_vDD
MG Level DoF Distribution.
SmartPtr< DoFIndexStorage > m_spDoFIndexStrgForLevelNoGhost
SmartPtr< DoFIndexStorage > m_spDoFIndexStrgForLevelWithGhost
Protected Attributes inherited from ug::DoFDistributionInfoProvider
ConstSmartPtr< DoFDistributionInfo > m_spDDI
Function Pattern.
Additional Inherited Members
Protected Member Functions inherited from ug::IApproximationSpace
void create_dof_distribution (const GridLevel &gl)
creates a dof distribution
void dof_distribution_info_required ()
create dof distribution info
void grid_changed_callback (const GridMessage_Adaption &msg)
void grid_distribution_callback (const GridMessage_Distribution &msg)
called during parallel redistribution
void init (SmartPtr< subset_handler_type > spMGSH, SmartPtr< grid_type > spMG, const AlgebraType &algebraType)
initializing
void register_at_adaption_msg_hub ()
registers at message hub for grid adaption
void reinit ()
reinits all data after grid adaption
void surface_view_required ()
creates surface SurfaceView if needed
Detailed Description
template<typename TDomain>
class ug::ApproximationSpace< TDomain >
base class for approximation spaces without type of algebra or dof distribution
Member Typedef Documentation
domain_type
template<typename TDomain > typedef TDomain ug::ApproximationSpace< TDomain >::domain_type
Domain type.
subset_handler_type
template<typename TDomain > typedef domain_type::subset_handler_type ug::ApproximationSpace< TDomain >::subset_handler_type
Subset Handler type.
Constructor & Destructor Documentation
ApproximationSpace() [1/2]
template<typename TDomain > ug::ApproximationSpace< TDomain >::ApproximationSpace (SmartPtr< TDomain > domain)
constructor
References ug::ApproximationSpace< TDomain >::m_spDomain, ug::IApproximationSpace::m_spMGSH, UG_THROW, and SmartPtr< T, FreePolicy >::valid().
ApproximationSpace() [2/2]
template<typename TDomain > ug::ApproximationSpace< TDomain >::ApproximationSpace (SmartPtr< TDomain > domain, const AlgebraType & algebraType)
constructor passing requested algebra type
References ug::ApproximationSpace< TDomain >::m_spDomain, ug::IApproximationSpace::m_spMGSH, UG_THROW, and SmartPtr< T, FreePolicy >::valid().
Member Function Documentation
domain() [1/2]
template<typename TDomain > SmartPtr<TDomain> ug::ApproximationSpace< TDomain >::domain () inline
Return the domain.
References ug::ApproximationSpace< TDomain >::m_spDomain.
domain() [2/2]
template<typename TDomain > ConstSmartPtr<TDomain> ug::ApproximationSpace< TDomain >::domain () const inline
Return the domain.
References ug::ApproximationSpace< TDomain >::m_spDomain.
Referenced by ug::OrderDownwind(), and ug::OrderLex().
get_dim()
template<typename TDomain > int ug::ApproximationSpace< TDomain >::get_dim () const inline
References ug::ApproximationSpace< TDomain >::dim.
Member Data Documentation
dim
template<typename TDomain > const int ug::ApproximationSpace< TDomain >::dim = domain_type::dim static
World Dimension.
Referenced by ug::ApproximationSpace< TDomain >::get_dim().
m_spDomain
template<typename TDomain > SmartPtr<TDomain> ug::ApproximationSpace< TDomain >::m_spDomain protected
Domain, where solution lives.
Referenced by ug::ApproximationSpace< TDomain >::ApproximationSpace(), and ug::ApproximationSpace< TDomain >::domain().
The documentation for this class was generated from the following files:
ugbase/lib_disc/common/marking_utils.h
ugbase/lib_disc/function_spaces/approximation_space.h
ugbase/lib_disc/function_spaces/approximation_space.cpp