ug4: ug::ICplUserData< dim > Class Template Reference
ug::ICplUserData< dim > Class Template Reference abstract
Base class for UserData.
#include <user_data.h>
Public Member Functions
bool at_current_time (size_t s) const
returns true iff the time point specification is equal to the current one, or not specified
virtual void check_setup () const
returns if the dependent data is ready for evaluation
void clear ()
clear all data
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)=0
compute values (and derivatives iff compDeriv == true)
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)=0
compute values (and derivatives iff compDeriv == true, but only for the 'current' time point)
virtual bool constant () const
returns if data is constant
int dim_local_ips () const
returns current local ip dimension
ICplUserData ()
default constructor
const MathVector< dim > & ip (size_t s, size_t ip) const
returns global ip
const MathVector< dim > * ips (size_t s) const
returns global ips
template<int ldim>
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
returns local ip
template<int ldim>
const MathVector< ldim > * local_ips (size_t s) const
returns local ips
virtual SmartPtr< ICplUserData > needed_data (size_t i)
return needed data
size_t num_ip (size_t s) const
returns the number of integration points
virtual size_t num_needed_data () const
number of other Data this data depends on
size_t num_series () const
returns the number of ip series
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
set local positions, returns series id
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
set local positions without the specification of the time point, returns series id
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
set global positions
template<int ldim>
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
sets new local ip positions for a local ip series
void set_subset (int si)
set the subset of evaluation
void set_time_point (size_t timePoint)
sets the current time point
void set_time_point (const size_t seriesId, const int timePointSpec)
sets a new time point for a local ip series
void set_times (const std::vector< number > &vTime)
set evaluation time
int subset () const
returns the subset of evaluation
number time () const
get the current evaluation time
number time (size_t s) const
get the specified evaluation time
size_t time_point ()
returns the current time point
size_t time_point (size_t s) const
returns the time point specification (in particular, the current one, if the own one not specified)
int time_point_specification (size_t s) const
returns the time point specification (note: it may be -1, i.e. not specified)
virtual void update_dof_sizes (const LocalIndices &ind)
resize arrays
virtual bool zero_derivative () const
returns if data depends on solution
virtual ~ICplUserData ()
virtual desctructor
Public Member Functions inherited from ug::UserDataInfo
virtual bool continuous () const =0
returns if provided data is continuous over geometric object boundaries
const FunctionGroup & function_group () const
Function Group of functions.
virtual int get_dim () const =0
returns dimension
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual bool requires_grid_fct () const =0
returns if grid function is needed for evaluation
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
sets the function pattern for a possibly needed grid function
virtual std::string type () const =0
returns type of data as string (e.g. "Number", "Vector", "Matrix")
virtual ~UserDataInfo ()
virtual destructor
Protected Member Functions
void check_s (size_t s) const
checks in debug mode the correct usage of indices
void check_s_ip (size_t s, size_t ip) const
checks in debug mode the correct usage of indices
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
help function to get local ips
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
callback invoked after global ips have been changed
virtual void local_ip_series_added (const size_t seriesID)
callback invoked after local ips have been added to the series
virtual void local_ip_series_to_be_cleared ()
callback invoked, when local ips are cleared
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)=0
callback invoked, if a local ip series has been changed
Protected Attributes
int m_defaultTimePoint
default time point (or -1 if not specified)
int m_locPosDim
dimension of local position (-1 indicates no dim set)
std::vector< const MathVector< 1 > * > m_pvLocIP1d
local ips of dimension 1d-3d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
subset for evaluation
size_t m_timePoint
current time point (used if no explicit specification for series)
std::vector< bool > m_vMayChange
flags if local ips may change
std::vector< size_t > m_vNumIP
number of evaluation points (-1 indicates no ips set)
std::vector< number > m_vTime
time for evaluation
std::vector< int > m_vTimePoint
time points for the series
std::vector< const MathVector< dim > * > m_vvGlobPos
global ips
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Detailed Description
template<int dim>
class ug::ICplUserData< dim >
Base class for UserData.
This is the base class for all coupled data at integration point. It handles the set of local integration points and stores the current time.
Template Parameters
dim world dimension
Constructor & Destructor Documentation
template<int dim> ug::ICplUserData< dim >::ICplUserData ()
default constructor
References ug::ICplUserData< dim >::m_locPosDim, ug::ICplUserData< dim >::m_pvLocIP1d, ug::ICplUserData< dim >::m_pvLocIP2d, ug::ICplUserData< dim >::m_pvLocIP3d, ug::ICplUserData< dim >::m_vMayChange, ug::ICplUserData< dim >::m_vNumIP, and ug::ICplUserData< dim >::m_vTime.
template<int dim> virtual ug::ICplUserData< dim >::~ICplUserData () inline virtual
virtual desctructor
Member Function Documentation
template<int dim> bool ug::ICplUserData< dim >::at_current_time (size_t s) const inline
returns true iff the time point specification is equal to the current one, or not specified
References ug::ICplUserData< dim >::m_timePoint, ug::ICplUserData< dim >::m_vTimePoint, ug::ICplUserData< dim >::num_series(), and UG_ASSERT.
template<int dim> void ug::ICplUserData< dim >::check_s (size_t s) const inline protected
checks in debug mode the correct usage of indices
References ug::ICplUserData< dim >::m_vvGlobPos, ug::ICplUserData< dim >::num_series(), and UG_ASSERT.
Referenced by ug::ICplUserData< dim >::check_s_ip().
template<int dim> void ug::ICplUserData< dim >::check_s_ip (size_t s, size_t ip) const inline protected
checks in debug mode the correct usage of indices
References ug::ICplUserData< dim >::check_s(), ug::ICplUserData< dim >::m_vvGlobPos, ug::ICplUserData< dim >::num_ip(), ug::CplUserData< TData, dim, TRet >::register_storage_callback(), and UG_ASSERT.
Referenced by ug::DependentUserData< TData, dim >::check_s_ip_fct().
template<int dim> virtual void ug::ICplUserData< dim >::check_setup () const inline virtual
returns if the dependent data is ready for evaluation
Reimplemented in ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >, ug::VectorDataExport< dim >, ug::GradientDataExport< dim >, and ug::ValueDataExport< dim >.
Referenced by ug::DependentUserData< TData, dim >::extract_fct_grp().
template<int dim> void ug::ICplUserData< dim >::clear ()
clear all data
References ug::ICplUserData< dim >::local_ip_series_to_be_cleared(), ug::ICplUserData< dim >::m_locPosDim, ug::ICplUserData< dim >::m_pvLocIP1d, ug::ICplUserData< dim >::m_pvLocIP2d, ug::ICplUserData< dim >::m_pvLocIP3d, ug::ICplUserData< dim >::m_si, ug::ICplUserData< dim >::m_timePoint, ug::ICplUserData< dim >::m_vMayChange, ug::ICplUserData< dim >::m_vNumIP, and ug::ICplUserData< dim >::m_vTime.
template<int dim> virtual void ug::ICplUserData< dim >::compute (LocalVector * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) pure virtual
compute values (and derivatives iff compDeriv == true)
Implemented in ug::vrl::VRLCondUserNumber< dim >, ug::StdDependentUserData< TImpl, TData, dim >, ug::StdDependentUserData< GradientDataExport< dim >, MathVector< dim >, dim >, ug::StdDependentUserData< GridFunctionGradientComponentData< TGridFunction >, number, TGridFunction::dim >, ug::StdDependentUserData< GridFunctionVectorData< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >, ug::StdDependentUserData< VectorDataExport< dim >, MathVector< dim >, dim >, ug::StdDependentUserData< DataExport< number, dim >, number, dim >, ug::StdDependentUserData< DataExport< ug::MathVector< dim >, dim >, ug::MathVector< dim >, dim >, ug::StdDependentUserData< DataExport< TData, dim >, TData, dim >, ug::StdDependentUserData< GridFunctionGradientData< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >, ug::StdDependentUserData< GridFunctionNumberData< TGridFunction >, number, TGridFunction::dim >, ug::StdDependentUserData< ValueDataExport< dim >, number, dim >, ug::StdExplicitGridFunctionData< TImpl, TData, TGridFunction >, ug::StdExplicitGridFunctionData< ExplicitGridFunctionValue< TGridFunction >, number, TGridFunction >, ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >, ug::StdConstData< TImpl, TData, dim >, ug::StdConstData< ConstUserVector< dim, worldDim >, MathVector< dim >, worldDim >, ug::StdConstData< ConstUserNumber< dim >, number, dim >, ug::StdConstData< ConstUserMatrix< N, M, worldDim >, MathMatrix< N, M >, worldDim >, ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >, ug::StdGlobPosData< TImpl, TData, dim, TRet >, ug::StdGlobPosData< IDWUserData< WDim, TData >, TData, WDim >, ug::StdGlobPosData< VRLCondUserNumber< dim >, number, dim, bool >, ug::StdGlobPosData< VRLUserData< TData, dim >, TData, dim >, ug::StdGlobPosData< RotatingVelocity2d, MathVector< 2 >, 2 >, ug::StdGlobPosData< LuaUserData< TData, dim, TRet >, TData, dim, TRet >, ug::StdGlobPosData< RotatingCone2d, number, 2 >, ug::StdGlobPosData< GlobalGridFunctionNumberData< TGridFunction >, number, TGridFunction::dim >, ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >.
template<int dim> virtual void ug::ICplUserData< dim >::compute (LocalVectorTimeSeries * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) pure virtual
compute values (and derivatives iff compDeriv == true, but only for the 'current' time point)
Implemented in ug::StdDependentUserData< TImpl, TData, dim >, ug::StdDependentUserData< GradientDataExport< dim >, MathVector< dim >, dim >, ug::StdDependentUserData< GridFunctionGradientComponentData< TGridFunction >, number, TGridFunction::dim >, ug::StdDependentUserData< GridFunctionVectorData< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >, ug::StdDependentUserData< VectorDataExport< dim >, MathVector< dim >, dim >, ug::StdDependentUserData< DataExport< number, dim >, number, dim >, ug::StdDependentUserData< DataExport< ug::MathVector< dim >, dim >, ug::MathVector< dim >, dim >, ug::StdDependentUserData< DataExport< TData, dim >, TData, dim >, ug::StdDependentUserData< GridFunctionGradientData< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >, ug::StdDependentUserData< GridFunctionNumberData< TGridFunction >, number, TGridFunction::dim >, ug::StdDependentUserData< ValueDataExport< dim >, number, dim >, ug::StdExplicitGridFunctionData< TImpl, TData, TGridFunction >, ug::StdExplicitGridFunctionData< ExplicitGridFunctionValue< TGridFunction >, number, TGridFunction >, ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >, ug::StdConstData< TImpl, TData, dim >, ug::StdConstData< ConstUserVector< dim, worldDim >, MathVector< dim >, worldDim >, ug::StdConstData< ConstUserNumber< dim >, number, dim >, ug::StdConstData< ConstUserMatrix< N, M, worldDim >, MathMatrix< N, M >, worldDim >, ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >, ug::StdGlobPosData< TImpl, TData, dim, TRet >, ug::StdGlobPosData< IDWUserData< WDim, TData >, TData, WDim >, ug::StdGlobPosData< VRLCondUserNumber< dim >, number, dim, bool >, ug::StdGlobPosData< VRLUserData< TData, dim >, TData, dim >, ug::StdGlobPosData< RotatingVelocity2d, MathVector< 2 >, 2 >, ug::StdGlobPosData< LuaUserData< TData, dim, TRet >, TData, dim, TRet >, ug::StdGlobPosData< RotatingCone2d, number, 2 >, ug::StdGlobPosData< GlobalGridFunctionNumberData< TGridFunction >, number, TGridFunction::dim >, ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >.
template<int dim> virtual bool ug::ICplUserData< dim >::constant () const inline virtual
returns if data is constant
Reimplemented in ug::StdConstData< TImpl, TData, dim >, ug::StdConstData< ConstUserVector< dim, worldDim >, MathVector< dim >, worldDim >, ug::StdConstData< ConstUserNumber< dim >, number, dim >, ug::StdConstData< ConstUserMatrix< N, M, worldDim >, MathMatrix< N, M >, worldDim >, ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >, ug::StdGlobPosData< TImpl, TData, dim, TRet >, ug::StdGlobPosData< IDWUserData< WDim, TData >, TData, WDim >, ug::StdGlobPosData< VRLCondUserNumber< dim >, number, dim, bool >, ug::StdGlobPosData< VRLUserData< TData, dim >, TData, dim >, ug::StdGlobPosData< RotatingVelocity2d, MathVector< 2 >, 2 >, ug::StdGlobPosData< LuaUserData< TData, dim, TRet >, TData, dim, TRet >, ug::StdGlobPosData< RotatingCone2d, number, 2 >, ug::StdGlobPosData< GlobalGridFunctionNumberData< TGridFunction >, number, TGridFunction::dim >, ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >, ug::StdExplicitGridFunctionData< TImpl, TData, TGridFunction >, ug::StdExplicitGridFunctionData< ExplicitGridFunctionValue< TGridFunction >, number, TGridFunction >, and ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >.
template<int dim> int ug::ICplUserData< dim >::dim_local_ips () const inline
returns current local ip dimension
Referenced by ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >::compute().
template<int dim> std::vector<const MathVector<1>*>& ug::ICplUserData< dim >::get_local_ips (Int2Type< 1 >) inline protected
help function to get local ips
Referenced by ug::ICplUserData< dim >::local_ip(), ug::ICplUserData< dim >::local_ips(), ug::ICplUserData< dim >::register_local_ip_series(), and ug::ICplUserData< dim >::set_local_ips().
template<int dim> std::vector<const MathVector<2>*>& ug::ICplUserData< dim >::get_local_ips (Int2Type< 2 >) inline protected
template<int dim> std::vector<const MathVector<3>*>& ug::ICplUserData< dim >::get_local_ips (Int2Type< 3 >) inline protected
template<int dim> const std::vector<const MathVector<1>*>& ug::ICplUserData< dim >::get_local_ips (Int2Type< 1 >) const inline protected
template<int dim> const std::vector<const MathVector<2>*>& ug::ICplUserData< dim >::get_local_ips (Int2Type< 2 >) const inline protected
template<int dim> const std::vector<const MathVector<3>*>& ug::ICplUserData< dim >::get_local_ips (Int2Type< 3 >) const inline protected
template<int dim> virtual void ug::ICplUserData< dim >::global_ips_changed (const size_t seriesID, const MathVector< dim > * vPos, const size_t numIP) inline protected virtual
callback invoked after global ips have been changed
This callback is invoked when the global ips have been changed. It can be used by derived classes to react on this fact, e.g. to forward the global_ips.
Reimplemented in ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >.
Referenced by ug::ICplUserData< dim >::set_global_ips().
template<int dim> const MathVector<dim>& ug::ICplUserData< dim >::ip (size_t s, size_t ip) const inline
returns global ip
References ug::ICplUserData< dim >::ip().
Referenced by ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >::compute(), ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >::compute(), ug::GridFunctionNumberData< TGridFunction >::eval_and_deriv(), ug::DarcyVelocityLinker< dim >::eval_and_deriv(), ug::GridFunctionVectorData< TGridFunction >::eval_and_deriv(), ug::LuaUserFunction< TData, dim, TDataIn >::eval_and_deriv(), ug::GridFunctionGradientData< TGridFunction >::eval_and_deriv(), ug::GridFunctionGradientComponentData< TGridFunction >::eval_and_deriv(), ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >::evaluate(), ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >::evaluate(), ug::DarcyVelocityLinker< dim >::evaluate(), ug::ExplicitGridFunctionValue< TGridFunction >::evaluate(), ug::LuaUserFunction< TData, dim, TDataIn >::evaluate(), ug::ExplicitGridFunctionGradient< TGridFunction >::evaluate(), ug::ICplUserData< dim >::ip(), ug::ICplUserData< dim >::local_ip(), ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >::operator()(), ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >::operator()(), ug::DependentUserData< TData, dim >::resize_deriv_array(), ug::DependentUserData< TData, dim >::set_zero(), and ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >::value_storage_changed().
template<int dim> const MathVector<dim>* ug::ICplUserData< dim >::ips (size_t s) const inline
returns global ips
Referenced by ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >::eval().
template<int dim> template<int ldim> const MathVector< ldim > & ug::ICplUserData< dim >::local_ip (size_t s, size_t ip) const
returns local ip
References ug::ICplUserData< dim >::get_local_ips(), ug::ICplUserData< dim >::ip(), ug::ICplUserData< dim >::m_locPosDim, ug::ICplUserData< dim >::num_ip(), ug::ICplUserData< dim >::num_series(), UG_ASSERT, and UG_THROW.
template<int dim> virtual void ug::ICplUserData< dim >::local_ip_series_added (const size_t seriesID) inline protected virtual
callback invoked after local ips have been added to the series
This callback is invoked when local ips have been added. It can be used by derived classes to react on this fact, e.g. to forward the local_ips or to adapt data field sizes. Note: The number of series can only be increased and the number of ips for a series can not be changed once set. This is important to allow derived classes to only increase their data fields as well, leaving accessing pointers invariant. If the local ip series must be changed, this can only be done through a clear(), that will invoke the local_ip_series_to_be_cleared() callback, and adding all local series again.
Reimplemented in ug::DependentUserData< TData, dim >, ug::DependentUserData< MathVector< dim >, dim >, ug::DependentUserData< TRet, dim >, ug::DependentUserData< ug::MathMatrix< dim, dim >, dim >, ug::DependentUserData< ug::MathVector< dim >, dim >, ug::DependentUserData< number, dim >, ug::DependentUserData< MathVector< TGridFunction::dim >, dim >, ug::CplUserData< TData, dim, TRet >, ug::CplUserData< MathVector< dim >, dim >, ug::CplUserData< number, dim, void >, ug::CplUserData< MathTensor< TRank, dim >, dim, void >, ug::CplUserData< MathVector< TGridFunction::dim >, dim, void >, ug::CplUserData< TData, dim, void >, ug::CplUserData< TRet, dim >, ug::CplUserData< MathVector< dim >, dim, void >, ug::CplUserData< MathVector< 2 >, dim, void >, ug::CplUserData< MathMatrix< N, M >, dim, void >, ug::CplUserData< number, dim, bool >, ug::CplUserData< ug::MathMatrix< dim, dim >, dim >, ug::CplUserData< TData, 2 >, ug::CplUserData< ug::MathVector< dim >, dim >, ug::CplUserData< TData, dim >, ug::CplUserData< number, 2, bool >, ug::CplUserData< number, dim >, ug::CplUserData< MathVector< TGridFunction::dim >, dim >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >.
Referenced by ug::ICplUserData< dim >::register_local_ip_series().
template<int dim> virtual void ug::ICplUserData< dim >::local_ip_series_to_be_cleared () inline protected virtual
callback invoked, when local ips are cleared
Reimplemented in ug::DependentUserData< TData, dim >, ug::DependentUserData< MathVector< dim >, dim >, ug::DependentUserData< TRet, dim >, ug::DependentUserData< ug::MathMatrix< dim, dim >, dim >, ug::DependentUserData< ug::MathVector< dim >, dim >, ug::DependentUserData< number, dim >, ug::DependentUserData< MathVector< TGridFunction::dim >, dim >, ug::CplUserData< TData, dim, TRet >, ug::CplUserData< MathVector< dim >, dim >, ug::CplUserData< number, dim, void >, ug::CplUserData< MathTensor< TRank, dim >, dim, void >, ug::CplUserData< MathVector< TGridFunction::dim >, dim, void >, ug::CplUserData< TData, dim, void >, ug::CplUserData< TRet, dim >, ug::CplUserData< MathVector< dim >, dim, void >, ug::CplUserData< MathVector< 2 >, dim, void >, ug::CplUserData< MathMatrix< N, M >, dim, void >, ug::CplUserData< number, dim, bool >, ug::CplUserData< ug::MathMatrix< dim, dim >, dim >, ug::CplUserData< TData, 2 >, ug::CplUserData< ug::MathVector< dim >, dim >, ug::CplUserData< TData, dim >, ug::CplUserData< number, 2, bool >, ug::CplUserData< number, dim >, and ug::CplUserData< MathVector< TGridFunction::dim >, dim >.
Referenced by ug::ICplUserData< dim >::clear().
template<int dim> template<int ldim> const MathVector< ldim > * ug::ICplUserData< dim >::local_ips (size_t s) const
returns local ips
References ug::ICplUserData< dim >::get_local_ips(), ug::ICplUserData< dim >::m_locPosDim, ug::ICplUserData< dim >::num_series(), UG_ASSERT, and UG_THROW.
template<int dim> virtual void ug::ICplUserData< dim >::local_ips_changed (const size_t seriesID, const size_t newNumIP) protected pure virtual
callback invoked, if a local ip series has been changed
Implemented in ug::DependentUserData< TData, dim >, ug::DependentUserData< MathVector< dim >, dim >, ug::DependentUserData< TRet, dim >, ug::DependentUserData< ug::MathMatrix< dim, dim >, dim >, ug::DependentUserData< ug::MathVector< dim >, dim >, ug::DependentUserData< number, dim >, ug::DependentUserData< MathVector< TGridFunction::dim >, dim >, ug::CplUserData< TData, dim, TRet >, ug::CplUserData< MathVector< dim >, dim >, ug::CplUserData< number, dim, void >, ug::CplUserData< MathTensor< TRank, dim >, dim, void >, ug::CplUserData< MathVector< TGridFunction::dim >, dim, void >, ug::CplUserData< TData, dim, void >, ug::CplUserData< TRet, dim >, ug::CplUserData< MathVector< dim >, dim, void >, ug::CplUserData< MathVector< 2 >, dim, void >, ug::CplUserData< MathMatrix< N, M >, dim, void >, ug::CplUserData< number, dim, bool >, ug::CplUserData< ug::MathMatrix< dim, dim >, dim >, ug::CplUserData< TData, 2 >, ug::CplUserData< ug::MathVector< dim >, dim >, ug::CplUserData< TData, dim >, ug::CplUserData< number, 2, bool >, ug::CplUserData< number, dim >, ug::CplUserData< MathVector< TGridFunction::dim >, dim >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >.
Referenced by ug::ICplUserData< dim >::set_local_ips().
template<int dim> virtual SmartPtr<ICplUserData> ug::ICplUserData< dim >::needed_data (size_t i) inline virtual
return needed data
Reimplemented in ug::DataExport< TData, dim >, ug::DataExport< ug::MathVector< dim >, dim >, ug::DataExport< number, dim >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >.
References SPNULL.
template<int dim> size_t ug::ICplUserData< dim >::num_ip (size_t s) const inline
returns the number of integration points
References UG_ASSERT.
Referenced by ug::ICplUserData< dim >::check_s_ip(), ug::DependentUserData< TData, dim >::check_s_ip(), ug::CplUserData< TData, dim, TRet >::check_series_ip(), ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >::compute(), ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >::compute(), ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >::eval(), ug::ICplUserData< dim >::local_ip(), ug::CplUserData< TData, dim, TRet >::local_ip_series_added(), ug::DependentUserData< TData, dim >::resize_deriv_array(), ug::ICplUserData< dim >::set_global_ips(), and ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >::value_storage_changed().
template<int dim> virtual size_t ug::ICplUserData< dim >::num_needed_data () const inline virtual
number of other Data this data depends on
Reimplemented in ug::DataExport< TData, dim >, ug::DataExport< ug::MathVector< dim >, dim >, ug::DataExport< number, dim >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >.
template<int dim> size_t ug::ICplUserData< dim >::num_series () const inline
returns the number of ip series
Referenced by ug::ICplUserData< dim >::at_current_time(), ug::ICplUserData< dim >::check_s(), ug::DependentUserData< TData, dim >::check_s_ip(), ug::CplUserData< TData, dim, TRet >::check_series(), ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >::compute(), ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >::compute(), ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >::eval(), ug::ICplUserData< dim >::local_ip(), ug::ICplUserData< dim >::local_ips(), ug::ICplUserData< dim >::set_global_ips(), ug::ICplUserData< dim >::set_local_ips(), ug::ICplUserData< dim >::set_time_point(), ug::ICplUserData< dim >::time_point(), and ug::ICplUserData< dim >::time_point_specification().
template<int dim> template<int ldim> size_t ug::ICplUserData< dim >::register_local_ip_series (const MathVector< ldim > * vPos, const size_t numIP, const int timePointSpec, bool bMayChange = true)
set local positions, returns series id
This method registers a local ip series. If the position of points may change during computations, this can be specified. IMPORTANT: the memory of the local ip values must remain valid until the UserData is deleted.
Returns
size_t series id
References ug::ICplUserData< dim >::get_local_ips(), ug::ICplUserData< dim >::local_ip_series_added(), ug::ICplUserData< dim >::m_defaultTimePoint, ug::ICplUserData< dim >::m_locPosDim, ug::ICplUserData< dim >::m_vMayChange, ug::ICplUserData< dim >::m_vNumIP, ug::ICplUserData< dim >::m_vTimePoint, and UG_THROW.
template<int dim> template<int ldim> size_t ug::ICplUserData< dim >::register_local_ip_series (const MathVector< ldim > * vPos, const size_t numIP, bool bMayChange = true) inline
set local positions without the specification of the time point, returns series id
template<int dim> void ug::ICplUserData< dim >::set_global_ips (size_t s, const MathVector< dim > * vPos, size_t numIP)
set global positions
References ug::ICplUserData< dim >::global_ips_changed(), ug::ICplUserData< dim >::m_vvGlobPos, ug::ICplUserData< dim >::num_ip(), ug::ICplUserData< dim >::num_series(), UG_ASSERT, and UG_THROW.
template<int dim> template<int ldim> void ug::ICplUserData< dim >::set_local_ips (const size_t seriesId, const MathVector< ldim > * vPos, const size_t numIP)
sets new local ip positions for a local ip series
This method set new local positions for an already registered ip series. Of course this is only possible for a ip series with the bMayChange flag set to true.
References ug::ICplUserData< dim >::get_local_ips(), ug::ICplUserData< dim >::local_ips_changed(), ug::ICplUserData< dim >::m_locPosDim, ug::ICplUserData< dim >::m_vMayChange, ug::ICplUserData< dim >::m_vNumIP, ug::ICplUserData< dim >::num_series(), and UG_THROW.
template<int dim> void ug::ICplUserData< dim >::set_subset (int si) inline
set the subset of evaluation
template<int dim> void ug::ICplUserData< dim >::set_time_point (size_t timePoint) inline
sets the current time point
template<int dim> void ug::ICplUserData< dim >::set_time_point (const size_t seriesId, const int timePointSpec)
sets a new time point for a local ip series
This method set a new time point for an already registered ip series. Of course this is only possible for a ip series with the bMayChange flag set to true.
References ug::ICplUserData< dim >::m_defaultTimePoint, ug::ICplUserData< dim >::m_vMayChange, ug::ICplUserData< dim >::m_vTimePoint, ug::ICplUserData< dim >::num_series(), and UG_THROW.
template<int dim> void ug::ICplUserData< dim >::set_times (const std::vector< number > & vTime) inline
set evaluation time
template<int dim> int ug::ICplUserData< dim >::subset () const inline
returns the subset of evaluation
Referenced by ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >::compute(), and ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >::eval().
template<int dim> number ug::ICplUserData< dim >::time () const inline
get the current evaluation time
Referenced by ug::LuaUserData< TData, dim, TRet >::check_callback_returns(), ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >::compute(), ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >::eval(), ug::LuaUserFunction< TData, dim, TDataIn >::eval_deriv(), ug::LuaUserFunction< TData, dim, TDataIn >::eval_value(), ug::RotatingCone2d::evaluate(), ug::DarcyVelocityLinker< dim >::evaluate(), ug::ProjectionLinker< dim >::evaluate(), ug::LuaUserData< TData, dim, TRet >::evaluate(), ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >::evaluate(), ug::LuaUserFunction< TData, dim, TDataIn >::evaluate(), ug::GradientDataExport< dim >::GradientDataExport(), ug::InverseLinker< dim >::InverseLinker(), ug::DataExport< TData, dim >::MemberFunctionFunctor< TClass, refDim >::operator()(), ug::DataExport< TData, dim >::Functor< 3 >::operator()(), ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::ScaleAddLinker(), ug::ValueDataExport< dim >::ValueDataExport(), ug::VectorDataExport< dim >::VectorDataExport(), and ug::LognormalRandomField< TData, dim, TRet >::~LognormalRandomField().
template<int dim> number ug::ICplUserData< dim >::time (size_t s) const inline
get the specified evaluation time
template<int dim> size_t ug::ICplUserData< dim >::time_point () inline
returns the current time point
Referenced by ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >::eval().
template<int dim> size_t ug::ICplUserData< dim >::time_point (size_t s) const inline
returns the time point specification (in particular, the current one, if the own one not specified)
References ug::ICplUserData< dim >::m_timePoint, ug::ICplUserData< dim >::m_vTimePoint, ug::ICplUserData< dim >::num_series(), and UG_ASSERT.
template<int dim> int ug::ICplUserData< dim >::time_point_specification (size_t s) const inline
returns the time point specification (note: it may be -1, i.e. not specified)
References ug::ICplUserData< dim >::m_vTimePoint, ug::ICplUserData< dim >::num_series(), and UG_ASSERT.
template<int dim> virtual void ug::ICplUserData< dim >::update_dof_sizes (const LocalIndices & ind) inline virtual
resize arrays
Reimplemented in ug::DependentUserData< TData, dim >, ug::DependentUserData< MathVector< dim >, dim >, ug::DependentUserData< TRet, dim >, ug::DependentUserData< ug::MathMatrix< dim, dim >, dim >, ug::DependentUserData< ug::MathVector< dim >, dim >, ug::DependentUserData< number, dim >, and ug::DependentUserData< MathVector< TGridFunction::dim >, dim >.
template<int dim> virtual bool ug::ICplUserData< dim >::zero_derivative () const inline virtual
returns if data depends on solution
Reimplemented in ug::DependentUserData< TData, dim >, ug::DependentUserData< MathVector< dim >, dim >, ug::DependentUserData< TRet, dim >, ug::DependentUserData< ug::MathMatrix< dim, dim >, dim >, ug::DependentUserData< ug::MathVector< dim >, dim >, ug::DependentUserData< number, dim >, ug::DependentUserData< MathVector< TGridFunction::dim >, dim >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >.
Member Data Documentation
template<int dim> int ug::ICplUserData< dim >::m_defaultTimePoint protected
default time point (or -1 if not specified)
Referenced by ug::ICplUserData< dim >::register_local_ip_series(), and ug::ICplUserData< dim >::set_time_point().
template<int dim> int ug::ICplUserData< dim >::m_locPosDim protected
dimension of local position (-1 indicates no dim set)
Referenced by ug::ICplUserData< dim >::clear(), ug::ICplUserData< dim >::ICplUserData(), ug::ICplUserData< dim >::local_ip(), ug::ICplUserData< dim >::local_ips(), ug::ICplUserData< dim >::register_local_ip_series(), and ug::ICplUserData< dim >::set_local_ips().
template<int dim> std::vector<const MathVector<1>*> ug::ICplUserData< dim >::m_pvLocIP1d protected
local ips of dimension 1d-3d
Referenced by ug::ICplUserData< dim >::clear(), and ug::ICplUserData< dim >::ICplUserData().
template<int dim> std::vector<const MathVector<2>*> ug::ICplUserData< dim >::m_pvLocIP2d protected
Referenced by ug::ICplUserData< dim >::clear(), and ug::ICplUserData< dim >::ICplUserData().
template<int dim> std::vector<const MathVector<3>*> ug::ICplUserData< dim >::m_pvLocIP3d protected
Referenced by ug::ICplUserData< dim >::clear(), and ug::ICplUserData< dim >::ICplUserData().
template<int dim> int ug::ICplUserData< dim >::m_si protected
subset for evaluation
Referenced by ug::ICplUserData< dim >::clear().
template<int dim> size_t ug::ICplUserData< dim >::m_timePoint protected
current time point (used if no explicit specification for series)
Referenced by ug::ICplUserData< dim >::at_current_time(), ug::ICplUserData< dim >::clear(), and ug::ICplUserData< dim >::time_point().
template<int dim> std::vector<bool> ug::ICplUserData< dim >::m_vMayChange protected
flags if local ips may change
Referenced by ug::ICplUserData< dim >::clear(), ug::ICplUserData< dim >::ICplUserData(), ug::ICplUserData< dim >::register_local_ip_series(), ug::ICplUserData< dim >::set_local_ips(), and ug::ICplUserData< dim >::set_time_point().
template<int dim> std::vector<size_t> ug::ICplUserData< dim >::m_vNumIP protected
number of evaluation points (-1 indicates no ips set)
Referenced by ug::ICplUserData< dim >::clear(), ug::ICplUserData< dim >::ICplUserData(), ug::ICplUserData< dim >::register_local_ip_series(), and ug::ICplUserData< dim >::set_local_ips().
template<int dim> std::vector<number> ug::ICplUserData< dim >::m_vTime protected
time for evaluation
Referenced by ug::ICplUserData< dim >::clear(), and ug::ICplUserData< dim >::ICplUserData().
template<int dim> std::vector<int> ug::ICplUserData< dim >::m_vTimePoint protected
time points for the series
Referenced by ug::ICplUserData< dim >::at_current_time(), ug::ICplUserData< dim >::register_local_ip_series(), ug::ICplUserData< dim >::set_time_point(), ug::ICplUserData< dim >::time_point(), and ug::ICplUserData< dim >::time_point_specification().
template<int dim> std::vector<const MathVector<dim>*> ug::ICplUserData< dim >::m_vvGlobPos protected
global ips
Referenced by ug::ICplUserData< dim >::check_s(), ug::ICplUserData< dim >::check_s_ip(), and ug::ICplUserData< dim >::set_global_ips().
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/user_data/user_data.h
ugbase/lib_disc/spatial_disc/user_data/user_data_impl.h