ug4: ug::FV1Geometry< TElem, TWorldDim >::SCVF Class Reference
ug::FV1Geometry< TElem, TWorldDim >::SCVF Class Reference
Sub-Control Volume Face structure.
#include <fv1_geom.h>
Public Member Functions
number detJ () const
Determinant of Jacobian in integration point.
size_t from () const
index of SubControlVolume on one side of the scvf
const MathVector< worldDim > & global_corner (size_t co) const
return global corner number i
const MathVector< worldDim > & global_grad (size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector () const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip () const
global integration point of scvf
const MathMatrix< worldDim, dim > & JTInv () const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector () const
vector of local gradients in ip point
const MathVector< dim > & local_ip () const
local integration point of scvf
const MathVector< worldDim > & normal () const
normal on scvf (points direction "from"->"to"). Norm is equal to area
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points on scvf
size_t num_sh () const
number of shape functions
SCVF ()
number shape (size_t sh) const
value of shape function i in integration point
const number * shape_vector () const
vector of shape functions in ip point
size_t to () const
index of SubControlVolume on one side of the scvf
Static Public Attributes
static const size_t numCo = traits::NumCornersOfSCVF
Number of corners of scvf.
Private Attributes
number detj
size_t From
MathVector< worldDim > globalIP
MathMatrix< worldDim, dim > JtInv
MathVector< dim > localIP
MathVector< worldDim > Normal
size_t To
MathVector< worldDim > vGlobalGrad [nsh]
MathVector< worldDim > vGloPos [numCo]
MathVector< dim > vLocalGrad [nsh]
MathVector< dim > vLocPos [numCo]
MidID vMidID [numCo]
number vShape [nsh]
Friends
class FV1Geometry< TElem, TWorldDim >
Detailed Description
template<typename TElem, int TWorldDim>
class ug::FV1Geometry< TElem, TWorldDim >::SCVF
Sub-Control Volume Face structure.
Each finite element is cut by several sub-control volume faces. The idea is that the "dual" skeleton formed by the sub control volume faces of all elements again gives rise to a regular mesh with closed (lipschitz-bounded) control volumes. The SCVF are the boundary of the control volume. In computation the flux over each SCVF must be the same in both directions over the face in order to guarantee the conservation property.
Constructor & Destructor Documentation
SCVF()
template<typename TElem , int TWorldDim> ug::FV1Geometry< TElem, TWorldDim >::SCVF::SCVF () inline
Member Function Documentation
detJ()
template<typename TElem , int TWorldDim> number ug::FV1Geometry< TElem, TWorldDim >::SCVF::detJ () const inline
Determinant of Jacobian in integration point.
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::detj.
from()
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::SCVF::from () const inline
index of SubControlVolume on one side of the scvf
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::From.
global_corner()
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::FV1Geometry< TElem, TWorldDim >::SCVF::global_corner (size_t co) const inline
return global corner number i
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::num_corners(), UG_ASSERT, and ug::FV1Geometry< TElem, TWorldDim >::SCVF::vGloPos.
global_grad()
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::FV1Geometry< TElem, TWorldDim >::SCVF::global_grad (size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::num_sh(), UG_ASSERT, and ug::FV1Geometry< TElem, TWorldDim >::SCVF::vGlobalGrad.
global_grad_vector()
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::FV1Geometry< TElem, TWorldDim >::SCVF::global_grad_vector () const inline
vector of global gradients in ip point
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::vGlobalGrad.
global_ip()
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::FV1Geometry< TElem, TWorldDim >::SCVF::global_ip () const inline
global integration point of scvf
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::globalIP.
JTInv()
template<typename TElem , int TWorldDim> const MathMatrix<worldDim,dim>& ug::FV1Geometry< TElem, TWorldDim >::SCVF::JTInv () const inline
Transposed Inverse of Jacobian in integration point.
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::JtInv.
local_corner()
template<typename TElem , int TWorldDim> const MathVector<dim>& ug::FV1Geometry< TElem, TWorldDim >::SCVF::local_corner (size_t co) const inline
return local corner number i
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::num_corners(), UG_ASSERT, and ug::FV1Geometry< TElem, TWorldDim >::SCVF::vLocPos.
local_grad()
template<typename TElem , int TWorldDim> const MathVector<dim>& ug::FV1Geometry< TElem, TWorldDim >::SCVF::local_grad (size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::num_sh(), UG_ASSERT, and ug::FV1Geometry< TElem, TWorldDim >::SCVF::vLocalGrad.
local_grad_vector()
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::FV1Geometry< TElem, TWorldDim >::SCVF::local_grad_vector () const inline
vector of local gradients in ip point
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::vLocalGrad.
local_ip()
template<typename TElem , int TWorldDim> const MathVector<dim>& ug::FV1Geometry< TElem, TWorldDim >::SCVF::local_ip () const inline
local integration point of scvf
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::localIP.
normal()
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::FV1Geometry< TElem, TWorldDim >::SCVF::normal () const inline
normal on scvf (points direction "from"->"to"). Norm is equal to area
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::Normal.
num_corners()
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::SCVF::num_corners () const inline
number of corners, that bound the scvf
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::numCo.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::global_corner(), and ug::FV1Geometry< TElem, TWorldDim >::SCVF::local_corner().
num_ip()
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::SCVF::num_ip () const inline
number of integration points on scvf
References ug::FV1Geometry< TElem, TWorldDim >::nip.
num_sh()
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::SCVF::num_sh () const inline
number of shape functions
References ug::FV1Geometry< TElem, TWorldDim >::nsh.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::global_grad(), and ug::FV1Geometry< TElem, TWorldDim >::SCVF::local_grad().
shape()
template<typename TElem , int TWorldDim> number ug::FV1Geometry< TElem, TWorldDim >::SCVF::shape (size_t sh) const inline
value of shape function i in integration point
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::vShape.
shape_vector()
template<typename TElem , int TWorldDim> const number* ug::FV1Geometry< TElem, TWorldDim >::SCVF::shape_vector () const inline
vector of shape functions in ip point
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::vShape.
to()
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::SCVF::to () const inline
index of SubControlVolume on one side of the scvf
References ug::FV1Geometry< TElem, TWorldDim >::SCVF::To.
Friends And Related Function Documentation
FV1Geometry< TElem, TWorldDim >
template<typename TElem , int TWorldDim> friend class FV1Geometry< TElem, TWorldDim > friend
Member Data Documentation
detj
template<typename TElem , int TWorldDim> number ug::FV1Geometry< TElem, TWorldDim >::SCVF::detj private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::detJ().
From
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::SCVF::From private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::from().
globalIP
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1Geometry< TElem, TWorldDim >::SCVF::globalIP private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::global_ip().
JtInv
template<typename TElem , int TWorldDim> MathMatrix<worldDim,dim> ug::FV1Geometry< TElem, TWorldDim >::SCVF::JtInv private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::JTInv().
localIP
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1Geometry< TElem, TWorldDim >::SCVF::localIP private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::local_ip().
Normal
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1Geometry< TElem, TWorldDim >::SCVF::Normal private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::normal().
numCo
template<typename TElem , int TWorldDim> const size_t ug::FV1Geometry< TElem, TWorldDim >::SCVF::numCo = traits::NumCornersOfSCVF static
Number of corners of scvf.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::num_corners().
To
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::SCVF::To private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::to().
vGlobalGrad
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1Geometry< TElem, TWorldDim >::SCVF::vGlobalGrad[nsh] private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::global_grad(), and ug::FV1Geometry< TElem, TWorldDim >::SCVF::global_grad_vector().
vGloPos
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1Geometry< TElem, TWorldDim >::SCVF::vGloPos[numCo] private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::global_corner().
vLocalGrad
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1Geometry< TElem, TWorldDim >::SCVF::vLocalGrad[nsh] private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::local_grad(), and ug::FV1Geometry< TElem, TWorldDim >::SCVF::local_grad_vector().
vLocPos
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1Geometry< TElem, TWorldDim >::SCVF::vLocPos[numCo] private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::local_corner().
vMidID
template<typename TElem , int TWorldDim> MidID ug::FV1Geometry< TElem, TWorldDim >::SCVF::vMidID[numCo] private
vShape
template<typename TElem , int TWorldDim> number ug::FV1Geometry< TElem, TWorldDim >::SCVF::vShape[nsh] private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::shape(), and ug::FV1Geometry< TElem, TWorldDim >::SCVF::shape_vector().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv1_geom.h