ug4: ug::RegularRefiner_MultiGrid Class Reference
ug::RegularRefiner_MultiGrid Class Reference
#include <regular_refiner_multi_grid.h>
Public Member Functions
virtual bool adaptivity_supported () const
returns whether the refiner is able to perform adaptive refinement
virtual bool coarsening_supported () const
returns true, if the refiner supports coarsening.
virtual Grid * get_associated_grid ()
DEPRECIATED! Use grid(). Has to return the associated grid. Pure virtual.
virtual RefinementMark get_mark (Vertex *v)
Returns the mark of a given element. Default returns RM_REFINE.
virtual RefinementMark get_mark (Edge *e)
Returns the mark of a given element. Default returns RM_REFINE.
virtual RefinementMark get_mark (Face *f)
Returns the mark of a given element. Default returns RM_REFINE.
virtual RefinementMark get_mark (Volume *v)
Returns the mark of a given element. Default returns RM_REFINE.
virtual Grid * grid ()
Returns the grid associated with the refiner.
template<class TElem >
bool is_closure (TElem *elem)
virtual bool mark (Vertex *v, RefinementMark refMark=RM_REFINE)
Marks a element for refinement. Default implementation is empty.
virtual bool mark (Edge *e, RefinementMark refMark=RM_REFINE)
Marks a element for refinement. Default implementation is empty.
virtual bool mark (Face *f, RefinementMark refMark=RM_REFINE)
Marks a element for refinement. Default implementation is empty.
virtual bool mark (Volume *v, RefinementMark refMark=RM_REFINE)
Marks a element for refinement. Default implementation is empty.
virtual void mark_neighborhood (size_t numIterations, RefinementMark refMark, bool sideNbrsOnly)
marks the neighborhood of currently marked elements.
MultiGrid * multi_grid () const
RegularRefiner_MultiGrid ()
RegularRefiner_MultiGrid (MultiGrid *pmg)
virtual bool save_marks_to_file (const char *filename)
Writes the associated grid and marks to a file. Pure virtual.
void set_grid (MultiGrid *pmg)
Public Member Functions inherited from ug::IRefiner
virtual void clear_marks ()
clears all marks. Default implementation is empty
bool coarsen ()
Performs coarsening on the elements marked RM_COARSEN.
bool debugging_enabled () const
void enable_debugging (bool enable)
virtual RefinementMark get_mark (GridObject *o)
returns the mark of the specified geometric object
IRefiner (SPRefinementProjector projector=SPNULL)
virtual bool mark (GridObject *o, RefinementMark refMark=RM_REFINE)
marks the specified geometric object
template<class TIterator >
void mark (const TIterator &iterBegin, const TIterator &iterEnd, RefinementMark refMark=RM_REFINE)
marks all elements between iterBegin and iterEnd.
void mark_neighborhood (size_t numIterations)
marks the neighborhood of currently marked elements.
size_t num_marked_edges (std::vector< int > &numMarkedEdgesOut)
returns the number of (globally) marked edges on all levels of the hierarchy
size_t num_marked_edges ()
returns the number of (globally) marked edges on all levels of the hierarchy
size_t num_marked_elements (std::vector< int > &numMarkedElemsOut)
returns the number of (globally) marked grid-objects of highest dimension
size_t num_marked_elements ()
returns the number of (globally) marked grid-objects of highest dimension
size_t num_marked_faces (std::vector< int > &numMarkedFacesOut)
returns the number of (globally) marked faces on all levels of the hierarchy
size_t num_marked_faces ()
returns the number of (globally) marked faces on all levels of the hierarchy
size_t num_marked_volumes (std::vector< int > &numMarkedVolsOut)
returns the number of (globally) marked volumes on all levels of the hierarchy
size_t num_marked_volumes ()
returns the number of (globally) marked volumes on all levels of the hierarchy
SPRefinementProjector projector ()
void refine ()
Performs refinement on the marked elements.
void set_adjusted_marks_debug_filename (const char *filename)
sets a filename to which adjusted marks are saved during refinement / coarsening
void set_projector (SPRefinementProjector projector)
virtual ~IRefiner ()
void adaption_begins ()
notifies all listeners of the associated message-hub, that adaption begins / ends.
void adaption_ends ()
notifies all listeners of the associated message-hub, that adaption begins / ends.
Protected Types
enum Marks {
NONE = RM_NONE, COPY = RM_COPY, REGULAR = RM_REFINE, ANISOTROPIC = RM_ANISOTROPIC,
LIFT = REGULAR | ANISOTROPIC | COPY
}
Protected Member Functions
template<class TSide >
void adjust_side_of_states (size_t lvl, uint considerSideMarks, uint ignoreElemMarks, RefinementMark newElemMark, bool closure)
template<class TElem >
void adjust_side_states (size_t lvl, uint considerElemMarks, uint ignoreSideMarks, RefinementMark newSideMark, bool closure)
template<class TElem >
void clear_dummies ()
void collect_objects_for_refine ()
template<class TElem >
void copy_state_to_sides (size_t lvl, uint considerElemMarks, bool closure)
template<class TElem >
void mark_by_level_discrepancy (int lvl, Grid::VertexAttachmentAccessor< AInt > aaLvl)
virtual void num_marked_edges_local (std::vector< int > &numMarkedEdgesOut)
returns the number of locally marked edges on all levels of the hierarchy
virtual void num_marked_faces_local (std::vector< int > &numMarkedFacesOut)
returns the number of locally marked faces on all levels of the hierarchy
virtual void num_marked_volumes_local (std::vector< int > &numMarkedVolsOut)
returns the number of locally marked volumes on all levels of the hierarchy
virtual bool perform_coarsening ()
Called by coarsen(). Derived classes sould implement their coarsen algorithm here.
virtual void perform_refinement ()
called by refine(). Derived classes should implement their refinement algorithm here.
bool refinement_is_allowed (Vertex *v)
bool refinement_is_allowed (Edge *e)
bool refinement_is_allowed (Face *f)
bool refinement_is_allowed (Volume *v)
Protected Member Functions inherited from ug::IRefiner
void set_message_hub (SPMessageHub msgHub)
sets the message hub.
Private Member Functions
RegularRefiner_MultiGrid (const RegularRefiner_MultiGrid &)
Private Attributes
MultiElementAttachmentAccessor< AByte > m_aaClosure
ABool m_aClosure
MGSelector m_marks
MultiGrid * m_pMG
Additional Inherited Members
Protected Attributes inherited from ug::IRefiner
bool m_adaptionIsActive
std::string m_adjustedMarksDebugFilename
bool m_debuggingEnabled
SPMessageHub m_messageHub
int m_msgIdAdaption
SPRefinementProjector m_projector
Member Enumeration Documentation
Marks
enum ug::RegularRefiner_MultiGrid::Marks protected
Enumerator
NONE
COPY
REGULAR
ANISOTROPIC
LIFT
Constructor & Destructor Documentation
RegularRefiner_MultiGrid() [1/3]
ug::RegularRefiner_MultiGrid::RegularRefiner_MultiGrid ()
RegularRefiner_MultiGrid() [2/3]
ug::RegularRefiner_MultiGrid::RegularRefiner_MultiGrid (MultiGrid * pmg)
References set_grid().
RegularRefiner_MultiGrid() [3/3]
ug::RegularRefiner_MultiGrid::RegularRefiner_MultiGrid (const RegularRefiner_MultiGrid &) inline private
Member Function Documentation
adaptivity_supported()
bool ug::RegularRefiner_MultiGrid::adaptivity_supported () const virtual
returns whether the refiner is able to perform adaptive refinement
pure virtual!
Implements ug::IRefiner.
References coarsening_supported().
Referenced by grid().
adjust_side_of_states()
template<class TSide > void ug::RegularRefiner_MultiGrid::adjust_side_of_states (size_t lvl, uint considerSideMarks, uint ignoreElemMarks, RefinementMark newElemMark, bool closure) protected
References ug::Grid::associated_elements(), clear_dummies(), end_for, for_each_in_vec, get_mark(), lg_end_for, lg_for_each_in_lvl_template, m_aaClosure, m_marks, m_pMG, refinement_is_allowed(), ug::RM_DUMMY, and ug::ISelector::select().
Referenced by copy_state_to_sides().
adjust_side_states()
template<class TElem > void ug::RegularRefiner_MultiGrid::adjust_side_states (size_t lvl, uint considerElemMarks, uint ignoreSideMarks, RefinementMark newSideMark, bool closure) protected
References ug::Grid::associated_elements(), copy_state_to_sides(), end_for, for_each_in_vec, get_mark(), lg_end_for, lg_for_each_in_lvl_template, m_aaClosure, m_marks, m_pMG, refinement_is_allowed(), ug::RM_DUMMY, and ug::ISelector::select().
Referenced by perform_refinement().
clear_dummies()
template<class TElem > void ug::RegularRefiner_MultiGrid::clear_dummies () protected
References get_mark(), lg_end_for, lg_for_each_in_lvl_template, m_marks, mark(), mark_by_level_discrepancy(), ug::MGSelector::num_levels(), ug::RM_DUMMY, and ug::RM_NONE.
Referenced by adjust_side_of_states().
coarsening_supported()
bool ug::RegularRefiner_MultiGrid::coarsening_supported () const virtual
returns true, if the refiner supports coarsening.
pure virtual!
Implements ug::IRefiner.
References mark().
Referenced by adaptivity_supported().
collect_objects_for_refine()
void ug::RegularRefiner_MultiGrid::collect_objects_for_refine () protected
References ug::Grid::attach_to_vertices(), ug::MultiGrid::begin(), ug::MultiGrid::end(), ug::MultiGrid::get_parent(), lg_end_for, lg_for_each_in_lvl, LIFT, m_marks, m_pMG, ug::MultiGrid::num_levels(), perform_coarsening(), ug::RM_ANISOTROPIC, ug::RM_COPY, ug::RM_DUMMY, ug::ISelector::select(), and ug::SetAttachmentValues().
Referenced by mark_by_level_discrepancy(), and perform_refinement().
copy_state_to_sides()
template<class TElem > void ug::RegularRefiner_MultiGrid::copy_state_to_sides (size_t lvl, uint considerElemMarks, bool closure) protected
References adjust_side_of_states(), ug::Grid::associated_elements(), end_for, for_each_in_vec, get_mark(), lg_end_for, lg_for_each_in_lvl_template, m_aaClosure, m_marks, m_pMG, refinement_is_allowed(), ug::RM_DUMMY, and ug::ISelector::select().
Referenced by adjust_side_states().
get_associated_grid()
Grid * ug::RegularRefiner_MultiGrid::get_associated_grid () virtual
DEPRECIATED! Use grid(). Has to return the associated grid. Pure virtual.
Implements ug::IRefiner.
References grid(), and m_pMG.
Referenced by multi_grid().
get_mark() [1/4]
RefinementMark ug::RegularRefiner_MultiGrid::get_mark (Vertex * v) virtual
Returns the mark of a given element. Default returns RM_REFINE.
Reimplemented from ug::IRefiner.
References ug::ISelector::get_selection_status(), and m_marks.
Referenced by adjust_side_of_states(), adjust_side_states(), clear_dummies(), copy_state_to_sides(), get_mark(), mark_by_level_discrepancy(), and mark_neighborhood().
get_mark() [2/4]
RefinementMark ug::RegularRefiner_MultiGrid::get_mark (Edge * e) virtual
Returns the mark of a given element. Default returns RM_REFINE.
Reimplemented from ug::IRefiner.
References get_mark(), ug::ISelector::get_selection_status(), and m_marks.
get_mark() [3/4]
RefinementMark ug::RegularRefiner_MultiGrid::get_mark (Face * f) virtual
Returns the mark of a given element. Default returns RM_REFINE.
Reimplemented from ug::IRefiner.
References get_mark(), ug::ISelector::get_selection_status(), and m_marks.
get_mark() [4/4]
RefinementMark ug::RegularRefiner_MultiGrid::get_mark (Volume * v) virtual
Returns the mark of a given element. Default returns RM_REFINE.
Reimplemented from ug::IRefiner.
References ug::ISelector::get_selection_status(), m_marks, and save_marks_to_file().
grid()
Grid * ug::RegularRefiner_MultiGrid::grid () virtual
Returns the grid associated with the refiner.
Pure virtual. Specify this method in derived classes!
Implements ug::IRefiner.
References adaptivity_supported(), and m_pMG.
Referenced by get_associated_grid().
is_closure()
template<class TElem > bool ug::RegularRefiner_MultiGrid::is_closure (TElem * elem)
mark() [1/4]
bool ug::RegularRefiner_MultiGrid::mark (Vertex * v, RefinementMark refMark = RM_REFINE) virtual
Marks a element for refinement. Default implementation is empty.
Reimplemented from ug::IRefiner.
References m_marks, and ug::ISelector::select().
Referenced by clear_dummies(), coarsening_supported(), mark(), and mark_by_level_discrepancy().
mark() [2/4]
bool ug::RegularRefiner_MultiGrid::mark (Edge * e, RefinementMark refMark = RM_REFINE) virtual
Marks a element for refinement. Default implementation is empty.
Reimplemented from ug::IRefiner.
References m_marks, mark(), and ug::ISelector::select().
mark() [3/4]
bool ug::RegularRefiner_MultiGrid::mark (Face * f, RefinementMark refMark = RM_REFINE) virtual
Marks a element for refinement. Default implementation is empty.
Reimplemented from ug::IRefiner.
References m_marks, mark(), and ug::ISelector::select().
mark() [4/4]
bool ug::RegularRefiner_MultiGrid::mark (Volume * v, RefinementMark refMark = RM_REFINE) virtual
Marks a element for refinement. Default implementation is empty.
Reimplemented from ug::IRefiner.
References m_marks, mark_neighborhood(), and ug::ISelector::select().
mark_by_level_discrepancy()
template<class TElem > void ug::RegularRefiner_MultiGrid::mark_by_level_discrepancy (int lvl, Grid::VertexAttachmentAccessor< AInt > aaLvl) protected
References ug::Grid::associated_elements(), collect_objects_for_refine(), end_for, for_each_in_vec, get_mark(), lg_end_for, lg_for_each_in_lvl, LIFT, m_marks, m_pMG, mark(), refinement_is_allowed(), and ug::RM_ANISOTROPIC.
Referenced by clear_dummies().
mark_neighborhood()
void ug::RegularRefiner_MultiGrid::mark_neighborhood (size_t numIterations, RefinementMark refMark, bool sideNbrsOnly) virtual
marks the neighborhood of currently marked elements.
In each step direct neighbors of currently marked elements are also marked. You may specify the refinement mark that will be applied to newly mared elements
elements which already were marked will be ignored. By passing RM_NONE as refMark, the refinement-mark will be derived from neighbored elements. If sideNbrsOnly is set to true, only elements which are connected to sides of marked elements are also marked. Otherwise all elements which are connected to vertices of marked elements are marked.
Reimplemented from ug::IRefiner.
References get_mark(), and UG_THROW.
Referenced by mark().
multi_grid()
MultiGrid * ug::RegularRefiner_MultiGrid::multi_grid () const
References get_associated_grid(), and m_pMG.
Referenced by set_grid().
num_marked_edges_local()
void ug::RegularRefiner_MultiGrid::num_marked_edges_local (std::vector< int > & numMarkedEdgesOut) protected virtual
returns the number of locally marked edges on all levels of the hierarchy
Implements ug::IRefiner.
References m_marks, ug::MGSelector::num(), ug::MGSelector::num_levels(), and num_marked_faces_local().
Referenced by perform_coarsening().
num_marked_faces_local()
void ug::RegularRefiner_MultiGrid::num_marked_faces_local (std::vector< int > & numMarkedFacesOut) protected virtual
returns the number of locally marked faces on all levels of the hierarchy
Implements ug::IRefiner.
References m_marks, ug::MGSelector::num(), ug::MGSelector::num_levels(), and num_marked_volumes_local().
Referenced by num_marked_edges_local().
num_marked_volumes_local()
void ug::RegularRefiner_MultiGrid::num_marked_volumes_local (std::vector< int > & numMarkedVolsOut) protected virtual
returns the number of locally marked volumes on all levels of the hierarchy
Implements ug::IRefiner.
References m_marks, ug::MGSelector::num(), ug::MGSelector::num_levels(), and refinement_is_allowed().
Referenced by num_marked_faces_local().
perform_coarsening()
bool ug::RegularRefiner_MultiGrid::perform_coarsening () protected virtual
Called by coarsen(). Derived classes sould implement their coarsen algorithm here.
Since the default implementation does not perform coarsening, it returns false.
Reimplemented from ug::IRefiner.
References num_marked_edges_local().
Referenced by collect_objects_for_refine().
perform_refinement()
void ug::RegularRefiner_MultiGrid::perform_refinement () protected virtual
called by refine(). Derived classes should implement their refinement algorithm here.
Implements ug::IRefiner.
References adjust_side_states(), and collect_objects_for_refine().
Referenced by save_marks_to_file().
refinement_is_allowed() [1/4]
bool ug::RegularRefiner_MultiGrid::refinement_is_allowed (Vertex * v) protected
References ug::MultiGrid::has_children(), and m_pMG.
Referenced by adjust_side_of_states(), adjust_side_states(), copy_state_to_sides(), mark_by_level_discrepancy(), num_marked_volumes_local(), and refinement_is_allowed().
refinement_is_allowed() [2/4]
bool ug::RegularRefiner_MultiGrid::refinement_is_allowed (Edge * e) protected
References ug::MultiGrid::has_children(), m_pMG, and refinement_is_allowed().
refinement_is_allowed() [3/4]
bool ug::RegularRefiner_MultiGrid::refinement_is_allowed (Face * f) protected
References ug::MultiGrid::has_children(), m_pMG, and refinement_is_allowed().
refinement_is_allowed() [4/4]
bool ug::RegularRefiner_MultiGrid::refinement_is_allowed (Volume * v) protected
References ug::MultiGrid::has_children(), and m_pMG.
save_marks_to_file()
bool ug::RegularRefiner_MultiGrid::save_marks_to_file (const char * filename) virtual
Writes the associated grid and marks to a file. Pure virtual.
Elements should be assigned to subsets depending on their current refinement-mark.
Implements ug::IRefiner.
References perform_refinement(), and UG_THROW.
Referenced by get_mark().
set_grid()
void ug::RegularRefiner_MultiGrid::set_grid (MultiGrid * pmg)
References ug::MGSelector::assign_grid(), m_marks, m_pMG, and multi_grid().
Referenced by RegularRefiner_MultiGrid().
Member Data Documentation
m_aaClosure
MultiElementAttachmentAccessor<AByte> ug::RegularRefiner_MultiGrid::m_aaClosure private
Referenced by adjust_side_of_states(), adjust_side_states(), and copy_state_to_sides().
m_aClosure
ABool ug::RegularRefiner_MultiGrid::m_aClosure private
m_marks
MGSelector ug::RegularRefiner_MultiGrid::m_marks private
Referenced by adjust_side_of_states(), adjust_side_states(), clear_dummies(), collect_objects_for_refine(), copy_state_to_sides(), get_mark(), mark(), mark_by_level_discrepancy(), num_marked_edges_local(), num_marked_faces_local(), num_marked_volumes_local(), and set_grid().
m_pMG
MultiGrid* ug::RegularRefiner_MultiGrid::m_pMG private
Referenced by adjust_side_of_states(), adjust_side_states(), collect_objects_for_refine(), copy_state_to_sides(), get_associated_grid(), grid(), mark_by_level_discrepancy(), multi_grid(), refinement_is_allowed(), and set_grid().
The documentation for this class was generated from the following files:
ugbase/lib_grid/refinement/regular_refiner_multi_grid.h
ugbase/lib_grid/refinement/regular_refiner_multi_grid.cpp