ug4: ug::LocalShapeFunctionSet< TDim, TShape, TGrad > Class Template Reference
ug::LocalShapeFunctionSet< TDim, TShape, TGrad > Class Template Reference abstract
lib_discretization » Local Finite Elements
virtual base class for local shape function sets
#include <local_shape_function_set.h>
Public Types
typedef TGrad grad_type
Gradient type.
typedef MathVector< dim > position_type
Domain position type.
typedef TShape shape_type
Shape type.
Public Member Functions
virtual bool continuous () const =0
returns if space constructs continuous functions
virtual void grad (grad_type &g, size_t i, const MathVector< dim > &x) const =0
evaluates the gradient of the shape function
virtual void grads (std::vector< std::vector< grad_type > > &vvGrad, const std::vector< MathVector< dim > > &vLocPos) const =0
returns all gradients evaluated at a several points
virtual void shape (shape_type &shape, size_t i, const MathVector< dim > &x) const =0
evaluates the shape function
virtual shape_type shape (size_t i, const MathVector< dim > &x) const =0
evaluates the shape function
virtual void shapes (std::vector< std::vector< shape_type > > &vvShape, const std::vector< MathVector< dim > > &vLocPos) const =0
returns all shape functions evaluated at several point
virtual ~LocalShapeFunctionSet ()
virtual destructor
virtual void shapes (shape_type *vShape, const MathVector< dim > &x) const =0
returns all shape functions evaluated at a point
virtual void shapes (std::vector< shape_type > &vShape, const MathVector< dim > &x) const =0
returns all shape functions evaluated at a point
virtual void grads (grad_type *vGrad, const MathVector< dim > &x) const =0
returns all gradients evaluated at a point
virtual void grads (std::vector< grad_type > &vGrad, const MathVector< dim > &x) const =0
returns all gradients evaluated at a point
Public Member Functions inherited from ug::DimLocalDoFSet< TDim >
DimLocalDoFSet ()
constructor
virtual bool exact_position_available () const =0
returns if the local dof position are exact
bool operator!= (const DimLocalDoFSet< TDim > &v) const
inequality check
bool operator== (const DimLocalDoFSet< TDim > &v) const
equality check
virtual bool position (size_t i, MathVector< TDim > &pos) const =0
local position of DoF i
Public Member Functions inherited from ug::LocalDoFSet
int dim () const
returns the reference dimension
virtual const LocalDoF & local_dof (size_t dof) const =0
returns the DoFs storage
size_t num_dof (int d, size_t id) const
returns the number of DoFs on a sub-geometric object of dim and id
virtual size_t num_dof (ReferenceObjectID roid) const =0
returns the number of DoFs on a sub-geometric object type
bool operator!= (const LocalDoFSet &v) const
inequality check
bool operator== (const LocalDoFSet &v) const
equality check
virtual ReferenceObjectID roid () const =0
returns the Reference object id of the corresponding grid object
virtual ~LocalDoFSet ()
virtual destructor
size_t num_dof () const
virtual size_t num_sh () const
Static Public Attributes
static const int dim = TDim
Dimension, where shape functions are defined.
Detailed Description
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>>
class ug::LocalShapeFunctionSet< TDim, TShape, TGrad >
virtual base class for local shape function sets
This class is a base class for the supply of local shape functions on finite elements. The class provides evaluation of the shape functions and the gradients at arbitrary points in the interior of a reference element.
Template Parameters
TDim Reference Element Dimension
TShape type of Range of Shape Functions
TGrad type of gradient of shape functions
Member Typedef Documentation
grad_type
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> typedef TGrad ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grad_type
Gradient type.
position_type
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> typedef MathVector<dim> ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::position_type
Domain position type.
shape_type
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> typedef TShape ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shape_type
Shape type.
Constructor & Destructor Documentation
~LocalShapeFunctionSet()
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> virtual ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::~LocalShapeFunctionSet () inline virtual
virtual destructor
Member Function Documentation
continuous()
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> virtual bool ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::continuous () const pure virtual
returns if space constructs continuous functions
Implemented in ug::LocalShapeFunctionSetWrapper< TImpl >.
grad()
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> virtual void ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grad (grad_type & g, size_t i, const MathVector< dim > & x) const pure virtual
evaluates the gradient of the shape function
This function returns the gradient of Shape Function i at an element-local evaluation point.
Parameters
[in] i number of DoF
[in] x Position on reference element (evaluation point)
Returns
gradient at point
grads() [1/3]
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> virtual void ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads (grad_type * vGrad, const MathVector< dim > & x) const pure virtual
returns all gradients evaluated at a point
This function returns the gradients of all Shape Functions at an element-local evaluation point in an array.
Parameters
[out] vGrad Vector of gradients
[in] x Position on reference element (evaluation point)
Referenced by ug::ComputeGradientCrouzeixRaviart(), ug::ComputeGradientLagrange1(), ug::GridFunctionGradientData< TGridFunction >::eval_and_deriv(), ug::GradientDataExport< dim >::eval_and_deriv(), ug::GridFunctionGradientComponentData< TGridFunction >::eval_and_deriv(), ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate(), ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate(), ug::ExplicitGridFunctionGradient< TGridFunction >::evaluate(), ug::H1SemiDistIntegrand< TGridFunction >::evaluate(), ug::H1EnergyDistIntegrand< TGridFunction >::evaluate(), ug::H1DistIntegrand< TGridFunction >::evaluate(), ug::H1ErrorIntegrand< TGridFunction >::evaluate(), ug::H1SemiIntegrand< TGridFunction >::evaluate(), ug::H1EnergyIntegrand< TGridFunction >::evaluate(), ug::H1NormIntegrand< TGridFunction >::evaluate(), ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update_boundary_faces(), ug::DimFV1IBGeometry< TDim, TWorldDim >::update_boundary_faces(), ug::DimCRFVGeometry< TDim, TWorldDim >::update_boundary_faces(), ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces(), ug::DimCRFVGeometry< TDim, TWorldDim >::update_hanging(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_local(), ug::DimFVGeometry< TWorldDim, TDim >::update_local(), ug::DimFV1IBGeometry< TDim, TWorldDim >::update_local_data(), and ug::DimCRFVGeometry< TDim, TWorldDim >::update_local_data().
grads() [2/3]
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> virtual void ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads (std::vector< grad_type > & vGrad, const MathVector< dim > & x) const pure virtual
returns all gradients evaluated at a point
This function returns the gradients of all Shape Functions at an element-local evaluation point in an array.
Parameters
[out] vGrad Vector of gradients
[in] x Position on reference element (evaluation point)
grads() [3/3]
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> virtual void ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads (std::vector< std::vector< grad_type > > & vvGrad, const std::vector< MathVector< dim > > & vLocPos) const pure virtual
returns all gradients evaluated at a several points
This function returns the gradients of all Shape Functions at several element-local evaluation point in an array.
Parameters
[out] vvGrad Vector of gradients
[in] vLocPos Vector of Position on reference element
shape() [1/2]
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> virtual void ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shape (shape_type & shape, size_t i, const MathVector< dim > & x) const pure virtual
evaluates the shape function
This function returns the value of Shape Function i at an element-local evaluation point.
Parameters
[out] shape the shape function
[in] i number of DoF
[in] x Position on reference element (evaluation point)
shape() [2/2]
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> virtual shape_type ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shape (size_t i, const MathVector< dim > & x) const pure virtual
evaluates the shape function
This function returns the value of Shape Function i at an element-local evaluation point.
Parameters
[in] i number of DoF
[in] x Position on reference element (evaluation point)
Returns
shape function value at point
Implemented in ug::LocalShapeFunctionSetWrapper< TImpl >.
Referenced by ug::L2DistIntegrand< TGridFunction >::evaluate(), ug::H1SemiDistIntegrand< TGridFunction >::evaluate(), ug::H1EnergyDistIntegrand< TGridFunction >::evaluate(), ug::H1DistIntegrand< TGridFunction >::evaluate(), ug::L2ErrorIntegrand< TGridFunction >::evaluate(), ug::H1ErrorIntegrand< TGridFunction >::evaluate(), ug::L2Integrand< TGridFunction >::evaluate(), ug::H1SemiIntegrand< TGridFunction >::evaluate(), ug::H1EnergyIntegrand< TGridFunction >::evaluate(), ug::H1NormIntegrand< TGridFunction >::evaluate(), and ug::StdFuncIntegrand< TGridFunction >::evaluate().
shapes() [1/3]
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> virtual void ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes (shape_type * vShape, const MathVector< dim > & x) const pure virtual
returns all shape functions evaluated at a point
This function returns the values of all Shape Functions at an element-local evaluation point in an array.
Parameters
[out] vShape Vector of Shapes
[in] x Position on reference element (evaluation point)
Referenced by ug::DirichletBoundary< TDomain, TAlgebra >::adjust_error(), ug::GridFunctionVectorData< TGridFunction >::eval_and_deriv(), ug::VectorDataExport< dim >::eval_and_deriv(), ug::GridFunctionNumberData< TGridFunction >::eval_and_deriv(), ug::ValueDataExport< dim >::eval_and_deriv(), ug::ExplicitGridFunctionVector< TGridFunction >::evaluate(), ug::GlobalGridFunctionNumberData< TGridFunction, elemDim >::evaluate(), ug::ExplicitGridFunctionValue< TGridFunction >::evaluate(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry(), ug::CrouzeixRaviartElemTransfer< TDomain >::prolongate(), ug::StdLagrangeElemTransfer< TDomain >::prolongate(), ug::ProlongateElemwise(), ug::RestrictElemwise(), ug::ShapesAtGlobalPositionElem(), ug::ShapesAtGlobalPositionVertex(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update(), ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update_boundary_faces(), ug::DimFV1IBGeometry< TDim, TWorldDim >::update_boundary_faces(), ug::DimCRFVGeometry< TDim, TWorldDim >::update_boundary_faces(), ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces(), ug::DimCRFVGeometry< TDim, TWorldDim >::update_hanging(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_local(), ug::DimFVGeometry< TWorldDim, TDim >::update_local(), ug::DimFV1IBGeometry< TDim, TWorldDim >::update_local_data(), ug::DimCRFVGeometry< TDim, TWorldDim >::update_local_data(), and ug::VTKOutput< TDim >::write_cell_values_elementwise().
shapes() [2/3]
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> virtual void ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes (std::vector< shape_type > & vShape, const MathVector< dim > & x) const pure virtual
returns all shape functions evaluated at a point
This function returns the values of all Shape Functions at an element-local evaluation point in an array.
Parameters
[out] vShape Vector of Shapes
[in] x Position on reference element (evaluation point)
shapes() [3/3]
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> virtual void ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes (std::vector< std::vector< shape_type > > & vvShape, const std::vector< MathVector< dim > > & vLocPos) const pure virtual
returns all shape functions evaluated at several point
This function returns the values of all Shape Functions at several element-local evaluation point in an array.
Parameters
[out] vvShape Vector of Shapes
[in] vLocPos Vector of Position on reference element
Member Data Documentation
dim
template<int TDim, typename TShape = number, typename TGrad = MathVector<TDim>> const int ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::dim = TDim static
Dimension, where shape functions are defined.
The documentation for this class was generated from the following file:
ugbase/lib_disc/local_finite_element/local_shape_function_set.h