ug4: ug::SubdivisionLoopProjector< TAPosition > Class Template Reference
ug::SubdivisionLoopProjector< TAPosition > Class Template Reference
lib_grid » algorithms » refinement
Refines grids with an extended loop scheme.
#include <loop_subdivision_projectors.h>
Public Member Functions
virtual void consider_as_crease_edge (Grid::edge_traits::callback cbIsCrease)
virtual void new_vertex (Vertex *vrt, Vertex *parent)
called when a new vertex was created from an old vertex.
virtual void new_vertex (Vertex *vrt, Edge *parent)
called when a new vertex was created from an old edge.
virtual void new_vertex (Vertex *vrt, Face *parent)
called when a new vertex was created from an old face.
virtual void new_vertex (Vertex *vrt, Volume *parent)
called when a new vertex was created from an old volume.
SubdivisionLoopProjector ()
SubdivisionLoopProjector (Grid &g, TAPosition &aPos, TAPosition &aTargetPos)
make sure that aPos and aTargetPos are attached to the vertices of the grid.
virtual ~SubdivisionLoopProjector ()
Public Member Functions inherited from ug::RefinementCallbackLinear< TAPosition >
virtual int current_pos (number *coordsOut, Vertex *vrt, int maxCoords)
Gives access to the position of the current vertex.
RefinementCallbackLinear ()
RefinementCallbackLinear (Grid &grid, TAPosition &aPos)
make sure that aPos is attached to the vertices of the grid.
virtual ~RefinementCallbackLinear ()
Public Member Functions inherited from ug::IRefinementCallback
virtual void flat_grid_vertex_encountered (Vertex *vrt)
callback for vertices in flat grids.
virtual ~IRefinementCallback ()
Protected Member Functions
virtual bool is_crease_edge (Edge *edge)
virtual bool is_crease_vertex (Vertex *vrt)
Protected Member Functions inherited from ug::IRefinementCallback
template<class TAttachmentAccessor >
int current_pos_helper (number *coordsOut, Vertex *vrt, int maxCoords, TAttachmentAccessor &aaPos)
A helper implementation of current_pos available for derived classes.
Protected Attributes
Grid::VertexAttachmentAccessor< TAPosition > m_aaTargetPos
Grid::edge_traits::callback m_cbIsCrease
Protected Attributes inherited from ug::RefinementCallbackLinear< TAPosition >
Grid::VertexAttachmentAccessor< TAPosition > m_aaPos
Grid * m_pGrid
Private Types
typedef RefinementCallbackLinear< TAPosition > BaseClass
typedef TAPosition::ValueType pos_type
Additional Inherited Members
Protected Types inherited from ug::RefinementCallbackLinear< TAPosition >
typedef TAPosition::ValueType pos_type
Detailed Description
template<class TAPosition>
class ug::SubdivisionLoopProjector< TAPosition >
Refines grids with an extended loop scheme.
Inner vertices are positioned using the loop scheme, boundary vertices are positioned using b-spline weights.
Please note that the refiner works on different position attachments: A source and a target position attachment. If you use the refiner in the context of multigrid refinement, you can use the same attachment for both. However, if the callback is used to refine a flat grid, then it's crucial to use different attachments.
Member Typedef Documentation
template<class TAPosition> typedef RefinementCallbackLinear<TAPosition> ug::SubdivisionLoopProjector< TAPosition >::BaseClass private
template<class TAPosition> typedef TAPosition::ValueType ug::SubdivisionLoopProjector< TAPosition >::pos_type private
Constructor & Destructor Documentation
template<class TAPosition > ug::SubdivisionLoopProjector< TAPosition >::SubdivisionLoopProjector ()
Referenced by ug::SubdivisionLoopBoundaryProjector< TAPosition >::is_crease_edge().
template<class TAPosition > ug::SubdivisionLoopProjector< TAPosition >::SubdivisionLoopProjector (Grid & g, TAPosition & aPos, TAPosition & aTargetPos)
make sure that aPos and aTargetPos are attached to the vertices of the grid.
For flat grids it is crucial that aPos and aTargetPos differ. If g is a multigrid, that aPos and aTargetPos can safely be the same.
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::Grid::attach_to_vertices(), ug::Grid::has_vertex_attachment(), ug::SubdivisionLoopProjector< TAPosition >::m_aaTargetPos, and ug::SubdivisionLoopProjector< TAPosition >::~SubdivisionLoopProjector().
template<class TAPosition > ug::SubdivisionLoopProjector< TAPosition >::~SubdivisionLoopProjector () virtual
References ug::SubdivisionLoopProjector< TAPosition >::consider_as_crease_edge().
Referenced by ug::SubdivisionLoopProjector< TAPosition >::SubdivisionLoopProjector().
Member Function Documentation
template<class TAPosition > void ug::SubdivisionLoopProjector< TAPosition >::consider_as_crease_edge (Grid::edge_traits::callback cbIsCrease) virtual
References ug::SubdivisionLoopProjector< TAPosition >::m_cbIsCrease, and ug::SubdivisionLoopProjector< TAPosition >::new_vertex().
Referenced by ug::SubdivisionLoopProjector< TAPosition >::~SubdivisionLoopProjector().
template<class TAPosition > bool ug::SubdivisionLoopProjector< TAPosition >::is_crease_edge (Edge * edge) protected virtual
References ug::SubdivisionLoopProjector< TAPosition >::m_cbIsCrease, ug::RefinementCallbackLinear< TAPosition >::m_pGrid, and ug::NumAssociatedFaces().
Referenced by ug::SubdivisionLoopProjector< TAPosition >::is_crease_vertex(), and ug::SubdivisionLoopProjector< TAPosition >::new_vertex().
template<class TAPosition > bool ug::SubdivisionLoopProjector< TAPosition >::is_crease_vertex (Vertex * vrt) protected virtual
References ug::Grid::associated_elements(), ug::SubdivisionLoopProjector< TAPosition >::is_crease_edge(), ug::IsRegularSurfaceVertex(), ug::SubdivisionLoopProjector< TAPosition >::m_cbIsCrease, ug::RefinementCallbackLinear< TAPosition >::m_pGrid, and ug::PointerConstArray< TPtr >::size().
Referenced by ug::SubdivisionLoopProjector< TAPosition >::new_vertex().
template<class TAPosition > void ug::SubdivisionLoopProjector< TAPosition >::new_vertex (Vertex * vrt, Vertex * parent) virtual
called when a new vertex was created from an old vertex.
Reimplemented from ug::RefinementCallbackLinear< TAPosition >.
References ug::CalculateCenter(), ug::GetConnectedVertex(), ug::SubdivRules_PLoop::inst(), ug::SubdivisionLoopProjector< TAPosition >::is_crease_edge(), ug::SubdivisionLoopProjector< TAPosition >::is_crease_vertex(), ug::IsBoundaryEdge3D(), ug::IsBoundaryVertex3D(), ug::RefinementCallbackLinear< TAPosition >::m_aaPos, ug::SubdivisionLoopProjector< TAPosition >::m_aaTargetPos, ug::RefinementCallbackLinear< TAPosition >::m_pGrid, ug::Grid::num(), ug::SubdivRules_PLoop::ref_even_crease_weights(), ug::SubdivRules_PLoop::ref_even_inner_center_weight(), ug::SubdivRules_PLoop::ref_even_inner_nbr_weight(), ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid(), ug::VecAdd(), ug::VecScaleAdd(), and ug::VecSet().
Referenced by ug::SubdivisionLoopProjector< TAPosition >::consider_as_crease_edge(), and ug::SubdivisionLoopProjector< TAPosition >::new_vertex().
template<class TAPosition > void ug::SubdivisionLoopProjector< TAPosition >::new_vertex (Vertex * vrt, Edge * parent) virtual
called when a new vertex was created from an old edge.
Reimplemented from ug::RefinementCallbackLinear< TAPosition >.
References ug::CalculateCenter(), ug::CollectAssociated(), ug::GetAssociatedFaces(), ug::GetConnectedVertex(), ug::SubdivRules_PLoop::inst(), ug::SubdivisionLoopProjector< TAPosition >::is_crease_edge(), ug::SubdivisionLoopProjector< TAPosition >::is_crease_vertex(), ug::IsBoundaryEdge3D(), ug::IsBoundaryFace3D(), ug::RefinementCallbackLinear< TAPosition >::m_aaPos, ug::SubdivisionLoopProjector< TAPosition >::m_aaTargetPos, ug::RefinementCallbackLinear< TAPosition >::m_pGrid, ug::SubdivisionLoopProjector< TAPosition >::new_vertex(), ug::SubdivRules_PLoop::ref_odd_crease_weights(), ug::SubdivRules_PLoop::ref_odd_inner_weights(), ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid(), ug::VecScaleAdd(), and ug::EdgeVertices::vertex().
template<class TAPosition > void ug::SubdivisionLoopProjector< TAPosition >::new_vertex (Vertex * vrt, Face * parent) virtual
called when a new vertex was created from an old face.
Reimplemented from ug::RefinementCallbackLinear< TAPosition >.
References ug::CalculateCenter(), ug::RefinementCallbackLinear< TAPosition >::m_aaPos, ug::SubdivisionLoopProjector< TAPosition >::m_aaTargetPos, and ug::SubdivisionLoopProjector< TAPosition >::new_vertex().
template<class TAPosition > void ug::SubdivisionLoopProjector< TAPosition >::new_vertex (Vertex * vrt, Volume * parent) virtual
called when a new vertex was created from an old volume.
Reimplemented from ug::RefinementCallbackLinear< TAPosition >.
References ug::CalculateCenter(), ug::SubdivisionLoopProjector< TAPosition >::is_crease_vertex(), ug::RefinementCallbackLinear< TAPosition >::m_aaPos, and ug::SubdivisionLoopProjector< TAPosition >::m_aaTargetPos.
Member Data Documentation
template<class TAPosition> Grid::VertexAttachmentAccessor<TAPosition> ug::SubdivisionLoopProjector< TAPosition >::m_aaTargetPos protected
Referenced by ug::SubdivisionLoopProjector< TAPosition >::new_vertex(), and ug::SubdivisionLoopProjector< TAPosition >::SubdivisionLoopProjector().
template<class TAPosition> Grid::edge_traits::callback ug::SubdivisionLoopProjector< TAPosition >::m_cbIsCrease protected
Referenced by ug::SubdivisionLoopProjector< TAPosition >::consider_as_crease_edge(), ug::SubdivisionLoopProjector< TAPosition >::is_crease_edge(), and ug::SubdivisionLoopProjector< TAPosition >::is_crease_vertex().
The documentation for this class was generated from the following files:
ugbase/lib_grid/algorithms/refinement/refinement_projectors/loop_subdivision_projectors.h
ugbase/lib_grid/algorithms/refinement/refinement_projectors/loop_subdivision_projectors_impl.h