ug4: ug::DimHFV1Geometry< TDim, TWorldDim >::SCV Class Reference
ug::DimHFV1Geometry< TDim, TWorldDim >::SCV Class Reference
#include <hfv1_geom.h>
Public Member Functions
number detJ () const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_corner (size_t co) const
return global corner number i
const MathVector< worldDim > & global_grad (size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector () const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip () const
global integration point
const MathMatrix< worldDim, dim > & JTInv () const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector () const
vector of local gradients in ip point
const MathVector< dim > & local_ip () const
local integration point of scv
size_t node_id () const
node id that this scv is associated to
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shape functions
SCV ()
number shape (size_t sh) const
value of shape function i in integration point
const number * shape_vector () const
vector of shape functions in ip point
number volume () const
volume of scv
Private Types
typedef traits::scv_type scv_type
type of element the subcontrol volume represents
Private Attributes
number detj
MathVector< worldDim > globalGrad [m_maxNSH]
MathMatrix< worldDim, dim > JtInv
MathVector< dim > localGrad [m_maxNSH]
MidID m_midId [m_maxNumCorners]
size_t m_numCorners
MathVector< worldDim > m_vGloPos [m_maxNumCorners]
MathVector< dim > m_vLocPos [m_maxNumCorners]
size_t nodeId
size_t numSH
number vol
number vShape [m_maxNSH]
Static Private Attributes
static const size_t m_maxNumCorners = traits::MaxNumCornersOfSCV
Number of corners of scvf.
static const size_t m_numIP = 1
number of integration points
Friends
class DimHFV1Geometry< TDim, TWorldDim >
Member Typedef Documentation
scv_type
template<int TDim, int TWorldDim = TDim> typedef traits::scv_type ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::scv_type private
type of element the subcontrol volume represents
Constructor & Destructor Documentation
SCV()
template<int TDim, int TWorldDim = TDim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::SCV () inline
Member Function Documentation
detJ()
template<int TDim, int TWorldDim = TDim> number ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::detJ () const inline
Determinant of Jacobian in integration point.
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::detj.
global_corner()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_corner (size_t co) const inline
return global corner number i
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_vGloPos, ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_corners(), and UG_ASSERT.
global_grad()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_grad (size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::globalGrad, ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_sh(), and UG_ASSERT.
global_grad_vector()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_grad_vector () const inline
vector of global gradients in ip point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::globalGrad.
global_ip()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_ip () const inline
global integration point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_vGloPos.
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::update().
JTInv()
template<int TDim, int TWorldDim = TDim> const MathMatrix<worldDim,dim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::JTInv () const inline
Transposed Inverse of Jacobian in integration point.
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::JtInv.
local_corner()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_corner (size_t co) const inline
return local corner number i
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_vLocPos, ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_corners(), and UG_ASSERT.
local_grad()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_grad (size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::localGrad, ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_sh(), and UG_ASSERT.
local_grad_vector()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>* ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_grad_vector () const inline
vector of local gradients in ip point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::localGrad.
local_ip()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_ip () const inline
local integration point of scv
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_vLocPos.
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::update().
node_id()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::node_id () const inline
node id that this scv is associated to
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::nodeId.
num_corners()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_corners () const inline
number of corners, that bound the scvf
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_numCorners.
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::copy_global_corners(), ug::DimHFV1Geometry< TDim, TWorldDim >::copy_local_corners(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_corner(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_corner().
num_ip()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_ip () const inline
number of integration points
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_numIP.
num_sh()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_sh () const inline
number of shape functions
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::numSH.
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_grad(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_grad().
shape()
template<int TDim, int TWorldDim = TDim> number ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::shape (size_t sh) const inline
value of shape function i in integration point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::vShape.
shape_vector()
template<int TDim, int TWorldDim = TDim> const number* ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::shape_vector () const inline
vector of shape functions in ip point
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::vShape.
volume()
template<int TDim, int TWorldDim = TDim> number ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::volume () const inline
volume of scv
References ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::vol.
Friends And Related Function Documentation
DimHFV1Geometry< TDim, TWorldDim >
template<int TDim, int TWorldDim = TDim> friend class DimHFV1Geometry< TDim, TWorldDim > friend
Member Data Documentation
detj
template<int TDim, int TWorldDim = TDim> number ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::detj private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::detJ().
globalGrad
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::globalGrad[m_maxNSH] private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_grad(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_grad_vector().
JtInv
template<int TDim, int TWorldDim = TDim> MathMatrix<worldDim,dim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::JtInv private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::JTInv().
localGrad
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::localGrad[m_maxNSH] private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_grad(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_grad_vector().
m_maxNumCorners
template<int TDim, int TWorldDim = TDim> const size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_maxNumCorners = traits::MaxNumCornersOfSCV static private
Number of corners of scvf.
m_midId
template<int TDim, int TWorldDim = TDim> MidID ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_midId[m_maxNumCorners] private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::copy_global_corners(), and ug::DimHFV1Geometry< TDim, TWorldDim >::copy_local_corners().
m_numCorners
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_numCorners private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_corners().
m_numIP
template<int TDim, int TWorldDim = TDim> const size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_numIP = 1 static private
number of integration points
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_ip().
m_vGloPos
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_vGloPos[m_maxNumCorners] private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::copy_global_corners(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_corner(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_ip().
m_vLocPos
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_vLocPos[m_maxNumCorners] private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::copy_local_corners(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_corner(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_ip().
nodeId
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::nodeId private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::node_id().
numSH
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::numSH private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_sh().
vol
template<int TDim, int TWorldDim = TDim> number ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::vol private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::volume().
vShape
template<int TDim, int TWorldDim = TDim> number ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::vShape[m_maxNSH] private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::shape(), and ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::shape_vector().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/hfv1_geom.h