ug4: ug::VolumeDescriptor Class Reference
ug::VolumeDescriptor Class Reference
Holds a set of vertices which represent the corners of a volume element.
#include <grid_base_objects.h>
Public Member Functions
virtual size_t num_vertices () const
VolumeDescriptor & operator= (const VolumeDescriptor &vv)
VolumeDescriptor & operator= (const VolumeVertices &vv)
void set_num_vertices (uint numVertices)
void set_vertex (uint index, Vertex *vrt)
virtual Vertex * vertex (size_t index) const
virtual ConstVertexArray vertices () const
VolumeDescriptor ()
VolumeDescriptor (const VolumeDescriptor &vd)
VolumeDescriptor (uint numVertices)
virtual ~VolumeDescriptor ()
Public Member Functions inherited from ug::VolumeVertices
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~VolumeVertices ()
Public Member Functions inherited from ug::IVertexGroup
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~IVertexGroup ()
Protected Attributes
uint m_numVertices
Vertex * m_vertices [MAX_VOLUME_VERTICES]
Additional Inherited Members
Public Types inherited from ug::IVertexGroup
typedef Vertex *const * ConstVertexArray
Detailed Description
Holds a set of vertices which represent the corners of a volume element.
Constructor & Destructor Documentation
VolumeDescriptor() [1/3]
ug::VolumeDescriptor::VolumeDescriptor ()
VolumeDescriptor() [2/3]
ug::VolumeDescriptor::VolumeDescriptor (uint numVertices)
References set_num_vertices().
VolumeDescriptor() [3/3]
ug::VolumeDescriptor::VolumeDescriptor (const VolumeDescriptor & vd)
References m_numVertices, and m_vertices.
~VolumeDescriptor()
virtual ug::VolumeDescriptor::~VolumeDescriptor () inline virtual
Member Function Documentation
num_vertices()
virtual size_t ug::VolumeDescriptor::num_vertices () const inline virtual
Reimplemented from ug::VolumeVertices.
Referenced by ug::Grid::assign_grid(), ug::Duplicate(), ug::ExpandFractures3d(), and ug::MergeGrids().
operator=() [1/2]
VolumeDescriptor & ug::VolumeDescriptor::operator= (const VolumeDescriptor & vv)
References m_numVertices, and m_vertices.
operator=() [2/2]
VolumeDescriptor & ug::VolumeDescriptor::operator= (const VolumeVertices & vv)
References m_numVertices, m_vertices, ug::VolumeVertices::num_vertices(), and ug::VolumeVertices::vertex().
set_num_vertices()
void ug::VolumeDescriptor::set_num_vertices (uint numVertices) inline
Referenced by ug::Grid::assign_grid(), ug::CreateVolumesFromElementIndexList(), ug::Duplicate(), ug::ExpandFractures3d(), ug::Tetrahedron::get_flipped_orientation(), ug::Hexahedron::get_flipped_orientation(), ug::Prism::get_flipped_orientation(), ug::Pyramid::get_flipped_orientation(), ug::Octahedron::get_flipped_orientation(), ug::MergeGrids(), ug::MergeVertices(), ug::Grid::replace_vertex(), and VolumeDescriptor().
set_vertex()
void ug::VolumeDescriptor::set_vertex (uint index, Vertex * vrt) inline
Referenced by ug::Grid::assign_grid(), ug::CreateVolumesFromElementIndexList(), ug::Duplicate(), ug::ExpandFractures3d(), ug::Tetrahedron::get_flipped_orientation(), ug::Hexahedron::get_flipped_orientation(), ug::Prism::get_flipped_orientation(), ug::Pyramid::get_flipped_orientation(), ug::Octahedron::get_flipped_orientation(), ug::MergeGrids(), ug::MergeVertices(), ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex(), and ug::Grid::replace_vertex().
vertex()
virtual Vertex* ug::VolumeDescriptor::vertex (size_t index) const inline virtual
Reimplemented from ug::VolumeVertices.
Referenced by ug::Grid::flip_orientation().
vertices()
virtual ConstVertexArray ug::VolumeDescriptor::vertices () const inline virtual
Reimplemented from ug::VolumeVertices.
Member Data Documentation
m_numVertices
uint ug::VolumeDescriptor::m_numVertices protected
Referenced by operator=(), and VolumeDescriptor().
m_vertices
Vertex* ug::VolumeDescriptor::m_vertices[MAX_VOLUME_VERTICES] protected
Referenced by operator=(), and VolumeDescriptor().
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid/grid_base_objects.h
ugbase/lib_grid/grid/grid_base_objects.cpp