ug4: ug::SubsetHandlerSerializer Class Reference
ug::SubsetHandlerSerializer Class Reference
lib_grid » algorithms » serialization
#include <serialization.h>
Public Member Functions
virtual void read_data (BinaryBuffer &in, Vertex *o)
virtual void read_data (BinaryBuffer &in, Edge *o)
virtual void read_data (BinaryBuffer &in, Face *o)
virtual void read_data (BinaryBuffer &in, Volume *o)
virtual void read_info (BinaryBuffer &in)
Read the info written during write_info here. Default: empty implementation.
SubsetHandlerSerializer (ISubsetHandler &sh)
virtual void write_data (BinaryBuffer &out, Vertex *o) const
virtual void write_data (BinaryBuffer &out, Edge *o) const
virtual void write_data (BinaryBuffer &out, Face *o) const
virtual void write_data (BinaryBuffer &out, Volume *o) const
virtual void write_info (BinaryBuffer &out) const
writes subset-infos to the stream (subset names and colors)
Public Member Functions inherited from ug::GridDataSerializer
virtual void deserialization_done ()
this method is called after read_info has been called for all geometric objects.
virtual void deserialization_starts ()
this method is called after read_info has been called for all geometric objects.
virtual ~GridDataSerializer ()
Static Public Member Functions
static SPGridDataSerializer create (ISubsetHandler &sh)
Private Attributes
ISubsetHandler & m_sh
Constructor & Destructor Documentation
ug::SubsetHandlerSerializer::SubsetHandlerSerializer (ISubsetHandler & sh)
References write_info().
Member Function Documentation
static SPGridDataSerializer ug::SubsetHandlerSerializer::create (ISubsetHandler & sh) inline static
References ug::GeomObjDataSerializer< TGeomObj >::read_data(), ug::GeomObjDataSerializer< TGeomObj >::read_info(), ug::GeomObjDataSerializer< TGeomObj >::write_data(), and ug::GeomObjDataSerializer< TGeomObj >::write_info().
Referenced by ug::DistributeDomain(), and ug::DomainLoadBalancer< TDomain >::DomainLoadBalancer().
void ug::SubsetHandlerSerializer::read_data (BinaryBuffer & in, Vertex * o) virtual
Reimplemented from ug::GridDataSerializer.
References ug::ISubsetHandler::assign_subset(), ug::Deserialize(), and m_sh.
Referenced by read_data(), and write_data().
void ug::SubsetHandlerSerializer::read_data (BinaryBuffer & in, Edge * o) virtual
Reimplemented from ug::GridDataSerializer.
References ug::ISubsetHandler::assign_subset(), ug::Deserialize(), m_sh, and read_data().
void ug::SubsetHandlerSerializer::read_data (BinaryBuffer & in, Face * o) virtual
Reimplemented from ug::GridDataSerializer.
References ug::ISubsetHandler::assign_subset(), ug::Deserialize(), m_sh, and read_data().
void ug::SubsetHandlerSerializer::read_data (BinaryBuffer & in, Volume * o) virtual
Reimplemented from ug::GridDataSerializer.
References ug::ISubsetHandler::assign_subset(), ug::Deserialize(), and m_sh.
void ug::SubsetHandlerSerializer::read_info (BinaryBuffer & in) virtual
Read the info written during write_info here. Default: empty implementation.
Reimplemented from ug::GridDataSerializer.
References ug::SubsetInfo::color, ug::Deserialize(), ug::SubsetInfo::m_propertyMap, m_sh, ug::SubsetInfo::name, ug::ISubsetHandler::subset_info(), and write_data().
Referenced by write_info().
void ug::SubsetHandlerSerializer::write_data (BinaryBuffer & out, Vertex * o) const virtual
Reimplemented from ug::GridDataSerializer.
References ug::ISubsetHandler::get_subset_index(), m_sh, and ug::Serialize().
Referenced by read_info(), and write_data().
void ug::SubsetHandlerSerializer::write_data (BinaryBuffer & out, Edge * o) const virtual
Reimplemented from ug::GridDataSerializer.
References ug::ISubsetHandler::get_subset_index(), m_sh, ug::Serialize(), and write_data().
void ug::SubsetHandlerSerializer::write_data (BinaryBuffer & out, Face * o) const virtual
Reimplemented from ug::GridDataSerializer.
References ug::ISubsetHandler::get_subset_index(), m_sh, ug::Serialize(), and write_data().
void ug::SubsetHandlerSerializer::write_data (BinaryBuffer & out, Volume * o) const virtual
Reimplemented from ug::GridDataSerializer.
References ug::ISubsetHandler::get_subset_index(), m_sh, read_data(), and ug::Serialize().
void ug::SubsetHandlerSerializer::write_info (BinaryBuffer & out) const virtual
writes subset-infos to the stream (subset names and colors)
Reimplemented from ug::GridDataSerializer.
References ug::SubsetInfo::color, ug::SubsetInfo::m_propertyMap, m_sh, ug::SubsetInfo::name, ug::ISubsetHandler::num_subsets(), read_info(), ug::Serialize(), and ug::ISubsetHandler::subset_info().
Referenced by SubsetHandlerSerializer().
Member Data Documentation
ISubsetHandler& ug::SubsetHandlerSerializer::m_sh private
Referenced by read_data(), read_info(), write_data(), and write_info().
The documentation for this class was generated from the following files:
ugbase/lib_grid/algorithms/serialization.h
ugbase/lib_grid/algorithms/serialization.cpp