ug4: ug::DimFV1Geometry< TDim, TWorldDim > Class Template Reference
ug::DimFV1Geometry< TDim, TWorldDim > Class Template Reference
Geometry and shape functions for 1st order Vertex-Centered Finite Volume.
#include <fv1_geom.h>
Classes
class BF
boundary face
class SCV
sub control volume structure
class SCVF
Sub-Control Volume Face structure.
Public Types
typedef traits::scv_type scv_type
type of SubControlVolume
typedef fv1_dim_traits< TDim, TWorldDim > traits
used traits
Public Member Functions
void add_boundary_subset (int subsetIndex)
add subset that is interpreted as boundary subset.
const std::vector< BF > & bf (int si) const
returns reference to vector of boundary faces for subsetIndex
const BF & bf (int si, size_t i) const
returns the boundary face i for subsetIndex
void clear_boundary_subsets ()
reset all boundary subsets
const MathVector< worldDim > * coe_global () const
returns the global coordinates of the center of mass of the element
const MathVector< dim > * coe_local () const
returns the local coordinates of the center of mass of the element
const MathVector< worldDim > * corners () const
get vector of corners for current element
DimFV1Geometry ()
construct object and initialize local values and sizes
GridObject * elem () const
get the element
const MathVector< worldDim > & global_node_position (size_t nodeID) const
return global coords for node ID
const MathVector< dim > & local_node_position (size_t nodeID) const
return local coords for node ID
size_t num_bf () const
number of all boundary faces
size_t num_bf (int si) const
number of boundary faces on subset 'subsetIndex'
size_t num_boundary_subsets ()
number of registered boundary subsets
size_t num_scv () const
number of SubControlVolumes
size_t num_scv_ips () const
returns number of all scv ips
size_t num_scvf () const
number of SubControlVolumeFaces
size_t num_scvf_ips () const
returns number of all scvf ips
size_t num_sh () const
number of shape functions
void remove_boundary_subset (int subsetIndex)
removes subset that is interpreted as boundary subset.
ReferenceObjectID roid () const
returns reference object id
const SCV & scv (size_t i) const
const access to SubControlVolume number i
const MathVector< worldDim > * scv_global_ips () const
returns all ips of scv as they appear in scv loop
const MathVector< dim > * scv_local_ips () const
returns all ips of scv as they appear in scv loop
const SCVF & scvf (size_t i) const
const access to SubControlVolumeFace number i
const MathVector< worldDim > * scvf_global_ips () const
returns all ips of scvf as they appear in scv loop
const MathVector< dim > * scvf_local_ips () const
returns all ips of scvf as they appear in scv loop
void update (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update data for given element
void update_boundary_faces (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update boundary data for given element
void update_local (ReferenceObjectID roid)
update local data
Static Public Attributes
static const int dim = TDim
dimension of reference element
static const size_t maxNSH = traits::maxNSH
max number of shape functions
static const size_t maxNumSCV = traits::maxNumSCV
number of SubControlVolumes
static const size_t maxNumSCVF = traits::maxNumSCVF
max number of SubControlVolumeFaces
static const size_t nip = 1
number of integration points
static const int order = 1
order
static const bool staticLocalData = false
flag indicating if local data may change
static const bool usesHangingNodes = false
Hanging node flag: this Geometry does not support hanging nodes.
static const int worldDim = TWorldDim
dimension of world
Protected Attributes
std::map< int, std::vector< BF > > m_mapVectorBF
std::vector< BF > m_vEmptyVectorBF
MathVector< worldDim > m_vGlobSCV_IP [maxNumSCV]
MathVector< worldDim > m_vGlobSCVF_IP [maxNumSCVF]
MathVector< dim > m_vLocSCV_IP [maxNumSCV]
MathVector< dim > m_vLocSCVF_IP [maxNumSCVF]
Private Attributes
size_t m_nsh
current number of shape functions
size_t m_numSCV
current number of scv
size_t m_numSCVF
current number of scvf
GridObject * m_pElem
pointer to current element
ReferenceObjectID m_roid
current reference object id
SCV m_vSCV [maxNumSCV]
SubControlVolumes.
SCVF m_vSCVF [maxNumSCVF]
SubControlVolumeFaces.
MathVector< worldDim > m_vvGloMid [dim+1][maxMid]
MathVector< dim > m_vvLocMid [dim+1][maxMid]
local and global geom object midpoints for each dimension
Static Private Attributes
static const int maxMid = maxNumSCVF + 1
max number of geometric objects in a dimension
Detailed Description
template<int TDim, int TWorldDim = TDim>
class ug::DimFV1Geometry< TDim, TWorldDim >
Geometry and shape functions for 1st order Vertex-Centered Finite Volume.
Template Parameters
TDim reference element dim
TWorldDim (physical) world dimension
Member Typedef Documentation
scv_type
template<int TDim, int TWorldDim = TDim> typedef traits::scv_type ug::DimFV1Geometry< TDim, TWorldDim >::scv_type
type of SubControlVolume
traits
template<int TDim, int TWorldDim = TDim> typedef fv1_dim_traits<TDim, TWorldDim> ug::DimFV1Geometry< TDim, TWorldDim >::traits
used traits
Constructor & Destructor Documentation
DimFV1Geometry()
template<int TDim, int TWorldDim = TDim> ug::DimFV1Geometry< TDim, TWorldDim >::DimFV1Geometry () inline
construct object and initialize local values and sizes
Member Function Documentation
add_boundary_subset()
template<int TDim, int TWorldDim = TDim> void ug::DimFV1Geometry< TDim, TWorldDim >::add_boundary_subset (int subsetIndex) inline
add subset that is interpreted as boundary subset.
References ug::DimFV1Geometry< TDim, TWorldDim >::m_mapVectorBF.
Referenced by ug::IntegralNormalComponentOnManifoldUsingFV1Geom(), ug::IntegrateNormalComponentOnManifold(), and ug::IntegrateNormalGradientOnManifold().
bf() [1/2]
template<int TDim, int TWorldDim = TDim> const std::vector<BF>& ug::DimFV1Geometry< TDim, TWorldDim >::bf (int si) const inline
returns reference to vector of boundary faces for subsetIndex
References ug::DimFV1Geometry< TDim, TWorldDim >::m_mapVectorBF, and ug::DimFV1Geometry< TDim, TWorldDim >::m_vEmptyVectorBF.
bf() [2/2]
template<int TDim, int TWorldDim = TDim> const BF& ug::DimFV1Geometry< TDim, TWorldDim >::bf (int si, size_t i) const inline
returns the boundary face i for subsetIndex
References ug::DimFV1Geometry< TDim, TWorldDim >::m_mapVectorBF, and UG_THROW.
Referenced by ug::IntegralNormalComponentOnManifoldUsingFV1Geom(), ug::IntegrateNormalComponentOnManifold(), and ug::IntegrateNormalGradientOnManifold().
clear_boundary_subsets()
template<int TDim, int TWorldDim = TDim> void ug::DimFV1Geometry< TDim, TWorldDim >::clear_boundary_subsets () inline
reset all boundary subsets
References ug::DimFV1Geometry< TDim, TWorldDim >::m_mapVectorBF.
coe_global()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimFV1Geometry< TDim, TWorldDim >::coe_global () const inline
returns the global coordinates of the center of mass of the element
References ug::DimFV1Geometry< TDim, TWorldDim >::dim, and ug::DimFV1Geometry< TDim, TWorldDim >::m_vvGloMid.
coe_local()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>* ug::DimFV1Geometry< TDim, TWorldDim >::coe_local () const inline
returns the local coordinates of the center of mass of the element
References ug::DimFV1Geometry< TDim, TWorldDim >::dim, and ug::DimFV1Geometry< TDim, TWorldDim >::m_vvLocMid.
corners()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimFV1Geometry< TDim, TWorldDim >::corners () const inline
get vector of corners for current element
References ug::DimFV1Geometry< TDim, TWorldDim >::m_vvGloMid.
elem()
template<int TDim, int TWorldDim = TDim> GridObject* ug::DimFV1Geometry< TDim, TWorldDim >::elem () const inline
get the element
References ug::DimFV1Geometry< TDim, TWorldDim >::m_pElem.
global_node_position()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimFV1Geometry< TDim, TWorldDim >::global_node_position (size_t nodeID) const inline
return global coords for node ID
References ug::DimFV1Geometry< TDim, TWorldDim >::m_vvGloMid, ug::DimFV1Geometry< TDim, TWorldDim >::maxMid, and UG_ASSERT.
local_node_position()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimFV1Geometry< TDim, TWorldDim >::local_node_position (size_t nodeID) const inline
return local coords for node ID
References ug::DimFV1Geometry< TDim, TWorldDim >::m_vvLocMid, ug::DimFV1Geometry< TDim, TWorldDim >::maxMid, and UG_ASSERT.
num_bf() [1/2]
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1Geometry< TDim, TWorldDim >::num_bf () const inline
number of all boundary faces
References ug::DimFV1Geometry< TDim, TWorldDim >::m_mapVectorBF.
num_bf() [2/2]
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1Geometry< TDim, TWorldDim >::num_bf (int si) const inline
number of boundary faces on subset 'subsetIndex'
References ug::DimFV1Geometry< TDim, TWorldDim >::m_mapVectorBF.
num_boundary_subsets()
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1Geometry< TDim, TWorldDim >::num_boundary_subsets () inline
number of registered boundary subsets
References ug::DimFV1Geometry< TDim, TWorldDim >::m_mapVectorBF.
num_scv()
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1Geometry< TDim, TWorldDim >::num_scv () const inline
number of SubControlVolumes
References ug::DimFV1Geometry< TDim, TWorldDim >::m_numSCV.
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::scv().
num_scv_ips()
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1Geometry< TDim, TWorldDim >::num_scv_ips () const inline
returns number of all scv ips
References ug::DimFV1Geometry< TDim, TWorldDim >::m_numSCV.
num_scvf()
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1Geometry< TDim, TWorldDim >::num_scvf () const inline
number of SubControlVolumeFaces
References ug::DimFV1Geometry< TDim, TWorldDim >::m_numSCVF.
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::scvf().
num_scvf_ips()
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1Geometry< TDim, TWorldDim >::num_scvf_ips () const inline
returns number of all scvf ips
References ug::DimFV1Geometry< TDim, TWorldDim >::m_numSCVF.
num_sh()
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1Geometry< TDim, TWorldDim >::num_sh () const inline
number of shape functions
References ug::DimFV1Geometry< TDim, TWorldDim >::m_nsh.
remove_boundary_subset()
template<int TDim, int TWorldDim = TDim> void ug::DimFV1Geometry< TDim, TWorldDim >::remove_boundary_subset (int subsetIndex) inline
removes subset that is interpreted as boundary subset.
References ug::DimFV1Geometry< TDim, TWorldDim >::m_mapVectorBF.
roid()
template<int TDim, int TWorldDim = TDim> ReferenceObjectID ug::DimFV1Geometry< TDim, TWorldDim >::roid () const inline
returns reference object id
References ug::DimFV1Geometry< TDim, TWorldDim >::m_roid.
scv()
template<int TDim, int TWorldDim = TDim> const SCV& ug::DimFV1Geometry< TDim, TWorldDim >::scv (size_t i) const inline
const access to SubControlVolume number i
References ug::DimFV1Geometry< TDim, TWorldDim >::m_vSCV, ug::DimFV1Geometry< TDim, TWorldDim >::num_scv(), and UG_ASSERT.
scv_global_ips()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimFV1Geometry< TDim, TWorldDim >::scv_global_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::DimFV1Geometry< TDim, TWorldDim >::m_roid, ug::DimFV1Geometry< TDim, TWorldDim >::m_vGlobSCV_IP, ug::DimFV1Geometry< TDim, TWorldDim >::m_vvGloMid, ug::ROID_OCTAHEDRON, and ug::ROID_PYRAMID.
scv_local_ips()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>* ug::DimFV1Geometry< TDim, TWorldDim >::scv_local_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::DimFV1Geometry< TDim, TWorldDim >::m_roid, ug::DimFV1Geometry< TDim, TWorldDim >::m_vLocSCV_IP, ug::DimFV1Geometry< TDim, TWorldDim >::m_vvLocMid, ug::ROID_OCTAHEDRON, and ug::ROID_PYRAMID.
scvf()
template<int TDim, int TWorldDim = TDim> const SCVF& ug::DimFV1Geometry< TDim, TWorldDim >::scvf (size_t i) const inline
const access to SubControlVolumeFace number i
References ug::DimFV1Geometry< TDim, TWorldDim >::m_vSCVF, ug::DimFV1Geometry< TDim, TWorldDim >::num_scvf(), and UG_ASSERT.
scvf_global_ips()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimFV1Geometry< TDim, TWorldDim >::scvf_global_ips () const inline
returns all ips of scvf as they appear in scv loop
References ug::DimFV1Geometry< TDim, TWorldDim >::m_vGlobSCVF_IP.
scvf_local_ips()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>* ug::DimFV1Geometry< TDim, TWorldDim >::scvf_local_ips () const inline
returns all ips of scvf as they appear in scv loop
References ug::DimFV1Geometry< TDim, TWorldDim >::m_vLocSCVF_IP.
update()
template<int TDim, int TWorldDim> void ug::DimFV1Geometry< TDim, TWorldDim >::update (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update data for given element
References ug::AveragePositions(), ug::DimReferenceMapping< TDim, TWorldDim >::is_linear(), ug::DimReferenceMapping< TDim, TWorldDim >::jacobian_transposed_inverse(), ug::MatVecMult(), ug::ReferenceElement::num(), ug::GridObject::reference_object_id(), ug::ROID_OCTAHEDRON, ug::ROID_PYRAMID, ug::DimReferenceMapping< TDim, TWorldDim >::sqrt_gram_det(), UG_CATCH_THROW, and ug::DimReferenceMapping< TDim, TWorldDim >::update().
Referenced by ug::IntegralNormalComponentOnManifoldUsingFV1Geom(), ug::IntegrateNormalComponentOnManifold(), and ug::IntegrateNormalGradientOnManifold().
update_boundary_faces()
template<int TDim, int TWorldDim> void ug::DimFV1Geometry< TDim, TWorldDim >::update_boundary_faces (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update boundary data for given element
References ug::AveragePositions(), ug::CollectEdgesSorted(), ug::CollectFacesSorted(), ug::CollectVertices(), ug::ComputeBFMidID(), ug::DimFV1Geometry< TDim, TWorldDim >::BF::detj, dim, ug::ISubsetHandler::get_subset_index(), ug::DimFV1Geometry< TDim, TWorldDim >::BF::globalIP, ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::ISubsetHandler::grid(), ug::ReferenceElement::id(), ug::DimReferenceMapping< TDim, TWorldDim >::jacobian_transposed_inverse(), ug::DimFV1Geometry< TDim, TWorldDim >::BF::JtInv, ug::LFEID::LAGRANGE, ug::DimFV1Geometry< TDim, TWorldDim >::BF::localIP, ug::MatVecMult(), ug::DimFV1Geometry< TDim, TWorldDim >::BF::nodeId, ug::DimFV1Geometry< TDim, TWorldDim >::BF::Normal, ug::ReferenceElement::num(), ug::LocalDoFSet::num_sh(), ug::DimFV1Geometry< TDim, TWorldDim >::BF::num_sh(), ug::DimFV1Geometry< TDim, TWorldDim >::BF::numSH, ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), ug::DimReferenceMapping< TDim, TWorldDim >::sqrt_gram_det(), UG_CATCH_THROW, ug::DimReferenceMapping< TDim, TWorldDim >::update(), ug::VecTwoNorm(), ug::DimFV1Geometry< TDim, TWorldDim >::BF::vGlobalGrad, ug::DimFV1Geometry< TDim, TWorldDim >::BF::vGloPos, ug::DimFV1Geometry< TDim, TWorldDim >::BF::vLocalGrad, ug::DimFV1Geometry< TDim, TWorldDim >::BF::vLocPos, ug::DimFV1Geometry< TDim, TWorldDim >::BF::vMidID, ug::DimFV1Geometry< TDim, TWorldDim >::BF::Vol, and ug::DimFV1Geometry< TDim, TWorldDim >::BF::vShape.
update_local()
template<int TDim, int TWorldDim> void ug::DimFV1Geometry< TDim, TWorldDim >::update_local (ReferenceObjectID roid)
update local data
References ug::AveragePositions(), ug::ComputeSCVFMidID(), ug::ComputeSCVMidID(), ug::DimReferenceElement< d >::corner(), dim, ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::LFEID::LAGRANGE, ug::ReferenceElement::num(), ug::LocalDoFSet::num_sh(), ug::ROID_OCTAHEDRON, ug::ROID_PYRAMID, ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), and UG_CATCH_THROW.
Member Data Documentation
dim
template<int TDim, int TWorldDim = TDim> const int ug::DimFV1Geometry< TDim, TWorldDim >::dim = TDim static
dimension of reference element
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::coe_global(), and ug::DimFV1Geometry< TDim, TWorldDim >::coe_local().
m_mapVectorBF
template<int TDim, int TWorldDim = TDim> std::map<int, std::vector<BF> > ug::DimFV1Geometry< TDim, TWorldDim >::m_mapVectorBF protected
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::add_boundary_subset(), ug::DimFV1Geometry< TDim, TWorldDim >::bf(), ug::DimFV1Geometry< TDim, TWorldDim >::clear_boundary_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::num_bf(), ug::DimFV1Geometry< TDim, TWorldDim >::num_boundary_subsets(), and ug::DimFV1Geometry< TDim, TWorldDim >::remove_boundary_subset().
m_nsh
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1Geometry< TDim, TWorldDim >::m_nsh private
current number of shape functions
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::num_sh().
m_numSCV
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1Geometry< TDim, TWorldDim >::m_numSCV private
current number of scv
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::num_scv(), and ug::DimFV1Geometry< TDim, TWorldDim >::num_scv_ips().
m_numSCVF
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1Geometry< TDim, TWorldDim >::m_numSCVF private
current number of scvf
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::num_scvf(), and ug::DimFV1Geometry< TDim, TWorldDim >::num_scvf_ips().
m_pElem
template<int TDim, int TWorldDim = TDim> GridObject* ug::DimFV1Geometry< TDim, TWorldDim >::m_pElem private
pointer to current element
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::elem().
m_roid
template<int TDim, int TWorldDim = TDim> ReferenceObjectID ug::DimFV1Geometry< TDim, TWorldDim >::m_roid private
current reference object id
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::roid(), ug::DimFV1Geometry< TDim, TWorldDim >::scv_global_ips(), and ug::DimFV1Geometry< TDim, TWorldDim >::scv_local_ips().
m_vEmptyVectorBF
template<int TDim, int TWorldDim = TDim> std::vector<BF> ug::DimFV1Geometry< TDim, TWorldDim >::m_vEmptyVectorBF protected
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::bf().
m_vGlobSCV_IP
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimFV1Geometry< TDim, TWorldDim >::m_vGlobSCV_IP[maxNumSCV] protected
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::scv_global_ips().
m_vGlobSCVF_IP
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimFV1Geometry< TDim, TWorldDim >::m_vGlobSCVF_IP[maxNumSCVF] protected
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::scvf_global_ips().
m_vLocSCV_IP
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimFV1Geometry< TDim, TWorldDim >::m_vLocSCV_IP[maxNumSCV] protected
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::scv_local_ips().
m_vLocSCVF_IP
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimFV1Geometry< TDim, TWorldDim >::m_vLocSCVF_IP[maxNumSCVF] protected
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::scvf_local_ips().
m_vSCV
template<int TDim, int TWorldDim = TDim> SCV ug::DimFV1Geometry< TDim, TWorldDim >::m_vSCV[maxNumSCV] private
SubControlVolumes.
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::scv().
m_vSCVF
template<int TDim, int TWorldDim = TDim> SCVF ug::DimFV1Geometry< TDim, TWorldDim >::m_vSCVF[maxNumSCVF] private
SubControlVolumeFaces.
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::scvf().
m_vvGloMid
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimFV1Geometry< TDim, TWorldDim >::m_vvGloMid[dim+1][maxMid] private
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::coe_global(), ug::DimFV1Geometry< TDim, TWorldDim >::corners(), ug::DimFV1Geometry< TDim, TWorldDim >::global_node_position(), and ug::DimFV1Geometry< TDim, TWorldDim >::scv_global_ips().
m_vvLocMid
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimFV1Geometry< TDim, TWorldDim >::m_vvLocMid[dim+1][maxMid] private
local and global geom object midpoints for each dimension
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::coe_local(), ug::DimFV1Geometry< TDim, TWorldDim >::local_node_position(), and ug::DimFV1Geometry< TDim, TWorldDim >::scv_local_ips().
maxMid
template<int TDim, int TWorldDim = TDim> const int ug::DimFV1Geometry< TDim, TWorldDim >::maxMid = maxNumSCVF + 1 static private
max number of geometric objects in a dimension
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::global_node_position(), and ug::DimFV1Geometry< TDim, TWorldDim >::local_node_position().
maxNSH
template<int TDim, int TWorldDim = TDim> const size_t ug::DimFV1Geometry< TDim, TWorldDim >::maxNSH = traits::maxNSH static
max number of shape functions
maxNumSCV
template<int TDim, int TWorldDim = TDim> const size_t ug::DimFV1Geometry< TDim, TWorldDim >::maxNumSCV = traits::maxNumSCV static
number of SubControlVolumes
maxNumSCVF
template<int TDim, int TWorldDim = TDim> const size_t ug::DimFV1Geometry< TDim, TWorldDim >::maxNumSCVF = traits::maxNumSCVF static
max number of SubControlVolumeFaces
nip
template<int TDim, int TWorldDim = TDim> const size_t ug::DimFV1Geometry< TDim, TWorldDim >::nip = 1 static
number of integration points
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::num_ip(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::num_ip(), and ug::DimFV1Geometry< TDim, TWorldDim >::BF::num_ip().
order
template<int TDim, int TWorldDim = TDim> const int ug::DimFV1Geometry< TDim, TWorldDim >::order = 1 static
order
staticLocalData
template<int TDim, int TWorldDim = TDim> const bool ug::DimFV1Geometry< TDim, TWorldDim >::staticLocalData = false static
flag indicating if local data may change
usesHangingNodes
template<int TDim, int TWorldDim = TDim> const bool ug::DimFV1Geometry< TDim, TWorldDim >::usesHangingNodes = false static
Hanging node flag: this Geometry does not support hanging nodes.
worldDim
template<int TDim, int TWorldDim = TDim> const int ug::DimFV1Geometry< TDim, TWorldDim >::worldDim = TWorldDim static
dimension of world
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/fv1_geom.h
ugbase/lib_disc/spatial_disc/disc_util/fv1_geom.cpp