ug4: ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF Class Reference
ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF Class Reference
#include <fv1_geom.h>
Public Member Functions
BF ()
const MathVector< worldDim > & global_corner (size_t i) const
return global position of corner number i
const MathVector< worldDim > & global_ip () const
global integration point
const MathVector< dim > & local_corner (size_t i) const
return local position of corner number i
const MathVector< dim > & local_ip () const
local integration point of bf
size_t node_id () const
node id that this bf is associated to
size_t num_corners () const
number of corners, that bound the bf
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shape functions
number shape (size_t i, size_t ip) const
value of shape function i in integration point
number volume () const
volume of bf
Private Attributes
MidID midId [numCorners]
size_t nodeId
MathVector< worldDim > vGloPos [numCorners]
MathVector< dim > vLocPos [numCorners]
number vol
std::vector< number > vShape
Static Private Attributes
static const size_t m_numIP = 1
static const size_t numCorners = fv1_traits<ref_elem_type, dim>::NumCornersOfSCV
Friends
class FV1ManifoldGeometry< TElem, TWorldDim >
Constructor & Destructor Documentation
BF()
template<typename TElem , int TWorldDim> ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::BF () inline
Member Function Documentation
global_corner()
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::global_corner (size_t i) const inline
return global position of corner number i
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::num_corners(), UG_ASSERT, and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vGloPos.
global_ip()
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::global_ip () const inline
global integration point
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vGloPos.
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::update().
local_corner()
template<typename TElem , int TWorldDim> const MathVector<dim>& ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::local_corner (size_t i) const inline
return local position of corner number i
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::num_corners(), UG_ASSERT, and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vLocPos.
local_ip()
template<typename TElem , int TWorldDim> const MathVector<dim>& ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::local_ip () const inline
local integration point of bf
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vLocPos.
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry().
node_id()
template<typename TElem , int TWorldDim> size_t ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::node_id () const inline
node id that this bf is associated to
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::nodeId.
num_corners()
template<typename TElem , int TWorldDim> size_t ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::num_corners () const inline
number of corners, that bound the bf
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::numCorners.
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_global_corners(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_local_corners(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::global_corner(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::local_corner().
num_ip()
template<typename TElem , int TWorldDim> size_t ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::num_ip () const inline
number of integration points
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::m_numIP.
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::shape().
num_sh()
template<typename TElem , int TWorldDim> size_t ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::num_sh () const inline
number of shape functions
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vShape.
shape()
template<typename TElem , int TWorldDim> number ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::shape (size_t i, size_t ip) const inline
value of shape function i in integration point
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::num_ip(), UG_ASSERT, and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vShape.
volume()
template<typename TElem , int TWorldDim> number ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::volume () const inline
volume of bf
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vol.
Friends And Related Function Documentation
FV1ManifoldGeometry< TElem, TWorldDim >
template<typename TElem , int TWorldDim> friend class FV1ManifoldGeometry< TElem, TWorldDim > friend
Member Data Documentation
m_numIP
template<typename TElem , int TWorldDim> const size_t ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::m_numIP = 1 static private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::num_ip().
midId
template<typename TElem , int TWorldDim> MidID ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::midId[numCorners] private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_global_corners(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_local_corners(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry().
nodeId
template<typename TElem , int TWorldDim> size_t ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::nodeId private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::node_id().
numCorners
template<typename TElem , int TWorldDim> const size_t ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::numCorners = fv1_traits<ref_elem_type, dim>::NumCornersOfSCV static private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::num_corners().
vGloPos
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vGloPos[numCorners] private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_global_corners(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::global_corner(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::global_ip().
vLocPos
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vLocPos[numCorners] private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_local_corners(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::local_corner(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::local_ip().
vol
template<typename TElem , int TWorldDim> number ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vol private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::volume().
vShape
template<typename TElem , int TWorldDim> std::vector<number> ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vShape private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::num_sh(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::shape().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv1_geom.h