ug4: ug::ValueIndicatorUserData< TDomain > Class Template Reference
ug::ValueIndicatorUserData< TDomain > Class Template Reference
"Heaviside step function" based on the value of values of a further userdata
#include <subset_indicator_user_data.h>
Public Member Functions
virtual bool continuous () const
Indicator functions are discontinuous.
template<int refDim>
void evaluate (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
Evaluator.
void operator() (number &vValue, const MathVector< dim > &globIP, number time, int si) const
This function should not be used.
void operator() (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
This function should not be used.
virtual bool requires_grid_fct () const
Returns true to get the grid element in the evaluation routine.
ValueIndicatorUserData (SmartPtr< UserData< number, dim, void > > spData, number threshold, bool greater)
constructor
Public Member Functions inherited from ug::StdUserData< ValueIndicatorUserData< TDomain >, number, TDomain::dim, void, UserData< number, TDomain::dim, void > >
virtual void operator() (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
Public Member Functions inherited from ug::UserData< TData, dim, TRet >
int get_dim () const
returns dimension
virtual TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const =0
returns value for a global position
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, Vertex *vrt) const
returns a value at a vertex
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const =0
returns values for global positions
std::string type () const
returns type of data as string (e.g. "Number", "Vector", "Matrix")
TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const =0
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
Function Group of functions.
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
sets the function pattern for a possibly needed grid function
virtual ~UserDataInfo ()
virtual destructor
Private Types
typedef TDomain domain_type
the domain type
typedef TDomain::grid_type grid_type
the grid type
Private Member Functions
void reset_values (number vValue[], const size_t nip) const
Private Attributes
bool m_greater
if less or greater
SmartPtr< UserData< number, dim, void > > m_spData
the original data
number m_threshold
the threshold value
Static Private Attributes
static const int dim = TDomain::dim
the world dimension
Additional Inherited Members
Public Types inherited from ug::UserData< TData, dim, TRet >
typedef TData data_type
typedef TRet return_type
Protected Member Functions inherited from ug::StdUserData< ValueIndicatorUserData< TDomain >, number, TDomain::dim, void, UserData< number, TDomain::dim, void > >
ValueIndicatorUserData< TDomain > & getImpl ()
access to implementation
const ValueIndicatorUserData< TDomain > & getImpl () const
const access to implementation
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Detailed Description
template<typename TDomain>
class ug::ValueIndicatorUserData< TDomain >
"Heaviside step function" based on the value of values of a further userdata
This class implements the UserData that returns 1 if the given user data is greater/less or equal than a given value.
Member Typedef Documentation
domain_type
template<typename TDomain > typedef TDomain ug::ValueIndicatorUserData< TDomain >::domain_type private
the domain type
grid_type
template<typename TDomain > typedef TDomain::grid_type ug::ValueIndicatorUserData< TDomain >::grid_type private
the grid type
Constructor & Destructor Documentation
ValueIndicatorUserData()
template<typename TDomain > ug::ValueIndicatorUserData< TDomain >::ValueIndicatorUserData (SmartPtr< UserData< number, dim, void > > spData, number threshold, bool greater) inline
constructor
Parameters
spData the original data
threshold the threshold value
greater if greater or less
References ug::ValueIndicatorUserData< TDomain >::m_spData, and UG_THROW.
Member Function Documentation
continuous()
template<typename TDomain > virtual bool ug::ValueIndicatorUserData< TDomain >::continuous () const inline virtual
Indicator functions are discontinuous.
Implements ug::UserData< TData, dim, TRet >.
References ug::ValueIndicatorUserData< TDomain >::m_spData.
evaluate()
template<typename TDomain > template<int refDim> void ug::ValueIndicatorUserData< TDomain >::evaluate (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< refDim, dim > * vJT = NULL) const inline
Evaluator.
References ug::ValueIndicatorUserData< TDomain >::reset_values().
operator()() [1/2]
template<typename TDomain > void ug::ValueIndicatorUserData< TDomain >::operator() (number & vValue, const MathVector< dim > & globIP, number time, int si) const inline virtual
This function should not be used.
Implements ug::StdUserData< ValueIndicatorUserData< TDomain >, number, TDomain::dim, void, UserData< number, TDomain::dim, void > >.
References ug::ValueIndicatorUserData< TDomain >::reset_values().
operator()() [2/2]
template<typename TDomain > void ug::ValueIndicatorUserData< TDomain >::operator() (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const inline virtual
This function should not be used.
Implements ug::StdUserData< ValueIndicatorUserData< TDomain >, number, TDomain::dim, void, UserData< number, TDomain::dim, void > >.
References ug::ValueIndicatorUserData< TDomain >::reset_values().
requires_grid_fct()
template<typename TDomain > virtual bool ug::ValueIndicatorUserData< TDomain >::requires_grid_fct () const inline virtual
Returns true to get the grid element in the evaluation routine.
Implements ug::UserData< TData, dim, TRet >.
References ug::ValueIndicatorUserData< TDomain >::m_spData.
reset_values()
template<typename TDomain > void ug::ValueIndicatorUserData< TDomain >::reset_values (number vValue[], const size_t nip) const inline private
References ug::ValueIndicatorUserData< TDomain >::m_greater, and ug::ValueIndicatorUserData< TDomain >::m_threshold.
Referenced by ug::ValueIndicatorUserData< TDomain >::evaluate(), and ug::ValueIndicatorUserData< TDomain >::operator()().
Member Data Documentation
dim
template<typename TDomain > const int ug::ValueIndicatorUserData< TDomain >::dim = TDomain::dim static private
the world dimension
m_greater
template<typename TDomain > bool ug::ValueIndicatorUserData< TDomain >::m_greater private
if less or greater
Referenced by ug::ValueIndicatorUserData< TDomain >::reset_values().
m_spData
template<typename TDomain > SmartPtr<UserData<number, dim, void> > ug::ValueIndicatorUserData< TDomain >::m_spData private
the original data
Referenced by ug::ValueIndicatorUserData< TDomain >::continuous(), ug::ValueIndicatorUserData< TDomain >::requires_grid_fct(), and ug::ValueIndicatorUserData< TDomain >::ValueIndicatorUserData().
m_threshold
template<typename TDomain > number ug::ValueIndicatorUserData< TDomain >::m_threshold private
the threshold value
Referenced by ug::ValueIndicatorUserData< TDomain >::reset_values().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/user_data/common_user_data/subset_indicator_user_data.h