ug4: ug::MapSparseMatrix< TValueType > Class Template Reference
ug::MapSparseMatrix< TValueType > Class Template Reference
lib_algebra
sparse matrix for big, variable sparse matrices.
#include <mapsparsematrix.h>
Classes
struct connection
class const_row_iterator
class row_iterator
Public Types
enum { rows_sorted =true }
typedef SparseMatrix< value_type > this_type
typedef TValueType value_type
Public Member Functions
template<typename M >
void add (const M &mat)
void add_matrix_row (size_t row, connection *c, size_t nr)
template<typename Vector_type >
bool apply (Vector_type &res, const Vector_type &x) const
calculate res = A x
template<typename Vector_type >
bool apply_transposed (Vector_type &res, const Vector_type &x) const
calculate res = A.T x
template<typename vector_t >
bool axpy (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const vector_t &w1) const
calculate dest = alpha1*v1 + beta1*A*w1 (A = this matrix)
template<typename vector_t >
bool axpy_transposed (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const vector_t &w1) const
calculate dest = alpha1*v1 + beta1*A^T*w1 (A = this matrix)
row_iterator begin_row (size_t r)
const_row_iterator begin_row (size_t r) const
void defragment ()
row_iterator end_row (size_t r)
const_row_iterator end_row (size_t r) const
template<typename M >
void get (M &mat) const
get local matrix
const_row_iterator get_connection (size_t r, size_t c, bool &bFound) const
row_iterator get_connection (size_t r, size_t c, bool &bFound)
const_row_iterator get_connection (size_t r, size_t c) const
row_iterator get_connection (size_t r, size_t c)
bool is_isolated (size_t i) const
check for isolated condition of an index
MapSparseMatrix ()
constructor for empty SparseMatrix
template<typename vector_t >
void mat_mult_add_row (size_t row, typename vector_t::value_type &dest, double alpha, const vector_t &v) const
calculates dest += alpha * A[row, .] v;
template<typename Vector_type >
bool matmul_minus (Vector_type &res, const Vector_type &x) const
calculate res -= A x
size_t num_cols () const
returns the number of cols
size_t num_connections (size_t i) const
returns number of connections of row row.
size_t num_rows () const
returns number of rows
const value_type & operator() (size_t r, size_t c) const
value_type & operator() (size_t r, size_t c)
SparseMatrix< value_type > & operator*= (double d)
SparseMatrix< value_type > & operator= (const SparseMatrix< value_type > &B)
void p () const
void pr (size_t row) const
void print (const char *const name=NULL) const
void print_to_file (const char *filename) const
void printrow (size_t row) const
void printtype () const
bool resize (size_t newRows, size_t newCols)
resizes the SparseMatrix
bool scale (double d)
template<typename M >
void set (const M &mat)
set local matrix
bool set (double a)
set matrix to Id*a
bool set_as_copy_of (const MapSparseMatrix< value_type > &B, double scale=1.0)
create/recreate this as a copy of SparseMatrix B
bool set_as_transpose_of (const SparseMatrix< value_type > &B, double scale=1.0)
write in a empty SparseMatrix (this) the transpose SparseMatrix of B.
void set_matrix_row (size_t row, connection *c, size_t nr)
size_t total_num_connections () const
returns the total number of connections
virtual ~MapSparseMatrix ()
destructor
Protected Attributes
size_t cols
std::vector< std::map< size_t, TValueType > > data
Private Member Functions
MapSparseMatrix (MapSparseMatrix &)
disallow copy operator
Friends
std::ostream & operator<< (std::ostream &out, const MapSparseMatrix &m)
Detailed Description
template<typename TValueType>
class ug::MapSparseMatrix< TValueType >
sparse matrix for big, variable sparse matrices.
SparseMatrix
See also
matrixrow, CreateAsMultiplyOf
Parameters
T blocktype
Member Typedef Documentation
template<typename TValueType> typedef SparseMatrix<value_type> ug::MapSparseMatrix< TValueType >::this_type
template<typename TValueType> typedef TValueType ug::MapSparseMatrix< TValueType >::value_type
Member Enumeration Documentation
template<typename TValueType> anonymous enum
Enumerator
rows_sorted
Constructor & Destructor Documentation
template<typename T > ug::MapSparseMatrix< T >::MapSparseMatrix ()
constructor for empty SparseMatrix
Referenced by ug::MapSparseMatrix< TValueType >::connection::operator<(), and ug::MapSparseMatrix< TValueType >::pr().
template<typename TValueType> virtual ug::MapSparseMatrix< TValueType >::~MapSparseMatrix () inline virtual
destructor
References ug::MapSparseMatrix< TValueType >::resize(), ug::MapSparseMatrix< TValueType >::scale(), ug::MapSparseMatrix< TValueType >::set_as_copy_of(), and ug::MapSparseMatrix< TValueType >::set_as_transpose_of().
template<typename TValueType> ug::MapSparseMatrix< TValueType >::MapSparseMatrix (MapSparseMatrix< TValueType > &) private
disallow copy operator
Member Function Documentation
template<typename TValueType> template<typename M > void ug::MapSparseMatrix< TValueType >::add (const M & mat)
Add a local matrix
The local matrix type must declare the following members:
num_rows()
num_cols()
row_index(size_t i)
col_index(size_t j)
operator()(size_t i, size_t j) so that mat(i,j) will go to SparseMat(mat.row_index(i), mat.col_index(j))
Parameters
mat the whole local matrix type
Referenced by ug::MapSparseMatrix< TValueType >::operator*=().
template<typename T > void ug::MapSparseMatrix< T >::add_matrix_row (size_t row, connection * c, size_t nr)
adds the connections c to the matrixrow row. if c has a connection con with con.iIndex=i, and the matrix already has a connection (row, i), the function will set A(row,i) += con.dValue. otherwise the connection A(row, i) is created and set to con.dValue.
Parameters
row row to add to
c connections ("row") to be added the row.
nr number of connections in array c.
Returns
true on success.
Note
you may use double connections in c.
References ug::MapSparseMatrix< TValueType >::connection::iIndex, and PROFILE_BEGIN_GROUP.
Referenced by ug::MapSparseMatrix< TValueType >::operator()().
template<typename TValueType> template<typename Vector_type > bool ug::MapSparseMatrix< TValueType >::apply (Vector_type & res, const Vector_type & x) const inline
calculate res = A x
References ug::MapSparseMatrix< TValueType >::axpy().
template<typename TValueType> template<typename Vector_type > bool ug::MapSparseMatrix< TValueType >::apply_transposed (Vector_type & res, const Vector_type & x) const inline
calculate res = A.T x
References ug::MapSparseMatrix< TValueType >::axpy_transposed().
template<typename T > template<typename vector_t > bool ug::MapSparseMatrix< T >::axpy (vector_t & dest, const number & alpha1, const vector_t & v1, const number & beta1, const vector_t & w1) const
calculate dest = alpha1*v1 + beta1*A*w1 (A = this matrix)
References begin_row(), end_row(), ug::MapSparseMatrix< TValueType >::const_row_iterator::index(), ug::MatMult(), ug::MatMultAdd(), num_rows(), PROFILE_BEGIN_GROUP, ug::MapSparseMatrix< TValueType >::const_row_iterator::value(), and ug::VecScaleAssign().
Referenced by ug::MapSparseMatrix< TValueType >::apply(), ug::MapSparseMatrix< TValueType >::matmul_minus(), and ug::MapSparseMatrix< TValueType >::operator=().
template<typename T > template<typename vector_t > bool ug::MapSparseMatrix< T >::axpy_transposed (vector_t & dest, const number & alpha1, const vector_t & v1, const number & beta1, const vector_t & w1) const
calculate dest = alpha1*v1 + beta1*A^T*w1 (A = this matrix)
References begin_row(), end_row(), ug::MatMultTransposedAdd(), num_rows(), PROFILE_BEGIN_GROUP, and ug::VecScaleAssign().
Referenced by ug::MapSparseMatrix< TValueType >::apply_transposed(), ug::MatMultTransposedAdd(), and ug::MapSparseMatrix< TValueType >::operator=().
template<typename TValueType> row_iterator ug::MapSparseMatrix< TValueType >::begin_row (size_t r) inline
References ug::MapSparseMatrix< TValueType >::data.
Referenced by ug::MapSparseMatrix< TValueType >::set_as_copy_of().
template<typename TValueType> const_row_iterator ug::MapSparseMatrix< TValueType >::begin_row (size_t r) const inline
References ug::MapSparseMatrix< TValueType >::data.
template<typename TValueType> void ug::MapSparseMatrix< TValueType >::defragment () inline
References ug::MapSparseMatrix< TValueType >::connection::print(), ug::MapSparseMatrix< TValueType >::print_to_file(), ug::MapSparseMatrix< TValueType >::printrow(), and ug::MapSparseMatrix< TValueType >::printtype().
template<typename TValueType> row_iterator ug::MapSparseMatrix< TValueType >::end_row (size_t r) inline
References ug::MapSparseMatrix< TValueType >::data.
Referenced by ug::MapSparseMatrix< TValueType >::get_connection(), and ug::MapSparseMatrix< TValueType >::set_as_copy_of().
template<typename TValueType> const_row_iterator ug::MapSparseMatrix< TValueType >::end_row (size_t r) const inline
References ug::MapSparseMatrix< TValueType >::data.
template<typename TValueType> template<typename M > void ug::MapSparseMatrix< TValueType >::get (M & mat) const
get local matrix
See also
add
template<typename TValueType> const_row_iterator ug::MapSparseMatrix< TValueType >::get_connection (size_t r, size_t c, bool & bFound) const inline
Parameters
r index of the row
c index of the column
Returns
a const_row_iterator to the connection A(r,c) if existing, otherwise end_row(row)
References ug::MapSparseMatrix< TValueType >::data, ug::MapSparseMatrix< TValueType >::end_row(), and ug::find().
template<typename TValueType> row_iterator ug::MapSparseMatrix< TValueType >::get_connection (size_t r, size_t c, bool & bFound) inline
Parameters
r index of the row
c index of the column
Returns
a row_iterator to the connection A(r,c) if existing, otherwise end_row(row)
References ug::MapSparseMatrix< TValueType >::data, ug::MapSparseMatrix< TValueType >::end_row(), and ug::find().
template<typename TValueType> const_row_iterator ug::MapSparseMatrix< TValueType >::get_connection (size_t r, size_t c) const inline
Parameters
r index of the row
c index of the column
Returns
a const_row_iterator to the connection A(r,c) if existing, otherwise end_row(row)
References ug::MapSparseMatrix< TValueType >::data, and ug::find().
template<typename TValueType> row_iterator ug::MapSparseMatrix< TValueType >::get_connection (size_t r, size_t c) inline
Parameters
r index of the row
c index of the column
Returns
a row_iterator to the connection A(r,c)
Remarks
creates connection if necessary.
References ug::MapSparseMatrix< TValueType >::data, and ug::find().
template<typename T > bool ug::MapSparseMatrix< T >::is_isolated (size_t i) const inline
check for isolated condition of an index
Parameters
i
Returns
true if only A[i,i] != 0.0
References begin_row(), end_row(), num_rows(), and UG_ASSERT.
Referenced by ug::MapSparseMatrix< TValueType >::matmul_minus().
template<typename T > template<typename vector_t > void ug::MapSparseMatrix< T >::mat_mult_add_row (size_t row, typename vector_t::value_type & dest, double alpha, const vector_t & v) const inline
calculates dest += alpha * A[row, .] v;
References begin_row(), end_row(), and ug::MatMultAdd().
Referenced by ug::MapSparseMatrix< TValueType >::num_connections().
template<typename TValueType> template<typename Vector_type > bool ug::MapSparseMatrix< TValueType >::matmul_minus (Vector_type & res, const Vector_type & x) const inline
calculate res -= A x
References ug::MapSparseMatrix< TValueType >::axpy(), ug::MapSparseMatrix< TValueType >::is_isolated(), and ug::MapSparseMatrix< TValueType >::scale().
template<typename TValueType> size_t ug::MapSparseMatrix< TValueType >::num_cols () const inline
returns the number of cols
References ug::MapSparseMatrix< TValueType >::cols.
Referenced by ug::MapSparseMatrix< TValueType >::set_as_copy_of().
template<typename TValueType> size_t ug::MapSparseMatrix< TValueType >::num_connections (size_t i) const inline
returns number of connections of row row.
References alpha, ug::MapSparseMatrix< TValueType >::data, and ug::MapSparseMatrix< TValueType >::mat_mult_add_row().
Referenced by ug::MapSparseMatrix< TValueType >::total_num_connections().
template<typename TValueType> size_t ug::MapSparseMatrix< TValueType >::num_rows () const inline
returns number of rows
References ug::MapSparseMatrix< TValueType >::data.
Referenced by ug::MapSparseMatrix< TValueType >::set_as_copy_of().
template<typename TValueType> const value_type& ug::MapSparseMatrix< TValueType >::operator() (size_t r, size_t c) const inline
operator() (size_t r, size_t c) const access connection (r, c)
Parameters
r row
c column
Note
if connection (r, c) is not there, returns 0.0
Returns
SparseMat(r, c)
References ug::MapSparseMatrix< TValueType >::data.
template<typename TValueType> value_type& ug::MapSparseMatrix< TValueType >::operator() (size_t r, size_t c) inline
operator() (size_t r, size_t c) const access or create connection (r, c)
Parameters
r row
c column
Note
(r,c) is added to sparsity pattern if not already there use operator()(r,c,bConnectionFound) to prevent
Returns
SparseMat(r, c)=0.0 if connection created, otherwise SparseMat(r, c)
References ug::MapSparseMatrix< TValueType >::add_matrix_row(), ug::MapSparseMatrix< TValueType >::data, and ug::MapSparseMatrix< TValueType >::set_matrix_row().
template<typename TValueType> SparseMatrix<value_type>& ug::MapSparseMatrix< TValueType >::operator*= (double d) inline
References ug::MapSparseMatrix< TValueType >::add(), and ug::MapSparseMatrix< TValueType >::scale().
template<typename TValueType> SparseMatrix<value_type>& ug::MapSparseMatrix< TValueType >::operator= (const SparseMatrix< value_type > & B) inline
References ug::MapSparseMatrix< TValueType >::axpy(), ug::MapSparseMatrix< TValueType >::axpy_transposed(), and ug::MapSparseMatrix< TValueType >::set_as_copy_of().
template<typename TValueType> void ug::MapSparseMatrix< TValueType >::p () const inline
References ug::MapSparseMatrix< TValueType >::connection::print().
template<typename TValueType> void ug::MapSparseMatrix< TValueType >::pr (size_t row) const inline
References ug::MapSparseMatrix< TValueType >::MapSparseMatrix(), and ug::MapSparseMatrix< TValueType >::printrow().
template<typename T > void ug::MapSparseMatrix< T >::print (const char *const text = NULL) const
print to console whole SparseMatrix
References num_cols(), num_rows(), and UG_LOG.
template<typename TValueType> void ug::MapSparseMatrix< TValueType >::print_to_file (const char * filename) const
Referenced by ug::MapSparseMatrix< TValueType >::defragment().
template<typename T > void ug::MapSparseMatrix< T >::printrow (size_t row) const
print the row row to the console
References begin_row(), end_row(), and UG_LOG.
Referenced by ug::MapSparseMatrix< TValueType >::defragment(), and ug::MapSparseMatrix< TValueType >::pr().
template<typename T > void ug::MapSparseMatrix< T >::printtype () const
Referenced by ug::MapSparseMatrix< TValueType >::defragment().
template<typename T > bool ug::MapSparseMatrix< T >::resize (size_t newRows, size_t newCols)
resizes the SparseMatrix
Parameters
newRows new nr of rows
newCols new nr of cols
Returns
References PROFILE_BEGIN_GROUP.
Referenced by ug::MapSparseMatrix< TValueType >::~MapSparseMatrix().
template<typename T > bool ug::MapSparseMatrix< T >::scale (double d)
References begin_row(), end_row(), num_rows(), and PROFILE_BEGIN_GROUP.
Referenced by ug::MapSparseMatrix< TValueType >::matmul_minus(), ug::MapSparseMatrix< TValueType >::operator*=(), and ug::MapSparseMatrix< TValueType >::~MapSparseMatrix().
template<typename TValueType> template<typename M > void ug::MapSparseMatrix< TValueType >::set (const M & mat)
set local matrix
See also
add
template<typename T > bool ug::MapSparseMatrix< T >::set (double a)
set matrix to Id*a
References begin_row(), end_row(), num_rows(), and PROFILE_BEGIN_GROUP.
template<typename TValueType> bool ug::MapSparseMatrix< T >::set_as_copy_of (const MapSparseMatrix< value_type > & B, double scale = 1.0)
create/recreate this as a copy of SparseMatrix B
Parameters
B the matrix of which to create a copy of
scale an optional scaling
Returns
true on success
References ug::MapSparseMatrix< TValueType >::begin_row(), ug::MapSparseMatrix< TValueType >::end_row(), ug::MapSparseMatrix< TValueType >::num_cols(), ug::MapSparseMatrix< TValueType >::num_rows(), PROFILE_BEGIN_GROUP, and resize().
Referenced by ug::MapSparseMatrix< TValueType >::operator=(), and ug::MapSparseMatrix< TValueType >::~MapSparseMatrix().
template<typename T > bool ug::MapSparseMatrix< T >::set_as_transpose_of (const SparseMatrix< value_type > & B, double scale = 1.0)
write in a empty SparseMatrix (this) the transpose SparseMatrix of B.
Parameters
B the matrix of which to create the transpose of
scale an optional scaling
Returns
true on success
References ug::SparseMatrix< TValueType >::begin_row(), ug::SparseMatrix< TValueType >::end_row(), ug::SparseMatrix< TValueType >::num_cols(), ug::SparseMatrix< TValueType >::num_rows(), PROFILE_BEGIN_GROUP, and resize().
Referenced by ug::MapSparseMatrix< TValueType >::~MapSparseMatrix().
template<typename T > void ug::MapSparseMatrix< T >::set_matrix_row (size_t row, connection * c, size_t nr)
set a row of the matrix. all previous content in this row is destroyed (
See also
add_matrix_row).
Parameters
row index of the row to set
c pointer to a array of sorted connections of size nr
nr number of connections in c
Remarks
will sort array c
References ug::MapSparseMatrix< TValueType >::connection::iIndex, and PROFILE_BEGIN_GROUP.
Referenced by ug::MapSparseMatrix< TValueType >::operator()().
template<typename TValueType> size_t ug::MapSparseMatrix< TValueType >::total_num_connections () const inline
returns the total number of connections
References ug::MapSparseMatrix< TValueType >::data, and ug::MapSparseMatrix< TValueType >::num_connections().
Friends And Related Function Documentation
template<typename TValueType> std::ostream& operator<< (std::ostream & out, const MapSparseMatrix< TValueType > & m) friend
Member Data Documentation
template<typename TValueType> size_t ug::MapSparseMatrix< TValueType >::cols protected
Referenced by ug::MapSparseMatrix< TValueType >::num_cols().
template<typename TValueType> std::vector<std::map<size_t, TValueType> > ug::MapSparseMatrix< TValueType >::data protected
Referenced by ug::MapSparseMatrix< TValueType >::begin_row(), ug::MapSparseMatrix< TValueType >::end_row(), ug::MapSparseMatrix< TValueType >::get_connection(), ug::MapSparseMatrix< TValueType >::num_connections(), ug::MapSparseMatrix< TValueType >::num_rows(), ug::MapSparseMatrix< TValueType >::operator()(), and ug::MapSparseMatrix< TValueType >::total_num_connections().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/map_algebra/mapsparsematrix.h
ugbase/lib_algebra/map_algebra/mapsparsematrix_impl.h
ugbase/lib_algebra/map_algebra/mapsparsematrix_print.h