ug4: ug::Traverser_RayElementIntersection< tree_t > Class Template Reference
ug::Traverser_RayElementIntersection< tree_t > Class Template Reference
#include <ntree_traverser.h>
Public Types
typedef tree_t::box_t box_t
typedef tree_t::elem_t elem_t
typedef RayElemIntersectionRecord< elem_t > intersection_record_t
typedef tree_t::vector_t vector_t
Public Member Functions
void begin_traversal (const tree_t &tree)
void end_traversal (const tree_t &)
const std::vector< intersection_record_t > & result () const
Traverser_RayElementIntersection (const vector_t &rayFrom, const vector_t rayDir, const number small=1.e-12)
void visit_down (const tree_t &, size_t)
int visit_up (const tree_t &tree, size_t node)
Private Attributes
std::vector< intersection_record_t > m_intersections
vector_t m_rayDir
vector_t m_rayFrom
const number m_small
Member Typedef Documentation
box_t
template<class tree_t> typedef tree_t::box_t ug::Traverser_RayElementIntersection< tree_t >::box_t
elem_t
template<class tree_t> typedef tree_t::elem_t ug::Traverser_RayElementIntersection< tree_t >::elem_t
intersection_record_t
template<class tree_t> typedef RayElemIntersectionRecord<elem_t> ug::Traverser_RayElementIntersection< tree_t >::intersection_record_t
vector_t
template<class tree_t> typedef tree_t::vector_t ug::Traverser_RayElementIntersection< tree_t >::vector_t
Constructor & Destructor Documentation
Traverser_RayElementIntersection()
template<class tree_t> ug::Traverser_RayElementIntersection< tree_t >::Traverser_RayElementIntersection (const vector_t & rayFrom, const vector_t rayDir, const number small = 1.e-12) inline
Member Function Documentation
begin_traversal()
template<class tree_t> void ug::Traverser_RayElementIntersection< tree_t >::begin_traversal (const tree_t & tree) inline
References ug::Traverser_RayElementIntersection< tree_t >::m_intersections.
end_traversal()
template<class tree_t> void ug::Traverser_RayElementIntersection< tree_t >::end_traversal (const tree_t &) inline
result()
template<class tree_t> const std::vector<intersection_record_t>& ug::Traverser_RayElementIntersection< tree_t >::result () const inline
References ug::Traverser_RayElementIntersection< tree_t >::m_intersections.
Referenced by ug::RayElementIntersections().
visit_down()
template<class tree_t> void ug::Traverser_RayElementIntersection< tree_t >::visit_down (const tree_t & , size_t) inline
visit_up()
template<class tree_t> int ug::Traverser_RayElementIntersection< tree_t >::visit_up (const tree_t & tree, size_t node) inline
References ug::DONT_TRAVERSE_CHILDREN, ug::Traverser_RayElementIntersection< tree_t >::m_intersections, ug::Traverser_RayElementIntersection< tree_t >::m_rayDir, ug::Traverser_RayElementIntersection< tree_t >::m_rayFrom, ug::Traverser_RayElementIntersection< tree_t >::m_small, ug::TRAVERSE_CHILDREN, ug::VecLength(), ug::VecScale(), and ug::VecSet().
Member Data Documentation
m_intersections
template<class tree_t> std::vector<intersection_record_t> ug::Traverser_RayElementIntersection< tree_t >::m_intersections private
Referenced by ug::Traverser_RayElementIntersection< tree_t >::begin_traversal(), ug::Traverser_RayElementIntersection< tree_t >::result(), and ug::Traverser_RayElementIntersection< tree_t >::visit_up().
m_rayDir
template<class tree_t> vector_t ug::Traverser_RayElementIntersection< tree_t >::m_rayDir private
Referenced by ug::Traverser_RayElementIntersection< tree_t >::visit_up().
m_rayFrom
template<class tree_t> vector_t ug::Traverser_RayElementIntersection< tree_t >::m_rayFrom private
Referenced by ug::Traverser_RayElementIntersection< tree_t >::visit_up().
m_small
template<class tree_t> const number ug::Traverser_RayElementIntersection< tree_t >::m_small private
Referenced by ug::Traverser_RayElementIntersection< tree_t >::visit_up().
The documentation for this class was generated from the following file:
ugbase/common/space_partitioning/ntree_traverser.h