ug4: ug::FV1ManifoldGeometry< TElem, TWorldDim > Class Template Reference
ug::FV1ManifoldGeometry< TElem, TWorldDim > Class Template Reference
#include <fv1_geom.h>
Classes
class BF
struct MidID
Public Types
typedef fv1_traits< ref_elem_type, dim >::scv_type bf_type
typedef TElem elem_type
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
Public Member Functions
const BF & bf (size_t i) const
const access to Boundary Face number i
const MathVector< worldDim > * bf_global_ips () const
returns all ips of scvf as they appear in scv loop
const MathVector< dim > * bf_local_ips () const
returns all ips of BF as they appear in scv loop
const MathVector< worldDim > * corners () const
get vector of corners for current element
GridObject * elem () const
get the element
FV1ManifoldGeometry ()
constructor
size_t num_bf () const
number of BoundaryFaces
size_t num_bf_global_ips () const
returns number of all BF ips
size_t num_bf_local_ips () const
returns number of all BF ips
void update (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update data for given element
Static Public Attributes
static const int dim = ref_elem_type::dim
static const size_t m_numBF = ref_elem_type::numCorners
static const int order = 1
static const bool staticLocalData = true
flag indicating if local data may change
static const bool usesHangingNodes = false
static const int worldDim = TWorldDim
Protected Member Functions
void copy_global_corners (BF &bf)
void copy_local_corners (BF &bf)
Protected Attributes
std::vector< MathVector< worldDim > > m_vGlobBFIP
std::vector< MathVector< dim > > m_vLocBFIP
Private Attributes
MathVector< worldDim > m_gloMid [dim+1][m_numBF]
MathVector< dim > m_locMid [dim+1][m_numBF]
GridObject * m_pElem
ReferenceMapping< ref_elem_type, worldDim > m_rMapping
const ref_elem_type & m_rRefElem
BF m_vBF [m_numBF]
Member Typedef Documentation
bf_type
template<typename TElem , int TWorldDim> typedef fv1_traits<ref_elem_type, dim>::scv_type ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf_type
elem_type
template<typename TElem , int TWorldDim> typedef TElem ug::FV1ManifoldGeometry< TElem, TWorldDim >::elem_type
ref_elem_type
template<typename TElem , int TWorldDim> typedef reference_element_traits<TElem>::reference_element_type ug::FV1ManifoldGeometry< TElem, TWorldDim >::ref_elem_type
Constructor & Destructor Documentation
FV1ManifoldGeometry()
template<typename TElem , int TWorldDim> ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry
constructor
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_local_corners(), dim, ug::FV1ManifoldGeometry< TElem, TWorldDim >::dim, ug::LFEID::LAGRANGE, ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::local_ip(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_locMid, ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_numBF, ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_rRefElem, ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_vBF, ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_vLocBFIP, ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::midId, ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::nodeId, ug::FV1ManifoldGeometry< TElem, TWorldDim >::num_bf(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), UG_ASSERT, and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vShape.
Member Function Documentation
bf()
template<typename TElem , int TWorldDim> const BF& ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf (size_t i) const inline
const access to Boundary Face number i
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_vBF, ug::FV1ManifoldGeometry< TElem, TWorldDim >::num_bf(), and UG_ASSERT.
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_global_corners(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_local_corners(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry().
bf_global_ips()
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf_global_ips () const inline
returns all ips of scvf as they appear in scv loop
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_vGlobBFIP.
bf_local_ips()
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf_local_ips () const inline
returns all ips of BF as they appear in scv loop
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_vLocBFIP.
copy_global_corners()
template<typename TElem , int TWorldDim> void ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_global_corners (BF & bf) inline protected
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::dim, ug::FV1ManifoldGeometry< TElem, TWorldDim >::MidID::dim, ug::FV1ManifoldGeometry< TElem, TWorldDim >::MidID::id, ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_gloMid, ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::midId, ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::num_corners(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vGloPos.
copy_local_corners()
template<typename TElem , int TWorldDim> void ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_local_corners (BF & bf) inline protected
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::dim, ug::FV1ManifoldGeometry< TElem, TWorldDim >::MidID::dim, ug::FV1ManifoldGeometry< TElem, TWorldDim >::MidID::id, ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_locMid, ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::midId, ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::num_corners(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::vLocPos.
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry().
corners()
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::FV1ManifoldGeometry< TElem, TWorldDim >::corners () const inline
get vector of corners for current element
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_gloMid.
elem()
template<typename TElem , int TWorldDim> GridObject* ug::FV1ManifoldGeometry< TElem, TWorldDim >::elem () const inline
get the element
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_pElem.
num_bf()
template<typename TElem , int TWorldDim> size_t ug::FV1ManifoldGeometry< TElem, TWorldDim >::num_bf () const inline
number of BoundaryFaces
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_numBF.
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry().
num_bf_global_ips()
template<typename TElem , int TWorldDim> size_t ug::FV1ManifoldGeometry< TElem, TWorldDim >::num_bf_global_ips () const inline
returns number of all BF ips
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_vGlobBFIP.
num_bf_local_ips()
template<typename TElem , int TWorldDim> size_t ug::FV1ManifoldGeometry< TElem, TWorldDim >::num_bf_local_ips () const inline
returns number of all BF ips
References ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_vLocBFIP.
update()
template<typename TElem , int TWorldDim> void ug::FV1ManifoldGeometry< TElem, TWorldDim >::update (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update data for given element
References dim, and ug::FV1ManifoldGeometry< TElem, TWorldDim >::BF::global_ip().
Member Data Documentation
dim
template<typename TElem , int TWorldDim> const int ug::FV1ManifoldGeometry< TElem, TWorldDim >::dim = ref_elem_type::dim static
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_global_corners(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_local_corners(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry().
m_gloMid
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_gloMid[dim+1][m_numBF] private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_global_corners(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::corners().
m_locMid
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_locMid[dim+1][m_numBF] private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_local_corners(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry().
m_numBF
template<typename TElem , int TWorldDim> const size_t ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_numBF = ref_elem_type::numCorners static
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::num_bf().
m_pElem
template<typename TElem , int TWorldDim> GridObject* ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_pElem private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::elem().
m_rMapping
template<typename TElem , int TWorldDim> ReferenceMapping<ref_elem_type, worldDim> ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_rMapping private
m_rRefElem
template<typename TElem , int TWorldDim> const ref_elem_type& ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_rRefElem private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry().
m_vBF
template<typename TElem , int TWorldDim> BF ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_vBF[m_numBF] private
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry().
m_vGlobBFIP
template<typename TElem , int TWorldDim> std::vector<MathVector<worldDim> > ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_vGlobBFIP protected
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf_global_ips(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::num_bf_global_ips().
m_vLocBFIP
template<typename TElem , int TWorldDim> std::vector<MathVector<dim> > ug::FV1ManifoldGeometry< TElem, TWorldDim >::m_vLocBFIP protected
Referenced by ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf_local_ips(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::FV1ManifoldGeometry(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::num_bf_local_ips().
order
template<typename TElem , int TWorldDim> const int ug::FV1ManifoldGeometry< TElem, TWorldDim >::order = 1 static
staticLocalData
template<typename TElem , int TWorldDim> const bool ug::FV1ManifoldGeometry< TElem, TWorldDim >::staticLocalData = true static
flag indicating if local data may change
usesHangingNodes
template<typename TElem , int TWorldDim> const bool ug::FV1ManifoldGeometry< TElem, TWorldDim >::usesHangingNodes = false static
worldDim
template<typename TElem , int TWorldDim> const int ug::FV1ManifoldGeometry< TElem, TWorldDim >::worldDim = TWorldDim static
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/fv1_geom.h
ugbase/lib_disc/spatial_disc/disc_util/fv1_geom.cpp