ug4: ug::HFV1ManifoldGeometry< TElem, TWorldDim > Class Template Reference
ug::HFV1ManifoldGeometry< TElem, TWorldDim > Class Template Reference
#include <hfv1_geom.h>
Classes
class BF
struct MidID
struct NatEdgeInfo
struct NewEdgeInfo
Public Types
typedef hfv1_traits< ref_elem_type, dim >::scv_type bf_type
typedef TElem elem_type
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
Public Member Functions
const BF & bf (size_t i) const
const access to Boundary Face number i
const MathVector< worldDim > * bf_global_ips () const
returns all ips of scvf as they appear in scv loop
const MathVector< dim > * bf_local_ips () const
returns all ips of scvf as they appear in scv loop
HFV1ManifoldGeometry ()
constructor
size_t num_bf () const
number of BoundaryFaces
size_t num_bf_global_ips () const
returns number of all scvf ips
size_t num_bf_local_ips () const
returns number of all scvf ips
void print ()
print information about hfvg to log
int subset_index () const
returns subset index
void update (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update data for given element
Static Public Attributes
static const int dim = ref_elem_type::dim
static const size_t m_numNaturalBF = ref_elem_type::numCorners
static const size_t m_numNaturalBFS = ref_elem_type::numEdges
static const int order = 1
static const bool staticLocalData = true
flag indicating if local data may change
static const bool usesHangingNodes = true
static const int worldDim = TWorldDim
Protected Member Functions
void compute_side_midpoints (MathVector< dim > &locSideMid, MathVector< worldDim > &gloSideMid)
void compute_side_midpoints (size_t i, size_t j, size_t k, size_t l, MathVector< dim > &locSideMid, MathVector< worldDim > &gloSideMid)
void compute_side_midpoints (size_t i, size_t j, size_t k, MathVector< dim > &locSideMid, MathVector< worldDim > &gloSideMid)
size_t get_child_edge_of_corner (size_t i, size_t co)
Protected Attributes
std::vector< MathVector< worldDim > > m_vGlobBFIP
std::vector< MathVector< dim > > m_vLocBFIP
Private Attributes
std::vector< MathVector< worldDim > > m_gloMid [dim+1]
std::vector< MathVector< dim > > m_locMid [dim+1]
TElem * m_pElem
ReferenceMapping< ref_elem_type, worldDim > m_rMapping
const ref_elem_type & m_rRefElem
int m_ssi
std::vector< BF > m_vBF
std::vector< NatEdgeInfo > m_vNatEdgeInfo
std::vector< NewEdgeInfo > m_vNewEdgeInfo
Member Typedef Documentation
template<typename TElem , int TWorldDim> typedef hfv1_traits<ref_elem_type, dim>::scv_type ug::HFV1ManifoldGeometry< TElem, TWorldDim >::bf_type
template<typename TElem , int TWorldDim> typedef TElem ug::HFV1ManifoldGeometry< TElem, TWorldDim >::elem_type
template<typename TElem , int TWorldDim> typedef reference_element_traits<TElem>::reference_element_type ug::HFV1ManifoldGeometry< TElem, TWorldDim >::ref_elem_type
Constructor & Destructor Documentation
template<typename TElem , int TWorldDim> ug::HFV1ManifoldGeometry< TElem, TWorldDim >::HFV1ManifoldGeometry ()
constructor
References ug::HFV1ManifoldGeometry< TElem, TWorldDim >::dim, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_gloMid, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_locMid, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_numNaturalBF, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_rRefElem, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vBF, and ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::update().
Member Function Documentation
template<typename TElem , int TWorldDim> const BF& ug::HFV1ManifoldGeometry< TElem, TWorldDim >::bf (size_t i) const inline
const access to Boundary Face number i
References UG_ASSERT.
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::HFV1ManifoldGeometry< TElem, TWorldDim >::bf_global_ips () const inline
returns all ips of scvf as they appear in scv loop
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::HFV1ManifoldGeometry< TElem, TWorldDim >::bf_local_ips () const inline
returns all ips of scvf as they appear in scv loop
template<typename TElem , int TWorldDim> void ug::HFV1ManifoldGeometry< TElem, TWorldDim >::compute_side_midpoints (MathVector< dim > & locSideMid, MathVector< worldDim > & gloSideMid) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, and ug::HFV1Geometry< TElem, TWorldDim >::m_rRefElem.
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> void ug::HFV1ManifoldGeometry< TElem, TWorldDim >::compute_side_midpoints (size_t i, size_t j, size_t k, size_t l, MathVector< dim > & locSideMid, MathVector< worldDim > & gloSideMid) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, and ug::VecAdd().
template<typename TElem , int TWorldDim> void ug::HFV1ManifoldGeometry< TElem, TWorldDim >::compute_side_midpoints (size_t i, size_t j, size_t k, MathVector< dim > & locSideMid, MathVector< worldDim > & gloSideMid) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, and ug::VecAdd().
template<typename TElem , int TWorldDim> size_t ug::HFV1ManifoldGeometry< TElem, TWorldDim >::get_child_edge_of_corner (size_t i, size_t co) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_vNatEdgeInfo, and ug::HFV1Geometry< TElem, TWorldDim >::m_vNewEdgeInfo.
template<typename TElem , int TWorldDim> size_t ug::HFV1ManifoldGeometry< TElem, TWorldDim >::num_bf () const inline
number of BoundaryFaces
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> size_t ug::HFV1ManifoldGeometry< TElem, TWorldDim >::num_bf_global_ips () const inline
returns number of all scvf ips
template<typename TElem , int TWorldDim> size_t ug::HFV1ManifoldGeometry< TElem, TWorldDim >::num_bf_local_ips () const inline
returns number of all scvf ips
template<typename TElem , int TWorldDim> void ug::HFV1ManifoldGeometry< TElem, TWorldDim >::print ()
print information about hfvg to log
debug output
References ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vBF, and UG_LOG.
template<typename TElem , int TWorldDim> int ug::HFV1ManifoldGeometry< TElem, TWorldDim >::subset_index () const inline
returns subset index
References UG_THROW.
template<typename TElem , int TWorldDim> void ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update data for given element
References ug::AveragePositions(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::bf(), ug::CollectEdges(), ug::CollectEdgesSorted(), ug::CollectFaces(), ug::CollectFacesSorted(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::compute_side_midpoints(), ug::Face::container_section(), ug::CSEDGE_CONSTRAINED_EDGE, ug::CSEDGE_CONSTRAINING_EDGE, ug::CSEDGE_REGULAR_EDGE, ug::CSFACE_CONSTRAINING_QUADRILATERAL, ug::CSFACE_CONSTRAINING_TRIANGLE, dim, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::dim, ug::ISubsetHandler::get_subset_index(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::BF::global_ip(), ug::ISubsetHandler::grid(), ug::LFEID::LAGRANGE, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::BF::local_ip(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_gloMid, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_locMid, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_numNaturalBF, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_numNaturalBFS, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_pElem, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_rRefElem, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_ssi, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vBF, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vGlobBFIP, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vLocBFIP, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vNatEdgeInfo, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vNewEdgeInfo, ug::HFV1ManifoldGeometry< TElem, TWorldDim >::num_bf(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::BF::numCorners, ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), UG_ASSERT, UG_THROW, and ug::VecInterpolateLinear().
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::HFV1ManifoldGeometry().
Member Data Documentation
template<typename TElem , int TWorldDim> const int ug::HFV1ManifoldGeometry< TElem, TWorldDim >::dim = ref_elem_type::dim static
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::HFV1ManifoldGeometry(), and ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<MathVector<worldDim> > ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_gloMid[dim+1] private
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::HFV1ManifoldGeometry(), and ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<MathVector<dim> > ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_locMid[dim+1] private
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::HFV1ManifoldGeometry(), and ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> const size_t ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_numNaturalBF = ref_elem_type::numCorners static
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::HFV1ManifoldGeometry(), and ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> const size_t ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_numNaturalBFS = ref_elem_type::numEdges static
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> TElem* ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_pElem private
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> ReferenceMapping<ref_elem_type, worldDim> ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_rMapping private
template<typename TElem , int TWorldDim> const ref_elem_type& ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_rRefElem private
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::HFV1ManifoldGeometry(), and ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> int ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_ssi private
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<BF> ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vBF private
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::HFV1ManifoldGeometry(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::print(), and ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<MathVector<worldDim> > ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vGlobBFIP protected
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<MathVector<dim> > ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vLocBFIP protected
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<NatEdgeInfo> ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vNatEdgeInfo private
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<NewEdgeInfo> ug::HFV1ManifoldGeometry< TElem, TWorldDim >::m_vNewEdgeInfo private
Referenced by ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> const int ug::HFV1ManifoldGeometry< TElem, TWorldDim >::order = 1 static
template<typename TElem , int TWorldDim> const bool ug::HFV1ManifoldGeometry< TElem, TWorldDim >::staticLocalData = true static
flag indicating if local data may change
template<typename TElem , int TWorldDim> const bool ug::HFV1ManifoldGeometry< TElem, TWorldDim >::usesHangingNodes = true static
template<typename TElem , int TWorldDim> const int ug::HFV1ManifoldGeometry< TElem, TWorldDim >::worldDim = TWorldDim static
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/hfv1_geom.h
ugbase/lib_disc/spatial_disc/disc_util/hfv1_geom.cpp