ug4: ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra > Class Template Reference
ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra > Class Template Reference
#include <bridge_mat_vec_operations.h>
Public Member Functions
void assign (SmartPtr< vector_type > p)
SmartPtr< vector_type > eval ()
size_t size () const
VecScaleAddClass ()
VecScaleAddClass (const VecScaleAddClass< TAlgebra > &parent)
VecScaleAddClass (double scale, SmartPtr< VecScaleAddClass< TAlgebra > > vsac)
VecScaleAddClass (double scale, SmartPtr< VecScaleAddClass< TAlgebra > > vsac, double scale1, SmartPtr< vector_type > v1)
VecScaleAddClass (double scale1, SmartPtr< vector_type > v1)
VecScaleAddClass (double scale1, SmartPtr< vector_type > v1, double scale, SmartPtr< VecScaleAddClass< TAlgebra > > vsac)
VecScaleAddClass (double scale1, SmartPtr< vector_type > v1, double scale2, SmartPtr< vector_type > v2)
Private Types
typedef TAlgebra::vector_type vector_type
Private Attributes
std::vector< double > scaling
std::vector< SmartPtr< vector_type > > vecs
Member Typedef Documentation
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::vector_type private
Constructor & Destructor Documentation
VecScaleAddClass() [1/7]
template<typename TAlgebra > ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::VecScaleAddClass (double scale1, SmartPtr< vector_type > v1) inline
References ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::scaling, and ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::vecs.
VecScaleAddClass() [2/7]
template<typename TAlgebra > ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::VecScaleAddClass (double scale1, SmartPtr< vector_type > v1, double scale2, SmartPtr< vector_type > v2) inline
References ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::scaling, and ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::vecs.
VecScaleAddClass() [3/7]
template<typename TAlgebra > ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::VecScaleAddClass (double scale, SmartPtr< VecScaleAddClass< TAlgebra > > vsac, double scale1, SmartPtr< vector_type > v1) inline
References ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::scaling, and ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::vecs.
VecScaleAddClass() [4/7]
template<typename TAlgebra > ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::VecScaleAddClass (double scale1, SmartPtr< vector_type > v1, double scale, SmartPtr< VecScaleAddClass< TAlgebra > > vsac) inline
References ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::scaling, and ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::vecs.
VecScaleAddClass() [5/7]
template<typename TAlgebra > ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::VecScaleAddClass (double scale, SmartPtr< VecScaleAddClass< TAlgebra > > vsac) inline
References ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::scaling, and ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::vecs.
VecScaleAddClass() [6/7]
template<typename TAlgebra > ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::VecScaleAddClass () inline
VecScaleAddClass() [7/7]
template<typename TAlgebra > ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::VecScaleAddClass (const VecScaleAddClass< TAlgebra > & parent) inline
Member Function Documentation
assign()
template<typename TAlgebra > void ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::assign (SmartPtr< vector_type > p) inline
References p, ug::PST_CONSISTENT, ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::scaling, ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::size(), UG_THROW, ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::vecs, ug::VecScaleAdd(), and ug::VecScaleAssign().
Referenced by ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::eval().
eval()
template<typename TAlgebra > SmartPtr<vector_type> ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::eval () inline
References ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::assign(), p, and ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::vecs.
size()
template<typename TAlgebra > size_t ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::size () const inline
References ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::scaling.
Referenced by ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::assign().
Member Data Documentation
scaling
template<typename TAlgebra > std::vector<double> ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::scaling private
Referenced by ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::assign(), ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::size(), and ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::VecScaleAddClass().
vecs
template<typename TAlgebra > std::vector<SmartPtr<vector_type> > ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::vecs private
Referenced by ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::assign(), ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::eval(), and ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::VecScaleAddClass().
The documentation for this class was generated from the following file:
ugbase/bridge/algebra_bridges/bridge_mat_vec_operations.h