ug4: ug::unvisited_iterator Class Reference
ug::unvisited_iterator Class Reference
Public Member Functions
bool operator!= (const unvisited_iterator &o) const
unsigned operator* () const
void operator++ ()
bool operator== (const unvisited_iterator &o) const
unvisited_iterator (std::vector< BOOL > &vec_bool)
unvisited_iterator (std::vector< BOOL > &vec_bool, unsigned i)
Public Attributes
unsigned cur
unsigned n
std::vector< BOOL > & visited
Constructor & Destructor Documentation
unvisited_iterator() [1/2]
ug::unvisited_iterator::unvisited_iterator (std::vector< BOOL > & vec_bool, unsigned i) inline
unvisited_iterator() [2/2]
ug::unvisited_iterator::unvisited_iterator (std::vector< BOOL > & vec_bool) inline
References cur, operator++(), and visited.
Member Function Documentation
operator!=()
bool ug::unvisited_iterator::operator!= (const unvisited_iterator & o) const inline
References operator==().
operator*()
unsigned ug::unvisited_iterator::operator* () const inline
References cur.
operator++()
void ug::unvisited_iterator::operator++ () inline
References cur, n, and visited.
Referenced by unvisited_iterator().
operator==()
bool ug::unvisited_iterator::operator== (const unvisited_iterator & o) const inline
References cur.
Referenced by operator!=().
Member Data Documentation
cur
unsigned ug::unvisited_iterator::cur
Referenced by operator*(), operator++(), operator==(), and unvisited_iterator().
n
unsigned ug::unvisited_iterator::n
Referenced by operator++().
visited
std::vector<BOOL>& ug::unvisited_iterator::visited
Referenced by operator++(), and unvisited_iterator().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/ordering_strategies/algorithms/iters.cpp