ug4: ug::MaximumMarking< TDomain > Class Template Reference
ug::MaximumMarking< TDomain > Class Template Reference
#include <error_elem_marking_strategy.h>
Public Types
typedef IElementMarkingStrategy< TDomain > base_type
Public Types inherited from ug::IElementMarkingStrategy< TDomain >
typedef Grid::AttachmentAccessor< elem_type, ug::Attachment< number > > elem_accessor_type
typedef domain_traits< dim >::element_type elem_type
element type to be marked
Public Member Functions
MaximumMarking (number theta, number eps)
MaximumMarking (number theta=1.0)
MaximumMarking (number theta_max, number theta_min, number eps)
void set_max_level (int lvl)
void set_min_level (int lvl)
Public Member Functions inherited from ug::IElementMarkingStrategy< TDomain >
number global_estimated_error () const
number global_estimated_error_per_elem_max () const
number global_estimated_error_per_elem_min () const
IElementMarkingStrategy ()
void mark (IMultigridElementIndicators< TDomain > &mgElemIndicators, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd)
This function marks all elements.
virtual ~IElementMarkingStrategy ()
Protected Member Functions
void mark (typename base_type::elem_accessor_type &aaErrorSq, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd)
DEPRECATED:
Protected Attributes
number m_eps
int m_max_level
int m_min_level
number m_theta
number m_theta_min
Protected Attributes inherited from ug::IElementMarkingStrategy< TDomain >
number m_latest_error
number m_latest_error_per_elem_max
number m_latest_error_per_elem_min
Additional Inherited Members
Static Public Attributes inherited from ug::IElementMarkingStrategy< TDomain >
static const int dim = TDomain::dim
world dimension
Detailed Description
template<typename TDomain>
class ug::MaximumMarking< TDomain >
Marks elements with \eta_K >= \theta \max_{K'} \eta_{K'} for refinement (cf. Verfuerth script)
Member Typedef Documentation
base_type
template<typename TDomain > typedef IElementMarkingStrategy<TDomain> ug::MaximumMarking< TDomain >::base_type
Constructor & Destructor Documentation
MaximumMarking() [1/3]
template<typename TDomain > ug::MaximumMarking< TDomain >::MaximumMarking (number theta = 1.0) inline
MaximumMarking() [2/3]
template<typename TDomain > ug::MaximumMarking< TDomain >::MaximumMarking (number theta, number eps) inline
MaximumMarking() [3/3]
template<typename TDomain > ug::MaximumMarking< TDomain >::MaximumMarking (number theta_max, number theta_min, number eps) inline
Member Function Documentation
mark()
template<typename TDomain > void ug::MaximumMarking< TDomain >::mark (typename base_type::elem_accessor_type & aaError, IRefiner & refiner, ConstSmartPtr< DoFDistribution > dd) protected virtual
DEPRECATED:
Implements ug::IElementMarkingStrategy< TDomain >.
References pcl::ProcessCommunicator::allreduce(), ug::ComputeMinMax(), ug::IRefiner::mark(), pcl::NumProcs(), PCL_RO_MAX, PCL_RO_SUM, ug::RM_COARSEN, ug::RM_REFINE, UG_ASSERT, and UG_LOG.
set_max_level()
template<typename TDomain > void ug::MaximumMarking< TDomain >::set_max_level (int lvl) inline
References ug::MaximumMarking< TDomain >::m_max_level.
set_min_level()
template<typename TDomain > void ug::MaximumMarking< TDomain >::set_min_level (int lvl) inline
References ug::MaximumMarking< TDomain >::m_min_level.
Member Data Documentation
m_eps
template<typename TDomain > number ug::MaximumMarking< TDomain >::m_eps protected
m_max_level
template<typename TDomain > int ug::MaximumMarking< TDomain >::m_max_level protected
Referenced by ug::MaximumMarking< TDomain >::set_max_level().
m_min_level
template<typename TDomain > int ug::MaximumMarking< TDomain >::m_min_level protected
Referenced by ug::MaximumMarking< TDomain >::set_min_level().
m_theta
template<typename TDomain > number ug::MaximumMarking< TDomain >::m_theta protected
m_theta_min
template<typename TDomain > number ug::MaximumMarking< TDomain >::m_theta_min protected
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/error_elem_marking_strategy.h