ug4: ug::TruncatedEquidistantLagrange1D Class Reference
ug::TruncatedEquidistantLagrange1D Class Reference
#include <lagrange1d.h>
Public Member Functions
TruncatedEquidistantLagrange1D (const size_t i, const size_t degree)
Public Member Functions inherited from ug::Polynomial1D
size_t degree () const
Polynomial1D derivative () const
returns the derivative of this polynomial as a polynomial
Polynomial1D & operator*= (const Polynomial1D &v)
multiply by a polynomial
Polynomial1D & operator*= (number scale)
multiply by a scalar
Polynomial1D (size_t degree=0)
Constructor producing zero polynomial of degree 'degree'.
Polynomial1D (const std::vector< number > &a)
Constructor passing coefficients for the polynomial.
number value (const number x) const
evaluate the value of the polynom at x
Static Public Member Functions
static number position (const size_t i, const size_t degree)
returns the position of the i'th interpolation point
Protected Member Functions
void compute_coeffs (const int i, const int p)
computes the coefficients for passed interpolation points
Protected Member Functions inherited from ug::Polynomial1D
void set_coefficients (const std::vector< number > &a)
Detailed Description
Truncated EquiDistant Lagrange Function
Creates for given order p and iterpolation point i the polynomial
\[ \prod_{j=0}^{i-1} \frac{x - \frac{j}{p}}{\frac{i}{p} - \frac{j}{p}} \]
Constructor & Destructor Documentation
ug::TruncatedEquidistantLagrange1D::TruncatedEquidistantLagrange1D (const size_t i, const size_t degree) inline
creates a lagrange polynomial with equidistant interpolation points
Parameters
[in] i number of interpolation point, where polynom is 1
[in] degree degree of polynom
References ug::Lagrange1D::compute_coeffs(), and UG_ASSERT.
Member Function Documentation
void ug::TruncatedEquidistantLagrange1D::compute_coeffs (const int i, const int p) inline protected
computes the coefficients for passed interpolation points
References ug::Polynomial1D::set_coefficients().
static number ug::TruncatedEquidistantLagrange1D::position (const size_t i, const size_t degree) inline static
returns the position of the i'th interpolation point
References UG_ASSERT.
Referenced by ug::LagrangeLSFS< ReferenceTriangle, TOrder >::position(), ug::FlexLagrangeLSFS< ReferenceTriangle >::position(), ug::LagrangeLSFS< ReferenceTetrahedron, TOrder >::position(), ug::FlexLagrangeLSFS< ReferenceTetrahedron >::position(), ug::LagrangeLSFS< ReferencePrism, TOrder >::position(), and ug::FlexLagrangeLSFS< ReferencePrism >::position().
The documentation for this class was generated from the following file:
ugbase/lib_disc/local_finite_element/common/lagrange1d.h