ug4: ug::DelaunayDebugSaver Class Reference
ug::DelaunayDebugSaver Class Reference
Public Member Functions
void enable_save (bool enable=true)
void save (Grid &g, const char *msg)
template<class TAAPos >
void save (Grid &g, const char *msg, DelaunayInfo< TAAPos > &dinfo)
Static Public Member Functions
static DelaunayDebugSaver & inst ()
Private Member Functions
DelaunayDebugSaver ()
Private Attributes
int m_counter
bool m_saveEnabled
Constructor & Destructor Documentation
DelaunayDebugSaver()
ug::DelaunayDebugSaver::DelaunayDebugSaver () inline private
Member Function Documentation
enable_save()
void ug::DelaunayDebugSaver::enable_save (bool enable = true) inline
inst()
static DelaunayDebugSaver& ug::DelaunayDebugSaver::inst () inline static
save() [1/2]
void ug::DelaunayDebugSaver::save (Grid & g, const char * msg) inline
References ug::AssignGridToSubset(), ug::SaveGridToFile(), and UG_LOG.
save() [2/2]
template<class TAAPos > void ug::DelaunayDebugSaver::save (Grid & g, const char * msg, DelaunayInfo< TAAPos > & dinfo) inline
References AssignSubsetColors(), ug::Grid::begin(), ug::Grid::end(), ug::DelaunayInfo< TAAPos >::mark(), ug::SaveGridToFile(), and UG_LOG.
Member Data Documentation
m_counter
int ug::DelaunayDebugSaver::m_counter private
m_saveEnabled
bool ug::DelaunayDebugSaver::m_saveEnabled private
The documentation for this class was generated from the following file:
ugbase/lib_grid/algorithms/remeshing/delaunay_triangulation.cpp