ug4: ug::P1LagrangeElemTransfer< TDomain > Class Template Reference
ug::P1LagrangeElemTransfer< TDomain > Class Template Reference
#include <local_transfer.h>
Public Member Functions
void do_restrict (GridObject *parent, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent)
void do_restrict (Vertex *parent, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent)
P1LagrangeElemTransfer (const LFEID &lfeid)
virtual bool perform_prolongation_on (GridBaseObjectId gbo)
virtual bool perform_restriction_on (GridBaseObjectId gbo)
template<typename TElem >
void prolongate (TElem *parent, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent)
Public Member Functions inherited from ug::ElemProlongationBase< TDomain, P1LagrangeElemTransfer< TDomain > >
virtual void prolongate (Edge *parent)
virtual void prolongate (Face *parent)
virtual void prolongate (Vertex *parent)
virtual void prolongate (Volume *parent)
Public Member Functions inherited from ug::IElemProlongation< TDomain >
virtual void init (ConstSmartPtr< TDomain > spDomain, SmartPtr< TransferValueAccessor > vValueChild, SmartPtr< TransferValueAccessor > vValueParent)
virtual ~IElemProlongation ()
Public Member Functions inherited from ug::ElemRestrictionBase< TDomain, P1LagrangeElemTransfer< TDomain > >
virtual void do_restrict (Edge *parent)
virtual void do_restrict (Face *parent)
virtual void do_restrict (Vertex *parent)
virtual void do_restrict (Volume *parent)
Public Member Functions inherited from ug::IElemRestriction< TDomain >
virtual void init (ConstSmartPtr< TDomain > spDomain, SmartPtr< TransferValueAccessor > vValueChild, SmartPtr< TransferValueAccessor > vValueParent)
virtual ~IElemRestriction ()
Protected Attributes
LFEID m_lfeid
Protected Attributes inherited from ug::IElemProlongation< TDomain >
ConstSmartPtr< TDomain > m_spDomain
ConstSmartPtr< MultiGrid > m_spGrid
SmartPtr< TransferValueAccessor > m_vValueChild
SmartPtr< TransferValueAccessor > m_vValueParent
Protected Attributes inherited from ug::IElemRestriction< TDomain >
ConstSmartPtr< TDomain > m_spDomain
ConstSmartPtr< MultiGrid > m_spGrid
SmartPtr< TransferValueAccessor > m_vValueChild
SmartPtr< TransferValueAccessor > m_vValueParent
Additional Inherited Members
Protected Member Functions inherited from ug::ElemProlongationBase< TDomain, P1LagrangeElemTransfer< TDomain > >
P1LagrangeElemTransfer< TDomain > & getImpl ()
access to implementation
const P1LagrangeElemTransfer< TDomain > & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::ElemRestrictionBase< TDomain, P1LagrangeElemTransfer< TDomain > >
P1LagrangeElemTransfer< TDomain > & getImpl ()
access to implementation
const P1LagrangeElemTransfer< TDomain > & getImpl () const
const access to implementation
Constructor & Destructor Documentation
P1LagrangeElemTransfer()
template<typename TDomain > ug::P1LagrangeElemTransfer< TDomain >::P1LagrangeElemTransfer (const LFEID & lfeid) inline
Member Function Documentation
do_restrict() [1/2]
template<typename TDomain > void ug::P1LagrangeElemTransfer< TDomain >::do_restrict (GridObject * parent, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent) inline
References UG_THROW.
do_restrict() [2/2]
template<typename TDomain > void ug::P1LagrangeElemTransfer< TDomain >::do_restrict (Vertex * parent, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent) inline
References ug::TransferValueAccessor::access_closure(), ug::TransferValueAccessor::access_inner(), ug::MultiGrid::get_child(), ug::MultiGrid::num_children(), ug::TransferValueAccessor::size(), UG_ASSERT, and UG_THROW.
perform_prolongation_on()
template<typename TDomain > virtual bool ug::P1LagrangeElemTransfer< TDomain >::perform_prolongation_on (GridBaseObjectId gbo) inline virtual
Implements ug::IElemProlongation< TDomain >.
References ug::LFEID::dim(), and ug::P1LagrangeElemTransfer< TDomain >::m_lfeid.
perform_restriction_on()
template<typename TDomain > virtual bool ug::P1LagrangeElemTransfer< TDomain >::perform_restriction_on (GridBaseObjectId gbo) inline virtual
Implements ug::IElemRestriction< TDomain >.
References ug::VERTEX.
prolongate()
template<typename TDomain > template<typename TElem > void ug::P1LagrangeElemTransfer< TDomain >::prolongate (TElem * parent, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent) inline
References ug::TransferValueAccessor::access_closure(), ug::TransferValueAccessor::access_inner(), ug::MultiGrid::get_child(), ug::MultiGrid::num_children(), ug::TransferValueAccessor::size(), UG_ASSERT, and UG_THROW.
Member Data Documentation
m_lfeid
template<typename TDomain > LFEID ug::P1LagrangeElemTransfer< TDomain >::m_lfeid protected
Referenced by ug::P1LagrangeElemTransfer< TDomain >::perform_prolongation_on().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/local_transfer.h