ug4: ug::DimFVGeometry< TWorldDim, TDim >::BF Class Reference
ug::DimFVGeometry< TWorldDim, TDim >::BF Class Reference
boundary face
#include <fvho_geom.h>
Public Member Functions
BF ()
number detJ (size_t ip) const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_corner (size_t co) const
return glbal corner number i
const MathVector< worldDim > & global_grad (size_t ip, size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector (size_t ip) const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip (size_t ip) const
global integration point of scvf
const MathMatrix< worldDim, dim > & JTInv (size_t ip) const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t ip, size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector (size_t ip) const
vector of local gradients in ip point
const MathVector< dim > & local_ip (size_t ip) const
local integration point of scvf
size_t node_id () const
index of SubControlVolume of the bf
const MathVector< worldDim > & normal () const
outer normal on bf. Norm is equal to area
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points on scvf
size_t num_sh () const
number of shape functions
number shape (size_t ip, size_t sh) const
value of shape function i in integration point
const number * shape_vector (size_t ip) const
vector of shape functions in ip point
number volume () const
volume of bf
number weight (size_t ip) const
integration weight
Static Public Attributes
static const size_t numCo = traits::NumCornersOfSCVF
Number of corners of bf.
Private Attributes
size_t nip
size_t nodeId
MathVector< worldDim > Normal
size_t nsh
std::vector< number > vDetJ
std::vector< MathVector< worldDim > > vGlobalIP
MathVector< worldDim > vGloPos [numCo]
std::vector< MathMatrix< worldDim, dim > > vJtInv
std::vector< MathVector< dim > > vLocalIP
MathVector< dim > vLocPos [numCo]
MidID vMidID [numCo]
number Vol
std::vector< std::vector< MathVector< worldDim > > > vvGlobalGrad
std::vector< std::vector< MathVector< dim > > > vvLocalGrad
std::vector< std::vector< number > > vvShape
const number * vWeight
Friends
class DimFVGeometry< worldDim, dim >
let outer class access private members
Detailed Description
template<int TWorldDim, int TDim = TWorldDim>
class ug::DimFVGeometry< TWorldDim, TDim >::BF
boundary face
Constructor & Destructor Documentation
BF()
template<int TWorldDim, int TDim = TWorldDim> ug::DimFVGeometry< TWorldDim, TDim >::BF::BF () inline
Member Function Documentation
detJ()
template<int TWorldDim, int TDim = TWorldDim> number ug::DimFVGeometry< TWorldDim, TDim >::BF::detJ (size_t ip) const inline
Determinant of Jacobian in integration point.
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vDetJ.
global_corner()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>& ug::DimFVGeometry< TWorldDim, TDim >::BF::global_corner (size_t co) const inline
return glbal corner number i
global_grad()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>& ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad (size_t ip, size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), ug::DimFVGeometry< TWorldDim, TDim >::BF::num_sh(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vvGlobalGrad.
global_grad_vector()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>* ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad_vector (size_t ip) const inline
vector of global gradients in ip point
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vvGlobalGrad.
global_ip()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>& ug::DimFVGeometry< TWorldDim, TDim >::BF::global_ip (size_t ip) const inline
global integration point of scvf
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vGlobalIP.
JTInv()
template<int TWorldDim, int TDim = TWorldDim> const MathMatrix<worldDim,dim>& ug::DimFVGeometry< TWorldDim, TDim >::BF::JTInv (size_t ip) const inline
Transposed Inverse of Jacobian in integration point.
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vJtInv.
local_corner()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>& ug::DimFVGeometry< TWorldDim, TDim >::BF::local_corner (size_t co) const inline
return local corner number i
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_corners(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vLocPos.
local_grad()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>& ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad (size_t ip, size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), ug::DimFVGeometry< TWorldDim, TDim >::BF::num_sh(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vvLocalGrad.
local_grad_vector()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>* ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad_vector (size_t ip) const inline
vector of local gradients in ip point
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vvLocalGrad.
local_ip()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>& ug::DimFVGeometry< TWorldDim, TDim >::BF::local_ip (size_t ip) const inline
local integration point of scvf
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vLocalIP.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
node_id()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::BF::node_id () const inline
index of SubControlVolume of the bf
References ug::DimFVGeometry< TWorldDim, TDim >::BF::nodeId.
normal()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>& ug::DimFVGeometry< TWorldDim, TDim >::BF::normal () const inline
outer normal on bf. Norm is equal to area
References ug::DimFVGeometry< TWorldDim, TDim >::BF::Normal.
num_corners()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::BF::num_corners () const inline
number of corners, that bound the scvf
References ug::DimFVGeometry< TWorldDim, TDim >::BF::numCo.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::local_corner(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
num_ip()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip () const inline
number of integration points on scvf
References ug::DimFVGeometry< TWorldDim, TDim >::BF::nip.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::detJ(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_ip(), ug::DimFVGeometry< TWorldDim, TDim >::BF::JTInv(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_ip(), ug::DimFVGeometry< TWorldDim, TDim >::BF::shape(), ug::DimFVGeometry< TWorldDim, TDim >::BF::shape_vector(), ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), and ug::DimFVGeometry< TWorldDim, TDim >::BF::weight().
num_sh()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::BF::num_sh () const inline
number of shape functions
References ug::DimFVGeometry< TWorldDim, TDim >::BF::nsh.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
shape()
template<int TWorldDim, int TDim = TWorldDim> number ug::DimFVGeometry< TWorldDim, TDim >::BF::shape (size_t ip, size_t sh) const inline
value of shape function i in integration point
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vvShape.
shape_vector()
template<int TWorldDim, int TDim = TWorldDim> const number* ug::DimFVGeometry< TWorldDim, TDim >::BF::shape_vector (size_t ip) const inline
vector of shape functions in ip point
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vvShape.
volume()
template<int TWorldDim, int TDim = TWorldDim> number ug::DimFVGeometry< TWorldDim, TDim >::BF::volume () const inline
volume of bf
References ug::DimFVGeometry< TWorldDim, TDim >::BF::Vol.
weight()
template<int TWorldDim, int TDim = TWorldDim> number ug::DimFVGeometry< TWorldDim, TDim >::BF::weight (size_t ip) const inline
integration weight
References ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vWeight.
Friends And Related Function Documentation
DimFVGeometry< worldDim, dim >
template<int TWorldDim, int TDim = TWorldDim> friend class DimFVGeometry< worldDim, dim > friend
let outer class access private members
Member Data Documentation
nip
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::BF::nip private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
nodeId
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::BF::nodeId private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::node_id(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
Normal
template<int TWorldDim, int TDim = TWorldDim> MathVector<worldDim> ug::DimFVGeometry< TWorldDim, TDim >::BF::Normal private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::normal(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
nsh
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::BF::nsh private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::num_sh(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
numCo
template<int TWorldDim, int TDim = TWorldDim> const size_t ug::DimFVGeometry< TWorldDim, TDim >::BF::numCo = traits::NumCornersOfSCVF static
Number of corners of bf.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::num_corners().
vDetJ
template<int TWorldDim, int TDim = TWorldDim> std::vector<number> ug::DimFVGeometry< TWorldDim, TDim >::BF::vDetJ private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::detJ(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
vGlobalIP
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathVector<worldDim> > ug::DimFVGeometry< TWorldDim, TDim >::BF::vGlobalIP private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::global_ip(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
vGloPos
template<int TWorldDim, int TDim = TWorldDim> MathVector<worldDim> ug::DimFVGeometry< TWorldDim, TDim >::BF::vGloPos[numCo] private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
vJtInv
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathMatrix<worldDim,dim> > ug::DimFVGeometry< TWorldDim, TDim >::BF::vJtInv private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::JTInv(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
vLocalIP
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathVector<dim> > ug::DimFVGeometry< TWorldDim, TDim >::BF::vLocalIP private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::local_ip(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
vLocPos
template<int TWorldDim, int TDim = TWorldDim> MathVector<dim> ug::DimFVGeometry< TWorldDim, TDim >::BF::vLocPos[numCo] private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::local_corner(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
vMidID
template<int TWorldDim, int TDim = TWorldDim> MidID ug::DimFVGeometry< TWorldDim, TDim >::BF::vMidID[numCo] private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
Vol
template<int TWorldDim, int TDim = TWorldDim> number ug::DimFVGeometry< TWorldDim, TDim >::BF::Vol private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), and ug::DimFVGeometry< TWorldDim, TDim >::BF::volume().
vvGlobalGrad
template<int TWorldDim, int TDim = TWorldDim> std::vector<std::vector<MathVector<worldDim> > > ug::DimFVGeometry< TWorldDim, TDim >::BF::vvGlobalGrad private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::BF::global_grad_vector(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
vvLocalGrad
template<int TWorldDim, int TDim = TWorldDim> std::vector<std::vector<MathVector<dim> > > ug::DimFVGeometry< TWorldDim, TDim >::BF::vvLocalGrad private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::BF::local_grad_vector(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
vvShape
template<int TWorldDim, int TDim = TWorldDim> std::vector<std::vector<number> > ug::DimFVGeometry< TWorldDim, TDim >::BF::vvShape private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::BF::shape(), ug::DimFVGeometry< TWorldDim, TDim >::BF::shape_vector(), and ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
vWeight
template<int TWorldDim, int TDim = TWorldDim> const number* ug::DimFVGeometry< TWorldDim, TDim >::BF::vWeight private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), and ug::DimFVGeometry< TWorldDim, TDim >::BF::weight().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fvho_geom.h