ug4: ug::bridge::LUACompiler Class Reference
ug::bridge::LUACompiler Class Reference
#include <lua_compiler.h>
Public Member Functions
bool call (double *ret, const double *in) const
bool create (const char *functionName, LuaFunctionHandle *pHandle=NULL)
bool createC (const char *functionName, LuaFunctionHandle *pHandle=NULL)
bool createVM (const char *functionName, LuaFunctionHandle *pHandle=NULL)
bool is_valid () const
LUACompiler ()
const std::string & name () const
int num_in () const
int num_out () const
virtual ~LUACompiler ()
Public Attributes
bool bInitialized
bool bVM
LUA2C_Function m_f
int m_iIn
int m_iOut
std::string m_name
Private Types
typedef int(* LUA2C_Function) (double *, const double *)
Private Attributes
DynLibHandle m_libHandle
std::string m_pDyn
VMAdd * vm
Member Typedef Documentation
LUA2C_Function
typedef int(* ug::bridge::LUACompiler::LUA2C_Function) (double *, const double *) private
Constructor & Destructor Documentation
LUACompiler()
ug::bridge::LUACompiler::LUACompiler () inline
References bInitialized, bVM, m_f, m_libHandle, m_name, m_pDyn, and vm.
~LUACompiler()
ug::bridge::LUACompiler::~LUACompiler () virtual
References ug::CloseLibrary(), ug::DID_LUACOMPILER, s, and UG_DLOG.
Member Function Documentation
call()
bool ug::bridge::LUACompiler::call (double * ret, const double * in) const
References UG_ASSERT.
Referenced by ug::LuaUserFunction< TData, dim, TDataIn >::eval_deriv().
create()
bool ug::bridge::LUACompiler::create (const char * functionName, LuaFunctionHandle * pHandle = NULL)
References ug::useLua2VM.
createC()
bool ug::bridge::LUACompiler::createC (const char * functionName, LuaFunctionHandle * pHandle = NULL)
References ug::LUAParserClass::createC(), ug::CreateDirectory(), ug::DID_LUACOMPILER, ug::DirectoryExists(), ug::GetFileLines(), ug::GetLibraryProcedure(), ug::GetLogAssistant(), ug::MakeTmpFile(), ug::LUAParserClass::num_in(), ug::LUAParserClass::num_out(), ug::OpenLibrary(), p, ug::LUAParserClass::parse_luaFunction(), PROFILE_BEGIN_GROUP, ug::ROOT_PATH, UG_DLOG, UG_LOG, and UG_THROW.
createVM()
bool ug::bridge::LUACompiler::createVM (const char * functionName, LuaFunctionHandle * pHandle = NULL)
References ug::LUAParserClass::createVM(), ug::DID_LUACOMPILER, ug::UGError::get_stacktrace(), IF_DEBUG, ug::LUAParserClass::parse_luaFunction(), PROFILE_BEGIN_GROUP, UG_DLOG, and UG_LOG.
is_valid()
bool ug::bridge::LUACompiler::is_valid () const inline
References bInitialized.
name()
const std::string& ug::bridge::LUACompiler::name () const inline
References m_name.
Referenced by ug::LuaUserFunction< TData, dim, TDataIn >::eval_deriv().
num_in()
int ug::bridge::LUACompiler::num_in () const inline
References m_iIn.
num_out()
int ug::bridge::LUACompiler::num_out () const inline
References m_iOut.
Referenced by ug::LuaUserFunction< TData, dim, TDataIn >::eval_deriv().
Member Data Documentation
bInitialized
bool ug::bridge::LUACompiler::bInitialized
Referenced by is_valid(), and LUACompiler().
bVM
bool ug::bridge::LUACompiler::bVM
Referenced by LUACompiler().
m_f
LUA2C_Function ug::bridge::LUACompiler::m_f
Referenced by LUACompiler().
m_iIn
int ug::bridge::LUACompiler::m_iIn
Referenced by num_in().
m_iOut
int ug::bridge::LUACompiler::m_iOut
Referenced by num_out().
m_libHandle
DynLibHandle ug::bridge::LUACompiler::m_libHandle private
Referenced by LUACompiler().
m_name
std::string ug::bridge::LUACompiler::m_name
Referenced by LUACompiler(), and name().
m_pDyn
std::string ug::bridge::LUACompiler::m_pDyn private
Referenced by LUACompiler().
vm
VMAdd* ug::bridge::LUACompiler::vm private
Referenced by LUACompiler().
The documentation for this class was generated from the following files:
ugbase/bindings/lua/compiler/lua_compiler.h
ugbase/bindings/lua/compiler/lua_compiler.cpp