ug4: ug::StdGlobPosData< TImpl, TData, dim, TRet > Class Template Reference
ug::StdGlobPosData< TImpl, TData, dim, TRet > Class Template Reference
#include <std_glob_pos_data.h>
Public Member Functions
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
implement as a UserData
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
implement as a UserData
virtual bool constant () const
returns if data is constant
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
template<int refDim>
void evaluate (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
virtual TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const
returns value for a global position
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
returns value for global positions
virtual bool requires_grid_fct () const
returns if grid function is needed for evaluation
Public Member Functions inherited from ug::StdUserData< StdGlobPosData< TImpl, TData, dim, TRet >, TData, dim, TRet >
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
Public Member Functions inherited from ug::CplUserData< TData, dim, TRet >
bool defined (size_t s, size_t ip) const
returns flag, if data is evaluated (for conditional data)
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
register external callback, invoked when data storage changed
void unregister_storage_callback (DataImport< TData, dim > *obj)
register all callbacks registered by class
const TData & value (size_t s, size_t ip) const
returns the value at ip
TData & value (size_t s, size_t ip)
returns the value at ip
const TData * values (size_t s) const
returns all values for a series
TData * values (size_t s)
returns all values for a series
~CplUserData ()
destructor
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
returns true iff the time point specification is equal to the current one, or not specified
virtual void check_setup () const
returns if the dependent data is ready for evaluation
void clear ()
clear all data
int dim_local_ips () const
returns current local ip dimension
ICplUserData ()
default constructor
const MathVector< dim > & ip (size_t s, size_t ip) const
returns global ip
const MathVector< dim > * ips (size_t s) const
returns global ips
template<int ldim>
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
returns local ip
template<int ldim>
const MathVector< ldim > * local_ips (size_t s) const
returns local ips
virtual SmartPtr< ICplUserData > needed_data (size_t i)
return needed data
size_t num_ip (size_t s) const
returns the number of integration points
virtual size_t num_needed_data () const
number of other Data this data depends on
size_t num_series () const
returns the number of ip series
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
set local positions, returns series id
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
set local positions without the specification of the time point, returns series id
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
set global positions
template<int ldim>
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
sets new local ip positions for a local ip series
void set_subset (int si)
set the subset of evaluation
void set_time_point (size_t timePoint)
sets the current time point
void set_time_point (const size_t seriesId, const int timePointSpec)
sets a new time point for a local ip series
void set_times (const std::vector< number > &vTime)
set evaluation time
int subset () const
returns the subset of evaluation
number time () const
get the current evaluation time
number time (size_t s) const
get the specified evaluation time
size_t time_point ()
returns the current time point
size_t time_point (size_t s) const
returns the time point specification (in particular, the current one, if the own one not specified)
int time_point_specification (size_t s) const
returns the time point specification (note: it may be -1, i.e. not specified)
virtual void update_dof_sizes (const LocalIndices &ind)
resize arrays
virtual bool zero_derivative () const
returns if data depends on solution
virtual ~ICplUserData ()
virtual desctructor
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
Function Group of functions.
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
sets the function pattern for a possibly needed grid function
virtual ~UserDataInfo ()
virtual destructor
Public Member Functions inherited from ug::UserData< TData, dim, TRet >
int get_dim () const
returns dimension
std::string type () const
returns type of data as string (e.g. "Number", "Vector", "Matrix")
TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
Protected Member Functions
TImpl & getImpl ()
access to implementation
const TImpl & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::StdUserData< StdGlobPosData< TImpl, TData, dim, TRet >, TData, dim, TRet >
StdGlobPosData< TImpl, TData, dim, TRet > & getImpl ()
access to implementation
const StdGlobPosData< TImpl, TData, dim, TRet > & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::CplUserData< TData, dim, TRet >
void call_storage_callback () const
calls are registered external storage callbacks
void check_series (size_t s) const
checks in debug mode the correct index
void check_series_ip (size_t s, size_t ip) const
checks in debug mode the correct index
virtual void local_ip_series_added (const size_t seriesID)
resizes the data field, when local ip changed signaled
virtual void local_ip_series_to_be_cleared ()
free the data field memory and set series to zero
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
implement callback, called when local IPs changed
virtual void value_storage_changed (const size_t seriesID)
callback, invoked when storage of data has changed for a series
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
checks in debug mode the correct usage of indices
void check_s_ip (size_t s, size_t ip) const
checks in debug mode the correct usage of indices
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
help function to get local ips
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
callback invoked after global ips have been changed
Additional Inherited Members
Public Types inherited from ug::CplUserData< TData, dim, TRet >
typedef ICplUserData< dim > base_type
type of base class
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
default time point (or -1 if not specified)
int m_locPosDim
dimension of local position (-1 indicates no dim set)
std::vector< const MathVector< 1 > * > m_pvLocIP1d
local ips of dimension 1d-3d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
subset for evaluation
size_t m_timePoint
current time point (used if no explicit specification for series)
std::vector< bool > m_vMayChange
flags if local ips may change
std::vector< size_t > m_vNumIP
number of evaluation points (-1 indicates no ips set)
std::vector< number > m_vTime
time for evaluation
std::vector< int > m_vTimePoint
time points for the series
std::vector< const MathVector< dim > * > m_vvGlobPos
global ips
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Detailed Description
template<typename TImpl, typename TData, int dim, typename TRet = void>
class ug::StdGlobPosData< TImpl, TData, dim, TRet >
This class is a base class for all position and time dependent user data. The data thus does not depend on the a computed solution. In order to use the interface, the deriving class must implement the method:
inline TRet evaluate(TData& D, const MathVector<dim>& x, number time, int si) const
Member Function Documentation
template<typename TImpl, typename TData, int dim, typename TRet = void> virtual void ug::StdGlobPosData< TImpl, TData, dim, TRet >::compute (LocalVector * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) inline virtual
implement as a UserData
Implements ug::ICplUserData< dim >.
Reimplemented in ug::vrl::VRLCondUserNumber< dim >.
template<typename TImpl, typename TData, int dim, typename TRet = void> virtual void ug::StdGlobPosData< TImpl, TData, dim, TRet >::compute (LocalVectorTimeSeries * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) inline virtual
implement as a UserData
Implements ug::ICplUserData< dim >.
template<typename TImpl, typename TData, int dim, typename TRet = void> virtual bool ug::StdGlobPosData< TImpl, TData, dim, TRet >::constant () const inline virtual
returns if data is constant
Reimplemented from ug::ICplUserData< dim >.
template<typename TImpl, typename TData, int dim, typename TRet = void> virtual bool ug::StdGlobPosData< TImpl, TData, dim, TRet >::continuous () const inline virtual
returns if provided data is continuous over geometric object boundaries
Implements ug::UserData< TData, dim, TRet >.
Reimplemented in ug::vrl::VRLCondUserNumber< dim >, and ug::GlobalGridFunctionNumberData< TGridFunction >.
template<typename TImpl, typename TData, int dim, typename TRet = void> template<int refDim> void ug::StdGlobPosData< TImpl, TData, dim, TRet >::evaluate (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< refDim, dim > * vJT = NULL) const inline
template<typename TImpl, typename TData, int dim, typename TRet = void> TImpl& ug::StdGlobPosData< TImpl, TData, dim, TRet >::getImpl () inline protected
access to implementation
Referenced by ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >::compute(), ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >::evaluate(), and ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >::operator()().
template<typename TImpl, typename TData, int dim, typename TRet = void> const TImpl& ug::StdGlobPosData< TImpl, TData, dim, TRet >::getImpl () const inline protected
const access to implementation
template<typename TImpl, typename TData, int dim, typename TRet = void> virtual TRet ug::StdGlobPosData< TImpl, TData, dim, TRet >::operator() (TData & value, const MathVector< dim > & globIP, number time, int si) const inline virtual
returns value for a global position
Implements ug::StdUserData< StdGlobPosData< TImpl, TData, dim, TRet >, TData, dim, TRet >.
template<typename TImpl, typename TData, int dim, typename TRet = void> virtual void ug::StdGlobPosData< TImpl, TData, dim, TRet >::operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const inline virtual
returns value for global positions
Implements ug::StdUserData< StdGlobPosData< TImpl, TData, dim, TRet >, TData, dim, TRet >.
template<typename TImpl, typename TData, int dim, typename TRet = void> virtual bool ug::StdGlobPosData< TImpl, TData, dim, TRet >::requires_grid_fct () const inline virtual
returns if grid function is needed for evaluation
Implements ug::UserData< TData, dim, TRet >.
Reimplemented in ug::vrl::VRLCondUserNumber< dim >.
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/user_data/std_glob_pos_data.h