ug4: ug::AttachmentPipe< TElem, TElemHandler > Class Template Reference
ug::AttachmentPipe< TElem, TElemHandler > Class Template Reference
Handles data which has been attached to the pipe using callbacks for the element.
#include <attachment_pipe.h>
Public Types
typedef attachment_traits< TElem, TElemHandler > atraits
typedef std::list< AttachmentEntry > AttachmentEntryContainer
typedef AttachmentEntryContainer::iterator AttachmentEntryIterator
typedef Hash< uint, AttachmentEntryIterator > AttachmentEntryIteratorHash
typedef AttachmentEntryContainer::const_iterator ConstAttachmentEntryIterator
typedef TElem element
typedef TElemHandler ElementHandler
Public Member Functions
AttachmentPipe ()
AttachmentPipe (typename atraits::ElemHandlerPtr pHandler)
ConstAttachmentEntryIterator attachments_begin () const
ConstAttachmentEntryIterator attachments_end () const
void clear ()
calls both clear_elements and clear_attachments.
void clear_attachments ()
clears registered attachments and associated data but keeps existing elements.
void clear_elements ()
clears elements and associated data but keeps registered attachments
void defragment ()
void detach (IAttachment &attachment)
Removes the data associated with the given attachment from the pipe.
template<class TAttachment >
TAttachment::ValueType * get_data_array (TAttachment &attachment)
Lets you access the raw data array associated with the given attachment.
atraits::ElemHandlerPtr get_elem_handler ()
bool has_attachment (IAttachment &attachment) const
Returns true if the given attachment is currently attached to the pipe.
bool is_fragmented () const
Returns whether the attachment pipe is fragmented.
size_t num_data_entries () const
Returns the size of the associated data arrays.
size_t num_elements () const
Returns the number of registered elements.
void register_element (TElem elem)
Registers a new element at the attachment pipe.
void reserve (size_t numElems)
Reserves memory for element- and data-entries.
void reset_values (size_t dataIndex)
fills the attached data at the given index with the default values.
void unregister_element (const TElem &elem)
Unregisters the given element.
~AttachmentPipe ()
template<class TAttachment >
void attach (TAttachment &attachment, const typename TAttachment::ValueType &defaultValue, uint options)
attaches a new data-array to the pipe.
void attach (IAttachment &attachment, uint options=0)
attaches a new data-array to the pipe.
IAttachmentDataContainer * get_data_container (IAttachment &attachment) const
Returns the data container managing the data array for the given attachment.
template<class TAttachment >
TAttachment::ContainerType * get_data_container (TAttachment &attachment)
Returns the data container managing the data array for the given attachment.
Protected Types
typedef std::stack< size_t > UINTStack
Protected Member Functions
size_t get_container_size ()
void grow_attachment_containers (size_t newMinSize)
void resize_attachment_containers (size_t newSize)
Protected Attributes
AttachmentEntryContainer m_attachmentEntryContainer
AttachmentEntryIteratorHash m_attachmentEntryIteratorHash
size_t m_containerSize
total size of containers.
size_t m_numDataEntries
size_t m_numElements
atraits::ElemHandlerPtr m_pHandler
UINTStack m_stackFreeEntries
holds indices to free entries.
Detailed Description
template<class TElem, class TElemHandler>
class ug::AttachmentPipe< TElem, TElemHandler >
Handles data which has been attached to the pipe using callbacks for the element.
The AttachmentPipe can be used to attach data to a collection of elements. Elements have to be registered at the AttachmentPipe. Using the methods defined in the attachment_traits template class, registered elements are associated with their data-entries.
TODO: enum Options : CopyAllowed
copy_values(TElem from, TElem to)
swap_entry_indices()?!?
Member Typedef Documentation
template<class TElem, class TElemHandler> typedef attachment_traits<TElem, TElemHandler> ug::AttachmentPipe< TElem, TElemHandler >::atraits
template<class TElem, class TElemHandler> typedef std::list<AttachmentEntry> ug::AttachmentPipe< TElem, TElemHandler >::AttachmentEntryContainer
template<class TElem, class TElemHandler> typedef AttachmentEntryContainer::iterator ug::AttachmentPipe< TElem, TElemHandler >::AttachmentEntryIterator
template<class TElem, class TElemHandler> typedef Hash<uint, AttachmentEntryIterator> ug::AttachmentPipe< TElem, TElemHandler >::AttachmentEntryIteratorHash
template<class TElem, class TElemHandler> typedef AttachmentEntryContainer::const_iterator ug::AttachmentPipe< TElem, TElemHandler >::ConstAttachmentEntryIterator
template<class TElem, class TElemHandler> typedef TElem ug::AttachmentPipe< TElem, TElemHandler >::element
template<class TElem, class TElemHandler> typedef TElemHandler ug::AttachmentPipe< TElem, TElemHandler >::ElementHandler
template<class TElem, class TElemHandler> typedef std::stack<size_t> ug::AttachmentPipe< TElem, TElemHandler >::UINTStack protected
Constructor & Destructor Documentation
template<class TElem , class TElemHandler > ug::AttachmentPipe< TElem, TElemHandler >::AttachmentPipe ()
template<class TElem , class TElemHandler > ug::AttachmentPipe< TElem, TElemHandler >::AttachmentPipe (typename atraits::ElemHandlerPtr pHandler)
References ug::AttachmentPipe< TElem, TElemHandler >::~AttachmentPipe().
template<class TElem , class TElemHandler > ug::AttachmentPipe< TElem, TElemHandler >::~AttachmentPipe ()
References ug::AttachmentPipe< TElem, TElemHandler >::clear(), and ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryContainer.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::AttachmentPipe().
Member Function Documentation
template<class TElem , class TElemHandler > template<class TAttachment > void ug::AttachmentPipe< TElem, TElemHandler >::attach (TAttachment & attachment, const typename TAttachment::ValueType & defaultValue, uint options)
attaches a new data-array to the pipe.
Attachs a new attachment and creates a container which holds the data associated with the elements through this attachment. Several overloads exist: You may pass an attachment together with a default value and with an option constant or simply the attachment together with an optional option constant. Not that in the first case the concrete type of the attachment has to be known, whereas in the second case only the interface IAttachment has to be specified.
The option constant is not used by the attachment system but may be used by a user to store a constant with each attachment.
References ug::IAttachment::clone(), ug::AttachmentPipe< TElem, TElemHandler >::get_container_size(), ug::AttachmentPipe< TElem, TElemHandler >::has_attachment(), ug::UID::id(), ug::Hash< TKey, TValue >::insert(), ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryContainer, ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryIteratorHash, and ug::IAttachmentDataContainer::resize().
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::unregister_element().
template<class TElem , class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::attach (IAttachment & attachment, uint options = 0)
attaches a new data-array to the pipe.
Attachs a new attachment and creates a container which holds the data associated with the elements through this attachment. Several overloads exist: You may pass an attachment together with a default value and with an option constant or simply the attachment together with an optional option constant. Not that in the first case the concrete type of the attachment has to be known, whereas in the second case only the interface IAttachment has to be specified.
The option constant is not used by the attachment system but may be used by a user to store a constant with each attachment.
References ug::IAttachment::clone(), ug::IAttachment::create_container(), ug::AttachmentPipe< TElem, TElemHandler >::detach(), ug::AttachmentPipe< TElem, TElemHandler >::get_container_size(), ug::AttachmentPipe< TElem, TElemHandler >::has_attachment(), ug::UID::id(), ug::Hash< TKey, TValue >::insert(), ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryContainer, ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryIteratorHash, and ug::IAttachmentDataContainer::resize().
template<class TElem, class TElemHandler> ConstAttachmentEntryIterator ug::AttachmentPipe< TElem, TElemHandler >::attachments_begin () const inline
Referenced by ug::Grid::clear_attachments(), and ug::PrintAttachmentInfo().
template<class TElem, class TElemHandler> ConstAttachmentEntryIterator ug::AttachmentPipe< TElem, TElemHandler >::attachments_end () const inline
Referenced by ug::Grid::clear_attachments(), and ug::PrintAttachmentInfo().
template<class TElem , class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::clear ()
calls both clear_elements and clear_attachments.
References ug::AttachmentPipe< TElem, TElemHandler >::clear_attachments(), and ug::AttachmentPipe< TElem, TElemHandler >::clear_elements().
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::~AttachmentPipe().
template<class TElem , class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::clear_attachments ()
clears registered attachments and associated data but keeps existing elements.
References ug::Hash< TKey, TValue >::clear(), ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryContainer, ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryIteratorHash, and ug::AttachmentPipe< TElem, TElemHandler >::reset_values().
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::clear(), and ug::AttachmentPipe< TElem, TElemHandler >::clear_elements().
template<class TElem , class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::clear_elements ()
clears elements and associated data but keeps registered attachments
References ug::AttachmentPipe< TElem, TElemHandler >::clear_attachments(), ug::AttachmentPipe< TElem, TElemHandler >::m_numDataEntries, ug::AttachmentPipe< TElem, TElemHandler >::m_numElements, ug::AttachmentPipe< TElem, TElemHandler >::m_stackFreeEntries, and ug::AttachmentPipe< TElem, TElemHandler >::resize_attachment_containers().
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::clear().
template<class TElem , class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::defragment ()
Aligns data with elements and removes unused data-memory.
References ug::attachment_traits< TElem, TElemHandler >::elements_begin(), ug::attachment_traits< TElem, TElemHandler >::elements_end(), ug::attachment_traits< TElem, TElemHandler >::get_data_index(), ug::INVALID_ATTACHMENT_INDEX, ug::AttachmentPipe< TElem, TElemHandler >::is_fragmented(), ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryContainer, ug::AttachmentPipe< TElem, TElemHandler >::m_numDataEntries, ug::AttachmentPipe< TElem, TElemHandler >::m_pHandler, ug::AttachmentPipe< TElem, TElemHandler >::m_stackFreeEntries, ug::AttachmentPipe< TElem, TElemHandler >::num_data_entries(), ug::AttachmentPipe< TElem, TElemHandler >::num_elements(), ug::AttachmentPipe< TElem, TElemHandler >::resize_attachment_containers(), and ug::attachment_traits< TElem, TElemHandler >::set_data_index().
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::get_data_container().
template<class TElem , class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::detach (IAttachment & attachment)
Removes the data associated with the given attachment from the pipe.
References ug::Hash< TKey, TValue >::erase(), ug::Hash< TKey, TValue >::get_entry(), ug::AttachmentPipe< TElem, TElemHandler >::has_attachment(), ug::UID::id(), ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryContainer, and ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryIteratorHash.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::attach(), and ug::Grid::clear_attachments().
template<class TElem , class TElemHandler > size_t ug::AttachmentPipe< TElem, TElemHandler >::get_container_size () inline protected
References ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::AttachmentAccessor(), and ug::AttachmentPipe< TElem, TElemHandler >::m_containerSize.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::attach(), ug::AttachmentPipe< TElem, TElemHandler >::grow_attachment_containers(), and ug::AttachmentPipe< TElem, TElemHandler >::reserve().
template<class TElem , class TElemHandler > template<class TAttachment > TAttachment::ValueType * ug::AttachmentPipe< TElem, TElemHandler >::get_data_array (TAttachment & attachment)
Lets you access the raw data array associated with the given attachment.
If you access several arrays through this method, it is guaranteed that the data associated with one specific object are found at the same indices in those arrays.
Note that if you access the data arrays after a call to defragment, then the i-th data-entry corresponds to the i-th element.
Please not that the pointer may be invalidated through the following operations:
register_element
defragment
clear, clear_elements, clear_attachments
References ug::AttachmentPipe< TElem, TElemHandler >::get_data_container(), and ug::AttachmentPipe< TElem, TElemHandler >::has_attachment().
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::has_attachment().
template<class TElem , class TElemHandler > IAttachmentDataContainer * ug::AttachmentPipe< TElem, TElemHandler >::get_data_container (IAttachment & attachment) const
Returns the data container managing the data array for the given attachment.
References ug::Hash< TKey, TValue >::get_entry(), ug::UID::id(), and ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryIteratorHash.
Referenced by ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::access(), ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::AttachmentAccessor(), and ug::AttachmentPipe< TElem, TElemHandler >::get_data_array().
template<class TElem , class TElemHandler > template<class TAttachment > TAttachment::ContainerType * ug::AttachmentPipe< TElem, TElemHandler >::get_data_container (TAttachment & attachment)
Returns the data container managing the data array for the given attachment.
References ug::AttachmentPipe< TElem, TElemHandler >::defragment(), ug::Hash< TKey, TValue >::get_entry(), and ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryIteratorHash.
template<class TElem, class TElemHandler> atraits::ElemHandlerPtr ug::AttachmentPipe< TElem, TElemHandler >::get_elem_handler () inline
Referenced by ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::access(), and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::AttachmentAccessor().
template<class TElem , class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::grow_attachment_containers (size_t newMinSize) protected
References ug::AttachmentPipe< TElem, TElemHandler >::get_container_size(), and ug::AttachmentPipe< TElem, TElemHandler >::resize_attachment_containers().
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::register_element(), and ug::AttachmentPipe< TElem, TElemHandler >::resize_attachment_containers().
template<class TElem , class TElemHandler > bool ug::AttachmentPipe< TElem, TElemHandler >::has_attachment (IAttachment & attachment) const
Returns true if the given attachment is currently attached to the pipe.
References ug::AttachmentPipe< TElem, TElemHandler >::get_data_array(), ug::Hash< TKey, TValue >::has_entry(), ug::UID::id(), and ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryIteratorHash.
Referenced by ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::access(), ug::AttachmentPipe< TElem, TElemHandler >::attach(), ug::AttachmentPipe< TElem, TElemHandler >::detach(), and ug::AttachmentPipe< TElem, TElemHandler >::get_data_array().
template<class TElem, class TElemHandler> bool ug::AttachmentPipe< TElem, TElemHandler >::is_fragmented () const inline
Returns whether the attachment pipe is fragmented.
The pipe gets fragmented whenever elements are erased. Through the creation of new elements the pipe may be automatically defragmented. Through a call to defragment() the pipe can be defragmented at any time.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::defragment().
template<class TElem, class TElemHandler> size_t ug::AttachmentPipe< TElem, TElemHandler >::num_data_entries () const inline
Returns the size of the associated data arrays.
Note: If the pipe is fragmented, then num_elements and num_data_entries differ. If the pipe however isn't fragmented, then both values are the same.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::defragment(), ug::Grid::edge_fragmentation(), ug::Grid::face_fragmentation(), ug::Grid::vertex_fragmentation(), and ug::Grid::volume_fragmentation().
template<class TElem, class TElemHandler> size_t ug::AttachmentPipe< TElem, TElemHandler >::num_elements () const inline
Returns the number of registered elements.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::defragment(), ug::Grid::edge_fragmentation(), ug::Grid::face_fragmentation(), ug::Grid::vertex_fragmentation(), and ug::Grid::volume_fragmentation().
template<class TElem, class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::register_element (TElem elem)
Registers a new element at the attachment pipe.
Registers the element and reserves memory for all registered attachments. Note that this method may be faster if memory has previously been reserved using reserve_new.
References ug::AttachmentPipe< TElem, TElemHandler >::grow_attachment_containers(), ug::AttachmentPipe< TElem, TElemHandler >::m_numDataEntries, ug::AttachmentPipe< TElem, TElemHandler >::m_numElements, ug::AttachmentPipe< TElem, TElemHandler >::m_pHandler, ug::AttachmentPipe< TElem, TElemHandler >::m_stackFreeEntries, ug::AttachmentPipe< TElem, TElemHandler >::reset_values(), ug::attachment_traits< TElem, TElemHandler >::set_data_index(), and ug::AttachmentPipe< TElem, TElemHandler >::unregister_element().
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::reserve().
template<class TElem , class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::reserve (size_t numElems)
Reserves memory for element- and data-entries.
This method reserves memory for data and elements. Note that numElems specifies the total amount of elements for which data shall be reserved. If numElems is smaller than num_elements, then nothing will be done. Note that a call to reserve does not change num_elements nor num_data_entries.
If you want to reserve space for additional N elements, please call reserve with numElems = num_elements() + N.
Note that reserve is optional and only serves performance benefits.
References ug::AttachmentPipe< TElem, TElemHandler >::get_container_size(), ug::AttachmentPipe< TElem, TElemHandler >::register_element(), and ug::AttachmentPipe< TElem, TElemHandler >::resize_attachment_containers().
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::reset_values().
template<class TElem , class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::reset_values (size_t dataIndex)
fills the attached data at the given index with the default values.
References ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryContainer, and ug::AttachmentPipe< TElem, TElemHandler >::reserve().
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::clear_attachments(), and ug::AttachmentPipe< TElem, TElemHandler >::register_element().
template<class TElem , class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::resize_attachment_containers (size_t newSize) protected
References ug::AttachmentPipe< TElem, TElemHandler >::grow_attachment_containers(), ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryContainer, and ug::AttachmentPipe< TElem, TElemHandler >::m_containerSize.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::clear_elements(), ug::AttachmentPipe< TElem, TElemHandler >::defragment(), ug::AttachmentPipe< TElem, TElemHandler >::grow_attachment_containers(), and ug::AttachmentPipe< TElem, TElemHandler >::reserve().
template<class TElem, class TElemHandler > void ug::AttachmentPipe< TElem, TElemHandler >::unregister_element (const TElem & elem)
Unregisters the given element.
Unregisters the given element but does not yet clear associated data. Indeed the memory is kept until defragment is called or new elements reuse the memory.
References ug::AttachmentPipe< TElem, TElemHandler >::attach(), ug::attachment_traits< TElem, TElemHandler >::get_data_index(), ug::AttachmentPipe< TElem, TElemHandler >::m_numElements, ug::AttachmentPipe< TElem, TElemHandler >::m_pHandler, and ug::AttachmentPipe< TElem, TElemHandler >::m_stackFreeEntries.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::register_element().
Member Data Documentation
template<class TElem, class TElemHandler> AttachmentEntryContainer ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryContainer protected
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::attach(), ug::AttachmentPipe< TElem, TElemHandler >::clear_attachments(), ug::AttachmentPipe< TElem, TElemHandler >::defragment(), ug::AttachmentPipe< TElem, TElemHandler >::detach(), ug::AttachmentPipe< TElem, TElemHandler >::reset_values(), ug::AttachmentPipe< TElem, TElemHandler >::resize_attachment_containers(), and ug::AttachmentPipe< TElem, TElemHandler >::~AttachmentPipe().
template<class TElem, class TElemHandler> AttachmentEntryIteratorHash ug::AttachmentPipe< TElem, TElemHandler >::m_attachmentEntryIteratorHash protected
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::attach(), ug::AttachmentPipe< TElem, TElemHandler >::clear_attachments(), ug::AttachmentPipe< TElem, TElemHandler >::detach(), ug::AttachmentPipe< TElem, TElemHandler >::get_data_container(), and ug::AttachmentPipe< TElem, TElemHandler >::has_attachment().
template<class TElem, class TElemHandler> size_t ug::AttachmentPipe< TElem, TElemHandler >::m_containerSize protected
total size of containers.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::get_container_size(), and ug::AttachmentPipe< TElem, TElemHandler >::resize_attachment_containers().
template<class TElem, class TElemHandler> size_t ug::AttachmentPipe< TElem, TElemHandler >::m_numDataEntries protected
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::clear_elements(), ug::AttachmentPipe< TElem, TElemHandler >::defragment(), and ug::AttachmentPipe< TElem, TElemHandler >::register_element().
template<class TElem, class TElemHandler> size_t ug::AttachmentPipe< TElem, TElemHandler >::m_numElements protected
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::clear_elements(), ug::AttachmentPipe< TElem, TElemHandler >::register_element(), and ug::AttachmentPipe< TElem, TElemHandler >::unregister_element().
template<class TElem, class TElemHandler> atraits::ElemHandlerPtr ug::AttachmentPipe< TElem, TElemHandler >::m_pHandler protected
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::defragment(), ug::AttachmentPipe< TElem, TElemHandler >::register_element(), and ug::AttachmentPipe< TElem, TElemHandler >::unregister_element().
template<class TElem, class TElemHandler> UINTStack ug::AttachmentPipe< TElem, TElemHandler >::m_stackFreeEntries protected
holds indices to free entries.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::clear_elements(), ug::AttachmentPipe< TElem, TElemHandler >::defragment(), ug::AttachmentPipe< TElem, TElemHandler >::register_element(), and ug::AttachmentPipe< TElem, TElemHandler >::unregister_element().
The documentation for this class was generated from the following files:
ugbase/lib_grid/attachments/attachment_pipe.h
ugbase/lib_grid/attachments/attachment_pipe.hpp