ug4: ug::BGLParallelMatrix< T > Class Template Reference
ug::BGLParallelMatrix< T > Class Template Reference
#include <parallel_matrix.h>
Classes
class adjacency_iterator
class edge
struct filter_local
class out_edge_iterator
class vertex_iterator_
Public Types
typedef T::const_row_iterator const_row_iterator
typedef detail::bglp_vertex_descriptor vertex_descriptor
typedef boost::filter_iterator< filter_local, vertex_iterator_ > vertex_iterator
Public Member Functions
adjacency_iterator begin_adjacent_vertices (int row) const
const_row_iterator begin_col (int col) const
out_edge_iterator begin_out_edges (int row) const
vertex_iterator begin_vertices () const
BGLParallelMatrix (T const *m=nullptr)
int degree (int v) const
adjacency_iterator end_adjacent_vertices (int row) const
const_row_iterator end_col (int col) const
out_edge_iterator end_out_edges (int row) const
vertex_iterator end_vertices () const
int in_degree (int v) const
int num_cols () const
int num_connections (int v) const
int num_rows () const
BGLParallelMatrix & operator= (BGLParallelMatrix const &o)
int out_degree (int v) const
void refresh ()
Public Attributes
ghosts _ghosts
T const * _matrix
owners _owners
Private Types
typedef boost::graph_traits< T >::out_edge_iterator base_edge_iterator
typedef boost::graph_traits< T >::vertex_iterator base_vertex_iterator
typedef std::vector< int > ghosts
typedef std::vector< int > owners
Private Attributes
T _matrix_transpose
Member Typedef Documentation
base_edge_iterator
template<class T > typedef boost::graph_traits<T>::out_edge_iterator ug::BGLParallelMatrix< T >::base_edge_iterator private
base_vertex_iterator
template<class T > typedef boost::graph_traits<T>::vertex_iterator ug::BGLParallelMatrix< T >::base_vertex_iterator private
const_row_iterator
template<class T > typedef T::const_row_iterator ug::BGLParallelMatrix< T >::const_row_iterator
ghosts
template<class T > typedef std::vector<int> ug::BGLParallelMatrix< T >::ghosts private
owners
template<class T > typedef std::vector<int> ug::BGLParallelMatrix< T >::owners private
vertex_descriptor
template<class T > typedef detail::bglp_vertex_descriptor ug::BGLParallelMatrix< T >::vertex_descriptor
vertex_iterator
template<class T > typedef boost::filter_iterator<filter_local, vertex_iterator_> ug::BGLParallelMatrix< T >::vertex_iterator
Constructor & Destructor Documentation
BGLParallelMatrix()
template<class T > ug::BGLParallelMatrix< T >::BGLParallelMatrix (T const * m = nullptr) inline explicit
References ug::BGLParallelMatrix< T >::refresh(), and untested.
Member Function Documentation
begin_adjacent_vertices()
template<class T > adjacency_iterator ug::BGLParallelMatrix< T >::begin_adjacent_vertices (int row) const inline
References ug::BGLParallelMatrix< T >::_ghosts, ug::BGLParallelMatrix< T >::_matrix, ug::BGLParallelMatrix< T >::_owners, boost::adjacent_vertices(), p, and untested.
Referenced by boost::adjacent_vertices().
begin_col()
template<class T > const_row_iterator ug::BGLParallelMatrix< T >::begin_col (int col) const inline
References ug::BGLParallelMatrix< T >::_matrix_transpose.
begin_out_edges()
template<class T > out_edge_iterator ug::BGLParallelMatrix< T >::begin_out_edges (int row) const inline
References ug::BGLParallelMatrix< T >::_ghosts, ug::BGLParallelMatrix< T >::_matrix, ug::BGLParallelMatrix< T >::_owners, boost::out_edges(), and p.
Referenced by boost::out_edges().
begin_vertices()
template<class T > vertex_iterator ug::BGLParallelMatrix< T >::begin_vertices () const inline
References ug::BGLParallelMatrix< T >::_matrix, ug::BGLParallelMatrix< T >::_owners, and boost::vertices().
Referenced by boost::vertices().
degree()
template<class T > int ug::BGLParallelMatrix< T >::degree (int v) const inline
References ug::BGLParallelMatrix< T >::out_degree(), and untested.
end_adjacent_vertices()
template<class T > adjacency_iterator ug::BGLParallelMatrix< T >::end_adjacent_vertices (int row) const inline
References ug::BGLParallelMatrix< T >::_ghosts, ug::BGLParallelMatrix< T >::_matrix, ug::BGLParallelMatrix< T >::_owners, boost::adjacent_vertices(), p, and untested.
Referenced by boost::adjacent_vertices().
end_col()
template<class T > const_row_iterator ug::BGLParallelMatrix< T >::end_col (int col) const inline
References ug::BGLParallelMatrix< T >::_matrix_transpose.
end_out_edges()
template<class T > out_edge_iterator ug::BGLParallelMatrix< T >::end_out_edges (int row) const inline
References ug::BGLParallelMatrix< T >::_ghosts, ug::BGLParallelMatrix< T >::_matrix, ug::BGLParallelMatrix< T >::_owners, boost::out_edges(), and p.
Referenced by boost::out_edges().
end_vertices()
template<class T > vertex_iterator ug::BGLParallelMatrix< T >::end_vertices () const inline
References ug::BGLParallelMatrix< T >::_matrix, ug::BGLParallelMatrix< T >::_owners, and boost::vertices().
Referenced by boost::vertices().
in_degree()
template<class T > int ug::BGLParallelMatrix< T >::in_degree (int v) const inline
References ug::BGLParallelMatrix< T >::_matrix, ug::BGLParallelMatrix< T >::_matrix_transpose, ug::BGLParallelMatrix< T >::num_rows(), and boost::out_degree().
Referenced by ug::BGLParallelMatrix< T >::out_degree().
num_cols()
template<class T > int ug::BGLParallelMatrix< T >::num_cols () const inline
References ug::BGLParallelMatrix< T >::num_rows(), and untested.
num_connections()
template<class T > int ug::BGLParallelMatrix< T >::num_connections (int v) const inline
References ug::BGLParallelMatrix< T >::_matrix, ug::BGLParallelMatrix< T >::_matrix_transpose, and ug::BGLParallelMatrix< T >::num_rows().
num_rows()
template<class T > int ug::BGLParallelMatrix< T >::num_rows () const inline
References ug::BGLParallelMatrix< T >::_matrix.
Referenced by ug::BGLParallelMatrix< T >::in_degree(), ug::BGLParallelMatrix< T >::num_cols(), and ug::BGLParallelMatrix< T >::num_connections().
operator=()
template<class T > BGLParallelMatrix& ug::BGLParallelMatrix< T >::operator= (BGLParallelMatrix< T > const & o) inline
References ug::BGLParallelMatrix< T >::_matrix, ug::BGLParallelMatrix< T >::_matrix_transpose, and untested.
out_degree()
template<class T > int ug::BGLParallelMatrix< T >::out_degree (int v) const inline
References ug::BGLParallelMatrix< T >::in_degree().
Referenced by ug::BGLParallelMatrix< T >::degree().
refresh()
template<class T > void ug::BGLParallelMatrix< T >::refresh
References ug::BGLParallelMatrix< T >::_ghosts, ug::BGLParallelMatrix< T >::_matrix, ug::BGLParallelMatrix< T >::_owners, pcl::SingleLevelLayout< TInterface >::begin(), pcl::SingleLevelLayout< TInterface >::end(), pcl::SingleLevelLayout< TInterface >::interface(), pcl::SingleLevelLayout< TInterface >::proc_id(), pcl::ProcessCommunicator::receive_data(), pcl::ProcessCommunicator::send_data(), and pcl::OrderedInterface< TType, TContainer, TAlloc >::size().
Referenced by ug::BGLParallelMatrix< T >::BGLParallelMatrix().
Member Data Documentation
_ghosts
template<class T > ghosts ug::BGLParallelMatrix< T >::_ghosts
Referenced by ug::BGLParallelMatrix< T >::begin_adjacent_vertices(), ug::BGLParallelMatrix< T >::begin_out_edges(), ug::BGLParallelMatrix< T >::end_adjacent_vertices(), ug::BGLParallelMatrix< T >::end_out_edges(), and ug::BGLParallelMatrix< T >::refresh().
_matrix
template<class T > T const* ug::BGLParallelMatrix< T >::_matrix
Referenced by ug::BGLParallelMatrix< T >::begin_adjacent_vertices(), ug::BGLParallelMatrix< T >::begin_out_edges(), ug::BGLParallelMatrix< T >::begin_vertices(), ug::BGLParallelMatrix< T >::end_adjacent_vertices(), ug::BGLParallelMatrix< T >::end_out_edges(), ug::BGLParallelMatrix< T >::end_vertices(), ug::BGLParallelMatrix< T >::in_degree(), ug::BGLParallelMatrix< T >::num_connections(), ug::BGLParallelMatrix< T >::num_rows(), ug::BGLParallelMatrix< T >::operator=(), and ug::BGLParallelMatrix< T >::refresh().
_matrix_transpose
template<class T > T ug::BGLParallelMatrix< T >::_matrix_transpose private
Referenced by ug::BGLParallelMatrix< T >::begin_col(), ug::BGLParallelMatrix< T >::end_col(), ug::BGLParallelMatrix< T >::in_degree(), ug::BGLParallelMatrix< T >::num_connections(), and ug::BGLParallelMatrix< T >::operator=().
_owners
template<class T > owners ug::BGLParallelMatrix< T >::_owners
Referenced by ug::BGLParallelMatrix< T >::begin_adjacent_vertices(), ug::BGLParallelMatrix< T >::begin_out_edges(), ug::BGLParallelMatrix< T >::begin_vertices(), ug::BGLParallelMatrix< T >::end_adjacent_vertices(), ug::BGLParallelMatrix< T >::end_out_edges(), ug::BGLParallelMatrix< T >::end_vertices(), and ug::BGLParallelMatrix< T >::refresh().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/graph_interface/parallel_matrix.h