ug4: ug::MathMatrix< N, M, T > Class Template Reference
ug::MathMatrix< N, M, T > Class Template Reference
ugbase » Math » Matrix
A class for fixed size, dense matrices.
#include <math_matrix.h>
Public Types
typedef std::size_t size_type
typedef T value_type
Public Member Functions
void assign (const MathVector< N, value_type > &vec, const std::size_t row)
value_type & entry (std::size_t row, std::size_t col)
const value_type & entry (std::size_t row, std::size_t col) const
MathMatrix ()
MathMatrix (const MathMatrix &v)
std::size_t num_cols () const
std::size_t num_rows () const
value_type & operator() (std::size_t row, std::size_t col)
const value_type & operator() (std::size_t row, std::size_t col) const
value_type operator* (const MathMatrix &v) const
Multiplies the matrix element-wise with another matrix and sums up the entries.
MathMatrix & operator*= (const value_type &val)
Multiplies all elements of the matrix with the given value.
MathMatrix & operator+= (const MathMatrix &B)
Adds a matrix to 'this' one: \(A_{this} \leftarrow A_{this} + B\).
MathMatrix & operator+= (const value_type &val)
Adds the given value to all elements of the matrix.
MathMatrix & operator-= (const MathMatrix &B)
Subtracts a matrix from 'this' one: \(A_{this} \leftarrow A_{this} - B\).
MathMatrix & operator-= (const value_type &val)
Subtracts the given value from all elements of the matrix.
MathMatrix & operator/= (const value_type &val)
Divides all elements of the matrix by the given value.
MathMatrix & operator= (const MathMatrix &v)
Assigns the elements of the given matrix to this one.
MathMatrix & operator= (const value_type &val)
Assigns the given value to all elements of the matrix.
value_type * operator[] (std::size_t index)
const value_type * operator[] (std::size_t index) const
Static Public Attributes
static const std::size_t ColSize = M
static const std::size_t RowSize = N
Protected Member Functions
void assign (const MathMatrix &v)
Protected Attributes
value_type m_data [N][M]
Detailed Description
template<std::size_t N, std::size_t M, typename T>
class ug::MathMatrix< N, M, T >
A class for fixed size, dense matrices.
A static memory NxM matrix
Member Typedef Documentation
size_type
template<std::size_t N, std::size_t M, typename T > typedef std::size_t ug::MathMatrix< N, M, T >::size_type
value_type
template<std::size_t N, std::size_t M, typename T > typedef T ug::MathMatrix< N, M, T >::value_type
Constructor & Destructor Documentation
MathMatrix() [1/2]
template<std::size_t N, std::size_t M, typename T > ug::MathMatrix< N, M, T >::MathMatrix () inline
MathMatrix() [2/2]
template<std::size_t N, std::size_t M, typename T > ug::MathMatrix< N, M, T >::MathMatrix (const MathMatrix< N, M, T > & v) inline
References ug::MathMatrix< N, M, T >::assign().
Member Function Documentation
assign() [1/2]
template<std::size_t N, std::size_t M, typename T > void ug::MathMatrix< N, M, T >::assign (const MathMatrix< N, M, T > & v) inline protected
References ug::MathMatrix< N, M, T >::m_data.
assign() [2/2]
template<std::size_t N, std::size_t M, typename T > void ug::MathMatrix< N, M, T >::assign (const MathVector< N, value_type > & vec, const std::size_t row) inline
References ug::MathMatrix< N, M, T >::m_data, ug::MathVector< N, T >::Size, and UG_ASSERT.
Referenced by ug::MathMatrix< N, M, T >::MathMatrix(), and ug::MathMatrix< N, M, T >::operator=().
entry() [1/2]
template<std::size_t N, std::size_t M, typename T > value_type& ug::MathMatrix< N, M, T >::entry (std::size_t row, std::size_t col) inline
Referenced by ug::operator<<().
entry() [2/2]
template<std::size_t N, std::size_t M, typename T > const value_type& ug::MathMatrix< N, M, T >::entry (std::size_t row, std::size_t col) const inline
num_cols()
template<std::size_t N, std::size_t M, typename T > std::size_t ug::MathMatrix< N, M, T >::num_cols () const inline
Referenced by ug::IsFiniteAndNotTooBig(), and ug::Transpose().
num_rows()
template<std::size_t N, std::size_t M, typename T > std::size_t ug::MathMatrix< N, M, T >::num_rows () const inline
Referenced by ug::IsFiniteAndNotTooBig(), and ug::Transpose().
operator()() [1/2]
template<std::size_t N, std::size_t M, typename T > value_type& ug::MathMatrix< N, M, T >::operator() (std::size_t row, std::size_t col) inline
References ug::MathMatrix< N, M, T >::m_data, and UG_ASSERT.
operator()() [2/2]
template<std::size_t N, std::size_t M, typename T > const value_type& ug::MathMatrix< N, M, T >::operator() (std::size_t row, std::size_t col) const inline
References ug::MathMatrix< N, M, T >::m_data, and UG_ASSERT.
operator*()
template<std::size_t N, std::size_t M, typename T > value_type ug::MathMatrix< N, M, T >::operator* (const MathMatrix< N, M, T > & v) const inline
Multiplies the matrix element-wise with another matrix and sums up the entries.
Parameters
v The Matrix.
Returns
A scalar value of the element-wise summed up products
References ug::MathMatrix< N, M, T >::m_data.
operator*=()
template<std::size_t N, std::size_t M, typename T > MathMatrix& ug::MathMatrix< N, M, T >::operator*= (const value_type & val) inline
Multiplies all elements of the matrix with the given value.
Parameters
val The factor.
Returns
A reference to this matrix.
References ug::MathMatrix< N, M, T >::m_data.
operator+=() [1/2]
template<std::size_t N, std::size_t M, typename T > MathMatrix& ug::MathMatrix< N, M, T >::operator+= (const MathMatrix< N, M, T > & B) inline
Adds a matrix to 'this' one: \(A_{this} \leftarrow A_{this} + B\).
Parameters
B The matrix to be added.
Returns
A reference to this matrix.
References ug::MathMatrix< N, M, T >::m_data.
operator+=() [2/2]
template<std::size_t N, std::size_t M, typename T > MathMatrix& ug::MathMatrix< N, M, T >::operator+= (const value_type & val) inline
Adds the given value to all elements of the matrix.
Parameters
val The value to be added.
Returns
A reference to this matrix.
References ug::MathMatrix< N, M, T >::m_data.
operator-=() [1/2]
template<std::size_t N, std::size_t M, typename T > MathMatrix& ug::MathMatrix< N, M, T >::operator-= (const MathMatrix< N, M, T > & B) inline
Subtracts a matrix from 'this' one: \(A_{this} \leftarrow A_{this} - B\).
Parameters
B The matrix to be subtracted.
Returns
A reference to this matrix.
References ug::MathMatrix< N, M, T >::m_data.
operator-=() [2/2]
template<std::size_t N, std::size_t M, typename T > MathMatrix& ug::MathMatrix< N, M, T >::operator-= (const value_type & val) inline
Subtracts the given value from all elements of the matrix.
Parameters
val The value to be subtracted.
Returns
A reference to this matrix.
References ug::MathMatrix< N, M, T >::m_data.
operator/=()
template<std::size_t N, std::size_t M, typename T > MathMatrix& ug::MathMatrix< N, M, T >::operator/= (const value_type & val) inline
Divides all elements of the matrix by the given value.
Parameters
val The divisor.
Returns
A reference to this matrix.
References ug::MathMatrix< N, M, T >::m_data.
operator=() [1/2]
template<std::size_t N, std::size_t M, typename T > MathMatrix& ug::MathMatrix< N, M, T >::operator= (const MathMatrix< N, M, T > & v) inline
Assigns the elements of the given matrix to this one.
Parameters
v The matrix to be assigned.
Returns
A reference to this matrix.
References ug::MathMatrix< N, M, T >::assign().
operator=() [2/2]
template<std::size_t N, std::size_t M, typename T > MathMatrix& ug::MathMatrix< N, M, T >::operator= (const value_type & val) inline
Assigns the given value to all elements of the matrix.
Parameters
val The value to be assigned to the matrix.
Returns
A reference to this matrix.
References ug::MathMatrix< N, M, T >::m_data.
operator[]() [1/2]
template<std::size_t N, std::size_t M, typename T > value_type* ug::MathMatrix< N, M, T >::operator[] (std::size_t index) inline
References ug::MathMatrix< N, M, T >::m_data, and UG_ASSERT.
operator[]() [2/2]
template<std::size_t N, std::size_t M, typename T > const value_type* ug::MathMatrix< N, M, T >::operator[] (std::size_t index) const inline
References ug::MathMatrix< N, M, T >::m_data, and UG_ASSERT.
Member Data Documentation
ColSize
template<std::size_t N, std::size_t M, typename T > const std::size_t ug::MathMatrix< N, M, T >::ColSize = M static
m_data
template<std::size_t N, std::size_t M, typename T > value_type ug::MathMatrix< N, M, T >::m_data[N][M] protected
Referenced by ug::MathMatrix< N, M, T >::assign(), ug::MathMatrix< N, M, T >::operator()(), ug::MathMatrix< N, M, T >::operator*(), ug::MathMatrix< N, M, T >::operator*=(), ug::MathMatrix< N, M, T >::operator+=(), ug::MathMatrix< N, M, T >::operator-=(), ug::MathMatrix< N, M, T >::operator/=(), ug::MathMatrix< N, M, T >::operator=(), and ug::MathMatrix< N, M, T >::operator[]().
RowSize
template<std::size_t N, std::size_t M, typename T > const std::size_t ug::MathMatrix< N, M, T >::RowSize = N static
The documentation for this class was generated from the following file:
ugbase/common/math/math_vector_matrix/math_matrix.h