ug4: ug::CompositeUserData< TData, dim, TRet > Class Template Reference
ug::CompositeUserData< TData, dim, TRet > Class Template Reference
This is a compositum for user data from different subsets.
#include <composite_user_data.h>
Public Types
typedef UserData< TData, dim, TRet > base_type
typedef std::map< int, ref_type > map_type
typedef SmartPtr< base_type > ref_type
Public Types inherited from ug::UserData< TData, dim, void >
typedef TData data_type
typedef void return_type
Public Member Functions
void add (int si, ref_type ref)
! Add 'UserData' for given subset index.
CompositeUserData (bool continuous)
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
ref_type get (int si)
SmartPtr< TCplUserData > get_coupled (int si)
bool has (int si)
bool is_coupled (int si)
virtual TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const
returns value for a global position
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
returns values for global positions
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
virtual bool requires_grid_fct () const
returns true, if at least one of the underlying UserData requires grid functions.
virtual ~CompositeUserData ()
Public Member Functions inherited from ug::UserData< TData, dim, void >
int get_dim () const
returns dimension
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, Vertex *vrt) const
returns a value at a vertex
std::string type () const
returns type of data as string (e.g. "Number", "Vector", "Matrix")
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
Function Group of functions.
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
sets the function pattern for a possibly needed grid function
virtual ~UserDataInfo ()
virtual destructor
Protected Types
typedef CplUserData< TData, dim, TRet > TCplUserData
Protected Member Functions
map_type::const_iterator find (int si) const
Protected Attributes
bool m_bRequiresGridFunction
bool m_continuous
map_type m_map
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Detailed Description
template<typename TData, int dim, typename TRet = void>
class ug::CompositeUserData< TData, dim, TRet >
This is a compositum for user data from different subsets.
This is handy, but the implementation is rather slow.
Member Typedef Documentation
base_type
template<typename TData , int dim, typename TRet = void> typedef UserData<TData, dim, TRet> ug::CompositeUserData< TData, dim, TRet >::base_type
map_type
template<typename TData , int dim, typename TRet = void> typedef std::map<int, ref_type> ug::CompositeUserData< TData, dim, TRet >::map_type
ref_type
template<typename TData , int dim, typename TRet = void> typedef SmartPtr<base_type> ug::CompositeUserData< TData, dim, TRet >::ref_type
TCplUserData
template<typename TData , int dim, typename TRet = void> typedef CplUserData<TData, dim, TRet> ug::CompositeUserData< TData, dim, TRet >::TCplUserData protected
Constructor & Destructor Documentation
CompositeUserData()
template<typename TData , int dim, typename TRet = void> ug::CompositeUserData< TData, dim, TRet >::CompositeUserData (bool continuous) inline
~CompositeUserData()
template<typename TData , int dim, typename TRet = void> virtual ug::CompositeUserData< TData, dim, TRet >::~CompositeUserData () inline virtual
Member Function Documentation
add()
template<typename TData , int dim, typename TRet = void> void ug::CompositeUserData< TData, dim, TRet >::add (int si, ref_type ref) inline
! Add 'UserData' for given subset index.
References ug::CompositeUserData< TData, dim, TRet >::m_bRequiresGridFunction, ug::CompositeUserData< TData, dim, TRet >::m_continuous, and ug::CompositeUserData< TData, dim, TRet >::m_map.
continuous()
template<typename TData , int dim, typename TRet = void> virtual bool ug::CompositeUserData< TData, dim, TRet >::continuous () const inline virtual
returns if provided data is continuous over geometric object boundaries
Implements ug::UserData< TData, dim, void >.
References ug::CompositeUserData< TData, dim, TRet >::m_continuous.
find()
template<typename TData , int dim, typename TRet = void> map_type::const_iterator ug::CompositeUserData< TData, dim, TRet >::find (int si) const inline protected
References ug::CompositeUserData< TData, dim, TRet >::m_map, and UG_ASSERT.
Referenced by ug::CompositeUserData< TData, dim, TRet >::get(), ug::CompositeUserData< TData, dim, TRet >::get_coupled(), ug::CompositeUserData< TData, dim, TRet >::has(), ug::CompositeUserData< TData, dim, TRet >::is_coupled(), and ug::CompositeUserData< TData, dim, TRet >::operator()().
get()
template<typename TData , int dim, typename TRet = void> ref_type ug::CompositeUserData< TData, dim, TRet >::get (int si) inline
References ug::CompositeUserData< TData, dim, TRet >::find().
get_coupled()
template<typename TData , int dim, typename TRet = void> SmartPtr<TCplUserData> ug::CompositeUserData< TData, dim, TRet >::get_coupled (int si) inline
References ug::CompositeUserData< TData, dim, TRet >::find().
has()
template<typename TData , int dim, typename TRet = void> bool ug::CompositeUserData< TData, dim, TRet >::has (int si) inline
References ug::CompositeUserData< TData, dim, TRet >::find(), and ug::CompositeUserData< TData, dim, TRet >::m_map.
Referenced by ug::CompositeUserData< TData, dim, TRet >::is_coupled().
is_coupled()
template<typename TData , int dim, typename TRet = void> bool ug::CompositeUserData< TData, dim, TRet >::is_coupled (int si) inline
References ug::CompositeUserData< TData, dim, TRet >::find(), and ug::CompositeUserData< TData, dim, TRet >::has().
operator()() [1/5]
template<typename TData , int dim, typename TRet = void> virtual TRet ug::CompositeUserData< TData, dim, TRet >::operator() (TData & value, const MathVector< dim > & globIP, number time, int si) const inline virtual
returns value for a global position
Implements ug::UserData< TData, dim, void >.
References ug::CompositeUserData< TData, dim, TRet >::find().
operator()() [2/5]
template<typename TData , int dim, typename TRet = void> virtual void ug::CompositeUserData< TData, dim, TRet >::operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const inline virtual
returns values for global positions
Implements ug::UserData< TData, dim, void >.
References ug::CompositeUserData< TData, dim, TRet >::find().
operator()() [3/5]
template<typename TData , int dim, typename TRet = void> virtual void ug::CompositeUserData< TData, dim, TRet >::operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< 1, dim > * vJT = NULL) const inline virtual
returns values for local and global positions
Implements ug::UserData< TData, dim, void >.
References ug::CompositeUserData< TData, dim, TRet >::find().
operator()() [4/5]
template<typename TData , int dim, typename TRet = void> virtual void ug::CompositeUserData< TData, dim, TRet >::operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< 2, dim > * vJT = NULL) const inline virtual
returns values for local and global positions
Implements ug::UserData< TData, dim, void >.
References ug::CompositeUserData< TData, dim, TRet >::find().
operator()() [5/5]
template<typename TData , int dim, typename TRet = void> virtual void ug::CompositeUserData< TData, dim, TRet >::operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< 3, dim > * vJT = NULL) const inline virtual
returns values for local and global positions
Implements ug::UserData< TData, dim, void >.
References ug::CompositeUserData< TData, dim, TRet >::find().
requires_grid_fct()
template<typename TData , int dim, typename TRet = void> virtual bool ug::CompositeUserData< TData, dim, TRet >::requires_grid_fct () const inline virtual
returns true, if at least one of the underlying UserData requires grid functions.
Implements ug::UserData< TData, dim, void >.
References ug::CompositeUserData< TData, dim, TRet >::m_bRequiresGridFunction.
Member Data Documentation
m_bRequiresGridFunction
template<typename TData , int dim, typename TRet = void> bool ug::CompositeUserData< TData, dim, TRet >::m_bRequiresGridFunction protected
Referenced by ug::CompositeUserData< TData, dim, TRet >::add(), and ug::CompositeUserData< TData, dim, TRet >::requires_grid_fct().
m_continuous
template<typename TData , int dim, typename TRet = void> bool ug::CompositeUserData< TData, dim, TRet >::m_continuous protected
Referenced by ug::CompositeUserData< TData, dim, TRet >::add(), and ug::CompositeUserData< TData, dim, TRet >::continuous().
m_map
template<typename TData , int dim, typename TRet = void> map_type ug::CompositeUserData< TData, dim, TRet >::m_map protected
Referenced by ug::CompositeUserData< TData, dim, TRet >::add(), ug::CompositeUserData< TData, dim, TRet >::find(), and ug::CompositeUserData< TData, dim, TRet >::has().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/user_data/common_user_data/composite_user_data.h