ug4: ug::DimFEGeometry< TWorldDim, TRefDim >::BF Class Reference
ug::DimFEGeometry< TWorldDim, TRefDim >::BF Class Reference
boundary face
#include <fe_geom.h>
Public Member Functions
BF ()
number detJ (size_t ip) const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_grad (size_t ip, size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector (size_t ip) const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip (size_t ip) const
global integration point of scvf
const MathMatrix< worldDim, dim > & JTInv (size_t ip) const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_grad (size_t ip, size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector (size_t ip) const
vector of local gradients in ip point
const MathVector< dim > & local_ip (size_t ip) const
local integration point of scvf
const MathVector< worldDim > & normal () const
outer normal on bf. Norm is equal to area
size_t num_ip () const
number of integration points on scvf
size_t num_sh () const
number of shape functions
number shape (size_t ip, size_t sh) const
value of shape function i in integration point
const number * shape_vector (size_t ip) const
vector of shape functions in ip point
number volume () const
volume of bf
number weight (size_t ip) const
integration weight
Protected Attributes
size_t nip
MathVector< worldDim > Normal
size_t nsh
std::vector< number > vDetJ
std::vector< MathVector< worldDim > > vGlobalIP
std::vector< MathMatrix< worldDim, dim > > vJtInv
std::vector< MathVector< dim > > vLocalIP
number Vol
std::vector< std::vector< MathVector< worldDim > > > vvGlobalGrad
std::vector< std::vector< MathVector< dim > > > vvLocalGrad
std::vector< std::vector< number > > vvShape
const number * vWeight
Friends
class DimFEGeometry< worldDim, dim >
let outer class access private members
Detailed Description
template<int TWorldDim, int TRefDim = TWorldDim>
class ug::DimFEGeometry< TWorldDim, TRefDim >::BF
boundary face
Constructor & Destructor Documentation
BF()
template<int TWorldDim, int TRefDim = TWorldDim> ug::DimFEGeometry< TWorldDim, TRefDim >::BF::BF () inline
Member Function Documentation
detJ()
template<int TWorldDim, int TRefDim = TWorldDim> number ug::DimFEGeometry< TWorldDim, TRefDim >::BF::detJ (size_t ip) const inline
Determinant of Jacobian in integration point.
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), UG_ASSERT, and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vDetJ.
global_grad()
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<worldDim>& ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_grad (size_t ip, size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_sh(), UG_ASSERT, and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vvGlobalGrad.
global_grad_vector()
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<worldDim>* ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_grad_vector (size_t ip) const inline
vector of global gradients in ip point
global_ip()
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<worldDim>& ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_ip (size_t ip) const inline
global integration point of scvf
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), UG_ASSERT, and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vGlobalIP.
JTInv()
template<int TWorldDim, int TRefDim = TWorldDim> const MathMatrix<worldDim,dim>& ug::DimFEGeometry< TWorldDim, TRefDim >::BF::JTInv (size_t ip) const inline
Transposed Inverse of Jacobian in integration point.
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), UG_ASSERT, and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vJtInv.
local_grad()
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<dim>& ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_grad (size_t ip, size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_sh(), UG_ASSERT, and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vvLocalGrad.
local_grad_vector()
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<dim>* ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_grad_vector (size_t ip) const inline
vector of local gradients in ip point
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), UG_ASSERT, and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vvLocalGrad.
local_ip()
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<dim>& ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_ip (size_t ip) const inline
local integration point of scvf
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), UG_ASSERT, and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vLocalIP.
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
normal()
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<worldDim>& ug::DimFEGeometry< TWorldDim, TRefDim >::BF::normal () const inline
outer normal on bf. Norm is equal to area
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::Normal.
num_ip()
template<int TWorldDim, int TRefDim = TWorldDim> size_t ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip () const inline
number of integration points on scvf
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::nip.
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::detJ(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_grad(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_ip(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::JTInv(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_grad(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_grad_vector(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_ip(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::shape(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::shape_vector(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces(), and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::weight().
num_sh()
template<int TWorldDim, int TRefDim = TWorldDim> size_t ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_sh () const inline
number of shape functions
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::nsh.
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_grad(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_grad(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
shape()
template<int TWorldDim, int TRefDim = TWorldDim> number ug::DimFEGeometry< TWorldDim, TRefDim >::BF::shape (size_t ip, size_t sh) const inline
value of shape function i in integration point
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), UG_ASSERT, and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vvShape.
shape_vector()
template<int TWorldDim, int TRefDim = TWorldDim> const number* ug::DimFEGeometry< TWorldDim, TRefDim >::BF::shape_vector (size_t ip) const inline
vector of shape functions in ip point
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), UG_ASSERT, and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vvShape.
volume()
template<int TWorldDim, int TRefDim = TWorldDim> number ug::DimFEGeometry< TWorldDim, TRefDim >::BF::volume () const inline
volume of bf
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::Vol.
weight()
template<int TWorldDim, int TRefDim = TWorldDim> number ug::DimFEGeometry< TWorldDim, TRefDim >::BF::weight (size_t ip) const inline
integration weight
References ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), UG_ASSERT, ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vDetJ, and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vWeight.
Friends And Related Function Documentation
DimFEGeometry< worldDim, dim >
template<int TWorldDim, int TRefDim = TWorldDim> friend class DimFEGeometry< worldDim, dim > friend
let outer class access private members
Member Data Documentation
nip
template<int TWorldDim, int TRefDim = TWorldDim> size_t ug::DimFEGeometry< TWorldDim, TRefDim >::BF::nip protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
Normal
template<int TWorldDim, int TRefDim = TWorldDim> MathVector<worldDim> ug::DimFEGeometry< TWorldDim, TRefDim >::BF::Normal protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::normal(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
nsh
template<int TWorldDim, int TRefDim = TWorldDim> size_t ug::DimFEGeometry< TWorldDim, TRefDim >::BF::nsh protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_sh(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
vDetJ
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<number> ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vDetJ protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::detJ(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces(), and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::weight().
vGlobalIP
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<MathVector<worldDim> > ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vGlobalIP protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_ip(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
vJtInv
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<MathMatrix<worldDim,dim> > ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vJtInv protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::JTInv(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
vLocalIP
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<MathVector<dim> > ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vLocalIP protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_ip(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
Vol
template<int TWorldDim, int TRefDim = TWorldDim> number ug::DimFEGeometry< TWorldDim, TRefDim >::BF::Vol protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces(), and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::volume().
vvGlobalGrad
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<std::vector<MathVector<worldDim> > > ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vvGlobalGrad protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_grad(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
vvLocalGrad
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<std::vector<MathVector<dim> > > ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vvLocalGrad protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_grad(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_grad_vector(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
vvShape
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<std::vector<number> > ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vvShape protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::shape(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::shape_vector(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
vWeight
template<int TWorldDim, int TRefDim = TWorldDim> const number* ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vWeight protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces(), and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::weight().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fe_geom.h