ug4: ug::DarcyVelocityLinker< dim > Class Template Reference
ug::DarcyVelocityLinker< dim > Class Template Reference
Hard Coded Linker for the Darcy velocity.
#include <darcy_velocity_linker.h>
Public Member Functions
DarcyVelocityLinker ()
template<int refDim>
void eval_and_deriv (MathVector< dim > vDarcyVel[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, bool bDeriv, int s, std::vector< std::vector< MathVector< dim > > > vvvDeriv[], const MathMatrix< refDim, dim > *vJT=NULL) const
void evaluate (MathVector< dim > &value, const MathVector< dim > &globIP, number time, int si) const
template<int refDim>
void evaluate (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
void set_density (number val)
void set_density (SmartPtr< CplUserData< number, dim > > data)
set density import
void set_derivative_mask (int mask)
void set_gravity (SmartPtr< CplUserData< MathVector< dim >, dim > > data)
set gravity import
void set_permeability (number val)
void set_permeability (SmartPtr< CplUserData< MathMatrix< dim, dim >, dim > > data)
set permeability import
void set_pressure_gradient (SmartPtr< CplUserData< MathVector< dim >, dim > > data)
set pressure gradient import
void set_viscosity (number val)
void set_viscosity (SmartPtr< CplUserData< number, dim > > data)
set permeability import
Public Member Functions inherited from ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >
virtual void check_setup () const
returns if data is ok
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
compute values (and derivatives iff compDeriv == true)
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
compute values (and derivatives iff compDeriv == true, but only for the 'current' time point)
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
void evaluate (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
virtual SmartPtr< ICplUserData< dim > > needed_data (size_t i)
return needed data
virtual size_t num_input () const
number of inputs
virtual size_t num_needed_data () const
number of other Data this data depends on
virtual void operator() (MathVector< dim > &value, const MathVector< dim > &globIP, number time, int si) const
returns value for a global position
virtual void operator() (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
returns value for global positions
virtual bool requires_grid_fct () const
returns that a grid function is needed for evaluation
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
updates the function group
virtual void set_input (size_t i, SmartPtr< ICplUserData< dim > > input, SmartPtr< UserDataInfo > info)
sets an input
void set_num_input (size_t num)
sets the number of inputs
virtual bool zero_derivative () const
returns if derivative is zero
bool zero_derivative (size_t i) const
returns if the derivative of the i'th input is zero
Public Member Functions inherited from ug::StdUserData< TImpl, TData, dim, TRet, TBase >
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
Public Member Functions inherited from ug::CplUserData< TData, dim, void >
bool defined (size_t s, size_t ip) const
returns flag, if data is evaluated (for conditional data)
size_t num_ip (size_t s) const
returns the number of integration points
size_t num_series () const
explicitly forward some functions
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
register external callback, invoked when data storage changed
void unregister_storage_callback (DataImport< TData, dim > *obj)
register all callbacks registered by class
TData & value (size_t s, size_t ip)
returns the value at ip
const TData & value (size_t s, size_t ip) const
returns the value at ip
TData * values (size_t s)
returns all values for a series
const TData * values (size_t s) const
returns all values for a series
~CplUserData ()
destructor
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
returns true iff the time point specification is equal to the current one, or not specified
void clear ()
clear all data
virtual bool constant () const
returns if data is constant
int dim_local_ips () const
returns current local ip dimension
ICplUserData ()
default constructor
const MathVector< dim > & ip (size_t s, size_t ip) const
returns global ip
const MathVector< dim > * ips (size_t s) const
returns global ips
template<int ldim>
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
returns local ip
template<int ldim>
const MathVector< ldim > * local_ips (size_t s) const
returns local ips
size_t num_ip (size_t s) const
returns the number of integration points
size_t num_series () const
returns the number of ip series
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
set local positions without the specification of the time point, returns series id
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
set local positions, returns series id
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
set global positions
template<int ldim>
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
sets new local ip positions for a local ip series
void set_subset (int si)
set the subset of evaluation
void set_time_point (const size_t seriesId, const int timePointSpec)
sets a new time point for a local ip series
void set_time_point (size_t timePoint)
sets the current time point
void set_times (const std::vector< number > &vTime)
set evaluation time
int subset () const
returns the subset of evaluation
number time () const
get the current evaluation time
number time (size_t s) const
get the specified evaluation time
size_t time_point ()
returns the current time point
size_t time_point (size_t s) const
returns the time point specification (in particular, the current one, if the own one not specified)
int time_point_specification (size_t s) const
returns the time point specification (note: it may be -1, i.e. not specified)
virtual void update_dof_sizes (const LocalIndices &ind)
resize arrays
virtual ~ICplUserData ()
virtual desctructor
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
Function Group of functions.
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual ~UserDataInfo ()
virtual destructor
Public Member Functions inherited from ug::UserData< TData, dim, void >
int get_dim () const
returns dimension
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, Vertex *vrt) const
returns a value at a vertex
std::string type () const
returns type of data as string (e.g. "Number", "Vector", "Matrix")
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
Protected Attributes
int m_partialDerivMask
SmartPtr< DependentUserData< number, dim > > m_spDDensity
SmartPtr< CplUserData< number, dim > > m_spDensity
SmartPtr< DependentUserData< MathVector< dim >, dim > > m_spDGravity
SmartPtr< DependentUserData< MathMatrix< dim, dim >, dim > > m_spDPermeability
SmartPtr< DependentUserData< MathVector< dim >, dim > > m_spDPressureGrad
SmartPtr< DependentUserData< number, dim > > m_spDViscosity
SmartPtr< CplUserData< MathVector< dim >, dim > > m_spGravity
SmartPtr< CplUserData< MathMatrix< dim, dim >, dim > > m_spPermeability
SmartPtr< CplUserData< MathVector< dim >, dim > > m_spPressureGrad
SmartPtr< CplUserData< number, dim > > m_spViscosity
Protected Attributes inherited from ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >
std::vector< FunctionIndexMapping > m_vMap
Function mapping for each input relative to common FunctionGroup.
std::vector< SmartPtr< ICplUserData< dim > > > m_vspICplUserData
data input
std::vector< SmartPtr< UserDataInfo > > m_vspUserDataInfo
data input casted to IDependend data
std::vector< std::vector< size_t > > m_vvSeriesID
series id the linker uses to get data from input
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
default time point (or -1 if not specified)
int m_locPosDim
dimension of local position (-1 indicates no dim set)
std::vector< const MathVector< 1 > * > m_pvLocIP1d
local ips of dimension 1d-3d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
subset for evaluation
size_t m_timePoint
current time point (used if no explicit specification for series)
std::vector< bool > m_vMayChange
flags if local ips may change
std::vector< size_t > m_vNumIP
number of evaluation points (-1 indicates no ips set)
std::vector< number > m_vTime
time for evaluation
std::vector< int > m_vTimePoint
time points for the series
std::vector< const MathVector< dim > * > m_vvGlobPos
global ips
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Static Protected Attributes
static const size_t _DP_ = 4
import for pressure gradient
static const size_t _G_ = 3
import for gravity
static const size_t _K_ = 0
import for permeability
static const size_t _MU_ = 1
import for viscosity
static const size_t _RHO_ = 2
import for density
Private Types
typedef StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim > base_type
Base class type.
Additional Inherited Members
Public Types inherited from ug::CplUserData< TData, dim, void >
typedef ICplUserData< dim > base_type
type of base class
Public Types inherited from ug::UserData< TData, dim, void >
typedef TData data_type
typedef void return_type
Protected Member Functions inherited from ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >
void eval_deriv (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
void eval_deriv (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
DarcyVelocityLinker< dim > & getImpl ()
access to implementation
const DarcyVelocityLinker< dim > & getImpl () const
const access to implementation
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
forwards the global positions to the data inputs
size_t input_common_fct (size_t i, size_t fct) const
returns the number in the common FctGrp for a fct of an input
size_t input_num_fct (size_t i) const
returns number of functions the input depends on
virtual void local_ip_series_added (const size_t seriesID)
requests series id's from input data
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
forwards the local positions to the data inputs
size_t series_id (size_t i, size_t s) const
returns the series id set for the i'th input
Protected Member Functions inherited from ug::StdUserData< TImpl, TData, dim, TRet, TBase >
TImpl & getImpl ()
access to implementation
const TImpl & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::CplUserData< TData, dim, void >
void call_storage_callback () const
calls are registered external storage callbacks
void check_series (size_t s) const
checks in debug mode the correct index
void check_series_ip (size_t s, size_t ip) const
checks in debug mode the correct index
virtual void local_ip_series_to_be_cleared ()
free the data field memory and set series to zero
virtual void value_storage_changed (const size_t seriesID)
callback, invoked when storage of data has changed for a series
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
checks in debug mode the correct usage of indices
void check_s_ip (size_t s, size_t ip) const
checks in debug mode the correct usage of indices
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
help function to get local ips
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
Detailed Description
template<int dim>
class ug::DarcyVelocityLinker< dim >
Hard Coded Linker for the Darcy velocity.
This linker computes the Darcy velocity \(\mathbf{q} = - \frac{\mathbf{K}}{\mu} (\nabla p - \rho \mathbf{g}) \), where
\(\mathbf{K} \) permeability
\(\mu \) viscosity
\(\rho \) density
\(\mathbf{g} \) gravity
\(\nabla p \) pressure gradient
are input parameters. This linker can be composed as a tree of other linkers, but is computationally cheaper.
Member Typedef Documentation
base_type
template<int dim> typedef StdDataLinker< DarcyVelocityLinker<dim>, MathVector<dim>, dim> ug::DarcyVelocityLinker< dim >::base_type private
Base class type.
Constructor & Destructor Documentation
DarcyVelocityLinker()
template<int dim> ug::DarcyVelocityLinker< dim >::DarcyVelocityLinker () inline
References ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::set_num_input().
Member Function Documentation
eval_and_deriv()
template<int dim> template<int refDim> void ug::DarcyVelocityLinker< dim >::eval_and_deriv (MathVector< dim > vDarcyVel[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, bool bDeriv, int s, std::vector< std::vector< MathVector< dim > > > vvvDeriv[], const MathMatrix< refDim, dim > * vJT = NULL) const inline
References ug::DarcyVelocityLinker< dim >::_DP_, ug::DarcyVelocityLinker< dim >::_G_, ug::DarcyVelocityLinker< dim >::_K_, ug::DarcyVelocityLinker< dim >::_MU_, ug::DarcyVelocityLinker< dim >::_RHO_, ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::input_common_fct(), ug::ICplUserData< dim >::ip(), ug::DarcyVelocityLinker< dim >::m_partialDerivMask, ug::DarcyVelocityLinker< dim >::m_spDDensity, ug::DarcyVelocityLinker< dim >::m_spDensity, ug::DarcyVelocityLinker< dim >::m_spDGravity, ug::DarcyVelocityLinker< dim >::m_spDPermeability, ug::DarcyVelocityLinker< dim >::m_spDPressureGrad, ug::DarcyVelocityLinker< dim >::m_spDViscosity, ug::DarcyVelocityLinker< dim >::m_spGravity, ug::DarcyVelocityLinker< dim >::m_spPermeability, ug::DarcyVelocityLinker< dim >::m_spPressureGrad, ug::DarcyVelocityLinker< dim >::m_spViscosity, ug::MatScale(), ug::MatVecMult(), s, UG_ASSERT, ug::VecScale(), ug::VecScaleAppend(), ug::VecSubtract(), and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::zero_derivative().
evaluate() [1/2]
template<int dim> void ug::DarcyVelocityLinker< dim >::evaluate (MathVector< dim > & value, const MathVector< dim > & globIP, number time, int si) const inline
References ug::MatVecMult(), ug::ICplUserData< dim >::time(), ug::CplUserData< TData, dim, void >::value(), ug::VecScale(), and ug::VecSubtract().
evaluate() [2/2]
template<int dim> template<int refDim> void ug::DarcyVelocityLinker< dim >::evaluate (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< refDim, dim > * vJT = NULL) const inline
References ug::ICplUserData< dim >::ip(), ug::MatVecMult(), ug::ICplUserData< dim >::time(), ug::VecScale(), and ug::VecSubtract().
set_density() [1/2]
template<int dim> void ug::DarcyVelocityLinker< dim >::set_density (number val) inline
References make_sp(), and ug::DarcyVelocityLinker< dim >::set_density().
set_density() [2/2]
template<int dim> void ug::DarcyVelocityLinker< dim >::set_density (SmartPtr< CplUserData< number, dim > > data) inline
set density import
References ug::DarcyVelocityLinker< dim >::_RHO_, ug::DarcyVelocityLinker< dim >::m_spDDensity, ug::DarcyVelocityLinker< dim >::m_spDensity, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::set_input().
Referenced by ug::DarcyVelocityLinker< dim >::set_density().
set_derivative_mask()
template<int dim> void ug::DarcyVelocityLinker< dim >::set_derivative_mask (int mask) inline
References ug::DarcyVelocityLinker< dim >::m_partialDerivMask.
set_gravity()
template<int dim> void ug::DarcyVelocityLinker< dim >::set_gravity (SmartPtr< CplUserData< MathVector< dim >, dim > > data) inline
set gravity import
References ug::DarcyVelocityLinker< dim >::_G_, dim, ug::DarcyVelocityLinker< dim >::m_spDGravity, ug::DarcyVelocityLinker< dim >::m_spGravity, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::set_input().
set_permeability() [1/2]
template<int dim> void ug::DarcyVelocityLinker< dim >::set_permeability (number val) inline
References make_sp(), and ug::DarcyVelocityLinker< dim >::set_permeability().
set_permeability() [2/2]
template<int dim> void ug::DarcyVelocityLinker< dim >::set_permeability (SmartPtr< CplUserData< MathMatrix< dim, dim >, dim > > data) inline
set permeability import
References ug::DarcyVelocityLinker< dim >::_K_, dim, ug::DarcyVelocityLinker< dim >::m_spDPermeability, ug::DarcyVelocityLinker< dim >::m_spPermeability, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::set_input().
Referenced by ug::DarcyVelocityLinker< dim >::set_permeability().
set_pressure_gradient()
template<int dim> void ug::DarcyVelocityLinker< dim >::set_pressure_gradient (SmartPtr< CplUserData< MathVector< dim >, dim > > data) inline
set pressure gradient import
References ug::DarcyVelocityLinker< dim >::_DP_, dim, ug::DarcyVelocityLinker< dim >::m_spDPressureGrad, ug::DarcyVelocityLinker< dim >::m_spPressureGrad, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::set_input().
set_viscosity() [1/2]
template<int dim> void ug::DarcyVelocityLinker< dim >::set_viscosity (number val) inline
References make_sp(), and ug::DarcyVelocityLinker< dim >::set_viscosity().
set_viscosity() [2/2]
template<int dim> void ug::DarcyVelocityLinker< dim >::set_viscosity (SmartPtr< CplUserData< number, dim > > data) inline
set permeability import
References ug::DarcyVelocityLinker< dim >::_MU_, ug::DarcyVelocityLinker< dim >::m_spDViscosity, ug::DarcyVelocityLinker< dim >::m_spViscosity, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::set_input().
Referenced by ug::DarcyVelocityLinker< dim >::set_viscosity().
Member Data Documentation
_DP_
template<int dim> const size_t ug::DarcyVelocityLinker< dim >::_DP_ = 4 static protected
import for pressure gradient
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_pressure_gradient().
_G_
template<int dim> const size_t ug::DarcyVelocityLinker< dim >::_G_ = 3 static protected
import for gravity
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_gravity().
_K_
template<int dim> const size_t ug::DarcyVelocityLinker< dim >::_K_ = 0 static protected
import for permeability
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_permeability().
_MU_
template<int dim> const size_t ug::DarcyVelocityLinker< dim >::_MU_ = 1 static protected
import for viscosity
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_viscosity().
_RHO_
template<int dim> const size_t ug::DarcyVelocityLinker< dim >::_RHO_ = 2 static protected
import for density
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_density().
m_partialDerivMask
template<int dim> int ug::DarcyVelocityLinker< dim >::m_partialDerivMask protected
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_derivative_mask().
m_spDDensity
template<int dim> SmartPtr<DependentUserData<number, dim> > ug::DarcyVelocityLinker< dim >::m_spDDensity protected
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_density().
m_spDensity
template<int dim> SmartPtr<CplUserData<number, dim> > ug::DarcyVelocityLinker< dim >::m_spDensity protected
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_density().
m_spDGravity
template<int dim> SmartPtr<DependentUserData<MathVector<dim>, dim> > ug::DarcyVelocityLinker< dim >::m_spDGravity protected
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_gravity().
m_spDPermeability
template<int dim> SmartPtr<DependentUserData<MathMatrix<dim,dim>, dim> > ug::DarcyVelocityLinker< dim >::m_spDPermeability protected
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_permeability().
m_spDPressureGrad
template<int dim> SmartPtr<DependentUserData<MathVector<dim>, dim> > ug::DarcyVelocityLinker< dim >::m_spDPressureGrad protected
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_pressure_gradient().
m_spDViscosity
template<int dim> SmartPtr<DependentUserData<number, dim> > ug::DarcyVelocityLinker< dim >::m_spDViscosity protected
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_viscosity().
m_spGravity
template<int dim> SmartPtr<CplUserData<MathVector<dim>, dim> > ug::DarcyVelocityLinker< dim >::m_spGravity protected
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_gravity().
m_spPermeability
template<int dim> SmartPtr<CplUserData<MathMatrix<dim,dim>, dim> > ug::DarcyVelocityLinker< dim >::m_spPermeability protected
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_permeability().
m_spPressureGrad
template<int dim> SmartPtr<CplUserData<MathVector<dim>, dim> > ug::DarcyVelocityLinker< dim >::m_spPressureGrad protected
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_pressure_gradient().
m_spViscosity
template<int dim> SmartPtr<CplUserData<number, dim> > ug::DarcyVelocityLinker< dim >::m_spViscosity protected
Referenced by ug::DarcyVelocityLinker< dim >::eval_and_deriv(), and ug::DarcyVelocityLinker< dim >::set_viscosity().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/user_data/linker/darcy_velocity_linker.h