ug4: ug::dirichlet_iterator< TAlgebra > Class Template Reference
ug::dirichlet_iterator< TAlgebra > Class Template Reference
Public Types
typedef TAlgebra::matrix_type matrix_type
Public Member Functions
dirichlet_iterator (matrix_type &mat, unsigned i, unsigned num)
bool operator!= (const dirichlet_iterator &o) const
unsigned operator* () const
void operator++ ()
bool operator== (const dirichlet_iterator &o) const
Protected Attributes
matrix_type & A
unsigned cur
unsigned n
Member Typedef Documentation
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::dirichlet_iterator< TAlgebra >::matrix_type
Constructor & Destructor Documentation
dirichlet_iterator()
template<typename TAlgebra > ug::dirichlet_iterator< TAlgebra >::dirichlet_iterator (matrix_type & mat, unsigned i, unsigned num) inline
References ug::dirichlet_iterator< TAlgebra >::operator++().
Member Function Documentation
operator!=()
template<typename TAlgebra > bool ug::dirichlet_iterator< TAlgebra >::operator!= (const dirichlet_iterator< TAlgebra > & o) const inline
References ug::dirichlet_iterator< TAlgebra >::operator==().
operator*()
template<typename TAlgebra > unsigned ug::dirichlet_iterator< TAlgebra >::operator* () const inline
References ug::dirichlet_iterator< TAlgebra >::cur.
operator++()
template<typename TAlgebra > void ug::dirichlet_iterator< TAlgebra >::operator++ () inline
References ug::dirichlet_iterator< TAlgebra >::A, ug::dirichlet_iterator< TAlgebra >::cur, and ug::dirichlet_iterator< TAlgebra >::n.
Referenced by ug::dirichlet_iterator< TAlgebra >::dirichlet_iterator().
operator==()
template<typename TAlgebra > bool ug::dirichlet_iterator< TAlgebra >::operator== (const dirichlet_iterator< TAlgebra > & o) const inline
References ug::dirichlet_iterator< TAlgebra >::cur.
Referenced by ug::dirichlet_iterator< TAlgebra >::operator!=().
Member Data Documentation
A
template<typename TAlgebra > matrix_type& ug::dirichlet_iterator< TAlgebra >::A protected
Referenced by ug::dirichlet_iterator< TAlgebra >::operator++().
cur
template<typename TAlgebra > unsigned ug::dirichlet_iterator< TAlgebra >::cur protected
Referenced by ug::dirichlet_iterator< TAlgebra >::operator*(), ug::dirichlet_iterator< TAlgebra >::operator++(), and ug::dirichlet_iterator< TAlgebra >::operator==().
n
template<typename TAlgebra > unsigned ug::dirichlet_iterator< TAlgebra >::n protected
Referenced by ug::dirichlet_iterator< TAlgebra >::operator++().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/ordering_strategies/algorithms/iters.cpp