ug4: ug::AutoLinearSolver< TVector > Class Template Reference
ug::AutoLinearSolver< TVector > Class Template Reference
linear solver using abstract preconditioner interface
#include <auto_linear_solver.h>
Public Types
typedef IPreconditionedLinearOperatorInverse< vector_type > base_type
Base type.
typedef TVector vector_type
Vector type.
Public Types inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
typedef ILinearOperatorInverse< TVector, TVector > base_type
Base class.
typedef TVector codomain_function_type
Range space.
typedef TVector domain_function_type
Domain space.
Public Types inherited from ug::ILinearOperatorInverse< X, Y >
typedef Y codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Types inherited from ug::ILinearIterator< X, X >
typedef X codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Types inherited from ug::VectorDebugWritingObject< TVector >
typedef TVector vector_type
type of vector
Public Member Functions
virtual bool apply (vector_type &x, const vector_type &b)
compute new correction c = B*d
virtual bool apply_return_defect (vector_type &x, vector_type &b)
solves the system and returns the last defect
AutoLinearSolver ()
AutoLinearSolver (double desiredDefect, double desiredReduction)
bool compute_correction (vector_type &c, vector_type &d)
virtual bool init (SmartPtr< ILinearOperator< vector_type, vector_type > > J)
initializes the solver for an operator
virtual bool init (SmartPtr< ILinearOperator< vector_type, vector_type > > J, const vector_type &u)
initializes the solver for an operator
bool init_op (SmartPtr< ILinearOperator< vector_type, vector_type > > J)
virtual const char * name () const
returns the name of the solver
void print_information ()
bool reinit ()
void set_reduction_always_accept (double d)
void set_reinit_when_worse_then_average (double d)
virtual bool supports_parallel () const
returns if parallel solving is supported
Public Member Functions inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
virtual std::string config_string () const
returns information about configuration parameters
std::string config_string_preconditioner_convergence_check () const
returns config information of convergence check and preconditioner
IPreconditionedLinearOperatorInverse ()
Empty constructor.
IPreconditionedLinearOperatorInverse (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond)
constructor setting the preconditioner
IPreconditionedLinearOperatorInverse (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond, SmartPtr< IConvergenceCheck< TVector > > spConvCheck)
constructor setting the preconditioner
void set_compute_fresh_defect_when_finished (bool bRecompute)
for debug: computes norm again after whole calculation of apply
void set_preconditioner (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond)
sets the preconditioner
SmartPtr< ILinearIterator< TVector, TVector > > preconditioner ()
ConstSmartPtr< ILinearIterator< TVector, TVector > > preconditioner () const
Public Member Functions inherited from ug::ILinearOperatorInverse< X, Y >
virtual bool apply (Y &u, const X &f)=0
applies inverse operator, i.e. returns u = A^{-1} f
virtual bool apply_return_defect (Y &u, X &f)=0
applies inverse operator, i.e. returns u = A^{-1} f and returns defect d := f - A*u
virtual bool apply_update_defect (Y &u, X &f)
virtual SmartPtr< ILinearIterator< X, Y > > clone ()
clone
SmartPtr< IConvergenceCheck< X > > convergence_check ()
returns the convergence check
ConstSmartPtr< IConvergenceCheck< X > > convergence_check () const
returns the convergence check
number defect () const
returns the current defect
ILinearOperatorInverse ()
constructor setting convergence check to (100, 1e-12, 1e-12, true)
ILinearOperatorInverse (SmartPtr< IConvergenceCheck< X > > spConvCheck)
Default constructor.
virtual bool init (SmartPtr< ILinearOperator< Y, X > > J, const Y &u)
initializes for the inverse for a linearized operator at linearization point u
virtual bool init (SmartPtr< ILinearOperator< Y, X > > L)
initializes for the inverse for a linear operator
SmartPtr< ILinearOperator< Y, X > > linear_operator ()
returns the current Operator this Inverse Operator is initialized for
number reduction () const
returns the current relative reduction
void set_convergence_check (SmartPtr< IConvergenceCheck< X > > spConvCheck)
set the convergence check
virtual int standard_offset () const
returns the standard offset for output
int step () const
returns the current number of steps
virtual ~ILinearOperatorInverse ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< X, X >
virtual bool apply (X &c, const X &d)=0
compute new correction c = B*d
virtual bool apply_update_defect (X &c, X &d)=0
compute new correction c = B*d and update defect d := d - A*c
SmartPtr< IDamping< X, X > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< X, X > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< X, X > > J, const X &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< X, X > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< X, X > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TVector >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
SmartPtr< ILinearIterator< X, X > > preconditioner ()
ConstSmartPtr< ILinearIterator< X, X > > preconditioner () const
void prepare_conv_check ()
prepares the convergence check output
Protected Member Functions inherited from ug::VectorDebugWritingObject< TVector >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Private Attributes
double m_avgReduction
int m_bInited
double m_desiredDefect
double m_desiredReduction
size_t m_initCalled
size_t m_initsDone
double m_lastCallReduction
double m_lastCallTime
double m_lastInitTime
double m_reductionAlwaysAccept
double m_reductionPerTime
double m_savedTime
vector_type m_u
double m_worseThenAverage
SmartPtr< ILinearOperator< vector_type, vector_type > > pJ
Additional Inherited Members
Protected Attributes inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
bool m_bRecompute
flag if fresh defect should be computed when finish for debug purpose
SmartPtr< ILinearIterator< TVector, TVector > > m_spPrecond
Iterator used in the iterative scheme to compute the correction and update the defect.
Protected Attributes inherited from ug::ILinearOperatorInverse< X, Y >
SmartPtr< IConvergenceCheck< X > > m_spConvCheck
smart pointer holding the convergence check
SmartPtr< ILinearOperator< Y, X > > m_spLinearOperator
Operator that is inverted by this Inverse Operator.
Protected Attributes inherited from ug::ILinearIterator< X, X >
SmartPtr< IDamping< X, X > > m_spDamping
the scaling
Protected Attributes inherited from ug::VectorDebugWritingObject< TVector >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Detailed Description
template<typename TVector>
class ug::AutoLinearSolver< TVector >
linear solver using abstract preconditioner interface
This class is a linear iterating scheme, that uses any implementation of the ILinearIterator interface to precondition the iteration.
Template Parameters
TAlgebra algebra type
Member Typedef Documentation
base_type
template<typename TVector > typedef IPreconditionedLinearOperatorInverse<vector_type> ug::AutoLinearSolver< TVector >::base_type
Base type.
vector_type
template<typename TVector > typedef TVector ug::AutoLinearSolver< TVector >::vector_type
Vector type.
Constructor & Destructor Documentation
AutoLinearSolver() [1/2]
template<typename TVector > ug::AutoLinearSolver< TVector >::AutoLinearSolver (double desiredDefect, double desiredReduction) inline
References ug::AutoLinearSolver< TVector >::m_bInited, ug::AutoLinearSolver< TVector >::m_desiredDefect, ug::AutoLinearSolver< TVector >::m_desiredReduction, ug::AutoLinearSolver< TVector >::m_initCalled, ug::AutoLinearSolver< TVector >::m_initsDone, and ug::AutoLinearSolver< TVector >::m_savedTime.
AutoLinearSolver() [2/2]
template<typename TVector > ug::AutoLinearSolver< TVector >::AutoLinearSolver () inline
References ug::AutoLinearSolver< TVector >::m_bInited, ug::AutoLinearSolver< TVector >::m_initCalled, ug::AutoLinearSolver< TVector >::m_initsDone, ug::AutoLinearSolver< TVector >::m_reductionAlwaysAccept, ug::AutoLinearSolver< TVector >::m_savedTime, and ug::AutoLinearSolver< TVector >::m_worseThenAverage.
Member Function Documentation
apply()
template<typename TVector > virtual bool ug::AutoLinearSolver< TVector >::apply (vector_type & x, const vector_type & b) inline virtual
compute new correction c = B*d
This method applies the iterator operator, i.e. c = B*d. The domain function d remains unchanged. Note, that this method can always be implemented by creating a copy of d and calling apply_update_defect with this copy.
Parameters
[in] d defect
[out] c correction
Returns
bool success flag
Reimplemented from ug::IPreconditionedLinearOperatorInverse< TVector >.
References ug::AutoLinearSolver< TVector >::apply_return_defect().
Referenced by ug::AutoLinearSolver< TVector >::compute_correction().
apply_return_defect()
template<typename TVector > virtual bool ug::AutoLinearSolver< TVector >::apply_return_defect (vector_type & x, vector_type & b) inline virtual
solves the system and returns the last defect
References ug::AutoLinearSolver< TVector >::compute_correction(), ug::ILinearOperatorInverse< X, Y >::convergence_check(), ug::ILinearOperatorInverse< X, Y >::defect(), ug::get_clock_s(), ug::ILinearOperatorInverse< X, Y >::linear_operator(), LS_PROFILE_BEGIN, LS_PROFILE_END, ug::AutoLinearSolver< TVector >::m_avgReduction, ug::AutoLinearSolver< TVector >::m_bInited, ug::AutoLinearSolver< TVector >::m_desiredDefect, ug::AutoLinearSolver< TVector >::m_desiredReduction, ug::AutoLinearSolver< TVector >::m_initCalled, ug::AutoLinearSolver< TVector >::m_initsDone, ug::AutoLinearSolver< TVector >::m_lastCallReduction, ug::AutoLinearSolver< TVector >::m_lastCallTime, ug::AutoLinearSolver< TVector >::m_lastInitTime, ug::AutoLinearSolver< TVector >::m_reductionPerTime, ug::AutoLinearSolver< TVector >::m_savedTime, ug::AutoLinearSolver< TVector >::name(), ug::AutoLinearSolver< TVector >::prepare_conv_check(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::ILinearOperatorInverse< X, Y >::reduction(), ug::AutoLinearSolver< TVector >::reinit(), ug::reset_floats(), sprintf(), UG_LOG, UG_THROW, and ug::VectorDebugWritingObject< TVector >::write_debug().
Referenced by ug::AutoLinearSolver< TVector >::apply().
compute_correction()
template<typename TVector > bool ug::AutoLinearSolver< TVector >::compute_correction (vector_type & c, vector_type & d) inline
References ug::AutoLinearSolver< TVector >::apply(), ug::ILinearOperatorInverse< X, Y >::linear_operator(), LS_PROFILE_BEGIN, LS_PROFILE_END, ug::AutoLinearSolver< TVector >::preconditioner(), and UG_LOG.
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect().
init() [1/2]
template<typename TVector > virtual bool ug::AutoLinearSolver< TVector >::init (SmartPtr< ILinearOperator< vector_type, vector_type > > L) inline virtual
initializes the solver for an operator
Reimplemented from ug::IPreconditionedLinearOperatorInverse< TVector >.
References ug::AutoLinearSolver< TVector >::init_op(), and ug::AutoLinearSolver< TVector >::m_u.
init() [2/2]
template<typename TVector > virtual bool ug::AutoLinearSolver< TVector >::init (SmartPtr< ILinearOperator< vector_type, vector_type > > J, const vector_type & u) inline virtual
initializes the solver for an operator
Reimplemented from ug::IPreconditionedLinearOperatorInverse< TVector >.
References ug::AutoLinearSolver< TVector >::init_op(), and ug::AutoLinearSolver< TVector >::m_u.
init_op()
template<typename TVector > bool ug::AutoLinearSolver< TVector >::init_op (SmartPtr< ILinearOperator< vector_type, vector_type > > J) inline
References ug::ILinearOperatorInverse< X, Y >::init(), ug::AutoLinearSolver< TVector >::m_bInited, ug::AutoLinearSolver< TVector >::m_initCalled, ug::AutoLinearSolver< TVector >::pJ, and ug::AutoLinearSolver< TVector >::reinit().
Referenced by ug::AutoLinearSolver< TVector >::init().
name()
template<typename TVector > virtual const char* ug::AutoLinearSolver< TVector >::name () const inline virtual
returns the name of the solver
Implements ug::ILinearOperatorInverse< X, Y >.
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), and ug::AutoLinearSolver< TVector >::prepare_conv_check().
preconditioner() [1/2]
template<typename TVector > SmartPtr<ILinearIterator<X, X> > ug::IPreconditionedLinearOperatorInverse< X >::preconditioner inline protected
returns the preconditioner
Referenced by ug::AutoLinearSolver< TVector >::compute_correction(), ug::AutoLinearSolver< TVector >::prepare_conv_check(), and ug::AutoLinearSolver< TVector >::supports_parallel().
preconditioner() [2/2]
template<typename TVector > ConstSmartPtr<ILinearIterator<X, X> > ug::IPreconditionedLinearOperatorInverse< X >::preconditioner inline protected
prepare_conv_check()
template<typename TVector > void ug::AutoLinearSolver< TVector >::prepare_conv_check () inline protected
prepares the convergence check output
References ug::ILinearOperatorInverse< X, Y >::convergence_check(), ug::AutoLinearSolver< TVector >::name(), ug::AutoLinearSolver< TVector >::preconditioner(), and s.
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect().
print_information()
template<typename TVector > void ug::AutoLinearSolver< TVector >::print_information () inline
References ug::AutoLinearSolver< TVector >::m_avgReduction, ug::AutoLinearSolver< TVector >::m_initCalled, ug::AutoLinearSolver< TVector >::m_initsDone, ug::AutoLinearSolver< TVector >::m_lastInitTime, ug::AutoLinearSolver< TVector >::m_reductionPerTime, ug::AutoLinearSolver< TVector >::m_savedTime, ug::reset_floats(), and UG_LOG.
reinit()
template<typename TVector > bool ug::AutoLinearSolver< TVector >::reinit () inline
References ug::get_clock_s(), ug::IPreconditionedLinearOperatorInverse< X >::init(), ug::AutoLinearSolver< TVector >::m_bInited, ug::AutoLinearSolver< TVector >::m_initsDone, ug::AutoLinearSolver< TVector >::m_lastInitTime, ug::AutoLinearSolver< TVector >::m_u, ug::AutoLinearSolver< TVector >::pJ, and SmartPtr< T, FreePolicy >::valid().
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), and ug::AutoLinearSolver< TVector >::init_op().
set_reduction_always_accept()
template<typename TVector > void ug::AutoLinearSolver< TVector >::set_reduction_always_accept (double d) inline
References ug::AutoLinearSolver< TVector >::m_reductionAlwaysAccept.
set_reinit_when_worse_then_average()
template<typename TVector > void ug::AutoLinearSolver< TVector >::set_reinit_when_worse_then_average (double d) inline
References ug::AutoLinearSolver< TVector >::m_worseThenAverage.
supports_parallel()
template<typename TVector > virtual bool ug::AutoLinearSolver< TVector >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearOperatorInverse< X, Y >.
References ug::AutoLinearSolver< TVector >::preconditioner().
Member Data Documentation
m_avgReduction
template<typename TVector > double ug::AutoLinearSolver< TVector >::m_avgReduction private
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), and ug::AutoLinearSolver< TVector >::print_information().
m_bInited
template<typename TVector > int ug::AutoLinearSolver< TVector >::m_bInited private
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), ug::AutoLinearSolver< TVector >::AutoLinearSolver(), ug::AutoLinearSolver< TVector >::init_op(), and ug::AutoLinearSolver< TVector >::reinit().
m_desiredDefect
template<typename TVector > double ug::AutoLinearSolver< TVector >::m_desiredDefect private
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), and ug::AutoLinearSolver< TVector >::AutoLinearSolver().
m_desiredReduction
template<typename TVector > double ug::AutoLinearSolver< TVector >::m_desiredReduction private
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), and ug::AutoLinearSolver< TVector >::AutoLinearSolver().
m_initCalled
template<typename TVector > size_t ug::AutoLinearSolver< TVector >::m_initCalled private
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), ug::AutoLinearSolver< TVector >::AutoLinearSolver(), ug::AutoLinearSolver< TVector >::init_op(), and ug::AutoLinearSolver< TVector >::print_information().
m_initsDone
template<typename TVector > size_t ug::AutoLinearSolver< TVector >::m_initsDone private
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), ug::AutoLinearSolver< TVector >::AutoLinearSolver(), ug::AutoLinearSolver< TVector >::print_information(), and ug::AutoLinearSolver< TVector >::reinit().
m_lastCallReduction
template<typename TVector > double ug::AutoLinearSolver< TVector >::m_lastCallReduction private
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect().
m_lastCallTime
template<typename TVector > double ug::AutoLinearSolver< TVector >::m_lastCallTime private
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect().
m_lastInitTime
template<typename TVector > double ug::AutoLinearSolver< TVector >::m_lastInitTime private
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), ug::AutoLinearSolver< TVector >::print_information(), and ug::AutoLinearSolver< TVector >::reinit().
m_reductionAlwaysAccept
template<typename TVector > double ug::AutoLinearSolver< TVector >::m_reductionAlwaysAccept private
Referenced by ug::AutoLinearSolver< TVector >::AutoLinearSolver(), and ug::AutoLinearSolver< TVector >::set_reduction_always_accept().
m_reductionPerTime
template<typename TVector > double ug::AutoLinearSolver< TVector >::m_reductionPerTime private
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), and ug::AutoLinearSolver< TVector >::print_information().
m_savedTime
template<typename TVector > double ug::AutoLinearSolver< TVector >::m_savedTime private
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), ug::AutoLinearSolver< TVector >::AutoLinearSolver(), and ug::AutoLinearSolver< TVector >::print_information().
m_u
template<typename TVector > vector_type ug::AutoLinearSolver< TVector >::m_u private
Referenced by ug::AutoLinearSolver< TVector >::init(), and ug::AutoLinearSolver< TVector >::reinit().
m_worseThenAverage
template<typename TVector > double ug::AutoLinearSolver< TVector >::m_worseThenAverage private
Referenced by ug::AutoLinearSolver< TVector >::AutoLinearSolver(), and ug::AutoLinearSolver< TVector >::set_reinit_when_worse_then_average().
pJ
template<typename TVector > SmartPtr<ILinearOperator<vector_type,vector_type> > ug::AutoLinearSolver< TVector >::pJ private
Referenced by ug::AutoLinearSolver< TVector >::init_op(), and ug::AutoLinearSolver< TVector >::reinit().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/linear_solver/auto_linear_solver.h