ug4: ug::LagrangeLSFS< ReferenceTriangle, TOrder > Class Template Reference
ug::LagrangeLSFS< ReferenceTriangle, TOrder > Class Template Reference
#include <lagrange.h>
Public Types
typedef base_type::grad_type grad_type
Gradient type.
typedef base_type::shape_type shape_type
Shape type.
Public Types inherited from ug::BaseLSFS< LagrangeLSFS< ReferenceTriangle, TOrder >, 2 >
typedef MathVector< TDim > grad_type
Gradient type.
typedef LagrangeLSFS< ReferenceTriangle, TOrder > ImplType
type of implementation
typedef number shape_type
Shape type.
Public Member Functions
void check_index (size_t i) const
checks in debug mode that index is valid
void check_multi_index (const MathVector< dim, int > &ind) const
checks in debug mode that multi-index is valid
bool continuous () const
returns if space constructs continuous functions
void grad (grad_type &g, const MathVector< dim, int > ind, const MathVector< dim > &x) const
evaluates the gradient
void grad (grad_type &g, const size_t i, const MathVector< dim > &x) const
evaluates the shape function
size_t index (const MathVector< dim, int > &ind) const
return the index for a multi_index
LagrangeLSFS ()
Constructor.
size_t mapped_index (const MathVector< dim, int > &ind) const
return the index for a multi_index
MathVector< dim, int > mapped_multi_index (size_t i) const
return the multi_index for an index
const MathVector< dim, int > & multi_index (size_t i) const
return Multi index for index i
size_t num_sh () const
bool position (size_t i, MathVector< dim > &pos) const
local position of DoF i
number shape (const MathVector< dim, int > &ind, const MathVector< dim > &x) const
shape value for a Multi Index
number shape (const size_t i, const MathVector< dim > &x) const
evaluates the shape function
Public Member Functions inherited from ug::LagrangeLDS< ReferenceTriangle >
bool exact_position_available () const
returns if the local dof position are exact
LagrangeLDS (size_t order=1)
constructor
const LocalDoF & local_dof (size_t dof) const
returns the dof storage
size_t num_dof () const
returns the total number of DoFs on the finite element
size_t num_dof (ReferenceObjectID roid) const
returns the number of DoFs on a sub-geometric object type
ReferenceObjectID roid () const
returns the type of reference element
void set_order (size_t order)
sets the order
Public Member Functions inherited from ug::LocalDoFSet
int dim () const
returns the reference dimension
size_t num_dof (int d, size_t id) const
returns the number of DoFs on a sub-geometric object of dim and id
bool operator!= (const LocalDoFSet &v) const
inequality check
bool operator== (const LocalDoFSet &v) const
equality check
virtual ~LocalDoFSet ()
virtual destructor
size_t num_dof () const
Public Member Functions inherited from ug::BaseLSFS< LagrangeLSFS< ReferenceTriangle, TOrder >, 2 >
void grad (grad_type &g, size_t i, const MathVector< dim > &x) const
evaluates the gradient of the shape function
void grads (grad_type *vGrad, const MathVector< dim > &x) const
returns all gradients evaluated at a point
void grads (std::vector< grad_type > &vGrad, const MathVector< dim > &x) const
returns all gradients evaluated at a point
void grads (std::vector< std::vector< grad_type > > &vvGrad, const std::vector< MathVector< dim > > &vLocPos) const
returns all gradients evaluated at a point
void shape (shape_type &sh, size_t i, const MathVector< dim > &x) const
evaluates the shape function
shape_type shape (size_t i, const MathVector< dim > &x) const
evaluates the shape function
void shapes (shape_type *vShape, const MathVector< dim > &x) const
returns all shape functions evaluated at a point
void shapes (std::vector< shape_type > &vShape, const MathVector< dim > &x) const
returns all shape functions evaluated at a point
void shapes (std::vector< std::vector< shape_type > > &vvShape, const std::vector< MathVector< dim > > &vLocPos) const
returns all shape functions evaluated at a point
Static Public Attributes
static const int dim = ReferenceTriangle::dim
Dimension, where shape functions are defined.
static const size_t nsh = BinomialCoefficient<dim + p, p>::value
Number of shape functions.
static const size_t order = TOrder
Order of Shape functions.
Static Public Attributes inherited from ug::BaseLSFS< LagrangeLSFS< ReferenceTriangle, TOrder >, 2 >
static const int dim
dimension of reference element
Private Types
typedef BaseLSFS< LagrangeLSFS< ReferenceTriangle, TOrder >, 2 > base_type
base class
Private Attributes
Polynomial1D m_vDPolynom [p+1]
MathVector< dim, int > m_vMultiIndex [nsh]
Polynomial1D m_vPolynom [p+1]
Static Private Attributes
static const size_t p = TOrder
abbreviation for order
Additional Inherited Members
Protected Member Functions inherited from ug::BaseLSFS< LagrangeLSFS< ReferenceTriangle, TOrder >, 2 >
ImplType & getImpl ()
access to implementation
const ImplType & getImpl () const
const access to implementation
Protected Attributes inherited from ug::LagrangeLDS< ReferenceTriangle >
std::vector< LocalDoF > m_vLocalDoF
association to geom obj
size_t p
order
Member Typedef Documentation
base_type
template<int TOrder> typedef BaseLSFS<LagrangeLSFS<ReferenceTriangle, TOrder>, 2> ug::LagrangeLSFS< ReferenceTriangle, TOrder >::base_type private
base class
grad_type
template<int TOrder> typedef base_type::grad_type ug::LagrangeLSFS< ReferenceTriangle, TOrder >::grad_type
Gradient type.
shape_type
template<int TOrder> typedef base_type::shape_type ug::LagrangeLSFS< ReferenceTriangle, TOrder >::shape_type
Shape type.
Constructor & Destructor Documentation
LagrangeLSFS()
template<int TOrder> ug::LagrangeLSFS< ReferenceTriangle, TOrder >::LagrangeLSFS
Constructor.
References ug::Provider< TClass >::get(), p, and ug::SetLagrangeMultiIndex().
Member Function Documentation
check_index()
template<int TOrder> void ug::LagrangeLSFS< ReferenceTriangle, TOrder >::check_index (size_t i) const inline
checks in debug mode that index is valid
References UG_ASSERT.
check_multi_index()
template<int TOrder> void ug::LagrangeLSFS< ReferenceTriangle, TOrder >::check_multi_index (const MathVector< dim, int > & ind) const inline
checks in debug mode that multi-index is valid
References p, and UG_ASSERT.
continuous()
template<int TOrder> bool ug::LagrangeLSFS< ReferenceTriangle, TOrder >::continuous () const inline
returns if space constructs continuous functions
grad() [1/2]
template<int TOrder> void ug::LagrangeLSFS< ReferenceTriangle, TOrder >::grad (grad_type & g, const MathVector< dim, int > ind, const MathVector< dim > & x) const inline
evaluates the gradient
References dim, p, ug::SMALL, and UG_ASSERT.
grad() [2/2]
template<int TOrder> void ug::LagrangeLSFS< ReferenceTriangle, TOrder >::grad (grad_type & g, const size_t i, const MathVector< dim > & x) const inline
evaluates the shape function
This function returns the value of Shape Function i at an element-local evaluation point.
Parameters
[in] i number of DoF
[in] x Position on reference element (evaluation point)
Returns
shape function value at point
index()
template<int TOrder> size_t ug::LagrangeLSFS< ReferenceTriangle, TOrder >::index (const MathVector< dim, int > & ind) const inline
return the index for a multi_index
References UG_THROW.
mapped_index()
template<int TOrder> size_t ug::LagrangeLSFS< ReferenceTriangle, TOrder >::mapped_index (const MathVector< dim, int > & ind) const inline
return the index for a multi_index
References p.
mapped_multi_index()
template<int TOrder> MathVector<dim,int> ug::LagrangeLSFS< ReferenceTriangle, TOrder >::mapped_multi_index (size_t i) const inline
return the multi_index for an index
References p, and UG_ASSERT.
multi_index()
template<int TOrder> const MathVector<dim,int>& ug::LagrangeLSFS< ReferenceTriangle, TOrder >::multi_index (size_t i) const inline
return Multi index for index i
num_sh()
template<int TOrder> size_t ug::LagrangeLSFS< ReferenceTriangle, TOrder >::num_sh () const inline virtual
returns the total number of dofs on the finite element
Reimplemented from ug::LocalDoFSet.
position()
template<int TOrder> bool ug::LagrangeLSFS< ReferenceTriangle, TOrder >::position (size_t i, MathVector< dim > & pos) const inline
local position of DoF i
This function returns the local position of a DoF if possible.
Parameters
[in] i number of DoF
[out] pos Position of DoF
Return values
true if position exists
false if no meaningful position available
References dim, p, and ug::TruncatedEquidistantLagrange1D::position().
shape() [1/2]
template<int TOrder> number ug::LagrangeLSFS< ReferenceTriangle, TOrder >::shape (const MathVector< dim, int > & ind, const MathVector< dim > & x) const inline
shape value for a Multi Index
References p.
shape() [2/2]
template<int TOrder> number ug::LagrangeLSFS< ReferenceTriangle, TOrder >::shape (const size_t i, const MathVector< dim > & x) const inline
evaluates the shape function
This function returns the value of Shape Function i at an element-local evaluation point.
Parameters
[in] i number of DoF
[in] x Position on reference element (evaluation point)
Returns
shape function value at point
Member Data Documentation
dim
template<int TOrder> const int ug::LagrangeLSFS< ReferenceTriangle, TOrder >::dim = ReferenceTriangle::dim static
Dimension, where shape functions are defined.
m_vDPolynom
template<int TOrder> Polynomial1D ug::LagrangeLSFS< ReferenceTriangle, TOrder >::m_vDPolynom[p+1] private
m_vMultiIndex
template<int TOrder> MathVector<dim,int> ug::LagrangeLSFS< ReferenceTriangle, TOrder >::m_vMultiIndex[nsh] private
m_vPolynom
template<int TOrder> Polynomial1D ug::LagrangeLSFS< ReferenceTriangle, TOrder >::m_vPolynom[p+1] private
nsh
template<int TOrder> const size_t ug::LagrangeLSFS< ReferenceTriangle, TOrder >::nsh = BinomialCoefficient<dim + p, p>::value static
Number of shape functions.
order
template<int TOrder> const size_t ug::LagrangeLSFS< ReferenceTriangle, TOrder >::order = TOrder static
Order of Shape functions.
p
template<int TOrder> const size_t ug::LagrangeLSFS< ReferenceTriangle, TOrder >::p = TOrder static private
abbreviation for order
The documentation for this class was generated from the following files:
ugbase/lib_disc/local_finite_element/lagrange/lagrange.h
ugbase/lib_disc/local_finite_element/lagrange/lagrange.cpp