ug4: ug::DoFDistribution Class Reference
ug::DoFDistribution Class Reference
#include <dof_distribution.h>
Classes
struct dim_traits
struct traits
Public Member Functions
template<typename TElem , typename TBaseElem >
void collect_associated (std::vector< TBaseElem * > &vAssElem, TElem *elem, bool clearContainer=true) const
returns the adjacent elements
void copy_values (const std::vector< std::pair< size_t, size_t > > &vIndexMap, bool bDisjunct)
swaps values in managed functions, if indices swapped
SurfaceView::SurfaceConstants defaultValidSurfState () const
returns the default valid surface state
DoFCount dof_count () const
DoFDistribution (SmartPtr< MultiGrid > spMG, SmartPtr< MGSubsetHandler > spMGSH, ConstSmartPtr< DoFDistributionInfo > spDDInfo, SmartPtr< SurfaceView > spSurfView, const GridLevel &level, bool bGrouped, SmartPtr< DoFIndexStorage > spDoFIndexStorage=SPNULL)
constructor
void get_connections (std::vector< std::vector< size_t > > &vvConnection) const
returns the connections
const GridLevel & grid_level () const
returns grid level
bool grouped () const
returns if dofs are grouped
size_t inner_algebra_indices_for_fct (GridObject *elem, std::vector< size_t > &ind, bool bClear, int fct) const
template<class TGeomObj >
bool is_contained (TGeomObj *obj) const
returns if the grid object is part of the dof distribution
void manage_grid_function (IGridFunction &gridFct)
registers a grid function for adaptation management
size_t num_indices () const
return the number of dofs distributed
size_t num_indices (int si) const
return the number of dofs distributed on subset si
void permute_indices (const std::vector< size_t > &vIndNew)
renames the indices
void permute_values (const std::vector< size_t > &vIndNew)
permutes values in managed functions, if indices permuted
void reinit ()
initializes the indices
void resize_values (size_t newSize)
changes values in managed functions, number of indices changed
ConstSmartPtr< SurfaceView > surface_view () const
returns the surface view
void unmanage_grid_function (IGridFunction &gridFct)
unregisters a grid function for adaptation management
~DoFDistribution ()
destructor
SmartPtr< MultiGrid > multi_grid ()
ConstSmartPtr< MultiGrid > multi_grid () const
template<typename TElem >
traits< TElem >::iterator begin ()
template<typename TElem >
traits< TElem >::iterator begin (SurfaceView::SurfaceConstants validStates)
template<typename TElem >
traits< TElem >::iterator end ()
template<typename TElem >
traits< TElem >::iterator end (SurfaceView::SurfaceConstants validStates)
template<typename TElem >
traits< TElem >::const_iterator begin () const
template<typename TElem >
traits< TElem >::const_iterator begin (SurfaceView::SurfaceConstants validStates) const
template<typename TElem >
traits< TElem >::const_iterator end () const
template<typename TElem >
traits< TElem >::const_iterator end (SurfaceView::SurfaceConstants validStates) const
template<typename TElem >
traits< TElem >::iterator begin (int si)
template<typename TElem >
traits< TElem >::iterator begin (int si, SurfaceView::SurfaceConstants validStates)
template<typename TElem >
traits< TElem >::iterator end (int si)
template<typename TElem >
traits< TElem >::iterator end (int si, SurfaceView::SurfaceConstants validStates)
template<typename TElem >
traits< TElem >::const_iterator begin (int si) const
template<typename TElem >
traits< TElem >::const_iterator begin (int si, SurfaceView::SurfaceConstants validStates) const
template<typename TElem >
traits< TElem >::const_iterator end (int si) const
template<typename TElem >
traits< TElem >::const_iterator end (int si, SurfaceView::SurfaceConstants validStates) const
void indices (GridObject *elem, LocalIndices &ind, bool bHang=false) const
extracts all indices of the element (sorted)
void indices (Vertex *elem, LocalIndices &ind, bool bHang=false) const
extracts all indices of the element (sorted)
void indices (Edge *elem, LocalIndices &ind, bool bHang=false) const
extracts all indices of the element (sorted)
void indices (Face *elem, LocalIndices &ind, bool bHang=false) const
extracts all indices of the element (sorted)
void indices (Volume *elem, LocalIndices &ind, bool bHang=false) const
extracts all indices of the element (sorted)
size_t dof_indices (GridObject *elem, size_t fct, std::vector< DoFIndex > &ind, bool bHang=false, bool bClear=true) const
extracts all multiindices for a function (sorted)
size_t dof_indices (Vertex *elem, size_t fct, std::vector< DoFIndex > &ind, bool bHang=false, bool bClear=true) const
extracts all multiindices for a function (sorted)
size_t dof_indices (Edge *elem, size_t fct, std::vector< DoFIndex > &ind, bool bHang=false, bool bClear=true) const
extracts all multiindices for a function (sorted)
size_t dof_indices (Face *elem, size_t fct, std::vector< DoFIndex > &ind, bool bHang=false, bool bClear=true) const
extracts all multiindices for a function (sorted)
size_t dof_indices (Volume *elem, size_t fct, std::vector< DoFIndex > &ind, bool bHang=false, bool bClear=true) const
extracts all multiindices for a function (sorted)
size_t inner_dof_indices (GridObject *elem, size_t fct, std::vector< DoFIndex > &ind, bool bClear=true) const
extracts all multiindices of a function in the inner (sorted)
size_t inner_dof_indices (Vertex *elem, size_t fct, std::vector< DoFIndex > &ind, bool bClear=true) const
extracts all multiindices of a function in the inner (sorted)
size_t inner_dof_indices (Edge *elem, size_t fct, std::vector< DoFIndex > &ind, bool bClear=true) const
extracts all multiindices of a function in the inner (sorted)
size_t inner_dof_indices (Face *elem, size_t fct, std::vector< DoFIndex > &ind, bool bClear=true) const
extracts all multiindices of a function in the inner (sorted)
size_t inner_dof_indices (Volume *elem, size_t fct, std::vector< DoFIndex > &ind, bool bClear=true) const
extracts all multiindices of a function in the inner (sorted)
size_t algebra_indices (GridObject *elem, std::vector< size_t > &ind, bool bClear=true) const
extracts all algebra indices of an element (not sorted)
size_t algebra_indices (Vertex *elem, std::vector< size_t > &ind, bool bClear=true) const
extracts all algebra indices of an element (not sorted)
size_t algebra_indices (Edge *elem, std::vector< size_t > &ind, bool bClear=true) const
extracts all algebra indices of an element (not sorted)
size_t algebra_indices (Face *elem, std::vector< size_t > &ind, bool bClear=true) const
extracts all algebra indices of an element (not sorted)
size_t algebra_indices (Volume *elem, std::vector< size_t > &ind, bool bClear=true) const
extracts all algebra indices of an element (not sorted)
size_t inner_algebra_indices (GridObject *elem, std::vector< size_t > &ind, bool bClear=true) const
extracts all algebra indices in the inner of the element (not sorted)
size_t inner_algebra_indices (Vertex *elem, std::vector< size_t > &ind, bool bClear=true) const
extracts all algebra indices in the inner of the element (not sorted)
size_t inner_algebra_indices (Edge *elem, std::vector< size_t > &ind, bool bClear=true) const
extracts all algebra indices in the inner of the element (not sorted)
size_t inner_algebra_indices (Face *elem, std::vector< size_t > &ind, bool bClear=true) const
extracts all algebra indices in the inner of the element (not sorted)
size_t inner_algebra_indices (Volume *elem, std::vector< size_t > &ind, bool bClear=true) const
extracts all algebra indices in the inner of the element (not sorted)
ConstSmartPtr< AlgebraLayouts > layouts () const
SmartPtr< AlgebraLayouts > layouts ()
Public Member Functions inherited from ug::DoFDistributionInfoProvider
int dim (size_t fct) const
returns the dimension in which solution lives
int dim_subset (int si) const
returns dimension of subset
ConstSmartPtr< DoFDistributionInfo > dof_distribution_info () const
returns underlying info
DoFDistributionInfoProvider (ConstSmartPtr< DoFDistributionInfo > spDDI)
constructor
DoFDistributionInfoProvider ()
constructor
FunctionGroup fct_grp_by_name (const char *names) const
returns a function group to a string of functions
size_t fct_id_by_name (const char *name) const
returns fct id by name
ConstSmartPtr< FunctionPattern > function_pattern () const
returns the function pattern
bool is_def_everywhere (size_t fct) const
returns true if the discrete function nr_fct is defined everywhere
bool is_def_in_subset (size_t fct, int si) const
returns if a function is defined on a subset
size_t max_dofs (const int dim) const
returns the maximum number of dofs on grid objects in a dimension
size_t max_dofs (const GridBaseObjectId gbo) const
returns the maximum number of dofs on a grid base object type
size_t max_dofs (const ReferenceObjectID roid) const
returns the maximum number of dofs on reference object type
size_t max_dofs (const int dim, const int si) const
returns the maximum number of dofs in a dimension on a subset
size_t max_dofs (const GridBaseObjectId gbo, const int si) const
returns the maximum number of dofs on a grid base object on a subset
size_t max_fct_dofs (const size_t fct, int dim) const
returns the maximal number of dofs on a dimension for a function component
size_t max_fct_dofs (const size_t fct, const GridBaseObjectId gbo) const
returns the maximal number of dofs on a base object type for a function component
size_t max_fct_dofs (const size_t fct, const ReferenceObjectID roid) const
returns the number of dofs on a reference object for a function component
size_t max_fct_dofs (const size_t fct, const int dim, const int si) const
returns the maximum number of dofs in a dimension on a subset for a function component
size_t max_fct_dofs (const size_t fct, const GridBaseObjectId gbo, const int si) const
returns the maximum number of dofs on a grid base object on a subset for a function component
std::string name (size_t fct) const
returns the name of the discrete function nr_fct
std::vector< std::string > names () const
returns the names of the discrete functions
size_t num_dofs (const ReferenceObjectID roid, const int si) const
returns the number of dofs on a Reference Object on a subset
size_t num_fct () const
number of discrete functions on subset si
size_t num_fct (int si) const
number of discrete functions on subset si
size_t num_fct_dofs (const size_t fct, const ReferenceObjectID roid, const int si) const
returns the number of dofs on a Reference Object on a subset for a function component
int num_subsets () const
returns number of subsets
size_t offset (const ReferenceObjectID roid, const int si, const size_t fct) const
returns the offset for reference element, subset and function
void print_local_dof_statistic () const
prints statistic on local dof distribution
void print_local_dof_statistic (int verboseLev) const
prints informations
void set_dof_distribution_info (ConstSmartPtr< DoFDistributionInfo > spDDI)
sets the dd info
SubsetGroup subset_grp_by_name (const char *names) const
returns subset group by name
ConstSmartPtr< ISubsetHandler > subset_handler () const
returns the subset handler
int subset_id_by_name (const char *name) const
returns the subset id
std::string subset_name (int si) const
returns subset name
const LFEID & local_finite_element_id (size_t fct) const
const LFEID & lfeid (size_t fct) const
Protected Member Functions
template<typename TBaseElem >
size_t _algebra_indices (TBaseElem *elem, std::vector< size_t > &ind, bool bClear=true) const
template<typename TBaseElem >
size_t _dof_indices (TBaseElem *elem, size_t fct, std::vector< DoFIndex > &ind, bool bHang=false, bool bClear=true) const
template<typename TBaseElem >
void _indices (TBaseElem *elem, LocalIndices &ind, bool bHang=false) const
template<typename TBaseElem >
size_t _inner_algebra_indices (TBaseElem *elem, std::vector< size_t > &ind, bool bClear=true) const
template<typename TBaseElem >
size_t _inner_dof_indices (TBaseElem *elem, size_t fct, std::vector< DoFIndex > &ind, bool bClear=true) const
template<typename TBaseObject >
void add (TBaseObject *obj, const ReferenceObjectID roid, const int si)
adds indices to a geometric object
template<typename TBaseElem >
void add_indices_from_layouts (IndexLayout &indexLayout, int keyType)
template<typename TBaseElem >
void changable_indices (std::vector< size_t > &vIndex, const std::vector< TBaseElem * > &vElem) const
returns indices, that can be changed on the element
void check_subsets ()
checks that subset assignment is ok
template<typename TBaseElem , typename TConstraining , typename TConstrained , typename TSubElem >
void constrained_edge_dof_indices (TBaseElem *elem, size_t fct, std::vector< DoFIndex > &ind, const typename Grid::traits< TSubElem >::secure_container &vSubElem) const
multi indices on constrained edges
template<typename TBaseElem , typename TConstraining , typename TConstrained , typename TSubElem >
void constrained_edge_indices (TBaseElem *elem, LocalIndices &ind, const typename Grid::traits< TSubElem >::secure_container &vSubElem) const
template<typename TBaseElem , typename TConstraining , typename TConstrained , typename TSubElem >
void constrained_face_dof_indices (TBaseElem *elem, size_t fct, std::vector< DoFIndex > &ind, const typename Grid::traits< TSubElem >::secure_container &vSubElem) const
multi indices on constrained faces
template<typename TBaseElem , typename TConstraining , typename TConstrained , typename TSubElem >
void constrained_face_indices (TBaseElem *elem, LocalIndices &ind, const typename Grid::traits< TSubElem >::secure_container &vSubElem) const
template<typename TConstraining , typename TConstrained , typename TBaseElem >
void constrained_vertex_dof_indices (size_t fct, std::vector< DoFIndex > &ind, const typename Grid::traits< TBaseElem >::secure_container &vSubElem) const
multi indices on constrained vertices
template<typename TConstraining , typename TConstrained , typename TBaseElem >
void constrained_vertex_indices (LocalIndices &ind, const typename Grid::traits< TBaseElem >::secure_container &vSubElem) const
extract dofs on constrained objects
template<typename TBaseElem , typename TSubBaseElem >
void dof_indices (TBaseElem *elem, const ReferenceObjectID roid, size_t fct, std::vector< DoFIndex > &ind, const typename Grid::traits< TSubBaseElem >::secure_container &vElem) const
extracts the indices of a subelement of an element
template<typename TBaseElem >
size_t extract_inner_algebra_indices (TBaseElem *elem, std::vector< size_t > &ind) const
adds all algebra indices of an geom object to the LocalIndices
template<typename TBaseElem >
void extract_inner_algebra_indices (const typename Grid::traits< TBaseElem >::secure_container &vElem, std::vector< size_t > &ind) const
adds all algebra indices of a set of geometric objects
template<typename TBaseElem >
void get_connections (std::vector< std::vector< size_t > > &vvConnection) const
template<typename TBaseElem , typename TSubBaseElem >
void indices (TBaseElem *elem, const ReferenceObjectID roid, LocalIndices &ind, const typename Grid::traits< TSubBaseElem >::secure_container &vElem) const
extracts the indices of the subelement of an element
template<typename TBaseElem >
void indices_on_vertex (TBaseElem *elem, const ReferenceObjectID roid, LocalIndices &ind, const Grid::SecureVertexContainer &vElem) const
extracts the indices of the vertices
template<typename TBaseElem >
void permute_indices (const std::vector< size_t > &vNewInd)
template<typename TBaseElem >
void reinit ()
initializes the indices
void reinit_index_layout (IndexLayout &layout, int keyType)
void reinit_layouts_and_communicator ()
template<typename TBaseElem , typename TConstraining , typename TConstrained >
void sort_constrained_edges (std::vector< size_t > &sortedInd, TBaseElem *elem, TConstraining *constrainingObj, size_t objIndex) const
template<typename TBaseElem , typename TConstraining , typename TConstrained >
void sort_constrained_faces (std::vector< size_t > &sortedInd, TBaseElem *elem, TConstraining *constrainingObj, size_t objIndex) const
template<typename TBaseElem >
void sum_dof_count (DoFCount &cnt) const
template<typename TElem >
size_t & obj_index (TElem *obj)
template<typename TElem >
const size_t & obj_index (TElem *obj) const
Protected Attributes
bool m_bGrouped
grouping
GridLevel m_gridLevel
Grid level.
size_t m_numIndex
number of distributed indices on whole domain
MultiGrid * m_pMG
SmartPtr< DoFIndexStorage > m_spDoFIndexStorage
DoF-Index Memory Storage.
SmartPtr< MultiGrid > m_spMG
Multi Grid.
SmartPtr< MGSubsetHandler > m_spMGSH
Subset Handler.
SmartPtr< SurfaceView > m_spSurfView
MultiGrid Subset Handler.
std::vector< size_t > m_vNumIndexOnSubset
number of distributed indices on each subset
std::vector< IGridFunction * > m_vpGridFunction
managed grid functions
SmartPtr< AlgebraLayouts > spAlgebraLayouts
algebra layouts
Protected Attributes inherited from ug::DoFDistributionInfoProvider
ConstSmartPtr< DoFDistributionInfo > m_spDDI
Function Pattern.
Constructor & Destructor Documentation
ug::DoFDistribution::DoFDistribution (SmartPtr< MultiGrid > spMG, SmartPtr< MGSubsetHandler > spMGSH, ConstSmartPtr< DoFDistributionInfo > spDDInfo, SmartPtr< SurfaceView > spSurfView, const GridLevel & level, bool bGrouped, SmartPtr< DoFIndexStorage > spDoFIndexStorage = SPNULL)
constructor
References check_subsets(), m_spDoFIndexStorage, m_vNumIndexOnSubset, ug::DoFDistributionInfoProvider::num_subsets(), reinit(), spAlgebraLayouts, and ~DoFDistribution().
ug::DoFDistribution::~DoFDistribution ()
destructor
Referenced by DoFDistribution().
Member Function Documentation
template<typename TBaseElem > size_t ug::DoFDistribution::_algebra_indices (TBaseElem * elem, std::vector< size_t > & ind, bool bClear = true) const protected
References ug::Grid::associated_elements(), dim, ug::DoFDistributionInfoProvider::dim(), dof_indices(), ug::EDGE, ug::FACE, m_pMG, ug::DoFDistributionInfoProvider::max_dofs(), ug::VERTEX, and ug::VOLUME.
Referenced by num_indices().
template<typename TBaseElem > size_t ug::DoFDistribution::_dof_indices (TBaseElem * elem, size_t fct, std::vector< DoFIndex > & ind, bool bHang = false, bool bClear = true) const protected
References ug::Grid::associated_elements_sorted(), dim, ug::DoFDistributionInfoProvider::dim(), ug::EDGE, ug::FACE, m_pMG, ug::DoFDistributionInfoProvider::max_dofs(), ug::VERTEX, and ug::VOLUME.
Referenced by num_indices().
template<typename TBaseElem > void ug::DoFDistribution::_indices (TBaseElem * elem, LocalIndices & ind, bool bHang = false) const protected
References ug::Grid::associated_elements_sorted(), changable_indices(), ug::LocalIndices::clear_dof(), dim, ug::DoFDistributionInfoProvider::dim(), ug::EDGE, ug::FACE, m_pMG, ug::DoFDistributionInfoProvider::max_dofs(), ug::DoFDistributionInfoProvider::num_fct(), ug::LocalIndices::resize_fct(), ug::VERTEX, and ug::VOLUME.
Referenced by num_indices().
template<typename TBaseElem > size_t ug::DoFDistribution::_inner_algebra_indices (TBaseElem * elem, std::vector< size_t > & ind, bool bClear = true) const protected
References extract_inner_algebra_indices().
Referenced by num_indices().
template<typename TBaseElem > size_t ug::DoFDistribution::_inner_dof_indices (TBaseElem * elem, size_t fct, std::vector< DoFIndex > & ind, bool bClear = true) const protected
References constrained_vertex_dof_indices(), ug::DoFDistributionInfoProvider::is_def_in_subset(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_fct_dofs(), obj_index(), and ug::DoFDistributionInfoProvider::offset().
Referenced by num_indices().
template<typename TBaseObject > void ug::DoFDistribution::add (TBaseObject * obj, const ReferenceObjectID roid, const int si) protected
adds indices to a geometric object
References extract_inner_algebra_indices(), ug::PeriodicBoundaryManager::is_master(), ug::PeriodicBoundaryManager::is_slave(), m_bGrouped, m_numIndex, m_spMG, m_vNumIndexOnSubset, ug::DoFDistributionInfoProvider::num_dofs(), obj_index(), and UG_ASSERT.
Referenced by defaultValidSurfState(), num_indices(), and reinit().
template<typename TBaseElem > void ug::DoFDistribution::add_indices_from_layouts (IndexLayout & indexLayout, int keyType) protected
References pcl::OrderedInterface< TType, TContainer, TAlloc >::get_element(), ug::GridLayoutMap::get_layout(), grid_level(), ug::GridLayoutMap::has_layout(), inner_algebra_indices(), pcl::SingleLevelLayout< TInterface >::interface(), ug::GridLevel::is_surface(), ug::GridLevel::level(), m_spMG, m_spSurfView, multi_grid(), ug::SurfaceView::SURFACE, and ug::GridLevel::top().
Referenced by reinit_index_layout().
size_t ug::DoFDistribution::algebra_indices (GridObject * elem, std::vector< size_t > & ind, bool bClear = true) const
extracts all algebra indices of an element (not sorted)
All Algebra-Indices of the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is not sorted, no constrained DoFs are extracted. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[out] ind vector of algebra indices
[in] bClear flag if vector has to be clear before insertion
References ug::GridObject::base_object_id(), ug::EDGE, ug::FACE, UG_THROW, ug::VERTEX, and ug::VOLUME.
Referenced by num_indices().
size_t ug::DoFDistribution::algebra_indices (Vertex * elem, std::vector< size_t > & ind, bool bClear = true) const
extracts all algebra indices of an element (not sorted)
All Algebra-Indices of the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is not sorted, no constrained DoFs are extracted. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[out] ind vector of algebra indices
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::algebra_indices (Edge * elem, std::vector< size_t > & ind, bool bClear = true) const
extracts all algebra indices of an element (not sorted)
All Algebra-Indices of the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is not sorted, no constrained DoFs are extracted. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[out] ind vector of algebra indices
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::algebra_indices (Face * elem, std::vector< size_t > & ind, bool bClear = true) const
extracts all algebra indices of an element (not sorted)
All Algebra-Indices of the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is not sorted, no constrained DoFs are extracted. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[out] ind vector of algebra indices
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::algebra_indices (Volume * elem, std::vector< size_t > & ind, bool bClear = true) const
extracts all algebra indices of an element (not sorted)
All Algebra-Indices of the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is not sorted, no constrained DoFs are extracted. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[out] ind vector of algebra indices
[in] bClear flag if vector has to be clear before insertion
template<typename TElem > traits<TElem>::iterator ug::DoFDistribution::begin () inline
iterator for elements where dofs are defined
References defaultValidSurfState(), m_gridLevel, and m_spSurfView.
Referenced by ug::SymP1Constraints< TDomain, TAlgebra >::adjust_defect(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_defect(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_error(), ug::SymP1Constraints< TDomain, TAlgebra >::adjust_jacobian(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_jacobian(), ug::SymP1Constraints< TDomain, TAlgebra >::adjust_linear(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_linear(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_prolongation(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_restriction(), ug::SymP1Constraints< TDomain, TAlgebra >::adjust_rhs(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_rhs(), ug::SymP1Constraints< TDomain, TAlgebra >::adjust_solution(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_solution(), ug::DirichletBoundary< TDomain, TAlgebra >::assemble_dirichlet_rows(), ug::CheckDoFElem(), ug::ExtractAlgebraIndices2(), ug::ExtractPositionsElem(), ug::ExtractPositionsVertex(), and get_connections().
template<typename TElem > traits<TElem>::iterator ug::DoFDistribution::begin (SurfaceView::SurfaceConstants validStates) inline
iterator for elements where dofs are defined
References m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::const_iterator ug::DoFDistribution::begin () const inline
iterator for elements where dofs are defined
References defaultValidSurfState(), m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::const_iterator ug::DoFDistribution::begin (SurfaceView::SurfaceConstants validStates) const inline
iterator for elements where dofs are defined
References m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::iterator ug::DoFDistribution::begin (int si) inline
iterator for elements where dofs are defined
References defaultValidSurfState(), m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::iterator ug::DoFDistribution::begin (int si, SurfaceView::SurfaceConstants validStates) inline
iterator for elements where dofs are defined
References m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::const_iterator ug::DoFDistribution::begin (int si) const inline
iterator for elements where dofs are defined
References defaultValidSurfState(), m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::const_iterator ug::DoFDistribution::begin (int si, SurfaceView::SurfaceConstants validStates) const inline
iterator for elements where dofs are defined
References m_gridLevel, and m_spSurfView.
template<typename TBaseElem > void ug::DoFDistribution::changable_indices (std::vector< size_t > & vIndex, const std::vector< TBaseElem * > & vElem) const protected
returns indices, that can be changed on the element
References m_spMGSH, obj_index(), and UG_ASSERT.
Referenced by _indices(), and num_indices().
void ug::DoFDistribution::check_subsets () protected
checks that subset assignment is ok
References m_spMGSH, multi_grid(), and UG_THROW.
Referenced by DoFDistribution(), and num_indices().
template<typename TElem , typename TBaseElem > void ug::DoFDistribution::collect_associated (std::vector< TBaseElem * > & vAssElem, TElem * elem, bool clearContainer = true) const inline
returns the adjacent elements
References grid_level(), and m_spSurfView.
Referenced by ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), and get_connections().
template<typename TBaseElem , typename TConstraining , typename TConstrained , typename TSubElem > void ug::DoFDistribution::constrained_edge_dof_indices (TBaseElem * elem, size_t fct, std::vector< DoFIndex > & ind, const typename Grid::traits< TSubElem >::secure_container & vSubElem) const protected
multi indices on constrained edges
References ug::ComputeOrientationOffset(), constrained_face_dof_indices(), ug::DoFDistributionInfoProvider::is_def_in_subset(), ug::DoFDistributionInfoProvider::lfeid(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_dofs(), ug::DoFDistributionInfoProvider::num_fct_dofs(), obj_index(), ug::DoFDistributionInfoProvider::offset(), and ug::PointerConstArray< TPtr >::size().
Referenced by constrained_vertex_dof_indices(), and num_indices().
template<typename TBaseElem , typename TConstraining , typename TConstrained , typename TSubElem > void ug::DoFDistribution::constrained_edge_indices (TBaseElem * elem, LocalIndices & ind, const typename Grid::traits< TSubElem >::secure_container & vSubElem) const protected
References constrained_face_indices(), ug::DoFDistributionInfoProvider::is_def_in_subset(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_fct(), obj_index(), ug::DoFDistributionInfoProvider::offset(), ug::LocalIndices::push_back_index(), ug::LocalIndices::push_back_multi_index(), and ug::PointerConstArray< TPtr >::size().
Referenced by num_indices(), and sort_constrained_faces().
template<typename TBaseElem , typename TConstraining , typename TConstrained , typename TSubElem > void ug::DoFDistribution::constrained_face_dof_indices (TBaseElem * elem, size_t fct, std::vector< DoFIndex > & ind, const typename Grid::traits< TSubElem >::secure_container & vSubElem) const protected
multi indices on constrained faces
References ug::ComputeOrientationOffset(), ug::DoFDistributionInfoProvider::is_def_in_subset(), ug::DoFDistributionInfoProvider::lfeid(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_dofs(), ug::DoFDistributionInfoProvider::num_fct_dofs(), obj_index(), ug::DoFDistributionInfoProvider::offset(), and ug::PointerConstArray< TPtr >::size().
Referenced by constrained_edge_dof_indices(), and num_indices().
template<typename TBaseElem , typename TConstraining , typename TConstrained , typename TSubElem > void ug::DoFDistribution::constrained_face_indices (TBaseElem * elem, LocalIndices & ind, const typename Grid::traits< TSubElem >::secure_container & vSubElem) const protected
References ug::DoFDistributionInfoProvider::is_def_in_subset(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_fct(), obj_index(), ug::DoFDistributionInfoProvider::offset(), ug::LocalIndices::push_back_index(), ug::LocalIndices::push_back_multi_index(), and ug::PointerConstArray< TPtr >::size().
Referenced by constrained_edge_indices(), and num_indices().
template<typename TConstraining , typename TConstrained , typename TBaseElem > void ug::DoFDistribution::constrained_vertex_dof_indices (size_t fct, std::vector< DoFIndex > & ind, const typename Grid::traits< TBaseElem >::secure_container & vSubElem) const protected
multi indices on constrained vertices
References constrained_edge_dof_indices(), ug::DoFDistributionInfoProvider::is_def_in_subset(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_dofs(), ug::DoFDistributionInfoProvider::num_fct_dofs(), obj_index(), ug::DoFDistributionInfoProvider::offset(), and ug::PointerConstArray< TPtr >::size().
Referenced by _inner_dof_indices(), and num_indices().
template<typename TConstraining , typename TConstrained , typename TBaseElem > void ug::DoFDistribution::constrained_vertex_indices (LocalIndices & ind, const typename Grid::traits< TBaseElem >::secure_container & vSubElem) const protected
extract dofs on constrained objects
References ug::DoFDistributionInfoProvider::is_def_in_subset(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_fct(), obj_index(), ug::DoFDistributionInfoProvider::offset(), ug::LocalIndices::push_back_index(), ug::LocalIndices::push_back_multi_index(), ug::PointerConstArray< TPtr >::size(), and sort_constrained_edges().
Referenced by indices(), and num_indices().
void ug::DoFDistribution::copy_values (const std::vector< std::pair< size_t, size_t > > & vIndexMap, bool bDisjunct)
swaps values in managed functions, if indices swapped
References m_vpGridFunction.
SurfaceView::SurfaceConstants ug::DoFDistribution::defaultValidSurfState () const
returns the default valid surface state
References add(), ug::SurfaceView::ALL, ug::SurfaceView::ALL_BUT_SHADOW_COPY, ug::GridLevel::is_level(), ug::GridLevel::is_surface(), m_gridLevel, and UG_THROW.
Referenced by begin(), and end().
DoFCount ug::DoFDistribution::dof_count () const
References ug::DoFDistributionInfoProvider::dof_distribution_info(), ug::EDGE, ug::FACE, get_connections(), grid_level(), ug::DoFDistributionInfoProvider::max_dofs(), PROFILE_FUNC, ug::VERTEX, and ug::VOLUME.
size_t ug::DoFDistribution::dof_indices (GridObject * elem, size_t fct, std::vector< DoFIndex > & ind, bool bHang = false, bool bClear = true) const
extracts all multiindices for a function (sorted)
All Multi-Indices of a function living on the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bHang is set to true, also the DoFs on the Constrained Objects belonging to the constraining Subelements are extracted and added at the end of the indices. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[in] fct the function
[out] ind vector of multi indices
[in] bHang flag if extracting of constrained dofs required
[in] bClear flag if vector has to be clear before insertion
References ug::GridObject::base_object_id(), ug::EDGE, ug::FACE, UG_THROW, ug::VERTEX, and ug::VOLUME.
Referenced by _algebra_indices(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_error(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), ug::CheckDoFElem(), num_indices(), ug::ProlongateElemwise(), and ug::RestrictElemwise().
size_t ug::DoFDistribution::dof_indices (Vertex * elem, size_t fct, std::vector< DoFIndex > & ind, bool bHang = false, bool bClear = true) const
extracts all multiindices for a function (sorted)
All Multi-Indices of a function living on the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bHang is set to true, also the DoFs on the Constrained Objects belonging to the constraining Subelements are extracted and added at the end of the indices. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[in] fct the function
[out] ind vector of multi indices
[in] bHang flag if extracting of constrained dofs required
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::dof_indices (Edge * elem, size_t fct, std::vector< DoFIndex > & ind, bool bHang = false, bool bClear = true) const
extracts all multiindices for a function (sorted)
All Multi-Indices of a function living on the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bHang is set to true, also the DoFs on the Constrained Objects belonging to the constraining Subelements are extracted and added at the end of the indices. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[in] fct the function
[out] ind vector of multi indices
[in] bHang flag if extracting of constrained dofs required
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::dof_indices (Face * elem, size_t fct, std::vector< DoFIndex > & ind, bool bHang = false, bool bClear = true) const
extracts all multiindices for a function (sorted)
All Multi-Indices of a function living on the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bHang is set to true, also the DoFs on the Constrained Objects belonging to the constraining Subelements are extracted and added at the end of the indices. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[in] fct the function
[out] ind vector of multi indices
[in] bHang flag if extracting of constrained dofs required
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::dof_indices (Volume * elem, size_t fct, std::vector< DoFIndex > & ind, bool bHang = false, bool bClear = true) const
extracts all multiindices for a function (sorted)
All Multi-Indices of a function living on the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bHang is set to true, also the DoFs on the Constrained Objects belonging to the constraining Subelements are extracted and added at the end of the indices. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[in] fct the function
[out] ind vector of multi indices
[in] bHang flag if extracting of constrained dofs required
[in] bClear flag if vector has to be clear before insertion
template<typename TBaseElem , typename TSubBaseElem > void ug::DoFDistribution::dof_indices (TBaseElem * elem, const ReferenceObjectID roid, size_t fct, std::vector< DoFIndex > & ind, const typename Grid::traits< TSubBaseElem >::secure_container & vElem) const protected
extracts the indices of a subelement of an element
References ug::ComputeOrientationOffset(), ug::DoFDistributionInfoProvider::is_def_in_subset(), ug::DoFDistributionInfoProvider::lfeid(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_dofs(), ug::DoFDistributionInfoProvider::num_fct_dofs(), obj_index(), ug::DoFDistributionInfoProvider::offset(), ug::PointerConstArray< TPtr >::size(), and UG_ASSERT.
template<typename TElem > traits<TElem>::iterator ug::DoFDistribution::end () inline
iterator for elements where dofs are defined
References defaultValidSurfState(), m_gridLevel, and m_spSurfView.
Referenced by ug::SymP1Constraints< TDomain, TAlgebra >::adjust_defect(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_defect(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_error(), ug::SymP1Constraints< TDomain, TAlgebra >::adjust_jacobian(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_jacobian(), ug::SymP1Constraints< TDomain, TAlgebra >::adjust_linear(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_linear(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_prolongation(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_restriction(), ug::SymP1Constraints< TDomain, TAlgebra >::adjust_rhs(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_rhs(), ug::SymP1Constraints< TDomain, TAlgebra >::adjust_solution(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_solution(), ug::DirichletBoundary< TDomain, TAlgebra >::assemble_dirichlet_rows(), ug::CheckDoFElem(), ug::ExtractAlgebraIndices2(), ug::ExtractPositionsElem(), ug::ExtractPositionsVertex(), and get_connections().
template<typename TElem > traits<TElem>::iterator ug::DoFDistribution::end (SurfaceView::SurfaceConstants validStates) inline
iterator for elements where dofs are defined
References m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::const_iterator ug::DoFDistribution::end () const inline
iterator for elements where dofs are defined
References defaultValidSurfState(), m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::const_iterator ug::DoFDistribution::end (SurfaceView::SurfaceConstants validStates) const inline
iterator for elements where dofs are defined
References m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::iterator ug::DoFDistribution::end (int si) inline
iterator for elements where dofs are defined
References defaultValidSurfState(), m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::iterator ug::DoFDistribution::end (int si, SurfaceView::SurfaceConstants validStates) inline
iterator for elements where dofs are defined
References m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::const_iterator ug::DoFDistribution::end (int si) const inline
iterator for elements where dofs are defined
References defaultValidSurfState(), m_gridLevel, and m_spSurfView.
template<typename TElem > traits<TElem>::const_iterator ug::DoFDistribution::end (int si, SurfaceView::SurfaceConstants validStates) const inline
iterator for elements where dofs are defined
References defaultValidSurfState(), m_gridLevel, and m_spSurfView.
template<typename TBaseElem > size_t ug::DoFDistribution::extract_inner_algebra_indices (TBaseElem * elem, std::vector< size_t > & ind) const protected
adds all algebra indices of an geom object to the LocalIndices
References ug::DoFDistributionInfoProvider::is_def_in_subset(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_dofs(), ug::DoFDistributionInfoProvider::num_fct(), ug::DoFDistributionInfoProvider::num_fct_dofs(), obj_index(), and ug::DoFDistributionInfoProvider::offset().
Referenced by _inner_algebra_indices(), add(), and num_indices().
template<typename TBaseElem > void ug::DoFDistribution::extract_inner_algebra_indices (const typename Grid::traits< TBaseElem >::secure_container & vElem, std::vector< size_t > & ind) const protected
adds all algebra indices of a set of geometric objects
References inner_algebra_indices(), and ug::PointerConstArray< TPtr >::size().
void ug::DoFDistribution::get_connections (std::vector< std::vector< size_t > > & vvConnection) const
returns the connections
References grouped(), ug::DoFDistributionInfoProvider::num_dofs(), num_indices(), ug::NUM_REFERENCE_OBJECTS, ug::DoFDistributionInfoProvider::num_subsets(), and UG_THROW.
Referenced by dof_count(), get_connections(), and ug::OrderCuthillMcKee().
template<typename TBaseElem > void ug::DoFDistribution::get_connections (std::vector< std::vector< size_t > > & vvConnection) const protected
References begin(), collect_associated(), dim, ug::DoFDistributionInfoProvider::dim(), ug::EDGE, end(), ug::FACE, ug::find(), get_connections(), ug::DoFDistributionInfoProvider::max_dofs(), ug::VERTEX, and ug::VOLUME.
const GridLevel& ug::DoFDistribution::grid_level () const inline
returns grid level
References m_gridLevel.
Referenced by add_indices_from_layouts(), ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::calc_error(), collect_associated(), dof_count(), is_contained(), reinit(), reinit_layouts_and_communicator(), and sum_dof_count().
bool ug::DoFDistribution::grouped () const inline
returns if dofs are grouped
References m_bGrouped.
Referenced by get_connections().
void ug::DoFDistribution::indices (GridObject * elem, LocalIndices & ind, bool bHang = false) const
extracts all indices of the element (sorted)
All Indices of the element (including the subelements) are extracted and stored in the LocalIndices structure. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bHang is set to true, also the DoFs on the Constained Objects belonging to the constraining Subelements are extracted and added at the end of the indices.
Parameters
[in] elem the element
[out] ind Local indices
[in] bHang flag if extracting of constrained dofs required
References ug::GridObject::base_object_id(), ug::EDGE, ug::FACE, UG_THROW, ug::VERTEX, and ug::VOLUME.
Referenced by num_indices().
void ug::DoFDistribution::indices (Vertex * elem, LocalIndices & ind, bool bHang = false) const
extracts all indices of the element (sorted)
All Indices of the element (including the subelements) are extracted and stored in the LocalIndices structure. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bHang is set to true, also the DoFs on the Constained Objects belonging to the constraining Subelements are extracted and added at the end of the indices.
Parameters
[in] elem the element
[out] ind Local indices
[in] bHang flag if extracting of constrained dofs required
void ug::DoFDistribution::indices (Edge * elem, LocalIndices & ind, bool bHang = false) const
extracts all indices of the element (sorted)
All Indices of the element (including the subelements) are extracted and stored in the LocalIndices structure. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bHang is set to true, also the DoFs on the Constained Objects belonging to the constraining Subelements are extracted and added at the end of the indices.
Parameters
[in] elem the element
[out] ind Local indices
[in] bHang flag if extracting of constrained dofs required
void ug::DoFDistribution::indices (Face * elem, LocalIndices & ind, bool bHang = false) const
extracts all indices of the element (sorted)
All Indices of the element (including the subelements) are extracted and stored in the LocalIndices structure. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bHang is set to true, also the DoFs on the Constained Objects belonging to the constraining Subelements are extracted and added at the end of the indices.
Parameters
[in] elem the element
[out] ind Local indices
[in] bHang flag if extracting of constrained dofs required
void ug::DoFDistribution::indices (Volume * elem, LocalIndices & ind, bool bHang = false) const
extracts all indices of the element (sorted)
All Indices of the element (including the subelements) are extracted and stored in the LocalIndices structure. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bHang is set to true, also the DoFs on the Constained Objects belonging to the constraining Subelements are extracted and added at the end of the indices.
Parameters
[in] elem the element
[out] ind Local indices
[in] bHang flag if extracting of constrained dofs required
template<typename TBaseElem , typename TSubBaseElem > void ug::DoFDistribution::indices (TBaseElem * elem, const ReferenceObjectID roid, LocalIndices & ind, const typename Grid::traits< TSubBaseElem >::secure_container & vElem) const protected
extracts the indices of the subelement of an element
References ug::ComputeOrientationOffset(), constrained_vertex_indices(), ug::DoFDistributionInfoProvider::is_def_in_subset(), ug::DoFDistributionInfoProvider::lfeid(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_fct(), ug::DoFDistributionInfoProvider::num_fct_dofs(), obj_index(), ug::DoFDistributionInfoProvider::offset(), ug::LocalIndices::push_back_index(), ug::LocalIndices::push_back_multi_index(), ug::PointerConstArray< TPtr >::size(), and UG_ASSERT.
template<typename TBaseElem > void ug::DoFDistribution::indices_on_vertex (TBaseElem * elem, const ReferenceObjectID roid, LocalIndices & ind, const Grid::SecureVertexContainer & vElem) const protected
extracts the indices of the vertices
References ug::DoFDistributionInfoProvider::is_def_in_subset(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_fct(), ug::DoFDistributionInfoProvider::num_fct_dofs(), obj_index(), ug::DoFDistributionInfoProvider::offset(), ug::LocalIndices::push_back_index(), ug::LocalIndices::push_back_multi_index(), and ug::ROID_VERTEX.
Referenced by num_indices().
size_t ug::DoFDistribution::inner_algebra_indices (GridObject * elem, std::vector< size_t > & ind, bool bClear = true) const
extracts all algebra indices in the inner of the element (not sorted)
All Algebra-Indices of the element (excluding the subelements) are extracted and stored in a std::vector. The order of the indices is not sorted, no constrained DoFs are extracted. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[out] ind vector of algebra indices
[in] bClear flag if vector has to be clear before insertion
References ug::GridObject::base_object_id(), ug::EDGE, ug::FACE, UG_THROW, ug::VERTEX, and ug::VOLUME.
Referenced by add_indices_from_layouts(), ug::AddEntriesToIndexLayout_DomainDecomposition(), ug::AddEntriesToLevelIndexLayout(), ug::AddEntriesToSurfaceIndexLayout(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), ug::AssembleInjectionByAverageOfChildren(), ug::AssembleInjectionForP1Lagrange(), extract_inner_algebra_indices(), ug::ExtractPositionsVertex(), num_indices(), and ug::StdInjection< TDomain, TAlgebra >::set_identity_on_pure_surface().
size_t ug::DoFDistribution::inner_algebra_indices (Vertex * elem, std::vector< size_t > & ind, bool bClear = true) const
extracts all algebra indices in the inner of the element (not sorted)
All Algebra-Indices of the element (excluding the subelements) are extracted and stored in a std::vector. The order of the indices is not sorted, no constrained DoFs are extracted. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[out] ind vector of algebra indices
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::inner_algebra_indices (Edge * elem, std::vector< size_t > & ind, bool bClear = true) const
extracts all algebra indices in the inner of the element (not sorted)
All Algebra-Indices of the element (excluding the subelements) are extracted and stored in a std::vector. The order of the indices is not sorted, no constrained DoFs are extracted. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[out] ind vector of algebra indices
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::inner_algebra_indices (Face * elem, std::vector< size_t > & ind, bool bClear = true) const
extracts all algebra indices in the inner of the element (not sorted)
All Algebra-Indices of the element (excluding the subelements) are extracted and stored in a std::vector. The order of the indices is not sorted, no constrained DoFs are extracted. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[out] ind vector of algebra indices
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::inner_algebra_indices (Volume * elem, std::vector< size_t > & ind, bool bClear = true) const
extracts all algebra indices in the inner of the element (not sorted)
All Algebra-Indices of the element (excluding the subelements) are extracted and stored in a std::vector. The order of the indices is not sorted, no constrained DoFs are extracted. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[out] ind vector of algebra indices
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::inner_algebra_indices_for_fct (GridObject * elem, std::vector< size_t > & ind, bool bClear, int fct) const
References ug::DoFDistributionInfoProvider::is_def_in_subset(), m_bGrouped, m_spMGSH, ug::DoFDistributionInfoProvider::num_dofs(), ug::DoFDistributionInfoProvider::num_fct_dofs(), obj_index(), ug::DoFDistributionInfoProvider::offset(), and ug::GridObject::reference_object_id().
Referenced by ug::ExtractAlgebraIndices2(), ug::get_algebra_indices(), and num_indices().
size_t ug::DoFDistribution::inner_dof_indices (GridObject * elem, size_t fct, std::vector< DoFIndex > & ind, bool bClear = true) const
extracts all multiindices of a function in the inner (sorted)
All Multi-Indices of a function living on the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[in] fct the function
[out] ind vector of multi indices
[in] bClear flag if vector has to be clear before insertion
References ug::GridObject::base_object_id(), ug::EDGE, ug::FACE, UG_THROW, ug::VERTEX, and ug::VOLUME.
Referenced by ug::DirichletBoundary< TDomain, TAlgebra >::adjust_defect(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_jacobian(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_linear(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_prolongation(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_restriction(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_rhs(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_solution(), ug::DirichletBoundary< TDomain, TAlgebra >::assemble_dirichlet_rows(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), ug::CheckDoFElem(), ug::collectStretchedElementIndices(), ug::ExtractPositionsElem(), num_indices(), and ug::RestrictElemwise().
size_t ug::DoFDistribution::inner_dof_indices (Vertex * elem, size_t fct, std::vector< DoFIndex > & ind, bool bClear = true) const
extracts all multiindices of a function in the inner (sorted)
All Multi-Indices of a function living on the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[in] fct the function
[out] ind vector of multi indices
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::inner_dof_indices (Edge * elem, size_t fct, std::vector< DoFIndex > & ind, bool bClear = true) const
extracts all multiindices of a function in the inner (sorted)
All Multi-Indices of a function living on the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[in] fct the function
[out] ind vector of multi indices
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::inner_dof_indices (Face * elem, size_t fct, std::vector< DoFIndex > & ind, bool bClear = true) const
extracts all multiindices of a function in the inner (sorted)
All Multi-Indices of a function living on the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[in] fct the function
[out] ind vector of multi indices
[in] bClear flag if vector has to be clear before insertion
size_t ug::DoFDistribution::inner_dof_indices (Volume * elem, size_t fct, std::vector< DoFIndex > & ind, bool bClear = true) const
extracts all multiindices of a function in the inner (sorted)
All Multi-Indices of a function living on the element (including the subelements) are extracted and stored in a std::vector. The order of the indices is sorted, i.e. the dofs are provided as specified in the local dof set of the local finite element trial space. If bClear is set to true, the vector is cleared before insertion.
Parameters
[in] elem the element
[in] fct the function
[out] ind vector of multi indices
[in] bClear flag if vector has to be clear before insertion
template<class TGeomObj > bool ug::DoFDistribution::is_contained (TGeomObj * obj) const inline
returns if the grid object is part of the dof distribution
References grid_level(), and m_spSurfView.
Referenced by ug::DirichletBoundary< TDomain, TAlgebra >::adjust_prolongation(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_restriction(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), and ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction().
ConstSmartPtr<AlgebraLayouts> ug::DoFDistribution::layouts () const inline
returns algebra layouts
References spAlgebraLayouts.
Referenced by ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::assemble_jacobian(), ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::assemble_linear(), ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::assemble_mass_matrix(), ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::assemble_stiffness_matrix(), reinit_layouts_and_communicator(), and ug::WriteAlgebraIndices().
SmartPtr<AlgebraLayouts> ug::DoFDistribution::layouts () inline
returns algebra layouts
References spAlgebraLayouts.
void ug::DoFDistribution::manage_grid_function (IGridFunction & gridFct)
registers a grid function for adaptation management
References m_vpGridFunction.
SmartPtr<MultiGrid> ug::DoFDistribution::multi_grid () inline
returns the multigrid
References m_spMG.
Referenced by add_indices_from_layouts(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), ug::AssembleInjectionByAverageOfChildren(), ug::AssembleInjectionForP1Lagrange(), check_subsets(), ug::get_algebra_indices(), ug::MarkElements(), ug::MarkElementsAbsolute(), ug::MarkElementsForCoarsening(), ug::MarkElementsForRefinement(), ug::StdInjection< TDomain, TAlgebra >::set_identity_on_pure_surface(), sort_constrained_edges(), and sort_constrained_faces().
ConstSmartPtr<MultiGrid> ug::DoFDistribution::multi_grid () const inline
returns the multigrid
References m_spMG.
size_t ug::DoFDistribution::num_indices () const inline
return the number of dofs distributed
References m_numIndex.
Referenced by ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), ug::AssembleInjectionByAverageOfChildren(), ug::AssembleInjectionForP1Lagrange(), ug::CheckDoFPositions(), ug::ExtractAlgebraIndices(), ug::ExtractPositions(), ug::ExtractPositionsVertex(), get_connections(), ug::OrderLexForDofDist(), reinit_layouts_and_communicator(), and ug::AssemblingTuner< TAlgebra >::resize().
size_t ug::DoFDistribution::num_indices (int si) const inline
return the number of dofs distributed on subset si
References _algebra_indices(), _dof_indices(), _indices(), _inner_algebra_indices(), _inner_dof_indices(), add(), algebra_indices(), changable_indices(), check_subsets(), constrained_edge_dof_indices(), constrained_edge_indices(), constrained_face_dof_indices(), constrained_face_indices(), constrained_vertex_dof_indices(), constrained_vertex_indices(), dof_indices(), extract_inner_algebra_indices(), indices(), indices_on_vertex(), inner_algebra_indices(), inner_algebra_indices_for_fct(), inner_dof_indices(), m_vNumIndexOnSubset, sort_constrained_edges(), and sort_constrained_faces().
template<typename TElem > size_t& ug::DoFDistribution::obj_index (TElem * obj) inline protected
returns the index assigned to a grid object
References m_spDoFIndexStorage.
Referenced by _inner_dof_indices(), add(), changable_indices(), constrained_edge_dof_indices(), constrained_edge_indices(), constrained_face_dof_indices(), constrained_face_indices(), constrained_vertex_dof_indices(), constrained_vertex_indices(), dof_indices(), extract_inner_algebra_indices(), indices(), indices_on_vertex(), inner_algebra_indices_for_fct(), permute_indices(), and reinit().
template<typename TElem > const size_t& ug::DoFDistribution::obj_index (TElem * obj) const inline protected
returns the index assigned to a grid object
References m_spDoFIndexStorage.
void ug::DoFDistribution::permute_indices (const std::vector< size_t > & vIndNew)
renames the indices
References ug::EDGE, ug::FACE, ug::DoFDistributionInfoProvider::max_dofs(), permute_values(), reinit_layouts_and_communicator(), ug::VERTEX, and ug::VOLUME.
Referenced by ug::OrderCuthillMcKee(), and ug::OrderLexForDofDist().
template<typename TBaseElem > void ug::DoFDistribution::permute_indices (const std::vector< size_t > & vNewInd) protected
References ug::SurfaceView::ALL, and obj_index().
void ug::DoFDistribution::permute_values (const std::vector< size_t > & vIndNew)
permutes values in managed functions, if indices permuted
References m_vpGridFunction.
Referenced by permute_indices().
void ug::DoFDistribution::reinit ()
initializes the indices
References ug::EDGE, ug::FACE, m_numIndex, m_vNumIndexOnSubset, ug::DoFDistributionInfoProvider::max_dofs(), ug::DoFDistributionInfoProvider::num_subsets(), reinit_layouts_and_communicator(), ug::VERTEX, and ug::VOLUME.
Referenced by DoFDistribution().
template<typename TBaseElem > void ug::DoFDistribution::reinit () protected
initializes the indices
References add(), ug::SurfaceView::ALL, dim, ug::DoFDistributionInfoProvider::dim(), ug::MultiGrid::get_child(), ug::MultiGrid::get_parent(), grid_level(), ug::SurfaceView::is_contained(), ug::GridLevel::LEVEL, m_spMG, m_spSurfView, ug::DoFDistributionInfoProvider::max_dofs(), ug::MultiGrid::num_children(), ug::DoFDistributionInfoProvider::num_subsets(), obj_index(), ug::SurfaceView::SHADOW_RIM_COPY, ug::GridLevel::SURFACE, ug::SurfaceView::SURFACE_RIM, ug::GridLevel::type(), and UG_THROW.
void ug::DoFDistribution::reinit_index_layout (IndexLayout & layout, int keyType) protected
References add_indices_from_layouts(), pcl::SingleLevelLayout< TInterface >::clear(), ug::EDGE, ug::FACE, ug::DoFDistributionInfoProvider::max_dofs(), pcl::RemoveEmptyInterfaces(), ug::VERTEX, and ug::VOLUME.
Referenced by reinit_layouts_and_communicator().
void ug::DoFDistribution::reinit_layouts_and_communicator () protected
References pcl::ProcessCommunicator::create_sub_communicator(), pcl::ProcessCommunicator::empty(), grid_level(), ug::INT_H_MASTER, ug::INT_H_SLAVE, ug::INT_V_MASTER, ug::INT_V_SLAVE, layouts(), num_indices(), and reinit_index_layout().
Referenced by permute_indices(), and reinit().
void ug::DoFDistribution::resize_values (size_t newSize)
changes values in managed functions, number of indices changed
References m_vpGridFunction.
template<typename TBaseElem , typename TConstraining , typename TConstrained > void ug::DoFDistribution::sort_constrained_edges (std::vector< size_t > & sortedInd, TBaseElem * elem, TConstraining * constrainingObj, size_t objIndex) const protected
References dim, ug::DoFDistributionInfoProvider::dim(), ug::ReferenceElement::id(), multi_grid(), sort_constrained_faces(), UG_THROW, ug::FaceVertices::vertex(), and ug::VolumeVertices::vertex().
Referenced by constrained_vertex_indices(), and num_indices().
template<typename TBaseElem , typename TConstraining , typename TConstrained > void ug::DoFDistribution::sort_constrained_faces (std::vector< size_t > & sortedInd, TBaseElem * elem, TConstraining * constrainingObj, size_t objIndex) const protected
References constrained_edge_indices(), dim, ug::DoFDistributionInfoProvider::dim(), ug::ReferenceElement::id(), multi_grid(), UG_THROW, and ug::VolumeVertices::vertex().
Referenced by num_indices(), and sort_constrained_edges().
template<typename TBaseElem > void ug::DoFDistribution::sum_dof_count (DoFCount & cnt) const protected
References ug::DoFCount::add(), ug::Flag< TEnum, TStorageType, defaultValue >::contains(), ug::ES_NONE, ug::DistributedGridManager::get_status(), grid_level(), m_spSurfView, ug::SurfaceView::MG_SHADOW_RIM_COPY, ug::DoFDistributionInfoProvider::num_fct(), ug::DoFDistributionInfoProvider::num_fct_dofs(), ug::SurfaceView::subset_handler(), and ug::SurfaceView::surface_state().
ConstSmartPtr<SurfaceView> ug::DoFDistribution::surface_view () const inline
returns the surface view
References m_spSurfView.
Referenced by ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::calc_error().
void ug::DoFDistribution::unmanage_grid_function (IGridFunction & gridFct)
unregisters a grid function for adaptation management
References m_vpGridFunction.
Member Data Documentation
bool ug::DoFDistribution::m_bGrouped protected
grouping
Referenced by _inner_dof_indices(), add(), constrained_edge_dof_indices(), constrained_edge_indices(), constrained_face_dof_indices(), constrained_face_indices(), constrained_vertex_dof_indices(), constrained_vertex_indices(), dof_indices(), extract_inner_algebra_indices(), grouped(), indices(), indices_on_vertex(), and inner_algebra_indices_for_fct().
GridLevel ug::DoFDistribution::m_gridLevel protected
Grid level.
Referenced by begin(), defaultValidSurfState(), end(), and grid_level().
size_t ug::DoFDistribution::m_numIndex protected
number of distributed indices on whole domain
Referenced by add(), num_indices(), and reinit().
MultiGrid* ug::DoFDistribution::m_pMG protected
Referenced by _algebra_indices(), _dof_indices(), and _indices().
SmartPtr<DoFIndexStorage> ug::DoFDistribution::m_spDoFIndexStorage protected
DoF-Index Memory Storage.
Referenced by DoFDistribution(), and obj_index().
SmartPtr<MultiGrid> ug::DoFDistribution::m_spMG protected
Multi Grid.
Referenced by add(), add_indices_from_layouts(), multi_grid(), and reinit().
SmartPtr<MGSubsetHandler> ug::DoFDistribution::m_spMGSH protected
Subset Handler.
Referenced by _inner_dof_indices(), changable_indices(), check_subsets(), constrained_edge_dof_indices(), constrained_edge_indices(), constrained_face_dof_indices(), constrained_face_indices(), constrained_vertex_dof_indices(), constrained_vertex_indices(), dof_indices(), extract_inner_algebra_indices(), indices(), indices_on_vertex(), and inner_algebra_indices_for_fct().
SmartPtr<SurfaceView> ug::DoFDistribution::m_spSurfView protected
MultiGrid Subset Handler.
Referenced by add_indices_from_layouts(), begin(), collect_associated(), end(), is_contained(), reinit(), sum_dof_count(), and surface_view().
std::vector<size_t> ug::DoFDistribution::m_vNumIndexOnSubset protected
number of distributed indices on each subset
Referenced by add(), DoFDistribution(), num_indices(), and reinit().
std::vector<IGridFunction*> ug::DoFDistribution::m_vpGridFunction protected
managed grid functions
This vector holds a pointer to all grid functions, that should be managed (i.e. adapted), when the dof distribution is changed. NOTE: No SmartPtr is used here on purpose. The GridFunction stores a SmartPtr to the DoFDistribution. If we would use a SmartPtr here those objects would reference each other and would never be deleted.
Referenced by copy_values(), manage_grid_function(), permute_values(), resize_values(), and unmanage_grid_function().
SmartPtr<AlgebraLayouts> ug::DoFDistribution::spAlgebraLayouts protected
algebra layouts
Referenced by DoFDistribution(), and layouts().
The documentation for this class was generated from the following files:
ugbase/lib_disc/dof_manager/dof_distribution.h
ugbase/lib_disc/dof_manager/dof_distribution.cpp