ug4: ug::IsNotInSubGrid Class Reference
ug::IsNotInSubGrid Class Reference
Callbacks that return true if an element is not contained in a sub-grid.
#include <sub_grid.h>
Public Member Functions
IsNotInSubGrid (const ISubGrid &subGrid)
bool operator() (Edge *e)
bool operator() (Face *f)
bool operator() (Vertex *v)
bool operator() (Volume *v)
Private Member Functions
template<class TElem >
bool callback (TElem *e)
Private Attributes
const ISubGrid & m_subGrid
Detailed Description
Callbacks that return true if an element is not contained in a sub-grid.
Please make sure that the associated sub-grid exists until the callback-class was destroyed.
Constructor & Destructor Documentation
IsNotInSubGrid()
ug::IsNotInSubGrid::IsNotInSubGrid (const ISubGrid & subGrid) inline
Member Function Documentation
callback()
template<class TElem > bool ug::IsNotInSubGrid::callback (TElem * e) inline private
References ug::ISubGrid::is_contained(), and m_subGrid.
Referenced by operator()().
operator()() [1/4]
bool ug::IsNotInSubGrid::operator() (Edge * e) inline
References callback().
operator()() [2/4]
bool ug::IsNotInSubGrid::operator() (Face * f) inline
References callback().
operator()() [3/4]
bool ug::IsNotInSubGrid::operator() (Vertex * v) inline
References callback().
operator()() [4/4]
bool ug::IsNotInSubGrid::operator() (Volume * v) inline
References callback().
Member Data Documentation
m_subGrid
const ISubGrid& ug::IsNotInSubGrid::m_subGrid private
Referenced by callback().
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/sub_grid.h