ug4: ug::ConvectionShapesWeightedUpwind< TDim > Class Template Reference
ug::ConvectionShapesWeightedUpwind< TDim > Class Template Reference
#include <conv_shape.h>
Public Types
typedef IConvectionShapes< TDim > base_type
Base class.
typedef ConvectionShapesWeightedUpwind< TDim > this_type
This class.
Public Types inherited from ug::IConvectionShapes< TDim >
typedef IConvectionShapes< dim > this_type
Abbreviation for own type.
typedef bool(this_type::* UpdateFunc) (const FVGeometryBase *geo, const MathVector< dim > *Velocity, const MathMatrix< dim, dim > *Diffusion, bool computeDeriv)
type of update function
Public Member Functions
ConvectionShapesWeightedUpwind ()
constructor
ConvectionShapesWeightedUpwind (number weight)
constructor
void set_weight (number weight)
set weighting between full upwind (1.0) and no upwind (0.0)
template<typename TFVGeom >
bool update (const TFVGeom *geo, const MathVector< dim > *Velocity, const MathMatrix< dim, dim > *DiffDisp, bool computeDeriv)
update of values for FV1Geometry
Public Member Functions inherited from ug::IConvectionShapes< TDim >
const MathMatrix< dim, dim > & D_diffusion (size_t scvf, size_t sh) const
upwind shapes for ip vel
const MathVector< dim > & D_vel (size_t scvf, size_t sh) const
upwind shape for corner vel
IConvectionShapes ()
constructor
bool non_zero_deriv_diffusion () const
returns if upwind shape w.r.t. ip vel is non-zero
size_t num_scvf () const
returns number of sub control volume faces
size_t num_sh () const
returns number of shapes
number operator() (size_t scvf, size_t sh) const
shape value
void register_update_func (TAssFunc func)
register a update function for a Geometry
bool set_geometry_type (const TFVGeom &geo)
set the Geometry type to use for next updates
bool update (const FVGeometryBase *geo, const MathVector< dim > *Velocity, const MathMatrix< dim, dim > *DiffDisp, bool computeDeriv)
virtual ~IConvectionShapes ()
destructor
Static Public Attributes
static const int dim = TDim
Dimension.
Private Member Functions
void register_func (Int2Type< 1 >)
void register_func (Int2Type< 2 >)
void register_func (Int2Type< 3 >)
template<typename TElem >
void register_func_for_elem ()
template<int refDim>
void register_func_for_refDim ()
Private Attributes
number m_weight
Additional Inherited Members
Protected Member Functions inherited from ug::IConvectionShapes< TDim >
number & conv_shape (size_t scvf, size_t sh)
non-const access to ip velocity (i.e. interpolated velocity at ip)
MathMatrix< dim, dim > & conv_shape_diffusion (size_t scvf, size_t sh)
non-const access to upwind shapes for ip vel
MathVector< dim > & D_vel (size_t scvf, size_t sh)
non-const access to upwind shapes for corner vel
void set_non_zero_deriv_diffusion_flag (bool flag)
sets the shape ip flag
void set_sizes (size_t numScvf, size_t numSh)
resize the data arrays
Protected Attributes inherited from ug::IConvectionShapes< TDim >
bool m_bNonZeroDerivDiffusion
flag if ip shapes are non-zero
int m_id
id of current geometry type
size_t m_numScvf
number of current scvf
size_t m_numSh
number of current shape functions (usually in corners)
std::vector< UpdateFunc > m_vUpdateFunc
Vector holding all update functions.
std::vector< std::vector< number > > m_vUpShape
upwind shapes for corners shape functions
std::vector< std::vector< MathMatrix< dim, dim > > > m_vUpShapeDiffusion
upwind shapes for corners shape functions
std::vector< std::vector< MathVector< dim > > > m_vUpShapeVel
upwind shapes for corners shape functions
Member Typedef Documentation
base_type
template<int TDim> typedef IConvectionShapes<TDim> ug::ConvectionShapesWeightedUpwind< TDim >::base_type
Base class.
this_type
template<int TDim> typedef ConvectionShapesWeightedUpwind<TDim> ug::ConvectionShapesWeightedUpwind< TDim >::this_type
This class.
Constructor & Destructor Documentation
ConvectionShapesWeightedUpwind() [1/2]
template<int TDim> ug::ConvectionShapesWeightedUpwind< TDim >::ConvectionShapesWeightedUpwind () inline
constructor
References ug::ConvectionShapesWeightedUpwind< TDim >::register_func(), and ug::IConvectionShapes< TDim >::set_non_zero_deriv_diffusion_flag().
ConvectionShapesWeightedUpwind() [2/2]
template<int TDim> ug::ConvectionShapesWeightedUpwind< TDim >::ConvectionShapesWeightedUpwind (number weight) inline
constructor
References ug::ConvectionShapesWeightedUpwind< TDim >::register_func(), ug::IConvectionShapes< TDim >::set_non_zero_deriv_diffusion_flag(), and ug::ConvectionShapesWeightedUpwind< TDim >::set_weight().
Member Function Documentation
register_func() [1/3]
template<int TDim> void ug::ConvectionShapesWeightedUpwind< TDim >::register_func (Int2Type< 1 >) inline private
Referenced by ug::ConvectionShapesWeightedUpwind< TDim >::ConvectionShapesWeightedUpwind(), and ug::ConvectionShapesWeightedUpwind< TDim >::register_func().
register_func() [2/3]
template<int TDim> void ug::ConvectionShapesWeightedUpwind< TDim >::register_func (Int2Type< 2 >) inline private
References ug::ConvectionShapesWeightedUpwind< TDim >::register_func().
register_func() [3/3]
template<int TDim> void ug::ConvectionShapesWeightedUpwind< TDim >::register_func (Int2Type< 3 >) inline private
References ug::ConvectionShapesWeightedUpwind< TDim >::register_func().
register_func_for_elem()
template<int TDim> template<typename TElem > void ug::ConvectionShapesWeightedUpwind< TDim >::register_func_for_elem () inline private
register_func_for_refDim()
template<int TDim> template<int refDim> void ug::ConvectionShapesWeightedUpwind< TDim >::register_func_for_refDim () inline private
set_weight()
template<int TDim> void ug::ConvectionShapesWeightedUpwind< TDim >::set_weight (number weight) inline
set weighting between full upwind (1.0) and no upwind (0.0)
References ug::ConvectionShapesWeightedUpwind< TDim >::m_weight.
Referenced by ug::ConvectionShapesWeightedUpwind< TDim >::ConvectionShapesWeightedUpwind().
update()
template<int TDim> template<typename TFVGeom > bool ug::ConvectionShapesWeightedUpwind< TDim >::update (const TFVGeom * geo, const MathVector< dim > * Velocity, const MathMatrix< dim, dim > * DiffDisp, bool computeDeriv)
update of values for FV1Geometry
References UG_ASSERT, ug::VecDot(), ug::VecScale(), ug::VecScaleAppend(), and ug::VecSet().
Member Data Documentation
dim
template<int TDim> const int ug::ConvectionShapesWeightedUpwind< TDim >::dim = TDim static
Dimension.
m_weight
template<int TDim> number ug::ConvectionShapesWeightedUpwind< TDim >::m_weight private
Referenced by ug::ConvectionShapesWeightedUpwind< TDim >::set_weight().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/conv_shape.h