ug4: ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra > Class Template Reference
ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra > Class Template Reference
Public Member Functions
bool evaluate (const std::vector< number > &pos, std::vector< number > &result, SmartPtr< TGridFunction > u, number time, bool interpolateOverNeighbouringTriangles)
std::vector< number > evaluateLua (const std::vector< number > &pos, SmartPtr< TGridFunction > u, number time, bool interpolateOverNeighbouringTriangles)
VectorValuedUserDataEvaluator (SmartPtr< UserData< MathVector< dim >, dim > > userData)
Private Types
typedef TGridFunction::template dim_traits< dim >::grid_base_object TElem
typedef GridFunction< TDomain, TAlgebra > TGridFunction
typedef lg_ntree< dim, dim, TElem > tree_t
Private Member Functions
bool evaluateOnThisProcess (const std::vector< number > &pos, std::vector< number > &result, SmartPtr< TGridFunction > u, number time)
bool evaluateOnThisProcessNeighbouring (const std::vector< number > &pos, std::vector< number > &result, SmartPtr< TGridFunction > u, number time)
void initialize (SmartPtr< TGridFunction > u)
Private Attributes
bool m_initialized = false
SmartPtr< tree_t > m_tree
SmartPtr< UserData< MathVector< dim >, dim > > m_userData
Static Private Attributes
static const int dim = TDomain::dim
Member Typedef Documentation
TElem
template<typename TDomain , typename TAlgebra > typedef TGridFunction::template dim_traits<dim>::grid_base_object ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::TElem private
TGridFunction
template<typename TDomain , typename TAlgebra > typedef GridFunction<TDomain, TAlgebra> ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::TGridFunction private
tree_t
template<typename TDomain , typename TAlgebra > typedef lg_ntree<dim, dim, TElem> ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::tree_t private
Constructor & Destructor Documentation
VectorValuedUserDataEvaluator()
template<typename TDomain , typename TAlgebra > ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::VectorValuedUserDataEvaluator (SmartPtr< UserData< MathVector< dim >, dim > > userData) inline
Member Function Documentation
evaluate()
template<typename TDomain , typename TAlgebra > bool ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::evaluate (const std::vector< number > & pos, std::vector< number > & result, SmartPtr< TGridFunction > u, number time, bool interpolateOverNeighbouringTriangles) inline
References pcl::ProcessCommunicator::allreduce(), dim, and PCL_RO_SUM.
evaluateLua()
template<typename TDomain , typename TAlgebra > std::vector<number> ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::evaluateLua (const std::vector< number > & pos, SmartPtr< TGridFunction > u, number time, bool interpolateOverNeighbouringTriangles) inline
evaluateOnThisProcess()
template<typename TDomain , typename TAlgebra > bool ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::evaluateOnThisProcess (const std::vector< number > & pos, std::vector< number > & result, SmartPtr< TGridFunction > u, number time) inline private
References ug::CollectCornerCoordinates(), dim, ug::FindContainingElement(), ug::GetLocalVector(), ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::LocalVector::resize(), UG_CATCH_THROW, and ug::VecSet().
evaluateOnThisProcessNeighbouring()
template<typename TDomain , typename TAlgebra > bool ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::evaluateOnThisProcessNeighbouring (const std::vector< number > & pos, std::vector< number > & result, SmartPtr< TGridFunction > u, number time) inline private
References ug::CollectCornerCoordinates(), ug::DimReferenceElement< d >::corners(), dim, ug::FindContainingElement(), SmartPtr< T, FreePolicy >::get(), ug::GetLocalVector(), ug::LocalVector::resize(), ug::MathVector< N, T >::size(), and UG_CATCH_THROW.
initialize()
template<typename TDomain , typename TAlgebra > void ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::initialize (SmartPtr< TGridFunction > u) inline private
References make_sp().
Member Data Documentation
dim
template<typename TDomain , typename TAlgebra > const int ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::dim = TDomain::dim static private
m_initialized
template<typename TDomain , typename TAlgebra > bool ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::m_initialized = false private
m_tree
template<typename TDomain , typename TAlgebra > SmartPtr<tree_t> ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::m_tree private
m_userData
template<typename TDomain , typename TAlgebra > SmartPtr<UserData<MathVector<dim>, dim> > ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::m_userData private
The documentation for this class was generated from the following file:
ugbase/bridge/disc_bridges/evaluate_at_position_bridge.cpp