ug4: ug::attachment_traits< Volume *, ElementStorage< Volume > > Class Reference
ug::attachment_traits< Volume *, ElementStorage< Volume > > Class Reference
#include <element_storage.h>
Public Types
typedef const ElementStorage< Volume > * ConstElemHandlerPtr
typedef const Volume * ConstElemPtr
typedef ElementStorage< Volume >::SectionContainer::iterator element_iterator
typedef ElementStorage< Volume > * ElemHandlerPtr
typedef Volume * ElemPtr
typedef Volume *& ElemRef
Static Public Member Functions
static element_iterator elements_begin (ElemHandlerPtr pHandler)
static element_iterator elements_end (ElemHandlerPtr pHandler)
static uint get_data_index (ConstElemHandlerPtr pHandler, ConstElemPtr elem)
static void set_data_index (ElemHandlerPtr pHandler, ElemPtr elem, uint index)
Member Typedef Documentation
ConstElemHandlerPtr
typedef const ElementStorage<Volume>* ug::attachment_traits< Volume *, ElementStorage< Volume > >::ConstElemHandlerPtr
ConstElemPtr
typedef const Volume* ug::attachment_traits< Volume *, ElementStorage< Volume > >::ConstElemPtr
element_iterator
typedef ElementStorage<Volume>::SectionContainer::iterator ug::attachment_traits< Volume *, ElementStorage< Volume > >::element_iterator
ElemHandlerPtr
typedef ElementStorage<Volume>* ug::attachment_traits< Volume *, ElementStorage< Volume > >::ElemHandlerPtr
ElemPtr
typedef Volume* ug::attachment_traits< Volume *, ElementStorage< Volume > >::ElemPtr
ElemRef
typedef Volume*& ug::attachment_traits< Volume *, ElementStorage< Volume > >::ElemRef
Member Function Documentation
elements_begin()
static element_iterator ug::attachment_traits< Volume *, ElementStorage< Volume > >::elements_begin (ElemHandlerPtr pHandler) inline static
References ug::SectionContainer< TValue, TContainer >::begin(), and ug::ElementStorage< TElem >::m_sectionContainer.
elements_end()
static element_iterator ug::attachment_traits< Volume *, ElementStorage< Volume > >::elements_end (ElemHandlerPtr pHandler) inline static
References ug::SectionContainer< TValue, TContainer >::end(), and ug::ElementStorage< TElem >::m_sectionContainer.
get_data_index()
static uint ug::attachment_traits< Volume *, ElementStorage< Volume > >::get_data_index (ConstElemHandlerPtr pHandler, ConstElemPtr elem) inline static
References ug::GridObject::grid_data_index().
set_data_index()
static void ug::attachment_traits< Volume *, ElementStorage< Volume > >::set_data_index (ElemHandlerPtr pHandler, ElemPtr elem, uint index) inline static
References ug::GridObject::set_grid_data_index().
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/element_storage.h