ug4: ug::SectionContainer< TValue, TContainer > Class Template Reference
ug::SectionContainer< TValue, TContainer > Class Template Reference
ugbase » Common » Common Utilities
A container that is divided into different sections.
#include <section_container.h>
Classes
struct Section
Public Types
typedef Container::const_iterator const_iterator
typedef TContainer Container
typedef Container::iterator iterator
typedef TValue value_type
Public Member Functions
void append (const SectionContainer &c)
appends the elements of the given container to the current one
value_type & back (int secIndex=-1)
returns the last entry in the given section.
iterator begin ()
const_iterator begin () const
void clear ()
void clear_section (int sectionIndex)
iterator end ()
const_iterator end () const
void erase (const iterator &iter, int sectionIndex)
value_type & front (int secIndex=-1)
returns the first entry in the given section.
Container & get_container ()
returns the container for raw access.
iterator insert (const TValue &val, int sectionIndex)
uint num_elements (int sectionIndex) const
uint num_elements () const
int num_sections () const
iterator section_begin (int sectionIndex)
const_iterator section_begin (int sectionIndex) const
iterator section_end (int sectionIndex)
const_iterator section_end (int sectionIndex) const
SectionContainer ()
void transfer_elements (SectionContainer &c)
takes all elements from the given section container and transfers them to this one.
Protected Types
typedef std::vector< Section > SectionVec
Protected Member Functions
void add_sections (int num)
Protected Attributes
Container m_container
uint m_numElements
SectionVec m_vSections
Detailed Description
template<class TValue, class TContainer>
class ug::SectionContainer< TValue, TContainer >
A container that is divided into different sections.
This container can be used to store values that have a common base, but can be sorted in different sections. The SectionContainer supplies you with interfaces to iterate over a certain section or to iterate over the complete container. The SectionContainer works on containers of the standard template library. Be sure, that TContainer holds values of type TValue. TContainer has to support the container operations of a std::list.
Member Typedef Documentation
template<class TValue, class TContainer> typedef Container::const_iterator ug::SectionContainer< TValue, TContainer >::const_iterator
template<class TValue, class TContainer> typedef TContainer ug::SectionContainer< TValue, TContainer >::Container
template<class TValue, class TContainer> typedef Container::iterator ug::SectionContainer< TValue, TContainer >::iterator
template<class TValue, class TContainer> typedef std::vector<Section> ug::SectionContainer< TValue, TContainer >::SectionVec protected
template<class TValue, class TContainer> typedef TValue ug::SectionContainer< TValue, TContainer >::value_type
Constructor & Destructor Documentation
template<class TValue , class TContainer > ug::SectionContainer< TValue, TContainer >::SectionContainer ()
References ug::SectionContainer< TValue, TContainer >::clear().
Member Function Documentation
template<class TValue , class TContainer > void ug::SectionContainer< TValue, TContainer >::add_sections (int num) protected
References ug::SectionContainer< TValue, TContainer >::m_container, ug::SectionContainer< TValue, TContainer >::m_vSections, and ug::SectionContainer< TValue, TContainer >::num_elements().
Referenced by ug::SectionContainer< TValue, TContainer >::back(), ug::SectionContainer< ug::Face *, AttachedElementList >::get_container(), and ug::SectionContainer< TValue, TContainer >::insert().
template<class TValue , class TContainer > void ug::SectionContainer< TValue, TContainer >::append (const SectionContainer< TValue, TContainer > & c)
appends the elements of the given container to the current one
Note that the append operation is performed for each section separately.
Warning
This method should not be used if the underlying container and the given one operate on the same AttachedElemList. Otherwise severe side effect will occur! Use transfer_elements instead!
References ug::SectionContainer< TValue, TContainer >::insert(), ug::SectionContainer< TValue, TContainer >::num_sections(), ug::SectionContainer< TValue, TContainer >::section_begin(), ug::SectionContainer< TValue, TContainer >::section_end(), and ug::SectionContainer< TValue, TContainer >::transfer_elements().
Referenced by ug::SectionContainer< TValue, TContainer >::erase(), ug::SectionContainer< ug::Face *, AttachedElementList >::get_container(), and ug::MultiGridSubsetHandler::join_subset_lists().
template<class TValue , class TContainer > SectionContainer< TValue, TContainer >::value_type & ug::SectionContainer< TValue, TContainer >::back (int secIndex = -1)
returns the last entry in the given section.
use index -1 to get the last entry of the complete chain. Make sure to only call this method if there are elements in the given section at all.
References ug::SectionContainer< TValue, TContainer >::add_sections(), ug::SectionContainer< TValue, TContainer >::m_container, ug::SectionContainer< TValue, TContainer >::m_vSections, and ug::SectionContainer< TValue, TContainer >::num_sections().
Referenced by ug::SectionContainer< ug::Face *, AttachedElementList >::end(), and ug::SectionContainer< TValue, TContainer >::front().
template<class TValue, class TContainer> iterator ug::SectionContainer< TValue, TContainer >::begin () inline
Referenced by ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::elements_begin(), ug::attachment_traits< Edge *, ElementStorage< Edge > >::elements_begin(), ug::attachment_traits< Face *, ElementStorage< Face > >::elements_begin(), and ug::attachment_traits< Volume *, ElementStorage< Volume > >::elements_begin().
template<class TValue, class TContainer> const_iterator ug::SectionContainer< TValue, TContainer >::begin () const inline
template<class TValue , class TContainer > void ug::SectionContainer< TValue, TContainer >::clear ()
References ug::SectionContainer< TValue, TContainer >::clear_section(), ug::SectionContainer< TValue, TContainer >::m_container, ug::SectionContainer< TValue, TContainer >::Section::m_elemsBegin, ug::SectionContainer< TValue, TContainer >::Section::m_elemsEnd, ug::SectionContainer< TValue, TContainer >::Section::m_numElements, ug::SectionContainer< TValue, TContainer >::m_numElements, and ug::SectionContainer< TValue, TContainer >::m_vSections.
Referenced by ug::SectionContainer< TValue, TContainer >::SectionContainer().
template<class TValue , class TContainer > void ug::SectionContainer< TValue, TContainer >::clear_section (int sectionIndex)
References ug::SectionContainer< TValue, TContainer >::m_container, ug::SectionContainer< TValue, TContainer >::m_numElements, ug::SectionContainer< TValue, TContainer >::m_vSections, ug::SectionContainer< TValue, TContainer >::num_sections(), ug::SectionContainer< TValue, TContainer >::section_begin(), and ug::SectionContainer< TValue, TContainer >::section_end().
Referenced by ug::SectionContainer< TValue, TContainer >::clear().
template<class TValue, class TContainer> iterator ug::SectionContainer< TValue, TContainer >::end () inline
Referenced by ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::elements_end(), ug::attachment_traits< Edge *, ElementStorage< Edge > >::elements_end(), ug::attachment_traits< Face *, ElementStorage< Face > >::elements_end(), and ug::attachment_traits< Volume *, ElementStorage< Volume > >::elements_end().
template<class TValue, class TContainer> const_iterator ug::SectionContainer< TValue, TContainer >::end () const inline
template<class TValue, class TContainer> void ug::SectionContainer< TValue, TContainer >::erase (const iterator & iter, int sectionIndex)
References ug::SectionContainer< TValue, TContainer >::append(), ug::SectionContainer< TValue, TContainer >::m_container, ug::SectionContainer< TValue, TContainer >::m_numElements, ug::SectionContainer< TValue, TContainer >::m_vSections, ug::SectionContainer< TValue, TContainer >::num_elements(), and ug::SectionContainer< TValue, TContainer >::num_sections().
Referenced by ug::GridSubsetHandler::clear_subset_elements(), ug::MultiGridSubsetHandler::clear_subset_elements(), ug::SectionContainer< TValue, TContainer >::insert(), and ug::SectionContainer< TValue, TContainer >::transfer_elements().
template<class TValue , class TContainer > SectionContainer< TValue, TContainer >::value_type & ug::SectionContainer< TValue, TContainer >::front (int secIndex = -1)
returns the first entry in the given section.
use index -1 to get the first entry of the complete chain. Make sure to only call this method if there are elements in the given section at all.
References ug::SectionContainer< TValue, TContainer >::back(), ug::SectionContainer< TValue, TContainer >::m_container, ug::SectionContainer< TValue, TContainer >::m_vSections, and ug::SectionContainer< TValue, TContainer >::num_sections().
Referenced by ug::SectionContainer< ug::Face *, AttachedElementList >::end(), and ug::SectionContainer< TValue, TContainer >::section_end().
template<class TValue, class TContainer> Container& ug::SectionContainer< TValue, TContainer >::get_container () inline
returns the container for raw access.
Use this method with extreme care. Changes to the elements and to the layout of the container may most likely result in a corruption of the SectionContainer.
Referenced by ug::MGSelector::add_level(), ug::GridSubsetHandler::add_required_subset_lists(), ug::MGSelector::disable_element_support(), ug::ElementStorage< Edge >::ElementStorage(), ug::MGSelector::enable_element_support(), ug::MultiGridSubsetHandler::new_subset(), and ug::ElementStorage< Edge >::~ElementStorage().
template<class TValue, class TContainer > SectionContainer< TValue, TContainer >::iterator ug::SectionContainer< TValue, TContainer >::insert (const TValue & val, int sectionIndex)
References ug::SectionContainer< TValue, TContainer >::add_sections(), ug::SectionContainer< TValue, TContainer >::erase(), ug::SectionContainer< TValue, TContainer >::m_container, ug::SectionContainer< TValue, TContainer >::m_numElements, ug::SectionContainer< TValue, TContainer >::m_vSections, ug::SectionContainer< TValue, TContainer >::num_elements(), and ug::SectionContainer< TValue, TContainer >::num_sections().
Referenced by ug::SectionContainer< TValue, TContainer >::append(), ug::SectionContainer< TValue, TContainer >::num_elements(), and ug::SectionContainer< TValue, TContainer >::transfer_elements().
template<class TValue , class TContainer > uint ug::SectionContainer< TValue, TContainer >::num_elements (int sectionIndex) const
References ug::SectionContainer< TValue, TContainer >::insert(), ug::SectionContainer< TValue, TContainer >::m_vSections, and ug::SectionContainer< TValue, TContainer >::num_sections().
template<class TValue, class TContainer> uint ug::SectionContainer< TValue, TContainer >::num_elements () const inline
Referenced by ug::SectionContainer< TValue, TContainer >::add_sections(), ug::SectionContainer< ug::Face *, AttachedElementList >::end(), ug::SectionContainer< TValue, TContainer >::erase(), and ug::SectionContainer< TValue, TContainer >::insert().
template<class TValue, class TContainer> int ug::SectionContainer< TValue, TContainer >::num_sections () const inline
Referenced by ug::SectionContainer< TValue, TContainer >::append(), ug::SectionContainer< TValue, TContainer >::back(), ug::SectionContainer< TValue, TContainer >::clear_section(), ug::SectionContainer< TValue, TContainer >::erase(), ug::SectionContainer< TValue, TContainer >::front(), ug::SectionContainer< TValue, TContainer >::insert(), ug::SectionContainer< TValue, TContainer >::num_elements(), ug::SectionContainer< TValue, TContainer >::section_begin(), ug::SectionContainer< TValue, TContainer >::section_end(), and ug::SectionContainer< TValue, TContainer >::transfer_elements().
template<class TValue , class TContainer > SectionContainer< TValue, TContainer >::iterator ug::SectionContainer< TValue, TContainer >::section_begin (int sectionIndex)
if the section is empty section_begin and section_end return the same iterators. However, no assumptions on the positions of these iterators should be made.
References ug::SectionContainer< TValue, TContainer >::m_container, ug::SectionContainer< TValue, TContainer >::m_vSections, and ug::SectionContainer< TValue, TContainer >::num_sections().
Referenced by ug::SectionContainer< TValue, TContainer >::append(), ug::SectionContainer< TValue, TContainer >::clear_section(), ug::SectionContainer< ug::Face *, AttachedElementList >::end(), and ug::SectionContainer< TValue, TContainer >::transfer_elements().
template<class TValue , class TContainer > SectionContainer< TValue, TContainer >::const_iterator ug::SectionContainer< TValue, TContainer >::section_begin (int sectionIndex) const
References ug::SectionContainer< TValue, TContainer >::m_container, ug::SectionContainer< TValue, TContainer >::m_vSections, ug::SectionContainer< TValue, TContainer >::num_sections(), and ug::SectionContainer< TValue, TContainer >::section_end().
template<class TValue , class TContainer > SectionContainer< TValue, TContainer >::iterator ug::SectionContainer< TValue, TContainer >::section_end (int sectionIndex)
if the section is empty section_begin and section_end return the same iterators. However, no assumptions on the positions of these iterators should be made.
References ug::SectionContainer< TValue, TContainer >::m_container, ug::SectionContainer< TValue, TContainer >::m_vSections, and ug::SectionContainer< TValue, TContainer >::num_sections().
Referenced by ug::SectionContainer< TValue, TContainer >::append(), ug::SectionContainer< TValue, TContainer >::clear_section(), ug::SectionContainer< ug::Face *, AttachedElementList >::end(), ug::SectionContainer< TValue, TContainer >::section_begin(), and ug::SectionContainer< TValue, TContainer >::transfer_elements().
template<class TValue , class TContainer > SectionContainer< TValue, TContainer >::const_iterator ug::SectionContainer< TValue, TContainer >::section_end (int sectionIndex) const
References ug::SectionContainer< TValue, TContainer >::front(), ug::SectionContainer< TValue, TContainer >::m_container, ug::SectionContainer< TValue, TContainer >::m_vSections, and ug::SectionContainer< TValue, TContainer >::num_sections().
template<class TValue , class TContainer > void ug::SectionContainer< TValue, TContainer >::transfer_elements (SectionContainer< TValue, TContainer > & c)
takes all elements from the given section container and transfers them to this one.
References ug::SectionContainer< TValue, TContainer >::erase(), ug::SectionContainer< TValue, TContainer >::insert(), ug::SectionContainer< TValue, TContainer >::num_sections(), ug::SectionContainer< TValue, TContainer >::section_begin(), and ug::SectionContainer< TValue, TContainer >::section_end().
Referenced by ug::SectionContainer< TValue, TContainer >::append(), ug::SectionContainer< ug::Face *, AttachedElementList >::get_container(), and ug::GridSubsetHandler::join_subset_lists().
Member Data Documentation
template<class TValue, class TContainer> Container ug::SectionContainer< TValue, TContainer >::m_container protected
Referenced by ug::SectionContainer< TValue, TContainer >::add_sections(), ug::SectionContainer< TValue, TContainer >::back(), ug::SectionContainer< ug::Face *, AttachedElementList >::begin(), ug::SectionContainer< TValue, TContainer >::clear(), ug::SectionContainer< TValue, TContainer >::clear_section(), ug::SectionContainer< ug::Face *, AttachedElementList >::end(), ug::SectionContainer< TValue, TContainer >::erase(), ug::SectionContainer< TValue, TContainer >::front(), ug::SectionContainer< ug::Face *, AttachedElementList >::get_container(), ug::SectionContainer< TValue, TContainer >::insert(), ug::SectionContainer< TValue, TContainer >::section_begin(), and ug::SectionContainer< TValue, TContainer >::section_end().
template<class TValue, class TContainer> uint ug::SectionContainer< TValue, TContainer >::m_numElements protected
Referenced by ug::SectionContainer< TValue, TContainer >::clear(), ug::SectionContainer< TValue, TContainer >::clear_section(), ug::SectionContainer< TValue, TContainer >::erase(), ug::SectionContainer< TValue, TContainer >::insert(), and ug::SectionContainer< ug::Face *, AttachedElementList >::num_elements().
template<class TValue, class TContainer> SectionVec ug::SectionContainer< TValue, TContainer >::m_vSections protected
Referenced by ug::SectionContainer< TValue, TContainer >::add_sections(), ug::SectionContainer< TValue, TContainer >::back(), ug::SectionContainer< TValue, TContainer >::clear(), ug::SectionContainer< TValue, TContainer >::clear_section(), ug::SectionContainer< TValue, TContainer >::erase(), ug::SectionContainer< TValue, TContainer >::front(), ug::SectionContainer< TValue, TContainer >::insert(), ug::SectionContainer< TValue, TContainer >::num_elements(), ug::SectionContainer< ug::Face *, AttachedElementList >::num_sections(), ug::SectionContainer< TValue, TContainer >::section_begin(), and ug::SectionContainer< TValue, TContainer >::section_end().
The documentation for this class was generated from the following files:
ugbase/common/util/section_container.h
ugbase/common/util/section_container.hpp