ug4: ug::ComPol_Selection< TLayout > Class Template Reference
ug::ComPol_Selection< TLayout > Class Template Reference
#include <compol_selection.h>
Public Types
typedef Layout::Element Element
typedef Layout::Type GeomObj
typedef Layout::Interface Interface
typedef Interface::const_iterator InterfaceIter
typedef TLayout Layout
Public Types inherited from pcl::ICommunicationPolicy< TLayout >
typedef Layout::Interface Interface
typedef TLayout Layout
Public Member Functions
virtual bool collect (ug::BinaryBuffer &buff, const Interface &interface)
writes 1 for selected and 0 for unselected interface entries
ComPol_Selection (ISelector &sel, bool select=true, bool deselect=true)
Construct the communication policy with a ug::Selector.
virtual bool extract (ug::BinaryBuffer &buff, const Interface &interface)
reads marks from the given stream
virtual int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
Public Member Functions inherited from pcl::ICommunicationPolicy< TLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual ~ICommunicationPolicy ()
Protected Member Functions
bool deselect_allowed ()
bool select_allowed ()
Protected Attributes
bool m_bDeselectAllowed
bool m_bSelectAllowed
ISelector & m_sel
Member Typedef Documentation
Element
template<class TLayout> typedef Layout::Element ug::ComPol_Selection< TLayout >::Element
GeomObj
template<class TLayout> typedef Layout::Type ug::ComPol_Selection< TLayout >::GeomObj
Interface
template<class TLayout> typedef Layout::Interface ug::ComPol_Selection< TLayout >::Interface
InterfaceIter
template<class TLayout> typedef Interface::const_iterator ug::ComPol_Selection< TLayout >::InterfaceIter
Layout
template<class TLayout> typedef TLayout ug::ComPol_Selection< TLayout >::Layout
Constructor & Destructor Documentation
ComPol_Selection()
template<class TLayout> ug::ComPol_Selection< TLayout >::ComPol_Selection (ISelector & sel, bool select = true, bool deselect = true) inline
Construct the communication policy with a ug::Selector.
Through the parameters select and deselect one may specify whether a process selects and/or deselects elements based on the received selection status.
Member Function Documentation
collect()
template<class TLayout> virtual bool ug::ComPol_Selection< TLayout >::collect (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
writes 1 for selected and 0 for unselected interface entries
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::ISelector::get_selection_status(), ug::ComPol_Selection< TLayout >::m_sel, and ug::BinaryBuffer::write().
deselect_allowed()
template<class TLayout> bool ug::ComPol_Selection< TLayout >::deselect_allowed () inline protected
References ug::ComPol_Selection< TLayout >::m_bDeselectAllowed.
Referenced by ug::ComPol_Selection< TLayout >::extract().
extract()
template<class TLayout> virtual bool ug::ComPol_Selection< TLayout >::extract (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
reads marks from the given stream
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::ISelector::deselect(), ug::ComPol_Selection< TLayout >::deselect_allowed(), ug::ComPol_Selection< TLayout >::m_sel, ug::BinaryBuffer::read(), ug::ISelector::select(), and ug::ComPol_Selection< TLayout >::select_allowed().
get_required_buffer_size()
template<class TLayout> virtual int ug::ComPol_Selection< TLayout >::get_required_buffer_size (const Interface & interface) inline virtual
returns the size of the buffer in bytes, that will be required for interface-communication.
Determines the size of the buffer on which the extract and receive methods for the given interface will operate. If the buffer-size can't be calculated on both sides (sender and receiver) this method should return -1. This will lead to an additional communication step in which buffer-sizes will be exchanged. If the buffer-size can be calculated on both sides, it makes sense to do so, since this leads to less communication and overall improved performance. The buffer-size has to exactly match the size of required memory. Make sure that you completely fill the buffer during collect(...) and that you read all data during extract(...). The default implementation returns -1.
Reimplemented from pcl::ICommunicationPolicy< TLayout >.
select_allowed()
template<class TLayout> bool ug::ComPol_Selection< TLayout >::select_allowed () inline protected
References ug::ComPol_Selection< TLayout >::m_bSelectAllowed.
Referenced by ug::ComPol_Selection< TLayout >::extract().
Member Data Documentation
m_bDeselectAllowed
template<class TLayout> bool ug::ComPol_Selection< TLayout >::m_bDeselectAllowed protected
Referenced by ug::ComPol_Selection< TLayout >::deselect_allowed().
m_bSelectAllowed
template<class TLayout> bool ug::ComPol_Selection< TLayout >::m_bSelectAllowed protected
Referenced by ug::ComPol_Selection< TLayout >::select_allowed().
m_sel
template<class TLayout> ISelector& ug::ComPol_Selection< TLayout >::m_sel protected
Referenced by ug::ComPol_Selection< TLayout >::collect(), ug::ComPol_EnableSelectionStateBits< TLayout >::collect(), ug::ComPol_Selection< TLayout >::extract(), and ug::ComPol_EnableSelectionStateBits< TLayout >::extract().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/util/compol_selection.h