ug4: ug::AlgebraLayouts Class Reference
ug::AlgebraLayouts Class Reference
Extends the HorizontalAlgebraLayouts by vertical layouts.
#include <algebra_layouts.h>
Public Member Functions
void clear ()
clears the struct
const IndexLayout & vertical_master () const
const IndexLayout & vertical_slave () const
IndexLayout & vertical_master ()
IndexLayout & vertical_slave ()
Public Member Functions inherited from ug::HorizontalAlgebraLayouts
void clear ()
clears the struct
pcl::InterfaceCommunicator< IndexLayout > & comm () const
returns (non-const !!!) communicator
void enable_overlap (bool enable)
HorizontalAlgebraLayouts ()
bool overlap_enabled () const
Tells whether overlap interfaces should be considered.
const pcl::ProcessCommunicator & proc_comm () const
returns process communicator
const IndexLayout & master () const
const IndexLayout & master_overlap () const
const IndexLayout & slave () const
const IndexLayout & slave_overlap () const
IndexLayout & master ()
IndexLayout & master_overlap ()
IndexLayout & slave ()
IndexLayout & slave_overlap ()
pcl::InterfaceCommunicator< IndexLayout > & comm ()
pcl::ProcessCommunicator & proc_comm ()
Protected Attributes
IndexLayout verticalMasterLayout
vertical master index layout
IndexLayout verticalSlaveLayout
vertical slave index layout
Protected Attributes inherited from ug::HorizontalAlgebraLayouts
pcl::InterfaceCommunicator< IndexLayout > communicator
communicator
bool m_overlapEnabled
IndexLayout masterLayout
(horizontal) master index layout
IndexLayout masterOverlapLayout
pcl::ProcessCommunicator processCommunicator
process communicator
IndexLayout slaveLayout
(horizontal) slave index layout
IndexLayout slaveOverlapLayout
Detailed Description
Extends the HorizontalAlgebraLayouts by vertical layouts.
Member Function Documentation
clear()
void ug::AlgebraLayouts::clear () inline
clears the struct
References ug::HorizontalAlgebraLayouts::clear(), pcl::SingleLevelLayout< TInterface >::clear(), verticalMasterLayout, and verticalSlaveLayout.
Referenced by ug::CreateLocalAlgebraLayouts(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver().
vertical_master() [1/2]
IndexLayout& ug::AlgebraLayouts::vertical_master () inline
returns the vertical slave/master index layout
References verticalMasterLayout.
vertical_master() [2/2]
const IndexLayout& ug::AlgebraLayouts::vertical_master () const inline
returns the vertical slave/master index layout
References verticalMasterLayout.
Referenced by ug::GenerateGlobalConsecutiveIndices(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver(), and ug::operator<<().
vertical_slave() [1/2]
IndexLayout& ug::AlgebraLayouts::vertical_slave () inline
returns the vertical slave/master index layout
References verticalSlaveLayout.
vertical_slave() [2/2]
const IndexLayout& ug::AlgebraLayouts::vertical_slave () const inline
returns the vertical slave/master index layout
References verticalSlaveLayout.
Referenced by ug::operator<<().
Member Data Documentation
verticalMasterLayout
IndexLayout ug::AlgebraLayouts::verticalMasterLayout protected
vertical master index layout
Referenced by clear(), and vertical_master().
verticalSlaveLayout
IndexLayout ug::AlgebraLayouts::verticalSlaveLayout protected
vertical slave index layout
Referenced by clear(), and vertical_slave().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/parallelization/algebra_layouts.h