ug4: ug::ComPol_CheckDistributedParentStates< TLayout > Class Template Reference
ug::ComPol_CheckDistributedParentStates< TLayout > Class Template Reference
Public Types
typedef Layout::Element Element
typedef Layout::Type GeomObj
typedef Layout::Interface Interface
typedef Interface::const_iterator InterfaceIter
typedef TLayout Layout
Public Types inherited from pcl::ICommunicationPolicy< TLayout >
typedef Layout::Interface Interface
typedef TLayout Layout
Public Member Functions
virtual bool collect (ug::BinaryBuffer &buff, const Interface &interface)
should write data which is associated with the interface elements to the buffer.
ComPol_CheckDistributedParentStates (MultiGrid &mg)
bool exchange_data ()
virtual bool extract (ug::BinaryBuffer &buff, const Interface &interface)
extract data from the buffer and assigns it to the interface-elements.
virtual int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
virtual ~ComPol_CheckDistributedParentStates ()
Public Member Functions inherited from pcl::ICommunicationPolicy< TLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual ~ICommunicationPolicy ()
Private Attributes
bool m_comparisionFailed
DistributedGridManager * m_dgm
MultiGrid & m_mg
bool m_performMasterCheck
Member Typedef Documentation
Element
template<class TLayout > typedef Layout::Element ug::ComPol_CheckDistributedParentStates< TLayout >::Element
GeomObj
template<class TLayout > typedef Layout::Type ug::ComPol_CheckDistributedParentStates< TLayout >::GeomObj
Interface
template<class TLayout > typedef Layout::Interface ug::ComPol_CheckDistributedParentStates< TLayout >::Interface
InterfaceIter
template<class TLayout > typedef Interface::const_iterator ug::ComPol_CheckDistributedParentStates< TLayout >::InterfaceIter
Layout
template<class TLayout > typedef TLayout ug::ComPol_CheckDistributedParentStates< TLayout >::Layout
Constructor & Destructor Documentation
ComPol_CheckDistributedParentStates()
template<class TLayout > ug::ComPol_CheckDistributedParentStates< TLayout >::ComPol_CheckDistributedParentStates (MultiGrid & mg) inline
~ComPol_CheckDistributedParentStates()
template<class TLayout > virtual ug::ComPol_CheckDistributedParentStates< TLayout >::~ComPol_CheckDistributedParentStates () inline virtual
Member Function Documentation
collect()
template<class TLayout > virtual bool ug::ComPol_CheckDistributedParentStates< TLayout >::collect (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
should write data which is associated with the interface elements to the buffer.
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::Serialize().
exchange_data()
template<class TLayout > bool ug::ComPol_CheckDistributedParentStates< TLayout >::exchange_data () inline
References pcl::InterfaceCommunicator< TLayout >::communicate(), ug::GridLayoutMap::get_layout(), ug::GridLayoutMap::has_layout(), ug::INT_H_MASTER, ug::INT_H_SLAVE, ug::INT_V_MASTER, ug::INT_V_SLAVE, pcl::InterfaceCommunicator< TLayout >::receive_data(), and pcl::InterfaceCommunicator< TLayout >::send_data().
Referenced by ug::CheckDistributedParentTypes().
extract()
template<class TLayout > virtual bool ug::ComPol_CheckDistributedParentStates< TLayout >::extract (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
extract data from the buffer and assigns it to the interface-elements.
If this method is called between calls to begin_layout_extraction and end_layout_extraction, the interface that is passed to this method belongs to the layout.
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::GridObject::base_object_id(), ug::Deserialize(), ug::GetGridObjectCenter(), and UG_LOG.
get_required_buffer_size()
template<class TLayout > virtual int ug::ComPol_CheckDistributedParentStates< TLayout >::get_required_buffer_size (const Interface & interface) inline virtual
returns the size of the buffer in bytes, that will be required for interface-communication.
Determines the size of the buffer on which the extract and receive methods for the given interface will operate. If the buffer-size can't be calculated on both sides (sender and receiver) this method should return -1. This will lead to an additional communication step in which buffer-sizes will be exchanged. If the buffer-size can be calculated on both sides, it makes sense to do so, since this leads to less communication and overall improved performance. The buffer-size has to exactly match the size of required memory. Make sure that you completely fill the buffer during collect(...) and that you read all data during extract(...). The default implementation returns -1.
Reimplemented from pcl::ICommunicationPolicy< TLayout >.
Member Data Documentation
m_comparisionFailed
template<class TLayout > bool ug::ComPol_CheckDistributedParentStates< TLayout >::m_comparisionFailed private
m_dgm
template<class TLayout > DistributedGridManager* ug::ComPol_CheckDistributedParentStates< TLayout >::m_dgm private
m_mg
template<class TLayout > MultiGrid& ug::ComPol_CheckDistributedParentStates< TLayout >::m_mg private
m_performMasterCheck
template<class TLayout > bool ug::ComPol_CheckDistributedParentStates< TLayout >::m_performMasterCheck private
The documentation for this class was generated from the following file:
ugbase/lib_grid/algorithms/debug_util.cpp