ug4: ug::ReferenceElementProvider Class Reference
ug::ReferenceElementProvider Class Reference
Provider for Reference Elements.
#include <reference_element.h>
Static Public Member Functions
template<int dim>
static const DimReferenceElement< dim > & get (ReferenceObjectID roid)
returns a dimension dependent Reference Element
static const ReferenceElement & get (ReferenceObjectID roid)
returns a Reference Element
Private Member Functions
ReferenceElementProvider & operator= (const ReferenceElementProvider &)
ReferenceElementProvider ()
constructor
ReferenceElementProvider (const ReferenceElementProvider &)
Static Private Member Functions
template<int dim>
static bool add_dim_elem (const DimReferenceElement< dim > &elem)
adds a Reference Element
static bool add_elem (const ReferenceElement &elem)
adds a Reference Element
template<int dim>
static const DimReferenceElement< dim > & get_dim_elem (ReferenceObjectID roid)
returns a Reference Element
static const ReferenceElement & get_elem (ReferenceObjectID roid)
returns a Reference Element
template<int dim>
static const DimReferenceElement< dim > ** get_vector ()
returns vector of DimReferenceElement
static ReferenceElementProvider & instance ()
provide instance of singleton
Static Private Attributes
static const ReferenceElement * m_vElem [NUM_REFERENCE_OBJECTS]
vector storing all ReferenceElement
Detailed Description
Provider for Reference Elements.
Constructor & Destructor Documentation
ReferenceElementProvider() [1/2]
ug::ReferenceElementProvider::ReferenceElementProvider () private
constructor
References UG_THROW.
ReferenceElementProvider() [2/2]
ug::ReferenceElementProvider::ReferenceElementProvider (const ReferenceElementProvider &) inline private
Member Function Documentation
add_dim_elem()
template<int dim> bool ug::ReferenceElementProvider::add_dim_elem (const DimReferenceElement< dim > & elem) static private
adds a Reference Element
References ug::NUM_REFERENCE_OBJECTS, ug::ReferenceElement::roid(), and UG_ASSERT.
add_elem()
bool ug::ReferenceElementProvider::add_elem (const ReferenceElement & elem) static private
adds a Reference Element
References ug::NUM_REFERENCE_OBJECTS, ug::ReferenceElement::roid(), and UG_ASSERT.
get() [1/2]
template<int dim> static const DimReferenceElement<dim>& ug::ReferenceElementProvider::get (ReferenceObjectID roid) inline static
returns a dimension dependent Reference Element
References dim, get_dim_elem(), and instance().
Referenced by ug::CommonLocalDoFSet::add(), ug::ObstacleInNormalDir< TDomain, TAlgebra >::adjust_sol_and_cor_elem(), ug::LocalFiniteElementProvider::create_sub_dof_set(), ug::SideAndElemErrEstData< TDomain >::init_quadrature(), ug::LocalDoFSet::num_dof(), and ug::SideNormal().
get() [2/2]
static const ReferenceElement& ug::ReferenceElementProvider::get (ReferenceObjectID roid) inline static
returns a Reference Element
References get_elem(), and instance().
get_dim_elem()
template<int dim> static const DimReferenceElement<dim>& ug::ReferenceElementProvider::get_dim_elem (ReferenceObjectID roid) inline static private
returns a Reference Element
References ug::NUM_REFERENCE_OBJECTS, and UG_ASSERT.
Referenced by get().
get_elem()
const ReferenceElement & ug::ReferenceElementProvider::get_elem (ReferenceObjectID roid) static private
returns a Reference Element
References ug::NUM_REFERENCE_OBJECTS, ug::ReferenceElement::roid(), and UG_ASSERT.
Referenced by get().
get_vector()
template<int dim> static const DimReferenceElement<dim>** ug::ReferenceElementProvider::get_vector () inline static private
returns vector of DimReferenceElement
References ug::NUM_REFERENCE_OBJECTS.
instance()
static ReferenceElementProvider& ug::ReferenceElementProvider::instance () inline static private
provide instance of singleton
Referenced by get().
operator=()
ReferenceElementProvider& ug::ReferenceElementProvider::operator= (const ReferenceElementProvider &) private
Member Data Documentation
m_vElem
const ReferenceElement * ug::ReferenceElementProvider::m_vElem static private
vector storing all ReferenceElement
The documentation for this class was generated from the following files:
ugbase/lib_disc/reference_element/reference_element.h
ugbase/lib_disc/reference_element/reference_element.cpp