ug4: ug::PrimalSubassembledMatrixInverse< TAlgebra > Class Template Reference
ug::PrimalSubassembledMatrixInverse< TAlgebra > Class Template Reference
operator implementation of the inverse of the Schur complement w.r.t. the "Delta unknowns"
#include <feti.h>
Classes
struct StepConv
Public Types
typedef TAlgebra algebra_type
typedef ILinearOperatorInverse< vector_type > base_type
Base type.
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual bool apply (vector_type &u, const vector_type &f)
applies inverse operator, i.e. returns u = A^{-1} f
virtual bool apply_return_defect (vector_type &u, vector_type &f)
applies inverse operator, i.e. returns u = A^{-1} f and returns defect d := f - A*u
void clear_total_itercnt_of_inner_solvers ()
int get_total_itercnt_of_inner_solvers ()
virtual bool init (SmartPtr< ILinearOperator< vector_type > > L)
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
virtual const char * name () const
name of class
PrimalSubassembledMatrixInverse ()
constructor
void print_statistic_of_inner_solver (bool bPrintOnlyAverages)
prints some convergence statistic of inner solvers
void set_coarse_problem_solver (SmartPtr< ILinearOperatorInverse< vector_type > > coarseProblemSolver)
sets the coarse problem solver
void set_feti_layouts (FetiLayouts< algebra_type > &fetiLayouts)
sets the primal layouts
void set_neumann_solver (SmartPtr< ILinearOperatorInverse< vector_type > > neumannSolver)
sets the Neumann solver
void set_statistic_type (std::string type)
sets statistic slot where next iterate should be counted
void set_test_one_to_many_layouts (bool bTest)
set 'm_bTestOneToManyLayouts'
virtual bool supports_parallel () const
returns if parallel solving is supported
virtual ~PrimalSubassembledMatrixInverse ()
Public Member Functions inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
virtual bool apply_update_defect (TAlgebra::vector_type &u, TAlgebra::vector_type &f)
compute new correction c = B*d and update defect d := d - A*c
virtual SmartPtr< ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > > clone ()
clone
virtual std::string config_string () const
returns information about configuration parameters
ConstSmartPtr< IConvergenceCheck< TAlgebra::vector_type > > convergence_check () const
returns the convergence check
SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > convergence_check ()
returns the convergence check
number defect () const
returns the current defect
ILinearOperatorInverse ()
constructor setting convergence check to (100, 1e-12, 1e-12, true)
ILinearOperatorInverse (SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > spConvCheck)
Default constructor.
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)
initializes for the inverse for a linear operator
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)
initializes for the inverse for a linearized operator at linearization point u
SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > linear_operator ()
returns the current Operator this Inverse Operator is initialized for
number reduction () const
returns the current relative reduction
void set_convergence_check (SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > spConvCheck)
set the convergence check
virtual int standard_offset () const
returns the standard offset for output
int step () const
returns the current number of steps
virtual ~ILinearOperatorInverse ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
void set_damp (number factor)
sets the damping to a constant factor
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
DebugWritingObject ()
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Attributes
pcl::ProcessCommunicator m_allToOneProcessComm
bool m_bTestOneToManyLayouts
IndexLayout m_masterAllToOneLayout
std::map< std::string, std::vector< StepConv > > m_mvStepConv
FetiLayouts< algebra_type > * m_pFetiLayouts
matrix_type * m_pMatrix
matrix_type * m_pNeumannMatrix
int m_primalRootProc
matrix_type * m_pRootSchurComplementMatrix
IndexLayout m_slaveAllToOneLayout
SmartPtr< ILinearOperatorInverse< vector_type > > m_spCoarseProblemSolver
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spNeumannOperator
SmartPtr< ILinearOperatorInverse< vector_type > > m_spNeumannSolver
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spRootSchurComplementOp
std::string m_statType
int m_totalIterCntOfInnerSolvers
Protected Attributes inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > m_spConvCheck
smart pointer holding the convergence check
SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > m_spLinearOperator
Operator that is inverted by this Inverse Operator.
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Additional Inherited Members
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
virtual void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void write_debug (const vector_type &vec, std::string filename)
virtual void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
Detailed Description
template<typename TAlgebra>
class ug::PrimalSubassembledMatrixInverse< TAlgebra >
operator implementation of the inverse of the Schur complement w.r.t. the "Delta unknowns"
This operator provides the application of the inverse of the Schur complement w.r.t. the "Delta unknowns", \({\tilde{S}_{\Delta \Delta}}^{-1}\).
Member Typedef Documentation
template<typename TAlgebra> typedef TAlgebra ug::PrimalSubassembledMatrixInverse< TAlgebra >::algebra_type
template<typename TAlgebra> typedef ILinearOperatorInverse<vector_type> ug::PrimalSubassembledMatrixInverse< TAlgebra >::base_type
Base type.
template<typename TAlgebra> typedef TAlgebra::matrix_type ug::PrimalSubassembledMatrixInverse< TAlgebra >::matrix_type
template<typename TAlgebra> typedef TAlgebra::vector_type ug::PrimalSubassembledMatrixInverse< TAlgebra >::vector_type
Constructor & Destructor Documentation
template<typename TAlgebra > ug::PrimalSubassembledMatrixInverse< TAlgebra >::PrimalSubassembledMatrixInverse ()
constructor
References ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
Referenced by ug::LocalSchurComplement< TAlgebra >::print_statistic_of_inner_solver().
template<typename TAlgebra> virtual ug::PrimalSubassembledMatrixInverse< TAlgebra >::~PrimalSubassembledMatrixInverse () inline virtual
Member Function Documentation
template<typename TAlgebra > bool ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply (vector_type & u, const vector_type & f) virtual
applies inverse operator, i.e. returns u = A^{-1} f
This method applies the inverse operator, i.e. u = A^{-1} f. The domain function f remains unchanged. Note, that this method can always be implemented by creating a copy of f and calling apply_return_defect with this copy.
Parameters
[in] f right-hand side
[out] u solution
Returns
bool success flag
Implements ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
References ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), FETI_PROFILE_FUNC, and ug::PrimalSubassembledMatrixInverse< TAlgebra >::print_statistic_of_inner_solver().
Referenced by ug::FETISolver< TAlgebra >::apply_F(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), ug::FETISolver< TAlgebra >::apply_return_defect(), and ug::FETISolver< TAlgebra >::compute_d().
template<typename TAlgebra > bool ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect (vector_type & u, vector_type & f) virtual
applies inverse operator, i.e. returns u = A^{-1} f and returns defect d := f - A*u
This method applies the inverse operator, i.e. u = A^{-1} f. The domain function f is changed in the way, that the defect d := f - A*u is returned in the function. This is always useful, when the inverting algorithm can (or must) update the defect during computation (this is e.g. the case for the geometric multigrid method). Note, that this method can always be implemented by calling apply and then computing d := f - A*u.
Parameters
[in,out] f right-hand side
[out] u solution
Returns
bool success flag
Implements ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
References pcl::AllProcsTrue(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply(), FETI_PROFILE_BEGIN, FETI_PROFILE_END, ug::PrimalSubassembledMatrixInverse< TAlgebra >::StepConv::lastDef2a, ug::PrimalSubassembledMatrixInverse< TAlgebra >::StepConv::lastDef7, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_masterAllToOneLayout, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_mvStepConv, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pFetiLayouts, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pMatrix, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pNeumannMatrix, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_primalRootProc, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pRootSchurComplementMatrix, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_slaveAllToOneLayout, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spCoarseProblemSolver, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spNeumannSolver, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spRootSchurComplementOp, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_statType, ug::PrimalSubassembledMatrixInverse< TAlgebra >::StepConv::numIter2a, ug::PrimalSubassembledMatrixInverse< TAlgebra >::StepConv::numIter7, pcl::ProcRank(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, UG_LOG, UG_LOG_ALL_PROCS, ug::FetiLayouts< TAlgebra >::vec_scale_add_on_primal(), ug::FetiLayouts< TAlgebra >::vec_scale_assign_on_primal(), ug::FetiLayouts< TAlgebra >::vec_set_on_primal(), ug::FetiLayouts< TAlgebra >::vec_use_intra_sd_communication(), ug::VecBroadcast(), and ug::VecGather().
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> void ug::PrimalSubassembledMatrixInverse< TAlgebra >::clear_total_itercnt_of_inner_solvers () inline
template<typename TAlgebra> int ug::PrimalSubassembledMatrixInverse< TAlgebra >::get_total_itercnt_of_inner_solvers () inline
template<typename TAlgebra > bool ug::PrimalSubassembledMatrixInverse< TAlgebra >::init (SmartPtr< ILinearOperator< vector_type > > L) virtual
References pcl::ProcessCommunicator::allgatherv(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), ug::BlockRef(), ug::BuildOneToManyLayout(), pcl::CollectUniqueElements(), ug::DebugWritingObject< TAlgebra >::debug_writer(), FETI_PROFILE_BEGIN, FETI_PROFILE_END, pcl::ProcessCommunicator::gatherv(), ug::FetiLayouts< TAlgebra >::get_intra_sd_process_communicator(), ug::FetiLayouts< TAlgebra >::get_primal_master_layout(), ug::FetiLayouts< TAlgebra >::get_primal_slave_layout(), pcl::ProcessCommunicator::get_proc_id(), ug::GetCols(), ug::PrimalConnection< TValue >::ind1, ug::PrimalConnection< TValue >::ind2, ug::PrimalSubassembledMatrixInverse< TAlgebra >::StepConv::lastDefSC, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_allToOneProcessComm, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_bTestOneToManyLayouts, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_masterAllToOneLayout, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_mvStepConv, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pFetiLayouts, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pMatrix, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pNeumannMatrix, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_primalRootProc, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pRootSchurComplementMatrix, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_slaveAllToOneLayout, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spCoarseProblemSolver, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spNeumannOperator, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spNeumannSolver, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spOperator, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spRootSchurComplementOp, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_statType, ug::FetiLayouts< TAlgebra >::mat_set_dirichlet_on_primal(), ug::FetiLayouts< TAlgebra >::mat_use_intra_sd_communication(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::StepConv::numIterSC, pcl::ProcRank(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, pcl::ProcessCommunicator::size(), SPNULL, pcl::TestLayout(), UG_LOG, UG_LOG_ALL_PROCS, ug::PrimalConnection< TValue >::value, ug::FetiLayouts< TAlgebra >::vec_scale_add_on_primal(), ug::FetiLayouts< TAlgebra >::vec_set_on_primal(), ug::FetiLayouts< TAlgebra >::vec_use_intra_sd_communication(), ug::DebugWritingObject< TAlgebra >::write_debug(), and ug::AlgebraDebugWriter< TAlgebra >::write_matrix().
Referenced by ug::FETISolver< TAlgebra >::init(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::PrimalSubassembledMatrixInverse().
template<typename TAlgebra> virtual bool ug::PrimalSubassembledMatrixInverse< TAlgebra >::init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type & u) inline virtual
template<typename TAlgebra> virtual const char* ug::PrimalSubassembledMatrixInverse< TAlgebra >::name () const inline virtual
name of class
Implements ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
template<typename TAlgebra > void ug::PrimalSubassembledMatrixInverse< TAlgebra >::print_statistic_of_inner_solver (bool bPrintOnlyAverages)
prints some convergence statistic of inner solvers
References pcl::ProcessCommunicator::allreduce(), ug::FETISolver< TAlgebra >::FETISolver(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_mvStepConv, ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_totalIterCntOfInnerSolvers, pcl::NumProcs(), PCL_DT_DOUBLE, PCL_DT_INT, PCL_RO_MAX, PCL_RO_MIN, PCL_RO_SUM, and UG_LOG.
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply().
template<typename TAlgebra> void ug::PrimalSubassembledMatrixInverse< TAlgebra >::set_coarse_problem_solver (SmartPtr< ILinearOperatorInverse< vector_type > > coarseProblemSolver) inline
sets the coarse problem solver
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra> void ug::PrimalSubassembledMatrixInverse< TAlgebra >::set_feti_layouts (FetiLayouts< algebra_type > & fetiLayouts) inline
sets the primal layouts
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra> void ug::PrimalSubassembledMatrixInverse< TAlgebra >::set_neumann_solver (SmartPtr< ILinearOperatorInverse< vector_type > > neumannSolver) inline
sets the Neumann solver
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra> void ug::PrimalSubassembledMatrixInverse< TAlgebra >::set_statistic_type (std::string type) inline
sets statistic slot where next iterate should be counted
Referenced by ug::FETISolver< TAlgebra >::apply_return_defect(), and ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra> void ug::PrimalSubassembledMatrixInverse< TAlgebra >::set_test_one_to_many_layouts (bool bTest) inline
set 'm_bTestOneToManyLayouts'
template<typename TAlgebra> virtual bool ug::PrimalSubassembledMatrixInverse< TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
Member Data Documentation
template<typename TAlgebra> pcl::ProcessCommunicator ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_allToOneProcessComm protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> bool ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_bTestOneToManyLayouts protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> IndexLayout ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_masterAllToOneLayout protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> std::map<std::string, std::vector<StepConv> > ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_mvStepConv protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::init(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::print_statistic_of_inner_solver().
template<typename TAlgebra> FetiLayouts<algebra_type>* ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pFetiLayouts protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> matrix_type* ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pMatrix protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> matrix_type* ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pNeumannMatrix protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> int ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_primalRootProc protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> matrix_type* ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_pRootSchurComplementMatrix protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> IndexLayout ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_slaveAllToOneLayout protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> SmartPtr<ILinearOperatorInverse<vector_type> > ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spCoarseProblemSolver protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> SmartPtr<MatrixOperator<matrix_type, vector_type> > ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spNeumannOperator protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> SmartPtr<ILinearOperatorInverse<vector_type> > ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spNeumannSolver protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> SmartPtr<MatrixOperator<matrix_type,vector_type> > ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spOperator protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> SmartPtr<MatrixOperator<matrix_type, vector_type> > ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_spRootSchurComplementOp protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> std::string ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_statType protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), and ug::PrimalSubassembledMatrixInverse< TAlgebra >::init().
template<typename TAlgebra> int ug::PrimalSubassembledMatrixInverse< TAlgebra >::m_totalIterCntOfInnerSolvers protected
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::print_statistic_of_inner_solver().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/operator/linear_solver/feti.h
ugbase/lib_algebra/operator/linear_solver/feti.cpp