ug4: ug::ILUTScalarPreconditioner< TAlgebra > Class Template Reference
ug::ILUTScalarPreconditioner< TAlgebra > Class Template Reference
#include <ilut_scalar.h>
Public Types
typedef TAlgebra algebra_type
typedef IPreconditioner< TAlgebra >::matrix_operator_type matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual SmartPtr< ILinearIterator< vector_type > > clone ()
Clone.
virtual std::string config_string () const
ILUTScalarPreconditioner (const ILUTScalarPreconditioner< TAlgebra > &parent)
clone constructor
ILUTScalarPreconditioner (double eps=1e-6)
void preprocess (const matrix_type &M)
void set_info (bool info)
sets storage information output to true or false
void set_show_progress (bool b)
sets the indication of the progress to true or false
void set_sort (bool b)
void set_threshold (number thresh)
sets threshold for incomplete LU factorisation (added 01122010ih)
bool solve (vector_type &c, const vector_type &d)
virtual bool supports_parallel () const
returns if parallel solving is supported
virtual ~ILUTScalarPreconditioner ()
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
returns true if the debug writer is set
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
bool apply_double (vector_type &c, const vector_type &d)
void get_vector (CPUAlgebra::vector_type &v_scalar, const vector_type &v)
virtual const char * name () const
returns the name of iterator
virtual bool postprocess ()
cleans the operator
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
initializes the preconditioner
void set_vector (CPUAlgebra::vector_type &v_scalar, vector_type &v)
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
computes a new correction c = B*d
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
void enter_debug_writer_section (const char *secDir)
enters a debugging section
void enter_debug_writer_section (std::string secDir)
enters a debugging section
void leave_debug_writer_section ()
leaves a debugging section
void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
void write_debug (const matrix_type &mat, std::string name)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
SmartPtr< ILUTPreconditioner< CPUAlgebra > > ilut
LinearSolver< CPUAlgebra::vector_type > linearSolver
bool m_bSort
CPUAlgebra::vector_type m_c
CPUAlgebra::vector_type m_d
double m_eps
bool m_info
bool m_show_progress
size_t m_size
SmartPtr< MatrixOperator< CPUAlgebra::matrix_type, CPUAlgebra::vector_type > > mo
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Private Types
typedef IPreconditioner< TAlgebra > base_type
typedef matrix_type::value_type block_type
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::ILUTScalarPreconditioner< TAlgebra >::algebra_type
base_type
template<typename TAlgebra > typedef IPreconditioner<TAlgebra> ug::ILUTScalarPreconditioner< TAlgebra >::base_type private
block_type
template<typename TAlgebra > typedef matrix_type::value_type ug::ILUTScalarPreconditioner< TAlgebra >::block_type private
matrix_operator_type
template<typename TAlgebra > typedef IPreconditioner<TAlgebra>::matrix_operator_type ug::ILUTScalarPreconditioner< TAlgebra >::matrix_operator_type
Matrix Operator type.
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::ILUTScalarPreconditioner< TAlgebra >::matrix_type
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::ILUTScalarPreconditioner< TAlgebra >::vector_type
Constructor & Destructor Documentation
ILUTScalarPreconditioner() [1/2]
template<typename TAlgebra > ug::ILUTScalarPreconditioner< TAlgebra >::ILUTScalarPreconditioner (double eps = 1e-6) inline
ILUTScalarPreconditioner() [2/2]
template<typename TAlgebra > ug::ILUTScalarPreconditioner< TAlgebra >::ILUTScalarPreconditioner (const ILUTScalarPreconditioner< TAlgebra > & parent) inline
clone constructor
References ug::ILUTScalarPreconditioner< TAlgebra >::m_bSort, ug::ILUTScalarPreconditioner< TAlgebra >::m_eps, ug::ILUTScalarPreconditioner< TAlgebra >::m_info, ug::ILUTScalarPreconditioner< TAlgebra >::m_show_progress, ug::ILUTScalarPreconditioner< TAlgebra >::set_info(), ug::ILUTScalarPreconditioner< TAlgebra >::set_show_progress(), and ug::ILUTScalarPreconditioner< TAlgebra >::set_sort().
~ILUTScalarPreconditioner()
template<typename TAlgebra > virtual ug::ILUTScalarPreconditioner< TAlgebra >::~ILUTScalarPreconditioner () inline virtual
Member Function Documentation
apply_double()
template<typename TAlgebra > bool ug::ILUTScalarPreconditioner< TAlgebra >::apply_double (vector_type & c, const vector_type & d) inline protected
References ug::CreateLocalAlgebraLayouts(), ug::ILUTScalarPreconditioner< TAlgebra >::get_vector(), ug::ILUTScalarPreconditioner< TAlgebra >::ilut, ug::ILUTScalarPreconditioner< TAlgebra >::m_c, ug::ILUTScalarPreconditioner< TAlgebra >::m_d, ug::ILUTScalarPreconditioner< TAlgebra >::m_size, ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::Vector< TValueType >::resize(), ug::ParallelVector< TVector >::set(), ug::ParallelVector< TVector >::set_layouts(), ug::ParallelVector< TVector >::set_storage_type(), and ug::ILUTScalarPreconditioner< TAlgebra >::set_vector().
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::step().
clone()
template<typename TAlgebra > virtual SmartPtr<ILinearIterator<vector_type> > ug::ILUTScalarPreconditioner< TAlgebra >::clone () inline virtual
Clone.
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References make_sp().
config_string()
template<typename TAlgebra > virtual std::string ug::ILUTScalarPreconditioner< TAlgebra >::config_string () const inline virtual
Reimplemented from ug::ILinearIterator< TAlgebra::vector_type >.
References ug::ILUTScalarPreconditioner< TAlgebra >::m_bSort, and ug::ILUTScalarPreconditioner< TAlgebra >::m_eps.
get_vector()
template<typename TAlgebra > void ug::ILUTScalarPreconditioner< TAlgebra >::get_vector (CPUAlgebra::vector_type & v_scalar, const vector_type & v) inline protected
References ug::BlockRef(), and ug::GetSize().
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::apply_double(), and ug::ILUTScalarPreconditioner< TAlgebra >::solve().
name()
template<typename TAlgebra > virtual const char* ug::ILUTScalarPreconditioner< TAlgebra >::name () const inline protected virtual
returns the name of iterator
This method returns the name of the iterator operator. This function is typically needed, when the iterator operator is used inside of another operator and some debug output should be printed
Returns
const char* name of inverse operator
Implements ug::IPreconditioner< TAlgebra >.
postprocess()
template<typename TAlgebra > virtual bool ug::ILUTScalarPreconditioner< TAlgebra >::postprocess () inline protected virtual
cleans the operator
Implements ug::IPreconditioner< TAlgebra >.
preprocess() [1/2]
template<typename TAlgebra > void ug::ILUTScalarPreconditioner< TAlgebra >::preprocess (const matrix_type & M) inline
References pcl::CollectUniqueElements(), ug::CreateLocalAlgebraLayouts(), ug::GetDoubleSparseFromBlockSparse(), ug::ILUTScalarPreconditioner< TAlgebra >::ilut, ug::ILUTScalarPreconditioner< TAlgebra >::linearSolver, ug::ILUTScalarPreconditioner< TAlgebra >::m_bSort, ug::ILUTScalarPreconditioner< TAlgebra >::m_eps, ug::ILUTScalarPreconditioner< TAlgebra >::m_info, ug::ILUTScalarPreconditioner< TAlgebra >::m_show_progress, ug::ILUTScalarPreconditioner< TAlgebra >::m_size, make_sp(), ug::MatAddSlaveRowsToMasterRowOverlap0(), ug::ILUTScalarPreconditioner< TAlgebra >::mo, ug::PST_ADDITIVE, ug::ParallelMatrix< TMatrix >::set_layouts(), ug::ParallelMatrix< TMatrix >::set_storage_type(), ug::SetDirichletRow(), and STATIC_ASSERT.
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::preprocess().
preprocess() [2/2]
template<typename TAlgebra > virtual bool ug::ILUTScalarPreconditioner< TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) inline protected virtual
initializes the preconditioner
This method is used to initialize the preconditioner. Usually, here are performed computationally expensive operations, that should only be computed once for an underlying matrix (e.g. LU factorization), while the preconditioner will by applied (using 'step'-method) several times.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::ILUTScalarPreconditioner< TAlgebra >::preprocess().
set_info()
template<typename TAlgebra > void ug::ILUTScalarPreconditioner< TAlgebra >::set_info (bool info) inline
sets storage information output to true or false
References ug::ILUTScalarPreconditioner< TAlgebra >::m_info.
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::ILUTScalarPreconditioner().
set_show_progress()
template<typename TAlgebra > void ug::ILUTScalarPreconditioner< TAlgebra >::set_show_progress (bool b) inline
sets the indication of the progress to true or false
References ug::ILUTScalarPreconditioner< TAlgebra >::m_show_progress.
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::ILUTScalarPreconditioner().
set_sort()
template<typename TAlgebra > void ug::ILUTScalarPreconditioner< TAlgebra >::set_sort (bool b) inline
References ug::ILUTScalarPreconditioner< TAlgebra >::m_bSort.
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::ILUTScalarPreconditioner().
set_threshold()
template<typename TAlgebra > void ug::ILUTScalarPreconditioner< TAlgebra >::set_threshold (number thresh) inline
sets threshold for incomplete LU factorisation (added 01122010ih)
References ug::ILUTScalarPreconditioner< TAlgebra >::m_eps.
set_vector()
template<typename TAlgebra > void ug::ILUTScalarPreconditioner< TAlgebra >::set_vector (CPUAlgebra::vector_type & v_scalar, vector_type & v) inline protected
References ug::BlockRef(), and ug::GetSize().
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::apply_double(), and ug::ILUTScalarPreconditioner< TAlgebra >::solve().
solve()
template<typename TAlgebra > bool ug::ILUTScalarPreconditioner< TAlgebra >::solve (vector_type & c, const vector_type & d) inline
References ug::CreateLocalAlgebraLayouts(), ug::ILUTScalarPreconditioner< TAlgebra >::get_vector(), ug::ILUTScalarPreconditioner< TAlgebra >::linearSolver, ug::ILUTScalarPreconditioner< TAlgebra >::m_c, ug::ILUTScalarPreconditioner< TAlgebra >::m_d, ug::ILUTScalarPreconditioner< TAlgebra >::m_size, ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::Vector< TValueType >::resize(), ug::ParallelVector< TVector >::set(), ug::ParallelVector< TVector >::set_layouts(), ug::ParallelVector< TVector >::set_storage_type(), and ug::ILUTScalarPreconditioner< TAlgebra >::set_vector().
step()
template<typename TAlgebra > virtual bool ug::ILUTScalarPreconditioner< TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) inline protected virtual
computes a new correction c = B*d
This method computes a new correction c = B*d. It can only be called, when the preprocess has been done.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
[out] c correction
[in] d defect
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::ILUTScalarPreconditioner< TAlgebra >::apply_double(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, and ug::PST_UNIQUE.
supports_parallel()
template<typename TAlgebra > virtual bool ug::ILUTScalarPreconditioner< TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearIterator< TAlgebra::vector_type >.
Member Data Documentation
ilut
template<typename TAlgebra > SmartPtr<ILUTPreconditioner<CPUAlgebra> > ug::ILUTScalarPreconditioner< TAlgebra >::ilut protected
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::apply_double(), and ug::ILUTScalarPreconditioner< TAlgebra >::preprocess().
linearSolver
template<typename TAlgebra > LinearSolver<CPUAlgebra::vector_type> ug::ILUTScalarPreconditioner< TAlgebra >::linearSolver protected
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::preprocess(), and ug::ILUTScalarPreconditioner< TAlgebra >::solve().
m_bSort
template<typename TAlgebra > bool ug::ILUTScalarPreconditioner< TAlgebra >::m_bSort protected
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::config_string(), ug::ILUTScalarPreconditioner< TAlgebra >::ILUTScalarPreconditioner(), ug::ILUTScalarPreconditioner< TAlgebra >::preprocess(), and ug::ILUTScalarPreconditioner< TAlgebra >::set_sort().
m_c
template<typename TAlgebra > CPUAlgebra::vector_type ug::ILUTScalarPreconditioner< TAlgebra >::m_c protected
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::apply_double(), and ug::ILUTScalarPreconditioner< TAlgebra >::solve().
m_d
template<typename TAlgebra > CPUAlgebra::vector_type ug::ILUTScalarPreconditioner< TAlgebra >::m_d protected
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::apply_double(), and ug::ILUTScalarPreconditioner< TAlgebra >::solve().
m_eps
template<typename TAlgebra > double ug::ILUTScalarPreconditioner< TAlgebra >::m_eps protected
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::config_string(), ug::ILUTScalarPreconditioner< TAlgebra >::ILUTScalarPreconditioner(), ug::ILUTScalarPreconditioner< TAlgebra >::preprocess(), and ug::ILUTScalarPreconditioner< TAlgebra >::set_threshold().
m_info
template<typename TAlgebra > bool ug::ILUTScalarPreconditioner< TAlgebra >::m_info protected
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::ILUTScalarPreconditioner(), ug::ILUTScalarPreconditioner< TAlgebra >::preprocess(), and ug::ILUTScalarPreconditioner< TAlgebra >::set_info().
m_show_progress
template<typename TAlgebra > bool ug::ILUTScalarPreconditioner< TAlgebra >::m_show_progress protected
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::ILUTScalarPreconditioner(), ug::ILUTScalarPreconditioner< TAlgebra >::preprocess(), and ug::ILUTScalarPreconditioner< TAlgebra >::set_show_progress().
m_size
template<typename TAlgebra > size_t ug::ILUTScalarPreconditioner< TAlgebra >::m_size protected
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::apply_double(), ug::ILUTScalarPreconditioner< TAlgebra >::preprocess(), and ug::ILUTScalarPreconditioner< TAlgebra >::solve().
mo
template<typename TAlgebra > SmartPtr<MatrixOperator<CPUAlgebra::matrix_type, CPUAlgebra::vector_type> > ug::ILUTScalarPreconditioner< TAlgebra >::mo protected
Referenced by ug::ILUTScalarPreconditioner< TAlgebra >::preprocess().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/preconditioner/ilut_scalar.h