ug4: ug::AbsoluteMarking< TDomain > Class Template Reference
ug::AbsoluteMarking< TDomain > Class Template Reference
marks elements above an absolute threshold (based on S. Reiter's idea)
#include <error_elem_marking_strategy.h>
Public Types
typedef IElementMarkingStrategy< TDomain > base_type
Public Types inherited from ug::IElementMarkingStrategy< TDomain >
typedef Grid::AttachmentAccessor< elem_type, ug::Attachment< number > > elem_accessor_type
typedef domain_traits< dim >::element_type elem_type
element type to be marked
Public Member Functions
AbsoluteMarking (number eta)
Public Member Functions inherited from ug::IElementMarkingStrategy< TDomain >
number global_estimated_error () const
number global_estimated_error_per_elem_max () const
number global_estimated_error_per_elem_min () const
IElementMarkingStrategy ()
void mark (IMultigridElementIndicators< TDomain > &mgElemIndicators, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd)
This function marks all elements.
virtual ~IElementMarkingStrategy ()
Protected Member Functions
void mark (typename base_type::elem_accessor_type &aaError, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd)
DEPRECATED:
Protected Attributes
number m_eta
int m_max_level
Protected Attributes inherited from ug::IElementMarkingStrategy< TDomain >
number m_latest_error
number m_latest_error_per_elem_max
number m_latest_error_per_elem_min
Additional Inherited Members
Static Public Attributes inherited from ug::IElementMarkingStrategy< TDomain >
static const int dim = TDomain::dim
world dimension
Detailed Description
template<typename TDomain>
class ug::AbsoluteMarking< TDomain >
marks elements above an absolute threshold (based on S. Reiter's idea)
Member Typedef Documentation
base_type
template<typename TDomain > typedef IElementMarkingStrategy<TDomain> ug::AbsoluteMarking< TDomain >::base_type
Constructor & Destructor Documentation
AbsoluteMarking()
template<typename TDomain > ug::AbsoluteMarking< TDomain >::AbsoluteMarking (number eta) inline
Member Function Documentation
mark()
template<typename TDomain > void ug::AbsoluteMarking< TDomain >::mark (typename base_type::elem_accessor_type & aaError, IRefiner & refiner, ConstSmartPtr< DoFDistribution > dd) protected virtual
DEPRECATED:
Implements ug::IElementMarkingStrategy< TDomain >.
References pcl::ProcessCommunicator::allreduce(), ug::IRefiner::mark(), pcl::NumProcs(), PCL_RO_SUM, ug::RM_REFINE, and UG_LOG.
Member Data Documentation
m_eta
template<typename TDomain > number ug::AbsoluteMarking< TDomain >::m_eta protected
m_max_level
template<typename TDomain > int ug::AbsoluteMarking< TDomain >::m_max_level protected
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/error_elem_marking_strategy.h