ug4: ug::bridge::ExportedMethodGroup Class Reference
ug::bridge::ExportedMethodGroup Class Reference
ugbase » Bridge » Registry
Groups of methods - useful to realize overloaded methods.
#include <class.h>
Classes
struct Overload
Public Member Functions
template<class TFunc >
bool add_overload (const TFunc &m, ProxyFunc pf, const std::string &className, const std::string &methodOptions, const std::string &retValInfos, const std::string &paramInfos, const std::string &tooltip, const std::string &help)
adds an overload. Returns false if the overload already existed.
ExportedMethodGroup (const std::string &name)
ExportedMethod * get_overload (size_t index)
const ExportedMethod * get_overload (size_t index) const
template<class TType >
ExportedMethod * get_overload_by_type ()
template<class TType >
const ExportedMethod * get_overload_by_type () const
ExportedMethod * get_overload_by_type_id (size_t typeID)
const ExportedMethod * get_overload_by_type_id (size_t typeID) const
size_t get_overload_type_id (size_t index) const
const std::string & name () const
name of function group
size_t num_overloads () const
~ExportedMethodGroup ()
Private Types
typedef ExportedMethod::ProxyFunc ProxyFunc
Private Attributes
std::string m_name
std::vector< Overload > m_overloads
Detailed Description
Groups of methods - useful to realize overloaded methods.
Member Typedef Documentation
ProxyFunc
typedef ExportedMethod::ProxyFunc ug::bridge::ExportedMethodGroup::ProxyFunc private
Constructor & Destructor Documentation
ExportedMethodGroup()
ug::bridge::ExportedMethodGroup::ExportedMethodGroup (const std::string & name) inline
~ExportedMethodGroup()
ug::bridge::ExportedMethodGroup::~ExportedMethodGroup () inline
References m_overloads.
Member Function Documentation
add_overload()
template<class TFunc > bool ug::bridge::ExportedMethodGroup::add_overload (const TFunc & m, ProxyFunc pf, const std::string & className, const std::string & methodOptions, const std::string & retValInfos, const std::string & paramInfos, const std::string & tooltip, const std::string & help) inline
adds an overload. Returns false if the overload already existed.
References func(), get_overload_by_type_id(), m_name, and m_overloads.
Referenced by ug::bridge::ExportedClass< TClass >::add_method().
get_overload() [1/2]
ExportedMethod* ug::bridge::ExportedMethodGroup::get_overload (size_t index) inline
References m_overloads.
Referenced by ug::bridge::lua::ExecuteMethod(), ug::vrl::invocation::getMethodBySignature(), and ug::bridge::lua::LuaProxyMethod().
get_overload() [2/2]
const ExportedMethod* ug::bridge::ExportedMethodGroup::get_overload (size_t index) const inline
References m_overloads.
get_overload_by_type() [1/2]
template<class TType > ExportedMethod* ug::bridge::ExportedMethodGroup::get_overload_by_type () inline
References get_overload_by_type_id().
get_overload_by_type() [2/2]
template<class TType > const ExportedMethod* ug::bridge::ExportedMethodGroup::get_overload_by_type () const inline
References get_overload_by_type_id().
get_overload_by_type_id() [1/2]
ExportedMethod* ug::bridge::ExportedMethodGroup::get_overload_by_type_id (size_t typeID) inline
References m_overloads.
Referenced by add_overload(), and get_overload_by_type().
get_overload_by_type_id() [2/2]
const ExportedMethod* ug::bridge::ExportedMethodGroup::get_overload_by_type_id (size_t typeID) const inline
References m_overloads.
get_overload_type_id()
size_t ug::bridge::ExportedMethodGroup::get_overload_type_id (size_t index) const inline
References m_overloads.
name()
const std::string& ug::bridge::ExportedMethodGroup::name () const inline
name of function group
References m_name.
Referenced by ug::bridge::lua::CreateBindings_LUA(), ug::bridge::lua::ExecuteMethod(), and ug::bridge::lua::LuaProxyMethod().
num_overloads()
size_t ug::bridge::ExportedMethodGroup::num_overloads () const inline
References m_overloads.
Referenced by ug::bridge::lua::ExecuteMethod(), and ug::vrl::invocation::getMethodBySignature().
Member Data Documentation
m_name
std::string ug::bridge::ExportedMethodGroup::m_name private
Referenced by add_overload(), and name().
m_overloads
std::vector<Overload> ug::bridge::ExportedMethodGroup::m_overloads private
Referenced by add_overload(), get_overload(), get_overload_by_type_id(), get_overload_type_id(), num_overloads(), and ~ExportedMethodGroup().
The documentation for this class was generated from the following file:
ugbase/registry/class.h