ug4: ug::OctahedronDescriptor Class Reference
ug::OctahedronDescriptor Class Reference
only used to initialize a octahedron. for all other tasks you should use VolumeDescripor.
#include <grid_objects_3d.h>
Public Member Functions
uint num_vertices () const
OctahedronDescriptor ()
OctahedronDescriptor (const OctahedronDescriptor &td)
OctahedronDescriptor (const VolumeVertices &vv)
OctahedronDescriptor (Vertex *v1, Vertex *v2, Vertex *v3, Vertex *v4, Vertex *v5, Vertex *v6)
Vertex * vertex (size_t index) const
Protected Attributes
Vertex * m_vertex [6]
Detailed Description
only used to initialize a octahedron. for all other tasks you should use VolumeDescripor.
please be sure to pass the vertices in the correct order: v1: bottom-vertex v2, v3, v4, v5: middle-section-vertices in counterclockwise order (if viewed from the top). v6: top-vertex
Constructor & Destructor Documentation
OctahedronDescriptor() [1/4]
ug::OctahedronDescriptor::OctahedronDescriptor () inline
OctahedronDescriptor() [2/4]
ug::OctahedronDescriptor::OctahedronDescriptor (const OctahedronDescriptor & td)
References vertex().
OctahedronDescriptor() [3/4]
ug::OctahedronDescriptor::OctahedronDescriptor (const VolumeVertices & vv)
References ug::VolumeVertices::num_vertices(), and ug::VolumeVertices::vertex().
OctahedronDescriptor() [4/4]
ug::OctahedronDescriptor::OctahedronDescriptor (Vertex * v1, Vertex * v2, Vertex * v3, Vertex * v4, Vertex * v5, Vertex * v6)
Member Function Documentation
num_vertices()
uint ug::OctahedronDescriptor::num_vertices () const inline
vertex()
Vertex* ug::OctahedronDescriptor::vertex (size_t index) const inline
Referenced by ug::Octahedron::Octahedron(), and OctahedronDescriptor().
Member Data Documentation
m_vertex
Vertex* ug::OctahedronDescriptor::m_vertex[6] protected
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid_objects/grid_objects_3d.h
ugbase/lib_grid/grid_objects/grid_objects_3d.cpp