ug4: ug::DomainRayTracer Class Reference
ug::DomainRayTracer Class Reference
TEMPORARY QUICK HACK! DON'T USE! WILL BE REPLACED SOON!
Public Types
typedef vector3 vector_t
Public Member Functions
DomainRayTracer (Domain3d &dom)
void init (const char *subsetNames)
void init (const std::vector< int > &subsetIndices)
size_t num_trace_points () const
void set_small (number small)
const vector_t & trace_point (size_t i) const
number trace_point_x (size_t i) const
number trace_point_y (size_t i) const
number trace_point_z (size_t i) const
size_t trace_ray (const vector_t &from, const vector_t &dir)
Private Types
typedef RayElemIntersectionRecord< Triangle * > intersection_record_t
typedef lg_ntree< 3, 3, Triangle > tree_t
local coordinate regarding trace-ray
Private Attributes
Domain3d * m_dom
std::vector< intersection_record_t > m_intersectionRecords
number m_small
std::vector< vector_t > m_tracePoints
tree_t m_tree
Detailed Description
TEMPORARY QUICK HACK! DON'T USE! WILL BE REPLACED SOON!
Member Typedef Documentation
intersection_record_t
typedef RayElemIntersectionRecord<Triangle*> ug::DomainRayTracer::intersection_record_t private
tree_t
typedef lg_ntree<3, 3, Triangle> ug::DomainRayTracer::tree_t private
local coordinate regarding trace-ray
vector_t
typedef vector3 ug::DomainRayTracer::vector_t
Constructor & Destructor Documentation
DomainRayTracer()
ug::DomainRayTracer::DomainRayTracer (Domain3d & dom) inline
Member Function Documentation
init() [1/2]
void ug::DomainRayTracer::init (const char * subsetNames) inline
References ug::SubsetGroup::add(), ug::SubsetGroup::index_vector(), init(), and ug::TokenizeString().
init() [2/2]
void ug::DomainRayTracer::init (const std::vector< int > & subsetIndices) inline
References ug::MultiGridSubsetHandler::begin(), ug::MultiGridSubsetHandler::end(), ug::MultiGrid::has_children(), and ug::MultiGridSubsetHandler::num_levels().
num_trace_points()
size_t ug::DomainRayTracer::num_trace_points () const inline
set_small()
void ug::DomainRayTracer::set_small (number small) inline
trace_point()
const vector_t& ug::DomainRayTracer::trace_point (size_t i) const inline
trace_point_x()
number ug::DomainRayTracer::trace_point_x (size_t i) const inline
trace_point_y()
number ug::DomainRayTracer::trace_point_y (size_t i) const inline
trace_point_z()
number ug::DomainRayTracer::trace_point_z (size_t i) const inline
trace_ray()
size_t ug::DomainRayTracer::trace_ray (const vector_t & from, const vector_t & dir) inline
References end_for, for_each_in_vec, ug::PointOnRay(), ug::RayElementIntersections(), and ug::RayElemIntersectionRecord< TElem >::smin.
Member Data Documentation
m_dom
Domain3d* ug::DomainRayTracer::m_dom private
m_intersectionRecords
std::vector<intersection_record_t> ug::DomainRayTracer::m_intersectionRecords private
m_small
number ug::DomainRayTracer::m_small private
m_tracePoints
std::vector<vector_t> ug::DomainRayTracer::m_tracePoints private
m_tree
tree_t ug::DomainRayTracer::m_tree private
The documentation for this class was generated from the following file:
ugbase/bridge/domain_bridges/ray_tracing_bridge.cpp