ug4: ug::FracturedMediaRefiner< TGrid, TAPosition > Class Template Reference
ug::FracturedMediaRefiner< TGrid, TAPosition > Class Template Reference
#include <fractured_media_refiner.h>
Public Member Functions
FracturedMediaRefiner (IRefinementCallback *refCallback=NULL)
FracturedMediaRefiner (TGrid &g, IRefinementCallback *refCallback=NULL)
virtual bool mark (Face *f, RefinementMark refMark=RM_REFINE)
Marks a face for refinement.
void set_aspect_ratio_threshold (number threshold)
if the aspect ratio is smaller then the given threshold, the element is considered a fracture element.
void set_position_attachment (TAPosition &aPos)
virtual ~FracturedMediaRefiner ()
Protected Member Functions
number aspect_ratio (Face *f)
virtual void collect_objects_for_refine ()
Private Types
typedef THangingNodeRefiner< TGrid > BaseClass
Private Attributes
Grid::VertexAttachmentAccessor< TAPosition > m_aaPos
number m_aspectRatioThreshold
std::queue< Face * > m_queDegeneratedFaces
Detailed Description
template<class TGrid, class TAPosition>
class ug::FracturedMediaRefiner< TGrid, TAPosition >
This class takes special care for degenerated fractures during refinement. Degenerated faces are refined using anisotropic refinement, so that their degenerated sides are not refined.
Currently this only works in 2d.
Todo:
Add support for degenerated volumes
Use a IsDegenerated callback instead of thresholds
Member Typedef Documentation
template<class TGrid , class TAPosition > typedef THangingNodeRefiner<TGrid> ug::FracturedMediaRefiner< TGrid, TAPosition >::BaseClass private
Constructor & Destructor Documentation
template<class TGrid , class TAPosition > ug::FracturedMediaRefiner< TGrid, TAPosition >::FracturedMediaRefiner (IRefinementCallback * refCallback = NULL)
template<class TGrid , class TAPosition > ug::FracturedMediaRefiner< TGrid, TAPosition >::FracturedMediaRefiner (TGrid & g, IRefinementCallback * refCallback = NULL)
References ug::FracturedMediaRefiner< TGrid, TAPosition >::~FracturedMediaRefiner().
template<class TGrid , class TAPosition > ug::FracturedMediaRefiner< TGrid, TAPosition >::~FracturedMediaRefiner () virtual
References ug::FracturedMediaRefiner< TGrid, TAPosition >::set_aspect_ratio_threshold().
Referenced by ug::FracturedMediaRefiner< TGrid, TAPosition >::FracturedMediaRefiner().
Member Function Documentation
template<class TGrid , class TAPosition > number ug::FracturedMediaRefiner< TGrid, TAPosition >::aspect_ratio (Face * f) protected
References ug::FracturedMediaRefiner< TGrid, TAPosition >::collect_objects_for_refine(), ug::Face::edge_desc(), ug::EdgeLength(), ug::FracturedMediaRefiner< TGrid, TAPosition >::m_aaPos, ug::Face::num_edges(), UG_THROW, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid().
Referenced by ug::FracturedMediaRefiner< TGrid, TAPosition >::collect_objects_for_refine(), and ug::FracturedMediaRefiner< TGrid, TAPosition >::mark().
template<class TGrid , class TAPosition > void ug::FracturedMediaRefiner< TGrid, TAPosition >::collect_objects_for_refine () protected virtual
References ug::FracturedMediaRefiner< TGrid, TAPosition >::aspect_ratio(), ug::CollectAssociated(), ug::EdgeLength(), ug::FracturedMediaRefiner< TGrid, TAPosition >::m_aaPos, ug::FracturedMediaRefiner< TGrid, TAPosition >::m_aspectRatioThreshold, ug::FracturedMediaRefiner< TGrid, TAPosition >::m_queDegeneratedFaces, ug::RM_ANISOTROPIC, ug::RM_NONE, ug::RM_REFINE, ug::SMALL, UG_THROW, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid().
Referenced by ug::FracturedMediaRefiner< TGrid, TAPosition >::aspect_ratio().
template<class TGrid , class TAPosition > bool ug::FracturedMediaRefiner< TGrid, TAPosition >::mark (Face * f, RefinementMark refMark = RM_REFINE) virtual
Marks a face for refinement.
Uses the degenerated-edge-threshold to determine, whether the face is a fracture-face or not. Make sure to specify a position attachment before marking any elements.
References ug::FracturedMediaRefiner< TGrid, TAPosition >::aspect_ratio(), ug::FracturedMediaRefiner< TGrid, TAPosition >::m_aaPos, ug::FracturedMediaRefiner< TGrid, TAPosition >::m_aspectRatioThreshold, ug::FracturedMediaRefiner< TGrid, TAPosition >::m_queDegeneratedFaces, UG_ASSERT, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid().
Referenced by ug::FracturedMediaRefiner< TGrid, TAPosition >::set_position_attachment().
template<class TGrid , class TAPosition > void ug::FracturedMediaRefiner< TGrid, TAPosition >::set_aspect_ratio_threshold (number threshold)
if the aspect ratio is smaller then the given threshold, the element is considered a fracture element.
References ug::FracturedMediaRefiner< TGrid, TAPosition >::m_aspectRatioThreshold, and ug::FracturedMediaRefiner< TGrid, TAPosition >::set_position_attachment().
Referenced by ug::FracturedMediaRefiner< TGrid, TAPosition >::~FracturedMediaRefiner().
template<class TGrid , class TAPosition > void ug::FracturedMediaRefiner< TGrid, TAPosition >::set_position_attachment (TAPosition & aPos)
Todo:
: replace this with a callback
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::FracturedMediaRefiner< TGrid, TAPosition >::m_aaPos, ug::FracturedMediaRefiner< TGrid, TAPosition >::mark(), and UG_ASSERT.
Referenced by ug::FracturedMediaRefiner< TGrid, TAPosition >::set_aspect_ratio_threshold().
Member Data Documentation
template<class TGrid , class TAPosition > Grid::VertexAttachmentAccessor<TAPosition> ug::FracturedMediaRefiner< TGrid, TAPosition >::m_aaPos private
Referenced by ug::FracturedMediaRefiner< TGrid, TAPosition >::aspect_ratio(), ug::FracturedMediaRefiner< TGrid, TAPosition >::collect_objects_for_refine(), ug::FracturedMediaRefiner< TGrid, TAPosition >::mark(), and ug::FracturedMediaRefiner< TGrid, TAPosition >::set_position_attachment().
template<class TGrid , class TAPosition > number ug::FracturedMediaRefiner< TGrid, TAPosition >::m_aspectRatioThreshold private
Referenced by ug::FracturedMediaRefiner< TGrid, TAPosition >::collect_objects_for_refine(), ug::FracturedMediaRefiner< TGrid, TAPosition >::mark(), and ug::FracturedMediaRefiner< TGrid, TAPosition >::set_aspect_ratio_threshold().
template<class TGrid , class TAPosition > std::queue<Face*> ug::FracturedMediaRefiner< TGrid, TAPosition >::m_queDegeneratedFaces private
Referenced by ug::FracturedMediaRefiner< TGrid, TAPosition >::collect_objects_for_refine(), and ug::FracturedMediaRefiner< TGrid, TAPosition >::mark().
The documentation for this class was generated from the following files:
ugbase/lib_grid/algorithms/refinement/fractured_media_refiner.h
ugbase/lib_grid/algorithms/refinement/fractured_media_refiner.cpp