ug4: ug::LocalToGlobalMapperNLGS< TAlgebra > Class Template Reference
ug::LocalToGlobalMapperNLGS< TAlgebra > Class Template Reference
#include <nl_gauss_seidel.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef algebra_type::matrix_type matrix_type
Type of algebra matrix.
typedef algebra_type::vector_type vector_type
Type of algebra vector.
Public Types inherited from ug::ILocalToGlobalMapper< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef algebra_type::matrix_type matrix_type
Type of algebra matrix.
typedef algebra_type::vector_type vector_type
Type of algebra vector.
Public Member Functions
void add_local_mat_to_global (matrix_type &mat, const LocalMatrix &lmat, ConstSmartPtr< DoFDistribution > dd)
adds a local matrix to the global matrix
void add_local_vec_to_global (vector_type &vec, const LocalVector &lvec, ConstSmartPtr< DoFDistribution > dd)
adds a local vector to the global rhs
LocalToGlobalMapperNLGS ()
default constructor
void modify_LocalSol (LocalVector &vecMod, const LocalVector &lvec, ConstSmartPtr< DoFDistribution > dd)
modifies local solution vector for adapted defect computation
void set_assembling_index (const size_t assIndex)
sets assembling index
~LocalToGlobalMapperNLGS ()
destructor
Public Member Functions inherited from ug::ILocalToGlobalMapper< TAlgebra >
ILocalToGlobalMapper ()
default Constructor
virtual ~ILocalToGlobalMapper ()
virtual destructor
Private Attributes
size_t m_assemblingIndex
Member Typedef Documentation
template<typename TAlgebra> typedef TAlgebra ug::LocalToGlobalMapperNLGS< TAlgebra >::algebra_type
Algebra type.
template<typename TAlgebra> typedef algebra_type::matrix_type ug::LocalToGlobalMapperNLGS< TAlgebra >::matrix_type
Type of algebra matrix.
template<typename TAlgebra> typedef algebra_type::vector_type ug::LocalToGlobalMapperNLGS< TAlgebra >::vector_type
Type of algebra vector.
Constructor & Destructor Documentation
template<typename TAlgebra> ug::LocalToGlobalMapperNLGS< TAlgebra >::LocalToGlobalMapperNLGS () inline
default constructor
References ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_mat_to_global(), and ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_vec_to_global().
template<typename TAlgebra> ug::LocalToGlobalMapperNLGS< TAlgebra >::~LocalToGlobalMapperNLGS () inline
destructor
References ug::LocalToGlobalMapperNLGS< TAlgebra >::m_assemblingIndex.
Member Function Documentation
template<typename TAlgebra > void ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_mat_to_global (matrix_type & mat, const LocalMatrix & lmat, ConstSmartPtr< DoFDistribution > dd) virtual
adds a local matrix to the global matrix
Implements ug::ILocalToGlobalMapper< TAlgebra >.
References ug::BlockRef(), ug::LocalIndices::comp(), ug::LocalMatrix::get_col_indices(), ug::LocalMatrix::get_row_indices(), ug::LocalIndices::index(), ug::NLGaussSeidelSolver< TDomain, TAlgebra >::NLGaussSeidelSolver(), ug::LocalMatrix::num_all_col_dof(), ug::LocalMatrix::num_all_col_fct(), ug::LocalMatrix::num_all_row_dof(), ug::LocalMatrix::num_all_row_fct(), and ug::LocalMatrix::value().
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::LocalToGlobalMapperNLGS().
template<typename TAlgebra > void ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_vec_to_global (vector_type & vec, const LocalVector & lvec, ConstSmartPtr< DoFDistribution > dd) virtual
adds a local vector to the global rhs
Implements ug::ILocalToGlobalMapper< TAlgebra >.
References ug::BlockRef(), ug::LocalIndices::comp(), ug::LocalVector::get_indices(), ug::LocalIndices::index(), ug::LocalVector::num_all_dof(), ug::LocalVector::num_all_fct(), and ug::LocalVector::value().
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::LocalToGlobalMapperNLGS().
template<typename TAlgebra> void ug::LocalToGlobalMapperNLGS< TAlgebra >::modify_LocalSol (LocalVector & vecMod, const LocalVector & lvec, ConstSmartPtr< DoFDistribution > dd) inline virtual
modifies local solution vector for adapted defect computation
Implements ug::ILocalToGlobalMapper< TAlgebra >.
template<typename TAlgebra> void ug::LocalToGlobalMapperNLGS< TAlgebra >::set_assembling_index (const size_t assIndex) inline
sets assembling index
References ug::LocalToGlobalMapperNLGS< TAlgebra >::m_assemblingIndex.
Member Data Documentation
template<typename TAlgebra> size_t ug::LocalToGlobalMapperNLGS< TAlgebra >::m_assemblingIndex private
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::set_assembling_index(), and ug::LocalToGlobalMapperNLGS< TAlgebra >::~LocalToGlobalMapperNLGS().
The documentation for this class was generated from the following files:
ugbase/lib_disc/operator/non_linear_operator/nl_gauss_seidel/nl_gauss_seidel.h
ugbase/lib_disc/operator/non_linear_operator/nl_gauss_seidel/nl_gauss_seidel_impl.h