ug4: ug::RiverOrdering< TAlgebra, TDomain, O_t > Class Template Reference
ug::RiverOrdering< TAlgebra, TDomain, O_t > Class Template Reference
#include <riverorder.h>
Public Types
typedef boost::graph_traits< G_t >::adjacency_iterator adj_iter
typedef IOrderingAlgorithm< TAlgebra, O_t > baseclass
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::bidirectionalS > G_t
typedef GridFunction< TDomain, TAlgebra > GridFunc_t
Grid function type for the solution.
typedef TAlgebra::matrix_type M_t
typedef TAlgebra::vector_type V_t
typedef boost::graph_traits< G_t >::vertex_descriptor vd
Public Types inherited from ug::IOrderingAlgorithm< TAlgebra, O_t >
typedef TAlgebra::matrix_type M_t
typedef TAlgebra::vector_type V_t
Public Member Functions
void check ()
SmartPtr< IOrderingAlgorithm< TAlgebra, O_t > > clone ()
void compute ()
vd get_source_vertex (std::vector< BOOL > &visited, G_t &g)
void init (M_t *)
void init (M_t *, const O_t &)
void init (M_t *, const V_t &, const O_t &)
void init (M_t *A, const V_t &V)
virtual const char * name () const
O_t & ordering ()
RiverOrdering ()
RiverOrdering (const LexOrdering< TAlgebra, TDomain, O_t > &parent)
clone constructor
void select_sources (const char *ssName)
void topological_ordering (O_t &o, G_t &g)
Public Member Functions inherited from ug::IOrderingAlgorithm< TAlgebra, O_t >
virtual void init (M_t *, const std::vector< size_t > &)=0
virtual void init (M_t *, const V_t &, const std::vector< size_t > &)=0
IOrderingAlgorithm ()
virtual ~IOrderingAlgorithm ()
Private Attributes
G_t g
std::vector< BOOL > m_sources
int m_ssIdx
const char * m_ssName
O_t o
Member Typedef Documentation
adj_iter
template<typename TAlgebra , typename TDomain , typename O_t > typedef boost::graph_traits<G_t>::adjacency_iterator ug::RiverOrdering< TAlgebra, TDomain, O_t >::adj_iter
baseclass
template<typename TAlgebra , typename TDomain , typename O_t > typedef IOrderingAlgorithm<TAlgebra, O_t> ug::RiverOrdering< TAlgebra, TDomain, O_t >::baseclass
G_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS> ug::RiverOrdering< TAlgebra, TDomain, O_t >::G_t
GridFunc_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef GridFunction<TDomain, TAlgebra> ug::RiverOrdering< TAlgebra, TDomain, O_t >::GridFunc_t
Grid function type for the solution.
M_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef TAlgebra::matrix_type ug::RiverOrdering< TAlgebra, TDomain, O_t >::M_t
V_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef TAlgebra::vector_type ug::RiverOrdering< TAlgebra, TDomain, O_t >::V_t
vd
template<typename TAlgebra , typename TDomain , typename O_t > typedef boost::graph_traits<G_t>::vertex_descriptor ug::RiverOrdering< TAlgebra, TDomain, O_t >::vd
Constructor & Destructor Documentation
RiverOrdering() [1/2]
template<typename TAlgebra , typename TDomain , typename O_t > ug::RiverOrdering< TAlgebra, TDomain, O_t >::RiverOrdering () inline
RiverOrdering() [2/2]
template<typename TAlgebra , typename TDomain , typename O_t > ug::RiverOrdering< TAlgebra, TDomain, O_t >::RiverOrdering (const LexOrdering< TAlgebra, TDomain, O_t > & parent) inline
clone constructor
Member Function Documentation
check()
template<typename TAlgebra , typename TDomain , typename O_t > void ug::RiverOrdering< TAlgebra, TDomain, O_t >::check () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::is_permutation(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::name(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::o, and UG_THROW.
Referenced by ug::RiverOrdering< TAlgebra, TDomain, O_t >::compute().
clone()
template<typename TAlgebra , typename TDomain , typename O_t > SmartPtr<IOrderingAlgorithm<TAlgebra, O_t> > ug::RiverOrdering< TAlgebra, TDomain, O_t >::clone () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References make_sp().
compute()
template<typename TAlgebra , typename TDomain , typename O_t > void ug::RiverOrdering< TAlgebra, TDomain, O_t >::compute () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::RiverOrdering< TAlgebra, TDomain, O_t >::check(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::g, ug::RiverOrdering< TAlgebra, TDomain, O_t >::o, and ug::RiverOrdering< TAlgebra, TDomain, O_t >::topological_ordering().
get_source_vertex()
template<typename TAlgebra , typename TDomain , typename O_t > vd ug::RiverOrdering< TAlgebra, TDomain, O_t >::get_source_vertex (std::vector< BOOL > & visited, G_t & g) inline
References boost::adjacent_vertices(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::g, boost::in_degree(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::m_sources, and boost::num_vertices().
Referenced by ug::RiverOrdering< TAlgebra, TDomain, O_t >::topological_ordering().
init() [1/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::RiverOrdering< TAlgebra, TDomain, O_t >::init (M_t *) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::RiverOrdering< TAlgebra, TDomain, O_t >::name(), and UG_THROW.
init() [2/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::RiverOrdering< TAlgebra, TDomain, O_t >::init (M_t * , const O_t &) inline
References ug::RiverOrdering< TAlgebra, TDomain, O_t >::name(), and UG_THROW.
init() [3/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::RiverOrdering< TAlgebra, TDomain, O_t >::init (M_t * , const V_t & , const O_t &) inline
References ug::RiverOrdering< TAlgebra, TDomain, O_t >::name(), and UG_THROW.
init() [4/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::RiverOrdering< TAlgebra, TDomain, O_t >::init (M_t * A, const V_t & V) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::GridFunction< TDomain, TAlgebra >::domain(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::g, ug::RiverOrdering< TAlgebra, TDomain, O_t >::m_sources, ug::RiverOrdering< TAlgebra, TDomain, O_t >::m_ssIdx, ug::RiverOrdering< TAlgebra, TDomain, O_t >::m_ssName, ug::RiverOrdering< TAlgebra, TDomain, O_t >::name(), boost::num_vertices(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::o, UG_CATCH_THROW, UG_LOG, and UG_THROW.
name()
template<typename TAlgebra , typename TDomain , typename O_t > virtual const char* ug::RiverOrdering< TAlgebra, TDomain, O_t >::name () const inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
Referenced by ug::RiverOrdering< TAlgebra, TDomain, O_t >::check(), and ug::RiverOrdering< TAlgebra, TDomain, O_t >::init().
ordering()
template<typename TAlgebra , typename TDomain , typename O_t > O_t& ug::RiverOrdering< TAlgebra, TDomain, O_t >::ordering () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::RiverOrdering< TAlgebra, TDomain, O_t >::o.
select_sources()
template<typename TAlgebra , typename TDomain , typename O_t > void ug::RiverOrdering< TAlgebra, TDomain, O_t >::select_sources (const char * ssName) inline
References ug::RiverOrdering< TAlgebra, TDomain, O_t >::m_ssName.
topological_ordering()
template<typename TAlgebra , typename TDomain , typename O_t > void ug::RiverOrdering< TAlgebra, TDomain, O_t >::topological_ordering (O_t & o, G_t & g) inline
References ug::RiverOrdering< TAlgebra, TDomain, O_t >::g, ug::RiverOrdering< TAlgebra, TDomain, O_t >::get_source_vertex(), boost::num_vertices(), and ug::RiverOrdering< TAlgebra, TDomain, O_t >::o.
Referenced by ug::RiverOrdering< TAlgebra, TDomain, O_t >::compute().
Member Data Documentation
g
template<typename TAlgebra , typename TDomain , typename O_t > G_t ug::RiverOrdering< TAlgebra, TDomain, O_t >::g private
Referenced by ug::RiverOrdering< TAlgebra, TDomain, O_t >::compute(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::get_source_vertex(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::init(), and ug::RiverOrdering< TAlgebra, TDomain, O_t >::topological_ordering().
m_sources
template<typename TAlgebra , typename TDomain , typename O_t > std::vector<BOOL> ug::RiverOrdering< TAlgebra, TDomain, O_t >::m_sources private
Referenced by ug::RiverOrdering< TAlgebra, TDomain, O_t >::get_source_vertex(), and ug::RiverOrdering< TAlgebra, TDomain, O_t >::init().
m_ssIdx
template<typename TAlgebra , typename TDomain , typename O_t > int ug::RiverOrdering< TAlgebra, TDomain, O_t >::m_ssIdx private
Referenced by ug::RiverOrdering< TAlgebra, TDomain, O_t >::init().
m_ssName
template<typename TAlgebra , typename TDomain , typename O_t > const char* ug::RiverOrdering< TAlgebra, TDomain, O_t >::m_ssName private
Referenced by ug::RiverOrdering< TAlgebra, TDomain, O_t >::init(), and ug::RiverOrdering< TAlgebra, TDomain, O_t >::select_sources().
o
template<typename TAlgebra , typename TDomain , typename O_t > O_t ug::RiverOrdering< TAlgebra, TDomain, O_t >::o private
Referenced by ug::RiverOrdering< TAlgebra, TDomain, O_t >::check(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::compute(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::init(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::ordering(), and ug::RiverOrdering< TAlgebra, TDomain, O_t >::topological_ordering().
The documentation for this class was generated from the following file:
ugbase/lib_disc/ordering_strategies/algorithms/riverorder.h