ug4: ug::BidirectionalMatrix< T > Class Template Reference
ug::BidirectionalMatrix< T > Class Template Reference
#include <bidirectional.h>
Public Types
typedef T::const_row_iterator const_row_iterator
Public Member Functions
const_row_iterator begin_col (int col) const
const_row_iterator begin_row (int row) const
BidirectionalMatrix (BidirectionalMatrix const &o)
BidirectionalMatrix (T const *m=nullptr)
int degree (int v) const
const_row_iterator end_col (int col) const
const_row_iterator end_row (int row) const
int in_degree (int v) const
int num_cols () const
int num_connections (int v) const
int num_rows () const
BidirectionalMatrix & operator= (BidirectionalMatrix const &o)
int out_degree (int v) const
void refresh ()
Private Attributes
T const * _matrix
T _matrix_transpose
Member Typedef Documentation
const_row_iterator
template<class T > typedef T::const_row_iterator ug::BidirectionalMatrix< T >::const_row_iterator
Constructor & Destructor Documentation
BidirectionalMatrix() [1/2]
template<class T > ug::BidirectionalMatrix< T >::BidirectionalMatrix (T const * m = nullptr) inline explicit
References ug::BidirectionalMatrix< T >::refresh().
BidirectionalMatrix() [2/2]
template<class T > ug::BidirectionalMatrix< T >::BidirectionalMatrix (BidirectionalMatrix< T > const & o) inline explicit
References ug::BidirectionalMatrix< T >::_matrix_transpose.
Member Function Documentation
begin_col()
template<class T > const_row_iterator ug::BidirectionalMatrix< T >::begin_col (int col) const inline
References ug::BidirectionalMatrix< T >::_matrix_transpose.
Referenced by boost::coadjacent_vertices().
begin_row()
template<class T > const_row_iterator ug::BidirectionalMatrix< T >::begin_row (int row) const inline
References ug::BidirectionalMatrix< T >::_matrix.
Referenced by boost::adjacent_vertices().
degree()
template<class T > int ug::BidirectionalMatrix< T >::degree (int v) const inline
References ug::BidirectionalMatrix< T >::out_degree(), and untested.
Referenced by boost::degree().
end_col()
template<class T > const_row_iterator ug::BidirectionalMatrix< T >::end_col (int col) const inline
References ug::BidirectionalMatrix< T >::_matrix_transpose.
Referenced by boost::coadjacent_vertices().
end_row()
template<class T > const_row_iterator ug::BidirectionalMatrix< T >::end_row (int row) const inline
References ug::BidirectionalMatrix< T >::_matrix.
Referenced by boost::adjacent_vertices().
in_degree()
template<class T > int ug::BidirectionalMatrix< T >::in_degree (int v) const inline
References ug::BidirectionalMatrix< T >::_matrix_transpose, and boost::out_degree().
Referenced by boost::in_degree().
num_cols()
template<class T > int ug::BidirectionalMatrix< T >::num_cols () const inline
References ug::BidirectionalMatrix< T >::num_rows(), and untested.
num_connections()
template<class T > int ug::BidirectionalMatrix< T >::num_connections (int v) const inline
References ug::BidirectionalMatrix< T >::_matrix, ug::BidirectionalMatrix< T >::_matrix_transpose, and ug::BidirectionalMatrix< T >::num_rows().
num_rows()
template<class T > int ug::BidirectionalMatrix< T >::num_rows () const inline
References ug::BidirectionalMatrix< T >::_matrix.
Referenced by ug::BidirectionalMatrix< T >::num_cols(), ug::BidirectionalMatrix< T >::num_connections(), boost::num_vertices(), and boost::vertices().
operator=()
template<class T > BidirectionalMatrix& ug::BidirectionalMatrix< T >::operator= (BidirectionalMatrix< T > const & o) inline
References ug::BidirectionalMatrix< T >::_matrix, and ug::BidirectionalMatrix< T >::_matrix_transpose.
out_degree()
template<class T > int ug::BidirectionalMatrix< T >::out_degree (int v) const inline
References ug::BidirectionalMatrix< T >::_matrix, and boost::out_degree().
Referenced by ug::BidirectionalMatrix< T >::degree(), and boost::out_degree().
refresh()
template<class T > void ug::BidirectionalMatrix< T >::refresh () inline
References ug::BidirectionalMatrix< T >::_matrix, ug::BidirectionalMatrix< T >::_matrix_transpose, ug::get_clock_s(), and UG_LOG.
Referenced by ug::BidirectionalMatrix< T >::BidirectionalMatrix().
Member Data Documentation
_matrix
template<class T > T const* ug::BidirectionalMatrix< T >::_matrix private
Referenced by ug::BidirectionalMatrix< T >::begin_row(), ug::BidirectionalMatrix< T >::end_row(), ug::BidirectionalMatrix< T >::num_connections(), ug::BidirectionalMatrix< T >::num_rows(), ug::BidirectionalMatrix< T >::operator=(), ug::BidirectionalMatrix< T >::out_degree(), and ug::BidirectionalMatrix< T >::refresh().
_matrix_transpose
template<class T > T ug::BidirectionalMatrix< T >::_matrix_transpose private
Referenced by ug::BidirectionalMatrix< T >::begin_col(), ug::BidirectionalMatrix< T >::BidirectionalMatrix(), ug::BidirectionalMatrix< T >::end_col(), ug::BidirectionalMatrix< T >::in_degree(), ug::BidirectionalMatrix< T >::num_connections(), ug::BidirectionalMatrix< T >::operator=(), and ug::BidirectionalMatrix< T >::refresh().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/graph_interface/bidirectional.h