ug4: ug::bridge::ExportedFunction Class Reference
ug::bridge::ExportedFunction Class Reference
ugbase » Bridge » Registry
This class describes a wrapper for a c++ - function, that is exported by ug.
#include <global_function.h>
Public Types
typedef void(* ProxyFunc) (void *func, const ParameterStack &in, ParameterStack &out)
Public Member Functions
void execute (const ParameterStack &paramsIn, ParameterStack &paramsOut) const
executes the function
template<typename TFunc >
ExportedFunction (TFunc f, ProxyFunc pf, const std::string &name, const std::string &funcOptions, const std::string &group, const std::string &retValInfos, const std::string &paramInfos, const std::string &tooltip, const std::string &help)
const std::string & group () const
return groups
Public Member Functions inherited from ug::bridge::ExportedFunctionBase
bool check_consistency (std::string classname="") const
returns true if all parameters of the function are correctly declared
ExportedFunctionBase (const std::string &funcName, const std::string &funcOptions, const std::string &retValInfos, const std::string &paramInfos, const std::string &tooltip, const std::string &help)
const std::string & help () const
help informations
const std::string & name () const
name of function
size_t num_infos (size_t i) const
number of info strings for one parameter
size_t num_parameter () const
number of parameters.
const std::string & options () const
name of function
const char * parameter_class_name (size_t i) const
class name of parameter i
const std::string & parameter_info (size_t i, size_t j) const
type info of all parameters
const std::string & parameter_info_string () const
whole string of all type infos for of all parameters
const std::vector< std::string > & parameter_info_vec (size_t i) const
type info of i th parameters
const std::string & parameter_name (size_t i) const
name of parameter i
const ParameterInfo & params_in () const
parameter list for input values
ParameterInfo & params_in ()
non-const export of param list
const ParameterInfo & params_out () const
parameter list for input values
const std::string & return_info (size_t i) const
type info of return type
const std::vector< std::string > & return_info_vec () const
type info of return value
const std::string & return_name () const
name of return value
const std::string & tooltip () const
gives some information to the exported functions
Protected Attributes
void * m_func
pointer to to function
std::string m_group
save groups
ProxyFunc m_proxy_func
proxy function
Protected Attributes inherited from ug::bridge::ExportedFunctionBase
std::string m_help
std::string m_methodOptions
std::string m_name
std::string m_paramInfos
ParameterInfo m_paramsIn
ParameterInfo m_paramsOut
std::string m_retValInfos
std::string m_tooltip
std::vector< std::string > m_vRetValInfo
std::vector< std::vector< std::string > > m_vvParamInfo
Additional Inherited Members
Protected Member Functions inherited from ug::bridge::ExportedFunctionBase
template<typename TFunc >
void create_parameter_stack ()
void tokenize (const std::string &str, std::vector< std::string > &tokens, const char delimiter)
Detailed Description
This class describes a wrapper for a c++ - function, that is exported by ug.
Member Typedef Documentation
typedef void(* ug::bridge::ExportedFunction::ProxyFunc) (void *func, const ParameterStack &in, ParameterStack &out)
Constructor & Destructor Documentation
template<typename TFunc > ug::bridge::ExportedFunction::ExportedFunction (TFunc f, ProxyFunc pf, const std::string & name, const std::string & funcOptions, const std::string & group, const std::string & retValInfos, const std::string & paramInfos, const std::string & tooltip, const std::string & help) inline
Member Function Documentation
void ug::bridge::ExportedFunction::execute (const ParameterStack & paramsIn, ParameterStack & paramsOut) const inline
executes the function
Referenced by Java_edu_gcsc_vrl_ug_UG__1invokeFunction(), ug::bridge::lua::LuaProxyFunction(), and ug::bridge::WriteLUAObject2().
const std::string& ug::bridge::ExportedFunction::group () const inline
return groups
Referenced by ug::vrl::function2NativeFunction().
Member Data Documentation
void* ug::bridge::ExportedFunction::m_func protected
pointer to to function
Referenced by ug::bridge::ExportedFunctionGroup::get_overload(), and ug::bridge::ExportedFunctionGroup::get_overload_by_type_id().
std::string ug::bridge::ExportedFunction::m_group protected
save groups
ProxyFunc ug::bridge::ExportedFunction::m_proxy_func protected
proxy function
The documentation for this class was generated from the following file:
ugbase/registry/global_function.h