ug4: ug::PILUTPreconditioner< TAlgebra > Class Template Reference
ug::PILUTPreconditioner< TAlgebra > Class Template Reference
#include <pilut.h>
Public Types
typedef TAlgebra algebra_type
typedef IPreconditioner< TAlgebra >::matrix_operator_type matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
SmartPtr< ILinearIterator< vector_type > > clone ()
clone
PILUTPreconditioner (double eps=0)
void set_info (bool info)
sets storage information output to true or false
void set_show_progress (bool s)
set whether the progress meter should be shown
void set_threshold (number thresh)
sets threshold for incomplete LU factorisation (added 01122010ih)
virtual ~PILUTPreconditioner ()
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
virtual std::string config_string () const
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
virtual bool supports_parallel () const=0
returns if parallel solving is supported
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
returns true if the debug writer is set
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
size_t eliminate_row (std::vector< typename matrix_type::connection > &con, size_t start, size_t stop, double dmax)
virtual const char * name () const
returns the name of iterator
virtual bool postprocess ()
cleans the operator
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
initializes the preconditioner
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
computes a new correction c = B*d
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
void enter_debug_writer_section (const char *secDir)
enters a debugging section
void enter_debug_writer_section (std::string secDir)
enters a debugging section
void leave_debug_writer_section ()
leaves a debugging section
void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
void write_debug (const matrix_type &mat, std::string name)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
double m_eps
bool m_info
matrix_type m_L
bool m_show_progress
matrix_type m_U
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Static Protected Attributes
static const number m_small = 1e-8
Private Types
typedef matrix_type::value_type block_type
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::PILUTPreconditioner< TAlgebra >::algebra_type
block_type
template<typename TAlgebra > typedef matrix_type::value_type ug::PILUTPreconditioner< TAlgebra >::block_type private
matrix_operator_type
template<typename TAlgebra > typedef IPreconditioner<TAlgebra>::matrix_operator_type ug::PILUTPreconditioner< TAlgebra >::matrix_operator_type
Matrix Operator type.
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::PILUTPreconditioner< TAlgebra >::matrix_type
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::PILUTPreconditioner< TAlgebra >::vector_type
Constructor & Destructor Documentation
PILUTPreconditioner()
template<typename TAlgebra > ug::PILUTPreconditioner< TAlgebra >::PILUTPreconditioner (double eps = 0) inline
~PILUTPreconditioner()
template<typename TAlgebra > virtual ug::PILUTPreconditioner< TAlgebra >::~PILUTPreconditioner () inline virtual
Member Function Documentation
clone()
template<typename TAlgebra > SmartPtr<ILinearIterator<vector_type> > ug::PILUTPreconditioner< TAlgebra >::clone () inline virtual
clone
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References ug::ILinearIterator< TAlgebra::vector_type >::damping(), ug::DebugWritingObject< TAlgebra >::debug_writer(), ug::PILUTPreconditioner< TAlgebra >::m_eps, and ug::PILUTPreconditioner< TAlgebra >::m_info.
eliminate_row()
template<typename TAlgebra > size_t ug::PILUTPreconditioner< TAlgebra >::eliminate_row (std::vector< typename matrix_type::connection > & con, size_t start, size_t stop, double dmax) inline protected
References ug::BlockNorm(), ug::PILUTPreconditioner< TAlgebra >::m_eps, ug::PILUTPreconditioner< TAlgebra >::m_U, and UG_ASSERT.
Referenced by ug::PILUTPreconditioner< TAlgebra >::preprocess().
name()
template<typename TAlgebra > virtual const char* ug::PILUTPreconditioner< TAlgebra >::name () const inline protected virtual
returns the name of iterator
This method returns the name of the iterator operator. This function is typically needed, when the iterator operator is used inside of another operator and some debug output should be printed
Returns
const char* name of inverse operator
Implements ug::IPreconditioner< TAlgebra >.
postprocess()
template<typename TAlgebra > virtual bool ug::PILUTPreconditioner< TAlgebra >::postprocess () inline protected virtual
cleans the operator
Implements ug::IPreconditioner< TAlgebra >.
preprocess()
template<typename TAlgebra > virtual bool ug::PILUTPreconditioner< TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) inline protected virtual
initializes the preconditioner
This method is used to initialize the preconditioner. Usually, here are performed computationally expensive operations, that should only be computed once for an underlying matrix (e.g. LU factorization), while the preconditioner will by applied (using 'step'-method) several times.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::BlockNorm(), ug::PILUTPreconditioner< TAlgebra >::eliminate_row(), ug::PILUTPreconditioner< TAlgebra >::m_eps, ug::PILUTPreconditioner< TAlgebra >::m_info, ug::PILUTPreconditioner< TAlgebra >::m_L, ug::PILUTPreconditioner< TAlgebra >::m_show_progress, ug::PILUTPreconditioner< TAlgebra >::m_U, num_rows(), PROFILE_BEGIN, PROFILE_END, PROGRESS_FINISH, PROGRESS_START_WITH, PROGRESS_UPDATE, ug::reset_floats(), STATIC_ASSERT, and UG_LOG.
set_info()
template<typename TAlgebra > void ug::PILUTPreconditioner< TAlgebra >::set_info (bool info) inline
sets storage information output to true or false
References ug::PILUTPreconditioner< TAlgebra >::m_info.
set_show_progress()
template<typename TAlgebra > void ug::PILUTPreconditioner< TAlgebra >::set_show_progress (bool s) inline
set whether the progress meter should be shown
References ug::PILUTPreconditioner< TAlgebra >::m_show_progress, and s.
set_threshold()
template<typename TAlgebra > void ug::PILUTPreconditioner< TAlgebra >::set_threshold (number thresh) inline
sets threshold for incomplete LU factorisation (added 01122010ih)
References ug::PILUTPreconditioner< TAlgebra >::m_eps.
step()
template<typename TAlgebra > virtual bool ug::PILUTPreconditioner< TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) inline protected virtual
computes a new correction c = B*d
This method computes a new correction c = B*d. It can only be called, when the preprocess has been done.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
[out] c correction
[in] d defect
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::BlockNorm(), ug::InverseMatMult(), ug::PILUTPreconditioner< TAlgebra >::m_L, ug::PILUTPreconditioner< TAlgebra >::m_small, ug::PILUTPreconditioner< TAlgebra >::m_U, ug::MatMultAdd(), ug::PST_CONSISTENT, s, UG_ASSERT, and UG_LOG.
Member Data Documentation
m_eps
template<typename TAlgebra > double ug::PILUTPreconditioner< TAlgebra >::m_eps protected
Referenced by ug::PILUTPreconditioner< TAlgebra >::clone(), ug::PILUTPreconditioner< TAlgebra >::eliminate_row(), ug::PILUTPreconditioner< TAlgebra >::preprocess(), and ug::PILUTPreconditioner< TAlgebra >::set_threshold().
m_info
template<typename TAlgebra > bool ug::PILUTPreconditioner< TAlgebra >::m_info protected
Referenced by ug::PILUTPreconditioner< TAlgebra >::clone(), ug::PILUTPreconditioner< TAlgebra >::preprocess(), and ug::PILUTPreconditioner< TAlgebra >::set_info().
m_L
template<typename TAlgebra > matrix_type ug::PILUTPreconditioner< TAlgebra >::m_L protected
Referenced by ug::PILUTPreconditioner< TAlgebra >::preprocess(), and ug::PILUTPreconditioner< TAlgebra >::step().
m_show_progress
template<typename TAlgebra > bool ug::PILUTPreconditioner< TAlgebra >::m_show_progress protected
Referenced by ug::PILUTPreconditioner< TAlgebra >::preprocess(), and ug::PILUTPreconditioner< TAlgebra >::set_show_progress().
m_small
template<typename TAlgebra > const number ug::PILUTPreconditioner< TAlgebra >::m_small = 1e-8 static protected
Referenced by ug::PILUTPreconditioner< TAlgebra >::step().
m_U
template<typename TAlgebra > matrix_type ug::PILUTPreconditioner< TAlgebra >::m_U protected
Referenced by ug::PILUTPreconditioner< TAlgebra >::eliminate_row(), ug::PILUTPreconditioner< TAlgebra >::preprocess(), and ug::PILUTPreconditioner< TAlgebra >::step().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/preconditioner/pilut.h