ug4: ug::IIntegrand< TData, TWorldDim > Class Template Reference
ug::IIntegrand< TData, TWorldDim > Class Template Reference abstract
Abstract integrand interface.
#include <integrate.h>
Public Types
typedef TData data_type
data type
Public Member Functions
virtual void set_subset (int si)
sets the subset
int subset () const
returns the subset
virtual ~IIntegrand ()
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
Static Public Attributes
static const int worldDim = TWorldDim
world dimension
Protected Attributes
int m_si
subset
Detailed Description
template<typename TData, int TWorldDim>
class ug::IIntegrand< TData, TWorldDim >
Abstract integrand interface.
An integrand is a short-living (temporary) object that is generated/used in various integration functions.
Member Typedef Documentation
data_type
template<typename TData, int TWorldDim> typedef TData ug::IIntegrand< TData, TWorldDim >::data_type
data type
Constructor & Destructor Documentation
~IIntegrand()
template<typename TData, int TWorldDim> virtual ug::IIntegrand< TData, TWorldDim >::~IIntegrand () inline virtual
Member Function Documentation
set_subset()
template<typename TData, int TWorldDim> virtual void ug::IIntegrand< TData, TWorldDim >::set_subset (int si) inline virtual
sets the subset
Reimplemented in ug::H1EnergyIntegrand< TGridFunction >, ug::H1SemiDistIntegrand< TGridFunction >, ug::H1SemiIntegrand< TGridFunction >, ug::L2DistIntegrand< TGridFunction >, ug::L2Integrand< TGridFunction >, ug::H1ErrorIntegrand< TGridFunction >, ug::L2ErrorIntegrand< TGridFunction >, and ug::UserDataDistIntegrandSq< TData, TGridFunction >.
Referenced by ug::H1EnergyIntegrand< TGridFunction >::evaluate(), ug::IntegrateSubset(), ug::UserDataDistIntegrandSq< TData, TGridFunction >::set_subset(), ug::L2ErrorIntegrand< TGridFunction >::set_subset(), ug::H1ErrorIntegrand< TGridFunction >::set_subset(), ug::L2Integrand< TGridFunction >::set_subset(), ug::L2DistIntegrand< TGridFunction >::set_subset(), ug::H1SemiIntegrand< TGridFunction >::set_subset(), ug::H1SemiDistIntegrand< TGridFunction >::set_subset(), and ug::H1EnergyIntegrand< TGridFunction >::set_subset().
subset()
template<typename TData, int TWorldDim> int ug::IIntegrand< TData, TWorldDim >::subset () const inline
returns the subset
Referenced by ug::L2Integrand< TGridFunction >::evaluate(), ug::L2DistIntegrand< TGridFunction >::evaluate(), ug::H1SemiIntegrand< TGridFunction >::evaluate(), ug::H1SemiDistIntegrand< TGridFunction >::evaluate(), and ug::H1EnergyIntegrand< TGridFunction >::evaluate().
values() [1/3]
template<typename TData, int TWorldDim> virtual void ug::IIntegrand< TData, TWorldDim >::values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject * pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP) pure virtual
returns the values of the integrand for a bunch of ips
Parameters
vValue[out] the value of the integrand at the ips
vGlobIP[in] global integration point positions
pElem[in] the element to integrate
vCornerCoords[in] corner coordinates of the element
vLocIP[in] local integration point positions
vJT[in] jacobian transposed at integration point
numIP[in] number of integration points
Implemented in ug::StdIntegrand< TData, TWorldDim, TImpl >, ug::StdIntegrand< number, TGridFunction::dim, H1ErrorIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, L2Integrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, H1EnergyIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, UserDataIntegrandSq< TData, TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, H1SemiIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, L2DistIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, H1SemiDistIntegrand< TGridFunction > >, ug::StdIntegrand< TData, TGridFunction::dim, UserDataIntegrand< TData, TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, L2ErrorIntegrand< TGridFunction > >, and ug::StdIntegrand< number, TGridFunction::dim, UserDataDistIntegrandSq< TData, TGridFunction > >.
Referenced by ug::Integrate().
values() [2/3]
template<typename TData, int TWorldDim> virtual void ug::IIntegrand< TData, TWorldDim >::values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject * pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP) pure virtual
returns the values of the integrand for a bunch of ips
Parameters
vValue[out] the value of the integrand at the ips
vGlobIP[in] global integration point positions
pElem[in] the element to integrate
vCornerCoords[in] corner coordinates of the element
vLocIP[in] local integration point positions
vJT[in] jacobian transposed at integration point
numIP[in] number of integration points
Implemented in ug::StdIntegrand< TData, TWorldDim, TImpl >, ug::StdIntegrand< number, TGridFunction::dim, H1ErrorIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, L2Integrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, H1EnergyIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, UserDataIntegrandSq< TData, TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, H1SemiIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, L2DistIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, H1SemiDistIntegrand< TGridFunction > >, ug::StdIntegrand< TData, TGridFunction::dim, UserDataIntegrand< TData, TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, L2ErrorIntegrand< TGridFunction > >, and ug::StdIntegrand< number, TGridFunction::dim, UserDataDistIntegrandSq< TData, TGridFunction > >.
values() [3/3]
template<typename TData, int TWorldDim> virtual void ug::IIntegrand< TData, TWorldDim >::values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject * pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP) pure virtual
returns the values of the integrand for a bunch of ips
Parameters
vValue[out] the value of the integrand at the ips
vGlobIP[in] global integration point positions
pElem[in] the element to integrate
vCornerCoords[in] corner coordinates of the element
vLocIP[in] local integration point positions
vJT[in] jacobian transposed at integration point
numIP[in] number of integration points
Implemented in ug::StdIntegrand< TData, TWorldDim, TImpl >, ug::StdIntegrand< number, TGridFunction::dim, H1ErrorIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, L2Integrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, H1EnergyIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, UserDataIntegrandSq< TData, TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, H1SemiIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, L2DistIntegrand< TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, H1SemiDistIntegrand< TGridFunction > >, ug::StdIntegrand< TData, TGridFunction::dim, UserDataIntegrand< TData, TGridFunction > >, ug::StdIntegrand< number, TGridFunction::dim, L2ErrorIntegrand< TGridFunction > >, and ug::StdIntegrand< number, TGridFunction::dim, UserDataDistIntegrandSq< TData, TGridFunction > >.
Member Data Documentation
m_si
template<typename TData, int TWorldDim> int ug::IIntegrand< TData, TWorldDim >::m_si protected
subset
worldDim
template<typename TData, int TWorldDim> const int ug::IIntegrand< TData, TWorldDim >::worldDim = TWorldDim static
world dimension
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/integrate.h