ug4: ug::CRFVGeometry< TElem, TWorldDim > Class Template Reference
ug::CRFVGeometry< TElem, TWorldDim > Class Template Reference
#include <fvcr_geom.h>
Classes
class BF
boundary face
class CONSTRAINED_DOF
public hanging node interface for compatibility reasons
class SCV
sub control volume structure
class SCVF
Sub-Control Volume Face structure.
Public Types
typedef TElem elem_type
type of element
typedef crfv_traits< TWorldDim, TWorldDim >::face_type face_type0
typedef crfv_traits< TWorldDim, TWorldDim+1 >::face_type face_type1
typedef CrouzeixRaviartLSFS< ref_elem_type > local_shape_fct_set_type
type of Shape function used
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
type of reference element
typedef crfv_traits< TWorldDim, TWorldDim >::scv_type scv_type0
traits
typedef crfv_traits< TWorldDim, TWorldDim+1 >::scv_type scv_type1
Public Member Functions
void add_boundary_subset (int subsetIndex)
add subset that is interpreted as boundary subset.
const BF & bf (int subsetIndex, size_t i) const
returns the boundary face i for subsetIndex
const std::vector< BF > & bf (int subsetIndex) const
returns reference to vector of boundary faces for subsetIndex
void clear_boundary_subsets ()
reset all boundary subsets
const CONSTRAINED_DOF & constrained_dof (size_t i) const
const MathVector< worldDim > * corners () const
CRFVGeometry ()
construct object and initialize local values and sizes
const MathVector< worldDim > global_bary () const
returns global barycenter
const MathVector< dim > local_bary () const
returns local barycenter
size_t num_bf () const
number of all boundary faces
size_t num_bf (int subsetIndex) const
number of boundary faces on subset 'subsetIndex'
size_t num_boundary_subsets ()
number of registered boundary subsets
size_t num_constrained_dofs () const
size_t num_scv () const
number of SubControlVolumes
size_t num_scv_ips () const
returns number of all scv ips
size_t num_scvf () const
number of SubControlVolumeFaces
size_t num_scvf_ips () const
returns number of all scvf ips
size_t num_sh () const
number of shape functions
void remove_boundary_subset (int subsetIndex)
removes subset that is interpreted as boundary subset.
const SCV & scv (size_t i) const
const access to SubControlVolume number i
const MathVector< worldDim > * scv_global_ips () const
returns all ips of scv as they appear in scv loop
const MathVector< dim > * scv_local_ips () const
returns all ips of scv as they appear in scv loop
const SCVF & scvf (size_t i) const
const access to SubControlVolumeFace number i
const MathVector< worldDim > * scvf_global_ips () const
returns all ips of scvf as they appear in scv loop
const MathVector< dim > * scvf_local_ips () const
returns all ips of scvf as they appear in scv loop
void update (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update data for given element
void update_boundary_faces (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update boundary data for given element
void update_local_data ()
update local data
Public Attributes
MathVector< worldDim > globalBary
MathVector< dim > localBary
Static Public Attributes
static const int dim = ref_elem_type::dim
dimension of reference element
static const size_t maxNumSCVF = ref_elem_type::numEdges
static const size_t nip = 1
number of integration points
static const size_t nsh = local_shape_fct_set_type::nsh
number of shape functions
static const size_t numSCV = nsh
number of SubControlVolumes
static const size_t numSCVF = ref_elem_type::numEdges
number of SubControlVolumeFaces
static const int order = 1
order
static const bool staticLocalData = true
flag indicating if local data may change
static const bool usesHangingNodes = false
Hanging node flag: this Geometry does not support hanging nodes.
static const int worldDim = TWorldDim
dimension of world
Protected Attributes
std::map< int, std::vector< BF > > m_mapVectorBF
MathVector< worldDim > m_vCo [numMaxCo]
MathVector< worldDim > m_vGlobSCVF_IP [numSCVF]
MathVector< worldDim > m_vGlobUnkCoords [numSCV]
MathVector< dim > m_vLocSCVF_IP [numSCVF]
MathVector< dim > m_vLocUnkCoords [numSCV]
Static Protected Attributes
static const size_t numMaxCo = 8
Private Attributes
CONSTRAINED_DOF cd
MathVector< dim > m_ipCoord [numSCVF]
ReferenceMapping< ref_elem_type, worldDim > m_mapping
Reference Mapping.
TElem * m_pElem
pointer to current element
const ref_elem_type & m_rRefElem
Reference Element.
const local_shape_fct_set_type & m_rTrialSpace
Shape function set.
SCV m_vSCV [numSCV]
SubControlVolumes.
SCVF m_vSCVF [numSCVF]
SubControlVolumeFaces.
Member Typedef Documentation
template<typename TElem , int TWorldDim> typedef TElem ug::CRFVGeometry< TElem, TWorldDim >::elem_type
type of element
template<typename TElem , int TWorldDim> typedef crfv_traits<TWorldDim,TWorldDim>::face_type ug::CRFVGeometry< TElem, TWorldDim >::face_type0
template<typename TElem , int TWorldDim> typedef crfv_traits<TWorldDim,TWorldDim+1>::face_type ug::CRFVGeometry< TElem, TWorldDim >::face_type1
template<typename TElem , int TWorldDim> typedef CrouzeixRaviartLSFS<ref_elem_type> ug::CRFVGeometry< TElem, TWorldDim >::local_shape_fct_set_type
type of Shape function used
template<typename TElem , int TWorldDim> typedef reference_element_traits<TElem>::reference_element_type ug::CRFVGeometry< TElem, TWorldDim >::ref_elem_type
type of reference element
template<typename TElem , int TWorldDim> typedef crfv_traits<TWorldDim,TWorldDim>::scv_type ug::CRFVGeometry< TElem, TWorldDim >::scv_type0
traits
template<typename TElem , int TWorldDim> typedef crfv_traits<TWorldDim,TWorldDim+1>::scv_type ug::CRFVGeometry< TElem, TWorldDim >::scv_type1
Constructor & Destructor Documentation
template<typename TElem , int TWorldDim> ug::CRFVGeometry< TElem, TWorldDim >::CRFVGeometry ()
construct object and initialize local values and sizes
References ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::update_boundary_faces().
Member Function Documentation
template<typename TElem , int TWorldDim> void ug::CRFVGeometry< TElem, TWorldDim >::add_boundary_subset (int subsetIndex) inline
add subset that is interpreted as boundary subset.
template<typename TElem , int TWorldDim> const BF& ug::CRFVGeometry< TElem, TWorldDim >::bf (int subsetIndex, size_t i) const inline
returns the boundary face i for subsetIndex
References UG_ASSERT.
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update_boundary_faces().
template<typename TElem , int TWorldDim> const std::vector<BF>& ug::CRFVGeometry< TElem, TWorldDim >::bf (int subsetIndex) const inline
returns reference to vector of boundary faces for subsetIndex
References UG_ASSERT.
template<typename TElem , int TWorldDim> void ug::CRFVGeometry< TElem, TWorldDim >::clear_boundary_subsets () inline
reset all boundary subsets
template<typename TElem , int TWorldDim> const CONSTRAINED_DOF& ug::CRFVGeometry< TElem, TWorldDim >::constrained_dof (size_t i) const inline
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::CRFVGeometry< TElem, TWorldDim >::corners () const inline
template<typename TElem , int TWorldDim> const MathVector<worldDim> ug::CRFVGeometry< TElem, TWorldDim >::global_bary () const inline
returns global barycenter
template<typename TElem , int TWorldDim> const MathVector<dim> ug::CRFVGeometry< TElem, TWorldDim >::local_bary () const inline
returns local barycenter
template<typename TElem , int TWorldDim> size_t ug::CRFVGeometry< TElem, TWorldDim >::num_bf () const inline
number of all boundary faces
template<typename TElem , int TWorldDim> size_t ug::CRFVGeometry< TElem, TWorldDim >::num_bf (int subsetIndex) const inline
number of boundary faces on subset 'subsetIndex'
template<typename TElem , int TWorldDim> size_t ug::CRFVGeometry< TElem, TWorldDim >::num_boundary_subsets () inline
number of registered boundary subsets
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> size_t ug::CRFVGeometry< TElem, TWorldDim >::num_constrained_dofs () const inline
template<typename TElem , int TWorldDim> size_t ug::CRFVGeometry< TElem, TWorldDim >::num_scv () const inline
number of SubControlVolumes
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> size_t ug::CRFVGeometry< TElem, TWorldDim >::num_scv_ips () const inline
returns number of all scv ips
template<typename TElem , int TWorldDim> size_t ug::CRFVGeometry< TElem, TWorldDim >::num_scvf () const inline
number of SubControlVolumeFaces
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update(), and ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> size_t ug::CRFVGeometry< TElem, TWorldDim >::num_scvf_ips () const inline
returns number of all scvf ips
template<typename TElem , int TWorldDim> size_t ug::CRFVGeometry< TElem, TWorldDim >::num_sh () const inline
number of shape functions
template<typename TElem , int TWorldDim> void ug::CRFVGeometry< TElem, TWorldDim >::remove_boundary_subset (int subsetIndex) inline
removes subset that is interpreted as boundary subset.
template<typename TElem , int TWorldDim> const SCV& ug::CRFVGeometry< TElem, TWorldDim >::scv (size_t i) const inline
const access to SubControlVolume number i
References UG_ASSERT.
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::CRFVGeometry< TElem, TWorldDim >::scv_global_ips () const inline
returns all ips of scv as they appear in scv loop
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::CRFVGeometry< TElem, TWorldDim >::scv_local_ips () const inline
returns all ips of scv as they appear in scv loop
template<typename TElem , int TWorldDim> const SCVF& ug::CRFVGeometry< TElem, TWorldDim >::scvf (size_t i) const inline
const access to SubControlVolumeFace number i
References UG_ASSERT.
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update(), and ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::CRFVGeometry< TElem, TWorldDim >::scvf_global_ips () const inline
returns all ips of scvf as they appear in scv loop
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::CRFVGeometry< TElem, TWorldDim >::scvf_local_ips () const inline
returns all ips of scvf as they appear in scv loop
template<typename TElem , int TWorldDim> void ug::CRFVGeometry< TElem, TWorldDim >::update (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update data for given element
References ug::AveragePositions(), ug::CRFVGeometry< TElem, TWorldDim >::SCVF::detj, ug::CRFVGeometry< TElem, TWorldDim >::SCV::detj, ug::CRFVGeometry< TElem, TWorldDim >::dim, ug::CRFVGeometry< TElem, TWorldDim >::SCVF::global_ip(), ug::CRFVGeometry< TElem, TWorldDim >::globalBary, ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::CRFVGeometry< TElem, TWorldDim >::SCVF::JtInv, ug::CRFVGeometry< TElem, TWorldDim >::SCV::JtInv, ug::CRFVGeometry< TElem, TWorldDim >::m_mapping, ug::CRFVGeometry< TElem, TWorldDim >::m_pElem, ug::CRFVGeometry< TElem, TWorldDim >::m_rRefElem, ug::CRFVGeometry< TElem, TWorldDim >::m_vCo, ug::CRFVGeometry< TElem, TWorldDim >::m_vGlobSCVF_IP, ug::CRFVGeometry< TElem, TWorldDim >::m_vGlobUnkCoords, ug::CRFVGeometry< TElem, TWorldDim >::m_vSCV, ug::CRFVGeometry< TElem, TWorldDim >::m_vSCVF, ug::MatVecMult(), ug::CRFVGeometry< TElem, TWorldDim >::SCVF::Normal, ug::CRFVGeometry< TElem, TWorldDim >::SCV::Normal, ug::CRFVGeometry< TElem, TWorldDim >::num_boundary_subsets(), ug::CRFVGeometry< TElem, TWorldDim >::num_scv(), ug::CRFVGeometry< TElem, TWorldDim >::num_scvf(), ug::CRFVGeometry< TElem, TWorldDim >::SCVF::num_sh(), ug::CRFVGeometry< TElem, TWorldDim >::SCV::num_sh(), ug::CRFVGeometry< TElem, TWorldDim >::SCVF::numCo, ug::CRFVGeometry< TElem, TWorldDim >::SCV::numCorners, ug::CRFVGeometry< TElem, TWorldDim >::scv(), ug::CRFVGeometry< TElem, TWorldDim >::scvf(), ug::ReferenceMapping< TRefElem, TWorldDim >::sqrt_gram_det(), UG_ASSERT, ug::ReferenceMapping< TRefElem, TWorldDim >::update(), ug::CRFVGeometry< TElem, TWorldDim >::update_boundary_faces(), ug::CRFVGeometry< TElem, TWorldDim >::SCV::vGlobIP, ug::CRFVGeometry< TElem, TWorldDim >::SCVF::vGloPos, ug::CRFVGeometry< TElem, TWorldDim >::SCV::vGloPos, and ug::CRFVGeometry< TElem, TWorldDim >::SCV::Vol.
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> void ug::CRFVGeometry< TElem, TWorldDim >::update_boundary_faces (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update boundary data for given element
References ug::CRFVGeometry< TElem, TWorldDim >::bf(), ug::CollectEdgesSorted(), ug::CollectFacesSorted(), ug::CollectVertices(), ug::CRFVGeometry< TElem, TWorldDim >::BF::detj, ug::CRFVGeometry< TElem, TWorldDim >::dim, ug::ISubsetHandler::get_subset_index(), ug::CRFVGeometry< TElem, TWorldDim >::BF::globalIP, ug::ISubsetHandler::grid(), ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::CRFVGeometry< TElem, TWorldDim >::BF::JtInv, ug::CRFVGeometry< TElem, TWorldDim >::BF::localIP, ug::CRFVGeometry< TElem, TWorldDim >::m_mapping, ug::CRFVGeometry< TElem, TWorldDim >::m_mapVectorBF, ug::CRFVGeometry< TElem, TWorldDim >::m_rTrialSpace, ug::CRFVGeometry< TElem, TWorldDim >::m_vSCV, ug::MatVecMult(), ug::CRFVGeometry< TElem, TWorldDim >::SCV::nodeID, ug::CRFVGeometry< TElem, TWorldDim >::BF::nodeID, ug::CRFVGeometry< TElem, TWorldDim >::SCV::Normal, ug::CRFVGeometry< TElem, TWorldDim >::BF::Normal, ug::CRFVGeometry< TElem, TWorldDim >::BF::num_sh(), ug::CRFVGeometry< TElem, TWorldDim >::BF::numCo, ug::CRFVGeometry< TElem, TWorldDim >::SCV::numCorners, ug::ReferenceMapping< TRefElem, TWorldDim >::sqrt_gram_det(), ug::VecTwoNorm(), ug::CRFVGeometry< TElem, TWorldDim >::BF::vGlobalGrad, ug::CRFVGeometry< TElem, TWorldDim >::SCV::vGlobIP, ug::CRFVGeometry< TElem, TWorldDim >::BF::vLocalGrad, ug::CRFVGeometry< TElem, TWorldDim >::SCV::vLocIP, ug::CRFVGeometry< TElem, TWorldDim >::BF::Vol, and ug::CRFVGeometry< TElem, TWorldDim >::BF::vShape.
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> void ug::CRFVGeometry< TElem, TWorldDim >::update_local_data ()
update local data
References ug::AveragePositions(), ug::CRFVGeometry< TElem, TWorldDim >::dim, ug::CRFVGeometry< TElem, TWorldDim >::SCVF::From, ug::CRFVGeometry< TElem, TWorldDim >::SCVF::local_ip(), ug::CRFVGeometry< TElem, TWorldDim >::localBary, ug::CRFVGeometry< TElem, TWorldDim >::m_rRefElem, ug::CRFVGeometry< TElem, TWorldDim >::m_rTrialSpace, ug::CRFVGeometry< TElem, TWorldDim >::m_vLocSCVF_IP, ug::CRFVGeometry< TElem, TWorldDim >::m_vLocUnkCoords, ug::CRFVGeometry< TElem, TWorldDim >::m_vSCV, ug::CRFVGeometry< TElem, TWorldDim >::m_vSCVF, ug::CRFVGeometry< TElem, TWorldDim >::SCV::nodeID, ug::CRFVGeometry< TElem, TWorldDim >::num_scvf(), ug::CRFVGeometry< TElem, TWorldDim >::SCVF::numCo, ug::CRFVGeometry< TElem, TWorldDim >::SCV::numCorners, ug::CRFVGeometry< TElem, TWorldDim >::numSCV, ug::CRFVGeometry< TElem, TWorldDim >::numSCVF, ug::CRFVGeometry< TElem, TWorldDim >::scvf(), ug::CRFVGeometry< TElem, TWorldDim >::SCVF::To, ug::CRFVGeometry< TElem, TWorldDim >::update(), ug::CRFVGeometry< TElem, TWorldDim >::SCV::vLocIP, ug::CRFVGeometry< TElem, TWorldDim >::SCVF::vLocPos, and ug::CRFVGeometry< TElem, TWorldDim >::SCV::vLocPos.
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::CRFVGeometry().
Member Data Documentation
template<typename TElem , int TWorldDim> CONSTRAINED_DOF ug::CRFVGeometry< TElem, TWorldDim >::cd private
template<typename TElem , int TWorldDim> const int ug::CRFVGeometry< TElem, TWorldDim >::dim = ref_elem_type::dim static
dimension of reference element
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update(), ug::CRFVGeometry< TElem, TWorldDim >::update_boundary_faces(), and ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::CRFVGeometry< TElem, TWorldDim >::globalBary
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> MathVector<dim> ug::CRFVGeometry< TElem, TWorldDim >::localBary
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> MathVector<dim> ug::CRFVGeometry< TElem, TWorldDim >::m_ipCoord[numSCVF] private
template<typename TElem , int TWorldDim> ReferenceMapping<ref_elem_type, worldDim> ug::CRFVGeometry< TElem, TWorldDim >::m_mapping private
Reference Mapping.
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update(), and ug::CRFVGeometry< TElem, TWorldDim >::update_boundary_faces().
template<typename TElem , int TWorldDim> std::map<int, std::vector<BF> > ug::CRFVGeometry< TElem, TWorldDim >::m_mapVectorBF protected
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update_boundary_faces().
template<typename TElem , int TWorldDim> TElem* ug::CRFVGeometry< TElem, TWorldDim >::m_pElem private
pointer to current element
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> const ref_elem_type& ug::CRFVGeometry< TElem, TWorldDim >::m_rRefElem private
Reference Element.
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update(), and ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const local_shape_fct_set_type& ug::CRFVGeometry< TElem, TWorldDim >::m_rTrialSpace private
Shape function set.
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update_boundary_faces(), and ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::CRFVGeometry< TElem, TWorldDim >::m_vCo[numMaxCo] protected
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::CRFVGeometry< TElem, TWorldDim >::m_vGlobSCVF_IP[numSCVF] protected
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::CRFVGeometry< TElem, TWorldDim >::m_vGlobUnkCoords[numSCV] protected
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> MathVector<dim> ug::CRFVGeometry< TElem, TWorldDim >::m_vLocSCVF_IP[numSCVF] protected
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> MathVector<dim> ug::CRFVGeometry< TElem, TWorldDim >::m_vLocUnkCoords[numSCV] protected
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> SCV ug::CRFVGeometry< TElem, TWorldDim >::m_vSCV[numSCV] private
SubControlVolumes.
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update(), ug::CRFVGeometry< TElem, TWorldDim >::update_boundary_faces(), and ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> SCVF ug::CRFVGeometry< TElem, TWorldDim >::m_vSCVF[numSCVF] private
SubControlVolumeFaces.
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update(), and ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const size_t ug::CRFVGeometry< TElem, TWorldDim >::maxNumSCVF = ref_elem_type::numEdges static
template<typename TElem , int TWorldDim> const size_t ug::CRFVGeometry< TElem, TWorldDim >::nip = 1 static
number of integration points
template<typename TElem , int TWorldDim> const size_t ug::CRFVGeometry< TElem, TWorldDim >::nsh = local_shape_fct_set_type::nsh static
number of shape functions
template<typename TElem , int TWorldDim> const size_t ug::CRFVGeometry< TElem, TWorldDim >::numMaxCo = 8 static protected
template<typename TElem , int TWorldDim> const size_t ug::CRFVGeometry< TElem, TWorldDim >::numSCV = nsh static
number of SubControlVolumes
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const size_t ug::CRFVGeometry< TElem, TWorldDim >::numSCVF = ref_elem_type::numEdges static
number of SubControlVolumeFaces
Referenced by ug::CRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const int ug::CRFVGeometry< TElem, TWorldDim >::order = 1 static
order
template<typename TElem , int TWorldDim> const bool ug::CRFVGeometry< TElem, TWorldDim >::staticLocalData = true static
flag indicating if local data may change
template<typename TElem , int TWorldDim> const bool ug::CRFVGeometry< TElem, TWorldDim >::usesHangingNodes = false static
Hanging node flag: this Geometry does not support hanging nodes.
template<typename TElem , int TWorldDim> const int ug::CRFVGeometry< TElem, TWorldDim >::worldDim = TWorldDim static
dimension of world
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/fvcr_geom.h
ugbase/lib_disc/spatial_disc/disc_util/fvcr_geom.cpp