ug4: ug::IVector_AlgebraDownCastTo< TVec > Class Template Reference
ug::IVector_AlgebraDownCastTo< TVec > Class Template Reference
#include <ivector.h>
Public Member Functions
virtual double norm2 () const
virtual void print (std::ostream &output) const
virtual void set (double d)
virtual std::string short_desc () const
virtual void vec_add (double a1, double a2, const IVector &iv2)
virtual void vec_add (double a1, double a2, const IVector &iv2, double a3, const IVector &iv3)
virtual void vec_add (double a1, double a2, const IVector &iv2, double a3, const IVector &iv3, double a4, const IVector &iv4)
virtual double vec_prod (const IVector &iv) const
Public Member Functions inherited from ug::IVector
virtual size_t capacity () const =0
virtual void clear ()=0
virtual SmartPtr< IVector > clone () const =0
clones the vector (deep-copy) including values
virtual SmartPtr< IVector > clone_without_values (size_t size) const =0
clones the vector (deep-copy) excluding values
template<typename T >
T & downcast ()
template<typename T >
const T & downcast () const
double norm () const
void operator*= (double alpha)
void operator+= (const IVector &v)
void operator+= (const TE_VecAdd2< IVector > &t)
void operator+= (const TE_VecAdd3< IVector > &t)
void operator-= (const IVector &v)
void operator-= (const TE_VecAdd2< IVector > &t)
void operator-= (const TE_VecAdd3< IVector > &t)
void operator= (const IVector &v)
void operator= (const TE_VecAdd2< IVector > &t)
void operator= (const TE_VecAdd3< IVector > &t)
void operator= (const TE_VecScale< IVector > &t)
virtual void resize (size_t newSize, bool bCopyValues=true)=0
virtual size_t size () const =0
Public Member Functions inherited from ug::TE_Vector< IVector >
double scaling () const
const IVector & vec () const
Public Member Functions inherited from ug::TE_AlphaVec< T >
const T & cast () const
double scaling () const
Private Types
typedef IVector_AlgebraDownCastTo< TVec > this_type
Private Member Functions
TVec & downcast ()
const TVec & downcast () const
Friends
std::ostream & operator<< (std::ostream &output, const this_type &v)
Additional Inherited Members
Public Types inherited from ug::TE_Vector< IVector >
typedef IVector vector_type
Member Typedef Documentation
this_type
template<typename TVec > typedef IVector_AlgebraDownCastTo<TVec> ug::IVector_AlgebraDownCastTo< TVec >::this_type private
Member Function Documentation
downcast() [1/2]
template<typename TVec > TVec& ug::IVector_AlgebraDownCastTo< TVec >::downcast () inline private
Referenced by ug::IVector_AlgebraDownCastTo< TVec >::norm2(), ug::IVector_AlgebraDownCastTo< TVec >::print(), ug::IVector_AlgebraDownCastTo< TVec >::set(), ug::IVector_AlgebraDownCastTo< TVec >::short_desc(), ug::IVector_AlgebraDownCastTo< TVec >::vec_add(), and ug::IVector_AlgebraDownCastTo< TVec >::vec_prod().
downcast() [2/2]
template<typename TVec > const TVec& ug::IVector_AlgebraDownCastTo< TVec >::downcast () const inline private
norm2()
template<typename TVec > virtual double ug::IVector_AlgebraDownCastTo< TVec >::norm2 () const inline virtual
Implements ug::IVector.
References ug::IVector_AlgebraDownCastTo< TVec >::downcast(), and VecNorm2().
print()
template<typename TVec > virtual void ug::IVector_AlgebraDownCastTo< TVec >::print (std::ostream & output) const inline virtual
Implements ug::IVector.
References ug::IVector_AlgebraDownCastTo< TVec >::downcast(), and ug::IVector_AlgebraDownCastTo< TVec >::short_desc().
set()
template<typename TVec > virtual void ug::IVector_AlgebraDownCastTo< TVec >::set (double d) inline virtual
Implements ug::IVector.
References ug::IVector_AlgebraDownCastTo< TVec >::downcast().
short_desc()
template<typename TVec > virtual std::string ug::IVector_AlgebraDownCastTo< TVec >::short_desc () const inline virtual
Implements ug::IVector.
References ug::IVector_AlgebraDownCastTo< TVec >::downcast(), ug::IVector::size(), and ug::TypeName().
Referenced by ug::IVector_AlgebraDownCastTo< TVec >::print().
vec_add() [1/3]
template<typename TVec > virtual void ug::IVector_AlgebraDownCastTo< TVec >::vec_add (double a1, double a2, const IVector & iv2) inline virtual
Implements ug::IVector.
References ug::IVector::downcast(), ug::IVector_AlgebraDownCastTo< TVec >::downcast(), and ug::VecAdd().
vec_add() [2/3]
template<typename TVec > virtual void ug::IVector_AlgebraDownCastTo< TVec >::vec_add (double a1, double a2, const IVector & iv2, double a3, const IVector & iv3) inline virtual
Implements ug::IVector.
References ug::IVector::downcast(), ug::IVector_AlgebraDownCastTo< TVec >::downcast(), and ug::VecAdd().
vec_add() [3/3]
template<typename TVec > virtual void ug::IVector_AlgebraDownCastTo< TVec >::vec_add (double a1, double a2, const IVector & iv2, double a3, const IVector & iv3, double a4, const IVector & iv4) inline virtual
Implements ug::IVector.
References ug::IVector::downcast(), ug::IVector_AlgebraDownCastTo< TVec >::downcast(), and ug::VecAdd().
vec_prod()
template<typename TVec > virtual double ug::IVector_AlgebraDownCastTo< TVec >::vec_prod (const IVector & iv) const inline virtual
Implements ug::IVector.
References ug::IVector::downcast(), ug::IVector_AlgebraDownCastTo< TVec >::downcast(), and ug::VecProd().
Friends And Related Function Documentation
operator<<
template<typename TVec > std::ostream& operator<< (std::ostream & output, const this_type & v) friend
The documentation for this class was generated from the following file:
ugbase/lib_algebra/vector_interface/ivector.h