ug4: ug::BalanceWeightsLuaCallback< TDomain > Class Template Reference
ug::BalanceWeightsLuaCallback< TDomain > Class Template Reference
ugbase » Bridge » Domain Bridge » Load Balancing Bridge
Public Member Functions
BalanceWeightsLuaCallback (SmartPtr< TDomain > spDom, const char *luaCallbackName)
virtual number get_weight (Edge *e)
virtual number get_weight (Face *e)
virtual number get_weight (Vertex *e)
virtual number get_weight (Volume *e)
void set_time (number time)
number time () const
virtual ~BalanceWeightsLuaCallback ()
Public Member Functions inherited from ug::IBalanceWeights
virtual number get_refined_weight (Edge *e)
virtual number get_refined_weight (Face *e)
todo: use a more sophisticated implementation
virtual number get_refined_weight (Vertex *e)
virtual number get_refined_weight (Volume *e)
todo: use a more sophisticated implementation
virtual bool has_level_offsets ()
virtual void refresh_weights (int baseLevel)
virtual ~IBalanceWeights ()
virtual bool consider_in_level_above (Vertex *)
Relative indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Edge *)
Relative indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Face *)
Relative indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Volume *)
Relative indicator in which level the specifed elements should be partitioned.
Private Types
typedef TDomain::position_accessor_type aapos_t
typedef TDomain::grid_type grid_t
typedef TDomain::position_type pos_t
Private Member Functions
template<class TElem >
number get_weight_impl (TElem *e)
Private Attributes
aapos_t m_aaPos
LuaFunction< number, number > m_callback
MultiGrid * m_pmg
SmartPtr< TDomain > m_spDom
number m_time
Member Typedef Documentation
aapos_t
template<class TDomain > typedef TDomain::position_accessor_type ug::BalanceWeightsLuaCallback< TDomain >::aapos_t private
grid_t
template<class TDomain > typedef TDomain::grid_type ug::BalanceWeightsLuaCallback< TDomain >::grid_t private
pos_t
template<class TDomain > typedef TDomain::position_type ug::BalanceWeightsLuaCallback< TDomain >::pos_t private
Constructor & Destructor Documentation
BalanceWeightsLuaCallback()
template<class TDomain > ug::BalanceWeightsLuaCallback< TDomain >::BalanceWeightsLuaCallback (SmartPtr< TDomain > spDom, const char * luaCallbackName) inline
References SmartPtr< T, FreePolicy >::get().
~BalanceWeightsLuaCallback()
template<class TDomain > virtual ug::BalanceWeightsLuaCallback< TDomain >::~BalanceWeightsLuaCallback () inline virtual
Member Function Documentation
get_weight() [1/4]
template<class TDomain > virtual number ug::BalanceWeightsLuaCallback< TDomain >::get_weight (Edge * e) inline virtual
Reimplemented from ug::IBalanceWeights.
get_weight() [2/4]
template<class TDomain > virtual number ug::BalanceWeightsLuaCallback< TDomain >::get_weight (Face * e) inline virtual
Reimplemented from ug::IBalanceWeights.
get_weight() [3/4]
template<class TDomain > virtual number ug::BalanceWeightsLuaCallback< TDomain >::get_weight (Vertex * e) inline virtual
Reimplemented from ug::IBalanceWeights.
get_weight() [4/4]
template<class TDomain > virtual number ug::BalanceWeightsLuaCallback< TDomain >::get_weight (Volume * e) inline virtual
Reimplemented from ug::IBalanceWeights.
get_weight_impl()
template<class TDomain > template<class TElem > number ug::BalanceWeightsLuaCallback< TDomain >::get_weight_impl (TElem * e) inline private
References ug::CalculateCenter(), p, and ug::VecCopy().
set_time()
template<class TDomain > void ug::BalanceWeightsLuaCallback< TDomain >::set_time (number time) inline
time()
template<class TDomain > number ug::BalanceWeightsLuaCallback< TDomain >::time () const inline
Member Data Documentation
m_aaPos
template<class TDomain > aapos_t ug::BalanceWeightsLuaCallback< TDomain >::m_aaPos private
m_callback
template<class TDomain > LuaFunction<number, number> ug::BalanceWeightsLuaCallback< TDomain >::m_callback private
m_pmg
template<class TDomain > MultiGrid* ug::BalanceWeightsLuaCallback< TDomain >::m_pmg private
m_spDom
template<class TDomain > SmartPtr<TDomain> ug::BalanceWeightsLuaCallback< TDomain >::m_spDom private
m_time
template<class TDomain > number ug::BalanceWeightsLuaCallback< TDomain >::m_time private
The documentation for this class was generated from the following file:
ugbase/bridge/domain_bridges/load_balancing_bridge.cpp