ug4: ug::MathVector< 4, T > Class Template Reference
ug::MathVector< 4, T > Class Template Reference
ugbase » Math » Vectors
#include <math_vector.h>
Public Types
typedef std::size_t size_type
typedef T value_type
Public Member Functions
value_type & coord (std::size_t index)
value_type coord (std::size_t index) const
MathVector ()
MathVector (const MathVector< 4, T > &v)
MathVector (const value_type &val)
MathVector (value_type x, value_type y, value_type z, value_type w)
value_type operator* (const MathVector &v) const
MathVector & operator*= (const value_type &val)
MathVector & operator+= (const MathVector &v)
MathVector & operator+= (const value_type &val)
MathVector operator- () const
MathVector & operator-= (const MathVector &v)
MathVector & operator-= (const value_type &val)
MathVector & operator/= (const value_type &val)
MathVector & operator= (const MathVector &v)
MathVector & operator= (const value_type &val)
value_type & operator[] (std::size_t index)
const value_type & operator[] (std::size_t index) const
void set_coord (std::size_t index, value_type v)
std::size_t size () const
value_type & w ()
const value_type & w () const
value_type & x ()
const value_type & x () const
value_type & y ()
const value_type & y () const
value_type & z ()
const value_type & z () const
Static Public Member Functions
static MathVector from (const MathVector< 0, T > &v)
static MathVector from (const MathVector< 1, T > &v)
static MathVector from (const MathVector< 2, T > &v)
static MathVector from (const MathVector< 3, T > &v)
static MathVector from (const MathVector< 4, T > &v)
template<std::size_t fromN>
static MathVector from (const MathVector< fromN, T > &v)
Public Attributes
value_type m_data [4]
Static Public Attributes
static const std::size_t Size = 4
Protected Member Functions
void assign (const MathVector< 4, T > &v)
Detailed Description
template<typename T>
class ug::MathVector< 4, T >
A mathematical Vector with 4 entries and static storage
Member Typedef Documentation
size_type
template<typename T > typedef std::size_t ug::MathVector< 4, T >::size_type
value_type
template<typename T > typedef T ug::MathVector< 4, T >::value_type
Constructor & Destructor Documentation
MathVector() [1/4]
template<typename T > ug::MathVector< 4, T >::MathVector () inline
References ug::MathVector< N, T >::m_data.
MathVector() [2/4]
template<typename T > ug::MathVector< 4, T >::MathVector (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
MathVector() [3/4]
template<typename T > ug::MathVector< 4, T >::MathVector (value_type x, value_type y, value_type z, value_type w) inline
References ug::MathVector< N, T >::m_data.
MathVector() [4/4]
template<typename T > ug::MathVector< 4, T >::MathVector (const MathVector< 4, T > & v) inline
References ug::MathVector< N, T >::assign().
Member Function Documentation
assign()
template<typename T > void ug::MathVector< 4, T >::assign (const MathVector< 4, T > & v) inline protected
References m_data, and ug::MathVector< N, T >::m_data.
coord() [1/2]
template<typename T > value_type& ug::MathVector< 4, T >::coord (std::size_t index) inline
References ug::MathVector< N, T >::m_data.
coord() [2/2]
template<typename T > value_type ug::MathVector< 4, T >::coord (std::size_t index) const inline
References ug::MathVector< N, T >::m_data.
from() [1/6]
template<typename T > static MathVector ug::MathVector< 4, T >::from (const MathVector< 0, T > & v) inline static
References ug::MathVector< N, T >::MathVector().
from() [2/6]
template<typename T > static MathVector ug::MathVector< 4, T >::from (const MathVector< 1, T > & v) inline static
References ug::MathVector< N, T >::MathVector().
from() [3/6]
template<typename T > static MathVector ug::MathVector< 4, T >::from (const MathVector< 2, T > & v) inline static
References ug::MathVector< N, T >::MathVector().
from() [4/6]
template<typename T > static MathVector ug::MathVector< 4, T >::from (const MathVector< 3, T > & v) inline static
References ug::MathVector< N, T >::MathVector().
from() [5/6]
template<typename T > static MathVector ug::MathVector< 4, T >::from (const MathVector< 4, T > & v) inline static
from() [6/6]
template<typename T > template<std::size_t fromN> static MathVector ug::MathVector< 4, T >::from (const MathVector< fromN, T > & v) inline static
operator*()
template<typename T > value_type ug::MathVector< 4, T >::operator* (const MathVector< 4, T > & v) const inline
References ug::MathVector< N, T >::coord(), and ug::MathVector< N, T >::m_data.
operator*=()
template<typename T > MathVector& ug::MathVector< 4, T >::operator*= (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
operator+=() [1/2]
template<typename T > MathVector& ug::MathVector< 4, T >::operator+= (const MathVector< 4, T > & v) inline
References ug::MathVector< N, T >::coord(), and ug::MathVector< N, T >::m_data.
operator+=() [2/2]
template<typename T > MathVector& ug::MathVector< 4, T >::operator+= (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
operator-()
template<typename T > MathVector ug::MathVector< 4, T >::operator- () const inline
References ug::MathVector< N, T >::m_data.
operator-=() [1/2]
template<typename T > MathVector& ug::MathVector< 4, T >::operator-= (const MathVector< 4, T > & v) inline
References ug::MathVector< N, T >::coord(), and ug::MathVector< N, T >::m_data.
operator-=() [2/2]
template<typename T > MathVector& ug::MathVector< 4, T >::operator-= (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
operator/=()
template<typename T > MathVector& ug::MathVector< 4, T >::operator/= (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
operator=() [1/2]
template<typename T > MathVector& ug::MathVector< 4, T >::operator= (const MathVector< 4, T > & v) inline
References ug::MathVector< N, T >::assign().
operator=() [2/2]
template<typename T > MathVector& ug::MathVector< 4, T >::operator= (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
operator[]() [1/2]
template<typename T > value_type& ug::MathVector< 4, T >::operator[] (std::size_t index) inline
References ug::MathVector< N, T >::m_data.
operator[]() [2/2]
template<typename T > const value_type& ug::MathVector< 4, T >::operator[] (std::size_t index) const inline
References ug::MathVector< N, T >::m_data.
set_coord()
template<typename T > void ug::MathVector< 4, T >::set_coord (std::size_t index, value_type v) inline
References ug::MathVector< N, T >::m_data.
size()
template<typename T > std::size_t ug::MathVector< 4, T >::size () const inline
w() [1/2]
template<typename T > value_type& ug::MathVector< 4, T >::w () inline
References ug::MathVector< N, T >::m_data.
w() [2/2]
template<typename T > const value_type& ug::MathVector< 4, T >::w () const inline
References ug::MathVector< N, T >::m_data.
x() [1/2]
template<typename T > value_type& ug::MathVector< 4, T >::x () inline
References ug::MathVector< N, T >::m_data.
x() [2/2]
template<typename T > const value_type& ug::MathVector< 4, T >::x () const inline
References ug::MathVector< N, T >::m_data.
y() [1/2]
template<typename T > value_type& ug::MathVector< 4, T >::y () inline
References ug::MathVector< N, T >::m_data.
y() [2/2]
template<typename T > const value_type& ug::MathVector< 4, T >::y () const inline
References ug::MathVector< N, T >::m_data.
z() [1/2]
template<typename T > value_type& ug::MathVector< 4, T >::z () inline
References ug::MathVector< N, T >::m_data.
z() [2/2]
template<typename T > const value_type& ug::MathVector< 4, T >::z () const inline
References ug::MathVector< N, T >::m_data.
Member Data Documentation
m_data
template<typename T > value_type ug::MathVector< 4, T >::m_data[4]
Referenced by assign().
Size
template<typename T > const std::size_t ug::MathVector< 4, T >::Size = 4 static
The documentation for this class was generated from the following file:
ugbase/common/math/math_vector_matrix/math_vector.h