ug4: ug::FV1Geometry< TElem, TWorldDim > Class Template Reference
ug::FV1Geometry< TElem, TWorldDim > Class Template Reference
Geometry and shape functions for 1st order Vertex-Centered Finite Volume.
#include <fv1_geom.h>
Classes
class BF
boundary face
class SCV
sub control volume structure
class SCVF
Sub-Control Volume Face structure.
Public Types
typedef TElem elem_type
type of element
typedef LagrangeP1< ref_elem_type > local_shape_fct_set_type
type of Shape function used
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
type of reference element
typedef traits::scv_type scv_type
type of SubControlVolume
typedef fv1_traits< ref_elem_type, TWorldDim > traits
used traits
Public Member Functions
void add_boundary_subset (int subsetIndex)
add subset that is interpreted as boundary subset.
const BF & bf (int si, size_t i) const
returns the boundary face i for subsetIndex
const std::vector< BF > & bf (int si) const
returns reference to vector of boundary faces for subsetIndex
void clear_boundary_subsets ()
reset all boundary subsets
const MathVector< worldDim > * coe_global () const
returns the global coordinates of the center of mass of the element
const MathVector< dim > * coe_local () const
returns the local coordinates of the center of mass of the element
const MathVector< worldDim > * corners () const
get vector of the global coordinates of corners for current element
TElem * elem () const
get the element
FV1Geometry ()
construct object and initialize local values and sizes
size_t num_bf () const
number of all boundary faces
size_t num_bf (int si) const
number of boundary faces on subset 'subsetIndex'
size_t num_boundary_subsets ()
number of registered boundary subsets
size_t num_scv () const
number of SubControlVolumes
size_t num_scv_ips () const
returns number of all scv ips
size_t num_scvf () const
number of SubControlVolumeFaces
size_t num_scvf_ips () const
returns number of all scvf ips
size_t num_sh () const
number of shape functions
void remove_boundary_subset (int subsetIndex)
removes subset that is interpreted as boundary subset.
void reset_curr_elem ()
ReferenceObjectID roid () const
returns reference object id
const SCV & scv (size_t i) const
const access to SubControlVolume number i
const MathVector< worldDim > * scv_global_ips () const
returns all ips of scv as they appear in scv loop
const MathVector< dim > * scv_local_ips () const
returns all ips of scv as they appear in scv loop
const SCVF & scvf (size_t i) const
const access to SubControlVolumeFace number i
const MathVector< worldDim > * scvf_global_ips () const
returns all ips of scvf as they appear in scv loop
const MathVector< dim > * scvf_local_ips () const
returns all ips of scvf as they appear in scv loop
void update (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update data for given element
void update_boundary_faces (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update boundary data for given element
void update_local_data ()
update local data
Static Public Attributes
static const int dim = ref_elem_type::dim
dimension of reference element
static const size_t nip = 1
number of integration points
static const size_t nsh = local_shape_fct_set_type::nsh
number of shape functions
static const size_t numSCV
number of SubControlVolumes
static const size_t numSCVF
number of SubControlVolumeFaces
static const int order = 1
order
static const bool staticLocalData = true
flag indicating if local data may change
static const bool usesHangingNodes = false
Hanging node flag: this Geometry does not support hanging nodes.
static const int worldDim = TWorldDim
dimension of world
Protected Attributes
std::map< int, std::vector< BF > > m_mapVectorBF
std::vector< BF > m_vEmptyVectorBF
MathVector< worldDim > m_vGlobSCV_IP [numSCV]
MathVector< worldDim > m_vGlobSCVF_IP [numSCVF]
MathVector< dim > m_vLocSCV_IP [numSCV]
MathVector< dim > m_vLocSCVF_IP [numSCVF]
Private Attributes
ReferenceMapping< ref_elem_type, worldDim > m_mapping
Reference Mapping.
TElem * m_pElem
pointer to current element
const ref_elem_type & m_rRefElem
Reference Element.
const local_shape_fct_set_type & m_rTrialSpace
Shape function set.
SCV m_vSCV [numSCV]
SubControlVolumes.
SCVF m_vSCVF [numSCVF]
SubControlVolumeFaces.
MathVector< worldDim > m_vvGloMid [dim+1][maxMid]
MathVector< dim > m_vvLocMid [dim+1][maxMid]
local and global geom object midpoints for each dimension
Static Private Attributes
static const int maxMid = numSCVF + 1
max number of geom objects in all dimensions
Detailed Description
template<typename TElem, int TWorldDim>
class ug::FV1Geometry< TElem, TWorldDim >
Geometry and shape functions for 1st order Vertex-Centered Finite Volume.
Template Parameters
TElem Element type
TWorldDim (physical) world dimension
Member Typedef Documentation
template<typename TElem , int TWorldDim> typedef TElem ug::FV1Geometry< TElem, TWorldDim >::elem_type
type of element
template<typename TElem , int TWorldDim> typedef LagrangeP1<ref_elem_type> ug::FV1Geometry< TElem, TWorldDim >::local_shape_fct_set_type
type of Shape function used
template<typename TElem , int TWorldDim> typedef reference_element_traits<TElem>::reference_element_type ug::FV1Geometry< TElem, TWorldDim >::ref_elem_type
type of reference element
template<typename TElem , int TWorldDim> typedef traits::scv_type ug::FV1Geometry< TElem, TWorldDim >::scv_type
type of SubControlVolume
template<typename TElem , int TWorldDim> typedef fv1_traits<ref_elem_type, TWorldDim> ug::FV1Geometry< TElem, TWorldDim >::traits
used traits
Constructor & Destructor Documentation
template<typename TElem , int TWorldDim> ug::FV1Geometry< TElem, TWorldDim >::FV1Geometry ()
construct object and initialize local values and sizes
References ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
Referenced by ug::CopyCornerByMidID().
Member Function Documentation
template<typename TElem , int TWorldDim> void ug::FV1Geometry< TElem, TWorldDim >::add_boundary_subset (int subsetIndex) inline
add subset that is interpreted as boundary subset.
References ug::FV1Geometry< TElem, TWorldDim >::m_mapVectorBF.
template<typename TElem , int TWorldDim> const BF& ug::FV1Geometry< TElem, TWorldDim >::bf (int si, size_t i) const inline
returns the boundary face i for subsetIndex
References ug::FV1Geometry< TElem, TWorldDim >::m_mapVectorBF, ug::FV1Geometry< TElem, TWorldDim >::num_bf(), UG_ASSERT, and UG_THROW.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces(), and ug::DimFV1Geometry< TDim, TWorldDim >::update_boundary_faces().
template<typename TElem , int TWorldDim> const std::vector<BF>& ug::FV1Geometry< TElem, TWorldDim >::bf (int si) const inline
returns reference to vector of boundary faces for subsetIndex
References ug::FV1Geometry< TElem, TWorldDim >::m_mapVectorBF, and ug::FV1Geometry< TElem, TWorldDim >::m_vEmptyVectorBF.
template<typename TElem , int TWorldDim> void ug::FV1Geometry< TElem, TWorldDim >::clear_boundary_subsets () inline
reset all boundary subsets
References ug::FV1Geometry< TElem, TWorldDim >::m_mapVectorBF.
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::FV1Geometry< TElem, TWorldDim >::coe_global () const inline
returns the global coordinates of the center of mass of the element
References ug::FV1Geometry< TElem, TWorldDim >::dim, and ug::FV1Geometry< TElem, TWorldDim >::m_vvGloMid.
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::FV1Geometry< TElem, TWorldDim >::coe_local () const inline
returns the local coordinates of the center of mass of the element
References ug::FV1Geometry< TElem, TWorldDim >::dim, and ug::FV1Geometry< TElem, TWorldDim >::m_vvLocMid.
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::FV1Geometry< TElem, TWorldDim >::corners () const inline
get vector of the global coordinates of corners for current element
References ug::FV1Geometry< TElem, TWorldDim >::m_vvGloMid.
template<typename TElem , int TWorldDim> TElem* ug::FV1Geometry< TElem, TWorldDim >::elem () const inline
get the element
References ug::FV1Geometry< TElem, TWorldDim >::m_pElem.
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::DimFV1Geometry(), ug::FV1Geometry< TElem, TWorldDim >::update(), and ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces().
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::num_bf () const inline
number of all boundary faces
References ug::FV1Geometry< TElem, TWorldDim >::m_mapVectorBF.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::bf(), and ug::FV1ManifoldGeometry< TElem, TWorldDim >::bf().
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::num_bf (int si) const inline
number of boundary faces on subset 'subsetIndex'
References ug::FV1Geometry< TElem, TWorldDim >::m_mapVectorBF.
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::num_boundary_subsets () inline
number of registered boundary subsets
References ug::FV1Geometry< TElem, TWorldDim >::m_mapVectorBF.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::num_scv () const inline
number of SubControlVolumes
References ug::FV1Geometry< TElem, TWorldDim >::numSCV.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::scv(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::FV1Geometry< TElem, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::num_scv_ips () const inline
returns number of all scv ips
References ug::FV1Geometry< TElem, TWorldDim >::numSCV.
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::num_scvf () const inline
number of SubControlVolumeFaces
References ug::FV1Geometry< TElem, TWorldDim >::numSCVF.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::scvf(), ug::DimFV1Geometry< TDim, TWorldDim >::scvf(), ug::FV1Geometry< TElem, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::num_scvf_ips () const inline
returns number of all scvf ips
References ug::FV1Geometry< TElem, TWorldDim >::numSCVF.
template<typename TElem , int TWorldDim> size_t ug::FV1Geometry< TElem, TWorldDim >::num_sh () const inline
number of shape functions
References ug::FV1Geometry< TElem, TWorldDim >::nsh.
template<typename TElem , int TWorldDim> void ug::FV1Geometry< TElem, TWorldDim >::remove_boundary_subset (int subsetIndex) inline
removes subset that is interpreted as boundary subset.
References ug::FV1Geometry< TElem, TWorldDim >::m_mapVectorBF.
template<typename TElem , int TWorldDim> void ug::FV1Geometry< TElem, TWorldDim >::reset_curr_elem () inline
References ug::FV1Geometry< TElem, TWorldDim >::m_pElem.
template<typename TElem , int TWorldDim> ReferenceObjectID ug::FV1Geometry< TElem, TWorldDim >::roid () const inline
returns reference object id
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::roid(), and ug::DimFV1Geometry< TDim, TWorldDim >::update_local().
template<typename TElem , int TWorldDim> const SCV& ug::FV1Geometry< TElem, TWorldDim >::scv (size_t i) const inline
const access to SubControlVolume number i
References ug::FV1Geometry< TElem, TWorldDim >::m_vSCV, ug::FV1Geometry< TElem, TWorldDim >::num_scv(), and UG_ASSERT.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::FV1Geometry< TElem, TWorldDim >::scv_global_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::FV1Geometry< TElem, TWorldDim >::m_vGlobSCV_IP, ug::FV1Geometry< TElem, TWorldDim >::m_vvGloMid, ug::ROID_OCTAHEDRON, and ug::ROID_PYRAMID.
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::FV1Geometry< TElem, TWorldDim >::scv_local_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::FV1Geometry< TElem, TWorldDim >::m_vLocSCV_IP, ug::FV1Geometry< TElem, TWorldDim >::m_vvLocMid, ug::ROID_OCTAHEDRON, and ug::ROID_PYRAMID.
template<typename TElem , int TWorldDim> const SCVF& ug::FV1Geometry< TElem, TWorldDim >::scvf (size_t i) const inline
const access to SubControlVolumeFace number i
References ug::FV1Geometry< TElem, TWorldDim >::m_vSCVF, ug::FV1Geometry< TElem, TWorldDim >::num_scvf(), and UG_ASSERT.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::FV1Geometry< TElem, TWorldDim >::scvf_global_ips () const inline
returns all ips of scvf as they appear in scv loop
References ug::FV1Geometry< TElem, TWorldDim >::m_vGlobSCVF_IP.
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::FV1Geometry< TElem, TWorldDim >::scvf_local_ips () const inline
returns all ips of scvf as they appear in scv loop
References ug::FV1Geometry< TElem, TWorldDim >::m_vLocSCVF_IP.
template<typename TElem , int TWorldDim> void ug::FV1Geometry< TElem, TWorldDim >::update (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update data for given element
References ug::AveragePositions(), ug::FV1Geometry< TElem, TWorldDim >::SCVF::detj, ug::FV1Geometry< TElem, TWorldDim >::SCV::detj, ug::DID_FV1_GEOM, ug::FV1Geometry< TElem, TWorldDim >::elem(), ug::FV1Geometry< TElem, TWorldDim >::SCVF::global_ip(), ug::FV1Geometry< TElem, TWorldDim >::SCV::global_ip(), ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::FV1Geometry< TElem, TWorldDim >::SCVF::JtInv, ug::FV1Geometry< TElem, TWorldDim >::SCV::JtInv, ug::FV1Geometry< TElem, TWorldDim >::m_mapping, ug::FV1Geometry< TElem, TWorldDim >::m_pElem, ug::FV1Geometry< TElem, TWorldDim >::m_rRefElem, ug::FV1Geometry< TElem, TWorldDim >::m_vGlobSCV_IP, ug::FV1Geometry< TElem, TWorldDim >::m_vGlobSCVF_IP, ug::FV1Geometry< TElem, TWorldDim >::m_vSCV, ug::FV1Geometry< TElem, TWorldDim >::m_vSCVF, ug::FV1Geometry< TElem, TWorldDim >::m_vvGloMid, ug::MatVecMult(), ug::FV1Geometry< TElem, TWorldDim >::SCV::midId, ug::fv1_traits< TRefElem, TWorldDim >::NormalOnSCVF(), ug::FV1Geometry< TElem, TWorldDim >::num_boundary_subsets(), ug::FV1Geometry< TElem, TWorldDim >::SCV::num_corners(), ug::FV1Geometry< TElem, TWorldDim >::num_scv(), ug::FV1Geometry< TElem, TWorldDim >::num_scvf(), ug::FV1Geometry< TElem, TWorldDim >::SCVF::num_sh(), ug::FV1Geometry< TElem, TWorldDim >::SCV::num_sh(), ug::FV1Geometry< TElem, TWorldDim >::SCVF::numCo, ug::ROID_OCTAHEDRON, ug::ROID_PYRAMID, ug::FV1Geometry< TElem, TWorldDim >::scv(), ug::FV1Geometry< TElem, TWorldDim >::scvf(), ug::ReferenceMapping< TRefElem, TWorldDim >::sqrt_gram_det(), UG_ASSERT, UG_DLOG, ug::ReferenceMapping< TRefElem, TWorldDim >::update(), ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces(), ug::VecLength(), ug::FV1Geometry< TElem, TWorldDim >::SCVF::vGloPos, ug::FV1Geometry< TElem, TWorldDim >::SCV::vGloPos, ug::FV1Geometry< TElem, TWorldDim >::SCV::vLocPos, ug::FV1Geometry< TElem, TWorldDim >::SCVF::vMidID, and ug::FV1Geometry< TElem, TWorldDim >::SCV::Vol.
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::DimFV1Geometry(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> void ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update boundary data for given element
References ug::AveragePositions(), ug::FV1Geometry< TElem, TWorldDim >::bf(), ug::CollectEdgesSorted(), ug::CollectFacesSorted(), ug::CollectVertices(), ug::ComputeBFMidID(), ug::FV1Geometry< TElem, TWorldDim >::BF::detj, ug::FV1Geometry< TElem, TWorldDim >::dim, ug::FV1Geometry< TElem, TWorldDim >::elem(), ug::ISubsetHandler::get_subset_index(), ug::FV1Geometry< TElem, TWorldDim >::BF::globalIP, ug::BaseLSFS< TImpl, TDim, TShape, TGrad >::grads(), ug::ISubsetHandler::grid(), ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::FV1Geometry< TElem, TWorldDim >::BF::JtInv, ug::FV1Geometry< TElem, TWorldDim >::BF::localIP, ug::FV1Geometry< TElem, TWorldDim >::m_mapping, ug::FV1Geometry< TElem, TWorldDim >::m_mapVectorBF, ug::FV1Geometry< TElem, TWorldDim >::m_rRefElem, ug::FV1Geometry< TElem, TWorldDim >::m_rTrialSpace, ug::FV1Geometry< TElem, TWorldDim >::m_vvGloMid, ug::FV1Geometry< TElem, TWorldDim >::m_vvLocMid, ug::MatVecMult(), ug::FV1Geometry< TElem, TWorldDim >::BF::nodeId, ug::FV1Geometry< TElem, TWorldDim >::BF::Normal, ug::fv1_traits< TRefElem, TWorldDim >::NormalOnBF(), ug::FV1Geometry< TElem, TWorldDim >::BF::num_sh(), ug::FV1Geometry< TElem, TWorldDim >::BF::numCo, ug::BaseLSFS< TImpl, TDim, TShape, TGrad >::shapes(), ug::ReferenceMapping< TRefElem, TWorldDim >::sqrt_gram_det(), UG_ASSERT, ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), ug::VecTwoNorm(), ug::FV1Geometry< TElem, TWorldDim >::BF::vGlobalGrad, ug::FV1Geometry< TElem, TWorldDim >::BF::vGloPos, ug::FV1Geometry< TElem, TWorldDim >::BF::vLocalGrad, ug::FV1Geometry< TElem, TWorldDim >::BF::vLocPos, ug::FV1Geometry< TElem, TWorldDim >::BF::vMidID, ug::FV1Geometry< TElem, TWorldDim >::BF::Vol, and ug::FV1Geometry< TElem, TWorldDim >::BF::vShape.
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::DimFV1Geometry(), ug::FV1Geometry< TElem, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> void ug::FV1Geometry< TElem, TWorldDim >::update_local_data ()
update local data
References ug::AveragePositions(), ug::ComputeSCVFMidID(), ug::ComputeSCVMidID(), ug::DID_FV1_GEOM, ug::FV1Geometry< TElem, TWorldDim >::SCVF::From, ug::BaseLSFS< TImpl, TDim, TShape, TGrad >::grads(), ug::FV1Geometry< TElem, TWorldDim >::SCVF::local_ip(), ug::FV1Geometry< TElem, TWorldDim >::SCV::local_ip(), ug::FV1Geometry< TElem, TWorldDim >::m_rRefElem, ug::FV1Geometry< TElem, TWorldDim >::m_rTrialSpace, ug::FV1Geometry< TElem, TWorldDim >::m_vLocSCV_IP, ug::FV1Geometry< TElem, TWorldDim >::m_vLocSCVF_IP, ug::FV1Geometry< TElem, TWorldDim >::m_vSCV, ug::FV1Geometry< TElem, TWorldDim >::m_vSCVF, ug::FV1Geometry< TElem, TWorldDim >::m_vvLocMid, ug::FV1Geometry< TElem, TWorldDim >::SCV::midId, ug::FV1Geometry< TElem, TWorldDim >::SCV::nodeId, ug::FV1Geometry< TElem, TWorldDim >::SCV::num_corners(), ug::FV1Geometry< TElem, TWorldDim >::num_scv(), ug::FV1Geometry< TElem, TWorldDim >::num_scvf(), ug::FV1Geometry< TElem, TWorldDim >::SCVF::numCo, ug::ROID_OCTAHEDRON, ug::ROID_PYRAMID, ug::FV1Geometry< TElem, TWorldDim >::scv(), ug::FV1Geometry< TElem, TWorldDim >::scvf(), ug::BaseLSFS< TImpl, TDim, TShape, TGrad >::shapes(), ug::FV1Geometry< TElem, TWorldDim >::SCVF::To, UG_DLOG, ug::FV1Geometry< TElem, TWorldDim >::update(), ug::FV1Geometry< TElem, TWorldDim >::SCVF::vLocPos, ug::FV1Geometry< TElem, TWorldDim >::SCV::vLocPos, and ug::FV1Geometry< TElem, TWorldDim >::SCVF::vMidID.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::FV1Geometry().
Member Data Documentation
template<typename TElem , int TWorldDim> const int ug::FV1Geometry< TElem, TWorldDim >::dim = ref_elem_type::dim static
dimension of reference element
Referenced by ug::FV1Geometry< TElem, TWorldDim >::coe_global(), ug::DimFV1Geometry< TDim, TWorldDim >::coe_global(), ug::FV1Geometry< TElem, TWorldDim >::coe_local(), ug::DimFV1Geometry< TDim, TWorldDim >::coe_local(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_global_corners(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::copy_local_corners(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::MidID::MidID(), ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces(), ug::DimFV1Geometry< TDim, TWorldDim >::update_boundary_faces(), and ug::DimFV1Geometry< TDim, TWorldDim >::update_local().
template<typename TElem , int TWorldDim> ReferenceMapping<ref_elem_type, worldDim> ug::FV1Geometry< TElem, TWorldDim >::m_mapping private
Reference Mapping.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::update(), and ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces().
template<typename TElem , int TWorldDim> std::map<int, std::vector<BF> > ug::FV1Geometry< TElem, TWorldDim >::m_mapVectorBF protected
Referenced by ug::FV1Geometry< TElem, TWorldDim >::add_boundary_subset(), ug::DimFV1Geometry< TDim, TWorldDim >::add_boundary_subset(), ug::FV1Geometry< TElem, TWorldDim >::bf(), ug::DimFV1Geometry< TDim, TWorldDim >::bf(), ug::FV1Geometry< TElem, TWorldDim >::clear_boundary_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::clear_boundary_subsets(), ug::FV1Geometry< TElem, TWorldDim >::num_bf(), ug::DimFV1Geometry< TDim, TWorldDim >::num_bf(), ug::FV1Geometry< TElem, TWorldDim >::num_boundary_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::num_boundary_subsets(), ug::FV1Geometry< TElem, TWorldDim >::remove_boundary_subset(), ug::DimFV1Geometry< TDim, TWorldDim >::remove_boundary_subset(), ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces(), and ug::DimFV1Geometry< TDim, TWorldDim >::update_boundary_faces().
template<typename TElem , int TWorldDim> TElem* ug::FV1Geometry< TElem, TWorldDim >::m_pElem private
pointer to current element
Referenced by ug::FV1Geometry< TElem, TWorldDim >::elem(), ug::DimFV1Geometry< TDim, TWorldDim >::elem(), ug::FV1ManifoldGeometry< TElem, TWorldDim >::elem(), ug::FV1Geometry< TElem, TWorldDim >::reset_curr_elem(), ug::FV1Geometry< TElem, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> const ref_elem_type& ug::FV1Geometry< TElem, TWorldDim >::m_rRefElem private
Reference Element.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::update(), ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const local_shape_fct_set_type& ug::FV1Geometry< TElem, TWorldDim >::m_rTrialSpace private
Shape function set.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> std::vector<BF> ug::FV1Geometry< TElem, TWorldDim >::m_vEmptyVectorBF protected
Referenced by ug::FV1Geometry< TElem, TWorldDim >::bf(), and ug::DimFV1Geometry< TDim, TWorldDim >::bf().
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1Geometry< TElem, TWorldDim >::m_vGlobSCV_IP[numSCV] protected
Referenced by ug::FV1Geometry< TElem, TWorldDim >::scv_global_ips(), ug::DimFV1Geometry< TDim, TWorldDim >::scv_global_ips(), ug::FV1Geometry< TElem, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1Geometry< TElem, TWorldDim >::m_vGlobSCVF_IP[numSCVF] protected
Referenced by ug::FV1Geometry< TElem, TWorldDim >::scvf_global_ips(), ug::DimFV1Geometry< TDim, TWorldDim >::scvf_global_ips(), ug::FV1Geometry< TElem, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1Geometry< TElem, TWorldDim >::m_vLocSCV_IP[numSCV] protected
Referenced by ug::FV1Geometry< TElem, TWorldDim >::scv_local_ips(), ug::DimFV1Geometry< TDim, TWorldDim >::scv_local_ips(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1Geometry< TElem, TWorldDim >::m_vLocSCVF_IP[numSCVF] protected
Referenced by ug::FV1Geometry< TElem, TWorldDim >::scvf_local_ips(), ug::DimFV1Geometry< TDim, TWorldDim >::scvf_local_ips(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> SCV ug::FV1Geometry< TElem, TWorldDim >::m_vSCV[numSCV] private
SubControlVolumes.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::scv(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::FV1Geometry< TElem, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> SCVF ug::FV1Geometry< TElem, TWorldDim >::m_vSCVF[numSCVF] private
SubControlVolumeFaces.
Referenced by ug::FV1Geometry< TElem, TWorldDim >::scvf(), ug::DimFV1Geometry< TDim, TWorldDim >::scvf(), ug::FV1Geometry< TElem, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1Geometry< TElem, TWorldDim >::m_vvGloMid[dim+1][maxMid] private
Referenced by ug::FV1Geometry< TElem, TWorldDim >::coe_global(), ug::DimFV1Geometry< TDim, TWorldDim >::coe_global(), ug::FV1Geometry< TElem, TWorldDim >::corners(), ug::DimFV1Geometry< TDim, TWorldDim >::corners(), ug::FV1Geometry< TElem, TWorldDim >::scv_global_ips(), ug::DimFV1Geometry< TDim, TWorldDim >::scv_global_ips(), ug::FV1Geometry< TElem, TWorldDim >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces(), and ug::DimFV1Geometry< TDim, TWorldDim >::update_boundary_faces().
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1Geometry< TElem, TWorldDim >::m_vvLocMid[dim+1][maxMid] private
local and global geom object midpoints for each dimension
Referenced by ug::FV1Geometry< TElem, TWorldDim >::coe_local(), ug::DimFV1Geometry< TDim, TWorldDim >::coe_local(), ug::FV1Geometry< TElem, TWorldDim >::scv_local_ips(), ug::DimFV1Geometry< TDim, TWorldDim >::scv_local_ips(), ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces(), ug::DimFV1Geometry< TDim, TWorldDim >::update_boundary_faces(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), and ug::FV1Geometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const int ug::FV1Geometry< TElem, TWorldDim >::maxMid = numSCVF + 1 static private
max number of geom objects in all dimensions
Referenced by ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::update_local().
template<typename TElem , int TWorldDim> const size_t ug::FV1Geometry< TElem, TWorldDim >::nip = 1 static
number of integration points
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::num_ip(), ug::FV1Geometry< TElem, TWorldDim >::SCV::num_ip(), ug::FV1Geometry< TElem, TWorldDim >::BF::num_ip(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::num_ip(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::num_ip(), and ug::DimFV1Geometry< TDim, TWorldDim >::BF::num_ip().
template<typename TElem , int TWorldDim> const size_t ug::FV1Geometry< TElem, TWorldDim >::nsh = local_shape_fct_set_type::nsh static
number of shape functions
Referenced by ug::FV1Geometry< TElem, TWorldDim >::SCVF::num_sh(), ug::FV1Geometry< TElem, TWorldDim >::SCV::num_sh(), ug::FV1Geometry< TElem, TWorldDim >::BF::num_sh(), and ug::FV1Geometry< TElem, TWorldDim >::num_sh().
template<typename TElem , int TWorldDim> const size_t ug::FV1Geometry< TElem, TWorldDim >::numSCV static
Initial value:
= (ref_elem_type::REFERENCE_OBJECT_ID == ROID_PYRAMID || ref_elem_type::REFERENCE_OBJECT_ID == ROID_OCTAHEDRON)
                   ? ((ref_elem_type::REFERENCE_OBJECT_ID == ROID_PYRAMID) ? (4*ref_elem_type::numEdges) : 16) : ref_elem_type::numCorners
number of SubControlVolumes
Referenced by ug::FV1Geometry< TElem, TWorldDim >::num_scv(), and ug::FV1Geometry< TElem, TWorldDim >::num_scv_ips().
template<typename TElem , int TWorldDim> const size_t ug::FV1Geometry< TElem, TWorldDim >::numSCVF static
Initial value:
= (ref_elem_type::REFERENCE_OBJECT_ID == ROID_PYRAMID || ref_elem_type::REFERENCE_OBJECT_ID == ROID_OCTAHEDRON)
                  ? ((ref_elem_type::REFERENCE_OBJECT_ID == ROID_PYRAMID) ? (2*ref_elem_type::numEdges) : 24) : ref_elem_type::numEdges
number of SubControlVolumeFaces
Referenced by ug::FV1Geometry< TElem, TWorldDim >::num_scvf(), and ug::FV1Geometry< TElem, TWorldDim >::num_scvf_ips().
template<typename TElem , int TWorldDim> const int ug::FV1Geometry< TElem, TWorldDim >::order = 1 static
order
template<typename TElem , int TWorldDim> const bool ug::FV1Geometry< TElem, TWorldDim >::staticLocalData = true static
flag indicating if local data may change
template<typename TElem , int TWorldDim> const bool ug::FV1Geometry< TElem, TWorldDim >::usesHangingNodes = false static
Hanging node flag: this Geometry does not support hanging nodes.
template<typename TElem , int TWorldDim> const int ug::FV1Geometry< TElem, TWorldDim >::worldDim = TWorldDim static
dimension of world
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/fv1_geom.h
ugbase/lib_disc/spatial_disc/disc_util/fv1_geom.cpp