ug4: ug::node_tree::Traverser_CollisionTree Class Reference
ug::node_tree::Traverser_CollisionTree Class Reference
Enhances the Traverser base-class by methods to traverse a collision tree.
#include <traverser_collision_tree.h>
Public Member Functions
Traverser_CollisionTree ()
virtual ~Traverser_CollisionTree ()
Public Member Functions inherited from ug::node_tree::Traverser
Traverser ()
virtual ~Traverser ()
Protected Member Functions
CollisionTreeRootNode * get_current_root_node ()
virtual void handle_collision_edges (CollisionEdgesNode *colEdgesNode)
virtual void handle_collision_tree_root (CollisionTreeRootNode *colTreeRootNode)
virtual void handle_collision_triangles (CollisionTrianglesNode *colTrisNode)
Protected Member Functions inherited from ug::node_tree::Traverser
void apply (SPNode &node)
virtual void handle_boxed_group (BoxedGroupNode *boxedGroup)
virtual void handle_group (GroupNode *group)
template<typename HandlerType >
void register_handler_function (unsigned int oc, HandlerType func)
void traverse_object (Object *obj)
Private Attributes
std::stack< CollisionTreeRootNode * > m_stackRootNodes
Detailed Description
Enhances the Traverser base-class by methods to traverse a collision tree.
Derive from this class if you want to create a traverser that traverses a collision-tree.
This class does nothing more than registering its callback-methods at the base-traverser.
The methods here do not do much. handle_collision_tree_root calls its handle_boxed_group on its node. The other methods are empty.
Constructor & Destructor Documentation
Traverser_CollisionTree()
ug::node_tree::Traverser_CollisionTree::Traverser_CollisionTree ()
References handle_collision_edges(), handle_collision_tree_root(), handle_collision_triangles(), ug::node_tree::OC_COLLISION_EDGES_NODE, ug::node_tree::OC_COLLISION_TREE_ROOT_NODE, ug::node_tree::OC_COLLISION_TRIANGLES_NODE, and ug::node_tree::Traverser::register_handler_function().
~Traverser_CollisionTree()
ug::node_tree::Traverser_CollisionTree::~Traverser_CollisionTree () virtual
References handle_collision_tree_root().
Member Function Documentation
get_current_root_node()
CollisionTreeRootNode * ug::node_tree::Traverser_CollisionTree::get_current_root_node () protected
References m_stackRootNodes.
Referenced by handle_collision_triangles().
handle_collision_edges()
void ug::node_tree::Traverser_CollisionTree::handle_collision_edges (CollisionEdgesNode * colEdgesNode) protected virtual
Reimplemented in ug::node_tree::Traverser_ProjectPoint.
References handle_collision_triangles().
Referenced by handle_collision_tree_root(), and Traverser_CollisionTree().
handle_collision_tree_root()
void ug::node_tree::Traverser_CollisionTree::handle_collision_tree_root (CollisionTreeRootNode * colTreeRootNode) protected virtual
References ug::node_tree::Traverser::handle_boxed_group(), handle_collision_edges(), and m_stackRootNodes.
Referenced by Traverser_CollisionTree(), and ~Traverser_CollisionTree().
handle_collision_triangles()
void ug::node_tree::Traverser_CollisionTree::handle_collision_triangles (CollisionTrianglesNode * colTrisNode) protected virtual
Reimplemented in ug::node_tree::Traverser_IntersectFaces, and ug::node_tree::Traverser_ProjectPoint.
References get_current_root_node().
Referenced by handle_collision_edges(), and Traverser_CollisionTree().
Member Data Documentation
m_stackRootNodes
std::stack<CollisionTreeRootNode*> ug::node_tree::Traverser_CollisionTree::m_stackRootNodes private
Referenced by get_current_root_node(), and handle_collision_tree_root().
The documentation for this class was generated from the following files:
ugbase/common/node_tree/traversers/traverser_collision_tree.h
ugbase/common/node_tree/traversers/traverser_collision_tree.cpp