ug4: ug::vrl::TestClass Class Reference
ug::vrl::TestClass Class Reference
#include <playground.h>
Public Member Functions
int add (int a, int b)
ConstSmartPtr< TestClass > constSmartTestImpl ()
std::string getRev ()
std::string getString ()
int performTest ()
int print ()
int print2 ()
int print2 () const
int print_name ()
SmartPtr< TestClass > smartTestImpl ()
TestClass ()
TestClass (std::string name)
~TestClass ()
Constructor & Destructor Documentation
TestClass() [1/2]
ug::vrl::TestClass::TestClass ()
References UG_LOG.
Referenced by constSmartTestImpl(), and smartTestImpl().
TestClass() [2/2]
ug::vrl::TestClass::TestClass (std::string name)
References UG_LOG.
~TestClass()
ug::vrl::TestClass::~TestClass ()
References UG_LOG.
Member Function Documentation
add()
int ug::vrl::TestClass::add (int a, int b)
Referenced by ug::vrl::registerPlayground().
constSmartTestImpl()
ConstSmartPtr< TestClass > ug::vrl::TestClass::constSmartTestImpl ()
References TestClass().
Referenced by ug::vrl::registerPlayground().
getRev()
std::string ug::vrl::TestClass::getRev ()
References ug::vrl::svnRevision().
Referenced by ug::vrl::registerPlayground().
getString()
std::string ug::vrl::TestClass::getString ()
References UG_LOG.
Referenced by ug::vrl::registerPlayground().
performTest()
int ug::vrl::TestClass::performTest ()
print()
int ug::vrl::TestClass::print ()
References UG_LOG.
Referenced by ug::vrl::registerPlayground().
print2() [1/2]
int ug::vrl::TestClass::print2 ()
References UG_LOG.
Referenced by ug::vrl::TestSmartPtr2ConstPtr().
print2() [2/2]
int ug::vrl::TestClass::print2 () const
References UG_LOG.
print_name()
int ug::vrl::TestClass::print_name ()
References UG_LOG.
smartTestImpl()
SmartPtr< TestClass > ug::vrl::TestClass::smartTestImpl ()
References TestClass().
Referenced by ug::vrl::registerPlayground().
The documentation for this class was generated from the following files:
ugbase/bindings/vrl/playground.h
ugbase/bindings/vrl/playground.cpp