ug4: ug::AttachmentAccessor< TElem, TAttachment, TElemHandler > Class Template Reference
ug::AttachmentAccessor< TElem, TAttachment, TElemHandler > Class Template Reference
Used to access data that has been attached to an attachment pipe.
#include <attachment_pipe.h>
Public Types
typedef attachment_traits< TElem, TElemHandler > atraits
typedef TAttachment::ContainerType ContainerType
typedef TElem element
typedef TAttachment::ValueType ValueType
Public Member Functions
bool access (AttachmentPipe< TElem, TElemHandler > &attachmentPipe, TAttachment &attachment)
AttachmentAccessor ()
AttachmentAccessor (const AttachmentAccessor &aa)
AttachmentAccessor (AttachmentPipe< TElem, TElemHandler > &attachmentPipe, TAttachment &attachment)
size_t element_data_index (typename atraits::ConstElemPtr elem)
returns the data index of the given element regarding the associated container.
void invalidate ()
attachment_value_traits< ValueType >::reference operator[] (typename atraits::ConstElemPtr elem)
attachment_value_traits< ValueType >::const_reference operator[] (typename atraits::ConstElemPtr elem) const
ValueType * raw_data ()
returns the raw pointer to the data of the associated container
void swap (AttachmentAccessor< TElem, TAttachment, TElemHandler > &acc)
calls swap on associated containers
bool valid () const
Protected Attributes
ContainerType * m_pContainer
TElemHandler * m_pHandler
Detailed Description
template<class TElem, class TAttachment, class TElemHandler>
class ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >
Used to access data that has been attached to an attachment pipe.
Once initialized, an AttachmentAccessor can be used to access the data stored in the given Attachment at the given AttachmentPipe. The reference type of the associated value is taken from attachment_value_traits. By default this is the standard reference type.
To initialize an AttachmentAccessor, you may either use its constructor or its access method, which returns false if the specified attachment is not present in the specified attachment pipe.
Note that data-access using an attachment accessor is cheap. Setting up a new attachment accessor however involves some work. While this is generally fast, too, it would introduce an unnecessary overhead inside inner loops or frequently called methods. You should thus try to minimize calls to access or to the accessors constructor.
Member Typedef Documentation
template<class TElem, class TAttachment, class TElemHandler> typedef attachment_traits<TElem, TElemHandler> ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::atraits
template<class TElem, class TAttachment, class TElemHandler> typedef TAttachment::ContainerType ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::ContainerType
template<class TElem, class TAttachment, class TElemHandler> typedef TElem ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::element
template<class TElem, class TAttachment, class TElemHandler> typedef TAttachment::ValueType ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::ValueType
Constructor & Destructor Documentation
template<class TElem , class TAttachment , class TElemHandler > ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::AttachmentAccessor ()
Referenced by ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::AttachmentAccessor(), and ug::AttachmentPipe< TElem, TElemHandler >::get_container_size().
template<class TElem , class TAttachment , class TElemHandler > ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::AttachmentAccessor (const AttachmentAccessor< TElem, TAttachment, TElemHandler > & aa)
References ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::AttachmentAccessor(), ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::m_pContainer, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::m_pHandler.
template<class TElem, class TAttachment, class TElemHandler> ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::AttachmentAccessor (AttachmentPipe< TElem, TElemHandler > & attachmentPipe, TAttachment & attachment)
References ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::access(), ug::AttachmentPipe< TElem, TElemHandler >::get_data_container(), ug::AttachmentPipe< TElem, TElemHandler >::get_elem_handler(), ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::m_pContainer, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::m_pHandler.
Member Function Documentation
template<class TElem, class TAttachment, class TElemHandler> bool ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::access (AttachmentPipe< TElem, TElemHandler > & attachmentPipe, TAttachment & attachment)
References ug::AttachmentPipe< TElem, TElemHandler >::get_data_container(), ug::AttachmentPipe< TElem, TElemHandler >::get_elem_handler(), ug::AttachmentPipe< TElem, TElemHandler >::has_attachment(), ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::m_pContainer, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::m_pHandler.
Referenced by ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::AttachmentAccessor().
template<class TElem, class TAttachment, class TElemHandler> size_t ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::element_data_index (typename atraits::ConstElemPtr elem) inline
returns the data index of the given element regarding the associated container.
Note that the data index does not stay constant all the time. If the associated container is, e.g., defragmented, the data index may change.
template<class TElem, class TAttachment, class TElemHandler> void ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::invalidate () inline
Referenced by ug::MultiElementAttachmentAccessor< Attachment< Values > >::access(), and ug::DoFIndexStorage::clear_attachments().
template<class TElem, class TAttachment, class TElemHandler> attachment_value_traits<ValueType>::reference ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::operator[] (typename atraits::ConstElemPtr elem) inline
template<class TElem, class TAttachment, class TElemHandler> attachment_value_traits<ValueType>::const_reference ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::operator[] (typename atraits::ConstElemPtr elem) const inline
template<class TElem, class TAttachment, class TElemHandler> ValueType* ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::raw_data () inline
returns the raw pointer to the data of the associated container
ATTENTION: Use this method with extreme care! Returns NULL if no container was associated.
template<class TElem, class TAttachment, class TElemHandler> void ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::swap (AttachmentAccessor< TElem, TAttachment, TElemHandler > & acc) inline
calls swap on associated containers
Referenced by ug::ProjectToLimitPLoop(), and ug::ProjectToLimitSubdivBoundary().
template<class TElem, class TAttachment, class TElemHandler> bool ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid () const inline
Referenced by ug::FracturedMediaRefiner< TGrid, TAPosition >::aspect_ratio(), ug::DoFIndexStorage::clear_attachments(), ug::FracturedMediaRefiner< TGrid, TAPosition >::collect_objects_for_refine(), ug::MultiElementAttachmentAccessor< Attachment< Values > >::is_valid_edge_accessor(), ug::MultiElementAttachmentAccessor< Attachment< Values > >::is_valid_face_accessor(), ug::MultiElementAttachmentAccessor< Attachment< Values > >::is_valid_vertex_accessor(), ug::MultiElementAttachmentAccessor< Attachment< Values > >::is_valid_volume_accessor(), ug::FracturedMediaRefiner< TGrid, TAPosition >::mark(), ug::SphereProjector< TAPosition >::new_vertex(), ug::CylinderProjector< TAPosition >::new_vertex(), ug::SphericalFalloffProjector< TAPosition >::new_vertex(), ug::CylindricalFalloffProjector< TAPosition >::new_vertex(), ug::SubdivisionLoopBoundaryProjector< TAPosition >::new_vertex(), ug::RefinementCallbackLinear< TAPosition >::new_vertex(), ug::SubdivisionLoopProjector< TAPosition >::new_vertex(), ug::SphereProjector< TAPosition >::perform_projection(), ug::CylinderProjector< TAPosition >::perform_projection(), ug::SphericalFalloffProjector< TAPosition >::perform_projection(), ug::CylindricalFalloffProjector< TAPosition >::perform_projection(), and ug::NTreeGridData< world_dim >::position().
Member Data Documentation
template<class TElem, class TAttachment, class TElemHandler> ContainerType* ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::m_pContainer protected
Referenced by ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::access(), ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::AttachmentAccessor(), and ug::AttachmentAccessor< Vertex::grid_base_object *, APosition, traits< Vertex >::ElementStorage >::swap().
template<class TElem, class TAttachment, class TElemHandler> TElemHandler* ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::m_pHandler protected
Referenced by ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::access(), and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::AttachmentAccessor().
The documentation for this class was generated from the following files:
ugbase/lib_grid/attachments/attachment_pipe.h
ugbase/lib_grid/attachments/attachment_pipe.hpp