ug4: ug::FV1IBGeometry< TElem, TWorldDim >::BF Class Reference
ug::FV1IBGeometry< TElem, TWorldDim >::BF Class Reference
boundary face
#include <fv1ib_geom.h>
Public Member Functions
BF ()
number detJ () const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_corner (size_t co) const
return global corner number i
const MathVector< worldDim > & global_grad (size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector () const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip () const
global integration point of bf
const MathMatrix< worldDim, dim > & JTInv () const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector () const
vector of local gradients in ip point
const MathVector< dim > & local_ip () const
local integration point of bf
size_t node_id () const
index of SubControlVolume of the bf
const MathVector< worldDim > & normal () const
outer normal on bf. Norm is equal to area
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points on bf
size_t num_sh () const
number of shape functions
number shape (size_t sh) const
value of shape function i in integration point
const number * shape_vector () const
vector of local gradients in ip point
number volume () const
volume of bf
Static Public Attributes
static const size_t numCo = traits::NumCornersOfSCVF
Number of corners of bf.
Private Attributes
number detj
MathVector< worldDim > globalIP
MathMatrix< worldDim, dim > JtInv
MathVector< dim > localIP
size_t nodeId
MathVector< worldDim > Normal
MathVector< worldDim > vGlobalGrad [nsh]
MathVector< worldDim > vGloPos [numCo]
MathVector< dim > vLocalGrad [nsh]
MathVector< dim > vLocPos [numCo]
MidID vMidID [numCo]
number Vol
number vShape [nsh]
Friends
class FV1IBGeometry< TElem, TWorldDim >
let outer class access private members
Detailed Description
template<typename TElem, int TWorldDim>
class ug::FV1IBGeometry< TElem, TWorldDim >::BF
boundary face
Constructor & Destructor Documentation
template<typename TElem , int TWorldDim> ug::FV1IBGeometry< TElem, TWorldDim >::BF::BF () inline
Member Function Documentation
template<typename TElem , int TWorldDim> number ug::FV1IBGeometry< TElem, TWorldDim >::BF::detJ () const inline
Determinant of Jacobian in integration point.
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::detj.
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::FV1IBGeometry< TElem, TWorldDim >::BF::global_corner (size_t co) const inline
return global corner number i
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_corners(), UG_ASSERT, and ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vGloPos.
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::FV1IBGeometry< TElem, TWorldDim >::BF::global_grad (size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_sh(), UG_ASSERT, and ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vGlobalGrad.
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::FV1IBGeometry< TElem, TWorldDim >::BF::global_grad_vector () const inline
vector of global gradients in ip point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vGlobalGrad.
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::FV1IBGeometry< TElem, TWorldDim >::BF::global_ip () const inline
global integration point of bf
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::globalIP.
template<typename TElem , int TWorldDim> const MathMatrix<worldDim, dim>& ug::FV1IBGeometry< TElem, TWorldDim >::BF::JTInv () const inline
Transposed Inverse of Jacobian in integration point.
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::JtInv.
template<typename TElem , int TWorldDim> const MathVector<dim>& ug::FV1IBGeometry< TElem, TWorldDim >::BF::local_corner (size_t co) const inline
return local corner number i
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_corners(), UG_ASSERT, and ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vLocPos.
template<typename TElem , int TWorldDim> const MathVector<dim>& ug::FV1IBGeometry< TElem, TWorldDim >::BF::local_grad (size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_sh(), UG_ASSERT, and ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vLocalGrad.
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::FV1IBGeometry< TElem, TWorldDim >::BF::local_grad_vector () const inline
vector of local gradients in ip point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vLocalGrad.
template<typename TElem , int TWorldDim> const MathVector<dim>& ug::FV1IBGeometry< TElem, TWorldDim >::BF::local_ip () const inline
local integration point of bf
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::localIP.
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::BF::node_id () const inline
index of SubControlVolume of the bf
template<typename TElem , int TWorldDim> const MathVector<worldDim>& ug::FV1IBGeometry< TElem, TWorldDim >::BF::normal () const inline
outer normal on bf. Norm is equal to area
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::Normal.
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::BF::num_corners () const inline
number of corners, that bound the scvf
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::numCo.
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::BF::num_ip () const inline
number of integration points on bf
References ug::FV1IBGeometry< TElem, TWorldDim >::nip.
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::BF::num_sh () const inline
number of shape functions
References ug::FV1IBGeometry< TElem, TWorldDim >::nsh.
template<typename TElem , int TWorldDim> number ug::FV1IBGeometry< TElem, TWorldDim >::BF::shape (size_t sh) const inline
value of shape function i in integration point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_sh(), UG_ASSERT, and ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vShape.
template<typename TElem , int TWorldDim> const number* ug::FV1IBGeometry< TElem, TWorldDim >::BF::shape_vector () const inline
vector of local gradients in ip point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vShape.
template<typename TElem , int TWorldDim> number ug::FV1IBGeometry< TElem, TWorldDim >::BF::volume () const inline
volume of bf
Friends And Related Function Documentation
template<typename TElem , int TWorldDim> friend class FV1IBGeometry< TElem, TWorldDim > friend
let outer class access private members
Member Data Documentation
template<typename TElem , int TWorldDim> number ug::FV1IBGeometry< TElem, TWorldDim >::BF::detj private
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1IBGeometry< TElem, TWorldDim >::BF::globalIP private
template<typename TElem , int TWorldDim> MathMatrix<worldDim,dim> ug::FV1IBGeometry< TElem, TWorldDim >::BF::JtInv private
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1IBGeometry< TElem, TWorldDim >::BF::localIP private
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::BF::nodeId private
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1IBGeometry< TElem, TWorldDim >::BF::Normal private
template<typename TElem , int TWorldDim> const size_t ug::FV1IBGeometry< TElem, TWorldDim >::BF::numCo = traits::NumCornersOfSCVF static
Number of corners of bf.
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1IBGeometry< TElem, TWorldDim >::BF::vGlobalGrad[nsh] private
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1IBGeometry< TElem, TWorldDim >::BF::vGloPos[numCo] private
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1IBGeometry< TElem, TWorldDim >::BF::vLocalGrad[nsh] private
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1IBGeometry< TElem, TWorldDim >::BF::vLocPos[numCo] private
template<typename TElem , int TWorldDim> MidID ug::FV1IBGeometry< TElem, TWorldDim >::BF::vMidID[numCo] private
template<typename TElem , int TWorldDim> number ug::FV1IBGeometry< TElem, TWorldDim >::BF::Vol private
template<typename TElem , int TWorldDim> number ug::FV1IBGeometry< TElem, TWorldDim >::BF::vShape[nsh] private
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv1ib_geom.h