ug4: ug::bridge::ClassNameProvider< TClass > Class Template Reference
ug::bridge::ClassNameProvider< TClass > Class Template Reference
ugbase » Bridge » Registry
provides the name for a class
#include <class_name_provider.h>
Static Public Member Functions
static const ClassNameNode & class_name_node ()
return the class name node in the class hierarchy
static bool forward_declared ()
returns if class name is forward declared
static const std::string & group ()
groups
static bool is_a (const std::string &parent, bool strict=false)
static const std::string & name ()
name of this class
static bool named ()
returns if the class has been named by user
static const std::vector< const char * > & names ()
returns vector of all names including parent class names
static void set_name (const std::string &nameIn, const std::string &group, bool newName=false)
set name of class and copy parent names
template<typename TParent1 >
static void set_name (const std::string &nameIn, const std::string &group, bool newName=false)
set name of class and copy parent names
template<typename TParent1 , typename TParent2 >
static void set_name (const std::string &nameIn, const std::string &group, bool newName=false)
set name of class and copy parent names
Static Protected Member Functions
static void set_foreward_declared ()
sets a temporary name to the class
Static Private Attributes
static bool m_bForwardDeclared = false
set to true if class has not been named by user, but a default name given
static ClassNameNode m_ClassNameNode = ClassNameNode()
class name node holding own name and pointers to base class name nodes
static std::string m_group = std::string("")
Name of group, we're this class is sorted.
static std::vector< const char * > m_names = std::vector<const char*>()
vector of parent class names (depreciated)
Detailed Description
template<typename TClass>
class ug::bridge::ClassNameProvider< TClass >
provides the name for a class
Member Function Documentation
template<typename TClass > static const ClassNameNode& ug::bridge::ClassNameProvider< TClass >::class_name_node () inline static
return the class name node in the class hierarchy
Referenced by ug::bridge::ParameterInfo::_push_type(), ug::bridge::ParameterInfo::_push_vector_type(), ug::bridge::ClassCastProvider::add_cast_func(), and ug::bridge::ExportedClass< TClass >::class_name_node().
template<typename TClass > static bool ug::bridge::ClassNameProvider< TClass >::forward_declared () inline static
returns if class name is forward declared
template<typename TClass > static const std::string& ug::bridge::ClassNameProvider< TClass >::group () inline static
groups
Referenced by ug::bridge::ExportedClass< TClass >::group().
template<typename TClass > bool ug::bridge::ClassNameProvider< TClass >::is_a (const std::string & parent, bool strict = false) static
check if a given class name is equal This function checks if a given class name is equal to this class name. If the flag 'strict' is set to true, the class name must match exactly. If it is set to false, also parent names (of the class hierarchy) are checked and if this class inherits from the parent class true is returned.
References ug::bridge::ClassNameTreeContains(), and UG_THROW_REGISTRY_ERROR.
template<typename TClass > const std::string & ug::bridge::ClassNameProvider< TClass >::name () static
name of this class
Referenced by ug::bridge::ClassCastProvider::cast_to(), ug::bridge::Registry::get_class_(), ug::bridge::GetClassName(), and ug::bridge::ExportedClass< TClass >::name().
template<typename TClass > static bool ug::bridge::ClassNameProvider< TClass >::named () inline static
returns if the class has been named by user
template<typename TClass > const std::vector< const char * > & ug::bridge::ClassNameProvider< TClass >::names () static
returns vector of all names including parent class names
References ug::bridge::ExtractClassNameVec().
Referenced by ug::bridge::ExportedClass< TClass >::class_names().
template<typename TClass > void ug::bridge::ClassNameProvider< TClass >::set_foreward_declared () static protected
sets a temporary name to the class
template<typename TClass > void ug::bridge::ClassNameProvider< TClass >::set_name (const std::string & nameIn, const std::string & group, bool newName = false) static
set name of class and copy parent names
References UG_ERR_LOG, UG_THROW_REGISTRY_ERROR, and UG_THROW_REGISTRY_MSG.
Referenced by ug::bridge::ExportedClass< TClass >::ExportedClass().
template<typename TClass > template<typename TParent1 > static void ug::bridge::ClassNameProvider< TClass >::set_name (const std::string & nameIn, const std::string & group, bool newName = false) static
set name of class and copy parent names
template<typename TClass > template<typename TParent1 , typename TParent2 > static void ug::bridge::ClassNameProvider< TClass >::set_name (const std::string & nameIn, const std::string & group, bool newName = false) static
set name of class and copy parent names
Member Data Documentation
template<typename TClass > bool ug::bridge::ClassNameProvider< TClass >::m_bForwardDeclared = false static private
set to true if class has not been named by user, but a default name given
template<typename TClass > ClassNameNode ug::bridge::ClassNameProvider< TClass >::m_ClassNameNode = ClassNameNode() static private
class name node holding own name and pointers to base class name nodes
template<typename TClass > std::string ug::bridge::ClassNameProvider< TClass >::m_group = std::string("") static private
Name of group, we're this class is sorted.
template<typename TClass > std::vector< const char * > ug::bridge::ClassNameProvider< TClass >::m_names = std::vector<const char*>() static private
vector of parent class names (depreciated)
The documentation for this class was generated from the following files:
ugbase/registry/class_name_provider.h
ugbase/registry/class_name_provider_impl.h