ug4: ug::Partitioner_DynamicBisection< TElem, dim > Class Template Reference
ug::Partitioner_DynamicBisection< TElem, dim > Class Template Reference
lib_grid » parallelization » parallel distribution
Parallel bisection partitioner.
#include <partitioner_dynamic_bisection.h>
Classes
struct ElemList
struct Entry
struct TreeNode
Public Types
typedef Grid::VertexAttachmentAccessor< apos_t > aapos_t
typedef Attachment< vector_t > apos_t
typedef IPartitioner base_class
typedef TElem elem_t
typedef GridLayoutMap::Types< elem_t >::Layout::LevelLayout layout_t
typedef TElem::side side_t
typedef MathVector< dim > vector_t
Public Member Functions
virtual ConstSPProcessHierarchy current_process_hierarchy () const
void enable_longest_split_axis (bool enable)
enables automatical determination of split-axis by longest geometry extension
void enable_split_axis (int axis, bool enable)
enable or disable splits along a certain axis.
void enable_static_partitioning (bool enable)
virtual SubsetHandler & get_partitions ()
virtual const std::vector< int > * get_process_map () const
returns the processes map. Updated during partitioning. may be NULL.
virtual ConstSPProcessHierarchy next_process_hierarchy () const
int num_split_improvement_iterations () const
the maximum number of iterations performed to find a good split plane
virtual bool partition (size_t baseLvl, size_t elementThreshold)
Partitioner_DynamicBisection ()
virtual void set_balance_weights (SPBalanceWeights balanceWeights)
void set_grid (MultiGrid *mg, Attachment< MathVector< dim > > aPos)
virtual void set_next_process_hierarchy (SPProcessHierarchy procHierarchy)
void set_num_split_improvement_iterations (int num)
virtual void set_partition_post_processor (SPPartitionPostProcessor ppp)
void set_start_split_axis (int axis)
sets the axis with which bisection is started.
void set_subset_handler (SmartPtr< SubsetHandler > sh)
allows to optionally specify a subset-handler on which the balancer shall operate
void set_tolerance (number tol)
sets the tolerance threshold. 1: no tolerance, 0: full tolerance.
bool static_partitioning_enabled () const
virtual bool supports_balance_weights () const
virtual bool supports_connection_weights () const
virtual bool supports_repartitioning () const
virtual ~Partitioner_DynamicBisection ()
Public Member Functions inherited from ug::IPartitioner
IPartitioner ()
virtual bool problems_occurred ()
indicates whether problems occurred during the last partitioning
void set_verbose (bool verbose)
bool verbose () const
virtual ~IPartitioner ()
virtual void enable_clustered_siblings (bool bEnable)
virtual bool clustered_siblings_enabled ()
Private Types
enum constants {
UNCLASSIFIED = 0, LEFT = 1, RIGHT = 1 << 1, CUTTING = LEFT | RIGHT,
CUTTING_CENTER_LEFT, CUTTING_CENTER_RIGHT, TOTAL, NUM_CONSTANTS
}
Private Member Functions
void bisect_elements (std::vector< TreeNode > &childNodesOut, std::vector< TreeNode > &parentNodes, ANumber aWeight, number maxChildWeight, pcl::ProcessCommunicator &com, int cutRecursion, int splitAxis)
void calculate_global_dimensions (std::vector< TreeNode > &treeNodes, number maxChildWeight, ANumber aWeight, pcl::ProcessCommunicator &com)
int classify_elem (elem_t *e, int splitAxis, number splitValue)
void control_bisection (ISubsetHandler &partitionSH, std::vector< TreeNode > &treeNodes, ANumber aWeight, number maxChildWeight, pcl::ProcessCommunicator &com)
void copy_partitions_to_children (ISubsetHandler &partitionSH, int lvl)
void gather_weights_from_level (int baseLvl, int childLvl, ANumber aWeight, bool copyToVMastersOnBaseLvl, bool markedElemsOnly)
int get_next_split_axis ()
returns the next valid split axis to m_lastSplitAxis.
int get_next_split_axis (int lastAxis) const
returns the next valid split axis to the specified one
void improve_split_values (std::vector< TreeNode > &treeNodes, size_t maxIterations, ANumber aWeight, pcl::ProcessCommunicator &com)
void perform_bisection (int numTargetProcs, int minLvl, int maxLvl, int partitionLvl, ANumber aWeight, pcl::ProcessCommunicator com)
Private Attributes
aapos_t m_aaPos
apos_t m_aPos
SPBalanceWeights m_balanceWeights
std::vector< Entry > m_entries
int m_firstSplitAxisEnabled
int m_highestRedistLevel
pcl::InterfaceCommunicator< layout_t > m_intfcCom
int m_lastSplitAxis
int m_longestSplitAxisEnabled
MultiGrid * m_mg
SPProcessHierarchy m_nextProcessHierarchy
int m_numSplitAxisEnabled
SPPartitionPostProcessor m_partitionPostProcessor
SPProcessHierarchy m_processHierarchy
std::vector< int > m_procMap
SmartPtr< SubsetHandler > m_sh
bool m_splitAxisEnabled [dim]
size_t m_splitImproveIterations
int m_startSplitAxis
bool m_staticPartitioning
number m_tolerance
Static Private Attributes
static const size_t s_invalidIndex = -1
Additional Inherited Members
Protected Attributes inherited from ug::IPartitioner
bool m_problemsOccurred
Detailed Description
template<class TElem, int dim>
class ug::Partitioner_DynamicBisection< TElem, dim >
Parallel bisection partitioner.
The partitioner can be used inside a LoadBalancer or separately. It can operate on serial and parallel multigrids.
The following partition hints provided by a process hierarchy are supported:
'enableXCuts' (bool)
'enableYCuts' (bool)
'enableZCuts' (bool)
Member Typedef Documentation
aapos_t
template<class TElem , int dim> typedef Grid::VertexAttachmentAccessor<apos_t> ug::Partitioner_DynamicBisection< TElem, dim >::aapos_t
apos_t
template<class TElem , int dim> typedef Attachment<vector_t> ug::Partitioner_DynamicBisection< TElem, dim >::apos_t
base_class
template<class TElem , int dim> typedef IPartitioner ug::Partitioner_DynamicBisection< TElem, dim >::base_class
elem_t
template<class TElem , int dim> typedef TElem ug::Partitioner_DynamicBisection< TElem, dim >::elem_t
layout_t
template<class TElem , int dim> typedef GridLayoutMap::Types<elem_t>::Layout::LevelLayout ug::Partitioner_DynamicBisection< TElem, dim >::layout_t
side_t
template<class TElem , int dim> typedef TElem::side ug::Partitioner_DynamicBisection< TElem, dim >::side_t
vector_t
template<class TElem , int dim> typedef MathVector<dim> ug::Partitioner_DynamicBisection< TElem, dim >::vector_t
Member Enumeration Documentation
constants
template<class TElem , int dim> enum ug::Partitioner_DynamicBisection::constants private
Enumerator
UNCLASSIFIED
LEFT
RIGHT
CUTTING
CUTTING_CENTER_LEFT
CUTTING_CENTER_RIGHT
TOTAL
NUM_CONSTANTS
Constructor & Destructor Documentation
Partitioner_DynamicBisection()
template<class TElem , int dim> ug::Partitioner_DynamicBisection< TElem, dim >::Partitioner_DynamicBisection ()
References dim, ug::Partitioner_DynamicBisection< TElem, dim >::m_balanceWeights, ug::Partitioner_DynamicBisection< TElem, dim >::m_numSplitAxisEnabled, ug::Partitioner_DynamicBisection< TElem, dim >::m_processHierarchy, ug::Partitioner_DynamicBisection< TElem, dim >::m_splitAxisEnabled, make_sp(), and ug::Partitioner_DynamicBisection< TElem, dim >::~Partitioner_DynamicBisection().
~Partitioner_DynamicBisection()
template<class TElem , int dim> ug::Partitioner_DynamicBisection< TElem, dim >::~Partitioner_DynamicBisection () virtual
References ug::Partitioner_DynamicBisection< TElem, dim >::set_grid().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::Partitioner_DynamicBisection().
Member Function Documentation
bisect_elements()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements (std::vector< TreeNode > & childNodesOut, std::vector< TreeNode > & parentNodes, ANumber aWeight, number maxChildWeight, pcl::ProcessCommunicator & com, int cutRecursion, int splitAxis) private
if splitAxis is set to -1, then the split-axis is chosen for each node as the axis along which the geometry of the node has the longest extension.
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::add(), pcl::ProcessCommunicator::allreduce(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::bisectionComplete, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::boxMax, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::boxMin, ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::CalculateCenter(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::center, ug::Partitioner_DynamicBisection< TElem, dim >::classify_elem(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::clear(), ug::Partitioner_DynamicBisection< TElem, dim >::CUTTING, dim, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::elem(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::elems, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::first(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::firstChildNode, GDIST_PROFILE_FUNC, ug::Partitioner_DynamicBisection< TElem, dim >::get_next_split_axis(), ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values(), ug::Partitioner_DynamicBisection< TElem, dim >::LEFT, ug::Partitioner_DynamicBisection< TElem, dim >::m_aaPos, ug::Partitioner_DynamicBisection< TElem, dim >::m_firstSplitAxisEnabled, ug::Partitioner_DynamicBisection< TElem, dim >::m_mg, ug::Partitioner_DynamicBisection< TElem, dim >::m_numSplitAxisEnabled, ug::Partitioner_DynamicBisection< TElem, dim >::m_splitAxisEnabled, ug::Partitioner_DynamicBisection< TElem, dim >::m_splitImproveIterations, ug::Partitioner_DynamicBisection< TElem, dim >::m_tolerance, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::maxSplitValue, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::minSplitValue, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::next(), PCL_RO_SUM, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::ratioLeft, ug::Partitioner_DynamicBisection< TElem, dim >::RIGHT, ug::Partitioner_DynamicBisection< TElem, dim >::s_invalidIndex, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::splitAxis, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::splitValue, and UG_THROW.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::control_bisection().
calculate_global_dimensions()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions (std::vector< TreeNode > & treeNodes, number maxChildWeight, ANumber aWeight, pcl::ProcessCommunicator & com) private
References pcl::ProcessCommunicator::allreduce(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::boxMax, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::boxMin, ug::CalculateCenter(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::center, dim, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::elem(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::elems, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::first(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::firstChildNode, GDIST_PROFILE_FUNC, ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values(), ug::Partitioner_DynamicBisection< TElem, dim >::m_aaPos, ug::Partitioner_DynamicBisection< TElem, dim >::m_mg, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::next(), PCL_RO_MAX, PCL_RO_MIN, PCL_RO_SUM, ug::Partitioner_DynamicBisection< TElem, dim >::s_invalidIndex, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::totalWeight, ug::VecScaleAdd(), and ug::VecSet().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), and ug::Partitioner_DynamicBisection< TElem, dim >::classify_elem().
classify_elem()
template<class TElem , int dim> int ug::Partitioner_DynamicBisection< TElem, dim >::classify_elem (elem_t * e, int splitAxis, number splitValue) private
References ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::Partitioner_DynamicBisection< TElem, dim >::CUTTING, ug::Partitioner_DynamicBisection< TElem, dim >::LEFT, ug::Partitioner_DynamicBisection< TElem, dim >::m_aaPos, ug::Partitioner_DynamicBisection< TElem, dim >::RIGHT, and ug::Partitioner_DynamicBisection< TElem, dim >::UNCLASSIFIED.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level(), and ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values().
control_bisection()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::control_bisection (ISubsetHandler & partitionSH, std::vector< TreeNode > & treeNodes, ANumber aWeight, number maxChildWeight, pcl::ProcessCommunicator & com) private
References ug::ISubsetHandler::assign_subset(), ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::bisectionComplete, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::elem(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::elems, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::first(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::firstChildNode, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::firstProc, GDIST_PROFILE_FUNC, ug::Partitioner_DynamicBisection< TElem, dim >::get_next_split_axis(), ug::Partitioner_DynamicBisection< TElem, dim >::m_entries, ug::Partitioner_DynamicBisection< TElem, dim >::m_longestSplitAxisEnabled, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::next(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::numTargetProcs, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::ratioLeft, ug::Partitioner_DynamicBisection< TElem, dim >::s_invalidIndex, and ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::set_entry_list().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection().
copy_partitions_to_children()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::copy_partitions_to_children (ISubsetHandler & partitionSH, int lvl) private
References ug::ISubsetHandler::assign_subset(), ug::MultiGrid::begin(), ug::Grid::distributed_grid_manager(), ug::MultiGrid::end(), ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level(), GDIST_PROFILE_FUNC, ug::MultiGrid::get_child(), ug::GridLayoutMap::get_layout(), ug::ISubsetHandler::get_subset_index(), ug::DistributedGridManager::grid_layout_map(), ug::GridLayoutMap::has_layout(), ug::INT_V_MASTER, ug::INT_V_SLAVE, ug::Grid::is_parallel(), ug::Partitioner_DynamicBisection< TElem, dim >::m_intfcCom, ug::Partitioner_DynamicBisection< TElem, dim >::m_mg, and ug::MultiGrid::num_children().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::get_next_split_axis(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), and ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection().
current_process_hierarchy()
template<class TElem , int dim> ConstSPProcessHierarchy ug::Partitioner_DynamicBisection< TElem, dim >::current_process_hierarchy () const virtual
Implements ug::IPartitioner.
References ug::Partitioner_DynamicBisection< TElem, dim >::m_processHierarchy, and ug::Partitioner_DynamicBisection< TElem, dim >::next_process_hierarchy().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::set_num_split_improvement_iterations(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_partition_post_processor().
enable_longest_split_axis()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::enable_longest_split_axis (bool enable) inline
enables automatical determination of split-axis by longest geometry extension
disabled by default
References ug::Partitioner_DynamicBisection< TElem, dim >::enable_split_axis(), and ug::Partitioner_DynamicBisection< TElem, dim >::m_longestSplitAxisEnabled.
enable_split_axis()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::enable_split_axis (int axis, bool enable)
enable or disable splits along a certain axis.
By default, splits along all axis are enabled.
References dim, ug::Partitioner_DynamicBisection< TElem, dim >::m_firstSplitAxisEnabled, ug::Partitioner_DynamicBisection< TElem, dim >::m_numSplitAxisEnabled, ug::Partitioner_DynamicBisection< TElem, dim >::m_splitAxisEnabled, and ug::Partitioner_DynamicBisection< TElem, dim >::set_next_process_hierarchy().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::enable_longest_split_axis(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_subset_handler().
enable_static_partitioning()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::enable_static_partitioning (bool enable)
static partitioning should be used if a globally refined multigrid is is used throughout a simulation. Static partitioning drastically reduces global communication. The drawback is, that static partitioning e.g. can't be used to properly rebalance a distributed adaptive grid.
References ug::Partitioner_DynamicBisection< TElem, dim >::m_staticPartitioning, and ug::Partitioner_DynamicBisection< TElem, dim >::static_partitioning_enabled().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::get_process_map(), and ug::Partitioner_DynamicBisection< TElem, dim >::supports_repartitioning().
gather_weights_from_level()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level (int baseLvl, int childLvl, ANumber aWeight, bool copyToVMastersOnBaseLvl, bool markedElemsOnly) private
References ug::MultiGrid::begin(), ug::Partitioner_DynamicBisection< TElem, dim >::classify_elem(), ug::IBalanceWeights::consider_in_level_above(), ug::Grid::distributed_grid_manager(), ug::MultiGrid::end(), GDIST_PROFILE_FUNC, ug::MultiGrid::get_child(), ug::GridLayoutMap::get_layout(), ug::IBalanceWeights::get_refined_weight(), ug::IBalanceWeights::get_weight(), ug::DistributedGridManager::grid_layout_map(), ug::Grid::has_attachment(), ug::GridLayoutMap::has_layout(), ug::IBalanceWeights::has_level_offsets(), ug::INT_V_MASTER, ug::INT_V_SLAVE, ug::DistributedGridManager::is_ghost(), ug::Grid::is_parallel(), ug::LIB_GRID, ug::Partitioner_DynamicBisection< TElem, dim >::m_balanceWeights, ug::Partitioner_DynamicBisection< TElem, dim >::m_intfcCom, ug::Partitioner_DynamicBisection< TElem, dim >::m_mg, ug::MultiGrid::num_children(), ug::MultiGrid::num_levels(), ug::SetAttachmentValues(), and UG_DLOG.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::copy_partitions_to_children(), and ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection().
get_next_split_axis() [1/2]
template<class TElem , int dim> int ug::Partitioner_DynamicBisection< TElem, dim >::get_next_split_axis () private
returns the next valid split axis to m_lastSplitAxis.
The method starts from m_startSplitAxis, cycling through all valid split axis.
Note
The method uses m_lastSplitAxis to determine the last used axis. It also sets m_lastSplitAxis to the next axis. In order to force the method to restart from m_startSplitAxis you may set m_lastSplitAxis to -1.
References ug::Partitioner_DynamicBisection< TElem, dim >::m_lastSplitAxis, and ug::Partitioner_DynamicBisection< TElem, dim >::m_startSplitAxis.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), and ug::Partitioner_DynamicBisection< TElem, dim >::control_bisection().
get_next_split_axis() [2/2]
template<class TElem , int dim> int ug::Partitioner_DynamicBisection< TElem, dim >::get_next_split_axis (int lastAxis) const private
returns the next valid split axis to the specified one
References ug::Partitioner_DynamicBisection< TElem, dim >::copy_partitions_to_children(), dim, ug::Partitioner_DynamicBisection< TElem, dim >::m_splitAxisEnabled, and UG_THROW.
get_partitions()
template<class TElem , int dim> SubsetHandler & ug::Partitioner_DynamicBisection< TElem, dim >::get_partitions () virtual
Implements ug::IPartitioner.
References ug::Partitioner_DynamicBisection< TElem, dim >::get_process_map(), ug::Partitioner_DynamicBisection< TElem, dim >::m_mg, ug::Partitioner_DynamicBisection< TElem, dim >::m_sh, and make_sp().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::supports_connection_weights(), and ug::Partitioner_DynamicBisection< TElem, dim >::supports_repartitioning().
get_process_map()
template<class TElem , int dim> const std::vector< int > * ug::Partitioner_DynamicBisection< TElem, dim >::get_process_map () const virtual
returns the processes map. Updated during partitioning. may be NULL.
If NULL is returned, this means that each subset index correspons to a global proc-rank.
Implements ug::IPartitioner.
References ug::Partitioner_DynamicBisection< TElem, dim >::enable_static_partitioning(), ug::Partitioner_DynamicBisection< TElem, dim >::m_procMap, and ug::Partitioner_DynamicBisection< TElem, dim >::static_partitioning_enabled().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::get_partitions(), and ug::Partitioner_DynamicBisection< TElem, dim >::supports_repartitioning().
improve_split_values()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values (std::vector< TreeNode > & treeNodes, size_t maxIterations, ANumber aWeight, pcl::ProcessCommunicator & com) private
References pcl::ProcessCommunicator::allreduce(), ug::CalculateCenter(), ug::Partitioner_DynamicBisection< TElem, dim >::classify_elem(), ug::Partitioner_DynamicBisection< TElem, dim >::CUTTING, ug::Partitioner_DynamicBisection< TElem, dim >::CUTTING_CENTER_LEFT, ug::Partitioner_DynamicBisection< TElem, dim >::CUTTING_CENTER_RIGHT, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::elem(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::elems, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::first(), ug::Partitioner_DynamicBisection< TElem, dim >::LEFT, ug::Partitioner_DynamicBisection< TElem, dim >::m_aaPos, ug::Partitioner_DynamicBisection< TElem, dim >::m_mg, ug::Partitioner_DynamicBisection< TElem, dim >::m_tolerance, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::maxSplitValue, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::minSplitValue, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::next(), ug::Partitioner_DynamicBisection< TElem, dim >::NUM_CONSTANTS, PCL_RO_SUM, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::ratioLeft, ug::Partitioner_DynamicBisection< TElem, dim >::RIGHT, ug::Partitioner_DynamicBisection< TElem, dim >::s_invalidIndex, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::splitAxis, ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::splitValue, and ug::Partitioner_DynamicBisection< TElem, dim >::TOTAL.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), and ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions().
next_process_hierarchy()
template<class TElem , int dim> ConstSPProcessHierarchy ug::Partitioner_DynamicBisection< TElem, dim >::next_process_hierarchy () const virtual
Implements ug::IPartitioner.
References ug::Partitioner_DynamicBisection< TElem, dim >::m_nextProcessHierarchy, and ug::Partitioner_DynamicBisection< TElem, dim >::supports_balance_weights().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::current_process_hierarchy(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_num_split_improvement_iterations().
num_split_improvement_iterations()
template<class TElem , int dim> int ug::Partitioner_DynamicBisection< TElem, dim >::num_split_improvement_iterations () const inline
the maximum number of iterations performed to find a good split plane
References ug::Partitioner_DynamicBisection< TElem, dim >::m_splitImproveIterations.
partition()
template<class TElem , int dim> bool ug::Partitioner_DynamicBisection< TElem, dim >::partition (size_t baseLvl, size_t elementThreshold) virtual
If the partitioner returns false, no partition-map has been created and no redistribution should be performed. Note, that returning false is not a sign of an error - it may even be a feature of a particular partitioner.
Implements ug::IPartitioner.
References pcl::ProcessCommunicator::allreduce(), ug::GridSubsetHandler::assign_subset(), ug::Grid::attach_to(), ug::MultiGrid::begin(), ug::ISubsetHandler::clear(), ug::ProcessHierarchy::cluster_procs(), ug::IPartitioner::clustered_siblings_enabled(), ug::Partitioner_DynamicBisection< TElem, dim >::copy_partitions_to_children(), ug::Grid::detach_from(), dim, ug::Partitioner_DynamicBisection< TElem, dim >::enable_split_axis(), ug::MultiGrid::end(), GDIST_PROFILE_FUNC, SmartPtr< T, FreePolicy >::get(), ug::ProcessHierarchy::global_proc_com(), ug::ProcessHierarchy::grid_base_level(), SmartPtr< T, FreePolicy >::invalid(), ug::Partitioner_DynamicBisection< TElem, dim >::m_balanceWeights, ug::Partitioner_DynamicBisection< TElem, dim >::m_highestRedistLevel, ug::Partitioner_DynamicBisection< TElem, dim >::m_mg, ug::Partitioner_DynamicBisection< TElem, dim >::m_nextProcessHierarchy, ug::Partitioner_DynamicBisection< TElem, dim >::m_partitionPostProcessor, ug::IPartitioner::m_problemsOccurred, ug::Partitioner_DynamicBisection< TElem, dim >::m_processHierarchy, ug::Partitioner_DynamicBisection< TElem, dim >::m_procMap, ug::Partitioner_DynamicBisection< TElem, dim >::m_sh, ug::Partitioner_DynamicBisection< TElem, dim >::m_splitAxisEnabled, make_sp(), ug::ProcessHierarchy::num_global_procs_involved(), ug::ProcessHierarchy::num_hierarchy_levels(), ug::ISubsetHandler::num_subsets(), ug::ProcessHierarchy::partition_hint(), pcl::PCD_LOCAL, PCL_DEBUG_BARRIER_ALL, PCL_RO_MAX, ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection(), pcl::ProcRank(), ug::Partitioner_DynamicBisection< TElem, dim >::static_partitioning_enabled(), ug::Variant::to_bool(), ug::MultiGrid::top_level(), UG_COND_THROW, UG_LOG, UG_THROW, and SmartPtr< T, FreePolicy >::valid().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::static_partitioning_enabled(), and ug::Partitioner_DynamicBisection< TElem, dim >::supports_repartitioning().
perform_bisection()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection (int numTargetProcs, int minLvl, int maxLvl, int partitionLvl, ANumber aWeight, pcl::ProcessCommunicator com) private
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::add(), pcl::ProcessCommunicator::allreduce(), ug::GridSubsetHandler::assign_subset(), ug::MultiGrid::begin(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::clear(), ug::Partitioner_DynamicBisection< TElem, dim >::control_bisection(), ug::Partitioner_DynamicBisection< TElem, dim >::copy_partitions_to_children(), ug::Grid::distributed_grid_manager(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::elems, pcl::ProcessCommunicator::empty(), ug::MultiGrid::end(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::firstProc, ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level(), GDIST_PROFILE_FUNC, ug::GridLayoutMap::get_layout(), ug::ISubsetHandler::get_subset_index(), ug::DistributedGridManager::grid_layout_map(), ug::GridLayoutMap::has_layout(), ug::INT_V_MASTER, ug::INT_V_SLAVE, ug::DistributedGridManager::is_ghost(), ug::Partitioner_DynamicBisection< TElem, dim >::m_balanceWeights, ug::Partitioner_DynamicBisection< TElem, dim >::m_entries, ug::Partitioner_DynamicBisection< TElem, dim >::m_intfcCom, ug::Partitioner_DynamicBisection< TElem, dim >::m_lastSplitAxis, ug::Partitioner_DynamicBisection< TElem, dim >::m_mg, ug::Partitioner_DynamicBisection< TElem, dim >::m_numSplitAxisEnabled, ug::Partitioner_DynamicBisection< TElem, dim >::m_partitionPostProcessor, ug::Partitioner_DynamicBisection< TElem, dim >::m_sh, ug::MultiGrid::num(), ug::Partitioner_DynamicBisection< TElem, dim >::TreeNode::numTargetProcs, PCL_RO_MAX, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::set_entry_list(), ug::SetAttachmentValues(), UG_ASSERT, UG_COND_THROW, and SmartPtr< T, FreePolicy >::valid().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::partition().
set_balance_weights()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::set_balance_weights (SPBalanceWeights balanceWeights) virtual
Implements ug::IPartitioner.
References ug::Partitioner_DynamicBisection< TElem, dim >::m_balanceWeights, and ug::Partitioner_DynamicBisection< TElem, dim >::set_partition_post_processor().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::set_next_process_hierarchy(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_num_split_improvement_iterations().
set_grid()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::set_grid (MultiGrid * mg, Attachment< MathVector< dim > > aPos)
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::Partitioner_DynamicBisection< TElem, dim >::m_aaPos, ug::Partitioner_DynamicBisection< TElem, dim >::m_aPos, ug::Partitioner_DynamicBisection< TElem, dim >::m_mg, ug::Partitioner_DynamicBisection< TElem, dim >::m_sh, and ug::Partitioner_DynamicBisection< TElem, dim >::set_subset_handler().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::~Partitioner_DynamicBisection().
set_next_process_hierarchy()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::set_next_process_hierarchy (SPProcessHierarchy procHierarchy) virtual
Implements ug::IPartitioner.
References ug::Partitioner_DynamicBisection< TElem, dim >::m_nextProcessHierarchy, and ug::Partitioner_DynamicBisection< TElem, dim >::set_balance_weights().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::enable_split_axis(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_num_split_improvement_iterations().
set_num_split_improvement_iterations()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::set_num_split_improvement_iterations (int num) inline
References ug::Partitioner_DynamicBisection< TElem, dim >::current_process_hierarchy(), ug::Partitioner_DynamicBisection< TElem, dim >::m_splitImproveIterations, ug::Partitioner_DynamicBisection< TElem, dim >::next_process_hierarchy(), ug::Partitioner_DynamicBisection< TElem, dim >::set_balance_weights(), ug::Partitioner_DynamicBisection< TElem, dim >::set_next_process_hierarchy(), ug::Partitioner_DynamicBisection< TElem, dim >::set_partition_post_processor(), ug::Partitioner_DynamicBisection< TElem, dim >::supports_balance_weights(), and ug::Partitioner_DynamicBisection< TElem, dim >::supports_connection_weights().
set_partition_post_processor()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::set_partition_post_processor (SPPartitionPostProcessor ppp) virtual
Reimplemented from ug::IPartitioner.
References ug::Partitioner_DynamicBisection< TElem, dim >::current_process_hierarchy(), and ug::Partitioner_DynamicBisection< TElem, dim >::m_partitionPostProcessor.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::set_balance_weights(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_num_split_improvement_iterations().
set_start_split_axis()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::set_start_split_axis (int axis) inline
sets the axis with which bisection is started.
0 by default.
Note
the start-split-axis is only considered if longest-split-axis is disabled.
References ug::Partitioner_DynamicBisection< TElem, dim >::m_startSplitAxis.
set_subset_handler()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::set_subset_handler (SmartPtr< SubsetHandler > sh)
allows to optionally specify a subset-handler on which the balancer shall operate
References ug::Partitioner_DynamicBisection< TElem, dim >::enable_split_axis(), ug::Partitioner_DynamicBisection< TElem, dim >::m_mg, and ug::Partitioner_DynamicBisection< TElem, dim >::m_sh.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::set_grid().
set_tolerance()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::set_tolerance (number tol) inline
sets the tolerance threshold. 1: no tolerance, 0: full tolerance.
the tolerance is defaulted to 0.99
References ug::Partitioner_DynamicBisection< TElem, dim >::m_tolerance.
static_partitioning_enabled()
template<class TElem , int dim> bool ug::Partitioner_DynamicBisection< TElem, dim >::static_partitioning_enabled () const
References ug::Partitioner_DynamicBisection< TElem, dim >::m_staticPartitioning, and ug::Partitioner_DynamicBisection< TElem, dim >::partition().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::enable_static_partitioning(), ug::Partitioner_DynamicBisection< TElem, dim >::get_process_map(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), and ug::Partitioner_DynamicBisection< TElem, dim >::supports_repartitioning().
supports_balance_weights()
template<class TElem , int dim> bool ug::Partitioner_DynamicBisection< TElem, dim >::supports_balance_weights () const virtual
Implements ug::IPartitioner.
References ug::Partitioner_DynamicBisection< TElem, dim >::supports_connection_weights().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::next_process_hierarchy(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_num_split_improvement_iterations().
supports_connection_weights()
template<class TElem , int dim> bool ug::Partitioner_DynamicBisection< TElem, dim >::supports_connection_weights () const virtual
References ug::Partitioner_DynamicBisection< TElem, dim >::get_partitions().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::set_num_split_improvement_iterations(), and ug::Partitioner_DynamicBisection< TElem, dim >::supports_balance_weights().
supports_repartitioning()
template<class TElem , int dim> virtual bool ug::Partitioner_DynamicBisection< TElem, dim >::supports_repartitioning () const inline virtual
Implements ug::IPartitioner.
References ug::Partitioner_DynamicBisection< TElem, dim >::enable_static_partitioning(), ug::Partitioner_DynamicBisection< TElem, dim >::get_partitions(), ug::Partitioner_DynamicBisection< TElem, dim >::get_process_map(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), and ug::Partitioner_DynamicBisection< TElem, dim >::static_partitioning_enabled().
Member Data Documentation
m_aaPos
template<class TElem , int dim> aapos_t ug::Partitioner_DynamicBisection< TElem, dim >::m_aaPos private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::Partitioner_DynamicBisection< TElem, dim >::classify_elem(), ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_grid().
m_aPos
template<class TElem , int dim> apos_t ug::Partitioner_DynamicBisection< TElem, dim >::m_aPos private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::set_grid().
m_balanceWeights
template<class TElem , int dim> SPBalanceWeights ug::Partitioner_DynamicBisection< TElem, dim >::m_balanceWeights private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), ug::Partitioner_DynamicBisection< TElem, dim >::Partitioner_DynamicBisection(), ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_balance_weights().
m_entries
template<class TElem , int dim> std::vector<Entry> ug::Partitioner_DynamicBisection< TElem, dim >::m_entries private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::control_bisection(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::elem(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::entries(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::next(), ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection(), and ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::set_entry_list().
m_firstSplitAxisEnabled
template<class TElem , int dim> int ug::Partitioner_DynamicBisection< TElem, dim >::m_firstSplitAxisEnabled private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), and ug::Partitioner_DynamicBisection< TElem, dim >::enable_split_axis().
m_highestRedistLevel
template<class TElem , int dim> int ug::Partitioner_DynamicBisection< TElem, dim >::m_highestRedistLevel private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::partition().
m_intfcCom
template<class TElem , int dim> pcl::InterfaceCommunicator<layout_t> ug::Partitioner_DynamicBisection< TElem, dim >::m_intfcCom private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::copy_partitions_to_children(), ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level(), and ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection().
m_lastSplitAxis
template<class TElem , int dim> int ug::Partitioner_DynamicBisection< TElem, dim >::m_lastSplitAxis private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::get_next_split_axis(), and ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection().
m_longestSplitAxisEnabled
template<class TElem , int dim> int ug::Partitioner_DynamicBisection< TElem, dim >::m_longestSplitAxisEnabled private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::control_bisection(), and ug::Partitioner_DynamicBisection< TElem, dim >::enable_longest_split_axis().
m_mg
template<class TElem , int dim> MultiGrid* ug::Partitioner_DynamicBisection< TElem, dim >::m_mg private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::Partitioner_DynamicBisection< TElem, dim >::copy_partitions_to_children(), ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level(), ug::Partitioner_DynamicBisection< TElem, dim >::get_partitions(), ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection(), ug::Partitioner_DynamicBisection< TElem, dim >::set_grid(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_subset_handler().
m_nextProcessHierarchy
template<class TElem , int dim> SPProcessHierarchy ug::Partitioner_DynamicBisection< TElem, dim >::m_nextProcessHierarchy private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::next_process_hierarchy(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_next_process_hierarchy().
m_numSplitAxisEnabled
template<class TElem , int dim> int ug::Partitioner_DynamicBisection< TElem, dim >::m_numSplitAxisEnabled private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::enable_split_axis(), ug::Partitioner_DynamicBisection< TElem, dim >::Partitioner_DynamicBisection(), and ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection().
m_partitionPostProcessor
template<class TElem , int dim> SPPartitionPostProcessor ug::Partitioner_DynamicBisection< TElem, dim >::m_partitionPostProcessor private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::partition(), ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_partition_post_processor().
m_processHierarchy
template<class TElem , int dim> SPProcessHierarchy ug::Partitioner_DynamicBisection< TElem, dim >::m_processHierarchy private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::current_process_hierarchy(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), and ug::Partitioner_DynamicBisection< TElem, dim >::Partitioner_DynamicBisection().
m_procMap
template<class TElem , int dim> std::vector<int> ug::Partitioner_DynamicBisection< TElem, dim >::m_procMap private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::get_process_map(), and ug::Partitioner_DynamicBisection< TElem, dim >::partition().
m_sh
template<class TElem , int dim> SmartPtr<SubsetHandler> ug::Partitioner_DynamicBisection< TElem, dim >::m_sh private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::get_partitions(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection(), ug::Partitioner_DynamicBisection< TElem, dim >::set_grid(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_subset_handler().
m_splitAxisEnabled
template<class TElem , int dim> bool ug::Partitioner_DynamicBisection< TElem, dim >::m_splitAxisEnabled[dim] private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::enable_split_axis(), ug::Partitioner_DynamicBisection< TElem, dim >::get_next_split_axis(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), and ug::Partitioner_DynamicBisection< TElem, dim >::Partitioner_DynamicBisection().
m_splitImproveIterations
template<class TElem , int dim> size_t ug::Partitioner_DynamicBisection< TElem, dim >::m_splitImproveIterations private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::num_split_improvement_iterations(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_num_split_improvement_iterations().
m_startSplitAxis
template<class TElem , int dim> int ug::Partitioner_DynamicBisection< TElem, dim >::m_startSplitAxis private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::get_next_split_axis(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_start_split_axis().
m_staticPartitioning
template<class TElem , int dim> bool ug::Partitioner_DynamicBisection< TElem, dim >::m_staticPartitioning private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::enable_static_partitioning(), and ug::Partitioner_DynamicBisection< TElem, dim >::static_partitioning_enabled().
m_tolerance
template<class TElem , int dim> number ug::Partitioner_DynamicBisection< TElem, dim >::m_tolerance private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values(), and ug::Partitioner_DynamicBisection< TElem, dim >::set_tolerance().
s_invalidIndex
template<class TElem , int dim> const size_t ug::Partitioner_DynamicBisection< TElem, dim >::s_invalidIndex = -1 static private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::add(), ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::clear(), ug::Partitioner_DynamicBisection< TElem, dim >::control_bisection(), and ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values().
The documentation for this class was generated from the following files:
ugbase/lib_grid/parallelization/partitioner_dynamic_bisection.h
ugbase/lib_grid/parallelization/partitioner_dynamic_bisection.cpp