ug4: ug::ParallelGlobalFracturedMediaRefiner Class Reference
ug::ParallelGlobalFracturedMediaRefiner Class Reference
Lib_grid_parallelization_refinement
Adds parallel support to GlobalFracturedMediaRefiner.
#include <parallel_global_fractured_media_refiner.h>
Public Member Functions
ParallelGlobalFracturedMediaRefiner (DistributedGridManager &distGridMgr, SPRefinementProjector projector=SPNULL)
virtual ~ParallelGlobalFracturedMediaRefiner ()
Public Member Functions inherited from ug::GlobalFracturedMediaRefiner
virtual bool adaptivity_supported () const
returns whether the refiner is able to perform adaptive refinement
void assign_grid (MultiGrid &mg)
void assign_grid (MultiGrid *mg)
virtual bool coarsening_supported () const
returns true, if the refiner supports coarsening.
virtual Grid * get_associated_grid ()
DEPRECIATED! Use grid(). Has to return the associated grid. Pure virtual.
GlobalFracturedMediaRefiner (MultiGrid &mg, SPRefinementProjector projector=SPNULL)
GlobalFracturedMediaRefiner (SPRefinementProjector projector=SPNULL)
virtual Grid * grid ()
Returns the grid associated with the refiner.
virtual void grid_to_be_destroyed (Grid *grid)
bool is_fracture (int subInd)
returns whether the specified subset is regarded as a fracture.
void mark_as_fracture (int subInd, bool isFracture)
sets the position attachment
virtual MultiGrid * multi_grid ()
virtual bool save_marks_to_file (const char *filename)
Writes the associated grid and marks to a file. Pure virtual.
void set_subset_handler (ISubsetHandler &sh)
void set_subset_handler (ISubsetHandler *sh)
virtual ~GlobalFracturedMediaRefiner ()
Public Member Functions inherited from ug::IRefiner
virtual void clear_marks ()
clears all marks. Default implementation is empty
bool coarsen ()
Performs coarsening on the elements marked RM_COARSEN.
bool debugging_enabled () const
void enable_debugging (bool enable)
int get_local_edge_mark (Face *f, Edge *e) const
returns the local mark of the specified edge of the given face
int get_local_edge_mark (Volume *vol, Edge *e) const
returns the local mark of the specified edge of the given volume
int get_local_face_mark (Volume *vol, Face *f) const
returns the local mark of the specified face of the given volume
virtual RefinementMark get_mark (GridObject *o) const
returns the mark of the specified geometric object
IRefiner (SPRefinementProjector projector=SPNULL)
virtual bool local_marks_supported () const
returns true, if the refiner supports local marks.
template<class TIterator >
void mark (const TIterator &iterBegin, const TIterator &iterEnd, RefinementMark refMark=RM_REFINE)
marks all elements between iterBegin and iterEnd.
virtual bool mark (GridObject *o, RefinementMark refMark=RM_REFINE)
marks the specified geometric object
void mark_neighborhood (size_t numIterations)
marks the neighborhood of currently marked elements.
virtual void mark_neighborhood (size_t numIterations, RefinementMark refMark, bool sideNbrsOnly)
marks the neighborhood of currently marked elements.
template<class TElem >
bool marked_closure (TElem *elem) const
template<class TElem >
bool marked_full (TElem *elem) const
template<class TElem >
bool marked_local (TElem *elem) const
size_t num_marked_edges ()
returns the number of (globally) marked edges on all levels of the hierarchy
size_t num_marked_edges (std::vector< int > &numMarkedEdgesOut)
returns the number of (globally) marked edges on all levels of the hierarchy
size_t num_marked_elements ()
returns the number of (globally) marked grid-objects of highest dimension
size_t num_marked_elements (std::vector< int > &numMarkedElemsOut)
returns the number of (globally) marked grid-objects of highest dimension
size_t num_marked_faces ()
returns the number of (globally) marked faces on all levels of the hierarchy
size_t num_marked_faces (std::vector< int > &numMarkedFacesOut)
returns the number of (globally) marked faces on all levels of the hierarchy
size_t num_marked_volumes ()
returns the number of (globally) marked volumes on all levels of the hierarchy
size_t num_marked_volumes (std::vector< int > &numMarkedVolsOut)
returns the number of (globally) marked volumes on all levels of the hierarchy
SPRefinementProjector projector ()
void refine ()
Performs refinement on the marked elements.
void set_adjusted_marks_debug_filename (const char *filename)
sets a filename to which adjusted marks are saved during refinement / coarsening
void set_projector (SPRefinementProjector projector)
virtual ~IRefiner ()
virtual bool mark (Vertex *v, RefinementMark refMark=RM_REFINE)
Marks an element for refinement. Default implementation is empty.
virtual bool mark (Edge *e, RefinementMark refMark=RM_REFINE)
Marks an element for refinement. Default implementation is empty.
virtual bool mark (Face *f, RefinementMark refMark=RM_REFINE)
Marks an element for refinement. Default implementation is empty.
virtual bool mark (Volume *v, RefinementMark refMark=RM_REFINE)
Marks an element for refinement. Default implementation is empty.
virtual void mark_local (Face *e, int mark)
Marks a face or volume for local refinement.
virtual void mark_local (Volume *e, int mark)
Marks a face or volume for local refinement.
virtual int get_local_mark (Face *e) const
returns the local mark of the specified face or volume.
virtual int get_local_mark (Volume *e) const
returns the local mark of the specified face or volume.
virtual RefinementMark get_mark (Vertex *v) const
Returns the mark of a given element. Default returns RM_REFINE.
virtual RefinementMark get_mark (Edge *e) const
Returns the mark of a given element. Default returns RM_REFINE.
virtual RefinementMark get_mark (Face *f) const
Returns the mark of a given element. Default returns RM_REFINE.
virtual RefinementMark get_mark (Volume *v) const
Returns the mark of a given element. Default returns RM_REFINE.
void adaption_begins ()
notifies all listeners of the associated message-hub, that adaption begins / ends.
void adaption_ends ()
notifies all listeners of the associated message-hub, that adaption begins / ends.
Public Member Functions inherited from ug::GridObserver
virtual void elements_to_be_cleared (Grid *grid)
virtual ~GridObserver ()
virtual void vertex_created (Grid *grid, Vertex *vrt, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void edge_created (Grid *grid, Edge *e, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void face_created (Grid *grid, Face *f, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void volume_created (Grid *grid, Volume *vol, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void vertex_to_be_erased (Grid *grid, Vertex *vrt, Vertex *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void edge_to_be_erased (Grid *grid, Edge *e, Edge *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void face_to_be_erased (Grid *grid, Face *f, Face *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void volume_to_be_erased (Grid *grid, Volume *vol, Volume *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void vertices_to_be_merged (Grid *grid, Vertex *target, Vertex *elem1, Vertex *elem2)
Notified when two elements of the same type are going to be merged.
virtual void edges_to_be_merged (Grid *grid, Edge *target, Edge *elem1, Edge *elem2)
Notified when two elements of the same type are going to be merged.
virtual void faces_to_be_merged (Grid *grid, Face *target, Face *elem1, Face *elem2)
Notified when two elements of the same type are going to be merged.
virtual void volumes_to_be_merged (Grid *grid, Volume *target, Volume *elem1, Volume *elem2)
Notified when two elements of the same type are going to be merged.
Protected Member Functions
virtual void communicate_marks (BoolMarker &marker)
Called by adjust_marks. Default implementation does nothing.
virtual bool refinement_is_allowed (Edge *elem)
a callback that allows to deny refinement of special edges
virtual bool refinement_is_allowed (Face *elem)
a callback that allows to deny refinement of special faces
virtual bool refinement_is_allowed (Vertex *elem)
a callback that allows to deny refinement of special vertices
virtual bool refinement_is_allowed (Volume *elem)
a callback that allows to deny refinement of special volumes
virtual void refinement_step_begins ()
this method helps derived classes to perform operations directly before actual element refinment is performed.
virtual void refinement_step_ends ()
this method helps derived classes to perform operations directly after actual element refinment took place.
Protected Member Functions inherited from ug::GlobalFracturedMediaRefiner
virtual void adjust_marks ()
called by perform_refinement to adjust the marks
template<class TElem >
void assign_elem_and_side_marks ()
performs the actual marking
template<class TElem >
bool is_fracture_element (TElem *e)
returns true if the specified element is a fracture element.
template<class TElem >
void mark_sides_of_marked_top_level_elements ()
recursively marks sides of all marked top level elements of the given type
template<class TElem >
size_t num_marked (const std::vector< TElem * > &elems) const
returns the number of marked entries
virtual void num_marked_edges_local (std::vector< int > &numMarkedEdgesOut)
returns the number of (globally) marked edges on this level of the hierarchy
template<class TElem >
void num_marked_elems (std::vector< int > &numMarkedElemsOut)
virtual void num_marked_faces_local (std::vector< int > &numMarkedFacesOut)
returns the number of (globally) marked faces on this level of the hierarchy
virtual void num_marked_volumes_local (std::vector< int > &numMarkedVolsOut)
returns the number of (globally) marked volumes on this level of the hierarchy
virtual void perform_refinement ()
performs refinement on the marked elements.
Protected Member Functions inherited from ug::IRefiner
virtual bool perform_coarsening ()
Called by coarsen(). Derived classes sould implement their coarsen algorithm here.
void set_message_hub (SPMessageHub msgHub)
sets the message hub.
Protected Attributes
DistributedGridManager & m_distGridMgr
pcl::InterfaceCommunicator< EdgeLayout > m_intfComEDGE
pcl::InterfaceCommunicator< FaceLayout > m_intfComFACE
Protected Attributes inherited from ug::GlobalFracturedMediaRefiner
BoolMarker m_marker
MultiGrid * m_pMG
ISubsetHandler * m_pSH
std::vector< bool > m_subsetIsFracture
Protected Attributes inherited from ug::IRefiner
bool m_adaptionIsActive
std::string m_adjustedMarksDebugFilename
bool m_debuggingEnabled
SPMessageHub m_messageHub
int m_msgIdAdaption
SPRefinementProjector m_projector
Detailed Description
Adds parallel support to GlobalFracturedMediaRefiner.
Constructor & Destructor Documentation
ParallelGlobalFracturedMediaRefiner()
ug::ParallelGlobalFracturedMediaRefiner::ParallelGlobalFracturedMediaRefiner (DistributedGridManager & distGridMgr, SPRefinementProjector projector = SPNULL)
~ParallelGlobalFracturedMediaRefiner()
ug::ParallelGlobalFracturedMediaRefiner::~ParallelGlobalFracturedMediaRefiner () virtual
Member Function Documentation
communicate_marks()
void ug::ParallelGlobalFracturedMediaRefiner::communicate_marks (BoolMarker & marker) protected virtual
Called by adjust_marks. Default implementation does nothing.
If you communicate marks (using an or operation) in this method, then the GlobalFracturedMediaRefiner should run fine in a parallel environment, too. The default implementation does nothing (that's fine for a serial environment).
Reimplemented from ug::GlobalFracturedMediaRefiner.
References ug::DistributedGridManager::grid_layout_map(), ug::INT_H_MASTER, ug::INT_H_SLAVE, m_distGridMgr, m_intfComEDGE, and m_intfComFACE.
refinement_is_allowed() [1/4]
bool ug::ParallelGlobalFracturedMediaRefiner::refinement_is_allowed (Edge * elem) protected virtual
a callback that allows to deny refinement of special edges
Reimplemented from ug::GlobalFracturedMediaRefiner.
References ug::DistributedGridManager::is_ghost(), and m_distGridMgr.
refinement_is_allowed() [2/4]
bool ug::ParallelGlobalFracturedMediaRefiner::refinement_is_allowed (Face * elem) protected virtual
a callback that allows to deny refinement of special faces
Reimplemented from ug::GlobalFracturedMediaRefiner.
References ug::DistributedGridManager::is_ghost(), and m_distGridMgr.
refinement_is_allowed() [3/4]
bool ug::ParallelGlobalFracturedMediaRefiner::refinement_is_allowed (Vertex * elem) protected virtual
a callback that allows to deny refinement of special vertices
Reimplemented from ug::GlobalFracturedMediaRefiner.
References ug::DistributedGridManager::is_ghost(), and m_distGridMgr.
refinement_is_allowed() [4/4]
bool ug::ParallelGlobalFracturedMediaRefiner::refinement_is_allowed (Volume * elem) protected virtual
a callback that allows to deny refinement of special volumes
Reimplemented from ug::GlobalFracturedMediaRefiner.
References ug::DistributedGridManager::is_ghost(), and m_distGridMgr.
refinement_step_begins()
void ug::ParallelGlobalFracturedMediaRefiner::refinement_step_begins () protected virtual
this method helps derived classes to perform operations directly before actual element refinment is performed.
Called from the refine() method in each refinement-iteration after collect_objects_for_refine(). Default implementation is empty.
Reimplemented from ug::GlobalFracturedMediaRefiner.
References ug::DistributedGridManager::begin_ordered_element_insertion(), and m_distGridMgr.
refinement_step_ends()
void ug::ParallelGlobalFracturedMediaRefiner::refinement_step_ends () protected virtual
this method helps derived classes to perform operations directly after actual element refinment took place.
Called from the refine() method in each refinement-iteration after all scheduled elements had been refined. The refine process will either terminate after this method or will start a new iteration, if new elements had been marked during refine. Default implementation is empty.
Reimplemented from ug::GlobalFracturedMediaRefiner.
References ug::DistributedGridManager::end_ordered_element_insertion(), and m_distGridMgr.
Member Data Documentation
m_distGridMgr
DistributedGridManager& ug::ParallelGlobalFracturedMediaRefiner::m_distGridMgr protected
Referenced by communicate_marks(), refinement_is_allowed(), refinement_step_begins(), and refinement_step_ends().
m_intfComEDGE
pcl::InterfaceCommunicator<EdgeLayout> ug::ParallelGlobalFracturedMediaRefiner::m_intfComEDGE protected
Referenced by communicate_marks().
m_intfComFACE
pcl::InterfaceCommunicator<FaceLayout> ug::ParallelGlobalFracturedMediaRefiner::m_intfComFACE protected
Referenced by communicate_marks().
The documentation for this class was generated from the following files:
ugbase/lib_grid/parallelization/parallel_refinement/parallel_global_fractured_media_refiner.h
ugbase/lib_grid/parallelization/parallel_refinement/parallel_global_fractured_media_refiner.cpp