ug4: ug::DimFVGeometry< TWorldDim, TDim >::SCV Class Reference
ug::DimFVGeometry< TWorldDim, TDim >::SCV Class Reference
sub control volume structure
#include <fvho_geom.h>
Public Member Functions
number detJ (size_t ip) const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_corner (size_t co) const
return glbal corner number i
const MathVector< worldDim > & global_grad (size_t ip, size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector (size_t ip) const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip (size_t ip) const
global integration point
const MathMatrix< worldDim, dim > & JTInv (size_t ip) const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t ip, size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector (size_t ip) const
vector of local gradients in ip point
const MathVector< dim > & local_ip (size_t ip) const
local integration point of scv
size_t node_id () const
node id that this scv is associated to
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shape functions
SCV ()
number shape (size_t ip, size_t sh) const
value of shape function i in integration point
const number * shape_vector (size_t ip) const
vector of shape functions in ip point
number weight (size_t ip) const
weigth of integration point
Static Public Attributes
static const size_t numCo = traits::NumCornersOfSCV
Number of corners of scvf.
Private Attributes
size_t nip
size_t nodeId
size_t nsh
std::vector< number > vDetJ
std::vector< number > vDetJMap
std::vector< MathVector< worldDim > > vGlobalIP
MathVector< worldDim > vGloPos [numCo]
std::vector< MathMatrix< worldDim, dim > > vJtInv
std::vector< MathVector< dim > > vLocalIP
MathVector< dim > vLocPos [numCo]
MidID vMidID [numCo]
std::vector< std::vector< MathVector< worldDim > > > vvGlobalGrad
std::vector< std::vector< MathVector< dim > > > vvLocalGrad
std::vector< std::vector< number > > vvShape
const number * vWeight
Friends
class DimFVGeometry< worldDim, dim >
Detailed Description
template<int TWorldDim, int TDim = TWorldDim>
class ug::DimFVGeometry< TWorldDim, TDim >::SCV
sub control volume structure
Constructor & Destructor Documentation
SCV()
template<int TWorldDim, int TDim = TWorldDim> ug::DimFVGeometry< TWorldDim, TDim >::SCV::SCV () inline
Member Function Documentation
detJ()
template<int TWorldDim, int TDim = TWorldDim> number ug::DimFVGeometry< TWorldDim, TDim >::SCV::detJ (size_t ip) const inline
Determinant of Jacobian in integration point.
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vDetJ.
global_corner()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>& ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_corner (size_t co) const inline
return glbal corner number i
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_corners(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vGloPos.
global_grad()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>& ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_grad (size_t ip, size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_sh(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vvGlobalGrad.
global_grad_vector()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>* ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_grad_vector (size_t ip) const inline
vector of global gradients in ip point
global_ip()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>& ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_ip (size_t ip) const inline
global integration point
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vGlobalIP.
JTInv()
template<int TWorldDim, int TDim = TWorldDim> const MathMatrix<worldDim,dim>& ug::DimFVGeometry< TWorldDim, TDim >::SCV::JTInv (size_t ip) const inline
Transposed Inverse of Jacobian in integration point.
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vJtInv.
local_corner()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>& ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_corner (size_t co) const inline
return local corner number i
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_corners(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vLocPos.
local_grad()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>& ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad (size_t ip, size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_sh(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vvLocalGrad.
local_grad_vector()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>* ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad_vector (size_t ip) const inline
vector of local gradients in ip point
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vvLocalGrad.
local_ip()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>& ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_ip (size_t ip) const inline
local integration point of scv
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vLocalIP.
node_id()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCV::node_id () const inline
node id that this scv is associated to
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::nodeId.
num_corners()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_corners () const inline
number of corners, that bound the scvf
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::numCo.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_corner(), and ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_corner().
num_ip()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip () const inline
number of integration points
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::nip.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::detJ(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::JTInv(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::shape(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::shape_vector(), and ug::DimFVGeometry< TWorldDim, TDim >::SCV::weight().
num_sh()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_sh () const inline
number of shape functions
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::nsh.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_grad(), and ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad().
shape()
template<int TWorldDim, int TDim = TWorldDim> number ug::DimFVGeometry< TWorldDim, TDim >::SCV::shape (size_t ip, size_t sh) const inline
value of shape function i in integration point
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vvShape.
shape_vector()
template<int TWorldDim, int TDim = TWorldDim> const number* ug::DimFVGeometry< TWorldDim, TDim >::SCV::shape_vector (size_t ip) const inline
vector of shape functions in ip point
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vvShape.
weight()
template<int TWorldDim, int TDim = TWorldDim> number ug::DimFVGeometry< TWorldDim, TDim >::SCV::weight (size_t ip) const inline
weigth of integration point
References ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), UG_ASSERT, ug::DimFVGeometry< TWorldDim, TDim >::SCV::vDetJMap, and ug::DimFVGeometry< TWorldDim, TDim >::SCV::vWeight.
Friends And Related Function Documentation
DimFVGeometry< worldDim, dim >
template<int TWorldDim, int TDim = TWorldDim> friend class DimFVGeometry< worldDim, dim > friend
Member Data Documentation
nip
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCV::nip private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip().
nodeId
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCV::nodeId private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::node_id().
nsh
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCV::nsh private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_sh().
numCo
template<int TWorldDim, int TDim = TWorldDim> const size_t ug::DimFVGeometry< TWorldDim, TDim >::SCV::numCo = traits::NumCornersOfSCV static
Number of corners of scvf.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_corners().
vDetJ
template<int TWorldDim, int TDim = TWorldDim> std::vector<number> ug::DimFVGeometry< TWorldDim, TDim >::SCV::vDetJ private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::detJ().
vDetJMap
template<int TWorldDim, int TDim = TWorldDim> std::vector<number> ug::DimFVGeometry< TWorldDim, TDim >::SCV::vDetJMap private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::weight().
vGlobalIP
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathVector<worldDim> > ug::DimFVGeometry< TWorldDim, TDim >::SCV::vGlobalIP private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_ip().
vGloPos
template<int TWorldDim, int TDim = TWorldDim> MathVector<worldDim> ug::DimFVGeometry< TWorldDim, TDim >::SCV::vGloPos[numCo] private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_corner().
vJtInv
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathMatrix<worldDim,dim> > ug::DimFVGeometry< TWorldDim, TDim >::SCV::vJtInv private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::JTInv().
vLocalIP
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathVector<dim> > ug::DimFVGeometry< TWorldDim, TDim >::SCV::vLocalIP private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_ip().
vLocPos
template<int TWorldDim, int TDim = TWorldDim> MathVector<dim> ug::DimFVGeometry< TWorldDim, TDim >::SCV::vLocPos[numCo] private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_corner().
vMidID
template<int TWorldDim, int TDim = TWorldDim> MidID ug::DimFVGeometry< TWorldDim, TDim >::SCV::vMidID[numCo] private
vvGlobalGrad
template<int TWorldDim, int TDim = TWorldDim> std::vector<std::vector<MathVector<worldDim> > > ug::DimFVGeometry< TWorldDim, TDim >::SCV::vvGlobalGrad private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_grad().
vvLocalGrad
template<int TWorldDim, int TDim = TWorldDim> std::vector<std::vector<MathVector<dim> > > ug::DimFVGeometry< TWorldDim, TDim >::SCV::vvLocalGrad private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad(), and ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_grad_vector().
vvShape
template<int TWorldDim, int TDim = TWorldDim> std::vector<std::vector<number> > ug::DimFVGeometry< TWorldDim, TDim >::SCV::vvShape private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::shape(), and ug::DimFVGeometry< TWorldDim, TDim >::SCV::shape_vector().
vWeight
template<int TWorldDim, int TDim = TWorldDim> const number* ug::DimFVGeometry< TWorldDim, TDim >::SCV::vWeight private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCV::weight().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fvho_geom.h