ug4: ug::ConstrainedVertex Class Reference
ug::ConstrainedVertex Class Reference
lib_grid » geometric objects
A vertex appearing on edges or faces.
#include <grid_objects_0d.h>
Public Member Functions
ConstrainedVertex ()
virtual int container_section () const
virtual GridObject * create_empty_instance () const
create an instance of the derived type
GridObject * get_constraining_object ()
number get_local_coordinate_1 () const
number get_local_coordinate_2 () const
const vector2 & get_local_coordinates () const
int get_parent_base_object_id ()
virtual bool is_constrained () const
returns true if the object is constrained by other objects.
virtual ReferenceObjectID reference_object_id () const
virtual void remove_constraint_link (const Edge *e)
removes a constraint link to the grid object.
virtual void remove_constraint_link (const Face *f)
removes a constraint link to the grid object.
void set_constraining_object (GridObject *constrObj)
void set_local_coordinate_1 (number coord)
void set_local_coordinate_2 (number coord)
void set_local_coordinates (const vector2 &coords)
void set_local_coordinates (number x, number y)
void set_parent_base_object_id (int id)
virtual ~ConstrainedVertex ()
Public Member Functions inherited from ug::Vertex
virtual int base_object_id () const
uint32 get_hash_value () const
returns a value that can be used for hashing.
uint num_sides () const
virtual ~Vertex ()
Public Member Functions inherited from ug::GridObject
uint grid_data_index () const
Returns the grid attachment data index of a geometric object.
virtual bool is_constraining () const
returns the id of the reference-object.
virtual ~GridObject ()
virtual void remove_constraint_link (const Vertex *vrt)
removes a constraint link to the grid object.
Static Public Member Functions
static bool type_match (GridObject *pObj)
Static Public Member Functions inherited from ug::Vertex
static bool type_match (GridObject *pObj)
Protected Attributes
GridObject * m_constrainingObj
vector2 m_localCoord
int m_parentBaseObjectId
Protected Attributes inherited from ug::Vertex
uint32 m_hashValue
Protected Attributes inherited from ug::GridObject
uint m_gridDataIndex
Friends
class Grid
Additional Inherited Members
Public Types inherited from ug::Vertex
typedef Vertex grid_base_object
typedef Edge higher_dim_base_object
typedef void lower_dim_base_object
typedef Vertex side
typedef Edge sideof
Static Public Attributes inherited from ug::Vertex
static const int BASE_OBJECT_ID = VERTEX
static const bool CAN_BE_SIDE = true
static const int dim = 0
reference dimension
static const bool HAS_SIDES = false
static const size_t NUM_VERTICES = 1
Protected Member Functions inherited from ug::GridObject
void set_grid_data_index (uint index)
ATTENTION: Use this method with extreme care!
Detailed Description
A vertex appearing on edges or faces.
ConstrainedVertices appear during hanging-vertex-refinement. They should be treated with care, since they are often referenced by other elements, as e.g. by a ConstrainingEdge.
Constructor & Destructor Documentation
ConstrainedVertex()
ug::ConstrainedVertex::ConstrainedVertex () inline
~ConstrainedVertex()
virtual ug::ConstrainedVertex::~ConstrainedVertex () inline virtual
Member Function Documentation
container_section()
virtual int ug::ConstrainedVertex::container_section () const inline virtual
Reimplemented from ug::Vertex.
References ug::CSVRT_CONSTRAINED_VERTEX.
create_empty_instance()
virtual GridObject* ug::ConstrainedVertex::create_empty_instance () const inline virtual
create an instance of the derived type
Make sure to overload this method in derivates of this class!
Reimplemented from ug::GridObject.
get_constraining_object()
GridObject* ug::ConstrainedVertex::get_constraining_object () inline
Referenced by ug::CheckElementConsistency(), ug::CheckHangingNodeConsistency(), ug::CollectConstraining(), ug::MarkForAdaption_GradientAverage(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_vertex(), ug::StdHNodeAdjuster::ref_marks_changed(), and ug::SerializeMultiGridElements().
get_local_coordinate_1()
number ug::ConstrainedVertex::get_local_coordinate_1 () const inline
Referenced by ug::SerializeMultiGridElements().
get_local_coordinate_2()
number ug::ConstrainedVertex::get_local_coordinate_2 () const inline
Referenced by ug::SerializeMultiGridElements().
get_local_coordinates()
const vector2& ug::ConstrainedVertex::get_local_coordinates () const inline
get_parent_base_object_id()
int ug::ConstrainedVertex::get_parent_base_object_id () inline
Referenced by ug::CollectConstraining(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_vertex(), and ug::SerializeMultiGridElements().
is_constrained()
virtual bool ug::ConstrainedVertex::is_constrained () const inline virtual
returns true if the object is constrained by other objects.
This is normally only the case for special constrained objects. The default implementation returns false.
Reimplemented from ug::GridObject.
reference_object_id()
virtual ReferenceObjectID ug::ConstrainedVertex::reference_object_id () const inline virtual
A reference object represents a class of geometric objects. Tetrahedrons, Triangles etc are such classes. Reference ids should be defined in the file in which concrete geometric objects are defined.
Reimplemented from ug::Vertex.
References ug::ROID_VERTEX.
remove_constraint_link() [1/2]
virtual void ug::ConstrainedVertex::remove_constraint_link (const Edge * e) inline virtual
removes a constraint link to the grid object.
This method is e.g. called on the constraining edges of a constrained vertex as soon as the constrained vertex is deleted.
Reimplemented from ug::GridObject.
remove_constraint_link() [2/2]
virtual void ug::ConstrainedVertex::remove_constraint_link (const Face * f) inline virtual
removes a constraint link to the grid object.
This method is e.g. called on the constraining edges of a constrained vertex as soon as the constrained vertex is deleted.
Reimplemented from ug::GridObject.
set_constraining_object()
void ug::ConstrainedVertex::set_constraining_object (GridObject * constrObj) inline
References ug::GridObject::base_object_id().
Referenced by ug::DeserializeMultiGridElements(), ug::GridReaderUGX::grid(), ug::HangingNodeRefiner_MultiGrid::perform_coarsening(), and ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex().
set_local_coordinate_1()
void ug::ConstrainedVertex::set_local_coordinate_1 (number coord) inline
Referenced by ug::DeserializeGridElements(), ug::DeserializeMultiGridElements(), and ug::HangingNodeRefiner_MultiGrid::perform_coarsening().
set_local_coordinate_2()
void ug::ConstrainedVertex::set_local_coordinate_2 (number coord) inline
Referenced by ug::DeserializeGridElements(), and ug::DeserializeMultiGridElements().
set_local_coordinates() [1/2]
void ug::ConstrainedVertex::set_local_coordinates (const vector2 & coords) inline
set_local_coordinates() [2/2]
void ug::ConstrainedVertex::set_local_coordinates (number x, number y) inline
Referenced by ug::GridReaderUGX::create_constrained_vertices(), ug::HangingNodeRefiner_MultiGrid::perform_coarsening(), and ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex().
set_parent_base_object_id()
void ug::ConstrainedVertex::set_parent_base_object_id (int id) inline
References UG_THROW.
Referenced by ug::DeserializeMultiGridElements(), and ug::HangingNodeRefiner_MultiGrid::perform_coarsening().
type_match()
static bool ug::ConstrainedVertex::type_match (GridObject * pObj) inline static
Friends And Related Function Documentation
Grid
friend class Grid friend
Member Data Documentation
m_constrainingObj
GridObject* ug::ConstrainedVertex::m_constrainingObj protected
m_localCoord
vector2 ug::ConstrainedVertex::m_localCoord protected
m_parentBaseObjectId
int ug::ConstrainedVertex::m_parentBaseObjectId protected
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid_objects/grid_objects_0d.h