ug4: ug::AlgebraType Class Reference
ug::AlgebraType Class Reference
lib_algebra
class describing the type of an algebra
#include <algebra_type.h>
Public Types
enum { VariableBlockSize = -1 }
indicating variable block size
enum Type { CPU = 0 , GPU = 1 }
types of algebra
Public Member Functions
AlgebraType ()
empty constructor
AlgebraType (const char *type)
constructor for variable block size
AlgebraType (const char *type, int blockSize)
constructor for fix blocksize
AlgebraType (Type type, int blockSize)
constructor for fix blocksize
int blocksize () const
returns the blocksize
int type () const
returns the type
Protected Attributes
int m_blockSize
int m_type
Detailed Description
class describing the type of an algebra
Member Enumeration Documentation
anonymous enum
anonymous enum
indicating variable block size
Enumerator
VariableBlockSize
Type
enum ug::AlgebraType::Type
types of algebra
Enumerator
CPU
GPU
Constructor & Destructor Documentation
AlgebraType() [1/4]
ug::AlgebraType::AlgebraType ()
empty constructor
AlgebraType() [2/4]
ug::AlgebraType::AlgebraType (Type type, int blockSize)
constructor for fix blocksize
References UG_THROW, and VariableBlockSize.
AlgebraType() [3/4]
ug::AlgebraType::AlgebraType (const char * type, int blockSize)
constructor for fix blocksize
References CPU, GPU, m_type, type(), UG_THROW, and VariableBlockSize.
AlgebraType() [4/4]
ug::AlgebraType::AlgebraType (const char * type)
constructor for variable block size
References CPU, GPU, m_type, type(), and UG_THROW.
Member Function Documentation
blocksize()
int ug::AlgebraType::blocksize () const inline
returns the blocksize
References m_blockSize.
Referenced by ug::bridge::InitUG(), and ug::operator<<().
type()
int ug::AlgebraType::type () const inline
returns the type
References m_type.
Referenced by AlgebraType(), ug::bridge::InitUG(), and ug::operator<<().
Member Data Documentation
m_blockSize
int ug::AlgebraType::m_blockSize protected
Referenced by blocksize().
m_type
int ug::AlgebraType::m_type protected
Referenced by AlgebraType(), and type().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/algebra_type.h
ugbase/lib_algebra/algebra_type.cpp