ug4: ug::ToElementPosition< TElem, TAVrtPos > Class Template Reference
ug::ToElementPosition< TElem, TAVrtPos > Class Template Reference
Public Types
typedef TAVrtPos::ValueType TValue
Public Member Functions
TValue operator() (Edge *e)
TValue operator() (Face *e)
TValue operator() (Vertex *e)
TValue operator() (Volume *e)
ToElementPosition (Grid &g, TAVrtPos &aPos)
Private Attributes
Grid::VertexAttachmentAccessor< TAVrtPos > m_aaPos
Member Typedef Documentation
TValue
template<class TElem , class TAVrtPos > typedef TAVrtPos::ValueType ug::ToElementPosition< TElem, TAVrtPos >::TValue
Constructor & Destructor Documentation
ToElementPosition()
template<class TElem , class TAVrtPos > ug::ToElementPosition< TElem, TAVrtPos >::ToElementPosition (Grid & g, TAVrtPos & aPos) inline
References ug::Grid::has_vertex_attachment().
Member Function Documentation
operator()() [1/4]
template<class TElem , class TAVrtPos > TValue ug::ToElementPosition< TElem, TAVrtPos >::operator() (Edge * e) inline
References ug::CalculateCenter().
operator()() [2/4]
template<class TElem , class TAVrtPos > TValue ug::ToElementPosition< TElem, TAVrtPos >::operator() (Face * e) inline
References ug::CalculateCenter().
operator()() [3/4]
template<class TElem , class TAVrtPos > TValue ug::ToElementPosition< TElem, TAVrtPos >::operator() (Vertex * e) inline
operator()() [4/4]
template<class TElem , class TAVrtPos > TValue ug::ToElementPosition< TElem, TAVrtPos >::operator() (Volume * e) inline
References ug::CalculateCenter().
Member Data Documentation
m_aaPos
template<class TElem , class TAVrtPos > Grid::VertexAttachmentAccessor<TAVrtPos> ug::ToElementPosition< TElem, TAVrtPos >::m_aaPos private
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/parallelization_util.cpp