ug4: ug::SubLocalDoFSet< TDim > Class Template Reference
ug::SubLocalDoFSet< TDim > Class Template Reference
Public Member Functions
virtual bool exact_position_available () const
returns if the local dof position are exact
virtual const LocalDoF & local_dof (size_t dof) const
returns the DoFs storage
virtual size_t num_dof (ReferenceObjectID roid) const
returns the number of DoFs on a sub-geometric object type
virtual size_t num_sh () const
virtual bool position (size_t i, MathVector< TDim > &pos) const
local position of DoF i
virtual ReferenceObjectID roid () const
returns the Reference object id of the corresponding grid object
template<int setDim>
SubLocalDoFSet (const ReferenceObjectID roid, const DimLocalDoFSet< setDim > &set)
Public Member Functions inherited from ug::DimLocalDoFSet< TDim >
DimLocalDoFSet ()
constructor
bool operator!= (const DimLocalDoFSet< TDim > &v) const
inequality check
bool operator== (const DimLocalDoFSet< TDim > &v) const
equality check
Public Member Functions inherited from ug::LocalDoFSet
int dim () const
returns the reference dimension
size_t num_dof (int d, size_t id) const
returns the number of DoFs on a sub-geometric object of dim and id
bool operator!= (const LocalDoFSet &v) const
inequality check
bool operator== (const LocalDoFSet &v) const
equality check
virtual ~LocalDoFSet ()
virtual destructor
size_t num_dof () const
Protected Member Functions
void set (const std::vector< size_t > &vNumDoF, const std::vector< LocalDoF > &vLocalDoF, const std::vector< MathVector< TDim > > &vLocalPos)
Protected Attributes
const bool m_bExactPos
bool m_bInit
const ReferenceObjectID m_roid
Reference ID this DoF Set is for.
std::vector< LocalDoF > m_vLocalDoF
Local DoFs of this set.
std::vector< MathVector< TDim > > m_vLocalPos
Local Positions of DoFs.
std::vector< size_t > m_vNumDoF
Static Private Attributes
static const int dim = TDim
Detailed Description
template<int TDim>
class ug::SubLocalDoFSet< TDim >
Intersection of local dofs
Constructor & Destructor Documentation
SubLocalDoFSet()
template<int TDim> template<int setDim> ug::SubLocalDoFSet< TDim >::SubLocalDoFSet (const ReferenceObjectID roid, const DimLocalDoFSet< setDim > & set) inline
References ug::DimReferenceElement< d >::corner(), ug::LocalDoF::dim(), ug::SubLocalDoFSet< TDim >::dim, ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::LocalDoF::id(), ug::ReferenceElement::id(), ug::SubLocalDoFSet< TDim >::m_roid, ug::ReferenceElement::num(), ug::NUM_REFERENCE_OBJECTS, ug::UGError::push_msg(), ug::ReferenceElementDimension(), ug::SubLocalDoFSet< TDim >::roid(), ug::ReferenceElement::roid(), ug::SubLocalDoFSet< TDim >::set(), and UG_THROW.
Member Function Documentation
exact_position_available()
template<int TDim> virtual bool ug::SubLocalDoFSet< TDim >::exact_position_available () const inline virtual
returns if the local dof position are exact
Implements ug::DimLocalDoFSet< TDim >.
References ug::SubLocalDoFSet< TDim >::m_bExactPos.
Referenced by ug::SubLocalDoFSet< TDim >::position().
local_dof()
template<int TDim> virtual const LocalDoF& ug::SubLocalDoFSet< TDim >::local_dof (size_t dof) const inline virtual
returns the DoFs storage
Implements ug::LocalDoFSet.
References ug::SubLocalDoFSet< TDim >::m_vLocalDoF.
num_dof()
template<int TDim> virtual size_t ug::SubLocalDoFSet< TDim >::num_dof (ReferenceObjectID roid) const inline virtual
returns the number of DoFs on a sub-geometric object type
Implements ug::LocalDoFSet.
References ug::SubLocalDoFSet< TDim >::m_vNumDoF, and ug::SubLocalDoFSet< TDim >::roid().
num_sh()
template<int TDim> virtual size_t ug::SubLocalDoFSet< TDim >::num_sh () const inline virtual
returns the total number of dofs on the finite element
Reimplemented from ug::LocalDoFSet.
References ug::SubLocalDoFSet< TDim >::m_vLocalDoF.
position()
template<int TDim> virtual bool ug::SubLocalDoFSet< TDim >::position (size_t i, MathVector< TDim > & pos) const inline virtual
local position of DoF i
This function returns the local position of a DoF if possible.
Parameters
[in] i number of DoF
[out] pos Position of DoF
Return values
true if position exists
false if no meaningful position available
Implements ug::DimLocalDoFSet< TDim >.
References ug::SubLocalDoFSet< TDim >::exact_position_available(), and ug::SubLocalDoFSet< TDim >::m_vLocalPos.
roid()
template<int TDim> virtual ReferenceObjectID ug::SubLocalDoFSet< TDim >::roid () const inline virtual
returns the Reference object id of the corresponding grid object
Implements ug::LocalDoFSet.
References ug::SubLocalDoFSet< TDim >::m_roid.
Referenced by ug::SubLocalDoFSet< TDim >::num_dof(), and ug::SubLocalDoFSet< TDim >::SubLocalDoFSet().
set()
template<int TDim> void ug::SubLocalDoFSet< TDim >::set (const std::vector< size_t > & vNumDoF, const std::vector< LocalDoF > & vLocalDoF, const std::vector< MathVector< TDim > > & vLocalPos) inline protected
References ug::SubLocalDoFSet< TDim >::m_bInit, ug::SubLocalDoFSet< TDim >::m_vLocalDoF, ug::SubLocalDoFSet< TDim >::m_vLocalPos, ug::SubLocalDoFSet< TDim >::m_vNumDoF, and UG_THROW.
Referenced by ug::SubLocalDoFSet< TDim >::SubLocalDoFSet().
Member Data Documentation
dim
template<int TDim> const int ug::SubLocalDoFSet< TDim >::dim = TDim static private
Referenced by ug::SubLocalDoFSet< TDim >::SubLocalDoFSet().
m_bExactPos
template<int TDim> const bool ug::SubLocalDoFSet< TDim >::m_bExactPos protected
Referenced by ug::SubLocalDoFSet< TDim >::exact_position_available().
m_bInit
template<int TDim> bool ug::SubLocalDoFSet< TDim >::m_bInit protected
Referenced by ug::SubLocalDoFSet< TDim >::set().
m_roid
template<int TDim> const ReferenceObjectID ug::SubLocalDoFSet< TDim >::m_roid protected
Reference ID this DoF Set is for.
Referenced by ug::SubLocalDoFSet< TDim >::roid(), and ug::SubLocalDoFSet< TDim >::SubLocalDoFSet().
m_vLocalDoF
template<int TDim> std::vector<LocalDoF> ug::SubLocalDoFSet< TDim >::m_vLocalDoF protected
Local DoFs of this set.
Referenced by ug::SubLocalDoFSet< TDim >::local_dof(), ug::SubLocalDoFSet< TDim >::num_sh(), and ug::SubLocalDoFSet< TDim >::set().
m_vLocalPos
template<int TDim> std::vector<MathVector<TDim> > ug::SubLocalDoFSet< TDim >::m_vLocalPos protected
Local Positions of DoFs.
Referenced by ug::SubLocalDoFSet< TDim >::position(), and ug::SubLocalDoFSet< TDim >::set().
m_vNumDoF
template<int TDim> std::vector<size_t> ug::SubLocalDoFSet< TDim >::m_vNumDoF protected
Referenced by ug::SubLocalDoFSet< TDim >::num_dof(), and ug::SubLocalDoFSet< TDim >::set().
The documentation for this class was generated from the following file:
ugbase/lib_disc/local_finite_element/local_finite_element_provider.cpp