ug4: ug::AgglomeratingBase< TBase, TAlgebra > Class Template Reference
ug::AgglomeratingBase< TBase, TAlgebra > Class Template Reference abstract
#include <agglomerating_solver.h>
Public Types
typedef TAlgebra algebra_type
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Member Functions
virtual bool apply (vector_type &x, const vector_type &b)
virtual bool apply_agglomerated (vector_type &x, const vector_type &b)=0
virtual bool apply_return_defect (vector_type &u, vector_type &f)
virtual bool apply_update_defect (vector_type &u, vector_type &f)
virtual bool base_init (SmartPtr< ILinearOperator< vector_type > > A)
bool base_init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
Preprocess routine.
void broadcast_vector_from_one (vector_type &x, const vector_type &collectedX, ParallelStorageType type)
bool empty ()
void gather_vector_on_one (vector_type &collectedB, const vector_type &b, ParallelStorageType type)
bool i_am_root ()
virtual bool init_agglomerated (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)=0
void init_collected_vec (vector_type &collectedX)
bool init_mat (const matrix_type &A)
bool is_serial ()
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
virtual ~AgglomeratingBase ()
Protected Attributes
HorizontalAlgebraLayouts agglomerationLayout
vector_type collectedB
vector_type collectedX
bool m_bEmpty
bool m_bRoot
matrix_type * m_pMatrix
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spCollectedOp
SmartPtr< AlgebraLayouts > m_spLocalAlgebraLayouts
Member Typedef Documentation
algebra_type
template<typename TBase , typename TAlgebra > typedef TAlgebra ug::AgglomeratingBase< TBase, TAlgebra >::algebra_type
matrix_type
template<typename TBase , typename TAlgebra > typedef TAlgebra::matrix_type ug::AgglomeratingBase< TBase, TAlgebra >::matrix_type
vector_type
template<typename TBase , typename TAlgebra > typedef TAlgebra::vector_type ug::AgglomeratingBase< TBase, TAlgebra >::vector_type
Constructor & Destructor Documentation
~AgglomeratingBase()
template<typename TBase , typename TAlgebra > virtual ug::AgglomeratingBase< TBase, TAlgebra >::~AgglomeratingBase () inline virtual
Member Function Documentation
apply()
template<typename TBase , typename TAlgebra > virtual bool ug::AgglomeratingBase< TBase, TAlgebra >::apply (vector_type & x, const vector_type & b) inline virtual
References ug::AgglomeratingBase< TBase, TAlgebra >::apply_agglomerated(), ug::AgglomeratingBase< TBase, TAlgebra >::broadcast_vector_from_one(), ug::AgglomeratingBase< TBase, TAlgebra >::collectedB, ug::AgglomeratingBase< TBase, TAlgebra >::collectedX, ug::AgglomeratingBase< TBase, TAlgebra >::empty(), ug::AgglomeratingBase< TBase, TAlgebra >::gather_vector_on_one(), ug::AgglomeratingBase< TBase, TAlgebra >::i_am_root(), ug::AgglomeratingBase< TBase, TAlgebra >::is_serial(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, and UG_CATCH_THROW.
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::apply_return_defect(), ug::AgglomeratingBase< TBase, TAlgebra >::apply_update_defect(), and ug::AgglomeratingBase< TBase, TAlgebra >::step().
apply_agglomerated()
template<typename TBase , typename TAlgebra > virtual bool ug::AgglomeratingBase< TBase, TAlgebra >::apply_agglomerated (vector_type & x, const vector_type & b) pure virtual
Implemented in ug::AgglomeratingPreconditioner< TAlgebra >, ug::AgglomeratingIterator< TAlgebra >, and ug::AgglomeratingSolver< TAlgebra >.
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::apply().
apply_return_defect()
template<typename TBase , typename TAlgebra > virtual bool ug::AgglomeratingBase< TBase, TAlgebra >::apply_return_defect (vector_type & u, vector_type & f) inline virtual
References ug::AgglomeratingBase< TBase, TAlgebra >::apply(), ug::AgglomeratingBase< TBase, TAlgebra >::m_pMatrix, PROFILE_FUNC, and UG_LOG.
apply_update_defect()
template<typename TBase , typename TAlgebra > virtual bool ug::AgglomeratingBase< TBase, TAlgebra >::apply_update_defect (vector_type & u, vector_type & f) inline virtual
References ug::AgglomeratingBase< TBase, TAlgebra >::apply(), ug::AgglomeratingBase< TBase, TAlgebra >::m_pMatrix, PROFILE_FUNC, and UG_LOG.
base_init() [1/2]
template<typename TBase , typename TAlgebra > virtual bool ug::AgglomeratingBase< TBase, TAlgebra >::base_init (SmartPtr< ILinearOperator< vector_type > > A) inline virtual
References ug::AgglomeratingBase< TBase, TAlgebra >::base_init(), SmartPtr< T, FreePolicy >::invalid(), and UG_THROW.
base_init() [2/2]
template<typename TBase , typename TAlgebra > bool ug::AgglomeratingBase< TBase, TAlgebra >::base_init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op) inline
Preprocess routine.
References pcl::AllProcsTrue(), ug::AgglomeratingBase< TBase, TAlgebra >::collectedB, ug::AgglomeratingBase< TBase, TAlgebra >::collectedX, ug::AgglomeratingBase< TBase, TAlgebra >::i_am_root(), ug::AgglomeratingBase< TBase, TAlgebra >::init_agglomerated(), ug::AgglomeratingBase< TBase, TAlgebra >::init_collected_vec(), ug::AgglomeratingBase< TBase, TAlgebra >::init_mat(), ug::AgglomeratingBase< TBase, TAlgebra >::is_serial(), ug::AgglomeratingBase< TBase, TAlgebra >::m_pMatrix, ug::AgglomeratingBase< TBase, TAlgebra >::m_spCollectedOp, PROFILE_BEGIN, PROFILE_END, PROFILE_FUNC, UG_CATCH_THROW, and UG_LOG.
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::base_init(), ug::AgglomeratingSolver< TAlgebra >::init(), and ug::AgglomeratingIterator< TAlgebra >::init().
broadcast_vector_from_one()
template<typename TBase , typename TAlgebra > void ug::AgglomeratingBase< TBase, TAlgebra >::broadcast_vector_from_one (vector_type & x, const vector_type & collectedX, ParallelStorageType type) inline
References ug::AgglomeratingBase< TBase, TAlgebra >::agglomerationLayout, ug::BroadcastVectorFromOne(), ug::AgglomeratingBase< TBase, TAlgebra >::collectedX, and ug::PST_CONSISTENT.
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::apply().
empty()
template<typename TBase , typename TAlgebra > bool ug::AgglomeratingBase< TBase, TAlgebra >::empty () inline
References ug::AgglomeratingBase< TBase, TAlgebra >::m_bEmpty.
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::apply().
gather_vector_on_one()
template<typename TBase , typename TAlgebra > void ug::AgglomeratingBase< TBase, TAlgebra >::gather_vector_on_one (vector_type & collectedB, const vector_type & b, ParallelStorageType type) inline
References ug::AgglomeratingBase< TBase, TAlgebra >::agglomerationLayout, ug::AgglomeratingBase< TBase, TAlgebra >::collectedB, ug::GatherVectorOnOne(), and ug::PST_ADDITIVE.
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::apply().
i_am_root()
template<typename TBase , typename TAlgebra > bool ug::AgglomeratingBase< TBase, TAlgebra >::i_am_root () inline
References ug::AgglomeratingBase< TBase, TAlgebra >::m_bRoot.
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::apply(), ug::AgglomeratingBase< TBase, TAlgebra >::base_init(), and ug::AgglomeratingBase< TBase, TAlgebra >::init_collected_vec().
init_agglomerated()
template<typename TBase , typename TAlgebra > virtual bool ug::AgglomeratingBase< TBase, TAlgebra >::init_agglomerated (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op) pure virtual
Implemented in ug::AgglomeratingPreconditioner< TAlgebra >, ug::AgglomeratingIterator< TAlgebra >, and ug::AgglomeratingSolver< TAlgebra >.
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::base_init().
init_collected_vec()
template<typename TBase , typename TAlgebra > void ug::AgglomeratingBase< TBase, TAlgebra >::init_collected_vec (vector_type & collectedX) inline
References ug::AgglomeratingBase< TBase, TAlgebra >::collectedX, ug::AgglomeratingBase< TBase, TAlgebra >::i_am_root(), ug::AgglomeratingBase< TBase, TAlgebra >::m_spCollectedOp, and ug::AgglomeratingBase< TBase, TAlgebra >::m_spLocalAlgebraLayouts.
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::base_init().
init_mat()
template<typename TBase , typename TAlgebra > bool ug::AgglomeratingBase< TBase, TAlgebra >::init_mat (const matrix_type & A) inline
References ug::AgglomeratingBase< TBase, TAlgebra >::agglomerationLayout, ug::CollectMatrixOnOneProc(), ug::HorizontalAlgebraLayouts::comm(), ug::CreateLocalAlgebraLayouts(), ug::AgglomeratingBase< TBase, TAlgebra >::m_bEmpty, ug::AgglomeratingBase< TBase, TAlgebra >::m_bRoot, ug::AgglomeratingBase< TBase, TAlgebra >::m_spCollectedOp, ug::AgglomeratingBase< TBase, TAlgebra >::m_spLocalAlgebraLayouts, make_sp(), ug::HorizontalAlgebraLayouts::master(), ug::HorizontalAlgebraLayouts::proc_comm(), pcl::ProcRank(), PROFILE_FUNC, ug::HorizontalAlgebraLayouts::slave(), and UG_CATCH_THROW.
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::base_init().
is_serial()
template<typename TBase , typename TAlgebra > bool ug::AgglomeratingBase< TBase, TAlgebra >::is_serial () inline
References ug::AgglomeratingBase< TBase, TAlgebra >::m_pMatrix, and UG_COND_THROW.
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::apply(), and ug::AgglomeratingBase< TBase, TAlgebra >::base_init().
step()
template<typename TBase , typename TAlgebra > virtual bool ug::AgglomeratingBase< TBase, TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) inline virtual
References ug::AgglomeratingBase< TBase, TAlgebra >::apply().
Member Data Documentation
agglomerationLayout
template<typename TBase , typename TAlgebra > HorizontalAlgebraLayouts ug::AgglomeratingBase< TBase, TAlgebra >::agglomerationLayout protected
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::broadcast_vector_from_one(), ug::AgglomeratingBase< TBase, TAlgebra >::gather_vector_on_one(), and ug::AgglomeratingBase< TBase, TAlgebra >::init_mat().
collectedB
template<typename TBase , typename TAlgebra > vector_type ug::AgglomeratingBase< TBase, TAlgebra >::collectedB protected
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::apply(), ug::AgglomeratingBase< TBase, TAlgebra >::base_init(), and ug::AgglomeratingBase< TBase, TAlgebra >::gather_vector_on_one().
collectedX
template<typename TBase , typename TAlgebra > vector_type ug::AgglomeratingBase< TBase, TAlgebra >::collectedX protected
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::apply(), ug::AgglomeratingBase< TBase, TAlgebra >::base_init(), ug::AgglomeratingBase< TBase, TAlgebra >::broadcast_vector_from_one(), and ug::AgglomeratingBase< TBase, TAlgebra >::init_collected_vec().
m_bEmpty
template<typename TBase , typename TAlgebra > bool ug::AgglomeratingBase< TBase, TAlgebra >::m_bEmpty protected
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::empty(), and ug::AgglomeratingBase< TBase, TAlgebra >::init_mat().
m_bRoot
template<typename TBase , typename TAlgebra > bool ug::AgglomeratingBase< TBase, TAlgebra >::m_bRoot protected
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::i_am_root(), and ug::AgglomeratingBase< TBase, TAlgebra >::init_mat().
m_pMatrix
template<typename TBase , typename TAlgebra > matrix_type* ug::AgglomeratingBase< TBase, TAlgebra >::m_pMatrix protected
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::apply_return_defect(), ug::AgglomeratingBase< TBase, TAlgebra >::apply_update_defect(), ug::AgglomeratingBase< TBase, TAlgebra >::base_init(), and ug::AgglomeratingBase< TBase, TAlgebra >::is_serial().
m_spCollectedOp
template<typename TBase , typename TAlgebra > SmartPtr<MatrixOperator<matrix_type, vector_type> > ug::AgglomeratingBase< TBase, TAlgebra >::m_spCollectedOp protected
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::base_init(), ug::AgglomeratingBase< TBase, TAlgebra >::init_collected_vec(), and ug::AgglomeratingBase< TBase, TAlgebra >::init_mat().
m_spLocalAlgebraLayouts
template<typename TBase , typename TAlgebra > SmartPtr<AlgebraLayouts> ug::AgglomeratingBase< TBase, TAlgebra >::m_spLocalAlgebraLayouts protected
Referenced by ug::AgglomeratingBase< TBase, TAlgebra >::init_collected_vec(), and ug::AgglomeratingBase< TBase, TAlgebra >::init_mat().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/linear_solver/agglomerating_solver.h