ug4: ug::DegeneratedLayerManager< dim > Class Template Reference
ug::DegeneratedLayerManager< dim > Class Template Reference
Gegenerated layer subset manager.
#include <deg_layer_mngr.h>
Public Types
typedef grid_dim_traits< dim >::grid_base_object element_type
base grid element object type
typedef Attachment< signed char > mark_attachment_type
type of the attachment for the marks
typedef grid_dim_traits< dim >::side_type side_type
grid element's side base object type
enum t_grid_object_mark { D_LAYER_UNKNOWN = -1, D_LAYER_OUTER = 0, D_LAYER_INNER = 1 }
Marks for the grid vertices.
Public Member Functions
void add (const char *ss_names)
Adds a fracture subdomain.
int assign_middle_subset (int layer_si, int middle_si=-1)
Assigns a different subset index to the inner sides of a layer.
int assign_middle_subset (int layer_si, const char *middle_ss_name)
Assigns a different subset to the inner sides of a layer.
int assign_middle_subset (const char *layer_ss_name, const char *middle_ss_name)
Assigns a different subset to the inner sides of a layer.
void close ()
Closes the manager, i.e. computes all the data, ...
bool contains (int si)
Whether a subset is registered in the manager.
DegeneratedLayerManager (SmartPtr< MultiGridSubsetHandler > spSH)
Constructor.
void get_layer_sides (element_type *elem, size_t &num_fract_co, side_type *&inner_side, size_t &inner_side_idx, size_t inner_side_corners[], side_type *&outer_side, size_t &outer_side_idx, size_t outer_side_corners[], size_t ass_co[])
Gets the inner and the outer fracture sides of an element.
void init_refiner (SmartPtr< GlobalFracturedMediaRefiner > refiner, bool as_low_dim)
Initializes a refiner with the fracture subsets.
bool is_closed ()
Returns true if the manager is closed (and can be used) or false otherwise.
size_t num_subsets ()
Number of subsets in the manager.
void remove (const char *ss_names)
Removes a fracture subdomain (e.g. for dimension-adaptive method)
int subset (size_t i)
Subset #i in the manager (only if the manager is closed)
const SubsetGroup & subset_grp ()
Returns the subset group of the fracture network.
int vert_mark (Vertex *vrt)
Returs the mark of a vertex.
virtual ~DegeneratedLayerManager ()
Destructor.
Static Public Attributes
static const size_t maxElemCorners = grid_dim_traits<dim>::MaxNumVerticesOfElem
max. number of corners of the elements
static const size_t maxLayerSideCorners = maxElemCorners / 2
max. number of corners of non-degenerated sides
Protected Member Functions
void grid_adaption_callback (const GridMessage_Adaption &msg)
Called when a grid adaption has been performed.
void grid_distribution_callback (const GridMessage_Distribution &msg)
Called when a grid has been distributed between different processes.
void mark_vertices ()
Marks the inner fracture vertices.
Private Attributes
MultiGrid::AttachmentAccessor< Vertex, mark_attachment_type > m_aaVertMarks
Attachment accessor.
mark_attachment_type m_aVertexMarks
Attachment keeping the grid object marks for the vertices.
bool m_bClosed
'closed'-flag
SubsetGroup m_layerSsGrp
Subset group of the fractures.
MessageHub::SPCallbackId m_spGridAdaptionCallbackID
MessageHub::SPCallbackId m_spGridDistributionCallbackID
SmartPtr< MultiGridSubsetHandler > m_spSH
Subset handler to use.
Detailed Description
template<int dim>
class ug::DegeneratedLayerManager< dim >
Gegenerated layer subset manager.
Class for the manager of the degenerated layer (e.g. fracture) subsets. Note that the object of the class should get ALL the subsets that belong to ALL the degenerated layers in the domain. This object gets updated every time the grid is refined.
Usage instructions:
Create the object of the DegeneratedLayerManager class
Use the method DegeneratedLayerManager::add to register a degenerated layer subsets in the object
Call the DegeneratedLayerManager::close method to mark the vertices as 'inner' or 'outer'.
Remarks:
The grid must be created (loaded) before the object is created.
All the degenerated layer subsets must be registered in the same degenerated layer manager. There should exist only one such the manager at all. Alternatively, the different managers must hold groups of the layers that are not intersect or connected to each other. But every degenerated subset must be registered in one of the degenerated layer managers.
References:
S. Reiter, D. Logashenko, A. Grillo, G. Wittum, Preparation of grids for simulations of groundwater flow in fractured porous media, Computing and Visualization in Science, Vol. 15, No. 4 (2012), pp. 209-225, DOI: 10.1007/s00791-013-0210-7
Template Parameters
dim (topological) dimensionality of the grid
Member Typedef Documentation
template<int dim> typedef grid_dim_traits<dim>::grid_base_object ug::DegeneratedLayerManager< dim >::element_type
base grid element object type
template<int dim> typedef Attachment<signed char> ug::DegeneratedLayerManager< dim >::mark_attachment_type
type of the attachment for the marks
template<int dim> typedef grid_dim_traits<dim>::side_type ug::DegeneratedLayerManager< dim >::side_type
grid element's side base object type
Member Enumeration Documentation
template<int dim> enum ug::DegeneratedLayerManager::t_grid_object_mark
Marks for the grid vertices.
Enumerator
D_LAYER_UNKNOWN
D_LAYER_OUTER
D_LAYER_INNER
Constructor & Destructor Documentation
template<int dim> ug::DegeneratedLayerManager< dim >::DegeneratedLayerManager (SmartPtr< MultiGridSubsetHandler > spSH)
Constructor.
Class constructor: Parses the subset names, attaches itself to the grid to be updated if the grid is refined, and writes itself to the properties of the subsets.
Parameters
[in] spSH subset handler of the grid
References ug::Grid::message_hub(), ug::MessageHub::register_class_callback(), and UG_THROW.
template<int dim> ug::DegeneratedLayerManager< dim >::~DegeneratedLayerManager () virtual
Destructor.
Class destructor: Detaches the attachment.
References ug::DegeneratedLayerManager< dim >::add().
Member Function Documentation
template<int dim> void ug::DegeneratedLayerManager< dim >::add (const char * ss_names)
Adds a fracture subdomain.
Adds subsets to the manager
Parameters
[in] ss_names subset names of the fractures
References ug::DegeneratedLayerManager< dim >::remove(), ug::TokenizeString(), and UG_LOG.
Referenced by ug::DegeneratedLayerManager< dim >::~DegeneratedLayerManager().
template<int dim> int ug::DegeneratedLayerManager< dim >::assign_middle_subset (int layer_si, int middle_si = -1)
Assigns a different subset index to the inner sides of a layer.
Assigns a different subset index to the inner sides of a layer. (Only to the sides, not vertices, or edges in 3d!) If -1 passed instead of the index of the subset to assign, new subset is created. The function returns the index of the assigned subset.
Parameters
layer_si subset index of the layer
middle_si the subset index to assign (or -1 to create a new subset)
References ug::GMCT_CREATION_STARTS, ug::GMCT_CREATION_STOPS, ug::Grid::message_hub(), ug::MultiGrid::num_levels(), and ug::MessageHub::post_message().
Referenced by ug::DegeneratedLayerManager< dim >::assign_middle_subset(), ug::DegeneratedLayerManager< dim >::get_layer_sides(), and ug::DegeneratedLayerManager< dim >::vert_mark().
template<int dim> int ug::DegeneratedLayerManager< dim >::assign_middle_subset (int layer_si, const char * middle_ss_name)
Assigns a different subset to the inner sides of a layer.
Assigns a different subset to the inner sides of a layer. (Only to the sides, not vertices, or edges in 3d!) If the given subset does not exist, it is created. The function returns the index of the assigned subset.
Parameters
layer_si subset index of the layer
middle_ss_name name of the subset to assign
References ug::DegeneratedLayerManager< dim >::assign_middle_subset().
template<int dim> int ug::DegeneratedLayerManager< dim >::assign_middle_subset (const char * layer_ss_name, const char * middle_ss_name)
Assigns a different subset to the inner sides of a layer.
Assigns a different subset to the inner sides of a layer. (Only to the sides, not vertices, or edges in 3d!) If the given subset does not exist, it is created. The function returns the index of the assigned subset.
Parameters
layer_ss_name subset name of the layer
middle_ss_name name of the subset to assign
References UG_THROW.
template<int dim> void ug::DegeneratedLayerManager< dim >::close ()
Closes the manager, i.e. computes all the data, ...
Closes the manager: Computes the vertex marks
References dim, ug::DimensionOfSubset(), ug::DegeneratedLayerManager< dim >::init_refiner(), UG_LOG, and UG_THROW.
template<int dim> bool ug::DegeneratedLayerManager< dim >::contains (int si) inline
Whether a subset is registered in the manager.
Parameters
[in] si subset index
References ug::SubsetGroup::contains(), and ug::DegeneratedLayerManager< dim >::m_layerSsGrp.
Referenced by ug::DegeneratedLayerManager< dim >::is_closed().
template<int dim> void ug::DegeneratedLayerManager< dim >::get_layer_sides (element_type * elem, size_t & num_side_co, side_type *& inner_side, size_t & inner_side_idx, size_t inner_side_corners[], side_type *& outer_side, size_t & outer_side_idx, size_t outer_side_corners[], size_t ass_co[])
Gets the inner and the outer fracture sides of an element.
For a given element, finds its inner and outer layer sides. For these sides, gets the correspondence of the vertices in the degenerated element (i.e. considering all other sides as degenerated).
Parameters
[in] elem the element
[out] num_side_co number of corners of the inner/outer sides
[out] inner_side its fracture inner side
[out] inner_side_idx index of the inner side in the reference element
[out] inner_side_corners inner side corner idx -> elem. corner idx
[out] outer_side its fracture outer side
[out] outer_side_idx index of the outer side in the reference element
[out] outer_side_corners outer side corner idx -> elem. corner idx
[out] ass_co correspondence of the corners of the sides
References ug::DegeneratedLayerManager< dim >::assign_middle_subset(), ug::Grid::associated_elements(), ug::Grid::get_side(), ug::PointerConstArray< TPtr >::size(), UG_ASSERT, UG_THROW, and ug::EdgeVertices::vertex().
Referenced by ug::DegeneratedLayerManager< dim >::grid_distribution_callback(), and ug::DegeneratedLayerManager< dim >::vert_mark().
template<int dim> void ug::DegeneratedLayerManager< dim >::grid_adaption_callback (const GridMessage_Adaption & msg) protected
Called when a grid adaption has been performed.
The grid adaption callback: Catches the messages about grid refinements, ...
Parameters
msg the message from the message hub
References ug::GridMessage_Adaption::adaption_ends(), and ug::DegeneratedLayerManager< dim >::grid_distribution_callback().
Referenced by ug::DegeneratedLayerManager< dim >::mark_vertices(), and ug::DegeneratedLayerManager< dim >::vert_mark().
template<int dim> void ug::DegeneratedLayerManager< dim >::grid_distribution_callback (const GridMessage_Distribution & msg) protected
Called when a grid has been distributed between different processes.
The grid adaption callback: Catches the messages about the distribution of the grid
Parameters
msg the message from the message hub
References ug::DegeneratedLayerManager< dim >::get_layer_sides(), ug::GMDT_DISTRIBUTION_STOPS, and ug::GridMessage_Distribution::msg().
Referenced by ug::DegeneratedLayerManager< dim >::grid_adaption_callback(), and ug::DegeneratedLayerManager< dim >::vert_mark().
template<int dim> void ug::DegeneratedLayerManager< dim >::init_refiner (SmartPtr< GlobalFracturedMediaRefiner > refiner, bool as_low_dim)
Initializes a refiner with the fracture subsets.
Adds the registered subsets to the refiner
Parameters
refiner the refiner
as_low_dim whether it should consider the fractures as low-dimentional
References ug::GlobalFracturedMediaRefiner::mark_as_fracture(), and UG_THROW.
Referenced by ug::DegeneratedLayerManager< dim >::close().
template<int dim> bool ug::DegeneratedLayerManager< dim >::is_closed () inline
Returns true if the manager is closed (and can be used) or false otherwise.
References ug::DegeneratedLayerManager< dim >::contains(), and ug::DegeneratedLayerManager< dim >::m_bClosed.
Referenced by ug::DegeneratedLayerManager< dim >::subset().
template<int dim> void ug::DegeneratedLayerManager< dim >::mark_vertices () protected
Marks the inner fracture vertices.
Marks the vertices in such a way that the inner layer vertices are marked with D_LAYER_INNER, whereas all other vertices (at the fractures and in the bulk medium) are marked with D_LAYER_OUTER. After the call, there should be no vertices marked with D_LAYER_UNKNOWN.
References dim, ug::DimensionOfSubset(), ug::DegeneratedLayerManager< dim >::grid_adaption_callback(), ug::GridObject::is_constrained(), and ug::MultiGrid::num_levels().
Referenced by ug::DegeneratedLayerManager< dim >::vert_mark().
template<int dim> size_t ug::DegeneratedLayerManager< dim >::num_subsets () inline
Number of subsets in the manager.
References ug::DegeneratedLayerManager< dim >::m_layerSsGrp, and ug::SubsetGroup::size().
template<int dim> void ug::DegeneratedLayerManager< dim >::remove (const char * ss_names)
Removes a fracture subdomain (e.g. for dimension-adaptive method)
Removes subsets from the manager
Parameters
[in] ss_names subset names of the fractures
References ug::TokenizeString().
Referenced by ug::DegeneratedLayerManager< dim >::add().
template<int dim> int ug::DegeneratedLayerManager< dim >::subset (size_t i) inline
Subset #i in the manager (only if the manager is closed)
References ug::DegeneratedLayerManager< dim >::is_closed(), ug::DegeneratedLayerManager< dim >::m_layerSsGrp, and UG_THROW.
template<int dim> const SubsetGroup& ug::DegeneratedLayerManager< dim >::subset_grp () inline
Returns the subset group of the fracture network.
References ug::DegeneratedLayerManager< dim >::m_layerSsGrp.
template<int dim> int ug::DegeneratedLayerManager< dim >::vert_mark (Vertex * vrt) inline
Returs the mark of a vertex.
References ug::DegeneratedLayerManager< dim >::assign_middle_subset(), ug::DegeneratedLayerManager< dim >::get_layer_sides(), ug::DegeneratedLayerManager< dim >::grid_adaption_callback(), ug::DegeneratedLayerManager< dim >::grid_distribution_callback(), ug::DegeneratedLayerManager< dim >::m_aaVertMarks, and ug::DegeneratedLayerManager< dim >::mark_vertices().
Member Data Documentation
template<int dim> MultiGrid::AttachmentAccessor<Vertex, mark_attachment_type> ug::DegeneratedLayerManager< dim >::m_aaVertMarks private
Attachment accessor.
Referenced by ug::DegeneratedLayerManager< dim >::vert_mark().
template<int dim> mark_attachment_type ug::DegeneratedLayerManager< dim >::m_aVertexMarks private
Attachment keeping the grid object marks for the vertices.
template<int dim> bool ug::DegeneratedLayerManager< dim >::m_bClosed private
'closed'-flag
Referenced by ug::DegeneratedLayerManager< dim >::is_closed().
template<int dim> SubsetGroup ug::DegeneratedLayerManager< dim >::m_layerSsGrp private
Subset group of the fractures.
Referenced by ug::DegeneratedLayerManager< dim >::contains(), ug::DegeneratedLayerManager< dim >::num_subsets(), ug::DegeneratedLayerManager< dim >::subset(), and ug::DegeneratedLayerManager< dim >::subset_grp().
template<int dim> MessageHub::SPCallbackId ug::DegeneratedLayerManager< dim >::m_spGridAdaptionCallbackID private
template<int dim> MessageHub::SPCallbackId ug::DegeneratedLayerManager< dim >::m_spGridDistributionCallbackID private
template<int dim> SmartPtr<MultiGridSubsetHandler> ug::DegeneratedLayerManager< dim >::m_spSH private
Subset handler to use.
template<int dim> const size_t ug::DegeneratedLayerManager< dim >::maxElemCorners = grid_dim_traits<dim>::MaxNumVerticesOfElem static
max. number of corners of the elements
template<int dim> const size_t ug::DegeneratedLayerManager< dim >::maxLayerSideCorners = maxElemCorners / 2 static
max. number of corners of non-degenerated sides
The documentation for this class was generated from the following files:
ugbase/lib_grid/algorithms/deg_layer_mngr.h
ugbase/lib_grid/algorithms/deg_layer_mngr_impl.h