ug4: ug::LocalMarkAdjuster Class Reference
ug::LocalMarkAdjuster Class Reference
Use this adjuster on top of StdHNodeAdjuster if local-marks are present.
#include <local_mark_adjuster.h>
Public Member Functions
virtual void ref_marks_changed (IRefiner &ref, const std::vector< Vertex * > &vrts, const std::vector< Edge * > &edges, const std::vector< Face * > &faces, const std::vector< Volume * > &vols)
virtual ~LocalMarkAdjuster ()
Public Member Functions inherited from ug::IRefMarkAdjuster
virtual void coarsen_marks_changed (IRefiner &ref, const std::vector< Vertex * > &vrts, const std::vector< Edge * > &edges, const std::vector< Face * > &faces, const std::vector< Volume * > &vols)
virtual void enable (bool enable)
virtual bool enabled () const
IRefMarkAdjuster ()
virtual ~IRefMarkAdjuster ()
void enable_node_dependency_order_1 (bool bEnable)
enables or disables node-dependency-order-1.
bool node_dependency_order_1_enabled ()
enables or disables node-dependency-order-1.
Static Public Member Functions
static SPLocalMarkAdjuster create ()
Detailed Description
Use this adjuster on top of StdHNodeAdjuster if local-marks are present.
If an element with a local-mark is connected to a constraining edge/face which will be refined, then the element has to be fully refined.
Constructor & Destructor Documentation
~LocalMarkAdjuster()
virtual ug::LocalMarkAdjuster::~LocalMarkAdjuster () inline virtual
Member Function Documentation
create()
static SPLocalMarkAdjuster ug::LocalMarkAdjuster::create () inline static
Referenced by ug::HangingNodeRefiner_Grid::attach_local_marks().
ref_marks_changed()
void ug::LocalMarkAdjuster::ref_marks_changed (IRefiner & ref, const std::vector< Vertex * > & vrts, const std::vector< Edge * > & edges, const std::vector< Face * > & faces, const std::vector< Volume * > & vols) virtual
Reimplemented from ug::IRefMarkAdjuster.
References ug::Grid::associated_elements(), ug::Grid::associated_elements_sorted(), ug::Grid::get_edge(), ug::IRefiner::get_local_edge_mark(), ug::IRefiner::get_local_face_mark(), ug::IRefiner::get_local_mark(), ug::IRefiner::get_mark(), ug::IRefiner::grid(), ug::GridObject::is_constraining(), ug::IRefiner::mark(), ug::IRefiner::mark_local(), ug::IRefiner::marked_full(), ug::IRefiner::marked_local(), ug::Face::num_edges(), ug::Volume::num_edges(), ug::PointerConstArray< TPtr >::reserve(), ug::RM_FULL, ug::RM_LOCAL, and ug::PointerConstArray< TPtr >::size().
The documentation for this class was generated from the following files:
ugbase/lib_grid/refinement/ref_mark_adjusters/local_mark_adjuster.h
ugbase/lib_grid/refinement/ref_mark_adjusters/local_mark_adjuster.cpp