ug4: ug::FlexLagrangeLSFS< ReferenceQuadrilateral > Class Template Reference
ug::FlexLagrangeLSFS< ReferenceQuadrilateral > Class Template Reference
#include <lagrange.h>
Public Member Functions
void check_index (size_t i) const
checks in debug mode that index is valid
void check_multi_index (const MathVector< dim, int > &ind) const
checks in debug mode that multi-index is valid
bool continuous () const
returns if space constructs continuous functions
FlexLagrangeLSFS ()
default Constructor
FlexLagrangeLSFS (size_t order)
Constructor.
void grad (grad_type &g, const size_t i, const MathVector< dim > &x) const
evaluates the gradient of the shape function
void grad (grad_type &g, const MathVector< dim, int > ind, const MathVector< dim > &x) const
evaluates the gradient
size_t index (const MathVector< dim, int > &ind) const
return the index for a multi_index
size_t mapped_index (const MathVector< dim, int > &ind) const
return the index for a multi_index
MathVector< dim, int > mapped_multi_index (size_t i) const
return the multi_index for an index
const MathVector< dim, int > & multi_index (size_t i) const
return Multi index for index i
size_t num_sh () const
bool position (size_t i, MathVector< dim > &pos) const
local position of DoF i
void set_order (size_t order)
sets the order
number shape (const size_t i, const MathVector< dim > &x) const
evaluates the shape function
number shape (const MathVector< dim, int > &ind, const MathVector< dim > &x) const
shape value for a Multi Index
Public Member Functions inherited from ug::LagrangeLDS< ReferenceQuadrilateral >
bool exact_position_available () const
returns if the local dof position are exact
LagrangeLDS (size_t order=1)
constructor
const LocalDoF & local_dof (size_t dof) const
returns the dof storage
size_t num_dof () const
returns the total number of DoFs on the finite element
size_t num_dof (ReferenceObjectID roid) const
returns the number of DoFs on a sub-geometric object type
ReferenceObjectID roid () const
returns the type of reference element
void set_order (size_t order)
sets the order
Public Member Functions inherited from ug::LocalDoFSet
int dim () const
returns the reference dimension
size_t num_dof (int d, size_t id) const
returns the number of DoFs on a sub-geometric object of dim and id
bool operator!= (const LocalDoFSet &v) const
inequality check
bool operator== (const LocalDoFSet &v) const
equality check
virtual ~LocalDoFSet ()
virtual destructor
size_t num_dof () const
Public Member Functions inherited from ug::BaseLSFS< FlexLagrangeLSFS< ReferenceQuadrilateral >, 2 >
void grad (grad_type &g, size_t i, const MathVector< dim > &x) const
evaluates the gradient of the shape function
void grads (grad_type *vGrad, const MathVector< dim > &x) const
returns all gradients evaluated at a point
void grads (std::vector< grad_type > &vGrad, const MathVector< dim > &x) const
returns all gradients evaluated at a point
void grads (std::vector< std::vector< grad_type > > &vvGrad, const std::vector< MathVector< dim > > &vLocPos) const
returns all gradients evaluated at a point
shape_type shape (size_t i, const MathVector< dim > &x) const
evaluates the shape function
void shape (shape_type &sh, size_t i, const MathVector< dim > &x) const
evaluates the shape function
void shapes (shape_type *vShape, const MathVector< dim > &x) const
returns all shape functions evaluated at a point
void shapes (std::vector< shape_type > &vShape, const MathVector< dim > &x) const
returns all shape functions evaluated at a point
void shapes (std::vector< std::vector< shape_type > > &vvShape, const std::vector< MathVector< dim > > &vLocPos) const
returns all shape functions evaluated at a point
Static Public Attributes
static const int dim = ReferenceQuadrilateral::dim
Dimension, where shape functions are defined.
Static Public Attributes inherited from ug::BaseLSFS< FlexLagrangeLSFS< ReferenceQuadrilateral >, 2 >
static const int dim
dimension of reference element
Private Attributes
std::vector< Polynomial1D > m_vDPolynom
Derivative of Shape Polynomial.
std::vector< MathVector< dim, int > > m_vMultiIndex
std::vector< Polynomial1D > m_vPolynom
Shape Polynomials.
size_t nsh
Number of shape functions.
size_t p
order
Additional Inherited Members
Public Types inherited from ug::BaseLSFS< FlexLagrangeLSFS< ReferenceQuadrilateral >, 2 >
typedef MathVector< TDim > grad_type
Gradient type.
typedef FlexLagrangeLSFS< ReferenceQuadrilateral > ImplType
type of implementation
typedef number shape_type
Shape type.
Protected Member Functions inherited from ug::BaseLSFS< FlexLagrangeLSFS< ReferenceQuadrilateral >, 2 >
ImplType & getImpl ()
access to implementation
const ImplType & getImpl () const
const access to implementation
Protected Attributes inherited from ug::LagrangeLDS< ReferenceQuadrilateral >
std::vector< LocalDoF > m_vLocalDoF
association to geom obj
size_t p
order
Constructor & Destructor Documentation
ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::FlexLagrangeLSFS () inline
default Constructor
ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::FlexLagrangeLSFS (size_t order) inline
Constructor.
Member Function Documentation
void ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::check_index (size_t i) const inline
checks in debug mode that index is valid
References UG_ASSERT.
void ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::check_multi_index (const MathVector< dim, int > & ind) const inline
checks in debug mode that multi-index is valid
References UG_ASSERT.
bool ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::continuous () const inline
returns if space constructs continuous functions
void ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::grad (grad_type & g, const size_t i, const MathVector< dim > & x) const inline
evaluates the gradient of the shape function
This function returns the gradient of Shape Function i at an element-local evaluation point.
Parameters
[in] i number of DoF
[in] x Position on reference element (evaluation point)
Returns
gradient at point
void ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::grad (grad_type & g, const MathVector< dim, int > ind, const MathVector< dim > & x) const inline
evaluates the gradient
References dim.
size_t ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::index (const MathVector< dim, int > & ind) const inline
return the index for a multi_index
References UG_THROW.
Referenced by ug::ComputeMultiIndicesOfSubElement< 2 >().
size_t ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::mapped_index (const MathVector< dim, int > & ind) const inline
return the index for a multi_index
MathVector<dim,int> ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::mapped_multi_index (size_t i) const inline
return the multi_index for an index
const MathVector<dim,int>& ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::multi_index (size_t i) const inline
return Multi index for index i
size_t ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::num_sh () const inline virtual
returns the total number of dofs on the finite element
Reimplemented from ug::LocalDoFSet.
bool ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::position (size_t i, MathVector< dim > & pos) const inline
local position of DoF i
This function returns the local position of a DoF if possible.
Parameters
[in] i number of DoF
[out] pos Position of DoF
Return values
true if position exists
false if no meaningful position available
References dim, and ug::EquidistantLagrange1D::position().
void ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::set_order (size_t order)
sets the order
References ug::Provider< TClass >::get(), ug::LagrangeLDS< TRefElem >::set_order(), and ug::SetLagrangeMultiIndex().
number ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::shape (const size_t i, const MathVector< dim > & x) const inline
evaluates the shape function
This function returns the value of Shape Function i at an element-local evaluation point.
Parameters
[in] i number of DoF
[in] x Position on reference element (evaluation point)
Returns
shape function value at point
number ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::shape (const MathVector< dim, int > & ind, const MathVector< dim > & x) const inline
shape value for a Multi Index
Member Data Documentation
const int ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::dim = ReferenceQuadrilateral::dim static
Dimension, where shape functions are defined.
std::vector<Polynomial1D> ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::m_vDPolynom private
Derivative of Shape Polynomial.
std::vector<MathVector<dim,int> > ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::m_vMultiIndex private
std::vector<Polynomial1D> ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::m_vPolynom private
Shape Polynomials.
size_t ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::nsh private
Number of shape functions.
size_t ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::p private
order
The documentation for this class was generated from the following files:
ugbase/lib_disc/local_finite_element/lagrange/lagrange.h
ugbase/lib_disc/local_finite_element/lagrange/lagrange.cpp