ug4: ug::IVector Class Reference
ug::IVector Class Reference abstract
#include <ivector.h>
Public Member Functions
virtual size_t capacity () const =0
virtual void clear ()=0
virtual SmartPtr< IVector > clone () const =0
clones the vector (deep-copy) including values
virtual SmartPtr< IVector > clone_without_values (size_t size) const =0
clones the vector (deep-copy) excluding values
template<typename T >
T & downcast ()
template<typename T >
const T & downcast () const
double norm () const
virtual double norm2 () const =0
void operator*= (double alpha)
void operator+= (const IVector &v)
void operator+= (const TE_VecAdd2< IVector > &t)
void operator+= (const TE_VecAdd3< IVector > &t)
void operator-= (const IVector &v)
void operator-= (const TE_VecAdd2< IVector > &t)
void operator-= (const TE_VecAdd3< IVector > &t)
void operator= (const IVector &v)
void operator= (const TE_VecAdd2< IVector > &t)
void operator= (const TE_VecAdd3< IVector > &t)
void operator= (const TE_VecScale< IVector > &t)
virtual void print (std::ostream &output) const =0
virtual void resize (size_t newSize, bool bCopyValues=true)=0
virtual void set (double d)=0
virtual std::string short_desc () const =0
virtual size_t size () const =0
virtual void vec_add (double a1, double a2, const IVector &iv2)=0
virtual void vec_add (double a1, double a2, const IVector &iv2, double a3, const IVector &iv3)=0
virtual void vec_add (double a1, double a2, const IVector &iv2, double a3, const IVector &iv3, double a4, const IVector &iv4)=0
virtual double vec_prod (const IVector &v) const =0
Public Member Functions inherited from ug::TE_Vector< IVector >
double scaling () const
const IVector & vec () const
Public Member Functions inherited from ug::TE_AlphaVec< T >
const T & cast () const
double scaling () const
Additional Inherited Members
Public Types inherited from ug::TE_Vector< IVector >
typedef IVector vector_type
Member Function Documentation
capacity()
virtual size_t ug::IVector::capacity () const pure virtual
clear()
virtual void ug::IVector::clear () pure virtual
clone()
virtual SmartPtr<IVector> ug::IVector::clone () const pure virtual
clones the vector (deep-copy) including values
clone_without_values()
virtual SmartPtr<IVector> ug::IVector::clone_without_values (size_t size) const pure virtual
clones the vector (deep-copy) excluding values
downcast() [1/2]
template<typename T > T& ug::IVector::downcast () inline
References ug::TypeName(), and UG_ASSERT.
Referenced by ug::IVector_AlgebraDownCastTo< TVec >::vec_add(), and ug::IVector_AlgebraDownCastTo< TVec >::vec_prod().
downcast() [2/2]
template<typename T > const T& ug::IVector::downcast () const inline
References ug::TypeName(), and UG_ASSERT.
norm()
double ug::IVector::norm () const inline
References norm2().
norm2()
virtual double ug::IVector::norm2 () const pure virtual
Implemented in ug::IVector_AlgebraDownCastTo< TVec >.
Referenced by norm().
operator*=()
void ug::IVector::operator*= (double alpha) inline
References alpha, and vec_add().
operator+=() [1/3]
void ug::IVector::operator+= (const IVector & v) inline
References vec_add().
operator+=() [2/3]
void ug::IVector::operator+= (const TE_VecAdd2< IVector > & t) inline
References ug::TE_VecAdd2< T >::a1, ug::TE_VecAdd2< T >::a2, ug::TE_VecAdd2< T >::v1, ug::TE_VecAdd2< T >::v2, and vec_add().
operator+=() [3/3]
void ug::IVector::operator+= (const TE_VecAdd3< IVector > & t) inline
References ug::TE_VecAdd3< T >::a1, ug::TE_VecAdd3< T >::a2, ug::TE_VecAdd3< T >::a3, ug::TE_VecAdd3< T >::v1, ug::TE_VecAdd3< T >::v2, ug::TE_VecAdd3< T >::v3, and vec_add().
operator-=() [1/3]
void ug::IVector::operator-= (const IVector & v) inline
References vec_add().
operator-=() [2/3]
void ug::IVector::operator-= (const TE_VecAdd2< IVector > & t) inline
References ug::TE_VecAdd2< T >::a1, ug::TE_VecAdd2< T >::a2, ug::TE_VecAdd2< T >::v1, ug::TE_VecAdd2< T >::v2, and vec_add().
operator-=() [3/3]
void ug::IVector::operator-= (const TE_VecAdd3< IVector > & t) inline
References ug::TE_VecAdd3< T >::a1, ug::TE_VecAdd3< T >::a2, ug::TE_VecAdd3< T >::a3, ug::TE_VecAdd3< T >::v1, ug::TE_VecAdd3< T >::v2, ug::TE_VecAdd3< T >::v3, and vec_add().
operator=() [1/4]
void ug::IVector::operator= (const IVector & v) inline
References vec_add().
operator=() [2/4]
void ug::IVector::operator= (const TE_VecAdd2< IVector > & t) inline
References ug::TE_VecAdd2< T >::a1, ug::TE_VecAdd2< T >::a2, ug::TE_VecAdd2< T >::v1, ug::TE_VecAdd2< T >::v2, and vec_add().
operator=() [3/4]
void ug::IVector::operator= (const TE_VecAdd3< IVector > & t) inline
References ug::TE_VecAdd3< T >::a1, ug::TE_VecAdd3< T >::a2, ug::TE_VecAdd3< T >::a3, ug::TE_VecAdd3< T >::v1, ug::TE_VecAdd3< T >::v2, ug::TE_VecAdd3< T >::v3, and vec_add().
operator=() [4/4]
void ug::IVector::operator= (const TE_VecScale< IVector > & t) inline
References ug::TE_VecScale< T >::scaling(), ug::TE_VecScale< T >::vec(), and vec_add().
print()
virtual void ug::IVector::print (std::ostream & output) const pure virtual
Implemented in ug::IVector_AlgebraDownCastTo< TVec >.
resize()
virtual void ug::IVector::resize (size_t newSize, bool bCopyValues = true) pure virtual
set()
virtual void ug::IVector::set (double d) pure virtual
Implemented in ug::IVector_AlgebraDownCastTo< TVec >.
short_desc()
virtual std::string ug::IVector::short_desc () const pure virtual
Implemented in ug::IVector_AlgebraDownCastTo< TVec >.
size()
virtual size_t ug::IVector::size () const pure virtual
Referenced by ug::IVector_AlgebraDownCastTo< TVec >::short_desc().
vec_add() [1/3]
virtual void ug::IVector::vec_add (double a1, double a2, const IVector & iv2) pure virtual
Implemented in ug::IVector_AlgebraDownCastTo< TVec >.
Referenced by operator*=(), operator+=(), operator-=(), and operator=().
vec_add() [2/3]
virtual void ug::IVector::vec_add (double a1, double a2, const IVector & iv2, double a3, const IVector & iv3) pure virtual
Implemented in ug::IVector_AlgebraDownCastTo< TVec >.
vec_add() [3/3]
virtual void ug::IVector::vec_add (double a1, double a2, const IVector & iv2, double a3, const IVector & iv3, double a4, const IVector & iv4) pure virtual
Implemented in ug::IVector_AlgebraDownCastTo< TVec >.
vec_prod()
virtual double ug::IVector::vec_prod (const IVector & v) const pure virtual
Implemented in ug::IVector_AlgebraDownCastTo< TVec >.
The documentation for this class was generated from the following file:
ugbase/lib_algebra/vector_interface/ivector.h