ug4: ug::DenseMatrix< TStorage > Class Template Reference
ug::DenseMatrix< TStorage > Class Template Reference
lib_algebra » Small Algebra
#include <densematrix.h>
Public Types
enum { is_static = TStorage::is_static }
enum { static_num_rows = TStorage::static_num_rows }
enum { static_num_cols = TStorage::static_num_cols }
typedef TStorage base
typedef TStorage::size_type size_type
typedef DenseMatrix< TStorage > this_type
typedef TStorage::value_type value_type
Public Member Functions
DenseMatrix ()
DenseMatrix (double val)
DenseMatrix (const this_type &rhs)
const value_type & entry (size_type r, size_type c) const
value_type & entry (size_type r, size_type c)
void maple_print (const char *name)
template<typename TStorage2 >
bool operator!= (const TStorage2 &t) const
template<typename T2 >
bool operator!= (const T2 &t) const
template<typename TStorage2 >
DenseVector< TStorage2 > operator* (const DenseVector< TStorage2 > &vec) const
this_type operator* (const this_type &mat) const
this_type operator* (double alpha) const
this_type & operator*= (double alpha)
this_type & operator*= (const this_type &mat)
this_type operator+ (const this_type &other) const
template<typename T >
this_type & operator+= (const T &t)
this_type & operator+= (double alpha)
template<typename T2 >
DenseMatrix< TStorage > & operator+= (const T2 &t)
this_type operator- (const this_type &other) const
this_type operator- () const
template<typename T >
this_type & operator-= (const T &t)
this_type & operator-= (double alpha)
template<typename T2 >
DenseMatrix< TStorage > & operator-= (const T2 &t)
this_type operator/ (this_type &other)
this_type & operator/= (double alpha)
this_type & operator/= (this_type &other)
template<typename T2 >
DenseMatrix< TStorage > & operator= (const T2 &t)
this_type & operator= (const this_type &t)
template<typename T >
this_type & operator= (const T &t)
this_type & operator= (double alpha)
bool operator== (double t) const
template<typename TStorage2 >
bool operator== (const DenseMatrix< TStorage2 > &t) const
template<typename TStorage2 >
void subassign (size_t r, size_t c, const TStorage2 &t)
void subassign (size_t r, size_t c, const value_type &t)
this_type T () const
Static Public Attributes
static const eMatrixOrdering ordering = TStorage::ordering
Detailed Description
template<typename TStorage>
class ug::DenseMatrix< TStorage >
DenseMatrix is a mathematical matrix class, which inherits its storage behaviour (fixed/variable size, RowMajor/ColMajor ordering) from TStorage.
Parameters
TStorage storage policy with interface of VariableArray2.
See also
FixedArray2, VariableArray2, eMatrixOrdering
Member Typedef Documentation
template<typename TStorage> typedef TStorage ug::DenseMatrix< TStorage >::base
template<typename TStorage> typedef TStorage::size_type ug::DenseMatrix< TStorage >::size_type
template<typename TStorage> typedef DenseMatrix<TStorage> ug::DenseMatrix< TStorage >::this_type
template<typename TStorage> typedef TStorage::value_type ug::DenseMatrix< TStorage >::value_type
Member Enumeration Documentation
template<typename TStorage> anonymous enum
Enumerator
is_static
template<typename TStorage> anonymous enum
Enumerator
static_num_rows
template<typename TStorage> anonymous enum
Enumerator
static_num_cols
Constructor & Destructor Documentation
template<typename TStorage > ug::DenseMatrix< TStorage >::DenseMatrix ()
template<typename TStorage > ug::DenseMatrix< TStorage >::DenseMatrix (double val)
References ug::DenseMatrix< TStorage >::operator=().
template<typename TStorage > ug::DenseMatrix< TStorage >::DenseMatrix (const this_type & rhs)
Member Function Documentation
template<typename TStorage> const value_type& ug::DenseMatrix< TStorage >::entry (size_type r, size_type c) const inline
Referenced by ug::DenseMatrix< TStorage >::operator*=(), ug::DenseMatrix< TStorage >::operator+(), ug::DenseMatrix< TStorage >::operator+=(), ug::DenseMatrix< TStorage >::operator-(), ug::DenseMatrix< TStorage >::operator-=(), ug::DenseMatrix< TStorage >::operator/=(), ug::DenseMatrix< TStorage >::operator=(), ug::DenseMatrix< TStorage >::operator==(), ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::subassign(), and ug::DenseMatrix< TStorage >::T().
template<typename TStorage> value_type& ug::DenseMatrix< TStorage >::entry (size_type r, size_type c) inline
template<typename TStorage > void ug::DenseMatrix< TStorage >::maple_print (const char * name)
References ug::MatlabString(), and UG_LOG.
Referenced by ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::subassign().
template<typename TStorage> template<typename TStorage2 > bool ug::DenseMatrix< TStorage >::operator!= (const TStorage2 & t) const inline
template<typename TStorage> template<typename T2 > bool ug::DenseMatrix< TStorage >::operator!= (const T2 & t) const
References ug::DenseMatrix< TStorage >::operator==().
template<typename TStorage > template<typename TStorage2 > DenseVector< TStorage2 > ug::DenseMatrix< TStorage >::operator* (const DenseVector< TStorage2 > & vec) const
References num_cols(), num_rows(), and UG_ASSERT.
template<typename TStorage > DenseMatrix< TStorage > ug::DenseMatrix< TStorage >::operator* (const this_type & mat) const inline
References ug::AddMult(), num_cols(), num_rows(), and UG_ASSERT.
template<typename TStorage > DenseMatrix< TStorage > ug::DenseMatrix< TStorage >::operator* (double alpha) const inline
References alpha, num_cols(), and num_rows().
template<typename TStorage > DenseMatrix< TStorage > & ug::DenseMatrix< TStorage >::operator*= (double alpha) inline
References alpha, ug::DenseMatrix< TStorage >::entry(), num_cols(), and num_rows().
template<typename TStorage > DenseMatrix< TStorage > & ug::DenseMatrix< TStorage >::operator*= (const this_type & mat) inline
References ug::DenseMatrix< TStorage >::operator=().
template<typename TStorage > DenseMatrix< TStorage > ug::DenseMatrix< TStorage >::operator+ (const this_type & other) const inline
References ug::DenseMatrix< TStorage >::entry(), num_cols(), num_rows(), and UG_ASSERT.
template<typename TStorage> template<typename T > this_type& ug::DenseMatrix< TStorage >::operator+= (const T & t) inline
template<typename TStorage > DenseMatrix< TStorage > & ug::DenseMatrix< TStorage >::operator+= (double alpha) inline
References alpha, ug::DenseMatrix< TStorage >::entry(), num_cols(), and num_rows().
template<typename TStorage> template<typename T2 > DenseMatrix<TStorage>& ug::DenseMatrix< TStorage >::operator+= (const T2 & t)
References ug::DenseMatrix< TStorage >::entry(), num_cols(), num_rows(), and UG_ASSERT.
template<typename TStorage > DenseMatrix< TStorage > ug::DenseMatrix< TStorage >::operator- (const this_type & other) const inline
References ug::DenseMatrix< TStorage >::entry(), num_cols(), num_rows(), and UG_ASSERT.
template<typename TStorage > DenseMatrix< TStorage > ug::DenseMatrix< TStorage >::operator- () const inline
References ug::DenseMatrix< TStorage >::entry(), num_cols(), and num_rows().
template<typename TStorage> template<typename T > this_type& ug::DenseMatrix< TStorage >::operator-= (const T & t) inline
template<typename TStorage > DenseMatrix< TStorage > & ug::DenseMatrix< TStorage >::operator-= (double alpha) inline
References alpha, ug::DenseMatrix< TStorage >::entry(), num_cols(), and num_rows().
template<typename TStorage> template<typename T2 > DenseMatrix<TStorage>& ug::DenseMatrix< TStorage >::operator-= (const T2 & t)
References ug::DenseMatrix< TStorage >::entry(), num_cols(), num_rows(), and UG_ASSERT.
template<typename TStorage > DenseMatrix< TStorage > ug::DenseMatrix< TStorage >::operator/ (this_type & other)
References ug::Invert().
template<typename TStorage > DenseMatrix< TStorage > & ug::DenseMatrix< TStorage >::operator/= (double alpha) inline
References alpha, ug::DenseMatrix< TStorage >::entry(), num_cols(), and num_rows().
template<typename TStorage > DenseMatrix< TStorage > & ug::DenseMatrix< TStorage >::operator/= (this_type & other) inline
References ug::Invert().
template<typename TStorage> template<typename T2 > DenseMatrix<TStorage>& ug::DenseMatrix< TStorage >::operator= (const T2 & t)
References ug::DenseMatrix< TStorage >::entry(), and resize().
template<typename TStorage > DenseMatrix< TStorage > & ug::DenseMatrix< TStorage >::operator= (const this_type & t) inline
References ug::DenseMatrix< TStorage >::entry(), and resize().
Referenced by ug::DenseMatrix< TStorage >::DenseMatrix(), and ug::DenseMatrix< TStorage >::operator*=().
template<typename TStorage> template<typename T > this_type& ug::DenseMatrix< TStorage >::operator= (const T & t) inline
template<typename TStorage > DenseMatrix< TStorage > & ug::DenseMatrix< TStorage >::operator= (double alpha) inline
References ug::DenseMatrix< TStorage >::entry(), num_cols(), and num_rows().
template<typename TStorage > bool ug::DenseMatrix< TStorage >::operator== (double t) const inline
References ug::DenseMatrix< TStorage >::entry(), num_cols(), and num_rows().
Referenced by ug::DenseMatrix< TStorage >::operator!=().
template<typename TStorage > template<typename TStorage2 > bool ug::DenseMatrix< TStorage >::operator== (const DenseMatrix< TStorage2 > & t) const inline
References ug::DenseMatrix< TStorage >::entry(), num_cols(), and num_rows().
template<typename TStorage> template<typename TStorage2 > void ug::DenseMatrix< TStorage >::subassign (size_t r, size_t c, const TStorage2 & t) inline
Referenced by ug::ElementGaussSeidelStep(), ug::LineVanka< TDomain, TAlgebra >::linevanka_step(), and ug::Vanka_step().
template<typename TStorage> void ug::DenseMatrix< TStorage >::subassign (size_t r, size_t c, const value_type & t) inline
template<typename TStorage > DenseMatrix< TStorage > ug::DenseMatrix< TStorage >::T () const inline
References ug::DenseMatrix< TStorage >::entry(), num_cols(), and num_rows().
Member Data Documentation
template<typename TStorage> const eMatrixOrdering ug::DenseMatrix< TStorage >::ordering = TStorage::ordering static
The documentation for this class was generated from the following files:
ugbase/lib_algebra/small_algebra/small_matrix/densematrix.h
ugbase/lib_algebra/small_algebra/small_matrix/densematrix_impl.h