ug4: pcl::SingleLevelLayout< TInterface > Class Template Reference
pcl::SingleLevelLayout< TInterface > Class Template Reference
ugbase » PCL
the standard single-level-layout implementation
#include <pcl_communication_structs.h>
Public Types
typedef layout_tags::single_level_layout_tag category_tag
Layout category.
typedef InterfaceMap::const_iterator const_iterator
typedef Interface::Element Element
Element type.
typedef TInterface Interface
Interface type.
typedef std::map< int, TInterface > InterfaceMap
an interface-map is a list of interfaces, each associated with a process id.
typedef InterfaceMap::iterator iterator
An iterator that allows to iterate over the interfaces stored in the layout.
typedef Interface::Type Type
Type.
Public Member Functions
iterator begin (size_t level=0)
returns the iterator to the first interface of the layout.
const_iterator begin (size_t level=0) const
void clear ()
clears the layout
bool empty (size_t level=0) const
returns true if the layout has no interfaces.
iterator end (size_t level=0)
returns the iterator to the last interface of the layout.
const_iterator end (size_t level=0) const
iterator erase (iterator iter, size_t level=0)
erases the interface at the given iterator.
bool has_interface_elements () const
returns true if the layout contains interface elements
const Interface & interface (const_iterator iter) const
Interface & interface (int procID, size_t level=0)
returns the interface to the given process.
const Interface & interface (int procID, size_t level=0) const
Interface & interface (iterator iter)
returns the interface to the given iterator.
bool interface_exists (int procID, size_t level=0) const
returns true if an interface to the given procID already exists.
size_t num_interface_elements () const
returns the sum of the interface sizes
size_t num_interfaces (size_t level=0) const
returns the number of interfaces in the layout
size_t num_levels () const
returns 1
int proc_id (const_iterator iter) const
int proc_id (iterator iter) const
returns the target process of the interface given in iterator
SingleLevelLayout ()
template<class TCompare >
void sort_interface_entries (TCompare cmp)
sort the entries in all interfaces of this layout
Protected Attributes
InterfaceMap m_interfaceMap
holds the interfaces in a map.
Detailed Description
template<class TInterface>
class pcl::SingleLevelLayout< TInterface >
the standard single-level-layout implementation
A Layout is a collection of interfaces. Each interface is associated with a process-id.
This layout type supports the requirements of the pcl::layout_tags::single_level_layout_tag category.
The layout passes its local srcID on to created interfaces.
Additionally it features methods that allow to add new interfaces
In order to allow one method to operate both on a SingleLevelLayout and a MultiLevelLayout, the (size_t level = 0) convenience parameter has been added to some methods. Those parameters are ignored throughout the whole implementation.
Member Typedef Documentation
category_tag
template<class TInterface > typedef layout_tags::single_level_layout_tag pcl::SingleLevelLayout< TInterface >::category_tag
Layout category.
const_iterator
template<class TInterface > typedef InterfaceMap::const_iterator pcl::SingleLevelLayout< TInterface >::const_iterator
Element
template<class TInterface > typedef Interface::Element pcl::SingleLevelLayout< TInterface >::Element
Element type.
Interface
template<class TInterface > typedef TInterface pcl::SingleLevelLayout< TInterface >::Interface
Interface type.
InterfaceMap
template<class TInterface > typedef std::map<int, TInterface> pcl::SingleLevelLayout< TInterface >::InterfaceMap
an interface-map is a list of interfaces, each associated with a process id.
iterator
template<class TInterface > typedef InterfaceMap::iterator pcl::SingleLevelLayout< TInterface >::iterator
An iterator that allows to iterate over the interfaces stored in the layout.
Type
template<class TInterface > typedef Interface::Type pcl::SingleLevelLayout< TInterface >::Type
Type.
Constructor & Destructor Documentation
SingleLevelLayout()
template<class TInterface > pcl::SingleLevelLayout< TInterface >::SingleLevelLayout () inline
Member Function Documentation
begin() [1/2]
template<class TInterface > iterator pcl::SingleLevelLayout< TInterface >::begin (size_t level = 0) inline
returns the iterator to the first interface of the layout.
You should access the values of this iterator using the methods Layout::interface and Layout::proc_id.
References pcl::SingleLevelLayout< TInterface >::m_interfaceMap.
Referenced by ug::AddAllFromLayout(), ug::AddConnectionsBetweenSlaves(), ug::AddExtraProcessEntriesToSubdomainLayout(), ug::BuildDomainDecompositionLayouts(), ug::GenerateOverlapClass< matrix_type >::calculate(), ug::ParallelVector< TVector >::check_storage_type(), ug::CommunicateConnections(), ug::CommunicateOnInterfaces(), ug::CopyInterfaceEntrysToDomainDecompositionLayouts(), ug::ParallelNodes::create_mark_map(), ug::NewLayoutCreator::create_mark_map(), ug::CreateGlobalLayout(), pcl::SingleLevelLayout< TInterface >::empty(), ug::FindPositionInInterfaces(), ug::GetHighestReferencedIndex(), pcl::SingleLevelLayout< TInterface >::has_interface_elements(), ug::RowSendingScheme< matrix_type >::issue_send(), ug::LogIndexLayout(), ug::MarkAllFromLayout(), ug::MatExtractDiagOnLayout(), ug::MatWriteDiagOnLayout(), ug::NewLayoutCreator::NewLayoutCreator(), pcl::SingleLevelLayout< TInterface >::num_interface_elements(), ug::NumIndices(), ug::operator<<(), ug::PermuteIndicesInIndexLayout(), ug::RowSendingScheme< matrix_type >::process(), ug::BGLParallelMatrix< T >::refresh(), ug::SlicingData< TVec, N >::replace_indices_in_layout(), ug::ReplaceIndicesInLayout(), ug::ScaleLayoutValues(), ug::Serialize(), ug::SerializeLayout(), ug::SetLayoutValues(), pcl::SingleLevelLayout< TInterface >::sort_interface_entries(), and ug::ParallelNodes::sort_layout().
begin() [2/2]
template<class TInterface > const_iterator pcl::SingleLevelLayout< TInterface >::begin (size_t level = 0) const inline
References pcl::SingleLevelLayout< TInterface >::m_interfaceMap.
clear()
template<class TInterface > void pcl::SingleLevelLayout< TInterface >::clear () inline
clears the layout
References pcl::SingleLevelLayout< TInterface >::m_interfaceMap.
Referenced by ug::HorizontalAlgebraLayouts::clear(), ug::AlgebraLayouts::clear(), ug::CollectMatrixOnOneProc(), ug::CreateLayoutFromGlobalLayout(), ug::CreateLevelIndexLayout(), and ug::DoFDistribution::reinit_index_layout().
empty()
template<class TInterface > bool pcl::SingleLevelLayout< TInterface >::empty (size_t level = 0) const inline
returns true if the layout has no interfaces.
Note that this method only tells whether there are interfaces or not. To check whether there are any elements use has_interface_elements.
References pcl::SingleLevelLayout< TInterface >::begin(), and pcl::SingleLevelLayout< TInterface >::end().
Referenced by ug::BuildOneToManyLayout().
end() [1/2]
template<class TInterface > iterator pcl::SingleLevelLayout< TInterface >::end (size_t level = 0) inline
returns the iterator to the last interface of the layout.
You should access the values of this iterator using the methods Layout::interface and Layout::proc_id.
References pcl::SingleLevelLayout< TInterface >::m_interfaceMap.
Referenced by ug::AddAllFromLayout(), ug::AddConnectionsBetweenSlaves(), ug::AddExtraProcessEntriesToSubdomainLayout(), ug::BuildDomainDecompositionLayouts(), ug::GenerateOverlapClass< matrix_type >::calculate(), ug::ParallelVector< TVector >::check_storage_type(), ug::CommunicateConnections(), ug::CommunicateOnInterfaces(), ug::CopyInterfaceEntrysToDomainDecompositionLayouts(), ug::ParallelNodes::create_mark_map(), ug::NewLayoutCreator::create_mark_map(), ug::CreateGlobalLayout(), pcl::SingleLevelLayout< TInterface >::empty(), ug::FindPositionInInterfaces(), ug::GetHighestReferencedIndex(), pcl::SingleLevelLayout< TInterface >::has_interface_elements(), ug::RowSendingScheme< matrix_type >::issue_send(), ug::LogIndexLayout(), ug::MarkAllFromLayout(), ug::MatExtractDiagOnLayout(), ug::MatWriteDiagOnLayout(), ug::NewLayoutCreator::NewLayoutCreator(), pcl::SingleLevelLayout< TInterface >::num_interface_elements(), ug::NumIndices(), ug::operator<<(), ug::PermuteIndicesInIndexLayout(), ug::RowSendingScheme< matrix_type >::process(), ug::BGLParallelMatrix< T >::refresh(), ug::SlicingData< TVec, N >::replace_indices_in_layout(), ug::ReplaceIndicesInLayout(), ug::ScaleLayoutValues(), ug::Serialize(), ug::SerializeLayout(), ug::SetLayoutValues(), pcl::SingleLevelLayout< TInterface >::sort_interface_entries(), and ug::ParallelNodes::sort_layout().
end() [2/2]
template<class TInterface > const_iterator pcl::SingleLevelLayout< TInterface >::end (size_t level = 0) const inline
References pcl::SingleLevelLayout< TInterface >::m_interfaceMap.
erase()
template<class TInterface > iterator pcl::SingleLevelLayout< TInterface >::erase (iterator iter, size_t level = 0) inline
erases the interface at the given iterator.
returns an iterator to the next interface.
References pcl::SingleLevelLayout< TInterface >::m_interfaceMap.
has_interface_elements()
template<class TInterface > bool pcl::SingleLevelLayout< TInterface >::has_interface_elements () const inline
returns true if the layout contains interface elements
References pcl::SingleLevelLayout< TInterface >::begin(), pcl::SingleLevelLayout< TInterface >::end(), and pcl::SingleLevelLayout< TInterface >::interface().
interface() [1/4]
template<class TInterface > const Interface& pcl::SingleLevelLayout< TInterface >::interface (const_iterator iter) const inline
interface() [2/4]
template<class TInterface > Interface& pcl::SingleLevelLayout< TInterface >::interface (int procID, size_t level = 0) inline
returns the interface to the given process.
if the queried interface exist, it will be returned. If not it will be created. The new interfaces localSrcID will be set to the localSrcID of this layout.
References pcl::SingleLevelLayout< TInterface >::m_interfaceMap.
interface() [3/4]
template<class TInterface > const Interface& pcl::SingleLevelLayout< TInterface >::interface (int procID, size_t level = 0) const inline
References pcl::SingleLevelLayout< TInterface >::m_interfaceMap, and UG_ASSERT.
interface() [4/4]
template<class TInterface > Interface& pcl::SingleLevelLayout< TInterface >::interface (iterator iter) inline
returns the interface to the given iterator.
Referenced by ug::DoFDistribution::add_indices_from_layouts(), ug::AddAllFromLayout(), ug::AddConnectionsBetweenSlaves(), ug::AddEntriesToIndexLayout_DomainDecomposition(), ug::AddEntriesToLevelIndexLayout(), ug::AddEntriesToSurfaceIndexLayout(), ug::AddExtraProcessEntriesToSubdomainLayout(), ug::CommunicateOnInterfaces(), ug::CopyInterfaceEntrysToDomainDecompositionLayouts(), ug::Deserialize(), ug::DeserializeLayout(), pcl::SingleLevelLayout< TInterface >::has_interface_elements(), ug::MarkAllFromLayout(), pcl::SingleLevelLayout< TInterface >::num_interface_elements(), ug::NumIndices(), ug::ReceiveMatrix(), ug::ReceiveOnInterfaces(), ug::BGLParallelMatrix< T >::refresh(), ug::SlicingData< TVec, N >::replace_indices_in_layout(), ug::SendMatrix(), ug::Serialize(), pcl::SingleLevelLayout< TInterface >::sort_interface_entries(), and ug::ParallelNodes::sort_layout().
interface_exists()
template<class TInterface > bool pcl::SingleLevelLayout< TInterface >::interface_exists (int procID, size_t level = 0) const inline
returns true if an interface to the given procID already exists.
References pcl::SingleLevelLayout< TInterface >::m_interfaceMap.
num_interface_elements()
template<class TInterface > size_t pcl::SingleLevelLayout< TInterface >::num_interface_elements () const inline
returns the sum of the interface sizes
References pcl::SingleLevelLayout< TInterface >::begin(), pcl::SingleLevelLayout< TInterface >::end(), and pcl::SingleLevelLayout< TInterface >::interface().
num_interfaces()
template<class TInterface > size_t pcl::SingleLevelLayout< TInterface >::num_interfaces (size_t level = 0) const inline
returns the number of interfaces in the layout
References pcl::SingleLevelLayout< TInterface >::m_interfaceMap.
Referenced by ug::Serialize().
num_levels()
template<class TInterface > size_t pcl::SingleLevelLayout< TInterface >::num_levels () const inline
returns 1
proc_id() [1/2]
template<class TInterface > int pcl::SingleLevelLayout< TInterface >::proc_id (const_iterator iter) const inline
proc_id() [2/2]
template<class TInterface > int pcl::SingleLevelLayout< TInterface >::proc_id (iterator iter) const inline
returns the target process of the interface given in iterator
Referenced by ug::AddConnectionsBetweenSlaves(), ug::AddExtraProcessEntriesToSubdomainLayout(), ug::BuildDomainDecompositionLayouts(), ug::CommunicateOnInterfaces(), ug::CopyInterfaceEntrysToDomainDecompositionLayouts(), ug::ParallelNodes::create_mark_map(), ug::NewLayoutCreator::create_mark_map(), ug::CreateGlobalLayout(), ug::FindPositionInInterfaces(), ug::RowSendingScheme< matrix_type >::issue_send(), ug::LogIndexLayout(), ug::NewLayoutCreator::NewLayoutCreator(), ug::operator<<(), ug::RowSendingScheme< matrix_type >::process(), ug::BGLParallelMatrix< T >::refresh(), ug::Serialize(), and ug::SerializeLayout().
sort_interface_entries()
template<class TInterface > template<class TCompare > void pcl::SingleLevelLayout< TInterface >::sort_interface_entries (TCompare cmp) inline
sort the entries in all interfaces of this layout
References pcl::SingleLevelLayout< TInterface >::begin(), pcl::SingleLevelLayout< TInterface >::end(), and pcl::SingleLevelLayout< TInterface >::interface().
Referenced by pcl::MultiLevelLayout< TInterface >::sort_interface_entries().
Member Data Documentation
m_interfaceMap
template<class TInterface > InterfaceMap pcl::SingleLevelLayout< TInterface >::m_interfaceMap protected
holds the interfaces in a map.
Referenced by pcl::SingleLevelLayout< TInterface >::begin(), pcl::SingleLevelLayout< TInterface >::clear(), pcl::SingleLevelLayout< TInterface >::end(), pcl::SingleLevelLayout< TInterface >::erase(), pcl::SingleLevelLayout< TInterface >::interface(), pcl::SingleLevelLayout< TInterface >::interface_exists(), and pcl::SingleLevelLayout< TInterface >::num_interfaces().
The documentation for this class was generated from the following file:
ugbase/pcl/pcl_communication_structs.h