ug4: ug::BinaryStream Class Reference
ug::BinaryStream Class Reference
ugbase » Common » Common Utilities » Common IO
a specialzation of std::iostream, that uses a
#include <binary_stream.h>
Public Member Functions
BinaryStream ()
BinaryStream (size_t newSize)
void * buffer ()
bool can_read_more ()
returns true if there is more data left to read.
void clear ()
void read_jump (size_t jumpSize)
size_t read_pos () const
void reset ()
void resize (size_t newSize)
size_t size () const
void write_jump (size_t jumpSize)
Protected Attributes
BinaryStreamBuffer m_streamBuf
Detailed Description
a specialzation of std::iostream, that uses a
See also
BinaryStreamBuffer as buffer.
Constructor & Destructor Documentation
BinaryStream() [1/2]
ug::BinaryStream::BinaryStream () inline
BinaryStream() [2/2]
ug::BinaryStream::BinaryStream (size_t newSize) inline
References ug::BinaryStreamBuffer::resize().
Member Function Documentation
buffer()
void* ug::BinaryStream::buffer () inline
Referenced by pcl::ParallelArchive::BufferBinaryStream::buffer().
can_read_more()
bool ug::BinaryStream::can_read_more () inline
returns true if there is more data left to read.
Todo:
this method should be removed. The normal stream-methdos should be used instead (eof,...). However - those do not seem to work properly in the moment.
References ug::BinaryStreamBuffer::size().
clear()
void ug::BinaryStream::clear () inline
read_jump()
void ug::BinaryStream::read_jump (size_t jumpSize) inline
read_pos()
size_t ug::BinaryStream::read_pos () const inline
reset()
void ug::BinaryStream::reset () inline
resize()
void ug::BinaryStream::resize (size_t newSize) inline
size()
size_t ug::BinaryStream::size () const inline
Referenced by pcl::ParallelArchive::BufferBinaryStream::size().
write_jump()
void ug::BinaryStream::write_jump (size_t jumpSize) inline
Member Data Documentation
m_streamBuf
BinaryStreamBuffer ug::BinaryStream::m_streamBuf protected
The documentation for this class was generated from the following file:
ugbase/common/util/binary_stream.h