ug4: ug::QuadratureRule< TDim > Class Template Reference
ug::QuadratureRule< TDim > Class Template Reference
lib_discretization » Quadrature Rules
provides quadrature rule for a Reference Dimension
#include <quadrature.h>
Public Types
typedef MathVector< dim > position_type
Position Type in Reference Element Space.
typedef number weight_type
Type of weights.
Public Member Functions
size_t order () const
returns the order
const MathVector< dim > & point (size_t i) const
returns i'th integration point
const MathVector< dim > * points () const
returns all positions in an array of size()
QuadratureRule ()
constructor
size_t size () const
number of integration points
number weight (size_t i) const
return the i'th weight
const number * weights () const
returns all weights in an array of size()
virtual ~QuadratureRule ()
destructor
Static Public Attributes
static const int dim = TDim
Dimension of Reference Element.
Protected Attributes
size_t m_numPoints
number of points
int m_order
Order of rule.
const MathVector< dim > * m_pvPoint
Integration points.
const number * m_pvWeight
Weights.
Detailed Description
template<int TDim>
class ug::QuadratureRule< TDim >
provides quadrature rule for a Reference Dimension
A Quadrature Rule provides for a given Reference Element integration points and weights. An Integral over the Reference Element T is approximated by
\[ \int\limits_T f(\mathbf{x}) \; d\mathbf{x} \approx \sum_{i=0}^{n-1} f(\mathbf{x}_{i}) \cdot w_i \]
with the \(n\) integration points \(\mathbf{x}_i\) and weights \(w_i \).
Template Parameters
TDim Dimension of Reference Element
Member Typedef Documentation
position_type
template<int TDim> typedef MathVector<dim> ug::QuadratureRule< TDim >::position_type
Position Type in Reference Element Space.
weight_type
template<int TDim> typedef number ug::QuadratureRule< TDim >::weight_type
Type of weights.
Constructor & Destructor Documentation
QuadratureRule()
template<int TDim> ug::QuadratureRule< TDim >::QuadratureRule () inline
constructor
~QuadratureRule()
template<int TDim> virtual ug::QuadratureRule< TDim >::~QuadratureRule () inline virtual
destructor
Member Function Documentation
order()
template<int TDim> size_t ug::QuadratureRule< TDim >::order () const inline
returns the order
References ug::QuadratureRule< TDim >::m_order.
Referenced by ug::GaussQuadratureHexahedron::GaussQuadratureHexahedron(), ug::GaussQuadratureOctahedron::GaussQuadratureOctahedron(), ug::GaussQuadraturePrism::GaussQuadraturePrism(), ug::GaussQuadraturePyramid::GaussQuadraturePyramid(), ug::GaussQuadratureQuadrilateral::GaussQuadratureQuadrilateral(), ug::GaussQuadratureTetrahedron::GaussQuadratureTetrahedron(), ug::GaussQuadratureTriangle::GaussQuadratureTriangle(), and ug::PrintQuadRule().
point()
template<int TDim> const MathVector<dim>& ug::QuadratureRule< TDim >::point (size_t i) const inline
returns i'th integration point
References ug::QuadratureRule< TDim >::m_pvPoint, ug::QuadratureRule< TDim >::size(), and UG_ASSERT.
Referenced by ug::GaussQuadratureHexahedron::GaussQuadratureHexahedron(), ug::GaussQuadratureOctahedron::GaussQuadratureOctahedron(), ug::GaussQuadraturePrism::GaussQuadraturePrism(), ug::GaussQuadraturePyramid::GaussQuadraturePyramid(), ug::GaussQuadratureQuadrilateral::GaussQuadratureQuadrilateral(), ug::GaussQuadratureTetrahedron::GaussQuadratureTetrahedron(), ug::GaussQuadratureTriangle::GaussQuadratureTriangle(), ug::PrintQuadRule(), ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
points()
template<int TDim> const MathVector<dim>* ug::QuadratureRule< TDim >::points () const inline
returns all positions in an array of size()
References ug::QuadratureRule< TDim >::m_pvPoint.
Referenced by ug::Integrate(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
size()
template<int TDim> size_t ug::QuadratureRule< TDim >::size () const inline
number of integration points
References ug::QuadratureRule< TDim >::m_numPoints.
Referenced by ug::GaussQuadratureHexahedron::GaussQuadratureHexahedron(), ug::GaussQuadratureOctahedron::GaussQuadratureOctahedron(), ug::GaussQuadraturePrism::GaussQuadraturePrism(), ug::GaussQuadraturePyramid::GaussQuadraturePyramid(), ug::GaussQuadratureQuadrilateral::GaussQuadratureQuadrilateral(), ug::GaussQuadratureTetrahedron::GaussQuadratureTetrahedron(), ug::GaussQuadratureTriangle::GaussQuadratureTriangle(), ug::Integrate(), ug::QuadratureRule< TDim >::point(), ug::PrintQuadRule(), ug::DimFVGeometry< TWorldDim, TDim >::update(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_local(), ug::DimFVGeometry< TWorldDim, TDim >::update_local(), and ug::QuadratureRule< TDim >::weight().
weight()
template<int TDim> number ug::QuadratureRule< TDim >::weight (size_t i) const inline
return the i'th weight
References ug::QuadratureRule< TDim >::m_pvWeight, ug::QuadratureRule< TDim >::size(), and UG_ASSERT.
Referenced by ug::GaussQuadratureHexahedron::GaussQuadratureHexahedron(), ug::GaussQuadratureOctahedron::GaussQuadratureOctahedron(), ug::GaussQuadraturePrism::GaussQuadraturePrism(), ug::GaussQuadraturePyramid::GaussQuadraturePyramid(), ug::GaussQuadratureQuadrilateral::GaussQuadratureQuadrilateral(), ug::GaussQuadratureTetrahedron::GaussQuadratureTetrahedron(), ug::GaussQuadratureTriangle::GaussQuadratureTriangle(), ug::Integrate(), and ug::PrintQuadRule().
weights()
template<int TDim> const number* ug::QuadratureRule< TDim >::weights () const inline
returns all weights in an array of size()
References ug::QuadratureRule< TDim >::m_pvWeight.
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update_local(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
Member Data Documentation
dim
template<int TDim> const int ug::QuadratureRule< TDim >::dim = TDim static
Dimension of Reference Element.
m_numPoints
template<int TDim> size_t ug::QuadratureRule< TDim >::m_numPoints protected
number of points
Referenced by ug::QuadratureRule< TDim >::size().
m_order
template<int TDim> int ug::QuadratureRule< TDim >::m_order protected
Order of rule.
Referenced by ug::QuadratureRule< TDim >::order().
m_pvPoint
template<int TDim> const MathVector<dim>* ug::QuadratureRule< TDim >::m_pvPoint protected
Integration points.
Referenced by ug::QuadratureRule< TDim >::point(), and ug::QuadratureRule< TDim >::points().
m_pvWeight
template<int TDim> const number* ug::QuadratureRule< TDim >::m_pvWeight protected
Weights.
Referenced by ug::QuadratureRule< TDim >::weight(), and ug::QuadratureRule< TDim >::weights().
The documentation for this class was generated from the following file:
ugbase/lib_disc/quadrature/quadrature.h