ug4: ug::ConvectionShapesPartialUpwind< TDim > Class Template Reference
ug::ConvectionShapesPartialUpwind< TDim > Class Template Reference
#include <conv_shape.h>
Public Types
typedef IConvectionShapes< TDim > base_type
Base class.
typedef ConvectionShapesPartialUpwind< TDim > this_type
This class.
Public Types inherited from ug::IConvectionShapes< TDim >
typedef IConvectionShapes< dim > this_type
Abbreviation for own type.
typedef bool(this_type::* UpdateFunc) (const FVGeometryBase *geo, const MathVector< dim > *Velocity, const MathMatrix< dim, dim > *Diffusion, bool computeDeriv)
type of update function
Public Member Functions
ConvectionShapesPartialUpwind ()
constructor
template<typename TFVGeom >
bool update (const TFVGeom *geo, const MathVector< dim > *Velocity, const MathMatrix< dim, dim > *DiffDisp, bool computeDeriv)
update of values for FV1Geometry
Public Member Functions inherited from ug::IConvectionShapes< TDim >
const MathMatrix< dim, dim > & D_diffusion (size_t scvf, size_t sh) const
upwind shapes for ip vel
const MathVector< dim > & D_vel (size_t scvf, size_t sh) const
upwind shape for corner vel
IConvectionShapes ()
constructor
bool non_zero_deriv_diffusion () const
returns if upwind shape w.r.t. ip vel is non-zero
size_t num_scvf () const
returns number of sub control volume faces
size_t num_sh () const
returns number of shapes
number operator() (size_t scvf, size_t sh) const
shape value
void register_update_func (TAssFunc func)
register a update function for a Geometry
bool set_geometry_type (const TFVGeom &geo)
set the Geometry type to use for next updates
bool update (const FVGeometryBase *geo, const MathVector< dim > *Velocity, const MathMatrix< dim, dim > *DiffDisp, bool computeDeriv)
Static Public Attributes
static const int dim = TDim
Dimension.
Private Member Functions
void register_func (Int2Type< 1 >)
void register_func (Int2Type< 2 >)
void register_func (Int2Type< 3 >)
template<typename TElem >
void register_func_for_elem ()
template<int refDim>
void register_func_for_refDim ()
Additional Inherited Members
Protected Member Functions inherited from ug::IConvectionShapes< TDim >
number & conv_shape (size_t scvf, size_t sh)
non-const access to ip velocity (i.e. interpolated velocity at ip)
MathMatrix< dim, dim > & conv_shape_diffusion (size_t scvf, size_t sh)
non-const access to upwind shapes for ip vel
MathVector< dim > & D_vel (size_t scvf, size_t sh)
non-const access to upwind shapes for corner vel
void set_non_zero_deriv_diffusion_flag (bool flag)
sets the shape ip flag
void set_sizes (size_t numScvf, size_t numSh)
resize the data arrays
Protected Attributes inherited from ug::IConvectionShapes< TDim >
bool m_bNonZeroDerivDiffusion
flag if ip shapes are non-zero
int m_id
id of current geometry type
size_t m_numScvf
number of current scvf
size_t m_numSh
number of current shape functions (usually in corners)
std::vector< UpdateFunc > m_vUpdateFunc
Vector holding all update functions.
std::vector< std::vector< number > > m_vUpShape
upwind shapes for corners shape functions
std::vector< std::vector< MathMatrix< dim, dim > > > m_vUpShapeDiffusion
upwind shapes for corners shape functions
std::vector< std::vector< MathVector< dim > > > m_vUpShapeVel
upwind shapes for corners shape functions
Member Typedef Documentation
template<int TDim> typedef IConvectionShapes<TDim> ug::ConvectionShapesPartialUpwind< TDim >::base_type
Base class.
template<int TDim> typedef ConvectionShapesPartialUpwind<TDim> ug::ConvectionShapesPartialUpwind< TDim >::this_type
This class.
Constructor & Destructor Documentation
template<int TDim> ug::ConvectionShapesPartialUpwind< TDim >::ConvectionShapesPartialUpwind () inline
constructor
References ug::ConvectionShapesNoUpwind< TDim >::register_func(), and ug::ConvectionShapesNoUpwind< TDim >::update().
Member Function Documentation
template<int TDim> void ug::ConvectionShapesPartialUpwind< TDim >::register_func (Int2Type< 1 >) inline private
template<int TDim> void ug::ConvectionShapesPartialUpwind< TDim >::register_func (Int2Type< 2 >) inline private
References ug::ConvectionShapesNoUpwind< TDim >::register_func().
template<int TDim> void ug::ConvectionShapesPartialUpwind< TDim >::register_func (Int2Type< 3 >) inline private
References ug::ConvectionShapesNoUpwind< TDim >::register_func().
template<int TDim> template<typename TElem > void ug::ConvectionShapesPartialUpwind< TDim >::register_func_for_elem () inline private
template<int TDim> template<int refDim> void ug::ConvectionShapesPartialUpwind< TDim >::register_func_for_refDim () inline private
References ug::ConvectionShapesPartialUpwind< TDim >::update().
template<int TDim> template<typename TFVGeom > bool ug::ConvectionShapesPartialUpwind< TDim >::update (const TFVGeom * geo, const MathVector< dim > * Velocity, const MathMatrix< dim, dim > * DiffDisp, bool computeDeriv)
update of values for FV1Geometry
References ug::IConvectionShapes< TDim >::conv_shape(), ug::IConvectionShapes< TDim >::conv_shape_diffusion(), ug::IConvectionShapes< TDim >::D_vel(), ug::ConvectionShapesNoUpwind< TDim >::dim, ug::MatSet(), ug::MatVecMult(), ug::IConvectionShapes< TDim >::set_non_zero_deriv_diffusion_flag(), UG_ASSERT, UG_THROW, ug::VecDot(), ug::VecScale(), and ug::VecSet().
Referenced by ug::ConvectionShapesPartialUpwind< TDim >::register_func_for_refDim().
Member Data Documentation
template<int TDim> const int ug::ConvectionShapesPartialUpwind< TDim >::dim = TDim static
Dimension.
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/conv_shape.h