ug4: ug::attachment_traits< Vertex *, ElementStorage< Vertex > > Class Reference
ug::attachment_traits< Vertex *, ElementStorage< Vertex > > Class Reference
#include <element_storage.h>
Public Types
typedef const ElementStorage< Vertex > * ConstElemHandlerPtr
typedef const Vertex * ConstElemPtr
typedef ElementStorage< Vertex >::SectionContainer::iterator element_iterator
typedef ElementStorage< Vertex > * ElemHandlerPtr
typedef Vertex * ElemPtr
typedef Vertex *& ElemRef
Static Public Member Functions
static element_iterator elements_begin (ElemHandlerPtr pHandler)
static element_iterator elements_end (ElemHandlerPtr pHandler)
static uint get_data_index (ConstElemHandlerPtr pHandler, ConstElemPtr elem)
static void set_data_index (ElemHandlerPtr pHandler, ElemPtr elem, uint index)
Member Typedef Documentation
ConstElemHandlerPtr
typedef const ElementStorage<Vertex>* ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::ConstElemHandlerPtr
ConstElemPtr
typedef const Vertex* ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::ConstElemPtr
element_iterator
typedef ElementStorage<Vertex>::SectionContainer::iterator ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::element_iterator
ElemHandlerPtr
typedef ElementStorage<Vertex>* ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::ElemHandlerPtr
ElemPtr
typedef Vertex* ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::ElemPtr
ElemRef
typedef Vertex*& ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::ElemRef
Member Function Documentation
elements_begin()
static element_iterator ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::elements_begin (ElemHandlerPtr pHandler) inline static
References ug::SectionContainer< TValue, TContainer >::begin(), and ug::ElementStorage< TElem >::m_sectionContainer.
elements_end()
static element_iterator ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::elements_end (ElemHandlerPtr pHandler) inline static
References ug::SectionContainer< TValue, TContainer >::end(), and ug::ElementStorage< TElem >::m_sectionContainer.
get_data_index()
static uint ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::get_data_index (ConstElemHandlerPtr pHandler, ConstElemPtr elem) inline static
References ug::GridObject::grid_data_index().
set_data_index()
static void ug::attachment_traits< Vertex *, ElementStorage< Vertex > >::set_data_index (ElemHandlerPtr pHandler, ElemPtr elem, uint index) inline static
References ug::GridObject::set_grid_data_index().
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/element_storage.h