ug4: ug::ComPol_CopyAttachment< TLayout, TAttachment > Class Template Reference
ug::ComPol_CopyAttachment< TLayout, TAttachment > Class Template Reference
lib_grid » parallelization
copies values from a specified attachment to a stream and back.
#include <compol_copy_attachment.h>
Public Types
typedef Layout::Element Element
typedef Layout::Type GeomObj
typedef Layout::Interface Interface
typedef TLayout Layout
typedef TAttachment::ValueType Value
Public Types inherited from pcl::ICommunicationPolicy< TLayout >
typedef Layout::Interface Interface
typedef TLayout Layout
Public Member Functions
virtual bool collect (ug::BinaryBuffer &buff, const Interface &interface)
writes the data for the given interface to the buffer.
ComPol_CopyAttachment ()
Initialises the collector with an invalid grid.
ComPol_CopyAttachment (Grid &grid, TAttachment attachment)
Calls set_target internally.
virtual bool extract (ug::BinaryBuffer &buff, const Interface &interface)
reads the data from the buffer to the given interface .
void extract_on_constrained_elems_only (bool enable)
void set_attachment (Grid &grid, TAttachment &attachment)
The grid and the attachment from where the data shall be copied.
virtual ~ComPol_CopyAttachment ()
Public Member Functions inherited from pcl::ICommunicationPolicy< TLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
virtual ~ICommunicationPolicy ()
Protected Attributes
Grid::AttachmentAccessor< GeomObj, TAttachment > m_aaVal
bool m_extractOnConstrainedElemsOnly
Detailed Description
template<class TLayout, class TAttachment>
class ug::ComPol_CopyAttachment< TLayout, TAttachment >
copies values from a specified attachment to a stream and back.
TLayout::Type has to be either Vertex, Edge, Face or Volume.
Member Typedef Documentation
template<class TLayout, class TAttachment> typedef Layout::Element ug::ComPol_CopyAttachment< TLayout, TAttachment >::Element
template<class TLayout, class TAttachment> typedef Layout::Type ug::ComPol_CopyAttachment< TLayout, TAttachment >::GeomObj
template<class TLayout, class TAttachment> typedef Layout::Interface ug::ComPol_CopyAttachment< TLayout, TAttachment >::Interface
template<class TLayout, class TAttachment> typedef TLayout ug::ComPol_CopyAttachment< TLayout, TAttachment >::Layout
template<class TLayout, class TAttachment> typedef TAttachment::ValueType ug::ComPol_CopyAttachment< TLayout, TAttachment >::Value
Constructor & Destructor Documentation
template<class TNodeLayout , class TAttachment > ug::ComPol_CopyAttachment< TNodeLayout, TAttachment >::ComPol_CopyAttachment ()
Initialises the collector with an invalid grid.
be sure to call set_source before passing it to a communicator.
template<class TNodeLayout , class TAttachment > ug::ComPol_CopyAttachment< TNodeLayout, TAttachment >::ComPol_CopyAttachment (Grid & grid, TAttachment attachment)
Calls set_target internally.
References ug::ComPol_CopyAttachment< TLayout, TAttachment >::set_attachment().
template<class TLayout, class TAttachment> virtual ug::ComPol_CopyAttachment< TLayout, TAttachment >::~ComPol_CopyAttachment () inline virtual
References ug::ComPol_CopyAttachment< TLayout, TAttachment >::collect(), ug::ComPol_CopyAttachment< TLayout, TAttachment >::extract(), ug::ComPol_CopyAttachment< TLayout, TAttachment >::extract_on_constrained_elems_only(), and ug::ComPol_CopyAttachment< TLayout, TAttachment >::set_attachment().
Member Function Documentation
template<class TNodeLayout , class TAttachment > bool ug::ComPol_CopyAttachment< TNodeLayout, TAttachment >::collect (ug::BinaryBuffer & buff, const Interface & interface) virtual
writes the data for the given interface to the buffer.
Derived from ICollector Make sure that all members of the interface are members of the grid too.
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::ComPol_CopyAttachment< TLayout, TAttachment >::extract(), ug::ComPol_CopyAttachment< TLayout, TAttachment >::m_aaVal, and ug::Serialize().
Referenced by ug::ComPol_CopyAttachment< TLayout, TAttachment >::set_attachment(), and ug::ComPol_CopyAttachment< TLayout, TAttachment >::~ComPol_CopyAttachment().
template<class TNodeLayout , class TAttachment > bool ug::ComPol_CopyAttachment< TNodeLayout, TAttachment >::extract (ug::BinaryBuffer & buff, const Interface & interface) virtual
reads the data from the buffer to the given interface .
Derived from IExtractor Make sure that all members of the interface are members of the grid too.
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::Deserialize(), ug::ComPol_CopyAttachment< TLayout, TAttachment >::extract_on_constrained_elems_only(), ug::ComPol_CopyAttachment< TLayout, TAttachment >::m_aaVal, and ug::ComPol_CopyAttachment< TLayout, TAttachment >::m_extractOnConstrainedElemsOnly.
Referenced by ug::ComPol_CopyAttachment< TLayout, TAttachment >::collect(), and ug::ComPol_CopyAttachment< TLayout, TAttachment >::~ComPol_CopyAttachment().
template<class TNodeLayout , class TAttachment > void ug::ComPol_CopyAttachment< TNodeLayout, TAttachment >::extract_on_constrained_elems_only (bool enable)
References ug::ComPol_CopyAttachment< TLayout, TAttachment >::m_extractOnConstrainedElemsOnly.
Referenced by ug::ComPol_CopyAttachment< TLayout, TAttachment >::extract(), ug::SideAndElemErrEstData< TDomain >::summarize_err_est_data(), and ug::ComPol_CopyAttachment< TLayout, TAttachment >::~ComPol_CopyAttachment().
template<class TNodeLayout , class TAttachment > void ug::ComPol_CopyAttachment< TNodeLayout, TAttachment >::set_attachment (Grid & grid, TAttachment & attachment)
The grid and the attachment from where the data shall be copied.
Make sure that attachment is attached to the correct element-type of the grid.
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::ComPol_CopyAttachment< TLayout, TAttachment >::collect(), and ug::ComPol_CopyAttachment< TLayout, TAttachment >::m_aaVal.
Referenced by ug::ComPol_CopyAttachment< TLayout, TAttachment >::ComPol_CopyAttachment(), and ug::ComPol_CopyAttachment< TLayout, TAttachment >::~ComPol_CopyAttachment().
Member Data Documentation
template<class TLayout, class TAttachment> Grid::AttachmentAccessor<GeomObj, TAttachment> ug::ComPol_CopyAttachment< TLayout, TAttachment >::m_aaVal protected
Referenced by ug::ComPol_CopyAttachment< TLayout, TAttachment >::collect(), ug::ComPol_CopyAttachment< TLayout, TAttachment >::extract(), and ug::ComPol_CopyAttachment< TLayout, TAttachment >::set_attachment().
template<class TLayout, class TAttachment> bool ug::ComPol_CopyAttachment< TLayout, TAttachment >::m_extractOnConstrainedElemsOnly protected
Referenced by ug::ComPol_CopyAttachment< TLayout, TAttachment >::extract(), and ug::ComPol_CopyAttachment< TLayout, TAttachment >::extract_on_constrained_elems_only().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/util/compol_copy_attachment.h