ug4: ug::IMultigridElementIndicators< TDomain > Class Template Reference
ug::IMultigridElementIndicators< TDomain > Class Template Reference
This class encapsulates the multi-grid attachments for error estimation.
#include <error_elem_marking_strategy.h>
Public Types
typedef MultiGrid::AttachmentAccessor< elem_type, error_attachment_type > attachment_accessor_type
typedef domain_traits< dim >::element_type elem_type
typedef Attachment< number > error_attachment_type
Public Member Functions
void attach_indicators (SmartPtr< MultiGrid > pMG)
Attach error indicator to multigrid.
void detach_indicators ()
Detach error indicator from multigrid.
number & error (typename attachment_accessor_type::atraits::ConstElemPtr pElem)
returns error indicator value
const number & error (typename attachment_accessor_type::atraits::ConstElemPtr pElem) const
returns error indicator value
attachment_accessor_type & errors ()
IMultigridElementIndicators ()
CTOR.
~IMultigridElementIndicators ()
DTOR.
Static Public Attributes
static const int dim = TDomain::dim
world dimension
Protected Attributes
attachment_accessor_type m_aaError
error_attachment_type m_aError
SmartPtr< MultiGrid > m_pMG
Friends
class IElementMarkingStrategy< TDomain >
Detailed Description
template<typename TDomain>
class ug::IMultigridElementIndicators< TDomain >
This class encapsulates the multi-grid attachments for error estimation.
Purpose: replaces direct access to 'm_aaError' etc.
Member Typedef Documentation
attachment_accessor_type
template<typename TDomain > typedef MultiGrid::AttachmentAccessor<elem_type, error_attachment_type > ug::IMultigridElementIndicators< TDomain >::attachment_accessor_type
elem_type
template<typename TDomain > typedef domain_traits<dim>::element_type ug::IMultigridElementIndicators< TDomain >::elem_type
error_attachment_type
template<typename TDomain > typedef Attachment<number> ug::IMultigridElementIndicators< TDomain >::error_attachment_type
Constructor & Destructor Documentation
IMultigridElementIndicators()
template<typename TDomain > ug::IMultigridElementIndicators< TDomain >::IMultigridElementIndicators () inline
CTOR.
~IMultigridElementIndicators()
template<typename TDomain > ug::IMultigridElementIndicators< TDomain >::~IMultigridElementIndicators () inline
DTOR.
References ug::IMultigridElementIndicators< TDomain >::detach_indicators().
Member Function Documentation
attach_indicators()
template<typename TDomain > void ug::IMultigridElementIndicators< TDomain >::attach_indicators (SmartPtr< MultiGrid > pMG) inline
Attach error indicator to multigrid.
References ug::IMultigridElementIndicators< TDomain >::m_aaError, ug::IMultigridElementIndicators< TDomain >::m_aError, and ug::IMultigridElementIndicators< TDomain >::m_pMG.
detach_indicators()
template<typename TDomain > void ug::IMultigridElementIndicators< TDomain >::detach_indicators () inline
Detach error indicator from multigrid.
References SmartPtr< T, FreePolicy >::invalid(), ug::IMultigridElementIndicators< TDomain >::m_aError, and ug::IMultigridElementIndicators< TDomain >::m_pMG.
Referenced by ug::IMultigridElementIndicators< TDomain >::~IMultigridElementIndicators().
error() [1/2]
template<typename TDomain > number& ug::IMultigridElementIndicators< TDomain >::error (typename attachment_accessor_type::atraits::ConstElemPtr pElem) inline
returns error indicator value
References ug::IMultigridElementIndicators< TDomain >::m_aaError.
error() [2/2]
template<typename TDomain > const number& ug::IMultigridElementIndicators< TDomain >::error (typename attachment_accessor_type::atraits::ConstElemPtr pElem) const inline
returns error indicator value
References ug::IMultigridElementIndicators< TDomain >::m_aaError.
errors()
template<typename TDomain > attachment_accessor_type& ug::IMultigridElementIndicators< TDomain >::errors () inline
TODO: remove this function (mbreit: no, please leave it, it is very useful, at least with const access)
References ug::IMultigridElementIndicators< TDomain >::m_aaError.
Referenced by ug::IElementMarkingStrategy< TDomain >::mark().
Friends And Related Function Documentation
IElementMarkingStrategy< TDomain >
template<typename TDomain > friend class IElementMarkingStrategy< TDomain > friend
Member Data Documentation
dim
template<typename TDomain > const int ug::IMultigridElementIndicators< TDomain >::dim = TDomain::dim static
world dimension
m_aaError
template<typename TDomain > attachment_accessor_type ug::IMultigridElementIndicators< TDomain >::m_aaError protected
Referenced by ug::IMultigridElementIndicators< TDomain >::attach_indicators(), ug::IMultigridElementIndicators< TDomain >::error(), and ug::IMultigridElementIndicators< TDomain >::errors().
m_aError
template<typename TDomain > error_attachment_type ug::IMultigridElementIndicators< TDomain >::m_aError protected
Referenced by ug::IMultigridElementIndicators< TDomain >::attach_indicators(), and ug::IMultigridElementIndicators< TDomain >::detach_indicators().
m_pMG
template<typename TDomain > SmartPtr<MultiGrid> ug::IMultigridElementIndicators< TDomain >::m_pMG protected
Referenced by ug::IMultigridElementIndicators< TDomain >::attach_indicators(), and ug::IMultigridElementIndicators< TDomain >::detach_indicators().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/error_elem_marking_strategy.h