ug4: ug::MatrixOperator< M, X, Y > Class Template Reference
ug::MatrixOperator< M, X, Y > Class Template Reference
#include <matrix_operator.h>
Public Types
typedef Y codomain_function_type
typedef X domain_function_type
typedef M matrix_type
Public Types inherited from ug::ILinearOperator< X, Y >
typedef Y codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Types inherited from ug::IOperator< X, Y >
typedef Y codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Member Functions
virtual void apply (Y &f, const X &u)
virtual void apply_sub (Y &f, const X &u)
virtual M & get_matrix ()
virtual void init (const X &u)
init operator depending on a function u
virtual void init ()
init operator
Public Member Functions inherited from ug::ILinearOperator< X, Y >
virtual void prepare (X &u)
default implementation for IOperator interface
virtual ~ILinearOperator ()
virtual destructor
Public Member Functions inherited from ug::IOperator< X, Y >
virtual ~IOperator ()
virtual destructor
Member Typedef Documentation
codomain_function_type
template<typename M, typename X, typename Y = X> typedef Y ug::MatrixOperator< M, X, Y >::codomain_function_type
domain_function_type
template<typename M, typename X, typename Y = X> typedef X ug::MatrixOperator< M, X, Y >::domain_function_type
matrix_type
template<typename M, typename X, typename Y = X> typedef M ug::MatrixOperator< M, X, Y >::matrix_type
Member Function Documentation
apply()
template<typename M, typename X, typename Y = X> virtual void ug::MatrixOperator< M, X, Y >::apply (Y & f, const X & u) inline virtual
This method applies the operator, i.e. f = L*u (or d = J(u)*c in iterative schemes). Note, that the operator must have been initialized once before this method can be used.
Parameters
[in] u domain function
[out] f codomain function
Returns
bool success flag
Implements ug::ILinearOperator< X, Y >.
Reimplemented in ug::SchurComplementMatrixOperator< TAlgebra, M, X, Y >, ug::SchurComplementMatrixOperator< TAlgebra, matrix_type, vector_type >, ug::AssembledLinearOperator< TAlgebra >, and ug::AssembledLinearOperator< algebra_type >.
apply_sub()
template<typename M, typename X, typename Y = X> virtual void ug::MatrixOperator< M, X, Y >::apply_sub (Y & f, const X & u) inline virtual
This method applies the operator and subracts the result from the input codomain function, i.e. f -= L*u (or d -= J(u)*c in iterative schemes). Note, that the operator must have been initialized once before this method can be used.
Parameters
[in] u domain function
[in,out] f codomain function
Returns
bool success flag
Implements ug::ILinearOperator< X, Y >.
Reimplemented in ug::SchurComplementMatrixOperator< TAlgebra, M, X, Y >, ug::SchurComplementMatrixOperator< TAlgebra, matrix_type, vector_type >, ug::AssembledLinearOperator< TAlgebra >, and ug::AssembledLinearOperator< algebra_type >.
get_matrix()
template<typename M, typename X, typename Y = X> virtual M& ug::MatrixOperator< M, X, Y >::get_matrix () inline virtual
Reimplemented in ug::SchurComplementMatrixOperator< TAlgebra, M, X, Y >, and ug::SchurComplementMatrixOperator< TAlgebra, matrix_type, vector_type >.
Referenced by ug::MatrixDiagonal< M, X, Y >::apply(), ug::MatrixDiagonal< M, X, Y >::apply_sub(), ug::MatAdd(), ug::MatIdentity(), ug::MatScale(), ug::MatTranspose(), and ug::SaveMatrixToMTX().
init() [1/2]
template<typename M, typename X, typename Y = X> virtual void ug::MatrixOperator< M, X, Y >::init (const X & u) inline virtual
init operator depending on a function u
This method initializes the operator. Once initialized the 'apply'-method can be called. The function u is passed here, since the linear operator may be the linearization of some non-linear operator. Thus, the operator depends on the linearization point. If the operator is not a linearization, this method can be implemented by simply calling init() and forgetting about the linearization point.
Parameters
[in] u function (linearization point)
Returns
bool success flag
Implements ug::ILinearOperator< X, Y >.
Reimplemented in ug::SchurComplementMatrixOperator< TAlgebra, M, X, Y >, ug::SchurComplementMatrixOperator< TAlgebra, matrix_type, vector_type >, ug::AssembledLinearOperator< TAlgebra >, and ug::AssembledLinearOperator< algebra_type >.
Referenced by ug::MatrixDiagonal< M, X, Y >::init().
init() [2/2]
template<typename M, typename X, typename Y = X> virtual void ug::MatrixOperator< M, X, Y >::init () inline virtual
init operator
This method initializes the operator. Once initialized the 'apply'-method can be called. If the operator is a linearization this function returns false.
Returns
bool success flag
Implements ug::ILinearOperator< X, Y >.
Reimplemented in ug::SchurComplementMatrixOperator< TAlgebra, M, X, Y >, ug::SchurComplementMatrixOperator< TAlgebra, matrix_type, vector_type >, ug::AssembledLinearOperator< TAlgebra >, and ug::AssembledLinearOperator< algebra_type >.
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/interface/matrix_operator.h