ug4: ug::ILU< TAlgebra > Class Template Reference
ug::ILU< TAlgebra > Class Template Reference
ILU / ILU(beta) preconditioner.
#include <ilu.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef IPreconditioner< TAlgebra > base_type
Base type.
typedef IPreconditioner< TAlgebra >::matrix_operator_type matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef IOrderingAlgorithm< TAlgebra, ordering_container_type > ordering_algo_type
typedef std::vector< size_t > ordering_container_type
Ordering type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual SmartPtr< ILinearIterator< vector_type > > clone ()
Clone.
void enable_consistent_interfaces (bool enable)
enables consistent interfaces.
void enable_overlap (bool enable)
ILU (const ILU< TAlgebra > &parent)
clone constructor
ILU (double beta=0.0)
void set_beta (double beta)
set factor for \(ILU_{\beta} \)
void set_disable_preprocessing (bool bDisable)
disable preprocessing (if underlying matrix has not changed)
void set_inversion_eps (number eps)
sets the smallest allowed value for the Aii/Bi quotient
void set_ordering_algorithm (SmartPtr< ordering_algo_type > ordering_algo)
sets an ordering algorithm
void set_sort (bool b)
set cuthill-mckee sort on/off
void set_sort_eps (number eps)
sets the smallest allowed value for sorted factorization
virtual bool supports_parallel () const
returns if parallel solving is supported
virtual ~ILU ()
Destructor.
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
virtual std::string config_string () const
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
returns true if the debug writer is set
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
void apply_ordering ()
void applyLU (vector_type &c, const vector_type &d, vector_type &tmp)
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< ILinearOperator< vector_type > > L)
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
virtual const char * name () const
returns the name of iterator
virtual bool postprocess ()
Postprocess routine.
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
initializes the preconditioner
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
computes a new correction c = B*d
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
void enter_debug_writer_section (const char *secDir)
enters a debugging section
void enter_debug_writer_section (std::string secDir)
enters a debugging section
void leave_debug_writer_section ()
leaves a debugging section
void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
void write_debug (const matrix_type &mat, std::string name)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
bool m_bDisablePreprocessing
whether or not to disable preprocessing
number m_beta
factor for ILU-beta
bool m_bSortIsIdentity
vector_type m_h
help vector
matrix_type m_ILU
storage for factorization
number m_invEps
smallest allowed value for the Aii/Bi quotient
std::vector< size_t > m_newIndex
vector_type m_oC
vector_type m_oD
for overlaps only
ordering_container_type m_old_ordering
std::vector< size_t > m_oldIndex
ordering_container_type m_ordering
SmartPtr< OverlapWriter< TAlgebra > > m_overlapWriter
number m_sortEps
smallest allowed value for sorted factorization
SmartPtr< ordering_algo_type > m_spOrderingAlgo
for ordering algorithms
const vector_type * m_u
bool m_useConsistentInterfaces
bool m_useOverlap
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Private Member Functions
template<class T >
void write_overlap_debug (const T &t, std::string name)
Detailed Description
template<typename TAlgebra>
class ug::ILU< TAlgebra >
ILU / ILU(beta) preconditioner.
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::ILU< TAlgebra >::algebra_type
Algebra type.
base_type
template<typename TAlgebra > typedef IPreconditioner<TAlgebra> ug::ILU< TAlgebra >::base_type
Base type.
matrix_operator_type
template<typename TAlgebra > typedef IPreconditioner<TAlgebra>::matrix_operator_type ug::ILU< TAlgebra >::matrix_operator_type
Matrix Operator type.
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::ILU< TAlgebra >::matrix_type
Matrix type.
ordering_algo_type
template<typename TAlgebra > typedef IOrderingAlgorithm<TAlgebra, ordering_container_type> ug::ILU< TAlgebra >::ordering_algo_type
ordering_container_type
template<typename TAlgebra > typedef std::vector<size_t> ug::ILU< TAlgebra >::ordering_container_type
Ordering type.
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::ILU< TAlgebra >::vector_type
Vector type.
Constructor & Destructor Documentation
ILU() [1/2]
template<typename TAlgebra > ug::ILU< TAlgebra >::ILU (double beta = 0.0) inline
ILU() [2/2]
template<typename TAlgebra > ug::ILU< TAlgebra >::ILU (const ILU< TAlgebra > & parent) inline
clone constructor
~ILU()
template<typename TAlgebra > virtual ug::ILU< TAlgebra >::~ILU () inline virtual
Destructor.
Member Function Documentation
apply_ordering()
template<typename TAlgebra > void ug::ILU< TAlgebra >::apply_ordering () inline protected
References ug::get_clock_s(), ug::GetInversePermutation(), ug::ILU< TAlgebra >::m_bSortIsIdentity, ug::ILU< TAlgebra >::m_ILU, ug::ILU< TAlgebra >::m_old_ordering, ug::ILU< TAlgebra >::m_ordering, ug::ILU< TAlgebra >::m_spOrderingAlgo, ug::ILU< TAlgebra >::m_u, ug::ILU< TAlgebra >::m_useOverlap, ug::SetMatrixAsPermutation(), UG_LOG, and UG_THROW.
Referenced by ug::ILU< TAlgebra >::preprocess().
applyLU()
template<typename TAlgebra > void ug::ILU< TAlgebra >::applyLU (vector_type & c, const vector_type & d, vector_type & tmp) inline protected
References ug::invert_L(), ug::invert_U(), ug::ILU< TAlgebra >::m_bSortIsIdentity, ug::ILU< TAlgebra >::m_ILU, ug::ILU< TAlgebra >::m_invEps, ug::ILU< TAlgebra >::m_old_ordering, ug::ILU< TAlgebra >::m_ordering, ug::ILU< TAlgebra >::m_spOrderingAlgo, ug::VectorDebugWritingObject< TAlgebra::vector_type >::print_debugger_message(), and ug::SetVectorAsPermutation().
Referenced by ug::ILU< TAlgebra >::step().
clone()
template<typename TAlgebra > virtual SmartPtr<ILinearIterator<vector_type> > ug::ILU< TAlgebra >::clone () inline virtual
Clone.
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References make_sp().
enable_consistent_interfaces()
template<typename TAlgebra > void ug::ILU< TAlgebra >::enable_consistent_interfaces (bool enable) inline
enables consistent interfaces.
Connections between coefficients which lie in the same parallel interface are made consistent between processes.
References ug::ILU< TAlgebra >::m_useConsistentInterfaces.
enable_overlap()
template<typename TAlgebra > void ug::ILU< TAlgebra >::enable_overlap (bool enable) inline
References ug::ILU< TAlgebra >::m_useOverlap.
init() [1/3]
template<typename TAlgebra > virtual bool ug::ILU< TAlgebra >::init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type & u) inline protected virtual
implements the ILinearIterator-interface for matrix based preconditioner
This method implements the ILinearIterator interface. It check if the passed linear operator is matrix based (otherwise this preconditioner can not be used for the linear operator). Then the request is forwarded to the implementation of matrix based operators.
Parameters
[in] J linear operator
[in] u linearization point
Returns
bool success flag
Reimplemented from ug::IPreconditioner< TAlgebra >.
References ug::IPreconditioner< TAlgebra >::init(), SmartPtr< T, FreePolicy >::invalid(), ug::ILU< TAlgebra >::m_u, ug::ILU< TAlgebra >::name(), and UG_THROW.
init() [2/3]
template<typename TAlgebra > bool ug::ILU< TAlgebra >::init (SmartPtr< ILinearOperator< vector_type > > L) inline protected
References ug::IPreconditioner< TAlgebra >::init(), SmartPtr< T, FreePolicy >::invalid(), ug::ILU< TAlgebra >::m_u, ug::ILU< TAlgebra >::name(), and UG_THROW.
init() [3/3]
template<typename TAlgebra > bool ug::ILU< TAlgebra >::init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op) inline protected
References ug::IPreconditioner< TAlgebra >::init(), and ug::ILU< TAlgebra >::m_u.
name()
template<typename TAlgebra > virtual const char* ug::ILU< TAlgebra >::name () const inline protected virtual
returns the name of iterator
This method returns the name of the iterator operator. This function is typically needed, when the iterator operator is used inside of another operator and some debug output should be printed
Returns
const char* name of inverse operator
Implements ug::IPreconditioner< TAlgebra >.
Referenced by ug::ILU< TAlgebra >::init(), and ug::ILU< TAlgebra >::write_overlap_debug().
postprocess()
template<typename TAlgebra > virtual bool ug::ILU< TAlgebra >::postprocess () inline protected virtual
Postprocess routine.
Implements ug::IPreconditioner< TAlgebra >.
preprocess()
template<typename TAlgebra > virtual bool ug::ILU< TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) inline protected virtual
initializes the preconditioner
This method is used to initialize the preconditioner. Usually, here are performed computationally expensive operations, that should only be computed once for an underlying matrix (e.g. LU factorization), while the preconditioner will by applied (using 'step'-method) several times.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::ILU< TAlgebra >::apply_ordering(), pcl::CollectUniqueElements(), ug::CreateOverlap(), ug::DebugWritingObject< TAlgebra >::debug_writer(), ug::FactorizeILU(), ug::FactorizeILUBeta(), ug::FactorizeILUSorted(), ug::ILU< TAlgebra >::m_bDisablePreprocessing, ug::ILU< TAlgebra >::m_beta, ug::ILU< TAlgebra >::m_h, ug::ILU< TAlgebra >::m_ILU, ug::ILU< TAlgebra >::m_oC, ug::ILU< TAlgebra >::m_oD, ug::ILU< TAlgebra >::m_overlapWriter, ug::ILU< TAlgebra >::m_sortEps, ug::ILU< TAlgebra >::m_useConsistentInterfaces, ug::ILU< TAlgebra >::m_useOverlap, make_sp(), ug::MatAddSlaveRowsToMasterRowOverlap0(), ug::MatMakeConsistentOverlap0(), PROFILE_BEGIN_GROUP, ug::SetDirichletRow(), ug::DebugWritingObject< TAlgebra >::write_debug(), and ug::ILU< TAlgebra >::write_overlap_debug().
set_beta()
template<typename TAlgebra > void ug::ILU< TAlgebra >::set_beta (double beta) inline
set factor for \(ILU_{\beta} \)
References ug::ILU< TAlgebra >::m_beta.
set_disable_preprocessing()
template<typename TAlgebra > void ug::ILU< TAlgebra >::set_disable_preprocessing (bool bDisable) inline
disable preprocessing (if underlying matrix has not changed)
References ug::ILU< TAlgebra >::m_bDisablePreprocessing.
set_inversion_eps()
template<typename TAlgebra > void ug::ILU< TAlgebra >::set_inversion_eps (number eps) inline
sets the smallest allowed value for the Aii/Bi quotient
References ug::ILU< TAlgebra >::m_invEps.
set_ordering_algorithm()
template<typename TAlgebra > void ug::ILU< TAlgebra >::set_ordering_algorithm (SmartPtr< ordering_algo_type > ordering_algo) inline
sets an ordering algorithm
References ug::ILU< TAlgebra >::m_spOrderingAlgo.
set_sort()
template<typename TAlgebra > void ug::ILU< TAlgebra >::set_sort (bool b) inline
set cuthill-mckee sort on/off
References ug::ILU< TAlgebra >::m_spOrderingAlgo, make_sp(), SPNULL, and UG_LOG.
set_sort_eps()
template<typename TAlgebra > void ug::ILU< TAlgebra >::set_sort_eps (number eps) inline
sets the smallest allowed value for sorted factorization
References ug::ILU< TAlgebra >::m_sortEps.
step()
template<typename TAlgebra > virtual bool ug::ILU< TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) inline protected virtual
computes a new correction c = B*d
This method computes a new correction c = B*d. It can only be called, when the preprocess has been done.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
[out] c correction
[in] d defect
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::ILU< TAlgebra >::applyLU(), ug::ILU< TAlgebra >::m_h, ug::ILU< TAlgebra >::m_oC, ug::ILU< TAlgebra >::m_oD, ug::ILU< TAlgebra >::m_useConsistentInterfaces, ug::ILU< TAlgebra >::m_useOverlap, PROFILE_BEGIN_GROUP, ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::PST_UNIQUE, ug::SetLayoutValues(), ug::DebugWritingObject< TAlgebra >::write_debug(), and ug::ILU< TAlgebra >::write_overlap_debug().
supports_parallel()
template<typename TAlgebra > virtual bool ug::ILU< TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearIterator< TAlgebra::vector_type >.
write_overlap_debug()
template<typename TAlgebra > template<class T > void ug::ILU< TAlgebra >::write_overlap_debug (const T & t, std::string name) inline private
References ug::DebugWritingObject< TAlgebra >::debug_writer(), ug::ILU< TAlgebra >::m_overlapWriter, ug::ILU< TAlgebra >::m_useOverlap, ug::ILU< TAlgebra >::name(), and ug::DebugWritingObject< TAlgebra >::write_debug().
Referenced by ug::ILU< TAlgebra >::preprocess(), and ug::ILU< TAlgebra >::step().
Member Data Documentation
m_bDisablePreprocessing
template<typename TAlgebra > bool ug::ILU< TAlgebra >::m_bDisablePreprocessing protected
whether or not to disable preprocessing
Referenced by ug::ILU< TAlgebra >::preprocess(), and ug::ILU< TAlgebra >::set_disable_preprocessing().
m_beta
template<typename TAlgebra > number ug::ILU< TAlgebra >::m_beta protected
factor for ILU-beta
Referenced by ug::ILU< TAlgebra >::preprocess(), and ug::ILU< TAlgebra >::set_beta().
m_bSortIsIdentity
template<typename TAlgebra > bool ug::ILU< TAlgebra >::m_bSortIsIdentity protected
Referenced by ug::ILU< TAlgebra >::apply_ordering(), and ug::ILU< TAlgebra >::applyLU().
m_h
template<typename TAlgebra > vector_type ug::ILU< TAlgebra >::m_h protected
help vector
Referenced by ug::ILU< TAlgebra >::preprocess(), and ug::ILU< TAlgebra >::step().
m_ILU
template<typename TAlgebra > matrix_type ug::ILU< TAlgebra >::m_ILU protected
storage for factorization
Referenced by ug::ILU< TAlgebra >::apply_ordering(), ug::ILU< TAlgebra >::applyLU(), and ug::ILU< TAlgebra >::preprocess().
m_invEps
template<typename TAlgebra > number ug::ILU< TAlgebra >::m_invEps protected
smallest allowed value for the Aii/Bi quotient
Referenced by ug::ILU< TAlgebra >::applyLU(), and ug::ILU< TAlgebra >::set_inversion_eps().
m_newIndex
template<typename TAlgebra > std::vector<size_t> ug::ILU< TAlgebra >::m_newIndex protected
m_oC
template<typename TAlgebra > vector_type ug::ILU< TAlgebra >::m_oC protected
Referenced by ug::ILU< TAlgebra >::preprocess(), and ug::ILU< TAlgebra >::step().
m_oD
template<typename TAlgebra > vector_type ug::ILU< TAlgebra >::m_oD protected
for overlaps only
Referenced by ug::ILU< TAlgebra >::preprocess(), and ug::ILU< TAlgebra >::step().
m_old_ordering
template<typename TAlgebra > ordering_container_type ug::ILU< TAlgebra >::m_old_ordering protected
Referenced by ug::ILU< TAlgebra >::apply_ordering(), and ug::ILU< TAlgebra >::applyLU().
m_oldIndex
template<typename TAlgebra > std::vector<size_t> ug::ILU< TAlgebra >::m_oldIndex protected
m_ordering
template<typename TAlgebra > ordering_container_type ug::ILU< TAlgebra >::m_ordering protected
Referenced by ug::ILU< TAlgebra >::apply_ordering(), and ug::ILU< TAlgebra >::applyLU().
m_overlapWriter
template<typename TAlgebra > SmartPtr<OverlapWriter<TAlgebra> > ug::ILU< TAlgebra >::m_overlapWriter protected
Referenced by ug::ILU< TAlgebra >::preprocess(), and ug::ILU< TAlgebra >::write_overlap_debug().
m_sortEps
template<typename TAlgebra > number ug::ILU< TAlgebra >::m_sortEps protected
smallest allowed value for sorted factorization
Referenced by ug::ILU< TAlgebra >::preprocess(), and ug::ILU< TAlgebra >::set_sort_eps().
m_spOrderingAlgo
template<typename TAlgebra > SmartPtr<ordering_algo_type> ug::ILU< TAlgebra >::m_spOrderingAlgo protected
for ordering algorithms
Referenced by ug::ILU< TAlgebra >::apply_ordering(), ug::ILU< TAlgebra >::applyLU(), ug::ILU< TAlgebra >::set_ordering_algorithm(), and ug::ILU< TAlgebra >::set_sort().
m_u
template<typename TAlgebra > const vector_type* ug::ILU< TAlgebra >::m_u protected
Referenced by ug::ILU< TAlgebra >::apply_ordering(), and ug::ILU< TAlgebra >::init().
m_useConsistentInterfaces
template<typename TAlgebra > bool ug::ILU< TAlgebra >::m_useConsistentInterfaces protected
Referenced by ug::ILU< TAlgebra >::enable_consistent_interfaces(), ug::ILU< TAlgebra >::preprocess(), and ug::ILU< TAlgebra >::step().
m_useOverlap
template<typename TAlgebra > bool ug::ILU< TAlgebra >::m_useOverlap protected
Referenced by ug::ILU< TAlgebra >::apply_ordering(), ug::ILU< TAlgebra >::enable_overlap(), ug::ILU< TAlgebra >::preprocess(), ug::ILU< TAlgebra >::step(), and ug::ILU< TAlgebra >::write_overlap_debug().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/preconditioner/ilu.h