ug4: ug::ScalarGridFunctionData< TGridFunction > Class Template Reference
ug::ScalarGridFunctionData< TGridFunction > Class Template Reference
#include <integrate.h>
Public Types
typedef TGridFunction::domain_type domain_type
Public Member Functions
template<typename TElem >
size_t dof_indices (TElem *elem, std::vector< DoFIndex > &ind, bool bHang=false, bool bClear=true) const
SmartPtr< domain_type > domain ()
returns domain (forward)
ConstSmartPtr< domain_type > domain () const
returns const domain (forward)
size_t fct ()
TGridFunction & grid_function ()
const TGridFunction & grid_function () const
const LFEID & id () const
bool is_def_in_subset (int si) const
returns true, iff scalar function is defined in subset si
ScalarGridFunctionData (TGridFunction &gridFct, size_t cmp)
Private Attributes
size_t m_fct
component of function
TGridFunction & m_gridFct
grid function
LFEID m_id
local finite element id
Member Typedef Documentation
domain_type
template<typename TGridFunction> typedef TGridFunction::domain_type ug::ScalarGridFunctionData< TGridFunction >::domain_type
Constructor & Destructor Documentation
ScalarGridFunctionData()
template<typename TGridFunction> ug::ScalarGridFunctionData< TGridFunction >::ScalarGridFunctionData (TGridFunction & gridFct, size_t cmp) inline
Member Function Documentation
dof_indices()
template<typename TGridFunction> template<typename TElem > size_t ug::ScalarGridFunctionData< TGridFunction >::dof_indices (TElem * elem, std::vector< DoFIndex > & ind, bool bHang = false, bool bClear = true) const inline
References ug::ScalarGridFunctionData< TGridFunction >::m_fct, and ug::ScalarGridFunctionData< TGridFunction >::m_gridFct.
Referenced by ug::L2ErrorIntegrand< TGridFunction >::evaluate(), ug::H1ErrorIntegrand< TGridFunction >::evaluate(), ug::L2Integrand< TGridFunction >::evaluate(), ug::L2DistIntegrand< TGridFunction >::evaluate(), ug::H1SemiDistIntegrand< TGridFunction >::evaluate(), and ug::H1EnergyIntegrand< TGridFunction >::evaluate().
domain() [1/2]
template<typename TGridFunction> SmartPtr<domain_type> ug::ScalarGridFunctionData< TGridFunction >::domain () inline
returns domain (forward)
References ug::ScalarGridFunctionData< TGridFunction >::m_gridFct.
Referenced by ug::UserDataDistIntegrandSq< TData, TGridFunction >::evaluate(), ug::L2DistIntegrand< TGridFunction >::evaluate(), ug::H1SemiDistIntegrand< TGridFunction >::evaluate(), ug::H1EnergyIntegrand< TGridFunction >::evaluate(), ug::H1SemiDistIntegrand< TGridFunction >::H1SemiDistIntegrand(), ug::L2DistIntegrand< TGridFunction >::L2DistIntegrand(), and ug::UserDataDistIntegrandSq< TData, TGridFunction >::UserDataDistIntegrandSq().
domain() [2/2]
template<typename TGridFunction> ConstSmartPtr<domain_type> ug::ScalarGridFunctionData< TGridFunction >::domain () const inline
returns const domain (forward)
References ug::ScalarGridFunctionData< TGridFunction >::m_gridFct.
fct()
template<typename TGridFunction> size_t ug::ScalarGridFunctionData< TGridFunction >::fct () inline
References ug::ScalarGridFunctionData< TGridFunction >::m_fct.
Referenced by ug::H1SemiIntegrand< TGridFunction >::evaluate(), ug::H1EnergyIntegrand< TGridFunction >::evaluate(), ug::H1Error(), ug::H1SemiNorm2(), ug::L2Error(), ug::L2Norm2(), ug::UserDataDistIntegrandSq< TData, TGridFunction >::set_subset(), ug::L2ErrorIntegrand< TGridFunction >::set_subset(), ug::H1ErrorIntegrand< TGridFunction >::set_subset(), ug::L2Integrand< TGridFunction >::set_subset(), ug::L2DistIntegrand< TGridFunction >::set_subset(), ug::H1SemiIntegrand< TGridFunction >::set_subset(), ug::H1SemiDistIntegrand< TGridFunction >::set_subset(), and ug::H1EnergyIntegrand< TGridFunction >::set_subset().
grid_function() [1/2]
template<typename TGridFunction> TGridFunction& ug::ScalarGridFunctionData< TGridFunction >::grid_function () inline
References ug::ScalarGridFunctionData< TGridFunction >::m_gridFct.
Referenced by ug::UserDataDistIntegrandSq< TData, TGridFunction >::evaluate(), ug::L2ErrorIntegrand< TGridFunction >::evaluate(), ug::H1ErrorIntegrand< TGridFunction >::evaluate(), ug::L2Integrand< TGridFunction >::evaluate(), ug::L2DistIntegrand< TGridFunction >::evaluate(), ug::H1SemiIntegrand< TGridFunction >::evaluate(), ug::H1SemiDistIntegrand< TGridFunction >::evaluate(), and ug::H1EnergyIntegrand< TGridFunction >::evaluate().
grid_function() [2/2]
template<typename TGridFunction> const TGridFunction& ug::ScalarGridFunctionData< TGridFunction >::grid_function () const inline
References ug::ScalarGridFunctionData< TGridFunction >::m_gridFct.
id()
template<typename TGridFunction> const LFEID& ug::ScalarGridFunctionData< TGridFunction >::id () const inline
References ug::ScalarGridFunctionData< TGridFunction >::m_id.
Referenced by ug::L2ErrorIntegrand< TGridFunction >::evaluate(), ug::H1ErrorIntegrand< TGridFunction >::evaluate(), ug::L2Integrand< TGridFunction >::evaluate(), ug::L2DistIntegrand< TGridFunction >::evaluate(), ug::H1SemiIntegrand< TGridFunction >::evaluate(), ug::H1SemiDistIntegrand< TGridFunction >::evaluate(), and ug::H1EnergyIntegrand< TGridFunction >::evaluate().
is_def_in_subset()
template<typename TGridFunction> bool ug::ScalarGridFunctionData< TGridFunction >::is_def_in_subset (int si) const inline
returns true, iff scalar function is defined in subset si
References ug::ScalarGridFunctionData< TGridFunction >::m_fct, and ug::ScalarGridFunctionData< TGridFunction >::m_gridFct.
Referenced by ug::H1EnergyIntegrand< TGridFunction >::evaluate(), ug::UserDataDistIntegrandSq< TData, TGridFunction >::set_subset(), ug::L2ErrorIntegrand< TGridFunction >::set_subset(), ug::H1ErrorIntegrand< TGridFunction >::set_subset(), ug::L2Integrand< TGridFunction >::set_subset(), ug::L2DistIntegrand< TGridFunction >::set_subset(), ug::H1SemiIntegrand< TGridFunction >::set_subset(), ug::H1SemiDistIntegrand< TGridFunction >::set_subset(), and ug::H1EnergyIntegrand< TGridFunction >::set_subset().
Member Data Documentation
m_fct
template<typename TGridFunction> size_t ug::ScalarGridFunctionData< TGridFunction >::m_fct private
component of function
Referenced by ug::ScalarGridFunctionData< TGridFunction >::dof_indices(), ug::H1EnergyIntegrand< TGridFunction >::evaluate(), ug::ScalarGridFunctionData< TGridFunction >::fct(), and ug::ScalarGridFunctionData< TGridFunction >::is_def_in_subset().
m_gridFct
template<typename TGridFunction> TGridFunction& ug::ScalarGridFunctionData< TGridFunction >::m_gridFct private
grid function
Referenced by ug::ScalarGridFunctionData< TGridFunction >::dof_indices(), ug::ScalarGridFunctionData< TGridFunction >::domain(), ug::ScalarGridFunctionData< TGridFunction >::grid_function(), and ug::ScalarGridFunctionData< TGridFunction >::is_def_in_subset().
m_id
template<typename TGridFunction> LFEID ug::ScalarGridFunctionData< TGridFunction >::m_id private
local finite element id
Referenced by ug::H1EnergyIntegrand< TGridFunction >::evaluate(), and ug::ScalarGridFunctionData< TGridFunction >::id().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/integrate.h