ug4: ug::DimFVGeometry< TWorldDim, TDim > Class Template Reference
ug::DimFVGeometry< TWorldDim, TDim > Class Template Reference
Geometry and shape functions for any order Vertex-Centered Finite Volume.
#include <fvho_geom.h>
Classes
class BF
boundary face
class SCV
sub control volume structure
class SCVF
Sub-Control Volume Face structure.
struct SubElement
Public Types
typedef traits::scv_type scv_type
type of SubControlVolume
typedef traits::scvf_type scvf_type
type of SubControlVolumeFace
typedef fv1_dim_traits< TDim, TWorldDim > traits
traits used
Public Member Functions
void add_boundary_subset (int subsetIndex)
add subset that is interpreted as boundary subset.
const BF & bf (int si, size_t i) const
returns the boundary face i for subsetIndex
const std::vector< BF > & bf (int si) const
returns reference to vector of boundary faces for subsetIndex
void clear_boundary_subsets ()
reset all boundary subsets
DimFVGeometry ()
construct object and initialize local values and sizes
size_t num_bf () const
number of all boundary faces
size_t num_bf (int si) const
number of boundary faces on subset 'subsetIndex'
size_t num_boundary_subsets ()
number of registered boundary subsets
size_t num_scv () const
number of SubControlVolumes
size_t num_scv_ips () const
returns number of all scv ips
size_t num_scvf () const
number of SubControlVolumeFaces
size_t num_scvf_ips () const
returns number of all scvf ips
size_t num_sh () const
number of shape functions
void remove_boundary_subset (int subsetIndex)
removes subset that is interpreted as boundary subset.
void reset_curr_elem ()
const SCV & scv (size_t i) const
const access to SubControlVolume number i
const MathVector< worldDim > * scv_global_ips () const
returns all ips of scv as they appear in scv loop
const MathVector< dim > * scv_local_ips () const
returns all ips of scv as they appear in scv loop
const SCVF & scvf (size_t i) const
const access to SubControlVolumeFace number i
const MathVector< worldDim > * scvf_global_ips () const
returns all ips of scvf as they appear in scv loop
const MathVector< dim > * scvf_local_ips () const
returns all ips of scvf as they appear in scv loop
void update (GridObject *pElem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update data for given element
void update (GridObject *pElem, const MathVector< worldDim > *vCornerCoords, const LFEID &lfeID, size_t orderQuad, const ISubsetHandler *ish=NULL)
update data for given element
void update_boundary_faces (GridObject *pElem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update boundary data for given element
void update_local (ReferenceObjectID roid, const LFEID &lfeID, size_t orderQuad)
update local data
void update_local (ReferenceObjectID roid, const LFEID &lfeID)
Static Public Attributes
static const int dim = TDim
dimension of reference element
static const bool staticLocalData = false
flag indicating if local data may change
static const bool usesHangingNodes = false
Hanging node flag: this Geometry does not support hanging nodes.
static const int worldDim = TWorldDim
dimension of world
Protected Attributes
std::map< int, std::vector< BF > > m_mapVectorBF
std::vector< BF > m_vEmptyVectorBF
std::vector< MathVector< worldDim > > m_vGlobSCV_IP
std::vector< MathVector< worldDim > > m_vGlobSCVF_IP
std::vector< MathVector< dim > > m_vLocSCV_IP
std::vector< MathVector< dim > > m_vLocSCVF_IP
std::vector< SubElement > m_vSubElem
subelements (size: numSubElem)
Static Protected Attributes
static const int maxMid = traits::maxNumSCVF +1
Private Attributes
LFEID m_lfeID
current trial space
size_t m_nsh
number of shape functions
size_t m_numSCV
current number of scv
size_t m_numSCVF
current number of scvf
size_t m_numSCVFIP
number of scvf ip
size_t m_numSCVFPerSubElem
current number of SCVF per SubElement
size_t m_numSCVIP
number of scv ip
size_t m_numSCVPerSubElem
number of SCV per SubElement
size_t m_numSubElem
current number of subelements
int m_orderShape
current order
GridObject * m_pElem
pointer to current element
int m_quadOrderSCV
current quadrature order scv
int m_quadOrderSCVF
quadrature order
ReferenceObjectID m_roid
current reference object id
std::vector< SCV > m_vSCV
SubControlVolumes (size: numSCV)
std::vector< SCVF > m_vSCVF
SubControlVolumeFaces (size: numSCVF)
Detailed Description
template<int TWorldDim, int TDim = TWorldDim>
class ug::DimFVGeometry< TWorldDim, TDim >
Geometry and shape functions for any order Vertex-Centered Finite Volume.
Template Parameters
TDim reference element dim
TWorldDim (physical) world dimension
Member Typedef Documentation
template<int TWorldDim, int TDim = TWorldDim> typedef traits::scv_type ug::DimFVGeometry< TWorldDim, TDim >::scv_type
type of SubControlVolume
template<int TWorldDim, int TDim = TWorldDim> typedef traits::scvf_type ug::DimFVGeometry< TWorldDim, TDim >::scvf_type
type of SubControlVolumeFace
template<int TWorldDim, int TDim = TWorldDim> typedef fv1_dim_traits<TDim, TWorldDim> ug::DimFVGeometry< TWorldDim, TDim >::traits
traits used
Constructor & Destructor Documentation
template<int TWorldDim, int TDim> ug::DimFVGeometry< TWorldDim, TDim >::DimFVGeometry ()
construct object and initialize local values and sizes
References ug::DimFVGeometry< TWorldDim, TDim >::update_local().
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
Member Function Documentation
template<int TWorldDim, int TDim = TWorldDim> void ug::DimFVGeometry< TWorldDim, TDim >::add_boundary_subset (int subsetIndex) inline
add subset that is interpreted as boundary subset.
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
template<int TWorldDim, int TDim = TWorldDim> const BF& ug::DimFVGeometry< TWorldDim, TDim >::bf (int si, size_t i) const inline
returns the boundary face i for subsetIndex
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_bf(), UG_ASSERT, and UG_THROW.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
template<int TWorldDim, int TDim = TWorldDim> const std::vector<BF>& ug::DimFVGeometry< TWorldDim, TDim >::bf (int si) const inline
returns reference to vector of boundary faces for subsetIndex
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vEmptyVectorBF.
template<int TWorldDim, int TDim = TWorldDim> void ug::DimFVGeometry< TWorldDim, TDim >::clear_boundary_subsets () inline
reset all boundary subsets
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::num_bf () const inline
number of all boundary faces
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::num_bf (int si) const inline
number of boundary faces on subset 'subsetIndex'
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::num_boundary_subsets () inline
number of registered boundary subsets
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update().
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::num_scv () const inline
number of SubControlVolumes
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::num_scv_ips () const inline
returns number of all scv ips
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::num_scvf () const inline
number of SubControlVolumeFaces
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::num_scvf_ips () const inline
returns number of all scvf ips
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::num_sh () const inline
number of shape functions
template<int TWorldDim, int TDim = TWorldDim> void ug::DimFVGeometry< TWorldDim, TDim >::remove_boundary_subset (int subsetIndex) inline
removes subset that is interpreted as boundary subset.
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
template<int TWorldDim, int TDim = TWorldDim> void ug::DimFVGeometry< TWorldDim, TDim >::reset_curr_elem () inline
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_pElem.
template<int TWorldDim, int TDim = TWorldDim> const SCV& ug::DimFVGeometry< TWorldDim, TDim >::scv (size_t i) const inline
const access to SubControlVolume number i
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSCV, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scv(), and UG_ASSERT.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>* ug::DimFVGeometry< TWorldDim, TDim >::scv_global_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vGlobSCV_IP.
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>* ug::DimFVGeometry< TWorldDim, TDim >::scv_local_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vLocSCV_IP.
template<int TWorldDim, int TDim = TWorldDim> const SCVF& ug::DimFVGeometry< TWorldDim, TDim >::scvf (size_t i) const inline
const access to SubControlVolumeFace number i
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSCVF, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scvf(), and UG_ASSERT.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>* ug::DimFVGeometry< TWorldDim, TDim >::scvf_global_ips () const inline
returns all ips of scvf as they appear in scv loop
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vGlobSCVF_IP.
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>* ug::DimFVGeometry< TWorldDim, TDim >::scvf_local_ips () const inline
returns all ips of scvf as they appear in scv loop
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vLocSCVF_IP.
template<int TWorldDim, int TDim = TWorldDim> void ug::DimFVGeometry< TWorldDim, TDim >::update (GridObject * pElem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL) inline
update data for given element
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim> void ug::DimFVGeometry< TWorldDim, TDim >::update (GridObject * pElem, const MathVector< worldDim > * vCornerCoords, const LFEID & lfeID, size_t orderQuad, const ISubsetHandler * ish = NULL)
update data for given element
References ug::DimFVGeometry< TWorldDim, TDim >::dim, ug::QuadratureRuleProvider< TDim >::get(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::global_ip(), ug::DimReferenceMapping< TDim, TWorldDim >::jacobian_transposed_inverse(), ug::DimReferenceMapping< TDim, TWorldDim >::local_to_global(), ug::ReferenceMapping< TRefElem, TWorldDim >::local_to_global(), ug::DimFVGeometry< TWorldDim, TDim >::m_lfeID, ug::DimFVGeometry< TWorldDim, TDim >::m_pElem, ug::DimFVGeometry< TWorldDim, TDim >::m_quadOrderSCV, ug::DimFVGeometry< TWorldDim, TDim >::m_quadOrderSCVF, ug::DimFVGeometry< TWorldDim, TDim >::m_roid, ug::DimFVGeometry< TWorldDim, TDim >::m_vGlobSCV_IP, ug::DimFVGeometry< TWorldDim, TDim >::m_vGlobSCVF_IP, ug::DimFVGeometry< TWorldDim, TDim >::m_vSCV, ug::DimFVGeometry< TWorldDim, TDim >::m_vSCVF, ug::MatVecMult(), ug::DimFVGeometry< TWorldDim, TDim >::num_boundary_subsets(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_ip(), ug::DimFVGeometry< TWorldDim, TDim >::num_scv(), ug::DimFVGeometry< TWorldDim, TDim >::num_scvf(), ug::QuadratureRule< TDim >::point(), ug::GridObject::reference_object_id(), ug::DimFVGeometry< TWorldDim, TDim >::scv(), ug::DimFVGeometry< TWorldDim, TDim >::scvf(), ug::QuadratureRule< TDim >::size(), ug::DimReferenceMapping< TDim, TWorldDim >::sqrt_gram_det(), ug::ReferenceMapping< TRefElem, TWorldDim >::sqrt_gram_det(), UG_CATCH_THROW, ug::DimReferenceMapping< TDim, TWorldDim >::update(), ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), ug::DimFVGeometry< TWorldDim, TDim >::update_local(), and ug::VecNormalize().
template<int TWorldDim, int TDim> void ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces (GridObject * pElem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update boundary data for given element
References ug::DimFVGeometry< TWorldDim, TDim >::bf(), ug::CollectEdgesSorted(), ug::CollectFacesSorted(), ug::CollectVertices(), ug::ComputeBFMidID(), ug::DimFVGeometry< TWorldDim, TDim >::dim, ug::QuadratureRuleProvider< TDim >::get(), ug::ISubsetHandler::get_subset_index(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::ISubsetHandler::grid(), ug::DimReferenceMapping< TDim, TWorldDim >::jacobian_transposed_inverse(), ug::LFEID::LAGRANGE, ug::DimFVGeometry< TWorldDim, TDim >::BF::local_ip(), ug::DimReferenceMapping< TDim, TWorldDim >::local_to_global(), ug::ReferenceMapping< TRefElem, TWorldDim >::local_to_global(), ug::DimFVGeometry< TWorldDim, TDim >::m_mapVectorBF, ug::DimFVGeometry< TWorldDim, TDim >::m_numSubElem, ug::DimFVGeometry< TWorldDim, TDim >::m_orderShape, ug::DimFVGeometry< TWorldDim, TDim >::m_quadOrderSCVF, ug::DimFVGeometry< TWorldDim, TDim >::m_roid, ug::DimFVGeometry< TWorldDim, TDim >::m_vSubElem, ug::MatVecMult(), ug::DimFVGeometry< TWorldDim, TDim >::maxMid, ug::DimFVGeometry< TWorldDim, TDim >::BF::nip, ug::DimFVGeometry< TWorldDim, TDim >::BF::nodeId, ug::DimFVGeometry< TWorldDim, TDim >::BF::Normal, ug::DimFVGeometry< TWorldDim, TDim >::BF::nsh, ug::DimFVGeometry< TWorldDim, TDim >::BF::num_corners(), ug::DimFVGeometry< TWorldDim, TDim >::BF::num_ip(), ug::LocalDoFSet::num_sh(), ug::DimFVGeometry< TWorldDim, TDim >::BF::num_sh(), ug::DimFVGeometry< TWorldDim, TDim >::BF::numCo, ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), ug::DimReferenceMapping< TDim, TWorldDim >::sqrt_gram_det(), UG_CATCH_THROW, ug::DimReferenceMapping< TDim, TWorldDim >::update(), ug::DimFVGeometry< TWorldDim, TDim >::BF::vDetJ, ug::VecTwoNorm(), ug::DimFVGeometry< TWorldDim, TDim >::BF::vGlobalIP, ug::DimFVGeometry< TWorldDim, TDim >::BF::vGloPos, ug::DimFVGeometry< TWorldDim, TDim >::BF::vJtInv, ug::DimFVGeometry< TWorldDim, TDim >::BF::vLocalIP, ug::DimFVGeometry< TWorldDim, TDim >::BF::vLocPos, ug::DimFVGeometry< TWorldDim, TDim >::BF::vMidID, ug::DimFVGeometry< TWorldDim, TDim >::BF::Vol, ug::DimFVGeometry< TWorldDim, TDim >::BF::vvGlobalGrad, ug::DimFVGeometry< TWorldDim, TDim >::BF::vvLocalGrad, ug::DimFVGeometry< TWorldDim, TDim >::BF::vvShape, and ug::DimFVGeometry< TWorldDim, TDim >::BF::vWeight.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update().
template<int TWorldDim, int TDim> void ug::DimFVGeometry< TWorldDim, TDim >::update_local (ReferenceObjectID roid, const LFEID & lfeID, size_t orderQuad)
update local data
References ug::ComputeMidPoints(), ug::ComputeSCVFMidID(), ug::ComputeSCVMidID(), ug::DimFVGeometry< TWorldDim, TDim >::dim, ug::QuadratureRuleProvider< TDim >::get(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::ReferenceElement::id(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::local_ip(), ug::ReferenceMapping< TRefElem, TWorldDim >::local_to_global(), ug::DimFVGeometry< TWorldDim, TDim >::m_lfeID, ug::DimFVGeometry< TWorldDim, TDim >::m_nsh, ug::DimFVGeometry< TWorldDim, TDim >::m_numSCV, ug::DimFVGeometry< TWorldDim, TDim >::m_numSCVF, ug::DimFVGeometry< TWorldDim, TDim >::m_numSCVFIP, ug::DimFVGeometry< TWorldDim, TDim >::m_numSCVFPerSubElem, ug::DimFVGeometry< TWorldDim, TDim >::m_numSCVIP, ug::DimFVGeometry< TWorldDim, TDim >::m_numSCVPerSubElem, ug::DimFVGeometry< TWorldDim, TDim >::m_numSubElem, ug::DimFVGeometry< TWorldDim, TDim >::m_orderShape, ug::DimFVGeometry< TWorldDim, TDim >::m_quadOrderSCV, ug::DimFVGeometry< TWorldDim, TDim >::m_quadOrderSCVF, ug::DimFVGeometry< TWorldDim, TDim >::m_roid, ug::DimFVGeometry< TWorldDim, TDim >::m_vGlobSCV_IP, ug::DimFVGeometry< TWorldDim, TDim >::m_vGlobSCVF_IP, ug::DimFVGeometry< TWorldDim, TDim >::m_vLocSCV_IP, ug::DimFVGeometry< TWorldDim, TDim >::m_vLocSCVF_IP, ug::DimFVGeometry< TWorldDim, TDim >::m_vSCV, ug::DimFVGeometry< TWorldDim, TDim >::m_vSCVF, ug::DimFVGeometry< TWorldDim, TDim >::m_vSubElem, ug::DimFVGeometry< TWorldDim, TDim >::maxMid, ug::ReferenceElement::num(), ug::DimFVGeometry< TWorldDim, TDim >::num_scv(), ug::DimFVGeometry< TWorldDim, TDim >::num_scvf(), ug::LocalDoFSet::num_sh(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::numCo, ug::LFEID::order(), ug::QuadratureRule< TDim >::point(), ug::DimFVGeometry< TWorldDim, TDim >::scv(), ug::DimFVGeometry< TWorldDim, TDim >::scvf(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), ug::QuadratureRule< TDim >::size(), UG_CATCH_THROW, ug::DimFVGeometry< TWorldDim, TDim >::update(), ug::VecScaleAppend(), and ug::QuadratureRule< TDim >::weights().
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::DimFVGeometry(), and ug::DimFVGeometry< TWorldDim, TDim >::update().
template<int TWorldDim, int TDim = TWorldDim> void ug::DimFVGeometry< TWorldDim, TDim >::update_local (ReferenceObjectID roid, const LFEID & lfeID) inline
References ug::LFEID::order(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local().
Member Data Documentation
template<int TWorldDim, int TDim = TWorldDim> const int ug::DimFVGeometry< TWorldDim, TDim >::dim = TDim static
dimension of reference element
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> LFEID ug::DimFVGeometry< TWorldDim, TDim >::m_lfeID private
current trial space
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> std::map<int, std::vector<BF> > ug::DimFVGeometry< TWorldDim, TDim >::m_mapVectorBF protected
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces().
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::m_nsh private
number of shape functions
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::m_numSCV private
current number of scv
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::m_numSCVF private
current number of scvf
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::m_numSCVFIP private
number of scvf ip
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::m_numSCVFPerSubElem private
current number of SCVF per SubElement
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::m_numSCVIP private
number of scv ip
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::m_numSCVPerSubElem private
number of SCV per SubElement
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::m_numSubElem private
current number of subelements
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> int ug::DimFVGeometry< TWorldDim, TDim >::m_orderShape private
current order
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> GridObject* ug::DimFVGeometry< TWorldDim, TDim >::m_pElem private
pointer to current element
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update().
template<int TWorldDim, int TDim = TWorldDim> int ug::DimFVGeometry< TWorldDim, TDim >::m_quadOrderSCV private
current quadrature order scv
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> int ug::DimFVGeometry< TWorldDim, TDim >::m_quadOrderSCVF private
quadrature order
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> ReferenceObjectID ug::DimFVGeometry< TWorldDim, TDim >::m_roid private
current reference object id
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> std::vector<BF> ug::DimFVGeometry< TWorldDim, TDim >::m_vEmptyVectorBF protected
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathVector<worldDim> > ug::DimFVGeometry< TWorldDim, TDim >::m_vGlobSCV_IP protected
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathVector<worldDim> > ug::DimFVGeometry< TWorldDim, TDim >::m_vGlobSCVF_IP protected
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathVector<dim> > ug::DimFVGeometry< TWorldDim, TDim >::m_vLocSCV_IP protected
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathVector<dim> > ug::DimFVGeometry< TWorldDim, TDim >::m_vLocSCVF_IP protected
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> std::vector<SCV> ug::DimFVGeometry< TWorldDim, TDim >::m_vSCV private
SubControlVolumes (size: numSCV)
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> std::vector<SCVF> ug::DimFVGeometry< TWorldDim, TDim >::m_vSCVF private
SubControlVolumeFaces (size: numSCVF)
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> std::vector<SubElement> ug::DimFVGeometry< TWorldDim, TDim >::m_vSubElem protected
subelements (size: numSubElem)
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> const int ug::DimFVGeometry< TWorldDim, TDim >::maxMid = traits::maxNumSCVF +1 static protected
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TWorldDim, int TDim = TWorldDim> const bool ug::DimFVGeometry< TWorldDim, TDim >::staticLocalData = false static
flag indicating if local data may change
template<int TWorldDim, int TDim = TWorldDim> const bool ug::DimFVGeometry< TWorldDim, TDim >::usesHangingNodes = false static
Hanging node flag: this Geometry does not support hanging nodes.
template<int TWorldDim, int TDim = TWorldDim> const int ug::DimFVGeometry< TWorldDim, TDim >::worldDim = TWorldDim static
dimension of world
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/fvho_geom.h
ugbase/lib_disc/spatial_disc/disc_util/fvho_geom.cpp