ug4: ug::ComponentGaussSeidel< TDomain, TAlgebra > Class Template Reference
ug::ComponentGaussSeidel< TDomain, TAlgebra > Class Template Reference
ComponentGaussSeidel Preconditioner.
#include <component_gauss_seidel.h>
Classes
struct DimCache
Public Types
typedef GF::element_type Element
typedef GridFunction< TDomain, TAlgebra > GF
World dimension.
typedef GF::side_type Side
typedef TAlgebra algebra_type
typedef TAlgebra::vector_type vector_type
typedef TAlgebra::matrix_type matrix_type
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual SmartPtr< ILinearIterator< vector_type > > clone ()
Clone.
ComponentGaussSeidel (const std::vector< std::string > &vFullRowCmp)
default constructor
ComponentGaussSeidel (number relax, const std::vector< std::string > &vFullRowCmp)
constructor setting relaxation and type
ComponentGaussSeidel (number relax, const std::vector< std::string > &vFullRowCmp, const std::vector< int > &vSmooth, const std::vector< number > &vDamp)
constructor setting relaxation and type
void set_alpha (number alpha)
void set_beta (number beta)
void set_weights (bool b)
virtual bool supports_parallel () const
returns if parallel solving is supported
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
virtual std::string config_string () const
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
returns true if the debug writer is set
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Static Public Attributes
static const int dim = TDomain::dim
Protected Types
typedef IPreconditioner< TAlgebra > base_type
Protected Member Functions
void apply_blocks (const matrix_type &A, GF &c, const vector_type &d, number relax, const DimCache &dimCache, bool bReverse)
void apply_blocks_weighted (const matrix_type &A, GF &c, const vector_type &d, number relax, const DimCache &dimCache, bool bReverse)
void extract_blocks (const matrix_type &A, const GF &c)
virtual const char * name () const
Name of preconditioner.
virtual bool postprocess ()
Postprocess routine.
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
Preprocess routine.
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
step method
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
void enter_debug_writer_section (const char *secDir)
enters a debugging section
void enter_debug_writer_section (std::string secDir)
enters a debugging section
void leave_debug_writer_section ()
leaves a debugging section
void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
void write_debug (const matrix_type &mat, std::string name)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
matrix_type m_A
number m_alpha
number m_beta
bool m_bInit
init flag
bool m_bWeighted
number m_relax
relaxing parameter
std::vector< number > m_vDamp
DimCache m_vDimCache [VOLUME+1]
caching storage
std::vector< std::string > m_vFullRowCmp
components, whose matrix row must be fulfilled completely on gs-block
std::vector< int > m_vGroupObj
smooth order
SmartPtr< GF > m_weight
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Detailed Description
template<typename TDomain, typename TAlgebra>
class ug::ComponentGaussSeidel< TDomain, TAlgebra >
ComponentGaussSeidel Preconditioner.
Member Typedef Documentation
algebra_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra ug::ComponentGaussSeidel< TDomain, TAlgebra >::algebra_type
Algebra types
base_type
template<typename TDomain , typename TAlgebra > typedef IPreconditioner<TAlgebra> ug::ComponentGaussSeidel< TDomain, TAlgebra >::base_type protected
Element
template<typename TDomain , typename TAlgebra > typedef GF::element_type ug::ComponentGaussSeidel< TDomain, TAlgebra >::Element
GF
template<typename TDomain , typename TAlgebra > typedef GridFunction<TDomain, TAlgebra> ug::ComponentGaussSeidel< TDomain, TAlgebra >::GF
World dimension.
matrix_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::matrix_type ug::ComponentGaussSeidel< TDomain, TAlgebra >::matrix_type
Algebra types
Side
template<typename TDomain , typename TAlgebra > typedef GF::side_type ug::ComponentGaussSeidel< TDomain, TAlgebra >::Side
vector_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::vector_type ug::ComponentGaussSeidel< TDomain, TAlgebra >::vector_type
Algebra types
Constructor & Destructor Documentation
ComponentGaussSeidel() [1/3]
template<typename TDomain , typename TAlgebra > ug::ComponentGaussSeidel< TDomain, TAlgebra >::ComponentGaussSeidel (const std::vector< std::string > & vFullRowCmp) inline
default constructor
ComponentGaussSeidel() [2/3]
template<typename TDomain , typename TAlgebra > ug::ComponentGaussSeidel< TDomain, TAlgebra >::ComponentGaussSeidel (number relax, const std::vector< std::string > & vFullRowCmp) inline
constructor setting relaxation and type
ComponentGaussSeidel() [3/3]
template<typename TDomain , typename TAlgebra > ug::ComponentGaussSeidel< TDomain, TAlgebra >::ComponentGaussSeidel (number relax, const std::vector< std::string > & vFullRowCmp, const std::vector< int > & vSmooth, const std::vector< number > & vDamp) inline
constructor setting relaxation and type
Member Function Documentation
apply_blocks()
template<typename TDomain , typename TAlgebra > void ug::ComponentGaussSeidel< TDomain, TAlgebra >::apply_blocks (const matrix_type & A, GF & c, const vector_type & d, number relax, const DimCache & dimCache, bool bReverse) protected
References ug::DoFRef(), ug::MatMult(), ug::MatMultAdd(), s, ug::ComponentGaussSeidel< TDomain, TAlgebra >::DimCache::vBlockInverse, and ug::ComponentGaussSeidel< TDomain, TAlgebra >::DimCache::vvDoFIndex.
apply_blocks_weighted()
template<typename TDomain , typename TAlgebra > void ug::ComponentGaussSeidel< TDomain, TAlgebra >::apply_blocks_weighted (const matrix_type & A, GF & c, const vector_type & d, number relax, const DimCache & dimCache, bool bReverse) protected
References ug::DoFRef(), ug::MatMult(), ug::MatMultAdd(), s, UG_ASSERT, ug::ComponentGaussSeidel< TDomain, TAlgebra >::DimCache::vBlockInverse, and ug::ComponentGaussSeidel< TDomain, TAlgebra >::DimCache::vvDoFIndex.
clone()
template<typename TDomain , typename TAlgebra > SmartPtr< ILinearIterator< typename TAlgebra::vector_type > > ug::ComponentGaussSeidel< TDomain, TAlgebra >::clone virtual
Clone.
Implements ug::ILinearIterator< TAlgebra::vector_type >.
extract_blocks()
template<typename TDomain , typename TAlgebra > void ug::ComponentGaussSeidel< TDomain, TAlgebra >::extract_blocks (const matrix_type & A, const GF & c) protected
Create 'm_vGroupObj' contain all dimensions containg objects from 'vFullRowCmp'
References ug::GridFunction< TDomain, TAlgebra >::approx_space(), ug::GridFunction< TDomain, TAlgebra >::clone_without_values(), ug::DoFRef(), ug::EDGE, ug::FACE, ug::find(), ug::Invert(), UG_THROW, ug::VERTEX, and ug::VOLUME.
name()
template<typename TDomain , typename TAlgebra > virtual const char* ug::ComponentGaussSeidel< TDomain, TAlgebra >::name () const inline protected virtual
Name of preconditioner.
Implements ug::IPreconditioner< TAlgebra >.
postprocess()
template<typename TDomain , typename TAlgebra > virtual bool ug::ComponentGaussSeidel< TDomain, TAlgebra >::postprocess () inline protected virtual
Postprocess routine.
Implements ug::IPreconditioner< TAlgebra >.
preprocess()
template<typename TDomain , typename TAlgebra > bool ug::ComponentGaussSeidel< TDomain, TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) protected virtual
Preprocess routine.
Implements ug::IPreconditioner< TAlgebra >.
References pcl::CollectUniqueElements(), ug::MakeConsistent(), pcl::NumProcs(), and ug::SetDirichletRow().
set_alpha()
template<typename TDomain , typename TAlgebra > void ug::ComponentGaussSeidel< TDomain, TAlgebra >::set_alpha (number alpha) inline
References alpha, and ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_alpha.
set_beta()
template<typename TDomain , typename TAlgebra > void ug::ComponentGaussSeidel< TDomain, TAlgebra >::set_beta (number beta) inline
References ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_beta.
set_weights()
template<typename TDomain , typename TAlgebra > void ug::ComponentGaussSeidel< TDomain, TAlgebra >::set_weights (bool b) inline
References ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_bWeighted.
step()
template<typename TDomain , typename TAlgebra > bool ug::ComponentGaussSeidel< TDomain, TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) protected virtual
step method
Implements ug::IPreconditioner< TAlgebra >.
References SmartPtr< T, FreePolicy >::get(), pcl::NumProcs(), ug::PST_UNIQUE, and UG_THROW.
supports_parallel()
template<typename TDomain , typename TAlgebra > virtual bool ug::ComponentGaussSeidel< TDomain, TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearIterator< TAlgebra::vector_type >.
Member Data Documentation
dim
template<typename TDomain , typename TAlgebra > const int ug::ComponentGaussSeidel< TDomain, TAlgebra >::dim = TDomain::dim static
m_A
template<typename TDomain , typename TAlgebra > matrix_type ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_A protected
m_alpha
template<typename TDomain , typename TAlgebra > number ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_alpha protected
Referenced by ug::ComponentGaussSeidel< TDomain, TAlgebra >::set_alpha().
m_beta
template<typename TDomain , typename TAlgebra > number ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_beta protected
Referenced by ug::ComponentGaussSeidel< TDomain, TAlgebra >::set_beta().
m_bInit
template<typename TDomain , typename TAlgebra > bool ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_bInit protected
init flag
m_bWeighted
template<typename TDomain , typename TAlgebra > bool ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_bWeighted protected
Referenced by ug::ComponentGaussSeidel< TDomain, TAlgebra >::set_weights().
m_relax
template<typename TDomain , typename TAlgebra > number ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_relax protected
relaxing parameter
m_vDamp
template<typename TDomain , typename TAlgebra > std::vector<number> ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_vDamp protected
m_vDimCache
template<typename TDomain , typename TAlgebra > DimCache ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_vDimCache[VOLUME+1] protected
caching storage
m_vFullRowCmp
template<typename TDomain , typename TAlgebra > std::vector<std::string> ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_vFullRowCmp protected
components, whose matrix row must be fulfilled completely on gs-block
m_vGroupObj
template<typename TDomain , typename TAlgebra > std::vector<int> ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_vGroupObj protected
smooth order
m_weight
template<typename TDomain , typename TAlgebra > SmartPtr<GF> ug::ComponentGaussSeidel< TDomain, TAlgebra >::m_weight protected
The documentation for this class was generated from the following file:
ugbase/lib_disc/operator/linear_operator/element_gauss_seidel/component_gauss_seidel.h