ug4: ug::Stopwatch Class Reference
ug::Stopwatch Class Reference
ugbase » Common
Stopwatch class for quickly taking times.
#include <stopwatch.h>
Public Member Functions
double ms ()
Returns milliseconds since call of start.
void start ()
Starts the Stopwatch.
void stop ()
Stops the Stopwatch.
Stopwatch ()
Default constructor for the Stopwatch.
Private Attributes
double beg
Time point of the start of Stopwatch.
bool bRunning
Flag indicating state of Stopwatch.
double end
Time point of the end of Stopwatch.
Friends
std::ostream & operator<< (std::ostream &out, Stopwatch &s)
Prints number of milliseconds since call of start() to ostream.
Detailed Description
Stopwatch class for quickly taking times.
Depending on CXX11 flag, two different versions are compiled. If CXX11=ON, std::chrono from C++11's STL is used providing high resolution (microseconds) time measuring. Otherwise std::ctime is used providing millisecond resolution.
Note
If CXX11=OFF timings shorter than 100ms seem to be rather inaccurate.
Constructor & Destructor Documentation
Stopwatch()
ug::Stopwatch::Stopwatch () inline
Default constructor for the Stopwatch.
References ug::get_clock_s().
Member Function Documentation
ms()
double ug::Stopwatch::ms () inline
Returns milliseconds since call of start.
Returns the amount of milliseconds passed between calls of Stopwatch::start() and Stopwatch::stop() or this function call.
Note
If compiled with CXX11=ON returned milliseconds have microsecond resolution.
Returns
milliseconds
References ug::get_clock_s().
Referenced by ug::AlgebraicConvCheck< TVector >::post(), and ug::CompositeConvCheck< TVector, TDomain >::post().
start()
void ug::Stopwatch::start () inline
Starts the Stopwatch.
References ug::get_clock_s().
Referenced by ug::AlgebraicConvCheck< TVector >::start(), and ug::CompositeConvCheck< TVector, TDomain >::start().
stop()
void ug::Stopwatch::stop () inline
Stops the Stopwatch.
References ug::get_clock_s().
Referenced by ug::AlgebraicConvCheck< TVector >::post(), and ug::CompositeConvCheck< TVector, TDomain >::post().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, Stopwatch & s) friend
Prints number of milliseconds since call of start() to ostream.
Pretty prints the amount of milliseconds passed between calls of Stopwatch::start() and Stopwatch::stop() or this function call to the specified std::ostream.
Parameters
[out] out std::ostream to print number of milliseconds to
[in] sw a Stopwatch instance (usualy 'this')
Member Data Documentation
beg
double ug::Stopwatch::beg private
Time point of the start of Stopwatch.
bRunning
bool ug::Stopwatch::bRunning private
Flag indicating state of Stopwatch.
end
double ug::Stopwatch::end private
Time point of the end of Stopwatch.
The documentation for this class was generated from the following file:
ugbase/common/stopwatch.h