ug4: ug::DimFVGeometry< TWorldDim, TDim >::SCVF Class Reference
ug::DimFVGeometry< TWorldDim, TDim >::SCVF Class Reference
Sub-Control Volume Face structure.
#include <fvho_geom.h>
Public Member Functions
number detJ (size_t ip) const
Determinant of Jacobian in integration point.
size_t from () const
index of SubControlVolume on one side of the scvf
const MathVector< worldDim > & global_corner (size_t co) const
return glbal corner number i
const MathVector< worldDim > & global_grad (size_t ip, size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector (size_t ip) const
vector of gloabl gradients in ip point
const MathVector< worldDim > & global_ip (size_t ip) const
global integration point of scvf
const MathMatrix< worldDim, dim > & JTInv (size_t ip) const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t ip, size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector (size_t ip) const
vector of local gradients in ip point
const MathVector< dim > & local_ip (size_t ip) const
local integration point of scvf
const MathVector< worldDim > & normal () const
normal on scvf (points direction "from"->"to"), normalized
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points on scvf
size_t num_sh () const
number of shape functions
SCVF ()
number shape (size_t ip, size_t sh) const
value of shape function i in integration point
const number * shape_vector (size_t ip) const
vector of shape functions in ip point
size_t to () const
index of SubControlVolume on one side of the scvf
number weight (size_t ip) const
integration weight
Static Public Attributes
static const size_t numCo = traits::NumCornersOfSCVF
Number of corners of scvf.
Private Attributes
size_t From
size_t nip
MathVector< worldDim > Normal
size_t nsh
size_t To
std::vector< number > vDetJ
std::vector< number > vDetJMap
std::vector< MathVector< worldDim > > vGlobalIP
MathVector< worldDim > vGloPos [numCo]
std::vector< MathMatrix< worldDim, dim > > vJtInv
std::vector< MathVector< dim > > vLocalIP
MathVector< dim > vLocPos [numCo]
MidID vMidID [numCo]
std::vector< std::vector< MathVector< worldDim > > > vvGlobalGrad
std::vector< std::vector< MathVector< dim > > > vvLocalGrad
std::vector< std::vector< number > > vvShape
const number * vWeight
Friends
class DimFVGeometry< worldDim, dim >
Detailed Description
template<int TWorldDim, int TDim = TWorldDim>
class ug::DimFVGeometry< TWorldDim, TDim >::SCVF
Sub-Control Volume Face structure.
Constructor & Destructor Documentation
SCVF()
template<int TWorldDim, int TDim = TWorldDim> ug::DimFVGeometry< TWorldDim, TDim >::SCVF::SCVF () inline
Member Function Documentation
detJ()
template<int TWorldDim, int TDim = TWorldDim> number ug::DimFVGeometry< TWorldDim, TDim >::SCVF::detJ (size_t ip) const inline
Determinant of Jacobian in integration point.
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vDetJ.
from()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCVF::from () const inline
index of SubControlVolume on one side of the scvf
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::From.
global_corner()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>& ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_corner (size_t co) const inline
return glbal corner number i
global_grad()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>& ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad (size_t ip, size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_sh(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vvGlobalGrad.
global_grad_vector()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>* ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad_vector (size_t ip) const inline
vector of gloabl gradients in ip point
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vvGlobalGrad.
global_ip()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>& ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_ip (size_t ip) const inline
global integration point of scvf
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vGlobalIP.
JTInv()
template<int TWorldDim, int TDim = TWorldDim> const MathMatrix<worldDim,dim>& ug::DimFVGeometry< TWorldDim, TDim >::SCVF::JTInv (size_t ip) const inline
Transposed Inverse of Jacobian in integration point.
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vJtInv.
local_corner()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>& ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_corner (size_t co) const inline
return local corner number i
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_corners(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vLocPos.
local_grad()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>& ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad (size_t ip, size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_sh(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vvLocalGrad.
local_grad_vector()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>* ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad_vector (size_t ip) const inline
vector of local gradients in ip point
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vvLocalGrad.
local_ip()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<dim>& ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_ip (size_t ip) const inline
local integration point of scvf
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vLocalIP.
normal()
template<int TWorldDim, int TDim = TWorldDim> const MathVector<worldDim>& ug::DimFVGeometry< TWorldDim, TDim >::SCVF::normal () const inline
normal on scvf (points direction "from"->"to"), normalized
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::Normal.
num_corners()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_corners () const inline
number of corners, that bound the scvf
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::numCo.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_corner().
num_ip()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip () const inline
number of integration points on scvf
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::nip.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::detJ(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::JTInv(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad_vector(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_ip(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::shape(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::shape_vector(), and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::weight().
num_sh()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_sh () const inline
number of shape functions
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::nsh.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad(), and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad().
shape()
template<int TWorldDim, int TDim = TWorldDim> number ug::DimFVGeometry< TWorldDim, TDim >::SCVF::shape (size_t ip, size_t sh) const inline
value of shape function i in integration point
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vvShape.
shape_vector()
template<int TWorldDim, int TDim = TWorldDim> const number* ug::DimFVGeometry< TWorldDim, TDim >::SCVF::shape_vector (size_t ip) const inline
vector of shape functions in ip point
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), UG_ASSERT, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vvShape.
to()
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCVF::to () const inline
index of SubControlVolume on one side of the scvf
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::To.
weight()
template<int TWorldDim, int TDim = TWorldDim> number ug::DimFVGeometry< TWorldDim, TDim >::SCVF::weight (size_t ip) const inline
integration weight
References ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip(), UG_ASSERT, ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vDetJMap, and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vWeight.
Friends And Related Function Documentation
DimFVGeometry< worldDim, dim >
template<int TWorldDim, int TDim = TWorldDim> friend class DimFVGeometry< worldDim, dim > friend
Member Data Documentation
From
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCVF::From private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::from().
nip
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCVF::nip private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_ip().
Normal
template<int TWorldDim, int TDim = TWorldDim> MathVector<worldDim> ug::DimFVGeometry< TWorldDim, TDim >::SCVF::Normal private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::normal().
nsh
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCVF::nsh private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_sh().
numCo
template<int TWorldDim, int TDim = TWorldDim> const size_t ug::DimFVGeometry< TWorldDim, TDim >::SCVF::numCo = traits::NumCornersOfSCVF static
Number of corners of scvf.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_corners().
To
template<int TWorldDim, int TDim = TWorldDim> size_t ug::DimFVGeometry< TWorldDim, TDim >::SCVF::To private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::to().
vDetJ
template<int TWorldDim, int TDim = TWorldDim> std::vector<number> ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vDetJ private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::detJ().
vDetJMap
template<int TWorldDim, int TDim = TWorldDim> std::vector<number> ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vDetJMap private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::weight().
vGlobalIP
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathVector<worldDim> > ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vGlobalIP private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_ip().
vGloPos
template<int TWorldDim, int TDim = TWorldDim> MathVector<worldDim> ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vGloPos[numCo] private
vJtInv
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathMatrix<worldDim,dim> > ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vJtInv private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::JTInv().
vLocalIP
template<int TWorldDim, int TDim = TWorldDim> std::vector<MathVector<dim> > ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vLocalIP private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_ip().
vLocPos
template<int TWorldDim, int TDim = TWorldDim> MathVector<dim> ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vLocPos[numCo] private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_corner().
vMidID
template<int TWorldDim, int TDim = TWorldDim> MidID ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vMidID[numCo] private
vvGlobalGrad
template<int TWorldDim, int TDim = TWorldDim> std::vector<std::vector<MathVector<worldDim> > > ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vvGlobalGrad private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad(), and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::global_grad_vector().
vvLocalGrad
template<int TWorldDim, int TDim = TWorldDim> std::vector<std::vector<MathVector<dim> > > ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vvLocalGrad private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad(), and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::local_grad_vector().
vvShape
template<int TWorldDim, int TDim = TWorldDim> std::vector<std::vector<number> > ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vvShape private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::shape(), and ug::DimFVGeometry< TWorldDim, TDim >::SCVF::shape_vector().
vWeight
template<int TWorldDim, int TDim = TWorldDim> const number* ug::DimFVGeometry< TWorldDim, TDim >::SCVF::vWeight private
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::SCVF::weight().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fvho_geom.h