ug4: ug::Vertex Class Reference
ug::Vertex Class Reference
lib_grid » geometric objects
Base-class for all vertex-types.
#include <grid_base_objects.h>
Public Types
typedef Vertex grid_base_object
typedef Edge higher_dim_base_object
typedef void lower_dim_base_object
typedef Vertex side
typedef Edge sideof
Public Member Functions
virtual int base_object_id () const
virtual int container_section () const
uint32 get_hash_value () const
returns a value that can be used for hashing.
uint num_sides () const
virtual ReferenceObjectID reference_object_id () const
virtual ~Vertex ()
Public Member Functions inherited from ug::GridObject
virtual GridObject * create_empty_instance () const
create an instance of the derived type
uint grid_data_index () const
Returns the grid attachment data index of a geometric object.
virtual bool is_constrained () const
returns true if the object is constrained by other objects.
virtual bool is_constraining () const
returns the id of the reference-object.
virtual ~GridObject ()
Static Public Member Functions
static bool type_match (GridObject *pObj)
Static Public Attributes
static const int BASE_OBJECT_ID = VERTEX
static const bool CAN_BE_SIDE = true
static const int dim = 0
reference dimension
static const bool HAS_SIDES = false
static const size_t NUM_VERTICES = 1
Protected Attributes
uint32 m_hashValue
Protected Attributes inherited from ug::GridObject
uint m_gridDataIndex
Friends
class Grid
Additional Inherited Members
Protected Member Functions inherited from ug::GridObject
void set_grid_data_index (uint index)
ATTENTION: Use this method with extreme care!
Detailed Description
Base-class for all vertex-types.
Vertices are required in any grid. They are the geometric objects of lowest dimension. All other geometric objects of higher dimension reference vertices.
Member Typedef Documentation
typedef Vertex ug::Vertex::grid_base_object
typedef Edge ug::Vertex::higher_dim_base_object
typedef void ug::Vertex::lower_dim_base_object
typedef Vertex ug::Vertex::side
The side type is obviously wrong. It should be void. However, void would cause problems with template instantiations.
typedef Edge ug::Vertex::sideof
Constructor & Destructor Documentation
virtual ug::Vertex::~Vertex () inline virtual
Member Function Documentation
virtual int ug::Vertex::base_object_id () const inline virtual
Implements ug::GridObject.
References ug::VERTEX.
virtual int ug::Vertex::container_section () const inline virtual
Implements ug::GridObject.
Reimplemented in ug::ConstrainedVertex, and ug::RegularVertex.
Referenced by ug::Selector::add_to_list(), ug::MGSelector::add_to_list(), ug::Grid::erase(), ug::Selector::erase_from_list(), ug::MGSelector::erase_from_list(), ug::Grid::register_and_replace_element(), ug::Grid::register_vertex(), ug::Grid::replace_vertex(), and ug::Grid::unregister_vertex().
uint32 ug::Vertex::get_hash_value () const inline
returns a value that can be used for hashing.
this value is unique per grid. It is only set correctly if the vertex has been created by the grid or has been properly registered at it.
Referenced by ug::hash_key(), and ug::HashKey().
uint ug::Vertex::num_sides () const inline
virtual ReferenceObjectID ug::Vertex::reference_object_id () const inline virtual
A reference object represents a class of geometric objects. Tetrahedrons, Triangles etc are such classes. Reference ids should be defined in the file in which concrete geometric objects are defined.
Implements ug::GridObject.
Reimplemented in ug::ConstrainedVertex, and ug::RegularVertex.
References ug::ROID_UNKNOWN.
static bool ug::Vertex::type_match (GridObject * pObj) inline static
Friends And Related Function Documentation
friend class Grid friend
Member Data Documentation
const int ug::Vertex::BASE_OBJECT_ID = VERTEX static
const bool ug::Vertex::CAN_BE_SIDE = true static
const int ug::Vertex::dim = 0 static
reference dimension
const bool ug::Vertex::HAS_SIDES = false static
uint32 ug::Vertex::m_hashValue protected
Referenced by ug::Grid::assign_hash_value().
const size_t ug::Vertex::NUM_VERTICES = 1 static
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/grid_base_objects.h