ug4: ug::DimLocalDoFSet< TDim > Class Template Reference
ug::DimLocalDoFSet< TDim > Class Template Reference abstract
#include <local_dof_set.h>
Public Member Functions
DimLocalDoFSet ()
constructor
virtual bool exact_position_available () const =0
returns if the local dof position are exact
bool operator!= (const DimLocalDoFSet< TDim > &v) const
inequality check
bool operator== (const DimLocalDoFSet< TDim > &v) const
equality check
virtual bool position (size_t i, MathVector< TDim > &pos) const =0
local position of DoF i
Public Member Functions inherited from ug::LocalDoFSet
int dim () const
returns the reference dimension
virtual const LocalDoF & local_dof (size_t dof) const =0
returns the DoFs storage
size_t num_dof (int d, size_t id) const
returns the number of DoFs on a sub-geometric object of dim and id
virtual size_t num_dof (ReferenceObjectID roid) const =0
returns the number of DoFs on a sub-geometric object type
bool operator!= (const LocalDoFSet &v) const
inequality check
bool operator== (const LocalDoFSet &v) const
equality check
virtual ReferenceObjectID roid () const =0
returns the Reference object id of the corresponding grid object
virtual ~LocalDoFSet ()
virtual destructor
size_t num_dof () const
virtual size_t num_sh () const
Detailed Description
template<int TDim>
class ug::DimLocalDoFSet< TDim >
Local DoF Set also providing to local position of the dofs (iff available)
Constructor & Destructor Documentation
DimLocalDoFSet()
template<int TDim> ug::DimLocalDoFSet< TDim >::DimLocalDoFSet
constructor
Member Function Documentation
exact_position_available()
template<int TDim> virtual bool ug::DimLocalDoFSet< TDim >::exact_position_available () const pure virtual
returns if the local dof position are exact
Implemented in ug::SubLocalDoFSet< TDim >, and ug::LocalShapeFunctionSetWrapper< TImpl >.
Referenced by ug::DimLocalDoFSet< TDim >::operator==().
operator!=()
template<int TDim> bool ug::DimLocalDoFSet< TDim >::operator!= (const DimLocalDoFSet< TDim > & v) const inline
inequality check
operator==()
template<int TDim> bool ug::DimLocalDoFSet< TDim >::operator== (const DimLocalDoFSet< TDim > & v) const
equality check
References ug::DimLocalDoFSet< TDim >::exact_position_available(), ug::DimLocalDoFSet< TDim >::position(), and ug::VecDistance().
position()
template<int TDim> virtual bool ug::DimLocalDoFSet< TDim >::position (size_t i, MathVector< TDim > & pos) const pure virtual
local position of DoF i
This function returns the local position of a DoF if possible.
Parameters
[in] i number of DoF
[out] pos Position of DoF
Return values
true if position exists
false if no meaningful position available
Implemented in ug::SubLocalDoFSet< TDim >.
Referenced by ug::DoFPositionElem(), ug::InnerDoFPositionElem(), ug::InterpolateOnDiffElements(), ug::MaxErrorOnElements(), ug::operator<<(), and ug::DimLocalDoFSet< TDim >::operator==().
The documentation for this class was generated from the following files:
ugbase/lib_disc/local_finite_element/local_dof_set.h
ugbase/lib_disc/local_finite_element/local_dof_set.cpp