ug4: ug::ParallelHangingNodeRefiner_MultiGrid Class Reference
ug::ParallelHangingNodeRefiner_MultiGrid Class Reference
Lib_grid_parallelization_refinement
#include <parallel_hanging_node_refiner_multi_grid.h>
Public Types
typedef HangingNodeRefiner_MultiGrid BaseClass
Public Types inherited from ug::HangingNodeRefiner_MultiGrid
typedef HangingNodeRefinerBase< MGSelector > BaseClass
enum HNodeCoarsenMarks {
HNCM_FIRST = HNRM_MAX + 1, HNCM_NO_NBRS, HNCM_NONE, HNCM_PARTIAL,
HNCM_REPLACE, HNCM_ALL, HNCM_INVALID, HNCM_UNKNOWN
}
Public Types inherited from ug::HangingNodeRefinerBase< MGSelector >
enum HNodeRefMarks
typedef MGSelector selector_t
Public Member Functions
ParallelHangingNodeRefiner_MultiGrid (SPRefinementProjector projector=SPNULL)
ParallelHangingNodeRefiner_MultiGrid (DistributedGridManager &distGridMgr, SPRefinementProjector projector=SPNULL)
void set_distributed_grid_manager (DistributedGridManager &distGridMgr)
void set_involved_processes (pcl::ProcessCommunicator com)
virtual ~ParallelHangingNodeRefiner_MultiGrid ()
Public Member Functions inherited from ug::HangingNodeRefiner_MultiGrid
virtual bool adaptivity_supported () const
returns whether the refiner is able to perform adaptive refinement
virtual void assign_grid (MultiGrid &mg)
virtual bool coarsening_supported () const
returns true, if the refiner supports coarsening.
virtual Grid * get_associated_grid ()
DEPRECIATED! Use grid(). Has to return the associated grid. Pure virtual.
virtual Grid * grid ()
Returns the grid associated with the refiner.
virtual void grid_to_be_destroyed (Grid *grid)
HangingNodeRefiner_MultiGrid (SPRefinementProjector projector=SPNULL)
HangingNodeRefiner_MultiGrid (MultiGrid &mg, SPRefinementProjector projector=SPNULL)
virtual MultiGrid * multi_grid ()
virtual ~HangingNodeRefiner_MultiGrid ()
Public Member Functions inherited from ug::HangingNodeRefinerBase< MGSelector >
void add_ref_mark_adjuster (SPIRefMarkAdjuster adjuster)
Add a refmark adjuster, which will be called while marks are adjusted during refinement / coarsening.
virtual void clear_marks ()
clears all marks. Default implementation is empty
HangingNodeRefinerBase (SPRefinementProjector projector=SPNULL)
virtual void mark_neighborhood (size_t numIterations, RefinementMark refMark, bool sideNbrsOnly)
Marks the neighborhood of the current selection.
bool marked_adaptive (TElem *elem) const
bool marked_coarsen (TElem *elem) const
bool marked_refine (Edge *elem) const
bool marked_refine (TElem *elem) const
bool marked_regular (TElem *elem) const
virtual bool save_marks_to_file (const char *filename)
Writes the associated grid and marks to a file. Pure virtual.
virtual ~HangingNodeRefinerBase ()
void enable_node_dependency_order_1 (bool bEnable)
enables or disables node-dependency-order-1.
bool node_dependency_order_1_enabled ()
enables or disables node-dependency-order-1.
virtual bool mark (Vertex *v, RefinementMark refMark=RM_REFINE)
Marks a element for refinement.
virtual bool mark (Edge *e, RefinementMark refMark=RM_REFINE)
Marks a element for refinement.
virtual bool mark (Face *f, RefinementMark refMark=RM_REFINE)
Marks a element for refinement.
virtual bool mark (Volume *v, RefinementMark refMark=RM_REFINE)
Marks a element for refinement.
virtual RefinementMark get_mark (Vertex *v) const
Returns the mark of a given element.
virtual RefinementMark get_mark (Edge *e) const
Returns the mark of a given element.
virtual RefinementMark get_mark (Face *f) const
Returns the mark of a given element.
virtual RefinementMark get_mark (Volume *v) const
Returns the mark of a given element.
Public Member Functions inherited from ug::IRefiner
bool coarsen ()
Performs coarsening on the elements marked RM_COARSEN.
bool debugging_enabled () const
void enable_debugging (bool enable)
int get_local_edge_mark (Face *f, Edge *e) const
returns the local mark of the specified edge of the given face
int get_local_edge_mark (Volume *vol, Edge *e) const
returns the local mark of the specified edge of the given volume
int get_local_face_mark (Volume *vol, Face *f) const
returns the local mark of the specified face of the given volume
virtual RefinementMark get_mark (GridObject *o) const
returns the mark of the specified geometric object
IRefiner (SPRefinementProjector projector=SPNULL)
virtual bool local_marks_supported () const
returns true, if the refiner supports local marks.
virtual bool mark (GridObject *o, RefinementMark refMark=RM_REFINE)
marks the specified geometric object
template<class TIterator >
void mark (const TIterator &iterBegin, const TIterator &iterEnd, RefinementMark refMark=RM_REFINE)
marks all elements between iterBegin and iterEnd.
void mark_neighborhood (size_t numIterations)
marks the neighborhood of currently marked elements.
template<class TElem >
bool marked_closure (TElem *elem) const
template<class TElem >
bool marked_full (TElem *elem) const
template<class TElem >
bool marked_local (TElem *elem) const
size_t num_marked_edges (std::vector< int > &numMarkedEdgesOut)
returns the number of (globally) marked edges on all levels of the hierarchy
size_t num_marked_edges ()
returns the number of (globally) marked edges on all levels of the hierarchy
size_t num_marked_elements (std::vector< int > &numMarkedElemsOut)
returns the number of (globally) marked grid-objects of highest dimension
size_t num_marked_elements ()
returns the number of (globally) marked grid-objects of highest dimension
size_t num_marked_faces (std::vector< int > &numMarkedFacesOut)
returns the number of (globally) marked faces on all levels of the hierarchy
size_t num_marked_faces ()
returns the number of (globally) marked faces on all levels of the hierarchy
size_t num_marked_volumes (std::vector< int > &numMarkedVolsOut)
returns the number of (globally) marked volumes on all levels of the hierarchy
size_t num_marked_volumes ()
returns the number of (globally) marked volumes on all levels of the hierarchy
SPRefinementProjector projector ()
void refine ()
Performs refinement on the marked elements.
void set_adjusted_marks_debug_filename (const char *filename)
sets a filename to which adjusted marks are saved during refinement / coarsening
void set_projector (SPRefinementProjector projector)
virtual ~IRefiner ()
virtual void mark_local (Face *e, int mark)
Marks a face or volume for local refinement.
virtual void mark_local (Volume *e, int mark)
Marks a face or volume for local refinement.
virtual int get_local_mark (Face *e) const
returns the local mark of the specified face or volume.
virtual int get_local_mark (Volume *e) const
returns the local mark of the specified face or volume.
void adaption_begins ()
notifies all listeners of the associated message-hub, that adaption begins / ends.
void adaption_ends ()
notifies all listeners of the associated message-hub, that adaption begins / ends.
Public Member Functions inherited from ug::GridObserver
virtual void elements_to_be_cleared (Grid *grid)
virtual ~GridObserver ()
virtual void vertex_created (Grid *grid, Vertex *vrt, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void edge_created (Grid *grid, Edge *e, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void face_created (Grid *grid, Face *f, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void volume_created (Grid *grid, Volume *vol, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void vertex_to_be_erased (Grid *grid, Vertex *vrt, Vertex *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void edge_to_be_erased (Grid *grid, Edge *e, Edge *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void face_to_be_erased (Grid *grid, Face *f, Face *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void volume_to_be_erased (Grid *grid, Volume *vol, Volume *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void vertices_to_be_merged (Grid *grid, Vertex *target, Vertex *elem1, Vertex *elem2)
Notified when two elements of the same type are going to be merged.
virtual void edges_to_be_merged (Grid *grid, Edge *target, Edge *elem1, Edge *elem2)
Notified when two elements of the same type are going to be merged.
virtual void faces_to_be_merged (Grid *grid, Face *target, Face *elem1, Face *elem2)
Notified when two elements of the same type are going to be merged.
virtual void volumes_to_be_merged (Grid *grid, Volume *target, Volume *elem1, Volume *elem2)
Notified when two elements of the same type are going to be merged.
Protected Member Functions
virtual void assign_hnode_marks ()
distributes hnode marks
virtual void broadcast_marks_horizontally (bool vertices, bool edges, bool faces, bool allowDeselection=false)
virtual void broadcast_marks_vertically (bool vertices, bool edges, bool faces, bool volumes, bool allowDeselection=false)
virtual bool contains_edges ()
allows to check whether a distributed grid contains edges
virtual bool contains_faces ()
allows to check whether a distributed grid contains faces
virtual bool contains_volumes ()
allows to check whether a distributed grid contains volumes
virtual bool continue_collect_objects_for_refine (bool continueRequired)
virtual void copy_marks_to_vmasters (bool vertices, bool edges, bool faces, bool volumes)
virtual void copy_marks_to_vslaves (bool vertices, bool edges, bool faces, bool volumes)
virtual bool one_proc_true (bool localProcTrue)
virtual void post_coarsen ()
virtual void post_refine ()
virtual void pre_coarsen ()
virtual void pre_refine ()
creates required vertices in higher levels.
virtual bool refinement_is_allowed (Vertex *elem)
a callback that allows to deny refinement of special vertices
virtual bool refinement_is_allowed (Edge *elem)
a callback that allows to deny refinement of special edges
virtual bool refinement_is_allowed (Face *elem)
a callback that allows to deny refinement of special faces
virtual bool refinement_is_allowed (Volume *elem)
a callback that allows to deny refinement of special volumes
template<class TElem , class TIntfcCom >
void copy_marks_to_vmasters (TIntfcCom &com)
copies the current marks in the ref-mark-selector from v-slaves to v-masters
template<class TElem , class TIntfcCom >
void copy_marks_to_vslaves (TIntfcCom &com)
copies the current marks in the ref-mark-selector from v-slaves to v-masters
Protected Member Functions inherited from ug::HangingNodeRefiner_MultiGrid
template<class TElem >
void collect_child_corners (std::vector< Vertex *> &cornersOut, TElem *elem)
collects corner vertices and fills them into the associated vector
virtual void collect_objects_for_coarsen (bool scheduleCoarseningBeginsMessage=false)
adjusts the selection marks to those specified in HNodeCoarsenMarks.
void debug_save (ISelector &sel, const char *filename)
temporary method, which will be removed when debugging is done.
virtual Vertex * get_center_vertex (Edge *e)
Returns the vertex associated with the edge.
virtual Vertex * get_center_vertex (Face *f)
Returns the vertex associated with the face.
virtual void num_marked_edges_local (std::vector< int > &numMarkedEdgesOut)
returns the number of (globally) marked edges on this level of the hierarchy
template<class TElem >
void num_marked_elems (std::vector< int > &numMarkedElemsOut)
virtual void num_marked_faces_local (std::vector< int > &numMarkedFacesOut)
returns the number of (globally) marked faces on this level of the hierarchy
virtual void num_marked_volumes_local (std::vector< int > &numMarkedVolsOut)
returns the number of (globally) marked volumes on this level of the hierarchy
virtual bool perform_coarsening ()
performs coarsening on the elements marked with RM_COARSEN.
virtual void restrict_selection_to_coarsen_families ()
Deselects all elements which have an unselected sibling.
template<class TElem >
void restrict_selection_to_coarsen_families ()
Only complete families (all siblings are selected) may be coarsened.
virtual void restrict_selection_to_surface_coarsen_elements ()
Makes sure that only surface elements are marked and that only coarsen marks are used.
template<class TElem >
void restrict_selection_to_surface_coarsen_elements ()
Deselects all non-surface elements and all elements not marked with RM_COARSEN.
void save_coarsen_marks_to_file (ISelector &sel, const char *filename)
virtual void set_center_vertex (Edge *e, Vertex *v)
Associates a vertex with the edge.
virtual void set_center_vertex (Face *f, Vertex *v)
Associates a vertex with the face.
void set_grid (MultiGrid *mg)
performs registration and deregistration at a grid.
virtual void process_constraining_edge (ConstrainingEdge *cge)
calls base implementation and replaces cge with a normal edge.
virtual void refine_edge_with_normal_vertex (Edge *e, Vertex **newCornerVrts=NULL)
calls base implementation and replaces cge with a normal edge.
virtual void refine_edge_with_hanging_vertex (Edge *e, Vertex **newCornerVrts=NULL)
calls base implementation and replaces cge with a normal edge.
virtual void refine_face_with_normal_vertex (Face *f, Vertex **newCornerVrts=NULL)
calls base implementation and replaces cge with a normal edge.
virtual void refine_face_with_hanging_vertex (Face *f, Vertex **newCornerVrts=NULL)
calls base implementation and replaces cge with a normal edge.
virtual void refine_volume_with_normal_vertex (Volume *v, Vertex **newVolumeVrts=NULL)
calls base implementation and replaces cge with a normal edge.
Protected Member Functions inherited from ug::HangingNodeRefinerBase< MGSelector >
void add_hmark (TElem *elem, HNodeRefMarks mark)
bool adjusting_ref_marks () const
virtual void collect_objects_for_refine ()
marks unmarked elements that have to be refined due to marked neighbors.
MGSelector & get_refmark_selector ()
returns the selector which is internally used to mark elements.
bool is_marked (Vertex *v)
bool is_marked (Edge *e)
bool is_marked (Face *f)
bool is_marked (Volume *v)
bool marked_to_constrained (TElem *elem) const
bool marked_to_constraining (TElem *elem) const
bool marked_to_normal (TElem *elem) const
void perform_refinement ()
performs refinement on the marked elements.
bool remove_coarsen_marks ()
removes coarsen marks from the selection
void remove_hmark (TElem *elem, uint mark)
void set_grid (typename MGSelector ::grid_type *grid)
performs registration and deregistration at a grid.
virtual void process_constrained_vertex (ConstrainedVertex *cdv)
called to refine the specified element.
virtual void process_constrained_edge (ConstrainedEdge *cde)
called to refine the specified element.
virtual void process_constrained_face (ConstrainedFace *cdf)
called to refine the specified element.
virtual void process_constraining_face (ConstrainingFace *cgf)
called to refine the specified element.
Protected Member Functions inherited from ug::IRefiner
void set_message_hub (SPMessageHub msgHub)
sets the message hub.
Private Attributes
pcl::InterfaceCommunicator< EdgeLayout > m_intfComEDGE
pcl::InterfaceCommunicator< FaceLayout > m_intfComFACE
pcl::InterfaceCommunicator< VolumeLayout > m_intfComVOL
pcl::InterfaceCommunicator< VertexLayout > m_intfComVRT
DistributedGridManager * m_pDistGridMgr
MultiGrid * m_pMG
pcl::ProcessCommunicator m_procCom
Additional Inherited Members
Protected Types inherited from ug::HangingNodeRefinerBase< MGSelector >
typedef MGSelector ::template traits< Edge >::iterator sel_edge_iter
typedef MGSelector ::template traits< Face >::iterator sel_face_iter
typedef MGSelector ::template traits< Volume >::iterator sel_vol_iter
typedef MGSelector ::template traits< Vertex >::iterator sel_vrt_iter
Protected Attributes inherited from ug::HangingNodeRefinerBase< MGSelector >
std::vector< SPIRefMarkAdjuster > m_refMarkAdjusters
MGSelector m_selMarkedElements
Protected Attributes inherited from ug::IRefiner
bool m_adaptionIsActive
std::string m_adjustedMarksDebugFilename
bool m_debuggingEnabled
SPMessageHub m_messageHub
int m_msgIdAdaption
SPRefinementProjector m_projector
Detailed Description
This is a template class that allows to use a refiner in a parallel environment. Make sure that you initialize it with a valid DistributedGridManager.
Member Typedef Documentation
BaseClass
typedef HangingNodeRefiner_MultiGrid ug::ParallelHangingNodeRefiner_MultiGrid::BaseClass
Constructor & Destructor Documentation
ParallelHangingNodeRefiner_MultiGrid() [1/2]
ug::ParallelHangingNodeRefiner_MultiGrid::ParallelHangingNodeRefiner_MultiGrid (SPRefinementProjector projector = SPNULL)
References ug::HangingNodeRefinerBase< MGSelector >::add_ref_mark_adjuster(), and ug::ParallelHNodeAdjuster::create().
ParallelHangingNodeRefiner_MultiGrid() [2/2]
ug::ParallelHangingNodeRefiner_MultiGrid::ParallelHangingNodeRefiner_MultiGrid (DistributedGridManager & distGridMgr, SPRefinementProjector projector = SPNULL)
References ug::HangingNodeRefinerBase< MGSelector >::add_ref_mark_adjuster(), ug::ParallelHNodeAdjuster::create(), and ~ParallelHangingNodeRefiner_MultiGrid().
~ParallelHangingNodeRefiner_MultiGrid()
ug::ParallelHangingNodeRefiner_MultiGrid::~ParallelHangingNodeRefiner_MultiGrid () virtual
References set_distributed_grid_manager().
Referenced by ParallelHangingNodeRefiner_MultiGrid().
Member Function Documentation
assign_hnode_marks()
void ug::ParallelHangingNodeRefiner_MultiGrid::assign_hnode_marks () protected virtual
distributes hnode marks
Calls the base implementation to assign hnode marks and afterwards distributes them amongst neighbor processes.
Reimplemented from ug::HangingNodeRefinerBase< MGSelector >.
References ug::HangingNodeRefinerBase< MGSelector >::assign_hnode_marks(), ug::DistributedGridManager::grid_layout_map(), ug::HangingNodeRefinerBase< MGSelector >::HNRM_TO_CONSTRAINED, ug::HangingNodeRefinerBase< MGSelector >::HNRM_TO_CONSTRAINING, ug::HangingNodeRefinerBase< MGSelector >::HNRM_TO_NORMAL, ug::INT_H_MASTER, ug::INT_H_SLAVE, ug::INT_V_MASTER, ug::INT_V_SLAVE, ug::LIB_GRID, m_intfComEDGE, m_intfComFACE, m_intfComVRT, m_pDistGridMgr, ug::HangingNodeRefinerBase< MGSelector >::m_selMarkedElements, refinement_is_allowed(), and UG_DLOG.
broadcast_marks_horizontally()
void ug::ParallelHangingNodeRefiner_MultiGrid::broadcast_marks_horizontally (bool vertices, bool edges, bool faces, bool allowDeselection = false) protected virtual
This callback is called during execution of the coarsen() method after collect_objects_for_coarsen is done. It is responsible to mark elements for hnode coarsening. That means all elements on which a hanging node or constrained children shall be created have to be marked using mark_for_hnode_refinement during this method. The default implementation performs this marking for all local elements.
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References broadcast_marks_vertically(), ug::HangingNodeRefinerBase< MGSelector >::get_refmark_selector(), ug::DistributedGridManager::grid_layout_map(), ug::INT_H_MASTER, ug::INT_H_SLAVE, m_intfComEDGE, m_intfComFACE, m_intfComVRT, and m_pDistGridMgr.
Referenced by broadcast_marks_vertically().
broadcast_marks_vertically()
void ug::ParallelHangingNodeRefiner_MultiGrid::broadcast_marks_vertically (bool vertices, bool edges, bool faces, bool volumes, bool allowDeselection = false) protected virtual
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References broadcast_marks_horizontally(), copy_marks_to_vmasters(), ug::HangingNodeRefinerBase< MGSelector >::get_refmark_selector(), ug::DistributedGridManager::grid_layout_map(), ug::INT_V_MASTER, ug::INT_V_SLAVE, m_intfComEDGE, m_intfComFACE, m_intfComVOL, m_intfComVRT, m_pDistGridMgr, and one_proc_true().
Referenced by broadcast_marks_horizontally().
contains_edges()
bool ug::ParallelHangingNodeRefiner_MultiGrid::contains_edges () protected virtual
allows to check whether a distributed grid contains edges
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References pcl::ProcessCommunicator::allreduce(), contains_faces(), m_pMG, m_procCom, ug::MultiGrid::num(), and PCL_RO_LOR.
Referenced by one_proc_true().
contains_faces()
bool ug::ParallelHangingNodeRefiner_MultiGrid::contains_faces () protected virtual
allows to check whether a distributed grid contains faces
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References pcl::ProcessCommunicator::allreduce(), contains_volumes(), m_pMG, m_procCom, ug::MultiGrid::num(), and PCL_RO_LOR.
Referenced by contains_edges().
contains_volumes()
bool ug::ParallelHangingNodeRefiner_MultiGrid::contains_volumes () protected virtual
allows to check whether a distributed grid contains volumes
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References pcl::ProcessCommunicator::allreduce(), m_pMG, m_procCom, ug::MultiGrid::num(), and PCL_RO_LOR.
Referenced by contains_faces().
continue_collect_objects_for_refine()
bool ug::ParallelHangingNodeRefiner_MultiGrid::continue_collect_objects_for_refine (bool continueRequired) protected virtual
after each iteration in collet_objects_for_refine, this method determines whether the iteration shall be continued. Important for parallel refiners. The default implementation simply returns the specified value. This is fine for serial environments.
Reimplemented from ug::HangingNodeRefinerBase< MGSelector >.
References pcl::OneProcTrue().
Referenced by set_distributed_grid_manager().
copy_marks_to_vmasters() [1/2]
template<class TElem , class TIntfcCom > void ug::ParallelHangingNodeRefiner_MultiGrid::copy_marks_to_vmasters (TIntfcCom & com) protected
copies the current marks in the ref-mark-selector from v-slaves to v-masters
References copy_marks_to_vslaves(), ug::HangingNodeRefinerBase< MGSelector >::get_refmark_selector(), ug::DistributedGridManager::grid_layout_map(), ug::INT_V_MASTER, ug::INT_V_SLAVE, and m_pDistGridMgr.
Referenced by broadcast_marks_vertically(), copy_marks_to_vmasters(), and set_involved_processes().
copy_marks_to_vmasters() [2/2]
void ug::ParallelHangingNodeRefiner_MultiGrid::copy_marks_to_vmasters (bool vertices, bool edges, bool faces, bool volumes) protected virtual
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References copy_marks_to_vmasters(), m_intfComEDGE, m_intfComFACE, m_intfComVOL, and m_intfComVRT.
copy_marks_to_vslaves() [1/2]
template<class TElem , class TIntfcCom > void ug::ParallelHangingNodeRefiner_MultiGrid::copy_marks_to_vslaves (TIntfcCom & com) protected
copies the current marks in the ref-mark-selector from v-slaves to v-masters
References ug::HangingNodeRefinerBase< MGSelector >::get_refmark_selector(), ug::DistributedGridManager::grid_layout_map(), ug::INT_V_MASTER, ug::INT_V_SLAVE, and m_pDistGridMgr.
Referenced by copy_marks_to_vmasters(), and copy_marks_to_vslaves().
copy_marks_to_vslaves() [2/2]
void ug::ParallelHangingNodeRefiner_MultiGrid::copy_marks_to_vslaves (bool vertices, bool edges, bool faces, bool volumes) protected virtual
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References copy_marks_to_vslaves(), m_intfComEDGE, m_intfComFACE, m_intfComVOL, and m_intfComVRT.
one_proc_true()
bool ug::ParallelHangingNodeRefiner_MultiGrid::one_proc_true (bool localProcTrue) protected virtual
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References contains_edges(), and pcl::OneProcTrue().
Referenced by broadcast_marks_vertically().
post_coarsen()
void ug::ParallelHangingNodeRefiner_MultiGrid::post_coarsen () protected virtual
Notifies the associated distGridMgr that elements have been erased.
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References ug::DistributedGridManager::end_element_deletion(), m_pDistGridMgr, m_pMG, ug::HangingNodeRefiner_MultiGrid::post_coarsen(), pcl::ProcRank(), ug::SaveParallelGridLayout(), set_involved_processes(), and UG_LOG.
Referenced by pre_coarsen().
post_refine()
void ug::ParallelHangingNodeRefiner_MultiGrid::post_refine () protected virtual
Notifies the associated distGridMgr that new elements have been created.
Reimplemented from ug::HangingNodeRefinerBase< MGSelector >.
References ug::DistributedGridManager::end_ordered_element_insertion(), m_pDistGridMgr, m_pMG, ug::HangingNodeRefinerBase< MGSelector >::post_refine(), pre_coarsen(), pcl::ProcRank(), ug::SaveParallelGridLayout(), and UG_LOG.
Referenced by pre_refine().
pre_coarsen()
void ug::ParallelHangingNodeRefiner_MultiGrid::pre_coarsen () protected virtual
Notifies the associated distGridMgr that elements will be erased
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References ug::DistributedGridManager::begin_element_deletion(), m_pDistGridMgr, m_pMG, post_coarsen(), ug::HangingNodeRefiner_MultiGrid::pre_coarsen(), pcl::ProcRank(), ug::SaveParallelGridLayout(), and UG_LOG.
Referenced by post_refine().
pre_refine()
void ug::ParallelHangingNodeRefiner_MultiGrid::pre_refine () protected virtual
creates required vertices in higher levels.
Notifies the associated distGridMgr that new elements may now be created.
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References ug::DistributedGridManager::begin_ordered_element_insertion(), m_pDistGridMgr, m_pMG, post_refine(), ug::HangingNodeRefiner_MultiGrid::pre_refine(), pcl::ProcRank(), ug::SaveParallelGridLayout(), and UG_LOG.
Referenced by refinement_is_allowed().
refinement_is_allowed() [1/4]
bool ug::ParallelHangingNodeRefiner_MultiGrid::refinement_is_allowed (Vertex * elem) protected virtual
a callback that allows to deny refinement of special vertices
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References ug::DistributedGridManager::is_ghost(), m_pDistGridMgr, and ug::HangingNodeRefiner_MultiGrid::refinement_is_allowed().
Referenced by assign_hnode_marks(), and refinement_is_allowed().
refinement_is_allowed() [2/4]
bool ug::ParallelHangingNodeRefiner_MultiGrid::refinement_is_allowed (Edge * elem) protected virtual
a callback that allows to deny refinement of special edges
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References ug::DistributedGridManager::is_ghost(), m_pDistGridMgr, refinement_is_allowed(), and ug::HangingNodeRefiner_MultiGrid::refinement_is_allowed().
refinement_is_allowed() [3/4]
bool ug::ParallelHangingNodeRefiner_MultiGrid::refinement_is_allowed (Face * elem) protected virtual
a callback that allows to deny refinement of special faces
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References ug::DistributedGridManager::is_ghost(), m_pDistGridMgr, refinement_is_allowed(), and ug::HangingNodeRefiner_MultiGrid::refinement_is_allowed().
refinement_is_allowed() [4/4]
bool ug::ParallelHangingNodeRefiner_MultiGrid::refinement_is_allowed (Volume * elem) protected virtual
a callback that allows to deny refinement of special volumes
Reimplemented from ug::HangingNodeRefiner_MultiGrid.
References ug::DistributedGridManager::is_ghost(), m_pDistGridMgr, pre_refine(), and ug::HangingNodeRefiner_MultiGrid::refinement_is_allowed().
set_distributed_grid_manager()
void ug::ParallelHangingNodeRefiner_MultiGrid::set_distributed_grid_manager (DistributedGridManager & distGridMgr)
References continue_collect_objects_for_refine(), ug::DistributedGridManager::get_assigned_grid(), m_pDistGridMgr, and m_pMG.
Referenced by ~ParallelHangingNodeRefiner_MultiGrid().
set_involved_processes()
void ug::ParallelHangingNodeRefiner_MultiGrid::set_involved_processes (pcl::ProcessCommunicator com)
If not all processes are involved in refinement, one can set the involved processes here. By default all processes are involved.
References copy_marks_to_vmasters(), and m_procCom.
Referenced by post_coarsen().
Member Data Documentation
m_intfComEDGE
pcl::InterfaceCommunicator<EdgeLayout> ug::ParallelHangingNodeRefiner_MultiGrid::m_intfComEDGE private
Referenced by assign_hnode_marks(), broadcast_marks_horizontally(), broadcast_marks_vertically(), copy_marks_to_vmasters(), and copy_marks_to_vslaves().
m_intfComFACE
pcl::InterfaceCommunicator<FaceLayout> ug::ParallelHangingNodeRefiner_MultiGrid::m_intfComFACE private
Referenced by assign_hnode_marks(), broadcast_marks_horizontally(), broadcast_marks_vertically(), copy_marks_to_vmasters(), and copy_marks_to_vslaves().
m_intfComVOL
pcl::InterfaceCommunicator<VolumeLayout> ug::ParallelHangingNodeRefiner_MultiGrid::m_intfComVOL private
Referenced by broadcast_marks_vertically(), copy_marks_to_vmasters(), and copy_marks_to_vslaves().
m_intfComVRT
pcl::InterfaceCommunicator<VertexLayout> ug::ParallelHangingNodeRefiner_MultiGrid::m_intfComVRT private
Referenced by assign_hnode_marks(), broadcast_marks_horizontally(), broadcast_marks_vertically(), copy_marks_to_vmasters(), and copy_marks_to_vslaves().
m_pDistGridMgr
DistributedGridManager* ug::ParallelHangingNodeRefiner_MultiGrid::m_pDistGridMgr private
Referenced by assign_hnode_marks(), broadcast_marks_horizontally(), broadcast_marks_vertically(), copy_marks_to_vmasters(), copy_marks_to_vslaves(), post_coarsen(), post_refine(), pre_coarsen(), pre_refine(), refinement_is_allowed(), and set_distributed_grid_manager().
m_pMG
MultiGrid* ug::ParallelHangingNodeRefiner_MultiGrid::m_pMG private
Referenced by contains_edges(), contains_faces(), contains_volumes(), post_coarsen(), post_refine(), pre_coarsen(), pre_refine(), and set_distributed_grid_manager().
m_procCom
pcl::ProcessCommunicator ug::ParallelHangingNodeRefiner_MultiGrid::m_procCom private
Referenced by contains_edges(), contains_faces(), contains_volumes(), and set_involved_processes().
The documentation for this class was generated from the following files:
ugbase/lib_grid/parallelization/parallel_refinement/parallel_hanging_node_refiner_multi_grid.h
ugbase/lib_grid/parallelization/parallel_refinement/parallel_hanging_node_refiner_multi_grid.cpp