ug4: ug::bridge::ClassGroupDesc Class Reference
ug::bridge::ClassGroupDesc Class Reference
ugbase » Bridge » Registry
groups classes. One of the members is the default member.
#include <registry.h>
Public Member Functions
void add_class (IExportedClass *c, const std::string &tag)
adds a class to group
ClassGroupDesc ()
bool empty () const
returns if classes in group
IExportedClass * get_class (size_t i)
returns a class of the group
const IExportedClass * get_class (size_t i) const
returns a class of the group
const std::string & get_class_tag (size_t i) const
returns the class group tag for a class
IExportedClass * get_default_class () const
if no default class is set, this method returns NULL.
const std::string & name () const
returns name of group
size_t num_classes () const
returns number of classes in group
void set_default_class (size_t i)
sets the i'th class as default
void set_name (const std::string &name)
sets name of group
Private Attributes
std::vector< IExportedClass * > m_classes
classes registered to the class group
std::vector< std::string > m_classTags
tags can be used to describe classes. One tag for each class.
IExportedClass * m_defaultClass
the current default class
std::string m_name
name of class group
Detailed Description
groups classes. One of the members is the default member.
Constructor & Destructor Documentation
ClassGroupDesc()
ug::bridge::ClassGroupDesc::ClassGroupDesc () inline
Member Function Documentation
add_class()
void ug::bridge::ClassGroupDesc::add_class (IExportedClass * c, const std::string & tag) inline
adds a class to group
Referenced by ug::bridge::Registry::add_class_to_group().
empty()
bool ug::bridge::ClassGroupDesc::empty () const inline
returns if classes in group
Referenced by ug::vrl::classGroups2NativeClassGroups(), and ug::bridge::lua::LuaProxyGroupConstructor().
get_class() [1/2]
IExportedClass* ug::bridge::ClassGroupDesc::get_class (size_t i) inline
returns a class of the group
Referenced by ug::vrl::classGroups2NativeClassGroups(), and ug::bridge::UGTypeInfo().
get_class() [2/2]
const IExportedClass* ug::bridge::ClassGroupDesc::get_class (size_t i) const inline
returns a class of the group
get_class_tag()
const std::string& ug::bridge::ClassGroupDesc::get_class_tag (size_t i) const inline
returns the class group tag for a class
Referenced by ug::bridge::InitUG().
get_default_class()
IExportedClass* ug::bridge::ClassGroupDesc::get_default_class () const inline
if no default class is set, this method returns NULL.
Referenced by ug::vrl::classGroups2NativeClassGroups(), Java_edu_gcsc_vrl_ug_UG__1getDefaultClassNameFromGroup(), Java_edu_gcsc_vrl_ug_UG__1getExportedClassPtrByName(), ug::bridge::lua::LuaProxyGroupConstructor(), and ug::bridge::UGTypeInfo().
name()
const std::string& ug::bridge::ClassGroupDesc::name () const inline
returns name of group
Referenced by ug::vrl::classGroups2NativeClassGroups(), ug::bridge::lua::CreateBindings_LUA(), ug::bridge::GetClassesCompletitions(), and ug::bridge::lua::LuaProxyGroupConstructor().
num_classes()
size_t ug::bridge::ClassGroupDesc::num_classes () const inline
returns number of classes in group
Referenced by ug::vrl::classGroups2NativeClassGroups(), ug::bridge::InitUG(), and ug::bridge::UGTypeInfo().
set_default_class()
void ug::bridge::ClassGroupDesc::set_default_class (size_t i) inline
sets the i'th class as default
Referenced by ug::bridge::InitUG().
set_name()
void ug::bridge::ClassGroupDesc::set_name (const std::string & name) inline
sets name of group
References name.
Referenced by ug::bridge::Registry::get_class_group().
Member Data Documentation
m_classes
std::vector<IExportedClass*> ug::bridge::ClassGroupDesc::m_classes private
classes registered to the class group
m_classTags
std::vector<std::string> ug::bridge::ClassGroupDesc::m_classTags private
tags can be used to describe classes. One tag for each class.
m_defaultClass
IExportedClass* ug::bridge::ClassGroupDesc::m_defaultClass private
the current default class
m_name
std::string ug::bridge::ClassGroupDesc::m_name private
name of class group
The documentation for this class was generated from the following file:
ugbase/registry/registry.h