ug4: ug::OverlyingSubsetFinder< TDomain > Class Template Reference
ug::OverlyingSubsetFinder< TDomain > Class Template Reference
#include <overlying_subset_finder.hpp>
Public Member Functions
void debug ()
std::string findOverlyingSubset (const std::vector< number > &point)
OverlyingSubsetFinder (SmartPtr< TDomain > sp_domain, const std::string &top_ss_names)
Private Types
typedef TDomain domain_type
typedef domain_type::position_accessor_type position_accessor_type
typedef domain_type::position_attachment_type position_attachment_type
typedef grid_dim_traits< dim-1 >::element_type side_t
typedef Grid::traits< side_t >::iterator SideIterator
typedef RayElemIntersectionRecord< side_t * > top_intersection_record_t
typedef lg_ntree< dim-1, dim, side_t > top_tracer_tree_t
Private Attributes
SmartPtr< domain_type > m_sp_domain
Grid m_top_grid
std::vector< top_intersection_record_t > m_top_intersection_records
array to store all the intersections
SubsetGroup m_top_ss_grp
top_tracer_tree_t m_top_tracer_tree
Attachment< int > subset_index_attachment
Static Private Attributes
static const int dim = TDomain::dim
Member Typedef Documentation
domain_type
template<typename TDomain > typedef TDomain ug::OverlyingSubsetFinder< TDomain >::domain_type private
position_accessor_type
template<typename TDomain > typedef domain_type::position_accessor_type ug::OverlyingSubsetFinder< TDomain >::position_accessor_type private
position_attachment_type
template<typename TDomain > typedef domain_type::position_attachment_type ug::OverlyingSubsetFinder< TDomain >::position_attachment_type private
side_t
template<typename TDomain > typedef grid_dim_traits<dim-1>::element_type ug::OverlyingSubsetFinder< TDomain >::side_t private
SideIterator
template<typename TDomain > typedef Grid::traits<side_t>::iterator ug::OverlyingSubsetFinder< TDomain >::SideIterator private
top_intersection_record_t
template<typename TDomain > typedef RayElemIntersectionRecord<side_t*> ug::OverlyingSubsetFinder< TDomain >::top_intersection_record_t private
top_tracer_tree_t
template<typename TDomain > typedef lg_ntree<dim-1, dim, side_t> ug::OverlyingSubsetFinder< TDomain >::top_tracer_tree_t private
Constructor & Destructor Documentation
OverlyingSubsetFinder()
template<typename TDomain > ug::OverlyingSubsetFinder< TDomain >::OverlyingSubsetFinder (SmartPtr< TDomain > sp_domain, const std::string & top_ss_names) inline
Parameters
sp_domain the domain
top_ss_names top surface subset names
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::GridDataSerializationHandler::add(), ug::Grid::attach_to(), ug::Grid::begin(), ug::MultiGridSubsetHandler::begin(), ug::BroadcastGrid(), create(), ug::lg_ntree< tree_dim, world_dim, grid_elem_t >::create_tree(), ug::Grid::end(), ug::MultiGridSubsetHandler::end(), ug::OverlyingSubsetFinder< TDomain >::m_sp_domain, ug::OverlyingSubsetFinder< TDomain >::m_top_grid, ug::OverlyingSubsetFinder< TDomain >::m_top_ss_grp, ug::OverlyingSubsetFinder< TDomain >::m_top_tracer_tree, ug::ISelector::select(), ug::lg_ntree< tree_dim, world_dim, grid_elem_t >::set_grid(), ug::SubsetGroup::size(), and ug::OverlyingSubsetFinder< TDomain >::subset_index_attachment.
Member Function Documentation
debug()
template<typename TDomain > void ug::OverlyingSubsetFinder< TDomain >::debug () inline
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::Grid::begin(), ug::OverlyingSubsetFinder< TDomain >::dim, ug::Grid::end(), ug::OverlyingSubsetFinder< TDomain >::m_sp_domain, ug::OverlyingSubsetFinder< TDomain >::m_top_grid, ug::Grid::num(), ug::OverlyingSubsetFinder< TDomain >::subset_index_attachment, and UG_LOG_ALL_PROCS.
findOverlyingSubset()
template<typename TDomain > std::string ug::OverlyingSubsetFinder< TDomain >::findOverlyingSubset (const std::vector< number > & point) inline
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::OverlyingSubsetFinder< TDomain >::dim, ug::RayElemIntersectionRecord< TElem >::elem, ug::OverlyingSubsetFinder< TDomain >::m_sp_domain, ug::OverlyingSubsetFinder< TDomain >::m_top_grid, ug::OverlyingSubsetFinder< TDomain >::m_top_intersection_records, ug::OverlyingSubsetFinder< TDomain >::m_top_tracer_tree, ug::PointOnRay(), ug::RayElementIntersections(), ug::RayElemIntersectionRecord< TElem >::smin, ug::OverlyingSubsetFinder< TDomain >::subset_index_attachment, and UG_THROW.
Member Data Documentation
dim
template<typename TDomain > const int ug::OverlyingSubsetFinder< TDomain >::dim = TDomain::dim static private
Referenced by ug::OverlyingSubsetFinder< TDomain >::debug(), and ug::OverlyingSubsetFinder< TDomain >::findOverlyingSubset().
m_sp_domain
template<typename TDomain > SmartPtr<domain_type> ug::OverlyingSubsetFinder< TDomain >::m_sp_domain private
Referenced by ug::OverlyingSubsetFinder< TDomain >::debug(), ug::OverlyingSubsetFinder< TDomain >::findOverlyingSubset(), and ug::OverlyingSubsetFinder< TDomain >::OverlyingSubsetFinder().
m_top_grid
template<typename TDomain > Grid ug::OverlyingSubsetFinder< TDomain >::m_top_grid private
Referenced by ug::OverlyingSubsetFinder< TDomain >::debug(), ug::OverlyingSubsetFinder< TDomain >::findOverlyingSubset(), and ug::OverlyingSubsetFinder< TDomain >::OverlyingSubsetFinder().
m_top_intersection_records
template<typename TDomain > std::vector<top_intersection_record_t> ug::OverlyingSubsetFinder< TDomain >::m_top_intersection_records private
array to store all the intersections
Referenced by ug::OverlyingSubsetFinder< TDomain >::findOverlyingSubset().
m_top_ss_grp
template<typename TDomain > SubsetGroup ug::OverlyingSubsetFinder< TDomain >::m_top_ss_grp private
Referenced by ug::OverlyingSubsetFinder< TDomain >::OverlyingSubsetFinder().
m_top_tracer_tree
template<typename TDomain > top_tracer_tree_t ug::OverlyingSubsetFinder< TDomain >::m_top_tracer_tree private
Referenced by ug::OverlyingSubsetFinder< TDomain >::findOverlyingSubset(), and ug::OverlyingSubsetFinder< TDomain >::OverlyingSubsetFinder().
subset_index_attachment
template<typename TDomain > Attachment<int> ug::OverlyingSubsetFinder< TDomain >::subset_index_attachment private
Referenced by ug::OverlyingSubsetFinder< TDomain >::debug(), ug::OverlyingSubsetFinder< TDomain >::findOverlyingSubset(), and ug::OverlyingSubsetFinder< TDomain >::OverlyingSubsetFinder().
The documentation for this class was generated from the following file:
ugbase/lib_grid/algorithms/projections/overlying_subset_finder.hpp