ug4: ug::AlgebraicSpace< TGridFunction > Class Template Reference
ug::AlgebraicSpace< TGridFunction > Class Template Reference
#include <metric_spaces.h>
Private Types
typedef TGridFunction::vector_type vector_type
Private Member Functions
virtual double distance (TGridFunction &x, TGridFunction &y)
distance (for grid functions)
virtual double distance2 (TGridFunction &x, TGridFunction &y)
virtual double norm (TGridFunction &x)
norm (for grid functions)
virtual double norm2 (TGridFunction &x)
virtual ~AlgebraicSpace ()
Additional Inherited Members
Public Types inherited from ug::IGridFunctionSpace< TGridFunction >
typedef TGridFunction grid_function_type
typedef TGridFunction::vector_type vector_type
Public Member Functions inherited from ug::IGridFunctionSpace< TGridFunction >
virtual std::string config_string () const
virtual double distance (vector_type &x, vector_type &y)
OVERRIDE distance (for vectors)
virtual double norm (vector_type &x)
OVERRIDE norm (for vectors)
virtual double scaling () const
virtual ~IGridFunctionSpace ()
DTOR.
Public Member Functions inherited from ug::IBanachSpace< TGridFunction::vector_type >
virtual ~IBanachSpace ()
Member Typedef Documentation
vector_type
template<typename TGridFunction > typedef TGridFunction::vector_type ug::AlgebraicSpace< TGridFunction >::vector_type private
Constructor & Destructor Documentation
~AlgebraicSpace()
template<typename TGridFunction > virtual ug::AlgebraicSpace< TGridFunction >::~AlgebraicSpace () inline private virtual
Member Function Documentation
distance()
template<typename TGridFunction > virtual double ug::AlgebraicSpace< TGridFunction >::distance (TGridFunction & x, TGridFunction & y) inline private virtual
distance (for grid functions)
Implements ug::IGridFunctionSpace< TGridFunction >.
Referenced by ug::AlgebraicSpace< TGridFunction >::distance2().
distance2()
template<typename TGridFunction > virtual double ug::AlgebraicSpace< TGridFunction >::distance2 (TGridFunction & x, TGridFunction & y) inline private virtual
Implements ug::IGridFunctionSpace< TGridFunction >.
References ug::AlgebraicSpace< TGridFunction >::distance().
norm()
template<typename TGridFunction > virtual double ug::AlgebraicSpace< TGridFunction >::norm (TGridFunction & x) inline private virtual
norm (for grid functions)
Implements ug::IGridFunctionSpace< TGridFunction >.
Referenced by ug::AlgebraicSpace< TGridFunction >::norm2().
norm2()
template<typename TGridFunction > virtual double ug::AlgebraicSpace< TGridFunction >::norm2 (TGridFunction & x) inline private virtual
Implements ug::IGridFunctionSpace< TGridFunction >.
References ug::AlgebraicSpace< TGridFunction >::norm().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/metric_spaces.h