ug4: ug::const_ntree_element_iterator< elem_t, entry_t > Class Template Reference
ug::const_ntree_element_iterator< elem_t, entry_t > Class Template Reference
this iterator is used by the ntree class to provide access to the elements of a given node
#include <ntree_iterator.h>
Public Types
typedef size_t difference_type
typedef std::forward_iterator_tag iterator_category
typedef elem_t * pointer
typedef value_type & reference
typedef const_ntree_element_iterator this_type
typedef elem_t value_type
Public Member Functions
const_ntree_element_iterator ()
const_ntree_element_iterator (const entry_t *entries, size_t entryInd)
bool operator!= (const this_type &iter) const
value_type operator* () const
this_type operator++ ()
this_type operator++ (int unused)
bool operator== (const this_type &iter) const
Private Member Functions
bool equal (const this_type &other) const
void increment ()
Private Attributes
const entry_t * m_entries
size_t m_entryInd
Static Private Attributes
static const size_t s_invalidIndex = -1
marks an index as invalid
Detailed Description
template<class elem_t, class entry_t>
class ug::const_ntree_element_iterator< elem_t, entry_t >
this iterator is used by the ntree class to provide access to the elements of a given node
Member Typedef Documentation
difference_type
template<class elem_t , class entry_t > typedef size_t ug::const_ntree_element_iterator< elem_t, entry_t >::difference_type
iterator_category
template<class elem_t , class entry_t > typedef std::forward_iterator_tag ug::const_ntree_element_iterator< elem_t, entry_t >::iterator_category
pointer
template<class elem_t , class entry_t > typedef elem_t* ug::const_ntree_element_iterator< elem_t, entry_t >::pointer
reference
template<class elem_t , class entry_t > typedef value_type& ug::const_ntree_element_iterator< elem_t, entry_t >::reference
this_type
template<class elem_t , class entry_t > typedef const_ntree_element_iterator ug::const_ntree_element_iterator< elem_t, entry_t >::this_type
value_type
template<class elem_t , class entry_t > typedef elem_t ug::const_ntree_element_iterator< elem_t, entry_t >::value_type
Constructor & Destructor Documentation
const_ntree_element_iterator() [1/2]
template<class elem_t , class entry_t > ug::const_ntree_element_iterator< elem_t, entry_t >::const_ntree_element_iterator () inline
const_ntree_element_iterator() [2/2]
template<class elem_t , class entry_t > ug::const_ntree_element_iterator< elem_t, entry_t >::const_ntree_element_iterator (const entry_t * entries, size_t entryInd) inline
Member Function Documentation
equal()
template<class elem_t , class entry_t > bool ug::const_ntree_element_iterator< elem_t, entry_t >::equal (const this_type & other) const inline private
References ug::const_ntree_element_iterator< elem_t, entry_t >::m_entryInd.
Referenced by ug::const_ntree_element_iterator< elem_t, entry_t >::operator!=(), and ug::const_ntree_element_iterator< elem_t, entry_t >::operator==().
increment()
template<class elem_t , class entry_t > void ug::const_ntree_element_iterator< elem_t, entry_t >::increment () inline private
References ug::const_ntree_element_iterator< elem_t, entry_t >::m_entries, ug::const_ntree_element_iterator< elem_t, entry_t >::m_entryInd, and ug::const_ntree_element_iterator< elem_t, entry_t >::s_invalidIndex.
Referenced by ug::const_ntree_element_iterator< elem_t, entry_t >::operator++().
operator!=()
template<class elem_t , class entry_t > bool ug::const_ntree_element_iterator< elem_t, entry_t >::operator!= (const this_type & iter) const inline
References ug::const_ntree_element_iterator< elem_t, entry_t >::equal().
operator*()
template<class elem_t , class entry_t > value_type ug::const_ntree_element_iterator< elem_t, entry_t >::operator* () const inline
References ug::const_ntree_element_iterator< elem_t, entry_t >::m_entries, ug::const_ntree_element_iterator< elem_t, entry_t >::m_entryInd, and ug::const_ntree_element_iterator< elem_t, entry_t >::s_invalidIndex.
operator++() [1/2]
template<class elem_t , class entry_t > this_type ug::const_ntree_element_iterator< elem_t, entry_t >::operator++ () inline
References ug::const_ntree_element_iterator< elem_t, entry_t >::increment().
operator++() [2/2]
template<class elem_t , class entry_t > this_type ug::const_ntree_element_iterator< elem_t, entry_t >::operator++ (int unused) inline
References ug::const_ntree_element_iterator< elem_t, entry_t >::increment().
operator==()
template<class elem_t , class entry_t > bool ug::const_ntree_element_iterator< elem_t, entry_t >::operator== (const this_type & iter) const inline
References ug::const_ntree_element_iterator< elem_t, entry_t >::equal().
Member Data Documentation
m_entries
template<class elem_t , class entry_t > const entry_t* ug::const_ntree_element_iterator< elem_t, entry_t >::m_entries private
Referenced by ug::const_ntree_element_iterator< elem_t, entry_t >::increment(), and ug::const_ntree_element_iterator< elem_t, entry_t >::operator*().
m_entryInd
template<class elem_t , class entry_t > size_t ug::const_ntree_element_iterator< elem_t, entry_t >::m_entryInd private
Referenced by ug::const_ntree_element_iterator< elem_t, entry_t >::equal(), ug::const_ntree_element_iterator< elem_t, entry_t >::increment(), and ug::const_ntree_element_iterator< elem_t, entry_t >::operator*().
s_invalidIndex
template<class elem_t , class entry_t > const size_t ug::const_ntree_element_iterator< elem_t, entry_t >::s_invalidIndex = -1 static private
marks an index as invalid
Referenced by ug::const_ntree_element_iterator< elem_t, entry_t >::increment(), and ug::const_ntree_element_iterator< elem_t, entry_t >::operator*().
The documentation for this class was generated from the following file:
ugbase/common/space_partitioning/ntree_iterator.h