ug4: ug::PageContainer< T, MAX_PAGE_SIZE, Allocator > Class Template Reference
ug::PageContainer< T, MAX_PAGE_SIZE, Allocator > Class Template Reference
#include <page_container.h>
Public Types
typedef Allocator allocator_type
typedef Allocator::const_reference const_reference
typedef Allocator::difference_type difference_type
typedef Allocator::reference reference
typedef Allocator::size_type size_type
Public Member Functions
size_t capacity () const
void clear ()
PageContainer & operator= (const PageContainer &pc)
T & operator[] (size_t ind)
const T & operator[] (size_t ind) const
PageContainer ()
PageContainer (const PageContainer &pc)
void reserve (size_t size)
void resize (size_t size, const T &val=T())
size_t size () const
void swap (PageContainer &pc)
~PageContainer ()
Private Member Functions
void assign_container (const PageContainer &pc)
T * get_page (size_t ind) const
returns the page in which the data for the given index lies
size_t get_page_index (size_t ind) const
returns the index of the page in which the data for the given index lies
size_t get_page_offset (size_t ind) const
returns the offset that a index has in its page
Private Attributes
Allocator m_alloc
const size_t m_numPageEntries
std::vector< T * > m_pages
size_t m_size
Member Typedef Documentation
template<class T , int MAX_PAGE_SIZE = 4096, class Allocator = std::allocator<T>> typedef Allocator ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::allocator_type
template<class T , int MAX_PAGE_SIZE = 4096, class Allocator = std::allocator<T>> typedef Allocator::const_reference ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::const_reference
template<class T , int MAX_PAGE_SIZE = 4096, class Allocator = std::allocator<T>> typedef Allocator::difference_type ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::difference_type
template<class T , int MAX_PAGE_SIZE = 4096, class Allocator = std::allocator<T>> typedef Allocator::reference ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::reference
template<class T , int MAX_PAGE_SIZE = 4096, class Allocator = std::allocator<T>> typedef Allocator::size_type ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::size_type
Constructor & Destructor Documentation
template<class T , int MAX_PAGE_SIZE, class Allocator > ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::PageContainer ()
template<class T , int MAX_PAGE_SIZE, class Allocator > ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::PageContainer (const PageContainer< T, MAX_PAGE_SIZE, Allocator > & pc)
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::assign_container(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::~PageContainer().
template<class T , int MAX_PAGE_SIZE, class Allocator > ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::~PageContainer ()
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::clear(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_alloc, ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_numPageEntries, ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_pages, and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::operator=().
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::PageContainer().
Member Function Documentation
template<class T , int MAX_PAGE_SIZE, class Allocator > void ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::assign_container (const PageContainer< T, MAX_PAGE_SIZE, Allocator > & pc) private
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::clear(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page_offset(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_alloc, ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_numPageEntries, ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_size, and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::reserve().
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::operator=(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::PageContainer(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::swap().
template<class T , int MAX_PAGE_SIZE, class Allocator > size_t ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::capacity () const inline
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_numPageEntries, ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_pages, and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::resize().
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::size().
template<class T , int MAX_PAGE_SIZE, class Allocator > void ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::clear ()
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::operator[](), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::resize().
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::assign_container(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::reserve(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::~PageContainer().
template<class T , int MAX_PAGE_SIZE, class Allocator > T * ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page (size_t ind) const inline private
returns the page in which the data for the given index lies
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page_index(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_pages.
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::assign_container(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::operator[](), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::resize().
template<class T , int MAX_PAGE_SIZE, class Allocator > size_t ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page_index (size_t ind) const inline private
returns the index of the page in which the data for the given index lies
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page_offset(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_numPageEntries.
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page().
template<class T , int MAX_PAGE_SIZE, class Allocator > size_t ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page_offset (size_t ind) const inline private
returns the offset that a index has in its page
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_numPageEntries.
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::assign_container(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page_index(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::operator[](), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::resize().
template<class T , int MAX_PAGE_SIZE, class Allocator > PageContainer< T, MAX_PAGE_SIZE, Allocator > & ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::operator= (const PageContainer< T, MAX_PAGE_SIZE, Allocator > & pc)
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::assign_container(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::size().
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::~PageContainer().
template<class T , int MAX_PAGE_SIZE, class Allocator > T & ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::operator[] (size_t ind) inline
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page_offset(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_size.
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::clear().
template<class T , int MAX_PAGE_SIZE, class Allocator > const T & ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::operator[] (size_t ind) const inline
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page_offset(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_size, and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::swap().
template<class T , int MAX_PAGE_SIZE, class Allocator > void ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::reserve (size_t size)
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::clear(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_alloc, ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_numPageEntries, ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_pages, and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::size().
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::assign_container(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::resize().
template<class T , int MAX_PAGE_SIZE, class Allocator > void ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::resize (size_t size, const T & val = T())
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page_offset(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_alloc, ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_numPageEntries, ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_size, ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::reserve(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::size().
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::capacity(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::clear().
template<class T , int MAX_PAGE_SIZE, class Allocator > size_t ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::size () const inline
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::capacity(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_size.
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::operator=(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::reserve(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::resize().
template<class T , int MAX_PAGE_SIZE, class Allocator > void ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::swap (PageContainer< T, MAX_PAGE_SIZE, Allocator > & pc)
References ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::assign_container(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_alloc, ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_pages, and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_size.
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::operator[]().
Member Data Documentation
template<class T , int MAX_PAGE_SIZE = 4096, class Allocator = std::allocator<T>> Allocator ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_alloc private
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::assign_container(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::reserve(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::resize(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::swap(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::~PageContainer().
template<class T , int MAX_PAGE_SIZE = 4096, class Allocator = std::allocator<T>> const size_t ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_numPageEntries private
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::assign_container(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::capacity(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page_index(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page_offset(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::reserve(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::resize(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::~PageContainer().
template<class T , int MAX_PAGE_SIZE = 4096, class Allocator = std::allocator<T>> std::vector<T*> ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_pages private
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::capacity(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::get_page(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::reserve(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::swap(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::~PageContainer().
template<class T , int MAX_PAGE_SIZE = 4096, class Allocator = std::allocator<T>> size_t ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::m_size private
Referenced by ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::assign_container(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::operator[](), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::resize(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::size(), and ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::swap().
The documentation for this class was generated from the following files:
ugbase/lib_grid/attachments/page_container.h
ugbase/lib_grid/attachments/page_container_impl.h