ug4: ug::CrouzeixRaviartElemTransfer< TDomain > Class Template Reference
ug::CrouzeixRaviartElemTransfer< TDomain > Class Template Reference
#include <local_transfer.h>
Public Member Functions
CrouzeixRaviartElemTransfer (const LFEID &lfeid)
template<typename TParent >
void do_restrict (TParent *parent, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent)
virtual bool perform_prolongation_on (GridBaseObjectId gbo)
virtual bool perform_restriction_on (GridBaseObjectId gbo)
template<typename TSide >
void prolongate (const std::vector< typename TSide::sideof * > &vParentElem, const std::vector< TSide * > &vChildSide, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent)
template<typename TParent >
void prolongate (TParent *parent, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent)
void prolongate (Vertex *parent, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent)
Public Member Functions inherited from ug::ElemProlongationBase< TDomain, CrouzeixRaviartElemTransfer< TDomain > >
virtual void prolongate (Edge *parent)
virtual void prolongate (Face *parent)
virtual void prolongate (Vertex *parent)
virtual void prolongate (Volume *parent)
Public Member Functions inherited from ug::IElemProlongation< TDomain >
virtual void init (ConstSmartPtr< TDomain > spDomain, SmartPtr< TransferValueAccessor > vValueChild, SmartPtr< TransferValueAccessor > vValueParent)
virtual ~IElemProlongation ()
Public Member Functions inherited from ug::ElemRestrictionBase< TDomain, CrouzeixRaviartElemTransfer< TDomain > >
virtual void do_restrict (Edge *parent)
virtual void do_restrict (Face *parent)
virtual void do_restrict (Vertex *parent)
virtual void do_restrict (Volume *parent)
Public Member Functions inherited from ug::IElemRestriction< TDomain >
virtual void init (ConstSmartPtr< TDomain > spDomain, SmartPtr< TransferValueAccessor > vValueChild, SmartPtr< TransferValueAccessor > vValueParent)
virtual ~IElemRestriction ()
Static Public Attributes
static const int dim = TDomain::dim
world dimension
Protected Attributes
LFEID m_lfeid
Protected Attributes inherited from ug::IElemProlongation< TDomain >
ConstSmartPtr< TDomain > m_spDomain
ConstSmartPtr< MultiGrid > m_spGrid
SmartPtr< TransferValueAccessor > m_vValueChild
SmartPtr< TransferValueAccessor > m_vValueParent
Protected Attributes inherited from ug::IElemRestriction< TDomain >
ConstSmartPtr< TDomain > m_spDomain
ConstSmartPtr< MultiGrid > m_spGrid
SmartPtr< TransferValueAccessor > m_vValueChild
SmartPtr< TransferValueAccessor > m_vValueParent
Additional Inherited Members
Protected Member Functions inherited from ug::ElemProlongationBase< TDomain, CrouzeixRaviartElemTransfer< TDomain > >
CrouzeixRaviartElemTransfer< TDomain > & getImpl ()
access to implementation
const CrouzeixRaviartElemTransfer< TDomain > & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::ElemRestrictionBase< TDomain, CrouzeixRaviartElemTransfer< TDomain > >
CrouzeixRaviartElemTransfer< TDomain > & getImpl ()
access to implementation
const CrouzeixRaviartElemTransfer< TDomain > & getImpl () const
const access to implementation
Constructor & Destructor Documentation
CrouzeixRaviartElemTransfer()
template<typename TDomain > ug::CrouzeixRaviartElemTransfer< TDomain >::CrouzeixRaviartElemTransfer (const LFEID & lfeid) inline
Member Function Documentation
do_restrict()
template<typename TDomain > template<typename TParent > void ug::CrouzeixRaviartElemTransfer< TDomain >::do_restrict (TParent * parent, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent) inline
References ug::TransferValueAccessor::access_inner(), dim, ug::LFEID::dim(), ug::MultiGrid::get_child(), ug::CrouzeixRaviartElemTransfer< TDomain >::m_lfeid, ug::MultiGrid::num_children(), ug::TransferValueAccessor::size(), UG_ASSERT, and UG_THROW.
perform_prolongation_on()
template<typename TDomain > virtual bool ug::CrouzeixRaviartElemTransfer< TDomain >::perform_prolongation_on (GridBaseObjectId gbo) inline virtual
Implements ug::IElemProlongation< TDomain >.
References ug::LFEID::dim(), and ug::CrouzeixRaviartElemTransfer< TDomain >::m_lfeid.
perform_restriction_on()
template<typename TDomain > virtual bool ug::CrouzeixRaviartElemTransfer< TDomain >::perform_restriction_on (GridBaseObjectId gbo) inline virtual
Implements ug::IElemRestriction< TDomain >.
References ug::LFEID::dim(), and ug::CrouzeixRaviartElemTransfer< TDomain >::m_lfeid.
prolongate() [1/3]
template<typename TDomain > template<typename TSide > void ug::CrouzeixRaviartElemTransfer< TDomain >::prolongate (const std::vector< typename TSide::sideof * > & vParentElem, const std::vector< TSide * > & vChildSide, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent) inline
References ug::TransferValueAccessor::access_closure(), ug::TransferValueAccessor::access_inner(), ug::CollectCornerCoordinates(), dim, ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::InnerDoFPosition(), ug::CrouzeixRaviartElemTransfer< TDomain >::m_lfeid, p, ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), ug::TransferValueAccessor::size(), and UG_THROW.
prolongate() [2/3]
template<typename TDomain > template<typename TParent > void ug::CrouzeixRaviartElemTransfer< TDomain >::prolongate (TParent * parent, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent) inline
References dim, ug::LFEID::dim(), ug::MultiGrid::get_child(), ug::CrouzeixRaviartElemTransfer< TDomain >::m_lfeid, ug::MultiGrid::num_children(), p, and ug::PointerConstArray< TPtr >::size().
prolongate() [3/3]
template<typename TDomain > void ug::CrouzeixRaviartElemTransfer< TDomain >::prolongate (Vertex * parent, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent) inline
References UG_THROW.
Member Data Documentation
dim
template<typename TDomain > const int ug::CrouzeixRaviartElemTransfer< TDomain >::dim = TDomain::dim static
world dimension
m_lfeid
template<typename TDomain > LFEID ug::CrouzeixRaviartElemTransfer< TDomain >::m_lfeid protected
Referenced by ug::CrouzeixRaviartElemTransfer< TDomain >::do_restrict(), ug::CrouzeixRaviartElemTransfer< TDomain >::perform_prolongation_on(), ug::CrouzeixRaviartElemTransfer< TDomain >::perform_restriction_on(), and ug::CrouzeixRaviartElemTransfer< TDomain >::prolongate().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/local_transfer.h