ug4: ug::Vector< TValueType > Class Template Reference
ug::Vector< TValueType > Class Template Reference
lib_algebralib_algebra » | CRS Algebra » CPU Algebra
#include <vector.h>
Public Types
typedef TValueType value_type
typedef Vector< TValueType > vector_type
Public Member Functions
template<typename V >
void add (const V &u)
void add (const value_type *u, const size_t *indices, size_t nr)
size_t capacity () const
SmartPtr< vector_type > clone () const
clones the vector (deep-copy) including values
SmartPtr< vector_type > clone_without_values () const
clones the vector (deep-copy) excluding values
void create (size_t size)
create a vector with specific size
void create (const Vector &v)
create as a copy of other vector
size_t defragment ()
double dotprod (const Vector &w)
returns v.T w, that is the dotprod of this vector and w
template<typename V >
void get (V &u) const
void get (value_type *u, const size_t *indices, size_t nr) const
double norm () const
return sqrt(sum values[i]^2) (euclidian norm)
void operator*= (const number &a)
void operator+= (const Vector &v)
void operator-= (const Vector &v)
double operator= (double d)
assign double d to whole Vector
void operator= (const Vector &v)
assign other vector v
value_type & operator[] (size_t i)
access element i of the vector
const value_type & operator[] (size_t i) const
void p ()
gdb shortcut for print
void print (const char *const text=NULL) const
print vector to console
void reserve (size_t newCapacity, bool bCopyValues=true)
void reserve_exactly (size_t newCapacity, bool bCopyValues)
void reserve_sloppy (size_t newCapacity, bool bCopyValues=true)
void resize (size_t newSize, bool bCopyValues=true)
void resize_exactly (size_t newSize, bool bCopyValues=true)
resize the vector to be EXACTLY newSize big (no overhead)
void resize_sloppy (size_t newSize, bool bCopyValues=true)
void set (double d)
assign double d to whole Vector
template<typename V >
void set (const V &u)
void set (const value_type *u, const size_t *indices, size_t nr)
void set_random (double from, double to)
size_t size () const
Vector ()
constructor
Vector (size_t size)
constructor with size
Vector (const vector_type &v)
virtual ~Vector ()
virtual destructor
Protected Member Functions
virtual vector_type * virtual_clone () const
virtual clone using covariant return type
virtual vector_type * virtual_clone_without_values () const
virtual clone using covariant return type excluding values
Private Member Functions
void destroy ()
Private Attributes
size_t m_capacity
size of the vector (vector is from 0..size-1)
size_t m_size
size of the vector (vector is from 0..size-1)
value_type * values
array where the values are stored, size m_size
Friends
std::ostream & operator<< (std::ostream &output, const Vector &v)
ostream << operator
Member Typedef Documentation
template<typename TValueType> typedef TValueType ug::Vector< TValueType >::value_type
template<typename TValueType> typedef Vector<TValueType> ug::Vector< TValueType >::vector_type
Constructor & Destructor Documentation
template<typename value_type > Vector< value_type >::Vector ()
constructor
References FORCE_CREATION, and ug::Vector< TValueType >::p().
template<typename value_type > Vector< value_type >::Vector (size_t size)
constructor with size
References ug::Vector< TValueType >::create(), FORCE_CREATION, and ug::Vector< TValueType >::p().
template<typename value_type > Vector< value_type >::~Vector () virtual
virtual destructor
References ug::Vector< TValueType >::destroy().
template<typename TValueType> ug::Vector< TValueType >::Vector (const vector_type & v) inline
Member Function Documentation
template<typename value_type > template<typename V > void Vector< value_type >::add (const V & u)
add/set/get a local vector
The local vector type must provide the following members:
size() - length of local vector
index(size_t i) - global index for component i
operator[](size_t i) - access to value of component i
References ug::Vector< TValueType >::values.
Referenced by ug::Vector< double >::set().
template<typename value_type > void Vector< value_type >::add (const value_type * u, const size_t * indices, size_t nr)
References ug::Vector< TValueType >::values.
template<typename TValueType> size_t ug::Vector< TValueType >::capacity () const inline
template<typename value_type > SmartPtr< Vector< value_type > > Vector< value_type >::clone () const
clones the vector (deep-copy) including values
References ug::Vector< TValueType >::virtual_clone().
Referenced by ug::Vector< double >::Vector().
template<typename value_type > SmartPtr< Vector< value_type > > Vector< value_type >::clone_without_values () const
clones the vector (deep-copy) excluding values
References ug::Vector< TValueType >::virtual_clone_without_values().
Referenced by ug::Vector< double >::Vector().
template<typename value_type > void Vector< value_type >::create (size_t size)
create a vector with specific size
References ug::Vector< TValueType >::destroy(), ug::Vector< TValueType >::m_capacity, ug::Vector< TValueType >::m_size, ug::Vector< TValueType >::size(), and ug::Vector< TValueType >::values.
Referenced by ug::Vector< TValueType >::Vector(), and ug::Vector< double >::Vector().
template<typename value_type > void Vector< value_type >::create (const Vector< TValueType > & v)
create as a copy of other vector
References ug::Vector< TValueType >::m_capacity, ug::Vector< TValueType >::m_size, UG_ASSERT, and ug::Vector< TValueType >::values.
template<typename TValueType> size_t ug::Vector< TValueType >::defragment () inline
template<typename value_type > void Vector< value_type >::destroy () private
References ug::Vector< TValueType >::m_size, and ug::Vector< TValueType >::values.
Referenced by ug::Vector< TValueType >::create(), ug::Vector< double >::defragment(), and ug::Vector< TValueType >::~Vector().
template<typename value_type > double Vector< value_type >::dotprod (const Vector< TValueType > & w) inline
returns v.T w, that is the dotprod of this vector and w
References ug::Vector< TValueType >::m_size, UG_ASSERT, and ug::VecProd().
Referenced by ug::Vector< double >::capacity().
template<typename value_type > template<typename V > void Vector< value_type >::get (V & u) const
References ug::Vector< TValueType >::values.
template<typename value_type > void Vector< value_type >::get (value_type * u, const size_t * indices, size_t nr) const
References ug::Vector< TValueType >::values.
template<typename value_type > double Vector< value_type >::norm () const inline
return sqrt(sum values[i]^2) (euclidian norm)
References ug::BlockNorm2(), ug::Vector< TValueType >::size(), and ug::Vector< TValueType >::values.
Referenced by ug::Vector< double >::operator*=().
template<typename TValueType> void ug::Vector< TValueType >::operator*= (const number & a) inline
template<typename value_type > void Vector< value_type >::operator+= (const Vector< TValueType > & v) inline
References ug::Vector< TValueType >::size(), and UG_ASSERT.
Referenced by ug::Vector< double >::set().
template<typename value_type > void Vector< value_type >::operator-= (const Vector< TValueType > & v) inline
References ug::Vector< TValueType >::size(), and UG_ASSERT.
Referenced by ug::Vector< double >::set().
template<typename value_type > double Vector< value_type >::operator= (double d) inline
assign double d to whole Vector
Referenced by ug::Vector< double >::capacity(), ug::Vector< double >::set(), and ug::Vector< double >::Vector().
template<typename value_type > void Vector< value_type >::operator= (const Vector< TValueType > & v) inline
assign other vector v
References resize(), and ug::Vector< TValueType >::size().
template<typename value_type > value_type & Vector< value_type >::operator[] (size_t i) inline
access element i of the vector
References UG_ASSERT.
Referenced by ug::Vector< double >::capacity(), and ug::GPUVector< TValueType >::operator[]().
template<typename value_type > const value_type & Vector< value_type >::operator[] (size_t i) const inline
References UG_ASSERT.
template<typename TValueType> void ug::Vector< TValueType >::p () inline
gdb shortcut for print
Referenced by ug::Vector< TValueType >::Vector().
template<typename value_type > void Vector< value_type >::print (const char *const text = NULL) const
print vector to console
References ug::Vector< TValueType >::m_size, and ug::Vector< TValueType >::values.
Referenced by ug::Vector< double >::p(), and ug::Vector< double >::size().
template<typename TValueType> void ug::Vector< TValueType >::reserve (size_t newCapacity, bool bCopyValues = true) inline
template<typename value_type > void Vector< value_type >::reserve_exactly (size_t newCapacity, bool bCopyValues)
reserve will allocate EXACTLY newCapacity assertion if newCapacity < size
References ug::Vector< TValueType >::m_capacity, ug::Vector< TValueType >::m_size, UG_ASSERT, and ug::Vector< TValueType >::values.
Referenced by ug::Vector< double >::reserve(), ug::Vector< TValueType >::reserve_sloppy(), ug::Vector< TValueType >::resize_exactly(), ug::Vector< TValueType >::resize_sloppy(), and ug::Vector< double >::Vector().
template<typename value_type > void Vector< value_type >::reserve_sloppy (size_t newCapacity, bool bCopyValues = true)
reserve capacity in vector. if bigger than capacity, new capacity is newCapacity+oldCapacity/2
References ug::Vector< TValueType >::m_capacity, and ug::Vector< TValueType >::reserve_exactly().
Referenced by ug::Vector< double >::Vector().
template<typename TValueType> void ug::Vector< TValueType >::resize (size_t newSize, bool bCopyValues = true) inline
Referenced by ug::ILUTScalarPreconditioner< algebra_type >::apply_double(), ug::CloneVector(), ug::Deserialize(), ug::GetBlockGSCorrectionILUT(), ug::GPUVector< TValueType >::resize(), and ug::ILUTScalarPreconditioner< algebra_type >::solve().
template<typename value_type > void Vector< value_type >::resize_exactly (size_t newSize, bool bCopyValues = true)
resize the vector to be EXACTLY newSize big (no overhead)
References ug::Vector< TValueType >::m_capacity, ug::Vector< TValueType >::m_size, and ug::Vector< TValueType >::reserve_exactly().
Referenced by ug::Vector< double >::resize(), and ug::Vector< double >::Vector().
template<typename value_type > void Vector< value_type >::resize_sloppy (size_t newSize, bool bCopyValues = true)
resize vector. if bigger than capacity, new capacity is newSize+oldSize/2 so growth factor is 1.5 (this is to keep memory overhead small)
See also
also https://github.com/facebook/folly/blob/master/folly/docs/FBVector.md
References ug::Vector< TValueType >::m_capacity, ug::Vector< TValueType >::m_size, and ug::Vector< TValueType >::reserve_exactly().
Referenced by ug::Vector< double >::Vector().
template<typename TValueType> void ug::Vector< TValueType >::set (double d) inline
assign double d to whole Vector
template<typename value_type > template<typename V > void Vector< value_type >::set (const V & u)
References ug::Vector< TValueType >::values.
template<typename value_type > void Vector< value_type >::set (const value_type * u, const size_t * indices, size_t nr)
References ug::Vector< TValueType >::values.
template<typename value_type > void Vector< value_type >::set_random (double from, double to) inline
References ug::BlockRef(), ug::GetSize(), and ug::urand().
Referenced by ug::Vector< double >::set().
template<typename TValueType> size_t ug::Vector< TValueType >::size () const inline
Referenced by ug::GPUVector< TValueType >::add(), ug::GPUVector< TValueType >::assure_on_gpu(), ug::CloneVector(), ug::Vector< TValueType >::create(), ug::GPUVector< TValueType >::dotprod(), ug::Vector< TValueType >::norm(), ug::GPUVector< TValueType >::norm(), ug::Vector< double >::operator*=(), ug::GPUVector< TValueType >::operator*=(), ug::Vector< TValueType >::operator+=(), ug::GPUVector< TValueType >::operator+=(), ug::Vector< TValueType >::operator-=(), ug::GPUVector< TValueType >::operator-=(), ug::Vector< TValueType >::operator=(), ug::GPUVector< TValueType >::operator=(), ug::Serialize(), ug::ILUTPreconditioner< ug::CPUAlgebra >::solve(), ug::VecAssign(), ug::VecNormSquaredAdd(), ug::VecProd(), ug::VecScaleAdd(), ug::VecScaleAssign(), ug::Vector< double >::Vector(), and ug::GPUVector< TValueType >::virtual_clone_without_values().
template<typename value_type > Vector< value_type > * Vector< value_type >::virtual_clone () const protected virtual
virtual clone using covariant return type
This should be used instead of the copy constructor at the places where the additional information stored in the object of the derived class (like the geometry or the topology of the grid) should be kept.
Reimplemented in ug::ParallelVector< Vector< double > >, and ug::GPUVector< TValueType >.
Referenced by ug::Vector< TValueType >::clone(), and ug::Vector< double >::defragment().
template<typename value_type > Vector< value_type > * Vector< value_type >::virtual_clone_without_values () const protected virtual
virtual clone using covariant return type excluding values
This should be used instead of the copy constructor at the places where the additional information stored in the object of the derived class (like the geometry or the topology of the grid) should be kept.
Reimplemented in ug::ParallelVector< Vector< double > >, and ug::GPUVector< TValueType >.
References ug::Vector< TValueType >::m_size.
Referenced by ug::Vector< TValueType >::clone_without_values(), and ug::Vector< double >::defragment().
Friends And Related Function Documentation
template<typename TValueType> std::ostream& operator<< (std::ostream & output, const Vector< TValueType > & v) friend
ostream << operator
Member Data Documentation
template<typename TValueType> size_t ug::Vector< TValueType >::m_capacity private
size of the vector (vector is from 0..size-1)
Referenced by ug::Vector< double >::capacity(), ug::Vector< TValueType >::create(), ug::Vector< TValueType >::reserve_exactly(), ug::Vector< TValueType >::reserve_sloppy(), ug::Vector< TValueType >::resize_exactly(), ug::Vector< TValueType >::resize_sloppy(), and ug::Vector< double >::Vector().
template<typename TValueType> size_t ug::Vector< TValueType >::m_size private
size of the vector (vector is from 0..size-1)
Referenced by ug::Vector< TValueType >::create(), ug::Vector< TValueType >::destroy(), ug::Vector< TValueType >::dotprod(), ug::Vector< TValueType >::print(), ug::Vector< TValueType >::reserve_exactly(), ug::Vector< TValueType >::resize_exactly(), ug::Vector< TValueType >::resize_sloppy(), ug::Vector< double >::size(), ug::Vector< double >::Vector(), and ug::Vector< TValueType >::virtual_clone_without_values().
template<typename TValueType> value_type* ug::Vector< TValueType >::values private
array where the values are stored, size m_size
Referenced by ug::Vector< TValueType >::add(), ug::Vector< TValueType >::create(), ug::Vector< TValueType >::destroy(), ug::Vector< TValueType >::get(), ug::Vector< TValueType >::norm(), ug::Vector< double >::operator*=(), ug::Vector< TValueType >::print(), ug::Vector< TValueType >::reserve_exactly(), ug::Vector< TValueType >::set(), and ug::Vector< double >::Vector().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/cpu_algebra/vector.h
ugbase/lib_algebra/cpu_algebra/vector_impl.h