ug4: ug::attachment_traits< Edge *, ElementStorage< Edge > > Class Template Reference
ug::attachment_traits< Edge *, ElementStorage< Edge > > Class Template Reference
#include <element_storage.h>
Public Types
typedef const ElementStorage< Edge > * ConstElemHandlerPtr
typedef const Edge * ConstElemPtr
typedef ElementStorage< Edge >::SectionContainer::iterator element_iterator
typedef ElementStorage< Edge > * ElemHandlerPtr
typedef Edge * ElemPtr
typedef Edge *& ElemRef
Static Public Member Functions
static element_iterator elements_begin (ElemHandlerPtr pHandler)
static element_iterator elements_end (ElemHandlerPtr pHandler)
static uint get_data_index (ConstElemHandlerPtr pHandler, ConstElemPtr elem)
static void set_data_index (ElemHandlerPtr pHandler, ElemPtr elem, uint index)
Member Typedef Documentation
ConstElemHandlerPtr
typedef const ElementStorage<Edge>* ug::attachment_traits< Edge *, ElementStorage< Edge > >::ConstElemHandlerPtr
ConstElemPtr
typedef const Edge* ug::attachment_traits< Edge *, ElementStorage< Edge > >::ConstElemPtr
element_iterator
typedef ElementStorage<Edge>::SectionContainer::iterator ug::attachment_traits< Edge *, ElementStorage< Edge > >::element_iterator
ElemHandlerPtr
typedef ElementStorage<Edge>* ug::attachment_traits< Edge *, ElementStorage< Edge > >::ElemHandlerPtr
ElemPtr
typedef Edge* ug::attachment_traits< Edge *, ElementStorage< Edge > >::ElemPtr
ElemRef
typedef Edge*& ug::attachment_traits< Edge *, ElementStorage< Edge > >::ElemRef
Member Function Documentation
elements_begin()
static element_iterator ug::attachment_traits< Edge *, ElementStorage< Edge > >::elements_begin (ElemHandlerPtr pHandler) inline static
References ug::SectionContainer< TValue, TContainer >::begin(), and ug::ElementStorage< TElem >::m_sectionContainer.
elements_end()
static element_iterator ug::attachment_traits< Edge *, ElementStorage< Edge > >::elements_end (ElemHandlerPtr pHandler) inline static
References ug::SectionContainer< TValue, TContainer >::end(), and ug::ElementStorage< TElem >::m_sectionContainer.
get_data_index()
static uint ug::attachment_traits< Edge *, ElementStorage< Edge > >::get_data_index (ConstElemHandlerPtr pHandler, ConstElemPtr elem) inline static
References ug::GridObject::grid_data_index().
set_data_index()
static void ug::attachment_traits< Edge *, ElementStorage< Edge > >::set_data_index (ElemHandlerPtr pHandler, ElemPtr elem, uint index) inline static
References ug::GridObject::set_grid_data_index().
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/element_storage.h