ug4: ug::GlobalAttachments Class Reference
ug::GlobalAttachments Class Reference
Global attachments are automatically read/written from/to files and are considered during redistribution.
#include <global_attachments.h>
Classes
struct AttachmentEntry
struct AttachmentType
struct FunctionEntry
struct IAttachmentType
struct IFunctionEntry
Static Public Member Functions
template<class TElem >
static void add_data_serializer (GridDataSerializationHandler &handler, Grid &grid, const std::string &name)
template<class TElem >
static void attach (Grid &g, const std::string &name)
template<class TAttachment >
static TAttachment attachment (const std::string &name)
static bool attachment_pass_on_behaviour (const std::string &name)
template<class TAttachment >
static void declare_attachment (const std::string &name, bool passOnBehaviour=false)
static void declare_attachment (const std::string &name, const std::string &typeName, bool passOnBehaviour=false)
static const std::vector< std::string > & declared_attachment_names ()
template<class TElem >
static bool is_attached (Grid &g, const std::string &name)
static bool is_declared (const std::string &name)
template<class TElem >
static void read_attachment_values (std::istream &in, Grid &grid, const std::string &name)
template<class TAttachment >
static void register_attachment_type ()
static bool type_is_registered (const std::string &typeName)
static const char * type_name (const std::string &name)
template<class TAttachment >
static void undeclare_attachment (const std::string &name)
template<class TElem >
static void write_attachment_values (std::ostream &out, Grid &grid, const std::string &name)
Private Types
typedef std::map< std::string, AttachmentEntry > AttachmentMap
typedef std::map< std::string, IAttachmentType > AttachmentTypeMap
typedef std::vector< IFunctionEntry > FunctionVec
Private Member Functions
GlobalAttachments ()
~GlobalAttachments ()
Static Private Member Functions
template<class TElem , class TAttachment >
static void add_attachment_serializer (GridDataSerializationHandler &handler, Grid &g, IAttachment &attachment)
static AttachmentEntry & attachment_entry (const std::string &name)
static std::vector< std::string > & attachment_names ()
static AttachmentTypeMap & attachment_types ()
static AttachmentMap & attachments ()
template<class TElem , class TAttachment >
static void cast_and_attach (Grid &grid, IAttachment &attachment)
template<class TElem >
static IFunctionEntry & function_entry (const AttachmentEntry &ae)
template<class TElem >
static IFunctionEntry & function_entry (const std::string &name)
template<class TElem >
static FunctionVec & functions ()
static GlobalAttachments & inst ()
template<class TElem , class TAttachment >
static void read_attachment_from_stream (std::istream &in, Grid &grid, IAttachment &attachment)
static void register_standard_attachment_types ()
template<class TElem >
static void remove_function_entry (const AttachmentEntry &ae)
template<class TElem , class TAttachment >
static void write_attachment_to_stream (std::ostream &out, Grid &grid, IAttachment &attachment)
Private Attributes
AttachmentMap m_attachmentMap
std::vector< std::string > m_attachmentNames
AttachmentTypeMap m_attachmentTypeMap
FunctionVec m_functionVecs [4]
Detailed Description
Global attachments are automatically read/written from/to files and are considered during redistribution.
Member Typedef Documentation
AttachmentMap
typedef std::map<std::string, AttachmentEntry> ug::GlobalAttachments::AttachmentMap private
AttachmentTypeMap
typedef std::map<std::string, IAttachmentType> ug::GlobalAttachments::AttachmentTypeMap private
FunctionVec
typedef std::vector<IFunctionEntry> ug::GlobalAttachments::FunctionVec private
Constructor & Destructor Documentation
GlobalAttachments()
ug::GlobalAttachments::GlobalAttachments () inline private
~GlobalAttachments()
ug::GlobalAttachments::~GlobalAttachments () inline private
References attachments().
Member Function Documentation
add_attachment_serializer()
template<class TElem , class TAttachment > static void ug::GlobalAttachments::add_attachment_serializer (GridDataSerializationHandler & handler, Grid & g, IAttachment & attachment) inline static private
References ug::GridDataSerializationHandler::add(), attachment(), and create().
add_data_serializer()
template<class TElem > static void ug::GlobalAttachments::add_data_serializer (GridDataSerializationHandler & handler, Grid & grid, const std::string & name) inline static
References ug::GlobalAttachments::IFunctionEntry::addSerializer, ug::GlobalAttachments::AttachmentEntry::attachment, attachment_entry(), and name.
attach()
template<class TElem > static void ug::GlobalAttachments::attach (Grid & g, const std::string & name) inline static
References ug::GlobalAttachments::IFunctionEntry::attach, ug::GlobalAttachments::AttachmentEntry::attachment, attachment_entry(), and name.
attachment()
template<class TAttachment > static TAttachment ug::GlobalAttachments::attachment (const std::string & name) inline static
References ug::GlobalAttachments::AttachmentEntry::attachment, attachment_entry(), name, ug::GlobalAttachments::AttachmentEntry::type, and UG_COND_THROW.
Referenced by add_attachment_serializer(), cast_and_attach(), declare_attachment(), read_attachment_from_stream(), and write_attachment_to_stream().
attachment_entry()
static AttachmentEntry& ug::GlobalAttachments::attachment_entry (const std::string & name) inline static private
References ug::GlobalAttachments::AttachmentEntry::attachment, attachments(), name, and UG_COND_THROW.
Referenced by add_data_serializer(), attach(), attachment(), function_entry(), is_attached(), read_attachment_values(), type_name(), undeclare_attachment(), and write_attachment_values().
attachment_names()
static std::vector<std::string>& ug::GlobalAttachments::attachment_names () inline static private
References inst(), and m_attachmentNames.
Referenced by declare_attachment(), declared_attachment_names(), and undeclare_attachment().
attachment_pass_on_behaviour()
static bool ug::GlobalAttachments::attachment_pass_on_behaviour (const std::string & name) inline static
References attachments(), is_declared(), name, and UG_COND_THROW.
Referenced by ug::GridWriterUGX::process_global_attachments().
attachment_types()
static AttachmentTypeMap& ug::GlobalAttachments::attachment_types () inline static private
References inst(), m_attachmentTypeMap, and register_standard_attachment_types().
Referenced by declare_attachment(), register_attachment_type(), type_is_registered(), and undeclare_attachment().
attachments()
static AttachmentMap& ug::GlobalAttachments::attachments () inline static private
References inst(), and m_attachmentMap.
Referenced by attachment_entry(), attachment_pass_on_behaviour(), declare_attachment(), is_declared(), undeclare_attachment(), and ~GlobalAttachments().
cast_and_attach()
template<class TElem , class TAttachment > static void ug::GlobalAttachments::cast_and_attach (Grid & grid, IAttachment & attachment) inline static private
References ug::Grid::attach_to(), attachment(), and ug::Grid::has_attachment().
declare_attachment() [1/2]
template<class TAttachment > static void ug::GlobalAttachments::declare_attachment (const std::string & name, bool passOnBehaviour = false) inline static
References attachment(), attachment_names(), attachments(), name, ug::attachment_info_traits< TAttachment >::type_name(), and UG_COND_THROW.
Referenced by ug::GridReaderUGX::read_attachment().
declare_attachment() [2/2]
static void ug::GlobalAttachments::declare_attachment (const std::string & name, const std::string & typeName, bool passOnBehaviour = false) inline static
References attachment_types(), name, and UG_COND_THROW.
declared_attachment_names()
static const std::vector<std::string>& ug::GlobalAttachments::declared_attachment_names () inline static
References attachment_names().
Referenced by ug::GridWriterUGX::process_global_attachments().
function_entry() [1/2]
template<class TElem > static IFunctionEntry& ug::GlobalAttachments::function_entry (const AttachmentEntry & ae) inline static private
References ug::GlobalAttachments::AttachmentEntry::functionIndex.
function_entry() [2/2]
template<class TElem > static IFunctionEntry& ug::GlobalAttachments::function_entry (const std::string & name) inline static private
References attachment_entry(), and name.
functions()
template<class TElem > static FunctionVec& ug::GlobalAttachments::functions () inline static private
References inst(), and m_functionVecs.
inst()
static GlobalAttachments& ug::GlobalAttachments::inst () inline static private
Referenced by attachment_names(), attachment_types(), attachments(), and functions().
is_attached()
template<class TElem > static bool ug::GlobalAttachments::is_attached (Grid & g, const std::string & name) inline static
References ug::GlobalAttachments::AttachmentEntry::attachment, attachment_entry(), ug::Grid::has_attachment(), and name.
is_declared()
static bool ug::GlobalAttachments::is_declared (const std::string & name) inline static
References attachments(), and name.
Referenced by ug::RasterLayersProjector::add_attachments(), ug::NeuriteProjector::attach_surf_params(), ug::SomaProjector::attach_surf_params(), attachment_pass_on_behaviour(), ug::SomaProjector::check_attachment(), ug::NeuriteProjector::NeuriteProjector(), ug::GridReaderUGX::read_attachment(), ug::SomaProjector::SomaProjector(), and undeclare_attachment().
read_attachment_from_stream()
template<class TElem , class TAttachment > static void ug::GlobalAttachments::read_attachment_from_stream (std::istream & in, Grid & grid, IAttachment & attachment) inline static private
References ug::Grid::attach_to(), attachment(), ug::Grid::begin(), ug::Grid::end(), ug::Grid::has_attachment(), ug::attachment_io_traits< TAttachment >::read_value(), and UG_COND_THROW.
read_attachment_values()
template<class TElem > static void ug::GlobalAttachments::read_attachment_values (std::istream & in, Grid & grid, const std::string & name) inline static
References ug::GlobalAttachments::AttachmentEntry::attachment, attachment_entry(), name, and ug::GlobalAttachments::IFunctionEntry::readFunc.
register_attachment_type()
template<class TAttachment > static void ug::GlobalAttachments::register_attachment_type () inline static
References attachment_types(), and ug::attachment_info_traits< TAttachment >::type_name().
register_standard_attachment_types()
static void ug::GlobalAttachments::register_standard_attachment_types () inline static private
Referenced by attachment_types().
remove_function_entry()
template<class TElem > static void ug::GlobalAttachments::remove_function_entry (const AttachmentEntry & ae) inline static private
References ug::GlobalAttachments::AttachmentEntry::functionIndex.
type_is_registered()
static bool ug::GlobalAttachments::type_is_registered (const std::string & typeName) inline static
References attachment_types().
Referenced by ug::GridReaderUGX::read_attachment().
type_name()
static const char* ug::GlobalAttachments::type_name (const std::string & name) inline static
References attachment_entry(), name, and ug::GlobalAttachments::AttachmentEntry::type.
Referenced by ug::GridWriterUGX::process_global_attachments(), and ug::GridReaderUGX::read_attachment().
undeclare_attachment()
template<class TAttachment > static void ug::GlobalAttachments::undeclare_attachment (const std::string & name) inline static
References attachment_entry(), attachment_names(), attachment_types(), attachments(), is_declared(), name, ug::attachment_info_traits< TAttachment >::type_name(), and UG_COND_THROW.
write_attachment_to_stream()
template<class TElem , class TAttachment > static void ug::GlobalAttachments::write_attachment_to_stream (std::ostream & out, Grid & grid, IAttachment & attachment) inline static private
References attachment(), ug::Grid::begin(), ug::Grid::end(), ug::Grid::has_attachment(), UG_COND_THROW, and ug::attachment_io_traits< TAttachment >::write_value().
write_attachment_values()
template<class TElem > static void ug::GlobalAttachments::write_attachment_values (std::ostream & out, Grid & grid, const std::string & name) inline static
References ug::GlobalAttachments::AttachmentEntry::attachment, attachment_entry(), and name.
Member Data Documentation
m_attachmentMap
AttachmentMap ug::GlobalAttachments::m_attachmentMap private
Referenced by attachments().
m_attachmentNames
std::vector<std::string> ug::GlobalAttachments::m_attachmentNames private
Referenced by attachment_names().
m_attachmentTypeMap
AttachmentTypeMap ug::GlobalAttachments::m_attachmentTypeMap private
Referenced by attachment_types().
m_functionVecs
FunctionVec ug::GlobalAttachments::m_functionVecs[4] private
Referenced by functions().
The documentation for this class was generated from the following file:
ugbase/lib_grid/global_attachments.h