ug4: ug::IGridFunctionSpace< TGridFunction > Class Template Reference
ug::IGridFunctionSpace< TGridFunction > Class Template Reference abstract
Abstract base class for grid functions.
#include <metric_spaces.h>
Public Types
typedef TGridFunction grid_function_type
typedef TGridFunction::vector_type vector_type
Public Member Functions
virtual std::string config_string () const
virtual double distance (TGridFunction &x, TGridFunction &y)=0
distance (for grid functions)
virtual double distance (vector_type &x, vector_type &y)
OVERRIDE distance (for vectors)
virtual double distance2 (TGridFunction &x, TGridFunction &y)=0
virtual double norm (TGridFunction &x)=0
norm (for grid functions)
virtual double norm (vector_type &x)
OVERRIDE norm (for vectors)
virtual double norm2 (TGridFunction &x)=0
virtual double scaling () const
virtual ~IGridFunctionSpace ()
DTOR.
Public Member Functions inherited from ug::IBanachSpace< TGridFunction::vector_type >
virtual ~IBanachSpace ()
Detailed Description
template<typename TGridFunction>
class ug::IGridFunctionSpace< TGridFunction >
Abstract base class for grid functions.
Member Typedef Documentation
grid_function_type
template<typename TGridFunction > typedef TGridFunction ug::IGridFunctionSpace< TGridFunction >::grid_function_type
vector_type
template<typename TGridFunction > typedef TGridFunction::vector_type ug::IGridFunctionSpace< TGridFunction >::vector_type
Constructor & Destructor Documentation
~IGridFunctionSpace()
template<typename TGridFunction > virtual ug::IGridFunctionSpace< TGridFunction >::~IGridFunctionSpace () inline virtual
DTOR.
Member Function Documentation
config_string()
template<typename TGridFunction > virtual std::string ug::IGridFunctionSpace< TGridFunction >::config_string () const inline virtual
Reimplemented in ug::CompositeSpace< TGridFunction >, ug::TimeDependentSpace< TGridFunction >, and ug::IComponentSpace< TGridFunction >.
distance() [1/2]
template<typename TGridFunction > virtual double ug::IGridFunctionSpace< TGridFunction >::distance (TGridFunction & x, TGridFunction & y) pure virtual
distance (for grid functions)
Implemented in ug::AlgebraicSpace< TGridFunction >, ug::CompositeSpace< TGridFunction >, ug::IComponentSpace< TGridFunction >, and ug::SupErrorEvaluator< class >.
Referenced by ug::IGridFunctionSpace< TGridFunction >::distance().
distance() [2/2]
template<typename TGridFunction > virtual double ug::IGridFunctionSpace< TGridFunction >::distance (vector_type & x, vector_type & y) inline virtual
OVERRIDE distance (for vectors)
Reimplemented from ug::IBanachSpace< TGridFunction::vector_type >.
References ug::IGridFunctionSpace< TGridFunction >::distance().
distance2()
template<typename TGridFunction > virtual double ug::IGridFunctionSpace< TGridFunction >::distance2 (TGridFunction & x, TGridFunction & y) pure virtual
Implemented in ug::AlgebraicSpace< TGridFunction >, ug::IComponentSpace< TGridFunction >, ug::CompositeSpace< TGridFunction >, ug::H1ComponentSpace< TGridFunction >, ug::H1EnergyComponentSpace< TGridFunction >, ug::H1SemiComponentSpace< TGridFunction >, ug::L2QuotientSpace< TGridFunction >, ug::L2ComponentSpace< TGridFunction >, ug::GridFunctionComponentSpace< TGridFunction >, ug::SupErrorEvaluator< class >, and ug::UserDataSpace< class, class >.
norm() [1/2]
template<typename TGridFunction > virtual double ug::IGridFunctionSpace< TGridFunction >::norm (TGridFunction & x) pure virtual
norm (for grid functions)
Implemented in ug::AlgebraicSpace< TGridFunction >, ug::CompositeSpace< TGridFunction >, ug::IComponentSpace< TGridFunction >, and ug::SupErrorEvaluator< class >.
Referenced by ug::IGridFunctionSpace< TGridFunction >::norm().
norm() [2/2]
template<typename TGridFunction > virtual double ug::IGridFunctionSpace< TGridFunction >::norm (vector_type & x) inline virtual
OVERRIDE norm (for vectors)
Reimplemented from ug::IBanachSpace< TGridFunction::vector_type >.
References ug::IGridFunctionSpace< TGridFunction >::norm(), and UG_ASSERT.
norm2()
template<typename TGridFunction > virtual double ug::IGridFunctionSpace< TGridFunction >::norm2 (TGridFunction & x) pure virtual
Implemented in ug::AlgebraicSpace< TGridFunction >, ug::IComponentSpace< TGridFunction >, ug::CompositeSpace< TGridFunction >, ug::H1ComponentSpace< TGridFunction >, ug::H1EnergyComponentSpace< TGridFunction >, ug::H1SemiComponentSpace< TGridFunction >, ug::L2ComponentSpace< TGridFunction >, ug::GridFunctionComponentSpace< TGridFunction >, ug::SupErrorEvaluator< class >, ug::UserDataSpace< class, class >, and ug::L2QuotientSpace< TGridFunction >.
scaling()
template<typename TGridFunction > virtual double ug::IGridFunctionSpace< TGridFunction >::scaling () const inline virtual
Reimplemented in ug::TimeDependentSpace< TGridFunction >.
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/metric_spaces.h