ug4: ug::MathVector< N, T > Class Template Reference
ug::MathVector< N, T > Class Template Reference
ugbase » Math » Vectors
a mathematical Vector with N entries.
#include <math_vector.h>
Public Types
typedef std::size_t size_type
typedef T value_type
Public Member Functions
value_type & coord (size_t index)
value_type coord (size_t index) const
MathVector ()
MathVector (const MathVector &v)
MathVector (const value_type &val)
value_type operator* (const MathVector &v) const
MathVector & operator*= (const value_type &val)
MathVector & operator+= (const MathVector &v)
MathVector & operator+= (const value_type &val)
MathVector operator- () const
MathVector & operator-= (const MathVector &v)
MathVector & operator-= (const value_type &val)
MathVector & operator/= (const value_type &val)
MathVector & operator= (const MathVector &v)
MathVector & operator= (const value_type &val)
value_type & operator[] (size_t index)
const value_type & operator[] (size_t index) const
void set_coord (std::size_t index, value_type v)
std::size_t size () const
Static Public Member Functions
template<std::size_t fromN>
static MathVector from (const MathVector< fromN, T > &v)
Static Public Attributes
static const std::size_t Size = N
Protected Member Functions
void assign (const MathVector< N > &v)
Protected Attributes
value_type m_data [N]
Detailed Description
template<std::size_t N, typename T>
class ug::MathVector< N, T >
a mathematical Vector with N entries.
A mathematical Vector with N entries and static storage
Member Typedef Documentation
size_type
template<std::size_t N, typename T > typedef std::size_t ug::MathVector< N, T >::size_type
value_type
template<std::size_t N, typename T > typedef T ug::MathVector< N, T >::value_type
Constructor & Destructor Documentation
MathVector() [1/3]
template<std::size_t N, typename T > ug::MathVector< N, T >::MathVector () inline
References ug::MathVector< N, T >::m_data.
Referenced by ug::MathVector< 1, T >::from(), ug::MathVector< 2, T >::from(), ug::MathVector< 3, T >::from(), ug::MathVector< 4, T >::from(), and ug::MathVector< 0, T >::from().
MathVector() [2/3]
template<std::size_t N, typename T > ug::MathVector< N, T >::MathVector (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
MathVector() [3/3]
template<std::size_t N, typename T > ug::MathVector< N, T >::MathVector (const MathVector< N, T > & v) inline
References ug::MathVector< N, T >::assign().
Member Function Documentation
assign()
template<std::size_t N, typename T > void ug::MathVector< N, T >::assign (const MathVector< N > & v) inline protected
References ug::MathVector< N, T >::coord(), and ug::MathVector< N, T >::m_data.
Referenced by ug::MathVector< N, T >::MathVector(), ug::MathVector< 0, T >::MathVector(), ug::MathVector< 1, T >::MathVector(), ug::MathVector< 2, T >::MathVector(), ug::MathVector< 3, T >::MathVector(), ug::MathVector< 4, T >::MathVector(), ug::MathVector< N, T >::operator=(), ug::MathVector< 0, T >::operator=(), ug::MathVector< 1, T >::operator=(), ug::MathVector< 2, T >::operator=(), ug::MathVector< 3, T >::operator=(), and ug::MathVector< 4, T >::operator=().
coord() [1/2]
template<std::size_t N, typename T > value_type& ug::MathVector< N, T >::coord (size_t index) inline
References ug::MathVector< N, T >::m_data.
Referenced by ug::MathVector< N, T >::assign(), ug::MathVector< N, T >::operator*(), ug::MathVector< 2, T >::operator*(), ug::MathVector< 3, T >::operator*(), ug::MathVector< 4, T >::operator*(), ug::MathVector< N, T >::operator+=(), ug::MathVector< 2, T >::operator+=(), ug::MathVector< 3, T >::operator+=(), ug::MathVector< 4, T >::operator+=(), ug::MathVector< N, T >::operator-=(), ug::MathVector< 2, T >::operator-=(), ug::MathVector< 3, T >::operator-=(), ug::MathVector< 4, T >::operator-=(), ug::operator<<(), ug::read_plain_txt(), and ug::write_plain_txt().
coord() [2/2]
template<std::size_t N, typename T > value_type ug::MathVector< N, T >::coord (size_t index) const inline
References ug::MathVector< N, T >::m_data.
from()
template<std::size_t N, typename T > template<std::size_t fromN> static MathVector ug::MathVector< N, T >::from (const MathVector< fromN, T > & v) inline static
Referenced by ug::Geometry< dim, attachmentDim >::set_pos(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
operator*()
template<std::size_t N, typename T > value_type ug::MathVector< N, T >::operator* (const MathVector< N, T > & v) const inline
References ug::MathVector< N, T >::coord(), and ug::MathVector< N, T >::m_data.
operator*=()
template<std::size_t N, typename T > MathVector& ug::MathVector< N, T >::operator*= (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
operator+=() [1/2]
template<std::size_t N, typename T > MathVector& ug::MathVector< N, T >::operator+= (const MathVector< N, T > & v) inline
References ug::MathVector< N, T >::coord(), and ug::MathVector< N, T >::m_data.
operator+=() [2/2]
template<std::size_t N, typename T > MathVector& ug::MathVector< N, T >::operator+= (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
operator-()
template<std::size_t N, typename T > MathVector ug::MathVector< N, T >::operator- () const inline
References ug::MathVector< N, T >::m_data, and ug::MathVector< N, T >::set_coord().
operator-=() [1/2]
template<std::size_t N, typename T > MathVector& ug::MathVector< N, T >::operator-= (const MathVector< N, T > & v) inline
References ug::MathVector< N, T >::coord(), and ug::MathVector< N, T >::m_data.
operator-=() [2/2]
template<std::size_t N, typename T > MathVector& ug::MathVector< N, T >::operator-= (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
operator/=()
template<std::size_t N, typename T > MathVector& ug::MathVector< N, T >::operator/= (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
operator=() [1/2]
template<std::size_t N, typename T > MathVector& ug::MathVector< N, T >::operator= (const MathVector< N, T > & v) inline
References ug::MathVector< N, T >::assign().
operator=() [2/2]
template<std::size_t N, typename T > MathVector& ug::MathVector< N, T >::operator= (const value_type & val) inline
References ug::MathVector< N, T >::m_data.
operator[]() [1/2]
template<std::size_t N, typename T > value_type& ug::MathVector< N, T >::operator[] (size_t index) inline
References ug::MathVector< N, T >::m_data.
operator[]() [2/2]
template<std::size_t N, typename T > const value_type& ug::MathVector< N, T >::operator[] (size_t index) const inline
References ug::MathVector< N, T >::m_data.
set_coord()
template<std::size_t N, typename T > void ug::MathVector< N, T >::set_coord (std::size_t index, value_type v) inline
References ug::MathVector< N, T >::m_data.
Referenced by ug::MathVector< N, T >::operator-().
size()
template<std::size_t N, typename T > std::size_t ug::MathVector< N, T >::size () const inline
Referenced by ug::bp_defect_and_gradient(), ug::node_tree::CreateSubOctrees(), ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::evaluateOnThisProcessNeighbouring(), ug::IsFiniteAndNotTooBig(), ug::operator<<(), ug::operator>>(), ug::OrderDownwindForDofDist(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
Member Data Documentation
m_data
template<std::size_t N, typename T > value_type ug::MathVector< N, T >::m_data[N] protected
Referenced by ug::MathVector< 0, T >::assign(), ug::MathVector< 1, T >::assign(), ug::MathVector< 2, T >::assign(), ug::MathVector< 3, T >::assign(), ug::MathVector< 4, T >::assign(), ug::MathVector< N, T >::assign(), ug::MathVector< N, T >::coord(), ug::MathVector< 0, T >::coord(), ug::MathVector< 1, T >::coord(), ug::MathVector< 2, T >::coord(), ug::MathVector< 3, T >::coord(), ug::MathVector< 4, T >::coord(), ug::Deserialize(), ug::MathVector< N, T >::MathVector(), ug::MathVector< 1, T >::MathVector(), ug::MathVector< 2, T >::MathVector(), ug::MathVector< 3, T >::MathVector(), ug::MathVector< 4, T >::MathVector(), ug::MathVector< 0, T >::MathVector(), ug::MathVector< N, T >::operator*(), ug::MathVector< 0, T >::operator*(), ug::MathVector< 1, T >::operator*(), ug::MathVector< 2, T >::operator*(), ug::MathVector< 3, T >::operator*(), ug::MathVector< 4, T >::operator*(), ug::MathVector< N, T >::operator*=(), ug::MathVector< 0, T >::operator*=(), ug::MathVector< 1, T >::operator*=(), ug::MathVector< 2, T >::operator*=(), ug::MathVector< 3, T >::operator*=(), ug::MathVector< 4, T >::operator*=(), ug::MathVector< N, T >::operator+=(), ug::MathVector< 0, T >::operator+=(), ug::MathVector< 1, T >::operator+=(), ug::MathVector< 2, T >::operator+=(), ug::MathVector< 3, T >::operator+=(), ug::MathVector< 4, T >::operator+=(), ug::MathVector< 0, T >::operator-(), ug::MathVector< N, T >::operator-(), ug::MathVector< 1, T >::operator-(), ug::MathVector< 2, T >::operator-(), ug::MathVector< 3, T >::operator-(), ug::MathVector< 4, T >::operator-(), ug::MathVector< N, T >::operator-=(), ug::MathVector< 0, T >::operator-=(), ug::MathVector< 1, T >::operator-=(), ug::MathVector< 2, T >::operator-=(), ug::MathVector< 3, T >::operator-=(), ug::MathVector< 4, T >::operator-=(), ug::MathVector< N, T >::operator/=(), ug::MathVector< 0, T >::operator/=(), ug::MathVector< 1, T >::operator/=(), ug::MathVector< 2, T >::operator/=(), ug::MathVector< 3, T >::operator/=(), ug::MathVector< 4, T >::operator/=(), ug::MathVector< N, T >::operator=(), ug::MathVector< 0, T >::operator=(), ug::MathVector< 1, T >::operator=(), ug::MathVector< 2, T >::operator=(), ug::MathVector< 3, T >::operator=(), ug::MathVector< 4, T >::operator=(), ug::MathVector< N, T >::operator[](), ug::MathVector< 0, T >::operator[](), ug::MathVector< 1, T >::operator[](), ug::MathVector< 2, T >::operator[](), ug::MathVector< 3, T >::operator[](), ug::MathVector< 4, T >::operator[](), ug::Serialize(), ug::MathVector< N, T >::set_coord(), ug::MathVector< 0, T >::set_coord(), ug::MathVector< 1, T >::set_coord(), ug::MathVector< 2, T >::set_coord(), ug::MathVector< 3, T >::set_coord(), ug::MathVector< 4, T >::set_coord(), ug::MathVector< 4, T >::w(), ug::MathVector< 0, T >::x(), ug::MathVector< 1, T >::x(), ug::MathVector< 2, T >::x(), ug::MathVector< 3, T >::x(), ug::MathVector< 4, T >::x(), ug::MathVector< 2, T >::y(), ug::MathVector< 3, T >::y(), ug::MathVector< 4, T >::y(), ug::MathVector< 3, T >::z(), and ug::MathVector< 4, T >::z().
Size
template<std::size_t N, typename T > const std::size_t ug::MathVector< N, T >::Size = N static
Referenced by ug::MathMatrix< N, M, T >::assign().
The documentation for this class was generated from the following file:
ugbase/common/math/math_vector_matrix/math_vector.h