ug4: pcl::Reducer< T > Class Template Reference
pcl::Reducer< T > Class Template Reference
#include <pcl_reduce_traits.h>
Public Member Functions
T operator() (T v1, T v2)
T reduce (T v1, T v2)
Reducer (ReduceOperation rop)
Private Attributes
T(* m_op)(T, T)
Constructor & Destructor Documentation
Reducer()
template<class T > pcl::Reducer< T >::Reducer (ReduceOperation rop) inline
References pcl::Reducer< T >::m_op, and UG_THROW.
Member Function Documentation
operator()()
template<class T > T pcl::Reducer< T >::operator() (T v1, T v2) inline
References pcl::Reducer< T >::m_op.
reduce()
template<class T > T pcl::Reducer< T >::reduce (T v1, T v2) inline
References pcl::Reducer< T >::m_op.
Member Data Documentation
m_op
template<class T > T(* pcl::Reducer< T >::m_op) (T, T) private
Referenced by pcl::Reducer< T >::operator()(), pcl::Reducer< T >::reduce(), and pcl::Reducer< T >::Reducer().
The documentation for this class was generated from the following file:
ugbase/pcl/pcl_reduce_traits.h