ug4: ug::H1NormIntegrand< TGridFunction > Class Template Reference
ug::H1NormIntegrand< TGridFunction > Class Template Reference
#include <integrate.h>
Public Member Functions
template<int elemDim>
void evaluate (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP)
returns the values of the integrand for a bunch of ips
H1NormIntegrand (TGridFunction &gridFct, size_t cmp)
CTOR.
virtual void set_subset (int si)
sets subset
virtual ~H1NormIntegrand ()
DTOR.
Public Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, H1NormIntegrand< TGridFunction > >
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)
Public Member Functions inherited from ug::IIntegrand< TData, TWorldDim >
int subset () const
returns the subset
virtual ~IIntegrand ()
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
Static Public Attributes
static const int worldDim = TGridFunction::dim
world dimension of grid function
Static Public Attributes inherited from ug::StdIntegrand< number, TGridFunction::dim, H1NormIntegrand< TGridFunction > >
static const int worldDim
world dimension
Static Public Attributes inherited from ug::IIntegrand< TData, TWorldDim >
static const int worldDim = TWorldDim
world dimension
Private Attributes
ScalarGridFunctionData< TGridFunction > m_scalarData
Additional Inherited Members
Public Types inherited from ug::StdIntegrand< number, TGridFunction::dim, H1NormIntegrand< TGridFunction > >
typedef number data_type
data type
Public Types inherited from ug::IIntegrand< TData, TWorldDim >
typedef TData data_type
data type
Protected Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, H1NormIntegrand< TGridFunction > >
H1NormIntegrand< TGridFunction > & getImpl ()
access to implementation
const H1NormIntegrand< TGridFunction > & getImpl () const
const access to implementation
Protected Attributes inherited from ug::IIntegrand< TData, TWorldDim >
int m_si
subset
Constructor & Destructor Documentation
H1NormIntegrand()
template<typename TGridFunction > ug::H1NormIntegrand< TGridFunction >::H1NormIntegrand (TGridFunction & gridFct, size_t cmp) inline
CTOR.
~H1NormIntegrand()
template<typename TGridFunction > virtual ug::H1NormIntegrand< TGridFunction >::~H1NormIntegrand () inline virtual
DTOR.
Member Function Documentation
evaluate()
template<typename TGridFunction > template<int elemDim> void ug::H1NormIntegrand< TGridFunction >::evaluate (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject * pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP) inline
returns the values of the integrand for a bunch of ips
Parameters
vValue[out] the value of the integrand at the ips
vGlobIP[in] global integration point positions
pElem[in] the element to integrate
vCornerCoords[in] corner coordinates of the element
vLocIP[in] local integration point positions
vJT[in] jacobian transposed at integration point
numIP[in] number of integration points
References ug::DoFRef(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::H1NormIntegrand< TGridFunction >::m_scalarData, ug::MatVecMult(), ug::LocalDoFSet::num_sh(), ug::GridObject::reference_object_id(), ug::RightInverse(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shape(), UG_CATCH_THROW, UG_THROW, ug::VecDot(), ug::VecScaleAppend(), and ug::VecSet().
set_subset()
template<typename TGridFunction > virtual void ug::H1NormIntegrand< TGridFunction >::set_subset (int si) inline virtual
sets subset
Reimplemented from ug::IIntegrand< TData, TWorldDim >.
References ug::H1NormIntegrand< TGridFunction >::m_scalarData, ug::IIntegrand< TData, TWorldDim >::set_subset(), and UG_THROW.
Member Data Documentation
m_scalarData
template<typename TGridFunction > ScalarGridFunctionData<TGridFunction> ug::H1NormIntegrand< TGridFunction >::m_scalarData private
Referenced by ug::H1NormIntegrand< TGridFunction >::evaluate(), and ug::H1NormIntegrand< TGridFunction >::set_subset().
worldDim
template<typename TGridFunction > const int ug::H1NormIntegrand< TGridFunction >::worldDim = TGridFunction::dim static
world dimension of grid function
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/integrate.h