ug4: ug::IConvergenceCheck< TVector > Class Template Reference
ug::IConvergenceCheck< TVector > Class Template Reference abstract
#include <convergence_check.h>
Public Member Functions
virtual number avg_rate () const =0
virtual SmartPtr< IConvergenceCheck< TVector > > clone ()=0
clone the object
virtual std::string config_string () const =0
returns information about configuration parameters
virtual number defect () const =0
returns the current defect
virtual int get_offset () const =0
get the current offset
virtual bool iteration_ended ()=0
virtual bool post ()=0
virtual void print_line (std::string line)=0
prints a line
virtual number rate () const =0
virtual number reduction () const =0
virtual void set_info (std::string name)=0
sets info string
virtual void set_name (std::string name)=0
sets the name of the iteration
virtual void set_offset (int offset)=0
sets the number of spaces printed before output information
virtual void set_symbol (char symbol)=0
sets the symbol used for output
virtual void start (const TVector &d)=0
computes the start defect and set it
virtual void start_defect (number defect)=0
sets the given start defect
virtual int step () const =0
returns the current number of steps
virtual void update (const TVector &d)=0
computes the defect and sets it a the next defect value
virtual void update_defect (number defect)=0
sets the update for the current defect
virtual ~IConvergenceCheck ()
virtual destructor
Detailed Description
template<typename TVector>
class ug::IConvergenceCheck< TVector >
IConvergenceCheck
This is the base class for a convergence checking object. An instance is passed to an iterative solver to control the convergence.
Template Parameters
TVector vector type
Constructor & Destructor Documentation
template<typename TVector> virtual ug::IConvergenceCheck< TVector >::~IConvergenceCheck () inline virtual
virtual destructor
Member Function Documentation
template<typename TVector> virtual number ug::IConvergenceCheck< TVector >::avg_rate () const pure virtual
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
template<typename TVector> virtual SmartPtr<IConvergenceCheck<TVector> > ug::IConvergenceCheck< TVector >::clone () pure virtual
clone the object
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, ug::AlgebraicConvCheck< TVector >, and ug::EnergyConvCheck< TVector >.
template<typename TVector> virtual std::string ug::IConvergenceCheck< TVector >::config_string () const pure virtual
returns information about configuration parameters
this should return necessary information about parameters and possibly calling config_string of subcomponents.
Returns
std::string necessary information about configuration parameters
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, ug::EnergyConvCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
Referenced by ug::IConvergenceCheck< X >::~IConvergenceCheck().
template<typename TVector> virtual number ug::IConvergenceCheck< TVector >::defect () const pure virtual
returns the current defect
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
template<typename TVector> virtual int ug::IConvergenceCheck< TVector >::get_offset () const pure virtual
get the current offset
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
template<typename TVector> virtual bool ug::IConvergenceCheck< TVector >::iteration_ended () pure virtual
iteration_ended
Checks if the iteration must be ended. This can be due to convergence or divergence.
Returns
true if iteration ended false if iteration can and must be continued until convergence
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::AlgebraicConvCheck< TVector >, and ug::FixedConvergenceCheck< TVector >.
Referenced by ug::StdConvCheck< TVector >::set_supress_unsuccessful().
template<typename TVector> virtual bool ug::IConvergenceCheck< TVector >::post () pure virtual
post
post-processes the iteration. Some informative outputs of the status of the iteration after finishing the iteration can be placed here
Returns
true if iteration was successful false if iteration did not lead to a satisfying result
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
Referenced by ug::StdConvCheck< TVector >::set_supress_unsuccessful().
template<typename TVector> virtual void ug::IConvergenceCheck< TVector >::print_line (std::string line) pure virtual
prints a line
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::AlgebraicConvCheck< TVector >, and ug::FixedConvergenceCheck< TVector >.
Referenced by ug::StdConvCheck< TVector >::get_defects().
template<typename TVector> virtual number ug::IConvergenceCheck< TVector >::rate () const pure virtual
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
template<typename TVector> virtual number ug::IConvergenceCheck< TVector >::reduction () const pure virtual
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
template<typename TVector> virtual void ug::IConvergenceCheck< TVector >::set_info (std::string name) pure virtual
sets info string
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
template<typename TVector> virtual void ug::IConvergenceCheck< TVector >::set_name (std::string name) pure virtual
sets the name of the iteration
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
template<typename TVector> virtual void ug::IConvergenceCheck< TVector >::set_offset (int offset) pure virtual
sets the number of spaces printed before output information
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
template<typename TVector> virtual void ug::IConvergenceCheck< TVector >::set_symbol (char symbol) pure virtual
sets the symbol used for output
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
template<typename TVector> virtual void ug::IConvergenceCheck< TVector >::start (const TVector & d) pure virtual
computes the start defect and set it
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::AlgebraicConvCheck< TVector >, ug::EnergyConvCheck< TVector >, and ug::FixedConvergenceCheck< TVector >.
Referenced by ug::StdConvCheck< TVector >::set_supress_unsuccessful().
template<typename TVector> virtual void ug::IConvergenceCheck< TVector >::start_defect (number defect) pure virtual
sets the given start defect
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::AlgebraicConvCheck< TVector >, and ug::FixedConvergenceCheck< TVector >.
Referenced by ug::StdConvCheck< TVector >::set_supress_unsuccessful().
template<typename TVector> virtual int ug::IConvergenceCheck< TVector >::step () const pure virtual
returns the current number of steps
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::FixedConvergenceCheck< TVector >, and ug::AlgebraicConvCheck< TVector >.
Referenced by ug::StdConvCheck< TVector >::avg_rate().
template<typename TVector> virtual void ug::IConvergenceCheck< TVector >::update (const TVector & d) pure virtual
computes the defect and sets it a the next defect value
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::AlgebraicConvCheck< TVector >, ug::FixedConvergenceCheck< TVector >, and ug::EnergyConvCheck< TVector >.
Referenced by ug::StdConvCheck< TVector >::set_supress_unsuccessful().
template<typename TVector> virtual void ug::IConvergenceCheck< TVector >::update_defect (number defect) pure virtual
sets the update for the current defect
Implemented in ug::StdConvCheck< TVector >, ug::CompositeConvCheck< TVector, TDomain >, ug::AlgebraicConvCheck< TVector >, and ug::FixedConvergenceCheck< TVector >.
Referenced by ug::StdConvCheck< TVector >::set_supress_unsuccessful().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/convergence_check.h