ug4: ug::IDomainDiscretization< TAlgebra > Class Template Reference
ug::IDomainDiscretization< TAlgebra > Class Template Reference abstract
Interface for domain disretization.
#include <domain_disc_interface.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef algebra_type::matrix_type matrix_type
Type of algebra matrix.
typedef algebra_type::vector_type vector_type
Type of algebra vector.
Public Types inherited from ug::IAssemble< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef TAlgebra::matrix_type matrix_type
Type of algebra matrix.
typedef TAlgebra::vector_type vector_type
Type of algebra vector.
Public Member Functions
virtual void adjust_solution (vector_type &u, const GridLevel &gl)=0
sets dirichlet values in solution vector
virtual void adjust_solution (vector_type &u, ConstSmartPtr< DoFDistribution > dd)=0
virtual void adjust_solution (vector_type &u, number time, const GridLevel &gl)=0
sets dirichlet values in solution vector
virtual void adjust_solution (vector_type &u, number time, ConstSmartPtr< DoFDistribution > dd)=0
void adjust_solution (vector_type &u, number time)
adjust solution on surface level
virtual void assemble_defect (vector_type &d, const vector_type &u, const GridLevel &gl)=0
assembles Defect
virtual void assemble_defect (vector_type &d, const vector_type &u, ConstSmartPtr< DoFDistribution > dd)=0
virtual void assemble_defect (vector_type &d, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff, const GridLevel &gl)=0
assembles Defect
virtual void assemble_defect (vector_type &d, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff, ConstSmartPtr< DoFDistribution > dd)=0
void assemble_defect (vector_type &d, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
assembles defect on surface level
virtual void assemble_jacobian (matrix_type &J, const vector_type &u, const GridLevel &gl)=0
assembles Jacobian (or Approximation of Jacobian)
virtual void assemble_jacobian (matrix_type &J, const vector_type &u, ConstSmartPtr< DoFDistribution > dd)=0
virtual void assemble_jacobian (matrix_type &J, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const number s_a, const GridLevel &gl)=0
assembles Jacobian (or Approximation of Jacobian)
virtual void assemble_jacobian (matrix_type &J, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const number s_a0, ConstSmartPtr< DoFDistribution > dd)=0
void assemble_jacobian (matrix_type &J, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const number s_a)
assembles jacobian on surface level
virtual void assemble_linear (matrix_type &A, vector_type &b, const GridLevel &gl)=0
Assembles Matrix and Right-Hand-Side for a linear problem.
virtual void assemble_linear (matrix_type &A, vector_type &b, ConstSmartPtr< DoFDistribution > dd)=0
virtual void assemble_linear (matrix_type &A, vector_type &b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff, const GridLevel &gl)=0
Assembles matrix_type and Right-Hand-Side for a linear problem.
virtual void assemble_linear (matrix_type &A, vector_type &b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff, ConstSmartPtr< DoFDistribution > dd)=0
void assemble_linear (matrix_type &A, vector_type &b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
assembles linear on surface level
virtual void assemble_mass_matrix (matrix_type &M, const vector_type &u, const GridLevel &gl)=0
assembles the mass matrix
virtual void assemble_mass_matrix (matrix_type &M, const vector_type &u, ConstSmartPtr< DoFDistribution > dd)=0
virtual void assemble_rhs (vector_type &rhs, const vector_type &u, const GridLevel &gl)=0
assembles the rhs
virtual void assemble_rhs (vector_type &rhs, const vector_type &u, ConstSmartPtr< DoFDistribution > dd)=0
virtual void assemble_rhs (vector_type &b, const GridLevel &gl)=0
assembles the rhs
virtual void assemble_rhs (vector_type &b, ConstSmartPtr< DoFDistribution > dd)=0
virtual void assemble_rhs (vector_type &b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff, const GridLevel &gl)=0
Assembles Right-Hand-Side for a linear problem.
virtual void assemble_rhs (vector_type &b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff, ConstSmartPtr< DoFDistribution > dd)=0
void assemble_rhs (vector_type &b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
assembles rhs on surface level
virtual void assemble_stiffness_matrix (matrix_type &A, const vector_type &u, const GridLevel &gl)=0
assembles the stiffness matrix
virtual void assemble_stiffness_matrix (matrix_type &A, const vector_type &u, ConstSmartPtr< DoFDistribution > dd)=0
virtual void calc_error (const vector_type &u, const GridLevel &gl, vector_type *u_vtk=NULL)=0
computes the error estimator
virtual void calc_error (const vector_type &u, ConstSmartPtr< DoFDistribution > dd, vector_type *u_vtk=NULL)=0
virtual void calc_error (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd, std::vector< number > vScaleMass, std::vector< number > vScaleStiff, vector_type *u_vtk)=0
virtual void calc_error (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, std::vector< number > vScaleMass, std::vector< number > vScaleStiff, const GridLevel &gl, vector_type *u_vtk)=0
virtual SmartPtr< IConstraint< TAlgebra > > constraint (size_t i)=0
returns the i'th post process
virtual void finish_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd)=0
finishes time step
virtual void finish_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const GridLevel &gl)=0
virtual void finish_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol)
virtual void finish_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const GridLevel &gl)=0
finishes timestep
virtual void finish_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd)=0
void finish_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol)
finishes timestep on surface level
virtual void invalidate_error ()=0
marks error indicators as invalid
virtual bool is_error_valid ()=0
returns whether current error values are valid
virtual void mark_for_coarsening (IRefiner &refiner, number TOL, number coarseFrac, int maxLevel)=0
marks elements for coarsening
virtual void mark_for_refinement (IRefiner &refiner, number TOL, number refineFrac, int maxLevel)=0
marks elements for refinement
virtual size_t num_constraints () const =0
returns the number of post processes
virtual void prepare_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd)=0
prepares time step
virtual void prepare_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const GridLevel &gl)=0
virtual void prepare_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol)
virtual void prepare_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd)=0
prepares time step element-wise
virtual void prepare_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const GridLevel &gl)=0
void prepare_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol)
prepares timestep on surface level
virtual ~IDomainDiscretization ()
Public Member Functions inherited from ug::IAssemble< TAlgebra >
void adjust_solution (vector_type &u)
void assemble_defect (vector_type &d, const vector_type &u)
void assemble_jacobian (matrix_type &J, const vector_type &u)
void assemble_linear (matrix_type &A, vector_type &b)
void assemble_mass_matrix (matrix_type &M, const vector_type &u)
virtual void assemble_rhs (vector_type &rhs, const vector_type &u)
void assemble_rhs (vector_type &b)
void assemble_stiffness_matrix (matrix_type &A, const vector_type &u)
virtual ~IAssemble ()
Virtual Destructor.
virtual SmartPtr< AssemblingTuner< TAlgebra > > ass_tuner ()=0
virtual ConstSmartPtr< AssemblingTuner< TAlgebra > > ass_tuner () const =0
Detailed Description
template<typename TAlgebra>
class ug::IDomainDiscretization< TAlgebra >
Interface for domain disretization.
This class is the interface for spatial discretizations. It can be used in the stationary case as well as for the domain dependent part of an instationary problem (i.e. inside ITimeDiscretization).
By its structure it is convenient to implement element-wise Mass-Matrix and Stiffness-Matrix. Then the time-independent member functions can call only the Stiffness-Matrix assembling, while the time-dependent part can call Mass- and Stiffness-Matrix assembling.
Template Parameters
TAlgebra Algebra Type
Member Typedef Documentation
template<typename TAlgebra > typedef TAlgebra ug::IDomainDiscretization< TAlgebra >::algebra_type
Algebra type.
template<typename TAlgebra > typedef algebra_type::matrix_type ug::IDomainDiscretization< TAlgebra >::matrix_type
Type of algebra matrix.
template<typename TAlgebra > typedef algebra_type::vector_type ug::IDomainDiscretization< TAlgebra >::vector_type
Type of algebra vector.
Constructor & Destructor Documentation
template<typename TAlgebra > virtual ug::IDomainDiscretization< TAlgebra >::~IDomainDiscretization () inline virtual
References ug::IDomainDiscretization< TAlgebra >::adjust_solution(), ug::IDomainDiscretization< TAlgebra >::assemble_defect(), ug::IDomainDiscretization< TAlgebra >::assemble_jacobian(), ug::IDomainDiscretization< TAlgebra >::assemble_linear(), ug::IDomainDiscretization< TAlgebra >::assemble_mass_matrix(), ug::IDomainDiscretization< TAlgebra >::assemble_rhs(), ug::IDomainDiscretization< TAlgebra >::assemble_stiffness_matrix(), and ug::IDomainDiscretization< TAlgebra >::prepare_timestep().
Member Function Documentation
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::adjust_solution (vector_type & u, const GridLevel & gl) pure virtual
sets dirichlet values in solution vector
Sets dirichlet values of the NumericalSolution u when components are dirichlet
Parameters
[out] u Numerical Solution
[in] dd DoF Distribution
Implements ug::IAssemble< TAlgebra >.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::adjust_solution(), ug::IDomainDiscretization< TAlgebra >::assemble_rhs(), and ug::IDomainDiscretization< TAlgebra >::~IDomainDiscretization().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::adjust_solution (vector_type & u, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::adjust_solution (vector_type & u, number time, const GridLevel & gl) pure virtual
sets dirichlet values in solution vector
Sets dirichlet values of the Solution u when components are dirichlet
Parameters
[in] u Solution to set values at
[in] time time of next (to be computed) timestep
[in] dd DoF Distribution
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::adjust_solution (vector_type & u, number time, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > void ug::IDomainDiscretization< TAlgebra >::adjust_solution (vector_type & u, number time) inline
adjust solution on surface level
References ug::IDomainDiscretization< TAlgebra >::adjust_solution(), and ug::IDomainDiscretization< TAlgebra >::finish_timestep().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_defect (vector_type & d, const vector_type & u, const GridLevel & gl) pure virtual
assembles Defect
Assembles Defect at a given Solution u.
Parameters
[out] d Defect d(u) to be filled
[in] u Current iterate
[in] dd DoF Distribution
Implements ug::IAssemble< TAlgebra >.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::assemble_defect(), ug::IDomainDiscretization< TAlgebra >::assemble_jacobian(), and ug::IDomainDiscretization< TAlgebra >::~IDomainDiscretization().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_defect (vector_type & d, const vector_type & u, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_defect (vector_type & d, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > & vScaleMass, const std::vector< number > & vScaleStiff, const GridLevel & gl) pure virtual
assembles Defect
Assembles Defect at a given Solution u.
Parameters
[out] d Defect d(u) to be filled
[in] vSol vector of previous and current (iterated) solution
[in] vScaleMass scaling factors for mass matrix
[in] vScaleStiff scaling factors for stiffness matrix
[in] dd DoF Distribution
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_defect (vector_type & d, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > & vScaleMass, const std::vector< number > & vScaleStiff, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > void ug::IDomainDiscretization< TAlgebra >::assemble_defect (vector_type & d, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > & vScaleMass, const std::vector< number > & vScaleStiff) inline
assembles defect on surface level
References ug::IDomainDiscretization< TAlgebra >::assemble_defect(), and ug::IDomainDiscretization< TAlgebra >::assemble_linear().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_jacobian (matrix_type & J, const vector_type & u, const GridLevel & gl) pure virtual
assembles Jacobian (or Approximation of Jacobian)
Assembles Jacobian at a given iterate u.
Parameters
[out] J Jacobian J(u) matrix to be filled
[in] u Current iterate
[in] dd DoF Distribution
Implements ug::IAssemble< TAlgebra >.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::assemble_jacobian(), ug::IDomainDiscretization< TAlgebra >::prepare_timestep_elem(), and ug::IDomainDiscretization< TAlgebra >::~IDomainDiscretization().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_jacobian (matrix_type & J, const vector_type & u, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_jacobian (matrix_type & J, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const number s_a, const GridLevel & gl) pure virtual
assembles Jacobian (or Approximation of Jacobian)
Assembles Jacobian at a given Solution u.
Parameters
[out] J Jacobian J(u) Matrix to be filled
[in] vSol vector of previous and current (iterated) solution
[in] s_a scaling factors for mass matrix
[in] dd DoF Distribution
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_jacobian (matrix_type & J, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const number s_a0, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > void ug::IDomainDiscretization< TAlgebra >::assemble_jacobian (matrix_type & J, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const number s_a) inline
assembles jacobian on surface level
References ug::IDomainDiscretization< TAlgebra >::assemble_defect(), and ug::IDomainDiscretization< TAlgebra >::assemble_jacobian().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_linear (matrix_type & A, vector_type & b, const GridLevel & gl) pure virtual
Assembles Matrix and Right-Hand-Side for a linear problem.
Assembles matrix_type and Right-Hand-Side for a linear problem
Parameters
[out] A Mass-/Stiffness- Matrix
[out] b Right-Hand-Side
[in] dd DoF Distribution
Implements ug::IAssemble< TAlgebra >.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::assemble_defect(), ug::IDomainDiscretization< TAlgebra >::assemble_linear(), and ug::IDomainDiscretization< TAlgebra >::~IDomainDiscretization().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_linear (matrix_type & A, vector_type & b, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_linear (matrix_type & A, vector_type & b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > & vScaleMass, const std::vector< number > & vScaleStiff, const GridLevel & gl) pure virtual
Assembles matrix_type and Right-Hand-Side for a linear problem.
Assembles matrix_type and Right-Hand-Side for a linear problem
Parameters
[out] A Mass-/Stiffness- matrix_type of the discretization
[out] b Right-Hand-Side of the discretization
[in] vSol vector of previous and current (iterated) solution
[in] vScaleMass scaling factors for mass matrix
[in] vScaleStiff scaling factors for stiffness matrix
[in] dd DoF Distribution
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_linear (matrix_type & A, vector_type & b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > & vScaleMass, const std::vector< number > & vScaleStiff, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > void ug::IDomainDiscretization< TAlgebra >::assemble_linear (matrix_type & A, vector_type & b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > & vScaleMass, const std::vector< number > & vScaleStiff) inline
assembles linear on surface level
References ug::IDomainDiscretization< TAlgebra >::assemble_linear(), and ug::IDomainDiscretization< TAlgebra >::assemble_rhs().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_mass_matrix (matrix_type & M, const vector_type & u, const GridLevel & gl) pure virtual
assembles the mass matrix
Reimplemented from ug::IAssemble< TAlgebra >.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::~IDomainDiscretization().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_mass_matrix (matrix_type & M, const vector_type & u, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_rhs (vector_type & rhs, const vector_type & u, const GridLevel & gl) pure virtual
assembles the rhs
Implements ug::IAssemble< TAlgebra >.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::assemble_linear(), ug::IDomainDiscretization< TAlgebra >::assemble_rhs(), and ug::IDomainDiscretization< TAlgebra >::~IDomainDiscretization().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_rhs (vector_type & rhs, const vector_type & u, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_rhs (vector_type & b, const GridLevel & gl) pure virtual
assembles the rhs
Implements ug::IAssemble< TAlgebra >.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_rhs (vector_type & b, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_rhs (vector_type & b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > & vScaleMass, const std::vector< number > & vScaleStiff, const GridLevel & gl) pure virtual
Assembles Right-Hand-Side for a linear problem.
Assembles Right-Hand-Side for a linear problem
Parameters
[out] b Right-Hand-Side of the discretization
[in] vSol vector of previous and current (iterated) solution
[in] vScaleMass scaling factors for mass matrix
[in] vScaleStiff scaling factors for stiffness matrix
[in] dd DoF Distribution
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_rhs (vector_type & b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > & vScaleMass, const std::vector< number > & vScaleStiff, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > void ug::IDomainDiscretization< TAlgebra >::assemble_rhs (vector_type & b, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const std::vector< number > & vScaleMass, const std::vector< number > & vScaleStiff) inline
assembles rhs on surface level
References ug::IDomainDiscretization< TAlgebra >::adjust_solution(), and ug::IDomainDiscretization< TAlgebra >::assemble_rhs().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_stiffness_matrix (matrix_type & A, const vector_type & u, const GridLevel & gl) pure virtual
assembles the stiffness matrix
Reimplemented from ug::IAssemble< TAlgebra >.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::~IDomainDiscretization().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::assemble_stiffness_matrix (matrix_type & A, const vector_type & u, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::calc_error (const vector_type & u, const GridLevel & gl, vector_type * u_vtk = NULL) pure virtual
computes the error estimator
Computes the error estimator.
Parameters
[in] u vector of the solution to estimate the error for
[in] dd DoF Distribution
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::calc_error (const vector_type & u, ConstSmartPtr< DoFDistribution > dd, vector_type * u_vtk = NULL) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::calc_error (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd, std::vector< number > vScaleMass, std::vector< number > vScaleStiff, vector_type * u_vtk) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::calc_error (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, std::vector< number > vScaleMass, std::vector< number > vScaleStiff, const GridLevel & gl, vector_type * u_vtk) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual SmartPtr<IConstraint<TAlgebra> > ug::IDomainDiscretization< TAlgebra >::constraint (size_t i) pure virtual
returns the i'th post process
Implements ug::IAssemble< TAlgebra >.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::finish_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd) pure virtual
finishes time step
Finishes time step at a given solution u. This method is called only once after any time step.
Parameters
[in] vSol vector of previous and current (iterated) solution
[in] dd DoF distribution
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::adjust_solution(), and ug::IDomainDiscretization< TAlgebra >::finish_timestep().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::finish_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const GridLevel & gl) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::finish_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol) inline virtual
References ug::IDomainDiscretization< TAlgebra >::finish_timestep(), and ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const GridLevel & gl) pure virtual
finishes timestep
finishes timestep at a given Solution u.
Parameters
[in] vSol vector of previous and current (iterated) solution
[in] dd DoF Distribution
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::finish_timestep(), and ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > void ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol) inline
finishes timestep on surface level
References ug::IDomainDiscretization< TAlgebra >::calc_error(), ug::IDomainDiscretization< TAlgebra >::constraint(), ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem(), ug::IDomainDiscretization< TAlgebra >::invalidate_error(), ug::IDomainDiscretization< TAlgebra >::is_error_valid(), ug::IDomainDiscretization< TAlgebra >::mark_for_coarsening(), ug::IDomainDiscretization< TAlgebra >::mark_for_refinement(), and ug::IDomainDiscretization< TAlgebra >::num_constraints().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::invalidate_error () pure virtual
marks error indicators as invalid
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem().
template<typename TAlgebra > virtual bool ug::IDomainDiscretization< TAlgebra >::is_error_valid () pure virtual
returns whether current error values are valid
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::mark_for_coarsening (IRefiner & refiner, number TOL, number coarseFrac, int maxLevel) pure virtual
marks elements for coarsening
Marks elements for coarsening.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::mark_for_refinement (IRefiner & refiner, number TOL, number refineFrac, int maxLevel) pure virtual
marks elements for refinement
Marks elements for refinement.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem().
template<typename TAlgebra > virtual size_t ug::IDomainDiscretization< TAlgebra >::num_constraints () const pure virtual
returns the number of post processes
Implements ug::IAssemble< TAlgebra >.
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::finish_timestep_elem().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::prepare_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd) pure virtual
prepares time step
Prepares time step at a given solution u. This method is called only once before any time step.
Parameters
[in] vSol vector of previous and current (iterated) solution
[in] dd DoF distribution
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::prepare_timestep(), and ug::IDomainDiscretization< TAlgebra >::~IDomainDiscretization().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::prepare_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const GridLevel & gl) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::prepare_timestep (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol) inline virtual
References ug::IDomainDiscretization< TAlgebra >::prepare_timestep(), and ug::IDomainDiscretization< TAlgebra >::prepare_timestep_elem().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::prepare_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd) pure virtual
prepares time step element-wise
prepares time step element-wise at a given solution u.
Parameters
[in] vSol vector of previous and current (iterated) solution
[in] dd DoF Distribution
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainDiscretization< TAlgebra >::prepare_timestep(), and ug::IDomainDiscretization< TAlgebra >::prepare_timestep_elem().
template<typename TAlgebra > virtual void ug::IDomainDiscretization< TAlgebra >::prepare_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, const GridLevel & gl) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
template<typename TAlgebra > void ug::IDomainDiscretization< TAlgebra >::prepare_timestep_elem (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol) inline
prepares timestep on surface level
References ug::IDomainDiscretization< TAlgebra >::assemble_jacobian(), and ug::IDomainDiscretization< TAlgebra >::prepare_timestep_elem().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/domain_disc_interface.h