ug4: ug::ClusterElementStacks< elem_t, vector_t > Class Template Reference
ug::ClusterElementStacks< elem_t, vector_t > Class Template Reference
#include <cluster_element_stacks.h>
Public Member Functions
ClusterElementStacks ()
ClusterElementStacks (const Attachment< vector_t > &aPos, const vector_t &stackingDir)
void init_post_processing (MultiGrid *mg, SubsetHandler *partitions)
void partitioning_done ()
void post_process (int partitionLvl)
void set_position_attachment (const Attachment< vector_t > &aPos)
void set_stacking_direction (const vector_t &stackingDir)
virtual ~ClusterElementStacks ()
Public Member Functions inherited from ug::IPartitionPostProcessor
virtual ~IPartitionPostProcessor ()
Private Types
typedef Attachment< vector_t > a_position_t
typedef elem_t::side side_t
Private Attributes
a_position_t m_aPos
ABool m_aProcessed
MultiGrid * m_mg
SubsetHandler * m_partitions
vector_t m_stackingDir
Member Typedef Documentation
a_position_t
template<class elem_t , class vector_t > typedef Attachment<vector_t> ug::ClusterElementStacks< elem_t, vector_t >::a_position_t private
side_t
template<class elem_t , class vector_t > typedef elem_t::side ug::ClusterElementStacks< elem_t, vector_t >::side_t private
Constructor & Destructor Documentation
ClusterElementStacks() [1/2]
template<class elem_t , class vector_t > ug::ClusterElementStacks< elem_t, vector_t >::ClusterElementStacks () inline
References ug::ClusterElementStacks< elem_t, vector_t >::m_stackingDir, and ug::VecSet().
ClusterElementStacks() [2/2]
template<class elem_t , class vector_t > ug::ClusterElementStacks< elem_t, vector_t >::ClusterElementStacks (const Attachment< vector_t > & aPos, const vector_t & stackingDir) inline
~ClusterElementStacks()
template<class elem_t , class vector_t > virtual ug::ClusterElementStacks< elem_t, vector_t >::~ClusterElementStacks () inline virtual
Member Function Documentation
init_post_processing()
template<class elem_t , class vector_t > void ug::ClusterElementStacks< elem_t, vector_t >::init_post_processing (MultiGrid * mg, SubsetHandler * partitions) inline virtual
Implements ug::IPartitionPostProcessor.
References ug::Grid::attach_to(), ug::ClusterElementStacks< elem_t, vector_t >::m_aProcessed, ug::ClusterElementStacks< elem_t, vector_t >::m_mg, and ug::ClusterElementStacks< elem_t, vector_t >::m_partitions.
partitioning_done()
template<class elem_t , class vector_t > void ug::ClusterElementStacks< elem_t, vector_t >::partitioning_done () inline virtual
Implements ug::IPartitionPostProcessor.
References ug::Grid::detach_from(), ug::ClusterElementStacks< elem_t, vector_t >::m_aProcessed, and ug::ClusterElementStacks< elem_t, vector_t >::m_mg.
post_process()
template<class elem_t , class vector_t > void ug::ClusterElementStacks< elem_t, vector_t >::post_process (int partitionLvl) inline virtual
Implements ug::IPartitionPostProcessor.
References ug::GridSubsetHandler::assign_subset(), ug::Grid::associated_elements(), ug::MultiGrid::begin(), ug::CalculateNormal(), ug::MultiGrid::end(), end_for, for_each_in_vec, ug::ISubsetHandler::get_subset_index(), ug::Grid::has_vertex_attachment(), lg_end_for, lg_for_each_in_lvl_template, ug::ClusterElementStacks< elem_t, vector_t >::m_aPos, ug::ClusterElementStacks< elem_t, vector_t >::m_aProcessed, ug::ClusterElementStacks< elem_t, vector_t >::m_mg, ug::ClusterElementStacks< elem_t, vector_t >::m_partitions, ug::ClusterElementStacks< elem_t, vector_t >::m_stackingDir, s, ug::SetAttachmentValues(), ug::SMALL, UG_COND_THROW, ug::VecDot(), ug::VecLengthSq(), and ug::VecNormalize().
set_position_attachment()
template<class elem_t , class vector_t > void ug::ClusterElementStacks< elem_t, vector_t >::set_position_attachment (const Attachment< vector_t > & aPos) inline
References ug::ClusterElementStacks< elem_t, vector_t >::m_aPos.
set_stacking_direction()
template<class elem_t , class vector_t > void ug::ClusterElementStacks< elem_t, vector_t >::set_stacking_direction (const vector_t & stackingDir) inline
References ug::ClusterElementStacks< elem_t, vector_t >::m_stackingDir.
Member Data Documentation
m_aPos
template<class elem_t , class vector_t > a_position_t ug::ClusterElementStacks< elem_t, vector_t >::m_aPos private
Referenced by ug::ClusterElementStacks< elem_t, vector_t >::post_process(), and ug::ClusterElementStacks< elem_t, vector_t >::set_position_attachment().
m_aProcessed
template<class elem_t , class vector_t > ABool ug::ClusterElementStacks< elem_t, vector_t >::m_aProcessed private
Referenced by ug::ClusterElementStacks< elem_t, vector_t >::init_post_processing(), ug::ClusterElementStacks< elem_t, vector_t >::partitioning_done(), and ug::ClusterElementStacks< elem_t, vector_t >::post_process().
m_mg
template<class elem_t , class vector_t > MultiGrid* ug::ClusterElementStacks< elem_t, vector_t >::m_mg private
Referenced by ug::ClusterElementStacks< elem_t, vector_t >::init_post_processing(), ug::ClusterElementStacks< elem_t, vector_t >::partitioning_done(), and ug::ClusterElementStacks< elem_t, vector_t >::post_process().
m_partitions
template<class elem_t , class vector_t > SubsetHandler* ug::ClusterElementStacks< elem_t, vector_t >::m_partitions private
Referenced by ug::ClusterElementStacks< elem_t, vector_t >::init_post_processing(), and ug::ClusterElementStacks< elem_t, vector_t >::post_process().
m_stackingDir
template<class elem_t , class vector_t > vector_t ug::ClusterElementStacks< elem_t, vector_t >::m_stackingDir private
Referenced by ug::ClusterElementStacks< elem_t, vector_t >::ClusterElementStacks(), ug::ClusterElementStacks< elem_t, vector_t >::post_process(), and ug::ClusterElementStacks< elem_t, vector_t >::set_stacking_direction().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/partition_post_processors/cluster_element_stacks.h