ug4: pcl::IDomainDecompositionInfo Class Reference
pcl::IDomainDecompositionInfo Class Reference abstract
ugbase » PCL
#include <pcl_domain_decomposition.h>
Public Member Functions
virtual int get_num_spatial_dimensions () const =0
virtual int get_num_subdomains () const =0
virtual void get_subdomain_procs (std::vector< int > &procsOut, int subdomIndex)=0
virtual int map_proc_id_to_subdomain_id (int procID) const =0
mapping method "proc-id" ==> "subdomain-id"
virtual ~IDomainDecompositionInfo ()
Constructor & Destructor Documentation
~IDomainDecompositionInfo()
virtual pcl::IDomainDecompositionInfo::~IDomainDecompositionInfo () inline virtual
Member Function Documentation
get_num_spatial_dimensions()
virtual int pcl::IDomainDecompositionInfo::get_num_spatial_dimensions () const pure virtual
Implemented in pcl::StandardDomainDecompositionInfo.
get_num_subdomains()
virtual int pcl::IDomainDecompositionInfo::get_num_subdomains () const pure virtual
Implemented in pcl::StandardDomainDecompositionInfo.
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), and ug::FETISolver< TAlgebra >::print_statistic_of_inner_solver().
get_subdomain_procs()
virtual void pcl::IDomainDecompositionInfo::get_subdomain_procs (std::vector< int > & procsOut, int subdomIndex) pure virtual
Implemented in pcl::StandardDomainDecompositionInfo.
map_proc_id_to_subdomain_id()
virtual int pcl::IDomainDecompositionInfo::map_proc_id_to_subdomain_id (int procID) const pure virtual
mapping method "proc-id" ==> "subdomain-id"
This functions determines the subdomain a processor lives
Parameters
[out] procID id of processor
Returns
int id of subdomain the processor operates on
Implemented in pcl::StandardDomainDecompositionInfo.
Referenced by ug::AddEntriesToIndexLayout_DomainDecomposition(), ug::BuildDomainDecompositionLayouts(), ug::CommunicateConnections(), ug::CopyInterfaceEntrysToDomainDecompositionLayouts(), and ug::FetiLayouts< TAlgebra >::create_layouts().
The documentation for this class was generated from the following file:
ugbase/pcl/pcl_domain_decomposition.h