ug4: SparseMatrix< T > Class Template Reference
SparseMatrix< T > Class Template Reference
#include <sparsematrix_interface.h>
Public Types
typedef T value_type
Public Member Functions
const_row_iterator begin_row (size_t row) const
row_iterator begin_row (size_t row)
void defragment ()
const_row_iterator end_row (size_t row) const
row_iterator end_row (size_t row)
const_row_iterator get_connection (size_t r, size_t c, bool &bFound) const
row_iterator get_connection (size_t r, size_t c, bool &bFound)
const_row_iterator get_connection (size_t r, size_t c) const
row_iterator get_connection (size_t r, size_t c)
size_t num_cols () const
size_t num_connections (size_t row) const
size_t num_rows () const
value_type & operator() (size_t r, size_t c)
const value_type & operator() (size_t r, size_t c) const
bool resize (size_t newRows, size_t newCols)
SparseMatrix ()
size_t total_num_connections () const
virtual ~SparseMatrix ()
Member Typedef Documentation
template<typename T > typedef T SparseMatrix< T >::value_type
Constructor & Destructor Documentation
template<typename T > SparseMatrix< T >::SparseMatrix ()
template<typename T > virtual SparseMatrix< T >::~SparseMatrix () virtual
Member Function Documentation
template<typename T > const_row_iterator SparseMatrix< T >::begin_row (size_t row) const
Referenced by SparseMatrix< T >::total_num_connections().
template<typename T > row_iterator SparseMatrix< T >::begin_row (size_t row)
template<typename T > void SparseMatrix< T >::defragment ()
Referenced by SparseMatrix< T >::total_num_connections().
template<typename T > const_row_iterator SparseMatrix< T >::end_row (size_t row) const
Referenced by SparseMatrix< T >::total_num_connections().
template<typename T > row_iterator SparseMatrix< T >::end_row (size_t row)
template<typename T > const_row_iterator SparseMatrix< T >::get_connection (size_t r, size_t c, bool & bFound) const
Referenced by SparseMatrix< T >::total_num_connections().
template<typename T > row_iterator SparseMatrix< T >::get_connection (size_t r, size_t c, bool & bFound)
template<typename T > const_row_iterator SparseMatrix< T >::get_connection (size_t r, size_t c) const
template<typename T > row_iterator SparseMatrix< T >::get_connection (size_t r, size_t c)
template<typename T > size_t SparseMatrix< T >::num_cols () const inline
template<typename T > size_t SparseMatrix< T >::num_connections (size_t row) const inline
template<typename T > size_t SparseMatrix< T >::num_rows () const inline
template<typename T > value_type& SparseMatrix< T >::operator() (size_t r, size_t c)
operator() (size_t r, size_t c) const access connection (r, c)
Parameters
r row
c column
Note
it is assert'ed that connection (r,c) is there use operator()(r,c,bConnectionFound) to check.
Returns
SparseMat(r, c)
template<typename T > const value_type& SparseMatrix< T >::operator() (size_t r, size_t c) const
operator() (size_t r, size_t c) const access or create connection (r, c)
Parameters
r row
c column
Note
(r,c) is added to sparsity pattern if not already there use operator()(r,c,bConnectionFound) to prevent
Returns
SparseMat(r, c)=0.0 if connection created, otherwise SparseMat(r, c)
template<typename T > bool SparseMatrix< T >::resize (size_t newRows, size_t newCols)
template<typename T > size_t SparseMatrix< T >::total_num_connections () const inline
References A_type, ABC_type, B_type, SparseMatrix< T >::begin_row(), CreateAsProductOf(), SparseMatrix< T >::defragment(), SparseMatrix< T >::end_row(), and SparseMatrix< T >::get_connection().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/interface/sparsematrix_interface.h