ug4: ug::ISubGrid Class Reference
ug::ISubGrid Class Reference abstract
Instances represent a part of a grid.
#include <sub_grid.h>
Public Member Functions
virtual const GridObjectCollection & goc () const =0
virtual bool is_contained (Edge *) const =0
virtual bool is_contained (Face *) const =0
virtual bool is_contained (Vertex *) const =0
virtual bool is_contained (Volume *) const =0
virtual ~ISubGrid ()
Detailed Description
Instances represent a part of a grid.
One can iterate over the objects in a sub-grid and one may check whether elements are contained in a sub-grid.
See also
SubGrid
Constructor & Destructor Documentation
~ISubGrid()
virtual ug::ISubGrid::~ISubGrid () inline virtual
Member Function Documentation
goc()
virtual const GridObjectCollection& ug::ISubGrid::goc () const pure virtual
Implemented in ug::SubGrid< TCallbackCls >.
Referenced by ug::ProjectionHandler::refinement_begins(), and ug::SubdivisionProjector::refinement_begins().
is_contained() [1/4]
virtual bool ug::ISubGrid::is_contained (Edge *) const pure virtual
Implemented in ug::SubGrid< TCallbackCls >.
is_contained() [2/4]
virtual bool ug::ISubGrid::is_contained (Face *) const pure virtual
Implemented in ug::SubGrid< TCallbackCls >.
is_contained() [3/4]
virtual bool ug::ISubGrid::is_contained (Vertex *) const pure virtual
Implemented in ug::SubGrid< TCallbackCls >.
Referenced by ug::IsInSubGrid::callback(), ug::IsNotInSubGrid::callback(), and ug::ProjectionHandler::refinement_begins().
is_contained() [4/4]
virtual bool ug::ISubGrid::is_contained (Volume *) const pure virtual
Implemented in ug::SubGrid< TCallbackCls >.
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/sub_grid.h