ug4: ug::attachment_traits< Face *, ElementStorage< Face > > Class Reference
ug::attachment_traits< Face *, ElementStorage< Face > > Class Reference
#include <element_storage.h>
Public Types
typedef const ElementStorage< Face > * ConstElemHandlerPtr
typedef const Face * ConstElemPtr
typedef ElementStorage< Face >::SectionContainer::iterator element_iterator
typedef ElementStorage< Face > * ElemHandlerPtr
typedef Face * ElemPtr
typedef Face *& ElemRef
Static Public Member Functions
static element_iterator elements_begin (ElemHandlerPtr pHandler)
static element_iterator elements_end (ElemHandlerPtr pHandler)
static uint get_data_index (ConstElemHandlerPtr pHandler, ConstElemPtr elem)
static void set_data_index (ElemHandlerPtr pHandler, ElemPtr elem, uint index)
Member Typedef Documentation
ConstElemHandlerPtr
typedef const ElementStorage<Face>* ug::attachment_traits< Face *, ElementStorage< Face > >::ConstElemHandlerPtr
ConstElemPtr
typedef const Face* ug::attachment_traits< Face *, ElementStorage< Face > >::ConstElemPtr
element_iterator
typedef ElementStorage<Face>::SectionContainer::iterator ug::attachment_traits< Face *, ElementStorage< Face > >::element_iterator
ElemHandlerPtr
typedef ElementStorage<Face>* ug::attachment_traits< Face *, ElementStorage< Face > >::ElemHandlerPtr
ElemPtr
typedef Face* ug::attachment_traits< Face *, ElementStorage< Face > >::ElemPtr
ElemRef
typedef Face*& ug::attachment_traits< Face *, ElementStorage< Face > >::ElemRef
Member Function Documentation
elements_begin()
static element_iterator ug::attachment_traits< Face *, ElementStorage< Face > >::elements_begin (ElemHandlerPtr pHandler) inline static
References ug::SectionContainer< TValue, TContainer >::begin(), and ug::ElementStorage< TElem >::m_sectionContainer.
elements_end()
static element_iterator ug::attachment_traits< Face *, ElementStorage< Face > >::elements_end (ElemHandlerPtr pHandler) inline static
References ug::SectionContainer< TValue, TContainer >::end(), and ug::ElementStorage< TElem >::m_sectionContainer.
get_data_index()
static uint ug::attachment_traits< Face *, ElementStorage< Face > >::get_data_index (ConstElemHandlerPtr pHandler, ConstElemPtr elem) inline static
References ug::GridObject::grid_data_index().
set_data_index()
static void ug::attachment_traits< Face *, ElementStorage< Face > >::set_data_index (ElemHandlerPtr pHandler, ElemPtr elem, uint index) inline static
References ug::GridObject::set_grid_data_index().
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/element_storage.h