ug4: ug::TransferValueAccessor Class Reference
ug::TransferValueAccessor Class Reference abstract
#include <local_transfer_interface.h>
Public Member Functions
virtual void access_closure (GridObject *elem)=0
virtual void access_inner (GridObject *elem)=0
const number & operator[] (size_t i) const
number & operator[] (size_t i)
size_t size () const
virtual ~TransferValueAccessor ()
Protected Attributes
std::vector< number * > m_Val
Constructor & Destructor Documentation
virtual ug::TransferValueAccessor::~TransferValueAccessor () inline virtual
Member Function Documentation
virtual void ug::TransferValueAccessor::access_closure (GridObject * elem) pure virtual
Implemented in ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor.
Referenced by ug::P1LagrangeElemTransfer< TDomain >::do_restrict(), ug::StdLagrangeElemTransfer< TDomain >::do_restrict(), ug::P1LagrangeElemTransfer< TDomain >::prolongate(), ug::StdLagrangeElemTransfer< TDomain >::prolongate(), and ug::CrouzeixRaviartElemTransfer< TDomain >::prolongate().
virtual void ug::TransferValueAccessor::access_inner (GridObject * elem) pure virtual
Implemented in ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor.
Referenced by ug::PiecewiseConstantElemTransfer< TDomain >::do_restrict(), ug::P1LagrangeElemTransfer< TDomain >::do_restrict(), ug::StdLagrangeElemTransfer< TDomain >::do_restrict(), ug::CrouzeixRaviartElemTransfer< TDomain >::do_restrict(), ug::PiecewiseConstantElemTransfer< TDomain >::prolongate(), ug::P1LagrangeElemTransfer< TDomain >::prolongate(), ug::StdLagrangeElemTransfer< TDomain >::prolongate(), and ug::CrouzeixRaviartElemTransfer< TDomain >::prolongate().
const number& ug::TransferValueAccessor::operator[] (size_t i) const inline
References m_Val, and UG_ASSERT.
number& ug::TransferValueAccessor::operator[] (size_t i) inline
References m_Val, and UG_ASSERT.
size_t ug::TransferValueAccessor::size () const inline
References m_Val.
Referenced by ug::PiecewiseConstantElemTransfer< TDomain >::do_restrict(), ug::P1LagrangeElemTransfer< TDomain >::do_restrict(), ug::CrouzeixRaviartElemTransfer< TDomain >::do_restrict(), ug::P1LagrangeElemTransfer< TDomain >::prolongate(), ug::StdLagrangeElemTransfer< TDomain >::prolongate(), and ug::CrouzeixRaviartElemTransfer< TDomain >::prolongate().
Member Data Documentation
std::vector<number*> ug::TransferValueAccessor::m_Val protected
Referenced by ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::access_closure(), ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::access_inner(), operator[](), and size().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/local_transfer_interface.h