ug4: ug::GridReaderVTU Class Reference
ug::GridReaderVTU Class Reference
Grants read access to vtu (vtk) files.
#include <file_io_vtu.h>
Classes
struct GridEntry
struct SubsetHandlerEntry
Public Member Functions
const char * get_grid_name (size_t index) const
returns the name of the i-th grid
const char * get_subset_handler_name (size_t refGridIndex, size_t subsetHandlerIndex) const
returns the name of the given subset handler
template<class TPositionAttachment >
bool grid (Grid &gridOut, size_t index, TPositionAttachment &aPos)
returns the i-th grid.
GridReaderVTU ()
size_t num_grids () const
returns the number of grids in the given file
size_t num_subset_handlers (size_t refGridIndex) const
returns the number of subset handlers for the given grid
bool parse_file (const char *filename)
parses an xml file
bool subset_handler (ISubsetHandler &shOut, size_t refGridIndex, size_t subsetHandlerIndex)
fills the given subset-handler
virtual ~GridReaderVTU ()
Protected Member Functions
template<class T >
void check_indices (std::vector< T > &inds, size_t first, size_t num, size_t max)
bool create_cells (std::vector< GridObject * > &cellsOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > vertices, size_t pieceVrtOffset)
template<class TAAPos >
bool create_vertices (std::vector< Vertex * > &vrtsOut, Grid &grid, rapidxml::xml_node<> *vrtNode, TAAPos aaPos)
creates vertices from a vertex-node.
rapidxml::xml_node * find_child_node_by_argument_value (rapidxml::xml_node<> *parent, const char *nodeName, const char *argName, const char *argValue)
virtual bool new_document_parsed ()
initializes internal arrays
template<class T >
void read_scalar_data (std::vector< T > &dataOut, rapidxml::xml_node<> *dataNode, bool clearData=true)
Protected Attributes
rapidxml::xml_document m_doc
the xml_document which stores the data
std::vector< GridEntry > m_entries
holds grids which already have been created
std::string m_filename
stores the file-name
Detailed Description
Grants read access to vtu (vtk) files.
Before any data can be retrieved using the get_* methods, a file has to be successfully loaded using load_file.
Todo:
: Improve performance by using in-situ stringstreams during element creation.
Constructor & Destructor Documentation
GridReaderVTU()
ug::GridReaderVTU::GridReaderVTU ()
~GridReaderVTU()
ug::GridReaderVTU::~GridReaderVTU () virtual
Member Function Documentation
check_indices()
template<class T > void ug::GridReaderVTU::check_indices (std::vector< T > & inds, size_t first, size_t num, size_t max) protected
References UG_COND_THROW.
Referenced by create_cells().
create_cells()
bool ug::GridReaderVTU::create_cells (std::vector< GridObject * > & cellsOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > vertices, size_t pieceVrtOffset) protected
References check_indices(), grid(), m_filename, ug::UGError::push_msg(), read_scalar_data(), UG_COND_THROW, UG_LOG, UG_THROW, boost::vertices(), VRT, ug::VTK_HEXAHEDRON, ug::VTK_LINE, ug::VTK_NUM_TYPES, ug::VTK_PYRAMID, ug::VTK_QUAD, ug::VTK_TETRA, ug::VTK_TRIANGLE, ug::VTK_VERTEX, ug::VTK_WEDGE, and ug::VTKCellNames.
create_vertices()
template<class TAAPos > bool ug::GridReaderVTU::create_vertices (std::vector< Vertex * > & vrtsOut, Grid & grid, rapidxml::xml_node<> * vrtNode, TAAPos aaPos) protected
creates vertices from a vertex-node.
if aaPos has more coordinates per vertex than the vrtNode, 0's will be appended. If it has less, unused coordinates will be ignored.
References ug::Grid::create(), UG_COND_THROW, and UG_LOG.
find_child_node_by_argument_value()
xml_node * ug::GridReaderVTU::find_child_node_by_argument_value (rapidxml::xml_node<> * parent, const char * nodeName, const char * argName, const char * argValue) protected
Referenced by subset_handler().
get_grid_name()
const char * ug::GridReaderVTU::get_grid_name (size_t index) const
returns the name of the i-th grid
References m_entries, and num_grids().
get_subset_handler_name()
const char * ug::GridReaderVTU::get_subset_handler_name (size_t refGridIndex, size_t subsetHandlerIndex) const
returns the name of the given subset handler
References m_entries, num_grids(), and ug::GridReaderVTU::GridEntry::subsetHandlerEntries.
Referenced by subset_handler().
grid()
template<class TPositionAttachment > bool ug::GridReaderVTU::grid (Grid & gridOut, size_t index, TPositionAttachment & aPos)
returns the i-th grid.
TPositionAttachments value type has to be compatible with MathVector. Make sure that a file has already been loaded.
References ug::Grid::attach_to_vertices(), ug::Grid::get_options(), ug::GRIDOPT_NONE, ug::Grid::has_vertex_attachment(), ug::Grid::set_options(), UG_COND_THROW, UG_LOG, and boost::vertices().
Referenced by create_cells(), and ug::LoadGridFromVTU().
new_document_parsed()
bool ug::GridReaderVTU::new_document_parsed () protected virtual
initializes internal arrays
searches for all grid-nodes and stores, resizes m_entries and stores the node for each entry.
If you create your own version of this method, don't forget to call the base-class implementation!
References m_doc, m_entries, ug::GridReaderVTU::GridEntry::subsetHandlerEntries, and UG_COND_THROW.
Referenced by parse_file().
num_grids()
size_t ug::GridReaderVTU::num_grids () const inline
returns the number of grids in the given file
References m_entries.
Referenced by get_grid_name(), get_subset_handler_name(), and ug::LoadGridFromVTU().
num_subset_handlers()
size_t ug::GridReaderVTU::num_subset_handlers (size_t refGridIndex) const
returns the number of subset handlers for the given grid
References m_entries, and UG_LOG.
parse_file()
bool ug::GridReaderVTU::parse_file (const char * filename)
parses an xml file
References m_doc, m_filename, and new_document_parsed().
Referenced by ug::LoadGridFromVTU().
read_scalar_data()
template<class T > void ug::GridReaderVTU::read_scalar_data (std::vector< T > & dataOut, rapidxml::xml_node<> * dataNode, bool clearData = true) protected
Referenced by create_cells(), and subset_handler().
subset_handler()
bool ug::GridReaderVTU::subset_handler (ISubsetHandler & shOut, size_t refGridIndex, size_t subsetHandlerIndex)
fills the given subset-handler
References ug::ISubsetHandler::assign_subset(), ug::GridReaderVTU::GridEntry::cells, find_child_node_by_argument_value(), get_subset_handler_name(), m_entries, m_filename, ug::SubsetInfo::name, ug::GridReaderVTU::SubsetHandlerEntry::node, ug::GridReaderVTU::GridEntry::node, read_scalar_data(), ug::GridReaderVTU::SubsetHandlerEntry::sh, ug::ISubsetHandler::subset_info(), ug::GridReaderVTU::GridEntry::subsetHandlerEntries, UG_COND_THROW, UG_LOG, and UG_THROW.
Referenced by ug::LoadGridFromVTU().
Member Data Documentation
m_doc
rapidxml::xml_document ug::GridReaderVTU::m_doc protected
the xml_document which stores the data
Referenced by new_document_parsed(), and parse_file().
m_entries
std::vector<GridEntry> ug::GridReaderVTU::m_entries protected
holds grids which already have been created
Referenced by get_grid_name(), get_subset_handler_name(), new_document_parsed(), num_grids(), num_subset_handlers(), and subset_handler().
m_filename
std::string ug::GridReaderVTU::m_filename protected
stores the file-name
Referenced by create_cells(), parse_file(), and subset_handler().
The documentation for this class was generated from the following files:
ugbase/lib_grid/file_io/file_io_vtu.h
ugbase/lib_grid/file_io/file_io_vtu.cpp
ugbase/lib_grid/file_io/file_io_vtu_impl.h