ug4: ug::bridge::ClassNameNode Class Reference
ug::bridge::ClassNameNode Class Reference
ugbase » Bridge » Registry
node for class names
#include <class_name_provider.h>
Public Member Functions
void add_base_class (const ClassNameNode &node)
add a base class
const ClassNameNode & base_class (size_t i) const
return a base class
ClassNameNode ()
constructor
bool empty () const
returns if a name has been set
const std::string & name () const
returns own name
bool named () const
returns if a name has been set by the user
size_t num_base_classes () const
returns number of parents
void set_name (const std::string &name)
set name
Protected Attributes
std::string m_name
own name
std::vector< const ClassNameNode * > m_vBaseClass
base classes
Detailed Description
node for class names
A ClassNameNode stores the name of a registered class and pointers to the ClassNameNodes of the direct base classes of this class. By traversing the tree of ClassNameNodes all parent classes of a class can be found.
Constructor & Destructor Documentation
ClassNameNode()
ug::bridge::ClassNameNode::ClassNameNode ()
constructor
References m_name.
Member Function Documentation
add_base_class()
void ug::bridge::ClassNameNode::add_base_class (const ClassNameNode & node)
add a base class
References ug::find(), and m_vBaseClass.
base_class()
const ClassNameNode& ug::bridge::ClassNameNode::base_class (size_t i) const inline
return a base class
Referenced by ug::bridge::ClassCastProvider::cast_to_base_class(), ug::bridge::ClassNameTreeContains(), ug::bridge::ClassNameTreeWay(), ug::bridge::lua::ExecuteMethod(), ug::bridge::ExtractClassNameVec(), and ug::bridge::lua::MetatableIndexer().
empty()
bool ug::bridge::ClassNameNode::empty () const inline
returns if a name has been set
Referenced by ug::bridge::lua::LuaParsing< const void * >::checkAndGet(), ug::bridge::lua::LuaParsing< ConstSmartPtr< void > >::checkAndGet(), ug::bridge::lua::LuaParsing< SmartPtr< void > >::checkAndGet(), ug::bridge::lua::LuaParsing< void * >::checkAndGet(), ug::bridge::GetLuaTypeString(), named(), and ug::script::UGIsBaseClass().
name()
const std::string& ug::bridge::ClassNameNode::name () const inline
returns own name
Referenced by ug::bridge::ClassCastProvider::cast_to_base_class(), ug::bridge::ParameterInfo::class_name(), ug::bridge::ClassNameTreeContains(), ug::bridge::ClassNameTreeWay(), ug::bridge::lua::ExecuteMethod(), ug::bridge::ExtractClassNameVec(), ug::bridge::GetLuaTypeString(), ug::bridge::lua::LuaProxyMethod(), ug::bridge::lua::MetatableIndexer(), set_name(), ug::script::UGGetClassGroup(), and ug::script::UGGetClassName().
named()
bool ug::bridge::ClassNameNode::named () const
returns if a name has been set by the user
References empty(), and m_name.
Referenced by ug::bridge::ParameterInfo::parameter_named().
num_base_classes()
size_t ug::bridge::ClassNameNode::num_base_classes () const inline
returns number of parents
Referenced by ug::bridge::ClassNameTreeContains(), ug::bridge::ClassNameTreeWay(), ug::bridge::lua::ExecuteMethod(), ug::bridge::ExtractClassNameVec(), and ug::bridge::lua::MetatableIndexer().
set_name()
void ug::bridge::ClassNameNode::set_name (const std::string & name)
set name
References m_name, name(), and UG_THROW_REGISTRY_MSG.
Member Data Documentation
m_name
std::string ug::bridge::ClassNameNode::m_name protected
own name
Referenced by ClassNameNode(), named(), and set_name().
m_vBaseClass
std::vector<const ClassNameNode*> ug::bridge::ClassNameNode::m_vBaseClass protected
base classes
Referenced by add_base_class().
The documentation for this class was generated from the following files:
ugbase/registry/class_name_provider.h
ugbase/registry/class_name_provider.cpp