ug4: ug::RefinementProjectionHandler< TAPosition > Class Template Reference
ug::RefinementProjectionHandler< TAPosition > Class Template Reference
Register different refinement callbacks for different subsets.
#include <refinement_projection_handler.h>
Public Member Functions
virtual int current_pos (number *coordsOut, Vertex *vrt, int maxCoords)
returns the position of the given vertex.
virtual void flat_grid_vertex_encountered (Vertex *vrt)
callback for vertices in flat grids.
virtual void new_vertex (Vertex *vrt, Vertex *parent)
called when a new vertex was created from an old vertex.
virtual void new_vertex (Vertex *vrt, Edge *parent)
called when a new vertex was created from an old edge.
virtual void new_vertex (Vertex *vrt, Face *parent)
called when a new vertex was created from an old face.
virtual void new_vertex (Vertex *vrt, Volume *parent)
called when a new vertex was created from an old volume.
RefinementProjectionHandler (SmartPtr< ISubsetHandler > sh, TAPosition aPos)
void set_callback (int subsetIndex, SmartPtr< IRefinementCallback > callback)
void set_callback (std::string subsetName, SmartPtr< IRefinementCallback > callback)
void set_default_callback (SmartPtr< IRefinementCallback > callback)
virtual ~RefinementProjectionHandler ()
Public Member Functions inherited from ug::IRefinementCallback
virtual ~IRefinementCallback ()
Private Member Functions
template<class TParent >
void handle_new_vertex (Vertex *vrt, TParent *parent)
Private Attributes
Grid::VertexAttachmentAccessor< TAPosition > m_aaPos
std::vector< SmartPtr< IRefinementCallback > > m_callbacks
SmartPtr< IRefinementCallback > m_defaultCallback
SmartPtr< ISubsetHandler > m_sh
Additional Inherited Members
Protected Member Functions inherited from ug::IRefinementCallback
template<class TAttachmentAccessor >
int current_pos_helper (number *coordsOut, Vertex *vrt, int maxCoords, TAttachmentAccessor &aaPos)
A helper implementation of current_pos available for derived classes.
Detailed Description
template<class TAPosition>
class ug::RefinementProjectionHandler< TAPosition >
Register different refinement callbacks for different subsets.
Using set_callback you may specify a callback which will be executed, if the parent element is contained in the specified subset. You may also specify a default callback which is executed if no parent is present, if the parent isn't assigned to a subset or if no callback has been assigned to the parent's subset. By default the default callback is RefinementCallbackLinear.
Use IRefiner::set_refinement_callback to set an instance of this class as the refinement callback of a refiner.
Constructor & Destructor Documentation
template<class TAPosition > ug::RefinementProjectionHandler< TAPosition >::RefinementProjectionHandler (SmartPtr< ISubsetHandler > sh, TAPosition aPos) inline
References UG_ASSERT, and ug::RefinementProjectionHandler< TAPosition >::~RefinementProjectionHandler().
template<class TAPosition > ug::RefinementProjectionHandler< TAPosition >::~RefinementProjectionHandler () inline virtual
References ug::RefinementProjectionHandler< TAPosition >::set_default_callback().
Referenced by ug::RefinementProjectionHandler< TAPosition >::RefinementProjectionHandler().
Member Function Documentation
template<class TAPosition > int ug::RefinementProjectionHandler< TAPosition >::current_pos (number * coordsOut, Vertex * vrt, int maxCoords) inline virtual
returns the position of the given vertex.
Implements ug::IRefinementCallback.
References ug::IRefinementCallback::current_pos_helper().
Referenced by ug::RefinementProjectionHandler< TAPosition >::flat_grid_vertex_encountered().
template<class TAPosition > void ug::RefinementProjectionHandler< TAPosition >::flat_grid_vertex_encountered (Vertex * vrt) inline virtual
callback for vertices in flat grids.
Reimplemented from ug::IRefinementCallback.
References ug::RefinementProjectionHandler< TAPosition >::current_pos().
Referenced by ug::RefinementProjectionHandler< TAPosition >::new_vertex().
template<class TAPosition > template<class TParent > void ug::RefinementProjectionHandler< TAPosition >::handle_new_vertex (Vertex * vrt, TParent * parent) inline private
References ug::RefinementProjectionHandler< TAPosition >::new_vertex(), and UG_ASSERT.
Referenced by ug::RefinementProjectionHandler< TAPosition >::set_callback().
template<class TAPosition > void ug::RefinementProjectionHandler< TAPosition >::new_vertex (Vertex * vrt, Vertex * parent) inline virtual
called when a new vertex was created from an old vertex.
Implements ug::IRefinementCallback.
Referenced by ug::RefinementProjectionHandler< TAPosition >::handle_new_vertex(), and ug::RefinementProjectionHandler< TAPosition >::new_vertex().
template<class TAPosition > void ug::RefinementProjectionHandler< TAPosition >::new_vertex (Vertex * vrt, Edge * parent) inline virtual
called when a new vertex was created from an old edge.
Implements ug::IRefinementCallback.
References ug::RefinementProjectionHandler< TAPosition >::new_vertex().
template<class TAPosition > void ug::RefinementProjectionHandler< TAPosition >::new_vertex (Vertex * vrt, Face * parent) inline virtual
called when a new vertex was created from an old face.
Implements ug::IRefinementCallback.
References ug::RefinementProjectionHandler< TAPosition >::new_vertex().
template<class TAPosition > void ug::RefinementProjectionHandler< TAPosition >::new_vertex (Vertex * vrt, Volume * parent) inline virtual
called when a new vertex was created from an old volume.
Implements ug::IRefinementCallback.
References ug::RefinementProjectionHandler< TAPosition >::flat_grid_vertex_encountered().
template<class TAPosition > void ug::RefinementProjectionHandler< TAPosition >::set_callback (int subsetIndex, SmartPtr< IRefinementCallback > callback) inline
References UG_COND_THROW.
Referenced by ug::RefinementProjectionHandler< TAPosition >::set_default_callback().
template<class TAPosition > void ug::RefinementProjectionHandler< TAPosition >::set_callback (std::string subsetName, SmartPtr< IRefinementCallback > callback) inline
References ug::RefinementProjectionHandler< TAPosition >::handle_new_vertex(), and UG_ASSERT.
template<class TAPosition > void ug::RefinementProjectionHandler< TAPosition >::set_default_callback (SmartPtr< IRefinementCallback > callback) inline
References ug::RefinementProjectionHandler< TAPosition >::set_callback().
Referenced by ug::RefinementProjectionHandler< TAPosition >::~RefinementProjectionHandler().
Member Data Documentation
template<class TAPosition > Grid::VertexAttachmentAccessor<TAPosition> ug::RefinementProjectionHandler< TAPosition >::m_aaPos private
template<class TAPosition > std::vector<SmartPtr<IRefinementCallback> > ug::RefinementProjectionHandler< TAPosition >::m_callbacks private
template<class TAPosition > SmartPtr<IRefinementCallback> ug::RefinementProjectionHandler< TAPosition >::m_defaultCallback private
template<class TAPosition > SmartPtr<ISubsetHandler> ug::RefinementProjectionHandler< TAPosition >::m_sh private
The documentation for this class was generated from the following files:
ugbase/lib_grid/algorithms/refinement/refinement_projectors/refinement_projection_handler.h
ugbase/lib_grid/algorithms/refinement/refinement_projectors/refinement_projection_handler_impl.hpp