ug4: ug::InterSubsetPartitionWeighting Class Reference
ug::InterSubsetPartitionWeighting Class Reference
#include <partition_weighting_callbacks.h>
Public Member Functions
InterSubsetPartitionWeighting ()
virtual int operator() (Edge *e1, Edge *e2)
virtual int operator() (Face *f1, Face *f2)
virtual int operator() (Volume *v1, Volume *v2)
void set_inter_subset_weight (int si1, int si2, int weight)
virtual ~InterSubsetPartitionWeighting ()
Public Member Functions inherited from ug::PartitionWeighting
PartitionWeighting ()
void set_default_weights (int hWeight, int vWeight)
void set_subset_handler (MGSubsetHandler *sh)
virtual ~PartitionWeighting ()
Private Member Functions
template<class TElem >
int weigh (TElem *e1, TElem *e2)
Private Attributes
std::vector< int > m_vsi1
std::vector< int > m_vsi2
std::vector< int > m_vweights
Additional Inherited Members
Protected Attributes inherited from ug::PartitionWeighting
int m_hWeight
MGSubsetHandler * m_sh
int m_vWeight
Detailed Description
First simple implementation: Preventing division between two distinct subsets.
Constructor & Destructor Documentation
InterSubsetPartitionWeighting()
ug::InterSubsetPartitionWeighting::InterSubsetPartitionWeighting () inline
~InterSubsetPartitionWeighting()
virtual ug::InterSubsetPartitionWeighting::~InterSubsetPartitionWeighting () inline virtual
Member Function Documentation
operator()() [1/3]
virtual int ug::InterSubsetPartitionWeighting::operator() (Edge * e1, Edge * e2) inline virtual
Reimplemented from ug::PartitionWeighting.
References weigh().
operator()() [2/3]
virtual int ug::InterSubsetPartitionWeighting::operator() (Face * f1, Face * f2) inline virtual
Reimplemented from ug::PartitionWeighting.
References weigh().
operator()() [3/3]
virtual int ug::InterSubsetPartitionWeighting::operator() (Volume * v1, Volume * v2) inline virtual
Reimplemented from ug::PartitionWeighting.
References weigh().
set_inter_subset_weight()
void ug::InterSubsetPartitionWeighting::set_inter_subset_weight (int si1, int si2, int weight) inline
References m_vsi1, m_vsi2, and m_vweights.
weigh()
template<class TElem > int ug::InterSubsetPartitionWeighting::weigh (TElem * e1, TElem * e2) inline private
References ug::MultiGridSubsetHandler::get_level(), ug::ISubsetHandler::get_subset_index(), ug::PartitionWeighting::m_hWeight, ug::PartitionWeighting::m_sh, m_vsi1, m_vsi2, ug::PartitionWeighting::m_vWeight, m_vweights, and UG_THROW.
Referenced by operator()().
Member Data Documentation
m_vsi1
std::vector<int> ug::InterSubsetPartitionWeighting::m_vsi1 private
Referenced by set_inter_subset_weight(), and weigh().
m_vsi2
std::vector<int> ug::InterSubsetPartitionWeighting::m_vsi2 private
Referenced by set_inter_subset_weight(), and weigh().
m_vweights
std::vector<int> ug::InterSubsetPartitionWeighting::m_vweights private
Referenced by set_inter_subset_weight(), and weigh().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/util/partition_weighting_callbacks.h