ug4: ug::LineGaussSeidel< TDomain, TAlgebra > Class Template Reference
ug::LineGaussSeidel< TDomain, TAlgebra > Class Template Reference
#include <line_smoothers.h>
Public Types
typedef TAlgebra algebra_type
typedef IPreconditioner< TAlgebra > base_type
Base type.
typedef TDomain domain_type
Domain.
typedef IPreconditioner< TAlgebra >::matrix_operator_type matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual SmartPtr< ILinearIterator< vector_type > > clone ()
clone
size_t get_num_backwardx ()
size_t get_num_backwardy ()
size_t get_num_backwardz ()
size_t get_num_forwardx ()
size_t get_num_forwardy ()
size_t get_num_forwardz ()
LineGaussSeidel (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_num_steps (size_t forwardx, size_t backwardx)
void set_num_steps (size_t forwardx, size_t backwardx, size_t forwardy, size_t backwardy)
void set_num_steps (size_t forwardx, size_t backwardx, size_t forwardy, size_t backwardy, size_t forwardz, size_t backwardz)
virtual bool supports_parallel () const
returns if parallel solving is supported
bool update (size_t xsize)
~LineGaussSeidel ()
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
virtual std::string config_string () const
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
returns true if the debug writer is set
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
bool linegs_step (const matrix_type &A, vector_type &x, const vector_type &b)
virtual const char * name () const
returns the name of iterator
virtual bool postprocess ()
cleans the operator
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
initializes the preconditioner
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
computes a new correction c = B*d
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
void enter_debug_writer_section (const char *secDir)
enters a debugging section
void enter_debug_writer_section (std::string secDir)
enters a debugging section
void leave_debug_writer_section ()
leaves a debugging section
void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
void write_debug (const matrix_type &mat, std::string name)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
std::vector< size_t > indY
std::vector< size_t > indZ
matrix_type m_A
size_t m_ind_end
bool m_init
size_t m_nr_backwardx
size_t m_nr_backwardy
size_t m_nr_backwardz
size_t m_nr_forwardx
size_t m_nr_forwardy
size_t m_nr_forwardz
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Static Protected Attributes
static const int dim = domain_type::dim
world dimension
Member Typedef Documentation
algebra_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra ug::LineGaussSeidel< TDomain, TAlgebra >::algebra_type
base_type
template<typename TDomain , typename TAlgebra > typedef IPreconditioner<TAlgebra> ug::LineGaussSeidel< TDomain, TAlgebra >::base_type
Base type.
domain_type
template<typename TDomain , typename TAlgebra > typedef TDomain ug::LineGaussSeidel< TDomain, TAlgebra >::domain_type
Domain.
matrix_operator_type
template<typename TDomain , typename TAlgebra > typedef IPreconditioner<TAlgebra>::matrix_operator_type ug::LineGaussSeidel< TDomain, TAlgebra >::matrix_operator_type
Matrix Operator type.
matrix_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::matrix_type ug::LineGaussSeidel< TDomain, TAlgebra >::matrix_type
vector_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::vector_type ug::LineGaussSeidel< TDomain, TAlgebra >::vector_type
Constructor & Destructor Documentation
LineGaussSeidel()
template<typename TDomain , typename TAlgebra > ug::LineGaussSeidel< TDomain, TAlgebra >::LineGaussSeidel (SmartPtr< ApproximationSpace< TDomain > > approxSpace) inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::m_init, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardy, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardz, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardy, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardz, and ug::LineGaussSeidel< TDomain, TAlgebra >::m_spApproxSpace.
~LineGaussSeidel()
template<typename TDomain , typename TAlgebra > ug::LineGaussSeidel< TDomain, TAlgebra >::~LineGaussSeidel () inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::indY, and ug::LineGaussSeidel< TDomain, TAlgebra >::indZ.
Member Function Documentation
clone()
template<typename TDomain , typename TAlgebra > virtual SmartPtr<ILinearIterator<vector_type> > ug::LineGaussSeidel< TDomain, TAlgebra >::clone () inline virtual
clone
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References ug::ILinearIterator< TAlgebra::vector_type >::damping(), ug::DebugWritingObject< TAlgebra >::debug_writer(), ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_backwardx(), ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_backwardy(), ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_backwardz(), ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_forwardx(), ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_forwardy(), ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_forwardz(), and ug::LineGaussSeidel< TDomain, TAlgebra >::m_spApproxSpace.
get_num_backwardx()
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_backwardx () inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardx.
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::clone().
get_num_backwardy()
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_backwardy () inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardy.
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::clone().
get_num_backwardz()
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_backwardz () inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardz.
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::clone().
get_num_forwardx()
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_forwardx () inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardx.
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::clone().
get_num_forwardy()
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_forwardy () inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardy.
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::clone().
get_num_forwardz()
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_forwardz () inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardz.
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::clone().
linegs_step()
template<typename TDomain , typename TAlgebra > bool ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step (const matrix_type & A, vector_type & x, const vector_type & b) inline protected
References ug::LineGaussSeidel< TDomain, TAlgebra >::dim, ug::LineGaussSeidel< TDomain, TAlgebra >::indY, ug::LineGaussSeidel< TDomain, TAlgebra >::indZ, ug::InverseMatMult(), ug::LineGaussSeidel< TDomain, TAlgebra >::m_ind_end, ug::LineGaussSeidel< TDomain, TAlgebra >::m_init, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardy, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardz, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardy, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardz, ug::MatMultAdd(), s, and ug::LineGaussSeidel< TDomain, TAlgebra >::update().
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::step().
name()
template<typename TDomain , typename TAlgebra > virtual const char* ug::LineGaussSeidel< TDomain, TAlgebra >::name () const inline protected virtual
returns the name of iterator
This method returns the name of the iterator operator. This function is typically needed, when the iterator operator is used inside of another operator and some debug output should be printed
Returns
const char* name of inverse operator
Implements ug::IPreconditioner< TAlgebra >.
postprocess()
template<typename TDomain , typename TAlgebra > virtual bool ug::LineGaussSeidel< TDomain, TAlgebra >::postprocess () inline protected virtual
cleans the operator
Implements ug::IPreconditioner< TAlgebra >.
preprocess()
template<typename TDomain , typename TAlgebra > virtual bool ug::LineGaussSeidel< TDomain, TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) inline protected virtual
initializes the preconditioner
This method is used to initialize the preconditioner. Usually, here are performed computationally expensive operations, that should only be computed once for an underlying matrix (e.g. LU factorization), while the preconditioner will by applied (using 'step'-method) several times.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References pcl::CollectUniqueElements(), ug::LineGaussSeidel< TDomain, TAlgebra >::m_A, ug::MakeConsistent(), pcl::NumProcs(), and ug::SetDirichletRow().
set_num_steps() [1/3]
template<typename TDomain , typename TAlgebra > void ug::LineGaussSeidel< TDomain, TAlgebra >::set_num_steps (size_t forwardx, size_t backwardx) inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardy, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardz, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardy, and ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardz.
set_num_steps() [2/3]
template<typename TDomain , typename TAlgebra > void ug::LineGaussSeidel< TDomain, TAlgebra >::set_num_steps (size_t forwardx, size_t backwardx, size_t forwardy, size_t backwardy) inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardy, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardz, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardy, and ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardz.
set_num_steps() [3/3]
template<typename TDomain , typename TAlgebra > void ug::LineGaussSeidel< TDomain, TAlgebra >::set_num_steps (size_t forwardx, size_t backwardx, size_t forwardy, size_t backwardy, size_t forwardz, size_t backwardz) inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardy, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardz, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardy, and ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardz.
step()
template<typename TDomain , typename TAlgebra > virtual bool ug::LineGaussSeidel< TDomain, TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) inline protected virtual
computes a new correction c = B*d
This method computes a new correction c = B*d. It can only be called, when the preprocess has been done.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
[out] c correction
[in] d defect
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), ug::LineGaussSeidel< TDomain, TAlgebra >::m_A, pcl::NumProcs(), and ug::PST_UNIQUE.
supports_parallel()
template<typename TDomain , typename TAlgebra > virtual bool ug::LineGaussSeidel< TDomain, TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearIterator< TAlgebra::vector_type >.
update()
template<typename TDomain , typename TAlgebra > bool ug::LineGaussSeidel< TDomain, TAlgebra >::update (size_t xsize) inline
References ug::LineGaussSeidel< TDomain, TAlgebra >::dim, ug::LineGaussSeidel< TDomain, TAlgebra >::indY, ug::LineGaussSeidel< TDomain, TAlgebra >::indZ, ug::GridLevel::LEVEL, ug::LineGaussSeidel< TDomain, TAlgebra >::m_ind_end, ug::LineGaussSeidel< TDomain, TAlgebra >::m_init, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardy, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardz, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardx, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardy, ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardz, and ug::LineGaussSeidel< TDomain, TAlgebra >::m_spApproxSpace.
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step().
Member Data Documentation
dim
template<typename TDomain , typename TAlgebra > const int ug::LineGaussSeidel< TDomain, TAlgebra >::dim = domain_type::dim static protected
world dimension
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), and ug::LineGaussSeidel< TDomain, TAlgebra >::update().
indY
template<typename TDomain , typename TAlgebra > std::vector<size_t> ug::LineGaussSeidel< TDomain, TAlgebra >::indY protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), ug::LineGaussSeidel< TDomain, TAlgebra >::update(), and ug::LineGaussSeidel< TDomain, TAlgebra >::~LineGaussSeidel().
indZ
template<typename TDomain , typename TAlgebra > std::vector<size_t> ug::LineGaussSeidel< TDomain, TAlgebra >::indZ protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), ug::LineGaussSeidel< TDomain, TAlgebra >::update(), and ug::LineGaussSeidel< TDomain, TAlgebra >::~LineGaussSeidel().
m_A
template<typename TDomain , typename TAlgebra > matrix_type ug::LineGaussSeidel< TDomain, TAlgebra >::m_A protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::preprocess(), and ug::LineGaussSeidel< TDomain, TAlgebra >::step().
m_ind_end
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::m_ind_end protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), and ug::LineGaussSeidel< TDomain, TAlgebra >::update().
m_init
template<typename TDomain , typename TAlgebra > bool ug::LineGaussSeidel< TDomain, TAlgebra >::m_init protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::LineGaussSeidel(), ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), and ug::LineGaussSeidel< TDomain, TAlgebra >::update().
m_nr_backwardx
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardx protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_backwardx(), ug::LineGaussSeidel< TDomain, TAlgebra >::LineGaussSeidel(), ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), ug::LineGaussSeidel< TDomain, TAlgebra >::set_num_steps(), and ug::LineGaussSeidel< TDomain, TAlgebra >::update().
m_nr_backwardy
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardy protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_backwardy(), ug::LineGaussSeidel< TDomain, TAlgebra >::LineGaussSeidel(), ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), ug::LineGaussSeidel< TDomain, TAlgebra >::set_num_steps(), and ug::LineGaussSeidel< TDomain, TAlgebra >::update().
m_nr_backwardz
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_backwardz protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_backwardz(), ug::LineGaussSeidel< TDomain, TAlgebra >::LineGaussSeidel(), ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), ug::LineGaussSeidel< TDomain, TAlgebra >::set_num_steps(), and ug::LineGaussSeidel< TDomain, TAlgebra >::update().
m_nr_forwardx
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardx protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_forwardx(), ug::LineGaussSeidel< TDomain, TAlgebra >::LineGaussSeidel(), ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), ug::LineGaussSeidel< TDomain, TAlgebra >::set_num_steps(), and ug::LineGaussSeidel< TDomain, TAlgebra >::update().
m_nr_forwardy
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardy protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_forwardy(), ug::LineGaussSeidel< TDomain, TAlgebra >::LineGaussSeidel(), ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), ug::LineGaussSeidel< TDomain, TAlgebra >::set_num_steps(), and ug::LineGaussSeidel< TDomain, TAlgebra >::update().
m_nr_forwardz
template<typename TDomain , typename TAlgebra > size_t ug::LineGaussSeidel< TDomain, TAlgebra >::m_nr_forwardz protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::get_num_forwardz(), ug::LineGaussSeidel< TDomain, TAlgebra >::LineGaussSeidel(), ug::LineGaussSeidel< TDomain, TAlgebra >::linegs_step(), ug::LineGaussSeidel< TDomain, TAlgebra >::set_num_steps(), and ug::LineGaussSeidel< TDomain, TAlgebra >::update().
m_spApproxSpace
template<typename TDomain , typename TAlgebra > SmartPtr<ApproximationSpace<TDomain> > ug::LineGaussSeidel< TDomain, TAlgebra >::m_spApproxSpace protected
Referenced by ug::LineGaussSeidel< TDomain, TAlgebra >::clone(), ug::LineGaussSeidel< TDomain, TAlgebra >::LineGaussSeidel(), and ug::LineGaussSeidel< TDomain, TAlgebra >::update().
The documentation for this class was generated from the following file:
ugbase/lib_disc/operator/preconditioner/line_smoothers.h