ug4: ug::GlobalMultiGridRefiner Class Reference
ug::GlobalMultiGridRefiner Class Reference
lib_grid » algorithms » refinement
#include <global_multi_grid_refiner.h>
Public Member Functions
virtual bool adaptivity_supported () const
returns whether the refiner is able to perform adaptive refinement
void assign_grid (MultiGrid &mg)
void assign_grid (MultiGrid *mg)
virtual bool coarsening_supported () const
returns true, if the refiner supports coarsening.
virtual Grid * get_associated_grid ()
DEPRECIATED! Use grid(). Has to return the associated grid. Pure virtual.
GlobalMultiGridRefiner (SPRefinementProjector projector=SPNULL)
GlobalMultiGridRefiner (MultiGrid &mg, SPRefinementProjector projector=SPNULL)
virtual Grid * grid ()
Returns the grid associated with the refiner.
virtual void grid_to_be_destroyed (Grid *grid)
virtual MultiGrid * multi_grid ()
virtual bool save_marks_to_file (const char *filename)
Writes the associated grid and marks to a file. Pure virtual.
virtual ~GlobalMultiGridRefiner ()
Public Member Functions inherited from ug::IRefiner
virtual void clear_marks ()
clears all marks. Default implementation is empty
bool coarsen ()
Performs coarsening on the elements marked RM_COARSEN.
bool debugging_enabled () const
void enable_debugging (bool enable)
int get_local_edge_mark (Face *f, Edge *e) const
returns the local mark of the specified edge of the given face
int get_local_edge_mark (Volume *vol, Edge *e) const
returns the local mark of the specified edge of the given volume
int get_local_face_mark (Volume *vol, Face *f) const
returns the local mark of the specified face of the given volume
virtual RefinementMark get_mark (GridObject *o) const
returns the mark of the specified geometric object
IRefiner (SPRefinementProjector projector=SPNULL)
virtual bool local_marks_supported () const
returns true, if the refiner supports local marks.
virtual bool mark (GridObject *o, RefinementMark refMark=RM_REFINE)
marks the specified geometric object
template<class TIterator >
void mark (const TIterator &iterBegin, const TIterator &iterEnd, RefinementMark refMark=RM_REFINE)
marks all elements between iterBegin and iterEnd.
void mark_neighborhood (size_t numIterations)
marks the neighborhood of currently marked elements.
virtual void mark_neighborhood (size_t numIterations, RefinementMark refMark, bool sideNbrsOnly)
marks the neighborhood of currently marked elements.
template<class TElem >
bool marked_closure (TElem *elem) const
template<class TElem >
bool marked_full (TElem *elem) const
template<class TElem >
bool marked_local (TElem *elem) const
size_t num_marked_edges (std::vector< int > &numMarkedEdgesOut)
returns the number of (globally) marked edges on all levels of the hierarchy
size_t num_marked_edges ()
returns the number of (globally) marked edges on all levels of the hierarchy
size_t num_marked_elements (std::vector< int > &numMarkedElemsOut)
returns the number of (globally) marked grid-objects of highest dimension
size_t num_marked_elements ()
returns the number of (globally) marked grid-objects of highest dimension
size_t num_marked_faces (std::vector< int > &numMarkedFacesOut)
returns the number of (globally) marked faces on all levels of the hierarchy
size_t num_marked_faces ()
returns the number of (globally) marked faces on all levels of the hierarchy
size_t num_marked_volumes (std::vector< int > &numMarkedVolsOut)
returns the number of (globally) marked volumes on all levels of the hierarchy
size_t num_marked_volumes ()
returns the number of (globally) marked volumes on all levels of the hierarchy
SPRefinementProjector projector ()
void refine ()
Performs refinement on the marked elements.
void set_adjusted_marks_debug_filename (const char *filename)
sets a filename to which adjusted marks are saved during refinement / coarsening
void set_projector (SPRefinementProjector projector)
virtual ~IRefiner ()
virtual bool mark (Vertex *v, RefinementMark refMark=RM_REFINE)
Marks an element for refinement. Default implementation is empty.
virtual bool mark (Edge *e, RefinementMark refMark=RM_REFINE)
Marks an element for refinement. Default implementation is empty.
virtual bool mark (Face *f, RefinementMark refMark=RM_REFINE)
Marks an element for refinement. Default implementation is empty.
virtual bool mark (Volume *v, RefinementMark refMark=RM_REFINE)
Marks an element for refinement. Default implementation is empty.
virtual void mark_local (Face *e, int mark)
Marks a face or volume for local refinement.
virtual void mark_local (Volume *e, int mark)
Marks a face or volume for local refinement.
virtual int get_local_mark (Face *e) const
returns the local mark of the specified face or volume.
virtual int get_local_mark (Volume *e) const
returns the local mark of the specified face or volume.
virtual RefinementMark get_mark (Vertex *v) const
Returns the mark of a given element. Default returns RM_REFINE.
virtual RefinementMark get_mark (Edge *e) const
Returns the mark of a given element. Default returns RM_REFINE.
virtual RefinementMark get_mark (Face *f) const
Returns the mark of a given element. Default returns RM_REFINE.
virtual RefinementMark get_mark (Volume *v) const
Returns the mark of a given element. Default returns RM_REFINE.
void adaption_begins ()
notifies all listeners of the associated message-hub, that adaption begins / ends.
void adaption_ends ()
notifies all listeners of the associated message-hub, that adaption begins / ends.
Public Member Functions inherited from ug::GridObserver
virtual void elements_to_be_cleared (Grid *grid)
virtual ~GridObserver ()
virtual void vertex_created (Grid *grid, Vertex *vrt, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void edge_created (Grid *grid, Edge *e, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void face_created (Grid *grid, Face *f, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void volume_created (Grid *grid, Volume *vol, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void vertex_to_be_erased (Grid *grid, Vertex *vrt, Vertex *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void edge_to_be_erased (Grid *grid, Edge *e, Edge *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void face_to_be_erased (Grid *grid, Face *f, Face *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void volume_to_be_erased (Grid *grid, Volume *vol, Volume *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void vertices_to_be_merged (Grid *grid, Vertex *target, Vertex *elem1, Vertex *elem2)
Notified when two elements of the same type are going to be merged.
virtual void edges_to_be_merged (Grid *grid, Edge *target, Edge *elem1, Edge *elem2)
Notified when two elements of the same type are going to be merged.
virtual void faces_to_be_merged (Grid *grid, Face *target, Face *elem1, Face *elem2)
Notified when two elements of the same type are going to be merged.
virtual void volumes_to_be_merged (Grid *grid, Volume *target, Volume *elem1, Volume *elem2)
Notified when two elements of the same type are going to be merged.
Protected Member Functions
virtual void num_marked_edges_local (std::vector< int > &numMarkedEdgesOut)
returns the number of (globally) marked edges on this level of the hierarchy
template<class TElem >
void num_marked_elems (std::vector< int > &numMarkedElemsOut)
virtual void num_marked_faces_local (std::vector< int > &numMarkedFacesOut)
returns the number of (globally) marked faces on this level of the hierarchy
virtual void num_marked_volumes_local (std::vector< int > &numMarkedVolsOut)
returns the number of (globally) marked volumes on this level of the hierarchy
virtual void perform_refinement ()
performs refinement on the marked elements.
virtual bool refinement_is_allowed (Vertex *elem)
a callback that allows to deny refinement of special vertices
virtual bool refinement_is_allowed (Edge *elem)
a callback that allows to deny refinement of special edges
virtual bool refinement_is_allowed (Face *elem)
a callback that allows to deny refinement of special faces
virtual bool refinement_is_allowed (Volume *elem)
a callback that allows to deny refinement of special volumes
virtual void refinement_step_begins ()
this method helps derived classes to perform operations directly before actual element refinment is performed.
virtual void refinement_step_ends ()
this method helps derived classes to perform operations directly after actual element refinment took place.
Protected Member Functions inherited from ug::IRefiner
virtual bool perform_coarsening ()
Called by coarsen(). Derived classes sould implement their coarsen algorithm here.
void set_message_hub (SPMessageHub msgHub)
sets the message hub.
Protected Attributes
MultiGrid * m_pMG
Protected Attributes inherited from ug::IRefiner
bool m_adaptionIsActive
std::string m_adjustedMarksDebugFilename
bool m_debuggingEnabled
SPMessageHub m_messageHub
int m_msgIdAdaption
SPRefinementProjector m_projector
Constructor & Destructor Documentation
GlobalMultiGridRefiner() [1/2]
ug::GlobalMultiGridRefiner::GlobalMultiGridRefiner (SPRefinementProjector projector = SPNULL)
GlobalMultiGridRefiner() [2/2]
ug::GlobalMultiGridRefiner::GlobalMultiGridRefiner (MultiGrid & mg, SPRefinementProjector projector = SPNULL)
References assign_grid(), and m_pMG.
~GlobalMultiGridRefiner()
ug::GlobalMultiGridRefiner::~GlobalMultiGridRefiner () virtual
References m_pMG, and ug::Grid::unregister_observer().
Member Function Documentation
adaptivity_supported()
virtual bool ug::GlobalMultiGridRefiner::adaptivity_supported () const inline virtual
returns whether the refiner is able to perform adaptive refinement
pure virtual!
Implements ug::IRefiner.
assign_grid() [1/2]
void ug::GlobalMultiGridRefiner::assign_grid (MultiGrid & mg)
Referenced by GlobalMultiGridRefiner().
assign_grid() [2/2]
void ug::GlobalMultiGridRefiner::assign_grid (MultiGrid * mg)
References m_pMG, ug::Grid::message_hub(), num_marked_edges_local(), ug::OT_GRID_OBSERVER, ug::Grid::register_observer(), ug::IRefiner::set_message_hub(), and ug::Grid::unregister_observer().
coarsening_supported()
virtual bool ug::GlobalMultiGridRefiner::coarsening_supported () const inline virtual
returns true, if the refiner supports coarsening.
pure virtual!
Implements ug::IRefiner.
References num_marked_edges_local(), num_marked_elems(), num_marked_faces_local(), num_marked_volumes_local(), perform_refinement(), and save_marks_to_file().
get_associated_grid()
virtual Grid* ug::GlobalMultiGridRefiner::get_associated_grid () inline virtual
DEPRECIATED! Use grid(). Has to return the associated grid. Pure virtual.
Implements ug::IRefiner.
References m_pMG.
grid()
virtual Grid* ug::GlobalMultiGridRefiner::grid () inline virtual
Returns the grid associated with the refiner.
Pure virtual. Specify this method in derived classes!
Implements ug::IRefiner.
References m_pMG.
grid_to_be_destroyed()
void ug::GlobalMultiGridRefiner::grid_to_be_destroyed (Grid * grid) virtual
Reimplemented from ug::GridObserver.
References m_pMG.
multi_grid()
virtual MultiGrid* ug::GlobalMultiGridRefiner::multi_grid () inline virtual
References m_pMG.
num_marked_edges_local()
void ug::GlobalMultiGridRefiner::num_marked_edges_local (std::vector< int > & numMarkedEdgesOut) protected virtual
returns the number of (globally) marked edges on this level of the hierarchy
Implements ug::IRefiner.
References num_marked_faces_local().
Referenced by assign_grid(), and coarsening_supported().
num_marked_elems()
template<class TElem > void ug::GlobalMultiGridRefiner::num_marked_elems (std::vector< int > & numMarkedElemsOut) protected
References m_pMG, ug::MultiGrid::num(), ug::MultiGrid::num_levels(), and ug::MultiGrid::top_level().
Referenced by coarsening_supported(), and num_marked_volumes_local().
num_marked_faces_local()
void ug::GlobalMultiGridRefiner::num_marked_faces_local (std::vector< int > & numMarkedFacesOut) protected virtual
returns the number of (globally) marked faces on this level of the hierarchy
Implements ug::IRefiner.
References num_marked_volumes_local().
Referenced by coarsening_supported(), and num_marked_edges_local().
num_marked_volumes_local()
void ug::GlobalMultiGridRefiner::num_marked_volumes_local (std::vector< int > & numMarkedVolsOut) protected virtual
returns the number of (globally) marked volumes on this level of the hierarchy
Implements ug::IRefiner.
References num_marked_elems().
Referenced by coarsening_supported(), and num_marked_faces_local().
perform_refinement()
void ug::GlobalMultiGridRefiner::perform_refinement () protected virtual
performs refinement on the marked elements.
Implements ug::IRefiner.
References ug::MultiGrid::begin(), ug::MultiGrid::create(), ug::MultiGrid::create_by_cloning(), ug::MultiGrid::enable_hierarchical_insertion(), ug::Grid::enable_options(), ug::MultiGrid::end(), ug::FACEOPT_AUTOGENERATE_EDGES, ug::MultiGrid::get_child_vertex(), ug::Grid::get_edge(), ug::Grid::get_face(), ug::MultiGrid::get_grid_objects(), ug::GMAT_GLOBAL_REFINEMENT_BEGINS, ug::GMAT_GLOBAL_REFINEMENT_ENDS, GMGR_PROFILE, GMGR_PROFILE_END, GMGR_PROFILE_FUNC, ug::MultiGrid::hierarchical_insertion_enabled(), ug::LIB_GRID, LOG, ug::IRefiner::m_messageHub, m_pMG, ug::IRefiner::m_projector, ug::MultiGrid::num(), ug::Face::num_edges(), ug::Volume::num_edges(), ug::Grid::num_faces(), ug::Volume::num_faces(), ug::MultiGrid::num_levels(), ug::FaceVertices::num_vertices(), ug::VolumeVertices::num_vertices(), ug::Grid::num_volumes(), ug::Grid::option_is_enabled(), ug::IRefiner::projector(), ug::Volume::reference_object_id(), ug::Edge::refine(), ug::Face::refine(), ug::Volume::refine(), refinement_is_allowed(), refinement_step_begins(), refinement_step_ends(), ug::Grid::register_element(), ug::Grid::reserve(), ug::ROID_OCTAHEDRON, UG_DLOG, SmartPtr< T, FreePolicy >::valid(), ug::EdgeVertices::vertex(), ug::FaceVertices::vertex(), ug::VolumeVertices::vertex(), and ug::VOLOPT_AUTOGENERATE_FACES.
Referenced by coarsening_supported().
refinement_is_allowed() [1/4]
virtual bool ug::GlobalMultiGridRefiner::refinement_is_allowed (Vertex * elem) inline protected virtual
a callback that allows to deny refinement of special vertices
Referenced by perform_refinement().
refinement_is_allowed() [2/4]
virtual bool ug::GlobalMultiGridRefiner::refinement_is_allowed (Edge * elem) inline protected virtual
a callback that allows to deny refinement of special edges
refinement_is_allowed() [3/4]
virtual bool ug::GlobalMultiGridRefiner::refinement_is_allowed (Face * elem) inline protected virtual
a callback that allows to deny refinement of special faces
refinement_is_allowed() [4/4]
virtual bool ug::GlobalMultiGridRefiner::refinement_is_allowed (Volume * elem) inline protected virtual
a callback that allows to deny refinement of special volumes
refinement_step_begins()
virtual void ug::GlobalMultiGridRefiner::refinement_step_begins () inline protected virtual
this method helps derived classes to perform operations directly before actual element refinment is performed.
Called from the refine() method in each refinement-iteration after collect_objects_for_refine(). Default implementation is empty.
Referenced by perform_refinement().
refinement_step_ends()
virtual void ug::GlobalMultiGridRefiner::refinement_step_ends () inline protected virtual
this method helps derived classes to perform operations directly after actual element refinment took place.
Called from the refine() method in each refinement-iteration after all scheduled elements had been refined. The refine process will either terminate after this method or will start a new iteration, if new elements had been marked during refine. Default implementation is empty.
References m_pMG.
Referenced by perform_refinement().
save_marks_to_file()
bool ug::GlobalMultiGridRefiner::save_marks_to_file (const char * filename) virtual
Writes the associated grid and marks to a file. Pure virtual.
Elements should be assigned to subsets depending on their current refinement-mark.
Implements ug::IRefiner.
References ug::GridSubsetHandler::assign_subset(), ug::AssignGridToSubset(), ug::AssignSubsetColors(), ug::MultiGrid::begin(), ug::MultiGrid::end(), GMGR_PROFILE, m_pMG, ug::SubsetInfo::name, ug::MultiGrid::num_levels(), ug::SaveGridToFile(), ug::ISubsetHandler::subset_info(), and UG_THROW.
Referenced by coarsening_supported().
Member Data Documentation
m_pMG
MultiGrid* ug::GlobalMultiGridRefiner::m_pMG protected
Referenced by assign_grid(), get_associated_grid(), GlobalMultiGridRefiner(), grid(), grid_to_be_destroyed(), multi_grid(), num_marked_elems(), perform_refinement(), refinement_step_ends(), save_marks_to_file(), and ~GlobalMultiGridRefiner().
The documentation for this class was generated from the following files:
ugbase/lib_grid/refinement/global_multi_grid_refiner.h
ugbase/lib_grid/refinement/global_multi_grid_refiner.cpp