ug4: ug::BinaryBuffer Class Reference
ug::BinaryBuffer Class Reference
ugbase » Common » Common Utilities » Common IO
A Buffer for binary data.
#include <binary_buffer.h>
Public Member Functions
BinaryBuffer ()
BinaryBuffer (size_t bufSize)
creates a binary buffer and reserves bufSize bytes.
char * buffer ()
returns the raw buffer pointer or NULL if the buffer is empty (capacity() == 0)
size_t capacity () const
returns the capacity (reserved memory) of the buffer
void clear ()
clears the buffer
bool eof ()
returns true if the read-position reached the write-position
void read (char *buf, size_t size)
reads data of the given size (in bytes)
size_t read_pos () const
returns the current read-pos (in bytes)
void reserve (size_t newSize)
resizes the associated buffer to the given size.
void set_read_pos (size_t pos)
sets the read position (in bytes).
void set_write_pos (size_t pos)
sets the write position.
void write (const char *buf, size_t size)
writes data of the given size (in bytes)
size_t write_pos () const
returns the current write-pos (in bytes)
Private Attributes
std::vector< char > m_data
size_t m_readPos
size_t m_writePos
Detailed Description
A Buffer for binary data.
The BinaryBuffer allows read and write access, which mimics the behavior of std::iostream. However, in contrary to ug::BinaryStream, this class is not a specialization of std::iostream. This is crucial to achieve maximal performance.
Furthermore BinaryBuffer gives access to its internal buffer, which can be handy in some situations. However, this feature has to be used with extreme care!
Constructor & Destructor Documentation
BinaryBuffer() [1/2]
ug::BinaryBuffer::BinaryBuffer ()
BinaryBuffer() [2/2]
ug::BinaryBuffer::BinaryBuffer (size_t bufSize)
creates a binary buffer and reserves bufSize bytes.
Member Function Documentation
buffer()
char * ug::BinaryBuffer::buffer () inline
returns the raw buffer pointer or NULL if the buffer is empty (capacity() == 0)
References ug::GetDataPtr(), and m_data.
Referenced by ug::AddConnectionsBetweenSlaves(), pcl::ProcessCommunicator::broadcast(), pcl::ParallelArchive::BufferBinaryBuffer::buffer(), pcl::InterfaceCommunicator< TLayout >::communicate_and_resume(), ug::CommunicateOnInterfaces(), pcl::ProcessCommunicator::distribute_data(), pcl::ProcessCommunicator::gather(), ug::NewLayoutCreator::issue(), ug::ParallelNodes::issue(), ug::RowSendingScheme< matrix_type >::issue_send(), ug::LoadGridFromLGB(), ug::ComPol_MatCreateOverlap< TMatrix >::post_process(), ug::SaveGridToLGB(), ug::SendGlobalLayout(), ug::SendMatrix(), pcl::TestSizeOfInterfacesInLayoutsMatch(), pcl::InterfaceCommunicator< TLayout >::wait(), and pcl::WriteCombinedParallelFile().
capacity()
size_t ug::BinaryBuffer::capacity () const inline
returns the capacity (reserved memory) of the buffer
References m_data.
clear()
void ug::BinaryBuffer::clear ()
clears the buffer
This method does not free associated memory. It only resets the read and write positions. To free the memory you may create a new instance of ug::BinaryBuffer and assign it by value to your current instance.
References m_readPos, and m_writePos.
Referenced by pcl::ProcessCommunicator::distribute_data(), pcl::MinimalKeyValuePairAcrossAllProcs(), pcl::ReadCombinedParallelFile(), and pcl::InterfaceCommunicator< TLayout >::wait().
eof()
bool ug::BinaryBuffer::eof () inline
returns true if the read-position reached the write-position
References m_readPos, and m_writePos.
Referenced by ug::AddConnectionsBetweenSlaves(), ug::DeserializeGridElements(), ug::DeserializeMultiGridElements(), ug::NewLayoutCreator::process(), ug::ParallelNodes::process(), ug::ReadGridHeader(), and pcl::TestSizeOfInterfacesInLayoutsMatch().
read()
void ug::BinaryBuffer::read (char * buf, size_t size) inline
reads data of the given size (in bytes)
This automatically advances the read position.
References m_data, m_readPos, and m_writePos.
Referenced by ug::DeserializeAttachment(), ug::DeserializeGridElements(), ug::DeserializeMultiGridElements(), ug::DeserializeProjectionHandler(), ug::DeserializeSelector(), ug::DeserializeSubsetHandler(), ug::DistributeGrid(), ug::ComPol_AdjustType< TLayout >::extract(), ug::ComPol_BroadcastCoarsenMarks< TLayout >::extract(), ug::ComPol_BroadcastRefineMarks< TLayout >::extract(), ug::ComPol_BoolMarker_AddMarks< TLayout >::extract(), ug::ComPol_BoolMarker_RemoveMarks< TLayout >::extract(), ug::ComPol_InterfaceStatus< TLayout >::extract(), ug::ComPol_Selection< TLayout >::extract(), ug::ComPol_EnableSelectionStateBits< TLayout >::extract(), ug::ComPol_Subset< TLayout >::extract(), ug::ComPol_GatherSurfaceStates< TLayout >::extract(), pcl::SelectionCommPol< TLayout, TSelectorIn, TSelectorOut >::extract(), ug::GetParent(), ug::LoadGridFromLGB(), ug::ReadGridHeader(), ug::ReadSelectionStatesFromStream(), ug::ReadSubsetIndicesFromStream(), and pcl::InterfaceCommunicator< TLayout >::wait().
read_pos()
size_t ug::BinaryBuffer::read_pos () const inline
returns the current read-pos (in bytes)
References m_readPos.
Referenced by ug::ComPol_MatCreateOverlap< TMatrix >::post_process().
reserve()
void ug::BinaryBuffer::reserve (size_t newSize)
resizes the associated buffer to the given size.
You can check the number of bytes reserved in the buffer through ug::BinaryBuffer::capacity
References m_data.
Referenced by pcl::ProcessCommunicator::broadcast(), pcl::InterfaceCommunicator< TLayout >::communicate_and_resume(), pcl::ProcessCommunicator::distribute_data(), pcl::ProcessCommunicator::gather(), ug::LoadGridFromLGB(), pcl::ReadCombinedParallelFile(), and pcl::InterfaceCommunicator< TLayout >::wait().
set_read_pos()
void ug::BinaryBuffer::set_read_pos (size_t pos)
sets the read position (in bytes).
References m_readPos.
Referenced by ug::ReceiveMatrix().
set_write_pos()
void ug::BinaryBuffer::set_write_pos (size_t pos)
sets the write position.
References m_writePos.
Referenced by pcl::ProcessCommunicator::broadcast(), pcl::InterfaceCommunicator< TLayout >::communicate_and_resume(), pcl::ProcessCommunicator::distribute_data(), pcl::ProcessCommunicator::gather(), ug::LoadGridFromLGB(), and pcl::InterfaceCommunicator< TLayout >::wait().
write()
void ug::BinaryBuffer::write (const char * buf, size_t size) inline
writes data of the given size (in bytes)
This automatically advances the write position.
References m_data, and m_writePos.
Referenced by ug::ComPol_AdjustType< TLayout >::collect(), ug::ComPol_BroadcastCoarsenMarks< TLayout >::collect(), ug::ComPol_BroadcastRefineMarks< TLayout >::collect(), ug::ComPol_BoolMarker_AddMarks< TLayout >::collect(), ug::ComPol_BoolMarker_RemoveMarks< TLayout >::collect(), ug::ComPol_InterfaceStatus< TLayout >::collect(), ug::ComPol_Selection< TLayout >::collect(), ug::ComPol_EnableSelectionStateBits< TLayout >::collect(), ug::ComPol_Subset< TLayout >::collect(), ug::ComPol_GatherSurfaceStates< TLayout >::collect(), pcl::SelectionCommPol< TLayout, TSelectorIn, TSelectorOut >::collect(), ug::DistributeGrid(), pcl::ReadCombinedParallelFile(), ug::SaveGridToLGB(), pcl::InterfaceCommunicator< TLayout >::send_raw(), ug::SerializeAttachment(), ug::SerializeGridElements(), ug::SerializeMultiGridElements(), ug::SerializeProjectionHandler(), ug::SerializeSelector(), ug::SerializeSubsetHandler(), ug::WriteGridHeader(), ug::WriteParent(), ug::WriteSelectionStatesToStream(), and ug::WriteSubsetIndicesToStream().
write_pos()
size_t ug::BinaryBuffer::write_pos () const inline
returns the current write-pos (in bytes)
References m_writePos.
Referenced by ug::AddConnectionsBetweenSlaves(), pcl::ProcessCommunicator::broadcast(), pcl::InterfaceCommunicator< TLayout >::communicate_and_resume(), ug::CommunicateOnInterfaces(), pcl::ProcessCommunicator::gather(), ug::NewLayoutCreator::issue(), ug::ParallelNodes::issue(), ug::RowSendingScheme< matrix_type >::issue_send(), ug::ComPol_MatCreateOverlap< TMatrix >::post_process(), ug::NewLayoutCreator::process(), ug::ParallelNodes::process(), ug::ReceiveGlobalLayout(), ug::ReceiveMatrix(), ug::SaveGridToLGB(), ug::SendGlobalLayout(), ug::SendMatrix(), pcl::ParallelArchive::BufferBinaryBuffer::size(), pcl::TestSizeOfInterfacesInLayoutsMatch(), and pcl::WriteCombinedParallelFile().
Member Data Documentation
m_data
std::vector<char> ug::BinaryBuffer::m_data private
Referenced by buffer(), capacity(), read(), reserve(), and write().
m_readPos
size_t ug::BinaryBuffer::m_readPos private
Referenced by clear(), eof(), read(), read_pos(), and set_read_pos().
m_writePos
size_t ug::BinaryBuffer::m_writePos private
Referenced by clear(), eof(), read(), set_write_pos(), write(), and write_pos().
The documentation for this class was generated from the following files:
ugbase/common/util/binary_buffer.h
ugbase/common/util/binary_buffer.cpp
ugbase/common/util/binary_buffer_impl.h