ug4: ug::GradientEvaluator_LagrangeP1< TFunction > Class Template Reference
ug::GradientEvaluator_LagrangeP1< TFunction > Class Template Reference
#include <gradient_evaluators.h>
Public Types
typedef TFunction::element_type elem_t
typedef MathVector< dim > vector_t
Public Member Functions
vector_t evaluate (elem_t *elem)
GradientEvaluator_LagrangeP1 (TFunction *u, size_t fct)
Static Public Attributes
static const int dim = TFunction::dim
Private Attributes
MathMatrix< dim, dim > JTInv
TFunction::domain_type::position_accessor_type m_aaPos
size_t m_fct
TFunction * m_pu
std::vector< vector_t > vCorner
std::vector< vector_t > vGlobalGrad
std::vector< vector_t > vLocalGrad
Detailed Description
template<class TFunction>
class ug::GradientEvaluator_LagrangeP1< TFunction >
Provides a function to evaluate the gradient of a given grid function efficiently in each element.
Member Typedef Documentation
elem_t
template<class TFunction > typedef TFunction::element_type ug::GradientEvaluator_LagrangeP1< TFunction >::elem_t
vector_t
template<class TFunction > typedef MathVector<dim> ug::GradientEvaluator_LagrangeP1< TFunction >::vector_t
Constructor & Destructor Documentation
GradientEvaluator_LagrangeP1()
template<class TFunction > ug::GradientEvaluator_LagrangeP1< TFunction >::GradientEvaluator_LagrangeP1 (TFunction * u, size_t fct) inline
Member Function Documentation
evaluate()
template<class TFunction > vector_t ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate (elem_t * elem) inline
References ug::CollectCornerCoordinates(), ug::GradientEvaluator_LagrangeP1< TFunction >::dim, ug::DoFRef(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::DimReferenceMapping< TDim, TWorldDim >::jacobian_transposed_inverse(), ug::GradientEvaluator_LagrangeP1< TFunction >::JTInv, ug::LFEID::LAGRANGE, ug::GradientEvaluator_LagrangeP1< TFunction >::m_aaPos, ug::GradientEvaluator_LagrangeP1< TFunction >::m_fct, ug::GradientEvaluator_LagrangeP1< TFunction >::m_pu, ug::MatVecMult(), ug::LocalDoFSet::num_sh(), ug::DimReferenceMapping< TDim, TWorldDim >::update(), ug::GradientEvaluator_LagrangeP1< TFunction >::vCorner, ug::VecSet(), ug::GradientEvaluator_LagrangeP1< TFunction >::vGlobalGrad, and ug::GradientEvaluator_LagrangeP1< TFunction >::vLocalGrad.
Member Data Documentation
dim
template<class TFunction > const int ug::GradientEvaluator_LagrangeP1< TFunction >::dim = TFunction::dim static
Referenced by ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate().
JTInv
template<class TFunction > MathMatrix<dim, dim> ug::GradientEvaluator_LagrangeP1< TFunction >::JTInv private
Referenced by ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate().
m_aaPos
template<class TFunction > TFunction::domain_type::position_accessor_type ug::GradientEvaluator_LagrangeP1< TFunction >::m_aaPos private
Referenced by ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate().
m_fct
template<class TFunction > size_t ug::GradientEvaluator_LagrangeP1< TFunction >::m_fct private
Referenced by ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate().
m_pu
template<class TFunction > TFunction* ug::GradientEvaluator_LagrangeP1< TFunction >::m_pu private
Referenced by ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate().
vCorner
template<class TFunction > std::vector<vector_t > ug::GradientEvaluator_LagrangeP1< TFunction >::vCorner private
Referenced by ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate().
vGlobalGrad
template<class TFunction > std::vector<vector_t > ug::GradientEvaluator_LagrangeP1< TFunction >::vGlobalGrad private
Referenced by ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate().
vLocalGrad
template<class TFunction > std::vector<vector_t > ug::GradientEvaluator_LagrangeP1< TFunction >::vLocalGrad private
Referenced by ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/gradient_evaluators.h