ug4: ug::GMRES< TVector > Class Template Reference
ug::GMRES< TVector > Class Template Reference
the GMREs method as a solver for linear operators
#include <gmres.h>
Public Types
typedef IPreconditionedLinearOperatorInverse< vector_type > base_type
Base type.
typedef TVector vector_type
Vector type.
Public Types inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
typedef ILinearOperatorInverse< TVector, TVector > base_type
Base class.
typedef TVector codomain_function_type
Range space.
typedef TVector domain_function_type
Domain space.
Public Types inherited from ug::ILinearOperatorInverse< TVector >
typedef TVector codomain_function_type
Range space.
typedef TVector domain_function_type
Domain space.
Public Types inherited from ug::ILinearIterator< TVector, TVector >
typedef TVector codomain_function_type
Range space.
typedef TVector domain_function_type
Domain space.
Public Types inherited from ug::VectorDebugWritingObject< TVector >
typedef TVector vector_type
type of vector
Public Member Functions
virtual bool apply_return_defect (vector_type &x, vector_type &b)
applies inverse operator, i.e. returns u = A^{-1} f and returns defect d := f - A*u
virtual std::string config_string () const
returns information about configuration parameters
GMRES (size_t restart)
default constructor
GMRES (size_t restart, SmartPtr< ILinearIterator< vector_type > > spPrecond, SmartPtr< IConvergenceCheck< vector_type > > spConvCheck)
constructor setting the preconditioner and the convergence check
virtual const char * name () const
name of solver
virtual bool supports_parallel () const
returns if parallel solving is supported
Public Member Functions inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
virtual bool apply (TVector &x, const TVector &b)
applies inverse operator, i.e. returns u = A^{-1} f
std::string config_string_preconditioner_convergence_check () const
returns config information of convergence check and preconditioner
virtual bool init (SmartPtr< ILinearOperator< TVector, TVector > > J, const TVector &u)
initializes the solver for an operator
virtual bool init (SmartPtr< ILinearOperator< TVector, TVector > > L)
initializes the solver for an operator
IPreconditionedLinearOperatorInverse ()
Empty constructor.
IPreconditionedLinearOperatorInverse (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond)
constructor setting the preconditioner
IPreconditionedLinearOperatorInverse (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond, SmartPtr< IConvergenceCheck< TVector > > spConvCheck)
constructor setting the preconditioner
void set_compute_fresh_defect_when_finished (bool bRecompute)
for debug: computes norm again after whole calculation of apply
void set_preconditioner (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond)
sets the preconditioner
SmartPtr< ILinearIterator< TVector, TVector > > preconditioner ()
ConstSmartPtr< ILinearIterator< TVector, TVector > > preconditioner () const
Public Member Functions inherited from ug::ILinearOperatorInverse< TVector >
virtual bool apply_update_defect (TVector &u, TVector &f)
compute new correction c = B*d and update defect d := d - A*c
virtual SmartPtr< ILinearIterator< TVector, TVector > > clone ()
clone
ConstSmartPtr< IConvergenceCheck< TVector > > convergence_check () const
returns the convergence check
SmartPtr< IConvergenceCheck< TVector > > convergence_check ()
returns the convergence check
number defect () const
returns the current defect
ILinearOperatorInverse ()
constructor setting convergence check to (100, 1e-12, 1e-12, true)
ILinearOperatorInverse (SmartPtr< IConvergenceCheck< TVector > > spConvCheck)
Default constructor.
SmartPtr< ILinearOperator< TVector, TVector > > linear_operator ()
returns the current Operator this Inverse Operator is initialized for
number reduction () const
returns the current relative reduction
void set_convergence_check (SmartPtr< IConvergenceCheck< TVector > > spConvCheck)
set the convergence check
virtual int standard_offset () const
returns the standard offset for output
int step () const
returns the current number of steps
virtual ~ILinearOperatorInverse ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TVector, TVector >
SmartPtr< IDamping< TVector, TVector > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TVector, TVector > &parent)
copy constructor
void set_damp (SmartPtr< IDamping< TVector, TVector > > spScaling)
sets a scaling for the correction
void set_damp (number factor)
sets the damping to a constant factor
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TVector >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
void prepare_conv_check ()
prepares the output of the convergence check
number VecProd (vector_type &a, vector_type &b)
computes the vector product
bool VecScaleAppend (vector_type &a, vector_type &b, number s)
adds a scaled vector to a second one
Protected Member Functions inherited from ug::VectorDebugWritingObject< TVector >
virtual void write_debug (const vector_type &vec, std::string filename)
virtual void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
Protected Attributes
size_t m_restart
restart parameter
Protected Attributes inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
bool m_bRecompute
flag if fresh defect should be computed when finish for debug purpose
SmartPtr< ILinearIterator< TVector, TVector > > m_spPrecond
Iterator used in the iterative scheme to compute the correction and update the defect.
Protected Attributes inherited from ug::ILinearOperatorInverse< TVector >
SmartPtr< IConvergenceCheck< TVector > > m_spConvCheck
smart pointer holding the convergence check
SmartPtr< ILinearOperator< TVector, TVector > > m_spLinearOperator
Operator that is inverted by this Inverse Operator.
Protected Attributes inherited from ug::ILinearIterator< TVector, TVector >
SmartPtr< IDamping< TVector, TVector > > m_spDamping
the scaling
Protected Attributes inherited from ug::VectorDebugWritingObject< TVector >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Detailed Description
template<typename TVector>
class ug::GMRES< TVector >
the GMREs method as a solver for linear operators
This class implements the GMRES - method for the solution of linear operator problems like A*x = b, where the solution x = A^{-1} b is computed.
For detailed description of the algorithm, please refer to:
Barrett, Berry, Chan, Demmel, Donatom Dongarra, Eijkhout, Pozo, Romine, Van der Vorst, "Templates for the Solution of Linear Systems: Building Blocks for Iterative Methods"
Saad, "Iterative Methods For Sparse Linear Systems"
Template Parameters
TVector vector type
Member Typedef Documentation
template<typename TVector > typedef IPreconditionedLinearOperatorInverse<vector_type> ug::GMRES< TVector >::base_type
Base type.
template<typename TVector > typedef TVector ug::GMRES< TVector >::vector_type
Vector type.
Constructor & Destructor Documentation
template<typename TVector > ug::GMRES< TVector >::GMRES (size_t restart) inline
default constructor
template<typename TVector > ug::GMRES< TVector >::GMRES (size_t restart, SmartPtr< ILinearIterator< vector_type > > spPrecond, SmartPtr< IConvergenceCheck< vector_type > > spConvCheck) inline
constructor setting the preconditioner and the convergence check
Member Function Documentation
template<typename TVector > virtual bool ug::GMRES< TVector >::apply_return_defect (vector_type & u, vector_type & f) inline virtual
applies inverse operator, i.e. returns u = A^{-1} f and returns defect d := f - A*u
This method applies the inverse operator, i.e. u = A^{-1} f. The domain function f is changed in the way, that the defect d := f - A*u is returned in the function. This is always useful, when the inverting algorithm can (or must) update the defect during computation (this is e.g. the case for the geometric multigrid method). Note, that this method can always be implemented by calling apply and then computing d := f - A*u.
Parameters
[in,out] f right-hand side
[out] u solution
Returns
bool success flag
Implements ug::ILinearOperatorInverse< TVector >.
References alpha, ug::IPreconditionedLinearOperatorInverse< TVector >::apply(), ug::ILinearOperatorInverse< TVector >::convergence_check(), ug::ILinearOperatorInverse< TVector >::linear_operator(), ug::GMRES< TVector >::m_restart, ug::IPreconditionedLinearOperatorInverse< TVector >::preconditioner(), ug::GMRES< TVector >::prepare_conv_check(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::PST_UNIQUE, resize(), UG_LOG, UG_THROW, ug::GMRES< TVector >::VecProd(), and ug::GMRES< TVector >::VecScaleAppend().
template<typename TVector > virtual std::string ug::GMRES< TVector >::config_string () const inline virtual
returns information about configuration parameters
Reimplemented from ug::IPreconditionedLinearOperatorInverse< TVector >.
References ug::IPreconditionedLinearOperatorInverse< vector_type >::config_string_preconditioner_convergence_check(), and ug::GMRES< TVector >::m_restart.
template<typename TVector > virtual const char* ug::GMRES< TVector >::name () const inline virtual
name of solver
Implements ug::ILinearOperatorInverse< TVector >.
Referenced by ug::GMRES< TVector >::prepare_conv_check().
template<typename TVector > void ug::GMRES< TVector >::prepare_conv_check () inline protected
prepares the output of the convergence check
References ug::ILinearOperatorInverse< TVector >::convergence_check(), ug::GMRES< TVector >::name(), and ug::IPreconditionedLinearOperatorInverse< TVector >::preconditioner().
Referenced by ug::GMRES< TVector >::apply_return_defect().
template<typename TVector > virtual bool ug::GMRES< TVector >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearOperatorInverse< TVector >.
References ug::IPreconditionedLinearOperatorInverse< TVector >::preconditioner().
template<typename TVector > number ug::GMRES< TVector >::VecProd (vector_type & a, vector_type & b) inline protected
computes the vector product
Referenced by ug::GMRES< TVector >::apply_return_defect().
template<typename TVector > bool ug::GMRES< TVector >::VecScaleAppend (vector_type & a, vector_type & b, number s) inline protected
adds a scaled vector to a second one
References ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::PST_UNIQUE, and ug::VecScaleAdd().
Referenced by ug::GMRES< TVector >::apply_return_defect().
Member Data Documentation
template<typename TVector > size_t ug::GMRES< TVector >::m_restart protected
restart parameter
Referenced by ug::GMRES< TVector >::apply_return_defect(), and ug::GMRES< TVector >::config_string().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/linear_solver/gmres.h