ug4: ug::DenseMatrixInverse< TStorage > Class Template Reference
ug::DenseMatrixInverse< TStorage > Class Template Reference
#include <lapack_densematrix_inverse.h>
Public Member Functions
template<typename vector_t >
void apply (DenseVector< vector_t > &vec) const
template<typename vector_t >
void apply (DenseVector< vector_t > &vec) const
bool invert ()
bool invert ()
size_t num_cols () const
size_t num_cols () const
size_t num_rows () const
size_t num_rows () const
double & operator() (int r, int c)
double & operator() (int r, int c)
const double & operator() (int r, int c) const
const double & operator() (int r, int c) const
void resize (size_t k)
void resize (size_t k)
void resize (size_t k, size_t k2)
void resize (size_t k, size_t k2)
bool set_as_inverse_of (const DenseMatrix< TStorage > &mat)
initializes this object as inverse of mat
bool set_as_inverse_of (const DenseMatrix< TStorage > &mat)
initializes this object as inverse of mat
Private Attributes
DenseMatrix< TStorage > densemat
std::vector< lapack_int > interchange
std::vector< size_t > interchange
Friends
template<typename T >
std::ostream & operator<< (std::ostream &out, const DenseMatrixInverse< T > &mat)
template<typename T >
std::ostream & operator<< (std::ostream &out, const DenseMatrixInverse< T > &mat)
Detailed Description
template<typename TStorage>
class ug::DenseMatrixInverse< TStorage >
smallInverse<size_t n> A class to hold a inverse of a smallMatrix<n> implemented with LAPACKs LU-Decomposition dgetrf (uses double[n*n] for LU and interchange[n] for pivoting
smallInverse<size_t n> A class to hold a inverse of a smallMatrix<n>
Member Function Documentation
apply() [1/2]
template<typename TStorage > template<typename vector_t > void ug::DenseMatrixInverse< TStorage >::apply (DenseVector< vector_t > & vec) const inline
References ug::DenseMatrixInverse< TStorage >::densemat, ug::getrs(), ug::DenseMatrixInverse< TStorage >::interchange, ug::ModeNoTrans, ug::DenseMatrixInverse< TStorage >::num_rows(), and UG_COND_THROW.
Referenced by ug::MatMult(), and ug::MatMultAdd().
apply() [2/2]
template<typename TStorage > template<typename vector_t > void ug::DenseMatrixInverse< TStorage >::apply (DenseVector< vector_t > & vec) const inline
References ug::DenseMatrixInverse< TStorage >::densemat, ug::DenseMatrixInverse< TStorage >::interchange, and ug::SolveLU().
invert() [1/2]
template<typename TStorage > bool ug::DenseMatrixInverse< TStorage >::invert () inline
References ug::DenseMatrixInverse< TStorage >::densemat, ug::getrf(), ug::DenseMatrixInverse< TStorage >::interchange, and UG_THROW.
Referenced by ug::DenseMatrixInverse< TStorage >::set_as_inverse_of().
invert() [2/2]
template<typename TStorage > bool ug::DenseMatrixInverse< TStorage >::invert () inline
References ug::DenseMatrixInverse< TStorage >::densemat, ug::DenseMatrixInverse< TStorage >::interchange, ug::LUDecomp(), and UG_LOG.
num_cols() [1/2]
template<typename TStorage > size_t ug::DenseMatrixInverse< TStorage >::num_cols () const inline
References ug::DenseMatrixInverse< TStorage >::densemat.
num_cols() [2/2]
template<typename TStorage > size_t ug::DenseMatrixInverse< TStorage >::num_cols () const inline
References ug::DenseMatrixInverse< TStorage >::densemat.
num_rows() [1/2]
template<typename TStorage > size_t ug::DenseMatrixInverse< TStorage >::num_rows () const inline
References ug::DenseMatrixInverse< TStorage >::densemat.
Referenced by ug::DenseMatrixInverse< TStorage >::apply().
num_rows() [2/2]
template<typename TStorage > size_t ug::DenseMatrixInverse< TStorage >::num_rows () const inline
References ug::DenseMatrixInverse< TStorage >::densemat.
operator()() [1/4]
template<typename TStorage > double& ug::DenseMatrixInverse< TStorage >::operator() (int r, int c) inline
References ug::DenseMatrixInverse< TStorage >::densemat.
operator()() [2/4]
template<typename TStorage > double& ug::DenseMatrixInverse< TStorage >::operator() (int r, int c) inline
References ug::DenseMatrixInverse< TStorage >::densemat.
operator()() [3/4]
template<typename TStorage > const double& ug::DenseMatrixInverse< TStorage >::operator() (int r, int c) const inline
References ug::DenseMatrixInverse< TStorage >::densemat.
operator()() [4/4]
template<typename TStorage > const double& ug::DenseMatrixInverse< TStorage >::operator() (int r, int c) const inline
References ug::DenseMatrixInverse< TStorage >::densemat.
resize() [1/4]
template<typename TStorage > void ug::DenseMatrixInverse< TStorage >::resize (size_t k) inline
References ug::DenseMatrixInverse< TStorage >::densemat.
Referenced by ug::DenseMatrixInverse< TStorage >::resize().
resize() [2/4]
template<typename TStorage > void ug::DenseMatrixInverse< TStorage >::resize (size_t k) inline
References ug::DenseMatrixInverse< TStorage >::densemat.
resize() [3/4]
template<typename TStorage > void ug::DenseMatrixInverse< TStorage >::resize (size_t k, size_t k2) inline
References ug::DenseMatrixInverse< TStorage >::resize(), and UG_COND_THROW.
resize() [4/4]
template<typename TStorage > void ug::DenseMatrixInverse< TStorage >::resize (size_t k, size_t k2) inline
References ug::DenseMatrixInverse< TStorage >::resize(), and UG_COND_THROW.
set_as_inverse_of() [1/2]
template<typename TStorage > bool ug::DenseMatrixInverse< TStorage >::set_as_inverse_of (const DenseMatrix< TStorage > & mat) inline
initializes this object as inverse of mat
References ug::DenseMatrixInverse< TStorage >::densemat, ug::DenseMatrixInverse< TStorage >::invert(), and UG_COND_THROW.
set_as_inverse_of() [2/2]
template<typename TStorage > bool ug::DenseMatrixInverse< TStorage >::set_as_inverse_of (const DenseMatrix< TStorage > & mat) inline
initializes this object as inverse of mat
References ug::DenseMatrixInverse< TStorage >::densemat, ug::DenseMatrixInverse< TStorage >::invert(), and UG_ASSERT.
Friends And Related Function Documentation
operator<< [1/2]
template<typename TStorage > template<typename T > std::ostream& operator<< (std::ostream & out, const DenseMatrixInverse< T > & mat) friend
operator<< [2/2]
template<typename TStorage > template<typename T > std::ostream& operator<< (std::ostream & out, const DenseMatrixInverse< T > & mat) friend
Member Data Documentation
densemat
template<typename TStorage > DenseMatrix< TStorage > ug::DenseMatrixInverse< TStorage >::densemat private
Referenced by ug::DenseMatrixInverse< TStorage >::apply(), ug::DenseMatrixInverse< TStorage >::invert(), ug::DenseMatrixInverse< TStorage >::num_cols(), ug::DenseMatrixInverse< TStorage >::num_rows(), ug::DenseMatrixInverse< TStorage >::operator()(), ug::DenseMatrixInverse< TStorage >::resize(), and ug::DenseMatrixInverse< TStorage >::set_as_inverse_of().
interchange [1/2]
template<typename TStorage > std::vector<lapack_int> ug::DenseMatrixInverse< TStorage >::interchange private
Referenced by ug::DenseMatrixInverse< TStorage >::apply(), and ug::DenseMatrixInverse< TStorage >::invert().
interchange [2/2]
template<typename TStorage > std::vector<size_t> ug::DenseMatrixInverse< TStorage >::interchange private
The documentation for this class was generated from the following files:
ugbase/lib_algebra/small_algebra/lapack/lapack_densematrix_inverse.h
ugbase/lib_algebra/small_algebra/no_lapack/lu_decomp.h