ug4: ug::GridFunctionOrdering< TDomain, TAlgebra > Class Template Reference
ug::GridFunctionOrdering< TDomain, TAlgebra > Class Template Reference
Public Member Functions
SmartPtr< TGridFunctionNumberData > get ()
GridFunctionOrdering (SmartPtr< TGridFunction > spGridFct, const char *name)
Private Types
typedef GridFunction< TDomain, TAlgebra > TGridFunction
typedef GridFunctionNumberData< GridFunction< TDomain, TAlgebra > > TGridFunctionNumberData
typedef TGridFunction::template traits< Vertex >::const_iterator VertexConstIterator
Private Attributes
const char * m_name
SmartPtr< TGridFunction > m_u
Member Typedef Documentation
TGridFunction
template<typename TDomain , typename TAlgebra > typedef GridFunction<TDomain, TAlgebra> ug::GridFunctionOrdering< TDomain, TAlgebra >::TGridFunction private
TGridFunctionNumberData
template<typename TDomain , typename TAlgebra > typedef GridFunctionNumberData<GridFunction<TDomain, TAlgebra> > ug::GridFunctionOrdering< TDomain, TAlgebra >::TGridFunctionNumberData private
VertexConstIterator
template<typename TDomain , typename TAlgebra > typedef TGridFunction::template traits<Vertex>::const_iterator ug::GridFunctionOrdering< TDomain, TAlgebra >::VertexConstIterator private
Constructor & Destructor Documentation
GridFunctionOrdering()
template<typename TDomain , typename TAlgebra > ug::GridFunctionOrdering< TDomain, TAlgebra >::GridFunctionOrdering (SmartPtr< TGridFunction > spGridFct, const char * name) inline
References ug::GridFunction< TDomain, TAlgebra >::clone_without_values(), ug::DoFRef(), ug::GridFunction< TDomain, TAlgebra >::inner_dof_indices(), ug::GridFunctionOrdering< TDomain, TAlgebra >::m_name, ug::GridFunctionOrdering< TDomain, TAlgebra >::m_u, and name.
Member Function Documentation
get()
template<typename TDomain , typename TAlgebra > SmartPtr<TGridFunctionNumberData> ug::GridFunctionOrdering< TDomain, TAlgebra >::get () inline
References ug::GridFunctionOrdering< TDomain, TAlgebra >::m_name, and ug::GridFunctionOrdering< TDomain, TAlgebra >::m_u.
Member Data Documentation
m_name
template<typename TDomain , typename TAlgebra > const char* ug::GridFunctionOrdering< TDomain, TAlgebra >::m_name private
Referenced by ug::GridFunctionOrdering< TDomain, TAlgebra >::get(), and ug::GridFunctionOrdering< TDomain, TAlgebra >::GridFunctionOrdering().
m_u
template<typename TDomain , typename TAlgebra > SmartPtr<TGridFunction> ug::GridFunctionOrdering< TDomain, TAlgebra >::m_u private
Referenced by ug::GridFunctionOrdering< TDomain, TAlgebra >::get(), and ug::GridFunctionOrdering< TDomain, TAlgebra >::GridFunctionOrdering().
The documentation for this class was generated from the following file:
ugbase/lib_disc/ordering_strategies/io_grid_function_ordering.cpp