ug4: ug::bridge::ClassHierarchy Class Reference
ug::bridge::ClassHierarchy Class Reference
ugbase » Bridge » Registry
Class Hierarchy Helper Class for UG Registry This class stores class names and their subclasses.
#include <class_helper.h>
Public Member Functions
ClassHierarchy ()
ClassHierarchy * find_class (const char *name)
void insert_class (const IExportedClass &c)
bool operator< (const ClassHierarchy &other) const
void sort ()
Public Attributes
bool bGroup
std::string name
std::vector< ClassHierarchy > subclasses
Detailed Description
Class Hierarchy Helper Class for UG Registry This class stores class names and their subclasses.
See also
GetClassHierarchy
Constructor & Destructor Documentation
ClassHierarchy()
ug::bridge::ClassHierarchy::ClassHierarchy () inline
Member Function Documentation
find_class()
ClassHierarchy * ug::bridge::ClassHierarchy::find_class (const char * name)
searches the hierarchy for the classname name.
Parameters
name class name to be searched
Returns
NULL if class name not found, otherwise ClassHierarchy with the class as base (find_class(name)->name() == name)
References find_class(), and name.
Referenced by ug::bridge::ClassHierarchyString(), and find_class().
insert_class()
void ug::bridge::ClassHierarchy::insert_class (const IExportedClass & c)
adds the class c to the class hierarchy by attaching it to its base hierarchy (base hierarchy taken from c->class_names()). automatically creates nonexisting base hierarchy.
Parameters
c Class to be inserted
References bGroup, ug::bridge::IExportedClass::class_names(), ug::bridge::IExportedClass::group(), name, subclasses, ug::TokenizeString(), and ug::TrimString().
Referenced by ug::bridge::GetClassHierarchy().
operator<()
bool ug::bridge::ClassHierarchy::operator< (const ClassHierarchy & other) const inline
References name, and name.
sort()
void ug::bridge::ClassHierarchy::sort ()
Referenced by ug::bridge::GetClassHierarchy().
Member Data Documentation
bGroup
bool ug::bridge::ClassHierarchy::bGroup
Referenced by insert_class().
name
std::string ug::bridge::ClassHierarchy::name
Referenced by ug::bridge::GetClassHierarchy(), insert_class(), operator<(), and ug::bridge::PrintClassSubHierarchy().
subclasses
std::vector<ClassHierarchy> ug::bridge::ClassHierarchy::subclasses
Referenced by ug::bridge::GetClassHierarchy(), insert_class(), and ug::bridge::PrintClassSubHierarchy().
The documentation for this class was generated from the following files:
ugbase/registry/class_helper.h
ugbase/registry/class_helper.cpp