ug4: ug::GridFunctionDebugWriter< TDomain, TAlgebra > Class Template Reference
ug::GridFunctionDebugWriter< TDomain, TAlgebra > Class Template Reference
#include <grid_function_util.h>
Public Types
typedef TAlgebra algebra_type
type of matrix
typedef ApproximationSpace< TDomain > approximation_space_type
type of approximation space
typedef algebra_type::matrix_type matrix_type
type of matrix
typedef IDebugWriter< TAlgebra > super
typedef algebra_type::vector_type vector_type
type of vector
Public Types inherited from ug::IDebugWriter< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::IVectorDebugWriter< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
GridLevel grid_level () const
returns current grid level
GridFunctionDebugWriter (SmartPtr< ApproximationSpace< TDomain > > spApproxSpace)
Constructor.
void reset ()
sets to toplevel on surface
void set_conn_viewer_indices (bool b)
sets if .indices file is written or conn viewer
void set_conn_viewer_output (bool b)
sets if writing to conn viewer
void set_grid_level (const GridLevel &gridLevel)
sets the grid level
void set_grid_levels (const GridLevel &glFrom, const GridLevel &glTo)
sets the grid level
void set_print_consistent (bool b)
sets if data shall be made consistent before printing
void set_vtk_output (bool b)
sets if writing to vtk
virtual void update_positions ()
virtual void write_matrix (const matrix_type &mat, const char *filename)
write matrix
virtual void write_vector (const vector_type &vec, const char *filename)
write vector
virtual ~GridFunctionDebugWriter ()
Public Member Functions inherited from ug::IVectorDebugWriter< TAlgebra::vector_type >
int current_dimension () const
returns the current dimension
void enter_section (const char *secDir)
enter a new debugging section
std::string get_base_dir ()
SmartPtr< DebugWriterContext > get_context ()
get the debugging writer context
ConstSmartPtr< DebugWriterContext > get_context () const
get the debugging writer context
int get_dim () const
get the dimensionality
const std::vector< MathVector< dim > > & get_positions () const
returns the positions (only available for current dimension)
IVectorDebugWriter ()
Constructor.
void leave_section ()
leave the current debugging section
virtual void print_message (const char *msg)
prints a message
void set_base_dir (const char *const baseDir)
set the base directory for output files (.vec and .mat)
void set_context (SmartPtr< DebugWriterContext > context)
set the debugging writer context
void set_positions (const std::vector< MathVector< dim > > &vPos)
sets the current positions
void set_positions (IPositionProvider< dim > &provider)
employs a position provider to set the current positions
virtual ~IVectorDebugWriter ()
virtual destructor
Protected Member Functions
void extract_positions (const GridLevel &gridLevel)
reads the positions
void write_algebra_indices_CV (std::string name)
virtual void write_vector_to_conn_viewer (const vector_type &vec, const char *filename)
write vector
void write_vector_to_vtk (const vector_type &vec, const char *filename)
Protected Member Functions inherited from ug::IVectorDebugWriter< TAlgebra::vector_type >
void compose_file_path (std::string &path)
composes the path for the files and creates the intermediate directories (up to the base one):
std::vector< MathVector< 1 > > & get_pos (Int2Type< 1 >)
help function to get local ips
const std::vector< MathVector< 1 > > & get_pos (Int2Type< 1 >) const
std::vector< MathVector< 2 > > & get_pos (Int2Type< 2 >)
const std::vector< MathVector< 2 > > & get_pos (Int2Type< 2 >) const
std::vector< MathVector< 3 > > & get_pos (Int2Type< 3 >)
const std::vector< MathVector< 3 > > & get_pos (Int2Type< 3 >) const
std::vector< MathVector< dim > > & positions ()
returns the positions and sets the current dim
Protected Attributes
bool bConnViewerIndices
bool bConnViewerOut
bool bVTKOut
GridLevel m_glFrom
GridLevel m_glTo
bool m_printConsistent
SmartPtr< approximation_space_type > m_spApproxSpace
Protected Attributes inherited from ug::IVectorDebugWriter< TAlgebra::vector_type >
int m_currentDim
current dimension
SmartPtr< DebugWriterContext > m_spContext
debugging writer context
std::vector< MathVector< 1 > > m_vPos1d
vectors of positions
std::vector< MathVector< 2 > > m_vPos2d
std::vector< MathVector< 3 > > m_vPos3d
Static Private Attributes
static const int dim = TDomain::dim
dimension
Member Typedef Documentation
algebra_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra ug::GridFunctionDebugWriter< TDomain, TAlgebra >::algebra_type
type of matrix
approximation_space_type
template<typename TDomain , typename TAlgebra > typedef ApproximationSpace<TDomain> ug::GridFunctionDebugWriter< TDomain, TAlgebra >::approximation_space_type
type of approximation space
matrix_type
template<typename TDomain , typename TAlgebra > typedef algebra_type::matrix_type ug::GridFunctionDebugWriter< TDomain, TAlgebra >::matrix_type
type of matrix
super
template<typename TDomain , typename TAlgebra > typedef IDebugWriter<TAlgebra> ug::GridFunctionDebugWriter< TDomain, TAlgebra >::super
vector_type
template<typename TDomain , typename TAlgebra > typedef algebra_type::vector_type ug::GridFunctionDebugWriter< TDomain, TAlgebra >::vector_type
type of vector
Constructor & Destructor Documentation
GridFunctionDebugWriter()
template<typename TDomain , typename TAlgebra > ug::GridFunctionDebugWriter< TDomain, TAlgebra >::GridFunctionDebugWriter (SmartPtr< ApproximationSpace< TDomain > > spApproxSpace) inline
Constructor.
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::dim, and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::reset().
~GridFunctionDebugWriter()
template<typename TDomain , typename TAlgebra > virtual ug::GridFunctionDebugWriter< TDomain, TAlgebra >::~GridFunctionDebugWriter () inline virtual
Member Function Documentation
extract_positions()
template<typename TDomain , typename TAlgebra > void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::extract_positions (const GridLevel & gridLevel) inline protected
reads the positions
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_spApproxSpace.
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::update_positions().
grid_level()
template<typename TDomain , typename TAlgebra > GridLevel ug::GridFunctionDebugWriter< TDomain, TAlgebra >::grid_level () const inline
returns current grid level
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glFrom.
reset()
template<typename TDomain , typename TAlgebra > void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::reset () inline
sets to toplevel on surface
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_grid_level(), ug::GridLevel::SURFACE, and ug::GridLevel::TOP.
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::GridFunctionDebugWriter().
set_conn_viewer_indices()
template<typename TDomain , typename TAlgebra > void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_conn_viewer_indices (bool b) inline
sets if .indices file is written or conn viewer
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::bConnViewerIndices.
set_conn_viewer_output()
template<typename TDomain , typename TAlgebra > void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_conn_viewer_output (bool b) inline
sets if writing to conn viewer
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::bConnViewerOut.
set_grid_level()
template<typename TDomain , typename TAlgebra > void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_grid_level (const GridLevel & gridLevel) inline
sets the grid level
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glFrom, and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glTo.
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::reset().
set_grid_levels()
template<typename TDomain , typename TAlgebra > void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_grid_levels (const GridLevel & glFrom, const GridLevel & glTo) inline
sets the grid level
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glFrom, and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glTo.
set_print_consistent()
template<typename TDomain , typename TAlgebra > void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_print_consistent (bool b) inline
sets if data shall be made consistent before printing
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_printConsistent.
set_vtk_output()
template<typename TDomain , typename TAlgebra > void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_vtk_output (bool b) inline
sets if writing to vtk
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::bVTKOut.
update_positions()
template<typename TDomain , typename TAlgebra > virtual void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::update_positions () inline virtual
gives subclasses the oportunity to calculate the positions this is used e.g. in GridFunctionDebugWriter after this has been called, get_positions gives valid positions those positions are used e.g. in AMG or Schur methods.
Reimplemented from ug::IVectorDebugWriter< TAlgebra::vector_type >.
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::extract_positions(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glFrom.
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_matrix(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector_to_conn_viewer().
write_algebra_indices_CV()
template<typename TDomain , typename TAlgebra > void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_algebra_indices_CV (std::string name) inline protected
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::bConnViewerIndices, ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glFrom, ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_spApproxSpace, and name.
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_matrix(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector_to_conn_viewer().
write_matrix()
template<typename TDomain , typename TAlgebra > virtual void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_matrix (const matrix_type & mat, const char * filename) inline virtual
write matrix
Implements ug::IDebugWriter< TAlgebra >.
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::bConnViewerOut, ug::IVectorDebugWriter< TAlgebra::vector_type >::compose_file_path(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::dim, ug::FileTypeIs(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glFrom, ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glTo, ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_spApproxSpace, name, PROFILE_FUNC_GROUP, UG_THROW, ug::GridFunctionDebugWriter< TDomain, TAlgebra >::update_positions(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_algebra_indices_CV(), and ug::ConnectionViewer::WriteMatrixPar().
write_vector()
template<typename TDomain , typename TAlgebra > virtual void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector (const vector_type & vec, const char * filename) inline virtual
write vector
Implements ug::IDebugWriter< TAlgebra >.
References ug::GridFunctionDebugWriter< TDomain, TAlgebra >::bConnViewerOut, ug::GridFunctionDebugWriter< TDomain, TAlgebra >::bVTKOut, ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector_to_conn_viewer(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector_to_vtk().
write_vector_to_conn_viewer()
template<typename TDomain , typename TAlgebra > virtual void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector_to_conn_viewer (const vector_type & vec, const char * filename) inline protected virtual
write vector
References ug::IVectorDebugWriter< TAlgebra::vector_type >::compose_file_path(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::dim, ug::FileTypeIs(), name, PROFILE_FUNC_GROUP, UG_THROW, ug::GridFunctionDebugWriter< TDomain, TAlgebra >::update_positions(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_algebra_indices_CV(), and ug::ConnectionViewer::WriteVectorPar().
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector().
write_vector_to_vtk()
template<typename TDomain , typename TAlgebra > void ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector_to_vtk (const vector_type & vec, const char * filename) inline protected
References ug::IVectorDebugWriter< TAlgebra::vector_type >::compose_file_path(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glFrom, ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_printConsistent, ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_spApproxSpace, name, ug::VTKOutput< TDim >::print(), and PROFILE_FUNC_GROUP.
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector().
Member Data Documentation
bConnViewerIndices
template<typename TDomain , typename TAlgebra > bool ug::GridFunctionDebugWriter< TDomain, TAlgebra >::bConnViewerIndices protected
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_conn_viewer_indices(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_algebra_indices_CV().
bConnViewerOut
template<typename TDomain , typename TAlgebra > bool ug::GridFunctionDebugWriter< TDomain, TAlgebra >::bConnViewerOut protected
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_conn_viewer_output(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_matrix(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector().
bVTKOut
template<typename TDomain , typename TAlgebra > bool ug::GridFunctionDebugWriter< TDomain, TAlgebra >::bVTKOut protected
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_vtk_output(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector().
dim
template<typename TDomain , typename TAlgebra > const int ug::GridFunctionDebugWriter< TDomain, TAlgebra >::dim = TDomain::dim static private
dimension
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::GridFunctionDebugWriter(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_matrix(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector_to_conn_viewer().
m_glFrom
template<typename TDomain , typename TAlgebra > GridLevel ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glFrom protected
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::grid_level(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_grid_level(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_grid_levels(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::update_positions(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_algebra_indices_CV(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_matrix(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector_to_vtk().
m_glTo
template<typename TDomain , typename TAlgebra > GridLevel ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_glTo protected
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_grid_level(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_grid_levels(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_matrix().
m_printConsistent
template<typename TDomain , typename TAlgebra > bool ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_printConsistent protected
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::set_print_consistent(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector_to_vtk().
m_spApproxSpace
template<typename TDomain , typename TAlgebra > SmartPtr<approximation_space_type> ug::GridFunctionDebugWriter< TDomain, TAlgebra >::m_spApproxSpace protected
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::extract_positions(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_algebra_indices_CV(), ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_matrix(), and ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector_to_vtk().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/grid_function_util.h