ug4: ug::TParallelGlobalRefiner< TRefiner > Class Template Reference
ug::TParallelGlobalRefiner< TRefiner > Class Template Reference
lib_grid » parallelization » parallel refinement
Adds parallel support to a global refiner.
#include <parallel_global_refiner_t.h>
Public Member Functions
TParallelGlobalRefiner (DistributedGridManager &distGridMgr)
virtual ~TParallelGlobalRefiner ()
Protected Member Functions
virtual bool refinement_is_allowed (Vertex *elem)
virtual bool refinement_is_allowed (Edge *elem)
virtual bool refinement_is_allowed (Face *elem)
virtual bool refinement_is_allowed (Volume *elem)
virtual void refinement_step_begins ()
virtual void refinement_step_ends ()
Protected Attributes
DistributedGridManager & m_distGridMgr
Detailed Description
template<class TRefiner>
class ug::TParallelGlobalRefiner< TRefiner >
Adds parallel support to a global refiner.
Todo:
This class would benefit from some comfort methods and a better documentation.
Constructor & Destructor Documentation
template<class TRefiner > ug::TParallelGlobalRefiner< TRefiner >::TParallelGlobalRefiner (DistributedGridManager & distGridMgr)
References ug::TParallelGlobalRefiner< TRefiner >::~TParallelGlobalRefiner().
template<class TRefiner > ug::TParallelGlobalRefiner< TRefiner >::~TParallelGlobalRefiner () virtual
References ug::TParallelGlobalRefiner< TRefiner >::refinement_is_allowed().
Referenced by ug::TParallelGlobalRefiner< TRefiner >::TParallelGlobalRefiner().
Member Function Documentation
template<class TRefiner > bool ug::TParallelGlobalRefiner< TRefiner >::refinement_is_allowed (Vertex * elem) protected virtual
References ug::DistributedGridManager::is_ghost(), and ug::TParallelGlobalRefiner< TRefiner >::m_distGridMgr.
Referenced by ug::TParallelGlobalRefiner< TRefiner >::refinement_is_allowed(), and ug::TParallelGlobalRefiner< TRefiner >::~TParallelGlobalRefiner().
template<class TRefiner > bool ug::TParallelGlobalRefiner< TRefiner >::refinement_is_allowed (Edge * elem) protected virtual
References ug::DistributedGridManager::is_ghost(), ug::TParallelGlobalRefiner< TRefiner >::m_distGridMgr, and ug::TParallelGlobalRefiner< TRefiner >::refinement_is_allowed().
template<class TRefiner > bool ug::TParallelGlobalRefiner< TRefiner >::refinement_is_allowed (Face * elem) protected virtual
References ug::DistributedGridManager::is_ghost(), ug::TParallelGlobalRefiner< TRefiner >::m_distGridMgr, and ug::TParallelGlobalRefiner< TRefiner >::refinement_is_allowed().
template<class TRefiner > bool ug::TParallelGlobalRefiner< TRefiner >::refinement_is_allowed (Volume * elem) protected virtual
References ug::DistributedGridManager::is_ghost(), ug::TParallelGlobalRefiner< TRefiner >::m_distGridMgr, and ug::TParallelGlobalRefiner< TRefiner >::refinement_step_begins().
template<class TRefiner > void ug::TParallelGlobalRefiner< TRefiner >::refinement_step_begins () protected virtual
References ug::DistributedGridManager::begin_ordered_element_insertion(), ug::TParallelGlobalRefiner< TRefiner >::m_distGridMgr, and ug::TParallelGlobalRefiner< TRefiner >::refinement_step_ends().
Referenced by ug::TParallelGlobalRefiner< TRefiner >::refinement_is_allowed().
template<class TRefiner > void ug::TParallelGlobalRefiner< TRefiner >::refinement_step_ends () protected virtual
References ug::DistributedGridManager::end_ordered_element_insertion(), and ug::TParallelGlobalRefiner< TRefiner >::m_distGridMgr.
Referenced by ug::TParallelGlobalRefiner< TRefiner >::refinement_step_begins().
Member Data Documentation
template<class TRefiner > DistributedGridManager& ug::TParallelGlobalRefiner< TRefiner >::m_distGridMgr protected
Referenced by ug::TParallelGlobalRefiner< TRefiner >::refinement_is_allowed(), ug::TParallelGlobalRefiner< TRefiner >::refinement_step_begins(), and ug::TParallelGlobalRefiner< TRefiner >::refinement_step_ends().
The documentation for this class was generated from the following files:
ugbase/lib_grid/parallelization/parallel_refinement/parallel_global_refiner_t.h
ugbase/lib_grid/parallelization/parallel_refinement/parallel_global_refiner_t_impl.hpp