ug4: ug::PartitionWeighting Class Reference
ug::PartitionWeighting Class Reference
#include <partition_weighting_callbacks.h>
Public Member Functions
virtual int operator() (Edge *e1, Edge *e2)
virtual int operator() (Face *f1, Face *f2)
virtual int operator() (Volume *v1, Volume *v2)
PartitionWeighting ()
void set_default_weights (int hWeight, int vWeight)
void set_subset_handler (MGSubsetHandler *sh)
virtual ~PartitionWeighting ()
Protected Attributes
int m_hWeight
MGSubsetHandler * m_sh
int m_vWeight
Private Member Functions
template<class TElem >
int weigh (TElem *e1, TElem *e2)
Detailed Description
Base class for partition weighting callbacks.
Constructor & Destructor Documentation
PartitionWeighting()
ug::PartitionWeighting::PartitionWeighting () inline
~PartitionWeighting()
virtual ug::PartitionWeighting::~PartitionWeighting () inline virtual
Member Function Documentation
operator()() [1/3]
virtual int ug::PartitionWeighting::operator() (Edge * e1, Edge * e2) inline virtual
Reimplemented in ug::ProtectSubsetPartitionWeighting, and ug::InterSubsetPartitionWeighting.
References weigh().
operator()() [2/3]
virtual int ug::PartitionWeighting::operator() (Face * f1, Face * f2) inline virtual
Reimplemented in ug::ProtectSubsetPartitionWeighting, and ug::InterSubsetPartitionWeighting.
References weigh().
operator()() [3/3]
virtual int ug::PartitionWeighting::operator() (Volume * v1, Volume * v2) inline virtual
Reimplemented in ug::ProtectSubsetPartitionWeighting, and ug::InterSubsetPartitionWeighting.
References weigh().
set_default_weights()
void ug::PartitionWeighting::set_default_weights (int hWeight, int vWeight) inline
References m_hWeight, and m_vWeight.
set_subset_handler()
void ug::PartitionWeighting::set_subset_handler (MGSubsetHandler * sh) inline
References m_sh.
Referenced by ug::PartitionDomain_MetisKWay().
weigh()
template<class TElem > int ug::PartitionWeighting::weigh (TElem * e1, TElem * e2) inline private
References ug::MultiGridSubsetHandler::get_level(), m_hWeight, m_sh, m_vWeight, and UG_THROW.
Referenced by operator()().
Member Data Documentation
m_hWeight
int ug::PartitionWeighting::m_hWeight protected
Referenced by set_default_weights(), weigh(), ug::InterSubsetPartitionWeighting::weigh(), and ug::ProtectSubsetPartitionWeighting::weigh().
m_sh
MGSubsetHandler* ug::PartitionWeighting::m_sh protected
Referenced by set_subset_handler(), weigh(), ug::InterSubsetPartitionWeighting::weigh(), and ug::ProtectSubsetPartitionWeighting::weigh().
m_vWeight
int ug::PartitionWeighting::m_vWeight protected
Referenced by set_default_weights(), weigh(), ug::InterSubsetPartitionWeighting::weigh(), and ug::ProtectSubsetPartitionWeighting::weigh().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/util/partition_weighting_callbacks.h