ug4: ug::bridge::ExportedFunctionBase Class Reference
ug::bridge::ExportedFunctionBase Class Reference
ugbase » Bridge » Registry
Base class for function/method export.
#include <global_function.h>
Public Member Functions
bool check_consistency (std::string classname="") const
returns true if all parameters of the function are correctly declared
ExportedFunctionBase (const std::string &funcName, const std::string &funcOptions, const std::string &retValInfos, const std::string &paramInfos, const std::string &tooltip, const std::string &help)
const std::string & help () const
help informations
const std::string & name () const
name of function
size_t num_infos (size_t i) const
number of info strings for one parameter
size_t num_parameter () const
number of parameters.
const std::string & options () const
name of function
const char * parameter_class_name (size_t i) const
class name of parameter i
const std::string & parameter_info (size_t i, size_t j) const
type info of all parameters
const std::string & parameter_info_string () const
whole string of all type infos for of all parameters
const std::vector< std::string > & parameter_info_vec (size_t i) const
type info of i th parameters
const std::string & parameter_name (size_t i) const
name of parameter i
const ParameterInfo & params_in () const
parameter list for input values
ParameterInfo & params_in ()
non-const export of param list
const ParameterInfo & params_out () const
parameter list for input values
const std::string & return_info (size_t i) const
type info of return type
const std::vector< std::string > & return_info_vec () const
type info of return value
const std::string & return_name () const
name of return value
const std::string & tooltip () const
gives some information to the exported functions
Protected Member Functions
template<typename TFunc >
void create_parameter_stack ()
void tokenize (const std::string &str, std::vector< std::string > &tokens, const char delimiter)
Protected Attributes
std::string m_help
std::string m_methodOptions
std::string m_name
std::string m_paramInfos
ParameterInfo m_paramsIn
ParameterInfo m_paramsOut
std::string m_retValInfos
std::string m_tooltip
std::vector< std::string > m_vRetValInfo
std::vector< std::vector< std::string > > m_vvParamInfo
Detailed Description
Base class for function/method export.
Constructor & Destructor Documentation
ug::bridge::ExportedFunctionBase::ExportedFunctionBase (const std::string & funcName, const std::string & funcOptions, const std::string & retValInfos, const std::string & paramInfos, const std::string & tooltip, const std::string & help)
References m_name, m_paramInfos, m_retValInfos, m_vRetValInfo, m_vvParamInfo, tokenize(), UG_ERR_LOG, and UG_THROW_REGISTRY_ERROR.
Member Function Documentation
bool ug::bridge::ExportedFunctionBase::check_consistency (std::string classname = "") const
returns true if all parameters of the function are correctly declared
References name(), num_parameter(), parameter_name(), ug::bridge::ParameterInfo::parameter_named(), ug::bridge::ParameterToString(), params_in(), params_out(), ug::bridge::ParameterInfo::size(), and UG_ERR_LOG.
Referenced by ug::bridge::Registry::check_consistency().
template<typename TFunc > void ug::bridge::ExportedFunctionBase::create_parameter_stack () inline protected
References ug::bridge::CreateParameterInfo< TTypeList >::create(), and ug::bridge::CreateParameterInfoOut< TRet >::create().
const std::string& ug::bridge::ExportedFunctionBase::help () const inline
help informations
Referenced by ug::vrl::function2NativeFunction(), and ug::vrl::method2NativeMethod().
const std::string& ug::bridge::ExportedFunctionBase::name () const inline
name of function
Referenced by check_consistency(), ug::bridge::FindFunction(), ug::vrl::function2NativeFunction(), ug::bridge::FunctionInfo(), ug::bridge::lua::GetBestMatchingMember(), ug::bridge::GetMemberFunctionCompletitions(), ug::bridge::GetMemberFunctionInfo(), Java_edu_gcsc_vrl_ug_UG__1invokeFunction(), ug::vrl::method2NativeMethod(), and ug::vrl::params2NativeParams().
size_t ug::bridge::ExportedFunctionBase::num_infos (size_t i) const inline
number of info strings for one parameter
size_t ug::bridge::ExportedFunctionBase::num_parameter () const inline
number of parameters.
Referenced by check_consistency(), and ug::vrl::params2NativeParams().
const std::string& ug::bridge::ExportedFunctionBase::options () const inline
name of function
Referenced by ug::vrl::function2NativeFunction(), and ug::vrl::method2NativeMethod().
const char* ug::bridge::ExportedFunctionBase::parameter_class_name (size_t i) const inline
class name of parameter i
const std::string& ug::bridge::ExportedFunctionBase::parameter_info (size_t i, size_t j) const inline
type info of all parameters
const std::string& ug::bridge::ExportedFunctionBase::parameter_info_string () const inline
whole string of all type infos for of all parameters
const std::vector<std::string>& ug::bridge::ExportedFunctionBase::parameter_info_vec (size_t i) const inline
type info of i th parameters
Referenced by ug::vrl::params2NativeParams().
const std::string& ug::bridge::ExportedFunctionBase::parameter_name (size_t i) const inline
name of parameter i
Referenced by check_consistency().
const ParameterInfo& ug::bridge::ExportedFunctionBase::params_in () const inline
parameter list for input values
Referenced by check_consistency(), ug::bridge::ClassUsageExact(), ug::bridge::lua::ExecuteMethod(), ug::vrl::invocation::getFunctionBySignature(), ug::vrl::invocation::getMethodBySignature(), Java_edu_gcsc_vrl_ug_UG__1invokeFunction(), Java_edu_gcsc_vrl_ug_UG__1invokeMethod(), ug::bridge::lua::LuaProxyFunction(), ug::vrl::params2NativeParams(), and ug::bridge::WriteLUAObject2().
ParameterInfo& ug::bridge::ExportedFunctionBase::params_in () inline
non-const export of param list
const ParameterInfo& ug::bridge::ExportedFunctionBase::params_out () const inline
parameter list for input values
Referenced by check_consistency(), ug::bridge::ClassUsageExact(), ug::bridge::PrintParametersOut(), and ug::vrl::retVal2NativeParam().
const std::string& ug::bridge::ExportedFunctionBase::return_info (size_t i) const inline
type info of return type
const std::vector<std::string>& ug::bridge::ExportedFunctionBase::return_info_vec () const inline
type info of return value
Referenced by ug::vrl::retVal2NativeParam().
const std::string& ug::bridge::ExportedFunctionBase::return_name () const inline
name of return value
void ug::bridge::ExportedFunctionBase::tokenize (const std::string & str, std::vector< std::string > & tokens, const char delimiter) protected
References ug::TrimString().
Referenced by ExportedFunctionBase().
const std::string& ug::bridge::ExportedFunctionBase::tooltip () const inline
gives some information to the exported functions
Member Data Documentation
std::string ug::bridge::ExportedFunctionBase::m_help protected
std::string ug::bridge::ExportedFunctionBase::m_methodOptions protected
std::string ug::bridge::ExportedFunctionBase::m_name protected
Referenced by ExportedFunctionBase().
std::string ug::bridge::ExportedFunctionBase::m_paramInfos protected
Referenced by ExportedFunctionBase().
ParameterInfo ug::bridge::ExportedFunctionBase::m_paramsIn protected
ParameterInfo ug::bridge::ExportedFunctionBase::m_paramsOut protected
std::string ug::bridge::ExportedFunctionBase::m_retValInfos protected
Referenced by ExportedFunctionBase().
std::string ug::bridge::ExportedFunctionBase::m_tooltip protected
std::vector<std::string> ug::bridge::ExportedFunctionBase::m_vRetValInfo protected
Referenced by ExportedFunctionBase().
std::vector<std::vector<std::string> > ug::bridge::ExportedFunctionBase::m_vvParamInfo protected
Referenced by ExportedFunctionBase().
The documentation for this class was generated from the following files:
ugbase/registry/global_function.h
ugbase/registry/global_function.cpp