ug4: ug::ParallelShiftIdentifier< TPosAA > Class Template Reference
ug::ParallelShiftIdentifier< TPosAA > Class Template Reference
This class matches geometric elements which are parallel translated.
#include <periodic_boundary_manager.h>
Public Types
typedef TPosAA::ValueType AttachmentType
Public Member Functions
virtual bool match (Edge *e1, Edge *e2)
virtual bool match (Face *f1, Face *f2)
virtual bool match (Vertex *v1, Vertex *v2)
ParallelShiftIdentifier (TPosAA &aa)
void set_shift (AttachmentType &shift)
virtual ~ParallelShiftIdentifier ()
Public Member Functions inherited from ug::IIdentifier
virtual bool match (Volume *, Volume *)
virtual ~IIdentifier ()
Protected Member Functions
template<class TElem >
bool match_impl (TElem *, TElem *) const
Protected Attributes
TPosAA & m_aaPos
AttachmentType m_shift
AttachmentType m_shift_opposite
Detailed Description
template<class TPosAA>
class ug::ParallelShiftIdentifier< TPosAA >
This class matches geometric elements which are parallel translated.
Usage: class needs to be instantiated with the position attachment used on the Domain. Before using any match methods, the translation vector needs to be set with set_shift()
Template Parameters
<TPosAA>{class needs to be instantiated with the position attachment used on the Domain.}
Member Typedef Documentation
AttachmentType
template<class TPosAA> typedef TPosAA::ValueType ug::ParallelShiftIdentifier< TPosAA >::AttachmentType
Constructor & Destructor Documentation
~ParallelShiftIdentifier()
template<class TPosAA> virtual ug::ParallelShiftIdentifier< TPosAA >::~ParallelShiftIdentifier () inline virtual
ParallelShiftIdentifier()
template<class TPosAA> ug::ParallelShiftIdentifier< TPosAA >::ParallelShiftIdentifier (TPosAA & aa) inline
Member Function Documentation
match() [1/3]
template<class TPosAA> virtual bool ug::ParallelShiftIdentifier< TPosAA >::match (Edge * e1, Edge * e2) inline virtual
Implements ug::IIdentifier.
References ug::ParallelShiftIdentifier< TPosAA >::match_impl().
match() [2/3]
template<class TPosAA> virtual bool ug::ParallelShiftIdentifier< TPosAA >::match (Face * f1, Face * f2) inline virtual
Implements ug::IIdentifier.
References ug::ParallelShiftIdentifier< TPosAA >::match_impl().
match() [3/3]
template<class TPosAA> virtual bool ug::ParallelShiftIdentifier< TPosAA >::match (Vertex * v1, Vertex * v2) inline virtual
Implements ug::IIdentifier.
References ug::ParallelShiftIdentifier< TPosAA >::match_impl().
Referenced by ug::IdentifySubsets().
match_impl()
template<class TAAPos > template<class TElem > bool ug::ParallelShiftIdentifier< TAAPos >::match_impl (TElem * e1, TElem * e2) const protected
References ug::CalculateCenter(), ug::VecLengthSq(), and ug::VecSubtract().
Referenced by ug::ParallelShiftIdentifier< TPosAA >::match().
set_shift()
template<class TPosAA> void ug::ParallelShiftIdentifier< TPosAA >::set_shift (AttachmentType & shift) inline
References ug::ParallelShiftIdentifier< TPosAA >::m_shift, ug::ParallelShiftIdentifier< TPosAA >::m_shift_opposite, and ug::VecScale().
Referenced by ug::IdentifySubsets().
Member Data Documentation
m_aaPos
template<class TPosAA> TPosAA& ug::ParallelShiftIdentifier< TPosAA >::m_aaPos protected
m_shift
template<class TPosAA> AttachmentType ug::ParallelShiftIdentifier< TPosAA >::m_shift protected
Referenced by ug::ParallelShiftIdentifier< TPosAA >::set_shift().
m_shift_opposite
template<class TPosAA> AttachmentType ug::ParallelShiftIdentifier< TPosAA >::m_shift_opposite protected
Referenced by ug::ParallelShiftIdentifier< TPosAA >::set_shift().
The documentation for this class was generated from the following files:
ugbase/lib_grid/tools/periodic_boundary_manager.h
ugbase/lib_grid/tools/periodic_boundary_manager_impl.hpp