ug4: ug::LocalDoFSet Class Reference
ug::LocalDoFSet Class Reference abstract
#include <local_dof_set.h>
Public Member Functions
int dim () const
returns the reference dimension
virtual const LocalDoF & local_dof (size_t dof) const =0
returns the DoFs storage
virtual size_t num_dof (ReferenceObjectID roid) const =0
returns the number of DoFs on a sub-geometric object type
size_t num_dof (int d, size_t id) const
returns the number of DoFs on a sub-geometric object of dim and id
bool operator!= (const LocalDoFSet &v) const
inequality check
bool operator== (const LocalDoFSet &v) const
equality check
virtual ReferenceObjectID roid () const =0
returns the Reference object id of the corresponding grid object
virtual ~LocalDoFSet ()
virtual destructor
size_t num_dof () const
virtual size_t num_sh () const
Detailed Description
This class provides the interface for the storage of degrees of freedom on a finite element.
Constructor & Destructor Documentation
virtual ug::LocalDoFSet::~LocalDoFSet () inline virtual
virtual destructor
Member Function Documentation
int ug::LocalDoFSet::dim () const
returns the reference dimension
References ug::ReferenceElementDimension(), and roid().
Referenced by ug::LocalFiniteElementProvider::create_crouxeiz_raviart_set(), ug::LocalFiniteElementProvider::create_dof_set(), ug::LocalFiniteElementProvider::create_lagrange_set(), ug::LocalFiniteElementProvider::create_mini_bubble_set(), ug::LocalFiniteElementProvider::create_nedelec_set(), ug::LocalFiniteElementProvider::create_piecewise_constant_set(), ug::LocalFiniteElementProvider::create_set(), ug::LocalFiniteElementProvider::create_sub_dof_set(), operator==(), and ug::SubLocalDoFSet< TDim >::SubLocalDoFSet().
virtual const LocalDoF& ug::LocalDoFSet::local_dof (size_t dof) const pure virtual
returns the DoFs storage
Implemented in ug::SubLocalDoFSet< TDim >, ug::MiniBubbleLDS< TRefElem >, ug::MiniBubbleLDS< ReferenceEdge >, ug::MiniBubbleLDS< ReferenceHexahedron >, ug::MiniBubbleLDS< ReferenceTetrahedron >, ug::MiniBubbleLDS< ReferenceTriangle >, ug::MiniBubbleLDS< ReferenceQuadrilateral >, ug::LocalShapeFunctionSetWrapper< TImpl >, ug::LagrangeLDS< TRefElem >, ug::LagrangeLDS< ReferenceEdge >, ug::LagrangeLDS< ReferenceVertex >, ug::LagrangeLDS< ReferencePrism >, ug::LagrangeLDS< ReferenceOctahedron >, ug::LagrangeLDS< ReferencePyramid >, ug::LagrangeLDS< ReferenceHexahedron >, ug::LagrangeLDS< ReferenceTriangle >, ug::LagrangeLDS< ReferenceTetrahedron >, and ug::LagrangeLDS< ReferenceQuadrilateral >.
Referenced by ug::InnerDoFPositionElem(), and operator==().
size_t ug::LocalDoFSet::num_dof () const inline
returns the total number of dofs on the finite element
References ug::LocalDoF::operator==().
Referenced by num_dof(), num_sh(), ug::operator<<(), operator==(), and ug::DimLocalDoFSet< TDim >::operator==().
virtual size_t ug::LocalDoFSet::num_dof (ReferenceObjectID roid) const pure virtual
returns the number of DoFs on a sub-geometric object type
Implemented in ug::SubLocalDoFSet< TDim >, ug::MiniBubbleLDS< TRefElem >, ug::MiniBubbleLDS< ReferenceEdge >, ug::MiniBubbleLDS< ReferenceHexahedron >, ug::MiniBubbleLDS< ReferenceTetrahedron >, ug::MiniBubbleLDS< ReferenceTriangle >, ug::MiniBubbleLDS< ReferenceQuadrilateral >, ug::LocalShapeFunctionSetWrapper< TImpl >, ug::LagrangeLDS< TRefElem >, ug::LagrangeLDS< ReferenceEdge >, ug::LagrangeLDS< ReferenceVertex >, ug::LagrangeLDS< ReferencePrism >, ug::LagrangeLDS< ReferenceOctahedron >, ug::LagrangeLDS< ReferencePyramid >, ug::LagrangeLDS< ReferenceHexahedron >, ug::LagrangeLDS< ReferenceTriangle >, ug::LagrangeLDS< ReferenceTetrahedron >, and ug::LagrangeLDS< ReferenceQuadrilateral >.
size_t ug::LocalDoFSet::num_dof (int d, size_t id) const
returns the number of DoFs on a sub-geometric object of dim and id
References ug::ReferenceElementProvider::get(), num_dof(), ug::ReferenceElement::roid(), and roid().
size_t ug::LocalDoFSet::num_sh () const virtual
returns the total number of dofs on the finite element
Reimplemented in ug::LagrangeLSFS< ReferenceOctahedron, TOrder >, ug::FlexLagrangeLSFS< ReferenceHexahedron >, ug::LagrangeLSFS< ReferenceHexahedron, TOrder >, ug::LagrangeLSFS< ReferencePyramid, TOrder >, ug::FlexLagrangeLSFS< ReferencePrism >, ug::LagrangeLSFS< ReferencePrism, TOrder >, ug::FlexLagrangeLSFS< ReferenceTetrahedron >, ug::LagrangeLSFS< ReferenceTetrahedron, TOrder >, ug::FlexLagrangeLSFS< ReferenceQuadrilateral >, ug::LagrangeLSFS< ReferenceQuadrilateral, TOrder >, ug::FlexLagrangeLSFS< ReferenceTriangle >, ug::MiniBubbleLSFS< ReferenceHexahedron >, ug::MiniBubbleLSFS< ReferenceTetrahedron >, ug::LagrangeLSFS< ReferenceTriangle, TOrder >, ug::MiniBubbleLSFS< ReferenceQuadrilateral >, ug::FlexLagrangeLSFS< ReferenceEdge >, ug::MiniBubbleLSFS< ReferenceTriangle >, ug::LagrangeLSFS< ReferenceEdge, TOrder >, ug::MiniBubbleLSFS< ReferenceEdge >, ug::FlexLagrangeLSFS< ReferenceVertex >, ug::LagrangeLSFS< ReferenceVertex, TOrder >, ug::LocalShapeFunctionSetWrapper< TImpl >, and ug::LagrangeP1< TRefElem >.
References num_dof(), and ug::NUM_REFERENCE_OBJECTS.
Referenced by ug::ComputeGradientCrouzeixRaviart(), ug::ComputeGradientLagrange1(), ug::DoFPositionElem(), ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate(), ug::L2ErrorIntegrand< TGridFunction >::evaluate(), ug::H1ErrorIntegrand< TGridFunction >::evaluate(), ug::L2FuncIntegrand< TGridFunction >::evaluate(), ug::StdFuncIntegrand< TGridFunction >::evaluate(), ug::BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >::grads(), ug::InnerDoFPositionElem(), ug::InterpolateOnElements(), ug::MaxErrorOnElements(), ug::BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >::shapes(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), ug::DimCRFVGeometry< TDim, TWorldDim >::update_boundary_faces(), ug::DimFV1Geometry< TDim, TWorldDim >::update_boundary_faces(), ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), ug::DimCRFVGeometry< TDim, TWorldDim >::update_hanging(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_local(), ug::DimFV1Geometry< TDim, TWorldDim >::update_local(), ug::DimFVGeometry< TWorldDim, TDim >::update_local(), ug::DimCRFVGeometry< TDim, TWorldDim >::update_local_data(), and ug::VTKOutput< TDim >::write_cell_values_elementwise().
bool ug::LocalDoFSet::operator!= (const LocalDoFSet & v) const inline
inequality check
bool ug::LocalDoFSet::operator== (const LocalDoFSet & v) const
equality check
References dim(), local_dof(), num_dof(), ug::NUM_REFERENCE_OBJECTS, and roid().
virtual ReferenceObjectID ug::LocalDoFSet::roid () const pure virtual
returns the Reference object id of the corresponding grid object
Implemented in ug::SubLocalDoFSet< TDim >, ug::MiniBubbleLDS< TRefElem >, ug::MiniBubbleLDS< ReferenceEdge >, ug::MiniBubbleLDS< ReferenceHexahedron >, ug::MiniBubbleLDS< ReferenceTetrahedron >, ug::MiniBubbleLDS< ReferenceTriangle >, ug::MiniBubbleLDS< ReferenceQuadrilateral >, ug::LocalShapeFunctionSetWrapper< TImpl >, ug::LagrangeLDS< TRefElem >, ug::LagrangeLDS< ReferenceEdge >, ug::LagrangeLDS< ReferenceVertex >, ug::LagrangeLDS< ReferencePrism >, ug::LagrangeLDS< ReferenceOctahedron >, ug::LagrangeLDS< ReferencePyramid >, ug::LagrangeLDS< ReferenceHexahedron >, ug::LagrangeLDS< ReferenceTriangle >, ug::LagrangeLDS< ReferenceTetrahedron >, and ug::LagrangeLDS< ReferenceQuadrilateral >.
Referenced by ug::CommonLocalDoFSet::add(), dim(), num_dof(), ug::operator<<(), and operator==().
The documentation for this class was generated from the following files:
ugbase/lib_disc/local_finite_element/local_dof_set.h
ugbase/lib_disc/local_finite_element/local_dof_set.cpp