ug4: ug::QuadrilateralDescriptor Class Reference
ug::QuadrilateralDescriptor Class Reference
only used to initialize a quadrilateral. for all other tasks you should use FaceDescriptor.
#include <grid_objects_2d.h>
Public Member Functions
uint num_vertices () const
QuadrilateralDescriptor ()
QuadrilateralDescriptor (const QuadrilateralDescriptor &qd)
QuadrilateralDescriptor (Vertex *v1, Vertex *v2, Vertex *v3, Vertex *v4)
void set_vertex (uint index, Vertex *v)
Vertex * vertex (size_t index) const
Protected Attributes
Vertex * m_vertex [4]
Detailed Description
only used to initialize a quadrilateral. for all other tasks you should use FaceDescriptor.
Constructor & Destructor Documentation
QuadrilateralDescriptor() [1/3]
ug::QuadrilateralDescriptor::QuadrilateralDescriptor () inline
QuadrilateralDescriptor() [2/3]
ug::QuadrilateralDescriptor::QuadrilateralDescriptor (const QuadrilateralDescriptor & qd)
References vertex().
QuadrilateralDescriptor() [3/3]
ug::QuadrilateralDescriptor::QuadrilateralDescriptor (Vertex * v1, Vertex * v2, Vertex * v3, Vertex * v4)
Member Function Documentation
num_vertices()
uint ug::QuadrilateralDescriptor::num_vertices () const inline
set_vertex()
void ug::QuadrilateralDescriptor::set_vertex (uint index, Vertex * v) inline
vertex()
Vertex* ug::QuadrilateralDescriptor::vertex (size_t index) const inline
Referenced by ug::CustomQuadrilateral< ConcreteQuadrilateralType, BaseClass, RefTriType, RefQuadType >::CustomQuadrilateral(), and QuadrilateralDescriptor().
Member Data Documentation
m_vertex
Vertex* ug::QuadrilateralDescriptor::m_vertex[4] protected
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid_objects/grid_objects_2d.h
ugbase/lib_grid/grid_objects/grid_objects_2d.cpp