ug4: ug::UGError Class Reference
ug::UGError Class Reference
ugbase » Common
Instances of this class or of derived classes are thrown if errors arise.
#include <error.h>
Public Member Functions
const std::string & get_file (size_t i) const
returns the file where a message occured
unsigned long get_line (size_t i) const
returns the line where a message occured
const std::string & get_msg () const
returns the initial message
const std::string & get_msg (size_t i) const
returns a message in the message-stack (innermost is first)
std::string get_stacktrace () const
size_t num_msg () const
number of messages in message-stack
void push_msg (const char *msg, const char *file=" -- no file -- ", const unsigned long line=0)
adds a message to the message stack
void push_msg (const std::string &msg, const char *file=" -- no file -- ", const unsigned long line=0)
adds a message to the message stack
UGError (const char *msg, const char *file=" -- no file -- ", const unsigned long line=0)
UGError (const std::string &msg, const char *file=" -- no file -- ", const unsigned long line=0)
UGError (const std::string &msg, const std::exception &ex, const char *file, const unsigned long line)
virtual ~UGError ()
virtual destructor
Protected Attributes
std::vector< std::string > m_vFile
std::vector< unsigned long > m_vLine
std::vector< std::string > m_vMsg
Detailed Description
Instances of this class or of derived classes are thrown if errors arise.
By default the error-code is 0 and terminate returns false.
Constructor & Destructor Documentation
UGError() [1/3]
ug::UGError::UGError (const char * msg, const char * file = " -- no file -- ", const unsigned long line = 0) inline
References push_msg().
UGError() [2/3]
ug::UGError::UGError (const std::string & msg, const char * file = " -- no file -- ", const unsigned long line = 0) inline
References push_msg().
UGError() [3/3]
ug::UGError::UGError (const std::string & msg, const std::exception & ex, const char * file, const unsigned long line)
References ug::ErrorStringFromStdException(), ex, and push_msg().
~UGError()
virtual ug::UGError::~UGError () inline virtual
virtual destructor
Member Function Documentation
get_file()
const std::string& ug::UGError::get_file (size_t i) const inline
returns the file where a message occured
References m_vFile.
Referenced by get_stacktrace(), ug::bridge::RunShell(), ug::vrl::throwUgErrorAsJavaException(), ug_check_registry(), ug_init_bridge(), ug_init_path(), ug_init_plugins(), ug::bridge::lua::UGErrorTraceback(), and ugshell_main().
get_line()
unsigned long ug::UGError::get_line (size_t i) const inline
returns the line where a message occured
References m_vLine.
Referenced by get_stacktrace(), ug::bridge::RunShell(), ug::vrl::throwUgErrorAsJavaException(), ug_check_registry(), ug_init_bridge(), ug_init_path(), ug_init_plugins(), ug::bridge::lua::UGErrorTraceback(), and ugshell_main().
get_msg() [1/2]
const std::string& ug::UGError::get_msg () const inline
returns the initial message
References m_vMsg.
Referenced by ug::AttachAct(), ug::AttachProperty(), ug::FileReaderSWC::create_grid(), ug::bridge::DebugShell(), ug::ExportGridToSWC(), get_stacktrace(), ug::IntersectCoplanarTriangles(), ug::bridge::RunShell(), ug::vrl::throwUgErrorAsJavaException(), ug_check_registry(), ug_init_bridge(), ug_init_path(), ug_init_plugins(), ug::bridge::lua::UGErrorTraceback(), and ugshell_main().
get_msg() [2/2]
const std::string& ug::UGError::get_msg (size_t i) const inline
returns a message in the message-stack (innermost is first)
References m_vMsg.
get_stacktrace()
std::string ug::UGError::get_stacktrace () const inline
References get_file(), get_line(), get_msg(), and num_msg().
Referenced by ug::bridge::LUACompiler::createVM().
num_msg()
size_t ug::UGError::num_msg () const inline
number of messages in message-stack
References m_vMsg.
Referenced by ug::bridge::DebugShell(), get_stacktrace(), ug::bridge::RunShell(), ug::vrl::throwUgErrorAsJavaException(), ug_check_registry(), ug_init_bridge(), ug_init_path(), ug_init_plugins(), ug::bridge::lua::UGErrorTraceback(), and ugshell_main().
push_msg() [1/2]
void ug::UGError::push_msg (const char * msg, const char * file = " -- no file -- ", const unsigned long line = 0) inline
adds a message to the message stack
References m_vFile, m_vLine, and m_vMsg.
push_msg() [2/2]
void ug::UGError::push_msg (const std::string & msg, const char * file = " -- no file -- ", const unsigned long line = 0) inline
adds a message to the message stack
References m_vFile, m_vLine, and m_vMsg.
Referenced by ug::GridReaderVTU::create_cells(), ug::LocalFiniteElementProvider::register_set(), ug::SubLocalDoFSet< TDim >::SubLocalDoFSet(), UGError(), and ug::UGError_ReferenceElementMissing::UGError_ReferenceElementMissing().
Member Data Documentation
m_vFile
std::vector<std::string> ug::UGError::m_vFile protected
Referenced by get_file(), and push_msg().
m_vLine
std::vector<unsigned long> ug::UGError::m_vLine protected
Referenced by get_line(), and push_msg().
m_vMsg
std::vector<std::string> ug::UGError::m_vMsg protected
Referenced by get_msg(), num_msg(), and push_msg().
The documentation for this class was generated from the following files:
ugbase/common/error.h
ugbase/common/error.cpp