ug4: ug::GridLayoutMap Class Reference
ug::GridLayoutMap Class Reference
lets you access layouts by type and key
#include <parallel_grid_layout.h>
Classes
struct Types
defines the types that are used by a LayoutMap for a given TType.
Public Types
typedef int Key
Public Member Functions
void clear ()
template<class TType >
Types< TType >::Map::iterator erase_layout (typename Types< TType >::Map::iterator iter)
erases the specified layout
template<class TType >
void erase_layout (const Key &key)
erases the specified layout if it exists
template<class TType >
Types< TType >::Layout & get_layout (const Key &key)
creates the required layout if it doesn't exist already.
template<class TType >
const Types< TType >::Layout & get_layout (const Key &key) const
template<class TType >
bool has_layout (const Key &key) const
checks whether the layout associated with the given key exists for the given type.
void remove_empty_interfaces ()
removes empty interfaces.
template<class TType >
Types< TType >::Map::iterator layouts_begin ()
begin-iterator to the layout-map for the given type.
template<class TType >
Types< TType >::Map::const_iterator layouts_begin () const
begin-iterator to the layout-map for the given type.
template<class TType >
Types< TType >::Map::iterator layouts_end ()
end-iterator to the layout-map for the given type.
template<class TType >
Types< TType >::Map::const_iterator layouts_end () const
end-iterator to the layout-map for the given type.
Private Member Functions
template<class TType >
Types< TType >::Map & get_layout_map ()
template<class TType >
const Types< TType >::Map & get_layout_map () const
Types< Vertex >::Map & get_layout_map (Vertex *)
the argument is only a dummy to allow to choose the right method at compile time
const Types< Vertex >::Map & get_layout_map (Vertex *) const
the argument is only a dummy to allow to choose the right method at compile time
Types< Edge >::Map & get_layout_map (Edge *)
the argument is only a dummy to allow to choose the right method at compile time
const Types< Edge >::Map & get_layout_map (Edge *) const
the argument is only a dummy to allow to choose the right method at compile time
Types< Face >::Map & get_layout_map (Face *)
the argument is only a dummy to allow to choose the right method at compile time
const Types< Face >::Map & get_layout_map (Face *) const
the argument is only a dummy to allow to choose the right method at compile time
Types< Volume >::Map & get_layout_map (Volume *)
the argument is only a dummy to allow to choose the right method at compile time
const Types< Volume >::Map & get_layout_map (Volume *) const
the argument is only a dummy to allow to choose the right method at compile time
Private Attributes
Types< Edge >::Map m_edgeLayoutMap
Types< Face >::Map m_faceLayoutMap
Types< Vertex >::Map m_vertexLayoutMap
Types< Volume >::Map m_volumeLayoutMap
Detailed Description
lets you access layouts by type and key
The GridLayoutMap helps you to organize your layouts (e.g. master- and slave-layouts).
You may query layouts for Vertex, Edge, Face and Volume.
You may use a LayoutMap as follows:
GridLayoutMap layoutMap;
assert(!layoutMap.has_layout<Vertex>(0));
VertexLayout& layout = layoutMap.get_layout<Vertex>(0);
assert(layoutMap.has_layout<Vertex>(0));
To get associated types you may use the GridLayoutMap::Types array:
GridLayoutMap::Types<Vertex>::Layout l = layoutMap.get_layout<Vertex>(0);
The Types struct is very useful when it comes to using a LayoutMap in template code, too.
Member Typedef Documentation
typedef int ug::GridLayoutMap::Key
Member Function Documentation
void ug::GridLayoutMap::clear () inline
References get_layout_map(), m_edgeLayoutMap, m_faceLayoutMap, m_vertexLayoutMap, and m_volumeLayoutMap.
Referenced by ug::IDomain< TGrid, TSubsetHandler >::count_ghosts(), and ug::DistributeGrid().
template<class TType > GridLayoutMap::Types< TType >::Map::iterator ug::GridLayoutMap::erase_layout (typename Types< TType >::Map::iterator iter)
erases the specified layout
returns an iterator to the next layout.
Referenced by layouts_end().
template<class TType > void ug::GridLayoutMap::erase_layout (const Key & key)
erases the specified layout if it exists
template<class TType > GridLayoutMap::Types< TType >::Layout & ug::GridLayoutMap::get_layout (const Key & key)
creates the required layout if it doesn't exist already.
Referenced by ug::DistributedGridManager::add_element_to_interface(), ug::DoFDistribution::add_indices_from_layouts(), ug::Partitioner_DynamicBisection< TElem, dim >::copy_partitions_to_children(), ug::IDomain< TGrid, TSubsetHandler >::count_ghosts(), ug::CreateIndexLayouts_DomainDecomposition(), ug::CreateLayoutsFromDistInfos(), ug::CreateLevelIndexLayout(), ug::CreateSurfaceIndexLayout(), ug::ComPol_CheckDistributedParentStates< TLayout >::exchange_data(), ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level(), ug::ParallelDualGraph< TGeomBaseObj, TIndexType, TConnectingObj >::generate_graph(), has_layout(), ug::MightContainGhosts(), ug::PartitionMultiGridLevel_ParmetisKway(), ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection(), and ug::TestGridLayoutMap().
template<class TType > const GridLayoutMap::Types< TType >::Layout & ug::GridLayoutMap::get_layout (const Key & key) const
References layouts_begin(), and UG_THROW.
template<class TType > GridLayoutMap::Types< TType >::Map & ug::GridLayoutMap::get_layout_map () inline private
Referenced by clear(), and get_layout_map().
template<class TType > const GridLayoutMap::Types< TType >::Map & ug::GridLayoutMap::get_layout_map () const inline private
References get_layout_map().
GridLayoutMap::Types< Vertex >::Map & ug::GridLayoutMap::get_layout_map (Vertex *) inline private
the argument is only a dummy to allow to choose the right method at compile time
References get_layout_map(), and m_vertexLayoutMap.
const GridLayoutMap::Types< Vertex >::Map & ug::GridLayoutMap::get_layout_map (Vertex *) const inline private
the argument is only a dummy to allow to choose the right method at compile time
References get_layout_map(), and m_vertexLayoutMap.
GridLayoutMap::Types< Edge >::Map & ug::GridLayoutMap::get_layout_map (Edge *) inline private
the argument is only a dummy to allow to choose the right method at compile time
References get_layout_map(), and m_edgeLayoutMap.
const GridLayoutMap::Types< Edge >::Map & ug::GridLayoutMap::get_layout_map (Edge *) const inline private
the argument is only a dummy to allow to choose the right method at compile time
References get_layout_map(), and m_edgeLayoutMap.
GridLayoutMap::Types< Face >::Map & ug::GridLayoutMap::get_layout_map (Face *) inline private
the argument is only a dummy to allow to choose the right method at compile time
References get_layout_map(), and m_faceLayoutMap.
const GridLayoutMap::Types< Face >::Map & ug::GridLayoutMap::get_layout_map (Face *) const inline private
the argument is only a dummy to allow to choose the right method at compile time
References get_layout_map(), and m_faceLayoutMap.
GridLayoutMap::Types< Volume >::Map & ug::GridLayoutMap::get_layout_map (Volume *) inline private
the argument is only a dummy to allow to choose the right method at compile time
References get_layout_map(), and m_volumeLayoutMap.
const GridLayoutMap::Types< Volume >::Map & ug::GridLayoutMap::get_layout_map (Volume *) const inline private
the argument is only a dummy to allow to choose the right method at compile time
References m_volumeLayoutMap.
template<class TType > bool ug::GridLayoutMap::has_layout (const Key & key) const
checks whether the layout associated with the given key exists for the given type.
References get_layout().
Referenced by ug::DoFDistribution::add_indices_from_layouts(), ug::Partitioner_DynamicBisection< TElem, dim >::copy_partitions_to_children(), ug::IDomain< TGrid, TSubsetHandler >::count_ghosts(), ug::CreateIndexLayouts_DomainDecomposition(), ug::CreateLayoutsFromDistInfos(), ug::CreateLevelIndexLayout(), ug::CreateSurfaceIndexLayout(), ug::ComPol_CheckDistributedParentStates< TLayout >::exchange_data(), ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level(), ug::ParallelDualGraph< TGeomBaseObj, TIndexType, TConnectingObj >::generate_graph(), ug::MightContainGhosts(), ug::PartitionMultiGridLevel_ParmetisKway(), and ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection().
template<class TType > GridLayoutMap::Types< TType >::Map::iterator ug::GridLayoutMap::layouts_begin ()
begin-iterator to the layout-map for the given type.
iter.first will return the key, iter.second the layout (of type LayoutMap::Types<TType>::Layout).
Referenced by get_layout().
template<class TType > GridLayoutMap::Types< TType >::Map::const_iterator ug::GridLayoutMap::layouts_begin () const
begin-iterator to the layout-map for the given type.
iter.first will return the key, iter.second the layout (of type LayoutMap::Types<TType>::Layout).
References layouts_end().
template<class TType > GridLayoutMap::Types< TType >::Map::iterator ug::GridLayoutMap::layouts_end ()
end-iterator to the layout-map for the given type.
iter.first will return the key, iter.second the layout (of type LayoutMap::Types<TType>::Layout).
Referenced by layouts_begin().
template<class TType > GridLayoutMap::Types< TType >::Map::const_iterator ug::GridLayoutMap::layouts_end () const
end-iterator to the layout-map for the given type.
iter.first will return the key, iter.second the layout (of type LayoutMap::Types<TType>::Layout).
References erase_layout().
void ug::GridLayoutMap::remove_empty_interfaces ()
removes empty interfaces.
References m_edgeLayoutMap, m_faceLayoutMap, m_vertexLayoutMap, and m_volumeLayoutMap.
Member Data Documentation
Types<Edge>::Map ug::GridLayoutMap::m_edgeLayoutMap private
Referenced by clear(), get_layout_map(), and remove_empty_interfaces().
Types<Face>::Map ug::GridLayoutMap::m_faceLayoutMap private
Referenced by clear(), get_layout_map(), and remove_empty_interfaces().
Types<Vertex>::Map ug::GridLayoutMap::m_vertexLayoutMap private
Referenced by clear(), get_layout_map(), and remove_empty_interfaces().
Types<Volume>::Map ug::GridLayoutMap::m_volumeLayoutMap private
Referenced by clear(), get_layout_map(), and remove_empty_interfaces().
The documentation for this class was generated from the following files:
ugbase/lib_grid/parallelization/parallel_grid_layout.h
ugbase/lib_grid/parallelization/parallel_grid_layout.cpp
ugbase/lib_grid/parallelization/parallel_grid_layout_impl.hpp