ug4: ug::ComPol_MatAddRowsOverlap0< TMatrix > Class Template Reference
ug::ComPol_MatAddRowsOverlap0< TMatrix > Class Template Reference
lib_algebra » Parallel Algebra » Parallel Algebra Communication Policies
Communication Policy to copy slave couplings to master row.
#include <communication_policies.h>
Public Member Functions
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual bool collect (ug::BinaryBuffer &buff, const Interface &interface)
writes the interface values into a buffer that will be sent
ComPol_MatAddRowsOverlap0 (TMatrix &rMat, AlgebraIDVec &vGlobalID)
Constructor setting the vector.
virtual bool extract (ug::BinaryBuffer &buff, const Interface &interface)
writes values from a buffer into the interface
Public Member Functions inherited from pcl::ICommunicationPolicy< IndexLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
virtual ~ICommunicationPolicy ()
Private Attributes
AlgebraIDHashList m_algIDHash
TMatrix & m_rMat
AlgebraIDVec & m_vGlobalID
Additional Inherited Members
Public Types inherited from pcl::ICommunicationPolicy< IndexLayout >
typedef Layout::Interface Interface
typedef IndexLayout Layout
Detailed Description
template<class TMatrix>
class ug::ComPol_MatAddRowsOverlap0< TMatrix >
Communication Policy to copy slave couplings to master row.
This Communication policy assumes that the matrix is stored additively with no overlap. It then copies the row entries of the slaves indices to the corresponding master rows. Only those values are copied that have if the index the slave couples to has also a representation on the other process. This means that couplings to inner indices or to other slave/master, that have only connections to other processes, are not taken into account.
Template Parameters
TMatrix matrix type
Constructor & Destructor Documentation
ComPol_MatAddRowsOverlap0()
template<class TMatrix > ug::ComPol_MatAddRowsOverlap0< TMatrix >::ComPol_MatAddRowsOverlap0 (TMatrix & rMat, AlgebraIDVec & vGlobalID) inline
Constructor setting the vector.
vGlobalID must have size >= mat.num_rows()
References ug::ComPol_MatAddRowsOverlap0< TMatrix >::m_rMat, and UG_ASSERT.
Member Function Documentation
begin_layout_extraction()
template<class TMatrix > virtual bool ug::ComPol_MatAddRowsOverlap0< TMatrix >::begin_layout_extraction (const Layout * pLayout) inline virtual
signals the beginning of a layout extraction.
the default implementation returns true and does nothing else. This method is only called on processes which extract data.
Reimplemented from pcl::ICommunicationPolicy< IndexLayout >.
References ug::GenerateAlgebraIDHashList(), ug::ComPol_MatAddRowsOverlap0< TMatrix >::m_algIDHash, and ug::ComPol_MatAddRowsOverlap0< TMatrix >::m_vGlobalID.
collect()
template<class TMatrix > virtual bool ug::ComPol_MatAddRowsOverlap0< TMatrix >::collect (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
writes the interface values into a buffer that will be sent
done
Implements pcl::ICommunicationPolicy< IndexLayout >.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::begin(), pcl::OrderedInterface< TType, TContainer, TAlloc >::end(), pcl::OrderedInterface< TType, TContainer, TAlloc >::get_element(), ug::ComPol_MatAddRowsOverlap0< TMatrix >::m_rMat, ug::ComPol_MatAddRowsOverlap0< TMatrix >::m_vGlobalID, PROFILE_BEGIN_GROUP, and ug::Serialize().
extract()
template<class TMatrix > virtual bool ug::ComPol_MatAddRowsOverlap0< TMatrix >::extract (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
writes values from a buffer into the interface
done
Implements pcl::ICommunicationPolicy< IndexLayout >.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::begin(), ug::Deserialize(), pcl::OrderedInterface< TType, TContainer, TAlloc >::end(), pcl::OrderedInterface< TType, TContainer, TAlloc >::get_element(), ug::Hash< TKey, TValue >::get_entry(), ug::ComPol_MatAddRowsOverlap0< TMatrix >::m_algIDHash, ug::ComPol_MatAddRowsOverlap0< TMatrix >::m_rMat, and PROFILE_BEGIN_GROUP.
Member Data Documentation
m_algIDHash
template<class TMatrix > AlgebraIDHashList ug::ComPol_MatAddRowsOverlap0< TMatrix >::m_algIDHash private
Referenced by ug::ComPol_MatAddRowsOverlap0< TMatrix >::begin_layout_extraction(), and ug::ComPol_MatAddRowsOverlap0< TMatrix >::extract().
m_rMat
template<class TMatrix > TMatrix& ug::ComPol_MatAddRowsOverlap0< TMatrix >::m_rMat private
Referenced by ug::ComPol_MatAddRowsOverlap0< TMatrix >::collect(), ug::ComPol_MatAddRowsOverlap0< TMatrix >::ComPol_MatAddRowsOverlap0(), and ug::ComPol_MatAddRowsOverlap0< TMatrix >::extract().
m_vGlobalID
template<class TMatrix > AlgebraIDVec& ug::ComPol_MatAddRowsOverlap0< TMatrix >::m_vGlobalID private
Referenced by ug::ComPol_MatAddRowsOverlap0< TMatrix >::begin_layout_extraction(), and ug::ComPol_MatAddRowsOverlap0< TMatrix >::collect().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/parallelization/communication_policies.h