ug4: ug::BoostMinimumDegreeOrdering< TAlgebra, O_t > Class Template Reference
ug::BoostMinimumDegreeOrdering< TAlgebra, O_t > Class Template Reference final
Public Types
typedef IOrderingAlgorithm< TAlgebra, O_t > baseclass
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::bidirectionalS > G_t
typedef TAlgebra::matrix_type M_t
typedef TAlgebra::vector_type V_t
Public Types inherited from ug::IOrderingAlgorithm< TAlgebra, O_t >
typedef TAlgebra::matrix_type M_t
typedef TAlgebra::vector_type V_t
Public Member Functions
BoostMinimumDegreeOrdering ()
BoostMinimumDegreeOrdering (const BoostMinimumDegreeOrdering< TAlgebra, O_t > &parent)
clone constructor
void check ()
SmartPtr< IOrderingAlgorithm< TAlgebra, O_t > > clone ()
void compute ()
void init (M_t *, const O_t &)
void init (M_t *, const V_t &, const O_t &)
void init (M_t *A)
void init (M_t *A, const V_t &)
virtual const char * name () const
O_t & ordering ()
Public Member Functions inherited from ug::IOrderingAlgorithm< TAlgebra, O_t >
virtual void init (M_t *, const std::vector< size_t > &)=0
virtual void init (M_t *, const V_t &, const std::vector< size_t > &)=0
IOrderingAlgorithm ()
virtual ~IOrderingAlgorithm ()
Private Attributes
G_t g
O_t o
Member Typedef Documentation
baseclass
template<typename TAlgebra , typename O_t > typedef IOrderingAlgorithm<TAlgebra, O_t> ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::baseclass
G_t
template<typename TAlgebra , typename O_t > typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS> ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::G_t
M_t
template<typename TAlgebra , typename O_t > typedef TAlgebra::matrix_type ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::M_t
V_t
template<typename TAlgebra , typename O_t > typedef TAlgebra::vector_type ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::V_t
Constructor & Destructor Documentation
BoostMinimumDegreeOrdering() [1/2]
template<typename TAlgebra , typename O_t > ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::BoostMinimumDegreeOrdering () inline
BoostMinimumDegreeOrdering() [2/2]
template<typename TAlgebra , typename O_t > ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::BoostMinimumDegreeOrdering (const BoostMinimumDegreeOrdering< TAlgebra, O_t > & parent) inline
clone constructor
Member Function Documentation
check()
template<typename TAlgebra , typename O_t > void ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::check () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::is_permutation(), ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::name(), ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::o, and UG_COND_THROW.
Referenced by ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::compute().
clone()
template<typename TAlgebra , typename O_t > SmartPtr<IOrderingAlgorithm<TAlgebra, O_t> > ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::clone () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References make_sp().
compute()
template<typename TAlgebra , typename O_t > void ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::compute () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::check(), boost::degree(), ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::g, boost::get(), ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::name(), boost::num_vertices(), ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::o, UG_LOG, UG_THROW, and boost::vertices().
init() [1/4]
template<typename TAlgebra , typename O_t > void ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::init (M_t * , const O_t &) inline
References ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::name(), and UG_THROW.
init() [2/4]
template<typename TAlgebra , typename O_t > void ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::init (M_t * , const V_t & , const O_t &) inline
References ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::name(), and UG_THROW.
init() [3/4]
template<typename TAlgebra , typename O_t > void ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::init (M_t * A) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::g, ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::name(), and UG_LOG.
init() [4/4]
template<typename TAlgebra , typename O_t > void ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::init (M_t * A, const V_t &) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
name()
template<typename TAlgebra , typename O_t > virtual const char* ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::name () const inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
Referenced by ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::check(), ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::compute(), and ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::init().
ordering()
template<typename TAlgebra , typename O_t > O_t& ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::ordering () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::o.
Member Data Documentation
g
template<typename TAlgebra , typename O_t > G_t ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::g private
Referenced by ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::compute(), and ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::init().
o
template<typename TAlgebra , typename O_t > O_t ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::o private
Referenced by ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::check(), ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::compute(), and ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::ordering().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/ordering_strategies/algorithms/boost_minimum_degree_ordering.cpp