ug4: ug::MathTensor< 1, N, T > Class Template Reference
ug::MathTensor< 1, N, T > Class Template Reference
ugbase » Math » Tensor
#include <math_tensor.h>
Public Types
typedef size_t size_type
typedef T value_type
Public Member Functions
MathTensor (const bool init=true)
MathTensor (const MathTensor &v)
MathTensor & operator= (const MathTensor &v)
MathTensor & operator= (T val)
sets all values of the tensor to a value
value_type & operator[] (size_t i)
const value_type & operator[] (size_t i) const
size_t rank () const
void set (T val)
size_t size () const
Static Public Attributes
static const size_t Dimension = N
static const size_t Rank = 1
Protected Member Functions
void assign (const MathTensor< 1, N, T > &v)
Protected Attributes
value_type m_data [N]
Member Typedef Documentation
size_type
template<size_t N, typename T > typedef size_t ug::MathTensor< 1, N, T >::size_type
value_type
template<size_t N, typename T > typedef T ug::MathTensor< 1, N, T >::value_type
Constructor & Destructor Documentation
MathTensor() [1/2]
template<size_t N, typename T > ug::MathTensor< 1, N, T >::MathTensor (const bool init = true) inline
References init(), and ug::MathTensor< TRank, N, T >::set().
MathTensor() [2/2]
template<size_t N, typename T > ug::MathTensor< 1, N, T >::MathTensor (const MathTensor< 1, N, T > & v) inline
References ug::MathTensor< TRank, N, T >::assign().
Member Function Documentation
assign()
template<size_t N, typename T > void ug::MathTensor< 1, N, T >::assign (const MathTensor< 1, N, T > & v) inline protected
References ug::MathTensor< TRank, N, T >::m_data.
operator=() [1/2]
template<size_t N, typename T > MathTensor& ug::MathTensor< 1, N, T >::operator= (const MathTensor< 1, N, T > & v) inline
References ug::MathTensor< TRank, N, T >::assign().
operator=() [2/2]
template<size_t N, typename T > MathTensor& ug::MathTensor< 1, N, T >::operator= (T val) inline
sets all values of the tensor to a value
References ug::MathTensor< TRank, N, T >::set().
operator[]() [1/2]
template<size_t N, typename T > value_type& ug::MathTensor< 1, N, T >::operator[] (size_t i) inline
References ug::MathTensor< TRank, N, T >::m_data, ug::MathTensor< TRank, N, T >::size(), and UG_ASSERT.
operator[]() [2/2]
template<size_t N, typename T > const value_type& ug::MathTensor< 1, N, T >::operator[] (size_t i) const inline
References ug::MathTensor< TRank, N, T >::m_data, ug::MathTensor< TRank, N, T >::size(), and UG_ASSERT.
rank()
template<size_t N, typename T > size_t ug::MathTensor< 1, N, T >::rank () const inline
set()
template<size_t N, typename T > void ug::MathTensor< 1, N, T >::set (T val) inline
References ug::MathTensor< TRank, N, T >::m_data.
size()
template<size_t N, typename T > size_t ug::MathTensor< 1, N, T >::size () const inline
Member Data Documentation
Dimension
template<size_t N, typename T > const size_t ug::MathTensor< 1, N, T >::Dimension = N static
m_data
template<size_t N, typename T > value_type ug::MathTensor< 1, N, T >::m_data[N] protected
Rank
template<size_t N, typename T > const size_t ug::MathTensor< 1, N, T >::Rank = 1 static
The documentation for this class was generated from the following file:
ugbase/common/math/math_vector_matrix/math_tensor.h