ug4: ug::HFV1Geometry< TElem, TWorldDim > Class Template Reference
ug::HFV1Geometry< TElem, TWorldDim > Class Template Reference
#include <hfv1_geom.h>
Classes
struct MidID
struct NatEdgeInfo
struct NewEdgeInfo
class SCV
class SCVF
Public Member Functions
HFV1Geometry ()
constructor
size_t num_scv () const
number of SubControlVolumes
size_t num_scv_ips () const
returns number of all scv ips
size_t num_scvf () const
number of SubControlVolumeFaces
size_t num_scvf_ips () const
returns number of all scv ips
size_t num_sh () const
number of shape functions
void print ()
const SCV & scv (size_t i) const
const access to SubControlVolume number i
const MathVector< worldDim > * scv_global_ips () const
returns all ips of scv as they appear in scv loop
const MathVector< dim > * scv_local_ips () const
returns all ips of scv as they appear in scv loop
const SCVF & scvf (size_t i) const
const access to SubControlVolumeFace number i
const MathVector< worldDim > * scvf_global_ips () const
returns all ips of scv as they appear in scv loop
const MathVector< dim > * scvf_local_ips () const
returns all ips of scv as they appear in scv loop
void update (GridObject *pElem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update values for an element
Static Public Attributes
static const int dim = ref_elem_type::dim
dimension of reference element
static const bool staticLocalData = true
flag indicating if local data may change
static const bool usesHangingNodes = true
Hanging node flag: this Geometry does support hanging nodes.
static const int worldDim = TWorldDim
dimension of world
Protected Member Functions
void compute_side_midpoints (size_t i, MathVector< dim > &locSideMid, MathVector< worldDim > &gloSideMid)
void compute_side_midpoints (size_t i, size_t j, size_t k, size_t l, MathVector< dim > &locSideMid, MathVector< worldDim > &gloSideMid)
void compute_side_midpoints (size_t i, size_t j, size_t k, MathVector< dim > &locSideMid, MathVector< worldDim > &gloSideMid)
void copy_global_corners (SCVF &scvf)
void copy_global_corners (SCV &scv)
void copy_local_corners (SCVF &scvf)
void copy_local_corners (SCV &scv)
size_t get_child_edge_of_corner (size_t i, size_t co)
Protected Attributes
std::vector< MathVector< worldDim > > m_vGlobSCVFIP
std::vector< MathVector< worldDim > > m_vGlobSCVIP
std::vector< MathVector< dim > > m_vLocSCVFIP
std::vector< MathVector< dim > > m_vLocSCVIP
Private Types
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
type of reference element
Private Attributes
std::vector< MathVector< worldDim > > m_gloMid [dim+1]
std::vector< MathVector< dim > > m_locMid [dim+1]
size_t m_numSh
TElem * m_pElem
ReferenceMapping< ref_elem_type, worldDim > m_rMapping
const ref_elem_type & m_rRefElem
std::vector< NatEdgeInfo > m_vNatEdgeInfo
std::vector< NewEdgeInfo > m_vNewEdgeInfo
std::vector< SCV > m_vSCV
std::vector< SCVF > m_vSCVF
Static Private Attributes
static const size_t m_numNaturalSCV = ref_elem_type::numCorners
number of SubControlVolumes
static const size_t m_numNaturalSCVF = ref_elem_type::numEdges
number of SubControlVolumeFaces
Member Typedef Documentation
template<typename TElem , int TWorldDim> typedef reference_element_traits<TElem>::reference_element_type ug::HFV1Geometry< TElem, TWorldDim >::ref_elem_type private
type of reference element
Constructor & Destructor Documentation
template<typename TElem , int TWorldDim> ug::HFV1Geometry< TElem, TWorldDim >::HFV1Geometry ()
constructor
References ug::HFV1Geometry< TElem, TWorldDim >::dim, ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, ug::HFV1Geometry< TElem, TWorldDim >::m_numNaturalSCV, ug::HFV1Geometry< TElem, TWorldDim >::m_rRefElem, ug::HFV1Geometry< TElem, TWorldDim >::m_vSCV, and ug::HFV1Geometry< TElem, TWorldDim >::update().
Member Function Documentation
template<typename TElem , int TWorldDim> void ug::HFV1Geometry< TElem, TWorldDim >::compute_side_midpoints (size_t i, MathVector< dim > & locSideMid, MathVector< worldDim > & gloSideMid) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, and ug::HFV1Geometry< TElem, TWorldDim >::m_rRefElem.
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> void ug::HFV1Geometry< TElem, TWorldDim >::compute_side_midpoints (size_t i, size_t j, size_t k, size_t l, MathVector< dim > & locSideMid, MathVector< worldDim > & gloSideMid) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, and ug::VecAdd().
template<typename TElem , int TWorldDim> void ug::HFV1Geometry< TElem, TWorldDim >::compute_side_midpoints (size_t i, size_t j, size_t k, MathVector< dim > & locSideMid, MathVector< worldDim > & gloSideMid) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, and ug::VecAdd().
template<typename TElem , int TWorldDim> void ug::HFV1Geometry< TElem, TWorldDim >::copy_global_corners (SCVF & scvf) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::MidID::dim, ug::HFV1Geometry< TElem, TWorldDim >::MidID::id, ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::SCVF::m_midId, ug::HFV1Geometry< TElem, TWorldDim >::SCVF::m_vGloPos, and ug::HFV1Geometry< TElem, TWorldDim >::SCVF::num_corners().
template<typename TElem , int TWorldDim> void ug::HFV1Geometry< TElem, TWorldDim >::copy_global_corners (SCV & scv) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::MidID::dim, ug::HFV1Geometry< TElem, TWorldDim >::MidID::id, ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_midId, ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_vGloPos, ug::HFV1Geometry< TElem, TWorldDim >::SCV::num_corners(), and UG_ASSERT.
template<typename TElem , int TWorldDim> void ug::HFV1Geometry< TElem, TWorldDim >::copy_local_corners (SCVF & scvf) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::MidID::dim, ug::HFV1Geometry< TElem, TWorldDim >::MidID::id, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, ug::HFV1Geometry< TElem, TWorldDim >::SCVF::m_midId, ug::HFV1Geometry< TElem, TWorldDim >::SCVF::m_vLocPos, and ug::HFV1Geometry< TElem, TWorldDim >::SCVF::num_corners().
template<typename TElem , int TWorldDim> void ug::HFV1Geometry< TElem, TWorldDim >::copy_local_corners (SCV & scv) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::MidID::dim, ug::HFV1Geometry< TElem, TWorldDim >::MidID::id, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_midId, ug::HFV1Geometry< TElem, TWorldDim >::SCV::m_vLocPos, ug::HFV1Geometry< TElem, TWorldDim >::SCV::num_corners(), and UG_ASSERT.
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::get_child_edge_of_corner (size_t i, size_t co) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_vNatEdgeInfo, and ug::HFV1Geometry< TElem, TWorldDim >::m_vNewEdgeInfo.
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::num_scv () const inline
number of SubControlVolumes
References ug::HFV1Geometry< TElem, TWorldDim >::m_vSCV.
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::scv(), ug::DimHFV1Geometry< TDim, TWorldDim >::scv(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::num_scv_ips () const inline
returns number of all scv ips
References ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVIP.
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::num_scvf () const inline
number of SubControlVolumeFaces
References ug::HFV1Geometry< TElem, TWorldDim >::m_vSCVF.
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::scvf(), ug::DimHFV1Geometry< TDim, TWorldDim >::scvf(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::num_scvf_ips () const inline
returns number of all scv ips
References ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVFIP.
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::num_sh () const inline
number of shape functions
References ug::HFV1Geometry< TElem, TWorldDim >::m_numSh.
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::SCVF::global_grad(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_grad(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_grad(), ug::HFV1Geometry< TElem, TWorldDim >::SCVF::local_grad(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_grad(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_grad(), ug::HFV1Geometry< TElem, TWorldDim >::SCVF::shape(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::shape(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> void ug::HFV1Geometry< TElem, TWorldDim >::print ()
References ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, ug::HFV1Geometry< TElem, TWorldDim >::m_vSCV, ug::HFV1Geometry< TElem, TWorldDim >::m_vSCVF, UG_LOG, and ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const SCV& ug::HFV1Geometry< TElem, TWorldDim >::scv (size_t i) const inline
const access to SubControlVolume number i
References ug::HFV1Geometry< TElem, TWorldDim >::m_vSCV, ug::HFV1Geometry< TElem, TWorldDim >::num_scv(), and UG_ASSERT.
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::HFV1Geometry< TElem, TWorldDim >::scv_global_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVIP.
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::HFV1Geometry< TElem, TWorldDim >::scv_local_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::HFV1Geometry< TElem, TWorldDim >::m_vLocSCVIP.
template<typename TElem , int TWorldDim> const SCVF& ug::HFV1Geometry< TElem, TWorldDim >::scvf (size_t i) const inline
const access to SubControlVolumeFace number i
References ug::HFV1Geometry< TElem, TWorldDim >::m_vSCVF, ug::HFV1Geometry< TElem, TWorldDim >::num_scvf(), and UG_ASSERT.
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::HFV1Geometry< TElem, TWorldDim >::scvf_global_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVFIP.
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::HFV1Geometry< TElem, TWorldDim >::scvf_local_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::HFV1Geometry< TElem, TWorldDim >::m_vLocSCVFIP.
template<typename TElem , int TWorldDim> void ug::HFV1Geometry< TElem, TWorldDim >::update (GridObject * pElem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update values for an element
References ug::AveragePositions(), ug::CollectEdgesSorted(), ug::CollectFacesSorted(), ug::HFV1Geometry< TElem, TWorldDim >::compute_side_midpoints(), ug::CSEDGE_CONSTRAINED_EDGE, ug::CSEDGE_CONSTRAINING_EDGE, ug::CSEDGE_REGULAR_EDGE, ug::CSFACE_CONSTRAINING_QUADRILATERAL, ug::CSFACE_CONSTRAINING_TRIANGLE, dim, ug::HFV1Geometry< TElem, TWorldDim >::dim, ug::HFV1Geometry< TElem, TWorldDim >::get_child_edge_of_corner(), ug::HFV1Geometry< TElem, TWorldDim >::SCVF::global_ip(), ug::HFV1Geometry< TElem, TWorldDim >::SCV::global_ip(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::ISubsetHandler::grid(), ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::LFEID::LAGRANGE, ug::HFV1Geometry< TElem, TWorldDim >::SCVF::local_ip(), ug::HFV1Geometry< TElem, TWorldDim >::SCV::local_ip(), ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, ug::HFV1Geometry< TElem, TWorldDim >::SCVF::m_numCorners, ug::HFV1Geometry< TElem, TWorldDim >::m_numNaturalSCV, ug::HFV1Geometry< TElem, TWorldDim >::m_numNaturalSCVF, ug::HFV1Geometry< TElem, TWorldDim >::m_numSh, ug::HFV1Geometry< TElem, TWorldDim >::m_pElem, ug::HFV1Geometry< TElem, TWorldDim >::m_rMapping, ug::HFV1Geometry< TElem, TWorldDim >::m_rRefElem, ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVFIP, ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVIP, ug::HFV1Geometry< TElem, TWorldDim >::m_vLocSCVFIP, ug::HFV1Geometry< TElem, TWorldDim >::m_vLocSCVIP, ug::HFV1Geometry< TElem, TWorldDim >::m_vNatEdgeInfo, ug::HFV1Geometry< TElem, TWorldDim >::m_vNewEdgeInfo, ug::HFV1Geometry< TElem, TWorldDim >::m_vSCV, ug::HFV1Geometry< TElem, TWorldDim >::m_vSCVF, ug::MatVecMult(), ug::HFV1Geometry< TElem, TWorldDim >::num_scv(), ug::HFV1Geometry< TElem, TWorldDim >::num_scvf(), ug::HFV1Geometry< TElem, TWorldDim >::num_sh(), ug::HFV1Geometry< TElem, TWorldDim >::scv(), ug::HFV1Geometry< TElem, TWorldDim >::scvf(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), ug::ReferenceMapping< TRefElem, TWorldDim >::sqrt_gram_det(), UG_ASSERT, UG_THROW, ug::ReferenceMapping< TRefElem, TWorldDim >::update(), ug::VecDot(), ug::VecInterpolateLinear(), and ug::VecSubtract().
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::DimHFV1Geometry(), and ug::HFV1Geometry< TElem, TWorldDim >::HFV1Geometry().
Member Data Documentation
template<typename TElem , int TWorldDim> const int ug::HFV1Geometry< TElem, TWorldDim >::dim = ref_elem_type::dim static
dimension of reference element
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::HFV1Geometry(), ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> std::vector<MathVector<worldDim> > ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid[dim+1] private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::compute_side_midpoints(), ug::DimHFV1Geometry< TDim, TWorldDim >::compute_side_midpoints(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::compute_side_midpoints(), ug::HFV1Geometry< TElem, TWorldDim >::copy_global_corners(), ug::DimHFV1Geometry< TDim, TWorldDim >::copy_global_corners(), ug::HFV1Geometry< TElem, TWorldDim >::HFV1Geometry(), ug::HFV1Geometry< TElem, TWorldDim >::print(), ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> std::vector<MathVector<dim> > ug::HFV1Geometry< TElem, TWorldDim >::m_locMid[dim+1] private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::compute_side_midpoints(), ug::DimHFV1Geometry< TDim, TWorldDim >::compute_side_midpoints(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::compute_side_midpoints(), ug::HFV1Geometry< TElem, TWorldDim >::copy_local_corners(), ug::DimHFV1Geometry< TDim, TWorldDim >::copy_local_corners(), ug::HFV1Geometry< TElem, TWorldDim >::HFV1Geometry(), ug::HFV1Geometry< TElem, TWorldDim >::print(), ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const size_t ug::HFV1Geometry< TElem, TWorldDim >::m_numNaturalSCV = ref_elem_type::numCorners static private
number of SubControlVolumes
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::HFV1Geometry(), ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const size_t ug::HFV1Geometry< TElem, TWorldDim >::m_numNaturalSCVF = ref_elem_type::numEdges static private
number of SubControlVolumeFaces
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> size_t ug::HFV1Geometry< TElem, TWorldDim >::m_numSh private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::num_sh(), ug::DimHFV1Geometry< TDim, TWorldDim >::num_sh(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> TElem* ug::HFV1Geometry< TElem, TWorldDim >::m_pElem private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> ReferenceMapping<ref_elem_type, worldDim> ug::HFV1Geometry< TElem, TWorldDim >::m_rMapping private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const ref_elem_type& ug::HFV1Geometry< TElem, TWorldDim >::m_rRefElem private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::compute_side_midpoints(), ug::DimHFV1Geometry< TDim, TWorldDim >::compute_side_midpoints(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::compute_side_midpoints(), ug::HFV1Geometry< TElem, TWorldDim >::HFV1Geometry(), ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> std::vector<MathVector<worldDim> > ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVFIP protected
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::num_scvf_ips(), ug::DimHFV1Geometry< TDim, TWorldDim >::num_scvf_ips(), ug::HFV1Geometry< TElem, TWorldDim >::scvf_global_ips(), ug::DimHFV1Geometry< TDim, TWorldDim >::scvf_global_ips(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<MathVector<worldDim> > ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVIP protected
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::num_scv_ips(), ug::DimHFV1Geometry< TDim, TWorldDim >::num_scv_ips(), ug::HFV1Geometry< TElem, TWorldDim >::scv_global_ips(), ug::DimHFV1Geometry< TDim, TWorldDim >::scv_global_ips(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<MathVector<dim> > ug::HFV1Geometry< TElem, TWorldDim >::m_vLocSCVFIP protected
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::scvf_local_ips(), ug::DimHFV1Geometry< TDim, TWorldDim >::scvf_local_ips(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<MathVector<dim> > ug::HFV1Geometry< TElem, TWorldDim >::m_vLocSCVIP protected
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::scv_local_ips(), ug::DimHFV1Geometry< TDim, TWorldDim >::scv_local_ips(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<NatEdgeInfo> ug::HFV1Geometry< TElem, TWorldDim >::m_vNatEdgeInfo private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::get_child_edge_of_corner(), ug::DimHFV1Geometry< TDim, TWorldDim >::get_child_edge_of_corner(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::get_child_edge_of_corner(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<NewEdgeInfo> ug::HFV1Geometry< TElem, TWorldDim >::m_vNewEdgeInfo private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::get_child_edge_of_corner(), ug::DimHFV1Geometry< TDim, TWorldDim >::get_child_edge_of_corner(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::get_child_edge_of_corner(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<SCV> ug::HFV1Geometry< TElem, TWorldDim >::m_vSCV private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::HFV1Geometry(), ug::HFV1Geometry< TElem, TWorldDim >::num_scv(), ug::DimHFV1Geometry< TDim, TWorldDim >::num_scv(), ug::HFV1Geometry< TElem, TWorldDim >::print(), ug::HFV1Geometry< TElem, TWorldDim >::scv(), ug::DimHFV1Geometry< TDim, TWorldDim >::scv(), ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> std::vector<SCVF> ug::HFV1Geometry< TElem, TWorldDim >::m_vSCVF private
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::num_scvf(), ug::DimHFV1Geometry< TDim, TWorldDim >::num_scvf(), ug::HFV1Geometry< TElem, TWorldDim >::print(), ug::HFV1Geometry< TElem, TWorldDim >::scvf(), ug::DimHFV1Geometry< TDim, TWorldDim >::scvf(), ug::HFV1Geometry< TElem, TWorldDim >::update(), and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
template<typename TElem , int TWorldDim> const bool ug::HFV1Geometry< TElem, TWorldDim >::staticLocalData = true static
flag indicating if local data may change
template<typename TElem , int TWorldDim> const bool ug::HFV1Geometry< TElem, TWorldDim >::usesHangingNodes = true static
Hanging node flag: this Geometry does support hanging nodes.
template<typename TElem , int TWorldDim> const int ug::HFV1Geometry< TElem, TWorldDim >::worldDim = TWorldDim static
dimension of world
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/hfv1_geom.h
ugbase/lib_disc/spatial_disc/disc_util/hfv1_geom.cpp