ug4: boost::SM_edge< T > Class Template Reference
boost::SM_edge< T > Class Template Reference
#include <sparsematrix_boost.h>
Public Member Functions
bool operator!= (const SM_edge &other) const
SM_edge & operator= (SM_edge &&)=default
SM_edge & operator= (SM_edge const &)=default
bool operator== (const SM_edge &other) const
SM_edge ()
SM_edge (int s, int t, T const &v)
SM_edge (SM_edge &&)=default
SM_edge (SM_edge const &)=default
int source () const
int target () const
template<class X >
T const & value (X const &) const
Private Attributes
int _source
int _target
T _value
Constructor & Destructor Documentation
SM_edge() [1/4]
template<class T > boost::SM_edge< T >::SM_edge (SM_edge< T > const &) default
SM_edge() [2/4]
template<class T > boost::SM_edge< T >::SM_edge (SM_edge< T > &&) default
SM_edge() [3/4]
template<class T > boost::SM_edge< T >::SM_edge () inline explicit
References untested.
SM_edge() [4/4]
template<class T > boost::SM_edge< T >::SM_edge (int s, int t, T const & v) inline
References s.
Member Function Documentation
operator!=()
template<class T > bool boost::SM_edge< T >::operator!= (const SM_edge< T > & other) const inline
References boost::SM_edge< T >::operator==(), and untested.
operator=() [1/2]
template<class T > SM_edge& boost::SM_edge< T >::operator= (SM_edge< T > &&) default
operator=() [2/2]
template<class T > SM_edge& boost::SM_edge< T >::operator= (SM_edge< T > const &) default
operator==()
template<class T > bool boost::SM_edge< T >::operator== (const SM_edge< T > & other) const inline
References boost::SM_edge< T >::_source, boost::SM_edge< T >::_target, and untested.
Referenced by boost::SM_edge< T >::operator!=().
source()
template<class T > int boost::SM_edge< T >::source () const inline
References boost::SM_edge< T >::_source.
Referenced by boost::source().
target()
template<class T > int boost::SM_edge< T >::target () const inline
References boost::SM_edge< T >::_target.
Referenced by boost::target().
value()
template<class T > template<class X > T const& boost::SM_edge< T >::value (X const &) const inline
References boost::SM_edge< T >::_value.
Member Data Documentation
_source
template<class T > int boost::SM_edge< T >::_source private
Referenced by boost::SM_edge< T >::operator==(), and boost::SM_edge< T >::source().
_target
template<class T > int boost::SM_edge< T >::_target private
Referenced by boost::SM_edge< T >::operator==(), and boost::SM_edge< T >::target().
_value
template<class T > T boost::SM_edge< T >::_value private
Referenced by boost::SM_edge< T >::value().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/graph_interface/sparsematrix_boost.h