ug4: ug::node_tree::BoxedGroupNode Class Reference
ug::node_tree::BoxedGroupNode Class Reference
A group node featuring a bounding box.
#include <boxed_group_node.h>
Public Member Functions
virtual const vector3 & max_corner () const
virtual const vector3 & min_corner () const
virtual void set_box (const vector3 &minCorner, const vector3 &maxCorner)
virtual ~BoxedGroupNode ()
Public Member Functions inherited from ug::node_tree::GroupNode
virtual void add_child (SPNode node)
virtual void clear ()
virtual SPNode get_child (int index)
virtual int num_children ()
virtual void remove_child (SPNode node)
virtual ~GroupNode ()
Public Member Functions inherited from ug::node_tree::Node
virtual ~Node ()
Public Member Functions inherited from ug::node_tree::Object
unsigned int getObjectCode ()
virtual ~Object ()
Static Public Member Functions
static SPBoxedGroupNode create ()
Static Public Member Functions inherited from ug::node_tree::GroupNode
static SPGroupNode create ()
Protected Member Functions
BoxedGroupNode ()
Protected Member Functions inherited from ug::node_tree::GroupNode
GroupNode ()
Protected Member Functions inherited from ug::node_tree::Node
Node ()
Protected Member Functions inherited from ug::node_tree::Object
Object ()
Object (const Object &obj)
Protected Attributes
vector3 m_vMax
vector3 m_vMin
Protected Attributes inherited from ug::node_tree::GroupNode
std::vector< SPNode > vChildren
Protected Attributes inherited from ug::node_tree::Object
unsigned int m_objectCode
Detailed Description
A group node featuring a bounding box.
...
Constructor & Destructor Documentation
~BoxedGroupNode()
ug::node_tree::BoxedGroupNode::~BoxedGroupNode () virtual
BoxedGroupNode()
ug::node_tree::BoxedGroupNode::BoxedGroupNode () protected
Referenced by create().
Member Function Documentation
create()
SPBoxedGroupNode ug::node_tree::BoxedGroupNode::create () static
References BoxedGroupNode(), ug::node_tree::Object::m_objectCode, and ug::node_tree::OC_BOXED_GROUP_NODE.
max_corner()
const vector3 & ug::node_tree::BoxedGroupNode::max_corner () const virtual
References m_vMax.
Referenced by ug::node_tree::CreateSubOctrees(), ug::node_tree::Traverser_IntersectFaces::handle_boxed_group(), and ug::node_tree::Traverser_ProjectPoint::handle_boxed_group().
min_corner()
const vector3 & ug::node_tree::BoxedGroupNode::min_corner () const virtual
References m_vMin.
Referenced by ug::node_tree::CreateSubOctrees(), ug::node_tree::Traverser_IntersectFaces::handle_boxed_group(), and ug::node_tree::Traverser_ProjectPoint::handle_boxed_group().
set_box()
void ug::node_tree::BoxedGroupNode::set_box (const vector3 & minCorner, const vector3 & maxCorner) virtual
References m_vMax, and m_vMin.
Member Data Documentation
m_vMax
vector3 ug::node_tree::BoxedGroupNode::m_vMax protected
Referenced by max_corner(), and set_box().
m_vMin
vector3 ug::node_tree::BoxedGroupNode::m_vMin protected
Referenced by min_corner(), and set_box().
The documentation for this class was generated from the following files:
ugbase/common/node_tree/boxed_group_node.h
ugbase/common/node_tree/boxed_group_node.cpp