ug4: ug::TetrahedronDescriptor Class Reference
ug::TetrahedronDescriptor Class Reference
only used to initialize a tetrahedron. for all other tasks you should use VolumeDescripor.
#include <grid_objects_3d.h>
Public Member Functions
uint num_vertices () const
TetrahedronDescriptor ()
TetrahedronDescriptor (const TetrahedronDescriptor &td)
TetrahedronDescriptor (const VolumeVertices &vv)
TetrahedronDescriptor (Vertex *v1, Vertex *v2, Vertex *v3, Vertex *v4)
Vertex * vertex (size_t index) const
Protected Attributes
Vertex * m_vertex [4]
Detailed Description
only used to initialize a tetrahedron. for all other tasks you should use VolumeDescripor.
please be sure to pass the vertices in the correct order: v1, v2, v3: bottom-vertices in counterclockwise order (if viewed from the top). v4: top
Constructor & Destructor Documentation
TetrahedronDescriptor() [1/4]
ug::TetrahedronDescriptor::TetrahedronDescriptor () inline
TetrahedronDescriptor() [2/4]
ug::TetrahedronDescriptor::TetrahedronDescriptor (const TetrahedronDescriptor & td)
References vertex().
TetrahedronDescriptor() [3/4]
ug::TetrahedronDescriptor::TetrahedronDescriptor (const VolumeVertices & vv)
References ug::VolumeVertices::num_vertices(), and ug::VolumeVertices::vertex().
TetrahedronDescriptor() [4/4]
ug::TetrahedronDescriptor::TetrahedronDescriptor (Vertex * v1, Vertex * v2, Vertex * v3, Vertex * v4)
Member Function Documentation
num_vertices()
uint ug::TetrahedronDescriptor::num_vertices () const inline
vertex()
Vertex* ug::TetrahedronDescriptor::vertex (size_t index) const inline
Referenced by ug::Tetrahedron::Tetrahedron(), and TetrahedronDescriptor().
Member Data Documentation
m_vertex
Vertex* ug::TetrahedronDescriptor::m_vertex[4] protected
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid_objects/grid_objects_3d.h
ugbase/lib_grid/grid_objects/grid_objects_3d.cpp