ug4: ug::IElemError< TDomain > Class Template Reference
ug::IElemError< TDomain > Class Template Reference
#include <elem_disc_interface.h>
Public Types
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from ug::IElemDiscBase< TDomain >
typedef TDomain domain_type
Domain type.
typedef TDomain::position_type position_type
Position type.
Public Types inherited from ug::IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
Domain type.
typedef IElemDisc< TDomain > leaf_type
Barton Nackman trick (TODO: needed?)
Public Member Functions
IElemError (const char *functions, const char *subsets)
IElemError (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from ug::IElemDiscBase< TDomain >
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
returns approximation space
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
returns approximation space
void check_setup (bool bNonRegularGrid)
checks the setup of the elem disc
void clear_imports ()
removes all imports
SmartPtr< TDomain > domain ()
returns the domain
ConstSmartPtr< TDomain > domain () const
returns the domain
const FunctionGroup & function_group () const
returns the current function group
ConstSmartPtr< FunctionPattern > function_pattern () const
returns the current function pattern
IDataImport< dim > & get_import (size_t i)
returns an import
IElemDiscBase (const char *functions="", const char *subsets="")
Constructor.
IElemDiscBase (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Constructor.
bool is_time_dependent () const
returns if assembling is time-dependent
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
returns the local time solutions
const FunctionIndexMapping & map () const
returns the current function index mapping
size_t num_fct () const
number of functions this discretization handles
size_t num_imports () const
returns number of imports
size_t num_subsets () const
number of subsets this discretization handles
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegularGrid)=0
requests assembling for trial spaces and grid type
void register_import (IDataImport< dim > &Imp)
registers a data import
virtual bool requests_local_time_series ()
returns if local time series needed by assembling
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
sets the approximation space
void set_functions (const std::string &functions)
Approximation Space.
void set_functions (const std::vector< std::string > &functions)
sets functions by vector of names
void set_stationary ()
void set_stationary (bool bStationaryForced=true)
sets that the assembling is always stationary (even in instationary case)
void set_subsets (const std::string &subsets)
sets subset(s) by name list, divided by ','
void set_subsets (const std::vector< std::string > &subsets)
sets subset(s) by name list, divided by ','
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
sets if assembling should be time-dependent and the local time series
void set_time_independent ()
sets that the assembling is time independent
void set_time_point (const size_t timePoint)
sets the current time point
TDomain::subset_handler_type & subset_handler ()
returns the subset handler
const TDomain::subset_handler_type & subset_handler () const
returns the subset handler
const std::vector< std::string > & symb_fcts () const
returns the symbolic functions
const std::vector< std::string > & symb_subsets () const
returns the symbolic subsets
number time () const
returns currently set timepoint
size_t time_point () const
returns the currently considered time point of the time-disc scheme
virtual int type () const
returns the type of elem disc
virtual bool use_hanging () const
returns if discretization acts on hanging nodes if present
virtual ~IElemDiscBase ()
Virtual destructor.
const std::vector< number > & mass_scales () const
const std::vector< number > & stiff_scales () const
number mass_scale (const size_t timePoint) const
number stiff_scale (const size_t timePoint) const
number mass_scale () const
number stiff_scale () const
Public Member Functions inherited from ug::IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
check, if all inputs have been set
virtual void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual compute the error estimator (stiffness part) contribution for one element
virtual void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual compute the error estimator (mass part) contribution for one element
virtual void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual compute the error estimator (rhs part) contribution for one element
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_err_est_elem_loop ()
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
returns the pointer to the error estimator data object (or NULL)
bool err_est_enabled () const
find out whether or not a posteriori error estimation is to be performed for this disc
virtual void fsh_err_est_elem_loop ()
virtual postprocesses the loop over all elements of one type in the computation of the error estimator
IElemEstimatorFuncs ()
constructor
virtual void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual prepares the loop over all elements of one type for the computation of the error estimator
virtual void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
virtual prepares the loop over all elements of one type for the computation of the error estimator
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
sets the pointer to an error estimator data object (or NULL)
void set_roid (ReferenceObjectID id, int discType)
sets the geometric object type
virtual ~IElemEstimatorFuncs ()
Virtual destructor.
Static Public Attributes
static const int dim = TDomain::dim
Static Public Attributes inherited from ug::IElemDiscBase< TDomain >
static const int dim = TDomain::dim
World dimension.
Static Public Attributes inherited from ug::IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
World dimension.
Protected Member Functions
void clear_add_fct ()
sets all assemble functions to NULL (for all ReferenceObjectID's)
void clear_add_fct (ReferenceObjectID id)
sets all assemble functions to NULL for a given ReferenceObjectID
Protected Member Functions inherited from ug::IElemDiscBase< TDomain >
virtual void approximation_space_changed ()
callback invoked, when approximation space is changed
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
sets current function pattern
void update_function_index_mapping ()
updates the function index mapping
Protected Member Functions inherited from ug::IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
sets all assemble functions to NULL (for all ReferenceObjectID's)
void clear_add_fct (ReferenceObjectID id)
sets all assemble functions to NULL for a given ReferenceObjectID
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
sets all assemble functions to the corresponding virtual ones
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
Friends
class IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
Additional Inherited Members
Protected Attributes inherited from ug::IElemDiscBase< TDomain >
bool m_bStationaryForced
flag if stationary assembling is to be used even in instationary assembling
FunctionGroup m_fctGrp
current function group
FunctionIndexMapping m_fctIndexMap
current function index mapping
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
list of local vectors for all solutions of the time series
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
Approximation Space.
ConstSmartPtr< FunctionPattern > m_spFctPattern
current function pattern
size_t m_timePoint
time point
std::vector< std::string > m_vFct
vector holding name of all symbolic functions
std::vector< IDataImport< dim > * > m_vIImport
data imports
std::vector< std::string > m_vSubset
vector holding name of all symbolic subsets
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
Protected Attributes inherited from ug::IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
current Geometric Object
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
error estimation object associated to the element discretization
Member Typedef Documentation
domain_type
template<typename TDomain > typedef TDomain ug::IElemError< TDomain >::domain_type
estimator_base_type
template<typename TDomain > typedef IElemEstimatorFuncs<IElemDisc<TDomain>, TDomain> ug::IElemError< TDomain >::estimator_base_type
Constructor & Destructor Documentation
IElemError() [1/2]
template<typename TDomain > ug::IElemError< TDomain >::IElemError (const char * functions, const char * subsets) inline
IElemError() [2/2]
template<typename TDomain > ug::IElemError< TDomain >::IElemError (const std::vector< std::string > & vFct, const std::vector< std::string > & vSubset) inline
Member Function Documentation
clear_add_fct() [1/2]
template<typename TDomain > void ug::IElemError< TDomain >::clear_add_fct () inline protected
sets all assemble functions to NULL (for all ReferenceObjectID's)
References ug::IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::clear_add_fct().
Referenced by ug::IElemDisc< TDomain >::clear_add_fct().
clear_add_fct() [2/2]
template<typename TDomain > void ug::IElemError< TDomain >::clear_add_fct (ReferenceObjectID id) inline protected
sets all assemble functions to NULL for a given ReferenceObjectID
References ug::IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::clear_add_fct().
Friends And Related Function Documentation
IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
template<typename TDomain > friend class IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > friend
Member Data Documentation
dim
template<typename TDomain > const int ug::IElemError< TDomain >::dim = TDomain::dim static
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/elem_disc/elem_disc_interface.h