ug4: ug::LagrangeP1< TRefElem > Class Template Reference
ug::LagrangeP1< TRefElem > Class Template Reference
Lagrange shape functions of first order.
#include <lagrangep1.h>
Public Types
typedef base_type::grad_type grad_type
Gradient type.
typedef TRefElem reference_element_type
Reference Element type.
typedef base_type::shape_type shape_type
Shape type.
Public Types inherited from ug::BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >
typedef MathVector< TDim > grad_type
Gradient type.
typedef LagrangeP1< TRefElem > ImplType
type of implementation
typedef number shape_type
Shape type.
Public Member Functions
bool continuous () const
returns if space constructs continuous functions
void grad (grad_type &value, size_t i, const MathVector< dim > &x) const
evaluates the gradient of the shape function
LagrangeP1 ()
constructor
size_t num_sh () const
bool position (size_t i, MathVector< dim > &pos) const
local position of DoF i
shape_type shape (size_t i, const MathVector< dim > &x) const
evaluates the shape function
Public Member Functions inherited from ug::LagrangeLDS< TRefElem >
bool exact_position_available () const
returns if the local dof position are exact
LagrangeLDS (size_t order=1)
constructor
const LocalDoF & local_dof (size_t dof) const
returns the dof storage
size_t num_dof () const
returns the total number of DoFs on the finite element
size_t num_dof (ReferenceObjectID roid) const
returns the number of DoFs on a sub-geometric object type
ReferenceObjectID roid () const
returns the type of reference element
void set_order (size_t order)
sets the order
Public Member Functions inherited from ug::LocalDoFSet
int dim () const
returns the reference dimension
size_t num_dof (int d, size_t id) const
returns the number of DoFs on a sub-geometric object of dim and id
bool operator!= (const LocalDoFSet &v) const
inequality check
bool operator== (const LocalDoFSet &v) const
equality check
virtual ~LocalDoFSet ()
virtual destructor
size_t num_dof () const
Public Member Functions inherited from ug::BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >
void grad (grad_type &g, size_t i, const MathVector< dim > &x) const
evaluates the gradient of the shape function
void grads (grad_type *vGrad, const MathVector< dim > &x) const
returns all gradients evaluated at a point
void grads (std::vector< grad_type > &vGrad, const MathVector< dim > &x) const
returns all gradients evaluated at a point
void grads (std::vector< std::vector< grad_type > > &vvGrad, const std::vector< MathVector< dim > > &vLocPos) const
returns all gradients evaluated at a point
shape_type shape (size_t i, const MathVector< dim > &x) const
evaluates the shape function
void shape (shape_type &sh, size_t i, const MathVector< dim > &x) const
evaluates the shape function
void shapes (shape_type *vShape, const MathVector< dim > &x) const
returns all shape functions evaluated at a point
void shapes (std::vector< shape_type > &vShape, const MathVector< dim > &x) const
returns all shape functions evaluated at a point
void shapes (std::vector< std::vector< shape_type > > &vvShape, const std::vector< MathVector< dim > > &vLocPos) const
returns all shape functions evaluated at a point
Static Public Attributes
static const int dim = TRefElem::dim
Dimension, where shape functions are defined.
static const size_t nsh = TRefElem::numCorners
Number of shape functions.
static const size_t order = 1
Order of Shape functions.
Static Public Attributes inherited from ug::BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >
static const int dim
dimension of reference element
Private Types
typedef BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim > base_type
base class
Additional Inherited Members
Protected Member Functions inherited from ug::BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >
ImplType & getImpl ()
access to implementation
const ImplType & getImpl () const
const access to implementation
Protected Attributes inherited from ug::LagrangeLDS< TRefElem >
std::vector< LocalDoF > m_vLocalDoF
association to geom obj
size_t p
order
Detailed Description
template<typename TRefElem>
class ug::LagrangeP1< TRefElem >
Lagrange shape functions of first order.
This class provides Lagrangian Shape Functions of order 1 for a Reference Element.
Template Parameters
TRefElem Reference Element Type
Member Typedef Documentation
template<typename TRefElem> typedef BaseLSFS<LagrangeP1<TRefElem>, TRefElem::dim> ug::LagrangeP1< TRefElem >::base_type private
base class
template<typename TRefElem> typedef base_type::grad_type ug::LagrangeP1< TRefElem >::grad_type
Gradient type.
template<typename TRefElem> typedef TRefElem ug::LagrangeP1< TRefElem >::reference_element_type
Reference Element type.
template<typename TRefElem> typedef base_type::shape_type ug::LagrangeP1< TRefElem >::shape_type
Shape type.
Constructor & Destructor Documentation
template<typename TRefElem> ug::LagrangeP1< TRefElem >::LagrangeP1 () inline
constructor
Member Function Documentation
template<typename TRefElem> bool ug::LagrangeP1< TRefElem >::continuous () const inline
returns if space constructs continuous functions
template<typename TRefElem> void ug::LagrangeP1< TRefElem >::grad (grad_type & value, size_t i, const MathVector< dim > & x) const
evaluates the gradient of the shape function
This function returns the gradient of Shape Function i at an element-local evaluation point.
Parameters
[in] i number of DoF
[in] x Position on reference element (evaluation point)
Returns
gradient at point
Referenced by ug::LagrangeP1< TRefElem >::num_sh().
template<typename TRefElem> size_t ug::LagrangeP1< TRefElem >::num_sh () const inline virtual
returns the total number of dofs on the finite element
Reimplemented from ug::LocalDoFSet.
References ug::LagrangeP1< TRefElem >::grad(), ug::LagrangeP1< TRefElem >::nsh, ug::LagrangeP1< TRefElem >::position(), and ug::LagrangeP1< TRefElem >::shape().
Referenced by ug::FV1InnerBoundaryElemDisc< TDomain >::prep_err_est_elem(), and ug::FV1InnerBoundaryElemDisc< TDomain >::prep_err_est_elem_loop().
template<typename TRefElem> bool ug::LagrangeP1< TRefElem >::position (size_t i, MathVector< dim > & pos) const
local position of DoF i
This function returns the local position of a DoF if possible.
Parameters
[in] i number of DoF
[out] pos Position of DoF
Return values
true if position exists
false if no meaningful position available
Referenced by ug::LagrangeP1< TRefElem >::num_sh().
template<typename TRefElem> shape_type ug::LagrangeP1< TRefElem >::shape (size_t i, const MathVector< dim > & x) const
evaluates the shape function
This function returns the value of Shape Function i at an element-local evaluation point.
Parameters
[in] i number of DoF
[in] x Position on reference element (evaluation point)
Returns
shape function value at point
Referenced by ug::LagrangeP1< TRefElem >::num_sh().
Member Data Documentation
template<typename TRefElem> const int ug::LagrangeP1< TRefElem >::dim = TRefElem::dim static
Dimension, where shape functions are defined.
template<typename TRefElem> const size_t ug::LagrangeP1< TRefElem >::nsh = TRefElem::numCorners static
Number of shape functions.
Referenced by ug::LagrangeP1< TRefElem >::num_sh().
template<typename TRefElem> const size_t ug::LagrangeP1< TRefElem >::order = 1 static
Order of Shape functions.
The documentation for this class was generated from the following file:
ugbase/lib_disc/local_finite_element/lagrange/lagrangep1.h