ug4: ug::IsNotMarked Class Reference
ug::IsNotMarked Class Reference
lib_grid » element_callbacks
Element callback that returns true, if an element is not marked.
#include <basic_callbacks.h>
Public Member Functions
IsNotMarked (const Grid &grid)
bool operator() (Edge *e) const
bool operator() (Face *f) const
bool operator() (Vertex *v) const
bool operator() (Volume *v) const
Public Member Functions inherited from ug::ElementCallback
ElementCallback ()
virtual ~ElementCallback ()
Private Member Functions
template<class TElem >
bool callback (TElem *e) const
Private Attributes
const Grid & m_grid
Detailed Description
Element callback that returns true, if an element is not marked.
Constructor & Destructor Documentation
IsNotMarked()
ug::IsNotMarked::IsNotMarked (const Grid & grid) inline
Member Function Documentation
callback()
template<class TElem > bool ug::IsNotMarked::callback (TElem * e) const inline private
References ug::Grid::is_marked(), and m_grid.
Referenced by operator()().
operator()() [1/4]
bool ug::IsNotMarked::operator() (Edge * e) const inline virtual
Implements ug::ElementCallback.
References callback().
operator()() [2/4]
bool ug::IsNotMarked::operator() (Face * f) const inline virtual
Implements ug::ElementCallback.
References callback().
operator()() [3/4]
bool ug::IsNotMarked::operator() (Vertex * v) const inline virtual
Implements ug::ElementCallback.
References callback().
operator()() [4/4]
bool ug::IsNotMarked::operator() (Volume * v) const inline virtual
Implements ug::ElementCallback.
References callback().
Member Data Documentation
m_grid
const Grid& ug::IsNotMarked::m_grid private
Referenced by callback().
The documentation for this class was generated from the following file:
ugbase/lib_grid/callbacks/basic_callbacks.h