ug4: ug::DebugWritingObject< TAlgebra > Class Template Reference
ug::DebugWritingObject< TAlgebra > Class Template Reference
#include <debug_writer.h>
Public Types
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
returns true if the debug writer is set
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
void enter_debug_writer_section (const char *secDir)
enters a debugging section
void enter_debug_writer_section (std::string secDir)
enters a debugging section
void leave_debug_writer_section ()
leaves a debugging section
void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
void write_debug (const matrix_type &mat, std::string name)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::DebugWritingObject< TAlgebra >::algebra_type
type of algebra
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::DebugWritingObject< TAlgebra >::matrix_type
type of matrix
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::DebugWritingObject< TAlgebra >::vector_type
type of vector
Constructor & Destructor Documentation
DebugWritingObject() [1/3]
template<typename TAlgebra > ug::DebugWritingObject< TAlgebra >::DebugWritingObject () inline
DebugWritingObject() [2/3]
template<typename TAlgebra > ug::DebugWritingObject< TAlgebra >::DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter) inline
DebugWritingObject() [3/3]
template<typename TAlgebra > ug::DebugWritingObject< TAlgebra >::DebugWritingObject (const DebugWritingObject< algebra_type > & parent) inline
clone constructor
~DebugWritingObject()
template<typename TAlgebra > virtual ug::DebugWritingObject< TAlgebra >::~DebugWritingObject () inline virtual
virtual destructor
Member Function Documentation
debug_writer() [1/2]
template<typename TAlgebra > SmartPtr<IDebugWriter<algebra_type> > ug::DebugWritingObject< TAlgebra >::debug_writer () inline
returns the debug writer
References ug::DebugWritingObject< TAlgebra >::m_spDebugWriter.
Referenced by ug::PILUTPreconditioner< TAlgebra >::clone(), ug::Vanka< TAlgebra >::clone(), ug::DiagVanka< TAlgebra >::clone(), ug::ElementGaussSeidel< TDomain, TAlgebra >::clone(), ug::SequentialSubspaceCorrection< TDomain, TAlgebra >::clone(), ug::LineGaussSeidel< TDomain, TAlgebra >::clone(), ug::LineVanka< TDomain, TAlgebra >::clone(), ug::UzawaBase< TDomain, TAlgebra >::init_in_first_step(), ug::ILU< TAlgebra >::preprocess(), ug::FETISolver< TAlgebra >::write_debug(), and ug::ILU< TAlgebra >::write_overlap_debug().
debug_writer() [2/2]
template<typename TAlgebra > ConstSmartPtr<IDebugWriter<algebra_type> > ug::DebugWritingObject< TAlgebra >::debug_writer () const inline
References ug::DebugWritingObject< TAlgebra >::m_spDebugWriter.
debug_writer_valid()
template<typename TAlgebra > bool ug::DebugWritingObject< TAlgebra >::debug_writer_valid () const inline
returns true if the debug writer is set
References ug::DebugWritingObject< TAlgebra >::m_spDebugWriter.
enter_debug_writer_section() [1/2]
template<typename TAlgebra > void ug::DebugWritingObject< TAlgebra >::enter_debug_writer_section (const char * secDir) inline protected
enters a debugging section
References ug::DebugWritingObject< TAlgebra >::m_spDebugWriter.
enter_debug_writer_section() [2/2]
template<typename TAlgebra > void ug::DebugWritingObject< TAlgebra >::enter_debug_writer_section (std::string secDir) inline protected
enters a debugging section
leave_debug_writer_section()
template<typename TAlgebra > void ug::DebugWritingObject< TAlgebra >::leave_debug_writer_section () inline protected
leaves a debugging section
References ug::DebugWritingObject< TAlgebra >::m_spDebugWriter.
set_debug()
template<typename TAlgebra > virtual void ug::DebugWritingObject< TAlgebra >::set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter) inline virtual
set debug writer
Reimplemented in ug::UzawaBase< TDomain, TAlgebra >, ug::SchurPrecond< TAlgebra >, and ug::FETISolver< TAlgebra >.
References ug::DebugWritingObject< TAlgebra >::m_spDebugWriter, and ug::VectorDebugWritingObject< TVector >::set_debug().
Referenced by ug::FETISolver< TAlgebra >::set_debug(), and ug::SchurPrecond< TAlgebra >::set_debug().
write_debug() [1/2]
template<typename TAlgebra > void ug::DebugWritingObject< TAlgebra >::write_debug (const matrix_type & mat, const char * filename) inline protected
write debug output for a matrix (if debug writer set)
Referenced by ug::ILU< TAlgebra >::preprocess(), ug::ILUTPreconditioner< TAlgebra >::preprocess_mat2(), ug::ILU< TAlgebra >::step(), and ug::ILU< TAlgebra >::write_overlap_debug().
write_debug() [2/2]
template<typename TAlgebra > void ug::DebugWritingObject< TAlgebra >::write_debug (const matrix_type & mat, std::string name) inline protected
write debug output for a matrix (if debug writer set)
References ug::DebugWritingObject< TAlgebra >::m_spDebugWriter, name, PROFILE_FUNC_GROUP, and UG_THROW.
Member Data Documentation
m_spDebugWriter
template<typename TAlgebra > SmartPtr<IDebugWriter<algebra_type> > ug::DebugWritingObject< TAlgebra >::m_spDebugWriter protected
Debug Writer.
Referenced by ug::DebugWritingObject< TAlgebra >::debug_writer(), ug::DebugWritingObject< TAlgebra >::debug_writer_valid(), ug::DebugWritingObject< TAlgebra >::enter_debug_writer_section(), ug::DebugWritingObject< TAlgebra >::leave_debug_writer_section(), ug::DebugWritingObject< TAlgebra >::set_debug(), and ug::DebugWritingObject< TAlgebra >::write_debug().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/debug_writer.h