ug4: ug::Table< T > Class Template Reference
ug::Table< T > Class Template Reference
ugbase » Common » Common Utilities » Common Types
Useful for printing a table to the terminal or into a file.
#include <table.h>
Public Member Functions
void add_cols (size_t num)
void add_rows (size_t num)
void clear ()
const T & get (size_t rowInd, size_t colInd) const
uses operator() to get a value
char get_col_alignment (size_t col) const
char get_col_sep (size_t col) const
char get_row_sep (size_t row) const
size_t num_cols () const
size_t num_rows () const
T & operator() (size_t rowInd, size_t colInd)
Returns a reference to the given entry.
const T & operator() (size_t rowInd, size_t colInd) const
Returns a reference to the given entry.
void set (size_t rowInd, size_t colInd, T value)
uses operator() to set an entry to a value
void set_col_alignment (size_t i_col, const char *c)
void set_col_alignments (std::string s)
void set_col_seperator (size_t i_col, const char *c)
void set_col_seperators (std::string s)
void set_default_col_alignment (const char *c)
void set_default_col_seperator (const char *c)
void set_default_row_seperator (const char *c)
void set_row_seperator (size_t i_row, const char *c)
void set_row_seperators (std::string s)
std::ostream & stream (std::ostream &os) const
Table ()
Table (size_t numRows, size_t numCols)
std::string to_csv (const char *seperator) const
std::string to_latex () const
std::string to_string () const
void transpose ()
~Table ()
Private Types
typedef std::vector< std::vector< T * > > DataVec
Private Attributes
std::vector< char > m_colAlign
std::vector< char > m_colSep
DataVec m_data
char m_defaultColAlignment
char m_defaultColSeperator
char m_defaultRowSeperator
size_t m_numCols
size_t m_numRows
std::vector< char > m_rowSep
Detailed Description
template<class T>
class ug::Table< T >
Useful for printing a table to the terminal or into a file.
This class is for output purposes only. It automatically adds spacings, so that all entries in a column are indeed displayed in the same column. Note that the implementation is not optimized in regards to speed and efficiency. The class thus shouldn't be used in performance critical sections of your code. If it is however used in output related code, the introduced overhead should be fine and probably even negligible.
The class is most commonly used as a string table (Table<std::string>) or as a stringstream table (Table<std::stringstream>). If you want to use it for your own types, you may specialize the template method
template <class T> std::string EntryToString(const Table<T>& table, size_t rowInd, size_t colInd);
The default implementation of EntryToString may already be suited for most cases.
Here's an example on how to use the class:
#include "common/util/table.h"
...
ug::Table<std::stringstream> table;
table(0, 0) << "num rows:";   table(0, 1) << table.num_rows();
table(1, 0) << "num columns:";  table(1, 1) << table.num_cols();
std::cout << table;
And this is what the output looks like:
    num rows:  2
    num columns:  2
*
Note that several typedefs exist: StringTable, StringStreamTable
Todo:
different alignments for different columns / rows / fields
Member Typedef Documentation
template<class T> typedef std::vector<std::vector<T*> > ug::Table< T >::DataVec private
Constructor & Destructor Documentation
template<class T > ug::Table< T >::Table ()
References ug::Table< T >::m_defaultColAlignment, ug::Table< T >::m_defaultColSeperator, and ug::Table< T >::m_defaultRowSeperator.
template<class T > ug::Table< T >::Table (size_t numRows, size_t numCols)
References ug::Table< T >::add_cols(), ug::Table< T >::add_rows(), ug::Table< T >::m_defaultColAlignment, ug::Table< T >::m_defaultColSeperator, and ug::Table< T >::m_defaultRowSeperator.
template<class T > ug::Table< T >::~Table ()
References ug::Table< T >::clear().
Member Function Documentation
template<class T > void ug::Table< T >::add_cols (size_t num)
References ug::Table< T >::m_data, ug::Table< T >::m_numCols, and ug::Table< T >::m_numRows.
Referenced by ug::Table< T >::operator()(), and ug::Table< T >::Table().
template<class T > void ug::Table< T >::add_rows (size_t num)
References ug::Table< T >::m_data, ug::Table< T >::m_numCols, and ug::Table< T >::m_numRows.
Referenced by ug::Table< T >::operator()(), and ug::Table< T >::Table().
template<class T > void ug::Table< T >::clear ()
References ug::Table< T >::m_data, ug::Table< T >::m_numCols, and ug::Table< T >::m_numRows.
Referenced by ug::StringTableStream::clear(), ug::StringTableStream::operator<<(), and ug::Table< T >::~Table().
template<class T> const T& ug::Table< T >::get (size_t rowInd, size_t colInd) const inline
uses operator() to get a value
template<class T> char ug::Table< T >::get_col_alignment (size_t col) const inline
Referenced by ug::Table< T >::stream(), and ug::Table< T >::to_latex().
template<class T> char ug::Table< T >::get_col_sep (size_t col) const inline
Referenced by ug::Table< T >::stream(), and ug::Table< T >::to_latex().
template<class T> char ug::Table< T >::get_row_sep (size_t row) const inline
Referenced by ug::Table< T >::stream(), and ug::Table< T >::to_latex().
template<class T > size_t ug::Table< T >::num_cols () const
References ug::Table< T >::m_numCols.
Referenced by ug::Table< std::stringstream >::get(), ug::Table< T >::operator()(), ug::Table< T >::stream(), ug::Table< T >::to_csv(), and ug::Table< T >::to_latex().
template<class T > size_t ug::Table< T >::num_rows () const
References ug::Table< T >::m_numRows.
Referenced by ug::LoadBalancer::create_quality_record(), ug::Table< std::stringstream >::get(), ug::Table< T >::operator()(), ug::Table< T >::stream(), ug::Table< T >::to_csv(), and ug::Table< T >::to_latex().
template<class T > T & ug::Table< T >::operator() (size_t rowInd, size_t colInd)
Returns a reference to the given entry.
If an entry lies outside of the tables bounds, the table will automatically be resized accordingly.
References ug::Table< T >::add_cols(), ug::Table< T >::add_rows(), ug::Table< T >::m_data, ug::Table< T >::num_cols(), and ug::Table< T >::num_rows().
Referenced by ug::Table< std::stringstream >::get(), and ug::Table< std::stringstream >::set().
template<class T > const T & ug::Table< T >::operator() (size_t rowInd, size_t colInd) const
Returns a reference to the given entry.
References ug::Table< T >::m_data, ug::Table< T >::num_cols(), ug::Table< T >::num_rows(), and UG_COND_THROW.
template<class T> void ug::Table< T >::set (size_t rowInd, size_t colInd, T value) inline
uses operator() to set an entry to a value
template<class T> void ug::Table< T >::set_col_alignment (size_t i_col, const char * c) inline
template<class T> void ug::Table< T >::set_col_alignments (std::string s) inline
template<class T> void ug::Table< T >::set_col_seperator (size_t i_col, const char * c) inline
template<class T> void ug::Table< T >::set_col_seperators (std::string s) inline
template<class T> void ug::Table< T >::set_default_col_alignment (const char * c) inline
template<class T> void ug::Table< T >::set_default_col_seperator (const char * c) inline
template<class T> void ug::Table< T >::set_default_row_seperator (const char * c) inline
template<class T> void ug::Table< T >::set_row_seperator (size_t i_row, const char * c) inline
template<class T> void ug::Table< T >::set_row_seperators (std::string s) inline
template<class T > std::ostream & ug::Table< T >::stream (std::ostream & os) const
References ug::EntryToString(), ug::Table< T >::get_col_alignment(), ug::Table< T >::get_col_sep(), ug::Table< T >::get_row_sep(), ug::Table< T >::num_cols(), ug::Table< T >::num_rows(), and ug::repeat().
Referenced by ug::Table< std::stringstream >::set_col_alignments().
template<typename T > std::string ug::Table< T >::to_csv (const char * seperator) const
References ug::EntryToString(), ug::Table< T >::num_cols(), and ug::Table< T >::num_rows().
Referenced by ug::Table< std::stringstream >::set_col_alignments().
template<typename T > std::string ug::Table< T >::to_latex () const
References ug::EntryToString(), ug::Table< T >::get_col_alignment(), ug::Table< T >::get_col_sep(), ug::Table< T >::get_row_sep(), ug::Table< T >::num_cols(), and ug::Table< T >::num_rows().
Referenced by ug::Table< std::stringstream >::set_col_alignments().
template<class T > std::string ug::Table< T >::to_string () const
Referenced by ug::Table< std::stringstream >::set_col_alignments(), ug::ProcessHierarchy::to_string(), ug::DomainInfo::to_string(), and ug::StringTableStream::to_string().
template<class T> void ug::Table< T >::transpose () inline
Member Data Documentation
template<class T> std::vector<char> ug::Table< T >::m_colAlign private
Referenced by ug::Table< std::stringstream >::get_col_alignment(), ug::Table< std::stringstream >::set_col_alignment(), and ug::Table< std::stringstream >::set_col_alignments().
template<class T> std::vector<char> ug::Table< T >::m_colSep private
Referenced by ug::Table< std::stringstream >::get_col_sep(), ug::Table< std::stringstream >::set_col_seperator(), and ug::Table< std::stringstream >::set_col_seperators().
template<class T> DataVec ug::Table< T >::m_data private
Referenced by ug::Table< T >::add_cols(), ug::Table< T >::add_rows(), ug::Table< T >::clear(), ug::Table< T >::operator()(), and ug::Table< std::stringstream >::transpose().
template<class T> char ug::Table< T >::m_defaultColAlignment private
Referenced by ug::Table< std::stringstream >::get_col_alignment(), ug::Table< std::stringstream >::set_default_col_alignment(), and ug::Table< T >::Table().
template<class T> char ug::Table< T >::m_defaultColSeperator private
Referenced by ug::Table< std::stringstream >::get_col_sep(), ug::Table< std::stringstream >::set_default_col_seperator(), and ug::Table< T >::Table().
template<class T> char ug::Table< T >::m_defaultRowSeperator private
Referenced by ug::Table< std::stringstream >::get_row_sep(), ug::Table< std::stringstream >::set_default_row_seperator(), and ug::Table< T >::Table().
template<class T> size_t ug::Table< T >::m_numCols private
Referenced by ug::Table< T >::add_cols(), ug::Table< T >::add_rows(), ug::Table< T >::clear(), ug::Table< T >::num_cols(), and ug::Table< std::stringstream >::transpose().
template<class T> size_t ug::Table< T >::m_numRows private
Referenced by ug::Table< T >::add_cols(), ug::Table< T >::add_rows(), ug::Table< T >::clear(), ug::Table< T >::num_rows(), and ug::Table< std::stringstream >::transpose().
template<class T> std::vector<char> ug::Table< T >::m_rowSep private
Referenced by ug::Table< std::stringstream >::get_row_sep(), ug::Table< std::stringstream >::set_row_seperator(), and ug::Table< std::stringstream >::set_row_seperators().
The documentation for this class was generated from the following files:
ugbase/common/util/table.h
ugbase/common/util/table_impl.hpp