ug4: ug::L2QuotientSpace< TGridFunction > Class Template Reference
ug::L2QuotientSpace< TGridFunction > Class Template Reference
#include <metric_spaces.h>
Public Types
typedef IComponentSpace< TGridFunction > base_type
typedef L2DistIntegrand< TGridFunction >::weight_type weight_type
typedef IObjectWithWeights< weight_type > weighted_obj_type
Public Types inherited from ug::IComponentSpace< TGridFunction >
typedef IGridFunctionSpace< TGridFunction > base_type
Public Types inherited from ug::IGridFunctionSpace< TGridFunction >
typedef TGridFunction grid_function_type
typedef TGridFunction::vector_type vector_type
Public Types inherited from ug::IObjectWithWeights< L2DistIntegrand< TGridFunction >::weight_type >
typedef L2DistIntegrand< TGridFunction >::weight_type weight_type
Public Member Functions
double distance2 (TGridFunction &uFine, TGridFunction &uCoarse)
distance (for grid functions)
ConstSmartPtr< weight_type > get_weight ()
L2QuotientSpace (const char *fctNames)
CTOR.
L2QuotientSpace (const char *fctNames, int order)
L2QuotientSpace (const char *fctNames, int order, ConstSmartPtr< weight_type > spWeight, const char *ssNames=0)
L2QuotientSpace (const char *fctNames, int order, double weight, const char *ssNames=0)
double norm2 (TGridFunction &u)
norm (for grid functions)
void set_weight (ConstSmartPtr< weight_type > spWeight)
for weighted norms
~L2QuotientSpace ()
DTOR.
Public Member Functions inherited from ug::IComponentSpace< TGridFunction >
virtual std::string config_string () const
print config string
virtual double distance (TGridFunction &uFine, TGridFunction &uCoarse)
distance (for grid functions)
IComponentSpace (const char *fctNames)
IComponentSpace (const char *fctNames, const char *ssNames, int order)
IComponentSpace (const char *fctNames, int order)
virtual double norm (TGridFunction &uFine)
norm (for grid functions)
virtual ~IComponentSpace ()
Public Member Functions inherited from ug::IGridFunctionSpace< TGridFunction >
virtual double distance (vector_type &x, vector_type &y)
OVERRIDE distance (for vectors)
virtual double norm (vector_type &x)
OVERRIDE norm (for vectors)
virtual double scaling () const
virtual ~IGridFunctionSpace ()
DTOR.
Public Member Functions inherited from ug::IBanachSpace< TGridFunction::vector_type >
virtual ~IBanachSpace ()
Public Member Functions inherited from ug::IObjectWithWeights< L2DistIntegrand< TGridFunction >::weight_type >
ConstSmartPtr< weight_type > get_weight ()
IObjectWithWeights ()
IObjectWithWeights (ConstSmartPtr< weight_type > spW)
void set_weight (ConstSmartPtr< weight_type > spWeight)
for weighted norms
Public Attributes
ConstSmartPtr< weight_type > m_spWeight
Additional Inherited Members
Static Public Attributes inherited from ug::IComponentSpace< TGridFunction >
static const int dim =TGridFunction::dim
Protected Attributes inherited from ug::IComponentSpace< TGridFunction >
std::string m_fctNames
int m_quadorder
const char * m_ssNames
Protected Attributes inherited from ug::IObjectWithWeights< L2DistIntegrand< TGridFunction >::weight_type >
ConstSmartPtr< weight_type > m_spWeight
Detailed Description
template<typename TGridFunction>
class ug::L2QuotientSpace< TGridFunction >
Evaluates difference between two grid functions in L2 norm
Member Typedef Documentation
base_type
template<typename TGridFunction > typedef IComponentSpace<TGridFunction> ug::L2QuotientSpace< TGridFunction >::base_type
weight_type
template<typename TGridFunction > typedef L2DistIntegrand<TGridFunction>::weight_type ug::L2QuotientSpace< TGridFunction >::weight_type
weighted_obj_type
template<typename TGridFunction > typedef IObjectWithWeights<weight_type> ug::L2QuotientSpace< TGridFunction >::weighted_obj_type
Constructor & Destructor Documentation
L2QuotientSpace() [1/4]
template<typename TGridFunction > ug::L2QuotientSpace< TGridFunction >::L2QuotientSpace (const char * fctNames) inline
CTOR.
L2QuotientSpace() [2/4]
template<typename TGridFunction > ug::L2QuotientSpace< TGridFunction >::L2QuotientSpace (const char * fctNames, int order) inline
L2QuotientSpace() [3/4]
template<typename TGridFunction > ug::L2QuotientSpace< TGridFunction >::L2QuotientSpace (const char * fctNames, int order, double weight, const char * ssNames = 0) inline
L2QuotientSpace() [4/4]
template<typename TGridFunction > ug::L2QuotientSpace< TGridFunction >::L2QuotientSpace (const char * fctNames, int order, ConstSmartPtr< weight_type > spWeight, const char * ssNames = 0) inline
~L2QuotientSpace()
template<typename TGridFunction > ug::L2QuotientSpace< TGridFunction >::~L2QuotientSpace () inline
DTOR.
Member Function Documentation
distance2()
template<typename TGridFunction > double ug::L2QuotientSpace< TGridFunction >::distance2 (TGridFunction & uFine, TGridFunction & uCoarse) inline virtual
distance (for grid functions)
Implements ug::IComponentSpace< TGridFunction >.
References ug::Integral(), ug::L2Distance2(), ug::IComponentSpace< TGridFunction >::m_fctNames, ug::IComponentSpace< TGridFunction >::m_quadorder, ug::IObjectWithWeights< W >::m_spWeight, ug::IComponentSpace< TGridFunction >::m_ssNames, and make_sp().
get_weight()
template<typename TGridFunction > ConstSmartPtr<weight_type> ug::IObjectWithWeights< W >::get_weight inline
norm2()
template<typename TGridFunction > double ug::L2QuotientSpace< TGridFunction >::norm2 (TGridFunction & u) inline virtual
norm (for grid functions)
Implements ug::IComponentSpace< TGridFunction >.
References ug::Integral(), ug::L2Error(), ug::IComponentSpace< TGridFunction >::m_fctNames, ug::IComponentSpace< TGridFunction >::m_quadorder, ug::IComponentSpace< TGridFunction >::m_ssNames, and make_sp().
set_weight()
template<typename TGridFunction > void ug::IObjectWithWeights< W >::set_weight inline
for weighted norms
Member Data Documentation
m_spWeight
template<typename TGridFunction > ConstSmartPtr<weight_type> ug::IObjectWithWeights< W >::m_spWeight
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/metric_spaces.h