ug4: ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward > Class Template Reference
ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward > Class Template Reference
#include <block_gauss_seidel.h>
Public Types
typedef TAlgebra algebra_type
typedef IBlockJacobiPreconditioner< TAlgebra > base_type
Base type.
typedef matrix_type::const_row_iterator const_row_iterator
typedef IPreconditioner< TAlgebra >::matrix_operator_type matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
typedef matrix_type::value_type smallmat_type
typedef vector_type::value_type smallvec_type
typedef SparseBlockGaussSeidel2< TAlgebra, backward, forward > this_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::IBlockJacobiPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
typedef IPreconditioner< TAlgebra >::matrix_operator_type matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual SmartPtr< ILinearIterator< vector_type > > clone ()
clone
void set_depth (size_t d)
SparseBlockGaussSeidel2 ()
SparseBlockGaussSeidel2 (const this_type &parent)
SparseBlockGaussSeidel2 (int depth)
Public Member Functions inherited from ug::IBlockJacobiPreconditioner< TAlgebra >
IBlockJacobiPreconditioner ()
IBlockJacobiPreconditioner (const IBlockJacobiPreconditioner &parent)
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
returns true if the debug writer is set
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Public Attributes
std::map< size_t, SmartPtr< CPUAlgebra::matrix_type > > Aloc
std::vector< std::vector< size_t > > indices
size_t m_depth
std::map< size_t, SmartPtr< ILUTPreconditioner< CPUAlgebra > > > m_ilut
Protected Types
typedef matrix_type::value_type block_type
typedef matrix_type::const_row_iterator matrix_const_row_iterator
typedef matrix_type::row_iterator matrix_row_iterator
Protected Member Functions
virtual bool block_preprocess (matrix_type &A)
virtual bool block_step (matrix_type &A, vector_type &c, const vector_type &d)
virtual std::string config_string () const
virtual const char * name () const
returns the name of iterator
virtual bool postprocess ()
cleans the operator
virtual bool supports_parallel () const
returns if parallel solving is supported
Protected Member Functions inherited from ug::IBlockJacobiPreconditioner< TAlgebra >
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
initializes the preconditioner
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
computes a new correction c = B*d
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
void enter_debug_writer_section (const char *secDir)
enters a debugging section
void enter_debug_writer_section (std::string secDir)
enters a debugging section
void leave_debug_writer_section ()
leaves a debugging section
void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
void write_debug (const matrix_type &mat, std::string name)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Additional Inherited Members
Protected Attributes inherited from ug::IBlockJacobiPreconditioner< TAlgebra >
matrix_type A
SmartPtr< vector_type > m_spDtmp
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Detailed Description
template<typename TAlgebra, bool backward, bool forward>
class ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >
SparseBlockGaussSeidel experimental version a) can use bigger stencils since it uses SparseLU for solving blocks b) tries to use some overlapping blocks (BlockGaussSeidel always uses N blocks)
Member Typedef Documentation
algebra_type
template<typename TAlgebra , bool backward, bool forward> typedef TAlgebra ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::algebra_type
base_type
template<typename TAlgebra , bool backward, bool forward> typedef IBlockJacobiPreconditioner<TAlgebra> ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::base_type
Base type.
block_type
template<typename TAlgebra , bool backward, bool forward> typedef matrix_type::value_type ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::block_type protected
const_row_iterator
template<typename TAlgebra , bool backward, bool forward> typedef matrix_type::const_row_iterator ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::const_row_iterator
matrix_const_row_iterator
template<typename TAlgebra , bool backward, bool forward> typedef matrix_type::const_row_iterator ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::matrix_const_row_iterator protected
matrix_operator_type
template<typename TAlgebra , bool backward, bool forward> typedef IPreconditioner<TAlgebra>::matrix_operator_type ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::matrix_operator_type
Matrix Operator type.
matrix_row_iterator
template<typename TAlgebra , bool backward, bool forward> typedef matrix_type::row_iterator ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::matrix_row_iterator protected
matrix_type
template<typename TAlgebra , bool backward, bool forward> typedef TAlgebra::matrix_type ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::matrix_type
smallmat_type
template<typename TAlgebra , bool backward, bool forward> typedef matrix_type::value_type ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::smallmat_type
smallvec_type
template<typename TAlgebra , bool backward, bool forward> typedef vector_type::value_type ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::smallvec_type
this_type
template<typename TAlgebra , bool backward, bool forward> typedef SparseBlockGaussSeidel2<TAlgebra, backward, forward> ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::this_type
vector_type
template<typename TAlgebra , bool backward, bool forward> typedef TAlgebra::vector_type ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::vector_type
Constructor & Destructor Documentation
SparseBlockGaussSeidel2() [1/3]
template<typename TAlgebra , bool backward, bool forward> ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::SparseBlockGaussSeidel2 () inline
References ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::m_depth.
SparseBlockGaussSeidel2() [2/3]
template<typename TAlgebra , bool backward, bool forward> ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::SparseBlockGaussSeidel2 (int depth) inline
References ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::m_depth.
SparseBlockGaussSeidel2() [3/3]
template<typename TAlgebra , bool backward, bool forward> ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::SparseBlockGaussSeidel2 (const this_type & parent) inline
References ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::m_depth.
Member Function Documentation
block_preprocess()
template<typename TAlgebra , bool backward, bool forward> virtual bool ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::block_preprocess (matrix_type & A) inline protected virtual
Implements ug::IBlockJacobiPreconditioner< TAlgebra >.
References ug::IBlockJacobiPreconditioner< TAlgebra >::A, ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::Aloc, ug::cgraph::begin_row(), ug::CreateStrongConnectionGraphForSystems(), ug::cgraph::end_row(), ug::GetSliceSparse(), ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::indices, ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::m_ilut, make_sp(), num_rows(), PRINT_VECTOR, PROGRESS_FINISH, PROGRESS_START, ug::cgraph::resize(), ug::cgraph::set_connection(), ug::cgraph::size(), UG_COND_THROW, and UG_LOG.
block_step()
template<typename TAlgebra , bool backward, bool forward> virtual bool ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::block_step (matrix_type & A, vector_type & c, const vector_type & d) inline protected virtual
Implements ug::IBlockJacobiPreconditioner< TAlgebra >.
References ug::IBlockJacobiPreconditioner< TAlgebra >::A, ug::GetBlockGSCorrectionILUT(), ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::indices, ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::m_ilut, PROGRESS_FINISH, PROGRESS_START, PROGRESS_UPDATE, and ug::PST_CONSISTENT.
clone()
template<typename TAlgebra , bool backward, bool forward> virtual SmartPtr<ILinearIterator<vector_type> > ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::clone () inline virtual
clone
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References make_sp().
config_string()
template<typename TAlgebra , bool backward, bool forward> virtual std::string ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::config_string () const inline protected virtual
Reimplemented from ug::ILinearIterator< TAlgebra::vector_type >.
References ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::m_depth.
name()
template<typename TAlgebra , bool backward, bool forward> virtual const char* ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::name () const inline protected virtual
returns the name of iterator
This method returns the name of the iterator operator. This function is typically needed, when the iterator operator is used inside of another operator and some debug output should be printed
Returns
const char* name of inverse operator
Implements ug::IPreconditioner< TAlgebra >.
postprocess()
template<typename TAlgebra , bool backward, bool forward> virtual bool ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::postprocess () inline protected virtual
cleans the operator
Reimplemented from ug::IBlockJacobiPreconditioner< TAlgebra >.
set_depth()
template<typename TAlgebra , bool backward, bool forward> void ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::set_depth (size_t d) inline
References ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::m_depth.
supports_parallel()
template<typename TAlgebra , bool backward, bool forward> virtual bool ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::supports_parallel () const inline protected virtual
returns if parallel solving is supported
Reimplemented from ug::IBlockJacobiPreconditioner< TAlgebra >.
Member Data Documentation
Aloc
template<typename TAlgebra , bool backward, bool forward> std::map<size_t, SmartPtr<CPUAlgebra::matrix_type> > ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::Aloc
Referenced by ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::block_preprocess().
indices
template<typename TAlgebra , bool backward, bool forward> std::vector<std::vector<size_t> > ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::indices
Referenced by ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::block_preprocess(), and ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::block_step().
m_depth
template<typename TAlgebra , bool backward, bool forward> size_t ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::m_depth
Referenced by ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::config_string(), ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::set_depth(), and ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::SparseBlockGaussSeidel2().
m_ilut
template<typename TAlgebra , bool backward, bool forward> std::map<size_t, SmartPtr<ILUTPreconditioner<CPUAlgebra> > > ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::m_ilut
Referenced by ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::block_preprocess(), and ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::block_step().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/preconditioner/block_gauss_seidel.h