ug4: ug::HangingNodeRefinerBase< TSelector > Class Template Reference
ug::HangingNodeRefinerBase< TSelector > Class Template Reference abstract
lib_grid » algorithms » refinement
Base class for a hanging-node refiner.
#include <hanging_node_refiner_base.h>
Public Types
enum HNodeRefMarks { HNRM_TO_NORMAL = 1 << 5, HNRM_TO_CONSTRAINED = 1 << 6, HNRM_TO_CONSTRAINING = 1 << 7, HNRM_MAX }
typedef TSelector selector_t
Public Member Functions
void add_ref_mark_adjuster (SPIRefMarkAdjuster adjuster)
Add a refmark adjuster, which will be called while marks are adjusted during refinement / coarsening.
virtual void clear_marks ()
clears all marks. Default implementation is empty
virtual void grid_to_be_destroyed (Grid *grid)
HangingNodeRefinerBase (IRefinementCallback *refCallback=NULL)
virtual void mark_neighborhood (size_t numIterations, RefinementMark refMark, bool sideNbrsOnly)
Marks the neighborhood of the current selection.
virtual bool save_marks_to_file (const char *filename)
Writes the associated grid and marks to a file. Pure virtual.
virtual ~HangingNodeRefinerBase ()
void enable_node_dependency_order_1 (bool bEnable)
enables or disables node-dependency-order-1.
bool node_dependency_order_1_enabled ()
enables or disables node-dependency-order-1.
virtual bool mark (Vertex *v, RefinementMark refMark=RM_REFINE)
Marks a element for refinement.
virtual bool mark (Edge *e, RefinementMark refMark=RM_REFINE)
Marks a element for refinement.
virtual bool mark (Face *f, RefinementMark refMark=RM_REFINE)
Marks a element for refinement.
virtual bool mark (Volume *v, RefinementMark refMark=RM_REFINE)
Marks a element for refinement.
virtual RefinementMark get_mark (Vertex *v)
Returns the mark of a given element.
virtual RefinementMark get_mark (Edge *e)
Returns the mark of a given element.
virtual RefinementMark get_mark (Face *f)
Returns the mark of a given element.
virtual RefinementMark get_mark (Volume *v)
Returns the mark of a given element.
Public Member Functions inherited from ug::IRefiner
virtual bool adaptivity_supported () const =0
returns whether the refiner is able to perform adaptive refinement
bool coarsen ()
Performs coarsening on the elements marked RM_COARSEN.
virtual bool coarsening_supported () const =0
returns true, if the refiner supports coarsening.
bool debugging_enabled () const
void enable_debugging (bool enable)
virtual Grid * get_associated_grid ()=0
DEPRECIATED! Use grid(). Has to return the associated grid. Pure virtual.
virtual RefinementMark get_mark (GridObject *o)
returns the mark of the specified geometric object
IRefinementCallback * get_refinement_callback ()
virtual Grid * grid ()=0
Returns the grid associated with the refiner.
IRefiner (IRefinementCallback *refCallback=NULL)
virtual bool mark (GridObject *o, RefinementMark refMark=RM_REFINE)
marks the specified geometric object
template<class TIterator >
void mark (const TIterator &iterBegin, const TIterator &iterEnd, RefinementMark refMark=RM_REFINE)
marks all elements between iterBegin and iterEnd.
void mark_neighborhood (size_t numIterations)
marks the neighborhood of currently marked elements.
size_t num_marked_edges (std::vector< int > &numMarkedEdgesOut)
returns the number of (globally) marked edges on all levels of the hierarchy
size_t num_marked_edges ()
returns the number of (globally) marked edges on all levels of the hierarchy
size_t num_marked_elements (std::vector< int > &numMarkedElemsOut)
returns the number of (globally) marked grid-objects of highest dimension
size_t num_marked_elements ()
returns the number of (globally) marked grid-objects of highest dimension
size_t num_marked_faces (std::vector< int > &numMarkedFacesOut)
returns the number of (globally) marked faces on all levels of the hierarchy
size_t num_marked_faces ()
returns the number of (globally) marked faces on all levels of the hierarchy
size_t num_marked_volumes (std::vector< int > &numMarkedVolsOut)
returns the number of (globally) marked volumes on all levels of the hierarchy
size_t num_marked_volumes ()
returns the number of (globally) marked volumes on all levels of the hierarchy
void refine ()
Performs refinement on the marked elements.
void set_adjusted_marks_debug_filename (const char *filename)
sets a filename to which adjusted marks are saved during refinement / coarsening
void set_refinement_callback (IRefinementCallback *refCallback)
virtual ~IRefiner ()
void adaption_begins ()
notifies all listeners of the associated message-hub, that adaption begins / ends.
void adaption_ends ()
notifies all listeners of the associated message-hub, that adaption begins / ends.
Public Member Functions inherited from ug::GridObserver
virtual void elements_to_be_cleared (Grid *grid)
virtual ~GridObserver ()
virtual void vertex_created (Grid *grid, Vertex *vrt, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void edge_created (Grid *grid, Edge *e, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void face_created (Grid *grid, Face *f, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void volume_created (Grid *grid, Volume *vol, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void vertex_to_be_erased (Grid *grid, Vertex *vrt, Vertex *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void edge_to_be_erased (Grid *grid, Edge *e, Edge *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void face_to_be_erased (Grid *grid, Face *f, Face *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void volume_to_be_erased (Grid *grid, Volume *vol, Volume *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void vertices_to_be_merged (Grid *grid, Vertex *target, Vertex *elem1, Vertex *elem2)
Notified when two elements of the same type are going to be merged.
virtual void edges_to_be_merged (Grid *grid, Edge *target, Edge *elem1, Edge *elem2)
Notified when two elements of the same type are going to be merged.
virtual void faces_to_be_merged (Grid *grid, Face *target, Face *elem1, Face *elem2)
Notified when two elements of the same type are going to be merged.
virtual void volumes_to_be_merged (Grid *grid, Volume *target, Volume *elem1, Volume *elem2)
Notified when two elements of the same type are going to be merged.
Protected Types
typedef TSelector::template traits< Edge >::iterator sel_edge_iter
typedef TSelector::template traits< Face >::iterator sel_face_iter
typedef TSelector::template traits< Volume >::iterator sel_vol_iter
typedef TSelector::template traits< Vertex >::iterator sel_vrt_iter
Protected Member Functions
template<class TElem >
void add_hmark (TElem *elem, HNodeRefMarks mark)
virtual void assign_hnode_marks ()
virtual void collect_objects_for_refine ()
marks unmarked elements that have to be refined due to marked neighbors.
virtual bool continue_collect_objects_for_refine (bool continueRequired)
virtual Vertex * get_center_vertex (Edge *e)=0
Returns the vertex associated with the edge.
virtual Vertex * get_center_vertex (Face *f)=0
Returns the vertex associated with the face.
TSelector & get_refmark_selector ()
returns the selector which is internally used to mark elements.
bool is_marked (Vertex *v)
bool is_marked (Edge *e)
bool is_marked (Face *f)
bool is_marked (Volume *v)
template<class TElem >
bool marked_adaptive (TElem *elem)
template<class TElem >
bool marked_anisotropic (TElem *elem)
template<class TElem >
bool marked_coarsen (TElem *elem)
template<class TElem >
bool marked_copy (TElem *elem)
template<class TElem >
bool marked_refine (TElem *elem)
template<class TElem >
bool marked_regular (TElem *elem)
template<class TElem >
bool marked_to_constrained (TElem *elem)
template<class TElem >
bool marked_to_constraining (TElem *elem)
template<class TElem >
bool marked_to_normal (TElem *elem)
void perform_refinement ()
performs refinement on the marked elements.
virtual void post_refine ()
virtual void pre_refine ()
virtual bool refinement_is_allowed (Vertex *elem)
a callback that allows to deny refinement of special vertices
virtual bool refinement_is_allowed (Edge *elem)
a callback that allows to deny refinement of special edges
virtual bool refinement_is_allowed (Face *elem)
a callback that allows to deny refinement of special faces
virtual bool refinement_is_allowed (Volume *elem)
a callback that allows to deny refinement of special volumes
template<class TElem >
bool remove_coarsen_marks ()
removes coarsen marks from the selection
template<class TElem >
void remove_hmark (TElem *elem, uint mark)
virtual void set_center_vertex (Edge *e, Vertex *v)=0
Associates a vertex with the edge (pure virtual).
virtual void set_center_vertex (Face *f, Vertex *v)=0
Associates a vertex with the face (pure virtual).
void set_grid (typename TSelector::grid_type *grid)
performs registration and deregistration at a grid.
virtual void process_constrained_vertex (ConstrainedVertex *cdv)
called to refine the specified element.
virtual void process_constrained_edge (ConstrainedEdge *cde)
called to refine the specified element.
virtual void process_constraining_edge (ConstrainingEdge *cge)
called to refine the specified element.
virtual void refine_edge_with_normal_vertex (Edge *e, Vertex **newCornerVrts=NULL)
called to refine the specified element.
virtual void refine_edge_with_hanging_vertex (Edge *e, Vertex **newCornerVrts=NULL)
called to refine the specified element.
virtual void process_constrained_face (ConstrainedFace *cdf)
called to refine the specified element.
virtual void process_constraining_face (ConstrainingFace *cgf)
called to refine the specified element.
virtual void refine_face_with_normal_vertex (Face *f, Vertex **newCornerVrts=NULL)
called to refine the specified element.
virtual void refine_face_with_hanging_vertex (Face *f, Vertex **newCornerVrts=NULL)
called to refine the specified element.
virtual void refine_volume_with_normal_vertex (Volume *v, Vertex **newVolumeVrts=NULL)
called to refine the specified element.
Protected Member Functions inherited from ug::IRefiner
virtual void num_marked_edges_local (std::vector< int > &numMarkedEdgesOut)=0
returns the number of locally marked edges on all levels of the hierarchy
virtual void num_marked_faces_local (std::vector< int > &numMarkedFacesOut)=0
returns the number of locally marked faces on all levels of the hierarchy
virtual void num_marked_volumes_local (std::vector< int > &numMarkedVolsOut)=0
returns the number of locally marked volumes on all levels of the hierarchy
virtual bool perform_coarsening ()
Called by coarsen(). Derived classes sould implement their coarsen algorithm here.
void set_message_hub (SPMessageHub msgHub)
sets the message hub.
Protected Attributes
std::vector< SPIRefMarkAdjuster > m_refMarkAdjusters
TSelector m_selMarkedElements
Protected Attributes inherited from ug::IRefiner
bool m_adaptionIsActive
std::string m_adjustedMarksDebugFilename
bool m_debuggingEnabled
SPMessageHub m_messageHub
int m_msgIdAdaption
IRefinementCallback * m_refCallback
Private Member Functions
HangingNodeRefinerBase (const HangingNodeRefinerBase &)
private copy constructor to avoid copy construction
Private Attributes
bool m_adjustingRefMarks
true during collect_objects_for_refine
std::vector< Edge * > m_newlyMarkedRefEdges
std::vector< Face * > m_newlyMarkedRefFaces
std::vector< Volume * > m_newlyMarkedRefVols
std::vector< Vertex * > m_newlyMarkedRefVrts
bool m_nodeDependencyOrder1
Grid * m_pGrid
Detailed Description
template<class TSelector>
class ug::HangingNodeRefinerBase< TSelector >
Base class for a hanging-node refiner.
A hanging node refiner allows to adaptively refine grid elements by inserting hanging nodes at points where T-junctions would occur (ug::HangingVertex). If further refinement is performed, the refiner automatically takes care to adjust the refined area, so that no more than 1 hanging vertex resides on any edge.
Each edge on which a hanging node lies is replaced by a ug::ConstrainingEdge. Child-edges of a constraining edge have the type ug::ConstrainedEdge.
If volumes exist, the refiner may also create elements of type ug::ConstrainingTriangle or ug::ConstrainingQuadrilateral, as well as ug::ConstrainedTriangle and ug::ConstrainedQuadrilateral.
Use the mark methods to mark elements which shall be refined. A call to refine will then perform the refinement and clear all marks.
Please note: If you're using a hanging node refiner, you have to be careful to not destroy the connections between hanging-vertices, and constrained / constraining objects.
Specializations of this class exist to support hanging node refinement on flat and on hierarchical grids.
Note that you may set a refinement callback, which will be responsible to calculate new positions of newly created vertices. By default a linear refinement callback is created for one of the standard position attachments (ug::aPosition, ug::aPosition2, ug::aPosition1 - whichever is present).
This class can't be instantiated directly. Use one of its specializations instead.
For Developers: Note that HangingNodeRefinerBase stores flags together with the refinement marks. Precisely the value 128 is used to flag whether an element has to be refined using hanging-node-rules.
See also
ug::HangingNodeRefiner_Grid, ug::HangingNodeRefiner_MultiGrid
Member Typedef Documentation
template<class TSelector> typedef TSelector::template traits<Edge>::iterator ug::HangingNodeRefinerBase< TSelector >::sel_edge_iter protected
template<class TSelector> typedef TSelector::template traits<Face>::iterator ug::HangingNodeRefinerBase< TSelector >::sel_face_iter protected
template<class TSelector> typedef TSelector::template traits<Volume>::iterator ug::HangingNodeRefinerBase< TSelector >::sel_vol_iter protected
template<class TSelector> typedef TSelector::template traits<Vertex>::iterator ug::HangingNodeRefinerBase< TSelector >::sel_vrt_iter protected
template<class TSelector> typedef TSelector ug::HangingNodeRefinerBase< TSelector >::selector_t
Member Enumeration Documentation
template<class TSelector> enum ug::HangingNodeRefinerBase::HNodeRefMarks
additional mark to RefinementMarks. Used to flag whether an element will be refined with constraining.
Enumerator
HNRM_TO_NORMAL
HNRM_TO_CONSTRAINED
HNRM_TO_CONSTRAINING
HNRM_MAX
Constructor & Destructor Documentation
template<class TSelector > ug::HangingNodeRefinerBase< TSelector >::HangingNodeRefinerBase (IRefinementCallback * refCallback = NULL)
References ug::HangingNodeRefinerBase< TSelector >::add_ref_mark_adjuster(), and ug::StdHNodeAdjuster::create().
Referenced by ug::HangingNodeRefinerBase< Selector >::get_refmark_selector().
template<class TSelector > ug::HangingNodeRefinerBase< TSelector >::~HangingNodeRefinerBase () virtual
References ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::set_grid(), and ug::Grid::unregister_observer().
Referenced by ug::HangingNodeRefinerBase< TSelector >::HangingNodeRefinerBase().
template<class TSelector > ug::HangingNodeRefinerBase< TSelector >::HangingNodeRefinerBase (const HangingNodeRefinerBase< TSelector > &) private
private copy constructor to avoid copy construction
References ug::HangingNodeRefinerBase< TSelector >::~HangingNodeRefinerBase().
Member Function Documentation
template<class TSelector > template<class TElem > template void ug::HangingNodeRefinerBase< TSelector >::add_hmark (TElem * elem, HNodeRefMarks mark) protected
References ug::PeriodicBoundaryManager::is_periodic(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::HangingNodeRefinerBase< TSelector >::mark(), ug::PeriodicBoundaryManager::master(), ug::Grid::periodic_boundary_manager(), ug::HangingNodeRefinerBase< TSelector >::remove_hmark(), and ug::PeriodicBoundaryManager::slaves().
Referenced by ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::HangingNodeRefinerBase< Selector >::marked_to_constraining(), and ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex().
template<class TSelector> void ug::HangingNodeRefinerBase< TSelector >::add_ref_mark_adjuster (SPIRefMarkAdjuster adjuster) inline
Add a refmark adjuster, which will be called while marks are adjusted during refinement / coarsening.
Referenced by ug::AddHorizontalAnisotropyAdjuster(), and ug::HangingNodeRefinerBase< TSelector >::HangingNodeRefinerBase().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks () protected virtual
This callback is called during execution of the refine() method after collect_objects_for_refine has returned. It is responsible to mark elements for hnode refinement. That means all elements on which a hanging node or constrained children shall be created have to be marked using mark_for_hnode_refinement during this method. The default implementation performs this marking for all local elements. Make sure to not mark any new elements for refinement during this method.
Reimplemented in ug::ParallelHangingNodeRefiner_MultiGrid.
References ug::HangingNodeRefinerBase< TSelector >::add_hmark(), ug::CollectAssociated(), ug::ConstrainingEdge::constrained_edge(), ug::ConstrainingFace::constrained_edge(), ug::ConstrainingFace::constrained_face(), ug::ConstrainingEdge::constrained_vertex(), ug::ConstrainingFace::constrained_vertex(), ug::IRefiner::grid(), ug::HangingNodeRefinerBase< TSelector >::HNRM_TO_CONSTRAINING, ug::HangingNodeRefinerBase< TSelector >::HNRM_TO_NORMAL, ug::LIB_GRID, ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::HangingNodeRefinerBase< TSelector >::marked_refine(), ug::HangingNodeRefinerBase< TSelector >::marked_to_constraining(), ug::Grid::num(), ug::ConstrainingEdge::num_constrained_edges(), ug::ConstrainingFace::num_constrained_edges(), ug::ConstrainingFace::num_constrained_faces(), ug::ConstrainingEdge::num_constrained_vertices(), ug::ConstrainingFace::num_constrained_vertices(), ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), UG_ASSERT, and UG_DLOG.
Referenced by ug::HangingNodeRefinerBase< TSelector >::collect_objects_for_refine(), ug::HangingNodeRefinerBase< Selector >::continue_collect_objects_for_refine(), and ug::HangingNodeRefinerBase< TSelector >::perform_refinement().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::clear_marks () virtual
clears all marks. Default implementation is empty
Reimplemented from ug::IRefiner.
References ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefEdges, ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefFaces, ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefVols, ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefVrts, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, and ug::HangingNodeRefinerBase< TSelector >::mark().
Referenced by ug::HangingNodeRefinerBase< Selector >::node_dependency_order_1_enabled(), and ug::HangingNodeRefinerBase< TSelector >::perform_refinement().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::collect_objects_for_refine () protected virtual
marks unmarked elements that have to be refined due to marked neighbors.
all elements that have to be refined will be written to the passed queues. Note that this will most likely be more elements than just the marked ones.
This method is virtual to allow derivates to mark additional elements as required. Normally a a derived class will first call the method of its this class and the perform its own operations.
References ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::HangingNodeRefinerBase< TSelector >::continue_collect_objects_for_refine(), HNODE_PROFILE_FUNC, ug::LIB_GRID, ug::HangingNodeRefinerBase< TSelector >::m_adjustingRefMarks, ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefEdges, ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefFaces, ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefVols, ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefVrts, ug::HangingNodeRefinerBase< TSelector >::m_refMarkAdjusters, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, UG_DLOG, and UG_LOG.
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), and ug::HangingNodeRefinerBase< Selector >::refinement_is_allowed().
template<class TSelector> virtual bool ug::HangingNodeRefinerBase< TSelector >::continue_collect_objects_for_refine (bool continueRequired) inline protected virtual
after each iteration in collet_objects_for_refine, this method determines whether the iteration shall be continued. Important for parallel refiners. The default implementation simply returns the specified value. This is fine for serial environments.
Reimplemented in ug::ParallelHangingNodeRefiner_MultiGrid.
Referenced by ug::HangingNodeRefinerBase< TSelector >::collect_objects_for_refine().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::enable_node_dependency_order_1 (bool bEnable)
enables or disables node-dependency-order-1.
If enabled, hanging nodes may only depend on non-hanging nodes. An edge containing a hanging node thus will not have a hanging-node as a corner vertex.
Enabled by default.
References ug::HangingNodeRefinerBase< TSelector >::m_nodeDependencyOrder1, and ug::HangingNodeRefinerBase< TSelector >::m_refMarkAdjusters.
Referenced by ug::HangingNodeRefinerBase< TSelector >::save_marks_to_file().
template<class TSelector> virtual Vertex* ug::HangingNodeRefinerBase< TSelector >::get_center_vertex (Edge * e) protected pure virtual
Returns the vertex associated with the edge.
pure virtual method. Has to return the center vertex which was set to the edge via set_center_vertex. If no vertex was set, NULL has to be returned.
Implemented in ug::HangingNodeRefiner_MultiGrid, and ug::HangingNodeRefiner_Grid.
Referenced by ug::HangingNodeRefinerBase< Selector >::is_marked(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_vertex(), ug::HangingNodeRefinerBase< TSelector >::process_constraining_face(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex(), and ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex().
template<class TSelector> virtual Vertex* ug::HangingNodeRefinerBase< TSelector >::get_center_vertex (Face * f) protected pure virtual
Returns the vertex associated with the face.
pure virtual method. Has to return the center vertex which was set to the face via set_center_vertex. If no vertex was set, NULL has to be returned.
Implemented in ug::HangingNodeRefiner_MultiGrid, and ug::HangingNodeRefiner_Grid.
template<class TSelector > RefinementMark ug::HangingNodeRefinerBase< TSelector >::get_mark (Vertex * v) virtual
Returns the mark of a given element.
Reimplemented from ug::IRefiner.
References ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_COARSEN, ug::RM_DUMMY, and ug::RM_REFINE.
Referenced by ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::HangingNodeRefinerBase< TSelector >::mark(), ug::HangingNodeRefinerBase< TSelector >::mark_neighborhood(), ug::HangingNodeRefinerBase< Selector >::node_dependency_order_1_enabled(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex(), and ug::HangingNodeRefinerBase< TSelector >::remove_coarsen_marks().
template<class TSelector > RefinementMark ug::HangingNodeRefinerBase< TSelector >::get_mark (Edge * e) virtual
Returns the mark of a given element.
Reimplemented from ug::IRefiner.
References ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_COARSEN, ug::RM_DUMMY, and ug::RM_REFINE.
template<class TSelector > RefinementMark ug::HangingNodeRefinerBase< TSelector >::get_mark (Face * f) virtual
Returns the mark of a given element.
Reimplemented from ug::IRefiner.
References ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_COARSEN, ug::RM_DUMMY, and ug::RM_REFINE.
template<class TSelector > RefinementMark ug::HangingNodeRefinerBase< TSelector >::get_mark (Volume * v) virtual
Returns the mark of a given element.
Reimplemented from ug::IRefiner.
References ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_COARSEN, ug::RM_DUMMY, ug::RM_REFINE, and ug::HangingNodeRefinerBase< TSelector >::save_marks_to_file().
template<class TSelector> TSelector& ug::HangingNodeRefinerBase< TSelector >::get_refmark_selector () inline protected
returns the selector which is internally used to mark elements.
Be sure to use it carefully!
Referenced by ug::HangingNodeRefinerBase< TSelector >::save_marks_to_file().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::grid_to_be_destroyed (Grid * grid) virtual
Reimplemented from ug::GridObserver.
Reimplemented in ug::HangingNodeRefiner_MultiGrid, and ug::HangingNodeRefiner_Grid.
References ug::HangingNodeRefinerBase< TSelector >::m_pGrid.
template<class TSelector> bool ug::HangingNodeRefinerBase< TSelector >::is_marked (Vertex * v) inline protected
Referenced by ug::HangingNodeRefinerBase< TSelector >::mark_neighborhood().
template<class TSelector> bool ug::HangingNodeRefinerBase< TSelector >::is_marked (Edge * e) inline protected
template<class TSelector> bool ug::HangingNodeRefinerBase< TSelector >::is_marked (Face * f) inline protected
template<class TSelector> bool ug::HangingNodeRefinerBase< TSelector >::is_marked (Volume * v) inline protected
template<class TSelector > bool ug::HangingNodeRefinerBase< TSelector >::mark (Vertex * v, RefinementMark refMark = RM_REFINE) virtual
Marks a element for refinement.
Reimplemented from ug::IRefiner.
Reimplemented in ug::HangingNodeRefiner_Grid.
References ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::HangingNodeRefinerBase< TSelector >::m_adjustingRefMarks, ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefVrts, ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_DUMMY, and ug::RM_REFINE.
Referenced by ug::HangingNodeRefinerBase< TSelector >::add_hmark(), ug::HangingNodeRefinerBase< TSelector >::clear_marks(), ug::HangingNodeRefinerBase< TSelector >::mark_neighborhood(), and ug::HangingNodeRefinerBase< Selector >::node_dependency_order_1_enabled().
template<class TSelector > bool ug::HangingNodeRefinerBase< TSelector >::mark (Edge * e, RefinementMark refMark = RM_REFINE) virtual
Marks a element for refinement.
Reimplemented from ug::IRefiner.
Reimplemented in ug::HangingNodeRefiner_Grid.
References ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::HangingNodeRefinerBase< TSelector >::m_adjustingRefMarks, ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefEdges, ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_DUMMY, and ug::RM_REFINE.
template<class TSelector > bool ug::HangingNodeRefinerBase< TSelector >::mark (Face * f, RefinementMark refMark = RM_REFINE) virtual
Marks a element for refinement.
Reimplemented from ug::IRefiner.
Reimplemented in ug::HangingNodeRefiner_Grid.
References ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::HangingNodeRefinerBase< TSelector >::m_adjustingRefMarks, ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefFaces, ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_DUMMY, and ug::RM_REFINE.
template<class TSelector > bool ug::HangingNodeRefinerBase< TSelector >::mark (Volume * v, RefinementMark refMark = RM_REFINE) virtual
Marks a element for refinement.
Reimplemented from ug::IRefiner.
Reimplemented in ug::HangingNodeRefiner_Grid.
References ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::HangingNodeRefinerBase< TSelector >::m_adjustingRefMarks, ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefVols, ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::HangingNodeRefinerBase< TSelector >::mark_neighborhood(), ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_DUMMY, and ug::RM_REFINE.
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::mark_neighborhood (size_t numIterations, RefinementMark refMark, bool sideNbrsOnly) virtual
Marks the neighborhood of the current selection.
See also
ISelector::mark_neighborhood
Reimplemented from ug::IRefiner.
References ug::Grid::associated_elements(), end_for, for_each_in_vec, ug::Grid::get_edge(), ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::Face::get_opposing_side(), ug::HangingNodeRefinerBase< TSelector >::is_marked(), lg_end_for, lg_for_each, ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::HangingNodeRefinerBase< TSelector >::mark(), ug::Grid::num_edges(), ug::Grid::num_faces(), ug::FaceVertices::num_vertices(), ug::VolumeVertices::num_vertices(), ug::Grid::num_volumes(), pcl::OneProcTrue(), ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_COARSEN, ug::RM_DUMMY, ug::RM_NONE, ug::RM_REFINE, ug::PointerConstArray< TPtr >::size(), ug::EdgeVertices::vertex(), ug::FaceVertices::vertices(), and ug::VolumeVertices::vertices().
Referenced by ug::HangingNodeRefinerBase< TSelector >::mark(), and ug::HangingNodeRefinerBase< Selector >::node_dependency_order_1_enabled().
template<class TSelector> template<class TElem > bool ug::HangingNodeRefinerBase< TSelector >::marked_adaptive (TElem * elem) inline protected
Referenced by ug::HangingNodeRefinerBase< Selector >::marked_regular(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex(), and ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex().
template<class TSelector> template<class TElem > bool ug::HangingNodeRefinerBase< TSelector >::marked_anisotropic (TElem * elem) inline protected
template<class TSelector> template<class TElem > bool ug::HangingNodeRefinerBase< TSelector >::marked_coarsen (TElem * elem) inline protected
template<class TSelector> template<class TElem > bool ug::HangingNodeRefinerBase< TSelector >::marked_copy (TElem * elem) inline protected
Referenced by ug::HangingNodeRefinerBase< Selector >::marked_regular(), ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex(), and ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex().
template<class TSelector> template<class TElem > bool ug::HangingNodeRefinerBase< TSelector >::marked_refine (TElem * elem) inline protected
Referenced by ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::HangingNodeRefinerBase< Selector >::marked_regular(), and ug::HangingNodeRefinerBase< TSelector >::perform_refinement().
template<class TSelector> template<class TElem > bool ug::HangingNodeRefinerBase< TSelector >::marked_regular (TElem * elem) inline protected
template<class TSelector> template<class TElem > bool ug::HangingNodeRefinerBase< TSelector >::marked_to_constrained (TElem * elem) inline protected
template<class TSelector> template<class TElem > bool ug::HangingNodeRefinerBase< TSelector >::marked_to_constraining (TElem * elem) inline protected
Referenced by ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_edge(), and ug::HangingNodeRefinerBase< TSelector >::process_constrained_face().
template<class TSelector> template<class TElem > bool ug::HangingNodeRefinerBase< TSelector >::marked_to_normal (TElem * elem) inline protected
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_edge(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_face(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_vertex(), and ug::HangingNodeRefinerBase< TSelector >::process_constraining_face().
template<class TSelector> bool ug::HangingNodeRefinerBase< TSelector >::node_dependency_order_1_enabled () inline
enables or disables node-dependency-order-1.
If enabled, hanging nodes may only depend on non-hanging nodes. An edge containing a hanging node thus will not have a hanging-node as a corner vertex.
Enabled by default.
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::perform_refinement () protected virtual
performs refinement on the marked elements.
The grid's message hub is informed using a "GridAdaption" message, passing an instance of GridMessage_Adapation, with values GMAT_HNODE_REFINEMENT_BEGINS and GMAT_HNODE_REFINEMENT_ENDS. See lib_grid/lib_grid_messages.h for more details.
as defined in lib_grid/
automatically extends the refinement to avoid multiple hanging nodes on a single edge or face.
refine calls several virtual methods, which allow to influence the refinement process. Most notably the methods
collect_objects_for_refine
pre_refine
post_refine
are called in the given order. During element refinement further virtual methods are called, which perform the actual element refinement.
Implements ug::IRefiner.
References ug::aPosition, ug::aPosition1, ug::aPosition2, ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::HangingNodeRefinerBase< TSelector >::clear_marks(), ug::HangingNodeRefinerBase< TSelector >::collect_objects_for_refine(), ug::Grid::enable_options(), ug::GMAT_HNODE_REFINEMENT_BEGINS, ug::GMAT_HNODE_REFINEMENT_ENDS, ug::IRefiner::grid(), ug::GRIDOPT_AUTOGENERATE_SIDES, ug::Grid::has_vertex_attachment(), HNODE_PROFILE_BEGIN, HNODE_PROFILE_END, ug::LIB_GRID, LOG, ug::IRefiner::m_adjustedMarksDebugFilename, ug::IRefiner::m_messageHub, ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::IRefiner::m_refCallback, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::HangingNodeRefinerBase< TSelector >::marked_copy(), ug::HangingNodeRefinerBase< TSelector >::marked_refine(), ug::HangingNodeRefinerBase< TSelector >::marked_to_constraining(), ug::HangingNodeRefinerBase< TSelector >::marked_to_normal(), ug::Grid::option_is_enabled(), ug::HangingNodeRefinerBase< TSelector >::post_refine(), ug::HangingNodeRefinerBase< TSelector >::pre_refine(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_edge(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_face(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_vertex(), ug::HangingNodeRefinerBase< TSelector >::process_constraining_edge(), ug::HangingNodeRefinerBase< TSelector >::process_constraining_face(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), ug::HangingNodeRefinerBase< TSelector >::remove_hmark(), ug::RM_REFINE, ug::HangingNodeRefinerBase< TSelector >::save_marks_to_file(), and UG_DLOG.
template<class TSelector> virtual void ug::HangingNodeRefinerBase< TSelector >::post_refine () inline protected virtual
called by refine after refinement is done.
Reimplemented in ug::HangingNodeRefiner_Grid, and ug::ParallelHangingNodeRefiner_MultiGrid.
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement().
template<class TSelector> virtual void ug::HangingNodeRefinerBase< TSelector >::pre_refine () inline protected virtual
called by refine after collect_objects_for_refine and before actual refinement begins.
Reimplemented in ug::HangingNodeRefiner_MultiGrid, and ug::ParallelHangingNodeRefiner_MultiGrid.
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::process_constrained_edge (ConstrainedEdge * cde) protected virtual
called to refine the specified element.
Refines the element. Corner vertices of the newly created element can be specified through newCornerVrts. newCornerVrts = NULL (default) means, that the corner vertices of the original element shall be taken.
References ug::ConstrainingEdge::clear_constrained_edges(), ug::ConstrainingFace::clear_constrained_edges(), ug::Grid::create_and_replace(), ug::EDGE, ug::FACE, ug::ConstrainedEdge::get_constraining_object(), ug::ConstrainedEdge::get_parent_base_object_id(), ug::IRefiner::grid(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::marked_to_constraining(), ug::HangingNodeRefinerBase< TSelector >::marked_to_normal(), ug::HangingNodeRefinerBase< TSelector >::process_constraining_edge(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_hanging_vertex(), and UG_ASSERT.
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< Selector >::post_refine(), and ug::HangingNodeRefinerBase< TSelector >::process_constrained_vertex().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::process_constrained_face (ConstrainedFace * cdf) protected virtual
called to refine the specified element.
Refines the element. Corner vertices of the newly created element can be specified through newCornerVrts. newCornerVrts = NULL (default) means, that the corner vertices of the original element shall be taken.
References ug::ConstrainingFace::clear_constrained_faces(), ug::Grid::create_and_replace(), ug::FACE, ug::ConstrainedFace::get_constraining_object(), ug::ConstrainedFace::get_parent_base_object_id(), ug::IRefiner::grid(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::marked_to_constraining(), ug::HangingNodeRefinerBase< TSelector >::marked_to_normal(), ug::FaceVertices::num_vertices(), ug::HangingNodeRefinerBase< TSelector >::process_constraining_face(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), and UG_ASSERT.
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< Selector >::post_refine(), and ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::process_constrained_vertex (ConstrainedVertex * cdv) protected virtual
called to refine the specified element.
Refines the element. Corner vertices of the newly created element can be specified through newCornerVrts. newCornerVrts = NULL (default) means, that the corner vertices of the original element shall be taken.
References ug::ConstrainingEdge::clear_constrained_vertices(), ug::ConstrainingFace::clear_constrained_vertices(), ug::Grid::create_and_replace(), ug::EDGE, ug::FACE, ug::HangingNodeRefinerBase< TSelector >::get_center_vertex(), ug::ConstrainedVertex::get_constraining_object(), ug::ConstrainedVertex::get_parent_base_object_id(), ug::IRefiner::grid(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::marked_to_normal(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_edge(), ug::HangingNodeRefinerBase< TSelector >::set_center_vertex(), and UG_ASSERT.
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< Selector >::post_refine(), and ug::HangingNodeRefinerBase< TSelector >::remove_hmark().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::process_constraining_edge (ConstrainingEdge * cge) protected virtual
called to refine the specified element.
Refines the element. Corner vertices of the newly created element can be specified through newCornerVrts. newCornerVrts = NULL (default) means, that the corner vertices of the original element shall be taken.
Reimplemented in ug::HangingNodeRefiner_MultiGrid, and ug::HangingNodeRefiner_Grid.
References ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_normal_vertex().
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< Selector >::post_refine(), and ug::HangingNodeRefinerBase< TSelector >::process_constrained_edge().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::process_constraining_face (ConstrainingFace * cgf) protected virtual
called to refine the specified element.
Refines the element. Corner vertices of the newly created element can be specified through newCornerVrts. newCornerVrts = NULL (default) means, that the corner vertices of the original element shall be taken.
Reimplemented in ug::HangingNodeRefiner_Grid.
References ug::Grid::create_and_replace(), ug::HangingNodeRefinerBase< TSelector >::get_center_vertex(), ug::IRefiner::grid(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::marked_to_normal(), ug::FaceVertices::num_vertices(), ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::set_center_vertex(), and UG_ASSERT.
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< Selector >::post_refine(), and ug::HangingNodeRefinerBase< TSelector >::process_constrained_face().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_hanging_vertex (Edge * e, Vertex ** newCornerVrts = NULL) protected virtual
called to refine the specified element.
Refines the element. Corner vertices of the newly created element can be specified through newCornerVrts. newCornerVrts = NULL (default) means, that the corner vertices of the original element shall be taken.
Reimplemented in ug::HangingNodeRefiner_MultiGrid.
References ug::ConstrainingEdge::add_constrained_object(), ug::Grid::create(), ug::Grid::create_and_replace(), ug::IRefiner::grid(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::IRefiner::m_refCallback, ug::IRefinementCallback::new_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), ug::HangingNodeRefinerBase< TSelector >::set_center_vertex(), ug::ConstrainedEdge::set_constraining_object(), ug::ConstrainingEdge::type_match(), UG_ASSERT, and ug::EdgeVertices::vertex().
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< Selector >::post_refine(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_edge(), and ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_normal_vertex().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_normal_vertex (Edge * e, Vertex ** newCornerVrts = NULL) protected virtual
called to refine the specified element.
Refines the element. Corner vertices of the newly created element can be specified through newCornerVrts. newCornerVrts = NULL (default) means, that the corner vertices of the original element shall be taken.
Reimplemented in ug::HangingNodeRefiner_MultiGrid, and ug::HangingNodeRefiner_Grid.
References ug::Grid::create(), ug::Grid::create_by_cloning(), ug::IRefiner::grid(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::IRefiner::m_refCallback, ug::HangingNodeRefinerBase< TSelector >::marked_adaptive(), ug::HangingNodeRefinerBase< TSelector >::marked_copy(), ug::IRefinementCallback::new_vertex(), ug::Edge::refine(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), ug::Grid::register_element(), ug::HangingNodeRefinerBase< TSelector >::set_center_vertex(), and UG_ASSERT.
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< Selector >::post_refine(), and ug::HangingNodeRefinerBase< TSelector >::process_constraining_edge().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex (Face * f, Vertex ** newCornerVrts = NULL) protected virtual
called to refine the specified element.
Refines the element. Corner vertices of the newly created element can be specified through newCornerVrts. newCornerVrts = NULL (default) means, that the corner vertices of the original element shall be taken.
Reimplemented in ug::HangingNodeRefiner_MultiGrid.
References ug::ConstrainingFace::add_constrained_object(), ug::Grid::create(), ug::Grid::create_and_replace(), ug::HangingNodeRefinerBase< TSelector >::get_center_vertex(), ug::Grid::get_edge(), ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::IRefiner::grid(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::IRefiner::m_refCallback, ug::HangingNodeRefinerBase< TSelector >::marked_adaptive(), ug::MAX_FACE_VERTICES, ug::IRefinementCallback::new_vertex(), ug::Face::num_edges(), ug::FaceVertices::num_vertices(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_face(), ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), ug::Grid::register_element(), ug::RM_REFINE, ug::HangingNodeRefinerBase< TSelector >::set_center_vertex(), ug::ConstrainedEdge::set_constraining_object(), ug::ConstrainedFace::set_constraining_object(), UG_ASSERT, and ug::FaceVertices::vertex().
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< Selector >::post_refine(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_face(), and ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex (Face * f, Vertex ** newCornerVrts = NULL) protected virtual
called to refine the specified element.
Refines the element. Corner vertices of the newly created element can be specified through newCornerVrts. newCornerVrts = NULL (default) means, that the corner vertices of the original element shall be taken.
Reimplemented in ug::HangingNodeRefiner_MultiGrid, and ug::HangingNodeRefiner_Grid.
References ug::Grid::create_by_cloning(), ug::HangingNodeRefinerBase< TSelector >::get_center_vertex(), ug::Grid::get_edge(), ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::IRefiner::grid(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::IRefiner::m_refCallback, ug::HangingNodeRefinerBase< TSelector >::marked_adaptive(), ug::HangingNodeRefinerBase< TSelector >::marked_copy(), ug::MAX_FACE_VERTICES, ug::IRefinementCallback::new_vertex(), ug::Face::num_edges(), ug::FaceVertices::num_vertices(), ug::Face::refine(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), ug::Grid::register_element(), ug::RM_REFINE, ug::HangingNodeRefinerBase< TSelector >::set_center_vertex(), ug::FaceDescriptor::set_vertex(), and UG_ASSERT.
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< Selector >::post_refine(), and ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_hanging_vertex().
template<class TSelector > void ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex (Volume * v, Vertex ** newVolumeVrts = NULL) protected virtual
called to refine the specified element.
Refines the element. Corner vertices of the newly created element can be specified through newCornerVrts. newCornerVrts = NULL (default) means, that the corner vertices of the original element shall be taken.
Reimplemented in ug::HangingNodeRefiner_MultiGrid, and ug::HangingNodeRefiner_Grid.
References ug::HangingNodeRefinerBase< TSelector >::add_hmark(), ug::Grid::create_by_cloning(), ug::IRefinementCallback::current_pos(), ug::HangingNodeRefinerBase< TSelector >::get_center_vertex(), ug::Grid::get_edge(), ug::Grid::get_face(), ug::GetGridObjectCenter(), ug::IRefiner::grid(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::IRefiner::m_refCallback, ug::HangingNodeRefinerBase< TSelector >::marked_adaptive(), ug::HangingNodeRefinerBase< TSelector >::marked_copy(), ug::IRefinementCallback::new_vertex(), ug::Volume::num_edges(), ug::Volume::num_faces(), ug::FaceVertices::num_vertices(), ug::VolumeVertices::num_vertices(), ug::Volume::refine(), ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed(), ug::Grid::register_element(), ug::VolumeDescriptor::set_vertex(), UG_ASSERT, and ug::VolumeVertices::vertex().
Referenced by ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< Selector >::post_refine(), and ug::HangingNodeRefinerBase< TSelector >::process_constraining_face().
template<class TSelector> virtual bool ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed (Vertex * elem) inline protected virtual
a callback that allows to deny refinement of special vertices
Reimplemented in ug::HangingNodeRefiner_MultiGrid, and ug::ParallelHangingNodeRefiner_MultiGrid.
Referenced by ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::HangingNodeRefinerBase< TSelector >::mark(), ug::HangingNodeRefinerBase< TSelector >::mark_neighborhood(), ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex(), and ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex().
template<class TSelector> virtual bool ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed (Edge * elem) inline protected virtual
a callback that allows to deny refinement of special edges
Reimplemented in ug::HangingNodeRefiner_MultiGrid, and ug::ParallelHangingNodeRefiner_MultiGrid.
template<class TSelector> virtual bool ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed (Face * elem) inline protected virtual
a callback that allows to deny refinement of special faces
Reimplemented in ug::HangingNodeRefiner_MultiGrid, and ug::ParallelHangingNodeRefiner_MultiGrid.
template<class TSelector> virtual bool ug::HangingNodeRefinerBase< TSelector >::refinement_is_allowed (Volume * elem) inline protected virtual
a callback that allows to deny refinement of special volumes
Reimplemented in ug::HangingNodeRefiner_MultiGrid, and ug::ParallelHangingNodeRefiner_MultiGrid.
template<class TSelector > template<class TElem > bool ug::HangingNodeRefinerBase< TSelector >::remove_coarsen_marks () protected
removes coarsen marks from the selection
Note that derived classes are not informed about those deselections!
References ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, and ug::RM_COARSEN.
Referenced by ug::HangingNodeRefinerBase< Selector >::marked_to_constraining().
template<class TSelector > template<class TElem > void ug::HangingNodeRefinerBase< TSelector >::remove_hmark (TElem * elem, uint mark) protected
References ug::PeriodicBoundaryManager::is_periodic(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::PeriodicBoundaryManager::master(), ug::Grid::periodic_boundary_manager(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_vertex(), and ug::PeriodicBoundaryManager::slaves().
Referenced by ug::HangingNodeRefinerBase< TSelector >::add_hmark(), ug::HangingNodeRefinerBase< Selector >::marked_to_constraining(), and ug::HangingNodeRefinerBase< TSelector >::perform_refinement().
template<class TSelector > bool ug::HangingNodeRefinerBase< TSelector >::save_marks_to_file (const char * filename) virtual
Writes the associated grid and marks to a file. Pure virtual.
Elements should be assigned to subsets depending on their current refinement-mark.
Implements ug::IRefiner.
References ug::GridSubsetHandler::assign_subset(), ug::AssignGridToSubset(), ug::AssignSubsetColors(), ug::Grid::edges_begin(), ug::Grid::edges_end(), ug::HangingNodeRefinerBase< TSelector >::enable_node_dependency_order_1(), ug::Grid::faces_begin(), ug::Grid::faces_end(), ug::HangingNodeRefinerBase< TSelector >::get_refmark_selector(), ug::LIB_GRID, ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::SubsetInfo::name, ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_COARSEN, ug::RM_NONE, ug::RM_REFINE, ug::SaveGridHierarchyTransformed(), ug::SaveGridToFile(), ug::ISubsetHandler::subset_info(), UG_DLOG, UG_THROW, ug::Grid::vertices_begin(), ug::Grid::vertices_end(), ug::Grid::volumes_begin(), and ug::Grid::volumes_end().
Referenced by ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::HangingNodeRefinerBase< Selector >::node_dependency_order_1_enabled(), and ug::HangingNodeRefinerBase< TSelector >::perform_refinement().
template<class TSelector> virtual void ug::HangingNodeRefinerBase< TSelector >::set_center_vertex (Edge * e, Vertex * v) protected pure virtual
Associates a vertex with the edge (pure virtual).
Implemented in ug::HangingNodeRefiner_MultiGrid, and ug::HangingNodeRefiner_Grid.
Referenced by ug::HangingNodeRefinerBase< Selector >::is_marked(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_vertex(), ug::HangingNodeRefinerBase< TSelector >::process_constraining_face(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), and ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex().
template<class TSelector> virtual void ug::HangingNodeRefinerBase< TSelector >::set_center_vertex (Face * f, Vertex * v) protected pure virtual
Associates a vertex with the face (pure virtual).
Implemented in ug::HangingNodeRefiner_MultiGrid, and ug::HangingNodeRefiner_Grid.
template<class TSelector> void ug::HangingNodeRefinerBase< TSelector >::set_grid (typename TSelector::grid_type * grid) protected
performs registration and deregistration at a grid.
Sets a grid and performs registration at the given grid. The associated selector is also initialised with the given grid. It is cruical to call this method or everything will fail.
call set_grid(NULL) to unregister the observer from a grid.
Please note that this method is not declared virtual, since it is called during construction and destruction.
References ug::IRefiner::grid(), ug::HangingNodeRefinerBase< TSelector >::m_pGrid, ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements, ug::OT_GRID_OBSERVER, ug::Grid::register_observer(), ug::IRefiner::set_message_hub(), and ug::Grid::unregister_observer().
Referenced by ug::HangingNodeRefinerBase< Selector >::refinement_is_allowed(), and ug::HangingNodeRefinerBase< TSelector >::~HangingNodeRefinerBase().
Member Data Documentation
template<class TSelector> bool ug::HangingNodeRefinerBase< TSelector >::m_adjustingRefMarks private
true during collect_objects_for_refine
Referenced by ug::HangingNodeRefinerBase< TSelector >::collect_objects_for_refine(), and ug::HangingNodeRefinerBase< TSelector >::mark().
template<class TSelector> std::vector<Edge*> ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefEdges private
Referenced by ug::HangingNodeRefinerBase< TSelector >::clear_marks(), ug::HangingNodeRefinerBase< TSelector >::collect_objects_for_refine(), and ug::HangingNodeRefinerBase< TSelector >::mark().
template<class TSelector> std::vector<Face*> ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefFaces private
Referenced by ug::HangingNodeRefinerBase< TSelector >::clear_marks(), ug::HangingNodeRefinerBase< TSelector >::collect_objects_for_refine(), and ug::HangingNodeRefinerBase< TSelector >::mark().
template<class TSelector> std::vector<Volume*> ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefVols private
Referenced by ug::HangingNodeRefinerBase< TSelector >::clear_marks(), ug::HangingNodeRefinerBase< TSelector >::collect_objects_for_refine(), and ug::HangingNodeRefinerBase< TSelector >::mark().
template<class TSelector> std::vector<Vertex*> ug::HangingNodeRefinerBase< TSelector >::m_newlyMarkedRefVrts private
Referenced by ug::HangingNodeRefinerBase< TSelector >::clear_marks(), ug::HangingNodeRefinerBase< TSelector >::collect_objects_for_refine(), and ug::HangingNodeRefinerBase< TSelector >::mark().
template<class TSelector> bool ug::HangingNodeRefinerBase< TSelector >::m_nodeDependencyOrder1 private
Referenced by ug::HangingNodeRefinerBase< TSelector >::enable_node_dependency_order_1(), and ug::HangingNodeRefinerBase< Selector >::node_dependency_order_1_enabled().
template<class TSelector> Grid* ug::HangingNodeRefinerBase< TSelector >::m_pGrid private
Referenced by ug::HangingNodeRefinerBase< TSelector >::add_hmark(), ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::HangingNodeRefinerBase< TSelector >::grid_to_be_destroyed(), ug::HangingNodeRefinerBase< TSelector >::mark(), ug::HangingNodeRefinerBase< TSelector >::mark_neighborhood(), ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_edge(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_face(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_vertex(), ug::HangingNodeRefinerBase< TSelector >::process_constraining_face(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::remove_hmark(), ug::HangingNodeRefinerBase< TSelector >::save_marks_to_file(), ug::HangingNodeRefinerBase< TSelector >::set_grid(), and ug::HangingNodeRefinerBase< TSelector >::~HangingNodeRefinerBase().
template<class TSelector> std::vector<SPIRefMarkAdjuster> ug::HangingNodeRefinerBase< TSelector >::m_refMarkAdjusters protected
Referenced by ug::HangingNodeRefinerBase< Selector >::add_ref_mark_adjuster(), ug::HangingNodeRefinerBase< TSelector >::collect_objects_for_refine(), and ug::HangingNodeRefinerBase< TSelector >::enable_node_dependency_order_1().
template<class TSelector> TSelector ug::HangingNodeRefinerBase< TSelector >::m_selMarkedElements protected
Referenced by ug::HangingNodeRefinerBase< TSelector >::add_hmark(), ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::HangingNodeRefinerBase< TSelector >::clear_marks(), ug::HangingNodeRefinerBase< TSelector >::collect_objects_for_refine(), ug::HangingNodeRefinerBase< TSelector >::get_mark(), ug::HangingNodeRefinerBase< Selector >::get_refmark_selector(), ug::HangingNodeRefinerBase< Selector >::is_marked(), ug::HangingNodeRefinerBase< TSelector >::mark(), ug::HangingNodeRefinerBase< TSelector >::mark_neighborhood(), ug::HangingNodeRefinerBase< Selector >::marked_adaptive(), ug::HangingNodeRefinerBase< Selector >::marked_anisotropic(), ug::HangingNodeRefinerBase< Selector >::marked_coarsen(), ug::HangingNodeRefinerBase< Selector >::marked_copy(), ug::HangingNodeRefinerBase< Selector >::marked_refine(), ug::HangingNodeRefinerBase< Selector >::marked_to_constrained(), ug::HangingNodeRefinerBase< Selector >::marked_to_constraining(), ug::HangingNodeRefinerBase< Selector >::marked_to_normal(), ug::HangingNodeRefinerBase< TSelector >::perform_refinement(), ug::HangingNodeRefinerBase< TSelector >::remove_coarsen_marks(), ug::HangingNodeRefinerBase< TSelector >::remove_hmark(), and ug::HangingNodeRefinerBase< TSelector >::set_grid().
The documentation for this class was generated from the following files:
ugbase/lib_grid/algorithms/refinement/hanging_node_refiner_base.h
ugbase/lib_grid/algorithms/refinement/hanging_node_refiner_base.cpp