ug4: ug::bridge::MessageHubTest Class Reference
ug::bridge::MessageHubTest Class Reference
ugbase » Bridge » Misc Bridge » Test Bridge
Public Member Functions
void callback (const TestMessage &msg)
MessageHubTest ()
void post_message (const char *message)
Protected Attributes
MessageHub::SPCallbackId m_callbackId
SPMessageHub m_msgHub
Constructor & Destructor Documentation
ug::bridge::MessageHubTest::MessageHubTest () inline
References callback(), and ug::bridge::TestMsgCallback().
Member Function Documentation
void ug::bridge::MessageHubTest::callback (const TestMessage & msg) inline
References ug::bridge::TestMessage::m_strMsg, and UG_LOG.
Referenced by MessageHubTest().
void ug::bridge::MessageHubTest::post_message (const char * message) inline
References ug::bridge::TestMessage::m_strMsg.
Member Data Documentation
MessageHub::SPCallbackId ug::bridge::MessageHubTest::m_callbackId protected
SPMessageHub ug::bridge::MessageHubTest::m_msgHub protected
The documentation for this class was generated from the following file:
ugbase/bridge/misc_bridges/test_bridge.cpp