ug4: ug::GPUSparseMatrix< TValueType >::row_iterator Class Reference
ug::GPUSparseMatrix< TValueType >::row_iterator Class Reference
#include <gpusparsematrix.h>
Public Member Functions
void check () const
size_t index () const
bool operator!= (const row_iterator &o) const
void operator++ ()
void operator+= (int nr)
row_iterator * operator-> ()
bool operator== (const row_iterator &other) const
row_iterator (GPUSparseMatrix &_A, size_t _row, size_t _i)
value_type & value ()
~row_iterator ()
Private Attributes
GPUSparseMatrix & A
size_t i
size_t row
Detailed Description
template<typename TValueType>
class ug::GPUSparseMatrix< TValueType >::row_iterator
row_iterator iterator over a row
Constructor & Destructor Documentation
row_iterator()
template<typename TValueType > ug::GPUSparseMatrix< TValueType >::row_iterator::row_iterator (GPUSparseMatrix & _A, size_t _row, size_t _i) inline
References ug::GPUSparseMatrix< TValueType >::row_iterator::A, and ug::GPUSparseMatrix< TValueType >::add_iterator().
~row_iterator()
template<typename TValueType > ug::GPUSparseMatrix< TValueType >::row_iterator::~row_iterator () inline
References ug::GPUSparseMatrix< TValueType >::row_iterator::A, and ug::GPUSparseMatrix< TValueType >::remove_iterator().
Member Function Documentation
check()
template<typename TValueType > void ug::GPUSparseMatrix< TValueType >::row_iterator::check () const inline
References ug::GPUSparseMatrix< TValueType >::row_iterator::A, ug::GPUSparseMatrix< TValueType >::check_row(), ug::GPUSparseMatrix< TValueType >::row_iterator::i, and ug::GPUSparseMatrix< TValueType >::row_iterator::row.
Referenced by ug::GPUSparseMatrix< TValueType >::row_iterator::index(), ug::GPUSparseMatrix< TValueType >::row_iterator::operator==(), and ug::GPUSparseMatrix< TValueType >::row_iterator::value().
index()
template<typename TValueType > size_t ug::GPUSparseMatrix< TValueType >::row_iterator::index () const inline
References ug::GPUSparseMatrix< TValueType >::row_iterator::A, ug::GPUSparseMatrix< TValueType >::row_iterator::check(), ug::GPUSparseMatrix< TValueType >::cols, and ug::GPUSparseMatrix< TValueType >::row_iterator::i.
operator!=()
template<typename TValueType > bool ug::GPUSparseMatrix< TValueType >::row_iterator::operator!= (const row_iterator & o) const inline
References ug::GPUSparseMatrix< TValueType >::row_iterator::i.
operator++()
template<typename TValueType > void ug::GPUSparseMatrix< TValueType >::row_iterator::operator++ () inline
References ug::GPUSparseMatrix< TValueType >::row_iterator::i.
operator+=()
template<typename TValueType > void ug::GPUSparseMatrix< TValueType >::row_iterator::operator+= (int nr) inline
References ug::GPUSparseMatrix< TValueType >::row_iterator::i.
operator->()
template<typename TValueType > row_iterator* ug::GPUSparseMatrix< TValueType >::row_iterator::operator-> () inline
operator==()
template<typename TValueType > bool ug::GPUSparseMatrix< TValueType >::row_iterator::operator== (const row_iterator & other) const inline
References ug::GPUSparseMatrix< TValueType >::row_iterator::check(), and ug::GPUSparseMatrix< TValueType >::row_iterator::i.
value()
template<typename TValueType > value_type& ug::GPUSparseMatrix< TValueType >::row_iterator::value () inline
References ug::GPUSparseMatrix< TValueType >::row_iterator::A, ug::GPUSparseMatrix< TValueType >::row_iterator::check(), ug::GPUSparseMatrix< TValueType >::row_iterator::i, and ug::GPUSparseMatrix< TValueType >::values.
Member Data Documentation
A
template<typename TValueType > GPUSparseMatrix& ug::GPUSparseMatrix< TValueType >::row_iterator::A private
Referenced by ug::GPUSparseMatrix< TValueType >::row_iterator::check(), ug::GPUSparseMatrix< TValueType >::row_iterator::index(), ug::GPUSparseMatrix< TValueType >::row_iterator::row_iterator(), ug::GPUSparseMatrix< TValueType >::row_iterator::value(), and ug::GPUSparseMatrix< TValueType >::row_iterator::~row_iterator().
i
template<typename TValueType > size_t ug::GPUSparseMatrix< TValueType >::row_iterator::i private
Referenced by ug::GPUSparseMatrix< TValueType >::row_iterator::check(), ug::GPUSparseMatrix< TValueType >::row_iterator::index(), ug::GPUSparseMatrix< TValueType >::row_iterator::operator!=(), ug::GPUSparseMatrix< TValueType >::row_iterator::operator++(), ug::GPUSparseMatrix< TValueType >::row_iterator::operator+=(), ug::GPUSparseMatrix< TValueType >::row_iterator::operator==(), and ug::GPUSparseMatrix< TValueType >::row_iterator::value().
row
template<typename TValueType > size_t ug::GPUSparseMatrix< TValueType >::row_iterator::row private
Referenced by ug::GPUSparseMatrix< TValueType >::row_iterator::check().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/gpu_algebra/gpusparsematrix.h