ug4: ug::PProcessChain< TVector > Class Template Reference
ug::PProcessChain< TVector > Class Template Reference
a chain of pre- or postprocess operations
#include <pprocess.h>
Public Types
typedef IPProcessVector< TVector > p_process_type
typedef TVector vector_type
the vector type
Public Member Functions
void add (SmartPtr< p_process_type > p)
adds an operation at the end of the chain
void apply (vector_type &v)
performs all the operations
SmartPtr< p_process_type > operator[] (size_t i)
returns the operation #i
void remove (SmartPtr< p_process_type > p)
removes an operation from the chain
size_t size ()
returns the number of the operations
Private Attributes
std::vector< SmartPtr< p_process_type > > m_pp_chain
Detailed Description
template<typename TVector>
class ug::PProcessChain< TVector >
a chain of pre- or postprocess operations
A class for storing a chain of pre- or postprocess operations
Template Parameters
TVector the vector type in the algebra
Member Typedef Documentation
p_process_type
template<typename TVector > typedef IPProcessVector<TVector> ug::PProcessChain< TVector >::p_process_type
vector_type
template<typename TVector > typedef TVector ug::PProcessChain< TVector >::vector_type
the vector type
Member Function Documentation
add()
template<typename TVector > void ug::PProcessChain< TVector >::add (SmartPtr< p_process_type > p) inline
adds an operation at the end of the chain
References ug::PProcessChain< TVector >::m_pp_chain, and p.
Referenced by ug::BiCGStab< TVector >::add_postprocess_corr(), ug::CG< TVector >::add_postprocess_corr(), ug::GMRES< TVector >::add_postprocess_corr(), and ug::LinearSolver< TVector >::add_postprocess_corr().
apply()
template<typename TVector > void ug::PProcessChain< TVector >::apply (vector_type & v) inline
performs all the operations
References ug::PProcessChain< TVector >::m_pp_chain, and SmartPtr< T, FreePolicy >::valid().
Referenced by ug::BiCGStab< TVector >::apply_return_defect(), ug::CG< TVector >::apply_return_defect(), ug::GMRES< TVector >::apply_return_defect(), and ug::LinearSolver< TVector >::apply_return_defect().
operator[]()
template<typename TVector > SmartPtr<p_process_type> ug::PProcessChain< TVector >::operator[] (size_t i) inline
returns the operation #i
References ug::PProcessChain< TVector >::m_pp_chain.
remove()
template<typename TVector > void ug::PProcessChain< TVector >::remove (SmartPtr< p_process_type > p) inline
removes an operation from the chain
References boost::get(), ug::PProcessChain< TVector >::m_pp_chain, and p.
Referenced by ug::BiCGStab< TVector >::remove_postprocess_corr(), ug::CG< TVector >::remove_postprocess_corr(), ug::GMRES< TVector >::remove_postprocess_corr(), and ug::LinearSolver< TVector >::remove_postprocess_corr().
size()
template<typename TVector > size_t ug::PProcessChain< TVector >::size () inline
returns the number of the operations
References ug::PProcessChain< TVector >::m_pp_chain.
Member Data Documentation
m_pp_chain
template<typename TVector > std::vector<SmartPtr<p_process_type> > ug::PProcessChain< TVector >::m_pp_chain private
Referenced by ug::PProcessChain< TVector >::add(), ug::PProcessChain< TVector >::apply(), ug::PProcessChain< TVector >::operator[](), ug::PProcessChain< TVector >::remove(), and ug::PProcessChain< TVector >::size().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/interface/pprocess.h