ug4: ug::IElemDisc< TDomain > Class Template Reference
ug::IElemDisc< TDomain > Class Template Reference abstract
lib_discretization » Elem Disc
base class for all element-wise discretizations
#include <elem_disc_interface.h>
Public Types
typedef TDomain domain_type
Domain type.
typedef TDomain::position_type position_type
Position type.
Public Member Functions
virtual void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual Assembling of Defect (Stiffness part)
virtual void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
defect for explicit terms
virtual void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual Assembling of Defect (Mass part)
void add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier)
virtual void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
Assembling of Jacobian (Stiffness part)
virtual void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
Assembling of Jacobian (Mass part)
virtual void add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual Assembling of Right-Hand Side
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
returns approximation space
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
returns approximation space
void check_setup (bool bNonRegularGrid)
checks the setup of the elem disc
void clear_imports ()
removes all imports
virtual void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual compute the error estimator (stiffness part) contribution for one element
virtual void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual compute the error estimator (mass part) contribution for one element
virtual void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual compute the error estimator (rhs part) contribution for one element
SmartPtr< TDomain > domain ()
returns the domain
ConstSmartPtr< TDomain > domain () const
returns the domain
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
returns the pointer to the error estimator data object (or NULL)
bool err_est_enabled () const
find out whether or not a posteriori error estimation is to be performed for this disc
virtual void fsh_elem_loop ()
virtual postprocesses the loop over all elements of one type
virtual void fsh_err_est_elem_loop ()
virtual postprocesses the loop over all elements of one type in the computation of the error estimator
virtual void fsh_timestep (number time, VectorProxyBase *u)
finish the time step
virtual void fsh_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual finish the time step element-wise
const FunctionGroup & function_group () const
returns the current function group
ConstSmartPtr< FunctionPattern > function_pattern () const
returns the current function pattern
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > & get_elem_modifier ()
IDataImport< dim > & get_import (size_t i)
returns an import
IElemDisc (const char *functions="", const char *subsets="")
Constructor.
IElemDisc (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Constructor.
bool is_time_dependent () const
returns if assembling is time-dependent
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
returns the local time solutions
const FunctionIndexMapping & map () const
returns the current function index mapping
size_t num_fct () const
number of functions this discretization handles
size_t num_imports () const
returns number of imports
size_t num_subsets () const
number of subsets this discretization handles
virtual void post_assemble_loop ()
virtual prepares the loop over all elements of one type
virtual void prep_assemble_loop ()
virtual prepares the loop over all elements of one type
virtual void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
virtual prepare one elements for assembling
virtual void prep_elem_loop (const ReferenceObjectID roid, const int si)
virtual prepares the loop over all elements of one type
virtual void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual prepares the loop over all elements of one type for the computation of the error estimator
virtual void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
virtual prepares the loop over all elements of one type for the computation of the error estimator
virtual void prep_timestep (number time, VectorProxyBase *u)
prepare the time step
virtual void prep_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
prepare the time step element-wise
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegularGrid)=0
requests assembling for trial spaces and grid type
void register_import (IDataImport< dim > &Imp)
registers a data import
virtual bool requests_local_time_series ()
returns if local time series needed by assembling
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
sets the approximation space
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
sets the pointer to an error estimator data object (or NULL)
void set_functions (const std::string &functions)
sets functions by name list, divided by ','
void set_functions (const std::vector< std::string > &functions)
sets functions by vector of names
void set_roid (ReferenceObjectID id, int discType)
sets the geometric object type
void set_stationary (bool bStationaryForced=true)
sets that the assembling is always stationary (even in instationary case)
void set_stationary ()
void set_subsets (const std::string &subsets)
sets subset(s) by name list, divided by ','
void set_subsets (const std::vector< std::string > &subsets)
sets subset(s) by name list, divided by ','
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
sets if assembling should be time-dependent and the local time series
void set_time_independent ()
sets that the assembling is time independent
void set_time_point (const size_t timePoint)
sets the current time point
TDomain::subset_handler_type & subset_handler ()
returns the subset handler
const TDomain::subset_handler_type & subset_handler () const
returns the subset handler
const std::vector< std::string > & symb_fcts () const
returns the symbolic functions
const std::vector< std::string > & symb_subsets () const
returns the symbolic subsets
number time () const
returns currently set timepoint
size_t time_point () const
returns the currently considered time point of the time-disc scheme
virtual int type () const
returns the type of elem disc
virtual bool use_hanging () const
returns if discretization acts on hanging nodes if present
virtual ~IElemDisc ()
Virtual destructor.
const std::vector< number > & mass_scales () const
const std::vector< number > & stiff_scales () const
number mass_scale (const size_t timePoint) const
number stiff_scale (const size_t timePoint) const
number mass_scale () const
number stiff_scale () const
void do_prep_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_fsh_elem_loop ()
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_err_est_elem_loop ()
Static Public Attributes
static const int dim = TDomain::dim
World dimension.
Protected Member Functions
virtual void approximation_space_changed ()
callback invoked, when approximation space is changed
void clear_add_fct (ReferenceObjectID id)
sets all assemble functions to NULL for a given ReferenceObjectID
void clear_add_fct ()
sets all assemble functions to NULL (for all ReferenceObjectID's)
void remove_add_def_A_elem_fct (ReferenceObjectID id)
void remove_add_def_A_expl_elem_fct (ReferenceObjectID id)
void remove_add_def_M_elem_fct (ReferenceObjectID id)
void remove_add_jac_A_elem_fct (ReferenceObjectID id)
void remove_add_jac_M_elem_fct (ReferenceObjectID id)
void remove_add_rhs_elem_fct (ReferenceObjectID id)
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_elem_loop_fct (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_fsh_timestep_elem_fct (ReferenceObjectID id)
void remove_fsh_timestep_fct (size_t algebra_id)
void remove_prep_elem_fct (ReferenceObjectID id)
void remove_prep_elem_loop_fct (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_timestep_elem_fct (ReferenceObjectID id)
void remove_prep_timestep_fct (size_t algebra_id)
template<typename TAssFunc >
void set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
sets all assemble functions to the corresponding virtual ones
template<typename TAssFunc >
void set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_fsh_timestep_fct (size_t algebra_id, TAssFunc func)
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
sets current function pattern
template<typename TAssFunc >
void set_prep_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
template<typename TAssFunc >
void set_prep_timestep_fct (size_t algebra_id, TAssFunc func)
void update_function_index_mapping ()
updates the function index mapping
Protected Attributes
bool m_bStationaryForced
flag if stationary assembling is to be used even in instationary assembling
FunctionGroup m_fctGrp
current function group
FunctionIndexMapping m_fctIndexMap
current function index mapping
ReferenceObjectID m_id
current Geometric Object
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
list of local vectors for all solutions of the time series
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
Approximation Space.
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > m_spElemModifier
Approximation Space.
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
error estimation object associated to the element discretization
ConstSmartPtr< FunctionPattern > m_spFctPattern
current function pattern
size_t m_timePoint
time point
std::vector< std::string > m_vFct
vector holding name of all symbolic functions
std::vector< IDataImport< dim > * > m_vIImport
data imports
std::vector< std::string > m_vSubset
vector holding name of all symbolic subsets
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
Private Types
typedef void(T::* ElemComputeErrEstAFct) (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &)
typedef void(T::* ElemComputeErrEstMFct) (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &)
typedef void(T::* ElemComputeErrEstRhsFct) (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &)
typedef void(T::* ElemdAFct) (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
typedef void(T::* ElemdMFct) (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
typedef void(T::* ElemJAFct) (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
typedef void(T::* ElemJMFct) (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
typedef void(T::* ElemRHSFct) (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
typedef void(T::* FinishElemLoopFct) ()
typedef void(T::* FinishErrEstElemLoopFct) ()
typedef void(T::* FinishTimestepElemFct) (number, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
typedef void(T::* FinishTimestepFct) (number, VectorProxyBase *)
typedef void(T::* PrepareElemFct) (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
typedef void(T::* PrepareElemLoopFct) (ReferenceObjectID roid, int si)
typedef void(T::* PrepareErrEstElemFct) (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
typedef void(T::* PrepareErrEstElemLoopFct) (ReferenceObjectID roid, int si)
typedef void(T::* PrepareTimestepElemFct) (number, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
typedef void(T::* PrepareTimestepFct) (number, VectorProxyBase *)
typedef IElemDisc< TDomain > T
Private Attributes
bool m_bDoErrEst
flag indicating whether or not a posteriori error estimation is to be performed for this disc
ElemComputeErrEstAFct m_vElemComputeErrEstAFct [NUM_REFERENCE_OBJECTS]
ElemComputeErrEstMFct m_vElemComputeErrEstMFct [NUM_REFERENCE_OBJECTS]
ElemComputeErrEstRhsFct m_vElemComputeErrEstRhsFct [NUM_REFERENCE_OBJECTS]
ElemdAFct m_vElemdAExplFct [NUM_REFERENCE_OBJECTS]
ElemdAFct m_vElemdAFct [NUM_REFERENCE_OBJECTS]
ElemdMFct m_vElemdMFct [NUM_REFERENCE_OBJECTS]
ElemJAFct m_vElemJAFct [NUM_REFERENCE_OBJECTS]
ElemJMFct m_vElemJMFct [NUM_REFERENCE_OBJECTS]
ElemRHSFct m_vElemRHSFct [NUM_REFERENCE_OBJECTS]
FinishElemLoopFct m_vFinishElemLoopFct [NUM_REFERENCE_OBJECTS]
FinishErrEstElemLoopFct m_vFinishErrEstElemLoopFct [NUM_REFERENCE_OBJECTS]
FinishTimestepElemFct m_vFinishTimestepElemFct [NUM_REFERENCE_OBJECTS]
FinishTimestepFct m_vFinishTimestepFct [bridge::NUM_ALGEBRA_TYPES]
PrepareElemFct m_vPrepareElemFct [NUM_REFERENCE_OBJECTS]
PrepareElemLoopFct m_vPrepareElemLoopFct [NUM_REFERENCE_OBJECTS]
PrepareErrEstElemFct m_vPrepareErrEstElemFct [NUM_REFERENCE_OBJECTS]
PrepareErrEstElemLoopFct m_vPrepareErrEstElemLoopFct [NUM_REFERENCE_OBJECTS]
PrepareTimestepElemFct m_vPrepareTimestepElemFct [NUM_REFERENCE_OBJECTS]
PrepareTimestepFct m_vPrepareTimestepFct [bridge::NUM_ALGEBRA_TYPES]
Detailed Description
template<typename TDomain>
class ug::IElemDisc< TDomain >
base class for all element-wise discretizations
This class is the base class for element-wise discretizations. An implementation of this class must provide local stiffness/mass-matrix contribution of one element to the global jacobian and local contributions of one element to the local defect.
Member Typedef Documentation
template<typename TDomain> typedef TDomain ug::IElemDisc< TDomain >::domain_type
Domain type.
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::ElemComputeErrEstAFct) (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::ElemComputeErrEstMFct) (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::ElemComputeErrEstRhsFct) (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::ElemdAFct) (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[]) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::ElemdMFct) (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[]) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::ElemJAFct) (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[]) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::ElemJMFct) (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[]) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::ElemRHSFct) (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[]) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::FinishElemLoopFct) () private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::FinishErrEstElemLoopFct) () private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::FinishTimestepElemFct) (number, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[]) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::FinishTimestepFct) (number, VectorProxyBase *) private
template<typename TDomain> typedef TDomain::position_type ug::IElemDisc< TDomain >::position_type
Position type.
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::PrepareElemFct) (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[]) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::PrepareElemLoopFct) (ReferenceObjectID roid, int si) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::PrepareErrEstElemFct) (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[]) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::PrepareErrEstElemLoopFct) (ReferenceObjectID roid, int si) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::PrepareTimestepElemFct) (number, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[]) private
template<typename TDomain> typedef void(T::* ug::IElemDisc< TDomain >::PrepareTimestepFct) (number, VectorProxyBase *) private
template<typename TDomain> typedef IElemDisc<TDomain> ug::IElemDisc< TDomain >::T private
Constructor & Destructor Documentation
template<typename TDomain > ug::IElemDisc< TDomain >::IElemDisc (const char * functions = "", const char * subsets = "")
Constructor.
References ug::IElemDisc< TDomain >::set_default_add_fct(), ug::IElemDisc< TDomain >::set_functions(), and ug::IElemDisc< TDomain >::set_subsets().
template<typename TDomain > ug::IElemDisc< TDomain >::IElemDisc (const std::vector< std::string > & vFct, const std::vector< std::string > & vSubset)
Constructor.
References ug::IElemDisc< TDomain >::set_approximation_space(), ug::IElemDisc< TDomain >::set_default_add_fct(), ug::IElemDisc< TDomain >::set_functions(), and ug::IElemDisc< TDomain >::set_subsets().
template<typename TDomain> virtual ug::IElemDisc< TDomain >::~IElemDisc () inline virtual
Virtual destructor.
Member Function Documentation
template<typename TDomain > void ug::IElemDisc< TDomain >::add_def_A_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) virtual
virtual Assembling of Defect (Stiffness part)
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryBase< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFVCR< TDomain >, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::add_def_A_expl_elem(), ug::GridObject::reference_object_id(), and ug::ThrowMissingVirtualMethod().
Referenced by ug::IElemDisc< TDomain >::add_jac_M_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::add_def_A_expl_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) virtual
defect for explicit terms
Reimplemented in ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >.
References ug::IElemDisc< TDomain >::add_def_M_elem().
Referenced by ug::IElemDisc< TDomain >::add_def_A_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::add_def_M_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) virtual
virtual Assembling of Defect (Mass part)
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryBase< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFVCR< TDomain >, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::add_rhs_elem(), ug::GridObject::reference_object_id(), and ug::ThrowMissingVirtualMethod().
Referenced by ug::IElemDisc< TDomain >::add_def_A_expl_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> void ug::IElemDisc< TDomain >::add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier) inline
template<typename TDomain > void ug::IElemDisc< TDomain >::add_jac_A_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) virtual
Assembling of Jacobian (Stiffness part)
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryBase< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFVCR< TDomain >, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::add_jac_M_elem(), ug::GridObject::reference_object_id(), and ug::ThrowMissingVirtualMethod().
Referenced by ug::IElemDisc< TDomain >::fsh_elem_loop(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::add_jac_M_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) virtual
Assembling of Jacobian (Mass part)
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryBase< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFVCR< TDomain >, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::add_def_A_elem(), ug::GridObject::reference_object_id(), and ug::ThrowMissingVirtualMethod().
Referenced by ug::IElemDisc< TDomain >::add_jac_A_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::add_rhs_elem (LocalVector & rhs, GridObject * elem, const MathVector< dim > vCornerCoords[]) virtual
virtual Assembling of Right-Hand Side
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryFV1< TDomain >, ug::NeumannBoundaryFV< TDomain >, ug::NeumannBoundaryFE< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFVCR< TDomain >, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::prep_err_est_elem_loop(), ug::GridObject::reference_object_id(), and ug::ThrowMissingVirtualMethod().
Referenced by ug::IElemDisc< TDomain >::add_def_M_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> SmartPtr<ApproximationSpace<TDomain> > ug::IElemDisc< TDomain >::approx_space () inline
returns approximation space
Referenced by ug::NeumannBoundaryBase< TDomain >::update_subset_groups().
template<typename TDomain> ConstSmartPtr<ApproximationSpace<TDomain> > ug::IElemDisc< TDomain >::approx_space () const inline
returns approximation space
template<typename TDomain> virtual void ug::IElemDisc< TDomain >::approximation_space_changed () inline protected virtual
callback invoked, when approximation space is changed
Referenced by ug::IElemDisc< TDomain >::set_approximation_space().
template<typename TDomain > void ug::IElemDisc< TDomain >::check_setup (bool bNonRegularGrid)
checks the setup of the elem disc
References ug::FunctionGroup::local_finite_element_id(), ug::IElemDisc< TDomain >::m_fctGrp, ug::IElemDisc< TDomain >::m_spFctPattern, ug::IElemDisc< TDomain >::m_vSubset, ug::IElemDisc< TDomain >::prepare_setting(), ug::FunctionGroup::size(), ug::IElemDisc< TDomain >::symb_fcts(), ug::IElemDisc< TDomain >::symb_subsets(), and UG_LOG.
Referenced by ug::DataEvaluator< TDomain >::DataEvaluator().
template<typename TDomain > void ug::IElemDisc< TDomain >::clear_add_fct (ReferenceObjectID id) protected
sets all assemble functions to NULL for a given ReferenceObjectID
References ug::IElemDisc< TDomain >::m_vElemComputeErrEstAFct, ug::IElemDisc< TDomain >::m_vElemComputeErrEstMFct, ug::IElemDisc< TDomain >::m_vElemComputeErrEstRhsFct, ug::IElemDisc< TDomain >::m_vElemdAExplFct, ug::IElemDisc< TDomain >::m_vElemdAFct, ug::IElemDisc< TDomain >::m_vElemdMFct, ug::IElemDisc< TDomain >::m_vElemJAFct, ug::IElemDisc< TDomain >::m_vElemJMFct, ug::IElemDisc< TDomain >::m_vElemRHSFct, ug::IElemDisc< TDomain >::m_vFinishElemLoopFct, ug::IElemDisc< TDomain >::m_vFinishErrEstElemLoopFct, ug::IElemDisc< TDomain >::m_vFinishTimestepElemFct, ug::IElemDisc< TDomain >::m_vPrepareElemFct, ug::IElemDisc< TDomain >::m_vPrepareElemLoopFct, ug::IElemDisc< TDomain >::m_vPrepareErrEstElemFct, ug::IElemDisc< TDomain >::m_vPrepareErrEstElemLoopFct, and ug::IElemDisc< TDomain >::m_vPrepareTimestepElemFct.
template<typename TDomain > void ug::IElemDisc< TDomain >::clear_add_fct () protected
sets all assemble functions to NULL (for all ReferenceObjectID's)
References ug::IElemDisc< TDomain >::m_vFinishTimestepFct, ug::IElemDisc< TDomain >::m_vPrepareTimestepFct, ug::bridge::NUM_ALGEBRA_TYPES, and ug::NUM_REFERENCE_OBJECTS.
Referenced by ug::NeumannBoundaryFE< TDomain >::NeumannBoundaryFE(), ug::NeumannBoundaryFE< TDomain >::register_func(), ug::NeumannBoundaryFV< TDomain >::register_func(), and ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain> void ug::IElemDisc< TDomain >::clear_imports () inline
removes all imports
Referenced by ug::NeumannBoundaryFE< TDomain >::prep_elem_loop(), ug::NeumannBoundaryFV< TDomain >::prep_elem_loop(), ug::NeumannBoundaryFV1< TDomain >::prep_elem_loop(), and ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem_loop().
template<typename TDomain > void ug::IElemDisc< TDomain >::compute_err_est_A_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) virtual
virtual compute the error estimator (stiffness part) contribution for one element
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >.
References ug::IElemDisc< TDomain >::compute_err_est_M_elem().
Referenced by ug::IElemDisc< TDomain >::prep_err_est_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::compute_err_est_M_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) virtual
virtual compute the error estimator (mass part) contribution for one element
Reimplemented in ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >.
References ug::IElemDisc< TDomain >::compute_err_est_rhs_elem().
Referenced by ug::IElemDisc< TDomain >::compute_err_est_A_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::compute_err_est_rhs_elem (GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) virtual
virtual compute the error estimator (rhs part) contribution for one element
Reimplemented in ug::NeumannBoundaryFV1< TDomain >, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >.
References ug::IElemDisc< TDomain >::fsh_err_est_elem_loop().
Referenced by ug::IElemDisc< TDomain >::compute_err_est_M_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_add_def_A_elem (LocalVector & d, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::IElemDisc< TDomain >::do_add_def_A_expl_elem(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vElemdAFct, ug::IElemDisc< TDomain >::map(), and UG_ASSERT.
Referenced by ug::IElemDisc< TDomain >::do_add_jac_M_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_add_def_A_expl_elem (LocalVector & d, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::IElemDisc< TDomain >::do_add_def_M_elem(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vElemdAExplFct, and ug::IElemDisc< TDomain >::map().
Referenced by ug::IElemDisc< TDomain >::do_add_def_A_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_add_def_M_elem (LocalVector & d, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::IElemDisc< TDomain >::do_add_rhs_elem(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_bStationaryForced, ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vElemdMFct, ug::IElemDisc< TDomain >::map(), and UG_ASSERT.
Referenced by ug::IElemDisc< TDomain >::do_add_def_A_expl_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_add_jac_A_elem (LocalMatrix & J, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::LocalMatrix::access_by_map(), ug::IElemDisc< TDomain >::do_add_jac_M_elem(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vElemJAFct, ug::IElemDisc< TDomain >::map(), and UG_ASSERT.
Referenced by ug::IElemDisc< TDomain >::do_fsh_elem_loop().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_add_jac_M_elem (LocalMatrix & J, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::LocalMatrix::access_by_map(), ug::IElemDisc< TDomain >::do_add_def_A_elem(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_bStationaryForced, ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vElemJMFct, ug::IElemDisc< TDomain >::map(), and UG_ASSERT.
Referenced by ug::IElemDisc< TDomain >::do_add_jac_A_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_add_rhs_elem (LocalVector & rhs, GridObject * elem, const MathVector< dim > vCornerCoords[])
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::IElemDisc< TDomain >::do_prep_err_est_elem_loop(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vElemRHSFct, ug::IElemDisc< TDomain >::map(), and UG_ASSERT.
Referenced by ug::IElemDisc< TDomain >::do_add_def_M_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_compute_err_est_A_elem (LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale)
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::IElemDisc< TDomain >::do_compute_err_est_M_elem(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vElemComputeErrEstAFct, and ug::IElemDisc< TDomain >::map().
Referenced by ug::IElemDisc< TDomain >::do_prep_err_est_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_compute_err_est_M_elem (LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale)
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::IElemDisc< TDomain >::do_compute_err_est_rhs_elem(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vElemComputeErrEstMFct, and ug::IElemDisc< TDomain >::map().
Referenced by ug::IElemDisc< TDomain >::do_compute_err_est_A_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_compute_err_est_rhs_elem (GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale)
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::IElemDisc< TDomain >::do_fsh_err_est_elem_loop(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vElemComputeErrEstRhsFct, and ug::IElemDisc< TDomain >::map().
Referenced by ug::IElemDisc< TDomain >::do_compute_err_est_M_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_fsh_elem_loop ()
function dispatching call to implementation
References ug::IElemDisc< TDomain >::do_add_jac_A_elem(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_vFinishElemLoopFct, ug::IElemDisc< TDomain >::m_vIImport, and UG_ASSERT.
Referenced by ug::IElemDisc< TDomain >::do_prep_elem_loop().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_fsh_err_est_elem_loop ()
function dispatching call to implementation
References ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_vFinishErrEstElemLoopFct, and ug::IElemDisc< TDomain >::m_vIImport.
Referenced by ug::IElemDisc< TDomain >::do_compute_err_est_rhs_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_fsh_timestep (const number time, VectorProxyBase * u, size_t algebra_id)
function dispatching call to implementation
References ug::IElemDisc< TDomain >::do_fsh_timestep_elem(), ug::IElemDisc< TDomain >::m_vFinishTimestepFct, and ug::IElemDisc< TDomain >::time().
Referenced by ug::IElemDisc< TDomain >::do_prep_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_fsh_timestep_elem (const number time, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::IElemDisc< TDomain >::do_prep_elem_loop(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vFinishTimestepElemFct, ug::IElemDisc< TDomain >::map(), and ug::IElemDisc< TDomain >::time().
Referenced by ug::IElemDisc< TDomain >::do_fsh_timestep().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_prep_elem (LocalVector & u, GridObject * elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::IElemDisc< TDomain >::do_fsh_timestep(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vPrepareElemFct, ug::IElemDisc< TDomain >::map(), and UG_ASSERT.
Referenced by ug::IElemDisc< TDomain >::do_prep_timestep_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_prep_elem_loop (const ReferenceObjectID roid, const int si)
function dispatching call to implementation
References ug::IElemDisc< TDomain >::do_fsh_elem_loop(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_vIImport, ug::IElemDisc< TDomain >::m_vPrepareElemLoopFct, ug::IElemDisc< TDomain >::set_roid(), and UG_ASSERT.
Referenced by ug::IElemDisc< TDomain >::do_fsh_timestep_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_prep_err_est_elem (LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::IElemDisc< TDomain >::do_compute_err_est_A_elem(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vPrepareErrEstElemFct, ug::IElemDisc< TDomain >::map(), and UG_ASSERT.
Referenced by ug::IElemDisc< TDomain >::do_prep_err_est_elem_loop().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
function dispatching call to implementation
References ug::IElemDisc< TDomain >::do_prep_err_est_elem(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_vIImport, ug::IElemDisc< TDomain >::m_vPrepareErrEstElemLoopFct, ug::IElemDisc< TDomain >::set_roid(), and UG_ASSERT.
Referenced by ug::IElemDisc< TDomain >::do_add_rhs_elem().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_prep_timestep (const number time, VectorProxyBase * u, size_t algebra_id)
function dispatching call to implementation
References ug::IElemDisc< TDomain >::do_prep_timestep_elem(), ug::IElemDisc< TDomain >::m_vPrepareTimestepFct, and ug::IElemDisc< TDomain >::time().
Referenced by ug::IElemDisc< TDomain >::set_time_independent().
template<typename TDomain > void ug::IElemDisc< TDomain >::do_prep_timestep_elem (const number time, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
function dispatching call to implementation
References ug::LocalVectorTimeSeries::access_by_map(), ug::LocalVector::access_by_map(), ug::IElemDisc< TDomain >::do_prep_elem(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vPrepareTimestepElemFct, ug::IElemDisc< TDomain >::map(), and ug::IElemDisc< TDomain >::time().
Referenced by ug::IElemDisc< TDomain >::do_prep_timestep().
template<typename TDomain> SmartPtr<TDomain> ug::IElemDisc< TDomain >::domain () inline
returns the domain
template<typename TDomain> ConstSmartPtr<TDomain> ug::IElemDisc< TDomain >::domain () const inline
returns the domain
template<typename TDomain> virtual SmartPtr<IErrEstData<TDomain> > ug::IElemDisc< TDomain >::err_est_data () inline virtual
returns the pointer to the error estimator data object (or NULL)
Referenced by ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem(), and ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem_loop().
template<typename TDomain> bool ug::IElemDisc< TDomain >::err_est_enabled () const inline
find out whether or not a posteriori error estimation is to be performed for this disc
template<typename TDomain > void ug::IElemDisc< TDomain >::fsh_elem_loop () virtual
virtual postprocesses the loop over all elements of one type
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryFV1< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFVCR< TDomain >, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::add_jac_A_elem(), and ug::ThrowMissingVirtualMethod().
Referenced by ug::IElemDisc< TDomain >::prep_elem_loop(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::fsh_err_est_elem_loop () virtual
virtual postprocesses the loop over all elements of one type in the computation of the error estimator
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryFV1< TDomain >, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >.
Referenced by ug::IElemDisc< TDomain >::compute_err_est_rhs_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::fsh_timestep (number time, VectorProxyBase * u) virtual
finish the time step
References ug::IElemDisc< TDomain >::fsh_timestep_elem().
Referenced by ug::IElemDisc< TDomain >::prep_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::fsh_timestep_elem (const number time, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) virtual
virtual finish the time step element-wise
Reimplemented in ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::prep_elem_loop().
Referenced by ug::IElemDisc< TDomain >::fsh_timestep(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> const FunctionGroup& ug::IElemDisc< TDomain >::function_group () const inline
returns the current function group
template<typename TDomain> ConstSmartPtr<FunctionPattern> ug::IElemDisc< TDomain >::function_pattern () const inline
returns the current function pattern
template<typename TDomain> std::vector<SmartPtr<IElemDiscModifier<TDomain> > >& ug::IElemDisc< TDomain >::get_elem_modifier () inline
template<typename TDomain> IDataImport<dim>& ug::IElemDisc< TDomain >::get_import (size_t i) inline
returns an import
References UG_ASSERT.
Referenced by ug::DataEvaluator< TDomain >::extract_imports_and_userdata().
template<typename TDomain> bool ug::IElemDisc< TDomain >::is_time_dependent () const inline
returns if assembling is time-dependent
Referenced by ug::DataEvaluator< TDomain >::DataEvaluator(), and ug::DataEvaluator< TDomain >::extract_imports_and_userdata().
template<typename TDomain> bool ug::IElemDisc< TDomain >::local_time_series_needed () inline
Referenced by ug::DataEvaluator< TDomain >::DataEvaluator(), ug::IElemDisc< TDomain >::do_add_def_A_elem(), ug::IElemDisc< TDomain >::do_add_def_A_expl_elem(), ug::IElemDisc< TDomain >::do_add_def_M_elem(), ug::IElemDisc< TDomain >::do_add_jac_A_elem(), ug::IElemDisc< TDomain >::do_add_jac_M_elem(), ug::IElemDisc< TDomain >::do_add_rhs_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_A_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_M_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_rhs_elem(), ug::IElemDisc< TDomain >::do_fsh_timestep_elem(), ug::IElemDisc< TDomain >::do_prep_elem(), ug::IElemDisc< TDomain >::do_prep_err_est_elem(), and ug::IElemDisc< TDomain >::do_prep_timestep_elem().
template<typename TDomain> const LocalVectorTimeSeries* ug::IElemDisc< TDomain >::local_time_solutions () const inline
returns the local time solutions
This function returns the local time solutions. This a type of vector, that holds the local unknowns for each time point of a time series. Note, that the first sol is always the current (iterated, unknown) time point, while all remaining sols are the already computed time steps used e.g. in a time stepping scheme.
Returns
vLocalTimeSol vector of local time Solutions
template<typename TDomain> const FunctionIndexMapping& ug::IElemDisc< TDomain >::map () const inline
returns the current function index mapping
Referenced by ug::IElemDisc< TDomain >::do_add_def_A_elem(), ug::IElemDisc< TDomain >::do_add_def_A_expl_elem(), ug::IElemDisc< TDomain >::do_add_def_M_elem(), ug::IElemDisc< TDomain >::do_add_jac_A_elem(), ug::IElemDisc< TDomain >::do_add_jac_M_elem(), ug::IElemDisc< TDomain >::do_add_rhs_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_A_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_M_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_rhs_elem(), ug::IElemDisc< TDomain >::do_fsh_timestep_elem(), ug::IElemDisc< TDomain >::do_prep_elem(), ug::IElemDisc< TDomain >::do_prep_err_est_elem(), and ug::IElemDisc< TDomain >::do_prep_timestep_elem().
template<typename TDomain> number ug::IElemDisc< TDomain >::mass_scale (const size_t timePoint) const inline
returns the weight factors of the time-disc scheme
template<typename TDomain> number ug::IElemDisc< TDomain >::mass_scale () const inline
returns the weight factors of the time-disc scheme
template<typename TDomain> const std::vector<number>& ug::IElemDisc< TDomain >::mass_scales () const inline
returns the weight factors of the time-disc scheme
template<typename TDomain> size_t ug::IElemDisc< TDomain >::num_fct () const inline
number of functions this discretization handles
Referenced by ug::NeumannBoundaryBase< TDomain >::NeumannBoundaryBase().
template<typename TDomain> size_t ug::IElemDisc< TDomain >::num_imports () const inline
returns number of imports
Referenced by ug::DataEvaluator< TDomain >::extract_imports_and_userdata().
template<typename TDomain> size_t ug::IElemDisc< TDomain >::num_subsets () const inline
number of subsets this discretization handles
template<typename TDomain> virtual void ug::IElemDisc< TDomain >::post_assemble_loop () inline virtual
virtual prepares the loop over all elements of one type
template<typename TDomain> virtual void ug::IElemDisc< TDomain >::prep_assemble_loop () inline virtual
virtual prepares the loop over all elements of one type
Reimplemented in ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >.
template<typename TDomain > void ug::IElemDisc< TDomain >::prep_elem (const LocalVector & u, GridObject * elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[]) virtual
virtual prepare one elements for assembling
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryFV1< TDomain >, ug::NeumannBoundaryFV< TDomain >, ug::NeumannBoundaryFE< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFVCR< TDomain >, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::fsh_timestep(), ug::GridObject::reference_object_id(), and ug::ThrowMissingVirtualMethod().
Referenced by ug::IElemDisc< TDomain >::prep_timestep_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::prep_elem_loop (const ReferenceObjectID roid, const int si) virtual
virtual prepares the loop over all elements of one type
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryFV1< TDomain >, ug::NeumannBoundaryFV< TDomain >, ug::NeumannBoundaryFE< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFVCR< TDomain >, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::fsh_elem_loop(), and ug::ThrowMissingVirtualMethod().
Referenced by ug::IElemDisc< TDomain >::fsh_timestep_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::prep_err_est_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) virtual
virtual prepares the loop over all elements of one type for the computation of the error estimator
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryFV1< TDomain >, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >.
References ug::IElemDisc< TDomain >::compute_err_est_A_elem().
Referenced by ug::IElemDisc< TDomain >::prep_err_est_elem_loop(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::prep_err_est_elem_loop (const ReferenceObjectID roid, const int si) virtual
virtual prepares the loop over all elements of one type for the computation of the error estimator
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryFV1< TDomain >, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >.
References ug::IElemDisc< TDomain >::prep_err_est_elem().
Referenced by ug::IElemDisc< TDomain >::add_rhs_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain > void ug::IElemDisc< TDomain >::prep_timestep (number time, VectorProxyBase * u) virtual
prepare the time step
References ug::IElemDisc< TDomain >::prep_timestep_elem().
Referenced by ug::IElemDisc< TDomain >::set_default_add_fct(), and ug::ThrowMissingVirtualMethod().
template<typename TDomain > void ug::IElemDisc< TDomain >::prep_timestep_elem (const number time, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) virtual
prepare the time step element-wise
Reimplemented in ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >.
References ug::IElemDisc< TDomain >::prep_elem().
Referenced by ug::IElemDisc< TDomain >::prep_timestep(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> virtual void ug::IElemDisc< TDomain >::prepare_setting (const std::vector< LFEID > & vLfeID, bool bNonRegularGrid) pure virtual
requests assembling for trial spaces and grid type
This function is called before the assembling starts. The IElemDisc-Implementation is supposed to checks if it can assemble the set of LFEID and the grid type. It may register corresponding assembling functions or perform other initialization. If the ElemDisc does not support the setting it should throw an exception.
Parameters
[in] vLfeID vector of Local Finite Element IDs
[in] bNonRegularGrid regular grid type
Implemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::NeumannBoundaryFV1< TDomain >, ug::NeumannBoundaryFV< TDomain >, ug::NeumannBoundaryFE< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFVCR< TDomain >, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >.
Referenced by ug::IElemDisc< TDomain >::check_setup().
template<typename TDomain > void ug::IElemDisc< TDomain >::register_import (IDataImport< dim > & Imp)
registers a data import
References ug::IElemDisc< TDomain >::m_vIImport, UG_THROW, and ug::IElemDisc< TDomain >::update_function_index_mapping().
Referenced by ug::NeumannBoundaryFE< TDomain >::prep_elem_loop(), ug::NeumannBoundaryFV< TDomain >::prep_elem_loop(), ug::NeumannBoundaryFV1< TDomain >::prep_elem_loop(), and ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem_loop().
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_add_def_A_elem_fct (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_add_def_A_expl_elem_fct (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_add_def_M_elem_fct (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_add_jac_A_elem_fct (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_add_jac_M_elem_fct (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_add_rhs_elem_fct (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_compute_err_est_A_elem (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_compute_err_est_M_elem (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_compute_err_est_rhs_elem (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_fsh_elem_loop_fct (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_fsh_err_est_elem_loop (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_fsh_timestep_elem_fct (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_fsh_timestep_fct (size_t algebra_id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_prep_elem_fct (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_prep_elem_loop_fct (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_prep_err_est_elem (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_prep_err_est_elem_loop (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_prep_timestep_elem_fct (ReferenceObjectID id) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::remove_prep_timestep_fct (size_t algebra_id) protected
template<typename TDomain> virtual bool ug::IElemDisc< TDomain >::requests_local_time_series () inline virtual
returns if local time series needed by assembling
This callback must be implemented by a derived Elem Disc in order to handle time-dependent data. As return the derived Elem Disc can specify, if it really needs data from previous time steps for the (spatial) disc. The default is false.
Returns
if elem disc needs time series local solutions
Reimplemented in ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >.
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFE< TDomain >::register_func(), ug::NeumannBoundaryFV< TDomain >::register_func(), and ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func) protected
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFE< TDomain >::register_func(), ug::NeumannBoundaryFV< TDomain >::register_func(), and ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFE< TDomain >::register_func(), ug::NeumannBoundaryFV< TDomain >::register_func(), and ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFE< TDomain >::register_func(), ug::NeumannBoundaryFV< TDomain >::register_func(), and ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFE< TDomain >::register_func(), ug::NeumannBoundaryFV< TDomain >::register_func(), and ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > void ug::IElemDisc< TDomain >::set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
sets the approximation space
Calls protected virtual 'approximation_space_changed', when a new approximation space has been set. Note that 'approximation_space_changed' is only called once if the same approximation space is set multiple times.
References ug::IElemDisc< TDomain >::approximation_space_changed(), ug::IElemDisc< TDomain >::m_spApproxSpace, and ug::IElemDisc< TDomain >::set_function_pattern().
Referenced by ug::IElemDisc< TDomain >::IElemDisc().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func) protected
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func) protected
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > void ug::IElemDisc< TDomain >::set_default_add_fct () protected
sets all assemble functions to the corresponding virtual ones
References ug::IElemDisc< TDomain >::add_def_A_elem(), ug::IElemDisc< TDomain >::add_def_A_expl_elem(), ug::IElemDisc< TDomain >::add_def_M_elem(), ug::IElemDisc< TDomain >::add_jac_A_elem(), ug::IElemDisc< TDomain >::add_jac_M_elem(), ug::IElemDisc< TDomain >::add_rhs_elem(), ug::IElemDisc< TDomain >::compute_err_est_A_elem(), ug::IElemDisc< TDomain >::compute_err_est_M_elem(), ug::IElemDisc< TDomain >::compute_err_est_rhs_elem(), ug::IElemDisc< TDomain >::fsh_elem_loop(), ug::IElemDisc< TDomain >::fsh_err_est_elem_loop(), ug::IElemDisc< TDomain >::fsh_timestep(), ug::IElemDisc< TDomain >::fsh_timestep_elem(), ug::IElemDisc< TDomain >::m_vElemComputeErrEstAFct, ug::IElemDisc< TDomain >::m_vElemComputeErrEstMFct, ug::IElemDisc< TDomain >::m_vElemComputeErrEstRhsFct, ug::IElemDisc< TDomain >::m_vElemdAExplFct, ug::IElemDisc< TDomain >::m_vElemdAFct, ug::IElemDisc< TDomain >::m_vElemdMFct, ug::IElemDisc< TDomain >::m_vElemJAFct, ug::IElemDisc< TDomain >::m_vElemJMFct, ug::IElemDisc< TDomain >::m_vElemRHSFct, ug::IElemDisc< TDomain >::m_vFinishElemLoopFct, ug::IElemDisc< TDomain >::m_vFinishErrEstElemLoopFct, ug::IElemDisc< TDomain >::m_vFinishTimestepElemFct, ug::IElemDisc< TDomain >::m_vFinishTimestepFct, ug::IElemDisc< TDomain >::m_vPrepareElemFct, ug::IElemDisc< TDomain >::m_vPrepareElemLoopFct, ug::IElemDisc< TDomain >::m_vPrepareErrEstElemFct, ug::IElemDisc< TDomain >::m_vPrepareErrEstElemLoopFct, ug::IElemDisc< TDomain >::m_vPrepareTimestepElemFct, ug::IElemDisc< TDomain >::m_vPrepareTimestepFct, ug::bridge::NUM_ALGEBRA_TYPES, ug::NUM_REFERENCE_OBJECTS, ug::IElemDisc< TDomain >::prep_elem(), ug::IElemDisc< TDomain >::prep_elem_loop(), ug::IElemDisc< TDomain >::prep_err_est_elem(), ug::IElemDisc< TDomain >::prep_err_est_elem_loop(), ug::IElemDisc< TDomain >::prep_timestep(), and ug::IElemDisc< TDomain >::prep_timestep_elem().
Referenced by ug::IElemDisc< TDomain >::IElemDisc().
template<typename TDomain> void ug::IElemDisc< TDomain >::set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee) inline
sets the pointer to an error estimator data object (or NULL)
This function sets the pointer to an error estimator data object that should be used for this discretization. Note that the ElemDisc object must use RTTI to try to convert this pointer to the type of the objects accepted by it for this purpose. If the conversion fails than an exception must be thrown since this situation is not allowed.
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFE< TDomain >::register_func(), ug::NeumannBoundaryFV< TDomain >::register_func(), and ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func) protected
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_fsh_timestep_fct (size_t algebra_id, TAssFunc func) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt) protected
sets current function pattern
References ug::IElemDisc< TDomain >::m_spFctPattern, and ug::IElemDisc< TDomain >::update_function_index_mapping().
Referenced by ug::IElemDisc< TDomain >::set_approximation_space().
template<typename TDomain > void ug::IElemDisc< TDomain >::set_functions (const std::string & functions)
sets functions by name list, divided by ','
References ug::TokenizeString().
Referenced by ug::IElemDisc< TDomain >::IElemDisc().
template<typename TDomain > void ug::IElemDisc< TDomain >::set_functions (const std::vector< std::string > & functions)
sets functions by vector of names
References ug::IElemDisc< TDomain >::m_vFct, ug::RemoveWhitespaceFromString(), UG_THROW, and ug::IElemDisc< TDomain >::update_function_index_mapping().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_prep_elem_fct (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFE< TDomain >::register_func(), ug::NeumannBoundaryFV< TDomain >::register_func(), and ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFE< TDomain >::register_func(), ug::NeumannBoundaryFV< TDomain >::register_func(), and ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func) protected
Referenced by ug::NeumannBoundaryFV1< TDomain >::register_func().
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func) protected
template<typename TDomain > template<typename TAssFunc > void ug::IElemDisc< TDomain >::set_prep_timestep_fct (size_t algebra_id, TAssFunc func) protected
template<typename TDomain > void ug::IElemDisc< TDomain >::set_roid (ReferenceObjectID id, int discType)
sets the geometric object type
This functions set the geometric object type of the object, that is assembled next. The user has to call this function before most of the assembling routines can be called. Keep in mind, that the elements are looped type by type, thus this function has to be called very few times.
References ug::IElemDisc< TDomain >::dim, ug::IElemDisc< TDomain >::m_id, ug::IElemDisc< TDomain >::m_vElemdAFct, ug::IElemDisc< TDomain >::m_vElemdMFct, ug::IElemDisc< TDomain >::m_vElemJAFct, ug::IElemDisc< TDomain >::m_vElemJMFct, ug::IElemDisc< TDomain >::m_vElemRHSFct, ug::IElemDisc< TDomain >::m_vFinishElemLoopFct, ug::IElemDisc< TDomain >::m_vPrepareElemFct, ug::IElemDisc< TDomain >::m_vPrepareElemLoopFct, ug::MASS, ug::RHS, ug::ROID_UNKNOWN, ug::IElemDisc< TDomain >::set_time_dependent(), ug::STIFF, and UG_THROW.
Referenced by ug::IElemDisc< TDomain >::do_prep_elem_loop(), and ug::IElemDisc< TDomain >::do_prep_err_est_elem_loop().
template<typename TDomain> void ug::IElemDisc< TDomain >::set_stationary (bool bStationaryForced = true) inline
sets that the assembling is always stationary (even in instationary case)
template<typename TDomain> void ug::IElemDisc< TDomain >::set_stationary () inline
References ug::IElemDisc< TDomain >::set_stationary().
Referenced by ug::IElemDisc< TDomain >::set_stationary().
template<typename TDomain > void ug::IElemDisc< TDomain >::set_subsets (const std::string & subsets)
sets subset(s) by name list, divided by ','
References ug::TokenizeString().
Referenced by ug::NeumannBoundaryBase< TDomain >::add_inner_subsets(), and ug::IElemDisc< TDomain >::IElemDisc().
template<typename TDomain > void ug::IElemDisc< TDomain >::set_subsets (const std::vector< std::string > & subsets)
sets subset(s) by name list, divided by ','
References ug::IElemDisc< TDomain >::m_vSubset, ug::RemoveWhitespaceFromString(), and UG_THROW.
template<typename TDomain > void ug::IElemDisc< TDomain >::set_time_dependent (LocalVectorTimeSeries & locTimeSeries, const std::vector< number > & vScaleMass, const std::vector< number > & vScaleStiff)
sets if assembling should be time-dependent and the local time series
This function specifies if the assembling is time-dependent. If NULL is passed, the assembling is assumed to be time-independent. If a local time series is passed, this series is used as previous solution.
Parameters
[in] locTimeSeries Time series of previous solutions
References ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vScaleMass, and ug::IElemDisc< TDomain >::m_vScaleStiff.
Referenced by ug::DataEvaluator< TDomain >::DataEvaluator(), and ug::IElemDisc< TDomain >::set_roid().
template<typename TDomain > void ug::IElemDisc< TDomain >::set_time_independent ()
sets that the assembling is time independent
References ug::IElemDisc< TDomain >::do_prep_timestep(), ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries, ug::IElemDisc< TDomain >::m_vScaleMass, and ug::IElemDisc< TDomain >::m_vScaleStiff.
Referenced by ug::DataEvaluator< TDomain >::DataEvaluator().
template<typename TDomain> void ug::IElemDisc< TDomain >::set_time_point (const size_t timePoint) inline
sets the current time point
template<typename TDomain> number ug::IElemDisc< TDomain >::stiff_scale (const size_t timePoint) const inline
returns the weight factors of the time-disc scheme
template<typename TDomain> number ug::IElemDisc< TDomain >::stiff_scale () const inline
returns the weight factors of the time-disc scheme
template<typename TDomain> const std::vector<number>& ug::IElemDisc< TDomain >::stiff_scales () const inline
returns the weight factors of the time-disc scheme
template<typename TDomain> TDomain::subset_handler_type& ug::IElemDisc< TDomain >::subset_handler () inline
returns the subset handler
References UG_ASSERT.
Referenced by ug::NeumannBoundaryFE< TDomain >::prep_elem(), ug::NeumannBoundaryFV< TDomain >::prep_elem(), and ug::NeumannBoundaryFV1< TDomain >::prep_elem().
template<typename TDomain> const TDomain::subset_handler_type& ug::IElemDisc< TDomain >::subset_handler () const inline
returns the subset handler
References UG_ASSERT.
template<typename TDomain> const std::vector<std::string>& ug::IElemDisc< TDomain >::symb_fcts () const inline
returns the symbolic functions
Referenced by ug::IElemDisc< TDomain >::check_setup(), and ug::IElemDisc< TDomain >::update_function_index_mapping().
template<typename TDomain> const std::vector<std::string>& ug::IElemDisc< TDomain >::symb_subsets () const inline
returns the symbolic subsets
Referenced by ug::NeumannBoundaryBase< TDomain >::add_inner_subsets(), and ug::IElemDisc< TDomain >::check_setup().
template<typename TDomain> number ug::IElemDisc< TDomain >::time () const inline
returns currently set timepoint
Referenced by ug::NeumannBoundaryFE< TDomain >::add_rhs_elem(), ug::NeumannBoundaryFV< TDomain >::add_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::add_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem(), ug::IElemDisc< TDomain >::do_fsh_timestep(), ug::IElemDisc< TDomain >::do_fsh_timestep_elem(), ug::IElemDisc< TDomain >::do_prep_timestep(), and ug::IElemDisc< TDomain >::do_prep_timestep_elem().
template<typename TDomain> size_t ug::IElemDisc< TDomain >::time_point () const inline
returns the currently considered time point of the time-disc scheme
template<typename TDomain> virtual int ug::IElemDisc< TDomain >::type () const inline virtual
returns the type of elem disc
Reimplemented in ug::NeumannBoundaryBase< TDomain >.
References ug::EDT_ELEM, and ug::EDT_SIDE.
template<typename TDomain > void ug::IElemDisc< TDomain >::update_function_index_mapping () protected
updates the function index mapping
References ug::FunctionGroup::add(), ug::CreateFunctionIndexMapping(), ug::IElemDisc< TDomain >::m_fctGrp, ug::IElemDisc< TDomain >::m_fctIndexMap, ug::IElemDisc< TDomain >::m_spFctPattern, ug::IElemDisc< TDomain >::m_vIImport, ug::FunctionGroup::set_function_pattern(), ug::IElemDisc< TDomain >::symb_fcts(), and UG_CATCH_THROW.
Referenced by ug::IElemDisc< TDomain >::register_import(), ug::IElemDisc< TDomain >::set_function_pattern(), and ug::IElemDisc< TDomain >::set_functions().
template<typename TDomain> virtual bool ug::IElemDisc< TDomain >::use_hanging () const inline virtual
returns if discretization acts on hanging nodes if present
This function returns if a discretization really needs the hanging nodes in case of non-regular grid. This may not be the case for e.g. finite element assemblings but is needed for finite volumes
Reimplemented in ug::FV1InnerBoundaryElemDisc< TDomain >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV< class >, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFVCR< TDomain >.
Referenced by ug::DataEvaluator< TDomain >::DataEvaluator().
Member Data Documentation
template<typename TDomain> const int ug::IElemDisc< TDomain >::dim = TDomain::dim static
World dimension.
Referenced by ug::IElemDisc< TDomain >::set_roid().
template<typename TDomain> bool ug::IElemDisc< TDomain >::m_bDoErrEst private
flag indicating whether or not a posteriori error estimation is to be performed for this disc
template<typename TDomain> bool ug::IElemDisc< TDomain >::m_bStationaryForced protected
flag if stationary assembling is to be used even in instationary assembling
Referenced by ug::IElemDisc< TDomain >::do_add_def_M_elem(), and ug::IElemDisc< TDomain >::do_add_jac_M_elem().
template<typename TDomain> FunctionGroup ug::IElemDisc< TDomain >::m_fctGrp protected
current function group
Referenced by ug::IElemDisc< TDomain >::check_setup(), and ug::IElemDisc< TDomain >::update_function_index_mapping().
template<typename TDomain> FunctionIndexMapping ug::IElemDisc< TDomain >::m_fctIndexMap protected
current function index mapping
Referenced by ug::IElemDisc< TDomain >::update_function_index_mapping().
template<typename TDomain> ReferenceObjectID ug::IElemDisc< TDomain >::m_id protected
current Geometric Object
Referenced by ug::IElemDisc< TDomain >::do_add_def_A_elem(), ug::IElemDisc< TDomain >::do_add_def_A_expl_elem(), ug::IElemDisc< TDomain >::do_add_def_M_elem(), ug::IElemDisc< TDomain >::do_add_jac_A_elem(), ug::IElemDisc< TDomain >::do_add_jac_M_elem(), ug::IElemDisc< TDomain >::do_add_rhs_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_A_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_M_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_rhs_elem(), ug::IElemDisc< TDomain >::do_fsh_elem_loop(), ug::IElemDisc< TDomain >::do_fsh_err_est_elem_loop(), ug::IElemDisc< TDomain >::do_fsh_timestep_elem(), ug::IElemDisc< TDomain >::do_prep_elem(), ug::IElemDisc< TDomain >::do_prep_elem_loop(), ug::IElemDisc< TDomain >::do_prep_err_est_elem(), ug::IElemDisc< TDomain >::do_prep_err_est_elem_loop(), ug::IElemDisc< TDomain >::do_prep_timestep_elem(), and ug::IElemDisc< TDomain >::set_roid().
template<typename TDomain> LocalVectorTimeSeries* ug::IElemDisc< TDomain >::m_pLocalVectorTimeSeries protected
list of local vectors for all solutions of the time series
Referenced by ug::IElemDisc< TDomain >::do_add_def_A_elem(), ug::IElemDisc< TDomain >::do_add_def_A_expl_elem(), ug::IElemDisc< TDomain >::do_add_def_M_elem(), ug::IElemDisc< TDomain >::do_add_jac_A_elem(), ug::IElemDisc< TDomain >::do_add_jac_M_elem(), ug::IElemDisc< TDomain >::do_add_rhs_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_A_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_M_elem(), ug::IElemDisc< TDomain >::do_compute_err_est_rhs_elem(), ug::IElemDisc< TDomain >::do_fsh_timestep_elem(), ug::IElemDisc< TDomain >::do_prep_elem(), ug::IElemDisc< TDomain >::do_prep_err_est_elem(), ug::IElemDisc< TDomain >::do_prep_timestep_elem(), ug::IElemDisc< TDomain >::set_time_dependent(), and ug::IElemDisc< TDomain >::set_time_independent().
template<typename TDomain> SmartPtr<ApproximationSpace<TDomain> > ug::IElemDisc< TDomain >::m_spApproxSpace protected
Approximation Space.
Referenced by ug::IElemDisc< TDomain >::set_approximation_space().
template<typename TDomain> std::vector<SmartPtr<IElemDiscModifier<TDomain> > > ug::IElemDisc< TDomain >::m_spElemModifier protected
Approximation Space.
template<typename TDomain> SmartPtr<IErrEstData<TDomain> > ug::IElemDisc< TDomain >::m_spErrEstData protected
error estimation object associated to the element discretization
Referenced by ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem(), and ug::NeumannBoundaryFV1< TDomain >::prep_err_est_elem_loop().
template<typename TDomain> ConstSmartPtr<FunctionPattern> ug::IElemDisc< TDomain >::m_spFctPattern protected
current function pattern
Referenced by ug::IElemDisc< TDomain >::check_setup(), ug::IElemDisc< TDomain >::set_function_pattern(), and ug::IElemDisc< TDomain >::update_function_index_mapping().
template<typename TDomain> size_t ug::IElemDisc< TDomain >::m_timePoint protected
time point
template<typename TDomain> ElemComputeErrEstAFct ug::IElemDisc< TDomain >::m_vElemComputeErrEstAFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_compute_err_est_A_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> ElemComputeErrEstMFct ug::IElemDisc< TDomain >::m_vElemComputeErrEstMFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_compute_err_est_M_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> ElemComputeErrEstRhsFct ug::IElemDisc< TDomain >::m_vElemComputeErrEstRhsFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_compute_err_est_rhs_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> ElemdAFct ug::IElemDisc< TDomain >::m_vElemdAExplFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_add_def_A_expl_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> ElemdAFct ug::IElemDisc< TDomain >::m_vElemdAFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_add_def_A_elem(), ug::IElemDisc< TDomain >::set_default_add_fct(), and ug::IElemDisc< TDomain >::set_roid().
template<typename TDomain> ElemdMFct ug::IElemDisc< TDomain >::m_vElemdMFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_add_def_M_elem(), ug::IElemDisc< TDomain >::set_default_add_fct(), and ug::IElemDisc< TDomain >::set_roid().
template<typename TDomain> ElemJAFct ug::IElemDisc< TDomain >::m_vElemJAFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_add_jac_A_elem(), ug::IElemDisc< TDomain >::set_default_add_fct(), and ug::IElemDisc< TDomain >::set_roid().
template<typename TDomain> ElemJMFct ug::IElemDisc< TDomain >::m_vElemJMFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_add_jac_M_elem(), ug::IElemDisc< TDomain >::set_default_add_fct(), and ug::IElemDisc< TDomain >::set_roid().
template<typename TDomain> ElemRHSFct ug::IElemDisc< TDomain >::m_vElemRHSFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_add_rhs_elem(), ug::IElemDisc< TDomain >::set_default_add_fct(), and ug::IElemDisc< TDomain >::set_roid().
template<typename TDomain> std::vector<std::string> ug::IElemDisc< TDomain >::m_vFct protected
vector holding name of all symbolic functions
Referenced by ug::IElemDisc< TDomain >::set_functions().
template<typename TDomain> FinishElemLoopFct ug::IElemDisc< TDomain >::m_vFinishElemLoopFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_fsh_elem_loop(), ug::IElemDisc< TDomain >::set_default_add_fct(), and ug::IElemDisc< TDomain >::set_roid().
template<typename TDomain> FinishErrEstElemLoopFct ug::IElemDisc< TDomain >::m_vFinishErrEstElemLoopFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_fsh_err_est_elem_loop(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> FinishTimestepElemFct ug::IElemDisc< TDomain >::m_vFinishTimestepElemFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_fsh_timestep_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> FinishTimestepFct ug::IElemDisc< TDomain >::m_vFinishTimestepFct[bridge::NUM_ALGEBRA_TYPES] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_fsh_timestep(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> std::vector<IDataImport<dim>*> ug::IElemDisc< TDomain >::m_vIImport protected
data imports
Referenced by ug::IElemDisc< TDomain >::do_fsh_elem_loop(), ug::IElemDisc< TDomain >::do_fsh_err_est_elem_loop(), ug::IElemDisc< TDomain >::do_prep_elem_loop(), ug::IElemDisc< TDomain >::do_prep_err_est_elem_loop(), ug::IElemDisc< TDomain >::register_import(), and ug::IElemDisc< TDomain >::update_function_index_mapping().
template<typename TDomain> PrepareElemFct ug::IElemDisc< TDomain >::m_vPrepareElemFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_prep_elem(), ug::IElemDisc< TDomain >::set_default_add_fct(), and ug::IElemDisc< TDomain >::set_roid().
template<typename TDomain> PrepareElemLoopFct ug::IElemDisc< TDomain >::m_vPrepareElemLoopFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_prep_elem_loop(), ug::IElemDisc< TDomain >::set_default_add_fct(), and ug::IElemDisc< TDomain >::set_roid().
template<typename TDomain> PrepareErrEstElemFct ug::IElemDisc< TDomain >::m_vPrepareErrEstElemFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_prep_err_est_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> PrepareErrEstElemLoopFct ug::IElemDisc< TDomain >::m_vPrepareErrEstElemLoopFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_prep_err_est_elem_loop(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> PrepareTimestepElemFct ug::IElemDisc< TDomain >::m_vPrepareTimestepElemFct[NUM_REFERENCE_OBJECTS] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_prep_timestep_elem(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> PrepareTimestepFct ug::IElemDisc< TDomain >::m_vPrepareTimestepFct[bridge::NUM_ALGEBRA_TYPES] private
Referenced by ug::IElemDisc< TDomain >::clear_add_fct(), ug::IElemDisc< TDomain >::do_prep_timestep(), and ug::IElemDisc< TDomain >::set_default_add_fct().
template<typename TDomain> std::vector<number> ug::IElemDisc< TDomain >::m_vScaleMass protected
weight factors for time dependent assembling
Referenced by ug::IElemDisc< TDomain >::set_time_dependent(), and ug::IElemDisc< TDomain >::set_time_independent().
template<typename TDomain> std::vector<number> ug::IElemDisc< TDomain >::m_vScaleStiff protected
weight factors for time dependent assembling
Referenced by ug::IElemDisc< TDomain >::set_time_dependent(), and ug::IElemDisc< TDomain >::set_time_independent().
template<typename TDomain> std::vector<std::string> ug::IElemDisc< TDomain >::m_vSubset protected
vector holding name of all symbolic subsets
Referenced by ug::IElemDisc< TDomain >::check_setup(), and ug::IElemDisc< TDomain >::set_subsets().
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/elem_disc/elem_disc_interface.h
ugbase/lib_disc/spatial_disc/elem_disc/elem_disc_interface.cpp
ugbase/lib_disc/spatial_disc/elem_disc/elem_disc_interface_impl.h