ug4: ug::ElemProlongationBase< TDomain, TImpl > Class Template Reference
ug::ElemProlongationBase< TDomain, TImpl > Class Template Reference
#include <local_transfer_interface.h>
Public Member Functions
virtual void prolongate (Edge *parent)
virtual void prolongate (Face *parent)
virtual void prolongate (Vertex *parent)
virtual void prolongate (Volume *parent)
Public Member Functions inherited from ug::IElemProlongation< TDomain >
virtual void init (ConstSmartPtr< TDomain > spDomain, SmartPtr< TransferValueAccessor > vValueChild, SmartPtr< TransferValueAccessor > vValueParent)
virtual bool perform_prolongation_on (GridBaseObjectId gbo)=0
virtual ~IElemProlongation ()
Protected Member Functions
TImpl & getImpl ()
access to implementation
const TImpl & getImpl () const
const access to implementation
Additional Inherited Members
Protected Attributes inherited from ug::IElemProlongation< TDomain >
ConstSmartPtr< TDomain > m_spDomain
ConstSmartPtr< MultiGrid > m_spGrid
SmartPtr< TransferValueAccessor > m_vValueChild
SmartPtr< TransferValueAccessor > m_vValueParent
Member Function Documentation
getImpl() [1/2]
template<typename TDomain , typename TImpl > TImpl& ug::ElemProlongationBase< TDomain, TImpl >::getImpl () inline protected
access to implementation
Referenced by ug::ElemProlongationBase< TDomain, TImpl >::prolongate().
getImpl() [2/2]
template<typename TDomain , typename TImpl > const TImpl& ug::ElemProlongationBase< TDomain, TImpl >::getImpl () const inline protected
const access to implementation
prolongate() [1/4]
template<typename TDomain , typename TImpl > virtual void ug::ElemProlongationBase< TDomain, TImpl >::prolongate (Edge * parent) inline virtual
Implements ug::IElemProlongation< TDomain >.
References ug::ElemProlongationBase< TDomain, TImpl >::getImpl(), ug::IElemProlongation< TDomain >::m_vValueChild, and ug::IElemProlongation< TDomain >::m_vValueParent.
prolongate() [2/4]
template<typename TDomain , typename TImpl > virtual void ug::ElemProlongationBase< TDomain, TImpl >::prolongate (Face * parent) inline virtual
Implements ug::IElemProlongation< TDomain >.
References ug::ElemProlongationBase< TDomain, TImpl >::getImpl(), ug::IElemProlongation< TDomain >::m_vValueChild, and ug::IElemProlongation< TDomain >::m_vValueParent.
prolongate() [3/4]
template<typename TDomain , typename TImpl > virtual void ug::ElemProlongationBase< TDomain, TImpl >::prolongate (Vertex * parent) inline virtual
Implements ug::IElemProlongation< TDomain >.
Reimplemented in ug::StdLagrangeElemTransfer< TDomain >.
References ug::ElemProlongationBase< TDomain, TImpl >::getImpl(), ug::IElemProlongation< TDomain >::m_vValueChild, and ug::IElemProlongation< TDomain >::m_vValueParent.
prolongate() [4/4]
template<typename TDomain , typename TImpl > virtual void ug::ElemProlongationBase< TDomain, TImpl >::prolongate (Volume * parent) inline virtual
Implements ug::IElemProlongation< TDomain >.
References ug::ElemProlongationBase< TDomain, TImpl >::getImpl(), ug::IElemProlongation< TDomain >::m_vValueChild, and ug::IElemProlongation< TDomain >::m_vValueParent.
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/local_transfer_interface.h