ug4: AutoFreqAdaptNode Class Reference
AutoFreqAdaptNode Class Reference
#include <freq_adapt.h>
Public Member Functions
AutoFreqAdaptNode (unsigned long freq)
~AutoFreqAdaptNode ()
Protected Attributes
bool m_bActive
unsigned long m_prevFreq
Private Member Functions
bool is_active ()
void release ()
Friends
class FreqAdaptNodeManager
Constructor & Destructor Documentation
AutoFreqAdaptNode()
AutoFreqAdaptNode::AutoFreqAdaptNode (unsigned long freq)
References FreqAdaptNodeManager::add(), FreqAdaptValues::adjust_freq(), m_prevFreq, and FreqAdaptValues::newFreq.
~AutoFreqAdaptNode()
AutoFreqAdaptNode::~AutoFreqAdaptNode ()
References m_bActive, and FreqAdaptNodeManager::release_latest().
Member Function Documentation
is_active()
bool AutoFreqAdaptNode::is_active () inline private
References m_bActive.
release()
void AutoFreqAdaptNode::release () private
References FreqAdaptValues::adjust_freq(), m_bActive, and m_prevFreq.
Referenced by FreqAdaptNodeManager::release_latest().
Friends And Related Function Documentation
FreqAdaptNodeManager
friend class FreqAdaptNodeManager friend
Member Data Documentation
m_bActive
bool AutoFreqAdaptNode::m_bActive protected
Referenced by is_active(), release(), and ~AutoFreqAdaptNode().
m_prevFreq
unsigned long AutoFreqAdaptNode::m_prevFreq protected
Referenced by AutoFreqAdaptNode(), and release().
The documentation for this class was generated from the following files:
ugbase/common/profiler/freq_adapt.h
ugbase/common/profiler/freq_adapt.cpp