ug4: ug::H1EnergyIntegrand< TGridFunction > Class Template Reference
ug::H1EnergyIntegrand< TGridFunction > Class Template Reference
Norm of a grid function, evaluated in (weighted) H1-semi norm.
#include <integrate.h>
Public Types
typedef UserData< MathMatrix< worldDim, worldDim >, worldDim > weight_type
Public Types inherited from ug::StdIntegrand< number, TGridFunction::dim, H1EnergyIntegrand< TGridFunction > >
typedef number data_type
data type
Public Types inherited from ug::IIntegrand< number, TWorldDim >
typedef number data_type
data type
Public Member Functions
template<int elemDim>
void evaluate (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP)
returns the values of the integrand for a bunch of ips
H1EnergyIntegrand (TGridFunction &gridFct, size_t cmp)
constructor
H1EnergyIntegrand (TGridFunction &gridFct, size_t cmp, ConstSmartPtr< weight_type > spWeight)
constructor
virtual void set_subset (int si)
sets subset
virtual ~H1EnergyIntegrand ()
DTOR.
Public Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, H1EnergyIntegrand< TGridFunction > >
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)
Public Member Functions inherited from ug::IIntegrand< number, TWorldDim >
int subset () const
returns the subset
virtual ~IIntegrand ()
Static Public Attributes
static const int worldDim = TGridFunction::dim
world dimension of grid function
Static Public Attributes inherited from ug::StdIntegrand< number, TGridFunction::dim, H1EnergyIntegrand< TGridFunction > >
static const int worldDim
world dimension
Static Public Attributes inherited from ug::IIntegrand< number, TWorldDim >
static const int worldDim
world dimension
Protected Attributes
ScalarGridFunctionData< TGridFunction > m_scalarData
grid function data
ConstSmartPtr< weight_type > m_spWeight
scalar weight (optional)
Protected Attributes inherited from ug::IIntegrand< number, TWorldDim >
int m_si
subset
Additional Inherited Members
Protected Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, H1EnergyIntegrand< TGridFunction > >
H1EnergyIntegrand< TGridFunction > & getImpl ()
access to implementation
const H1EnergyIntegrand< TGridFunction > & getImpl () const
const access to implementation
Detailed Description
template<typename TGridFunction>
class ug::H1EnergyIntegrand< TGridFunction >
Norm of a grid function, evaluated in (weighted) H1-semi norm.
Member Typedef Documentation
weight_type
template<typename TGridFunction> typedef UserData<MathMatrix<worldDim, worldDim>, worldDim> ug::H1EnergyIntegrand< TGridFunction >::weight_type
Constructor & Destructor Documentation
H1EnergyIntegrand() [1/2]
template<typename TGridFunction> ug::H1EnergyIntegrand< TGridFunction >::H1EnergyIntegrand (TGridFunction & gridFct, size_t cmp) inline
constructor
H1EnergyIntegrand() [2/2]
template<typename TGridFunction> ug::H1EnergyIntegrand< TGridFunction >::H1EnergyIntegrand (TGridFunction & gridFct, size_t cmp, ConstSmartPtr< weight_type > spWeight) inline
constructor
~H1EnergyIntegrand()
template<typename TGridFunction> virtual ug::H1EnergyIntegrand< TGridFunction >::~H1EnergyIntegrand () inline virtual
DTOR.
Member Function Documentation
evaluate()
template<typename TGridFunction> template<int elemDim> void ug::H1EnergyIntegrand< TGridFunction >::evaluate (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject * pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP) inline
returns the values of the integrand for a bunch of ips
Parameters
vValue[out] the value of the integrand at the ips
vGlobIP[in] global integration point positions
pElem[in] the element to integrate
vCornerCoords[in] corner coordinates of the element
vLocIP[in] local integration point positions
vJT[in] jacobian transposed at integration point
numIP[in] number of integration points
References ug::SubsetGroup::add(), ug::DimFV1Geometry< TDim, TWorldDim >::add_boundary_subset(), pcl::ProcessCommunicator::allreduce(), ug::Grid::associated_elements_sorted(), ug::DimFV1Geometry< TDim, TWorldDim >::bf(), ug::CollectCornerCoordinates(), ug::SubsetGroup::contains(), dim, ug::DIM_SUBSET_EMPTY_GRID, ug::ScalarGridFunctionData< TGridFunction >::dof_indices(), ug::DoFRef(), ug::ScalarGridFunctionData< TGridFunction >::domain(), ug::ScalarGridFunctionData< TGridFunction >::fct(), ug::QuadratureRuleProvider< TDim >::get(), SmartPtr< T, FreePolicy >::get(), ug::ReferenceMappingProvider::get(), ug::ISubsetHandler::get_subset_index(), ug::GetLocalVector(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::ScalarGridFunctionData< TGridFunction >::grid_function(), ug::H1Error(), ug::ScalarGridFunctionData< TGridFunction >::id(), ug::Integral(), ug::IntegrateSubsets(), ug::Inverse(), ug::ScalarGridFunctionData< TGridFunction >::is_def_in_subset(), ug::DimReferenceMapping< TDim, TWorldDim >::jacobian_transposed(), ug::LFEID::LAGRANGE, ug::DimReferenceMapping< TDim, TWorldDim >::local_to_global(), ug::ScalarGridFunctionData< TGridFunction >::m_fct, ug::ScalarGridFunctionData< TGridFunction >::m_id, make_sp(), ug::MatVecMult(), ug::LocalDoFSet::num_sh(), pcl::NumProcs(), PCL_DT_DOUBLE, PCL_RO_SUM, ug::GridObject::reference_object_id(), ug::RemoveLowerDimSubsets(), ug::LocalVector::resize(), ug::RightInverse(), ug::SameDimensionsInAllSubsets(), ug::IIntegrand< TData, TWorldDim >::set_subset(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shape(), ug::PointerConstArray< TPtr >::size(), ug::SubsetGroup::size(), ug::MathVector< N, T >::size(), SPNULL, ug::SqrtGramDeterminant(), ug::IIntegrand< TData, TWorldDim >::subset(), ug::TokenizeString(), UG_ASSERT, UG_CATCH_THROW, UG_COND_THROW, UG_LOG, UG_THROW, ug::DimFV1Geometry< TDim, TWorldDim >::update(), ConstSmartPtr< T, FreePolicy >::valid(), ug::VecDistanceSq(), ug::VecDot(), ug::VecScaleAdd(), ug::VecScaleAppend(), ug::VecSet(), and ug::VecTwoNormSq().
set_subset()
template<typename TGridFunction> virtual void ug::H1EnergyIntegrand< TGridFunction >::set_subset (int si) inline virtual
sets subset
Reimplemented from ug::IIntegrand< number, TWorldDim >.
References ug::ScalarGridFunctionData< TGridFunction >::fct(), ug::ScalarGridFunctionData< TGridFunction >::is_def_in_subset(), ug::IIntegrand< TData, TWorldDim >::set_subset(), and UG_COND_THROW.
Member Data Documentation
m_scalarData
template<typename TGridFunction> ScalarGridFunctionData<TGridFunction> ug::H1EnergyIntegrand< TGridFunction >::m_scalarData protected
grid function data
m_spWeight
template<typename TGridFunction> ConstSmartPtr<weight_type> ug::H1EnergyIntegrand< TGridFunction >::m_spWeight protected
scalar weight (optional)
worldDim
template<typename TGridFunction> const int ug::H1EnergyIntegrand< TGridFunction >::worldDim = TGridFunction::dim static
world dimension of grid function
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/integrate.h