ug4: ug::PeriodicBoundaryManager::Group< TElem, Container > Class Template Reference
ug::PeriodicBoundaryManager::Group< TElem, Container > Class Template Reference
#include <periodic_boundary_manager.h>
Public Types
typedef std::pair< TElem *, TElem * > master_slave_pair
typedef Container SlaveContainer
typedef Container::iterator SlaveIterator
typedef std::set< master_slave_pair > unique_pairs
Public Member Functions
void add_slave (TElem *e)
Container & get_slaves ()
Group (TElem *m=NULL)
Public Attributes
TElem * m_master
Protected Attributes
Container m_slaves
Detailed Description
template<class TElem, class Container = std::vector<TElem*>>
class ug::PeriodicBoundaryManager::Group< TElem, Container >
A Group instance holds a master of type TElem and several children.
Member Typedef Documentation
master_slave_pair
template<class TElem , class Container = std::vector<TElem*>> typedef std::pair<TElem*, TElem*> ug::PeriodicBoundaryManager::Group< TElem, Container >::master_slave_pair
SlaveContainer
template<class TElem , class Container = std::vector<TElem*>> typedef Container ug::PeriodicBoundaryManager::Group< TElem, Container >::SlaveContainer
SlaveIterator
template<class TElem , class Container = std::vector<TElem*>> typedef Container::iterator ug::PeriodicBoundaryManager::Group< TElem, Container >::SlaveIterator
unique_pairs
template<class TElem , class Container = std::vector<TElem*>> typedef std::set<master_slave_pair> ug::PeriodicBoundaryManager::Group< TElem, Container >::unique_pairs
Constructor & Destructor Documentation
Group()
template<class TElem , class Container = std::vector<TElem*>> ug::PeriodicBoundaryManager::Group< TElem, Container >::Group (TElem * m = NULL) inline
Member Function Documentation
add_slave()
template<class TElem , class Container = std::vector<TElem*>> void ug::PeriodicBoundaryManager::Group< TElem, Container >::add_slave (TElem * e) inline
References ug::PeriodicBoundaryManager::Group< TElem, Container >::m_master, ug::PeriodicBoundaryManager::Group< TElem, Container >::m_slaves, and UG_ASSERT.
Referenced by ug::PeriodicBoundaryManager::make_slave(), and ug::PeriodicBoundaryManager::merge_groups().
get_slaves()
template<class TElem , class Container = std::vector<TElem*>> Container& ug::PeriodicBoundaryManager::Group< TElem, Container >::get_slaves () inline
References ug::PeriodicBoundaryManager::Group< TElem, Container >::m_slaves.
Referenced by ug::PeriodicBoundaryManager::handle_creation(), ug::PeriodicBoundaryManager::merge_groups(), ug::PeriodicBoundaryManager::print_identification(), and ug::PeriodicBoundaryManager::remove_group().
Member Data Documentation
m_master
template<class TElem , class Container = std::vector<TElem*>> TElem* ug::PeriodicBoundaryManager::Group< TElem, Container >::m_master
Referenced by ug::PeriodicBoundaryManager::Group< TElem, Container >::add_slave(), ug::PeriodicBoundaryManager::handle_creation(), ug::PeriodicBoundaryManager::make_master(), ug::PeriodicBoundaryManager::make_slave(), ug::PeriodicBoundaryManager::merge_groups(), ug::PeriodicBoundaryManager::print_identification(), ug::PeriodicBoundaryManager::remove_group(), ug::PeriodicBoundaryManager::replace_parent(), and ug::PeriodicBoundaryManager::set_group().
m_slaves
template<class TElem , class Container = std::vector<TElem*>> Container ug::PeriodicBoundaryManager::Group< TElem, Container >::m_slaves protected
Referenced by ug::PeriodicBoundaryManager::Group< TElem, Container >::add_slave(), and ug::PeriodicBoundaryManager::Group< TElem, Container >::get_slaves().
The documentation for this class was generated from the following file:
ugbase/lib_grid/tools/periodic_boundary_manager.h