ug4: ug::VariableArray2< T, T_ordering > Class Template Reference
ug::VariableArray2< T, T_ordering > Class Template Reference
#include <variable_array.h>
Public Types
enum { is_static =false }
enum { static_num_rows =0 }
enum { static_num_cols =0 }
typedef size_t size_type
typedef variable_type storage_type
typedef T value_type
Public Member Functions
const T & at (size_type r, size_type c) const
T & at (size_type r, size_type c)
size_type capacity_num_cols () const
size_type capacity_num_rows () const
size_type num_cols () const
size_type num_rows () const
const T & operator() (size_type r, size_type c) const
T & operator() (size_type r, size_type c)
void reserve (size_type nrRows, size_type nrCols) const
bool resize (size_type newRows, size_type newCols, bool bCopyValues=true)
VariableArray2 ()
VariableArray2 (size_type rows_, size_type cols_)
VariableArray2 (const VariableArray2< T, T_ordering > &other)
~VariableArray2 ()
Static Public Attributes
static const eMatrixOrdering ordering = T_ordering
Protected Attributes
size_type cols
size_type rows
T * values
Friends
template<typename _T , eMatrixOrdering _T_Ordering>
std::ostream & operator<< (std::ostream &out, const VariableArray2< _T, _T_Ordering > &arr)
Detailed Description
template<typename T, eMatrixOrdering T_ordering = ColMajor>
class ug::VariableArray2< T, T_ordering >
VariableArray2 is a two-dimensional array which supports a similar interface like stl::vector. You can use FixedArray2 in GeMatrix to get a variable size Matrix. Use is_static to distinguish between fixed and variable arrays.
Parameters
T type of object in Array (i.e. double)
T_ordering Ordering of columns/rows. Default is ColMajor.
See also
eMatrixOrdering
Member Typedef Documentation
size_type
template<typename T, eMatrixOrdering T_ordering = ColMajor> typedef size_t ug::VariableArray2< T, T_ordering >::size_type
storage_type
template<typename T, eMatrixOrdering T_ordering = ColMajor> typedef variable_type ug::VariableArray2< T, T_ordering >::storage_type
value_type
template<typename T, eMatrixOrdering T_ordering = ColMajor> typedef T ug::VariableArray2< T, T_ordering >::value_type
Member Enumeration Documentation
anonymous enum
template<typename T, eMatrixOrdering T_ordering = ColMajor> anonymous enum
Enumerator
is_static
anonymous enum
template<typename T, eMatrixOrdering T_ordering = ColMajor> anonymous enum
Enumerator
static_num_rows
anonymous enum
template<typename T, eMatrixOrdering T_ordering = ColMajor> anonymous enum
Enumerator
static_num_cols
Constructor & Destructor Documentation
VariableArray2() [1/3]
template<typename T , eMatrixOrdering T_ordering> ug::VariableArray2< T, T_ordering >::VariableArray2 ()
VariableArray2() [2/3]
template<typename T , eMatrixOrdering T_ordering> ug::VariableArray2< T, T_ordering >::VariableArray2 (size_type rows_, size_type cols_)
VariableArray2() [3/3]
template<typename T, eMatrixOrdering T_ordering> ug::VariableArray2< T, T_ordering >::VariableArray2 (const VariableArray2< T, T_ordering > & other)
~VariableArray2()
template<typename T , eMatrixOrdering T_ordering> ug::VariableArray2< T, T_ordering >::~VariableArray2 ()
Member Function Documentation
at() [1/2]
template<typename T, eMatrixOrdering T_ordering = ColMajor> const T& ug::VariableArray2< T, T_ordering >::at (size_type r, size_type c) const inline
Referenced by ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator*().
at() [2/2]
template<typename T, eMatrixOrdering T_ordering = ColMajor> T& ug::VariableArray2< T, T_ordering >::at (size_type r, size_type c) inline
capacity_num_cols()
template<typename T, eMatrixOrdering T_ordering = ColMajor> size_type ug::VariableArray2< T, T_ordering >::capacity_num_cols () const inline
capacity_num_rows()
template<typename T, eMatrixOrdering T_ordering = ColMajor> size_type ug::VariableArray2< T, T_ordering >::capacity_num_rows () const inline
num_cols()
template<typename T , eMatrixOrdering T_ordering> size_t ug::VariableArray2< T, T_ordering >::num_cols () const inline
Referenced by ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator*(), ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator+(), ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator-(), ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator=(), and ug::VariableArray2< LocalCplMatrix *>::VariableArray2().
num_rows()
template<typename T , eMatrixOrdering T_ordering> size_t ug::VariableArray2< T, T_ordering >::num_rows () const inline
Referenced by ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator*(), ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator+(), ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator-(), ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator=(), and ug::VariableArray2< LocalCplMatrix *>::VariableArray2().
operator()() [1/2]
template<typename T , eMatrixOrdering T_ordering> const T & ug::VariableArray2< T, T_ordering >::operator() (size_type r, size_type c) const inline
operator()() [2/2]
template<typename T , eMatrixOrdering T_ordering> T & ug::VariableArray2< T, T_ordering >::operator() (size_type r, size_type c) inline
reserve()
template<typename T, eMatrixOrdering T_ordering = ColMajor> void ug::VariableArray2< T, T_ordering >::reserve (size_type nrRows, size_type nrCols) const inline
resize()
template<typename T , eMatrixOrdering T_ordering> bool ug::VariableArray2< T, T_ordering >::resize (size_type newRows, size_type newCols, bool bCopyValues = true) inline
Referenced by ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator*(), ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator+(), ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator-(), and ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::T().
Friends And Related Function Documentation
operator<<
template<typename T, eMatrixOrdering T_ordering = ColMajor> template<typename _T , eMatrixOrdering _T_Ordering> std::ostream& operator<< (std::ostream & out, const VariableArray2< _T, _T_Ordering > & arr) friend
Member Data Documentation
cols
template<typename T, eMatrixOrdering T_ordering = ColMajor> size_type ug::VariableArray2< T, T_ordering >::cols protected
ordering
template<typename T, eMatrixOrdering T_ordering = ColMajor> const eMatrixOrdering ug::VariableArray2< T, T_ordering >::ordering = T_ordering static
rows
template<typename T, eMatrixOrdering T_ordering = ColMajor> size_type ug::VariableArray2< T, T_ordering >::rows protected
values
template<typename T, eMatrixOrdering T_ordering = ColMajor> T* ug::VariableArray2< T, T_ordering >::values protected
Referenced by ug::VariableArray2< LocalCplMatrix *>::VariableArray2().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/small_algebra/storage/variable_array.h
ugbase/lib_algebra/small_algebra/storage/variable_array_impl.h