ug4: ug::IVertexGroup Class Reference
ug::IVertexGroup Class Reference abstract
Base class for all classes which consist of a group of vertices.
#include <grid_base_objects.h>
Public Types
typedef Vertex *const * ConstVertexArray
Public Member Functions
virtual size_t num_vertices () const =0
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual Vertex * vertex (size_t index) const =0
virtual ConstVertexArray vertices () const =0
virtual ~IVertexGroup ()
Detailed Description
Base class for all classes which consist of a group of vertices.
Member Typedef Documentation
ConstVertexArray
typedef Vertex* const* ug::IVertexGroup::ConstVertexArray
Constructor & Destructor Documentation
~IVertexGroup()
virtual ug::IVertexGroup::~IVertexGroup () inline virtual
Member Function Documentation
num_vertices()
virtual size_t ug::IVertexGroup::num_vertices () const pure virtual
Implemented in ug::Octahedron, ug::Pyramid, ug::Prism, ug::Hexahedron, ug::Tetrahedron, ug::CustomQuadrilateral< ConstrainedQuadrilateral, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomQuadrilateral< Quadrilateral, Face, Triangle, Quadrilateral >, ug::CustomQuadrilateral< ConstrainingQuadrilateral, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< ConstrainedTriangle, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomTriangle< ConstrainingTriangle, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< Triangle, Face, Triangle, Quadrilateral >, ug::VolumeDescriptor, ug::VolumeVertices, ug::FaceDescriptor, ug::FaceVertices, ug::EdgeVertices, and ug::CustomVertexGroup.
Referenced by ug::NeuriteProjector::average_params(), ug::NeuriteProjector::average_pos_from_parent(), ug::Grid::create_by_cloning(), and ug::VertexGroupsMatch().
operator[]()
Vertex* ug::IVertexGroup::operator[] (size_t index) const inline
returns the i-th vertex.
size()
size_t ug::IVertexGroup::size () const inline
returns the number of vertices.
References boost::num_vertices().
Referenced by ug::bp_newton_start_pos(), ug::GetSharedVertex(), ug::GetSharedVertices(), and ug::NumSharedVertices().
vertex()
virtual Vertex* ug::IVertexGroup::vertex (size_t index) const pure virtual
Implemented in ug::Octahedron, ug::Pyramid, ug::Prism, ug::Hexahedron, ug::Tetrahedron, ug::CustomQuadrilateral< ConstrainedQuadrilateral, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomQuadrilateral< Quadrilateral, Face, Triangle, Quadrilateral >, ug::CustomQuadrilateral< ConstrainingQuadrilateral, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< ConstrainedTriangle, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomTriangle< ConstrainingTriangle, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< Triangle, Face, Triangle, Quadrilateral >, ug::VolumeDescriptor, ug::VolumeVertices, ug::FaceDescriptor, ug::FaceVertices, ug::EdgeVertices, and ug::CustomVertexGroup.
Referenced by ug::NeuriteProjector::average_params(), ug::NeuriteProjector::average_pos_from_parent(), ug::bp_newton_start_pos(), ug::Grid::create_by_cloning(), and ug::VertexGroupsMatch().
vertices()
virtual ConstVertexArray ug::IVertexGroup::vertices () const pure virtual
Implemented in ug::Octahedron, ug::Pyramid, ug::Prism, ug::Hexahedron, ug::Tetrahedron, ug::CustomQuadrilateral< ConstrainedQuadrilateral, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomQuadrilateral< Quadrilateral, Face, Triangle, Quadrilateral >, ug::CustomQuadrilateral< ConstrainingQuadrilateral, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< ConstrainedTriangle, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomTriangle< ConstrainingTriangle, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< Triangle, Face, Triangle, Quadrilateral >, ug::VolumeDescriptor, ug::VolumeVertices, ug::FaceDescriptor, ug::FaceVertices, ug::EdgeVertices, and ug::CustomVertexGroup.
Referenced by ug::Grid::create_by_cloning(), ug::GetSharedVertex(), ug::GetSharedVertices(), ug::NumSharedVertices(), and ug::VertexGroupsMatch().
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/grid_base_objects.h