ug4: ug::UzawaBase< TDomain, TAlgebra > Class Template Reference
ug::UzawaBase< TDomain, TAlgebra > Class Template Reference
#include <uzawa.h>
Public Types
typedef TGridFunction::element_type TElement
typedef GridFunction< TDomain, TAlgebra > TGridFunction
typedef TGridFunction::side_type TSide
typedef TAlgebra algebra_type
typedef TAlgebra::vector_type vector_type
typedef TAlgebra::matrix_type matrix_type
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
SmartPtr< ILinearIterator< typename TAlgebra::vector_type > > clone ()
clone
void extract_schur_update (const matrix_type &K, const TGridFunction &c)
Update C22 block by matrix.
void extract_sub_matrices (const matrix_type &K, const TGridFunction &c)
extract block matrix operators (called once)
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
Overriding base type.
void init_block_iterations ()
void init_block_operators ()
allocate block matrix operators
void postprocess_block_iterations ()
void set_backward_iter (SmartPtr< ILinearIterator< vector_type > > iter)
void set_forward_iter (SmartPtr< ILinearIterator< vector_type > > iter)
void set_schur_iter (SmartPtr< ILinearIterator< vector_type > > iter)
void set_schur_operator_update (SmartPtr< AssembledLinearOperator< TAlgebra > > spSchurUpdateOp, double theta=0.0)
virtual bool supports_parallel () const
returns if parallel solving is supported
UzawaBase (const char *sSchurCmp)
UzawaBase (const std::vector< std::string > &vSchurCmp)
default constructor
virtual ~UzawaBase ()
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
virtual std::string config_string () const
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
returns true if the debug writer is set
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Static Public Attributes
static const int dim = TDomain::dim
World dimension.
Protected Types
typedef IPreconditioner< TAlgebra > base_type
enum BLOCK {
AUX_A11 , B12 , B21 , AUX_C22 ,
AUX_M22 , AUX_ARRAY_SIZE
}
Protected Member Functions
void create_slice_debug_writers ()
void init_in_first_step (const matrix_type &pMat, const TGridFunction &pC)
void my_write_debug (const matrix_type &mat, std::string name, const GridLevel &glTo, const GridLevel &glFrom)
void my_write_debug (const matrix_type &mat, std::string name, const TGridFunction &rTo, const TGridFunction &rFrom)
auxiliary matrices (not cloned!)
virtual void my_write_debug (const TGridFunction &rGF, std::string name)
virtual const char * name () const
name
virtual bool postprocess ()
cleans the operator
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
initializes the preconditioner
template<int d>
void reset_slice_debug_writers ()
void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
computes a new correction c = B*d
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
void enter_debug_writer_section (const char *secDir)
enters a debugging section
void enter_debug_writer_section (std::string secDir)
enters a debugging section
void leave_debug_writer_section ()
leaves a debugging section
void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
void write_debug (const matrix_type &mat, std::string name)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
matrix_type m_A
SmartPtr< matrix_operator_type > m_auxMat [AUX_ARRAY_SIZE]
bool m_bInit
flag indicating, whether operator must be initialized
double m_dSchurUpdateWeight
scaling factor for (additive) Schur complement update
UzawaSlicing< TGridFunction > m_slicing
object for slicing routines
SmartPtr< ILinearIterator< vector_type > > m_spBackwardInverse
iteration for forward system
SmartPtr< ILinearIterator< vector_type > > m_spForwardInverse
iteration for forward system
SmartPtr< GridFunctionDebugWriter< TDomain, TAlgebra > > m_spGridFunctionDebugWriter
SmartPtr< ILinearIterator< vector_type > > m_SpSchurComplementInverse
iteration for forward system
SmartPtr< AssembledLinearOperator< TAlgebra > > m_spSchurUpdateOp
assembly for (additive) Schur complement update
SmartPtr< IDebugWriter< algebra_type > > m_spSliceDebugWriter [2]
std::vector< std::string > m_vSchurCmp
vector of strings identifying components used for Schur complement
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Static Private Attributes
static const bool UZAWA_CMP_DEFAULT = false
static const bool UZAWA_CMP_SCHUR = true
Detailed Description
template<typename TDomain, typename TAlgebra>
class ug::UzawaBase< TDomain, TAlgebra >
Base class for an Uzawa iteration
Member Typedef Documentation
algebra_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra ug::UzawaBase< TDomain, TAlgebra >::algebra_type
Algebra types
base_type
template<typename TDomain , typename TAlgebra > typedef IPreconditioner<TAlgebra> ug::UzawaBase< TDomain, TAlgebra >::base_type protected
matrix_operator_type
template<typename TDomain , typename TAlgebra > typedef MatrixOperator<matrix_type, vector_type> ug::UzawaBase< TDomain, TAlgebra >::matrix_operator_type
Algebra types
matrix_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::matrix_type ug::UzawaBase< TDomain, TAlgebra >::matrix_type
Algebra types
TElement
template<typename TDomain , typename TAlgebra > typedef TGridFunction::element_type ug::UzawaBase< TDomain, TAlgebra >::TElement
TGridFunction
template<typename TDomain , typename TAlgebra > typedef GridFunction<TDomain, TAlgebra> ug::UzawaBase< TDomain, TAlgebra >::TGridFunction
TSide
template<typename TDomain , typename TAlgebra > typedef TGridFunction::side_type ug::UzawaBase< TDomain, TAlgebra >::TSide
vector_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::vector_type ug::UzawaBase< TDomain, TAlgebra >::vector_type
Algebra types
Member Enumeration Documentation
BLOCK
template<typename TDomain , typename TAlgebra > enum ug::UzawaBase::BLOCK protected
Enumerator
AUX_A11
B12
B21
AUX_C22
AUX_M22
AUX_ARRAY_SIZE
Constructor & Destructor Documentation
UzawaBase() [1/2]
template<typename TDomain , typename TAlgebra > ug::UzawaBase< TDomain, TAlgebra >::UzawaBase (const std::vector< std::string > & vSchurCmp) inline
default constructor
References ug::UzawaBase< TDomain, TAlgebra >::init_block_operators().
UzawaBase() [2/2]
template<typename TDomain , typename TAlgebra > ug::UzawaBase< TDomain, TAlgebra >::UzawaBase (const char * sSchurCmp) inline
References ug::UzawaBase< TDomain, TAlgebra >::init_block_operators().
~UzawaBase()
template<typename TDomain , typename TAlgebra > virtual ug::UzawaBase< TDomain, TAlgebra >::~UzawaBase () inline virtual
Member Function Documentation
clone()
template<typename TDomain , typename TAlgebra > SmartPtr< ILinearIterator< typename TAlgebra::vector_type > > ug::UzawaBase< TDomain, TAlgebra >::clone virtual
clone
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References SPNULL.
create_slice_debug_writers()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::create_slice_debug_writers protected
References make_sp().
extract_schur_update()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::extract_schur_update (const matrix_type & K, const TGridFunction & c) inline
Update C22 block by matrix.
References ug::UzawaBase< TDomain, TAlgebra >::AUX_C22, ug::UzawaBase< TDomain, TAlgebra >::AUX_M22, ug::CheckRowIterators(), ug::GridFunction< TDomain, TAlgebra >::grid_level(), ug::UzawaBase< TDomain, TAlgebra >::m_auxMat, ug::UzawaBase< TDomain, TAlgebra >::m_dSchurUpdateWeight, ug::UzawaBase< TDomain, TAlgebra >::m_slicing, ug::UzawaBase< TDomain, TAlgebra >::m_spSchurUpdateOp, ug::UzawaBase< TDomain, TAlgebra >::m_spSliceDebugWriter, ug::UzawaBase< TDomain, TAlgebra >::my_write_debug(), ug::SchurDebug, UG_DLOG, and ug::UzawaBase< TDomain, TAlgebra >::UZAWA_CMP_SCHUR.
Referenced by ug::UzawaBase< TDomain, TAlgebra >::init_in_first_step().
extract_sub_matrices()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::extract_sub_matrices (const matrix_type & K, const TGridFunction & c)
extract block matrix operators (called once)
References ug::SchurDebug, and UG_DLOG.
Referenced by ug::UzawaBase< TDomain, TAlgebra >::init_in_first_step().
init()
template<typename TDomain , typename TAlgebra > virtual bool ug::UzawaBase< TDomain, TAlgebra >::init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type & u) inline virtual
Overriding base type.
Reimplemented from ug::IPreconditioner< TAlgebra >.
References ug::IPreconditioner< TAlgebra >::init(), ug::UzawaBase< TDomain, TAlgebra >::init_in_first_step(), ug::UzawaBase< TDomain, TAlgebra >::m_bInit, ug::SchurDebug, UG_ASSERT, UG_DLOG, and SmartPtr< T, FreePolicy >::valid().
init_block_iterations()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::init_block_iterations () inline
References ug::UzawaBase< TDomain, TAlgebra >::AUX_A11, ug::UzawaBase< TDomain, TAlgebra >::AUX_C22, ug::UzawaBase< TDomain, TAlgebra >::m_auxMat, ug::UzawaBase< TDomain, TAlgebra >::m_spBackwardInverse, ug::UzawaBase< TDomain, TAlgebra >::m_spForwardInverse, and ug::UzawaBase< TDomain, TAlgebra >::m_SpSchurComplementInverse.
Referenced by ug::UzawaBase< TDomain, TAlgebra >::init_in_first_step().
init_block_operators()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::init_block_operators () inline
allocate block matrix operators
References ug::UzawaBase< TDomain, TAlgebra >::AUX_A11, ug::UzawaBase< TDomain, TAlgebra >::AUX_C22, ug::UzawaBase< TDomain, TAlgebra >::AUX_M22, ug::UzawaBase< TDomain, TAlgebra >::B12, ug::UzawaBase< TDomain, TAlgebra >::B21, ug::UzawaBase< TDomain, TAlgebra >::m_auxMat, and make_sp().
Referenced by ug::UzawaBase< TDomain, TAlgebra >::UzawaBase().
init_in_first_step()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::init_in_first_step (const matrix_type & pMat, const TGridFunction & pC) inline protected
References ug::DebugWritingObject< TAlgebra >::debug_writer(), ug::UzawaBase< TDomain, TAlgebra >::extract_schur_update(), ug::UzawaBase< TDomain, TAlgebra >::extract_sub_matrices(), ug::GridFunction< TDomain, TAlgebra >::grid_level(), ug::UzawaBase< TDomain, TAlgebra >::init_block_iterations(), ug::UzawaBase< TDomain, TAlgebra >::m_slicing, ug::UzawaBase< TDomain, TAlgebra >::m_spGridFunctionDebugWriter, ug::UzawaBase< TDomain, TAlgebra >::m_vSchurCmp, ug::SchurDebug, UG_DLOG, and UG_LOG.
Referenced by ug::UzawaBase< TDomain, TAlgebra >::init().
my_write_debug() [1/3]
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::my_write_debug (const matrix_type & mat, std::string name, const GridLevel & glTo, const GridLevel & glFrom) inline protected
References ug::GridLevelAppendix(), ug::UzawaBase< TDomain, TAlgebra >::m_spGridFunctionDebugWriter, ug::UzawaBase< TDomain, TAlgebra >::name(), and PROFILE_FUNC_GROUP.
my_write_debug() [2/3]
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::my_write_debug (const matrix_type & mat, std::string name, const TGridFunction & rTo, const TGridFunction & rFrom) inline protected
auxiliary matrices (not cloned!)
References ug::GridFunction< TDomain, TAlgebra >::grid_level(), and ug::UzawaBase< TDomain, TAlgebra >::name().
Referenced by ug::UzawaBase< TDomain, TAlgebra >::extract_schur_update().
my_write_debug() [3/3]
template<typename TDomain , typename TAlgebra > virtual void ug::UzawaBase< TDomain, TAlgebra >::my_write_debug (const TGridFunction & rGF, std::string name) inline protected virtual
References ug::GridFunction< TDomain, TAlgebra >::grid_level(), ug::GridLevelAppendix(), ug::UzawaBase< TDomain, TAlgebra >::m_spGridFunctionDebugWriter, ug::UzawaBase< TDomain, TAlgebra >::name(), and PROFILE_FUNC_GROUP.
name()
template<typename TDomain , typename TAlgebra > virtual const char* ug::UzawaBase< TDomain, TAlgebra >::name () const inline protected virtual
name
Implements ug::IPreconditioner< TAlgebra >.
Referenced by ug::UzawaBase< TDomain, TAlgebra >::my_write_debug().
postprocess()
template<typename TDomain , typename TAlgebra > bool ug::UzawaBase< TDomain, TAlgebra >::postprocess protected virtual
cleans the operator
Implements ug::IPreconditioner< TAlgebra >.
postprocess_block_iterations()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::postprocess_block_iterations () inline
preprocess()
template<typename TDomain , typename TAlgebra > bool ug::UzawaBase< TDomain, TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) protected virtual
initializes the preconditioner
Implements ug::IPreconditioner< TAlgebra >.
References pcl::CollectUniqueElements(), ug::MakeConsistent(), pcl::NumProcs(), and ug::SetDirichletRow().
reset_slice_debug_writers()
template<typename TDomain , typename TAlgebra > template<int dim> void ug::UzawaBase< TDomain, TAlgebra >::reset_slice_debug_writers protected
References UG_LOG.
set_backward_iter()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::set_backward_iter (SmartPtr< ILinearIterator< vector_type > > iter) inline
References ug::UzawaBase< TDomain, TAlgebra >::m_spBackwardInverse.
set_debug()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter) protected virtual
set debug writer
Reimplemented from ug::DebugWritingObject< TAlgebra >.
References UG_LOG.
set_forward_iter()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::set_forward_iter (SmartPtr< ILinearIterator< vector_type > > iter) inline
References ug::UzawaBase< TDomain, TAlgebra >::m_spForwardInverse.
set_schur_iter()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::set_schur_iter (SmartPtr< ILinearIterator< vector_type > > iter) inline
References ug::UzawaBase< TDomain, TAlgebra >::m_SpSchurComplementInverse.
set_schur_operator_update()
template<typename TDomain , typename TAlgebra > void ug::UzawaBase< TDomain, TAlgebra >::set_schur_operator_update (SmartPtr< AssembledLinearOperator< TAlgebra > > spSchurUpdateOp, double theta = 0.0) inline
References ug::UzawaBase< TDomain, TAlgebra >::m_dSchurUpdateWeight, and ug::UzawaBase< TDomain, TAlgebra >::m_spSchurUpdateOp.
step()
template<typename TDomain , typename TAlgebra > bool ug::UzawaBase< TDomain, TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) protected virtual
computes a new correction c = B*d
Single step of an (inexact) Uzawa iteration.
Implements ug::IPreconditioner< TAlgebra >.
References SmartPtr< T, FreePolicy >::get(), pcl::NumProcs(), ug::PST_UNIQUE, and UG_THROW.
supports_parallel()
template<typename TDomain , typename TAlgebra > virtual bool ug::UzawaBase< TDomain, TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References ug::UzawaBase< TDomain, TAlgebra >::m_spForwardInverse, ug::UzawaBase< TDomain, TAlgebra >::m_SpSchurComplementInverse, and UG_ASSERT.
Member Data Documentation
dim
template<typename TDomain , typename TAlgebra > const int ug::UzawaBase< TDomain, TAlgebra >::dim = TDomain::dim static
World dimension.
m_A
template<typename TDomain , typename TAlgebra > matrix_type ug::UzawaBase< TDomain, TAlgebra >::m_A protected
m_auxMat
template<typename TDomain , typename TAlgebra > SmartPtr<matrix_operator_type> ug::UzawaBase< TDomain, TAlgebra >::m_auxMat[AUX_ARRAY_SIZE] protected
Referenced by ug::UzawaBase< TDomain, TAlgebra >::extract_schur_update(), ug::UzawaBase< TDomain, TAlgebra >::init_block_iterations(), and ug::UzawaBase< TDomain, TAlgebra >::init_block_operators().
m_bInit
template<typename TDomain , typename TAlgebra > bool ug::UzawaBase< TDomain, TAlgebra >::m_bInit protected
flag indicating, whether operator must be initialized
Referenced by ug::UzawaBase< TDomain, TAlgebra >::init().
m_dSchurUpdateWeight
template<typename TDomain , typename TAlgebra > double ug::UzawaBase< TDomain, TAlgebra >::m_dSchurUpdateWeight protected
scaling factor for (additive) Schur complement update
Referenced by ug::UzawaBase< TDomain, TAlgebra >::extract_schur_update(), and ug::UzawaBase< TDomain, TAlgebra >::set_schur_operator_update().
m_slicing
template<typename TDomain , typename TAlgebra > UzawaSlicing<TGridFunction> ug::UzawaBase< TDomain, TAlgebra >::m_slicing protected
object for slicing routines
Referenced by ug::UzawaBase< TDomain, TAlgebra >::extract_schur_update(), and ug::UzawaBase< TDomain, TAlgebra >::init_in_first_step().
m_spBackwardInverse
template<typename TDomain , typename TAlgebra > SmartPtr<ILinearIterator<vector_type> > ug::UzawaBase< TDomain, TAlgebra >::m_spBackwardInverse protected
iteration for forward system
Referenced by ug::UzawaBase< TDomain, TAlgebra >::init_block_iterations(), and ug::UzawaBase< TDomain, TAlgebra >::set_backward_iter().
m_spForwardInverse
template<typename TDomain , typename TAlgebra > SmartPtr<ILinearIterator<vector_type> > ug::UzawaBase< TDomain, TAlgebra >::m_spForwardInverse protected
iteration for forward system
Referenced by ug::UzawaBase< TDomain, TAlgebra >::init_block_iterations(), ug::UzawaBase< TDomain, TAlgebra >::set_forward_iter(), and ug::UzawaBase< TDomain, TAlgebra >::supports_parallel().
m_spGridFunctionDebugWriter
template<typename TDomain , typename TAlgebra > SmartPtr<GridFunctionDebugWriter<TDomain, TAlgebra> > ug::UzawaBase< TDomain, TAlgebra >::m_spGridFunctionDebugWriter protected
Referenced by ug::UzawaBase< TDomain, TAlgebra >::init_in_first_step(), and ug::UzawaBase< TDomain, TAlgebra >::my_write_debug().
m_SpSchurComplementInverse
template<typename TDomain , typename TAlgebra > SmartPtr<ILinearIterator<vector_type> > ug::UzawaBase< TDomain, TAlgebra >::m_SpSchurComplementInverse protected
iteration for forward system
Referenced by ug::UzawaBase< TDomain, TAlgebra >::init_block_iterations(), ug::UzawaBase< TDomain, TAlgebra >::set_schur_iter(), and ug::UzawaBase< TDomain, TAlgebra >::supports_parallel().
m_spSchurUpdateOp
template<typename TDomain , typename TAlgebra > SmartPtr<AssembledLinearOperator<TAlgebra> > ug::UzawaBase< TDomain, TAlgebra >::m_spSchurUpdateOp protected
assembly for (additive) Schur complement update
Referenced by ug::UzawaBase< TDomain, TAlgebra >::extract_schur_update(), and ug::UzawaBase< TDomain, TAlgebra >::set_schur_operator_update().
m_spSliceDebugWriter
template<typename TDomain , typename TAlgebra > SmartPtr<IDebugWriter<algebra_type> > ug::UzawaBase< TDomain, TAlgebra >::m_spSliceDebugWriter[2] protected
Referenced by ug::UzawaBase< TDomain, TAlgebra >::extract_schur_update().
m_vSchurCmp
template<typename TDomain , typename TAlgebra > std::vector<std::string> ug::UzawaBase< TDomain, TAlgebra >::m_vSchurCmp protected
vector of strings identifying components used for Schur complement
Referenced by ug::UzawaBase< TDomain, TAlgebra >::init_in_first_step().
UZAWA_CMP_DEFAULT
template<typename TDomain , typename TAlgebra > const bool ug::UzawaBase< TDomain, TAlgebra >::UZAWA_CMP_DEFAULT = false static private
UZAWA_CMP_SCHUR
template<typename TDomain , typename TAlgebra > const bool ug::UzawaBase< TDomain, TAlgebra >::UZAWA_CMP_SCHUR = true static private
Referenced by ug::UzawaBase< TDomain, TAlgebra >::extract_schur_update().
The documentation for this class was generated from the following file:
ugbase/lib_disc/operator/linear_operator/uzawa/uzawa.h