ug4: ug::L2DistIntegrand< TGridFunction > Class Template Reference
ug::L2DistIntegrand< TGridFunction > Class Template Reference
Integrand for the distance of two grid functions - evaluated in the (weighted) H1-semi norm.
#include <integrate.h>
Public Types
typedef L2Integrand< TGridFunction >::weight_type weight_type
Public Types inherited from ug::StdIntegrand< number, TGridFunction::dim, L2DistIntegrand< TGridFunction > >
typedef number data_type
data type
Public Types inherited from ug::IIntegrand< TData, TWorldDim >
typedef TData data_type
data type
Public Member Functions
template<int elemDim>
void evaluate (number vValue[], const MathVector< worldDim > vFineGlobIP[], GridObject *pFineElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vFineLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP)
returns the values of the integrand for a bunch of ips
L2DistIntegrand (TGridFunction &fineGridFct, size_t fineCmp, TGridFunction &coarseGridFct, size_t coarseCmp)
constructor (1st is fine grid function)
L2DistIntegrand (TGridFunction &fineGridFct, size_t fineCmp, TGridFunction &coarseGridFct, size_t coarseCmp, ConstSmartPtr< weight_type > spWeight)
constructor (1st is fine grid function)
L2DistIntegrand (TGridFunction &fineGridFct, size_t fineCmp, TGridFunction &coarseGridFct, size_t coarseCmp, ConstSmartPtr< weight_type > spWeight, number dist12)
constructor (1st is fine grid function)
virtual void set_subset (int si)
sets subset
virtual ~L2DistIntegrand ()
Public Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, L2DistIntegrand< TGridFunction > >
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)
Public Member Functions inherited from ug::IIntegrand< TData, TWorldDim >
int subset () const
returns the subset
virtual ~IIntegrand ()
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
Static Public Attributes
static const int worldDim = TGridFunction::dim
world dimension of grid function
Static Public Attributes inherited from ug::StdIntegrand< number, TGridFunction::dim, L2DistIntegrand< TGridFunction > >
static const int worldDim
world dimension
Static Public Attributes inherited from ug::IIntegrand< TData, TWorldDim >
static const int worldDim = TWorldDim
world dimension
Protected Attributes
ScalarGridFunctionData< TGridFunction > m_coarseData
const int m_coarseTopLevel
double m_deltaFineCoarse
shift
ScalarGridFunctionData< TGridFunction > m_fineData
const int m_fineTopLevel
SmartPtr< MultiGrid > m_spMG
multigrid
ConstSmartPtr< weight_type > m_spWeight
Protected Attributes inherited from ug::IIntegrand< TData, TWorldDim >
int m_si
subset
Additional Inherited Members
Protected Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, L2DistIntegrand< TGridFunction > >
L2DistIntegrand< TGridFunction > & getImpl ()
access to implementation
const L2DistIntegrand< TGridFunction > & getImpl () const
const access to implementation
Detailed Description
template<typename TGridFunction>
class ug::L2DistIntegrand< TGridFunction >
Integrand for the distance of two grid functions - evaluated in the (weighted) H1-semi norm.
Member Typedef Documentation
weight_type
template<typename TGridFunction > typedef L2Integrand<TGridFunction>::weight_type ug::L2DistIntegrand< TGridFunction >::weight_type
Constructor & Destructor Documentation
L2DistIntegrand() [1/3]
template<typename TGridFunction > ug::L2DistIntegrand< TGridFunction >::L2DistIntegrand (TGridFunction & fineGridFct, size_t fineCmp, TGridFunction & coarseGridFct, size_t coarseCmp) inline
constructor (1st is fine grid function)
References ug::L2DistIntegrand< TGridFunction >::m_coarseData, ug::L2DistIntegrand< TGridFunction >::m_coarseTopLevel, ug::L2DistIntegrand< TGridFunction >::m_fineData, ug::L2DistIntegrand< TGridFunction >::m_fineTopLevel, and UG_COND_THROW.
L2DistIntegrand() [2/3]
template<typename TGridFunction > ug::L2DistIntegrand< TGridFunction >::L2DistIntegrand (TGridFunction & fineGridFct, size_t fineCmp, TGridFunction & coarseGridFct, size_t coarseCmp, ConstSmartPtr< weight_type > spWeight) inline
constructor (1st is fine grid function)
References ug::L2DistIntegrand< TGridFunction >::m_coarseData, ug::L2DistIntegrand< TGridFunction >::m_coarseTopLevel, ug::L2DistIntegrand< TGridFunction >::m_fineData, ug::L2DistIntegrand< TGridFunction >::m_fineTopLevel, and UG_COND_THROW.
L2DistIntegrand() [3/3]
template<typename TGridFunction > ug::L2DistIntegrand< TGridFunction >::L2DistIntegrand (TGridFunction & fineGridFct, size_t fineCmp, TGridFunction & coarseGridFct, size_t coarseCmp, ConstSmartPtr< weight_type > spWeight, number dist12) inline
constructor (1st is fine grid function)
References ug::L2DistIntegrand< TGridFunction >::m_coarseData, ug::L2DistIntegrand< TGridFunction >::m_coarseTopLevel, ug::L2DistIntegrand< TGridFunction >::m_fineData, ug::L2DistIntegrand< TGridFunction >::m_fineTopLevel, and UG_COND_THROW.
~L2DistIntegrand()
template<typename TGridFunction > virtual ug::L2DistIntegrand< TGridFunction >::~L2DistIntegrand () inline virtual
Member Function Documentation
evaluate()
template<typename TGridFunction > template<int elemDim> void ug::L2DistIntegrand< TGridFunction >::evaluate (number vValue[], const MathVector< worldDim > vFineGlobIP[], GridObject * pFineElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vFineLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP) inline
returns the values of the integrand for a bunch of ips
Parameters
vValue[out] the value of the integrand at the ips
vGlobIP[in] global integration point positions
pElem[in] the element to integrate
vCornerCoords[in] corner coordinates of the element
vLocIP[in] local integration point positions
vJT[in] jacobian transposed at integration point
numIP[in] number of integration points
References ug::CollectCornerCoordinates(), ug::DoFRef(), ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::L2DistIntegrand< TGridFunction >::m_coarseData, ug::L2DistIntegrand< TGridFunction >::m_coarseTopLevel, ug::L2DistIntegrand< TGridFunction >::m_deltaFineCoarse, ug::L2DistIntegrand< TGridFunction >::m_fineData, ug::L2DistIntegrand< TGridFunction >::m_fineTopLevel, ug::L2DistIntegrand< TGridFunction >::m_spMG, ug::L2DistIntegrand< TGridFunction >::m_spWeight, ug::GridObject::reference_object_id(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shape(), ug::IIntegrand< TData, TWorldDim >::subset(), UG_ASSERT, UG_CATCH_THROW, ConstSmartPtr< T, FreePolicy >::valid(), and ug::VecSet().
set_subset()
template<typename TGridFunction > virtual void ug::L2DistIntegrand< TGridFunction >::set_subset (int si) inline virtual
sets subset
Reimplemented from ug::IIntegrand< TData, TWorldDim >.
References ug::L2DistIntegrand< TGridFunction >::m_coarseData, ug::L2DistIntegrand< TGridFunction >::m_fineData, ug::IIntegrand< TData, TWorldDim >::set_subset(), and UG_COND_THROW.
Member Data Documentation
m_coarseData
template<typename TGridFunction > ScalarGridFunctionData<TGridFunction> ug::L2DistIntegrand< TGridFunction >::m_coarseData protected
Referenced by ug::L2DistIntegrand< TGridFunction >::evaluate(), ug::L2DistIntegrand< TGridFunction >::L2DistIntegrand(), and ug::L2DistIntegrand< TGridFunction >::set_subset().
m_coarseTopLevel
template<typename TGridFunction > const int ug::L2DistIntegrand< TGridFunction >::m_coarseTopLevel protected
Referenced by ug::L2DistIntegrand< TGridFunction >::evaluate(), and ug::L2DistIntegrand< TGridFunction >::L2DistIntegrand().
m_deltaFineCoarse
template<typename TGridFunction > double ug::L2DistIntegrand< TGridFunction >::m_deltaFineCoarse protected
shift
Referenced by ug::L2DistIntegrand< TGridFunction >::evaluate().
m_fineData
template<typename TGridFunction > ScalarGridFunctionData<TGridFunction> ug::L2DistIntegrand< TGridFunction >::m_fineData protected
Referenced by ug::L2DistIntegrand< TGridFunction >::evaluate(), ug::L2DistIntegrand< TGridFunction >::L2DistIntegrand(), and ug::L2DistIntegrand< TGridFunction >::set_subset().
m_fineTopLevel
template<typename TGridFunction > const int ug::L2DistIntegrand< TGridFunction >::m_fineTopLevel protected
Referenced by ug::L2DistIntegrand< TGridFunction >::evaluate(), and ug::L2DistIntegrand< TGridFunction >::L2DistIntegrand().
m_spMG
template<typename TGridFunction > SmartPtr<MultiGrid> ug::L2DistIntegrand< TGridFunction >::m_spMG protected
multigrid
Referenced by ug::L2DistIntegrand< TGridFunction >::evaluate().
m_spWeight
template<typename TGridFunction > ConstSmartPtr<weight_type> ug::L2DistIntegrand< TGridFunction >::m_spWeight protected
Referenced by ug::L2DistIntegrand< TGridFunction >::evaluate().
worldDim
template<typename TGridFunction > const int ug::L2DistIntegrand< TGridFunction >::worldDim = TGridFunction::dim static
world dimension of grid function
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/integrate.h