ug4: ug::DimHFV1Geometry< TDim, TWorldDim > Class Template Reference
ug::DimHFV1Geometry< TDim, TWorldDim > Class Template Reference
#include <hfv1_geom.h>
Classes
struct MidID
struct NatEdgeInfo
struct NewEdgeInfo
class SCV
class SCVF
Public Types
typedef traits::elem_type_0 elem_type_0
element type names
typedef traits::elem_type_1 elem_type_1
typedef traits::elem_type_2 elem_type_2
typedef traits::elem_type_3 elem_type_3
typedef traits::elem_type_4 elem_type_4
typedef hdimfv1_traits< TDim > traits
traits
Public Member Functions
DimHFV1Geometry ()
constructor
size_t num_scv () const
number of SubControlVolumes
size_t num_scv_ips () const
returns number of all scv ips
size_t num_scvf () const
number of SubControlVolumeFaces
size_t num_scvf_ips () const
returns number of all scv ips
size_t num_sh () const
number of shape functions
const SCV & scv (size_t i) const
const access to SubControlVolume number i
const MathVector< worldDim > * scv_global_ips () const
returns all ips of scv as they appear in scv loop
const MathVector< dim > * scv_local_ips () const
returns all ips of scv as they appear in scv loop
const SCVF & scvf (size_t i) const
const access to SubControlVolumeFace number i
const MathVector< worldDim > * scvf_global_ips () const
returns all ips of scv as they appear in scv loop
const MathVector< dim > * scvf_local_ips () const
returns all ips of scv as they appear in scv loop
void update (GridObject *pElem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update values for an element
void update_local_data ()
update local data for an element
Static Public Attributes
static const int dim = TDim
dimension of reference element
static const bool staticLocalData = true
flag indicating if local data may change
static const bool usesHangingNodes = true
Hanging node flag: this Geometry does support hanging nodes.
static const int worldDim = TWorldDim
dimension of world
Protected Member Functions
void compute_side_midpoints (size_t i, MathVector< dim > &locSideMid, MathVector< worldDim > &gloSideMid)
void compute_side_midpoints (size_t i, size_t j, size_t k, size_t l, MathVector< dim > &locSideMid, MathVector< worldDim > &gloSideMid)
void compute_side_midpoints (size_t i, size_t j, size_t k, MathVector< dim > &locSideMid, MathVector< worldDim > &gloSideMid)
void copy_global_corners (SCVF &scvf)
void copy_global_corners (SCV &scv)
void copy_local_corners (SCVF &scvf)
void copy_local_corners (SCV &scv)
size_t get_child_edge_of_corner (size_t i, size_t co)
Protected Attributes
std::vector< MathVector< worldDim > > m_vGlobSCVFIP
std::vector< MathVector< worldDim > > m_vGlobSCVIP
std::vector< MathVector< dim > > m_vLocSCVFIP
std::vector< MathVector< dim > > m_vLocSCVIP
Private Attributes
std::vector< MathVector< worldDim > > m_gloMid [dim+1]
std::vector< MathVector< dim > > m_locMid [dim+1]
size_t m_numNaturalSCV
number of SubControlVolumes
size_t m_numNaturalSCVF
number of SubControlVolumeFaces
size_t m_numSh
GridObject * m_pElem
pointer to current element
DimReferenceMapping< dim, worldDim > * m_rMapping
reference mapping
ReferenceObjectID m_roid
current reference object id
DimReferenceElement< dim > m_rRefElem
reference element
std::vector< NatEdgeInfo > m_vNatEdgeInfo
std::vector< NewEdgeInfo > m_vNewEdgeInfo
std::vector< SCV > m_vSCV
std::vector< SCVF > m_vSCVF
Static Private Attributes
static const size_t m_maxNSH = fv1_dim_traits<TDim, TWorldDim>::maxNSH
max number of shapes
Member Typedef Documentation
elem_type_0
template<int TDim, int TWorldDim = TDim> typedef traits::elem_type_0 ug::DimHFV1Geometry< TDim, TWorldDim >::elem_type_0
element type names
elem_type_1
template<int TDim, int TWorldDim = TDim> typedef traits::elem_type_1 ug::DimHFV1Geometry< TDim, TWorldDim >::elem_type_1
elem_type_2
template<int TDim, int TWorldDim = TDim> typedef traits::elem_type_2 ug::DimHFV1Geometry< TDim, TWorldDim >::elem_type_2
elem_type_3
template<int TDim, int TWorldDim = TDim> typedef traits::elem_type_3 ug::DimHFV1Geometry< TDim, TWorldDim >::elem_type_3
elem_type_4
template<int TDim, int TWorldDim = TDim> typedef traits::elem_type_4 ug::DimHFV1Geometry< TDim, TWorldDim >::elem_type_4
traits
template<int TDim, int TWorldDim = TDim> typedef hdimfv1_traits<TDim> ug::DimHFV1Geometry< TDim, TWorldDim >::traits
traits
Constructor & Destructor Documentation
DimHFV1Geometry()
template<int TDim, int TWorldDim = TDim> ug::DimHFV1Geometry< TDim, TWorldDim >::DimHFV1Geometry () inline
constructor
References ug::HFV1Geometry< TElem, TWorldDim >::update().
Member Function Documentation
compute_side_midpoints() [1/3]
template<int TDim, int TWorldDim = TDim> void ug::DimHFV1Geometry< TDim, TWorldDim >::compute_side_midpoints (size_t i, MathVector< dim > & locSideMid, MathVector< worldDim > & gloSideMid) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, and ug::HFV1Geometry< TElem, TWorldDim >::m_rRefElem.
compute_side_midpoints() [2/3]
template<int TDim, int TWorldDim = TDim> void ug::DimHFV1Geometry< TDim, TWorldDim >::compute_side_midpoints (size_t i, size_t j, size_t k, size_t l, MathVector< dim > & locSideMid, MathVector< worldDim > & gloSideMid) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, and ug::VecAdd().
compute_side_midpoints() [3/3]
template<int TDim, int TWorldDim = TDim> void ug::DimHFV1Geometry< TDim, TWorldDim >::compute_side_midpoints (size_t i, size_t j, size_t k, MathVector< dim > & locSideMid, MathVector< worldDim > & gloSideMid) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, and ug::VecAdd().
copy_global_corners() [1/2]
template<int TDim, int TWorldDim = TDim> void ug::DimHFV1Geometry< TDim, TWorldDim >::copy_global_corners (SCVF & scvf) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::MidID::dim, ug::DimHFV1Geometry< TDim, TWorldDim >::MidID::dim, ug::HFV1Geometry< TElem, TWorldDim >::MidID::id, ug::DimHFV1Geometry< TDim, TWorldDim >::MidID::id, ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_midId, ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_vGloPos, and ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_corners().
copy_global_corners() [2/2]
template<int TDim, int TWorldDim = TDim> void ug::DimHFV1Geometry< TDim, TWorldDim >::copy_global_corners (SCV & scv) inline protected
References ug::DimHFV1Geometry< TDim, TWorldDim >::MidID::dim, ug::HFV1Geometry< TElem, TWorldDim >::MidID::id, ug::DimHFV1Geometry< TDim, TWorldDim >::MidID::id, ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_midId, ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_vGloPos, ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_corners(), and UG_ASSERT.
copy_local_corners() [1/2]
template<int TDim, int TWorldDim = TDim> void ug::DimHFV1Geometry< TDim, TWorldDim >::copy_local_corners (SCVF & scvf) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::MidID::dim, ug::DimHFV1Geometry< TDim, TWorldDim >::MidID::dim, ug::HFV1Geometry< TElem, TWorldDim >::MidID::id, ug::DimHFV1Geometry< TDim, TWorldDim >::MidID::id, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_midId, ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::m_vLocPos, and ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::num_corners().
copy_local_corners() [2/2]
template<int TDim, int TWorldDim = TDim> void ug::DimHFV1Geometry< TDim, TWorldDim >::copy_local_corners (SCV & scv) inline protected
References ug::DimHFV1Geometry< TDim, TWorldDim >::MidID::dim, ug::HFV1Geometry< TElem, TWorldDim >::MidID::id, ug::DimHFV1Geometry< TDim, TWorldDim >::MidID::id, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_midId, ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::m_vLocPos, ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::num_corners(), and UG_ASSERT.
get_child_edge_of_corner()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::get_child_edge_of_corner (size_t i, size_t co) inline protected
References ug::HFV1Geometry< TElem, TWorldDim >::m_vNatEdgeInfo, and ug::HFV1Geometry< TElem, TWorldDim >::m_vNewEdgeInfo.
num_scv()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::num_scv () const inline
number of SubControlVolumes
References ug::HFV1Geometry< TElem, TWorldDim >::m_vSCV.
num_scv_ips()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::num_scv_ips () const inline
returns number of all scv ips
References ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVIP.
num_scvf()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::num_scvf () const inline
number of SubControlVolumeFaces
References ug::HFV1Geometry< TElem, TWorldDim >::m_vSCVF.
num_scvf_ips()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::num_scvf_ips () const inline
returns number of all scv ips
References ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVFIP.
num_sh()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::num_sh () const inline
number of shape functions
References ug::HFV1Geometry< TElem, TWorldDim >::m_numSh.
scv()
template<int TDim, int TWorldDim = TDim> const SCV& ug::DimHFV1Geometry< TDim, TWorldDim >::scv (size_t i) const inline
const access to SubControlVolume number i
References ug::HFV1Geometry< TElem, TWorldDim >::m_vSCV, ug::HFV1Geometry< TElem, TWorldDim >::num_scv(), and UG_ASSERT.
scv_global_ips()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimHFV1Geometry< TDim, TWorldDim >::scv_global_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVIP.
scv_local_ips()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>* ug::DimHFV1Geometry< TDim, TWorldDim >::scv_local_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::HFV1Geometry< TElem, TWorldDim >::m_vLocSCVIP.
scvf()
template<int TDim, int TWorldDim = TDim> const SCVF& ug::DimHFV1Geometry< TDim, TWorldDim >::scvf (size_t i) const inline
const access to SubControlVolumeFace number i
References ug::HFV1Geometry< TElem, TWorldDim >::m_vSCVF, ug::HFV1Geometry< TElem, TWorldDim >::num_scvf(), and UG_ASSERT.
scvf_global_ips()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimHFV1Geometry< TDim, TWorldDim >::scvf_global_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVFIP.
scvf_local_ips()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>* ug::DimHFV1Geometry< TDim, TWorldDim >::scvf_local_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::HFV1Geometry< TElem, TWorldDim >::m_vLocSCVFIP.
update()
template<int TDim, int TWorldDim> void ug::DimHFV1Geometry< TDim, TWorldDim >::update (GridObject * pElem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update values for an element
References ug::AveragePositions(), ug::CollectEdgesSorted(), ug::CollectFacesSorted(), ug::HFV1Geometry< TElem, TWorldDim >::compute_side_midpoints(), ug::CSEDGE_CONSTRAINED_EDGE, ug::CSEDGE_CONSTRAINING_EDGE, ug::CSEDGE_REGULAR_EDGE, ug::CSFACE_CONSTRAINING_QUADRILATERAL, ug::CSFACE_CONSTRAINING_TRIANGLE, ug::HFV1Geometry< TElem, TWorldDim >::dim, ug::HFV1Geometry< TElem, TWorldDim >::get_child_edge_of_corner(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::global_ip(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::global_ip(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::ISubsetHandler::grid(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::HFV1ManifoldGeometry(), ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::LFEID::LAGRANGE, ug::DimHFV1Geometry< TDim, TWorldDim >::SCVF::local_ip(), ug::DimHFV1Geometry< TDim, TWorldDim >::SCV::local_ip(), ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, ug::HFV1Geometry< TElem, TWorldDim >::SCVF::m_numCorners, ug::HFV1Geometry< TElem, TWorldDim >::m_numNaturalSCV, ug::HFV1Geometry< TElem, TWorldDim >::m_numNaturalSCVF, ug::HFV1Geometry< TElem, TWorldDim >::m_numSh, ug::HFV1Geometry< TElem, TWorldDim >::m_pElem, ug::HFV1Geometry< TElem, TWorldDim >::m_rMapping, ug::HFV1Geometry< TElem, TWorldDim >::m_rRefElem, ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVFIP, ug::HFV1Geometry< TElem, TWorldDim >::m_vGlobSCVIP, ug::HFV1Geometry< TElem, TWorldDim >::m_vLocSCVFIP, ug::HFV1Geometry< TElem, TWorldDim >::m_vLocSCVIP, ug::HFV1Geometry< TElem, TWorldDim >::m_vNatEdgeInfo, ug::HFV1Geometry< TElem, TWorldDim >::m_vNewEdgeInfo, ug::HFV1Geometry< TElem, TWorldDim >::m_vSCV, ug::HFV1Geometry< TElem, TWorldDim >::m_vSCVF, ug::MatVecMult(), ug::HFV1Geometry< TElem, TWorldDim >::num_scv(), ug::HFV1Geometry< TElem, TWorldDim >::num_scvf(), ug::LocalDoFSet::num_sh(), ug::HFV1Geometry< TElem, TWorldDim >::num_sh(), ug::ROID_EDGE, ug::ROID_HEXAHEDRON, ug::ROID_OCTAHEDRON, ug::ROID_PRISM, ug::ROID_PYRAMID, ug::ROID_QUADRILATERAL, ug::ROID_TETRAHEDRON, ug::ROID_TRIANGLE, ug::HFV1Geometry< TElem, TWorldDim >::scv(), ug::HFV1Geometry< TElem, TWorldDim >::scvf(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), ug::ReferenceMapping< TRefElem, TWorldDim >::sqrt_gram_det(), UG_ASSERT, UG_THROW, ug::ReferenceMapping< TRefElem, TWorldDim >::update(), ug::VecDot(), ug::VecInterpolateLinear(), and ug::VecSubtract().
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data().
update_local_data()
template<int TDim, int TWorldDim> void ug::DimHFV1Geometry< TDim, TWorldDim >::update_local_data ()
update local data for an element
References ug::HFV1Geometry< TElem, TWorldDim >::dim, ug::HFV1Geometry< TElem, TWorldDim >::m_gloMid, ug::HFV1Geometry< TElem, TWorldDim >::m_locMid, ug::HFV1Geometry< TElem, TWorldDim >::m_numNaturalSCV, ug::HFV1Geometry< TElem, TWorldDim >::m_numNaturalSCVF, ug::HFV1Geometry< TElem, TWorldDim >::m_pElem, ug::HFV1Geometry< TElem, TWorldDim >::m_rMapping, ug::HFV1Geometry< TElem, TWorldDim >::m_rRefElem, ug::HFV1Geometry< TElem, TWorldDim >::m_vSCV, ug::ROID_OCTAHEDRON, ug::ROID_PYRAMID, and ug::DimHFV1Geometry< TDim, TWorldDim >::update().
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::print().
Member Data Documentation
dim
template<int TDim, int TWorldDim = TDim> const int ug::DimHFV1Geometry< TDim, TWorldDim >::dim = TDim static
dimension of reference element
m_gloMid
template<int TDim, int TWorldDim = TDim> std::vector<MathVector<worldDim> > ug::DimHFV1Geometry< TDim, TWorldDim >::m_gloMid[dim+1] private
m_locMid
template<int TDim, int TWorldDim = TDim> std::vector<MathVector<dim> > ug::DimHFV1Geometry< TDim, TWorldDim >::m_locMid[dim+1] private
m_maxNSH
template<int TDim, int TWorldDim = TDim> const size_t ug::DimHFV1Geometry< TDim, TWorldDim >::m_maxNSH = fv1_dim_traits<TDim, TWorldDim>::maxNSH static private
max number of shapes
m_numNaturalSCV
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::m_numNaturalSCV private
number of SubControlVolumes
m_numNaturalSCVF
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::m_numNaturalSCVF private
number of SubControlVolumeFaces
m_numSh
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::m_numSh private
m_pElem
template<int TDim, int TWorldDim = TDim> GridObject* ug::DimHFV1Geometry< TDim, TWorldDim >::m_pElem private
pointer to current element
m_rMapping
template<int TDim, int TWorldDim = TDim> DimReferenceMapping<dim, worldDim>* ug::DimHFV1Geometry< TDim, TWorldDim >::m_rMapping private
reference mapping
m_roid
template<int TDim, int TWorldDim = TDim> ReferenceObjectID ug::DimHFV1Geometry< TDim, TWorldDim >::m_roid private
current reference object id
m_rRefElem
template<int TDim, int TWorldDim = TDim> DimReferenceElement<dim> ug::DimHFV1Geometry< TDim, TWorldDim >::m_rRefElem private
reference element
m_vGlobSCVFIP
template<int TDim, int TWorldDim = TDim> std::vector<MathVector<worldDim> > ug::DimHFV1Geometry< TDim, TWorldDim >::m_vGlobSCVFIP protected
m_vGlobSCVIP
template<int TDim, int TWorldDim = TDim> std::vector<MathVector<worldDim> > ug::DimHFV1Geometry< TDim, TWorldDim >::m_vGlobSCVIP protected
m_vLocSCVFIP
template<int TDim, int TWorldDim = TDim> std::vector<MathVector<dim> > ug::DimHFV1Geometry< TDim, TWorldDim >::m_vLocSCVFIP protected
m_vLocSCVIP
template<int TDim, int TWorldDim = TDim> std::vector<MathVector<dim> > ug::DimHFV1Geometry< TDim, TWorldDim >::m_vLocSCVIP protected
m_vNatEdgeInfo
template<int TDim, int TWorldDim = TDim> std::vector<NatEdgeInfo> ug::DimHFV1Geometry< TDim, TWorldDim >::m_vNatEdgeInfo private
m_vNewEdgeInfo
template<int TDim, int TWorldDim = TDim> std::vector<NewEdgeInfo> ug::DimHFV1Geometry< TDim, TWorldDim >::m_vNewEdgeInfo private
m_vSCV
template<int TDim, int TWorldDim = TDim> std::vector<SCV> ug::DimHFV1Geometry< TDim, TWorldDim >::m_vSCV private
m_vSCVF
template<int TDim, int TWorldDim = TDim> std::vector<SCVF> ug::DimHFV1Geometry< TDim, TWorldDim >::m_vSCVF private
staticLocalData
template<int TDim, int TWorldDim = TDim> const bool ug::DimHFV1Geometry< TDim, TWorldDim >::staticLocalData = true static
flag indicating if local data may change
usesHangingNodes
template<int TDim, int TWorldDim = TDim> const bool ug::DimHFV1Geometry< TDim, TWorldDim >::usesHangingNodes = true static
Hanging node flag: this Geometry does support hanging nodes.
worldDim
template<int TDim, int TWorldDim = TDim> const int ug::DimHFV1Geometry< TDim, TWorldDim >::worldDim = TWorldDim static
dimension of world
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/hfv1_geom.h
ugbase/lib_disc/spatial_disc/disc_util/hfv1_geom.cpp