ug4: ug::SparseMatrix< TValueType >::row_iterator Class Reference
ug::SparseMatrix< TValueType >::row_iterator Class Reference
#include <sparsematrix.h>
Public Member Functions
void check () const
size_t index () const
bool operator!= (const row_iterator &o) const
void operator++ ()
void operator+= (int nr)
row_iterator * operator-> ()
bool operator== (const row_iterator &other) const
row_iterator (const row_iterator &other)
row_iterator (row_iterator &&other)
row_iterator (SparseMatrix &_A, size_t row, size_t _i)
value_type & value ()
~row_iterator ()
Private Attributes
size_t _row
SparseMatrix & A
size_t i
Detailed Description
template<typename TValueType>
class ug::SparseMatrix< TValueType >::row_iterator
row_iterator iterator over a row
Constructor & Destructor Documentation
row_iterator() [1/3]
template<typename TValueType > ug::SparseMatrix< TValueType >::row_iterator::row_iterator (SparseMatrix & _A, size_t row, size_t _i) inline
References ug::SparseMatrix< TValueType >::row_iterator::A, and ug::SparseMatrix< TValueType >::add_iterator().
row_iterator() [2/3]
template<typename TValueType > ug::SparseMatrix< TValueType >::row_iterator::row_iterator (row_iterator && other) inline
References ug::SparseMatrix< TValueType >::row_iterator::A, and ug::SparseMatrix< TValueType >::add_iterator().
row_iterator() [3/3]
template<typename TValueType > ug::SparseMatrix< TValueType >::row_iterator::row_iterator (const row_iterator & other) inline
References ug::SparseMatrix< TValueType >::row_iterator::_row, ug::SparseMatrix< TValueType >::row_iterator::A, and ug::SparseMatrix< TValueType >::add_iterator().
~row_iterator()
template<typename TValueType > ug::SparseMatrix< TValueType >::row_iterator::~row_iterator () inline
References ug::SparseMatrix< TValueType >::row_iterator::_row, ug::SparseMatrix< TValueType >::row_iterator::A, and ug::SparseMatrix< TValueType >::remove_iterator().
Member Function Documentation
check()
template<typename TValueType > void ug::SparseMatrix< TValueType >::row_iterator::check () const inline
References ug::SparseMatrix< TValueType >::row_iterator::_row, ug::SparseMatrix< TValueType >::row_iterator::A, ug::SparseMatrix< TValueType >::check_row(), and ug::SparseMatrix< TValueType >::row_iterator::i.
Referenced by ug::SparseMatrix< TValueType >::row_iterator::index(), ug::SparseMatrix< TValueType >::row_iterator::operator==(), and ug::SparseMatrix< TValueType >::row_iterator::value().
index()
template<typename TValueType > size_t ug::SparseMatrix< TValueType >::row_iterator::index () const inline
References ug::SparseMatrix< TValueType >::row_iterator::A, ug::SparseMatrix< TValueType >::row_iterator::check(), ug::SparseMatrix< TValueType >::cols, and ug::SparseMatrix< TValueType >::row_iterator::i.
operator!=()
template<typename TValueType > bool ug::SparseMatrix< TValueType >::row_iterator::operator!= (const row_iterator & o) const inline
References ug::SparseMatrix< TValueType >::row_iterator::i.
operator++()
template<typename TValueType > void ug::SparseMatrix< TValueType >::row_iterator::operator++ () inline
References ug::SparseMatrix< TValueType >::row_iterator::i.
operator+=()
template<typename TValueType > void ug::SparseMatrix< TValueType >::row_iterator::operator+= (int nr) inline
References ug::SparseMatrix< TValueType >::row_iterator::i.
operator->()
template<typename TValueType > row_iterator* ug::SparseMatrix< TValueType >::row_iterator::operator-> () inline
operator==()
template<typename TValueType > bool ug::SparseMatrix< TValueType >::row_iterator::operator== (const row_iterator & other) const inline
References ug::SparseMatrix< TValueType >::row_iterator::check(), and ug::SparseMatrix< TValueType >::row_iterator::i.
value()
template<typename TValueType > value_type& ug::SparseMatrix< TValueType >::row_iterator::value () inline
References ug::SparseMatrix< TValueType >::row_iterator::A, ug::SparseMatrix< TValueType >::row_iterator::check(), ug::SparseMatrix< TValueType >::row_iterator::i, and ug::SparseMatrix< TValueType >::values.
Member Data Documentation
_row
template<typename TValueType > size_t ug::SparseMatrix< TValueType >::row_iterator::_row private
Referenced by ug::SparseMatrix< TValueType >::row_iterator::check(), ug::SparseMatrix< TValueType >::row_iterator::row_iterator(), and ug::SparseMatrix< TValueType >::row_iterator::~row_iterator().
A
template<typename TValueType > SparseMatrix& ug::SparseMatrix< TValueType >::row_iterator::A private
Referenced by ug::SparseMatrix< TValueType >::row_iterator::check(), ug::SparseMatrix< TValueType >::row_iterator::index(), ug::SparseMatrix< TValueType >::row_iterator::row_iterator(), ug::SparseMatrix< TValueType >::row_iterator::value(), and ug::SparseMatrix< TValueType >::row_iterator::~row_iterator().
i
template<typename TValueType > size_t ug::SparseMatrix< TValueType >::row_iterator::i private
Referenced by ug::SparseMatrix< TValueType >::row_iterator::check(), ug::SparseMatrix< TValueType >::row_iterator::index(), ug::SparseMatrix< TValueType >::row_iterator::operator!=(), ug::SparseMatrix< TValueType >::row_iterator::operator++(), ug::SparseMatrix< TValueType >::row_iterator::operator+=(), ug::SparseMatrix< TValueType >::row_iterator::operator==(), and ug::SparseMatrix< TValueType >::row_iterator::value().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/cpu_algebra/sparsematrix.h