ug4: ug::MathTensor< TRank, N, T > Class Template Reference
ug::MathTensor< TRank, N, T > Class Template Reference
ugbase » Math » Tensor
a mathematical Tensor of rank TRank and N entries.
#include <math_tensor.h>
Public Types
typedef size_t size_type
typedef MathTensor< TRank-1, N, T > value_type
Public Member Functions
MathTensor ()
MathTensor (const MathTensor &v)
MathTensor & operator= (const MathTensor &v)
MathTensor & operator= (T val)
sets all values of the tensor to a value
value_type & operator[] (size_t i)
const value_type & operator[] (size_t i) const
size_t rank () const
void set (T val)
size_t size () const
Static Public Attributes
static const size_t Dimension = N
static const size_t Rank = TRank
Protected Member Functions
void assign (const MathTensor< TRank, N, T > &v)
Protected Attributes
value_type m_data [N]
Detailed Description
template<size_t TRank, size_t N, typename T>
class ug::MathTensor< TRank, N, T >
a mathematical Tensor of rank TRank and N entries.
Member Typedef Documentation
size_type
template<size_t TRank, size_t N, typename T > typedef size_t ug::MathTensor< TRank, N, T >::size_type
value_type
template<size_t TRank, size_t N, typename T > typedef MathTensor<TRank-1, N, T> ug::MathTensor< TRank, N, T >::value_type
Constructor & Destructor Documentation
MathTensor() [1/2]
template<size_t TRank, size_t N, typename T > ug::MathTensor< TRank, N, T >::MathTensor () inline
MathTensor() [2/2]
template<size_t TRank, size_t N, typename T > ug::MathTensor< TRank, N, T >::MathTensor (const MathTensor< TRank, N, T > & v) inline
References ug::MathTensor< TRank, N, T >::assign().
Member Function Documentation
assign()
template<size_t TRank, size_t N, typename T > void ug::MathTensor< TRank, N, T >::assign (const MathTensor< TRank, N, T > & v) inline protected
References ug::MathTensor< TRank, N, T >::m_data.
Referenced by ug::MathTensor< TRank, N, T >::MathTensor(), ug::MathTensor< 1, N, T >::MathTensor(), ug::MathTensor< TRank, N, T >::operator=(), and ug::MathTensor< 1, N, T >::operator=().
operator=() [1/2]
template<size_t TRank, size_t N, typename T > MathTensor& ug::MathTensor< TRank, N, T >::operator= (const MathTensor< TRank, N, T > & v) inline
References ug::MathTensor< TRank, N, T >::assign().
operator=() [2/2]
template<size_t TRank, size_t N, typename T > MathTensor& ug::MathTensor< TRank, N, T >::operator= (T val) inline
sets all values of the tensor to a value
References ug::MathTensor< TRank, N, T >::set().
operator[]() [1/2]
template<size_t TRank, size_t N, typename T > value_type& ug::MathTensor< TRank, N, T >::operator[] (size_t i) inline
References ug::MathTensor< TRank, N, T >::m_data, ug::MathTensor< TRank, N, T >::size(), and UG_ASSERT.
operator[]() [2/2]
template<size_t TRank, size_t N, typename T > const value_type& ug::MathTensor< TRank, N, T >::operator[] (size_t i) const inline
References ug::MathTensor< TRank, N, T >::m_data, ug::MathTensor< TRank, N, T >::size(), and UG_ASSERT.
rank()
template<size_t TRank, size_t N, typename T > size_t ug::MathTensor< TRank, N, T >::rank () const inline
set()
template<size_t TRank, size_t N, typename T > void ug::MathTensor< TRank, N, T >::set (T val) inline
References ug::MathTensor< TRank, N, T >::m_data, and ug::MathTensor< TRank, N, T >::set().
Referenced by ug::MathTensor< 1, N, T >::MathTensor(), ug::MathTensor< TRank, N, T >::operator=(), ug::MathTensor< 1, N, T >::operator=(), ug::ConstUserTensor< TRank, dim >::set(), and ug::MathTensor< TRank, N, T >::set().
size()
template<size_t TRank, size_t N, typename T > size_t ug::MathTensor< TRank, N, T >::size () const inline
Referenced by ug::IsFiniteAndNotTooBig(), ug::operator<<(), ug::MathTensor< TRank, N, T >::operator[](), and ug::MathTensor< 1, N, T >::operator[]().
Member Data Documentation
Dimension
template<size_t TRank, size_t N, typename T > const size_t ug::MathTensor< TRank, N, T >::Dimension = N static
m_data
template<size_t TRank, size_t N, typename T > value_type ug::MathTensor< TRank, N, T >::m_data[N] protected
Referenced by ug::MathTensor< 1, N, T >::assign(), ug::MathTensor< TRank, N, T >::assign(), ug::MathTensor< TRank, N, T >::operator[](), ug::MathTensor< 1, N, T >::operator[](), ug::MathTensor< TRank, N, T >::set(), and ug::MathTensor< 1, N, T >::set().
Rank
template<size_t TRank, size_t N, typename T > const size_t ug::MathTensor< TRank, N, T >::Rank = TRank static
The documentation for this class was generated from the following file:
ugbase/common/math/math_vector_matrix/math_tensor.h