ug4: ug::GaussQuadBase< TImpl, TDim, TOrder, TNip > Class Template Reference
ug::GaussQuadBase< TImpl, TDim, TOrder, TNip > Class Template Reference
wrapper to ease implementation
#include <gauss_quad.h>
Public Types
typedef MathVector< dim > position_type
Position Type in Reference Element Space.
typedef number weight_type
Type of weights.
Static Public Member Functions
static size_t order ()
returns the order
static const MathVector< dim > & point (size_t i)
returns i'th integration point
static const MathVector< dim > * points ()
returns all positions in an array of size()
static size_t size ()
number of integration points
static number weight (size_t i)
return the i'th weight
static const number * weights ()
returns all weights in an array of size()
Static Public Attributes
static const size_t dim = TDim
Dimension of integration domain.
static const size_t nip = TNip
Number of integration points.
static const size_t p = TOrder
Order of quadrature rule.
Protected Member Functions
MathVector< 1 > m_vPoint [10]
MathVector< 2 > m_vPoint [10]
MathVector< 2 > m_vPoint [12]
MathVector< 2 > m_vPoint [12]
MathVector< 2 > m_vPoint [12]
MathVector< 3 > m_vPoint [14]
MathVector< 3 > m_vPoint [15]
MathVector< 3 > m_vPoint [16]
MathVector< 2 > m_vPoint [16]
MathVector< 2 > m_vPoint [16]
MathVector< 2 > m_vPoint [17]
MathVector< 2 > m_vPoint [19]
MathVector< 1 > m_vPoint [1]
MathVector< 2 > m_vPoint [1]
MathVector< 3 > m_vPoint [1]
MathVector< 2 > m_vPoint [1]
MathVector< 0 > m_vPoint [1]
MathVector< 2 > m_vPoint [24]
MathVector< 3 > m_vPoint [24]
MathVector< 2 > m_vPoint [25]
MathVector< 2 > m_vPoint [28]
MathVector< 1 > m_vPoint [2]
MathVector< 3 > m_vPoint [31]
MathVector< 3 > m_vPoint [31]
MathVector< 2 > m_vPoint [33]
MathVector< 2 > m_vPoint [33]
MathVector< 1 > m_vPoint [3]
MathVector< 2 > m_vPoint [3]
MathVector< 3 > m_vPoint [43]
MathVector< 3 > m_vPoint [47]
MathVector< 1 > m_vPoint [4]
MathVector< 2 > m_vPoint [4]
MathVector< 2 > m_vPoint [4]
MathVector< 3 > m_vPoint [4]
MathVector< 2 > m_vPoint [4]
MathVector< 3 > m_vPoint [58]
MathVector< 1 > m_vPoint [5]
MathVector< 1 > m_vPoint [6]
MathVector< 3 > m_vPoint [6]
MathVector< 3 > m_vPoint [6]
MathVector< 3 > m_vPoint [6]
MathVector< 2 > m_vPoint [6]
MathVector< 2 > m_vPoint [6]
MathVector< 1 > m_vPoint [7]
MathVector< 2 > m_vPoint [7]
MathVector< 3 > m_vPoint [7]
MathVector< 2 > m_vPoint [7]
MathVector< 1 > m_vPoint [8]
MathVector< 3 > m_vPoint [8]
MathVector< 3 > m_vPoint [8]
MathVector< 3 > m_vPoint [8]
MathVector< 3 > m_vPoint [90]
MathVector< 1 > m_vPoint [9]
number m_vWeight [10]
number m_vWeight [10]
number m_vWeight [12]
number m_vWeight [12]
number m_vWeight [12]
number m_vWeight [14]
number m_vWeight [15]
number m_vWeight [16]
number m_vWeight [16]
number m_vWeight [16]
number m_vWeight [17]
number m_vWeight [19]
number m_vWeight [1]
number m_vWeight [1]
number m_vWeight [1]
number m_vWeight [1]
number m_vWeight [1]
number m_vWeight [24]
number m_vWeight [24]
number m_vWeight [25]
number m_vWeight [28]
number m_vWeight [2]
number m_vWeight [31]
number m_vWeight [31]
number m_vWeight [33]
number m_vWeight [33]
number m_vWeight [3]
number m_vWeight [3]
number m_vWeight [43]
number m_vWeight [47]
number m_vWeight [4]
number m_vWeight [4]
number m_vWeight [4]
number m_vWeight [4]
number m_vWeight [4]
number m_vWeight [58]
number m_vWeight [5]
number m_vWeight [6]
number m_vWeight [6]
number m_vWeight [6]
number m_vWeight [6]
number m_vWeight [6]
number m_vWeight [6]
number m_vWeight [7]
number m_vWeight [7]
number m_vWeight [7]
number m_vWeight [7]
number m_vWeight [8]
number m_vWeight [8]
number m_vWeight [8]
number m_vWeight [8]
number m_vWeight [90]
number m_vWeight [9]
Static Protected Attributes
static MathVector< dim > m_vPoint [nip]
integration points
static number m_vWeight [nip]
weights
Detailed Description
template<typename TImpl, int TDim, int TOrder, int TNip>
class ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >
wrapper to ease implementation
Member Typedef Documentation
position_type
template<typename TImpl , int TDim, int TOrder, int TNip> typedef MathVector<dim> ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::position_type
Position Type in Reference Element Space.
weight_type
template<typename TImpl , int TDim, int TOrder, int TNip> typedef number ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::weight_type
Type of weights.
Member Function Documentation
m_vPoint() [1/53]
MathVector< 1 > ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 19 >, 1, 19, 10 >::m_vPoint protected
m_vPoint() [2/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 6 >, 2, 6, 10 >::m_vPoint protected
m_vPoint() [3/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 7 >, 2, 7, 12 >::m_vPoint protected
m_vPoint() [4/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 6 >, 2, 6, 12 >::m_vPoint protected
m_vPoint() [5/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 7 >, 2, 7, 12 >::m_vPoint protected
m_vPoint() [6/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 5 >, 3, 5, 14 >::m_vPoint protected
m_vPoint() [7/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 5 >, 3, 5, 15 >::m_vPoint protected
m_vPoint() [8/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceOctahedron, 2 >, 3, 2, 16 >::m_vPoint protected
m_vPoint() [9/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 8 >, 2, 8, 16 >::m_vPoint protected
m_vPoint() [10/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 8 >, 2, 8, 16 >::m_vPoint protected
m_vPoint() [11/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 9 >, 2, 9, 17 >::m_vPoint protected
m_vPoint() [12/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 9 >, 2, 9, 19 >::m_vPoint protected
m_vPoint() [13/53]
MathVector< 1 > ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 1 >, 1, 1, 1 >::m_vPoint protected
m_vPoint() [14/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 1 >, 2, 1, 1 >::m_vPoint protected
m_vPoint() [15/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 1 >, 3, 1, 1 >::m_vPoint protected
m_vPoint() [16/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 1 >, 2, 1, 1 >::m_vPoint protected
m_vPoint() [17/53]
MathVector< 0 > ug::GaussQuadBase< GaussQuadrature< ReferenceVertex, 0 >, 0, 0, 1 >::m_vPoint protected
m_vPoint() [18/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 11 >, 2, 11, 24 >::m_vPoint protected
m_vPoint() [19/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 6 >, 3, 6, 24 >::m_vPoint protected
m_vPoint() [20/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 10 >, 2, 10, 25 >::m_vPoint protected
m_vPoint() [21/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 11 >, 2, 11, 28 >::m_vPoint protected
m_vPoint() [22/53]
MathVector< 1 > ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 3 >, 1, 3, 2 >::m_vPoint protected
m_vPoint() [23/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 7 >, 3, 7, 31 >::m_vPoint protected
m_vPoint() [24/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 7 >, 3, 7, 31 >::m_vPoint protected
m_vPoint() [25/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 13 >, 2, 13, 33 >::m_vPoint protected
m_vPoint() [26/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 12 >, 2, 12, 33 >::m_vPoint protected
m_vPoint() [27/53]
MathVector< 1 > ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 5 >, 1, 5, 3 >::m_vPoint protected
m_vPoint() [28/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 2 >, 2, 2, 3 >::m_vPoint protected
m_vPoint() [29/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 8 >, 3, 8, 43 >::m_vPoint protected
m_vPoint() [30/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 8 >, 3, 8, 47 >::m_vPoint protected
m_vPoint() [31/53]
MathVector< 1 > ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 7 >, 1, 7, 4 >::m_vPoint protected
m_vPoint() [32/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 2 >, 2, 2, 4 >::m_vPoint protected
m_vPoint() [33/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 3 >, 2, 3, 4 >::m_vPoint protected
m_vPoint() [34/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 2 >, 3, 2, 4 >::m_vPoint protected
m_vPoint() [35/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 3 >, 2, 3, 4 >::m_vPoint protected
m_vPoint() [36/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 9 >, 3, 9, 58 >::m_vPoint protected
m_vPoint() [37/53]
MathVector< 1 > ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 9 >, 1, 9, 5 >::m_vPoint protected
m_vPoint() [38/53]
MathVector< 1 > ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 11 >, 1, 11, 6 >::m_vPoint protected
m_vPoint() [39/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 3 >, 3, 3, 6 >::m_vPoint protected
m_vPoint() [40/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferencePrism, 0 >, 3, 0, 6 >::m_vPoint protected
m_vPoint() [41/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferencePrism, 2 >, 3, 2, 6 >::m_vPoint protected
m_vPoint() [42/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 4 >, 2, 4, 6 >::m_vPoint protected
m_vPoint() [43/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 4 >, 2, 4, 6 >::m_vPoint protected
m_vPoint() [44/53]
MathVector< 1 > ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 13 >, 1, 13, 7 >::m_vPoint protected
m_vPoint() [45/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 5 >, 2, 5, 7 >::m_vPoint protected
m_vPoint() [46/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 0 >, 3, 0, 7 >::m_vPoint protected
m_vPoint() [47/53]
MathVector< 2 > ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 5 >, 2, 5, 7 >::m_vPoint protected
m_vPoint() [48/53]
MathVector< 1 > ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 15 >, 1, 15, 8 >::m_vPoint protected
m_vPoint() [49/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 2 >, 3, 2, 8 >::m_vPoint protected
m_vPoint() [50/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferencePyramid, 2 >, 3, 2, 8 >::m_vPoint protected
m_vPoint() [51/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 3 >, 3, 3, 8 >::m_vPoint protected
m_vPoint() [52/53]
MathVector< 3 > ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 11 >, 3, 11, 90 >::m_vPoint protected
m_vPoint() [53/53]
MathVector< 1 > ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 17 >, 1, 17, 9 >::m_vPoint protected
m_vWeight() [1/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 19 >, 1, 19, 10 >::m_vWeight protected
m_vWeight() [2/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 6 >, 2, 6, 10 >::m_vWeight protected
m_vWeight() [3/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 7 >, 2, 7, 12 >::m_vWeight protected
m_vWeight() [4/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 6 >, 2, 6, 12 >::m_vWeight protected
m_vWeight() [5/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 7 >, 2, 7, 12 >::m_vWeight protected
m_vWeight() [6/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 5 >, 3, 5, 14 >::m_vWeight protected
m_vWeight() [7/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 5 >, 3, 5, 15 >::m_vWeight protected
m_vWeight() [8/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceOctahedron, 2 >, 3, 2, 16 >::m_vWeight protected
m_vWeight() [9/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 8 >, 2, 8, 16 >::m_vWeight protected
m_vWeight() [10/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 8 >, 2, 8, 16 >::m_vWeight protected
m_vWeight() [11/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 9 >, 2, 9, 17 >::m_vWeight protected
m_vWeight() [12/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 9 >, 2, 9, 19 >::m_vWeight protected
m_vWeight() [13/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 1 >, 1, 1, 1 >::m_vWeight protected
m_vWeight() [14/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 1 >, 2, 1, 1 >::m_vWeight protected
m_vWeight() [15/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 1 >, 3, 1, 1 >::m_vWeight protected
m_vWeight() [16/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 1 >, 2, 1, 1 >::m_vWeight protected
m_vWeight() [17/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceVertex, 0 >, 0, 0, 1 >::m_vWeight protected
m_vWeight() [18/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 11 >, 2, 11, 24 >::m_vWeight protected
m_vWeight() [19/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 6 >, 3, 6, 24 >::m_vWeight protected
m_vWeight() [20/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 10 >, 2, 10, 25 >::m_vWeight protected
m_vWeight() [21/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 11 >, 2, 11, 28 >::m_vWeight protected
m_vWeight() [22/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 3 >, 1, 3, 2 >::m_vWeight protected
m_vWeight() [23/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 7 >, 3, 7, 31 >::m_vWeight protected
m_vWeight() [24/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 7 >, 3, 7, 31 >::m_vWeight protected
m_vWeight() [25/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 13 >, 2, 13, 33 >::m_vWeight protected
m_vWeight() [26/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 12 >, 2, 12, 33 >::m_vWeight protected
m_vWeight() [27/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 5 >, 1, 5, 3 >::m_vWeight protected
m_vWeight() [28/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 2 >, 2, 2, 3 >::m_vWeight protected
m_vWeight() [29/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 8 >, 3, 8, 43 >::m_vWeight protected
m_vWeight() [30/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 8 >, 3, 8, 47 >::m_vWeight protected
m_vWeight() [31/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 7 >, 1, 7, 4 >::m_vWeight protected
m_vWeight() [32/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 2 >, 2, 2, 4 >::m_vWeight protected
m_vWeight() [33/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 3 >, 2, 3, 4 >::m_vWeight protected
m_vWeight() [34/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 2 >, 3, 2, 4 >::m_vWeight protected
m_vWeight() [35/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 3 >, 2, 3, 4 >::m_vWeight protected
m_vWeight() [36/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 9 >, 3, 9, 58 >::m_vWeight protected
m_vWeight() [37/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 9 >, 1, 9, 5 >::m_vWeight protected
m_vWeight() [38/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 11 >, 1, 11, 6 >::m_vWeight protected
m_vWeight() [39/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 3 >, 3, 3, 6 >::m_vWeight protected
m_vWeight() [40/53]
number ug::GaussQuadBase< GaussQuadrature< ReferencePrism, 0 >, 3, 0, 6 >::m_vWeight protected
m_vWeight() [41/53]
number ug::GaussQuadBase< GaussQuadrature< ReferencePrism, 2 >, 3, 2, 6 >::m_vWeight protected
m_vWeight() [42/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 4 >, 2, 4, 6 >::m_vWeight protected
m_vWeight() [43/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 4 >, 2, 4, 6 >::m_vWeight protected
m_vWeight() [44/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 13 >, 1, 13, 7 >::m_vWeight protected
m_vWeight() [45/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceQuadrilateral, 5 >, 2, 5, 7 >::m_vWeight protected
m_vWeight() [46/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 0 >, 3, 0, 7 >::m_vWeight protected
m_vWeight() [47/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTriangle, 5 >, 2, 5, 7 >::m_vWeight protected
m_vWeight() [48/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 15 >, 1, 15, 8 >::m_vWeight protected
m_vWeight() [49/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 2 >, 3, 2, 8 >::m_vWeight protected
m_vWeight() [50/53]
number ug::GaussQuadBase< GaussQuadrature< ReferencePyramid, 2 >, 3, 2, 8 >::m_vWeight protected
m_vWeight() [51/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceTetrahedron, 3 >, 3, 3, 8 >::m_vWeight protected
m_vWeight() [52/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceHexahedron, 11 >, 3, 11, 90 >::m_vWeight protected
m_vWeight() [53/53]
number ug::GaussQuadBase< GaussQuadrature< ReferenceEdge, 17 >, 1, 17, 9 >::m_vWeight protected
order()
template<typename TImpl , int TDim, int TOrder, int TNip> static size_t ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::order () inline static
returns the order
References ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::p.
Referenced by ug::TestQuadRule().
point()
template<typename TImpl , int TDim, int TOrder, int TNip> static const MathVector<dim>& ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::point (size_t i) inline static
returns i'th integration point
References ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::m_vPoint, ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::size(), and UG_ASSERT.
Referenced by ug::TestQuadRule().
points()
template<typename TImpl , int TDim, int TOrder, int TNip> static const MathVector<dim>* ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::points () inline static
returns all positions in an array of size()
References ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::m_vPoint.
size()
template<typename TImpl , int TDim, int TOrder, int TNip> static size_t ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::size () inline static
number of integration points
References ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::nip.
Referenced by ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::point(), ug::TestQuadRule(), and ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::weight().
weight()
template<typename TImpl , int TDim, int TOrder, int TNip> static number ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::weight (size_t i) inline static
return the i'th weight
References ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::m_vWeight, ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::size(), and UG_ASSERT.
Referenced by ug::TestQuadRule().
weights()
template<typename TImpl , int TDim, int TOrder, int TNip> static const number* ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::weights () inline static
returns all weights in an array of size()
References ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::m_vWeight.
Member Data Documentation
dim
template<typename TImpl , int TDim, int TOrder, int TNip> const size_t ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::dim = TDim static
Dimension of integration domain.
m_vPoint
template<typename TImpl , int TDim, int TOrder, int TNip> MathVector<dim> ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::m_vPoint[nip] static protected
integration points
Referenced by ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::point(), and ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::points().
m_vWeight
template<typename TImpl , int TDim, int TOrder, int TNip> number ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::m_vWeight[nip] static protected
weights
Referenced by ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::weight(), and ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::weights().
nip
template<typename TImpl , int TDim, int TOrder, int TNip> const size_t ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::nip = TNip static
Number of integration points.
Referenced by ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::size().
p
template<typename TImpl , int TDim, int TOrder, int TNip> const size_t ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::p = TOrder static
Order of quadrature rule.
Referenced by ug::GaussQuadBase< TImpl, TDim, TOrder, TNip >::order().
The documentation for this class was generated from the following file:
ugbase/lib_disc/quadrature/gauss/gauss_quad.h