ug4: ug::ParallelProgress Class Reference
ug::ParallelProgress Class Reference
#include <parallel_progress.h>
Public Member Functions
void calc_next_value ()
ParallelProgress ()
void set (double now)
void set (int now)
void set (size_t now)
void set_length (int l)
void setD (double now)
void start (double total, std::string msg, size_t numProc)
void stop ()
~ParallelProgress ()
Private Attributes
double dNextValueToUpdate
size_t iNextValueToUpdate
int m_length
std::string m_msg
double m_now
double m_total
int posNow
double startS
Constructor & Destructor Documentation
ParallelProgress()
ug::ParallelProgress::ParallelProgress ()
References m_length.
~ParallelProgress()
ug::ParallelProgress::~ParallelProgress () inline
References stop().
Member Function Documentation
calc_next_value()
void ug::ParallelProgress::calc_next_value () inline
References dNextValueToUpdate, iNextValueToUpdate, m_length, m_total, and posNow.
Referenced by setD(), and start().
set() [1/3]
void ug::ParallelProgress::set (double now) inline
References dNextValueToUpdate, and setD().
set() [2/3]
void ug::ParallelProgress::set (int now) inline
References iNextValueToUpdate, and setD().
set() [3/3]
void ug::ParallelProgress::set (size_t now) inline
References iNextValueToUpdate, and setD().
set_length()
void ug::ParallelProgress::set_length (int l) inline
References m_length.
setD()
void ug::ParallelProgress::setD (double now)
References calc_next_value(), ug::LogAssistant::flush(), ug::GetLogAssistant(), m_length, m_now, m_total, posNow, and ug::print_mark().
Referenced by set(), and stop().
start()
void ug::ParallelProgress::start (double total, std::string msg, size_t numProc)
References calc_next_value(), ug::get_clock_s(), m_length, m_msg, m_now, m_total, posNow, pcl::ProcRank(), startS, and UG_LOG.
stop()
void ug::ParallelProgress::stop ()
References ug::get_clock_s(), m_total, ug::reset_floats(), setD(), startS, and UG_LOG.
Referenced by ~ParallelProgress().
Member Data Documentation
dNextValueToUpdate
double ug::ParallelProgress::dNextValueToUpdate private
Referenced by calc_next_value(), and set().
iNextValueToUpdate
size_t ug::ParallelProgress::iNextValueToUpdate private
Referenced by calc_next_value(), and set().
m_length
int ug::ParallelProgress::m_length private
Referenced by calc_next_value(), ParallelProgress(), set_length(), setD(), and start().
m_msg
std::string ug::ParallelProgress::m_msg private
Referenced by start().
m_now
double ug::ParallelProgress::m_now private
Referenced by setD(), and start().
m_total
double ug::ParallelProgress::m_total private
Referenced by calc_next_value(), setD(), start(), and stop().
posNow
int ug::ParallelProgress::posNow private
Referenced by calc_next_value(), setD(), and start().
startS
double ug::ParallelProgress::startS private
Referenced by start(), and stop().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/operator/preconditioner/schur/parallel_progress.h
ugbase/lib_algebra/operator/preconditioner/schur/parallel_progress.cpp