ug4: ug::AssemblingTuner< TAlgebra > Class Template Reference
ug::AssemblingTuner< TAlgebra > Class Template Reference
The AssemblingTuner class combines tools to adapt the assembling routine.
#include <ass_tuner.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef algebra_type::matrix_type matrix_type
Type of algebra matrix.
typedef vector_type::value_type value_type
Type of algebra value.
typedef algebra_type::vector_type vector_type
Type of algebra vector.
Public Member Functions
void add_local_mat_to_global (matrix_type &mat, const LocalMatrix &lmat, ConstSmartPtr< DoFDistribution > dd) const
void add_local_vec_to_global (vector_type &vec, const LocalVector &lvec, ConstSmartPtr< DoFDistribution > dd) const
LocalToGlobalMapper-function calls.
AssemblingTuner ()
constructor
template<typename TElem >
void collect_selected_elements (std::vector< TElem *> &vElem, ConstSmartPtr< DoFDistribution > dd, int si) const
gets the element iterator from the Selector
bool constraint_type_enabled (int type) const
returns if constraint type enabled
void disable_single_index_assembling ()
sets an index for which the assembling should be carried out
bool elem_disc_type_enabled (int type) const
returns if elem disc type enabled
template<typename TElem >
bool element_used (TElem *elem) const
returns if element is to be used in assembling
void enable_constraints (int bEnableTypes)
enables constraints
void enable_elem_discs (int bEnableTypes)
enables elem discs
void enable_modify_solution (bool bEnable)
enables the usage of modify solution
int enabled_constraints () const
returns flags of enabled constraints
int enabled_elem_discs () const
returns flags of enabled elem discs
bool matrix_is_const () const
void modify_LocalSol (LocalVector &vecMod, const LocalVector &lvec, ConstSmartPtr< DoFDistribution > dd) const
bool modify_solution_enabled () const
checks whether the assemble index is set or not
bool regular_grid_forced () const
returns if assembling is to considered as regular grid
void resize (ConstSmartPtr< DoFDistribution > dd, vector_type &vec) const
resize functions used in assemble funcs
void resize (ConstSmartPtr< DoFDistribution > dd, matrix_type &mat) const
bool selected_elements_used () const
returns if only selected elements used for assembling
void set_dirichlet_row (matrix_type &mat, const DoFIndex &ind) const
void set_dirichlet_val (vector_type &vec, const DoFIndex &ind, const double val) const
void set_force_regular_grid (bool bForce)
forces the assembling to consider the grid as regular
void set_mapping (ILocalToGlobalMapper< TAlgebra > *pMapper=NULL)
set local to global mapping
void set_marker (BoolMarker *mark=NULL)
sets a marker to exclude elements from assembling
void set_matrix_is_const (bool bCh)
void set_selector (Selector *sel=NULL)
sets a selector of elements for assembling
void set_single_index_assembling (const size_t index)
bool single_index_assembling_enabled () const
checks whether the assemble DoFindex is set or not
Protected Attributes
bool m_bForceRegGrid
forces the assembling to regard the grid as regular
bool m_bMatrixIsConst
disables matrix assembling if set to false
bool m_bModifySolutionImplemented
bool m_bSingleAssIndex
object for DoFindex-wise assemble routine
int m_ConstraintTypesEnabled
enables the constraints
int m_ElemTypesEnabled
enables the constraints
BoolMarker * m_pBoolMarker
marker used to skip elements
ILocalToGlobalMapper< TAlgebra > * m_pMapper
LocalToGlobalMapper.
LocalToGlobalMapper< TAlgebra > m_pMapperCommon
default LocalToGlobalMapper
Selector * m_pSelector
selector used to set a list of elements for the assembling
size_t m_SingleAssIndex
Detailed Description
template<typename TAlgebra>
class ug::AssemblingTuner< TAlgebra >
The AssemblingTuner class combines tools to adapt the assembling routine.
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::AssemblingTuner< TAlgebra >::algebra_type
Algebra type.
matrix_type
template<typename TAlgebra > typedef algebra_type::matrix_type ug::AssemblingTuner< TAlgebra >::matrix_type
Type of algebra matrix.
value_type
template<typename TAlgebra > typedef vector_type::value_type ug::AssemblingTuner< TAlgebra >::value_type
Type of algebra value.
vector_type
template<typename TAlgebra > typedef algebra_type::vector_type ug::AssemblingTuner< TAlgebra >::vector_type
Type of algebra vector.
Constructor & Destructor Documentation
AssemblingTuner()
template<typename TAlgebra > ug::AssemblingTuner< TAlgebra >::AssemblingTuner () inline
constructor
Member Function Documentation
add_local_mat_to_global()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::add_local_mat_to_global (matrix_type & mat, const LocalMatrix & lmat, ConstSmartPtr< DoFDistribution > dd) const inline
add_local_vec_to_global()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::add_local_vec_to_global (vector_type & vec, const LocalVector & lvec, ConstSmartPtr< DoFDistribution > dd) const inline
LocalToGlobalMapper-function calls.
collect_selected_elements()
template<typename TAlgebra > template<typename TElem > void ug::AssemblingTuner< TAlgebra >::collect_selected_elements (std::vector< TElem *> & vElem, ConstSmartPtr< DoFDistribution > dd, int si) const
gets the element iterator from the Selector
References ug::Selector::begin(), ug::Selector::end(), ug::ISubsetHandler::get_subset_index(), ug::DoFDistributionInfoProvider::subset_handler(), and UG_THROW.
constraint_type_enabled()
template<typename TAlgebra > bool ug::AssemblingTuner< TAlgebra >::constraint_type_enabled (int type) const inline
returns if constraint type enabled
disable_single_index_assembling()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::disable_single_index_assembling () inline
sets an index for which the assembling should be carried out
This methods sets a boolean if an DoFindex-wise assemble routine should be used. This proceeding is e.g. useful for a nonlinear Gauss-Seidel or nonlinear Jacobi solver. The specific index is passed.
Parameters
[in] ind DoFIndex
elem_disc_type_enabled()
template<typename TAlgebra > bool ug::AssemblingTuner< TAlgebra >::elem_disc_type_enabled (int type) const inline
returns if elem disc type enabled
References resize().
element_used()
template<typename TAlgebra > template<typename TElem > bool ug::AssemblingTuner< TAlgebra >::element_used (TElem * elem) const
returns if element is to be used in assembling
enable_constraints()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::enable_constraints (int bEnableTypes) inline
enables constraints
enable_elem_discs()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::enable_elem_discs (int bEnableTypes) inline
enables elem discs
enable_modify_solution()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::enable_modify_solution (bool bEnable) inline
enables the usage of modify solution
enabled_constraints()
template<typename TAlgebra > int ug::AssemblingTuner< TAlgebra >::enabled_constraints () const inline
returns flags of enabled constraints
enabled_elem_discs()
template<typename TAlgebra > int ug::AssemblingTuner< TAlgebra >::enabled_elem_discs () const inline
returns flags of enabled elem discs
matrix_is_const()
template<typename TAlgebra > bool ug::AssemblingTuner< TAlgebra >::matrix_is_const () const inline
whether matrix is to be modified by assembling
Returns
true iff matrix is not to be modified
modify_LocalSol()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::modify_LocalSol (LocalVector & vecMod, const LocalVector & lvec, ConstSmartPtr< DoFDistribution > dd) const inline
modify_solution_enabled()
template<typename TAlgebra > bool ug::AssemblingTuner< TAlgebra >::modify_solution_enabled () const inline
checks whether the assemble index is set or not
regular_grid_forced()
template<typename TAlgebra > bool ug::AssemblingTuner< TAlgebra >::regular_grid_forced () const inline
returns if assembling is to considered as regular grid
resize() [1/2]
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::resize (ConstSmartPtr< DoFDistribution > dd, vector_type & vec) const
resize functions used in assemble funcs
References ug::DoFDistribution::num_indices().
resize() [2/2]
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::resize (ConstSmartPtr< DoFDistribution > dd, matrix_type & mat) const
References ug::DoFDistribution::num_indices().
selected_elements_used()
template<typename TAlgebra > bool ug::AssemblingTuner< TAlgebra >::selected_elements_used () const inline
returns if only selected elements used for assembling
set_dirichlet_row()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::set_dirichlet_row (matrix_type & mat, const DoFIndex & ind) const
only one index will be set to Dirichlet in case of index-wise assembling instead of setting a complete matrix row to Dirichlet
References ug::SetDirichletRow(), and UG_THROW.
set_dirichlet_val()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::set_dirichlet_val (vector_type & vec, const DoFIndex & ind, const double val) const
References ug::BlockRef(), ug::DoFRef(), and UG_THROW.
set_force_regular_grid()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::set_force_regular_grid (bool bForce) inline
forces the assembling to consider the grid as regular
set_mapping()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::set_mapping (ILocalToGlobalMapper< TAlgebra > * pMapper = NULL) inline
set local to global mapping
set_marker()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::set_marker (BoolMarker * mark = NULL) inline
sets a marker to exclude elements from assembling
This methods sets a marker. Only elements that are marked will be assembled during assembling process. If no marker is set, this corresponds to a marker where all elements have been marked.
Parameters
[in] mark BoolMarker
set_matrix_is_const()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::set_matrix_is_const (bool bCh) inline
specify whether matrix will be modified by assembling disables matrix assembling if set to true
Parameters
bCh set true if matrix is not to be changed during assembling
set_selector()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::set_selector (Selector * sel = NULL) inline
sets a selector of elements for assembling
This methods sets an element list. Only elements of this list will be assembled during assembling process. The list especially defines the begin and end of the element-iterator in the element assembling-loop. If no element list is set, this corresponds to an assembling where the loop is carried out over all elements of a subset.
Parameters
[in] sel Selector
set_single_index_assembling()
template<typename TAlgebra > void ug::AssemblingTuner< TAlgebra >::set_single_index_assembling (const size_t index) inline
single_index_assembling_enabled()
template<typename TAlgebra > bool ug::AssemblingTuner< TAlgebra >::single_index_assembling_enabled () const inline
checks whether the assemble DoFindex is set or not
Member Data Documentation
m_bForceRegGrid
template<typename TAlgebra > bool ug::AssemblingTuner< TAlgebra >::m_bForceRegGrid protected
forces the assembling to regard the grid as regular
m_bMatrixIsConst
template<typename TAlgebra > bool ug::AssemblingTuner< TAlgebra >::m_bMatrixIsConst protected
disables matrix assembling if set to false
m_bModifySolutionImplemented
template<typename TAlgebra > bool ug::AssemblingTuner< TAlgebra >::m_bModifySolutionImplemented protected
calls the 'modify_solution()' method of constraints; gives the modified solution to the assembling methods
m_bSingleAssIndex
template<typename TAlgebra > bool ug::AssemblingTuner< TAlgebra >::m_bSingleAssIndex protected
object for DoFindex-wise assemble routine
m_ConstraintTypesEnabled
template<typename TAlgebra > int ug::AssemblingTuner< TAlgebra >::m_ConstraintTypesEnabled protected
enables the constraints
m_ElemTypesEnabled
template<typename TAlgebra > int ug::AssemblingTuner< TAlgebra >::m_ElemTypesEnabled protected
enables the constraints
m_pBoolMarker
template<typename TAlgebra > BoolMarker* ug::AssemblingTuner< TAlgebra >::m_pBoolMarker protected
marker used to skip elements
m_pMapper
template<typename TAlgebra > ILocalToGlobalMapper<TAlgebra>* ug::AssemblingTuner< TAlgebra >::m_pMapper protected
LocalToGlobalMapper.
m_pMapperCommon
template<typename TAlgebra > LocalToGlobalMapper<TAlgebra> ug::AssemblingTuner< TAlgebra >::m_pMapperCommon protected
default LocalToGlobalMapper
m_pSelector
template<typename TAlgebra > Selector* ug::AssemblingTuner< TAlgebra >::m_pSelector protected
selector used to set a list of elements for the assembling
m_SingleAssIndex
template<typename TAlgebra > size_t ug::AssemblingTuner< TAlgebra >::m_SingleAssIndex protected
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/ass_tuner.h
ugbase/lib_disc/spatial_disc/ass_tuner_impl.h