ug4: ug::ExpectedErrorMarkingStrategy< TDomain > Class Template Reference
ug::ExpectedErrorMarkingStrategy< TDomain > Class Template Reference
#include <error_elem_marking_strategy.h>
Public Types
typedef IElementMarkingStrategy< TDomain > base_type
Public Types inherited from ug::IElementMarkingStrategy< TDomain >
typedef Grid::AttachmentAccessor< elem_type, ug::Attachment< number > > elem_accessor_type
typedef domain_traits< dim >::element_type elem_type
element type to be marked
Public Member Functions
ExpectedErrorMarkingStrategy (number tol, int max_level, number safetyFactor, number expectedReductionFactor)
void mark (typename base_type::elem_accessor_type &aaError, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd)
DEPRECATED:
void set_expected_reduction_factor (number expectedReductionFactor)
void set_max_level (int max_level)
void set_safety_factor (number safetyFactor)
void set_tolerance (number tol)
Public Member Functions inherited from ug::IElementMarkingStrategy< TDomain >
number global_estimated_error () const
number global_estimated_error_per_elem_max () const
number global_estimated_error_per_elem_min () const
IElementMarkingStrategy ()
void mark (IMultigridElementIndicators< TDomain > &mgElemIndicators, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd)
This function marks all elements.
virtual ~IElementMarkingStrategy ()
Protected Member Functions
void merge_sorted_lists (std::vector< std::pair< number, int > >::iterator beginFirst, std::vector< std::pair< number, int > >::iterator beginSecond, std::vector< std::pair< number, int > >::iterator end)
Protected Attributes
number m_expRedFac
int m_max_level
number m_safety
number m_tol
Protected Attributes inherited from ug::IElementMarkingStrategy< TDomain >
number m_latest_error
number m_latest_error_per_elem_max
number m_latest_error_per_elem_min
Additional Inherited Members
Static Public Attributes inherited from ug::IElementMarkingStrategy< TDomain >
static const int dim = TDomain::dim
world dimension
Detailed Description
template<typename TDomain>
class ug::ExpectedErrorMarkingStrategy< TDomain >
Refine as many largest-error elements as necessary to reach tolerance. The expected tolerance is calculated using a user-given expected error reduction factor.
Member Typedef Documentation
base_type
template<typename TDomain > typedef IElementMarkingStrategy<TDomain> ug::ExpectedErrorMarkingStrategy< TDomain >::base_type
Constructor & Destructor Documentation
ExpectedErrorMarkingStrategy()
template<typename TDomain > ug::ExpectedErrorMarkingStrategy< TDomain >::ExpectedErrorMarkingStrategy (number tol, int max_level, number safetyFactor, number expectedReductionFactor) inline
Member Function Documentation
mark()
template<typename TDomain > void ug::ExpectedErrorMarkingStrategy< TDomain >::mark (typename base_type::elem_accessor_type & aaError, IRefiner & refiner, ConstSmartPtr< DoFDistribution > dd) virtual
DEPRECATED:
Implements ug::IElementMarkingStrategy< TDomain >.
References pcl::ProcessCommunicator::allreduce(), pcl::ProcessCommunicator::broadcast(), ug::ElementDebugInfo(), pcl::ProcessCommunicator::gatherv(), ug::GetDataPtr(), ug::IRefiner::grid(), ug::IRefiner::mark(), pcl::NumProcs(), p, PCL_DT_INT, PCL_RO_SUM, pcl::ProcRank(), ug::RM_REFINE, pcl::ProcessCommunicator::scatter(), UG_COND_THROW, UG_LOG_ALL_PROCS, and UG_LOGN.
merge_sorted_lists()
template<typename TDomain > void ug::ExpectedErrorMarkingStrategy< TDomain >::merge_sorted_lists (std::vector< std::pair< number, int > >::iterator beginFirst, std::vector< std::pair< number, int > >::iterator beginSecond, std::vector< std::pair< number, int > >::iterator end) protected
set_expected_reduction_factor()
template<typename TDomain > void ug::ExpectedErrorMarkingStrategy< TDomain >::set_expected_reduction_factor (number expectedReductionFactor) inline
References ug::ExpectedErrorMarkingStrategy< TDomain >::m_expRedFac.
set_max_level()
template<typename TDomain > void ug::ExpectedErrorMarkingStrategy< TDomain >::set_max_level (int max_level) inline
References ug::ExpectedErrorMarkingStrategy< TDomain >::m_max_level.
set_safety_factor()
template<typename TDomain > void ug::ExpectedErrorMarkingStrategy< TDomain >::set_safety_factor (number safetyFactor) inline
References ug::ExpectedErrorMarkingStrategy< TDomain >::m_safety.
set_tolerance()
template<typename TDomain > void ug::ExpectedErrorMarkingStrategy< TDomain >::set_tolerance (number tol) inline
References ug::ExpectedErrorMarkingStrategy< TDomain >::m_tol.
Member Data Documentation
m_expRedFac
template<typename TDomain > number ug::ExpectedErrorMarkingStrategy< TDomain >::m_expRedFac protected
Referenced by ug::ExpectedErrorMarkingStrategy< TDomain >::set_expected_reduction_factor().
m_max_level
template<typename TDomain > int ug::ExpectedErrorMarkingStrategy< TDomain >::m_max_level protected
Referenced by ug::ExpectedErrorMarkingStrategy< TDomain >::set_max_level().
m_safety
template<typename TDomain > number ug::ExpectedErrorMarkingStrategy< TDomain >::m_safety protected
Referenced by ug::ExpectedErrorMarkingStrategy< TDomain >::set_safety_factor().
m_tol
template<typename TDomain > number ug::ExpectedErrorMarkingStrategy< TDomain >::m_tol protected
Referenced by ug::ExpectedErrorMarkingStrategy< TDomain >::set_tolerance().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/error_elem_marking_strategy.h