ug4: ug::SparseVector< T > Class Template Reference
ug::SparseVector< T > Class Template Reference
#include <sparse_vector.h>
Classes
class const_iterator
class iterator
Public Types
typedef T value_type
Public Member Functions
const_iterator begin () const
const_iterator end () const
bool has_connection (size_t c) const
size_t num_connections () const
T & operator() (size_t c)
const T & operator() (size_t c) const
void print () const
size_t size ()
SparseVector (size_t s)
Private Types
typedef std::map< size_t, T > container
Private Attributes
container data
size_t m_size
Member Typedef Documentation
container
template<typename T> typedef std::map<size_t, T> ug::SparseVector< T >::container private
value_type
template<typename T> typedef T ug::SparseVector< T >::value_type
Constructor & Destructor Documentation
SparseVector()
template<typename T> ug::SparseVector< T >::SparseVector (size_t s) inline
Member Function Documentation
begin()
template<typename T> const_iterator ug::SparseVector< T >::begin () const inline
References ug::SparseVector< T >::data.
Referenced by ug::SparseVector< T >::print().
end()
template<typename T> const_iterator ug::SparseVector< T >::end () const inline
References ug::SparseVector< T >::data.
Referenced by ug::SparseVector< T >::print().
has_connection()
template<typename T> bool ug::SparseVector< T >::has_connection (size_t c) const inline
References ug::SparseVector< T >::data.
num_connections()
template<typename T> size_t ug::SparseVector< T >::num_connections () const inline
References ug::SparseVector< T >::data.
operator()() [1/2]
template<typename T> T& ug::SparseVector< T >::operator() (size_t c) inline
References ug::SparseVector< T >::data, and ug::SparseVector< T >::m_size.
operator()() [2/2]
template<typename T> const T& ug::SparseVector< T >::operator() (size_t c) const inline
References ug::SparseVector< T >::data, and ug::SparseVector< T >::m_size.
print()
template<typename T> void ug::SparseVector< T >::print () const inline
References ug::SparseVector< T >::begin(), ug::SparseVector< T >::end(), and UG_LOG.
size()
template<typename T> size_t ug::SparseVector< T >::size () inline
References ug::SparseVector< T >::m_size.
Member Data Documentation
data
template<typename T> container ug::SparseVector< T >::data private
Referenced by ug::SparseVector< T >::begin(), ug::SparseVector< T >::end(), ug::SparseVector< T >::has_connection(), ug::SparseVector< T >::num_connections(), and ug::SparseVector< T >::operator()().
m_size
template<typename T> size_t ug::SparseVector< T >::m_size private
Referenced by ug::SparseVector< T >::operator()(), and ug::SparseVector< T >::size().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/algebra_common/sparse_vector.h