ug4: ScalarMatrixAdapter< AT, ST > Class Template Reference
ScalarMatrixAdapter< AT, ST > Class Template Reference
#include <scalar_matrix_adapter.hh>
Classes
class const_row_iterator
class row_iterator
Public Types
typedef AT::matrix_type encapsulated_matrix_type
typedef ST::matrix_type::value_type value_type
Public Member Functions
row_iterator begin_row (size_t r)
const_row_iterator begin_row (size_t r) const
row_iterator end_row (size_t r)
const_row_iterator end_row (size_t r) const
size_t num_cols () const
returns the number of cols
size_t num_rows () const
returns number of rows
value_type & operator() (size_t r, size_t c)
ScalarMatrixAdapter< CPUAlgebra, CPUAlgebra >::value_type & operator() (size_t r, size_t c)
const value_type & operator() (size_t r, size_t c) const
void print (const char *text) const
print (underlying) matrix
void printrow (size_t row) const
print (block) row of (underlying) matrix
void resize_and_clear (size_t newRows, size_t newCols)
bool resize_and_keep_values (size_t newRows, size_t newCols)
ScalarMatrixAdapter (encapsulated_matrix_type &mat)
size_t total_num_connections () const
returns the total number of connections
Static Public Attributes
static const int blockSize = AT::blockSize
Protected Member Functions
std::ostream & outputToStream (std::ostream &os) const
Protected Attributes
const encapsulated_matrix_type & m_const
encapsulated_matrix_type & m_src
Friends
std::ostream & operator<< (std::ostream &os, ScalarMatrixAdapter< AT, ST > const &a)
operator overloading for streams
Member Typedef Documentation
encapsulated_matrix_type
template<class AT , class ST = CPUAlgebra> typedef AT::matrix_type ScalarMatrixAdapter< AT, ST >::encapsulated_matrix_type
value_type
template<class AT , class ST = CPUAlgebra> typedef ST::matrix_type::value_type ScalarMatrixAdapter< AT, ST >::value_type
Constructor & Destructor Documentation
ScalarMatrixAdapter()
template<class AT , class ST = CPUAlgebra> ScalarMatrixAdapter< AT, ST >::ScalarMatrixAdapter (encapsulated_matrix_type & mat) inline
Member Function Documentation
begin_row() [1/2]
template<class AT , class ST = CPUAlgebra> row_iterator ScalarMatrixAdapter< AT, ST >::begin_row (size_t r) inline
begin_row() [2/2]
template<class AT , class ST = CPUAlgebra> const_row_iterator ScalarMatrixAdapter< AT, ST >::begin_row (size_t r) const inline
end_row() [1/2]
template<class AT , class ST = CPUAlgebra> row_iterator ScalarMatrixAdapter< AT, ST >::end_row (size_t r) inline
end_row() [2/2]
template<class AT , class ST = CPUAlgebra> const_row_iterator ScalarMatrixAdapter< AT, ST >::end_row (size_t r) const inline
num_cols()
template<class AT , class ST = CPUAlgebra> size_t ScalarMatrixAdapter< AT, ST >::num_cols () const inline
returns the number of cols
num_rows()
template<class AT , class ST = CPUAlgebra> size_t ScalarMatrixAdapter< AT, ST >::num_rows () const inline
returns number of rows
operator()() [1/3]
template<class AT , class ST = CPUAlgebra> value_type& ScalarMatrixAdapter< AT, ST >::operator() (size_t r, size_t c) inline
References ug::BlockRef(), num_cols(), num_rows(), and UG_ASSERT.
operator()() [2/3]
ScalarMatrixAdapter< CPUAlgebra, CPUAlgebra >::value_type & ScalarMatrixAdapter< CPUAlgebra, CPUAlgebra >::operator() (size_t r, size_t c) inline
operator()() [3/3]
template<class AT , class ST = CPUAlgebra> const value_type& ScalarMatrixAdapter< AT, ST >::operator() (size_t r, size_t c) const inline
References ug::BlockRef(), num_cols(), num_rows(), and UG_ASSERT.
outputToStream()
template<class AT , class ST = CPUAlgebra> std::ostream& ScalarMatrixAdapter< AT, ST >::outputToStream (std::ostream & os) const inline protected
print()
template<class AT , class ST = CPUAlgebra> void ScalarMatrixAdapter< AT, ST >::print (const char * text) const inline
print (underlying) matrix
printrow()
template<class AT , class ST = CPUAlgebra> void ScalarMatrixAdapter< AT, ST >::printrow (size_t row) const inline
print (block) row of (underlying) matrix
resize_and_clear()
template<class AT , class ST = CPUAlgebra> void ScalarMatrixAdapter< AT, ST >::resize_and_clear (size_t newRows, size_t newCols) inline
resize_and_keep_values()
template<class AT , class ST = CPUAlgebra> bool ScalarMatrixAdapter< AT, ST >::resize_and_keep_values (size_t newRows, size_t newCols) inline
total_num_connections()
template<class AT , class ST = CPUAlgebra> size_t ScalarMatrixAdapter< AT, ST >::total_num_connections () const inline
returns the total number of connections
Friends And Related Function Documentation
operator<<
template<class AT , class ST = CPUAlgebra> std::ostream& operator<< (std::ostream & os, ScalarMatrixAdapter< AT, ST > const & a) friend
operator overloading for streams
Member Data Documentation
blockSize
template<class AT , class ST = CPUAlgebra> const int ScalarMatrixAdapter< AT, ST >::blockSize = AT::blockSize static
m_const
template<class AT , class ST = CPUAlgebra> const encapsulated_matrix_type& ScalarMatrixAdapter< AT, ST >::m_const protected
m_src
template<class AT , class ST = CPUAlgebra> encapsulated_matrix_type& ScalarMatrixAdapter< AT, ST >::m_src protected
The documentation for this class was generated from the following file:
ugbase/lib_algebra/adapter/scalar_matrix_adapter.hh