ug4: ug::IDataImport< dim > Class Template Reference
ug::IDataImport< dim > Class Template Reference abstract
Base class for data import.
#include <data_import.h>
Public Member Functions
virtual void add_jacobian (LocalMatrix &J, const number scale)=0
add jacobian entries introduced by this import
virtual void check_setup ()=0
checks if ready for evaluation
virtual void clear_ips ()=0
removes the positions
virtual void compute_lin_defect (LocalVector &u)=0
compute lin defect
const FunctionIndexMapping & conn_map () const
get function mapping of dependent data
virtual bool constant () const =0
returns if data is constant
virtual SmartPtr< ICplUserData< dim > > data ()=0
returns the connected user data
virtual bool data_given () const =0
returns if data is set
IDataImport (bool compLinDefect=true)
Constructor.
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions
DiscPart part () const
returns if import is located in mass part (for time dependent problems)
void set_comp_lin_defect (bool b)
sets if lin defect is to be computed
void set_expl_part ()
set to explicit part
void set_map (const FunctionIndexMapping &map)
set function group for linearization of defect
void set_mass_part ()
sets if import is located in mass part (for time dependent problems)
void set_none_part ()
set to no part
void set_part (DiscPart part)
sets part of import
void set_rhs_part ()
sets if import is located in rhs part
virtual void set_roid (ReferenceObjectID id)=0
sets the geometric object type
void set_stiff_part ()
sets if import is located in stiff part (default)
virtual void update_dof_sizes (const LocalIndices &ind)=0
resize arrays
bool zero_derivative () const
returns if data depends on unknown functions
virtual ~IDataImport ()
Protected Attributes
bool m_bCompLinDefect
indicates iff lin defect should be computed
FunctionIndexMapping m_map
Mapping for import fct.
DiscPart m_part
flag to indicate where import is located
SmartPtr< ICplUserData< dim > > m_spICplUserData
connected iexport
Detailed Description
template<int dim>
class ug::IDataImport< dim >
Base class for data import.
An IDataImport is the base class for importing data to ElemDiscs
Constructor & Destructor Documentation
template<int dim> ug::IDataImport< dim >::IDataImport (bool compLinDefect = true) inline
Constructor.
template<int dim> virtual ug::IDataImport< dim >::~IDataImport () inline virtual
Member Function Documentation
template<int dim> virtual void ug::IDataImport< dim >::add_jacobian (LocalMatrix & J, const number scale) pure virtual
add jacobian entries introduced by this import
Implemented in ug::DataImport< TData, dim >, ug::DataImport< ug::MathMatrix< dim, dim >, dim >, ug::DataImport< ug::MathVector< dim >, dim >, and ug::DataImport< number, dim >.
Referenced by ug::DataImport< number, dim >::lin_defect(), and ug::IDataImport< dim >::num_fct().
template<int dim> virtual void ug::IDataImport< dim >::check_setup () pure virtual
checks if ready for evaluation
Implemented in ug::DataImport< TData, dim >, ug::DataImport< ug::MathMatrix< dim, dim >, dim >, ug::DataImport< ug::MathVector< dim >, dim >, and ug::DataImport< number, dim >.
Referenced by ug::IDataImport< dim >::num_fct().
template<int dim> virtual void ug::IDataImport< dim >::clear_ips () pure virtual
removes the positions
Implemented in ug::DataImport< TData, dim >, ug::DataImport< ug::MathMatrix< dim, dim >, dim >, ug::DataImport< ug::MathVector< dim >, dim >, and ug::DataImport< number, dim >.
Referenced by ug::IDataImport< dim >::num_fct(), and ug::DataImport< number, dim >::position().
template<int dim> virtual void ug::IDataImport< dim >::compute_lin_defect (LocalVector & u) pure virtual
compute lin defect
Implemented in ug::DataImport< TData, dim >, ug::DataImport< ug::MathMatrix< dim, dim >, dim >, ug::DataImport< ug::MathVector< dim >, dim >, and ug::DataImport< number, dim >.
Referenced by ug::IDataImport< dim >::num_fct().
template<int dim> const FunctionIndexMapping& ug::IDataImport< dim >::conn_map () const inline
get function mapping of dependent data
References ug::IDataImport< dim >::m_spICplUserData.
template<int dim> virtual bool ug::IDataImport< dim >::constant () const pure virtual
returns if data is constant
This method, returns if the connected data is constant.
Implemented in ug::DataImport< TData, dim >, ug::DataImport< ug::MathMatrix< dim, dim >, dim >, ug::DataImport< ug::MathVector< dim >, dim >, and ug::DataImport< number, dim >.
Referenced by ug::IDataImport< dim >::part().
template<int dim> virtual SmartPtr<ICplUserData<dim> > ug::IDataImport< dim >::data () pure virtual
returns the connected user data
Implemented in ug::DataImport< TData, dim >, ug::DataImport< ug::MathMatrix< dim, dim >, dim >, ug::DataImport< ug::MathVector< dim >, dim >, and ug::DataImport< number, dim >.
Referenced by ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), and ug::IDataImport< dim >::zero_derivative().
template<int dim> virtual bool ug::IDataImport< dim >::data_given () const pure virtual
returns if data is set
Implemented in ug::DataImport< TData, dim >, ug::DataImport< ug::MathMatrix< dim, dim >, dim >, ug::DataImport< ug::MathVector< dim >, dim >, and ug::DataImport< number, dim >.
Referenced by ug::DataImport< number, dim >::constant(), ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), ug::IDataImport< dim >::part(), and ug::DataImport< number, dim >::position().
template<int dim> const FunctionIndexMapping& ug::IDataImport< dim >::map () const inline
get function mapping
References ug::IDataImport< dim >::m_map.
Referenced by ug::DataImport< number, dim >::compute_lin_defect(), and ug::IDataImport< dim >::set_map().
template<int dim> size_t ug::IDataImport< dim >::num_fct () const inline
number of functions
References ug::IDataImport< dim >::add_jacobian(), ug::IDataImport< dim >::check_setup(), ug::IDataImport< dim >::clear_ips(), ug::IDataImport< dim >::compute_lin_defect(), ug::IDataImport< dim >::m_map, ug::FunctionIndexMapping::num_fct(), ug::IDataImport< dim >::set_roid(), and ug::IDataImport< dim >::update_dof_sizes().
template<int dim> DiscPart ug::IDataImport< dim >::part () const inline
returns if import is located in mass part (for time dependent problems)
References ug::IDataImport< dim >::constant(), ug::IDataImport< dim >::data_given(), and ug::IDataImport< dim >::m_part.
Referenced by ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), and ug::IDataImport< dim >::set_part().
template<int dim> void ug::IDataImport< dim >::set_comp_lin_defect (bool b) inline
sets if lin defect is to be computed
References ug::IDataImport< dim >::m_bCompLinDefect.
template<int dim> void ug::IDataImport< dim >::set_expl_part () inline
set to explicit part
References ug::EXPL, and ug::IDataImport< dim >::m_part.
template<int dim> void ug::IDataImport< dim >::set_map (const FunctionIndexMapping & map) inline
set function group for linearization of defect
References ug::IDataImport< dim >::m_map, and ug::IDataImport< dim >::map().
template<int dim> void ug::IDataImport< dim >::set_mass_part () inline
sets if import is located in mass part (for time dependent problems)
References ug::IDataImport< dim >::m_part, and ug::MASS.
template<int dim> void ug::IDataImport< dim >::set_none_part () inline
set to no part
References ug::IDataImport< dim >::m_part, and ug::NONE.
template<int dim> void ug::IDataImport< dim >::set_part (DiscPart part) inline
sets part of import
References ug::IDataImport< dim >::m_part, and ug::IDataImport< dim >::part().
template<int dim> void ug::IDataImport< dim >::set_rhs_part () inline
sets if import is located in rhs part
References ug::IDataImport< dim >::m_part, and ug::RHS.
template<int dim> virtual void ug::IDataImport< dim >::set_roid (ReferenceObjectID id) pure virtual
sets the geometric object type
Implemented in ug::DataImport< TData, dim >, ug::DataImport< ug::MathMatrix< dim, dim >, dim >, ug::DataImport< ug::MathVector< dim >, dim >, and ug::DataImport< number, dim >.
Referenced by ug::IDataImport< dim >::num_fct().
template<int dim> void ug::IDataImport< dim >::set_stiff_part () inline
sets if import is located in stiff part (default)
References ug::IDataImport< dim >::m_part, and ug::STIFF.
template<int dim> virtual void ug::IDataImport< dim >::update_dof_sizes (const LocalIndices & ind) pure virtual
resize arrays
Implemented in ug::DataImport< TData, dim >, ug::DataImport< ug::MathMatrix< dim, dim >, dim >, ug::DataImport< ug::MathVector< dim >, dim >, and ug::DataImport< number, dim >.
Referenced by ug::DataImport< number, dim >::lin_defect(), and ug::IDataImport< dim >::num_fct().
template<int dim> bool ug::IDataImport< dim >::zero_derivative () const inline
returns if data depends on unknown functions
This method returns if the data depends on the unknown functions.
References ug::IDataImport< dim >::data(), ug::IDataImport< dim >::m_bCompLinDefect, and ug::IDataImport< dim >::m_spICplUserData.
Referenced by ug::DataEvaluator< TDomain >::extract_imports_and_userdata().
Member Data Documentation
template<int dim> bool ug::IDataImport< dim >::m_bCompLinDefect protected
indicates iff lin defect should be computed
Referenced by ug::IDataImport< dim >::set_comp_lin_defect(), and ug::IDataImport< dim >::zero_derivative().
template<int dim> FunctionIndexMapping ug::IDataImport< dim >::m_map protected
Mapping for import fct.
Referenced by ug::IDataImport< dim >::map(), ug::IDataImport< dim >::num_fct(), and ug::IDataImport< dim >::set_map().
template<int dim> DiscPart ug::IDataImport< dim >::m_part protected
flag to indicate where import is located
Referenced by ug::IDataImport< dim >::part(), ug::IDataImport< dim >::set_expl_part(), ug::IDataImport< dim >::set_mass_part(), ug::IDataImport< dim >::set_none_part(), ug::IDataImport< dim >::set_part(), ug::IDataImport< dim >::set_rhs_part(), and ug::IDataImport< dim >::set_stiff_part().
template<int dim> SmartPtr<ICplUserData<dim> > ug::IDataImport< dim >::m_spICplUserData protected
connected iexport
Referenced by ug::IDataImport< dim >::conn_map(), and ug::IDataImport< dim >::zero_derivative().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/user_data/data_import.h