ug4: ug::IndexView< index_type > Class Template Reference
ug::IndexView< index_type > Class Template Reference
#include <index_view.h>
Public Types
typedef std::vector< index_type > iterator
Public Member Functions
iterator begin ()
iterator end ()
IndexView (const std::vector< index_type > &indices)
IndexView (index_type *indices, size_t size)
bool is_in_view (index_type i)
Private Member Functions
void init ()
Private Attributes
std::vector< bool > is_in_locals
std::vector< index_type > local_to_global
Member Typedef Documentation
iterator
template<typename index_type > typedef std::vector<index_type> ug::IndexView< index_type >::iterator
Constructor & Destructor Documentation
IndexView() [1/2]
template<typename index_type > ug::IndexView< index_type >::IndexView (const std::vector< index_type > & indices) inline
References ug::IndexView< index_type >::init(), and ug::IndexView< index_type >::local_to_global.
IndexView() [2/2]
template<typename index_type > ug::IndexView< index_type >::IndexView (index_type * indices, size_t size) inline
References ug::IndexView< index_type >::init(), and ug::IndexView< index_type >::local_to_global.
Member Function Documentation
begin()
template<typename index_type > iterator ug::IndexView< index_type >::begin () inline
References ug::IndexView< index_type >::local_to_global.
end()
template<typename index_type > iterator ug::IndexView< index_type >::end () inline
References ug::IndexView< index_type >::local_to_global.
init()
template<typename index_type > void ug::IndexView< index_type >::init () inline private
References ug::IndexView< index_type >::is_in_locals, and ug::IndexView< index_type >::local_to_global.
Referenced by ug::IndexView< index_type >::IndexView().
is_in_view()
template<typename index_type > bool ug::IndexView< index_type >::is_in_view (index_type i) inline
References ug::IndexView< index_type >::is_in_locals.
Member Data Documentation
is_in_locals
template<typename index_type > std::vector<bool> ug::IndexView< index_type >::is_in_locals private
Referenced by ug::IndexView< index_type >::init(), and ug::IndexView< index_type >::is_in_view().
local_to_global
template<typename index_type > std::vector<index_type> ug::IndexView< index_type >::local_to_global private
Referenced by ug::IndexView< index_type >::begin(), ug::IndexView< index_type >::end(), ug::IndexView< index_type >::IndexView(), and ug::IndexView< index_type >::init().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/common/index_view.h