ug4: ug::BiCGStab< TVector > Class Template Reference
ug::BiCGStab< TVector > Class Template Reference
the BiCGStab method as a solver for linear operators
#include <bicgstab.h>
Public Types
typedef IPreconditionedLinearOperatorInverse< vector_type > base_type
Base type.
typedef TVector vector_type
Vector type.
Public Types inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
typedef ILinearOperatorInverse< TVector, TVector > base_type
Base class.
typedef TVector codomain_function_type
Range space.
typedef TVector domain_function_type
Domain space.
Public Types inherited from ug::ILinearOperatorInverse< X, Y >
typedef Y codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Types inherited from ug::ILinearIterator< X, X >
typedef X codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Types inherited from ug::VectorDebugWritingObject< TVector >
typedef TVector vector_type
type of vector
Public Member Functions
void add_postprocess_corr (SmartPtr< IPProcessVector< vector_type > > p)
adds a post-process for the iterates
virtual bool apply_return_defect (vector_type &x, vector_type &b)
BiCGStab ()
constructors
BiCGStab (SmartPtr< ILinearIterator< vector_type > > spPrecond, SmartPtr< IConvergenceCheck< vector_type > > spConvCheck)
BiCGStab (SmartPtr< ILinearIterator< vector_type, vector_type > > spPrecond)
virtual std::string config_string () const
returns information about configuration parameters
virtual const char * name () const
name of solver
void remove_postprocess_corr (SmartPtr< IPProcessVector< vector_type > > p)
removes a post-process for the iterates
void set_min_orthogonality (number minOrtho)
sets to restart if given orthogonality missed
void set_restart (int numRestarts)
sets to restart at given number of iteration steps
virtual bool supports_parallel () const
returns if parallel solving is supported
Public Member Functions inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
virtual bool apply (TVector &x, const TVector &b)
compute new correction c = B*d
std::string config_string_preconditioner_convergence_check () const
returns config information of convergence check and preconditioner
virtual bool init (SmartPtr< ILinearOperator< TVector, TVector > > J, const TVector &u)
initializes the solver for an operator
virtual bool init (SmartPtr< ILinearOperator< TVector, TVector > > L)
initializes the solver for an operator
IPreconditionedLinearOperatorInverse ()
Empty constructor.
IPreconditionedLinearOperatorInverse (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond)
constructor setting the preconditioner
IPreconditionedLinearOperatorInverse (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond, SmartPtr< IConvergenceCheck< TVector > > spConvCheck)
constructor setting the preconditioner
void set_compute_fresh_defect_when_finished (bool bRecompute)
for debug: computes norm again after whole calculation of apply
void set_preconditioner (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond)
sets the preconditioner
SmartPtr< ILinearIterator< TVector, TVector > > preconditioner ()
ConstSmartPtr< ILinearIterator< TVector, TVector > > preconditioner () const
Public Member Functions inherited from ug::ILinearOperatorInverse< X, Y >
virtual bool apply (Y &u, const X &f)=0
applies inverse operator, i.e. returns u = A^{-1} f
virtual bool apply_return_defect (Y &u, X &f)=0
applies inverse operator, i.e. returns u = A^{-1} f and returns defect d := f - A*u
virtual bool apply_update_defect (Y &u, X &f)
virtual SmartPtr< ILinearIterator< X, Y > > clone ()
clone
SmartPtr< IConvergenceCheck< X > > convergence_check ()
returns the convergence check
ConstSmartPtr< IConvergenceCheck< X > > convergence_check () const
returns the convergence check
number defect () const
returns the current defect
ILinearOperatorInverse ()
constructor setting convergence check to (100, 1e-12, 1e-12, true)
ILinearOperatorInverse (SmartPtr< IConvergenceCheck< X > > spConvCheck)
Default constructor.
virtual bool init (SmartPtr< ILinearOperator< Y, X > > J, const Y &u)
initializes for the inverse for a linearized operator at linearization point u
virtual bool init (SmartPtr< ILinearOperator< Y, X > > L)
initializes for the inverse for a linear operator
SmartPtr< ILinearOperator< Y, X > > linear_operator ()
returns the current Operator this Inverse Operator is initialized for
number reduction () const
returns the current relative reduction
void set_convergence_check (SmartPtr< IConvergenceCheck< X > > spConvCheck)
set the convergence check
virtual int standard_offset () const
returns the standard offset for output
int step () const
returns the current number of steps
virtual ~ILinearOperatorInverse ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< X, X >
virtual bool apply (X &c, const X &d)=0
compute new correction c = B*d
virtual bool apply_update_defect (X &c, X &d)=0
compute new correction c = B*d and update defect d := d - A*c
SmartPtr< IDamping< X, X > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< X, X > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< X, X > > J, const X &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< X, X > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< X, X > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TVector >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
void enter_precond_debug_section (int loopCnt, char phase)
debugger section for the preconditioner
SmartPtr< ILinearIterator< X, X > > preconditioner ()
ConstSmartPtr< ILinearIterator< X, X > > preconditioner () const
void prepare_conv_check ()
prepares the output of the convergence check
void write_debugXR (vector_type &x, vector_type &r, int loopCnt, char phase)
debugger output: solution and residual
Protected Member Functions inherited from ug::VectorDebugWritingObject< TVector >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
PProcessChain< vector_type > m_corr_post_process
postprocessor for the correction in the iterations
number m_minOrtho
minimal value in (0,1) accepted for Orthoginality before restart
int m_numRestarts
restarts at every numRestarts steps (numRestarts <= 0 --> never)
Protected Attributes inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
bool m_bRecompute
flag if fresh defect should be computed when finish for debug purpose
SmartPtr< ILinearIterator< TVector, TVector > > m_spPrecond
Iterator used in the iterative scheme to compute the correction and update the defect.
Protected Attributes inherited from ug::ILinearOperatorInverse< X, Y >
SmartPtr< IConvergenceCheck< X > > m_spConvCheck
smart pointer holding the convergence check
SmartPtr< ILinearOperator< Y, X > > m_spLinearOperator
Operator that is inverted by this Inverse Operator.
Protected Attributes inherited from ug::ILinearIterator< X, X >
SmartPtr< IDamping< X, X > > m_spDamping
the scaling
Protected Attributes inherited from ug::VectorDebugWritingObject< TVector >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Detailed Description
template<typename TVector>
class ug::BiCGStab< TVector >
the BiCGStab method as a solver for linear operators
This class implements the BiCGStab - method for the solution of linear operator problems like A*x = b, where the solution x = A^{-1} b is computed.
For detailed description of the algorithm, please refer to:
Barrett, Berry, Chan, Demmel, Donatom Dongarra, Eijkhout, Pozo, Romine, Van der Vorst, "Templates for the Solution of Linear Systems: Building Blocks for Iterative Methods", p.24, Fig, 2.10
Saad, "Iterative Methods For Sparse Linear Systems", p246, Alg. 7.7
Template Parameters
TVector vector type
Member Typedef Documentation
base_type
template<typename TVector > typedef IPreconditionedLinearOperatorInverse<vector_type> ug::BiCGStab< TVector >::base_type
Base type.
vector_type
template<typename TVector > typedef TVector ug::BiCGStab< TVector >::vector_type
Vector type.
Constructor & Destructor Documentation
BiCGStab() [1/3]
template<typename TVector > ug::BiCGStab< TVector >::BiCGStab () inline
constructors
BiCGStab() [2/3]
template<typename TVector > ug::BiCGStab< TVector >::BiCGStab (SmartPtr< ILinearIterator< vector_type, vector_type > > spPrecond) inline
BiCGStab() [3/3]
template<typename TVector > ug::BiCGStab< TVector >::BiCGStab (SmartPtr< ILinearIterator< vector_type > > spPrecond, SmartPtr< IConvergenceCheck< vector_type > > spConvCheck) inline
Member Function Documentation
add_postprocess_corr()
template<typename TVector > void ug::BiCGStab< TVector >::add_postprocess_corr (SmartPtr< IPProcessVector< vector_type > > p) inline
adds a post-process for the iterates
References ug::PProcessChain< TVector >::add(), ug::BiCGStab< TVector >::m_corr_post_process, and p.
apply_return_defect()
template<typename TVector > virtual bool ug::BiCGStab< TVector >::apply_return_defect (vector_type & x, vector_type & b) inline virtual
References alpha, ug::IPreconditionedLinearOperatorInverse< TVector >::apply(), ug::PProcessChain< TVector >::apply(), ug::ILinearOperatorInverse< X, Y >::convergence_check(), ug::BiCGStab< TVector >::enter_precond_debug_section(), ug::VectorDebugWritingObject< TVector >::leave_vector_debug_writer_section(), ug::ILinearOperatorInverse< X, Y >::linear_operator(), LS_PROFILE_BEGIN, ug::BiCGStab< TVector >::m_corr_post_process, ug::BiCGStab< TVector >::m_minOrtho, ug::BiCGStab< TVector >::m_numRestarts, omega, p, ug::BiCGStab< TVector >::preconditioner(), ug::BiCGStab< TVector >::prepare_conv_check(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::PST_UNIQUE, s, ug::ILinearOperatorInverse< X, Y >::step(), UG_LOG, UG_THROW, ug::VecProd(), ug::VecScaleAdd(), and ug::BiCGStab< TVector >::write_debugXR().
config_string()
template<typename TVector > virtual std::string ug::BiCGStab< TVector >::config_string () const inline virtual
returns information about configuration parameters
Reimplemented from ug::IPreconditionedLinearOperatorInverse< TVector >.
References ug::IPreconditionedLinearOperatorInverse< X >::config_string_preconditioner_convergence_check(), ug::BiCGStab< TVector >::m_minOrtho, and ug::BiCGStab< TVector >::m_numRestarts.
enter_precond_debug_section()
template<typename TVector > void ug::BiCGStab< TVector >::enter_precond_debug_section (int loopCnt, char phase) inline protected
debugger section for the preconditioner
References ug::VectorDebugWritingObject< TVector >::enter_vector_debug_writer_section(), sprintf(), and ug::VectorDebugWritingObject< TVector >::vector_debug_writer_valid().
Referenced by ug::BiCGStab< TVector >::apply_return_defect().
name()
template<typename TVector > virtual const char* ug::BiCGStab< TVector >::name () const inline virtual
name of solver
Implements ug::ILinearOperatorInverse< X, Y >.
Referenced by ug::BiCGStab< TVector >::prepare_conv_check().
preconditioner() [1/2]
template<typename TVector > SmartPtr<ILinearIterator<X, X> > ug::IPreconditionedLinearOperatorInverse< X >::preconditioner inline protected
returns the preconditioner
Referenced by ug::BiCGStab< TVector >::apply_return_defect(), ug::BiCGStab< TVector >::prepare_conv_check(), and ug::BiCGStab< TVector >::supports_parallel().
preconditioner() [2/2]
template<typename TVector > ConstSmartPtr<ILinearIterator<X, X> > ug::IPreconditionedLinearOperatorInverse< X >::preconditioner inline protected
prepare_conv_check()
template<typename TVector > void ug::BiCGStab< TVector >::prepare_conv_check () inline protected
prepares the output of the convergence check
References ug::ILinearOperatorInverse< X, Y >::convergence_check(), ug::BiCGStab< TVector >::name(), ug::BiCGStab< TVector >::preconditioner(), and s.
Referenced by ug::BiCGStab< TVector >::apply_return_defect().
remove_postprocess_corr()
template<typename TVector > void ug::BiCGStab< TVector >::remove_postprocess_corr (SmartPtr< IPProcessVector< vector_type > > p) inline
removes a post-process for the iterates
References ug::BiCGStab< TVector >::m_corr_post_process, p, and ug::PProcessChain< TVector >::remove().
set_min_orthogonality()
template<typename TVector > void ug::BiCGStab< TVector >::set_min_orthogonality (number minOrtho) inline
sets to restart if given orthogonality missed
References ug::BiCGStab< TVector >::m_minOrtho.
set_restart()
template<typename TVector > void ug::BiCGStab< TVector >::set_restart (int numRestarts) inline
sets to restart at given number of iteration steps
References ug::BiCGStab< TVector >::m_numRestarts.
supports_parallel()
template<typename TVector > virtual bool ug::BiCGStab< TVector >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearOperatorInverse< X, Y >.
References ug::BiCGStab< TVector >::preconditioner().
write_debugXR()
template<typename TVector > void ug::BiCGStab< TVector >::write_debugXR (vector_type & x, vector_type & r, int loopCnt, char phase) inline protected
debugger output: solution and residual
References sprintf(), ug::VectorDebugWritingObject< TVector >::vector_debug_writer_valid(), and ug::VectorDebugWritingObject< TVector >::write_debug().
Referenced by ug::BiCGStab< TVector >::apply_return_defect().
Member Data Documentation
m_corr_post_process
template<typename TVector > PProcessChain<vector_type> ug::BiCGStab< TVector >::m_corr_post_process protected
postprocessor for the correction in the iterations
These postprocess operations are applied to the preconditioned defect before the orthogonalization. The goal is to prevent the useless kernel parts to prevail in the (floating point) arithmetics.
Referenced by ug::BiCGStab< TVector >::add_postprocess_corr(), ug::BiCGStab< TVector >::apply_return_defect(), and ug::BiCGStab< TVector >::remove_postprocess_corr().
m_minOrtho
template<typename TVector > number ug::BiCGStab< TVector >::m_minOrtho protected
minimal value in (0,1) accepted for Orthoginality before restart
Referenced by ug::BiCGStab< TVector >::apply_return_defect(), ug::BiCGStab< TVector >::config_string(), and ug::BiCGStab< TVector >::set_min_orthogonality().
m_numRestarts
template<typename TVector > int ug::BiCGStab< TVector >::m_numRestarts protected
restarts at every numRestarts steps (numRestarts <= 0 --> never)
Referenced by ug::BiCGStab< TVector >::apply_return_defect(), ug::BiCGStab< TVector >::config_string(), and ug::BiCGStab< TVector >::set_restart().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/linear_solver/bicgstab.h