ug4: ug::DoFCount Class Reference
ug::DoFCount Class Reference
#include <dof_count.h>
Classes
struct Cnt
Public Member Functions
void add (int fct, int si, SurfaceView::SurfaceState ss, byte is, uint64 numDoF)
void collect_values (std::vector< uint64 > &vNum) const
DoFCount ()
DoFCount (const GridLevel &gl, ConstSmartPtr< DoFDistributionInfo > spDDInfo)
const GridLevel & grid_level () const
uint64 num (int fct, int si, SurfaceView::SurfaceState ss, byte is) const
uint64 num_contains (int fct, int si, SurfaceView::SurfaceState ss, byte is) const
void set_values (const std::vector< uint64 > &vNum)
void sum_values_over_procs (int proc=-1)
sums values over all procs (reduced to 'proc', allreduce for -1)
Public Member Functions inherited from ug::DoFDistributionInfoProvider
SubsetGroup all_subsets_grp_except_for (const char *names) const
returns subset group of all the subsets except for (by name)
int dim (size_t fct) const
returns the dimension in which solution lives
int dim_subset (int si) const
returns dimension of subset
ConstSmartPtr< DoFDistributionInfo > dof_distribution_info () const
returns underlying info
DoFDistributionInfoProvider ()
constructor
DoFDistributionInfoProvider (ConstSmartPtr< DoFDistributionInfo > spDDI)
constructor
FunctionGroup fct_grp_by_name (const char *names) const
returns a function group to a string of functions
size_t fct_id_by_name (const char *name) const
returns fct id by name
ConstSmartPtr< FunctionPattern > function_pattern () const
returns the function pattern
bool is_def_everywhere (size_t fct) const
returns true if the discrete function nr_fct is defined everywhere
bool is_def_in_subset (size_t fct, int si) const
returns if a function is defined on a subset
size_t max_dofs (const GridBaseObjectId gbo) const
returns the maximum number of dofs on a grid base object type
size_t max_dofs (const GridBaseObjectId gbo, const int si) const
returns the maximum number of dofs on a grid base object on a subset
size_t max_dofs (const int dim) const
returns the maximum number of dofs on grid objects in a dimension
size_t max_dofs (const int dim, const int si) const
returns the maximum number of dofs in a dimension on a subset
size_t max_dofs (const ReferenceObjectID roid) const
returns the maximum number of dofs on reference object type
size_t max_fct_dofs (const size_t fct, const GridBaseObjectId gbo) const
returns the maximal number of dofs on a base object type for a function component
size_t max_fct_dofs (const size_t fct, const GridBaseObjectId gbo, const int si) const
returns the maximum number of dofs on a grid base object on a subset for a function component
size_t max_fct_dofs (const size_t fct, const int dim, const int si) const
returns the maximum number of dofs in a dimension on a subset for a function component
size_t max_fct_dofs (const size_t fct, const ReferenceObjectID roid) const
returns the number of dofs on a reference object for a function component
size_t max_fct_dofs (const size_t fct, int dim) const
returns the maximal number of dofs on a dimension for a function component
std::string name (size_t fct) const
returns the name of the discrete function nr_fct
std::vector< std::string > names () const
returns the names of the discrete functions
size_t num_dofs (const ReferenceObjectID roid, const int si) const
returns the number of dofs on a Reference Object on a subset
size_t num_fct () const
number of discrete functions on subset si
size_t num_fct (int si) const
number of discrete functions on subset si
size_t num_fct_dofs (const size_t fct, const ReferenceObjectID roid, const int si) const
returns the number of dofs on a Reference Object on a subset for a function component
int num_subsets () const
returns number of subsets
size_t offset (const ReferenceObjectID roid, const int si, const size_t fct) const
returns the offset for reference element, subset and function
void print_local_dof_statistic () const
prints statistic on local dof distribution
void print_local_dof_statistic (int verboseLev) const
prints informations
void set_dof_distribution_info (ConstSmartPtr< DoFDistributionInfo > spDDI)
sets the dd info
SubsetGroup subset_grp_by_name (const char *names) const
returns subset group by name
ConstSmartPtr< ISubsetHandler > subset_handler () const
returns the subset handler
int subset_id_by_name (const char *name) const
returns the subset id
std::string subset_name (int si) const
returns subset name
const LFEID & local_finite_element_id (size_t fct) const
const LFEID & lfeid (size_t fct) const
Static Public Attributes
static const byte ALL_ES = ES_MAX + 1
static const int ALL_FCT = -1
static const byte ALL_SS = SS_MAX + 1
static const int ALL_SUBSET = -1
static const byte ES_MAX = (ES_V_MASTER | ES_H_MASTER | ES_H_SLAVE | ES_V_SLAVE)
static const byte SS_MAX = SurfaceView::ALL
static const byte UNIQUE_ES = ES_MAX + 2
static const byte UNIQUE_SS = SS_MAX + 2
Protected Attributes
GridLevel m_gridLevel
std::vector< std::vector< Cnt > > vvCmpSubset
Protected Attributes inherited from ug::DoFDistributionInfoProvider
ConstSmartPtr< DoFDistributionInfo > m_spDDI
Function Pattern.
Constructor & Destructor Documentation
DoFCount() [1/2]
ug::DoFCount::DoFCount () inline
DoFCount() [2/2]
ug::DoFCount::DoFCount (const GridLevel & gl, ConstSmartPtr< DoFDistributionInfo > spDDInfo)
References ug::DoFDistributionInfoProvider::num_fct(), ug::DoFDistributionInfoProvider::num_subsets(), resize(), and vvCmpSubset.
Member Function Documentation
add()
void ug::DoFCount::add (int fct, int si, SurfaceView::SurfaceState ss, byte is, uint64 numDoF)
References UG_THROW, and vvCmpSubset.
Referenced by ug::DoFDistribution::sum_dof_count().
collect_values()
void ug::DoFCount::collect_values (std::vector< uint64 > & vNum) const
References PROFILE_FUNC, and vvCmpSubset.
Referenced by sum_values_over_procs().
grid_level()
const GridLevel& ug::DoFCount::grid_level () const inline
References m_gridLevel.
Referenced by ug::PrintDoFCount().
num()
uint64 ug::DoFCount::num (int fct, int si, SurfaceView::SurfaceState ss, byte is) const
References ALL_FCT, ALL_SUBSET, and vvCmpSubset.
Referenced by ug::DoFCount::Cnt::add(), ug::DoFCount::Cnt::PCnt::num(), ug::DoFCount::Cnt::num(), ug::DoFCount::Cnt::PCnt::num_contains(), ug::GridFunction< TDomain, TAlgebra >::num_dofs(), and ug::PrintDoFCount().
num_contains()
uint64 ug::DoFCount::num_contains (int fct, int si, SurfaceView::SurfaceState ss, byte is) const
References ALL_FCT, ALL_SUBSET, and vvCmpSubset.
Referenced by ug::DoFCount::Cnt::PCnt::num(), ug::DoFCount::Cnt::PCnt::num_contains(), ug::DoFCount::Cnt::num_contains(), and ug::PrintDoFCount().
set_values()
void ug::DoFCount::set_values (const std::vector< uint64 > & vNum)
References PROFILE_FUNC, and vvCmpSubset.
Referenced by sum_values_over_procs().
sum_values_over_procs()
void ug::DoFCount::sum_values_over_procs (int proc = -1)
sums values over all procs (reduced to 'proc', allreduce for -1)
References pcl::ProcessCommunicator::allreduce(), collect_values(), PCL_DT_UNSIGNED_LONG_LONG, PCL_RO_SUM, PROFILE_FUNC, pcl::ProcessCommunicator::reduce(), and set_values().
Referenced by ug::GridFunction< TDomain, TAlgebra >::num_dofs().
Member Data Documentation
ALL_ES
const byte ug::DoFCount::ALL_ES = ES_MAX + 1 static
Referenced by ug::DoFCount::Cnt::PCnt::num(), and ug::DoFCount::Cnt::PCnt::num_contains().
ALL_FCT
const int ug::DoFCount::ALL_FCT = -1 static
Referenced by num(), num_contains(), and ug::GridFunction< TDomain, TAlgebra >::num_dofs().
ALL_SS
const byte ug::DoFCount::ALL_SS = SS_MAX + 1 static
Referenced by ug::DoFCount::Cnt::num(), and ug::DoFCount::Cnt::num_contains().
ALL_SUBSET
const int ug::DoFCount::ALL_SUBSET = -1 static
Referenced by num(), num_contains(), and ug::GridFunction< TDomain, TAlgebra >::num_dofs().
ES_MAX
const byte ug::DoFCount::ES_MAX = (ES_V_MASTER | ES_H_MASTER | ES_H_SLAVE | ES_V_SLAVE) static
Referenced by ug::DoFCount::Cnt::add(), ug::DoFCount::Cnt::PCnt::collect_values(), ug::DoFCount::Cnt::PCnt::num(), ug::DoFCount::Cnt::PCnt::num_contains(), ug::DoFCount::Cnt::PCnt::PCnt(), and ug::DoFCount::Cnt::PCnt::set_values().
m_gridLevel
GridLevel ug::DoFCount::m_gridLevel protected
Referenced by grid_level().
SS_MAX
const byte ug::DoFCount::SS_MAX = SurfaceView::ALL static
Referenced by ug::DoFCount::Cnt::add(), ug::DoFCount::Cnt::Cnt(), ug::DoFCount::Cnt::num(), and ug::DoFCount::Cnt::num_contains().
UNIQUE_ES
const byte ug::DoFCount::UNIQUE_ES = ES_MAX + 2 static
Referenced by ug::DoFCount::Cnt::PCnt::num(), ug::DoFCount::Cnt::PCnt::num_contains(), and ug::GridFunction< TDomain, TAlgebra >::num_dofs().
UNIQUE_SS
const byte ug::DoFCount::UNIQUE_SS = SS_MAX + 2 static
Referenced by ug::DoFCount::Cnt::num(), ug::DoFCount::Cnt::num_contains(), and ug::GridFunction< TDomain, TAlgebra >::num_dofs().
vvCmpSubset
std::vector<std::vector<Cnt> > ug::DoFCount::vvCmpSubset protected
Referenced by add(), collect_values(), DoFCount(), num(), num_contains(), and set_values().
The documentation for this class was generated from the following files:
ugbase/lib_disc/dof_manager/dof_count.h
ugbase/lib_disc/dof_manager/dof_count.cpp