ug4: ug::FractalProjector Class Reference
ug::FractalProjector Class Reference
lib_grid » algorithms » refinement
calculates new positions by offsetting new vertices to along its parents normal.
#include <fractal_projector.h>
Public Member Functions
FractalProjector ()
FractalProjector (Grid &grid, number scaleFac, APosition &aPos=aPosition)
make sure that aPos is attached to the vertices of the grid.
number get_scale_fac ()
virtual void new_vertex (Vertex *vrt, Edge *parent)
called when a new vertex was created from an old edge.
virtual void new_vertex (Vertex *vrt, Face *parent)
called when a new vertex was created from an old face.
void set_scale_fac (number scaleFac)
virtual ~FractalProjector ()
Public Member Functions inherited from ug::RefinementCallbackLinear< APosition >
virtual int current_pos (number *coordsOut, Vertex *vrt, int maxCoords)
Gives access to the position of the current vertex.
virtual void new_vertex (Vertex *vrt, Vertex *parent)
called when a new vertex was created from an old vertex.
virtual void new_vertex (Vertex *vrt, Volume *parent)
called when a new vertex was created from an old volume.
RefinementCallbackLinear ()
RefinementCallbackLinear (Grid &grid, APosition &aPos)
make sure that aPos is attached to the vertices of the grid.
virtual ~RefinementCallbackLinear ()
Public Member Functions inherited from ug::IRefinementCallback
virtual void flat_grid_vertex_encountered (Vertex *vrt)
callback for vertices in flat grids.
virtual ~IRefinementCallback ()
Protected Attributes
number m_scaleFac
Protected Attributes inherited from ug::RefinementCallbackLinear< APosition >
Grid::VertexAttachmentAccessor< APosition > m_aaPos
Grid * m_pGrid
Additional Inherited Members
Protected Types inherited from ug::RefinementCallbackLinear< APosition >
typedef APosition::ValueType pos_type
Protected Member Functions inherited from ug::IRefinementCallback
template<class TAttachmentAccessor >
int current_pos_helper (number *coordsOut, Vertex *vrt, int maxCoords, TAttachmentAccessor &aaPos)
A helper implementation of current_pos available for derived classes.
Detailed Description
calculates new positions by offsetting new vertices to along its parents normal.
Make sure to initialise the callback correctly. Use the same grid on which the refinement-operations will be performed. Make sure that aPos (given in the constructor) is attached to the vertices of the grid.
An uninitialized refinement-callback may not be used during refinement.
Constructor & Destructor Documentation
ug::FractalProjector::FractalProjector ()
ug::FractalProjector::FractalProjector (Grid & grid, number scaleFac, APosition & aPos = aPosition)
make sure that aPos is attached to the vertices of the grid.
References ~FractalProjector().
ug::FractalProjector::~FractalProjector () virtual
References new_vertex().
Referenced by FractalProjector().
Member Function Documentation
number ug::FractalProjector::get_scale_fac () inline
References m_scaleFac.
Referenced by ug::CreateFractal_NormalScale().
void ug::FractalProjector::new_vertex (Vertex * vrt, Edge * parent) virtual
called when a new vertex was created from an old edge.
Reimplemented from ug::RefinementCallbackLinear< APosition >.
References ug::CalculateNormal(), ug::RefinementCallbackLinear< APosition >::m_aaPos, ug::RefinementCallbackLinear< APosition >::m_pGrid, m_scaleFac, ug::RefinementCallbackLinear< TAPosition >::new_vertex(), ug::VecAdd(), ug::VecDistance(), ug::VecScale(), and ug::EdgeVertices::vertex().
Referenced by ~FractalProjector().
void ug::FractalProjector::new_vertex (Vertex * vrt, Face * parent) virtual
called when a new vertex was created from an old face.
Reimplemented from ug::RefinementCallbackLinear< APosition >.
References ug::CalculateNormal(), ug::RefinementCallbackLinear< APosition >::m_aaPos, m_scaleFac, ug::RefinementCallbackLinear< TAPosition >::new_vertex(), ug::FaceVertices::num_vertices(), ug::VecAdd(), ug::VecDistance(), ug::VecScale(), and ug::FaceVertices::vertex().
void ug::FractalProjector::set_scale_fac (number scaleFac) inline
References m_scaleFac.
Referenced by ug::CreateFractal_NormalScale().
Member Data Documentation
number ug::FractalProjector::m_scaleFac protected
Referenced by get_scale_fac(), new_vertex(), and set_scale_fac().
The documentation for this class was generated from the following files:
ugbase/lib_grid/algorithms/refinement/refinement_projectors/fractal_projector.h
ugbase/lib_grid/algorithms/refinement/refinement_projectors/fractal_projector.cpp