ug4: ug::ParallelColoring Class Reference
ug::ParallelColoring Class Reference
#include <parallel_coloring.h>
Public Member Functions
int color (pcl::InterfaceCommunicator< IndexLayout > &com)
ParallelColoring ()
void save_colors_in (std::map< int, int > *p)
void save_processes_with_higher_color_in (std::vector< int > *p)
void save_processes_with_lower_color_in (std::vector< int > *p)
void set_connections (std::set< int > &pids_)
Private Attributes
std::map< int, int > * p_colors
std::vector< int > * p_processesWithHigherColor
std::vector< int > * p_processesWithLowerColor
std::set< int > pids
Constructor & Destructor Documentation
ParallelColoring()
ug::ParallelColoring::ParallelColoring () inline
Member Function Documentation
color()
int ug::ParallelColoring::color (pcl::InterfaceCommunicator< IndexLayout > & com)
References pcl::InterfaceCommunicator< TLayout >::communicate(), ug::DBG_COLORING, p_colors, p_processesWithHigherColor, p_processesWithLowerColor, pids, pcl::ProcRank(), PROFILE_FUNC_GROUP, pcl::InterfaceCommunicator< TLayout >::receive_raw(), pcl::InterfaceCommunicator< TLayout >::send_raw(), and UG_DLOG.
Referenced by ug::ColorProcessorGraph().
save_colors_in()
void ug::ParallelColoring::save_colors_in (std::map< int, int > * p) inline
References p, and p_colors.
save_processes_with_higher_color_in()
void ug::ParallelColoring::save_processes_with_higher_color_in (std::vector< int > * p) inline
References p, and p_processesWithHigherColor.
Referenced by ug::ColorProcessorGraph().
save_processes_with_lower_color_in()
void ug::ParallelColoring::save_processes_with_lower_color_in (std::vector< int > * p) inline
References p, and p_processesWithLowerColor.
Referenced by ug::ColorProcessorGraph().
set_connections()
void ug::ParallelColoring::set_connections (std::set< int > & pids_) inline
References pids.
Referenced by ug::ColorProcessorGraph().
Member Data Documentation
p_colors
std::map<int, int>* ug::ParallelColoring::p_colors private
Referenced by color(), and save_colors_in().
p_processesWithHigherColor
std::vector<int>* ug::ParallelColoring::p_processesWithHigherColor private
Referenced by color(), and save_processes_with_higher_color_in().
p_processesWithLowerColor
std::vector<int>* ug::ParallelColoring::p_processesWithLowerColor private
Referenced by color(), and save_processes_with_lower_color_in().
pids
std::set<int> ug::ParallelColoring::pids private
Referenced by color(), and set_connections().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/parallelization/parallel_coloring.h
ugbase/lib_algebra/parallelization/parallel_coloring.cpp