ug4: ug::ComPol_BroadcastRefineMarks< TLayout > Class Template Reference
ug::ComPol_BroadcastRefineMarks< TLayout > Class Template Reference
Public Types
typedef Layout::Element Element
typedef Layout::Type GeomObj
typedef Layout::Interface Interface
typedef Interface::const_iterator InterfaceIter
typedef TLayout Layout
Public Types inherited from pcl::ICommunicationPolicy< TLayout >
typedef Layout::Interface Interface
typedef TLayout Layout
Public Member Functions
virtual bool collect (ug::BinaryBuffer &buff, const Interface &interface)
writes writes the selection states of the interface entries
ComPol_BroadcastRefineMarks (IRefiner &ref, byte consideredMarks)
virtual bool extract (ug::BinaryBuffer &buff, const Interface &interface)
reads marks from the given stream
virtual int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
virtual ~ComPol_BroadcastRefineMarks ()
Public Member Functions inherited from pcl::ICommunicationPolicy< TLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual ~ICommunicationPolicy ()
Public Attributes
byte m_consideredMarks
IRefiner & m_ref
Member Typedef Documentation
Element
template<class TLayout> typedef Layout::Element ug::ComPol_BroadcastRefineMarks< TLayout >::Element
GeomObj
template<class TLayout> typedef Layout::Type ug::ComPol_BroadcastRefineMarks< TLayout >::GeomObj
Interface
template<class TLayout> typedef Layout::Interface ug::ComPol_BroadcastRefineMarks< TLayout >::Interface
InterfaceIter
template<class TLayout> typedef Interface::const_iterator ug::ComPol_BroadcastRefineMarks< TLayout >::InterfaceIter
Layout
template<class TLayout> typedef TLayout ug::ComPol_BroadcastRefineMarks< TLayout >::Layout
Constructor & Destructor Documentation
ComPol_BroadcastRefineMarks()
template<class TLayout> ug::ComPol_BroadcastRefineMarks< TLayout >::ComPol_BroadcastRefineMarks (IRefiner & ref, byte consideredMarks) inline
~ComPol_BroadcastRefineMarks()
template<class TLayout> virtual ug::ComPol_BroadcastRefineMarks< TLayout >::~ComPol_BroadcastRefineMarks () inline virtual
Member Function Documentation
collect()
template<class TLayout> virtual bool ug::ComPol_BroadcastRefineMarks< TLayout >::collect (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
writes writes the selection states of the interface entries
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::IRefiner::get_mark(), ug::ComPol_BroadcastRefineMarks< TLayout >::m_ref, and ug::BinaryBuffer::write().
extract()
template<class TLayout> virtual bool ug::ComPol_BroadcastRefineMarks< TLayout >::extract (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
reads marks from the given stream
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::IRefiner::get_mark(), ug::ComPol_BroadcastRefineMarks< TLayout >::m_consideredMarks, ug::ComPol_BroadcastRefineMarks< TLayout >::m_ref, ug::IRefiner::mark(), ug::BinaryBuffer::read(), ug::RM_ANISOTROPIC, ug::RM_CLOSURE, ug::RM_COARSEN, and ug::RM_REFINE.
get_required_buffer_size()
template<class TLayout> virtual int ug::ComPol_BroadcastRefineMarks< TLayout >::get_required_buffer_size (const Interface & interface) inline virtual
returns the size of the buffer in bytes, that will be required for interface-communication.
Determines the size of the buffer on which the extract and receive methods for the given interface will operate. If the buffer-size can't be calculated on both sides (sender and receiver) this method should return -1. This will lead to an additional communication step in which buffer-sizes will be exchanged. If the buffer-size can be calculated on both sides, it makes sense to do so, since this leads to less communication and overall improved performance. The buffer-size has to exactly match the size of required memory. Make sure that you completely fill the buffer during collect(...) and that you read all data during extract(...). The default implementation returns -1.
Reimplemented from pcl::ICommunicationPolicy< TLayout >.
Member Data Documentation
m_consideredMarks
template<class TLayout> byte ug::ComPol_BroadcastRefineMarks< TLayout >::m_consideredMarks
Referenced by ug::ComPol_BroadcastRefineMarks< TLayout >::extract().
m_ref
template<class TLayout> IRefiner& ug::ComPol_BroadcastRefineMarks< TLayout >::m_ref
Referenced by ug::ComPol_BroadcastRefineMarks< TLayout >::collect(), and ug::ComPol_BroadcastRefineMarks< TLayout >::extract().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/parallel_refinement/parallel_hnode_adjuster.cpp