ug4: ug::LuaFunction< TData, TDataIn > Class Template Reference
ug::LuaFunction< TData, TDataIn > Class Template Reference
#include <lua_user_data.h>
Public Member Functions
LuaFunction ()
constructor
virtual void operator() (TData &out, int numArgs,...)
evaluates the data
void set_lua_callback (const char *luaCallback, size_t numArgs)
sets the Lua function used to compute the data
virtual ~LuaFunction ()
Public Member Functions inherited from ug::IFunction< TData, TDataIn >
virtual ~IFunction ()
virtual destructor
Protected Attributes
std::string m_cbValueName
callback name as string
int m_cbValueRef
reference to lua function
lua_State * m_L
lua state
size_t m_numArgs
number of arguments to use
Detailed Description
template<typename TData, typename TDataIn>
class ug::LuaFunction< TData, TDataIn >
Template Parameters
TData Return value type
TDataIn Input daten type
Constructor & Destructor Documentation
LuaFunction()
template<typename TData , typename TDataIn > ug::LuaFunction< TData, TDataIn >::LuaFunction
constructor
References ug::script::GetDefaultLuaState(), ug::LuaFunction< TData, TDataIn >::m_cbValueRef, and ug::LuaFunction< TData, TDataIn >::m_L.
~LuaFunction()
template<typename TData , typename TDataIn > virtual ug::LuaFunction< TData, TDataIn >::~LuaFunction () inline virtual
Member Function Documentation
operator()()
template<typename TData , typename TDataIn > void ug::LuaFunction< TData, TDataIn >::operator() (TData & out, int numArgs, ...) virtual
evaluates the data
Implements ug::IFunction< TData, TDataIn >.
References ug::IsFiniteAndNotTooBig(), PROFILE_CALLBACK_BEGIN, PROFILE_CALLBACK_END, read(), UG_ASSERT, UG_CATCH_THROW, UG_COND_THROW, and UG_THROW.
set_lua_callback()
template<typename TData , typename TDataIn > void ug::LuaFunction< TData, TDataIn >::set_lua_callback (const char * luaCallback, size_t numArgs)
sets the Lua function used to compute the data
This function sets the lua callback. The name of the function is passed as a string. Make sure, that the function name is defined when executing the script.
References UG_THROW.
Referenced by ug::MarkForCoarsen_ElementsByLuaCallback(), and ug::MarkForRefinement_ElementsByLuaCallback().
Member Data Documentation
m_cbValueName
template<typename TData , typename TDataIn > std::string ug::LuaFunction< TData, TDataIn >::m_cbValueName protected
callback name as string
m_cbValueRef
template<typename TData , typename TDataIn > int ug::LuaFunction< TData, TDataIn >::m_cbValueRef protected
reference to lua function
Referenced by ug::LuaFunction< TData, TDataIn >::LuaFunction().
m_L
template<typename TData , typename TDataIn > lua_State* ug::LuaFunction< TData, TDataIn >::m_L protected
lua state
Referenced by ug::LuaFunction< TData, TDataIn >::LuaFunction().
m_numArgs
template<typename TData , typename TDataIn > size_t ug::LuaFunction< TData, TDataIn >::m_numArgs protected
number of arguments to use
The documentation for this class was generated from the following files:
ugbase/bindings/lua/lua_user_data.h
ugbase/bindings/lua/lua_user_data_impl.h