ug4: ug::MathTensorX< TEntry, N > Class Template Reference
ug::MathTensorX< TEntry, N > Class Template Reference
ugbase » Math » Tensor
#include <math_tensor.h>
Public Types
typedef size_t size_type
typedef TEntry value_type
Public Member Functions
MathTensorX ()
MathTensorX (const MathTensorX &v)
MathTensorX & operator= (const MathTensorX &v)
value_type & operator[] (size_t i)
const value_type & operator[] (size_t i) const
size_t rank () const
size_t size () const
Static Public Attributes
static const size_t Dimension = N
static const size_t Rank = TEntry::Rank+1
Protected Member Functions
void assign (const MathTensorX< TEntry, N > &v)
Protected Attributes
TEntry m_data [N]
Member Typedef Documentation
size_type
template<typename TEntry , size_t N> typedef size_t ug::MathTensorX< TEntry, N >::size_type
value_type
template<typename TEntry , size_t N> typedef TEntry ug::MathTensorX< TEntry, N >::value_type
Constructor & Destructor Documentation
MathTensorX() [1/2]
template<typename TEntry , size_t N> ug::MathTensorX< TEntry, N >::MathTensorX () inline
MathTensorX() [2/2]
template<typename TEntry , size_t N> ug::MathTensorX< TEntry, N >::MathTensorX (const MathTensorX< TEntry, N > & v) inline
References ug::MathTensorX< TEntry, N >::assign().
Member Function Documentation
assign()
template<typename TEntry , size_t N> void ug::MathTensorX< TEntry, N >::assign (const MathTensorX< TEntry, N > & v) inline protected
References ug::MathTensorX< TEntry, N >::m_data.
Referenced by ug::MathTensorX< TEntry, N >::MathTensorX(), and ug::MathTensorX< TEntry, N >::operator=().
operator=()
template<typename TEntry , size_t N> MathTensorX& ug::MathTensorX< TEntry, N >::operator= (const MathTensorX< TEntry, N > & v) inline
References ug::MathTensorX< TEntry, N >::assign().
operator[]() [1/2]
template<typename TEntry , size_t N> value_type& ug::MathTensorX< TEntry, N >::operator[] (size_t i) inline
References ug::MathTensorX< TEntry, N >::m_data, ug::MathTensorX< TEntry, N >::size(), and UG_ASSERT.
operator[]() [2/2]
template<typename TEntry , size_t N> const value_type& ug::MathTensorX< TEntry, N >::operator[] (size_t i) const inline
References ug::MathTensorX< TEntry, N >::m_data, ug::MathTensorX< TEntry, N >::size(), and UG_ASSERT.
rank()
template<typename TEntry , size_t N> size_t ug::MathTensorX< TEntry, N >::rank () const inline
References ug::MathTensorX< TEntry, N >::Rank.
size()
template<typename TEntry , size_t N> size_t ug::MathTensorX< TEntry, N >::size () const inline
Referenced by ug::IsFiniteAndNotTooBig(), and ug::MathTensorX< TEntry, N >::operator[]().
Member Data Documentation
Dimension
template<typename TEntry , size_t N> const size_t ug::MathTensorX< TEntry, N >::Dimension = N static
m_data
template<typename TEntry , size_t N> TEntry ug::MathTensorX< TEntry, N >::m_data[N] protected
Referenced by ug::MathTensorX< TEntry, N >::assign(), and ug::MathTensorX< TEntry, N >::operator[]().
Rank
template<typename TEntry , size_t N> const size_t ug::MathTensorX< TEntry, N >::Rank = TEntry::Rank+1 static
Referenced by ug::MathTensorX< TEntry, N >::rank().
The documentation for this class was generated from the following file:
ugbase/common/math/math_vector_matrix/math_tensor.h