ug4: ConstSmartPtr< void > Class Reference
ConstSmartPtr< void > Class Reference
#include <smart_pointer.h>
Public Member Functions
template<class T , template< class TPtr > class TFreePolicy>
ConstSmartPtr< T, TFreePolicy > cast_reinterpret () const
Returns a SmartPtr with the specified type and shared reference counting.
ConstSmartPtr ()
template<class T , template< class TPtr > class TFreePolicy>
ConstSmartPtr (const ConstSmartPtr< T, TFreePolicy > &sp)
ConstSmartPtr (const ConstSmartPtr< void > &sp)
template<class T , template< class TPtr > class TFreePolicy>
ConstSmartPtr (const SmartPtr< T, TFreePolicy > &sp)
ConstSmartPtr (const SmartPtr< void > &sp)
ConstSmartPtr (NullSmartPtr)
ConstSmartPtr (void *ptr, void(*freeFunc)(const void *))
const void * get () const
bool invalid () const
returns true if the pointer is invalid, false if not.
void invalidate ()
operator bool () const noexcept
template<class T , template< class TPtr > class TFreePolicy>
ConstSmartPtr< void > & operator= (const ConstSmartPtr< T, TFreePolicy > &sp)
ConstSmartPtr< void > & operator= (const ConstSmartPtr< void > &sp)
template<class T , template< class TPtr > class TFreePolicy>
ConstSmartPtr< void > & operator= (const SmartPtr< T, TFreePolicy > &sp)
ConstSmartPtr< void > & operator= (const SmartPtr< void > &sp)
ConstSmartPtr< void > & operator= (NullSmartPtr)
int refcount () const
template<class T , template< class TPtr > class TFreePolicy>
void set_impl (const void *ptr)
sets the void* to a different location correspoding to a cast to a new type T
bool valid () const
returns true if the pointer is valid, false if not.
~ConstSmartPtr ()
Private Member Functions
void release ()
Private Attributes
void(* m_freeFunc)(const void *)
const void * m_ptr
int * m_refCountPtr
Constructor & Destructor Documentation
ConstSmartPtr() [1/7]
ConstSmartPtr< void >::ConstSmartPtr () inline explicit
ConstSmartPtr() [2/7]
ConstSmartPtr< void >::ConstSmartPtr (void * ptr, void(*)(const void *) freeFunc) inline explicit
ConstSmartPtr() [3/7]
ConstSmartPtr< void >::ConstSmartPtr (NullSmartPtr) inline
ConstSmartPtr() [4/7]
ConstSmartPtr< void >::ConstSmartPtr (const SmartPtr< void > & sp) inline
ConstSmartPtr() [5/7]
ConstSmartPtr< void >::ConstSmartPtr (const ConstSmartPtr< void > & sp) inline
ConstSmartPtr() [6/7]
template<class T , template< class TPtr > class TFreePolicy> ConstSmartPtr< void >::ConstSmartPtr (const SmartPtr< T, TFreePolicy > & sp) inline
ConstSmartPtr() [7/7]
template<class T , template< class TPtr > class TFreePolicy> ConstSmartPtr< void >::ConstSmartPtr (const ConstSmartPtr< T, TFreePolicy > & sp) inline
~ConstSmartPtr()
ConstSmartPtr< void >::~ConstSmartPtr () inline
References ConstSmartPtr< T, FreePolicy >::release().
Member Function Documentation
cast_reinterpret()
template<class T , template< class TPtr > class TFreePolicy> ConstSmartPtr<T, TFreePolicy> ConstSmartPtr< void >::cast_reinterpret () const inline
Returns a SmartPtr with the specified type and shared reference counting.
USE WITH CARE! ONLY COMPATIBLE TYPES SHOULD BE USED
References ConstSmartPtr< T, FreePolicy >::m_ptr.
get()
const void* ConstSmartPtr< void >::get () const inline
References ConstSmartPtr< T, FreePolicy >::m_ptr.
Referenced by ug::bridge::lua::LuaParsing< const void * >::checkAndGet(), ug::vrl::constSmartPointer2JObject(), and ug::vrl::jObject2PtrVector().
invalid()
bool ConstSmartPtr< void >::invalid () const inline
returns true if the pointer is invalid, false if not.
References ConstSmartPtr< T, FreePolicy >::m_ptr.
invalidate()
void ConstSmartPtr< void >::invalidate () inline
References ConstSmartPtr< T, FreePolicy >::m_ptr, ConstSmartPtr< T, FreePolicy >::release(), and ConstSmartPtr< T, FreePolicy >::valid().
operator bool()
ConstSmartPtr< void >::operator bool () const inline explicit noexcept
References ConstSmartPtr< T, FreePolicy >::m_ptr.
operator=() [1/5]
template<class T , template< class TPtr > class TFreePolicy> ConstSmartPtr<void>& ConstSmartPtr< void >::operator= (const ConstSmartPtr< T, TFreePolicy > & sp) inline
References ConstSmartPtr< T, FreePolicy >::m_ptr, ConstSmartPtr< T, FreePolicy >::m_refCount, and ConstSmartPtr< T, FreePolicy >::release().
operator=() [2/5]
ConstSmartPtr<void>& ConstSmartPtr< void >::operator= (const ConstSmartPtr< void > & sp) inline
References m_freeFunc, ConstSmartPtr< T, FreePolicy >::m_ptr, m_ptr, m_refCountPtr, and ConstSmartPtr< T, FreePolicy >::release().
operator=() [3/5]
template<class T , template< class TPtr > class TFreePolicy> ConstSmartPtr<void>& ConstSmartPtr< void >::operator= (const SmartPtr< T, TFreePolicy > & sp) inline
References SmartPtr< T, FreePolicy >::m_ptr, ConstSmartPtr< T, FreePolicy >::m_ptr, SmartPtr< T, FreePolicy >::m_refCount, and ConstSmartPtr< T, FreePolicy >::release().
operator=() [4/5]
ConstSmartPtr<void>& ConstSmartPtr< void >::operator= (const SmartPtr< void > & sp) inline
References SmartPtr< void >::m_freeFunc, ConstSmartPtr< T, FreePolicy >::m_ptr, SmartPtr< void >::m_ptr, SmartPtr< void >::m_refCountPtr, and ConstSmartPtr< T, FreePolicy >::release().
operator=() [5/5]
ConstSmartPtr<void>& ConstSmartPtr< void >::operator= (NullSmartPtr) inline
References ConstSmartPtr< T, FreePolicy >::m_ptr, and ConstSmartPtr< T, FreePolicy >::release().
refcount()
int ConstSmartPtr< void >::refcount () const inline
release()
void ConstSmartPtr< void >::release () inline private
References ConstSmartPtr< T, FreePolicy >::m_ptr.
set_impl()
template<class T , template< class TPtr > class TFreePolicy> void ConstSmartPtr< void >::set_impl (const void * ptr) inline
sets the void* to a different location correspoding to a cast to a new type T
!!! WARNING: THIS METHOD IS DANDGEROUS: DO NOT USE IT UNLESS YOU REALLY KNOW WHAT YOU ARE DOING !!!
References ConstSmartPtr< T, FreePolicy >::m_ptr.
valid()
bool ConstSmartPtr< void >::valid () const inline
returns true if the pointer is valid, false if not.
References ConstSmartPtr< T, FreePolicy >::m_ptr.
Member Data Documentation
m_freeFunc
void(* ConstSmartPtr< void >::m_freeFunc) (const void *) private
Referenced by operator=().
m_ptr
const void* ConstSmartPtr< void >::m_ptr private
Referenced by operator=().
m_refCountPtr
int* ConstSmartPtr< void >::m_refCountPtr private
Referenced by operator=().
The documentation for this class was generated from the following file:
ugbase/common/util/smart_pointer.h