ug4: ug::IsNotOnBoundary Class Reference
ug::IsNotOnBoundary Class Reference
Element callback that returns true, if an element does not lie on the grids boundary.
#include <topology_callbacks.h>
Public Member Functions
IsNotOnBoundary (Grid &g)
bool operator() (Vertex *v)
bool operator() (Edge *e)
bool operator() (Face *f)
Private Member Functions
template<class TElem >
bool callback (TElem *e)
Private Attributes
Grid & m_grid
Detailed Description
Element callback that returns true, if an element does not lie on the grids boundary.
Constructor & Destructor Documentation
ug::IsNotOnBoundary::IsNotOnBoundary (Grid & g) inline
Member Function Documentation
template<class TElem > bool ug::IsNotOnBoundary::callback (TElem * e) inline private
References ug::LiesOnBoundary(), and ug::IsOnBoundary::m_grid.
bool ug::IsNotOnBoundary::operator() (Vertex * v) inline
References ug::IsOnBoundary::callback().
bool ug::IsNotOnBoundary::operator() (Edge * e) inline
References ug::IsOnBoundary::callback().
bool ug::IsNotOnBoundary::operator() (Face * f) inline
References ug::IsOnBoundary::callback().
Member Data Documentation
Grid& ug::IsNotOnBoundary::m_grid private
The documentation for this class was generated from the following file:
ugbase/lib_grid/callbacks/topology_callbacks.h