ug4: ug::AlgebraDebugWriter< TAlgebra > Class Template Reference
ug::AlgebraDebugWriter< TAlgebra > Class Template Reference
Debug writer for connection viewer (based on algebraic information + vector positions only)
#include <algebra_debug_writer.h>
Public Types
typedef TAlgebra algebra_type
type of matrix
typedef IDebugWriter< TAlgebra > base_type
type of base
typedef algebra_type::matrix_type matrix_type
type of matrix
typedef algebra_type::vector_type vector_type
type of vector
Public Types inherited from ug::IDebugWriter< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::IVectorDebugWriter< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
AlgebraDebugWriter ()
Constructor.
virtual void write_matrix (const matrix_type &mat, const char *filename)
write matrix
virtual void write_vector (const vector_type &vec, const char *filename)
write vector
Public Member Functions inherited from ug::IDebugWriter< TAlgebra >
virtual void write_matrix (const matrix_type &mat, const char *name)=0
write matrix
virtual void write_vector (const vector_type &vec, const char *name)=0
write vector
Public Member Functions inherited from ug::IVectorDebugWriter< TAlgebra::vector_type >
int current_dimension () const
returns the current dimension
void enter_section (const char *secDir)
enter a new debugging section
std::string get_base_dir ()
SmartPtr< DebugWriterContext > get_context ()
get the debugging writer context
ConstSmartPtr< DebugWriterContext > get_context () const
get the debugging writer context
int get_dim () const
get the dimensionality
const std::vector< MathVector< dim > > & get_positions () const
returns the positions (only available for current dimension)
IVectorDebugWriter ()
Constructor.
void leave_section ()
leave the current debugging section
virtual void print_message (const char *msg)
prints a message
void set_base_dir (const char *const baseDir)
set the base directory for output files (.vec and .mat)
void set_context (SmartPtr< DebugWriterContext > context)
set the debugging writer context
void set_positions (const std::vector< MathVector< dim > > &vPos)
sets the current positions
void set_positions (IPositionProvider< dim > &provider)
employs a position provider to set the current positions
virtual void update_positions ()
virtual ~IVectorDebugWriter ()
virtual destructor
Private Member Functions
template<int dim>
void write_matrix_dim (const matrix_type &mat, const char *filename)
auxiliary function for matrices
template<int dim>
void write_vector_dim (const vector_type &vec, const char *filename)
auxiliary function for vectors
Additional Inherited Members
Protected Member Functions inherited from ug::IVectorDebugWriter< TAlgebra::vector_type >
void compose_file_path (std::string &path)
composes the path for the files and creates the intermediate directories (up to the base one):
std::vector< MathVector< 1 > > & get_pos (Int2Type< 1 >)
help function to get local ips
const std::vector< MathVector< 1 > > & get_pos (Int2Type< 1 >) const
std::vector< MathVector< 2 > > & get_pos (Int2Type< 2 >)
const std::vector< MathVector< 2 > > & get_pos (Int2Type< 2 >) const
std::vector< MathVector< 3 > > & get_pos (Int2Type< 3 >)
const std::vector< MathVector< 3 > > & get_pos (Int2Type< 3 >) const
std::vector< MathVector< dim > > & positions ()
returns the positions and sets the current dim
Protected Attributes inherited from ug::IVectorDebugWriter< TAlgebra::vector_type >
int m_currentDim
current dimension
SmartPtr< DebugWriterContext > m_spContext
debugging writer context
std::vector< MathVector< 1 > > m_vPos1d
vectors of positions
std::vector< MathVector< 2 > > m_vPos2d
std::vector< MathVector< 3 > > m_vPos3d
Detailed Description
template<typename TAlgebra>
class ug::AlgebraDebugWriter< TAlgebra >
Debug writer for connection viewer (based on algebraic information + vector positions only)
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::AlgebraDebugWriter< TAlgebra >::algebra_type
type of matrix
base_type
template<typename TAlgebra > typedef IDebugWriter<TAlgebra> ug::AlgebraDebugWriter< TAlgebra >::base_type
type of base
matrix_type
template<typename TAlgebra > typedef algebra_type::matrix_type ug::AlgebraDebugWriter< TAlgebra >::matrix_type
type of matrix
vector_type
template<typename TAlgebra > typedef algebra_type::vector_type ug::AlgebraDebugWriter< TAlgebra >::vector_type
type of vector
Constructor & Destructor Documentation
AlgebraDebugWriter()
template<typename TAlgebra > ug::AlgebraDebugWriter< TAlgebra >::AlgebraDebugWriter () inline
Constructor.
Member Function Documentation
write_matrix()
template<typename TAlgebra > virtual void ug::AlgebraDebugWriter< TAlgebra >::write_matrix (const matrix_type & mat, const char * filename) inline virtual
write matrix
References ug::IVectorDebugWriter< TAlgebra::vector_type >::current_dimension(), ug::FileTypeIs(), UG_ASSERT, and UG_THROW.
write_matrix_dim()
template<typename TAlgebra > template<int dim> void ug::AlgebraDebugWriter< TAlgebra >::write_matrix_dim (const matrix_type & mat, const char * filename) inline private
auxiliary function for matrices
References dim, ug::IVectorDebugWriter< TAlgebra::vector_type >::get_base_dir(), name, and UG_THROW.
write_vector()
template<typename TAlgebra > virtual void ug::AlgebraDebugWriter< TAlgebra >::write_vector (const vector_type & vec, const char * filename) inline virtual
write vector
References ug::IVectorDebugWriter< TAlgebra::vector_type >::current_dimension(), and UG_ASSERT.
write_vector_dim()
template<typename TAlgebra > template<int dim> void ug::AlgebraDebugWriter< TAlgebra >::write_vector_dim (const vector_type & vec, const char * filename) inline private
auxiliary function for vectors
References dim, ug::IVectorDebugWriter< TAlgebra::vector_type >::get_base_dir(), name, and UG_THROW.
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/algebra_debug_writer.h