ug4: SmallObject< maxObjSize, maxChunkSize > Class Template Reference
SmallObject< maxObjSize, maxChunkSize > Class Template Reference
#include <small_object_allocator.h>
Public Member Functions
virtual ~SmallObject ()
Static Public Member Functions
static void operator delete (void *p, std::size_t size)
static void * operator new (std::size_t size)
Detailed Description
template<std::size_t maxObjSize = 64, std::size_t maxChunkSize = 4096>
class SmallObject< maxObjSize, maxChunkSize >
This class implements the operators new and delete, so that they use the SmallObjectAllocator. By deriving from this class, your objects will be allocated through the SmallObjectAllocator too.
Constructor & Destructor Documentation
~SmallObject()
template<std::size_t maxObjSize = 64, std::size_t maxChunkSize = 4096> virtual SmallObject< maxObjSize, maxChunkSize >::~SmallObject () inline virtual
Member Function Documentation
operator delete()
template<std::size_t maxObjSize, std::size_t maxChunkSize> void SmallObject< maxObjSize, maxChunkSize >::operator delete (void * p, std::size_t size) static
References SmallObjectAllocator< maxObjSize, maxChunkSize >::deallocate(), and SmallObjectAllocator< maxObjSize, maxChunkSize >::inst().
operator new()
template<std::size_t maxObjSize, std::size_t maxChunkSize> void * SmallObject< maxObjSize, maxChunkSize >::operator new (std::size_t size) static
References SmallObjectAllocator< maxObjSize, maxChunkSize >::allocate(), and SmallObjectAllocator< maxObjSize, maxChunkSize >::inst().
The documentation for this class was generated from the following files:
ugbase/common/allocators/small_object_allocator.h
ugbase/common/allocators/small_object_allocator_impl.h