ug4: ug::ComPol_SynchronizeDistInfos< TLayout > Class Template Reference
ug::ComPol_SynchronizeDistInfos< TLayout > Class Template Reference
Communicates the distribution infos through existing interfaces.
Public Types
typedef Layout::Element Element
typedef Layout::Type GeomObj
typedef Layout::Interface Interface
typedef Interface::const_iterator InterfaceIter
typedef TLayout Layout
Public Types inherited from pcl::ICommunicationPolicy< TLayout >
typedef Layout::Interface Interface
typedef TLayout Layout
Public Member Functions
virtual bool collect (ug::BinaryBuffer &buff, const Interface &intfc)
write target processes and move-flag
ComPol_SynchronizeDistInfos (DistInfoSupplier &distInfos, bool merge)
void enable_merge (bool enable)
virtual bool extract (ug::BinaryBuffer &buff, const Interface &intfc)
read target processes and move-flag
virtual int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
bool merge_enabled ()
virtual ~ComPol_SynchronizeDistInfos ()
Public Member Functions inherited from pcl::ICommunicationPolicy< TLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual ~ICommunicationPolicy ()
Protected Attributes
DistInfoSupplier & m_distInfos
bool m_mergeEnabled
Detailed Description
template<class TLayout>
class ug::ComPol_SynchronizeDistInfos< TLayout >
Communicates the distribution infos through existing interfaces.
Distribution infos are packed into the send buffer for each node and are either merged with existing entries or existing entries are simply overwritten. The merge/overwrite behavior can be chosen through the member method enable_merge.
Member Typedef Documentation
Element
template<class TLayout> typedef Layout::Element ug::ComPol_SynchronizeDistInfos< TLayout >::Element
GeomObj
template<class TLayout> typedef Layout::Type ug::ComPol_SynchronizeDistInfos< TLayout >::GeomObj
Interface
template<class TLayout> typedef Layout::Interface ug::ComPol_SynchronizeDistInfos< TLayout >::Interface
InterfaceIter
template<class TLayout> typedef Interface::const_iterator ug::ComPol_SynchronizeDistInfos< TLayout >::InterfaceIter
Layout
template<class TLayout> typedef TLayout ug::ComPol_SynchronizeDistInfos< TLayout >::Layout
Constructor & Destructor Documentation
ComPol_SynchronizeDistInfos()
template<class TLayout> ug::ComPol_SynchronizeDistInfos< TLayout >::ComPol_SynchronizeDistInfos (DistInfoSupplier & distInfos, bool merge) inline
~ComPol_SynchronizeDistInfos()
template<class TLayout> virtual ug::ComPol_SynchronizeDistInfos< TLayout >::~ComPol_SynchronizeDistInfos () inline virtual
Member Function Documentation
collect()
template<class TLayout> virtual bool ug::ComPol_SynchronizeDistInfos< TLayout >::collect (ug::BinaryBuffer & buff, const Interface & intfc) inline virtual
write target processes and move-flag
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::Serialize().
enable_merge()
template<class TLayout> void ug::ComPol_SynchronizeDistInfos< TLayout >::enable_merge (bool enable) inline
Referenced by ug::SynchronizeDistInfos().
extract()
template<class TLayout> virtual bool ug::ComPol_SynchronizeDistInfos< TLayout >::extract (ug::BinaryBuffer & buff, const Interface & intfc) inline virtual
read target processes and move-flag
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::Deserialize().
get_required_buffer_size()
template<class TLayout> virtual int ug::ComPol_SynchronizeDistInfos< TLayout >::get_required_buffer_size (const Interface & interface) inline virtual
returns the size of the buffer in bytes, that will be required for interface-communication.
Determines the size of the buffer on which the extract and receive methods for the given interface will operate. If the buffer-size can't be calculated on both sides (sender and receiver) this method should return -1. This will lead to an additional communication step in which buffer-sizes will be exchanged. If the buffer-size can be calculated on both sides, it makes sense to do so, since this leads to less communication and overall improved performance. The buffer-size has to exactly match the size of required memory. Make sure that you completely fill the buffer during collect(...) and that you read all data during extract(...). The default implementation returns -1.
Reimplemented from pcl::ICommunicationPolicy< TLayout >.
merge_enabled()
template<class TLayout> bool ug::ComPol_SynchronizeDistInfos< TLayout >::merge_enabled () inline
Member Data Documentation
m_distInfos
template<class TLayout> DistInfoSupplier& ug::ComPol_SynchronizeDistInfos< TLayout >::m_distInfos protected
m_mergeEnabled
template<class TLayout> bool ug::ComPol_SynchronizeDistInfos< TLayout >::m_mergeEnabled protected
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/distribution.cpp