ug4: ug::UGProfileNode Class Reference
ug::UGProfileNode Class Reference
#include <profile_node.h>
Public Member Functions
std::string call_tree () const
std::string call_tree (double dSkipMarginal) const
std::string child_self_memory_sorted () const
std::string child_self_memory_sorted (double dSkipMarginal) const
std::string child_self_time_sorted () const
std::string child_self_time_sorted (double dSkipMarginal) const
std::string entry_count_sorted () const
std::string entry_count_sorted (double dSkipMarginal) const
double get_avg_entry_count () const
double get_avg_self_time () const
double get_avg_self_time_ms () const
double get_avg_total_time () const
double get_avg_total_time_ms () const
double get_self_mem () const
double get_total_mem () const
std::string groups () const
std::string total_memory_sorted () const
std::string total_memory_sorted (double dSkipMarginal) const
std::string total_time_sorted () const
std::string total_time_sorted (double dSkipMarginal) const
bool valid () const
Static Public Member Functions
static void CheckForTooSmallNodes ()
static const UGProfileNode * get_root ()
Detailed Description
UGProfileNode class for more information about Shiny's ProfileNode.
Note
do NOT introduce variables or virtual functions to this class. Shiny::ProfileNode are cast directly to UGProfileNode and therefore are assumed to have exactly the same size and format. If you really need to change that you'd have to change the whole GetProfileNode-process.
Member Function Documentation
call_tree() [1/2]
std::string ug::UGProfileNode::call_tree () const inline
References call_tree().
Referenced by call_tree().
call_tree() [2/2]
string ug::UGProfileNode::call_tree (double dSkipMarginal) const
Parameters
dSkipMarginal nodes with full*dSkipMarginal > node->full[ms or mem] are skipped
Returns
call tree profile information
CheckForTooSmallNodes()
void ug::UGProfileNode::CheckForTooSmallNodes () static
Referenced by ugshell_main().
child_self_memory_sorted() [1/2]
std::string ug::UGProfileNode::child_self_memory_sorted () const inline
References child_self_memory_sorted().
Referenced by child_self_memory_sorted().
child_self_memory_sorted() [2/2]
string ug::UGProfileNode::child_self_memory_sorted (double dSkipMarginal) const
Parameters
dSkipMarginal nodes with full*dSkipMarginal > node->full[ms or mem] are skipped
Returns
a table with all profile nodes information, sorted by self memory
child_self_time_sorted() [1/2]
std::string ug::UGProfileNode::child_self_time_sorted () const inline
References child_self_time_sorted().
Referenced by child_self_time_sorted().
child_self_time_sorted() [2/2]
string ug::UGProfileNode::child_self_time_sorted (double dSkipMarginal) const
Parameters
dSkipMarginal nodes with full*dSkipMarginal > node->full[ms or mem] are skipped
Returns
a table with all profile nodes information, sorted by self time
entry_count_sorted() [1/2]
std::string ug::UGProfileNode::entry_count_sorted () const inline
References entry_count_sorted().
Referenced by entry_count_sorted().
entry_count_sorted() [2/2]
string ug::UGProfileNode::entry_count_sorted (double dSkipMarginal) const
Parameters
dSkipMarginal nodes with full*dSkipMarginal > node->full[ms or mem] are skipped
Returns
a table with all profile nodes information, sorted by entry count
get_avg_entry_count()
double ug::UGProfileNode::get_avg_entry_count () const
Returns
number of entries in this profiler node
get_avg_self_time()
double ug::UGProfileNode::get_avg_self_time () const
Returns
time in seconds spend in this node excluding subnodes
get_avg_self_time_ms()
double ug::UGProfileNode::get_avg_self_time_ms () const
Returns
time in milliseconds spend in this node excluding subnodes
get_avg_total_time()
double ug::UGProfileNode::get_avg_total_time () const
Returns
time in seconds spend in this node including subnodes
get_avg_total_time_ms()
double ug::UGProfileNode::get_avg_total_time_ms () const
Returns
time in milliseconds spend in this node including subnodes
get_root()
static const UGProfileNode* ug::UGProfileNode::get_root () static
get_self_mem()
double ug::UGProfileNode::get_self_mem () const
get_total_mem()
double ug::UGProfileNode::get_total_mem () const
groups()
string ug::UGProfileNode::groups () const
Returns
Profiling group information
total_memory_sorted() [1/2]
std::string ug::UGProfileNode::total_memory_sorted () const inline
References total_memory_sorted().
Referenced by total_memory_sorted().
total_memory_sorted() [2/2]
string ug::UGProfileNode::total_memory_sorted (double dSkipMarginal) const
Parameters
dSkipMarginal nodes with full*dSkipMarginal > node->full[ms or mem] are skipped
Returns
a table with all profile nodes information, sorted by total memory
total_time_sorted() [1/2]
std::string ug::UGProfileNode::total_time_sorted () const inline
References total_time_sorted().
Referenced by total_time_sorted().
total_time_sorted() [2/2]
string ug::UGProfileNode::total_time_sorted (double dSkipMarginal) const
Parameters
dSkipMarginal nodes with full*dSkipMarginal > node->full[ms or mem] are skipped
Returns
a table with all profile nodes information, sorted by total time
valid()
bool ug::UGProfileNode::valid () const
Returns
true if node has been found
The documentation for this class was generated from the following files:
ugbase/common/profiler/profile_node.h
ugbase/common/profiler/profile_node.cpp