ug4: ug::StdHNodeAdjuster Class Reference
ug::StdHNodeAdjuster Class Reference
Makes sure that elements are marked correctly so that hnode-refinement produces a valid grid.
#include <std_hnode_adjuster.h>
Public Member Functions
virtual void ref_marks_changed (IRefiner &ref, const std::vector< Vertex * > &vrts, const std::vector< Edge * > &edges, const std::vector< Face * > &faces, const std::vector< Volume * > &vols)
virtual ~StdHNodeAdjuster ()
Public Member Functions inherited from ug::IRefMarkAdjuster
virtual void coarsen_marks_changed (IRefiner &ref, const std::vector< Vertex * > &vrts, const std::vector< Edge * > &edges, const std::vector< Face * > &faces, const std::vector< Volume * > &vols)
virtual void enable (bool enable)
virtual bool enabled () const
IRefMarkAdjuster ()
virtual ~IRefMarkAdjuster ()
void enable_node_dependency_order_1 (bool bEnable)
enables or disables node-dependency-order-1.
bool node_dependency_order_1_enabled ()
enables or disables node-dependency-order-1.
Static Public Member Functions
static SPStdHNodeAdjuster create ()
Detailed Description
Makes sure that elements are marked correctly so that hnode-refinement produces a valid grid.
This adjuster regards the grid as a serial grid. If the grid represents a part of a distributed grid, then the additional use of a parallel adjuster is required.
Constructor & Destructor Documentation
~StdHNodeAdjuster()
virtual ug::StdHNodeAdjuster::~StdHNodeAdjuster () inline virtual
Member Function Documentation
create()
static SPStdHNodeAdjuster ug::StdHNodeAdjuster::create () inline static
Referenced by ug::HangingNodeRefinerBase< TSelector >::HangingNodeRefinerBase().
ref_marks_changed()
void ug::StdHNodeAdjuster::ref_marks_changed (IRefiner & ref, const std::vector< Vertex * > & vrts, const std::vector< Edge * > & edges, const std::vector< Face * > & faces, const std::vector< Volume * > & vols) virtual
Reimplemented from ug::IRefMarkAdjuster.
References ug::Grid::associated_elements(), ug::ConstrainedVertex::get_constraining_object(), ug::IRefiner::get_mark(), ug::GetGridObjectCenter(), ug::IRefiner::grid(), ug::Grid::has_periodic_boundaries(), ug::GridObject::is_constrained(), ug::Grid::is_parallel(), ug::IRefiner::mark(), ug::mark_if_periodic(), ug::IRefMarkAdjuster::node_dependency_order_1_enabled(), ug::Grid::num_faces(), ug::FaceVertices::num_vertices(), ug::Grid::num_volumes(), ug::RM_ANISOTROPIC, ug::RM_LOCAL, ug::RM_REFINE, ug::PointerConstArray< TPtr >::size(), UG_ASSERT, ug::EdgeVertices::vertex(), and ug::FaceVertices::vertex().
The documentation for this class was generated from the following files:
ugbase/lib_grid/refinement/ref_mark_adjusters/std_hnode_adjuster.h
ugbase/lib_grid/refinement/ref_mark_adjusters/std_hnode_adjuster.cpp