ug4: boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap > Class Template Reference
boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap > Class Template Reference
#include <bucket_sorter.hpp>
Classes
class stack_
Public Types
typedef BucketType bucket_type
typedef Bucket Bucket_type
typedef stack_< ConstIter, ConstIndexValueMap > const_stack
typedef std::vector< value_type >::const_iterator ConstIndexValueMap
typedef std::vector< size_type >::const_iterator ConstIter
typedef std::vector< value_type >::iterator IndexValueMap
typedef std::vector< size_type >::iterator Iter
typedef std::vector< value_type >::size_type size_type
typedef stack_< Iter, IndexValueMap > stack
typedef ValueIndexMap value_index_map
typedef ValueType value_type
Public Member Functions
bucket_sorter ()
bucket_sorter (size_type _length, bucket_type _max_bucket, const Bucket &_bucket=Bucket(), const ValueIndexMap &_id=ValueIndexMap())
stack operator[] (const bucket_type &i)
const_stack operator[] (const bucket_type &i) const
void push (const value_type &x)
void push_back (const value_type &x)
void push_front (const value_type &x)
void remove (const value_type &x)
size_t size () const
void update (const value_type &x)
void update_back (const value_type &x)
void update_front (const value_type &x)
Static Public Member Functions
static size_type invalid_value ()
Protected Attributes
Bucket bucket
std::vector< size_type >::iterator head
ValueIndexMap id
std::vector< value_type > id_to_value
std::vector< size_type > next
std::vector< size_type > prev
std::vector< size_type >::iterator tail
Member Typedef Documentation
bucket_type
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > typedef BucketType boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket_type
Bucket_type
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > typedef Bucket boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::Bucket_type
const_stack
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > typedef stack_<ConstIter, ConstIndexValueMap> boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::const_stack
ConstIndexValueMap
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > typedef std::vector<value_type>::const_iterator boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::ConstIndexValueMap
ConstIter
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > typedef std::vector<size_type>::const_iterator boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::ConstIter
IndexValueMap
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > typedef std::vector<value_type>::iterator boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::IndexValueMap
Iter
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > typedef std::vector<size_type>::iterator boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::Iter
size_type
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > typedef std::vector<value_type>::size_type boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::size_type
stack
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > typedef stack_<Iter, IndexValueMap> boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack
value_index_map
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > typedef ValueIndexMap boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::value_index_map
value_type
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > typedef ValueType boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::value_type
Constructor & Destructor Documentation
bucket_sorter() [1/2]
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket_sorter (size_type _length, bucket_type _max_bucket, const Bucket & _bucket = Bucket(), const ValueIndexMap & _id = ValueIndexMap()) inline
References boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::head, boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::invalid_value(), and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::next.
bucket_sorter() [2/2]
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket_sorter () inline
References untested.
Member Function Documentation
invalid_value()
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > static size_type boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::invalid_value () inline static
Referenced by boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket_sorter(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::const_iterator::operator++(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::pop(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::push_back(), and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::push_front().
operator[]() [1/2]
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > stack boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::operator[] (const bucket_type & i) inline
References boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::head, boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::id_to_value, boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::next, boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::prev, and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::tail.
operator[]() [2/2]
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > const_stack boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::operator[] (const bucket_type & i) const inline
References boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::head, boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::id_to_value, boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::next, boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::prev, and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::tail.
push()
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > void boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push (const value_type & x) inline
References boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push_front().
push_back()
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > void boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push_back (const value_type & x) inline
References boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket, boost::get(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::id_to_value, and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::next.
push_front()
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > void boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push_front (const value_type & x) inline
References boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket, boost::get(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::id_to_value, and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::next.
Referenced by boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push().
remove()
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > void boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::remove (const value_type & x) inline
References boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket, boost::get(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::head, boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::next, boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::prev, and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::size().
Referenced by boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::update_back(), and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::update_front().
size()
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > size_t boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::size () const inline
References boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::head, and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::next.
Referenced by boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::remove().
update()
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > void boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::update (const value_type & x) inline
References boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::update_front().
update_back()
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > void boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::update_back (const value_type & x) inline
References boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket, itested, and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::remove().
update_front()
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > void boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::update_front (const value_type & x) inline
References boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket, and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::remove().
Referenced by boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::update().
Member Data Documentation
bucket
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > Bucket boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket protected
Referenced by boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push_back(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push_front(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::remove(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::update_back(), and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::update_front().
head
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > std::vector<size_type>::iterator boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::head protected
Referenced by boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket_sorter(), and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::remove().
id
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > ValueIndexMap boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::id protected
id_to_value
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > std::vector<value_type> boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::id_to_value protected
Referenced by boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::operator[](), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push_back(), and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push_front().
next
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > std::vector<size_type> boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::next protected
Referenced by boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::bucket_sorter(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push_back(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push_front(), and boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::remove().
prev
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > std::vector<size_type> boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::prev protected
Referenced by boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::remove().
tail
template<class BucketType , class ValueType , class Bucket , class ValueIndexMap > std::vector<size_type>::iterator boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::tail protected
The documentation for this class was generated from the following file:
ugbase/common/util/bucket_sorter.hpp