ug4: FixedAllocator Class Reference
FixedAllocator Class Reference
#include <small_object_allocator.h>
Classes
struct Chunk
Public Member Functions
void * allocate ()
void deallocate (void *p)
FixedAllocator (std::size_t blockSize, unsigned char numBlocksPerChunk)
Private Types
typedef std::vector< Chunk > Chunks
Private Member Functions
bool pointer_is_in_chunk (void *p, Chunk *chunk)
Private Attributes
Chunk * m_allocChunk
std::size_t m_blockSize
Chunks m_chunks
int m_deallocChunkIndex
int m_emptyChunkIndex
unsigned char m_numBlocksPerChunk
std::size_t m_numFreeBlocks
Detailed Description
Instances of this class can be used to allocate small objects of the same size in a highly efficient way.
Member Typedef Documentation
typedef std::vector<Chunk> FixedAllocator::Chunks private
Constructor & Destructor Documentation
FixedAllocator::FixedAllocator (std::size_t blockSize, unsigned char numBlocksPerChunk)
References allocate().
Member Function Documentation
void * FixedAllocator::allocate ()
References FixedAllocator::Chunk::allocate(), deallocate(), FixedAllocator::Chunk::init(), m_allocChunk, m_blockSize, m_chunks, m_deallocChunkIndex, FixedAllocator::Chunk::m_numAvailableBlocks, m_numBlocksPerChunk, and m_numFreeBlocks.
Referenced by FixedAllocator().
void FixedAllocator::deallocate (void * p)
References FixedAllocator::Chunk::deallocate(), FixedAllocator::Chunk::init(), m_blockSize, m_chunks, m_deallocChunkIndex, m_emptyChunkIndex, FixedAllocator::Chunk::m_numAvailableBlocks, m_numBlocksPerChunk, m_numFreeBlocks, and pointer_is_in_chunk().
Referenced by allocate().
bool FixedAllocator::pointer_is_in_chunk (void * p, Chunk * chunk) inline private
References m_blockSize, m_numBlocksPerChunk, and FixedAllocator::Chunk::m_pData.
Referenced by deallocate().
Member Data Documentation
Chunk* FixedAllocator::m_allocChunk private
Referenced by allocate().
std::size_t FixedAllocator::m_blockSize private
Referenced by allocate(), deallocate(), and pointer_is_in_chunk().
Chunks FixedAllocator::m_chunks private
Referenced by allocate(), and deallocate().
int FixedAllocator::m_deallocChunkIndex private
Referenced by allocate(), and deallocate().
int FixedAllocator::m_emptyChunkIndex private
Referenced by deallocate().
unsigned char FixedAllocator::m_numBlocksPerChunk private
Referenced by allocate(), deallocate(), and pointer_is_in_chunk().
std::size_t FixedAllocator::m_numFreeBlocks private
Referenced by allocate(), and deallocate().
The documentation for this class was generated from the following files:
ugbase/common/allocators/small_object_allocator.h
ugbase/common/allocators/small_object_allocator.cpp