ug4: ug::AssocElemIter< TElem, TAssocElem, VSorted > Class Template Reference
ug::AssocElemIter< TElem, TAssocElem, VSorted > Class Template Reference
Iterator that allows to traverse associated elements of a given element.
#include <associated_elements_iterator.h>
Public Member Functions
AssocElemIter (Grid &grid, TElem *elem, typename Grid::traits< TAssocElem >::callback cbConsiderElem=ConsiderAll())
AssocElemIter (typename Grid::traits< TAssocElem >::callback cbConsiderElem=ConsiderAll())
AssocElemIter end () const
bool invalid () const
bool operator!= (const AssocElemIter &iter) const
returns true if exactly one iterator is invalid or if the iterators point to different elements.
TAssocElem * operator* ()
AssocElemIter & operator++ ()
AssocElemIter operator++ (int unused)
bool operator== (const AssocElemIter &iter) const
returns true if both iterators are invalid or if both point to the same elemnt.
void reinit (Grid &grid, TElem *elem)
void reinit (Grid &grid, TElem *elem, typename Grid::traits< TAssocElem >::callback cb)
void set_callback (typename Grid::traits< TAssocElem >::callback cbConsiderElem)
bool valid () const
Private Member Functions
TAssocElem * dereference () const
dereference
bool equal (AssocElemIter const &other) const
returns true if both iterators are invalid or if both point to the same elemnt.
void increment ()
returns next iterator
void init (Grid &grid, TElem *elem)
Private Attributes
Grid::traits< TAssocElem >::secure_container m_assElems
Grid::traits< TAssocElem >::callback m_cbConsiderElem
size_t m_i
Detailed Description
template<class TElem, class TAssocElem, bool VSorted = false>
class ug::AssocElemIter< TElem, TAssocElem, VSorted >
Iterator that allows to traverse associated elements of a given element.
The type of the element whose associated elements shall be traversed has to be specified through the template argument TElem. The type of the associated elements has to be specified through the TAssocElem template argument. Through VRefOrder one can choose whether the traversed associated elements shall be sorted in the order in which they appear in the reference element of given element (false by default).
Constructor & Destructor Documentation
AssocElemIter() [1/2]
template<class TElem , class TAssocElem , bool VSorted = false> ug::AssocElemIter< TElem, TAssocElem, VSorted >::AssocElemIter (typename Grid::traits< TAssocElem >::callback cbConsiderElem = ConsiderAll()) inline
AssocElemIter() [2/2]
template<class TElem , class TAssocElem , bool VSorted = false> ug::AssocElemIter< TElem, TAssocElem, VSorted >::AssocElemIter (Grid & grid, TElem * elem, typename Grid::traits< TAssocElem >::callback cbConsiderElem = ConsiderAll()) inline
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::init().
Member Function Documentation
dereference()
template<class TElem , class TAssocElem , bool VSorted = false> TAssocElem* ug::AssocElemIter< TElem, TAssocElem, VSorted >::dereference () const inline private
dereference
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_assElems, and ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_i.
Referenced by ug::AssocElemIter< TElem, TAssocElem, VSorted >::equal(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::increment(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::init(), and ug::AssocElemIter< TElem, TAssocElem, VSorted >::operator*().
end()
template<class TElem , class TAssocElem , bool VSorted = false> AssocElemIter ug::AssocElemIter< TElem, TAssocElem, VSorted >::end () const inline
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_i.
equal()
template<class TElem , class TAssocElem , bool VSorted = false> bool ug::AssocElemIter< TElem, TAssocElem, VSorted >::equal (AssocElemIter< TElem, TAssocElem, VSorted > const & other) const inline private
returns true if both iterators are invalid or if both point to the same elemnt.
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::dereference(), and ug::AssocElemIter< TElem, TAssocElem, VSorted >::valid().
Referenced by ug::AssocElemIter< TElem, TAssocElem, VSorted >::operator!=(), and ug::AssocElemIter< TElem, TAssocElem, VSorted >::operator==().
increment()
template<class TElem , class TAssocElem , bool VSorted = false> void ug::AssocElemIter< TElem, TAssocElem, VSorted >::increment () inline private
returns next iterator
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::dereference(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_cbConsiderElem, ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_i, and ug::AssocElemIter< TElem, TAssocElem, VSorted >::valid().
Referenced by ug::AssocElemIter< TElem, TAssocElem, VSorted >::init(), and ug::AssocElemIter< TElem, TAssocElem, VSorted >::operator++().
init()
template<class TElem , class TAssocElem , bool VSorted = false> void ug::AssocElemIter< TElem, TAssocElem, VSorted >::init (Grid & grid, TElem * elem) inline private
References ug::Grid::associated_elements(), ug::Grid::associated_elements_sorted(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::dereference(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::increment(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_assElems, ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_cbConsiderElem, and ug::AssocElemIter< TElem, TAssocElem, VSorted >::valid().
Referenced by ug::AssocElemIter< TElem, TAssocElem, VSorted >::AssocElemIter(), and ug::AssocElemIter< TElem, TAssocElem, VSorted >::reinit().
invalid()
template<class TElem , class TAssocElem , bool VSorted = false> bool ug::AssocElemIter< TElem, TAssocElem, VSorted >::invalid () const inline
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_assElems, and ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_i.
operator!=()
template<class TElem , class TAssocElem , bool VSorted = false> bool ug::AssocElemIter< TElem, TAssocElem, VSorted >::operator!= (const AssocElemIter< TElem, TAssocElem, VSorted > & iter) const inline
returns true if exactly one iterator is invalid or if the iterators point to different elements.
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::equal().
operator*()
template<class TElem , class TAssocElem , bool VSorted = false> TAssocElem* ug::AssocElemIter< TElem, TAssocElem, VSorted >::operator* () inline
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::dereference().
operator++() [1/2]
template<class TElem , class TAssocElem , bool VSorted = false> AssocElemIter& ug::AssocElemIter< TElem, TAssocElem, VSorted >::operator++ () inline
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::increment().
operator++() [2/2]
template<class TElem , class TAssocElem , bool VSorted = false> AssocElemIter ug::AssocElemIter< TElem, TAssocElem, VSorted >::operator++ (int unused) inline
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::increment().
operator==()
template<class TElem , class TAssocElem , bool VSorted = false> bool ug::AssocElemIter< TElem, TAssocElem, VSorted >::operator== (const AssocElemIter< TElem, TAssocElem, VSorted > & iter) const inline
returns true if both iterators are invalid or if both point to the same elemnt.
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::equal().
reinit() [1/2]
template<class TElem , class TAssocElem , bool VSorted = false> void ug::AssocElemIter< TElem, TAssocElem, VSorted >::reinit (Grid & grid, TElem * elem) inline
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::init(), and ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_i.
Referenced by ug::SelectKinkVertices(), and ug::SimplifyPolylines().
reinit() [2/2]
template<class TElem , class TAssocElem , bool VSorted = false> void ug::AssocElemIter< TElem, TAssocElem, VSorted >::reinit (Grid & grid, TElem * elem, typename Grid::traits< TAssocElem >::callback cb) inline
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::init(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_cbConsiderElem, and ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_i.
set_callback()
template<class TElem , class TAssocElem , bool VSorted = false> void ug::AssocElemIter< TElem, TAssocElem, VSorted >::set_callback (typename Grid::traits< TAssocElem >::callback cbConsiderElem) inline
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_cbConsiderElem.
valid()
template<class TElem , class TAssocElem , bool VSorted = false> bool ug::AssocElemIter< TElem, TAssocElem, VSorted >::valid () const inline
References ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_assElems, and ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_i.
Referenced by ug::AssocElemIter< TElem, TAssocElem, VSorted >::equal(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::increment(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::init(), ug::SelectKinkVertices(), and ug::SimplifyPolylines().
Member Data Documentation
m_assElems
template<class TElem , class TAssocElem , bool VSorted = false> Grid::traits<TAssocElem>::secure_container ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_assElems private
Referenced by ug::AssocElemIter< TElem, TAssocElem, VSorted >::dereference(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::init(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::invalid(), and ug::AssocElemIter< TElem, TAssocElem, VSorted >::valid().
m_cbConsiderElem
template<class TElem , class TAssocElem , bool VSorted = false> Grid::traits<TAssocElem>::callback ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_cbConsiderElem private
Referenced by ug::AssocElemIter< TElem, TAssocElem, VSorted >::increment(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::init(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::reinit(), and ug::AssocElemIter< TElem, TAssocElem, VSorted >::set_callback().
m_i
template<class TElem , class TAssocElem , bool VSorted = false> size_t ug::AssocElemIter< TElem, TAssocElem, VSorted >::m_i private
Referenced by ug::AssocElemIter< TElem, TAssocElem, VSorted >::dereference(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::end(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::increment(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::invalid(), ug::AssocElemIter< TElem, TAssocElem, VSorted >::reinit(), and ug::AssocElemIter< TElem, TAssocElem, VSorted >::valid().
The documentation for this class was generated from the following file:
ugbase/lib_grid/iterators/associated_elements_iterator.h