ug4: ug::FunctionGroup Class Reference
ug::FunctionGroup Class Reference
#include <function_group.h>
Public Member Functions
void add (size_t fct)
adds a function by id to this group
void add (const char *name)
adds function with a given name to this group
void add (const std::string &name)
adds function with a given name to this group
void add (const std::vector< std::string > &name)
adds functions with a given names to this group
void add (const FunctionGroup &fctGroup)
adds all functions of a function group
void add_all ()
selects all subsets in the order of the underlying pattern
void clear ()
clear all subsets
bool contains (size_t uniqueID) const
returns true if unique id is contained in this group
bool contains (const FunctionGroup &fctGroup) const
returns true if all unique ids of another function group are contained
int dim (size_t i) const
dimension of a function
int dim () const
common dimension of all functions
bool empty () const
returns if function group is empty
ConstSmartPtr< FunctionPattern > function_pattern () const
get underlying function pattern
FunctionGroup ()
Default Constructor.
FunctionGroup (ConstSmartPtr< FunctionPattern > spFuncPattern)
Constructor setting function pattern.
FunctionGroup (ConstSmartPtr< FunctionPattern > spFuncPattern, const char *name)
Constructor setting function pattern and function.
FunctionGroup (ConstSmartPtr< FunctionPattern > spFuncPattern, const std::string &name)
Constructor setting function pattern and function.
FunctionGroup (ConstSmartPtr< FunctionPattern > spFuncPattern, const std::vector< std::string > &vName)
Constructor setting function pattern and functions.
size_t local_index (size_t uniqueID) const
return index in Function group for a function
const char * name (size_t i) const
returns the name of a function
std::string names () const
returns the comma-separted names of all functions
size_t operator[] (size_t i) const
returns unique function id of a function
void remove (size_t fct)
removes a function by id from this group
void remove (const char *name)
removes function with a given name from this group
void remove (const std::string &name)
removes function with a given name from this group
void remove (const std::vector< std::string > &vName)
removes functions with a given names from this group
void set_function_pattern (ConstSmartPtr< FunctionPattern > spFuncPattern)
set underlying function pattern
size_t size () const
number of functions in this group
void sort ()
sorts the selected functions by increasing unique id
size_t unique_id (size_t i) const
returns unique function id of a function
LFEID local_finite_element_id (size_t i) const
LFEID lfeid (size_t i) const
Protected Member Functions
bool is_init () const
returns if FunctionGroup is ready for use
Protected Attributes
ConstSmartPtr< FunctionPattern > m_spFunctionPattern
underlying function pattern
std::vector< size_t > m_vFunction
vector holding all selected unique function ids
Detailed Description
Group of functions represented by integers FunctionGroup is just a group of size_t, representing some functions. The function group is based on a FunctionPattern and the integer represent the position of the function in the function pattern. Selection of functions is best via usage of symbolic names of the functions.
Constructor & Destructor Documentation
FunctionGroup() [1/5]
ug::FunctionGroup::FunctionGroup ()
Default Constructor.
References clear().
FunctionGroup() [2/5]
ug::FunctionGroup::FunctionGroup (ConstSmartPtr< FunctionPattern > spFuncPattern)
Constructor setting function pattern.
References clear().
FunctionGroup() [3/5]
ug::FunctionGroup::FunctionGroup (ConstSmartPtr< FunctionPattern > spFuncPattern, const char * name)
Constructor setting function pattern and function.
References add(), and clear().
FunctionGroup() [4/5]
ug::FunctionGroup::FunctionGroup (ConstSmartPtr< FunctionPattern > spFuncPattern, const std::string & name)
Constructor setting function pattern and function.
References add(), and clear().
FunctionGroup() [5/5]
ug::FunctionGroup::FunctionGroup (ConstSmartPtr< FunctionPattern > spFuncPattern, const std::vector< std::string > & vName)
Constructor setting function pattern and functions.
References add(), and clear().
Member Function Documentation
add() [1/5]
void ug::FunctionGroup::add (size_t fct)
adds a function by id to this group
References ug::find(), is_init(), m_spFunctionPattern, m_vFunction, name(), ug::TrimString(), and UG_THROW.
Referenced by add(), add_all(), ug::CheckGFforNaN(), ug::CreateUnionOfFunctionGroups(), ug::DependentUserData< MathVector< TGridFunction::dim >, dim >::extract_fct_grp(), function_pattern(), FunctionGroup(), ug::SumGFValuesAt(), and ug::IElemDiscBase< TDomain >::update_function_index_mapping().
add() [2/5]
void ug::FunctionGroup::add (const char * name)
adds function with a given name to this group
References add(), and ug::TokenizeString().
add() [3/5]
void ug::FunctionGroup::add (const std::string & name)
adds function with a given name to this group
add() [4/5]
void ug::FunctionGroup::add (const std::vector< std::string > & name)
adds functions with a given names to this group
add() [5/5]
void ug::FunctionGroup::add (const FunctionGroup & fctGroup)
adds all functions of a function group
References add(), function_pattern(), is_init(), m_spFunctionPattern, size(), and UG_THROW.
add_all()
void ug::FunctionGroup::add_all ()
selects all subsets in the order of the underlying pattern
References add(), is_init(), m_spFunctionPattern, and UG_THROW.
Referenced by ug::CreateFunctionIndexMapping(), and function_pattern().
clear()
void ug::FunctionGroup::clear () inline
clear all subsets
References m_vFunction, and sort().
Referenced by ug::CreateUnionOfFunctionGroups(), ug::DependentUserData< MathVector< TGridFunction::dim >, dim >::extract_fct_grp(), FunctionGroup(), and set_function_pattern().
contains() [1/2]
bool ug::FunctionGroup::contains (size_t uniqueID) const
returns true if unique id is contained in this group
References ug::find(), and m_vFunction.
Referenced by contains(), ug::CreateFunctionIndexMapping(), and unique_id().
contains() [2/2]
bool ug::FunctionGroup::contains (const FunctionGroup & fctGroup) const
returns true if all unique ids of another function group are contained
References contains(), and size().
dim() [1/2]
int ug::FunctionGroup::dim (size_t i) const
dimension of a function
Returns the dimension of a function. The dimension is defined to be the highest dimension of grid entity the function lives on
References is_init(), m_spFunctionPattern, m_vFunction, size(), and UG_THROW.
dim() [2/2]
int ug::FunctionGroup::dim () const
common dimension of all functions
Returns the commen dimension of all functions of the group. This dimension is defined to be the highest dimension of grid entity the functions live on
Returns
-1 if no common dimension available dim >= 0 common dimension
References is_init(), size(), and UG_THROW.
Referenced by unique_id().
empty()
bool ug::FunctionGroup::empty () const inline
returns if function group is empty
References m_vFunction.
function_pattern()
ConstSmartPtr<FunctionPattern> ug::FunctionGroup::function_pattern () const inline
get underlying function pattern
References add(), add_all(), m_spFunctionPattern, and name().
Referenced by add(), ug::CreateFunctionIndexMapping(), and ug::DependentUserData< MathVector< TGridFunction::dim >, dim >::extract_fct_grp().
is_init()
bool ug::FunctionGroup::is_init () const inline protected
returns if FunctionGroup is ready for use
References m_spFunctionPattern.
Referenced by add(), add_all(), dim(), local_finite_element_id(), name(), names(), and remove().
lfeid()
LFEID ug::FunctionGroup::lfeid (size_t i) const
returns the trial space of the discrete function fct
References local_finite_element_id().
Referenced by unique_id().
local_finite_element_id()
LFEID ug::FunctionGroup::local_finite_element_id (size_t i) const
returns the trial space of the discrete function fct
References is_init(), m_spFunctionPattern, m_vFunction, size(), and UG_THROW.
Referenced by ug::IElemDiscBase< TDomain >::check_setup(), lfeid(), and unique_id().
local_index()
size_t ug::FunctionGroup::local_index (size_t uniqueID) const
return index in Function group for a function
References m_vFunction, and UG_THROW.
Referenced by ug::CreateFunctionIndexMapping(), and unique_id().
name()
const char * ug::FunctionGroup::name (size_t i) const
returns the name of a function
References is_init(), m_spFunctionPattern, m_vFunction, size(), and UG_THROW.
Referenced by add(), function_pattern(), names(), and size().
names()
std::string ug::FunctionGroup::names () const
returns the comma-separted names of all functions
References is_init(), name(), size(), and UG_THROW.
Referenced by size().
operator[]()
size_t ug::FunctionGroup::operator[] (size_t i) const inline
returns unique function id of a function
References unique_id().
remove() [1/4]
void ug::FunctionGroup::remove (size_t fct)
removes a function by id from this group
References ug::find(), is_init(), m_spFunctionPattern, m_vFunction, ug::TrimString(), and UG_THROW.
Referenced by remove().
remove() [2/4]
void ug::FunctionGroup::remove (const char * name)
removes function with a given name from this group
References remove(), and ug::TokenizeString().
remove() [3/4]
void ug::FunctionGroup::remove (const std::string & name)
removes function with a given name from this group
remove() [4/4]
void ug::FunctionGroup::remove (const std::vector< std::string > & vName)
removes functions with a given names from this group
set_function_pattern()
void ug::FunctionGroup::set_function_pattern (ConstSmartPtr< FunctionPattern > spFuncPattern)
set underlying function pattern
References clear(), and m_spFunctionPattern.
Referenced by ug::CreateUnionOfFunctionGroups(), ug::UserDataInfo::set_function_pattern(), ug::DependentUserData< MathVector< TGridFunction::dim >, dim >::set_function_pattern(), and ug::IElemDiscBase< TDomain >::update_function_index_mapping().
size()
size_t ug::FunctionGroup::size () const inline
number of functions in this group
References m_vFunction, name(), and names().
Referenced by add(), ug::DirichletBoundary< TDomain, TAlgebra >::check_functions_and_subsets(), ug::IObstacleConstraint< TDomain, TAlgebra >::check_functions_and_subsets(), ug::IElemDiscBase< TDomain >::check_setup(), ug::CheckGFforNaN(), contains(), ug::CreateFunctionIndexMapping(), dim(), ug::DirichletBoundary< TDomain, TAlgebra >::extract_data(), ug::IObstacleConstraint< TDomain, TAlgebra >::extract_data(), ug::IntegrateDiscFlux(), local_finite_element_id(), name(), names(), ug::operator<<(), and unique_id().
sort()
void ug::FunctionGroup::sort ()
sorts the selected functions by increasing unique id
References m_vFunction.
Referenced by clear(), and ug::CreateUnionOfFunctionGroups().
unique_id()
size_t ug::FunctionGroup::unique_id (size_t i) const inline
returns unique function id of a function
References contains(), dim(), lfeid(), local_finite_element_id(), local_index(), m_vFunction, size(), and UG_ASSERT.
Referenced by operator[]().
Member Data Documentation
m_spFunctionPattern
ConstSmartPtr<FunctionPattern> ug::FunctionGroup::m_spFunctionPattern protected
underlying function pattern
Referenced by add(), add_all(), dim(), function_pattern(), is_init(), local_finite_element_id(), name(), remove(), and set_function_pattern().
m_vFunction
std::vector<size_t> ug::FunctionGroup::m_vFunction protected
vector holding all selected unique function ids
Referenced by add(), clear(), contains(), dim(), empty(), local_finite_element_id(), local_index(), name(), remove(), size(), sort(), and unique_id().
The documentation for this class was generated from the following files:
ugbase/lib_disc/common/function_group.h
ugbase/lib_disc/common/function_group.cpp