ug4: ug::DimCRFVGeometry< TDim, TWorldDim >::SCV Class Reference
ug::DimCRFVGeometry< TDim, TWorldDim >::SCV Class Reference
sub control volume structure
#include <fvcr_geom.h>
Public Member Functions
number detJ () const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_corner (size_t co) const
return global corner number i
const MathVector< worldDim > & global_grad (size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector () const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip () const
global integration point
const MathMatrix< worldDim, dim > & JTInv () const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector () const
vector of local gradients in ip point
const MathVector< dim > & local_ip () const
local integration point of scv
size_t node_id () const
node id that this scv is associated to
const MathVector< worldDim > & normal () const
normal on scvf (points direction "from"->"to"). Norm is equal to area
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shape functions
SCV ()
number shape (size_t sh) const
value of shape function i in integration point
const number * shape_vector () const
vector of shape functions in ip point
number volume () const
volume of scv
Static Public Attributes
static const size_t maxNumCo = 5
Number of corners of scv.
Private Attributes
number detj
MathMatrix< worldDim, dim > JtInv
size_t nodeID
MathVector< worldDim > Normal
int numCorners
size_t numSH
MathVector< worldDim > vGlobalGrad [maxNSH]
MathVector< dim > vGlobIP
MathVector< worldDim > vGloPos [maxNumCo]
MathVector< dim > vLocalGrad [maxNSH]
MathVector< dim > vLocIP
MathVector< dim > vLocPos [maxNumCo]
number Vol
number vShape [maxNSH]
Friends
class DimCRFVGeometry< dim, worldDim >
Detailed Description
template<int TDim, int TWorldDim = TDim>
class ug::DimCRFVGeometry< TDim, TWorldDim >::SCV
sub control volume structure
Constructor & Destructor Documentation
SCV()
template<int TDim, int TWorldDim = TDim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::SCV () inline
Member Function Documentation
detJ()
template<int TDim, int TWorldDim = TDim> number ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::detJ () const inline
Determinant of Jacobian in integration point.
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::detj.
global_corner()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_corner (size_t co) const inline
return global corner number i
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::num_corners(), UG_ASSERT, and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vGloPos.
global_grad()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_grad (size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::num_sh(), UG_ASSERT, and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vGlobalGrad.
global_grad_vector()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_grad_vector () const inline
vector of global gradients in ip point
global_ip()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_ip () const inline
global integration point
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vGlobIP.
JTInv()
template<int TDim, int TWorldDim = TDim> const MathMatrix<worldDim,dim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::JTInv () const inline
Transposed Inverse of Jacobian in integration point.
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::JtInv.
local_corner()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::local_corner (size_t co) const inline
return local corner number i
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::num_corners(), UG_ASSERT, and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vLocPos.
local_grad()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::local_grad (size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::num_sh(), UG_ASSERT, and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vLocalGrad.
local_grad_vector()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>* ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::local_grad_vector () const inline
vector of local gradients in ip point
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vLocalGrad.
local_ip()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::local_ip () const inline
local integration point of scv
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vLocIP.
node_id()
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::node_id () const inline
node id that this scv is associated to
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::nodeID.
normal()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::normal () const inline
normal on scvf (points direction "from"->"to"). Norm is equal to area
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::Normal.
num_corners()
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::num_corners () const inline
number of corners, that bound the scvf
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::numCorners.
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_corner(), and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::local_corner().
num_ip()
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::num_ip () const inline
number of integration points
References ug::DimCRFVGeometry< TDim, TWorldDim >::nip.
num_sh()
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::num_sh () const inline
number of shape functions
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::numSH.
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_grad(), and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::local_grad().
shape()
template<int TDim, int TWorldDim = TDim> number ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::shape (size_t sh) const inline
value of shape function i in integration point
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vShape.
shape_vector()
template<int TDim, int TWorldDim = TDim> const number* ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::shape_vector () const inline
vector of shape functions in ip point
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vShape.
volume()
template<int TDim, int TWorldDim = TDim> number ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::volume () const inline
volume of scv
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::Vol.
Friends And Related Function Documentation
DimCRFVGeometry< dim, worldDim >
template<int TDim, int TWorldDim = TDim> friend class DimCRFVGeometry< dim, worldDim > friend
Member Data Documentation
detj
template<int TDim, int TWorldDim = TDim> number ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::detj private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::detJ().
JtInv
template<int TDim, int TWorldDim = TDim> MathMatrix<worldDim,dim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::JtInv private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::JTInv().
maxNumCo
template<int TDim, int TWorldDim = TDim> const size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::maxNumCo = 5 static
Number of corners of scv.
nodeID
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::nodeID private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::node_id().
Normal
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::Normal private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::normal().
numCorners
template<int TDim, int TWorldDim = TDim> int ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::numCorners private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::num_corners().
numSH
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::numSH private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::num_sh().
vGlobalGrad
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vGlobalGrad[maxNSH] private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_grad().
vGlobIP
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vGlobIP private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_ip().
vGloPos
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vGloPos[maxNumCo] private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_corner().
vLocalGrad
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vLocalGrad[maxNSH] private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::local_grad(), and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::local_grad_vector().
vLocIP
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vLocIP private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::local_ip().
vLocPos
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vLocPos[maxNumCo] private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::local_corner().
Vol
template<int TDim, int TWorldDim = TDim> number ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::Vol private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::volume().
vShape
template<int TDim, int TWorldDim = TDim> number ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::vShape[maxNSH] private
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::shape(), and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::shape_vector().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fvcr_geom.h