ug4: ug::UserDataDistIntegrandSq< TData, TGridFunction > Class Template Reference
ug::UserDataDistIntegrandSq< TData, TGridFunction > Class Template Reference
For arbitrary UserData $f$ and grid functions u_1 and u_2, this class (should) define the integrand $ (f(u_1)- f(u_2))^2$.
#include <integrate.h>
Public Member Functions
template<int elemDim>
void evaluate (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pFineElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vFineLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP)
returns the values of the integrand for a bunch of ips
virtual void set_subset (int si)
sets subset
UserDataDistIntegrandSq (SmartPtr< UserData< TData, worldDim > > spData, TGridFunction &fineGridFct, size_t fineCmp, TGridFunction &coarseGridFct, size_t coarseCmp)
constructor (1st is fine grid function)
virtual ~UserDataDistIntegrandSq ()
Public Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, UserDataDistIntegrandSq< TData, TGridFunction > >
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)
Public Member Functions inherited from ug::IIntegrand< number, TWorldDim >
int subset () const
returns the subset
virtual ~IIntegrand ()
Static Public Attributes
static const int worldDim = TGridFunction::dim
world dimension of grid function
Static Public Attributes inherited from ug::StdIntegrand< number, TGridFunction::dim, UserDataDistIntegrandSq< TData, TGridFunction > >
static const int worldDim
world dimension
Static Public Attributes inherited from ug::IIntegrand< number, TWorldDim >
static const int worldDim
world dimension
Protected Member Functions
number inner_dist2 (const number &v1, const number &v2)
number inner_dist2 (const MathVector< worldDim > &v1, const MathVector< worldDim > &v2)
template<typename T >
number inner_dist2 (const T &d1, const T &d2)
number inner_prod (const number &d1, const number &d2)
number inner_prod (const MathVector< worldDim > &d1, const MathVector< worldDim > &d2)
template<typename T >
number inner_prod (const T &d1, const T &d2)
Protected Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, UserDataDistIntegrandSq< TData, TGridFunction > >
UserDataDistIntegrandSq< TData, TGridFunction > & getImpl ()
access to implementation
const UserDataDistIntegrandSq< TData, TGridFunction > & getImpl () const
const access to implementation
Protected Attributes
ScalarGridFunctionData< TGridFunction > m_coarseData
const int m_coarseTopLevel
ScalarGridFunctionData< TGridFunction > m_fineData
const int m_fineTopLevel
SmartPtr< UserData< TData, worldDim > > m_spData
SmartPtr< MultiGrid > m_spMG
multigrid
double m_time
Protected Attributes inherited from ug::IIntegrand< number, TWorldDim >
int m_si
subset
Additional Inherited Members
Public Types inherited from ug::StdIntegrand< number, TGridFunction::dim, UserDataDistIntegrandSq< TData, TGridFunction > >
typedef number data_type
data type
Public Types inherited from ug::IIntegrand< number, TWorldDim >
typedef number data_type
data type
Detailed Description
template<typename TData, typename TGridFunction>
class ug::UserDataDistIntegrandSq< TData, TGridFunction >
For arbitrary UserData $f$ and grid functions u_1 and u_2, this class (should) define the integrand $ (f(u_1)- f(u_2))^2$.
Constructor & Destructor Documentation
UserDataDistIntegrandSq()
template<typename TData , typename TGridFunction > ug::UserDataDistIntegrandSq< TData, TGridFunction >::UserDataDistIntegrandSq (SmartPtr< UserData< TData, worldDim > > spData, TGridFunction & fineGridFct, size_t fineCmp, TGridFunction & coarseGridFct, size_t coarseCmp) inline
constructor (1st is fine grid function)
References ug::ScalarGridFunctionData< TGridFunction >::domain(), SmartPtr< T, FreePolicy >::get(), and UG_THROW.
~UserDataDistIntegrandSq()
template<typename TData , typename TGridFunction > virtual ug::UserDataDistIntegrandSq< TData, TGridFunction >::~UserDataDistIntegrandSq () inline virtual
Member Function Documentation
evaluate()
template<typename TData , typename TGridFunction > template<int elemDim> void ug::UserDataDistIntegrandSq< TData, TGridFunction >::evaluate (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject * pFineElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vFineLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP) inline
returns the values of the integrand for a bunch of ips
Parameters
vValue[out] the value of the integrand at the ips
vGlobIP[in] global integration point positions
pElem[in] the element to integrate
vCornerCoords[in] corner coordinates of the element
vLocIP[in] local integration point positions
vJT[in] jacobian transposed at integration point
numIP[in] number of integration points
References ug::CollectCornerCoordinates(), ug::ScalarGridFunctionData< TGridFunction >::domain(), ug::GetLocalVector(), ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::ScalarGridFunctionData< TGridFunction >::grid_function(), ug::GridObject::reference_object_id(), ug::LocalVector::resize(), UG_CATCH_THROW, and ug::VecSet().
inner_dist2() [1/3]
template<typename TData , typename TGridFunction > number ug::UserDataDistIntegrandSq< TData, TGridFunction >::inner_dist2 (const number & v1, const number & v2) inline protected
inner_dist2() [2/3]
template<typename TData , typename TGridFunction > number ug::UserDataDistIntegrandSq< TData, TGridFunction >::inner_dist2 (const MathVector< worldDim > & v1, const MathVector< worldDim > & v2) inline protected
References ug::VecDistanceSq().
inner_dist2() [3/3]
template<typename TData , typename TGridFunction > template<typename T > number ug::UserDataDistIntegrandSq< TData, TGridFunction >::inner_dist2 (const T & d1, const T & d2) inline protected
References UG_ASSERT.
inner_prod() [1/3]
template<typename TData , typename TGridFunction > number ug::UserDataDistIntegrandSq< TData, TGridFunction >::inner_prod (const number & d1, const number & d2) inline protected
inner_prod() [2/3]
template<typename TData , typename TGridFunction > number ug::UserDataDistIntegrandSq< TData, TGridFunction >::inner_prod (const MathVector< worldDim > & d1, const MathVector< worldDim > & d2) inline protected
References ug::VecDot().
inner_prod() [3/3]
template<typename TData , typename TGridFunction > template<typename T > number ug::UserDataDistIntegrandSq< TData, TGridFunction >::inner_prod (const T & d1, const T & d2) inline protected
References UG_ASSERT.
set_subset()
template<typename TData , typename TGridFunction > virtual void ug::UserDataDistIntegrandSq< TData, TGridFunction >::set_subset (int si) inline virtual
sets subset
Reimplemented from ug::IIntegrand< number, TWorldDim >.
References ug::ScalarGridFunctionData< TGridFunction >::fct(), ug::ScalarGridFunctionData< TGridFunction >::is_def_in_subset(), ug::IIntegrand< TData, TWorldDim >::set_subset(), and UG_THROW.
Member Data Documentation
m_coarseData
template<typename TData , typename TGridFunction > ScalarGridFunctionData<TGridFunction> ug::UserDataDistIntegrandSq< TData, TGridFunction >::m_coarseData protected
m_coarseTopLevel
template<typename TData , typename TGridFunction > const int ug::UserDataDistIntegrandSq< TData, TGridFunction >::m_coarseTopLevel protected
m_fineData
template<typename TData , typename TGridFunction > ScalarGridFunctionData<TGridFunction> ug::UserDataDistIntegrandSq< TData, TGridFunction >::m_fineData protected
m_fineTopLevel
template<typename TData , typename TGridFunction > const int ug::UserDataDistIntegrandSq< TData, TGridFunction >::m_fineTopLevel protected
m_spData
template<typename TData , typename TGridFunction > SmartPtr<UserData<TData, worldDim> > ug::UserDataDistIntegrandSq< TData, TGridFunction >::m_spData protected
m_spMG
template<typename TData , typename TGridFunction > SmartPtr<MultiGrid> ug::UserDataDistIntegrandSq< TData, TGridFunction >::m_spMG protected
multigrid
m_time
template<typename TData , typename TGridFunction > double ug::UserDataDistIntegrandSq< TData, TGridFunction >::m_time protected
worldDim
template<typename TData , typename TGridFunction > const int ug::UserDataDistIntegrandSq< TData, TGridFunction >::worldDim = TGridFunction::dim static
world dimension of grid function
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/integrate.h