ug4: ug::IsRegularSurfaceElem Class Reference
ug::IsRegularSurfaceElem Class Reference
Returns true if an element is a regular surface element.
#include <parallel_callbacks.h>
Public Member Functions
IsRegularSurfaceElem (const DistributedGridManager &dgm)
bool operator() (Edge *e)
bool operator() (Face *f)
bool operator() (Vertex *v)
bool operator() (Volume *v)
Private Member Functions
template<class TElem >
bool is_ok (TElem *e)
Private Attributes
const DistributedGridManager & m_dgm
const MultiGrid * m_mg
Detailed Description
Returns true if an element is a regular surface element.
Regular surface elements are elements which lie on the surface and are not a ghost element. (Ghost are vertical masters, which do not lie in any other interface).
Constructor & Destructor Documentation
IsRegularSurfaceElem()
ug::IsRegularSurfaceElem::IsRegularSurfaceElem (const DistributedGridManager & dgm) inline
References m_mg, and UG_ASSERT.
Member Function Documentation
is_ok()
template<class TElem > bool ug::IsRegularSurfaceElem::is_ok (TElem * e) inline private
References ug::MultiGrid::has_children(), ug::DistributedGridManager::is_ghost(), m_dgm, and m_mg.
Referenced by operator()().
operator()() [1/4]
bool ug::IsRegularSurfaceElem::operator() (Edge * e) inline
References is_ok().
operator()() [2/4]
bool ug::IsRegularSurfaceElem::operator() (Face * f) inline
References is_ok().
operator()() [3/4]
bool ug::IsRegularSurfaceElem::operator() (Vertex * v) inline
References is_ok().
operator()() [4/4]
bool ug::IsRegularSurfaceElem::operator() (Volume * v) inline
References is_ok().
Member Data Documentation
m_dgm
const DistributedGridManager& ug::IsRegularSurfaceElem::m_dgm private
Referenced by is_ok().
m_mg
const MultiGrid* ug::IsRegularSurfaceElem::m_mg private
Referenced by is_ok(), and IsRegularSurfaceElem().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/util/parallel_callbacks.h