ug4: ug::SubdivRules_PLoop Class Reference
ug::SubdivRules_PLoop Class Reference
lib_grid » algorithms » refinement » subdivision
A singleton that stores all rules for a piecewise-loop subdivision surface.
#include <subdivision_rules_piecewise_loop.h>
Classes
struct NeighborInfo
Public Member Functions
number get_beta (size_t valency)
returns beta as it is used in the subdivision masks.
vector3 proj_crease_weights ()
number proj_inner_center_weight (size_t valence)
void proj_inner_crease_nbr_weights (number &centerWgtOut, number *nbrWgtsOut, NeighborInfo *nbrInfos, size_t numNbrs)
number proj_inner_nbr_weight (size_t valence)
vector3 ref_even_crease_weights ()
returns weights for center, nbr1 and nbr2.
number ref_even_inner_center_weight (size_t valence)
number ref_even_inner_nbr_weight (size_t valence)
vector2 ref_odd_crease_weights ()
vector4 ref_odd_inner_weights ()
vector4 ref_odd_inner_weights (size_t creaseValence)
weights of an odd vertex on an inner edge that is connected to a crease.
Static Public Member Functions
static SubdivRules_PLoop & inst ()
returns the only instance to this singleton.
Private Member Functions
number calculate_beta (size_t valency)
calculates beta as it is used in the subdivision masks.
size_t next_ind (size_t ind, size_t numInds)
returns the next index in a cyclic index set
SubdivRules_PLoop & operator= (const SubdivRules_PLoop &src)
private assignment operator prohibits assignment.
size_t prev_ind (size_t ind, size_t numInds)
returns the previous index in a cyclic index set
SubdivRules_PLoop ()
private constructor prohibits multiple instantiation.
SubdivRules_PLoop (const SubdivRules_PLoop &src)
private copy constructor prohibits copy-construction.
Private Attributes
std::vector< number > m_betas
Detailed Description
A singleton that stores all rules for a piecewise-loop subdivision surface.
Constructor & Destructor Documentation
ug::SubdivRules_PLoop::SubdivRules_PLoop () private
private constructor prohibits multiple instantiation.
Referenced by proj_inner_crease_nbr_weights().
ug::SubdivRules_PLoop::SubdivRules_PLoop (const SubdivRules_PLoop & src) private
private copy constructor prohibits copy-construction.
Member Function Documentation
number ug::SubdivRules_PLoop::calculate_beta (size_t valency) private
calculates beta as it is used in the subdivision masks.
References ug::PI.
Referenced by proj_inner_crease_nbr_weights().
number ug::SubdivRules_PLoop::get_beta (size_t valency)
returns beta as it is used in the subdivision masks.
performs a lookup if the valency is small enough. calculates a fresh beta else.
Referenced by proj_inner_center_weight(), proj_inner_crease_nbr_weights(), proj_inner_nbr_weight(), ref_even_inner_center_weight(), and ref_even_inner_nbr_weight().
static SubdivRules_PLoop& ug::SubdivRules_PLoop::inst () inline static
returns the only instance to this singleton.
Referenced by ug::MoveVertexToSubdivisionSurfacePosition(), ug::SubdivisionLoopBoundaryProjector< TAPosition >::new_vertex(), ug::SubdivisionLoopProjector< TAPosition >::new_vertex(), ug::ProjectToLimitPLoop(), and ug::ProjectToLimitSubdivBoundary().
size_t ug::SubdivRules_PLoop::next_ind (size_t ind, size_t numInds) inline private
returns the next index in a cyclic index set
Referenced by proj_inner_crease_nbr_weights().
SubdivRules_PLoop & ug::SubdivRules_PLoop::operator= (const SubdivRules_PLoop & src) private
private assignment operator prohibits assignment.
Referenced by proj_inner_crease_nbr_weights().
size_t ug::SubdivRules_PLoop::prev_ind (size_t ind, size_t numInds) inline private
returns the previous index in a cyclic index set
Referenced by proj_inner_crease_nbr_weights().
vector3 ug::SubdivRules_PLoop::proj_crease_weights () inline
Referenced by ug::ProjectToLimitPLoop(), and ug::ProjectToLimitSubdivBoundary().
number ug::SubdivRules_PLoop::proj_inner_center_weight (size_t valence) inline
References get_beta().
Referenced by proj_inner_crease_nbr_weights(), and ug::ProjectToLimitPLoop().
void ug::SubdivRules_PLoop::proj_inner_crease_nbr_weights (number & centerWgtOut, number * nbrWgtsOut, NeighborInfo * nbrInfos, size_t numNbrs) inline
nbrInfos have to be specified in clockwise or counter-clockwise order.
References calculate_beta(), ug::SubdivRules_PLoop::NeighborInfo::creaseValence, get_beta(), next_ind(), operator=(), prev_ind(), proj_inner_center_weight(), proj_inner_nbr_weight(), ref_even_inner_center_weight(), ref_even_inner_nbr_weight(), ref_odd_inner_weights(), and SubdivRules_PLoop().
Referenced by ug::ProjectToLimitPLoop().
number ug::SubdivRules_PLoop::proj_inner_nbr_weight (size_t valence) inline
References get_beta().
Referenced by proj_inner_crease_nbr_weights(), and ug::ProjectToLimitPLoop().
vector3 ug::SubdivRules_PLoop::ref_even_crease_weights () inline
returns weights for center, nbr1 and nbr2.
Referenced by ug::SubdivisionLoopBoundaryProjector< TAPosition >::new_vertex(), and ug::SubdivisionLoopProjector< TAPosition >::new_vertex().
number ug::SubdivRules_PLoop::ref_even_inner_center_weight (size_t valence) inline
References get_beta().
Referenced by ug::MoveVertexToSubdivisionSurfacePosition(), ug::SubdivisionLoopProjector< TAPosition >::new_vertex(), and proj_inner_crease_nbr_weights().
number ug::SubdivRules_PLoop::ref_even_inner_nbr_weight (size_t valence) inline
References get_beta().
Referenced by ug::MoveVertexToSubdivisionSurfacePosition(), ug::SubdivisionLoopProjector< TAPosition >::new_vertex(), and proj_inner_crease_nbr_weights().
vector2 ug::SubdivRules_PLoop::ref_odd_crease_weights () inline
Referenced by ug::SubdivisionLoopBoundaryProjector< TAPosition >::new_vertex(), and ug::SubdivisionLoopProjector< TAPosition >::new_vertex().
vector4 ug::SubdivRules_PLoop::ref_odd_inner_weights () inline
Referenced by ug::MoveVertexToSubdivisionSurfacePosition(), ug::SubdivisionLoopProjector< TAPosition >::new_vertex(), proj_inner_crease_nbr_weights(), and ref_odd_inner_weights().
vector4 ug::SubdivRules_PLoop::ref_odd_inner_weights (size_t creaseValence) inline
weights of an odd vertex on an inner edge that is connected to a crease.
The weight for the vertex on the crease is in v.x(), the inner edge vertex in v.y() and the two indirectly connected vertex weights are in v.z() and v.w. creaseValence specifies the number of associated edges of the crease vertex.
Rules are taken from: "Piecewise Smooth Subdivision Surfaces with Normal Control", H. Biermann, Adi Levin, Denis Zorin.
References ug::PI, and ref_odd_inner_weights().
Member Data Documentation
std::vector<number> ug::SubdivRules_PLoop::m_betas private
The documentation for this class was generated from the following files:
ugbase/lib_grid/algorithms/subdivision/subdivision_rules_piecewise_loop.h
ugbase/lib_grid/algorithms/subdivision/subdivision_rules_piecewise_loop.cpp