ug4: ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment > Class Template Reference
ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment > Class Template Reference
lib_grid » algorithms » serialization
Serialization callback for grid attachments.
#include <serialization.h>
Public Member Functions
GeomObjAttachmentSerializer (Grid &g, TAttachment a)
virtual void read_data (BinaryBuffer &in, TGeomObj *o)
read data associated with the given object. Pure virtual.
virtual void write_data (BinaryBuffer &out, TGeomObj *o) const
write data associated with the given object. Pure virtual.
virtual ~GeomObjAttachmentSerializer ()
Public Member Functions inherited from ug::GeomObjDataSerializer< TGeomObj >
virtual void deserialization_done ()
this method will be called after read_info has been called for all geometric objects.
virtual void deserialization_starts ()
this method is called after read_info has been called for all geometric objects.
virtual void read_info (BinaryBuffer &in)
Read the info written during write_info here. Default: empty implementation.
virtual void write_info (BinaryBuffer &out) const
can be used to write arbitrary info to the file.
virtual ~GeomObjDataSerializer ()
Static Public Member Functions
static SmartPtr< GeomObjDataSerializer< TGeomObj > > create (Grid &g, TAttachment a)
Private Attributes
Grid::AttachmentAccessor< TGeomObj, TAttachment > m_aa
Detailed Description
template<class TGeomObj, class TAttachment>
class ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >
Serialization callback for grid attachments.
template class where TGeomObj should be one of the following types: Vertex, Edge, Face, Volume.
Note that the attachment is automatically attached, if not yet present.
Constructor & Destructor Documentation
GeomObjAttachmentSerializer()
template<class TGeomObj , class TAttachment > ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::GeomObjAttachmentSerializer (Grid & g, TAttachment a) inline
Referenced by ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::create().
~GeomObjAttachmentSerializer()
template<class TGeomObj , class TAttachment > virtual ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::~GeomObjAttachmentSerializer () inline virtual
Member Function Documentation
create()
template<class TGeomObj , class TAttachment > static SmartPtr<GeomObjDataSerializer<TGeomObj> > ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::create (Grid & g, TAttachment a) inline static
References ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::GeomObjAttachmentSerializer().
Referenced by ug::DistributeDomain().
read_data()
template<class TGeomObj , class TAttachment > virtual void ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::read_data (BinaryBuffer & in, TGeomObj * o) inline virtual
read data associated with the given object. Pure virtual.
Implements ug::GeomObjDataSerializer< TGeomObj >.
References ug::Deserialize(), and ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::m_aa.
write_data()
template<class TGeomObj , class TAttachment > virtual void ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::write_data (BinaryBuffer & out, TGeomObj * o) const inline virtual
write data associated with the given object. Pure virtual.
Implements ug::GeomObjDataSerializer< TGeomObj >.
References ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::m_aa, and ug::Serialize().
Member Data Documentation
m_aa
template<class TGeomObj , class TAttachment > Grid::AttachmentAccessor<TGeomObj, TAttachment> ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::m_aa private
Referenced by ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::read_data(), and ug::GeomObjAttachmentSerializer< TGeomObj, TAttachment >::write_data().
The documentation for this class was generated from the following file:
ugbase/lib_grid/algorithms/serialization.h