ug4: ug::SurfaceView::SurfaceViewElementIterator< TElem > Class Template Reference
ug::SurfaceView::SurfaceViewElementIterator< TElem > Class Template Reference
Iterator to traverse the surface of a multi-grid hierarchy.
#include <surface_view.h>
Public Member Functions
bool operator!= (const this_type &iter) const
TValue operator* ()
this_type operator++ ()
this_type operator++ (int unused)
bool operator== (const this_type &iter) const
SurfaceViewElementIterator ()
Private Types
typedef SurfaceViewElementIterator< TElem > this_type
typedef TElem * TValue
Private Member Functions
TValue dereference () const
dereference
bool equal (SurfaceViewElementIterator< TElem > const &other) const
returns if this iterator equals another
void increment ()
returns next valid iterator
bool increment_section ()
returns begin-iterator of next non-empty section, returns false if not available
template<class TGeomObj >
bool is_contained (TGeomObj *obj) const
returns if valid element, i.e. contained in iterator loop
SurfaceViewElementIterator (bool start, SurfaceView *surfView, const GridLevel &gl, SurfaceState validStates, int si=-1)
Private Attributes
geometry_traits< TElem >::iterator m_elemIter
int m_fromSI
GridLevel m_gl
geometry_traits< TElem >::iterator m_iterEndSection
int m_lvl
SurfaceView * m_pSurfView
int m_si
int m_topLvl
int m_toSI
SurfaceState m_validStates
Friends
class ConstSurfaceViewElementIterator< TElem >
class SurfaceView
Detailed Description
template<class TElem>
class ug::SurfaceView::SurfaceViewElementIterator< TElem >
Iterator to traverse the surface of a multi-grid hierarchy.
Member Typedef Documentation
template<class TElem> typedef SurfaceViewElementIterator<TElem> ug::SurfaceView::SurfaceViewElementIterator< TElem >::this_type private
template<class TElem> typedef TElem* ug::SurfaceView::SurfaceViewElementIterator< TElem >::TValue private
Constructor & Destructor Documentation
template<class TElem > ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator ()
References ug::SurfaceView::SurfaceViewElementIterator< TElem >::equal().
Referenced by ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator().
template<class TElem > ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator (bool start, SurfaceView * surfView, const GridLevel & gl, SurfaceState validStates, int si = -1) private
References ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::is_contained(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_elemIter, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_iterEndSection, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_lvl, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_si, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_topLvl, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_toSI, ug::SurfaceView::subset_handler(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator(), and UG_ASSERT.
Member Function Documentation
template<class TElem > SurfaceView::SurfaceViewElementIterator< TElem >::TValue ug::SurfaceView::SurfaceViewElementIterator< TElem >::dereference () const inline private
dereference
References ug::SurfaceView::SurfaceViewElementIterator< TElem >::is_contained(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_elemIter.
Referenced by ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator*(), and ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::operator*().
template<class TElem> bool ug::SurfaceView::SurfaceViewElementIterator< TElem >::equal (SurfaceView::SurfaceViewElementIterator< TElem > const & other) const inline private
returns if this iterator equals another
References ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_elemIter.
Referenced by ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator!=(), ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::operator!=(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator*(), ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::operator*(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator==(), ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::operator==(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator().
template<class TElem > void ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment () private
returns next valid iterator
References ug::SurfaceView::SurfaceViewElementIterator< TElem >::dereference(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::is_contained(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_elemIter, and ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_iterEndSection.
Referenced by ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator*(), ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::operator*(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator++(), ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::operator++(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator().
template<class TElem > bool ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section () private
returns begin-iterator of next non-empty section, returns false if not available
References ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_elemIter, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_fromSI, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_iterEndSection, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_lvl, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_pSurfView, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_si, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_topLvl, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_toSI, and ug::SurfaceView::subset_handler().
Referenced by ug::SurfaceView::SurfaceViewElementIterator< TElem >::equal(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator*(), ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::operator*(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator().
template<class TElem > template<class TGeomObj > bool ug::SurfaceView::SurfaceViewElementIterator< TElem >::is_contained (TGeomObj * obj) const inline private
returns if valid element, i.e. contained in iterator loop
References ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::ConstSurfaceViewElementIterator(), ug::Flag< TEnum, TStorageType, defaultValue >::contains(), ug::GridLevel::ghosts(), ug::SurfaceView::is_ghost(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_gl, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_lvl, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_pSurfView, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_topLvl, ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_validStates, ug::SurfaceView::MG_SHADOW, ug::SurfaceView::MG_SURFACE_PURE, ug::Flag< TEnum, TStorageType, defaultValue >::partially_contains(), ug::SurfaceView::surface_state(), and ug::SurfaceView::TREAT_TOP_LVL_SHADOWS_AS_SURFACE_PURE.
Referenced by ug::SurfaceView::SurfaceViewElementIterator< TElem >::dereference(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator*(), ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::operator*(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator().
template<class TElem> bool ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator!= (const this_type & iter) const inline
References ug::SurfaceView::SurfaceViewElementIterator< TElem >::equal().
template<class TElem> TValue ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator* () inline
References ug::SurfaceView::SurfaceViewElementIterator< TElem >::dereference(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::equal(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::is_contained().
template<class TElem> this_type ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator++ () inline
References ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment().
template<class TElem> this_type ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator++ (int unused) inline
References ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment().
template<class TElem> bool ug::SurfaceView::SurfaceViewElementIterator< TElem >::operator== (const this_type & iter) const inline
References ug::SurfaceView::SurfaceViewElementIterator< TElem >::equal().
Friends And Related Function Documentation
template<class TElem> friend class ConstSurfaceViewElementIterator< TElem > friend
template<class TElem> friend class SurfaceView friend
Member Data Documentation
template<class TElem> geometry_traits<TElem>::iterator ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_elemIter private
Referenced by ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::ConstSurfaceViewElementIterator(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::dereference(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::equal(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator().
template<class TElem> int ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_fromSI private
Referenced by ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::ConstSurfaceViewElementIterator(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section().
template<class TElem> GridLevel ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_gl private
Referenced by ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::ConstSurfaceViewElementIterator(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::is_contained().
template<class TElem> geometry_traits<TElem>::iterator ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_iterEndSection private
Referenced by ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::ConstSurfaceViewElementIterator(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator().
template<class TElem> int ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_lvl private
Referenced by ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::ConstSurfaceViewElementIterator(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::is_contained(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator().
template<class TElem> SurfaceView* ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_pSurfView private
Referenced by ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::ConstSurfaceViewElementIterator(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::is_contained().
template<class TElem> int ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_si private
Referenced by ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::ConstSurfaceViewElementIterator(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator().
template<class TElem> int ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_topLvl private
Referenced by ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::ConstSurfaceViewElementIterator(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::is_contained(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator().
template<class TElem> int ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_toSI private
Referenced by ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::ConstSurfaceViewElementIterator(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::increment_section(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::SurfaceViewElementIterator().
template<class TElem> SurfaceState ug::SurfaceView::SurfaceViewElementIterator< TElem >::m_validStates private
Referenced by ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::ConstSurfaceViewElementIterator(), and ug::SurfaceView::SurfaceViewElementIterator< TElem >::is_contained().
The documentation for this class was generated from the following files:
ugbase/lib_grid/tools/surface_view.h
ugbase/lib_grid/tools/surface_view_impl.hpp