ug4: ug::LagrangeLDS< TRefElem > Class Template Reference
ug::LagrangeLDS< TRefElem > Class Template Reference
Lagrange DoF Set.
#include <lagrange_local_dof.h>
Public Member Functions
bool exact_position_available () const
returns if the local dof position are exact
LagrangeLDS (size_t order=1)
constructor
const LocalDoF & local_dof (size_t dof) const
returns the dof storage
size_t num_dof () const
returns the total number of DoFs on the finite element
size_t num_dof (ReferenceObjectID roid) const
returns the number of DoFs on a sub-geometric object type
ReferenceObjectID roid () const
returns the type of reference element
void set_order (size_t order)
sets the order
Public Member Functions inherited from ug::LocalDoFSet
int dim () const
returns the reference dimension
size_t num_dof (int d, size_t id) const
returns the number of DoFs on a sub-geometric object of dim and id
bool operator!= (const LocalDoFSet &v) const
inequality check
bool operator== (const LocalDoFSet &v) const
equality check
virtual ~LocalDoFSet ()
virtual destructor
size_t num_dof () const
virtual size_t num_sh () const
Protected Attributes
std::vector< LocalDoF > m_vLocalDoF
association to geom obj
size_t p
order
Detailed Description
template<typename TRefElem>
class ug::LagrangeLDS< TRefElem >
Lagrange DoF Set.
Constructor & Destructor Documentation
LagrangeLDS()
template<typename TRefElem > ug::LagrangeLDS< TRefElem >::LagrangeLDS (size_t order = 1)
constructor
Member Function Documentation
exact_position_available()
template<typename TRefElem > bool ug::LagrangeLDS< TRefElem >::exact_position_available () const inline
returns if the local dof position are exact
local_dof()
template<typename TRefElem > const LocalDoF& ug::LagrangeLDS< TRefElem >::local_dof (size_t dof) const inline virtual
returns the dof storage
Implements ug::LocalDoFSet.
References ug::LagrangeLDS< TRefElem >::m_vLocalDoF.
num_dof() [1/2]
template<typename TRefElem > size_t ug::LagrangeLDS< TRefElem >::num_dof () const inline
returns the total number of DoFs on the finite element
References ug::LagrangeLDS< TRefElem >::m_vLocalDoF.
num_dof() [2/2]
template<typename TRefElem > size_t ug::LagrangeLDS< TRefElem >::num_dof (ReferenceObjectID roid) const virtual
returns the number of DoFs on a sub-geometric object type
Implements ug::LocalDoFSet.
References ug::LagrangeNumDoFOnSub(), and p.
roid()
template<typename TRefElem > ReferenceObjectID ug::LagrangeLDS< TRefElem >::roid () const inline virtual
returns the type of reference element
Implements ug::LocalDoFSet.
set_order()
template<typename TRefElem > void ug::LagrangeLDS< TRefElem >::set_order (size_t order)
sets the order
References p, and ug::SetLagrangeLocalDoFs().
Referenced by ug::FlexLagrangeLSFS< ReferenceEdge >::set_order(), ug::FlexLagrangeLSFS< ReferenceTriangle >::set_order(), ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::set_order(), ug::FlexLagrangeLSFS< ReferenceTetrahedron >::set_order(), ug::FlexLagrangeLSFS< ReferencePrism >::set_order(), and ug::FlexLagrangeLSFS< ReferenceHexahedron >::set_order().
Member Data Documentation
m_vLocalDoF
template<typename TRefElem > std::vector<LocalDoF> ug::LagrangeLDS< TRefElem >::m_vLocalDoF protected
association to geom obj
Referenced by ug::LagrangeLDS< TRefElem >::local_dof(), and ug::LagrangeLDS< TRefElem >::num_dof().
p
template<typename TRefElem > size_t ug::LagrangeLDS< TRefElem >::p protected
order
The documentation for this class was generated from the following files:
ugbase/lib_disc/local_finite_element/lagrange/lagrange_local_dof.h
ugbase/lib_disc/local_finite_element/lagrange/lagrange_local_dof.cpp