ug4: ug::node_tree::CollisionTreeRootNode Class Reference
ug::node_tree::CollisionTreeRootNode Class Reference
A group node featuring a bounding box and a set of points.
#include <collision_tree_root_node.h>
Public Member Functions
virtual void add_points (vector3 *pPoints, int numPoints)
virtual void clear_points ()
virtual const vector3 & get_point (int index) const
virtual const vector3 * get_points () const
virtual int num_points ()
virtual ~CollisionTreeRootNode ()
Public Member Functions inherited from ug::node_tree::BoxedGroupNode
virtual const vector3 & max_corner () const
virtual const vector3 & min_corner () const
virtual void set_box (const vector3 &minCorner, const vector3 &maxCorner)
virtual ~BoxedGroupNode ()
Public Member Functions inherited from ug::node_tree::GroupNode
virtual void add_child (SPNode node)
virtual void clear ()
virtual SPNode get_child (int index)
virtual int num_children ()
virtual void remove_child (SPNode node)
virtual ~GroupNode ()
Public Member Functions inherited from ug::node_tree::Node
virtual ~Node ()
Public Member Functions inherited from ug::node_tree::Object
unsigned int getObjectCode ()
virtual ~Object ()
Static Public Member Functions
static SPCollisionTreeRootNode create ()
Static Public Member Functions inherited from ug::node_tree::BoxedGroupNode
static SPBoxedGroupNode create ()
Static Public Member Functions inherited from ug::node_tree::GroupNode
static SPGroupNode create ()
Protected Types
typedef std::vector< vector3 > PointVec
Protected Member Functions
CollisionTreeRootNode ()
Protected Member Functions inherited from ug::node_tree::BoxedGroupNode
BoxedGroupNode ()
Protected Member Functions inherited from ug::node_tree::GroupNode
GroupNode ()
Protected Member Functions inherited from ug::node_tree::Node
Node ()
Protected Member Functions inherited from ug::node_tree::Object
Object ()
Object (const Object &obj)
Protected Attributes
PointVec m_vPoints
Protected Attributes inherited from ug::node_tree::BoxedGroupNode
vector3 m_vMax
vector3 m_vMin
Protected Attributes inherited from ug::node_tree::GroupNode
std::vector< SPNode > vChildren
Protected Attributes inherited from ug::node_tree::Object
unsigned int m_objectCode
Detailed Description
A group node featuring a bounding box and a set of points.
Points are indexed by the subsidiary leaf elements.
Member Typedef Documentation
PointVec
typedef std::vector<vector3> ug::node_tree::CollisionTreeRootNode::PointVec protected
Constructor & Destructor Documentation
~CollisionTreeRootNode()
ug::node_tree::CollisionTreeRootNode::~CollisionTreeRootNode () virtual
CollisionTreeRootNode()
ug::node_tree::CollisionTreeRootNode::CollisionTreeRootNode () protected
Referenced by create().
Member Function Documentation
add_points()
void ug::node_tree::CollisionTreeRootNode::add_points (vector3 * pPoints, int numPoints) virtual
References m_vPoints.
clear_points()
void ug::node_tree::CollisionTreeRootNode::clear_points () virtual
References m_vPoints.
create()
SPCollisionTreeRootNode ug::node_tree::CollisionTreeRootNode::create () static
References CollisionTreeRootNode(), ug::node_tree::Object::m_objectCode, and ug::node_tree::OC_COLLISION_TREE_ROOT_NODE.
get_point()
const vector3 & ug::node_tree::CollisionTreeRootNode::get_point (int index) const virtual
References m_vPoints.
get_points()
const vector3 * ug::node_tree::CollisionTreeRootNode::get_points () const virtual
References m_vPoints.
Referenced by ug::node_tree::Traverser_ProjectPoint::handle_collision_edges(), ug::node_tree::Traverser_IntersectFaces::handle_collision_triangles(), and ug::node_tree::Traverser_ProjectPoint::handle_collision_triangles().
num_points()
int ug::node_tree::CollisionTreeRootNode::num_points () virtual
References m_vPoints.
Member Data Documentation
m_vPoints
PointVec ug::node_tree::CollisionTreeRootNode::m_vPoints protected
Referenced by add_points(), clear_points(), get_point(), get_points(), and num_points().
The documentation for this class was generated from the following files:
ugbase/common/node_tree/collision_tree_root_node.h
ugbase/common/node_tree/collision_tree_root_node.cpp