ug4: ug::GridSubsetHandler Class Reference
ug::GridSubsetHandler Class Reference
lib_grid » grid-tools
Partitions elements of a grid into several subsets.
#include <subset_handler_grid.h>
Classes
struct Subset
Public Member Functions
void assign_grid (Grid &grid)
void assign_grid (Grid *grid)
void assign_subset (Edge *elem, int subsetIndex)
assigns an edge to a subset.
virtual void assign_subset (Edge *elem, int subsetIndex)=0
void assign_subset (Face *elem, int subsetIndex)
assigns a face to a subset.
virtual void assign_subset (Face *elem, int subsetIndex)=0
virtual void assign_subset (GridObject *elem, int subsetIndex)
template<class TIterator >
void assign_subset (TIterator iterBegin, TIterator iterEnd, int subsetIndex)
void assign_subset (Vertex *elem, int subsetIndex)
assigns a vertex to a subset.
virtual void assign_subset (Vertex *elem, int subsetIndex)=0
void assign_subset (Volume *elem, int subsetIndex)
assigns a volume to a subset.
virtual void assign_subset (Volume *elem, int subsetIndex)=0
template<class TElem >
geometry_traits< TElem >::iterator begin (int subsetIndex)
returns the begin-iterator for the elements of type TElem in the given subset.
template<class TElem >
geometry_traits< TElem >::const_iterator begin (int subsetIndex) const
returns the begin-iterator for the elements of type TElem in the given subset.
template<class TElem >
geometry_traits< TElem >::const_iterator begin (int subsetIndex, size_t) const
returns the begin-iterator for the elements of type TElem in the given subset.
template<class TElem >
void clear_subset_elements (int subsetIndex)
removes all elements of type TElem from the specified subset.
virtual bool contains_edges (int subsetIndex) const
returns true if the subset contains edges
virtual bool contains_faces (int subsetIndex) const
returns true if the subset contains faces
virtual bool contains_vertices (int subsetIndex) const
collects all vertices that are in the given subset.
virtual bool contains_volumes (int subsetIndex) const
returns true if the subset contains volumes
template<class TElem >
bool empty () const
returns true if the subset-handler contains no elements of the given type.
bool empty () const
returns true if the subset-handler contains no elements at all.
template<class TElem >
bool empty (int subsetIndex) const
bool empty (int subsetIndex) const
returns true if the subset-handler contains no elements at all.
template<class TElem >
geometry_traits< TElem >::iterator end (int subsetIndex)
returns the end-iterator for the elements of type TElem in the given subset.
template<class TElem >
geometry_traits< TElem >::const_iterator end (int subsetIndex) const
returns the end-iterator for the elements of type TElem in the given subset.
template<class TElem >
geometry_traits< TElem >::const_iterator end (int subsetIndex, size_t) const
returns the end-iterator for the elements of type TElem in the given subset.
GridObjectCollection get_grid_objects () const
virtual GridObjectCollection get_grid_objects_in_subset (int subsetIndex) const
Returns the geometric object collection for the given subset.
virtual void grid_to_be_destroyed (Grid *grid)
perform cleanup
GridSubsetHandler (const GridSubsetHandler &sh)
GridSubsetHandler (Grid &grid, uint supportedElements=SHE_ALL)
GridSubsetHandler (uint supportedElements=SHE_ALL)
template<class TElem >
uint num () const
returns the total number of elements
template<class TElem >
uint num (int subsetIndex) const
returns the number of elements in the given subset
template<class TElem >
uint num (int subsetIndex, size_t) const
returns the number of elements in the given subset
template<class TElem >
uint num_elements (int subsetIndex) const
returns the number of elements in the given subset
template<class TElem >
uint num_elements (int subsetIndex, size_t) const
returns the number of elements in the given subset
uint num_levels () const
returns number of levels (always 1)
GridSubsetHandler & operator= (const GridSubsetHandler &sh)
GridSubsetHandler & operator= (const ISubsetHandler &sh)
template<class TElem >
bool perform_self_tests ()
only for debug purposes
~GridSubsetHandler ()
Public Member Functions inherited from ug::ISubsetHandler
virtual void assign_subset (GridObject *elem, int subsetIndex)
template<class TIterator >
void assign_subset (TIterator iterBegin, TIterator iterEnd, int subsetIndex)
void clear ()
void clear_subset (int subsetIndex)
void clear_subsets ()
void disable_element_support (uint shElements)
disable support for element-types.
virtual void edge_created (Grid *grid, Edge *e, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void edge_to_be_erased (Grid *grid, Edge *e, Edge *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void edges_to_be_merged (Grid *grid, Edge *target, Edge *elem1, Edge *elem2)
Notified when two elements of the same type are going to be merged.
bool elements_are_supported (uint shElements) const
returns true if the given element-types are supported.
virtual void elements_to_be_cleared (Grid *grid)
void enable_element_support (uint shElements)
enable support for element-types. Does not invalidate previous settings.
void enable_strict_inheritance (bool bEnable)
void enable_subset_inheritance (bool bEnable)
void erase_subset (int subsetIndex)
erases the subset at the given index. Assigns -1 to all entries. Moves all other subsets 1 index up.
virtual void face_created (Grid *grid, Face *f, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void face_to_be_erased (Grid *grid, Face *f, Face *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void faces_to_be_merged (Grid *grid, Face *target, Face *elem1, Face *elem2)
Notified when two elements of the same type are going to be merged.
int get_default_subset_index ()
int get_subset_index (const char *name) const
returns the index of the first subset with the given name.
int get_subset_index (Edge *elem) const
int get_subset_index (Face *elem) const
int get_subset_index (GridObject *elem) const
int get_subset_index (Vertex *elem) const
int get_subset_index (Volume *elem) const
const char * get_subset_name (int subsetIndex) const
returns the name of a subset
Grid * grid () const
returns a pointer to the grid on which the subset-handler works.
void insert_subset (int subsetIndex)
inserts a subset at the given index. Moves all other subsets 1 index higher.
ISubsetHandler (Grid &grid, uint supportedElements=SHE_ALL)
pass a grid and an or-combination of SubsetHandlerElements to supportedElements.
ISubsetHandler (uint supportedElements=SHE_ALL)
pass an or-combination of SubsetHandlerElements to supportedElements.
void join_subsets (int targetSub, int sub1, int sub2, bool eraseUnusedSubs)
Joins two subsets into a new one. Optionally erases the old subsets, if they are no longer used.
void move_subset (int indexFrom, int indexTo)
Moves the subset from index From to index To. Moves all subsets between indexFrom+1 and indexTo in the opposite direction.
int num_subsets () const
returns the number of subset-infos (return value is int, since SubsetIndices are of type int)
ISubsetHandler & operator= (const ISubsetHandler &sh)
assigns subsets based on the subsets in the given subset-handler
void set_default_subset_index (int subsetIndex)
void set_default_subset_info (const SubsetInfo &defSI)
sets the default subset-info. Used when initializing new subset-infos.
void set_subset_info (int subsetIndex, const SubsetInfo &subsetInfo)
void set_subset_name (const char *name, int subsetIndex)
sets the name of a subset
void set_supported_elements (uint shElements)
set the type of elements that shall be handled by the SubsetHandler.
bool strict_inheritance_enabled ()
SubsetInfo & subset_info (int subsetIndex)
const SubsetInfo & subset_info (int subsetIndex) const
bool subset_inheritance_enabled ()
void subset_required (int index)
if the subset with the given index does not yet exist, it will be created.
void subset_required (int index) const
throws an error if the given index is equal or higher than num_subsets.
void swap_subsets (int subsetIndex1, int subsetIndex2)
Swaps the given subsets,.
virtual void vertex_created (Grid *grid, Vertex *vrt, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void vertex_to_be_erased (Grid *grid, Vertex *vrt, Vertex *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void vertices_to_be_merged (Grid *grid, Vertex *target, Vertex *elem1, Vertex *elem2)
Notified when two elements of the same type are going to be merged.
virtual void volume_created (Grid *grid, Volume *vol, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void volume_to_be_erased (Grid *grid, Volume *vol, Volume *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void volumes_to_be_merged (Grid *grid, Volume *target, Volume *elem1, Volume *elem2)
Notified when two elements of the same type are going to be merged.
virtual ~ISubsetHandler ()
Public Member Functions inherited from ug::GridObserver
virtual ~GridObserver ()
Protected Types
typedef Grid::traits< Edge >::AttachedElementList AttachedEdgeList
typedef Grid::traits< Face >::AttachedElementList AttachedFaceList
typedef Grid::traits< Vertex >::AttachedElementList AttachedVertexList
enable subset-attachment support
typedef Grid::traits< Volume >::AttachedElementList AttachedVolumeList
typedef Grid::traits< Edge >::SectionContainer EdgeSectionContainer
typedef Grid::traits< Face >::SectionContainer FaceSectionContainer
typedef std::vector< Subset * > SubsetVec
typedef Grid::traits< Vertex >::SectionContainer VertexSectionContainer
typedef Grid::traits< Volume >::SectionContainer VolumeSectionContainer
Protected Types inherited from ug::ISubsetHandler
typedef AInt ASubsetIndex
typedef Grid::traits< Edge >::AttachedElementList AttachedEdgeList
typedef Grid::traits< Face >::AttachedElementList AttachedFaceList
typedef Grid::traits< Vertex >::AttachedElementList AttachedVertexList
enable subset-attachment support
typedef Grid::traits< Volume >::AttachedElementList AttachedVolumeList
typedef Grid::traits< Edge >::SectionContainer EdgeSectionContainer
typedef Grid::traits< Face >::SectionContainer FaceSectionContainer
typedef std::vector< SubsetInfo > SubsetInfoVec
typedef Grid::traits< Vertex >::SectionContainer VertexSectionContainer
typedef Grid::traits< Volume >::SectionContainer VolumeSectionContainer
Protected Member Functions
void add_required_subset_lists (int maxIndex)
add a subset
template<class TElem >
void assign_subset_impl (TElem *elem, int subsetIndex)
this method is called by ISubsetHandler when attachment_support has been enabled.
template<class TElem >
void change_elem_subset_indices (int indOld, int indNew)
helper for change_subset_indices
virtual void change_subset_indices (int indOld, int indNew)
changes the subset-indices of all elements int the subset.
void cleanup ()
helper for collect_subset_elements
virtual void clear_subset_lists (int index)
clears the element lists in the given subset. Does not alter any indices.
void detach_data ()
detaches all attached data.
virtual void erase_subset_lists ()
erases the subsets. Doesn't alter any indices.
void erase_subset_lists (int index)
erases the subset but does not touch the subset-indices.
void erase_subset_lists_impl ()
non-virtual implementation of erase_subset_lists. Callable from destructor
void join_subset_lists (int target, int src1, int src2)
join the subset-lists but do not touch the subset-indices.
void move_subset_lists (int indexFrom, int indexTo)
moves the subset but does not touch the subset-indices.
uint num_subsets_in_list () const
returns the number of subsets in the local list
template<class TElem >
Grid::traits< TElem >::SectionContainer & section_container (int si)
returns the section container for the given type, subset and level
template<class TElem >
const Grid::traits< TElem >::SectionContainer & section_container (int si) const
returns the const section container for the given type, subset and level
void swap_subset_lists (int ind1, int ind2)
swaps the subsets but does not touch the subset-indices.
VertexSectionContainer::iterator get_list_iterator (Vertex *o)
returns the iterator at which the given element lies in the section container
EdgeSectionContainer::iterator get_list_iterator (Edge *o)
returns the iterator at which the given element lies in the section container
FaceSectionContainer::iterator get_list_iterator (Face *o)
returns the iterator at which the given element lies in the section container
VolumeSectionContainer::iterator get_list_iterator (Volume *o)
returns the iterator at which the given element lies in the section container
Protected Member Functions inherited from ug::ISubsetHandler
void alter_subset_index (Edge *e, int subsetIndex)
void alter_subset_index (Face *f, int subsetIndex)
void alter_subset_index (Vertex *v, int subsetIndex)
void alter_subset_index (Volume *v, int subsetIndex)
void assign_subset_handler (const ISubsetHandler &sh)
selects elements based on the selection in the srcHandler
void create_required_subsets (int index)
creates all required infos (and pipes) up to the given index.
template<class TElem >
void elems_to_be_merged (Grid *grid, TElem *target, TElem *elem1, TElem *elem2)
helper for GridObserver callbacks.
void reset_subset_indices (uint shElements=SHE_ALL)
sets the subset-indices of all elements of m_pGrid to -1.
void set_grid (Grid *grid)
set the grid on which the subset-handler shall work.
void subset_assigned (Edge *e, int subsetIndex)
void subset_assigned (Face *f, int subsetIndex)
void subset_assigned (Vertex *v, int subsetIndex)
void subset_assigned (Volume *v, int subsetIndex)
Protected Attributes
AttachedEdgeList::AEntry m_aSharedEntryEDGE
AttachedFaceList::AEntry m_aSharedEntryFACE
AttachedVolumeList::AEntry m_aSharedEntryVOL
AttachedVertexList::AEntry m_aSharedEntryVRT
SubsetVec m_subsets
Protected Attributes inherited from ug::ISubsetHandler
Grid::EdgeAttachmentAccessor< ASubsetIndex > m_aaSubsetIndexEDGE
Grid::FaceAttachmentAccessor< ASubsetIndex > m_aaSubsetIndexFACE
Grid::VolumeAttachmentAccessor< ASubsetIndex > m_aaSubsetIndexVOL
Grid::VertexAttachmentAccessor< ASubsetIndex > m_aaSubsetIndexVRT
ASubsetIndex m_aSubsetIndex
bool m_bStrictInheritanceEnabled
bool m_bSubsetInheritanceEnabled
int m_defaultSubsetIndex
SubsetInfo m_defaultSubsetInfo
Grid * m_pGrid
SubsetInfoVec m_subsetInfos
uint m_supportedElements
Detailed Description
Partitions elements of a grid into several subsets.
The user can iterate over elements of grid subset-wise.
Member Typedef Documentation
AttachedEdgeList
typedef Grid::traits<Edge>::AttachedElementList ug::ISubsetHandler::AttachedEdgeList protected
AttachedFaceList
typedef Grid::traits<Face>::AttachedElementList ug::ISubsetHandler::AttachedFaceList protected
AttachedVertexList
typedef Grid::traits<Vertex>::AttachedElementList ug::ISubsetHandler::AttachedVertexList protected
enable subset-attachment support
if subset-attachments are enabled you may attach data to the elements of a subset. This is useful if you want to store different data in the elements of different subsets. returns true if subset-attachments are enabled. attach with unspecified default value. Pass either Vertex, Edge, Face or Volume as TGeomObjClass. attach with specified default value Pass either Vertex, Edge, Face or Volume as TGeomObjClass. Pass either Vertex, Edge, Face or Volume as TGeomObjClass. returns the attachment data container for elements of type TGeomObj for the given subset. Use the data-container with care! You should never clear or resize it.
Valid types for TGeomObj are Vertex, Edge, Face and Volume. call it like this (let sh be an instance of ISubsetHandler): sh.get_attachment_data_container<Vertex>(aSomeAttachment, someSubsetIndex);
AttachedVolumeList
typedef Grid::traits<Volume>::AttachedElementList ug::ISubsetHandler::AttachedVolumeList protected
EdgeSectionContainer
typedef Grid::traits<Edge>::SectionContainer ug::ISubsetHandler::EdgeSectionContainer protected
FaceSectionContainer
typedef Grid::traits<Face>::SectionContainer ug::ISubsetHandler::FaceSectionContainer protected
SubsetVec
typedef std::vector<Subset*> ug::GridSubsetHandler::SubsetVec protected
VertexSectionContainer
typedef Grid::traits<Vertex>::SectionContainer ug::ISubsetHandler::VertexSectionContainer protected
VolumeSectionContainer
typedef Grid::traits<Volume>::SectionContainer ug::ISubsetHandler::VolumeSectionContainer protected
Constructor & Destructor Documentation
GridSubsetHandler() [1/3]
ug::GridSubsetHandler::GridSubsetHandler (uint supportedElements = SHE_ALL)
GridSubsetHandler() [2/3]
ug::GridSubsetHandler::GridSubsetHandler (Grid & grid, uint supportedElements = SHE_ALL)
References assign_grid(), and ug::ISubsetHandler::grid().
GridSubsetHandler() [3/3]
ug::GridSubsetHandler::GridSubsetHandler (const GridSubsetHandler & sh)
WARNING: Don't call the copy-constructor from derived classes, Since it calls virtual methods.
References assign_grid(), ug::ISubsetHandler::assign_subset_handler(), and ug::ISubsetHandler::grid().
~GridSubsetHandler()
ug::GridSubsetHandler::~GridSubsetHandler ()
References detach_data(), erase_subset_lists_impl(), and ug::ISubsetHandler::m_pGrid.
Member Function Documentation
add_required_subset_lists()
void ug::GridSubsetHandler::add_required_subset_lists (int maxIndex) protected virtual
add a subset
Implements ug::ISubsetHandler.
References ug::ISubsetHandler::elements_are_supported(), ug::Grid::get_attachment_pipe(), ug::SectionContainer< TValue, TContainer >::get_container(), m_aSharedEntryEDGE, m_aSharedEntryFACE, m_aSharedEntryVOL, m_aSharedEntryVRT, ug::GridSubsetHandler::Subset::m_edges, ug::GridSubsetHandler::Subset::m_faces, ug::ISubsetHandler::m_pGrid, m_subsets, ug::GridSubsetHandler::Subset::m_vertices, ug::GridSubsetHandler::Subset::m_volumes, ug::AttachedElementList< TAttachmentPipe >::set_pipe(), ug::SHE_EDGE, ug::SHE_FACE, ug::SHE_VERTEX, and ug::SHE_VOLUME.
assign_grid() [1/2]
void ug::GridSubsetHandler::assign_grid (Grid & grid)
References assign_grid(), and ug::ISubsetHandler::grid().
assign_grid() [2/2]
void ug::GridSubsetHandler::assign_grid (Grid * grid)
References ug::Grid::attach_to_edges(), ug::Grid::attach_to_faces(), ug::Grid::attach_to_vertices(), ug::Grid::attach_to_volumes(), cleanup(), ug::ISubsetHandler::elements_are_supported(), ug::ISubsetHandler::grid(), m_aSharedEntryEDGE, m_aSharedEntryFACE, m_aSharedEntryVOL, m_aSharedEntryVRT, ug::ISubsetHandler::m_pGrid, ug::ISubsetHandler::set_grid(), ug::SHE_EDGE, ug::SHE_FACE, ug::SHE_VERTEX, and ug::SHE_VOLUME.
Referenced by assign_grid(), GridSubsetHandler(), ug::MultiGrid::init(), and ug::LoadGridFromART().
assign_subset() [1/10]
void ug::GridSubsetHandler::assign_subset (Edge * elem, int subsetIndex) virtual
assigns an edge to a subset.
If the subset doesn't already exist, it will be created.
Implements ug::ISubsetHandler.
References assign_subset_impl(), ug::ISubsetHandler::elements_are_supported(), and ug::SHE_EDGE.
assign_subset() [2/10]
virtual void ug::ISubsetHandler::assign_subset
The implementation in a derived class should store the element in a list and call subset_assigned with the iterators position and the subset-index. The iterator can later be retrieved with get_list_iterator(...). The index can be retrieved with get_subset_index(...).
assign_subset() [3/10]
void ug::GridSubsetHandler::assign_subset (Face * elem, int subsetIndex) virtual
assigns a face to a subset.
If the subset doesn't already exist, it will be created.
Implements ug::ISubsetHandler.
References assign_subset_impl(), ug::ISubsetHandler::elements_are_supported(), and ug::SHE_FACE.
assign_subset() [4/10]
virtual void ug::ISubsetHandler::assign_subset
The implementation in a derived class should store the element in a list and call subset_assigned with the iterators position and the subset-index. The iterator can later be retrieved with get_list_iterator(...). The index can be retrieved with get_subset_index(...).
assign_subset() [5/10]
void ug::ISubsetHandler::assign_subset
Forwards the call to the assign_subset method for the specific type (e.g. Vertex, Edge, Face, Volume).
assign_subset() [6/10]
template<class TIterator > void ug::ISubsetHandler::assign_subset (class TIterator)
assign_subset() [7/10]
void ug::GridSubsetHandler::assign_subset (Vertex * elem, int subsetIndex) virtual
assigns a vertex to a subset.
If the subset doesn't already exist, it will be created.
Implements ug::ISubsetHandler.
References assign_subset_impl(), ug::ISubsetHandler::elements_are_supported(), and ug::SHE_VERTEX.
Referenced by ug::AdjustSubsetsForLgmNg(), ug::AssignCreaseVertices(), ug::AssignFaceInterfaceEdgesToSubsets(), ug::AssignFixedVertices(), ug::AssignSubsetsByInterfaceType(), ug::AssignSubsetsByLevel(), ug::AssignSubsetsByQuality(), ug::AssignSubsetsBySurfaceViewState(), ug::AssignTetrahedronAttributesByAspectRatio(), ug::AssignVolumeInterfaceFacesToSubsets(), ug::CheckValences(), ug::MultiGrid::create(), ug::MultiGrid::create_by_cloning(), ug::MultiGrid::element_created(), ug::ExpandFractures2d(), ug::ExpandFractures3d(), ug::ExtrudeCylinder(), ug::MarkFixedCreaseVertices(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), ug::PartitionDomain_MetisKWay(), ug::PartitionElements_RegularGrid(), ug::PartitionGrid_MetisKway(), ug::PartitionMultiGrid_MetisKway(), ug::PartitionMultiGridLevel_MetisKway(), ug::PartitionMultiGridLevel_ParmetisKway(), ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection(), ug::PerformRetetrahedralization(), ug::ClusterElementStacks< elem_t, vector_t >::post_process(), ug::SmoothPartitionBounds< elem_t >::post_process(), ug::DelaunayDebugSaver::save(), ug::GlobalFracturedMediaRefiner::save_marks_to_file(), ug::GlobalMultiGridRefiner::save_marks_to_file(), ug::HangingNodeRefinerBase< TSelector >::save_marks_to_file(), ug::SaveCoarsenMarksToFile(), ug::SavePartitionMapToFile(), ug::SeparateFaceSubsetsByNormal(), ug::SeparateSubsetsByLowerDimSeparators(), ug::SplitIrregularManifoldSubset(), ug::SplitIrregularPolyChain(), and ug::TriangleFill_SweepLine().
assign_subset() [8/10]
virtual void ug::ISubsetHandler::assign_subset
The implementation in a derived class should store the element in a list and call subset_assigned with the iterators position and the subset-index. The iterator can later be retrieved with get_list_iterator(...). The index can be retrieved with get_subset_index(...).
assign_subset() [9/10]
void ug::GridSubsetHandler::assign_subset (Volume * elem, int subsetIndex) virtual
assigns a volume to a subset.
If the subset doesn't already exist, it will be created.
Implements ug::ISubsetHandler.
References assign_subset_impl(), ug::ISubsetHandler::elements_are_supported(), and ug::SHE_VOLUME.
assign_subset() [10/10]
virtual void ug::ISubsetHandler::assign_subset
The implementation in a derived class should store the element in a list and call subset_assigned with the iterators position and the subset-index. The iterator can later be retrieved with get_list_iterator(...). The index can be retrieved with get_subset_index(...).
assign_subset_impl()
template<class TElem > void ug::GridSubsetHandler::assign_subset_impl (TElem * elem, int subsetIndex) inline protected
this method is called by ISubsetHandler when attachment_support has been enabled.
a helper method for the public assign_subset methods.
References get_list_iterator(), ug::ISubsetHandler::get_subset_index(), ug::ISubsetHandler::m_pGrid, ug::ISubsetHandler::subset_assigned(), and ug::ISubsetHandler::subset_required().
Referenced by assign_subset().
begin() [1/3]
template<class TElem > geometry_traits< TElem >::iterator ug::GridSubsetHandler::begin (int subsetIndex)
returns the begin-iterator for the elements of type TElem in the given subset.
e.g. begin<Triangle>(0)
References num_subsets_in_list().
Referenced by ug::AdjustSubsetsForLgmNg(), ug::AssignCreaseVertices(), ug::AssignFaceInterfaceEdgesToSubsets(), ug::AssignFixedVertices(), ug::AssignVolumeInterfaceFacesToSubsets(), ug::MultiGrid::begin(), ug::DistributeExpansionMarks3D(), ug::ExpandFractures2d(), ug::ExportGridToUG(), ug::ExportGridToUG_2D(), ug::MarkFixedCreaseVertices(), ug::SavePartitionMapToFile(), ug::SeparateFaceSubsetsByNormal(), ug::SplitIrregularManifoldSubset(), ug::SplitIrregularPolyChain(), ug::WriteLGM(), and ug::WriteNG().
begin() [2/3]
template<class TElem > geometry_traits< TElem >::const_iterator ug::GridSubsetHandler::begin (int subsetIndex) const
returns the begin-iterator for the elements of type TElem in the given subset.
e.g. begin<Triangle>(0)
References num_subsets_in_list().
begin() [3/3]
template<class TElem > geometry_traits<TElem>::const_iterator ug::GridSubsetHandler::begin (int subsetIndex, size_t) const inline
returns the begin-iterator for the elements of type TElem in the given subset.
only for compatibility reasons with MGSubsetHandler. second argument is ignored. use i.e. as follows: begin<Triangle>(0, 0)
change_elem_subset_indices()
template<class TElem > void ug::GridSubsetHandler::change_elem_subset_indices (int indOld, int indNew) protected
helper for change_subset_indices
References ug::ISubsetHandler::alter_subset_index().
change_subset_indices()
void ug::GridSubsetHandler::change_subset_indices (int indOld, int indNew) protected virtual
changes the subset-indices of all elements int the subset.
WARNING: subsets are not automatically changed accordingly. After termination Subset-Indices and Subset-Infos/iterators are asynchronous. Make sure to change subset-infos and iterators accordingly.
Implements ug::ISubsetHandler.
References ug::ISubsetHandler::elements_are_supported(), ug::ISubsetHandler::m_pGrid, ug::SHE_EDGE, ug::SHE_FACE, ug::SHE_VERTEX, and ug::SHE_VOLUME.
cleanup()
void ug::GridSubsetHandler::cleanup () protected
helper for collect_subset_elements
removes attachments
References detach_data(), and erase_subset_lists_impl().
Referenced by assign_grid(), and grid_to_be_destroyed().
clear_subset_elements()
template<class TElem > void ug::GridSubsetHandler::clear_subset_elements (int subsetIndex)
removes all elements of type TElem from the specified subset.
References ug::ISubsetHandler::alter_subset_index(), ug::SectionContainer< TValue, TContainer >::erase(), ug::ISubsetHandler::m_pGrid, and num_subsets_in_list().
clear_subset_lists()
void ug::GridSubsetHandler::clear_subset_lists (int index) protected virtual
clears the element lists in the given subset. Does not alter any indices.
Implements ug::ISubsetHandler.
References ug::ISubsetHandler::m_pGrid.
contains_edges()
virtual bool ug::GridSubsetHandler::contains_edges (int subsetIndex) const inline virtual
returns true if the subset contains edges
Implements ug::ISubsetHandler.
contains_faces()
virtual bool ug::GridSubsetHandler::contains_faces (int subsetIndex) const inline virtual
returns true if the subset contains faces
Implements ug::ISubsetHandler.
contains_vertices()
virtual bool ug::GridSubsetHandler::contains_vertices (int subsetIndex) const inline virtual
collects all vertices that are in the given subset.
Please consider using begin and end methods instead. If subset -1 is specified, the method has compexity O(n), where n is the number of vertices in the underlying grid.
Returns
number of collected elements.
See also
begin, end collects all edges that are in the given subset. Please consider using begin and end methods instead. If subset -1 is specified, the method has compexity O(n), where n is the number of edges in the underlying grid.
Returns
number of collected elements.
See also
begin, end collects all faces that are in the given subset. Please consider using begin and end methods instead. If subset -1 is specified, the method has compexity O(n), where n is the number of faces in the underlying grid.
Returns
number of collected elements.
See also
begin, end collects all volumes that are in the given subset. Please consider using begin and end methods instead. If subset -1 is specified, the method has compexity O(n), where n is the number of volumes in the underlying grid.
Returns
number of collected elements.
See also
begin, end returns true if the subset contains vertices
Implements ug::ISubsetHandler.
contains_volumes()
virtual bool ug::GridSubsetHandler::contains_volumes (int subsetIndex) const inline virtual
returns true if the subset contains volumes
Implements ug::ISubsetHandler.
detach_data()
void ug::GridSubsetHandler::detach_data () protected
detaches all attached data.
References ug::Grid::detach_from_edges(), ug::Grid::detach_from_faces(), ug::Grid::detach_from_vertices(), ug::Grid::detach_from_volumes(), ug::ISubsetHandler::elements_are_supported(), m_aSharedEntryEDGE, m_aSharedEntryFACE, m_aSharedEntryVOL, m_aSharedEntryVRT, ug::ISubsetHandler::m_pGrid, ug::SHE_EDGE, ug::SHE_FACE, ug::SHE_VERTEX, and ug::SHE_VOLUME.
Referenced by cleanup(), and ~GridSubsetHandler().
empty() [1/4]
template<class TElem > bool ug::GridSubsetHandler::empty inline
returns true if the subset-handler contains no elements of the given type.
Referenced by ug::ExportGridToUG_2D(), ug::PartitionDomain_MetisKWay(), ug::PartitionDomain_RegularGrid(), and ug::SplitIrregularManifoldSubset().
empty() [2/4]
bool ug::GridSubsetHandler::empty () const inline
returns true if the subset-handler contains no elements at all.
empty() [3/4]
template<class TElem > bool ug::GridSubsetHandler::empty (int subsetIndex) const inline
empty() [4/4]
bool ug::GridSubsetHandler::empty (int subsetIndex) const inline
returns true if the subset-handler contains no elements at all.
end() [1/3]
template<class TElem > geometry_traits< TElem >::iterator ug::GridSubsetHandler::end (int subsetIndex)
returns the end-iterator for the elements of type TElem in the given subset.
e.g. end<Triangle>(0)
References num_subsets_in_list().
Referenced by ug::AdjustSubsetsForLgmNg(), ug::AssignCreaseVertices(), ug::AssignFaceInterfaceEdgesToSubsets(), ug::AssignFixedVertices(), ug::AssignVolumeInterfaceFacesToSubsets(), ug::DistributeExpansionMarks3D(), ug::MultiGrid::end(), ug::ExpandFractures2d(), ug::ExportGridToUG(), ug::ExportGridToUG_2D(), ug::MarkFixedCreaseVertices(), ug::SavePartitionMapToFile(), ug::SeparateFaceSubsetsByNormal(), ug::SplitIrregularManifoldSubset(), ug::SplitIrregularPolyChain(), ug::WriteLGM(), and ug::WriteNG().
end() [2/3]
template<class TElem > geometry_traits< TElem >::const_iterator ug::GridSubsetHandler::end (int subsetIndex) const
returns the end-iterator for the elements of type TElem in the given subset.
e.g. end<Triangle>(0)
References num_subsets_in_list().
end() [3/3]
template<class TElem > geometry_traits<TElem>::const_iterator ug::GridSubsetHandler::end (int subsetIndex, size_t) const inline
returns the end-iterator for the elements of type TElem in the given subset.
only for compatibility reasons with MGSubsetHandler. second argument is ignored. use i.e. as follows: end<Triangle>(0, 0)
erase_subset_lists() [1/2]
void ug::GridSubsetHandler::erase_subset_lists () protected virtual
erases the subsets. Doesn't alter any indices.
Implements ug::ISubsetHandler.
References erase_subset_lists_impl().
erase_subset_lists() [2/2]
void ug::GridSubsetHandler::erase_subset_lists (int index) protected virtual
erases the subset but does not touch the subset-indices.
Implements ug::ISubsetHandler.
References m_subsets, and num_subsets_in_list().
erase_subset_lists_impl()
void ug::GridSubsetHandler::erase_subset_lists_impl () protected
non-virtual implementation of erase_subset_lists. Callable from destructor
References m_subsets.
Referenced by cleanup(), erase_subset_lists(), and ~GridSubsetHandler().
get_grid_objects()
GridObjectCollection ug::GridSubsetHandler::get_grid_objects () const
References ug::GridObjectCollection::add_level(), m_subsets, and num_subsets_in_list().
Referenced by ug::MultiGrid::get_grid_objects(), and ug::PrintGridElementNumbers().
get_grid_objects_in_subset()
GridObjectCollection ug::GridSubsetHandler::get_grid_objects_in_subset (int subsetInd) const virtual
Returns the geometric object collection for the given subset.
Note that the GOC may contain multiple levels.
Implements ug::ISubsetHandler.
References m_subsets, num_subsets_in_list(), and ug::ISubsetHandler::subset_required().
Referenced by ug::MultiGrid::get_grid_objects().
get_list_iterator() [1/4]
EdgeSectionContainer::iterator ug::GridSubsetHandler::get_list_iterator (Edge * o) inline protected
returns the iterator at which the given element lies in the section container
This method may only be called if the element is in a subset != -1.
get_list_iterator() [2/4]
FaceSectionContainer::iterator ug::GridSubsetHandler::get_list_iterator (Face * o) inline protected
returns the iterator at which the given element lies in the section container
This method may only be called if the element is in a subset != -1.
get_list_iterator() [3/4]
VertexSectionContainer::iterator ug::GridSubsetHandler::get_list_iterator (Vertex * o) inline protected
returns the iterator at which the given element lies in the section container
This method may only be called if the element is in a subset != -1.
Referenced by assign_subset_impl().
get_list_iterator() [4/4]
VolumeSectionContainer::iterator ug::GridSubsetHandler::get_list_iterator (Volume * o) inline protected
returns the iterator at which the given element lies in the section container
This method may only be called if the element is in a subset != -1.
grid_to_be_destroyed()
void ug::GridSubsetHandler::grid_to_be_destroyed (Grid * grid) virtual
perform cleanup
Reimplemented from ug::ISubsetHandler.
References cleanup(), ug::ISubsetHandler::grid(), ug::ISubsetHandler::grid_to_be_destroyed(), and ug::ISubsetHandler::m_pGrid.
join_subset_lists()
void ug::GridSubsetHandler::join_subset_lists (int target, int src1, int src2) protected virtual
join the subset-lists but do not touch the subset-indices.
Implements ug::ISubsetHandler.
References ug::GridSubsetHandler::Subset::m_edges, ug::GridSubsetHandler::Subset::m_faces, m_subsets, ug::GridSubsetHandler::Subset::m_vertices, ug::GridSubsetHandler::Subset::m_volumes, boost::target(), and ug::SectionContainer< TValue, TContainer >::transfer_elements().
move_subset_lists()
void ug::GridSubsetHandler::move_subset_lists (int indexFrom, int indexTo) protected virtual
moves the subset but does not touch the subset-indices.
Implements ug::ISubsetHandler.
References m_subsets.
num() [1/3]
template<class TElem > uint ug::GridSubsetHandler::num
returns the total number of elements
References num_subsets_in_list().
Referenced by ug::AdjustSubsetsForLgmNg(), ug::ExportGridToUG(), ug::ExportGridToUG_2D(), ug::MarkFixedCreaseVertices(), ug::MultiGrid::num(), ug::PerformRetetrahedralization(), ug::SplitIrregularManifoldSubset(), ug::SplitIrregularPolyChain(), and ug::SubsetIsRegularGrid().
num() [2/3]
template<class TElem > uint ug::GridSubsetHandler::num (int subsetIndex) const
returns the number of elements in the given subset
References num_subsets_in_list().
num() [3/3]
template<class TElem > uint ug::GridSubsetHandler::num (int subsetIndex, size_t) const inline
returns the number of elements in the given subset
only for compatibility reasons with MGSubsetHandler. second argument is ignored.
num_elements() [1/2]
template<class TElem > uint ug::GridSubsetHandler::num_elements (int subsetIndex) const
returns the number of elements in the given subset
References num_subsets_in_list().
Referenced by ug::AssignFaceInterfaceEdgesToSubsets(), ug::AssignVolumeInterfaceFacesToSubsets(), ug::GetMaxSubsetIndex(), and ug::MakeSubsetsConsecutive().
num_elements() [2/2]
template<class TElem > uint ug::GridSubsetHandler::num_elements (int subsetIndex, size_t) const inline
returns the number of elements in the given subset
only for compatibility reasons with MGSubsetHandler. second argument is ignored.
num_levels()
uint ug::GridSubsetHandler::num_levels () const inline
returns number of levels (always 1)
only for compatibility reasons with MGSubsetHandler.
num_subsets_in_list()
uint ug::GridSubsetHandler::num_subsets_in_list () const inline protected
returns the number of subsets in the local list
Referenced by begin(), clear_subset_elements(), end(), erase_subset_lists(), get_grid_objects(), get_grid_objects_in_subset(), num(), num_elements(), and perform_self_tests().
operator=() [1/2]
GridSubsetHandler & ug::GridSubsetHandler::operator= (const GridSubsetHandler & sh)
References ug::ISubsetHandler::operator=().
operator=() [2/2]
GridSubsetHandler & ug::GridSubsetHandler::operator= (const ISubsetHandler & sh)
References ug::ISubsetHandler::operator=().
perform_self_tests()
template<class TElem > bool ug::GridSubsetHandler::perform_self_tests
only for debug purposes
References ug::ISubsetHandler::get_subset_index(), LOG, and num_subsets_in_list().
section_container() [1/2]
template<class TElem > Grid::traits< TElem >::SectionContainer & ug::GridSubsetHandler::section_container (int si) inline protected
returns the section container for the given type, subset and level
References ug::GridSubsetHandler::Subset::m_edges, ug::GridSubsetHandler::Subset::m_faces, m_subsets, ug::GridSubsetHandler::Subset::m_vertices, and ug::GridSubsetHandler::Subset::m_volumes.
Referenced by section_container().
section_container() [2/2]
template<class TElem > const Grid::traits< TElem >::SectionContainer & ug::GridSubsetHandler::section_container (int si) const inline protected
returns the const section container for the given type, subset and level
References ug::GridSubsetHandler::Subset::m_edges, ug::GridSubsetHandler::Subset::m_faces, m_subsets, ug::GridSubsetHandler::Subset::m_vertices, ug::GridSubsetHandler::Subset::m_volumes, and section_container().
swap_subset_lists()
void ug::GridSubsetHandler::swap_subset_lists (int ind1, int ind2) protected virtual
swaps the subsets but does not touch the subset-indices.
Implements ug::ISubsetHandler.
References m_subsets.
Member Data Documentation
m_aSharedEntryEDGE
AttachedEdgeList::AEntry ug::GridSubsetHandler::m_aSharedEntryEDGE protected
Referenced by add_required_subset_lists(), assign_grid(), and detach_data().
m_aSharedEntryFACE
AttachedFaceList::AEntry ug::GridSubsetHandler::m_aSharedEntryFACE protected
Referenced by add_required_subset_lists(), assign_grid(), and detach_data().
m_aSharedEntryVOL
AttachedVolumeList::AEntry ug::GridSubsetHandler::m_aSharedEntryVOL protected
Referenced by add_required_subset_lists(), assign_grid(), and detach_data().
m_aSharedEntryVRT
AttachedVertexList::AEntry ug::GridSubsetHandler::m_aSharedEntryVRT protected
Referenced by add_required_subset_lists(), assign_grid(), and detach_data().
m_subsets
SubsetVec ug::GridSubsetHandler::m_subsets protected
Referenced by add_required_subset_lists(), erase_subset_lists(), erase_subset_lists_impl(), get_grid_objects(), get_grid_objects_in_subset(), join_subset_lists(), move_subset_lists(), section_container(), and swap_subset_lists().
The documentation for this class was generated from the following files:
ugbase/lib_grid/tools/subset_handler_grid.h
ugbase/lib_grid/tools/subset_handler_grid.cpp
ugbase/lib_grid/tools/subset_handler_grid_impl.hpp