ug4: ug::VMAdd Class Reference
ug::VMAdd Class Reference
--> documentation in vm.doxygen <–///
#include <vm.h>
Public Member Functions
void adjust_jmp_pos (int iPos, int jmpPos)
void assign (int v)
void binary (int oper)
double call ()
double call (double *stack, int &SP)
double call (double a)
double call (double a, double b)
double call (double a, double b, double c)
void call (SmartPtr< VMAdd > subfunction)
double call_sub (double *stack, int &SP)
int execute (double *ret, const double *in)
void execute_binary (size_t &i, double *stack, int SP)
void execute_unary (size_t &i, double &v)
int get_pos ()
int jmp ()
int jmp_if_false ()
int jump (VMInstruction instr)
size_t num_in ()
size_t num_out ()
void print ()
void print_rec (int level)
void print_short ()
void push (double constant)
void push_var (int i)
void ret ()
void set_in_out (size_t nrIn, size_t nrOut)
void set_name (std::string name)
void set_nr_of_variables (size_t nr)
void unary (int oper)
VMAdd ()
Private Types
enum VMInstruction {
PUSH_CONSTANT =0 , PUSH_VAR , JMP_IF_FALSE , JMP ,
OP_UNARY , OP_BINARY , ASSIGN , OP_RETURN ,
OP_CALL
}
Private Member Functions
void deserializeDouble (size_t &p, double &d)
void deserializeInt (size_t &p, int &i)
void deserializeVMInstr (size_t &p, VMInstruction &instr)
void print_op (size_t &i)
void print_unaryDouble (const char *desc, size_t &i)
void print_unaryInt (const char *desc, size_t &i)
void serializeChar (char c)
void serializeDouble (double d)
void serializeInt (int d)
void serializeVMInstr (VMInstruction inst)
Private Attributes
std::string m_name
size_t m_nrIn
size_t m_nrOut
std::vector< SmartPtr< VMAdd > > subfunctions
std::vector< double > variables
std::vector< char > vmBuf
Detailed Description
--> documentation in vm.doxygen <–///
Member Enumeration Documentation
VMInstruction
enum ug::VMAdd::VMInstruction private
Enumerator
PUSH_CONSTANT
PUSH_VAR
JMP_IF_FALSE
JMP
OP_UNARY
OP_BINARY
ASSIGN
OP_RETURN
OP_CALL
Constructor & Destructor Documentation
VMAdd()
ug::VMAdd::VMAdd () inline
References m_name.
Member Function Documentation
adjust_jmp_pos()
void ug::VMAdd::adjust_jmp_pos (int iPos, int jmpPos) inline
References p, and vmBuf.
Referenced by ug::LUAParserClass::createVM().
assign()
void ug::VMAdd::assign (int v) inline
References ASSIGN, and serializeInt().
Referenced by ug::LUAParserClass::createVM().
binary()
void ug::VMAdd::binary (int oper) inline
References OP_BINARY, and serializeInt().
Referenced by ug::LUAParserClass::createVM().
call() [1/6]
double ug::VMAdd::call () inline
Referenced by call(), call_sub(), and execute().
call() [2/6]
double ug::VMAdd::call (double * stack, int & SP) inline
References ASSIGN, deserializeDouble(), deserializeInt(), deserializeVMInstr(), execute_binary(), execute_unary(), JMP, JMP_IF_FALSE, m_nrOut, OP_BINARY, OP_CALL, OP_RETURN, OP_UNARY, PUSH_CONSTANT, PUSH_VAR, subfunctions, UG_ASSERT, and variables.
call() [3/6]
double ug::VMAdd::call (double a) inline
References call(), m_nrIn, m_nrOut, UG_ASSERT, and variables.
call() [4/6]
double ug::VMAdd::call (double a, double b) inline
References call(), m_nrIn, m_nrOut, UG_ASSERT, and variables.
call() [5/6]
double ug::VMAdd::call (double a, double b, double c) inline
References call(), m_nrIn, m_nrOut, UG_ASSERT, and variables.
call() [6/6]
void ug::VMAdd::call (SmartPtr< VMAdd > subfunction) inline
References OP_CALL, serializeInt(), and subfunctions.
Referenced by ug::LUAParserClass::createVM().
call_sub()
double ug::VMAdd::call_sub (double * stack, int & SP) inline
References call(), m_nrIn, and variables.
deserializeDouble()
void ug::VMAdd::deserializeDouble (size_t & p, double & d) inline private
References p, and vmBuf.
Referenced by call(), and print_unaryDouble().
deserializeInt()
void ug::VMAdd::deserializeInt (size_t & p, int & i) inline private
References p, and vmBuf.
Referenced by call(), execute_binary(), execute_unary(), print_op(), print_rec(), and print_unaryInt().
deserializeVMInstr()
void ug::VMAdd::deserializeVMInstr (size_t & p, VMInstruction & instr) inline private
References p, and vmBuf.
Referenced by call(), and print_rec().
execute()
int ug::VMAdd::execute (double * ret, const double * in) inline
References call(), m_nrIn, m_nrOut, ret(), UG_ASSERT, and variables.
execute_binary()
void ug::VMAdd::execute_binary (size_t & i, double * stack, int SP) inline
References deserializeInt(), LUAPARSER_AND, LUAPARSER_EQ, LUAPARSER_GE, LUAPARSER_LE, LUAPARSER_MATH_MAX, LUAPARSER_MATH_MIN, LUAPARSER_MATH_POW, LUAPARSER_NE, and LUAPARSER_OR.
Referenced by call().
execute_unary()
void ug::VMAdd::execute_unary (size_t & i, double & v) inline
References deserializeInt(), LUAPARSER_MATH_ABS, LUAPARSER_MATH_CEIL, LUAPARSER_MATH_COS, LUAPARSER_MATH_EXP, LUAPARSER_MATH_FLOOR, LUAPARSER_MATH_LOG, LUAPARSER_MATH_LOG10, LUAPARSER_MATH_SIN, and LUAPARSER_MATH_SQRT.
Referenced by call().
get_pos()
int ug::VMAdd::get_pos () inline
References vmBuf.
Referenced by ug::LUAParserClass::createVM(), and jump().
jmp()
int ug::VMAdd::jmp () inline
References JMP, and jump().
Referenced by ug::LUAParserClass::createVM().
jmp_if_false()
int ug::VMAdd::jmp_if_false () inline
References JMP_IF_FALSE, and jump().
Referenced by ug::LUAParserClass::createVM().
jump()
int ug::VMAdd::jump (VMInstruction instr) inline
References get_pos(), serializeInt(), and serializeVMInstr().
Referenced by jmp(), and jmp_if_false().
num_in()
size_t ug::VMAdd::num_in () inline
References m_nrIn.
num_out()
size_t ug::VMAdd::num_out () inline
References m_nrOut.
print()
void ug::VMAdd::print () inline
References print_rec().
Referenced by ug::bridge::convertVM().
print_op()
void ug::VMAdd::print_op (size_t & i) inline private
References deserializeInt(), LUAPARSER_AND, LUAPARSER_EQ, LUAPARSER_GE, LUAPARSER_LE, LUAPARSER_MATH_ABS, LUAPARSER_MATH_CEIL, LUAPARSER_MATH_COS, LUAPARSER_MATH_EXP, LUAPARSER_MATH_FLOOR, LUAPARSER_MATH_LOG, LUAPARSER_MATH_LOG10, LUAPARSER_MATH_MAX, LUAPARSER_MATH_MIN, LUAPARSER_MATH_POW, LUAPARSER_MATH_SIN, LUAPARSER_MATH_SQRT, LUAPARSER_NE, LUAPARSER_OR, and UG_LOG.
Referenced by print_rec().
print_rec()
void ug::VMAdd::print_rec (int level) inline
References ASSIGN, deserializeInt(), deserializeVMInstr(), JMP, JMP_IF_FALSE, m_name, OP_BINARY, OP_CALL, OP_RETURN, OP_UNARY, print_op(), print_short(), print_unaryDouble(), print_unaryInt(), PUSH_CONSTANT, PUSH_VAR, subfunctions, UG_ASSERT, UG_COND_THROW, UG_LOG, and vmBuf.
Referenced by print().
print_short()
void ug::VMAdd::print_short () inline
References m_name, m_nrIn, m_nrOut, subfunctions, UG_LOG, and variables.
Referenced by print_rec().
print_unaryDouble()
void ug::VMAdd::print_unaryDouble (const char * desc, size_t & i) inline private
References deserializeDouble(), and UG_LOG.
Referenced by print_rec().
print_unaryInt()
void ug::VMAdd::print_unaryInt (const char * desc, size_t & i) inline private
References deserializeInt(), and UG_LOG.
Referenced by print_rec().
push()
void ug::VMAdd::push (double constant) inline
References PUSH_CONSTANT, serializeDouble(), and serializeInt().
Referenced by ug::LUAParserClass::createVM().
push_var()
void ug::VMAdd::push_var (int i) inline
References PUSH_VAR, and serializeInt().
Referenced by ug::LUAParserClass::createVM().
ret()
void ug::VMAdd::ret () inline
References OP_RETURN, and serializeInt().
Referenced by ug::LUAParserClass::createVM(), and execute().
serializeChar()
void ug::VMAdd::serializeChar (char c) inline private
References vmBuf.
Referenced by serializeDouble(), and serializeInt().
serializeDouble()
void ug::VMAdd::serializeDouble (double d) inline private
References serializeChar().
Referenced by push().
serializeInt()
void ug::VMAdd::serializeInt (int d) inline private
References serializeChar().
Referenced by assign(), binary(), call(), jump(), push(), push_var(), ret(), serializeVMInstr(), and unary().
serializeVMInstr()
void ug::VMAdd::serializeVMInstr (VMInstruction inst) inline private
References serializeInt().
Referenced by jump().
set_in_out()
void ug::VMAdd::set_in_out (size_t nrIn, size_t nrOut) inline
References m_nrIn, and m_nrOut.
Referenced by ug::LUAParserClass::createVMHeader().
set_name()
void ug::VMAdd::set_name (std::string name) inline
References m_name, and name.
Referenced by ug::LUAParserClass::createVM().
set_nr_of_variables()
void ug::VMAdd::set_nr_of_variables (size_t nr) inline
References variables.
Referenced by ug::LUAParserClass::createVMHeader().
unary()
void ug::VMAdd::unary (int oper) inline
References OP_UNARY, and serializeInt().
Referenced by ug::LUAParserClass::createVM().
Member Data Documentation
m_name
std::string ug::VMAdd::m_name private
Referenced by print_rec(), print_short(), set_name(), and VMAdd().
m_nrIn
size_t ug::VMAdd::m_nrIn private
Referenced by call(), call_sub(), execute(), num_in(), print_short(), and set_in_out().
m_nrOut
size_t ug::VMAdd::m_nrOut private
Referenced by call(), execute(), num_out(), print_short(), and set_in_out().
subfunctions
std::vector<SmartPtr<VMAdd> > ug::VMAdd::subfunctions private
Referenced by call(), print_rec(), and print_short().
variables
std::vector<double> ug::VMAdd::variables private
Referenced by call(), call_sub(), execute(), print_short(), and set_nr_of_variables().
vmBuf
std::vector<char> ug::VMAdd::vmBuf private
Referenced by adjust_jmp_pos(), deserializeDouble(), deserializeInt(), deserializeVMInstr(), get_pos(), print_rec(), and serializeChar().
The documentation for this class was generated from the following file:
ugbase/bindings/lua/compiler/vm.h