ug4: ug::FileReaderSWC Class Reference
ug::FileReaderSWC Class Reference
#include <file_io_swc.h>
Public Types
typedef swc_types::SWCPoint SWCPoint
Public Member Functions
bool create_grid (Grid &g, ISubsetHandler *pSH, number scale_length=1.0)
FileReaderSWC ()
bool load_file (const char *fileName)
std::vector< swc_types::SWCPoint > & swc_points ()
const std::vector< swc_types::SWCPoint > & swc_points () const
~FileReaderSWC ()
Protected Attributes
std::vector< swc_types::SWCPoint > m_vPts
Member Typedef Documentation
SWCPoint
typedef swc_types::SWCPoint ug::FileReaderSWC::SWCPoint
Constructor & Destructor Documentation
FileReaderSWC()
ug::FileReaderSWC::FileReaderSWC () inline
~FileReaderSWC()
ug::FileReaderSWC::~FileReaderSWC () inline
Member Function Documentation
create_grid()
bool ug::FileReaderSWC::create_grid (Grid & g, ISubsetHandler * pSH, number scale_length = 1.0)
References ug::aPosition, ug::ISubsetHandler::assign_subset(), AssignSubsetColors(), ug::Grid::attach_to_vertices(), ug::swc_types::SWCPoint::conns, ug::swc_types::SWCPoint::coords, ug::Grid::create(), EraseEmptySubsets(), ug::UGError::get_msg(), ug::Grid::has_vertex_attachment(), ug::swc_types::SWCPoint::radius, ug::ISubsetHandler::set_subset_name(), ug::swc_types::SWCPoint::type, UG_LOGN, and ug::VecScale().
Referenced by ug::LoadGridFromSWC().
load_file()
bool ug::FileReaderSWC::load_file (const char * fileName)
References ug::swc_types::SWCPoint::conns, ug::swc_types::SWCPoint::coords, ug::swc_types::SWCPoint::radius, ug::swc_types::SWC_APIC, ug::swc_types::SWC_AXON, ug::swc_types::SWC_CUSTOM, ug::swc_types::SWC_DEND, ug::swc_types::SWC_END, ug::swc_types::SWC_FORK, ug::swc_types::SWC_SOMA, ug::swc_types::SWC_UNDF, ug::TrimString(), ug::swc_types::SWCPoint::type, and UG_LOGN.
Referenced by ug::LoadGridFromSWC().
swc_points() [1/2]
std::vector< swc_types::SWCPoint > & ug::FileReaderSWC::swc_points ()
swc_points() [2/2]
const std::vector< swc_types::SWCPoint > & ug::FileReaderSWC::swc_points () const
Member Data Documentation
m_vPts
std::vector<swc_types::SWCPoint> ug::FileReaderSWC::m_vPts protected
The documentation for this class was generated from the following files:
ugbase/lib_grid/file_io/file_io_swc.h
ugbase/lib_grid/file_io/file_io_swc.cpp