ug4: ug::stdvector< T, Allocator > Class Template Reference
ug::stdvector< T, Allocator > Class Template Reference
#include <stl_debug.h>
Public Types
typedef super::size_type size_type
Public Member Functions
super::reference operator[] (size_t i)
super::const_reference operator[] (size_t i) const
stdvector (const Allocator &a=Allocator())
stdvector (const std::vector< T, Allocator > &x)
stdvector (const stdvector< T, Allocator > &x)
stdvector (size_type n, const T &value=T(), const Allocator &a=Allocator())
Private Types
typedef std::vector< T, Allocator > super
Private Member Functions
void size_check (size_t i) const
Member Typedef Documentation
size_type
template<typename T , class Allocator = std::allocator<T>> typedef super::size_type ug::stdvector< T, Allocator >::size_type
super
template<typename T , class Allocator = std::allocator<T>> typedef std::vector<T, Allocator> ug::stdvector< T, Allocator >::super private
Constructor & Destructor Documentation
stdvector() [1/4]
template<typename T , class Allocator = std::allocator<T>> ug::stdvector< T, Allocator >::stdvector (const Allocator & a = Allocator()) inline explicit
stdvector() [2/4]
template<typename T , class Allocator = std::allocator<T>> ug::stdvector< T, Allocator >::stdvector (size_type n, const T & value = T(), const Allocator & a = Allocator()) inline explicit
stdvector() [3/4]
template<typename T , class Allocator = std::allocator<T>> ug::stdvector< T, Allocator >::stdvector (const std::vector< T, Allocator > & x) inline
stdvector() [4/4]
template<typename T , class Allocator = std::allocator<T>> ug::stdvector< T, Allocator >::stdvector (const stdvector< T, Allocator > & x) inline
Member Function Documentation
operator[]() [1/2]
template<typename T , class Allocator = std::allocator<T>> super::reference ug::stdvector< T, Allocator >::operator[] (size_t i) inline
References ug::stdvector< T, Allocator >::size_check().
operator[]() [2/2]
template<typename T , class Allocator = std::allocator<T>> super::const_reference ug::stdvector< T, Allocator >::operator[] (size_t i) const inline
References ug::stdvector< T, Allocator >::size_check().
size_check()
template<typename T , class Allocator = std::allocator<T>> void ug::stdvector< T, Allocator >::size_check (size_t i) const inline private
References UG_COND_THROW.
Referenced by ug::stdvector< T, Allocator >::operator[]().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/common/stl_debug.h