ug4: ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV Class Reference
ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV Class Reference
sub control volume structure
#include <fv1_geom.h>
Public Member Functions
number detJ () const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_corner (size_t co) const
return global corner number i
const MathVector< worldDim > * global_corners () const
return global corners
const MathVector< worldDim > & global_grad (size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector () const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip () const
global integration point
const MathMatrix< worldDim, dim > & JTInv () const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > * local_corners () const
return local corners
const MathVector< dim > & local_grad (size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector () const
vector of local gradients in ip point
const MathVector< dim > & local_ip () const
local integration point of scv
size_t node_id () const
node id that this scv is associated to
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shape functions
SCV ()
number shape (size_t sh) const
value of shape function i in integration point
const number * shape_vector () const
vector of shape functions in ip point
number volume () const
volume of scv
Static Public Attributes
static const size_t numCo = traits::NumCornersOfSCV
Number of corners of scvf.
Private Attributes
number detj
MathMatrix< worldDim, dim > JtInv
MidID midId [numCo]
size_t nodeId
MathVector< worldDim > vGlobalGrad [nsh]
MathVector< worldDim > vGloPos [numCo]
MathVector< dim > vLocalGrad [nsh]
MathVector< dim > vLocPos [numCo]
number Vol
number vShape [nsh]
Friends
class FV1Geometry_gen< TElem, TWorldDim, TCondensed >
Detailed Description
template<typename TElem, int TWorldDim, bool TCondensed>
class ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV
sub control volume structure
Constructor & Destructor Documentation
SCV()
template<typename TElem , int TWorldDim, bool TCondensed> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::SCV () inline
Member Function Documentation
detJ()
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::detJ () const inline
Determinant of Jacobian in integration point.
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::detj.
global_corner()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<worldDim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::global_corner (size_t co) const inline
return global corner number i
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::num_corners(), UG_ASSERT, and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vGloPos.
global_corners()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<worldDim>* ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::global_corners () const inline
return global corners
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vGloPos.
global_grad()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<worldDim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::global_grad (size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::num_sh(), UG_ASSERT, and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vGlobalGrad.
global_grad_vector()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<worldDim>* ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::global_grad_vector () const inline
vector of global gradients in ip point
global_ip()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<worldDim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::global_ip () const inline
global integration point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vGloPos.
JTInv()
template<typename TElem , int TWorldDim, bool TCondensed> const MathMatrix<worldDim,dim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::JTInv () const inline
Transposed Inverse of Jacobian in integration point.
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::JtInv.
local_corner()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<dim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_corner (size_t co) const inline
return local corner number i
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::num_corners(), UG_ASSERT, and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vLocPos.
local_corners()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<dim>* ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_corners () const inline
return local corners
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vLocPos.
local_grad()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<dim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_grad (size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::num_sh(), UG_ASSERT, and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vLocalGrad.
local_grad_vector()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<dim>* ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_grad_vector () const inline
vector of local gradients in ip point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vLocalGrad.
local_ip()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<dim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_ip () const inline
local integration point of scv
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vLocPos.
node_id()
template<typename TElem , int TWorldDim, bool TCondensed> size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::node_id () const inline
node id that this scv is associated to
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::nodeId.
num_corners()
template<typename TElem , int TWorldDim, bool TCondensed> size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::num_corners () const inline
number of corners, that bound the scvf
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::numCo.
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::global_corner(), and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_corner().
num_ip()
template<typename TElem , int TWorldDim, bool TCondensed> size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::num_ip () const inline
number of integration points
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::nip.
num_sh()
template<typename TElem , int TWorldDim, bool TCondensed> size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::num_sh () const inline
number of shape functions
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::nsh.
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::global_grad(), and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_grad().
shape()
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::shape (size_t sh) const inline
value of shape function i in integration point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vShape.
shape_vector()
template<typename TElem , int TWorldDim, bool TCondensed> const number* ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::shape_vector () const inline
vector of shape functions in ip point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vShape.
volume()
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::volume () const inline
volume of scv
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::Vol.
Friends And Related Function Documentation
FV1Geometry_gen< TElem, TWorldDim, TCondensed >
template<typename TElem , int TWorldDim, bool TCondensed> friend class FV1Geometry_gen< TElem, TWorldDim, TCondensed > friend
Member Data Documentation
detj
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::detj private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::detJ().
JtInv
template<typename TElem , int TWorldDim, bool TCondensed> MathMatrix<worldDim,dim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::JtInv private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::JTInv().
midId
template<typename TElem , int TWorldDim, bool TCondensed> MidID ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::midId[numCo] private
nodeId
template<typename TElem , int TWorldDim, bool TCondensed> size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::nodeId private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::node_id().
numCo
template<typename TElem , int TWorldDim, bool TCondensed> const size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::numCo = traits::NumCornersOfSCV static
Number of corners of scvf.
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::num_corners().
vGlobalGrad
template<typename TElem , int TWorldDim, bool TCondensed> MathVector<worldDim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vGlobalGrad[nsh] private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::global_grad().
vGloPos
template<typename TElem , int TWorldDim, bool TCondensed> MathVector<worldDim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vGloPos[numCo] private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::global_corner(), ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::global_corners(), and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::global_ip().
vLocalGrad
template<typename TElem , int TWorldDim, bool TCondensed> MathVector<dim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vLocalGrad[nsh] private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_grad(), and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_grad_vector().
vLocPos
template<typename TElem , int TWorldDim, bool TCondensed> MathVector<dim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vLocPos[numCo] private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_corner(), ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_corners(), and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::local_ip().
Vol
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::Vol private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::volume().
vShape
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::vShape[nsh] private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::shape(), and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::SCV::shape_vector().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv1_geom.h