ug4: ug::SchurPrecond< TAlgebra > Class Template Reference
ug::SchurPrecond< TAlgebra > Class Template Reference
operator implementation of the DD Schur complement solver
#include <schur_precond.h>
Public Types
typedef TAlgebra algebra_type
typedef IPreconditioner< TAlgebra > base_type
Base type.
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual SmartPtr< ILinearIterator< vector_type > > clone ()
clone
virtual std::string config_string () const
size_t num_global_skeleton ()
size_t num_local_skeleton ()
SchurPrecond ()
constructor
SchurPrecond (const SchurPrecond< TAlgebra > &parent)
void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
void set_dirichlet_solver (SmartPtr< ILinearOperatorInverse< vector_type > > dirichletSolver)
sets the Dirichlet solver (forward to Schur complement)
void set_schur_complement_operator (SmartPtr< SchurComplementOperator< algebra_type > > scop)
void set_skeleton_solver (SmartPtr< ISchurComplementInverse< algebra_type > > skeletonSolver)
sets the coarse problem solver
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
void set_damp (number factor)
sets the damping to a constant factor
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
DebugWritingObject ()
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
virtual const char * name () const
name of solver
virtual bool postprocess ()
cleans the operator
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
initializes the preconditioner
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
computes a new correction c = B*d
virtual bool supports_parallel () const
returns if parallel solving is supported
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
virtual void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void write_debug (const vector_type &vec, std::string filename)
virtual void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
Protected Attributes
SmartPtr< vector_type > m_aux_rhs [2]
SmartPtr< vector_type > m_aux_sol [2]
size_t m_myMasterSkeleton
size_t m_myTotalSkeleton
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_pA
SmartPtr< ILinearOperatorInverse< vector_type > > m_spDirichletSolver
Solver Dirichlet problems \(A_{II}\) (also used in Schur complement)
SmartPtr< SchurComplementOperator< algebra_type > > m_spSchurComplementOp
Local Schur complement for each subdomain.
SmartPtr< ISchurComplementInverse< TAlgebra > > m_spSkeletonSolver
Solver for coarse (skeleton) problem.
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Private Member Functions
bool check_requirements ()
bool create_and_init_local_schur_complement (SmartPtr< MatrixOperator< matrix_type, vector_type > > A, std::vector< schur_slice_desc_type > &skeletonMark)
void create_aux_vectors (const vector_type &d)
void get_skeleton_slicing (SmartPtr< MatrixOperator< matrix_type, vector_type > > A, std::vector< schur_slice_desc_type > &skeletonMark)
void init_skeleton_solver ()
void schur_solve_skeleton (vector_type &u_skeleton, const vector_type &f_skeleton)
void schur_solver_backward (vector_type &u_inner, vector_type &f_inner, vector_type &u_skeleton)
void schur_solver_forward (vector_type &u_inner, vector_type &f_inner)
Detailed Description
template<typename TAlgebra>
class ug::SchurPrecond< TAlgebra >
operator implementation of the DD Schur complement solver
This operator implements a Schur complement solver
Member Typedef Documentation
algebra_type
template<typename TAlgebra> typedef TAlgebra ug::SchurPrecond< TAlgebra >::algebra_type
base_type
template<typename TAlgebra> typedef IPreconditioner<TAlgebra> ug::SchurPrecond< TAlgebra >::base_type
Base type.
matrix_type
template<typename TAlgebra> typedef TAlgebra::matrix_type ug::SchurPrecond< TAlgebra >::matrix_type
vector_type
template<typename TAlgebra> typedef TAlgebra::vector_type ug::SchurPrecond< TAlgebra >::vector_type
Constructor & Destructor Documentation
SchurPrecond() [1/2]
template<typename TAlgebra > ug::SchurPrecond< TAlgebra >::SchurPrecond ()
constructor
References ug::SchurPrecond< TAlgebra >::m_aux_rhs, ug::SchurPrecond< TAlgebra >::m_aux_sol, ug::SchurPrecond< TAlgebra >::postprocess(), and SPNULL.
SchurPrecond() [2/2]
template<typename TAlgebra> ug::SchurPrecond< TAlgebra >::SchurPrecond (const SchurPrecond< TAlgebra > & parent) inline
References ug::SchurPrecond< TAlgebra >::m_spDirichletSolver, ug::SchurPrecond< TAlgebra >::m_spSchurComplementOp, and ug::SchurPrecond< TAlgebra >::m_spSkeletonSolver.
Member Function Documentation
check_requirements()
template<typename TAlgebra > bool ug::SchurPrecond< TAlgebra >::check_requirements () private
References ug::SchurPrecond< TAlgebra >::get_skeleton_slicing(), ug::SchurPrecond< TAlgebra >::m_spDirichletSolver, ug::SchurPrecond< TAlgebra >::m_spSkeletonSolver, and UG_LOG.
Referenced by ug::SchurPrecond< TAlgebra >::init_skeleton_solver(), ug::SchurPrecond< TAlgebra >::num_local_skeleton(), and ug::SchurPrecond< TAlgebra >::preprocess().
clone()
template<typename TAlgebra> virtual SmartPtr<ILinearIterator<vector_type> > ug::SchurPrecond< TAlgebra >::clone () inline virtual
clone
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References make_sp().
config_string()
template<typename TAlgebra> virtual std::string ug::SchurPrecond< TAlgebra >::config_string () const inline virtual
Reimplemented from ug::ILinearIterator< TAlgebra::vector_type >.
References ug::ConfigShift(), ug::SchurPrecond< TAlgebra >::m_spDirichletSolver, ug::SchurPrecond< TAlgebra >::m_spSkeletonSolver, and ug::SchurPrecond< TAlgebra >::name().
create_and_init_local_schur_complement()
template<typename TAlgebra > bool ug::SchurPrecond< TAlgebra >::create_and_init_local_schur_complement (SmartPtr< MatrixOperator< matrix_type, vector_type > > A, std::vector< schur_slice_desc_type > & skeletonMark) private
References ug::DebugWritingObject< TAlgebra >::debug_writer(), ug::SchurPrecond< TAlgebra >::init_skeleton_solver(), ug::SchurPrecond< TAlgebra >::m_spDirichletSolver, ug::SchurPrecond< TAlgebra >::m_spSchurComplementOp, make_sp(), SCHUR_PROFILE_BEGIN, ug::SchurDebug, UG_ASSERT, UG_CATCH_THROW, and UG_DLOG.
Referenced by ug::SchurPrecond< TAlgebra >::num_local_skeleton(), ug::SchurPrecond< TAlgebra >::postprocess(), and ug::SchurPrecond< TAlgebra >::preprocess().
create_aux_vectors()
template<typename TAlgebra > void ug::SchurPrecond< TAlgebra >::create_aux_vectors (const vector_type & d) private
References ug::SchurPrecond< TAlgebra >::m_aux_rhs, ug::SchurPrecond< TAlgebra >::m_aux_sol, ug::SchurPrecond< TAlgebra >::m_spSchurComplementOp, make_sp(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::SchurPrecond< TAlgebra >::schur_solver_forward(), ug::SchurDebug, ug::SD_INNER, ug::SD_SKELETON, ug::SlicingData< TVec, N >::slice_clone_without_values(), and UG_DLOG.
Referenced by ug::SchurPrecond< TAlgebra >::num_local_skeleton(), ug::SchurPrecond< TAlgebra >::preprocess(), and ug::SchurPrecond< TAlgebra >::step().
get_skeleton_slicing()
template<typename TAlgebra > void ug::SchurPrecond< TAlgebra >::get_skeleton_slicing (SmartPtr< MatrixOperator< matrix_type, vector_type > > A, std::vector< schur_slice_desc_type > & skeletonMark) private
References ug::SchurPrecond< TAlgebra >::m_myMasterSkeleton, ug::SchurPrecond< TAlgebra >::m_myTotalSkeleton, ug::MarkAllFromLayout(), ug::SchurPrecond< TAlgebra >::preprocess(), ug::SD_INNER, and ug::SD_SKELETON.
Referenced by ug::SchurPrecond< TAlgebra >::check_requirements(), ug::SchurPrecond< TAlgebra >::num_local_skeleton(), and ug::SchurPrecond< TAlgebra >::preprocess().
init_skeleton_solver()
template<typename TAlgebra > void ug::SchurPrecond< TAlgebra >::init_skeleton_solver () private
References ug::SchurPrecond< TAlgebra >::check_requirements(), ug::SchurPrecond< TAlgebra >::m_spSchurComplementOp, ug::SchurPrecond< TAlgebra >::m_spSkeletonSolver, SCHUR_PROFILE_BEGIN, UG_CATCH_THROW, and UG_THROW.
Referenced by ug::SchurPrecond< TAlgebra >::create_and_init_local_schur_complement(), ug::SchurPrecond< TAlgebra >::num_local_skeleton(), and ug::SchurPrecond< TAlgebra >::preprocess().
name()
template<typename TAlgebra> virtual const char* ug::SchurPrecond< TAlgebra >::name () const inline protected virtual
name of solver
Implements ug::IPreconditioner< TAlgebra >.
References ug::SchurPrecond< TAlgebra >::postprocess(), ug::SchurPrecond< TAlgebra >::preprocess(), and ug::SchurPrecond< TAlgebra >::step().
Referenced by ug::SchurPrecond< TAlgebra >::config_string().
num_global_skeleton()
template<typename TAlgebra> size_t ug::SchurPrecond< TAlgebra >::num_global_skeleton () inline
returns the size of the skeleton problem note that this is the global size, i.e. without counting slaves
References ug::SchurPrecond< TAlgebra >::m_myMasterSkeleton, ug::SchurPrecond< TAlgebra >::m_pA, and PCL_RO_SUM.
num_local_skeleton()
template<typename TAlgebra> size_t ug::SchurPrecond< TAlgebra >::num_local_skeleton () inline
returns the local skeleton size. note that the sum over these is bigger than num_global_skeleton, since this function includes also slaves
References ug::SchurPrecond< TAlgebra >::check_requirements(), ug::SchurPrecond< TAlgebra >::create_and_init_local_schur_complement(), ug::SchurPrecond< TAlgebra >::create_aux_vectors(), ug::SchurPrecond< TAlgebra >::get_skeleton_slicing(), ug::SchurPrecond< TAlgebra >::init_skeleton_solver(), ug::SchurPrecond< TAlgebra >::m_myTotalSkeleton, ug::SchurPrecond< TAlgebra >::schur_solve_skeleton(), ug::SchurPrecond< TAlgebra >::schur_solver_backward(), and ug::SchurPrecond< TAlgebra >::schur_solver_forward().
postprocess()
template<typename TAlgebra > bool ug::SchurPrecond< TAlgebra >::postprocess () protected virtual
cleans the operator
Implements ug::IPreconditioner< TAlgebra >.
References ug::SchurPrecond< TAlgebra >::create_and_init_local_schur_complement(), ug::SchurPrecond< TAlgebra >::m_aux_rhs, ug::SchurPrecond< TAlgebra >::m_aux_sol, and SPNULL.
Referenced by ug::SchurPrecond< TAlgebra >::name(), and ug::SchurPrecond< TAlgebra >::SchurPrecond().
preprocess()
template<typename TAlgebra > bool ug::SchurPrecond< TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) protected virtual
initializes the preconditioner
This method is used to initialize the preconditioner. Usually, here are performed computationally expensive operations, that should only be computed once for an underlying matrix (e.g. LU factorization), while the preconditioner will by applied (using 'step'-method) several times.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::SchurPrecond< TAlgebra >::check_requirements(), ug::SchurPrecond< TAlgebra >::create_and_init_local_schur_complement(), ug::SchurPrecond< TAlgebra >::create_aux_vectors(), ug::SchurPrecond< TAlgebra >::get_skeleton_slicing(), ug::SchurPrecond< TAlgebra >::init_skeleton_solver(), ug::SchurPrecond< TAlgebra >::m_pA, ug::SchurDebug, UG_CATCH_THROW, and UG_DLOG.
Referenced by ug::SchurPrecond< TAlgebra >::get_skeleton_slicing(), and ug::SchurPrecond< TAlgebra >::name().
schur_solve_skeleton()
template<typename TAlgebra > void ug::SchurPrecond< TAlgebra >::schur_solve_skeleton (vector_type & u_skeleton, const vector_type & f_skeleton) private
References ug::SchurPrecond< TAlgebra >::m_spSkeletonSolver, ug::PST_ADDITIVE, ug::PST_CONSISTENT, SCHUR_PROFILE_BEGIN, ug::SchurPrecond< TAlgebra >::schur_solver_backward(), ug::SchurDebug, UG_DLOG, UG_LOG, and UG_THROW.
Referenced by ug::SchurPrecond< TAlgebra >::num_local_skeleton(), ug::SchurPrecond< TAlgebra >::schur_solver_forward(), and ug::SchurPrecond< TAlgebra >::step().
schur_solver_backward()
template<typename TAlgebra > void ug::SchurPrecond< TAlgebra >::schur_solver_backward (vector_type & u_inner, vector_type & f_inner, vector_type & u_skeleton) private
References ug::SchurPrecond< TAlgebra >::m_spDirichletSolver, ug::SchurPrecond< TAlgebra >::m_spSchurComplementOp, SCHUR_PROFILE_BEGIN, ug::SchurDebug, ug::SD_INNER, ug::SD_SKELETON, ug::SchurPrecond< TAlgebra >::step(), UG_DLOG, and UG_LOG.
Referenced by ug::SchurPrecond< TAlgebra >::num_local_skeleton(), ug::SchurPrecond< TAlgebra >::schur_solve_skeleton(), and ug::SchurPrecond< TAlgebra >::step().
schur_solver_forward()
template<typename TAlgebra > void ug::SchurPrecond< TAlgebra >::schur_solver_forward (vector_type & u_inner, vector_type & f_inner) private
f_skeleton *= -1.0;
References ug::SchurPrecond< TAlgebra >::m_spDirichletSolver, SCHUR_PROFILE_BEGIN, ug::SchurPrecond< TAlgebra >::schur_solve_skeleton(), ug::SchurDebug, and UG_DLOG.
Referenced by ug::SchurPrecond< TAlgebra >::create_aux_vectors(), ug::SchurPrecond< TAlgebra >::num_local_skeleton(), and ug::SchurPrecond< TAlgebra >::step().
set_debug()
template<typename TAlgebra> void ug::SchurPrecond< TAlgebra >::set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter) inline virtual
set debug writer
Reimplemented from ug::DebugWritingObject< TAlgebra >.
References ug::DebugWritingObject< TAlgebra >::set_debug().
set_dirichlet_solver()
template<typename TAlgebra> void ug::SchurPrecond< TAlgebra >::set_dirichlet_solver (SmartPtr< ILinearOperatorInverse< vector_type > > dirichletSolver) inline
sets the Dirichlet solver (forward to Schur complement)
References ug::SchurPrecond< TAlgebra >::m_spDirichletSolver.
set_schur_complement_operator()
template<typename TAlgebra> void ug::SchurPrecond< TAlgebra >::set_schur_complement_operator (SmartPtr< SchurComplementOperator< algebra_type > > scop) inline
References ug::SchurPrecond< TAlgebra >::m_spSchurComplementOp.
set_skeleton_solver()
template<typename TAlgebra> void ug::SchurPrecond< TAlgebra >::set_skeleton_solver (SmartPtr< ISchurComplementInverse< algebra_type > > skeletonSolver) inline
sets the coarse problem solver
References ug::SchurPrecond< TAlgebra >::m_spSkeletonSolver.
step()
template<typename TAlgebra > bool ug::SchurPrecond< TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) protected virtual
computes a new correction c = B*d
This method computes a new correction c = B*d. It can only be called, when the preprocess has been done.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
[out] c correction
[in] d defect
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::SchurPrecond< TAlgebra >::create_aux_vectors(), ug::SlicingData< TVec, N >::get_vector_slice(), ug::SchurPrecond< TAlgebra >::m_aux_rhs, ug::SchurPrecond< TAlgebra >::m_aux_sol, ug::SchurPrecond< TAlgebra >::m_spDirichletSolver, ug::SchurPrecond< TAlgebra >::m_spSchurComplementOp, PROFILE_BEGIN, ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::PST_UNIQUE, ug::SchurPrecond< TAlgebra >::schur_solve_skeleton(), ug::SchurPrecond< TAlgebra >::schur_solver_backward(), ug::SchurPrecond< TAlgebra >::schur_solver_forward(), ug::SchurDebug, ug::SD_INNER, ug::SD_SKELETON, ug::SlicingData< TVec, N >::set_vector_slice(), ug::SlicingData< TVec, N >::subtract_vector_slice(), UG_ALGEBRA_CPP_TEMPLATE_DEFINE_ALL, UG_ASSERT, UG_CATCH_THROW, UG_DLOG, and UG_LOG.
Referenced by ug::SchurPrecond< TAlgebra >::name(), and ug::SchurPrecond< TAlgebra >::schur_solver_backward().
supports_parallel()
template<typename TAlgebra> virtual bool ug::SchurPrecond< TAlgebra >::supports_parallel () const inline protected virtual
returns if parallel solving is supported
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References ug::SchurPrecond< TAlgebra >::m_spDirichletSolver, and ug::SchurPrecond< TAlgebra >::m_spSkeletonSolver.
Member Data Documentation
m_aux_rhs
template<typename TAlgebra> SmartPtr<vector_type> ug::SchurPrecond< TAlgebra >::m_aux_rhs[2] protected
Referenced by ug::SchurPrecond< TAlgebra >::create_aux_vectors(), ug::SchurPrecond< TAlgebra >::postprocess(), ug::SchurPrecond< TAlgebra >::SchurPrecond(), and ug::SchurPrecond< TAlgebra >::step().
m_aux_sol
template<typename TAlgebra> SmartPtr<vector_type> ug::SchurPrecond< TAlgebra >::m_aux_sol[2] protected
Referenced by ug::SchurPrecond< TAlgebra >::create_aux_vectors(), ug::SchurPrecond< TAlgebra >::postprocess(), ug::SchurPrecond< TAlgebra >::SchurPrecond(), and ug::SchurPrecond< TAlgebra >::step().
m_myMasterSkeleton
template<typename TAlgebra> size_t ug::SchurPrecond< TAlgebra >::m_myMasterSkeleton protected
Referenced by ug::SchurPrecond< TAlgebra >::get_skeleton_slicing(), and ug::SchurPrecond< TAlgebra >::num_global_skeleton().
m_myTotalSkeleton
template<typename TAlgebra> size_t ug::SchurPrecond< TAlgebra >::m_myTotalSkeleton protected
Referenced by ug::SchurPrecond< TAlgebra >::get_skeleton_slicing(), and ug::SchurPrecond< TAlgebra >::num_local_skeleton().
m_pA
template<typename TAlgebra> SmartPtr<MatrixOperator<matrix_type, vector_type> > ug::SchurPrecond< TAlgebra >::m_pA protected
Referenced by ug::SchurPrecond< TAlgebra >::num_global_skeleton(), and ug::SchurPrecond< TAlgebra >::preprocess().
m_spDirichletSolver
template<typename TAlgebra> SmartPtr<ILinearOperatorInverse<vector_type> > ug::SchurPrecond< TAlgebra >::m_spDirichletSolver protected
Solver Dirichlet problems \(A_{II}\) (also used in Schur complement)
Referenced by ug::SchurPrecond< TAlgebra >::check_requirements(), ug::SchurPrecond< TAlgebra >::config_string(), ug::SchurPrecond< TAlgebra >::create_and_init_local_schur_complement(), ug::SchurPrecond< TAlgebra >::schur_solver_backward(), ug::SchurPrecond< TAlgebra >::schur_solver_forward(), ug::SchurPrecond< TAlgebra >::SchurPrecond(), ug::SchurPrecond< TAlgebra >::set_dirichlet_solver(), ug::SchurPrecond< TAlgebra >::step(), and ug::SchurPrecond< TAlgebra >::supports_parallel().
m_spSchurComplementOp
template<typename TAlgebra> SmartPtr<SchurComplementOperator<algebra_type> > ug::SchurPrecond< TAlgebra >::m_spSchurComplementOp protected
Local Schur complement for each subdomain.
Referenced by ug::SchurPrecond< TAlgebra >::create_and_init_local_schur_complement(), ug::SchurPrecond< TAlgebra >::create_aux_vectors(), ug::SchurPrecond< TAlgebra >::init_skeleton_solver(), ug::SchurPrecond< TAlgebra >::schur_solver_backward(), ug::SchurPrecond< TAlgebra >::SchurPrecond(), ug::SchurPrecond< TAlgebra >::set_schur_complement_operator(), and ug::SchurPrecond< TAlgebra >::step().
m_spSkeletonSolver
template<typename TAlgebra> SmartPtr< ISchurComplementInverse<TAlgebra> > ug::SchurPrecond< TAlgebra >::m_spSkeletonSolver protected
Solver for coarse (skeleton) problem.
Referenced by ug::SchurPrecond< TAlgebra >::check_requirements(), ug::SchurPrecond< TAlgebra >::config_string(), ug::SchurPrecond< TAlgebra >::init_skeleton_solver(), ug::SchurPrecond< TAlgebra >::schur_solve_skeleton(), ug::SchurPrecond< TAlgebra >::SchurPrecond(), ug::SchurPrecond< TAlgebra >::set_skeleton_solver(), and ug::SchurPrecond< TAlgebra >::supports_parallel().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/operator/preconditioner/schur/schur_precond.h
ugbase/lib_algebra/operator/preconditioner/schur/schur_precond.cpp