ug4: ug::ISchurComplementInverse< TAlgebra > Class Template Reference
ug::ISchurComplementInverse< TAlgebra > Class Template Reference abstract
#include <schur_complement_inverse_interface.h>
Public Member Functions
virtual bool apply (vector_type &u, const vector_type &f)=0
virtual bool apply_return_defect (vector_type &u, vector_type &f)=0
virtual std::string config_string () const =0
virtual bool init (SmartPtr< SchurComplementOperator< TAlgebra > > op)=0
virtual bool supports_parallel () const =0
virtual ~ISchurComplementInverse ()
Private Types
typedef TAlgebra::vector_type vector_type
Member Typedef Documentation
template<typename TAlgebra> typedef TAlgebra::vector_type ug::ISchurComplementInverse< TAlgebra >::vector_type private
Constructor & Destructor Documentation
template<typename TAlgebra> virtual ug::ISchurComplementInverse< TAlgebra >::~ISchurComplementInverse () inline virtual
References ug::ISchurComplementInverse< TAlgebra >::apply(), ug::ISchurComplementInverse< TAlgebra >::apply_return_defect(), ug::ISchurComplementInverse< TAlgebra >::config_string(), ug::ISchurComplementInverse< TAlgebra >::init(), and ug::ISchurComplementInverse< TAlgebra >::supports_parallel().
Member Function Documentation
template<typename TAlgebra> virtual bool ug::ISchurComplementInverse< TAlgebra >::apply (vector_type & u, const vector_type & f) pure virtual
Implemented in ug::SchurInverseWithAutoFullMatrix< TAlgebra >, ug::SchurInverseWithAGammaGamma< TAlgebra >, ug::SchurInverseWithFullMatrix< TAlgebra >, and ug::SchurInverseWithOperator< TAlgebra >.
Referenced by ug::ISchurComplementInverse< TAlgebra >::~ISchurComplementInverse().
template<typename TAlgebra> virtual bool ug::ISchurComplementInverse< TAlgebra >::apply_return_defect (vector_type & u, vector_type & f) pure virtual
Implemented in ug::SchurInverseWithAutoFullMatrix< TAlgebra >, ug::SchurInverseWithAGammaGamma< TAlgebra >, ug::SchurInverseWithFullMatrix< TAlgebra >, and ug::SchurInverseWithOperator< TAlgebra >.
Referenced by ug::ISchurComplementInverse< TAlgebra >::~ISchurComplementInverse().
template<typename TAlgebra> virtual std::string ug::ISchurComplementInverse< TAlgebra >::config_string () const pure virtual
Implemented in ug::SchurInverseWithAutoFullMatrix< TAlgebra >, ug::SchurInverseWithAGammaGamma< TAlgebra >, ug::SchurInverseWithFullMatrix< TAlgebra >, and ug::SchurInverseWithOperator< TAlgebra >.
Referenced by ug::ISchurComplementInverse< TAlgebra >::~ISchurComplementInverse().
template<typename TAlgebra> virtual bool ug::ISchurComplementInverse< TAlgebra >::init (SmartPtr< SchurComplementOperator< TAlgebra > > op) pure virtual
Implemented in ug::SchurInverseWithAutoFullMatrix< TAlgebra >, ug::SchurInverseWithAGammaGamma< TAlgebra >, ug::SchurInverseWithFullMatrix< TAlgebra >, and ug::SchurInverseWithOperator< TAlgebra >.
Referenced by ug::ISchurComplementInverse< TAlgebra >::~ISchurComplementInverse().
template<typename TAlgebra> virtual bool ug::ISchurComplementInverse< TAlgebra >::supports_parallel () const pure virtual
Implemented in ug::SchurInverseWithAutoFullMatrix< TAlgebra >, ug::SchurInverseWithAGammaGamma< TAlgebra >, ug::SchurInverseWithFullMatrix< TAlgebra >, and ug::SchurInverseWithOperator< TAlgebra >.
Referenced by ug::ISchurComplementInverse< TAlgebra >::~ISchurComplementInverse().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/preconditioner/schur/schur_complement_inverse_interface.h