ug4: ug::node_tree::GroupNode Class Reference
ug::node_tree::GroupNode Class Reference
You can group nodes using the GroupNode.
#include <group_node.h>
Public Member Functions
virtual void add_child (SPNode node)
virtual void clear ()
virtual SPNode get_child (int index)
virtual int num_children ()
virtual void remove_child (SPNode node)
virtual ~GroupNode ()
Public Member Functions inherited from ug::node_tree::Node
virtual ~Node ()
Public Member Functions inherited from ug::node_tree::Object
unsigned int getObjectCode ()
virtual ~Object ()
Static Public Member Functions
static SPGroupNode create ()
Protected Member Functions
GroupNode ()
Protected Member Functions inherited from ug::node_tree::Node
Node ()
Protected Member Functions inherited from ug::node_tree::Object
Object ()
Object (const Object &obj)
Protected Attributes
std::vector< SPNode > vChildren
Protected Attributes inherited from ug::node_tree::Object
unsigned int m_objectCode
Detailed Description
You can group nodes using the GroupNode.
...
Constructor & Destructor Documentation
~GroupNode()
ug::node_tree::GroupNode::~GroupNode () virtual
GroupNode()
ug::node_tree::GroupNode::GroupNode () protected
Referenced by create().
Member Function Documentation
add_child()
void ug::node_tree::GroupNode::add_child (SPNode node) virtual
References vChildren.
Referenced by ug::node_tree::CreateSubOctrees().
clear()
void ug::node_tree::GroupNode::clear () virtual
References vChildren.
create()
SPGroupNode ug::node_tree::GroupNode::create () static
References GroupNode(), ug::node_tree::Object::m_objectCode, and ug::node_tree::OC_GROUP_NODE.
get_child()
SPNode ug::node_tree::GroupNode::get_child (int index) virtual
References vChildren.
Referenced by ug::node_tree::Traverser::handle_group(), and ug::node_tree::Traverser_ProjectPoint::handle_group().
num_children()
int ug::node_tree::GroupNode::num_children () virtual
References vChildren.
Referenced by ug::node_tree::Traverser::handle_group(), and ug::node_tree::Traverser_ProjectPoint::handle_group().
remove_child()
void ug::node_tree::GroupNode::remove_child (SPNode node) virtual
References vChildren.
Member Data Documentation
vChildren
std::vector<SPNode> ug::node_tree::GroupNode::vChildren protected
Referenced by add_child(), clear(), get_child(), num_children(), and remove_child().
The documentation for this class was generated from the following files:
ugbase/common/node_tree/group_node.h
ugbase/common/node_tree/group_node.cpp