ug4: ug::IsInSubset Class Reference
ug::IsInSubset Class Reference
lib_grid » element_callbacks
Element callback that returns true, if an element is contained in a subset.
#include <subset_callbacks.h>
Public Member Functions
IsInSubset (const ISubsetHandler &sh, int subsetIndex)
bool operator() (Edge *e) const
bool operator() (Face *f) const
bool operator() (Vertex *v) const
bool operator() (Volume *v) const
Public Member Functions inherited from ug::ElementCallback
ElementCallback ()
virtual ~ElementCallback ()
Private Member Functions
template<class TElem >
bool callback (TElem *e) const
Private Attributes
const ISubsetHandler & m_sh
int m_si
Detailed Description
Element callback that returns true, if an element is contained in a subset.
Constructor & Destructor Documentation
IsInSubset()
ug::IsInSubset::IsInSubset (const ISubsetHandler & sh, int subsetIndex) inline
Member Function Documentation
callback()
template<class TElem > bool ug::IsInSubset::callback (TElem * e) const inline private
References ug::ISubsetHandler::get_subset_index(), m_sh, and m_si.
Referenced by operator()().
operator()() [1/4]
bool ug::IsInSubset::operator() (Edge * e) const inline virtual
Implements ug::ElementCallback.
References callback().
operator()() [2/4]
bool ug::IsInSubset::operator() (Face * f) const inline virtual
Implements ug::ElementCallback.
References callback().
operator()() [3/4]
bool ug::IsInSubset::operator() (Vertex * v) const inline virtual
Implements ug::ElementCallback.
References callback().
operator()() [4/4]
bool ug::IsInSubset::operator() (Volume * v) const inline virtual
Implements ug::ElementCallback.
References callback().
Member Data Documentation
m_sh
const ISubsetHandler& ug::IsInSubset::m_sh private
Referenced by callback().
m_si
int ug::IsInSubset::m_si private
Referenced by callback().
The documentation for this class was generated from the following file:
ugbase/lib_grid/callbacks/subset_callbacks.h