ug4: ug::MaximumDistIntegrand< TGridFunction > Class Template Reference
ug::MaximumDistIntegrand< TGridFunction > Class Template Reference
#include <integrate.h>
Public Member Functions
template<int elemDim>
void evaluate (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP)
returns the values of the integrand for a bunch of ips
double max ()
MaximumDistIntegrand (TGridFunction &gridFct, size_t cmp)
constructor
double min ()
void reset ()
virtual void set_subset (int si)
sets subset
virtual ~MaximumDistIntegrand ()
Public Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, MaximumDistIntegrand< TGridFunction > >
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)
Public Member Functions inherited from ug::IIntegrand< TData, TWorldDim >
int subset () const
returns the subset
virtual ~IIntegrand ()
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)=0
returns the values of the integrand for a bunch of ips
Static Public Attributes
static const int worldDim = TGridFunction::dim
world dimension of grid function
Static Public Attributes inherited from ug::StdIntegrand< number, TGridFunction::dim, MaximumDistIntegrand< TGridFunction > >
static const int worldDim
world dimension
Static Public Attributes inherited from ug::IIntegrand< TData, TWorldDim >
static const int worldDim = TWorldDim
world dimension
Protected Attributes
double m_max
double m_min
ScalarGridFunctionData< TGridFunction > m_scalarData
Protected Attributes inherited from ug::IIntegrand< TData, TWorldDim >
int m_si
subset
Additional Inherited Members
Public Types inherited from ug::StdIntegrand< number, TGridFunction::dim, MaximumDistIntegrand< TGridFunction > >
typedef number data_type
data type
Public Types inherited from ug::IIntegrand< TData, TWorldDim >
typedef TData data_type
data type
Protected Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, MaximumDistIntegrand< TGridFunction > >
MaximumDistIntegrand< TGridFunction > & getImpl ()
access to implementation
const MaximumDistIntegrand< TGridFunction > & getImpl () const
const access to implementation
Constructor & Destructor Documentation
MaximumDistIntegrand()
template<typename TGridFunction > ug::MaximumDistIntegrand< TGridFunction >::MaximumDistIntegrand (TGridFunction & gridFct, size_t cmp) inline
constructor
~MaximumDistIntegrand()
template<typename TGridFunction > virtual ug::MaximumDistIntegrand< TGridFunction >::~MaximumDistIntegrand () inline virtual
Member Function Documentation
evaluate()
template<typename TGridFunction > template<int elemDim> void ug::MaximumDistIntegrand< TGridFunction >::evaluate (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject * pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP) inline
returns the values of the integrand for a bunch of ips
Parameters
vValue[out] the value of the integrand at the ips
vGlobIP[in] global integration point positions
pElem[in] the element to integrate
vCornerCoords[in] corner coordinates of the element
vLocIP[in] local integration point positions
vJT[in] jacobian transposed at integration point
numIP[in] number of integration points
References ug::DoFRef(), ug::MaximumDistIntegrand< TGridFunction >::m_max, ug::MaximumDistIntegrand< TGridFunction >::m_min, ug::MaximumDistIntegrand< TGridFunction >::m_scalarData, ug::LocalDoFSet::num_sh(), ug::GridObject::reference_object_id(), UG_CATCH_THROW, and UG_COND_THROW.
max()
template<typename TGridFunction > double ug::MaximumDistIntegrand< TGridFunction >::max () inline
References ug::MaximumDistIntegrand< TGridFunction >::m_max.
min()
template<typename TGridFunction > double ug::MaximumDistIntegrand< TGridFunction >::min () inline
References ug::MaximumDistIntegrand< TGridFunction >::m_min.
Referenced by ug::GetMinimum().
reset()
template<typename TGridFunction > void ug::MaximumDistIntegrand< TGridFunction >::reset () inline
References ug::MaximumDistIntegrand< TGridFunction >::m_max, and ug::MaximumDistIntegrand< TGridFunction >::m_min.
set_subset()
template<typename TGridFunction > virtual void ug::MaximumDistIntegrand< TGridFunction >::set_subset (int si) inline virtual
sets subset
Reimplemented from ug::IIntegrand< TData, TWorldDim >.
References ug::MaximumDistIntegrand< TGridFunction >::m_scalarData, ug::IIntegrand< TData, TWorldDim >::set_subset(), and UG_COND_THROW.
Member Data Documentation
m_max
template<typename TGridFunction > double ug::MaximumDistIntegrand< TGridFunction >::m_max protected
Referenced by ug::MaximumDistIntegrand< TGridFunction >::evaluate(), ug::MaximumDistIntegrand< TGridFunction >::max(), and ug::MaximumDistIntegrand< TGridFunction >::reset().
m_min
template<typename TGridFunction > double ug::MaximumDistIntegrand< TGridFunction >::m_min protected
Referenced by ug::MaximumDistIntegrand< TGridFunction >::evaluate(), ug::MaximumDistIntegrand< TGridFunction >::min(), and ug::MaximumDistIntegrand< TGridFunction >::reset().
m_scalarData
template<typename TGridFunction > ScalarGridFunctionData<TGridFunction> ug::MaximumDistIntegrand< TGridFunction >::m_scalarData protected
Referenced by ug::MaximumDistIntegrand< TGridFunction >::evaluate(), and ug::MaximumDistIntegrand< TGridFunction >::set_subset().
worldDim
template<typename TGridFunction > const int ug::MaximumDistIntegrand< TGridFunction >::worldDim = TGridFunction::dim static
world dimension of grid function
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/integrate.h