ug4: ug::LocalShapeFunctionSetWrapper< TImpl > Class Template Reference
ug::LocalShapeFunctionSetWrapper< TImpl > Class Template Reference
wrapper class implementing the LocalShapeFunctionSet interface
Public Types
typedef ImplType::grad_type grad_type
Gradient type.
typedef ImplType::shape_type shape_type
Shape type.
Public Types inherited from ug::LocalShapeFunctionSet< TImpl::dim, TImpl::shape_type, TImpl::grad_type >
typedef TImpl::grad_type grad_type
Gradient type.
typedef MathVector< dim > position_type
Domain position type.
typedef TImpl::shape_type shape_type
Shape type.
Public Member Functions
virtual bool continuous () const
returns if space constructs continuous functions
virtual bool exact_position_available () const
virtual void grad (grad_type &g, size_t i, const MathVector< dim > &x) const
evaluates the gradient of the shape function
virtual void grads (grad_type *vGrad, const MathVector< dim > &x) const
returns all gradients evaluated at a point
virtual void grads (std::vector< grad_type > &vGrad, const MathVector< dim > &x) const
returns all gradients evaluated at a point
virtual void grads (std::vector< std::vector< grad_type > > &vvGrad, const std::vector< MathVector< dim > > &vLocPos) const
returns all gradients evaluated at a point
virtual const LocalDoF & local_dof (size_t dof) const
returns the DoFs storage
LocalShapeFunctionSetWrapper ()
constructor
virtual size_t num_dof (ReferenceObjectID roid) const
virtual size_t num_sh () const
virtual bool position (size_t i, MathVector< dim > &pos) const
local position of DoF i
virtual ReferenceObjectID roid () const
virtual shape_type shape (size_t i, const MathVector< dim > &x) const
evaluates the shape function
virtual void shape (shape_type &s, size_t i, const MathVector< dim > &x) const
evaluates the shape function
virtual void shapes (shape_type *vShape, const MathVector< dim > &x) const
returns all shape functions evaluated at a point
virtual void shapes (std::vector< shape_type > &vShape, const MathVector< dim > &x) const
returns all shape functions evaluated at a point
virtual void shapes (std::vector< std::vector< shape_type > > &vvShape, const std::vector< MathVector< dim > > &vLocPos) const
returns all shape functions evaluated at a point
Public Member Functions inherited from ug::LocalShapeFunctionSet< TImpl::dim, TImpl::shape_type, TImpl::grad_type >
virtual void grad (grad_type &g, size_t i, const MathVector< dim > &x) const =0
evaluates the gradient of the shape function
virtual void grads (std::vector< std::vector< grad_type > > &vvGrad, const std::vector< MathVector< dim > > &vLocPos) const =0
returns all gradients evaluated at a several points
virtual void shape (shape_type &shape, size_t i, const MathVector< dim > &x) const =0
evaluates the shape function
virtual void shapes (std::vector< std::vector< shape_type > > &vvShape, const std::vector< MathVector< dim > > &vLocPos) const =0
returns all shape functions evaluated at several point
virtual ~LocalShapeFunctionSet ()
virtual destructor
virtual void shapes (shape_type *vShape, const MathVector< dim > &x) const =0
returns all shape functions evaluated at a point
virtual void shapes (std::vector< shape_type > &vShape, const MathVector< dim > &x) const =0
returns all shape functions evaluated at a point
virtual void grads (grad_type *vGrad, const MathVector< dim > &x) const =0
returns all gradients evaluated at a point
virtual void grads (std::vector< grad_type > &vGrad, const MathVector< dim > &x) const =0
returns all gradients evaluated at a point
Public Member Functions inherited from ug::DimLocalDoFSet< TDim >
DimLocalDoFSet ()
constructor
bool operator!= (const DimLocalDoFSet< TDim > &v) const
inequality check
bool operator== (const DimLocalDoFSet< TDim > &v) const
equality check
virtual bool position (size_t i, MathVector< TDim > &pos) const =0
local position of DoF i
Public Member Functions inherited from ug::LocalDoFSet
int dim () const
returns the reference dimension
size_t num_dof (int d, size_t id) const
returns the number of DoFs on a sub-geometric object of dim and id
bool operator!= (const LocalDoFSet &v) const
inequality check
bool operator== (const LocalDoFSet &v) const
equality check
virtual ~LocalDoFSet ()
virtual destructor
size_t num_dof () const
Static Public Attributes
static const int dim = TImpl::dim
reference element dimension
Static Public Attributes inherited from ug::LocalShapeFunctionSet< TImpl::dim, TImpl::shape_type, TImpl::grad_type >
static const int dim
Dimension, where shape functions are defined.
Private Types
typedef TImpl ImplType
Implementation.
Detailed Description
template<typename TImpl>
class ug::LocalShapeFunctionSetWrapper< TImpl >
wrapper class implementing the LocalShapeFunctionSet interface
This class wrappes a class passed by the template argument into the virtual ILocalShapeFunctionSet interface and makes it thus usable in that context on the price of virtual functions.
Template Parameters
TImpl Implementation of a Local Shape Function Set
Member Typedef Documentation
template<typename TImpl > typedef ImplType::grad_type ug::LocalShapeFunctionSetWrapper< TImpl >::grad_type
Gradient type.
template<typename TImpl > typedef TImpl ug::LocalShapeFunctionSetWrapper< TImpl >::ImplType private
Implementation.
template<typename TImpl > typedef ImplType::shape_type ug::LocalShapeFunctionSetWrapper< TImpl >::shape_type
Shape type.
Constructor & Destructor Documentation
template<typename TImpl > ug::LocalShapeFunctionSetWrapper< TImpl >::LocalShapeFunctionSetWrapper () inline
constructor
Member Function Documentation
template<typename TImpl > virtual bool ug::LocalShapeFunctionSetWrapper< TImpl >::continuous () const inline virtual
returns if space constructs continuous functions
Implements ug::LocalShapeFunctionSet< TImpl::dim, TImpl::shape_type, TImpl::grad_type >.
Referenced by ug::LocalFiniteElementProvider::continuous().
template<typename TImpl > virtual bool ug::LocalShapeFunctionSetWrapper< TImpl >::exact_position_available () const inline virtual
Implements ug::DimLocalDoFSet< TDim >.
Referenced by ug::SubLocalDoFSet< TDim >::position().
template<typename TImpl > virtual void ug::LocalShapeFunctionSetWrapper< TImpl >::grad (grad_type & g, size_t i, const MathVector< dim > & x) const inline virtual
evaluates the gradient of the shape function
This function returns the gradient of Shape Function i at an element-local evaluation point.
Parameters
[in] i number of DoF
[in] x Position on reference element (evaluation point)
Returns
gradient at point
template<typename TImpl > virtual void ug::LocalShapeFunctionSetWrapper< TImpl >::grads (grad_type * vGrad, const MathVector< dim > & x) const inline virtual
returns all gradients evaluated at a point
This function returns the gradients of all Shape Functions at an element-local evaluation point in an array.
Parameters
[out] vGrad Vector of gradients
[in] x Position on reference element (evaluation point)
template<typename TImpl > virtual void ug::LocalShapeFunctionSetWrapper< TImpl >::grads (std::vector< grad_type > & vGrad, const MathVector< dim > & x) const inline virtual
returns all gradients evaluated at a point
This function returns the gradients of all Shape Functions at an element-local evaluation point in an array.
Parameters
[out] vGrad Vector of gradients
[in] x Position on reference element (evaluation point)
template<typename TImpl > virtual void ug::LocalShapeFunctionSetWrapper< TImpl >::grads (std::vector< std::vector< grad_type > > & vvGrad, const std::vector< MathVector< dim > > & vLocPos) const inline virtual
returns all gradients evaluated at a point
This function returns the gradients of all Shape Functions at an element-local evaluation point in an array.
Parameters
[out] vGrad Vector of gradients
[in] x Position on reference element (evaluation point)
template<typename TImpl > virtual const LocalDoF& ug::LocalShapeFunctionSetWrapper< TImpl >::local_dof (size_t dof) const inline virtual
returns the DoFs storage
Implements ug::LocalDoFSet.
Referenced by ug::SubLocalDoFSet< TDim >::SubLocalDoFSet().
template<typename TImpl > virtual size_t ug::LocalShapeFunctionSetWrapper< TImpl >::num_dof (ReferenceObjectID roid) const inline virtual
returns the total number of dofs on the finite element
Implements ug::LocalDoFSet.
template<typename TImpl > virtual size_t ug::LocalShapeFunctionSetWrapper< TImpl >::num_sh () const inline virtual
returns the total number of dofs on the finite element
Reimplemented from ug::LocalDoFSet.
template<typename TImpl > virtual bool ug::LocalShapeFunctionSetWrapper< TImpl >::position (size_t i, MathVector< dim > & pos) const inline virtual
local position of DoF i
This function returns the local position of a DoF if possible.
Parameters
[in] i number of DoF
[out] pos Position of DoF
Return values
true if position exists
false if no meaningful position available
template<typename TImpl > virtual ReferenceObjectID ug::LocalShapeFunctionSetWrapper< TImpl >::roid () const inline virtual
Implements ug::LocalDoFSet.
Referenced by ug::LocalFiniteElementProvider::create_dof_set(), ug::LocalFiniteElementProvider::create_lagrange_set(), ug::LocalFiniteElementProvider::create_mini_bubble_set(), ug::LocalFiniteElementProvider::create_set(), ug::LocalFiniteElementProvider::create_sub_dof_set(), ug::SubLocalDoFSet< TDim >::num_dof(), and ug::LocalFiniteElementProvider::register_set().
template<typename TImpl > virtual shape_type ug::LocalShapeFunctionSetWrapper< TImpl >::shape (size_t i, const MathVector< dim > & x) const inline virtual
evaluates the shape function
This function returns the value of Shape Function i at an element-local evaluation point.
Parameters
[in] i number of DoF
[in] x Position on reference element (evaluation point)
Returns
shape function value at point
Implements ug::LocalShapeFunctionSet< TImpl::dim, TImpl::shape_type, TImpl::grad_type >.
template<typename TImpl > virtual void ug::LocalShapeFunctionSetWrapper< TImpl >::shape (shape_type & s, size_t i, const MathVector< dim > & x) const inline virtual
evaluates the shape function
This function returns the value of Shape Function i at an element-local evaluation point.
Parameters
[in] i number of DoF
[in] x Position on reference element (evaluation point)
Returns
shape function value at point
References dim.
template<typename TImpl > virtual void ug::LocalShapeFunctionSetWrapper< TImpl >::shapes (shape_type * vShape, const MathVector< dim > & x) const inline virtual
returns all shape functions evaluated at a point
This function returns the values of all Shape Functions at an element-local evaluation point in an array.
Parameters
[out] vShape Vector of Shapes
[in] x Position on reference element (evaluation point)
template<typename TImpl > virtual void ug::LocalShapeFunctionSetWrapper< TImpl >::shapes (std::vector< shape_type > & vShape, const MathVector< dim > & x) const inline virtual
returns all shape functions evaluated at a point
This function returns the values of all Shape Functions at an element-local evaluation point in an array.
Parameters
[out] vShape Vector of Shapes
[in] x Position on reference element (evaluation point)
template<typename TImpl > virtual void ug::LocalShapeFunctionSetWrapper< TImpl >::shapes (std::vector< std::vector< shape_type > > & vvShape, const std::vector< MathVector< dim > > & vLocPos) const inline virtual
returns all shape functions evaluated at a point
This function returns the values of all Shape Functions at an element-local evaluation point in an array.
Parameters
[out] vShape Vector of Shapes
[in] x Position on reference element (evaluation point)
Member Data Documentation
template<typename TImpl > const int ug::LocalShapeFunctionSetWrapper< TImpl >::dim = TImpl::dim static
reference element dimension
The documentation for this class was generated from the following file:
ugbase/lib_disc/local_finite_element/local_finite_element_provider.cpp