ug4: ug::DoFDistributionInfoProvider Class Reference
ug::DoFDistributionInfoProvider Class Reference
#include <dof_distribution_info.h>
Public Member Functions
int dim (size_t fct) const
returns the dimension in which solution lives
int dim_subset (int si) const
returns dimension of subset
ConstSmartPtr< DoFDistributionInfo > dof_distribution_info () const
returns underlying info
DoFDistributionInfoProvider (ConstSmartPtr< DoFDistributionInfo > spDDI)
constructor
DoFDistributionInfoProvider ()
constructor
FunctionGroup fct_grp_by_name (const char *names) const
returns a function group to a string of functions
size_t fct_id_by_name (const char *name) const
returns fct id by name
ConstSmartPtr< FunctionPattern > function_pattern () const
returns the function pattern
bool is_def_everywhere (size_t fct) const
returns true if the discrete function nr_fct is defined everywhere
bool is_def_in_subset (size_t fct, int si) const
returns if a function is defined on a subset
size_t max_dofs (const int dim) const
returns the maximum number of dofs on grid objects in a dimension
size_t max_dofs (const GridBaseObjectId gbo) const
returns the maximum number of dofs on a grid base object type
size_t max_dofs (const ReferenceObjectID roid) const
returns the maximum number of dofs on reference object type
size_t max_dofs (const int dim, const int si) const
returns the maximum number of dofs in a dimension on a subset
size_t max_dofs (const GridBaseObjectId gbo, const int si) const
returns the maximum number of dofs on a grid base object on a subset
size_t max_fct_dofs (const size_t fct, int dim) const
returns the maximal number of dofs on a dimension for a function component
size_t max_fct_dofs (const size_t fct, const GridBaseObjectId gbo) const
returns the maximal number of dofs on a base object type for a function component
size_t max_fct_dofs (const size_t fct, const ReferenceObjectID roid) const
returns the number of dofs on a reference object for a function component
size_t max_fct_dofs (const size_t fct, const int dim, const int si) const
returns the maximum number of dofs in a dimension on a subset for a function component
size_t max_fct_dofs (const size_t fct, const GridBaseObjectId gbo, const int si) const
returns the maximum number of dofs on a grid base object on a subset for a function component
std::string name (size_t fct) const
returns the name of the discrete function nr_fct
std::vector< std::string > names () const
returns the names of the discrete functions
size_t num_dofs (const ReferenceObjectID roid, const int si) const
returns the number of dofs on a Reference Object on a subset
size_t num_fct () const
number of discrete functions on subset si
size_t num_fct (int si) const
number of discrete functions on subset si
size_t num_fct_dofs (const size_t fct, const ReferenceObjectID roid, const int si) const
returns the number of dofs on a Reference Object on a subset for a function component
int num_subsets () const
returns number of subsets
size_t offset (const ReferenceObjectID roid, const int si, const size_t fct) const
returns the offset for reference element, subset and function
void print_local_dof_statistic () const
prints statistic on local dof distribution
void print_local_dof_statistic (int verboseLev) const
prints informations
void set_dof_distribution_info (ConstSmartPtr< DoFDistributionInfo > spDDI)
sets the dd info
SubsetGroup subset_grp_by_name (const char *names) const
returns subset group by name
ConstSmartPtr< ISubsetHandler > subset_handler () const
returns the subset handler
int subset_id_by_name (const char *name) const
returns the subset id
std::string subset_name (int si) const
returns subset name
const LFEID & local_finite_element_id (size_t fct) const
const LFEID & lfeid (size_t fct) const
Protected Attributes
ConstSmartPtr< DoFDistributionInfo > m_spDDI
Function Pattern.
Constructor & Destructor Documentation
DoFDistributionInfoProvider() [1/2]
ug::DoFDistributionInfoProvider::DoFDistributionInfoProvider (ConstSmartPtr< DoFDistributionInfo > spDDI) inline
constructor
DoFDistributionInfoProvider() [2/2]
ug::DoFDistributionInfoProvider::DoFDistributionInfoProvider () inline
constructor
Member Function Documentation
dim()
int ug::DoFDistributionInfoProvider::dim (size_t fct) const inline
returns the dimension in which solution lives
Referenced by ug::DoFDistribution::_algebra_indices(), ug::DoFDistribution::_dof_indices(), ug::DoFDistribution::_indices(), ug::DoFDistribution::get_connections(), ug::ApproximationSpace< TDomain >::get_dim(), ug::DoFDistribution::reinit(), ug::DoFDistribution::sort_constrained_edges(), and ug::DoFDistribution::sort_constrained_faces().
dim_subset()
int ug::DoFDistributionInfoProvider::dim_subset (int si) const inline
returns dimension of subset
dof_distribution_info()
ConstSmartPtr<DoFDistributionInfo> ug::DoFDistributionInfoProvider::dof_distribution_info () const inline
returns underlying info
Referenced by ug::DoFDistribution::dof_count().
fct_grp_by_name()
FunctionGroup ug::DoFDistributionInfoProvider::fct_grp_by_name (const char * names) const
returns a function group to a string of functions
References ug::TokenizeString().
fct_id_by_name()
size_t ug::DoFDistributionInfoProvider::fct_id_by_name (const char * name) const inline
returns fct id by name
Referenced by ug::MarkForAdaption_AbsoluteGradientIndicator(), ug::MarkForAdaption_AbsoluteGradientJumpIndicator(), ug::MarkForAdaption_GradientIndicator(), ug::MarkForAdaption_GradientJump(), and ug::MarkForAdaption_GradientJumpIndicator().
function_pattern()
ConstSmartPtr<FunctionPattern> ug::DoFDistributionInfoProvider::function_pattern () const inline
returns the function pattern
Referenced by ug::Prolongate(), and ug::Restrict().
is_def_everywhere()
bool ug::DoFDistributionInfoProvider::is_def_everywhere (size_t fct) const inline
returns true if the discrete function nr_fct is defined everywhere
is_def_in_subset()
bool ug::DoFDistributionInfoProvider::is_def_in_subset (size_t fct, int si) const inline
returns if a function is defined on a subset
Referenced by ug::DoFDistribution::_inner_dof_indices(), ug::ActiveSet< TDomain, TAlgebra >::active_index(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::CheckDoFElem(), ug::collectStretchedElementIndices(), ug::DoFDistribution::constrained_edge_dof_indices(), ug::DoFDistribution::constrained_edge_indices(), ug::DoFDistribution::constrained_face_dof_indices(), ug::DoFDistribution::constrained_face_indices(), ug::DoFDistribution::constrained_vertex_dof_indices(), ug::DoFDistribution::constrained_vertex_indices(), ug::DoFDistribution::dof_indices(), ug::DoFDistribution::extract_inner_algebra_indices(), ug::ExtractAlgebraIndices2(), ug::ExtractPositionsElem(), ug::get_algebra_indices(), ug::DoFDistribution::indices(), ug::DoFDistribution::indices_on_vertex(), ug::DoFDistribution::inner_algebra_indices_for_fct(), ug::ProlongateElemwise(), and ug::RestrictElemwise().
lfeid()
const LFEID& ug::DoFDistributionInfoProvider::lfeid (size_t fct) const inline
returns the local finite element id of a function
Referenced by ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), ug::DoFDistribution::constrained_edge_dof_indices(), ug::DoFDistribution::constrained_face_dof_indices(), ug::DoFDistribution::dof_indices(), and ug::DoFDistribution::indices().
local_finite_element_id()
const LFEID& ug::DoFDistributionInfoProvider::local_finite_element_id (size_t fct) const inline
returns the local finite element id of a function
Referenced by ug::DirichletBoundary< TDomain, TAlgebra >::adjust_correction(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_defect(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_error(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_jacobian(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_linear(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_prolongation(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_restriction(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_rhs(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_solution(), ug::AssembleInjectionForP1Lagrange(), ug::CheckDoFElem(), ug::collectStretchedElementIndices(), ug::ExtractPositionsElem(), ug::MarkForAdaption_AbsoluteGradientIndicator(), ug::MarkForAdaption_AbsoluteGradientJumpIndicator(), ug::MarkForAdaption_GradientIndicator(), ug::MarkForAdaption_GradientJumpIndicator(), ug::OrderDirectionYForDofDist(), ug::OrderDirectionZForDofDist(), ug::OrderLexForDofDist(), ug::Prolongate(), ug::ProlongateElemwise(), ug::Restrict(), and ug::RestrictElemwise().
max_dofs() [1/5]
size_t ug::DoFDistributionInfoProvider::max_dofs (const int dim) const inline
returns the maximum number of dofs on grid objects in a dimension
Referenced by ug::DoFDistribution::_algebra_indices(), ug::DoFDistribution::_dof_indices(), ug::DoFDistribution::_indices(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_correction(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_defect(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_jacobian(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_linear(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_prolongation(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_restriction(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_rhs(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_solution(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), ug::AssembleInjectionByAverageOfChildren(), ug::CheckDoFPositions(), ug::AdaptionSurfaceGridFunction< TDomain >::copy_from_surface(), ug::AdaptionSurfaceGridFunction< TDomain >::copy_to_surface(), ug::CreateLevelIndexLayout(), ug::CreateSurfaceIndexLayout(), ug::DoFDistribution::dof_count(), ug::ExtractAlgebraIndices(), ug::ExtractPositions(), ug::DoFDistribution::get_connections(), ug::DoFIndexStorage::init_attachments(), ug::DoFDistribution::permute_indices(), ug::DoFDistribution::reinit(), ug::DoFDistribution::reinit_index_layout(), and ug::StdInjection< TDomain, TAlgebra >::set_identity_on_pure_surface().
max_dofs() [2/5]
size_t ug::DoFDistributionInfoProvider::max_dofs (const GridBaseObjectId gbo) const inline
returns the maximum number of dofs on a grid base object type
max_dofs() [3/5]
size_t ug::DoFDistributionInfoProvider::max_dofs (const ReferenceObjectID roid) const inline
returns the maximum number of dofs on reference object type
max_dofs() [4/5]
size_t ug::DoFDistributionInfoProvider::max_dofs (const int dim, const int si) const inline
returns the maximum number of dofs in a dimension on a subset
max_dofs() [5/5]
size_t ug::DoFDistributionInfoProvider::max_dofs (const GridBaseObjectId gbo, const int si) const inline
returns the maximum number of dofs on a grid base object on a subset
max_fct_dofs() [1/5]
size_t ug::DoFDistributionInfoProvider::max_fct_dofs (const size_t fct, int dim) const inline
returns the maximal number of dofs on a dimension for a function component
Referenced by ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), and ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction().
max_fct_dofs() [2/5]
size_t ug::DoFDistributionInfoProvider::max_fct_dofs (const size_t fct, const GridBaseObjectId gbo) const inline
returns the maximal number of dofs on a base object type for a function component
max_fct_dofs() [3/5]
size_t ug::DoFDistributionInfoProvider::max_fct_dofs (const size_t fct, const ReferenceObjectID roid) const inline
returns the number of dofs on a reference object for a function component
max_fct_dofs() [4/5]
size_t ug::DoFDistributionInfoProvider::max_fct_dofs (const size_t fct, const int dim, const int si) const inline
returns the maximum number of dofs in a dimension on a subset for a function component
max_fct_dofs() [5/5]
size_t ug::DoFDistributionInfoProvider::max_fct_dofs (const size_t fct, const GridBaseObjectId gbo, const int si) const inline
returns the maximum number of dofs on a grid base object on a subset for a function component
name()
std::string ug::DoFDistributionInfoProvider::name (size_t fct) const inline
returns the name of the discrete function nr_fct
Referenced by ug::IApproximationSpace::add(), and ug::OrderLexForDofDist().
names()
std::vector<std::string> ug::DoFDistributionInfoProvider::names () const inline
returns the names of the discrete functions
num_dofs()
size_t ug::DoFDistributionInfoProvider::num_dofs (const ReferenceObjectID roid, const int si) const inline
returns the number of dofs on a Reference Object on a subset
Referenced by ug::DoFDistribution::add(), ug::DoFDistribution::constrained_edge_dof_indices(), ug::DoFDistribution::constrained_face_dof_indices(), ug::DoFDistribution::constrained_vertex_dof_indices(), ug::DoFDistribution::dof_indices(), ug::DoFDistribution::extract_inner_algebra_indices(), ug::DoFDistribution::get_connections(), ug::DoFDistribution::inner_algebra_indices_for_fct(), ug::OrderDirectionYForDofDist(), ug::OrderDirectionZForDofDist(), and ug::OrderLexForDofDist().
num_fct() [1/2]
size_t ug::DoFDistributionInfoProvider::num_fct () const inline
number of discrete functions on subset si
Referenced by ug::DoFDistribution::_indices(), ug::ActiveSet< TDomain, TAlgebra >::active_index(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), ug::AssembleInjectionForP1Lagrange(), ug::CheckDoFElem(), ug::collectStretchedElementIndices(), ug::DoFDistribution::constrained_edge_indices(), ug::DoFDistribution::constrained_face_indices(), ug::DoFDistribution::constrained_vertex_indices(), ug::DoFCount::DoFCount(), ug::DoFDistribution::extract_inner_algebra_indices(), ug::ExtractAlgebraIndices2(), ug::ExtractPositionsElem(), ug::get_algebra_indices(), ug::DoFDistribution::indices(), ug::DoFDistribution::indices_on_vertex(), ug::OrderDirectionYForDofDist(), ug::OrderDirectionZForDofDist(), ug::OrderLexForDofDist(), ug::Prolongate(), ug::ProlongateElemwise(), ug::Restrict(), ug::RestrictElemwise(), and ug::DoFDistribution::sum_dof_count().
num_fct() [2/2]
size_t ug::DoFDistributionInfoProvider::num_fct (int si) const inline
number of discrete functions on subset si
num_fct_dofs()
size_t ug::DoFDistributionInfoProvider::num_fct_dofs (const size_t fct, const ReferenceObjectID roid, const int si) const inline
returns the number of dofs on a Reference Object on a subset for a function component
Referenced by ug::DoFDistribution::_inner_dof_indices(), ug::DoFDistribution::constrained_edge_dof_indices(), ug::DoFDistribution::constrained_face_dof_indices(), ug::DoFDistribution::constrained_vertex_dof_indices(), ug::DoFDistribution::dof_indices(), ug::DoFDistribution::extract_inner_algebra_indices(), ug::DoFDistribution::indices(), ug::DoFDistribution::indices_on_vertex(), ug::DoFDistribution::inner_algebra_indices_for_fct(), and ug::DoFDistribution::sum_dof_count().
num_subsets()
int ug::DoFDistributionInfoProvider::num_subsets () const inline
returns number of subsets
Referenced by ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), ug::CheckDoFElem(), ug::collectStretchedElementIndices(), ug::DoFCount::DoFCount(), ug::DoFDistribution::DoFDistribution(), ug::ExtractAlgebraIndices2(), ug::ExtractPositionsElem(), ug::DoFDistribution::get_connections(), ug::OrderDirectionYForDofDist(), ug::OrderDirectionZForDofDist(), ug::OrderLexForDofDist(), ug::ProlongateElemwise(), ug::DoFDistribution::reinit(), ug::RestrictElemwise(), and ug::StdInjection< TDomain, TAlgebra >::set_identity_on_pure_surface().
offset()
size_t ug::DoFDistributionInfoProvider::offset (const ReferenceObjectID roid, const int si, const size_t fct) const inline
returns the offset for reference element, subset and function
Referenced by ug::DoFDistribution::_inner_dof_indices(), ug::DoFDistribution::constrained_edge_dof_indices(), ug::DoFDistribution::constrained_edge_indices(), ug::DoFDistribution::constrained_face_dof_indices(), ug::DoFDistribution::constrained_face_indices(), ug::DoFDistribution::constrained_vertex_dof_indices(), ug::DoFDistribution::constrained_vertex_indices(), ug::DoFDistribution::dof_indices(), ug::DoFDistribution::extract_inner_algebra_indices(), ug::DoFDistribution::indices(), ug::DoFDistribution::indices_on_vertex(), and ug::DoFDistribution::inner_algebra_indices_for_fct().
print_local_dof_statistic() [1/2]
void ug::DoFDistributionInfoProvider::print_local_dof_statistic () const inline
prints statistic on local dof distribution
References print_local_dof_statistic().
Referenced by print_local_dof_statistic().
print_local_dof_statistic() [2/2]
void ug::DoFDistributionInfoProvider::print_local_dof_statistic (int verboseLev) const inline
prints informations
set_dof_distribution_info()
void ug::DoFDistributionInfoProvider::set_dof_distribution_info (ConstSmartPtr< DoFDistributionInfo > spDDI) inline
sets the dd info
subset_grp_by_name()
SubsetGroup ug::DoFDistributionInfoProvider::subset_grp_by_name (const char * names) const
returns subset group by name
subset_handler()
ConstSmartPtr<ISubsetHandler> ug::DoFDistributionInfoProvider::subset_handler () const inline
returns the subset handler
Referenced by ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::assemble_defect(), ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::assemble_jacobian(), ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::assemble_linear(), ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::assemble_mass_matrix(), ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::assemble_rhs(), ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::assemble_stiffness_matrix(), ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::calc_error(), ug::AssemblingTuner< TAlgebra >::collect_selected_elements(), ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::finish_timestep(), ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::finish_timestep_elem(), ug::get_algebra_indices(), ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::prepare_timestep(), and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::prepare_timestep_elem().
subset_id_by_name()
int ug::DoFDistributionInfoProvider::subset_id_by_name (const char * name) const inline
returns the subset id
References ug::FunctionPattern::names(), and ug::FunctionPattern::subset_grp_by_name().
subset_name()
std::string ug::DoFDistributionInfoProvider::subset_name (int si) const inline
returns subset name
Member Data Documentation
m_spDDI
ConstSmartPtr<DoFDistributionInfo> ug::DoFDistributionInfoProvider::m_spDDI protected
Function Pattern.
The documentation for this class was generated from the following files:
ugbase/lib_disc/dof_manager/dof_distribution_info.h
ugbase/lib_disc/dof_manager/dof_distribution_info.cpp