ug4: ug::GridFunctionComponentSpace< TGridFunction > Class Template Reference
ug::GridFunctionComponentSpace< TGridFunction > Class Template Reference
#include <metric_spaces.h>
Public Member Functions
virtual double distance2 (TGridFunction &uFine, TGridFunction &uCoarse)
GridFunctionComponentSpace (const char *fctNames)
GridFunctionComponentSpace (const char *fctNames, const char *ssNames)
virtual double norm2 (TGridFunction &uFine)
virtual ~GridFunctionComponentSpace ()
Public Member Functions inherited from ug::IComponentSpace< TGridFunction >
virtual std::string config_string () const
print config string
virtual double distance (TGridFunction &uFine, TGridFunction &uCoarse)
distance (for grid functions)
IComponentSpace (const char *fctNames)
IComponentSpace (const char *fctNames, const char *ssNames, int order)
IComponentSpace (const char *fctNames, int order)
virtual double norm (TGridFunction &uFine)
norm (for grid functions)
virtual ~IComponentSpace ()
Public Member Functions inherited from ug::IGridFunctionSpace< TGridFunction >
virtual double distance (vector_type &x, vector_type &y)
OVERRIDE distance (for vectors)
virtual double norm (vector_type &x)
OVERRIDE norm (for vectors)
virtual double scaling () const
virtual ~IGridFunctionSpace ()
DTOR.
Public Member Functions inherited from ug::IBanachSpace< TGridFunction::vector_type >
virtual ~IBanachSpace ()
Private Member Functions
template<typename TBaseElem >
void add_distance_values (number &sum, const TGridFunction &uFine, const TGridFunction &uCoarse, ConstSmartPtr< DoFDistribution > dd, int si, const FunctionGroup &fg) const
template<typename TBaseElem >
void add_norm_values (number &sum, const TGridFunction &uFine, ConstSmartPtr< DoFDistribution > dd, int si, const FunctionGroup &fg) const
Additional Inherited Members
Public Types inherited from ug::IComponentSpace< TGridFunction >
typedef IGridFunctionSpace< TGridFunction > base_type
Public Types inherited from ug::IGridFunctionSpace< TGridFunction >
typedef TGridFunction grid_function_type
typedef TGridFunction::vector_type vector_type
Static Public Attributes inherited from ug::IComponentSpace< TGridFunction >
static const int dim =TGridFunction::dim
Protected Attributes inherited from ug::IComponentSpace< TGridFunction >
std::string m_fctNames
int m_quadorder
const char * m_ssNames
Detailed Description
template<typename TGridFunction>
class ug::GridFunctionComponentSpace< TGridFunction >
Computes simple vector (2-)norm from grid function DoFs which belong to either of the subsets and either of the functions supplied in the constructor.
Constructor & Destructor Documentation
GridFunctionComponentSpace() [1/2]
template<typename TGridFunction > ug::GridFunctionComponentSpace< TGridFunction >::GridFunctionComponentSpace (const char * fctNames) inline
GridFunctionComponentSpace() [2/2]
template<typename TGridFunction > ug::GridFunctionComponentSpace< TGridFunction >::GridFunctionComponentSpace (const char * fctNames, const char * ssNames) inline
~GridFunctionComponentSpace()
template<typename TGridFunction > virtual ug::GridFunctionComponentSpace< TGridFunction >::~GridFunctionComponentSpace () inline virtual
Member Function Documentation
add_distance_values()
template<typename TGridFunction > template<typename TBaseElem > void ug::GridFunctionComponentSpace< TGridFunction >::add_distance_values (number & sum, const TGridFunction & uFine, const TGridFunction & uCoarse, ConstSmartPtr< DoFDistribution > dd, int si, const FunctionGroup & fg) const inline private
References ug::SurfaceView::ALL, ug::DoFRef(), ug::MultiGrid::get_child(), ug::SurfaceView::is_contained(), ug::MultiGrid::num_children(), ug::SurfaceView::SHADOW_RIM_COPY, ug::FunctionGroup::size(), and ug::SurfaceView::SURFACE_RIM.
add_norm_values()
template<typename TGridFunction > template<typename TBaseElem > void ug::GridFunctionComponentSpace< TGridFunction >::add_norm_values (number & sum, const TGridFunction & uFine, ConstSmartPtr< DoFDistribution > dd, int si, const FunctionGroup & fg) const inline private
References ug::SurfaceView::ALL, ug::DoFRef(), ug::MultiGrid::get_child(), ug::SurfaceView::is_contained(), ug::MultiGrid::num_children(), ug::SurfaceView::SHADOW_RIM_COPY, ug::FunctionGroup::size(), and ug::SurfaceView::SURFACE_RIM.
distance2()
template<typename TGridFunction > virtual double ug::GridFunctionComponentSpace< TGridFunction >::distance2 (TGridFunction & uFine, TGridFunction & uCoarse) inline virtual
Implements ug::IComponentSpace< TGridFunction >.
References ug::SubsetGroup::add(), ug::FunctionGroup::add(), ug::SubsetGroup::add_all(), pcl::ProcessCommunicator::allreduce(), ug::EDGE, ug::FACE, ug::IComponentSpace< TGridFunction >::m_fctNames, ug::IComponentSpace< TGridFunction >::m_ssNames, pcl::NumProcs(), PCL_RO_SUM, ug::SubsetGroup::size(), ug::TokenizeTrimString(), UG_CATCH_THROW, UG_COND_THROW, ug::VERTEX, and ug::VOLUME.
norm2()
template<typename TGridFunction > virtual double ug::GridFunctionComponentSpace< TGridFunction >::norm2 (TGridFunction & uFine) inline virtual
Implements ug::IComponentSpace< TGridFunction >.
References ug::SubsetGroup::add(), ug::FunctionGroup::add(), ug::SubsetGroup::add_all(), pcl::ProcessCommunicator::allreduce(), ug::EDGE, ug::FACE, ug::IComponentSpace< TGridFunction >::m_fctNames, ug::IComponentSpace< TGridFunction >::m_ssNames, pcl::NumProcs(), PCL_RO_SUM, ug::SubsetGroup::size(), ug::TokenizeTrimString(), UG_CATCH_THROW, ug::VERTEX, and ug::VOLUME.
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/metric_spaces.h