ug4: ug::LocalMatrix Class Reference
ug::LocalMatrix Class Reference
#include <local_algebra.h>
Public Types
typedef LocalMatrix this_type
own type
typedef number value_type
Entry type used by algebra.
Public Member Functions
void access_all ()
access all functions
void access_by_map (const FunctionIndexMapping &funcMap)
access only part of the functions using mapping (restrict functions)
void access_by_map (const FunctionIndexMapping &rowFuncMap, const FunctionIndexMapping &colFuncMap)
access only part of the functions using mapping (restrict functions)
const LocalIndices & get_col_indices () const
get current local indices
const LocalIndices & get_row_indices () const
get current local indices
LocalMatrix ()
Constructor.
LocalMatrix (const LocalIndices &rowInd, const LocalIndices &colInd)
Constructor.
size_t num_all_col_dof (size_t fct) const
returns the number of dofs for a function
size_t num_all_col_fct () const
returns the number of all functions
size_t num_all_row_dof (size_t fct) const
returns the number of dofs for a function
size_t num_all_row_fct () const
returns the number of all functions
size_t num_col_dof (size_t fct) const
returns the number of dofs for the currently accessible (restricted) function
size_t num_col_fct () const
returns the number of currently accessible (restricted) functions
size_t num_row_dof (size_t fct) const
returns the number of dofs for the currently accessible (restricted) function
size_t num_row_fct () const
returns the number of currently accessible (restricted) functions
number & operator() (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF)
access to (restricted) coupling (rowFct, rowDoF) x (colFct, colDoF)
number operator() (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF) const
const access to (restricted) coupling (rowFct, rowDoF) x (colFct, colDoF)
this_type & operator* (number val)
multiply all entries
this_type & operator*= (number val)
multiply matrix
this_type & operator+= (const this_type &rhs)
add matrix
this_type & operator-= (const this_type &rhs)
subtract matrix
this_type & operator= (number val)
set all entries
void resize (const LocalIndices &ind)
resize for same ind in row and column
void resize (const LocalIndices &rowInd, const LocalIndices &colInd)
resize for current local indices
this_type & scale_append (number s, const this_type &rhs)
add scaled matrix
number & value (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF)
access to coupling (rowFct, rowDoF) x (colFct, colDoF)
number value (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF) const
const access to coupling (rowFct, rowDoF) x (colFct, colDoF)
Protected Types
typedef DenseMatrix< VariableArray2< LocalCplMatrix * > > FctCplAccMatrix
typedef DenseMatrix< VariableArray2< LocalCplMatrix > > FctCplMatrix
typedef DenseMatrix< VariableArray2< value_type > > LocalCplMatrix
Protected Member Functions
void check_all_dof (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF) const
checks correct (dof1,dof2) index in debug mode
void check_all_fct (size_t rowFct, size_t colFct) const
checks correct (fct1,fct2) index in debug mode
void check_dof (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF) const
checks correct (dof1,dof2) index in debug mode
void check_fct (size_t rowFct, size_t colFct) const
checks correct (fct1,fct2) index in debug mode
Protected Attributes
FctCplMatrix m_CplMat
FctCplAccMatrix m_CplMatAcc
const FunctionIndexMapping * m_pColFuncMap
Column Access Mapping.
const LocalIndices * m_pColIndex
const FunctionIndexMapping * m_pRowFuncMap
Row Access Mapping.
const LocalIndices * m_pRowIndex
Member Typedef Documentation
FctCplAccMatrix
typedef DenseMatrix<VariableArray2<LocalCplMatrix*> > ug::LocalMatrix::FctCplAccMatrix protected
FctCplMatrix
typedef DenseMatrix<VariableArray2<LocalCplMatrix> > ug::LocalMatrix::FctCplMatrix protected
LocalCplMatrix
typedef DenseMatrix<VariableArray2<value_type> > ug::LocalMatrix::LocalCplMatrix protected
this_type
typedef LocalMatrix ug::LocalMatrix::this_type
own type
value_type
typedef number ug::LocalMatrix::value_type
Entry type used by algebra.
Constructor & Destructor Documentation
LocalMatrix() [1/2]
ug::LocalMatrix::LocalMatrix () inline
Constructor.
LocalMatrix() [2/2]
ug::LocalMatrix::LocalMatrix (const LocalIndices & rowInd, const LocalIndices & colInd) inline
Constructor.
References resize().
Member Function Documentation
access_all()
void ug::LocalMatrix::access_all () inline
access all functions
References m_CplMat, m_CplMatAcc, m_pColFuncMap, m_pColIndex, m_pRowFuncMap, m_pRowIndex, ug::LocalIndices::num_fct(), and ug::VariableArray2< T, T_ordering >::resize().
Referenced by resize().
access_by_map() [1/2]
void ug::LocalMatrix::access_by_map (const FunctionIndexMapping & funcMap) inline
access only part of the functions using mapping (restrict functions)
Referenced by ug::DataImport< TData, dim >::add_jacobian(), ug::IElemAssembleFuncs< TLeaf, TDomain >::do_add_jac_A_elem(), and ug::IElemAssembleFuncs< TLeaf, TDomain >::do_add_jac_M_elem().
access_by_map() [2/2]
void ug::LocalMatrix::access_by_map (const FunctionIndexMapping & rowFuncMap, const FunctionIndexMapping & colFuncMap) inline
access only part of the functions using mapping (restrict functions)
References m_CplMat, m_CplMatAcc, m_pColFuncMap, m_pRowFuncMap, and ug::FunctionIndexMapping::num_fct().
check_all_dof()
void ug::LocalMatrix::check_all_dof (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF) const inline protected
checks correct (dof1,dof2) index in debug mode
References check_all_fct(), num_all_col_dof(), num_all_row_dof(), and UG_LOCALALGEBRA_ASSERT.
Referenced by value().
check_all_fct()
void ug::LocalMatrix::check_all_fct (size_t rowFct, size_t colFct) const inline protected
checks correct (fct1,fct2) index in debug mode
References num_all_col_fct(), num_all_row_fct(), and UG_LOCALALGEBRA_ASSERT.
Referenced by check_all_dof().
check_dof()
void ug::LocalMatrix::check_dof (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF) const inline protected
checks correct (dof1,dof2) index in debug mode
References check_fct(), num_col_dof(), num_row_dof(), and UG_LOCALALGEBRA_ASSERT.
Referenced by operator()().
check_fct()
void ug::LocalMatrix::check_fct (size_t rowFct, size_t colFct) const inline protected
checks correct (fct1,fct2) index in debug mode
References num_col_fct(), num_row_fct(), and UG_LOCALALGEBRA_ASSERT.
Referenced by check_dof().
get_col_indices()
const LocalIndices& ug::LocalMatrix::get_col_indices () const inline
get current local indices
References m_pColIndex.
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_mat_to_global(), and ug::AddLocalMatrixToGlobal().
get_row_indices()
const LocalIndices& ug::LocalMatrix::get_row_indices () const inline
get current local indices
References m_pRowIndex.
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_mat_to_global(), and ug::AddLocalMatrixToGlobal().
num_all_col_dof()
size_t ug::LocalMatrix::num_all_col_dof (size_t fct) const inline
returns the number of dofs for a function
References m_CplMat, and ug::VariableArray2< T, T_ordering >::num_cols().
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_mat_to_global(), ug::AddLocalMatrixToGlobal(), and check_all_dof().
num_all_col_fct()
size_t ug::LocalMatrix::num_all_col_fct () const inline
returns the number of all functions
References m_CplMat, and ug::VariableArray2< T, T_ordering >::num_cols().
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_mat_to_global(), ug::AddLocalMatrixToGlobal(), and check_all_fct().
num_all_row_dof()
size_t ug::LocalMatrix::num_all_row_dof (size_t fct) const inline
returns the number of dofs for a function
References m_CplMat, and ug::VariableArray2< T, T_ordering >::num_rows().
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_mat_to_global(), ug::AddLocalMatrixToGlobal(), and check_all_dof().
num_all_row_fct()
size_t ug::LocalMatrix::num_all_row_fct () const inline
returns the number of all functions
References m_CplMat, and ug::VariableArray2< T, T_ordering >::num_rows().
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_mat_to_global(), ug::AddLocalMatrixToGlobal(), and check_all_fct().
num_col_dof()
size_t ug::LocalMatrix::num_col_dof (size_t fct) const inline
returns the number of dofs for the currently accessible (restricted) function
References m_CplMat, m_pColFuncMap, m_pRowFuncMap, and ug::VariableArray2< T, T_ordering >::num_cols().
Referenced by check_dof(), and ug::operator<<().
num_col_fct()
size_t ug::LocalMatrix::num_col_fct () const inline
returns the number of currently accessible (restricted) functions
References m_CplMatAcc, m_pColFuncMap, ug::VariableArray2< T, T_ordering >::num_cols(), and ug::FunctionIndexMapping::num_fct().
Referenced by check_fct(), and ug::operator<<().
num_row_dof()
size_t ug::LocalMatrix::num_row_dof (size_t fct) const inline
returns the number of dofs for the currently accessible (restricted) function
References m_CplMat, m_pRowFuncMap, and ug::VariableArray2< T, T_ordering >::num_rows().
Referenced by check_dof(), and ug::operator<<().
num_row_fct()
size_t ug::LocalMatrix::num_row_fct () const inline
returns the number of currently accessible (restricted) functions
References m_CplMatAcc, m_pRowFuncMap, ug::FunctionIndexMapping::num_fct(), and ug::VariableArray2< T, T_ordering >::num_rows().
Referenced by check_fct(), and ug::operator<<().
operator()() [1/2]
number& ug::LocalMatrix::operator() (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF) inline
access to (restricted) coupling (rowFct, rowDoF) x (colFct, colDoF)
References check_dof(), and m_CplMatAcc.
operator()() [2/2]
number ug::LocalMatrix::operator() (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF) const inline
const access to (restricted) coupling (rowFct, rowDoF) x (colFct, colDoF)
References check_dof(), and m_CplMatAcc.
operator*()
this_type& ug::LocalMatrix::operator* (number val) inline
multiply all entries
References operator*=().
operator*=()
this_type& ug::LocalMatrix::operator*= (number val) inline
multiply matrix
References m_CplMat, ug::VariableArray2< T, T_ordering >::num_cols(), and ug::VariableArray2< T, T_ordering >::num_rows().
Referenced by operator*().
operator+=()
this_type& ug::LocalMatrix::operator+= (const this_type & rhs) inline
add matrix
References m_CplMat, m_pColIndex, m_pRowIndex, ug::VariableArray2< T, T_ordering >::num_cols(), ug::VariableArray2< T, T_ordering >::num_rows(), and UG_LOCALALGEBRA_ASSERT.
operator-=()
this_type& ug::LocalMatrix::operator-= (const this_type & rhs) inline
subtract matrix
References m_CplMat, m_pColIndex, m_pRowIndex, ug::VariableArray2< T, T_ordering >::num_cols(), ug::VariableArray2< T, T_ordering >::num_rows(), and UG_LOCALALGEBRA_ASSERT.
operator=()
this_type& ug::LocalMatrix::operator= (number val) inline
set all entries
References m_CplMat, ug::VariableArray2< T, T_ordering >::num_cols(), and ug::VariableArray2< T, T_ordering >::num_rows().
resize() [1/2]
void ug::LocalMatrix::resize (const LocalIndices & ind) inline
resize for same ind in row and column
References resize().
Referenced by ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleJacobian(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleJacobian(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleLinear(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleLinear(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleMassMatrix(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleMassMatrix(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleStiffnessMatrix(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleStiffnessMatrix(), ug::ActiveSet< TDomain, TAlgebra >::lagrange_mat_inv_elem(), LocalMatrix(), and resize().
resize() [2/2]
void ug::LocalMatrix::resize (const LocalIndices & rowInd, const LocalIndices & colInd) inline
resize for current local indices
References access_all(), m_CplMat, m_CplMatAcc, m_pColIndex, m_pRowIndex, ug::VariableArray2< T, T_ordering >::num_cols(), ug::LocalIndices::num_dof(), ug::LocalIndices::num_fct(), ug::VariableArray2< T, T_ordering >::num_rows(), and ug::VariableArray2< T, T_ordering >::resize().
scale_append()
this_type& ug::LocalMatrix::scale_append (number s, const this_type & rhs) inline
add scaled matrix
References m_CplMat, m_pColIndex, m_pRowIndex, ug::MatScaleAppend(), ug::VariableArray2< T, T_ordering >::num_cols(), ug::VariableArray2< T, T_ordering >::num_rows(), s, and UG_LOCALALGEBRA_ASSERT.
Referenced by ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleLinear(), and ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleLinear().
value() [1/2]
number& ug::LocalMatrix::value (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF) inline
access to coupling (rowFct, rowDoF) x (colFct, colDoF)
References check_all_dof(), and m_CplMat.
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_mat_to_global(), and ug::AddLocalMatrixToGlobal().
value() [2/2]
number ug::LocalMatrix::value (size_t rowFct, size_t rowDoF, size_t colFct, size_t colDoF) const inline
const access to coupling (rowFct, rowDoF) x (colFct, colDoF)
References check_all_dof(), and m_CplMat.
Member Data Documentation
m_CplMat
FctCplMatrix ug::LocalMatrix::m_CplMat protected
Referenced by access_all(), access_by_map(), num_all_col_dof(), num_all_col_fct(), num_all_row_dof(), num_all_row_fct(), num_col_dof(), num_row_dof(), operator*=(), operator+=(), operator-=(), operator=(), resize(), scale_append(), and value().
m_CplMatAcc
FctCplAccMatrix ug::LocalMatrix::m_CplMatAcc protected
Referenced by access_all(), access_by_map(), num_col_fct(), num_row_fct(), operator()(), and resize().
m_pColFuncMap
const FunctionIndexMapping* ug::LocalMatrix::m_pColFuncMap protected
Column Access Mapping.
Referenced by access_all(), access_by_map(), num_col_dof(), and num_col_fct().
m_pColIndex
const LocalIndices* ug::LocalMatrix::m_pColIndex protected
Referenced by access_all(), get_col_indices(), operator+=(), operator-=(), resize(), and scale_append().
m_pRowFuncMap
const FunctionIndexMapping* ug::LocalMatrix::m_pRowFuncMap protected
Row Access Mapping.
Referenced by access_all(), access_by_map(), num_col_dof(), num_row_dof(), and num_row_fct().
m_pRowIndex
const LocalIndices* ug::LocalMatrix::m_pRowIndex protected
Referenced by access_all(), get_row_indices(), operator+=(), operator-=(), resize(), and scale_append().
The documentation for this class was generated from the following file:
ugbase/lib_disc/common/local_algebra.h