ug4: ug::LexOrdering< TAlgebra, TDomain, O_t > Class Template Reference
ug::LexOrdering< TAlgebra, TDomain, O_t > Class Template Reference
#include <lexorder.h>
Public Types
typedef IOrderingAlgorithm< TAlgebra, O_t > baseclass
typedef GridFunction< TDomain, TAlgebra > GridFunc_t
Grid function type for the solution.
typedef TAlgebra::matrix_type M_t
typedef std::pair< MathVector< TDomain::dim >, size_t > Position_t
Position attachment type.
typedef TAlgebra::vector_type V_t
Public Types inherited from ug::IOrderingAlgorithm< TAlgebra, O_t >
typedef TAlgebra::matrix_type M_t
typedef TAlgebra::vector_type V_t
Public Member Functions
void check ()
SmartPtr< IOrderingAlgorithm< TAlgebra, O_t > > clone ()
void compute ()
void init (M_t *)
void init (M_t *, const O_t &)
void init (M_t *, const V_t &, const O_t &)
void init (M_t *A, const V_t &V)
LexOrdering ()
LexOrdering (const LexOrdering< TAlgebra, TDomain, O_t > &parent)
clone constructor
virtual const char * name () const
O_t & ordering ()
void parse ()
void set_direction (const char *dir)
Public Member Functions inherited from ug::IOrderingAlgorithm< TAlgebra, O_t >
virtual void init (M_t *, const std::vector< size_t > &)=0
virtual void init (M_t *, const V_t &, const std::vector< size_t > &)=0
IOrderingAlgorithm ()
virtual ~IOrderingAlgorithm ()
Private Attributes
const char * m_dir
std::vector< Position_t > m_vPositions
M_t * mat
O_t o
Member Typedef Documentation
baseclass
template<typename TAlgebra , typename TDomain , typename O_t > typedef IOrderingAlgorithm<TAlgebra, O_t> ug::LexOrdering< TAlgebra, TDomain, O_t >::baseclass
GridFunc_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef GridFunction<TDomain, TAlgebra> ug::LexOrdering< TAlgebra, TDomain, O_t >::GridFunc_t
Grid function type for the solution.
M_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef TAlgebra::matrix_type ug::LexOrdering< TAlgebra, TDomain, O_t >::M_t
Position_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef std::pair<MathVector<TDomain::dim>, size_t> ug::LexOrdering< TAlgebra, TDomain, O_t >::Position_t
Position attachment type.
V_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef TAlgebra::vector_type ug::LexOrdering< TAlgebra, TDomain, O_t >::V_t
Constructor & Destructor Documentation
LexOrdering() [1/2]
template<typename TAlgebra , typename TDomain , typename O_t > ug::LexOrdering< TAlgebra, TDomain, O_t >::LexOrdering () inline
LexOrdering() [2/2]
template<typename TAlgebra , typename TDomain , typename O_t > ug::LexOrdering< TAlgebra, TDomain, O_t >::LexOrdering (const LexOrdering< TAlgebra, TDomain, O_t > & parent) inline
clone constructor
Member Function Documentation
check()
template<typename TAlgebra , typename TDomain , typename O_t > void ug::LexOrdering< TAlgebra, TDomain, O_t >::check () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::is_permutation(), ug::LexOrdering< TAlgebra, TDomain, O_t >::name(), ug::LexOrdering< TAlgebra, TDomain, O_t >::o, and UG_THROW.
clone()
template<typename TAlgebra , typename TDomain , typename O_t > SmartPtr<IOrderingAlgorithm<TAlgebra, O_t> > ug::LexOrdering< TAlgebra, TDomain, O_t >::clone () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References make_sp().
compute()
template<typename TAlgebra , typename TDomain , typename O_t > void ug::LexOrdering< TAlgebra, TDomain, O_t >::compute () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::LexOrdering< TAlgebra, TDomain, O_t >::m_dir, ug::LexOrdering< TAlgebra, TDomain, O_t >::m_vPositions, ug::LexOrdering< TAlgebra, TDomain, O_t >::mat, ug::LexOrdering< TAlgebra, TDomain, O_t >::name(), ug::LexOrdering< TAlgebra, TDomain, O_t >::o, UG_LOG, and UG_THROW.
init() [1/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::LexOrdering< TAlgebra, TDomain, O_t >::init (M_t *) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::LexOrdering< TAlgebra, TDomain, O_t >::name(), and UG_THROW.
init() [2/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::LexOrdering< TAlgebra, TDomain, O_t >::init (M_t * , const O_t &) inline
References ug::LexOrdering< TAlgebra, TDomain, O_t >::name(), and UG_THROW.
init() [3/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::LexOrdering< TAlgebra, TDomain, O_t >::init (M_t * , const V_t & , const O_t &) inline
References ug::LexOrdering< TAlgebra, TDomain, O_t >::name(), and UG_THROW.
init() [4/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::LexOrdering< TAlgebra, TDomain, O_t >::init (M_t * A, const V_t & V) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::GridFunction< TDomain, TAlgebra >::domain(), ug::ExtractPositions(), ug::LexOrdering< TAlgebra, TDomain, O_t >::m_dir, ug::LexOrdering< TAlgebra, TDomain, O_t >::m_vPositions, ug::LexOrdering< TAlgebra, TDomain, O_t >::mat, ug::LexOrdering< TAlgebra, TDomain, O_t >::name(), ug::LexOrdering< TAlgebra, TDomain, O_t >::o, UG_LOG, and UG_THROW.
name()
template<typename TAlgebra , typename TDomain , typename O_t > virtual const char* ug::LexOrdering< TAlgebra, TDomain, O_t >::name () const inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
Referenced by ug::LexOrdering< TAlgebra, TDomain, O_t >::check(), ug::LexOrdering< TAlgebra, TDomain, O_t >::compute(), ug::LexOrdering< TAlgebra, TDomain, O_t >::init(), and ug::LexOrdering< TAlgebra, TDomain, O_t >::parse().
ordering()
template<typename TAlgebra , typename TDomain , typename O_t > O_t& ug::LexOrdering< TAlgebra, TDomain, O_t >::ordering () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::LexOrdering< TAlgebra, TDomain, O_t >::o.
parse()
template<typename TAlgebra , typename TDomain , typename O_t > void ug::LexOrdering< TAlgebra, TDomain, O_t >::parse () inline
References ug::LexOrdering< TAlgebra, TDomain, O_t >::m_dir, ug::LexOrdering< TAlgebra, TDomain, O_t >::name(), and UG_THROW.
set_direction()
template<typename TAlgebra , typename TDomain , typename O_t > void ug::LexOrdering< TAlgebra, TDomain, O_t >::set_direction (const char * dir) inline
References ug::LexOrdering< TAlgebra, TDomain, O_t >::m_dir.
Member Data Documentation
m_dir
template<typename TAlgebra , typename TDomain , typename O_t > const char* ug::LexOrdering< TAlgebra, TDomain, O_t >::m_dir private
Referenced by ug::LexOrdering< TAlgebra, TDomain, O_t >::compute(), ug::LexOrdering< TAlgebra, TDomain, O_t >::init(), ug::LexOrdering< TAlgebra, TDomain, O_t >::parse(), and ug::LexOrdering< TAlgebra, TDomain, O_t >::set_direction().
m_vPositions
template<typename TAlgebra , typename TDomain , typename O_t > std::vector<Position_t> ug::LexOrdering< TAlgebra, TDomain, O_t >::m_vPositions private
Referenced by ug::LexOrdering< TAlgebra, TDomain, O_t >::compute(), and ug::LexOrdering< TAlgebra, TDomain, O_t >::init().
mat
template<typename TAlgebra , typename TDomain , typename O_t > M_t* ug::LexOrdering< TAlgebra, TDomain, O_t >::mat private
Referenced by ug::LexOrdering< TAlgebra, TDomain, O_t >::compute(), and ug::LexOrdering< TAlgebra, TDomain, O_t >::init().
o
template<typename TAlgebra , typename TDomain , typename O_t > O_t ug::LexOrdering< TAlgebra, TDomain, O_t >::o private
Referenced by ug::LexOrdering< TAlgebra, TDomain, O_t >::check(), ug::LexOrdering< TAlgebra, TDomain, O_t >::compute(), ug::LexOrdering< TAlgebra, TDomain, O_t >::init(), and ug::LexOrdering< TAlgebra, TDomain, O_t >::ordering().
The documentation for this class was generated from the following file:
ugbase/lib_disc/ordering_strategies/algorithms/lexorder.h