ug4: ug::ComPol_BoolMarker_RemoveMarks< TLayout > Class Template Reference
ug::ComPol_BoolMarker_RemoveMarks< TLayout > Class Template Reference
removes marks at extracting side, if no mark was received
#include <compol_boolmarker.h>
Public Types
typedef Layout::Element Element
typedef Layout::Type GeomObj
typedef Layout::Interface Interface
typedef Interface::const_iterator InterfaceIter
typedef TLayout Layout
Public Types inherited from pcl::ICommunicationPolicy< TLayout >
typedef Layout::Interface Interface
typedef TLayout Layout
Public Member Functions
virtual bool collect (ug::BinaryBuffer &buff, const Interface &interface)
writes 1 for marked and 0 for unmarked interface entries
ComPol_BoolMarker_RemoveMarks (BoolMarker &marker)
Construct the communication policy with a ug::BoolMarker.
virtual bool extract (ug::BinaryBuffer &buff, const Interface &interface)
reads marks from the given stream
virtual int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
Public Member Functions inherited from pcl::ICommunicationPolicy< TLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual ~ICommunicationPolicy ()
Protected Attributes
BoolMarker & m_rMarker
Detailed Description
template<class TLayout>
class ug::ComPol_BoolMarker_RemoveMarks< TLayout >
removes marks at extracting side, if no mark was received
Member Typedef Documentation
Element
template<class TLayout > typedef Layout::Element ug::ComPol_BoolMarker_RemoveMarks< TLayout >::Element
GeomObj
template<class TLayout > typedef Layout::Type ug::ComPol_BoolMarker_RemoveMarks< TLayout >::GeomObj
Interface
template<class TLayout > typedef Layout::Interface ug::ComPol_BoolMarker_RemoveMarks< TLayout >::Interface
InterfaceIter
template<class TLayout > typedef Interface::const_iterator ug::ComPol_BoolMarker_RemoveMarks< TLayout >::InterfaceIter
Layout
template<class TLayout > typedef TLayout ug::ComPol_BoolMarker_RemoveMarks< TLayout >::Layout
Constructor & Destructor Documentation
ComPol_BoolMarker_RemoveMarks()
template<class TLayout > ug::ComPol_BoolMarker_RemoveMarks< TLayout >::ComPol_BoolMarker_RemoveMarks (BoolMarker & marker) inline
Construct the communication policy with a ug::BoolMarker.
Member Function Documentation
collect()
template<class TLayout > virtual bool ug::ComPol_BoolMarker_RemoveMarks< TLayout >::collect (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
writes 1 for marked and 0 for unmarked interface entries
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::BoolMarker::is_marked(), ug::ComPol_BoolMarker_RemoveMarks< TLayout >::m_rMarker, and ug::BinaryBuffer::write().
extract()
template<class TLayout > virtual bool ug::ComPol_BoolMarker_RemoveMarks< TLayout >::extract (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
reads marks from the given stream
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::ComPol_BoolMarker_RemoveMarks< TLayout >::m_rMarker, ug::BinaryBuffer::read(), and ug::BoolMarker::unmark().
get_required_buffer_size()
template<class TLayout > virtual int ug::ComPol_BoolMarker_RemoveMarks< TLayout >::get_required_buffer_size (const Interface & interface) inline virtual
returns the size of the buffer in bytes, that will be required for interface-communication.
Determines the size of the buffer on which the extract and receive methods for the given interface will operate. If the buffer-size can't be calculated on both sides (sender and receiver) this method should return -1. This will lead to an additional communication step in which buffer-sizes will be exchanged. If the buffer-size can be calculated on both sides, it makes sense to do so, since this leads to less communication and overall improved performance. The buffer-size has to exactly match the size of required memory. Make sure that you completely fill the buffer during collect(...) and that you read all data during extract(...). The default implementation returns -1.
Reimplemented from pcl::ICommunicationPolicy< TLayout >.
Member Data Documentation
m_rMarker
template<class TLayout > BoolMarker& ug::ComPol_BoolMarker_RemoveMarks< TLayout >::m_rMarker protected
Referenced by ug::ComPol_BoolMarker_RemoveMarks< TLayout >::collect(), and ug::ComPol_BoolMarker_RemoveMarks< TLayout >::extract().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/util/compol_boolmarker.h