ug4: ug::CompositeConvCheck< TVector, TDomain > Class Template Reference
ug::CompositeConvCheck< TVector, TDomain > Class Template Reference
#include <composite_conv_check.h>
Classes
struct CmpInfo
struct NativCmpInfo
Public Member Functions
number avg_rate () const
virtual SmartPtr< IConvergenceCheck< TVector > > clone ()
clones this instance
virtual std::string config_string () const
returns information about configuration parameters
number defect () const
returns the current defect
void disable_rest_check ()
disables rest check
int get_offset () const
output
bool iteration_ended ()
bool post ()
void print_line (std::string line)
prints a line using prefixes
number rate () const
number reduction () const
void set_adaptive (bool adapt)
whether or not the underlying approximatioon space is adaptive
void set_all_component_check (const number minDefect, const number relReduction)
sets check for all components in approximation space
void set_info (std::string info)
sets info string
void set_level (int level)
set level of grid, where defect vectors come from
void set_maximum_steps (int maxSteps)
sets maximum number of iteration steps
void set_name (std::string name)
sets the name of the iteration
void set_offset (int offset)
sets the number of spaces printed before output information
void set_rest_check (number minDefect, number relReduction)
sets default values for non-explicitly specified cmps
void set_symbol (char symbol)
sets the symbol used for output
void set_time_measurement (bool yesOrNo)
enables time measurement
void set_verbose (bool level)
sets if verbose
void start (const TVector &d)
computes the start defect and set it
void start_defect (number initialDefect)
defect control
int step () const
information about current status
void update (const TVector &d)
computes the defect and sets it a the next defect value
void update_defect (number newDefect)
sets the update for the current defect
virtual ~CompositeConvCheck ()
destructor
CompositeConvCheck (SmartPtr< ApproximationSpace< TDomain > > approx)
CompositeConvCheck (SmartPtr< ApproximationSpace< TDomain > > spApproxSpace, int maxSteps, number minDefect, number relReduction)
void set_component_check (const std::string &vFctName, const std::vector< number > &vMinDefect, const std::vector< number > &vRelReduction)
void set_component_check (const std::vector< std::string > &vFctName, const std::vector< number > &vMinDefect, const std::vector< number > &vRelReduction)
void set_component_check (const std::vector< std::string > &vFctName, const number minDefect, const number relReduction)
void set_component_check (const std::string &fctName, const number minDefect, const number relReduction)
void set_group_check (const std::vector< std::string > &vFctName, const number minDefect, const number relReduction)
void set_group_check (const std::string &fctNames, const number minDefect, const number relReduction)
Public Member Functions inherited from ug::IConvergenceCheck< TVector >
virtual ~IConvergenceCheck ()
virtual destructor
Protected Member Functions
number defect_all () const
returns defect for all components
template<typename TBaseElem >
void extract_dof_indices (ConstSmartPtr< DoFDistribution > dd)
extracts multi-indices for a fct-comp on a element type
void extract_dof_indices (ConstSmartPtr< DoFDistribution > dd)
extracts multi-indices from dof distribution
const std::string & fctName (size_t i)
number initial_defect_all () const
returns initial defect for all components
bool is_valid_number (number value)
number last_defect_all () const
returns last defect for all components
number norm (const TVector &vec, const std::vector< DoFIndex > &index)
calculates the 2-norm of the entries of the vector vec specified by index
void print_offset ()
void update_rest_check ()
Protected Attributes
bool m_bAdaptive
adaptivity flag
bool m_bCheckRest
default Values
bool m_bTimeMeas
enables time measurement
std::vector< CmpInfo > m_CmpInfo
infos for each component
int m_currentStep
current step
std::string m_info
info for iteration (e.g. preconditioner type)
int m_maxSteps
maximum number of steps to be performed
std::string m_name
name of iteration
size_t m_numAllDoFs
int m_offset
number of spaces inserted before output
number m_restMinDefect
number m_restRelReduction
SmartPtr< ApproximationSpace< TDomain > > m_spApprox
ApproxSpace.
Stopwatch m_stopwatch
a stopwatch
char m_symbol
symbol for output appearance
bool m_verbose
verbose level
std::vector< NativCmpInfo > m_vNativCmpInfo
info on natural components
Detailed Description
template<class TVector, class TDomain>
class ug::CompositeConvCheck< TVector, TDomain >
CompositeConvCheck
This is an implementation of the convergence check interface, that makes it possible to define required defect reductions on the individual functions constituting the overall solution.
Constructor & Destructor Documentation
template<class TVector , class TDomain > ug::CompositeConvCheck< TVector, TDomain >::CompositeConvCheck (SmartPtr< ApproximationSpace< TDomain > > approx)
constructors
References ug::CompositeConvCheck< TVector, TDomain >::set_level(), and ug::GridLevel::TOP.
template<class TVector , class TDomain > ug::CompositeConvCheck< TVector, TDomain >::CompositeConvCheck (SmartPtr< ApproximationSpace< TDomain > > spApproxSpace, int maxSteps, number minDefect, number relReduction)
constructors
References ug::CompositeConvCheck< TVector, TDomain >::set_level(), and ug::GridLevel::TOP.
template<class TVector , class TDomain > virtual ug::CompositeConvCheck< TVector, TDomain >::~CompositeConvCheck () inline virtual
destructor
References ug::CompositeConvCheck< TVector, TDomain >::set_level().
Member Function Documentation
template<class TVector , class TDomain > number ug::CompositeConvCheck< TVector, TDomain >::avg_rate () const inline virtual
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::defect_all(), ug::CompositeConvCheck< TVector, TDomain >::initial_defect_all(), and ug::CompositeConvCheck< TVector, TDomain >::m_currentStep.
template<class TVector , class TDomain > SmartPtr< IConvergenceCheck< TVector > > ug::CompositeConvCheck< TVector, TDomain >::clone () virtual
clones this instance
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::m_spApprox, and ug::CompositeConvCheck< TVector, TDomain >::set_component_check().
Referenced by ug::CompositeConvCheck< TVector, TDomain >::set_adaptive().
template<class TVector , class TDomain > virtual std::string ug::CompositeConvCheck< TVector, TDomain >::config_string () const inline virtual
returns information about configuration parameters
this should return necessary information about parameters and possibly calling config_string of subcomponents.
Returns
std::string necessary information about configuration parameters
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::is_valid_number(), ug::CompositeConvCheck< TVector, TDomain >::m_CmpInfo, ug::CompositeConvCheck< TVector, TDomain >::m_maxSteps, and ug::CompositeConvCheck< TVector, TDomain >::print_offset().
template<class TVector , class TDomain > number ug::CompositeConvCheck< TVector, TDomain >::defect () const inline virtual
returns the current defect
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::defect_all().
Referenced by ug::CompositeConvCheck< TVector, TDomain >::defect_all(), ug::CompositeConvCheck< TVector, TDomain >::initial_defect_all(), and ug::CompositeConvCheck< TVector, TDomain >::last_defect_all().
template<class TVector , class TDomain > number ug::CompositeConvCheck< TVector, TDomain >::defect_all () const inline protected
returns defect for all components
References ug::CompositeConvCheck< TVector, TDomain >::NativCmpInfo::currDefect, and ug::CompositeConvCheck< TVector, TDomain >::defect().
Referenced by ug::CompositeConvCheck< TVector, TDomain >::avg_rate(), ug::CompositeConvCheck< TVector, TDomain >::defect(), ug::CompositeConvCheck< TVector, TDomain >::rate(), and ug::CompositeConvCheck< TVector, TDomain >::reduction().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check () inline
disables rest check
References ug::CompositeConvCheck< TVector, TDomain >::fctName(), ug::CompositeConvCheck< TVector, TDomain >::iteration_ended(), ug::CompositeConvCheck< TVector, TDomain >::m_bCheckRest, ug::CompositeConvCheck< TVector, TDomain >::post(), ug::CompositeConvCheck< TVector, TDomain >::set_all_component_check(), ug::CompositeConvCheck< TVector, TDomain >::set_component_check(), ug::CompositeConvCheck< TVector, TDomain >::set_group_check(), ug::CompositeConvCheck< TVector, TDomain >::start(), ug::CompositeConvCheck< TVector, TDomain >::start_defect(), ug::CompositeConvCheck< TVector, TDomain >::update(), ug::CompositeConvCheck< TVector, TDomain >::update_defect(), and ug::CompositeConvCheck< TVector, TDomain >::update_rest_check().
template<class TVector , class TDomain > template<typename TBaseElem > void ug::CompositeConvCheck< TVector, TDomain >::extract_dof_indices (ConstSmartPtr< DoFDistribution > dd) protected
extracts multi-indices for a fct-comp on a element type
References ug::SurfaceView::ALL, ug::MultiGrid::get_child(), ug::SurfaceView::is_contained(), ug::CompositeConvCheck< TVector, TDomain >::m_vNativCmpInfo, ug::MultiGrid::num_children(), ug::SurfaceView::SHADOW_RIM_COPY, and ug::SurfaceView::SURFACE_RIM.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::fctName(), and ug::CompositeConvCheck< TVector, TDomain >::set_level().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::extract_dof_indices (ConstSmartPtr< DoFDistribution > dd) protected
extracts multi-indices from dof distribution
References ug::EDGE, ug::FACE, ug::CompositeConvCheck< TVector, TDomain >::m_numAllDoFs, ug::CompositeConvCheck< TVector, TDomain >::m_vNativCmpInfo, ug::CompositeConvCheck< TVector, TDomain >::norm(), ug::VERTEX, and ug::VOLUME.
template<class TVector , class TDomain > const std::string& ug::CompositeConvCheck< TVector, TDomain >::fctName (size_t i) inline protected
References ug::CompositeConvCheck< TVector, TDomain >::extract_dof_indices(), ug::CompositeConvCheck< TVector, TDomain >::m_CmpInfo, and ug::CompositeConvCheck< TVector, TDomain >::norm().
Referenced by ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check().
template<class TVector , class TDomain > int ug::CompositeConvCheck< TVector, TDomain >::get_offset () const inline virtual
output
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::m_offset.
template<class TVector , class TDomain > number ug::CompositeConvCheck< TVector, TDomain >::initial_defect_all () const inline protected
returns initial defect for all components
References ug::CompositeConvCheck< TVector, TDomain >::defect(), and ug::CompositeConvCheck< TVector, TDomain >::NativCmpInfo::initDefect.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::avg_rate(), and ug::CompositeConvCheck< TVector, TDomain >::reduction().
template<class TVector , class TDomain > bool ug::CompositeConvCheck< TVector, TDomain >::is_valid_number (number value) protected
Referenced by ug::CompositeConvCheck< TVector, TDomain >::config_string(), ug::CompositeConvCheck< TVector, TDomain >::iteration_ended(), and ug::CompositeConvCheck< TVector, TDomain >::post().
template<class TVector , class TDomain > bool ug::CompositeConvCheck< TVector, TDomain >::iteration_ended () virtual
iteration_ended
Checks if the iteration must be ended. This can be due to convergence or divergence.
Returns
true if iteration ended false if iteration can and must be continued until convergence
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::currDefect, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::initDefect, ug::CompositeConvCheck< TVector, TDomain >::is_valid_number(), ug::CompositeConvCheck< TVector, TDomain >::m_CmpInfo, ug::CompositeConvCheck< TVector, TDomain >::m_maxSteps, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::minDefect, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::relReduction, and ug::CompositeConvCheck< TVector, TDomain >::step().
Referenced by ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check().
template<class TVector , class TDomain > number ug::CompositeConvCheck< TVector, TDomain >::last_defect_all () const inline protected
returns last defect for all components
References ug::CompositeConvCheck< TVector, TDomain >::defect(), and ug::CompositeConvCheck< TVector, TDomain >::NativCmpInfo::lastDefect.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::rate().
template<class TVector , class TDomain > number ug::CompositeConvCheck< TVector, TDomain >::norm (const TVector & vec, const std::vector< DoFIndex > & index) protected
calculates the 2-norm of the entries of the vector vec specified by index
References pcl::ProcessCommunicator::allreduce(), ug::DoFRef(), PCL_RO_SUM, ug::PST_UNIQUE, and UG_THROW.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::extract_dof_indices(), ug::CompositeConvCheck< TVector, TDomain >::fctName(), ug::CompositeConvCheck< TVector, TDomain >::start(), and ug::CompositeConvCheck< TVector, TDomain >::update().
template<class TVector , class TDomain > bool ug::CompositeConvCheck< TVector, TDomain >::post () virtual
post
post-processes the iteration. Some informative outputs of the status of the iteration after finishing the iteration can be placed here
Returns
true if iteration was successful false if iteration did not lead to a satisfying result
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::currDefect, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::initDefect, ug::CompositeConvCheck< TVector, TDomain >::is_valid_number(), ug::CompositeConvCheck< TVector, TDomain >::m_bTimeMeas, ug::CompositeConvCheck< TVector, TDomain >::m_CmpInfo, ug::CompositeConvCheck< TVector, TDomain >::m_maxSteps, ug::CompositeConvCheck< TVector, TDomain >::m_stopwatch, ug::CompositeConvCheck< TVector, TDomain >::m_symbol, ug::CompositeConvCheck< TVector, TDomain >::m_verbose, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::minDefect, ug::Stopwatch::ms(), ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::name, ug::CompositeConvCheck< TVector, TDomain >::print_offset(), ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::relReduction, ug::repeat(), ug::CompositeConvCheck< TVector, TDomain >::step(), ug::Stopwatch::stop(), and UG_LOG.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::print_line (std::string line) virtual
prints a line using prefixes
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::print_offset(), and UG_LOG.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::set_adaptive().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::print_offset () protected
References ug::CompositeConvCheck< TVector, TDomain >::m_offset, ug::CompositeConvCheck< TVector, TDomain >::m_symbol, ug::repeat(), and UG_LOG.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::config_string(), ug::CompositeConvCheck< TVector, TDomain >::post(), ug::CompositeConvCheck< TVector, TDomain >::print_line(), ug::CompositeConvCheck< TVector, TDomain >::start(), and ug::CompositeConvCheck< TVector, TDomain >::update().
template<class TVector , class TDomain > number ug::CompositeConvCheck< TVector, TDomain >::rate () const inline virtual
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::defect_all(), and ug::CompositeConvCheck< TVector, TDomain >::last_defect_all().
template<class TVector , class TDomain > number ug::CompositeConvCheck< TVector, TDomain >::reduction () const inline virtual
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::defect_all(), and ug::CompositeConvCheck< TVector, TDomain >::initial_defect_all().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_adaptive (bool adapt) inline
whether or not the underlying approximatioon space is adaptive
References ug::CompositeConvCheck< TVector, TDomain >::clone(), ug::CompositeConvCheck< TVector, TDomain >::m_bAdaptive, and ug::CompositeConvCheck< TVector, TDomain >::print_line().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_all_component_check (const number minDefect, const number relReduction)
sets check for all components in approximation space
References ug::CompositeConvCheck< TVector, TDomain >::m_spApprox, and ug::CompositeConvCheck< TVector, TDomain >::set_component_check().
Referenced by ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check(), and ug::CompositeConvCheck< TVector, TDomain >::set_component_check().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_component_check (const std::string & vFctName, const std::vector< number > & vMinDefect, const std::vector< number > & vRelReduction)
sets check for single component
References ug::TokenizeTrimString().
Referenced by ug::CompositeConvCheck< TVector, TDomain >::clone(), ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check(), ug::CompositeConvCheck< TVector, TDomain >::set_all_component_check(), and ug::CompositeConvCheck< TVector, TDomain >::set_component_check().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_component_check (const std::vector< std::string > & vFctName, const std::vector< number > & vMinDefect, const std::vector< number > & vRelReduction)
sets check for single component
References ug::CompositeConvCheck< TVector, TDomain >::set_component_check(), and UG_THROW.
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_component_check (const std::vector< std::string > & vFctName, const number minDefect, const number relReduction)
sets check for single component
References ug::CompositeConvCheck< TVector, TDomain >::set_all_component_check(), and ug::CompositeConvCheck< TVector, TDomain >::set_component_check().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_component_check (const std::string & fctName, const number minDefect, const number relReduction)
sets check for single component
References ug::CompositeConvCheck< TVector, TDomain >::m_CmpInfo, ug::CompositeConvCheck< TVector, TDomain >::m_spApprox, ug::CompositeConvCheck< TVector, TDomain >::set_group_check(), ug::TokenizeTrimString(), and ug::CompositeConvCheck< TVector, TDomain >::update_rest_check().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_group_check (const std::vector< std::string > & vFctName, const number minDefect, const number relReduction)
sets check for group of components
References ug::CompositeConvCheck< TVector, TDomain >::m_CmpInfo, ug::CompositeConvCheck< TVector, TDomain >::m_spApprox, ug::CompositeConvCheck< TVector, TDomain >::m_vNativCmpInfo, ug::TrimString(), and ug::CompositeConvCheck< TVector, TDomain >::update_rest_check().
Referenced by ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check(), ug::CompositeConvCheck< TVector, TDomain >::set_component_check(), and ug::CompositeConvCheck< TVector, TDomain >::set_group_check().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_group_check (const std::string & fctNames, const number minDefect, const number relReduction)
sets check for group of components
References ug::CompositeConvCheck< TVector, TDomain >::set_group_check(), ug::TokenizeTrimString(), and ug::CompositeConvCheck< TVector, TDomain >::update_rest_check().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_info (std::string name) inline virtual
sets info string
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::m_info.
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_level (int level)
set level of grid, where defect vectors come from
References ug::CompositeConvCheck< TVector, TDomain >::extract_dof_indices(), ug::CompositeConvCheck< TVector, TDomain >::m_spApprox, ug::GridLevel::SURFACE, and ug::CompositeConvCheck< TVector, TDomain >::update_rest_check().
Referenced by ug::CompositeConvCheck< TVector, TDomain >::CompositeConvCheck(), ug::CompositeConvCheck< TVector, TDomain >::start(), and ug::CompositeConvCheck< TVector, TDomain >::~CompositeConvCheck().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_maximum_steps (int maxSteps) inline
sets maximum number of iteration steps
References ug::CompositeConvCheck< TVector, TDomain >::m_maxSteps.
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_name (std::string name) inline virtual
sets the name of the iteration
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::m_name.
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_offset (int offset) inline virtual
sets the number of spaces printed before output information
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::m_offset.
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_rest_check (number minDefect, number relReduction) inline
sets default values for non-explicitly specified cmps
References ug::CompositeConvCheck< TVector, TDomain >::m_bCheckRest, ug::CompositeConvCheck< TVector, TDomain >::m_restMinDefect, ug::CompositeConvCheck< TVector, TDomain >::m_restRelReduction, and ug::CompositeConvCheck< TVector, TDomain >::update_rest_check().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_symbol (char symbol) inline virtual
sets the symbol used for output
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::m_symbol.
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_time_measurement (bool yesOrNo) inline
enables time measurement
References ug::CompositeConvCheck< TVector, TDomain >::m_bTimeMeas.
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::set_verbose (bool level) inline
sets if verbose
References ug::CompositeConvCheck< TVector, TDomain >::m_verbose.
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::start (const TVector & d) virtual
computes the start defect and set it
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::currDefect, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::initDefect, ug::CompositeConvCheck< TVector, TDomain >::m_bAdaptive, ug::CompositeConvCheck< TVector, TDomain >::m_bTimeMeas, ug::CompositeConvCheck< TVector, TDomain >::m_CmpInfo, ug::CompositeConvCheck< TVector, TDomain >::m_currentStep, ug::CompositeConvCheck< TVector, TDomain >::m_info, ug::CompositeConvCheck< TVector, TDomain >::m_name, ug::CompositeConvCheck< TVector, TDomain >::m_numAllDoFs, ug::CompositeConvCheck< TVector, TDomain >::m_stopwatch, ug::CompositeConvCheck< TVector, TDomain >::m_symbol, ug::CompositeConvCheck< TVector, TDomain >::m_verbose, ug::CompositeConvCheck< TVector, TDomain >::m_vNativCmpInfo, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::minDefect, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::name, ug::CompositeConvCheck< TVector, TDomain >::norm(), ug::CompositeConvCheck< TVector, TDomain >::print_offset(), ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::relReduction, ug::repeat(), ug::CompositeConvCheck< TVector, TDomain >::set_level(), ug::Stopwatch::start(), ug::CompositeConvCheck< TVector, TDomain >::step(), ug::GridLevel::TOP, UG_LOG, UG_THROW, and ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::vFct.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::start_defect (number initialDefect) virtual
defect control
Implements ug::IConvergenceCheck< TVector >.
References UG_THROW.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check().
template<class TVector , class TDomain > int ug::CompositeConvCheck< TVector, TDomain >::step () const inline virtual
information about current status
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::m_currentStep.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::iteration_ended(), ug::CompositeConvCheck< TVector, TDomain >::post(), ug::CompositeConvCheck< TVector, TDomain >::start(), and ug::CompositeConvCheck< TVector, TDomain >::update().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::update (const TVector & d) virtual
computes the defect and sets it a the next defect value
Implements ug::IConvergenceCheck< TVector >.
References ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::currDefect, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::initDefect, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::lastDefect, ug::CompositeConvCheck< TVector, TDomain >::m_CmpInfo, ug::CompositeConvCheck< TVector, TDomain >::m_currentStep, ug::CompositeConvCheck< TVector, TDomain >::m_numAllDoFs, ug::CompositeConvCheck< TVector, TDomain >::m_verbose, ug::CompositeConvCheck< TVector, TDomain >::m_vNativCmpInfo, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::minDefect, ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::name, ug::CompositeConvCheck< TVector, TDomain >::norm(), ug::CompositeConvCheck< TVector, TDomain >::print_offset(), ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::relReduction, ug::CompositeConvCheck< TVector, TDomain >::step(), UG_LOG, UG_THROW, and ug::CompositeConvCheck< TVector, TDomain >::CmpInfo::vFct.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::update_defect (number defect) virtual
sets the update for the current defect
Implements ug::IConvergenceCheck< TVector >.
References UG_THROW.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check().
template<class TVector , class TDomain > void ug::CompositeConvCheck< TVector, TDomain >::update_rest_check () protected
References ug::CompositeConvCheck< TVector, TDomain >::m_bCheckRest, ug::CompositeConvCheck< TVector, TDomain >::m_CmpInfo, ug::CompositeConvCheck< TVector, TDomain >::m_restMinDefect, ug::CompositeConvCheck< TVector, TDomain >::m_restRelReduction, and ug::CompositeConvCheck< TVector, TDomain >::m_vNativCmpInfo.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check(), ug::CompositeConvCheck< TVector, TDomain >::set_component_check(), ug::CompositeConvCheck< TVector, TDomain >::set_group_check(), ug::CompositeConvCheck< TVector, TDomain >::set_level(), and ug::CompositeConvCheck< TVector, TDomain >::set_rest_check().
Member Data Documentation
template<class TVector , class TDomain > bool ug::CompositeConvCheck< TVector, TDomain >::m_bAdaptive protected
adaptivity flag
Referenced by ug::CompositeConvCheck< TVector, TDomain >::set_adaptive(), and ug::CompositeConvCheck< TVector, TDomain >::start().
template<class TVector , class TDomain > bool ug::CompositeConvCheck< TVector, TDomain >::m_bCheckRest protected
default Values
Referenced by ug::CompositeConvCheck< TVector, TDomain >::disable_rest_check(), ug::CompositeConvCheck< TVector, TDomain >::set_rest_check(), and ug::CompositeConvCheck< TVector, TDomain >::update_rest_check().
template<class TVector , class TDomain > bool ug::CompositeConvCheck< TVector, TDomain >::m_bTimeMeas protected
enables time measurement
Referenced by ug::CompositeConvCheck< TVector, TDomain >::post(), ug::CompositeConvCheck< TVector, TDomain >::set_time_measurement(), and ug::CompositeConvCheck< TVector, TDomain >::start().
template<class TVector , class TDomain > std::vector<CmpInfo> ug::CompositeConvCheck< TVector, TDomain >::m_CmpInfo protected
infos for each component
Referenced by ug::CompositeConvCheck< TVector, TDomain >::config_string(), ug::CompositeConvCheck< TVector, TDomain >::fctName(), ug::CompositeConvCheck< TVector, TDomain >::iteration_ended(), ug::CompositeConvCheck< TVector, TDomain >::post(), ug::CompositeConvCheck< TVector, TDomain >::set_component_check(), ug::CompositeConvCheck< TVector, TDomain >::set_group_check(), ug::CompositeConvCheck< TVector, TDomain >::start(), ug::CompositeConvCheck< TVector, TDomain >::update(), and ug::CompositeConvCheck< TVector, TDomain >::update_rest_check().
template<class TVector , class TDomain > int ug::CompositeConvCheck< TVector, TDomain >::m_currentStep protected
current step
Referenced by ug::CompositeConvCheck< TVector, TDomain >::avg_rate(), ug::CompositeConvCheck< TVector, TDomain >::start(), ug::CompositeConvCheck< TVector, TDomain >::step(), and ug::CompositeConvCheck< TVector, TDomain >::update().
template<class TVector , class TDomain > std::string ug::CompositeConvCheck< TVector, TDomain >::m_info protected
info for iteration (e.g. preconditioner type)
Referenced by ug::CompositeConvCheck< TVector, TDomain >::set_info(), and ug::CompositeConvCheck< TVector, TDomain >::start().
template<class TVector , class TDomain > int ug::CompositeConvCheck< TVector, TDomain >::m_maxSteps protected
maximum number of steps to be performed
Referenced by ug::CompositeConvCheck< TVector, TDomain >::config_string(), ug::CompositeConvCheck< TVector, TDomain >::iteration_ended(), ug::CompositeConvCheck< TVector, TDomain >::post(), and ug::CompositeConvCheck< TVector, TDomain >::set_maximum_steps().
template<class TVector , class TDomain > std::string ug::CompositeConvCheck< TVector, TDomain >::m_name protected
name of iteration
Referenced by ug::CompositeConvCheck< TVector, TDomain >::set_name(), and ug::CompositeConvCheck< TVector, TDomain >::start().
template<class TVector , class TDomain > size_t ug::CompositeConvCheck< TVector, TDomain >::m_numAllDoFs protected
Referenced by ug::CompositeConvCheck< TVector, TDomain >::extract_dof_indices(), ug::CompositeConvCheck< TVector, TDomain >::start(), and ug::CompositeConvCheck< TVector, TDomain >::update().
template<class TVector , class TDomain > int ug::CompositeConvCheck< TVector, TDomain >::m_offset protected
number of spaces inserted before output
Referenced by ug::CompositeConvCheck< TVector, TDomain >::get_offset(), ug::CompositeConvCheck< TVector, TDomain >::print_offset(), and ug::CompositeConvCheck< TVector, TDomain >::set_offset().
template<class TVector , class TDomain > number ug::CompositeConvCheck< TVector, TDomain >::m_restMinDefect protected
Referenced by ug::CompositeConvCheck< TVector, TDomain >::set_rest_check(), and ug::CompositeConvCheck< TVector, TDomain >::update_rest_check().
template<class TVector , class TDomain > number ug::CompositeConvCheck< TVector, TDomain >::m_restRelReduction protected
Referenced by ug::CompositeConvCheck< TVector, TDomain >::set_rest_check(), and ug::CompositeConvCheck< TVector, TDomain >::update_rest_check().
template<class TVector , class TDomain > SmartPtr<ApproximationSpace<TDomain> > ug::CompositeConvCheck< TVector, TDomain >::m_spApprox protected
ApproxSpace.
Referenced by ug::CompositeConvCheck< TVector, TDomain >::clone(), ug::CompositeConvCheck< TVector, TDomain >::set_all_component_check(), ug::CompositeConvCheck< TVector, TDomain >::set_component_check(), ug::CompositeConvCheck< TVector, TDomain >::set_group_check(), and ug::CompositeConvCheck< TVector, TDomain >::set_level().
template<class TVector , class TDomain > Stopwatch ug::CompositeConvCheck< TVector, TDomain >::m_stopwatch protected
a stopwatch
Referenced by ug::CompositeConvCheck< TVector, TDomain >::post(), and ug::CompositeConvCheck< TVector, TDomain >::start().
template<class TVector , class TDomain > char ug::CompositeConvCheck< TVector, TDomain >::m_symbol protected
symbol for output appearance
Referenced by ug::CompositeConvCheck< TVector, TDomain >::post(), ug::CompositeConvCheck< TVector, TDomain >::print_offset(), ug::CompositeConvCheck< TVector, TDomain >::set_symbol(), and ug::CompositeConvCheck< TVector, TDomain >::start().
template<class TVector , class TDomain > bool ug::CompositeConvCheck< TVector, TDomain >::m_verbose protected
verbose level
Referenced by ug::CompositeConvCheck< TVector, TDomain >::post(), ug::CompositeConvCheck< TVector, TDomain >::set_verbose(), ug::CompositeConvCheck< TVector, TDomain >::start(), and ug::CompositeConvCheck< TVector, TDomain >::update().
template<class TVector , class TDomain > std::vector<NativCmpInfo> ug::CompositeConvCheck< TVector, TDomain >::m_vNativCmpInfo protected
info on natural components
Referenced by ug::CompositeConvCheck< TVector, TDomain >::extract_dof_indices(), ug::CompositeConvCheck< TVector, TDomain >::set_group_check(), ug::CompositeConvCheck< TVector, TDomain >::start(), ug::CompositeConvCheck< TVector, TDomain >::update(), and ug::CompositeConvCheck< TVector, TDomain >::update_rest_check().
The documentation for this class was generated from the following files:
ugbase/lib_disc/operator/composite_conv_check.h
ugbase/lib_disc/operator/composite_conv_check_impl.h