ug4: ConstSmartPtr< T, FreePolicy > Class Template Reference
ConstSmartPtr< T, FreePolicy > Class Template Reference
ugbase » Common » Common Utilities
#include <smart_pointer.h>
Public Member Functions
SmartPtr< T, FreePolicy > cast_const () const
performs a const cast
template<class TDest >
ConstSmartPtr< TDest, FreePolicy > cast_dynamic () const
preforms a dynamic cast
template<class TDest >
ConstSmartPtr< TDest, FreePolicy > cast_reinterpret () const
performs a static cast
template<class TDest >
ConstSmartPtr< TDest, FreePolicy > cast_static () const
performs a static cast
ConstSmartPtr ()
ConstSmartPtr (const ConstSmartPtr &sp)
template<class TPtr >
ConstSmartPtr (const ConstSmartPtr< TPtr, FreePolicy > &sp)
template<class TPtr >
ConstSmartPtr (const SmartPtr< TPtr, FreePolicy > &sp)
ConstSmartPtr (const T *ptr)
ConstSmartPtr (const T *ptr, int *refCount)
WARNING: this method is DANGEROUS!
ConstSmartPtr (NullSmartPtr)
const T * get () const
bool invalid () const
returns true if the pointer is invalid, false if not.
template<class TDest >
bool is_of_type () const
operator bool () const noexcept
bool operator!= (const ConstSmartPtr &sp) const
template<class TPtr >
bool operator!= (const SmartPtr< TPtr, FreePolicy > &sp) const
bool operator!= (NullSmartPtr) const
const T & operator* () const
const T * operator-> () const
ConstSmartPtr & operator= (const ConstSmartPtr &sp)
template<class TIn >
ConstSmartPtr< T, FreePolicy > & operator= (const ConstSmartPtr< TIn, FreePolicy > &sp)
ConstSmartPtr & operator= (const SmartPtr< T, FreePolicy > &sp)
template<class TIn >
ConstSmartPtr< T, FreePolicy > & operator= (const SmartPtr< TIn, FreePolicy > &sp)
ConstSmartPtr & operator= (NullSmartPtr)
bool operator== (const ConstSmartPtr &sp) const
template<class TPtr >
bool operator== (const SmartPtr< TPtr, FreePolicy > &sp) const
bool operator== (NullSmartPtr) const
int refcount () const
int * refcount_ptr () const
WARNING: this method is dangerous!
bool valid () const
returns true if the pointer is valid, false if not.
~ConstSmartPtr ()
Private Member Functions
void release ()
decrements the refCount and frees the encapsulated pointer if required.
Static Private Member Functions
static void free_void_ptr (void *ptr)
Private Attributes
const T * m_ptr
int * m_refCount
Friends
class ConstSmartPtr< void >
Constructor & Destructor Documentation
ConstSmartPtr() [1/7]
template<typename T , template< class TT > class FreePolicy> ConstSmartPtr< T, FreePolicy >::ConstSmartPtr () inline explicit
ConstSmartPtr() [2/7]
template<typename T , template< class TT > class FreePolicy> ConstSmartPtr< T, FreePolicy >::ConstSmartPtr (const T * ptr) inline explicit
References ConstSmartPtr< T, FreePolicy >::m_refCount.
ConstSmartPtr() [3/7]
template<typename T , template< class TT > class FreePolicy> ConstSmartPtr< T, FreePolicy >::ConstSmartPtr (NullSmartPtr) inline
ConstSmartPtr() [4/7]
template<typename T , template< class TT > class FreePolicy> ConstSmartPtr< T, FreePolicy >::ConstSmartPtr (const ConstSmartPtr< T, FreePolicy > & sp) inline
References ConstSmartPtr< T, FreePolicy >::m_refCount.
ConstSmartPtr() [5/7]
template<typename T , template< class TT > class FreePolicy> template<class TPtr > ConstSmartPtr< T, FreePolicy >::ConstSmartPtr (const SmartPtr< TPtr, FreePolicy > & sp) inline
this template method allows to assign smart-pointers that encapsulate derivates of T. Make sure that the pointer-type of TSmartPtr is castable to T*.
References ConstSmartPtr< T, FreePolicy >::m_refCount.
ConstSmartPtr() [6/7]
template<typename T , template< class TT > class FreePolicy> template<class TPtr > ConstSmartPtr< T, FreePolicy >::ConstSmartPtr (const ConstSmartPtr< TPtr, FreePolicy > & sp) inline
References ConstSmartPtr< T, FreePolicy >::m_refCount.
~ConstSmartPtr()
template<typename T , template< class TT > class FreePolicy> ConstSmartPtr< T, FreePolicy >::~ConstSmartPtr () inline
References ConstSmartPtr< T, FreePolicy >::release().
ConstSmartPtr() [7/7]
template<typename T , template< class TT > class FreePolicy> ConstSmartPtr< T, FreePolicy >::ConstSmartPtr (const T * ptr, int * refCount) inline explicit
WARNING: this method is DANGEROUS!
You should only use this constructor if you really know what you're doing! The following methods are required for SmartPtr<void> and casts
References ConstSmartPtr< T, FreePolicy >::m_refCount.
Member Function Documentation
cast_const()
template<typename T , template< class TT > class FreePolicy> SmartPtr<T, FreePolicy> ConstSmartPtr< T, FreePolicy >::cast_const () const inline
performs a const cast
References ConstSmartPtr< T, FreePolicy >::m_ptr, and ConstSmartPtr< T, FreePolicy >::m_refCount.
cast_dynamic()
template<typename T , template< class TT > class FreePolicy> template<class TDest > ConstSmartPtr<TDest, FreePolicy> ConstSmartPtr< T, FreePolicy >::cast_dynamic () const inline
preforms a dynamic cast
References ConstSmartPtr< T, FreePolicy >::m_ptr, ConstSmartPtr< T, FreePolicy >::m_refCount, and p.
cast_reinterpret()
template<typename T , template< class TT > class FreePolicy> template<class TDest > ConstSmartPtr<TDest, FreePolicy> ConstSmartPtr< T, FreePolicy >::cast_reinterpret () const inline
performs a static cast
References ConstSmartPtr< T, FreePolicy >::m_ptr, ConstSmartPtr< T, FreePolicy >::m_refCount, and p.
cast_static()
template<typename T , template< class TT > class FreePolicy> template<class TDest > ConstSmartPtr<TDest, FreePolicy> ConstSmartPtr< T, FreePolicy >::cast_static () const inline
performs a static cast
References ConstSmartPtr< T, FreePolicy >::m_ptr, ConstSmartPtr< T, FreePolicy >::m_refCount, and p.
free_void_ptr()
template<typename T , template< class TT > class FreePolicy> static void ConstSmartPtr< T, FreePolicy >::free_void_ptr (void * ptr) inline static private
get()
template<typename T , template< class TT > class FreePolicy> const T* ConstSmartPtr< T, FreePolicy >::get () const inline
References ConstSmartPtr< T, FreePolicy >::m_ptr.
Referenced by ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::calc_error(), ug::CheckDoFElem(), ug::collectStretchedElementIndices(), ug::ExtractPositionsElem(), ug::MarkElementsAbsolute(), ConstSmartPtr< T, FreePolicy >::operator=(), ConstSmartPtr< T, FreePolicy >::operator==(), and SmartPtr< T, FreePolicy >::operator==().
invalid()
template<typename T , template< class TT > class FreePolicy> bool ConstSmartPtr< T, FreePolicy >::invalid () const inline
returns true if the pointer is invalid, false if not.
References ConstSmartPtr< T, FreePolicy >::m_ptr.
Referenced by ug::LocalFiniteElementProvider::create_sub_dof_set(), ug::CreateUnionOfFunctionGroups(), ug::DependentUserData< TData, dim >::extract_fct_grp(), and ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::extract_ids().
is_of_type()
template<typename T , template< class TT > class FreePolicy> template<class TDest > bool ConstSmartPtr< T, FreePolicy >::is_of_type () const inline
References ConstSmartPtr< T, FreePolicy >::m_ptr.
operator bool()
template<typename T , template< class TT > class FreePolicy> ConstSmartPtr< T, FreePolicy >::operator bool () const inline explicit noexcept
References ConstSmartPtr< T, FreePolicy >::m_ptr.
operator!=() [1/3]
template<typename T , template< class TT > class FreePolicy> bool ConstSmartPtr< T, FreePolicy >::operator!= (const ConstSmartPtr< T, FreePolicy > & sp) const inline
References ConstSmartPtr< T, FreePolicy >::operator==().
operator!=() [2/3]
template<typename T , template< class TT > class FreePolicy> template<class TPtr > bool ConstSmartPtr< T, FreePolicy >::operator!= (const SmartPtr< TPtr, FreePolicy > & sp) const inline
References ConstSmartPtr< T, FreePolicy >::operator==().
operator!=() [3/3]
template<typename T , template< class TT > class FreePolicy> bool ConstSmartPtr< T, FreePolicy >::operator!= (NullSmartPtr) const inline
References ConstSmartPtr< T, FreePolicy >::m_ptr.
operator*()
template<typename T , template< class TT > class FreePolicy> const T& ConstSmartPtr< T, FreePolicy >::operator* () const inline
References ConstSmartPtr< T, FreePolicy >::m_ptr.
operator->()
template<typename T , template< class TT > class FreePolicy> const T* ConstSmartPtr< T, FreePolicy >::operator-> () const inline
References ConstSmartPtr< T, FreePolicy >::m_ptr.
operator=() [1/5]
template<typename T , template< class TT > class FreePolicy> ConstSmartPtr& ConstSmartPtr< T, FreePolicy >::operator= (const ConstSmartPtr< T, FreePolicy > & sp) inline
References ConstSmartPtr< T, FreePolicy >::m_ptr, ConstSmartPtr< T, FreePolicy >::m_refCount, and ConstSmartPtr< T, FreePolicy >::release().
operator=() [2/5]
template<typename T , template< class TT > class FreePolicy> template<class TIn > ConstSmartPtr<T, FreePolicy>& ConstSmartPtr< T, FreePolicy >::operator= (const ConstSmartPtr< TIn, FreePolicy > & sp) inline
References ConstSmartPtr< T, FreePolicy >::get(), ConstSmartPtr< T, FreePolicy >::m_ptr, ConstSmartPtr< T, FreePolicy >::m_refCount, ConstSmartPtr< T, FreePolicy >::refcount_ptr(), and ConstSmartPtr< T, FreePolicy >::release().
operator=() [3/5]
template<typename T , template< class TT > class FreePolicy> ConstSmartPtr& ConstSmartPtr< T, FreePolicy >::operator= (const SmartPtr< T, FreePolicy > & sp) inline
References SmartPtr< T, FreePolicy >::m_ptr, ConstSmartPtr< T, FreePolicy >::m_ptr, SmartPtr< T, FreePolicy >::m_refCount, ConstSmartPtr< T, FreePolicy >::m_refCount, and ConstSmartPtr< T, FreePolicy >::release().
operator=() [4/5]
template<typename T , template< class TT > class FreePolicy> template<class TIn > ConstSmartPtr<T, FreePolicy>& ConstSmartPtr< T, FreePolicy >::operator= (const SmartPtr< TIn, FreePolicy > & sp) inline
References SmartPtr< T, FreePolicy >::get(), ConstSmartPtr< T, FreePolicy >::m_ptr, ConstSmartPtr< T, FreePolicy >::m_refCount, SmartPtr< T, FreePolicy >::refcount_ptr(), and ConstSmartPtr< T, FreePolicy >::release().
operator=() [5/5]
template<typename T , template< class TT > class FreePolicy> ConstSmartPtr& ConstSmartPtr< T, FreePolicy >::operator= (NullSmartPtr) inline
References ConstSmartPtr< T, FreePolicy >::m_ptr, ConstSmartPtr< T, FreePolicy >::m_refCount, and ConstSmartPtr< T, FreePolicy >::release().
operator==() [1/3]
template<typename T , template< class TT > class FreePolicy> bool ConstSmartPtr< T, FreePolicy >::operator== (const ConstSmartPtr< T, FreePolicy > & sp) const inline
References ConstSmartPtr< T, FreePolicy >::get().
Referenced by ConstSmartPtr< T, FreePolicy >::operator!=().
operator==() [2/3]
template<typename T , template< class TT > class FreePolicy> template<class TPtr > bool ConstSmartPtr< T, FreePolicy >::operator== (const SmartPtr< TPtr, FreePolicy > & sp) const inline
References SmartPtr< T, FreePolicy >::get(), and ConstSmartPtr< T, FreePolicy >::get().
operator==() [3/3]
template<typename T , template< class TT > class FreePolicy> bool ConstSmartPtr< T, FreePolicy >::operator== (NullSmartPtr) const inline
References ConstSmartPtr< T, FreePolicy >::m_ptr.
refcount()
template<typename T , template< class TT > class FreePolicy> int ConstSmartPtr< T, FreePolicy >::refcount () const inline
References ConstSmartPtr< T, FreePolicy >::m_refCount.
Referenced by ug::vrl::ConstSmartTestFunction().
refcount_ptr()
template<typename T , template< class TT > class FreePolicy> int* ConstSmartPtr< T, FreePolicy >::refcount_ptr () const inline
WARNING: this method is dangerous!
This method should never be used since it may be removed in future versions of the SmartPtr class. It is featured in order to allow to implement a template-constructor that casts element-pointers of a smart pointer.
References ConstSmartPtr< T, FreePolicy >::m_refCount.
Referenced by ConstSmartPtr< T, FreePolicy >::operator=().
release()
template<typename T , template< class TT > class FreePolicy> void ConstSmartPtr< T, FreePolicy >::release () inline private
decrements the refCount and frees the encapsulated pointer if required.
References ConstSmartPtr< T, FreePolicy >::m_ptr, and ConstSmartPtr< T, FreePolicy >::m_refCount.
Referenced by ConstSmartPtr< void >::invalidate(), ConstSmartPtr< T, FreePolicy >::operator=(), ConstSmartPtr< void >::operator=(), ConstSmartPtr< T, FreePolicy >::~ConstSmartPtr(), and ConstSmartPtr< void >::~ConstSmartPtr().
valid()
template<typename T , template< class TT > class FreePolicy> bool ConstSmartPtr< T, FreePolicy >::valid () const inline
returns true if the pointer is valid, false if not.
References ConstSmartPtr< T, FreePolicy >::m_ptr.
Referenced by ug::IProjGaussSeidel< TDomain, TAlgebra >::apply(), ug::LoadBalancer::create_quality_record(), ug::LocalFiniteElementProvider::create_sub_dof_set(), ug::L2DistIntegrand< TGridFunction >::evaluate(), ug::H1SemiDistIntegrand< TGridFunction >::evaluate(), ug::H1EnergyDistIntegrand< TGridFunction >::evaluate(), ug::L2Integrand< TGridFunction >::evaluate(), ug::H1SemiIntegrand< TGridFunction >::evaluate(), ug::H1EnergyIntegrand< TGridFunction >::evaluate(), ug::LocalFiniteElementProvider::get(), ug::LocalFiniteElementProvider::get_dofs(), and ConstSmartPtr< void >::invalidate().
Friends And Related Function Documentation
ConstSmartPtr< void >
template<typename T , template< class TT > class FreePolicy> friend class ConstSmartPtr< void > friend
Member Data Documentation
m_ptr
template<typename T , template< class TT > class FreePolicy> const T* ConstSmartPtr< T, FreePolicy >::m_ptr private
Referenced by ConstSmartPtr< T, FreePolicy >::cast_const(), ConstSmartPtr< T, FreePolicy >::cast_dynamic(), ConstSmartPtr< T, FreePolicy >::cast_reinterpret(), ConstSmartPtr< void >::cast_reinterpret(), ConstSmartPtr< T, FreePolicy >::cast_static(), ConstSmartPtr< T, FreePolicy >::get(), ConstSmartPtr< void >::get(), ConstSmartPtr< T, FreePolicy >::invalid(), ConstSmartPtr< void >::invalid(), ConstSmartPtr< void >::invalidate(), ConstSmartPtr< T, FreePolicy >::is_of_type(), ConstSmartPtr< T, FreePolicy >::operator bool(), ConstSmartPtr< void >::operator bool(), ConstSmartPtr< T, FreePolicy >::operator!=(), ConstSmartPtr< T, FreePolicy >::operator*(), ConstSmartPtr< T, FreePolicy >::operator->(), ConstSmartPtr< T, FreePolicy >::operator=(), ConstSmartPtr< void >::operator=(), ConstSmartPtr< T, FreePolicy >::operator==(), ConstSmartPtr< T, FreePolicy >::release(), ConstSmartPtr< void >::release(), ConstSmartPtr< void >::set_impl(), ConstSmartPtr< T, FreePolicy >::valid(), and ConstSmartPtr< void >::valid().
m_refCount
template<typename T , template< class TT > class FreePolicy> int* ConstSmartPtr< T, FreePolicy >::m_refCount private
Referenced by ConstSmartPtr< T, FreePolicy >::cast_const(), ConstSmartPtr< T, FreePolicy >::cast_dynamic(), ConstSmartPtr< T, FreePolicy >::cast_reinterpret(), ConstSmartPtr< T, FreePolicy >::cast_static(), ConstSmartPtr< T, FreePolicy >::ConstSmartPtr(), ConstSmartPtr< void >::operator=(), ConstSmartPtr< T, FreePolicy >::operator=(), ConstSmartPtr< T, FreePolicy >::refcount(), ConstSmartPtr< T, FreePolicy >::refcount_ptr(), and ConstSmartPtr< T, FreePolicy >::release().
The documentation for this class was generated from the following file:
ugbase/common/util/smart_pointer.h