ug4: ug::StdTransfer< TDomain, TAlgebra > Class Template Reference
ug::StdTransfer< TDomain, TAlgebra > Class Template Reference
Standard Prolongation Operator.
#include <std_transfer.h>
Classes
struct TransferKey
struct to distinguish already assembled operators
Public Types
typedef TAlgebra algebra_type
Type of Algebra.
typedef ITransferOperator< TDomain, TAlgebra > base_type
Type of base class.
typedef TDomain domain_type
Type of Domain.
typedef GridFunction< TDomain, TAlgebra > GF
Type of GridFunction.
typedef TAlgebra::matrix_type matrix_type
Type of Matrix.
typedef TAlgebra::vector_type vector_type
Type of Vector.
Public Types inherited from ug::ITransferOperator< TDomain, TAlgebra >
typedef TDomain domain_type
Domain type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Member Functions
virtual SmartPtr< ITransferOperator< TDomain, TAlgebra > > clone ()
returns new instance with same setting
void do_restrict (GF &uCoarse, const GF &uFine)
apply operator to a grid function
virtual void do_restrict (vector_type &uCoarse, const vector_type &uFine)
apply transposed Operator, restrict function
void enable_p1_lagrange_optimization (bool enable)
enables/disables an assembling optimization for p1-lagrange elements
virtual void init ()
initialize the operator
bool p1_lagrange_optimization_enabled () const
void prolongate (GF &uFine, const GF &uCoarse)
apply operator to a grid function
virtual void prolongate (vector_type &uFine, const vector_type &uCoarse)
apply Operator, interpolate function
virtual SmartPtr< matrix_type > prolongation (const GridLevel &fineGL, const GridLevel &coarseGL, ConstSmartPtr< ApproximationSpace< TDomain > > spApproxSpace)
returns prolongation as a matrix
virtual SmartPtr< matrix_type > restriction (const GridLevel &coarseGL, const GridLevel &fineGL, ConstSmartPtr< ApproximationSpace< TDomain > > spApproxSpace)
returns restriction as a matrix
void set_debug (SmartPtr< IDebugWriter< TAlgebra > > spDebugWriter)
set debug writer
virtual void set_levels (GridLevel coarseLevel, GridLevel fineLevel)
Set levels.
void set_prolongation_damping (number damp)
set prolongation damping (only applied on vector operation, not (!!) in assembled matrices)
void set_restriction_damping (number damp)
set restriction damping (only applied on vector operation, not (!!) in assembled matrices)
void set_use_transposed (bool bTransposed)
sets if restriction and prolongation are transposed
StdTransfer ()
Default constructor.
virtual ~StdTransfer ()
virtual destructor
Public Member Functions inherited from ug::ITransferOperator< TDomain, TAlgebra >
virtual void add_constraint (SmartPtr< IConstraint< TAlgebra > > pp)
adds a dirichlet post process (not added if already registered)
virtual void clear_constraints ()
clears dirichlet post processes
ITransferOperator ()
constructor
virtual void remove_constraint (SmartPtr< IConstraint< TAlgebra > > pp)
removes a post process
virtual ~ITransferOperator ()
virtual destructor
Protected Types
typedef std::map< TransferKey, SmartPtr< matrix_type > > TransferMap
Protected Member Functions
template<typename TChild >
void assemble_prolongation (matrix_type &mat, const DoFDistribution &fineDD, const DoFDistribution &coarseDD, ConstSmartPtr< TDomain > spDomain)
void assemble_prolongation (matrix_type &mat, const DoFDistribution &fineDD, const DoFDistribution &coarseDD, ConstSmartPtr< TDomain > spDomain)
void assemble_prolongation_p1 (matrix_type &mat, const DoFDistribution &fineDD, const DoFDistribution &coarseDD)
template<typename TChild >
void assemble_restriction (matrix_type &mat, const DoFDistribution &coarseDD, const DoFDistribution &fineDD, ConstSmartPtr< TDomain > spDomain)
void assemble_restriction (matrix_type &mat, const DoFDistribution &coarseDD, const DoFDistribution &fineDD, ConstSmartPtr< TDomain > spDomain)
void remove_outdated (TransferMap &map, const RevisionCounter &revCnt)
void write_debug (const matrix_type &mat, std::string name, const GridLevel &glTo, const GridLevel &glFrom)
debug writing of matrix
Protected Attributes
bool bCached
flag if cached (matrix) transfer used
bool m_bUseTransposed
flag if transposed is used
number m_dampProl
number m_dampRes
damping parameter
TransferMap m_mProlongation
TransferMap m_mRestriction
bool m_p1LagrangeOptimizationEnabled
flag for p1-lagrange-optimization
SmartPtr< IDebugWriter< TAlgebra > > m_spDebugWriter
debug writer
std::vector< SmartPtr< IConstraint< TAlgebra > > > m_vConstraint
list of post processes
Protected Attributes inherited from ug::ITransferOperator< TDomain, TAlgebra >
std::vector< SmartPtr< IConstraint< TAlgebra > > > m_vConstraint
list of post processes
Detailed Description
template<typename TDomain, typename TAlgebra>
class ug::StdTransfer< TDomain, TAlgebra >
Standard Prolongation Operator.
By default a special optimization is performed for p1-lagrange-elements. This optimization is only valid if all elements have been refined with standard refinement rules. If closure elements are generated, this optimization has to be deactivated (use StdTransfer::enable_p1_lagrange_optimization(false)).
Member Typedef Documentation
algebra_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra ug::StdTransfer< TDomain, TAlgebra >::algebra_type
Type of Algebra.
base_type
template<typename TDomain , typename TAlgebra > typedef ITransferOperator<TDomain, TAlgebra> ug::StdTransfer< TDomain, TAlgebra >::base_type
Type of base class.
domain_type
template<typename TDomain , typename TAlgebra > typedef TDomain ug::StdTransfer< TDomain, TAlgebra >::domain_type
Type of Domain.
GF
template<typename TDomain , typename TAlgebra > typedef GridFunction<TDomain, TAlgebra> ug::StdTransfer< TDomain, TAlgebra >::GF
Type of GridFunction.
matrix_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::matrix_type ug::StdTransfer< TDomain, TAlgebra >::matrix_type
Type of Matrix.
TransferMap
template<typename TDomain , typename TAlgebra > typedef std::map<TransferKey, SmartPtr<matrix_type> > ug::StdTransfer< TDomain, TAlgebra >::TransferMap protected
vector_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::vector_type ug::StdTransfer< TDomain, TAlgebra >::vector_type
Type of Vector.
Constructor & Destructor Documentation
StdTransfer()
template<typename TDomain , typename TAlgebra > ug::StdTransfer< TDomain, TAlgebra >::StdTransfer () inline
Default constructor.
~StdTransfer()
template<typename TDomain , typename TAlgebra > virtual ug::StdTransfer< TDomain, TAlgebra >::~StdTransfer () inline virtual
virtual destructor
Member Function Documentation
assemble_prolongation() [1/2]
template<typename TDomain , typename TAlgebra > template<typename TChild > void ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation (matrix_type & mat, const DoFDistribution & fineDD, const DoFDistribution & coarseDD, ConstSmartPtr< TDomain > spDomain) protected
References ug::GridObject::base_object_id(), ug::DoFDistribution::collect_associated(), ug::LFEID::CROUZEIX_RAVIART, dim, ug::LFEID::dim(), ug::DoFDistribution::dof_indices(), ug::DoFRef(), SmartPtr< T, FreePolicy >::get(), ug::MultiGrid::get_parent(), ug::DoFDistribution::inner_algebra_indices(), ug::DoFDistribution::inner_dof_indices(), ug::InnerDoFPosition(), ug::DoFDistribution::is_contained(), ug::LFEID::LAGRANGE, ug::DoFDistributionInfoProvider::lfeid(), ug::DoFDistributionInfoProvider::max_fct_dofs(), ug::DoFDistribution::multi_grid(), ug::DoFDistributionInfoProvider::num_fct(), ug::DoFDistributionInfoProvider::num_subsets(), p, ug::LFEID::PIECEWISE_CONSTANT, PROFILE_FUNC_GROUP, ug::ShapesAtGlobalPosition(), ug::LFEID::type(), UG_ASSERT, and UG_THROW.
assemble_prolongation() [2/2]
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation (matrix_type & mat, const DoFDistribution & fineDD, const DoFDistribution & coarseDD, ConstSmartPtr< TDomain > spDomain) protected
References ug::EDGE, ug::FACE, ug::DoFDistributionInfoProvider::max_dofs(), ug::DoFDistribution::num_indices(), ug::VERTEX, and ug::VOLUME.
assemble_prolongation_p1()
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1 (matrix_type & mat, const DoFDistribution & fineDD, const DoFDistribution & coarseDD) protected
References ug::DoFRef(), ug::ElementDebugInfo(), ug::MultiGrid::get_parent(), ug::DoFDistribution::inner_algebra_indices(), ug::DoFDistribution::inner_dof_indices(), ug::DoFDistribution::is_contained(), ug::DoFDistributionInfoProvider::is_def_in_subset(), ug::LFEID::LAGRANGE, ug::DoFDistributionInfoProvider::lfeid(), ug::DoFDistribution::multi_grid(), ug::DoFDistributionInfoProvider::num_fct(), ug::DoFDistribution::num_indices(), ug::DoFDistributionInfoProvider::num_subsets(), ug::LFEID::order(), PROFILE_FUNC_GROUP, ug::GridObject::reference_object_id(), ug::ROID_EDGE, ug::ROID_HEXAHEDRON, ug::ROID_QUADRILATERAL, ug::ROID_VERTEX, ug::LFEID::type(), UG_ASSERT, UG_THROW, ug::EdgeVertices::vertex(), ug::FaceVertices::vertex(), and ug::VolumeVertices::vertex().
assemble_restriction() [1/2]
template<typename TDomain , typename TAlgebra > template<typename TChild > void ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction (matrix_type & mat, const DoFDistribution & coarseDD, const DoFDistribution & fineDD, ConstSmartPtr< TDomain > spDomain) protected
References ug::GridObject::base_object_id(), ug::DoFDistribution::collect_associated(), ug::LFEID::CROUZEIX_RAVIART, dim, ug::LFEID::dim(), ug::DoFDistribution::dof_indices(), ug::DoFRef(), SmartPtr< T, FreePolicy >::get(), ug::MultiGrid::get_parent(), ug::DoFDistribution::inner_algebra_indices(), ug::DoFDistribution::inner_dof_indices(), ug::InnerDoFPosition(), ug::DoFDistribution::is_contained(), ug::LFEID::LAGRANGE, ug::DoFDistributionInfoProvider::lfeid(), ug::DoFDistributionInfoProvider::max_fct_dofs(), ug::DoFDistribution::multi_grid(), ug::MultiGrid::num_children(), ug::DoFDistributionInfoProvider::num_fct(), ug::DoFDistributionInfoProvider::num_subsets(), p, ug::LFEID::PIECEWISE_CONSTANT, PROFILE_FUNC_GROUP, ug::ShapesAtGlobalPosition(), ug::LFEID::type(), UG_ASSERT, and UG_THROW.
assemble_restriction() [2/2]
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction (matrix_type & mat, const DoFDistribution & coarseDD, const DoFDistribution & fineDD, ConstSmartPtr< TDomain > spDomain) protected
References ug::EDGE, ug::FACE, ug::DoFDistributionInfoProvider::max_dofs(), ug::DoFDistribution::num_indices(), ug::VERTEX, and ug::VOLUME.
clone()
template<typename TDomain , typename TAlgebra > SmartPtr< ITransferOperator< TDomain, TAlgebra > > ug::StdTransfer< TDomain, TAlgebra >::clone virtual
returns new instance with same setting
Implements ug::ITransferOperator< TDomain, TAlgebra >.
Reimplemented in ug::TruncatedMonotoneTransfer< TDomain, TAlgebra >.
do_restrict() [1/2]
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::do_restrict (GF & uCoarse, const GF & uFine)
apply operator to a grid function
References ug::GridFunction< TDomain, TAlgebra >::approx_space(), ug::CT_ALL, ug::GridFunction< TDomain, TAlgebra >::grid_level(), PROFILE_FUNC_GROUP, UG_CATCH_THROW, and UG_THROW.
do_restrict() [2/2]
template<typename TDomain , typename TAlgebra > virtual void ug::StdTransfer< TDomain, TAlgebra >::do_restrict (vector_type & uCoarse, const vector_type & uFine) inline virtual
apply transposed Operator, restrict function
Implements ug::ITransferOperator< TDomain, TAlgebra >.
References UG_THROW.
enable_p1_lagrange_optimization()
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::enable_p1_lagrange_optimization (bool enable) inline
enables/disables an assembling optimization for p1-lagrange elements
The optimization is enabled by default. It can however only be used, if all elements are refined with their standard refinement rule. If one uses anisotropic refinement or refinement with closure, the optimization should be disabled.
Todo:
The normal assembling strategy should be optimized in such a way that the p1-lagrange optimization is no longer required. This however involves something like a ref-type-hash for each element, which returns a unique number based on the types and order of children.
References ug::StdTransfer< TDomain, TAlgebra >::m_p1LagrangeOptimizationEnabled.
init()
template<typename TDomain , typename TAlgebra > virtual void ug::StdTransfer< TDomain, TAlgebra >::init () inline virtual
initialize the operator
Implements ug::ITransferOperator< TDomain, TAlgebra >.
Reimplemented in ug::TruncatedMonotoneTransfer< TDomain, TAlgebra >.
p1_lagrange_optimization_enabled()
template<typename TDomain , typename TAlgebra > bool ug::StdTransfer< TDomain, TAlgebra >::p1_lagrange_optimization_enabled () const inline
References ug::StdTransfer< TDomain, TAlgebra >::m_p1LagrangeOptimizationEnabled.
prolongate() [1/2]
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::prolongate (GF & uFine, const GF & uCoarse)
apply operator to a grid function
References ug::AdditiveToConsistent(), ug::GridFunction< TDomain, TAlgebra >::approx_space(), ug::LFEID::CROUZEIX_RAVIART, ug::CT_ALL, ug::GridFunction< TDomain, TAlgebra >::grid_level(), ug::MatMultDirect(), ug::LFEID::PIECEWISE_CONSTANT, PROFILE_FUNC_GROUP, ug::ScaleLayoutValues(), UG_CATCH_THROW, and UG_THROW.
prolongate() [2/2]
template<typename TDomain , typename TAlgebra > virtual void ug::StdTransfer< TDomain, TAlgebra >::prolongate (vector_type & uFine, const vector_type & uCoarse) inline virtual
apply Operator, interpolate function
Implements ug::ITransferOperator< TDomain, TAlgebra >.
References UG_THROW.
prolongation()
template<typename TDomain , typename TAlgebra > SmartPtr< typename TAlgebra::matrix_type > ug::StdTransfer< TDomain, TAlgebra >::prolongation (const GridLevel & fineGL, const GridLevel & coarseGL, ConstSmartPtr< ApproximationSpace< TDomain > > spApproxSpace) virtual
returns prolongation as a matrix
Reimplemented from ug::ITransferOperator< TDomain, TAlgebra >.
Reimplemented in ug::TruncatedMonotoneTransfer< TDomain, TAlgebra >.
References ug::CT_ALL, ug::LFEID::LAGRANGE, ug::GridLevel::level(), ug::PST_CONSISTENT, ug::ParallelMatrix< TMatrix >::set_storage_type(), ug::GridLevel::type(), and UG_THROW.
remove_outdated()
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::remove_outdated (TransferMap & map, const RevisionCounter & revCnt) inline protected
References ug::RevisionCounter::obj().
restriction()
template<typename TDomain , typename TAlgebra > SmartPtr< typename TAlgebra::matrix_type > ug::StdTransfer< TDomain, TAlgebra >::restriction (const GridLevel & coarseGL, const GridLevel & fineGL, ConstSmartPtr< ApproximationSpace< TDomain > > spApproxSpace) virtual
returns restriction as a matrix
Reimplemented from ug::ITransferOperator< TDomain, TAlgebra >.
Reimplemented in ug::TruncatedMonotoneTransfer< TDomain, TAlgebra >.
References ug::CT_ALL, ug::GridLevel::level(), ug::PST_CONSISTENT, ug::ParallelMatrix< TMatrix >::set_storage_type(), ug::GridLevel::type(), and UG_THROW.
set_debug()
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::set_debug (SmartPtr< IDebugWriter< TAlgebra > > spDebugWriter) inline
set debug writer
References ug::StdTransfer< TDomain, TAlgebra >::m_spDebugWriter.
set_levels()
template<typename TDomain , typename TAlgebra > virtual void ug::StdTransfer< TDomain, TAlgebra >::set_levels (GridLevel coarseLevel, GridLevel fineLevel) inline virtual
Set levels.
Implements ug::ITransferOperator< TDomain, TAlgebra >.
Reimplemented in ug::TruncatedMonotoneTransfer< TDomain, TAlgebra >.
set_prolongation_damping()
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::set_prolongation_damping (number damp) inline
set prolongation damping (only applied on vector operation, not (!!) in assembled matrices)
References ug::StdTransfer< TDomain, TAlgebra >::m_dampProl.
set_restriction_damping()
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::set_restriction_damping (number damp) inline
set restriction damping (only applied on vector operation, not (!!) in assembled matrices)
References ug::StdTransfer< TDomain, TAlgebra >::m_dampRes.
set_use_transposed()
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::set_use_transposed (bool bTransposed) inline
sets if restriction and prolongation are transposed
References ug::StdTransfer< TDomain, TAlgebra >::m_bUseTransposed.
write_debug()
template<typename TDomain , typename TAlgebra > void ug::StdTransfer< TDomain, TAlgebra >::write_debug (const matrix_type & mat, std::string name, const GridLevel & glTo, const GridLevel & glFrom) protected
debug writing of matrix
References SmartPtr< T, FreePolicy >::invalid(), ug::GridLevel::level(), name, PROFILE_FUNC_GROUP, and ug::ToString().
Member Data Documentation
bCached
template<typename TDomain , typename TAlgebra > bool ug::StdTransfer< TDomain, TAlgebra >::bCached protected
flag if cached (matrix) transfer used
m_bUseTransposed
template<typename TDomain , typename TAlgebra > bool ug::StdTransfer< TDomain, TAlgebra >::m_bUseTransposed protected
flag if transposed is used
Referenced by ug::StdTransfer< TDomain, TAlgebra >::set_use_transposed().
m_dampProl
template<typename TDomain , typename TAlgebra > number ug::StdTransfer< TDomain, TAlgebra >::m_dampProl protected
Referenced by ug::StdTransfer< TDomain, TAlgebra >::set_prolongation_damping().
m_dampRes
template<typename TDomain , typename TAlgebra > number ug::StdTransfer< TDomain, TAlgebra >::m_dampRes protected
damping parameter
Referenced by ug::StdTransfer< TDomain, TAlgebra >::set_restriction_damping().
m_mProlongation
template<typename TDomain , typename TAlgebra > TransferMap ug::StdTransfer< TDomain, TAlgebra >::m_mProlongation protected
m_mRestriction
template<typename TDomain , typename TAlgebra > TransferMap ug::StdTransfer< TDomain, TAlgebra >::m_mRestriction protected
m_p1LagrangeOptimizationEnabled
template<typename TDomain , typename TAlgebra > bool ug::StdTransfer< TDomain, TAlgebra >::m_p1LagrangeOptimizationEnabled protected
flag for p1-lagrange-optimization
Referenced by ug::StdTransfer< TDomain, TAlgebra >::enable_p1_lagrange_optimization(), and ug::StdTransfer< TDomain, TAlgebra >::p1_lagrange_optimization_enabled().
m_spDebugWriter
template<typename TDomain , typename TAlgebra > SmartPtr<IDebugWriter<TAlgebra> > ug::StdTransfer< TDomain, TAlgebra >::m_spDebugWriter protected
debug writer
Referenced by ug::StdTransfer< TDomain, TAlgebra >::set_debug().
m_vConstraint
template<typename TDomain , typename TAlgebra > std::vector<SmartPtr<IConstraint<TAlgebra> > > ug::ITransferOperator< TDomain, TAlgebra >::m_vConstraint protected
list of post processes
The documentation for this class was generated from the following files:
ugbase/lib_disc/operator/linear_operator/std_transfer.h
ugbase/lib_disc/operator/linear_operator/std_transfer_impl.h