ug4: ug::CplUserData< TData, dim, TRet > Class Template Reference
ug::CplUserData< TData, dim, TRet > Class Template Reference
Type based UserData.
#include <user_data.h>
Public Types
typedef ICplUserData< dim > base_type
type of base class
Public Member Functions
bool defined (size_t s, size_t ip) const
returns flag, if data is evaluated (for conditional data)
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
register external callback, invoked when data storage changed
void unregister_storage_callback (DataImport< TData, dim > *obj)
register all callbacks registered by class
const TData & value (size_t s, size_t ip) const
returns the value at ip
TData & value (size_t s, size_t ip)
returns the value at ip
const TData * values (size_t s) const
returns all values for a series
TData * values (size_t s)
returns all values for a series
~CplUserData ()
destructor
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
returns true iff the time point specification is equal to the current one, or not specified
virtual void check_setup () const
returns if the dependent data is ready for evaluation
void clear ()
clear all data
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)=0
compute values (and derivatives iff compDeriv == true)
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)=0
compute values (and derivatives iff compDeriv == true, but only for the 'current' time point)
virtual bool constant () const
returns if data is constant
int dim_local_ips () const
returns current local ip dimension
ICplUserData ()
default constructor
const MathVector< dim > & ip (size_t s, size_t ip) const
returns global ip
const MathVector< dim > * ips (size_t s) const
returns global ips
template<int ldim>
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
returns local ip
template<int ldim>
const MathVector< ldim > * local_ips (size_t s) const
returns local ips
virtual SmartPtr< ICplUserData > needed_data (size_t i)
return needed data
size_t num_ip (size_t s) const
returns the number of integration points
virtual size_t num_needed_data () const
number of other Data this data depends on
size_t num_series () const
returns the number of ip series
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
set local positions, returns series id
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
set local positions without the specification of the time point, returns series id
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
set global positions
template<int ldim>
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
sets new local ip positions for a local ip series
void set_subset (int si)
set the subset of evaluation
void set_time_point (size_t timePoint)
sets the current time point
void set_time_point (const size_t seriesId, const int timePointSpec)
sets a new time point for a local ip series
void set_times (const std::vector< number > &vTime)
set evaluation time
int subset () const
returns the subset of evaluation
number time () const
get the current evaluation time
number time (size_t s) const
get the specified evaluation time
size_t time_point ()
returns the current time point
size_t time_point (size_t s) const
returns the time point specification (in particular, the current one, if the own one not specified)
int time_point_specification (size_t s) const
returns the time point specification (note: it may be -1, i.e. not specified)
virtual void update_dof_sizes (const LocalIndices &ind)
resize arrays
virtual bool zero_derivative () const
returns if data depends on solution
virtual ~ICplUserData ()
virtual desctructor
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
Function Group of functions.
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
sets the function pattern for a possibly needed grid function
virtual ~UserDataInfo ()
virtual destructor
Public Member Functions inherited from ug::UserData< TData, dim, TRet >
virtual bool continuous () const =0
returns if provided data is continuous over geometric object boundaries
int get_dim () const
returns dimension
virtual TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const =0
returns value for a global position
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const =0
returns value for global positions
virtual bool requires_grid_fct () const =0
returns if grid function is needed for evaluation
std::string type () const
returns type of data as string (e.g. "Number", "Vector", "Matrix")
TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const =0
Protected Member Functions
void call_storage_callback () const
calls are registered external storage callbacks
void check_series (size_t s) const
checks in debug mode the correct index
void check_series_ip (size_t s, size_t ip) const
checks in debug mode the correct index
virtual void local_ip_series_added (const size_t seriesID)
resizes the data field, when local ip changed signaled
virtual void local_ip_series_to_be_cleared ()
free the data field memory and set series to zero
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
implement callback, called when local IPs changed
virtual void value_storage_changed (const size_t seriesID)
callback, invoked when storage of data has changed for a series
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
checks in debug mode the correct usage of indices
void check_s_ip (size_t s, size_t ip) const
checks in debug mode the correct usage of indices
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
help function to get local ips
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
callback invoked after global ips have been changed
Private Types
typedef boost::function< void()> CallbackFct
registered callbacks
Private Attributes
std::vector< std::pair< DataImport< TData, dim > *, CallbackFct > > m_vCallback
std::vector< std::vector< bool > > m_vvBoolFlag
bool flag at ip (size: (0,...num_series-1) x (0,...,num_ip-1))
std::vector< std::vector< TData > > m_vvValue
data at ip (size: (0,...num_series-1) x (0,...,num_ip-1))
Additional Inherited Members
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
default time point (or -1 if not specified)
int m_locPosDim
dimension of local position (-1 indicates no dim set)
std::vector< const MathVector< 1 > * > m_pvLocIP1d
local ips of dimension 1d-3d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
subset for evaluation
size_t m_timePoint
current time point (used if no explicit specification for series)
std::vector< bool > m_vMayChange
flags if local ips may change
std::vector< size_t > m_vNumIP
number of evaluation points (-1 indicates no ips set)
std::vector< number > m_vTime
time for evaluation
std::vector< int > m_vTimePoint
time points for the series
std::vector< const MathVector< dim > * > m_vvGlobPos
global ips
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Detailed Description
template<typename TData, int dim, typename TRet = void>
class ug::CplUserData< TData, dim, TRet >
Type based UserData.
This class is the base class for all integration point data for a templated type. It provides the access to the data and handles the global integration points.
Template Parameters
TData Data
dim world dimension
TRet Type of return flag (bool or void)
Member Typedef Documentation
template<typename TData, int dim, typename TRet = void> typedef ICplUserData<dim> ug::CplUserData< TData, dim, TRet >::base_type
type of base class
template<typename TData, int dim, typename TRet = void> typedef boost::function<void ()> ug::CplUserData< TData, dim, TRet >::CallbackFct private
registered callbacks
Constructor & Destructor Documentation
template<typename TData, int dim, typename TRet = void> ug::CplUserData< TData, dim, TRet >::~CplUserData () inline
destructor
Member Function Documentation
template<typename TData , int dim, typename TRet > void ug::CplUserData< TData, dim, TRet >::call_storage_callback () const protected
calls are registered external storage callbacks
Referenced by ug::CplUserData< TData, dim, TRet >::unregister_storage_callback().
template<typename TData , int dim, typename TRet > void ug::CplUserData< TData, dim, TRet >::check_series (size_t s) const inline protected
checks in debug mode the correct index
References ug::ICplUserData< dim >::num_series(), and UG_ASSERT.
template<typename TData , int dim, typename TRet > void ug::CplUserData< TData, dim, TRet >::check_series_ip (size_t s, size_t ip) const inline protected
checks in debug mode the correct index
References ug::ICplUserData< dim >::num_ip(), and UG_ASSERT.
template<typename TData, int dim, typename TRet = void> bool ug::CplUserData< TData, dim, TRet >::defined (size_t s, size_t ip) const inline
returns flag, if data is evaluated (for conditional data)
template<typename TData , int dim, typename TRet > void ug::CplUserData< TData, dim, TRet >::local_ip_series_added (const size_t seriesID) protected virtual
resizes the data field, when local ip changed signaled
Reimplemented from ug::ICplUserData< dim >.
Reimplemented in ug::DependentUserData< TData, dim >, ug::DependentUserData< MathVector< dim >, dim >, ug::DependentUserData< TRet, dim >, ug::DependentUserData< ug::MathMatrix< dim, dim >, dim >, ug::DependentUserData< ug::MathVector< dim >, dim >, ug::DependentUserData< number, dim >, ug::DependentUserData< MathVector< TGridFunction::dim >, dim >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >.
References ug::ICplUserData< dim >::num_ip(), and UG_THROW.
template<typename TData , int dim, typename TRet > void ug::CplUserData< TData, dim, TRet >::local_ip_series_to_be_cleared () protected virtual
free the data field memory and set series to zero
Reimplemented from ug::ICplUserData< dim >.
Reimplemented in ug::DependentUserData< TData, dim >, ug::DependentUserData< MathVector< dim >, dim >, ug::DependentUserData< TRet, dim >, ug::DependentUserData< ug::MathMatrix< dim, dim >, dim >, ug::DependentUserData< ug::MathVector< dim >, dim >, ug::DependentUserData< number, dim >, and ug::DependentUserData< MathVector< TGridFunction::dim >, dim >.
template<typename TData , int dim, typename TRet > void ug::CplUserData< TData, dim, TRet >::local_ips_changed (const size_t seriesID, const size_t newNumIP) protected virtual
implement callback, called when local IPs changed
Implements ug::ICplUserData< dim >.
Reimplemented in ug::DependentUserData< TData, dim >, ug::DependentUserData< MathVector< dim >, dim >, ug::DependentUserData< TRet, dim >, ug::DependentUserData< ug::MathMatrix< dim, dim >, dim >, ug::DependentUserData< ug::MathVector< dim >, dim >, ug::DependentUserData< number, dim >, ug::DependentUserData< MathVector< TGridFunction::dim >, dim >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >.
template<typename TData, int dim, typename TRet > void ug::CplUserData< TData, dim, TRet >::register_storage_callback (DataImport< TData, dim > * obj, void(DataImport< TData, dim >::*)() func)
register external callback, invoked when data storage changed
References ug::CplUserData< TData, dim, TRet >::unregister_storage_callback().
Referenced by ug::ICplUserData< dim >::check_s_ip().
template<typename TData, int dim, typename TRet > void ug::CplUserData< TData, dim, TRet >::unregister_storage_callback (DataImport< TData, dim > * obj)
register all callbacks registered by class
References ug::CplUserData< TData, dim, TRet >::call_storage_callback().
Referenced by ug::CplUserData< TData, dim, TRet >::register_storage_callback().
template<typename TData, int dim, typename TRet = void> const TData& ug::CplUserData< TData, dim, TRet >::value (size_t s, size_t ip) const inline
returns the value at ip
Referenced by ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >::compute().
template<typename TData, int dim, typename TRet = void> TData& ug::CplUserData< TData, dim, TRet >::value (size_t s, size_t ip) inline
returns the value at ip
template<typename TData, int dim, typename TRet = void> virtual void ug::CplUserData< TData, dim, TRet >::value_storage_changed (const size_t seriesID) inline protected virtual
callback, invoked when storage of data has changed for a series
Reimplemented in ug::StdConstData< TImpl, TData, dim >, ug::StdConstData< ConstUserVector< dim, worldDim >, MathVector< dim >, worldDim >, ug::StdConstData< ConstUserNumber< dim >, number, dim >, ug::StdConstData< ConstUserMatrix< N, M, worldDim >, MathMatrix< N, M >, worldDim >, and ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >.
template<typename TData, int dim, typename TRet = void> const TData* ug::CplUserData< TData, dim, TRet >::values (size_t s) const inline
returns all values for a series
template<typename TData, int dim, typename TRet = void> TData* ug::CplUserData< TData, dim, TRet >::values (size_t s) inline
returns all values for a series
Member Data Documentation
template<typename TData, int dim, typename TRet = void> std::vector<std::pair<DataImport<TData,dim>*, CallbackFct> > ug::CplUserData< TData, dim, TRet >::m_vCallback private
template<typename TData, int dim, typename TRet = void> std::vector<std::vector<bool> > ug::CplUserData< TData, dim, TRet >::m_vvBoolFlag private
bool flag at ip (size: (0,...num_series-1) x (0,...,num_ip-1))
template<typename TData, int dim, typename TRet = void> std::vector<std::vector<TData> > ug::CplUserData< TData, dim, TRet >::m_vvValue private
data at ip (size: (0,...num_series-1) x (0,...,num_ip-1))
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/user_data/user_data.h
ugbase/lib_disc/spatial_disc/user_data/user_data_impl.h