ug4: ug::HexahedronDescriptor Class Reference
ug::HexahedronDescriptor Class Reference
only used to initialize a hexahedron. for all other tasks you should use VolumeDescriptor.
#include <grid_objects_3d.h>
Public Member Functions
HexahedronDescriptor ()
HexahedronDescriptor (const HexahedronDescriptor &td)
HexahedronDescriptor (const VolumeVertices &vv)
HexahedronDescriptor (Vertex *v1, Vertex *v2, Vertex *v3, Vertex *v4, Vertex *v5, Vertex *v6, Vertex *v7, Vertex *v8)
uint num_vertices () const
Vertex * vertex (size_t index) const
Protected Attributes
Vertex * m_vertex [8]
Detailed Description
only used to initialize a hexahedron. for all other tasks you should use VolumeDescriptor.
please be sure to pass the vertices in the correct order: v1, v2, v3, v4: bottom-vertices in counterclockwise order (if viewed from the top). v5, v6, v7, v8: top-vertices in counterclockwise order (if viewed from the top).
Constructor & Destructor Documentation
HexahedronDescriptor() [1/4]
ug::HexahedronDescriptor::HexahedronDescriptor () inline
HexahedronDescriptor() [2/4]
ug::HexahedronDescriptor::HexahedronDescriptor (const HexahedronDescriptor & td)
References vertex().
HexahedronDescriptor() [3/4]
ug::HexahedronDescriptor::HexahedronDescriptor (const VolumeVertices & vv)
References ug::VolumeVertices::num_vertices(), and ug::VolumeVertices::vertex().
HexahedronDescriptor() [4/4]
ug::HexahedronDescriptor::HexahedronDescriptor (Vertex * v1, Vertex * v2, Vertex * v3, Vertex * v4, Vertex * v5, Vertex * v6, Vertex * v7, Vertex * v8)
Member Function Documentation
num_vertices()
uint ug::HexahedronDescriptor::num_vertices () const inline
vertex()
Vertex* ug::HexahedronDescriptor::vertex (size_t index) const inline
Referenced by ug::Hexahedron::Hexahedron(), and HexahedronDescriptor().
Member Data Documentation
m_vertex
Vertex* ug::HexahedronDescriptor::m_vertex[8] protected
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid_objects/grid_objects_3d.h
ugbase/lib_grid/grid_objects/grid_objects_3d.cpp