ug4: ug::GridMessage_Distribution Class Reference
ug::GridMessage_Distribution Class Reference
#include <lib_grid_messages.h>
Public Member Functions
GridMessage_Distribution (GridMessageDistributionType msg, GridDataSerializationHandler &gdsh)
GridMessageDistributionType msg () const
GridDataSerializationHandler & serialization_handler () const
Public Member Functions inherited from ug::MessageHub::IMessage
IMessage ()
virtual ~IMessage ()
Private Attributes
GridMessageDistributionType m_msg
GridDataSerializationHandler & m_serializationHandler
Constructor & Destructor Documentation
GridMessage_Distribution()
ug::GridMessage_Distribution::GridMessage_Distribution (GridMessageDistributionType msg, GridDataSerializationHandler & gdsh) inline
Member Function Documentation
msg()
GridMessageDistributionType ug::GridMessage_Distribution::msg () const inline
References m_msg.
Referenced by ug::IApproximationSpace::grid_distribution_callback(), ug::GridFunction< TDomain, TAlgebra >::grid_distribution_callback(), and ug::DegeneratedLayerManager< dim >::grid_distribution_callback().
serialization_handler()
GridDataSerializationHandler& ug::GridMessage_Distribution::serialization_handler () const inline
References m_serializationHandler.
Referenced by ug::GridFunction< TDomain, TAlgebra >::grid_distribution_callback().
Member Data Documentation
m_msg
GridMessageDistributionType ug::GridMessage_Distribution::m_msg private
Referenced by msg().
m_serializationHandler
GridDataSerializationHandler& ug::GridMessage_Distribution::m_serializationHandler private
Referenced by serialization_handler().
The documentation for this class was generated from the following file:
ugbase/lib_grid/lib_grid_messages.h