ug4: ug::ParallelMatrix< TMatrix > Class Template Reference
ug::ParallelMatrix< TMatrix > Class Template Reference
lib_algebra » Parallel Algebra
Wrapper for sequential matrices to handle them in parallel.
#include <parallel_matrix.h>
Public Types
enum { rows_sorted =TMatrix::rows_sorted }
typedef ParallelMatrix< TMatrix > this_type
own type
Public Member Functions
void add_storage_type (uint type)
adds a storage type
template<typename TPVector >
bool apply (TPVector &res, const TPVector &x) const
calculate res = A x
template<typename TPVector >
bool apply_transposed (TPVector &res, const TPVector &x) const
calculate res = A.T x
bool change_storage_type (ParallelStorageType type)
changes to the requested storage type if possible
uint get_storage_mask () const
returns storage type mask
ParallelStorageType get_storage_type () const
bool has_storage_type (uint type) const
returns if the current storage type has a given representation
ConstSmartPtr< AlgebraLayouts > layouts () const
returns the algebra layouts
template<typename TPVector >
bool matmul_minus (TPVector &res, const TPVector &x) const
calculate res -= A x
this_type & operator= (const this_type &M)
assignment
ParallelMatrix ()
Default Constructor.
ParallelMatrix (SmartPtr< AlgebraLayouts > layouts)
Constructor setting the layouts.
void remove_storage_type (uint type)
removes a storage type
void set_layouts (ConstSmartPtr< AlgebraLayouts > layouts)
sets the algebra layouts
void set_storage_type (uint type)
sets the storage type
Private Member Functions
ParallelMatrix (const ParallelMatrix &)
Private Attributes
ConstSmartPtr< AlgebraLayouts > m_spAlgebraLayouts
algebra layouts and communicators
uint m_type
type of storage (i.e. consistent, additiv, additiv unique)
Detailed Description
template<typename TMatrix>
class ug::ParallelMatrix< TMatrix >
Wrapper for sequential matrices to handle them in parallel.
A ParallelMatrix is a wrapper around a sequential vector to make it usable in parallel. It has all the function a sequential matrix supports, since it is derived from it. Furthermore the ParallelStorageType is remembered. Currently only additive storage type is implemented. In addition some functions of the sequential matrix are overwritten to adapted the functionality to parallel (e.g. set)
Please Note: The Implementation is not yet finished.
Template Parameters
TMatrix Sequential Matrix Type
Member Typedef Documentation
template<typename TMatrix> typedef ParallelMatrix<TMatrix> ug::ParallelMatrix< TMatrix >::this_type
own type
Member Enumeration Documentation
template<typename TMatrix> anonymous enum
Enumerator
rows_sorted
Constructor & Destructor Documentation
template<typename TMatrix> ug::ParallelMatrix< TMatrix >::ParallelMatrix (const ParallelMatrix< TMatrix > &) private
template<typename TMatrix> ug::ParallelMatrix< TMatrix >::ParallelMatrix () inline
Default Constructor.
template<typename TMatrix> ug::ParallelMatrix< TMatrix >::ParallelMatrix (SmartPtr< AlgebraLayouts > layouts) inline
Constructor setting the layouts.
Member Function Documentation
template<typename TMatrix> void ug::ParallelMatrix< TMatrix >::add_storage_type (uint type) inline
adds a storage type
type may be any or-combination of constants enumerated in ug::ParallelStorageType.
References ug::ParallelMatrix< TMatrix >::m_type.
template<typename TMatrix > template<typename TPVector > bool ug::ParallelMatrix< TMatrix >::apply (TPVector & res, const TPVector & x) const
calculate res = A x
References ug::ParallelMatrix< TMatrix >::apply_transposed(), PROFILE_FUNC_GROUP, ug::PST_ADDITIVE, ug::PST_CONSISTENT, and UG_THROW.
Referenced by ug::ParallelMatrix< TMatrix >::change_storage_type(), and ug::ParallelMatrix< TMatrix >::get_storage_type().
template<typename TMatrix > template<typename TPVector > bool ug::ParallelMatrix< TMatrix >::apply_transposed (TPVector & res, const TPVector & x) const
calculate res = A.T x
References ug::ParallelMatrix< TMatrix >::matmul_minus(), PROFILE_FUNC_GROUP, ug::PST_ADDITIVE, ug::PST_CONSISTENT, and UG_THROW.
Referenced by ug::ParallelMatrix< TMatrix >::apply(), and ug::ParallelMatrix< TMatrix >::get_storage_type().
template<typename TMatrix > bool ug::ParallelMatrix< TMatrix >::change_storage_type (ParallelStorageType type)
changes to the requested storage type if possible
References ug::ParallelMatrix< TMatrix >::apply(), ug::PST_UNDEFINED, UG_LOG, and UG_THROW.
Referenced by ug::ParallelMatrix< TMatrix >::operator=(), and ug::ParallelMatrix< TMatrix >::remove_storage_type().
template<typename TMatrix> uint ug::ParallelMatrix< TMatrix >::get_storage_mask () const inline
returns storage type mask
References ug::ParallelMatrix< TMatrix >::m_type.
Referenced by ug::ParallelMatrix< TMatrix >::operator=(), and ug::SerializeUniquePart().
template<typename TMatrix> ParallelStorageType ug::ParallelMatrix< TMatrix >::get_storage_type () const inline
References ug::ParallelMatrix< TMatrix >::apply(), ug::ParallelMatrix< TMatrix >::apply_transposed(), ug::ParallelMatrix< TMatrix >::m_type, ug::ParallelMatrix< TMatrix >::matmul_minus(), and ug::ParallelMatrix< TMatrix >::operator=().
Referenced by ug::GetMultType().
template<typename TMatrix> bool ug::ParallelMatrix< TMatrix >::has_storage_type (uint type) const inline
returns if the current storage type has a given representation
type may be any or-combination of constants enumerated in ug::ParallelStorageType.
References ug::ParallelMatrix< TMatrix >::m_type, and ug::PST_UNDEFINED.
Referenced by ug::GetMultType().
template<typename TMatrix> ConstSmartPtr<AlgebraLayouts> ug::ParallelMatrix< TMatrix >::layouts () const inline
returns the algebra layouts
References ug::ParallelMatrix< TMatrix >::m_spAlgebraLayouts.
Referenced by ug::MakeConsistent(), ug::ParallelMatrix< TMatrix >::operator=(), ug::ILUTPreconditioner< ug::CPUAlgebra >::preprocess_mat(), and ug::ParallelMatrix< TMatrix >::set_layouts().
template<typename TMatrix > template<typename TPVector > bool ug::ParallelMatrix< TMatrix >::matmul_minus (TPVector & res, const TPVector & x) const
calculate res -= A x
References PROFILE_FUNC_GROUP, ug::PST_ADDITIVE, ug::PST_CONSISTENT, and UG_THROW.
Referenced by ug::ParallelMatrix< TMatrix >::apply_transposed(), and ug::ParallelMatrix< TMatrix >::get_storage_type().
template<typename TMatrix> ParallelMatrix< TMatrix >::this_type & ug::ParallelMatrix< TMatrix >::operator= (const this_type & M)
assignment
References ug::ParallelMatrix< TMatrix >::change_storage_type(), ug::ParallelMatrix< TMatrix >::get_storage_mask(), and ug::ParallelMatrix< TMatrix >::layouts().
Referenced by ug::ParallelMatrix< TMatrix >::get_storage_type().
template<typename TMatrix> void ug::ParallelMatrix< TMatrix >::remove_storage_type (uint type) inline
removes a storage type
type may be any or-combination of constants enumerated in ug::ParallelStorageType.
References ug::ParallelMatrix< TMatrix >::change_storage_type(), and ug::ParallelMatrix< TMatrix >::m_type.
template<typename TMatrix> void ug::ParallelMatrix< TMatrix >::set_layouts (ConstSmartPtr< AlgebraLayouts > layouts) inline
sets the algebra layouts
References ug::ParallelMatrix< TMatrix >::layouts(), and ug::ParallelMatrix< TMatrix >::m_spAlgebraLayouts.
Referenced by ug::MakeConsistent(), ug::IExternalSolver< TAlgebra >::mat_preprocess(), and ug::ILUTScalarPreconditioner< algebra_type >::preprocess().
template<typename TMatrix> void ug::ParallelMatrix< TMatrix >::set_storage_type (uint type) inline
sets the storage type
type may be any or-combination of constants enumerated in ug::ParallelStorageType.
References ug::ParallelMatrix< TMatrix >::m_type.
Referenced by ug::DeserializeUniquePart(), ug::IExternalSolver< TAlgebra >::mat_preprocess(), and ug::ILUTScalarPreconditioner< algebra_type >::preprocess().
Member Data Documentation
template<typename TMatrix> ConstSmartPtr<AlgebraLayouts> ug::ParallelMatrix< TMatrix >::m_spAlgebraLayouts private
algebra layouts and communicators
Referenced by ug::ParallelMatrix< TMatrix >::layouts(), and ug::ParallelMatrix< TMatrix >::set_layouts().
template<typename TMatrix> uint ug::ParallelMatrix< TMatrix >::m_type private
type of storage (i.e. consistent, additiv, additiv unique)
Referenced by ug::ParallelMatrix< TMatrix >::add_storage_type(), ug::ParallelMatrix< TMatrix >::get_storage_mask(), ug::ParallelMatrix< TMatrix >::get_storage_type(), ug::ParallelMatrix< TMatrix >::has_storage_type(), ug::ParallelMatrix< TMatrix >::remove_storage_type(), and ug::ParallelMatrix< TMatrix >::set_storage_type().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/parallelization/parallel_matrix.h
ugbase/lib_algebra/parallelization/parallel_matrix_impl.h