ug4: ug::Raster< T, TDIM >::MultiIndex Class Reference
ug::Raster< T, TDIM >::MultiIndex Class Reference
#include <raster.h>
Public Member Functions
const int dim () const
MultiIndex ()
MultiIndex (size_t i)
size_t & operator[] (int d)
size_t operator[] (int d) const
void set (size_t i)
Private Attributes
size_t m_ind [TDIM]
Friends
std::ostream & operator<< (std::ostream &o, const MultiIndex &mi)
Constructor & Destructor Documentation
MultiIndex() [1/2]
template<class T , int TDIM> ug::Raster< T, TDIM >::MultiIndex::MultiIndex ()
MultiIndex() [2/2]
template<class T , int TDIM> ug::Raster< T, TDIM >::MultiIndex::MultiIndex (size_t i)
References ug::Raster< T, TDIM >::MultiIndex::dim().
Member Function Documentation
dim()
template<class T , int TDIM> const int ug::Raster< T, TDIM >::MultiIndex::dim () const
References ug::Raster< T, TDIM >::MultiIndex::set().
Referenced by ug::Raster< T, TDIM >::MultiIndex::MultiIndex().
operator[]() [1/2]
template<class T , int TDIM> size_t & ug::Raster< T, TDIM >::MultiIndex::operator[] (int d)
References ug::Raster< T, TDIM >::MultiIndex::m_ind.
Referenced by ug::Raster< T, TDIM >::MultiIndex::set().
operator[]() [2/2]
template<class T , int TDIM> size_t ug::Raster< T, TDIM >::MultiIndex::operator[] (int d) const
References ug::Raster< T, TDIM >::Coordinate::Coordinate(), and ug::Raster< T, TDIM >::MultiIndex::m_ind.
set()
template<class T , int TDIM> void ug::Raster< T, TDIM >::MultiIndex::set (size_t i)
References ug::Raster< T, TDIM >::MultiIndex::m_ind, and ug::Raster< T, TDIM >::MultiIndex::operator[]().
Referenced by ug::Raster< T, TDIM >::MultiIndex::dim().
Friends And Related Function Documentation
operator<<
template<class T, int TDIM> std::ostream& operator<< (std::ostream & o, const MultiIndex & mi) friend
Member Data Documentation
m_ind
template<class T, int TDIM> size_t ug::Raster< T, TDIM >::MultiIndex::m_ind[TDIM] private
Referenced by ug::Raster< T, TDIM >::MultiIndex::operator[](), and ug::Raster< T, TDIM >::MultiIndex::set().
The documentation for this class was generated from the following files:
ugbase/common/util/raster.h
ugbase/common/util/raster_impl.hpp