ug4: ug::PiecewiseConstantElemTransfer< TDomain > Class Template Reference
ug::PiecewiseConstantElemTransfer< TDomain > Class Template Reference
#include <local_transfer.h>
Public Member Functions
template<typename TElem >
void do_restrict (TElem *parent, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent)
virtual bool perform_prolongation_on (GridBaseObjectId gbo)
virtual bool perform_restriction_on (GridBaseObjectId gbo)
PiecewiseConstantElemTransfer (const LFEID &lfeid)
template<typename TElem >
void prolongate (TElem *parent, TransferValueAccessor &vValueChild, TransferValueAccessor &vValueParent)
Public Member Functions inherited from ug::ElemProlongationBase< TDomain, PiecewiseConstantElemTransfer< TDomain > >
virtual void prolongate (Edge *parent)
virtual void prolongate (Face *parent)
virtual void prolongate (Vertex *parent)
virtual void prolongate (Volume *parent)
Public Member Functions inherited from ug::IElemProlongation< TDomain >
virtual void init (ConstSmartPtr< TDomain > spDomain, SmartPtr< TransferValueAccessor > vValueChild, SmartPtr< TransferValueAccessor > vValueParent)
virtual ~IElemProlongation ()
Public Member Functions inherited from ug::ElemRestrictionBase< TDomain, PiecewiseConstantElemTransfer< TDomain > >
virtual void do_restrict (Edge *parent)
virtual void do_restrict (Face *parent)
virtual void do_restrict (Vertex *parent)
virtual void do_restrict (Volume *parent)
Public Member Functions inherited from ug::IElemRestriction< TDomain >
virtual void init (ConstSmartPtr< TDomain > spDomain, SmartPtr< TransferValueAccessor > vValueChild, SmartPtr< TransferValueAccessor > vValueParent)
virtual ~IElemRestriction ()
Protected Attributes
LFEID m_lfeid
Protected Attributes inherited from ug::IElemProlongation< TDomain >
ConstSmartPtr< TDomain > m_spDomain
ConstSmartPtr< MultiGrid > m_spGrid
SmartPtr< TransferValueAccessor > m_vValueChild
SmartPtr< TransferValueAccessor > m_vValueParent
Protected Attributes inherited from ug::IElemRestriction< TDomain >
ConstSmartPtr< TDomain > m_spDomain
ConstSmartPtr< MultiGrid > m_spGrid
SmartPtr< TransferValueAccessor > m_vValueChild
SmartPtr< TransferValueAccessor > m_vValueParent
Additional Inherited Members
Protected Member Functions inherited from ug::ElemProlongationBase< TDomain, PiecewiseConstantElemTransfer< TDomain > >
PiecewiseConstantElemTransfer< TDomain > & getImpl ()
access to implementation
const PiecewiseConstantElemTransfer< TDomain > & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::ElemRestrictionBase< TDomain, PiecewiseConstantElemTransfer< TDomain > >
PiecewiseConstantElemTransfer< TDomain > & getImpl ()
access to implementation
const PiecewiseConstantElemTransfer< TDomain > & getImpl () const
const access to implementation
Constructor & Destructor Documentation
PiecewiseConstantElemTransfer()
template<typename TDomain > ug::PiecewiseConstantElemTransfer< TDomain >::PiecewiseConstantElemTransfer (const LFEID & lfeid) inline
Member Function Documentation
do_restrict()
template<typename TDomain > template<typename TElem > void ug::PiecewiseConstantElemTransfer< TDomain >::do_restrict (TElem * parent, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent) inline
References ug::TransferValueAccessor::access_inner(), ug::MultiGrid::get_child(), ug::MultiGrid::num_children(), ug::TransferValueAccessor::size(), and UG_ASSERT.
perform_prolongation_on()
template<typename TDomain > virtual bool ug::PiecewiseConstantElemTransfer< TDomain >::perform_prolongation_on (GridBaseObjectId gbo) inline virtual
Implements ug::IElemProlongation< TDomain >.
References ug::LFEID::dim(), and ug::PiecewiseConstantElemTransfer< TDomain >::m_lfeid.
perform_restriction_on()
template<typename TDomain > virtual bool ug::PiecewiseConstantElemTransfer< TDomain >::perform_restriction_on (GridBaseObjectId gbo) inline virtual
Implements ug::IElemRestriction< TDomain >.
References ug::LFEID::dim(), and ug::PiecewiseConstantElemTransfer< TDomain >::m_lfeid.
prolongate()
template<typename TDomain > template<typename TElem > void ug::PiecewiseConstantElemTransfer< TDomain >::prolongate (TElem * parent, TransferValueAccessor & vValueChild, TransferValueAccessor & vValueParent) inline
References ug::TransferValueAccessor::access_inner(), ug::MultiGrid::get_child(), and ug::MultiGrid::num_children().
Member Data Documentation
m_lfeid
template<typename TDomain > LFEID ug::PiecewiseConstantElemTransfer< TDomain >::m_lfeid protected
Referenced by ug::PiecewiseConstantElemTransfer< TDomain >::perform_prolongation_on(), and ug::PiecewiseConstantElemTransfer< TDomain >::perform_restriction_on().
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/local_transfer.h