ug4: ug::RefinementCallback_IntersectCylinder Class Reference
ug::RefinementCallback_IntersectCylinder Class Reference
lib_grid » algorithms » refinement
If a refined edge intersects the given cylinder, the new vertex will be placed at the intersection.
#include <misc_refinement_projectors.h>
Public Member Functions
virtual void new_vertex (Vertex *vrt, Edge *parent)
called when a new vertex was created from an old edge.
RefinementCallback_IntersectCylinder ()
RefinementCallback_IntersectCylinder (Grid &grid, const vector3 &center, const vector3 &axis, number radius, APosition &aPos=aPosition)
make sure that aPos is attached to the vertices of the grid.
virtual ~RefinementCallback_IntersectCylinder ()
Public Member Functions inherited from ug::RefinementCallbackLinear< APosition >
virtual int current_pos (number *coordsOut, Vertex *vrt, int maxCoords)
Gives access to the position of the current vertex.
virtual void new_vertex (Vertex *vrt, Vertex *parent)
called when a new vertex was created from an old vertex.
virtual void new_vertex (Vertex *vrt, Face *parent)
called when a new vertex was created from an old face.
virtual void new_vertex (Vertex *vrt, Volume *parent)
called when a new vertex was created from an old volume.
RefinementCallbackLinear ()
RefinementCallbackLinear (Grid &grid, APosition &aPos)
make sure that aPos is attached to the vertices of the grid.
virtual ~RefinementCallbackLinear ()
Public Member Functions inherited from ug::IRefinementCallback
virtual void flat_grid_vertex_encountered (Vertex *vrt)
callback for vertices in flat grids.
virtual ~IRefinementCallback ()
Protected Attributes
vector3 m_axis
vector3 m_center
number m_radius
Protected Attributes inherited from ug::RefinementCallbackLinear< APosition >
Grid::VertexAttachmentAccessor< APosition > m_aaPos
Grid * m_pGrid
Additional Inherited Members
Protected Types inherited from ug::RefinementCallbackLinear< APosition >
typedef APosition::ValueType pos_type
Protected Member Functions inherited from ug::IRefinementCallback
template<class TAttachmentAccessor >
int current_pos_helper (number *coordsOut, Vertex *vrt, int maxCoords, TAttachmentAccessor &aaPos)
A helper implementation of current_pos available for derived classes.
Detailed Description
If a refined edge intersects the given cylinder, the new vertex will be placed at the intersection.
Constructor & Destructor Documentation
ug::RefinementCallback_IntersectCylinder::RefinementCallback_IntersectCylinder ()
ug::RefinementCallback_IntersectCylinder::RefinementCallback_IntersectCylinder (Grid & grid, const vector3 & center, const vector3 & axis, number radius, APosition & aPos = aPosition)
make sure that aPos is attached to the vertices of the grid.
References ~RefinementCallback_IntersectCylinder().
ug::RefinementCallback_IntersectCylinder::~RefinementCallback_IntersectCylinder () virtual
References new_vertex().
Referenced by RefinementCallback_IntersectCylinder().
Member Function Documentation
void ug::RefinementCallback_IntersectCylinder::new_vertex (Vertex * vrt, Edge * parent) virtual
called when a new vertex was created from an old edge.
Reimplemented from ug::RefinementCallbackLinear< APosition >.
References ug::RefinementCallbackLinear< APosition >::m_aaPos, m_axis, m_center, m_radius, ug::RefinementCallbackLinear< TAPosition >::new_vertex(), ug::RayCylinderIntersection(), ug::RefinementCallbackEdgePlaneCut::RefinementCallbackEdgePlaneCut(), ug::VecScaleAdd(), ug::VecSubtract(), and ug::EdgeVertices::vertex().
Referenced by ~RefinementCallback_IntersectCylinder().
Member Data Documentation
vector3 ug::RefinementCallback_IntersectCylinder::m_axis protected
Referenced by new_vertex().
vector3 ug::RefinementCallback_IntersectCylinder::m_center protected
Referenced by new_vertex().
number ug::RefinementCallback_IntersectCylinder::m_radius protected
Referenced by new_vertex().
The documentation for this class was generated from the following files:
ugbase/lib_grid/algorithms/refinement/refinement_projectors/misc_refinement_projectors.h
ugbase/lib_grid/algorithms/refinement/refinement_projectors/misc_refinement_projectors.cpp