ug4: ug::PeriodicAttachmentAccessor< TElem, TAttachment > Class Template Reference
ug::PeriodicAttachmentAccessor< TElem, TAttachment > Class Template Reference
Accesses attachements with consideration to periodic boundaries.
#include <periodic_boundary_manager.h>
Public Types
typedef attachment_value_traits< ValueType >::const_reference ConstRefType
typedef attachment_value_traits< ValueType >::reference RefType
typedef TAttachment::ValueType ValueType
Public Member Functions
bool access (Grid &g, TAttachment &a)
RefType operator[] (TElem *e)
ConstRefType operator[] (TElem *e) const
PeriodicAttachmentAccessor ()
PeriodicAttachmentAccessor (Grid &g, TAttachment &a)
PeriodicAttachmentAccessor (PeriodicBoundaryManager &pbm)
Private Attributes
Grid::AttachmentAccessor< TElem, TAttachment > m_aa
PeriodicBoundaryManager * m_pbm
Detailed Description
template<class TElem, class TAttachment>
class ug::PeriodicAttachmentAccessor< TElem, TAttachment >
Accesses attachements with consideration to periodic boundaries.
Slave element redirects to related master element also works in case of no periodic boundary conditions (but is then probably slower than standard attachment accessor)
Member Typedef Documentation
ConstRefType
template<class TElem , class TAttachment > typedef attachment_value_traits<ValueType>::const_reference ug::PeriodicAttachmentAccessor< TElem, TAttachment >::ConstRefType
RefType
template<class TElem , class TAttachment > typedef attachment_value_traits<ValueType>::reference ug::PeriodicAttachmentAccessor< TElem, TAttachment >::RefType
ValueType
template<class TElem , class TAttachment > typedef TAttachment::ValueType ug::PeriodicAttachmentAccessor< TElem, TAttachment >::ValueType
Constructor & Destructor Documentation
PeriodicAttachmentAccessor() [1/3]
template<class TElem , class TAttachment > ug::PeriodicAttachmentAccessor< TElem, TAttachment >::PeriodicAttachmentAccessor () inline
PeriodicAttachmentAccessor() [2/3]
template<class TElem , class TAttachment > ug::PeriodicAttachmentAccessor< TElem, TAttachment >::PeriodicAttachmentAccessor (Grid & g, TAttachment & a) inline
References ug::PeriodicAttachmentAccessor< TElem, TAttachment >::access().
PeriodicAttachmentAccessor() [3/3]
template<class TElem , class TAttachment > ug::PeriodicAttachmentAccessor< TElem, TAttachment >::PeriodicAttachmentAccessor (PeriodicBoundaryManager & pbm) inline
Member Function Documentation
access()
template<class TElem , class TAttachment > bool ug::PeriodicAttachmentAccessor< TElem, TAttachment >::access (Grid & g, TAttachment & a) inline
References ug::PeriodicAttachmentAccessor< TElem, TAttachment >::m_aa, ug::PeriodicAttachmentAccessor< TElem, TAttachment >::m_pbm, and ug::Grid::periodic_boundary_manager().
Referenced by ug::PeriodicAttachmentAccessor< TElem, TAttachment >::PeriodicAttachmentAccessor().
operator[]() [1/2]
template<class TElem , class TAttachment > RefType ug::PeriodicAttachmentAccessor< TElem, TAttachment >::operator[] (TElem * e) inline
References ug::PeriodicBoundaryManager::is_slave(), ug::PeriodicAttachmentAccessor< TElem, TAttachment >::m_aa, ug::PeriodicAttachmentAccessor< TElem, TAttachment >::m_pbm, and ug::PeriodicBoundaryManager::master().
operator[]() [2/2]
template<class TElem , class TAttachment > ConstRefType ug::PeriodicAttachmentAccessor< TElem, TAttachment >::operator[] (TElem * e) const inline
References ug::PeriodicBoundaryManager::is_slave(), ug::PeriodicAttachmentAccessor< TElem, TAttachment >::m_aa, ug::PeriodicAttachmentAccessor< TElem, TAttachment >::m_pbm, and ug::PeriodicBoundaryManager::master().
Member Data Documentation
m_aa
template<class TElem , class TAttachment > Grid::AttachmentAccessor<TElem, TAttachment> ug::PeriodicAttachmentAccessor< TElem, TAttachment >::m_aa private
Referenced by ug::PeriodicAttachmentAccessor< TElem, TAttachment >::access(), and ug::PeriodicAttachmentAccessor< TElem, TAttachment >::operator[]().
m_pbm
template<class TElem , class TAttachment > PeriodicBoundaryManager* ug::PeriodicAttachmentAccessor< TElem, TAttachment >::m_pbm private
Referenced by ug::PeriodicAttachmentAccessor< TElem, TAttachment >::access(), and ug::PeriodicAttachmentAccessor< TElem, TAttachment >::operator[]().
The documentation for this class was generated from the following file:
ugbase/lib_grid/tools/periodic_boundary_manager.h