ug4: ug::UndirectedMatrix< T > Class Template Reference
ug::UndirectedMatrix< T > Class Template Reference
#include <undirected.h>
Classes
class edge
class map_type
Public Types
typedef boost::geometry::concatenate_iterator< boost::SM_adjacency_iterator< value_type >, G_adj_it, int, int > adjacency_iterator
typedef boost::adjacency_list< boost::vecS, boost::vecS > G
typedef boost::graph_traits< G >::adjacency_iterator G_adj_it
typedef boost::graph_traits< T >::adjacency_iterator T_adj_it
typedef T::value_type value_type
Public Member Functions
adjacency_iterator begin_row (int row) const
int degree (int v) const
adjacency_iterator end_row (int row) const
int in_degree (int v) const
int num_cols () const
int num_rows () const
UndirectedMatrix & operator= (UndirectedMatrix const &o)
int out_degree (int v) const
void refresh ()
UndirectedMatrix (T const *m=nullptr)
UndirectedMatrix (UndirectedMatrix &&o)=delete
UndirectedMatrix (UndirectedMatrix const &o)
Private Types
typedef T::const_row_iterator const_row_iterator
Private Attributes
G _extra_fill
T const * _matrix
Member Typedef Documentation
adjacency_iterator
template<class T > typedef boost::geometry::concatenate_iterator< boost::SM_adjacency_iterator<value_type>, G_adj_it, int, int> ug::UndirectedMatrix< T >::adjacency_iterator
const_row_iterator
template<class T > typedef T::const_row_iterator ug::UndirectedMatrix< T >::const_row_iterator private
G
template<class T > typedef boost::adjacency_list<boost::vecS, boost::vecS> ug::UndirectedMatrix< T >::G
G_adj_it
template<class T > typedef boost::graph_traits<G>::adjacency_iterator ug::UndirectedMatrix< T >::G_adj_it
T_adj_it
template<class T > typedef boost::graph_traits<T>::adjacency_iterator ug::UndirectedMatrix< T >::T_adj_it
value_type
template<class T > typedef T::value_type ug::UndirectedMatrix< T >::value_type
Constructor & Destructor Documentation
UndirectedMatrix() [1/3]
template<class T > ug::UndirectedMatrix< T >::UndirectedMatrix (T const * m = nullptr) inline explicit
References ug::UndirectedMatrix< T >::refresh(), and untested.
UndirectedMatrix() [2/3]
template<class T > ug::UndirectedMatrix< T >::UndirectedMatrix (UndirectedMatrix< T > && o) delete
UndirectedMatrix() [3/3]
template<class T > ug::UndirectedMatrix< T >::UndirectedMatrix (UndirectedMatrix< T > const & o) inline explicit
References untested.
Member Function Documentation
begin_row()
template<class T > adjacency_iterator ug::UndirectedMatrix< T >::begin_row (int row) const inline
References ug::UndirectedMatrix< T >::_extra_fill, ug::UndirectedMatrix< T >::_matrix, and boost::adjacent_vertices().
Referenced by boost::adjacent_vertices(), and boost::out_edges().
degree()
template<class T > int ug::UndirectedMatrix< T >::degree (int v) const inline
References ug::UndirectedMatrix< T >::out_degree().
Referenced by boost::degree().
end_row()
template<class T > adjacency_iterator ug::UndirectedMatrix< T >::end_row (int row) const inline
References ug::UndirectedMatrix< T >::_extra_fill, ug::UndirectedMatrix< T >::_matrix, and boost::adjacent_vertices().
Referenced by boost::adjacent_vertices(), and boost::out_edges().
in_degree()
template<class T > int ug::UndirectedMatrix< T >::in_degree (int v) const inline
References ug::UndirectedMatrix< T >::_extra_fill, ug::UndirectedMatrix< T >::_matrix, and boost::out_degree().
Referenced by ug::UndirectedMatrix< T >::out_degree().
num_cols()
template<class T > int ug::UndirectedMatrix< T >::num_cols () const inline
References ug::UndirectedMatrix< T >::num_rows(), and untested.
num_rows()
template<class T > int ug::UndirectedMatrix< T >::num_rows () const inline
References ug::UndirectedMatrix< T >::_matrix.
Referenced by ug::UndirectedMatrix< T >::num_cols(), boost::num_vertices(), and boost::vertices().
operator=()
template<class T > UndirectedMatrix& ug::UndirectedMatrix< T >::operator= (UndirectedMatrix< T > const & o) inline
References ug::UndirectedMatrix< T >::_extra_fill, ug::UndirectedMatrix< T >::_matrix, and untested.
out_degree()
template<class T > int ug::UndirectedMatrix< T >::out_degree (int v) const inline
References ug::UndirectedMatrix< T >::in_degree().
Referenced by ug::UndirectedMatrix< T >::degree().
refresh()
template<class T > void ug::UndirectedMatrix< T >::refresh
References boost::adjacent_vertices(), ug::get_clock_s(), itested, and UG_LOG.
Referenced by ug::UndirectedMatrix< T >::UndirectedMatrix().
Member Data Documentation
_extra_fill
template<class T > G ug::UndirectedMatrix< T >::_extra_fill private
Referenced by ug::UndirectedMatrix< T >::begin_row(), ug::UndirectedMatrix< T >::end_row(), ug::UndirectedMatrix< T >::in_degree(), and ug::UndirectedMatrix< T >::operator=().
_matrix
template<class T > T const* ug::UndirectedMatrix< T >::_matrix private
Referenced by ug::UndirectedMatrix< T >::begin_row(), ug::UndirectedMatrix< T >::end_row(), ug::UndirectedMatrix< T >::in_degree(), ug::UndirectedMatrix< T >::num_rows(), and ug::UndirectedMatrix< T >::operator=().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/graph_interface/undirected.h