ug4: ug::IsSelected Class Reference
ug::IsSelected Class Reference
lib_grid » element_callbacks
Element callback that returns true, if an element is selected.
#include <selection_callbacks.h>
Public Member Functions
IsSelected (const ISelector &sel)
bool operator() (Edge *e) const
bool operator() (Face *f) const
bool operator() (Vertex *v) const
bool operator() (Volume *v) const
Public Member Functions inherited from ug::ElementCallback
ElementCallback ()
virtual ~ElementCallback ()
Private Member Functions
template<class TElem >
bool callback (TElem *e) const
Private Attributes
const ISelector & m_sel
Detailed Description
Element callback that returns true, if an element is selected.
Constructor & Destructor Documentation
IsSelected()
ug::IsSelected::IsSelected (const ISelector & sel) inline
Member Function Documentation
callback()
template<class TElem > bool ug::IsSelected::callback (TElem * e) const inline private
References ug::ISelector::is_selected(), and m_sel.
Referenced by operator()().
operator()() [1/4]
bool ug::IsSelected::operator() (Edge * e) const inline virtual
Implements ug::ElementCallback.
References callback().
operator()() [2/4]
bool ug::IsSelected::operator() (Face * f) const inline virtual
Implements ug::ElementCallback.
References callback().
operator()() [3/4]
bool ug::IsSelected::operator() (Vertex * v) const inline virtual
Implements ug::ElementCallback.
References callback().
operator()() [4/4]
bool ug::IsSelected::operator() (Volume * v) const inline virtual
Implements ug::ElementCallback.
References callback().
Member Data Documentation
m_sel
const ISelector& ug::IsSelected::m_sel private
Referenced by callback().
The documentation for this class was generated from the following file:
ugbase/lib_grid/callbacks/selection_callbacks.h