ug4: ug::LFEID Class Reference
ug::LFEID Class Reference
lib_discretization » Local Finite Elements
Identifier for Local Finite Elements.
#include <local_finite_element_id.h>
Public Types
enum { ADAPTIV = -1 , INVALID = -10 }
special possibilities for order
enum SpaceType {
NONE = -1 , LAGRANGE = 0 , CROUZEIX_RAVIART , PIECEWISE_CONSTANT ,
DG , MINI , NEDELEC , USER_DEFINED ,
NUM_SPACE_TYPES
}
Space Type.
Public Member Functions
int dim () const
returns the space dimension of the local finite element
LFEID ()
default constructor
LFEID (SpaceType type, int dim, int order)
constructor with values
bool operator!= (const LFEID &v) const
inequality check
bool operator< (const LFEID &v) const
operator <
bool operator<= (const LFEID &v) const
operator <=
bool operator== (const LFEID &v) const
equality check
bool operator> (const LFEID &v) const
operator >
bool operator>= (const LFEID &v) const
operator >=
int order () const
returns the order of the local finite element
SpaceType type () const
returns the type of the local finite element
Private Attributes
int m_dim
dimension
int m_order
Order.
SpaceType m_type
Space type.
Friends
std::ostream & operator<< (std::ostream &out, const LFEID &v)
writes the Identifier to the output stream
Detailed Description
Identifier for Local Finite Elements.
This Class is used to distinguish between different local finite elements (lfe). Each lfe has a unique Space Type (e.g. Lagrange, DG) and the order of trial functions. It the function space is p-adaptive, the enum ADAPTIVE is set as order.
Member Enumeration Documentation
anonymous enum
anonymous enum
special possibilities for order
Enumerator
ADAPTIV
INVALID
SpaceType
enum ug::LFEID::SpaceType
Space Type.
Enumerator
NONE
LAGRANGE
CROUZEIX_RAVIART
PIECEWISE_CONSTANT
DG
MINI
NEDELEC
USER_DEFINED
NUM_SPACE_TYPES
Constructor & Destructor Documentation
LFEID() [1/2]
ug::LFEID::LFEID () inline
default constructor
LFEID() [2/2]
ug::LFEID::LFEID (SpaceType type, int dim, int order) inline
constructor with values
Member Function Documentation
dim()
int ug::LFEID::dim () const inline
returns the space dimension of the local finite element
References m_dim.
Referenced by ug::FunctionPattern::add(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_error(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), ug::ComputeOrientationOffsetGeneric(), ug::CrouzeixRaviartElemTransfer< TDomain >::do_restrict(), ug::PiecewiseConstantElemTransfer< TDomain >::perform_prolongation_on(), ug::P1LagrangeElemTransfer< TDomain >::perform_prolongation_on(), ug::StdLagrangeElemTransfer< TDomain >::perform_prolongation_on(), ug::CrouzeixRaviartElemTransfer< TDomain >::perform_prolongation_on(), ug::PiecewiseConstantElemTransfer< TDomain >::perform_restriction_on(), ug::StdLagrangeElemTransfer< TDomain >::perform_restriction_on(), ug::CrouzeixRaviartElemTransfer< TDomain >::perform_restriction_on(), and ug::CrouzeixRaviartElemTransfer< TDomain >::prolongate().
operator!=()
bool ug::LFEID::operator!= (const LFEID & v) const inline
inequality check
operator<()
bool ug::LFEID::operator< (const LFEID & v) const inline
operator <
returns comparison which set id is regarded lesser The Local Finite Elements are ordered by type first, then by dimension and then by increasing order.
References m_dim, m_order, and m_type.
operator<=()
bool ug::LFEID::operator<= (const LFEID & v) const inline
operator <=
operator==()
bool ug::LFEID::operator== (const LFEID & v) const inline
equality check
References m_dim, m_order, and m_type.
operator>()
bool ug::LFEID::operator> (const LFEID & v) const inline
operator >
References m_dim, m_order, and m_type.
operator>=()
bool ug::LFEID::operator>= (const LFEID & v) const inline
operator >=
order()
int ug::LFEID::order () const inline
returns the order of the local finite element
References m_order.
Referenced by ug::FunctionPattern::add(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_error(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::AssembleInjectionForP1Lagrange(), ug::ComputeOrientationOffsetGeneric(), ug::GetStandardElementProlongation(), ug::GetStandardElementRestriction(), ug::StdLagrangeElemTransfer< TDomain >::perform_prolongation_on(), ug::Prolongate(), ug::Restrict(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update(), ug::DimFEGeometry< TWorldDim, TRefDim >::update(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update_local(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_local(), ug::DimFVGeometry< TWorldDim, TDim >::update_local(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local().
type()
SpaceType ug::LFEID::type () const inline
returns the type of the local finite element
References m_type.
Referenced by ug::FunctionPattern::add(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_error(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::StdTransfer< TDomain, TAlgebra >::assemble_restriction(), ug::AssembleInjectionForP1Lagrange(), ug::ComputeOrientationOffsetGeneric(), ug::GetStandardElementProlongation(), ug::GetStandardElementRestriction(), ug::Prolongate(), ug::Restrict(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const LFEID & v) friend
writes the Identifier to the output stream
Member Data Documentation
m_dim
int ug::LFEID::m_dim private
dimension
Referenced by dim(), operator<(), operator==(), and operator>().
m_order
int ug::LFEID::m_order private
Order.
Referenced by operator<(), operator==(), operator>(), and order().
m_type
SpaceType ug::LFEID::m_type private
Space type.
Referenced by operator<(), operator==(), operator>(), and type().
The documentation for this class was generated from the following file:
ugbase/lib_disc/local_finite_element/local_finite_element_id.h