ug4: ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF Class Reference
ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF Class Reference
boundary face
#include <fv1_geom.h>
Public Member Functions
BF ()
number detJ () const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_corner (size_t co) const
return global corner number i
const MathVector< worldDim > & global_grad (size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector () const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip () const
global integration point of bf
const MathMatrix< worldDim, dim > & JTInv () const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector () const
vector of local gradients in ip point
const MathVector< dim > & local_ip () const
local integration point of bf
size_t node_id () const
index of SubControlVolume of the bf
const MathVector< worldDim > & normal () const
outer normal on bf. Norm is equal to area
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points on bf
size_t num_sh () const
number of shape functions
number shape (size_t sh) const
value of shape function i in integration point
const number * shape_vector () const
vector of local gradients in ip point
number volume () const
volume of bf
Static Public Attributes
static const size_t numCo = traits::NumCornersOfBF
Number of corners of bf.
Private Attributes
number detj
MathVector< worldDim > globalIP
MathMatrix< worldDim, dim > JtInv
MathVector< dim > localIP
size_t nodeId
MathVector< worldDim > Normal
MathVector< worldDim > vGlobalGrad [nsh]
MathVector< worldDim > vGloPos [numCo]
MathVector< dim > vLocalGrad [nsh]
MathVector< dim > vLocPos [numCo]
MidID vMidID [numCo]
number Vol
number vShape [nsh]
Friends
class FV1Geometry_gen< TElem, TWorldDim, TCondensed >
let outer class access private members
Detailed Description
template<typename TElem, int TWorldDim, bool TCondensed>
class ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF
boundary face
Constructor & Destructor Documentation
BF()
template<typename TElem , int TWorldDim, bool TCondensed> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::BF () inline
Member Function Documentation
detJ()
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::detJ () const inline
Determinant of Jacobian in integration point.
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::detj.
global_corner()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<worldDim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::global_corner (size_t co) const inline
return global corner number i
global_grad()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<worldDim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::global_grad (size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::num_sh(), UG_ASSERT, and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vGlobalGrad.
global_grad_vector()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<worldDim>* ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::global_grad_vector () const inline
vector of global gradients in ip point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vGlobalGrad.
global_ip()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<worldDim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::global_ip () const inline
global integration point of bf
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::globalIP.
JTInv()
template<typename TElem , int TWorldDim, bool TCondensed> const MathMatrix<worldDim, dim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::JTInv () const inline
Transposed Inverse of Jacobian in integration point.
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::JtInv.
local_corner()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<dim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::local_corner (size_t co) const inline
return local corner number i
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::num_corners(), UG_ASSERT, and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vLocPos.
local_grad()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<dim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::local_grad (size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::num_sh(), UG_ASSERT, and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vLocalGrad.
local_grad_vector()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<dim>* ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::local_grad_vector () const inline
vector of local gradients in ip point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vLocalGrad.
local_ip()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<dim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::local_ip () const inline
local integration point of bf
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::localIP.
node_id()
template<typename TElem , int TWorldDim, bool TCondensed> size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::node_id () const inline
index of SubControlVolume of the bf
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::nodeId.
normal()
template<typename TElem , int TWorldDim, bool TCondensed> const MathVector<worldDim>& ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::normal () const inline
outer normal on bf. Norm is equal to area
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::Normal.
num_corners()
template<typename TElem , int TWorldDim, bool TCondensed> size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::num_corners () const inline
number of corners, that bound the scvf
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::numCo.
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::local_corner().
num_ip()
template<typename TElem , int TWorldDim, bool TCondensed> size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::num_ip () const inline
number of integration points on bf
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::nip.
num_sh()
template<typename TElem , int TWorldDim, bool TCondensed> size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::num_sh () const inline
number of shape functions
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::nsh.
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::global_grad(), ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::local_grad(), and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::shape().
shape()
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::shape (size_t sh) const inline
value of shape function i in integration point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::num_sh(), UG_ASSERT, and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vShape.
shape_vector()
template<typename TElem , int TWorldDim, bool TCondensed> const number* ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::shape_vector () const inline
vector of local gradients in ip point
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vShape.
volume()
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::volume () const inline
volume of bf
References ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::Vol.
Friends And Related Function Documentation
FV1Geometry_gen< TElem, TWorldDim, TCondensed >
template<typename TElem , int TWorldDim, bool TCondensed> friend class FV1Geometry_gen< TElem, TWorldDim, TCondensed > friend
let outer class access private members
Member Data Documentation
detj
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::detj private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::detJ().
globalIP
template<typename TElem , int TWorldDim, bool TCondensed> MathVector<worldDim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::globalIP private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::global_ip().
JtInv
template<typename TElem , int TWorldDim, bool TCondensed> MathMatrix<worldDim,dim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::JtInv private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::JTInv().
localIP
template<typename TElem , int TWorldDim, bool TCondensed> MathVector<dim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::localIP private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::local_ip().
nodeId
template<typename TElem , int TWorldDim, bool TCondensed> size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::nodeId private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::node_id().
Normal
template<typename TElem , int TWorldDim, bool TCondensed> MathVector<worldDim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::Normal private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::normal().
numCo
template<typename TElem , int TWorldDim, bool TCondensed> const size_t ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::numCo = traits::NumCornersOfBF static
Number of corners of bf.
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::num_corners().
vGlobalGrad
template<typename TElem , int TWorldDim, bool TCondensed> MathVector<worldDim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vGlobalGrad[nsh] private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::global_grad(), and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::global_grad_vector().
vGloPos
template<typename TElem , int TWorldDim, bool TCondensed> MathVector<worldDim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vGloPos[numCo] private
vLocalGrad
template<typename TElem , int TWorldDim, bool TCondensed> MathVector<dim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vLocalGrad[nsh] private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::local_grad(), and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::local_grad_vector().
vLocPos
template<typename TElem , int TWorldDim, bool TCondensed> MathVector<dim> ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vLocPos[numCo] private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::local_corner().
vMidID
template<typename TElem , int TWorldDim, bool TCondensed> MidID ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vMidID[numCo] private
Vol
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::Vol private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::volume().
vShape
template<typename TElem , int TWorldDim, bool TCondensed> number ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::vShape[nsh] private
Referenced by ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::shape(), and ug::FV1Geometry_gen< TElem, TWorldDim, TCondensed >::BF::shape_vector().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv1_geom.h