ug4: ug::FetiLayouts< TAlgebra > Class Template Reference
ug::FetiLayouts< TAlgebra > Class Template Reference
Auxiliary class for handling of "FETI layouts".
#include <feti.h>
Public Types
typedef TAlgebra algebra_type
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Member Functions
void create_layouts (ConstSmartPtr< AlgebraLayouts > stdLayouts, size_t numIndices, pcl::IDomainDecompositionInfo &DDInfo, bool bDebug=false)
FetiLayouts ()
const std::vector< IndexLayout::Element > & get_dual_indices () const
const std::vector< IndexLayout::Element > & get_dual_master_indices () const
IndexLayout & get_dual_master_layout ()
const std::vector< IndexLayout::Element > & get_dual_nbr_master_indices () const
IndexLayout & get_dual_nbr_master_layout ()
const std::vector< IndexLayout::Element > & get_dual_nbr_slave_indices () const
IndexLayout & get_dual_nbr_slave_layout ()
const std::vector< IndexLayout::Element > & get_dual_slave_indices () const
IndexLayout & get_dual_slave_layout ()
IndexLayout & get_intra_sd_master_layout ()
pcl::ProcessCommunicator & get_intra_sd_process_communicator ()
IndexLayout & get_intra_sd_slave_layout ()
const std::vector< IndexLayout::Element > & get_primal_indices () const
const std::vector< IndexLayout::Element > & get_primal_master_indices () const
IndexLayout & get_primal_master_layout ()
const std::vector< IndexLayout::Element > & get_primal_slave_indices () const
IndexLayout & get_primal_slave_layout ()
const IndexLayout & get_std_master_layout ()
const pcl::ProcessCommunicator & get_std_process_communicator ()
const IndexLayout & get_std_slave_layout ()
void mat_set_dirichlet_on_dual (matrix_type &mat)
void mat_set_dirichlet_on_primal (matrix_type &mat)
void mat_use_intra_sd_communication (matrix_type &mat)
void mat_use_std_communication (matrix_type &mat)
void test_layouts (bool bPrint)
number vec_norm_on_identified_dual (vector_type &vec)
calculates norm on dual
number vec_prod_on_identified_dual (const vector_type &vecSrc1, const vector_type &vecSrc2)
void vec_scale_add_on_dual (vector_type &vecDest, number alpha1, const vector_type &vecSrc1, number alpha2, const vector_type &vecSrc2)
calculates vecDest = alpha1*vecSource1 + alpha2*vecSource2 on dual
void vec_scale_add_on_primal (vector_type &vecDest, number alpha1, const vector_type &vecSrc1, number alpha2, const vector_type &vecSrc2)
calculates vecDest = alpha1*vecSource1 + alpha2*vecSource2 on primal
void vec_scale_append_on_dual (vector_type &vecInOut, const vector_type &vecSrc1, number alpha1)
calculates vecInOut += alpha1*vecSrc1 on dual
void vec_scale_append_on_primal (vector_type &vecInOut, const vector_type &vecSrc1, number alpha1)
calculates vecInOut += alpha1*vecSrc1 on primal
void vec_scale_assign_on_dual (vector_type &vecDest, const vector_type &vecSrc, number alpha)
calculates vecDest = alpha*vecSrc on dual
void vec_scale_assign_on_primal (vector_type &vecDest, const vector_type &vecSrc, number alpha)
calculates vecDest = alpha*vecSrc on primal
void vec_set_on_dual (vector_type &vecDest, number alpha)
sets vecDest = alpha on dual
void vec_set_on_primal (vector_type &vecDest, number alpha)
sets vecDest = alpha on primal
void vec_use_intra_sd_communication (vector_type &vec)
void vec_use_std_communication (vector_type &vec)
Protected Member Functions
void add_merge_sort_remove_doubles (std::vector< IndexLayout::Element > &vOut, const std::vector< IndexLayout::Element > &v)
void sort_and_remove_doubles (std::vector< IndexLayout::Element > &vIndex)
Protected Attributes
IndexLayout m_masterDualLayout
IndexLayout m_masterDualNbrLayout
IndexLayout m_masterPrimalLayout
IndexLayout m_slaveDualLayout
IndexLayout m_slaveDualNbrLayout
IndexLayout m_slavePrimalLayout
SmartPtr< AlgebraLayouts > m_spInnerLayouts
ConstSmartPtr< AlgebraLayouts > m_spStdLayouts
std::vector< IndexLayout::Element > m_vUniqueDualIndex
std::vector< IndexLayout::Element > m_vUniqueMasterDualIndex
std::vector< IndexLayout::Element > m_vUniqueMasterDualNbrIndex
std::vector< IndexLayout::Element > m_vUniquePrimalIndex
std::vector< IndexLayout::Element > m_vUniquePrimalMasterIndex
std::vector< IndexLayout::Element > m_vUniquePrimalSlaveIndex
std::vector< IndexLayout::Element > m_vUniqueSlaveDualIndex
std::vector< IndexLayout::Element > m_vUniqueSlaveDualNbrIndex
Detailed Description
template<typename TAlgebra>
class ug::FetiLayouts< TAlgebra >
Auxiliary class for handling of "FETI layouts".
This class groups all layouts used in FETI method together and provides useful functions on those.
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::FetiLayouts< TAlgebra >::algebra_type
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::FetiLayouts< TAlgebra >::matrix_type
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::FetiLayouts< TAlgebra >::vector_type
Constructor & Destructor Documentation
FetiLayouts()
template<typename TAlgebra > ug::FetiLayouts< TAlgebra >::FetiLayouts () inline
Member Function Documentation
add_merge_sort_remove_doubles()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::add_merge_sort_remove_doubles (std::vector< IndexLayout::Element > & vOut, const std::vector< IndexLayout::Element > & v) inline protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts().
create_layouts()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::create_layouts (ConstSmartPtr< AlgebraLayouts > stdLayouts, size_t numIndices, pcl::IDomainDecompositionInfo & DDInfo, bool bDebug = false) inline
References ug::FetiLayouts< TAlgebra >::add_merge_sort_remove_doubles(), ug::BuildDomainDecompositionLayouts(), pcl::CollectElements(), pcl::ProcessCommunicator::create_sub_communicator(), pcl::IDomainDecompositionInfo::get_num_subdomains(), ug::FetiLayouts< TAlgebra >::m_masterDualLayout, ug::FetiLayouts< TAlgebra >::m_masterDualNbrLayout, ug::FetiLayouts< TAlgebra >::m_masterPrimalLayout, ug::FetiLayouts< TAlgebra >::m_slaveDualLayout, ug::FetiLayouts< TAlgebra >::m_slaveDualNbrLayout, ug::FetiLayouts< TAlgebra >::m_slavePrimalLayout, ug::FetiLayouts< TAlgebra >::m_spInnerLayouts, ug::FetiLayouts< TAlgebra >::m_spStdLayouts, ug::FetiLayouts< TAlgebra >::m_vUniqueDualIndex, ug::FetiLayouts< TAlgebra >::m_vUniqueMasterDualIndex, ug::FetiLayouts< TAlgebra >::m_vUniqueMasterDualNbrIndex, ug::FetiLayouts< TAlgebra >::m_vUniquePrimalIndex, ug::FetiLayouts< TAlgebra >::m_vUniquePrimalMasterIndex, ug::FetiLayouts< TAlgebra >::m_vUniquePrimalSlaveIndex, ug::FetiLayouts< TAlgebra >::m_vUniqueSlaveDualIndex, ug::FetiLayouts< TAlgebra >::m_vUniqueSlaveDualNbrIndex, pcl::IDomainDecompositionInfo::map_proc_id_to_subdomain_id(), pcl::PrintLayout(), pcl::ProcRank(), ug::FetiLayouts< TAlgebra >::sort_and_remove_doubles(), and UG_LOG.
get_dual_indices()
template<typename TAlgebra > const std::vector<IndexLayout::Element>& ug::FetiLayouts< TAlgebra >::get_dual_indices () const inline
References ug::FetiLayouts< TAlgebra >::m_vUniqueDualIndex.
get_dual_master_indices()
template<typename TAlgebra > const std::vector<IndexLayout::Element>& ug::FetiLayouts< TAlgebra >::get_dual_master_indices () const inline
References ug::FetiLayouts< TAlgebra >::m_vUniqueMasterDualIndex.
get_dual_master_layout()
template<typename TAlgebra > IndexLayout& ug::FetiLayouts< TAlgebra >::get_dual_master_layout () inline
References ug::FetiLayouts< TAlgebra >::m_masterDualLayout.
get_dual_nbr_master_indices()
template<typename TAlgebra > const std::vector<IndexLayout::Element>& ug::FetiLayouts< TAlgebra >::get_dual_nbr_master_indices () const inline
References ug::FetiLayouts< TAlgebra >::m_vUniqueMasterDualNbrIndex.
get_dual_nbr_master_layout()
template<typename TAlgebra > IndexLayout& ug::FetiLayouts< TAlgebra >::get_dual_nbr_master_layout () inline
References ug::FetiLayouts< TAlgebra >::m_masterDualNbrLayout.
get_dual_nbr_slave_indices()
template<typename TAlgebra > const std::vector<IndexLayout::Element>& ug::FetiLayouts< TAlgebra >::get_dual_nbr_slave_indices () const inline
References ug::FetiLayouts< TAlgebra >::m_vUniqueSlaveDualNbrIndex.
get_dual_nbr_slave_layout()
template<typename TAlgebra > IndexLayout& ug::FetiLayouts< TAlgebra >::get_dual_nbr_slave_layout () inline
References ug::FetiLayouts< TAlgebra >::m_slaveDualNbrLayout.
get_dual_slave_indices()
template<typename TAlgebra > const std::vector<IndexLayout::Element>& ug::FetiLayouts< TAlgebra >::get_dual_slave_indices () const inline
References ug::FetiLayouts< TAlgebra >::m_vUniqueSlaveDualIndex.
get_dual_slave_layout()
template<typename TAlgebra > IndexLayout& ug::FetiLayouts< TAlgebra >::get_dual_slave_layout () inline
References ug::FetiLayouts< TAlgebra >::m_slaveDualLayout.
get_intra_sd_master_layout()
template<typename TAlgebra > IndexLayout& ug::FetiLayouts< TAlgebra >::get_intra_sd_master_layout () inline
References ug::FetiLayouts< TAlgebra >::m_spInnerLayouts.
get_intra_sd_process_communicator()
template<typename TAlgebra > pcl::ProcessCommunicator& ug::FetiLayouts< TAlgebra >::get_intra_sd_process_communicator () inline
References ug::FetiLayouts< TAlgebra >::m_spInnerLayouts.
get_intra_sd_slave_layout()
template<typename TAlgebra > IndexLayout& ug::FetiLayouts< TAlgebra >::get_intra_sd_slave_layout () inline
References ug::FetiLayouts< TAlgebra >::m_spInnerLayouts.
get_primal_indices()
template<typename TAlgebra > const std::vector<IndexLayout::Element>& ug::FetiLayouts< TAlgebra >::get_primal_indices () const inline
References ug::FetiLayouts< TAlgebra >::m_vUniquePrimalIndex.
get_primal_master_indices()
template<typename TAlgebra > const std::vector<IndexLayout::Element>& ug::FetiLayouts< TAlgebra >::get_primal_master_indices () const inline
References ug::FetiLayouts< TAlgebra >::m_vUniquePrimalMasterIndex.
get_primal_master_layout()
template<typename TAlgebra > IndexLayout& ug::FetiLayouts< TAlgebra >::get_primal_master_layout () inline
References ug::FetiLayouts< TAlgebra >::m_masterPrimalLayout.
get_primal_slave_indices()
template<typename TAlgebra > const std::vector<IndexLayout::Element>& ug::FetiLayouts< TAlgebra >::get_primal_slave_indices () const inline
References ug::FetiLayouts< TAlgebra >::m_vUniquePrimalSlaveIndex.
get_primal_slave_layout()
template<typename TAlgebra > IndexLayout& ug::FetiLayouts< TAlgebra >::get_primal_slave_layout () inline
References ug::FetiLayouts< TAlgebra >::m_slavePrimalLayout.
get_std_master_layout()
template<typename TAlgebra > const IndexLayout& ug::FetiLayouts< TAlgebra >::get_std_master_layout () inline
References ug::FetiLayouts< TAlgebra >::m_spStdLayouts.
Referenced by ug::FetiLayouts< TAlgebra >::mat_use_std_communication().
get_std_process_communicator()
template<typename TAlgebra > const pcl::ProcessCommunicator& ug::FetiLayouts< TAlgebra >::get_std_process_communicator () inline
References ug::FetiLayouts< TAlgebra >::m_spStdLayouts.
Referenced by ug::FetiLayouts< TAlgebra >::mat_use_std_communication().
get_std_slave_layout()
template<typename TAlgebra > const IndexLayout& ug::FetiLayouts< TAlgebra >::get_std_slave_layout () inline
References ug::FetiLayouts< TAlgebra >::m_spStdLayouts.
Referenced by ug::FetiLayouts< TAlgebra >::mat_use_std_communication().
mat_set_dirichlet_on_dual()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::mat_set_dirichlet_on_dual (matrix_type & mat) inline
References ug::FetiLayouts< TAlgebra >::m_vUniqueDualIndex, and ug::SetDirichletRow().
mat_set_dirichlet_on_primal()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::mat_set_dirichlet_on_primal (matrix_type & mat) inline
References ug::FetiLayouts< TAlgebra >::m_vUniquePrimalIndex, and ug::SetDirichletRow().
mat_use_intra_sd_communication()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::mat_use_intra_sd_communication (matrix_type & mat) inline
References ug::FetiLayouts< TAlgebra >::m_spInnerLayouts.
mat_use_std_communication()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::mat_use_std_communication (matrix_type & mat) inline
References ug::FetiLayouts< TAlgebra >::get_std_master_layout(), ug::FetiLayouts< TAlgebra >::get_std_process_communicator(), and ug::FetiLayouts< TAlgebra >::get_std_slave_layout().
sort_and_remove_doubles()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::sort_and_remove_doubles (std::vector< IndexLayout::Element > & vIndex) inline protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts().
test_layouts()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::test_layouts (bool bPrint) inline
References ug::FetiLayouts< TAlgebra >::m_masterDualLayout, ug::FetiLayouts< TAlgebra >::m_masterDualNbrLayout, ug::FetiLayouts< TAlgebra >::m_masterPrimalLayout, ug::FetiLayouts< TAlgebra >::m_slaveDualLayout, ug::FetiLayouts< TAlgebra >::m_slaveDualNbrLayout, ug::FetiLayouts< TAlgebra >::m_slavePrimalLayout, ug::FetiLayouts< TAlgebra >::m_spInnerLayouts, ug::FetiLayouts< TAlgebra >::m_spStdLayouts, pcl::TestLayout(), and UG_LOG.
vec_norm_on_identified_dual()
template<typename TAlgebra > number ug::FetiLayouts< TAlgebra >::vec_norm_on_identified_dual (vector_type & vec) inline
calculates norm on dual
References ug::FetiLayouts< TAlgebra >::vec_prod_on_identified_dual().
vec_prod_on_identified_dual()
template<typename TAlgebra > number ug::FetiLayouts< TAlgebra >::vec_prod_on_identified_dual (const vector_type & vecSrc1, const vector_type & vecSrc2) inline
References ug::FetiLayouts< TAlgebra >::m_spStdLayouts, ug::FetiLayouts< TAlgebra >::m_vUniqueMasterDualIndex, PCL_DT_DOUBLE, PCL_RO_SUM, and ug::VecProd().
Referenced by ug::FetiLayouts< TAlgebra >::vec_norm_on_identified_dual().
vec_scale_add_on_dual()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::vec_scale_add_on_dual (vector_type & vecDest, number alpha1, const vector_type & vecSrc1, number alpha2, const vector_type & vecSrc2) inline
calculates vecDest = alpha1*vecSource1 + alpha2*vecSource2 on dual
References ug::FetiLayouts< TAlgebra >::m_vUniqueDualIndex, and ug::VecScaleAdd().
vec_scale_add_on_primal()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::vec_scale_add_on_primal (vector_type & vecDest, number alpha1, const vector_type & vecSrc1, number alpha2, const vector_type & vecSrc2) inline
calculates vecDest = alpha1*vecSource1 + alpha2*vecSource2 on primal
References ug::FetiLayouts< TAlgebra >::m_vUniquePrimalIndex, and ug::VecScaleAdd().
vec_scale_append_on_dual()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::vec_scale_append_on_dual (vector_type & vecInOut, const vector_type & vecSrc1, number alpha1) inline
calculates vecInOut += alpha1*vecSrc1 on dual
References ug::FetiLayouts< TAlgebra >::m_vUniqueDualIndex, and ug::VecScaleAdd().
vec_scale_append_on_primal()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::vec_scale_append_on_primal (vector_type & vecInOut, const vector_type & vecSrc1, number alpha1) inline
calculates vecInOut += alpha1*vecSrc1 on primal
References ug::FetiLayouts< TAlgebra >::m_vUniquePrimalIndex, and ug::VecScaleAdd().
vec_scale_assign_on_dual()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::vec_scale_assign_on_dual (vector_type & vecDest, const vector_type & vecSrc, number alpha) inline
calculates vecDest = alpha*vecSrc on dual
References alpha, ug::FetiLayouts< TAlgebra >::m_vUniqueDualIndex, and ug::VecScaleAssign().
vec_scale_assign_on_primal()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::vec_scale_assign_on_primal (vector_type & vecDest, const vector_type & vecSrc, number alpha) inline
calculates vecDest = alpha*vecSrc on primal
References alpha, ug::FetiLayouts< TAlgebra >::m_vUniquePrimalIndex, and ug::VecScaleAssign().
vec_set_on_dual()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::vec_set_on_dual (vector_type & vecDest, number alpha) inline
sets vecDest = alpha on dual
References alpha, ug::FetiLayouts< TAlgebra >::m_vUniqueDualIndex, and ug::VecSet().
vec_set_on_primal()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::vec_set_on_primal (vector_type & vecDest, number alpha) inline
sets vecDest = alpha on primal
References alpha, ug::FetiLayouts< TAlgebra >::m_vUniquePrimalIndex, and ug::VecSet().
vec_use_intra_sd_communication()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::vec_use_intra_sd_communication (vector_type & vec) inline
References ug::FetiLayouts< TAlgebra >::m_spInnerLayouts.
vec_use_std_communication()
template<typename TAlgebra > void ug::FetiLayouts< TAlgebra >::vec_use_std_communication (vector_type & vec) inline
References ug::FetiLayouts< TAlgebra >::m_spStdLayouts.
Member Data Documentation
m_masterDualLayout
template<typename TAlgebra > IndexLayout ug::FetiLayouts< TAlgebra >::m_masterDualLayout protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), ug::FetiLayouts< TAlgebra >::get_dual_master_layout(), and ug::FetiLayouts< TAlgebra >::test_layouts().
m_masterDualNbrLayout
template<typename TAlgebra > IndexLayout ug::FetiLayouts< TAlgebra >::m_masterDualNbrLayout protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), ug::FetiLayouts< TAlgebra >::get_dual_nbr_master_layout(), and ug::FetiLayouts< TAlgebra >::test_layouts().
m_masterPrimalLayout
template<typename TAlgebra > IndexLayout ug::FetiLayouts< TAlgebra >::m_masterPrimalLayout protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), ug::FetiLayouts< TAlgebra >::get_primal_master_layout(), and ug::FetiLayouts< TAlgebra >::test_layouts().
m_slaveDualLayout
template<typename TAlgebra > IndexLayout ug::FetiLayouts< TAlgebra >::m_slaveDualLayout protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), ug::FetiLayouts< TAlgebra >::get_dual_slave_layout(), and ug::FetiLayouts< TAlgebra >::test_layouts().
m_slaveDualNbrLayout
template<typename TAlgebra > IndexLayout ug::FetiLayouts< TAlgebra >::m_slaveDualNbrLayout protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), ug::FetiLayouts< TAlgebra >::get_dual_nbr_slave_layout(), and ug::FetiLayouts< TAlgebra >::test_layouts().
m_slavePrimalLayout
template<typename TAlgebra > IndexLayout ug::FetiLayouts< TAlgebra >::m_slavePrimalLayout protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), ug::FetiLayouts< TAlgebra >::get_primal_slave_layout(), and ug::FetiLayouts< TAlgebra >::test_layouts().
m_spInnerLayouts
template<typename TAlgebra > SmartPtr<AlgebraLayouts> ug::FetiLayouts< TAlgebra >::m_spInnerLayouts protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), ug::FetiLayouts< TAlgebra >::get_intra_sd_master_layout(), ug::FetiLayouts< TAlgebra >::get_intra_sd_process_communicator(), ug::FetiLayouts< TAlgebra >::get_intra_sd_slave_layout(), ug::FetiLayouts< TAlgebra >::mat_use_intra_sd_communication(), ug::FetiLayouts< TAlgebra >::test_layouts(), and ug::FetiLayouts< TAlgebra >::vec_use_intra_sd_communication().
m_spStdLayouts
template<typename TAlgebra > ConstSmartPtr<AlgebraLayouts> ug::FetiLayouts< TAlgebra >::m_spStdLayouts protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), ug::FetiLayouts< TAlgebra >::get_std_master_layout(), ug::FetiLayouts< TAlgebra >::get_std_process_communicator(), ug::FetiLayouts< TAlgebra >::get_std_slave_layout(), ug::FetiLayouts< TAlgebra >::test_layouts(), ug::FetiLayouts< TAlgebra >::vec_prod_on_identified_dual(), and ug::FetiLayouts< TAlgebra >::vec_use_std_communication().
m_vUniqueDualIndex
template<typename TAlgebra > std::vector<IndexLayout::Element> ug::FetiLayouts< TAlgebra >::m_vUniqueDualIndex protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), ug::FetiLayouts< TAlgebra >::get_dual_indices(), ug::FetiLayouts< TAlgebra >::mat_set_dirichlet_on_dual(), ug::FetiLayouts< TAlgebra >::vec_scale_add_on_dual(), ug::FetiLayouts< TAlgebra >::vec_scale_append_on_dual(), ug::FetiLayouts< TAlgebra >::vec_scale_assign_on_dual(), and ug::FetiLayouts< TAlgebra >::vec_set_on_dual().
m_vUniqueMasterDualIndex
template<typename TAlgebra > std::vector<IndexLayout::Element> ug::FetiLayouts< TAlgebra >::m_vUniqueMasterDualIndex protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), ug::FetiLayouts< TAlgebra >::get_dual_master_indices(), and ug::FetiLayouts< TAlgebra >::vec_prod_on_identified_dual().
m_vUniqueMasterDualNbrIndex
template<typename TAlgebra > std::vector<IndexLayout::Element> ug::FetiLayouts< TAlgebra >::m_vUniqueMasterDualNbrIndex protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), and ug::FetiLayouts< TAlgebra >::get_dual_nbr_master_indices().
m_vUniquePrimalIndex
template<typename TAlgebra > std::vector<IndexLayout::Element> ug::FetiLayouts< TAlgebra >::m_vUniquePrimalIndex protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), ug::FetiLayouts< TAlgebra >::get_primal_indices(), ug::FetiLayouts< TAlgebra >::mat_set_dirichlet_on_primal(), ug::FetiLayouts< TAlgebra >::vec_scale_add_on_primal(), ug::FetiLayouts< TAlgebra >::vec_scale_append_on_primal(), ug::FetiLayouts< TAlgebra >::vec_scale_assign_on_primal(), and ug::FetiLayouts< TAlgebra >::vec_set_on_primal().
m_vUniquePrimalMasterIndex
template<typename TAlgebra > std::vector<IndexLayout::Element> ug::FetiLayouts< TAlgebra >::m_vUniquePrimalMasterIndex protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), and ug::FetiLayouts< TAlgebra >::get_primal_master_indices().
m_vUniquePrimalSlaveIndex
template<typename TAlgebra > std::vector<IndexLayout::Element> ug::FetiLayouts< TAlgebra >::m_vUniquePrimalSlaveIndex protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), and ug::FetiLayouts< TAlgebra >::get_primal_slave_indices().
m_vUniqueSlaveDualIndex
template<typename TAlgebra > std::vector<IndexLayout::Element> ug::FetiLayouts< TAlgebra >::m_vUniqueSlaveDualIndex protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), and ug::FetiLayouts< TAlgebra >::get_dual_slave_indices().
m_vUniqueSlaveDualNbrIndex
template<typename TAlgebra > std::vector<IndexLayout::Element> ug::FetiLayouts< TAlgebra >::m_vUniqueSlaveDualNbrIndex protected
Referenced by ug::FetiLayouts< TAlgebra >::create_layouts(), and ug::FetiLayouts< TAlgebra >::get_dual_nbr_slave_indices().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/linear_solver/feti.h