ug4: ug::AssembledMultiGridCycle< TDomain, TAlgebra > Class Template Reference
ug::AssembledMultiGridCycle< TDomain, TAlgebra > Class Template Reference
geometric multi grid preconditioner
#include <mg_solver.h>
Classes
struct LevData
struct LevelIndex
struct SurfLevelMap
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef TDomain domain_type
Domain.
typedef GridFunction< TDomain, TAlgebra > GF
Grid Function type.
typedef algebra_type::matrix_type matrix_type
Matrix type.
typedef MGStats< TDomain, TAlgebra > mg_stats_type
MGStats type.
typedef algebra_type::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Member Functions
void add_prolongation_post_process (SmartPtr< ITransferPostProcess< TDomain, TAlgebra > > PP)
add prolongation post process
void add_restriction_post_process (SmartPtr< ITransferPostProcess< TDomain, TAlgebra > > PP)
add restriction post process
AssembledMultiGridCycle ()
constructor without arguments
AssembledMultiGridCycle (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
constructor setting approximation space
void clear_transfer_post_process ()
clears all transfer post process
virtual std::string config_string () const
returns information about configuration parameters
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
Prepare for Operator J(u) and linearization point u (current solution)
virtual bool init (SmartPtr< ILinearOperator< vector_type > > L)
Prepare for Linear Operator L.
virtual const char * name () const
name
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
sets the approximation space
void set_base_level (int baseLevel)
sets the level where exact solving is performed in the mg cycle
void set_base_solver (SmartPtr< ILinearOperatorInverse< vector_type > > baseSolver)
sets the base solver that is used
void set_comm_comp_overlap (bool bOverlap)
sets if communication and computation should be overlaped
void set_cycle_type (int type)
sets the cycle type (1 = V-cycle, 2 = W-cycle, ...)
void set_cycle_type (const std::string &type)
sets the cycle type (1 = V-cycle, 2 = W-cycle, ...)
void set_debug (SmartPtr< GridFunctionDebugWriter< TDomain, TAlgebra > > spDebugWriter)
set debug output
void set_discretization (SmartPtr< IAssemble< TAlgebra > > spAss)
sets the assembling procedure that is used to compute coarse grid matrices
void set_emulate_full_refined_grid (bool bEmulate)
sets if copies should be used to emulate a full-refined grid
void set_gathered_base_solver_if_ambiguous (bool bGathered)
sets if the base solver is applied in parallel
void set_mg_stats (SmartPtr< mg_stats_type > mgstats)
sets MGStats, an object which records statistics for individual iterations
void set_num_postsmooth (int num)
sets the number of post-smoothing steps to be performed
void set_num_presmooth (int num)
sets the number of pre-smoothing steps to be performed
void set_postsmoother (SmartPtr< ILinearIterator< vector_type > > smoother)
sets the post-smoother that is used
void set_presmoother (SmartPtr< ILinearIterator< vector_type > > smoother)
sets the pre-smoother that is used
void set_projection (SmartPtr< ITransferOperator< TDomain, TAlgebra > > P)
sets the projection operator
void set_prolongation (SmartPtr< ITransferOperator< TDomain, TAlgebra > > P)
sets the prolongation operator
void set_rap (bool bRAP)
sets if RAP - Product used to build coarse grid matrices
void set_restriction (SmartPtr< ITransferOperator< TDomain, TAlgebra > > P)
sets the restriction operator
void set_smooth_on_surface_rim (bool bSmooth)
sets if smoothing is performed on surface rim
void set_smoother (SmartPtr< ILinearIterator< vector_type > > smoother)
sets the smoother that is used
void set_surface_level (int topLevel)
sets the surface level (default is top-surface)
void set_transfer (SmartPtr< ITransferOperator< TDomain, TAlgebra > > P)
sets the transfer operator
virtual bool supports_parallel () const
returns if parallel solving is supported
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
virtual bool apply (TAlgebra::vector_type &c, const TAlgebra::vector_type &d)=0
compute new correction c = B*d
virtual bool apply_update_defect (TAlgebra::vector_type &c, TAlgebra::vector_type &d)=0
compute new correction c = B*d and update defect d := d - A*c
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
void set_damp (number factor)
sets the damping to a constant factor
virtual ~ILinearIterator ()
virtual destructor
Protected Member Functions
void copy_ghost_to_noghost (SmartPtr< GF > spVecTo, ConstSmartPtr< GF > spVecFrom, const std::vector< size_t > &vMapPatchToGlobal)
copies vector to smoothing patch using cached mapping
void copy_noghost_to_ghost (SmartPtr< GF > spVecTo, ConstSmartPtr< GF > spVecFrom, const std::vector< size_t > &vMapPatchToGlobal)
copies vector from smoothing patch using cached mapping
void copy_noghost_to_ghost (SmartPtr< matrix_type > spMatTo, ConstSmartPtr< matrix_type > spMatFrom, const std::vector< size_t > &vMapPatchToGlobal)
copies matrix from smoothing patch using cached mapping
bool gathered_base_master () const
returns if gathered base master
void log_debug_data (int lvl, std::string name)
logs a level-data-struct to the terminal
void mg_stats_defect (GF &gf, int lvl, typename mg_stats_type::Stage stage)
Calls MGStats::set_defect (if available) with the given parameters.
void write_debug (ConstSmartPtr< GF > spGF, std::string name)
writes debug output for a level vector only on smooth path
void write_debug (const GF &rGF, std::string name)
template<typename TElem >
void init_noghost_to_ghost_mapping (std::vector< size_t > &vNoGhostToGhostMap, ConstSmartPtr< DoFDistribution > spNoGhostDD, ConstSmartPtr< DoFDistribution > spGhostDD)
void init_noghost_to_ghost_mapping (int lev)
void write_debug (const matrix_type &mat, std::string name, const GridLevel &glTo, const GridLevel &glFrom)
writes debug output for a level matrix only on smooth path
void write_debug (const matrix_type &mat, std::string name, const GF &rTo, const GF &rFrom)
writes debug output for a level matrix only on smooth path
Protected Attributes
bool m_bGatheredBaseIfAmbiguous
flag, if to solve base problem in parallel when gathered and (!) parallel possible
bool m_bGatheredBaseUsed
flag if using parallel base solver
pcl::InterfaceCommunicator< IndexLayout > m_Com
communicator
int m_dbgIterCnt
counter for debug, to distinguish the iterations
bool m_ignoreInitForBaseSolver
flag indicating whether the base-solver shall be initialized during a call to init()
SmartPtr< mg_stats_type > m_mgstats
MGStats are used for debugging to record statistics on individual iterations.
GF * m_pC
current surface correction
SmartPtr< GridFunctionDebugWriter< TDomain, TAlgebra > > m_spDebugWriter
Debug Writer.
std::vector< SmartPtr< LevData > > m_vLevData
storage for all level
SmartPtr< GF > spGatheredBaseCorr
vector for gathered base solver
SmartPtr< MatrixOperator< matrix_type, vector_type > > spGatheredBaseMat
Matrix for gathered base solver.
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
ConstSmartPtr< matrix_type > m_spSurfaceMat
operator to invert (surface grid)
const vector_type * m_pSurfaceSol
Solution on surface grid.
SmartPtr< IAssemble< TAlgebra > > m_spAss
assembling routine for coarse grid matrices
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
approximation space for level and surface grid
int m_topLev
int m_surfaceLev
operator to invert (surface grid)
int m_baseLev
base level (where exact inverse is computed)
int m_cycleType
cylce type (1 = V-cycle, 2 = W-cylcle, ...)
int m_numPreSmooth
number of Presmooth steps
int m_numPostSmooth
number of Postsmooth steps
int m_LocalFullRefLevel
lowest level containing surface geom obj (proc-locally)
GridLevel::ViewType m_GridLevelType
grid-view for level vectors
bool m_bUseRAP
using RAP-Product (assemble coarse-grid matrices otherwise)
bool m_bSmoothOnSurfaceRim
flag if smoothing on surface rim
bool m_bCommCompOverlap
flag if overlapping communication and computation
RevisionCounter m_ApproxSpaceRevision
approximation space revision of cached values
SmartPtr< ILinearIterator< vector_type > > m_spPreSmootherPrototype
prototype for pre-smoother
SmartPtr< ILinearIterator< vector_type > > m_spPostSmootherPrototype
prototype for post-smoother
SmartPtr< ITransferOperator< TDomain, TAlgebra > > m_spProjectionPrototype
prototype for projection operator
SmartPtr< ITransferOperator< TDomain, TAlgebra > > m_spProlongationPrototype
prototype for prolongation operator
SmartPtr< ITransferOperator< TDomain, TAlgebra > > m_spRestrictionPrototype
prototype for restriction operator
std::vector< SmartPtr< ITransferPostProcess< TDomain, TAlgebra > > > m_vspProlongationPostProcess
prototpe for transfer post process
std::vector< SmartPtr< ITransferPostProcess< TDomain, TAlgebra > > > m_vspRestrictionPostProcess
operator to invert (surface grid)
SmartPtr< ILinearOperatorInverse< vector_type > > m_spBaseSolver
base solver for the coarse problem
std::vector< LevelIndex > m_vSurfToLevelMap
operator to invert (surface grid)
static const int _V_ = 1
operator to invert (surface grid)
static const int _W_ = 2
operator to invert (surface grid)
static const int _F_ = -1
operator to invert (surface grid)
virtual void ignore_init_for_base_solver (bool ignore)
does not call init on base-solver during initialization
virtual bool ignore_init_for_base_solver () const
operator to invert (surface grid)
virtual bool apply (vector_type &c, const vector_type &d)
Compute new correction c = B*d.
virtual bool apply_update_defect (vector_type &c, vector_type &d)
Compute new correction c = B*d and return new defect d := d - A*c.
SmartPtr< ILinearIterator< vector_type > > clone ()
Clone.
~AssembledMultiGridCycle ()
Destructor.
void lmgc (int lev, int cycleType)
compute correction on level and update defect
void presmooth_and_restriction (int lev)
performs presmoothing on the given level
void prolongation_and_postsmooth (int lev)
performs prolongation to the level above
void base_solve (int lev)
compute base solver
void init_level_memory (int baseLev, int topLev)
allocates the memory
void init ()
initializes common part
void init_smoother ()
initializes the smoother and base solver
void assemble_level_operator ()
initializes the coarse grid matrices
void init_rap_operator ()
operator to invert (surface grid)
void init_base_solver ()
initializes the smoother and base solver
void init_transfer ()
initializes the transfers
void init_projection ()
initializes the prolongation
void assemble_rim_cpl (const vector_type *u)
void init_rap_rim_cpl ()
operator to invert (surface grid)
template<typename TElem >
void init_index_mappings ()
operator to invert (surface grid)
void init_index_mappings ()
operator to invert (surface grid)
Detailed Description
template<typename TDomain, typename TAlgebra>
class ug::AssembledMultiGridCycle< TDomain, TAlgebra >
geometric multi grid preconditioner
This class implements one step of the geometric multi grid as a preconditioner for linear iteration schemes such as linear iteration, cg or bicgstab.
The coarse grid spaces are build up according to the Approximation Space that is set from outside. In addition an Assembling routine must be specified that is used to assemble the coarse grid matrices.
Template Parameters
TApproximationSpace Type of Approximation Space
TAlgebra Type of Algebra
Member Typedef Documentation
algebra_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra ug::AssembledMultiGridCycle< TDomain, TAlgebra >::algebra_type
Algebra type.
domain_type
template<typename TDomain , typename TAlgebra > typedef TDomain ug::AssembledMultiGridCycle< TDomain, TAlgebra >::domain_type
Domain.
GF
template<typename TDomain , typename TAlgebra > typedef GridFunction<TDomain, TAlgebra> ug::AssembledMultiGridCycle< TDomain, TAlgebra >::GF
Grid Function type.
matrix_type
template<typename TDomain , typename TAlgebra > typedef algebra_type::matrix_type ug::AssembledMultiGridCycle< TDomain, TAlgebra >::matrix_type
Matrix type.
mg_stats_type
template<typename TDomain , typename TAlgebra > typedef MGStats<TDomain, TAlgebra> ug::AssembledMultiGridCycle< TDomain, TAlgebra >::mg_stats_type
MGStats type.
vector_type
template<typename TDomain , typename TAlgebra > typedef algebra_type::vector_type ug::AssembledMultiGridCycle< TDomain, TAlgebra >::vector_type
Vector type.
Constructor & Destructor Documentation
AssembledMultiGridCycle() [1/2]
template<typename TDomain , typename TAlgebra > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::AssembledMultiGridCycle ()
constructor without arguments
AssembledMultiGridCycle() [2/2]
template<typename TDomain , typename TAlgebra > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::AssembledMultiGridCycle (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
constructor setting approximation space
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_approximation_space().
~AssembledMultiGridCycle()
template<typename TDomain , typename TAlgebra > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::~AssembledMultiGridCycle ()
Destructor.
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply().
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
Member Function Documentation
add_prolongation_post_process()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::add_prolongation_post_process (SmartPtr< ITransferPostProcess< TDomain, TAlgebra > > PP) inline
add prolongation post process
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vspProlongationPostProcess.
add_restriction_post_process()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::add_restriction_post_process (SmartPtr< ITransferPostProcess< TDomain, TAlgebra > > PP) inline
add restriction post process
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vspRestrictionPostProcess.
apply()
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply (vector_type & c, const vector_type & d) virtual
Compute new correction c = B*d.
\
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply_update_defect(), ug::ILinearIterator< TAlgebra::vector_type >::damping(), GMG_PROFILE_BEGIN, GMG_PROFILE_END, GMG_PROFILE_FUNC, kappa, ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_cycleType, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_dbgIterCnt, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_pC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spApproxSpace, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spDebugWriter, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spSurfaceMat, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::PST_CONSISTENT, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sc, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sd, UG_CATCH_THROW, UG_DLOG, UG_THROW, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply_update_defect(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::~AssembledMultiGridCycle().
apply_update_defect()
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply_update_defect (vector_type & c, vector_type & d) virtual
Compute new correction c = B*d and return new defect d := d - A*c.
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spSurfaceMat, UG_THROW, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
assemble_level_operator()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator () protected
initializes the coarse grid matrices
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::A, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_noghost_to_ghost(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::gathered_base_master(), GMG_PROFILE_BEGIN, GMG_PROFILE_END, GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_projection(), ug::GridLevel::LEVEL, ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bCommCompOverlap, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bGatheredBaseUsed, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_Com, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_GridLevelType, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_LocalFullRefLevel, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_pSurfaceSol, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spAss, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spSurfaceMat, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vSurfToLevelMap, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::Projection, ug::PST_CONSISTENT, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::spGatheredBaseMat, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::st, ug::GridLevel::SURFACE, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::t, UG_ASSERT, UG_CATCH_THROW, UG_DLOG, UG_THROW, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vMapPatchToGlobal, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::ignore_init_for_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
assemble_rim_cpl()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl (const vector_type * u) protected
assembles the missing matrix part on the coarse level, that must be added if the correction has been computed to ensure a correctly updated defect. (i.e. assembles A^c, with d^f -= A^c * c^c)
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::A, GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bSmoothOnSurfaceRim, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_LocalFullRefLevel, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spSurfaceMat, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vSurfToLevelMap, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::RimCpl_Coarse_Fine, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::RimCpl_Fine_Coarse, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sc, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sd, ug::SetRow(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::st, UG_DLOG, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vShadowing, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vSurfShadowing, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
base_solve()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve (int lev) protected
compute base solver
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::A, ug::MatrixOperator< M, X, Y >::apply_sub(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_ghost_to_noghost(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_noghost_to_ghost(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::gathered_base_master(), SmartPtr< T, FreePolicy >::get(), GMG_PROFILE_BEGIN, GMG_PROFILE_END, GMG_PROFILE_FUNC, ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::log_debug_data(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bGatheredBaseUsed, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_Com, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_LocalFullRefLevel, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spBaseSolver, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::PST_CONSISTENT, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sc, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sd, ug::SetLayoutValues(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::spGatheredBaseCorr, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::t, UG_CATCH_THROW, UG_DLOG, UG_THROW, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vMapPatchToGlobal.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
clear_transfer_post_process()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clear_transfer_post_process () inline
clears all transfer post process
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vspProlongationPostProcess, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vspRestrictionPostProcess.
clone()
template<typename TDomain , typename TAlgebra > SmartPtr< ILinearIterator< typename TAlgebra::vector_type > > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone () virtual
Clone.
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_cycleType, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_numPostSmooth, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_numPreSmooth, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spApproxSpace, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spAss, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spBaseSolver, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spDebugWriter, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPostSmootherPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPreSmootherPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spProjectionPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spProlongationPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spRestrictionPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_surfaceLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vspProlongationPostProcess, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vspRestrictionPostProcess, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::~AssembledMultiGridCycle().
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_approximation_space(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
config_string()
template<typename TDomain , typename TAlgebra > std::string ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string () const virtual
returns information about configuration parameters
Reimplemented from ug::ILinearIterator< TAlgebra::vector_type >.
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::_F_, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::_V_, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::_W_, ug::ConfigShift(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bGatheredBaseIfAmbiguous, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_cycleType, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_numPostSmooth, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_numPreSmooth, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spBaseSolver, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPostSmootherPrototype, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPreSmootherPrototype.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::mg_stats_defect(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
copy_ghost_to_noghost()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_ghost_to_noghost (SmartPtr< GF > spVecTo, ConstSmartPtr< GF > spVecFrom, const std::vector< size_t > & vMapPatchToGlobal) protected
copies vector to smoothing patch using cached mapping
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_noghost_to_ghost(), ug::GridFunction< TDomain, TAlgebra >::dd(), GMG_PROFILE_FUNC, UG_ASSERT, and UG_THROW.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_noghost_to_ghost_mapping(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth().
copy_noghost_to_ghost() [1/2]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_noghost_to_ghost (SmartPtr< GF > spVecTo, ConstSmartPtr< GF > spVecFrom, const std::vector< size_t > & vMapPatchToGlobal) protected
copies vector from smoothing patch using cached mapping
References ug::GridFunction< TDomain, TAlgebra >::dd(), GMG_PROFILE_FUNC, UG_ASSERT, and UG_THROW.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_ghost_to_noghost(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction().
copy_noghost_to_ghost() [2/2]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_noghost_to_ghost (SmartPtr< matrix_type > spMatTo, ConstSmartPtr< matrix_type > spMatFrom, const std::vector< size_t > & vMapPatchToGlobal) protected
copies matrix from smoothing patch using cached mapping
References GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), and UG_ASSERT.
gathered_base_master()
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::gathered_base_master () const protected
returns if gathered base master
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bGatheredBaseUsed, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), and UG_THROW.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator().
ignore_init_for_base_solver() [1/2]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::ignore_init_for_base_solver (bool ignore) virtual
does not call init on base-solver during initialization
Use this method with care. It can be useful e.g. during repeated adaption of a linear problem, where the base-level does not change.
Warning
Currently only works in serial environments
Note
This only affects calls to init(...) and has no effect on direct calls to init_base_solver.
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::ignore_init_for_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_ignoreInitForBaseSolver, pcl::NumProcs(), and UG_COND_THROW.
ignore_init_for_base_solver() [2/2]
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::ignore_init_for_base_solver () const virtual
operator to invert (surface grid)
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_ignoreInitForBaseSolver.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::ignore_init_for_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
init() [1/3]
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type & u) virtual
Prepare for Operator J(u) and linearization point u (current solution)
References GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_pSurfaceSol, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spAss, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spSurfaceMat, UG_DLOG, and SmartPtr< T, FreePolicy >::valid().
init() [2/3]
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init (SmartPtr< ILinearOperator< vector_type > > L) virtual
Prepare for Linear Operator L.
References GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_pSurfaceSol, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spAss, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spSurfaceMat, UG_DLOG, and SmartPtr< T, FreePolicy >::valid().
init() [3/3]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init () protected
initializes common part
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::GridFunction< TDomain, TAlgebra >::dof_distribution(), GMG_PROFILE_BEGIN, GMG_PROFILE_END, GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::ignore_init_for_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_smoother(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_transfer(), ConstSmartPtr< T, FreePolicy >::invalid(), ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_ApproxSpaceRevision, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bUseRAP, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_pSurfaceSol, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spApproxSpace, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spAss, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spBaseSolver, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPostSmootherPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPreSmootherPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spProlongationPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spRestrictionPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spSurfaceMat, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_surfaceLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::GridLevel::TOP, UG_CATCH_THROW, UG_DLOG, and UG_THROW.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply_update_defect(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
init_base_solver()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver () protected
initializes the smoother and base solver
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::A, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::gathered_base_master(), GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings(), ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bGatheredBaseUsed, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_pSurfaceSol, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spBaseSolver, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, pcl::PCD_LOCAL, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::spGatheredBaseCorr, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::spGatheredBaseMat, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::st, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::t, UG_DLOG, and UG_THROW.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_smoother(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
init_index_mappings() [1/2]
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings () protected
operator to invert (surface grid)
References ug::SurfaceView::ALL, ug::PeriodicBoundaryManager::is_slave(), ug::GridLevel::LEVEL, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_GridLevelType, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_LocalFullRefLevel, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spApproxSpace, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_surfaceLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vSurfToLevelMap, ug::SurfaceView::MG_SHADOW_RIM_COPY, ug::SurfaceView::MG_SURFACE_RIM, ug::GridLevel::SURFACE, UG_ASSERT, and UG_THROW.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver().
init_index_mappings() [2/2]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings () protected
operator to invert (surface grid)
References ug::EDGE, ug::FACE, GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_noghost_to_ghost_mapping(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_LocalFullRefLevel, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spApproxSpace, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_surfaceLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vSurfToLevelMap, ug::GridLevel::SURFACE, UG_THROW, ug::VERTEX, and ug::VOLUME.
init_level_memory()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory (int baseLev, int topLev) protected
allocates the memory
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::gathered_base_master(), SmartPtr< T, FreePolicy >::get(), GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_noghost_to_ghost_mapping(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bGatheredBaseIfAmbiguous, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bGatheredBaseUsed, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_GridLevelType, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spApproxSpace, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spBaseSolver, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPostSmootherPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPreSmootherPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spProjectionPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spProlongationPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spRestrictionPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::ILevelPreconditioner< TAlgebra >::set_grid_level(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::spGatheredBaseCorr, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::spGatheredBaseMat, SPNULL, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::t, and UG_THROW.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_noghost_to_ghost(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
init_noghost_to_ghost_mapping() [1/2]
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_noghost_to_ghost_mapping (std::vector< size_t > & vNoGhostToGhostMap, ConstSmartPtr< DoFDistribution > spNoGhostDD, ConstSmartPtr< DoFDistribution > spGhostDD) protected
init mapping from noghost -> w/ ghost
References UG_ASSERT.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory().
init_noghost_to_ghost_mapping() [2/2]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_noghost_to_ghost_mapping (int lev) protected
init mapping from noghost -> w/ ghost
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_ghost_to_noghost(), ug::EDGE, ug::FACE, GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::st, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::t, ug::VERTEX, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vMapPatchToGlobal, and ug::VOLUME.
init_projection()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_projection () protected
initializes the prolongation
References GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_smoother(), ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::Projection, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::st, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::t, and UG_DLOG.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_transfer(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
init_rap_operator()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator () protected
operator to invert (surface grid)
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::A, ug::AddMultiplyOf(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_noghost_to_ghost(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::gathered_base_master(), GMG_PROFILE_BEGIN, GMG_PROFILE_END, GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl(), ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bCommCompOverlap, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bGatheredBaseUsed, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_Com, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spApproxSpace, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spSurfaceMat, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vSurfToLevelMap, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::Prolongation, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::Restriction, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::spGatheredBaseMat, SPNULL, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::st, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::t, UG_ASSERT, UG_CATCH_THROW, UG_DLOG, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vMapPatchToGlobal, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
init_rap_rim_cpl()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl () protected
operator to invert (surface grid)
References GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_transfer(), ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bSmoothOnSurfaceRim, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_LocalFullRefLevel, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spSurfaceMat, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vSurfToLevelMap, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::RimCpl_Coarse_Fine, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::RimCpl_Fine_Coarse, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sc, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sd, UG_DLOG, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vShadowing, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vSurfShadowing, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
init_smoother()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_smoother () protected
initializes the smoother and base solver
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::A, GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver(), ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::PostSmoother, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::PreSmoother, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sc, UG_CATCH_THROW, UG_DLOG, and UG_THROW.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_projection(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
init_transfer()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_transfer () protected
initializes the transfers
References GMG_PROFILE_FUNC, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_projection(), ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spAss, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::Prolongation, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::Restriction, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::st, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::t, and UG_DLOG.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
lmgc()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc (int lev, int cycleType) protected
compute correction on level and update defect
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::_F_, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::_V_, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), GMG_PROFILE_FUNC, ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth(), UG_CATCH_THROW, UG_DLOG, UG_THROW, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
log_debug_data()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::log_debug_data (int lvl, std::string name) protected
logs a level-data-struct to the terminal
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spDebugWriter, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::mg_stats_defect(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sc, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sd, ug::ToString(), UG_LOG, ug::VecProd(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_debug(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
mg_stats_defect()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::mg_stats_defect (GF & gf, int lvl, typename mg_stats_type::Stage stage) protected
Calls MGStats::set_defect (if available) with the given parameters.
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_mgstats.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::log_debug_data(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_debug().
name()
template<typename TDomain , typename TAlgebra > virtual const char* ug::AssembledMultiGridCycle< TDomain, TAlgebra >::name () const inline virtual
name
Implements ug::ILinearIterator< TAlgebra::vector_type >.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_debug().
presmooth_and_restriction()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction (int lev) protected
performs presmoothing on the given level
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::A, ug::MGStats< TDomain, TAlgebra >::AFTER_PRE_SMOOTH, ug::MatrixOperator< M, X, Y >::apply_sub(), ug::MGStats< TDomain, TAlgebra >::BEFORE_PRE_SMOOTH, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_noghost_to_ghost(), GMG_PROFILE_BEGIN, GMG_PROFILE_END, GMG_PROFILE_FUNC, ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::log_debug_data(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bCommCompOverlap, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bSmoothOnSurfaceRim, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_Com, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_LocalFullRefLevel, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_numPreSmooth, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vspRestrictionPostProcess, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::mg_stats_defect(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::PreSmoother, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth(), ug::PST_ADDITIVE, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::Restriction, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::RimCpl_Coarse_Fine, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sc, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sd, ug::SetLayoutValues(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::st, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::t, UG_CATCH_THROW, UG_DLOG, UG_THROW, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vMapPatchToGlobal, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vShadowing.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::gathered_base_master(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
prolongation_and_postsmooth()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth (int lev) protected
performs prolongation to the level above
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::A, ug::MGStats< TDomain, TAlgebra >::AFTER_POST_SMOOTH, ug::MatrixOperator< M, X, Y >::apply_sub(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::MGStats< TDomain, TAlgebra >::BEFORE_POST_SMOOTH, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::copy_ghost_to_noghost(), GMG_PROFILE_BEGIN, GMG_PROFILE_END, GMG_PROFILE_FUNC, ug::LIB_DISC_MULTIGRID, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::log_debug_data(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bSmoothOnSurfaceRim, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_Com, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_LocalFullRefLevel, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_mgstats, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_numPostSmooth, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spDebugWriter, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vspProlongationPostProcess, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::mg_stats_defect(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::PostSmoother, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::Prolongation, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::RimCpl_Coarse_Fine, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::RimCpl_Fine_Coarse, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sc, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::sd, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::st, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::t, UG_CATCH_THROW, UG_DLOG, UG_THROW, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vMapPatchToGlobal, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vShadowing, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::LevData::vSurfLevelMap.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
set_approximation_space()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
sets the approximation space
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spApproxSpace, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spProjectionPrototype, and make_sp().
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::AssembledMultiGridCycle(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_mg_stats().
set_base_level()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_base_level (int baseLevel) inline
sets the level where exact solving is performed in the mg cycle
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev.
set_base_solver()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_base_solver (SmartPtr< ILinearOperatorInverse< vector_type > > baseSolver) inline
sets the base solver that is used
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spBaseSolver.
set_comm_comp_overlap()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_comm_comp_overlap (bool bOverlap) inline
sets if communication and computation should be overlaped
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bCommCompOverlap.
set_cycle_type() [1/2]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_cycle_type (int type) inline
sets the cycle type (1 = V-cycle, 2 = W-cycle, ...)
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_cycleType.
set_cycle_type() [2/2]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_cycle_type (const std::string & type) inline
sets the cycle type (1 = V-cycle, 2 = W-cycle, ...)
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::_F_, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::_V_, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::_W_, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_cycleType, ug::TrimString(), and UG_THROW.
set_debug()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_debug (SmartPtr< GridFunctionDebugWriter< TDomain, TAlgebra > > spDebugWriter) inline
set debug output
If a DebugWriter is passed by this method, the multi grid cycle writes the level/surface vectors and matrices for debug purposes.
Parameters
[in] debugWriter Debug Writer to use
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::log_debug_data(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spDebugWriter, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::mg_stats_defect(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::name(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
set_discretization()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_discretization (SmartPtr< IAssemble< TAlgebra > > spAss) inline
sets the assembling procedure that is used to compute coarse grid matrices
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spAss.
set_emulate_full_refined_grid()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_emulate_full_refined_grid (bool bEmulate) inline
sets if copies should be used to emulate a full-refined grid
References ug::GridLevel::LEVEL, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_GridLevelType, and ug::GridLevel::SURFACE.
set_gathered_base_solver_if_ambiguous()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_gathered_base_solver_if_ambiguous (bool bGathered) inline
sets if the base solver is applied in parallel
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bGatheredBaseIfAmbiguous.
set_mg_stats()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_mg_stats (SmartPtr< mg_stats_type > mgstats) inline
sets MGStats, an object which records statistics for individual iterations
Setting MGStats is optional. If set, a runtime overhead is incurred. Only useful for debugging.
See also
MGStats
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_mgstats, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_approximation_space().
set_num_postsmooth()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_num_postsmooth (int num) inline
sets the number of post-smoothing steps to be performed
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_numPostSmooth.
set_num_presmooth()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_num_presmooth (int num) inline
sets the number of pre-smoothing steps to be performed
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_numPreSmooth.
set_postsmoother()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_postsmoother (SmartPtr< ILinearIterator< vector_type > > smoother) inline
sets the post-smoother that is used
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPostSmootherPrototype.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_smoother().
set_presmoother()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_presmoother (SmartPtr< ILinearIterator< vector_type > > smoother) inline
sets the pre-smoother that is used
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPreSmootherPrototype.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_smoother().
set_projection()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_projection (SmartPtr< ITransferOperator< TDomain, TAlgebra > > P) inline
sets the projection operator
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spProjectionPrototype.
set_prolongation()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_prolongation (SmartPtr< ITransferOperator< TDomain, TAlgebra > > P) inline
sets the prolongation operator
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spProlongationPrototype.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_transfer().
set_rap()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_rap (bool bRAP) inline
sets if RAP - Product used to build coarse grid matrices
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bUseRAP.
set_restriction()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_restriction (SmartPtr< ITransferOperator< TDomain, TAlgebra > > P) inline
sets the restriction operator
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spRestrictionPrototype.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_transfer().
set_smooth_on_surface_rim()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_smooth_on_surface_rim (bool bSmooth) inline
sets if smoothing is performed on surface rim
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bSmoothOnSurfaceRim.
set_smoother()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_smoother (SmartPtr< ILinearIterator< vector_type > > smoother) inline
sets the smoother that is used
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_postsmoother(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_presmoother().
set_surface_level()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_surface_level (int topLevel) inline
sets the surface level (default is top-surface)
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_surfaceLev.
set_transfer()
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_transfer (SmartPtr< ITransferOperator< TDomain, TAlgebra > > P) inline
sets the transfer operator
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_prolongation(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_restriction().
supports_parallel()
template<typename TDomain , typename TAlgebra > virtual bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply_update_defect(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::ignore_init_for_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_projection(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_smoother(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_transfer(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPostSmootherPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPreSmootherPrototype, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::~AssembledMultiGridCycle().
write_debug() [1/4]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug (ConstSmartPtr< GF > spGF, std::string name) protected
writes debug output for a level vector only on smooth path
This method writes the level vector to a debug file, if a debug writer has been set.
Parameters
[in] spGF Level Vector to write for debug purpose
[in] name Filename
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply_update_defect(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::log_debug_data(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_debug(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
write_debug() [2/4]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug (const GF & rGF, std::string name) protected
References ug::GridFunction< TDomain, TAlgebra >::grid_level(), ug::GridLevelAppendix(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_dbgIterCnt, ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spDebugWriter, PROFILE_FUNC_GROUP, and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
write_debug() [3/4]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug (const matrix_type & mat, std::string name, const GridLevel & glTo, const GridLevel & glFrom) protected
writes debug output for a level matrix only on smooth path
This method writes the level matrix to a debug file, if a debug writer has been set.
Parameters
[in] mat Level Matrix to write for debug purpose
[in] name Filename
References ug::GridLevelAppendix(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::log_debug_data(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spDebugWriter, and PROFILE_FUNC_GROUP.
write_debug() [4/4]
template<typename TDomain , typename TAlgebra > void ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug (const matrix_type & mat, std::string name, const GF & rTo, const GF & rFrom) protected
writes debug output for a level matrix only on smooth path
This method writes the level matrix to a debug file, if a debug writer has been set.
Parameters
[in] mat Level Matrix to write for debug purpose
[in] name Filename
References ug::GridFunction< TDomain, TAlgebra >::grid_level(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
Member Data Documentation
_F_
template<typename TDomain , typename TAlgebra > const int ug::AssembledMultiGridCycle< TDomain, TAlgebra >::_F_ = -1 static protected
operator to invert (surface grid)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_cycle_type().
_V_
template<typename TDomain , typename TAlgebra > const int ug::AssembledMultiGridCycle< TDomain, TAlgebra >::_V_ = 1 static protected
operator to invert (surface grid)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_cycle_type().
_W_
template<typename TDomain , typename TAlgebra > const int ug::AssembledMultiGridCycle< TDomain, TAlgebra >::_W_ = 2 static protected
operator to invert (surface grid)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_cycle_type().
m_ApproxSpaceRevision
template<typename TDomain , typename TAlgebra > RevisionCounter ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_ApproxSpaceRevision protected
approximation space revision of cached values
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init().
m_baseLev
template<typename TDomain , typename TAlgebra > int ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_baseLev protected
base level (where exact inverse is computed)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::gathered_base_master(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_projection(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_smoother(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_transfer(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_base_level().
m_bCommCompOverlap
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bCommCompOverlap protected
flag if overlapping communication and computation
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_comm_comp_overlap().
m_bGatheredBaseIfAmbiguous
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bGatheredBaseIfAmbiguous protected
flag, if to solve base problem in parallel when gathered and (!) parallel possible
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_gathered_base_solver_if_ambiguous().
m_bGatheredBaseUsed
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bGatheredBaseUsed protected
flag if using parallel base solver
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::gathered_base_master(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator().
m_bSmoothOnSurfaceRim
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bSmoothOnSurfaceRim protected
flag if smoothing on surface rim
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_smooth_on_surface_rim().
m_bUseRAP
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_bUseRAP protected
using RAP-Product (assemble coarse-grid matrices otherwise)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_rap().
m_Com
template<typename TDomain , typename TAlgebra > pcl::InterfaceCommunicator<IndexLayout> ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_Com protected
communicator
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth().
m_cycleType
template<typename TDomain , typename TAlgebra > int ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_cycleType protected
cylce type (1 = V-cycle, 2 = W-cylcle, ...)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_cycle_type().
m_dbgIterCnt
template<typename TDomain , typename TAlgebra > int ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_dbgIterCnt protected
counter for debug, to distinguish the iterations
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
m_GridLevelType
template<typename TDomain , typename TAlgebra > GridLevel::ViewType ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_GridLevelType protected
grid-view for level vectors
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_emulate_full_refined_grid().
m_ignoreInitForBaseSolver
template<typename TDomain , typename TAlgebra > bool ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_ignoreInitForBaseSolver protected
flag indicating whether the base-solver shall be initialized during a call to init()
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::ignore_init_for_base_solver().
m_LocalFullRefLevel
template<typename TDomain , typename TAlgebra > int ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_LocalFullRefLevel protected
lowest level containing surface geom obj (proc-locally)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth().
m_mgstats
template<typename TDomain , typename TAlgebra > SmartPtr<mg_stats_type> ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_mgstats protected
MGStats are used for debugging to record statistics on individual iterations.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::mg_stats_defect(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_mg_stats().
m_numPostSmooth
template<typename TDomain , typename TAlgebra > int ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_numPostSmooth protected
number of Postsmooth steps
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_num_postsmooth().
m_numPreSmooth
template<typename TDomain , typename TAlgebra > int ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_numPreSmooth protected
number of Presmooth steps
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_num_presmooth().
m_pC
template<typename TDomain , typename TAlgebra > GF* ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_pC protected
current surface correction
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply().
m_pSurfaceSol
template<typename TDomain , typename TAlgebra > const vector_type* ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_pSurfaceSol protected
Solution on surface grid.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver().
m_spApproxSpace
template<typename TDomain , typename TAlgebra > SmartPtr<ApproximationSpace<TDomain> > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spApproxSpace protected
approximation space for level and surface grid
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_approximation_space().
m_spAss
template<typename TDomain , typename TAlgebra > SmartPtr<IAssemble<TAlgebra> > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spAss protected
assembling routine for coarse grid matrices
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_transfer(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_discretization().
m_spBaseSolver
template<typename TDomain , typename TAlgebra > SmartPtr<ILinearOperatorInverse<vector_type> > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spBaseSolver protected
base solver for the coarse problem
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_base_solver().
m_spDebugWriter
template<typename TDomain , typename TAlgebra > SmartPtr<GridFunctionDebugWriter<TDomain, TAlgebra> > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spDebugWriter protected
Debug Writer.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::log_debug_data(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_debug(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::write_debug().
m_spPostSmootherPrototype
template<typename TDomain , typename TAlgebra > SmartPtr<ILinearIterator<vector_type> > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPostSmootherPrototype protected
prototype for post-smoother
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_postsmoother(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
m_spPreSmootherPrototype
template<typename TDomain , typename TAlgebra > SmartPtr<ILinearIterator<vector_type> > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spPreSmootherPrototype protected
prototype for pre-smoother
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::config_string(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_presmoother(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::supports_parallel().
m_spProjectionPrototype
template<typename TDomain , typename TAlgebra > SmartPtr<ITransferOperator<TDomain, TAlgebra> > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spProjectionPrototype protected
prototype for projection operator
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_approximation_space(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_projection().
m_spProlongationPrototype
template<typename TDomain , typename TAlgebra > SmartPtr<ITransferOperator<TDomain, TAlgebra> > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spProlongationPrototype protected
prototype for prolongation operator
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_prolongation().
m_spRestrictionPrototype
template<typename TDomain , typename TAlgebra > SmartPtr<ITransferOperator<TDomain, TAlgebra> > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spRestrictionPrototype protected
prototype for restriction operator
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_restriction().
m_spSurfaceMat
template<typename TDomain , typename TAlgebra > ConstSmartPtr<matrix_type> ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_spSurfaceMat protected
operator to invert (surface grid)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply_update_defect(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl().
m_surfaceLev
template<typename TDomain , typename TAlgebra > int ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_surfaceLev protected
operator to invert (surface grid)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::set_surface_level().
m_topLev
template<typename TDomain , typename TAlgebra > int ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_topLev protected
top level (i.e. highest level in hierarchy. This is the surface level in case of non-adaptive refinement)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_projection(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_smoother(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_transfer(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::lmgc().
m_vLevData
template<typename TDomain , typename TAlgebra > std::vector<SmartPtr<LevData> > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vLevData protected
storage for all level
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::apply(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::gathered_base_master(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_noghost_to_ghost_mapping(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_projection(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_smoother(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_transfer(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::log_debug_data(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth().
m_vspProlongationPostProcess
template<typename TDomain , typename TAlgebra > std::vector<SmartPtr<ITransferPostProcess<TDomain, TAlgebra> > > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vspProlongationPostProcess protected
prototpe for transfer post process
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::add_prolongation_post_process(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clear_transfer_post_process(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::prolongation_and_postsmooth().
m_vspRestrictionPostProcess
template<typename TDomain , typename TAlgebra > std::vector<SmartPtr<ITransferPostProcess<TDomain, TAlgebra> > > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vspRestrictionPostProcess protected
operator to invert (surface grid)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::add_restriction_post_process(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clear_transfer_post_process(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::clone(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::presmooth_and_restriction().
m_vSurfToLevelMap
template<typename TDomain , typename TAlgebra > std::vector<LevelIndex> ug::AssembledMultiGridCycle< TDomain, TAlgebra >::m_vSurfToLevelMap protected
operator to invert (surface grid)
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_rim_cpl(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_index_mappings(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_rim_cpl().
spGatheredBaseCorr
template<typename TDomain , typename TAlgebra > SmartPtr<GF> ug::AssembledMultiGridCycle< TDomain, TAlgebra >::spGatheredBaseCorr protected
vector for gathered base solver
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::base_solve(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory().
spGatheredBaseMat
template<typename TDomain , typename TAlgebra > SmartPtr<MatrixOperator<matrix_type, vector_type> > ug::AssembledMultiGridCycle< TDomain, TAlgebra >::spGatheredBaseMat protected
Matrix for gathered base solver.
Referenced by ug::AssembledMultiGridCycle< TDomain, TAlgebra >::assemble_level_operator(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_base_solver(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_level_memory(), and ug::AssembledMultiGridCycle< TDomain, TAlgebra >::init_rap_operator().
The documentation for this class was generated from the following files:
ugbase/lib_disc/operator/linear_operator/multi_grid_solver/mg_solver.h
ugbase/lib_disc/operator/linear_operator/multi_grid_solver/mg_solver_impl.hpp