ug4: ug::VolumeVertices Class Reference
ug::VolumeVertices Class Reference
holds the vertices of a Volume or a VolumeDescriptor
#include <grid_base_objects.h>
Public Member Functions
virtual size_t num_vertices () const
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual Vertex * vertex (size_t index) const
virtual ConstVertexArray vertices () const
virtual ~VolumeVertices ()
Public Member Functions inherited from ug::IVertexGroup
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~IVertexGroup ()
Additional Inherited Members
Public Types inherited from ug::IVertexGroup
typedef Vertex *const * ConstVertexArray
Detailed Description
holds the vertices of a Volume or a VolumeDescriptor
Constructor & Destructor Documentation
~VolumeVertices()
virtual ug::VolumeVertices::~VolumeVertices () inline virtual
Member Function Documentation
num_vertices()
virtual size_t ug::VolumeVertices::num_vertices () const inline virtual
Implements ug::IVertexGroup.
Reimplemented in ug::Octahedron, ug::Pyramid, ug::Prism, ug::Hexahedron, ug::Tetrahedron, and ug::VolumeDescriptor.
References UG_ASSERT.
Referenced by ug::AspectRatio(), ug::Grid::assign_grid(), ug::CalculateCenter(), ug::CalculateConstrainedSmoothVolumePosInTopLevel(), ug::CalculateNumElemsVertexAttachmentInTopLevel(), ug::CalculateSmoothVolumePosInTopLevel(), ug::grid_unit_tests::CheckAssociatedEdgesOfVolumes(), ug::CollapseEdge(), ug::CollectAssociatedSides(), ug::CollectNeighbors(), ug::CollectVertices(), ug::CompareVertices(), ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_3d(), ug::CreateEdgeSplitGeometry(), ug::Duplicate(), ug::EraseConnectingElements(), ug::ExpandFractures3d(), ug::Grid::flip_orientation(), ug::Grid::get_associated(), ug::Grid::get_associated_sorted(), ug::GetNeighbours(), ug::GetVertexIndex(), ug::HashKey(), ug::HexahedronDescriptor::HexahedronDescriptor(), ug::MergeGrids(), ug::MergeVertices(), ug::NumVertices(), ug::OctahedronDescriptor::OctahedronDescriptor(), ug::VolumeDescriptor::operator=(), ug::GlobalFracturedMediaRefiner::perform_refinement(), ug::GlobalMultiGridRefiner::perform_refinement(), ug::PrismDescriptor::PrismDescriptor(), ug::ProlongateP1(), ug::PyramidDescriptor::PyramidDescriptor(), ug::MGHNodeAdjuster::ref_marks_changed(), ug::Refine(), ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex(), ug::SmoothProjector::refinement_ends(), ug::Grid::register_and_replace_element(), ug::Grid::register_volume(), ug::Grid::replace_vertex(), ug::SelectInnerSelectionVertices(), ug::TetrahedronDescriptor::TetrahedronDescriptor(), ug::Grid::unregister_volume(), ug::Grid::vertex_store_associated_volumes(), ug::VolumeContains(), and ug::WriteNG().
operator[]()
Vertex* ug::VolumeVertices::operator[] (size_t index) const inline
returns the i-th vertex.
size()
size_t ug::VolumeVertices::size () const inline
returns the number of vertices.
References boost::num_vertices().
vertex()
virtual Vertex* ug::VolumeVertices::vertex (size_t index) const inline virtual
Implements ug::IVertexGroup.
Reimplemented in ug::Octahedron, ug::Pyramid, ug::Prism, ug::Hexahedron, ug::Tetrahedron, and ug::VolumeDescriptor.
References UG_ASSERT.
Referenced by ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::CalculateConstrainedSmoothVolumePosInTopLevel(), ug::CalculateNumElemsVertexAttachmentInTopLevel(), ug::CalculateSmoothVolumePosInTopLevel(), ug::CollectAssociatedSides(), ug::CreateEdgeSplitGeometry(), ug::Duplicate(), ug::EraseConnectingElements(), ug::ExpandFractures3d(), ug::Grid::get_opposing_object(), ug::Grid::get_volume(), ug::GetNeighbours(), ug::GetVertex(), ug::GetVertexIndex(), ug::HexahedronDescriptor::HexahedronDescriptor(), ug::MergeGrids(), ug::MergeVertices(), ug::OctahedronDescriptor::OctahedronDescriptor(), ug::VolumeDescriptor::operator=(), ug::GlobalFracturedMediaRefiner::perform_refinement(), ug::GlobalMultiGridRefiner::perform_refinement(), ug::PrismDescriptor::PrismDescriptor(), ug::ProlongateP1(), ug::PyramidDescriptor::PyramidDescriptor(), ug::MGHNodeAdjuster::ref_marks_changed(), ug::Refine(), ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex(), ug::SmoothProjector::refinement_ends(), ug::SelectInnerSelectionVertices(), ug::DoFDistribution::sort_constrained_edges(), ug::DoFDistribution::sort_constrained_faces(), ug::TetrahedronDescriptor::TetrahedronDescriptor(), and ug::WriteNG().
vertices()
virtual ConstVertexArray ug::VolumeVertices::vertices () const inline virtual
Implements ug::IVertexGroup.
Reimplemented in ug::Octahedron, ug::Pyramid, ug::Prism, ug::Hexahedron, ug::Tetrahedron, and ug::VolumeDescriptor.
References UG_ASSERT.
Referenced by ug::Grid::assign_grid(), ug::CalculateCenter(), ug::grid_unit_tests::CheckAssociatedEdgesOfVolumes(), ug::CollectNeighbors(), ug::CollectVertices(), ug::CompareVertices(), ug::ConvertToTetrahedra(), ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_3d(), ug::Grid::get_associated(), ug::Grid::get_associated_sorted(), ug::HashKey(), ug::Refine(), ug::Grid::register_and_replace_element(), ug::Grid::register_volume(), ug::Grid::replace_vertex(), ug::Grid::unregister_volume(), ug::Grid::vertex_store_associated_volumes(), and ug::VolumeContains().
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/grid_base_objects.h