ug4: ug::StdDataLinker< TImpl, TData, dim > Class Template Reference
ug::StdDataLinker< TImpl, TData, dim > Class Template Reference
combines several UserDatas to a new UserData of a specified type
#include <linker.h>
Public Member Functions
virtual void check_setup () const
returns if data is ok
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
compute values (and derivatives iff compDeriv == true)
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
compute values (and derivatives iff compDeriv == true, but only for the 'current' time point)
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
template<int refDim>
void evaluate (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
virtual SmartPtr< ICplUserData< dim > > needed_data (size_t i)
return needed data
virtual size_t num_input () const
number of inputs
virtual size_t num_needed_data () const
number of other Data this data depends on
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const
returns value for a global position
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
returns value for global positions
virtual bool requires_grid_fct () const
returns that a grid function is needed for evaluation
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
updates the function group
virtual void set_input (size_t i, SmartPtr< ICplUserData< dim > > input, SmartPtr< UserDataInfo > info)
sets an input
void set_num_input (size_t num)
sets the number of inputs
virtual bool zero_derivative () const
returns if derivative is zero
bool zero_derivative (size_t i) const
returns if the derivative of the i'th input is zero
Public Member Functions inherited from ug::StdUserData< StdDataLinker< TImpl, TData, dim >, TData, dim, void, DependentUserData< TData, dim > >
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
Public Member Functions inherited from ug::DependentUserData< TData, dim >
DependentUserData ()
default constructor
const TData & deriv (size_t s, size_t ip, size_t fct, size_t dof) const
returns the derivative of the local function, at ip and for a dof
TData & deriv (size_t s, size_t ip, size_t fct, size_t dof)
returns the derivative of the local function, at ip and for a dof
TData * deriv (size_t s, size_t ip, size_t fct)
returns the derivatives of the local function, at ip
const TData * deriv (size_t s, size_t ip, size_t fct) const
returns the derivatives of the local function, at ip
size_t num_sh (size_t fct) const
number of shapes for local function
virtual void update_dof_sizes (const LocalIndices &ind)
resize lin defect arrays
DependentUserData (const char *symbFct)
DependentUserData (const std::string &symbFct)
DependentUserData (const std::vector< std::string > &symbFct)
void set_functions (const char *symbFct)
void set_functions (const std::string &symbFct)
void set_functions (const std::vector< std::string > &symbFct)
Public Member Functions inherited from ug::CplUserData< TData, dim >
bool defined (size_t s, size_t ip) const
returns flag, if data is evaluated (for conditional data)
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
register external callback, invoked when data storage changed
void unregister_storage_callback (DataImport< TData, dim > *obj)
register all callbacks registered by class
const TData & value (size_t s, size_t ip) const
returns the value at ip
TData & value (size_t s, size_t ip)
returns the value at ip
const TData * values (size_t s) const
returns all values for a series
TData * values (size_t s)
returns all values for a series
~CplUserData ()
destructor
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
returns true iff the time point specification is equal to the current one, or not specified
void clear ()
clear all data
virtual bool constant () const
returns if data is constant
int dim_local_ips () const
returns current local ip dimension
ICplUserData ()
default constructor
const MathVector< dim > & ip (size_t s, size_t ip) const
returns global ip
const MathVector< dim > * ips (size_t s) const
returns global ips
template<int ldim>
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
returns local ip
template<int ldim>
const MathVector< ldim > * local_ips (size_t s) const
returns local ips
size_t num_ip (size_t s) const
returns the number of integration points
size_t num_series () const
returns the number of ip series
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
set local positions, returns series id
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
set local positions without the specification of the time point, returns series id
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
set global positions
template<int ldim>
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
sets new local ip positions for a local ip series
void set_subset (int si)
set the subset of evaluation
void set_time_point (size_t timePoint)
sets the current time point
void set_time_point (const size_t seriesId, const int timePointSpec)
sets a new time point for a local ip series
void set_times (const std::vector< number > &vTime)
set evaluation time
int subset () const
returns the subset of evaluation
number time () const
get the current evaluation time
number time (size_t s) const
get the specified evaluation time
size_t time_point ()
returns the current time point
size_t time_point (size_t s) const
returns the time point specification (in particular, the current one, if the own one not specified)
int time_point_specification (size_t s) const
returns the time point specification (note: it may be -1, i.e. not specified)
virtual ~ICplUserData ()
virtual desctructor
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
Function Group of functions.
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual ~UserDataInfo ()
virtual destructor
Public Member Functions inherited from ug::UserData< TData, dim, void >
int get_dim () const
returns dimension
std::string type () const
returns type of data as string (e.g. "Number", "Vector", "Matrix")
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
Protected Member Functions
template<int refDim>
void eval_deriv (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
template<int refDim>
void eval_deriv (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
TImpl & getImpl ()
access to implementation
const TImpl & getImpl () const
const access to implementation
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
forwards the global positions to the data inputs
size_t input_common_fct (size_t i, size_t fct) const
returns the number in the common FctGrp for a fct of an input
size_t input_num_fct (size_t i) const
returns number of functions the input depends on
virtual void local_ip_series_added (const size_t seriesID)
requests series id's from input data
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
forwards the local positions to the data inputs
size_t series_id (size_t i, size_t s) const
returns the series id set for the i'th input
Protected Member Functions inherited from ug::StdUserData< StdDataLinker< TImpl, TData, dim >, TData, dim, void, DependentUserData< TData, dim > >
StdDataLinker< TImpl, TData, dim > & getImpl ()
access to implementation
const StdDataLinker< TImpl, TData, dim > & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::DependentUserData< TData, dim >
void check_s_ip (size_t s, size_t ip) const
checks in debug mode the correct usage of indices
void check_s_ip_fct (size_t s, size_t ip, size_t fct) const
checks in debug mode the correct usage of indices
void check_s_ip_fct_dof (size_t s, size_t ip, size_t fct, size_t dof) const
checks in debug mode the correct usage of indices
void extract_fct_grp ()
extracts the function group
virtual void local_ip_series_to_be_cleared ()
implement callback, invoked when local ips are cleared
void resize_deriv_array ()
resizes the derivative arrays for current number of ips.
void resize_deriv_array (const size_t seriesID)
resizes the derivative arrays for current number of ips of a single series
Protected Member Functions inherited from ug::CplUserData< TData, dim >
void call_storage_callback () const
calls are registered external storage callbacks
void check_series (size_t s) const
checks in debug mode the correct index
void check_series_ip (size_t s, size_t ip) const
checks in debug mode the correct index
virtual void value_storage_changed (const size_t seriesID)
callback, invoked when storage of data has changed for a series
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
checks in debug mode the correct usage of indices
void check_s_ip (size_t s, size_t ip) const
checks in debug mode the correct usage of indices
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
help function to get local ips
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
Protected Attributes
std::vector< FunctionIndexMapping > m_vMap
Function mapping for each input relative to common FunctionGroup.
std::vector< SmartPtr< ICplUserData< dim > > > m_vspICplUserData
data input
std::vector< SmartPtr< UserDataInfo > > m_vspUserDataInfo
data input casted to IDependend data
std::vector< std::vector< size_t > > m_vvSeriesID
series id the linker uses to get data from input
Protected Attributes inherited from ug::DependentUserData< TData, dim >
std::vector< std::string > m_SymbFct
string of symbolic functions required
std::vector< size_t > m_vvNumDoFPerFct
number of functions and their dofs
std::vector< std::vector< std::vector< std::vector< TData > > > > m_vvvvDeriv
Derivatives.
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
default time point (or -1 if not specified)
int m_locPosDim
dimension of local position (-1 indicates no dim set)
std::vector< const MathVector< 1 > * > m_pvLocIP1d
local ips of dimension 1d-3d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
subset for evaluation
size_t m_timePoint
current time point (used if no explicit specification for series)
std::vector< bool > m_vMayChange
flags if local ips may change
std::vector< size_t > m_vNumIP
number of evaluation points (-1 indicates no ips set)
std::vector< number > m_vTime
time for evaluation
std::vector< int > m_vTimePoint
time points for the series
std::vector< const MathVector< dim > * > m_vvGlobPos
global ips
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Additional Inherited Members
Public Types inherited from ug::DependentUserData< TData, dim >
typedef CplUserData< TData, dim > base_type
Base class type.
Public Types inherited from ug::CplUserData< TData, dim >
typedef ICplUserData< dim > base_type
type of base class
Static Public Member Functions inherited from ug::DependentUserData< TData, dim >
static void set_zero (std::vector< std::vector< TData > > vvvDeriv[], const size_t nip)
sets all derivative values to zero
Detailed Description
template<typename TImpl, typename TData, int dim>
class ug::StdDataLinker< TImpl, TData, dim >
combines several UserDatas to a new UserData of a specified type
This class provides data at integration points and implements the DependentUserData interface.
Template Parameters
TData output Data type
dim World dimension
Member Function Documentation
template<typename TImpl , typename TData , int dim> void ug::StdDataLinker< TImpl, TData, dim >::check_setup () const virtual
returns if data is ok
Reimplemented from ug::ICplUserData< dim >.
References ug::StdDataLinker< TImpl, TData, dim >::set_function_pattern(), and UG_THROW.
Referenced by ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::needed_data().
template<typename TImpl , typename TData , int dim> void ug::StdDataLinker< TImpl, TData, dim >::compute (LocalVector * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) virtual
compute values (and derivatives iff compDeriv == true)
Implements ug::ICplUserData< dim >.
References ug::GridObject::base_object_id(), UG_ASSERT, and UG_THROW.
Referenced by ug::StdDataLinker< TImpl, TData, dim >::eval_deriv().
template<typename TImpl , typename TData , int dim> void ug::StdDataLinker< TImpl, TData, dim >::compute (LocalVectorTimeSeries * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) virtual
compute values (and derivatives iff compDeriv == true, but only for the 'current' time point)
Implements ug::ICplUserData< dim >.
References ug::GridObject::base_object_id(), UG_ASSERT, and UG_THROW.
template<typename TImpl , typename TData , int dim> bool ug::StdDataLinker< TImpl, TData, dim >::continuous () const virtual
returns if provided data is continuous over geometric object boundaries
Implements ug::UserData< TData, dim, void >.
template<typename TImpl , typename TData , int dim> template<int refDim> void ug::StdDataLinker< TImpl, TData, dim >::eval_deriv (LocalVector * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) protected
template<typename TImpl , typename TData , int dim> template<int refDim> void ug::StdDataLinker< TImpl, TData, dim >::eval_deriv (LocalVectorTimeSeries * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) protected
References ug::StdDataLinker< TImpl, TData, dim >::compute(), and ug::LocalVectorTimeSeries::solution().
template<typename TImpl , typename TData, int dim> template<int refDim> void ug::StdDataLinker< TImpl, TData, dim >::evaluate (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< refDim, dim > * vJT = NULL) const inline
Referenced by ug::StdDataLinker< TImpl, TData, dim >::operator()().
template<typename TImpl, typename TData, int dim> TImpl& ug::StdDataLinker< TImpl, TData, dim >::getImpl () inline protected
access to implementation
template<typename TImpl, typename TData, int dim> const TImpl& ug::StdDataLinker< TImpl, TData, dim >::getImpl () const inline protected
const access to implementation
template<typename TImpl , typename TData , int dim> void ug::StdDataLinker< TImpl, TData, dim >::global_ips_changed (const size_t seriesID, const MathVector< dim > * vPos, const size_t numIP) protected virtual
forwards the global positions to the data inputs
Reimplemented from ug::ICplUserData< dim >.
References UG_ASSERT.
Referenced by ug::StdDataLinker< TImpl, TData, dim >::local_ips_changed(), and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::series_id().
template<typename TImpl, typename TData, int dim> size_t ug::StdDataLinker< TImpl, TData, dim >::input_common_fct (size_t i, size_t fct) const inline protected
returns the number in the common FctGrp for a fct of an input
template<typename TImpl, typename TData, int dim> size_t ug::StdDataLinker< TImpl, TData, dim >::input_num_fct (size_t i) const inline protected
returns number of functions the input depends on
template<typename TImpl , typename TData , int dim> void ug::StdDataLinker< TImpl, TData, dim >::local_ip_series_added (const size_t seriesID) protected virtual
requests series id's from input data
Reimplemented from ug::DependentUserData< TData, dim >.
References ug::DependentUserData< TData, dim >::local_ip_series_added(), ug::StdDataLinker< TImpl, TData, dim >::local_ips_changed(), UG_ASSERT, and UG_THROW.
Referenced by ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::series_id(), and ug::StdDataLinker< TImpl, TData, dim >::set_function_pattern().
template<typename TImpl , typename TData , int dim> void ug::StdDataLinker< TImpl, TData, dim >::local_ips_changed (const size_t seriesID, const size_t newNumIP) protected virtual
forwards the local positions to the data inputs
Reimplemented from ug::DependentUserData< TData, dim >.
References ug::StdDataLinker< TImpl, TData, dim >::global_ips_changed(), ug::DependentUserData< TData, dim >::local_ips_changed(), UG_ASSERT, and UG_THROW.
Referenced by ug::StdDataLinker< TImpl, TData, dim >::local_ip_series_added(), and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::series_id().
template<typename TImpl, typename TData, int dim> virtual SmartPtr<ICplUserData<dim> > ug::StdDataLinker< TImpl, TData, dim >::needed_data (size_t i) inline virtual
return needed data
Reimplemented from ug::ICplUserData< dim >.
template<typename TImpl, typename TData, int dim> virtual size_t ug::StdDataLinker< TImpl, TData, dim >::num_input () const inline virtual
number of inputs
template<typename TImpl, typename TData, int dim> virtual size_t ug::StdDataLinker< TImpl, TData, dim >::num_needed_data () const inline virtual
number of other Data this data depends on
Reimplemented from ug::ICplUserData< dim >.
Referenced by ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::num_input().
template<typename TImpl , typename TData, int dim> void ug::StdDataLinker< TImpl, TData, dim >::operator() (TData & value, const MathVector< dim > & globIP, number time, int si) const virtual
returns value for a global position
Implements ug::StdUserData< StdDataLinker< TImpl, TData, dim >, TData, dim, void, DependentUserData< TData, dim > >.
template<typename TImpl , typename TData, int dim> void ug::StdDataLinker< TImpl, TData, dim >::operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const virtual
returns value for global positions
Implements ug::StdUserData< StdDataLinker< TImpl, TData, dim >, TData, dim, void, DependentUserData< TData, dim > >.
References ug::StdDataLinker< TImpl, TData, dim >::evaluate().
template<typename TImpl , typename TData , int dim> bool ug::StdDataLinker< TImpl, TData, dim >::requires_grid_fct () const virtual
returns that a grid function is needed for evaluation
Reimplemented from ug::DependentUserData< TData, dim >.
Reimplemented in ug::ProjectionLinker< dim >.
template<typename TImpl, typename TData, int dim> size_t ug::StdDataLinker< TImpl, TData, dim >::series_id (size_t i, size_t s) const inline protected
returns the series id set for the i'th input
template<typename TImpl , typename TData , int dim> void ug::StdDataLinker< TImpl, TData, dim >::set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt) virtual
updates the function group
Reimplemented from ug::DependentUserData< TData, dim >.
References ug::CreateFunctionIndexMapping(), ug::CreateUnionOfFunctionGroups(), ug::StdDataLinker< TImpl, TData, dim >::local_ip_series_added(), and UG_CATCH_THROW.
Referenced by ug::StdDataLinker< TImpl, TData, dim >::check_setup(), and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::needed_data().
template<typename TImpl, typename TData, int dim> virtual void ug::StdDataLinker< TImpl, TData, dim >::set_input (size_t i, SmartPtr< ICplUserData< dim > > input, SmartPtr< UserDataInfo > info) inline virtual
sets an input
template<typename TImpl, typename TData, int dim> void ug::StdDataLinker< TImpl, TData, dim >::set_num_input (size_t num) inline
sets the number of inputs
template<typename TImpl , typename TData , int dim> bool ug::StdDataLinker< TImpl, TData, dim >::zero_derivative () const virtual
returns if derivative is zero
Reimplemented from ug::DependentUserData< TData, dim >.
template<typename TImpl, typename TData, int dim> bool ug::StdDataLinker< TImpl, TData, dim >::zero_derivative (size_t i) const inline
returns if the derivative of the i'th input is zero
Member Data Documentation
template<typename TImpl, typename TData, int dim> std::vector<FunctionIndexMapping> ug::StdDataLinker< TImpl, TData, dim >::m_vMap protected
Function mapping for each input relative to common FunctionGroup.
Referenced by ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::input_common_fct().
template<typename TImpl, typename TData, int dim> std::vector<SmartPtr<ICplUserData<dim> > > ug::StdDataLinker< TImpl, TData, dim >::m_vspICplUserData protected
data input
Referenced by ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::needed_data(), ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::num_needed_data(), ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::set_input(), ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::set_num_input(), and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::zero_derivative().
template<typename TImpl, typename TData, int dim> std::vector<SmartPtr<UserDataInfo> > ug::StdDataLinker< TImpl, TData, dim >::m_vspUserDataInfo protected
data input casted to IDependend data
Referenced by ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::input_num_fct(), ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::set_input(), and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::set_num_input().
template<typename TImpl, typename TData, int dim> std::vector<std::vector<size_t> > ug::StdDataLinker< TImpl, TData, dim >::m_vvSeriesID protected
series id the linker uses to get data from input
Referenced by ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::series_id().
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/user_data/linker/linker.h
ugbase/lib_disc/spatial_disc/user_data/linker/linker_impl.h