ug4: ug::Grid::AttachmentAccessor< TElem, TAttachment > Class Template Reference
ug::Grid::AttachmentAccessor< TElem, TAttachment > Class Template Reference
the generic attachment-accessor for access to grids attachment pipes.
#include <grid.h>
Public Member Functions
bool access (Grid &grid, TAttachment &a)
AttachmentAccessor ()
AttachmentAccessor (const AttachmentAccessor &aa)
AttachmentAccessor (Grid &grid, TAttachment &a)
AttachmentAccessor (Grid &grid, TAttachment &a, bool autoAttach)
Public Member Functions inherited from ug::AttachmentAccessor< TElem::grid_base_object *, TAttachment, traits< TElem >::ElementStorage >
bool access (AttachmentPipe< TElem, traits< TElem >::ElementStorage > &attachmentPipe, TAttachment &attachment)
AttachmentAccessor ()
AttachmentAccessor (const AttachmentAccessor &aa)
AttachmentAccessor (AttachmentPipe< TElem, traits< TElem >::ElementStorage > &attachmentPipe, TAttachment &attachment)
size_t element_data_index (typename atraits::ConstElemPtr elem)
returns the data index of the given element regarding the associated container.
void invalidate ()
attachment_value_traits< ValueType >::reference operator[] (typename atraits::ConstElemPtr elem)
attachment_value_traits< ValueType >::const_reference operator[] (typename atraits::ConstElemPtr elem) const
ValueType * raw_data ()
returns the raw pointer to the data of the associated container
void swap (AttachmentAccessor< TElem, TAttachment, traits< TElem >::ElementStorage > &acc)
calls swap on associated containers
bool valid () const
Additional Inherited Members
Public Types inherited from ug::AttachmentAccessor< TElem::grid_base_object *, TAttachment, traits< TElem >::ElementStorage >
typedef attachment_traits< TElem, traits< TElem >::ElementStorage > atraits
typedef TAttachment::ContainerType ContainerType
typedef TElem element
typedef TAttachment::ValueType ValueType
Protected Attributes inherited from ug::AttachmentAccessor< TElem::grid_base_object *, TAttachment, traits< TElem >::ElementStorage >
ContainerType * m_pContainer
traits< TElem >::ElementStorage * m_pHandler
Detailed Description
template<class TElem, class TAttachment>
class ug::Grid::AttachmentAccessor< TElem, TAttachment >
the generic attachment-accessor for access to grids attachment pipes.
Constructor & Destructor Documentation
template<class TElem , class TAttachment > ug::Grid::AttachmentAccessor< TElem, TAttachment >::AttachmentAccessor ()
Referenced by ug::Grid::AttachmentAccessor< TElem, TAttachment >::AttachmentAccessor(), and ug::Grid::find_volume_in_associated_volumes().
template<class TElem , class TAttachment > ug::Grid::AttachmentAccessor< TElem, TAttachment >::AttachmentAccessor (const AttachmentAccessor< TElem, TAttachment > & aa)
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::AttachmentAccessor().
template<class TElem , class TAttachment> ug::Grid::AttachmentAccessor< TElem, TAttachment >::AttachmentAccessor (Grid & grid, TAttachment & a)
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::AttachmentAccessor().
template<class TElem , class TAttachment> ug::Grid::AttachmentAccessor< TElem, TAttachment >::AttachmentAccessor (Grid & grid, TAttachment & a, bool autoAttach)
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::Grid::attach_to(), ug::Grid::has_attachment(), and ug::Grid::VertexAttachmentAccessor< TAttachment >::VertexAttachmentAccessor().
Member Function Documentation
template<class TElem, class TAttachment> bool ug::Grid::AttachmentAccessor< TElem, TAttachment >::access (Grid & grid, TAttachment & a) inline
Referenced by ug::MultiElementAttachmentAccessor< Attachment< Values > >::access(), ug::Grid::AttachmentAccessor< TElem, TAttachment >::AttachmentAccessor(), ug::CylinderProjector< TAPosition >::CylinderProjector(), ug::CylindricalFalloffProjector< TAPosition >::CylindricalFalloffProjector(), ug::Domain< d, TGrid, TSubsetHandler >::Domain(), ug::DoFIndexStorage::init_attachments(), ug::NTreeGridData< world_dim >::NTreeGridData(), ug::RefinementCallbackLinear< TAPosition >::RefinementCallbackLinear(), ug::ComPol_CopyAttachment< TLayout, TAttachment >::set_attachment(), ug::ComPol_GatherVecAttachment< TLayout, TAttachment >::set_attachment(), ug::Partitioner_DynamicBisection< TElem, dim >::set_grid(), ug::FracturedMediaRefiner< TGrid, TAPosition >::set_position_attachment(), ug::SphereProjector< TAPosition >::SphereProjector(), ug::SphericalFalloffProjector< TAPosition >::SphericalFalloffProjector(), ug::SubdivisionLoopBoundaryProjector< TAPosition >::SubdivisionLoopBoundaryProjector(), and ug::SubdivisionLoopProjector< TAPosition >::SubdivisionLoopProjector().
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid/grid.h
ugbase/lib_grid/grid/grid_impl.hpp