ug4: ug::script::LuaError Class Reference
ug::script::LuaError Class Reference
Error class thrown if an error occurs during parsing.
#include <lua_util.h>
Public Member Functions
LuaError (const char *msg)
LuaError ()
bool show_msg () const
Public Member Functions inherited from ug::UGError
const std::string & get_file (size_t i) const
returns the file where a message occured
unsigned long get_line (size_t i) const
returns the line where a message occured
const std::string & get_msg () const
returns the initial message
const std::string & get_msg (size_t i) const
returns a message in the message-stack (innermost is first)
std::string get_stacktrace () const
size_t num_msg () const
number of messages in message-stack
void push_msg (const std::string &msg, const char *file=" -- no file -- ", const unsigned long line=0)
adds a message to the message stack
void push_msg (const char *msg, const char *file=" -- no file -- ", const unsigned long line=0)
adds a message to the message stack
UGError (const char *msg, const char *file=" -- no file -- ", const unsigned long line=0)
UGError (const std::string &msg, const char *file=" -- no file -- ", const unsigned long line=0)
UGError (const std::string &msg, const std::exception &ex, const char *file, const unsigned long line)
virtual ~UGError ()
virtual destructor
Protected Attributes
bool bShowMsg
Protected Attributes inherited from ug::UGError
std::vector< std::string > m_vFile
std::vector< unsigned long > m_vLine
std::vector< std::string > m_vMsg
Detailed Description
Error class thrown if an error occurs during parsing.
Constructor & Destructor Documentation
ug::script::LuaError::LuaError (const char * msg) inline
ug::script::LuaError::LuaError () inline
Member Function Documentation
bool ug::script::LuaError::show_msg () const inline
References bShowMsg.
Referenced by ug::bridge::DebugShell(), main(), and ug::bridge::RunShell().
Member Data Documentation
bool ug::script::LuaError::bShowMsg protected
Referenced by show_msg().
The documentation for this class was generated from the following file:
ugbase/bindings/lua/lua_util.h