ug4: ug::MeanValueMarking< TDomain > Class Template Reference
ug::MeanValueMarking< TDomain > Class Template Reference
#include <error_elem_marking_strategy.h>
Public Types
typedef IElementMarkingStrategy< TDomain > base_type
Public Types inherited from ug::IElementMarkingStrategy< TDomain >
typedef MultiGrid::AttachmentAccessor< elem_type, ug::Attachment< number > > elem_accessor_type
typedef domain_traits< dim >::element_type elem_type
element type to be marked
Public Member Functions
void mark (typename base_type::elem_accessor_type &aaError, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd)
MeanValueMarking (number theta, number factor)
Public Member Functions inherited from ug::IElementMarkingStrategy< TDomain >
virtual ~IElementMarkingStrategy ()
Protected Attributes
number m_factor
number m_theta
Additional Inherited Members
Static Public Attributes inherited from ug::IElementMarkingStrategy< TDomain >
static const int dim = TDomain::dim
world dimension
Detailed Description
template<typename TDomain>
class ug::MeanValueMarking< TDomain >
marks elements above a certain fraction of the maximum
Member Typedef Documentation
template<typename TDomain > typedef IElementMarkingStrategy<TDomain> ug::MeanValueMarking< TDomain >::base_type
Constructor & Destructor Documentation
template<typename TDomain > ug::MeanValueMarking< TDomain >::MeanValueMarking (number theta, number factor) inline
References ug::IElementMarkingStrategy< TDomain >::mark().
Member Function Documentation
template<typename TDomain > void ug::MeanValueMarking< TDomain >::mark (typename base_type::elem_accessor_type & aaError, IRefiner & refiner, ConstSmartPtr< DoFDistribution > dd) virtual
Implements ug::IElementMarkingStrategy< TDomain >.
References pcl::ProcessCommunicator::allreduce(), ug::ComputeMinMax(), ug::IRefiner::mark(), pcl::NumProcs(), PCL_RO_SUM, ug::RM_REFINE, and UG_LOG.
Member Data Documentation
template<typename TDomain > number ug::MeanValueMarking< TDomain >::m_factor protected
template<typename TDomain > number ug::MeanValueMarking< TDomain >::m_theta protected
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/error_elem_marking_strategy.h