ug4: ug::GridLevel Class Reference
ug::GridLevel Class Reference
#include <grid_level.h>
Public Types
enum { TOP = -1 }
indicates that always top level should be used
enum ViewType { LEVEL = 0 , SURFACE = 1 }
type of view
Public Member Functions
bool ghosts () const
returns if ghosts are considered as part of the level
GridLevel ()
constructor creation surface grid
GridLevel (int level)
constructor
GridLevel (int level, const std::string &type)
constructor
GridLevel (int level, ViewType type, bool bWithGhosts=false)
constructor
bool is_level () const
returns if type is level
bool is_surface () const
returns if type is surface
int level () const
returns the level
bool operator!= (const GridLevel &rhs) const
operator !=
bool operator< (const GridLevel &rhs) const
operator <
bool operator<= (const GridLevel &rhs) const
operator <=
bool operator== (const GridLevel &rhs) const
operator ==
bool operator> (const GridLevel &rhs) const
operator >
bool operator>= (const GridLevel &rhs) const
operator >=
bool top () const
returns if top level
ViewType type () const
returns the type
Protected Attributes
bool m_bWithGhosts
with ghosts (only senseful in parallel)
int m_level
the grid level
ViewType m_type
type (i.e. surface or level view)
Member Enumeration Documentation
anonymous enum
anonymous enum
indicates that always top level should be used
Enumerator
TOP
ViewType
enum ug::GridLevel::ViewType
type of view
Enumerator
LEVEL
SURFACE
Constructor & Destructor Documentation
GridLevel() [1/4]
ug::GridLevel::GridLevel () inline
constructor creation surface grid
GridLevel() [2/4]
ug::GridLevel::GridLevel (int level, ViewType type, bool bWithGhosts = false) inline
constructor
GridLevel() [3/4]
ug::GridLevel::GridLevel (int level) inline
constructor
GridLevel() [4/4]
ug::GridLevel::GridLevel (int level, const std::string & type) inline
constructor
References LEVEL, m_type, SURFACE, type(), and UG_THROW.
Member Function Documentation
ghosts()
bool ug::GridLevel::ghosts () const inline
returns if ghosts are considered as part of the level
References m_bWithGhosts.
Referenced by ug::IApproximationSpace::create_dof_distribution(), ug::GridLevelAppendix(), ug::SurfaceView::is_contained(), operator<(), ug::operator<<(), operator==(), operator>(), ug::PrintDoFCount(), and ug::SurfaceView::surface_state().
is_level()
bool ug::GridLevel::is_level () const inline
returns if type is level
References LEVEL, and type().
Referenced by ug::IApproximationSpace::create_dof_distribution(), ug::DoFDistribution::defaultValidSurfState(), ug::GridLevelAppendix(), ug::operator<<(), and ug::PrintDoFCount().
is_surface()
bool ug::GridLevel::is_surface () const inline
returns if type is surface
References SURFACE, and type().
Referenced by ug::DoFDistribution::add_indices_from_layouts(), ug::NestedIterationSolver< TDomain, TAlgebra >::apply(), ug::DoFDistribution::defaultValidSurfState(), ug::GridLevelAppendix(), ug::operator<<(), and ug::PrintDoFCount().
level()
int ug::GridLevel::level () const inline
returns the level
References m_level.
Referenced by ug::DoFDistribution::add_indices_from_layouts(), ug::NestedIterationSolver< TDomain, TAlgebra >::apply(), ug::GridLevelAppendix(), ug::SurfaceView::is_contained(), operator<(), ug::operator<<(), operator==(), operator>(), ug::StdTransfer< TDomain, TAlgebra >::prolongation(), ug::StdTransfer< TDomain, TAlgebra >::restriction(), ug::TruncatedMonotoneTransfer< TDomain, TAlgebra >::restriction(), ug::SurfaceView::surface_state(), top(), and ug::StdTransfer< TDomain, TAlgebra >::write_debug().
operator!=()
bool ug::GridLevel::operator!= (const GridLevel & rhs) const inline
operator !=
References operator==().
operator<()
bool ug::GridLevel::operator< (const GridLevel & rhs) const inline
operator <
References ghosts(), level(), TOP, and type().
operator<=()
bool ug::GridLevel::operator<= (const GridLevel & rhs) const inline
operator <=
operator==()
bool ug::GridLevel::operator== (const GridLevel & rhs) const inline
operator ==
References ghosts(), level(), and type().
Referenced by operator!=().
operator>()
bool ug::GridLevel::operator> (const GridLevel & rhs) const inline
operator >
References ghosts(), level(), TOP, and type().
operator>=()
bool ug::GridLevel::operator>= (const GridLevel & rhs) const inline
operator >=
top()
bool ug::GridLevel::top () const inline
returns if top level
References level(), and TOP.
Referenced by ug::DoFDistribution::add_indices_from_layouts(), ug::NestedIterationSolver< TDomain, TAlgebra >::apply(), ug::GridLevelAppendix(), ug::SurfaceView::is_contained(), ug::operator<<(), and ug::SurfaceView::surface_state().
type()
ViewType ug::GridLevel::type () const inline
returns the type
References m_type.
Referenced by ug::SideFluxErrEstData< TDomain >::alloc_err_est_data(), ug::SideAndElemErrEstData< TDomain >::alloc_err_est_data(), GridLevel(), is_level(), is_surface(), operator<(), operator==(), operator>(), ug::StdTransfer< TDomain, TAlgebra >::prolongation(), ug::DoFDistribution::reinit(), and ug::StdTransfer< TDomain, TAlgebra >::restriction().
Member Data Documentation
m_bWithGhosts
bool ug::GridLevel::m_bWithGhosts protected
with ghosts (only senseful in parallel)
Referenced by ghosts().
m_level
int ug::GridLevel::m_level protected
the grid level
Referenced by level().
m_type
ViewType ug::GridLevel::m_type protected
type (i.e. surface or level view)
Referenced by GridLevel(), and type().
The documentation for this class was generated from the following file:
ugbase/lib_grid/tools/grid_level.h