ug4: ug::UserDataInfo Class Reference
ug::UserDataInfo Class Reference abstract
base class providing runtime-info on dimension and type
#include <user_data.h>
Public Member Functions
virtual bool continuous () const =0
returns if provided data is continuous over geometric object boundaries
const FunctionGroup & function_group () const
Function Group of functions.
virtual int get_dim () const =0
returns dimension
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual bool requires_grid_fct () const =0
returns if grid function is needed for evaluation
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
sets the function pattern for a possibly needed grid function
virtual std::string type () const =0
returns type of data as string (e.g. "Number", "Vector", "Matrix")
virtual ~UserDataInfo ()
virtual destructor
Protected Attributes
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Detailed Description
base class providing runtime-info on dimension and type
Constructor & Destructor Documentation
~UserDataInfo()
virtual ug::UserDataInfo::~UserDataInfo () inline virtual
virtual destructor
References requires_grid_fct().
Member Function Documentation
continuous()
virtual bool ug::UserDataInfo::continuous () const pure virtual
returns if provided data is continuous over geometric object boundaries
Implemented in ug::vrl::VRLCondUserNumber< dim >, ug::GridFunctionGradientComponentData< TGridFunction >, ug::ExplicitGridFunctionGradient< TGridFunction >, ug::GridFunctionGradientData< TGridFunction >, ug::GlobalGridFunctionGradientData< TGridFunction >, ug::ExplicitGridFunctionValue< TGridFunction >, ug::GridFunctionVectorData< TGridFunction >, ug::DataExport< TData, dim >, ug::DataExport< ug::MathMatrix< dim, dim >, dim >, ug::DataExport< ug::MathVector< dim >, dim >, ug::DataExport< number, dim >, ug::VectorDataExport< dim >, ug::GlobalGridFunctionNumberData< TGridFunction, elemDim >, ug::UserData< TData, dim, TRet >, ug::UserData< TRet, dim, void >, ug::UserData< number, dim, void >, ug::UserData< MathTensor< TRank, dim >, dim, void >, ug::UserData< MathVector< TGridFunction::dim >, dim, void >, ug::UserData< TData, dim, void >, ug::UserData< MathVector< dim >, dim, void >, ug::UserData< MathVector< 2 >, dim, void >, ug::UserData< ug::MathVector< dim >, dim, void >, ug::UserData< MathMatrix< N, M >, dim, void >, ug::UserData< TData, worldDim >, ug::UserData< number, worldDim >, ug::UserData< ug::MathMatrix< dim, dim >, dim, void >, ug::UserData< ug::MathVector< worldDim >, worldDim >, ug::UserData< number, dim, bool >, ug::UserData< number, domain_type::dim >, ug::UserData< number, TDomain::dim, void >, ug::UserData< ug::MathVector< non >, dim >, ug::UserData< MathVector< TGridFunc::dim >, dim, void >, ug::UserData< ug::MathVector< dim >, dim >, ug::UserData< MathVector< TGFunc::dim >, dim, void >, ug::UserData< number, dim >, ug::StdConstData< TImpl, TData, dim >, ug::StdConstData< ConstUserVector< dim, worldDim >, MathVector< dim >, worldDim >, ug::StdConstData< ConstUserNumber< dim >, number, dim >, ug::StdConstData< ConstUserMatrix< N, M, worldDim >, MathMatrix< N, M >, worldDim >, ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >, ug::StdGlobPosData< TImpl, TData, dim, TRet >, ug::StdGlobPosData< IDWUserData< WDim, TData >, TData, WDim >, ug::StdGlobPosData< VRLCondUserNumber< dim >, number, dim, bool >, ug::StdGlobPosData< GlobalGridFunctionNumberData< TGridFunction, elemDim >, number, TGridFunction::dim >, ug::StdGlobPosData< VRLUserData< TData, dim >, TData, dim >, ug::StdGlobPosData< RotatingVelocity2d, MathVector< 2 >, 2 >, ug::StdGlobPosData< LuaUserData< TData, dim, TRet >, TData, dim, TRet >, ug::StdGlobPosData< GlobalGridFunctionGradientData< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >, ug::StdGlobPosData< RotatingCone2d, number, 2 >, ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >, ug::GradientDataExport< dim >, ug::SubsetIndicatorUserData< TDomain >, ug::StdExplicitGridFunctionData< TImpl, TData, TGridFunction >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdExplicitGridFunctionData< ExplicitGridFunctionValue< TGridFunction >, number, TGridFunction >, ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >, ug::GridFunctionNumberData< TGridFunction >, ug::ValueDataExport< dim >, ug::Electromagnetism::EddyCurrentCurlEDependentCmpUserData< TImpl, ReIm, TGFunc >, ug::Electromagnetism::EddyCurrentHeat< class >, ug::Electromagnetism::NedelecCurlData< class >, ug::Electromagnetism::NedelecGridFunctionData< class >, ug::Electromagnetism::NedelecSigmaEData< class >, ug::NavierStokes::SeparatedPressureSource< class >, ug::NavierStokes::SeparatedPressureSourceInter< class >, ug::NavierStokes::StdTurbulentViscosityData< TData, dim, TImpl, TGridFunction >, and ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >.
Referenced by ug::UserData< number, dim >::type().
function_group()
const FunctionGroup& ug::UserDataInfo::function_group () const inline
Function Group of functions.
References m_fctGrp.
get_dim()
virtual int ug::UserDataInfo::get_dim () const pure virtual
returns dimension
Implemented in ug::UserData< TData, dim, TRet >, ug::UserData< TRet, dim, void >, ug::UserData< number, dim, void >, ug::UserData< MathTensor< TRank, dim >, dim, void >, ug::UserData< MathVector< TGridFunction::dim >, dim, void >, ug::UserData< TData, dim, void >, ug::UserData< MathVector< dim >, dim, void >, ug::UserData< MathVector< 2 >, dim, void >, ug::UserData< ug::MathVector< dim >, dim, void >, ug::UserData< MathMatrix< N, M >, dim, void >, ug::UserData< TData, worldDim >, ug::UserData< number, worldDim >, ug::UserData< ug::MathMatrix< dim, dim >, dim, void >, ug::UserData< ug::MathVector< worldDim >, worldDim >, ug::UserData< number, dim, bool >, ug::UserData< number, domain_type::dim >, ug::UserData< number, TDomain::dim, void >, ug::UserData< ug::MathVector< non >, dim >, ug::UserData< MathVector< TGridFunc::dim >, dim, void >, ug::UserData< ug::MathVector< dim >, dim >, ug::UserData< MathVector< TGFunc::dim >, dim, void >, and ug::UserData< number, dim >.
map()
const FunctionIndexMapping& ug::UserDataInfo::map () const inline
get function mapping
References m_map.
Referenced by ug::GlobalGridFunctionNumberData< TGridFunction, elemDim >::evaluate(), ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate(), and ug::DependentUserData< MathVector< TGridFunction::dim >, dim >::update_dof_sizes().
num_fct()
size_t ug::UserDataInfo::num_fct () const inline
number of functions this export depends on
References m_map, and ug::FunctionIndexMapping::num_fct().
Referenced by ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::input_common_fct(), and ug::DependentUserData< MathVector< TGridFunction::dim >, dim >::update_dof_sizes().
requires_grid_fct()
virtual bool ug::UserDataInfo::requires_grid_fct () const pure virtual
returns if grid function is needed for evaluation
Implemented in ug::vrl::VRLCondUserNumber< dim >, ug::DependentUserData< TData, dim >, ug::DependentUserData< MathVector< dim >, dim >, ug::DependentUserData< TRet, dim >, ug::DependentUserData< MathVector< TGridFunc::dim >, dim >, ug::DependentUserData< MathVector< TGFunc::dim >, dim >, ug::DependentUserData< ug::MathMatrix< dim, dim >, dim >, ug::DependentUserData< ug::MathVector< dim >, dim >, ug::DependentUserData< number, dim >, ug::DependentUserData< MathVector< TGridFunction::dim >, dim >, ug::DataExport< TData, dim >, ug::DataExport< ug::MathMatrix< dim, dim >, dim >, ug::DataExport< ug::MathVector< dim >, dim >, ug::DataExport< number, dim >, ug::UserData< TData, dim, TRet >, ug::UserData< TRet, dim, void >, ug::UserData< number, dim, void >, ug::UserData< MathTensor< TRank, dim >, dim, void >, ug::UserData< MathVector< TGridFunction::dim >, dim, void >, ug::UserData< TData, dim, void >, ug::UserData< MathVector< dim >, dim, void >, ug::UserData< MathVector< 2 >, dim, void >, ug::UserData< ug::MathVector< dim >, dim, void >, ug::UserData< MathMatrix< N, M >, dim, void >, ug::UserData< TData, worldDim >, ug::UserData< number, worldDim >, ug::UserData< ug::MathMatrix< dim, dim >, dim, void >, ug::UserData< ug::MathVector< worldDim >, worldDim >, ug::UserData< number, dim, bool >, ug::UserData< number, domain_type::dim >, ug::UserData< number, TDomain::dim, void >, ug::UserData< ug::MathVector< non >, dim >, ug::UserData< MathVector< TGridFunc::dim >, dim, void >, ug::UserData< ug::MathVector< dim >, dim >, ug::UserData< MathVector< TGFunc::dim >, dim, void >, ug::UserData< number, dim >, ug::StdConstData< TImpl, TData, dim >, ug::StdConstData< ConstUserVector< dim, worldDim >, MathVector< dim >, worldDim >, ug::StdConstData< ConstUserNumber< dim >, number, dim >, ug::StdConstData< ConstUserMatrix< N, M, worldDim >, MathMatrix< N, M >, worldDim >, ug::StdConstData< ConstUserTensor< TRank, dim >, MathTensor< TRank, dim >, dim >, ug::StdGlobPosData< TImpl, TData, dim, TRet >, ug::StdGlobPosData< IDWUserData< WDim, TData >, TData, WDim >, ug::StdGlobPosData< VRLCondUserNumber< dim >, number, dim, bool >, ug::StdGlobPosData< GlobalGridFunctionNumberData< TGridFunction, elemDim >, number, TGridFunction::dim >, ug::StdGlobPosData< VRLUserData< TData, dim >, TData, dim >, ug::StdGlobPosData< RotatingVelocity2d, MathVector< 2 >, 2 >, ug::StdGlobPosData< LuaUserData< TData, dim, TRet >, TData, dim, TRet >, ug::StdGlobPosData< GlobalGridFunctionGradientData< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >, ug::StdGlobPosData< RotatingCone2d, number, 2 >, ug::StdGlobPosData< LognormalRandomField< TData, dim, TRet >, TData, dim, TRet >, ug::SubsetIndicatorUserData< TDomain >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >, ug::StdExplicitGridFunctionData< TImpl, TData, TGridFunction >, ug::StdExplicitGridFunctionData< ExplicitGridFunctionValue< TGridFunction >, number, TGridFunction >, ug::StdExplicitGridFunctionData< ExplicitGridFunctionGradient< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction >, ug::ProjectionLinker< dim >, ug::Electromagnetism::EddyCurrentCurlEDependentCmpUserData< TImpl, ReIm, TGFunc >, ug::Electromagnetism::EddyCurrentHeat< class >, ug::Electromagnetism::NedelecCurlData< class >, ug::Electromagnetism::NedelecGridFunctionData< class >, ug::Electromagnetism::NedelecSigmaEData< class >, ug::NavierStokes::SeparatedPressureSource< class >, ug::NavierStokes::SeparatedPressureSourceInter< class >, ug::NavierStokes::StdTurbulentViscosityData< TData, dim, TImpl, TGridFunction >, and ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >.
Referenced by ug::UserData< number, dim >::type(), and ~UserDataInfo().
set_function_pattern()
virtual void ug::UserDataInfo::set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt) inline virtual
sets the function pattern for a possibly needed grid function
Reimplemented in ug::DependentUserData< TData, dim >, ug::DependentUserData< MathVector< dim >, dim >, ug::DependentUserData< TRet, dim >, ug::DependentUserData< MathVector< TGridFunc::dim >, dim >, ug::DependentUserData< MathVector< TGFunc::dim >, dim >, ug::DependentUserData< ug::MathMatrix< dim, dim >, dim >, ug::DependentUserData< ug::MathVector< dim >, dim >, ug::DependentUserData< number, dim >, ug::DependentUserData< MathVector< TGridFunction::dim >, dim >, ug::StdDataLinker< TImpl, TData, dim >, ug::StdDataLinker< LuaUserFunction< TData, dim, TDataIn >, TData, dim >, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim >, ug::StdDataLinker< ProjectionLinker< dim >, MathVector< dim >, dim >, ug::StdDataLinker< InverseLinker< dim >, number, dim >, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >, and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >.
References m_fctGrp, and ug::FunctionGroup::set_function_pattern().
Referenced by ug::DependentUserData< MathVector< TGridFunction::dim >, dim >::requires_grid_fct().
type()
virtual std::string ug::UserDataInfo::type () const pure virtual
returns type of data as string (e.g. "Number", "Vector", "Matrix")
Implemented in ug::UserData< TData, dim, TRet >, ug::UserData< TRet, dim, void >, ug::UserData< number, dim, void >, ug::UserData< MathTensor< TRank, dim >, dim, void >, ug::UserData< MathVector< TGridFunction::dim >, dim, void >, ug::UserData< TData, dim, void >, ug::UserData< MathVector< dim >, dim, void >, ug::UserData< MathVector< 2 >, dim, void >, ug::UserData< ug::MathVector< dim >, dim, void >, ug::UserData< MathMatrix< N, M >, dim, void >, ug::UserData< TData, worldDim >, ug::UserData< number, worldDim >, ug::UserData< ug::MathMatrix< dim, dim >, dim, void >, ug::UserData< ug::MathVector< worldDim >, worldDim >, ug::UserData< number, dim, bool >, ug::UserData< number, domain_type::dim >, ug::UserData< number, TDomain::dim, void >, ug::UserData< ug::MathVector< non >, dim >, ug::UserData< MathVector< TGridFunc::dim >, dim, void >, ug::UserData< ug::MathVector< dim >, dim >, ug::UserData< MathVector< TGFunc::dim >, dim, void >, and ug::UserData< number, dim >.
Member Data Documentation
m_fctGrp
FunctionGroup ug::UserDataInfo::m_fctGrp protected
functions the data depends on
Referenced by ug::DependentUserData< MathVector< TGridFunction::dim >, dim >::extract_fct_grp(), function_group(), set_function_pattern(), and ug::DependentUserData< MathVector< TGridFunction::dim >, dim >::set_function_pattern().
m_map
FunctionIndexMapping ug::UserDataInfo::m_map protected
Mapping for import fct.
Referenced by ug::DependentUserData< MathVector< TGridFunction::dim >, dim >::extract_fct_grp(), map(), and num_fct().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/user_data/user_data.h