ug4: ug::Archivar< TArchive, TBase, TPairSeq > Class Template Reference
ug::Archivar< TArchive, TBase, TPairSeq > Class Template Reference
#include <archivar.h>
Public Member Functions
Archivar ()
template<class T >
void archive (TArchive &ar, T &t)
template<class T >
void archive (TArchive &ar, T &t, const char *name)
template<class TDerived >
void register_class (const char *name)
Private Types
typedef void(* archive_sig) (TArchive &, TBase &, const char *name)
typedef std::map< std::string, archive_sig > callback_map_t
Private Attributes
callback_map_t m_callbackMap
Member Typedef Documentation
archive_sig
template<class TArchive , class TBase , class TPairSeq > typedef void(* ug::Archivar< TArchive, TBase, TPairSeq >::archive_sig) (TArchive &, TBase &, const char *name) private
callback_map_t
template<class TArchive , class TBase , class TPairSeq > typedef std::map<std::string, archive_sig> ug::Archivar< TArchive, TBase, TPairSeq >::callback_map_t private
Constructor & Destructor Documentation
Archivar()
template<class TArchive , class TBase , class TPairSeq > ug::Archivar< TArchive, TBase, TPairSeq >::Archivar () inline
References func().
Member Function Documentation
archive() [1/2]
template<class TArchive , class TBase , class TPairSeq > template<class T > void ug::Archivar< TArchive, TBase, TPairSeq >::archive (TArchive & ar, T & t) inline
Referenced by ug::GridWriterUGX::create_projector_node(), ug::GridReaderUGX::read_projector(), and ug::SerializeProjector().
archive() [2/2]
template<class TArchive , class TBase , class TPairSeq > template<class T > void ug::Archivar< TArchive, TBase, TPairSeq >::archive (TArchive & ar, T & t, const char * name) inline
References ug::Archivar< TArchive, TBase, TPairSeq >::m_callbackMap, name, and UG_COND_THROW.
register_class()
template<class TArchive , class TBase , class TPairSeq > template<class TDerived > void ug::Archivar< TArchive, TBase, TPairSeq >::register_class (const char * name) inline
References ug::Archivar< TArchive, TBase, TPairSeq >::m_callbackMap, and name.
Member Data Documentation
m_callbackMap
template<class TArchive , class TBase , class TPairSeq > callback_map_t ug::Archivar< TArchive, TBase, TPairSeq >::m_callbackMap private
Referenced by ug::Archivar< TArchive, TBase, TPairSeq >::archive(), and ug::Archivar< TArchive, TBase, TPairSeq >::register_class().
The documentation for this class was generated from the following file:
ugbase/common/util/archivar.h