ug4: ug::bridge::MethodPtrWrapper Class Reference
ug::bridge::MethodPtrWrapper Class Reference
ugbase » Bridge » Registry
#include <class.h>
Public Member Functions
void * get_raw_ptr () const
MethodPtrWrapper (const MethodPtrWrapper &mpw)
template<typename TMethod >
MethodPtrWrapper (TMethod m)
~MethodPtrWrapper ()
Protected Attributes
void * data
int size
Constructor & Destructor Documentation
MethodPtrWrapper() [1/2]
template<typename TMethod > ug::bridge::MethodPtrWrapper::MethodPtrWrapper (TMethod m) inline
References data, and size.
MethodPtrWrapper() [2/2]
ug::bridge::MethodPtrWrapper::MethodPtrWrapper (const MethodPtrWrapper & mpw) inline
References data, get_raw_ptr(), and size.
~MethodPtrWrapper()
ug::bridge::MethodPtrWrapper::~MethodPtrWrapper () inline
References data.
Member Function Documentation
get_raw_ptr()
void* ug::bridge::MethodPtrWrapper::get_raw_ptr () const inline
References data.
Referenced by ug::bridge::MethodProxy< TClass, TMethod, TRet >::apply(), ug::bridge::MethodProxy< TClass, TMethod, void >::apply(), ug::bridge::MethodProxy< TClass, TMethod, CustomReturn >::apply(), and MethodPtrWrapper().
Member Data Documentation
data
void* ug::bridge::MethodPtrWrapper::data protected
Referenced by get_raw_ptr(), MethodPtrWrapper(), and ~MethodPtrWrapper().
size
int ug::bridge::MethodPtrWrapper::size protected
Referenced by MethodPtrWrapper().
The documentation for this class was generated from the following file:
ugbase/registry/class.h