ug4: ug::vrl::BasicTest Class Reference
ug::vrl::BasicTest Class Reference
#include <basicTest.h>
Public Member Functions
BasicTest ()
BasicTest (std::string name)
std::string get () const
void setName (std::string name)
int size () const
~BasicTest ()
Private Attributes
std::string _name
Constructor & Destructor Documentation
ug::vrl::BasicTest::BasicTest ()
References _name.
Referenced by ug::vrl::getInstanceBySmartPtr().
ug::vrl::BasicTest::BasicTest (std::string name)
References _name.
ug::vrl::BasicTest::~BasicTest ()
References UG_LOG.
Member Function Documentation
std::string ug::vrl::BasicTest::get () const
References _name.
Referenced by ug::vrl::registerBasicTest().
void ug::vrl::BasicTest::setName (std::string name)
References _name.
int ug::vrl::BasicTest::size () const
References _name.
Referenced by ug::vrl::registerBasicTest().
Member Data Documentation
std::string ug::vrl::BasicTest::_name private
Referenced by BasicTest(), get(), setName(), and size().
The documentation for this class was generated from the following files:
ugbase/bindings/vrl/basicTest.h
ugbase/bindings/vrl/basicTest.cpp