ug4: ug::CommonLocalDoFSet Class Reference
ug::CommonLocalDoFSet Class Reference
#include <local_dof_set.h>
Public Types
enum { NOT_SPECIFIED = -1 }
indicate not set value
Public Member Functions
void add (const LocalDoFSet &set)
add a local dof set to the intersection
void clear ()
reset all numbers of dofs to not set
CommonLocalDoFSet ()
constructor
int num_dof (ReferenceObjectID roid) const
number of dofs on a reference element type
Protected Attributes
int m_vNumDoF [NUM_REFERENCE_OBJECTS]
Detailed Description
Intersection of local dof sets
Member Enumeration Documentation
anonymous enum
anonymous enum
indicate not set value
Enumerator
NOT_SPECIFIED
Constructor & Destructor Documentation
CommonLocalDoFSet()
ug::CommonLocalDoFSet::CommonLocalDoFSet () inline
constructor
References clear().
Member Function Documentation
add()
void ug::CommonLocalDoFSet::add (const LocalDoFSet & set)
add a local dof set to the intersection
References ug::LocalDoFSet::dim(), ug::ReferenceElementProvider::get(), m_vNumDoF, NOT_SPECIFIED, ug::ReferenceElement::num(), ug::LocalDoFSet::num_dof(), ug::NUM_REFERENCE_OBJECTS, ug::ReferenceElementDimension(), ug::LocalDoFSet::roid(), and UG_THROW.
clear()
void ug::CommonLocalDoFSet::clear ()
reset all numbers of dofs to not set
References m_vNumDoF, NOT_SPECIFIED, and ug::NUM_REFERENCE_OBJECTS.
Referenced by CommonLocalDoFSet().
num_dof()
int ug::CommonLocalDoFSet::num_dof (ReferenceObjectID roid) const inline
number of dofs on a reference element type
References m_vNumDoF.
Referenced by ug::DoFDistributionInfo::create_offsets(), ug::DoFPositionVertex(), ug::InnerDoFPositionVertex(), ug::operator<<(), ug::OrderDirectionYForDofDist(), ug::OrderDirectionZForDofDist(), and ug::OrderLexForDofDist().
Member Data Documentation
m_vNumDoF
int ug::CommonLocalDoFSet::m_vNumDoF[NUM_REFERENCE_OBJECTS] protected
Referenced by add(), clear(), and num_dof().
The documentation for this class was generated from the following files:
ugbase/lib_disc/local_finite_element/local_dof_set.h
ugbase/lib_disc/local_finite_element/local_dof_set.cpp