ug4: ug::DomainLoadBalancer< TDomain > Class Template Reference
ug::DomainLoadBalancer< TDomain > Class Template Reference
A small wrapper for LoadBalancer which adds comfort methods to balance and distribute domains.
#include <domain_load_balancer.h>
Public Member Functions
virtual void add_serializer (SPEdgeDataSerializer cb)
virtual void add_serializer (SPFaceDataSerializer cb)
virtual void add_serializer (SPGridDataSerializer cb)
virtual void add_serializer (SPVertexDataSerializer cb)
add serialization callbacks.
virtual void add_serializer (SPVolumeDataSerializer cb)
DomainLoadBalancer (SmartPtr< TDomain > dom)
Public Member Functions inherited from ug::LoadBalancer
void create_quality_record (const char *label)
virtual void enable_vertical_interface_creation (bool enable)
LoadBalancer ()
void print_last_quality_record () const
void print_quality_records () const
bool problems_occurred ()
indicates whether problems occurred during the last rebalancing.
virtual bool rebalance ()
performs load balancing if the balance is too bad or if a distribution level has been reached.
virtual void set_balance_threshold (number threshold)
If the balance falls below the given threshold, then rebalance will perform redistribution.
virtual void set_balance_weights (SPBalanceWeights balanceWeights)
Sets a callback class which provides the balance weight for a given element.
virtual void set_element_threshold (size_t threshold)
virtual void set_grid (MultiGrid *mg)
virtual void set_next_process_hierarchy (SPProcessHierarchy procHierarchy)
Sets a callback class which provides connection weights between two neighbor elements.
virtual void set_partitioner (SPPartitioner partitioner)
Sets the partitioner which is used to partition the grid into balanced parts.
virtual ~LoadBalancer ()
virtual number estimate_distribution_quality (std::vector< number > *pLvlQualitiesOut)
number estimate_distribution_quality ()
virtual void add_serializer (SPVertexDataSerializer cb)
add serialization callbacks.
virtual void add_serializer (SPEdgeDataSerializer cb)
add serialization callbacks.
virtual void add_serializer (SPFaceDataSerializer cb)
add serialization callbacks.
virtual void add_serializer (SPVolumeDataSerializer cb)
add serialization callbacks.
virtual void add_serializer (SPGridDataSerializer cb)
add serialization callbacks.
Private Types
typedef LoadBalancer base_class
Private Attributes
SmartPtr< TDomain > m_dom
Detailed Description
template<class TDomain>
class ug::DomainLoadBalancer< TDomain >
A small wrapper for LoadBalancer which adds comfort methods to balance and distribute domains.
Member Typedef Documentation
base_class
template<class TDomain > typedef LoadBalancer ug::DomainLoadBalancer< TDomain >::base_class private
Constructor & Destructor Documentation
DomainLoadBalancer()
template<class TDomain > ug::DomainLoadBalancer< TDomain >::DomainLoadBalancer (SmartPtr< TDomain > dom) inline
Adds serializers for the domains position attachment and for its subset handler.
References ug::LoadBalancer::add_serializer(), create(), ug::SubsetHandlerSerializer::create(), SmartPtr< T, FreePolicy >::get(), ug::LoadBalancer::set_grid(), and SmartPtr< T, FreePolicy >::valid().
Member Function Documentation
add_serializer() [1/5]
template<class TDomain > virtual void ug::LoadBalancer::add_serializer inline
add_serializer() [2/5]
template<class TDomain > virtual void ug::LoadBalancer::add_serializer inline
add_serializer() [3/5]
template<class TDomain > virtual void ug::LoadBalancer::add_serializer inline
add_serializer() [4/5]
template<class TDomain > virtual void ug::LoadBalancer::add_serializer inline
add serialization callbacks.
Used when the grid is being distributed to pack data associated with grid objects or associated classes like subset-handlers.
add_serializer() [5/5]
template<class TDomain > virtual void ug::LoadBalancer::add_serializer inline
Member Data Documentation
m_dom
template<class TDomain > SmartPtr<TDomain> ug::DomainLoadBalancer< TDomain >::m_dom private
The documentation for this class was generated from the following file:
ugbase/lib_disc/parallelization/domain_load_balancer.h