ug4: ug::bridge::ExportedClassBaseImpl Class Reference
ug::bridge::ExportedClassBaseImpl Class Reference
ugbase » Bridge » Registry
A base implementation with non-template methods.
#include <class.h>
Classes
struct ConstructorOverload
Public Member Functions
virtual bool construct_as_smart_pointer () const
returns whether the class shall be wrapped in a SmartPtr on construction
virtual void destroy (void *obj) const
destructur for object
ExportedClassBaseImpl (const std::string &tooltip)
virtual const ExportedMethodGroup * get_const_exported_method_group (const std::string &name) const
virtual const ExportedMethod & get_const_method (size_t i) const
returns the first overload of an exported const function
virtual const ExportedMethodGroup & get_const_method_group (size_t ind) const
returns the i-th method group (all overloads of the i-th function)
virtual const ExportedMethod & get_const_overload (size_t funcInd, size_t oInd) const
returns the i-th overload of a const method
virtual const ExportedConstructor & get_constructor (size_t i) const
get exported constructor
virtual const ExportedMethodGroup * get_exported_method_group (const std::string &name) const
virtual const ExportedMethod & get_method (size_t i) const
returns the first overload of an exported function
virtual const ExportedMethodGroup & get_method_group (size_t ind) const
returns the i-th method group (all overloads of the i-th function)
virtual const ExportedMethod & get_overload (size_t funcInd, size_t oInd) const
returns the i-th overload of a method
virtual bool is_instantiable () const
is instantiable
virtual size_t num_const_methods () const
number of registered const-methods (overloads are not counted)
virtual size_t num_const_overloads (size_t funcInd) const
returns the number of overloads of a const method
virtual size_t num_constructors () const
number of registered constructors
virtual size_t num_methods () const
number of registered methods (overloads are not counted)
virtual size_t num_overloads (size_t funcInd) const
returns the number of overloads of a method
virtual void set_construct_as_smart_pointer (bool enable)
sets whether the class shall be wrapped in a SmartPtr
virtual const std::string & tooltip () const
tooltip
virtual ~ExportedClassBaseImpl ()
destructor
Public Member Functions inherited from ug::bridge::IExportedClass
virtual bool check_consistency () const
returns false is consistency-check failed
virtual const ClassNameNode & class_name_node () const =0
name node of class
virtual const std::vector< const char * > * class_names () const =0
name-list of class hierarchy
virtual DeleteFunction get_delete_function () const =0
returns a function which will call delete on the object
virtual const std::string & group () const =0
get groups
virtual const std::string & name () const =0
name of class
virtual ~IExportedClass ()
virtual destructor
Protected Types
typedef void(* DestructorFunc) (void *)
Protected Member Functions
bool constmethodname_registered (const std::string &name)
returns true if methodname is already used by a method in this class
bool constructor_type_id_registered (size_t typeID)
returns if a constructor overload is registered
ExportedMethodGroup * get_const_exported_method_group (const std::string &name)
ExportedMethodGroup * get_exported_method_group (const std::string &name)
bool methodname_registered (const std::string &name)
returns true if methodname is already used by a method in this class
Protected Attributes
bool m_constructAsSmartPtr
DestructorFunc m_destructor
std::string m_tooltip
std::vector< ExportedMethodGroup * > m_vConstMethod
std::vector< ConstructorOverload > m_vConstructor
std::vector< ExportedMethodGroup * > m_vMethod
Private Member Functions
ExportedClassBaseImpl ()
ExportedClassBaseImpl (const ExportedClassBaseImpl &other)
Additional Inherited Members
Public Types inherited from ug::bridge::IExportedClass
typedef void(* DeleteFunction) (const void *)
Detailed Description
A base implementation with non-template methods.
Speeds up compilation times.
Member Typedef Documentation
typedef void(* ug::bridge::ExportedClassBaseImpl::DestructorFunc) (void *) protected
Constructor & Destructor Documentation
ug::bridge::ExportedClassBaseImpl::ExportedClassBaseImpl () private
Referenced by ug::bridge::IExportedClass::check_consistency(), and ExportedClassBaseImpl().
ug::bridge::ExportedClassBaseImpl::ExportedClassBaseImpl (const ExportedClassBaseImpl & other) private
References ExportedClassBaseImpl().
ug::bridge::ExportedClassBaseImpl::ExportedClassBaseImpl (const std::string & tooltip)
References ~ExportedClassBaseImpl().
ug::bridge::ExportedClassBaseImpl::~ExportedClassBaseImpl () virtual
destructor
References m_vConstMethod, m_vConstructor, m_vMethod, and tooltip().
Referenced by ExportedClassBaseImpl().
Member Function Documentation
bool ug::bridge::ExportedClassBaseImpl::constmethodname_registered (const std::string & name) protected
returns true if methodname is already used by a method in this class
References m_vConstMethod, methodname_registered(), and ug::bridge::IExportedClass::name().
Referenced by constructor_type_id_registered().
bool ug::bridge::ExportedClassBaseImpl::construct_as_smart_pointer () const virtual
returns whether the class shall be wrapped in a SmartPtr on construction
Implements ug::bridge::IExportedClass.
References m_constructAsSmartPtr, and set_construct_as_smart_pointer().
Referenced by get_constructor().
bool ug::bridge::ExportedClassBaseImpl::constructor_type_id_registered (size_t typeID) protected
returns if a constructor overload is registered
References constmethodname_registered(), and m_vConstructor.
Referenced by destroy().
void ug::bridge::ExportedClassBaseImpl::destroy (void * obj) const virtual
destructur for object
Implements ug::bridge::IExportedClass.
References constructor_type_id_registered(), and m_destructor.
Referenced by is_instantiable().
const ExportedMethodGroup * ug::bridge::ExportedClassBaseImpl::get_const_exported_method_group (const std::string & name) const virtual
Implements ug::bridge::IExportedClass.
References m_vConstMethod, and ug::bridge::IExportedClass::name().
Referenced by get_const_exported_method_group(), and get_exported_method_group().
ExportedMethodGroup * ug::bridge::ExportedClassBaseImpl::get_const_exported_method_group (const std::string & name) protected
References get_const_exported_method_group(), m_vConstMethod, and ug::bridge::IExportedClass::name().
const ExportedMethod & ug::bridge::ExportedClassBaseImpl::get_const_method (size_t i) const virtual
returns the first overload of an exported const function
Implements ug::bridge::IExportedClass.
References m_vConstMethod, and num_overloads().
Referenced by get_method().
const ExportedMethodGroup & ug::bridge::ExportedClassBaseImpl::get_const_method_group (size_t ind) const virtual
returns the i-th method group (all overloads of the i-th function)
Implements ug::bridge::IExportedClass.
References m_vConstMethod, and num_constructors().
Referenced by get_method_group().
const ExportedMethod & ug::bridge::ExportedClassBaseImpl::get_const_overload (size_t funcInd, size_t oInd) const virtual
returns the i-th overload of a const method
Implements ug::bridge::IExportedClass.
References get_method_group(), and m_vConstMethod.
Referenced by get_overload().
const ExportedConstructor & ug::bridge::ExportedClassBaseImpl::get_constructor (size_t i) const virtual
get exported constructor
Implements ug::bridge::IExportedClass.
References construct_as_smart_pointer(), and m_vConstructor.
Referenced by num_constructors().
const ExportedMethodGroup * ug::bridge::ExportedClassBaseImpl::get_exported_method_group (const std::string & name) const virtual
Implements ug::bridge::IExportedClass.
References get_const_exported_method_group(), m_vMethod, and ug::bridge::IExportedClass::name().
Referenced by get_exported_method_group(), and methodname_registered().
ExportedMethodGroup * ug::bridge::ExportedClassBaseImpl::get_exported_method_group (const std::string & name) protected
References get_exported_method_group(), m_vMethod, and ug::bridge::IExportedClass::name().
const ExportedMethod & ug::bridge::ExportedClassBaseImpl::get_method (size_t i) const virtual
returns the first overload of an exported function
Implements ug::bridge::IExportedClass.
References get_const_method(), and m_vMethod.
Referenced by num_const_methods().
const ExportedMethodGroup & ug::bridge::ExportedClassBaseImpl::get_method_group (size_t ind) const virtual
returns the i-th method group (all overloads of the i-th function)
Implements ug::bridge::IExportedClass.
References get_const_method_group(), and m_vMethod.
Referenced by get_const_overload().
const ExportedMethod & ug::bridge::ExportedClassBaseImpl::get_overload (size_t funcInd, size_t oInd) const virtual
returns the i-th overload of a method
Implements ug::bridge::IExportedClass.
References get_const_overload(), and m_vMethod.
Referenced by num_const_overloads().
bool ug::bridge::ExportedClassBaseImpl::is_instantiable () const virtual
is instantiable
Implements ug::bridge::IExportedClass.
References destroy(), and m_vConstructor.
Referenced by set_construct_as_smart_pointer().
bool ug::bridge::ExportedClassBaseImpl::methodname_registered (const std::string & name) protected
returns true if methodname is already used by a method in this class
References get_exported_method_group(), m_vMethod, and ug::bridge::IExportedClass::name().
Referenced by constmethodname_registered().
size_t ug::bridge::ExportedClassBaseImpl::num_const_methods () const virtual
number of registered const-methods (overloads are not counted)
Implements ug::bridge::IExportedClass.
References get_method(), and m_vConstMethod.
Referenced by num_methods().
size_t ug::bridge::ExportedClassBaseImpl::num_const_overloads (size_t funcInd) const virtual
returns the number of overloads of a const method
Implements ug::bridge::IExportedClass.
References get_overload(), and m_vConstMethod.
Referenced by num_overloads().
size_t ug::bridge::ExportedClassBaseImpl::num_constructors () const virtual
number of registered constructors
Implements ug::bridge::IExportedClass.
References get_constructor(), and m_vConstructor.
Referenced by get_const_method_group().
size_t ug::bridge::ExportedClassBaseImpl::num_methods () const virtual
number of registered methods (overloads are not counted)
Implements ug::bridge::IExportedClass.
References m_vMethod, and num_const_methods().
Referenced by tooltip().
size_t ug::bridge::ExportedClassBaseImpl::num_overloads (size_t funcInd) const virtual
returns the number of overloads of a method
Implements ug::bridge::IExportedClass.
References m_vMethod, and num_const_overloads().
Referenced by get_const_method().
void ug::bridge::ExportedClassBaseImpl::set_construct_as_smart_pointer (bool enable) virtual
sets whether the class shall be wrapped in a SmartPtr
Returns a reference to this, so that it can be used in a chained call.
References is_instantiable(), and m_constructAsSmartPtr.
Referenced by construct_as_smart_pointer().
const std::string & ug::bridge::ExportedClassBaseImpl::tooltip () const virtual
tooltip
Implements ug::bridge::IExportedClass.
References m_tooltip, and num_methods().
Referenced by ~ExportedClassBaseImpl().
Member Data Documentation
bool ug::bridge::ExportedClassBaseImpl::m_constructAsSmartPtr protected
Referenced by construct_as_smart_pointer(), and set_construct_as_smart_pointer().
DestructorFunc ug::bridge::ExportedClassBaseImpl::m_destructor protected
Referenced by destroy().
std::string ug::bridge::ExportedClassBaseImpl::m_tooltip protected
Referenced by tooltip().
std::vector<ExportedMethodGroup*> ug::bridge::ExportedClassBaseImpl::m_vConstMethod protected
Referenced by constmethodname_registered(), get_const_exported_method_group(), get_const_method(), get_const_method_group(), get_const_overload(), num_const_methods(), num_const_overloads(), and ~ExportedClassBaseImpl().
std::vector<ConstructorOverload> ug::bridge::ExportedClassBaseImpl::m_vConstructor protected
Referenced by constructor_type_id_registered(), get_constructor(), is_instantiable(), num_constructors(), and ~ExportedClassBaseImpl().
std::vector<ExportedMethodGroup*> ug::bridge::ExportedClassBaseImpl::m_vMethod protected
Referenced by get_exported_method_group(), get_method(), get_method_group(), get_overload(), methodname_registered(), num_methods(), num_overloads(), and ~ExportedClassBaseImpl().
The documentation for this class was generated from the following files:
ugbase/registry/class.h
ugbase/registry/class.cpp