ug4: ug::GridReaderUGX Class Reference
ug::GridReaderUGX Class Reference
Grants read access to ugx files.
#include <file_io_ugx.h>
Classes
struct GridEntry
struct SelectorEntry
struct SubsetHandlerEntry
Public Member Functions
const char * get_grid_name (size_t index) const
returns the name of the i-th grid
const char * get_projection_handler_name (size_t refGridIndex, size_t phIndex) const
returns the name of the given projection-handler
size_t get_projection_handler_subset_handler_index (size_t phIndex, size_t refGridIndex)
returns the subset handler index for a projection handler
const char * get_selector_name (size_t refGridIndex, size_t selectorIndex) const
returns the name of the given selector
const char * get_subset_handler_name (size_t refGridIndex, size_t subsetHandlerIndex) const
returns the name of the given subset handler
template<class TPositionAttachment >
bool grid (Grid &gridOut, size_t index, TPositionAttachment &aPos)
returns the i-th grid.
GridReaderUGX ()
size_t num_grids () const
returns the number of grids
size_t num_projection_handlers (size_t refGridIndex) const
returns the number of projection-handlers for the given grid
size_t num_selectors (size_t refGridIndex) const
returns the number of selectors for the given grid
size_t num_subset_handlers (size_t refGridIndex) const
returns the number of subset handlers for the given grid
bool parse_file (const char *filename)
parses an xml file
bool projection_handler (ProjectionHandler &phOut, size_t phIndex, size_t refGridIndex)
fills the given projection-handler
bool selector (ISelector &selOut, size_t selectorIndex, size_t refGridIndex)
fills the given selector
bool subset_handler (ISubsetHandler &shOut, size_t subsetHandlerIndex, size_t refGridIndex)
fills the given subset-handler
virtual ~GridReaderUGX ()
Protected Member Functions
bool create_constrained_edges (std::vector< Edge * > &edgesOut, std::vector< std::pair< int, int > > &constrainingObjsOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_constrained_quadrilaterals (std::vector< Face * > &facesOut, std::vector< std::pair< int, int > > &constrainingObjsOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_constrained_triangles (std::vector< Face * > &facesOut, std::vector< std::pair< int, int > > &constrainingObjsOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
template<class TAAPos >
bool create_constrained_vertices (std::vector< Vertex * > &vrtsOut, std::vector< std::pair< int, int > > &constrainingObjsOut, Grid &grid, rapidxml::xml_node<> *vrtNode, TAAPos aaPos)
bool create_constraining_edges (std::vector< Edge * > &edgesOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_constraining_quadrilaterals (std::vector< Face * > &facesOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_constraining_triangles (std::vector< Face * > &facesOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_edges (std::vector< Edge * > &edgesOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_hexahedrons (std::vector< Volume * > &volsOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_octahedrons (std::vector< Volume * > &volsOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_prisms (std::vector< Volume * > &volsOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_pyramids (std::vector< Volume * > &volsOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_quadrilaterals (std::vector< Face * > &facesOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_tetrahedrons (std::vector< Volume * > &volsOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
bool create_triangles (std::vector< Face * > &facesOut, Grid &grid, rapidxml::xml_node<> *node, std::vector< Vertex * > &vrts)
template<class TAAPos >
bool create_vertices (std::vector< Vertex * > &vrtsOut, Grid &grid, rapidxml::xml_node<> *vrtNode, TAAPos aaPos)
creates vertices from a vertex-node.
virtual bool new_document_parsed ()
initializes internal arrays
template<class TElem >
bool read_attachment (Grid &grid, rapidxml::xml_node<> *node)
SPRefinementProjector read_projector (rapidxml::xml_node<> *projNode)
template<class TGeomObj >
bool read_selector_elements (ISelector &selOut, const char *elemNodeName, rapidxml::xml_node<> *selNode, std::vector< TGeomObj * > &vElems)
template<class TGeomObj >
bool read_subset_handler_elements (ISubsetHandler &shOut, const char *elemNodeName, rapidxml::xml_node<> *subsetNode, int subsetIndex, std::vector< TGeomObj * > &vElems)
Protected Attributes
rapidxml::xml_document m_doc
the xml_document which stores the data
std::vector< GridEntry > m_entries
holds grids which already have been created
Detailed Description
Grants read access to ugx files.
Before any data can be retrieved using the get_* methods, a file has to be successfully loaded using load_file.
Todo:
: Improve performance by using in-situ stringstreams during element creation.
Constructor & Destructor Documentation
GridReaderUGX()
ug::GridReaderUGX::GridReaderUGX ()
~GridReaderUGX()
ug::GridReaderUGX::~GridReaderUGX () virtual
Member Function Documentation
create_constrained_edges()
bool ug::GridReaderUGX::create_constrained_edges (std::vector< Edge * > & edgesOut, std::vector< std::pair< int, int > > & constrainingObjsOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_constrained_quadrilaterals()
bool ug::GridReaderUGX::create_constrained_quadrilaterals (std::vector< Face * > & facesOut, std::vector< std::pair< int, int > > & constrainingObjsOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_constrained_triangles()
bool ug::GridReaderUGX::create_constrained_triangles (std::vector< Face * > & facesOut, std::vector< std::pair< int, int > > & constrainingObjsOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_constrained_vertices()
template<class TAAPos > bool ug::GridReaderUGX::create_constrained_vertices (std::vector< Vertex * > & vrtsOut, std::vector< std::pair< int, int > > & constrainingObjsOut, Grid & grid, rapidxml::xml_node<> * vrtNode, TAAPos aaPos) protected
References ug::Grid::create(), and ug::ConstrainedVertex::set_local_coordinates().
create_constraining_edges()
bool ug::GridReaderUGX::create_constraining_edges (std::vector< Edge * > & edgesOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_constraining_quadrilaterals()
bool ug::GridReaderUGX::create_constraining_quadrilaterals (std::vector< Face * > & facesOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_constraining_triangles()
bool ug::GridReaderUGX::create_constraining_triangles (std::vector< Face * > & facesOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_edges()
bool ug::GridReaderUGX::create_edges (std::vector< Edge * > & edgesOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_hexahedrons()
bool ug::GridReaderUGX::create_hexahedrons (std::vector< Volume * > & volsOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_octahedrons()
bool ug::GridReaderUGX::create_octahedrons (std::vector< Volume * > & volsOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_prisms()
bool ug::GridReaderUGX::create_prisms (std::vector< Volume * > & volsOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_pyramids()
bool ug::GridReaderUGX::create_pyramids (std::vector< Volume * > & volsOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_quadrilaterals()
bool ug::GridReaderUGX::create_quadrilaterals (std::vector< Face * > & facesOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_tetrahedrons()
bool ug::GridReaderUGX::create_tetrahedrons (std::vector< Volume * > & volsOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_triangles()
bool ug::GridReaderUGX::create_triangles (std::vector< Face * > & facesOut, Grid & grid, rapidxml::xml_node<> * node, std::vector< Vertex * > & vrts) protected
References ug::Grid::create(), and UG_LOG.
create_vertices()
template<class TAAPos > bool ug::GridReaderUGX::create_vertices (std::vector< Vertex * > & vrtsOut, Grid & grid, rapidxml::xml_node<> * vrtNode, TAAPos aaPos) protected
creates vertices from a vertex-node.
if aaPos has more coordinates per vertex than the vrtNode, 0's will be appended. If it has less, unused coordinates will be ignored.
References ug::Grid::create().
get_grid_name()
const char * ug::GridReaderUGX::get_grid_name (size_t index) const
returns the name of the i-th grid
get_projection_handler_name()
const char * ug::GridReaderUGX::get_projection_handler_name (size_t refGridIndex, size_t phIndex) const
returns the name of the given projection-handler
References ug::GridReaderUGX::GridEntry::projectionHandlerEntries, and UG_COND_THROW.
get_projection_handler_subset_handler_index()
size_t ug::GridReaderUGX::get_projection_handler_subset_handler_index (size_t phIndex, size_t refGridIndex)
returns the subset handler index for a projection handler
References ug::GridReaderUGX::GridEntry::projectionHandlerEntries, and UG_COND_THROW.
Referenced by ug::LoadDomain().
get_selector_name()
const char * ug::GridReaderUGX::get_selector_name (size_t refGridIndex, size_t selectorIndex) const
returns the name of the given selector
References ug::GridReaderUGX::GridEntry::selectorEntries, and UG_COND_THROW.
get_subset_handler_name()
const char * ug::GridReaderUGX::get_subset_handler_name (size_t refGridIndex, size_t subsetHandlerIndex) const
returns the name of the given subset handler
References ug::GridReaderUGX::GridEntry::subsetHandlerEntries.
Referenced by ug::LoadDomain().
grid()
template<class TPositionAttachment > bool ug::GridReaderUGX::grid (Grid & gridOut, size_t index, TPositionAttachment & aPos)
returns the i-th grid.
TPositionAttachments value type has to be compatible with MathVector. Make sure that a file has already been loaded.
References ug::ConstrainingEdge::add_constrained_object(), ug::ConstrainingFace::add_constrained_object(), ug::Grid::attach_to_vertices(), ug::Grid::begin(), ug::Grid::get_options(), ug::GRIDOPT_NONE, ug::Grid::has_vertex_attachment(), name, ug::ConstrainedVertex::set_constraining_object(), ug::ConstrainedEdge::set_constraining_object(), ug::ConstrainedFace::set_constraining_object(), ug::Grid::set_options(), UG_LOG, and boost::vertices().
Referenced by ug::LoadDomain(), and ug::LoadGridFromUGX().
new_document_parsed()
bool ug::GridReaderUGX::new_document_parsed () protected virtual
initializes internal arrays
searches for all grid-nodes and stores, resizes m_entries and stores the node for each entry.
If you create your own version of this method, don't forget to call the base-class implementation!
References ug::GridReaderUGX::GridEntry::projectionHandlerEntries, ug::GridReaderUGX::GridEntry::selectorEntries, and ug::GridReaderUGX::GridEntry::subsetHandlerEntries.
num_grids()
size_t ug::GridReaderUGX::num_grids () const inline
returns the number of grids
References m_entries.
Referenced by ug::LoadDomain(), and ug::LoadGridFromUGX().
num_projection_handlers()
size_t ug::GridReaderUGX::num_projection_handlers (size_t refGridIndex) const
returns the number of projection-handlers for the given grid
References UG_COND_THROW.
Referenced by ug::LoadDomain().
num_selectors()
size_t ug::GridReaderUGX::num_selectors (size_t refGridIndex) const
returns the number of selectors for the given grid
References UG_COND_THROW.
num_subset_handlers()
size_t ug::GridReaderUGX::num_subset_handlers (size_t refGridIndex) const
returns the number of subset handlers for the given grid
References UG_LOG.
Referenced by ug::LoadDomain(), and ug::LoadGridFromUGX().
parse_file()
bool ug::GridReaderUGX::parse_file (const char * filename)
parses an xml file
Referenced by ug::LoadDomain(), and ug::LoadGridFromUGX().
projection_handler()
bool ug::GridReaderUGX::projection_handler (ProjectionHandler & phOut, size_t phIndex, size_t refGridIndex)
fills the given projection-handler
References ug::GridReaderUGX::GridEntry::projectionHandlerEntries, ug::ProjectionHandler::set_default_projector(), ug::ProjectionHandler::set_projector(), UG_COND_THROW, and SmartPtr< T, FreePolicy >::valid().
Referenced by ug::LoadDomain().
read_attachment()
template<class TElem > bool ug::GridReaderUGX::read_attachment (Grid & grid, rapidxml::xml_node<> * node) protected
References ug::GlobalAttachments::declare_attachment(), ug::GlobalAttachments::is_declared(), name, ug::GlobalAttachments::type_is_registered(), ug::GlobalAttachments::type_name(), and UG_COND_THROW.
read_projector()
SPRefinementProjector ug::GridReaderUGX::read_projector (rapidxml::xml_node<> * projNode) protected
References ug::Archivar< TArchive, TBase, TPairSeq >::archive(), ug::Factory< TBase, TPairSeq >::create(), and UG_LOG.
read_selector_elements()
template<class TGeomObj > bool ug::GridReaderUGX::read_selector_elements (ISelector & selOut, const char * elemNodeName, rapidxml::xml_node<> * selNode, std::vector< TGeomObj * > & vElems) protected
References ug::ISelector::select(), and UG_LOG.
read_subset_handler_elements()
template<class TGeomObj > bool ug::GridReaderUGX::read_subset_handler_elements (ISubsetHandler & shOut, const char * elemNodeName, rapidxml::xml_node<> * subsetNode, int subsetIndex, std::vector< TGeomObj * > & vElems) protected
References ug::ISubsetHandler::assign_subset(), and UG_LOG.
selector()
bool ug::GridReaderUGX::selector (ISelector & selOut, size_t selectorIndex, size_t refGridIndex)
fills the given selector
References ug::GridReaderUGX::GridEntry::edges, ug::ISelector::elements_are_supported(), ug::GridReaderUGX::GridEntry::faces, ug::GridReaderUGX::SelectorEntry::node, ug::GridReaderUGX::SelectorEntry::sel, ug::GridReaderUGX::GridEntry::selectorEntries, ug::SHE_EDGE, ug::SHE_FACE, ug::SHE_VERTEX, ug::SHE_VOLUME, UG_LOG, ug::GridReaderUGX::GridEntry::vertices, and ug::GridReaderUGX::GridEntry::volumes.
subset_handler()
bool ug::GridReaderUGX::subset_handler (ISubsetHandler & shOut, size_t subsetHandlerIndex, size_t refGridIndex)
fills the given subset-handler
References ug::SubsetInfo::color, ug::GridReaderUGX::GridEntry::edges, ug::ISubsetHandler::elements_are_supported(), ug::GridReaderUGX::GridEntry::faces, ug::SubsetInfo::name, ug::GridReaderUGX::SubsetHandlerEntry::node, ug::ISubsetHandler::set_subset_info(), ug::GridReaderUGX::SubsetHandlerEntry::sh, ug::SHE_EDGE, ug::SHE_FACE, ug::SHE_VERTEX, ug::SHE_VOLUME, ug::ISubsetHandler::subset_info(), ug::GridReaderUGX::GridEntry::subsetHandlerEntries, ug::SubsetInfo::subsetState, UG_LOG, ug::GridReaderUGX::GridEntry::vertices, and ug::GridReaderUGX::GridEntry::volumes.
Referenced by ug::LoadDomain(), and ug::LoadGridFromUGX().
Member Data Documentation
m_doc
rapidxml::xml_document ug::GridReaderUGX::m_doc protected
the xml_document which stores the data
m_entries
std::vector<GridEntry> ug::GridReaderUGX::m_entries protected
holds grids which already have been created
Referenced by num_grids().
The documentation for this class was generated from the following files:
ugbase/lib_grid/file_io/file_io_ugx.h
ugbase/lib_grid/file_io/file_io_ugx.cpp
ugbase/lib_grid/file_io/file_io_ugx_impl.hpp