ug4: ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor Class Reference
ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor Class Reference
#include <adaption_surface_grid_function.h>
Public Member Functions
void access_closure (GridObject *elem)
void access_inner (GridObject *elem)
ValueAccessor (AdaptionSurfaceGridFunction< TDomain > &rASGF, size_t fct)
Public Member Functions inherited from ug::TransferValueAccessor
number & operator[] (size_t i)
const number & operator[] (size_t i) const
size_t size () const
virtual ~TransferValueAccessor ()
Protected Member Functions
template<typename TBaseElem , typename TSubBaseElem >
void access_closure (TBaseElem *elem)
template<typename TBaseElem >
void access_closure (TBaseElem *elem)
Protected Attributes
const size_t m_fct
bool m_HasDoFs [NUM_GEOMETRIC_BASE_OBJECTS]
AdaptionSurfaceGridFunction< TDomain > & m_rASGF
Protected Attributes inherited from ug::TransferValueAccessor
std::vector< number * > m_Val
Constructor & Destructor Documentation
ValueAccessor()
template<typename TDomain > ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::ValueAccessor (AdaptionSurfaceGridFunction< TDomain > & rASGF, size_t fct)
References ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::m_HasDoFs, ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::m_rASGF, and ug::NUM_GEOMETRIC_BASE_OBJECTS.
Member Function Documentation
access_closure() [1/3]
template<typename TDomain > void ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::access_closure (GridObject * elem) virtual
Implements ug::TransferValueAccessor.
References ug::GridObject::base_object_id(), ug::EDGE, ug::FACE, UG_THROW, ug::VERTEX, and ug::VOLUME.
access_closure() [2/3]
template<typename TDomain > template<typename TBaseElem , typename TSubBaseElem > void ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::access_closure (TBaseElem * elem) protected
References ug::ComputeOrientationOffset(), ug::ElementDebugInfo(), ug::PointerConstArray< TPtr >::size(), and UG_ASSERT.
access_closure() [3/3]
template<typename TDomain > template<typename TBaseElem > void ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::access_closure (TBaseElem * elem) protected
References ug::EDGE, ug::FACE, ug::VERTEX, and ug::VOLUME.
access_inner()
template<typename TDomain > void ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::access_inner (GridObject * elem) virtual
Implements ug::TransferValueAccessor.
References ug::ElementDebugInfo(), and UG_ASSERT.
Member Data Documentation
m_fct
template<typename TDomain > const size_t ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::m_fct protected
m_HasDoFs
template<typename TDomain > bool ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::m_HasDoFs[NUM_GEOMETRIC_BASE_OBJECTS] protected
Referenced by ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::ValueAccessor().
m_rASGF
template<typename TDomain > AdaptionSurfaceGridFunction<TDomain>& ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::m_rASGF protected
Referenced by ug::AdaptionSurfaceGridFunction< TDomain >::ValueAccessor::ValueAccessor().
The documentation for this class was generated from the following files:
ugbase/lib_disc/function_spaces/adaption_surface_grid_function.h
ugbase/lib_disc/function_spaces/adaption_surface_grid_function.cpp