ug4: pcl::ParallelArchive Class Reference
pcl::ParallelArchive Class Reference
#include <parallel_archive.h>
Classes
struct Buffer_stringstream
struct BufferBinaryBuffer
struct BufferBinaryStream
struct BufferInterface
internal virtual buffer interface to support different buffers
struct ConstCharBuffer
Public Member Functions
void add_raw (FileBufferDescriptor f)
ug::BinaryBuffer & create_BinaryBuffer_file (std::string name)
ug::BinaryStream & create_BinaryStream_file (std::string name)
void create_new_archive (std::string filename)
std::stringstream & create_stringstream_file (std::string name)
ParallelArchive (std::string filename, pcl::ProcessCommunicator pc=pcl::ProcessCommunicator(pcl::PCD_WORLD))
void write ()
~ParallelArchive ()
Private Types
typedef std::map< std::string, SmartPtr< BufferInterface > >::iterator map_iterator
Private Attributes
std::map< std::string, SmartPtr< BufferInterface > > files
bool m_bUnsafe
bool m_bWritten
std::string m_filename
pcl::ProcessCommunicator m_pc
Detailed Description
This class creates one .a archive out of several parallel file writes This has two advantages
Instead of writing 1024 files for 1024 cores, this writes 1 file
It uses MPI I/O, which will be a LOT faster when number of cores are high
For extracting the archive use ar x thefile.a
Example usage:
  ParallelArchive pa("test.tar", pcl::ProcessCommunicator(pcl::PCD_WORLD));
std::stringstream &b = pa.create_stringstream_file(std::string("bla") + ToString(pcl::ProcRank()));
b << "Hello World!";
pa.write();
Member Typedef Documentation
map_iterator
typedef std::map<std::string, SmartPtr<BufferInterface> >::iterator pcl::ParallelArchive::map_iterator private
Constructor & Destructor Documentation
ParallelArchive()
pcl::ParallelArchive::ParallelArchive (std::string filename, pcl::ProcessCommunicator pc = pcl::ProcessCommunicator(pcl::PCD_WORLD)) inline
Create a parallel archive. Note that the file is written on descruction or when you call write() explicitely
Parameters
filename the name of the archive. add .a for clearness
pc the process communicator used for MPI purposes. default WORLD
References m_bUnsafe, and m_bWritten.
~ParallelArchive()
pcl::ParallelArchive::~ParallelArchive () inline
if the file(s) were not written already, this will write the file NOTE: Don't do this when using add_raw (unsafe!) NOTE: Communication happens here.
References m_bUnsafe, m_bWritten, UG_LOGN, and write().
Member Function Documentation
add_raw()
void pcl::ParallelArchive::add_raw (FileBufferDescriptor f) inline
add raw buffer descriptors (see FileBufferDescriptor) NOTE: be sure all data/pointers are valid until write is called NOTE: You HAVE to use ParallelArchive::write explicitely using deconstructors is UNSAFE since data can be deconstructed before ParallelArchive.
Parameters
f
References pcl::FileBufferDescriptor::buf, files, m_bUnsafe, make_sp(), pcl::FileBufferDescriptor::name, and pcl::FileBufferDescriptor::size.
create_BinaryBuffer_file()
ug::BinaryBuffer& pcl::ParallelArchive::create_BinaryBuffer_file (std::string name) inline
create a file inside the archive.
Parameters
name the filename inside the archive. can be a path, but only filename is taken
Returns
a BinaryBuffer to write data to
References files, name, and p.
create_BinaryStream_file()
ug::BinaryStream& pcl::ParallelArchive::create_BinaryStream_file (std::string name) inline
create a file inside the archive.
Parameters
name the filename inside the archive. can be a path, but only filename is taken
Returns
a BinaryStream to write data to
References files, name, and p.
create_new_archive()
void pcl::ParallelArchive::create_new_archive (std::string filename) inline
References m_bWritten, m_filename, and write().
create_stringstream_file()
std::stringstream& pcl::ParallelArchive::create_stringstream_file (std::string name) inline
create a file inside the archive.
Parameters
name the filename inside the archive. can be a path, but only filename is taken
Returns
a stringstream to write data to
References files, name, and p.
Referenced by ug::ConnectionViewer::WriteMatrixPar().
write()
void pcl::ParallelArchive::write () inline
explicitely writes the data NOTE: Communication happens here.
References ug::FilenameWithoutPath(), files, m_bWritten, m_filename, m_pc, and pcl::WriteParallelArchive().
Referenced by create_new_archive(), and ~ParallelArchive().
Member Data Documentation
files
std::map<std::string, SmartPtr<BufferInterface> > pcl::ParallelArchive::files private
Referenced by add_raw(), create_BinaryBuffer_file(), create_BinaryStream_file(), create_stringstream_file(), and write().
m_bUnsafe
bool pcl::ParallelArchive::m_bUnsafe private
Referenced by add_raw(), ParallelArchive(), and ~ParallelArchive().
m_bWritten
bool pcl::ParallelArchive::m_bWritten private
Referenced by create_new_archive(), ParallelArchive(), write(), and ~ParallelArchive().
m_filename
std::string pcl::ParallelArchive::m_filename private
Referenced by create_new_archive(), and write().
m_pc
pcl::ProcessCommunicator pcl::ParallelArchive::m_pc private
Referenced by write().
The documentation for this class was generated from the following file:
ugbase/pcl/parallel_archive.h