ug4: ug::UID Class Reference
ug::UID Class Reference
ugbase » Common » Common Utilities
supplies a unique ID.
#include <uid.h>
Public Member Functions
unsigned int id () const
bool operator== (const UID &uid)
UID ()
UID (const UID &uid)
virtual ~UID ()
Private Attributes
unsigned int m_uID
Detailed Description
supplies a unique ID.
Derivatives of this class can be identified by their unique ID. Useful for hashing and other applications, where the need for identification is given.
Constructor & Destructor Documentation
UID() [1/2]
ug::UID::UID () inline
References m_uID.
UID() [2/2]
ug::UID::UID (const UID & uid) inline
References id(), and m_uID.
~UID()
virtual ug::UID::~UID () inline virtual
References m_uID.
Member Function Documentation
id()
unsigned int ug::UID::id () const inline
References m_uID.
Referenced by ug::AttachmentPipe< TElem *, ElementStorage< TElem > >::attach(), ug::AttachmentPipe< TElem *, ElementStorage< TElem > >::detach(), ug::AttachmentPipe< TElem *, ElementStorage< TElem > >::get_data_container(), ug::AttachmentPipe< TElem *, ElementStorage< TElem > >::has_attachment(), operator==(), and UID().
operator==()
bool ug::UID::operator== (const UID & uid) inline
References id().
Member Data Documentation
m_uID
unsigned int ug::UID::m_uID private
Referenced by id(), UID(), and ~UID().
The documentation for this class was generated from the following file:
ugbase/common/util/uid.h