ug4: ug::BoundedEquidistantLagrange1D Class Reference
ug::BoundedEquidistantLagrange1D Class Reference
#include <lagrange1d.h>
Public Member Functions
BoundedEquidistantLagrange1D (const size_t i, const size_t degree, const size_t bound)
Public Member Functions inherited from ug::Polynomial1D
size_t degree () const
Polynomial1D derivative () const
returns the derivative of this polynomial as a polynomial
Polynomial1D & operator*= (const Polynomial1D &v)
multiply by a polynomial
Polynomial1D & operator*= (number scale)
multiply by a scalar
Polynomial1D (const std::vector< number > &a)
Constructor passing coefficients for the polynomial.
Polynomial1D (size_t degree=0)
Constructor producing zero polynomial of degree 'degree'.
number value (const number x) const
evaluate the value of the polynom at x
Static Public Member Functions
static number position (const size_t i, const size_t degree)
returns the position of the i'th interpolation point
Protected Member Functions
void compute_coeffs (const int i, const int p, const int b)
computes the coefficients for passed interpolation points
Protected Member Functions inherited from ug::Polynomial1D
void set_coefficients (const std::vector< number > &a)
Detailed Description
Bounded EquiDistant Lagrange Function
Creates for given order p, interpolation point i and upper bound 0 <= b <= p the polynomial
\[ \prod_{\substack{j=0\\j\neq i}}^{b} \frac{x - \frac{j}{p}}{\frac{i}{p} - \frac{j}{p}} \]
Thus, it is a polynomial of order b.
Constructor & Destructor Documentation
BoundedEquidistantLagrange1D()
ug::BoundedEquidistantLagrange1D::BoundedEquidistantLagrange1D (const size_t i, const size_t degree, const size_t bound) inline
creates a lagrange polynomial with equidistant interpolation points
Parameters
[in] i number of interpolation point, where polynom is 1
[in] degree degree of polynom
[in] bound Point until lagrange points are included
References compute_coeffs(), ug::Polynomial1D::degree(), and UG_ASSERT.
Member Function Documentation
compute_coeffs()
void ug::BoundedEquidistantLagrange1D::compute_coeffs (const int i, const int p, const int b) inline protected
computes the coefficients for passed interpolation points
References p, and ug::Polynomial1D::set_coefficients().
Referenced by BoundedEquidistantLagrange1D().
position()
static number ug::BoundedEquidistantLagrange1D::position (const size_t i, const size_t degree) inline static
returns the position of the i'th interpolation point
References ug::Polynomial1D::degree(), and UG_ASSERT.
The documentation for this class was generated from the following file:
ugbase/lib_disc/local_finite_element/common/lagrange1d.h