ug4: ug::EdgeDescriptor Class Reference
ug::EdgeDescriptor Class Reference
Can be used to store information about an edge and to construct an edge.
#include <grid_base_objects.h>
Public Member Functions
EdgeDescriptor ()
EdgeDescriptor (const EdgeDescriptor &ed)
EdgeDescriptor (Vertex *vrt1, Vertex *vrt2)
EdgeDescriptor & operator= (const EdgeDescriptor &ed)
void set_vertex (uint index, Vertex *vrt)
void set_vertices (Vertex *vrt1, Vertex *vrt2)
Public Member Functions inherited from ug::EdgeVertices
virtual size_t num_vertices () const
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual Vertex * vertex (size_t index) const
virtual ConstVertexArray vertices () const
virtual ~EdgeVertices ()
Public Member Functions inherited from ug::IVertexGroup
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~IVertexGroup ()
Additional Inherited Members
Public Types inherited from ug::IVertexGroup
typedef Vertex *const * ConstVertexArray
Protected Member Functions inherited from ug::EdgeVertices
void assign_edge_vertices (const EdgeVertices &ev)
Protected Attributes inherited from ug::EdgeVertices
Vertex * m_vertices [2]
Detailed Description
Can be used to store information about an edge and to construct an edge.
Constructor & Destructor Documentation
EdgeDescriptor() [1/3]
ug::EdgeDescriptor::EdgeDescriptor ()
EdgeDescriptor() [2/3]
ug::EdgeDescriptor::EdgeDescriptor (const EdgeDescriptor & ed)
References ug::EdgeVertices::assign_edge_vertices().
EdgeDescriptor() [3/3]
ug::EdgeDescriptor::EdgeDescriptor (Vertex * vrt1, Vertex * vrt2)
References ug::EdgeVertices::m_vertices.
Member Function Documentation
operator=()
EdgeDescriptor & ug::EdgeDescriptor::operator= (const EdgeDescriptor & ed)
References ug::EdgeVertices::assign_edge_vertices().
set_vertex()
void ug::EdgeDescriptor::set_vertex (uint index, Vertex * vrt) inline
set_vertices()
void ug::EdgeDescriptor::set_vertices (Vertex * vrt1, Vertex * vrt2) inline
Referenced by ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_2d(), ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_3d(), ug::Face::edge_desc(), ug::CustomTriangle< ConcreteTriangleType, BaseClass, RefTriType, RefQuadType >::edge_desc(), ug::CustomQuadrilateral< ConcreteQuadrilateralType, BaseClass, RefTriType, RefQuadType >::edge_desc(), ug::Tetrahedron::edge_desc(), ug::Hexahedron::edge_desc(), ug::Prism::edge_desc(), ug::Pyramid::edge_desc(), ug::Octahedron::edge_desc(), ug::MergeGrids(), ug::MergeVertices(), ug::GlobalFracturedMediaRefiner::perform_refinement(), and ug::Grid::replace_vertex().
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid/grid_base_objects.h
ugbase/lib_grid/grid/grid_base_objects.cpp