ug4: ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV Class Reference
ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV Class Reference
sub control volume structure
#include <fvho_geom.h>
Public Member Functions
number detJ (size_t ip) const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_corner (size_t co) const
return glbal corner number i
const MathVector< worldDim > & global_grad (size_t ip, size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector (size_t ip) const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip (size_t ip) const
global integration point
const MathMatrix< worldDim, dim > & JTInv (size_t ip) const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t ip, size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector (size_t ip) const
vector of local gradients in ip point
const MathVector< dim > & local_ip (size_t ip) const
local integration point of scv
size_t node_id () const
node id that this scv is associated to
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shape functions
SCV ()
number shape (size_t ip, size_t sh) const
value of shape function i in integration point
const number * shape_vector (size_t ip) const
vector of shape functions in ip point
number weight (size_t ip) const
weigth of integration point
Static Public Attributes
static const size_t nip = scv_quad_rule_type::nip
Number of integration points.
static const size_t numCo = traits::NumCornersOfSCV
Number of corners of scvf.
Private Attributes
size_t nodeId
number vDetJ [nip]
number vDetJMap [nip]
MathVector< worldDim > vGlobalIP [nip]
MathVector< worldDim > vGloPos [numCo]
MathMatrix< worldDim, dim > vJtInv [nip]
MathVector< dim > vLocalIP [nip]
MathVector< dim > vLocPos [numCo]
MidID vMidID [numCo]
MathVector< worldDim > vvGlobalGrad [nip][nsh]
MathVector< dim > vvLocalGrad [nip][nsh]
number vvShape [nip][nsh]
const number * vWeight
Friends
class FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >
Detailed Description
template<int TOrder, typename TElem, int TWorldDim, int TQuadOrder = TOrder + 1>
class ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV
sub control volume structure
Constructor & Destructor Documentation
SCV()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::SCV () inline
Member Function Documentation
detJ()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::detJ (size_t ip) const inline
Determinant of Jacobian in integration point.
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vDetJ.
global_corner()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_corner (size_t co) const inline
return glbal corner number i
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_corners(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vGloPos.
global_grad()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_grad (size_t ip, size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_sh(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vvGlobalGrad.
global_grad_vector()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_grad_vector (size_t ip) const inline
vector of global gradients in ip point
global_ip()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_ip (size_t ip) const inline
global integration point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vGlobalIP.
JTInv()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathMatrix<worldDim,dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::JTInv (size_t ip) const inline
Transposed Inverse of Jacobian in integration point.
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vJtInv.
local_corner()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_corner (size_t co) const inline
return local corner number i
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_corners(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vLocPos.
local_grad()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad (size_t ip, size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_sh(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vvLocalGrad.
local_grad_vector()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad_vector (size_t ip) const inline
vector of local gradients in ip point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vvLocalGrad.
local_ip()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_ip (size_t ip) const inline
local integration point of scv
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vLocalIP.
node_id()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::node_id () const inline
node id that this scv is associated to
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::nodeId.
num_corners()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_corners () const inline
number of corners, that bound the scvf
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::numCo.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_corner(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_corner().
num_ip()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip () const inline
number of integration points
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::nip.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::detJ(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::JTInv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad_vector(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::shape(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::shape_vector(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::weight().
num_sh()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_sh () const inline
number of shape functions
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::nsh.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_grad(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad().
shape()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::shape (size_t ip, size_t sh) const inline
value of shape function i in integration point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vvShape.
shape_vector()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const number* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::shape_vector (size_t ip) const inline
vector of shape functions in ip point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), UG_ASSERT, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vvShape.
weight()
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::weight (size_t ip) const inline
weigth of integration point
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), UG_ASSERT, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vDetJMap, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vWeight.
Friends And Related Function Documentation
FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> friend class FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder > friend
Member Data Documentation
nip
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::nip = scv_quad_rule_type::nip static
Number of integration points.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip().
nodeId
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::nodeId private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::node_id().
numCo
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::numCo = traits::NumCornersOfSCV static
Number of corners of scvf.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_corners().
vDetJ
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vDetJ[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::detJ().
vDetJMap
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vDetJMap[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::weight().
vGlobalIP
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vGlobalIP[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_ip().
vGloPos
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vGloPos[numCo] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_corner().
vJtInv
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathMatrix<worldDim,dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vJtInv[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::JTInv().
vLocalIP
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vLocalIP[nip] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_ip().
vLocPos
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vLocPos[numCo] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_corner().
vMidID
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MidID ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vMidID[numCo] private
vvGlobalGrad
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vvGlobalGrad[nip][nsh] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_grad().
vvLocalGrad
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vvLocalGrad[nip][nsh] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_grad_vector().
vvShape
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> number ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vvShape[nip][nsh] private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::shape(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::shape_vector().
vWeight
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const number* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vWeight private
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::weight().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fvho_geom.h