ug4: ug::FETISolver< TAlgebra > Class Template Reference
ug::FETISolver< TAlgebra > Class Template Reference
operator implementation of the FETI-DP solver
#include <feti.h>
Public Types
typedef TAlgebra algebra_type
typedef ILinearOperatorInverse< vector_type > base_type
Base type.
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
Public Types inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual bool apply (vector_type &x, const vector_type &b)
solves the system
bool apply_F (vector_type &f, const vector_type &v)
function which applies matrix \(F\) of the reduced system ("Delta system") to a vector \(v\)
bool apply_M_inverse (vector_type &z, const vector_type &r)
function which applies matrix \(M^{-1}^{(i)} \) to a vector \(r \)
virtual bool apply_return_defect (vector_type &lambda, vector_type &d)
bool apply_scaling_matrix (vector_type &s, const vector_type &v)
function which applies diagonal scaling matrix \(D_{\Delta}^{(i)}\) to a vector \(v\)
bool compute_d (vector_type &d, const vector_type &f)
function which computes right hand side vector 'd' of the dual unknowns
FETISolver ()
constructor
virtual bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > A)
initializes the solver for operator A
virtual const char * name () const
name of solver
void print_statistic_of_inner_solver (bool bPrintOnlyAverages)
prints some convergence statistic of inner solvers
void set_coarse_problem_solver (SmartPtr< ILinearOperatorInverse< vector_type > > coarseProblemSolver)
sets the coarse problem solver
void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
void set_dirichlet_solver (SmartPtr< ILinearOperatorInverse< vector_type > > dirichletSolver)
sets the Dirichlet solver
void set_domain_decomp_info (pcl::IDomainDecompositionInfo &ddInfo)
void set_neumann_solver (SmartPtr< ILinearOperatorInverse< vector_type > > neumannSolver)
sets the Neumann solver
void set_test_one_to_many_layouts (bool bTest)
virtual bool supports_parallel () const
returns if parallel solving is supported
void test_layouts (bool bPrint)
virtual ~FETISolver ()
Public Member Functions inherited from ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >
virtual bool init (SmartPtr< MatrixOperator< TAlgebra::matrix_type, TAlgebra::vector_type, TAlgebra::vector_type > > A)=0
initializes this inverse operator for a matrix-based operator
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > A, const TAlgebra::vector_type &u)
initializes this inverse operator for a linear operator
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > A)
initializes this inverse operator for a linear operator
virtual ~IMatrixOperatorInverse ()
virtual destructor
Public Member Functions inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
virtual bool apply_update_defect (TAlgebra::vector_type &u, TAlgebra::vector_type &f)
compute new correction c = B*d and update defect d := d - A*c
virtual SmartPtr< ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > > clone ()
clone
virtual std::string config_string () const
returns information about configuration parameters
ConstSmartPtr< IConvergenceCheck< TAlgebra::vector_type > > convergence_check () const
returns the convergence check
SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > convergence_check ()
returns the convergence check
number defect () const
returns the current defect
ILinearOperatorInverse ()
constructor setting convergence check to (100, 1e-12, 1e-12, true)
ILinearOperatorInverse (SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > spConvCheck)
Default constructor.
SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > linear_operator ()
returns the current Operator this Inverse Operator is initialized for
number reduction () const
returns the current relative reduction
void set_convergence_check (SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > spConvCheck)
set the convergence check
virtual int standard_offset () const
returns the standard offset for output
int step () const
returns the current number of steps
virtual ~ILinearOperatorInverse ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
void set_damp (number factor)
sets the damping to a constant factor
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
DebugWritingObject ()
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
void prepare_conv_check ()
virtual void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
virtual void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void write_debug (const vector_type &vec, std::string filename)
Protected Attributes
FetiLayouts< algebra_type > m_fetiLayouts
int m_iterCnt
LocalSchurComplement< algebra_type > m_LocalSchurComplement
matrix_type * m_pMatrix
PrimalSubassembledMatrixInverse< algebra_type > m_PrimalSubassembledMatrixInverse
SmartPtr< ILinearOperatorInverse< vector_type > > m_spCoarseProblemSolver
SmartPtr< ILinearOperatorInverse< vector_type > > m_spDirichletSolver
SmartPtr< ILinearOperatorInverse< vector_type > > m_spNeumannSolver
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spOperator
Protected Attributes inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > m_spConvCheck
smart pointer holding the convergence check
SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > m_spLinearOperator
Operator that is inverted by this Inverse Operator.
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Private Attributes
pcl::IDomainDecompositionInfo * m_pDDInfo
Detailed Description
template<typename TAlgebra>
class ug::FETISolver< TAlgebra >
operator implementation of the FETI-DP solver
This operator implements a FETI-DP solver, see e.g. "Domain Decomposition Methods -- Algorithms and Theory", A. Toselli, O. Widlund, Springer 2004, sec. 1.3.5, p. 12ff.
Member Typedef Documentation
template<typename TAlgebra > typedef TAlgebra ug::FETISolver< TAlgebra >::algebra_type
template<typename TAlgebra > typedef ILinearOperatorInverse<vector_type> ug::FETISolver< TAlgebra >::base_type
Base type.
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::FETISolver< TAlgebra >::matrix_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::FETISolver< TAlgebra >::vector_type
Constructor & Destructor Documentation
template<typename TAlgebra > ug::FETISolver< TAlgebra >::FETISolver ()
constructor
References ug::FETISolver< TAlgebra >::init().
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::print_statistic_of_inner_solver().
template<typename TAlgebra > virtual ug::FETISolver< TAlgebra >::~FETISolver () inline virtual
Member Function Documentation
template<typename TAlgebra > virtual bool ug::FETISolver< TAlgebra >::apply (vector_type & x, const vector_type & b) inline virtual
solves the system
Implements ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >.
template<typename TAlgebra > bool ug::FETISolver< TAlgebra >::apply_F (vector_type & f, const vector_type & v)
function which applies matrix \(F\) of the reduced system ("Delta system") to a vector \(v\)
This function applies matrix \(F := B_{\Delta} \tilde{S}^{-1} B_{\Delta}^T\) to a vector \(v\). \(v\) can be: (a) unknown vector of Lagrange multipliers, lambda, and (b) search direction 'p' in cg method.
Parameters
[in] v vector \(v\) living on "Dual layout"
[out] f result of application of \(F\)
References ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply(), ug::FETISolver< TAlgebra >::compute_d(), ug::ComputeDifferenceOnDelta(), ug::ComputeDifferenceOnDeltaTransposed(), FETI_PROFILE_BEGIN, FETI_PROFILE_END, FETI_PROFILE_FUNC, ug::FetiLayouts< TAlgebra >::get_dual_master_indices(), ug::FetiLayouts< TAlgebra >::get_dual_master_layout(), ug::FetiLayouts< TAlgebra >::get_dual_nbr_master_layout(), ug::FetiLayouts< TAlgebra >::get_dual_nbr_slave_indices(), ug::FetiLayouts< TAlgebra >::get_dual_nbr_slave_layout(), ug::FetiLayouts< TAlgebra >::get_dual_slave_indices(), ug::FetiLayouts< TAlgebra >::get_dual_slave_layout(), ug::FETISolver< TAlgebra >::m_fetiLayouts, ug::FETISolver< TAlgebra >::m_PrimalSubassembledMatrixInverse, ug::PST_ADDITIVE, ug::PST_CONSISTENT, and ug::FetiLayouts< TAlgebra >::vec_use_intra_sd_communication().
Referenced by ug::FETISolver< TAlgebra >::apply_return_defect().
template<typename TAlgebra > bool ug::FETISolver< TAlgebra >::apply_M_inverse (vector_type & z, const vector_type & r)
function which applies matrix \(M^{-1}^{(i)} \) to a vector \(r \)
This function applies matrix \(M^{-1}^{(i)} := D_{\Delta}^{(i)} B_{\Delta}^{(i)} S_{\Delta}^{(i)} {B_{\Delta}^{(i)}}^T D_{\Delta}^{(i)}\) to a vector \(r\).
Parameters
[in] r vector \(r\) living on "Dual layout"
[out] z result of application of \(M^{-1} \)
References ug::LocalSchurComplement< TAlgebra >::apply(), ug::FETISolver< TAlgebra >::apply_scaling_matrix(), ug::ComputeDifferenceOnDelta(), ug::ComputeDifferenceOnDeltaTransposed(), FETI_PROFILE_BEGIN, FETI_PROFILE_END, FETI_PROFILE_FUNC, ug::FetiLayouts< TAlgebra >::get_dual_master_indices(), ug::FetiLayouts< TAlgebra >::get_dual_master_layout(), ug::FetiLayouts< TAlgebra >::get_dual_nbr_master_layout(), ug::FetiLayouts< TAlgebra >::get_dual_nbr_slave_indices(), ug::FetiLayouts< TAlgebra >::get_dual_nbr_slave_layout(), ug::FetiLayouts< TAlgebra >::get_dual_slave_indices(), ug::FetiLayouts< TAlgebra >::get_dual_slave_layout(), ug::FETISolver< TAlgebra >::m_fetiLayouts, ug::FETISolver< TAlgebra >::m_LocalSchurComplement, ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::FETISolver< TAlgebra >::test_layouts(), and ug::FetiLayouts< TAlgebra >::vec_use_intra_sd_communication().
Referenced by ug::FETISolver< TAlgebra >::apply_return_defect(), and ug::FETISolver< TAlgebra >::compute_d().
template<typename TAlgebra > bool ug::FETISolver< TAlgebra >::apply_return_defect (vector_type & lambda, vector_type & d) virtual
solves the reduced system \(F \lambda = d\) with preconditioned cg method and returns the last defect of iteration in rhs (derived from 'CGSolver::apply_return_defect()')
Implements ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >.
References pcl::AllProcsTrue(), alpha, ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply(), ug::FETISolver< TAlgebra >::apply_F(), ug::FETISolver< TAlgebra >::apply_M_inverse(), ug::FETISolver< TAlgebra >::compute_d(), ug::ComputeDifferenceOnDeltaTransposed(), ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >::convergence_check(), FETI_PROFILE_BEGIN, FETI_PROFILE_END, ug::FetiLayouts< TAlgebra >::get_dual_master_indices(), ug::FetiLayouts< TAlgebra >::get_dual_nbr_slave_indices(), ug::FetiLayouts< TAlgebra >::get_dual_slave_indices(), ug::FETISolver< TAlgebra >::m_fetiLayouts, ug::FETISolver< TAlgebra >::m_iterCnt, ug::FETISolver< TAlgebra >::m_LocalSchurComplement, ug::FETISolver< TAlgebra >::m_PrimalSubassembledMatrixInverse, ug::FETISolver< TAlgebra >::prepare_conv_check(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::LocalSchurComplement< TAlgebra >::set_statistic_type(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::set_statistic_type(), UG_LOG, ug::FetiLayouts< TAlgebra >::vec_norm_on_identified_dual(), ug::FetiLayouts< TAlgebra >::vec_prod_on_identified_dual(), ug::FetiLayouts< TAlgebra >::vec_scale_add_on_dual(), ug::FetiLayouts< TAlgebra >::vec_scale_append_on_dual(), ug::FetiLayouts< TAlgebra >::vec_use_intra_sd_communication(), and ug::FetiLayouts< TAlgebra >::vec_use_std_communication().
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra > bool ug::FETISolver< TAlgebra >::apply_scaling_matrix (vector_type & s, const vector_type & v) inline
function which applies diagonal scaling matrix \(D_{\Delta}^{(i)}\) to a vector \(v\)
References ug::FetiLayouts< TAlgebra >::test_layouts().
Referenced by ug::FETISolver< TAlgebra >::apply_M_inverse().
template<typename TAlgebra > bool ug::FETISolver< TAlgebra >::compute_d (vector_type & d, const vector_type & f)
function which computes right hand side vector 'd' of the dual unknowns
This function computes \(d := B_{\Delta} \tilde{S}_{\Delta \Delta}^{-1} \tilde{f}_{\Delta}\) to a vector \(v\). \(v\) can be: (a) unknown vector of Lagrange multipliers, lambda, and (b) search direction 'p' in cg method.
Parameters
[in] f vector \(\tilde{f}_{\Delta}\)
[out] d right hand side vector \(d\) of reduced system
References ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply(), ug::FETISolver< TAlgebra >::apply_M_inverse(), ug::ComputeDifferenceOnDelta(), FETI_PROFILE_BEGIN, FETI_PROFILE_END, FETI_PROFILE_FUNC, ug::FetiLayouts< TAlgebra >::get_dual_master_layout(), ug::FetiLayouts< TAlgebra >::get_dual_nbr_master_layout(), ug::FetiLayouts< TAlgebra >::get_dual_nbr_slave_layout(), ug::FetiLayouts< TAlgebra >::get_dual_slave_layout(), ug::FETISolver< TAlgebra >::m_fetiLayouts, ug::FETISolver< TAlgebra >::m_PrimalSubassembledMatrixInverse, ug::PST_CONSISTENT, and UG_LOG.
Referenced by ug::FETISolver< TAlgebra >::apply_F(), and ug::FETISolver< TAlgebra >::apply_return_defect().
template<typename TAlgebra > bool ug::FETISolver< TAlgebra >::init (SmartPtr< MatrixOperator< matrix_type, vector_type > > A) virtual
initializes the solver for operator A
References pcl::AllProcsTrue(), ug::FETISolver< TAlgebra >::apply_return_defect(), ug::FetiLayouts< TAlgebra >::create_layouts(), ug::DebugWritingObject< TAlgebra >::debug_writer(), FETI_PROFILE_BEGIN, FETI_PROFILE_END, ug::LocalSchurComplement< TAlgebra >::init(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::init(), ug::FETISolver< TAlgebra >::m_fetiLayouts, ug::FETISolver< TAlgebra >::m_LocalSchurComplement, ug::FETISolver< TAlgebra >::m_pDDInfo, ug::FETISolver< TAlgebra >::m_pMatrix, ug::FETISolver< TAlgebra >::m_PrimalSubassembledMatrixInverse, ug::FETISolver< TAlgebra >::m_spCoarseProblemSolver, ug::FETISolver< TAlgebra >::m_spDirichletSolver, ug::FETISolver< TAlgebra >::m_spNeumannSolver, ug::FETISolver< TAlgebra >::m_spOperator, ug::PrimalSubassembledMatrixInverse< TAlgebra >::set_coarse_problem_solver(), ug::LocalSchurComplement< TAlgebra >::set_dirichlet_solver(), ug::LocalSchurComplement< TAlgebra >::set_feti_layouts(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::set_feti_layouts(), ug::LocalSchurComplement< TAlgebra >::set_matrix(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::set_neumann_solver(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::set_statistic_type(), SPNULL, and UG_LOG.
Referenced by ug::FETISolver< TAlgebra >::FETISolver().
template<typename TAlgebra > virtual const char* ug::FETISolver< TAlgebra >::name () const inline virtual
name of solver
Implements ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
template<typename TAlgebra > void ug::FETISolver< TAlgebra >::prepare_conv_check () inline protected
Referenced by ug::FETISolver< TAlgebra >::apply_return_defect().
template<typename TAlgebra > void ug::FETISolver< TAlgebra >::print_statistic_of_inner_solver (bool bPrintOnlyAverages) inline
prints some convergence statistic of inner solvers
References UG_LOG.
template<typename TAlgebra > void ug::FETISolver< TAlgebra >::set_coarse_problem_solver (SmartPtr< ILinearOperatorInverse< vector_type > > coarseProblemSolver) inline
sets the coarse problem solver
template<typename TAlgebra > void ug::FETISolver< TAlgebra >::set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter) inline virtual
set debug writer
Reimplemented from ug::DebugWritingObject< TAlgebra >.
References init(), and ug::VectorDebugWritingObject< TVector >::set_debug().
template<typename TAlgebra > void ug::FETISolver< TAlgebra >::set_dirichlet_solver (SmartPtr< ILinearOperatorInverse< vector_type > > dirichletSolver) inline
sets the Dirichlet solver
template<typename TAlgebra > void ug::FETISolver< TAlgebra >::set_domain_decomp_info (pcl::IDomainDecompositionInfo & ddInfo) inline
template<typename TAlgebra > void ug::FETISolver< TAlgebra >::set_neumann_solver (SmartPtr< ILinearOperatorInverse< vector_type > > neumannSolver) inline
sets the Neumann solver
template<typename TAlgebra > void ug::FETISolver< TAlgebra >::set_test_one_to_many_layouts (bool bTest) inline
template<typename TAlgebra > virtual bool ug::FETISolver< TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
template<typename TAlgebra > void ug::FETISolver< TAlgebra >::test_layouts (bool bPrint)
References ug::FETISolver< TAlgebra >::m_fetiLayouts, ug::FetiLayouts< TAlgebra >::test_layouts(), and UG_ALGEBRA_CPP_TEMPLATE_DEFINE_ALL.
Referenced by ug::FETISolver< TAlgebra >::apply_M_inverse().
template<typename TAlgebra > virtual void ug::FETISolver< TAlgebra >::write_debug (const vector_type & vec, const char * filename) inline protected virtual
writing debug output for a vector (if debug writer set)
Reimplemented from ug::VectorDebugWritingObject< TAlgebra::vector_type >.
References SPNULL.
Member Data Documentation
template<typename TAlgebra > FetiLayouts<algebra_type> ug::FETISolver< TAlgebra >::m_fetiLayouts protected
Referenced by ug::FETISolver< TAlgebra >::apply_F(), ug::FETISolver< TAlgebra >::apply_M_inverse(), ug::FETISolver< TAlgebra >::apply_return_defect(), ug::FETISolver< TAlgebra >::compute_d(), ug::FETISolver< TAlgebra >::init(), and ug::FETISolver< TAlgebra >::test_layouts().
template<typename TAlgebra > int ug::FETISolver< TAlgebra >::m_iterCnt protected
Referenced by ug::FETISolver< TAlgebra >::apply_return_defect().
template<typename TAlgebra > LocalSchurComplement<algebra_type> ug::FETISolver< TAlgebra >::m_LocalSchurComplement protected
Referenced by ug::FETISolver< TAlgebra >::apply_M_inverse(), ug::FETISolver< TAlgebra >::apply_return_defect(), and ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra > pcl::IDomainDecompositionInfo* ug::FETISolver< TAlgebra >::m_pDDInfo private
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra > matrix_type* ug::FETISolver< TAlgebra >::m_pMatrix protected
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra > PrimalSubassembledMatrixInverse<algebra_type> ug::FETISolver< TAlgebra >::m_PrimalSubassembledMatrixInverse protected
Referenced by ug::FETISolver< TAlgebra >::apply_F(), ug::FETISolver< TAlgebra >::apply_return_defect(), ug::FETISolver< TAlgebra >::compute_d(), and ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra > SmartPtr<ILinearOperatorInverse<vector_type> > ug::FETISolver< TAlgebra >::m_spCoarseProblemSolver protected
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra > SmartPtr<ILinearOperatorInverse<vector_type> > ug::FETISolver< TAlgebra >::m_spDirichletSolver protected
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra > SmartPtr<ILinearOperatorInverse<vector_type> > ug::FETISolver< TAlgebra >::m_spNeumannSolver protected
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra > SmartPtr<MatrixOperator<matrix_type,vector_type> > ug::FETISolver< TAlgebra >::m_spOperator protected
Referenced by ug::FETISolver< TAlgebra >::init().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/operator/linear_solver/feti.h
ugbase/lib_algebra/operator/linear_solver/feti.cpp