ug4: ug::IRefinementCallback Class Reference
ug::IRefinementCallback Class Reference abstract
lib_grid » algorithms » refinement
can be used to calculate new positions of vertices created during refinement.
#include <refinement_callbacks.h>
Public Member Functions
virtual int current_pos (number *coordsOut, Vertex *vrt, int maxCoords)=0
Gives access to the position of the current vertex.
virtual void flat_grid_vertex_encountered (Vertex *vrt)
callback for vertices in flat grids.
virtual void new_vertex (Vertex *vrt, Vertex *parent)=0
called when a new vertex was created from an old vertex.
virtual void new_vertex (Vertex *vrt, Edge *parent)=0
called when a new vertex was created from an old edge.
virtual void new_vertex (Vertex *vrt, Face *parent)=0
called when a new vertex was created from an old face.
virtual void new_vertex (Vertex *vrt, Volume *parent)=0
called when a new vertex was created from an old volume.
virtual ~IRefinementCallback ()
Protected Member Functions
template<class TAttachmentAccessor >
int current_pos_helper (number *coordsOut, Vertex *vrt, int maxCoords, TAttachmentAccessor &aaPos)
A helper implementation of current_pos available for derived classes.
Detailed Description
can be used to calculate new positions of vertices created during refinement.
Constructor & Destructor Documentation
virtual ug::IRefinementCallback::~IRefinementCallback () inline virtual
References new_vertex().
Member Function Documentation
virtual int ug::IRefinementCallback::current_pos (number * coordsOut, Vertex * vrt, int maxCoords) pure virtual
Gives access to the position of the current vertex.
The method returns the number of coordinates associated with the vertex and writes those coordinates to coordsOut. No more than maxCoords will be written to coordsOut. coordsOut thus has to be at least as big as maxCoords.
Implemented in ug::RefinementCallbackLinear< TAPosition >, ug::RefinementCallbackLinear< APosition >, ug::RefinementProjectionHandler< TAPosition >, ug::CylindricalFalloffProjector< TAPosition >, ug::SphericalFalloffProjector< TAPosition >, ug::CylinderProjector< TAPosition >, and ug::SphereProjector< TAPosition >.
Referenced by ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_3d(), flat_grid_vertex_encountered(), ug::GlobalMultiGridRefiner::perform_refinement(), ug::GlobalFracturedMediaRefiner::perform_refinement(), ug::Refine(), and ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex().
template<class TAttachmentAccessor > int ug::IRefinementCallback::current_pos_helper (number * coordsOut, Vertex * vrt, int maxCoords, TAttachmentAccessor & aaPos) protected
A helper implementation of current_pos available for derived classes.
References ug::RefinementCallbackLinear< TAPosition >::RefinementCallbackLinear().
Referenced by ug::SphereProjector< TAPosition >::current_pos(), ug::CylinderProjector< TAPosition >::current_pos(), ug::SphericalFalloffProjector< TAPosition >::current_pos(), ug::CylindricalFalloffProjector< TAPosition >::current_pos(), ug::RefinementProjectionHandler< TAPosition >::current_pos(), ug::RefinementCallbackLinear< TAPosition >::current_pos(), and flat_grid_vertex_encountered().
virtual void ug::IRefinementCallback::flat_grid_vertex_encountered (Vertex * vrt) inline virtual
callback for vertices in flat grids.
called for old vertices in flat grids which are used during refinement, since no new vertices will be created here. Calls new_vertex(vrt, vrt) by default.
Please note that this method won't be called during multigrid refinement.
Reimplemented in ug::RefinementProjectionHandler< TAPosition >.
References current_pos(), current_pos_helper(), and new_vertex().
Referenced by ug::Refine().
virtual void ug::IRefinementCallback::new_vertex (Vertex * vrt, Vertex * parent) pure virtual
called when a new vertex was created from an old vertex.
Implemented in ug::SubdivisionLoopProjector< TAPosition >, ug::RefinementCallbackLinear< TAPosition >, ug::RefinementCallbackLinear< APosition >, ug::SubdivisionLoopBoundaryProjector< TAPosition >, ug::CylindricalFalloffProjector< TAPosition >, ug::SphericalFalloffProjector< TAPosition >, ug::RefinementProjectionHandler< TAPosition >, ug::CylinderProjector< TAPosition >, and ug::SphereProjector< TAPosition >.
Referenced by ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_2d(), ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_3d(), flat_grid_vertex_encountered(), ug::GlobalMultiGridRefiner::perform_refinement(), ug::GlobalFracturedMediaRefiner::perform_refinement(), ug::HangingNodeRefiner_MultiGrid::pre_refine(), ug::Refine(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex(), and ~IRefinementCallback().
virtual void ug::IRefinementCallback::new_vertex (Vertex * vrt, Edge * parent) pure virtual
called when a new vertex was created from an old edge.
Implemented in ug::SubdivisionLoopProjector< TAPosition >, ug::RefinementCallbackLinear< TAPosition >, ug::RefinementCallbackLinear< APosition >, ug::RefinementCallbackEdgePlaneCut, ug::SubdivisionLoopBoundaryProjector< TAPosition >, ug::CylindricalFalloffProjector< TAPosition >, ug::RefinementProjectionHandler< TAPosition >, ug::SphericalFalloffProjector< TAPosition >, ug::FractalProjector, ug::CylinderProjector< TAPosition >, ug::SphereProjector< TAPosition >, and ug::RefinementCallback_IntersectCylinder.
virtual void ug::IRefinementCallback::new_vertex (Vertex * vrt, Face * parent) pure virtual
called when a new vertex was created from an old face.
Implemented in ug::SubdivisionLoopProjector< TAPosition >, ug::RefinementCallbackLinear< TAPosition >, ug::RefinementCallbackLinear< APosition >, ug::SubdivisionLoopBoundaryProjector< TAPosition >, ug::CylindricalFalloffProjector< TAPosition >, ug::RefinementProjectionHandler< TAPosition >, ug::SphericalFalloffProjector< TAPosition >, ug::FractalProjector, ug::CylinderProjector< TAPosition >, and ug::SphereProjector< TAPosition >.
virtual void ug::IRefinementCallback::new_vertex (Vertex * vrt, Volume * parent) pure virtual
called when a new vertex was created from an old volume.
Implemented in ug::SubdivisionLoopProjector< TAPosition >, ug::RefinementCallbackLinear< TAPosition >, ug::RefinementCallbackLinear< APosition >, ug::SubdivisionLoopBoundaryProjector< TAPosition >, ug::CylindricalFalloffProjector< TAPosition >, ug::RefinementProjectionHandler< TAPosition >, ug::SphericalFalloffProjector< TAPosition >, ug::CylinderProjector< TAPosition >, and ug::SphereProjector< TAPosition >.
The documentation for this class was generated from the following files:
ugbase/lib_grid/algorithms/refinement/refinement_callbacks.h
ugbase/lib_grid/algorithms/refinement/refinement_callbacks_impl.hpp