ug4: ug::ProcessHierarchy Class Reference
ug::ProcessHierarchy Class Reference
lib_grid » parallelization » parallel distribution
Defines how the different levels of a grid shall be distributed across the available processes.
#include <load_balancer.h>
Classes
struct HLevelInfo
Public Member Functions
void add_hierarchy_level (size_t gridLvl, size_t numProcsPerProc)
void add_partition_hint (int hlvl, const std::string &name, const Variant &value)
allows specification of partitioning hints per hierarchy level.
const std::vector< int > & cluster_procs (size_t hierarchyLevel) const
bool empty () const
pcl::ProcessCommunicator global_proc_com (size_t hierarchyLevel) const
size_t grid_base_level (size_t hierarchyLevel) const
size_t hierarchy_level_from_grid_level (size_t gridLevel) const
size_t num_global_procs_involved (size_t hierarchyLevel) const
size_t num_hierarchy_levels () const
bool partition_hint (Variant &valOut, int hlvl, const std::string &name) const
returns true if the queried partition hint exists and writes it value to 'valOut'
std::string to_string () const
Returns a string which describes the hierarchy layout.
~ProcessHierarchy ()
Static Public Member Functions
static SPProcessHierarchy create ()
Protected Types
typedef std::map< std::string, Variant > PartitionHintMap
Protected Member Functions
HLevelInfo & get_hlevel_info (size_t lvl)
const HLevelInfo & get_hlevel_info (size_t lvl) const
void init_cluster_procs (std::vector< int > &clusterProcs, size_t hlvl, size_t numProcsPerProc)
Private Attributes
std::vector< HLevelInfo > m_levels
Detailed Description
Defines how the different levels of a grid shall be distributed across the available processes.
Used by LoadBalancer and by different partitioners.
Member Typedef Documentation
typedef std::map<std::string, Variant> ug::ProcessHierarchy::PartitionHintMap protected
Constructor & Destructor Documentation
ug::ProcessHierarchy::~ProcessHierarchy ()
Referenced by create().
Member Function Documentation
void ug::ProcessHierarchy::add_hierarchy_level (size_t gridLvl, size_t numProcsPerProc)
References ug::ProcessHierarchy::HLevelInfo::clusterProcs, pcl::ProcessCommunicator::create_communicator(), ug::ProcessHierarchy::HLevelInfo::globalCom, ug::ProcessHierarchy::HLevelInfo::gridLvl, ug::ProcessHierarchy::HLevelInfo::numGlobalProcsInUse, and UG_THROW.
Referenced by create().
void ug::ProcessHierarchy::add_partition_hint (int hlvl, const std::string & name, const Variant & value)
allows specification of partitioning hints per hierarchy level.
Note
A hint is valid for all subsequent hierarchy levels until it is specified again with a different value.
Partitioners are free to ignore any partitioning hints. For a list of supported hints please check the documentation of the respective partitioner.
References ug::Variant::to_bool(), and UG_LOG.
Referenced by create().
const std::vector< int > & ug::ProcessHierarchy::cluster_procs (size_t hierarchyLevel) const
Contains only processes which are contained in the cluster of the given hierarchyLevel in which the local process is included.
Referenced by create(), and ug::Partitioner_DynamicBisection< TElem, dim >::partition().
static SPProcessHierarchy ug::ProcessHierarchy::create () inline static
References add_hierarchy_level(), add_partition_hint(), cluster_procs(), empty(), global_proc_com(), grid_base_level(), hierarchy_level_from_grid_level(), num_global_procs_involved(), num_hierarchy_levels(), partition_hint(), to_string(), and ~ProcessHierarchy().
Referenced by ug::CreateProcessHierarchy(), and ug::LoadBalancer::LoadBalancer().
bool ug::ProcessHierarchy::empty () const
Referenced by create().
HLevelInfo& ug::ProcessHierarchy::get_hlevel_info (size_t lvl) inline protected
References m_levels.
const HLevelInfo& ug::ProcessHierarchy::get_hlevel_info (size_t lvl) const inline protected
References ug::ProcessHierarchy::HLevelInfo::clusterProcs, init_cluster_procs(), and m_levels.
pcl::ProcessCommunicator ug::ProcessHierarchy::global_proc_com (size_t hierarchyLevel) const
Contains all processes which participate on the given hierarchy level, but only if the local process participates itself. If it doesn't, the returned communicator is empty.
Referenced by create(), ug::LoadBalancer::estimate_distribution_quality_impl(), and ug::Partitioner_DynamicBisection< TElem, dim >::partition().
size_t ug::ProcessHierarchy::grid_base_level (size_t hierarchyLevel) const
Referenced by create(), and ug::Partitioner_DynamicBisection< TElem, dim >::partition().
size_t ug::ProcessHierarchy::hierarchy_level_from_grid_level (size_t gridLevel) const
References UG_THROW.
Referenced by create(), and ug::LoadBalancer::estimate_distribution_quality_impl().
void ug::ProcessHierarchy::init_cluster_procs (std::vector< int > & clusterProcs, size_t hlvl, size_t numProcsPerProc) protected
References ug::ProcessHierarchy::HLevelInfo::numGlobalProcsInUse, pcl::ProcRank(), and UG_ASSERT.
Referenced by get_hlevel_info().
size_t ug::ProcessHierarchy::num_global_procs_involved (size_t hierarchyLevel) const
Referenced by create(), ug::LoadBalancer::estimate_distribution_quality_impl(), and ug::Partitioner_DynamicBisection< TElem, dim >::partition().
size_t ug::ProcessHierarchy::num_hierarchy_levels () const
Referenced by create(), and ug::Partitioner_DynamicBisection< TElem, dim >::partition().
bool ug::ProcessHierarchy::partition_hint (Variant & valOut, int hlvl, const std::string & name) const
returns true if the queried partition hint exists and writes it value to 'valOut'
The method searches hierarchy levels starting from the specified one down to level 0 and returns the first matching value.
References ug::Variant::to_bool(), and UG_LOG.
Referenced by create(), and ug::Partitioner_DynamicBisection< TElem, dim >::partition().
std::string ug::ProcessHierarchy::to_string () const
Returns a string which describes the hierarchy layout.
References ug::Table< T >::to_string().
Referenced by create().
Member Data Documentation
std::vector<HLevelInfo> ug::ProcessHierarchy::m_levels private
Referenced by get_hlevel_info().
The documentation for this class was generated from the following files:
ugbase/lib_grid/parallelization/load_balancer.h
ugbase/lib_grid/parallelization/load_balancer.cpp