ug4: ug::DirectionalOrdering< TAlgebra, TDomain, O_t > Class Template Reference
ug::DirectionalOrdering< TAlgebra, TDomain, O_t > Class Template Reference
Public Types
typedef IOrderingAlgorithm< TAlgebra, O_t > baseclass
typedef GridFunction< TDomain, TAlgebra > GridFunc_t
typedef TAlgebra::matrix_type M_t
typedef std::pair< MathVector< TDomain::dim >, size_t > Position_t
typedef std::pair< number, size_t > Scalar_t
typedef MathVector< TDomain::dim > small_vec_t
typedef SmartPtr< UserData< MathVector< TDomain::dim >, TDomain::dim > > TSpUserData
typedef TAlgebra::vector_type V_t
Public Types inherited from ug::IOrderingAlgorithm< TAlgebra, O_t >
typedef TAlgebra::matrix_type M_t
typedef TAlgebra::vector_type V_t
Public Member Functions
void check ()
SmartPtr< IOrderingAlgorithm< TAlgebra, O_t > > clone ()
void compute ()
DirectionalOrdering ()
DirectionalOrdering (const DirectionalOrdering< TAlgebra, TDomain, O_t > &parent)
clone constructor
void init (M_t *A)
void init (M_t *A, const O_t &inv_map)
void init (M_t *A, const V_t &, const O_t &inv_map)
void init (M_t *A, const V_t &V)
virtual const char * name () const
O_t & ordering ()
void set_direction (small_vec_t *dir)
Public Member Functions inherited from ug::IOrderingAlgorithm< TAlgebra, O_t >
virtual void init (M_t *, const std::vector< size_t > &)=0
virtual void init (M_t *, const V_t &, const std::vector< size_t > &)=0
IOrderingAlgorithm ()
virtual ~IOrderingAlgorithm ()
Private Attributes
small_vec_t * m_dir
std::vector< Position_t > m_vPositions
std::vector< Scalar_t > m_vScalars
O_t o
Member Typedef Documentation
baseclass
template<typename TAlgebra , typename TDomain , typename O_t > typedef IOrderingAlgorithm<TAlgebra, O_t> ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::baseclass
GridFunc_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef GridFunction<TDomain, TAlgebra> ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::GridFunc_t
M_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef TAlgebra::matrix_type ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::M_t
Position_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef std::pair<MathVector<TDomain::dim>, size_t> ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::Position_t
Scalar_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef std::pair<number, size_t> ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::Scalar_t
small_vec_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef MathVector<TDomain::dim> ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::small_vec_t
TSpUserData
template<typename TAlgebra , typename TDomain , typename O_t > typedef SmartPtr<UserData<MathVector<TDomain::dim>, TDomain::dim> > ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::TSpUserData
V_t
template<typename TAlgebra , typename TDomain , typename O_t > typedef TAlgebra::vector_type ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::V_t
Constructor & Destructor Documentation
DirectionalOrdering() [1/2]
template<typename TAlgebra , typename TDomain , typename O_t > ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::DirectionalOrdering () inline
DirectionalOrdering() [2/2]
template<typename TAlgebra , typename TDomain , typename O_t > ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::DirectionalOrdering (const DirectionalOrdering< TAlgebra, TDomain, O_t > & parent) inline
clone constructor
Member Function Documentation
check()
template<typename TAlgebra , typename TDomain , typename O_t > void ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::check () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::is_permutation(), ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::name(), ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::o, and UG_THROW.
Referenced by ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::compute().
clone()
template<typename TAlgebra , typename TDomain , typename O_t > SmartPtr<IOrderingAlgorithm<TAlgebra, O_t> > ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::clone () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References make_sp().
compute()
template<typename TAlgebra , typename TDomain , typename O_t > void ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::compute () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::check(), ug::CompareScalar(), ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::m_vPositions, ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::m_vScalars, and ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::o.
init() [1/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::init (M_t * A) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::name(), and UG_THROW.
init() [2/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::init (M_t * A, const O_t & inv_map) inline
References ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::name(), and UG_THROW.
init() [3/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::init (M_t * A, const V_t & , const O_t & inv_map) inline
References ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::name(), and UG_THROW.
init() [4/4]
template<typename TAlgebra , typename TDomain , typename O_t > void ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::init (M_t * A, const V_t & V) inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::GridFunction< TDomain, TAlgebra >::domain(), ug::ExtractPositions(), ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::m_dir, ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::m_vPositions, ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::name(), ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::o, UG_LOG, and UG_THROW.
name()
template<typename TAlgebra , typename TDomain , typename O_t > virtual const char* ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::name () const inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
Referenced by ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::check(), and ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::init().
ordering()
template<typename TAlgebra , typename TDomain , typename O_t > O_t& ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::ordering () inline virtual
Implements ug::IOrderingAlgorithm< TAlgebra, O_t >.
References ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::o.
set_direction()
template<typename TAlgebra , typename TDomain , typename O_t > void ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::set_direction (small_vec_t * dir) inline
References ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::m_dir.
Member Data Documentation
m_dir
template<typename TAlgebra , typename TDomain , typename O_t > small_vec_t* ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::m_dir private
Referenced by ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::init(), and ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::set_direction().
m_vPositions
template<typename TAlgebra , typename TDomain , typename O_t > std::vector<Position_t> ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::m_vPositions private
Referenced by ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::compute(), and ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::init().
m_vScalars
template<typename TAlgebra , typename TDomain , typename O_t > std::vector<Scalar_t> ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::m_vScalars private
Referenced by ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::compute().
o
template<typename TAlgebra , typename TDomain , typename O_t > O_t ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::o private
Referenced by ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::check(), ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::compute(), ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::init(), and ug::DirectionalOrdering< TAlgebra, TDomain, O_t >::ordering().
The documentation for this class was generated from the following file:
ugbase/lib_disc/ordering_strategies/algorithms/directional_ordering.cpp