ug4: ug::VectorDebugWritingObject< TVector > Class Template Reference
ug::VectorDebugWritingObject< TVector > Class Template Reference
#include <debug_writer.h>
Public Types
typedef TVector vector_type
type of vector
Public Member Functions
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Member Typedef Documentation
vector_type
template<typename TVector > typedef TVector ug::VectorDebugWritingObject< TVector >::vector_type
type of vector
Constructor & Destructor Documentation
VectorDebugWritingObject() [1/2]
template<typename TVector > ug::VectorDebugWritingObject< TVector >::VectorDebugWritingObject () inline
VectorDebugWritingObject() [2/2]
template<typename TVector > ug::VectorDebugWritingObject< TVector >::VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter) inline
~VectorDebugWritingObject()
template<typename TVector > virtual ug::VectorDebugWritingObject< TVector >::~VectorDebugWritingObject () inline virtual
virtual destructor
Member Function Documentation
enter_vector_debug_writer_section() [1/2]
template<typename TVector > void ug::VectorDebugWritingObject< TVector >::enter_vector_debug_writer_section (const char * secDir) inline protected
enters a debugging section
References ug::VectorDebugWritingObject< TVector >::m_spVectorDebugWriter.
enter_vector_debug_writer_section() [2/2]
template<typename TVector > void ug::VectorDebugWritingObject< TVector >::enter_vector_debug_writer_section (std::string secDir) inline protected
enters a debugging section
Referenced by ug::CG< TVector >::enter_precond_debug_section(), ug::LinearSolver< TVector >::enter_precond_debug_section(), and ug::BiCGStab< TVector >::enter_precond_debug_section().
leave_vector_debug_writer_section()
template<typename TVector > void ug::VectorDebugWritingObject< TVector >::leave_vector_debug_writer_section () inline protected
leaves a debugging section
References ug::VectorDebugWritingObject< TVector >::m_spVectorDebugWriter.
Referenced by ug::BiCGStab< TVector >::apply_return_defect(), ug::CG< TVector >::apply_return_defect(), and ug::LinearSolver< TVector >::apply_return_defect().
print_debugger_message() [1/2]
template<typename TVector > void ug::VectorDebugWritingObject< TVector >::print_debugger_message (const char * msg) inline protected
prints a debugger message (listing all the sections)
References ug::VectorDebugWritingObject< TVector >::m_spVectorDebugWriter.
print_debugger_message() [2/2]
template<typename TVector > void ug::VectorDebugWritingObject< TVector >::print_debugger_message (std::string msg) inline protected
prints a debugger message (listing all the sections)
set_debug()
template<typename TVector > virtual void ug::VectorDebugWritingObject< TVector >::set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter) inline virtual
set debug writer
References ug::VectorDebugWritingObject< TVector >::m_spVectorDebugWriter.
Referenced by ug::DebugWritingObject< TAlgebra >::set_debug(), and ug::FETISolver< TAlgebra >::set_debug().
vector_debug_writer() [1/2]
template<typename TVector > SmartPtr<IVectorDebugWriter<vector_type> > ug::VectorDebugWritingObject< TVector >::vector_debug_writer () inline
returns the debug writer
References ug::VectorDebugWritingObject< TVector >::m_spVectorDebugWriter.
Referenced by ug::DebugIterator< TAlgebra >::clone().
vector_debug_writer() [2/2]
template<typename TVector > ConstSmartPtr<IVectorDebugWriter<vector_type> > ug::VectorDebugWritingObject< TVector >::vector_debug_writer () const inline
References ug::VectorDebugWritingObject< TVector >::m_spVectorDebugWriter.
vector_debug_writer_valid()
template<typename TVector > bool ug::VectorDebugWritingObject< TVector >::vector_debug_writer_valid () const inline
returns true if the debug writer is set
References ug::VectorDebugWritingObject< TVector >::m_spVectorDebugWriter.
Referenced by ug::LinearSolver< TVector >::apply_return_defect(), ug::CG< TVector >::enter_precond_debug_section(), ug::LinearSolver< TVector >::enter_precond_debug_section(), ug::BiCGStab< TVector >::enter_precond_debug_section(), ug::LinearSolver< TVector >::write_debugXCD(), ug::CG< TVector >::write_debugXR(), and ug::BiCGStab< TVector >::write_debugXR().
write_debug() [1/2]
template<typename TVector > void ug::VectorDebugWritingObject< TVector >::write_debug (const vector_type & vec, const char * filename) inline
writing debug output for a vector (if debug writer set)
Referenced by ug::AutoLinearSolver< TVector >::apply_return_defect(), ug::LinearSolver< TVector >::apply_return_defect(), ug::LinearSolver< TVector >::write_debugXCD(), ug::CG< TVector >::write_debugXR(), and ug::BiCGStab< TVector >::write_debugXR().
write_debug() [2/2]
template<typename TVector > virtual void ug::VectorDebugWritingObject< TVector >::write_debug (const vector_type & vec, std::string name) inline protected virtual
writing debug output for a vector (if debug writer set)
Reimplemented in ug::NewtonSolver< TAlgebra >.
References ug::VectorDebugWritingObject< TVector >::m_spVectorDebugWriter, name, PROFILE_FUNC_GROUP, and UG_THROW.
Member Data Documentation
m_spVectorDebugWriter
template<typename TVector > SmartPtr<IVectorDebugWriter<vector_type> > ug::VectorDebugWritingObject< TVector >::m_spVectorDebugWriter protected
Debug Writer.
Referenced by ug::VectorDebugWritingObject< TVector >::enter_vector_debug_writer_section(), ug::VectorDebugWritingObject< TVector >::leave_vector_debug_writer_section(), ug::VectorDebugWritingObject< TVector >::print_debugger_message(), ug::VectorDebugWritingObject< TVector >::set_debug(), ug::VectorDebugWritingObject< TVector >::vector_debug_writer(), ug::VectorDebugWritingObject< TVector >::vector_debug_writer_valid(), and ug::VectorDebugWritingObject< TVector >::write_debug().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/debug_writer.h