ug4: ug::DataEvaluator< TDomain > Class Template Reference
ug::DataEvaluator< TDomain > Class Template Reference
helper class to evaluate data evaluation for local contributions during assembling
#include <data_evaluator.h>
Public Member Functions
void add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], ProcessType type=PT_ALL)
compute local stiffness defect for all IElemDiscs
void add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], ProcessType type=PT_ALL)
compute local stiffness defect for all IElemDiscs explicit
void add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], ProcessType type=PT_ALL)
compute local mass defect for all IElemDiscs
void add_jac_A_elem (LocalMatrix &A, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], ProcessType type=PT_ALL)
compute local stiffness matrix for all IElemDiscs
void add_jac_M_elem (LocalMatrix &M, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], ProcessType type=PT_ALL)
compute local mass matrix for all IElemDiscs
void add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[], ProcessType type=PT_ALL)
compute local rhs for all IElemDiscs
void compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const LocalIndices &ind, const number scaleMass=(number) 1.0, const number scaleStiff=(number) 1.0)
compute contributions of the local error indicators in one element for all IElemDiscs
void compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const LocalIndices &ind, const number scaleMass=(number) 1.0, const number scaleStiff=(number) 1.0)
compute contributions of the local error indicators in one element for all IElemDiscs
void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const LocalIndices &ind, const number scaleMass=(number) 1.0, const number scaleStiff=(number) 1.0)
compute contributions of the local error indicators in one element for all IElemDiscs
DataEvaluator (int discPart, const std::vector< IElemDisc< TDomain > * > &vElemDisc, ConstSmartPtr< FunctionPattern > fctPat, const bool bNonRegularGrid, LocalVectorTimeSeries *locTimeSeries=NULL, const std::vector< number > *vScaleMass=NULL, const std::vector< number > *vScaleStiff=NULL)
sets the elem discs to evaluate
void finish_elem_loop ()
finishes the element loop for all IElemDiscs
void finish_err_est_elem_loop ()
finishes the error estimator element loop for all IElemDiscs
void finish_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
finishes all time-dependent IElemDiscs
void finish_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
finishes the elements of all time-dependent IElemDiscs
void prepare_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[], const LocalIndices &ind, bool bDeriv=false)
prepares the element for all IElemDiscs
void prepare_elem_loop (const ReferenceObjectID id, int si)
prepares the element loop for all IElemDiscs
void prepare_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const LocalIndices &ind, bool bDeriv=false)
prepares the element for all IElemDiscs
void prepare_err_est_elem_loop (const ReferenceObjectID id, int si)
prepares the element loop for all IElemDiscs for the computation of the error estimator
void prepare_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
prepares all time-dependent IElemDiscs
void prepare_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
prepares the elements of all time-dependent IElemDiscs
void set_time_point (const size_t timePoint)
sets the time point for data evaluation
bool time_series_needed () const
returns if local time series is really needed for assembling
bool use_hanging () const
returns if one of the element discs needs hanging dofs
Static Public Attributes
static const int dim = TDomain::dim
world dimension
Protected Member Functions
void add_data_to_eval_data (std::vector< SmartPtr< ICplUserData< dim > > > &vEvalData, std::vector< SmartPtr< ICplUserData< dim > > > &vTryingToAdd)
tries to add the last entry of vTryingToAdd to the eval data
void clear_extracted_data_and_mappings ()
clears imports and user data and mappings betweem commonFctGrp and local
void clear_positions_in_user_data ()
clears all requested positions in user data
void extract_imports_and_userdata (int subsetIndex, int discPart)
extracts imports and userdata from IElemDiscs
Protected Attributes
bool m_bNeedLocTimeSeries
flag indicating if any elem disc needs local time series
bool m_bUseHanging
flag if hanging nodes are used
int m_discPart
disc part needed (MASS and/or STIFF and/or RHS)
LocalVectorTimeSeries * m_pLocTimeSeries
local time series (non-const since mapping may change)
ConstSmartPtr< FunctionPattern > m_spFctPattern
underlying function pattern
std::vector< IElemDisc< TDomain > * > m_vElemDisc [MAX_PROCESS]
elem disc data
std::vector< IDataImport< dim > * > m_vImport [MAX_PROCESS][MAX_PART]
imports that must be evaluated
std::vector< SmartPtr< ICplUserData< dim > > > m_vConstData
std::vector< SmartPtr< ICplUserData< dim > > > m_vPosData
std::vector< SmartPtr< ICplUserData< dim > > > m_vDependentData
Detailed Description
template<typename TDomain>
class ug::DataEvaluator< TDomain >
helper class to evaluate data evaluation for local contributions during assembling
This class is a helper class to facilitate the correct evaluation of data during the assembling process. For a given set of IElemDisc this class prepares the assembling, checks for DataImport/DataExports and schedules the evaluation of the data in the correct order. In addition the coupling contributions due to Import/Exports are computed by this class and can be added to the local jacobian/defect.
Constructor & Destructor Documentation
template<typename TDomain > ug::DataEvaluator< TDomain >::DataEvaluator (int discPart, const std::vector< IElemDisc< TDomain > * > & vElemDisc, ConstSmartPtr< FunctionPattern > fctPat, const bool bNonRegularGrid, LocalVectorTimeSeries * locTimeSeries = NULL, const std::vector< number > * vScaleMass = NULL, const std::vector< number > * vScaleStiff = NULL)
sets the elem discs to evaluate
References ug::DataEvaluator< TDomain >::add_data_to_eval_data(), ug::IElemDisc< TDomain >::check_setup(), ug::IElemDisc< TDomain >::is_time_dependent(), ug::IElemDisc< TDomain >::local_time_series_needed(), ug::DataEvaluator< TDomain >::m_bNeedLocTimeSeries, ug::DataEvaluator< TDomain >::m_bUseHanging, ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_pLocTimeSeries, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::PT_ALL, ug::PT_INSTATIONARY, ug::PT_STATIONARY, ug::IElemDisc< TDomain >::set_time_dependent(), ug::IElemDisc< TDomain >::set_time_independent(), and ug::IElemDisc< TDomain >::use_hanging().
Member Function Documentation
template<typename TDomain > void ug::DataEvaluator< TDomain >::add_data_to_eval_data (std::vector< SmartPtr< ICplUserData< dim > > > & vEvalData, std::vector< SmartPtr< ICplUserData< dim > > > & vTryingToAdd) protected
tries to add the last entry of vTryingToAdd to the eval data
References ug::find(), and UG_THROW.
Referenced by ug::DataEvaluator< TDomain >::DataEvaluator(), ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::add_def_A_elem (LocalVector & d, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], ProcessType type = PT_ALL)
compute local stiffness defect for all IElemDiscs
References ug::DataEvaluator< TDomain >::add_def_A_expl_elem(), ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::STIFF, UG_ASSERT, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::add_jac_M_elem(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::add_def_A_expl_elem (LocalVector & d, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], ProcessType type = PT_ALL)
compute local stiffness defect for all IElemDiscs explicit
References ug::DataEvaluator< TDomain >::add_def_M_elem(), ug::EXPL, ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_vElemDisc, UG_ASSERT, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::add_def_A_elem(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::add_def_M_elem (LocalVector & d, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], ProcessType type = PT_ALL)
compute local mass defect for all IElemDiscs
References ug::DataEvaluator< TDomain >::add_rhs_elem(), ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::MASS, UG_ASSERT, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::add_def_A_expl_elem(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::add_jac_A_elem (LocalMatrix & A, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], ProcessType type = PT_ALL)
compute local stiffness matrix for all IElemDiscs
References ug::DataEvaluator< TDomain >::add_jac_M_elem(), ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::m_vImport, ug::RHS, ug::STIFF, UG_ASSERT, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::finish_timestep_elem(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::add_jac_M_elem (LocalMatrix & M, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], ProcessType type = PT_ALL)
compute local mass matrix for all IElemDiscs
References ug::DataEvaluator< TDomain >::add_def_A_elem(), ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::m_vImport, ug::MASS, UG_ASSERT, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::add_jac_A_elem(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::add_rhs_elem (LocalVector & rhs, GridObject * elem, const MathVector< dim > vCornerCoords[], ProcessType type = PT_ALL)
compute local rhs for all IElemDiscs
References ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::prepare_err_est_elem_loop(), ug::RHS, UG_ASSERT, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::add_def_M_elem(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::clear_extracted_data_and_mappings () protected
clears imports and user data and mappings betweem commonFctGrp and local
References ug::DataEvaluator< TDomain >::m_vConstData, ug::DataEvaluator< TDomain >::m_vDependentData, ug::DataEvaluator< TDomain >::m_vImport, ug::DataEvaluator< TDomain >::m_vPosData, ug::MASS, ug::MAX_PROCESS, ug::RHS, and ug::STIFF.
Referenced by ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::clear_positions_in_user_data () protected
clears all requested positions in user data
References ug::DataEvaluator< TDomain >::m_vConstData, ug::DataEvaluator< TDomain >::m_vDependentData, and ug::DataEvaluator< TDomain >::m_vPosData.
Referenced by ug::DataEvaluator< TDomain >::finish_elem_loop(), ug::DataEvaluator< TDomain >::finish_err_est_elem_loop(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::compute_err_est_A_elem (LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const LocalIndices & ind, const number scaleMass = (number) 1.0, const number scaleStiff = (number) 1.0)
compute contributions of the local error indicators in one element for all IElemDiscs
References ug::DataEvaluator< TDomain >::compute_err_est_M_elem(), ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::PT_ALL, ug::STIFF, UG_ASSERT, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::prepare_err_est_elem(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::compute_err_est_M_elem (LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const LocalIndices & ind, const number scaleMass = (number) 1.0, const number scaleStiff = (number) 1.0)
compute contributions of the local error indicators in one element for all IElemDiscs
References ug::DataEvaluator< TDomain >::compute_err_est_rhs_elem(), ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::MASS, ug::PT_ALL, UG_ASSERT, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::compute_err_est_A_elem(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::compute_err_est_rhs_elem (GridObject * elem, const MathVector< dim > vCornerCoords[], const LocalIndices & ind, const number scaleMass = (number) 1.0, const number scaleStiff = (number) 1.0)
compute contributions of the local error indicators in one element for all IElemDiscs
References ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::PT_ALL, ug::RHS, UG_ASSERT, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::compute_err_est_M_elem(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::extract_imports_and_userdata (int subsetIndex, int discPart) protected
extracts imports and userdata from IElemDiscs
References ug::DataEvaluator< TDomain >::add_data_to_eval_data(), ug::DataEvaluator< TDomain >::clear_extracted_data_and_mappings(), ug::IDataImport< dim >::data(), ug::IDataImport< dim >::data_given(), ug::IElemDisc< TDomain >::get_import(), ug::IElemDisc< TDomain >::is_time_dependent(), ug::DataEvaluator< TDomain >::m_pLocTimeSeries, ug::DataEvaluator< TDomain >::m_spFctPattern, ug::DataEvaluator< TDomain >::m_vConstData, ug::DataEvaluator< TDomain >::m_vDependentData, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::m_vImport, ug::DataEvaluator< TDomain >::m_vPosData, ug::MASS, ug::IElemDisc< TDomain >::num_imports(), ug::IDataImport< dim >::part(), ug::PT_ALL, ug::PT_INSTATIONARY, ug::PT_STATIONARY, ug::LocalVectorTimeSeries::times(), UG_CATCH_THROW, UG_THROW, and ug::IDataImport< dim >::zero_derivative().
Referenced by ug::DataEvaluator< TDomain >::prepare_elem_loop(), ug::DataEvaluator< TDomain >::prepare_err_est_elem_loop(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::finish_elem_loop ()
finishes the element loop for all IElemDiscs
References ug::DataEvaluator< TDomain >::clear_positions_in_user_data(), ug::DataEvaluator< TDomain >::m_vElemDisc, ug::PT_ALL, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::finish_err_est_elem_loop ()
finishes the error estimator element loop for all IElemDiscs
References ug::DataEvaluator< TDomain >::clear_positions_in_user_data(), ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::prepare_err_est_elem(), ug::PT_ALL, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::finish_timestep (const number time, VectorProxyBase * u, size_t algebra_id)
finishes all time-dependent IElemDiscs
References ug::DataEvaluator< TDomain >::finish_timestep_elem(), ug::DataEvaluator< TDomain >::m_vElemDisc, ug::PT_ALL, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::finish_timestep_elem (const number time, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
finishes the elements of all time-dependent IElemDiscs
References ug::DataEvaluator< TDomain >::add_jac_A_elem(), ug::DataEvaluator< TDomain >::m_vElemDisc, ug::PT_ALL, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::finish_timestep(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::prepare_elem (LocalVector & u, GridObject * elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[], const LocalIndices & ind, bool bDeriv = false)
prepares the element for all IElemDiscs
References ug::LocalVector::access_by_map(), ug::DID_DATA_EVALUATOR, ug::DataEvaluator< TDomain >::m_pLocTimeSeries, ug::DataEvaluator< TDomain >::m_vDependentData, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::m_vImport, ug::DataEvaluator< TDomain >::m_vPosData, ug::MASS, ug::PT_ALL, ug::RHS, ug::STIFF, ug::DataEvaluator< TDomain >::time_series_needed(), UG_CATCH_THROW, and UG_DLOG.
Referenced by ug::DataEvaluator< TDomain >::prepare_timestep_elem(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::prepare_elem_loop (const ReferenceObjectID id, int si)
prepares the element loop for all IElemDiscs
References ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_vConstData, ug::DataEvaluator< TDomain >::m_vDependentData, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::m_vImport, ug::MASS, ug::PT_ALL, ug::RHS, ug::STIFF, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::set_time_point(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::prepare_err_est_elem (LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const LocalIndices & ind, bool bDeriv = false)
prepares the element for all IElemDiscs
References ug::LocalVector::access_by_map(), ug::DataEvaluator< TDomain >::compute_err_est_A_elem(), ug::DataEvaluator< TDomain >::m_vDependentData, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::m_vPosData, ug::PT_ALL, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::finish_err_est_elem_loop(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::prepare_err_est_elem_loop (const ReferenceObjectID id, int si)
prepares the element loop for all IElemDiscs for the computation of the error estimator
References ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), ug::DataEvaluator< TDomain >::m_discPart, ug::DataEvaluator< TDomain >::m_vConstData, ug::DataEvaluator< TDomain >::m_vDependentData, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::m_vImport, ug::MASS, ug::PT_ALL, ug::RHS, ug::STIFF, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::add_rhs_elem(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::prepare_timestep (const number time, VectorProxyBase * u, size_t algebra_id)
prepares all time-dependent IElemDiscs
References ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::prepare_timestep_elem(), ug::PT_ALL, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::prepare_timestep_elem (const number time, LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
prepares the elements of all time-dependent IElemDiscs
References ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::prepare_elem(), ug::PT_ALL, and UG_CATCH_THROW.
Referenced by ug::DataEvaluator< TDomain >::prepare_timestep(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain > void ug::DataEvaluator< TDomain >::set_time_point (const size_t timePoint)
sets the time point for data evaluation
References ug::DataEvaluator< TDomain >::m_vDependentData, ug::DataEvaluator< TDomain >::m_vElemDisc, ug::DataEvaluator< TDomain >::m_vPosData, ug::DataEvaluator< TDomain >::prepare_elem_loop(), and ug::PT_ALL.
template<typename TDomain> bool ug::DataEvaluator< TDomain >::time_series_needed () const inline
returns if local time series is really needed for assembling
References ug::DataEvaluator< TDomain >::m_bNeedLocTimeSeries.
Referenced by ug::DataEvaluator< TDomain >::prepare_elem().
template<typename TDomain> bool ug::DataEvaluator< TDomain >::use_hanging () const inline
returns if one of the element discs needs hanging dofs
References ug::DataEvaluator< TDomain >::add_data_to_eval_data(), ug::DataEvaluator< TDomain >::add_def_A_elem(), ug::DataEvaluator< TDomain >::add_def_A_expl_elem(), ug::DataEvaluator< TDomain >::add_def_M_elem(), ug::DataEvaluator< TDomain >::add_jac_A_elem(), ug::DataEvaluator< TDomain >::add_jac_M_elem(), ug::DataEvaluator< TDomain >::add_rhs_elem(), ug::DataEvaluator< TDomain >::clear_extracted_data_and_mappings(), ug::DataEvaluator< TDomain >::clear_positions_in_user_data(), ug::DataEvaluator< TDomain >::compute_err_est_A_elem(), ug::DataEvaluator< TDomain >::compute_err_est_M_elem(), ug::DataEvaluator< TDomain >::compute_err_est_rhs_elem(), ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), ug::DataEvaluator< TDomain >::finish_elem_loop(), ug::DataEvaluator< TDomain >::finish_err_est_elem_loop(), ug::DataEvaluator< TDomain >::finish_timestep(), ug::DataEvaluator< TDomain >::finish_timestep_elem(), ug::DataEvaluator< TDomain >::m_bUseHanging, ug::DataEvaluator< TDomain >::prepare_elem(), ug::DataEvaluator< TDomain >::prepare_elem_loop(), ug::DataEvaluator< TDomain >::prepare_err_est_elem(), ug::DataEvaluator< TDomain >::prepare_err_est_elem_loop(), ug::DataEvaluator< TDomain >::prepare_timestep(), ug::DataEvaluator< TDomain >::prepare_timestep_elem(), and ug::PT_ALL.
Member Data Documentation
template<typename TDomain> const int ug::DataEvaluator< TDomain >::dim = TDomain::dim static
world dimension
template<typename TDomain> bool ug::DataEvaluator< TDomain >::m_bNeedLocTimeSeries protected
flag indicating if any elem disc needs local time series
Referenced by ug::DataEvaluator< TDomain >::DataEvaluator(), and ug::DataEvaluator< TDomain >::time_series_needed().
template<typename TDomain> bool ug::DataEvaluator< TDomain >::m_bUseHanging protected
flag if hanging nodes are used
Referenced by ug::DataEvaluator< TDomain >::DataEvaluator(), and ug::DataEvaluator< TDomain >::use_hanging().
template<typename TDomain> int ug::DataEvaluator< TDomain >::m_discPart protected
disc part needed (MASS and/or STIFF and/or RHS)
Referenced by ug::DataEvaluator< TDomain >::add_def_A_elem(), ug::DataEvaluator< TDomain >::add_def_A_expl_elem(), ug::DataEvaluator< TDomain >::add_def_M_elem(), ug::DataEvaluator< TDomain >::add_jac_A_elem(), ug::DataEvaluator< TDomain >::add_jac_M_elem(), ug::DataEvaluator< TDomain >::add_rhs_elem(), ug::DataEvaluator< TDomain >::compute_err_est_A_elem(), ug::DataEvaluator< TDomain >::compute_err_est_M_elem(), ug::DataEvaluator< TDomain >::compute_err_est_rhs_elem(), ug::DataEvaluator< TDomain >::DataEvaluator(), ug::DataEvaluator< TDomain >::prepare_elem_loop(), and ug::DataEvaluator< TDomain >::prepare_err_est_elem_loop().
template<typename TDomain> LocalVectorTimeSeries* ug::DataEvaluator< TDomain >::m_pLocTimeSeries protected
local time series (non-const since mapping may change)
Referenced by ug::DataEvaluator< TDomain >::DataEvaluator(), ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), and ug::DataEvaluator< TDomain >::prepare_elem().
template<typename TDomain> ConstSmartPtr<FunctionPattern> ug::DataEvaluator< TDomain >::m_spFctPattern protected
underlying function pattern
Referenced by ug::DataEvaluator< TDomain >::extract_imports_and_userdata().
template<typename TDomain> std::vector<SmartPtr<ICplUserData<dim> > > ug::DataEvaluator< TDomain >::m_vConstData protected
user data that must be evaluated
Referenced by ug::DataEvaluator< TDomain >::clear_extracted_data_and_mappings(), ug::DataEvaluator< TDomain >::clear_positions_in_user_data(), ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), ug::DataEvaluator< TDomain >::prepare_elem_loop(), and ug::DataEvaluator< TDomain >::prepare_err_est_elem_loop().
template<typename TDomain> std::vector<SmartPtr<ICplUserData<dim> > > ug::DataEvaluator< TDomain >::m_vDependentData protected
user data that must be evaluated
Referenced by ug::DataEvaluator< TDomain >::clear_extracted_data_and_mappings(), ug::DataEvaluator< TDomain >::clear_positions_in_user_data(), ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), ug::DataEvaluator< TDomain >::prepare_elem(), ug::DataEvaluator< TDomain >::prepare_elem_loop(), ug::DataEvaluator< TDomain >::prepare_err_est_elem(), ug::DataEvaluator< TDomain >::prepare_err_est_elem_loop(), and ug::DataEvaluator< TDomain >::set_time_point().
template<typename TDomain> std::vector<IElemDisc<TDomain>*> ug::DataEvaluator< TDomain >::m_vElemDisc[MAX_PROCESS] protected
elem disc data
Referenced by ug::DataEvaluator< TDomain >::add_def_A_elem(), ug::DataEvaluator< TDomain >::add_def_A_expl_elem(), ug::DataEvaluator< TDomain >::add_def_M_elem(), ug::DataEvaluator< TDomain >::add_jac_A_elem(), ug::DataEvaluator< TDomain >::add_jac_M_elem(), ug::DataEvaluator< TDomain >::add_rhs_elem(), ug::DataEvaluator< TDomain >::compute_err_est_A_elem(), ug::DataEvaluator< TDomain >::compute_err_est_M_elem(), ug::DataEvaluator< TDomain >::compute_err_est_rhs_elem(), ug::DataEvaluator< TDomain >::DataEvaluator(), ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), ug::DataEvaluator< TDomain >::finish_elem_loop(), ug::DataEvaluator< TDomain >::finish_err_est_elem_loop(), ug::DataEvaluator< TDomain >::finish_timestep(), ug::DataEvaluator< TDomain >::finish_timestep_elem(), ug::DataEvaluator< TDomain >::prepare_elem(), ug::DataEvaluator< TDomain >::prepare_elem_loop(), ug::DataEvaluator< TDomain >::prepare_err_est_elem(), ug::DataEvaluator< TDomain >::prepare_err_est_elem_loop(), ug::DataEvaluator< TDomain >::prepare_timestep(), ug::DataEvaluator< TDomain >::prepare_timestep_elem(), and ug::DataEvaluator< TDomain >::set_time_point().
template<typename TDomain> std::vector<IDataImport<dim>*> ug::DataEvaluator< TDomain >::m_vImport[MAX_PROCESS][MAX_PART] protected
imports that must be evaluated
Referenced by ug::DataEvaluator< TDomain >::add_jac_A_elem(), ug::DataEvaluator< TDomain >::add_jac_M_elem(), ug::DataEvaluator< TDomain >::clear_extracted_data_and_mappings(), ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), ug::DataEvaluator< TDomain >::prepare_elem(), ug::DataEvaluator< TDomain >::prepare_elem_loop(), and ug::DataEvaluator< TDomain >::prepare_err_est_elem_loop().
template<typename TDomain> std::vector<SmartPtr<ICplUserData<dim> > > ug::DataEvaluator< TDomain >::m_vPosData protected
user data that must be evaluated
Referenced by ug::DataEvaluator< TDomain >::clear_extracted_data_and_mappings(), ug::DataEvaluator< TDomain >::clear_positions_in_user_data(), ug::DataEvaluator< TDomain >::extract_imports_and_userdata(), ug::DataEvaluator< TDomain >::prepare_elem(), ug::DataEvaluator< TDomain >::prepare_err_est_elem(), and ug::DataEvaluator< TDomain >::set_time_point().
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/user_data/data_evaluator.h
ugbase/lib_disc/spatial_disc/user_data/data_evaluator.cpp