ug4: ug::AgglomeratingSolver< TAlgebra > Class Template Reference
ug::AgglomeratingSolver< TAlgebra > Class Template Reference
#include <agglomerating_solver.h>
Public Types
typedef TAlgebra algebra_type
typedef AgglomeratingBase< IMatrixOperatorInverse< matrix_type, vector_type >, algebra_type > base_type
Base type.
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::AgglomeratingBase< IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >, TAlgebra >
typedef TAlgebra algebra_type
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
Public Types inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::ILinearIterator< X, Y >
typedef Y codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Member Functions
AgglomeratingSolver (SmartPtr< ILinearOperatorInverse< vector_type, vector_type > > linOpInverse)
virtual bool apply_agglomerated (vector_type &x, const vector_type &b)
virtual std::string config_string () const
returns information about configuration parameters
virtual bool init (SmartPtr< ILinearOperator< vector_type > > A)
virtual bool init (SmartPtr< ILinearOperator< vector_type > > A, const vector_type &u)
virtual bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
virtual bool init_agglomerated (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
virtual const char * name () const
returns the name of the operator inverse
virtual bool supports_parallel () const
returns if parallel solving is supported
virtual ~AgglomeratingSolver ()
Public Member Functions inherited from ug::AgglomeratingBase< IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >, TAlgebra >
virtual bool apply (vector_type &x, const vector_type &b)
virtual bool apply_return_defect (vector_type &u, vector_type &f)
virtual bool apply_update_defect (vector_type &u, vector_type &f)
virtual bool base_init (SmartPtr< ILinearOperator< vector_type > > A)
bool base_init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
Preprocess routine.
void broadcast_vector_from_one (vector_type &x, const vector_type &collectedX, ParallelStorageType type)
bool empty ()
void gather_vector_on_one (vector_type &collectedB, const vector_type &b, ParallelStorageType type)
bool i_am_root ()
void init_collected_vec (vector_type &collectedX)
bool init_mat (const matrix_type &A)
bool is_serial ()
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
virtual ~AgglomeratingBase ()
Public Member Functions inherited from ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > A)
initializes this inverse operator for a linear operator
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > A, const TAlgebra::vector_type &u)
initializes this inverse operator for a linear operator
virtual bool init (SmartPtr< MatrixOperator< TAlgebra::matrix_type, TAlgebra::vector_type, TAlgebra::vector_type > > A)=0
initializes this inverse operator for a matrix-based operator
virtual ~IMatrixOperatorInverse ()
virtual destructor
Public Member Functions inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
virtual SmartPtr< ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > > clone ()
clone
SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > convergence_check ()
returns the convergence check
ConstSmartPtr< IConvergenceCheck< TAlgebra::vector_type > > convergence_check () const
returns the convergence check
number defect () const
returns the current defect
ILinearOperatorInverse ()
constructor setting convergence check to (100, 1e-12, 1e-12, true)
ILinearOperatorInverse (SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > spConvCheck)
Default constructor.
SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > linear_operator ()
returns the current Operator this Inverse Operator is initialized for
number reduction () const
returns the current relative reduction
void set_convergence_check (SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > spConvCheck)
set the convergence check
virtual int standard_offset () const
returns the standard offset for output
int step () const
returns the current number of steps
virtual ~ILinearOperatorInverse ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< X, Y >
virtual bool apply (Y &c, const X &d)=0
compute new correction c = B*d
virtual bool apply_update_defect (Y &c, X &d)=0
compute new correction c = B*d and update defect d := d - A*c
SmartPtr< IDamping< X, Y > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< X, Y > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< Y, X > > J, const Y &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< Y, X > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< X, Y > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Protected Attributes
std::string m_name
SmartPtr< ILinearOperatorInverse< vector_type, vector_type > > m_pLinOpInverse
Protected Attributes inherited from ug::AgglomeratingBase< IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >, TAlgebra >
HorizontalAlgebraLayouts agglomerationLayout
vector_type collectedB
vector_type collectedX
bool m_bEmpty
bool m_bRoot
matrix_type * m_pMatrix
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spCollectedOp
SmartPtr< AlgebraLayouts > m_spLocalAlgebraLayouts
Protected Attributes inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > m_spConvCheck
smart pointer holding the convergence check
SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > m_spLinearOperator
Operator that is inverted by this Inverse Operator.
Protected Attributes inherited from ug::ILinearIterator< X, Y >
SmartPtr< IDamping< X, Y > > m_spDamping
the scaling
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::AgglomeratingSolver< TAlgebra >::algebra_type
base_type
template<typename TAlgebra > typedef AgglomeratingBase<IMatrixOperatorInverse<matrix_type,vector_type>, algebra_type > ug::AgglomeratingSolver< TAlgebra >::base_type
Base type.
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::AgglomeratingSolver< TAlgebra >::matrix_type
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::AgglomeratingSolver< TAlgebra >::vector_type
Constructor & Destructor Documentation
AgglomeratingSolver()
template<typename TAlgebra > ug::AgglomeratingSolver< TAlgebra >::AgglomeratingSolver (SmartPtr< ILinearOperatorInverse< vector_type, vector_type > > linOpInverse) inline
References ug::AgglomeratingSolver< TAlgebra >::m_name, ug::AgglomeratingSolver< TAlgebra >::m_pLinOpInverse, and UG_COND_THROW.
~AgglomeratingSolver()
template<typename TAlgebra > virtual ug::AgglomeratingSolver< TAlgebra >::~AgglomeratingSolver () inline virtual
Member Function Documentation
apply_agglomerated()
template<typename TAlgebra > virtual bool ug::AgglomeratingSolver< TAlgebra >::apply_agglomerated (vector_type & x, const vector_type & b) inline virtual
Implements ug::AgglomeratingBase< IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >, TAlgebra >.
References ug::AgglomeratingSolver< TAlgebra >::m_pLinOpInverse, and UG_CATCH_THROW.
config_string()
template<typename TAlgebra > virtual std::string ug::AgglomeratingSolver< TAlgebra >::config_string () const inline virtual
returns information about configuration parameters
this should return necessary information about parameters and possibly calling config_string of subcomponents.
Returns
std::string necessary information about configuration parameters
Reimplemented from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
References ug::AgglomeratingSolver< TAlgebra >::m_pLinOpInverse.
init() [1/3]
template<typename TAlgebra > virtual bool ug::AgglomeratingSolver< TAlgebra >::init (SmartPtr< ILinearOperator< vector_type > > A) inline virtual
References ug::AgglomeratingBase< TBase, TAlgebra >::base_init().
init() [2/3]
template<typename TAlgebra > virtual bool ug::AgglomeratingSolver< TAlgebra >::init (SmartPtr< ILinearOperator< vector_type > > A, const vector_type & u) inline virtual
References ug::AgglomeratingBase< TBase, TAlgebra >::base_init().
init() [3/3]
template<typename TAlgebra > virtual bool ug::AgglomeratingSolver< TAlgebra >::init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op) inline virtual
References ug::AgglomeratingBase< TBase, TAlgebra >::base_init().
init_agglomerated()
template<typename TAlgebra > virtual bool ug::AgglomeratingSolver< TAlgebra >::init_agglomerated (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op) inline virtual
Implements ug::AgglomeratingBase< IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >, TAlgebra >.
References ug::AgglomeratingSolver< TAlgebra >::m_pLinOpInverse, and UG_CATCH_THROW.
name()
template<typename TAlgebra > virtual const char* ug::AgglomeratingSolver< TAlgebra >::name () const inline virtual
returns the name of the operator inverse
This method returns the name of the inverse operator. This function is typically needed, when the inverse operator is used inside of another and some debug output should be printed
Returns
const char* name of inverse operator
Implements ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
References ug::AgglomeratingSolver< TAlgebra >::m_name.
supports_parallel()
template<typename TAlgebra > virtual bool ug::AgglomeratingSolver< TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
Member Data Documentation
m_name
template<typename TAlgebra > std::string ug::AgglomeratingSolver< TAlgebra >::m_name protected
Referenced by ug::AgglomeratingSolver< TAlgebra >::AgglomeratingSolver(), and ug::AgglomeratingSolver< TAlgebra >::name().
m_pLinOpInverse
template<typename TAlgebra > SmartPtr<ILinearOperatorInverse<vector_type, vector_type> > ug::AgglomeratingSolver< TAlgebra >::m_pLinOpInverse protected
Referenced by ug::AgglomeratingSolver< TAlgebra >::AgglomeratingSolver(), ug::AgglomeratingSolver< TAlgebra >::apply_agglomerated(), ug::AgglomeratingSolver< TAlgebra >::config_string(), and ug::AgglomeratingSolver< TAlgebra >::init_agglomerated().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/linear_solver/agglomerating_solver.h