ug4: ug::DistributedGridManager::ElementInfo< TGeomObj > Class Template Reference
ug::DistributedGridManager::ElementInfo< TGeomObj > Class Template Reference
Be careful when creating copies of ElementInfo.
#include <distributed_grid.h>
Classes
struct Data
struct Entry
Public Types
typedef EntryList::const_iterator ConstEntryIterator
typedef EntryList::iterator EntryIterator
typedef std::list< Entry > EntryList
typedef GridLayoutMap::template Types< TGeomObj >::Interface Interface
typedef Interface::iterator InterfaceElemIter
Public Member Functions
void add_entry (Interface *interface, InterfaceElemIter iter, int intfcType)
ElementInfo ()
EntryIterator find_entry (Interface *interface)
Note: This method may only be called if is_interface_entry() returns true.
Interface * get_interface (EntryIterator iter)
int get_interface_type (ConstEntryIterator iter) const
int get_interface_type (EntryIterator iter) const
size_t get_local_id (ConstEntryIterator iter) const
size_t get_local_id (EntryIterator iter) const
byte get_status () const
int get_target_proc (ConstEntryIterator iter) const
int get_target_proc (EntryIterator iter) const
bool is_interface_element ()
void remove_entry (Interface *interface)
void reset ()
void set_status (byte status)
~ElementInfo ()
EntryIterator entries_begin ()
Note: This method may only be called if is_interface_entry() returns true.
EntryIterator entries_end ()
Note: This method may only be called if is_interface_entry() returns true.
ConstEntryIterator entries_begin () const
Note: This method may only be called if is_interface_entry() returns true.
ConstEntryIterator entries_end () const
Note: This method may only be called if is_interface_entry() returns true.
Protected Member Functions
Data & data ()
returns the data object. Creates it if necessary.
bool has_data () const
Protected Attributes
OwnedPtr< Data > m_data
OwnedPtr is required to transfer ownership of the data-ptr during copy-operations.
Detailed Description
template<class TGeomObj>
class ug::DistributedGridManager::ElementInfo< TGeomObj >
Be careful when creating copies of ElementInfo.
Ownership of the internal data-object is transfered to the new copy. The old instance will thus point to a NULL pointer instead of the data object after the copy operation.
Member Typedef Documentation
ConstEntryIterator
template<class TGeomObj > typedef EntryList::const_iterator ug::DistributedGridManager::ElementInfo< TGeomObj >::ConstEntryIterator
EntryIterator
template<class TGeomObj > typedef EntryList::iterator ug::DistributedGridManager::ElementInfo< TGeomObj >::EntryIterator
EntryList
template<class TGeomObj > typedef std::list<Entry> ug::DistributedGridManager::ElementInfo< TGeomObj >::EntryList
Interface
template<class TGeomObj > typedef GridLayoutMap::template Types<TGeomObj>::Interface ug::DistributedGridManager::ElementInfo< TGeomObj >::Interface
InterfaceElemIter
template<class TGeomObj > typedef Interface::iterator ug::DistributedGridManager::ElementInfo< TGeomObj >::InterfaceElemIter
Constructor & Destructor Documentation
ElementInfo()
template<class TGeomObj > ug::DistributedGridManager::ElementInfo< TGeomObj >::ElementInfo () inline
~ElementInfo()
template<class TGeomObj > ug::DistributedGridManager::ElementInfo< TGeomObj >::~ElementInfo () inline
References ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::m_data.
Member Function Documentation
add_entry()
template<class TGeomObj > void ug::DistributedGridManager::ElementInfo< TGeomObj >::add_entry (Interface * interface, InterfaceElemIter iter, int intfcType) inline
References ug::DistributedGridManager::ElementInfo< TGeomObj >::data(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::Data::m_entries.
Referenced by ug::DistributedGridManager::add_element_to_interface(), and ug::DistributedGridManager::update_elem_info().
data()
template<class TGeomObj > Data& ug::DistributedGridManager::ElementInfo< TGeomObj >::data () inline protected
returns the data object. Creates it if necessary.
References ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::m_data.
Referenced by ug::DistributedGridManager::ElementInfo< TGeomObj >::add_entry(), ug::DistributedGridManager::ElementInfo< TGeomObj >::remove_entry(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::set_status().
entries_begin() [1/2]
template<class TGeomObj > EntryIterator ug::DistributedGridManager::ElementInfo< TGeomObj >::entries_begin () inline
Note: This method may only be called if is_interface_entry() returns true.
References ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::m_data.
Referenced by ug::DistributedGridManager::element_to_be_erased(), ug::DistributedGridManager::ElementInfo< TGeomObj >::find_entry(), ug::DistributedGridManager::handle_created_element(), and ug::DistributedGridManager::schedule_element_for_insertion().
entries_begin() [2/2]
template<class TGeomObj > ConstEntryIterator ug::DistributedGridManager::ElementInfo< TGeomObj >::entries_begin () const inline
Note: This method may only be called if is_interface_entry() returns true.
References ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::m_data.
entries_end() [1/2]
template<class TGeomObj > EntryIterator ug::DistributedGridManager::ElementInfo< TGeomObj >::entries_end () inline
Note: This method may only be called if is_interface_entry() returns true.
References ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::m_data.
Referenced by ug::DistributedGridManager::element_to_be_erased(), ug::DistributedGridManager::ElementInfo< TGeomObj >::find_entry(), ug::DistributedGridManager::handle_created_element(), and ug::DistributedGridManager::schedule_element_for_insertion().
entries_end() [2/2]
template<class TGeomObj > ConstEntryIterator ug::DistributedGridManager::ElementInfo< TGeomObj >::entries_end () const inline
Note: This method may only be called if is_interface_entry() returns true.
References ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::m_data.
find_entry()
template<class TGeomObj > EntryIterator ug::DistributedGridManager::ElementInfo< TGeomObj >::find_entry (Interface * interface) inline
Note: This method may only be called if is_interface_entry() returns true.
References ug::DistributedGridManager::ElementInfo< TGeomObj >::entries_begin(), ug::DistributedGridManager::ElementInfo< TGeomObj >::entries_end(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data().
Referenced by ug::DistributedGridManager::ElementInfo< TGeomObj >::remove_entry().
get_interface()
template<class TGeomObj > Interface* ug::DistributedGridManager::ElementInfo< TGeomObj >::get_interface (EntryIterator iter) inline
get_interface_type() [1/2]
template<class TGeomObj > int ug::DistributedGridManager::ElementInfo< TGeomObj >::get_interface_type (ConstEntryIterator iter) const inline
get_interface_type() [2/2]
template<class TGeomObj > int ug::DistributedGridManager::ElementInfo< TGeomObj >::get_interface_type (EntryIterator iter) const inline
Referenced by ug::DistributedGridManager::schedule_element_for_insertion().
get_local_id() [1/2]
template<class TGeomObj > size_t ug::DistributedGridManager::ElementInfo< TGeomObj >::get_local_id (ConstEntryIterator iter) const inline
get_local_id() [2/2]
template<class TGeomObj > size_t ug::DistributedGridManager::ElementInfo< TGeomObj >::get_local_id (EntryIterator iter) const inline
Referenced by ug::DistributedGridManager::schedule_element_for_insertion().
get_status()
template<class TGeomObj > byte ug::DistributedGridManager::ElementInfo< TGeomObj >::get_status () const inline
References ug::ES_NONE, ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::m_data.
Referenced by ug::DistributedGridManager::get_status(), ug::DistributedGridManager::is_interface_element(), ug::DistributedGridManager::schedule_element_for_insertion(), and ug::DistributedGridManager::update_elem_info().
get_target_proc() [1/2]
template<class TGeomObj > int ug::DistributedGridManager::ElementInfo< TGeomObj >::get_target_proc (ConstEntryIterator iter) const inline
get_target_proc() [2/2]
template<class TGeomObj > int ug::DistributedGridManager::ElementInfo< TGeomObj >::get_target_proc (EntryIterator iter) const inline
Referenced by ug::DistributedGridManager::schedule_element_for_insertion().
has_data()
template<class TGeomObj > bool ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data () const inline protected
References ug::DistributedGridManager::ElementInfo< TGeomObj >::m_data.
Referenced by ug::DistributedGridManager::ElementInfo< TGeomObj >::data(), ug::DistributedGridManager::ElementInfo< TGeomObj >::entries_begin(), ug::DistributedGridManager::ElementInfo< TGeomObj >::entries_end(), ug::DistributedGridManager::ElementInfo< TGeomObj >::find_entry(), ug::DistributedGridManager::ElementInfo< TGeomObj >::get_status(), ug::DistributedGridManager::ElementInfo< TGeomObj >::is_interface_element(), ug::DistributedGridManager::ElementInfo< TGeomObj >::reset(), ug::DistributedGridManager::ElementInfo< TGeomObj >::set_status(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::~ElementInfo().
is_interface_element()
template<class TGeomObj > bool ug::DistributedGridManager::ElementInfo< TGeomObj >::is_interface_element () inline
References ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::m_data.
Referenced by ug::DistributedGridManager::element_to_be_erased(), ug::DistributedGridManager::handle_created_element(), and ug::DistributedGridManager::schedule_element_for_insertion().
remove_entry()
template<class TGeomObj > void ug::DistributedGridManager::ElementInfo< TGeomObj >::remove_entry (Interface * interface) inline
References ug::DistributedGridManager::ElementInfo< TGeomObj >::data(), ug::DistributedGridManager::ElementInfo< TGeomObj >::find_entry(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::Data::m_entries.
reset()
template<class TGeomObj > void ug::DistributedGridManager::ElementInfo< TGeomObj >::reset () inline
References ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::m_data.
Referenced by ug::DistributedGridManager::handle_created_element(), and ug::DistributedGridManager::reset_elem_infos().
set_status()
template<class TGeomObj > void ug::DistributedGridManager::ElementInfo< TGeomObj >::set_status (byte status) inline
References ug::DistributedGridManager::ElementInfo< TGeomObj >::data(), ug::ES_NONE, ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::Data::m_status.
Referenced by ug::DistributedGridManager::add_element_to_interface(), ug::DistributedGridManager::create_missing_constrained_h_interfaces(), ug::DistributedGridManager::handle_created_element(), ug::DistributedGridManager::schedule_element_for_insertion(), and ug::DistributedGridManager::update_elem_info().
Member Data Documentation
m_data
template<class TGeomObj > OwnedPtr<Data> ug::DistributedGridManager::ElementInfo< TGeomObj >::m_data protected
OwnedPtr is required to transfer ownership of the data-ptr during copy-operations.
Since ElementInfo objects are stored in attachments, they will be copied from time to time. Ownership is thereby transfered to the new copy.
Referenced by ug::DistributedGridManager::ElementInfo< TGeomObj >::data(), ug::DistributedGridManager::ElementInfo< TGeomObj >::entries_begin(), ug::DistributedGridManager::ElementInfo< TGeomObj >::entries_end(), ug::DistributedGridManager::ElementInfo< TGeomObj >::get_status(), ug::DistributedGridManager::ElementInfo< TGeomObj >::has_data(), ug::DistributedGridManager::ElementInfo< TGeomObj >::is_interface_element(), ug::DistributedGridManager::ElementInfo< TGeomObj >::reset(), and ug::DistributedGridManager::ElementInfo< TGeomObj >::~ElementInfo().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/distributed_grid.h