ug4: ug::Geometry< dim, attachmentDim > Class Template Reference
ug::Geometry< dim, attachmentDim > Class Template Reference
provides a grid and access to the coordinates of the vertices
#include <geometry.h>
Public Types
typedef MathVector< attachmentDim > attached_vector_t
typedef IGeometry< dim > base_t
typedef Attachment< attached_vector_t > position_attachment_t
typedef base_t::vector_t vector_t
Public Types inherited from ug::IGeometry< dim >
typedef MathVector< dim > vector_t
Public Member Functions
virtual vector_t element_center (Edge *e) const
virtual vector_t element_center (Face *e) const
virtual vector_t element_center (Vertex *e) const
virtual vector_t element_center (Volume *e) const
Geometry (Grid &g, position_attachment_t a)
virtual vector_t pos (Vertex *vrt) const
const IAttachment & position_attachment () const
virtual int position_attachment_dim () const
virtual void set_pos (Vertex *vrt, const vector_t &p)
Public Member Functions inherited from ug::IGeometry< dim >
Grid & grid () const
IGeometry (Grid &g)
virtual ~IGeometry ()
Private Attributes
Grid::VertexAttachmentAccessor< position_attachment_t > m_aaPos
position_attachment_t m_aPos
Detailed Description
template<int dim, int attachmentDim>
class ug::Geometry< dim, attachmentDim >
provides a grid and access to the coordinates of the vertices
The dimension of the output coordinates ('dim') may differ from the dimension of the coordinates which are actually attached to the grid ('attachedDim').
Member Typedef Documentation
attached_vector_t
template<int dim, int attachmentDim> typedef MathVector<attachmentDim> ug::Geometry< dim, attachmentDim >::attached_vector_t
base_t
template<int dim, int attachmentDim> typedef IGeometry<dim> ug::Geometry< dim, attachmentDim >::base_t
position_attachment_t
template<int dim, int attachmentDim> typedef Attachment<attached_vector_t> ug::Geometry< dim, attachmentDim >::position_attachment_t
vector_t
template<int dim, int attachmentDim> typedef base_t::vector_t ug::Geometry< dim, attachmentDim >::vector_t
Constructor & Destructor Documentation
Geometry()
template<int dim, int attachmentDim> ug::Geometry< dim, attachmentDim >::Geometry (Grid & g, position_attachment_t a) inline
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::Grid::has_vertex_attachment(), ug::Geometry< dim, attachmentDim >::m_aaPos, and UG_COND_THROW.
Member Function Documentation
element_center() [1/4]
template<int dim, int attachmentDim> virtual vector_t ug::Geometry< dim, attachmentDim >::element_center (Edge * e) const inline virtual
Implements ug::IGeometry< dim >.
References ug::CalculateCenter(), ug::MathVector< dim >::from(), and ug::Geometry< dim, attachmentDim >::m_aaPos.
element_center() [2/4]
template<int dim, int attachmentDim> virtual vector_t ug::Geometry< dim, attachmentDim >::element_center (Face * e) const inline virtual
Implements ug::IGeometry< dim >.
References ug::CalculateCenter(), ug::MathVector< dim >::from(), and ug::Geometry< dim, attachmentDim >::m_aaPos.
element_center() [3/4]
template<int dim, int attachmentDim> virtual vector_t ug::Geometry< dim, attachmentDim >::element_center (Vertex * e) const inline virtual
Implements ug::IGeometry< dim >.
References ug::MathVector< dim >::from(), and ug::Geometry< dim, attachmentDim >::m_aaPos.
element_center() [4/4]
template<int dim, int attachmentDim> virtual vector_t ug::Geometry< dim, attachmentDim >::element_center (Volume * e) const inline virtual
Implements ug::IGeometry< dim >.
References ug::CalculateCenter(), ug::MathVector< dim >::from(), and ug::Geometry< dim, attachmentDim >::m_aaPos.
pos()
template<int dim, int attachmentDim> virtual vector_t ug::Geometry< dim, attachmentDim >::pos (Vertex * vrt) const inline virtual
Implements ug::IGeometry< dim >.
References ug::MathVector< dim >::from(), and ug::Geometry< dim, attachmentDim >::m_aaPos.
position_attachment()
template<int dim, int attachmentDim> const IAttachment& ug::Geometry< dim, attachmentDim >::position_attachment () const inline virtual
Implements ug::IGeometry< dim >.
References ug::Geometry< dim, attachmentDim >::m_aPos.
position_attachment_dim()
template<int dim, int attachmentDim> virtual int ug::Geometry< dim, attachmentDim >::position_attachment_dim () const inline virtual
Implements ug::IGeometry< dim >.
set_pos()
template<int dim, int attachmentDim> virtual void ug::Geometry< dim, attachmentDim >::set_pos (Vertex * vrt, const vector_t & p) inline virtual
Implements ug::IGeometry< dim >.
References ug::MathVector< N, T >::from(), ug::Geometry< dim, attachmentDim >::m_aaPos, and p.
Member Data Documentation
m_aaPos
template<int dim, int attachmentDim> Grid::VertexAttachmentAccessor<position_attachment_t> ug::Geometry< dim, attachmentDim >::m_aaPos private
Referenced by ug::Geometry< dim, attachmentDim >::element_center(), ug::Geometry< dim, attachmentDim >::Geometry(), ug::Geometry< dim, attachmentDim >::pos(), and ug::Geometry< dim, attachmentDim >::set_pos().
m_aPos
template<int dim, int attachmentDim> position_attachment_t ug::Geometry< dim, attachmentDim >::m_aPos private
Referenced by ug::Geometry< dim, attachmentDim >::position_attachment().
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/geometry.h