ug4: ug::IVectorDebugWriter< TVector > Class Template Reference
ug::IVectorDebugWriter< TVector > Class Template Reference abstract
base class for all vector debug writer
#include <debug_writer.h>
Public Types
typedef TVector vector_type
type of vector
Public Member Functions
int current_dimension () const
returns the current dimension
void enter_section (const char *secDir)
enter a new debugging section
std::string get_base_dir ()
SmartPtr< DebugWriterContext > get_context ()
get the debugging writer context
ConstSmartPtr< DebugWriterContext > get_context () const
get the debugging writer context
int get_dim () const
get the dimensionality
template<int dim>
const std::vector< MathVector< dim > > & get_positions () const
returns the positions (only available for current dimension)
IVectorDebugWriter ()
Constructor.
void leave_section ()
leave the current debugging section
virtual void print_message (const char *msg)
prints a message
void set_base_dir (const char *const baseDir)
set the base directory for output files (.vec and .mat)
void set_context (SmartPtr< DebugWriterContext > context)
set the debugging writer context
template<int dim>
void set_positions (const std::vector< MathVector< dim > > &vPos)
sets the current positions
template<int dim>
void set_positions (IPositionProvider< dim > &provider)
employs a position provider to set the current positions
virtual void update_positions ()
virtual void write_vector (const vector_type &vec, const char *name)=0
write vector
virtual ~IVectorDebugWriter ()
virtual destructor
Protected Member Functions
void compose_file_path (std::string &path)
composes the path for the files and creates the intermediate directories (up to the base one):
std::vector< MathVector< 1 > > & get_pos (Int2Type< 1 >)
help function to get local ips
const std::vector< MathVector< 1 > > & get_pos (Int2Type< 1 >) const
std::vector< MathVector< 2 > > & get_pos (Int2Type< 2 >)
const std::vector< MathVector< 2 > > & get_pos (Int2Type< 2 >) const
std::vector< MathVector< 3 > > & get_pos (Int2Type< 3 >)
const std::vector< MathVector< 3 > > & get_pos (Int2Type< 3 >) const
template<int dim>
std::vector< MathVector< dim > > & positions ()
returns the positions and sets the current dim
Protected Attributes
int m_currentDim
current dimension
SmartPtr< DebugWriterContext > m_spContext
debugging writer context
std::vector< MathVector< 1 > > m_vPos1d
vectors of positions
std::vector< MathVector< 2 > > m_vPos2d
std::vector< MathVector< 3 > > m_vPos3d
Detailed Description
template<typename TVector>
class ug::IVectorDebugWriter< TVector >
base class for all vector debug writer
This is the base class for debug output of algebraic vectors
Member Typedef Documentation
vector_type
template<typename TVector > typedef TVector ug::IVectorDebugWriter< TVector >::vector_type
type of vector
Constructor & Destructor Documentation
IVectorDebugWriter()
template<typename TVector > ug::IVectorDebugWriter< TVector >::IVectorDebugWriter () inline
Constructor.
~IVectorDebugWriter()
template<typename TVector > virtual ug::IVectorDebugWriter< TVector >::~IVectorDebugWriter () inline virtual
virtual destructor
Member Function Documentation
compose_file_path()
template<typename TVector > void ug::IVectorDebugWriter< TVector >::compose_file_path (std::string & path) inline protected
composes the path for the files and creates the intermediate directories (up to the base one):
References ug::IVectorDebugWriter< TVector >::m_spContext.
current_dimension()
template<typename TVector > int ug::IVectorDebugWriter< TVector >::current_dimension () const inline
returns the current dimension
References ug::IVectorDebugWriter< TVector >::m_currentDim.
enter_section()
template<typename TVector > void ug::IVectorDebugWriter< TVector >::enter_section (const char * secDir) inline
enter a new debugging section
References ug::IVectorDebugWriter< TVector >::m_spContext.
get_base_dir()
template<typename TVector > std::string ug::IVectorDebugWriter< TVector >::get_base_dir () inline
References ug::IVectorDebugWriter< TVector >::m_spContext.
get_context() [1/2]
template<typename TVector > SmartPtr<DebugWriterContext> ug::IVectorDebugWriter< TVector >::get_context () inline
get the debugging writer context
References ug::IVectorDebugWriter< TVector >::m_spContext.
get_context() [2/2]
template<typename TVector > ConstSmartPtr<DebugWriterContext> ug::IVectorDebugWriter< TVector >::get_context () const inline
get the debugging writer context
References ug::IVectorDebugWriter< TVector >::m_spContext.
get_dim()
template<typename TVector > int ug::IVectorDebugWriter< TVector >::get_dim () const inline
get the dimensionality
References ug::IVectorDebugWriter< TVector >::m_currentDim.
Referenced by ug::OverlapWriter< TAlgebra >::init().
get_pos() [1/6]
template<typename TVector > std::vector<MathVector<1> >& ug::IVectorDebugWriter< TVector >::get_pos (Int2Type< 1 >) inline protected
help function to get local ips
References ug::IVectorDebugWriter< TVector >::m_vPos1d.
Referenced by ug::IVectorDebugWriter< TVector >::get_positions(), ug::IVectorDebugWriter< TVector >::positions(), and ug::IVectorDebugWriter< TVector >::set_positions().
get_pos() [2/6]
template<typename TVector > const std::vector<MathVector<1> >& ug::IVectorDebugWriter< TVector >::get_pos (Int2Type< 1 >) const inline protected
References ug::IVectorDebugWriter< TVector >::m_vPos1d.
get_pos() [3/6]
template<typename TVector > std::vector<MathVector<2> >& ug::IVectorDebugWriter< TVector >::get_pos (Int2Type< 2 >) inline protected
References ug::IVectorDebugWriter< TVector >::m_vPos2d.
get_pos() [4/6]
template<typename TVector > const std::vector<MathVector<2> >& ug::IVectorDebugWriter< TVector >::get_pos (Int2Type< 2 >) const inline protected
References ug::IVectorDebugWriter< TVector >::m_vPos2d.
get_pos() [5/6]
template<typename TVector > std::vector<MathVector<3> >& ug::IVectorDebugWriter< TVector >::get_pos (Int2Type< 3 >) inline protected
References ug::IVectorDebugWriter< TVector >::m_vPos3d.
get_pos() [6/6]
template<typename TVector > const std::vector<MathVector<3> >& ug::IVectorDebugWriter< TVector >::get_pos (Int2Type< 3 >) const inline protected
References ug::IVectorDebugWriter< TVector >::m_vPos3d.
get_positions()
template<typename TVector > template<int dim> const std::vector<MathVector<dim> >& ug::IVectorDebugWriter< TVector >::get_positions () const inline
returns the positions (only available for current dimension)
References dim, ug::IVectorDebugWriter< TVector >::get_pos(), and ug::IVectorDebugWriter< TVector >::m_currentDim.
leave_section()
template<typename TVector > void ug::IVectorDebugWriter< TVector >::leave_section () inline
leave the current debugging section
References ug::IVectorDebugWriter< TVector >::m_spContext.
positions()
template<typename TVector > template<int dim> std::vector<MathVector<dim> >& ug::IVectorDebugWriter< TVector >::positions () inline protected
returns the positions and sets the current dim
References dim, ug::IVectorDebugWriter< TVector >::get_pos(), and ug::IVectorDebugWriter< TVector >::m_currentDim.
print_message()
template<typename TVector > virtual void ug::IVectorDebugWriter< TVector >::print_message (const char * msg) inline virtual
prints a message
References ug::IVectorDebugWriter< TVector >::m_spContext.
set_base_dir()
template<typename TVector > void ug::IVectorDebugWriter< TVector >::set_base_dir (const char *const baseDir) inline
set the base directory for output files (.vec and .mat)
References ug::IVectorDebugWriter< TVector >::m_spContext, and ug::IVectorDebugWriter< TVector >::set_context().
set_context()
template<typename TVector > void ug::IVectorDebugWriter< TVector >::set_context (SmartPtr< DebugWriterContext > context) inline
set the debugging writer context
References ug::IVectorDebugWriter< TVector >::m_spContext.
Referenced by ug::IVectorDebugWriter< TVector >::set_base_dir().
set_positions() [1/2]
template<typename TVector > template<int dim> void ug::IVectorDebugWriter< TVector >::set_positions (const std::vector< MathVector< dim > > & vPos) inline
sets the current positions
References dim, ug::IVectorDebugWriter< TVector >::get_pos(), and ug::IVectorDebugWriter< TVector >::m_currentDim.
set_positions() [2/2]
template<typename TVector > template<int dim> void ug::IVectorDebugWriter< TVector >::set_positions (IPositionProvider< dim > & provider) inline
employs a position provider to set the current positions
References dim, ug::IVectorDebugWriter< TVector >::get_pos(), ug::IPositionProvider< dim >::get_positions(), and ug::IVectorDebugWriter< TVector >::m_currentDim.
update_positions()
template<typename TVector > virtual void ug::IVectorDebugWriter< TVector >::update_positions () inline virtual
gives subclasses the oportunity to calculate the positions this is used e.g. in GridFunctionDebugWriter after this has been called, get_positions gives valid positions those positions are used e.g. in AMG or Schur methods.
Reimplemented in ug::GridFunctionDebugWriter< TDomain, TAlgebra >.
write_vector()
template<typename TVector > virtual void ug::IVectorDebugWriter< TVector >::write_vector (const vector_type & vec, const char * name) pure virtual
write vector
Implemented in ug::IDebugWriter< TAlgebra >, and ug::GridFunctionDebugWriter< TDomain, TAlgebra >.
Member Data Documentation
m_currentDim
template<typename TVector > int ug::IVectorDebugWriter< TVector >::m_currentDim protected
current dimension
Referenced by ug::IVectorDebugWriter< TVector >::current_dimension(), ug::IVectorDebugWriter< TVector >::get_dim(), ug::IVectorDebugWriter< TVector >::get_positions(), ug::IVectorDebugWriter< TVector >::positions(), and ug::IVectorDebugWriter< TVector >::set_positions().
m_spContext
template<typename TVector > SmartPtr<DebugWriterContext> ug::IVectorDebugWriter< TVector >::m_spContext protected
debugging writer context
Referenced by ug::IVectorDebugWriter< TVector >::compose_file_path(), ug::IVectorDebugWriter< TVector >::enter_section(), ug::IVectorDebugWriter< TVector >::get_base_dir(), ug::IVectorDebugWriter< TVector >::get_context(), ug::IVectorDebugWriter< TVector >::leave_section(), ug::IVectorDebugWriter< TVector >::print_message(), ug::IVectorDebugWriter< TVector >::set_base_dir(), and ug::IVectorDebugWriter< TVector >::set_context().
m_vPos1d
template<typename TVector > std::vector<MathVector<1> > ug::IVectorDebugWriter< TVector >::m_vPos1d protected
vectors of positions
Referenced by ug::IVectorDebugWriter< TVector >::get_pos().
m_vPos2d
template<typename TVector > std::vector<MathVector<2> > ug::IVectorDebugWriter< TVector >::m_vPos2d protected
Referenced by ug::IVectorDebugWriter< TVector >::get_pos().
m_vPos3d
template<typename TVector > std::vector<MathVector<3> > ug::IVectorDebugWriter< TVector >::m_vPos3d protected
Referenced by ug::IVectorDebugWriter< TVector >::get_pos().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/debug_writer.h