ug4: ug::BGLParallelMatrix< T >::out_edge_iterator Class Reference
ug::BGLParallelMatrix< T >::out_edge_iterator Class Reference
#include <parallel_matrix.h>
Public Member Functions
bool operator!= (out_edge_iterator const &p) const
edge operator* () const
out_edge_iterator & operator++ ()
bool operator== (out_edge_iterator const &p) const
out_edge_iterator ()
out_edge_iterator (base_edge_iterator b, owners const *o, ghosts const *g, T const *m)
Private Attributes
base_edge_iterator _base
ghosts const * _ghosts
T const * _matrix
owners const * _owners
Constructor & Destructor Documentation
out_edge_iterator() [1/2]
template<class T > ug::BGLParallelMatrix< T >::out_edge_iterator::out_edge_iterator () inline
out_edge_iterator() [2/2]
template<class T > ug::BGLParallelMatrix< T >::out_edge_iterator::out_edge_iterator (base_edge_iterator b, owners const * o, ghosts const * g, T const * m) inline
Member Function Documentation
operator!=()
template<class T > bool ug::BGLParallelMatrix< T >::out_edge_iterator::operator!= (out_edge_iterator const & p) const inline
References ug::BGLParallelMatrix< T >::out_edge_iterator::operator==(), and p.
operator*()
template<class T > BGLParallelMatrix< T >::edge ug::BGLParallelMatrix< T >::out_edge_iterator::operator*
References ug::BGLParallelMatrix< T >::out_edge_iterator::_base, ug::BGLParallelMatrix< T >::out_edge_iterator::_ghosts, ug::BGLParallelMatrix< T >::out_edge_iterator::_matrix, ug::BGLParallelMatrix< T >::out_edge_iterator::_owners, s, boost::source(), and boost::target().
operator++()
template<class T > out_edge_iterator& ug::BGLParallelMatrix< T >::out_edge_iterator::operator++ () inline
References ug::BGLParallelMatrix< T >::out_edge_iterator::_base.
operator==()
template<class T > bool ug::BGLParallelMatrix< T >::out_edge_iterator::operator== (out_edge_iterator const & p) const inline
References ug::BGLParallelMatrix< T >::out_edge_iterator::_base, and p.
Referenced by ug::BGLParallelMatrix< T >::out_edge_iterator::operator!=().
Member Data Documentation
_base
template<class T > base_edge_iterator ug::BGLParallelMatrix< T >::out_edge_iterator::_base private
Referenced by ug::BGLParallelMatrix< T >::out_edge_iterator::operator*(), ug::BGLParallelMatrix< T >::out_edge_iterator::operator++(), and ug::BGLParallelMatrix< T >::out_edge_iterator::operator==().
_ghosts
template<class T > ghosts const* ug::BGLParallelMatrix< T >::out_edge_iterator::_ghosts private
Referenced by ug::BGLParallelMatrix< T >::out_edge_iterator::operator*().
_matrix
template<class T > T const* ug::BGLParallelMatrix< T >::out_edge_iterator::_matrix private
Referenced by ug::BGLParallelMatrix< T >::out_edge_iterator::operator*().
_owners
template<class T > owners const* ug::BGLParallelMatrix< T >::out_edge_iterator::_owners private
Referenced by ug::BGLParallelMatrix< T >::out_edge_iterator::operator*().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/graph_interface/parallel_matrix.h