ug4: ug::MapSparseMatrix< TValueType >::const_row_iterator Class Reference
ug::MapSparseMatrix< TValueType >::const_row_iterator Class Reference
#include <mapsparsematrix.h>
Public Member Functions
const_row_iterator (super it)
size_t index () const
const value_type & value ()
Private Types
typedef std::map< size_t, TValueType >::const_iterator super
Member Typedef Documentation
template<typename TValueType> typedef std::map<size_t, TValueType>::const_iterator ug::MapSparseMatrix< TValueType >::const_row_iterator::super private
Constructor & Destructor Documentation
template<typename TValueType> ug::MapSparseMatrix< TValueType >::const_row_iterator::const_row_iterator (super it) inline
Member Function Documentation
template<typename TValueType> size_t ug::MapSparseMatrix< TValueType >::const_row_iterator::index () const inline
References ug::operator*().
Referenced by ug::MapSparseMatrix< TValueType >::axpy().
template<typename TValueType> const value_type& ug::MapSparseMatrix< TValueType >::const_row_iterator::value () inline
References ug::operator*().
Referenced by ug::MapSparseMatrix< TValueType >::axpy().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/map_algebra/mapsparsematrix.h