ug4: ug::CUDAManager Class Reference
ug::CUDAManager Class Reference
#include <cuda_manager.h>
Public Member Functions
template<typename T >
T * get_temp_buffer (size_t n)
template<typename T >
T * get_temp_return_buffer ()
void init ()
virtual ~CUDAManager ()
Static Public Member Functions
static cublasHandle_t get_cublasHandle ()
static void get_cuda_devices (std::vector< cudaDeviceProp > &devices)
static cusparseHandle_t get_cusparseHandle ()
static CUDAManager & get_instance ()
static int get_max_multiprocessor_cuda_device ()
Public Attributes
size_t m_maxThreadsPerBlock
Private Attributes
cublasHandle_t cublasHandle
cusparseHandle_t cusparseHandle
void * m_tempBuffer
void * m_tempRetBuffer
size_t m_tempSize
Constructor & Destructor Documentation
~CUDAManager()
ug::CUDAManager::~CUDAManager () virtual
Member Function Documentation
get_cublasHandle()
static cublasHandle_t ug::CUDAManager::get_cublasHandle () inline static
References cublasHandle, and get_instance().
get_cuda_devices()
void ug::CUDAManager::get_cuda_devices (std::vector< cudaDeviceProp > & devices) static
get_cusparseHandle()
static cusparseHandle_t ug::CUDAManager::get_cusparseHandle () inline static
References cusparseHandle, and get_instance().
Referenced by ug::GPUSparseMatrix< TValueType >::axpy().
get_instance()
CUDAManager & ug::CUDAManager::get_instance () static
References init().
Referenced by ug::GPUSparseMatrix< TValueType >::copy_to_device(), get_cublasHandle(), and get_cusparseHandle().
get_max_multiprocessor_cuda_device()
int ug::CUDAManager::get_max_multiprocessor_cuda_device () static
get_temp_buffer()
template<typename T > T* ug::CUDAManager::get_temp_buffer (size_t n) inline
References ug::DID_CUDA, m_tempBuffer, m_tempSize, and UG_DLOG.
get_temp_return_buffer()
template<typename T > T* ug::CUDAManager::get_temp_return_buffer () inline
References m_tempRetBuffer.
init()
void ug::CUDAManager::init ()
References CUDA_CHECK_STATUS, CUDA_CHECK_SUCCESS, ug::DID_CUDA, printf(), UG_DLOG, and UG_THROW.
Referenced by get_instance().
Member Data Documentation
cublasHandle
cublasHandle_t ug::CUDAManager::cublasHandle private
Referenced by get_cublasHandle().
cusparseHandle
cusparseHandle_t ug::CUDAManager::cusparseHandle private
Referenced by get_cusparseHandle().
m_maxThreadsPerBlock
size_t ug::CUDAManager::m_maxThreadsPerBlock
m_tempBuffer
void* ug::CUDAManager::m_tempBuffer private
Referenced by get_temp_buffer().
m_tempRetBuffer
void* ug::CUDAManager::m_tempRetBuffer private
Referenced by get_temp_return_buffer().
m_tempSize
size_t ug::CUDAManager::m_tempSize private
Referenced by get_temp_buffer().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/gpu_algebra/cuda/cuda_manager.h
ugbase/lib_algebra/gpu_algebra/cuda/cuda_manager.cpp