ug4: ug::NewLayoutCreator Class Reference
ug::NewLayoutCreator Class Reference
#include <new_layout_creator.h>
Classes
struct NewSlaveNotification
Public Member Functions
void add_new_layouts_to (IndexLayout &newMasterLayout, IndexLayout &newSlaveLayout)
void create_node (const AlgebraID &globalID, int pid)
void create_node (const AlgebraID &globalID, size_t localIndex, int pid)
void create_node (size_t localIndex, int pid)
size_t create_slave_node (const AlgebraID &globalID, int distanceToMasterOrInner)
void issue (pcl::InterfaceCommunicator< IndexLayout > &communicator)
NewLayoutCreator (ParallelNodes &_PN, IndexLayout &masterLayout, IndexLayout &slaveLayout)
void process ()
Private Types
typedef std::map< int, BinaryBuffer > BufferMap
Private Member Functions
void create_mark_map (IndexLayout &masterLayout)
Private Attributes
std::set< int > masterPIDs
std::map< int, std::set< size_t > > newMasters
std::map< int, std::vector< NewSlaveNotification > > newSlaveNotifications
std::map< int, std::set< size_t > > newSlaves
BufferMap notificationBufferMap
std::map< int, std::set< size_t > > notified
map for marking nodes
ParallelNodes & PN
std::set< int > slavePIDs
Member Typedef Documentation
BufferMap
typedef std::map<int, BinaryBuffer> ug::NewLayoutCreator::BufferMap private
Constructor & Destructor Documentation
NewLayoutCreator()
ug::NewLayoutCreator::NewLayoutCreator (ParallelNodes & _PN, IndexLayout & masterLayout, IndexLayout & slaveLayout) inline
References pcl::SingleLevelLayout< TInterface >::begin(), create_mark_map(), pcl::SingleLevelLayout< TInterface >::end(), masterPIDs, pcl::SingleLevelLayout< TInterface >::proc_id(), and slavePIDs.
Member Function Documentation
add_new_layouts_to()
void ug::NewLayoutCreator::add_new_layouts_to (IndexLayout & newMasterLayout, IndexLayout & newSlaveLayout) inline
References ug::ParallelNodes::insert_into_layout_sorted(), masterPIDs, newMasters, newSlaves, PN, and slavePIDs.
create_mark_map()
void ug::NewLayoutCreator::create_mark_map (IndexLayout & masterLayout) inline private
References pcl::SingleLevelLayout< TInterface >::begin(), pcl::SingleLevelLayout< TInterface >::end(), ug::LIB_ALG_MATRIX, notified, pcl::SingleLevelLayout< TInterface >::proc_id(), PROFILE_FUNC, and UG_DLOG.
Referenced by NewLayoutCreator().
create_node() [1/3]
void ug::NewLayoutCreator::create_node (const AlgebraID & globalID, int pid) inline
References ug::ParallelNodes::global_to_local(), and PN.
Referenced by create_node().
create_node() [2/3]
void ug::NewLayoutCreator::create_node (const AlgebraID & globalID, size_t localIndex, int pid) inline
References ug::find(), ug::LIB_ALG_MATRIX, ug::AlgebraID::master_proc(), newMasters, newSlaveNotifications, notified, pcl::ProcRank(), and UG_DLOG.
create_node() [3/3]
void ug::NewLayoutCreator::create_node (size_t localIndex, int pid) inline
References create_node(), ug::ParallelNodes::local_to_global(), and PN.
create_slave_node()
size_t ug::NewLayoutCreator::create_slave_node (const AlgebraID & globalID, int distanceToMasterOrInner) inline
References ug::ParallelNodes::get_local_index_or_create_new(), ug::LIB_ALG_MATRIX, ug::AlgebraID::master_proc(), newSlaves, PN, and UG_DLOG.
issue()
void ug::NewLayoutCreator::issue (pcl::InterfaceCommunicator< IndexLayout > & communicator) inline
References ug::BinaryBuffer::buffer(), ug::LIB_ALG_MATRIX, masterPIDs, newSlaveNotifications, notificationBufferMap, pcl::InterfaceCommunicator< TLayout >::receive_raw(), pcl::InterfaceCommunicator< TLayout >::send_raw(), ug::Serialize(), slavePIDs, UG_DLOG, and ug::BinaryBuffer::write_pos().
process()
void ug::NewLayoutCreator::process () inline
References ug::Deserialize(), ug::BinaryBuffer::eof(), ug::NewLayoutCreator::NewSlaveNotification::id, ug::AlgebraID::index_on_master(), ug::LIB_ALG_MATRIX, ug::AlgebraID::master_proc(), masterPIDs, newMasters, ug::NewLayoutCreator::NewSlaveNotification::newSlaveOnPID, notificationBufferMap, notified, pcl::ProcRank(), UG_ASSERT, UG_DLOG, and ug::BinaryBuffer::write_pos().
Member Data Documentation
masterPIDs
std::set<int> ug::NewLayoutCreator::masterPIDs private
Referenced by add_new_layouts_to(), issue(), NewLayoutCreator(), and process().
newMasters
std::map<int, std::set<size_t> > ug::NewLayoutCreator::newMasters private
Referenced by add_new_layouts_to(), create_node(), and process().
newSlaveNotifications
std::map<int, std::vector<NewSlaveNotification> > ug::NewLayoutCreator::newSlaveNotifications private
Referenced by create_node(), and issue().
newSlaves
std::map<int, std::set<size_t> > ug::NewLayoutCreator::newSlaves private
Referenced by add_new_layouts_to(), and create_slave_node().
notificationBufferMap
BufferMap ug::NewLayoutCreator::notificationBufferMap private
Referenced by issue(), and process().
notified
std::map<int, std::set<size_t> > ug::NewLayoutCreator::notified private
map for marking nodes
for each processor we need to have a list which of our master nodes exist on their processor this is important because we sometimes will need to add them to interfaces
the map serves two functions:
knowing which processor has copies of our own master nodes, and so constructing correct interfaces
knowing which notifications are sent
if i is a master node (that is PN.local_to_global(i).master_proc() == pcl::ProcRank()) then i in notified[pid] means: process pid already knows that i is a slave node on his processor, and this processor knows that i the associated master that means: i is in a master interface on this processor and in a slave interface on pid.
if is is not a master node then i in notified[pid] means: we already sent a notification to the owner of i (processor PN.local_to_global(i).master_proc()) that processor pid has a copy of i.
Referenced by create_mark_map(), create_node(), and process().
PN
ParallelNodes& ug::NewLayoutCreator::PN private
Referenced by add_new_layouts_to(), create_node(), and create_slave_node().
slavePIDs
std::set<int> ug::NewLayoutCreator::slavePIDs private
Referenced by add_new_layouts_to(), issue(), and NewLayoutCreator().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/parallelization/new_layout_creator.h