ug4: ug::SortedGridFunctionOrdering< TDomain, TAlgebra > Class Template Reference
ug::SortedGridFunctionOrdering< TDomain, TAlgebra > Class Template Reference
Public Member Functions
SmartPtr< TGridFunctionNumberData > get ()
SortedGridFunctionOrdering (SmartPtr< TGridFunction > spGridFct, SmartPtr< ordering_algo_type > spOrdAlgo, const char *name)
Private Types
typedef IOrderingAlgorithm< TAlgebra, ordering_container_type > ordering_algo_type
typedef std::vector< size_t > ordering_container_type
typedef GridFunction< TDomain, TAlgebra > TGridFunction
typedef GridFunctionNumberData< GridFunction< TDomain, TAlgebra > > TGridFunctionNumberData
typedef TGridFunction::template traits< Vertex >::const_iterator VertexConstIterator
Private Attributes
const char * m_name
SmartPtr< TGridFunction > m_u
Member Typedef Documentation
ordering_algo_type
template<typename TDomain , typename TAlgebra > typedef IOrderingAlgorithm<TAlgebra, ordering_container_type> ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::ordering_algo_type private
ordering_container_type
template<typename TDomain , typename TAlgebra > typedef std::vector<size_t> ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::ordering_container_type private
TGridFunction
template<typename TDomain , typename TAlgebra > typedef GridFunction<TDomain, TAlgebra> ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::TGridFunction private
TGridFunctionNumberData
template<typename TDomain , typename TAlgebra > typedef GridFunctionNumberData<GridFunction<TDomain, TAlgebra> > ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::TGridFunctionNumberData private
VertexConstIterator
template<typename TDomain , typename TAlgebra > typedef TGridFunction::template traits<Vertex>::const_iterator ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::VertexConstIterator private
Constructor & Destructor Documentation
SortedGridFunctionOrdering()
template<typename TDomain , typename TAlgebra > ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::SortedGridFunctionOrdering (SmartPtr< TGridFunction > spGridFct, SmartPtr< ordering_algo_type > spOrdAlgo, const char * name) inline
References ug::GridFunction< TDomain, TAlgebra >::clone_without_values(), ug::DoFRef(), ug::GridFunction< TDomain, TAlgebra >::inner_dof_indices(), ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::m_name, ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::m_u, and name.
Member Function Documentation
get()
template<typename TDomain , typename TAlgebra > SmartPtr<TGridFunctionNumberData> ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::get () inline
References ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::m_name, and ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::m_u.
Member Data Documentation
m_name
template<typename TDomain , typename TAlgebra > const char* ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::m_name private
Referenced by ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::get(), and ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::SortedGridFunctionOrdering().
m_u
template<typename TDomain , typename TAlgebra > SmartPtr<TGridFunction> ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::m_u private
Referenced by ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::get(), and ug::SortedGridFunctionOrdering< TDomain, TAlgebra >::SortedGridFunctionOrdering().
The documentation for this class was generated from the following file:
ugbase/lib_disc/ordering_strategies/io_sorted_grid_function_ordering.cpp