ug4: ug::PPP_ReplaceCoordinate< dim > Class Template Reference
ug::PPP_ReplaceCoordinate< dim > Class Template Reference
Temporarily replaces the specified coordinate in the given position attachment.
#include <replace_coordinate.h>
Public Types
typedef Grid::VertexAttachmentAccessor< apos_t > aapos_t
typedef Attachment< vector_t > apos_t
typedef MathVector< dim > vector_t
Public Member Functions
virtual void partitioning_done (MultiGrid *mg, IPartitioner *partitioner)
virtual void partitioning_starts (MultiGrid *mg, IPartitioner *partitioner)
PPP_ReplaceCoordinate (apos_t aPos, ANumber aNewCoord, int newCoordIndex)
Public Member Functions inherited from ug::IPartitionPreProcessor
virtual ~IPartitionPreProcessor ()
Private Attributes
ANumber m_aNewCoord
ANumber m_aOrigCoord
apos_t m_aPos
int m_newCoordIndex
Detailed Description
template<int dim>
class ug::PPP_ReplaceCoordinate< dim >
Temporarily replaces the specified coordinate in the given position attachment.
Warning
After 'partitioning_starts' was called, the coordinates of the underlying mesh may be changed. Make sure to call 'partitioning_done' when the partitioner is done. Also make sure to call 'partitioning_done' if errors occurred during partitioning.
Member Typedef Documentation
aapos_t
template<int dim> typedef Grid::VertexAttachmentAccessor<apos_t> ug::PPP_ReplaceCoordinate< dim >::aapos_t
apos_t
template<int dim> typedef Attachment<vector_t> ug::PPP_ReplaceCoordinate< dim >::apos_t
vector_t
template<int dim> typedef MathVector<dim> ug::PPP_ReplaceCoordinate< dim >::vector_t
Constructor & Destructor Documentation
PPP_ReplaceCoordinate()
template<int dim> ug::PPP_ReplaceCoordinate< dim >::PPP_ReplaceCoordinate (apos_t aPos, ANumber aNewCoord, int newCoordIndex) inline
Member Function Documentation
partitioning_done()
template<int dim> virtual void ug::PPP_ReplaceCoordinate< dim >::partitioning_done (MultiGrid * mg, IPartitioner * partitioner) inline virtual
Implements ug::IPartitionPreProcessor.
References ug::Grid::detach_from_vertices(), ug::Grid::get_attachment_data_container(), ug::Grid::has_vertex_attachment(), ug::PPP_ReplaceCoordinate< dim >::m_aOrigCoord, ug::PPP_ReplaceCoordinate< dim >::m_aPos, ug::PPP_ReplaceCoordinate< dim >::m_newCoordIndex, UG_COND_THROW, and UG_LOG.
partitioning_starts()
template<int dim> virtual void ug::PPP_ReplaceCoordinate< dim >::partitioning_starts (MultiGrid * mg, IPartitioner * partitioner) inline virtual
Implements ug::IPartitionPreProcessor.
References ug::Grid::attach_to_vertices(), ug::Grid::get_attachment_data_container(), ug::Grid::has_vertex_attachment(), ug::PPP_ReplaceCoordinate< dim >::m_aNewCoord, ug::PPP_ReplaceCoordinate< dim >::m_aOrigCoord, ug::PPP_ReplaceCoordinate< dim >::m_aPos, ug::PPP_ReplaceCoordinate< dim >::m_newCoordIndex, UG_COND_THROW, and UG_LOG.
Member Data Documentation
m_aNewCoord
template<int dim> ANumber ug::PPP_ReplaceCoordinate< dim >::m_aNewCoord private
Referenced by ug::PPP_ReplaceCoordinate< dim >::partitioning_starts().
m_aOrigCoord
template<int dim> ANumber ug::PPP_ReplaceCoordinate< dim >::m_aOrigCoord private
Referenced by ug::PPP_ReplaceCoordinate< dim >::partitioning_done(), and ug::PPP_ReplaceCoordinate< dim >::partitioning_starts().
m_aPos
template<int dim> apos_t ug::PPP_ReplaceCoordinate< dim >::m_aPos private
Referenced by ug::PPP_ReplaceCoordinate< dim >::partitioning_done(), and ug::PPP_ReplaceCoordinate< dim >::partitioning_starts().
m_newCoordIndex
template<int dim> int ug::PPP_ReplaceCoordinate< dim >::m_newCoordIndex private
Referenced by ug::PPP_ReplaceCoordinate< dim >::partitioning_done(), and ug::PPP_ReplaceCoordinate< dim >::partitioning_starts().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/partition_pre_processors/replace_coordinate.h