ug4: ug::DoFIndexStorage Class Reference
ug::DoFIndexStorage Class Reference
#include <dof_index_storage.h>
Public Member Functions
DoFIndexStorage (SmartPtr< MultiGrid > spMG, ConstSmartPtr< DoFDistributionInfo > spDDInfo)
SmartPtr< MultiGrid > multi_grid ()
returns the multigrid
ConstSmartPtr< MultiGrid > multi_grid () const
~DoFIndexStorage ()
size_t & obj_index (GridObject *obj)
size_t & obj_index (Vertex *vrt)
size_t & obj_index (Edge *ed)
size_t & obj_index (Face *face)
size_t & obj_index (Volume *vol)
const size_t & obj_index (GridObject *obj) const
const size_t & obj_index (Vertex *vrt) const
const size_t & obj_index (Edge *ed) const
const size_t & obj_index (Face *face) const
const size_t & obj_index (Volume *vol) const
Public Member Functions inherited from ug::DoFDistributionInfoProvider
SubsetGroup all_subsets_grp_except_for (const char *names) const
returns subset group of all the subsets except for (by name)
int dim (size_t fct) const
returns the dimension in which solution lives
int dim_subset (int si) const
returns dimension of subset
ConstSmartPtr< DoFDistributionInfo > dof_distribution_info () const
returns underlying info
DoFDistributionInfoProvider ()
constructor
DoFDistributionInfoProvider (ConstSmartPtr< DoFDistributionInfo > spDDI)
constructor
FunctionGroup fct_grp_by_name (const char *names) const
returns a function group to a string of functions
size_t fct_id_by_name (const char *name) const
returns fct id by name
ConstSmartPtr< FunctionPattern > function_pattern () const
returns the function pattern
bool is_def_everywhere (size_t fct) const
returns true if the discrete function nr_fct is defined everywhere
bool is_def_in_subset (size_t fct, int si) const
returns if a function is defined on a subset
size_t max_dofs (const GridBaseObjectId gbo) const
returns the maximum number of dofs on a grid base object type
size_t max_dofs (const GridBaseObjectId gbo, const int si) const
returns the maximum number of dofs on a grid base object on a subset
size_t max_dofs (const int dim) const
returns the maximum number of dofs on grid objects in a dimension
size_t max_dofs (const int dim, const int si) const
returns the maximum number of dofs in a dimension on a subset
size_t max_dofs (const ReferenceObjectID roid) const
returns the maximum number of dofs on reference object type
size_t max_fct_dofs (const size_t fct, const GridBaseObjectId gbo) const
returns the maximal number of dofs on a base object type for a function component
size_t max_fct_dofs (const size_t fct, const GridBaseObjectId gbo, const int si) const
returns the maximum number of dofs on a grid base object on a subset for a function component
size_t max_fct_dofs (const size_t fct, const int dim, const int si) const
returns the maximum number of dofs in a dimension on a subset for a function component
size_t max_fct_dofs (const size_t fct, const ReferenceObjectID roid) const
returns the number of dofs on a reference object for a function component
size_t max_fct_dofs (const size_t fct, int dim) const
returns the maximal number of dofs on a dimension for a function component
std::string name (size_t fct) const
returns the name of the discrete function nr_fct
std::vector< std::string > names () const
returns the names of the discrete functions
size_t num_dofs (const ReferenceObjectID roid, const int si) const
returns the number of dofs on a Reference Object on a subset
size_t num_fct () const
number of discrete functions on subset si
size_t num_fct (int si) const
number of discrete functions on subset si
size_t num_fct_dofs (const size_t fct, const ReferenceObjectID roid, const int si) const
returns the number of dofs on a Reference Object on a subset for a function component
int num_subsets () const
returns number of subsets
size_t offset (const ReferenceObjectID roid, const int si, const size_t fct) const
returns the offset for reference element, subset and function
void print_local_dof_statistic () const
prints statistic on local dof distribution
void print_local_dof_statistic (int verboseLev) const
prints informations
void set_dof_distribution_info (ConstSmartPtr< DoFDistributionInfo > spDDI)
sets the dd info
SubsetGroup subset_grp_by_name (const char *names) const
returns subset group by name
ConstSmartPtr< ISubsetHandler > subset_handler () const
returns the subset handler
int subset_id_by_name (const char *name) const
returns the subset id
std::string subset_name (int si) const
returns subset name
const LFEID & local_finite_element_id (size_t fct) const
const LFEID & lfeid (size_t fct) const
Protected Types
typedef ug::Attachment< size_t > ADoF
Attachment type.
typedef Grid::AttachmentAccessor< Vertex, ADoF > vertex_attachment_accessor_type
typedef Grid::AttachmentAccessor< Edge, ADoF > edge_attachment_accessor_type
typedef Grid::AttachmentAccessor< Face, ADoF > face_attachment_accessor_type
typedef Grid::AttachmentAccessor< Volume, ADoF > volume_attachment_accessor_type
Protected Member Functions
void clear_attachments ()
removes the attachments
void init_attachments ()
initializes the attachments
Protected Attributes
ADoF m_aIndex
SmartPtr< MultiGrid > m_spMG
Multi Grid.
vertex_attachment_accessor_type m_aaIndexVRT
edge_attachment_accessor_type m_aaIndexEDGE
face_attachment_accessor_type m_aaIndexFACE
volume_attachment_accessor_type m_aaIndexVOL
Protected Attributes inherited from ug::DoFDistributionInfoProvider
ConstSmartPtr< DoFDistributionInfo > m_spDDI
Function Pattern.
Member Typedef Documentation
ADoF
typedef ug::Attachment<size_t> ug::DoFIndexStorage::ADoF protected
Attachment type.
edge_attachment_accessor_type
typedef Grid::AttachmentAccessor<Edge, ADoF> ug::DoFIndexStorage::edge_attachment_accessor_type protected
Attachment Accessors
face_attachment_accessor_type
typedef Grid::AttachmentAccessor<Face, ADoF> ug::DoFIndexStorage::face_attachment_accessor_type protected
Attachment Accessors
vertex_attachment_accessor_type
typedef Grid::AttachmentAccessor<Vertex, ADoF> ug::DoFIndexStorage::vertex_attachment_accessor_type protected
Attachment Accessors
volume_attachment_accessor_type
typedef Grid::AttachmentAccessor<Volume, ADoF> ug::DoFIndexStorage::volume_attachment_accessor_type protected
Attachment Accessors
Constructor & Destructor Documentation
DoFIndexStorage()
ug::DoFIndexStorage::DoFIndexStorage (SmartPtr< MultiGrid > spMG, ConstSmartPtr< DoFDistributionInfo > spDDInfo)
References init_attachments().
~DoFIndexStorage()
ug::DoFIndexStorage::~DoFIndexStorage ()
References clear_attachments().
Member Function Documentation
clear_attachments()
void ug::DoFIndexStorage::clear_attachments () protected
removes the attachments
References ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::invalidate(), m_aaIndexEDGE, m_aaIndexFACE, m_aaIndexVOL, m_aaIndexVRT, m_aIndex, multi_grid(), and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid().
Referenced by ~DoFIndexStorage().
init_attachments()
void ug::DoFIndexStorage::init_attachments () protected
initializes the attachments
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::EDGE, ug::FACE, m_aaIndexEDGE, m_aaIndexFACE, m_aaIndexVOL, m_aaIndexVRT, m_aIndex, ug::DoFDistributionInfoProvider::max_dofs(), multi_grid(), ug::VERTEX, and ug::VOLUME.
Referenced by DoFIndexStorage().
multi_grid() [1/2]
SmartPtr<MultiGrid> ug::DoFIndexStorage::multi_grid () inline
returns the multigrid
References m_spMG.
Referenced by clear_attachments(), and init_attachments().
multi_grid() [2/2]
ConstSmartPtr<MultiGrid> ug::DoFIndexStorage::multi_grid () const inline
References m_spMG.
obj_index() [1/10]
size_t& ug::DoFIndexStorage::obj_index (Edge * ed) inline
returns first algebra index of a geometric object
References m_aaIndexEDGE.
obj_index() [2/10]
const size_t& ug::DoFIndexStorage::obj_index (Edge * ed) const inline
const access to first algebra index of a geometric object
References m_aaIndexEDGE.
obj_index() [3/10]
size_t& ug::DoFIndexStorage::obj_index (Face * face) inline
returns first algebra index of a geometric object
References m_aaIndexFACE.
obj_index() [4/10]
const size_t& ug::DoFIndexStorage::obj_index (Face * face) const inline
const access to first algebra index of a geometric object
References m_aaIndexFACE.
obj_index() [5/10]
size_t & ug::DoFIndexStorage::obj_index (GridObject * obj)
returns first algebra index of a geometric object
References ug::GridObject::base_object_id(), ug::EDGE, ug::FACE, UG_THROW, ug::VERTEX, and ug::VOLUME.
Referenced by obj_index().
obj_index() [6/10]
const size_t & ug::DoFIndexStorage::obj_index (GridObject * obj) const
const access to first algebra index of a geometric object
References ug::GridObject::base_object_id(), ug::EDGE, ug::FACE, obj_index(), UG_THROW, ug::VERTEX, and ug::VOLUME.
obj_index() [7/10]
size_t& ug::DoFIndexStorage::obj_index (Vertex * vrt) inline
returns first algebra index of a geometric object
References m_aaIndexVRT.
obj_index() [8/10]
const size_t& ug::DoFIndexStorage::obj_index (Vertex * vrt) const inline
const access to first algebra index of a geometric object
References m_aaIndexVRT.
obj_index() [9/10]
size_t& ug::DoFIndexStorage::obj_index (Volume * vol) inline
returns first algebra index of a geometric object
References m_aaIndexVOL.
obj_index() [10/10]
const size_t& ug::DoFIndexStorage::obj_index (Volume * vol) const inline
const access to first algebra index of a geometric object
References m_aaIndexVOL.
Member Data Documentation
m_aaIndexEDGE
edge_attachment_accessor_type ug::DoFIndexStorage::m_aaIndexEDGE protected
Attachments
Referenced by clear_attachments(), init_attachments(), and obj_index().
m_aaIndexFACE
face_attachment_accessor_type ug::DoFIndexStorage::m_aaIndexFACE protected
Attachments
Referenced by clear_attachments(), init_attachments(), and obj_index().
m_aaIndexVOL
volume_attachment_accessor_type ug::DoFIndexStorage::m_aaIndexVOL protected
Attachments
Referenced by clear_attachments(), init_attachments(), and obj_index().
m_aaIndexVRT
vertex_attachment_accessor_type ug::DoFIndexStorage::m_aaIndexVRT protected
Attachments
Referenced by clear_attachments(), init_attachments(), and obj_index().
m_aIndex
ADoF ug::DoFIndexStorage::m_aIndex protected
Referenced by clear_attachments(), and init_attachments().
m_spMG
SmartPtr<MultiGrid> ug::DoFIndexStorage::m_spMG protected
Multi Grid.
Referenced by multi_grid().
The documentation for this class was generated from the following files:
ugbase/lib_disc/dof_manager/dof_index_storage.h
ugbase/lib_disc/dof_manager/dof_index_storage.cpp