ug4: ug::vrl::VRLCondUserNumber< dim > Class Template Reference
ug::vrl::VRLCondUserNumber< dim > Class Template Reference
Public Member Functions
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool computeDeriv=false)
implement as a UserData
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
bool evaluate (number &c, const MathVector< dim > &x, number time, int si) const
evaluates the data at a given point and time
void releaseGlobalRefs ()
virtual bool requires_grid_fct () const
returns if grid function is needed for evaluation
void set_vrl_callback (const char *expression)
VRLCondUserNumber ()
~VRLCondUserNumber ()
Public Member Functions inherited from ug::StdGlobPosData< VRLCondUserNumber< dim >, number, dim, bool >
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
implement as a UserData
virtual bool constant () const
returns if data is constant
void evaluate (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
virtual bool operator() (number &value, const MathVector< dim > &globIP, number time, int si) const
returns value for a global position
virtual void operator() (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
returns value for global positions
Public Member Functions inherited from ug::StdUserData< TImpl, TData, dim, TRet, TBase >
virtual TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const =0
returns value for a global position
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const =0
returns value for global positions
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
Public Member Functions inherited from ug::CplUserData< TData, dim, void >
bool defined (size_t s, size_t ip) const
returns flag, if data is evaluated (for conditional data)
size_t num_ip (size_t s) const
returns the number of integration points
size_t num_series () const
explicitly forward some functions
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
register external callback, invoked when data storage changed
void unregister_storage_callback (DataImport< TData, dim > *obj)
register all callbacks registered by class
TData & value (size_t s, size_t ip)
returns the value at ip
const TData & value (size_t s, size_t ip) const
returns the value at ip
TData * values (size_t s)
returns all values for a series
const TData * values (size_t s) const
returns all values for a series
~CplUserData ()
destructor
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
returns true iff the time point specification is equal to the current one, or not specified
virtual void check_setup () const
returns if the dependent data is ready for evaluation
void clear ()
clear all data
int dim_local_ips () const
returns current local ip dimension
ICplUserData ()
default constructor
const MathVector< dim > & ip (size_t s, size_t ip) const
returns global ip
const MathVector< dim > * ips (size_t s) const
returns global ips
template<int ldim>
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
returns local ip
template<int ldim>
const MathVector< ldim > * local_ips (size_t s) const
returns local ips
virtual SmartPtr< ICplUserData > needed_data (size_t i)
return needed data
size_t num_ip (size_t s) const
returns the number of integration points
virtual size_t num_needed_data () const
number of other Data this data depends on
size_t num_series () const
returns the number of ip series
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
set local positions without the specification of the time point, returns series id
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
set local positions, returns series id
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
set global positions
template<int ldim>
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
sets new local ip positions for a local ip series
void set_subset (int si)
set the subset of evaluation
void set_time_point (const size_t seriesId, const int timePointSpec)
sets a new time point for a local ip series
void set_time_point (size_t timePoint)
sets the current time point
void set_times (const std::vector< number > &vTime)
set evaluation time
int subset () const
returns the subset of evaluation
number time () const
get the current evaluation time
number time (size_t s) const
get the specified evaluation time
size_t time_point ()
returns the current time point
size_t time_point (size_t s) const
returns the time point specification (in particular, the current one, if the own one not specified)
int time_point_specification (size_t s) const
returns the time point specification (note: it may be -1, i.e. not specified)
virtual void update_dof_sizes (const LocalIndices &ind)
resize arrays
virtual bool zero_derivative () const
returns if data depends on solution
virtual ~ICplUserData ()
virtual desctructor
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
Function Group of functions.
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
sets the function pattern for a possibly needed grid function
virtual ~UserDataInfo ()
virtual destructor
Public Member Functions inherited from ug::UserData< TData, dim, void >
int get_dim () const
returns dimension
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, Vertex *vrt) const
returns a value at a vertex
std::string type () const
returns type of data as string (e.g. "Number", "Vector", "Matrix")
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
Static Public Member Functions
static std::string group_name ()
static std::string name ()
static std::string params ()
Protected Member Functions
jobject compileCondUserDataString (JNIEnv *env, const char *s) const
jdouble condData2Boolean (JNIEnv *env, jobject obj) const
jdouble condData2Double (JNIEnv *env, jobject obj) const
jclass getCondUserDataClass (JNIEnv *env) const
jmethodID getCondUserDataRunMethod (JNIEnv *env, jclass cls) const
Protected Member Functions inherited from ug::StdGlobPosData< VRLCondUserNumber< dim >, number, dim, bool >
VRLCondUserNumber< dim > & getImpl ()
access to implementation
const VRLCondUserNumber< dim > & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::StdUserData< TImpl, TData, dim, TRet, TBase >
TImpl & getImpl ()
access to implementation
const TImpl & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::CplUserData< TData, dim, void >
void call_storage_callback () const
calls are registered external storage callbacks
void check_series (size_t s) const
checks in debug mode the correct index
void check_series_ip (size_t s, size_t ip) const
checks in debug mode the correct index
virtual void local_ip_series_added (const size_t seriesID)
resizes the data field, when local ip changed signaled
virtual void local_ip_series_to_be_cleared ()
free the data field memory and set series to zero
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
implement callback, called when local IPs changed
virtual void value_storage_changed (const size_t seriesID)
callback, invoked when storage of data has changed for a series
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
checks in debug mode the correct usage of indices
void check_s_ip (size_t s, size_t ip) const
checks in debug mode the correct usage of indices
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
help function to get local ips
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
callback invoked after global ips have been changed
Private Attributes
bool initialized
std::string invocationErrorMsg
jmethodID runMethod
jclass userDataClass
jobject userDataObject
Additional Inherited Members
Public Types inherited from ug::CplUserData< TData, dim, void >
typedef ICplUserData< dim > base_type
type of base class
Public Types inherited from ug::UserData< TData, dim, void >
typedef TData data_type
typedef void return_type
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
default time point (or -1 if not specified)
int m_locPosDim
dimension of local position (-1 indicates no dim set)
std::vector< const MathVector< 1 > * > m_pvLocIP1d
local ips of dimension 1d-3d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
subset for evaluation
size_t m_timePoint
current time point (used if no explicit specification for series)
std::vector< bool > m_vMayChange
flags if local ips may change
std::vector< size_t > m_vNumIP
number of evaluation points (-1 indicates no ips set)
std::vector< number > m_vTime
time for evaluation
std::vector< int > m_vTimePoint
time points for the series
std::vector< const MathVector< dim > * > m_vvGlobPos
global ips
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Constructor & Destructor Documentation
VRLCondUserNumber()
template<int dim> ug::vrl::VRLCondUserNumber< dim >::VRLCondUserNumber () inline
References dim, and ug::vrl::VRLCondUserNumber< dim >::invocationErrorMsg.
~VRLCondUserNumber()
template<int dim> ug::vrl::VRLCondUserNumber< dim >::~VRLCondUserNumber () inline
References ug::vrl::VRLCondUserNumber< dim >::releaseGlobalRefs().
Member Function Documentation
compileCondUserDataString()
template<int dim> jobject ug::vrl::VRLCondUserNumber< dim >::compileCondUserDataString (JNIEnv * env, const char * s) const inline protected
References ug::vrl::VRLCondUserNumber< dim >::runMethod, s, and ug::vrl::stringC2J().
Referenced by ug::vrl::VRLCondUserNumber< dim >::set_vrl_callback().
compute()
template<int dim> virtual void ug::vrl::VRLCondUserNumber< dim >::compute (LocalVector * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) inline virtual
implement as a UserData
Reimplemented from ug::StdGlobPosData< VRLCondUserNumber< dim >, number, dim, bool >.
References ug::ICplUserData< dim >::ip(), ug::CplUserData< TData, dim, void >::num_ip(), ug::CplUserData< TData, dim, void >::num_series(), ug::StdGlobPosData< VRLCondUserNumber< dim >, number, dim, bool >::operator()(), s, ug::ICplUserData< dim >::subset(), ug::ICplUserData< dim >::time(), and ug::CplUserData< TData, dim, void >::value().
condData2Boolean()
template<int dim> jdouble ug::vrl::VRLCondUserNumber< dim >::condData2Boolean (JNIEnv * env, jobject obj) const inline protected
Referenced by ug::vrl::VRLCondUserNumber< dim >::evaluate().
condData2Double()
template<int dim> jdouble ug::vrl::VRLCondUserNumber< dim >::condData2Double (JNIEnv * env, jobject obj) const inline protected
Referenced by ug::vrl::VRLCondUserNumber< dim >::evaluate().
continuous()
template<int dim> virtual bool ug::vrl::VRLCondUserNumber< dim >::continuous () const inline virtual
returns if provided data is continuous over geometric object boundaries
Reimplemented from ug::StdGlobPosData< VRLCondUserNumber< dim >, number, dim, bool >.
evaluate()
template<int dim> bool ug::vrl::VRLCondUserNumber< dim >::evaluate (number & c, const MathVector< dim > & x, number time, int si) const inline
evaluates the data at a given point and time
References ug::vrl::checkException(), ug::vrl::VRLCondUserNumber< dim >::condData2Boolean(), ug::vrl::VRLCondUserNumber< dim >::condData2Double(), ug::vrl::ConvertParametersToJava(), ug::vrl::threading::getEnv(), ug::vrl::getJavaVM(), ug::vrl::VRLCondUserNumber< dim >::invocationErrorMsg, ug::vrl::VRLCondUserNumber< dim >::params(), ug::vrl::VRLCondUserNumber< dim >::runMethod, ug::ICplUserData< dim >::time(), and ug::vrl::VRLCondUserNumber< dim >::userDataObject.
getCondUserDataClass()
template<int dim> jclass ug::vrl::VRLCondUserNumber< dim >::getCondUserDataClass (JNIEnv * env) const inline protected
Referenced by ug::vrl::VRLCondUserNumber< dim >::set_vrl_callback().
getCondUserDataRunMethod()
template<int dim> jmethodID ug::vrl::VRLCondUserNumber< dim >::getCondUserDataRunMethod (JNIEnv * env, jclass cls) const inline protected
References ug::vrl::checkException(), and UG_LOG.
Referenced by ug::vrl::VRLCondUserNumber< dim >::set_vrl_callback().
group_name()
template<int dim> static std::string ug::vrl::VRLCondUserNumber< dim >::group_name () inline static
References name.
name()
template<int dim> static std::string ug::vrl::VRLCondUserNumber< dim >::name () inline static
References dim, and name.
params()
template<int dim> static std::string ug::vrl::VRLCondUserNumber< dim >::params () inline static
References dim.
Referenced by ug::vrl::VRLCondUserNumber< dim >::evaluate().
releaseGlobalRefs()
template<int dim> void ug::vrl::VRLCondUserNumber< dim >::releaseGlobalRefs () inline
References ug::vrl::threading::getEnv(), ug::vrl::getJavaVM(), ug::vrl::VRLCondUserNumber< dim >::initialized, ug::vrl::VRLCondUserNumber< dim >::userDataClass, and ug::vrl::VRLCondUserNumber< dim >::userDataObject.
Referenced by ug::vrl::VRLCondUserNumber< dim >::set_vrl_callback(), and ug::vrl::VRLCondUserNumber< dim >::~VRLCondUserNumber().
requires_grid_fct()
template<int dim> virtual bool ug::vrl::VRLCondUserNumber< dim >::requires_grid_fct () const inline virtual
returns if grid function is needed for evaluation
Reimplemented from ug::StdGlobPosData< VRLCondUserNumber< dim >, number, dim, bool >.
set_vrl_callback()
template<int dim> void ug::vrl::VRLCondUserNumber< dim >::set_vrl_callback (const char * expression) inline
References ug::vrl::VRLCondUserNumber< dim >::compileCondUserDataString(), ug::vrl::VRLCondUserNumber< dim >::getCondUserDataClass(), ug::vrl::VRLCondUserNumber< dim >::getCondUserDataRunMethod(), ug::vrl::threading::getEnv(), ug::vrl::getJavaVM(), ug::vrl::VRLCondUserNumber< dim >::initialized, ug::vrl::VRLCondUserNumber< dim >::releaseGlobalRefs(), ug::vrl::VRLCondUserNumber< dim >::runMethod, ug::vrl::VRLCondUserNumber< dim >::userDataClass, and ug::vrl::VRLCondUserNumber< dim >::userDataObject.
Member Data Documentation
initialized
template<int dim> bool ug::vrl::VRLCondUserNumber< dim >::initialized private
Referenced by ug::vrl::VRLCondUserNumber< dim >::releaseGlobalRefs(), and ug::vrl::VRLCondUserNumber< dim >::set_vrl_callback().
invocationErrorMsg
template<int dim> std::string ug::vrl::VRLCondUserNumber< dim >::invocationErrorMsg private
Referenced by ug::vrl::VRLCondUserNumber< dim >::evaluate(), and ug::vrl::VRLCondUserNumber< dim >::VRLCondUserNumber().
runMethod
template<int dim> jmethodID ug::vrl::VRLCondUserNumber< dim >::runMethod private
Referenced by ug::vrl::VRLCondUserNumber< dim >::compileCondUserDataString(), ug::vrl::VRLCondUserNumber< dim >::evaluate(), and ug::vrl::VRLCondUserNumber< dim >::set_vrl_callback().
userDataClass
template<int dim> jclass ug::vrl::VRLCondUserNumber< dim >::userDataClass private
Referenced by ug::vrl::VRLCondUserNumber< dim >::releaseGlobalRefs(), and ug::vrl::VRLCondUserNumber< dim >::set_vrl_callback().
userDataObject
template<int dim> jobject ug::vrl::VRLCondUserNumber< dim >::userDataObject private
Referenced by ug::vrl::VRLCondUserNumber< dim >::evaluate(), ug::vrl::VRLCondUserNumber< dim >::releaseGlobalRefs(), and ug::vrl::VRLCondUserNumber< dim >::set_vrl_callback().
The documentation for this class was generated from the following file:
ugbase/bindings/vrl/user_data.cpp