ug4: ug::EdgeVertices Class Reference
ug::EdgeVertices Class Reference
holds the vertices of an Edge or an EdgeDescriptor.
#include <grid_base_objects.h>
Public Member Functions
virtual size_t num_vertices () const
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual Vertex * vertex (size_t index) const
virtual ConstVertexArray vertices () const
virtual ~EdgeVertices ()
Public Member Functions inherited from ug::IVertexGroup
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~IVertexGroup ()
Protected Member Functions
void assign_edge_vertices (const EdgeVertices &ev)
Protected Attributes
Vertex * m_vertices [2]
Friends
class Grid
Additional Inherited Members
Public Types inherited from ug::IVertexGroup
typedef Vertex *const * ConstVertexArray
Detailed Description
holds the vertices of an Edge or an EdgeDescriptor.
Constructor & Destructor Documentation
~EdgeVertices()
virtual ug::EdgeVertices::~EdgeVertices () inline virtual
Member Function Documentation
assign_edge_vertices()
void ug::EdgeVertices::assign_edge_vertices (const EdgeVertices & ev) inline protected
References m_vertices.
Referenced by ug::EdgeDescriptor::EdgeDescriptor(), and ug::EdgeDescriptor::operator=().
num_vertices()
virtual size_t ug::EdgeVertices::num_vertices () const inline virtual
Implements ug::IVertexGroup.
Referenced by ug::grid_unit_tests::CheckAssociatedVolumesOfEdges(), ug::CheckElementConsistency(), ug::CollectVertices(), ug::ExportGridToTIKZ(), ug::Grid::get_associated(), ug::Grid::get_associated_sorted(), ug::NumVertices(), ug::ProlongateP1(), ug::MGHNodeAdjuster::ref_marks_changed(), and ug::SmoothProjector::refinement_ends().
operator[]()
Vertex* ug::EdgeVertices::operator[] (size_t index) const inline
returns the i-th vertex.
size()
size_t ug::EdgeVertices::size () const inline
returns the number of vertices.
vertex()
virtual Vertex* ug::EdgeVertices::vertex (size_t index) const inline virtual
Implements ug::IVertexGroup.
Referenced by ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::Grid::assign_grid(), ug::AssignCreaseVertices(), ug::AssignFixedVertices(), ug::AssignInnerAndBoundarySubsets(), ug::CalculateAngles(), ug::CalculateAverageCurvature(), ug::CalculateBoundaryVertexNormal2D(), ug::CalculateCenter(), ug::CalculateCreaseNormal(), ug::CalculateMaxAngle(), ug::CalculateMaxDihedral(), ug::CalculateMinAngle(), ug::CalculateMinDihedral(), ug::CalculateNormal(), ug::CalculateNormalNoNormalize(), ug::CalculateNumManifoldEdgesVertexAttachmentInParentLevel(), ug::CalculateOuterNormal(), ug::CalculateSmoothManifoldPosInParentLevelButterflyScheme(), ug::CheckElementConsistency(), ug::CheckHangingNodeConsistency(), ug::CollapseEdge(), ug::CollectAssociatedSides(), ug::CollectFaces(), ug::CollectNeighbors(), ug::CollectVertices(), ug::CollectVolumes(), ug::CompareVertices(), ug::ConstrainedEdge::ConstrainedEdge(), ug::ConstrainingEdge::ConstrainingEdge(), ug::ContainsPoint(), ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_2d(), ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_3d(), ug::CreateEdgeSplitGeometry(), ug::CreatePolyChain(), ug::CutEdgesWithPlane(), ug::DistributeExpansionMarks3D(), ug::Duplicate(), ug::EdgeCollapseIsValid(), ug::EdgeContains(), ug::EdgeLength(), ug::EdgeLengthSq(), ug::EdgeOrientation< TDomain >::elem_evaluate(), ug::DistributedGridManager::end_element_deletion(), ug::EraseConnectingElements(), ug::ExportGridToTIKZ(), ug::ExportGridToUG_2D(), ug::Extrude(), ug::ExtrudeLayers(), ug::Grid::face_autogenerate_edges(), ug::FaceIsOnRightSide(), ug::FixEdgeOrientation(), ug::Grid::flip_orientation(), ug::Grid::get_edge(), ug::DegeneratedLayerManager< dim >::get_layer_sides(), ug::Grid::get_side(), ug::GetAssociatedFaces(), ug::GetConnectedVertex(), ug::GetConnectedVertexIndex(), ug::GetFirstSectionOfPolyChain(), ug::GetVertex(), ug::GetVertexIndex(), ug::HashKey(), ug::DelaunayInfo< TAAPos >::init_marks(), ug::InsertCenterVertex(), ug::LoadGridFromART(), ug::MakeDelaunay(), ug::MarkAnisotropicOnlyX(), ug::MarkForRefinement_AnisotropicDirection(), ug::MarkForRefinementByDirection(), ug::MergeGrids(), ug::MergeVertices(), ug::MinimizeEdgeLength_SwapsOnly(), ug::MultiEdgeSplit(), ug::CylinderCutProjector::new_vertex(), ug::PlaneCutProjector::new_vertex(), ug::SubdivisionProjector::new_vertex(), ug::NumAssociatedFaces(), ug::ObtainSimpleGrid_CollapseEdge(), ug::ConnectedToOneMarkedVrt::operator()(), ug::OrientationMatches(), ug::GlobalFracturedMediaRefiner::perform_refinement(), ug::GlobalMultiGridRefiner::perform_refinement(), ug::PerformCollapses(), ug::PerformSplits(), ug::ProjectToLimitLoop(), ug::ProjectVerticesToCloseEdges(), ug::ProlongateP1(), ug::QualityGridGeneration(), ug::RayElementIntersection(), ug::HorizontalAnisotropyAdjuster< TAPos >::ref_marks_changed(), ug::MGHNodeAdjuster::ref_marks_changed(), ug::StdHNodeAdjuster::ref_marks_changed(), ug::RegularEdge::refine(), ug::ConstrainedEdge::refine(), ug::ConstrainingEdge::refine(), ug::HangingNodeRefinerBase< TSelector >::refine_edge_with_hanging_vertex(), ug::SmoothProjector::refinement_ends(), ug::Grid::register_and_replace_element(), ug::Grid::register_edge(), ug::Grid::register_face(), ug::Grid::register_volume(), ug::RegularEdge::RegularEdge(), ug::Grid::replace_vertex(), ug::ResolveEdgeEdgeIntersection(), ug::ResolveEdgeFaceIntersection(), ug::ResolveVertexEdgeIntersection(), ug::ResolveVertexFaceIntersection(), ug::SaveGridToART(), ug::SelectInnerSelectionVertices(), ug::SelectShortPolychains(), ug::SerializeGridElements(), ug::SerializeMultiGridElements(), ug::SimplifyPolylines(), ug::SlopeSmooth(), ug::SwapEdge(), ug::TriangleFill_SweepLine(), ug::TryCollapse(), ug::TrySplit(), ug::TrySwap(), ug::Grid::unregister_edge(), ug::Grid::vertex_store_associated_edges(), ug::Grid::volume_autogenerate_edges(), ug::WeightedFaceSmooth(), ug::WriteEdges(), and ug::WriteLGM().
vertices()
virtual ConstVertexArray ug::EdgeVertices::vertices () const inline virtual
Implements ug::IVertexGroup.
Referenced by ug::grid_unit_tests::CheckAssociatedVolumesOfEdges(), ug::Grid::get_associated(), ug::Grid::get_associated_sorted(), ug::GetMaxEdgeLength(), ug::DelaunayInfo< TAAPos >::is_dart_segment(), ug::DelaunayInfo< TAAPos >::is_dart_shell_segment(), and ug::DelaunayInfo< TAAPos >::is_new_dart_segment().
Friends And Related Function Documentation
Grid
friend class Grid friend
Member Data Documentation
m_vertices
Vertex* ug::EdgeVertices::m_vertices[2] protected
Referenced by assign_edge_vertices(), ug::EdgeDescriptor::EdgeDescriptor(), ug::Grid::flip_orientation(), and ug::Edge::get_opposing_side().
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/grid_base_objects.h