ug4: ug::RasterLayersProjector Class Reference
ug::RasterLayersProjector Class Reference
#include <raster_layers_projector.h>
Public Types
typedef Grid::VertexAttachmentAccessor< ANumber > rel_z_attachment_accessor_t
typedef ANumber rel_z_attachment_t
Public Member Functions
template<class TElem >
number average_rel_z (TElem *e) const
number average_rel_z (Vertex *e) const
virtual number new_vertex (Vertex *vrt, Edge *parent)
called when a new vertex was created from an old edge.
virtual number new_vertex (Vertex *vrt, Face *parent)
called when a new vertex was created from an old face.
virtual number new_vertex (Vertex *vrt, Vertex *parent)
called when a new vertex was created from an old vertex.
virtual number new_vertex (Vertex *vrt, Volume *parent)
called when a new vertex was created from an old volume.
RasterLayersProjector ()
RasterLayersProjector (SPIGeometry3d geometry)
RasterLayersProjector (SPIGeometry3d geometry, SPRasterLayers layers)
rel_z_attachment_t rel_z_attachment () const
rel_z_attachment_accessor_t rel_z_attachment_accessor () const
void set_geometry (SPIGeometry3d g)
void set_layers (SPRasterLayers layers)
Public Member Functions inherited from ug::RefinementProjector
virtual SPIGeometry3d geometry () const
virtual void refinement_begins (const ISubGrid *sg)
called before refinement begins
virtual bool refinement_begins_requires_subgrid () const
virtual void refinement_ends ()
called when refinement is done
RefinementProjector ()
RefinementProjector (SPElementCallback cb)
RefinementProjector (SPIGeometry3d geometry)
RefinementProjector (SPIGeometry3d geometry, SPElementCallback concernedElems)
virtual void set_concerned_elements (SPElementCallback cb)
virtual ~RefinementProjector ()
Private Member Functions
void add_attachments ()
template<class TParent >
number new_vertex_impl (Vertex *vrt, TParent *parent)
void remove_attachments ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
rel_z_attachment_accessor_t m_aaRelZ
rel_z_attachment_t m_aRelZ
SPRasterLayers m_layers
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from ug::RefinementProjector
IGeometry3d & geom ()
const IGeometry3d & geom () const
template<class TElem >
bool is_concerned (TElem *e)
vector3 pos (Vertex *v) const
void set_pos (Vertex *v, const vector3 &p)
Member Typedef Documentation
rel_z_attachment_accessor_t
typedef Grid::VertexAttachmentAccessor<ANumber> ug::RasterLayersProjector::rel_z_attachment_accessor_t
rel_z_attachment_t
typedef ANumber ug::RasterLayersProjector::rel_z_attachment_t
Constructor & Destructor Documentation
RasterLayersProjector() [1/3]
ug::RasterLayersProjector::RasterLayersProjector () inline
RasterLayersProjector() [2/3]
ug::RasterLayersProjector::RasterLayersProjector (SPIGeometry3d geometry) inline
References add_attachments().
RasterLayersProjector() [3/3]
ug::RasterLayersProjector::RasterLayersProjector (SPIGeometry3d geometry, SPRasterLayers layers) inline
References add_attachments(), and set_layers().
Member Function Documentation
add_attachments()
void ug::RasterLayersProjector::add_attachments () inline private
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::Grid::attach_to_vertices(), ug::RefinementProjector::geom(), ug::IGeometry< dim >::grid(), ug::Grid::has_attachment(), ug::GlobalAttachments::is_declared(), m_aaRelZ, and m_aRelZ.
Referenced by RasterLayersProjector(), and set_geometry().
average_rel_z() [1/2]
template<class TElem > number ug::RasterLayersProjector::average_rel_z (TElem * e) const inline
References m_aaRelZ.
average_rel_z() [2/2]
number ug::RasterLayersProjector::average_rel_z (Vertex * e) const inline
References m_aaRelZ.
Referenced by new_vertex_impl().
new_vertex() [1/4]
virtual number ug::RasterLayersProjector::new_vertex (Vertex * vrt, Edge * parent) inline virtual
called when a new vertex was created from an old edge.
Reimplemented from ug::RefinementProjector.
References new_vertex_impl().
new_vertex() [2/4]
virtual number ug::RasterLayersProjector::new_vertex (Vertex * vrt, Face * parent) inline virtual
called when a new vertex was created from an old face.
Reimplemented from ug::RefinementProjector.
References new_vertex_impl().
new_vertex() [3/4]
virtual number ug::RasterLayersProjector::new_vertex (Vertex * vrt, Vertex * parent) inline virtual
called when a new vertex was created from an old vertex.
Reimplemented from ug::RefinementProjector.
References m_aaRelZ, ug::RefinementProjector::pos(), and ug::RefinementProjector::set_pos().
new_vertex() [4/4]
virtual number ug::RasterLayersProjector::new_vertex (Vertex * vrt, Volume * parent) inline virtual
called when a new vertex was created from an old volume.
Reimplemented from ug::RefinementProjector.
References new_vertex_impl().
new_vertex_impl()
template<class TParent > number ug::RasterLayersProjector::new_vertex_impl (Vertex * vrt, TParent * parent) inline private
References average_rel_z(), ug::IGeometry< dim >::element_center(), ug::RefinementProjector::geom(), m_aaRelZ, m_layers, and ug::RefinementProjector::set_pos().
Referenced by new_vertex().
rel_z_attachment()
rel_z_attachment_t ug::RasterLayersProjector::rel_z_attachment () const inline
References m_aRelZ.
rel_z_attachment_accessor()
rel_z_attachment_accessor_t ug::RasterLayersProjector::rel_z_attachment_accessor () const inline
References m_aaRelZ.
remove_attachments()
void ug::RasterLayersProjector::remove_attachments () inline private
References ug::Grid::detach_from_vertices(), ug::RefinementProjector::geom(), ug::RefinementProjector::geometry(), ug::IGeometry< dim >::grid(), ug::Grid::has_vertex_attachment(), ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::invalidate(), m_aaRelZ, and m_aRelZ.
Referenced by set_geometry().
serialize()
template<class Archive > void ug::RasterLayersProjector::serialize (Archive & ar, const unsigned int version) inline private
References ug::AT_DATA, ug::AT_GUI, SmartPtr< T, FreePolicy >::invalid(), m_layers, make_sp(), and UG_EMPTY_BASE_CLASS_SERIALIZATION.
set_geometry()
void ug::RasterLayersProjector::set_geometry (SPIGeometry3d g) inline virtual
Reimplemented from ug::RefinementProjector.
References add_attachments(), ug::RefinementProjector::geometry(), remove_attachments(), and ug::RefinementProjector::set_geometry().
set_layers()
void ug::RasterLayersProjector::set_layers (SPRasterLayers layers) inline
References m_layers.
Referenced by RasterLayersProjector().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_aaRelZ
rel_z_attachment_accessor_t ug::RasterLayersProjector::m_aaRelZ private
Referenced by add_attachments(), average_rel_z(), new_vertex(), new_vertex_impl(), rel_z_attachment_accessor(), and remove_attachments().
m_aRelZ
rel_z_attachment_t ug::RasterLayersProjector::m_aRelZ private
Referenced by add_attachments(), rel_z_attachment(), and remove_attachments().
m_layers
SPRasterLayers ug::RasterLayersProjector::m_layers private
Referenced by new_vertex_impl(), serialize(), and set_layers().
The documentation for this class was generated from the following file:
ugbase/lib_grid/refinement/projectors/raster_layers_projector.h