ug4: ug::DebugWriterContext Class Reference
ug::DebugWriterContext Class Reference
Context of a debugger writer: Keeps the debugging section etc.
#include <debug_writer.h>
Public Member Functions
void compose_file_path (std::string &path)
composes the path for the files and creates the intermediate directories (up to the base one):
DebugWriterContext ()
constructor
void enter_section (const char *secDir)
enter a new debugging section
std::string get_base_dir ()
void leave_section ()
leave the current debugging section
void print_message (const char *msg)
prints a message
void set_base_dir (const char *const baseDir)
set the base directory for output files (.vec and .mat)
Protected Attributes
std::string m_baseDir
base directory for the debugging output
std::vector< std::string > m_secDir
debuging section subdirectories
Detailed Description
Context of a debugger writer: Keeps the debugging section etc.
Constructor & Destructor Documentation
DebugWriterContext()
ug::DebugWriterContext::DebugWriterContext () inline
constructor
Member Function Documentation
compose_file_path()
void ug::DebugWriterContext::compose_file_path (std::string & path) inline
composes the path for the files and creates the intermediate directories (up to the base one):
References ug::CreateDirectory(), ug::FileExists(), get_base_dir(), m_secDir, and UG_WARNING.
enter_section()
void ug::DebugWriterContext::enter_section (const char * secDir) inline
enter a new debugging section
References m_secDir.
get_base_dir()
std::string ug::DebugWriterContext::get_base_dir () inline
References m_baseDir.
Referenced by compose_file_path().
leave_section()
void ug::DebugWriterContext::leave_section () inline
leave the current debugging section
References m_secDir.
print_message()
void ug::DebugWriterContext::print_message (const char * msg) inline
prints a message
References m_secDir, and UG_LOG.
set_base_dir()
void ug::DebugWriterContext::set_base_dir (const char *const baseDir) inline
set the base directory for output files (.vec and .mat)
References m_baseDir.
Member Data Documentation
m_baseDir
std::string ug::DebugWriterContext::m_baseDir protected
base directory for the debugging output
Referenced by get_base_dir(), and set_base_dir().
m_secDir
std::vector<std::string> ug::DebugWriterContext::m_secDir protected
debuging section subdirectories
Referenced by compose_file_path(), enter_section(), leave_section(), and print_message().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/debug_writer.h