ug4: ug::vrl::VRLUserLinker< TData, dim, TDataIn > Class Template Reference
ug::vrl::VRLUserLinker< TData, dim, TDataIn > Class Template Reference
Public Types
typedef StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim > base_type
type of base class
Public Types inherited from ug::CplUserData< TData, dim, void >
typedef ICplUserData< dim > base_type
type of base class
Public Types inherited from ug::UserData< TData, dim, void >
typedef TData data_type
typedef void return_type
Public Member Functions
template<int refDim>
void eval_and_deriv (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, bool bDeriv, int s, std::vector< std::vector< TData > > vvvDeriv[], const MathMatrix< refDim, dim > *vJT=NULL)
void eval_deriv (TData &value, const std::vector< TDataIn > &dataIn, const MathVector< dim > &x, number time, int si, size_t arg) const
evaluates the data at a given point and time
void eval_value (TData &value, const std::vector< TDataIn > &dataIn, const MathVector< dim > &x, number time, int si) const
evaluates the data at a given point and time
void evaluate (TData &value, const MathVector< dim > &globIP, number time, int si) const
template<int refDim>
void evaluate (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
size_t num_args () const
void releaseGlobalRefs ()
void set_input (size_t i, SmartPtr< CplUserData< TDataIn, dim > > data)
void set_vrl_deriv_callback (size_t arg, const char *expression)
sets the vrl function used to compute the derivative
void set_vrl_value_callback (const char *expression, size_t numArgs)
const char * vrl_deriv_callback (size_t arg)
const char * vrl_value_callback ()
VRLUserLinker ()
~VRLUserLinker ()
Public Member Functions inherited from ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >
virtual void check_setup () const
returns if data is ok
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
compute values (and derivatives iff compDeriv == true)
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
compute values (and derivatives iff compDeriv == true, but only for the 'current' time point)
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
void evaluate (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
virtual SmartPtr< ICplUserData< dim > > needed_data (size_t i)
return needed data
virtual size_t num_input () const
number of inputs
virtual size_t num_needed_data () const
number of other Data this data depends on
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const
returns value for a global position
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
returns value for global positions
virtual bool requires_grid_fct () const
returns that a grid function is needed for evaluation
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
updates the function group
virtual void set_input (size_t i, SmartPtr< ICplUserData< dim > > input, SmartPtr< UserDataInfo > info)
sets an input
void set_num_input (size_t num)
sets the number of inputs
virtual bool zero_derivative () const
returns if derivative is zero
bool zero_derivative (size_t i) const
returns if the derivative of the i'th input is zero
Public Member Functions inherited from ug::StdUserData< TImpl, TData, dim, TRet, TBase >
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
Public Member Functions inherited from ug::CplUserData< TData, dim, void >
bool defined (size_t s, size_t ip) const
returns flag, if data is evaluated (for conditional data)
size_t num_ip (size_t s) const
returns the number of integration points
size_t num_series () const
explicitly forward some functions
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
register external callback, invoked when data storage changed
void unregister_storage_callback (DataImport< TData, dim > *obj)
register all callbacks registered by class
TData & value (size_t s, size_t ip)
returns the value at ip
const TData & value (size_t s, size_t ip) const
returns the value at ip
TData * values (size_t s)
returns all values for a series
const TData * values (size_t s) const
returns all values for a series
~CplUserData ()
destructor
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
returns true iff the time point specification is equal to the current one, or not specified
void clear ()
clear all data
virtual bool constant () const
returns if data is constant
int dim_local_ips () const
returns current local ip dimension
ICplUserData ()
default constructor
const MathVector< dim > & ip (size_t s, size_t ip) const
returns global ip
const MathVector< dim > * ips (size_t s) const
returns global ips
template<int ldim>
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
returns local ip
template<int ldim>
const MathVector< ldim > * local_ips (size_t s) const
returns local ips
size_t num_ip (size_t s) const
returns the number of integration points
size_t num_series () const
returns the number of ip series
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
set local positions without the specification of the time point, returns series id
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
set local positions, returns series id
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
set global positions
template<int ldim>
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
sets new local ip positions for a local ip series
void set_subset (int si)
set the subset of evaluation
void set_time_point (const size_t seriesId, const int timePointSpec)
sets a new time point for a local ip series
void set_time_point (size_t timePoint)
sets the current time point
void set_times (const std::vector< number > &vTime)
set evaluation time
int subset () const
returns the subset of evaluation
number time () const
get the current evaluation time
number time (size_t s) const
get the specified evaluation time
size_t time_point ()
returns the current time point
size_t time_point (size_t s) const
returns the time point specification (in particular, the current one, if the own one not specified)
int time_point_specification (size_t s) const
returns the time point specification (note: it may be -1, i.e. not specified)
virtual void update_dof_sizes (const LocalIndices &ind)
resize arrays
virtual ~ICplUserData ()
virtual desctructor
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
Function Group of functions.
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual ~UserDataInfo ()
virtual destructor
Public Member Functions inherited from ug::UserData< TData, dim, void >
int get_dim () const
returns dimension
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, Vertex *vrt) const
returns a value at a vertex
std::string type () const
returns type of data as string (e.g. "Number", "Vector", "Matrix")
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
Static Public Member Functions
static std::string group_name ()
static std::string name ()
Static Public Attributes
static const unsigned int retArrayDim = vrl_traits<TData>::retArrayDim
Protected Member Functions
void set_num_input (size_t num)
set number of needed inputs
Protected Member Functions inherited from ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >
void eval_deriv (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
void eval_deriv (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
VRLUserLinker< TData, dim, TDataIn > & getImpl ()
access to implementation
const VRLUserLinker< TData, dim, TDataIn > & getImpl () const
const access to implementation
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
forwards the global positions to the data inputs
size_t input_common_fct (size_t i, size_t fct) const
returns the number in the common FctGrp for a fct of an input
size_t input_num_fct (size_t i) const
returns number of functions the input depends on
virtual void local_ip_series_added (const size_t seriesID)
requests series id's from input data
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
forwards the local positions to the data inputs
size_t series_id (size_t i, size_t s) const
returns the series id set for the i'th input
Protected Member Functions inherited from ug::StdUserData< TImpl, TData, dim, TRet, TBase >
TImpl & getImpl ()
access to implementation
const TImpl & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::CplUserData< TData, dim, void >
void call_storage_callback () const
calls are registered external storage callbacks
void check_series (size_t s) const
checks in debug mode the correct index
void check_series_ip (size_t s, size_t ip) const
checks in debug mode the correct index
virtual void local_ip_series_to_be_cleared ()
free the data field memory and set series to zero
virtual void value_storage_changed (const size_t seriesID)
callback, invoked when storage of data has changed for a series
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
checks in debug mode the correct usage of indices
void check_s_ip (size_t s, size_t ip) const
checks in debug mode the correct usage of indices
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
help function to get local ips
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
Static Protected Member Functions
static jobject compileUserDataString (JNIEnv *env, const char *s)
static jclass getUserDataClass (JNIEnv *env)
static jmethodID getUserDataRunMethod (JNIEnv *env, jclass cls)
Protected Attributes
std::vector< SmartPtr< DependentUserData< TDataIn, dim > > > m_vpDependData
data input casted to dependend data
std::vector< SmartPtr< CplUserData< TDataIn, dim > > > m_vpUserData
data input
Protected Attributes inherited from ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >
std::vector< FunctionIndexMapping > m_vMap
Function mapping for each input relative to common FunctionGroup.
std::vector< SmartPtr< ICplUserData< dim > > > m_vspICplUserData
data input
std::vector< SmartPtr< UserDataInfo > > m_vspUserDataInfo
data input casted to IDependend data
std::vector< std::vector< size_t > > m_vvSeriesID
series id the linker uses to get data from input
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
default time point (or -1 if not specified)
int m_locPosDim
dimension of local position (-1 indicates no dim set)
std::vector< const MathVector< 1 > * > m_pvLocIP1d
local ips of dimension 1d-3d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
subset for evaluation
size_t m_timePoint
current time point (used if no explicit specification for series)
std::vector< bool > m_vMayChange
flags if local ips may change
std::vector< size_t > m_vNumIP
number of evaluation points (-1 indicates no ips set)
std::vector< number > m_vTime
time for evaluation
std::vector< int > m_vTimePoint
time points for the series
std::vector< const MathVector< dim > * > m_vvGlobPos
global ips
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Private Attributes
bool initialized
size_t m_numArgs
std::string m_ValueCode
std::vector< std::string > m_vDerivCode
jmethodID runMethod
jclass userDataClass
jobject userDataValue
std::vector< jobject > vUserDataDeriv
Member Typedef Documentation
base_type
template<typename TData , int dim, typename TDataIn > typedef StdDataLinker<VRLUserLinker<TData, dim, TDataIn>, TData, dim> ug::vrl::VRLUserLinker< TData, dim, TDataIn >::base_type
type of base class
Constructor & Destructor Documentation
VRLUserLinker()
template<typename TData , int dim, typename TDataIn > ug::vrl::VRLUserLinker< TData, dim, TDataIn >::VRLUserLinker () inline
~VRLUserLinker()
template<typename TData , int dim, typename TDataIn > ug::vrl::VRLUserLinker< TData, dim, TDataIn >::~VRLUserLinker () inline
References ug::vrl::VRLUserLinker< TData, dim, TDataIn >::releaseGlobalRefs().
Member Function Documentation
compileUserDataString()
template<typename TData , int dim, typename TDataIn > static jobject ug::vrl::VRLUserLinker< TData, dim, TDataIn >::compileUserDataString (JNIEnv * env, const char * s) inline static protected
References ug::vrl::VRLUserLinker< TData, dim, TDataIn >::retArrayDim, ug::vrl::VRLUserLinker< TData, dim, TDataIn >::runMethod, s, and ug::vrl::stringC2J().
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_deriv_callback(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
eval_and_deriv()
template<typename TData , int dim, typename TDataIn > template<int refDim> void ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_and_deriv (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, bool bDeriv, int s, std::vector< std::vector< TData > > vvvDeriv[], const MathMatrix< refDim, dim > * vJT = NULL) inline
References ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_deriv(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_value(), ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >::input_common_fct(), ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >::input_num_fct(), ug::ICplUserData< dim >::ip(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vpDependData, ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vpUserData, ug::linker_traits< TData, TDataIn, TRet >::mult_add(), ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >::num_input(), s, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >::series_id(), ug::ICplUserData< dim >::time(), ug::CplUserData< TData, dim, void >::value(), and ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >::zero_derivative().
eval_deriv()
template<typename TData , int dim, typename TDataIn > void ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_deriv (TData & value, const std::vector< TDataIn > & dataIn, const MathVector< dim > & x, number time, int si, size_t arg) const inline
evaluates the data at a given point and time
References ug::vrl::checkException(), dim, ug::vrl::threading::getEnv(), ug::vrl::getJavaVM(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::runMethod, ug::ICplUserData< dim >::time(), ug::CplUserData< TData, dim, void >::value(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::vUserDataDeriv.
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_and_deriv().
eval_value()
template<typename TData , int dim, typename TDataIn > void ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_value (TData & value, const std::vector< TDataIn > & dataIn, const MathVector< dim > & x, number time, int si) const inline
evaluates the data at a given point and time
References ug::vrl::checkException(), dim, ug::vrl::threading::getEnv(), ug::vrl::getJavaVM(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::runMethod, ug::ICplUserData< dim >::time(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::userDataValue, and ug::CplUserData< TData, dim, void >::value().
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_and_deriv(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::evaluate().
evaluate() [1/2]
template<typename TData , int dim, typename TDataIn > void ug::vrl::VRLUserLinker< TData, dim, TDataIn >::evaluate (TData & value, const MathVector< dim > & globIP, number time, int si) const inline
References ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_value(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vpUserData, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >::num_input(), ug::ICplUserData< dim >::time(), and ug::CplUserData< TData, dim, void >::value().
evaluate() [2/2]
template<typename TData , int dim, typename TDataIn > template<int refDim> void ug::vrl::VRLUserLinker< TData, dim, TDataIn >::evaluate (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< refDim, dim > * vJT = NULL) const inline
References ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_value(), ug::ICplUserData< dim >::ip(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vpUserData, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >::num_input(), and ug::ICplUserData< dim >::time().
getUserDataClass()
template<typename TData , int dim, typename TDataIn > static jclass ug::vrl::VRLUserLinker< TData, dim, TDataIn >::getUserDataClass (JNIEnv * env) inline static protected
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
getUserDataRunMethod()
template<typename TData , int dim, typename TDataIn > static jmethodID ug::vrl::VRLUserLinker< TData, dim, TDataIn >::getUserDataRunMethod (JNIEnv * env, jclass cls) inline static protected
References ug::vrl::checkException(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::name(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::retArrayDim, and UG_LOG.
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
group_name()
template<typename TData , int dim, typename TDataIn > static std::string ug::vrl::VRLUserLinker< TData, dim, TDataIn >::group_name () inline static
References name.
name()
template<typename TData , int dim, typename TDataIn > static std::string ug::vrl::VRLUserLinker< TData, dim, TDataIn >::name () inline static
References dim, and name.
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::getUserDataRunMethod(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_deriv_callback(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
num_args()
template<typename TData , int dim, typename TDataIn > size_t ug::vrl::VRLUserLinker< TData, dim, TDataIn >::num_args () const inline
References ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_numArgs.
releaseGlobalRefs()
template<typename TData , int dim, typename TDataIn > void ug::vrl::VRLUserLinker< TData, dim, TDataIn >::releaseGlobalRefs () inline
References ug::vrl::threading::getEnv(), ug::vrl::getJavaVM(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::initialized, ug::vrl::VRLUserLinker< TData, dim, TDataIn >::userDataClass, and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::userDataValue.
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::~VRLUserLinker().
set_input()
template<typename TData , int dim, typename TDataIn > void ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_input (size_t i, SmartPtr< CplUserData< TDataIn, dim > > data) inline
References ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vpDependData, ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vpUserData, ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >::num_input(), ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >::set_input(), UG_ASSERT, and UG_THROW.
set_num_input()
template<typename TData , int dim, typename TDataIn > void ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_num_input (size_t num) inline protected
set number of needed inputs
References ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vpDependData, ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vpUserData, and ug::StdDataLinker< VRLUserLinker< TData, dim, TDataIn >, TData, dim >::set_num_input().
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
set_vrl_deriv_callback()
template<typename TData , int dim, typename TDataIn > void ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_deriv_callback (size_t arg, const char * expression) inline
sets the vrl function used to compute the derivative
References append(), ug::vrl::checkException(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::compileUserDataString(), ug::vrl::threading::getEnv(), ug::vrl::getJavaVM(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vDerivCode, ug::vrl::VRLUserLinker< TData, dim, TDataIn >::name(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::vUserDataDeriv.
set_vrl_value_callback()
template<typename TData , int dim, typename TDataIn > void ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback (const char * expression, size_t numArgs) inline
References append(), ug::vrl::checkException(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::compileUserDataString(), ug::vrl::threading::getEnv(), ug::vrl::getJavaVM(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::getUserDataClass(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::getUserDataRunMethod(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_numArgs, ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_ValueCode, ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vDerivCode, ug::vrl::VRLUserLinker< TData, dim, TDataIn >::name(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::releaseGlobalRefs(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::runMethod, ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_num_input(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::userDataClass, ug::vrl::VRLUserLinker< TData, dim, TDataIn >::userDataValue, and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::vUserDataDeriv.
vrl_deriv_callback()
template<typename TData , int dim, typename TDataIn > const char* ug::vrl::VRLUserLinker< TData, dim, TDataIn >::vrl_deriv_callback (size_t arg) inline
References ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vDerivCode.
vrl_value_callback()
template<typename TData , int dim, typename TDataIn > const char* ug::vrl::VRLUserLinker< TData, dim, TDataIn >::vrl_value_callback () inline
References ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_ValueCode.
Member Data Documentation
initialized
template<typename TData , int dim, typename TDataIn > bool ug::vrl::VRLUserLinker< TData, dim, TDataIn >::initialized private
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::releaseGlobalRefs().
m_numArgs
template<typename TData , int dim, typename TDataIn > size_t ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_numArgs private
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::num_args(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
m_ValueCode
template<typename TData , int dim, typename TDataIn > std::string ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_ValueCode private
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::vrl_value_callback().
m_vDerivCode
template<typename TData , int dim, typename TDataIn > std::vector<std::string> ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vDerivCode private
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_deriv_callback(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::vrl_deriv_callback().
m_vpDependData
template<typename TData , int dim, typename TDataIn > std::vector<SmartPtr<DependentUserData<TDataIn, dim> > > ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vpDependData protected
data input casted to dependend data
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_and_deriv(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_input(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_num_input().
m_vpUserData
template<typename TData , int dim, typename TDataIn > std::vector<SmartPtr<CplUserData<TDataIn, dim> > > ug::vrl::VRLUserLinker< TData, dim, TDataIn >::m_vpUserData protected
data input
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_and_deriv(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::evaluate(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_input(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_num_input().
retArrayDim
template<typename TData , int dim, typename TDataIn > const unsigned int ug::vrl::VRLUserLinker< TData, dim, TDataIn >::retArrayDim = vrl_traits<TData>::retArrayDim static
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::compileUserDataString(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::getUserDataRunMethod().
runMethod
template<typename TData , int dim, typename TDataIn > jmethodID ug::vrl::VRLUserLinker< TData, dim, TDataIn >::runMethod private
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::compileUserDataString(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_deriv(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_value(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
userDataClass
template<typename TData , int dim, typename TDataIn > jclass ug::vrl::VRLUserLinker< TData, dim, TDataIn >::userDataClass private
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::releaseGlobalRefs(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
userDataValue
template<typename TData , int dim, typename TDataIn > jobject ug::vrl::VRLUserLinker< TData, dim, TDataIn >::userDataValue private
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_value(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::releaseGlobalRefs(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
vUserDataDeriv
template<typename TData , int dim, typename TDataIn > std::vector<jobject> ug::vrl::VRLUserLinker< TData, dim, TDataIn >::vUserDataDeriv private
Referenced by ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_deriv(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_deriv_callback(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
The documentation for this class was generated from the following file:
ugbase/bindings/vrl/user_data.cpp