ug4: ug::IsBoundaryOrManifodFace Class Reference
ug::IsBoundaryOrManifodFace Class Reference
#include <topology_callbacks.h>
Public Member Functions
IsBoundaryOrManifodFace (Grid &g)
bool operator() (Edge *e) const
bool operator() (Face *f) const
bool operator() (Vertex *v) const
bool operator() (Volume *) const
Public Member Functions inherited from ug::ElementCallback
ElementCallback ()
virtual ~ElementCallback ()
Private Member Functions
template<class TElem >
bool callback (TElem *e) const
Private Attributes
Grid & m_grid
Grid::volume_traits::secure_container m_tmpVols
Constructor & Destructor Documentation
IsBoundaryOrManifodFace()
ug::IsBoundaryOrManifodFace::IsBoundaryOrManifodFace (Grid & g) inline
Member Function Documentation
callback()
template<class TElem > bool ug::IsBoundaryOrManifodFace::callback (TElem * e) const inline private
References m_grid, m_tmpVols, and ug::PointerConstArray< TPtr >::size().
Referenced by operator()().
operator()() [1/4]
bool ug::IsBoundaryOrManifodFace::operator() (Edge * e) const inline virtual
Implements ug::ElementCallback.
operator()() [2/4]
bool ug::IsBoundaryOrManifodFace::operator() (Face * f) const inline virtual
Implements ug::ElementCallback.
References callback().
operator()() [3/4]
bool ug::IsBoundaryOrManifodFace::operator() (Vertex * v) const inline virtual
Implements ug::ElementCallback.
operator()() [4/4]
bool ug::IsBoundaryOrManifodFace::operator() (Volume *) const inline virtual
Implements ug::ElementCallback.
Member Data Documentation
m_grid
Grid& ug::IsBoundaryOrManifodFace::m_grid private
Referenced by callback().
m_tmpVols
Grid::volume_traits::secure_container ug::IsBoundaryOrManifodFace::m_tmpVols private
Referenced by callback().
The documentation for this class was generated from the following file:
ugbase/lib_grid/callbacks/topology_callbacks.h