ug4: ug::VarianceMarking< TDomain > Class Template Reference
ug::VarianceMarking< TDomain > Class Template Reference
#include <error_elem_marking_strategy.h>
Public Types
typedef IElementMarkingStrategy< TDomain > base_type
Public Types inherited from ug::IElementMarkingStrategy< TDomain >
typedef Grid::AttachmentAccessor< elem_type, ug::Attachment< number > > elem_accessor_type
typedef domain_traits< dim >::element_type elem_type
element type to be marked
Public Member Functions
VarianceMarking (number theta)
VarianceMarking (number theta, number width)
Public Member Functions inherited from ug::IElementMarkingStrategy< TDomain >
number global_estimated_error () const
number global_estimated_error_per_elem_max () const
number global_estimated_error_per_elem_min () const
IElementMarkingStrategy ()
void mark (IMultigridElementIndicators< TDomain > &mgElemIndicators, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd)
This function marks all elements.
virtual ~IElementMarkingStrategy ()
Protected Member Functions
void mark (typename base_type::elem_accessor_type &aaError2, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd)
DEPRECATED:
Protected Attributes
int m_max_level
number m_theta
number m_width
Protected Attributes inherited from ug::IElementMarkingStrategy< TDomain >
number m_latest_error
number m_latest_error_per_elem_max
number m_latest_error_per_elem_min
Additional Inherited Members
Static Public Attributes inherited from ug::IElementMarkingStrategy< TDomain >
static const int dim = TDomain::dim
world dimension
Detailed Description
template<typename TDomain>
class ug::VarianceMarking< TDomain >
Marks elements above \(\theta * (\mu + width * \sigma) \) for refinement where \(\mu = E[\eta^2], \sigma^2 = Var[\eta^2] \)
Member Typedef Documentation
base_type
template<typename TDomain > typedef IElementMarkingStrategy<TDomain> ug::VarianceMarking< TDomain >::base_type
Constructor & Destructor Documentation
VarianceMarking() [1/2]
template<typename TDomain > ug::VarianceMarking< TDomain >::VarianceMarking (number theta) inline
VarianceMarking() [2/2]
template<typename TDomain > ug::VarianceMarking< TDomain >::VarianceMarking (number theta, number width) inline
Member Function Documentation
mark()
template<typename TDomain > void ug::VarianceMarking< TDomain >::mark (typename base_type::elem_accessor_type & aaError, IRefiner & refiner, ConstSmartPtr< DoFDistribution > dd) protected virtual
DEPRECATED:
Implements ug::IElementMarkingStrategy< TDomain >.
References pcl::ProcessCommunicator::allreduce(), ug::ComputeMinMax(), ug::IRefiner::mark(), pcl::NumProcs(), PCL_RO_SUM, ug::RM_REFINE, and UG_LOG.
Member Data Documentation
m_max_level
template<typename TDomain > int ug::VarianceMarking< TDomain >::m_max_level protected
m_theta
template<typename TDomain > number ug::VarianceMarking< TDomain >::m_theta protected
m_width
template<typename TDomain > number ug::VarianceMarking< TDomain >::m_width protected
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/error_elem_marking_strategy.h