ug4: ug::TriangleDescriptor Class Reference
ug::TriangleDescriptor Class Reference
only used to initialize a triangle. for all other tasks you should use FaceDescriptor.
#include <grid_objects_2d.h>
Public Member Functions
uint num_vertices () const
void set_vertex (uint index, Vertex *v)
TriangleDescriptor ()
TriangleDescriptor (const TriangleDescriptor &td)
TriangleDescriptor (Vertex *v1, Vertex *v2, Vertex *v3)
Vertex * vertex (size_t index) const
Protected Attributes
Vertex * m_vertex [3]
Detailed Description
only used to initialize a triangle. for all other tasks you should use FaceDescriptor.
Constructor & Destructor Documentation
TriangleDescriptor() [1/3]
ug::TriangleDescriptor::TriangleDescriptor () inline
TriangleDescriptor() [2/3]
ug::TriangleDescriptor::TriangleDescriptor (const TriangleDescriptor & td)
References vertex().
TriangleDescriptor() [3/3]
ug::TriangleDescriptor::TriangleDescriptor (Vertex * v1, Vertex * v2, Vertex * v3)
Member Function Documentation
num_vertices()
uint ug::TriangleDescriptor::num_vertices () const inline
set_vertex()
void ug::TriangleDescriptor::set_vertex (uint index, Vertex * v) inline
Referenced by ug::ExtrudeLayersMixed().
vertex()
Vertex* ug::TriangleDescriptor::vertex (size_t index) const inline
Referenced by ug::CalculateNormalDot(), ug::CustomTriangle< ConcreteTriangleType, BaseClass, RefTriType, RefQuadType >::CustomTriangle(), ug::ExtrudeLayersMixed(), and TriangleDescriptor().
Member Data Documentation
m_vertex
Vertex* ug::TriangleDescriptor::m_vertex[3] protected
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid_objects/grid_objects_2d.h
ugbase/lib_grid/grid_objects/grid_objects_2d.cpp