ug4: ug::ElemRestrictionBase< TDomain, TImpl > Class Template Reference
ug::ElemRestrictionBase< TDomain, TImpl > Class Template Reference
#include <local_transfer_interface.h>
Public Member Functions
virtual void do_restrict (Edge *parent)
virtual void do_restrict (Face *parent)
virtual void do_restrict (Vertex *parent)
virtual void do_restrict (Volume *parent)
Public Member Functions inherited from ug::IElemRestriction< TDomain >
virtual void init (ConstSmartPtr< TDomain > spDomain, SmartPtr< TransferValueAccessor > vValueChild, SmartPtr< TransferValueAccessor > vValueParent)
virtual bool perform_restriction_on (GridBaseObjectId gbo)=0
virtual ~IElemRestriction ()
Protected Member Functions
TImpl & getImpl ()
access to implementation
const TImpl & getImpl () const
const access to implementation
Additional Inherited Members
Protected Attributes inherited from ug::IElemRestriction< TDomain >
ConstSmartPtr< TDomain > m_spDomain
ConstSmartPtr< MultiGrid > m_spGrid
SmartPtr< TransferValueAccessor > m_vValueChild
SmartPtr< TransferValueAccessor > m_vValueParent
Member Function Documentation
do_restrict() [1/4]
template<typename TDomain , typename TImpl > virtual void ug::ElemRestrictionBase< TDomain, TImpl >::do_restrict (Edge * parent) inline virtual
Implements ug::IElemRestriction< TDomain >.
References ug::ElemRestrictionBase< TDomain, TImpl >::getImpl(), ug::IElemRestriction< TDomain >::m_vValueChild, and ug::IElemRestriction< TDomain >::m_vValueParent.
do_restrict() [2/4]
template<typename TDomain , typename TImpl > virtual void ug::ElemRestrictionBase< TDomain, TImpl >::do_restrict (Face * parent) inline virtual
Implements ug::IElemRestriction< TDomain >.
References ug::ElemRestrictionBase< TDomain, TImpl >::getImpl(), ug::IElemRestriction< TDomain >::m_vValueChild, and ug::IElemRestriction< TDomain >::m_vValueParent.
do_restrict() [3/4]
template<typename TDomain , typename TImpl > virtual void ug::ElemRestrictionBase< TDomain, TImpl >::do_restrict (Vertex * parent) inline virtual
Implements ug::IElemRestriction< TDomain >.
Reimplemented in ug::StdLagrangeElemTransfer< TDomain >.
References ug::ElemRestrictionBase< TDomain, TImpl >::getImpl(), ug::IElemRestriction< TDomain >::m_vValueChild, and ug::IElemRestriction< TDomain >::m_vValueParent.
do_restrict() [4/4]
template<typename TDomain , typename TImpl > virtual void ug::ElemRestrictionBase< TDomain, TImpl >::do_restrict (Volume * parent) inline virtual
Implements ug::IElemRestriction< TDomain >.
References ug::ElemRestrictionBase< TDomain, TImpl >::getImpl(), ug::IElemRestriction< TDomain >::m_vValueChild, and ug::IElemRestriction< TDomain >::m_vValueParent.
getImpl() [1/2]
template<typename TDomain , typename TImpl > TImpl& ug::ElemRestrictionBase< TDomain, TImpl >::getImpl () inline protected
access to implementation
Referenced by ug::ElemRestrictionBase< TDomain, TImpl >::do_restrict().
getImpl() [2/2]
template<typename TDomain , typename TImpl > const TImpl& ug::ElemRestrictionBase< TDomain, TImpl >::getImpl () const inline protected
const access to implementation
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/local_transfer_interface.h