ug4: ug::FV1IBGeometry< TElem, TWorldDim > Class Template Reference
ug::FV1IBGeometry< TElem, TWorldDim > Class Template Reference
Geometry and shape functions for 1st order Vertex-Centered Finite Volume.
#include <fv1ib_geom.h>
Classes
class BF
boundary face
class SCV
sub control volume structure
class SCVF
Sub-Control Volume Face structure.
Public Types
typedef TElem elem_type
type of element
typedef LagrangeP1< ref_elem_type > local_shape_fct_set_type
type of Shape function used
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
type of reference element
typedef traits::scv_type scv_type
type of SubControlVolume
typedef fv1_traits< ref_elem_type, TWorldDim > traits
used traits
Public Member Functions
void adapt (GridObject *elem, const MathVector< TWorldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
adapt integration points for elements cut by the inner boundary
void adapt_integration_points (GridObject *elem, const MathVector< TWorldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
adapt integration points for elements cut by the inner boundary
void adapt_normals (GridObject *elem, const MathVector< TWorldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
adapt normals for elements cut by the inner boundary
void add_boundary_subset (int subsetIndex)
add subset that is interpreted as boundary subset.
const std::vector< BF > & bf (int si) const
returns reference to vector of boundary faces for subsetIndex
const BF & bf (int si, size_t i) const
returns the boundary face i for subsetIndex
void clear_boundary_subsets ()
reset all boundary subsets
const MathVector< worldDim > * corners () const
get vector of the global coordinates of corners for current element
FV1IBGeometry ()
construct object and initialize local values and sizes
size_t num_bf () const
number of all boundary faces
size_t num_bf (int si) const
number of boundary faces on subset 'subsetIndex'
size_t num_boundary_subsets ()
number of registered boundary subsets
size_t num_scv () const
number of SubControlVolumes
size_t num_scv_ips () const
returns number of all scv ips
size_t num_scvf () const
number of SubControlVolumeFaces
size_t num_scvf_ips () const
returns number of all scvf ips
size_t num_sh () const
number of shape functions
void remove_boundary_subset (int subsetIndex)
removes subset that is interpreted as boundary subset.
const SCV & scv (size_t i) const
const access to SubControlVolume number i
const MathVector< worldDim > * scv_global_ips () const
returns all ips of scv as they appear in scv loop
const MathVector< dim > * scv_local_ips () const
returns all ips of scv as they appear in scv loop
const SCVF & scvf (size_t i) const
const access to SubControlVolumeFace number i
const MathVector< worldDim > * scvf_global_ips () const
returns all ips of scvf as they appear in scv loop
const MathVector< dim > * scvf_local_ips () const
returns all ips of scvf as they appear in scv loop
void update (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update data for given element
void update_boundary_faces (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update boundary data for given element
void update_local_data ()
update local data
Public Attributes
MathVector< worldDim > m_MidPoint
MathVector< worldDim > vSCVF_PosOnEdge [numSCVF]
new members for adaptions
Static Public Attributes
static const int dim = ref_elem_type::dim
dimension of reference element
static const size_t nip = 1
number of integration points
static const size_t nsh = local_shape_fct_set_type::nsh
number of shape functions
static const size_t numSCV
number of SubControlVolumes
static const size_t numSCVF
number of SubControlVolumeFaces
static const int order = 1
order
static const bool staticLocalData = true
flag indicating if local data may change
static const bool usesHangingNodes = false
Hanging node flag: this Geometry does not support hanging nodes.
static const int worldDim = TWorldDim
dimension of world
Protected Attributes
ReferenceMapping< ref_elem_type, worldDim > m_mapping
Reference Mapping.
std::map< int, std::vector< BF > > m_mapVectorBF
TElem * m_pElem
pointer to current element
const ref_elem_type & m_rRefElem
Reference Element.
const local_shape_fct_set_type & m_rTrialSpace
Shape function set.
std::vector< BF > m_vEmptyVectorBF
MathVector< worldDim > m_vGlobSCVF_IP [numSCVF]
MathVector< dim > m_vLocSCVF_IP [numSCVF]
SCV m_vSCV [numSCV]
SubControlVolumes.
SCVF m_vSCVF [numSCVF]
SubControlVolumeFaces.
MathVector< worldDim > m_vvGloMid [dim+1][maxMid]
MathVector< dim > m_vvLocMid [dim+1][maxMid]
local and global geom object midpoints for each dimension
Static Protected Attributes
static const int maxMid = numSCVF + 1
max number of geom objects in all dimensions
Detailed Description
template<typename TElem, int TWorldDim>
class ug::FV1IBGeometry< TElem, TWorldDim >
Geometry and shape functions for 1st order Vertex-Centered Finite Volume.
Template Parameters
TElem Element type
TWorldDim (physical) world dimension
Member Typedef Documentation
elem_type
template<typename TElem , int TWorldDim> typedef TElem ug::FV1IBGeometry< TElem, TWorldDim >::elem_type
type of element
local_shape_fct_set_type
template<typename TElem , int TWorldDim> typedef LagrangeP1<ref_elem_type> ug::FV1IBGeometry< TElem, TWorldDim >::local_shape_fct_set_type
type of Shape function used
ref_elem_type
template<typename TElem , int TWorldDim> typedef reference_element_traits<TElem>::reference_element_type ug::FV1IBGeometry< TElem, TWorldDim >::ref_elem_type
type of reference element
scv_type
template<typename TElem , int TWorldDim> typedef traits::scv_type ug::FV1IBGeometry< TElem, TWorldDim >::scv_type
type of SubControlVolume
traits
template<typename TElem , int TWorldDim> typedef fv1_traits<ref_elem_type, TWorldDim> ug::FV1IBGeometry< TElem, TWorldDim >::traits
used traits
Constructor & Destructor Documentation
FV1IBGeometry()
template<typename TElem , int TWorldDim> FV1IBGeometry::FV1IBGeometry ()
construct object and initialize local values and sizes
References ug::FV1IBGeometry< TElem, TWorldDim >::update_local_data().
Member Function Documentation
adapt()
template<typename TElem , int TWorldDim> void FV1IBGeometry::adapt (GridObject * elem, const MathVector< TWorldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
adapt integration points for elements cut by the inner boundary
References UG_LOG, ug::VecDot(), and ug::VecSubtract().
adapt_integration_points()
template<typename TElem , int TWorldDim> void FV1IBGeometry::adapt_integration_points (GridObject * elem, const MathVector< TWorldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
adapt integration points for elements cut by the inner boundary
References UG_THROW.
adapt_normals()
template<typename TElem , int TWorldDim> void FV1IBGeometry::adapt_normals (GridObject * elem, const MathVector< TWorldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
adapt normals for elements cut by the inner boundary
BEACHTE: normal on scvf (points direction "from"->"to")
References UG_LOG, and UG_THROW.
add_boundary_subset()
template<typename TElem , int TWorldDim> void ug::FV1IBGeometry< TElem, TWorldDim >::add_boundary_subset (int subsetIndex) inline
add subset that is interpreted as boundary subset.
References ug::FV1IBGeometry< TElem, TWorldDim >::m_mapVectorBF.
bf() [1/2]
template<typename TElem , int TWorldDim> const std::vector<BF>& ug::FV1IBGeometry< TElem, TWorldDim >::bf (int si) const inline
returns reference to vector of boundary faces for subsetIndex
References ug::FV1IBGeometry< TElem, TWorldDim >::m_mapVectorBF, and ug::FV1IBGeometry< TElem, TWorldDim >::m_vEmptyVectorBF.
bf() [2/2]
template<typename TElem , int TWorldDim> const BF& ug::FV1IBGeometry< TElem, TWorldDim >::bf (int si, size_t i) const inline
returns the boundary face i for subsetIndex
References ug::FV1IBGeometry< TElem, TWorldDim >::m_mapVectorBF, ug::FV1IBGeometry< TElem, TWorldDim >::num_bf(), UG_ASSERT, and UG_THROW.
clear_boundary_subsets()
template<typename TElem , int TWorldDim> void ug::FV1IBGeometry< TElem, TWorldDim >::clear_boundary_subsets () inline
reset all boundary subsets
References ug::FV1IBGeometry< TElem, TWorldDim >::m_mapVectorBF.
corners()
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::FV1IBGeometry< TElem, TWorldDim >::corners () const inline
get vector of the global coordinates of corners for current element
References ug::FV1IBGeometry< TElem, TWorldDim >::m_vvGloMid.
num_bf() [1/2]
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::num_bf () const inline
number of all boundary faces
References ug::FV1IBGeometry< TElem, TWorldDim >::m_mapVectorBF.
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::bf().
num_bf() [2/2]
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::num_bf (int si) const inline
number of boundary faces on subset 'subsetIndex'
References ug::FV1IBGeometry< TElem, TWorldDim >::m_mapVectorBF.
num_boundary_subsets()
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::num_boundary_subsets () inline
number of registered boundary subsets
References ug::FV1IBGeometry< TElem, TWorldDim >::m_mapVectorBF.
num_scv()
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::num_scv () const inline
number of SubControlVolumes
References ug::FV1IBGeometry< TElem, TWorldDim >::numSCV.
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::scv().
num_scv_ips()
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::num_scv_ips () const inline
returns number of all scv ips
References ug::FV1IBGeometry< TElem, TWorldDim >::numSCV.
num_scvf()
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::num_scvf () const inline
number of SubControlVolumeFaces
References ug::FV1IBGeometry< TElem, TWorldDim >::numSCVF.
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::scvf().
num_scvf_ips()
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::num_scvf_ips () const inline
returns number of all scvf ips
References ug::FV1IBGeometry< TElem, TWorldDim >::numSCVF.
num_sh()
template<typename TElem , int TWorldDim> size_t ug::FV1IBGeometry< TElem, TWorldDim >::num_sh () const inline
number of shape functions
References ug::FV1IBGeometry< TElem, TWorldDim >::nsh.
remove_boundary_subset()
template<typename TElem , int TWorldDim> void ug::FV1IBGeometry< TElem, TWorldDim >::remove_boundary_subset (int subsetIndex) inline
removes subset that is interpreted as boundary subset.
References ug::FV1IBGeometry< TElem, TWorldDim >::m_mapVectorBF.
scv()
template<typename TElem , int TWorldDim> const SCV& ug::FV1IBGeometry< TElem, TWorldDim >::scv (size_t i) const inline
const access to SubControlVolume number i
References ug::FV1IBGeometry< TElem, TWorldDim >::m_vSCV, ug::FV1IBGeometry< TElem, TWorldDim >::num_scv(), and UG_ASSERT.
scv_global_ips()
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::FV1IBGeometry< TElem, TWorldDim >::scv_global_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::FV1IBGeometry< TElem, TWorldDim >::m_vvGloMid.
scv_local_ips()
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::FV1IBGeometry< TElem, TWorldDim >::scv_local_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::FV1IBGeometry< TElem, TWorldDim >::m_vvLocMid.
scvf()
template<typename TElem , int TWorldDim> const SCVF& ug::FV1IBGeometry< TElem, TWorldDim >::scvf (size_t i) const inline
const access to SubControlVolumeFace number i
References ug::FV1IBGeometry< TElem, TWorldDim >::m_vSCVF, ug::FV1IBGeometry< TElem, TWorldDim >::num_scvf(), and UG_ASSERT.
scvf_global_ips()
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::FV1IBGeometry< TElem, TWorldDim >::scvf_global_ips () const inline
returns all ips of scvf as they appear in scv loop
References ug::FV1IBGeometry< TElem, TWorldDim >::m_vGlobSCVF_IP.
scvf_local_ips()
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::FV1IBGeometry< TElem, TWorldDim >::scvf_local_ips () const inline
returns all ips of scvf as they appear in scv loop
References ug::FV1IBGeometry< TElem, TWorldDim >::m_vLocSCVF_IP.
update()
template<typename TElem , int TWorldDim> void FV1IBGeometry::update (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update data for given element
References ug::AveragePositions(), ug::MatVecMult(), and UG_ASSERT.
update_boundary_faces()
template<typename TElem , int TWorldDim> void FV1IBGeometry::update_boundary_faces (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update boundary data for given element
References ug::AveragePositions(), ug::CollectEdgesSorted(), ug::CollectFacesSorted(), ug::CollectVertices(), ug::ComputeBFMidID(), ug::FV1IBGeometry< TElem, TWorldDim >::BF::detj, dim, ug::ISubsetHandler::get_subset_index(), ug::FV1IBGeometry< TElem, TWorldDim >::BF::globalIP, ug::ISubsetHandler::grid(), ug::FV1IBGeometry< TElem, TWorldDim >::BF::JtInv, ug::FV1IBGeometry< TElem, TWorldDim >::BF::localIP, ug::MatVecMult(), ug::FV1IBGeometry< TElem, TWorldDim >::BF::nodeId, ug::FV1IBGeometry< TElem, TWorldDim >::BF::Normal, ug::FV1IBGeometry< TElem, TWorldDim >::BF::num_sh(), ug::ROID_PYRAMID, UG_ASSERT, ug::VecTwoNorm(), ug::FV1IBGeometry< TElem, TWorldDim >::BF::vGlobalGrad, ug::FV1IBGeometry< TElem, TWorldDim >::BF::vGloPos, ug::FV1IBGeometry< TElem, TWorldDim >::BF::vLocalGrad, ug::FV1IBGeometry< TElem, TWorldDim >::BF::vLocPos, ug::FV1IBGeometry< TElem, TWorldDim >::BF::vMidID, ug::FV1IBGeometry< TElem, TWorldDim >::BF::Vol, and ug::FV1IBGeometry< TElem, TWorldDim >::BF::vShape.
update_local_data()
template<typename TElem , int TWorldDim> void FV1IBGeometry::update_local_data ()
update local data
References ug::AveragePositions(), ug::ComputeSCVFMidID(), ug::ComputeSCVMidID(), and ug::ROID_PYRAMID.
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::FV1IBGeometry().
Member Data Documentation
dim
template<typename TElem , int TWorldDim> const int ug::FV1IBGeometry< TElem, TWorldDim >::dim = ref_elem_type::dim static
dimension of reference element
m_mapping
template<typename TElem , int TWorldDim> ReferenceMapping<ref_elem_type, worldDim> ug::FV1IBGeometry< TElem, TWorldDim >::m_mapping protected
Reference Mapping.
m_mapVectorBF
template<typename TElem , int TWorldDim> std::map<int, std::vector<BF> > ug::FV1IBGeometry< TElem, TWorldDim >::m_mapVectorBF protected
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::add_boundary_subset(), ug::FV1IBGeometry< TElem, TWorldDim >::bf(), ug::FV1IBGeometry< TElem, TWorldDim >::clear_boundary_subsets(), ug::FV1IBGeometry< TElem, TWorldDim >::num_bf(), ug::FV1IBGeometry< TElem, TWorldDim >::num_boundary_subsets(), and ug::FV1IBGeometry< TElem, TWorldDim >::remove_boundary_subset().
m_MidPoint
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1IBGeometry< TElem, TWorldDim >::m_MidPoint
m_pElem
template<typename TElem , int TWorldDim> TElem* ug::FV1IBGeometry< TElem, TWorldDim >::m_pElem protected
pointer to current element
m_rRefElem
template<typename TElem , int TWorldDim> const ref_elem_type& ug::FV1IBGeometry< TElem, TWorldDim >::m_rRefElem protected
Reference Element.
m_rTrialSpace
template<typename TElem , int TWorldDim> const local_shape_fct_set_type& ug::FV1IBGeometry< TElem, TWorldDim >::m_rTrialSpace protected
Shape function set.
m_vEmptyVectorBF
template<typename TElem , int TWorldDim> std::vector<BF> ug::FV1IBGeometry< TElem, TWorldDim >::m_vEmptyVectorBF protected
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::bf().
m_vGlobSCVF_IP
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1IBGeometry< TElem, TWorldDim >::m_vGlobSCVF_IP[numSCVF] protected
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::scvf_global_ips().
m_vLocSCVF_IP
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1IBGeometry< TElem, TWorldDim >::m_vLocSCVF_IP[numSCVF] protected
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::scvf_local_ips().
m_vSCV
template<typename TElem , int TWorldDim> SCV ug::FV1IBGeometry< TElem, TWorldDim >::m_vSCV[numSCV] protected
SubControlVolumes.
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::scv().
m_vSCVF
template<typename TElem , int TWorldDim> SCVF ug::FV1IBGeometry< TElem, TWorldDim >::m_vSCVF[numSCVF] protected
SubControlVolumeFaces.
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::scvf().
m_vvGloMid
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1IBGeometry< TElem, TWorldDim >::m_vvGloMid[dim+1][maxMid] protected
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::corners(), and ug::FV1IBGeometry< TElem, TWorldDim >::scv_global_ips().
m_vvLocMid
template<typename TElem , int TWorldDim> MathVector<dim> ug::FV1IBGeometry< TElem, TWorldDim >::m_vvLocMid[dim+1][maxMid] protected
local and global geom object midpoints for each dimension
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::scv_local_ips().
maxMid
template<typename TElem , int TWorldDim> const int ug::FV1IBGeometry< TElem, TWorldDim >::maxMid = numSCVF + 1 static protected
max number of geom objects in all dimensions
nip
template<typename TElem , int TWorldDim> const size_t ug::FV1IBGeometry< TElem, TWorldDim >::nip = 1 static
number of integration points
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_ip(), ug::FV1IBGeometry< TElem, TWorldDim >::SCV::num_ip(), and ug::FV1IBGeometry< TElem, TWorldDim >::BF::num_ip().
nsh
template<typename TElem , int TWorldDim> const size_t ug::FV1IBGeometry< TElem, TWorldDim >::nsh = local_shape_fct_set_type::nsh static
number of shape functions
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_sh(), ug::FV1IBGeometry< TElem, TWorldDim >::SCV::num_sh(), ug::FV1IBGeometry< TElem, TWorldDim >::BF::num_sh(), and ug::FV1IBGeometry< TElem, TWorldDim >::num_sh().
numSCV
template<typename TElem , int TWorldDim> const size_t ug::FV1IBGeometry< TElem, TWorldDim >::numSCV static
Initial value:
= (ref_elem_type::REFERENCE_OBJECT_ID != ROID_PYRAMID)
                ? ref_elem_type::numCorners : 8
number of SubControlVolumes
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::num_scv(), and ug::FV1IBGeometry< TElem, TWorldDim >::num_scv_ips().
numSCVF
template<typename TElem , int TWorldDim> const size_t ug::FV1IBGeometry< TElem, TWorldDim >::numSCVF static
Initial value:
= (ref_elem_type::REFERENCE_OBJECT_ID != ROID_PYRAMID)
                ? ref_elem_type::numEdges : 12
number of SubControlVolumeFaces
Referenced by ug::FV1IBGeometry< TElem, TWorldDim >::num_scvf(), and ug::FV1IBGeometry< TElem, TWorldDim >::num_scvf_ips().
order
template<typename TElem , int TWorldDim> const int ug::FV1IBGeometry< TElem, TWorldDim >::order = 1 static
order
staticLocalData
template<typename TElem , int TWorldDim> const bool ug::FV1IBGeometry< TElem, TWorldDim >::staticLocalData = true static
flag indicating if local data may change
usesHangingNodes
template<typename TElem , int TWorldDim> const bool ug::FV1IBGeometry< TElem, TWorldDim >::usesHangingNodes = false static
Hanging node flag: this Geometry does not support hanging nodes.
vSCVF_PosOnEdge
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::FV1IBGeometry< TElem, TWorldDim >::vSCVF_PosOnEdge[numSCVF]
new members for adaptions
worldDim
template<typename TElem , int TWorldDim> const int ug::FV1IBGeometry< TElem, TWorldDim >::worldDim = TWorldDim static
dimension of world
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/fv1ib_geom.h
ugbase/lib_disc/spatial_disc/disc_util/fv1ib_geom_impl.h