ug4: ug::EnergyConvCheck< TVector > Class Template Reference
ug::EnergyConvCheck< TVector > Class Template Reference
#include <energy_convergence_check.h>
Public Member Functions
virtual SmartPtr< IConvergenceCheck< TVector > > clone ()
clone the object
virtual std::string config_string () const
returns information about configuration parameters
double energy_norm (const TVector &d)
EnergyConvCheck ()
EnergyConvCheck (int maxSteps, number minDefect, number relReduction)
EnergyConvCheck (int maxSteps, number minDefect, number relReduction, bool verbose)
EnergyConvCheck (int maxSteps, number minDefect, number relReduction, bool verbose, bool suppressUnsuccessful)
void set_linear_operator (SmartPtr< ILinearOperator< TVector > > op)
void start (const TVector &d)
computes the start defect and set it
void update (const TVector &d)
computes the defect and sets it a the next defect value
Public Member Functions inherited from ug::StdConvCheck< TVector >
number avg_rate () const
number defect () const
returns the current defect
const std::vector< number > get_defects () const
int get_offset () const
get the current offset
bool iteration_ended ()
bool post ()
number previous_defect () const
void print_line (std::string line)
prints a line
number rate () const
number reduction () const
void set_info (std::string info)
sets info string
void set_maximum_steps (int maxSteps)
void set_minimum_defect (number minDefect)
void set_name (std::string name)
sets the name of the iteration
void set_offset (int offset)
sets the number of spaces printed before output information
void set_reduction (number relReduction)
void set_supress_unsuccessful (bool bsupress)
void set_symbol (char symbol)
sets the symbol used for output
void set_verbose (bool level)
void start_defect (number initialDefect)
sets the given start defect
StdConvCheck ()
StdConvCheck (int maxSteps, number minDefect, number relReduction)
StdConvCheck (int maxSteps, number minDefect, number relReduction, bool verbose)
StdConvCheck (int maxSteps, number minDefect, number relReduction, bool verbose, bool suppressUnsuccessful)
int step () const
returns the current number of steps
void update_defect (number newDefect)
sets the update for the current defect
Public Member Functions inherited from ug::IConvergenceCheck< TVector >
virtual ~IConvergenceCheck ()
virtual destructor
Private Types
typedef StdConvCheck< TVector > base_type
Private Attributes
SmartPtr< ILinearOperator< TVector > > m_op
SmartPtr< TVector > tmp
SmartPtr< TVector > tmp2
Additional Inherited Members
Protected Member Functions inherited from ug::StdConvCheck< TVector >
bool is_valid_number (number value)
void print_offset ()
Protected Attributes inherited from ug::StdConvCheck< TVector >
number m_currentDefect
int m_currentStep
std::string m_info
number m_initialDefect
number m_lastDefect
int m_maxSteps
number m_minDefect
std::string m_name
int m_offset
number m_ratesProduct
number m_relReduction
bool m_supress_unsuccessful
char m_symbol
bool m_verbose
Member Typedef Documentation
base_type
template<typename TVector > typedef StdConvCheck<TVector> ug::EnergyConvCheck< TVector >::base_type private
Constructor & Destructor Documentation
EnergyConvCheck() [1/4]
template<typename TVector > ug::EnergyConvCheck< TVector >::EnergyConvCheck () inline
EnergyConvCheck() [2/4]
template<typename TVector > ug::EnergyConvCheck< TVector >::EnergyConvCheck (int maxSteps, number minDefect, number relReduction) inline
EnergyConvCheck() [3/4]
template<typename TVector > ug::EnergyConvCheck< TVector >::EnergyConvCheck (int maxSteps, number minDefect, number relReduction, bool verbose) inline
EnergyConvCheck() [4/4]
template<typename TVector > ug::EnergyConvCheck< TVector >::EnergyConvCheck (int maxSteps, number minDefect, number relReduction, bool verbose, bool suppressUnsuccessful) inline
Member Function Documentation
clone()
template<typename TVector > virtual SmartPtr<IConvergenceCheck<TVector> > ug::EnergyConvCheck< TVector >::clone () inline virtual
clone the object
Reimplemented from ug::StdConvCheck< TVector >.
config_string()
template<typename TVector > virtual std::string ug::EnergyConvCheck< TVector >::config_string () const inline virtual
returns information about configuration parameters
this should return necessary information about parameters and possibly calling config_string of subcomponents.
Returns
std::string necessary information about configuration parameters
Reimplemented from ug::StdConvCheck< TVector >.
References ug::StdConvCheck< TVector >::m_maxSteps, ug::StdConvCheck< TVector >::m_minDefect, and ug::StdConvCheck< TVector >::m_relReduction.
energy_norm()
template<typename TVector > double ug::EnergyConvCheck< TVector >::energy_norm (const TVector & d) inline
References ug::EnergyConvCheck< TVector >::m_op, ug::PST_CONSISTENT, ug::EnergyConvCheck< TVector >::tmp, ug::EnergyConvCheck< TVector >::tmp2, SmartPtr< T, FreePolicy >::valid(), and ug::VecProd().
Referenced by ug::EnergyConvCheck< TVector >::start(), and ug::EnergyConvCheck< TVector >::update().
set_linear_operator()
template<typename TVector > void ug::EnergyConvCheck< TVector >::set_linear_operator (SmartPtr< ILinearOperator< TVector > > op) inline
References ug::EnergyConvCheck< TVector >::m_op.
start()
template<typename TVector > void ug::EnergyConvCheck< TVector >::start (const TVector & d) inline virtual
computes the start defect and set it
Reimplemented from ug::StdConvCheck< TVector >.
References ug::EnergyConvCheck< TVector >::energy_norm(), and ug::StdConvCheck< TVector >::start_defect().
update()
template<typename TVector > void ug::EnergyConvCheck< TVector >::update (const TVector & d) inline virtual
computes the defect and sets it a the next defect value
Reimplemented from ug::StdConvCheck< TVector >.
References ug::EnergyConvCheck< TVector >::energy_norm(), and ug::StdConvCheck< TVector >::update_defect().
Member Data Documentation
m_op
template<typename TVector > SmartPtr<ILinearOperator<TVector> > ug::EnergyConvCheck< TVector >::m_op private
Referenced by ug::EnergyConvCheck< TVector >::energy_norm(), and ug::EnergyConvCheck< TVector >::set_linear_operator().
tmp
template<typename TVector > SmartPtr<TVector> ug::EnergyConvCheck< TVector >::tmp private
Referenced by ug::EnergyConvCheck< TVector >::energy_norm().
tmp2
template<typename TVector > SmartPtr<TVector> ug::EnergyConvCheck< TVector >::tmp2 private
Referenced by ug::EnergyConvCheck< TVector >::energy_norm().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/energy_convergence_check.h