ug4: ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF Class Reference
ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF Class Reference
Sub-Control Volume Face structure.
#include <fvcr_geom.h>
Public Member Functions
number detJ () const
Determinant of Jacobian in integration point.
size_t from () const
index of SubControlVolume on one side of the scvf
const MathVector< worldDim > & global_corner (size_t co) const
return glbal corner number i
const MathVector< worldDim > & global_grad (size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector () const
vector of gloabl gradients in ip point
const MathVector< worldDim > & global_ip () const
global integration point of scvf
const MathMatrix< worldDim, dim > & JTInv () const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector () const
vector of local gradients in ip point
const MathVector< dim > & local_ip () const
local integration point of scvf
const MathVector< worldDim > & normal () const
normal on scvf (points direction "from"->"to"). Norm is equal to area
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points on scvf
size_t num_sh () const
number of shape functions
void operator= (const SCVF &s)
SCVF ()
number shape (size_t sh) const
value of shape function i in integration point
const number * shape_vector () const
vector of shape functions in ip point
size_t to () const
index of SubControlVolume on one side of the scvf
Static Public Attributes
static const size_t numCo = dim
Number of corners of scvf.
Private Attributes
number detj
size_t From
MathVector< worldDim > globalIP
MathMatrix< worldDim, dim > JtInv
MathVector< dim > localIP
MathVector< worldDim > Normal
size_t numSH
size_t To
MathVector< worldDim > vGlobalGrad [maxNSH]
MathVector< worldDim > vGloPos [numCo]
MathVector< dim > vLocalGrad [maxNSH]
MathVector< dim > vLocPos [numCo]
number vShape [maxNSH]
Friends
class DimCRFVGeometry< dim, worldDim >
Detailed Description
template<int TDim, int TWorldDim = TDim>
class ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF
Sub-Control Volume Face structure.
Each finite element is cut by several sub-control volume faces. The idea is that the "dual" skeleton formed by the sub control volume faces of all elements again gives rise to a regular mesh with closed (lipschitz-bounded) control volumes. The SCVF are the boundary of the control volume. In computation the flux over each SCVF must be the same in both directions over the face in order to guarantee the conservation property.
Constructor & Destructor Documentation
template<int TDim, int TWorldDim = TDim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::SCVF () inline
Member Function Documentation
template<int TDim, int TWorldDim = TDim> number ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::detJ () const inline
Determinant of Jacobian in integration point.
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::from () const inline
index of SubControlVolume on one side of the scvf
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::global_corner (size_t co) const inline
return glbal corner number i
References UG_ASSERT.
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::global_grad (size_t sh) const inline
value of global gradient of shape function i in integration point
References UG_ASSERT.
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::global_grad_vector () const inline
vector of gloabl gradients in ip point
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::global_ip () const inline
global integration point of scvf
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
template<int TDim, int TWorldDim = TDim> const MathMatrix<worldDim,dim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::JTInv () const inline
Transposed Inverse of Jacobian in integration point.
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::local_corner (size_t co) const inline
return local corner number i
References UG_ASSERT.
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::local_grad (size_t sh) const inline
value of local gradient of shape function i in integration point
References UG_ASSERT.
template<int TDim, int TWorldDim = TDim> const MathVector<dim>* ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::local_grad_vector () const inline
vector of local gradients in ip point
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::local_ip () const inline
local integration point of scvf
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::normal () const inline
normal on scvf (points direction "from"->"to"). Norm is equal to area
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::num_corners () const inline
number of corners, that bound the scvf
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::num_ip () const inline
number of integration points on scvf
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::num_sh () const inline
number of shape functions
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
template<int TDim, int TWorldDim = TDim> void ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator= (const SCVF & s) inline
References ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::detJ(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::from(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::global_corner(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::global_grad(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::global_ip(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::JTInv(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::local_corner(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::local_ip(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::normal(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::num_sh(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::shape(), and ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::to().
template<int TDim, int TWorldDim = TDim> number ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::shape (size_t sh) const inline
value of shape function i in integration point
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
template<int TDim, int TWorldDim = TDim> const number* ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::shape_vector () const inline
vector of shape functions in ip point
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::to () const inline
index of SubControlVolume on one side of the scvf
Referenced by ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::operator=().
Friends And Related Function Documentation
template<int TDim, int TWorldDim = TDim> friend class DimCRFVGeometry< dim, worldDim > friend
Member Data Documentation
template<int TDim, int TWorldDim = TDim> number ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::detj private
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::From private
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::globalIP private
template<int TDim, int TWorldDim = TDim> MathMatrix<worldDim,dim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::JtInv private
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::localIP private
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::Normal private
template<int TDim, int TWorldDim = TDim> const size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::numCo = dim static
Number of corners of scvf.
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::numSH private
template<int TDim, int TWorldDim = TDim> size_t ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::To private
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::vGlobalGrad[maxNSH] private
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::vGloPos[numCo] private
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::vLocalGrad[maxNSH] private
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::vLocPos[numCo] private
template<int TDim, int TWorldDim = TDim> number ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::vShape[maxNSH] private
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fvcr_geom.h