ug4: ug::LinearSolver< TVector > Class Template Reference
ug::LinearSolver< TVector > Class Template Reference
linear solver using abstract preconditioner interface
#include <linear_solver.h>
Public Types
typedef IPreconditionedLinearOperatorInverse< vector_type > base_type
Base type.
typedef TVector vector_type
Vector type.
Public Types inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
typedef ILinearOperatorInverse< TVector, TVector > base_type
Base class.
typedef TVector codomain_function_type
Range space.
typedef TVector domain_function_type
Domain space.
Public Types inherited from ug::ILinearOperatorInverse< X, Y >
typedef Y codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Types inherited from ug::ILinearIterator< X, X >
typedef X codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Types inherited from ug::VectorDebugWritingObject< TVector >
typedef TVector vector_type
type of vector
Public Member Functions
void add_postprocess_corr (SmartPtr< IPProcessVector< vector_type > > p)
adds a post-process for the iterates
virtual bool apply_return_defect (vector_type &x, vector_type &b)
solves the system and returns the last defect
bool compute_correction (vector_type &c, vector_type &d)
LinearSolver ()
constructors
LinearSolver (SmartPtr< ILinearIterator< vector_type, vector_type > > spPrecond)
LinearSolver (SmartPtr< ILinearIterator< vector_type, vector_type > > spPrecond, SmartPtr< IConvergenceCheck< vector_type > > spConvCheck)
virtual const char * name () const
returns the name of the solver
void remove_postprocess_corr (SmartPtr< IPProcessVector< vector_type > > p)
removes a post-process for the iterates
virtual bool supports_parallel () const
returns if parallel solving is supported
Public Member Functions inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
virtual bool apply (TVector &x, const TVector &b)
compute new correction c = B*d
virtual std::string config_string () const
returns information about configuration parameters
std::string config_string_preconditioner_convergence_check () const
returns config information of convergence check and preconditioner
virtual bool init (SmartPtr< ILinearOperator< TVector, TVector > > J, const TVector &u)
initializes the solver for an operator
virtual bool init (SmartPtr< ILinearOperator< TVector, TVector > > L)
initializes the solver for an operator
IPreconditionedLinearOperatorInverse ()
Empty constructor.
IPreconditionedLinearOperatorInverse (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond)
constructor setting the preconditioner
IPreconditionedLinearOperatorInverse (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond, SmartPtr< IConvergenceCheck< TVector > > spConvCheck)
constructor setting the preconditioner
void set_compute_fresh_defect_when_finished (bool bRecompute)
for debug: computes norm again after whole calculation of apply
void set_preconditioner (SmartPtr< ILinearIterator< TVector, TVector > > spPrecond)
sets the preconditioner
SmartPtr< ILinearIterator< TVector, TVector > > preconditioner ()
ConstSmartPtr< ILinearIterator< TVector, TVector > > preconditioner () const
Public Member Functions inherited from ug::ILinearOperatorInverse< X, Y >
virtual bool apply (Y &u, const X &f)=0
applies inverse operator, i.e. returns u = A^{-1} f
virtual bool apply_return_defect (Y &u, X &f)=0
applies inverse operator, i.e. returns u = A^{-1} f and returns defect d := f - A*u
virtual bool apply_update_defect (Y &u, X &f)
virtual SmartPtr< ILinearIterator< X, Y > > clone ()
clone
SmartPtr< IConvergenceCheck< X > > convergence_check ()
returns the convergence check
ConstSmartPtr< IConvergenceCheck< X > > convergence_check () const
returns the convergence check
number defect () const
returns the current defect
ILinearOperatorInverse ()
constructor setting convergence check to (100, 1e-12, 1e-12, true)
ILinearOperatorInverse (SmartPtr< IConvergenceCheck< X > > spConvCheck)
Default constructor.
virtual bool init (SmartPtr< ILinearOperator< Y, X > > J, const Y &u)
initializes for the inverse for a linearized operator at linearization point u
virtual bool init (SmartPtr< ILinearOperator< Y, X > > L)
initializes for the inverse for a linear operator
SmartPtr< ILinearOperator< Y, X > > linear_operator ()
returns the current Operator this Inverse Operator is initialized for
number reduction () const
returns the current relative reduction
void set_convergence_check (SmartPtr< IConvergenceCheck< X > > spConvCheck)
set the convergence check
virtual int standard_offset () const
returns the standard offset for output
int step () const
returns the current number of steps
virtual ~ILinearOperatorInverse ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< X, X >
virtual bool apply (X &c, const X &d)=0
compute new correction c = B*d
virtual bool apply_update_defect (X &c, X &d)=0
compute new correction c = B*d and update defect d := d - A*c
SmartPtr< IDamping< X, X > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< X, X > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< X, X > > J, const X &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< X, X > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< X, X > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TVector >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
void enter_precond_debug_section (int loopCnt)
debugger section for the preconditioner
SmartPtr< ILinearIterator< X, X > > preconditioner ()
ConstSmartPtr< ILinearIterator< X, X > > preconditioner () const
void prepare_conv_check ()
prepares the convergence check output
void write_debugXCD (vector_type &x, vector_type &c, vector_type &d, int loopCnt, bool bWriteC)
debugger output: solution, correction, defect
Protected Member Functions inherited from ug::VectorDebugWritingObject< TVector >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
PProcessChain< vector_type > m_corr_post_process
postprocessor for the correction in the iterations
Protected Attributes inherited from ug::IPreconditionedLinearOperatorInverse< TVector >
bool m_bRecompute
flag if fresh defect should be computed when finish for debug purpose
SmartPtr< ILinearIterator< TVector, TVector > > m_spPrecond
Iterator used in the iterative scheme to compute the correction and update the defect.
Protected Attributes inherited from ug::ILinearOperatorInverse< X, Y >
SmartPtr< IConvergenceCheck< X > > m_spConvCheck
smart pointer holding the convergence check
SmartPtr< ILinearOperator< Y, X > > m_spLinearOperator
Operator that is inverted by this Inverse Operator.
Protected Attributes inherited from ug::ILinearIterator< X, X >
SmartPtr< IDamping< X, X > > m_spDamping
the scaling
Protected Attributes inherited from ug::VectorDebugWritingObject< TVector >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Detailed Description
template<typename TVector>
class ug::LinearSolver< TVector >
linear solver using abstract preconditioner interface
This class is a linear iterating scheme, that uses any implementation of the ILinearIterator interface to precondition the iteration.
Template Parameters
TAlgebra algebra type
Member Typedef Documentation
base_type
template<typename TVector > typedef IPreconditionedLinearOperatorInverse<vector_type> ug::LinearSolver< TVector >::base_type
Base type.
vector_type
template<typename TVector > typedef TVector ug::LinearSolver< TVector >::vector_type
Vector type.
Constructor & Destructor Documentation
LinearSolver() [1/3]
template<typename TVector > ug::LinearSolver< TVector >::LinearSolver () inline
constructors
LinearSolver() [2/3]
template<typename TVector > ug::LinearSolver< TVector >::LinearSolver (SmartPtr< ILinearIterator< vector_type, vector_type > > spPrecond) inline
LinearSolver() [3/3]
template<typename TVector > ug::LinearSolver< TVector >::LinearSolver (SmartPtr< ILinearIterator< vector_type, vector_type > > spPrecond, SmartPtr< IConvergenceCheck< vector_type > > spConvCheck) inline
Member Function Documentation
add_postprocess_corr()
template<typename TVector > void ug::LinearSolver< TVector >::add_postprocess_corr (SmartPtr< IPProcessVector< vector_type > > p) inline
adds a post-process for the iterates
References ug::PProcessChain< TVector >::add(), ug::LinearSolver< TVector >::m_corr_post_process, and p.
apply_return_defect()
template<typename TVector > virtual bool ug::LinearSolver< TVector >::apply_return_defect (vector_type & x, vector_type & b) inline virtual
solves the system and returns the last defect
References ug::PProcessChain< TVector >::apply(), ug::LinearSolver< TVector >::compute_correction(), ug::ILinearOperatorInverse< X, Y >::convergence_check(), ug::LinearSolver< TVector >::enter_precond_debug_section(), ug::VectorDebugWritingObject< TVector >::leave_vector_debug_writer_section(), ug::ILinearOperatorInverse< X, Y >::linear_operator(), LS_PROFILE_BEGIN, LS_PROFILE_END, ug::LinearSolver< TVector >::m_corr_post_process, ug::LinearSolver< TVector >::prepare_conv_check(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, UG_LOG, UG_THROW, ug::VectorDebugWritingObject< TVector >::vector_debug_writer_valid(), ug::VectorDebugWritingObject< TVector >::write_debug(), and ug::LinearSolver< TVector >::write_debugXCD().
compute_correction()
template<typename TVector > bool ug::LinearSolver< TVector >::compute_correction (vector_type & c, vector_type & d) inline
Compute a correction c := B*d using one iterative step Internally the defect is updated d := d - A*c = b - A*(x+c)
Parameters
c
d
References ug::ILinearOperatorInverse< X, Y >::apply_update_defect(), LS_PROFILE_BEGIN, LS_PROFILE_END, ug::LinearSolver< TVector >::preconditioner(), and UG_LOG.
Referenced by ug::LinearSolver< TVector >::apply_return_defect().
enter_precond_debug_section()
template<typename TVector > void ug::LinearSolver< TVector >::enter_precond_debug_section (int loopCnt) inline protected
debugger section for the preconditioner
References ug::VectorDebugWritingObject< TVector >::enter_vector_debug_writer_section(), sprintf(), and ug::VectorDebugWritingObject< TVector >::vector_debug_writer_valid().
Referenced by ug::LinearSolver< TVector >::apply_return_defect().
name()
template<typename TVector > virtual const char* ug::LinearSolver< TVector >::name () const inline virtual
returns the name of the solver
Implements ug::ILinearOperatorInverse< X, Y >.
Referenced by ug::LinearSolver< TVector >::prepare_conv_check().
preconditioner() [1/2]
template<typename TVector > SmartPtr<ILinearIterator<X, X> > ug::IPreconditionedLinearOperatorInverse< X >::preconditioner inline protected
returns the preconditioner
Referenced by ug::LinearSolver< TVector >::compute_correction(), ug::LinearSolver< TVector >::prepare_conv_check(), and ug::LinearSolver< TVector >::supports_parallel().
preconditioner() [2/2]
template<typename TVector > ConstSmartPtr<ILinearIterator<X, X> > ug::IPreconditionedLinearOperatorInverse< X >::preconditioner inline protected
prepare_conv_check()
template<typename TVector > void ug::LinearSolver< TVector >::prepare_conv_check () inline protected
prepares the convergence check output
References ug::ILinearOperatorInverse< X, Y >::convergence_check(), ug::LinearSolver< TVector >::name(), ug::LinearSolver< TVector >::preconditioner(), and s.
Referenced by ug::LinearSolver< TVector >::apply_return_defect().
remove_postprocess_corr()
template<typename TVector > void ug::LinearSolver< TVector >::remove_postprocess_corr (SmartPtr< IPProcessVector< vector_type > > p) inline
removes a post-process for the iterates
References ug::LinearSolver< TVector >::m_corr_post_process, p, and ug::PProcessChain< TVector >::remove().
supports_parallel()
template<typename TVector > virtual bool ug::LinearSolver< TVector >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearOperatorInverse< X, Y >.
References ug::LinearSolver< TVector >::preconditioner().
write_debugXCD()
template<typename TVector > void ug::LinearSolver< TVector >::write_debugXCD (vector_type & x, vector_type & c, vector_type & d, int loopCnt, bool bWriteC) inline protected
debugger output: solution, correction, defect
References sprintf(), ug::VectorDebugWritingObject< TVector >::vector_debug_writer_valid(), and ug::VectorDebugWritingObject< TVector >::write_debug().
Referenced by ug::LinearSolver< TVector >::apply_return_defect().
Member Data Documentation
m_corr_post_process
template<typename TVector > PProcessChain<vector_type> ug::LinearSolver< TVector >::m_corr_post_process protected
postprocessor for the correction in the iterations
Referenced by ug::LinearSolver< TVector >::add_postprocess_corr(), ug::LinearSolver< TVector >::apply_return_defect(), and ug::LinearSolver< TVector >::remove_postprocess_corr().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/linear_solver/linear_solver.h