ug4: ug::Flag< TEnum, TStorageType, defaultValue > Class Template Reference
ug::Flag< TEnum, TStorageType, defaultValue > Class Template Reference
Helps maintaining, activating and deactivating a set of flags from an enum.
#include <flags.h>
Public Member Functions
Flag & add (TStorageType flag)
bool contains (const Flag &flag) const
bool contains (TStorageType flag) const
Flag ()
Flag (const Flag &flag)
Flag (TStorageType flag)
TStorageType get () const
bool operator!= (const Flag &flag) const
bool operator!= (TStorageType val) const
Flag operator& (const Flag &flag) const
Flag operator&= (const Flag &flag)
TStorageType operator() () const
Flag operator= (const Flag &flag)
Flag operator= (TStorageType val)
bool operator== (const Flag &flag) const
bool operator== (TStorageType val) const
Flag operator| (const Flag &flag) const
Flag operator|= (const Flag &flag)
bool partially_contains (const Flag &flag) const
bool partially_contains (TStorageType flag) const
Flag & remove (TStorageType flag)
Flag & set (TStorageType flag)
Private Attributes
TStorageType m_value
Detailed Description
template<class TEnum, class TStorageType = unsigned int, TStorageType defaultValue = 0>
class ug::Flag< TEnum, TStorageType, defaultValue >
Helps maintaining, activating and deactivating a set of flags from an enum.
Given an enum
enum SomeEnum{
  E1 = 0,
  E2 = 1,
  E3 = 1 << 1,
  E4 = 1 << 2
};
One can use the Flag class as follows:
typedef Flag<SomeEnum> SomeFlag;
...
SomeFlag f1(E2), f2(E4);
SomeFlag f3(f1 | f2);
if(f3.contains(E2))
  f3.remove(E2);
...
Constructor & Destructor Documentation
Flag() [1/3]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> ug::Flag< TEnum, TStorageType, defaultValue >::Flag () inline
Referenced by ug::Flag< TEnum, TStorageType, defaultValue >::operator&(), and ug::Flag< TEnum, TStorageType, defaultValue >::operator|().
Flag() [2/3]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> ug::Flag< TEnum, TStorageType, defaultValue >::Flag (TStorageType flag) inline
Flag() [3/3]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> ug::Flag< TEnum, TStorageType, defaultValue >::Flag (const Flag< TEnum, TStorageType, defaultValue > & flag) inline
Member Function Documentation
add()
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> Flag& ug::Flag< TEnum, TStorageType, defaultValue >::add (TStorageType flag) inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
contains() [1/2]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> bool ug::Flag< TEnum, TStorageType, defaultValue >::contains (const Flag< TEnum, TStorageType, defaultValue > & flag) const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
contains() [2/2]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> bool ug::Flag< TEnum, TStorageType, defaultValue >::contains (TStorageType flag) const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
Referenced by ug::SurfaceView::is_contained(), ug::SurfaceView::is_shadowing(), ug::MarkAlongSurface(), and ug::DoFDistribution::sum_dof_count().
get()
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> TStorageType ug::Flag< TEnum, TStorageType, defaultValue >::get () const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
Referenced by ug::AssignSubsetsBySurfaceViewState().
operator!=() [1/2]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> bool ug::Flag< TEnum, TStorageType, defaultValue >::operator!= (const Flag< TEnum, TStorageType, defaultValue > & flag) const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
operator!=() [2/2]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> bool ug::Flag< TEnum, TStorageType, defaultValue >::operator!= (TStorageType val) const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
operator&()
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> Flag ug::Flag< TEnum, TStorageType, defaultValue >::operator& (const Flag< TEnum, TStorageType, defaultValue > & flag) const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::Flag(), and ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
operator&=()
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> Flag ug::Flag< TEnum, TStorageType, defaultValue >::operator&= (const Flag< TEnum, TStorageType, defaultValue > & flag) inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
operator()()
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> TStorageType ug::Flag< TEnum, TStorageType, defaultValue >::operator() () const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
operator=() [1/2]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> Flag ug::Flag< TEnum, TStorageType, defaultValue >::operator= (const Flag< TEnum, TStorageType, defaultValue > & flag) inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
operator=() [2/2]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> Flag ug::Flag< TEnum, TStorageType, defaultValue >::operator= (TStorageType val) inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
operator==() [1/2]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> bool ug::Flag< TEnum, TStorageType, defaultValue >::operator== (const Flag< TEnum, TStorageType, defaultValue > & flag) const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
operator==() [2/2]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> bool ug::Flag< TEnum, TStorageType, defaultValue >::operator== (TStorageType val) const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
operator|()
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> Flag ug::Flag< TEnum, TStorageType, defaultValue >::operator| (const Flag< TEnum, TStorageType, defaultValue > & flag) const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::Flag(), and ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
operator|=()
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> Flag ug::Flag< TEnum, TStorageType, defaultValue >::operator|= (const Flag< TEnum, TStorageType, defaultValue > & flag) inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
partially_contains() [1/2]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> bool ug::Flag< TEnum, TStorageType, defaultValue >::partially_contains (const Flag< TEnum, TStorageType, defaultValue > & flag) const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
partially_contains() [2/2]
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> bool ug::Flag< TEnum, TStorageType, defaultValue >::partially_contains (TStorageType flag) const inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
Referenced by ug::ExchangeAndAdjustSideErrors(), ug::SurfaceView::SurfaceViewElementIterator< TElem >::is_contained(), ug::SurfaceView::ConstSurfaceViewElementIterator< TElem >::is_contained(), ug::SurfaceView::is_contained(), ug::SurfaceView::is_shadowed(), ug::MarkForAdaption_GradientAverage(), and ug::SurfaceView::surface_state().
remove()
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> Flag& ug::Flag< TEnum, TStorageType, defaultValue >::remove (TStorageType flag) inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
set()
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> Flag& ug::Flag< TEnum, TStorageType, defaultValue >::set (TStorageType flag) inline
References ug::Flag< TEnum, TStorageType, defaultValue >::m_value.
Member Data Documentation
m_value
template<class TEnum , class TStorageType = unsigned int, TStorageType defaultValue = 0> TStorageType ug::Flag< TEnum, TStorageType, defaultValue >::m_value private
Referenced by ug::Flag< TEnum, TStorageType, defaultValue >::add(), ug::Flag< TEnum, TStorageType, defaultValue >::contains(), ug::Flag< TEnum, TStorageType, defaultValue >::get(), ug::Flag< TEnum, TStorageType, defaultValue >::operator!=(), ug::Flag< TEnum, TStorageType, defaultValue >::operator&(), ug::Flag< TEnum, TStorageType, defaultValue >::operator&=(), ug::Flag< TEnum, TStorageType, defaultValue >::operator()(), ug::Flag< TEnum, TStorageType, defaultValue >::operator=(), ug::Flag< TEnum, TStorageType, defaultValue >::operator==(), ug::Flag< TEnum, TStorageType, defaultValue >::operator|(), ug::Flag< TEnum, TStorageType, defaultValue >::operator|=(), ug::Flag< TEnum, TStorageType, defaultValue >::partially_contains(), ug::Flag< TEnum, TStorageType, defaultValue >::remove(), and ug::Flag< TEnum, TStorageType, defaultValue >::set().
The documentation for this class was generated from the following file:
ugbase/common/util/flags.h