ug4: ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder > Class Template Reference
ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder > Class Template Reference
Geometry and shape functions for any order Vertex-Centered Finite Volume.
#include <fvho_geom.h>
Classes
class BF
boundary face
class SCV
sub control volume structure
class SCVF
Sub-Control Volume Face structure.
struct SubElement
Public Types
typedef TElem elem_type
type of element
typedef LagrangeLSFS< ref_elem_type, p > local_shape_fct_set_type
type of Shape function used
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
type of reference element
typedef GaussQuadrature< scv_type, quadOrderSCV > scv_quad_rule_type
type of quadrature rule
typedef traits::scv_type scv_type
type of SubControlVolume
typedef GaussQuadrature< scvf_type, quadOrderSCVF > scvf_quad_rule_type
type of quadrature rule
typedef traits::scvf_type scvf_type
type of SubControlVolumeFace
typedef fv1_traits< ref_elem_type, worldDim > traits
traits used
Public Member Functions
void add_boundary_subset (int subsetIndex)
add subset that is interpreted as boundary subset.
const BF & bf (int si, size_t i) const
returns the boundary face i for subsetIndex
const std::vector< BF > & bf (int si) const
returns reference to vector of boundary faces for subsetIndex
void clear_boundary_subsets ()
reset all boundary subsets
FVGeometry ()
construct object and initialize local values and sizes
size_t num_bf () const
number of all boundary faces
size_t num_bf (int si) const
number of boundary faces on subset 'subsetIndex'
size_t num_boundary_subsets ()
number of registered boundary subsets
size_t num_scv () const
number of SubControlVolumes
size_t num_scv_ips () const
returns number of all scv ips
size_t num_scvf () const
number of SubControlVolumeFaces
size_t num_scvf_ips () const
returns number of all scvf ips
size_t num_sh () const
number of shape functions
void remove_boundary_subset (int subsetIndex)
removes subset that is interpreted as boundary subset.
void reset_curr_elem ()
const SCV & scv (size_t i) const
const access to SubControlVolume number i
const MathVector< worldDim > * scv_global_ips () const
returns all ips of scv as they appear in scv loop
const MathVector< dim > * scv_local_ips () const
returns all ips of scv as they appear in scv loop
const SCVF & scvf (size_t i) const
const access to SubControlVolumeFace number i
const MathVector< worldDim > * scvf_global_ips () const
returns all ips of scvf as they appear in scv loop
const MathVector< dim > * scvf_local_ips () const
returns all ips of scvf as they appear in scv loop
void update (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update data for given element
void update_boundary_faces (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update boundary data for given element
void update_local (ReferenceObjectID roid, const LFEID &lfeID=LFEID(LFEID::LAGRANGE, worldDim, 1), size_t orderQuad=TQuadOrder)
update Geometry for roid
void update_local_data ()
update local data
Static Public Attributes
static const int dim = ref_elem_type::dim
dimension of reference element
static const size_t nsh = local_shape_fct_set_type::nsh
number of shape functions
static const size_t numSCV = numSubElem * numSCVPerSubElem
number of SubControlVolumes
static const size_t numSCVF = numSubElem * numSCVFPerSubElem
number of SubControlVolumeFaces
static const size_t numSCVFIP = scvf_quad_rule_type::nip * numSCVF
number of scvf ip
static const size_t numSCVFPerSubElem = ref_elem_type::numEdges
number of SCVF per SubElement
static const size_t numSCVIP = scv_quad_rule_type::nip * numSCV
number of scv ip
static const size_t numSCVPerSubElem = ref_elem_type::numCorners
number of SCV per SubElement
static const size_t numSubElem = Pow<p, dim>::value
number of subelements
static const int order = TOrder
order
static const int quadOrderSCV = TQuadOrder
quadrature order
static const int quadOrderSCVF = TQuadOrder
quadrature order
static const bool staticLocalData = true
flag indicating if local data may change
static const bool usesHangingNodes = false
Hanging node flag: this Geometry does not support hanging nodes.
static const int worldDim = TWorldDim
dimension of world
Protected Attributes
std::map< int, std::vector< BF > > m_mapVectorBF
std::vector< BF > m_vEmptyVectorBF
MathVector< worldDim > m_vGlobSCV_IP [numSCVIP]
MathVector< worldDim > m_vGlobSCVF_IP [numSCVFIP]
MathVector< dim > m_vLocSCV_IP [numSCVIP]
MathVector< dim > m_vLocSCVF_IP [numSCVFIP]
SubElement m_vSubElem [numSubElem]
subelements
Static Protected Attributes
static const int maxMid = numSCVF + 1
Private Attributes
TElem * m_pElem
pointer to current element
ReferenceMapping< ref_elem_type, worldDim > m_rMapping
Reference Mapping.
const ref_elem_type & m_rRefElem
Reference Element.
const scvf_quad_rule_type & m_rSCVFQuadRule
Quad Rule scvf.
const scv_quad_rule_type & m_rSCVQuadRule
Quad Rule scv.
const local_shape_fct_set_type & m_rTrialSpace
Shape function set.
MathVector< dim > m_vLocCorner [ref_elem_type::numCorners]
corners of reference element
SCV m_vSCV [numSCV]
SubControlVolumes.
SCVF m_vSCVF [numSCVF]
SubControlVolumeFaces.
Static Private Attributes
static const int p = TOrder
small abbreviation for order
Detailed Description
template<int TOrder, typename TElem, int TWorldDim, int TQuadOrder = TOrder + 1>
class ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >
Geometry and shape functions for any order Vertex-Centered Finite Volume.
Template Parameters
TOrder order
TElem Element type
TWorldDim (physical) world dimension
TQuadOrderSCVF integration order for scvf
TQuadOrderSCV integration order for scv
Member Typedef Documentation
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> typedef TElem ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::elem_type
type of element
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> typedef LagrangeLSFS<ref_elem_type, p> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::local_shape_fct_set_type
type of Shape function used
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> typedef reference_element_traits<TElem>::reference_element_type ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::ref_elem_type
type of reference element
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> typedef GaussQuadrature<scv_type, quadOrderSCV> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scv_quad_rule_type
type of quadrature rule
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> typedef traits::scv_type ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scv_type
type of SubControlVolume
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> typedef GaussQuadrature<scvf_type, quadOrderSCVF> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scvf_quad_rule_type
type of quadrature rule
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> typedef traits::scvf_type ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scvf_type
type of SubControlVolumeFace
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> typedef fv1_traits<ref_elem_type, worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::traits
traits used
Constructor & Destructor Documentation
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::FVGeometry ()
construct object and initialize local values and sizes
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
Referenced by ug::ComputeMultiIndicesOfSubElement< 3 >().
Member Function Documentation
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> void ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::add_boundary_subset (int subsetIndex) inline
add subset that is interpreted as boundary subset.
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const BF& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::bf (int si, size_t i) const inline
returns the boundary face i for subsetIndex
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF, and UG_THROW.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const std::vector<BF>& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::bf (int si) const inline
returns reference to vector of boundary faces for subsetIndex
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vEmptyVectorBF.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> void ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::clear_boundary_subsets () inline
reset all boundary subsets
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_bf () const inline
number of all boundary faces
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::bf().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_bf (int si) const inline
number of boundary faces on subset 'subsetIndex'
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_boundary_subsets () inline
number of registered boundary subsets
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scv () const inline
number of SubControlVolumes
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCV.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scv(), ug::DimFVGeometry< TWorldDim, TDim >::scv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scv_ips () const inline
returns number of all scv ips
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCVIP.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scvf () const inline
number of SubControlVolumeFaces
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCVF.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scvf(), ug::DimFVGeometry< TWorldDim, TDim >::scvf(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scvf_ips () const inline
returns number of all scvf ips
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCVFIP.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_sh () const inline
number of shape functions
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::nsh.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> void ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::remove_boundary_subset (int subsetIndex) inline
removes subset that is interpreted as boundary subset.
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> void ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::reset_curr_elem () inline
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_pElem.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const SCV& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scv (size_t i) const inline
const access to SubControlVolume number i
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSCV, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scv(), and UG_ASSERT.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scv_global_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vGlobSCV_IP.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scv_local_ips () const inline
returns all ips of scv as they appear in scv loop
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vLocSCV_IP.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const SCVF& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scvf (size_t i) const inline
const access to SubControlVolumeFace number i
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSCVF, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scvf(), and UG_ASSERT.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<worldDim>* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scvf_global_ips () const inline
returns all ips of scvf as they appear in scv loop
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vGlobSCVF_IP.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const MathVector<dim>* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scvf_local_ips () const inline
returns all ips of scvf as they appear in scv loop
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vLocSCVF_IP.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder> void ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update data for given element
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::global_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::global_ip(), ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_ip(), ug::ReferenceMapping< TRefElem, TWorldDim >::local_to_global(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_pElem, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rMapping, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rSCVFQuadRule, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rSCVQuadRule, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vGlobSCV_IP, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vGlobSCVF_IP, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSCV, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSCVF, ug::MatVecMult(), ug::fv1_traits< TRefElem, TWorldDim >::NormalOnSCVF(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::nsh, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_boundary_subsets(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_corners(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_corners(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scvf(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scvf(), ug::ReferenceMapping< TRefElem, TWorldDim >::sqrt_gram_det(), UG_ASSERT, ug::ReferenceMapping< TRefElem, TWorldDim >::update(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vDetJ, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vDetJ, ug::VecNormalize(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vGlobalIP, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vGlobalIP, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vGloPos, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vGloPos, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vJtInv, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vJtInv, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vLocPos, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vLocPos.
Referenced by ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder> void ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update boundary data for given element
References ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::bf(), ug::CollectEdgesSorted(), ug::CollectFacesSorted(), ug::CollectVertices(), ug::ComputeBFMidID(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::dim, ug::DimFVGeometry< TWorldDim, TDim >::DimFVGeometry(), ug::ISubsetHandler::get_subset_index(), ug::ISubsetHandler::grid(), ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::local_ip(), ug::ReferenceMapping< TRefElem, TWorldDim >::local_to_global(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rMapping, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rRefElem, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rSCVFQuadRule, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rTrialSpace, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSubElem, ug::MatVecMult(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::nodeId, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::Normal, ug::fv1_traits< TRefElem, TWorldDim >::NormalOnSCVF(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_corners(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_sh(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::numCo, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSubElem, ug::ReferenceMapping< TRefElem, TWorldDim >::sqrt_gram_det(), UG_ASSERT, ug::ReferenceMapping< TRefElem, TWorldDim >::update(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vDetJ, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SubElement::vDoFID, ug::VecTwoNorm(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SubElement::vElemBndSide, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vGlobalIP, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vGloPos, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vJtInv, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vLocalIP, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vLocPos, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vMidID, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::Vol, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvGlobalGrad, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SubElement::vvGloMid, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvLocalGrad, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SubElement::vvLocMid, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vvShape, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::vWeight.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::DimFVGeometry< TWorldDim, TDim >::update().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder> void ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local (ReferenceObjectID roid, const LFEID & lfeID = LFEID(LFEID::LAGRANGE, worldDim, 1), size_t orderQuad = TQuadOrder)
update Geometry for roid
References ug::LFEID::LAGRANGE, ug::LFEID::order(), ug::LFEID::type(), UG_THROW, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::FVGeometry(), and ug::DimFVGeometry< TWorldDim, TDim >::update_local().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder> void ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data ()
update local data
References ug::ComputeSCVFMidID(), ug::ComputeSCVMidID(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::dim, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::From, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SubElement::isBndElem, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::local_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::local_ip(), ug::ReferenceMapping< TRefElem, TWorldDim >::local_to_global(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rRefElem, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rSCVFQuadRule, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rSCVQuadRule, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rTrialSpace, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vLocSCV_IP, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vLocSCVF_IP, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSCV, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSCVF, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSubElem, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::nodeId, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_corners(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_ip(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scvf(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::numCo, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCVFPerSubElem, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCVPerSubElem, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSubElem, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::p, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scvf(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::To, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SubElement::vDoFID, ug::VecScaleAppend(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SubElement::vElemBndSide, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vLocalIP, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vLocalIP, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vLocPos, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vLocPos, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vMidID, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vMidID, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SubElement::vvLocMid, ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::vWeight, and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::vWeight.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::FVGeometry(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local().
Member Data Documentation
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const int ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::dim = ref_elem_type::dim static
dimension of reference element
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> std::map<int, std::vector<BF> > ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_mapVectorBF protected
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::add_boundary_subset(), ug::DimFVGeometry< TWorldDim, TDim >::add_boundary_subset(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::bf(), ug::DimFVGeometry< TWorldDim, TDim >::bf(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::clear_boundary_subsets(), ug::DimFVGeometry< TWorldDim, TDim >::clear_boundary_subsets(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_bf(), ug::DimFVGeometry< TWorldDim, TDim >::num_bf(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_boundary_subsets(), ug::DimFVGeometry< TWorldDim, TDim >::num_boundary_subsets(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::remove_boundary_subset(), ug::DimFVGeometry< TWorldDim, TDim >::remove_boundary_subset(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> TElem* ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_pElem private
pointer to current element
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::reset_curr_elem(), ug::DimFVGeometry< TWorldDim, TDim >::reset_curr_elem(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> ReferenceMapping<ref_elem_type, worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rMapping private
Reference Mapping.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const ref_elem_type& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rRefElem private
Reference Element.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const scvf_quad_rule_type& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rSCVFQuadRule private
Quad Rule scvf.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const scv_quad_rule_type& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rSCVQuadRule private
Quad Rule scv.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const local_shape_fct_set_type& ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_rTrialSpace private
Shape function set.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> std::vector<BF> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vEmptyVectorBF protected
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::bf(), and ug::DimFVGeometry< TWorldDim, TDim >::bf().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vGlobSCV_IP[numSCVIP] protected
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scv_global_ips(), ug::DimFVGeometry< TWorldDim, TDim >::scv_global_ips(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<worldDim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vGlobSCVF_IP[numSCVFIP] protected
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scvf_global_ips(), ug::DimFVGeometry< TWorldDim, TDim >::scvf_global_ips(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vLocCorner[ref_elem_type::numCorners] private
corners of reference element
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vLocSCV_IP[numSCVIP] protected
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scv_local_ips(), ug::DimFVGeometry< TWorldDim, TDim >::scv_local_ips(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> MathVector<dim> ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vLocSCVF_IP[numSCVFIP] protected
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scvf_local_ips(), ug::DimFVGeometry< TWorldDim, TDim >::scvf_local_ips(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> SCV ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSCV[numSCV] private
SubControlVolumes.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scv(), ug::DimFVGeometry< TWorldDim, TDim >::scv(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> SCVF ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSCVF[numSCVF] private
SubControlVolumeFaces.
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::scvf(), ug::DimFVGeometry< TWorldDim, TDim >::scvf(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> SubElement ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::m_vSubElem[numSubElem] protected
subelements
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const int ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::maxMid = numSCVF + 1 static protected
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::nsh = local_shape_fct_set_type::nsh static
number of shape functions
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCVF::num_sh(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::SCV::num_sh(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::BF::num_sh(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_sh(), ug::DimFVGeometry< TWorldDim, TDim >::SCVF::num_sh(), ug::DimFVGeometry< TWorldDim, TDim >::SCV::num_sh(), ug::DimFVGeometry< TWorldDim, TDim >::BF::num_sh(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCV = numSubElem * numSCVPerSubElem static
number of SubControlVolumes
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scv().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCVF = numSubElem * numSCVFPerSubElem static
number of SubControlVolumeFaces
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scvf().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCVFIP = scvf_quad_rule_type::nip * numSCVF static
number of scvf ip
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scvf_ips().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCVFPerSubElem = ref_elem_type::numEdges static
number of SCVF per SubElement
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCVIP = scv_quad_rule_type::nip * numSCV static
number of scv ip
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::num_scv_ips().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSCVPerSubElem = ref_elem_type::numCorners static
number of SCV per SubElement
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const size_t ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::numSubElem = Pow<p, dim>::value static
number of subelements
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const int ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::order = TOrder static
order
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const int ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::p = TOrder static private
small abbreviation for order
Referenced by ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const int ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::quadOrderSCV = TQuadOrder static
quadrature order
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const int ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::quadOrderSCVF = TQuadOrder static
quadrature order
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const bool ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::staticLocalData = true static
flag indicating if local data may change
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const bool ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::usesHangingNodes = false static
Hanging node flag: this Geometry does not support hanging nodes.
template<int TOrder, typename TElem , int TWorldDim, int TQuadOrder = TOrder + 1> const int ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::worldDim = TWorldDim static
dimension of world
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/fvho_geom.h
ugbase/lib_disc/spatial_disc/disc_util/fvho_geom.cpp