ug4: ug::H1SemiDiffIntegrand< TGridFunction > Class Template Reference
ug::H1SemiDiffIntegrand< TGridFunction > Class Template Reference
#include <integrate.h>
Public Member Functions
template<int elemDim>
void evaluate (number vValue[], const MathVector< worldDim > vFineGlobIP[], GridObject *pFineElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vFineLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP)
returns the values of the integrand for a bunch of ips
H1SemiDiffIntegrand (SmartPtr< TGridFunction > spFineGridFct, size_t fineCmp, SmartPtr< TGridFunction > spCoarseGridFct, size_t coarseCmp)
constructor (1 is fine grid function)
virtual void set_subset (int si)
sets subset
Public Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, H1SemiDiffIntegrand< TGridFunction > >
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)
virtual void values (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)
Public Member Functions inherited from ug::IIntegrand< number, TWorldDim >
int subset () const
returns the subset
virtual ~IIntegrand ()
Static Public Attributes
static const int worldDim = TGridFunction::dim
world dimension of grid function
Static Public Attributes inherited from ug::StdIntegrand< number, TGridFunction::dim, H1SemiDiffIntegrand< TGridFunction > >
static const int worldDim
world dimension
Static Public Attributes inherited from ug::IIntegrand< number, TWorldDim >
static const int worldDim
world dimension
Private Attributes
const size_t m_coarseFct
const LFEID m_coarseLFEID
const int m_coarseTopLevel
const size_t m_fineFct
const LFEID m_fineLFEID
const int m_fineTopLevel
SmartPtr< TGridFunction > m_spCoarseGridFct
SmartPtr< TGridFunction > m_spFineGridFct
SmartPtr< MultiGrid > m_spMG
multigrid
Additional Inherited Members
Public Types inherited from ug::StdIntegrand< number, TGridFunction::dim, H1SemiDiffIntegrand< TGridFunction > >
typedef number data_type
data type
Public Types inherited from ug::IIntegrand< number, TWorldDim >
typedef number data_type
data type
Protected Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, H1SemiDiffIntegrand< TGridFunction > >
H1SemiDiffIntegrand< TGridFunction > & getImpl ()
access to implementation
const H1SemiDiffIntegrand< TGridFunction > & getImpl () const
const access to implementation
Protected Attributes inherited from ug::IIntegrand< number, TWorldDim >
int m_si
subset
Constructor & Destructor Documentation
H1SemiDiffIntegrand()
template<typename TGridFunction > ug::H1SemiDiffIntegrand< TGridFunction >::H1SemiDiffIntegrand (SmartPtr< TGridFunction > spFineGridFct, size_t fineCmp, SmartPtr< TGridFunction > spCoarseGridFct, size_t coarseCmp) inline
constructor (1 is fine grid function)
References SmartPtr< T, FreePolicy >::get(), and UG_THROW.
Member Function Documentation
evaluate()
template<typename TGridFunction > template<int elemDim> void ug::H1SemiDiffIntegrand< TGridFunction >::evaluate (number vValue[], const MathVector< worldDim > vFineGlobIP[], GridObject * pFineElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vFineLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP) inline
returns the values of the integrand for a bunch of ips
Parameters
vValue[out] the value of the integrand at the ips
vGlobIP[in] global integration point positions
pElem[in] the element to integrate
vCornerCoords[in] corner coordinates of the element
vLocIP[in] local integration point positions
vJT[in] jacobian transposed at integration point
numIP[in] number of integration points
References ug::CollectCornerCoordinates(), ug::DoFRef(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::Inverse(), ug::MatVecMult(), ug::GridObject::reference_object_id(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shape(), UG_CATCH_THROW, ug::VecDistanceSq(), ug::VecScaleAppend(), and ug::VecSet().
set_subset()
template<typename TGridFunction > virtual void ug::H1SemiDiffIntegrand< TGridFunction >::set_subset (int si) inline virtual
sets subset
Reimplemented from ug::IIntegrand< number, TWorldDim >.
References ug::IIntegrand< TData, TWorldDim >::set_subset(), and UG_THROW.
Member Data Documentation
m_coarseFct
template<typename TGridFunction > const size_t ug::H1SemiDiffIntegrand< TGridFunction >::m_coarseFct private
m_coarseLFEID
template<typename TGridFunction > const LFEID ug::H1SemiDiffIntegrand< TGridFunction >::m_coarseLFEID private
m_coarseTopLevel
template<typename TGridFunction > const int ug::H1SemiDiffIntegrand< TGridFunction >::m_coarseTopLevel private
m_fineFct
template<typename TGridFunction > const size_t ug::H1SemiDiffIntegrand< TGridFunction >::m_fineFct private
m_fineLFEID
template<typename TGridFunction > const LFEID ug::H1SemiDiffIntegrand< TGridFunction >::m_fineLFEID private
m_fineTopLevel
template<typename TGridFunction > const int ug::H1SemiDiffIntegrand< TGridFunction >::m_fineTopLevel private
m_spCoarseGridFct
template<typename TGridFunction > SmartPtr<TGridFunction> ug::H1SemiDiffIntegrand< TGridFunction >::m_spCoarseGridFct private
m_spFineGridFct
template<typename TGridFunction > SmartPtr<TGridFunction> ug::H1SemiDiffIntegrand< TGridFunction >::m_spFineGridFct private
m_spMG
template<typename TGridFunction > SmartPtr<MultiGrid> ug::H1SemiDiffIntegrand< TGridFunction >::m_spMG private
multigrid
worldDim
template<typename TGridFunction > const int ug::H1SemiDiffIntegrand< TGridFunction >::worldDim = TGridFunction::dim static
world dimension of grid function
The documentation for this class was generated from the following file:
ugbase/lib_disc/function_spaces/integrate.h