ug4: ug::MatrixDiagonal< M, X, Y > Class Template Reference
ug::MatrixDiagonal< M, X, Y > Class Template Reference
#include <matrix_diagonal.h>
Public Types
typedef Y codomain_function_type
typedef X domain_function_type
typedef M matrix_type
typedef MatrixOperator< M, X, Y > mo_type
Public Types inherited from ug::ILinearOperator< X, Y >
typedef Y codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Types inherited from ug::IOperator< X, Y >
typedef Y codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Member Functions
virtual void apply (Y &f, const X &u)
virtual void apply_sub (Y &f, const X &u)
virtual void init (const X &u)
init operator depending on a function u
virtual void init ()
init operator
MatrixDiagonal (SmartPtr< mo_type > mo)
Public Member Functions inherited from ug::ILinearOperator< X, Y >
virtual void prepare (X &u)
default implementation for IOperator interface
virtual ~ILinearOperator ()
virtual destructor
Public Member Functions inherited from ug::IOperator< X, Y >
virtual ~IOperator ()
virtual destructor
Public Attributes
SmartPtr< mo_type > m_mo
Member Typedef Documentation
template<typename M , typename X , typename Y = X> typedef Y ug::MatrixDiagonal< M, X, Y >::codomain_function_type
template<typename M , typename X , typename Y = X> typedef X ug::MatrixDiagonal< M, X, Y >::domain_function_type
template<typename M , typename X , typename Y = X> typedef M ug::MatrixDiagonal< M, X, Y >::matrix_type
template<typename M , typename X , typename Y = X> typedef MatrixOperator<M, X, Y> ug::MatrixDiagonal< M, X, Y >::mo_type
Constructor & Destructor Documentation
template<typename M , typename X , typename Y = X> ug::MatrixDiagonal< M, X, Y >::MatrixDiagonal (SmartPtr< mo_type > mo) inline
Member Function Documentation
template<typename M , typename X , typename Y = X> virtual void ug::MatrixDiagonal< M, X, Y >::apply (Y & f, const X & u) inline virtual
This method applies the operator, i.e. f = L*u (or d = J(u)*c in iterative schemes). Note, that the operator must have been initialized once before this method can be used.
Parameters
[in] u domain function
[out] f codomain function
Returns
bool success flag
Implements ug::ILinearOperator< X, Y >.
References ug::MatrixOperator< M, X, Y >::get_matrix().
template<typename M , typename X , typename Y = X> virtual void ug::MatrixDiagonal< M, X, Y >::apply_sub (Y & f, const X & u) inline virtual
This method applies the operator and subracts the result from the input codomain function, i.e. f -= L*u (or d -= J(u)*c in iterative schemes). Note, that the operator must have been initialized once before this method can be used.
Parameters
[in] u domain function
[in,out] f codomain function
Returns
bool success flag
Implements ug::ILinearOperator< X, Y >.
References ug::MatrixOperator< M, X, Y >::get_matrix().
template<typename M , typename X , typename Y = X> virtual void ug::MatrixDiagonal< M, X, Y >::init (const X & u) inline virtual
init operator depending on a function u
This method initializes the operator. Once initialized the 'apply'-method can be called. The function u is passed here, since the linear operator may be the linearization of some non-linear operator. Thus, the operator depends on the linearization point. If the operator is not a linearization, this method can be implemented by simply calling init() and forgetting about the linearization point.
Parameters
[in] u function (linearization point)
Returns
bool success flag
Implements ug::ILinearOperator< X, Y >.
References ug::MatrixOperator< M, X, Y >::init().
template<typename M , typename X , typename Y = X> virtual void ug::MatrixDiagonal< M, X, Y >::init () inline virtual
init operator
This method initializes the operator. Once initialized the 'apply'-method can be called. If the operator is a linearization this function returns false.
Returns
bool success flag
Implements ug::ILinearOperator< X, Y >.
References ug::MatrixOperator< M, X, Y >::init().
Member Data Documentation
template<typename M , typename X , typename Y = X> SmartPtr<mo_type> ug::MatrixDiagonal< M, X, Y >::m_mo
The documentation for this class was generated from the following file:
ugbase/bridge/algebra_bridges/matrix_diagonal.h