ug4: ug::SparseMatrix< TValueType >::const_row_iterator Class Reference
ug::SparseMatrix< TValueType >::const_row_iterator Class Reference
#include <sparsematrix.h>
Public Member Functions
void check () const
const_row_iterator (const const_row_iterator &other)
const_row_iterator (const SparseMatrix &_A, size_t row, size_t _i)
const_row_iterator (const_row_iterator &&other)
size_t idx () const
size_t index () const
bool operator!= (const const_row_iterator &o) const
void operator++ ()
void operator+= (int nr)
const_row_iterator * operator-> () const
const_row_iterator & operator= (const_row_iterator &&)=delete
const_row_iterator & operator= (const_row_iterator const &)=delete
bool operator== (const const_row_iterator &other) const
const value_type & value () const
~const_row_iterator ()
Private Attributes
size_t _row
const SparseMatrix & A
size_t i
Constructor & Destructor Documentation
const_row_iterator() [1/3]
template<typename TValueType > ug::SparseMatrix< TValueType >::const_row_iterator::const_row_iterator (const SparseMatrix & _A, size_t row, size_t _i) inline
References ug::SparseMatrix< TValueType >::const_row_iterator::A, and ug::SparseMatrix< TValueType >::add_iterator().
const_row_iterator() [2/3]
template<typename TValueType > ug::SparseMatrix< TValueType >::const_row_iterator::const_row_iterator (const const_row_iterator & other) inline
References ug::SparseMatrix< TValueType >::const_row_iterator::_row, ug::SparseMatrix< TValueType >::const_row_iterator::A, and ug::SparseMatrix< TValueType >::add_iterator().
const_row_iterator() [3/3]
template<typename TValueType > ug::SparseMatrix< TValueType >::const_row_iterator::const_row_iterator (const_row_iterator && other) inline
References ug::SparseMatrix< TValueType >::const_row_iterator::_row, ug::SparseMatrix< TValueType >::const_row_iterator::A, and ug::SparseMatrix< TValueType >::add_iterator().
~const_row_iterator()
template<typename TValueType > ug::SparseMatrix< TValueType >::const_row_iterator::~const_row_iterator () inline
References ug::SparseMatrix< TValueType >::const_row_iterator::_row, ug::SparseMatrix< TValueType >::const_row_iterator::A, and ug::SparseMatrix< TValueType >::remove_iterator().
Member Function Documentation
check()
template<typename TValueType > void ug::SparseMatrix< TValueType >::const_row_iterator::check () const inline
References ug::SparseMatrix< TValueType >::const_row_iterator::_row, ug::SparseMatrix< TValueType >::const_row_iterator::A, ug::SparseMatrix< TValueType >::check_row(), and ug::SparseMatrix< TValueType >::const_row_iterator::i.
Referenced by ug::SparseMatrix< TValueType >::const_row_iterator::index(), and ug::SparseMatrix< TValueType >::const_row_iterator::value().
idx()
template<typename TValueType > size_t ug::SparseMatrix< TValueType >::const_row_iterator::idx () const inline
References ug::SparseMatrix< TValueType >::const_row_iterator::i.
Referenced by boost::SM_adjacency_iterator< T >::idx().
index()
template<typename TValueType > size_t ug::SparseMatrix< TValueType >::const_row_iterator::index () const inline
References ug::SparseMatrix< TValueType >::const_row_iterator::A, ug::SparseMatrix< TValueType >::const_row_iterator::check(), ug::SparseMatrix< TValueType >::cols, and ug::SparseMatrix< TValueType >::const_row_iterator::i.
Referenced by boost::SM_adjacency_iterator< T >::dereference().
operator!=()
template<typename TValueType > bool ug::SparseMatrix< TValueType >::const_row_iterator::operator!= (const const_row_iterator & o) const inline
References ug::SparseMatrix< TValueType >::const_row_iterator::i.
operator++()
template<typename TValueType > void ug::SparseMatrix< TValueType >::const_row_iterator::operator++ () inline
References ug::SparseMatrix< TValueType >::const_row_iterator::i.
operator+=()
template<typename TValueType > void ug::SparseMatrix< TValueType >::const_row_iterator::operator+= (int nr) inline
References ug::SparseMatrix< TValueType >::const_row_iterator::i.
operator->()
template<typename TValueType > const_row_iterator* ug::SparseMatrix< TValueType >::const_row_iterator::operator-> () const inline
operator=() [1/2]
template<typename TValueType > const_row_iterator& ug::SparseMatrix< TValueType >::const_row_iterator::operator= (const_row_iterator &&) delete
operator=() [2/2]
template<typename TValueType > const_row_iterator& ug::SparseMatrix< TValueType >::const_row_iterator::operator= (const_row_iterator const &) delete
operator==()
template<typename TValueType > bool ug::SparseMatrix< TValueType >::const_row_iterator::operator== (const const_row_iterator & other) const inline
References ug::SparseMatrix< TValueType >::const_row_iterator::i.
value()
template<typename TValueType > const value_type& ug::SparseMatrix< TValueType >::const_row_iterator::value () const inline
References ug::SparseMatrix< TValueType >::const_row_iterator::A, ug::SparseMatrix< TValueType >::const_row_iterator::check(), ug::SparseMatrix< TValueType >::const_row_iterator::i, and ug::SparseMatrix< TValueType >::values.
Referenced by boost::SM_adjacency_iterator< T >::skip_zeroes(), and boost::SM_adjacency_iterator< T >::value().
Member Data Documentation
_row
template<typename TValueType > size_t ug::SparseMatrix< TValueType >::const_row_iterator::_row private
Referenced by ug::SparseMatrix< TValueType >::const_row_iterator::check(), ug::SparseMatrix< TValueType >::const_row_iterator::const_row_iterator(), and ug::SparseMatrix< TValueType >::const_row_iterator::~const_row_iterator().
A
template<typename TValueType > const SparseMatrix& ug::SparseMatrix< TValueType >::const_row_iterator::A private
Referenced by ug::SparseMatrix< TValueType >::const_row_iterator::check(), ug::SparseMatrix< TValueType >::const_row_iterator::const_row_iterator(), ug::SparseMatrix< TValueType >::const_row_iterator::index(), ug::SparseMatrix< TValueType >::const_row_iterator::value(), and ug::SparseMatrix< TValueType >::const_row_iterator::~const_row_iterator().
i
template<typename TValueType > size_t ug::SparseMatrix< TValueType >::const_row_iterator::i private
Referenced by ug::SparseMatrix< TValueType >::const_row_iterator::check(), ug::SparseMatrix< TValueType >::const_row_iterator::idx(), ug::SparseMatrix< TValueType >::const_row_iterator::index(), ug::SparseMatrix< TValueType >::const_row_iterator::operator!=(), ug::SparseMatrix< TValueType >::const_row_iterator::operator++(), ug::SparseMatrix< TValueType >::const_row_iterator::operator+=(), ug::SparseMatrix< TValueType >::const_row_iterator::operator==(), and ug::SparseMatrix< TValueType >::const_row_iterator::value().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/cpu_algebra/sparsematrix.h