ug4: ug::ComPol_GatherSurfaceStates< TLayout > Class Template Reference
ug::ComPol_GatherSurfaceStates< TLayout > Class Template Reference
adds marking at extracting side
Public Types
typedef Layout::Element Element
typedef Layout::Type GeomObj
typedef Layout::Interface Interface
typedef Interface::const_iterator InterfaceIter
typedef TLayout Layout
Public Types inherited from pcl::ICommunicationPolicy< TLayout >
typedef Layout::Interface Interface
typedef TLayout Layout
Public Member Functions
virtual bool collect (ug::BinaryBuffer &buff, const Interface &intfc)
write surface state for each entry
ComPol_GatherSurfaceStates (MultiGrid &mg, MultiElementAttachmentAccessor< SurfaceView::ASurfaceState > &aaElemSurfState)
Construct the communication policy with a ug::BoolMarker.
virtual bool extract (ug::BinaryBuffer &buff, const Interface &intfc)
reads marks from the given stream
virtual int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
virtual ~ComPol_GatherSurfaceStates ()
Public Member Functions inherited from pcl::ICommunicationPolicy< TLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual ~ICommunicationPolicy ()
Protected Attributes
MultiElementAttachmentAccessor< SurfaceView::ASurfaceState > m_aaESS
MultiGrid & m_mg
Detailed Description
template<class TLayout>
class ug::ComPol_GatherSurfaceStates< TLayout >
adds marking at extracting side
Member Typedef Documentation
Element
template<class TLayout > typedef Layout::Element ug::ComPol_GatherSurfaceStates< TLayout >::Element
GeomObj
template<class TLayout > typedef Layout::Type ug::ComPol_GatherSurfaceStates< TLayout >::GeomObj
Interface
template<class TLayout > typedef Layout::Interface ug::ComPol_GatherSurfaceStates< TLayout >::Interface
InterfaceIter
template<class TLayout > typedef Interface::const_iterator ug::ComPol_GatherSurfaceStates< TLayout >::InterfaceIter
Layout
template<class TLayout > typedef TLayout ug::ComPol_GatherSurfaceStates< TLayout >::Layout
Constructor & Destructor Documentation
ComPol_GatherSurfaceStates()
template<class TLayout > ug::ComPol_GatherSurfaceStates< TLayout >::ComPol_GatherSurfaceStates (MultiGrid & mg, MultiElementAttachmentAccessor< SurfaceView::ASurfaceState > & aaElemSurfState) inline
Construct the communication policy with a ug::BoolMarker.
~ComPol_GatherSurfaceStates()
template<class TLayout > virtual ug::ComPol_GatherSurfaceStates< TLayout >::~ComPol_GatherSurfaceStates () inline virtual
Member Function Documentation
collect()
template<class TLayout > virtual bool ug::ComPol_GatherSurfaceStates< TLayout >::collect (ug::BinaryBuffer & buff, const Interface & intfc) inline virtual
write surface state for each entry
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::BinaryBuffer::write().
extract()
template<class TLayout > virtual bool ug::ComPol_GatherSurfaceStates< TLayout >::extract (ug::BinaryBuffer & buff, const Interface & intfc) inline virtual
reads marks from the given stream
Implements pcl::ICommunicationPolicy< TLayout >.
References boost::get(), and ug::BinaryBuffer::read().
get_required_buffer_size()
template<class TLayout > virtual int ug::ComPol_GatherSurfaceStates< TLayout >::get_required_buffer_size (const Interface & interface) inline virtual
returns the size of the buffer in bytes, that will be required for interface-communication.
Determines the size of the buffer on which the extract and receive methods for the given interface will operate. If the buffer-size can't be calculated on both sides (sender and receiver) this method should return -1. This will lead to an additional communication step in which buffer-sizes will be exchanged. If the buffer-size can be calculated on both sides, it makes sense to do so, since this leads to less communication and overall improved performance. The buffer-size has to exactly match the size of required memory. Make sure that you completely fill the buffer during collect(...) and that you read all data during extract(...). The default implementation returns -1.
Reimplemented from pcl::ICommunicationPolicy< TLayout >.
Member Data Documentation
m_aaESS
template<class TLayout > MultiElementAttachmentAccessor<SurfaceView::ASurfaceState> ug::ComPol_GatherSurfaceStates< TLayout >::m_aaESS protected
m_mg
template<class TLayout > MultiGrid& ug::ComPol_GatherSurfaceStates< TLayout >::m_mg protected
The documentation for this class was generated from the following file:
ugbase/lib_grid/tools/surface_view.cpp