ug4: ug::DimFV1IBGeometry< TDim, TWorldDim >::BF Class Reference
ug::DimFV1IBGeometry< TDim, TWorldDim >::BF Class Reference
boundary face
#include <fv1ib_geom.h>
Public Member Functions
BF ()
number detJ () const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_corner (size_t co) const
return global corner number i
const MathVector< worldDim > & global_grad (size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector () const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip () const
global integration point of bf
const MathMatrix< worldDim, dim > & JTInv () const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector () const
vector of local gradients in ip point
const MathVector< dim > & local_ip () const
local integration point of bf
size_t node_id () const
index of SubControlVolume of the bf
const MathVector< worldDim > & normal () const
outer normal on bf. Norm is equal to area
size_t num_corners () const
number of corners, that bound the scvf
size_t num_ip () const
number of integration points on bf
size_t num_sh () const
number of shape functions
number shape (size_t sh) const
value of shape function i in integration point
const number * shape_vector () const
vector of local gradients in ip point
number volume () const
volume of bf
Static Public Attributes
static const size_t numCo = traits::NumCornersOfSCVF
Number of corners of bf.
Private Attributes
number detj
MathVector< worldDim > globalIP
MathMatrix< worldDim, dim > JtInv
MathVector< dim > localIP
size_t nodeId
MathVector< worldDim > Normal
size_t numSH
MathVector< worldDim > vGlobalGrad [maxNSH]
MathVector< worldDim > vGloPos [numCo]
MathVector< dim > vLocalGrad [maxNSH]
MathVector< dim > vLocPos [numCo]
MidID vMidID [numCo]
number Vol
number vShape [maxNSH]
Friends
class DimFV1IBGeometry< dim, worldDim >
let outer class access private members
Detailed Description
template<int TDim, int TWorldDim = TDim>
class ug::DimFV1IBGeometry< TDim, TWorldDim >::BF
boundary face
Constructor & Destructor Documentation
template<int TDim, int TWorldDim = TDim> ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::BF () inline
Member Function Documentation
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::detJ () const inline
Determinant of Jacobian in integration point.
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::detj.
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::global_corner (size_t co) const inline
return global corner number i
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_corners(), UG_ASSERT, and ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vGloPos.
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::global_grad (size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_sh(), UG_ASSERT, and ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vGlobalGrad.
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::global_grad_vector () const inline
vector of global gradients in ip point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vGlobalGrad.
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::global_ip () const inline
global integration point of bf
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::globalIP.
template<int TDim, int TWorldDim = TDim> const MathMatrix<worldDim, dim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::JTInv () const inline
Transposed Inverse of Jacobian in integration point.
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::JtInv.
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::local_corner (size_t co) const inline
return local corner number i
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_corners(), UG_ASSERT, and ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vLocPos.
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::local_grad (size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_sh(), UG_ASSERT, and ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vLocalGrad.
template<int TDim, int TWorldDim = TDim> const MathVector<dim>* ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::local_grad_vector () const inline
vector of local gradients in ip point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vLocalGrad.
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::local_ip () const inline
local integration point of bf
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::localIP.
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::node_id () const inline
index of SubControlVolume of the bf
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::normal () const inline
outer normal on bf. Norm is equal to area
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::Normal.
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::num_corners () const inline
number of corners, that bound the scvf
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::numCo.
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::num_ip () const inline
number of integration points on bf
References ug::FV1IBGeometry< TElem, TWorldDim >::nip.
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::num_sh () const inline
number of shape functions
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::shape (size_t sh) const inline
value of shape function i in integration point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::num_sh(), UG_ASSERT, and ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vShape.
template<int TDim, int TWorldDim = TDim> const number* ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::shape_vector () const inline
vector of local gradients in ip point
References ug::FV1IBGeometry< TElem, TWorldDim >::SCVF::vShape.
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::volume () const inline
volume of bf
Friends And Related Function Documentation
template<int TDim, int TWorldDim = TDim> friend class DimFV1IBGeometry< dim, worldDim > friend
let outer class access private members
Member Data Documentation
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::detj private
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::globalIP private
template<int TDim, int TWorldDim = TDim> MathMatrix<worldDim,dim> ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::JtInv private
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::localIP private
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::nodeId private
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::Normal private
template<int TDim, int TWorldDim = TDim> const size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::numCo = traits::NumCornersOfSCVF static
Number of corners of bf.
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::numSH private
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::vGlobalGrad[maxNSH] private
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::vGloPos[numCo] private
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::vLocalGrad[maxNSH] private
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::vLocPos[numCo] private
template<int TDim, int TWorldDim = TDim> MidID ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::vMidID[numCo] private
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::Vol private
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::BF::vShape[maxNSH] private
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv1ib_geom.h