ug4: ug::ConstrainingFace Class Reference
ug::ConstrainingFace Class Reference
This class is used to store constrained geometric objects.
#include <grid_objects_2d.h>
Public Member Functions
void add_constrained_object (Edge *pObj)
void add_constrained_object (Face *pObj)
void add_constrained_object (Vertex *pObj)
void clear_constrained_edges ()
void clear_constrained_faces ()
void clear_constrained_objects ()
void clear_constrained_vertices ()
template<>
Vertex * constrained (size_t ind) const
template<>
Edge * constrained (size_t ind) const
template<>
Face * constrained (size_t ind) const
template<class TElem >
TElem * constrained (size_t ind) const
Edge * constrained_edge (size_t ind) const
Face * constrained_face (size_t ind) const
Vertex * constrained_vertex (size_t ind) const
bool is_constrained_object (Edge *edge)
bool is_constrained_object (Face *face)
bool is_constrained_object (Vertex *vrt)
virtual bool is_constraining () const
returns the id of the reference-object.
template<>
size_t num_constrained () const
template<>
size_t num_constrained () const
template<>
size_t num_constrained () const
template<class TElem >
size_t num_constrained () const
size_t num_constrained_edges () const
size_t num_constrained_faces () const
size_t num_constrained_vertices () const
virtual void remove_constraint_link (const Edge *e)
removes a constraint link to the grid object.
virtual void remove_constraint_link (const Face *f)
removes a constraint link to the grid object.
virtual void remove_constraint_link (const Vertex *vrt)
removes a constraint link to the grid object.
void unconstrain_object (const Edge *edge)
void unconstrain_object (const Face *face)
void unconstrain_object (const Vertex *vrt)
virtual ~ConstrainingFace ()
Public Member Functions inherited from ug::Face
virtual int base_object_id () const
virtual bool collapse_edge (std::vector< Face * > &vNewFacesOut, int edgeIndex, Vertex *newVertex, Vertex **pSubstituteVertices=NULL)
virtual bool collapse_edges (std::vector< Face * > &vNewFacesOut, std::vector< Vertex * > &vNewEdgeVertices, Vertex **pSubstituteVertices=NULL)
virtual int container_section () const
virtual Edge * create_edge (int index)
create the edge with index i and return it.
virtual void create_faces_by_edge_split (int splitEdgeIndex, Vertex *newVertex, std::vector< Face * > &vNewFacesOut, Vertex **pSubstituteVertices=NULL)
virtual EdgeDescriptor edge_desc (int index) const
returns the i-th edge of the face.
virtual void edge_desc (int index, EdgeDescriptor &edOut) const
returns the i-th edge of the face.
int get_local_side_index (EdgeVertices *e) const
returns the local index of the specified edge.
virtual std::pair< GridBaseObjectId, int > get_opposing_object (Vertex *vrt) const
returns an index to the obbject, which lies on the opposite side of the face to the given vertex.
virtual bool get_opposing_side (EdgeVertices *e, EdgeDescriptor &edOut) const
retrieves the edge-descriptor for the opposing side to the specified one.
virtual bool is_regular_ref_rule (int edgeMarks) const
returns true if the specified edgeMarks would lead to a regular refinement
uint num_edges () const
uint num_sides () const
virtual ReferenceObjectID reference_object_id () const
virtual bool refine (std::vector< Face * > &vNewFacesOut, Vertex **newFaceVertexOut, Vertex **newEdgeVertices, Vertex *newFaceVertex=NULL, Vertex **pSubstituteVertices=NULL, int snapPointIndex=-1)
virtual ~Face ()
Public Member Functions inherited from ug::GridObject
virtual GridObject * create_empty_instance () const
create an instance of the derived type
uint grid_data_index () const
Returns the grid attachment data index of a geometric object.
virtual bool is_constrained () const
returns true if the object is constrained by other objects.
virtual ~GridObject ()
Public Member Functions inherited from ug::FaceVertices
virtual size_t num_vertices () const
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual Vertex * vertex (size_t index) const
virtual ConstVertexArray vertices () const
virtual ~FaceVertices ()
Public Member Functions inherited from ug::IVertexGroup
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~IVertexGroup ()
Static Public Member Functions
static bool type_match (GridObject *pObj)
Static Public Member Functions inherited from ug::Face
static bool type_match (GridObject *pObj)
Protected Attributes
std::vector< Edge * > m_constrainedEdges
std::vector< Face * > m_constrainedFaces
std::vector< Vertex * > m_constrainedVertices
Protected Attributes inherited from ug::GridObject
uint m_gridDataIndex
Additional Inherited Members
Public Types inherited from ug::Face
typedef Face grid_base_object
typedef Volume higher_dim_base_object
typedef Edge lower_dim_base_object
typedef Edge side
typedef Volume sideof
Public Types inherited from ug::IVertexGroup
typedef Vertex *const * ConstVertexArray
Static Public Attributes inherited from ug::Face
static const int BASE_OBJECT_ID = FACE
static const bool CAN_BE_SIDE = true
static const int dim = 2
reference dimension
static const bool HAS_SIDES = true
Protected Member Functions inherited from ug::Face
virtual void set_vertex (uint index, Vertex *pVrt)
Protected Member Functions inherited from ug::GridObject
void set_grid_data_index (uint index)
ATTENTION: Use this method with extreme care!
Detailed Description
This class is used to store constrained geometric objects.
Please note, that the user is has to link and unlink constrained objects manually.
Constructor & Destructor Documentation
~ConstrainingFace()
virtual ug::ConstrainingFace::~ConstrainingFace () inline virtual
Member Function Documentation
add_constrained_object() [1/3]
void ug::ConstrainingFace::add_constrained_object (Edge * pObj) inline
References UG_ASSERT.
add_constrained_object() [2/3]
void ug::ConstrainingFace::add_constrained_object (Face * pObj) inline
References UG_ASSERT.
add_constrained_object() [3/3]
void ug::ConstrainingFace::add_constrained_object (Vertex * pObj) inline
References UG_ASSERT.
Referenced by ug::DeserializeMultiGridElements(), ug::GridReaderUGX::grid(), ug::HangingNodeRefiner_MultiGrid::perform_coarsening(), and ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex().
clear_constrained_edges()
void ug::ConstrainingFace::clear_constrained_edges () inline
Referenced by ug::HangingNodeRefinerBase< TSelector >::process_constrained_edge().
clear_constrained_faces()
void ug::ConstrainingFace::clear_constrained_faces () inline
Referenced by ug::HangingNodeRefinerBase< TSelector >::process_constrained_face().
clear_constrained_objects()
void ug::ConstrainingFace::clear_constrained_objects () inline
clear_constrained_vertices()
void ug::ConstrainingFace::clear_constrained_vertices () inline
Referenced by ug::HangingNodeRefinerBase< TSelector >::process_constrained_vertex().
constrained() [1/4]
template<> Vertex* ug::ConstrainingFace::constrained (size_t ind) const
constrained() [2/4]
template<> Edge* ug::ConstrainingFace::constrained (size_t ind) const
constrained() [3/4]
template<> Face* ug::ConstrainingFace::constrained (size_t ind) const
constrained() [4/4]
template<class TElem > TElem* ug::ConstrainingFace::constrained (size_t ind) const
constrained_edge()
Edge* ug::ConstrainingFace::constrained_edge (size_t ind) const inline
References UG_ASSERT.
Referenced by ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), and ug::SelectAssociatedConstrainedElements().
constrained_face()
Face* ug::ConstrainingFace::constrained_face (size_t ind) const inline
References UG_ASSERT.
Referenced by ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::CollectConstraining(), and ug::SelectAssociatedConstrainedElements().
constrained_vertex()
Vertex* ug::ConstrainingFace::constrained_vertex (size_t ind) const inline
References UG_ASSERT.
Referenced by ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::HangingNodeRefiner_Grid::collect_objects_for_refine(), ug::HangingNodeRefiner_MultiGrid::perform_coarsening(), and ug::SelectAssociatedConstrainedElements().
is_constrained_object() [1/3]
bool ug::ConstrainingFace::is_constrained_object (Edge * edge) inline
References ug::find().
is_constrained_object() [2/3]
bool ug::ConstrainingFace::is_constrained_object (Face * face) inline
References ug::find().
is_constrained_object() [3/3]
bool ug::ConstrainingFace::is_constrained_object (Vertex * vrt) inline
References ug::find().
Referenced by ug::CheckHangingNodeConsistency().
is_constraining()
virtual bool ug::ConstrainingFace::is_constraining () const inline virtual
returns the id of the reference-object.
returns true if the object constrains other objects. This is normally only the case for special constraining objects. The default implementation returns false.
Reimplemented from ug::GridObject.
num_constrained() [1/4]
template<> size_t ug::ConstrainingFace::num_constrained () const
num_constrained() [2/4]
template<> size_t ug::ConstrainingFace::num_constrained () const
num_constrained() [3/4]
template<> size_t ug::ConstrainingFace::num_constrained () const
num_constrained() [4/4]
template<class TElem > size_t ug::ConstrainingFace::num_constrained () const
num_constrained_edges()
size_t ug::ConstrainingFace::num_constrained_edges () const inline
Referenced by ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::CheckHangingNodeConsistency(), and ug::SelectAssociatedConstrainedElements().
num_constrained_faces()
size_t ug::ConstrainingFace::num_constrained_faces () const inline
Referenced by ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::CheckHangingNodeConsistency(), ug::CollectConstraining(), and ug::SelectAssociatedConstrainedElements().
num_constrained_vertices()
size_t ug::ConstrainingFace::num_constrained_vertices () const inline
Referenced by ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::CheckHangingNodeConsistency(), ug::HangingNodeRefiner_Grid::collect_objects_for_refine(), ug::HangingNodeRefiner_MultiGrid::perform_coarsening(), and ug::SelectAssociatedConstrainedElements().
remove_constraint_link() [1/3]
virtual void ug::ConstrainingFace::remove_constraint_link (const Edge * e) inline virtual
removes a constraint link to the grid object.
This method is e.g. called on the constraining edges of a constrained vertex as soon as the constrained vertex is deleted.
Reimplemented from ug::GridObject.
remove_constraint_link() [2/3]
virtual void ug::ConstrainingFace::remove_constraint_link (const Face * f) inline virtual
removes a constraint link to the grid object.
This method is e.g. called on the constraining edges of a constrained vertex as soon as the constrained vertex is deleted.
Reimplemented from ug::GridObject.
remove_constraint_link() [3/3]
virtual void ug::ConstrainingFace::remove_constraint_link (const Vertex * vrt) inline virtual
removes a constraint link to the grid object.
This method is e.g. called on the constraining edges of a constrained vertex as soon as the constrained vertex is deleted.
Reimplemented from ug::GridObject.
type_match()
static bool ug::ConstrainingFace::type_match (GridObject * pObj) inline static
unconstrain_object() [1/3]
void ug::ConstrainingFace::unconstrain_object (const Edge * edge) inline
References ug::find().
unconstrain_object() [2/3]
void ug::ConstrainingFace::unconstrain_object (const Face * face) inline
References ug::find().
unconstrain_object() [3/3]
void ug::ConstrainingFace::unconstrain_object (const Vertex * vrt) inline
References ug::find().
Member Data Documentation
m_constrainedEdges
std::vector<Edge*> ug::ConstrainingFace::m_constrainedEdges protected
m_constrainedFaces
std::vector<Face*> ug::ConstrainingFace::m_constrainedFaces protected
m_constrainedVertices
std::vector<Vertex*> ug::ConstrainingFace::m_constrainedVertices protected
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid_objects/grid_objects_2d.h
ugbase/lib_grid/grid_objects/grid_objects_2d.cpp