ug4: ug::ComPol_EnableSelectionStateBits< TLayout > Class Template Reference
ug::ComPol_EnableSelectionStateBits< TLayout > Class Template Reference
#include <compol_selection.h>
Public Types
typedef Layout::Element Element
typedef Layout::Type GeomObj
typedef Layout::Interface Interface
typedef Interface::const_iterator InterfaceIter
typedef TLayout Layout
Public Types inherited from pcl::ICommunicationPolicy< TLayout >
typedef Layout::Interface Interface
typedef TLayout Layout
Public Member Functions
virtual bool collect (ug::BinaryBuffer &buff, const Interface &interface)
writes writes the selection states of the interface entries
ComPol_EnableSelectionStateBits (ISelector &sel, byte stateBits)
virtual bool extract (ug::BinaryBuffer &buff, const Interface &interface)
reads marks from the given stream
virtual int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
Public Member Functions inherited from pcl::ICommunicationPolicy< TLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual ~ICommunicationPolicy ()
Public Attributes
ISelector & m_sel
byte m_stateBits
Detailed Description
template<class TLayout>
class ug::ComPol_EnableSelectionStateBits< TLayout >
Enables only the part of the selection-state for which the specified stateBits hold 1.
Member Typedef Documentation
Element
template<class TLayout > typedef Layout::Element ug::ComPol_EnableSelectionStateBits< TLayout >::Element
GeomObj
template<class TLayout > typedef Layout::Type ug::ComPol_EnableSelectionStateBits< TLayout >::GeomObj
Interface
template<class TLayout > typedef Layout::Interface ug::ComPol_EnableSelectionStateBits< TLayout >::Interface
InterfaceIter
template<class TLayout > typedef Interface::const_iterator ug::ComPol_EnableSelectionStateBits< TLayout >::InterfaceIter
Layout
template<class TLayout > typedef TLayout ug::ComPol_EnableSelectionStateBits< TLayout >::Layout
Constructor & Destructor Documentation
ComPol_EnableSelectionStateBits()
template<class TLayout > ug::ComPol_EnableSelectionStateBits< TLayout >::ComPol_EnableSelectionStateBits (ISelector & sel, byte stateBits) inline
Member Function Documentation
collect()
template<class TLayout > virtual bool ug::ComPol_EnableSelectionStateBits< TLayout >::collect (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
writes writes the selection states of the interface entries
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::ISelector::get_selection_status(), ug::ComPol_EnableSelectionStateBits< TLayout >::m_sel, and ug::BinaryBuffer::write().
extract()
template<class TLayout > virtual bool ug::ComPol_EnableSelectionStateBits< TLayout >::extract (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
reads marks from the given stream
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::ISelector::get_selection_status(), ug::ComPol_EnableSelectionStateBits< TLayout >::m_sel, ug::ComPol_EnableSelectionStateBits< TLayout >::m_stateBits, ug::BinaryBuffer::read(), and ug::ISelector::select().
get_required_buffer_size()
template<class TLayout > virtual int ug::ComPol_EnableSelectionStateBits< TLayout >::get_required_buffer_size (const Interface & interface) inline virtual
returns the size of the buffer in bytes, that will be required for interface-communication.
Determines the size of the buffer on which the extract and receive methods for the given interface will operate. If the buffer-size can't be calculated on both sides (sender and receiver) this method should return -1. This will lead to an additional communication step in which buffer-sizes will be exchanged. If the buffer-size can be calculated on both sides, it makes sense to do so, since this leads to less communication and overall improved performance. The buffer-size has to exactly match the size of required memory. Make sure that you completely fill the buffer during collect(...) and that you read all data during extract(...). The default implementation returns -1.
Reimplemented from pcl::ICommunicationPolicy< TLayout >.
Member Data Documentation
m_sel
template<class TLayout > ISelector& ug::ComPol_EnableSelectionStateBits< TLayout >::m_sel
Referenced by ug::ComPol_EnableSelectionStateBits< TLayout >::collect(), and ug::ComPol_EnableSelectionStateBits< TLayout >::extract().
m_stateBits
template<class TLayout > byte ug::ComPol_EnableSelectionStateBits< TLayout >::m_stateBits
Referenced by ug::ComPol_EnableSelectionStateBits< TLayout >::extract().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/util/compol_selection.h