ug4: ug::VertexBasedSubspace< TDomain, TAlgebra > Class Template Reference
ug::VertexBasedSubspace< TDomain, TAlgebra > Class Template Reference
Collects indices on all elements with v \in Vtx(elem)
#include <sequential_subspace_correction.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef LocalIndexSubspace< TDomain, TAlgebra, Vertex > base_type
Base type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::LocalIndexSubspace< TDomain, TAlgebra, Vertex >
typedef TAlgebra algebra_type
Algebra type.
typedef std::vector< size_t > index_vector
Local data.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef DenseMatrix< VariableArray2< number > > matrix_type_local
typedef TAlgebra::vector_type vector_type
Vector type.
typedef DenseVector< VariableArray1< number > > vector_type_local
Public Types inherited from ug::ILocalSubspace< TDomain, TAlgebra, TObject >
typedef TAlgebra algebra_type
Algebra type.
typedef GridFunction< TDomain, TAlgebra > grid_function_type
Grid function type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef DenseMatrix< VariableArray2< number > > matrix_type_local
typedef TAlgebra::vector_type vector_type
Vector type.
typedef DenseVector< VariableArray1< number > > vector_type_local
Public Member Functions
bool check (void *obj) const
void init (void *obj, const vector_type &cvec)
Extract indices for local DoFs.
VertexBasedSubspace ()
CTOR.
virtual ~VertexBasedSubspace ()
virtual DTOR
Public Member Functions inherited from ug::LocalIndexSubspace< TDomain, TAlgebra, Vertex >
virtual void extract_matrix (const matrix_type &A)
Extract matrix (on local index set)
virtual void extract_rhs (const vector_type &d)
Extract rhs (on local index set) for parallel subspace correction.
virtual void extract_rhs (const vector_type &d, const matrix_type &A, const vector_type &c)
Extract rhs (on local index set) for sequential subspace correction.
virtual void init (Vertex *, const vector_type &)=0
Called once.
virtual size_t size ()
virtual void update_solution (vector_type &u, double omega=1.0)
u = u + ck
virtual ~LocalIndexSubspace ()
virtual DTOR
Public Member Functions inherited from ug::ILocalSubspace< TDomain, TAlgebra, TObject >
virtual void init (TObject *, const vector_type &)=0
Extract local data (based on group obj).
virtual bool preprocess (const vector_type &c)
Called once.
virtual ~ILocalSubspace ()
virtual DTOR
Protected Types
typedef Vertex TObject
Additional Inherited Members
Protected Attributes inherited from ug::LocalIndexSubspace< TDomain, TAlgebra, Vertex >
matrix_type_local m_Aloc
vector_type_local m_dloc
vector_type_local m_uloc
Memory for local algebra.
index_vector m_vInd
Algebraic indices.
Detailed Description
template<typename TDomain, typename TAlgebra>
class ug::VertexBasedSubspace< TDomain, TAlgebra >
Collects indices on all elements with v \in Vtx(elem)
Member Typedef Documentation
algebra_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra ug::VertexBasedSubspace< TDomain, TAlgebra >::algebra_type
Algebra type.
base_type
template<typename TDomain , typename TAlgebra > typedef LocalIndexSubspace<TDomain, TAlgebra, Vertex> ug::VertexBasedSubspace< TDomain, TAlgebra >::base_type
Base type.
matrix_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::matrix_type ug::VertexBasedSubspace< TDomain, TAlgebra >::matrix_type
Matrix type.
TObject
template<typename TDomain , typename TAlgebra > typedef Vertex ug::VertexBasedSubspace< TDomain, TAlgebra >::TObject protected
vector_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::vector_type ug::VertexBasedSubspace< TDomain, TAlgebra >::vector_type
Vector type.
Constructor & Destructor Documentation
VertexBasedSubspace()
template<typename TDomain , typename TAlgebra > ug::VertexBasedSubspace< TDomain, TAlgebra >::VertexBasedSubspace () inline
CTOR.
~VertexBasedSubspace()
template<typename TDomain , typename TAlgebra > virtual ug::VertexBasedSubspace< TDomain, TAlgebra >::~VertexBasedSubspace () inline virtual
virtual DTOR
Member Function Documentation
check()
template<typename TDomain , typename TAlgebra > bool ug::VertexBasedSubspace< TDomain, TAlgebra >::check (void * obj) const inline
Referenced by ug::VertexBasedSubspace< TDomain, TAlgebra >::init().
init()
template<typename TDomain , typename TAlgebra > void ug::VertexBasedSubspace< TDomain, TAlgebra >::init (void * obj, const vector_type & cvec) inline
Extract indices for local DoFs.
References ug::VertexBasedSubspace< TDomain, TAlgebra >::check(), ug::GridFunction< TDomain, TAlgebra >::collect_associated(), ug::LocalIndexSubspace< TDomain, TAlgebra, Vertex >::m_vInd, and UG_ASSERT.
The documentation for this class was generated from the following file:
ugbase/lib_disc/operator/linear_operator/subspace_correction/sequential_subspace_correction.h