ug4: ug::VertexCenteredVankaSubspace< TDomain, TAlgebra > Class Template Reference
ug::VertexCenteredVankaSubspace< TDomain, TAlgebra > Class Template Reference
Collects indices on all elements with v \in Vtx(elem)
#include <sequential_subspace_correction.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef LocalDoFSubspace< TDomain, TAlgebra, Vertex > base_type
Base type.
typedef GridFunction< TDomain, TAlgebra > grid_function_type
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::LocalDoFSubspace< TDomain, TAlgebra, Vertex >
typedef TAlgebra algebra_type
Algebra type.
typedef std::vector< DoFIndex > index_vector
Local data.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef DenseMatrix< VariableArray2< number > > matrix_type_local
typedef TAlgebra::vector_type vector_type
Vector type.
typedef DenseVector< VariableArray1< number > > vector_type_local
Public Types inherited from ug::ILocalSubspace< TDomain, TAlgebra, TObject >
typedef TAlgebra algebra_type
Algebra type.
typedef GridFunction< TDomain, TAlgebra > grid_function_type
Grid function type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef DenseMatrix< VariableArray2< number > > matrix_type_local
typedef TAlgebra::vector_type vector_type
Vector type.
typedef DenseVector< VariableArray1< number > > vector_type_local
Public Member Functions
void init (Vertex *groupObj, const vector_type &cvec)
Extract indices for single vertex.
bool preprocess (const vector_type &cvec)
OVERRIDE.
VertexCenteredVankaSubspace (const std::vector< std::string > &vVtxCmp, const std::vector< std::string > &vElemCmp)
CTOR.
virtual ~VertexCenteredVankaSubspace ()
virtual DTOR
Public Member Functions inherited from ug::LocalDoFSubspace< TDomain, TAlgebra, Vertex >
bool check (void *obj) const
virtual void extract_matrix (const matrix_type &A)
Extract matrix (on local index set)
virtual void extract_rhs (const vector_type &d)
Extract rhs (on local index set) for parallel subspace correction.
virtual void extract_rhs (const vector_type &d, const matrix_type &A, const vector_type &c)
Extract rhs (on local index set) for sequential subspace correction.
virtual size_t size ()
virtual void update_solution (vector_type &u, double omega=1.0)
u = u + ck
virtual ~LocalDoFSubspace ()
virtual DTOR
Public Member Functions inherited from ug::ILocalSubspace< TDomain, TAlgebra, TObject >
virtual void init (TObject *, const vector_type &)=0
Extract local data (based on group obj).
virtual ~ILocalSubspace ()
virtual DTOR
Protected Member Functions
void extract_ids (const grid_function_type *c)
Extracts function IDs.
Protected Attributes
std::vector< std::string > m_vElemCmp
std::vector< size_t > m_vElemFct
std::vector< std::string > m_vVtxCmp
std::vector< size_t > m_vVtxFct
Protected Attributes inherited from ug::LocalDoFSubspace< TDomain, TAlgebra, Vertex >
matrix_type_local m_Aloc
vector_type_local m_dloc
vector_type_local m_uloc
std::vector< DoFIndex > m_vInd
Algebraic indices.
Detailed Description
template<typename TDomain, typename TAlgebra>
class ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >
Collects indices on all elements with v \in Vtx(elem)
Member Typedef Documentation
algebra_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::algebra_type
Algebra type.
base_type
template<typename TDomain , typename TAlgebra > typedef LocalDoFSubspace<TDomain, TAlgebra, Vertex> ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::base_type
Base type.
grid_function_type
template<typename TDomain , typename TAlgebra > typedef GridFunction<TDomain, TAlgebra> ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::grid_function_type
matrix_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::matrix_type ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::matrix_type
Matrix type.
vector_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::vector_type ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::vector_type
Vector type.
Constructor & Destructor Documentation
VertexCenteredVankaSubspace()
template<typename TDomain , typename TAlgebra > ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::VertexCenteredVankaSubspace (const std::vector< std::string > & vVtxCmp, const std::vector< std::string > & vElemCmp) inline
CTOR.
~VertexCenteredVankaSubspace()
template<typename TDomain , typename TAlgebra > virtual ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::~VertexCenteredVankaSubspace () inline virtual
virtual DTOR
Member Function Documentation
extract_ids()
template<typename TDomain , typename TAlgebra > void ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::extract_ids (const grid_function_type * c) inline protected
Extracts function IDs.
References ug::GridFunction< TDomain, TAlgebra >::approx_space(), ConstSmartPtr< T, FreePolicy >::invalid(), ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::m_vElemCmp, ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::m_vElemFct, ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::m_vVtxCmp, ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::m_vVtxFct, and UG_COND_THROW.
Referenced by ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::preprocess().
init()
template<typename TDomain , typename TAlgebra > void ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::init (Vertex * groupObj, const vector_type & cvec) inline virtual
Extract indices for single vertex.
Implements ug::LocalDoFSubspace< TDomain, TAlgebra, Vertex >.
References ug::GridFunction< TDomain, TAlgebra >::collect_associated(), ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::m_vElemFct, ug::LocalDoFSubspace< TDomain, TAlgebra, Vertex >::m_vInd, and ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::m_vVtxFct.
preprocess()
template<typename TDomain , typename TAlgebra > bool ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::preprocess (const vector_type & cvec) inline virtual
OVERRIDE.
Reimplemented from ug::ILocalSubspace< TDomain, TAlgebra, TObject >.
References ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::extract_ids(), and UG_COND_THROW.
Member Data Documentation
m_vElemCmp
template<typename TDomain , typename TAlgebra > std::vector<std::string> ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::m_vElemCmp protected
Referenced by ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::extract_ids().
m_vElemFct
template<typename TDomain , typename TAlgebra > std::vector<size_t> ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::m_vElemFct protected
Referenced by ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::extract_ids(), and ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::init().
m_vVtxCmp
template<typename TDomain , typename TAlgebra > std::vector<std::string> ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::m_vVtxCmp protected
Referenced by ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::extract_ids().
m_vVtxFct
template<typename TDomain , typename TAlgebra > std::vector<size_t> ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::m_vVtxFct protected
Referenced by ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::extract_ids(), and ug::VertexCenteredVankaSubspace< TDomain, TAlgebra >::init().
The documentation for this class was generated from the following file:
ugbase/lib_disc/operator/linear_operator/subspace_correction/sequential_subspace_correction.h