ug4: ug::StrongNegativeConnectionsByBlockNorm Class Reference
ug::StrongNegativeConnectionsByBlockNorm Class Reference
Adds 'strong negative connections' to graph.
#include <block_gauss_seidel.h>
Public Member Functions
template<typename TRowType >
void find (const TRowType &Ci, size_t i, cgraph &graph)
StrongNegativeConnectionsByBlockNorm (double theta)
Protected Attributes
double m_theta
Detailed Description
Adds 'strong negative connections' to graph.
Criterion: \(-a_{ij} \ge \epsilon \max_{a_{ik}<0} |a_{ik}| \)
Constructor & Destructor Documentation
StrongNegativeConnectionsByBlockNorm()
ug::StrongNegativeConnectionsByBlockNorm::StrongNegativeConnectionsByBlockNorm (double theta) inline
Member Function Documentation
find()
template<typename TRowType > void ug::StrongNegativeConnectionsByBlockNorm::find (const TRowType & Ci, size_t i, cgraph & graph) inline
References ug::BlockNorm(), m_theta, and ug::cgraph::set_connection().
Referenced by ug::CreateStrongConnectionGraphForSystems().
Member Data Documentation
m_theta
double ug::StrongNegativeConnectionsByBlockNorm::m_theta protected
Referenced by find().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/preconditioner/block_gauss_seidel.h