ug4: ug::LU< TAlgebra > Class Template Reference
ug::LU< TAlgebra > Class Template Reference
#include <lu.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef IMatrixOperatorInverse< matrix_type, vector_type > base_type
Base type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
Public Types inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::ILinearIterator< X, Y >
typedef Y codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Member Functions
virtual bool apply (vector_type &u, const vector_type &f)
Compute u = L^{-1} * f.
bool apply_lu (vector_type &x, const vector_type &b)
virtual bool apply_return_defect (vector_type &u, vector_type &f)
Compute u = L^{-1} * f AND return defect f := f - L*u.
virtual std::string config_string () const
returns information about configuration parameters
virtual bool init (SmartPtr< ILinearOperator< Y, X > > A)
initializes this inverse operator for a linear operator
virtual bool init (SmartPtr< ILinearOperator< Y, X > > A, const Y &u)
initializes this inverse operator for a linear operator
virtual bool init (SmartPtr< MatrixOperator< M, Y, X > > A)=0
initializes this inverse operator for a matrix-based operator
virtual bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
set operator L, that will be inverted
bool init_lu (const matrix_type *pA)
initializes the solver for a matrix A
LU ()
constructor
virtual const char * name () const
returns the name of the operator inverse
void set_info (bool b)
void set_minimum_for_sparse (size_t N)
void set_show_progress (bool b)
void set_sort_sparse (bool b)
virtual bool supports_parallel () const
returns if parallel solving is supported
virtual ~LU ()
Destructor.
Public Member Functions inherited from ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > A)
initializes this inverse operator for a linear operator
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > A, const TAlgebra::vector_type &u)
initializes this inverse operator for a linear operator
virtual bool init (SmartPtr< MatrixOperator< TAlgebra::matrix_type, TAlgebra::vector_type, TAlgebra::vector_type > > A)=0
initializes this inverse operator for a matrix-based operator
virtual ~IMatrixOperatorInverse ()
virtual destructor
Public Member Functions inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
virtual bool apply_update_defect (TAlgebra::vector_type &u, TAlgebra::vector_type &f)
virtual SmartPtr< ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > > clone ()
clone
SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > convergence_check ()
returns the convergence check
ConstSmartPtr< IConvergenceCheck< TAlgebra::vector_type > > convergence_check () const
returns the convergence check
number defect () const
returns the current defect
ILinearOperatorInverse ()
constructor setting convergence check to (100, 1e-12, 1e-12, true)
ILinearOperatorInverse (SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > spConvCheck)
Default constructor.
SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > linear_operator ()
returns the current Operator this Inverse Operator is initialized for
number reduction () const
returns the current relative reduction
void set_convergence_check (SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > spConvCheck)
set the convergence check
virtual int standard_offset () const
returns the standard offset for output
int step () const
returns the current number of steps
virtual ~ILinearOperatorInverse ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< X, Y >
virtual bool apply (Y &c, const X &d)=0
compute new correction c = B*d
virtual bool apply_update_defect (Y &c, X &d)=0
compute new correction c = B*d and update defect d := d - A*c
SmartPtr< IDamping< X, Y > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< X, Y > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< Y, X > > J, const Y &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< Y, X > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< X, Y > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Protected Attributes
SmartPtr< ILUTScalarPreconditioner< algebra_type > > ilut_scalar
CPUAlgebra::vector_type m_b
bool m_bDense
bool m_bInfo
bool m_bShowProgress
bool m_bSortSparse
size_t m_iMinimumForSparse
DenseMatrixInverse< DenseMatrix< VariableArray2< double > > > m_mat
inverse
const matrix_type * m_pMatrix
matrix to invert
size_t m_size
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spOperator
Operator to invert.
DenseVector< VariableArray1< double > > m_tmp
CPUAlgebra::vector_type m_u
Protected Attributes inherited from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >
SmartPtr< IConvergenceCheck< TAlgebra::vector_type > > m_spConvCheck
smart pointer holding the convergence check
SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > m_spLinearOperator
Operator that is inverted by this Inverse Operator.
Protected Attributes inherited from ug::ILinearIterator< X, Y >
SmartPtr< IDamping< X, Y > > m_spDamping
the scaling
Private Member Functions
bool init_dense (const matrix_type &A)
returns name of solver
bool init_sparse (const matrix_type &A)
void init_var (const matrix_type &A)
void print_info (const matrix_type &A)
bool solve_dense (vector_type &x, const vector_type &b)
bool solve_sparse (vector_type &x, const vector_type &b)
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::LU< TAlgebra >::algebra_type
Algebra type.
base_type
template<typename TAlgebra > typedef IMatrixOperatorInverse<matrix_type,vector_type> ug::LU< TAlgebra >::base_type
Base type.
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::LU< TAlgebra >::matrix_type
Matrix type.
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::LU< TAlgebra >::vector_type
Vector type.
Constructor & Destructor Documentation
LU()
template<typename TAlgebra > ug::LU< TAlgebra >::LU () inline
constructor
References ug::LU< TAlgebra >::m_iMinimumForSparse.
~LU()
template<typename TAlgebra > virtual ug::LU< TAlgebra >::~LU () inline virtual
Destructor.
Member Function Documentation
apply()
template<typename TAlgebra > virtual bool ug::LU< TAlgebra >::apply (vector_type & u, const vector_type & f) inline virtual
Compute u = L^{-1} * f.
Implements ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >.
References ug::LU< TAlgebra >::apply_lu(), ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >::convergence_check(), ug::LU< TAlgebra >::m_pMatrix, PROFILE_FUNC, ug::PST_ADDITIVE, ug::PST_CONSISTENT, UG_ASSERT, and UG_LOG.
Referenced by ug::LU< TAlgebra >::apply_return_defect().
apply_lu()
template<typename TAlgebra > bool ug::LU< TAlgebra >::apply_lu (vector_type & x, const vector_type & b) inline
References ug::GetSize(), ug::LU< TAlgebra >::m_bDense, ug::LU< TAlgebra >::m_pMatrix, ug::LU< TAlgebra >::m_size, PROFILE_BEGIN_GROUP, ug::LU< TAlgebra >::solve_dense(), ug::LU< TAlgebra >::solve_sparse(), UG_ASSERT, and UG_CATCH_THROW.
Referenced by ug::LU< TAlgebra >::apply().
apply_return_defect()
template<typename TAlgebra > virtual bool ug::LU< TAlgebra >::apply_return_defect (vector_type & u, vector_type & f) inline virtual
Compute u = L^{-1} * f AND return defect f := f - L*u.
Implements ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >.
References ug::LU< TAlgebra >::apply(), ug::LU< TAlgebra >::m_pMatrix, PROFILE_BEGIN_GROUP, and UG_LOG.
config_string()
template<typename TAlgebra > virtual std::string ug::LU< TAlgebra >::config_string () const inline virtual
returns information about configuration parameters
this should return necessary information about parameters and possibly calling config_string of subcomponents.
Returns
std::string necessary information about configuration parameters
Reimplemented from ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
References ug::LU< TAlgebra >::m_iMinimumForSparse.
init() [1/4]
template<typename TAlgebra > virtual bool ug::IMatrixOperatorInverse< M, X, Y >::init inline
initializes this inverse operator for a linear operator
This method implements the ILinearOperatorInverse interface method. Basically, the request is forwarded to the matrix-based init method, if the the operator is matrix-based. If the operator is not matrix-based this inverse can not be used and false is returned
Parameters
[in] A linear matrix-based operator to invert
Returns
bool success flag
init() [2/4]
template<typename TAlgebra > virtual bool ug::IMatrixOperatorInverse< M, X, Y >::init inline
initializes this inverse operator for a linear operator
This method implements the ILinearOperatorInverse interface method. Basically, the request is forwarded to the matrix-based init method, if the the operator is matrix-based. If the operator is not matrix-based this inverse can not be used and false is returned
Parameters
[in] A linear matrix-based operator to invert
[in] u linearization point
Returns
bool success flag
init() [3/4]
template<typename TAlgebra > virtual bool ug::IMatrixOperatorInverse< M, X, Y >::init
initializes this inverse operator for a matrix-based operator
This method passes the operator A that is inverted by this operator. In addition some preparation step can be made.
Parameters
[in] A linear matrix-basewd operator to invert
Returns
bool success flag
init() [4/4]
template<typename TAlgebra > virtual bool ug::LU< TAlgebra >::init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op) inline virtual
set operator L, that will be inverted
References ug::LU< TAlgebra >::init_lu(), ug::LU< TAlgebra >::m_spOperator, and UG_LOG.
init_dense()
template<typename TAlgebra > bool ug::LU< TAlgebra >::init_dense (const matrix_type & A) inline private
returns name of solver
References ug::GetBytesSizeString(), ug::GetDenseDoubleFromSparse(), ug::LU< TAlgebra >::m_bDense, ug::LU< TAlgebra >::m_bInfo, ug::LU< TAlgebra >::m_mat, ug::LU< TAlgebra >::m_size, ug::LU< TAlgebra >::print_info(), PROFILE_FUNC, UG_LOG, and UG_THROW.
Referenced by ug::LU< TAlgebra >::init_lu().
init_lu()
template<typename TAlgebra > bool ug::LU< TAlgebra >::init_lu (const matrix_type * pA) inline
initializes the solver for a matrix A
References ug::LU< TAlgebra >::init_dense(), ug::LU< TAlgebra >::init_sparse(), ug::LU< TAlgebra >::init_var(), ug::LU< TAlgebra >::m_iMinimumForSparse, ug::LU< TAlgebra >::m_pMatrix, ug::LU< TAlgebra >::m_size, PROFILE_BEGIN_GROUP, PROFILE_FUNC, UG_ASSERT, UG_CATCH_THROW, and UG_LOG.
Referenced by ug::LU< TAlgebra >::init().
init_sparse()
template<typename TAlgebra > bool ug::LU< TAlgebra >::init_sparse (const matrix_type & A) inline private
References ug::LU< TAlgebra >::ilut_scalar, ug::LU< TAlgebra >::m_bDense, ug::LU< TAlgebra >::m_bInfo, ug::LU< TAlgebra >::m_bShowProgress, ug::LU< TAlgebra >::m_bSortSparse, make_sp(), ug::LU< TAlgebra >::print_info(), PROFILE_FUNC, UG_CATCH_THROW, and UG_LOG.
Referenced by ug::LU< TAlgebra >::init_lu().
init_var()
template<typename TAlgebra > void ug::LU< TAlgebra >::init_var (const matrix_type & A) inline private
References UG_ASSERT.
Referenced by ug::LU< TAlgebra >::init_lu().
name()
template<typename TAlgebra > virtual const char* ug::LU< TAlgebra >::name () const inline virtual
returns the name of the operator inverse
This method returns the name of the inverse operator. This function is typically needed, when the inverse operator is used inside of another and some debug output should be printed
Returns
const char* name of inverse operator
Implements ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
print_info()
template<typename TAlgebra > void ug::LU< TAlgebra >::print_info (const matrix_type & A) inline private
References UG_LOG.
Referenced by ug::LU< TAlgebra >::init_dense(), and ug::LU< TAlgebra >::init_sparse().
set_info()
template<typename TAlgebra > void ug::LU< TAlgebra >::set_info (bool b) inline
References ug::LU< TAlgebra >::m_bInfo.
set_minimum_for_sparse()
template<typename TAlgebra > void ug::LU< TAlgebra >::set_minimum_for_sparse (size_t N) inline
References ug::LU< TAlgebra >::m_iMinimumForSparse.
set_show_progress()
template<typename TAlgebra > void ug::LU< TAlgebra >::set_show_progress (bool b) inline
References ug::LU< TAlgebra >::m_bShowProgress.
set_sort_sparse()
template<typename TAlgebra > void ug::LU< TAlgebra >::set_sort_sparse (bool b) inline
References ug::LU< TAlgebra >::m_bSortSparse.
solve_dense()
template<typename TAlgebra > bool ug::LU< TAlgebra >::solve_dense (vector_type & x, const vector_type & b) inline private
References ug::BlockRef(), ug::GetSize(), ug::LU< TAlgebra >::m_mat, ug::LU< TAlgebra >::m_size, ug::LU< TAlgebra >::m_tmp, PROFILE_FUNC, and UG_CATCH_THROW.
Referenced by ug::LU< TAlgebra >::apply_lu().
solve_sparse()
template<typename TAlgebra > bool ug::LU< TAlgebra >::solve_sparse (vector_type & x, const vector_type & b) inline private
References ug::LU< TAlgebra >::ilut_scalar, and PROFILE_FUNC.
Referenced by ug::LU< TAlgebra >::apply_lu().
supports_parallel()
template<typename TAlgebra > virtual bool ug::LU< TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >.
Member Data Documentation
ilut_scalar
template<typename TAlgebra > SmartPtr<ILUTScalarPreconditioner<algebra_type> > ug::LU< TAlgebra >::ilut_scalar protected
Referenced by ug::LU< TAlgebra >::init_sparse(), and ug::LU< TAlgebra >::solve_sparse().
m_b
template<typename TAlgebra > CPUAlgebra::vector_type ug::LU< TAlgebra >::m_b protected
m_bDense
template<typename TAlgebra > bool ug::LU< TAlgebra >::m_bDense protected
Referenced by ug::LU< TAlgebra >::apply_lu(), ug::LU< TAlgebra >::init_dense(), and ug::LU< TAlgebra >::init_sparse().
m_bInfo
template<typename TAlgebra > bool ug::LU< TAlgebra >::m_bInfo protected
Referenced by ug::LU< TAlgebra >::init_dense(), ug::LU< TAlgebra >::init_sparse(), and ug::LU< TAlgebra >::set_info().
m_bShowProgress
template<typename TAlgebra > bool ug::LU< TAlgebra >::m_bShowProgress protected
Referenced by ug::LU< TAlgebra >::init_sparse(), and ug::LU< TAlgebra >::set_show_progress().
m_bSortSparse
template<typename TAlgebra > bool ug::LU< TAlgebra >::m_bSortSparse protected
Referenced by ug::LU< TAlgebra >::init_sparse(), and ug::LU< TAlgebra >::set_sort_sparse().
m_iMinimumForSparse
template<typename TAlgebra > size_t ug::LU< TAlgebra >::m_iMinimumForSparse protected
Referenced by ug::LU< TAlgebra >::config_string(), ug::LU< TAlgebra >::init_lu(), ug::LU< TAlgebra >::LU(), and ug::LU< TAlgebra >::set_minimum_for_sparse().
m_mat
template<typename TAlgebra > DenseMatrixInverse<DenseMatrix<VariableArray2<double> > > ug::LU< TAlgebra >::m_mat protected
inverse
Referenced by ug::LU< TAlgebra >::init_dense(), and ug::LU< TAlgebra >::solve_dense().
m_pMatrix
template<typename TAlgebra > const matrix_type* ug::LU< TAlgebra >::m_pMatrix protected
matrix to invert
Referenced by ug::LU< TAlgebra >::apply(), ug::LU< TAlgebra >::apply_lu(), ug::LU< TAlgebra >::apply_return_defect(), and ug::LU< TAlgebra >::init_lu().
m_size
template<typename TAlgebra > size_t ug::LU< TAlgebra >::m_size protected
Referenced by ug::LU< TAlgebra >::apply_lu(), ug::LU< TAlgebra >::init_dense(), ug::LU< TAlgebra >::init_lu(), and ug::LU< TAlgebra >::solve_dense().
m_spOperator
template<typename TAlgebra > SmartPtr<MatrixOperator<matrix_type, vector_type> > ug::LU< TAlgebra >::m_spOperator protected
Operator to invert.
Referenced by ug::LU< TAlgebra >::init().
m_tmp
template<typename TAlgebra > DenseVector<VariableArray1<double> > ug::LU< TAlgebra >::m_tmp protected
Referenced by ug::LU< TAlgebra >::solve_dense().
m_u
template<typename TAlgebra > CPUAlgebra::vector_type ug::LU< TAlgebra >::m_u protected
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/linear_solver/lu.h