ug4: ug::IBalanceWeights Class Reference
ug::IBalanceWeights Class Reference
Lib_grid_parallelization_distribution
#include <partitioner.h>
Public Member Functions
virtual number get_refined_weight (Edge *e)
virtual number get_refined_weight (Face *e)
todo: use a more sophisticated implementation
virtual number get_refined_weight (Vertex *e)
virtual number get_refined_weight (Volume *e)
todo: use a more sophisticated implementation
virtual number get_weight (Edge *)
virtual number get_weight (Face *)
virtual number get_weight (Vertex *)
virtual number get_weight (Volume *)
virtual bool has_level_offsets ()
virtual void refresh_weights (int baseLevel)
virtual ~IBalanceWeights ()
virtual bool consider_in_level_above (Vertex *)
Relative indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Edge *)
Relative indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Face *)
Relative indicator in which level the specifed elements should be partitioned.
virtual bool consider_in_level_above (Volume *)
Relative indicator in which level the specifed elements should be partitioned.
Constructor & Destructor Documentation
~IBalanceWeights()
virtual ug::IBalanceWeights::~IBalanceWeights () inline virtual
Member Function Documentation
consider_in_level_above() [1/4]
virtual bool ug::IBalanceWeights::consider_in_level_above (Edge *) inline virtual
Relative indicator in which level the specifed elements should be partitioned.
If this method returns true, one should use get_refined_weight instead of get_weight.
Reimplemented in ug::BalanceWeightsRefMarks.
consider_in_level_above() [2/4]
virtual bool ug::IBalanceWeights::consider_in_level_above (Face *) inline virtual
Relative indicator in which level the specifed elements should be partitioned.
If this method returns true, one should use get_refined_weight instead of get_weight.
Reimplemented in ug::BalanceWeightsRefMarks.
consider_in_level_above() [3/4]
virtual bool ug::IBalanceWeights::consider_in_level_above (Vertex *) inline virtual
Relative indicator in which level the specifed elements should be partitioned.
If this method returns true, one should use get_refined_weight instead of get_weight.
Reimplemented in ug::BalanceWeightsRefMarks.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level().
consider_in_level_above() [4/4]
virtual bool ug::IBalanceWeights::consider_in_level_above (Volume *) inline virtual
Relative indicator in which level the specifed elements should be partitioned.
If this method returns true, one should use get_refined_weight instead of get_weight.
Reimplemented in ug::BalanceWeightsRefMarks.
get_refined_weight() [1/4]
virtual number ug::IBalanceWeights::get_refined_weight (Edge * e) inline virtual
Reimplemented in ug::BalanceWeightsRefMarks.
References get_weight().
get_refined_weight() [2/4]
virtual number ug::IBalanceWeights::get_refined_weight (Face * e) inline virtual
todo: use a more sophisticated implementation
Reimplemented in ug::BalanceWeightsRefMarks.
References get_weight().
get_refined_weight() [3/4]
virtual number ug::IBalanceWeights::get_refined_weight (Vertex * e) inline virtual
Reimplemented in ug::BalanceWeightsRefMarks.
References get_weight().
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level().
get_refined_weight() [4/4]
virtual number ug::IBalanceWeights::get_refined_weight (Volume * e) inline virtual
todo: use a more sophisticated implementation
Reimplemented in ug::BalanceWeightsRefMarks.
References get_weight().
get_weight() [1/4]
virtual number ug::IBalanceWeights::get_weight (Edge *) inline virtual
Reimplemented in ug::AnisotropicBalanceWeights< dim >, ug::StdBalanceWeights, and ug::BalanceWeightsLuaCallback< TDomain >.
get_weight() [2/4]
virtual number ug::IBalanceWeights::get_weight (Face *) inline virtual
Reimplemented in ug::AnisotropicBalanceWeights< dim >, ug::StdBalanceWeights, and ug::BalanceWeightsLuaCallback< TDomain >.
get_weight() [3/4]
virtual number ug::IBalanceWeights::get_weight (Vertex *) inline virtual
Reimplemented in ug::AnisotropicBalanceWeights< dim >, ug::StdBalanceWeights, and ug::BalanceWeightsLuaCallback< TDomain >.
Referenced by ug::LoadBalancer::estimate_distribution_quality_impl(), ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level(), ug::BalanceWeightsRefMarks::get_refined_weight(), and get_refined_weight().
get_weight() [4/4]
virtual number ug::IBalanceWeights::get_weight (Volume *) inline virtual
Reimplemented in ug::AnisotropicBalanceWeights< dim >, ug::StdBalanceWeights, and ug::BalanceWeightsLuaCallback< TDomain >.
has_level_offsets()
virtual bool ug::IBalanceWeights::has_level_offsets () inline virtual
Reimplemented in ug::BalanceWeightsRefMarks.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::gather_weights_from_level().
refresh_weights()
virtual void ug::IBalanceWeights::refresh_weights (int baseLevel) inline virtual
Reimplemented in ug::StdBalanceWeights, and ug::AnisotropicBalanceWeights< dim >.
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/partitioner.h