ug4: ug::node_tree::Traverser Class Reference
ug::node_tree::Traverser Class Reference
Derivates of a Traverser can be used to traverse a scenegraph.
#include <traverser.h>
Public Member Functions
Traverser ()
virtual ~Traverser ()
Protected Member Functions
void apply (SPNode &node)
virtual void handle_boxed_group (BoxedGroupNode *boxedGroup)
virtual void handle_group (GroupNode *group)
template<typename HandlerType >
void register_handler_function (unsigned int oc, HandlerType func)
void traverse_object (Object *obj)
Private Types
typedef void(Traverser::* HandlerFunc) (Object *obj)
Private Member Functions
bool handler_function_registered (unsigned int oc)
Private Attributes
std::vector< HandlerFunc > m_vHandlerFuncs
Detailed Description
Derivates of a Traverser can be used to traverse a scenegraph.
Member Typedef Documentation
HandlerFunc
typedef void(Traverser::* ug::node_tree::Traverser::HandlerFunc) (Object *obj) private
Constructor & Destructor Documentation
Traverser()
ug::node_tree::Traverser::Traverser ()
References handle_boxed_group(), handle_group(), m_vHandlerFuncs, ug::node_tree::OC_BOXED_GROUP_NODE, ug::node_tree::OC_GROUP_NODE, ug::node_tree::OC_NODES_END, and register_handler_function().
~Traverser()
ug::node_tree::Traverser::~Traverser () virtual
Member Function Documentation
apply()
void ug::node_tree::Traverser::apply (SPNode & node) protected
References SmartPtr< T, FreePolicy >::get(), and traverse_object().
handle_boxed_group()
void ug::node_tree::Traverser::handle_boxed_group (BoxedGroupNode * boxedGroup) protected virtual
Reimplemented in ug::node_tree::Traverser_ProjectPoint, and ug::node_tree::Traverser_IntersectFaces.
References handle_group().
Referenced by ug::node_tree::Traverser_CollisionTree::handle_collision_tree_root(), and Traverser().
handle_group()
void ug::node_tree::Traverser::handle_group (GroupNode * group) protected virtual
Reimplemented in ug::node_tree::Traverser_ProjectPoint.
References SmartPtr< T, FreePolicy >::get(), ug::node_tree::GroupNode::get_child(), ug::node_tree::GroupNode::num_children(), and traverse_object().
Referenced by handle_boxed_group(), and Traverser().
handler_function_registered()
bool ug::node_tree::Traverser::handler_function_registered (unsigned int oc) private
References m_vHandlerFuncs.
Referenced by traverse_object().
register_handler_function()
template<typename HandlerType > void ug::node_tree::Traverser::register_handler_function (unsigned int oc, HandlerType func) protected
References func(), and m_vHandlerFuncs.
Referenced by Traverser(), and ug::node_tree::Traverser_CollisionTree::Traverser_CollisionTree().
traverse_object()
void ug::node_tree::Traverser::traverse_object (Object * obj) protected
References ug::node_tree::Object::getObjectCode(), handler_function_registered(), and m_vHandlerFuncs.
Referenced by apply(), and handle_group().
Member Data Documentation
m_vHandlerFuncs
std::vector<HandlerFunc> ug::node_tree::Traverser::m_vHandlerFuncs private
Referenced by handler_function_registered(), register_handler_function(), traverse_object(), and Traverser().
The documentation for this class was generated from the following files:
ugbase/common/node_tree/traverser.h
ugbase/common/node_tree/traverser.cpp