ug4: ug::RowSendingScheme< matrix_type > Class Template Reference
ug::RowSendingScheme< matrix_type > Class Template Reference
#include <row_sending_scheme.h>
Public Member Functions
void add_rows_to_matrix (matrix_type &mat)
void issue_send (pcl::InterfaceCommunicator< IndexLayout > &communicator, const IndexLayout &sendLayout, const IndexLayout &receiveLayout)
void process (const IndexLayout &receiveLayout)
RowSendingScheme (matrix_type &_mat, ParallelNodes &_PN)
void set_create_new_nodes (bool bCreateNewNodes)
void set_rows_in_matrix (matrix_type &mat)
Private Types
typedef std::map< int, BinaryBuffer > BufferMap
typedef matrix_type::connection connection
Private Member Functions
void issue_send (BinaryBuffer &buf, int pid, int localRowIndex)
void process (BinaryBuffer &buf, int pid, size_t localRowIndex)
void resize_mat (matrix_type &mat)
Private Attributes
size_t colMax
std::map< size_t, std::vector< connection > > connections
bool m_bCreateNewNodes
const matrix_type & mat
ParallelNodes & PN
size_t rowMax
BufferMap rowsBufferMap
Member Typedef Documentation
BufferMap
template<typename matrix_type > typedef std::map<int, BinaryBuffer> ug::RowSendingScheme< matrix_type >::BufferMap private
connection
template<typename matrix_type > typedef matrix_type::connection ug::RowSendingScheme< matrix_type >::connection private
Constructor & Destructor Documentation
RowSendingScheme()
template<typename matrix_type > ug::RowSendingScheme< matrix_type >::RowSendingScheme (matrix_type & _mat, ParallelNodes & _PN) inline
Member Function Documentation
add_rows_to_matrix()
template<typename matrix_type > void ug::RowSendingScheme< matrix_type >::add_rows_to_matrix (matrix_type & mat) inline
References ug::RowSendingScheme< matrix_type >::connections, ug::RowSendingScheme< matrix_type >::mat, and ug::RowSendingScheme< matrix_type >::resize_mat().
Referenced by ug::GenerateOverlapClass< matrix_type >::communicate().
issue_send() [1/2]
template<typename matrix_type > void ug::RowSendingScheme< matrix_type >::issue_send (BinaryBuffer & buf, int pid, int localRowIndex) inline private
Put row 'localRowIndex' into the binary buffer 'buf' PN keeps track about which indices exist on the recieving pid
Parameters
buf buf to write it to
pid receiving pid
localRowIndex local row index
Note
modifies PN by specifying which nodes we sent to pid
References ug::ParallelNodes::create_node(), ug::LIB_ALG_MATRIX, ug::ParallelNodes::local_to_global(), ug::RowSendingScheme< matrix_type >::m_bCreateNewNodes, ug::RowSendingScheme< matrix_type >::mat, num_connections(), ug::RowSendingScheme< matrix_type >::PN, ug::Serialize(), and UG_DLOG.
issue_send() [2/2]
template<typename matrix_type > void ug::RowSendingScheme< matrix_type >::issue_send (pcl::InterfaceCommunicator< IndexLayout > & communicator, const IndexLayout & sendLayout, const IndexLayout & receiveLayout) inline
for processor pid in sendLayout for i in interface send row i to processor pid for processor pid in receivingLayout issue receive data issue
Parameters
communicator
sendLayout
receiveLayout
See also
issue_send
References pcl::SingleLevelLayout< TInterface >::begin(), ug::BinaryBuffer::buffer(), pcl::SingleLevelLayout< TInterface >::end(), ug::ParallelNodes::issue(), ug::LIB_ALG_MATRIX, ug::RowSendingScheme< matrix_type >::PN, pcl::SingleLevelLayout< TInterface >::proc_id(), pcl::InterfaceCommunicator< TLayout >::receive_raw(), ug::RowSendingScheme< matrix_type >::rowsBufferMap, pcl::InterfaceCommunicator< TLayout >::send_raw(), UG_DLOG, and ug::BinaryBuffer::write_pos().
Referenced by ug::GenerateOverlapClass< matrix_type >::communicate().
process() [1/2]
template<typename matrix_type > void ug::RowSendingScheme< matrix_type >::process (BinaryBuffer & buf, int pid, size_t localRowIndex) inline private
References ug::RowSendingScheme< matrix_type >::colMax, ug::RowSendingScheme< matrix_type >::connections, ug::ParallelNodes::create_slave_node(), ug::Deserialize(), ug::ParallelNodes::distance_to_master_or_inner(), ug::ParallelNodes::get_local_index_if_available(), ug::LIB_ALG_MATRIX, ug::RowSendingScheme< matrix_type >::m_bCreateNewNodes, num_connections(), ug::RowSendingScheme< matrix_type >::PN, ug::RowSendingScheme< matrix_type >::rowMax, and UG_DLOG.
process() [2/2]
template<typename matrix_type > void ug::RowSendingScheme< matrix_type >::process (const IndexLayout & receiveLayout) inline
References pcl::SingleLevelLayout< TInterface >::begin(), ug::RowSendingScheme< matrix_type >::colMax, ug::RowSendingScheme< matrix_type >::connections, pcl::SingleLevelLayout< TInterface >::end(), ug::LIB_ALG_MATRIX, ug::RowSendingScheme< matrix_type >::PN, pcl::SingleLevelLayout< TInterface >::proc_id(), ug::ParallelNodes::process(), ug::RowSendingScheme< matrix_type >::rowMax, ug::RowSendingScheme< matrix_type >::rowsBufferMap, and UG_DLOG.
Referenced by ug::GenerateOverlapClass< matrix_type >::communicate().
resize_mat()
template<typename matrix_type > void ug::RowSendingScheme< matrix_type >::resize_mat (matrix_type & mat) inline private
References ug::RowSendingScheme< matrix_type >::colMax, ug::RowSendingScheme< matrix_type >::mat, and ug::RowSendingScheme< matrix_type >::rowMax.
Referenced by ug::RowSendingScheme< matrix_type >::add_rows_to_matrix(), and ug::RowSendingScheme< matrix_type >::set_rows_in_matrix().
set_create_new_nodes()
template<typename matrix_type > void ug::RowSendingScheme< matrix_type >::set_create_new_nodes (bool bCreateNewNodes) inline
References ug::RowSendingScheme< matrix_type >::m_bCreateNewNodes.
Referenced by ug::GenerateOverlapClass< matrix_type >::communicate().
set_rows_in_matrix()
template<typename matrix_type > void ug::RowSendingScheme< matrix_type >::set_rows_in_matrix (matrix_type & mat) inline
References ug::RowSendingScheme< matrix_type >::connections, ug::RowSendingScheme< matrix_type >::mat, and ug::RowSendingScheme< matrix_type >::resize_mat().
Referenced by ug::GenerateOverlapClass< matrix_type >::communicate().
Member Data Documentation
colMax
template<typename matrix_type > size_t ug::RowSendingScheme< matrix_type >::colMax private
Referenced by ug::RowSendingScheme< matrix_type >::process(), and ug::RowSendingScheme< matrix_type >::resize_mat().
connections
template<typename matrix_type > std::map<size_t, std::vector<connection> > ug::RowSendingScheme< matrix_type >::connections private
Referenced by ug::RowSendingScheme< matrix_type >::add_rows_to_matrix(), ug::RowSendingScheme< matrix_type >::process(), and ug::RowSendingScheme< matrix_type >::set_rows_in_matrix().
m_bCreateNewNodes
template<typename matrix_type > bool ug::RowSendingScheme< matrix_type >::m_bCreateNewNodes private
Referenced by ug::RowSendingScheme< matrix_type >::issue_send(), ug::RowSendingScheme< matrix_type >::process(), and ug::RowSendingScheme< matrix_type >::set_create_new_nodes().
mat
template<typename matrix_type > const matrix_type& ug::RowSendingScheme< matrix_type >::mat private
Referenced by ug::RowSendingScheme< matrix_type >::add_rows_to_matrix(), ug::RowSendingScheme< matrix_type >::issue_send(), ug::RowSendingScheme< matrix_type >::resize_mat(), and ug::RowSendingScheme< matrix_type >::set_rows_in_matrix().
PN
template<typename matrix_type > ParallelNodes& ug::RowSendingScheme< matrix_type >::PN private
Referenced by ug::RowSendingScheme< matrix_type >::issue_send(), and ug::RowSendingScheme< matrix_type >::process().
rowMax
template<typename matrix_type > size_t ug::RowSendingScheme< matrix_type >::rowMax private
Referenced by ug::RowSendingScheme< matrix_type >::process(), and ug::RowSendingScheme< matrix_type >::resize_mat().
rowsBufferMap
template<typename matrix_type > BufferMap ug::RowSendingScheme< matrix_type >::rowsBufferMap private
Referenced by ug::RowSendingScheme< matrix_type >::issue_send(), and ug::RowSendingScheme< matrix_type >::process().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/parallelization/row_sending_scheme.h