ug4: ug::MultiElementAttachmentAccessor< TAttachment > Class Template Reference
ug::MultiElementAttachmentAccessor< TAttachment > Class Template Reference
lib_grid » algorithms » attachment util
Accesses attachements in different element types at the same time.
#include <attachment_util.h>
Public Types
typedef attachment_value_traits< ValueType >::const_reference ConstRefType
typedef attachment_value_traits< ValueType >::reference RefType
typedef TAttachment::ValueType ValueType
Public Member Functions
bool access (Grid &g, TAttachment &a, bool vrts=true, bool edges=true, bool faces=true, bool vols=true)
Grid::AttachmentAccessor< Edge, TAttachment > & edge_accessor ()
Grid::AttachmentAccessor< Face, TAttachment > & face_accessor ()
void invalidate ()
bool is_valid_edge_accessor () const
bool is_valid_face_accessor () const
bool is_valid_vertex_accessor () const
bool is_valid_volume_accessor () const
MultiElementAttachmentAccessor ()
MultiElementAttachmentAccessor (Grid &g, TAttachment &a, bool vrts=true, bool edges=true, bool faces=true, bool vols=true)
RefType operator[] (Edge *e)
ConstRefType operator[] (Edge *e) const
RefType operator[] (Face *e)
ConstRefType operator[] (Face *e) const
RefType operator[] (GridObject *e)
ConstRefType operator[] (GridObject *e) const
RefType operator[] (Vertex *e)
ConstRefType operator[] (Vertex *e) const
RefType operator[] (Volume *e)
ConstRefType operator[] (Volume *e) const
Grid::AttachmentAccessor< Vertex, TAttachment > & vertex_accessor ()
Grid::AttachmentAccessor< Volume, TAttachment > & volume_accessor ()
Private Attributes
Grid::AttachmentAccessor< Edge, TAttachment > m_aaEdge
Grid::AttachmentAccessor< Face, TAttachment > m_aaFace
Grid::AttachmentAccessor< Volume, TAttachment > m_aaVol
Grid::AttachmentAccessor< Vertex, TAttachment > m_aaVrt
Detailed Description
template<class TAttachment>
class ug::MultiElementAttachmentAccessor< TAttachment >
Accesses attachements in different element types at the same time.
If the same attachment is attached to vertices, edges, faces and volumes of a grid, then this accessor can be used to access them all at once.
Member Typedef Documentation
ConstRefType
template<class TAttachment > typedef attachment_value_traits<ValueType>::const_reference ug::MultiElementAttachmentAccessor< TAttachment >::ConstRefType
RefType
template<class TAttachment > typedef attachment_value_traits<ValueType>::reference ug::MultiElementAttachmentAccessor< TAttachment >::RefType
ValueType
template<class TAttachment > typedef TAttachment::ValueType ug::MultiElementAttachmentAccessor< TAttachment >::ValueType
Constructor & Destructor Documentation
MultiElementAttachmentAccessor() [1/2]
template<class TAttachment > ug::MultiElementAttachmentAccessor< TAttachment >::MultiElementAttachmentAccessor () inline
MultiElementAttachmentAccessor() [2/2]
template<class TAttachment > ug::MultiElementAttachmentAccessor< TAttachment >::MultiElementAttachmentAccessor (Grid & g, TAttachment & a, bool vrts = true, bool edges = true, bool faces = true, bool vols = true) inline
References ug::MultiElementAttachmentAccessor< TAttachment >::access().
Member Function Documentation
access()
template<class TAttachment > bool ug::MultiElementAttachmentAccessor< TAttachment >::access (Grid & g, TAttachment & a, bool vrts = true, bool edges = true, bool faces = true, bool vols = true) inline
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::invalidate(), ug::MultiElementAttachmentAccessor< TAttachment >::m_aaEdge, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaFace, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVol, and ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVrt.
Referenced by ug::MultiElementAttachmentAccessor< TAttachment >::MultiElementAttachmentAccessor().
edge_accessor()
template<class TAttachment > Grid::AttachmentAccessor<Edge, TAttachment>& ug::MultiElementAttachmentAccessor< TAttachment >::edge_accessor () inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaEdge.
face_accessor()
template<class TAttachment > Grid::AttachmentAccessor<Face, TAttachment>& ug::MultiElementAttachmentAccessor< TAttachment >::face_accessor () inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaFace.
invalidate()
template<class TAttachment > void ug::MultiElementAttachmentAccessor< TAttachment >::invalidate () inline
References ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::invalidate(), ug::MultiElementAttachmentAccessor< TAttachment >::m_aaEdge, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaFace, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVol, and ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVrt.
is_valid_edge_accessor()
template<class TAttachment > bool ug::MultiElementAttachmentAccessor< TAttachment >::is_valid_edge_accessor () const inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaEdge, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid().
is_valid_face_accessor()
template<class TAttachment > bool ug::MultiElementAttachmentAccessor< TAttachment >::is_valid_face_accessor () const inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaFace, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid().
is_valid_vertex_accessor()
template<class TAttachment > bool ug::MultiElementAttachmentAccessor< TAttachment >::is_valid_vertex_accessor () const inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVrt, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid().
is_valid_volume_accessor()
template<class TAttachment > bool ug::MultiElementAttachmentAccessor< TAttachment >::is_valid_volume_accessor () const inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVol, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid().
operator[]() [1/10]
template<class TAttachment > RefType ug::MultiElementAttachmentAccessor< TAttachment >::operator[] (Edge * e) inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaEdge.
operator[]() [2/10]
template<class TAttachment > ConstRefType ug::MultiElementAttachmentAccessor< TAttachment >::operator[] (Edge * e) const inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaEdge.
operator[]() [3/10]
template<class TAttachment > RefType ug::MultiElementAttachmentAccessor< TAttachment >::operator[] (Face * e) inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaFace.
operator[]() [4/10]
template<class TAttachment > ConstRefType ug::MultiElementAttachmentAccessor< TAttachment >::operator[] (Face * e) const inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaFace.
operator[]() [5/10]
template<class TAttachment > RefType ug::MultiElementAttachmentAccessor< TAttachment >::operator[] (GridObject * e) inline
References ug::GridObject::base_object_id(), ug::EDGE, ug::FACE, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaEdge, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaFace, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVol, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVrt, UG_THROW, ug::VERTEX, and ug::VOLUME.
operator[]() [6/10]
template<class TAttachment > ConstRefType ug::MultiElementAttachmentAccessor< TAttachment >::operator[] (GridObject * e) const inline
References ug::GridObject::base_object_id(), ug::EDGE, ug::FACE, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaEdge, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaFace, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVol, ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVrt, UG_THROW, ug::VERTEX, and ug::VOLUME.
operator[]() [7/10]
template<class TAttachment > RefType ug::MultiElementAttachmentAccessor< TAttachment >::operator[] (Vertex * e) inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVrt.
operator[]() [8/10]
template<class TAttachment > ConstRefType ug::MultiElementAttachmentAccessor< TAttachment >::operator[] (Vertex * e) const inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVrt.
operator[]() [9/10]
template<class TAttachment > RefType ug::MultiElementAttachmentAccessor< TAttachment >::operator[] (Volume * e) inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVol.
operator[]() [10/10]
template<class TAttachment > ConstRefType ug::MultiElementAttachmentAccessor< TAttachment >::operator[] (Volume * e) const inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVol.
vertex_accessor()
template<class TAttachment > Grid::AttachmentAccessor<Vertex, TAttachment>& ug::MultiElementAttachmentAccessor< TAttachment >::vertex_accessor () inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVrt.
volume_accessor()
template<class TAttachment > Grid::AttachmentAccessor<Volume, TAttachment>& ug::MultiElementAttachmentAccessor< TAttachment >::volume_accessor () inline
References ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVol.
Member Data Documentation
m_aaEdge
template<class TAttachment > Grid::AttachmentAccessor<Edge, TAttachment> ug::MultiElementAttachmentAccessor< TAttachment >::m_aaEdge private
Referenced by ug::MultiElementAttachmentAccessor< TAttachment >::access(), ug::MultiElementAttachmentAccessor< TAttachment >::edge_accessor(), ug::MultiElementAttachmentAccessor< TAttachment >::invalidate(), ug::MultiElementAttachmentAccessor< TAttachment >::is_valid_edge_accessor(), and ug::MultiElementAttachmentAccessor< TAttachment >::operator[]().
m_aaFace
template<class TAttachment > Grid::AttachmentAccessor<Face, TAttachment> ug::MultiElementAttachmentAccessor< TAttachment >::m_aaFace private
Referenced by ug::MultiElementAttachmentAccessor< TAttachment >::access(), ug::MultiElementAttachmentAccessor< TAttachment >::face_accessor(), ug::MultiElementAttachmentAccessor< TAttachment >::invalidate(), ug::MultiElementAttachmentAccessor< TAttachment >::is_valid_face_accessor(), and ug::MultiElementAttachmentAccessor< TAttachment >::operator[]().
m_aaVol
template<class TAttachment > Grid::AttachmentAccessor<Volume, TAttachment> ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVol private
Referenced by ug::MultiElementAttachmentAccessor< TAttachment >::access(), ug::MultiElementAttachmentAccessor< TAttachment >::invalidate(), ug::MultiElementAttachmentAccessor< TAttachment >::is_valid_volume_accessor(), ug::MultiElementAttachmentAccessor< TAttachment >::operator[](), and ug::MultiElementAttachmentAccessor< TAttachment >::volume_accessor().
m_aaVrt
template<class TAttachment > Grid::AttachmentAccessor<Vertex, TAttachment> ug::MultiElementAttachmentAccessor< TAttachment >::m_aaVrt private
Referenced by ug::MultiElementAttachmentAccessor< TAttachment >::access(), ug::MultiElementAttachmentAccessor< TAttachment >::invalidate(), ug::MultiElementAttachmentAccessor< TAttachment >::is_valid_vertex_accessor(), ug::MultiElementAttachmentAccessor< TAttachment >::operator[](), and ug::MultiElementAttachmentAccessor< TAttachment >::vertex_accessor().
The documentation for this class was generated from the following file:
ugbase/lib_grid/algorithms/attachment_util.h