ug4: ug::GaussQuadratureHexahedron Class Reference
ug::GaussQuadratureHexahedron Class Reference
#include <gauss_tensor_prod.h>
Public Member Functions
GaussQuadratureHexahedron (size_t order)
constructor
~GaussQuadratureHexahedron ()
destructor
Public Member Functions inherited from ug::QuadratureRule< 3 >
size_t order () const
returns the order
const MathVector< dim > & point (size_t i) const
returns i'th integration point
const MathVector< dim > * points () const
returns all positions in an array of size()
QuadratureRule ()
constructor
size_t size () const
number of integration points
number weight (size_t i) const
return the i'th weight
const number * weights () const
returns all weights in an array of size()
virtual ~QuadratureRule ()
destructor
Additional Inherited Members
Public Types inherited from ug::QuadratureRule< 3 >
typedef MathVector< dim > position_type
Position Type in Reference Element Space.
typedef number weight_type
Type of weights.
Static Public Attributes inherited from ug::QuadratureRule< 3 >
static const int dim
Dimension of Reference Element.
Protected Attributes inherited from ug::QuadratureRule< 3 >
size_t m_numPoints
number of points
int m_order
Order of rule.
const MathVector< dim > * m_pvPoint
Integration points.
const number * m_pvWeight
Weights.
Detailed Description
The following class provides QuadratureRules for hexahedrons by using Gauss Jacobi Quadrature and Gauss Legendre Quadrature
Constructor & Destructor Documentation
GaussQuadratureHexahedron()
ug::GaussQuadratureHexahedron::GaussQuadratureHexahedron (size_t order)
constructor
References ug::QuadratureRule< 3 >::m_numPoints, ug::QuadratureRule< 3 >::m_order, ug::QuadratureRule< 3 >::m_pvPoint, ug::QuadratureRule< 3 >::m_pvWeight, ug::QuadratureRule< TDim >::order(), ug::QuadratureRule< 3 >::order(), ug::QuadratureRule< TDim >::point(), ug::QuadratureRule< TDim >::size(), and ug::QuadratureRule< TDim >::weight().
~GaussQuadratureHexahedron()
ug::GaussQuadratureHexahedron::~GaussQuadratureHexahedron ()
destructor
References ug::QuadratureRule< 3 >::m_pvPoint, and ug::QuadratureRule< 3 >::m_pvWeight.
The documentation for this class was generated from the following files:
ugbase/lib_disc/quadrature/gauss_tensor_prod/gauss_tensor_prod.h
ugbase/lib_disc/quadrature/gauss_tensor_prod/gauss_tensor_prod.cpp