ug4: ug::IAssemble< TAlgebra > Class Template Reference
ug::IAssemble< TAlgebra > Class Template Reference abstract
lib_discretization » Assembling
Interface providing Jacobian and Defect of a discretization.
#include <assemble_interface.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef TAlgebra::matrix_type matrix_type
Type of algebra matrix.
typedef TAlgebra::vector_type vector_type
Type of algebra vector.
Public Member Functions
void adjust_solution (vector_type &u)
virtual void adjust_solution (vector_type &u, const GridLevel &gl)=0
sets dirichlet values in solution vector
void assemble_defect (vector_type &d, const vector_type &u)
virtual void assemble_defect (vector_type &d, const vector_type &u, const GridLevel &gl)=0
assembles Defect
void assemble_jacobian (matrix_type &J, const vector_type &u)
virtual void assemble_jacobian (matrix_type &J, const vector_type &u, const GridLevel &gl)=0
assembles Jacobian (or Approximation of Jacobian)
void assemble_linear (matrix_type &A, vector_type &b)
virtual void assemble_linear (matrix_type &A, vector_type &b, const GridLevel &gl)=0
Assembles Matrix and Right-Hand-Side for a linear problem.
void assemble_mass_matrix (matrix_type &M, const vector_type &u)
virtual void assemble_mass_matrix (matrix_type &M, const vector_type &u, const GridLevel &gl)
assembles mass matrix
void assemble_rhs (vector_type &b)
virtual void assemble_rhs (vector_type &b, const GridLevel &gl)=0
Assembles Right-Hand-Side for a linear problem.
virtual void assemble_rhs (vector_type &rhs, const vector_type &u)
virtual void assemble_rhs (vector_type &rhs, const vector_type &u, const GridLevel &gl)=0
assembles rhs
void assemble_stiffness_matrix (matrix_type &A, const vector_type &u)
virtual void assemble_stiffness_matrix (matrix_type &A, const vector_type &u, const GridLevel &gl)
assembles stiffness matrix
virtual SmartPtr< IConstraint< TAlgebra > > constraint (size_t i)=0
returns the i'th constraint
virtual size_t num_constraints () const =0
returns the number of constraints
virtual ~IAssemble ()
Virtual Destructor.
virtual SmartPtr< AssemblingTuner< TAlgebra > > ass_tuner ()=0
virtual ConstSmartPtr< AssemblingTuner< TAlgebra > > ass_tuner () const =0
Detailed Description
template<typename TAlgebra>
class ug::IAssemble< TAlgebra >
Interface providing Jacobian and Defect of a discretization.
Interface to generate Jacobi-Matrices and Defect-Vectors for a nonlinear problem and to compute Matrix and Right-Hand Side for a linear problem.
The Interface can be used directly to compute Jacobian and Defect (resp. Mass-Stiffness-matrix_type and right-hand side) in case of nonlinear (resp. linear) problem. Furthermore, the interface is used in the NewtonSolver and MultiGridSolver. The NewtonSolver uses the functions assemble_defect+assemble_jacobian or assemble_jacobian_defect. The MultiGridSolver uses the function assemble_jacobian in order to assemble coarse grid Matrices.
To give an idea of the usage, an implementation should obey this rules:
Time dependent nonlinear problem \(\partial_t u + A(u) = f \). Using a l-step time stepping, the defect will be
\[ d(u^k) = \sum_{i=0}^{l-1} s_{m,i} M(u^{k-i}) + s_{a,i} \{A(u^{k-i}) - f\} \]
and assemble_linear will return false.
Time dependent linear problem \(\partial_t u + A*u = f \). Using a l-step time stepping, the defect will be
\[ d(u^k) = \sum_{i=0}^{l-1} s_{m,i} M*u^{k-i} + s_{a,i} \{A*u^{k-i} - f \} J(u^k) = s_{m,0}*M + s_{a,0} A \]
and assemble_linear will compute \(A = s_{m,0}*M + s_{a,0} A \) and \(b = - \{ \sum_{i=1}^{l-1} s_{m,i} M*u^{k-i} + s_{a,i} \{A*u^{k-i} - f\} \} + s_{a,0} * f \)
Stationary Non-linear Problem \(A(u) = f \). Then, the defect will be
\[ d(u) = A(u) - f \]
and assemble_linear will return false.
Stationary linear Problem \(A*u = f \). Then, the defect will be
\[ d(u) = A*u - f J(u) = A \]
and assemble_linear will compute \(A = A \) and \(b = f \).
Template Parameters
TAlgebra Algebra type
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::IAssemble< TAlgebra >::algebra_type
Algebra type.
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::IAssemble< TAlgebra >::matrix_type
Type of algebra matrix.
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::IAssemble< TAlgebra >::vector_type
Type of algebra vector.
Constructor & Destructor Documentation
~IAssemble()
template<typename TAlgebra > virtual ug::IAssemble< TAlgebra >::~IAssemble () inline virtual
Virtual Destructor.
Member Function Documentation
adjust_solution() [1/2]
template<typename TAlgebra > void ug::IAssemble< TAlgebra >::adjust_solution (vector_type & u) inline
References ug::IAssemble< TAlgebra >::adjust_solution().
adjust_solution() [2/2]
template<typename TAlgebra > virtual void ug::IAssemble< TAlgebra >::adjust_solution (vector_type & u, const GridLevel & gl) pure virtual
sets dirichlet values in solution vector
Sets dirichlet values of the NumericalSolution u when components are dirichlet
Parameters
[out] u Numerical Solution
[in] gl Grid Level
Implemented in ug::IDomainDiscretization< TAlgebra >, ug::SDIRK< TAlgebra >, ug::MultiStepTimeDiscretization< TAlgebra >, ug::CompositeTimeDiscretization< TAlgebra >, ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IAssemble< TAlgebra >::adjust_solution().
ass_tuner() [1/2]
template<typename TAlgebra > virtual ConstSmartPtr<AssemblingTuner<TAlgebra> > ug::IAssemble< TAlgebra >::ass_tuner () const pure virtual
Implemented in ug::ITimeDiscretization< TAlgebra >, ug::CompositeTimeDiscretization< TAlgebra >, ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
ass_tuner() [2/2]
template<typename TAlgebra > virtual SmartPtr<AssemblingTuner<TAlgebra> > ug::IAssemble< TAlgebra >::ass_tuner () pure virtual
Implemented in ug::ITimeDiscretization< TAlgebra >, ug::CompositeTimeDiscretization< TAlgebra >, ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
assemble_defect() [1/2]
template<typename TAlgebra > void ug::IAssemble< TAlgebra >::assemble_defect (vector_type & d, const vector_type & u) inline
References ug::IAssemble< TAlgebra >::assemble_defect().
assemble_defect() [2/2]
template<typename TAlgebra > virtual void ug::IAssemble< TAlgebra >::assemble_defect (vector_type & d, const vector_type & u, const GridLevel & gl) pure virtual
assembles Defect
Assembles Defect at a given Solution u.
Parameters
[out] d Defect d(u) to be filled
[in] u Current iterate
[in] gl Grid Level
Implemented in ug::IDomainDiscretization< TAlgebra >, ug::SDIRK< TAlgebra >, ug::MultiStepTimeDiscretization< TAlgebra >, ug::CompositeTimeDiscretization< TAlgebra >, ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IAssemble< TAlgebra >::assemble_defect().
assemble_jacobian() [1/2]
template<typename TAlgebra > void ug::IAssemble< TAlgebra >::assemble_jacobian (matrix_type & J, const vector_type & u) inline
References ug::IAssemble< TAlgebra >::assemble_jacobian().
assemble_jacobian() [2/2]
template<typename TAlgebra > virtual void ug::IAssemble< TAlgebra >::assemble_jacobian (matrix_type & J, const vector_type & u, const GridLevel & gl) pure virtual
assembles Jacobian (or Approximation of Jacobian)
Assembles Jacobian at a given iterate u.
Parameters
[out] J Jacobian J(u) matrix to be filled
[in] u Current iterate
[in] gl Grid Level
Implemented in ug::IDomainDiscretization< TAlgebra >, ug::SDIRK< TAlgebra >, ug::MultiStepTimeDiscretization< TAlgebra >, ug::CompositeTimeDiscretization< TAlgebra >, ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IAssemble< TAlgebra >::assemble_jacobian().
assemble_linear() [1/2]
template<typename TAlgebra > void ug::IAssemble< TAlgebra >::assemble_linear (matrix_type & A, vector_type & b) inline
References ug::IAssemble< TAlgebra >::assemble_linear().
assemble_linear() [2/2]
template<typename TAlgebra > virtual void ug::IAssemble< TAlgebra >::assemble_linear (matrix_type & A, vector_type & b, const GridLevel & gl) pure virtual
Assembles Matrix and Right-Hand-Side for a linear problem.
Assembles matrix_type and Right-Hand-Side for a linear problem
Parameters
[out] A Mass-/Stiffness- Matrix
[out] b Right-Hand-Side
[in] gl Grid Level
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >, ug::IDomainDiscretization< TAlgebra >, ug::SDIRK< TAlgebra >, ug::MultiStepTimeDiscretization< TAlgebra >, and ug::CompositeTimeDiscretization< TAlgebra >.
Referenced by ug::IAssemble< TAlgebra >::assemble_linear().
assemble_mass_matrix() [1/2]
template<typename TAlgebra > void ug::IAssemble< TAlgebra >::assemble_mass_matrix (matrix_type & M, const vector_type & u) inline
References ug::IAssemble< TAlgebra >::assemble_mass_matrix().
assemble_mass_matrix() [2/2]
template<typename TAlgebra > virtual void ug::IAssemble< TAlgebra >::assemble_mass_matrix (matrix_type & M, const vector_type & u, const GridLevel & gl) inline virtual
assembles mass matrix
Reimplemented in ug::IDomainDiscretization< TAlgebra >, ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
References UG_THROW.
Referenced by ug::IAssemble< TAlgebra >::assemble_mass_matrix().
assemble_rhs() [1/4]
template<typename TAlgebra > void ug::IAssemble< TAlgebra >::assemble_rhs (vector_type & b) inline
References ug::IAssemble< TAlgebra >::assemble_rhs().
assemble_rhs() [2/4]
template<typename TAlgebra > virtual void ug::IAssemble< TAlgebra >::assemble_rhs (vector_type & b, const GridLevel & gl) pure virtual
Assembles Right-Hand-Side for a linear problem.
Assembles Right-Hand-Side for a linear problem
Parameters
[out] b Right-Hand-Side
[in] gl Grid Level
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >, ug::IDomainDiscretization< TAlgebra >, ug::SDIRK< TAlgebra >, ug::MultiStepTimeDiscretization< TAlgebra >, and ug::CompositeTimeDiscretization< TAlgebra >.
assemble_rhs() [3/4]
template<typename TAlgebra > virtual void ug::IAssemble< TAlgebra >::assemble_rhs (vector_type & rhs, const vector_type & u) inline virtual
References ug::IAssemble< TAlgebra >::assemble_rhs().
assemble_rhs() [4/4]
template<typename TAlgebra > virtual void ug::IAssemble< TAlgebra >::assemble_rhs (vector_type & rhs, const vector_type & u, const GridLevel & gl) pure virtual
assembles rhs
Implemented in ug::IDomainDiscretization< TAlgebra >, ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >, ug::SDIRK< TAlgebra >, ug::MultiStepTimeDiscretization< TAlgebra >, and ug::CompositeTimeDiscretization< TAlgebra >.
Referenced by ug::IAssemble< TAlgebra >::assemble_rhs().
assemble_stiffness_matrix() [1/2]
template<typename TAlgebra > void ug::IAssemble< TAlgebra >::assemble_stiffness_matrix (matrix_type & A, const vector_type & u) inline
References ug::IAssemble< TAlgebra >::assemble_stiffness_matrix().
assemble_stiffness_matrix() [2/2]
template<typename TAlgebra > virtual void ug::IAssemble< TAlgebra >::assemble_stiffness_matrix (matrix_type & A, const vector_type & u, const GridLevel & gl) inline virtual
assembles stiffness matrix
Reimplemented in ug::IDomainDiscretization< TAlgebra >, ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
References UG_THROW.
Referenced by ug::IAssemble< TAlgebra >::assemble_stiffness_matrix().
constraint()
template<typename TAlgebra > virtual SmartPtr<IConstraint<TAlgebra> > ug::IAssemble< TAlgebra >::constraint (size_t i) pure virtual
returns the i'th constraint
Implemented in ug::IDomainDiscretization< TAlgebra >, ug::ITimeDiscretization< TAlgebra >, ug::CompositeTimeDiscretization< TAlgebra >, ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
num_constraints()
template<typename TAlgebra > virtual size_t ug::IAssemble< TAlgebra >::num_constraints () const pure virtual
returns the number of constraints
Implemented in ug::IDomainDiscretization< TAlgebra >, ug::ITimeDiscretization< TAlgebra >, ug::CompositeTimeDiscretization< TAlgebra >, ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, TAlgebra, LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
The documentation for this class was generated from the following file:
ugbase/lib_disc/assemble_interface.h