ug4: ug::ComPol_MatCopyDiag< TMatrix > Class Template Reference
ug::ComPol_MatCopyDiag< TMatrix > Class Template Reference
#include <matrix_overlap_impl.h>
Public Member Functions
bool collect (ug::BinaryBuffer &buff, const Interface &interface)
should write data which is associated with the interface elements to the buffer.
ComPol_MatCopyDiag (TMatrix &mat)
bool extract (ug::BinaryBuffer &buff, const Interface &interface)
extract data from the buffer and assigns it to the interface-elements.
int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
Public Member Functions inherited from pcl::ICommunicationPolicy< IndexLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual ~ICommunicationPolicy ()
Private Attributes
TMatrix & m_mat
Additional Inherited Members
Public Types inherited from pcl::ICommunicationPolicy< IndexLayout >
typedef Layout::Interface Interface
typedef IndexLayout Layout
Constructor & Destructor Documentation
ComPol_MatCopyDiag()
template<class TMatrix > ug::ComPol_MatCopyDiag< TMatrix >::ComPol_MatCopyDiag (TMatrix & mat) inline
Member Function Documentation
collect()
template<class TMatrix > bool ug::ComPol_MatCopyDiag< TMatrix >::collect (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
should write data which is associated with the interface elements to the buffer.
Implements pcl::ICommunicationPolicy< IndexLayout >.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::begin(), pcl::OrderedInterface< TType, TContainer, TAlloc >::end(), pcl::OrderedInterface< TType, TContainer, TAlloc >::get_element(), ug::ComPol_MatCopyDiag< TMatrix >::m_mat, PROFILE_BEGIN_GROUP, and ug::Serialize().
extract()
template<class TMatrix > bool ug::ComPol_MatCopyDiag< TMatrix >::extract (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
extract data from the buffer and assigns it to the interface-elements.
If this method is called between calls to begin_layout_extraction and end_layout_extraction, the interface that is passed to this method belongs to the layout.
Implements pcl::ICommunicationPolicy< IndexLayout >.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::begin(), ug::Deserialize(), pcl::OrderedInterface< TType, TContainer, TAlloc >::end(), pcl::OrderedInterface< TType, TContainer, TAlloc >::get_element(), ug::ComPol_MatCopyDiag< TMatrix >::m_mat, and PROFILE_BEGIN_GROUP.
get_required_buffer_size()
template<class TMatrix > int ug::ComPol_MatCopyDiag< TMatrix >::get_required_buffer_size (const Interface & interface) inline virtual
returns the size of the buffer in bytes, that will be required for interface-communication.
Determines the size of the buffer on which the extract and receive methods for the given interface will operate. If the buffer-size can't be calculated on both sides (sender and receiver) this method should return -1. This will lead to an additional communication step in which buffer-sizes will be exchanged. If the buffer-size can be calculated on both sides, it makes sense to do so, since this leads to less communication and overall improved performance. The buffer-size has to exactly match the size of required memory. Make sure that you completely fill the buffer during collect(...) and that you read all data during extract(...). The default implementation returns -1.
Reimplemented from pcl::ICommunicationPolicy< IndexLayout >.
References pcl::OrderedInterface< TType, TContainer, TAlloc >::size().
Member Data Documentation
m_mat
template<class TMatrix > TMatrix& ug::ComPol_MatCopyDiag< TMatrix >::m_mat private
Referenced by ug::ComPol_MatCopyDiag< TMatrix >::collect(), and ug::ComPol_MatCopyDiag< TMatrix >::extract().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/parallelization/matrix_overlap_impl.h