ug4: ug::IBlockJacobiPreconditioner< TAlgebra > Class Template Reference
ug::IBlockJacobiPreconditioner< TAlgebra > Class Template Reference abstract
#include <block_gauss_seidel.h>
Public Types
typedef TAlgebra algebra_type
typedef IPreconditioner< TAlgebra >::matrix_operator_type matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
IBlockJacobiPreconditioner ()
IBlockJacobiPreconditioner (const IBlockJacobiPreconditioner &parent)
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
virtual SmartPtr< ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > > clone ()=0
clone
virtual std::string config_string () const
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
returns true if the debug writer is set
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
virtual bool block_preprocess (matrix_type &A)=0
virtual bool block_step (matrix_type &A, vector_type &c, const vector_type &d)=0
virtual bool postprocess ()
cleans the operator
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
initializes the preconditioner
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
computes a new correction c = B*d
virtual bool supports_parallel () const
returns if parallel solving is supported
Protected Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual const char * name () const =0
returns the name of iterator
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
void enter_debug_writer_section (const char *secDir)
enters a debugging section
void enter_debug_writer_section (std::string secDir)
enters a debugging section
void leave_debug_writer_section ()
leaves a debugging section
void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
void write_debug (const matrix_type &mat, std::string name)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
matrix_type A
SmartPtr< vector_type > m_spDtmp
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::IBlockJacobiPreconditioner< TAlgebra >::algebra_type
matrix_operator_type
template<typename TAlgebra > typedef IPreconditioner<TAlgebra>::matrix_operator_type ug::IBlockJacobiPreconditioner< TAlgebra >::matrix_operator_type
Matrix Operator type.
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::IBlockJacobiPreconditioner< TAlgebra >::matrix_type
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::IBlockJacobiPreconditioner< TAlgebra >::vector_type
Constructor & Destructor Documentation
IBlockJacobiPreconditioner() [1/2]
template<typename TAlgebra > ug::IBlockJacobiPreconditioner< TAlgebra >::IBlockJacobiPreconditioner () inline
IBlockJacobiPreconditioner() [2/2]
template<typename TAlgebra > ug::IBlockJacobiPreconditioner< TAlgebra >::IBlockJacobiPreconditioner (const IBlockJacobiPreconditioner< TAlgebra > & parent) inline
Member Function Documentation
block_preprocess()
template<typename TAlgebra > virtual bool ug::IBlockJacobiPreconditioner< TAlgebra >::block_preprocess (matrix_type & A) protected pure virtual
Implemented in ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >, ug::SparseBlockGaussSeidel< TAlgebra, backward, forward >, ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >, and ug::BlockGaussSeidel< TAlgebra, backward, forward >.
Referenced by ug::IBlockJacobiPreconditioner< TAlgebra >::preprocess().
block_step()
template<typename TAlgebra > virtual bool ug::IBlockJacobiPreconditioner< TAlgebra >::block_step (matrix_type & A, vector_type & c, const vector_type & d) protected pure virtual
Implemented in ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >, ug::SparseBlockGaussSeidel< TAlgebra, backward, forward >, ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >, and ug::BlockGaussSeidel< TAlgebra, backward, forward >.
Referenced by ug::IBlockJacobiPreconditioner< TAlgebra >::step().
postprocess()
template<typename TAlgebra > virtual bool ug::IBlockJacobiPreconditioner< TAlgebra >::postprocess () inline protected virtual
cleans the operator
Implements ug::IPreconditioner< TAlgebra >.
Reimplemented in ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >, ug::SparseBlockGaussSeidel< TAlgebra, backward, forward >, ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >, and ug::BlockGaussSeidel< TAlgebra, backward, forward >.
preprocess()
template<typename TAlgebra > virtual bool ug::IBlockJacobiPreconditioner< TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) inline protected virtual
initializes the preconditioner
This method is used to initialize the preconditioner. Usually, here are performed computationally expensive operations, that should only be computed once for an underlying matrix (e.g. LU factorization), while the preconditioner will by applied (using 'step'-method) several times.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::IBlockJacobiPreconditioner< TAlgebra >::A, ug::IBlockJacobiPreconditioner< TAlgebra >::block_preprocess(), pcl::CollectUniqueElements(), ug::MatAddSlaveRowsToMasterRowOverlap0(), and ug::SetDirichletRow().
step()
template<typename TAlgebra > virtual bool ug::IBlockJacobiPreconditioner< TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) inline protected virtual
computes a new correction c = B*d
This method computes a new correction c = B*d. It can only be called, when the preprocess has been done.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
[out] c correction
[in] d defect
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::IBlockJacobiPreconditioner< TAlgebra >::A, ug::IBlockJacobiPreconditioner< TAlgebra >::block_step(), ug::IBlockJacobiPreconditioner< TAlgebra >::m_spDtmp, ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::PST_UNIQUE, and SmartPtr< T, FreePolicy >::valid().
supports_parallel()
template<typename TAlgebra > virtual bool ug::IBlockJacobiPreconditioner< TAlgebra >::supports_parallel () const inline protected virtual
returns if parallel solving is supported
Implements ug::ILinearIterator< TAlgebra::vector_type >.
Reimplemented in ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >, ug::SparseBlockGaussSeidel< TAlgebra, backward, forward >, ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >, and ug::BlockGaussSeidel< TAlgebra, backward, forward >.
Member Data Documentation
A
template<typename TAlgebra > matrix_type ug::IBlockJacobiPreconditioner< TAlgebra >::A protected
Referenced by ug::BlockGaussSeidel< TAlgebra, backward, forward >::block_preprocess(), ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >::block_preprocess(), ug::SparseBlockGaussSeidel< TAlgebra, backward, forward >::block_preprocess(), ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::block_preprocess(), ug::BlockGaussSeidel< TAlgebra, backward, forward >::block_step(), ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >::block_step(), ug::SparseBlockGaussSeidel< TAlgebra, backward, forward >::block_step(), ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::block_step(), ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >::correct(), ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >::correct_backward(), ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >::correct_forward(), ug::IBlockJacobiPreconditioner< TAlgebra >::preprocess(), and ug::IBlockJacobiPreconditioner< TAlgebra >::step().
m_spDtmp
template<typename TAlgebra > SmartPtr<vector_type> ug::IBlockJacobiPreconditioner< TAlgebra >::m_spDtmp protected
Referenced by ug::IBlockJacobiPreconditioner< TAlgebra >::step().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/preconditioner/block_gauss_seidel.h