ug4: ug::GPUSparseMatrix< TValueType >::const_row_iterator Class Reference
ug::GPUSparseMatrix< TValueType >::const_row_iterator Class Reference
#include <gpusparsematrix.h>
Public Member Functions
void check () const
const_row_iterator (const GPUSparseMatrix &_A, size_t _row, size_t _i)
size_t index () const
bool operator!= (const const_row_iterator &o) const
void operator++ ()
void operator+= (int nr)
const_row_iterator * operator-> ()
bool operator== (const const_row_iterator &other) const
const value_type & value () const
~const_row_iterator ()
Private Attributes
const GPUSparseMatrix & A
size_t i
size_t row
Constructor & Destructor Documentation
const_row_iterator()
template<typename TValueType > ug::GPUSparseMatrix< TValueType >::const_row_iterator::const_row_iterator (const GPUSparseMatrix & _A, size_t _row, size_t _i) inline
References ug::GPUSparseMatrix< TValueType >::const_row_iterator::A, and ug::GPUSparseMatrix< TValueType >::add_iterator().
~const_row_iterator()
template<typename TValueType > ug::GPUSparseMatrix< TValueType >::const_row_iterator::~const_row_iterator () inline
References ug::GPUSparseMatrix< TValueType >::const_row_iterator::A, and ug::GPUSparseMatrix< TValueType >::remove_iterator().
Member Function Documentation
check()
template<typename TValueType > void ug::GPUSparseMatrix< TValueType >::const_row_iterator::check () const inline
References ug::GPUSparseMatrix< TValueType >::const_row_iterator::A, ug::GPUSparseMatrix< TValueType >::check_row(), ug::GPUSparseMatrix< TValueType >::const_row_iterator::i, and ug::GPUSparseMatrix< TValueType >::const_row_iterator::row.
Referenced by ug::GPUSparseMatrix< TValueType >::const_row_iterator::index(), and ug::GPUSparseMatrix< TValueType >::const_row_iterator::value().
index()
template<typename TValueType > size_t ug::GPUSparseMatrix< TValueType >::const_row_iterator::index () const inline
References ug::GPUSparseMatrix< TValueType >::const_row_iterator::A, ug::GPUSparseMatrix< TValueType >::const_row_iterator::check(), ug::GPUSparseMatrix< TValueType >::cols, and ug::GPUSparseMatrix< TValueType >::const_row_iterator::i.
operator!=()
template<typename TValueType > bool ug::GPUSparseMatrix< TValueType >::const_row_iterator::operator!= (const const_row_iterator & o) const inline
References ug::GPUSparseMatrix< TValueType >::const_row_iterator::i.
operator++()
template<typename TValueType > void ug::GPUSparseMatrix< TValueType >::const_row_iterator::operator++ () inline
References ug::GPUSparseMatrix< TValueType >::const_row_iterator::i.
operator+=()
template<typename TValueType > void ug::GPUSparseMatrix< TValueType >::const_row_iterator::operator+= (int nr) inline
References ug::GPUSparseMatrix< TValueType >::const_row_iterator::i.
operator->()
template<typename TValueType > const_row_iterator* ug::GPUSparseMatrix< TValueType >::const_row_iterator::operator-> () inline
operator==()
template<typename TValueType > bool ug::GPUSparseMatrix< TValueType >::const_row_iterator::operator== (const const_row_iterator & other) const inline
References ug::GPUSparseMatrix< TValueType >::const_row_iterator::i.
value()
template<typename TValueType > const value_type& ug::GPUSparseMatrix< TValueType >::const_row_iterator::value () const inline
References ug::GPUSparseMatrix< TValueType >::const_row_iterator::A, ug::GPUSparseMatrix< TValueType >::const_row_iterator::check(), ug::GPUSparseMatrix< TValueType >::const_row_iterator::i, and ug::GPUSparseMatrix< TValueType >::values.
Member Data Documentation
A
template<typename TValueType > const GPUSparseMatrix& ug::GPUSparseMatrix< TValueType >::const_row_iterator::A private
Referenced by ug::GPUSparseMatrix< TValueType >::const_row_iterator::check(), ug::GPUSparseMatrix< TValueType >::const_row_iterator::const_row_iterator(), ug::GPUSparseMatrix< TValueType >::const_row_iterator::index(), ug::GPUSparseMatrix< TValueType >::const_row_iterator::value(), and ug::GPUSparseMatrix< TValueType >::const_row_iterator::~const_row_iterator().
i
template<typename TValueType > size_t ug::GPUSparseMatrix< TValueType >::const_row_iterator::i private
Referenced by ug::GPUSparseMatrix< TValueType >::const_row_iterator::check(), ug::GPUSparseMatrix< TValueType >::const_row_iterator::index(), ug::GPUSparseMatrix< TValueType >::const_row_iterator::operator!=(), ug::GPUSparseMatrix< TValueType >::const_row_iterator::operator++(), ug::GPUSparseMatrix< TValueType >::const_row_iterator::operator+=(), ug::GPUSparseMatrix< TValueType >::const_row_iterator::operator==(), and ug::GPUSparseMatrix< TValueType >::const_row_iterator::value().
row
template<typename TValueType > size_t ug::GPUSparseMatrix< TValueType >::const_row_iterator::row private
Referenced by ug::GPUSparseMatrix< TValueType >::const_row_iterator::check().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/gpu_algebra/gpusparsematrix.h