ug4: ug::RegularEdge Class Reference
ug::RegularEdge Class Reference
lib_grid » geometric objects
Edges connect two vertices.
#include <grid_objects_1d.h>
Public Member Functions
virtual int container_section () const
virtual GridObject * create_empty_instance () const
create an instance of the derived type
virtual ReferenceObjectID reference_object_id () const
virtual bool refine (std::vector< Edge * > &vNewEdgesOut, Vertex *newVertex, Vertex **pSubstituteVrts=NULL)
virtual refine. Returns pointers to Edge.
bool refine (std::vector< RegularEdge * > &vNewEdgesOut, Vertex *newVertex, Vertex **pSubstituteVrts=NULL)
non virtual refine. Returns pointers to RegularEdge.
RegularEdge ()
RegularEdge (const EdgeDescriptor &descriptor)
RegularEdge (Vertex *v1, Vertex *v2)
virtual ~RegularEdge ()
Public Member Functions inherited from ug::Edge
virtual int base_object_id () const
bool get_opposing_side (Vertex *v, Vertex **vrtOut)
retrieves the vertex on the opposing side to the specified one.
bool get_opposing_side (Vertex *v, VertexDescriptor &vrtOut)
uint num_sides () const
virtual ~Edge ()
Public Member Functions inherited from ug::GridObject
uint grid_data_index () const
Returns the grid attachment data index of a geometric object.
virtual bool is_constrained () const
returns true if the object is constrained by other objects.
virtual bool is_constraining () const
returns the id of the reference-object.
virtual ~GridObject ()
virtual void remove_constraint_link (const Vertex *vrt)
removes a constraint link to the grid object.
virtual void remove_constraint_link (const Edge *e)
removes a constraint link to the grid object.
virtual void remove_constraint_link (const Face *f)
removes a constraint link to the grid object.
Public Member Functions inherited from ug::EdgeVertices
virtual size_t num_vertices () const
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual Vertex * vertex (size_t index) const
virtual ConstVertexArray vertices () const
virtual ~EdgeVertices ()
Public Member Functions inherited from ug::IVertexGroup
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~IVertexGroup ()
Static Public Member Functions
static bool type_match (GridObject *pObj)
Static Public Member Functions inherited from ug::Edge
static bool type_match (GridObject *pObj)
Friends
class Grid
Additional Inherited Members
Public Types inherited from ug::Edge
typedef Edge grid_base_object
typedef Face higher_dim_base_object
typedef Vertex lower_dim_base_object
typedef Vertex side
typedef Face sideof
Public Types inherited from ug::IVertexGroup
typedef Vertex *const * ConstVertexArray
Static Public Attributes inherited from ug::Edge
static const int BASE_OBJECT_ID = EDGE
static const bool CAN_BE_SIDE = true
static const int dim = 1
reference dimension
static const bool HAS_SIDES = true
static const size_t NUM_VERTICES = 2
Protected Member Functions inherited from ug::Edge
void set_vertex (uint index, Vertex *pVrt)
Protected Member Functions inherited from ug::GridObject
void set_grid_data_index (uint index)
ATTENTION: Use this method with extreme care!
Protected Member Functions inherited from ug::EdgeVertices
void assign_edge_vertices (const EdgeVertices &ev)
Protected Attributes inherited from ug::GridObject
uint m_gridDataIndex
Protected Attributes inherited from ug::EdgeVertices
Vertex * m_vertices [2]
Detailed Description
Edges connect two vertices.
The most commonly used edge-type.
Constructor & Destructor Documentation
RegularEdge() [1/3]
ug::RegularEdge::RegularEdge () inline
Referenced by refine().
RegularEdge() [2/3]
ug::RegularEdge::RegularEdge (Vertex * v1, Vertex * v2) inline
RegularEdge() [3/3]
ug::RegularEdge::RegularEdge (const EdgeDescriptor & descriptor) inline
References ug::EdgeVertices::vertex().
~RegularEdge()
virtual ug::RegularEdge::~RegularEdge () inline virtual
Member Function Documentation
container_section()
virtual int ug::RegularEdge::container_section () const inline virtual
Reimplemented from ug::Edge.
References ug::CSEDGE_REGULAR_EDGE.
create_empty_instance()
virtual GridObject* ug::RegularEdge::create_empty_instance () const inline virtual
create an instance of the derived type
Make sure to overload this method in derivates of this class!
Reimplemented from ug::GridObject.
reference_object_id()
virtual ReferenceObjectID ug::RegularEdge::reference_object_id () const inline virtual
A reference object represents a class of geometric objects. Tetrahedrons, Triangles etc are such classes. Reference ids should be defined in the file in which concrete geometric objects are defined.
Reimplemented from ug::Edge.
References ug::ROID_EDGE.
refine() [1/2]
bool ug::RegularEdge::refine (std::vector< Edge * > & vNewEdgesOut, Vertex * newVertex, Vertex ** pSubstituteVrts = NULL) virtual
virtual refine. Returns pointers to Edge.
create 2 new edges, connecting the original edges end-points with vrtNew.
See also
Edge::refine.
Reimplemented from ug::Edge.
References RegularEdge(), and ug::EdgeVertices::vertex().
Referenced by refine().
refine() [2/2]
bool ug::RegularEdge::refine (std::vector< RegularEdge * > & vNewEdgesOut, Vertex * newVertex, Vertex ** pSubstituteVrts = NULL)
non virtual refine. Returns pointers to RegularEdge.
create 2 new edges, connecting the original edges end-points with vrtNew.
See also
Edge::refine.
References refine().
type_match()
static bool ug::RegularEdge::type_match (GridObject * pObj) inline static
Friends And Related Function Documentation
Grid
friend class Grid friend
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid_objects/grid_objects_1d.h
ugbase/lib_grid/grid_objects/grid_objects_1d.cpp