ug4: ug::GridPointsOrdering< TDomain, TAlgebra > Class Template Reference
ug::GridPointsOrdering< TDomain, TAlgebra > Class Template Reference
Public Member Functions
template<typename TElem >
void count_sizes ()
void create_vtkoutput_ordering ()
SmartPtr< TGridFunctionNumberData > get ()
GridPointsOrdering (SmartPtr< TGridFunction > spGridFct, const char *name)
const char * name () const
template<typename TElem >
void number_points_elementwise ()
Private Types
typedef ug::Attachment< int > AVrtIndex
typedef GridFunction< TDomain, TAlgebra > TGridFunction
typedef GridFunctionNumberData< GridFunction< TDomain, TAlgebra > > TGridFunctionNumberData
Private Attributes
Grid::VertexAttachmentAccessor< AVrtIndex > m_aaVrtIndex
size_t m_n
const char * m_name
int m_numConn
int m_numElem
int m_numVert
SmartPtr< TGridFunction > m_u
Member Typedef Documentation
AVrtIndex
template<typename TDomain , typename TAlgebra > typedef ug::Attachment<int> ug::GridPointsOrdering< TDomain, TAlgebra >::AVrtIndex private
TGridFunction
template<typename TDomain , typename TAlgebra > typedef GridFunction<TDomain, TAlgebra> ug::GridPointsOrdering< TDomain, TAlgebra >::TGridFunction private
TGridFunctionNumberData
template<typename TDomain , typename TAlgebra > typedef GridFunctionNumberData<GridFunction<TDomain, TAlgebra> > ug::GridPointsOrdering< TDomain, TAlgebra >::TGridFunctionNumberData private
Constructor & Destructor Documentation
GridPointsOrdering()
template<typename TDomain , typename TAlgebra > ug::GridPointsOrdering< TDomain, TAlgebra >::GridPointsOrdering (SmartPtr< TGridFunction > spGridFct, const char * name) inline
References ug::GridFunction< TDomain, TAlgebra >::clone_without_values(), ug::GridPointsOrdering< TDomain, TAlgebra >::create_vtkoutput_ordering(), ug::DoFRef(), ug::GridFunction< TDomain, TAlgebra >::inner_dof_indices(), ug::GridPointsOrdering< TDomain, TAlgebra >::m_aaVrtIndex, ug::GridPointsOrdering< TDomain, TAlgebra >::m_n, ug::GridPointsOrdering< TDomain, TAlgebra >::m_name, ug::GridPointsOrdering< TDomain, TAlgebra >::m_numConn, ug::GridPointsOrdering< TDomain, TAlgebra >::m_numElem, ug::GridPointsOrdering< TDomain, TAlgebra >::m_numVert, ug::GridPointsOrdering< TDomain, TAlgebra >::m_u, and ug::GridPointsOrdering< TDomain, TAlgebra >::name().
Member Function Documentation
count_sizes()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::GridPointsOrdering< TDomain, TAlgebra >::count_sizes () inline
References ug::GridFunction< TDomain, TAlgebra >::domain(), ug::GetVertex(), ug::Grid::is_marked(), ug::GridPointsOrdering< TDomain, TAlgebra >::m_numConn, ug::GridPointsOrdering< TDomain, TAlgebra >::m_numElem, ug::GridPointsOrdering< TDomain, TAlgebra >::m_numVert, ug::GridPointsOrdering< TDomain, TAlgebra >::m_u, ug::Grid::mark(), and ug::ROID_OCTAHEDRON.
create_vtkoutput_ordering()
template<typename TDomain , typename TAlgebra > void ug::GridPointsOrdering< TDomain, TAlgebra >::create_vtkoutput_ordering () inline
References ug::Grid::attach_to_vertices(), ug::Grid::begin_marking(), dim, ug::DimensionOfSubsets(), ug::GridFunction< TDomain, TAlgebra >::domain(), ug::Grid::end_marking(), ug::DoFDistributionInfoProvider::is_def_everywhere(), ug::GridPointsOrdering< TDomain, TAlgebra >::m_aaVrtIndex, ug::GridPointsOrdering< TDomain, TAlgebra >::m_numVert, ug::GridPointsOrdering< TDomain, TAlgebra >::m_u, ug::GridPointsOrdering< TDomain, TAlgebra >::name(), ug::DoFDistributionInfoProvider::num_fct(), UG_CATCH_THROW, and UG_THROW.
Referenced by ug::GridPointsOrdering< TDomain, TAlgebra >::GridPointsOrdering().
get()
template<typename TDomain , typename TAlgebra > SmartPtr<TGridFunctionNumberData> ug::GridPointsOrdering< TDomain, TAlgebra >::get () inline
References ug::GridPointsOrdering< TDomain, TAlgebra >::m_name, and ug::GridPointsOrdering< TDomain, TAlgebra >::m_u.
name()
template<typename TDomain , typename TAlgebra > const char* ug::GridPointsOrdering< TDomain, TAlgebra >::name () const inline
Referenced by ug::GridPointsOrdering< TDomain, TAlgebra >::create_vtkoutput_ordering(), and ug::GridPointsOrdering< TDomain, TAlgebra >::GridPointsOrdering().
number_points_elementwise()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::GridPointsOrdering< TDomain, TAlgebra >::number_points_elementwise () inline
References ug::GridFunction< TDomain, TAlgebra >::domain(), ug::GetVertex(), ug::Grid::is_marked(), ug::GridPointsOrdering< TDomain, TAlgebra >::m_aaVrtIndex, ug::GridPointsOrdering< TDomain, TAlgebra >::m_n, ug::GridPointsOrdering< TDomain, TAlgebra >::m_u, and ug::Grid::mark().
Member Data Documentation
m_aaVrtIndex
template<typename TDomain , typename TAlgebra > Grid::VertexAttachmentAccessor<AVrtIndex> ug::GridPointsOrdering< TDomain, TAlgebra >::m_aaVrtIndex private
Referenced by ug::GridPointsOrdering< TDomain, TAlgebra >::create_vtkoutput_ordering(), ug::GridPointsOrdering< TDomain, TAlgebra >::GridPointsOrdering(), and ug::GridPointsOrdering< TDomain, TAlgebra >::number_points_elementwise().
m_n
template<typename TDomain , typename TAlgebra > size_t ug::GridPointsOrdering< TDomain, TAlgebra >::m_n private
Referenced by ug::GridPointsOrdering< TDomain, TAlgebra >::GridPointsOrdering(), and ug::GridPointsOrdering< TDomain, TAlgebra >::number_points_elementwise().
m_name
template<typename TDomain , typename TAlgebra > const char* ug::GridPointsOrdering< TDomain, TAlgebra >::m_name private
Referenced by ug::GridPointsOrdering< TDomain, TAlgebra >::get(), and ug::GridPointsOrdering< TDomain, TAlgebra >::GridPointsOrdering().
m_numConn
template<typename TDomain , typename TAlgebra > int ug::GridPointsOrdering< TDomain, TAlgebra >::m_numConn private
Referenced by ug::GridPointsOrdering< TDomain, TAlgebra >::count_sizes(), and ug::GridPointsOrdering< TDomain, TAlgebra >::GridPointsOrdering().
m_numElem
template<typename TDomain , typename TAlgebra > int ug::GridPointsOrdering< TDomain, TAlgebra >::m_numElem private
Referenced by ug::GridPointsOrdering< TDomain, TAlgebra >::count_sizes(), and ug::GridPointsOrdering< TDomain, TAlgebra >::GridPointsOrdering().
m_numVert
template<typename TDomain , typename TAlgebra > int ug::GridPointsOrdering< TDomain, TAlgebra >::m_numVert private
Referenced by ug::GridPointsOrdering< TDomain, TAlgebra >::count_sizes(), ug::GridPointsOrdering< TDomain, TAlgebra >::create_vtkoutput_ordering(), and ug::GridPointsOrdering< TDomain, TAlgebra >::GridPointsOrdering().
m_u
template<typename TDomain , typename TAlgebra > SmartPtr<TGridFunction> ug::GridPointsOrdering< TDomain, TAlgebra >::m_u private
Referenced by ug::GridPointsOrdering< TDomain, TAlgebra >::count_sizes(), ug::GridPointsOrdering< TDomain, TAlgebra >::create_vtkoutput_ordering(), ug::GridPointsOrdering< TDomain, TAlgebra >::get(), ug::GridPointsOrdering< TDomain, TAlgebra >::GridPointsOrdering(), and ug::GridPointsOrdering< TDomain, TAlgebra >::number_points_elementwise().
The documentation for this class was generated from the following file:
ugbase/lib_disc/ordering_strategies/io_grid_points_ordering.cpp