ug4: ug::LocalDoF Class Reference
ug::LocalDoF Class Reference
lib_discretization » Local Finite Elements
#include <local_dof_set.h>
Public Member Functions
int dim () const
returns the dimension of associated geometric object
size_t id () const
returns the index for the geometric object (w.r.t reference element numbering)
LocalDoF ()
default constructor
LocalDoF (int dim, size_t id, size_t offset)
constructor
size_t offset () const
returns the offset for the geometric object
bool operator!= (const LocalDoF &v) const
inequality check
bool operator== (const LocalDoF &v) const
equality check
void set (int dim, size_t id, size_t offset)
sets the values
Protected Attributes
int m_dim
dimension of sub-geometric object
size_t m_id
id of sub-geometric object in counting of reference element
size_t m_offset
offset if several DoFs associated to the same geometric object
Detailed Description
This class is used to store for a single degree of freedom (DoF) the location within an element. For continuous finite elements the DoFs are usually associated with a sub-geometric object of the element itself (e.g. a vertex). This can be requested from this class, which stores the dimension of the sub-element the DoF is located on, the id of the sub-element (w.r.t. to the numbering in the reference elements) and an offset > 0 if there are more than one DoFs associated with the same sub-element.
Constructor & Destructor Documentation
LocalDoF() [1/2]
ug::LocalDoF::LocalDoF () inline
default constructor
LocalDoF() [2/2]
ug::LocalDoF::LocalDoF (int dim, size_t id, size_t offset) inline
constructor
Create a pair describing the position of a DoF within the reference element.
Parameters
[in] dim dimension of sub-geometric object
[in] id number of sub-geometric object (in the numbering used by the reference element)
[in] offset if several DoFs are associated with the same sub-geometric object the offset specifies the number within all DoFs on that geometric object
Member Function Documentation
dim()
int ug::LocalDoF::dim () const inline
returns the dimension of associated geometric object
References m_dim.
Referenced by ug::InnerDoFPositionElem(), ug::operator<<(), operator==(), set(), and ug::SubLocalDoFSet< TDim >::SubLocalDoFSet().
id()
size_t ug::LocalDoF::id () const inline
returns the index for the geometric object (w.r.t reference element numbering)
References m_id.
Referenced by ug::operator<<(), operator==(), set(), and ug::SubLocalDoFSet< TDim >::SubLocalDoFSet().
offset()
size_t ug::LocalDoF::offset () const inline
returns the offset for the geometric object
References m_offset.
Referenced by ug::operator<<(), operator==(), and set().
operator!=()
bool ug::LocalDoF::operator!= (const LocalDoF & v) const inline
inequality check
operator==()
bool ug::LocalDoF::operator== (const LocalDoF & v) const inline
equality check
References dim(), id(), and offset().
set()
void ug::LocalDoF::set (int dim, size_t id, size_t offset) inline
sets the values
References dim(), id(), m_dim, m_id, m_offset, and offset().
Member Data Documentation
m_dim
int ug::LocalDoF::m_dim protected
dimension of sub-geometric object
Referenced by dim(), and set().
m_id
size_t ug::LocalDoF::m_id protected
id of sub-geometric object in counting of reference element
Referenced by id(), and set().
m_offset
size_t ug::LocalDoF::m_offset protected
offset if several DoFs associated to the same geometric object
Referenced by offset(), and set().
The documentation for this class was generated from the following file:
ugbase/lib_disc/local_finite_element/local_dof_set.h