ug4: ug::ReferenceMappingProvider Class Reference
ug::ReferenceMappingProvider Class Reference
class to provide reference mappings
#include <reference_mapping_provider.h>
Static Public Member Functions
template<int TDim, int TWorldDim>
static DimReferenceMapping< TDim, TWorldDim > & get (ReferenceObjectID roid)
returns a reference to a DimReferenceMapping
template<int TDim, int TWorldDim>
static DimReferenceMapping< TDim, TWorldDim > & get (ReferenceObjectID roid, const MathVector< TWorldDim > *vCornerCoord)
returns a reference to a DimReferenceMapping with updated element corners
template<int TDim, int TWorldDim>
static DimReferenceMapping< TDim, TWorldDim > & get (ReferenceObjectID roid, const std::vector< MathVector< TWorldDim > > &vCornerCoord)
returns a reference to a DimReferenceMapping with updated element corners
Private Member Functions
template<int TDim, int TWorldDim>
DimReferenceMapping< TDim, TWorldDim > * get_mapping (ReferenceObjectID roid)
ReferenceMappingProvider & operator= (const ReferenceMappingProvider &)
ReferenceMappingProvider ()
ReferenceMappingProvider (const ReferenceMappingProvider &)
template<int TDim, int TWorldDim>
void set_mapping (ReferenceObjectID roid, DimReferenceMapping< TDim, TWorldDim > &map)
~ReferenceMappingProvider ()
Static Private Member Functions
static ReferenceMappingProvider & inst ()
Private Attributes
void * m_vvvMapping [4][4][NUM_REFERENCE_OBJECTS]
Detailed Description
class to provide reference mappings
This class provides references mappings. It is implemented as a Singleton.
Constructor & Destructor Documentation
ReferenceMappingProvider() [1/2]
ug::ReferenceMappingProvider::ReferenceMappingProvider () private
References get(), m_vvvMapping, ug::NUM_REFERENCE_OBJECTS, ug::ROID_EDGE, ug::ROID_HEXAHEDRON, ug::ROID_OCTAHEDRON, ug::ROID_PRISM, ug::ROID_PYRAMID, ug::ROID_QUADRILATERAL, ug::ROID_TETRAHEDRON, and ug::ROID_TRIANGLE.
ReferenceMappingProvider() [2/2]
ug::ReferenceMappingProvider::ReferenceMappingProvider (const ReferenceMappingProvider &) private
~ReferenceMappingProvider()
ug::ReferenceMappingProvider::~ReferenceMappingProvider () inline private
Member Function Documentation
get() [1/3]
template<int TDim, int TWorldDim> static DimReferenceMapping<TDim, TWorldDim>& ug::ReferenceMappingProvider::get (ReferenceObjectID roid) inline static
returns a reference to a DimReferenceMapping
This class returns a reference mapping for a ReferenceObjectID. The reference dimension and the world dimension must be chosen as template arguments. An exception is throw if such an mapping does not exist.
Parameters
[in] roid Reference Object ID
Template Parameters
TDim reference element dimension
TWorldDim (physical) world dimension
References get_mapping(), inst(), and UG_THROW.
Referenced by ug::SideAndElemErrEstData< TDomain >::get_elem_error_indicator(), ug::SideAndElemErrEstData< TDomain >::init_quadrature(), ug::IntegralNormalComponentOnManifoldGeneral(), ReferenceMappingProvider(), ug::SideAndElemErrEstData< TDomain >::side_global_ips(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
get() [2/3]
template<int TDim, int TWorldDim> static DimReferenceMapping<TDim, TWorldDim>& ug::ReferenceMappingProvider::get (ReferenceObjectID roid, const MathVector< TWorldDim > * vCornerCoord) inline static
returns a reference to a DimReferenceMapping with updated element corners
This class returns a reference mapping for a ReferenceObjectID. The reference dimension and the world dimension must be chosen as template arguments. An exception is throw if such an mapping does not exist.
Parameters
[in] roid Reference Object ID
[in] vCornerCoord The corner coordinates of the element
Template Parameters
TDim reference element dimension
TWorldDim (physical) world dimension
References ug::DimReferenceMapping< TDim, TWorldDim >::update().
get() [3/3]
template<int TDim, int TWorldDim> static DimReferenceMapping<TDim, TWorldDim>& ug::ReferenceMappingProvider::get (ReferenceObjectID roid, const std::vector< MathVector< TWorldDim > > & vCornerCoord) inline static
returns a reference to a DimReferenceMapping with updated element corners
This class returns a reference mapping for a ReferenceObjectID. The reference dimension and the world dimension must be chosen as template arguments. An exception is throw if such an mapping does not exist.
Parameters
[in] roid Reference Object ID
[in] vCornerCoord The corner coordinates of the element
Template Parameters
TDim reference element dimension
TWorldDim (physical) world dimension
References ug::DimReferenceMapping< TDim, TWorldDim >::update().
get_mapping()
template<int TDim, int TWorldDim> DimReferenceMapping<TDim, TWorldDim>* ug::ReferenceMappingProvider::get_mapping (ReferenceObjectID roid) inline private
References m_vvvMapping, ug::NUM_REFERENCE_OBJECTS, UG_ASSERT, and UG_STATIC_ASSERT.
Referenced by get().
inst()
static ReferenceMappingProvider& ug::ReferenceMappingProvider::inst () inline static private
Referenced by get().
operator=()
ReferenceMappingProvider& ug::ReferenceMappingProvider::operator= (const ReferenceMappingProvider &) private
set_mapping()
template<int TDim, int TWorldDim> void ug::ReferenceMappingProvider::set_mapping (ReferenceObjectID roid, DimReferenceMapping< TDim, TWorldDim > & map) inline private
References m_vvvMapping.
Member Data Documentation
m_vvvMapping
void* ug::ReferenceMappingProvider::m_vvvMapping[4][4][NUM_REFERENCE_OBJECTS] private
Referenced by get_mapping(), ReferenceMappingProvider(), and set_mapping().
The documentation for this class was generated from the following files:
ugbase/lib_disc/reference_element/reference_mapping_provider.h
ugbase/lib_disc/reference_element/reference_mapping_provider.cpp