ug4: ug::CylindricalFalloffProjector< TAPosition > Class Template Reference
ug::CylindricalFalloffProjector< TAPosition > Class Template Reference
lib_grid » algorithms » refinement
calculates new positions of vertices by projecting on a cylinder
#include <cylindrical_falloff_projector.h>
Public Member Functions
virtual int current_pos (number *coordsOut, Vertex *vrt, int maxCoords)
Gives access to the position of the current vertex.
CylindricalFalloffProjector ()
CylindricalFalloffProjector (Grid &grid, TAPosition &aPos, const typename TAPosition::ValueType &center, const typename TAPosition::ValueType &axis, number innerRadius, number outerRadius)
make sure that aPos is attached to the vertices of the grid.
virtual void new_vertex (Vertex *vrt, Vertex *parent)
called when a new vertex was created from an old vertex.
virtual void new_vertex (Vertex *vrt, Edge *parent)
called when a new vertex was created from an old edge.
virtual void new_vertex (Vertex *vrt, Face *parent)
called when a new vertex was created from an old face.
virtual void new_vertex (Vertex *vrt, Volume *parent)
called when a new vertex was created from an old volume.
virtual ~CylindricalFalloffProjector ()
Public Member Functions inherited from ug::IRefinementCallback
virtual void flat_grid_vertex_encountered (Vertex *vrt)
callback for vertices in flat grids.
virtual ~IRefinementCallback ()
Protected Types
typedef TAPosition::ValueType pos_type
Protected Member Functions
template<class TElem >
void perform_projection (Vertex *vrt, TElem *parent)
Protected Member Functions inherited from ug::IRefinementCallback
template<class TAttachmentAccessor >
int current_pos_helper (number *coordsOut, Vertex *vrt, int maxCoords, TAttachmentAccessor &aaPos)
A helper implementation of current_pos available for derived classes.
Protected Attributes
Grid::VertexAttachmentAccessor< TAPosition > m_aaPos
pos_type m_axis
pos_type m_center
number m_innerRadius
number m_outerRadius
Grid * m_pGrid
Detailed Description
template<class TAPosition>
class ug::CylindricalFalloffProjector< TAPosition >
calculates new positions of vertices by projecting on a cylinder
Only vertices inside innerRadius are projected to a cylinder. The ones outside of outerRadius are positioned through normal linear interpolation. The ones in between are gradually processed from cylindrical-projection to linear interpolation.
Make sure to initialize the callback correctly. Use the same grid on which the refinement-operations will be performed. Make sure that aPos (given in the constructor) is attached to the vertices of the grid.
An uninitialized refinement-callback may not be used during refinement.
Member Typedef Documentation
template<class TAPosition > typedef TAPosition::ValueType ug::CylindricalFalloffProjector< TAPosition >::pos_type protected
Constructor & Destructor Documentation
template<class TAPosition > ug::CylindricalFalloffProjector< TAPosition >::CylindricalFalloffProjector ()
template<class TAPosition > ug::CylindricalFalloffProjector< TAPosition >::CylindricalFalloffProjector (Grid & grid, TAPosition & aPos, const typename TAPosition::ValueType & center, const typename TAPosition::ValueType & axis, number innerRadius, number outerRadius)
make sure that aPos is attached to the vertices of the grid.
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::Grid::attach_to_vertices(), ug::Grid::has_vertex_attachment(), ug::CylindricalFalloffProjector< TAPosition >::m_aaPos, ug::CylindricalFalloffProjector< TAPosition >::m_innerRadius, ug::CylindricalFalloffProjector< TAPosition >::m_outerRadius, ug::SMALL, and ug::CylindricalFalloffProjector< TAPosition >::~CylindricalFalloffProjector().
template<class TAPosition > ug::CylindricalFalloffProjector< TAPosition >::~CylindricalFalloffProjector () virtual
References ug::CylindricalFalloffProjector< TAPosition >::new_vertex().
Referenced by ug::CylindricalFalloffProjector< TAPosition >::CylindricalFalloffProjector().
Member Function Documentation
template<class TAPosition > int ug::CylindricalFalloffProjector< TAPosition >::current_pos (number * coordsOut, Vertex * vrt, int maxCoords) virtual
Gives access to the position of the current vertex.
The method returns the number of coordinates associated with the vertex and writes those coordinates to coordsOut. No more than maxCoords will be written to coordsOut. coordsOut thus has to be at least as big as maxCoords.
Implements ug::IRefinementCallback.
References ug::IRefinementCallback::current_pos_helper(), ug::CylindricalFalloffProjector< TAPosition >::m_aaPos, and ug::CylindricalFalloffProjector< TAPosition >::perform_projection().
Referenced by ug::CylindricalFalloffProjector< TAPosition >::new_vertex().
template<class TAPosition > void ug::CylindricalFalloffProjector< TAPosition >::new_vertex (Vertex * vrt, Vertex * parent) virtual
called when a new vertex was created from an old vertex.
Implements ug::IRefinementCallback.
References ug::CylindricalFalloffProjector< TAPosition >::m_aaPos, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid().
Referenced by ug::CylindricalFalloffProjector< TAPosition >::new_vertex(), and ug::CylindricalFalloffProjector< TAPosition >::~CylindricalFalloffProjector().
template<class TAPosition > void ug::CylindricalFalloffProjector< TAPosition >::new_vertex (Vertex * vrt, Edge * parent) virtual
called when a new vertex was created from an old edge.
Implements ug::IRefinementCallback.
References ug::CylindricalFalloffProjector< TAPosition >::new_vertex(), and ug::CylindricalFalloffProjector< TAPosition >::perform_projection().
template<class TAPosition > void ug::CylindricalFalloffProjector< TAPosition >::new_vertex (Vertex * vrt, Face * parent) virtual
called when a new vertex was created from an old face.
Implements ug::IRefinementCallback.
References ug::CylindricalFalloffProjector< TAPosition >::new_vertex(), and ug::CylindricalFalloffProjector< TAPosition >::perform_projection().
template<class TAPosition > void ug::CylindricalFalloffProjector< TAPosition >::new_vertex (Vertex * vrt, Volume * parent) virtual
called when a new vertex was created from an old volume.
Implements ug::IRefinementCallback.
References ug::CylindricalFalloffProjector< TAPosition >::current_pos(), and ug::CylindricalFalloffProjector< TAPosition >::perform_projection().
template<class TAPosition > template<class TElem > void ug::CylindricalFalloffProjector< TAPosition >::perform_projection (Vertex * vrt, TElem * parent) protected
References ug::DistancePointToRay(), ug::CylindricalFalloffProjector< TAPosition >::m_aaPos, ug::CylindricalFalloffProjector< TAPosition >::m_axis, ug::CylindricalFalloffProjector< TAPosition >::m_center, ug::CylindricalFalloffProjector< TAPosition >::m_innerRadius, ug::CylindricalFalloffProjector< TAPosition >::m_outerRadius, ug::ProjectPointToRay(), ug::SMALL, ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid(), ug::VecAdd(), ug::VecLength(), ug::VecScale(), ug::VecScaleAdd(), ug::VecSet(), and ug::VecSubtract().
Referenced by ug::CylindricalFalloffProjector< TAPosition >::current_pos(), and ug::CylindricalFalloffProjector< TAPosition >::new_vertex().
Member Data Documentation
template<class TAPosition > Grid::VertexAttachmentAccessor<TAPosition> ug::CylindricalFalloffProjector< TAPosition >::m_aaPos protected
Referenced by ug::CylindricalFalloffProjector< TAPosition >::current_pos(), ug::CylindricalFalloffProjector< TAPosition >::CylindricalFalloffProjector(), ug::CylindricalFalloffProjector< TAPosition >::new_vertex(), and ug::CylindricalFalloffProjector< TAPosition >::perform_projection().
template<class TAPosition > pos_type ug::CylindricalFalloffProjector< TAPosition >::m_axis protected
Referenced by ug::CylindricalFalloffProjector< TAPosition >::perform_projection().
template<class TAPosition > pos_type ug::CylindricalFalloffProjector< TAPosition >::m_center protected
Referenced by ug::CylindricalFalloffProjector< TAPosition >::perform_projection().
template<class TAPosition > number ug::CylindricalFalloffProjector< TAPosition >::m_innerRadius protected
Referenced by ug::CylindricalFalloffProjector< TAPosition >::CylindricalFalloffProjector(), and ug::CylindricalFalloffProjector< TAPosition >::perform_projection().
template<class TAPosition > number ug::CylindricalFalloffProjector< TAPosition >::m_outerRadius protected
Referenced by ug::CylindricalFalloffProjector< TAPosition >::CylindricalFalloffProjector(), and ug::CylindricalFalloffProjector< TAPosition >::perform_projection().
template<class TAPosition > Grid* ug::CylindricalFalloffProjector< TAPosition >::m_pGrid protected
The documentation for this class was generated from the following files:
ugbase/lib_grid/algorithms/refinement/refinement_projectors/cylindrical_falloff_projector.h
ugbase/lib_grid/algorithms/refinement/refinement_projectors/cylindrical_falloff_projector_impl.h