ug4: ug::non_dirichlet_iterator< TAlgebra > Class Template Reference
ug::non_dirichlet_iterator< TAlgebra > Class Template Reference
Public Types
typedef TAlgebra::matrix_type matrix_type
Public Member Functions
non_dirichlet_iterator (matrix_type &mat, unsigned i, unsigned num)
bool operator!= (const non_dirichlet_iterator &o) const
unsigned operator* () const
void operator++ ()
bool operator== (const non_dirichlet_iterator &o) const
Protected Attributes
matrix_type & A
unsigned cur
unsigned n
Member Typedef Documentation
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::non_dirichlet_iterator< TAlgebra >::matrix_type
Constructor & Destructor Documentation
non_dirichlet_iterator()
template<typename TAlgebra > ug::non_dirichlet_iterator< TAlgebra >::non_dirichlet_iterator (matrix_type & mat, unsigned i, unsigned num) inline
References ug::non_dirichlet_iterator< TAlgebra >::operator++().
Member Function Documentation
operator!=()
template<typename TAlgebra > bool ug::non_dirichlet_iterator< TAlgebra >::operator!= (const non_dirichlet_iterator< TAlgebra > & o) const inline
References ug::non_dirichlet_iterator< TAlgebra >::operator==().
operator*()
template<typename TAlgebra > unsigned ug::non_dirichlet_iterator< TAlgebra >::operator* () const inline
References ug::non_dirichlet_iterator< TAlgebra >::cur.
operator++()
template<typename TAlgebra > void ug::non_dirichlet_iterator< TAlgebra >::operator++ () inline
References ug::non_dirichlet_iterator< TAlgebra >::A, ug::non_dirichlet_iterator< TAlgebra >::cur, and ug::non_dirichlet_iterator< TAlgebra >::n.
Referenced by ug::non_dirichlet_iterator< TAlgebra >::non_dirichlet_iterator().
operator==()
template<typename TAlgebra > bool ug::non_dirichlet_iterator< TAlgebra >::operator== (const non_dirichlet_iterator< TAlgebra > & o) const inline
References ug::non_dirichlet_iterator< TAlgebra >::cur.
Referenced by ug::non_dirichlet_iterator< TAlgebra >::operator!=().
Member Data Documentation
A
template<typename TAlgebra > matrix_type& ug::non_dirichlet_iterator< TAlgebra >::A protected
Referenced by ug::non_dirichlet_iterator< TAlgebra >::operator++().
cur
template<typename TAlgebra > unsigned ug::non_dirichlet_iterator< TAlgebra >::cur protected
Referenced by ug::non_dirichlet_iterator< TAlgebra >::operator*(), ug::non_dirichlet_iterator< TAlgebra >::operator++(), and ug::non_dirichlet_iterator< TAlgebra >::operator==().
n
template<typename TAlgebra > unsigned ug::non_dirichlet_iterator< TAlgebra >::n protected
Referenced by ug::non_dirichlet_iterator< TAlgebra >::operator++().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/ordering_strategies/algorithms/iters.cpp