ug4: ug::NTreeGridData< world_dim > Class Template Reference
ug::NTreeGridData< world_dim > Class Template Reference
#include <lg_ntree.h>
Public Types
typedef Grid::VertexAttachmentAccessor< position_attachment_t > position_accessor_t
typedef Attachment< position_t > position_attachment_t
typedef MathVector< world_dim > position_t
Public Member Functions
Grid * grid_ptr () const
NTreeGridData ()
NTreeGridData (Grid &grid, position_attachment_t aPos)
const position_t & position (Vertex *v) const
position_accessor_t position_accessor () const
Private Attributes
position_accessor_t m_aaPos
Grid * m_pGrid
Member Typedef Documentation
position_accessor_t
template<int world_dim> typedef Grid::VertexAttachmentAccessor<position_attachment_t> ug::NTreeGridData< world_dim >::position_accessor_t
position_attachment_t
template<int world_dim> typedef Attachment<position_t> ug::NTreeGridData< world_dim >::position_attachment_t
position_t
template<int world_dim> typedef MathVector<world_dim > ug::NTreeGridData< world_dim >::position_t
Constructor & Destructor Documentation
NTreeGridData() [1/2]
template<int world_dim> ug::NTreeGridData< world_dim >::NTreeGridData () inline
NTreeGridData() [2/2]
template<int world_dim> ug::NTreeGridData< world_dim >::NTreeGridData (Grid & grid, position_attachment_t aPos) inline
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::Grid::attach_to_vertices(), ug::Grid::has_vertex_attachment(), ug::NTreeGridData< world_dim >::m_aaPos, and ug::NTreeGridData< world_dim >::m_pGrid.
Member Function Documentation
grid_ptr()
template<int world_dim> Grid* ug::NTreeGridData< world_dim >::grid_ptr () const inline
References ug::NTreeGridData< world_dim >::m_pGrid.
position()
template<int world_dim> const position_t& ug::NTreeGridData< world_dim >::position (Vertex * v) const inline
References ug::NTreeGridData< world_dim >::m_aaPos, UG_ASSERT, and ug::AttachmentAccessor< TElem, TAttachment, TElemHandler >::valid().
position_accessor()
template<int world_dim> position_accessor_t ug::NTreeGridData< world_dim >::position_accessor () const inline
References ug::NTreeGridData< world_dim >::m_aaPos.
Member Data Documentation
m_aaPos
template<int world_dim> position_accessor_t ug::NTreeGridData< world_dim >::m_aaPos private
Referenced by ug::NTreeGridData< world_dim >::NTreeGridData(), ug::NTreeGridData< world_dim >::position(), and ug::NTreeGridData< world_dim >::position_accessor().
m_pGrid
template<int world_dim> Grid* ug::NTreeGridData< world_dim >::m_pGrid private
Referenced by ug::NTreeGridData< world_dim >::grid_ptr(), and ug::NTreeGridData< world_dim >::NTreeGridData().
The documentation for this class was generated from the following file:
ugbase/lib_grid/algorithms/space_partitioning/lg_ntree.h