ug4: ug::HCRFVGeometry< TElem, TWorldDim > Class Template Reference
ug::HCRFVGeometry< TElem, TWorldDim > Class Template Reference
#include <hfvcr_geom.h>
Classes
class CONSTRAINED_DOF
class HandledEdge
class SCV
sub control volume structure
class SCVF
Sub-Control Volume Face structure.
Public Types
typedef TElem elem_type
type of element
typedef hcrfv_traits< TWorldDim, TWorldDim >::face_type face_type0
typedef hcrfv_traits< TWorldDim, TWorldDim+1 >::face_type face_type1
typedef CrouzeixRaviartLSFS< ref_elem_type > local_shape_fct_set_type
type of Shape function used
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
type of reference element
typedef hcrfv_traits< TWorldDim, TWorldDim >::scv_type scv_type0
traits
typedef hcrfv_traits< TWorldDim, TWorldDim+1 >::scv_type scv_type1
typedef hcrfv_traits< dim, worldDim > traits
used traits
Public Member Functions
const CONSTRAINED_DOF & constrained_dof (size_t i) const
const access to constrained dof i
const MathVector< worldDim > * corners () const
const MathVector< worldDim > global_bary () const
returns global barycenter
HCRFVGeometry ()
construct object and initialize local values and sizes
const MathVector< dim > local_bary () const
returns local barycenter
size_t num_constrained_dofs () const
number of constrained dofs
size_t num_scv () const
number of SubControlVolumes
size_t num_scv_ips () const
returns number of all scv ips
size_t num_scvf () const
number of SubControlVolumeFaces
size_t num_scvf_ips () const
returns number of all scvf ips
size_t num_sh () const
number of shape functions
void print ()
debug output
const SCV & scv (size_t i) const
const access to SubControlVolume number i
const MathVector< worldDim > * scv_global_ips () const
returns all ips of scv as they appear in scv loop
const MathVector< dim > * scv_local_ips () const
returns all ips of scv as they appear in scv loop
const SCVF & scvf (size_t i) const
const access to SubControlVolumeFace number i
const MathVector< worldDim > * scvf_global_ips () const
returns all ips of scvf as they appear in scv loop
const MathVector< dim > * scvf_local_ips () const
returns all ips of scvf as they appear in scv loop
void update (GridObject *elem, const MathVector< worldDim > *vCornerCoords, const ISubsetHandler *ish=NULL)
update data for given element
void update_local_data ()
update local data
Public Attributes
MathVector< worldDim > globalBary
MathVector< dim > localBary
Static Public Attributes
static const int dim = ref_elem_type::dim
dimension of reference element
static const size_t maxNumSCV = traits::maxNumSCV
static const size_t maxNumSCVF = traits::maxNumSCVF
static const size_t nip = 1
number of integration points
static const size_t nsh = local_shape_fct_set_type::nsh
number of shape functions
static const size_t numNaturalSCV = nsh
number of SubControlVolumes
static const size_t numNaturalSCVF = ref_elem_type::numEdges
number of SubControlVolumeFaces
static const int order = 1
order
static const bool staticLocalData = true
flag indicating if local data may change
static const bool usesHangingNodes = true
Hanging node flag: this geometry supports hanging nodes.
static const int worldDim = TWorldDim
dimension of world
Protected Attributes
MathVector< worldDim > m_vCo [numMaxCo]
MathVector< worldDim > m_vGlobSCVF_IP [maxNumSCVF]
MathVector< worldDim > m_vGlobUnkCoords [maxNumSCV]
MathVector< dim > m_vLocSCVF_IP [maxNumSCVF]
MathVector< dim > m_vLocUnkCoords [maxNumSCV]
Static Protected Attributes
static const size_t numMaxCo = 8
Private Attributes
std::vector< HandledEdge > handledEdges
bool localUpdateNecessary
MathVector< dim > m_ipCoord [maxNumSCVF]
ReferenceMapping< ref_elem_type, worldDim > m_mapping
Reference Mapping.
TElem * m_pElem
pointer to current element
const ref_elem_type & m_rRefElem
Reference Element.
const local_shape_fct_set_type & m_rTrialSpace
Shape function set.
CONSTRAINED_DOF m_vCD [maxNumSCV]
constrained Dofs
SCV m_vSCV [maxNumSCV]
SubControlVolumes.
SCVF m_vSCVF [maxNumSCVF]
SubControlVolumeFaces.
size_t numConstrainedDofs
size_t numDofs
size_t numSCV
size_t numSCVF
Static Private Attributes
static const size_t deleted = 117
Member Typedef Documentation
template<typename TElem , int TWorldDim> typedef TElem ug::HCRFVGeometry< TElem, TWorldDim >::elem_type
type of element
template<typename TElem , int TWorldDim> typedef hcrfv_traits<TWorldDim,TWorldDim>::face_type ug::HCRFVGeometry< TElem, TWorldDim >::face_type0
template<typename TElem , int TWorldDim> typedef hcrfv_traits<TWorldDim,TWorldDim+1>::face_type ug::HCRFVGeometry< TElem, TWorldDim >::face_type1
template<typename TElem , int TWorldDim> typedef CrouzeixRaviartLSFS<ref_elem_type> ug::HCRFVGeometry< TElem, TWorldDim >::local_shape_fct_set_type
type of Shape function used
template<typename TElem , int TWorldDim> typedef reference_element_traits<TElem>::reference_element_type ug::HCRFVGeometry< TElem, TWorldDim >::ref_elem_type
type of reference element
template<typename TElem , int TWorldDim> typedef hcrfv_traits<TWorldDim,TWorldDim>::scv_type ug::HCRFVGeometry< TElem, TWorldDim >::scv_type0
traits
template<typename TElem , int TWorldDim> typedef hcrfv_traits<TWorldDim,TWorldDim+1>::scv_type ug::HCRFVGeometry< TElem, TWorldDim >::scv_type1
template<typename TElem , int TWorldDim> typedef hcrfv_traits<dim,worldDim> ug::HCRFVGeometry< TElem, TWorldDim >::traits
used traits
Constructor & Destructor Documentation
template<typename TElem , int TWorldDim> ug::HCRFVGeometry< TElem, TWorldDim >::HCRFVGeometry ()
construct object and initialize local values and sizes
References ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
Member Function Documentation
template<typename TElem , int TWorldDim> const CONSTRAINED_DOF& ug::HCRFVGeometry< TElem, TWorldDim >::constrained_dof (size_t i) const inline
const access to constrained dof i
References UG_ASSERT.
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::HCRFVGeometry< TElem, TWorldDim >::corners () const inline
template<typename TElem , int TWorldDim> const MathVector<worldDim> ug::HCRFVGeometry< TElem, TWorldDim >::global_bary () const inline
returns global barycenter
template<typename TElem , int TWorldDim> const MathVector<dim> ug::HCRFVGeometry< TElem, TWorldDim >::local_bary () const inline
returns local barycenter
template<typename TElem , int TWorldDim> size_t ug::HCRFVGeometry< TElem, TWorldDim >::num_constrained_dofs () const inline
number of constrained dofs
template<typename TElem , int TWorldDim> size_t ug::HCRFVGeometry< TElem, TWorldDim >::num_scv () const inline
number of SubControlVolumes
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> size_t ug::HCRFVGeometry< TElem, TWorldDim >::num_scv_ips () const inline
returns number of all scv ips
template<typename TElem , int TWorldDim> size_t ug::HCRFVGeometry< TElem, TWorldDim >::num_scvf () const inline
number of SubControlVolumeFaces
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> size_t ug::HCRFVGeometry< TElem, TWorldDim >::num_scvf_ips () const inline
returns number of all scvf ips
template<typename TElem , int TWorldDim> size_t ug::HCRFVGeometry< TElem, TWorldDim >::num_sh () const inline
number of shape functions
template<typename TElem , int TWorldDim> void ug::HCRFVGeometry< TElem, TWorldDim >::print ()
debug output
References ug::HCRFVGeometry< TElem, TWorldDim >::m_vCD, ug::HCRFVGeometry< TElem, TWorldDim >::m_vSCV, ug::HCRFVGeometry< TElem, TWorldDim >::m_vSCVF, ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::num_sh(), ug::HCRFVGeometry< TElem, TWorldDim >::numConstrainedDofs, ug::HCRFVGeometry< TElem, TWorldDim >::CONSTRAINED_DOF::numConstrainingDofs, ug::HCRFVGeometry< TElem, TWorldDim >::numSCV, ug::HCRFVGeometry< TElem, TWorldDim >::numSCVF, and UG_LOG.
template<typename TElem , int TWorldDim> const SCV& ug::HCRFVGeometry< TElem, TWorldDim >::scv (size_t i) const inline
const access to SubControlVolume number i
References UG_ASSERT.
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::HCRFVGeometry< TElem, TWorldDim >::scv_global_ips () const inline
returns all ips of scv as they appear in scv loop
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::HCRFVGeometry< TElem, TWorldDim >::scv_local_ips () const inline
returns all ips of scv as they appear in scv loop
template<typename TElem , int TWorldDim> const SCVF& ug::HCRFVGeometry< TElem, TWorldDim >::scvf (size_t i) const inline
const access to SubControlVolumeFace number i
References UG_ASSERT.
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const MathVector<worldDim>* ug::HCRFVGeometry< TElem, TWorldDim >::scvf_global_ips () const inline
returns all ips of scvf as they appear in scv loop
template<typename TElem , int TWorldDim> const MathVector<dim>* ug::HCRFVGeometry< TElem, TWorldDim >::scvf_local_ips () const inline
returns all ips of scvf as they appear in scv loop
template<typename TElem , int TWorldDim> void ug::HCRFVGeometry< TElem, TWorldDim >::update (GridObject * elem, const MathVector< worldDim > * vCornerCoords, const ISubsetHandler * ish = NULL)
update data for given element
References ug::HCRFVGeometry< TElem, TWorldDim >::HandledEdge::associatedSCV, ug::AveragePositions(), ug::HCRFVGeometry< TElem, TWorldDim >::CONSTRAINED_DOF::cDofInd, ug::HCRFVGeometry< TElem, TWorldDim >::CONSTRAINED_DOF::cDofWeights, ug::CollectEdgesSorted(), ug::CollectFacesSorted(), ug::HCRFVGeometry< TElem, TWorldDim >::deleted, ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::detj, ug::HCRFVGeometry< TElem, TWorldDim >::SCV::detj, ug::HCRFVGeometry< TElem, TWorldDim >::dim, ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::From, ug::HCRFVGeometry< TElem, TWorldDim >::HandledEdge::from, ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::global_ip(), ug::HCRFVGeometry< TElem, TWorldDim >::globalBary, ug::ISubsetHandler::grid(), ug::HCRFVGeometry< TElem, TWorldDim >::handledEdges, ug::HCRFVGeometry< TElem, TWorldDim >::CONSTRAINED_DOF::i, ug::HCRFVGeometry< TElem, TWorldDim >::HandledEdge::index, ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::JtInv, ug::HCRFVGeometry< TElem, TWorldDim >::SCV::JtInv, ug::HCRFVGeometry< TElem, TWorldDim >::localBary, ug::HCRFVGeometry< TElem, TWorldDim >::localUpdateNecessary, ug::HCRFVGeometry< TElem, TWorldDim >::m_mapping, ug::HCRFVGeometry< TElem, TWorldDim >::m_pElem, ug::HCRFVGeometry< TElem, TWorldDim >::m_rRefElem, ug::HCRFVGeometry< TElem, TWorldDim >::m_rTrialSpace, ug::HCRFVGeometry< TElem, TWorldDim >::m_vCD, ug::HCRFVGeometry< TElem, TWorldDim >::m_vCo, ug::HCRFVGeometry< TElem, TWorldDim >::m_vGlobSCVF_IP, ug::HCRFVGeometry< TElem, TWorldDim >::m_vGlobUnkCoords, ug::HCRFVGeometry< TElem, TWorldDim >::m_vLocUnkCoords, ug::HCRFVGeometry< TElem, TWorldDim >::m_vSCV, ug::HCRFVGeometry< TElem, TWorldDim >::m_vSCVF, ug::MatVecMult(), ug::HCRFVGeometry< TElem, TWorldDim >::SCV::nodeID, ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::Normal, ug::HCRFVGeometry< TElem, TWorldDim >::SCV::Normal, ug::HCRFVGeometry< TElem, TWorldDim >::num_scv(), ug::HCRFVGeometry< TElem, TWorldDim >::num_scvf(), ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::num_sh(), ug::HCRFVGeometry< TElem, TWorldDim >::SCV::num_sh(), ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::numCo, ug::HCRFVGeometry< TElem, TWorldDim >::numConstrainedDofs, ug::HCRFVGeometry< TElem, TWorldDim >::CONSTRAINED_DOF::numConstrainingDofs, ug::HCRFVGeometry< TElem, TWorldDim >::SCV::numCorners, ug::HCRFVGeometry< TElem, TWorldDim >::numDofs, ug::HCRFVGeometry< TElem, TWorldDim >::numSCV, ug::HCRFVGeometry< TElem, TWorldDim >::numSCVF, ug::HCRFVGeometry< TElem, TWorldDim >::scv(), ug::HCRFVGeometry< TElem, TWorldDim >::scvf(), ug::HCRFVGeometry< TElem, TWorldDim >::HandledEdge::scvfIndex, ug::ReferenceMapping< TRefElem, TWorldDim >::sqrt_gram_det(), ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::To, UG_ASSERT, ug::ReferenceMapping< TRefElem, TWorldDim >::update(), ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data(), ug::HCRFVGeometry< TElem, TWorldDim >::SCV::vGlobIP, ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::vGloPos, ug::HCRFVGeometry< TElem, TWorldDim >::SCV::vGloPos, ug::HCRFVGeometry< TElem, TWorldDim >::SCV::vLocIP, ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::vLocPos, ug::HCRFVGeometry< TElem, TWorldDim >::SCV::vLocPos, ug::HCRFVGeometry< TElem, TWorldDim >::SCV::Vol, and ug::HCRFVGeometry< TElem, TWorldDim >::worldDim.
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> void ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data ()
update local data
References ug::AveragePositions(), ug::HCRFVGeometry< TElem, TWorldDim >::dim, ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::From, ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::local_ip(), ug::HCRFVGeometry< TElem, TWorldDim >::localBary, ug::HCRFVGeometry< TElem, TWorldDim >::localUpdateNecessary, ug::HCRFVGeometry< TElem, TWorldDim >::m_rRefElem, ug::HCRFVGeometry< TElem, TWorldDim >::m_rTrialSpace, ug::HCRFVGeometry< TElem, TWorldDim >::m_vLocSCVF_IP, ug::HCRFVGeometry< TElem, TWorldDim >::m_vLocUnkCoords, ug::HCRFVGeometry< TElem, TWorldDim >::m_vSCV, ug::HCRFVGeometry< TElem, TWorldDim >::m_vSCVF, ug::HCRFVGeometry< TElem, TWorldDim >::SCV::nodeID, ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::numCo, ug::HCRFVGeometry< TElem, TWorldDim >::numConstrainedDofs, ug::HCRFVGeometry< TElem, TWorldDim >::SCV::numCorners, ug::HCRFVGeometry< TElem, TWorldDim >::numDofs, ug::HCRFVGeometry< TElem, TWorldDim >::numNaturalSCV, ug::HCRFVGeometry< TElem, TWorldDim >::numNaturalSCVF, ug::HCRFVGeometry< TElem, TWorldDim >::numSCV, ug::HCRFVGeometry< TElem, TWorldDim >::numSCVF, ug::HCRFVGeometry< TElem, TWorldDim >::scvf(), ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::To, ug::HCRFVGeometry< TElem, TWorldDim >::update(), ug::HCRFVGeometry< TElem, TWorldDim >::SCV::vLocIP, ug::HCRFVGeometry< TElem, TWorldDim >::SCVF::vLocPos, and ug::HCRFVGeometry< TElem, TWorldDim >::SCV::vLocPos.
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::HCRFVGeometry(), and ug::HCRFVGeometry< TElem, TWorldDim >::update().
Member Data Documentation
template<typename TElem , int TWorldDim> const size_t ug::HCRFVGeometry< TElem, TWorldDim >::deleted = 117 static private
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> const int ug::HCRFVGeometry< TElem, TWorldDim >::dim = ref_elem_type::dim static
dimension of reference element
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::HCRFVGeometry< TElem, TWorldDim >::globalBary
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> std::vector<HandledEdge> ug::HCRFVGeometry< TElem, TWorldDim >::handledEdges private
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> MathVector<dim> ug::HCRFVGeometry< TElem, TWorldDim >::localBary
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> bool ug::HCRFVGeometry< TElem, TWorldDim >::localUpdateNecessary private
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> MathVector<dim> ug::HCRFVGeometry< TElem, TWorldDim >::m_ipCoord[maxNumSCVF] private
template<typename TElem , int TWorldDim> ReferenceMapping<ref_elem_type, worldDim> ug::HCRFVGeometry< TElem, TWorldDim >::m_mapping private
Reference Mapping.
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> TElem* ug::HCRFVGeometry< TElem, TWorldDim >::m_pElem private
pointer to current element
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> const ref_elem_type& ug::HCRFVGeometry< TElem, TWorldDim >::m_rRefElem private
Reference Element.
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const local_shape_fct_set_type& ug::HCRFVGeometry< TElem, TWorldDim >::m_rTrialSpace private
Shape function set.
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> CONSTRAINED_DOF ug::HCRFVGeometry< TElem, TWorldDim >::m_vCD[maxNumSCV] private
constrained Dofs
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::print(), and ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::HCRFVGeometry< TElem, TWorldDim >::m_vCo[numMaxCo] protected
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::HCRFVGeometry< TElem, TWorldDim >::m_vGlobSCVF_IP[maxNumSCVF] protected
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> MathVector<worldDim> ug::HCRFVGeometry< TElem, TWorldDim >::m_vGlobUnkCoords[maxNumSCV] protected
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
template<typename TElem , int TWorldDim> MathVector<dim> ug::HCRFVGeometry< TElem, TWorldDim >::m_vLocSCVF_IP[maxNumSCVF] protected
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> MathVector<dim> ug::HCRFVGeometry< TElem, TWorldDim >::m_vLocUnkCoords[maxNumSCV] protected
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> SCV ug::HCRFVGeometry< TElem, TWorldDim >::m_vSCV[maxNumSCV] private
SubControlVolumes.
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::print(), ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> SCVF ug::HCRFVGeometry< TElem, TWorldDim >::m_vSCVF[maxNumSCVF] private
SubControlVolumeFaces.
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::print(), ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const size_t ug::HCRFVGeometry< TElem, TWorldDim >::maxNumSCV = traits::maxNumSCV static
template<typename TElem , int TWorldDim> const size_t ug::HCRFVGeometry< TElem, TWorldDim >::maxNumSCVF = traits::maxNumSCVF static
template<typename TElem , int TWorldDim> const size_t ug::HCRFVGeometry< TElem, TWorldDim >::nip = 1 static
number of integration points
template<typename TElem , int TWorldDim> const size_t ug::HCRFVGeometry< TElem, TWorldDim >::nsh = local_shape_fct_set_type::nsh static
number of shape functions
template<typename TElem , int TWorldDim> size_t ug::HCRFVGeometry< TElem, TWorldDim >::numConstrainedDofs private
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::print(), ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> size_t ug::HCRFVGeometry< TElem, TWorldDim >::numDofs private
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const size_t ug::HCRFVGeometry< TElem, TWorldDim >::numMaxCo = 8 static protected
template<typename TElem , int TWorldDim> const size_t ug::HCRFVGeometry< TElem, TWorldDim >::numNaturalSCV = nsh static
number of SubControlVolumes
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const size_t ug::HCRFVGeometry< TElem, TWorldDim >::numNaturalSCVF = ref_elem_type::numEdges static
number of SubControlVolumeFaces
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> size_t ug::HCRFVGeometry< TElem, TWorldDim >::numSCV private
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::print(), ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> size_t ug::HCRFVGeometry< TElem, TWorldDim >::numSCVF private
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::print(), ug::HCRFVGeometry< TElem, TWorldDim >::update(), and ug::HCRFVGeometry< TElem, TWorldDim >::update_local_data().
template<typename TElem , int TWorldDim> const int ug::HCRFVGeometry< TElem, TWorldDim >::order = 1 static
order
template<typename TElem , int TWorldDim> const bool ug::HCRFVGeometry< TElem, TWorldDim >::staticLocalData = true static
flag indicating if local data may change
template<typename TElem , int TWorldDim> const bool ug::HCRFVGeometry< TElem, TWorldDim >::usesHangingNodes = true static
Hanging node flag: this geometry supports hanging nodes.
template<typename TElem , int TWorldDim> const int ug::HCRFVGeometry< TElem, TWorldDim >::worldDim = TWorldDim static
dimension of world
Referenced by ug::HCRFVGeometry< TElem, TWorldDim >::update().
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/hfvcr_geom.h
ugbase/lib_disc/spatial_disc/disc_util/hfvcr_geom.cpp