ug4: ug::ScalarSubVectorAdapter< InVT, ST > Class Template Reference
ug::ScalarSubVectorAdapter< InVT, ST > Class Template Reference
#include <scalar_subvector_adapter.hh>
Public Types
typedef InVT encapsulated_vector_type
typedef ST::vector_type::value_type value_type
Public Member Functions
value_type & operator[] (size_t i)
ScalarSubVectorAdapter< CPUAlgebra::vector_type, CPUAlgebra >::value_type & operator[] (size_t i)
ScalarSubVectorAdapter< ParallelVector< CPUAlgebra::vector_type >, CPUAlgebra >::value_type & operator[] (size_t i)
const value_type & operator[] (size_t i) const
void print (const char *const text=NULL) const
void reserve (size_t newCapacity, bool bCopyValues=true)
void resize (size_t newSize, bool bCopyValues=true)
ScalarSubVectorAdapter (encapsulated_vector_type &vec, size_t alpha)
void set_random (double from, double to)
size_t size () const
Static Public Attributes
static const int blockSize = block_traits<typename InVT::value_type>::static_size
Private Attributes
const size_t m_alpha
encapsulated_vector_type & m_src
Member Typedef Documentation
encapsulated_vector_type
template<class InVT , class ST = CPUAlgebra::vector_type> typedef InVT ug::ScalarSubVectorAdapter< InVT, ST >::encapsulated_vector_type
value_type
template<class InVT , class ST = CPUAlgebra::vector_type> typedef ST::vector_type::value_type ug::ScalarSubVectorAdapter< InVT, ST >::value_type
Constructor & Destructor Documentation
ScalarSubVectorAdapter()
template<class InVT , class ST = CPUAlgebra::vector_type> ug::ScalarSubVectorAdapter< InVT, ST >::ScalarSubVectorAdapter (encapsulated_vector_type & vec, size_t alpha) inline
Member Function Documentation
operator[]() [1/4]
template<class InVT , class ST = CPUAlgebra::vector_type> value_type& ug::ScalarSubVectorAdapter< InVT, ST >::operator[] (size_t i) inline
References ug::BlockRef(), ug::ScalarSubVectorAdapter< InVT, ST >::m_alpha, and ug::ScalarSubVectorAdapter< InVT, ST >::m_src.
operator[]() [2/4]
ScalarSubVectorAdapter< CPUAlgebra::vector_type, CPUAlgebra >::value_type & ug::ScalarSubVectorAdapter< CPUAlgebra::vector_type, CPUAlgebra >::operator[] (size_t i) inline
operator[]() [3/4]
ScalarSubVectorAdapter< ParallelVector< CPUAlgebra::vector_type >, CPUAlgebra >::value_type & ug::ScalarSubVectorAdapter< ParallelVector< CPUAlgebra::vector_type >, CPUAlgebra >::operator[] (size_t i) inline
operator[]() [4/4]
template<class InVT , class ST = CPUAlgebra::vector_type> const value_type& ug::ScalarSubVectorAdapter< InVT, ST >::operator[] (size_t i) const inline
References ug::BlockRef(), ug::ScalarSubVectorAdapter< InVT, ST >::m_alpha, and ug::ScalarSubVectorAdapter< InVT, ST >::m_src.
print()
template<class InVT , class ST = CPUAlgebra::vector_type> void ug::ScalarSubVectorAdapter< InVT, ST >::print (const char *const text = NULL) const inline
References ug::ScalarSubVectorAdapter< InVT, ST >::m_src.
reserve()
template<class InVT , class ST = CPUAlgebra::vector_type> void ug::ScalarSubVectorAdapter< InVT, ST >::reserve (size_t newCapacity, bool bCopyValues = true) inline
References ug::ScalarSubVectorAdapter< InVT, ST >::m_src.
resize()
template<class InVT , class ST = CPUAlgebra::vector_type> void ug::ScalarSubVectorAdapter< InVT, ST >::resize (size_t newSize, bool bCopyValues = true) inline
References ug::ScalarSubVectorAdapter< InVT, ST >::m_src.
set_random()
template<class InVT , class ST = CPUAlgebra::vector_type> void ug::ScalarSubVectorAdapter< InVT, ST >::set_random (double from, double to) inline
References ug::BlockRef(), ug::ScalarSubVectorAdapter< InVT, ST >::m_alpha, ug::ScalarSubVectorAdapter< InVT, ST >::m_src, ug::ScalarSubVectorAdapter< InVT, ST >::size(), and ug::urand().
size()
template<class InVT , class ST = CPUAlgebra::vector_type> size_t ug::ScalarSubVectorAdapter< InVT, ST >::size () const inline
References ug::ScalarSubVectorAdapter< InVT, ST >::m_src.
Referenced by ug::ScalarSubVectorAdapter< InVT, ST >::set_random().
Member Data Documentation
blockSize
template<class InVT , class ST = CPUAlgebra::vector_type> const int ug::ScalarSubVectorAdapter< InVT, ST >::blockSize = block_traits<typename InVT::value_type>::static_size static
m_alpha
template<class InVT , class ST = CPUAlgebra::vector_type> const size_t ug::ScalarSubVectorAdapter< InVT, ST >::m_alpha private
Referenced by ug::ScalarSubVectorAdapter< InVT, ST >::operator[](), and ug::ScalarSubVectorAdapter< InVT, ST >::set_random().
m_src
template<class InVT , class ST = CPUAlgebra::vector_type> encapsulated_vector_type& ug::ScalarSubVectorAdapter< InVT, ST >::m_src private
Referenced by ug::ScalarSubVectorAdapter< InVT, ST >::operator[](), ug::ScalarSubVectorAdapter< InVT, ST >::print(), ug::ScalarSubVectorAdapter< InVT, ST >::reserve(), ug::ScalarSubVectorAdapter< InVT, ST >::resize(), ug::ScalarSubVectorAdapter< InVT, ST >::set_random(), and ug::ScalarSubVectorAdapter< InVT, ST >::size().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/adapter/scalar_subvector_adapter.hh