ug4: ug::EquidistantLagrange1D Class Reference
ug::EquidistantLagrange1D Class Reference
#include <lagrange1d.h>
Public Member Functions
EquidistantLagrange1D (const size_t i, const size_t degree)
Public Member Functions inherited from ug::Polynomial1D
size_t degree () const
Polynomial1D derivative () const
returns the derivative of this polynomial as a polynomial
Polynomial1D & operator*= (const Polynomial1D &v)
multiply by a polynomial
Polynomial1D & operator*= (number scale)
multiply by a scalar
Polynomial1D (const std::vector< number > &a)
Constructor passing coefficients for the polynomial.
Polynomial1D (size_t degree=0)
Constructor producing zero polynomial of degree 'degree'.
number value (const number x) const
evaluate the value of the polynom at x
Static Public Member Functions
static number position (const size_t i, const size_t degree)
returns the position of the i'th interpolation point
Protected Member Functions
void compute_coeffs (const int i, const int p)
computes the coefficients for passed interpolation points
Protected Member Functions inherited from ug::Polynomial1D
void set_coefficients (const std::vector< number > &a)
Detailed Description
EquiDistant Lagrange Function
Constructor & Destructor Documentation
EquidistantLagrange1D()
ug::EquidistantLagrange1D::EquidistantLagrange1D (const size_t i, const size_t degree) inline
creates a lagrange polynomial with equidistant interpolation points
Parameters
[in] i number of interpolation point, where polynom is 1
[in] degree degree of polynom
References compute_coeffs(), ug::Polynomial1D::degree(), and UG_ASSERT.
Member Function Documentation
compute_coeffs()
void ug::EquidistantLagrange1D::compute_coeffs (const int i, const int p) inline protected
computes the coefficients for passed interpolation points
References p, and ug::Polynomial1D::set_coefficients().
Referenced by EquidistantLagrange1D().
position()
static number ug::EquidistantLagrange1D::position (const size_t i, const size_t degree) inline static
returns the position of the i'th interpolation point
References ug::Polynomial1D::degree(), and UG_ASSERT.
Referenced by ug::LagrangeLSFS< ReferenceEdge, TOrder >::position(), ug::FlexLagrangeLSFS< ReferenceEdge >::position(), ug::LagrangeLSFS< ReferenceQuadrilateral, TOrder >::position(), ug::FlexLagrangeLSFS< ReferenceQuadrilateral >::position(), ug::LagrangeLSFS< ReferencePrism, TOrder >::position(), ug::FlexLagrangeLSFS< ReferencePrism >::position(), ug::LagrangeLSFS< ReferencePyramid, TOrder >::position(), ug::LagrangeLSFS< ReferenceHexahedron, TOrder >::position(), ug::FlexLagrangeLSFS< ReferenceHexahedron >::position(), and ug::LagrangeLSFS< ReferenceOctahedron, TOrder >::position().
The documentation for this class was generated from the following file:
ugbase/lib_disc/local_finite_element/common/lagrange1d.h