ug4: ug::IDomainErrorIndicator< TAlgebra > Class Template Reference
ug::IDomainErrorIndicator< TAlgebra > Class Template Reference abstract
Interface for an object that can estimate the (global) error.
#include <domain_disc_interface.h>
Public Types
typedef TAlgebra::vector_type vector_type
Type of algebra vector.
Public Member Functions
virtual void calc_error (const vector_type &u, const GridLevel &gl, vector_type *u_vtk=NULL)=0
computes the error estimator
virtual void calc_error (const vector_type &u, ConstSmartPtr< DoFDistribution > dd, vector_type *u_vtk=NULL)=0
virtual void calc_error (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd, std::vector< number > vScaleMass, std::vector< number > vScaleStiff, vector_type *u_vtk)=0
virtual void calc_error (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, std::vector< number > vScaleMass, std::vector< number > vScaleStiff, const GridLevel &gl, vector_type *u_vtk)=0
virtual void invalidate_error ()=0
marks error indicators as invalid
virtual bool is_error_valid ()=0
returns whether current error values are valid
virtual ~IDomainErrorIndicator ()
Detailed Description
template<typename TAlgebra>
class ug::IDomainErrorIndicator< TAlgebra >
Interface for an object that can estimate the (global) error.
Member Typedef Documentation
vector_type
template<typename TAlgebra> typedef TAlgebra::vector_type ug::IDomainErrorIndicator< TAlgebra >::vector_type
Type of algebra vector.
Constructor & Destructor Documentation
~IDomainErrorIndicator()
template<typename TAlgebra> virtual ug::IDomainErrorIndicator< TAlgebra >::~IDomainErrorIndicator () inline virtual
Member Function Documentation
calc_error() [1/4]
template<typename TAlgebra> virtual void ug::IDomainErrorIndicator< TAlgebra >::calc_error (const vector_type & u, const GridLevel & gl, vector_type * u_vtk = NULL) pure virtual
computes the error estimator
Computes the error estimator.
Parameters
[in] u vector of the solution to estimate the error for
[in] dd DoF Distribution
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, ug::CPUAlgebra, StdGlobAssembler< TDomain, ug::CPUAlgebra > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainErrorIndicator< ug::CPUAlgebra >::~IDomainErrorIndicator().
calc_error() [2/4]
template<typename TAlgebra> virtual void ug::IDomainErrorIndicator< TAlgebra >::calc_error (const vector_type & u, ConstSmartPtr< DoFDistribution > dd, vector_type * u_vtk = NULL) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, ug::CPUAlgebra, StdGlobAssembler< TDomain, ug::CPUAlgebra > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
calc_error() [3/4]
template<typename TAlgebra> virtual void ug::IDomainErrorIndicator< TAlgebra >::calc_error (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd, std::vector< number > vScaleMass, std::vector< number > vScaleStiff, vector_type * u_vtk) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, ug::CPUAlgebra, StdGlobAssembler< TDomain, ug::CPUAlgebra > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
calc_error() [4/4]
template<typename TAlgebra> virtual void ug::IDomainErrorIndicator< TAlgebra >::calc_error (ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, std::vector< number > vScaleMass, std::vector< number > vScaleStiff, const GridLevel & gl, vector_type * u_vtk) pure virtual
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, ug::CPUAlgebra, StdGlobAssembler< TDomain, ug::CPUAlgebra > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
invalidate_error()
template<typename TAlgebra> virtual void ug::IDomainErrorIndicator< TAlgebra >::invalidate_error () pure virtual
marks error indicators as invalid
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, ug::CPUAlgebra, StdGlobAssembler< TDomain, ug::CPUAlgebra > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainErrorIndicator< ug::CPUAlgebra >::~IDomainErrorIndicator().
is_error_valid()
template<typename TAlgebra> virtual bool ug::IDomainErrorIndicator< TAlgebra >::is_error_valid () pure virtual
returns whether current error values are valid
Implemented in ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >, ug::DomainDiscretizationBase< TDomain, ug::CPUAlgebra, StdGlobAssembler< TDomain, ug::CPUAlgebra > >, and ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >.
Referenced by ug::IDomainErrorIndicator< ug::CPUAlgebra >::~IDomainErrorIndicator().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/domain_disc_interface.h