ug4: ug::LocalVector Class Reference
ug::LocalVector Class Reference
#include <local_algebra.h>
Public Types
typedef LocalVector this_type
own type
typedef number value_type
Type to store DoF values.
Public Member Functions
void access_all ()
access all functions
void access_by_map (const FunctionIndexMapping &funcMap)
access only part of the functions using mapping (restrict functions)
const LocalIndices & get_indices () const
get current local indices
const LFEID & local_finite_element_id (size_t fct) const
returns the local finite element id of a function
LocalVector ()
default Constructor
LocalVector (const LocalIndices &ind)
Constructor.
size_t num_all_dof (size_t fct) const
returns the number of dofs for a function (unrestricted functions)
size_t num_all_fct () const
returns the number of all functions
size_t num_dof (size_t fct) const
returns the number of dofs for the currently accessible function
size_t num_fct () const
returns the number of currently accessible functions
number & operator() (size_t fct, size_t dof)
access to dof of currently accessible function fct
number operator() (size_t fct, size_t dof) const
const access to dof of currently accessible function fct
this_type & operator* (number val)
multiply all components of the vector
this_type & operator*= (number val)
multiply all components of the vector
this_type & operator+= (const this_type &rhs)
add a local vector
this_type & operator-= (const this_type &rhs)
subtract a local vector
this_type & operator= (number val)
set all components of the vector
void resize (const LocalIndices &ind)
resize for current local indices
this_type & scale_append (number s, const this_type &rhs)
add a scaled vector
number & value (size_t fct, size_t dof)
access to dof of a fct (unrestricted functions)
const number & value (size_t fct, size_t dof) const
const access to dof of a fct (unrestricted functions)
Protected Member Functions
void check_all_dof (size_t fct, size_t dof) const
checks correct dof index in debug mode
void check_all_fct (size_t fct) const
checks correct fct index in debug mode
void check_dof (size_t fct, size_t dof) const
checks correct dof index in debug mode
void check_fct (size_t fct) const
checks correct fct index in debug mode
Protected Attributes
const FunctionIndexMapping * m_pFuncMap
Access Mapping.
const LocalIndices * m_pIndex
Indices.
std::vector< std::vector< value_type > > m_vvValue
Entries (fct, dof)
std::vector< value_type * > m_vvValueAcc
Entries (fct, dof)
Member Typedef Documentation
this_type
typedef LocalVector ug::LocalVector::this_type
own type
value_type
typedef number ug::LocalVector::value_type
Type to store DoF values.
Constructor & Destructor Documentation
LocalVector() [1/2]
ug::LocalVector::LocalVector () inline
default Constructor
References m_vvValue.
LocalVector() [2/2]
ug::LocalVector::LocalVector (const LocalIndices & ind) inline
Constructor.
References resize().
Member Function Documentation
access_all()
void ug::LocalVector::access_all () inline
access all functions
References m_pFuncMap, m_pIndex, m_vvValue, m_vvValueAcc, and ug::LocalIndices::num_fct().
Referenced by resize().
access_by_map()
void ug::LocalVector::access_by_map (const FunctionIndexMapping & funcMap) inline
access only part of the functions using mapping (restrict functions)
References m_pFuncMap, m_vvValue, m_vvValueAcc, and ug::FunctionIndexMapping::num_fct().
Referenced by ug::LocalVectorTimeSeries::access_by_map(), ug::DataImport< number, dim >::compute_lin_defect(), ug::IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::do_add_def_A_elem(), ug::IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::do_add_def_A_expl_elem(), ug::IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::do_add_def_M_elem(), ug::IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::do_add_jac_A_elem(), ug::IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::do_add_jac_M_elem(), ug::IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::do_add_rhs_elem(), ug::IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::do_compute_err_est_A_elem(), ug::IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::do_compute_err_est_M_elem(), ug::IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::do_fsh_timestep_elem(), ug::IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::do_prep_elem(), ug::IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::do_prep_err_est_elem(), ug::IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::do_prep_timestep_elem(), ug::ValueDataExport< dim >::eval_and_deriv(), ug::GradientDataExport< dim >::eval_and_deriv(), ug::VectorDataExport< dim >::eval_and_deriv(), ug::DataExport< number, dim >::eval_and_deriv(), ug::DataEvaluator< TDomain >::prepare_elem(), and ug::DataEvaluatorBase< TDomain, IElemError< TDomain > >::prepare_err_est_elem().
check_all_dof()
void ug::LocalVector::check_all_dof (size_t fct, size_t dof) const inline protected
checks correct dof index in debug mode
References check_all_fct(), num_all_dof(), and UG_LOCALALGEBRA_ASSERT.
Referenced by value().
check_all_fct()
void ug::LocalVector::check_all_fct (size_t fct) const inline protected
checks correct fct index in debug mode
References num_all_fct(), and UG_LOCALALGEBRA_ASSERT.
Referenced by check_all_dof(), and num_all_dof().
check_dof()
void ug::LocalVector::check_dof (size_t fct, size_t dof) const inline protected
checks correct dof index in debug mode
References check_fct(), num_dof(), and UG_LOCALALGEBRA_ASSERT.
Referenced by operator()().
check_fct()
void ug::LocalVector::check_fct (size_t fct) const inline protected
checks correct fct index in debug mode
References num_fct(), and UG_LOCALALGEBRA_ASSERT.
Referenced by check_dof(), local_finite_element_id(), and num_dof().
get_indices()
const LocalIndices& ug::LocalVector::get_indices () const inline
get current local indices
References m_pIndex.
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_vec_to_global(), ug::AddLocalVector(), and ug::GetLocalVector().
local_finite_element_id()
const LFEID& ug::LocalVector::local_finite_element_id (size_t fct) const inline
returns the local finite element id of a function
References check_fct(), ug::LocalIndices::local_finite_element_id(), m_pFuncMap, m_pIndex, and UG_ASSERT.
num_all_dof()
size_t ug::LocalVector::num_all_dof (size_t fct) const inline
returns the number of dofs for a function (unrestricted functions)
References check_all_fct(), and m_vvValue.
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_vec_to_global(), ug::AddLocalVector(), check_all_dof(), ug::GetLocalVector(), and ug::NLGaussSeidelSolver< TDomain, TAlgebra >::prepare().
num_all_fct()
size_t ug::LocalVector::num_all_fct () const inline
returns the number of all functions
References m_vvValue.
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_vec_to_global(), ug::AddLocalVector(), check_all_fct(), ug::GetLocalVector(), and ug::NLGaussSeidelSolver< TDomain, TAlgebra >::prepare().
num_dof()
size_t ug::LocalVector::num_dof (size_t fct) const inline
returns the number of dofs for the currently accessible function
References check_fct(), m_pFuncMap, and m_vvValue.
Referenced by check_dof(), and ug::operator<<().
num_fct()
size_t ug::LocalVector::num_fct () const inline
returns the number of currently accessible functions
References m_pFuncMap, m_vvValue, and ug::FunctionIndexMapping::num_fct().
Referenced by ug::FV1InnerBoundaryElemDisc< TDomain >::add_def_A_elem(), ug::FV1InnerBoundaryElemDisc< TDomain >::add_jac_A_elem(), check_fct(), ug::FV1InnerBoundaryElemDisc< TDomain >::compute_err_est_A_elem(), and ug::operator<<().
operator()() [1/2]
number& ug::LocalVector::operator() (size_t fct, size_t dof) inline
access to dof of currently accessible function fct
References check_dof(), and m_vvValueAcc.
operator()() [2/2]
number ug::LocalVector::operator() (size_t fct, size_t dof) const inline
const access to dof of currently accessible function fct
References check_dof(), and m_vvValueAcc.
operator*()
this_type& ug::LocalVector::operator* (number val) inline
multiply all components of the vector
References operator*=().
operator*=()
this_type& ug::LocalVector::operator*= (number val) inline
multiply all components of the vector
References m_vvValue.
Referenced by operator*().
operator+=()
this_type& ug::LocalVector::operator+= (const this_type & rhs) inline
add a local vector
References m_pIndex, m_vvValue, and UG_LOCALALGEBRA_ASSERT.
operator-=()
this_type& ug::LocalVector::operator-= (const this_type & rhs) inline
subtract a local vector
References m_pIndex, m_vvValue, and UG_LOCALALGEBRA_ASSERT.
operator=()
this_type& ug::LocalVector::operator= (number val) inline
set all components of the vector
References m_vvValue.
resize()
void ug::LocalVector::resize (const LocalIndices & ind) inline
resize for current local indices
References access_all(), m_pIndex, m_vvValue, m_vvValueAcc, ug::LocalIndices::num_dof(), and ug::LocalIndices::num_fct().
Referenced by ug::ActiveSet< TDomain, TAlgebra >::active_index_elem(), ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::AssembleDefect(), ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::AssembleErrorEstimator(), ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::AssembleJacobian(), ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::AssembleLinear(), ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::AssembleMassMatrix(), ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::AssembleRhs(), ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::AssembleStiffnessMatrix(), ug::DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::calc_error(), ug::ActiveSet< TDomain, TAlgebra >::check_conv_elem(), ug::UserDataIntegrand< TData, TGridFunction >::evaluate(), ug::UserDataIntegrandSq< TData, TGridFunction >::evaluate(), ug::UserDataDistIntegrandSq< TData, TGridFunction >::evaluate(), ug::H1SemiIntegrand< TGridFunction >::evaluate(), ug::H1SemiDistIntegrand< TGridFunction >::evaluate(), ug::H1EnergyIntegrand< TGridFunction >::evaluate(), ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::FinishTimestepElem(), LocalVector(), ug::NLGaussSeidelSolver< TDomain, TAlgebra >::prepare(), ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::PrepareTimestepElem(), ug::VTKOutput< TDim >::write_cell_data_elementwise(), and ug::VTKOutput< TDim >::write_nodal_data_elementwise().
scale_append()
this_type& ug::LocalVector::scale_append (number s, const this_type & rhs) inline
add a scaled vector
References m_pIndex, m_vvValue, and UG_LOCALALGEBRA_ASSERT.
Referenced by ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::AssembleDefect(), ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::AssembleLinear(), and ug::StdGlobAssembler< TDomain, ug::CPUAlgebra >::AssembleRhs().
value() [1/2]
number& ug::LocalVector::value (size_t fct, size_t dof) inline
access to dof of a fct (unrestricted functions)
References check_all_dof(), and m_vvValue.
Referenced by ug::LocalToGlobalMapperNLGS< TAlgebra >::add_local_vec_to_global(), ug::AddLocalVector(), and ug::GetLocalVector().
value() [2/2]
const number& ug::LocalVector::value (size_t fct, size_t dof) const inline
const access to dof of a fct (unrestricted functions)
References check_all_dof(), and m_vvValue.
Member Data Documentation
m_pFuncMap
const FunctionIndexMapping* ug::LocalVector::m_pFuncMap protected
Access Mapping.
Referenced by access_all(), access_by_map(), local_finite_element_id(), num_dof(), and num_fct().
m_pIndex
const LocalIndices* ug::LocalVector::m_pIndex protected
Indices.
Referenced by access_all(), get_indices(), local_finite_element_id(), operator+=(), operator-=(), resize(), and scale_append().
m_vvValue
std::vector<std::vector<value_type> > ug::LocalVector::m_vvValue protected
Entries (fct, dof)
Referenced by access_all(), access_by_map(), LocalVector(), num_all_dof(), num_all_fct(), num_dof(), num_fct(), operator*=(), operator+=(), operator-=(), operator=(), resize(), scale_append(), and value().
m_vvValueAcc
std::vector<value_type*> ug::LocalVector::m_vvValueAcc protected
Entries (fct, dof)
Referenced by access_all(), access_by_map(), operator()(), and resize().
The documentation for this class was generated from the following file:
ugbase/lib_disc/common/local_algebra.h