ug4: ug::IIdentifier Class Reference
ug::IIdentifier Class Reference abstract
Interface to match periodic geometric elements.
#include <periodic_boundary_manager.h>
Public Member Functions
virtual bool match (Vertex *, Vertex *)=0
virtual bool match (Edge *, Edge *)=0
virtual bool match (Face *, Face *)=0
virtual bool match (Volume *, Volume *)
virtual ~IIdentifier ()
Detailed Description
Interface to match periodic geometric elements.
Constructor & Destructor Documentation
~IIdentifier()
virtual ug::IIdentifier::~IIdentifier () inline virtual
References match().
Member Function Documentation
match() [1/4]
virtual bool ug::IIdentifier::match (Vertex * , Vertex *) pure virtual
Implemented in ug::ParallelShiftIdentifier< TPosAA >.
Referenced by ug::PeriodicBoundaryManager::identify(), and ~IIdentifier().
match() [2/4]
virtual bool ug::IIdentifier::match (Edge * , Edge *) pure virtual
Implemented in ug::ParallelShiftIdentifier< TPosAA >.
match() [3/4]
virtual bool ug::IIdentifier::match (Face * , Face *) pure virtual
Implemented in ug::ParallelShiftIdentifier< TPosAA >.
match() [4/4]
virtual bool ug::IIdentifier::match (Volume * , Volume *) inline virtual
References UG_THROW.
The documentation for this class was generated from the following file:
ugbase/lib_grid/tools/periodic_boundary_manager.h