ug4: ug::ReferenceMapping< ReferencePrism, TWorldDim > Class Template Reference
ug::ReferenceMapping< ReferencePrism, TWorldDim > Class Template Reference
#include <reference_mapping.h>
Public Types
typedef BaseReferenceMapping< ReferencePrism::dim, TWorldDim, false, ReferenceMapping< ReferencePrism, TWorldDim > > base_type
Public Member Functions
void jacobian_transposed (MathMatrix< dim, worldDim > &JT, const MathVector< dim > &locPos) const
returns transposed of jacobian
void local_to_global (MathVector< worldDim > &globPos, const MathVector< dim > &locPos) const
map local coordinate to global coordinate
ReferenceMapping ()
Default Constructor.
void update (const std::vector< MathVector< worldDim > > &vCornerCoord)
refresh mapping for new set of corners
void update (const MathVector< worldDim > *vCornerCoord)
update the mapping for a new set of corners
ReferenceMapping (const MathVector< worldDim > *vCornerCoord)
ReferenceMapping (const std::vector< MathVector< worldDim > > &vCornerCoord)
Public Member Functions inherited from ug::BaseReferenceMapping< ReferencePrism::dim, TWorldDim, false, ReferenceMapping< ReferencePrism, TWorldDim > >
void global_to_local (MathVector< dim > &locPos, const MathVector< worldDim > &globPos, const size_t maxIter=1000, const number tol=1e-10) const
map global coordinate to local coordinate
void global_to_local (MathVector< dim > *vLocPos, const MathVector< worldDim > *vGlobPos, size_t n, const size_t maxIter=1000, const number tol=1e-10) const
map global coordinate to local coordinate for n local positions
void global_to_local (std::vector< MathVector< dim > > &vLocPos, const std::vector< MathVector< worldDim > > &vGlobPos, const size_t maxIter=1000, const number tol=1e-10) const
map global coordinate to local coordinate for a vector of local positions
bool is_linear () const
returns if mapping is affine
void jacobian (MathMatrix< worldDim, dim > &J, const MathVector< dim > &locPos) const
returns jacobian
void jacobian (MathMatrix< worldDim, dim > *vJ, const MathVector< dim > *vLocPos, size_t n) const
returns jacobian for n local positions
void jacobian (std::vector< MathMatrix< worldDim, dim > > &vJ, const std::vector< MathVector< dim > > &vLocPos) const
returns jacobian for a vector of local positions
void jacobian_transposed (MathMatrix< dim, worldDim > *vJT, const MathVector< dim > *vLocPos, size_t n) const
returns transposed of jacobian for n local positions
void jacobian_transposed (std::vector< MathMatrix< dim, worldDim > > &vJT, const std::vector< MathVector< dim > > &vLocPos) const
returns transposed of jacobian for a vector of positions
number jacobian_transposed_inverse (MathMatrix< worldDim, dim > &JTInv, const MathVector< dim > &locPos) const
returns transposed of the inverse of the jacobian
void jacobian_transposed_inverse (MathMatrix< worldDim, dim > *vJTInv, number *vDet, const MathVector< dim > *vLocPos, size_t n) const
returns transposed of the inverse of the jacobian for n local positions
void jacobian_transposed_inverse (MathMatrix< worldDim, dim > *vJTInv, const MathVector< dim > *vLocPos, size_t n) const
returns transposed of the inverse of the jacobian for n local positions
void jacobian_transposed_inverse (std::vector< MathMatrix< worldDim, dim > > &vJTInv, std::vector< number > &vDet, const std::vector< MathVector< dim > > &vLocPos) const
returns transposed of the inverse of the jacobian for a vector of positions
void jacobian_transposed_inverse (std::vector< MathMatrix< worldDim, dim > > &vJTInv, const std::vector< MathVector< dim > > &vLocPos) const
returns transposed of the inverse of the jacobian for a vector of positions
void local_to_global (MathVector< worldDim > *vGlobPos, const MathVector< dim > *vLocPos, size_t n) const
map local coordinate to global coordinate for n local positions
void local_to_global (std::vector< MathVector< worldDim > > &vGlobPos, const std::vector< MathVector< dim > > &vLocPos) const
map local coordinate to global coordinate for a vector of local positions
number sqrt_gram_det (const MathVector< dim > &locPos) const
returns the determinate of the jacobian
void sqrt_gram_det (number *vDet, const MathVector< dim > *vLocPos, size_t n) const
returns the determinate of the jacobian for n local positions
void sqrt_gram_det (std::vector< number > &vDet, const std::vector< MathVector< dim > > &vLocPos) const
returns the determinate of the jacobian for a vector of local positions
Static Public Attributes
static const int dim = ReferencePrism::dim
reference dimension
static const bool isLinear = false
flag if mapping is linear (i.e. Jacobian does not depend on x)
static const int worldDim = TWorldDim
world dimension
Private Attributes
MathVector< worldDim > x [ReferencePrism::numCorners]
Additional Inherited Members
Protected Member Functions inherited from ug::BaseReferenceMapping< ReferencePrism::dim, TWorldDim, false, ReferenceMapping< ReferencePrism, TWorldDim > >
ReferenceMapping< ReferencePrism, TWorldDim > & getImpl ()
access to implementation
const ReferenceMapping< ReferencePrism, TWorldDim > & getImpl () const
const access to implementation
Member Typedef Documentation
template<int TWorldDim> typedef BaseReferenceMapping<ReferencePrism::dim, TWorldDim, false, ReferenceMapping<ReferencePrism, TWorldDim> > ug::ReferenceMapping< ReferencePrism, TWorldDim >::base_type
Constructor & Destructor Documentation
template<int TWorldDim> ug::ReferenceMapping< ReferencePrism, TWorldDim >::ReferenceMapping () inline
Default Constructor.
template<int TWorldDim> ug::ReferenceMapping< ReferencePrism, TWorldDim >::ReferenceMapping (const MathVector< worldDim > * vCornerCoord) inline
Constructor setting the corners
References ug::ReferenceMapping< TRefElem, TWorldDim >::update().
template<int TWorldDim> ug::ReferenceMapping< ReferencePrism, TWorldDim >::ReferenceMapping (const std::vector< MathVector< worldDim > > & vCornerCoord) inline
Constructor setting the corners
References ug::ReferenceMapping< TRefElem, TWorldDim >::update().
Member Function Documentation
template<int TWorldDim> void ug::ReferenceMapping< ReferencePrism, TWorldDim >::jacobian_transposed (MathMatrix< dim, worldDim > & JT, const MathVector< dim > & locPos) const inline
returns transposed of jacobian
References ug::ReferenceMapping< TRefElem, TWorldDim >::worldDim.
template<int TWorldDim> void ug::ReferenceMapping< ReferencePrism, TWorldDim >::local_to_global (MathVector< worldDim > & globPos, const MathVector< dim > & locPos) const inline
map local coordinate to global coordinate
References ug::ReferenceMapping< TRefElem, TWorldDim >::worldDim.
template<int TWorldDim> void ug::ReferenceMapping< ReferencePrism, TWorldDim >::update (const std::vector< MathVector< worldDim > > & vCornerCoord) inline
refresh mapping for new set of corners
References ug::ReferencePrism::numCorners, UG_ASSERT, and ug::ReferenceMapping< TRefElem, TWorldDim >::update().
template<int TWorldDim> void ug::ReferenceMapping< ReferencePrism, TWorldDim >::update (const MathVector< worldDim > * vCornerCoord) inline
update the mapping for a new set of corners
References ug::ReferencePrism::numCorners.
Member Data Documentation
template<int TWorldDim> const int ug::ReferenceMapping< ReferencePrism, TWorldDim >::dim = ReferencePrism::dim static
reference dimension
template<int TWorldDim> const bool ug::ReferenceMapping< ReferencePrism, TWorldDim >::isLinear = false static
flag if mapping is linear (i.e. Jacobian does not depend on x)
template<int TWorldDim> const int ug::ReferenceMapping< ReferencePrism, TWorldDim >::worldDim = TWorldDim static
world dimension
template<int TWorldDim> MathVector<worldDim> ug::ReferenceMapping< ReferencePrism, TWorldDim >::x[ReferencePrism::numCorners] private
The documentation for this class was generated from the following file:
ugbase/lib_disc/reference_element/reference_mapping.h