ug4: ug::DimFEGeometry< TWorldDim, TRefDim > Class Template Reference
ug::DimFEGeometry< TWorldDim, TRefDim > Class Template Reference
#include <fe_geom.h>
Classes
class BF
boundary face
Public Member Functions
void add_boundary_subset (int subsetIndex)
add subset that is interpreted as boundary subset.
const BF & bf (int si, size_t i) const
returns the boundary face i for subsetIndex
const std::vector< BF > & bf (int si) const
returns reference to vector of boundary faces for subsetIndex
void clear_boundary_subsets ()
reset all boundary subsets
DimFEGeometry ()
default Constructor
DimFEGeometry (size_t order, LFEID lfeid)
Constructor.
DimFEGeometry (ReferenceObjectID roid, size_t order, LFEID lfeid)
Constructor.
const MathVector< worldDim > & global_grad (size_t ip, size_t sh) const
global gradient at ip
const MathVector< worldDim > & global_ip (size_t ip) const
global integration point
const MathVector< worldDim > * global_ips () const
global integration point
const MathVector< dim > & local_grad (size_t ip, size_t sh) const
local gradient at ip
const MathVector< dim > & local_ip (size_t ip) const
local integration point
const MathVector< dim > * local_ips () const
local integration point
size_t num_bf () const
number of all boundary faces
size_t num_bf (int si) const
number of boundary faces on subset 'subsetIndex'
size_t num_boundary_subsets ()
number of registered boundary subsets
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shape functions
void remove_boundary_subset (int subsetIndex)
removes subset that is interpreted as boundary subset.
number shape (size_t ip, size_t sh) const
shape function at ip
void update (GridObject *pElem, const MathVector< worldDim > *vCorner)
update Geometry for corners
void update (GridObject *pElem, const MathVector< worldDim > *vCorner, const LFEID &lfeID, size_t orderQuad)
update Geometry for corners
void update (GridObject *pElem, const MathVector< worldDim > *vCorner, const LFEID &lfeID)
void update_boundary_faces (GridObject *pElem, const MathVector< worldDim > *vCornerCoords, size_t orderQuad, const ISubsetHandler *ish)
update boundary data for given element
void update_local (ReferenceObjectID roid, const LFEID &lfeID, size_t orderQuad)
update Geometry for roid
void update_local (ReferenceObjectID roid, const LFEID &lfeID)
number weight (size_t ip) const
weight for integration point
Static Public Attributes
static const int dim = TRefDim
reference element dimension
static const bool staticLocalData = false
flag indicating if local data may change
static const int worldDim = TWorldDim
world dimension
Protected Attributes
LFEID m_lfeID
current local finite element id
std::map< int, std::vector< BF > > m_mapVectorBF
size_t m_nip
number of integration point
size_t m_nsh
number of shape functions
GridObject * m_pElem
current element
int m_quadOrder
current integration order
ReferenceObjectID m_roid
current reference object id the local values are prepared for
std::vector< number > m_vDetJ
determinant of transformation at ip (size = nip)
std::vector< BF > m_vEmptyVectorBF
std::vector< MathVector< worldDim > > m_vIPGlobal
global integration points (size = nip)
const MathVector< dim > * m_vIPLocal
local quadrature points
std::vector< MathMatrix< worldDim, dim > > m_vJTInv
jacobian of transformation at ip (size = nip)
const number * m_vQuadWeight
local quadrature weights
std::vector< std::vector< MathVector< worldDim > > > m_vvGradGlobal
local gradient evaluated at ip (size = nip x nsh)
std::vector< std::vector< MathVector< dim > > > m_vvGradLocal
global gradient evaluated at ip (size = nip x nsh)
std::vector< std::vector< number > > m_vvShape
shape functions evaluated at ip (size = nip x nsh)
Constructor & Destructor Documentation
template<int TWorldDim, int TRefDim> ug::DimFEGeometry< TWorldDim, TRefDim >::DimFEGeometry ()
default Constructor
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::DimFEGeometry().
template<int TWorldDim, int TRefDim> ug::DimFEGeometry< TWorldDim, TRefDim >::DimFEGeometry (size_t order, LFEID lfeid)
Constructor.
References ug::DimFEGeometry< TWorldDim, TRefDim >::DimFEGeometry().
template<int TWorldDim, int TRefDim> ug::DimFEGeometry< TWorldDim, TRefDim >::DimFEGeometry (ReferenceObjectID roid, size_t order, LFEID lfeid)
Constructor.
References ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
Member Function Documentation
template<int TWorldDim, int TRefDim = TWorldDim> void ug::DimFEGeometry< TWorldDim, TRefDim >::add_boundary_subset (int subsetIndex) inline
add subset that is interpreted as boundary subset.
template<int TWorldDim, int TRefDim = TWorldDim> const BF& ug::DimFEGeometry< TWorldDim, TRefDim >::bf (int si, size_t i) const inline
returns the boundary face i for subsetIndex
References UG_ASSERT, and UG_THROW.
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
template<int TWorldDim, int TRefDim = TWorldDim> const std::vector<BF>& ug::DimFEGeometry< TWorldDim, TRefDim >::bf (int si) const inline
returns reference to vector of boundary faces for subsetIndex
template<int TWorldDim, int TRefDim = TWorldDim> void ug::DimFEGeometry< TWorldDim, TRefDim >::clear_boundary_subsets () inline
reset all boundary subsets
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<worldDim>& ug::DimFEGeometry< TWorldDim, TRefDim >::global_grad (size_t ip, size_t sh) const inline
global gradient at ip
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvGradGlobal, ug::MathVector< N, T >::size(), UG_ASSERT, and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<worldDim>& ug::DimFEGeometry< TWorldDim, TRefDim >::global_ip (size_t ip) const inline
global integration point
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vIPGlobal, ug::MathVector< N, T >::size(), and UG_ASSERT.
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<worldDim>* ug::DimFEGeometry< TWorldDim, TRefDim >::global_ips () const inline
global integration point
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vIPGlobal.
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<dim>& ug::DimFEGeometry< TWorldDim, TRefDim >::local_grad (size_t ip, size_t sh) const inline
local gradient at ip
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvGradLocal, ug::MathVector< N, T >::size(), and UG_ASSERT.
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<dim>& ug::DimFEGeometry< TWorldDim, TRefDim >::local_ip (size_t ip) const inline
local integration point
References UG_ASSERT.
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<dim>* ug::DimFEGeometry< TWorldDim, TRefDim >::local_ips () const inline
local integration point
template<int TWorldDim, int TRefDim = TWorldDim> size_t ug::DimFEGeometry< TWorldDim, TRefDim >::num_bf () const inline
number of all boundary faces
template<int TWorldDim, int TRefDim = TWorldDim> size_t ug::DimFEGeometry< TWorldDim, TRefDim >::num_bf (int si) const inline
number of boundary faces on subset 'subsetIndex'
template<int TWorldDim, int TRefDim = TWorldDim> size_t ug::DimFEGeometry< TWorldDim, TRefDim >::num_boundary_subsets () inline
number of registered boundary subsets
template<int TWorldDim, int TRefDim = TWorldDim> size_t ug::DimFEGeometry< TWorldDim, TRefDim >::num_ip () const inline
number of integration points
template<int TWorldDim, int TRefDim = TWorldDim> size_t ug::DimFEGeometry< TWorldDim, TRefDim >::num_sh () const inline
number of shape functions
template<int TWorldDim, int TRefDim = TWorldDim> void ug::DimFEGeometry< TWorldDim, TRefDim >::remove_boundary_subset (int subsetIndex) inline
removes subset that is interpreted as boundary subset.
template<int TWorldDim, int TRefDim = TWorldDim> number ug::DimFEGeometry< TWorldDim, TRefDim >::shape (size_t ip, size_t sh) const inline
shape function at ip
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvShape, and UG_ASSERT.
template<int TWorldDim, int TRefDim = TWorldDim> void ug::DimFEGeometry< TWorldDim, TRefDim >::update (GridObject * pElem, const MathVector< worldDim > * vCorner) inline
update Geometry for corners
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim> void ug::DimFEGeometry< TWorldDim, TRefDim >::update (GridObject * pElem, const MathVector< worldDim > * vCorner, const LFEID & lfeID, size_t orderQuad)
update Geometry for corners
References ug::DimReferenceMapping< TDim, TWorldDim >::jacobian_transposed_inverse(), ug::DimReferenceMapping< TDim, TWorldDim >::local_to_global(), ug::DimFEGeometry< TWorldDim, TRefDim >::m_lfeID, ug::DimFEGeometry< TWorldDim, TRefDim >::m_nip, ug::DimFEGeometry< TWorldDim, TRefDim >::m_nsh, ug::DimFEGeometry< TWorldDim, TRefDim >::m_pElem, ug::DimFEGeometry< TWorldDim, TRefDim >::m_quadOrder, ug::DimFEGeometry< TWorldDim, TRefDim >::m_roid, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vDetJ, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vIPGlobal, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vIPLocal, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vJTInv, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vvGradGlobal, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vvGradLocal, ug::MatVecMult(), ug::GridObject::reference_object_id(), UG_CATCH_THROW, ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> void ug::DimFEGeometry< TWorldDim, TRefDim >::update (GridObject * pElem, const MathVector< worldDim > * vCorner, const LFEID & lfeID) inline
References ug::LFEID::order(), and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
template<int TWorldDim, int TRefDim> void ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces (GridObject * pElem, const MathVector< worldDim > * vCornerCoords, size_t orderQuad, const ISubsetHandler * ish)
update boundary data for given element
References ug::DimFEGeometry< TWorldDim, TRefDim >::bf(), ug::CollectAssociated(), ug::DimReferenceElement< d >::corner(), ug::DimFEGeometry< TWorldDim, TRefDim >::dim, ug::QuadratureRuleProvider< TDim >::get(), ug::ReferenceMappingProvider::get(), ug::ISubsetHandler::get_subset_index(), ug::ISubsetHandler::grid(), ug::ReferenceElement::id(), ug::DimReferenceMapping< TDim, TWorldDim >::jacobian_transposed_inverse(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_ip(), ug::DimReferenceMapping< TDim, TWorldDim >::local_to_global(), ug::DimFEGeometry< TWorldDim, TRefDim >::m_lfeID, ug::DimFEGeometry< TWorldDim, TRefDim >::m_mapVectorBF, ug::DimFEGeometry< TWorldDim, TRefDim >::m_roid, ug::MatVecMult(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::nip, ug::DimFEGeometry< TWorldDim, TRefDim >::BF::Normal, ug::DimFEGeometry< TWorldDim, TRefDim >::BF::nsh, ug::ReferenceElement::num(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_sh(), ug::GridObject::reference_object_id(), ug::ReferenceElement::roid(), UG_CATCH_THROW, ug::DimReferenceMapping< TDim, TWorldDim >::update(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vDetJ, ug::VecTwoNorm(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vGlobalIP, ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vJtInv, ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vLocalIP, ug::DimFEGeometry< TWorldDim, TRefDim >::BF::Vol, ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vvGlobalGrad, ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vvLocalGrad, ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vvShape, ug::DimFEGeometry< TWorldDim, TRefDim >::BF::vWeight, and ug::DimFEGeometry< TWorldDim, TRefDim >::worldDim.
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update().
template<int TWorldDim, int TRefDim> void ug::DimFEGeometry< TWorldDim, TRefDim >::update_local (ReferenceObjectID roid, const LFEID & lfeID, size_t orderQuad)
update Geometry for roid
References ug::QuadratureRuleProvider< TDim >::get(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::DimFEGeometry< TWorldDim, TRefDim >::m_lfeID, ug::DimFEGeometry< TWorldDim, TRefDim >::m_nip, ug::DimFEGeometry< TWorldDim, TRefDim >::m_nsh, ug::DimFEGeometry< TWorldDim, TRefDim >::m_quadOrder, ug::DimFEGeometry< TWorldDim, TRefDim >::m_roid, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vDetJ, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vIPGlobal, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vIPLocal, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vJTInv, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vQuadWeight, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vvGradGlobal, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vvGradLocal, ug::DimFEGeometry< TWorldDim, TRefDim >::m_vvShape, ug::LocalDoFSet::num_sh(), ug::QuadratureRule< TDim >::points(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), ug::QuadratureRule< TDim >::size(), UG_CATCH_THROW, ug::DimFEGeometry< TWorldDim, TRefDim >::update(), and ug::QuadratureRule< TDim >::weights().
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::DimFEGeometry(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update().
template<int TWorldDim, int TRefDim = TWorldDim> void ug::DimFEGeometry< TWorldDim, TRefDim >::update_local (ReferenceObjectID roid, const LFEID & lfeID) inline
References ug::LFEID::order(), and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> number ug::DimFEGeometry< TWorldDim, TRefDim >::weight (size_t ip) const inline
weight for integration point
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vDetJ, and UG_ASSERT.
Member Data Documentation
template<int TWorldDim, int TRefDim = TWorldDim> const int ug::DimFEGeometry< TWorldDim, TRefDim >::dim = TRefDim static
reference element dimension
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
template<int TWorldDim, int TRefDim = TWorldDim> LFEID ug::DimFEGeometry< TWorldDim, TRefDim >::m_lfeID protected
current local finite element id
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> std::map<int, std::vector<BF> > ug::DimFEGeometry< TWorldDim, TRefDim >::m_mapVectorBF protected
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
template<int TWorldDim, int TRefDim = TWorldDim> size_t ug::DimFEGeometry< TWorldDim, TRefDim >::m_nip protected
number of integration point
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> size_t ug::DimFEGeometry< TWorldDim, TRefDim >::m_nsh protected
number of shape functions
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> GridObject* ug::DimFEGeometry< TWorldDim, TRefDim >::m_pElem protected
current element
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update().
template<int TWorldDim, int TRefDim = TWorldDim> int ug::DimFEGeometry< TWorldDim, TRefDim >::m_quadOrder protected
current integration order
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> ReferenceObjectID ug::DimFEGeometry< TWorldDim, TRefDim >::m_roid protected
current reference object id the local values are prepared for
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<number> ug::DimFEGeometry< TWorldDim, TRefDim >::m_vDetJ protected
determinant of transformation at ip (size = nip)
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<BF> ug::DimFEGeometry< TWorldDim, TRefDim >::m_vEmptyVectorBF protected
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<MathVector<worldDim> > ug::DimFEGeometry< TWorldDim, TRefDim >::m_vIPGlobal protected
global integration points (size = nip)
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> const MathVector<dim>* ug::DimFEGeometry< TWorldDim, TRefDim >::m_vIPLocal protected
local quadrature points
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<MathMatrix<worldDim,dim> > ug::DimFEGeometry< TWorldDim, TRefDim >::m_vJTInv protected
jacobian of transformation at ip (size = nip)
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> const number* ug::DimFEGeometry< TWorldDim, TRefDim >::m_vQuadWeight protected
local quadrature weights
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<std::vector<MathVector<worldDim> > > ug::DimFEGeometry< TWorldDim, TRefDim >::m_vvGradGlobal protected
local gradient evaluated at ip (size = nip x nsh)
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<std::vector<MathVector<dim> > > ug::DimFEGeometry< TWorldDim, TRefDim >::m_vvGradLocal protected
global gradient evaluated at ip (size = nip x nsh)
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> std::vector<std::vector<number> > ug::DimFEGeometry< TWorldDim, TRefDim >::m_vvShape protected
shape functions evaluated at ip (size = nip x nsh)
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
template<int TWorldDim, int TRefDim = TWorldDim> const bool ug::DimFEGeometry< TWorldDim, TRefDim >::staticLocalData = false static
flag indicating if local data may change
template<int TWorldDim, int TRefDim = TWorldDim> const int ug::DimFEGeometry< TWorldDim, TRefDim >::worldDim = TWorldDim static
world dimension
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces().
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/fe_geom.h
ugbase/lib_disc/spatial_disc/disc_util/fe_geom.cpp