ug4: ug::SmoothPartitionBounds< elem_t > Class Template Reference
ug::SmoothPartitionBounds< elem_t > Class Template Reference
early draft. Currently only useful for prism-geometries in the d3f-wipp setting
#include <smooth_partition_bounds.h>
Public Member Functions
void init_post_processing (MultiGrid *mg, SubsetHandler *partitions)
void partitioning_done ()
void post_process (int partitionLvl)
SmoothPartitionBounds ()
virtual ~SmoothPartitionBounds ()
Public Member Functions inherited from ug::IPartitionPostProcessor
virtual ~IPartitionPostProcessor ()
Private Types
typedef Attachment< subset_pair_t > a_subset_pair_t
typedef elem_t::side side_t
typedef std::pair< int, int > subset_pair_t
Private Attributes
a_subset_pair_t m_aSubsetNbrs
MultiGrid * m_mg
SubsetHandler * m_partitions
Detailed Description
template<class elem_t>
class ug::SmoothPartitionBounds< elem_t >
early draft. Currently only useful for prism-geometries in the d3f-wipp setting
Member Typedef Documentation
a_subset_pair_t
template<class elem_t > typedef Attachment<subset_pair_t> ug::SmoothPartitionBounds< elem_t >::a_subset_pair_t private
side_t
template<class elem_t > typedef elem_t::side ug::SmoothPartitionBounds< elem_t >::side_t private
subset_pair_t
template<class elem_t > typedef std::pair<int, int> ug::SmoothPartitionBounds< elem_t >::subset_pair_t private
Constructor & Destructor Documentation
SmoothPartitionBounds()
template<class elem_t > ug::SmoothPartitionBounds< elem_t >::SmoothPartitionBounds () inline
~SmoothPartitionBounds()
template<class elem_t > virtual ug::SmoothPartitionBounds< elem_t >::~SmoothPartitionBounds () inline virtual
References ug::Grid::detach_from(), ug::Grid::has_attachment(), ug::SmoothPartitionBounds< elem_t >::m_aSubsetNbrs, and ug::SmoothPartitionBounds< elem_t >::m_mg.
Member Function Documentation
init_post_processing()
template<class elem_t > void ug::SmoothPartitionBounds< elem_t >::init_post_processing (MultiGrid * mg, SubsetHandler * partitions) inline virtual
Implements ug::IPartitionPostProcessor.
References ug::Grid::attach_to(), ug::SmoothPartitionBounds< elem_t >::m_aSubsetNbrs, ug::SmoothPartitionBounds< elem_t >::m_mg, and ug::SmoothPartitionBounds< elem_t >::m_partitions.
partitioning_done()
template<class elem_t > void ug::SmoothPartitionBounds< elem_t >::partitioning_done () inline virtual
Implements ug::IPartitionPostProcessor.
References ug::Grid::detach_from(), ug::SmoothPartitionBounds< elem_t >::m_aSubsetNbrs, and ug::SmoothPartitionBounds< elem_t >::m_mg.
post_process()
template<class elem_t > void ug::SmoothPartitionBounds< elem_t >::post_process (int partitionLvl) inline virtual
Implements ug::IPartitionPostProcessor.
References ug::GridSubsetHandler::assign_subset(), ug::Grid::associated_elements(), ug::MultiGrid::begin(), ug::MultiGrid::end(), end_for, for_each_in_vec, ug::ISubsetHandler::get_subset_index(), lg_for_each_in_lvl_template, ug::SmoothPartitionBounds< elem_t >::m_aSubsetNbrs, ug::SmoothPartitionBounds< elem_t >::m_mg, ug::SmoothPartitionBounds< elem_t >::m_partitions, ug::ROID_QUADRILATERAL, s, and ug::SetAttachmentValues().
Member Data Documentation
m_aSubsetNbrs
template<class elem_t > a_subset_pair_t ug::SmoothPartitionBounds< elem_t >::m_aSubsetNbrs private
Referenced by ug::SmoothPartitionBounds< elem_t >::init_post_processing(), ug::SmoothPartitionBounds< elem_t >::partitioning_done(), ug::SmoothPartitionBounds< elem_t >::post_process(), and ug::SmoothPartitionBounds< elem_t >::~SmoothPartitionBounds().
m_mg
template<class elem_t > MultiGrid* ug::SmoothPartitionBounds< elem_t >::m_mg private
Referenced by ug::SmoothPartitionBounds< elem_t >::init_post_processing(), ug::SmoothPartitionBounds< elem_t >::partitioning_done(), ug::SmoothPartitionBounds< elem_t >::post_process(), and ug::SmoothPartitionBounds< elem_t >::~SmoothPartitionBounds().
m_partitions
template<class elem_t > SubsetHandler* ug::SmoothPartitionBounds< elem_t >::m_partitions private
Referenced by ug::SmoothPartitionBounds< elem_t >::init_post_processing(), and ug::SmoothPartitionBounds< elem_t >::post_process().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/partition_post_processors/smooth_partition_bounds.h