ug4: ug::FaceDescriptor Class Reference
ug::FaceDescriptor Class Reference
Can be queried for the edges and vertices of a face.
#include <grid_base_objects.h>
Public Member Functions
FaceDescriptor ()
FaceDescriptor (const FaceDescriptor &fd)
FaceDescriptor (uint numVertices)
FaceDescriptor (Vertex *v0, Vertex *v1, Vertex *v2)
FaceDescriptor (Vertex *v0, Vertex *v1, Vertex *v2, Vertex *v3)
virtual size_t num_vertices () const
FaceDescriptor & operator= (const FaceDescriptor &fd)
void set_num_vertices (uint numVertices)
void set_vertex (uint index, Vertex *vrt)
virtual Vertex * vertex (size_t index) const
virtual ConstVertexArray vertices () const
virtual ~FaceDescriptor ()
Public Member Functions inherited from ug::FaceVertices
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~FaceVertices ()
Public Member Functions inherited from ug::IVertexGroup
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~IVertexGroup ()
Protected Attributes
uint m_numVertices
Vertex * m_vertices [MAX_FACE_VERTICES]
Additional Inherited Members
Public Types inherited from ug::IVertexGroup
typedef Vertex *const * ConstVertexArray
Detailed Description
Can be queried for the edges and vertices of a face.
Constructor & Destructor Documentation
FaceDescriptor() [1/5]
ug::FaceDescriptor::FaceDescriptor ()
FaceDescriptor() [2/5]
ug::FaceDescriptor::FaceDescriptor (uint numVertices)
FaceDescriptor() [3/5]
ug::FaceDescriptor::FaceDescriptor (const FaceDescriptor & fd)
References m_numVertices, and m_vertices.
FaceDescriptor() [4/5]
ug::FaceDescriptor::FaceDescriptor (Vertex * v0, Vertex * v1, Vertex * v2) inline
FaceDescriptor() [5/5]
ug::FaceDescriptor::FaceDescriptor (Vertex * v0, Vertex * v1, Vertex * v2, Vertex * v3) inline
~FaceDescriptor()
virtual ug::FaceDescriptor::~FaceDescriptor () inline virtual
Member Function Documentation
num_vertices()
virtual size_t ug::FaceDescriptor::num_vertices () const inline virtual
Reimplemented from ug::FaceVertices.
Referenced by ug::Grid::assign_grid(), ug::Duplicate(), ug::ExpandFractures2d(), ug::GetNeighbours(), ug::GetRightLeftUnitIndex(), ug::InsertCenterVertex(), ug::MergeGrids(), ug::OrientationMatches(), and ug::Grid::replace_vertex().
operator=()
FaceDescriptor & ug::FaceDescriptor::operator= (const FaceDescriptor & fd)
References m_numVertices, and m_vertices.
set_num_vertices()
void ug::FaceDescriptor::set_num_vertices (uint numVertices) inline
Referenced by ug::Grid::assign_grid(), ug::Duplicate(), ug::ExpandFractures2d(), ug::ExpandFractures3d(), ug::Tetrahedron::face_desc(), ug::Hexahedron::face_desc(), ug::Prism::face_desc(), ug::Pyramid::face_desc(), ug::Octahedron::face_desc(), ug::MergeGrids(), ug::MergeVertices(), ug::MinimizeEdgeLength_SwapsOnly(), ug::GlobalFracturedMediaRefiner::perform_refinement(), and ug::Grid::replace_vertex().
set_vertex()
void ug::FaceDescriptor::set_vertex (uint index, Vertex * vrt) inline
Referenced by ug::Grid::assign_grid(), ug::Duplicate(), ug::EdgeCollapseIsValid(), ug::ExpandFractures2d(), ug::ExpandFractures3d(), ug::Tetrahedron::face_desc(), ug::Hexahedron::face_desc(), ug::Prism::face_desc(), ug::Pyramid::face_desc(), ug::Octahedron::face_desc(), ug::MergeGrids(), ug::MergeVertices(), ug::MinimizeEdgeLength_SwapsOnly(), ug::MultiEdgeSplit(), ug::GlobalFracturedMediaRefiner::perform_refinement(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex(), ug::Grid::replace_vertex(), ug::ReplaceByQuadrilaterals_EdgeBased(), ug::ResolveTriangleIntersections(), and ug::ResolveVertexFaceIntersection().
vertex()
virtual Vertex* ug::FaceDescriptor::vertex (size_t index) const inline virtual
Reimplemented from ug::FaceVertices.
Referenced by ug::CalculateMinVolumeHeight(), ug::CollectVolumes(), ug::ContainsPoint(), ug::Grid::flip_orientation(), ug::Grid::get_face(), ug::GetNeighbours(), ug::GetRightLeftUnitIndex(), ug::InsertCenterVertex(), ug::MultiEdgeSplit(), ug::OrientationMatches(), ug::Grid::register_volume(), ug::ResolveVertexFaceIntersection(), ug::Grid::volume_autogenerate_faces(), and ug::Grid::volume_store_associated_faces().
vertices()
virtual ConstVertexArray ug::FaceDescriptor::vertices () const inline virtual
Reimplemented from ug::FaceVertices.
Referenced by ug::Grid::replace_vertex().
Member Data Documentation
m_numVertices
uint ug::FaceDescriptor::m_numVertices protected
Referenced by FaceDescriptor(), and operator=().
m_vertices
Vertex* ug::FaceDescriptor::m_vertices[MAX_FACE_VERTICES] protected
Referenced by FaceDescriptor(), and operator=().
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid/grid_base_objects.h
ugbase/lib_grid/grid/grid_base_objects.cpp