ug4: ug::CustomVertexGroup Class Reference
ug::CustomVertexGroup Class Reference
this class can be used if one wants to create a custom element from a set of vertices.
#include <grid_base_objects.h>
Public Member Functions
void clear ()
CustomVertexGroup ()
CustomVertexGroup (size_t numVrts)
virtual size_t num_vertices () const
void push_back (Vertex *vrt)
void resize (size_t newSize)
void set_num_vertices (size_t newSize)
void set_vertex (size_t index, Vertex *vrt)
virtual Vertex * vertex (size_t index) const
virtual ConstVertexArray vertices () const
virtual ~CustomVertexGroup ()
Public Member Functions inherited from ug::IVertexGroup
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~IVertexGroup ()
Private Attributes
std::vector< Vertex * > m_vrts
Additional Inherited Members
Public Types inherited from ug::IVertexGroup
typedef Vertex *const * ConstVertexArray
Detailed Description
this class can be used if one wants to create a custom element from a set of vertices.
Constructor & Destructor Documentation
CustomVertexGroup() [1/2]
ug::CustomVertexGroup::CustomVertexGroup () inline
CustomVertexGroup() [2/2]
ug::CustomVertexGroup::CustomVertexGroup (size_t numVrts) inline
~CustomVertexGroup()
virtual ug::CustomVertexGroup::~CustomVertexGroup () inline virtual
Member Function Documentation
clear()
void ug::CustomVertexGroup::clear () inline
num_vertices()
virtual size_t ug::CustomVertexGroup::num_vertices () const inline virtual
Implements ug::IVertexGroup.
push_back()
void ug::CustomVertexGroup::push_back (Vertex * vrt) inline
resize()
void ug::CustomVertexGroup::resize (size_t newSize) inline
Referenced by ug::CopyGridElements(), ug::CopyGridLevelElements(), and ug::CopySelectedElements().
set_num_vertices()
void ug::CustomVertexGroup::set_num_vertices (size_t newSize) inline
set_vertex()
void ug::CustomVertexGroup::set_vertex (size_t index, Vertex * vrt) inline
Referenced by ug::CopyGridElements(), ug::CopyGridLevelElements(), and ug::CopySelectedElements().
vertex()
virtual Vertex* ug::CustomVertexGroup::vertex (size_t index) const inline virtual
Implements ug::IVertexGroup.
vertices()
virtual ConstVertexArray ug::CustomVertexGroup::vertices () const inline virtual
Implements ug::IVertexGroup.
Member Data Documentation
m_vrts
std::vector<Vertex*> ug::CustomVertexGroup::m_vrts private
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/grid_base_objects.h