ug4: ug::MGSelector Class Reference
ug::MGSelector Class Reference
lib_grid » grid-tools
specialization of ISelector for grids of class MultiGrid.
#include <selector_multi_grid.h>
Classes
struct Level
class MGSelectionIterator
struct traits
The traits class holds some important types for each element-type.
Public Types
typedef ISelector BaseClass
typedef MultiGrid grid_type
Public Types inherited from ug::ISelector
enum { DESELECTED = 0 , SELECTED = 1 }
typedef byte status_t
Public Member Functions
void assign_grid (MultiGrid &grid)
void assign_grid (MultiGrid *grid)
template<class TElem >
TElem * back (int level)
returns the last selected element of the given type on the specified level.
template<class TElem >
traits< TElem >::iterator begin ()
template<class TElem >
traits< TElem >::const_iterator begin () const
template<class TElem >
traits< TElem >::level_iterator begin (int level)
template<class TElem >
traits< TElem >::const_level_iterator begin (int level) const
virtual void clear ()
template<class TElem >
void clear ()
void clear (int level)
template<class TElem >
void clear (int level)
virtual bool contains_edges () const
returns true if the selector contains edges
virtual bool contains_faces () const
returns true if the selector contains faces
virtual bool contains_vertices () const
returns true if the selector contains vertices
virtual bool contains_volumes () const
returns true if the selector contains volumes
void disable_element_support (uint shElements)
disable support for element-types.
traits< Edge >::level_iterator edges_begin (int level)
traits< Edge >::level_iterator edges_end (int level)
bool empty () const
template<class TElem >
bool empty () const
bool empty (int level) const
template<class TElem >
bool empty (int level) const
void enable_element_support (uint shElements)
enable support for element-types. Does not invalidate previous settings.
template<class TElem >
traits< TElem >::iterator end ()
template<class TElem >
traits< TElem >::const_iterator end () const
template<class TElem >
traits< TElem >::level_iterator end (int level)
template<class TElem >
traits< TElem >::const_level_iterator end (int level) const
traits< Face >::level_iterator faces_begin (int level)
traits< Face >::level_iterator faces_end (int level)
template<class TElem >
TElem * front (int level)
returns the first selected element of the given type on the specified level.
virtual GridObjectCollection get_grid_objects () const
returns a geometric object collection, containing all selected objects
virtual void grid_to_be_destroyed (Grid *grid)
MGSelector (MultiGrid &grid, uint supportedElements=SE_ALL)
MGSelector (uint supportedElements=SE_ALL)
MultiGrid * multi_grid ()
template<class TElem >
size_t num () const
size_t num () const
template<class TElem >
size_t num (int level) const
size_t num (int level) const
size_t num_levels () const
void set_supported_elements (uint shElements)
set the type of elements that shall be handled by the Selector.
size_t top_level () const
traits< Vertex >::level_iterator vertices_begin (int level)
traits< Vertex >::level_iterator vertices_end (int level)
traits< Volume >::level_iterator volumes_begin (int level)
traits< Volume >::level_iterator volumes_end (int level)
virtual ~MGSelector ()
Public Member Functions inherited from ug::ISelector
bool autoselection_enabled ()
virtual void broadcast_selection_states (bool deselect=false, bool includeGhosts=false)
broadcasts the current selection
void deselect (GridObject *elem)
template<class TElem >
void deselect (TElem *elem)
template<class TIterator >
void deselect (TIterator iterBegin, TIterator iterEnd)
virtual void edge_created (Grid *grid, Edge *e, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void edge_to_be_erased (Grid *grid, Edge *e, Edge *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void edges_to_be_merged (Grid *grid, Edge *target, Edge *elem1, Edge *elem2)
Notified when two elements of the same type are going to be merged.
bool elements_are_supported (uint shElements) const
returns true if the given element-types are supported.
virtual void elements_to_be_cleared (Grid *grid)
void enable_autoselection (bool bEnable)
void enable_selection_inheritance (bool bEnable)
void enable_strict_inheritance (bool bEnable)
virtual void face_created (Grid *grid, Face *f, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void face_to_be_erased (Grid *grid, Face *f, Face *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void faces_to_be_merged (Grid *grid, Face *target, Face *elem1, Face *elem2)
Notified when two elements of the same type are going to be merged.
template<class TElem >
byte get_mark (TElem *elem) const
returns the selection state of the specified elelent
Grid * grid () const
template<class TElem >
bool is_selected (TElem *elem) const
returns true if an element is selected
ISelector (Grid &grid, uint supportedElements=SE_ALL)
ISelector (uint supportedElements=SE_ALL)
bool selection_inheritance_enabled ()
bool strict_inheritance_enabled ()
template<class TElem >
void unmark (TElem *elem)
deselects an element
virtual void vertex_created (Grid *grid, Vertex *vrt, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void vertex_to_be_erased (Grid *grid, Vertex *vrt, Vertex *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void vertices_to_be_merged (Grid *grid, Vertex *target, Vertex *elem1, Vertex *elem2)
Notified when two elements of the same type are going to be merged.
virtual void volume_created (Grid *grid, Volume *vol, GridObject *pParent=NULL, bool replacesParent=false)
Notified whenever a new element of the given type is created in the given grid.
virtual void volume_to_be_erased (Grid *grid, Volume *vol, Volume *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void volumes_to_be_merged (Grid *grid, Volume *target, Volume *elem1, Volume *elem2)
Notified when two elements of the same type are going to be merged.
virtual ~ISelector ()
void select (GridObject *elem, byte status)
selects an element
void select (GridObject *elem)
selects an element
template<class TElem >
void select (TElem *elem, byte status)
selects an element
template<class TElem >
void select (TElem *elem)
selects an element
template<class TIterator >
void select (TIterator iterBegin, TIterator iterEnd, byte status=1)
selects an element
template<class TElem >
void mark (TElem *elem)
selects an element
template<class TElem >
void mark (TElem *elem, byte status)
selects an element
byte get_selection_status (GridObject *elem) const
returns the selection state of the specified elelent
byte get_selection_status (Vertex *vrt) const
returns the selection state of the specified elelent
byte get_selection_status (Edge *edge) const
returns the selection state of the specified elelent
byte get_selection_status (Face *face) const
returns the selection state of the specified elelent
byte get_selection_status (Volume *vol) const
returns the selection state of the specified elelent
Public Member Functions inherited from ug::GridObserver
virtual ~GridObserver ()
Protected Types
typedef Grid::traits< Edge >::AttachedElementList AttachedEdgeList
typedef Grid::traits< Face >::AttachedElementList AttachedFaceList
typedef Grid::traits< Vertex >::AttachedElementList AttachedVertexList
typedef Grid::traits< Volume >::AttachedElementList AttachedVolumeList
typedef Grid::traits< Edge >::SectionContainer EdgeSectionContainer
typedef Grid::traits< Face >::SectionContainer FaceSectionContainer
typedef std::vector< Level * > LevelVec
typedef Grid::traits< Vertex >::SectionContainer VertexSectionContainer
typedef Grid::traits< Volume >::SectionContainer VolumeSectionContainer
Protected Types inherited from ug::ISelector
typedef Grid::traits< Edge >::AttachedElementList AttachedEdgeList
typedef Grid::traits< Face >::AttachedElementList AttachedFaceList
typedef Grid::traits< Vertex >::AttachedElementList AttachedVertexList
typedef Grid::traits< Volume >::AttachedElementList AttachedVolumeList
typedef Attachment< unsigned char > AUChar
typedef Grid::traits< Edge >::SectionContainer EdgeSectionContainer
typedef Grid::traits< Face >::SectionContainer FaceSectionContainer
typedef Grid::traits< Vertex >::SectionContainer VertexSectionContainer
typedef Grid::traits< Volume >::SectionContainer VolumeSectionContainer
Protected Member Functions
void add_level ()
virtual void add_to_list (Edge *elem)
virtual void add_to_list (Face *elem)
virtual void add_to_list (Vertex *elem)
virtual void add_to_list (Volume *elem)
void cleanup ()
This method should only be called if a complete cleanup is required.
void clear_lists ()
virtual void erase_from_list (Edge *elem)
virtual void erase_from_list (Face *elem)
virtual void erase_from_list (Vertex *elem)
virtual void erase_from_list (Volume *elem)
template<class TElem >
int get_section_index () const
void level_required (int newSize)
void multigrid_changed (const GridMessage_MultiGridChanged &gm)
callback for multigrid messages
template<class TElem >
Grid::traits< TElem >::SectionContainer & section_container (int level)
returns the section container for the given type, subset and level
template<class TElem >
const Grid::traits< TElem >::SectionContainer & section_container (int level) const
returns the const section container for the given type, subset and level
VertexSectionContainer::iterator get_level_iterator (Vertex *o)
returns the iterator at which the given element lies in the section container
EdgeSectionContainer::iterator get_level_iterator (Edge *o)
returns the iterator at which the given element lies in the section container
FaceSectionContainer::iterator get_level_iterator (Face *o)
returns the iterator at which the given element lies in the section container
VolumeSectionContainer::iterator get_level_iterator (Volume *o)
returns the iterator at which the given element lies in the section container
Protected Member Functions inherited from ug::ISelector
void disable_element_support (uint shElements)
disable support for element-types.
template<class TElem >
void elems_to_be_merged (Grid *grid, TElem *target, TElem *elem1, TElem *elem2)
helper for GridObserver callbacks.
void enable_element_support (uint shElements)
enable support for element-types. Does not invalidate previous settings.
void mark_deselected (Edge *elem)
void mark_deselected (Face *elem)
void mark_deselected (Vertex *elem)
void mark_deselected (Volume *elem)
void mark_selected (Edge *elem, byte status)
void mark_selected (Face *elem, byte status)
void mark_selected (Vertex *elem, byte status)
void mark_selected (Volume *elem, byte status)
void set_grid (Grid *grid)
performs grid registration / deregistration and initialisation of the observer.
void set_supported_elements (uint shElements)
set the type of elements that shall be handled by the SubsetHandler.
Protected Attributes
AttachedEdgeList::AEntry m_aSharedEntryEDGE
AttachedFaceList::AEntry m_aSharedEntryFACE
AttachedVolumeList::AEntry m_aSharedEntryVOL
AttachedVertexList::AEntry m_aSharedEntryVRT
MessageHub::SPCallbackId m_callbackId
LevelVec m_levels
MultiGrid * m_pMultiGrid
Copy Constructor not yet implemented!
VertexIterator m_tmpVBegin
VertexIterator m_tmpVEnd
Protected Attributes inherited from ug::ISelector
Grid::AttachmentAccessor< Edge, AUChar > m_aaSelEDGE
Grid::AttachmentAccessor< Face, AUChar > m_aaSelFACE
Grid::AttachmentAccessor< Volume, AUChar > m_aaSelVOL
Grid::AttachmentAccessor< Vertex, AUChar > m_aaSelVRT
AUChar m_aSelected
bool m_bAutoselectionEnabled
bool m_bSelectionInheritanceEnabled
bool m_bStrictInheritanceEnabled
pcl::InterfaceCommunicator< EdgeLayout > m_icomEDGE
pcl::InterfaceCommunicator< FaceLayout > m_icomFACE
pcl::InterfaceCommunicator< VolumeLayout > m_icomVOL
pcl::InterfaceCommunicator< VertexLayout > m_icomVRT
Grid * m_pGrid
uint m_supportedElements
Private Member Functions
MGSelector (const MGSelector &sel)
Detailed Description
specialization of ISelector for grids of class MultiGrid.
A selector is a useful class, that allows the user to mark elements of a grid as selected or deselected. The selection status is maintained even if new elements are created or old ones deleted. Features like autoselection and selection_inheritance allow users to follow the creation and removal of elements in all kind of algorithms.
Please note that the selector has to be registered at a grid before it may be used. You may register it using the constructor or the method assign_grid.
This is a specialization of ISelector for the MultiGrid class.
The following methods are the most used:
select, deselect, is_selected (see ISelector)
begin, end, num, clear.
Note that the number of levels in the MGSelector always matches the number of levels in the associated multigrid. This is guaranteed through a callback mechanism.
You may specify the element-type on which begin, end, num and clear operate via a template parameter, and the level via a normal int-parameter:
MultiGrid mg;
MGSelector sel(mg);
// ... create elements and select some
// number of selected vertices on level 1
int nSelVrts = sel.num<Vertex>(1);
// total number of selected triangles
int nSelTris = sel.num<Triangle>();
// iteration over all faces
for(uint i = 0; i < sel.num_levels(); ++i){
 for(FaceIterator iter = sel.begin<Face>(i);
  iter != sel.end<Face>(i); ++iter){
// ...
 }
}
Member Typedef Documentation
AttachedEdgeList
typedef Grid::traits<Edge>::AttachedElementList ug::ISelector::AttachedEdgeList protected
AttachedFaceList
typedef Grid::traits<Face>::AttachedElementList ug::ISelector::AttachedFaceList protected
AttachedVertexList
typedef Grid::traits<Vertex>::AttachedElementList ug::ISelector::AttachedVertexList protected
AttachedVolumeList
typedef Grid::traits<Volume>::AttachedElementList ug::ISelector::AttachedVolumeList protected
BaseClass
typedef ISelector ug::MGSelector::BaseClass
EdgeSectionContainer
typedef Grid::traits<Edge>::SectionContainer ug::ISelector::EdgeSectionContainer protected
FaceSectionContainer
typedef Grid::traits<Face>::SectionContainer ug::ISelector::FaceSectionContainer protected
grid_type
typedef MultiGrid ug::MGSelector::grid_type
LevelVec
typedef std::vector<Level*> ug::MGSelector::LevelVec protected
VertexSectionContainer
typedef Grid::traits<Vertex>::SectionContainer ug::ISelector::VertexSectionContainer protected
VolumeSectionContainer
typedef Grid::traits<Volume>::SectionContainer ug::ISelector::VolumeSectionContainer protected
Constructor & Destructor Documentation
MGSelector() [1/3]
ug::MGSelector::MGSelector (uint supportedElements = SE_ALL)
References m_pMultiGrid.
MGSelector() [2/3]
ug::MGSelector::MGSelector (MultiGrid & grid, uint supportedElements = SE_ALL)
References assign_grid(), and ug::ISelector::grid().
~MGSelector()
ug::MGSelector::~MGSelector () virtual
References cleanup().
MGSelector() [3/3]
ug::MGSelector::MGSelector (const MGSelector & sel) inline private
Member Function Documentation
add_level()
void ug::MGSelector::add_level () protected
References ug::ISelector::elements_are_supported(), ug::Grid::get_attachment_pipe(), ug::SectionContainer< TValue, TContainer >::get_container(), m_aSharedEntryEDGE, m_aSharedEntryFACE, m_aSharedEntryVOL, m_aSharedEntryVRT, ug::MGSelector::Level::m_edges, ug::MGSelector::Level::m_faces, m_levels, ug::ISelector::m_pGrid, ug::MGSelector::Level::m_vertices, ug::MGSelector::Level::m_volumes, ug::SE_EDGE, ug::SE_FACE, ug::SE_VERTEX, ug::SE_VOLUME, and ug::AttachedElementList< TAttachmentPipe >::set_pipe().
Referenced by level_required().
add_to_list() [1/4]
void ug::MGSelector::add_to_list (Edge * elem) protected virtual
Implements ug::ISelector.
References ug::Edge::container_section(), ug::MultiGrid::get_level(), and m_pMultiGrid.
add_to_list() [2/4]
void ug::MGSelector::add_to_list (Face * elem) protected virtual
Implements ug::ISelector.
References ug::Face::container_section(), ug::MultiGrid::get_level(), and m_pMultiGrid.
add_to_list() [3/4]
void ug::MGSelector::add_to_list (Vertex * elem) protected virtual
Implements ug::ISelector.
References ug::Vertex::container_section(), ug::MultiGrid::get_level(), and m_pMultiGrid.
add_to_list() [4/4]
void ug::MGSelector::add_to_list (Volume * elem) protected virtual
Implements ug::ISelector.
References ug::Volume::container_section(), ug::MultiGrid::get_level(), and m_pMultiGrid.
assign_grid() [1/2]
void ug::MGSelector::assign_grid (MultiGrid & grid)
References ug::ISelector::grid().
Referenced by MGSelector().
assign_grid() [2/2]
void ug::MGSelector::assign_grid (MultiGrid * grid)
References cleanup(), enable_element_support(), ug::ISelector::grid(), level_required(), m_callbackId, m_pMultiGrid, ug::ISelector::m_supportedElements, ug::Grid::message_hub(), multigrid_changed(), ug::MultiGrid::num_levels(), ug::SE_NONE, and ug::ISelector::set_grid().
back()
template<class TElem > TElem * ug::MGSelector::back (int level)
returns the last selected element of the given type on the specified level.
Make sure that elements of the given type exist! Behaviour is undefined, if not.
begin() [1/4]
template<class TElem > MGSelector::traits< TElem >::iterator ug::MGSelector::begin inline
References top_level().
Referenced by ug::AddTargetProcToDistInfos(), ug::AssignVerticalMasterAndSlaveStates(), ug::HangingNodeRefiner_MultiGrid::collect_objects_for_coarsen(), ug::AdaptionSurfaceGridFunction< TDomain >::do_restrict(), ug::AdaptiveRegularRefiner_MultiGrid::get_parents_of_marked_closure_elements(), ug::HangingNodeRefiner_MultiGrid::perform_coarsening(), ug::HangingNodeRefiner_MultiGrid::pre_refine(), ug::HangingNodeRefiner_MultiGrid::restrict_selection_to_coarsen_families(), ug::SelectAssociatedConstrainedElements(), ug::SelectAssociatedGenealogy(), ug::SelectChildrenOfSelectedShadowRimEdges(), ug::SelectChildrenOfSelectedShadowRimFaces(), ug::SelectChildrenOfSelectedShadowVertices(), and ug::SelectSelectedRootElementsAsVSlaves().
begin() [2/4]
template<class TElem > MGSelector::traits< TElem >::const_iterator ug::MGSelector::begin inline
References top_level().
begin() [3/4]
template<class TElem > MGSelector::traits< TElem >::level_iterator ug::MGSelector::begin (int level) inline
begin() [4/4]
template<class TElem > MGSelector::traits< TElem >::const_level_iterator ug::MGSelector::begin (int level) const inline
cleanup()
void ug::MGSelector::cleanup () protected
This method should only be called if a complete cleanup is required.
References disable_element_support(), m_callbackId, m_levels, m_pMultiGrid, ug::ISelector::m_supportedElements, and ug::ISelector::set_grid().
Referenced by assign_grid(), and ~MGSelector().
clear() [1/4]
void ug::MGSelector::clear () virtual
Implements ug::ISelector.
Referenced by ug::HangingNodeRefiner_MultiGrid::collect_objects_for_coarsen(), ug::DistributeGrid(), and ug::FillDistInfos().
clear() [2/4]
template<class TElem > void ug::MGSelector::clear inline virtual
Implements ug::ISelector.
References ug::ISelector::m_pGrid, and num_levels().
clear() [3/4]
void ug::MGSelector::clear (int level)
clear() [4/4]
template<class TElem > void ug::MGSelector::clear (int level) inline
References ug::ISelector::m_pGrid, and ug::ISelector::mark_deselected().
clear_lists()
void ug::MGSelector::clear_lists () protected
References m_levels.
Referenced by grid_to_be_destroyed().
contains_edges()
virtual bool ug::MGSelector::contains_edges () const inline virtual
returns true if the selector contains edges
Implements ug::ISelector.
contains_faces()
virtual bool ug::MGSelector::contains_faces () const inline virtual
returns true if the selector contains faces
Implements ug::ISelector.
contains_vertices()
virtual bool ug::MGSelector::contains_vertices () const inline virtual
returns true if the selector contains vertices
Implements ug::ISelector.
contains_volumes()
virtual bool ug::MGSelector::contains_volumes () const inline virtual
returns true if the selector contains volumes
Implements ug::ISelector.
disable_element_support()
void ug::MGSelector::disable_element_support (uint shElements)
disable support for element-types.
pass an or-combination of constants enumerated in SelectorElements.
References ug::Grid::detach_from_edges(), ug::Grid::detach_from_faces(), ug::Grid::detach_from_vertices(), ug::Grid::detach_from_volumes(), ug::ISelector::disable_element_support(), ug::ISelector::elements_are_supported(), ug::SectionContainer< TValue, TContainer >::get_container(), m_aSharedEntryEDGE, m_aSharedEntryFACE, m_aSharedEntryVOL, m_aSharedEntryVRT, ug::MGSelector::Level::m_edges, ug::MGSelector::Level::m_faces, m_levels, m_pMultiGrid, ug::MGSelector::Level::m_vertices, ug::MGSelector::Level::m_volumes, ug::SE_EDGE, ug::SE_FACE, ug::SE_VERTEX, ug::SE_VOLUME, and ug::AttachedElementList< TAttachmentPipe >::set_pipe().
Referenced by cleanup(), and set_supported_elements().
edges_begin()
traits<Edge>::level_iterator ug::MGSelector::edges_begin (int level) inline
Referenced by ug::SelectAssociatedGenealogy().
edges_end()
traits<Edge>::level_iterator ug::MGSelector::edges_end (int level) inline
Referenced by ug::SelectAssociatedGenealogy().
empty() [1/4]
bool ug::MGSelector::empty () const inline
References num().
empty() [2/4]
template<class TElem > bool ug::MGSelector::empty inline
empty() [3/4]
bool ug::MGSelector::empty (int level) const inline
References num().
Referenced by ug::FillDistInfos().
empty() [4/4]
template<class TElem > bool ug::MGSelector::empty (int level) const inline
enable_element_support()
void ug::MGSelector::enable_element_support (uint shElements) inline
enable support for element-types. Does not invalidate previous settings.
pass an or-combination of constants enumerated in SelectorElements.
References ug::Grid::attach_to_edges(), ug::Grid::attach_to_faces(), ug::Grid::attach_to_vertices(), ug::Grid::attach_to_volumes(), ug::ISelector::elements_are_supported(), ug::ISelector::enable_element_support(), ug::Grid::get_attachment_pipe(), ug::SectionContainer< TValue, TContainer >::get_container(), m_aSharedEntryEDGE, m_aSharedEntryFACE, m_aSharedEntryVOL, m_aSharedEntryVRT, ug::MGSelector::Level::m_edges, ug::MGSelector::Level::m_faces, m_levels, ug::ISelector::m_pGrid, m_pMultiGrid, ug::MGSelector::Level::m_vertices, ug::MGSelector::Level::m_volumes, ug::SE_EDGE, ug::SE_FACE, ug::SE_VERTEX, ug::SE_VOLUME, and ug::AttachedElementList< TAttachmentPipe >::set_pipe().
Referenced by assign_grid(), and set_supported_elements().
end() [1/4]
template<class TElem > MGSelector::traits< TElem >::iterator ug::MGSelector::end inline
References top_level().
Referenced by ug::AddTargetProcToDistInfos(), ug::AssignVerticalMasterAndSlaveStates(), ug::HangingNodeRefiner_MultiGrid::collect_objects_for_coarsen(), ug::AdaptionSurfaceGridFunction< TDomain >::do_restrict(), ug::AdaptiveRegularRefiner_MultiGrid::get_parents_of_marked_closure_elements(), ug::HangingNodeRefiner_MultiGrid::perform_coarsening(), ug::HangingNodeRefiner_MultiGrid::pre_refine(), ug::HangingNodeRefiner_MultiGrid::restrict_selection_to_coarsen_families(), ug::SelectAssociatedConstrainedElements(), ug::SelectAssociatedGenealogy(), ug::SelectChildrenOfSelectedShadowRimEdges(), ug::SelectChildrenOfSelectedShadowRimFaces(), ug::SelectChildrenOfSelectedShadowVertices(), and ug::SelectSelectedRootElementsAsVSlaves().
end() [2/4]
template<class TElem > MGSelector::traits< TElem >::const_iterator ug::MGSelector::end inline
References top_level().
end() [3/4]
template<class TElem > MGSelector::traits< TElem >::level_iterator ug::MGSelector::end (int level) inline
end() [4/4]
template<class TElem > MGSelector::traits< TElem >::const_level_iterator ug::MGSelector::end (int level) const inline
erase_from_list() [1/4]
void ug::MGSelector::erase_from_list (Edge * elem) protected virtual
Implements ug::ISelector.
References ug::Edge::container_section(), ug::MultiGrid::get_level(), get_level_iterator(), and m_pMultiGrid.
erase_from_list() [2/4]
void ug::MGSelector::erase_from_list (Face * elem) protected virtual
Implements ug::ISelector.
References ug::Face::container_section(), ug::MultiGrid::get_level(), get_level_iterator(), and m_pMultiGrid.
erase_from_list() [3/4]
void ug::MGSelector::erase_from_list (Vertex * elem) protected virtual
Implements ug::ISelector.
References ug::Vertex::container_section(), ug::MultiGrid::get_level(), get_level_iterator(), and m_pMultiGrid.
erase_from_list() [4/4]
void ug::MGSelector::erase_from_list (Volume * elem) protected virtual
Implements ug::ISelector.
References ug::Volume::container_section(), ug::MultiGrid::get_level(), get_level_iterator(), and m_pMultiGrid.
faces_begin()
traits<Face>::level_iterator ug::MGSelector::faces_begin (int level) inline
Referenced by ug::SelectAssociatedGenealogy().
faces_end()
traits<Face>::level_iterator ug::MGSelector::faces_end (int level) inline
Referenced by ug::SelectAssociatedGenealogy().
front()
template<class TElem > TElem * ug::MGSelector::front (int level)
returns the first selected element of the given type on the specified level.
Make sure that elements of the given type exist! Behaviour is undefined, if not.
get_grid_objects()
GridObjectCollection ug::MGSelector::get_grid_objects () const virtual
returns a geometric object collection, containing all selected objects
Implements ug::ISelector.
References ug::GridObjectCollection::add_level(), m_levels, and num_levels().
Referenced by ug::HangingNodeRefiner_MultiGrid::collect_objects_for_coarsen(), and ug::DistributeGrid().
get_level_iterator() [1/4]
EdgeSectionContainer::iterator ug::MGSelector::get_level_iterator (Edge * o) inline protected
returns the iterator at which the given element lies in the section container
This method may only be called if the element is indeed selected
get_level_iterator() [2/4]
FaceSectionContainer::iterator ug::MGSelector::get_level_iterator (Face * o) inline protected
returns the iterator at which the given element lies in the section container
This method may only be called if the element is indeed selected
get_level_iterator() [3/4]
VertexSectionContainer::iterator ug::MGSelector::get_level_iterator (Vertex * o) inline protected
returns the iterator at which the given element lies in the section container
This method may only be called if the element is indeed selected
Referenced by erase_from_list().
get_level_iterator() [4/4]
VolumeSectionContainer::iterator ug::MGSelector::get_level_iterator (Volume * o) inline protected
returns the iterator at which the given element lies in the section container
This method may only be called if the element is indeed selected
get_section_index()
template<class TElem > int ug::MGSelector::get_section_index inline protected
grid_to_be_destroyed()
void ug::MGSelector::grid_to_be_destroyed (Grid * grid) virtual
Reimplemented from ug::ISelector.
References clear_lists(), ug::ISelector::grid(), ug::ISelector::grid_to_be_destroyed(), and m_pMultiGrid.
level_required()
void ug::MGSelector::level_required (int newSize) inline protected
References add_level(), and m_levels.
Referenced by assign_grid(), multigrid_changed(), and section_container().
multi_grid()
MultiGrid* ug::MGSelector::multi_grid () inline
Referenced by ug::AssignVerticalMasterAndSlaveStates(), ug::AdaptionSurfaceGridFunction< TDomain >::select_parents(), ug::SelectAssociatedGenealogy(), ug::SelectAssociatedSides(), ug::SelectChildrenOfSelectedShadowRimEdges(), ug::SelectChildrenOfSelectedShadowRimFaces(), ug::SelectChildrenOfSelectedShadowVertices(), ug::SelectElementsForTargetPartition(), ug::SelectSelectedRootElementsAsVSlaves(), and ug::SelectUnselectedRootElementsAsVMasters().
multigrid_changed()
void ug::MGSelector::multigrid_changed (const GridMessage_MultiGridChanged & gm) protected
callback for multigrid messages
References ug::GMMGCT_LEVEL_ADDED, level_required(), ug::GridMessage_MultiGridChanged::message_type(), and ug::GridMessage_MultiGridChanged::num_levels_in_grid().
Referenced by assign_grid().
num() [1/4]
template<class TElem > size_t ug::MGSelector::num inline
References num_levels().
Referenced by empty().
num() [2/4]
size_t ug::MGSelector::num () const inline
num() [3/4]
template<class TElem > size_t ug::MGSelector::num (int level) const inline
References num_levels().
Referenced by ug::HangingNodeRefiner_MultiGrid::num_marked_elems(), and ug::HangingNodeRefiner_MultiGrid::pre_refine().
num() [4/4]
size_t ug::MGSelector::num (int level) const inline
num_levels()
size_t ug::MGSelector::num_levels () const inline
Referenced by ug::AddTargetProcToDistInfos(), ug::AssignVerticalMasterAndSlaveStates(), clear(), ug::AdaptionSurfaceGridFunction< TDomain >::do_restrict(), get_grid_objects(), num(), ug::HangingNodeRefiner_MultiGrid::num_marked_elems(), ug::SelectAssociatedConstrainedElements(), ug::SelectAssociatedGenealogy(), ug::SelectChildrenOfSelectedShadowRimEdges(), ug::SelectChildrenOfSelectedShadowRimFaces(), and ug::SelectChildrenOfSelectedShadowVertices().
section_container() [1/2]
template<class TElem > Grid::traits< TElem >::SectionContainer & ug::MGSelector::section_container (int level) inline protected
returns the section container for the given type, subset and level
References level_required(), ug::MGSelector::Level::m_edges, ug::MGSelector::Level::m_faces, m_levels, ug::MGSelector::Level::m_vertices, and ug::MGSelector::Level::m_volumes.
Referenced by section_container().
section_container() [2/2]
template<class TElem > const Grid::traits< TElem >::SectionContainer & ug::MGSelector::section_container (int level) const inline protected
returns the const section container for the given type, subset and level
References ug::MGSelector::Level::m_edges, ug::MGSelector::Level::m_faces, m_levels, ug::MGSelector::Level::m_vertices, ug::MGSelector::Level::m_volumes, and section_container().
set_supported_elements()
void ug::MGSelector::set_supported_elements (uint shElements) inline
set the type of elements that shall be handled by the Selector.
Pass an or-combination of constants enumerated in SelectorElements.
See also
Selector::enable_element_support
References disable_element_support(), enable_element_support(), and ug::ISelector::m_supportedElements.
top_level()
size_t ug::MGSelector::top_level () const inline
Referenced by begin(), and end().
vertices_begin()
traits<Vertex>::level_iterator ug::MGSelector::vertices_begin (int level) inline
Referenced by ug::SelectAssociatedGenealogy().
vertices_end()
traits<Vertex>::level_iterator ug::MGSelector::vertices_end (int level) inline
Referenced by ug::SelectAssociatedGenealogy().
volumes_begin()
traits<Volume>::level_iterator ug::MGSelector::volumes_begin (int level) inline
Referenced by ug::SelectAssociatedGenealogy().
volumes_end()
traits<Volume>::level_iterator ug::MGSelector::volumes_end (int level) inline
Referenced by ug::SelectAssociatedGenealogy().
Member Data Documentation
m_aSharedEntryEDGE
AttachedEdgeList::AEntry ug::MGSelector::m_aSharedEntryEDGE protected
Referenced by add_level(), disable_element_support(), and enable_element_support().
m_aSharedEntryFACE
AttachedFaceList::AEntry ug::MGSelector::m_aSharedEntryFACE protected
Referenced by add_level(), disable_element_support(), and enable_element_support().
m_aSharedEntryVOL
AttachedVolumeList::AEntry ug::MGSelector::m_aSharedEntryVOL protected
Referenced by add_level(), disable_element_support(), and enable_element_support().
m_aSharedEntryVRT
AttachedVertexList::AEntry ug::MGSelector::m_aSharedEntryVRT protected
Referenced by add_level(), disable_element_support(), and enable_element_support().
m_callbackId
MessageHub::SPCallbackId ug::MGSelector::m_callbackId protected
Referenced by assign_grid(), and cleanup().
m_levels
LevelVec ug::MGSelector::m_levels protected
Referenced by add_level(), cleanup(), clear_lists(), disable_element_support(), enable_element_support(), get_grid_objects(), level_required(), and section_container().
m_pMultiGrid
MultiGrid* ug::MGSelector::m_pMultiGrid protected
Copy Constructor not yet implemented!
Referenced by add_to_list(), assign_grid(), cleanup(), disable_element_support(), enable_element_support(), erase_from_list(), grid_to_be_destroyed(), and MGSelector().
m_tmpVBegin
VertexIterator ug::MGSelector::m_tmpVBegin protected
m_tmpVEnd
VertexIterator ug::MGSelector::m_tmpVEnd protected
The documentation for this class was generated from the following files:
ugbase/lib_grid/tools/selector_multi_grid.h
ugbase/lib_grid/tools/selector_multi_grid.cpp
ugbase/lib_grid/tools/selector_multi_grid_impl.hpp