ug4: ug::FVPointSourceOrSink< dim, TData > Class Template Reference
ug::FVPointSourceOrSink< dim, TData > Class Template Reference
Base class for the point sources and sinks.
#include <fv1_sss.h>
Public Member Functions
template<typename TElem , typename TAAPos , typename TFVGeom >
bool corresponds_to (TElem *elem, Grid &grid, TAAPos &aaPos, const TFVGeom &geo, size_t co)
test whether a source/sink point corresponds to a given corner of the element
FVPointSourceOrSink (const MathVector< dim > &_point)
class constructor (with the default constructor for data)
FVPointSourceOrSink (const MathVector< dim > &_point, const TData &_data)
class constructor (with the copy constructor for data)
FVPointSourceOrSink (const std::vector< number > &_point)
class constructor (with the default constructor for data)
const MathVector< dim > & position ()
returns the point of the source/sink
Private Attributes
MathVector< dim > point
the point of the source/sink
Detailed Description
template<int dim, typename TData>
class ug::FVPointSourceOrSink< dim, TData >
Base class for the point sources and sinks.
Constructor & Destructor Documentation
FVPointSourceOrSink() [1/3]
template<int dim, typename TData > ug::FVPointSourceOrSink< dim, TData >::FVPointSourceOrSink (const MathVector< dim > & _point) inline
class constructor (with the default constructor for data)
Parameters
_point coordinates of the source/sink
FVPointSourceOrSink() [2/3]
template<int dim, typename TData > ug::FVPointSourceOrSink< dim, TData >::FVPointSourceOrSink (const MathVector< dim > & _point, const TData & _data) inline
class constructor (with the copy constructor for data)
Parameters
_point coordinates of the source/sink
_data the data to copy
FVPointSourceOrSink() [3/3]
template<int dim, typename TData > ug::FVPointSourceOrSink< dim, TData >::FVPointSourceOrSink (const std::vector< number > & _point) inline
class constructor (with the default constructor for data)
Parameters
_point coordinates of the source/sink
References dim, ug::FVPointSourceOrSink< dim, TData >::point, and UG_THROW.
Member Function Documentation
corresponds_to()
template<int dim, typename TData > template<typename TElem , typename TAAPos , typename TFVGeom > bool ug::FVPointSourceOrSink< dim, TData >::corresponds_to (TElem * elem, Grid & grid, TAAPos & aaPos, const TFVGeom & geo, size_t co)
test whether a source/sink point corresponds to a given corner of the element
Test whether a source/sink point corresponds to a given corner of the element. Note that TElem must specify the dimensionality of the element. Thus, GridObject is not a proper type for TElem. It should be at least Edge, Face, Volume or derived classes.
Parameters
elem the element
grid the grid
aaPos position of the vertices
geo FV geometry (initialized for 'elem')
co corner to get the contribution for
References ug::ContainsPoint(), ug::VecDot(), and ug::VecSubtract().
Referenced by ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::point_iterator< TElem, TAAPos, TFVGeom >::next_sss().
position()
template<int dim, typename TData > const MathVector<dim>& ug::FVPointSourceOrSink< dim, TData >::position () inline
returns the point of the source/sink
References ug::FVPointSourceOrSink< dim, TData >::point.
Referenced by ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::point_iterator< TElem, TAAPos, TFVGeom >::next_sss().
Member Data Documentation
point
template<int dim, typename TData > MathVector<dim> ug::FVPointSourceOrSink< dim, TData >::point private
the point of the source/sink
Referenced by ug::FVPointSourceOrSink< dim, TData >::FVPointSourceOrSink(), and ug::FVPointSourceOrSink< dim, TData >::position().
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/fv1_sss.h
ugbase/lib_disc/spatial_disc/disc_util/fv1_sss_impl.h