ug4: ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom > Class Template Reference
ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom > Class Template Reference
class of line source and sink iterator for a given scv
#include <fv1_sss.h>
Public Member Functions
bool is_over ()
checks whether we are at the end
line_iterator (master_type *sss, TElem *elem, Grid &grid, TAAPos &aaPos, const TFVGeom &geo, size_t co)
class constructor (sets the iterator to the beginnging of the list)
line_iterator (this_type &op)
copy constructor
line_sss_type * operator* ()
access operator
this_type & operator++ ()
moves to the next valid source or sink
this_type & rewind ()
moves the iterator to the beginning of the list
const MathVector< dim > & seg_end ()
the 2nd of the intersection points with the bnd of the scv
const MathVector< dim > & seg_start ()
the 1st of the intersection points with the bnd of the scv
Private Types
typedef FVSingularSourcesAndSinks< dim, TPointData, TLineData > master_type
typedef line_iterator< TElem, TAAPos, TFVGeom > this_type
Private Member Functions
void next_sss (size_t index, MathVector< dim > &ls, MathVector< dim > &le)
Private Attributes
TAAPos & m_aaPos
size_t m_co
TElem * m_elem
AABox< MathVector< dim > > m_elem_bbox
const TFVGeom & m_geo
Grid & m_grid
size_t m_index
index of the current source/sink
MathVector< dim > m_le
the 2nd of the intersection points with the bnd of the scv
MathVector< dim > m_ls
the 1st of the intersection points with the bnd of the scv
master_type * m_sss
Detailed Description
template<int dim, typename TPointData, typename TLineData = TPointData>
template<typename TElem, typename TAAPos, typename TFVGeom>
class ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >
class of line source and sink iterator for a given scv
Member Typedef Documentation
master_type
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > typedef FVSingularSourcesAndSinks<dim, TPointData, TLineData> ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::master_type private
this_type
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > typedef line_iterator<TElem, TAAPos, TFVGeom> ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::this_type private
Constructor & Destructor Documentation
line_iterator() [1/2]
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::line_iterator (master_type * sss, TElem * elem, Grid & grid, TAAPos & aaPos, const TFVGeom & geo, size_t co) inline
class constructor (sets the iterator to the beginnging of the list)
Parameters
elem the manager the element to find the sources and sinks for
grid the grid
aaPos position attachment for the grid
geo FV geometry for the element
co corner to check the sources and sinks for
References ug::CalculateBoundingBox(), ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_aaPos, ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_elem, ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_elem_bbox, ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_le, ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_ls, and ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::next_sss().
line_iterator() [2/2]
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::line_iterator (this_type & op) inline
copy constructor
Member Function Documentation
is_over()
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > bool ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::is_over () inline
checks whether we are at the end
References ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_index, ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_sss, and ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::num_lines().
next_sss()
template<int dim, typename TPointData , typename TLineData > template<typename TElem , typename TAAPos , typename TFVGeom > void ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::next_sss (size_t index, MathVector< dim > & ls, MathVector< dim > & le) private
Finds the proper point source or sink starting with a given index
Parameters
index index to start the search with
ls the 1st of the intersection points with the bnd of the scv
le the 2nd of the intersection points with the bnd of the scv
References ug::FVLineSourceOrSink< dim, TData >::corresponds_to(), ug::FVLineSourceOrSink< dim, TData >::from_position(), and ug::FVLineSourceOrSink< dim, TData >::to_position().
Referenced by ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::line_iterator(), and ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::operator++().
operator*()
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > line_sss_type* ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::operator* () inline
access operator
References ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::ListL, ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_index, and ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_sss.
operator++()
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > this_type& ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::operator++ () inline
moves to the next valid source or sink
References ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_index, ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_le, ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_ls, and ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::next_sss().
rewind()
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > this_type& ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::rewind () inline
moves the iterator to the beginning of the list
References ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_index.
seg_end()
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > const MathVector<dim>& ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::seg_end () inline
the 2nd of the intersection points with the bnd of the scv
References ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_le.
seg_start()
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > const MathVector<dim>& ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::seg_start () inline
the 1st of the intersection points with the bnd of the scv
References ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_ls.
Member Data Documentation
m_aaPos
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > TAAPos& ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_aaPos private
Referenced by ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::line_iterator().
m_co
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > size_t ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_co private
m_elem
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > TElem* ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_elem private
Referenced by ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::line_iterator().
m_elem_bbox
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > AABox<MathVector<dim> > ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_elem_bbox private
Referenced by ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::line_iterator().
m_geo
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > const TFVGeom& ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_geo private
m_grid
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > Grid& ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_grid private
m_index
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > size_t ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_index private
index of the current source/sink
Referenced by ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::is_over(), ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::operator*(), ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::operator++(), and ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::rewind().
m_le
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > MathVector<dim> ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_le private
the 2nd of the intersection points with the bnd of the scv
Referenced by ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::line_iterator(), ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::operator++(), and ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::seg_end().
m_ls
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > MathVector<dim> ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_ls private
the 1st of the intersection points with the bnd of the scv
Referenced by ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::line_iterator(), ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::operator++(), and ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::seg_start().
m_sss
template<int dim, typename TPointData , typename TLineData = TPointData> template<typename TElem , typename TAAPos , typename TFVGeom > master_type* ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::m_sss private
Referenced by ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::is_over(), and ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::line_iterator< TElem, TAAPos, TFVGeom >::operator*().
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/fv1_sss.h
ugbase/lib_disc/spatial_disc/disc_util/fv1_sss_impl.h