ug4: ug::ParallelHNodeAdjuster Class Reference
ug::ParallelHNodeAdjuster Class Reference
Makes sure that that marks are propagated over process interfaces.
#include <parallel_hnode_adjuster.h>
Public Member Functions
virtual void ref_marks_changed (IRefiner &ref, const std::vector< Vertex * > &vrts, const std::vector< Edge * > &edges, const std::vector< Face * > &faces, const std::vector< Volume * > &vols)
virtual ~ParallelHNodeAdjuster ()
Public Member Functions inherited from ug::IRefMarkAdjuster
virtual void coarsen_marks_changed (IRefiner &ref, const std::vector< Vertex * > &vrts, const std::vector< Edge * > &edges, const std::vector< Face * > &faces, const std::vector< Volume * > &vols)
virtual void enable (bool enable)
virtual bool enabled () const
IRefMarkAdjuster ()
virtual ~IRefMarkAdjuster ()
void enable_node_dependency_order_1 (bool bEnable)
enables or disables node-dependency-order-1.
bool node_dependency_order_1_enabled ()
enables or disables node-dependency-order-1.
Static Public Member Functions
static SPParallelHNodeAdjuster create ()
Private Attributes
pcl::InterfaceCommunicator< EdgeLayout > m_intfComEDGE
pcl::InterfaceCommunicator< FaceLayout > m_intfComFACE
pcl::InterfaceCommunicator< VertexLayout > m_intfComVRT
pcl::ProcessCommunicator m_procCom
Detailed Description
Makes sure that that marks are propagated over process interfaces.
Constructor & Destructor Documentation
~ParallelHNodeAdjuster()
virtual ug::ParallelHNodeAdjuster::~ParallelHNodeAdjuster () inline virtual
Member Function Documentation
create()
static SPParallelHNodeAdjuster ug::ParallelHNodeAdjuster::create () inline static
Referenced by ug::ParallelHangingNodeRefiner_MultiGrid::ParallelHangingNodeRefiner_MultiGrid().
ref_marks_changed()
void ug::ParallelHNodeAdjuster::ref_marks_changed (IRefiner & ref, const std::vector< Vertex * > & vrts, const std::vector< Edge * > & edges, const std::vector< Face * > & faces, const std::vector< Volume * > & vols) virtual
Reimplemented from ug::IRefMarkAdjuster.
References ug::ContainsInterfaceElem(), ug::Grid::distributed_grid_manager(), ug::IRefiner::grid(), ug::DistributedGridManager::grid_layout_map(), ug::INT_H_MASTER, ug::INT_H_SLAVE, ug::Grid::is_parallel(), ug::LIB_GRID, m_intfComEDGE, m_intfComFACE, m_intfComVRT, pcl::OneProcTrue(), ug::RM_ANISOTROPIC, ug::RM_REFINE, UG_ASSERT, and UG_DLOG.
Member Data Documentation
m_intfComEDGE
pcl::InterfaceCommunicator<EdgeLayout> ug::ParallelHNodeAdjuster::m_intfComEDGE private
Referenced by ref_marks_changed().
m_intfComFACE
pcl::InterfaceCommunicator<FaceLayout> ug::ParallelHNodeAdjuster::m_intfComFACE private
Referenced by ref_marks_changed().
m_intfComVRT
pcl::InterfaceCommunicator<VertexLayout> ug::ParallelHNodeAdjuster::m_intfComVRT private
Referenced by ref_marks_changed().
m_procCom
pcl::ProcessCommunicator ug::ParallelHNodeAdjuster::m_procCom private
The documentation for this class was generated from the following files:
ugbase/lib_grid/parallelization/parallel_refinement/parallel_hnode_adjuster.h
ugbase/lib_grid/parallelization/parallel_refinement/parallel_hnode_adjuster.cpp