ug4: ug::LocalSchurComplement< TAlgebra > Class Template Reference
ug::LocalSchurComplement< TAlgebra > Class Template Reference
operator implementation of the local Schur complement
#include <feti.h>
Classes
struct StepConv
Public Types
typedef TAlgebra algebra_type
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::IOperator< TAlgebra::vector_type, TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual void apply (vector_type &f, const vector_type &u)
virtual void apply_sub (vector_type &f, const vector_type &u)
solves the system
void clear_total_itercnt_of_inner_solvers ()
int get_total_itercnt_of_inner_solvers ()
void init (const vector_type &u)
implementation of the operator for the solution dependent initialization.
virtual void init ()
initializes the solver for operator A
LocalSchurComplement ()
constructor
virtual const char * name () const
name of solver
void print_statistic_of_inner_solver (bool bPrintOnlyAverages)
prints some convergence statistic of inner solvers
void set_dirichlet_solver (SmartPtr< ILinearOperatorInverse< vector_type > > dirichletSolver)
sets a sequential Dirichlet solver
void set_feti_layouts (FetiLayouts< algebra_type > &fetiLayouts)
sets the primal layouts
void set_matrix (SmartPtr< MatrixOperator< matrix_type, vector_type > > A)
set original matrix from which the local Schur complement is constructed
void set_statistic_type (std::string type)
sets statistic slot where next iterate should be counted
virtual ~LocalSchurComplement ()
Public Member Functions inherited from ug::ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type >
virtual void prepare (TAlgebra::vector_type &u)
default implementation for IOperator interface
virtual ~ILinearOperator ()
virtual destructor
Public Member Functions inherited from ug::IOperator< TAlgebra::vector_type, TAlgebra::vector_type >
virtual ~IOperator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
DebugWritingObject ()
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Attributes
int m_applyCnt
std::map< std::string, std::vector< StepConv > > m_mvStepConv
matrix_type * m_pDirichletMatrix
FetiLayouts< algebra_type > * m_pFetiLayouts
matrix_type * m_pMatrix
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spDirichletOperator
SmartPtr< ILinearOperatorInverse< vector_type > > m_spDirichletSolver
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spOperator
std::string m_statType
int m_totalIterCntOfInnerSolvers
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Additional Inherited Members
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
virtual void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void write_debug (const vector_type &vec, std::string filename)
virtual void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
Detailed Description
template<typename TAlgebra>
class ug::LocalSchurComplement< TAlgebra >
operator implementation of the local Schur complement
This operator is the application of the local Schur complement \(S_{\Delta}^{i}\). The underlying matrix must have at least two layouts. The first layout, layout level 0, will be used to describe subdomain internal interfaces (i.e. "pure" processor interfaces), all other layouts are used to identify the boundary, layout level 1: \(\Delta \) (edges of subdomains), layout level 2: \(\Pi \) (vertices of subdomains, a.k.a. "cross points") - will be constructed here, and the Schur complement is build w.r.t. to these variables.
Member Typedef Documentation
template<typename TAlgebra> typedef TAlgebra ug::LocalSchurComplement< TAlgebra >::algebra_type
template<typename TAlgebra> typedef TAlgebra::matrix_type ug::LocalSchurComplement< TAlgebra >::matrix_type
template<typename TAlgebra> typedef TAlgebra::vector_type ug::LocalSchurComplement< TAlgebra >::vector_type
Constructor & Destructor Documentation
template<typename TAlgebra > ug::LocalSchurComplement< TAlgebra >::LocalSchurComplement ()
constructor
References ug::LocalSchurComplement< TAlgebra >::init().
template<typename TAlgebra> virtual ug::LocalSchurComplement< TAlgebra >::~LocalSchurComplement () inline virtual
Member Function Documentation
template<typename TAlgebra > void ug::LocalSchurComplement< TAlgebra >::apply (vector_type & f, const vector_type & u) virtual
applies the Schur complement built from matrix operator set via 'set_matrix()' to 'u' and returns the result 'f := S times u'
Implements ug::ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type >.
References ug::LocalSchurComplement< TAlgebra >::apply_sub(), ug::DebugWritingObject< TAlgebra >::debug_writer(), FETI_PROFILE_BEGIN, ug::LocalSchurComplement< TAlgebra >::StepConv::lastDef3b, ug::LocalSchurComplement< TAlgebra >::m_applyCnt, ug::LocalSchurComplement< TAlgebra >::m_mvStepConv, ug::LocalSchurComplement< TAlgebra >::m_pDirichletMatrix, ug::LocalSchurComplement< TAlgebra >::m_pFetiLayouts, ug::LocalSchurComplement< TAlgebra >::m_spDirichletOperator, ug::LocalSchurComplement< TAlgebra >::m_spDirichletSolver, ug::LocalSchurComplement< TAlgebra >::m_spOperator, ug::LocalSchurComplement< TAlgebra >::m_statType, ug::LocalSchurComplement< TAlgebra >::name(), ug::LocalSchurComplement< TAlgebra >::StepConv::numIter3b, pcl::ProcRank(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, SPNULL, UG_LOG_ALL_PROCS, UG_THROW, ug::FetiLayouts< TAlgebra >::vec_scale_append_on_dual(), ug::FetiLayouts< TAlgebra >::vec_set_on_dual(), and ug::FetiLayouts< TAlgebra >::vec_use_intra_sd_communication().
Referenced by ug::FETISolver< TAlgebra >::apply_M_inverse(), ug::LocalSchurComplement< TAlgebra >::apply_sub(), and ug::LocalSchurComplement< TAlgebra >::init().
template<typename TAlgebra > void ug::LocalSchurComplement< TAlgebra >::apply_sub (vector_type & f, const vector_type & u) virtual
solves the system
Implements ug::ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type >.
References ug::LocalSchurComplement< TAlgebra >::apply(), FETI_PROFILE_BEGIN, and ug::LocalSchurComplement< TAlgebra >::print_statistic_of_inner_solver().
Referenced by ug::LocalSchurComplement< TAlgebra >::apply().
template<typename TAlgebra> void ug::LocalSchurComplement< TAlgebra >::clear_total_itercnt_of_inner_solvers () inline
template<typename TAlgebra> int ug::LocalSchurComplement< TAlgebra >::get_total_itercnt_of_inner_solvers () inline
template<typename TAlgebra> void ug::LocalSchurComplement< TAlgebra >::init (const vector_type & u) inline virtual
implementation of the operator for the solution dependent initialization.
Implements ug::ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type >.
Referenced by ug::LocalSchurComplement< algebra_type >::init(), and ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra > void ug::LocalSchurComplement< TAlgebra >::init () virtual
initializes the solver for operator A
This method must be called, before the apply() method can be invoked. It has to be called each time, when the matrix has been replaced. A deep copy of the matrix is then constructed and in this copy the rows belonging to the \(\Delta\) and \(\Pi\) unknowns are set to identity rows. This matrix is used in the solution of the local dirichlet problem.
Implements ug::ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type >.
References ug::LocalSchurComplement< TAlgebra >::apply(), ug::LocalSchurComplement< TAlgebra >::m_applyCnt, ug::LocalSchurComplement< TAlgebra >::m_pDirichletMatrix, ug::LocalSchurComplement< TAlgebra >::m_pFetiLayouts, ug::LocalSchurComplement< TAlgebra >::m_pMatrix, ug::LocalSchurComplement< TAlgebra >::m_spDirichletOperator, ug::LocalSchurComplement< TAlgebra >::m_spDirichletSolver, ug::LocalSchurComplement< TAlgebra >::m_spOperator, ug::FetiLayouts< TAlgebra >::mat_set_dirichlet_on_dual(), ug::FetiLayouts< TAlgebra >::mat_set_dirichlet_on_primal(), ug::FetiLayouts< TAlgebra >::mat_use_intra_sd_communication(), UG_THROW, and ug::DebugWritingObject< TAlgebra >::write_debug().
Referenced by ug::LocalSchurComplement< TAlgebra >::LocalSchurComplement().
template<typename TAlgebra> virtual const char* ug::LocalSchurComplement< TAlgebra >::name () const inline virtual
name of solver
Referenced by ug::LocalSchurComplement< TAlgebra >::apply().
template<typename TAlgebra > void ug::LocalSchurComplement< TAlgebra >::print_statistic_of_inner_solver (bool bPrintOnlyAverages)
prints some convergence statistic of inner solvers
References pcl::ProcessCommunicator::allreduce(), ug::LocalSchurComplement< TAlgebra >::m_mvStepConv, ug::LocalSchurComplement< TAlgebra >::m_totalIterCntOfInnerSolvers, pcl::NumProcs(), PCL_DT_DOUBLE, PCL_DT_INT, PCL_RO_MAX, PCL_RO_MIN, PCL_RO_SUM, ug::PrimalSubassembledMatrixInverse< TAlgebra >::PrimalSubassembledMatrixInverse(), and UG_LOG.
Referenced by ug::LocalSchurComplement< TAlgebra >::apply_sub().
template<typename TAlgebra> void ug::LocalSchurComplement< TAlgebra >::set_dirichlet_solver (SmartPtr< ILinearOperatorInverse< vector_type > > dirichletSolver) inline
sets a sequential Dirichlet solver
This method sets the Dirichlet Solver that is used to invert the inner matrix \(A_{II}\)
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra> void ug::LocalSchurComplement< TAlgebra >::set_feti_layouts (FetiLayouts< algebra_type > & fetiLayouts) inline
sets the primal layouts
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra> void ug::LocalSchurComplement< TAlgebra >::set_matrix (SmartPtr< MatrixOperator< matrix_type, vector_type > > A) inline
set original matrix from which the local Schur complement is constructed
Using this method, the original matrix A is set. Given the matrix in the form \(A = \sum\limits_{p=1}^{N} A^{(p)}\) in additive form, with
\begin{align*} A^{(p)} \begin{pmatrix} A_{II}^{(p)} & A_{I \Delta}^{(p)} & A_{I \Pi}^{(p)} \\ A_{\Delta I}^{(p)} & A_{\Delta \Delta}^{(p)} & A_{\Delta \Pi}^{(p)} \\ A_{\Pi I}^{(p)} & A_{\Pi \Delta}^{(p)} & A_{\Pi \Pi}^{(p)} \end{pmatrix} \end{align*}
the local Schur complement is the processwise application of the operator
\begin{align*} S_{\Delta \Delta} = A_{\Delta \Delta} - \begin{pmatrix} A_{I \Delta}^T & A_{\Pi \Delta}^T \end{pmatrix} \begin{pmatrix} A_{II} & A_{I \Pi} \\ A_{\Pi I} & A_{\Pi \Pi} \end{pmatrix}^{-1} \begin{pmatrix} A_{I \Delta} \\ A_{\Pi \Delta} \end{pmatrix} * \end{align*}
Referenced by ug::FETISolver< TAlgebra >::init().
template<typename TAlgebra> void ug::LocalSchurComplement< TAlgebra >::set_statistic_type (std::string type) inline
sets statistic slot where next iterate should be counted
Referenced by ug::FETISolver< TAlgebra >::apply_return_defect().
Member Data Documentation
template<typename TAlgebra> int ug::LocalSchurComplement< TAlgebra >::m_applyCnt protected
Referenced by ug::LocalSchurComplement< TAlgebra >::apply(), and ug::LocalSchurComplement< TAlgebra >::init().
template<typename TAlgebra> std::map<std::string, std::vector<StepConv> > ug::LocalSchurComplement< TAlgebra >::m_mvStepConv protected
Referenced by ug::LocalSchurComplement< TAlgebra >::apply(), and ug::LocalSchurComplement< TAlgebra >::print_statistic_of_inner_solver().
template<typename TAlgebra> matrix_type* ug::LocalSchurComplement< TAlgebra >::m_pDirichletMatrix protected
Referenced by ug::LocalSchurComplement< TAlgebra >::apply(), and ug::LocalSchurComplement< TAlgebra >::init().
template<typename TAlgebra> FetiLayouts<algebra_type>* ug::LocalSchurComplement< TAlgebra >::m_pFetiLayouts protected
Referenced by ug::LocalSchurComplement< TAlgebra >::apply(), and ug::LocalSchurComplement< TAlgebra >::init().
template<typename TAlgebra> matrix_type* ug::LocalSchurComplement< TAlgebra >::m_pMatrix protected
Referenced by ug::LocalSchurComplement< TAlgebra >::init().
template<typename TAlgebra> SmartPtr<MatrixOperator<matrix_type, vector_type> > ug::LocalSchurComplement< TAlgebra >::m_spDirichletOperator protected
Referenced by ug::LocalSchurComplement< TAlgebra >::apply(), and ug::LocalSchurComplement< TAlgebra >::init().
template<typename TAlgebra> SmartPtr<ILinearOperatorInverse<vector_type> > ug::LocalSchurComplement< TAlgebra >::m_spDirichletSolver protected
Referenced by ug::LocalSchurComplement< TAlgebra >::apply(), and ug::LocalSchurComplement< TAlgebra >::init().
template<typename TAlgebra> SmartPtr<MatrixOperator<matrix_type,vector_type> > ug::LocalSchurComplement< TAlgebra >::m_spOperator protected
Referenced by ug::LocalSchurComplement< TAlgebra >::apply(), and ug::LocalSchurComplement< TAlgebra >::init().
template<typename TAlgebra> std::string ug::LocalSchurComplement< TAlgebra >::m_statType protected
Referenced by ug::LocalSchurComplement< TAlgebra >::apply().
template<typename TAlgebra> int ug::LocalSchurComplement< TAlgebra >::m_totalIterCntOfInnerSolvers protected
Referenced by ug::LocalSchurComplement< TAlgebra >::print_statistic_of_inner_solver().
The documentation for this class was generated from the following files:
ugbase/lib_algebra/operator/linear_solver/feti.h
ugbase/lib_algebra/operator/linear_solver/feti.cpp