ug4: ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV Class Reference
ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV Class Reference
sub control volume structure
#include <fv1ib_geom.h>
Public Member Functions
number detJ () const
Determinant of Jacobian in integration point.
const MathVector< worldDim > & global_corner (size_t co) const
return global corner number i
const MathVector< worldDim > & global_grad (size_t sh) const
value of global gradient of shape function i in integration point
const MathVector< worldDim > * global_grad_vector () const
vector of global gradients in ip point
const MathVector< worldDim > & global_ip () const
global integration point
const MathMatrix< worldDim, dim > & JTInv () const
Transposed Inverse of Jacobian in integration point.
const MathVector< dim > & local_corner (size_t co) const
return local corner number i
const MathVector< dim > & local_grad (size_t sh) const
value of local gradient of shape function i in integration point
const MathVector< dim > * local_grad_vector () const
vector of local gradients in ip point
const MathVector< dim > & local_ip () const
local integration point of scv
size_t node_id () const
node id that this scv is associated to
size_t num_corners () const
number of corners, that bound the scv
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shape functions
SCV ()
number shape (size_t sh) const
value of shape function i in integration point
const number * shape_vector () const
vector of shape functions in ip point
number volume () const
volume of scv
Static Public Attributes
static const size_t numCo = traits::NumCornersOfSCV
Number of corners of scv.
Private Attributes
number detj
MathMatrix< worldDim, dim > JtInv
size_t nodeId
size_t numSH
MathVector< worldDim > vGlobalGrad [maxNSH]
MathVector< worldDim > vGloPos [numCo]
MathVector< dim > vLocalGrad [maxNSH]
MathVector< dim > vLocPos [numCo]
MidID vMidID [numCo]
number Vol
number vShape [maxNSH]
Friends
class DimFV1IBGeometry< dim, worldDim >
Detailed Description
template<int TDim, int TWorldDim = TDim>
class ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV
sub control volume structure
Constructor & Destructor Documentation
SCV()
template<int TDim, int TWorldDim = TDim> ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::SCV () inline
Member Function Documentation
detJ()
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::detJ () const inline
Determinant of Jacobian in integration point.
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::detj.
global_corner()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::global_corner (size_t co) const inline
return global corner number i
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::num_corners(), UG_ASSERT, and ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vGloPos.
global_grad()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::global_grad (size_t sh) const inline
value of global gradient of shape function i in integration point
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::num_sh(), UG_ASSERT, and ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vGlobalGrad.
global_grad_vector()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>* ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::global_grad_vector () const inline
vector of global gradients in ip point
global_ip()
template<int TDim, int TWorldDim = TDim> const MathVector<worldDim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::global_ip () const inline
global integration point
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vGloPos.
JTInv()
template<int TDim, int TWorldDim = TDim> const MathMatrix<worldDim,dim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::JTInv () const inline
Transposed Inverse of Jacobian in integration point.
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::JtInv.
local_corner()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::local_corner (size_t co) const inline
return local corner number i
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::num_corners(), UG_ASSERT, and ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vLocPos.
local_grad()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::local_grad (size_t sh) const inline
value of local gradient of shape function i in integration point
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::num_sh(), UG_ASSERT, and ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vLocalGrad.
local_grad_vector()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>* ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::local_grad_vector () const inline
vector of local gradients in ip point
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vLocalGrad.
local_ip()
template<int TDim, int TWorldDim = TDim> const MathVector<dim>& ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::local_ip () const inline
local integration point of scv
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vLocPos.
node_id()
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::node_id () const inline
node id that this scv is associated to
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::nodeId.
num_corners()
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::num_corners () const inline
number of corners, that bound the scv
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::numCo.
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::global_corner(), and ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::local_corner().
num_ip()
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::num_ip () const inline
number of integration points
References ug::DimFV1IBGeometry< TDim, TWorldDim >::nip.
num_sh()
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::num_sh () const inline
number of shape functions
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::numSH.
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::global_grad(), and ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::local_grad().
shape()
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::shape (size_t sh) const inline
value of shape function i in integration point
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vShape.
shape_vector()
template<int TDim, int TWorldDim = TDim> const number* ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::shape_vector () const inline
vector of shape functions in ip point
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vShape.
volume()
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::volume () const inline
volume of scv
References ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::Vol.
Friends And Related Function Documentation
DimFV1IBGeometry< dim, worldDim >
template<int TDim, int TWorldDim = TDim> friend class DimFV1IBGeometry< dim, worldDim > friend
Member Data Documentation
detj
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::detj private
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::detJ().
JtInv
template<int TDim, int TWorldDim = TDim> MathMatrix<worldDim,dim> ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::JtInv private
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::JTInv().
nodeId
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::nodeId private
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::node_id().
numCo
template<int TDim, int TWorldDim = TDim> const size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::numCo = traits::NumCornersOfSCV static
Number of corners of scv.
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::num_corners().
numSH
template<int TDim, int TWorldDim = TDim> size_t ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::numSH private
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::num_sh().
vGlobalGrad
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vGlobalGrad[maxNSH] private
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::global_grad().
vGloPos
template<int TDim, int TWorldDim = TDim> MathVector<worldDim> ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vGloPos[numCo] private
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::global_corner(), and ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::global_ip().
vLocalGrad
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vLocalGrad[maxNSH] private
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::local_grad(), and ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::local_grad_vector().
vLocPos
template<int TDim, int TWorldDim = TDim> MathVector<dim> ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vLocPos[numCo] private
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::local_corner(), and ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::local_ip().
vMidID
template<int TDim, int TWorldDim = TDim> MidID ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vMidID[numCo] private
Vol
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::Vol private
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::volume().
vShape
template<int TDim, int TWorldDim = TDim> number ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::vShape[maxNSH] private
Referenced by ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::shape(), and ug::DimFV1IBGeometry< TDim, TWorldDim >::SCV::shape_vector().
The documentation for this class was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv1ib_geom.h