ug4: ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule > Class Template Reference
ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule > Class Template Reference
#include <fe_geom.h>
Public Types
typedef TQuadratureRule quad_rule_type
type of quadrature rule
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
type of reference element
typedef TTrialSpace trial_space_type
type of trial space
Public Member Functions
FEGeometry ()
Constructor.
const MathVector< worldDim > & global_grad (size_t ip, size_t sh) const
global gradient at ip
const MathVector< worldDim > & global_ip (size_t ip) const
global integration point
const MathVector< worldDim > * global_ips () const
global integration point
const MathVector< dim > & local_grad (size_t ip, size_t sh) const
local gradient at ip
const MathVector< dim > & local_ip (size_t ip) const
local integration point
const MathVector< dim > * local_ips () const
local integration point
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shape functions
number shape (size_t ip, size_t sh) const
shape function at ip
void update (GridObject *pElem, const MathVector< worldDim > *vCorner)
update Geometry for corners
void update (GridObject *pElem, const MathVector< worldDim > *vCorner, const LFEID &lfeID, size_t orderQuad)
update Geometry for corners
void update (GridObject *pElem, const MathVector< worldDim > *vCorner, const LFEID &lfeID)
void update_local (ReferenceObjectID roid, const LFEID &lfeID, size_t orderQuad)
update Geometry for roid
void update_local (ReferenceObjectID roid, const LFEID &lfeID)
number weight (size_t ip) const
weight for integration point
Static Public Attributes
static const int dim = ref_elem_type::dim
reference element dimension
static const size_t nip = quad_rule_type::nip
number of integration points
static const size_t nsh = trial_space_type::nsh
number of shape functions
static const bool staticLocalData = true
flag indicating if local data may change
static const int worldDim = TWorldDim
world dimension
Protected Attributes
ReferenceMapping< ref_elem_type, worldDim > m_mapping
reference mapping
TElem * m_pElem
current element
const quad_rule_type & m_rQuadRule
Quadrature rule.
const trial_space_type & m_rTrialSpace
Quadrature rule.
number m_vDetJ [nip]
determinate of transformation at ip
MathVector< worldDim > m_vIPGlobal [nip]
global integration points
MathMatrix< worldDim, dim > m_vJTInv [nip]
jacobian of transformation at ip
MathVector< worldDim > m_vvGradGlobal [nip][nsh]
local gradient evaluated at ip
MathVector< dim > m_vvGradLocal [nip][nsh]
global gradient evaluated at ip
number m_vvShape [nip][nsh]
shape functions evaluated at ip
Member Typedef Documentation
quad_rule_type
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > typedef TQuadratureRule ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::quad_rule_type
type of quadrature rule
ref_elem_type
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > typedef reference_element_traits<TElem>::reference_element_type ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::ref_elem_type
type of reference element
trial_space_type
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > typedef TTrialSpace ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::trial_space_type
type of trial space
Constructor & Destructor Documentation
FEGeometry()
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::FEGeometry ()
Constructor.
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_rQuadRule, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_rTrialSpace, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvGradLocal, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvShape, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::nip, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::nsh, and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update_local().
Member Function Documentation
global_grad()
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const MathVector<worldDim>& ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::global_grad (size_t ip, size_t sh) const inline
global gradient at ip
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvGradGlobal, UG_ASSERT, and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update_local().
global_ip()
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const MathVector<worldDim>& ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::global_ip (size_t ip) const inline
global integration point
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vIPGlobal, and UG_ASSERT.
global_ips()
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const MathVector<worldDim>* ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::global_ips () const inline
global integration point
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vIPGlobal.
local_grad()
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const MathVector<dim>& ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::local_grad (size_t ip, size_t sh) const inline
local gradient at ip
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvGradLocal, and UG_ASSERT.
local_ip()
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const MathVector<dim>& ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::local_ip (size_t ip) const inline
local integration point
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_rQuadRule.
local_ips()
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const MathVector<dim>* ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::local_ips () const inline
local integration point
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_rQuadRule.
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
num_ip()
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > size_t ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::num_ip () const inline
number of integration points
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::nip.
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::detJ(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_grad(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_grad_vector(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_ip(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::JTInv(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_grad(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_grad_vector(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_ip(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::shape(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::shape_vector(), and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::weight().
num_sh()
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > size_t ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::num_sh () const inline
number of shape functions
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::nsh.
Referenced by ug::DimFEGeometry< TWorldDim, TRefDim >::BF::global_grad(), and ug::DimFEGeometry< TWorldDim, TRefDim >::BF::local_grad().
shape()
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > number ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::shape (size_t ip, size_t sh) const inline
shape function at ip
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvShape, and UG_ASSERT.
update() [1/3]
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > void ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update (GridObject * pElem, const MathVector< worldDim > * vCorner) inline
update Geometry for corners
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_rQuadRule.
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update(), ug::DimFEGeometry< TWorldDim, TRefDim >::update(), and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update_local().
update() [2/3]
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > void ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update (GridObject * pElem, const MathVector< worldDim > * vCorner, const LFEID & lfeID, size_t orderQuad)
update Geometry for corners
References ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::local_ips(), ug::ReferenceMapping< TRefElem, TWorldDim >::local_to_global(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_mapping, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_pElem, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_rQuadRule, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vDetJ, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vIPGlobal, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vJTInv, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvGradGlobal, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvGradLocal, ug::MatVecMult(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::nip, ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::nsh, UG_ASSERT, and ug::ReferenceMapping< TRefElem, TWorldDim >::update().
update() [3/3]
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > void ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update (GridObject * pElem, const MathVector< worldDim > * vCorner, const LFEID & lfeID) inline
References ug::LFEID::order(), and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
update_local() [1/2]
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > void ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update_local (ReferenceObjectID roid, const LFEID & lfeID, size_t orderQuad)
update Geometry for roid
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_rQuadRule, UG_THROW, and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::FEGeometry(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::global_grad(), ug::DimFEGeometry< TWorldDim, TRefDim >::global_grad(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update_local(), and ug::DimFEGeometry< TWorldDim, TRefDim >::update_local().
update_local() [2/2]
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > void ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update_local (ReferenceObjectID roid, const LFEID & lfeID) inline
References ug::LFEID::order(), and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update_local().
weight()
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > number ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::weight (size_t ip) const inline
weight for integration point
References ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_rQuadRule, and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vDetJ.
Member Data Documentation
dim
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const int ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::dim = ref_elem_type::dim static
reference element dimension
m_mapping
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > ReferenceMapping<ref_elem_type, worldDim> ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_mapping protected
reference mapping
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
m_pElem
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > TElem* ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_pElem protected
current element
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
m_rQuadRule
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const quad_rule_type& ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_rQuadRule protected
Quadrature rule.
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::FEGeometry(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::local_ip(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::local_ips(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update_local(), and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::weight().
m_rTrialSpace
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const trial_space_type& ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_rTrialSpace protected
Quadrature rule.
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::FEGeometry().
m_vDetJ
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > number ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vDetJ[nip] protected
determinate of transformation at ip
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::weight(), and ug::DimFEGeometry< TWorldDim, TRefDim >::weight().
m_vIPGlobal
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > MathVector<worldDim> ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vIPGlobal[nip] protected
global integration points
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::global_ip(), ug::DimFEGeometry< TWorldDim, TRefDim >::global_ip(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::global_ips(), ug::DimFEGeometry< TWorldDim, TRefDim >::global_ips(), and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
m_vJTInv
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > MathMatrix<worldDim,dim> ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vJTInv[nip] protected
jacobian of transformation at ip
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
m_vvGradGlobal
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > MathVector<worldDim> ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvGradGlobal[nip][nsh] protected
local gradient evaluated at ip
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::global_grad(), ug::DimFEGeometry< TWorldDim, TRefDim >::global_grad(), and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
m_vvGradLocal
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > MathVector<dim> ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvGradLocal[nip][nsh] protected
global gradient evaluated at ip
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::FEGeometry(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::local_grad(), ug::DimFEGeometry< TWorldDim, TRefDim >::local_grad(), and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
m_vvShape
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > number ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::m_vvShape[nip][nsh] protected
shape functions evaluated at ip
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::FEGeometry(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::shape(), and ug::DimFEGeometry< TWorldDim, TRefDim >::shape().
nip
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const size_t ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::nip = quad_rule_type::nip static
number of integration points
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::FEGeometry(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::num_ip(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_ip(), and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
nsh
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const size_t ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::nsh = trial_space_type::nsh static
number of shape functions
Referenced by ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::FEGeometry(), ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::num_sh(), ug::DimFEGeometry< TWorldDim, TRefDim >::BF::num_sh(), and ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::update().
staticLocalData
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const bool ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::staticLocalData = true static
flag indicating if local data may change
worldDim
template<typename TElem , int TWorldDim, typename TTrialSpace , typename TQuadratureRule > const int ug::FEGeometry< TElem, TWorldDim, TTrialSpace, TQuadratureRule >::worldDim = TWorldDim static
world dimension
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/disc_util/fe_geom.h
ugbase/lib_disc/spatial_disc/disc_util/fe_geom_impl.h