ug4: ug::ILinearIterator< X, Y > Class Template Reference
ug::ILinearIterator< X, Y > Class Template Reference abstract
describes a linear iterator
#include <linear_iterator.h>
Public Types
typedef Y codomain_function_type
Range space.
typedef X domain_function_type
Domain space.
Public Member Functions
virtual bool apply (Y &c, const X &d)=0
compute new correction c = B*d
virtual bool apply_update_defect (Y &c, X &d)=0
compute new correction c = B*d and update defect d := d - A*c
virtual SmartPtr< ILinearIterator< X, Y > > clone ()=0
clone
virtual std::string config_string () const
SmartPtr< IDamping< X, Y > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< X, Y > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< Y, X > > J, const Y &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< Y, X > > L)=0
initialize for linear operator L
virtual const char * name () const =0
returns the name of iterator
void set_damp (SmartPtr< IDamping< X, Y > > spScaling)
sets a scaling for the correction
void set_damp (number factor)
sets the damping to a constant factor
virtual bool supports_parallel () const =0
returns if parallel solving is supported
virtual ~ILinearIterator ()
virtual destructor
Protected Attributes
SmartPtr< IDamping< X, Y > > m_spDamping
the scaling
Detailed Description
template<typename X, typename Y = X>
class ug::ILinearIterator< X, Y >
describes a linear iterator
This class is the base class for all linear iterators. Iterators (also called preconditioners) are used in iterative schemes when solving a linear system. Usually, a linear problem like L*u = f is intended to be solved. This is done in an iterative way by performing an iteration of
start: compute d := f - L*u iterate: - c := B*d (compute correction)
u := u + c (update solution)
d := d - L*c (update defect)
This iterator class describes the application of B in the scheme above. The application has been split up into two parts.
init(L, u) or init(L): These methods initialize the iterator and one of these methods has to be called before any of the apply methods can be used. Passing the linear operator indicates that this operator is used as underlying for the iterator.
apply or apply_return_defect: These methods are used to compute the correction (and to update the defect at the same time). Note, that these methods can only be called when the iterator has been initialized.
This splitting has been made, since initialization may be computationally expensive. Thus, the user of this class has the choice when to call this initialization. E.g. when the operator is applied several times the init of the iterator is only needed once.
Template Parameters
X Domain space function
Y Range space function
Member Typedef Documentation
template<typename X, typename Y = X> typedef Y ug::ILinearIterator< X, Y >::codomain_function_type
Range space.
template<typename X, typename Y = X> typedef X ug::ILinearIterator< X, Y >::domain_function_type
Domain space.
Constructor & Destructor Documentation
template<typename X, typename Y = X> virtual ug::ILinearIterator< X, Y >::~ILinearIterator () inline virtual
virtual destructor
template<typename X, typename Y = X> ug::ILinearIterator< X, Y >::ILinearIterator () inline
constructor
template<typename X, typename Y = X> ug::ILinearIterator< X, Y >::ILinearIterator (const ILinearIterator< X, Y > & parent) inline
copy constructor
Member Function Documentation
template<typename X, typename Y = X> virtual bool ug::ILinearIterator< X, Y >::apply (Y & c, const X & d) pure virtual
compute new correction c = B*d
This method applies the iterator operator, i.e. c = B*d. The domain function d remains unchanged. Note, that this method can always be implemented by creating a copy of d and calling apply_update_defect with this copy.
Parameters
[in] d defect
[out] c correction
Returns
bool success flag
Implemented in ug::FETISolver< TAlgebra >, ug::PrimalSubassembledMatrixInverse< TAlgebra >, ug::PrimalSubassembledMatrixInverse< algebra_type >, ug::LU< TAlgebra >, ug::IPreconditioner< TAlgebra >, ug::IPreconditioner< ug::CPUAlgebra >, ug::IPreconditioner< algebra_type >, ug::Jacobi< TAlgebra >, ug::AgglomeratingBase< IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >, TAlgebra >, ug::AgglomeratingBase< ILinearIterator< TAlgebra::vector_type >, TAlgebra >, ug::AgglomeratingBase< IPreconditioner< TAlgebra >, TAlgebra >, ug::AutoLinearSolver< TVector >, ug::DebugIterator< TAlgebra >, ug::LinearIteratorSum< X, Y >, ug::IExternalSolver< TAlgebra >, ug::ILinearOperatorInverse< X, Y >, ug::ILinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::ILinearOperatorInverse< vector_type >, ug::ILinearOperatorInverse< vector_type, vector_type >, ug::ILinearOperatorInverse< X >, ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >, ug::ILinearOperatorInverse< algebra_type::vector_type, algebra_type::vector_type >, ug::ILinearOperatorInverse< TVector >, ug::IPreconditionedLinearOperatorInverse< X >, ug::IPreconditionedLinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::IPreconditionedLinearOperatorInverse< vector_type >, ug::IPreconditionedLinearOperatorInverse< TVector >, ug::IProjGaussSeidel< TDomain, TAlgebra >, ug::OperatorInverseIterator< TAlgebra >, ug::LinearIteratorProduct< X, Y >, ug::ITransformingIteration< TAlgebra, TDerived >, ug::ITransformingIteration< TAlgebra, AssembledTransformingSmoother< TDomain, TAlgebra > >, ug::IMatrixOperatorInverse< M, X, Y >, ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >, ug::CombinedLinearIterator< X, Y >, and ug::AnalyzingSolver< M, X, Y >.
template<typename X, typename Y = X> virtual bool ug::ILinearIterator< X, Y >::apply_update_defect (Y & c, X & d) pure virtual
compute new correction c = B*d and update defect d := d - A*c
This method applies the inverse operator, i.e. c = B*d. The domain function d is changed in the way, that the defect d := d - A*c is returned in the function. This is always useful, when the iterating algorithm can (or must) update the defect during computation (this is e.g. the case for the geometric multigrid method). Note, that this method can always be implemented by calling apply and then computing d := d - A*c.
Parameters
[in,out] d defect
[out] u correction
Returns
bool success flag
Implemented in ug::IPreconditioner< TAlgebra >, ug::IPreconditioner< ug::CPUAlgebra >, ug::IPreconditioner< algebra_type >, ug::AgglomeratingBase< IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >, TAlgebra >, ug::AgglomeratingBase< ILinearIterator< TAlgebra::vector_type >, TAlgebra >, ug::AgglomeratingBase< IPreconditioner< TAlgebra >, TAlgebra >, ug::DebugIterator< TAlgebra >, ug::LinearIteratorSum< X, Y >, ug::ILinearOperatorInverse< X, Y >, ug::ILinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::ILinearOperatorInverse< vector_type >, ug::ILinearOperatorInverse< vector_type, vector_type >, ug::ILinearOperatorInverse< X >, ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >, ug::ILinearOperatorInverse< algebra_type::vector_type, algebra_type::vector_type >, ug::ILinearOperatorInverse< TVector >, ug::IProjGaussSeidel< TDomain, TAlgebra >, ug::OperatorInverseIterator< TAlgebra >, ug::LinearIteratorProduct< X, Y >, ug::ITransformingIteration< TAlgebra, TDerived >, ug::ITransformingIteration< TAlgebra, AssembledTransformingSmoother< TDomain, TAlgebra > >, and ug::CombinedLinearIterator< X, Y >.
template<typename X, typename Y = X> virtual SmartPtr<ILinearIterator<X,Y> > ug::ILinearIterator< X, Y >::clone () pure virtual
clone
Implemented in ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >, ug::LineVanka< TDomain, TAlgebra >, ug::SparseBlockGaussSeidel< TAlgebra, backward, forward >, ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >, ug::AgglomeratingPreconditioner< TAlgebra >, ug::LineGaussSeidel< TDomain, TAlgebra >, ug::AgglomeratingIterator< TAlgebra >, ug::BlockGaussSeidel< TAlgebra, backward, forward >, ug::ILU< TAlgebra >, ug::DiagVanka< TAlgebra >, ug::SymmetricGaussSeidel< TAlgebra >, ug::BackwardGaussSeidel< TAlgebra >, ug::AssembledMultiGridCycle< TDomain, TAlgebra >, ug::LinearIteratorSum< X, Y >, ug::AssembledTransformingSmoother< TDomain, TAlgebra >, ug::Vanka< TAlgebra >, ug::ILinearOperatorInverse< X, Y >, ug::GaussSeidel< TAlgebra >, ug::ILinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::ILinearOperatorInverse< vector_type >, ug::ILinearOperatorInverse< vector_type, vector_type >, ug::ILinearOperatorInverse< X >, ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >, ug::ILinearOperatorInverse< algebra_type::vector_type, algebra_type::vector_type >, ug::ILinearOperatorInverse< TVector >, ug::ProjSymmetricGaussSeidel< TDomain, TAlgebra >, ug::ElementGaussSeidel< TDomain, TAlgebra >, ug::LinearIteratorProduct< X, Y >, ug::ProjBackwardGaussSeidel< TDomain, TAlgebra >, ug::Jacobi< TAlgebra >, ug::SchurPrecond< TAlgebra >, ug::ProjGaussSeidel< TDomain, TAlgebra >, ug::DebugIterator< TAlgebra >, ug::IExternalSolver< TAlgebra >, ug::ComponentGaussSeidel< TDomain, TAlgebra >, ug::ILUTScalarPreconditioner< TAlgebra >, ug::ILUTScalarPreconditioner< algebra_type >, ug::CombinedLinearIterator< X, Y >, ug::OperatorInverseIterator< TAlgebra >, ug::PILUTPreconditioner< TAlgebra >, ug::ILUTPreconditioner< TAlgebra >, and ug::ILUTPreconditioner< ug::CPUAlgebra >.
Referenced by ug::ILinearIterator< X, X >::damping().
template<typename X, typename Y = X> virtual std::string ug::ILinearIterator< X, Y >::config_string () const inline virtual
Reimplemented in ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >, ug::SparseBlockGaussSeidel< TAlgebra, backward, forward >, ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >, ug::AgglomeratingPreconditioner< TAlgebra >, ug::BlockGaussSeidel< TAlgebra, backward, forward >, ug::AgglomeratingIterator< TAlgebra >, ug::BiCGStab< TVector >, ug::LU< TAlgebra >, ug::AgglomeratingSolver< TAlgebra >, ug::GMRES< TVector >, ug::ILUTScalarPreconditioner< TAlgebra >, ug::ILUTScalarPreconditioner< algebra_type >, ug::AssembledMultiGridCycle< TDomain, TAlgebra >, ug::IPreconditionedLinearOperatorInverse< X >, ug::IPreconditionedLinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::IPreconditionedLinearOperatorInverse< vector_type >, ug::IPreconditionedLinearOperatorInverse< TVector >, ug::SchurPrecond< TAlgebra >, ug::AnalyzingSolver< M, X, Y >, ug::ILinearOperatorInverse< X, Y >, ug::ILinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::ILinearOperatorInverse< vector_type >, ug::ILinearOperatorInverse< vector_type, vector_type >, ug::ILinearOperatorInverse< X >, ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >, ug::ILinearOperatorInverse< algebra_type::vector_type, algebra_type::vector_type >, ug::ILinearOperatorInverse< TVector >, ug::ILUTPreconditioner< TAlgebra >, and ug::ILUTPreconditioner< ug::CPUAlgebra >.
template<typename X, typename Y = X> SmartPtr<IDamping<X,Y> > ug::ILinearIterator< X, Y >::damping () inline
returns the scaling
template<typename X, typename Y = X> virtual bool ug::ILinearIterator< X, Y >::init (SmartPtr< ILinearOperator< Y, X > > J, const Y & u) pure virtual
initialize for operator J(u) and linearization point u
This method passes the linear operator J(u) that should be used as underlying by this iterator. As second argument the linearization point is passed. This is needed e.g. for the geometric multigrid method.
Parameters
[in] J linearized operator to use as underlying
[in] u linearization point
Returns
bool success flag
Implemented in ug::LinearIteratorSum< X, Y >, ug::ILinearOperatorInverse< X, Y >, ug::ILinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::ILinearOperatorInverse< vector_type >, ug::ILinearOperatorInverse< vector_type, vector_type >, ug::ILinearOperatorInverse< X >, ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >, ug::ILinearOperatorInverse< algebra_type::vector_type, algebra_type::vector_type >, ug::ILinearOperatorInverse< TVector >, ug::AutoLinearSolver< TVector >, ug::AnalyzingSolver< M, X, Y >, ug::IPreconditionedLinearOperatorInverse< X >, ug::IPreconditionedLinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::IPreconditionedLinearOperatorInverse< vector_type >, ug::IPreconditionedLinearOperatorInverse< TVector >, ug::IMatrixOperatorInverse< M, X, Y >, ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >, ug::LinearIteratorProduct< X, Y >, and ug::CombinedLinearIterator< X, Y >.
template<typename X, typename Y = X> virtual bool ug::ILinearIterator< X, Y >::init (SmartPtr< ILinearOperator< Y, X > > L) pure virtual
initialize for linear operator L
This method passes the operator L that used as underlying by this operator. In addition some preparation step can be made.
Parameters
[in] L linear operator to use as underlying
Returns
bool success flag
Implemented in ug::LinearIteratorSum< X, Y >, ug::AutoLinearSolver< TVector >, ug::IMatrixOperatorInverse< M, X, Y >, ug::IPreconditionedLinearOperatorInverse< X >, ug::IMatrixOperatorInverse< TAlgebra::matrix_type, TAlgebra::vector_type >, ug::IPreconditionedLinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::IPreconditionedLinearOperatorInverse< vector_type >, ug::IPreconditionedLinearOperatorInverse< TVector >, ug::AnalyzingSolver< M, X, Y >, ug::ILinearOperatorInverse< X, Y >, ug::ILinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::ILinearOperatorInverse< vector_type >, ug::ILinearOperatorInverse< vector_type, vector_type >, ug::ILinearOperatorInverse< X >, ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >, ug::ILinearOperatorInverse< algebra_type::vector_type, algebra_type::vector_type >, ug::ILinearOperatorInverse< TVector >, ug::LinearIteratorProduct< X, Y >, and ug::CombinedLinearIterator< X, Y >.
template<typename X, typename Y = X> virtual const char* ug::ILinearIterator< X, Y >::name () const pure virtual
returns the name of iterator
This method returns the name of the iterator operator. This function is typically needed, when the iterator operator is used inside of another operator and some debug output should be printed
Returns
const char* name of inverse operator
Implemented in ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >, ug::FETISolver< TAlgebra >, ug::LineVanka< TDomain, TAlgebra >, ug::SparseBlockGaussSeidel< TAlgebra, backward, forward >, ug::PrimalSubassembledMatrixInverse< TAlgebra >, ug::PrimalSubassembledMatrixInverse< algebra_type >, ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >, ug::LineGaussSeidel< TDomain, TAlgebra >, ug::AgglomeratingPreconditioner< TAlgebra >, ug::BlockGaussSeidel< TAlgebra, backward, forward >, ug::AgglomeratingIterator< TAlgebra >, ug::ILU< TAlgebra >, ug::DiagVanka< TAlgebra >, ug::AgglomeratingSolver< TAlgebra >, ug::SymmetricGaussSeidel< TAlgebra >, ug::Vanka< TAlgebra >, ug::BackwardGaussSeidel< TAlgebra >, ug::AssembledTransformingSmoother< TDomain, TAlgebra >, ug::ElementGaussSeidel< TDomain, TAlgebra >, ug::AssembledMultiGridCycle< TDomain, TAlgebra >, ug::GaussSeidel< TAlgebra >, ug::LinearIteratorSum< X, Y >, ug::ProjSymmetricGaussSeidel< TDomain, TAlgebra >, ug::ILUTScalarPreconditioner< TAlgebra >, ug::ILUTScalarPreconditioner< algebra_type >, ug::AnalyzingSolver< M, X, Y >, ug::IPreconditioner< TAlgebra >, ug::Jacobi< TAlgebra >, ug::IPreconditioner< ug::CPUAlgebra >, ug::IPreconditioner< algebra_type >, ug::AutoLinearSolver< TVector >, ug::DebugIterator< TAlgebra >, ug::ProjBackwardGaussSeidel< TDomain, TAlgebra >, ug::IProjGaussSeidel< TDomain, TAlgebra >, ug::SchurPrecond< TAlgebra >, ug::LU< TAlgebra >, ug::ILinearOperatorInverse< X, Y >, ug::ILinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::ILinearOperatorInverse< vector_type >, ug::ILinearOperatorInverse< vector_type, vector_type >, ug::ILinearOperatorInverse< X >, ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >, ug::ILinearOperatorInverse< algebra_type::vector_type, algebra_type::vector_type >, ug::ILinearOperatorInverse< TVector >, ug::LinearIteratorProduct< X, Y >, ug::OperatorInverseIterator< TAlgebra >, ug::ILUTPreconditioner< TAlgebra >, ug::ILUTPreconditioner< ug::CPUAlgebra >, ug::PILUTPreconditioner< TAlgebra >, ug::BiCGStab< TVector >, ug::ComponentGaussSeidel< TDomain, TAlgebra >, ug::ProjGaussSeidel< TDomain, TAlgebra >, ug::GMRES< TVector >, ug::CG< TVector >, ug::GaussSeidelBase< TAlgebra >, ug::LinearSolver< TVector >, ug::LinearSolver< ug::CPUAlgebra::vector_type >, ug::IExternalSolver< TAlgebra >, and ug::CombinedLinearIterator< X, Y >.
Referenced by ug::ILinearIterator< X, X >::config_string().
template<typename X, typename Y = X> void ug::ILinearIterator< X, Y >::set_damp (SmartPtr< IDamping< X, Y > > spScaling) inline
sets a scaling for the correction
Sets a scaling for the correction, i.e., once the correction has been computed, c = B*d, the correction is scaled by a factor, c := s*c, where s is provided by the passed scaling class. Note, that the scaling factor may depend on the defect and correction. The internal update of the defect as done in apply_update_defect must be performed with respect to the scaled correction.
Referenced by ug::ILinearIterator< X, X >::ILinearIterator().
template<typename X, typename Y = X> void ug::ILinearIterator< X, Y >::set_damp (number factor) inline
sets the damping to a constant factor
template<typename X, typename Y = X> virtual bool ug::ILinearIterator< X, Y >::supports_parallel () const pure virtual
returns if parallel solving is supported
Implemented in ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >, ug::FETISolver< TAlgebra >, ug::LineVanka< TDomain, TAlgebra >, ug::SparseBlockGaussSeidel< TAlgebra, backward, forward >, ug::PrimalSubassembledMatrixInverse< TAlgebra >, ug::PrimalSubassembledMatrixInverse< algebra_type >, ug::BlockGaussSeidelIterative< TAlgebra, backward, forward >, ug::AgglomeratingPreconditioner< TAlgebra >, ug::LineGaussSeidel< TDomain, TAlgebra >, ug::BlockGaussSeidel< TAlgebra, backward, forward >, ug::AgglomeratingIterator< TAlgebra >, ug::ILU< TAlgebra >, ug::AgglomeratingSolver< TAlgebra >, ug::DiagVanka< TAlgebra >, ug::IBlockJacobiPreconditioner< TAlgebra >, ug::Vanka< TAlgebra >, ug::AssembledTransformingSmoother< TDomain, TAlgebra >, ug::AssembledMultiGridCycle< TDomain, TAlgebra >, ug::ElementGaussSeidel< TDomain, TAlgebra >, ug::Jacobi< TAlgebra >, ug::SchurPrecond< TAlgebra >, ug::ILinearOperatorInverse< X, Y >, ug::ILinearOperatorInverse< ug::CPUAlgebra::vector_type >, ug::ILinearOperatorInverse< vector_type >, ug::ILinearOperatorInverse< vector_type, vector_type >, ug::ILinearOperatorInverse< X >, ug::ILinearOperatorInverse< TAlgebra::vector_type, TAlgebra::vector_type >, ug::ILinearOperatorInverse< algebra_type::vector_type, algebra_type::vector_type >, ug::ILinearOperatorInverse< TVector >, ug::DebugIterator< TAlgebra >, ug::BiCGStab< TVector >, ug::OperatorInverseIterator< TAlgebra >, ug::AutoLinearSolver< TVector >, ug::IExternalSolver< TAlgebra >, ug::ILUTScalarPreconditioner< TAlgebra >, ug::ILUTScalarPreconditioner< algebra_type >, ug::ComponentGaussSeidel< TDomain, TAlgebra >, ug::GMRES< TVector >, ug::CG< TVector >, ug::GaussSeidelBase< TAlgebra >, ug::LU< TAlgebra >, ug::LinearSolver< TVector >, ug::LinearSolver< ug::CPUAlgebra::vector_type >, ug::AnalyzingSolver< M, X, Y >, ug::ILUTPreconditioner< TAlgebra >, ug::ILUTPreconditioner< ug::CPUAlgebra >, and ug::CombinedLinearIterator< X, Y >.
Member Data Documentation
template<typename X, typename Y = X> SmartPtr<IDamping<X,Y> > ug::ILinearIterator< X, Y >::m_spDamping protected
the scaling
Referenced by ug::ILinearIterator< X, X >::config_string(), ug::ILinearIterator< X, X >::damping(), ug::ILinearIterator< X, X >::ILinearIterator(), and ug::ILinearIterator< X, X >::set_damp().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/interface/linear_iterator.h