ug4: ug::AdaptionSurfaceGridFunction< TDomain > Class Template Reference
ug::AdaptionSurfaceGridFunction< TDomain > Class Template Reference
#include <adaption_surface_grid_function.h>
Classes
class ValueAccessor
Public Types
typedef Attachment< Values > AValues
typedef std::vector< std::vector< number > > Values
Public Member Functions
AdaptionSurfaceGridFunction (SmartPtr< TDomain > spDomain, bool bObserveStorage=true)
template<typename TAlgebra >
void copy_from_surface (const GridFunction< TDomain, TAlgebra > &rSurfaceFct)
template<typename TAlgebra >
void copy_to_surface (GridFunction< TDomain, TAlgebra > &rSurfaceFct)
void do_restrict (const GridMessage_Adaption &msg)
template<typename TBaseElem >
void obj_created (TBaseElem *elem)
creates storage when object created
void prolongate (const GridMessage_Adaption &msg)
AValues value_attachment ()
virtual void vertex_created (Grid *grid, Vertex *vrt, GridObject *pParent=NULL, bool replacesParent=false)
virtual void edge_created (Grid *grid, Edge *e, GridObject *pParent=NULL, bool replacesParent=false)
virtual void face_created (Grid *grid, Face *f, GridObject *pParent=NULL, bool replacesParent=false)
virtual void volume_created (Grid *grid, Volume *vol, GridObject *pParent=NULL, bool replacesParent=false)
Public Member Functions inherited from ug::GridObserver
virtual void elements_to_be_cleared (Grid *grid)
virtual void grid_to_be_destroyed (Grid *grid)
virtual ~GridObserver ()
virtual void vertex_to_be_erased (Grid *grid, Vertex *vrt, Vertex *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void edge_to_be_erased (Grid *grid, Edge *e, Edge *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void face_to_be_erased (Grid *grid, Face *f, Face *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void volume_to_be_erased (Grid *grid, Volume *vol, Volume *replacedBy=NULL)
Notified whenever an element of the given type is erased from the given grid.
virtual void vertices_to_be_merged (Grid *grid, Vertex *target, Vertex *elem1, Vertex *elem2)
Notified when two elements of the same type are going to be merged.
virtual void edges_to_be_merged (Grid *grid, Edge *target, Edge *elem1, Edge *elem2)
Notified when two elements of the same type are going to be merged.
virtual void faces_to_be_merged (Grid *grid, Face *target, Face *elem1, Face *elem2)
Notified when two elements of the same type are going to be merged.
virtual void volumes_to_be_merged (Grid *grid, Volume *target, Volume *elem1, Volume *elem2)
Notified when two elements of the same type are going to be merged.
Protected Member Functions
void attach_entries (ConstSmartPtr< DoFDistributionInfo > spDDInfo)
template<typename TElem , typename TAlgebra >
void copy_from_surface (const GridFunction< TDomain, TAlgebra > &rSurfaceFct)
template<typename TElem , typename TAlgebra >
void copy_from_surface (const GridFunction< TDomain, TAlgebra > &rSurfaceFct, TElem *elem)
template<typename TElem , typename TAlgebra >
void copy_to_surface (GridFunction< TDomain, TAlgebra > &rSurfaceFct)
template<typename TElem , typename TAlgebra >
void copy_to_surface (GridFunction< TDomain, TAlgebra > &rSurfaceFct, TElem *elem)
template<typename TElem >
void detach_entries ()
void detach_entries ()
template<typename TBaseElem >
void do_restrict (const MGSelector &sel, const GridMessage_Adaption &msg)
template<typename TBaseElem >
void prolongate (const GridMessage_Adaption &msg, const size_t lvl)
template<typename TBaseElem >
void select_parents (MGSelector &sel, const GridMessage_Adaption &msg)
Protected Attributes
MultiElementAttachmentAccessor< AValues > m_aaValue
AValues m_aValue
bool m_bObserveStorage
int m_ParallelStorageType
ConstSmartPtr< DoFDistributionInfo > m_spDDInfo
SmartPtr< TDomain > m_spDomain
SmartPtr< MultiGrid > m_spGrid
std::vector< SmartPtr< IElemProlongation< TDomain > > > m_vpProlong
std::vector< SmartPtr< IElemRestriction< TDomain > > > m_vpRestrict
Friends
class ValueAccessor
Member Typedef Documentation
AValues
template<typename TDomain > typedef Attachment<Values> ug::AdaptionSurfaceGridFunction< TDomain >::AValues
Values
template<typename TDomain > typedef std::vector<std::vector<number> > ug::AdaptionSurfaceGridFunction< TDomain >::Values
Constructor & Destructor Documentation
AdaptionSurfaceGridFunction()
template<typename TDomain > ug::AdaptionSurfaceGridFunction< TDomain >::AdaptionSurfaceGridFunction (SmartPtr< TDomain > spDomain, bool bObserveStorage = true)
Member Function Documentation
attach_entries()
template<typename TDomain > void ug::AdaptionSurfaceGridFunction< TDomain >::attach_entries (ConstSmartPtr< DoFDistributionInfo > spDDInfo) protected
References ug::EDGE, ug::FACE, GFUNCADAPT_PROFILE_FUNC, ug::OT_EDGE_OBSERVER, ug::OT_FACE_OBSERVER, ug::OT_GRID_OBSERVER, ug::OT_VERTEX_OBSERVER, ug::OT_VOLUME_OBSERVER, UG_THROW, ug::VERTEX, and ug::VOLUME.
copy_from_surface() [1/3]
template<typename TDomain > template<typename TAlgebra > void ug::AdaptionSurfaceGridFunction< TDomain >::copy_from_surface (const GridFunction< TDomain, TAlgebra > & rSurfaceFct)
References ug::GridFunction< TDomain, TAlgebra >::dof_distribution(), ug::EDGE, ug::FACE, GFUNCADAPT_PROFILE_FUNC, ug::DoFDistributionInfoProvider::max_dofs(), ug::VERTEX, and ug::VOLUME.
copy_from_surface() [2/3]
template<typename TDomain > template<typename TElem , typename TAlgebra > void ug::AdaptionSurfaceGridFunction< TDomain >::copy_from_surface (const GridFunction< TDomain, TAlgebra > & rSurfaceFct) protected
References ug::SurfaceView::ALL, and ug::GridFunction< TDomain, TAlgebra >::approx_space().
copy_from_surface() [3/3]
template<typename TDomain > template<typename TElem , typename TAlgebra > void ug::AdaptionSurfaceGridFunction< TDomain >::copy_from_surface (const GridFunction< TDomain, TAlgebra > & rSurfaceFct, TElem * elem) protected
References ug::DoFRef(), and ug::GridFunction< TDomain, TAlgebra >::inner_dof_indices().
copy_to_surface() [1/3]
template<typename TDomain > template<typename TAlgebra > void ug::AdaptionSurfaceGridFunction< TDomain >::copy_to_surface (GridFunction< TDomain, TAlgebra > & rSurfaceFct)
References ug::EDGE, ug::FACE, GFUNCADAPT_PROFILE_FUNC, ug::DoFDistributionInfoProvider::max_dofs(), ug::VERTEX, and ug::VOLUME.
copy_to_surface() [2/3]
template<typename TDomain > template<typename TElem , typename TAlgebra > void ug::AdaptionSurfaceGridFunction< TDomain >::copy_to_surface (GridFunction< TDomain, TAlgebra > & rSurfaceFct) protected
References ug::SurfaceView::ALL, and ug::GridFunction< TDomain, TAlgebra >::approx_space().
copy_to_surface() [3/3]
template<typename TDomain > template<typename TElem , typename TAlgebra > void ug::AdaptionSurfaceGridFunction< TDomain >::copy_to_surface (GridFunction< TDomain, TAlgebra > & rSurfaceFct, TElem * elem) protected
References ug::DoFRef(), ug::GridFunction< TDomain, TAlgebra >::domain(), ug::ElementDebugInfo(), ug::GridFunction< TDomain, TAlgebra >::inner_dof_indices(), and UG_ASSERT.
detach_entries() [1/2]
template<typename TDomain > template<typename TElem > void ug::AdaptionSurfaceGridFunction< TDomain >::detach_entries protected
References UG_THROW.
detach_entries() [2/2]
template<typename TDomain > void ug::AdaptionSurfaceGridFunction< TDomain >::detach_entries () protected
do_restrict() [1/2]
template<typename TDomain > void ug::AdaptionSurfaceGridFunction< TDomain >::do_restrict (const GridMessage_Adaption & msg)
do_restrict() [2/2]
template<typename TDomain > template<typename TBaseElem > void ug::AdaptionSurfaceGridFunction< TDomain >::do_restrict (const MGSelector & sel, const GridMessage_Adaption & msg) protected
References ug::MGSelector::begin(), ug::MGSelector::end(), make_sp(), and ug::MGSelector::num_levels().
edge_created()
template<typename TDomain > virtual void ug::AdaptionSurfaceGridFunction< TDomain >::edge_created (Grid * grid, Edge * e, GridObject * pParent = NULL, bool replacesParent = false) inline virtual
grid observer callbacks
Reimplemented from ug::GridObserver.
References ug::AdaptionSurfaceGridFunction< TDomain >::obj_created().
face_created()
template<typename TDomain > virtual void ug::AdaptionSurfaceGridFunction< TDomain >::face_created (Grid * grid, Face * f, GridObject * pParent = NULL, bool replacesParent = false) inline virtual
grid observer callbacks
Reimplemented from ug::GridObserver.
References ug::AdaptionSurfaceGridFunction< TDomain >::obj_created().
obj_created()
template<typename TDomain > template<typename TBaseElem > void ug::AdaptionSurfaceGridFunction< TDomain >::obj_created (TBaseElem * elem) inline
creates storage when object created
Referenced by ug::AdaptionSurfaceGridFunction< TDomain >::edge_created(), ug::AdaptionSurfaceGridFunction< TDomain >::face_created(), ug::AdaptionSurfaceGridFunction< TDomain >::vertex_created(), and ug::AdaptionSurfaceGridFunction< TDomain >::volume_created().
prolongate() [1/2]
template<typename TDomain > void ug::AdaptionSurfaceGridFunction< TDomain >::prolongate (const GridMessage_Adaption & msg)
References ug::GridMessage_Adaption::affected_elements(), and ug::GridObjectCollection::num_levels().
prolongate() [2/2]
template<typename TDomain > template<typename TBaseElem > void ug::AdaptionSurfaceGridFunction< TDomain >::prolongate (const GridMessage_Adaption & msg, const size_t lvl) protected
References ug::GridMessage_Adaption::affected_elements(), ug::GridObjectCollection::begin(), ug::GridObjectCollection::end(), and make_sp().
select_parents()
template<typename TDomain > template<typename TBaseElem > void ug::AdaptionSurfaceGridFunction< TDomain >::select_parents (MGSelector & sel, const GridMessage_Adaption & msg) protected
References ug::GridMessage_Adaption::affected_elements(), ug::GridObject::base_object_id(), ug::GridObjectCollection::begin(), ug::GridObjectCollection::end(), ug::MultiGrid::get_parent(), ug::MGSelector::multi_grid(), ug::GridObjectCollection::num_levels(), and ug::ISelector::select().
value_attachment()
template<typename TDomain > AValues ug::AdaptionSurfaceGridFunction< TDomain >::value_attachment () inline
References ug::AdaptionSurfaceGridFunction< TDomain >::m_aValue.
vertex_created()
template<typename TDomain > virtual void ug::AdaptionSurfaceGridFunction< TDomain >::vertex_created (Grid * grid, Vertex * vrt, GridObject * pParent = NULL, bool replacesParent = false) inline virtual
grid observer callbacks
Reimplemented from ug::GridObserver.
References ug::AdaptionSurfaceGridFunction< TDomain >::obj_created().
volume_created()
template<typename TDomain > virtual void ug::AdaptionSurfaceGridFunction< TDomain >::volume_created (Grid * grid, Volume * vol, GridObject * pParent = NULL, bool replacesParent = false) inline virtual
grid observer callbacks
Reimplemented from ug::GridObserver.
References ug::AdaptionSurfaceGridFunction< TDomain >::obj_created().
Friends And Related Function Documentation
ValueAccessor
template<typename TDomain > friend class ValueAccessor friend
Member Data Documentation
m_aaValue
template<typename TDomain > MultiElementAttachmentAccessor<AValues> ug::AdaptionSurfaceGridFunction< TDomain >::m_aaValue protected
m_aValue
template<typename TDomain > AValues ug::AdaptionSurfaceGridFunction< TDomain >::m_aValue protected
Referenced by ug::AdaptionSurfaceGridFunction< TDomain >::value_attachment().
m_bObserveStorage
template<typename TDomain > bool ug::AdaptionSurfaceGridFunction< TDomain >::m_bObserveStorage protected
m_ParallelStorageType
template<typename TDomain > int ug::AdaptionSurfaceGridFunction< TDomain >::m_ParallelStorageType protected
m_spDDInfo
template<typename TDomain > ConstSmartPtr<DoFDistributionInfo> ug::AdaptionSurfaceGridFunction< TDomain >::m_spDDInfo protected
m_spDomain
template<typename TDomain > SmartPtr<TDomain> ug::AdaptionSurfaceGridFunction< TDomain >::m_spDomain protected
m_spGrid
template<typename TDomain > SmartPtr<MultiGrid> ug::AdaptionSurfaceGridFunction< TDomain >::m_spGrid protected
m_vpProlong
template<typename TDomain > std::vector<SmartPtr<IElemProlongation<TDomain> > > ug::AdaptionSurfaceGridFunction< TDomain >::m_vpProlong protected
m_vpRestrict
template<typename TDomain > std::vector<SmartPtr<IElemRestriction<TDomain> > > ug::AdaptionSurfaceGridFunction< TDomain >::m_vpRestrict protected
The documentation for this class was generated from the following files:
ugbase/lib_disc/function_spaces/adaption_surface_grid_function.h
ugbase/lib_disc/function_spaces/adaption_surface_grid_function.cpp
ugbase/lib_disc/function_spaces/adaption_surface_grid_function_impl.h