ug4: ug::LuaTableHandle Class Reference
ug::LuaTableHandle Class Reference
Handle for a lua reference.
#include <lua_table_handle.h>
Public Member Functions
ug::Variant get (int const &key) const
ug::Variant get (std::string const &key) const
LuaTableHandle ()=delete
LuaTableHandle (lua_State *ref, int idx)
LuaTableHandle (LuaTableHandle &&)
LuaTableHandle (LuaTableHandle const &)
LuaTableHandle & operator= (LuaTableHandle &&)
LuaTableHandle & operator= (LuaTableHandle const &)
size_t size () const
~LuaTableHandle ()
Private Attributes
impl::LuaTableHandle_ * _data
Detailed Description
Handle for a lua reference.
Constructor & Destructor Documentation
LuaTableHandle() [1/4]
ug::LuaTableHandle::LuaTableHandle () delete
LuaTableHandle() [2/4]
ug::LuaTableHandle::LuaTableHandle (LuaTableHandle const & p)
References _data, ug::impl::LuaTableHandle_::attach(), and p.
LuaTableHandle() [3/4]
ug::LuaTableHandle::LuaTableHandle (LuaTableHandle && p)
References _data, ug::impl::LuaTableHandle_::attach(), ug::impl::LuaTableHandle_::detach(), and p.
LuaTableHandle() [4/4]
ug::LuaTableHandle::LuaTableHandle (lua_State * ref, int idx) explicit
References _data, and ug::impl::LuaTableHandle_::attach().
~LuaTableHandle()
ug::LuaTableHandle::~LuaTableHandle ()
References _data, and ug::impl::LuaTableHandle_::detach().
Member Function Documentation
get() [1/2]
ug::Variant ug::LuaTableHandle::get (int const & key) const
References _data, and ug::impl::LuaTableHandle_::get().
get() [2/2]
ug::Variant ug::LuaTableHandle::get (std::string const & key) const
References _data, and ug::impl::LuaTableHandle_::get().
operator=() [1/2]
LuaTableHandle & ug::LuaTableHandle::operator= (LuaTableHandle && p)
References _data, ug::impl::LuaTableHandle_::attach(), ug::impl::LuaTableHandle_::detach(), and p.
operator=() [2/2]
LuaTableHandle & ug::LuaTableHandle::operator= (LuaTableHandle const & p)
References _data, ug::impl::LuaTableHandle_::attach(), p, and untested.
size()
size_t ug::LuaTableHandle::size () const
References _data, and ug::impl::LuaTableHandle_::size().
Member Data Documentation
_data
impl::LuaTableHandle_* ug::LuaTableHandle::_data private
Referenced by get(), LuaTableHandle(), operator=(), size(), and ~LuaTableHandle().
The documentation for this class was generated from the following files:
ugbase/bindings/lua/lua_table_handle.h
ugbase/bindings/lua/lua_table_handle.cpp