ug4: ug::FaceVertices Class Reference
ug::FaceVertices Class Reference
#include <grid_base_objects.h>
Public Member Functions
virtual size_t num_vertices () const
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual Vertex * vertex (size_t index) const
virtual ConstVertexArray vertices () const
virtual ~FaceVertices ()
Public Member Functions inherited from ug::IVertexGroup
Vertex * operator[] (size_t index) const
returns the i-th vertex.
size_t size () const
returns the number of vertices.
virtual ~IVertexGroup ()
Additional Inherited Members
Public Types inherited from ug::IVertexGroup
typedef Vertex *const * ConstVertexArray
Constructor & Destructor Documentation
~FaceVertices()
virtual ug::FaceVertices::~FaceVertices () inline virtual
Member Function Documentation
num_vertices()
virtual size_t ug::FaceVertices::num_vertices () const inline virtual
Implements ug::IVertexGroup.
Reimplemented in ug::CustomQuadrilateral< ConstrainedQuadrilateral, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomQuadrilateral< Quadrilateral, Face, Triangle, Quadrilateral >, ug::CustomQuadrilateral< ConstrainingQuadrilateral, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< ConstrainedTriangle, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomTriangle< ConstrainingTriangle, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< Triangle, Face, Triangle, Quadrilateral >, and ug::FaceDescriptor.
References UG_ASSERT.
Referenced by ug::AdaptSurfaceGridToCylinder(), ug::AspectRatio(), ug::Grid::assign_grid(), ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::AssignInnerAndBoundarySubsets(), ug::CalculateAngles(), ug::CalculateBoundingSphere(), ug::CalculateCenter(), ug::CalculateMaxAngle(), ug::CalculateMaxDihedral(), ug::CalculateMinAngle(), ug::CalculateMinDihedral(), ug::CalculateMinTriangleHeight(), ug::CalculateNormal(), ug::CalculateNormalNoNormalize(), ug::CalculateNumManifoldFacesVertexAttachmentInTopLevel(), ug::CalculateSmoothManifoldPosInTopLevelAveragingScheme(), ug::CalculateVertexNormals(), ug::CheckHangingNodeConsistency(), ug::DelaunayInfo< TAAPos >::classify_face(), ug::CollectAssociatedSides(), ug::CollectConstraining(), ug::CollectNeighborhood(), ug::CollectNeighbors(), ug::CollectSurfaceNeighborsSorted(), ug::CollectSurfaceVertices(), ug::CollectVertices(), ug::CompareVertices(), ug::ComputeOrientationOffsetLagrange(), ug::ContainsPoint(), ug::ConvertToTetrahedra(), ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_2d(), ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_3d(), ug::CreateEdgeSplitGeometry(), ug::CreateQuadrilateral_NoRegistration(), ug::DistributeExpansionMarks3D(), ug::Duplicate(), ug::EraseConnectingElements(), ug::ExpandFractures2d(), ug::ExpandFractures3d(), ug::ExportGridToSMESH(), ug::ExportGridToTETGEN(), ug::ExportGridToTIKZ(), ug::ExportGridToUG_2D(), ug::Extrude(), ug::ExtrudeLayers(), ug::ExtrudeLayersMixed(), ug::FaceArea(), ug::FaceContains(), ug::FaceIsOnRightSide(), ug::FaceQuality(), ug::Grid::flip_orientation(), ug::GenerateIcosphere(), ug::Grid::get_associated(), ug::Grid::get_associated_sorted(), ug::IRefiner::get_local_face_mark(), ug::GetAssociatedFaces(), ug::GetConnectedVertex(), ug::GetConnectedVertexIndex(), ug::GetFirstRegularVertex(), ug::GetVertexIndex(), ug::HashKey(), ug::DelaunayInfo< TAAPos >::init_marks(), ug::IntersectCoplanarTriangles(), ug::IsDegenerated(), ug::LoadGridFromART(), ug::MergeGrids(), ug::MergeVertices(), ug::NumAssociatedFaces(), ug::NumVertices(), ug::ObtainSimpleGrid_CollapseEdge(), ug::OrientationMatches(), ug::GlobalFracturedMediaRefiner::perform_refinement(), ug::GlobalMultiGridRefiner::perform_refinement(), ug::PerformTetrahedralization(), ug::HangingNodeRefinerBase< TSelector >::process_constrained_face(), ug::HangingNodeRefinerBase< TSelector >::process_constraining_face(), ug::ProjectVerticesToCloseFaces(), ug::ProlongateP1(), ug::QualityGridGeneration(), ug::RayElementIntersection(), ug::MGHNodeAdjuster::ref_marks_changed(), ug::StdHNodeAdjuster::ref_marks_changed(), ug::Refine(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_normal_vertex(), ug::HangingNodeRefinerBase< TSelector >::refine_volume_with_normal_vertex(), ug::SmoothProjector::refinement_ends(), ug::Grid::register_and_replace_element(), ug::Grid::register_face(), ug::Grid::replace_vertex(), ug::ReplaceByConstrained(), ug::ReplaceByConstraining(), ug::ReplaceByNormal(), ug::ReplaceLowValenceVertices(), ug::ReplaceValence3Vertices(), ug::ResolveEdgeFaceIntersection(), ug::ResolveTriangleIntersections(), ug::ResolveVertexFaceIntersection(), ug::SelectInnerSelectionVertices(), ug::Grid::unregister_face(), ug::Grid::vertex_store_associated_faces(), ug::WeightedFaceSmooth(), ug::WriteFaces(), ug::WriteLGM(), and ug::WriteNG().
operator[]()
Vertex* ug::FaceVertices::operator[] (size_t index) const inline
returns the i-th vertex.
size()
size_t ug::FaceVertices::size () const inline
returns the number of vertices.
References boost::num_vertices().
Referenced by ug::LoadGridFromART(), and ug::ObtainSimpleGrid().
vertex()
virtual Vertex* ug::FaceVertices::vertex (size_t index) const inline virtual
Implements ug::IVertexGroup.
Reimplemented in ug::CustomQuadrilateral< ConstrainedQuadrilateral, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomQuadrilateral< Quadrilateral, Face, Triangle, Quadrilateral >, ug::CustomQuadrilateral< ConstrainingQuadrilateral, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< ConstrainedTriangle, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomTriangle< ConstrainingTriangle, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< Triangle, Face, Triangle, Quadrilateral >, and ug::FaceDescriptor.
References UG_ASSERT.
Referenced by ug::AdaptSurfaceGridToCylinder(), ug::StdTransfer< TDomain, TAlgebra >::assemble_prolongation_p1(), ug::AssignInnerAndBoundarySubsets(), ug::CalculateAngles(), ug::CalculateBoundingSphere(), ug::CalculateMaxAngle(), ug::CalculateMaxDihedral(), ug::CalculateMinAngle(), ug::CalculateMinDihedral(), ug::CalculateMinTriangleHeight(), ug::CalculateNormal(), ug::CalculateNormalNoNormalize(), ug::CalculateNumManifoldFacesVertexAttachmentInTopLevel(), ug::CalculateSmoothManifoldPosInTopLevelAveragingScheme(), ug::CalculateVertexNormals(), ug::DelaunayInfo< TAAPos >::classify_face(), ug::CollectAssociatedSides(), ug::CollectConstraining(), ug::CollectSurfaceNeighborsSorted(), ug::CollectSurfaceVertices(), ug::CollectVolumes(), ug::ComputeOrientationOffsetLagrange(), ug::ContainsPoint(), ug::ConvertToTetrahedra(), ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_3d(), ug::CreateEdgeSplitGeometry(), ug::CreateQuadrilateral_NoRegistration(), ug::DistributeExpansionMarks3D(), ug::Duplicate(), ug::EraseConnectingElements(), ug::ExpandFractures2d(), ug::ExportGridToSMESH(), ug::ExportGridToTETGEN(), ug::ExportGridToTIKZ(), ug::ExportGridToUG_2D(), ug::Extrude(), ug::FaceArea(), ug::FaceQuality(), ug::Grid::flip_orientation(), ug::GenerateIcosphere(), ug::Grid::get_associated_vols_raw(), ug::Grid::get_face(), ug::Grid::get_opposing_object(), ug::GetAssociatedFaces(), ug::GetConnectedVertex(), ug::GetConnectedVertexIndex(), ug::GetFirstRegularVertex(), ug::GetVertex(), ug::GetVertexIndex(), ug::DelaunayInfo< TAAPos >::init_marks(), ug::IntersectCoplanarTriangles(), ug::DelaunayInfo< TAAPos >::is_classifiable(), ug::IsDegenerated(), ug::MergeGrids(), ug::MergeVertices(), ug::NumAssociatedFaces(), ug::NumAssociatedVolumes(), ug::ObtainSimpleGrid(), ug::ObtainSimpleGrid_CollapseEdge(), ug::OrientationMatches(), ug::GlobalFracturedMediaRefiner::perform_refinement(), ug::GlobalMultiGridRefiner::perform_refinement(), ug::PerformTetrahedralization(), ug::PointFaceTest(), ug::ProjectVerticesToCloseFaces(), ug::ProlongateP1(), ug::QualityGridGeneration(), ug::RayElementIntersection(), ug::MGHNodeAdjuster::ref_marks_changed(), ug::StdHNodeAdjuster::ref_marks_changed(), ug::HangingNodeRefinerBase< TSelector >::refine_face_with_hanging_vertex(), ug::SmoothProjector::refinement_ends(), ug::ReplaceLowValenceVertices(), ug::ReplaceValence3Vertices(), ug::ResolveEdgeFaceIntersection(), ug::ResolveTriangleIntersections(), ug::ResolveVertexFaceIntersection(), ug::SelectInnerSelectionVertices(), ug::DoFDistribution::sort_constrained_edges(), ug::SwapEdge(), ug::WriteFaces(), ug::WriteLGM(), and ug::WriteNG().
vertices()
virtual ConstVertexArray ug::FaceVertices::vertices () const inline virtual
Implements ug::IVertexGroup.
Reimplemented in ug::CustomQuadrilateral< ConstrainedQuadrilateral, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomQuadrilateral< Quadrilateral, Face, Triangle, Quadrilateral >, ug::CustomQuadrilateral< ConstrainingQuadrilateral, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< ConstrainedTriangle, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral >, ug::CustomTriangle< ConstrainingTriangle, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral >, ug::CustomTriangle< Triangle, Face, Triangle, Quadrilateral >, and ug::FaceDescriptor.
References UG_ASSERT.
Referenced by ug::Grid::assign_grid(), ug::HangingNodeRefinerBase< TSelector >::assign_hnode_marks(), ug::CalculateCenter(), ug::CollectNeighborhood(), ug::CollectNeighbors(), ug::CollectVertices(), ug::CompareVertices(), ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_2d(), ug::AdaptiveRegularRefiner_MultiGrid::create_closure_elements_3d(), ug::ExtrudeLayers(), ug::ExtrudeLayersMixed(), ug::FaceContains(), ug::Grid::get_associated(), ug::Grid::get_associated_sorted(), ug::IRefiner::get_local_face_mark(), ug::HashKey(), ug::DelaunayInfo< TAAPos >::init_marks(), ug::QuadrilateralAspectRatio(), ug::Refine(), ug::Grid::register_and_replace_element(), ug::Grid::register_face(), ug::Grid::replace_vertex(), ug::TriangleAspectRatio(), ug::Grid::unregister_face(), and ug::Grid::vertex_store_associated_faces().
The documentation for this class was generated from the following file:
ugbase/lib_grid/grid/grid_base_objects.h