ug4: ug::bridge::ClassCastProvider Class Reference
ug::bridge::ClassCastProvider Class Reference
ugbase » Bridge » Registry
provides castings from derived classes to base classes
#include <class_name_provider.h>
Static Public Member Functions
template<typename TBase , typename TDerived >
static void add_cast_func ()
add a cast function to the registry: Casts: Derived -> Base
static void * cast_to_base_class (void *pDerivVoid, const ClassNameNode *&node, const std::string &baseName)
cast a pointer to the desired base class
static const void * cast_to_base_class (const void *pDerivVoid, const ClassNameNode *&node, const std::string &baseName)
cast a pointer to the desired base class
template<typename T >
static T * cast_to (void *pDerivVoid, const ClassNameNode *&node)
casts a void pointer to a concrete class
template<typename T >
static const T * cast_to (const void *pDerivVoid, const ClassNameNode *&node)
cast a pointer to the desired base class
template<typename T >
static SmartPtr< T > cast_to (SmartPtr< void > pDerivVoid, const ClassNameNode *&node)
cast a pointer to the desired base class
template<typename T >
static ConstSmartPtr< T > cast_to (ConstSmartPtr< void > pDerivVoid, const ClassNameNode *&node)
cast a pointer to the desired base class
Protected Types
typedef void *(* CastFunc) (void *)
Static Protected Attributes
static std::map< std::pair< const ClassNameNode *, const ClassNameNode * >, CastFunc > m_mmCast = std::map<std::pair<const ClassNameNode*, const ClassNameNode*>, void* (*)(void*)> ()
Detailed Description
provides castings from derived classes to base classes
Member Typedef Documentation
CastFunc
typedef void*(* ug::bridge::ClassCastProvider::CastFunc) (void *) protected
Member Function Documentation
add_cast_func()
template<typename TBase , typename TDerived > void ug::bridge::ClassCastProvider::add_cast_func () static
add a cast function to the registry: Casts: Derived -> Base
References cast_to(), ug::bridge::ClassNameProvider< TClass >::class_name_node(), and m_mmCast.
cast_to() [1/4]
template<typename T > T * ug::bridge::ClassCastProvider::cast_to (void * pDerivVoid, const ClassNameNode *& node) static
casts a void pointer to a concrete class
This method casts a void pointer to a given derived classed and returns it as a reinterpreted cast to the type specified by the template argument. If conversion fails, an exception of type UGError_ClassCastFailed is thrown.
Parameters
[in] pDerivVoid void pointer to Derived object
[in,out] node on entry: class name node corresponding to pDerivVoid on exit: class name node corresponding to baseName
Returns
void* to base class
References ug::baseName(), cast_to_base_class(), and ug::bridge::ClassNameProvider< TClass >::name().
Referenced by add_cast_func(), and cast_to().
cast_to() [2/4]
template<typename T > const T * ug::bridge::ClassCastProvider::cast_to (const void * pDerivVoid, const ClassNameNode *& node) static
cast a pointer to the desired base class
This method casts a void pointer to a given derived class to the void pointer of a base class. If conversion fails, an exception of type UGError_ClassCastFailed is thrown.
Parameters
[in] pDerivVoid void pointer to Derived object
[in,out] node on entry: class name node corresponding to pDerivVoid on exit: class name node corresponding to baseName
[in] baseName name of base class the pointer should be casted to
Returns
void* to base class
References ug::baseName(), cast_to(), cast_to_base_class(), and ug::bridge::ClassNameProvider< TClass >::name().
cast_to() [3/4]
template<typename T > SmartPtr< T > ug::bridge::ClassCastProvider::cast_to (SmartPtr< void > pDerivVoid, const ClassNameNode *& node) static
cast a pointer to the desired base class
This method casts a void pointer to a given derived class to the void pointer of a base class. If conversion fails, an exception of type UGError_ClassCastFailed is thrown.
Parameters
[in] pDerivVoid void pointer to Derived object
[in,out] node on entry: class name node corresponding to pDerivVoid on exit: class name node corresponding to baseName
[in] baseName name of base class the pointer should be casted to
Returns
void* to base class
References ug::baseName(), SmartPtr< void >::cast_reinterpret(), cast_to(), cast_to_base_class(), SmartPtr< void >::get(), ug::bridge::ClassNameProvider< TClass >::name(), and SmartPtr< void >::set_impl().
cast_to() [4/4]
template<typename T > ConstSmartPtr< T > ug::bridge::ClassCastProvider::cast_to (ConstSmartPtr< void > pDerivVoid, const ClassNameNode *& node) static
cast a pointer to the desired base class
This method casts a void pointer to a given derived class to the void pointer of a base class. If conversion fails, an exception of type UGError_ClassCastFailed is thrown.
Parameters
[in] pDerivVoid void pointer to Derived object
[in,out] node on entry: class name node corresponding to pDerivVoid on exit: class name node corresponding to baseName
[in] baseName name of base class the pointer should be casted to
Returns
void* to base class
References ug::baseName(), ConstSmartPtr< void >::cast_reinterpret(), cast_to_base_class(), ConstSmartPtr< void >::get(), ug::bridge::ClassNameProvider< TClass >::name(), and ConstSmartPtr< void >::set_impl().
cast_to_base_class() [1/2]
void * ug::bridge::ClassCastProvider::cast_to_base_class (void * pDerivVoid, const ClassNameNode *& node, const std::string & baseName) static
cast a pointer to the desired base class
This method casts a void pointer to a given derived class to the void pointer of a base class. If conversion fails, an exception of type UGError_ClassCastFailed is thrown.
Parameters
[in] pDerivVoid void pointer to Derived object
[in,out] node on entry: class name node corresponding to pDerivVoid on exit: class name node corresponding to baseName
[in] baseName name of base class the pointer should be casted to
Returns
void* to base class
References ug::bridge::ClassNameNode::base_class(), ug::baseName(), ug::bridge::ClassNameTreeWay(), ug::bridge::ClassNameNode::name(), and UG_ERR_LOG.
Referenced by cast_to(), ug::bridge::ClassNameTreeWay(), and Java_edu_gcsc_vrl_ug_UG__1invokeMethod().
cast_to_base_class() [2/2]
const void * ug::bridge::ClassCastProvider::cast_to_base_class (const void * pDerivVoid, const ClassNameNode *& node, const std::string & baseName) static
cast a pointer to the desired base class
This method casts a void pointer to a given derived class to the void pointer of a base class. If conversion fails, an exception of type UGError_ClassCastFailed is thrown.
Parameters
[in] pDerivVoid void pointer to Derived object
[in,out] node on entry: class name node corresponding to pDerivVoid on exit: class name node corresponding to baseName
[in] baseName name of base class the pointer should be casted to
Returns
void* to base class
References m_mmCast.
Member Data Documentation
m_mmCast
std::map< std::pair< const ClassNameNode *, const ClassNameNode * >, void *(*)(void *)> ug::bridge::ClassCastProvider::m_mmCast = std::map<std::pair<const ClassNameNode*, const ClassNameNode*>, void* (*)(void*)> () static protected
Referenced by add_cast_func(), and cast_to_base_class().
The documentation for this class was generated from the following files:
ugbase/registry/class_name_provider.h
ugbase/registry/class_name_provider.cpp
ugbase/registry/class_name_provider_impl.h