ug4: ug::FunctionIndexMapping Class Reference
ug::FunctionIndexMapping Class Reference
describes a mapping between two local index sets
#include <function_group.h>
Public Member Functions
void clear ()
removes all connections
size_t num_fct () const
returns the number of indices that are mapped
size_t operator[] (size_t i) const
returns the mapped index
void push_back (size_t indexTo)
adds a mapping between indexFrom and indexTo
Protected Attributes
std::vector< size_t > m_vMapping
vector holding the mapped indices
Detailed Description
describes a mapping between two local index sets
This class is used to define a mapping between two index sets. The domain index set must contain indices in consecutive order [0, ..., N], while the codomain index set can have any size.
Member Function Documentation
clear()
void ug::FunctionIndexMapping::clear () inline
removes all connections
References m_vMapping.
Referenced by ug::CreateFunctionIndexMapping().
num_fct()
size_t ug::FunctionIndexMapping::num_fct () const inline
returns the number of indices that are mapped
References m_vMapping.
Referenced by ug::LocalVector::access_by_map(), ug::LocalMatrix::access_by_map(), ug::LocalMatrix::num_col_fct(), ug::LocalVector::num_fct(), ug::IDataImport< dim >::num_fct(), ug::UserDataInfo::num_fct(), ug::LocalMatrix::num_row_fct(), ug::operator<<(), operator[](), ug::DataImport< TData, dim >::update_dof_sizes(), and ug::DependentUserData< TData, dim >::update_dof_sizes().
operator[]()
size_t ug::FunctionIndexMapping::operator[] (size_t i) const inline
returns the mapped index
References m_vMapping, num_fct(), and UG_ASSERT.
push_back()
void ug::FunctionIndexMapping::push_back (size_t indexTo) inline
adds a mapping between indexFrom and indexTo
References m_vMapping.
Referenced by ug::CreateFunctionIndexMapping().
Member Data Documentation
m_vMapping
std::vector<size_t> ug::FunctionIndexMapping::m_vMapping protected
vector holding the mapped indices
Referenced by clear(), num_fct(), operator[](), and push_back().
The documentation for this class was generated from the following file:
ugbase/lib_disc/common/function_group.h