ug4: ug::PyramidDescriptor Class Reference
ug::PyramidDescriptor Class Reference
only used to initialize a pyramids. for all other tasks you should use VolumeDescripor.
#include <grid_objects_3d.h>
Public Member Functions
uint num_vertices () const
PyramidDescriptor ()
PyramidDescriptor (const PyramidDescriptor &td)
PyramidDescriptor (const VolumeVertices &vv)
PyramidDescriptor (Vertex *v1, Vertex *v2, Vertex *v3, Vertex *v4, Vertex *v5)
Vertex * vertex (size_t index) const
Protected Attributes
Vertex * m_vertex [5]
Detailed Description
only used to initialize a pyramids. for all other tasks you should use VolumeDescripor.
please be sure to pass the vertices in the correct order: v1, v2, v3, v4: bottom-vertices in counterclockwise order (if viewed from the top). v5: top-vertex.
Constructor & Destructor Documentation
PyramidDescriptor() [1/4]
ug::PyramidDescriptor::PyramidDescriptor () inline
PyramidDescriptor() [2/4]
ug::PyramidDescriptor::PyramidDescriptor (const PyramidDescriptor & td)
References vertex().
PyramidDescriptor() [3/4]
ug::PyramidDescriptor::PyramidDescriptor (const VolumeVertices & vv)
References ug::VolumeVertices::num_vertices(), and ug::VolumeVertices::vertex().
PyramidDescriptor() [4/4]
ug::PyramidDescriptor::PyramidDescriptor (Vertex * v1, Vertex * v2, Vertex * v3, Vertex * v4, Vertex * v5)
Member Function Documentation
num_vertices()
uint ug::PyramidDescriptor::num_vertices () const inline
vertex()
Vertex* ug::PyramidDescriptor::vertex (size_t index) const inline
Referenced by ug::Pyramid::Pyramid(), and PyramidDescriptor().
Member Data Documentation
m_vertex
Vertex* ug::PyramidDescriptor::m_vertex[5] protected
The documentation for this class was generated from the following files:
ugbase/lib_grid/grid_objects/grid_objects_3d.h
ugbase/lib_grid/grid_objects/grid_objects_3d.cpp