ug4: ug::DiagVanka< TAlgebra > Class Template Reference
ug::DiagVanka< TAlgebra > Class Template Reference
Diagvanka Preconditioner, description see above diagvanka_step function.
#include <vanka.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef IPreconditioner< TAlgebra > base_type
Base type.
typedef IPreconditioner< TAlgebra >::matrix_operator_type matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
Algebra type.
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
Matrix type.
typedef TAlgebra::vector_type vector_type
Vector type.
Public Types inherited from ug::ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
Range space.
typedef TAlgebra::vector_type domain_function_type
Domain space.
Public Types inherited from ug::DebugWritingObject< TAlgebra >
typedef TAlgebra algebra_type
type of algebra
typedef TAlgebra::matrix_type matrix_type
type of matrix
typedef TAlgebra::vector_type vector_type
type of vector
Public Types inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
type of vector
Public Member Functions
virtual SmartPtr< ILinearIterator< vector_type > > clone ()
Clone.
DiagVanka ()
default constructor
void set_relax (number omega)
set relaxation parameter
virtual bool supports_parallel () const
returns if parallel solving is supported
virtual ~DiagVanka ()
Destructor.
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
compute new correction c = B*d
virtual bool apply_update_defect (vector_type &c, vector_type &d)
compute new correction c = B*d and update defect d:= d - L*c
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
underlying matrix based operator used for the preconditioner
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
underlying matrix based operator for calculation of defect
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< ILinearOperator< vector_type > > L)
implements the ILinearIterator-interface for matrix based preconditioner
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
initializes the preconditioner for a matrix based operator
IPreconditioner ()
default constructor
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
clone constructor
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
constructor setting debug writer
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
virtual destructor
Public Member Functions inherited from ug::ILinearIterator< TAlgebra::vector_type >
virtual std::string config_string () const
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
returns the scaling
ILinearIterator ()
constructor
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
copy constructor
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
initialize for operator J(u) and linearization point u
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
initialize for linear operator L
void set_damp (number factor)
sets the damping to a constant factor
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
sets a scaling for the correction
virtual ~ILinearIterator ()
virtual destructor
Public Member Functions inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
returns the debug writer
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
returns true if the debug writer is set
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
clone constructor
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
set debug writer
virtual ~DebugWritingObject ()
virtual destructor
Public Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
set debug writer
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
returns the debug writer
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
returns true if the debug writer is set
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
writing debug output for a vector (if debug writer set)
virtual ~VectorDebugWritingObject ()
virtual destructor
Protected Member Functions
virtual const char * name () const
Name of preconditioner.
virtual bool postprocess ()
Postprocess routine.
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
Preprocess routine.
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
computes a new correction c = B*d
Protected Member Functions inherited from ug::DebugWritingObject< TAlgebra >
void enter_debug_writer_section (const char *secDir)
enters a debugging section
void enter_debug_writer_section (std::string secDir)
enters a debugging section
void leave_debug_writer_section ()
leaves a debugging section
void write_debug (const matrix_type &mat, const char *filename)
write debug output for a matrix (if debug writer set)
void write_debug (const matrix_type &mat, std::string name)
write debug output for a matrix (if debug writer set)
Protected Member Functions inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
enters a debugging section
void enter_vector_debug_writer_section (std::string secDir)
enters a debugging section
void leave_vector_debug_writer_section ()
leaves a debugging section
void print_debugger_message (const char *msg)
prints a debugger message (listing all the sections)
void print_debugger_message (std::string msg)
prints a debugger message (listing all the sections)
virtual void write_debug (const vector_type &vec, std::string name)
writing debug output for a vector (if debug writer set)
Protected Attributes
matrix_type m_A
number m_relax
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
init flag indicating if init has been called
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
underlying matrix based operator used for the preconditioner
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
underlying matrix based operator for calculation of defect
Protected Attributes inherited from ug::ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
the scaling
Protected Attributes inherited from ug::DebugWritingObject< TAlgebra >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Debug Writer.
Protected Attributes inherited from ug::VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Debug Writer.
Detailed Description
template<typename TAlgebra>
class ug::DiagVanka< TAlgebra >
Diagvanka Preconditioner, description see above diagvanka_step function.
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::DiagVanka< TAlgebra >::algebra_type
Algebra type.
base_type
template<typename TAlgebra > typedef IPreconditioner<TAlgebra> ug::DiagVanka< TAlgebra >::base_type
Base type.
matrix_operator_type
template<typename TAlgebra > typedef IPreconditioner<TAlgebra>::matrix_operator_type ug::DiagVanka< TAlgebra >::matrix_operator_type
Matrix Operator type.
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::DiagVanka< TAlgebra >::matrix_type
Matrix type.
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::DiagVanka< TAlgebra >::vector_type
Vector type.
Constructor & Destructor Documentation
DiagVanka()
template<typename TAlgebra > ug::DiagVanka< TAlgebra >::DiagVanka () inline
default constructor
References ug::DiagVanka< TAlgebra >::m_relax.
~DiagVanka()
template<typename TAlgebra > virtual ug::DiagVanka< TAlgebra >::~DiagVanka () inline virtual
Destructor.
Member Function Documentation
clone()
template<typename TAlgebra > virtual SmartPtr<ILinearIterator<vector_type> > ug::DiagVanka< TAlgebra >::clone () inline virtual
Clone.
Implements ug::ILinearIterator< TAlgebra::vector_type >.
References ug::ILinearIterator< TAlgebra::vector_type >::damping(), and ug::DebugWritingObject< TAlgebra >::debug_writer().
name()
template<typename TAlgebra > virtual const char* ug::DiagVanka< TAlgebra >::name () const inline protected virtual
Name of preconditioner.
Implements ug::IPreconditioner< TAlgebra >.
postprocess()
template<typename TAlgebra > virtual bool ug::DiagVanka< TAlgebra >::postprocess () inline protected virtual
Postprocess routine.
Implements ug::IPreconditioner< TAlgebra >.
preprocess()
template<typename TAlgebra > virtual bool ug::DiagVanka< TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) inline protected virtual
Preprocess routine.
Implements ug::IPreconditioner< TAlgebra >.
References pcl::CollectUniqueElements(), ug::DiagVanka< TAlgebra >::m_A, ug::MakeConsistent(), pcl::NumProcs(), and ug::SetDirichletRow().
set_relax()
template<typename TAlgebra > void ug::DiagVanka< TAlgebra >::set_relax (number omega) inline
set relaxation parameter
References ug::DiagVanka< TAlgebra >::m_relax, and omega.
step()
template<typename TAlgebra > virtual bool ug::DiagVanka< TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) inline protected virtual
computes a new correction c = B*d
This method computes a new correction c = B*d. It can only be called, when the preprocess has been done.
Parameters
[in] mat underlying matrix (i.e. L in L*u = f)
[out] c correction
[in] d defect
Returns
bool success flag
Implements ug::IPreconditioner< TAlgebra >.
References ug::Diag_Vanka_step(), ug::DiagVanka< TAlgebra >::m_A, ug::DiagVanka< TAlgebra >::m_relax, pcl::NumProcs(), and ug::PST_UNIQUE.
supports_parallel()
template<typename TAlgebra > virtual bool ug::DiagVanka< TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ug::ILinearIterator< TAlgebra::vector_type >.
Member Data Documentation
m_A
template<typename TAlgebra > matrix_type ug::DiagVanka< TAlgebra >::m_A protected
Referenced by ug::DiagVanka< TAlgebra >::preprocess(), and ug::DiagVanka< TAlgebra >::step().
m_relax
template<typename TAlgebra > number ug::DiagVanka< TAlgebra >::m_relax protected
Referenced by ug::DiagVanka< TAlgebra >::DiagVanka(), ug::DiagVanka< TAlgebra >::set_relax(), and ug::DiagVanka< TAlgebra >::step().
The documentation for this class was generated from the following file:
ugbase/lib_algebra/operator/preconditioner/vanka.h