ug4: ug::Hash< TKey, TValue > Class Template Reference
ug::Hash< TKey, TValue > Class Template Reference
#include <hash.h>
Classes
struct Entry
Public Types
typedef hash_iterator< key_t, value_t, Entry > iterator
typedef TKey key_t
typedef TValue value_t
Public Member Functions
iterator begin (const key_t &key)
size_t capacity () const
returns the capacity of the container in which key-value-pairs are stored.
void clear ()
bool empty () const
iterator end (const key_t &key)
void erase (const key_t &key)
value_t & get_entry (const key_t &key)
const value_t & get_entry (const key_t &key) const
bool get_entry (value_t &valOut, const key_t &key) const
bool has_entry (const key_t &key) const
Hash ()
Hash (size_t hashSize)
size_t hash_size () const
void insert (const key_t &key, const value_t &val)
void reserve (size_t size)
Reserves memory for key-value-pair storage.
void resize_hash (size_t size)
size_t size () const
returns the number of key-value-pairs currently stored in the hash
Private Member Functions
size_t find_entry (const key_t &key) const
size_t hash_index (const key_t &key) const
size_t invalid_index () const
Private Attributes
std::vector< Entry > m_entries
size_t m_firstUnusedEntry
std::vector< std::pair< size_t, size_t > > m_hashList
size_t m_numEntries
Member Typedef Documentation
template<class TKey, class TValue> typedef hash_iterator<key_t, value_t, Entry> ug::Hash< TKey, TValue >::iterator
template<class TKey, class TValue> typedef TKey ug::Hash< TKey, TValue >::key_t
template<class TKey, class TValue> typedef TValue ug::Hash< TKey, TValue >::value_t
Constructor & Destructor Documentation
template<class TKey , class TValue > ug::Hash< TKey, TValue >::Hash ()
References ug::Hash< TKey, TValue >::resize_hash().
template<class TKey , class TValue > ug::Hash< TKey, TValue >::Hash (size_t hashSize)
References ug::Hash< TKey, TValue >::resize_hash().
Member Function Documentation
template<class TKey , class TValue > Hash< TKey, TValue >::iterator ug::Hash< TKey, TValue >::begin (const key_t & key)
References ug::Hash< TKey, TValue >::empty(), ug::Hash< TKey, TValue >::end(), ug::Hash< TKey, TValue >::hash_index(), ug::Hash< TKey, TValue >::m_entries, and ug::Hash< TKey, TValue >::m_hashList.
Referenced by ug::Hash< TKey, TValue >::erase().
template<class TKey , class TValue > size_t ug::Hash< TKey, TValue >::capacity () const
returns the capacity of the container in which key-value-pairs are stored.
Use reserve to adjust this capacity. If the capacity would be too small to insert a new element, it will be automatically increased on element insertion.
See also
reserve
References ug::Hash< TKey, TValue >::clear(), and ug::Hash< TKey, TValue >::m_entries.
Referenced by ug::Hash< TKey, TValue >::reserve().
template<class TKey , class TValue > void ug::Hash< TKey, TValue >::clear ()
References ug::Hash< TKey, TValue >::empty(), ug::Hash< TKey, TValue >::invalid_index(), ug::Hash< TKey, TValue >::m_entries, ug::Hash< TKey, TValue >::m_firstUnusedEntry, ug::Hash< TKey, TValue >::m_hashList, and ug::Hash< TKey, TValue >::m_numEntries.
Referenced by ug::Hash< TKey, TValue >::capacity(), ug::AttachmentPipe< TElem, TElemHandler >::clear_attachments(), and ug::GenerateAlgebraIDHashList().
template<class TKey , class TValue > bool ug::Hash< TKey, TValue >::empty () const
References ug::Hash< TKey, TValue >::has_entry(), and ug::Hash< TKey, TValue >::m_numEntries.
Referenced by ug::Hash< TKey, TValue >::begin(), and ug::Hash< TKey, TValue >::clear().
template<class TKey , class TValue > Hash< TKey, TValue >::iterator ug::Hash< TKey, TValue >::end (const key_t & key)
References ug::Hash< TKey, TValue >::hash_index(), and ug::Hash< TKey, TValue >::invalid_index().
Referenced by ug::Hash< TKey, TValue >::begin().
template<class TKey , class TValue > void ug::Hash< TKey, TValue >::erase (const key_t & key)
References ug::Hash< TKey, TValue >::begin(), ug::Hash< TKey, TValue >::hash_index(), ug::Hash< TKey, TValue >::invalid_index(), ug::Hash< TKey, TValue >::m_entries, ug::Hash< TKey, TValue >::m_firstUnusedEntry, ug::Hash< TKey, TValue >::m_hashList, and ug::Hash< TKey, TValue >::m_numEntries.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::detach(), and ug::Hash< TKey, TValue >::insert().
template<class TKey , class TValue > size_t ug::Hash< TKey, TValue >::find_entry (const key_t & key) const private
References ug::Hash< TKey, TValue >::hash_index(), ug::Hash< TKey, TValue >::invalid_index(), ug::Hash< TKey, TValue >::m_entries, and ug::Hash< TKey, TValue >::m_hashList.
Referenced by ug::Hash< TKey, TValue >::get_entry(), ug::Hash< TKey, TValue >::has_entry(), and ug::Hash< TKey, TValue >::hash_index().
template<class TKey , class TValue > TValue & ug::Hash< TKey, TValue >::get_entry (const key_t & key)
References ug::Hash< TKey, TValue >::find_entry(), ug::Hash< TKey, TValue >::invalid_index(), ug::Hash< TKey, TValue >::m_entries, and UG_THROW.
Referenced by ug::DeserializeMultiGridElements(), ug::AttachmentPipe< TElem, TElemHandler >::detach(), ug::AttachmentPipe< TElem, TElemHandler >::get_data_container(), ug::Hash< TKey, TValue >::get_entry(), ug::vrl::invocation::getClassNodePtrByName(), ug::vrl::invocation::getExportedClassPtrByName(), and ug::Hash< TKey, TValue >::has_entry().
template<class TKey , class TValue > const TValue & ug::Hash< TKey, TValue >::get_entry (const key_t & key) const
References ug::Hash< TKey, TValue >::find_entry(), ug::Hash< TKey, TValue >::get_entry(), ug::Hash< TKey, TValue >::invalid_index(), ug::Hash< TKey, TValue >::m_entries, and UG_THROW.
template<class TKey , class TValue > bool ug::Hash< TKey, TValue >::get_entry (value_t & valOut, const key_t & key) const
References ug::Hash< TKey, TValue >::find_entry(), ug::Hash< TKey, TValue >::insert(), ug::Hash< TKey, TValue >::invalid_index(), and ug::Hash< TKey, TValue >::m_entries.
template<class TKey , class TValue > bool ug::Hash< TKey, TValue >::has_entry (const key_t & key) const
References ug::Hash< TKey, TValue >::find_entry(), ug::Hash< TKey, TValue >::get_entry(), and ug::Hash< TKey, TValue >::invalid_index().
Referenced by ug::Hash< TKey, TValue >::empty(), and ug::AttachmentPipe< TElem, TElemHandler >::has_attachment().
template<class TKey , class TValue > size_t ug::Hash< TKey, TValue >::hash_index (const key_t & key) const private
References ug::Hash< TKey, TValue >::find_entry(), ug::hash_key(), and ug::Hash< TKey, TValue >::m_hashList.
Referenced by ug::Hash< TKey, TValue >::begin(), ug::Hash< TKey, TValue >::end(), ug::Hash< TKey, TValue >::erase(), ug::Hash< TKey, TValue >::find_entry(), and ug::Hash< TKey, TValue >::insert().
template<class TKey , class TValue > size_t ug::Hash< TKey, TValue >::hash_size () const
References ug::Hash< TKey, TValue >::m_hashList, and ug::Hash< TKey, TValue >::reserve().
Referenced by ug::Hash< TKey, TValue >::resize_hash().
template<class TKey , class TValue > void ug::Hash< TKey, TValue >::insert (const key_t & key, const value_t & val)
References ug::Hash< TKey, TValue >::erase(), ug::Hash< TKey, TValue >::hash_index(), ug::Hash< TKey, TValue >::invalid_index(), ug::Hash< TKey, TValue >::m_entries, ug::Hash< TKey, TValue >::m_firstUnusedEntry, ug::Hash< TKey, TValue >::m_hashList, and ug::Hash< TKey, TValue >::m_numEntries.
Referenced by ug::AttachmentPipe< TElem, TElemHandler >::attach(), ug::ComPol_MatAddSetZeroInnerInterfaceCouplings< TMatrix >::collect(), ug::DeserializeMultiGridElements(), ug::GenerateAlgebraIDHashList(), ug::Hash< TKey, TValue >::get_entry(), and ug::vrl::invocation::initClasses().
template<class TKey, class TValue> size_t ug::Hash< TKey, TValue >::invalid_index () const inline private
Referenced by ug::Hash< TKey, TValue >::clear(), ug::Hash< TKey, TValue >::end(), ug::Hash< TKey, TValue >::erase(), ug::Hash< TKey, TValue >::find_entry(), ug::Hash< TKey, TValue >::get_entry(), ug::Hash< TKey, TValue >::has_entry(), ug::Hash< TKey, TValue >::insert(), and ug::Hash< TKey, TValue >::resize_hash().
template<class TKey , class TValue > void ug::Hash< TKey, TValue >::reserve (size_t size)
Reserves memory for key-value-pair storage.
See also
capacity
References ug::Hash< TKey, TValue >::capacity(), and ug::Hash< TKey, TValue >::m_entries.
Referenced by pcl::CollectUniqueElements(), ug::DeserializeMultiGridElements(), ug::GenerateAlgebraIDHashList(), ug::Hash< TKey, TValue >::hash_size(), and ug::vrl::invocation::initClasses().
template<class TKey , class TValue > void ug::Hash< TKey, TValue >::resize_hash (size_t size)
References ug::hash_key(), ug::Hash< TKey, TValue >::hash_size(), ug::Hash< TKey, TValue >::invalid_index(), ug::Hash< TKey, TValue >::Entry::key, ug::Hash< TKey, TValue >::m_entries, ug::Hash< TKey, TValue >::m_hashList, ug::Hash< TKey, TValue >::m_numEntries, ug::Hash< TKey, TValue >::Entry::next, and ug::Hash< TKey, TValue >::size().
Referenced by ug::GenerateAlgebraIDHashList(), and ug::Hash< TKey, TValue >::Hash().
template<class TKey, class TValue> size_t ug::Hash< TKey, TValue >::size () const
returns the number of key-value-pairs currently stored in the hash
Referenced by ug::Hash< TKey, TValue >::resize_hash().
Member Data Documentation
template<class TKey, class TValue> std::vector<Entry> ug::Hash< TKey, TValue >::m_entries private
Referenced by ug::Hash< TKey, TValue >::begin(), ug::Hash< TKey, TValue >::capacity(), ug::Hash< TKey, TValue >::clear(), ug::Hash< TKey, TValue >::erase(), ug::Hash< TKey, TValue >::find_entry(), ug::Hash< TKey, TValue >::get_entry(), ug::Hash< TKey, TValue >::insert(), ug::Hash< TKey, TValue >::reserve(), and ug::Hash< TKey, TValue >::resize_hash().
template<class TKey, class TValue> size_t ug::Hash< TKey, TValue >::m_firstUnusedEntry private
Referenced by ug::Hash< TKey, TValue >::clear(), ug::Hash< TKey, TValue >::erase(), and ug::Hash< TKey, TValue >::insert().
template<class TKey, class TValue> std::vector<std::pair<size_t, size_t> > ug::Hash< TKey, TValue >::m_hashList private
each entry holds a pair of indices pointing to the first and the last entry for the given hash-key.
Referenced by ug::Hash< TKey, TValue >::begin(), ug::Hash< TKey, TValue >::clear(), ug::Hash< TKey, TValue >::erase(), ug::Hash< TKey, TValue >::find_entry(), ug::Hash< TKey, TValue >::hash_index(), ug::Hash< TKey, TValue >::hash_size(), ug::Hash< TKey, TValue >::insert(), and ug::Hash< TKey, TValue >::resize_hash().
template<class TKey, class TValue> size_t ug::Hash< TKey, TValue >::m_numEntries private
Referenced by ug::Hash< TKey, TValue >::clear(), ug::Hash< TKey, TValue >::empty(), ug::Hash< TKey, TValue >::erase(), ug::Hash< TKey, TValue >::insert(), and ug::Hash< TKey, TValue >::resize_hash().
The documentation for this class was generated from the following files:
ugbase/common/util/hash.h
ugbase/common/util/hash_impl.hpp