ug4: ug::ComPol_Subset< TLayout > Class Template Reference
ug::ComPol_Subset< TLayout > Class Template Reference
#include <compol_subset.h>
Public Types
typedef Layout::Element Element
typedef Layout::Type GeomObj
typedef Layout::Interface Interface
typedef Interface::const_iterator InterfaceIter
typedef TLayout Layout
Public Types inherited from pcl::ICommunicationPolicy< TLayout >
typedef Layout::Interface Interface
typedef TLayout Layout
Public Member Functions
virtual bool collect (ug::BinaryBuffer &buff, const Interface &interface)
writes 1 for selected and 0 for unassigned interface entries
ComPol_Subset (ISubsetHandler &sel, bool overwrite=false)
Construct the communication policy with a ug::SubsetHandler.
virtual bool extract (ug::BinaryBuffer &buff, const Interface &interface)
reads marks from the given stream
virtual int get_required_buffer_size (const Interface &interface)
returns the size of the buffer in bytes, that will be required for interface-communication.
Public Member Functions inherited from pcl::ICommunicationPolicy< TLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
signals the beginning of a layout collection.
virtual bool begin_layout_extraction (const Layout *pLayout)
signals the beginning of a layout extraction.
virtual void begin_level_extraction (int level)
signals that a new layout-level will now be processed.
virtual bool end_layout_collection (const Layout *pLayout)
signals the end of a layout collection
virtual bool end_layout_extraction (const Layout *pLayout)
signals the end of a layout extraction
virtual ~ICommunicationPolicy ()
Protected Attributes
bool m_overwriteEnabled
ISubsetHandler & m_sh
Member Typedef Documentation
Element
template<class TLayout > typedef Layout::Element ug::ComPol_Subset< TLayout >::Element
GeomObj
template<class TLayout > typedef Layout::Type ug::ComPol_Subset< TLayout >::GeomObj
Interface
template<class TLayout > typedef Layout::Interface ug::ComPol_Subset< TLayout >::Interface
InterfaceIter
template<class TLayout > typedef Interface::const_iterator ug::ComPol_Subset< TLayout >::InterfaceIter
Layout
template<class TLayout > typedef TLayout ug::ComPol_Subset< TLayout >::Layout
Constructor & Destructor Documentation
ComPol_Subset()
template<class TLayout > ug::ComPol_Subset< TLayout >::ComPol_Subset (ISubsetHandler & sel, bool overwrite = false) inline
Construct the communication policy with a ug::SubsetHandler.
If overwrite is specified, the subset index in the target handler is simply overwritten (default is false).
Member Function Documentation
collect()
template<class TLayout > virtual bool ug::ComPol_Subset< TLayout >::collect (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
writes 1 for selected and 0 for unassigned interface entries
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::ISubsetHandler::get_subset_index(), ug::ComPol_Subset< TLayout >::m_sh, and ug::BinaryBuffer::write().
extract()
template<class TLayout > virtual bool ug::ComPol_Subset< TLayout >::extract (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
reads marks from the given stream
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::ISubsetHandler::assign_subset(), ug::ISubsetHandler::get_subset_index(), ug::ComPol_Subset< TLayout >::m_overwriteEnabled, ug::ComPol_Subset< TLayout >::m_sh, and ug::BinaryBuffer::read().
get_required_buffer_size()
template<class TLayout > virtual int ug::ComPol_Subset< TLayout >::get_required_buffer_size (const Interface & interface) inline virtual
returns the size of the buffer in bytes, that will be required for interface-communication.
Determines the size of the buffer on which the extract and receive methods for the given interface will operate. If the buffer-size can't be calculated on both sides (sender and receiver) this method should return -1. This will lead to an additional communication step in which buffer-sizes will be exchanged. If the buffer-size can be calculated on both sides, it makes sense to do so, since this leads to less communication and overall improved performance. The buffer-size has to exactly match the size of required memory. Make sure that you completely fill the buffer during collect(...) and that you read all data during extract(...). The default implementation returns -1.
Reimplemented from pcl::ICommunicationPolicy< TLayout >.
Member Data Documentation
m_overwriteEnabled
template<class TLayout > bool ug::ComPol_Subset< TLayout >::m_overwriteEnabled protected
Referenced by ug::ComPol_Subset< TLayout >::extract().
m_sh
template<class TLayout > ISubsetHandler& ug::ComPol_Subset< TLayout >::m_sh protected
Referenced by ug::ComPol_Subset< TLayout >::collect(), and ug::ComPol_Subset< TLayout >::extract().
The documentation for this class was generated from the following file:
ugbase/lib_grid/parallelization/util/compol_subset.h