ug4: ug::ScaleAddLinker< TData, dim, TDataScale, TRet > Class Template Reference
ug::ScaleAddLinker< TData, dim, TDataScale, TRet > Class Template Reference
#include <scale_add_linker.h>
Public Types
typedef StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TRet >, TRet, dim > base_type
Public Types inherited from ug::CplUserData< TData, dim, void >
typedef ICplUserData< dim > base_type
type of base class
Public Types inherited from ug::UserData< TData, dim, void >
typedef TData data_type
typedef void return_type
Public Member Functions
template<int refDim>
void eval_and_deriv (TRet vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, bool bDeriv, int s, std::vector< std::vector< TRet > > vvvDeriv[], const MathMatrix< refDim, dim > *vJT=NULL) const
void evaluate (TRet &value, const MathVector< dim > &globIP, number time, int si) const
template<int refDim>
void evaluate (TRet vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
ScaleAddLinker ()
constructor
ScaleAddLinker (const ScaleAddLinker &linker)
constructor
void add (SmartPtr< CplUserData< TDataScale, dim > > scale, SmartPtr< CplUserData< TData, dim > > data)
void add (number scale, SmartPtr< CplUserData< TData, dim > > data)
void add (SmartPtr< CplUserData< TDataScale, dim > > scale, number data)
void add (number scale, number data)
Public Member Functions inherited from ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TData >, TData, dim >
virtual void check_setup () const
returns if data is ok
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
compute values (and derivatives iff compDeriv == true)
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
compute values (and derivatives iff compDeriv == true, but only for the 'current' time point)
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
void evaluate (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
virtual SmartPtr< ICplUserData< dim > > needed_data (size_t i)
return needed data
virtual size_t num_input () const
number of inputs
virtual size_t num_needed_data () const
number of other Data this data depends on
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const
returns value for a global position
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
returns value for global positions
virtual bool requires_grid_fct () const
returns that a grid function is needed for evaluation
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
updates the function group
virtual void set_input (size_t i, SmartPtr< ICplUserData< dim > > input, SmartPtr< UserDataInfo > info)
sets an input
void set_num_input (size_t num)
sets the number of inputs
virtual bool zero_derivative () const
returns if derivative is zero
bool zero_derivative (size_t i) const
returns if the derivative of the i'th input is zero
Public Member Functions inherited from ug::StdUserData< TImpl, TData, dim, TRet, TBase >
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
Public Member Functions inherited from ug::CplUserData< TData, dim, void >
bool defined (size_t s, size_t ip) const
returns flag, if data is evaluated (for conditional data)
size_t num_ip (size_t s) const
returns the number of integration points
size_t num_series () const
explicitly forward some functions
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
register external callback, invoked when data storage changed
void unregister_storage_callback (DataImport< TData, dim > *obj)
register all callbacks registered by class
TData & value (size_t s, size_t ip)
returns the value at ip
const TData & value (size_t s, size_t ip) const
returns the value at ip
TData * values (size_t s)
returns all values for a series
const TData * values (size_t s) const
returns all values for a series
~CplUserData ()
destructor
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
returns true iff the time point specification is equal to the current one, or not specified
void clear ()
clear all data
virtual bool constant () const
returns if data is constant
int dim_local_ips () const
returns current local ip dimension
ICplUserData ()
default constructor
const MathVector< dim > & ip (size_t s, size_t ip) const
returns global ip
const MathVector< dim > * ips (size_t s) const
returns global ips
template<int ldim>
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
returns local ip
template<int ldim>
const MathVector< ldim > * local_ips (size_t s) const
returns local ips
size_t num_ip (size_t s) const
returns the number of integration points
size_t num_series () const
returns the number of ip series
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
set local positions without the specification of the time point, returns series id
template<int ldim>
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
set local positions, returns series id
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
set global positions
template<int ldim>
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
sets new local ip positions for a local ip series
void set_subset (int si)
set the subset of evaluation
void set_time_point (const size_t seriesId, const int timePointSpec)
sets a new time point for a local ip series
void set_time_point (size_t timePoint)
sets the current time point
void set_times (const std::vector< number > &vTime)
set evaluation time
int subset () const
returns the subset of evaluation
number time () const
get the current evaluation time
number time (size_t s) const
get the specified evaluation time
size_t time_point ()
returns the current time point
size_t time_point (size_t s) const
returns the time point specification (in particular, the current one, if the own one not specified)
int time_point_specification (size_t s) const
returns the time point specification (note: it may be -1, i.e. not specified)
virtual void update_dof_sizes (const LocalIndices &ind)
resize arrays
virtual ~ICplUserData ()
virtual desctructor
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
Function Group of functions.
const FunctionIndexMapping & map () const
get function mapping
size_t num_fct () const
number of functions this export depends on
virtual ~UserDataInfo ()
virtual destructor
Public Member Functions inherited from ug::UserData< TData, dim, void >
int get_dim () const
returns dimension
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, Vertex *vrt) const
returns a value at a vertex
std::string type () const
returns type of data as string (e.g. "Number", "Vector", "Matrix")
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
Protected Member Functions
size_t input_common_fct (size_t i, size_t fct) const
returns the number in the common FctGrp for a fct of an input
const TData & input_deriv (size_t i, size_t s, size_t ip, size_t fct, size_t dof) const
derivative of data at input at ip
size_t input_num_fct (size_t i) const
returns number of functions the input depends on
const TData & input_value (size_t i, size_t s, size_t ip) const
data at ip of input
size_t scale_common_fct (size_t i, size_t fct) const
returns the number in the common FctGrp for a fct of a scaling
const TDataScale & scale_deriv (size_t i, size_t s, size_t ip, size_t fct, size_t dof) const
derivative of data at input at ip
size_t scale_num_fct (size_t i) const
returns number of functions the scaling depends on
const TDataScale & scale_value (size_t i, size_t s, size_t ip) const
scale at ip of input
Protected Member Functions inherited from ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TData >, TData, dim >
void eval_deriv (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
void eval_deriv (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
ScaleAddLinker< TData, dim, TDataScale, TData > & getImpl ()
access to implementation
const ScaleAddLinker< TData, dim, TDataScale, TData > & getImpl () const
const access to implementation
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
forwards the global positions to the data inputs
size_t input_common_fct (size_t i, size_t fct) const
returns the number in the common FctGrp for a fct of an input
size_t input_num_fct (size_t i) const
returns number of functions the input depends on
virtual void local_ip_series_added (const size_t seriesID)
requests series id's from input data
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
forwards the local positions to the data inputs
size_t series_id (size_t i, size_t s) const
returns the series id set for the i'th input
Protected Member Functions inherited from ug::StdUserData< TImpl, TData, dim, TRet, TBase >
TImpl & getImpl ()
access to implementation
const TImpl & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::CplUserData< TData, dim, void >
void call_storage_callback () const
calls are registered external storage callbacks
void check_series (size_t s) const
checks in debug mode the correct index
void check_series_ip (size_t s, size_t ip) const
checks in debug mode the correct index
virtual void local_ip_series_to_be_cleared ()
free the data field memory and set series to zero
virtual void value_storage_changed (const size_t seriesID)
callback, invoked when storage of data has changed for a series
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
checks in debug mode the correct usage of indices
void check_s_ip (size_t s, size_t ip) const
checks in debug mode the correct usage of indices
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
help function to get local ips
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
Protected Attributes
std::vector< SmartPtr< DependentUserData< TData, dim > > > m_vpDependData
data input casted to dependend data
std::vector< SmartPtr< CplUserData< TDataScale, dim > > > m_vpScaleData
data input
std::vector< SmartPtr< DependentUserData< TDataScale, dim > > > m_vpScaleDependData
data input casted to dependend data
std::vector< SmartPtr< CplUserData< TData, dim > > > m_vpUserData
data input
Protected Attributes inherited from ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TData >, TData, dim >
std::vector< FunctionIndexMapping > m_vMap
Function mapping for each input relative to common FunctionGroup.
std::vector< SmartPtr< ICplUserData< dim > > > m_vspICplUserData
data input
std::vector< SmartPtr< UserDataInfo > > m_vspUserDataInfo
data input casted to IDependend data
std::vector< std::vector< size_t > > m_vvSeriesID
series id the linker uses to get data from input
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
default time point (or -1 if not specified)
int m_locPosDim
dimension of local position (-1 indicates no dim set)
std::vector< const MathVector< 1 > * > m_pvLocIP1d
local ips of dimension 1d-3d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
subset for evaluation
size_t m_timePoint
current time point (used if no explicit specification for series)
std::vector< bool > m_vMayChange
flags if local ips may change
std::vector< size_t > m_vNumIP
number of evaluation points (-1 indicates no ips set)
std::vector< number > m_vTime
time for evaluation
std::vector< int > m_vTimePoint
time points for the series
std::vector< const MathVector< dim > * > m_vvGlobPos
global ips
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
functions the data depends on
FunctionIndexMapping m_map
Mapping for import fct.
Detailed Description
template<typename TData, int dim, typename TDataScale, typename TRet = TData>
class ug::ScaleAddLinker< TData, dim, TDataScale, TRet >
This linker recombines the data like
l = s_1 * i_1 + ... + s_k * i_k
where, l, i_1, ..., i_k are of the same data type and the s_i are some scaling factor of a (possibly) different type, that is applicable to the data type
Template Parameters
TData exported and combined Data type
dim world dimension
TDataScale type of scaling data
Member Typedef Documentation
base_type
template<typename TData , int dim, typename TDataScale , typename TRet = TData> typedef StdDataLinker<ScaleAddLinker<TData, dim, TDataScale, TRet>, TRet, dim> ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::base_type
Constructor & Destructor Documentation
ScaleAddLinker() [1/2]
template<typename TData , int dim, typename TDataScale , typename TRet = TData> ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::ScaleAddLinker () inline
constructor
ScaleAddLinker() [2/2]
template<typename TData , int dim, typename TDataScale , typename TRet > ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::ScaleAddLinker (const ScaleAddLinker< TData, dim, TDataScale, TRet > & linker)
constructor
References ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::m_vpScaleData, ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::m_vpUserData, and UG_THROW.
Member Function Documentation
add() [1/4]
template<typename TData , int dim, typename TDataScale , typename TRet > void ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::add (number scale, number data)
adds an input to the list of summands scaled by a user data factor
add() [2/4]
template<typename TData , int dim, typename TDataScale , typename TRet > void ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::add (number scale, SmartPtr< CplUserData< TData, dim > > data)
adds an input to the list of summands scaled by a user data factor
add() [3/4]
template<typename TData , int dim, typename TDataScale , typename TRet > void ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::add (SmartPtr< CplUserData< TDataScale, dim > > scale, number data)
adds an input to the list of summands scaled by a user data factor
add() [4/4]
template<typename TData , int dim, typename TDataScale , typename TRet > void ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::add (SmartPtr< CplUserData< TDataScale, dim > > scale, SmartPtr< CplUserData< TData, dim > > data)
adds an input to the list of summands scaled by a user data factor
References UG_ASSERT.
eval_and_deriv()
template<typename TData , int dim, typename TDataScale , typename TRet > template<int refDim> void ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::eval_and_deriv (TRet vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, bool bDeriv, int s, std::vector< std::vector< TRet > > vvvDeriv[], const MathMatrix< refDim, dim > * vJT = NULL) const
References ug::linker_traits< TData, TDataIn, TRet >::mult_add(), s, and UG_ASSERT.
evaluate() [1/2]
template<typename TData , int dim, typename TDataScale , typename TRet > void ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::evaluate (TRet & value, const MathVector< dim > & globIP, number time, int si) const inline
References ug::linker_traits< TData, TDataIn, TRet >::mult_add().
evaluate() [2/2]
template<typename TData , int dim, typename TDataScale , typename TRet > template<int refDim> void ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::evaluate (TRet vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< refDim, dim > * vJT = NULL) const inline
input_common_fct()
template<typename TData , int dim, typename TDataScale , typename TRet = TData> size_t ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::input_common_fct (size_t i, size_t fct) const inline protected
returns the number in the common FctGrp for a fct of an input
References ug::StdDataLinker< TImpl, TData, dim >::input_common_fct().
input_deriv()
template<typename TData , int dim, typename TDataScale , typename TRet = TData> const TData& ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::input_deriv (size_t i, size_t s, size_t ip, size_t fct, size_t dof) const inline protected
derivative of data at input at ip
References ug::ICplUserData< dim >::ip(), ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::m_vpDependData, s, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TData >, TData, dim >::series_id(), and UG_ASSERT.
input_num_fct()
template<typename TData , int dim, typename TDataScale , typename TRet = TData> size_t ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::input_num_fct (size_t i) const inline protected
returns number of functions the input depends on
References ug::StdDataLinker< TImpl, TData, dim >::input_num_fct().
input_value()
template<typename TData , int dim, typename TDataScale , typename TRet = TData> const TData& ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::input_value (size_t i, size_t s, size_t ip) const inline protected
data at ip of input
References ug::ICplUserData< dim >::ip(), ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::m_vpUserData, s, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TData >, TData, dim >::series_id(), and UG_ASSERT.
scale_common_fct()
template<typename TData , int dim, typename TDataScale , typename TRet = TData> size_t ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::scale_common_fct (size_t i, size_t fct) const inline protected
returns the number in the common FctGrp for a fct of a scaling
References ug::StdDataLinker< TImpl, TData, dim >::input_common_fct().
scale_deriv()
template<typename TData , int dim, typename TDataScale , typename TRet = TData> const TDataScale& ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::scale_deriv (size_t i, size_t s, size_t ip, size_t fct, size_t dof) const inline protected
derivative of data at input at ip
References ug::ICplUserData< dim >::ip(), ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::m_vpScaleDependData, s, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TData >, TData, dim >::series_id(), and UG_ASSERT.
scale_num_fct()
template<typename TData , int dim, typename TDataScale , typename TRet = TData> size_t ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::scale_num_fct (size_t i) const inline protected
returns number of functions the scaling depends on
References ug::StdDataLinker< TImpl, TData, dim >::input_num_fct().
scale_value()
template<typename TData , int dim, typename TDataScale , typename TRet = TData> const TDataScale& ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::scale_value (size_t i, size_t s, size_t ip) const inline protected
scale at ip of input
References ug::ICplUserData< dim >::ip(), ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::m_vpScaleData, s, ug::StdDataLinker< ScaleAddLinker< TData, dim, TDataScale, TData >, TData, dim >::series_id(), and UG_ASSERT.
Member Data Documentation
m_vpDependData
template<typename TData , int dim, typename TDataScale , typename TRet = TData> std::vector<SmartPtr<DependentUserData<TData, dim> > > ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::m_vpDependData protected
data input casted to dependend data
Referenced by ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::input_deriv().
m_vpScaleData
template<typename TData , int dim, typename TDataScale , typename TRet = TData> std::vector<SmartPtr<CplUserData<TDataScale, dim> > > ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::m_vpScaleData protected
data input
Referenced by ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::scale_value(), and ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::ScaleAddLinker().
m_vpScaleDependData
template<typename TData , int dim, typename TDataScale , typename TRet = TData> std::vector<SmartPtr<DependentUserData<TDataScale, dim> > > ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::m_vpScaleDependData protected
data input casted to dependend data
Referenced by ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::scale_deriv().
m_vpUserData
template<typename TData , int dim, typename TDataScale , typename TRet = TData> std::vector<SmartPtr<CplUserData<TData, dim> > > ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::m_vpUserData protected
data input
Referenced by ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::input_value(), and ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::ScaleAddLinker().
The documentation for this class was generated from the following files:
ugbase/lib_disc/spatial_disc/user_data/linker/scale_add_linker.h
ugbase/lib_disc/spatial_disc/user_data/linker/scale_add_linker_impl.h