ug4: scripts/util/conv_rates_kinetic.lua File Reference
conv_rates_kinetic.lua File Reference
Functions
function util rates kinetic compute (ConvRateSetup)
function util rates kinetic StdLabel MeasLatexP (disc, p)
function util rates kinetic StdLabel MeasLatexQ (disc, p)
function util rates kinetic StdLabel MeasPdfP (disc, p)
function util rates kinetic StdLabel MeasPdfQ (disc, p)
function util rates kinetic NoMaxLevelPadding (p)
function util rates kinetic StdLabel NormLatex (f, t, n)
function util rates kinetic StdLabel NormPdf (f, t, n)
function util rates kinetic replot (gpOptions, file)
function util rates kinetic StdLabel SpaceLatex (x)
function util rates kinetic StdLabel SpacePdf (x)
function util rates kinetic StdAutoStepSize (lev, h)
function util rates kinetic StdMaxLevelPadding (p)
function util rates kinetic StdLabel TimeLatex ()
function util rates kinetic StdLabel TimePdf ()
function util rates kinetic StdLabel TimestepLatex ()
function util rates kinetic StdLabel TimestepPdf ()
Function Documentation
compute()
function util rates kinetic compute (ConvRateSetup)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :121-1133
Referenced by ug::DataEvaluator< TDomain >::prepare_elem(), ug::DataEvaluator< TDomain >::prepare_elem_loop(), ug::DataEvaluatorBase< TDomain, TElemDisc >::prepare_err_est_elem(), and ug::DataEvaluatorBase< TDomain, TElemDisc >::prepare_err_est_elem_loop().
MeasLatexP()
function util rates kinetic StdLabel MeasLatexP (disc , p)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :57-59
function util.rates.kinetic.StdLabel.MeasLatexP(disc, p)
  return disc.." $\\mathbb{P}_{"..p.."}$"
end
MeasLatexQ()
function util rates kinetic StdLabel MeasLatexQ (disc , p)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :61-63
function util.rates.kinetic.StdLabel.MeasLatexQ(disc, p)
  return disc.." $\\mathbb{Q}_{"..p.."}$"
end
MeasPdfP()
function util rates kinetic StdLabel MeasPdfP (disc , p)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :87-89
function util.rates.kinetic.StdLabel.MeasPdfP(disc, p)
  return disc.." $P_"..p.."$"
end
MeasPdfQ()
function util rates kinetic StdLabel MeasPdfQ (disc , p)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :91-93
function util.rates.kinetic.StdLabel.MeasPdfQ(disc, p)
  return disc.." $Q_"..p.."$"
end
NoMaxLevelPadding()
function util rates kinetic NoMaxLevelPadding (p)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :44-46
function util.rates.kinetic.NoMaxLevelPadding(p)
  return 0
end
NormLatex()
function util rates kinetic StdLabel NormLatex (f , t , n)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :78-85
function util.rates.kinetic.StdLabel.NormLatex(f, t, n)
  local gpType = {  ["exact"] =   "{}",
            ["best"] =    "h_{\text{min}}",
          }
  local gpNorm =  { l2 = "L_2", h1 = "H^1"}
  return "$\\norm{"..f.."_h - "..f.."_{"..gpType[t].."} }_{ "..gpNorm[n].."}$"
end
NormPdf()
function util rates kinetic StdLabel NormPdf (f , t , n)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :108-115
function util.rates.kinetic.StdLabel.NormPdf(f, t, n)
  local gpType = {  ["exact"] =   "{}",
            ["best"] =    "h_{\text{min}}",
          }
  local gpNorm =  { l2 = "L_2", h1 = "H^1"}
  return "$|| "..f.."_h - "..f.."_{"..gpType[t].."} ||_{"..gpNorm[n].."}$"
end
replot()
function util rates kinetic replot (gpOptions , file)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :1135-1168
SpaceLatex()
function util rates kinetic StdLabel SpaceLatex (x)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :65-68
function util.rates.kinetic.StdLabel.SpaceLatex(x)
  local gpSpaceLabel ={ DoFs = "Anzahl Unbekannte", h = "h"}
  return gpSpaceLabel[x]
end
References p.
SpacePdf()
function util rates kinetic StdLabel SpacePdf (x)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :95-98
function util.rates.kinetic.StdLabel.SpacePdf(x)
  local gpSpaceLabel ={ DoFs = "Unbekannte",  h = "h"}
  return gpSpaceLabel[x]
end
StdAutoStepSize()
function util rates kinetic StdAutoStepSize (lev , h)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :48-50
function util.rates.kinetic.StdAutoStepSize(lev, h)
  return h
end
StdMaxLevelPadding()
function util rates kinetic StdMaxLevelPadding (p)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :40-42
function util.rates.kinetic.StdMaxLevelPadding(p)
  return math.floor((p-1)/2)
end
TimeLatex()
function util rates kinetic StdLabel TimeLatex ()
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :74-76
function util.rates.kinetic.StdLabel.TimeLatex()
  return "Zeit"
end
TimePdf()
function util rates kinetic StdLabel TimePdf ()
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :104-106
function util.rates.kinetic.StdLabel.TimePdf()
  return "Zeit"
end
TimestepLatex()
function util rates kinetic StdLabel TimestepLatex ()
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :70-72
function util.rates.kinetic.StdLabel.TimestepLatex()
  return "$\\Delta t$"
end
TimestepPdf()
function util rates kinetic StdLabel TimestepPdf ()
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / conv_rates_kinetic.lua :100-102
function util.rates.kinetic.StdLabel.TimestepPdf()
  return "dt"
end