var dir_2377bdc3bce2db83d3a95ac44ec5f4e1 =
[
    [ "adaption_surface_grid_function.cpp", "adaption__surface__grid__function_8cpp.html", null ],
    [ "adaption_surface_grid_function.h", "adaption__surface__grid__function_8h.html", "adaption__surface__grid__function_8h" ],
    [ "adaption_surface_grid_function_impl.h", "adaption__surface__grid__function__impl_8h.html", "adaption__surface__grid__function__impl_8h" ],
    [ "approximation_space.cpp", "approximation__space_8cpp.html", "approximation__space_8cpp" ],
    [ "approximation_space.h", "approximation__space_8h.html", "approximation__space_8h" ],
    [ "dof_position_util.cpp", "dof__position__util_8cpp.html", "dof__position__util_8cpp" ],
    [ "dof_position_util.h", "dof__position__util_8h.html", "dof__position__util_8h" ],
    [ "error_elem_marking_strategy.h", "error__elem__marking__strategy_8h.html", "error__elem__marking__strategy_8h" ],
    [ "error_indicator.h", "error__indicator_8h.html", "error__indicator_8h" ],
    [ "error_indicator_util.h", "error__indicator__util_8h.html", "error__indicator__util_8h" ],
    [ "gradient_evaluators.h", "gradient__evaluators_8h.html", "gradient__evaluators_8h" ],
    [ "grid_function.cpp", "grid__function_8cpp.html", null ],
    [ "grid_function.h", "grid__function_8h.html", "grid__function_8h" ],
    [ "grid_function_coordinate_util.h", "grid__function__coordinate__util_8h.html", "grid__function__coordinate__util_8h" ],
    [ "grid_function_global_user_data.h", "grid__function__global__user__data_8h.html", "grid__function__global__user__data_8h" ],
    [ "grid_function_impl.h", "grid__function__impl_8h.html", null ],
    [ "grid_function_user_data.h", "grid__function__user__data_8h.html", "grid__function__user__data_8h" ],
    [ "grid_function_user_data_explicit.h", "grid__function__user__data__explicit_8h.html", "grid__function__user__data__explicit_8h" ],
    [ "grid_function_util.h", "grid__function__util_8h.html", "grid__function__util_8h" ],
    [ "integrate.h", "integrate_8h.html", "integrate_8h" ],
    [ "integrate_flux.h", "integrate__flux_8h.html", "integrate__flux_8h" ],
    [ "interpolate.h", "interpolate_8h.html", "interpolate_8h" ],
    [ "interpolate_inner.h", "interpolate__inner_8h.html", "interpolate__inner_8h" ],
    [ "level_transfer.h", "level__transfer_8h.html", "level__transfer_8h" ],
    [ "local_transfer.h", "local__transfer_8h.html", "local__transfer_8h" ],
    [ "local_transfer_interface.cpp", "local__transfer__interface_8cpp.html", "local__transfer__interface_8cpp" ],
    [ "local_transfer_interface.h", "local__transfer__interface_8h.html", "local__transfer__interface_8h" ],
    [ "max_error.h", "max__error_8h.html", "max__error_8h" ],
    [ "metric_spaces.h", "metric__spaces_8h.html", "metric__spaces_8h" ]
];