ug4: ugbase/lib_disc/spatial_disc/disc_util/fv1ib_geom_impl.h File Reference
fv1ib_geom_impl.h File Reference
#include "common/util/provider.h"
#include "fv1ib_geom.h"
#include "lib_disc/reference_element/reference_element.h"
#include "lib_disc/quadrature/quadrature.h"
#include "lib_algebra/common/operations_vec.h"
Functions
template<typename TRefElem >
static void ComputeBFMidID (const TRefElem &rRefElem, int side, MidID vMidID[], int co)
template<int dim, typename TRefElem , int maxMid>
static void ComputeMidPoints (const TRefElem &rRefElem, const MathVector< dim > vCorner[], MathVector< dim > vvMid[][maxMid])
template<typename TRefElem >
static void ComputeSCVFMidID (const TRefElem &rRefElem, MidID vMidID[], int i)
template<typename TRefElem >
static void ComputeSCVMidID (const TRefElem &rRefElem, MidID vMidID[], int i)
template<int dim, int maxMid>
static void CopyCornerByMidID (MathVector< dim > vCorner[], const MidID vMidID[], MathVector< dim > vvMidPos[][maxMid], const size_t numCo)
Function Documentation
ComputeBFMidID()
template<typename TRefElem > static void ComputeBFMidID (const TRefElem & rRefElem, int side, MidID vMidID[], int co) static
Parameters
[in] i indicates that scvf corresponds to i'th corner of ref elem
References dim, ug::ROID_PYRAMID, and UG_THROW.
Referenced by CopyCornerByMidID().
ComputeMidPoints()
template<int dim, typename TRefElem , int maxMid> static void ComputeMidPoints (const TRefElem & rRefElem, const MathVector< dim > vCorner[], MathVector< dim > vvMid[][maxMid]) static
Template Parameters
dim dimension of coordinates
TRefElem Reference element type
maxMid Maximum number of elements for all dimensions
References dim, ug::ROID_PYRAMID, and ug::VecScaleAdd().
ComputeSCVFMidID()
template<typename TRefElem > static void ComputeSCVFMidID (const TRefElem & rRefElem, MidID vMidID[], int i) static
Parameters
[in] i indicates that scvf corresponds to i'th edge of ref elem
References dim, ug::ROID_PYRAMID, and UG_THROW.
Referenced by CopyCornerByMidID().
ComputeSCVMidID()
template<typename TRefElem > static void ComputeSCVMidID (const TRefElem & rRefElem, MidID vMidID[], int i) static
Parameters
[in] i indicates that scvf corresponds to i'th corner of ref elem
References dim, ug::ROID_PYRAMID, and UG_THROW.
Referenced by CopyCornerByMidID().
CopyCornerByMidID()
template<int dim, int maxMid> static void CopyCornerByMidID (MathVector< dim > vCorner[], const MidID vMidID[], MathVector< dim > vvMidPos[][maxMid], const size_t numCo) static
References ug::AveragePositions(), ug::CollectEdgesSorted(), ug::CollectFacesSorted(), ug::CollectVertices(), ComputeBFMidID(), ComputeSCVFMidID(), ComputeSCVMidID(), dim, ug::ReferenceMapping< ref_elem_type, worldDim >::isLinear, ug::MatVecMult(), ug::ROID_PYRAMID, UG_ASSERT, UG_CATCH_THROW, UG_LOG, UG_THROW, ug::VecDot(), ug::VecSubtract(), and ug::VecTwoNorm().