ug4: normal_calculation
normal_calculation
lib_grid » algorithms
contains methods for the calculation of normals of edges, faces and volume elements.
Functions
vector2 ug::CalculateNormal (EdgeVertices *edge, Grid::AttachmentAccessor< Vertex, APosition2 > &aaPos)
vector3 ug::CalculateNormal (FaceVertices *face, Grid::AttachmentAccessor< Vertex, APosition > &aaPos)
template<class TAAPos >
TAAPos::ValueType ug::CalculateOuterNormal (Edge *v, int sideIndex, TAAPos aaPos)
template<class TAAPos >
TAAPos::ValueType ug::CalculateOuterNormal (Face *v, int sideIndex, TAAPos aaPos)
template<class TAAPos >
TAAPos::ValueType ug::CalculateOuterNormal (GridObject *v, int sideIndex, TAAPos aaPos)
template<class TAAPos >
TAAPos::ValueType ug::CalculateOuterNormal (Vertex *v, int sideIndex, TAAPos aaPos)
Calculates the outer normal of the i-th side of the given grid object.
template<class TAAPos >
TAAPos::ValueType ug::CalculateOuterNormal (Volume *v, int sideIndex, TAAPos aaPos)
Detailed Description
contains methods for the calculation of normals of edges, faces and volume elements.
Function Documentation
CalculateNormal() [1/2]
vector2 ug::CalculateNormal (EdgeVertices * edge, Grid::AttachmentAccessor< Vertex, APosition2 > & aaPos) inline
CalculateNormal() [2/2]
vector3 ug::CalculateNormal (FaceVertices * face, Grid::AttachmentAccessor< Vertex, APosition > & aaPos) inline
CalculateOuterNormal() [1/5]
template<class TAAPos > TAAPos::ValueType ug::CalculateOuterNormal (Edge * v, int sideIndex, TAAPos aaPos) inline
References ug::VecNormalize(), ug::VecSubtract(), and ug::EdgeVertices::vertex().
CalculateOuterNormal() [2/5]
template<class TAAPos > TAAPos::ValueType ug::CalculateOuterNormal (Face * v, int sideIndex, TAAPos aaPos) inline
References ug::CalculateCenter(), ug::DropAPerpendicular(), ug::Face::edge_desc(), ug::VecNormalize(), ug::VecSubtract(), and ug::EdgeVertices::vertex().
CalculateOuterNormal() [3/5]
template<class TAAPos > TAAPos::ValueType ug::CalculateOuterNormal (GridObject * v, int sideIndex, TAAPos aaPos) inline
References ug::GridObject::base_object_id(), ug::CalculateOuterNormal(), ug::EDGE, ug::FACE, UG_THROW, ug::VERTEX, and ug::VOLUME.
CalculateOuterNormal() [4/5]
template<class TAAPos > TAAPos::ValueType ug::CalculateOuterNormal (Vertex * v, int sideIndex, TAAPos aaPos) inline
Calculates the outer normal of the i-th side of the given grid object.
References ug::VecSet().
Referenced by ug::CalculateOuterNormal(), and ug::EvaluateGradientJump_SideIntegral().
CalculateOuterNormal() [5/5]
template<class TAAPos > TAAPos::ValueType ug::CalculateOuterNormal (Volume * v, int sideIndex, TAAPos aaPos) inline
References ug::CalculateNormal(), and ug::Volume::face_desc().