ug4: volume_calculation
volume_calculation
lib_grid » algorithms
contains methods for the calculation of the volumes of edge, face and volume elements
Functions
template<int dim>
void ug::CalculateBoundingBox (size_t npoints, const MathVector< dim > points[], MathVector< dim > &vMinBB, MathVector< dim > &vMaxBB)
Determine the bounding box for a set of points.
template<class TAAPos >
number ug::CalculateVolume (Volume *elem, TAAPos aaPos)
Calculates the volume of the given element.
template<class TAAPos >
number ug::CalculateVolume (Tetrahedron *elem, TAAPos aaPos)
Calculates the volume of the given element.
template<class TAAPos >
number ug::CalculateVolume (Pyramid *elem, TAAPos aaPos)
Calculates the volume of the given element.
template<class TAAPos >
number ug::CalculateVolume (Prism *elem, TAAPos aaPos)
Calculates the volume of the given element.
template<class TAAPos >
number ug::CalculateVolume (Hexahedron *elem, TAAPos aaPos)
Calculates the volume of the given element.
template<class TAAPos >
number ug::CalculateVolume (Octahedron *elem, TAAPos aaPos)
Calculates the volume of the given element.
template<class TAAPos >
number ug::CalculateVolume (FaceVertices *elem, TAAPos aaPos)
Calculates the volume of the given element.
template<class TAAPos >
number ug::CalculateVolume (EdgeVertices *elem, TAAPos aaPos)
Calculates the volume of the given element.
template<class TAAPos >
number ug::CalculateVolume (Vertex *elem, TAAPos aaPos)
Calculates the volume of the given element.
template<class TIterator , class TAAPos >
number ug::CalculateVolume (TIterator begin, TIterator end, TAAPos aaPos)
Calculates the volume of the given element.
Detailed Description
contains methods for the calculation of the volumes of edge, face and volume elements
Function Documentation
CalculateBoundingBox()
template<int dim> void ug::CalculateBoundingBox (size_t npoints, const MathVector< dim > points[], MathVector< dim > & vMinBB, MathVector< dim > & vMaxBB)
Determine the bounding box for a set of points.
References dim.
CalculateVolume() [1/10]
template<class TAAPos > number ug::CalculateVolume (EdgeVertices * elem, TAAPos aaPos) inline
Calculates the volume of the given element.
Make sure that aaPos has at least the same dimensionality as the specified element!
Note
If Volume-elements feature bended sides, the returned value is only an approximation to the actual volume.
References ug::EdgeLength().
CalculateVolume() [2/10]
template<class TAAPos > number ug::CalculateVolume (FaceVertices * elem, TAAPos aaPos) inline
Calculates the volume of the given element.
Make sure that aaPos has at least the same dimensionality as the specified element!
Note
If Volume-elements feature bended sides, the returned value is only an approximation to the actual volume.
References ug::FaceArea().
CalculateVolume() [3/10]
template<class TAAPos > number ug::CalculateVolume (Hexahedron * elem, TAAPos aaPos) inline
Calculates the volume of the given element.
Make sure that aaPos has at least the same dimensionality as the specified element!
Note
If Volume-elements feature bended sides, the returned value is only an approximation to the actual volume.
References ug::CalculateHexahedronVolume(), and ug::Hexahedron::vertex().
CalculateVolume() [4/10]
template<class TAAPos > number ug::CalculateVolume (Octahedron * elem, TAAPos aaPos) inline
Calculates the volume of the given element.
Make sure that aaPos has at least the same dimensionality as the specified element!
Note
If Volume-elements feature bended sides, the returned value is only an approximation to the actual volume.
References ug::CalculateOctahedronVolume(), and ug::Octahedron::vertex().
CalculateVolume() [5/10]
template<class TAAPos > number ug::CalculateVolume (Prism * elem, TAAPos aaPos) inline
Calculates the volume of the given element.
Make sure that aaPos has at least the same dimensionality as the specified element!
Note
If Volume-elements feature bended sides, the returned value is only an approximation to the actual volume.
References ug::CalculatePrismVolume(), and ug::Prism::vertex().
CalculateVolume() [6/10]
template<class TAAPos > number ug::CalculateVolume (Pyramid * elem, TAAPos aaPos) inline
Calculates the volume of the given element.
Make sure that aaPos has at least the same dimensionality as the specified element!
Note
If Volume-elements feature bended sides, the returned value is only an approximation to the actual volume.
References ug::CalculatePyramidVolume(), and ug::Pyramid::vertex().
CalculateVolume() [7/10]
template<class TAAPos > number ug::CalculateVolume (Tetrahedron * elem, TAAPos aaPos) inline
Calculates the volume of the given element.
Make sure that aaPos has at least the same dimensionality as the specified element!
Note
If Volume-elements feature bended sides, the returned value is only an approximation to the actual volume.
References ug::CalculateTetrahedronVolume(), and ug::Tetrahedron::vertex().
CalculateVolume() [8/10]
template<class TIterator , class TAAPos > number ug::CalculateVolume (TIterator begin, TIterator end, TAAPos aaPos) inline
Calculates the volume of the given element.
Make sure that aaPos has at least the same dimensionality as the specified element!
Note
If Volume-elements feature bended sides, the returned value is only an approximation to the actual volume.
References ug::CalculateVolume().
CalculateVolume() [9/10]
template<class TAAPos > number ug::CalculateVolume (Vertex * elem, TAAPos aaPos) inline
Calculates the volume of the given element.
Make sure that aaPos has at least the same dimensionality as the specified element!
Note
If Volume-elements feature bended sides, the returned value is only an approximation to the actual volume.
CalculateVolume() [10/10]
template<class TAAPos > number ug::CalculateVolume (Volume * elem, TAAPos aaPos) inline
Calculates the volume of the given element.
Make sure that aaPos has at least the same dimensionality as the specified element!
Note
If Volume-elements feature bended sides, the returned value is only an approximation to the actual volume.
References ug::Volume::reference_object_id(), ug::ROID_HEXAHEDRON, ug::ROID_OCTAHEDRON, ug::ROID_PRISM, ug::ROID_PYRAMID, ug::ROID_TETRAHEDRON, and UG_THROW.
Referenced by ug::CalculateVolume(), ug::EvaluateGradientJump_Norm(), ug::EvaluateGradientJump_SideIntegral(), ug::FindLargestVolume(), ug::FindSmallestVolume(), ug::AnisotropicBalanceWeights< dim >::get_weight_impl(), ug::MarkForAdaption_GradientAverage(), and ug::WeightedFaceSmooth().