ug4: Registry
Registry
ugbase » Bridge
Classes
class ug::bridge::ClassCastProvider
provides castings from derived classes to base classes
class ug::bridge::ClassGroupDesc
groups classes. One of the members is the default member.
class ug::bridge::ClassHierarchy
Class Hierarchy Helper Class for UG Registry This class stores class names and their subclasses.
class ug::bridge::ClassNameNode
node for class names
class ug::bridge::ClassNameProvider< TClass >
provides the name for a class
struct ug::bridge::constructor_traits< T, TTypelist >
struct ug::bridge::constructor_traits< T, TypeList< T1 > >
struct ug::bridge::constructor_traits< T, TypeList< T1, T2 > >
struct ug::bridge::constructor_traits< T, TypeList< T1, T2, T3 > >
struct ug::bridge::constructor_traits< T, TypeList< T1, T2, T3, T4 > >
struct ug::bridge::constructor_traits< T, TypeList< T1, T2, T3, T4, T5 > >
struct ug::bridge::constructor_traits< T, TypeList< T1, T2, T3, T4, T5, T6 > >
struct ug::bridge::constructor_traits< T, TypeList< T1, T2, T3, T4, T5, T6, T7 > >
struct ug::bridge::constructor_traits< T, TypeList< T1, T2, T3, T4, T5, T6, T7, T8 > >
struct ug::bridge::constructor_traits< T, TypeList<> >
struct ug::bridge::ConstructorProxy< TClass, TMethod >
struct ug::bridge::CreateParameterInfo< TTypeList >
struct ug::bridge::CreateParameterInfo< TypeList<> >
struct ug::bridge::CreateParameterInfoOut< TRet >
Creation of return value.
struct ug::bridge::CreateParameterInfoOut< CustomReturn >
struct ug::bridge::CreateParameterInfoOut< void >
Creation of void return value (template specialization)
class ug::bridge::CustomReturn
class ug::bridge::ExportedClass< TClass >
This template class represents real c++ classes in the registry.
class ug::bridge::ExportedClassBaseImpl
A base implementation with non-template methods.
class ug::bridge::ExportedConstructor
describing information for constructor
class ug::bridge::ExportedFunction
This class describes a wrapper for a c++ - function, that is exported by ug.
class ug::bridge::ExportedFunctionBase
Base class for function/method export.
class ug::bridge::ExportedFunctionGroup
Groups of Functions - useful to realize overloaded functions.
class ug::bridge::ExportedMethod
class ug::bridge::ExportedMethodGroup
Groups of methods - useful to realize overloaded methods.
struct ug::bridge::func_traits< TFunc >
struct ug::bridge::func_traits< TRet(*)()>
struct ug::bridge::func_traits< TRet(*)(P1)>
struct ug::bridge::func_traits< TRet(*)(T1, T2)>
struct ug::bridge::func_traits< TRet(*)(T1, T2, T3)>
struct ug::bridge::func_traits< TRet(*)(T1, T2, T3, T4)>
struct ug::bridge::func_traits< TRet(*)(T1, T2, T3, T4, T5)>
struct ug::bridge::func_traits< TRet(*)(T1, T2, T3, T4, T5, T6)>
struct ug::bridge::func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7)>
struct ug::bridge::func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7, T8)>
struct ug::bridge::func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7, T8, T9)>
struct ug::bridge::func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)>
struct ug::bridge::func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)>
struct ug::bridge::func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)>
struct ug::bridge::func_traits< TRet(TClass::*)() const >
struct ug::bridge::func_traits< TRet(TClass::*)()>
struct ug::bridge::func_traits< TRet(TClass::*)(P1) const >
struct ug::bridge::func_traits< TRet(TClass::*)(P1)>
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2) const >
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2)>
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3) const >
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3)>
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4) const >
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4)>
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5) const >
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5)>
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6) const >
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6)>
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7) const >
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7)>
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7, T8) const >
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7, T8)>
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7, T8, T9) const >
struct ug::bridge::func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7, T8, T9)>
struct ug::bridge::FunctionProxy< TFunc, TRet >
struct ug::bridge::FunctionProxy< TFunc, void >
class ug::bridge::IExportedClass
Base class for exported Classes.
class ug::bridge::JSONConstructible
struct ug::bridge::MethodProxy< TClass, TMethod, TRet >
struct ug::bridge::MethodProxy< TClass, TMethod, CustomReturn >
struct ug::bridge::MethodProxy< TClass, TMethod, void >
class ug::bridge::MethodPtrWrapper
class ug::bridge::ParameterInfo
a stack holding parameter infos about a parameter stack
class ug::bridge::ParameterStack
A stack that can hold values together with their type-id.
struct ug::bridge::ParameterStackToTypeValueList< TTypeList, index >
struct ug::bridge::ParameterStackToTypeValueList< TypeList<>, index >
struct ug::bridge::ParameterInfo::PushType< bool >
struct ug::bridge::ParameterStack::PushType< bool >
struct ug::bridge::ParameterInfo::PushType< const char * >
struct ug::bridge::ParameterStack::PushType< const char * >
struct ug::bridge::ParameterStack::PushType< const std::string & >
struct ug::bridge::ParameterInfo::PushType< const std::string & >
struct ug::bridge::ParameterStack::PushType< const std::vector< bool > & >
struct ug::bridge::ParameterInfo::PushType< const std::vector< bool > & >
struct ug::bridge::ParameterInfo::PushType< const std::vector< const char * > & >
struct ug::bridge::ParameterStack::PushType< const std::vector< const char * > & >
struct ug::bridge::ParameterStack::PushType< const std::vector< const T * > & >
struct ug::bridge::ParameterInfo::PushType< const std::vector< const TClass * > & >
struct ug::bridge::ParameterStack::PushType< const std::vector< ConstSmartPtr< T > > & >
struct ug::bridge::ParameterInfo::PushType< const std::vector< ConstSmartPtr< TClass > > & >
struct ug::bridge::ParameterInfo::PushType< const std::vector< double > & >
struct ug::bridge::ParameterStack::PushType< const std::vector< double > & >
struct ug::bridge::ParameterInfo::PushType< const std::vector< float > & >
struct ug::bridge::ParameterStack::PushType< const std::vector< float > & >
struct ug::bridge::ParameterStack::PushType< const std::vector< int > & >
struct ug::bridge::ParameterInfo::PushType< const std::vector< int > & >
struct ug::bridge::ParameterStack::PushType< const std::vector< size_t > & >
struct ug::bridge::ParameterInfo::PushType< const std::vector< size_t > & >
struct ug::bridge::ParameterStack::PushType< const std::vector< SmartPtr< T > > & >
struct ug::bridge::ParameterInfo::PushType< const std::vector< SmartPtr< TClass > > & >
struct ug::bridge::ParameterStack::PushType< const std::vector< std::string > & >
struct ug::bridge::ParameterInfo::PushType< const std::vector< std::string > & >
struct ug::bridge::ParameterStack::PushType< const std::vector< T * > & >
struct ug::bridge::ParameterInfo::PushType< const std::vector< TClass * > & >
struct ug::bridge::ParameterStack::PushType< const T & >
struct ug::bridge::ParameterStack::PushType< const T * >
struct ug::bridge::ParameterInfo::PushType< const TClass & >
struct ug::bridge::ParameterInfo::PushType< const TClass * >
struct ug::bridge::ParameterStack::PushType< ConstSmartPtr< T > >
struct ug::bridge::ParameterInfo::PushType< ConstSmartPtr< TClass > >
struct ug::bridge::ParameterInfo::PushType< double >
struct ug::bridge::ParameterStack::PushType< double >
struct ug::bridge::ParameterInfo::PushType< float >
struct ug::bridge::ParameterStack::PushType< float >
struct ug::bridge::ParameterInfo::PushType< int >
struct ug::bridge::ParameterStack::PushType< int >
struct ug::bridge::ParameterStack::PushType< size_t >
struct ug::bridge::ParameterInfo::PushType< size_t >
struct ug::bridge::ParameterStack::PushType< SmartPtr< T > >
struct ug::bridge::ParameterInfo::PushType< SmartPtr< TClass > >
struct ug::bridge::ParameterInfo::PushType< std::string >
struct ug::bridge::ParameterStack::PushType< std::string >
struct ug::bridge::ParameterStack::PushType< std::vector< bool > >
struct ug::bridge::ParameterInfo::PushType< std::vector< bool > >
struct ug::bridge::ParameterStack::PushType< std::vector< const char * > >
struct ug::bridge::ParameterInfo::PushType< std::vector< const char * > >
struct ug::bridge::ParameterStack::PushType< std::vector< const T * > >
struct ug::bridge::ParameterInfo::PushType< std::vector< const TClass * > >
struct ug::bridge::ParameterStack::PushType< std::vector< ConstSmartPtr< T > > >
struct ug::bridge::ParameterInfo::PushType< std::vector< ConstSmartPtr< TClass > > >
struct ug::bridge::ParameterInfo::PushType< std::vector< double > >
struct ug::bridge::ParameterStack::PushType< std::vector< double > >
struct ug::bridge::ParameterInfo::PushType< std::vector< float > >
struct ug::bridge::ParameterStack::PushType< std::vector< float > >
struct ug::bridge::ParameterStack::PushType< std::vector< int > >
struct ug::bridge::ParameterInfo::PushType< std::vector< int > >
struct ug::bridge::ParameterStack::PushType< std::vector< size_t > >
struct ug::bridge::ParameterInfo::PushType< std::vector< size_t > >
struct ug::bridge::ParameterStack::PushType< std::vector< SmartPtr< T > > >
struct ug::bridge::ParameterInfo::PushType< std::vector< SmartPtr< TClass > > >
struct ug::bridge::ParameterInfo::PushType< std::vector< std::string > >
struct ug::bridge::ParameterStack::PushType< std::vector< std::string > >
struct ug::bridge::ParameterStack::PushType< std::vector< T * > >
struct ug::bridge::ParameterInfo::PushType< std::vector< TClass * > >
struct ug::bridge::ParameterStack::PushType< T & >
struct ug::bridge::ParameterStack::PushType< T * >
struct ug::bridge::ParameterInfo::PushType< TClass & >
struct ug::bridge::ParameterInfo::PushType< TClass * >
class ug::bridge::Registry
Registry for functions and classes that are exported to scripts and visualizations.
struct ug::bridge::ParameterStack::ToType< bool >
struct ug::bridge::ParameterStack::ToType< const char * >
struct ug::bridge::ParameterStack::ToType< const std::string & >
struct ug::bridge::ParameterStack::ToType< const std::vector< bool > & >
struct ug::bridge::ParameterStack::ToType< const std::vector< const char * > & >
struct ug::bridge::ParameterStack::ToType< const std::vector< const T * > & >
struct ug::bridge::ParameterStack::ToType< const std::vector< ConstSmartPtr< T > > & >
struct ug::bridge::ParameterStack::ToType< const std::vector< double > & >
struct ug::bridge::ParameterStack::ToType< const std::vector< float > & >
struct ug::bridge::ParameterStack::ToType< const std::vector< int > & >
struct ug::bridge::ParameterStack::ToType< const std::vector< size_t > & >
struct ug::bridge::ParameterStack::ToType< const std::vector< SmartPtr< T > > & >
struct ug::bridge::ParameterStack::ToType< const std::vector< std::string > & >
struct ug::bridge::ParameterStack::ToType< const std::vector< T * > & >
struct ug::bridge::ParameterStack::ToType< const T & >
struct ug::bridge::ParameterStack::ToType< const T * >
struct ug::bridge::ParameterStack::ToType< const void * >
struct ug::bridge::ParameterStack::ToType< ConstSmartPtr< T > >
struct ug::bridge::ParameterStack::ToType< ConstSmartPtr< void > >
struct ug::bridge::ParameterStack::ToType< double >
struct ug::bridge::ParameterStack::ToType< float >
struct ug::bridge::ParameterStack::ToType< int >
struct ug::bridge::ParameterStack::ToType< size_t >
struct ug::bridge::ParameterStack::ToType< SmartPtr< std::vector< std::pair< const void *, const ClassNameNode * > > > >
struct ug::bridge::ParameterStack::ToType< SmartPtr< std::vector< std::pair< ConstSmartPtr< void >, const ClassNameNode * > > > >
struct ug::bridge::ParameterStack::ToType< SmartPtr< std::vector< std::pair< SmartPtr< void >, const ClassNameNode * > > > >
struct ug::bridge::ParameterStack::ToType< SmartPtr< std::vector< std::pair< void *, const ClassNameNode * > > > >
struct ug::bridge::ParameterStack::ToType< SmartPtr< T > >
struct ug::bridge::ParameterStack::ToType< SmartPtr< void > >
struct ug::bridge::ParameterStack::ToType< std::string >
struct ug::bridge::ParameterStack::ToType< std::vector< bool > >
struct ug::bridge::ParameterStack::ToType< std::vector< const char * > >
struct ug::bridge::ParameterStack::ToType< std::vector< const T * > >
struct ug::bridge::ParameterStack::ToType< std::vector< ConstSmartPtr< T > > >
struct ug::bridge::ParameterStack::ToType< std::vector< double > >
struct ug::bridge::ParameterStack::ToType< std::vector< float > >
struct ug::bridge::ParameterStack::ToType< std::vector< int > >
struct ug::bridge::ParameterStack::ToType< std::vector< size_t > >
struct ug::bridge::ParameterStack::ToType< std::vector< SmartPtr< T > > >
struct ug::bridge::ParameterStack::ToType< std::vector< std::string > >
struct ug::bridge::ParameterStack::ToType< std::vector< T * > >
struct ug::bridge::ParameterStack::ToType< T & >
struct ug::bridge::ParameterStack::ToType< T * >
struct ug::bridge::ParameterStack::ToType< void * >
struct ug::bridge::UG_REGISTRY_ERROR_FunctionOrMethodNameMissing
Exception throw, if method name has not been given.
struct ug::bridge::UGError_ClassCastFailed
struct ug::bridge::UGRegistryError
Macros
#define FUNC_TRAITS_GENERAL_CONST_MEMBER
#define FUNC_TRAITS_GENERAL_NON_CONST_MEMBER
Typedefs
typedef boost::function< void(Registry *pReg)> ug::bridge::FuncRegistryChanged
declaration of registry callback function.
Functions
template<class TClass >
void ug::bridge::CastAndDelete (const void *ptr)
Performs a reinterpret cast on the given pointer, then calls delete on it.
template<>
void ug::bridge::CastAndDelete< void > (const void *ptr)
string ug::bridge::ClassHierarchyString (const Registry &reg, const char *classname)
string ug::bridge::ClassInfo (const IExportedClass &c)
Prints the (const) method of one class.
string ug::bridge::ClassInfo (const Registry &reg, const char *classname)
bool ug::bridge::ClassNameTreeContains (const ClassNameNode &node, const std::string &name)
returns if a name is contained in the name tree at node or in base classes
bool ug::bridge::ClassNameTreeWay (std::vector< size_t > &vWay, const ClassNameNode &node, const std::string &name)
bool ug::bridge::ClassNameVecContains (const std::vector< const char * > &names, const std::string &name)
returns if a name is contained in the name vector
string ug::bridge::ClassUsageExact (const Registry &reg, const char *classname, bool OutParameters)
string ug::bridge::ConstructorInfo (const ExportedConstructor &constr, const char *classname, const char *highlightclassname)
template<typename TClass >
void ug::bridge::DestructorProxy (void *obj)
void ug::bridge::ExtractClassNameVec (std::vector< const char * > &names, const ClassNameNode &node, bool clearVec=true)
returns the vector containing all names in the name tree for node and its base classes
const ExportedFunction * ug::bridge::FindFunction (const Registry &reg, const char *functionname)
string ug::bridge::FunctionInfo (const ExportedFunctionBase &thefunc, bool isConst, const char *classname, const char *highlightclassname, bool bPrintHelp)
string ug::bridge::FunctionInfo (const Registry &reg, const char *functionname)
void ug::bridge::GetClassHierarchy (ClassHierarchy &hierarchy, const Registry &reg)
template<typename TClass >
const char * ug::bridge::GetClassName ()
std::string ug::GetRegistryIdentifierMessage ()
bool ug::bridge::IsClassInParameters (const ParameterInfo &par, const char *classname)
bool ug::IsValidRegistryIdentifier (const std::string &name)
string ug::bridge::ParameterToString (const ParameterInfo &par, int i)
Gets a description of the i-th parameter of a ParameterStack todo: perhaps this function would be better somewhere else like in parameter_stack.cpp.
template<typename TBase , typename TDerived >
void * ug::bridge::StaticVoidCast (void *DerivVoidPtr)
static cast function for two classes
Detailed Description
Macro Definition Documentation
FUNC_TRAITS_GENERAL_CONST_MEMBER
#define FUNC_TRAITS_GENERAL_CONST_MEMBER
Value:
  static const bool custom_return = std::is_same<TRet, CustomReturn>::value; \
  static const bool const_method = true;\
  typedef TClass class_type;\
  typedef TRet return_type
FUNC_TRAITS_GENERAL_NON_CONST_MEMBER
#define FUNC_TRAITS_GENERAL_NON_CONST_MEMBER
Value:
  static const bool custom_return = std::is_same<TRet, CustomReturn>::value; \
  static const bool const_method = false;\
  typedef TClass class_type;\
  typedef TRet return_type
Typedef Documentation
FuncRegistryChanged
typedef boost::function<void (Registry* pReg)> ug::bridge::FuncRegistryChanged
declaration of registry callback function.
Allows to notify listeners if the registry changes. Since FuncRegistryChanged is a functor, you can either pass a normal function or a member function of a class (Have a look at boost::bind in the second case).
Function Documentation
CastAndDelete()
template<class TClass > void ug::bridge::CastAndDelete (const void * ptr)
Performs a reinterpret cast on the given pointer, then calls delete on it.
CastAndDelete< void >()
template<> void ug::bridge::CastAndDelete< void > (const void * ptr) inline
References UG_THROW.
ClassHierarchyString()
UG_API std::string ug::bridge::ClassHierarchyString (const Registry & reg, const char * classname)
References ug::bridge::IExportedClass::class_names(), ug::bridge::ClassHierarchy::find_class(), ug::bridge::Registry::get_class(), ug::bridge::GetClassHierarchy(), and ug::bridge::PrintClassSubHierarchy().
Referenced by ug::bridge::ScriptPrintClassHierarchy(), and ug::bridge::UGTypeInfo().
ClassInfo() [1/2]
UG_API std::string ug::bridge::ClassInfo (const IExportedClass & c)
Prints the (const) method of one class.
References ug::bridge::FunctionInfo(), ug::bridge::IExportedClass::get_const_method(), ug::bridge::IExportedClass::get_method(), ug::bridge::IExportedClass::is_instantiable(), ug::bridge::IExportedClass::name(), ug::bridge::IExportedClass::num_const_methods(), and ug::bridge::IExportedClass::num_methods().
Referenced by ug::Factory< TBase, TPairSeq >::register_class(), and ug::bridge::UGTypeInfo().
ClassInfo() [2/2]
UG_API std::string ug::bridge::ClassInfo (const Registry & reg, const char * classname)
Searches the classname in the Registry and prints info of the class
References ug::bridge::Registry::get_class().
ClassNameTreeContains()
bool ug::bridge::ClassNameTreeContains (const ClassNameNode & node, const std::string & name)
returns if a name is contained in the name tree at node or in base classes
References ug::bridge::ClassNameNode::base_class(), name, ug::bridge::ClassNameNode::name(), and ug::bridge::ClassNameNode::num_base_classes().
Referenced by ug::bridge::lua::LuaParsing< const void * >::checkAndGet(), ug::bridge::lua::LuaParsing< ConstSmartPtr< void > >::checkAndGet(), ug::bridge::lua::LuaParsing< SmartPtr< void > >::checkAndGet(), ug::bridge::lua::LuaParsing< void * >::checkAndGet(), ug::vrl::compareParamTypes(), ug::bridge::ClassNameProvider< TClass >::is_a(), and ug::script::UGIsBaseClass().
ClassNameTreeWay()
bool ug::bridge::ClassNameTreeWay (std::vector< size_t > & vWay, const ClassNameNode & node, const std::string & name)
returns an std::vector that contains in reverse order the base class that must be used in the Class Hierarchy to get to the base class
References ug::bridge::ClassNameNode::base_class(), name, ug::bridge::ClassNameNode::name(), and ug::bridge::ClassNameNode::num_base_classes().
Referenced by ug::bridge::ClassCastProvider::cast_to_base_class().
ClassNameVecContains()
bool ug::bridge::ClassNameVecContains (const std::vector< const char * > & names, const std::string & name)
returns if a name is contained in the name vector
References name.
Referenced by ug::bridge::ClassInstantiations().
ClassUsageExact()
UG_API std::string ug::bridge::ClassUsageExact (const Registry & reg, const char * classname, bool OutParameters)
Parameters
reg Registry
classname the class (and only this class) to print usage in functions/member functions of.
OutParameters
References ug::bridge::FunctionInfo(), ug::bridge::Registry::get_class(), ug::bridge::IExportedClass::get_const_method(), ug::bridge::Registry::get_function(), ug::bridge::IExportedClass::get_method(), ug::bridge::IsClassInParameters(), ug::bridge::IExportedClass::name(), ug::bridge::Registry::num_classes(), ug::bridge::IExportedClass::num_const_methods(), ug::bridge::Registry::num_functions(), ug::bridge::IExportedClass::num_methods(), ug::bridge::ExportedFunctionBase::params_in(), and ug::bridge::ExportedFunctionBase::params_out().
Referenced by ug::bridge::ClassUsage().
ConstructorInfo()
UG_API std::string ug::bridge::ConstructorInfo (const ExportedConstructor & constr, const char * classname, const char * highlightclassname)
Prints parameters of the constructor constr. If highlightclassname != NULL, it highlights parameters which implement the highlightclassname class.
References UG_LOG.
Referenced by ug::bridge::lua::LuaConstructor().
DestructorProxy()
template<typename TClass > void ug::bridge::DestructorProxy (void * obj)
ExtractClassNameVec()
void ug::bridge::ExtractClassNameVec (std::vector< const char * > & names, const ClassNameNode & node, bool clearVec)
returns the vector containing all names in the name tree for node and its base classes
References ug::bridge::ClassNameNode::base_class(), ug::bridge::ClassNameNode::name(), and ug::bridge::ClassNameNode::num_base_classes().
Referenced by ug::vrl::getBaseClassNames(), and ug::bridge::ClassNameProvider< TClass >::names().
FindFunction()
UG_API const ExportedFunction * ug::bridge::FindFunction (const Registry & reg, const char * functionname)
References ug::bridge::Registry::get_function(), ug::bridge::ExportedFunctionBase::name(), and ug::bridge::Registry::num_functions().
Referenced by ug::bridge::FunctionInfo(), and ug::bridge::GetLuaGlobals().
FunctionInfo() [1/2]
UG_API std::string ug::bridge::FunctionInfo (const ExportedFunctionBase & thefunc, bool isConst, const char * classname, const char * highlightclassname, bool bPrintHelp)
Prints parameters of the function thefunc. If highlightclassname != NULL, it highlights parameters which implement the highlightclassname class.
References ug::bridge::ExportedFunctionBase::help(), ug::bridge::ExportedFunctionBase::name(), ug::bridge::PrintParametersOut(), and ug::bridge::ExportedFunctionBase::tooltip().
FunctionInfo() [2/2]
UG_API std::string ug::bridge::FunctionInfo (const Registry & reg, const char * functionname)
searches for a function named functionname in the registry and prints it
Finds the class classname in the default ug registry and returns IExportedClass pointer if found, otherwise NULL
References ug::bridge::FindFunction().
Referenced by ug::bridge::ClassInfo(), and ug::bridge::ClassUsageExact().
GetClassHierarchy()
UG_API void ug::bridge::GetClassHierarchy (ClassHierarchy & hierarchy, const Registry & reg)
inits hierarchy with all classes of UGBridge
References ug::bridge::Registry::get_class(), ug::bridge::ClassHierarchy::insert_class(), ug::bridge::ClassHierarchy::name, ug::bridge::Registry::num_classes(), ug::bridge::ClassHierarchy::sort(), and ug::bridge::ClassHierarchy::subclasses.
Referenced by ug::bridge::ClassHierarchyString().
GetClassName()
template<typename TClass > const char* ug::bridge::GetClassName ()
References ug::bridge::ClassNameProvider< TClass >::name().
GetRegistryIdentifierMessage()
UG_API std::string ug::GetRegistryIdentifierMessage ()
Returns a message describing which registry identifiers are valid and which are not.
Returns
message string
Referenced by ug::bridge::Registry::add_and_get_function(), ug::bridge::Registry::add_class_(), ug::bridge::ExportedClass< TClass >::add_method(), and ug::bridge::Registry::get_class_group().
IsClassInParameters()
UG_API bool ug::bridge::IsClassInParameters (const ParameterInfo & par, const char * classname)
Returns
true, if the class classname is in a parameter in the ParameterStack par
References ug::bridge::ParameterInfo::class_name(), ug::bridge::ParameterInfo::class_name_node(), ug::bridge::ParameterInfo::size(), and ug::bridge::ParameterInfo::type().
Referenced by ug::bridge::ClassUsageExact().
IsValidRegistryIdentifier()
UG_API bool ug::IsValidRegistryIdentifier (const std::string & name)
Checks whether the specified name is a valid registry identifier name.
Note: identifiers starting with F_, C_, I_ or containing __ (double underscore) or being equal to 'constructor' are invalid.
Parameters
name name to check
Returns
true if the specified name is valid; false otherwise
References ug::Contains(), name, and ug::StartsWith().
Referenced by ug::bridge::Registry::add_and_get_function(), ug::bridge::Registry::add_class_(), ug::bridge::ExportedClass< TClass >::add_method(), and ug::bridge::Registry::get_class_group().
ParameterToString()
UG_API std::string ug::bridge::ParameterToString (const ParameterInfo & par, int i)
Gets a description of the i-th parameter of a ParameterStack todo: perhaps this function would be better somewhere else like in parameter_stack.cpp.
References ug::bridge::ParameterInfo::class_name(), ug::bridge::ParameterInfo::is_vector(), and ug::bridge::ParameterInfo::type().
Referenced by ug::bridge::ExportedFunctionBase::check_consistency(), ug::bridge::PrintParametersIn(), and ug::bridge::PrintParametersOut().
StaticVoidCast()
template<typename TBase , typename TDerived > void* ug::bridge::StaticVoidCast (void * DerivVoidPtr)
static cast function for two classes