ug4: Utility Bridge
Utility Bridge
ugbase » Bridge » Misc Bridge
Functions
static int ug::bridge::ExecuteSystemCommand (const char *cmd)
static string ug::bridge::GetAppsPath ()
static string ug::bridge::GetBinPath ()
static string ug::bridge::GetCurrentPath ()
std::vector< std::string > ug::bridge::GetDirsInDir (const char *dir)
std::vector< std::string > ug::bridge::GetFilesInDir (const char *dir)
static string ug::bridge::GetRootPath ()
static string ug::bridge::GetScriptPath ()
void ug::bridge::int_srand (int seed)
void ug::bridge::RegisterBridge_Util (Registry &reg, string parentGroup)
void ug::bridge::SetMinSecondsUntilProgress (size_t s)
Detailed Description
Function Documentation
ExecuteSystemCommand()
static int ug::bridge::ExecuteSystemCommand (const char * cmd) static
This function executes the given string in a system shell (if available)
Parameters
[in] cmd The shell command to execute
Returns
1 if no shell available
Referenced by ug::bridge::RegisterBridge_Util().
GetAppsPath()
static string ug::bridge::GetAppsPath () static
References ug::APPS_PATH.
Referenced by ug::bridge::RegisterBridge_Util().
GetBinPath()
static string ug::bridge::GetBinPath () static
References ug::BIN_PATH.
Referenced by ug::bridge::RegisterBridge_Util().
GetCurrentPath()
static string ug::bridge::GetCurrentPath () static
Referenced by ug::bridge::RegisterBridge_Util().
GetDirsInDir()
std::vector<std::string> ug::bridge::GetDirsInDir (const char * dir)
References ug::GetDirectoriesInDirectory().
Referenced by ug::bridge::RegisterBridge_Util().
GetFilesInDir()
std::vector<std::string> ug::bridge::GetFilesInDir (const char * dir)
References ug::GetFilesInDirectory().
Referenced by ug::bridge::RegisterBridge_Util().
GetRootPath()
static string ug::bridge::GetRootPath () static
References ug::ROOT_PATH.
Referenced by ug::bridge::RegisterBridge_Util().
GetScriptPath()
static string ug::bridge::GetScriptPath () static
References ug::SCRIPT_PATH.
Referenced by ug::bridge::RegisterBridge_Util().
int_srand()
void ug::bridge::int_srand (int seed)
Referenced by ug::bridge::RegisterBridge_Util().
RegisterBridge_Util()
void ug::bridge::RegisterBridge_Util (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_function(), ug::ChangeDirectory(), ug::CreateDirectoryTMP(), ug::CurrentWorkingDirectory(), ug::DirectoryExists(), ug::bridge::ExecuteSystemCommand(), ug::FileCompare(), ug::FileExists(), ug::FindFileInStandardPaths(), boost::get(), ug::bridge::GetAppsPath(), ug::bridge::GetBinPath(), ug::bridge::GetCurrentPath(), ug::bridge::GetDirsInDir(), ug::bridge::GetFilesInDir(), ug::bridge::GetRootPath(), ug::bridge::GetScriptPath(), ug::GetTmpPath(), ug::bridge::int_srand(), name, num_cols(), num_rows(), OVERLOADED_FUNCTION_PTR, ug::SetAppsPath(), ug::bridge::SetMinSecondsUntilProgress(), ug::SetPluginPath(), ug::SetRootPath(), ug::SetScriptPath(), transpose(), and ug::UGForceExit().
Referenced by ug::bridge::RegisterStandardBridges().
SetMinSecondsUntilProgress()
void ug::bridge::SetMinSecondsUntilProgress (size_t s)
References ug::g_minSecondUntilProgress, and s.
Referenced by ug::bridge::RegisterBridge_Util().