ug4: Parallel Algebra Communication Scheme
Parallel Algebra Communication Scheme
lib_algebra » Parallel Algebra
Communication Scheme for parallel Algebra.
Classes
class ug::CommunicationScheme< TDerived, TValue >
CRTP Base class for communications on layout/interfaces.
class ug::CommunicationScheme< TDerived, bool >
CRTP Base class for communications on layout/interfaces.
class ug::StdArrayCommunicationScheme< TArray >
Communication Scheme for synchronization of arrays or similar datastructures.
Functions
template<typename TCommunicationScheme >
void ug::CommunicateFromMasterToSlave (HorizontalAlgebraLayouts &layouts, TCommunicationScheme &scheme)
template<typename TCommunicationScheme >
void ug::CommunicateFromSlaveToMaster (HorizontalAlgebraLayouts &layouts, TCommunicationScheme &scheme)
template<typename TCommunicationScheme >
void ug::CommunicateOnInterfaces (pcl::InterfaceCommunicator< IndexLayout > &communicator, const IndexLayout &sendingLayout, const IndexLayout &receivingLayout, TCommunicationScheme &scheme)
sends data over a CommunicationScheme from a sendingLayout to a receivingLayout
template<typename TPIDs , typename TReceiveScheme >
void ug::ReceiveOnInterfaces (pcl::InterfaceCommunicator< IndexLayout > &communicator, TPIDs &pids, IndexLayout &layout, TReceiveScheme &receiver)
receives data over a interface based on a CommunicationScheme on a subgroup of processes
template<typename TSendingScheme , typename TPIDs >
void ug::SendOnInterfaces (pcl::InterfaceCommunicator< IndexLayout > &communicator, TPIDs &pids, IndexLayout &layout, TSendingScheme &sender)
sends data over a interface based on a CommunicationScheme to a subgroup of processes
Detailed Description
Communication Scheme for parallel Algebra.
Function Documentation
CommunicateFromMasterToSlave()
template<typename TCommunicationScheme > void ug::CommunicateFromMasterToSlave (HorizontalAlgebraLayouts & layouts, TCommunicationScheme & scheme)
References ug::CommunicateOnInterfaces(), ug::HorizontalAlgebraLayouts::master(), ug::HorizontalAlgebraLayouts::proc_comm(), and ug::HorizontalAlgebraLayouts::slave().
CommunicateFromSlaveToMaster()
template<typename TCommunicationScheme > void ug::CommunicateFromSlaveToMaster (HorizontalAlgebraLayouts & layouts, TCommunicationScheme & scheme)
References ug::CommunicateOnInterfaces(), ug::HorizontalAlgebraLayouts::master(), ug::HorizontalAlgebraLayouts::proc_comm(), and ug::HorizontalAlgebraLayouts::slave().
CommunicateOnInterfaces()
template<typename TCommunicationScheme > void ug::CommunicateOnInterfaces (pcl::InterfaceCommunicator< IndexLayout > & communicator, const IndexLayout & sendingLayout, const IndexLayout & receivingLayout, TCommunicationScheme & scheme)
sends data over a CommunicationScheme from a sendingLayout to a receivingLayout
CommunicateOnInterfaces
Template Parameters
TCommunicationScheme type of the sending/receiving CommunicationScheme
Parameters
communicator InterfaceCommunicator used to send data
sendingLayout layout to send data from
receivingLayout layout to receive data from
scheme CommunicationScheme to use
References pcl::SingleLevelLayout< TInterface >::begin(), ug::BinaryBuffer::buffer(), pcl::InterfaceCommunicator< TLayout >::communicate(), pcl::SingleLevelLayout< TInterface >::end(), pcl::SingleLevelLayout< TInterface >::interface(), pcl::SingleLevelLayout< TInterface >::proc_id(), pcl::InterfaceCommunicator< TLayout >::receive_raw(), pcl::InterfaceCommunicator< TLayout >::send_raw(), and ug::BinaryBuffer::write_pos().
Referenced by ug::CommunicateFromMasterToSlave(), ug::CommunicateFromSlaveToMaster(), and ug::ConsistencyCheck().
ReceiveOnInterfaces()
template<typename TPIDs , typename TReceiveScheme > void ug::ReceiveOnInterfaces (pcl::InterfaceCommunicator< IndexLayout > & communicator, TPIDs & pids, IndexLayout & layout, TReceiveScheme & receiver)
receives data over a interface based on a CommunicationScheme on a subgroup of processes
ReceiveOnInterfaces
Template Parameters
TReceiveScheme type of the receiving CommunicationScheme
TPIDs type of the container of the pids
Parameters
communicator InterfaceCommunicator used to send data
pids pids to receive from
layout layout to use to receive
receiver receiving CommunicationScheme
References pcl::InterfaceCommunicator< TLayout >::communicate(), pcl::SingleLevelLayout< TInterface >::interface(), and pcl::InterfaceCommunicator< TLayout >::receive_raw().
SendOnInterfaces()
template<typename TSendingScheme , typename TPIDs > void ug::SendOnInterfaces (pcl::InterfaceCommunicator< IndexLayout > & communicator, TPIDs & pids, IndexLayout & layout, TSendingScheme & sender)
sends data over a interface based on a CommunicationScheme to a subgroup of processes
SendOnInterfaces
Template Parameters
TSendingScheme type of the sending CommunicationScheme
TPIDs type of the container of the pids
Parameters
communicator InterfaceCommunicator used to send data
pids pids to send to
layout layout to use to send
sender sending CommunicationScheme
References pcl::InterfaceCommunicator< TLayout >::communicate(), and pcl::InterfaceCommunicator< TLayout >::send_raw().