ug4: Periodic Bounadry Bridge
Periodic Bounadry Bridge
ugbase » Bridge » Domain Bridge
Classes
struct ug::bridge::periodicBoundary::Functionality
Functions
void ug::bridge::periodicBoundary::print_all_identifications (Grid &g)
Detailed Description
Function Documentation
print_all_identifications()
void ug::bridge::periodicBoundary::print_all_identifications (Grid & g)
References ug::Grid::has_periodic_boundaries(), ug::Grid::periodic_boundary_manager(), and ug::PeriodicBoundaryManager::print_identification().
Referenced by ug::bridge::periodicBoundary::Functionality::Common().