ug4: Profiler Bridge
Profiler Bridge
ugbase » Bridge » Misc Bridge
Functions
void ug::bridge::RegisterBridge_Profiler (Registry &reg, string parentGroup)
Detailed Description
Function Documentation
RegisterBridge_Profiler()
void ug::bridge::RegisterBridge_Profiler (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_function(), ug::GetProfileNode(), ug::GetProfilerAvailable(), name, OVERLOADED_CONST_METHOD_PTR, OVERLOADED_FUNCTION_PTR, ug::SetFrequency(), ug::SetShinyCallLoggingMaxFrequency(), ug::UGOutputProfileStatsOnExit(), ug::UpdateProfiler_BridgeImpl(), ug::WriteCallLog(), and ug::WriteProfileDataXML().
Referenced by ug::bridge::RegisterStandardBridges().