ug4: Selection Bridge
Selection Bridge
ugbase » Bridge » Domain Bridge
Classes
struct ug::bridge::Selection::Functionality
Functions
void ug::SelectAssociatedElements (ISelector &sel, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces)
Selects / Deselects associated (low dimensional) elements.
void ug::SelectDomainElements (ISelector &sel, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVolumes)
Selects / Deselects all elements.
template<class TDomain >
void ug::SelectDomainSubset (ISelector &sel, TDomain &dom, int subsetIndex, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVolumes)
Selects / Deselects elements in the given subset of the given domain.
Detailed Description
Function Documentation
SelectAssociatedElements()
void ug::SelectAssociatedElements (ISelector & sel, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces)
Selects / Deselects associated (low dimensional) elements.
References ug::GridObjectCollection::begin(), ug::GridObjectCollection::end(), ug::ISelector::get_grid_objects(), and ug::GridObjectCollection::num_levels().
Referenced by ug::bridge::Selection::Functionality::Common().
SelectDomainElements()
void ug::SelectDomainElements (ISelector & sel, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVolumes)
Selects / Deselects all elements.
References ug::Grid::begin(), ug::Grid::end(), ug::ISelector::grid(), and ug::ISelector::select().
Referenced by ug::bridge::Selection::Functionality::Common().
SelectDomainSubset()
template<class TDomain > void ug::SelectDomainSubset (ISelector & sel, TDomain & dom, int subsetIndex, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVolumes)
Selects / Deselects elements in the given subset of the given domain.