ug4: Parallel Algebra Consistency Check
Parallel Algebra Consistency Check
lib_algebra » Parallel Algebra
with ConsistencyCheck, you can check the consistency of any array over layouts
Classes
class ug::ConsistencyCheckClass< TVec, TValue >
class ug::ConsistencyCheckClassSend< TVec, TValue >
class ug::ConsistencyCheckClassSend< TVec, bool >
Functions
template<typename TVec >
void ug::ConsistencyCheck (const TVec &vec, const HorizontalAlgebraLayouts &layout, std::string name="")
template<typename TVec >
void ug::ConsistencyCheck (const TVec &vec, pcl::InterfaceCommunicator< IndexLayout > &com, const pcl::ProcessCommunicator &pc, const IndexLayout &masterLayout, const IndexLayout &slaveLayout, std::string name="")
receives data over a interface based on a CommunicationScheme on a subgroup of processes
Detailed Description
with ConsistencyCheck, you can check the consistency of any array over layouts
Function Documentation
ConsistencyCheck() [1/2]
template<typename TVec > void ug::ConsistencyCheck (const TVec & vec, const HorizontalAlgebraLayouts & layout, std::string name = "")
References pcl::AllProcsTrue(), ug::HorizontalAlgebraLayouts::comm(), ug::CommunicateOnInterfaces(), ug::ConsistencyCheckClass< TVec, TValue >::isOK(), ug::HorizontalAlgebraLayouts::master(), name, ug::HorizontalAlgebraLayouts::proc_comm(), PROFILE_FUNC_GROUP, ug::HorizontalAlgebraLayouts::slave(), and UG_COND_THROW.
ConsistencyCheck() [2/2]
template<typename TVec > void ug::ConsistencyCheck (const TVec & vec, pcl::InterfaceCommunicator< IndexLayout > & com, const pcl::ProcessCommunicator & pc, const IndexLayout & masterLayout, const IndexLayout & slaveLayout, std::string name = "")
receives data over a interface based on a CommunicationScheme on a subgroup of processes
ConsistencyCheck
Template Parameters
TVec vector type to check
Parameters
vec vec to check
com InterfaceCommunicator used to send data
pc ProcessCommunicator used for AllProcsTrue
masterLayout layout to send data
slaveLayout layout to receive data and check if equal
name name to be given out if not consistent. default ""
References pcl::AllProcsTrue(), ug::CommunicateOnInterfaces(), ug::ConsistencyCheckClass< TVec, TValue >::isOK(), name, PROFILE_FUNC_GROUP, and UG_COND_THROW.