ug4: PCL Bridge
PCL Bridge
ugbase » Bridge » Misc Bridge
Functions
template<typename T >
static T ug::bridge::ParallelMax (T t)
template<typename T >
static T ug::bridge::ParallelMin (T t)
template<typename T >
static T ug::bridge::ParallelSum (T t)
template<typename T >
static vector< T > ug::bridge::ParallelVecMax (const vector< T > &t)
template<typename T >
static vector< T > ug::bridge::ParallelVecMin (const vector< T > &t)
template<typename T >
static vector< T > ug::bridge::ParallelVecSum (const vector< T > &t)
static bool ug::bridge::PclAllProcsTrue (bool bTrue)
static void ug::bridge::PclDebugBarrierAll ()
static bool ug::bridge::PclDebugBarrierEnabled ()
void ug::bridge::RegisterBridge_PCL (Registry &reg, string parentGroup)
Detailed Description
Function Documentation
ParallelMax()
template<typename T > static T ug::bridge::ParallelMax (T t) static
References pcl::ProcessCommunicator::allreduce(), and PCL_RO_MAX.
ParallelMin()
template<typename T > static T ug::bridge::ParallelMin (T t) static
References pcl::ProcessCommunicator::allreduce(), and PCL_RO_MIN.
ParallelSum()
template<typename T > static T ug::bridge::ParallelSum (T t) static
References pcl::ProcessCommunicator::allreduce(), and PCL_RO_SUM.
ParallelVecMax()
template<typename T > static vector<T> ug::bridge::ParallelVecMax (const vector< T > & t) static
References pcl::ProcessCommunicator::allreduce(), and PCL_RO_MAX.
ParallelVecMin()
template<typename T > static vector<T> ug::bridge::ParallelVecMin (const vector< T > & t) static
References pcl::ProcessCommunicator::allreduce(), and PCL_RO_MIN.
ParallelVecSum()
template<typename T > static vector<T> ug::bridge::ParallelVecSum (const vector< T > & t) static
References pcl::ProcessCommunicator::allreduce(), and PCL_RO_SUM.
PclAllProcsTrue()
static bool ug::bridge::PclAllProcsTrue (bool bTrue) static
References pcl::AllProcsTrue().
Referenced by ug::bridge::RegisterBridge_PCL().
PclDebugBarrierAll()
static void ug::bridge::PclDebugBarrierAll () static
References PCL_DEBUG_BARRIER_ALL.
Referenced by ug::bridge::RegisterBridge_PCL().
PclDebugBarrierEnabled()
static bool ug::bridge::PclDebugBarrierEnabled () static
Referenced by ug::bridge::RegisterBridge_PCL().
RegisterBridge_PCL()
void ug::bridge::RegisterBridge_PCL (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_function(), pcl::DisableMPIInit(), pcl::NumProcs(), ug::bridge::PclAllProcsTrue(), ug::bridge::PclDebugBarrierAll(), ug::bridge::PclDebugBarrierEnabled(), pcl::ProcRank(), and pcl::SynchronizeProcesses().
Referenced by ug::bridge::RegisterStandardBridges().