ug4: Misc Bridge
Misc Bridge
ugbase » Bridge
Modules
PCL Bridge
Profiler Bridge
Test Bridge
Utility Bridge
VecMath Bridge
Functions
static void ug::bridge::errlog (const char *msg)
string ug::bridge::FilenameStringEscape (string s)
string ug::bridge::GetBuildHostname ()
double ug::bridge::GetClockS ()
string ug::bridge::GetCompileDate ()
string ug::bridge::GetGITRevision ()
uint32 ug::bridge::GetLogAssistantTag (const char *s)
string ug::bridge::GetOperatingSystem ()
string ug::bridge::GetSVNRevision ()
bool ug::bridge::IsDefinedBLAS_AVAILABLE ()
bool ug::bridge::IsDefinedLAPACK_AVAILABLE ()
bool ug::bridge::IsDefinedPCL_DEBUG_BARRIER_ENABLED ()
bool ug::bridge::IsDefinedPROFILE_PCL ()
bool ug::bridge::IsDefinedUG_ALGEBRA ()
bool ug::bridge::IsDefinedUG_BRIDGE ()
bool ug::bridge::IsDefinedUG_CPU_1 ()
bool ug::bridge::IsDefinedUG_CPU_2 ()
bool ug::bridge::IsDefinedUG_CPU_3 ()
bool ug::bridge::IsDefinedUG_CPU_4 ()
bool ug::bridge::IsDefinedUG_CPU_5 ()
bool ug::bridge::IsDefinedUG_CPU_6 ()
bool ug::bridge::IsDefinedUG_CPU_VAR ()
bool ug::bridge::IsDefinedUG_DEBUG ()
bool ug::bridge::IsDefinedUG_DIM_1 ()
bool ug::bridge::IsDefinedUG_DIM_2 ()
bool ug::bridge::IsDefinedUG_DIM_3 ()
bool ug::bridge::IsDefinedUG_ENABLE_DEBUG_LOGS ()
bool ug::bridge::IsDefinedUG_FOR_VRL ()
bool ug::bridge::IsDefinedUG_HLIBPRO ()
bool ug::bridge::IsDefinedUG_HYPRE ()
bool ug::bridge::IsDefinedUG_JSON ()
bool ug::bridge::IsDefinedUG_PARALLEL ()
bool ug::bridge::IsDefinedUG_PLUGINS ()
bool ug::bridge::IsDefinedUG_PROFILER ()
bool ug::bridge::IsDefinedUG_STATIC ()
bool ug::bridge::IsDefinedUG_TETGEN ()
void ug::bridge::PrintBuildConfiguration ()
prints CMake build parameters in a quite compact (pairwise) form
void ug::bridge::PrintBuildConfigurationExtended ()
void ug::bridge::RegisterBridge_Misc (Registry &reg, string parentGroup)
void ug::bridge::SetDebugLevel (const char *strTag, int level)
void ug::bridge::RegisterBridge_OrthoPoly (Registry &reg, string parentGroup)
Detailed Description
Function Documentation
errlog()
static void ug::bridge::errlog (const char * msg) static
References UG_ERR_LOG.
Referenced by ug::bridge::RegisterBridge_Misc().
FilenameStringEscape()
string ug::bridge::FilenameStringEscape (string s)
References s.
Referenced by ug::bridge::RegisterBridge_Misc().
GetBuildHostname()
string ug::bridge::GetBuildHostname ()
References ug::UGBuildHost().
Referenced by ug::bridge::RegisterBridge_Misc().
GetClockS()
double ug::bridge::GetClockS ()
clock() and os.clock only returns CPU time. get_clock_s returns seconds since 1970.
References ug::get_clock_s().
Referenced by ug::bridge::RegisterBridge_Misc().
GetCompileDate()
string ug::bridge::GetCompileDate ()
References ug::UGCompileDate().
Referenced by ug::bridge::RegisterBridge_Misc().
GetGITRevision()
string ug::bridge::GetGITRevision ()
References ug::UGGitRevision().
Referenced by ug::bridge::RegisterBridge_Misc().
GetLogAssistantTag()
uint32 ug::bridge::GetLogAssistantTag (const char * s)
References ug::crc32(), ug::GetDebugIDManager(), s, and UG_LOG.
GetOperatingSystem()
string ug::bridge::GetOperatingSystem ()
Referenced by ug::bridge::RegisterBridge_Misc().
GetSVNRevision()
string ug::bridge::GetSVNRevision ()
References ug::UGSvnRevision().
Referenced by ug::bridge::RegisterBridge_Misc().
IsDefinedBLAS_AVAILABLE()
bool ug::bridge::IsDefinedBLAS_AVAILABLE ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedLAPACK_AVAILABLE()
bool ug::bridge::IsDefinedLAPACK_AVAILABLE ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedPCL_DEBUG_BARRIER_ENABLED()
bool ug::bridge::IsDefinedPCL_DEBUG_BARRIER_ENABLED ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedPROFILE_PCL()
bool ug::bridge::IsDefinedPROFILE_PCL ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_ALGEBRA()
bool ug::bridge::IsDefinedUG_ALGEBRA ()
Referenced by ug::bridge::PrintBuildConfigurationExtended().
IsDefinedUG_BRIDGE()
bool ug::bridge::IsDefinedUG_BRIDGE ()
Referenced by ug::bridge::PrintBuildConfigurationExtended().
IsDefinedUG_CPU_1()
bool ug::bridge::IsDefinedUG_CPU_1 ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_CPU_2()
bool ug::bridge::IsDefinedUG_CPU_2 ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_CPU_3()
bool ug::bridge::IsDefinedUG_CPU_3 ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_CPU_4()
bool ug::bridge::IsDefinedUG_CPU_4 ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_CPU_5()
bool ug::bridge::IsDefinedUG_CPU_5 ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_CPU_6()
bool ug::bridge::IsDefinedUG_CPU_6 ()
IsDefinedUG_CPU_VAR()
bool ug::bridge::IsDefinedUG_CPU_VAR ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_DEBUG()
bool ug::bridge::IsDefinedUG_DEBUG ()
Referenced by ug::bridge::PrintBuildConfiguration(), and ug::bridge::RegisterBridge_Misc().
IsDefinedUG_DIM_1()
bool ug::bridge::IsDefinedUG_DIM_1 ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_DIM_2()
bool ug::bridge::IsDefinedUG_DIM_2 ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_DIM_3()
bool ug::bridge::IsDefinedUG_DIM_3 ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_ENABLE_DEBUG_LOGS()
bool ug::bridge::IsDefinedUG_ENABLE_DEBUG_LOGS ()
Referenced by ug::bridge::PrintBuildConfiguration(), and ug::bridge::RegisterBridge_Misc().
IsDefinedUG_FOR_VRL()
bool ug::bridge::IsDefinedUG_FOR_VRL ()
Referenced by ug::bridge::PrintBuildConfigurationExtended().
IsDefinedUG_HLIBPRO()
bool ug::bridge::IsDefinedUG_HLIBPRO ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_HYPRE()
bool ug::bridge::IsDefinedUG_HYPRE ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_JSON()
bool ug::bridge::IsDefinedUG_JSON ()
IsDefinedUG_PARALLEL()
bool ug::bridge::IsDefinedUG_PARALLEL ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_PLUGINS()
bool ug::bridge::IsDefinedUG_PLUGINS ()
Referenced by ug::bridge::PrintBuildConfigurationExtended().
IsDefinedUG_PROFILER()
bool ug::bridge::IsDefinedUG_PROFILER ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_STATIC()
bool ug::bridge::IsDefinedUG_STATIC ()
Referenced by ug::bridge::PrintBuildConfiguration().
IsDefinedUG_TETGEN()
bool ug::bridge::IsDefinedUG_TETGEN ()
Referenced by ug::bridge::PrintBuildConfiguration().
PrintBuildConfiguration()
void ug::bridge::PrintBuildConfiguration ()
prints CMake build parameters in a quite compact (pairwise) form
References append(), ug::AppendSpacesToString(), ug::bridge::IsDefinedBLAS_AVAILABLE(), ug::bridge::IsDefinedLAPACK_AVAILABLE(), ug::bridge::IsDefinedPCL_DEBUG_BARRIER_ENABLED(), ug::bridge::IsDefinedPROFILE_PCL(), ug::bridge::IsDefinedUG_CPU_1(), ug::bridge::IsDefinedUG_CPU_2(), ug::bridge::IsDefinedUG_CPU_3(), ug::bridge::IsDefinedUG_CPU_4(), ug::bridge::IsDefinedUG_CPU_5(), ug::bridge::IsDefinedUG_CPU_VAR(), ug::bridge::IsDefinedUG_DEBUG(), ug::bridge::IsDefinedUG_DIM_1(), ug::bridge::IsDefinedUG_DIM_2(), ug::bridge::IsDefinedUG_DIM_3(), ug::bridge::IsDefinedUG_ENABLE_DEBUG_LOGS(), ug::bridge::IsDefinedUG_HLIBPRO(), ug::bridge::IsDefinedUG_HYPRE(), ug::bridge::IsDefinedUG_PARALLEL(), ug::bridge::IsDefinedUG_PROFILER(), ug::bridge::IsDefinedUG_STATIC(), ug::bridge::IsDefinedUG_TETGEN(), and UG_LOG.
Referenced by ug::bridge::RegisterBridge_Misc().
PrintBuildConfigurationExtended()
void ug::bridge::PrintBuildConfigurationExtended ()
References ug::bridge::IsDefinedUG_ALGEBRA(), ug::bridge::IsDefinedUG_BRIDGE(), ug::bridge::IsDefinedUG_FOR_VRL(), ug::bridge::IsDefinedUG_PLUGINS(), and UG_LOG.
Referenced by ug::bridge::RegisterBridge_Misc().
RegisterBridge_Misc()
void ug::bridge::RegisterBridge_Misc (Registry & reg, string parentGroup)
References ug::AbortRun(), ug::bridge::Registry::add_class_(), ADD_DEFINED_FUNC, ug::bridge::Registry::add_function(), ug::ClearAbortRunFlag(), ug::bridge::errlog(), ug::bridge::FilenameStringEscape(), ug::bridge::GetBuildHostname(), ug::bridge::GetClockS(), ug::bridge::GetCompileDate(), ug::bridge::GetGITRevision(), ug::GetLogAssistant(), ug::bridge::GetOperatingSystem(), ug::bridge::GetSVNRevision(), ug::bridge::IsDefinedUG_DEBUG(), ug::bridge::IsDefinedUG_ENABLE_DEBUG_LOGS(), ug::LevenshteinDistance(), ug::bridge::PrintBuildConfiguration(), ug::bridge::PrintBuildConfigurationExtended(), ug::PrintLUA(), ug::ReplaceAll(), ug::TerminateAbortedRun(), ug_backtrace(), ug::WildcardMatch(), and ug::XMLStringEscape().
Referenced by ug::bridge::RegisterStandardBridges().
RegisterBridge_OrthoPoly()
void ug::bridge::RegisterBridge_OrthoPoly (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_function(), ug::Chebyshev1Poly(), ug::Chebyshev2Poly(), ug::LegendrePoly(), ug::NormalizedChebyshev1Poly(), ug::NormalizedChebyshev2Poly(), ug::NormalizedLegendrePoly(), ug::SqNormOfChebyshev1Poly(), ug::SqNormOfChebyshev2Poly(), and ug::SqNormOfLegendrePoly().
Referenced by ug::bridge::RegisterStandardBridges().
SetDebugLevel()
void ug::bridge::SetDebugLevel (const char * strTag, int level)
References ug::GetLogAssistant(), and ug::LogAssistant::set_debug_level().