ug4: User Data
User Data
lib_discretization
User Data.
Classes
class ug::ConstUserMatrix< N, M, worldDim >
constant matrix user data
class ug::ConstUserNumber< dim >
constant scalar user data
class ug::ConstUserTensor< TRank, dim >
constant tensor user data
class ug::ConstUserVector< dim, worldDim >
constant vector user data
Functions
template<int dim>
SmartPtr< CplUserData< MathMatrix< dim, dim >, dim > > ug::CreateConstUserData (number val, MathMatrix< dim, dim >)
template<int dim>
SmartPtr< CplUserData< MathTensor< 4, dim >, dim > > ug::CreateConstUserData (number val, MathTensor< 4, dim >)
template<int dim, int worldDim = dim>
SmartPtr< CplUserData< MathVector< dim >, worldDim > > ug::CreateConstUserData (number val, MathVector< dim >)
template<int dim>
SmartPtr< CplUserData< number, dim > > ug::CreateConstUserData (number val, number)
template<typename TData , int dim>
SmartPtr< CplUserData< TData, dim > > ug::CreateConstUserData (number val, TData dummy)
creates user data of desired type
Detailed Description
User Data.
User Data that can be used in assembling routines.
Function Documentation
CreateConstUserData() [1/5]
template<int dim> SmartPtr<CplUserData<MathMatrix<dim,dim>,dim> > ug::CreateConstUserData (number val, MathMatrix< dim, dim >)
References make_sp().
CreateConstUserData() [2/5]
template<int dim> SmartPtr<CplUserData<MathTensor<4,dim>,dim> > ug::CreateConstUserData (number val, MathTensor< 4, dim >)
References make_sp().
CreateConstUserData() [3/5]
template<int dim, int worldDim = dim> SmartPtr<CplUserData<MathVector<dim>,worldDim> > ug::CreateConstUserData (number val, MathVector< dim >)
References make_sp().
CreateConstUserData() [4/5]
template<int dim> SmartPtr<CplUserData<number,dim> > ug::CreateConstUserData (number val, number) inline
References make_sp().
CreateConstUserData() [5/5]
template<typename TData , int dim> SmartPtr<CplUserData<TData,dim> > ug::CreateConstUserData (number val, TData dummy)
creates user data of desired type