ug4: Test Bridge
Test Bridge
ugbase » Bridge » Misc Bridge
Classes
class ug::bridge::AllowName
class ug::bridge::Base
class ug::bridge::Base0
class ug::bridge::Base1
class ug::bridge::Base2
class ug::bridge::Base3
class ug::bridge::Cake
class ug::bridge::ConstClass
class ug::bridge::Derived
class ug::bridge::FurtherDerived
class ug::bridge::Intermediate0
class ug::bridge::Intermediate1
class ug::bridge::Message
class ug::bridge::MessageHubTest
class ug::bridge::MultipleDerived
class ug::bridge::NonAllowedName1
class ug::bridge::NonAllowedName2
class ug::bridge::NonAllowedName3
class ug::bridge::NonAllowedName4
class ug::bridge::Piece
class ug::bridge::SmartTest
SmartTest is a test-class which shall only be used encapsulated in a smart-pointer.
class ug::bridge::SmartTestDerived
class ug::bridge::Test
class ug::bridge::TestMessage
class ug::bridge::Unregistered
Typedefs
typedef SmartPtr< SmartTest > ug::bridge::SPSmartTest
typedef SmartPtr< SmartTestDerived > ug::bridge::SPSmartTestDerived
Functions
string ug::bridge::Add (const char *a, const char *b)
int ug::bridge::Add (int a, int b)
int ug::bridge::Add (int a, int b, int c)
int ug::bridge::ConstSmartTestFunc (ConstSmartPtr< Test > test)
ConstSmartPtr< Test > ug::bridge::ConstSmartTestImpl ()
template<typename T >
void ug::bridge::ConstStdVectorRefOfClass (const std::vector< T > &vec)
int ug::bridge::ConstTestFunc (const Test &t)
calls const print on const object of class Test
const FurtherDerived * ug::bridge::CreateConstFurtherDerived ()
void ug::bridge::NonAllowedFct1 ()
void ug::bridge::NonAllowedFct2 ()
void ug::bridge::NonAllowedFct3 ()
void ug::bridge::NotAllowedParamPerValue (Piece P)
void ug::bridge::PostRegisteredFunction ()
void ug::bridge::PostRegisterTest ()
template<typename T >
void ug::bridge::PrintConstStdVectorRef (const std::vector< T > &vec)
void ug::bridge::PrintFunction (Base &b)
void ug::bridge::PrintFunction (Base3 &b)
void ug::bridge::PrintFunction (SmartPtr< Base2 > b)
void ug::bridge::PrintFunction (SmartPtr< Base3 > b)
void ug::bridge::PrintFunctionIntermediate (Intermediate0 &b)
void ug::bridge::PrintFunctionIntermediate (SmartPtr< Intermediate1 > b)
void ug::bridge::PrintHelloWorldToScreen ()
template<typename T >
void ug::bridge::PrintStdVector (std::vector< T > vec)
template<typename T >
void ug::bridge::PrintStdVectorOfClass (std::vector< T > vec)
void ug::bridge::PrintStringTest (const std::string &str)
void ug::bridge::RegisterBridge_Test (Registry &reg, string parentGroup)
template<typename T >
const std::vector< T > & ug::bridge::ReturnConstStdVectorRef_Number ()
const std::vector< std::string > & ug::bridge::ReturnConstStdVectorRef_String ()
template<typename T >
const std::vector< T > & ug::bridge::ReturnConstStdVectorRefOfClass ()
template<typename T >
const std::vector< T > & ug::bridge::ReturnConstStdVectorRefOfClassSP ()
template<typename T >
std::vector< T > ug::bridge::ReturnStdVector_Number ()
std::vector< std::string > ug::bridge::ReturnStdVector_String ()
template<typename T >
std::vector< T > ug::bridge::ReturnStdVectorOfClass ()
SmartPtr< MultipleDerived > ug::bridge::SmartMultipleDerivedImpl ()
void ug::bridge::SmartTestArrived (SPSmartTest test)
int ug::bridge::SmartTestFunc (SmartPtr< Test > test)
SmartPtr< Test > ug::bridge::SmartTestImpl ()
string ug::bridge::StdStringTest ()
const char * ug::bridge::StringTest ()
int ug::bridge::TestFunc (Test &t)
calls non-const print on non-const object of class Test
void ug::bridge::TestMsgCallback (const TestMessage &msg)
void ug::bridge::TestPageContainer ()
const Test & ug::bridge::ToConst (Test &test)
returns a const reference to a non-const object of class Test
Unregistered * ug::bridge::UnregisteredParameterTest (Unregistered &unregistered)
Variables
const char * ug::bridge::REFINEMENT_MESSAGE_NAME = "MSG_GRID_ADAPTION"
Detailed Description
Typedef Documentation
SPSmartTest
typedef SmartPtr<SmartTest> ug::bridge::SPSmartTest
SPSmartTestDerived
typedef SmartPtr<SmartTestDerived> ug::bridge::SPSmartTestDerived
Function Documentation
Add() [1/3]
string ug::bridge::Add (const char * a, const char * b)
Referenced by ug::bridge::RegisterBridge_Test().
Add() [2/3]
int ug::bridge::Add (int a, int b)
Add() [3/3]
int ug::bridge::Add (int a, int b, int c)
ConstSmartTestFunc()
int ug::bridge::ConstSmartTestFunc (ConstSmartPtr< Test > test)
References UG_LOG.
Referenced by ug::bridge::RegisterBridge_Test().
ConstSmartTestImpl()
ConstSmartPtr<Test> ug::bridge::ConstSmartTestImpl ()
Referenced by ug::bridge::RegisterBridge_Test().
ConstStdVectorRefOfClass()
template<typename T > void ug::bridge::ConstStdVectorRefOfClass (const std::vector< T > & vec)
References print(), and UG_LOG.
Referenced by ug::bridge::RegisterBridge_Test().
ConstTestFunc()
int ug::bridge::ConstTestFunc (const Test & t)
calls const print on const object of class Test
References ug::bridge::Test::print().
Referenced by ug::bridge::RegisterBridge_Test().
CreateConstFurtherDerived()
const FurtherDerived* ug::bridge::CreateConstFurtherDerived ()
Referenced by ug::bridge::RegisterBridge_Test().
NonAllowedFct1()
void ug::bridge::NonAllowedFct1 ()
NonAllowedFct2()
void ug::bridge::NonAllowedFct2 ()
NonAllowedFct3()
void ug::bridge::NonAllowedFct3 ()
NotAllowedParamPerValue()
void ug::bridge::NotAllowedParamPerValue (Piece P)
PostRegisteredFunction()
void ug::bridge::PostRegisteredFunction ()
References UG_LOG.
Referenced by ug::bridge::PostRegisterTest().
PostRegisterTest()
void ug::bridge::PostRegisterTest ()
References ug::bridge::Registry::add_function(), ug::bridge::GetUGRegistry(), ug::bridge::PostRegisteredFunction(), and ug::bridge::Registry::registry_changed().
PrintConstStdVectorRef()
template<typename T > void ug::bridge::PrintConstStdVectorRef (const std::vector< T > & vec)
References UG_LOG.
PrintFunction() [1/4]
void ug::bridge::PrintFunction (Base & b)
References ug::bridge::Base::print().
Referenced by ug::bridge::RegisterBridge_Test().
PrintFunction() [2/4]
void ug::bridge::PrintFunction (Base3 & b)
References ug::bridge::Base3::print_base3(), and ug::bridge::Base3::virt_print_base3().
PrintFunction() [3/4]
void ug::bridge::PrintFunction (SmartPtr< Base2 > b)
PrintFunction() [4/4]
void ug::bridge::PrintFunction (SmartPtr< Base3 > b)
PrintFunctionIntermediate() [1/2]
void ug::bridge::PrintFunctionIntermediate (Intermediate0 & b)
References ug::bridge::Intermediate0::print_intermediate0(), and ug::bridge::Intermediate0::virt_print_intermediate0().
Referenced by ug::bridge::RegisterBridge_Test().
PrintFunctionIntermediate() [2/2]
void ug::bridge::PrintFunctionIntermediate (SmartPtr< Intermediate1 > b)
PrintHelloWorldToScreen()
void ug::bridge::PrintHelloWorldToScreen ()
References UG_LOG.
Referenced by ug::bridge::RegisterBridge_Test().
PrintStdVector()
template<typename T > void ug::bridge::PrintStdVector (std::vector< T > vec)
References UG_LOG.
PrintStdVectorOfClass()
template<typename T > void ug::bridge::PrintStdVectorOfClass (std::vector< T > vec)
References print(), and UG_LOG.
Referenced by ug::bridge::RegisterBridge_Test().
PrintStringTest()
void ug::bridge::PrintStringTest (const std::string & str)
References UG_LOG.
Referenced by ug::bridge::RegisterBridge_Test().
RegisterBridge_Test()
void ug::bridge::RegisterBridge_Test (Registry & reg, string parentGroup)
References ug::bridge::Add(), ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_function(), ug::bridge::ConstSmartTestFunc(), ug::bridge::ConstSmartTestImpl(), ug::bridge::ConstStdVectorRefOfClass(), ug::bridge::ConstTestFunc(), ug::bridge::CreateConstFurtherDerived(), print(), ug::bridge::PrintFunction(), ug::bridge::PrintFunctionIntermediate(), ug::bridge::PrintHelloWorldToScreen(), ug::bridge::PrintStdVectorOfClass(), ug::bridge::PrintStringTest(), ug::bridge::ReturnConstStdVectorRef_String(), ug::bridge::ReturnConstStdVectorRefOfClassSP(), ug::bridge::ReturnStdVector_String(), ug::bridge::ReturnStdVectorOfClass(), ug::bridge::SmartMultipleDerivedImpl(), ug::bridge::SmartTestArrived(), ug::bridge::SmartTestFunc(), ug::bridge::SmartTestImpl(), ug::bridge::StdStringTest(), ug::bridge::StringTest(), ug::bridge::TestFunc(), ug::bridge::TestPageContainer(), ug::bridge::ToConst(), and UG_REGISTRY_CATCH_THROW.
ReturnConstStdVectorRef_Number()
template<typename T > const std::vector<T>& ug::bridge::ReturnConstStdVectorRef_Number ()
ReturnConstStdVectorRef_String()
const std::vector<std::string>& ug::bridge::ReturnConstStdVectorRef_String ()
Referenced by ug::bridge::RegisterBridge_Test().
ReturnConstStdVectorRefOfClass()
template<typename T > const std::vector<T>& ug::bridge::ReturnConstStdVectorRefOfClass ()
ReturnConstStdVectorRefOfClassSP()
template<typename T > const std::vector<T>& ug::bridge::ReturnConstStdVectorRefOfClassSP ()
References make_sp().
Referenced by ug::bridge::RegisterBridge_Test().
ReturnStdVector_Number()
template<typename T > std::vector<T> ug::bridge::ReturnStdVector_Number ()
ReturnStdVector_String()
std::vector<std::string> ug::bridge::ReturnStdVector_String ()
Referenced by ug::bridge::RegisterBridge_Test().
ReturnStdVectorOfClass()
template<typename T > std::vector<T> ug::bridge::ReturnStdVectorOfClass ()
Referenced by ug::bridge::RegisterBridge_Test().
SmartMultipleDerivedImpl()
SmartPtr<MultipleDerived> ug::bridge::SmartMultipleDerivedImpl ()
Referenced by ug::bridge::RegisterBridge_Test().
SmartTestArrived()
void ug::bridge::SmartTestArrived (SPSmartTest test)
References UG_LOG.
Referenced by ug::bridge::RegisterBridge_Test().
SmartTestFunc()
int ug::bridge::SmartTestFunc (SmartPtr< Test > test)
References UG_LOG.
Referenced by ug::bridge::RegisterBridge_Test().
SmartTestImpl()
SmartPtr<Test> ug::bridge::SmartTestImpl ()
Referenced by ug::bridge::RegisterBridge_Test().
StdStringTest()
string ug::bridge::StdStringTest ()
Referenced by ug::bridge::RegisterBridge_Test().
StringTest()
const char* ug::bridge::StringTest ()
Referenced by ug::bridge::RegisterBridge_Test().
TestFunc()
int ug::bridge::TestFunc (Test & t)
calls non-const print on non-const object of class Test
References ug::bridge::Test::print().
Referenced by ug::bridge::RegisterBridge_Test().
TestMsgCallback()
void ug::bridge::TestMsgCallback (const TestMessage & msg)
References ug::bridge::TestMessage::m_strMsg, and UG_LOG.
Referenced by ug::bridge::MessageHubTest::MessageHubTest().
TestPageContainer()
void ug::bridge::TestPageContainer ()
References UG_LOG.
Referenced by ug::bridge::RegisterBridge_Test().
ToConst()
const Test& ug::bridge::ToConst (Test & test)
returns a const reference to a non-const object of class Test
Referenced by ug::bridge::RegisterBridge_Test().
UnregisteredParameterTest()
Unregistered* ug::bridge::UnregisteredParameterTest (Unregistered & unregistered)
Variable Documentation
REFINEMENT_MESSAGE_NAME
const char* ug::bridge::REFINEMENT_MESSAGE_NAME = "MSG_GRID_ADAPTION"