ug4: Vectors
Vectors
ugbase » Math
Classes
class ug::MathVector< N, T >
a mathematical Vector with N entries.
class ug::MathVector< 0, T >
class ug::MathVector< 1, T >
class ug::MathVector< 2, T >
class ug::MathVector< 3, T >
class ug::MathVector< 4, T >
Typedefs
typedef MathMatrix< 2, 2, number > ug::matrix22
a 2x2 matrix
typedef MathMatrix< 3, 3, number > ug::matrix33
a 3x3 matrix
typedef MathMatrix< 4, 4, number > ug::matrix44
a 4x4 matrix
typedef MathVector< 1, number > ug::vector1
a 1d vector
typedef MathVector< 2, number > ug::vector2
a 2d vector
typedef MathVector< 3, number > ug::vector3
a 3d vector
typedef MathVector< 4, number > ug::vector4
a 4d vector
Functions
template<typename vector_t >
void ug::CalculateTriangleNormal (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3)
Calculates a triangle-normal in 3d (output has length 1).
template<typename vector_t >
void ug::CalculateTriangleNormalNoNormalize (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3)
Calculates a triangle-normal in 3d (no normalization is performed).
template<class TStream , std::size_t N, class T >
void ug::Deserialize (TStream &out, MathVector< N, T > &valOut)
template<size_t dim>
void ug::GenVecCross (MathVector< dim > &result, const MathVector< dim > &v_1, const MathVector< dim > &v_2)
calculates the usual cross product in 3d, and the (det, 0) vector as a cross product in 2d
template<std::size_t N, typename T >
bool ug::operator!= (const MathVector< N, T > &v, const MathVector< N, T > &w)
template<std::size_t N, typename T >
bool ug::operator< (const MathVector< N, T > &v, const MathVector< N, T > &w)
std::ostream & ug::operator<< (std::ostream &outStream, const ug::MathVector< 1 > &v)
formatted output of MathVector objects: (...,...)
std::ostream & ug::operator<< (std::ostream &outStream, const ug::MathVector< 2 > &v)
formatted output of MathVector objects: (...,...)
std::ostream & ug::operator<< (std::ostream &outStream, const ug::MathVector< 3 > &v)
formatted output of MathVector objects: (...,...)
std::ostream & ug::operator<< (std::ostream &outStream, const ug::MathVector< 4 > &v)
formatted output of MathVector objects: (...,...)
template<std::size_t N, typename T >
std::ostream & ug::operator<< (std::ostream &outStream, const ug::MathVector< N, T > &v)
template<typename T >
std::ostream & ug::operator<< (std::ostream &outStream, const ug::MathVector< 0, T > &v)
template<typename T >
std::ostream & ug::operator<< (std::ostream &outStream, const ug::MathVector< 1, T > &v)
template<typename T >
std::ostream & ug::operator<< (std::ostream &outStream, const ug::MathVector< 2, T > &v)
template<typename T >
std::ostream & ug::operator<< (std::ostream &outStream, const ug::MathVector< 3, T > &v)
template<typename T >
std::ostream & ug::operator<< (std::ostream &outStream, const ug::MathVector< 4, T > &v)
template<std::size_t N, typename T >
bool ug::operator== (const MathVector< N, T > &v, const MathVector< N, T > &w)
template<typename T >
bool ug::operator== (const MathVector< 0, T > &v, const MathVector< 0, T > &w)
std::istream & ug::read_plain_txt (std::istream &inStream, ug::MathVector< 1 > &v)
plain text input of MathVectors: read space-separated coordinates
std::istream & ug::read_plain_txt (std::istream &inStream, ug::MathVector< 2 > &v)
plain text input of MathVectors: read space-separated coordinates
std::istream & ug::read_plain_txt (std::istream &inStream, ug::MathVector< 3 > &v)
plain text input of MathVectors: read space-separated coordinates
std::istream & ug::read_plain_txt (std::istream &inStream, ug::MathVector< 4 > &v)
plain text input of MathVectors: read space-separated coordinates
template<class TStream , std::size_t N, class T >
void ug::Serialize (TStream &out, const MathVector< N, T > &val)
template<typename vector_t >
void ug::VecAdd (vector_t &vOut, const vector_t &v1, const vector_t &v2)
adds two MathVector<N>s and stores the result in a third one
template<typename vector_t >
void ug::VecAdd (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3)
adds three MathVector<N>s and stores the result in a fourth one
template<typename vector_t >
void ug::VecAdd (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3, const vector_t &v4)
adds four MathVector<N>s and stores the result in a firth one
template<typename vector_t >
void ug::VecAdd (vector_t &vOut, const vector_t &v, typename vector_t::value_type s)
Add a scalar to a vector (componentwise)
template<typename vector_t >
vector_t::value_type ug::VecAngle (const vector_t &v1, const vector_t &v2)
returns the angle between two vectors in radiants
template<typename vector_t >
vector_t::value_type ug::VecAngleNorm (const vector_t &v1, const vector_t &v2)
returns the angle between two vectors of length 1 in radiants
template<typename vector_t >
void ug::VecAppend (vector_t &vOut, const vector_t &v1)
adds a MathVector<N> to a second one
template<typename vector_t >
void ug::VecAppend (vector_t &vOut, const vector_t &v1, const vector_t &v2)
adds two MathVector<N>s and adds the result to a third one
template<typename vector_t >
void ug::VecAppend (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3)
adds two MathVector<N>s and adds the result to a fourth one
template<typename vector_t >
void ug::VecAppend (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3, const vector_t &v4)
adds two MathVector<N>s and adds the result to a fifth one
template<typename vector_target_t , typename vector_source_t >
void ug::VecCopy (vector_target_t &target, const vector_source_t &source, typename vector_target_t::value_type fill)
Copy contents between vectors of possibly different types.
template<typename vector_t >
void ug::VecCross (vector_t &vOut, const vector_t &v1, const vector_t &v2)
calculates the cross product of two Vectors of dimension 3. It makes no sense to use VecCross for vector_ts that have not dimension 3.
template<typename vector_t >
vector_t::value_type ug::VecDistance (const vector_t &v1, const vector_t &v2)
returns the distance of two vector_ts.
template<typename vector_t >
vector_t::value_type ug::VecDistanceSq (const vector_t &v1, const vector_t &v2)
returns the squared distance of two vector_ts.
template<typename vector_t >
vector_t::value_type ug::VecDot (const vector_t &v1, const vector_t &v2)
returns the dot-product of two vector_ts
template<typename vector_t >
vector_t::value_type ug::VecInftyNorm (const vector_t &v)
template<typename vector_t >
void ug::VecInterpolateLinear (vector_t &vOut, const vector_t &v1, const vector_t &v2, typename vector_t::value_type interpAmount)
template<typename vector_t >
vector_t::value_type ug::VecLength (const vector_t &v)
returns the length of v. Slower than VecLengthSq.
template<typename vector_t >
vector_t::value_type ug::VecLengthSq (const vector_t &v)
returns the squared length of v. Faster than VecLength.
template<typename vector_t >
vector_t::value_type ug::VecMaxNorm (const vector_t &v)
template<typename vector_t >
void ug::VecNormalize (vector_t &vOut, const vector_t &v)
scales a vector_t to unit length
template<typename vector_t >
vector_t::value_type ug::VecOneNorm (const vector_t &v)
template<typename vector_t >
vector_t::value_type ug::VecPNorm (const vector_t &v, unsigned int p)
template<typename vector_t >
void ug::VecScale (vector_t &vOut, const vector_t &v, typename vector_t::value_type s)
scales a MathVector<N>
template<typename vector_t >
void ug::VecScaleAdd (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2)
Scales two Vectors, adds them and returns the sum in a third vector.
template<typename vector_t >
void ug::VecScaleAdd (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2, typename vector_t::value_type s3, const vector_t &v3)
Scales three Vectors, adds them and returns the sum in a fourth vector.
template<typename vector_t >
void ug::VecScaleAdd (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2, typename vector_t::value_type s3, const vector_t &v3, typename vector_t::value_type s4, const vector_t &v4)
Scales four Vectors, adds them and returns the sum in a fifth vector.
template<typename vector_t >
void ug::VecScaleAppend (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1)
Scales a Vector and adds it to a second vector.
template<typename vector_t >
void ug::VecScaleAppend (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2)
Scales two Vectors, adds them and adds the sum to a third vector.
template<typename vector_t >
void ug::VecScaleAppend (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2, typename vector_t::value_type s3, const vector_t &v3)
Scales three Vectors, adds them and adds the sum to a fourth vector.
template<typename vector_t >
void ug::VecScaleAppend (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2, typename vector_t::value_type s3, const vector_t &v3, typename vector_t::value_type s4, const vector_t &v4)
Scales four Vectors, adds them and adds the sum to a fifth vector.
template<typename vector_t >
void ug::VecSet (vector_t &vInOut, typename vector_t::value_type s)
Set each vector component to scalar (componentwise)
template<typename vector_t >
void ug::VecSubtract (vector_t &vOut, const vector_t &v1, const vector_t &v2)
subtracts v2 from v1 and stores the result in a vOut
template<typename vector_t >
void ug::VecSubtract (vector_t &vOut, const vector_t &v, typename vector_t::value_type s)
Subtract a scalar from a vector (componentwise)
template<typename vector_t >
vector_t::value_type ug::VecTwoNorm (const vector_t &v)
template<typename vector_t >
vector_t::value_type ug::VecTwoNormSq (const vector_t &v)
std::ostream & ug::write_plain_txt (std::ostream &outStream, const ug::MathVector< 1 > &v)
plain text output of MathVector objects: space-separated coordinates
std::ostream & ug::write_plain_txt (std::ostream &outStream, const ug::MathVector< 2 > &v)
plain text output of MathVector objects: space-separated coordinates
std::ostream & ug::write_plain_txt (std::ostream &outStream, const ug::MathVector< 3 > &v)
plain text output of MathVector objects: space-separated coordinates
std::ostream & ug::write_plain_txt (std::ostream &outStream, const ug::MathVector< 4 > &v)
plain text output of MathVector objects: space-separated coordinates
template<std::size_t fromN, std::size_t toN, typename T >
MathVector< toN, T > ug::MathVectorFrom (const MathVector< fromN, T > &v)
helper method which creates a vector from another vector of different dimensionality
template<std::size_t N, typename T >
MathVector< N, T > ug::MathVectorFrom (const MathVector< N, T > &v)
helper method which creates a vector from another vector of different dimensionality
Detailed Description
Abbreviations of small vectors
Typedef Documentation
matrix22
typedef MathMatrix<2,2, number> ug::matrix22
a 2x2 matrix
matrix33
typedef MathMatrix<3,3, number> ug::matrix33
a 3x3 matrix
matrix44
typedef MathMatrix<4,4, number> ug::matrix44
a 4x4 matrix
vector1
typedef MathVector<1, number> ug::vector1
a 1d vector
vector2
typedef MathVector<2, number> ug::vector2
a 2d vector
vector3
typedef MathVector<3, number> ug::vector3
a 3d vector
vector4
typedef MathVector<4, number> ug::vector4
a 4d vector
Function Documentation
CalculateTriangleNormal()
template<typename vector_t > void ug::CalculateTriangleNormal (vector_t & vOut, const vector_t & v1, const vector_t & v2, const vector_t & v3) inline
Calculates a triangle-normal in 3d (output has length 1).
Calculates a triangle-normal in 3d.
References ug::CalculateTriangleNormalNoNormalize(), and ug::VecNormalize().
Referenced by ug::CalculateNormal(), ug::CalculateNormalDot(), and ug::IntersectCoplanarTriangles().
CalculateTriangleNormalNoNormalize()
template<typename vector_t > void ug::CalculateTriangleNormalNoNormalize (vector_t & vOut, const vector_t & v1, const vector_t & v2, const vector_t & v3) inline
Calculates a triangle-normal in 3d (no normalization is performed).
Calculates a triangle-normal in 3d.
References ug::VecCross(), and ug::VecSubtract().
Referenced by ug::CalculateNormal(), ug::CalculateNormalNoNormalize(), ug::CalculateTriangleNormal(), ug::node_tree::Traverser_ProjectPoint::handle_collision_triangles(), ug::ProjectPointToSurface(), ug::QuadDiagonalIsValid(), ug::Valence3VertexIsObsolete(), and ug::Valence4VertexIsObsolete().
Deserialize()
template<class TStream , std::size_t N, class T > void ug::Deserialize (TStream & out, MathVector< N, T > & valOut)
References ug::MathVector< N, T >::m_data.
GenVecCross()
template<size_t dim> void ug::GenVecCross (MathVector< dim > & result, const MathVector< dim > & v_1, const MathVector< dim > & v_2) inline
calculates the usual cross product in 3d, and the (det, 0) vector as a cross product in 2d
computes the "generalized vector product" of two vectors
In 3d, this is a usual cross-product. In 2d, the first component of the result is the determinant of the 2x2-matrix build of the operands, and the second component is always 0.
Template Parameters
dim dimensionality of the vectors
Parameters
result = v_1 X v_2
References ug::GenVecCross< 2 >(), and UG_THROW.
Referenced by ug::TriangleArea(), and ug::VecCross().
MathVectorFrom() [1/2]
template<std::size_t fromN, std::size_t toN, typename T > MathVector<toN, T> ug::MathVectorFrom (const MathVector< fromN, T > & v)
helper method which creates a vector from another vector of different dimensionality
Typically, the method isn't invoked directly but serves as an implementation helper for MathVector<toN, T>::from(v).
MathVectorFrom() [2/2]
template<std::size_t N, typename T > MathVector<N, T> ug::MathVectorFrom (const MathVector< N, T > & v)
helper method which creates a vector from another vector of different dimensionality
Typically, the method isn't invoked directly but serves as an implementation helper for MathVector<toN, T>::from(v).
operator!=()
template<std::size_t N, typename T > bool ug::operator!= (const MathVector< N, T > & v, const MathVector< N, T > & w)
operator<()
template<std::size_t N, typename T > bool ug::operator< (const MathVector< N, T > & v, const MathVector< N, T > & w)
References ug::SMALL.
operator<<() [1/10]
UG_API std::ostream & ug::operator<< (std::ostream & outStream, const ug::MathVector< 1 > & v)
formatted output of MathVector objects: (...,...)
operator<<() [2/10]
UG_API std::ostream & ug::operator<< (std::ostream & outStream, const ug::MathVector< 2 > & v)
formatted output of MathVector objects: (...,...)
operator<<() [3/10]
UG_API std::ostream & ug::operator<< (std::ostream & outStream, const ug::MathVector< 3 > & v)
formatted output of MathVector objects: (...,...)
operator<<() [4/10]
UG_API std::ostream & ug::operator<< (std::ostream & outStream, const ug::MathVector< 4 > & v)
formatted output of MathVector objects: (...,...)
operator<<() [5/10]
template<std::size_t N, typename T > std::ostream& ug::operator<< (std::ostream & outStream, const ug::MathVector< N, T > & v)
operator<<() [6/10]
template<typename T > std::ostream& ug::operator<< (std::ostream & outStream, const ug::MathVector< 0, T > & v)
operator<<() [7/10]
template<typename T > std::ostream& ug::operator<< (std::ostream & outStream, const ug::MathVector< 1, T > & v)
operator<<() [8/10]
template<typename T > std::ostream& ug::operator<< (std::ostream & outStream, const ug::MathVector< 2, T > & v)
operator<<() [9/10]
template<typename T > std::ostream& ug::operator<< (std::ostream & outStream, const ug::MathVector< 3, T > & v)
operator<<() [10/10]
template<typename T > std::ostream& ug::operator<< (std::ostream & outStream, const ug::MathVector< 4, T > & v)
References ug::read_plain_txt(), UG_API, and ug::write_plain_txt().
operator==() [1/2]
template<std::size_t N, typename T > bool ug::operator== (const MathVector< N, T > & v, const MathVector< N, T > & w)
Referenced by SmartPtr< IBalanceWeights >::operator!=(), ug::DenseMatrix< VariableArray2< LocalCplMatrix * > >::operator!=(), and ConstSmartPtr< ug::LocalDoFSet >::operator!=().
operator==() [2/2]
template<typename T > bool ug::operator== (const MathVector< 0, T > & v, const MathVector< 0, T > & w)
read_plain_txt() [1/4]
UG_API std::istream & ug::read_plain_txt (std::istream & inStream, ug::MathVector< 1 > & v)
plain text input of MathVectors: read space-separated coordinates
References ug::MathVector< N, T >::coord().
Referenced by ug::IDWUserData< WDim, TData >::load_data_from(), and ug::operator<<().
read_plain_txt() [2/4]
UG_API std::istream & ug::read_plain_txt (std::istream & inStream, ug::MathVector< 2 > & v)
plain text input of MathVectors: read space-separated coordinates
References ug::MathVector< N, T >::coord().
read_plain_txt() [3/4]
UG_API std::istream & ug::read_plain_txt (std::istream & inStream, ug::MathVector< 3 > & v)
plain text input of MathVectors: read space-separated coordinates
References ug::MathVector< N, T >::coord().
read_plain_txt() [4/4]
UG_API std::istream & ug::read_plain_txt (std::istream & inStream, ug::MathVector< 4 > & v)
plain text input of MathVectors: read space-separated coordinates
References ug::MathVector< N, T >::coord().
Serialize()
template<class TStream , std::size_t N, class T > void ug::Serialize (TStream & out, const MathVector< N, T > & val)
References ug::MathVector< N, T >::m_data.
VecAdd() [1/4]
template<typename vector_t > void ug::VecAdd (vector_t & vOut, const vector_t & v1, const vector_t & v2) inline
adds two MathVector<N>s and stores the result in a third one
Referenced by ug::AABox< ug::MathVector< dim > >::AABox(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::calculate_center(), ug::ntree< tree_dim, world_dim, Triangle *, NTreeGridData< world_dim > >::calculate_center_of_mass(), ug::CalculateBarycenter(), ug::CalculateBoundaryVertexNormal3D(), ug::CalculateCenter(), ug::CalculateConstrainedSmoothVolumePosInTopLevel(), ug::CalculateCreaseNormal(), ug::CalculateMinCurvature(), ug::CalculateNormal(), ug::CalculateNormalNoNormalize(), ug::CalculateSmoothManifoldPosInParentLevelLoopScheme(), ug::CalculateSmoothManifoldPosInTopLevelAveragingScheme(), ug::CalculateSmoothVolumePosInTopLevel(), ug::CalculateVertexNormal(), ug::CalculateVertexNormals(), ug::AABox< ug::MathVector< dim > >::center(), ug::CollapseEdge(), ug::HFV1Geometry< TElem, TWorldDim >::compute_side_midpoints(), ug::DimHFV1Geometry< TDim, TWorldDim >::compute_side_midpoints(), ug::HFV1ManifoldGeometry< TElem, TWorldDim >::compute_side_midpoints(), ug::CreatePrism(), ug::node_tree::CreateSubOctrees(), ug::DropAPerpendicular(), ug::Duplicate(), ug::ExpandFractures2d(), ug::ExpandFractures3d(), ug::Extrude(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::grow_box(), ug::node_tree::GrowBox(), ug::LaplacianSmooth(), ug::fv1_traits_ReferenceFace3d::NormalOnSCVF_Face(), ug::ObtainSimpleGrid_CollapseEdge(), ug::ProjectPointToRay(), ug::QualityGridGeneration(), ug::RayPlaneIntersection(), ug::RayRayIntersection3d(), ug::tet_rules::Refine(), ug::SubdivisionProjector::refinement_begins(), ug::SnapMarkerPointToGridVertex(), ug::TangentialSmooth(), ug::TangentialSmoothSimple(), ug::TranslateDomain(), ug::TranslateSelection(), ug::TriangleFill(), ug::TrySplit(), ug::Valence4VertexIsObsolete(), ug::IVector_AlgebraDownCastTo< TVec >::vec_add(), ug::WeightedEdgeSmooth(), and ug::WeightedFaceSmooth().
VecAdd() [2/4]
template<typename vector_t > void ug::VecAdd (vector_t & vOut, const vector_t & v1, const vector_t & v2, const vector_t & v3) inline
adds three MathVector<N>s and stores the result in a fourth one
adds three Vectors and stores the result in a fourth one
VecAdd() [3/4]
template<typename vector_t > void ug::VecAdd (vector_t & vOut, const vector_t & v1, const vector_t & v2, const vector_t & v3, const vector_t & v4) inline
adds four MathVector<N>s and stores the result in a firth one
adds four Vectors and stores the result in a fifth one
VecAdd() [4/4]
template<typename vector_t > void ug::VecAdd (vector_t & vOut, const vector_t & v, typename vector_t::value_type s) inline
Add a scalar to a vector (componentwise)
VecAngle()
template<typename vector_t > vector_t::value_type ug::VecAngle (const vector_t & v1, const vector_t & v2) inline
returns the angle between two vectors in radiants
References ug::PI, ug::VecDot(), and ug::VecLengthSq().
Referenced by ug::DelaunayInfo< TAAPos >::init_marks(), ug::DelaunayInfo< TAAPos >::is_classifiable(), ug::OrderDownwindForDofDist(), ug::QualityGridGeneration(), ug::SelectKinkVertices(), and ug::SimplifyPolylines().
VecAngleNorm()
template<typename vector_t > vector_t::value_type ug::VecAngleNorm (const vector_t & v1, const vector_t & v2) inline
returns the angle between two vectors of length 1 in radiants
This method assumes that v1 and v2 are normalized vectors (both have length 1). No checks are performed!
References ug::PI, and ug::VecDot().
VecAppend() [1/4]
template<typename vector_t > void ug::VecAppend (vector_t & vOut, const vector_t & v1) inline
adds a MathVector<N> to a second one
adds a MathVector<N>s to a second one
Referenced by ug::ComputeElementExtensionsSq(), ug::ElementSize< ReferenceHexahedron, 3 >(), and ug::ElementSize< ReferencePrism, 3 >().
VecAppend() [2/4]
template<typename vector_t > void ug::VecAppend (vector_t & vOut, const vector_t & v1, const vector_t & v2) inline
adds two MathVector<N>s and adds the result to a third one
VecAppend() [3/4]
template<typename vector_t > void ug::VecAppend (vector_t & vOut, const vector_t & v1, const vector_t & v2, const vector_t & v3) inline
adds two MathVector<N>s and adds the result to a fourth one
adds three Vectors and adds the result to a fourth one
VecAppend() [4/4]
template<typename vector_t > void ug::VecAppend (vector_t & vOut, const vector_t & v1, const vector_t & v2, const vector_t & v3, const vector_t & v4) inline
adds two MathVector<N>s and adds the result to a fifth one
adds four Vectors and adds the result to a fifth one
VecCopy()
template<typename vector_target_t , typename vector_source_t > void ug::VecCopy (vector_target_t & target, const vector_source_t & source, typename vector_target_t::value_type fill)
Copy contents between vectors of possibly different types.
If the target vector is bigger than the source vector, additional entries will be set to the scalar given in the fill argument. If it is smaller, then the additional entries in the source vector are ignored.
Referenced by ug::ComputeDifferenceOnDelta(), ug::BalanceWeightsLuaCallback< TDomain >::get_weight_impl(), ug::GetElementByCoordinate(), ug::IntersectCoplanarTriangles(), ug::MarkForAdaption_ElementsContainingPoint(), ug::MarkForCoarsen_ElementsByLuaCallback(), ug::MarkForRefinement_ElementsByLuaCallback(), ug::PartitionElements_RegularGrid(), ug::ScaleDomain(), ug::ScaleDomainSqrtWeighting(), ug::ScaleDomainSquaredWeighting(), ug::ScaleDomainWeighting(), and ug::TranslateDomain().
VecCross()
template<typename vector_t > void ug::VecCross (vector_t & vOut, const vector_t & v1, const vector_t & v2) inline
calculates the cross product of two Vectors of dimension 3. It makes no sense to use VecCross for vector_ts that have not dimension 3.
calculates the cross product of two MathVector<N>s of dimension 3. It makes no sense to use VecCross for MathVector<N>s that have not dimension 3. todo: Create compile-time check for dimensionality in case of MathVector type.
References ug::GenVecCross().
Referenced by ug::CalculateMinTetrahedronHeight(), ug::CalculateOctahedronVolume(), ug::CalculatePyramidVolume(), ug::CalculateTetrahedronVolume(), ug::CalculateTriangleNormalNoNormalize(), ug::ConstructOrthonormalSystem(), ug::DelaunayLineLineIntersection(), ug::ElementNormal< ReferenceEdge, 3 >(), ug::ElementNormal< ReferenceQuadrilateral, 3 >(), ug::ElementNormal< ReferenceTriangle, 3 >(), ug::ElementSize< ReferenceHexahedron, 3 >(), ug::ElementSize< ReferenceOctahedron, 3 >(), ug::ElementSize< ReferencePrism, 3 >(), ug::ElementSize< ReferencePyramid, 3 >(), ug::ElementSize< ReferenceQuadrilateral, 3 >(), ug::ElementSize< ReferenceTetrahedron, 3 >(), ug::ElementSize< ReferenceTriangle, 3 >(), ug::GenVecCross< 3 >(), ug::PointIsInsideTetrahedron(), and ug::SlopeSmooth().
VecDistance()
template<typename vector_t > vector_t::value_type ug::VecDistance (const vector_t & v1, const vector_t & v2) inline
returns the distance of two vector_ts.
returns the distance of two MathVector<N>s.
References ug::VecDistanceSq().
Referenced by ug::CheckDoFElem(), ug::collectStretchedElementIndices(), ug::IDWInterpolation< WDim, TPntIterator, TData >::compute(), ug::DistancePointToLine(), ug::DistancePointToPlane(), ug::DistancePointToRay(), ug::DistancePointToTriangle(), ug::EdgeLength(), ug::ElementSize< ReferenceEdge, 1 >(), ug::ElementSize< ReferenceEdge, 2 >(), ug::ElementSize< ReferenceEdge, 3 >(), ug::FindVertexByCoordinate(), ug::MarkForAdaption_GradientAverage(), ug::fv1_traits_ReferenceFace3d::NormalOnSCVF_Face(), ug::DimLocalDoFSet< dim >::operator==(), ug::SphereProjector::perform_projection(), ug::ProjectVerticesToSphere(), ug::QualityGridGeneration(), ug::RayCylinderIntersection(), ug::RaySphereIntersection(), ug::ResolveTriangleIntersections(), ug::ScaleDomainSqrtWeighting(), ug::ScaleDomainSquaredWeighting(), ug::ScaleDomainWeighting(), ug::UpdateChainInfo(), and ug::VertexDistance().
VecDistanceSq()
template<typename vector_t > vector_t::value_type ug::VecDistanceSq (const vector_t & v1, const vector_t & v2) inline
returns the squared distance of two vector_ts.
returns the squared distance of two MathVector<N>s.
References ug::VecLengthSq(), and ug::VecSubtract().
Referenced by ug::AdaptSurfaceGridToCylinder(), ug::CalculateBoundingSphere(), ug::DelaunayInfo< TAAPos >::classify_face(), ug::bridge::Evaluate::CloseVertexExists(), ug::Sphere< vector_t >::contains_point(), ug::DelaunayLineLineIntersection(), ug::StdLagrangeElemTransfer< TDomain >::do_restrict(), ug::EdgeLengthSq(), ug::ElementDiameterSq(), ug::H1ErrorIntegrand< TGridFunction >::evaluate(), ug::H1SemiDiffIntegrand< TGridFunction >::evaluate(), ug::H1DiffIntegrand< TGridFunction >::evaluate(), ug::bridge::Evaluate::EvaluateAtVertex(), ug::ExpandFractures2d(), ug::ExpandFractures3d(), ug::FindClosestByCoordinate(), ug::FindCloseVertexInArray(), ug::FindVertexByCoordiante(), ug::FindVertexByCoordinate(), ug::IntersectCoplanarTriangles(), ug::Sphere< vector_t >::intersects(), ug::DelaunayInfo< TAAPos >::is_classifiable(), ug::IsDegenerated(), ug::IsSliver(), ug::MakeDelaunay(), ug::MarkForAdaption_VerticesInSphere(), ug::MarkForRefinement_ElementsInSphere(), ug::PerformCollapses(), ug::PerformSplits(), ug::ProjectVerticesToCloseEdges(), ug::ProjectVerticesToCloseFaces(), ug::QualityGridGeneration(), ug::tet_rules::Refine(), ug::RemoveDoubles(), ug::ResolveEdgeEdgeIntersection(), ug::ResolveVertexEdgeIntersection(), ug::ResolveVertexFaceIntersection(), ug::ScaleDomainSqrtWeighting(), ug::ScaleDomainSquaredWeighting(), ug::ScaleDomainWeighting(), ug::SeparateFaceSubsetsByNormal(), ug::SlopeSmooth(), ug::SnapMarkerPointToGridVertex(), ug::SplitOctahedronToTetrahedrons(), ug::TriangleCircumcenter(), ug::TriangleQuality_Area(), ug::UpdateChainInfo(), ug::Valence3VertexIsObsolete(), ug::Valence4VertexIsObsolete(), ug::VecDistance(), and ug::VertexDistanceSq().
VecDot()
template<typename vector_t > vector_t::value_type ug::VecDot (const vector_t & v1, const vector_t & v2) inline
returns the dot-product of two vector_ts
calculates the dot-product of two MathVector<N>s
Referenced by ug::ActiveSet< TDomain, TAlgebra >::active_index_elem(), ug::NeumannBoundaryFE< TDomain >::add_rhs_elem(), ug::NeumannBoundaryFV< TDomain >::add_rhs_elem(), ug::NeumannBoundaryFV1< TDomain >::add_rhs_elem(), ug::CalculateMinCurvature(), ug::CalculateNormalDot(), ug::CalculateOctahedronVolume(), ug::CalculatePolychainEdgeNormals(), ug::CalculateRightBendVal(), ug::CalculateTetrahedronVolume(), ug::ActiveSet< TDomain, TAlgebra >::check_conv_elem(), ug::CheckOrientation(), ug::DelaunayInfo< TAAPos >::classify_face(), ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem(), ug::ContainsPoint(), CopyCornerByMidID(), ug::FVPointSourceOrSink< dim, TData >::corresponds_to(), ug::FVLineSourceOrSink< dim, TData >::corresponds_to(), ug::DropAPerpendicular(), ug::ElementSize< ReferenceHexahedron, 3 >(), ug::ElementSize< ReferenceOctahedron, 3 >(), ug::ElementSize< ReferencePrism, 3 >(), ug::ElementSize< ReferencePyramid, 3 >(), ug::ElementSize< ReferenceTetrahedron, 3 >(), ug::LognormalRandomField< TData, dim, TRet >::eval_K(), ug::H1SemiNormFuncIntegrand< TGridFunction >::evaluate(), ug::H1NormFuncIntegrand< TGridFunction >::evaluate(), ug::EvaluateGradientJump_SideIntegral(), ug::ExpandFractures2d(), ug::ExpandFractures3d(), ug::FaceQuality(), ug::FindNormal(), ug::GeometricApproximationDegree(), ug::SingularSourcesAndSinks< dim, 1 >::get_contrib_of_scv(), ug::node_tree::Traverser_ProjectPoint::handle_collision_triangles(), ug::IntegralNormalComponentOnManifoldGeneral(), ug::IntegralNormalComponentOnManifoldUsingFV1Geom(), ug::IntegrateNormalGradientOnManifold(), ug::IntersectCoplanarTriangles(), ug::MarkCorners(), ug::MarkCreaseEdges(), ug::MarkForRefinement_AnisotropicDirection(), ug::MarkForRefinementByDirection(), ug::MatHouseholder(), ug::MinimizeEdgeLength_SwapsOnly(), ug::linker_traits< MathVector< dim >, MathVector< dim >, number >::mult_add(), ug::PointFaceTest(), ug::PointIsInsideQuadrilateral(), ug::PointIsInsideTetrahedron(), ug::PointIsInsideTriangle(), ug::ClusterElementStacks< elem_t, vector_t >::post_process(), ug::ProjectPointToPlane(), ug::ProjectPointToRay(), ug::ProjectPointToSurface(), ug::QuadDiagonalIsValid(), ug::RayCylinderIntersection(), ug::RayPlaneIntersection(), ug::RayRayProjection(), ug::ReflectVectorAtPlane(), ug::ResolveTriangleIntersections(), ug::SelectCreaseEdges(), ug::SelectEdgesByDirection(), ug::SelectLinkedFlatAndDegeneratedFaces(), ug::SelectLinkedFlatFaces(), ug::SelectSmoothEdgePath(), ug::SlopeSmooth(), ug::TangentialSmooth(), ug::TriangleCircumcenter(), ug::TriangleFill(), ug::TriangleFill_SweepLine(), ug::TriangleQuality(), ug::TrySwap(), ug::ConvectionShapesNoUpwind< TDim >::update(), ug::ConvectionShapesFullUpwind< TDim >::update(), ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::ConvectionShapesWeightedUpwind< TDim >::update(), ug::ConvectionShapesPartialUpwind< TDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), ug::UpdateChainInfo(), ug::VecAngle(), ug::VecAngleNorm(), and ug::WeightedNormalSmooth().
VecInftyNorm()
template<typename vector_t > vector_t::value_type ug::VecInftyNorm (const vector_t & v) inline
References ug::VecMaxNorm().
VecInterpolateLinear()
template<typename vector_t > void ug::VecInterpolateLinear (vector_t & vOut, const vector_t & v1, const vector_t & v2, typename vector_t::value_type interpAmount) inline
Referenced by ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), and ug::HFV1ManifoldGeometry< TElem, TWorldDim >::update().
VecLength()
template<typename vector_t > vector_t::value_type ug::VecLength (const vector_t & v) inline
returns the length of v. Slower than VecLengthSq.
References ug::VecLengthSq().
Referenced by ug::ActiveSet< TDomain, TAlgebra >::active_index_elem(), ug::CalculateMinTetrahedronHeight(), ug::CalculatePyramidVolume(), ug::ActiveSet< TDomain, TAlgebra >::check_conv_elem(), ug::DistanceLineToLine(), ug::FaceQuality(), ug::SingularSourcesAndSinks< dim, 1 >::get_contrib_of_scv(), ug::IntersectCoplanarTriangles(), ug::CylinderProjector::perform_projection(), ug::SphereProjector::perform_projection(), ug::RayCylinderIntersection(), ug::RaySphereIntersection(), ug::ObstacleInNormalDir< TDomain, TAlgebra >::transform_eulerian_coord_sys(), ug::TriangleArea(), ug::FV1Geometry< TElem, TWorldDim >::update(), ug::VecNormalize(), ug::VecTwoNorm(), and ug::Traverser_RayElementIntersection< tree_t >::visit_up().
VecLengthSq()
template<typename vector_t > vector_t::value_type ug::VecLengthSq (const vector_t & v) inline
returns the squared length of v. Faster than VecLength.
Referenced by ug::DelaunayLineLineIntersection(), ug::ExpandFractures2d(), ug::ExpandFractures3d(), ug::IntersectCoplanarTriangles(), ug::ParallelShiftIdentifier< TPosAA >::match_impl(), ug::OrderDownwindForDofDist(), ug::ClusterElementStacks< elem_t, vector_t >::post_process(), ug::QualityGridGeneration(), ug::SideAndElemErrEstData< TDomain >::summarize_err_est_data(), ug::VecAngle(), ug::VecDistanceSq(), ug::VecLength(), ug::VecTwoNormSq(), and ug::WeightedEdgeSmooth().
VecMaxNorm()
template<typename vector_t > vector_t::value_type ug::VecMaxNorm (const vector_t & v) inline
Referenced by ug::VecInftyNorm().
VecNormalize()
template<typename vector_t > void ug::VecNormalize (vector_t & vOut, const vector_t & v) inline
scales a vector_t to unit length
scales a MathVector<N> to unit length
References ug::VecLength(), and ug::VecScale().
Referenced by ug::AdaptSurfaceGridToCylinder(), ug::CalculateBoundaryVertexNormal2D(), ug::CalculateBoundaryVertexNormal3D(), ug::CalculateCreaseNormal(), ug::CalculateMinCurvature(), ug::CalculateNormal(), ug::CalculateNormalNoNormalize(), ug::CalculateOuterNormal(), ug::CalculatePolychainEdgeNormals(), ug::CalculateRightBendVal(), ug::CalculateTriangleNormal(), ug::CalculateVertexNormal(), ug::CalculateVertexNormals(), ug::DelaunayInfo< TAAPos >::classify_face(), ug::CollapseEdge(), ug::NeumannBoundaryFV1< TDomain >::compute_err_est_rhs_elem(), ug::ConstructOrthonormalSystem(), ug::DelaunayLineLineIntersection(), ug::ElementNormal< ReferenceEdge, 3 >(), ug::ElementNormal< ReferenceVertex, 2 >(), ug::ElementNormal< ReferenceVertex, 3 >(), ug::ExpandFractures2d(), ug::ExpandFractures3d(), ug::FindClosestPlane(), ug::FindNormal(), ug::GetColorFromStandardPalette(), ug::GetEdgeOnTheLeft(), ug::MarkCorners(), ug::MarkForRefinement_AnisotropicDirection(), ug::MarkForRefinementByDirection(), ug::fv1_traits< ReferenceEdge, 1 >::NormalOnSCVF(), ug::fv1_traits< ReferenceEdge, 2 >::NormalOnSCVF(), ug::fv1_traits< ReferenceEdge, 3 >::NormalOnSCVF(), ug::fv1_traits_ReferenceFace3d::NormalOnSCVF_Face(), ug::ObtainSimpleGrid_CollapseEdge(), ug::ClusterElementStacks< elem_t, vector_t >::post_process(), ug::ProjectPointToPlane(), ug::QualityGridGeneration(), ug::RayCylinderIntersection(), ug::SelectEdgesByDirection(), ug::SelectSmoothEdgePath(), ug::SlopeSmooth(), ug::TangentialSmooth(), ug::TriangleFill(), ug::TriangleFill_SweepLine(), ug::TriangleQuality(), ug::TrySplit(), ug::TrySwap(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), ug::DimFVGeometry< TWorldDim, TDim >::update(), and ug::WeightedNormalSmooth().
VecOneNorm()
template<typename vector_t > vector_t::value_type ug::VecOneNorm (const vector_t & v) inline
VecPNorm()
template<typename vector_t > vector_t::value_type ug::VecPNorm (const vector_t & v, unsigned int p) inline
VecScale()
template<typename vector_t > void ug::VecScale (vector_t & vOut, const vector_t & v, typename vector_t::value_type s) inline
scales a MathVector<N>
Referenced by ug::ApplySmoothManifoldPosToTopLevelAveragingScheme(), ug::ApplySmoothVolumePosToTopLevel(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::calculate_center(), ug::ntree< tree_dim, world_dim, Triangle *, NTreeGridData< world_dim > >::calculate_center_of_mass(), ug::CalculateBarycenter(), ug::CalculateCenter(), ug::CalculateMinTetrahedronHeight(), ug::CalculateNormalNoNormalize(), ug::CalculateRightBendVal(), ug::AABox< ug::MathVector< dim > >::center(), ug::CollapseEdge(), ug::ComputeElementExtensionsSq(), ug::FileReaderSWC::create_grid(), ug::CreatePrism(), ug::node_tree::CreateSubOctrees(), ug::DropAPerpendicular(), ug::ElementNormal< ReferenceEdge, 3 >(), ug::ElementNormal< ReferenceQuadrilateral, 3 >(), ug::ElementNormal< ReferenceTriangle, 3 >(), ug::DarcyVelocityLinker< dim >::eval_and_deriv(), ug::DarcyVelocityLinker< dim >::evaluate(), ug::ExplicitGridFunctionGradient< TGridFunction >::evaluate(), ug::ExpandFractures2d(), ug::ExpandFractures3d(), ug::ExtrudeCylinder(), ug::FaceQuality(), ug::FindNormal(), ug::GetEdgeOnTheLeft(), ug::node_tree::GrowBox(), ug::IntersectCoplanarTriangles(), ug::LaplacianSmooth(), ug::fv1_traits_ReferenceFace3d::NormalOnSCVF_Face(), ug::CylinderProjector::perform_projection(), ug::SphereProjector::perform_projection(), ug::ProjectPointToPlane(), ug::ProjectPointToRay(), ug::ProjectToLimitPLoop(), ug::QualityGridGeneration(), ug::RayCylinderIntersection(), ug::RayPlaneIntersection(), ug::tet_rules::Refine(), ug::ParallelShiftIdentifier< TPosAA >::set_shift(), ug::SnapMarkerPointToGridVertex(), ug::TangentialSmooth(), ug::TangentialSmoothSimple(), ug::ObstacleInNormalDir< TDomain, TAlgebra >::transform_eulerian_coord_sys(), ug::TriangleFill(), ug::TriangleQuality(), ug::ConvectionShapesNoUpwind< TDim >::update(), ug::ConvectionShapesFullUpwind< TDim >::update(), ug::ConvectionShapesWeightedUpwind< TDim >::update(), ug::ConvectionShapesPartialUpwind< TDim >::update(), ug::VecNormalize(), and ug::Traverser_RayElementIntersection< tree_t >::visit_up().
VecScaleAdd() [1/3]
template<typename vector_t > void ug::VecScaleAdd (vector_t & vOut, typename vector_t::value_type s1, const vector_t & v1, typename vector_t::value_type s2, const vector_t & v2) inline
Scales two Vectors, adds them and returns the sum in a third vector.
Referenced by ug::AdaptSurfaceGridToCylinder(), ug::ElementSideRayIntersectionWrapper< TRefElem, 2, 2 >::apply(), ug::ElementSideRayIntersectionWrapper< TRefElem, 3, 3 >::apply(), ug::SCVFofSCVRayIntersectionWrapper< 2, 2 >::apply(), ug::CG< TVector >::apply_return_defect(), ug::BiCGStab< TVector >::apply_return_defect(), ug::ApplySmoothManifoldPosToTopLevelAveragingScheme(), ug::ApplySmoothVolumePosToTopLevel(), ug::bridge::AlgebraCommon::VecScaleAddClass< TAlgebra >::assign(), ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::CalculateCenter(), ug::ComputeMidPoints(), ComputeMidPoints(), ug::FVLineSourceOrSink< dim, TData >::corresponds_to(), ug::GenerateIcosahedron(), ug::SingularSourcesAndSinks< dim, 1 >::get_contrib_of_scv(), ug::node_tree::Traverser_ProjectPoint::handle_collision_edges(), ug::IntegrateNormalGradientOnManifold(), ug::InterpolateValues(), ug::LaplacianSmooth(), ug::ReferenceMapping< ReferenceEdge, TWorldDim >::local_to_global(), ug::ReferenceMapping< ReferenceTriangle, TWorldDim >::local_to_global(), ug::ReferenceMapping< ReferenceQuadrilateral, TWorldDim >::local_to_global(), ug::ReferenceMapping< ReferenceTetrahedron, TWorldDim >::local_to_global(), ug::mat_operations_class< vector_t, matrix_t, MATRIX_USE_ROW_FUNCTIONS >::MatMultAdd(), ug::MatMultAdd(), ug::MatMultAddDirect(), ug::CylinderCutProjector::new_vertex(), ug::SubdivisionProjector::new_vertex(), ug::ProjectToLimitPLoop(), ug::ProjectToLimitSubdivBoundary(), ug::ProjectVerticesToSphere(), ug::ProlongateP1(), ug::QualityGridGeneration(), ug::SubdivisionProjector::refinement_begins(), ug::ReflectVectorAtPlane(), ug::ResolveEdgeEdgeIntersection(), ug::StandardLineSearch< TVector >::search(), ug::SetLagrangeEdgeMultiIndex(), ug::SlopeSmooth(), ug::TangentialSmooth(), ug::TangentialSmoothSimple(), ug::ObstacleInNormalDir< TDomain, TAlgebra >::transform_eulerian_coord_sys(), ug::TriangleBarycenter(), ug::TriangleCircumcenter(), ug::FetiLayouts< algebra_type >::vec_scale_add_on_dual(), ug::FetiLayouts< algebra_type >::vec_scale_add_on_primal(), ug::FetiLayouts< algebra_type >::vec_scale_append_on_dual(), ug::FetiLayouts< algebra_type >::vec_scale_append_on_primal(), ug::VecScaleAdd(), ug::bridge::AlgebraCommon::VecScaleAdd2(), ug::bridge::AlgebraCommon::VecScaleAdd3(), ug::GMRES< TVector >::VecScaleAppend(), ug::VectorAssign(), and ug::WeightedFaceSmooth().
VecScaleAdd() [2/3]
template<typename vector_t > void ug::VecScaleAdd (vector_t & vOut, typename vector_t::value_type s1, const vector_t & v1, typename vector_t::value_type s2, const vector_t & v2, typename vector_t::value_type s3, const vector_t & v3) inline
Scales three Vectors, adds them and returns the sum in a fourth vector.
VecScaleAdd() [3/3]
template<typename vector_t > void ug::VecScaleAdd (vector_t & vOut, typename vector_t::value_type s1, const vector_t & v1, typename vector_t::value_type s2, const vector_t & v2, typename vector_t::value_type s3, const vector_t & v3, typename vector_t::value_type s4, const vector_t & v4) inline
Scales four Vectors, adds them and returns the sum in a fifth vector.
VecScaleAppend() [1/4]
template<typename vector_t > void ug::VecScaleAppend (vector_t & vOut, typename vector_t::value_type s1, const vector_t & v1) inline
Scales a Vector and adds it to a second vector.
Referenced by ug::CalculateCenter(), ug::CalculateConstrainedSmoothVolumePosInTopLevel(), ug::CalculateSmoothManifoldPosInParentLevelLoopScheme(), ug::CalculateSmoothManifoldPosInTopLevelAveragingScheme(), ug::CalculateSmoothVolumePosInTopLevel(), ug::GradientDataExport< dim >::eval_and_deriv(), ug::DarcyVelocityLinker< dim >::eval_and_deriv(), ug::GridFunctionGradientData< TGridFunction >::eval_and_deriv(), ug::GridFunctionGradientComponentData< TGridFunction >::eval_and_deriv(), ug::ExplicitGridFunctionGradient< TGridFunction >::evaluate(), ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate(), ug::H1ErrorIntegrand< TGridFunction >::evaluate(), ug::H1SemiDiffIntegrand< TGridFunction >::evaluate(), ug::H1DiffIntegrand< TGridFunction >::evaluate(), ug::H1SemiNormFuncIntegrand< TGridFunction >::evaluate(), ug::H1NormFuncIntegrand< TGridFunction >::evaluate(), ug::linker_traits< MathVector< dim >, number >::mult_add(), ug::RayRayIntersection2d(), ug::SetLagrangeFaceMultiIndex(), ug::ConvectionShapesWeightedUpwind< TDim >::update(), ug::DimFVGeometry< TWorldDim, TDim >::update_local(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_local_data().
VecScaleAppend() [2/4]
template<typename vector_t > void ug::VecScaleAppend (vector_t & vOut, typename vector_t::value_type s1, const vector_t & v1, typename vector_t::value_type s2, const vector_t & v2) inline
Scales two Vectors, adds them and adds the sum to a third vector.
Scales two Vectors, adds the sum to a third vector.
VecScaleAppend() [3/4]
template<typename vector_t > void ug::VecScaleAppend (vector_t & vOut, typename vector_t::value_type s1, const vector_t & v1, typename vector_t::value_type s2, const vector_t & v2, typename vector_t::value_type s3, const vector_t & v3) inline
Scales three Vectors, adds them and adds the sum to a fourth vector.
Scales three Vectors, adds the sum to a fourth vector.
VecScaleAppend() [4/4]
template<typename vector_t > void ug::VecScaleAppend (vector_t & vOut, typename vector_t::value_type s1, const vector_t & v1, typename vector_t::value_type s2, const vector_t & v2, typename vector_t::value_type s3, const vector_t & v3, typename vector_t::value_type s4, const vector_t & v4) inline
Scales four Vectors, adds them and adds the sum to a fifth vector.
Scales four Vectors, adds the sum to a fifth vector.
VecSet()
template<typename vector_t > void ug::VecSet (vector_t & vInOut, typename vector_t::value_type s) inline
Set each vector component to scalar (componentwise)
Set each vector component to scalar.
Referenced by ug::AABox< ug::MathVector< dim > >::AABox(), ug::ntree< tree_dim, world_dim, Triangle *, NTreeGridData< world_dim > >::calculate_center_of_mass(), ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::CalculateBarycenter(), ug::CalculateBoundaryVertexNormal2D(), ug::CalculateBoundaryVertexNormal3D(), ug::CalculateBoundingBox(), ug::CalculateCenter(), ug::CalculateConstrainedSmoothVolumePosInTopLevel(), ug::CalculateCreaseNormal(), ug::CalculateOuterNormal(), ug::CalculateSmoothManifoldPosInParentLevelLoopScheme(), ug::CalculateSmoothManifoldPosInTopLevelAveragingScheme(), ug::CalculateSmoothVolumePosInTopLevel(), ug::ClusterElementStacks< elem_t, vector_t >::ClusterElementStacks(), ug::StdLinConsistentGravity< refDim >::compute(), ug::StdLinConsistentGravityX< refDim >::compute(), ug::ComputeGradientCrouzeixRaviart(), ug::ComputeGradientLagrange1(), ug::GradientDataExport< dim >::eval_and_deriv(), ug::GridFunctionGradientData< TGridFunction >::eval_and_deriv(), ug::GridFunctionGradientComponentData< TGridFunction >::eval_and_deriv(), ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate(), ug::GlobalGridFunctionNumberData< TGridFunction, elemDim >::evaluate(), ug::ExplicitGridFunctionGradient< TGridFunction >::evaluate(), ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate(), ug::H1ErrorIntegrand< TGridFunction >::evaluate(), ug::L2DiffIntegrand< TGridFunction >::evaluate(), ug::H1SemiDiffIntegrand< TGridFunction >::evaluate(), ug::H1DiffIntegrand< TGridFunction >::evaluate(), ug::H1SemiNormFuncIntegrand< TGridFunction >::evaluate(), ug::H1NormFuncIntegrand< TGridFunction >::evaluate(), ug::PiecewiseConstantLSFS< TRefElem >::grad(), ug::IntegrateNormalGradientOnManifold(), ug::LaplacianSmooth(), ug::MarkForAdaption_GradientAverage(), ug::StdLinConsistentGravity< refDim >::prepare_edge(), ug::StdLinConsistentGravity< refDim >::prepare_quadrilateral(), ug::StdLinConsistentGravity< refDim >::prepare_triangle(), ug::ProjectVerticesToCloseEdges(), ug::ProjectVerticesToCloseFaces(), ug::ProlongateElemwise(), ug::SubdivisionProjector::refinement_begins(), ug::RestrictElemwise(), ug::ConvectionShapesNoUpwind< TDim >::update(), ug::ConvectionShapesFullUpwind< TDim >::update(), ug::ConvectionShapesWeightedUpwind< TDim >::update(), ug::ConvectionShapesPartialUpwind< TDim >::update(), ug::FetiLayouts< algebra_type >::vec_set_on_dual(), ug::FetiLayouts< algebra_type >::vec_set_on_primal(), ug::Traverser_RayElementIntersection< tree_t >::visit_up(), ug::WeightedEdgeSmooth(), ug::WeightedFaceSmooth(), and ug::WeightedNormalSmooth().
VecSubtract() [1/2]
template<typename vector_t > void ug::VecSubtract (vector_t & vOut, const vector_t & v1, const vector_t & v2) inline
subtracts v2 from v1 and stores the result in a vOut
Referenced by ug::AABox< ug::MathVector< dim > >::AABox(), ug::AdaptSurfaceGridToCylinder(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::box_diagonal(), ug::CalculateCreaseNormal(), ug::CalculateMinTetrahedronHeight(), ug::CalculateNormal(), ug::CalculateNormalNoNormalize(), ug::CalculateOctahedronVolume(), ug::CalculateOuterNormal(), ug::CalculatePolychainEdgeNormals(), ug::CalculatePyramidVolume(), ug::CalculateTetrahedronVolume(), ug::CalculateTriangleNormalNoNormalize(), ug::CheckOrientation(), ug::DelaunayInfo< TAAPos >::classify_face(), ug::ComputeElementExtensionsSq(), ug::ContainsPoint(), CopyCornerByMidID(), ug::FVPointSourceOrSink< dim, TData >::corresponds_to(), ug::FVLineSourceOrSink< dim, TData >::corresponds_to(), ug::CutEdgesWithPlane(), ug::DelaunayLineLineIntersection(), ug::DistancePointToTriangle(), ug::DropAPerpendicular(), ug::ElementNormal< ReferenceEdge, 3 >(), ug::ElementNormal< ReferenceQuadrilateral, 3 >(), ug::ElementNormal< ReferenceTriangle, 3 >(), ug::ElementSize< ReferenceHexahedron, 3 >(), ug::ElementSize< ReferenceOctahedron, 3 >(), ug::ElementSize< ReferencePrism, 3 >(), ug::ElementSize< ReferencePyramid, 3 >(), ug::ElementSize< ReferenceQuadrilateral, 3 >(), ug::ElementSize< ReferenceTetrahedron, 3 >(), ug::ElementSize< ReferenceTriangle, 3 >(), ug::DarcyVelocityLinker< dim >::eval_and_deriv(), ug::DarcyVelocityLinker< dim >::evaluate(), ug::AABox< ug::MathVector< dim > >::extension(), ug::ExtrudeLayers(), ug::FaceQuality(), ug::FindNormal(), ug::SingularSourcesAndSinks< dim, 1 >::get_contrib_of_scv(), ug::BaseReferenceMapping< ReferenceTriangle::dim, TWorldDim, true, ReferenceMapping< ReferenceTriangle, TWorldDim > >::global_to_local(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::grow_box(), ug::node_tree::GrowBox(), ug::IdentifySubsets(), ug::DelaunayInfo< TAAPos >::init_marks(), ug::IntersectCoplanarTriangles(), ug::IntersectPlaneWithTetrahedron(), ug::DelaunayInfo< TAAPos >::is_classifiable(), ug::LaplacianSmooth(), ug::LineBoxIntersection(), ug::LineLineIntersection2d(), ug::LineLineProjection(), ug::LineSphereIntersection(), ug::MarkCorners(), ug::MarkForRefinement_AnisotropicDirection(), ug::MarkForRefinementByDirection(), ug::ParallelShiftIdentifier< TPosAA >::match_impl(), ug::MultiEdgeSplit(), ug::PlaneCutProjector::new_vertex(), ug::CylinderCutProjector::new_vertex(), ug::fv1_traits< ReferenceEdge, 2 >::NormalOnSCVF(), ug::fv1_traits< ReferenceEdge, 3 >::NormalOnSCVF(), ug::OrderDownwindForDofDist(), ug::CylinderProjector::perform_projection(), ug::SphereProjector::perform_projection(), ug::PointFaceTest(), ug::PointIsInsideQuadrilateral(), ug::PointIsInsideTetrahedron(), ug::PointIsInsideTriangle(), ug::StdLinConsistentGravityX< refDim >::prepare_simplex(), ug::ProjectPointToLine(), ug::ProjectPointToPlane(), ug::ProjectPointToRay(), ug::ProjectVerticesToSphere(), ug::QualityGridGeneration(), ug::RayCylinderIntersection(), ug::RayLineIntersection2d(), ug::RayPlaneIntersection(), ug::RayRayIntersection2d(), ug::RayRayProjection(), ug::ResolveEdgeFaceIntersection(), ug::SelectEdgesByDirection(), ug::SelectKinkVertices(), ug::SelectSmoothEdgePath(), ug::SetLagrangeFaceMultiIndex(), ug::SimplifyPolylines(), ug::SideAndElemErrEstData< TDomain >::summarize_err_est_data(), ug::TangentialSmooth(), ug::TransformPointSetTo2D(), ug::TriangleArea(), ug::TriangleBoxIntersection(), ug::TriangleCircumcenter(), ug::TriangleFill(), ug::TriangleFill_SweepLine(), ug::TriangleQuality(), ug::TrySwap(), ug::HFV1Geometry< TElem, TWorldDim >::update(), ug::ReferenceMapping< ReferenceEdge, TWorldDim >::update(), ug::ReferenceMapping< ReferenceTriangle, TWorldDim >::update(), ug::DimHFV1Geometry< TDim, TWorldDim >::update(), ug::ReferenceMapping< ReferenceTetrahedron, TWorldDim >::update(), ug::UpdateChainInfo(), ug::VecDistanceSq(), ug::WeightedEdgeSmooth(), and ug::WeightedFaceSmooth().
VecSubtract() [2/2]
template<typename vector_t > void ug::VecSubtract (vector_t & vOut, const vector_t & v, typename vector_t::value_type s) inline
Subtract a scalar from a vector (componentwise)
VecTwoNorm()
template<typename vector_t > vector_t::value_type ug::VecTwoNorm (const vector_t & v) inline
References ug::VecLength().
Referenced by ug::ComputeGradientCrouzeixRaviart(), ug::ComputeGradientLagrange1(), ug::ComputeGradientPiecewiseConstant(), CopyCornerByMidID(), ug::ElementNormal< ReferenceEdge, 3 >(), ug::ElementSideRayIntersection(), ug::ElementSize< ReferenceQuadrilateral, 3 >(), ug::ElementSize< ReferenceTriangle, 3 >(), ug::EvaluateGradientJump_Norm(), ug::BaseReferenceMapping< ReferenceTriangle::dim, TWorldDim, true, ReferenceMapping< ReferenceTriangle, TWorldDim > >::global_to_local(), ug::SCVFofSCVRayIntersection(), ug::DimFEGeometry< TWorldDim, TRefDim >::update_boundary_faces(), ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces(), ug::DimCRFVGeometry< TDim, TWorldDim >::update_boundary_faces(), ug::DimFV1Geometry< TDim, TWorldDim >::update_boundary_faces(), ug::DimFVGeometry< TWorldDim, TDim >::update_boundary_faces(), and ug::CRFVGeometry< TElem, TWorldDim >::update_boundary_faces().
VecTwoNormSq()
template<typename vector_t > vector_t::value_type ug::VecTwoNormSq (const vector_t & v) inline
References ug::VecLengthSq().
Referenced by ug::BaseReferenceMapping< ReferenceTriangle::dim, TWorldDim, true, ReferenceMapping< ReferenceTriangle, TWorldDim > >::global_to_local(), ug::PointIsInsideQuadrilateral(), ug::PointIsInsideTetrahedron(), and ug::PointIsInsideTriangle().
write_plain_txt() [1/4]
UG_API std::ostream & ug::write_plain_txt (std::ostream & outStream, const ug::MathVector< 1 > & v)
plain text output of MathVector objects: space-separated coordinates
References ug::MathVector< N, T >::coord().
Referenced by ug::operator<<().
write_plain_txt() [2/4]
UG_API std::ostream & ug::write_plain_txt (std::ostream & outStream, const ug::MathVector< 2 > & v)
plain text output of MathVector objects: space-separated coordinates
References ug::MathVector< N, T >::coord().
write_plain_txt() [3/4]
UG_API std::ostream & ug::write_plain_txt (std::ostream & outStream, const ug::MathVector< 3 > & v)
plain text output of MathVector objects: space-separated coordinates
References ug::MathVector< N, T >::coord().
write_plain_txt() [4/4]
UG_API std::ostream & ug::write_plain_txt (std::ostream & outStream, const ug::MathVector< 4 > & v)
plain text output of MathVector objects: space-separated coordinates
References ug::MathVector< N, T >::coord().