ug4: Common Types
Common Types
ugbase » Common » Common Utilities
Namespaces
ug
the ug namespace
Classes
struct ug::StringTableStream::RepeatedCol
class ug::StringTableStream
class ug::Table< T >
Useful for printing a table to the terminal or into a file.
class ug::Variant
A variant can represent variables of different types.
Typedefs
typedef Table< std::stringstream > ug::StringStreamTable
typedef Table< std::string > ug::StringTable
Functions
template<class TType >
int ug::ArrayEraseEntry (TType *array, const TType &entry, size_t size)
removes the first occurance of the specified entry.
template<class TType >
bool ug::ArrayReplaceEntry (TType *array, const TType &newEntry, const TType &oldEntry, size_t size)
replaces the first occurance of oldEntry with newEntry
template<class TType >
void ug::ArraySwapWithLast (TType *array, const TType &entry, size_t size)
Swaps the first entry with the given value with the last entry in the list.
void ug::StringTableStream::clear ()
RepeatedCol ug::StringTableStream::empty_col (size_t i)
template<class T >
std::string ug::EntryToString (const Table< T > &table, size_t rowInd, size_t colInd)
Returns a string-representation of the current entry.
std::string ug::EntryToString (const Table< std::string > &table, size_t rowInd, size_t colInd)
std::string ug::EntryToString (const Table< std::stringstream > &table, size_t rowInd, size_t colInd)
template<typename T >
StringTableStream & ug::StringTableStream::operator<< (T t)
StringTableStream & ug::StringTableStream::operator<< (const char *c)
StringTableStream & ug::StringTableStream::operator<< (RepeatedCol c)
StringTableStream & ug::StringTableStream::operator<< (std::string str)
std::ostream & ug::operator<< (std::ostream &os, const StringTableStream &sts)
template<class T >
std::ostream & ug::operator<< (std::ostream &os, const Table< T > &table)
prints a table to the specified ostream.
template<typename T >
RepeatedCol ug::StringTableStream::repeat_col (size_t nrRepeat, T contentToRepeat)
ug::StringTableStream::RepeatedCol::RepeatedCol (std::string _content, size_t _number)
template<typename T >
void ug::StringTableStream::set (size_t r, size_t c, T t)
ug::StringTableStream::StringTableStream ()
StringTable & ug::StringTableStream::table ()
template<>
bool ug::Variant::to () const
std::string ug::StringTableStream::to_string () const
template<>
Variant::Type ug::Variant::type ()
template<>
const std::string & ug::Variant::to< const std::string & > () const
template<>
std::string ug::Variant::to< std::string > () const
template<>
Variant::Type ug::Variant::type< const std::string & > ()
template<>
Variant::Type ug::Variant::type< std::string > ()
Variables
std::string ug::StringTableStream::RepeatedCol::content
size_t ug::StringTableStream::m_curCol
size_t ug::StringTableStream::m_curRow
size_t ug::StringTableStream::RepeatedCol::number
StringTable ug::StringTableStream::s
Detailed Description
Useful for printing a table like a stream to the terminal or into a file.
Typedef Documentation
StringStreamTable
typedef Table<std::stringstream> ug::StringStreamTable
StringTable
typedef Table<std::string> ug::StringTable
Function Documentation
ArrayEraseEntry()
template<class TType > int ug::ArrayEraseEntry (TType * array, const TType & entry, size_t size)
removes the first occurance of the specified entry.
Runs in O(size). copies all entries after the specified one to their predecessor. Be sure that TType supports operator= and operator==
Returns
new size
Referenced by ug::MGEdgeInfo::remove_child(), and ug::MGFaceInfo::remove_child().
ArrayReplaceEntry()
template<class TType > bool ug::ArrayReplaceEntry (TType * array, const TType & newEntry, const TType & oldEntry, size_t size)
replaces the first occurance of oldEntry with newEntry
Runs in O(size). Be sure that TType supports operator= and operator==
Returns
true if oldEntry was found, false if not.
Referenced by ug::MGEdgeInfo::replace_child(), ug::MGFaceInfo::replace_child(), and ug::MGVolumeInfo::replace_child().
ArraySwapWithLast()
template<class TType > void ug::ArraySwapWithLast (TType * array, const TType & entry, size_t size)
Swaps the first entry with the given value with the last entry in the list.
Runs in O(size). Iterates through all entries until the given one is found. Be sure that TType supports operator= and operator==
Referenced by ug::MGVolumeInfo::remove_child().
clear()
void ug::StringTableStream::clear () inline
References ug::Table< T >::clear().
empty_col()
RepeatedCol ug::StringTableStream::empty_col (size_t i) inline
ug::StringTableStream sts;
sts << 1 << "\n";
sts << sts.emtpy_col(1) << 1 << "\n";
sts << sts.empty_col(2) << 1 << "\n";
prints
* 1
*   1
*     1
*
Parameters
nrRepeat number of times to repeat
contentToRepeat what to repeat
Returns
RepeatedCol-struct for <<-ing into sts
References ug::StringTableStream::RepeatedCol::RepeatedCol().
EntryToString() [1/3]
template<class T > std::string ug::EntryToString (const Table< T > & table, size_t rowInd, size_t colInd) inline
Returns a string-representation of the current entry.
The default implementation prints the entry to a std::stringstream and returns the associated string. Specializations exist for std::string and std::stringstream.
Referenced by ug::Table< std::stringstream >::stream(), ug::Table< std::stringstream >::to_csv(), and ug::Table< std::stringstream >::to_latex().
EntryToString() [2/3]
std::string ug::EntryToString (const Table< std::string > & table, size_t rowInd, size_t colInd) inline
EntryToString() [3/3]
std::string ug::EntryToString (const Table< std::stringstream > & table, size_t rowInd, size_t colInd) inline
operator<<() [1/6]
template<typename T > StringTableStream& ug::StringTableStream::operator<< (T t) inline
operator <<. sets curCol++
Parameters
t anything which is ostream << -able
Returns
*this
References ug::StringTableStream::s, and ug::ToString().
operator<<() [2/6]
StringTableStream& ug::StringTableStream::operator<< (const char * c) inline
operator <<
Parameters
c a const char *. If contains a
, sets curRow++, curCol=0
Returns
*this
References ug::Table< T >::clear(), and ug::StringTableStream::s.
operator<<() [3/6]
StringTableStream& ug::StringTableStream::operator<< (RepeatedCol c) inline
References ug::StringTableStream::RepeatedCol::content, and ug::StringTableStream::RepeatedCol::number.
operator<<() [4/6]
StringTableStream& ug::StringTableStream::operator<< (std::string str) inline
operator<<() [5/6]
std::ostream& ug::operator<< (std::ostream & os, const StringTableStream & sts) inline
References ug::StringTableStream::to_string().
operator<<() [6/6]
template<class T > std::ostream & ug::operator<< (std::ostream & os, const Table< T > & table)
prints a table to the specified ostream.
Assumes that output begins at a new line. The method uses the template method size_t EstimateEntryWidth<T>(const Table<T>& table, size_t rowInd, size_t colInd). You may overload this method to adjust it to your datatypes. Note that specializations exist for std::string and std::stringstream.
Todo:
Support for line-breaks ('
' etc) and multi-line rows.
repeat_col()
template<typename T > RepeatedCol ug::StringTableStream::repeat_col (size_t nrRepeat, T contentToRepeat) inline
ug::StringTableStream sts;
sts << 1 << sts.repeat_col(2, 0) << "\n";
sts << 0 << 1 << 0 << "\n";
sts << sts.repeat(2, 0) << 1 << "\n";
prints
* 1 0 0
* 0 1 0
* 0 0 1
*
Parameters
nrRepeat number of times to repeat
contentToRepeat what to repeat
Returns
RepeatedCol-struct for <<-ing into sts
References ug::StringTableStream::RepeatedCol::RepeatedCol(), and ug::ToString().
RepeatedCol()
ug::StringTableStream::RepeatedCol::RepeatedCol (std::string _content, size_t _number) inline
Referenced by ug::StringTableStream::empty_col(), and ug::StringTableStream::repeat_col().
set()
template<typename T > void ug::StringTableStream::set (size_t r, size_t c, T t) inline
References ug::StringTableStream::s, and ug::ToString().
StringTableStream()
ug::StringTableStream::StringTableStream () inline
table()
StringTable& ug::StringTableStream::table () inline
References ug::StringTableStream::s.
to()
template<> bool ug::Variant::to () const inline
to_string()
std::string ug::StringTableStream::to_string () const inline
References ug::Table< T >::to_string().
Referenced by ug::bridge::LuaStackTraceString(), and ug::operator<<().
type()
template<> Variant::Type ug::Variant::type () inline
Variant::to< const std::string & >()
template<> const std::string& ug::Variant::to< const std::string &> () const inline
Variant::to< std::string >()
template<> std::string ug::Variant::to< std::string > () const inline
Variant::type< const std::string & >()
template<> Variant::Type ug::Variant::type< const std::string &> () inline
Variant::type< std::string >()
template<> Variant::Type ug::Variant::type< std::string > () inline
Variable Documentation
content
std::string ug::StringTableStream::RepeatedCol::content
Referenced by ug::StringTableStream::operator<<().
m_curCol
size_t ug::StringTableStream::m_curCol private
m_curRow
size_t ug::StringTableStream::m_curRow private
number
size_t ug::StringTableStream::RepeatedCol::number
Referenced by ug::StringTableStream::operator<<().
s
StringTable ug::StringTableStream::s private
Referenced by ug::StringTableStream::operator<<(), ug::StringTableStream::set(), and ug::StringTableStream::table().