ug4: Transformation Bridge
Transformation Bridge
ugbase » Bridge » Domain Bridge
Classes
struct ug::bridge::Transform::Functionality
Functions
template<class TDomain >
void ug::ScaleDomain (TDomain &dom, const vector3 &center, const vector3 &scale)
Scales selected elements around the given center.
template<class TDomain >
void ug::ScaleDomain (TDomain &dom, ISelector &sel, const vector3 &center, const vector3 &scale)
Scales selected elements around the given center.
template<class TDomain >
void ug::ScaleDomainSqrtWeighting (TDomain &dom, ISelector &sel, const vector3 &center, const vector3 &scale)
template<class TDomain >
void ug::ScaleDomainSquaredWeighting (TDomain &dom, ISelector &sel, const vector3 &center, const vector3 &scale)
template<class TDomain >
void ug::ScaleDomainWeighting (TDomain &dom, ISelector &sel, const vector3 &center, const vector3 &scale)
template<class TDomain >
void ug::TranslateDomain (TDomain &dom, ISelector &sel, const vector3 &offset)
Translates (moves) selected elements by the given offset.
Detailed Description
Function Documentation
ScaleDomain() [1/2]
template<class TDomain > void ug::ScaleDomain (TDomain & dom, const vector3 & center, const vector3 & scale)
Scales selected elements around the given center.
References s, and ug::VecCopy().
ScaleDomain() [2/2]
template<class TDomain > void ug::ScaleDomain (TDomain & dom, ISelector & sel, const vector3 & center, const vector3 & scale)
Scales selected elements around the given center.
References ug::CollectVerticesTouchingSelection(), s, and ug::VecCopy().
ScaleDomainSqrtWeighting()
template<class TDomain > void ug::ScaleDomainSqrtWeighting (TDomain & dom, ISelector & sel, const vector3 & center, const vector3 & scale)
References ug::CollectVerticesTouchingSelection(), s, ug::VecCopy(), ug::VecDistance(), and ug::VecDistanceSq().
ScaleDomainSquaredWeighting()
template<class TDomain > void ug::ScaleDomainSquaredWeighting (TDomain & dom, ISelector & sel, const vector3 & center, const vector3 & scale)
References ug::CollectVerticesTouchingSelection(), s, ug::VecCopy(), ug::VecDistance(), and ug::VecDistanceSq().
ScaleDomainWeighting()
template<class TDomain > void ug::ScaleDomainWeighting (TDomain & dom, ISelector & sel, const vector3 & center, const vector3 & scale)
References ug::CollectVerticesTouchingSelection(), s, ug::VecCopy(), ug::VecDistance(), and ug::VecDistanceSq().
TranslateDomain()
template<class TDomain > void ug::TranslateDomain (TDomain & dom, ISelector & sel, const vector3 & offset)
Translates (moves) selected elements by the given offset.
References ug::CollectVerticesTouchingSelection(), ug::VecAdd(), and ug::VecCopy().