ug4: Lua Utility Scripts
Lua Utility Scripts
Scripts
Modules
common Utility
Domain Discretization Utility
functions to create DomainDiscs using a string disc-type identifier
Domain Distribution Utility
creates partition maps of different structure and provides some easy to use domain distribution methods.
GNUPlot Utility
Load Balancing Utility
Parses parameters related to load-balancing and creates a load-balancer accordingly.
Metaprogramming Utility
Meta Programming Functions for Lua Scripts.
Lua Utility Scripts
Helpers for profiling output.
Solver Util
Table based solver creation.
Statistics Utility
Table Utility
Tests Utility
Timestep Utility
UserData Utility
Files
file scaling_analyzer.lua
lua script to compare profiling outputs from different runs of one problem
Functions
function AssertPluginsLoaded (pluginNamesList)
function bool2string (boolB)
function util FileDummy close () end
function util DirSeperator ()
function FillSpaces (str, minSize)
function FindEntry (entryList, name, guessInd)
function formatf (s,...)
function fsize (file)
function util GetBaseName (filename)
function util GetGridPath ()
function io open_ALL (filename, model)
function io open_ONE (filename, model, rootNode)
function pairsSortedByKeys (t, f)
function util ParallelMaxMinAvg (s)
function printf (s,...)
function util FileDummy read (...) error("io.open_0 does not support read.") end
function RequiredPlugins (pluginNamesList)
function util safe_io_open (filename, model)
function util FileDummy write (...) end
function writeln (...)
Detailed Description
General Lua utility scripts for ug4.
Function Documentation
AssertPluginsLoaded()
function AssertPluginsLoaded (pluginNamesList)
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :164-166
function AssertPluginsLoaded(pluginNamesList)
  RequiredPlugins(pluginNamesList)
end
bool2string()
function bool2string (boolB)
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :136-142
function bool2string(boolB)
  if boolB then
    return "true"
  else
    return "false"
  end
end
close()
function util FileDummy close ()
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :196
function util.FileDummy.close() end
Referenced by ug::bridge::RegisterDegeneratedLayerManager().
DirSeperator()
function util DirSeperator ()
perhaps move this to bridge, and use function
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :68-70
function util.DirSeperator()
  if GetOperatingSystem() == "cygwin" then return "\\" else return "/" end
end
FillSpaces()
function FillSpaces (str , minSize)
location: /home/sreiter/ug4-docugen/ugcore/scripts/tools / scaling_analyzer.lua :79-85
function FillSpaces(str, minSize)
  local strLen = string.len(str)
  if strLen < minSize then
    return str .. string.rep(" ", minSize - strLen)
  end
  return str
end
FindEntry()
function FindEntry (entryList , name , guessInd)
location: /home/sreiter/ug4-docugen/ugcore/scripts/tools / scaling_analyzer.lua :92-140
formatf()
function formatf (s , ...)
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :117-119
function formatf(s, ...)
  return s:format(...)
end
fsize()
function fsize (file)
fsize returns the filesize of a file (http://www.lua.org/pil/21.3.html)
Parameters
file
Returns
filesize
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :129-134
function fsize (file)
  local current = file:seek()      -- get current position
    local size = file:seek("end")    -- get file size
    file:seek("set", current)        -- restore position
    return size
end
GetBaseName()
function util GetBaseName (filename)
perhaps move this to file_util*
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :73-81
function util.GetBaseName(filename)
  for i=1,string.len(filename) do
    if string.char(string.byte(filename, i)) == util.DirSeperator() then
      return string.sub(filename, i+1)
    end
  end
  return filename
end
GetGridPath()
function util GetGridPath ()
returns the standard path at which grids are stored
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :63-65
function util.GetGridPath()
  return ug_get_data_path().."/grids/"
end
open_ALL()
function io open_ALL (filename , model)
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :174-177
function io.open_ALL(filename, model)
  ug_assert(filename ~= nil)
  return util._original_io_open(filename, model)
end
open_ONE()
function io open_ONE (filename , model , rootNode)
io.open_ONE opens the file on exactly one core all other cores get dummy file objects (FileDummy)
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :199-206
function io.open_ONE(filename, model, rootNode)
  if rootNode == nil then rootNode = 0 end
  if ProcRank() == rootNode then
    return util._original_io_open(filename, model)
  else
    return util.FileDummy
  end
end
pairsSortedByKeys()
function pairsSortedByKeys (t , f)
pairsSortedByKeys the normal pairs(table) function returns elements unsorted this function goes through elements sorted. see http://www.lua.org/pil/19.3.html use it like e.g. for name,arg in pairsSortedByKeys(util.args) do f can be nil (= std sort)
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :90-104
function pairsSortedByKeys (t, f)
    local a = {}
    for n in pairs(t) do
        table.insert(a, n)
    end
    table.sort(a, f)
    local i = 0      -- iterator variable
    local function iter()   -- iterator function
      i = i + 1
        if a[i] == nil then return nil
        else return a[i], t[a[i]]
        end
    end
  return iter
end
ParallelMaxMinAvg()
function util ParallelMaxMinAvg (s)
ParallelMaxMinAvg prints "min: (minimum), max: (maximum), avg: (average)" for parallel different integers s
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :212-214
function util.ParallelMaxMinAvg(s)
  return "min: "..ParallelMin(s)..", max: "..ParallelMax(s)..", avg: ".. ParallelSum(s)/NumProcs()
end
printf()
function printf (s , ...)
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :121-123
function printf(s,...)
  print(formatf(...))
end
Referenced by ug::bridge::CompletionFunction(), ug::bridge::GetGlobalFunctionInfo(), ug::bridge::GetMemberFunctionInfo(), and ug::CUDAManager::init().
read()
function util FileDummy read (...)
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :195
function util.FileDummy.read(...) error("io.open_0 does not support read.") end
Referenced by ug::LuaUserFunction< TData, dim, TDataIn >::eval_deriv(), ug::LuaUserFunction< TData, dim, TDataIn >::eval_value(), ug::LuaUserData< TData, dim, TRet >::evaluate(), ug::LuaUserFunction< TData, dim, TDataIn >::operator()(), and ug::LuaFunction< number, number >::operator()().
RequiredPlugins()
function RequiredPlugins (pluginNamesList)
Parameters
pluginNamesList a list like {"amg", "d3f"} of plugins to check
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :147-162
function RequiredPlugins(pluginNamesList)
  local notLoadedNames = ""
  local cmakePluginString = ""
  for i,v in pairs(pluginNamesList) do
    if PluginLoaded(v) == false then
      notLoadedNames=notLoadedNames..v.." "
      cmakePluginString = cmakePluginString.." -D"..v.."=ON"
    end
  end
  if notLoadedNames:len() > 0 then
    print("Plugin(s) needed but not loaded: "..notLoadedNames)
    print("Please use \n   cmake "..cmakePluginString.." ..; make\nin your build directory to add the plugin(s).")
    exit()
  end
end
safe_io_open()
function util safe_io_open (filename , model)
WARNING: Parallel File open is REALLY slow on clusters this function overwrite io.open and prints a warning if you use it on a core which is not 0 to remove this warning
check if you want to open the file on ALL cores if not, use if ProcRank()==0 open, write,close end
if you're really sure you want to do that, use io.open_ALL.
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :185-190
function util.safe_io_open(filename, model)
  if ProcRank() == 1 then
    ug_warning("--- WARNING: opening a file not from proc 0 may harm performance (see util.IOOpen) ! "..util.GetLUAFileAndLine(1).." ---")
  end
  return io.open_ALL(filename, model)
end
write()
function util FileDummy write (...)
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :194
function util.FileDummy.write(...) end
Referenced by pcl::ParallelArchive::create_new_archive(), and pcl::ParallelArchive::~ParallelArchive().
writeln()
function writeln (...)
adds writeln
location: /home/sreiter/ug4-docugen/ugcore/scripts / ug_util.lua :111-114
function writeln(...)
  write(...)
  write("\n")
end