ug4: Domain Discretization Utility
Domain Discretization Utility
Scripts » Lua Utility Scripts
functions to create DomainDiscs using a string disc-type identifier
Functions
function NeumannBoundary (fcts, discType)
function UpwindFV1 (upwindType, upwindParam)
Detailed Description
functions to create DomainDiscs using a string disc-type identifier
Function Documentation
NeumannBoundary()
function NeumannBoundary (fcts , discType)
Returns a NeumannBoundary Element-Disc of the requested type
Returns
Returns the element discreatization (of the Neumann BC)
Parameters
fcts (String) names of symbolic function
discType (String) discretizatin scheme
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / domain_disc_util.lua :42-51
function NeumannBoundary(fcts, discType)
  if discType == nil then discType = "fv1" end
  if    discType == "fv1"  then return NeumannBoundaryFV1(fcts)
  elseif  discType == "fv"   then return NeumannBoundaryFV(fcts)
  elseif  discType == "fe"   then return NeumannBoundaryFE(fcts)
  else
    print("NeumannBoundary: no disc type '"..discType.."' available. Aborting")
    exit();
  end
end
References create(), for(), if(), print(), and UpwindFV1().
UpwindFV1()
function UpwindFV1 (upwindType , upwindParam)
Returns a IConvectionShape class object of an upwind method (for FV1 discretization)
Returns
Returns the object of the upwind method
Parameters
upwindType type of the upwind as string
upwindParam object-specific parameters
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / domain_disc_util.lua :57-72
function UpwindFV1(upwindType, upwindParam)
  if upwindType == nil then upwindType = "partial" end
  if    upwindType == "no" then return NoUpwind()
  elseif  upwindType == "full" then return FullUpwind ()
  elseif  upwindType == "weighted" then
    local upwind = WeightedUpwind ()
    if upwindParam ~= nil then
      upwind:set_weight(upwindParam)
    end
    return upwind
  elseif  upwindType == "partial" then return PartialUpwind ()
  else
    print("UpwindFV1: no upwind type '"..upwindType.."' available. Aborting")
    exit();
  end
end
Referenced by NeumannBoundary().