ug4: Domain
Domain
lib_discretization
Classes
class ug::Domain< d, TGrid, TSubsetHandler >
class ug::DomainInfo
Describes the contents of a domain.
class ug::IDomain< TGrid, TSubsetHandler >
describes a physical domain
Typedefs
typedef IDomain< TGrid, TSubsetHandler > ug::Domain< d, TGrid, TSubsetHandler >::base_type
base type
typedef Domain< 1, MultiGrid, MGSubsetHandler > ug::Domain1d
typedef Domain< 2, MultiGrid, MGSubsetHandler > ug::Domain2d
typedef Domain< 3, MultiGrid, MGSubsetHandler > ug::Domain3d
typedef TGrid ug::IDomain< TGrid, TSubsetHandler >::grid_type
Grid type.
typedef base_type::grid_type ug::Domain< d, TGrid, TSubsetHandler >::grid_type
Grid type.
typedef unsigned long long ug::DomainInfo::int_t
typedef Grid::VertexAttachmentAccessor< position_attachment_type > ug::Domain< d, TGrid, TSubsetHandler >::position_accessor_type
Type of Accessor to the Position Data Attachment.
typedef Attachment< position_type > ug::Domain< d, TGrid, TSubsetHandler >::position_attachment_type
Type of Position Attachment.
typedef MathVector< dim > ug::Domain< d, TGrid, TSubsetHandler >::position_type
Type of position coordinates.
typedef TSubsetHandler ug::IDomain< TGrid, TSubsetHandler >::subset_handler_type
Subset Handler type.
typedef base_type::subset_handler_type ug::Domain< d, TGrid, TSubsetHandler >::subset_handler_type
Subset Handler type.
Functions
SmartPtr< TSubsetHandler > ug::IDomain< TGrid, TSubsetHandler >::additional_subset_handler (std::string name)
returns an additional subset handler Subset Handler
const ConstSmartPtr< TSubsetHandler > ug::IDomain< TGrid, TSubsetHandler >::additional_subset_handler (std::string name) const
const access to Subset Handler
std::vector< std::string > ug::IDomain< TGrid, TSubsetHandler >::additional_subset_handler_names () const
returns a list with the names of additional subset handlers
SPRefinementProjector ug::IDomain< TGrid, TSubsetHandler >::broadcast_refinement_projector (int rootProc, pcl::ProcessCommunicator &procCom, SPIGeometry3d geometry, SPRefinementProjector projector=SPNULL)
helper method to broadcast ug::RefinementProjectors to different processes
template<typename TDomain >
void ug::CollectCornerCoordinates (int base_object_id, std::vector< typename TDomain::position_type > &vCornerCoordsOut, GridObject &elem, const TDomain &domain, bool clearContainer)
returns the corner coordinates of a geometric object
template<typename TElem , typename TAAPos >
void ug::CollectCornerCoordinates (std::vector< typename TAAPos::ValueType > &vCornerCoordsOut, const TElem &elem, const TAAPos &aaPos, bool clearContainer=true)
returns the corner coordinates of a geometric object
template<typename TElem , typename TDomain >
void ug::CollectCornerCoordinates (std::vector< typename TDomain::position_type > &vCornerCoordsOut, const TElem &elem, const TDomain &domain, bool clearContainer=true)
returns the corner coordinates of a geometric object
template<class TElem >
void ug::IDomain< TGrid, TSubsetHandler >::count_ghosts (std::vector< DomainInfo::int_t > &numGhostsOnLvlOut)
template<class TElem >
size_t ug::IDomain< TGrid, TSubsetHandler >::count_local_unique_surface_elements ()
counts local surface elements which are not ghosts or h-slaves
bool ug::IDomain< TGrid, TSubsetHandler >::create_additional_subset_handler (std::string name)
creates an additional subset-handler with the given name
SPRefinementProjector ug::IDomain< TGrid, TSubsetHandler >::deserialize_projector (BinaryBuffer &buf)
DistributedGridManager * ug::IDomain< TGrid, TSubsetHandler >::distributed_grid_manager ()
returns Distributed Grid Manager
ug::Domain< d, TGrid, TSubsetHandler >::Domain (bool isAdaptive=true)
Default constructor.
const DomainInfo & ug::IDomain< TGrid, TSubsetHandler >::domain_info () const
returns information on the current domain
int ug::DomainInfo::element_type () const
template<typename TElem , typename TDomain >
number ug::ElementDiameter (const TElem &elem, TDomain &domain)
returns the maximal distance between to element vertices
template<typename TElem , typename TDomain >
number ug::ElementDiameterSq (const TElem &elem, TDomain &domain)
returns the maximal squared distance between to element vertices
template<typename TElem , typename TPosition >
number ug::ElementSize (const TElem &elem, const Grid::VertexAttachmentAccessor< Attachment< TPosition > > &aaPos)
returns the size of a geometric object
template<typename TElem , typename TDomain >
number ug::ElementSize (const TElem &elem, const TDomain &domain)
returns the size of a geometric object
bool ug::IDomain< TGrid, TSubsetHandler >::empty () const
returns whether the associated grid is empty
virtual SPIGeometry3d ug::Domain< d, TGrid, TSubsetHandler >::geometry3d () const
returns the geometry of the domain
virtual SPIGeometry3d ug::IDomain< TGrid, TSubsetHandler >::geometry3d () const =0
returns the geometry of the domain
virtual int ug::Domain< d, TGrid, TSubsetHandler >::get_dim () const
World Dimension.
virtual int ug::IDomain< TGrid, TSubsetHandler >::get_dim () const =0
World Dimension.
SmartPtr< TGrid > ug::IDomain< TGrid, TSubsetHandler >::grid ()
returns Grid
const ConstSmartPtr< TGrid > ug::IDomain< TGrid, TSubsetHandler >::grid () const
const access to Grid
void ug::IDomain< TGrid, TSubsetHandler >::grid_adaption_callback (const GridMessage_Adaption &msg)
void ug::IDomain< TGrid, TSubsetHandler >::grid_creation_callback (const GridMessage_Creation &msg)
Called when a domain has been loaded and during domain distribution.
void ug::IDomain< TGrid, TSubsetHandler >::grid_distribution_callback (const GridMessage_Distribution &msg)
ug::IDomain< TGrid, TSubsetHandler >::IDomain (bool isAdaptive=true)
Default constructor.
bool ug::IDomain< TGrid, TSubsetHandler >::is_adaptive () const
returns whether the domain may be used for adaptive refinement
bool ug::IDomain< TGrid, TSubsetHandler >::is_parallel ()
returns whether the domain can be used for parallel computations
size_t ug::DomainInfo::max_num_local_elements_on_level (size_t lvl) const
returns the maximum number of elements a process has on a given leven (excluding ghosts)
template<typename TDomain >
number ug::MaxElementDiameter (TDomain &domain, int level)
returns the maximal diameter of all elements between iterBegin and iterEnd.
SPMessageHub ug::IDomain< TGrid, TSubsetHandler >::message_hub ()
returns the message hub of the grid
size_t ug::DomainInfo::min_num_local_elements_on_level (size_t lvl) const
returns the minimum number of elements a process has on a given leven (excluding ghosts)
template<typename TDomain >
number ug::MinElementDiameter (TDomain &domain, int level)
returns the minimal diameter of all elements between iterBegin and iterEnd.
size_t ug::DomainInfo::num_elements () const
size_t ug::DomainInfo::num_elements_on_level (size_t lvl) const
returns the global number of elements on the given level (excluding ghosts...)
size_t ug::DomainInfo::num_levels () const
size_t ug::DomainInfo::num_local_elements_on_level (size_t lvl) const
returns the local number of elements on the given level (excluding ghosts...)
size_t ug::DomainInfo::num_local_ghosts_on_level (size_t lvl) const
returns the local number of ghosts on the given level
size_t ug::DomainInfo::num_subsets () const
size_t ug::DomainInfo::num_surface_elements () const
returns the global number of surface elements (elements without children)
position_accessor_type & ug::Domain< d, TGrid, TSubsetHandler >::position_accessor ()
get Position Accessor
const position_accessor_type & ug::Domain< d, TGrid, TSubsetHandler >::position_accessor () const
const access to Position Accessor
position_attachment_type & ug::Domain< d, TGrid, TSubsetHandler >::position_attachment ()
returns Position Attachment
const position_attachment_type & ug::Domain< d, TGrid, TSubsetHandler >::position_attachment () const
const access to Position Attachment
SPRefinementProjector ug::IDomain< TGrid, TSubsetHandler >::refinement_projector () const
returns the domain's ug::RefinementProjector. The pointer may be invalid.
template<typename TDomain >
void ug::SaveDomain (TDomain &domain, const char *filename)
Saves the domain to a grid-file.
void ug::IDomain< TGrid, TSubsetHandler >::serialize_projector (BinaryBuffer &bufOut, SPRefinementProjector proj)
void ug::DomainInfo::set_info (GridBaseObjectId elemType, const std::vector< int_t > &numElems, const std::vector< int_t > &numLocalElems, const std::vector< int_t > &minNumLocalElems, const std::vector< int_t > &maxNumLocalElems, const std::vector< int_t > &numLocalGhosts, const std::vector< int_t > &subsetDims, int_t numSurfElems)
void ug::IDomain< TGrid, TSubsetHandler >::set_refinement_projector (SPRefinementProjector proj)
sets the ug::RefinementProjector which can be used by refiners during refinement
size_t ug::DomainInfo::subset_dim (int si) const
SmartPtr< TSubsetHandler > ug::IDomain< TGrid, TSubsetHandler >::subset_handler ()
returns Subset Handler
const ConstSmartPtr< TSubsetHandler > ug::IDomain< TGrid, TSubsetHandler >::subset_handler () const
const access to Subset Handler
std::string ug::DomainInfo::to_string () const
void ug::IDomain< TGrid, TSubsetHandler >::update_domain_info ()
updates the internal domain-info object.
void ug::IDomain< TGrid, TSubsetHandler >::update_subset_infos (int rootProc)
updates and broadcasts subset names and dimensions from the given rootProc to all other processes.
virtual ug::Domain< d, TGrid, TSubsetHandler >::~Domain ()
virtual ug::IDomain< TGrid, TSubsetHandler >::~IDomain ()
Destructor.
Variables
static const int ug::Domain< d, TGrid, TSubsetHandler >::dim = d
World dimension.
position_accessor_type ug::Domain< d, TGrid, TSubsetHandler >::m_aaPos
Accessor.
bool ug::IDomain< TGrid, TSubsetHandler >::m_adaptionIsActive
std::map< std::string, SmartPtr< TSubsetHandler > > ug::IDomain< TGrid, TSubsetHandler >::m_additionalSH
additional subset handlers
position_attachment_type ug::Domain< d, TGrid, TSubsetHandler >::m_aPos
Position Attachment.
DomainInfo ug::IDomain< TGrid, TSubsetHandler >::m_domainInfo
GridBaseObjectId ug::DomainInfo::m_elementType
SPIGeometry3d ug::Domain< d, TGrid, TSubsetHandler >::m_geometry3d
bool ug::IDomain< TGrid, TSubsetHandler >::m_isAdaptive
std::vector< int_t > ug::DomainInfo::m_maxNumLocalElems
std::vector< int_t > ug::DomainInfo::m_minNumLocalElems
std::vector< int_t > ug::DomainInfo::m_numElems
std::vector< int_t > ug::DomainInfo::m_numLocalElems
local number of elements excluding ghosts.
std::vector< int_t > ug::DomainInfo::m_numLocalGhosts
int_t ug::DomainInfo::m_numSurfElems
SPRefinementProjector ug::IDomain< TGrid, TSubsetHandler >::m_refinementProjector
SmartPtr< TGrid > ug::IDomain< TGrid, TSubsetHandler >::m_spGrid
Grid.
MessageHub::SPCallbackId ug::IDomain< TGrid, TSubsetHandler >::m_spGridAdaptionCallbackID
MessageHub::SPCallbackId ug::IDomain< TGrid, TSubsetHandler >::m_spGridCreationCallbackID
MessageHub::SPCallbackId ug::IDomain< TGrid, TSubsetHandler >::m_spGridDistributionCallbackID
SmartPtr< TSubsetHandler > ug::IDomain< TGrid, TSubsetHandler >::m_spSH
Subset Handler.
std::vector< int_t > ug::DomainInfo::m_subsetDims
template<typename TDomain >
void ug::LoadDomain (TDomain &domain, const char *filename)
Loads a domain from a grid-file.
template<typename TDomain >
void ug::LoadDomain (TDomain &domain, const char *filename, int procId)
Loads a domain from a grid-file.
Detailed Description
Domain
Typedef Documentation
base_type
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> typedef IDomain<TGrid, TSubsetHandler> ug::Domain< d, TGrid, TSubsetHandler >::base_type private
base type
Domain1d
typedef Domain<1, MultiGrid, MGSubsetHandler> ug::Domain1d
Domain2d
typedef Domain<2, MultiGrid, MGSubsetHandler> ug::Domain2d
Domain3d
typedef Domain<3, MultiGrid, MGSubsetHandler> ug::Domain3d
grid_type [1/2]
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> typedef TGrid ug::IDomain< TGrid, TSubsetHandler >::grid_type
Grid type.
grid_type [2/2]
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> typedef base_type::grid_type ug::Domain< d, TGrid, TSubsetHandler >::grid_type
Grid type.
int_t
typedef unsigned long long ug::DomainInfo::int_t
position_accessor_type
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> typedef Grid::VertexAttachmentAccessor<position_attachment_type> ug::Domain< d, TGrid, TSubsetHandler >::position_accessor_type
Type of Accessor to the Position Data Attachment.
position_attachment_type
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> typedef Attachment<position_type> ug::Domain< d, TGrid, TSubsetHandler >::position_attachment_type
Type of Position Attachment.
position_type
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> typedef MathVector<dim> ug::Domain< d, TGrid, TSubsetHandler >::position_type
Type of position coordinates.
subset_handler_type [1/2]
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> typedef TSubsetHandler ug::IDomain< TGrid, TSubsetHandler >::subset_handler_type
Subset Handler type.
subset_handler_type [2/2]
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> typedef base_type::subset_handler_type ug::Domain< d, TGrid, TSubsetHandler >::subset_handler_type
Subset Handler type.
Function Documentation
additional_subset_handler() [1/2]
template<typename TGrid , typename TSubsetHandler > SmartPtr< TSubsetHandler > ug::IDomain< TGrid, TSubsetHandler >::additional_subset_handler (std::string name)
returns an additional subset handler Subset Handler
References name, UG_THROW, and SmartPtr< T, FreePolicy >::valid().
additional_subset_handler() [2/2]
template<typename TGrid , typename TSubsetHandler > const ConstSmartPtr< TSubsetHandler > ug::IDomain< TGrid, TSubsetHandler >::additional_subset_handler (std::string name) const
const access to Subset Handler
References name, UG_THROW, and SmartPtr< T, FreePolicy >::valid().
additional_subset_handler_names()
template<typename TGrid , typename TSubsetHandler > std::vector< std::string > ug::IDomain< TGrid, TSubsetHandler >::additional_subset_handler_names
returns a list with the names of additional subset handlers
broadcast_refinement_projector()
template<typename TGrid , typename TSubsetHandler > SPRefinementProjector ug::IDomain< TGrid, TSubsetHandler >::broadcast_refinement_projector (int rootProc, pcl::ProcessCommunicator & procCom, SPIGeometry3d geometry, SPRefinementProjector projector = SPNULL) protected
helper method to broadcast ug::RefinementProjectors to different processes
References pcl::ProcessCommunicator::broadcast(), ug::ProjectionHandler::default_projector(), ug::Deserialize(), SmartPtr< T, FreePolicy >::get(), boost::get(), make_sp(), ug::ProjectionHandler::num_projectors(), pcl::ProcRank(), ug::ProjectionHandler::projector(), ug::Serialize(), ug::ProjectionHandler::set_default_projector(), ug::ProjectionHandler::set_projector(), SPNULL, ug::ProjectionHandler::subset_handler(), UG_COND_THROW, UG_THROW, and SmartPtr< T, FreePolicy >::valid().
CollectCornerCoordinates() [1/3]
template<typename TDomain > void ug::CollectCornerCoordinates (int base_object_id, std::vector< typename TDomain::position_type > & vCornerCoordsOut, GridObject & elem, const TDomain & domain, bool clearContainer)
returns the corner coordinates of a geometric object
Returns the corner coordinates for a given geometric object in a vector
This function calls CollectCornerCoordinates based on the base object id
Parameters
[out] vCornerCoordsOut
[in] base_object_id
[in] elem
[in] domain
[in] clearContainer
References ug::EDGE, ug::FACE, UG_THROW, ug::VERTEX, and ug::VOLUME.
CollectCornerCoordinates() [2/3]
template<typename TElem , typename TAAPos > void ug::CollectCornerCoordinates (std::vector< typename TAAPos::ValueType > & vCornerCoordsOut, const TElem & elem, const TAAPos & aaPos, bool clearContainer = true)
returns the corner coordinates of a geometric object
Returns the corner coordinated of a geometric object in a vector
This function collects the corner coordinates for a given geometric object in the order prescribed by the reference elements
Parameters
[out] vCornerCoordsOut vector of corner coordinates
[in] elem Geometric Object
[in] aaPos AttachmentAccessor for Positions
[in] clearContainer empty container before filling
Referenced by ug::ActiveSet< TDomain, TAlgebra >::active_index_elem(), ug::DirichletBoundary< TDomain, TAlgebra >::adjust_error(), ug::ObstacleInNormalDir< TDomain, TAlgebra >::adjust_sol_and_cor_elem(), ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::calc_error(), ug::ActiveSet< TDomain, TAlgebra >::check_conv_elem(), ug::CheckDoFElem(), ug::CollectCornerCoordinates(), ug::ComputeGradientCrouzeixRaviart(), ug::ComputeGradientLagrange1(), ug::ComputeGradientPiecewiseConstant(), ug::ConstructGridOfSCV(), ug::ConstructGridOfSCVF(), ug::DoFPosition(), ug::ElementSize(), ug::GradientEvaluator_LagrangeP1< TFunction >::evaluate(), ug::GlobalGridFunctionGradientData< TGridFunction >::evaluate(), ug::GlobalGridFunctionNumberData< TGridFunction, elemDim >::evaluate(), ug::L2DistIntegrand< TGridFunction >::evaluate(), ug::H1SemiDistIntegrand< TGridFunction >::evaluate(), ug::H1EnergyDistIntegrand< TGridFunction >::evaluate(), ug::H1DistIntegrand< TGridFunction >::evaluate(), ug::UserDataDistIntegrandSq< TData, TGridFunction >::evaluate(), ug::OutNormCmp< TDomain >::evaluate(), ug::bridge::Evaluate::NumberValuedUserDataEvaluator< TDomain, TAlgebra >::evaluateOnThisProcess(), ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::evaluateOnThisProcess(), ug::bridge::Evaluate::VectorValuedUserDataEvaluator< TDomain, TAlgebra >::evaluateOnThisProcessNeighbouring(), ug::InnerDoFPosition(), ug::IntegralNormalComponentOnManifoldGeneral(), ug::IntegralNormalComponentOnManifoldUsingFV1Geom(), ug::Integrate(), ug::IntegrateNormalComponentOnManifold(), ug::IntegrateNormalGradientOnManifold(), ug::InterpolateOnDiffElements(), ug::ActiveSet< TDomain, TAlgebra >::lagrange_mat_inv_elem(), ug::MaxErrorOnElements(), ug::CrouzeixRaviartElemTransfer< TDomain >::prolongate(), ug::StdLagrangeElemTransfer< TDomain >::prolongate(), ug::ProlongateElemwise(), ug::RestrictElemwise(), ug::ShapesAtGlobalPosition(), ug::SideAndElemErrEstData< TDomain >::summarize_err_est_data(), ug::VTKOutput< TDim >::write_cell_data_elementwise(), and ug::VTKOutput< TDim >::write_nodal_data_elementwise().
CollectCornerCoordinates() [3/3]
template<typename TElem , typename TDomain > void ug::CollectCornerCoordinates (std::vector< typename TDomain::position_type > & vCornerCoordsOut, const TElem & elem, const TDomain & domain, bool clearContainer = true)
returns the corner coordinates of a geometric object
Returns the corner coordinated of a geometric object in a vector
This function collects the corner coordinates for a given geometric object in the order prescribed by the reference elements
Parameters
[out] vCornerCoordsOut vector of corner coordinates
[in] elem Geometric Object
[in] domain Domain
[in] clearContainer empty container before filling
References ug::CollectCornerCoordinates().
count_ghosts()
template<typename TGrid , typename TSubsetHandler > template<class TElem > void ug::IDomain< TGrid, TSubsetHandler >::count_ghosts (std::vector< DomainInfo::int_t > & numGhostsOnLvlOut) protected
make sure that elements of the given type are contained in at most one vmaster interface. This is always the case for highest dimensional elements.
References ug::GridLayoutMap::clear(), ug::GridLayoutMap::get_layout(), ug::DistributedGridManager::grid_layout_map(), ug::GridLayoutMap::has_layout(), ug::INT_V_MASTER, and ug::DistributedGridManager::is_ghost().
count_local_unique_surface_elements()
template<typename TGrid , typename TSubsetHandler > template<class TElem > size_t ug::IDomain< TGrid, TSubsetHandler >::count_local_unique_surface_elements protected
counts local surface elements which are not ghosts or h-slaves
References ug::DistributedGridManager::contains_status(), ug::ES_H_SLAVE, and ug::DistributedGridManager::is_ghost().
create_additional_subset_handler()
template<typename TGrid , typename TSubsetHandler > bool ug::IDomain< TGrid, TSubsetHandler >::create_additional_subset_handler (std::string name)
creates an additional subset-handler with the given name
If this subset-handler is created before the domain is loaded from a file, the contents of the handler will be filled with the contents of the file's subset-handler-node with the same name.
References name.
deserialize_projector()
template<typename TGrid , typename TSubsetHandler > SPRefinementProjector ug::IDomain< TGrid, TSubsetHandler >::deserialize_projector (BinaryBuffer & buf) protected
References ug::Factory< TBase, TPairSeq >::create(), ug::Deserialize(), and name.
distributed_grid_manager()
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> DistributedGridManager* ug::IDomain< TGrid, TSubsetHandler >::distributed_grid_manager () inline
returns Distributed Grid Manager
References ug::IDomain< TGrid, TSubsetHandler >::m_spGrid.
Domain()
template<int d, typename TGrid , typename TSubsetHandler > ug::Domain< d, TGrid, TSubsetHandler >::Domain (bool isAdaptive = true)
Default constructor.
creates an empty domain. Grid and Subset Handler are set up. The Distributed Grid Manager is set in the parallel case.
Parameters
[in] options Grid Options (optional)
References ug::Grid::AttachmentAccessor< TElem, TAttachment >::access(), ug::Domain< d, TGrid, TSubsetHandler >::dim, ug::IDomain< MultiGrid, MGSubsetHandler >::grid(), ug::GRIDOPT_AUTOGENERATE_SIDES, ug::Domain< d, TGrid, TSubsetHandler >::m_aaPos, ug::Domain< d, TGrid, TSubsetHandler >::m_aPos, ug::Domain< d, TGrid, TSubsetHandler >::m_geometry3d, ug::IDomain< MultiGrid, MGSubsetHandler >::m_refinementProjector, make_sp(), ug::MakeGeometry3d(), ug::VRTOPT_STORE_ASSOCIATED_EDGES, ug::VRTOPT_STORE_ASSOCIATED_FACES, and ug::VRTOPT_STORE_ASSOCIATED_VOLUMES.
domain_info()
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> const DomainInfo& ug::IDomain< TGrid, TSubsetHandler >::domain_info () const inline
returns information on the current domain
In a parallel environment, this information relates to the global (distributed) domain.
References ug::IDomain< TGrid, TSubsetHandler >::m_domainInfo.
element_type()
int ug::DomainInfo::element_type () const inline
References ug::DomainInfo::m_elementType.
ElementDiameter()
template<typename TElem , typename TDomain > number ug::ElementDiameter (const TElem & elem, TDomain & domain)
returns the maximal distance between to element vertices
Referenced by ug::ElementDiameter(), and ug::EvaluateGradientJump_SideIntegral().
ElementDiameterSq()
template<typename TElem , typename TDomain > number ug::ElementDiameterSq (const TElem & elem, TDomain & domain)
returns the maximal squared distance between to element vertices
Referenced by ug::ElementDiameter(), ug::ElementDiameterSq(), ug::EvaluateResidualErrorP1(), ug::MaxElementDiameter(), and ug::MinElementDiameter().
ElementSize() [1/2]
template<typename TElem , typename TPosition > number ug::ElementSize (const TElem & elem, const Grid::VertexAttachmentAccessor< Attachment< TPosition > > & aaPos)
returns the size of a geometric object
Returns the size of a geometric object
This function returns the size of a geometric object.
Parameters
[in] elem Geometric Object
[in] aaPos AttachmentAccessor for Positions
Returns
number Size of Element
References ug::CollectCornerCoordinates(), and dim.
ElementSize() [2/2]
template<typename TElem , typename TDomain > number ug::ElementSize (const TElem & elem, const TDomain & domain)
returns the size of a geometric object
Returns the size of a geometric object
This function returns the size of a geometric object.
Parameters
[in] elem Geometric Object
[in] domain Domain
Returns
number Size of Element
References ug::ElementSize().
empty()
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> bool ug::IDomain< TGrid, TSubsetHandler >::empty () const inline
returns whether the associated grid is empty
Note that one vertex is enough to consider the grid as non-empty.
References ug::IDomain< TGrid, TSubsetHandler >::m_spGrid.
geometry3d() [1/2]
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> virtual SPIGeometry3d ug::Domain< d, TGrid, TSubsetHandler >::geometry3d () const inline virtual
returns the geometry of the domain
Implements ug::IDomain< MultiGrid, MGSubsetHandler >.
References ug::Domain< d, TGrid, TSubsetHandler >::m_geometry3d.
geometry3d() [2/2]
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> virtual SPIGeometry3d ug::IDomain< TGrid, TSubsetHandler >::geometry3d () const pure virtual
returns the geometry of the domain
Implemented in ug::Domain< d, TGrid, TSubsetHandler >, and ug::Domain< dim, ug::MultiGrid, ug::MultiGridSubsetHandler >.
get_dim() [1/2]
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> virtual int ug::Domain< d, TGrid, TSubsetHandler >::get_dim () const inline virtual
World Dimension.
Implements ug::IDomain< MultiGrid, MGSubsetHandler >.
References ug::Domain< d, TGrid, TSubsetHandler >::dim.
get_dim() [2/2]
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> virtual int ug::IDomain< TGrid, TSubsetHandler >::get_dim () const pure virtual
World Dimension.
Implemented in ug::Domain< d, TGrid, TSubsetHandler >, and ug::Domain< dim, ug::MultiGrid, ug::MultiGridSubsetHandler >.
grid() [1/2]
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> SmartPtr<TGrid> ug::IDomain< TGrid, TSubsetHandler >::grid () inline
returns Grid
References ug::IDomain< TGrid, TSubsetHandler >::m_spGrid.
Referenced by ug::VTKOutput< TDim >::print().
grid() [2/2]
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> const ConstSmartPtr<TGrid> ug::IDomain< TGrid, TSubsetHandler >::grid () const inline
const access to Grid
References ug::IDomain< TGrid, TSubsetHandler >::m_spGrid.
grid_adaption_callback()
template<typename TGrid , typename TSubsetHandler > void ug::IDomain< TGrid, TSubsetHandler >::grid_adaption_callback (const GridMessage_Adaption & msg) inline protected
this callback is called by the message hub, when a grid adaption has been performed. It will call all necessary actions in order to keep the grid correct for computations.
References ug::GridMessage_Adaption::adaption_begins(), ug::GridMessage_Adaption::adaption_ends(), and UG_THROW.
grid_creation_callback()
template<typename TGrid , typename TSubsetHandler > void ug::IDomain< TGrid, TSubsetHandler >::grid_creation_callback (const GridMessage_Creation & msg) inline protected
Called when a domain has been loaded and during domain distribution.
References ug::GMCT_CREATION_STOPS, ug::GridMessage_Creation::msg(), and ug::GridMessage_Creation::proc_id().
grid_distribution_callback()
template<typename TGrid , typename TSubsetHandler > void ug::IDomain< TGrid, TSubsetHandler >::grid_distribution_callback (const GridMessage_Distribution & msg) inline protected
this callback is called by the message hub, when a grid has been distributed between different processes.
IDomain()
template<typename TGrid , typename TSubsetHandler > ug::IDomain< TGrid, TSubsetHandler >::IDomain (bool isAdaptive = true)
Default constructor.
creates an empty domain. Grid and Subset Handler are set up. The Distributed Grid Manager is set in the parallel case.
Parameters
[in] options Grid Options (optinal)
References ug::IDomain< TGrid, TSubsetHandler >::m_spGrid, ug::IDomain< TGrid, TSubsetHandler >::m_spGridAdaptionCallbackID, ug::IDomain< TGrid, TSubsetHandler >::m_spGridCreationCallbackID, ug::IDomain< TGrid, TSubsetHandler >::m_spGridDistributionCallbackID, and ug::IDomain< TGrid, TSubsetHandler >::message_hub().
is_adaptive()
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> bool ug::IDomain< TGrid, TSubsetHandler >::is_adaptive () const inline
returns whether the domain may be used for adaptive refinement
References ug::IDomain< TGrid, TSubsetHandler >::m_isAdaptive.
is_parallel()
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> bool ug::IDomain< TGrid, TSubsetHandler >::is_parallel () inline
returns whether the domain can be used for parallel computations
If ug was build with support for parallelism, this method will always return true and always false, if ug was build for serial environments.
References ug::IDomain< TGrid, TSubsetHandler >::m_spGrid.
LoadDomain() [1/2]
template<typename TDomain > void ug::LoadDomain (TDomain & domain, const char * filename)
Loads a domain from a grid-file.
By optionally specifying a procId, you can make sure that the domain is only loaded on one process. Pass -1, if you want to load it on all processes. Note that the procId is only important in parallel environments.
References ug::LoadDomain().
Referenced by ug::LoadAndRefineDomain().
LoadDomain() [2/2]
template<typename TDomain > void ug::LoadDomain (TDomain & domain, const char * filename, int procId)
Loads a domain from a grid-file.
By optionally specifying a procId, you can make sure that the domain is only loaded on one process. Pass -1, if you want to load it on all processes. Note that the procId is only important in parallel environments.
References ug::LoadGridFromFile(), make_sp(), PROFILE_FUNC_GROUP, and UG_THROW.
Referenced by ug::LoadDomain().
max_num_local_elements_on_level()
size_t ug::DomainInfo::max_num_local_elements_on_level (size_t lvl) const inline
returns the maximum number of elements a process has on a given leven (excluding ghosts)
References ug::DomainInfo::m_maxNumLocalElems.
MaxElementDiameter()
template<typename TDomain > number ug::MaxElementDiameter (TDomain & domain, int level)
returns the maximal diameter of all elements between iterBegin and iterEnd.
message_hub()
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> SPMessageHub ug::IDomain< TGrid, TSubsetHandler >::message_hub () inline
returns the message hub of the grid
References ug::IDomain< TGrid, TSubsetHandler >::m_spGrid.
Referenced by ug::IDomain< TGrid, TSubsetHandler >::IDomain().
min_num_local_elements_on_level()
size_t ug::DomainInfo::min_num_local_elements_on_level (size_t lvl) const inline
returns the minimum number of elements a process has on a given leven (excluding ghosts)
References ug::DomainInfo::m_minNumLocalElems.
MinElementDiameter()
template<typename TDomain > number ug::MinElementDiameter (TDomain & domain, int level)
returns the minimal diameter of all elements between iterBegin and iterEnd.
num_elements()
size_t ug::DomainInfo::num_elements () const inline
References ug::DomainInfo::m_numElems.
num_elements_on_level()
size_t ug::DomainInfo::num_elements_on_level (size_t lvl) const inline
returns the global number of elements on the given level (excluding ghosts...)
References ug::DomainInfo::m_numElems.
Referenced by ug::CreateProcessHierarchy().
num_levels()
size_t ug::DomainInfo::num_levels () const inline
References ug::DomainInfo::m_numElems.
Referenced by ug::CreateProcessHierarchy().
num_local_elements_on_level()
size_t ug::DomainInfo::num_local_elements_on_level (size_t lvl) const inline
returns the local number of elements on the given level (excluding ghosts...)
References ug::DomainInfo::m_numLocalElems.
num_local_ghosts_on_level()
size_t ug::DomainInfo::num_local_ghosts_on_level (size_t lvl) const inline
returns the local number of ghosts on the given level
References ug::DomainInfo::m_numLocalGhosts.
num_subsets()
size_t ug::DomainInfo::num_subsets () const inline
References ug::DomainInfo::m_subsetDims.
num_surface_elements()
size_t ug::DomainInfo::num_surface_elements () const inline
returns the global number of surface elements (elements without children)
References ug::DomainInfo::m_numSurfElems.
position_accessor() [1/2]
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> position_accessor_type& ug::Domain< d, TGrid, TSubsetHandler >::position_accessor () inline
get Position Accessor
References ug::Domain< d, TGrid, TSubsetHandler >::m_aaPos.
Referenced by ug::VTKOutput< TDim >::print().
position_accessor() [2/2]
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> const position_accessor_type& ug::Domain< d, TGrid, TSubsetHandler >::position_accessor () const inline
const access to Position Accessor
References ug::Domain< d, TGrid, TSubsetHandler >::m_aaPos.
position_attachment() [1/2]
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> position_attachment_type& ug::Domain< d, TGrid, TSubsetHandler >::position_attachment () inline
returns Position Attachment
References ug::Domain< d, TGrid, TSubsetHandler >::m_aPos.
position_attachment() [2/2]
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> const position_attachment_type& ug::Domain< d, TGrid, TSubsetHandler >::position_attachment () const inline
const access to Position Attachment
References ug::Domain< d, TGrid, TSubsetHandler >::m_aPos.
refinement_projector()
template<typename TGrid , typename TSubsetHandler > SPRefinementProjector ug::IDomain< TGrid, TSubsetHandler >::refinement_projector
returns the domain's ug::RefinementProjector. The pointer may be invalid.
SaveDomain()
template<typename TDomain > void ug::SaveDomain (TDomain & domain, const char * filename)
Saves the domain to a grid-file.
References ug::GridWriterUGX::add_grid(), ug::GridWriterUGX::add_subset_handler(), ug::GetFilenameExtension(), PROFILE_FUNC_GROUP, ug::SaveGridToFile(), UG_THROW, and ug::GridWriterUGX::write_to_file().
serialize_projector()
template<typename TGrid , typename TSubsetHandler > void ug::IDomain< TGrid, TSubsetHandler >::serialize_projector (BinaryBuffer & bufOut, SPRefinementProjector proj) protected
References ug::Factory< TBase, TPairSeq >::class_name(), SmartPtr< T, FreePolicy >::invalid(), and ug::Serialize().
set_info()
void ug::DomainInfo::set_info (GridBaseObjectId elemType, const std::vector< int_t > & numElems, const std::vector< int_t > & numLocalElems, const std::vector< int_t > & minNumLocalElems, const std::vector< int_t > & maxNumLocalElems, const std::vector< int_t > & numLocalGhosts, const std::vector< int_t > & subsetDims, int_t numSurfElems) inline
References ug::DomainInfo::m_elementType, ug::DomainInfo::m_maxNumLocalElems, ug::DomainInfo::m_minNumLocalElems, ug::DomainInfo::m_numElems, ug::DomainInfo::m_numLocalElems, ug::DomainInfo::m_numLocalGhosts, ug::DomainInfo::m_numSurfElems, and ug::DomainInfo::m_subsetDims.
set_refinement_projector()
template<typename TGrid , typename TSubsetHandler > void ug::IDomain< TGrid, TSubsetHandler >::set_refinement_projector (SPRefinementProjector proj)
sets the ug::RefinementProjector which can be used by refiners during refinement
References ug::RefinementProjector::set_geometry(), and SmartPtr< T, FreePolicy >::valid().
subset_dim()
size_t ug::DomainInfo::subset_dim (int si) const inline
References ug::DomainInfo::m_subsetDims.
subset_handler() [1/2]
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> SmartPtr<TSubsetHandler> ug::IDomain< TGrid, TSubsetHandler >::subset_handler () inline
returns Subset Handler
References ug::IDomain< TGrid, TSubsetHandler >::m_spSH.
Referenced by ug::VTKOutput< TDim >::print().
subset_handler() [2/2]
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> const ConstSmartPtr<TSubsetHandler> ug::IDomain< TGrid, TSubsetHandler >::subset_handler () const inline
const access to Subset Handler
References ug::IDomain< TGrid, TSubsetHandler >::m_spSH.
to_string()
std::string ug::DomainInfo::to_string () const
References ug::Table< T >::to_string(), and UG_THROW.
update_domain_info()
template<typename TGrid , typename TSubsetHandler > void ug::IDomain< TGrid, TSubsetHandler >::update_domain_info
updates the internal domain-info object.
This method is called automatically each time the associated grid has changed.
update_subset_infos()
template<typename TGrid , typename TSubsetHandler > void ug::IDomain< TGrid, TSubsetHandler >::update_subset_infos (int rootProc)
updates and broadcasts subset names and dimensions from the given rootProc to all other processes.
References pcl::ProcessCommunicator::broadcast(), ug::Deserialize(), dim, pcl::ProcRank(), PROFILE_FUNC, and ug::Serialize().
~Domain()
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> virtual ug::Domain< d, TGrid, TSubsetHandler >::~Domain () inline virtual
~IDomain()
template<typename TGrid , typename TSubsetHandler > ug::IDomain< TGrid, TSubsetHandler >::~IDomain virtual
Destructor.
Variable Documentation
dim
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> const int ug::Domain< d, TGrid, TSubsetHandler >::dim = d static
World dimension.
Referenced by ug::Domain< d, TGrid, TSubsetHandler >::Domain(), and ug::Domain< d, TGrid, TSubsetHandler >::get_dim().
m_aaPos
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> position_accessor_type ug::Domain< d, TGrid, TSubsetHandler >::m_aaPos protected
Accessor.
Referenced by ug::Domain< d, TGrid, TSubsetHandler >::Domain(), and ug::Domain< d, TGrid, TSubsetHandler >::position_accessor().
m_adaptionIsActive
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> bool ug::IDomain< TGrid, TSubsetHandler >::m_adaptionIsActive protected
m_additionalSH
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> std::map<std::string, SmartPtr<TSubsetHandler> > ug::IDomain< TGrid, TSubsetHandler >::m_additionalSH protected
additional subset handlers
m_aPos
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> position_attachment_type ug::Domain< d, TGrid, TSubsetHandler >::m_aPos protected
Position Attachment.
Referenced by ug::Domain< d, TGrid, TSubsetHandler >::Domain(), and ug::Domain< d, TGrid, TSubsetHandler >::position_attachment().
m_domainInfo
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> DomainInfo ug::IDomain< TGrid, TSubsetHandler >::m_domainInfo protected
Referenced by ug::IDomain< TGrid, TSubsetHandler >::domain_info().
m_elementType
GridBaseObjectId ug::DomainInfo::m_elementType private
Referenced by ug::DomainInfo::element_type(), and ug::DomainInfo::set_info().
m_geometry3d
template<int d, typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> SPIGeometry3d ug::Domain< d, TGrid, TSubsetHandler >::m_geometry3d protected
Referenced by ug::Domain< d, TGrid, TSubsetHandler >::Domain(), and ug::Domain< d, TGrid, TSubsetHandler >::geometry3d().
m_isAdaptive
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> bool ug::IDomain< TGrid, TSubsetHandler >::m_isAdaptive protected
Referenced by ug::IDomain< TGrid, TSubsetHandler >::is_adaptive().
m_maxNumLocalElems
std::vector<int_t> ug::DomainInfo::m_maxNumLocalElems private
Referenced by ug::DomainInfo::max_num_local_elements_on_level(), and ug::DomainInfo::set_info().
m_minNumLocalElems
std::vector<int_t> ug::DomainInfo::m_minNumLocalElems private
Referenced by ug::DomainInfo::min_num_local_elements_on_level(), and ug::DomainInfo::set_info().
m_numElems
std::vector<int_t> ug::DomainInfo::m_numElems private
Referenced by ug::DomainInfo::num_elements(), ug::DomainInfo::num_elements_on_level(), ug::DomainInfo::num_levels(), and ug::DomainInfo::set_info().
m_numLocalElems
std::vector<int_t> ug::DomainInfo::m_numLocalElems private
local number of elements excluding ghosts.
Referenced by ug::DomainInfo::num_local_elements_on_level(), and ug::DomainInfo::set_info().
m_numLocalGhosts
std::vector<int_t> ug::DomainInfo::m_numLocalGhosts private
Referenced by ug::DomainInfo::num_local_ghosts_on_level(), and ug::DomainInfo::set_info().
m_numSurfElems
int_t ug::DomainInfo::m_numSurfElems private
Referenced by ug::DomainInfo::num_surface_elements(), and ug::DomainInfo::set_info().
m_refinementProjector
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> SPRefinementProjector ug::IDomain< TGrid, TSubsetHandler >::m_refinementProjector protected
m_spGrid
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> SmartPtr<TGrid> ug::IDomain< TGrid, TSubsetHandler >::m_spGrid protected
Grid.
Referenced by ug::IDomain< TGrid, TSubsetHandler >::distributed_grid_manager(), ug::IDomain< TGrid, TSubsetHandler >::empty(), ug::IDomain< TGrid, TSubsetHandler >::grid(), ug::IDomain< TGrid, TSubsetHandler >::IDomain(), ug::IDomain< TGrid, TSubsetHandler >::is_parallel(), and ug::IDomain< TGrid, TSubsetHandler >::message_hub().
m_spGridAdaptionCallbackID
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> MessageHub::SPCallbackId ug::IDomain< TGrid, TSubsetHandler >::m_spGridAdaptionCallbackID protected
Referenced by ug::IDomain< TGrid, TSubsetHandler >::IDomain().
m_spGridCreationCallbackID
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> MessageHub::SPCallbackId ug::IDomain< TGrid, TSubsetHandler >::m_spGridCreationCallbackID protected
Referenced by ug::IDomain< TGrid, TSubsetHandler >::IDomain().
m_spGridDistributionCallbackID
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> MessageHub::SPCallbackId ug::IDomain< TGrid, TSubsetHandler >::m_spGridDistributionCallbackID protected
Referenced by ug::IDomain< TGrid, TSubsetHandler >::IDomain().
m_spSH
template<typename TGrid = MultiGrid, typename TSubsetHandler = MGSubsetHandler> SmartPtr<TSubsetHandler> ug::IDomain< TGrid, TSubsetHandler >::m_spSH protected
Subset Handler.
Referenced by ug::IDomain< TGrid, TSubsetHandler >::subset_handler().
m_subsetDims
std::vector<int_t> ug::DomainInfo::m_subsetDims private
Referenced by ug::DomainInfo::num_subsets(), ug::DomainInfo::set_info(), and ug::DomainInfo::subset_dim().