ug4: PCL
PCL
ugbase
the Process Communication Layer
Namespaces
pcl::interface_tags
Interface tags allow to differentiate between interfaces with different features.
pcl::layout_tags
Layout tags allow to differentiate between layouts with different features.
Classes
class pcl::BasicInterface< TType, TContainer, TAlloc >
You may add elements to this interface and iterate over them.
class pcl::DataTypeDirectlySupported
class pcl::DataTypeIndirectlySupported
class pcl::DataTypeTraits< T >
class pcl::DataTypeTraits< char >
class pcl::DataTypeTraits< double >
class pcl::DataTypeTraits< float >
class pcl::DataTypeTraits< int >
class pcl::DataTypeTraits< long >
class pcl::DataTypeTraits< unsigned char >
class pcl::DataTypeTraits< unsigned long >
class pcl::ICommunicationPolicy< TLayout >
specializations are responsible to pack and unpack interface data during communication.
class pcl::IDomainDecompositionInfo
class pcl::InterfaceCommunicator< TLayout >
Performs communication between interfaces on different processes.
class pcl::MultiLevelLayout< TInterface >
the standard multi-level-layout implementation
class pcl::OrderedInterface< TType, TContainer, TAlloc >
You may add elements to this interface and iterate over them.
class pcl::ProcessCommunicator
class pcl::SelectionCommPol< TLayout, TSelectorIn, TSelectorOut >
communicates selection-status of interface elements
class pcl::SingleLevelLayout< TInterface >
the standard single-level-layout implementation
class pcl::StandardDomainDecompositionInfo
struct pcl::type_traits< TType >
associate internally used types with an external typename
Macros
#define DEBUG_TESTLAYOUT(processCommunicator, com, master, slave) TESTLAYOUT(processCommunicator, com, master, slave)
#define DEBUG_TESTLAYOUTS(layout) DEBUG_TESTLAYOUT(layout->proc_comm(), layout->comm(), layout->master(), layout->slave())
#define PCL_DT_BYTE MPI_BYTE
#define PCL_DT_CHAR MPI_CHAR
#define PCL_DT_DOUBLE MPI_DOUBLE
#define PCL_DT_FLOAT MPI_FLOAT
#define PCL_DT_INT MPI_INT
#define PCL_DT_LONG MPI_LONG
#define PCL_DT_LONG_DOUBLE MPI_LONG_DOUBLE
#define PCL_DT_LONG_LONG_INT MPI_LONG_LONG_INT
#define PCL_DT_NULL MPI_DATATYPE_NULL
#define PCL_DT_PACKED MPI_PACKED
#define PCL_DT_SHORT MPI_SHORT
#define PCL_DT_UNSIGNED_CHAR MPI_UNSIGNED_CHAR
#define PCL_DT_UNSIGNED_LONG MPI_UNSIGNED_LONG
#define PCL_DT_UNSIGNED_LONG_LONG MPI_UNSIGNED_LONG_LONG
#define PCL_RO_BAND MPI_BAND
#define PCL_RO_BOR MPI_BOR
#define PCL_RO_BXOR MPI_BXOR
#define PCL_RO_LAND MPI_LAND
#define PCL_RO_LOR MPI_LOR
#define PCL_RO_LXOR MPI_LXOR
#define PCL_RO_MAX MPI_MAX
#define PCL_RO_MAXLOC MPI_MAXLOC
#define PCL_RO_MIN MPI_MIN
#define PCL_RO_MINLOC MPI_MINLOC
#define PCL_RO_PROD MPI_PROD
#define PCL_RO_SUM MPI_SUM
#define PRINTPC(com) UG_LOG(__FUNCTION__ << " : " << __LINE__ << "\n"); PrintPC(com)
#define TESTLAYOUT(processCommunicator, com, master, slave)
#define TESTLAYOUTS(layout) TESTLAYOUT(layout->proc_comm(), layout->comm(), layout->master(), layout->slave())
Typedefs
typedef MPI_Datatype pcl::DataType
typedef int pcl::ProcID
typedef MPI_Op pcl::ReduceOperation
Enumerations
enum pcl::ProcessCommunicatorDefaults { pcl::PCD_EMPTY = 0, pcl::PCD_WORLD = 1, pcl::PCD_LOCAL = 2 }
values that can be passed to a ProcessCommunicators constructor.
Functions
void pcl::Abort (int errorcode=1)
call this method to abort all mpi processes
template<typename TLayout >
void pcl::AddLayout (TLayout &destLayout, const TLayout &sourceLayout)
bool pcl::AllProcsTrue (bool bFlag, ProcessCommunicator comm)
void pcl::AllReduce (void *sendBuf, void *recBuf, int count, DataType type, ReduceOperation op)
reduces the data to a single buffer using the specified ReduceOperation and distributes the result to all processes.
template<class TLayout >
size_t pcl::CollectAssociatedProcesses (std::vector< int > &procIDsOut, TLayout &layout)
collects the ids of all processes to which interfaces exist.
void pcl::CollectData (ProcID thisProcID, int firstSendProc, int numSendProcs, void *pBuffer, int bufferSizePerProc, int tag)
collect the data send with send_data from proc firstSendProc to numSendProcs excluding destProc.
template<class TLayout >
void pcl::CollectElements (std::vector< typename TLayout::Element > &elemsOut, TLayout &layout, bool clearContainer=true)
writes all elements in the interfaces into the vector.
template<class TLayout >
void pcl::CollectUniqueElements (std::vector< typename TLayout::Element > &elemsOut, const TLayout &layout)
writes all elements in the interfaces into the resulting vector. avoids doubles.
void pcl::CommunicateInvolvedProcesses (std::vector< int > &vReceiveFromRanksOut, const std::vector< int > &vSendToRanks, const ProcessCommunicator &procComm=ProcessCommunicator())
exchanges information about which process wants to communicate with which other process.
void pcl::DistributeData (ProcID thisProcID, int firstRecProc, int numRecProcs, void *pBuffer, int *pBufferSegSizes, int tag)
sends the data in the different sections of the buffer to the specified processes.
void pcl::DistributeData (ProcID thisProcID, int *pRecProcMap, int numRecProcs, void *pBuffer, int *pBufferSegSizes, int tag)
sends the data in the different sections of the buffer to the specified processes.
void pcl::Finalize ()
call this method right before quitting your application
size_t pcl::GetSize (const DataType &t)
void pcl::Init (int *argcp, char ***argvp)
call this method before any other pcl-operations.
template<class TType , class TLayoutMap >
void pcl::LogLayoutMapStructure (TLayoutMap &lm)
Logs the internals of a layout-map for a given type.
template<class TLayout >
void pcl::LogLayoutStructure (TLayout &layout, const char *prefix="")
Logs the internals of a layout.
int pcl::MPI_Wait (MPI_Request *request, MPI_Status *status=MPI_STATUS_IGNORE)
void pcl::MPI_Waitall (int count, MPI_Request *array_of_requests, MPI_Status *array_of_statuses)
int pcl::NumProcs ()
returns the number of processes
bool pcl::OneProcTrue (bool bFlag, ProcessCommunicator comm)
std::ostream & pcl::operator<< (std::ostream &out, const ProcessCommunicator &processCommunicator)
bool pcl::ParallelReadFile (std::string &filename, std::vector< char > &file, bool bText, bool bDistributedLoad, const ProcessCommunicator &pc=ProcessCommunicator())
util function to read a file in parallel.
template<typename TLayout , typename TValue >
bool pcl::PrintLayout (const pcl::ProcessCommunicator &processCommunicator, pcl::InterfaceCommunicator< TLayout > &com, const TLayout &masterLayout, const TLayout &slaveLayout, boost::function< TValue(typename TLayout::Element)> cbToValue=TrivialToValue< typename TLayout::Element >)
template<typename TLayout >
bool pcl::PrintLayout (const pcl::ProcessCommunicator &processCommunicator, pcl::InterfaceCommunicator< TLayout > &com, const TLayout &masterLayout, const TLayout &slaveLayout)
template<typename TLayout >
void pcl::PrintLayout (const TLayout &layout)
void pcl::PrintPC (const pcl::ProcessCommunicator &processCommunicator)
int pcl::ProcRank ()
returns the rank of the process
void pcl::ReceiveData (void *pBuffOut, ProcID srcProc, int bufferSize, int tag)
receives the data that was send with
template<class TLayout >
void pcl::RemoveEmptyInterfaces (TLayout &layout)
removes all empty interfaces from the given layout.
template<class TLayout , class TSelector >
bool pcl::RemoveUnselectedInterfaceEntries (TLayout &layout, TSelector &sel)
template<class TType , class TLayoutMap , class TSelector >
bool pcl::RemoveUnselectedInterfaceEntries (TLayoutMap &lm, TSelector &sel)
void pcl::SendData (ProcID destProc, void *pBuffer, int bufferSize, int tag)
sends data to another process. data may be received using
bool pcl::SendRecvBuffersMatch (const std::vector< int > &recvFrom, const std::vector< int > &recvBufSizes, const std::vector< int > &sendTo, const std::vector< int > &sendBufSizes, const ProcessCommunicator &involvedProcs=ProcessCommunicator())
checks whether matching buffers in send- and recv-lists have the same size
bool pcl::SendRecvListsMatch (const std::vector< int > &recvFrom, const std::vector< int > &sendTo, const ProcessCommunicator &involvedProcs=ProcessCommunicator())
checks whether proc-entries in send- and recv-lists on participating processes match
void pcl::SetErrHandler ()
sets error handler
void pcl::SynchronizeProcesses ()
template<typename TLayout , typename TValue >
bool pcl::TestLayout (const pcl::ProcessCommunicator &processCommunicator, pcl::InterfaceCommunicator< TLayout > &com, const TLayout &masterLayout, const TLayout &slaveLayout, bool bPrint=false, boost::function< TValue(typename TLayout::Element)> cbToValue=TrivialToValue< typename TLayout::Element >, bool compareValues=false)
Checks whether the given layouts are consistent.
template<typename TLayout >
bool pcl::TestLayout (const pcl::ProcessCommunicator &processCommunicator, pcl::InterfaceCommunicator< TLayout > &com, const TLayout &masterLayout, const TLayout &slaveLayout, bool bPrint=false, bool compareValues=false)
template<typename TLayout >
bool pcl::TestLayoutIsDoubleEnded (const pcl::ProcessCommunicator processCommunicator, pcl::InterfaceCommunicator< TLayout > &com, const TLayout &masterLayout, const TLayout &slaveLayout)
tests if masterLayouts proc id's find a match in corresponding slaveLayouts proc ids.
template<typename TLayout , typename TValue >
bool pcl::TestSizeOfInterfacesInLayoutsMatch (pcl::InterfaceCommunicator< TLayout > &com, const TLayout &masterLayout, const TLayout &slaveLayout, bool bPrint=false, boost::function< TValue(typename TLayout::Element)> cbToValue=TrivialToValue< typename TLayout::Element >, bool compareValues=false)
if processor P1 has a interface to P2, then the size of the interface P1->P2 has to be the same as the size of interface P2->P1
double pcl::Time ()
returns the time in seconds
std::string pcl::ToString (const ProcessCommunicator &pc)
template<class TElem >
TElem pcl::TrivialToValue (TElem e)
Trivial implementation of a to-value callback.
void pcl::Waitall (std::vector< MPI_Request > &requests, std::vector< MPI_Status > &statuses)
void pcl::Waitall (std::vector< MPI_Request > &requests)
void pcl::Waitall (std::vector< MPI_Request > &requests, std::vector< MPI_Request > &requests2)
Detailed Description
the Process Communication Layer
Macro Definition Documentation
#define DEBUG_TESTLAYOUT (processCommunicator, com, master, slave) TESTLAYOUT(processCommunicator, com, master, slave)
#define DEBUG_TESTLAYOUTS (layout) DEBUG_TESTLAYOUT(layout->proc_comm(), layout->comm(), layout->master(), layout->slave())
#define PCL_DT_BYTE MPI_BYTE
Referenced by pcl::ProcessCommunicator::allgatherv(), and pcl::ProcessCommunicator::gatherv().
#define PCL_DT_CHAR MPI_CHAR
Referenced by pcl::ProcessCommunicator::broadcast(), pcl::DataTypeTraits< char >::get_data_type(), and GetSize().
#define PCL_DT_DOUBLE MPI_DOUBLE
Referenced by ug::ParallelVector< TVector >::dotprod(), pcl::DataTypeTraits< double >::get_data_type(), GetSize(), ug::Integral(), ug::IntegralNormalComponentOnManifoldSubsets(), ug::IntegrateDiscFlux(), ug::IntegrateNormalGradientOnManifold(), ug::IntegrateSubsets(), ug::LocalSchurComplement< TAlgebra >::print_statistic_of_inner_solver(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::print_statistic_of_inner_solver(), and ug::FetiLayouts< algebra_type >::vec_prod_on_identified_dual().
#define PCL_DT_FLOAT MPI_FLOAT
Referenced by pcl::DataTypeTraits< float >::get_data_type(), and GetSize().
#define PCL_DT_INT MPI_INT
Referenced by pcl::ProcessCommunicator::allgatherv(), AllProcsTrue(), ug::BuildOneToManyLayout(), CommunicateInvolvedProcesses(), ug::ConstructParallelDualGraphMGLevel(), pcl::ProcessCommunicator::create_sub_communicator(), pcl::ProcessCommunicator::gatherv(), ug::ParallelDualGraph< TGeomBaseObj, TIndexType, TConnectingObj >::generate_graph(), pcl::DataTypeTraits< int >::get_data_type(), GetSize(), OneProcTrue(), ug::LocalSchurComplement< TAlgebra >::print_statistic_of_inner_solver(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::print_statistic_of_inner_solver(), SendRecvBuffersMatch(), SendRecvListsMatch(), ug::TestGridLayoutMap(), and ug::IDomain< TGrid, TSubsetHandler >::update_domain_info().
#define PCL_DT_LONG MPI_LONG
Referenced by pcl::ProcessCommunicator::broadcast(), pcl::DataTypeTraits< long >::get_data_type(), and GetSize().
#define PCL_DT_LONG_DOUBLE MPI_LONG_DOUBLE
#define PCL_DT_LONG_LONG_INT MPI_LONG_LONG_INT
#define PCL_DT_NULL MPI_DATATYPE_NULL
#define PCL_DT_PACKED MPI_PACKED
#define PCL_DT_SHORT MPI_SHORT
#define PCL_DT_UNSIGNED_CHAR MPI_UNSIGNED_CHAR
Referenced by pcl::DataTypeTraits< unsigned char >::get_data_type(), and GetSize().
#define PCL_DT_UNSIGNED_LONG MPI_UNSIGNED_LONG
Referenced by pcl::DataTypeTraits< unsigned long >::get_data_type(), and GetSize().
#define PCL_DT_UNSIGNED_LONG_LONG MPI_UNSIGNED_LONG_LONG
Referenced by pcl::ProcessCommunicator::allreduce(), ug::GenerateGlobalConsecutiveIndices(), pcl::ProcessCommunicator::reduce(), and ug::DoFCount::sum_values_over_procs().
#define PCL_RO_BAND MPI_BAND
Referenced by ug::ComPol_AttachmentReduce< TLayout, TAttachment >::ComPol_AttachmentReduce().
#define PCL_RO_BOR MPI_BOR
Referenced by ug::CheckDistributedObjectConstraintTypes(), ug::ComPol_AttachmentReduce< TLayout, TAttachment >::ComPol_AttachmentReduce(), and ug::SynchronizeAttachedGlobalAttachments().
#define PCL_RO_BXOR MPI_BXOR
#define PCL_RO_LAND MPI_LAND
Referenced by AllProcsTrue(), and ug::ComPol_AttachmentReduce< TLayout, TAttachment >::ComPol_AttachmentReduce().
#define PCL_RO_LOR MPI_LOR
Referenced by ug::ComPol_AttachmentReduce< TLayout, TAttachment >::ComPol_AttachmentReduce(), ug::ParallelHangingNodeRefiner_MultiGrid::contains_edges(), ug::ParallelHangingNodeRefiner_MultiGrid::contains_faces(), ug::ParallelHangingNodeRefiner_MultiGrid::contains_volumes(), and OneProcTrue().
#define PCL_RO_LXOR MPI_LXOR
#define PCL_RO_MAX MPI_MAX
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::ComPol_AttachmentReduce< TLayout, TAttachment >::ComPol_AttachmentReduce(), ug::ComputeAvg(), ug::ComputeMinMax(), pcl::ProcessCommunicator::create_sub_communicator(), ug::LoadBalancer::estimate_distribution_quality(), ug::LoadBalancer::estimate_distribution_quality_impl(), ug::GetMaxEdgeLength(), ug::MarkForAdaption_GradientAverage(), ug::MarkForAdaption_GradientJump(), ug::MarkForAdaption_L2ErrorExact(), ug::MarkForAdaption_ResidualErrorP1Relative(), ug::MaxElementDiameter(), ug::bridge::ParallelMax(), ug::bridge::ParallelVecMax(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection(), ug::LocalSchurComplement< TAlgebra >::print_statistic_of_inner_solver(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::print_statistic_of_inner_solver(), ug::PrintElementEdgeRatios(), ug::SurfaceView::refresh_surface_states(), ug::TestGridLayoutMap(), and ug::IDomain< TGrid, TSubsetHandler >::update_domain_info().
#define PCL_RO_MAXLOC MPI_MAXLOC
#define PCL_RO_MIN MPI_MIN
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::ComPol_AttachmentReduce< TLayout, TAttachment >::ComPol_AttachmentReduce(), ug::ComputeAvg(), ug::ComputeMinMax(), ug::LoadBalancer::estimate_distribution_quality_impl(), ug::MarkForAdaption_GradientAverage(), ug::MarkForAdaption_GradientJump(), ug::MarkForAdaption_L2ErrorExact(), ug::MarkForAdaption_ResidualErrorP1Relative(), ug::bridge::ParallelMin(), ug::bridge::ParallelVecMin(), ug::LocalSchurComplement< TAlgebra >::print_statistic_of_inner_solver(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::print_statistic_of_inner_solver(), ug::PrintElementEdgeRatios(), and ug::IDomain< TGrid, TSubsetHandler >::update_domain_info().
#define PCL_RO_MINLOC MPI_MINLOC
#define PCL_RO_PROD MPI_PROD
Referenced by ug::ComPol_AttachmentReduce< TLayout, TAttachment >::ComPol_AttachmentReduce().
#define PCL_RO_SUM MPI_SUM
Referenced by ug::SideAndElemErrEstData< TDomain >::alloc_err_est_data(), ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::ComPol_AttachmentReduce< TLayout, TAttachment >::ComPol_AttachmentReduce(), ug::ComputeAvg(), ug::ComputeMinMax(), ug::ParallelVector< TVector >::dotprod(), ug::LoadBalancer::estimate_distribution_quality_impl(), ug::GlobalGridFunctionNumberData< TGridFunction >::evaluate_global(), ug::ExchangeAndAdjustSideErrors(), ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values(), ug::Integral(), ug::IntegralNormalComponentOnManifoldSubsets(), ug::IntegrateDiscFlux(), ug::IntegrateNormalGradientOnManifold(), ug::IntegrateSubsets(), ug::MaximumMarking< TDomain >::mark(), ug::VarianceMarking< TDomain >::mark(), ug::VarianceMarkingEta< TDomain >::mark(), ug::MeanValueMarking< TDomain >::mark(), ug::EquilibrationMarkingStrategy< TDomain >::mark(), ug::AbsoluteMarking< TDomain >::mark(), ug::MarkElements(), ug::MarkElementsAbsolute(), ug::MarkElementsForCoarsening(), ug::MarkElementsForRefinement(), ug::MarkForAdaption_GradientAverage(), ug::MarkForAdaption_L2ErrorExact(), ug::MarkForAdaption_ResidualErrorP1Absolute(), ug::ParallelVector< TVector >::norm(), ug::AlgebraicConvCheck< TVector >::norm(), ug::CompositeConvCheck< TVector, TDomain >::norm(), ug::SchurPrecond< TAlgebra >::num_global_skeleton(), ug::IRefiner::num_marked_edges(), ug::IRefiner::num_marked_elements(), ug::IRefiner::num_marked_faces(), ug::IRefiner::num_marked_volumes(), ug::bridge::ParallelSum(), ug::bridge::ParallelVecSum(), ug::LocalSchurComplement< TAlgebra >::print_statistic_of_inner_solver(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::print_statistic_of_inner_solver(), ug::PrintElementEdgeRatios(), ug::DoFCount::sum_values_over_procs(), ug::SideAndElemErrEstData< TDomain >::summarize_err_est_data(), ug::IDomain< TGrid, TSubsetHandler >::update_domain_info(), and ug::FetiLayouts< algebra_type >::vec_prod_on_identified_dual().
#define PRINTPC (com) UG_LOG(__FUNCTION__ << " : " << __LINE__ << "\n"); PrintPC(com)
#define TESTLAYOUT (processCommunicator, com, master, slave)
Value:
{ if(TestLayout(processCommunicator,\
    com, master, slave) == false) { PrintLayout(processCommunicator, com, master, slave); UG_COND_THROW(true, "layout broken"); } }
#define TESTLAYOUTS (layout) TESTLAYOUT(layout->proc_comm(), layout->comm(), layout->master(), layout->slave())
Typedef Documentation
typedef MPI_Datatype pcl::DataType
typedef int pcl::ProcID
typedef MPI_Op pcl::ReduceOperation
Enumeration Type Documentation
enum pcl::ProcessCommunicatorDefaults
values that can be passed to a ProcessCommunicators constructor.
Enumerator
PCD_EMPTY
PCD_WORLD
PCD_LOCAL
Function Documentation
void pcl::Abort (int errorcode)
call this method to abort all mpi processes
References PCL_COMM_WORLD, and PCL_PROFILE.
Referenced by MPIErrorHandler(), quit_all_mpi_procs_in_parallel(), ug_assert_failed(), and ug::UGForceExit().
template<typename TLayout > void pcl::AddLayout (TLayout & destLayout, const TLayout & sourceLayout)
References ParallelReadFile().
Referenced by ug::GenerateOverlapClass< matrix_type >::calculate(), ug::GenerateOverlapClass< matrix_type >::communicate(), ug::CreateAllToAllFromMasterSlave(), and ug::ParallelNodes::ParallelNodes().
bool pcl::AllProcsTrue (bool bFlag, ProcessCommunicator comm = ProcessCommunicator())
performs an allreduce and returns true if and only if all procs called the function with bFlag = true
References pcl::ProcessCommunicator::allreduce(), pcl::ProcessCommunicator::empty(), pcl::ProcessCommunicator::is_local(), PCL_DEBUG_BARRIER, PCL_DT_INT, PCL_PROFILE, and PCL_RO_LAND.
Referenced by ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), ug::FETISolver< TAlgebra >::apply_return_defect(), ug::AgglomeratingBase< IPreconditioner< TAlgebra >, TAlgebra >::base_init(), ug::CheckDiagonalInvertible(), ug::CheckDistributedObjectConstraintTypes(), ug::CheckDistributedParentTypes(), ug::CheckVectorInvertible(), ug::ConsistencyCheck(), ug::FETISolver< TAlgebra >::init(), ug::IsFinite(), ug::IsFiniteAndNotTooBig(), ug::LoadGrid(), ug::script::LoadUGScript(), ug::bridge::PclAllProcsTrue(), SendRecvBuffersMatch(), SendRecvListsMatch(), ug::TestGridLayoutMap(), and TestLayout().
void pcl::AllReduce (void * sendBuf, void * recBuf, int count, DataType type, ReduceOperation op)
reduces the data to a single buffer using the specified ReduceOperation and distributes the result to all processes.
Both, sendBuf and recBuf have to hold count elements of the specified type.
Parameters
sendBuf Sending buffer
recBuf Recieve buffer
count
type Data type
op has to be one of the
References PCL_COMM_WORLD, and UG_LOG.
template<class TLayout > size_t pcl::CollectAssociatedProcesses (std::vector< int > & procIDsOut, TLayout & layout)
collects the ids of all processes to which interfaces exist.
Fills a vector with the process-ids, to which interfaces exist in the given layout.
TLayout has to be compatible with pcl::Layout or pcl::MultiLevelLayout.
Returns
the number of associated processes.
References ug::find().
void pcl::CollectData (ProcID thisProcID, int firstSendProc, int numSendProcs, void * pBuffer, int bufferSizePerProc, int tag)
collect the data send with send_data from proc firstSendProc to numSendProcs excluding destProc.
References PCL_COMM_WORLD, UG_LOG, and Waitall().
template<class TLayout > void pcl::CollectElements (std::vector< typename TLayout::Element > & elemsOut, TLayout & layout, bool clearContainer = true)
writes all elements in the interfaces into the vector.
This function extracts all elements from a layout and stores them into a std::vector. Doubles may occur and are not removed. The container is clear as default, before extracting.
Referenced by ug::FetiLayouts< algebra_type >::create_layouts().
template<class TLayout > void pcl::CollectUniqueElements (std::vector< typename TLayout::Element > & elemsOut, const TLayout & layout)
writes all elements in the interfaces into the resulting vector. avoids doubles.
References ug::Hash< TKey, TValue >::reserve().
Referenced by ug::BuildOneToManyLayout(), ug::GenerateOverlapClass< matrix_type >::calculate(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::init(), ug::IExternalSolver< TAlgebra >::mat_preprocess(), ug::GaussSeidelBase< TAlgebra >::preprocess(), ug::ComponentGaussSeidel< TDomain, TAlgebra >::preprocess(), ug::ILUTScalarPreconditioner< algebra_type >::preprocess(), ug::Vanka< TAlgebra >::preprocess(), ug::IBlockJacobiPreconditioner< TAlgebra >::preprocess(), ug::DiagVanka< TAlgebra >::preprocess(), ug::ILU< TAlgebra >::preprocess(), ug::LineGaussSeidel< TDomain, TAlgebra >::preprocess(), ug::LineVanka< TDomain, TAlgebra >::preprocess(), and ug::ILUTPreconditioner< ug::CPUAlgebra >::preprocess_mat().
void pcl::CommunicateInvolvedProcesses (std::vector< int > & vReceiveFromRanksOut, const std::vector< int > & vSendToRanks, const ProcessCommunicator & procComm = ProcessCommunicator())
exchanges information about which process wants to communicate with which other process.
If processes want to send data to other processes, but the target processes do not know from where to receive their data, then this method can be used to notify each process from where he has to receive data.
Each process has to call this method, passing an array of process-ids to where it will send data (vSendToRanks).
The processes from which it has to receive data are then collected in vReceiveFromRanksOut.
Note that this method involves global communication (with respect to the used process-communicator) and should thus be rarely used - at least if the used process communicator is big.
References pcl::ProcessCommunicator::allgather(), pcl::ProcessCommunicator::allgatherv(), pcl::ProcessCommunicator::get_proc_id(), ug::GetDataPtr(), PCL_DT_INT, PCL_PROFILE, ProcRank(), and pcl::ProcessCommunicator::size().
Referenced by ug::DistributeGrid(), and SendRecvListsMatch().
void pcl::DistributeData (ProcID thisProcID, int firstRecProc, int numRecProcs, void * pBuffer, int * pBufferSegSizes, int tag)
sends the data in the different sections of the buffer to the specified processes.
pBufferSegSizes has to contain numRecProcs elements. Buffer-Segments are send to the processes firstRecProc, ..., firstRecProc + numRecProcs. If thisProcID lies in this range, then the buffer-segments are sent to firstRecProc, ..., firstRecProc + numRecProcs + 1, excluding thisProcID.
References PCL_COMM_WORLD, UG_LOG, and Waitall().
void pcl::DistributeData (ProcID thisProcID, int * pRecProcMap, int numRecProcs, void * pBuffer, int * pBufferSegSizes, int tag)
sends the data in the different sections of the buffer to the specified processes.
pRecProcMap and pBufferSegSizes have to contain numRecProcs elements. Entries in pRecProcMap specify the target-process of the i-th buffer segment.
References PCL_COMM_WORLD, UG_LOG, and Waitall().
void pcl::Finalize ()
call this method right before quitting your application
References PCL_PROFILE.
Referenced by ug::UGFinalize().
size_t pcl::GetSize (const DataType & t) inline
References PCL_DT_CHAR, PCL_DT_DOUBLE, PCL_DT_FLOAT, PCL_DT_INT, PCL_DT_LONG, PCL_DT_UNSIGNED_CHAR, PCL_DT_UNSIGNED_LONG, and UG_THROW.
Referenced by ug::ActiveSet< TDomain, TAlgebra >::ActiveSet(), pcl::ProcessCommunicator::allgather(), pcl::ProcessCommunicator::allgatherv(), pcl::ProcessCommunicator::allreduce(), pcl::ProcessCommunicator::gather(), pcl::ProcessCommunicator::gatherv(), pcl::ProcessCommunicator::reduce(), and pcl::ProcessCommunicator::scatter().
void pcl::Init (int * argcp, char *** argvp)
call this method before any other pcl-operations.
References PCL_COMM_WORLD, PCL_PROFILE, and SetErrHandler().
Referenced by main(), and ug::UGInit().
template<class TType , class TLayoutMap > void pcl::LogLayoutMapStructure (TLayoutMap & lm)
Logs the internals of a layout-map for a given type.
Supported layouts are pcl::SingleLevelLayout and pcl::MultiLevelLayout.
References LogLayoutStructure(), and PCLLOG.
template<class TLayout > void pcl::LogLayoutStructure (TLayout & layout, const char * prefix = "")
Logs the internals of a layout.
Supported layouts are pcl::SingleLevelLayout and pcl::MultiLevelLayout.
References PCLLOG.
Referenced by LogLayoutMapStructure().
int pcl::MPI_Wait (MPI_Request * request, MPI_Status * status = MPI_STATUS_IGNORE) inline
References PROFILE_FUNC_GROUP.
Referenced by pcl::ProcessCommunicator::receive_data(), ReceiveData(), pcl::ProcessCommunicator::send_data(), and SendData().
void pcl::MPI_Waitall (int count, MPI_Request * array_of_requests, MPI_Status * array_of_statuses) inline
References PROFILE_FUNC_GROUP.
Referenced by Waitall().
int pcl::NumProcs ()
returns the number of processes
References PCL_COMM_WORLD.
Referenced by ug::ComputeAvg(), ug::ComputeMinMax(), pcl::ProcessCommunicator::create_sub_communicator(), ug::CreateGlobalFracturedDomainRefiner(), ug::CreateLayoutsFromDistInfos(), ug::bridge::DebugShell(), ug::GlobalGridFunctionNumberData< TGridFunction >::evaluate_global(), pcl::InterfaceCommunicator< TLayout >::ExtractorInfo::ExtractorInfo(), ug::ConnectionViewer::GetParallelName(), ug::GlobalDomainRefiner(), ug::HangingNodeDomainRefiner(), ug::IdentifySubsets(), ug::AssembledMultiGridCycle< TDomain, TAlgebra >::ignore_init_for_base_solver(), ug::bridge::InitUG(), ug::Integral(), ug::IntegralNormalComponentOnManifoldSubsets(), ug::IntegrateDiscFlux(), ug::IntegrateNormalGradientOnManifold(), ug::IntegrateSubsets(), ug::script::LoadUGScript(), ug::LogIndexLayoutOnAllProcs(), main(), ug::MaximumMarking< TDomain >::mark(), ug::VarianceMarking< TDomain >::mark(), ug::VarianceMarkingEta< TDomain >::mark(), ug::MeanValueMarking< TDomain >::mark(), ug::EquilibrationMarkingStrategy< TDomain >::mark(), ug::AbsoluteMarking< TDomain >::mark(), ug::SurfaceView::mark_shadowing(), ug::MarkElements(), ug::MarkElementsAbsolute(), ug::MarkElementsForCoarsening(), ug::MarkElementsForRefinement(), ug::GaussSeidelBase< TAlgebra >::preprocess(), ug::ComponentGaussSeidel< TDomain, TAlgebra >::preprocess(), ug::ElementGaussSeidel< TDomain, TAlgebra >::preprocess(), ug::Vanka< TAlgebra >::preprocess(), ug::DiagVanka< TAlgebra >::preprocess(), ug::LineGaussSeidel< TDomain, TAlgebra >::preprocess(), ug::LineVanka< TDomain, TAlgebra >::preprocess(), ug::IApproximationSpace::print_layout_statistic(), ug::IApproximationSpace::print_statistic(), ug::LocalSchurComplement< TAlgebra >::print_statistic_of_inner_solver(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::print_statistic_of_inner_solver(), ug::VTKOutput< TDim >::print_subset(), ug::VTKOutput< TDim >::print_subsets(), ug::CopyAttachmentHandler< TElem, TAttachment >::propagate_to_level(), quit_all_mpi_procs_in_parallel(), ReadCombinedParallelFile(), ug::ReceiveMatrix(), ug::bridge::RegisterBridge_PCL(), pcl::InterfaceCommunicator< TLayout >::send_data(), pcl::InterfaceCommunicator< TLayout >::send_raw(), ug::SerializeRow(), pcl::StandardDomainDecompositionInfo::set_num_subdomains(), ug::LogAssistant::set_output_process(), pcl::StandardDomainDecompositionInfo::StandardDomainDecompositionInfo(), ug::GaussSeidelBase< TAlgebra >::step(), ug::ComponentGaussSeidel< TDomain, TAlgebra >::step(), ug::ElementGaussSeidel< TDomain, TAlgebra >::step(), ug::Vanka< TAlgebra >::step(), ug::DiagVanka< TAlgebra >::step(), ug::LineGaussSeidel< TDomain, TAlgebra >::step(), ug::LineVanka< TDomain, TAlgebra >::step(), ug::SynchronizeDistInfos(), ug::UGForceExit(), ug::VTKOutput< TDim >::vtu_filename(), ug::VTKOutput< TDim >::write_pvtu(), ug::VTKOutput< TDim >::write_subset_pvd(), ug::VTKOutput< TDim >::write_time_pvd(), WriteCombinedParallelFile(), and ug::ConnectionViewer::WriteMatrixPar().
bool pcl::OneProcTrue (bool bFlag, ProcessCommunicator comm = ProcessCommunicator())
performs an allreduce and returns true at least one process called the function with bFlag = true
References pcl::ProcessCommunicator::allreduce(), pcl::ProcessCommunicator::empty(), pcl::ProcessCommunicator::is_local(), PCL_DEBUG_BARRIER, PCL_DT_INT, PCL_PROFILE, and PCL_RO_LOR.
Referenced by ug::ParallelHangingNodeRefiner_MultiGrid::continue_collect_objects_for_refine(), ug::LoadGrid(), ug::HangingNodeRefinerBase< TSelector >::mark_neighborhood(), ug::ParallelHangingNodeRefiner_MultiGrid::one_proc_true(), and ug::ParallelHNodeAdjuster::ref_marks_changed().
std::ostream & pcl::operator<< (std::ostream & out, const ProcessCommunicator & processCommunicator)
References pcl::ProcessCommunicator::empty(), pcl::ProcessCommunicator::get_proc_id(), pcl::ProcessCommunicator::is_local(), pcl::ProcessCommunicator::is_world(), and pcl::ProcessCommunicator::size().
bool pcl::ParallelReadFile (std::string & filename, std::vector< char > & file, bool bText, bool bDistributedLoad, const ProcessCommunicator & pc = ProcessCommunicator())
util function to read a file in parallel.
See also
ReadFile in serial
Parameters
filename filename (in/out!)
file the file
if true, use r instead of rb for file functions
bDistributedLoad if false, just use ReadFile.
rank which should open files. core with rank pc.get_proc_id(0) reads this filename. status, filename, and file are transmitted to other cores
Returns
false on all cores if
template<typename TLayout , typename TValue > bool pcl::PrintLayout (const pcl::ProcessCommunicator & processCommunicator, pcl::InterfaceCommunicator< TLayout > & com, const TLayout & masterLayout, const TLayout & slaveLayout, boost::function< TValue(typename TLayout::Element)> cbToValue = TrivialToValue<typename TLayout::Element>)
References TestLayout().
Referenced by ug::GenerateOverlapClass< matrix_type >::calculate(), ug::GenerateOverlapClass< matrix_type >::communicate(), and ug::FetiLayouts< algebra_type >::create_layouts().
template<typename TLayout > bool pcl::PrintLayout (const pcl::ProcessCommunicator & processCommunicator, pcl::InterfaceCommunicator< TLayout > & com, const TLayout & masterLayout, const TLayout & slaveLayout) inline
References TestLayout().
template<typename TLayout > void pcl::PrintLayout (const TLayout & layout) inline
References UG_LOG.
void pcl::PrintPC (const pcl::ProcessCommunicator & processCommunicator) inline
References pcl::ProcessCommunicator::get_proc_id(), pcl::ProcessCommunicator::size(), and UG_LOG.
int pcl::ProcRank ()
returns the rank of the process
References PCL_COMM_WORLD.
Referenced by ug::ParallelNodes::add_new_layouts_to(), ug::AddConnectionsBetweenSlaves(), ug::AddEntriesToIndexLayout_DomainDecomposition(), ug::AddExtraProcessEntriesToSubdomainLayout(), ug::SchurComplementOperator< TAlgebra >::apply(), ug::LocalSchurComplement< TAlgebra >::apply(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::apply_return_defect(), pcl::ProcessCommunicator::broadcast(), ug::BroadcastGrid(), ug::BroadcastVectorFromOne(), ug::BuildDomainDecompositionLayouts(), ug::BuildOneToManyLayout(), ug::CollectMatrixOnOneProc(), ug::ParallelColoring::color(), ug::CommunicateConnections(), CommunicateInvolvedProcesses(), ug::ContinuousDebugSave(), ug::CopyInterfaceEntrysToDomainDecompositionLayouts(), ug::ComPol_NewConstrainedVerticals< TLayout >::create_initial_hash_entry(), ug::FetiLayouts< algebra_type >::create_layouts(), ug::DistributedGridManager::create_missing_constrained_h_interfaces(), ug::NewLayoutCreator::create_node(), ug::ParallelNodes::create_node(), ug::CreateAndDistributeGlobalIDs(), ug::CreateLayoutsFromDistInfos(), ug::HangingNodeRefiner_MultiGrid::debug_save(), ug::DistributeGrid(), ug::ComPol_NewConstrainedVerticals< TLayout >::exchange_data(), ug::ComPol_NewConstrainedVerticals< TLayout >::extract(), ug::FillDistInfos(), ug::GatherVectorOnOne(), ug::GenerateGlobalAlgebraIDs(), ug::ParallelNodes::get_local_index_if_available(), ug::ParallelNodes::get_local_index_or_create_new(), pcl::ProcessCommunicator::get_local_proc_id(), pcl::ProcessCommunicator::get_proc_id(), ug::LogAssistant::get_process_rank(), ug::ConnectionViewer::GetParallelName(), ug::IApproximationSpace::grid_changed_callback(), ug::IApproximationSpace::grid_distribution_callback(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::init(), ug::ProcessHierarchy::init_cluster_procs(), ug::AgglomeratingBase< IPreconditioner< TAlgebra >, TAlgebra >::init_mat(), ug::AlgebraID::is_master(), ug::LogAssistant::is_output_process(), pcl::ProcessCommunicator::is_proc_id(), ug::AlgebraID::is_slave(), ug::LoadDomain(), ug::LoadGrid(), ug::script::LoadUGScript(), ug::LogIndexLayoutOnAllProcs(), ug::MarkElements(), ug::MarkElementsAbsolute(), ug::MergeGlobalLayout(), ug::ParallelLayoutDebugSave(), ug::ParallelNodes::ParallelNodes(), ParallelReadFile(), ug::Partitioner_DynamicBisection< TElem, dim >::partition(), ug::PartitionDomain_MetisKWay(), ug::PartitionDomain_RegularGrid(), ug::PartitionMultiGridLevel_MetisKway(), ug::PartitionMultiGridLevel_ParmetisKway(), ug::ParallelHangingNodeRefiner_MultiGrid::post_coarsen(), ug::ParallelHangingNodeRefiner_MultiGrid::post_refine(), ug::ParallelHangingNodeRefiner_MultiGrid::pre_coarsen(), ug::ParallelHangingNodeRefiner_MultiGrid::pre_refine(), ug::VTKOutput< TDim >::print(), ug::IApproximationSpace::print_statistic(), ug::VTKOutput< TDim >::print_subset(), ug::VTKOutput< TDim >::print_subsets(), ug::NewLayoutCreator::process(), ug::ParallelNodes::process(), ReadCombinedParallelFile(), ug::ConsistencyCheckClass< TVec, TValue >::receive(), ug::ReceiveMatrix(), ug::bridge::RegisterBridge_PCL(), ug::SendMatrix(), SendRecvBuffersMatch(), SendRecvListsMatch(), ug::SchurComplementOperator< TAlgebra >::set_debug_dim(), ug::ParallelProgress::start(), ug::SynchronizeDistInfos(), TestLayout(), TestLayoutIsDoubleEnded(), TestSizeOfInterfacesInLayoutsMatch(), ug::IDomain< TGrid, TSubsetHandler >::update_subset_infos(), ug::VTKOutput< TDim >::write_subset_pvd(), WriteCombinedParallelFile(), ug::ConnectionViewer::WriteMatrixPar(), WriteParallelArchive(), and ug::WriteVectorCSV().
void pcl::ReceiveData (void * pBuffOut, ProcID srcProc, int bufferSize, int tag)
receives the data that was send with
See also
SendData or
DistributeData.
References MPI_Wait(), PCL_COMM_WORLD, and UG_LOG.
template<class TLayout > void pcl::RemoveEmptyInterfaces (TLayout & layout)
removes all empty interfaces from the given layout.
Referenced by ug::AddEntriesToLevelIndexLayout(), ug::AddEntriesToSurfaceIndexLayout(), and ug::DoFDistribution::reinit_index_layout().
template<class TLayout , class TSelector > bool pcl::RemoveUnselectedInterfaceEntries (TLayout & layout, TSelector & sel)
Removes unselected entries from the interfaces in the given layout. Empty interfaces are removed from the layout, too.
TLayout has to be compatible with pcl::Layout or pcl::MultiLevelLayout.
bool TSelector::is_selected(TType* t);
Returns
: true, if the layout has changed, false if not.
Referenced by RemoveUnselectedInterfaceEntries().
template<class TType , class TLayoutMap , class TSelector > bool pcl::RemoveUnselectedInterfaceEntries (TLayoutMap & lm, TSelector & sel)
Removes interface-entries, empty interfaces and empty layouts from the given layoutMap for the given type.
TLayoutMap has to be compatible with pcl::LayoutMap.
TSelector has to feature a method
bool TSelector::is_selected(TType* t);
Returns
: true, if the layout-map has changed, false if not.
References RemoveUnselectedInterfaceEntries().
void pcl::SendData (ProcID destProc, void * pBuffer, int bufferSize, int tag)
sends data to another process. data may be received using
See also
ReceiveData or
CollectData.
References MPI_Wait(), PCL_COMM_WORLD, and UG_LOG.
bool pcl::SendRecvBuffersMatch (const std::vector< int > & recvFrom, const std::vector< int > & recvBufSizes, const std::vector< int > & sendTo, const std::vector< int > & sendBufSizes, const ProcessCommunicator & involvedProcs = ProcessCommunicator())
checks whether matching buffers in send- and recv-lists have the same size
Note that this method does not check whether matching buffers exist. This is assumed. Checks are only performed on the sizes of associated buffers.
Make sure that recvBufSizes specifies the buffer size for each entry in recvFrom. Same for sendBufSizes and sendTo.
The return value is the same for all participating processes.
See also
pcl::SendRecvMapsMatch
References AllProcsTrue(), pcl::ProcessCommunicator::gather(), ug::LogAssistant::get_output_process(), pcl::ProcessCommunicator::get_proc_id(), ug::GetLogAssistant(), PCL_COMM_WORLD, PCL_DT_INT, PCL_PROFILE_FUNC, ProcRank(), pcl::ProcessCommunicator::size(), UG_LOG, and Waitall().
Referenced by pcl::InterfaceCommunicator< TLayout >::communicate_and_resume().
bool pcl::SendRecvListsMatch (const std::vector< int > & recvFrom, const std::vector< int > & sendTo, const ProcessCommunicator & involvedProcs = ProcessCommunicator())
checks whether proc-entries in send- and recv-lists on participating processes match
The return value is the same for all participating processes.
See also
pcl::SendRecvBuffersMatch
References AllProcsTrue(), CommunicateInvolvedProcesses(), ug::find(), pcl::ProcessCommunicator::gather(), ug::LogAssistant::get_output_process(), pcl::ProcessCommunicator::get_proc_id(), ug::GetLogAssistant(), PCL_DT_INT, PCL_PROFILE_FUNC, ProcRank(), pcl::ProcessCommunicator::size(), and UG_LOG.
Referenced by pcl::InterfaceCommunicator< TLayout >::communicate_and_resume().
void pcl::SetErrHandler ()
sets error handler
References MPIErrorHandler(), and PCL_COMM_WORLD.
Referenced by Init().
void pcl::SynchronizeProcesses ()
synchronizes all processes. This is just a shortcut if all processes have to be synchronized. This is equivalent to calling pcl::ProcessCommunicator()::barrier().
See also
pcl::ProcessCommunicator::barrier
References pcl::ProcessCommunicator::barrier().
Referenced by ug::LogIndexLayoutOnAllProcs(), and ug::bridge::RegisterBridge_PCL().
template<typename TLayout , typename TValue > bool pcl::TestLayout (const pcl::ProcessCommunicator & processCommunicator, pcl::InterfaceCommunicator< TLayout > & com, const TLayout & masterLayout, const TLayout & slaveLayout, bool bPrint = false, boost::function< TValue(typename TLayout::Element)> cbToValue = TrivialToValue<typename TLayout::Element>, bool compareValues = false)
Checks whether the given layouts are consistent.
Checks whether the given master and slave layout have the same number of elements and prints associated elements if bPrint = true. If the callback cbToValue is specified, then it is used during printing to print values associated with the elements in the layouts instead of printing the elements directly.
If compareValues = true is specified, then all entries supplied by cbToValue are compared between connected interface entries and mismatches are reported.
The methods returns true if all interfaces match and false if not. The return values are consistent among all processes.
References AllProcsTrue(), ProcRank(), PROFILE_FUNC_GROUP, TestLayoutIsDoubleEnded(), and UG_LOG.
Referenced by ug::GenerateOverlapClass< matrix_type >::calculate(), ug::GenerateOverlapClass< matrix_type >::communicate(), ug::PrimalSubassembledMatrixInverse< TAlgebra >::init(), PrintLayout(), ug::PrintLayouts(), and ug::FetiLayouts< algebra_type >::test_layouts().
template<typename TLayout > bool pcl::TestLayout (const pcl::ProcessCommunicator & processCommunicator, pcl::InterfaceCommunicator< TLayout > & com, const TLayout & masterLayout, const TLayout & slaveLayout, bool bPrint = false, bool compareValues = false)
template<typename TLayout > bool pcl::TestLayoutIsDoubleEnded (const pcl::ProcessCommunicator processCommunicator, pcl::InterfaceCommunicator< TLayout > & com, const TLayout & masterLayout, const TLayout & slaveLayout)
tests if masterLayouts proc id's find a match in corresponding slaveLayouts proc ids.
that is, iff processor P1 has processor P2 in his masterLayout, then processor P2 needs to have P1 in his slaveLayout
References pcl::InterfaceCommunicator< TLayout >::communicate(), ug::Deserialize(), pcl::ProcessCommunicator::get_local_proc_id(), pcl::ProcessCommunicator::get_proc_id(), ProcRank(), PROFILE_FUNC_GROUP, pcl::InterfaceCommunicator< TLayout >::receive_raw(), pcl::InterfaceCommunicator< TLayout >::send_raw(), pcl::ProcessCommunicator::size(), and UG_LOG.
Referenced by TestLayout().
template<typename TLayout , typename TValue > bool pcl::TestSizeOfInterfacesInLayoutsMatch (pcl::InterfaceCommunicator< TLayout > & com, const TLayout & masterLayout, const TLayout & slaveLayout, bool bPrint = false, boost::function< TValue(typename TLayout::Element)> cbToValue = TrivialToValue<typename TLayout::Element>, bool compareValues = false)
if processor P1 has a interface to P2, then the size of the interface P1->P2 has to be the same as the size of interface P2->P1
You may specify a callback, which allows to print not the elements in the interfaces directly, but to print associated values. This is useful, if e.g. pointers are stored in the layouts.
If compareValues = true is specified, then all entries supplied by cbToValue are compared between connected interface entries and mismatches are reported.
The callback-method takes a parameter of type TLayout::Element and has to return a value of type TValue (TValue = TLayout::Element by default).
References ug::BinaryBuffer::buffer(), pcl::InterfaceCommunicator< TLayout >::communicate(), ug::Deserialize(), ug::BinaryBuffer::eof(), ProcRank(), PROFILE_FUNC_GROUP, pcl::InterfaceCommunicator< TLayout >::receive_raw(), pcl::InterfaceCommunicator< TLayout >::send_raw(), ug::Serialize(), UG_LOG, and ug::BinaryBuffer::write_pos().
double pcl::Time ()
returns the time in seconds
std::string pcl::ToString (const ProcessCommunicator & pc) inline
References pcl::ProcessCommunicator::empty(), pcl::ProcessCommunicator::get_proc_id(), pcl::ProcessCommunicator::is_world(), and pcl::ProcessCommunicator::size().
template<class TElem > TElem pcl::TrivialToValue (TElem e)
Trivial implementation of a to-value callback.
TValue has to be constructable from TElem.
void pcl::Waitall (std::vector< MPI_Request > & requests, std::vector< MPI_Status > & statuses) inline
References MPI_Waitall(), and PROFILE_FUNC_GROUP.
Referenced by CollectData(), pcl::InterfaceCommunicator< TLayout >::communicate_and_resume(), pcl::ProcessCommunicator::distribute_data(), DistributeData(), pcl::ProcessCommunicator::send_data(), SendRecvBuffersMatch(), and pcl::InterfaceCommunicator< TLayout >::wait().
void pcl::Waitall (std::vector< MPI_Request > & requests) inline
References MPI_Waitall(), and PROFILE_FUNC_GROUP.
void pcl::Waitall (std::vector< MPI_Request > & requests, std::vector< MPI_Request > & requests2) inline
References MPI_Waitall(), and PROFILE_FUNC_GROUP.