ug4: Load Balancing Bridge
Load Balancing Bridge
ugbase » Bridge » Domain Bridge
Classes
class ug::BalanceWeightsLuaCallback< TDomain >
struct ug::bridge::LoadBalancing::Functionality
class ug::PartPreProc_RasterProjectorCoordinates< dim >
Functions
template<class TDomain , class elem_t , class vector_t >
static void ug::bridge::LoadBalancing::RegisterClusterElementStacks (Registry &reg, string name, string grpName, string clsGrpName)
template<class TDomain , class TPartitioner >
static void ug::bridge::LoadBalancing::RegisterDynamicBisectionPartitioner (Registry &reg, string name, string grpName, string clsGrpName)
template<class TDomain , class elem_t >
static void ug::bridge::LoadBalancing::RegisterSmoothPartitionBounds (Registry &reg, string name, string grpName, string clsGrpName)
Detailed Description
Function Documentation
RegisterClusterElementStacks()
template<class TDomain , class elem_t , class vector_t > static void ug::bridge::LoadBalancing::RegisterClusterElementStacks (Registry & reg, string name, string grpName, string clsGrpName) static
References ug::bridge::Registry::add_class_(), and ug::bridge::Registry::add_class_to_group().
RegisterDynamicBisectionPartitioner()
template<class TDomain , class TPartitioner > static void ug::bridge::LoadBalancing::RegisterDynamicBisectionPartitioner (Registry & reg, string name, string grpName, string clsGrpName) static
References ug::bridge::Registry::add_class_(), and ug::bridge::Registry::add_class_to_group().
Referenced by ug::bridge::LoadBalancing::Functionality::Common().
RegisterSmoothPartitionBounds()
template<class TDomain , class elem_t > static void ug::bridge::LoadBalancing::RegisterSmoothPartitionBounds (Registry & reg, string name, string grpName, string clsGrpName) static
References ug::bridge::Registry::add_class_(), and ug::bridge::Registry::add_class_to_group().