ug4: Interpolation Bridge
Interpolation Bridge
ugbase » Bridge » Discretization Bridge
Classes
struct ug::bridge::Interpolate::Functionality
struct ug::bridge::Evaluate::Functionality
Functions
template<typename TGridFunction >
number ug::bridge::Evaluate::EvaluateAtClosestVertex (const MathVector< TGridFunction::dim > &pos, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, SmartPtr< typename TGridFunction::domain_type::subset_handler_type > sh)
template<typename TGridFunction >
number ug::bridge::Evaluate::EvaluateAtVertex (const MathVector< TGridFunction::dim > &globPos, SmartPtr< TGridFunction > spGridFct, size_t fct, const SubsetGroup &ssGrp, typename TGridFunction::domain_type::subset_handler_type *sh)
Detailed Description
Function Documentation
template<typename TGridFunction > number ug::bridge::Evaluate::EvaluateAtClosestVertex (const MathVector< TGridFunction::dim > & pos, SmartPtr< TGridFunction > spGridFct, const char * cmp, const char * subsets, SmartPtr< typename TGridFunction::domain_type::subset_handler_type > sh)
References ug::SubsetGroup::add(), ug::SubsetGroup::add_all(), SmartPtr< T, FreePolicy >::get(), ug::TokenizeString(), and UG_THROW.
template<typename TGridFunction > number ug::bridge::Evaluate::EvaluateAtVertex (const MathVector< TGridFunction::dim > & globPos, SmartPtr< TGridFunction > spGridFct, size_t fct, const SubsetGroup & ssGrp, typename TGridFunction::domain_type::subset_handler_type * sh)
References ug::DistributedGridManager::contains_status(), ug::DoFRef(), SmartPtr< T, FreePolicy >::get(), ug::INT_H_SLAVE, ug::DistributedGridManager::is_ghost(), ug::SubsetGroup::size(), and ug::VecDistanceSq().