ug4: User Data Bridge
User Data Bridge
ugbase » Bridge » Discretization Bridge
Classes
struct ug::bridge::UserDataBridge::Functionality
Functions
template<typename TData , int dim, typename TTraits = user_data_traits<TData>>
void ug::bridge::RegisterUserDataType (Registry &reg, string grp)
template<typename TData , int dim, typename TTraits = user_data_traits<TData>>
void ug::bridge::RegisterUserDataTypeA (Registry &reg, string grp)
template<typename TData , int dim, typename TTraits = user_data_traits<TData>>
void ug::bridge::RegisterUserDataTypeB (Registry &reg, string grp)
Detailed Description
Function Documentation
RegisterUserDataType()
template<typename TData , int dim, typename TTraits = user_data_traits<TData>> void ug::bridge::RegisterUserDataType (Registry & reg, string grp)
RegisterUserDataTypeA()
template<typename TData , int dim, typename TTraits = user_data_traits<TData>> void ug::bridge::RegisterUserDataTypeA (Registry & reg, string grp)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), ug::bridge::Registry::add_function(), and name.
RegisterUserDataTypeB()
template<typename TData , int dim, typename TTraits = user_data_traits<TData>> void ug::bridge::RegisterUserDataTypeB (Registry & reg, string grp)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), and name.