ug4: Refinement Bridge
Refinement Bridge
ugbase » Bridge » Domain Bridge
Classes
struct ug::bridge::Refinement::Functionality
Functions
template<class TDomain >
static SPIRefMarkAdjuster ug::AddHorizontalAnisotropyAdjuster (IRefiner *ref, TDomain *dom)
Adds a horizontal-anisotropy-adjuster to the given refiner.
template<typename TDomain >
static SmartPtr< IRefiner > ug::CreateAdaptiveRegularDomainRefiner (TDomain *dom)
Creates an adaptive regular domain refiner.
template<class TDomain >
static SmartPtr< GlobalFracturedMediaRefiner > ug::CreateGlobalFracturedDomainRefiner (TDomain *dom)
Creates a global fractured domain refiner.
template<typename TDomain >
static SmartPtr< IRefiner > ug::GlobalDomainRefiner (TDomain *dom)
Creates a global domain refiner.
template<typename TDomain >
static SmartPtr< IRefiner > ug::HangingNodeDomainRefiner (TDomain *dom)
Creates an adaptive hanging node domain refiner.
template<class TDomain >
void ug::MarkAnisotropic_LongEdges (TDomain &dom, IRefiner &refiner, number minLen)
Marks all elements for anisotropic refienment and also marks all edges > minLen.
template<class TDomain , class TElem >
void ug::MarkForAdaption_ElementsContainingPoint (TDomain &dom, IRefiner &refiner, number x, number y, number z, std::string markType)
template<class TDomain >
void ug::MarkForAdaption_ElementsTouchingSubset (TDomain &dom, IRefiner &refiner, ISubsetHandler &sh, int subsetIndex, std::string markType)
template<class TDomain >
void ug::MarkForAdaption_ElementsTouchingSubsets (TDomain &dom, IRefiner &refiner, const char *subsets, std::string markType)
template<class TDomain >
void ug::MarkForAdaption_VerticesInCube (TDomain &dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type &min, const typename TDomain::position_type &max, std::string markType)
Marks all elements which have vertices in the given d-dimensional cube.
template<class TDomain >
void ug::MarkForAdaption_VerticesInSphere (TDomain &dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type &center, number radius, std::string markType)
Marks all vertices in the given d-dimensional sphere.
template<class TDomain >
void ug::MarkForCoarsen_ElementsByLuaCallback (TDomain &dom, SmartPtr< IRefiner > refiner, double time, const char *luaCallbackName)
static void ug::MarkForRefinement_All (SmartPtr< IRefiner > ref)
Marks all elements from refinement.
template<class TElem >
static void ug::MarkForRefinement_AllAnisotropic (SmartPtr< IRefiner > ref)
template<class TDomain >
void ug::MarkForRefinement_AnisotropicDirection (TDomain &dom, IRefiner &refiner, MathVector< TDomain::dim > &dir, number minEdgeRatio)
template<class TDomain >
void ug::MarkForRefinement_AnisotropicElements (TDomain &dom, IRefiner &refiner, number minEdgeRatio)
template<class TDomain >
void ug::MarkForRefinement_EdgeDirection (TDomain &dom, IRefiner &refiner, MathVector< TDomain::dim > &dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
template<class TDomain >
void ug::MarkForRefinement_ElementsByLuaCallback (TDomain &dom, SmartPtr< IRefiner > refiner, double time, size_t maxLvl, const char *luaCallbackName)
template<class TDomain , class TElem >
void ug::MarkForRefinement_ElementsInSphere (TDomain &dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type &center, number radius)
Marks all elements which lie completely in the given d-dimensional sphere.
template<class TDomain , class TSubsetHandler , class TElem >
void ug::MarkForRefinement_ElementsInSubset (TDomain &dom, IRefiner &refiner, TSubsetHandler &sh, int subsetIndex)
template<class elem_t >
void ug::MarkForRefinement_SubsetInterfaceElements (IRefiner &refiner, ISubsetHandler &sh)
template<class TDomain , class TElem >
void ug::MarkForRefinement_SubsetInterfaceElements (TDomain &dom, IRefiner &refiner)
template<class TDomain >
void ug::MarkForRefinement_VerticesInCube (TDomain &dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type &min, const typename TDomain::position_type &max)
template<class TDomain >
void ug::MarkForRefinement_VerticesInSphere (TDomain &dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type &center, number radius)
void ug::MarkNeighborsForAnisotropicRefinement (IRefiner &refiner, bool sideNbrsOnly)
void ug::MarkNeighborsForFullRefinement (IRefiner &refiner, bool sideNbrsOnly)
static RefinementMark ug::StringToRefinementMark (std::string markType)
Returns a refinement mark, given a string describing it.
Detailed Description
Function Documentation
AddHorizontalAnisotropyAdjuster()
template<class TDomain > static SPIRefMarkAdjuster ug::AddHorizontalAnisotropyAdjuster (IRefiner * ref, TDomain * dom) static
Adds a horizontal-anisotropy-adjuster to the given refiner.
Adds a horizontal-anisotropy-adjuster to the given refiner. The provided domain is used to obtain the used position attachment.
Note
ref has to be derived from HangingNodeRefinerBase
References ug::HangingNodeRefinerBase< TSelector >::add_ref_mark_adjuster(), make_sp(), and UG_COND_THROW.
CreateAdaptiveRegularDomainRefiner()
template<typename TDomain > static SmartPtr<IRefiner> ug::CreateAdaptiveRegularDomainRefiner (TDomain * dom) static
Creates an adaptive regular domain refiner.
Automatically chooses whether a parallel refiner is required.
References UG_THROW.
CreateGlobalFracturedDomainRefiner()
template<class TDomain > static SmartPtr<GlobalFracturedMediaRefiner> ug::CreateGlobalFracturedDomainRefiner (TDomain * dom) static
Creates a global fractured domain refiner.
References pcl::NumProcs(), ug::GlobalFracturedMediaRefiner::set_subset_handler(), and UG_THROW.
GlobalDomainRefiner()
template<typename TDomain > static SmartPtr<IRefiner> ug::GlobalDomainRefiner (TDomain * dom) static
Creates a global domain refiner.
Automatically chooses whether a parallel refiner is required.
References pcl::NumProcs().
HangingNodeDomainRefiner()
template<typename TDomain > static SmartPtr<IRefiner> ug::HangingNodeDomainRefiner (TDomain * dom) static
Creates an adaptive hanging node domain refiner.
Automatically chooses whether a parallel refiner is required.
References pcl::NumProcs(), and UG_THROW.
MarkAnisotropic_LongEdges()
template<class TDomain > void ug::MarkAnisotropic_LongEdges (TDomain & dom, IRefiner & refiner, number minLen)
Marks all elements for anisotropic refienment and also marks all edges > minLen.
References ug::Grid::associated_elements(), ug::MultiGrid::begin(), ug::EdgeLengthSq(), ug::MultiGrid::end(), ug::IRefiner::get_associated_grid(), ug::MultiGrid::has_children(), ug::IRefiner::mark(), ug::RM_ANISOTROPIC, ug::PointerConstArray< TPtr >::size(), ug::sq(), and UG_ASSERT.
MarkForAdaption_ElementsContainingPoint()
template<class TDomain , class TElem > void ug::MarkForAdaption_ElementsContainingPoint (TDomain & dom, IRefiner & refiner, number x, number y, number z, std::string markType)
References ug::ContainsPoint(), ug::IRefiner::mark(), PROFILE_FUNC, ug::StringToRefinementMark(), and ug::VecCopy().
MarkForAdaption_ElementsTouchingSubset()
template<class TDomain > void ug::MarkForAdaption_ElementsTouchingSubset (TDomain & dom, IRefiner & refiner, ISubsetHandler & sh, int subsetIndex, std::string markType)
References ug::EDGE, ug::FACE, ug::ISubsetHandler::get_subset_index(), ug::IRefiner::mark(), PROFILE_FUNC, ug::PointerConstArray< TPtr >::size(), ug::StringToRefinementMark(), and ug::VERTEX.
Referenced by ug::MarkForAdaption_ElementsTouchingSubsets().
MarkForAdaption_ElementsTouchingSubsets()
template<class TDomain > void ug::MarkForAdaption_ElementsTouchingSubsets (TDomain & dom, IRefiner & refiner, const char * subsets, std::string markType)
References ug::ISubsetHandler::get_subset_index(), ug::MarkForAdaption_ElementsTouchingSubset(), ug::TokenizeTrimString(), and UG_THROW.
MarkForAdaption_VerticesInCube()
template<class TDomain > void ug::MarkForAdaption_VerticesInCube (TDomain & dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type & min, const typename TDomain::position_type & max, std::string markType)
Marks all elements which have vertices in the given d-dimensional cube.
Make sure that TAPos is an attachment of vector_t position types.
References ug::Grid::begin(), ug::CollectAssociated(), ug::Grid::end(), SmartPtr< T, FreePolicy >::get(), PROFILE_FUNC_GROUP, and ug::StringToRefinementMark().
Referenced by ug::MarkForRefinement_VerticesInCube().
MarkForAdaption_VerticesInSphere()
template<class TDomain > void ug::MarkForAdaption_VerticesInSphere (TDomain & dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type & center, number radius, std::string markType)
Marks all vertices in the given d-dimensional sphere.
References ug::Grid::begin(), ug::CollectAssociated(), ug::Grid::end(), SmartPtr< T, FreePolicy >::get(), PROFILE_FUNC_GROUP, ug::StringToRefinementMark(), and ug::VecDistanceSq().
Referenced by ug::MarkForRefinement_VerticesInSphere().
MarkForCoarsen_ElementsByLuaCallback()
template<class TDomain > void ug::MarkForCoarsen_ElementsByLuaCallback (TDomain & dom, SmartPtr< IRefiner > refiner, double time, const char * luaCallbackName)
References ug::CalculateCenter(), PROFILE_FUNC, ug::RM_COARSEN, ug::LuaFunction< TData, TDataIn >::set_lua_callback(), UG_LOG, and ug::VecCopy().
MarkForRefinement_All()
static void ug::MarkForRefinement_All (SmartPtr< IRefiner > ref) static
Marks all elements from refinement.
marks face and for anisotropic refinement, if it contains edges below given sizeRatio. These edges are also marked.
Returns
true, if face has been marked for anisotropic refinement. This is the case, when one of its edges has been marked for refinement. If used in a parallel environment only elements on the calling procs are marked.
References ug::Grid::edges_begin(), ug::Grid::edges_end(), ug::Grid::faces_begin(), ug::Grid::faces_end(), PROFILE_FUNC_GROUP, UG_LOG, ug::Grid::vertices_begin(), ug::Grid::vertices_end(), ug::Grid::volumes_begin(), and ug::Grid::volumes_end().
Referenced by ug::bridge::Refinement::Functionality::Common().
MarkForRefinement_AllAnisotropic()
template<class TElem > static void ug::MarkForRefinement_AllAnisotropic (SmartPtr< IRefiner > ref) static
References ug::Grid::begin(), ug::Grid::end(), PROFILE_FUNC_GROUP, ug::RM_ANISOTROPIC, and UG_LOG.
MarkForRefinement_AnisotropicDirection()
template<class TDomain > void ug::MarkForRefinement_AnisotropicDirection (TDomain & dom, IRefiner & refiner, MathVector< TDomain::dim > & dir, number minEdgeRatio)
References ug::Grid::associated_elements(), ug::EdgeLengthSq(), end_for, for_each_in_vec, ug::MultiGrid::has_children(), lg_end_for, lg_for_each_template, ug::IRefiner::mark(), ug::RM_CLOSURE, ug::RM_REFINE, ug::SMALL, ug::sq(), ug::VecDot(), ug::VecNormalize(), ug::VecSubtract(), and ug::EdgeVertices::vertex().
MarkForRefinement_AnisotropicElements()
template<class TDomain > void ug::MarkForRefinement_AnisotropicElements (TDomain & dom, IRefiner & refiner, number minEdgeRatio)
References ug::Grid::begin(), ug::Grid::end(), and ug::MarkForAnisotropicRefinement().
MarkForRefinement_EdgeDirection()
template<class TDomain > void ug::MarkForRefinement_EdgeDirection (TDomain & dom, IRefiner & refiner, MathVector< TDomain::dim > & dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
References ug::MultiGrid::begin(), ug::MultiGrid::end(), and ug::MarkForRefinementByDirection().
MarkForRefinement_ElementsByLuaCallback()
template<class TDomain > void ug::MarkForRefinement_ElementsByLuaCallback (TDomain & dom, SmartPtr< IRefiner > refiner, double time, size_t maxLvl, const char * luaCallbackName)
THE NOT HIGHLY SUCCESSFUL IMPLEMENTATION OF THIS METHOD LEAD TO NEW INSIGHT. A NEW ANISOTROPIC REFINEMENT STRATEGY WILL BE IMPLEMENTED, WHICH WILL ALSO LEAD TO A REIMPLEMENTATION OF THIS METHOD. BEST NOT TO USE IT UNTIL THEN.
The sizeRatio determines Whether a face or a volume is considered anisotropic. Make sure that the sizeRatio is in the interval [0, 1]. If the ratio of the shortest edge to an other edge falls below the given threshold, then the associated face is considered anisotropic and the longer edge will be marked. The face itself will then be marked for anisotropic refinement. The same technique is applied to volumes, this time however the ratio between face-areas is considered when judging whether a volume is anisotropic.
VOLUME MARKS ARE CURRENTLY DISABLED
Note that this algorithm only really works for a serial environment.
Todo:
improve it so that it works in parallel, too. A specialization of HangingNodeRefiner may be required for this.
Todo:
activate and improve volume marks
References ug::CalculateCenter(), ug::EdgeLengthSq(), PROFILE_FUNC, ug::LuaFunction< TData, TDataIn >::set_lua_callback(), ug::PointerConstArray< TPtr >::size(), and ug::VecCopy().
MarkForRefinement_ElementsInSphere()
template<class TDomain , class TElem > void ug::MarkForRefinement_ElementsInSphere (TDomain & dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type & center, number radius)
Marks all elements which lie completely in the given d-dimensional sphere.
Valid parameters for TElem are Edge, Face, Volume.
References ug::Grid::begin(), ug::Grid::end(), SmartPtr< T, FreePolicy >::get(), PROFILE_FUNC_GROUP, and ug::VecDistanceSq().
MarkForRefinement_ElementsInSubset()
template<class TDomain , class TSubsetHandler , class TElem > void ug::MarkForRefinement_ElementsInSubset (TDomain & dom, IRefiner & refiner, TSubsetHandler & sh, int subsetIndex)
References ug::GridObjectCollection::begin(), ug::GridObjectCollection::end(), ug::IRefiner::mark(), ug::GridObjectCollection::num_levels(), and PROFILE_FUNC.
Referenced by ug::bridge::Refinement::Functionality::Domain().
MarkForRefinement_SubsetInterfaceElements() [1/2]
template<class elem_t > void ug::MarkForRefinement_SubsetInterfaceElements (IRefiner & refiner, ISubsetHandler & sh)
References ug::Grid::attach_to(), ug::ISubsetHandler::get_subset_index(), ug::IRefiner::grid(), ug::ISubsetHandler::grid(), ug::IRefiner::mark(), PCL_RO_MAX, PCL_RO_MIN, ug::SetAttachmentValues(), ug::PointerConstArray< TPtr >::size(), and UG_COND_THROW.
MarkForRefinement_SubsetInterfaceElements() [2/2]
template<class TDomain , class TElem > void ug::MarkForRefinement_SubsetInterfaceElements (TDomain & dom, IRefiner & refiner)
MarkForRefinement_VerticesInCube()
template<class TDomain > void ug::MarkForRefinement_VerticesInCube (TDomain & dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type & min, const typename TDomain::position_type & max)
References ug::MarkForAdaption_VerticesInCube().
MarkForRefinement_VerticesInSphere()
template<class TDomain > void ug::MarkForRefinement_VerticesInSphere (TDomain & dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type & center, number radius)
References ug::MarkForAdaption_VerticesInSphere().
MarkNeighborsForAnisotropicRefinement()
void ug::MarkNeighborsForAnisotropicRefinement (IRefiner & refiner, bool sideNbrsOnly)
References ug::IRefiner::mark_neighborhood(), and ug::RM_ANISOTROPIC.
Referenced by ug::bridge::Refinement::Functionality::Common().
MarkNeighborsForFullRefinement()
void ug::MarkNeighborsForFullRefinement (IRefiner & refiner, bool sideNbrsOnly)
References ug::IRefiner::mark_neighborhood(), and ug::RM_REFINE.
Referenced by ug::bridge::Refinement::Functionality::Common().
StringToRefinementMark()
static RefinementMark ug::StringToRefinementMark (std::string markType) static
Returns a refinement mark, given a string describing it.
Valid parameters are: "refine", "coarsen"
References ug::RM_COARSEN, ug::RM_NONE, ug::RM_REFINE, ug::TrimString(), and UG_THROW.
Referenced by ug::MarkForAdaption_ElementsContainingPoint(), ug::MarkForAdaption_ElementsTouchingSubset(), ug::MarkForAdaption_VerticesInCube(), and ug::MarkForAdaption_VerticesInSphere().