ug4: common Utility
common Utility
Scripts » Lua Utility Scripts
Functions
function common head (list, last)
function common path_sep ()
function common printf (s,...)
function common printfn (s,...)
function common scandir (directory_, extension_)
function common scandir_ugx (directory, extension)
function common scandir_xml (directory, extension)
function string split_path (sep, n)
function common sprintf (s,...)
function common sprintfn (s,...)
function common tail (list, first)
Detailed Description
Utility functions for common operations Questions? steph.nosp@m.an.g.nosp@m.rein@.nosp@m.gcsc.nosp@m..uni-.nosp@m.fran.nosp@m.kfurt.nosp@m..de
Function Documentation
head()
function common head (list , last)
head
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / common_util.lua :89-91
function common:head(list, last)
   return { table.remove({select(1, unpack(list))}, last) }
end
path_sep()
function common path_sep ()
returns the path separator used by the current OS
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / common_util.lua :160-162
function common:path_sep()
   return package.config:sub(1,1)
end
printf()
function common printf (s , ...)
unpacks a list of lists (trivial recursion to unpack all levels if needed) emulates printf
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / common_util.lua :64-66
function common:printf(s, ...)
   print(prepare(s, ...))
end
Referenced by ug::bridge::CompletionFunction(), ug::bridge::GetGlobalFunctionInfo(), ug::bridge::GetMemberFunctionInfo(), ug::CUDAManager::init(), and ug::bridge::print().
printfn()
function common printfn (s , ...)
emulates printf with newline appended
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / common_util.lua :69-71
function common:printfn(s, ...)
   print(prepare(s .. "\n", ...))
end
scandir()
function common scandir (directory_ , extension_)
lists all files in a directory, then stores it into a table
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / common_util.lua :104-157
scandir_ugx()
function common scandir_ugx (directory , extension)
list all ugx files
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / common_util.lua :167-169
function common:scandir_ugx(directory, extension)
   return common:scandir(directory, "ugx")
end
scandir_xml()
function common scandir_xml (directory , extension)
list all xml files
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / common_util.lua :174-176
function common:scandir_xml(directory, extension)
   return common:scandir(directory, "xml")
end
split_path()
function string split_path (sep , n)
split filename by delimiter (defaults to slash) and takes the n-th group
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / common_util.lua :94-99
function string:split_path(sep, n)
   local sep, fields = sep or "/", {}
   local pat = string.format("([^%s]+)", sep)
   self:gsub(pat, function(z) fields[#fields+1] = z end)
   return fields[n or #fields]
end
sprintf()
function common sprintf (s , ...)
emulates sprintf
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / common_util.lua :74-76
function common:sprintf(s, ...)
   return prepare(s, ...)
end
Referenced by ug::LocalSchurComplement< TAlgebra >::apply(), ug::NestedIterationSolver< TDomain, TAlgebra >::apply(), ug::NewtonSolver< TAlgebra >::apply(), ug::NLGaussSeidelSolver< TDomain, TAlgebra >::apply(), ug::NLJacobiSolver< TAlgebra >::apply(), ug::AutoLinearSolver< TVector >::apply_return_defect(), ug::GridWriterUGX::create_constrained_vertex_node(), ug::GridWriterUGX::create_vertex_node(), ug::CG< TVector >::enter_precond_debug_section(), ug::LinearSolver< TVector >::enter_precond_debug_section(), ug::BiCGStab< TVector >::enter_precond_debug_section(), ug::ConnectionViewer::GetParallelName(), ug::script::LuaCallHook(), ug::bridge::lua::LuaToStringDefault(), ug::TarHeader::set_checksum(), ug::TarHeader::set_filesize(), ug::TarHeader::TarHeader(), ug::FETISolver< TAlgebra >::write_debug(), ug::NLGaussSeidelSolver< TDomain, TAlgebra >::write_debug(), ug::NLJacobiSolver< TAlgebra >::write_debug(), ug::NewtonSolver< TAlgebra >::write_debug(), ug::LinearSolver< TVector >::write_debugXCD(), ug::CG< TVector >::write_debugXR(), ug::BiCGStab< TVector >::write_debugXR(), ug::ConnectionViewer::WriteMatrixPar(), and ug::WriteVectorCSV().
sprintfn()
function common sprintfn (s , ...)
emulates sprintfn
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / common_util.lua :79-81
function common:sprintfn(s, ...)
   return prepare(s .. "\n" , ...)
end
tail()
function common tail (list , first)
tail
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / common_util.lua :84-86
function common:tail(list, first)
    return { select(first or 10, unpack(list)) }
end