ug4: CompileInfo
CompileInfo
ugbase
providing version number and build information
Functions
const char * ug::UGBuildHost ()
const char * ug::UGCompileDate ()
const char * ug::UGGitRevision ()
const char * ug::UGSvnRevision ()
Detailed Description
providing version number and build information
Function Documentation
UGBuildHost()
UG_API const char * ug::UGBuildHost ()
References ug::UG_BUILD_HOST.
Referenced by ug::bridge::GetBuildHostname(), and ugshell_print_header().
UGCompileDate()
UG_API const char * ug::UGCompileDate ()
References ug::UG_COMPILE_DATE.
Referenced by ug::bridge::GetCompileDate(), Java_edu_gcsc_vrl_ug_UG__1getCompileDate(), and ugshell_print_header().
UGGitRevision()
UG_API const char * ug::UGGitRevision ()
References ug::UG_GIT_REVISION.
Referenced by ug::bridge::GetGITRevision(), and ugshell_print_header().
UGSvnRevision()
UG_API const char * ug::UGSvnRevision ()
References ug::UG_SVN_REVISION.
Referenced by ug::bridge::GetSVNRevision(), and ug::vrl::svnRevision().