ug4: ugbase/bindings/lua/info_commands.cpp File Reference
info_commands.cpp File Reference
#include <iomanip>
#include "bindings/lua/lua_util.h"
#include "bindings/lua/bindings_lua.h"
#include "bridge/bridge.h"
#include "bridge/util.h"
#include "registry/class_helper.h"
#include "common/util/sort_util.h"
#include "common/util/string_util.h"
#include "lua_stack_check.h"
#include "registry/class_name_provider.h"
#include "common/util/stringify.h"
#include "common/util/string_table_stream.h"
#include "common/profiler/profiler.h"
#include "bindings/lua/externals/lua/lstate.h"
#include "info_commands.h"
Namespaces
ug
the ug namespace
ug::bridge
Functions
bool ug::bridge::ClassInstantiations (const char *classname)
this function prints all objects which are of a certain class
string ug::bridge::ClassUsage (const char *classname)
void ug::bridge::EnableLUA2C (bool b)
void ug::bridge::EnableLUA2VM (bool b)
string ug::bridge::FunctionInfo (lua_State *L, bool bComplete, const char *functionName=NULL)
prints out information for a lua function (a function defined in lua script)
std::string get_gcc_backtrace ()
const ClassNameNode * ug::bridge::GetClassNameNode (lua_State *L, int index)
const std::vector< const char * > * ug::bridge::GetClassNames (lua_State *L, const char *name)
const std::vector< const char * > * ug::bridge::GetClassNames (lua_State *L, int index)
string ug::bridge::GetFileLinesLUA (const char *filename, size_t fromline, size_t toline)
std::string ug::bridge::GetLuaFileAndLine (lua_State *L)
returns the current file and line (
bool ug::bridge::GetLuaFileAndLine (lua_State *L, std::string &file, size_t &line)
returns the current file and line (
std::string ug::bridge::GetLuaFileAndLineNumber (lua_State *L)
returns the current file and line-number
void ug::bridge::GetLuaGlobal_classInstantiations (std::vector< std::string > &classInstantiations)
void ug::bridge::GetLuaGlobal_functions (std::vector< std::string > &functions)
void ug::bridge::GetLuaGlobal_internalFunctions (std::vector< std::string > &internalFunctions)
void ug::bridge::GetLuaGlobal_luaObjects (std::vector< std::string > &luaObjects)
void ug::bridge::GetLuaGlobal_scriptFunctions (std::vector< std::string > &scriptFunctions)
void ug::bridge::GetLuaGlobals (std::vector< std::string > *functions, std::vector< std::string > *internalFunctions, std::vector< std::string > *scriptFunctions, std::vector< std::string > *luaObjects, std::vector< std::string > *classInstantiations)
function to list all objects of the default LUA state
std::string ug::bridge::GetLuaLine (lua_State *L)
returns the current line-content
bool ug::bridge::GetLuaNamespace (lua_State *L, string name)
searches for a namespaces (lists) and pushes it onto the stack
string ug::bridge::GetLUAScriptFunctionDefined (const char *functionName)
returns file and line of defined script function
string ug::bridge::GetLuaTypeString (lua_State *L, int index)
void ug::bridge::InitSignals ()
void lua_backtrace ()
string ug::bridge::LuaClassMethodInfo (lua_State *L, int index, const ExportedMethod &thefunc)
prints out information for a method of a class
string ug::bridge::LuaCurrentLine (lua_State *L)
bool ug::bridge::LuaGetBoolean (lua_State *L, const char *name, bool notAvailable)
returns a boolean to a lua-variable.
void ug::bridge::LuaGetLastLine (lua_State *L, lua_Debug entry)
double ug::bridge::LuaGetNumber (lua_State *L, const char *name, double notAvailable)
returns an integer to a lua-variable.
string ug::bridge::LuaGetScriptFunctionString (lua_State *L, int index=-1)
prints the source of a lua script function which is on top of the stack
string ug::bridge::LuaGetString (lua_State *L, const char *name, const char *notAvailable)
returns the string to a lua-variable.
void ug::bridge::LuaList ()
void ug::bridge::LuaList_cfunctions ()
void ug::bridge::LuaList_classes ()
void ug::bridge::LuaList_classInstantiations ()
void ug::bridge::LuaList_internalFunctions ()
void ug::bridge::LuaList_luaObjects ()
void ug::bridge::LuaList_scriptFunctions ()
void ug::bridge::LuaPrintTable (lua_State *L, size_t iSpace, int index)
prints the source of a lua script function which is on top of the stack
void ug::bridge::LuaStackTrace (int fromlevel)
prints information about lua's call stack (file:line source).
std::string ug::bridge::LuaStackTraceString ()
string ug::bridge::LuaStackTraceString (lua_State *L, int fromLevel=0, int toLevel=-1)
prints information about lua's call stack (file:line source).
bool ug::bridge::RegisterInfoCommands (bridge::Registry &reg, const char *grp)
registers info commands TypeInfo, ClassUsage and others
bool ug::bridge::RegisterSerializationCommands (Registry &reg, const char *parentGroup)
bool ug::bridge::ScriptHasClass (const char *classname)
bool ug::bridge::ScriptHasClassGroup (const char *classname)
void ug::bridge::ScriptPrintClassHierarchy (const char *classname)
void ug::bridge::ScriptPrintClassUsage (const char *classname)
void ug::bridge::SetLuaNamespace (string name, string value)
void ug::bridge::SetLuaNamespaceInTable (string name, string value)
void shiny_backtrace ()
void ug_backtrace ()
int ug::bridge::UGTypeInfo (const char *p)
Prints info to a lua type.
Detailed Description
Author
Martin Rupp
Date
15.10.2010
Goethe-Center for Scientific Computing 2010.
Comfort functions for the lua ug shell. example: TypeInfo("
Function Documentation
get_gcc_backtrace()
std::string get_gcc_backtrace ()
References ug::demangle_block().
Referenced by gcc_backtrace().
lua_backtrace()
void lua_backtrace ()
References ug::script::IsLUADebug(), ug::bridge::LuaStackTraceString(), and UG_LOG.
Referenced by ug_backtrace().
shiny_backtrace()
void shiny_backtrace ()
References name, p, and UG_LOG.
Referenced by ug_backtrace().
ug_backtrace()
void ug_backtrace ()
References gcc_backtrace(), lua_backtrace(), and shiny_backtrace().