ug4: ugbase/lib_algebra/vector_interface/ivector_vec_functions.h File Reference
ivector_vec_functions.h File Reference
Functions
void VecAdd (double a1, IVector &v1, double a2, const IVector &v2)
void VecAdd (double a1, IVector &v1, double a2, const IVector &v2, double a3, const IVector &v3)
void VecAdd (double a1, IVector &v1, double a2, const IVector &v2, double a3, const IVector &v3, double a4, const IVector &v4)
template<typename T >
void VecAdd (double a1, T &v1, double a2, const IVector &v2)
template<typename T >
void VecAdd (double a1, T &v1, double a2, const IVector &v2, double a3, const IVector &v3)
template<typename T >
void VecAdd (double a1, T &v1, double a2, const IVector &v2, double a3, const IVector &v3, double a4, const IVector &v4)
double VecNorm (const IVector &v1)
double VecNorm2 (const IVector &v1)
double VecProd (const IVector &v1, const IVector &v2)
template<typename T >
double VecProd (T &v1, IVector &v2)
Function Documentation
VecAdd() [1/6]
void VecAdd (double a1, IVector & v1, double a2, const IVector & v2)
VecAdd() [2/6]
void VecAdd (double a1, IVector & v1, double a2, const IVector & v2, double a3, const IVector & v3)
VecAdd() [3/6]
void VecAdd (double a1, IVector & v1, double a2, const IVector & v2, double a3, const IVector & v3, double a4, const IVector & v4)
VecAdd() [4/6]
template<typename T > void VecAdd (double a1, T & v1, double a2, const IVector & v2) inline
Referenced by VecAdd().
VecAdd() [5/6]
template<typename T > void VecAdd (double a1, T & v1, double a2, const IVector & v2, double a3, const IVector & v3) inline
References VecAdd().
VecAdd() [6/6]
template<typename T > void VecAdd (double a1, T & v1, double a2, const IVector & v2, double a3, const IVector & v3, double a4, const IVector & v4) inline
References VecAdd().
VecNorm()
double VecNorm (const IVector & v1)
VecNorm2()
double VecNorm2 (const IVector & v1)
Referenced by ug::IVector_AlgebraDownCastTo< TVec >::norm2().
VecProd() [1/2]
double VecProd (const IVector & v1, const IVector & v2)
VecProd() [2/2]
template<typename T > double VecProd (T & v1, IVector & v2) inline