ug4: ugbase/bindings/lua/compiler/lexer.cpp File Reference
lexer.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include "lua_parser_class.h"
#include "parser.hpp"
#include <unistd.h>
Classes
struct yy_buffer_state
struct yy_trans_info
Macros
#define BEGIN (yy_start) = 1 + 2 *
#define ECHO fwrite(ug4_lua_YY_text, ug4_lua_YY_leng, 1, ug4_lua_YY_out)
#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
#define FLEX_BETA
#define FLEX_SCANNER
#define FLEXINT_H
#define INITIAL 0
#define INT16_MAX (32767)
#define INT16_MIN (-32767-1)
#define INT32_MAX (2147483647)
#define INT32_MIN (-2147483647-1)
#define INT8_MAX (127)
#define INT8_MIN (-128)
#define REJECT reject_used_but_not_detected
#define THE_PREFIX ug4_lua_YY_
#define UINT16_MAX (65535U)
#define UINT32_MAX (4294967295U)
#define UINT8_MAX (255U)
#define unput(c) yyunput(c, (yytext_ptr))
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
#define YY_BREAK break;
#define YY_BUF_SIZE 16384
#define YY_BUFFER_EOF_PENDING 2
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
#define yy_create_buffer ug4_lua_YY__create_buffer
#define YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]
#define YY_DECL int ug4_lua_YY_lex (void)
#define YY_DECL_IS_OURS 1
#define yy_delete_buffer ug4_lua_YY__delete_buffer
#define YY_DO_BEFORE_ACTION
#define YY_END_OF_BUFFER 39
#define YY_END_OF_BUFFER_CHAR 0
#define YY_EXIT_FAILURE 2
#define YY_EXTRA_TYPE void *
#define YY_FATAL_ERROR(msg) yy_fatal_error(msg)
#define yy_flex_debug ug4_lua_YY__flex_debug
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#define yy_flush_buffer ug4_lua_YY__flush_buffer
#define YY_FLUSH_BUFFER ug4_lua_YY__flush_buffer(YY_CURRENT_BUFFER)
#define yy_init_buffer ug4_lua_YY__init_buffer
#define YY_INPUT(buf, result, max_size)
#define YY_INT_ALIGNED short int
#define YY_LESS_LINENO(n)
#define yy_load_buffer_state ug4_lua_YY__load_buffer_state
#define YY_MORE_ADJ 0
#define yy_new_buffer ug4_lua_YY__create_buffer
#define YY_NEW_FILE ug4_lua_YY_restart(ug4_lua_YY_in)
#define YY_NULL 0
#define YY_NUM_RULES 38
#define YY_READ_BUF_SIZE 8192
#define YY_RESTORE_YY_MORE_OFFSET
#define YY_RULE_SETUP YY_USER_ACTION
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
#define yy_set_bol(at_bol)
#define yy_set_interactive(is_interactive)
#define YY_START (((yy_start) - 1) / 2)
#define YY_START_STACK_INCR 25
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
#define YY_STRUCT_YY_BUFFER_STATE
#define yy_switch_to_buffer ug4_lua_YY__switch_to_buffer
#define YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_SIZE_T
#define YY_USER_ACTION
#define yyalloc ug4_lua_YY_alloc
#define yyconst
#define yyerror ug4_lua_YY_error
#define yyfree ug4_lua_YY_free
#define yyin ug4_lua_YY_in
#define yyleng ug4_lua_YY_leng
#define yyless(n)
#define yyless(n)
#define yylex ug4_lua_YY_lex
#define yylineno ug4_lua_YY_lineno
#define yylval ug4_lua_YY_lval
#define yymore() yymore_used_but_not_detected
#define yyout ug4_lua_YY_out
#define yyrealloc ug4_lua_YY_realloc
#define yyrestart ug4_lua_YY_restart
#define YYSTATE YY_START
#define YYTABLES_NAME "yytables"
#define yyterminate() return YY_NULL
#define yytext ug4_lua_YY_text
#define yytext_ptr ug4_lua_YY_text
#define yywrap ug4_lua_YY_wrap
Typedefs
typedef short int flex_int16_t
typedef int flex_int32_t
typedef signed char flex_int8_t
typedef unsigned short int flex_uint16_t
typedef unsigned int flex_uint32_t
typedef unsigned char flex_uint8_t
typedef struct yy_buffer_state * YY_BUFFER_STATE
typedef unsigned char YY_CHAR
typedef size_t yy_size_t
typedef int yy_state_type
Functions
if (!(yy_init))
static int input (void)
int isatty (int)
YY_BUFFER_STATE ug4_lua_YY__create_buffer (FILE *file, int size)
void ug4_lua_YY__delete_buffer (YY_BUFFER_STATE b)
void ug4_lua_YY__flush_buffer (YY_BUFFER_STATE b)
static void ug4_lua_YY__init_buffer (YY_BUFFER_STATE b, FILE *file)
static void ug4_lua_YY__load_buffer_state (void)
YY_BUFFER_STATE ug4_lua_YY__scan_buffer (char *base, yy_size_t size)
YY_BUFFER_STATE ug4_lua_YY__scan_bytes (yyconst char *bytes, yy_size_t len)
YY_BUFFER_STATE ug4_lua_YY__scan_string (yyconst char *yy_str)
void ug4_lua_YY__switch_to_buffer (YY_BUFFER_STATE new_buffer)
void * ug4_lua_YY_alloc (yy_size_t)
static void ug4_lua_YY_ensure_buffer_stack (void)
void ug4_lua_YY_free (void *)
int ug4_lua_YY_get_debug (void)
YY_EXTRA_TYPE ug4_lua_YY_get_extra (void)
FILE * ug4_lua_YY_get_in (void)
yy_size_t ug4_lua_YY_get_leng (void)
int ug4_lua_YY_get_lineno (void)
FILE * ug4_lua_YY_get_out (void)
char * ug4_lua_YY_get_text (void)
int ug4_lua_YY_lex (void)
int ug4_lua_YY_lex_destroy (void)
void ug4_lua_YY_pop_buffer_state (void)
void ug4_lua_YY_push_buffer_state (YY_BUFFER_STATE new_buffer)
void * ug4_lua_YY_realloc (void *, yy_size_t)
void ug4_lua_YY_restart (FILE *input_file)
void ug4_lua_YY_set_debug (int debug_flag)
void ug4_lua_YY_set_extra (YY_EXTRA_TYPE user_defined)
void ug4_lua_YY_set_in (FILE *in_str)
void ug4_lua_YY_set_lineno (int line_number)
void ug4_lua_YY_set_out (FILE *out_str)
int ug4_lua_YY_wrap (void)
while (1)
static void yy_fatal_error (yyconst char *msg)
static void yy_fatal_error (yyconst char msg[])
static int yy_get_next_buffer (void)
static yy_state_type yy_get_previous_state (void)
static int yy_init_globals (void)
static yy_state_type yy_try_NUL_trans (yy_state_type current_state)
void yyerror (const char *)
static void yyunput (int c, char *buf_ptr)
static void yyunput (int c, register char *yy_bp)
Variables
LUAParserClass * globalP
int ug4_lua_YY__flex_debug = 0
FILE * ug4_lua_YY_in = (FILE *) 0
yy_size_t ug4_lua_YY_leng
int ug4_lua_YY_lineno = 1
FILE * ug4_lua_YY_out = (FILE *) 0
char * ug4_lua_YY_text
static yyconst flex_int16_t yy_accept [120]
register int yy_act
static yyconst flex_int16_t yy_base [122]
register char * yy_bp
static YY_BUFFER_STATE * yy_buffer_stack = 0
static size_t yy_buffer_stack_max = 0
static size_t yy_buffer_stack_top = 0
static char * yy_c_buf_p = (char *) 0
static yyconst flex_int16_t yy_chk [196]
register char * yy_cp
YY_DECL
static yyconst flex_int16_t yy_def [122]
static int yy_did_buffer_switch_on_eof
static yyconst flex_int32_t yy_ec [256]
static char yy_hold_char
static int yy_init = 0
static char * yy_last_accepting_cpos
static yy_state_type yy_last_accepting_state
static yyconst flex_int32_t yy_meta [39]
static yy_size_t yy_n_chars
static yyconst flex_int16_t yy_nxt [196]
static int yy_start = 0
Macro Definition Documentation
BEGIN
#define BEGIN (yy_start) = 1 + 2 *
ECHO
#define ECHO fwrite(ug4_lua_YY_text, ug4_lua_YY_leng, 1, ug4_lua_YY_out)
EOB_ACT_CONTINUE_SCAN
#define EOB_ACT_CONTINUE_SCAN 0
EOB_ACT_END_OF_FILE
#define EOB_ACT_END_OF_FILE 1
EOB_ACT_LAST_MATCH
#define EOB_ACT_LAST_MATCH 2
FLEX_BETA
#define FLEX_BETA
FLEX_SCANNER
#define FLEX_SCANNER
FLEXINT_H
#define FLEXINT_H
INITIAL
#define INITIAL 0
INT16_MAX
#define INT16_MAX (32767)
INT16_MIN
#define INT16_MIN (-32767-1)
INT32_MAX
#define INT32_MAX (2147483647)
INT32_MIN
#define INT32_MIN (-2147483647-1)
INT8_MAX
#define INT8_MAX (127)
INT8_MIN
#define INT8_MIN (-128)
REJECT
#define REJECT reject_used_but_not_detected
THE_PREFIX
#define THE_PREFIX ug4_lua_YY_
UINT16_MAX
#define UINT16_MAX (65535U)
UINT32_MAX
#define UINT32_MAX (4294967295U)
UINT8_MAX
#define UINT8_MAX (255U)
unput
#define unput (c) yyunput(c, (yytext_ptr))
YY_AT_BOL
#define YY_AT_BOL () (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)
YY_BREAK
#define YY_BREAK break;
YY_BUF_SIZE
#define YY_BUF_SIZE 16384
YY_BUFFER_EOF_PENDING
#define YY_BUFFER_EOF_PENDING 2
YY_BUFFER_NEW
#define YY_BUFFER_NEW 0
YY_BUFFER_NORMAL
#define YY_BUFFER_NORMAL 1
yy_create_buffer
#define yy_create_buffer ug4_lua_YY__create_buffer
YY_CURRENT_BUFFER
#define YY_CURRENT_BUFFER
Value:
((yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
YY_CURRENT_BUFFER_LVALUE
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]
YY_DECL
#define YY_DECL int ug4_lua_YY_lex (void)
YY_DECL_IS_OURS
#define YY_DECL_IS_OURS 1
yy_delete_buffer
#define yy_delete_buffer ug4_lua_YY__delete_buffer
YY_DO_BEFORE_ACTION
#define YY_DO_BEFORE_ACTION
Value:
(yytext_ptr) = yy_bp; \
  ug4_lua_YY_leng = (yy_size_t) (yy_cp - yy_bp); \
  (yy_hold_char) = *yy_cp; \
  *yy_cp = '\0'; \
  (yy_c_buf_p) = yy_cp;
YY_END_OF_BUFFER
#define YY_END_OF_BUFFER 39
YY_END_OF_BUFFER_CHAR
#define YY_END_OF_BUFFER_CHAR 0
YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
YY_FATAL_ERROR
#define YY_FATAL_ERROR (msg) yy_fatal_error(msg)
yy_flex_debug
#define yy_flex_debug ug4_lua_YY__flex_debug
YY_FLEX_MAJOR_VERSION
#define YY_FLEX_MAJOR_VERSION 2
YY_FLEX_MINOR_VERSION
#define YY_FLEX_MINOR_VERSION 5
YY_FLEX_SUBMINOR_VERSION
#define YY_FLEX_SUBMINOR_VERSION 35
yy_flush_buffer
#define yy_flush_buffer ug4_lua_YY__flush_buffer
YY_FLUSH_BUFFER
#define YY_FLUSH_BUFFER ug4_lua_YY__flush_buffer(YY_CURRENT_BUFFER)
yy_init_buffer
#define yy_init_buffer ug4_lua_YY__init_buffer
YY_INPUT
#define YY_INPUT (buf, result, max_size)
Value:
if (YY_CURRENT_BUFFER_LVALUE->yy_is_interactive) \
    { \
    int c = '*'; \
    yy_size_t n; \
    for ( n = 0; n < max_size && \
           (c = getc( ug4_lua_YY_in )) != EOF && c != '\n'; ++n ) \
      buf[n] = (char) c; \
    if ( c == '\n' ) \
      buf[n++] = (char) c; \
    if ( c == EOF && ferror( ug4_lua_YY_in ) ) \
      YY_FATAL_ERROR( "input in flex scanner failed" ); \
    result = n; \
    } \
  else \
    { \
    errno=0; \
    while ( (result = fread(buf, 1, max_size, ug4_lua_YY_in))==0 && ferror(ug4_lua_YY_in)) \
      { \
      if( errno != EINTR) \
        { \
        YY_FATAL_ERROR( "input in flex scanner failed" ); \
        break; \
        } \
      errno=0; \
      clearerr(ug4_lua_YY_in); \
      } \
    }\
\
YY_INT_ALIGNED
#define YY_INT_ALIGNED short int
YY_LESS_LINENO
#define YY_LESS_LINENO (n)
yy_load_buffer_state
#define yy_load_buffer_state ug4_lua_YY__load_buffer_state
YY_MORE_ADJ
#define YY_MORE_ADJ 0
yy_new_buffer
#define yy_new_buffer ug4_lua_YY__create_buffer
YY_NEW_FILE
#define YY_NEW_FILE ug4_lua_YY_restart(ug4_lua_YY_in)
YY_NULL
#define YY_NULL 0
YY_NUM_RULES
#define YY_NUM_RULES 38
YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
YY_RESTORE_YY_MORE_OFFSET
#define YY_RESTORE_YY_MORE_OFFSET
YY_RULE_SETUP
#define YY_RULE_SETUP YY_USER_ACTION
YY_SC_TO_UI
#define YY_SC_TO_UI (c) ((unsigned int) (unsigned char) c)
yy_set_bol
#define yy_set_bol (at_bol)
Value:
{ \
  if ( ! YY_CURRENT_BUFFER ){\
        ug4_lua_YY_ensure_buffer_stack (); \
    YY_CURRENT_BUFFER_LVALUE =    \
            ug4_lua_YY__create_buffer(ug4_lua_YY_in,YY_BUF_SIZE ); \
  } \
  YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
  }
yy_set_interactive
#define yy_set_interactive (is_interactive)
Value:
{ \
  if ( ! YY_CURRENT_BUFFER ){ \
        ug4_lua_YY_ensure_buffer_stack (); \
    YY_CURRENT_BUFFER_LVALUE =    \
            ug4_lua_YY__create_buffer(ug4_lua_YY_in,YY_BUF_SIZE ); \
  } \
  YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
  }
YY_START
#define YY_START (((yy_start) - 1) / 2)
YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
YY_STATE_BUF_SIZE
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))
YY_STATE_EOF
#define YY_STATE_EOF (state) (YY_END_OF_BUFFER + state + 1)
YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
yy_switch_to_buffer
#define yy_switch_to_buffer ug4_lua_YY__switch_to_buffer
YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
YY_USER_ACTION
#define YY_USER_ACTION
yyalloc
#define yyalloc ug4_lua_YY_alloc
yyconst
#define yyconst
yyerror
#define yyerror ug4_lua_YY_error
yyfree
#define yyfree ug4_lua_YY_free
yyin
#define yyin ug4_lua_YY_in
yyleng
#define yyleng ug4_lua_YY_leng
yyless [1/2]
#define yyless (n)
Value:
do \
    { \
    /* Undo effects of setting up ug4_lua_YY_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
    *yy_cp = (yy_hold_char); \
    YY_RESTORE_YY_MORE_OFFSET \
    (yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
    YY_DO_BEFORE_ACTION; /* set up ug4_lua_YY_text again */ \
    } \
  while ( 0 )
yyless [2/2]
#define yyless (n)
Value:
do \
    { \
    /* Undo effects of setting up ug4_lua_YY_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
    ug4_lua_YY_text[ug4_lua_YY_leng] = (yy_hold_char); \
    (yy_c_buf_p) = ug4_lua_YY_text + yyless_macro_arg; \
    (yy_hold_char) = *(yy_c_buf_p); \
    *(yy_c_buf_p) = '\0'; \
    ug4_lua_YY_leng = yyless_macro_arg; \
    } \
  while ( 0 )
yylex
#define yylex ug4_lua_YY_lex
yylineno
#define yylineno ug4_lua_YY_lineno
yylval
#define yylval ug4_lua_YY_lval
yymore
#define yymore () yymore_used_but_not_detected
yyout
#define yyout ug4_lua_YY_out
yyrealloc
#define yyrealloc ug4_lua_YY_realloc
yyrestart
#define yyrestart ug4_lua_YY_restart
YYSTATE
#define YYSTATE YY_START
YYTABLES_NAME
#define YYTABLES_NAME "yytables"
yyterminate
#define yyterminate () return YY_NULL
yytext
#define yytext ug4_lua_YY_text
yytext_ptr
#define yytext_ptr ug4_lua_YY_text
yywrap
#define yywrap ug4_lua_YY_wrap
Typedef Documentation
flex_int16_t
typedef short int flex_int16_t
flex_int32_t
typedef int flex_int32_t
flex_int8_t
typedef signed char flex_int8_t
flex_uint16_t
typedef unsigned short int flex_uint16_t
flex_uint32_t
typedef unsigned int flex_uint32_t
flex_uint8_t
typedef unsigned char flex_uint8_t
YY_BUFFER_STATE
typedef struct yy_buffer_state* YY_BUFFER_STATE
YY_CHAR
typedef unsigned char YY_CHAR
yy_size_t
typedef size_t yy_size_t
yy_state_type
typedef int yy_state_type
Function Documentation
if()
if (! yy_init)
References ug4_lua_YY__create_buffer(), ug4_lua_YY__load_buffer_state(), ug4_lua_YY_ensure_buffer_stack(), ug4_lua_YY_in, ug4_lua_YY_out, YY_BUF_SIZE, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_init, and yy_start.
Referenced by yyunput().
input()
static int input (void) static
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, ug4_lua_YY_in, ug4_lua_YY_restart(), ug4_lua_YY_wrap(), yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yy_did_buffer_switch_on_eof, YY_END_OF_BUFFER_CHAR, yy_get_next_buffer(), yy_hold_char, yy_n_chars, YY_NEW_FILE, and yytext_ptr.
Referenced by ug::IDWUserData< WDim, TData >::load_data_from(), and ug::StdDataLinker< DarcyVelocityLinker< dim >, MathVector< dim >, dim >::set_input().
isatty()
int isatty (int)
Referenced by ug4_lua_YY__init_buffer().
ug4_lua_YY__create_buffer()
YY_BUFFER_STATE ug4_lua_YY__create_buffer (FILE * file, int size)
Allocate and initialize an input buffer state.
Parameters
file A readable stream.
size The character buffer size in bytes. When in doubt, use YY_BUF_SIZE.
Returns
the allocated buffer state.
References ug4_lua_YY__init_buffer(), ug4_lua_YY_alloc(), yy_buffer_state::yy_buf_size, yy_buffer_state::yy_ch_buf, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by if(), and ug4_lua_YY_restart().
ug4_lua_YY__delete_buffer()
void ug4_lua_YY__delete_buffer (YY_BUFFER_STATE b)
Destroy the buffer.
Parameters
b a buffer created with ug4_lua_YY__create_buffer()
References ug4_lua_YY_free(), yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yy_buffer_state::yy_is_our_buffer.
Referenced by ug4_lua_YY_lex_destroy(), and ug4_lua_YY_pop_buffer_state().
ug4_lua_YY__flush_buffer()
void ug4_lua_YY__flush_buffer (YY_BUFFER_STATE b)
Discard all buffered characters. On the next scan, YY_INPUT will be called.
Parameters
b the buffer state to be flushed, usually YY_CURRENT_BUFFER.
References ug4_lua_YY__load_buffer_state(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_END_OF_BUFFER_CHAR, and yy_buffer_state::yy_n_chars.
Referenced by ug4_lua_YY__init_buffer().
ug4_lua_YY__init_buffer()
static void ug4_lua_YY__init_buffer (YY_BUFFER_STATE b, FILE * file) static
References isatty(), ug4_lua_YY__flush_buffer(), yy_buffer_state::yy_bs_column, yy_buffer_state::yy_bs_lineno, YY_CURRENT_BUFFER, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, and yy_buffer_state::yy_is_interactive.
Referenced by ug4_lua_YY__create_buffer(), and ug4_lua_YY_restart().
ug4_lua_YY__load_buffer_state()
static void ug4_lua_YY__load_buffer_state (void) static
References ug4_lua_YY_in, yy_c_buf_p, YY_CURRENT_BUFFER_LVALUE, yy_hold_char, yy_n_chars, and yytext_ptr.
Referenced by if(), ug4_lua_YY__flush_buffer(), ug4_lua_YY__switch_to_buffer(), ug4_lua_YY_pop_buffer_state(), ug4_lua_YY_push_buffer_state(), and ug4_lua_YY_restart().
ug4_lua_YY__scan_buffer()
YY_BUFFER_STATE ug4_lua_YY__scan_buffer (char * base, yy_size_t size)
Setup the input buffer state to scan directly from a user-specified character buffer.
Parameters
base the character buffer
size the size in bytes of the character buffer
Returns
the newly allocated buffer state object.
References ug4_lua_YY__switch_to_buffer(), ug4_lua_YY_alloc(), yy_buffer_state::yy_at_bol, yy_buffer_state::yy_buf_pos, yy_buffer_state::yy_buf_size, YY_BUFFER_NEW, yy_buffer_state::yy_buffer_status, yy_buffer_state::yy_ch_buf, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, yy_buffer_state::yy_fill_buffer, yy_buffer_state::yy_input_file, yy_buffer_state::yy_is_interactive, yy_buffer_state::yy_is_our_buffer, and yy_buffer_state::yy_n_chars.
Referenced by ug4_lua_YY__scan_bytes().
ug4_lua_YY__scan_bytes()
YY_BUFFER_STATE ug4_lua_YY__scan_bytes (yyconst char * yybytes, yy_size_t _yybytes_len)
Setup the input buffer state to scan the given bytes. The next call to ug4_lua_YY_lex() will scan from a copy of bytes.
Parameters
bytes the byte buffer to scan
len the number of bytes in the buffer pointed to by bytes.
Returns
the newly allocated buffer state object.
References ug4_lua_YY__scan_buffer(), ug4_lua_YY_alloc(), YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, and yy_buffer_state::yy_is_our_buffer.
Referenced by ug4_lua_YY__scan_string().
ug4_lua_YY__scan_string()
YY_BUFFER_STATE ug4_lua_YY__scan_string (yyconst char * yystr)
Setup the input buffer state to scan a string. The next call to ug4_lua_YY_lex() will scan from a copy of str.
Parameters
yystr a NUL-terminated string to scan
Returns
the newly allocated buffer state object.
Note
If you want to scan bytes that may contain NUL values, then use ug4_lua_YY__scan_bytes() instead.
References ug4_lua_YY__scan_bytes().
ug4_lua_YY__switch_to_buffer()
void ug4_lua_YY__switch_to_buffer (YY_BUFFER_STATE new_buffer)
Switch to a different input buffer.
Parameters
new_buffer The new input buffer.
References ug4_lua_YY__load_buffer_state(), ug4_lua_YY_ensure_buffer_stack(), yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_did_buffer_switch_on_eof, yy_hold_char, and yy_n_chars.
Referenced by ug4_lua_YY__scan_buffer().
ug4_lua_YY_alloc()
void * ug4_lua_YY_alloc (yy_size_t size)
Referenced by ug4_lua_YY__create_buffer(), ug4_lua_YY__scan_buffer(), ug4_lua_YY__scan_bytes(), and ug4_lua_YY_ensure_buffer_stack().
ug4_lua_YY_ensure_buffer_stack()
static void ug4_lua_YY_ensure_buffer_stack (void) static
References ug4_lua_YY_alloc(), ug4_lua_YY_realloc(), yy_buffer_stack, yy_buffer_stack_max, yy_buffer_stack_top, and YY_FATAL_ERROR.
Referenced by if(), ug4_lua_YY__switch_to_buffer(), ug4_lua_YY_push_buffer_state(), and ug4_lua_YY_restart().
ug4_lua_YY_free()
void ug4_lua_YY_free (void * ptr)
Referenced by ug4_lua_YY__delete_buffer(), and ug4_lua_YY_lex_destroy().
ug4_lua_YY_get_debug()
int ug4_lua_YY_get_debug (void)
References ug4_lua_YY__flex_debug.
ug4_lua_YY_get_extra()
YY_EXTRA_TYPE ug4_lua_YY_get_extra (void)
ug4_lua_YY_get_in()
FILE * ug4_lua_YY_get_in (void)
Get the input stream.
References ug4_lua_YY_in.
ug4_lua_YY_get_leng()
yy_size_t ug4_lua_YY_get_leng (void)
Get the length of the current token.
References ug4_lua_YY_leng.
ug4_lua_YY_get_lineno()
int ug4_lua_YY_get_lineno (void)
Get the current line number.
References ug4_lua_YY_lineno.
Referenced by while().
ug4_lua_YY_get_out()
FILE * ug4_lua_YY_get_out (void)
Get the output stream.
References ug4_lua_YY_out.
ug4_lua_YY_get_text()
char * ug4_lua_YY_get_text (void)
Get the current token.
References ug4_lua_YY_text.
ug4_lua_YY_lex()
int ug4_lua_YY_lex (void)
ug4_lua_YY_lex_destroy()
int ug4_lua_YY_lex_destroy (void)
References ug4_lua_YY__delete_buffer(), ug4_lua_YY_free(), ug4_lua_YY_pop_buffer_state(), yy_buffer_stack, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yy_init_globals().
ug4_lua_YY_pop_buffer_state()
void ug4_lua_YY_pop_buffer_state (void)
Removes and deletes the top of the stack, if present. The next element becomes the new top.
References ug4_lua_YY__delete_buffer(), ug4_lua_YY__load_buffer_state(), yy_buffer_stack_top, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, and yy_did_buffer_switch_on_eof.
Referenced by ug4_lua_YY_lex_destroy().
ug4_lua_YY_push_buffer_state()
void ug4_lua_YY_push_buffer_state (YY_BUFFER_STATE new_buffer)
Pushes the new state onto the stack. The new state becomes the current state. This function will allocate the stack if necessary.
Parameters
new_buffer The new state.
References ug4_lua_YY__load_buffer_state(), ug4_lua_YY_ensure_buffer_stack(), yy_buffer_stack_top, yy_c_buf_p, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, yy_did_buffer_switch_on_eof, yy_hold_char, and yy_n_chars.
ug4_lua_YY_realloc()
void * ug4_lua_YY_realloc (void * ptr, yy_size_t size)
Referenced by ug4_lua_YY_ensure_buffer_stack(), and yy_get_next_buffer().
ug4_lua_YY_restart()
void ug4_lua_YY_restart (FILE * input_file)
Immediately switch to a different input stream.
Parameters
input_file A readable stream.
Note
This function does not reset the start condition to INITIAL .
References ug4_lua_YY__create_buffer(), ug4_lua_YY__init_buffer(), ug4_lua_YY__load_buffer_state(), ug4_lua_YY_ensure_buffer_stack(), ug4_lua_YY_in, YY_BUF_SIZE, YY_CURRENT_BUFFER, and YY_CURRENT_BUFFER_LVALUE.
Referenced by input(), and yy_get_next_buffer().
ug4_lua_YY_set_debug()
void ug4_lua_YY_set_debug (int debug_flag)
References ug4_lua_YY__flex_debug.
ug4_lua_YY_set_extra()
void ug4_lua_YY_set_extra (YY_EXTRA_TYPE user_defined)
ug4_lua_YY_set_in()
void ug4_lua_YY_set_in (FILE * in_str)
Set the input stream. This does not discard the current input buffer.
Parameters
in_str A readable stream.
See also
ug4_lua_YY__switch_to_buffer
References ug4_lua_YY_in.
ug4_lua_YY_set_lineno()
void ug4_lua_YY_set_lineno (int line_number)
Set the current line number.
Parameters
line_number
References ug4_lua_YY_lineno.
ug4_lua_YY_set_out()
void ug4_lua_YY_set_out (FILE * out_str)
References ug4_lua_YY_out.
ug4_lua_YY_wrap()
int ug4_lua_YY_wrap (void)
References unput.
Referenced by input(), and while().
while()
while (1)
References ECHO, EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, ug::LUAParserClass::filename, ug::LUAParserClass::get_id_for_name(), globalP, ug::LUAParserClass::iLineAdd, INITIAL, LUAPARSER_AND, LUAPARSER_BREAK, LUAPARSER_DO, LUAPARSER_ELSE, LUAPARSER_ELSEIF, LUAPARSER_END, LUAPARSER_EQ, LUAPARSER_FOR, LUAPARSER_FUNCTION, LUAPARSER_GE, LUAPARSER_IF, LUAPARSER_LE, LUAPARSER_LOCAL, LUAPARSER_MATH_ABS, LUAPARSER_MATH_CEIL, LUAPARSER_MATH_COS, LUAPARSER_MATH_EXP, LUAPARSER_MATH_FLOOR, LUAPARSER_MATH_LOG, LUAPARSER_MATH_LOG10, LUAPARSER_MATH_MAX, LUAPARSER_MATH_MIN, LUAPARSER_MATH_PI, LUAPARSER_MATH_POW, LUAPARSER_MATH_SIN, LUAPARSER_MATH_SQRT, LUAPARSER_NE, LUAPARSER_OR, LUAPARSER_RETURN, LUAPARSER_THEN, LUAPARSER_VARIABLE, sprintf(), ug4_lua_YY_get_lineno(), ug4_lua_YY_in, ug4_lua_YY_text, ug4_lua_YY_wrap(), yy_accept, yy_act, yy_base, yy_bp, YY_BREAK, YY_BUFFER_NEW, YY_BUFFER_NORMAL, yy_c_buf_p, yy_chk, yy_cp, YY_CURRENT_BUFFER_LVALUE, yy_def, yy_did_buffer_switch_on_eof, YY_DO_BEFORE_ACTION, yy_ec, YY_END_OF_BUFFER, YY_FATAL_ERROR, yy_get_next_buffer(), yy_get_previous_state(), yy_hold_char, YY_INTEGER, yy_last_accepting_cpos, yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yy_n_chars, YY_NEW_FILE, yy_nxt, YY_RESTORE_YY_MORE_OFFSET, YY_RULE_SETUP, YY_SC_TO_UI, YY_START, yy_start, YY_STATE_EOF, yy_try_NUL_trans(), yyerror, yylval, yyterminate, and yytext_ptr.
yy_fatal_error() [1/2]
static void yy_fatal_error (yyconst char * msg) static
References YY_EXIT_FAILURE.
yy_fatal_error() [2/2]
static void yy_fatal_error (yyconst char msg[]) static
yy_get_next_buffer()
static int yy_get_next_buffer (void) static
References EOB_ACT_CONTINUE_SCAN, EOB_ACT_END_OF_FILE, EOB_ACT_LAST_MATCH, ug4_lua_YY_in, ug4_lua_YY_realloc(), ug4_lua_YY_restart(), yy_buffer_state::yy_buf_size, YY_BUFFER_EOF_PENDING, yy_c_buf_p, yy_buffer_state::yy_ch_buf, YY_CURRENT_BUFFER, YY_CURRENT_BUFFER_LVALUE, YY_END_OF_BUFFER_CHAR, YY_FATAL_ERROR, YY_INPUT, yy_buffer_state::yy_is_our_buffer, YY_MORE_ADJ, yy_n_chars, YY_READ_BUF_SIZE, and yytext_ptr.
Referenced by input(), and while().
yy_get_previous_state()
static yy_state_type yy_get_previous_state (void) static
References yy_accept, yy_base, yy_c_buf_p, yy_chk, yy_cp, yy_def, yy_ec, yy_last_accepting_cpos, yy_last_accepting_state, yy_meta, YY_MORE_ADJ, yy_nxt, YY_SC_TO_UI, yy_start, and yytext_ptr.
Referenced by while().
yy_init_globals()
static int yy_init_globals (void) static
References ug4_lua_YY_in, ug4_lua_YY_out, yy_buffer_stack, yy_buffer_stack_max, yy_buffer_stack_top, yy_c_buf_p, yy_init, and yy_start.
Referenced by ug4_lua_YY_lex_destroy().
yy_try_NUL_trans()
static yy_state_type yy_try_NUL_trans (yy_state_type current_state) static
References yy_accept, yy_base, yy_c_buf_p, yy_chk, yy_cp, yy_def, yy_last_accepting_cpos, yy_last_accepting_state, yy_meta, and yy_nxt.
Referenced by while().
yyerror()
void yyerror (const char * s)
yyunput() [1/2]
static void yyunput (int c, char * buf_ptr) static
yyunput() [2/2]
static void yyunput (int c, register char * yy_bp) static
References if(), yy_bp, yy_c_buf_p, yy_cp, YY_CURRENT_BUFFER_LVALUE, YY_FATAL_ERROR, yy_hold_char, yy_n_chars, and yytext_ptr.
Variable Documentation
globalP
LUAParserClass* globalP
Referenced by while(), yaccparse(), yyerror(), and yyparse().
ug4_lua_YY__flex_debug
int ug4_lua_YY__flex_debug = 0
Referenced by ug4_lua_YY_get_debug(), and ug4_lua_YY_set_debug().
ug4_lua_YY_in
FILE * ug4_lua_YY_in = (FILE *) 0
Referenced by if(), input(), ug4_lua_YY__load_buffer_state(), ug4_lua_YY_get_in(), ug4_lua_YY_restart(), ug4_lua_YY_set_in(), while(), yy_get_next_buffer(), and yy_init_globals().
ug4_lua_YY_leng
yy_size_t ug4_lua_YY_leng
Referenced by ug4_lua_YY_get_leng().
ug4_lua_YY_lineno
int ug4_lua_YY_lineno = 1
Referenced by ug4_lua_YY_get_lineno(), and ug4_lua_YY_set_lineno().
ug4_lua_YY_out
FILE * ug4_lua_YY_out = (FILE *) 0
Referenced by if(), ug4_lua_YY_get_out(), ug4_lua_YY_set_out(), and yy_init_globals().
ug4_lua_YY_text
char * ug4_lua_YY_text
Referenced by ug4_lua_YY_get_text(), and while().
yy_accept
yyconst flex_int16_t yy_accept[120] static
Initial value:
=
    {   0,
        0,    0,   39,   37,   36,   36,    4,    4,    2,    3,
        4,    4,    4,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   37,   36,    1,    0,    3,
        0,    6,    7,    5,   35,   35,   35,   18,   35,   35,
       35,   35,   13,   35,   35,   21,   35,   35,    8,    1,
        3,    0,    3,   20,   35,   35,    9,   17,   35,   35,
       35,   35,   35,   35,   15,   35,   35,   35,   35,   14,
       19,   35,   35,   10,    0,   35,   16,   35,    0,    0,
        0,    0,    0,    0,    0,    0,   12,   35,    0,    0,
        0,    0,    0,    0,    0,    0,   34,    0,    0,    0,
       11,   25,    0,   22,   24,    0,   26,   32,   33,   31,
       23,    0,   30,    0,    0,   28,   29,   27,    0
    }
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yy_act
register int yy_act
Referenced by while().
yy_base
yyconst flex_int16_t yy_base[122] static
Initial value:
=
    {   0,
        0,    0,  156,  157,   37,   39,  157,  149,   36,    0,
      142,  141,  140,    0,  123,  118,  120,   21,   19,  127,
      118,  130,  113,  124,  120,  130,   50,    0,   49,    0,
       55,  157,  157,  157,    0,  122,  120,    0,  106,  119,
      105,  108,    0,  117,  100,    0,   99,  112,  157,    0,
       58,   61,   66,    0,  115,  110,    0,    0,  111,  112,
      104,   91,   97,   99,   99,   88,   95,  113,   87,    0,
        0,   97,   93,    0,   63,   88,    0,   86,   97,   57,
       76,   86,   82,   56,   26,   61,    0,   82,   76,   84,
       74,   76,   76,   82,   66,   74,  157,   65,   72,   66,
        0,  157,   69,  157,  157,   65,   82,  157,  157,  157,
      157,   54,  157,   55,   74,  157,  157,  157,  157,   59,
       96
    }
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yy_bp
register char * yy_bp
Referenced by while(), and yyunput().
yy_buffer_stack
YY_BUFFER_STATE* yy_buffer_stack = 0 static
Stack as an array.
Referenced by ug4_lua_YY_ensure_buffer_stack(), ug4_lua_YY_lex_destroy(), and yy_init_globals().
yy_buffer_stack_max
size_t yy_buffer_stack_max = 0 static
capacity of stack.
Referenced by ug4_lua_YY_ensure_buffer_stack(), and yy_init_globals().
yy_buffer_stack_top
size_t yy_buffer_stack_top = 0 static
index of top of stack.
Referenced by ug4_lua_YY_ensure_buffer_stack(), ug4_lua_YY_pop_buffer_state(), ug4_lua_YY_push_buffer_state(), and yy_init_globals().
yy_c_buf_p
char* yy_c_buf_p = (char *) 0 static
Referenced by input(), ug4_lua_YY__load_buffer_state(), ug4_lua_YY__switch_to_buffer(), ug4_lua_YY_push_buffer_state(), while(), yy_get_next_buffer(), yy_get_previous_state(), yy_init_globals(), yy_try_NUL_trans(), and yyunput().
yy_chk
yyconst flex_int16_t yy_chk[196] static
Initial value:
=
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        6,    6,    9,    9,    9,    9,   18,   19,   18,   85,
        9,   27,   27,   19,   85,    9,   29,   29,   29,   31,
       31,  120,   31,   31,   31,   51,   51,   51,   52,   52,
       52,   84,   51,   53,   53,   53,   80,   51,   75,   84,
       75,  115,   75,   75,   86,   80,  114,  112,   75,   75,
      107,   86,   75,  106,  103,   75,  121,  100,  121,   99,
       98,   96,   95,   94,   93,   92,   91,   90,   89,   88,
       83,   82,   81,   79,   78,   76,   73,   72,   69,   68,
       67,   66,   65,   64,   63,   62,   61,   60,   59,   56,
       55,   48,   47,   45,   44,   42,   41,   40,   39,   37,
       36,   26,   25,   24,   23,   22,   21,   20,   17,   16,
       15,   13,   12,   11,    8,    3,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119
    }
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yy_cp
register char* yy_cp
Referenced by while(), yy_get_previous_state(), yy_try_NUL_trans(), and yyunput().
YY_DECL
YY_DECL
Initial value:
{
  register yy_state_type yy_current_state
The main scanner function which does all the work.
yy_def
yyconst flex_int16_t yy_def[122] static
Initial value:
=
    {   0,
      119,    1,  119,  119,  119,  119,  119,  119,  119,    9,
      119,  119,  119,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  119,  119,  121,  119,    9,
      119,  119,  119,  119,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  119,  121,
      119,  119,  119,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  119,  120,  120,  120,  119,  119,
      119,  119,  119,  119,  119,  119,  120,  120,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      120,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,    0,  119,
      119
    }
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yy_did_buffer_switch_on_eof
int yy_did_buffer_switch_on_eof static
Referenced by input(), ug4_lua_YY__switch_to_buffer(), ug4_lua_YY_pop_buffer_state(), ug4_lua_YY_push_buffer_state(), and while().
yy_ec
yyconst flex_int32_t yy_ec[256] static
Referenced by while(), and yy_get_previous_state().
yy_hold_char
char yy_hold_char static
Referenced by input(), ug4_lua_YY__load_buffer_state(), ug4_lua_YY__switch_to_buffer(), ug4_lua_YY_push_buffer_state(), while(), and yyunput().
yy_init
int yy_init = 0 static
Referenced by if(), and yy_init_globals().
yy_last_accepting_cpos
char* yy_last_accepting_cpos static
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yy_last_accepting_state
yy_state_type yy_last_accepting_state static
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yy_meta
yyconst flex_int32_t yy_meta[39] static
Initial value:
=
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    3,    3,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1
    }
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yy_n_chars
yy_size_t yy_n_chars static
Referenced by input(), ug4_lua_YY__load_buffer_state(), ug4_lua_YY__switch_to_buffer(), ug4_lua_YY_push_buffer_state(), while(), yy_get_next_buffer(), and yyunput().
yy_nxt
yyconst flex_int16_t yy_nxt[196] static
Initial value:
=
    {   0,
        4,    5,    6,    7,    7,    8,    4,    9,   10,   10,
       11,   12,   13,   14,   14,   15,   16,   14,   17,   18,
       19,   14,   14,   20,   14,   21,   22,   14,   23,   14,
       14,   24,   14,   25,   14,   14,   14,   26,   27,   27,
       27,   27,   29,   30,   30,   30,   39,   41,   40,   97,
       31,   27,   27,   42,   98,   31,   51,   51,   51,   52,
       52,   35,   53,   53,   53,   51,   51,   51,   53,   53,
       53,   95,   31,   53,   53,   53,   90,   31,   79,   96,
       80,  118,   81,   82,   99,   91,  117,  116,   83,   84,
      115,  100,   85,  114,  113,   86,   50,  112,   50,  111,
      110,  109,  108,  107,  106,  105,  104,  103,  102,  101,
       94,   93,   92,   89,   88,   87,   78,   77,   76,   75,
       74,   73,   72,   71,   70,   69,   68,   67,   66,   65,
       64,   63,   62,   61,   60,   59,   58,   57,   56,   55,
       54,   49,   48,   47,   46,   45,   44,   43,   38,   37,
       36,   34,   33,   32,   28,  119,    3,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119
    }
Referenced by while(), yy_get_previous_state(), and yy_try_NUL_trans().
yy_start
int yy_start = 0 static
Referenced by if(), while(), yy_get_previous_state(), and yy_init_globals().