ug4: ugbase/lib_grid/grid_objects/lookup_table_generator/lookup_table_generator.cpp File Reference
lookup_table_generator.cpp File Reference
#include <iostream>
#include "../tetrahedron_rules.h"
#include "../octahedron_rules.h"
#include "../pyramid_rules.h"
#include "../prism_rules.h"
#include "../hexahedron_rules.h"
Functions
int main (int argc, char *argv[])
void PrintEdgeFromVrts (int numVrts, int numEdges, const int edgeVrtInds[][2])
void PrintFaceContainsEdgeLists (int numEdges, int numFaces, const int edgeVrtInds[][2], const int faceVrtInds[][4])
void PrintFaceEdgeInds (int numEdges, int numFaces, const int edgeVrtInds[][2], const int faceVrtInds[][4])
void PrintFaceFromEdges (int numEdges, int numFaces, const int edgeVrtInds[][2], const int faceVrtInds[][4])
void PrintFaceFromVrts (int numVrts, int numFaces, const int faceVrtInds[][4])
Function Documentation
main()
int main (int argc, char * argv[])
References ug::hex_rules::EDGE_VRT_INDS, ug::hex_rules::FACE_VRT_INDS, ug::hex_rules::NUM_EDGES, ug::hex_rules::NUM_FACES, ug::hex_rules::NUM_VERTICES, PrintEdgeFromVrts(), PrintFaceContainsEdgeLists(), PrintFaceEdgeInds(), PrintFaceFromEdges(), and PrintFaceFromVrts().
PrintEdgeFromVrts()
void PrintEdgeFromVrts (int numVrts, int numEdges, const int edgeVrtInds[][2])
Referenced by main().
PrintFaceContainsEdgeLists()
void PrintFaceContainsEdgeLists (int numEdges, int numFaces, const int edgeVrtInds[][2], const int faceVrtInds[][4])
Referenced by main().
PrintFaceEdgeInds()
void PrintFaceEdgeInds (int numEdges, int numFaces, const int edgeVrtInds[][2], const int faceVrtInds[][4])
Referenced by main().
PrintFaceFromEdges()
void PrintFaceFromEdges (int numEdges, int numFaces, const int edgeVrtInds[][2], const int faceVrtInds[][4])
Referenced by main().
PrintFaceFromVrts()
void PrintFaceFromVrts (int numVrts, int numFaces, const int faceVrtInds[][4])
References ug::find().
Referenced by main().