ug4: ugbase/common/profiler/memtracker.cpp File Reference
memtracker.cpp File Reference
#include "memtracker.h"
#include "common/log.h"
#include "assert.h"
#include "common/util/string_util.h"
#include <map>
Classes
class ug::MemTrackerStruct
Namespaces
ug
the ug namespace
Typedefs
typedef map< void *, MemTrackerStruct > ug::MemTrackerMap
Functions
void ug::CalcTotalMem (const Shiny::ProfileNode *p)
void ug::DisplayVacantMemory ()
bool ug::EnableMemTracker (bool b)
void * ug::get_mem (size_t size)
size_t ug::GetSelfMem (const Shiny::ProfileNode *p)
size_t ug::GetTotalMem (const Shiny::ProfileNode *p)
bool ug::HasMemTracking ()
bool ug::IsMemTrackerEnabled ()
void operator delete (void *p) throw ()
void operator delete[] (void *p) throw ()
void * operator new (size_t size) throw (std::bad_alloc)
void * operator new[] (size_t size) throw (std::bad_alloc)
void ug::release_mem (void *p)
void ug::UpdateTotalMem ()
Variables
size_t ug::allocated = 0
bool ug::bMemTracker =false
MemTrackerMap ug::memTracker
map< const Shiny::ProfileNode *, size_t > ug::selfmem
map< const Shiny::ProfileNode *, size_t > ug::totalmem
Function Documentation
operator delete()
void operator delete (void * p) throw ()
References p, and ug::release_mem().
operator delete[]()
void operator delete[] (void * p) throw ()
References p, and ug::release_mem().
operator new()
void* operator new (size_t size) throw (std::bad_alloc)
References ug::get_mem().
operator new[]()
void* operator new[] (size_t size) throw (std::bad_alloc)
References ug::get_mem().