ug4: ug::shared_rules Namespace Reference
ug::shared_rules Namespace Reference
Functions
int RecursiveRefine (int *newIndsOut, int *newEdgeVrts, const int faceVrtInds[][4], const int faceEdgeInds[][4], int numVrts, int numEdges, int numFaces)
Variables
const int MAX_NUM_INDS_OUT = 256
Function Documentation
RecursiveRefine()
int ug::shared_rules::RecursiveRefine (int * newIndsOut, int * newEdgeVrts, const int faceVrtInds[][4], const int faceEdgeInds[][4], int numVrts, int numEdges, int numFaces)
Todo:
add support for snap-vertices.
References ug::hex_rules::MAX_NUM_INDS_OUT, ug::hex_rules::NUM_EDGES, ug::hex_rules::NUM_VERTICES, Refine(), and UG_LOG.
Referenced by ug::hex_rules::Refine(), ug::prism_rules::Refine(), ug::pyra_rules::Refine(), ug::oct_rules::Refine(), and ug::tet_rules::Refine().
Variable Documentation
MAX_NUM_INDS_OUT
const int ug::shared_rules::MAX_NUM_INDS_OUT = 256