ug4: ug::grid_unit_tests Namespace Reference
ug::grid_unit_tests Namespace Reference
Functions
void CheckAssociatedEdgesOfVolumes (Grid &g)
void CheckAssociatedVolumesOfEdges (Grid &g)
Function Documentation
void ug::grid_unit_tests::CheckAssociatedEdgesOfVolumes (Grid & g)
THIS METHOD USES Grid::mark! iterates over all volumes in g and checks for each whether the edges stored in the associated container are the same as the edges which can be found in the grid and which are contained by the volume...
If something is wrong, the method throws an instance of UGError.
References ug::Grid::begin_marking(), ug::Grid::clear_marks(), ug::CollectAssociated(), ug::Volume::edge_desc(), ug::Grid::enable_options(), ug::Grid::end_marking(), ug::Grid::get_edge(), ug::GRIDOPT_AUTOGENERATE_SIDES, ug::Grid::is_marked(), ug::Grid::mark(), ug::Volume::num_edges(), ug::VolumeVertices::num_vertices(), ug::Grid::option_is_enabled(), UG_LOG, UG_THROW, ug::VolumeVertices::vertices(), ug::VOLOPT_AUTOGENERATE_EDGES, ug::VOLOPT_STORE_ASSOCIATED_EDGES, ug::VolumeContains(), ug::Grid::volumes_begin(), and ug::Grid::volumes_end().
void ug::grid_unit_tests::CheckAssociatedVolumesOfEdges (Grid & g)
THIS METHOD USES Grid::mark! iterates over all edges in g and checks for each whether the volumes stored in the associated container are the same as the edges which can be found in the grid and which are contained by the volume...
If something is wrong, the method throws an instance of UGError.
References ug::Grid::begin_marking(), ug::Grid::clear_marks(), ug::CollectAssociated(), ug::EDGEOPT_STORE_ASSOCIATED_VOLUMES, ug::Grid::edges_begin(), ug::Grid::edges_end(), ug::Grid::enable_options(), ug::Grid::end_marking(), ug::Grid::is_marked(), ug::Grid::mark(), ug::EdgeVertices::num_vertices(), ug::Grid::option_is_enabled(), UG_LOG, UG_THROW, ug::EdgeVertices::vertices(), and ug::VolumeContains().