ug4: ug::grid_intersection_impl Namespace Reference
ug::grid_intersection_impl Namespace Reference
Functions
template<class TAPos >
void DebugSave (Grid &grid, const char *filePrefix, TAPos aPos)
template<class TAPos >
void DebugSave2d (Grid &grid, const char *filePrefix, TAPos aPos)
Function Documentation
DebugSave()
template<class TAPos > void ug::grid_intersection_impl::DebugSave (Grid & grid, const char * filePrefix, TAPos aPos)
References mkstr, ug::SaveGridToFile(), and UG_LOG.
Referenced by ug::ResolveTriangleIntersections().
DebugSave2d()
template<class TAPos > void ug::grid_intersection_impl::DebugSave2d (Grid & grid, const char * filePrefix, TAPos aPos)
References mkstr, ug::SaveGridToFile(), ug::TransformPointSetTo2D(), UG_LOG, ug::Grid::vertices_begin(), and ug::Grid::vertices_end().
Referenced by ug::ResolveTriangleIntersections().