ug4: ug::bridge Namespace Reference
ug::bridge Namespace Reference
Namespaces
AdaptiveTools
AlgebraCommon
Constraints
DiscAlgebra
Domain
domain_ray_tracing
DomainDisc
Eigensolver
ElemDiscs
Evaluate
FiniteVolume
GridFunction
Integrate
Interpolate
LoadBalancing
lua
LuaUserData
MaxError
MultiGrid
Obstacle
Ordering
Output
periodicBoundary
Preconditioner
Refinement
Restart
Schur
Selection
Solver
SuperLUBridge
Transform
UserDataBridge
Classes
struct AlgebraTypeIDProvider
class AllowName
class Base
class Base0
class Base1
class Base2
class Base3
class Cake
class ClassCastProvider
provides castings from derived classes to base classes
class ClassGroupDesc
groups classes. One of the members is the default member.
class ClassHierarchy
Class Hierarchy Helper Class for UG Registry This class stores class names and their subclasses.
class ClassNameNode
node for class names
class ClassNameProvider
provides the name for a class
struct CLI_Functionality
class ConstClass
struct constructor_traits
struct constructor_traits< T, TypeList< T1 > >
struct constructor_traits< T, TypeList< T1, T2 > >
struct constructor_traits< T, TypeList< T1, T2, T3 > >
struct constructor_traits< T, TypeList< T1, T2, T3, T4 > >
struct constructor_traits< T, TypeList< T1, T2, T3, T4, T5 > >
struct constructor_traits< T, TypeList< T1, T2, T3, T4, T5, T6 > >
struct constructor_traits< T, TypeList< T1, T2, T3, T4, T5, T6, T7 > >
struct constructor_traits< T, TypeList< T1, T2, T3, T4, T5, T6, T7, T8 > >
struct constructor_traits< T, TypeList<> >
struct ConstructorProxy
struct CreateParameterInfo
struct CreateParameterInfo< TypeList<> >
struct CreateParameterInfoOut
Creation of return value.
struct CreateParameterInfoOut< CustomReturn >
struct CreateParameterInfoOut< void >
Creation of void return value (template specialization)
class CustomReturn
class Derived
class ExpandLayersDesc
A helper class for ExpandLayers.
class ExportedClass
This template class represents real c++ classes in the registry.
class ExportedClassBaseImpl
A base implementation with non-template methods.
class ExportedConstructor
describing information for constructor
class ExportedFunction
This class describes a wrapper for a c++ - function, that is exported by ug.
class ExportedFunctionBase
Base class for function/method export.
class ExportedFunctionGroup
Groups of Functions - useful to realize overloaded functions.
class ExportedMethod
class ExportedMethodGroup
Groups of methods - useful to realize overloaded methods.
struct func_traits
struct func_traits< TRet(*)()>
struct func_traits< TRet(*)(P1)>
struct func_traits< TRet(*)(T1, T2)>
struct func_traits< TRet(*)(T1, T2, T3)>
struct func_traits< TRet(*)(T1, T2, T3, T4)>
struct func_traits< TRet(*)(T1, T2, T3, T4, T5)>
struct func_traits< TRet(*)(T1, T2, T3, T4, T5, T6)>
struct func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7)>
struct func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7, T8)>
struct func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7, T8, T9)>
struct func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)>
struct func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)>
struct func_traits< TRet(*)(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)>
struct func_traits< TRet(TClass::*)() const >
struct func_traits< TRet(TClass::*)()>
struct func_traits< TRet(TClass::*)(P1) const >
struct func_traits< TRet(TClass::*)(P1)>
struct func_traits< TRet(TClass::*)(T1, T2) const >
struct func_traits< TRet(TClass::*)(T1, T2)>
struct func_traits< TRet(TClass::*)(T1, T2, T3) const >
struct func_traits< TRet(TClass::*)(T1, T2, T3)>
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4) const >
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4)>
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5) const >
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5)>
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6) const >
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6)>
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7) const >
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7)>
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7, T8) const >
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7, T8)>
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7, T8, T9) const >
struct func_traits< TRet(TClass::*)(T1, T2, T3, T4, T5, T6, T7, T8, T9)>
struct func_traits< xp::xproperty< V, M > O::* >
struct Functionality
struct FunctionProxy
struct FunctionProxy< TFunc, void >
class FurtherDerived
class IExportedClass
Base class for exported Classes.
class Intermediate0
class Intermediate1
class JSONConstructible
class LUACompiler
class LuaStackCheck
class Message
class MessageHubTest
struct MethodProxy
struct MethodProxy< TClass, TMethod, CustomReturn >
struct MethodProxy< TClass, TMethod, void >
class MethodPtrWrapper
class MultipleDerived
class NonAllowedName1
class NonAllowedName2
class NonAllowedName3
class NonAllowedName4
class ParameterInfo
a stack holding parameter infos about a parameter stack
class ParameterStack
A stack that can hold values together with their type-id.
struct ParameterStackToTypeValueList
struct ParameterStackToTypeValueList< TypeList<>, index >
class Piece
struct RegisterAlgebraDependent
struct RegisterDomain1dAlgebraDependent
struct RegisterDomain2d3dAlgebraDependent
struct RegisterDomain2dAlgebraDependent
struct RegisterDomain3dAlgebraDependent
struct RegisterDomainAlgebraDependent
struct RegisterDomainDependent
class Registry
Registry for functions and classes that are exported to scripts and visualizations.
class SmartTest
SmartTest is a test-class which shall only be used encapsulated in a smart-pointer.
class SmartTestDerived
class Test
class TestMessage
struct UG_REGISTRY_ERROR_FunctionOrMethodNameMissing
Exception throw, if method name has not been given.
struct UGError_ClassCastFailed
struct UGRegistryError
class Unregistered
struct xproperty_traits
Typedefs
typedef boost::mpl::list< end_boost_list > CompileAlgebraList
typedef boost::mpl::list<> CompileDomainList
typedef boost::function< void(Registry *pReg)> FuncRegistryChanged
declaration of registry callback function.
typedef SmartPtr< SmartTest > SPSmartTest
typedef SmartPtr< SmartTestDerived > SPSmartTestDerived
Functions
string Add (const char *a, const char *b)
int Add (int a, int b)
int Add (int a, int b, int c)
template<class TClass >
void CastAndDelete (const void *ptr)
Performs a reinterpret cast on the given pointer, then calls delete on it.
template<>
void CastAndDelete< void > (const void *ptr)
string ClassHierarchyString (const Registry &reg, const char *classname)
string ClassInfo (const IExportedClass &c)
Prints the (const) method of one class.
string ClassInfo (const Registry &reg, const char *classname)
bool ClassInstantiations (const char *classname)
this function prints all objects which are of a certain class
bool ClassNameTreeContains (const ClassNameNode &node, const std::string &name)
returns if a name is contained in the name tree at node or in base classes
bool ClassNameTreeWay (std::vector< size_t > &vWay, const ClassNameNode &node, const std::string &name)
bool ClassNameVecContains (const std::vector< const char * > &names, const std::string &name)
returns if a name is contained in the name vector
string ClassUsage (const char *classname)
string ClassUsageExact (const Registry &reg, const char *classname, bool OutParameters)
int CompletionFunction (char *buf, int len, int buflen, int iPrintCompletionList)
A function to implement word completion of classes and functions of ugscript When entered Dom<tab>, it completes to Domain2d, for example. If Domain2d and Domain3d are registered, it completes to Domain and shows suggestions Domain2d and Domain3d. currently only works with Linenoise. todo: - not all completions must have same snipped length. change.
string ConstructorInfo (const ExportedConstructor &constr, const char *classname, const char *highlightclassname)
int ConstSmartTestFunc (ConstSmartPtr< Test > test)
ConstSmartPtr< Test > ConstSmartTestImpl ()
template<typename T >
void ConstStdVectorRefOfClass (const std::vector< T > &vec)
int ConstTestFunc (const Test &t)
calls const print on const object of class Test
int convert (const char *functionName)
int convertVM (const char *functionName)
const FurtherDerived * CreateConstFurtherDerived ()
bool CreateHierarchy (MultiGrid &mg, size_t numRefs)
bool CreateSmoothHierarchy (MultiGrid &mg, size_t numRefs)
debug_return DebugShell ()
template<typename TClass >
void DestructorProxy (void *obj)
void EnableLUA2C (bool b)
void EnableLUA2VM (bool b)
static void errlog (const char *msg)
static int ExecuteSystemCommand (const char *cmd)
void ExtractClassNameVec (std::vector< const char * > &names, const ClassNameNode &node, bool clearVec=true)
returns the vector containing all names in the name tree for node and its base classes
string FilenameStringEscape (string s)
const ExportedFunction * FindFunction (const Registry &reg, const char *functionname)
string FunctionInfo (const ExportedFunctionBase &thefunc, bool isConst, const char *classname, const char *highlightclassname, bool bPrintHelp)
string FunctionInfo (const Registry &reg, const char *functionname)
string FunctionInfo (lua_State *L, bool bComplete, const char *functionName=NULL)
prints out information for a lua function (a function defined in lua script)
template<typename TAlgebra >
std::string GetAlgebraSuffix ()
returns the algebra-suffix (e.g. "CPU3", "CPUFlex")
template<typename TAlgebraTypeType >
std::string GetAlgebraSuffix (const TAlgebraTypeType &algType)
returns the algebra-suffix (e.g. "CPU3", "CPUFlex")
template<typename TAlgebra >
std::string GetAlgebraTag ()
returns the algebra-suffix (e.g. "alg=CPU3", "alg=CPUVariable")
template<typename TAlgebraTypeType >
std::string GetAlgebraTag (const TAlgebraTypeType &algType)
returns the algebra-suffix (e.g. "alg=CPU3", "alg=CPUVariable")
static string GetAppsPath ()
static string GetBinPath ()
string GetBuildHostname ()
static size_t GetClassesCompletitions (char *buf, int len, std::vector< string > &matches, size_t &sniplen, int iPrintCompletionList)
void GetClassHierarchy (ClassHierarchy &hierarchy, const Registry &reg)
template<typename TClass >
const char * GetClassName ()
const ClassNameNode * GetClassNameNode (lua_State *L, int index)
const std::vector< const char * > * GetClassNames (lua_State *L, const char *name)
const std::vector< const char * > * GetClassNames (lua_State *L, int index)
double GetClockS ()
string GetCompileDate ()
static string GetCurrentPath ()
template<int dim, typename TAlgebra >
std::string GetDimensionAlgebraSuffix ()
returns the algebra-dim-suffix for a domain (e.g. "3dCPU1")
template<int dim, typename TAlgebra >
std::string GetDimensionAlgebraTag ()
returns the dim-tag for a domain (e.g. "dim=3d;alg=CPU1;")
template<typename TAlgebraTypeType >
std::string GetDimensionAlgebraTag (int dim, const TAlgebraTypeType &algType)
returns dim tag at runtime (e.g. "dim=3d;alg=CPU1;")
template<int dim>
std::string GetDimensionSuffix ()
returns the dim-suffix for a domain (e.g. "3d")
template<int dim>
std::string GetDimensionTag ()
returns the dim-tag for a domain (e.g. "dim=3d")
std::string GetDimensionTag (int dim)
returns dim tag at runtime (e.g. "dim=3d")
std::vector< std::string > GetDirsInDir (const char *dir)
template<typename TDomain , typename TAlgebra >
std::string GetDomainAlgebraSuffix ()
returns the dim-suffix for a domain (e.g. "3dCPU1")
template<typename TDomain , typename TAlgebra >
std::string GetDomainAlgebraTag ()
returns the dim-tag for a domain (e.g. "dim=3d;alg=CPU1;")
template<typename TDomain >
std::string GetDomainSuffix ()
returns the dim-suffix for a domain (e.g. "3d")
template<typename TDomain >
std::string GetDomainTag ()
returns the dim-tag for a domain (e.g. "dim=3d")
string GetFileLinesLUA (const char *filename, size_t fromline, size_t toline)
std::vector< std::string > GetFilesInDir (const char *dir)
string GetGITRevision ()
static bool GetGlobalFunctionInfo (char *buf, int len)
static size_t GetGlobalsCompletitions (char *buf, int len, std::vector< string > &matches, size_t &sniplen, int iPrintCompletionList)
uint32 GetLogAssistantTag (const char *s)
std::string GetLuaFileAndLine (lua_State *L)
returns the current file and line (
bool GetLuaFileAndLine (lua_State *L, std::string &file, size_t &line)
returns the current file and line (
std::string GetLuaFileAndLineNumber (lua_State *L)
returns the current file and line-number
void GetLuaGlobal_classInstantiations (std::vector< std::string > &classInstantiations)
void GetLuaGlobal_functions (std::vector< std::string > &functions)
void GetLuaGlobal_internalFunctions (std::vector< std::string > &internalFunctions)
void GetLuaGlobal_luaObjects (std::vector< std::string > &luaObjects)
void GetLuaGlobal_scriptFunctions (std::vector< std::string > &scriptFunctions)
void GetLuaGlobals (std::vector< std::string > *functions, std::vector< std::string > *internalFunctions, std::vector< std::string > *scriptFunctions, std::vector< std::string > *luaObjects, std::vector< std::string > *classInstantiations)
function to list all objects of the default LUA state
std::string GetLuaLine (lua_State *L)
returns the current line-content
UG_API bool GetLuaNamespace (lua_State *L, std::string name)
bool GetLuaNamespace (lua_State *L, string name)
searches for a namespaces (lists) and pushes it onto the stack
string GetLUAScriptFunctionDefined (const char *functionName)
returns file and line of defined script function
string GetLuaTypeString (lua_State *L, int index)
static size_t GetMemberFunctionCompletitions (char *buf, int len, std::vector< string > &matches, size_t &sniplen)
static bool GetMemberFunctionInfo (char *buf, int len)
static size_t GetNamespaceCompletitions (char *buf, int len, std::vector< string > &matches, size_t &sniplen, int iPrintCompletionList)
string GetOperatingSystem ()
static size_t GetOtherCompletitions (char *buf, int len, std::vector< string > &matches, size_t &sniplen)
size_t GetPathCompletitions (char *buf, int len, std::vector< string > &matches, size_t &sniplen)
static string GetRootPath ()
static string GetScriptPath ()
string GetSVNRevision ()
int GetUGDim ()
returns the dimension to which UG was initialized through InitUG
Registry & GetUGRegistry ()
returns the default registry used in ug
void InitBridge ()
calls RegisterStandardInterfaces
void InitShell ()
void InitSignals ()
void InitUG (int dim, const AlgebraType &algebraType)
Sets the default classes of class-groups based on a tags using default DoFManager.
void InitUG (int dim, const AlgebraType &algType, bool verbose)
Sets the default classes of class-groups based on a tags.
void InitUGPlugin_SuperLU6 (Registry *reg, string grp)
void int_srand (int seed)
bool IsClassInParameters (const ParameterInfo &par, const char *classname)
bool IsDefinedBLAS_AVAILABLE ()
bool IsDefinedLAPACK_AVAILABLE ()
bool IsDefinedPCL_DEBUG_BARRIER_ENABLED ()
bool IsDefinedPROFILE_PCL ()
bool IsDefinedUG_ALGEBRA ()
bool IsDefinedUG_BRIDGE ()
bool IsDefinedUG_CPU_1 ()
bool IsDefinedUG_CPU_2 ()
bool IsDefinedUG_CPU_3 ()
bool IsDefinedUG_CPU_4 ()
bool IsDefinedUG_CPU_5 ()
bool IsDefinedUG_CPU_6 ()
bool IsDefinedUG_CPU_VAR ()
bool IsDefinedUG_DEBUG ()
bool IsDefinedUG_DIM_1 ()
bool IsDefinedUG_DIM_2 ()
bool IsDefinedUG_DIM_3 ()
bool IsDefinedUG_ENABLE_DEBUG_LOGS ()
bool IsDefinedUG_FOR_VRL ()
bool IsDefinedUG_HLIBPRO ()
bool IsDefinedUG_HYPRE ()
bool IsDefinedUG_JSON ()
bool IsDefinedUG_PARALLEL ()
bool IsDefinedUG_PLUGINS ()
bool IsDefinedUG_PROFILER ()
bool IsDefinedUG_STATIC ()
bool IsDefinedUG_TETGEN ()
template<class T >
static bool IsValidPtr (T *o)
bool LoadGrid (Grid &grid, const char *filename)
bool LoadGrid (Grid &grid, ISubsetHandler &sh, const char *filename)
string LuaClassMethodInfo (lua_State *L, int index, const ExportedMethod &thefunc)
prints out information for a method of a class
string LuaCurrentLine (lua_State *L)
bool LuaGetBoolean (lua_State *L, const char *name, bool notAvailable)
returns a boolean to a lua-variable.
void LuaGetLastLine (lua_State *L, lua_Debug entry)
double LuaGetNumber (lua_State *L, const char *name, double notAvailable)
returns an integer to a lua-variable.
string LuaGetScriptFunctionString (lua_State *L, int index=-1)
prints the source of a lua script function which is on top of the stack
string LuaGetString (lua_State *L, const char *name, const char *notAvailable)
returns the string to a lua-variable.
void LuaList ()
void LuaList_cfunctions ()
void LuaList_classes ()
void LuaList_classInstantiations ()
void LuaList_internalFunctions ()
void LuaList_luaObjects ()
void LuaList_scriptFunctions ()
void LuaPrintTable (lua_State *L, size_t iSpace, int index)
prints the source of a lua script function which is on top of the stack
int LuaStackToParams (ParameterStack &ps, const ParameterInfo &psInfo, lua_State *L, int offsetToFirstParam=0)
copies parameter values from the lua-stack to a parameter-list.
void LuaStackTrace (int fromlevel)
prints information about lua's call stack (file:line source).
std::string LuaStackTraceString ()
string LuaStackTraceString (lua_State *L, int fromLevel=0, int toLevel=-1)
prints information about lua's call stack (file:line source).
string LUAStringEscape (string s)
void LuaWrite (const char *filename, const char *obj)
void LuaWriteCout (const char *obj)
void NonAllowedFct1 ()
void NonAllowedFct2 ()
void NonAllowedFct3 ()
void NotAllowedParamPerValue (Piece P)
template<typename T >
static T ParallelMax (T t)
template<typename T >
static T ParallelMin (T t)
template<typename T >
static T ParallelSum (T t)
template<typename T >
static vector< T > ParallelVecMax (const vector< T > &t)
template<typename T >
static vector< T > ParallelVecMin (const vector< T > &t)
template<typename T >
static vector< T > ParallelVecSum (const vector< T > &t)
string ParameterToString (const ParameterInfo &par, int i)
Gets a description of the i-th parameter of a ParameterStack todo: perhaps this function would be better somewhere else like in parameter_stack.cpp.
template<typename T >
static void ParamStackEntryToLuaStack (const ParameterStack &ps, lua_State *L, int index, bool bIsVector)
template<typename T >
static void ParamStackPointerEntryToLuaStack (const ParameterStack &ps, lua_State *L, int index, bool bIsVector)
int ParamsToLuaStack (const ParameterStack &ps, lua_State *L)
Pushes the parameter-values to the Lua-Stack.
static bool PclAllProcsTrue (bool bTrue)
static void PclDebugBarrierAll ()
static bool PclDebugBarrierEnabled ()
void PostRegisteredFunction ()
void PostRegisterTest ()
void print (const std::string &s)
void PrintBuildConfiguration ()
prints CMake build parameters in a quite compact (pairwise) form
void PrintBuildConfigurationExtended ()
void PrintClassSubHierarchy (ClassHierarchy &c, int level)
template<typename T >
void PrintConstStdVectorRef (const std::vector< T > &vec)
void PrintFunction (Base &b)
void PrintFunction (Base3 &b)
void PrintFunction (SmartPtr< Base2 > b)
void PrintFunction (SmartPtr< Base3 > b)
void PrintFunctionIntermediate (Intermediate0 &b)
void PrintFunctionIntermediate (SmartPtr< Intermediate1 > b)
void PrintHelloWorldToScreen ()
template<typename T >
string PrintParametersIn (const T &thefunc, const char *highlightclassname)
string PrintParametersOut (const ExportedFunctionBase &thefunc)
template<typename T >
void PrintStdVector (std::vector< T > vec)
template<typename T >
void PrintStdVectorOfClass (std::vector< T > vec)
void PrintStringTest (const std::string &str)
template<typename T >
static bool PushLuaStackEntryToParamStack (ParameterStack &ps, lua_State *L, int index, bool bIsVector)
template<typename T >
static bool PushLuaStackPointerEntryToParamStack (ParameterStack &ps, lua_State *L, int index, const char *baseClassName, bool bIsVector)
void RegisterBridge_AdaptiveTools (Registry &reg, string grp)
void RegisterBridge_AlgebraCommon (Registry &reg, string grp)
void RegisterBridge_AlgebraOrdering (Registry &reg, string grp)
void RegisterBridge_ConstrainedLinearIterator (Registry &reg, string grp)
void RegisterBridge_Constraints (Registry &reg, string grp)
void RegisterBridge_DiscAlgebra (Registry &reg, string grp)
void RegisterBridge_DiscCommon (Registry &reg, std::string grp=UG4_GRP)
Registers the common part of lib_discretization.
void RegisterBridge_DiscCommon (Registry &reg, string parentGroup)
void RegisterBridge_Domain (Registry &reg, std::string grp=UG4_GRP)
Registers the domain object and related methods.
void RegisterBridge_Domain (Registry &reg, string grp)
void RegisterBridge_DomainDependentPreconditioner (Registry &reg, string grp)
void RegisterBridge_DomainDisc (Registry &reg, string grp)
void RegisterBridge_DomainRayTracing (Registry &reg, std::string grp=UG4_GRP)
Registers methods to perform ray-tracing on domains.
void RegisterBridge_DomainRayTracing (Registry &reg, string grp)
void RegisterBridge_Eigensolver (Registry &reg, string grp)
void RegisterBridge_ElemDiscs (Registry &reg, std::string grp=UG4_GRP)
Registers the element discretizations.
void RegisterBridge_ElemDiscs (Registry &reg, string grp)
void RegisterBridge_Evaluate (Registry &reg, string grp)
void RegisterBridge_FiniteVolume (Registry &reg, string grp)
void RegisterBridge_GPU (Registry &reg, string grp)
void RegisterBridge_Grid (Registry &reg, std::string grp=UG4_GRP)
registers lib-grid interface methods at the registry.
void RegisterBridge_Grid (Registry &reg, string parentGroup)
void RegisterBridge_GridFunction (Registry &reg, string grp)
void RegisterBridge_Integrate (Registry &reg, string grp)
void RegisterBridge_Interpolate (Registry &reg, string grp)
void RegisterBridge_LoadBalancing (Registry &reg, std::string grp=UG4_GRP)
registers LoadBalancer, partitioners, etc
void RegisterBridge_LoadBalancing (Registry &reg, string grp)
void RegisterBridge_ManifoldUtil (Registry &reg, string grp)
void RegisterBridge_MaxError (Registry &reg, string grp)
void RegisterBridge_Misc (Registry &reg, std::string grp=UG4_GRP)
void RegisterBridge_Misc (Registry &reg, string parentGroup)
void RegisterBridge_MultiGrid (Registry &reg, string grp)
void RegisterBridge_Obstacle (Registry &reg, string grp)
void RegisterBridge_Ordering (Registry &reg, string grp)
void RegisterBridge_OrthoPoly (Registry &reg, std::string grp=UG4_GRP)
registers orthogonal polynomials
void RegisterBridge_Output (Registry &reg, string grp)
void RegisterBridge_PCL (Registry &reg, std::string grp=UG4_GRP)
registers methods for a parallel environment
void RegisterBridge_PCL (Registry &reg, string parentGroup)
void RegisterBridge_PeriodicBoundary (Registry &reg, std::string grp=UG4_GRP)
Registers periodic boundary identification.
void RegisterBridge_PeriodicBoundary (Registry &reg, string grp)
void RegisterBridge_PILUT (Registry &reg, std::string grp)
void RegisterBridge_Preconditioner (Registry &reg, string grp)
void RegisterBridge_Profiler (Registry &reg, std::string grp=UG4_GRP)
registers access to profiling functions at the registry
void RegisterBridge_Profiler (Registry &reg, string parentGroup)
void RegisterBridge_Raster (Registry &reg, std::string grp=UG4_GRP)
registers rasters, e.g. for 1,2,3 dimensional image data or density distributions
void RegisterBridge_Raster (Registry &reg, string parentGroup)
void RegisterBridge_ReferenceMappingTest (Registry &reg, std::string grp=UG4_GRP)
registers reference mapping test functionality (common)
void RegisterBridge_ReferenceMappingTest (Registry &reg, string grp)
void RegisterBridge_Refinement (Registry &reg, std::string grp=UG4_GRP)
Registers refiners and marking methods.
void RegisterBridge_Refinement (Registry &reg, string grp)
void RegisterBridge_Restart (Registry &reg, string grp)
void RegisterBridge_Schur (Registry &reg, string grp)
void RegisterBridge_Selection (Registry &reg, std::string grp=UG4_GRP)
Registers methods to perform selections on the elements of a domain.
void RegisterBridge_Selection (Registry &reg, string grp)
void RegisterBridge_Solver (Registry &reg, string grp)
void RegisterBridge_SuperLU (TRegistry &reg, string grp)
void RegisterBridge_Test (Registry &reg, std::string grp=UG4_GRP)
registers tests for the interface methods at the registry.
void RegisterBridge_Test (Registry &reg, string parentGroup)
void RegisterBridge_Transform (Registry &reg, std::string grp=UG4_GRP)
Registers methods to transform the vertices of a domain.
void RegisterBridge_Transform (Registry &reg, string grp)
void RegisterBridge_UserData (Registry &reg, std::string grp=UG4_GRP)
registers user data
void RegisterBridge_UserData (Registry &reg, string grp)
void RegisterBridge_Util (Registry &reg, std::string grp=UG4_GRP)
registers some util methods like path-access and script-parsing.
void RegisterBridge_Util (Registry &reg, string parentGroup)
void RegisterBridge_VecMath (Registry &reg, std::string grp=UG4_GRP)
Registers types and functions for 1, 2, 3 and 4 dimensional vector math.
void RegisterBridge_VecMath (Registry &reg, string parentGroup)
template<typename Functionality >
void RegisterCommon (Registry &reg, std::string grp)
bool RegisterConverter (Registry &reg, const char *parentGroup)
template<int dim>
static void RegisterDegeneratedLayerManager (Registry &reg, string grp)
template<typename Functionality >
void RegisterDimension1dDependent (Registry &reg, std::string grp)
template<typename Functionality >
void RegisterDimension2d3dDependent (Registry &reg, std::string grp)
template<typename Functionality >
void RegisterDimension2dDependent (Registry &reg, std::string grp)
template<typename Functionality >
void RegisterDimension3dDependent (Registry &reg, std::string grp)
template<typename Functionality >
void RegisterDimensionDependent (Registry &reg, std::string grp)
template<typename Functionality >
void RegisterDomain1dDependent (Registry &reg, std::string grp)
template<typename Functionality >
void RegisterDomain2d3dDependent (Registry &reg, std::string grp)
template<typename Functionality >
void RegisterDomain2dDependent (Registry &reg, std::string grp)
template<typename Functionality >
void RegisterDomain3dDependent (Registry &reg, std::string grp)
template<int dim>
void RegisterGeometry (Registry &reg, string grp)
void RegisterGridBridge_Balancing (Registry &reg, std::string parentGroup)
void RegisterGridBridge_Balancing (Registry &reg, string parentGroup)
void RegisterGridBridge_Debug (Registry &reg, std::string parentGroup)
void RegisterGridBridge_Debug (Registry &reg, string parentGroup)
void RegisterGridBridge_FileIO (Registry &reg, std::string parentGroup)
void RegisterGridBridge_FileIO (Registry &reg, string parentGroup)
void RegisterGridBridge_Grid (Registry &reg, std::string parentGroup)
void RegisterGridBridge_Grid (Registry &reg, string parentGroup)
void RegisterGridBridge_Layers (Registry &reg, std::string parentGroup)
void RegisterGridBridge_Layers (Registry &reg, string parentGroup)
void RegisterGridBridge_Misc (Registry &reg, std::string parentGroup)
void RegisterGridBridge_Misc (Registry &reg, string parentGroup)
void RegisterGridBridge_Refinement (Registry &reg, std::string parentGroup)
void RegisterGridBridge_Refinement (Registry &reg, string parentGroup)
void RegisterGridBridge_Selector (Registry &reg, std::string parentGroup)
void RegisterGridBridge_Selector (Registry &reg, string parentGroup)
void RegisterGridBridge_SubsetHandler (Registry &reg, std::string parentGroup)
void RegisterGridBridge_SubsetHandler (Registry &reg, string parentGroup)
bool RegisterInfoCommands (bridge::Registry &reg, const char *grp)
registers info commands TypeInfo, ClassUsage and others
void RegisterLuaUserData (Registry &reg, std::string grp)
void RegisterLuaUserData (Registry &reg, string grp)
template<class TValue , int TDIM>
static void RegisterRaster (Registry &reg, string name, string grp)
template<class TValue , int dim>
static void RegisterRasterUserData (Registry &reg, string name, string grp)
bool RegisterSerializationCommands (Registry &reg, const char *parentGroup)
UG_API void RegisterStandardBridges (Registry &reg, std::string grp=UG4_GRP)
registers all standard interfaces.
void RegisterStandardBridges (Registry &reg, string parentGroup)
template<typename TData , int dim, typename TTraits = user_data_traits<TData>>
void RegisterUserDataType (Registry &reg, string grp)
template<typename TData , int dim, typename TTraits = user_data_traits<TData>>
void RegisterUserDataTypeA (Registry &reg, string grp)
template<typename TData , int dim, typename TTraits = user_data_traits<TData>>
void RegisterUserDataTypeB (Registry &reg, string grp)
static void RegisterVecMathBridge_DimIndep (Registry &reg, string grp)
template<typename T >
const std::vector< T > & ReturnConstStdVectorRef_Number ()
const std::vector< std::string > & ReturnConstStdVectorRef_String ()
template<typename T >
const std::vector< T > & ReturnConstStdVectorRefOfClass ()
template<typename T >
const std::vector< T > & ReturnConstStdVectorRefOfClassSP ()
template<typename T >
std::vector< T > ReturnStdVector_Number ()
std::vector< std::string > ReturnStdVector_String ()
template<typename T >
std::vector< T > ReturnStdVectorOfClass ()
int RunShell (const char *prompt)
bool SaveGrid (Grid &grid, const char *filename)
bool SaveGrid (Grid &grid, const ISubsetHandler &sh, const char *filename)
bool SaveGrid (Grid &grid, ISubsetHandler &sh, const char *filename)
bool SaveGridHierarchy (MultiGrid &mg, const char *filename)
bool ScriptHasClass (const char *classname)
bool ScriptHasClassGroup (const char *classname)
void ScriptPrintClassHierarchy (const char *classname)
void ScriptPrintClassUsage (const char *classname)
void SetDebugLevel (const char *strTag, int level)
void SetLuaNamespace (string name, string value)
void SetLuaNamespaceInTable (string name, string value)
void SetMinSecondsUntilProgress (size_t s)
void SetOtherCompletions (const char **otherCompletions, int nr)
SmartPtr< MultipleDerived > SmartMultipleDerivedImpl ()
void SmartTestArrived (SPSmartTest test)
int SmartTestFunc (SmartPtr< Test > test)
SmartPtr< Test > SmartTestImpl ()
template<typename TBase , typename TDerived >
void * StaticVoidCast (void *DerivVoidPtr)
static cast function for two classes
string StdStringTest ()
const char * StringTest ()
int TestFunc (Test &t)
calls non-const print on non-const object of class Test
void TestMsgCallback (const TestMessage &msg)
bool TestNTree (const char *filename)
void TestPageContainer ()
const Test & ToConst (Test &test)
returns a const reference to a non-const object of class Test
void ug_cacheline (string str)
string ug_readline (const char *prompt, bool &quit)
int UGTypeInfo (const char *p)
Prints info to a lua type.
Unregistered * UnregisteredParameterTest (Unregistered &unregistered)
void WriteLUAObject (lua_State *L, std::string name, std::ostream &s)
void WriteLUAObject2 (lua_State *L, std::string name, std::ostream &s)
void RegisterBridge_OrthoPoly (Registry &reg, string parentGroup)
Variables
int iOtherCompletitionsLength
static const size_t NUM_ALGEBRA_TYPES = boost::mpl::size<CompileAlgebraList>::type::value - 1
const char ** pOtherCompletitions =NULL
const char * REFINEMENT_MESSAGE_NAME = "MSG_GRID_ADAPTION"
static int UG4_DIM = -1
the dimension to which ug was initialized through InitUG
const char * UG4_GRP = "/ug4"
string for ug4 group
Function Documentation
ClassInstantiations()
UG_API bool ug::bridge::ClassInstantiations (const char * classname)
this function prints all objects which are of a certain class
Parameters
classname the class name to be searched
Returns
true if class found, otherwise false
References ClassNameVecContains(), ug::bridge::Registry::get_class(), GetClassNames(), ug::script::GetDefaultLuaState(), GetUGRegistry(), LUA_STACK_CHECK, UG_ASSERT, and UG_LOG.
Referenced by ClassUsage(), RegisterInfoCommands(), and UGTypeInfo().
ClassUsage()
string ug::bridge::ClassUsage (const char * classname)
Parameters
classname the class to print usage in functions/member functions of (and all its subclasses) . class in in/out parameters is highlighted with [class].
Returns
true if class found, otherwise fals
References ug::bridge::IExportedClass::class_names(), ClassInstantiations(), ClassUsageExact(), ug::bridge::Registry::get_class(), and GetUGRegistry().
Referenced by ScriptPrintClassUsage().
convert()
int ug::bridge::convert (const char * functionName)
References ug::LUAParserClass::createC(), ug::LUAParserClass::parse_luaFunction(), and UG_LOG.
Referenced by RegisterConverter().
convertVM()
int ug::bridge::convertVM (const char * functionName)
References ug::LUAParserClass::createVM(), ug::LUAParserClass::parse_luaFunction(), ug::VMAdd::print(), ug::LUAParserClass::print_variable_names(), and UG_LOG.
Referenced by RegisterConverter().
CreateHierarchy()
bool ug::bridge::CreateHierarchy (MultiGrid & mg, size_t numRefs)
References numRefs, PROFILE_FUNC_GROUP, and ug::IRefiner::refine().
Referenced by RegisterGridBridge_Refinement().
CreateSmoothHierarchy()
bool ug::bridge::CreateSmoothHierarchy (MultiGrid & mg, size_t numRefs)
References ug::aPosition, ug::aPosition1, ug::aPosition2, ug::Grid::has_vertex_attachment(), make_sp(), ug::MakeGeometry3d(), numRefs, PROFILE_FUNC_GROUP, ProjectToLimitPLoop(), ug::IRefiner::refine(), UG_LOG, and SmartPtr< T, FreePolicy >::valid().
Referenced by RegisterGridBridge_Refinement().
DebugShell()
script::debug_return ug::bridge::DebugShell ()
References ug::script::DEBUG_CONTINUE, ug::script::DEBUG_EXIT, ug::script::DEBUG_FINISH, ug::script::DEBUG_NEXT, ug::script::DEBUG_STEP, ug::script::DebugBacktrace(), ug::script::DebugDown(), ug::script::DebugList(), ug::script::DebugUp(), ug::UGError::get_msg(), LuaStackTrace(), ug::UGError::num_msg(), pcl::NumProcs(), ug::script::ParseAndExecuteBuffer(), PROFILE_BEGIN, SetOtherCompletions(), ug::script::LuaError::show_msg(), ug_cacheline(), UG_DEBUG_PROMPT, UG_LOG, ug_readline(), and UGTypeInfo().
Referenced by InitShell().
EnableLUA2C()
void ug::bridge::EnableLUA2C (bool b)
References UG_LOG, ug::useLua2VM, and ug::useLuaCompiler.
Referenced by RegisterInfoCommands().
EnableLUA2VM()
void ug::bridge::EnableLUA2VM (bool b)
References ug::useLua2VM, and ug::useLuaCompiler.
Referenced by RegisterInfoCommands().
FunctionInfo()
UG_API std::string ug::bridge::FunctionInfo (lua_State * L, bool bComplete, const char * functionName = NULL)
prints out information for a lua function (a function defined in lua script)
Parameters
L the lua state
bComplete if complete, we print the source code of the function
Returns
0
References ug::GetFileLine(), GetFileLinesLUA(), and LUA_STACK_CHECK.
Referenced by ug::bridge::lua::ExecuteMethod(), GetGlobalFunctionInfo(), GetMemberFunctionInfo(), LuaClassMethodInfo(), LuaList_cfunctions(), ug::bridge::lua::LuaProxyFunction(), and UGTypeInfo().
GetClassNameNode()
UG_API const ClassNameNode * ug::bridge::GetClassNameNode (lua_State * L, int index)
Parameters
L the lua state
index the index of the lua object
Returns
the corresponing ClassNameNode
See also
ClassNameNode
References LUA_STACK_CHECK.
Referenced by GetLuaTypeString().
GetClassNames() [1/2]
UG_API const std::vector< const char * > * ug::bridge::GetClassNames (lua_State * L, const char * name)
Parameters
L the lua state
name the name of the lua object
Returns
the class names of the object or NULL if not found
References name, and p.
Referenced by ClassInstantiations(), LuaClassMethodInfo(), and LuaList_classInstantiations().
GetClassNames() [2/2]
UG_API const std::vector< const char * > * ug::bridge::GetClassNames (lua_State * L, int index)
Parameters
L the lua state
index the index of the lua object
Returns
a std::vector of class names
References LUA_STACK_CHECK, and p.
Referenced by GetMemberFunctionCompletitions(), and GetMemberFunctionInfo().
GetFileLinesLUA()
string ug::bridge::GetFileLinesLUA (const char * filename, size_t fromline, size_t toline)
this function also includes all lines before fromline which begin with – (lua comments) and adds line numbers
Parameters
filename
fromline
toline
Returns
string with lines
References ug::GetLogAssistant().
Referenced by FunctionInfo().
GetLuaFileAndLine() [1/2]
UG_API std::string ug::bridge::GetLuaFileAndLine (lua_State * L)
returns the current file and line (
returns the current file and line-number and line-content (
See also
LuaStackTrace).
References ug::GetFileLine(), ug::GetLogAssistant(), and PROFILE_FUNC.
Referenced by GetLuaFileAndLineNumber(), and GetLuaLine().
GetLuaFileAndLine() [2/2]
bool ug::bridge::GetLuaFileAndLine (lua_State * L, std::string & file, size_t & line)
returns the current file and line (
See also
LuaStackTrace).
Referenced by ug::bridge::lua::LuaConstructor(), ug::bridge::lua::LuaProxyFunction(), ug::bridge::lua::LuaProxyGroupConstructor(), and ug::bridge::lua::LuaProxyMethod().
GetLuaFileAndLineNumber()
UG_API std::string ug::bridge::GetLuaFileAndLineNumber (lua_State * L)
returns the current file and line-number
References GetLuaFileAndLine().
GetLuaGlobal_classInstantiations()
void ug::bridge::GetLuaGlobal_classInstantiations (std::vector< std::string > & classInstantiations)
References GetLuaGlobals().
Referenced by LuaList_classInstantiations().
GetLuaGlobal_functions()
void ug::bridge::GetLuaGlobal_functions (std::vector< std::string > & functions)
References GetLuaGlobals().
Referenced by LuaList_cfunctions().
GetLuaGlobal_internalFunctions()
void ug::bridge::GetLuaGlobal_internalFunctions (std::vector< std::string > & internalFunctions)
References GetLuaGlobals().
Referenced by LuaList_internalFunctions().
GetLuaGlobal_luaObjects()
void ug::bridge::GetLuaGlobal_luaObjects (std::vector< std::string > & luaObjects)
References GetLuaGlobals().
Referenced by LuaList_luaObjects().
GetLuaGlobal_scriptFunctions()
void ug::bridge::GetLuaGlobal_scriptFunctions (std::vector< std::string > & scriptFunctions)
References GetLuaGlobals().
Referenced by LuaList_scriptFunctions().
GetLuaGlobals()
void ug::bridge::GetLuaGlobals (std::vector< std::string > * functions, std::vector< std::string > * internalFunctions, std::vector< std::string > * scriptFunctions, std::vector< std::string > * luaObjects, std::vector< std::string > * classInstantiations)
function to list all objects of the default LUA state
Parameters
functions
internalFunctions
scriptFunctions
luaObjects
classInstantiations
References FindFunction(), ug::bridge::Registry::get_class(), ug::script::GetDefaultLuaState(), GetUGRegistry(), and LUA_STACK_CHECK.
Referenced by GetLuaGlobal_classInstantiations(), GetLuaGlobal_functions(), GetLuaGlobal_internalFunctions(), GetLuaGlobal_luaObjects(), and GetLuaGlobal_scriptFunctions().
GetLuaLine()
UG_API std::string ug::bridge::GetLuaLine (lua_State * L)
returns the current line-content
References ug::GetFileLine(), ug::GetLogAssistant(), GetLuaFileAndLine(), and PROFILE_FUNC.
Referenced by ug::bridge::lua::GetColonWarning().
GetLuaNamespace() [1/2]
UG_API bool ug::bridge::GetLuaNamespace (lua_State * L, std::string name)
GetLuaNamespace() [2/2]
bool ug::bridge::GetLuaNamespace (lua_State * L, string name)
searches for a namespaces (lists) and pushes it onto the stack
Parameters
L the lua state
name name of the namespace. also nested namespaces are allowed (like struc1.struc2)
Returns
true if namespace found
References LUA_STACK_CHECK, name, and ug::TokenizeString().
Referenced by GetLUAScriptFunctionDefined(), GetNamespaceCompletitions(), LuaGetBoolean(), LuaGetNumber(), LuaGetString(), ug::LUAParserClass::parse_luaFunction(), and UGTypeInfo().
GetLUAScriptFunctionDefined()
std::string ug::bridge::GetLUAScriptFunctionDefined (const char * functionName)
returns file and line of defined script function
References ug::script::GetDefaultLuaState(), GetLuaNamespace(), and LUA_STACK_CHECK.
Referenced by ug::LuaUserData< TData, dim, TRet >::check_callback_returns().
GetLuaTypeString()
UG_API std::string ug::bridge::GetLuaTypeString (lua_State * L, int index)
returns a String describing the content of the lua stack at a given index and all types it is compatible with (for ex. "2" is string and number)
Parameters
L the lua state
index lua stack index to get type string of
Returns
type string
References ug::bridge::ClassNameNode::empty(), GetClassNameNode(), and ug::bridge::ClassNameNode::name().
Referenced by ug::bridge::lua::GetLuaParametersString(), ug::bridge::lua::GetTypeMismatchString(), LuaList_luaObjects(), LuaPrintTable(), UGTypeInfo(), and WriteLUAObject2().
InitShell()
void ug::bridge::InitShell ()
References CompletionFunction(), DebugShell(), and ug::script::SetDebugShell().
Referenced by ug_init_luashell().
InitSignals()
void ug::bridge::InitSignals ()
References UG_LOG.
Referenced by RegisterInfoCommands().
InitUG()
void ug::bridge::InitUG (int dim, const AlgebraType & algType, bool verbose)
Sets the default classes of class-groups based on a tags.
If a class has a tag (e.g. "dim=1d", "dim=2d" or "dim=3d") then it will be set as default - depending on the given tags.
References ug::AlgebraType::blocksize(), dim, ug::bridge::Registry::get_class_group(), ug::bridge::ClassGroupDesc::get_class_tag(), GetAlgebraTag(), GetDimensionTag(), GetUGRegistry(), ug::bridge::Registry::num_class_groups(), ug::bridge::ClassGroupDesc::num_classes(), pcl::NumProcs(), PROFILE_FUNC, ug::bridge::ClassGroupDesc::set_default_class(), ug::AlgebraType::type(), UG4_DIM, UG_LOG, UG_THROW, and verbose.
IsValidPtr()
template<class T > static bool ug::bridge::IsValidPtr (T * o) static
LoadGrid() [1/2]
bool ug::bridge::LoadGrid (Grid & grid, const char * filename)
References ug::LoadGridFromFile(), and PROFILE_FUNC_GROUP.
Referenced by RegisterGridBridge_FileIO().
LoadGrid() [2/2]
bool ug::bridge::LoadGrid (Grid & grid, ISubsetHandler & sh, const char * filename)
References ug::LoadGridFromFile(), and PROFILE_FUNC_GROUP.
LuaClassMethodInfo()
UG_API std::string ug::bridge::LuaClassMethodInfo (lua_State * L, int index, const ExportedMethod & thefunc)
prints out information for a method of a class
Parameters
L the lua state
index index of the class object on the lua stack
thefunc method to print
Returns
0
References FunctionInfo(), and GetClassNames().
Referenced by ug::bridge::lua::ExecuteMethod(), and ug::bridge::lua::LuaProxyMethod().
LuaCurrentLine()
UG_API std::string ug::bridge::LuaCurrentLine (lua_State * L)
Parameters
L
Returns
the current line with content example: @/Users/mrupp/Documents/workspace/ug4svn/apps/amg//setup.lua:576 local dim = p.approxSpace:get_dim()
prints the current lua line
Parameters
L
References ug::GetFileLine(), and LuaGetLastLine().
LuaGetBoolean()
UG_API bool ug::bridge::LuaGetBoolean (lua_State * L, const char * name, bool notAvailable)
returns a boolean to a lua-variable.
Parameters
L the lua state
name name of the variable. namespaces are possible (like math.pi)
notAvailable return value if variable was not found
References GetLuaNamespace(), LUA_STACK_CHECK, and name.
LuaGetLastLine()
UG_API void ug::bridge::LuaGetLastLine (lua_State * L, lua_Debug entry)
Parameters
L
entry (out) returns the lua_Debug entry associated with the deepest call stack level (the "current line")
searches the lua stack for the first valid line info
Parameters
L the lua state
entry returned lua_Debug structure
Referenced by LuaCurrentLine().
LuaGetNumber()
UG_API double ug::bridge::LuaGetNumber (lua_State * L, const char * name, double notAvailable)
returns an integer to a lua-variable.
Parameters
L the lua state
name name of the variable. namespaces are possible (like math.pi)
notAvailable return value if variable was not found
References GetLuaNamespace(), LUA_STACK_CHECK, and name.
Referenced by ug::LUAParserClass::createVM(), and ug::LUAParserClass::getVar().
LuaGetScriptFunctionString()
UG_API std::string ug::bridge::LuaGetScriptFunctionString (lua_State * L, int index = -1)
prints the source of a lua script function which is on top of the stack
Parameters
L the lua state
References ug::GetFileLine(), LUA_STACK_CHECK, and p.
Referenced by LuaList_scriptFunctions(), and LuaPrintTable().
LuaGetString()
UG_API std::string ug::bridge::LuaGetString (lua_State * L, const char * name, const char * notAvailable)
returns the string to a lua-variable.
Parameters
L the lua state
name name of the variable. namespaces are possible (like math.pi)
notAvailable return value if variable was not found
References GetLuaNamespace(), LUA_STACK_CHECK, and name.
LuaList()
void ug::bridge::LuaList ()
References LuaList_cfunctions(), LuaList_classes(), LuaList_internalFunctions(), LuaList_luaObjects(), and LuaList_scriptFunctions().
Referenced by RegisterInfoCommands().
LuaList_cfunctions()
void ug::bridge::LuaList_cfunctions ()
References FunctionInfo(), GetLuaGlobal_functions(), GetUGRegistry(), and UG_LOG.
Referenced by LuaList(), and RegisterInfoCommands().
LuaList_classes()
void ug::bridge::LuaList_classes ()
References classes, ug::bridge::Registry::get_class(), GetUGRegistry(), ug::bridge::IExportedClass::name(), ug::bridge::Registry::num_classes(), and UG_LOG.
Referenced by LuaList(), and RegisterInfoCommands().
LuaList_classInstantiations()
void ug::bridge::LuaList_classInstantiations ()
References GetClassNames(), ug::script::GetDefaultLuaState(), GetLuaGlobal_classInstantiations(), ug::IsLonger(), and UG_LOG.
Referenced by RegisterInfoCommands().
LuaList_internalFunctions()
void ug::bridge::LuaList_internalFunctions ()
References GetLuaGlobal_internalFunctions(), and UG_LOG.
Referenced by LuaList(), and RegisterInfoCommands().
LuaList_luaObjects()
void ug::bridge::LuaList_luaObjects ()
References ug::script::GetDefaultLuaState(), GetLuaGlobal_luaObjects(), GetLuaTypeString(), ug::IsLonger(), p, and UG_LOG.
Referenced by LuaList(), and RegisterInfoCommands().
LuaList_scriptFunctions()
void ug::bridge::LuaList_scriptFunctions ()
References ug::script::GetDefaultLuaState(), GetLuaGlobal_scriptFunctions(), ug::IsLonger(), LuaGetScriptFunctionString(), and UG_LOG.
Referenced by LuaList(), and RegisterInfoCommands().
LuaPrintTable()
UG_API void ug::bridge::LuaPrintTable (lua_State * L, size_t iSpace, int index)
prints the source of a lua script function which is on top of the stack
Parameters
L the lua state
L the lua state
index lua stack index of the table
References GetLuaTypeString(), LUA_STACK_CHECK, LuaGetScriptFunctionString(), name, ug::repeat(), and UG_LOG.
Referenced by UGTypeInfo().
LuaStackToParams()
int ug::bridge::LuaStackToParams (ParameterStack & ps, const ParameterInfo & psInfo, lua_State * L, int offsetToFirstParam = 0)
copies parameter values from the lua-stack to a parameter-list.
Returns
The index of the first bad parameter starting from 1. Returns 0 if everything went right. Returns -1 if the number of parameters did not match.
References ug::bridge::ParameterInfo::class_name(), ug::bridge::ParameterInfo::is_vector(), PushLuaStackPointerEntryToParamStack(), ug::bridge::ParameterInfo::size(), ug::bridge::ParameterInfo::type(), ug::Variant::VT_BOOL, ug::Variant::VT_CONST_POINTER, ug::Variant::VT_CONST_SMART_POINTER, ug::Variant::VT_CSTRING, ug::Variant::VT_DOUBLE, ug::Variant::VT_FLOAT, ug::Variant::VT_INT, ug::Variant::VT_POINTER, ug::Variant::VT_SIZE_T, ug::Variant::VT_SMART_POINTER, and ug::Variant::VT_STDSTRING.
Referenced by ug::bridge::lua::ExecuteMethod(), ug::bridge::lua::LuaConstructor(), and ug::bridge::lua::LuaProxyFunction().
LuaStackTrace()
UG_API void ug::bridge::LuaStackTrace (int fromLevel)
prints information about lua's call stack (file:line source).
References ug::script::GetDefaultLuaState(), LuaStackTraceString(), and UG_LOG.
Referenced by ug::script::DebugBacktrace(), DebugShell(), ug::script::luaCallStackError(), and RegisterInfoCommands().
LuaStackTraceString() [1/2]
UG_API std::string ug::bridge::LuaStackTraceString ()
References ug::script::GetDefaultLuaState().
Referenced by LuaStackTrace().
LuaStackTraceString() [2/2]
UG_API std::string ug::bridge::LuaStackTraceString (lua_State * L, int fromLevel, int toLevel)
prints information about lua's call stack (file:line source).
this function returns e.g. 1 @/Users/mrupp/Documents/workspace/ug4svn/apps/amg//setup.lua:576 local dim = p.approxSpace:get_dim() 2 @/Users/mrupp/Documents/workspace/ug4svn/apps/amg//setup.lua:649 amgsetup.CreateApproxSpaceAndDisc() 3 @/Users/mrupp/Documents/workspace/ug4svn/apps/amg/famg_laplace.lua:21 amgsetup.LoadStdDomAndApproxSpace()
Parameters
L
fromLevel where to start
toLevel how far we want to go back
Returns
a list list
Parameters
L the lua state
backtraceLevel number of calls to display (<= 0 -> all)
References ug::GetFileLine(), ug::StringTableStream::to_string(), and ug::TrimString().
Referenced by lua_backtrace(), and ug::bridge::lua::PrintLUACallStack().
LUAStringEscape()
string ug::bridge::LUAStringEscape (string s)
References ug::ReplaceAll(), and s.
Referenced by WriteLUAObject2().
LuaWrite()
void ug::bridge::LuaWrite (const char * filename, const char * obj)
References ug::script::GetDefaultLuaState(), and WriteLUAObject().
Referenced by RegisterSerializationCommands().
LuaWriteCout()
void ug::bridge::LuaWriteCout (const char * obj)
References ug::script::GetDefaultLuaState(), and WriteLUAObject().
Referenced by RegisterSerializationCommands().
ParamStackEntryToLuaStack()
template<typename T > static void ug::bridge::ParamStackEntryToLuaStack (const ParameterStack & ps, lua_State * L, int index, bool bIsVector) static
References ug::bridge::ParameterStack::to().
ParamStackPointerEntryToLuaStack()
template<typename T > static void ug::bridge::ParamStackPointerEntryToLuaStack (const ParameterStack & ps, lua_State * L, int index, bool bIsVector) static
References ug::bridge::ParameterInfo::class_name(), and ug::bridge::ParameterStack::to().
ParamsToLuaStack()
int ug::bridge::ParamsToLuaStack (const ParameterStack & ps, lua_State * L)
Pushes the parameter-values to the Lua-Stack.
Returns
The number of items pushed to the stack.
References ug::bridge::ParameterInfo::is_vector(), ug::bridge::ParameterInfo::size(), ug::bridge::ParameterInfo::type(), UG_THROW, ug::Variant::VT_BOOL, ug::Variant::VT_CONST_POINTER, ug::Variant::VT_CONST_SMART_POINTER, ug::Variant::VT_CSTRING, ug::Variant::VT_DOUBLE, ug::Variant::VT_FLOAT, ug::Variant::VT_INT, ug::Variant::VT_POINTER, ug::Variant::VT_SIZE_T, ug::Variant::VT_SMART_POINTER, and ug::Variant::VT_STDSTRING.
Referenced by ug::bridge::lua::ExecuteMethod(), ug::bridge::lua::LuaProxyFunction(), and ug::bridge::lua::LuaToStringDefault().
print()
void ug::bridge::print (const std::string & s)
References printf(), and s.
PrintClassSubHierarchy()
void ug::bridge::PrintClassSubHierarchy (ClassHierarchy & c, int level)
References ug::bridge::ClassHierarchy::name, ug::bridge::ClassHierarchy::subclasses, and UG_LOG.
Referenced by ClassHierarchyString().
PrintParametersIn()
template<typename T > string ug::bridge::PrintParametersIn (const T & thefunc, const char * highlightclassname)
References ParameterToString().
PrintParametersOut()
string ug::bridge::PrintParametersOut (const ExportedFunctionBase & thefunc)
References ParameterToString(), ug::bridge::ExportedFunctionBase::params_out(), and ug::bridge::ParameterInfo::size().
Referenced by FunctionInfo().
PushLuaStackEntryToParamStack()
template<typename T > static bool ug::bridge::PushLuaStackEntryToParamStack (ParameterStack & ps, lua_State * L, int index, bool bIsVector) static
References ug::bridge::ParameterStack::push().
PushLuaStackPointerEntryToParamStack()
template<typename T > static bool ug::bridge::PushLuaStackPointerEntryToParamStack (ParameterStack & ps, lua_State * L, int index, const char * baseClassName, bool bIsVector) static
References ug::bridge::ParameterStack::push().
Referenced by LuaStackToParams(), and WriteLUAObject2().
RegisterBridge_AdaptiveTools()
void ug::bridge::RegisterBridge_AdaptiveTools (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_AlgebraCommon()
void ug::bridge::RegisterBridge_AlgebraCommon (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_AlgebraOrdering()
void ug::bridge::RegisterBridge_AlgebraOrdering (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_ConstrainedLinearIterator()
void ug::bridge::RegisterBridge_ConstrainedLinearIterator (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
RegisterBridge_Constraints()
void ug::bridge::RegisterBridge_Constraints (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_DiscAlgebra()
void ug::bridge::RegisterBridge_DiscAlgebra (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Domain()
void ug::bridge::RegisterBridge_Domain (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_DomainDependentPreconditioner()
void ug::bridge::RegisterBridge_DomainDependentPreconditioner (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_DomainDisc()
void ug::bridge::RegisterBridge_DomainDisc (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_DomainRayTracing()
void ug::bridge::RegisterBridge_DomainRayTracing (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Eigensolver()
void ug::bridge::RegisterBridge_Eigensolver (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_ElemDiscs()
void ug::bridge::RegisterBridge_ElemDiscs (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Evaluate()
void ug::bridge::RegisterBridge_Evaluate (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_FiniteVolume()
void ug::bridge::RegisterBridge_FiniteVolume (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_GPU()
void ug::bridge::RegisterBridge_GPU (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
RegisterBridge_Grid()
void ug::bridge::RegisterBridge_Grid (Registry & reg, string parentGroup)
References RegisterGridBridge_Balancing(), RegisterGridBridge_Debug(), RegisterGridBridge_FileIO(), RegisterGridBridge_Grid(), RegisterGridBridge_Layers(), RegisterGridBridge_Misc(), RegisterGridBridge_Refinement(), RegisterGridBridge_Selector(), RegisterGridBridge_SubsetHandler(), and UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_GridFunction()
void ug::bridge::RegisterBridge_GridFunction (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Integrate()
void ug::bridge::RegisterBridge_Integrate (Registry & reg, string grp)
References ug::bridge::Registry::add_function(), ug::TestQuadRule(), and UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Interpolate()
void ug::bridge::RegisterBridge_Interpolate (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_LoadBalancing()
void ug::bridge::RegisterBridge_LoadBalancing (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_ManifoldUtil()
void ug::bridge::RegisterBridge_ManifoldUtil (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_MaxError()
void ug::bridge::RegisterBridge_MaxError (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_MultiGrid()
void ug::bridge::RegisterBridge_MultiGrid (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Obstacle()
void ug::bridge::RegisterBridge_Obstacle (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Ordering()
void ug::bridge::RegisterBridge_Ordering (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Output()
void ug::bridge::RegisterBridge_Output (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_PeriodicBoundary()
void ug::bridge::RegisterBridge_PeriodicBoundary (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_PILUT()
void ug::bridge::RegisterBridge_PILUT (Registry & reg, std::string grp)
Referenced by RegisterStandardBridges().
RegisterBridge_Preconditioner()
void ug::bridge::RegisterBridge_Preconditioner (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Raster()
void ug::bridge::RegisterBridge_Raster (Registry & reg, string parentGroup)
Referenced by RegisterStandardBridges().
RegisterBridge_ReferenceMappingTest()
void ug::bridge::RegisterBridge_ReferenceMappingTest (Registry & reg, string grp)
References ug::bridge::Registry::add_function(), ug::EdgeReferenceMappingTest(), ug::OctReferenceMappingTest(), and ug::TetReferenceMappingTest().
Referenced by RegisterStandardBridges().
RegisterBridge_Refinement()
void ug::bridge::RegisterBridge_Refinement (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Restart()
void ug::bridge::RegisterBridge_Restart (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Schur()
void ug::bridge::RegisterBridge_Schur (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Selection()
void ug::bridge::RegisterBridge_Selection (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Solver()
void ug::bridge::RegisterBridge_Solver (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_Transform()
void ug::bridge::RegisterBridge_Transform (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterBridge_UserData()
void ug::bridge::RegisterBridge_UserData (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by RegisterStandardBridges().
RegisterConverter()
bool ug::bridge::RegisterConverter (Registry & reg, const char * parentGroup)
References ug::bridge::Registry::add_function(), convert(), and convertVM().
Referenced by ug::script::RegisterDefaultLuaBridge().
RegisterDegeneratedLayerManager()
template<int dim> static void ug::bridge::RegisterDegeneratedLayerManager (Registry & reg, string grp) static
A template function for registering a degenerated layer manager for a specified dimensionality.
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), close(), contains(), and name.
RegisterGeometry()
template<int dim> void ug::bridge::RegisterGeometry (Registry & reg, string grp)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), mkstr, and name.
RegisterGridBridge_Balancing() [1/2]
void ug::bridge::RegisterGridBridge_Balancing (Registry & reg, std::string parentGroup)
RegisterGridBridge_Balancing() [2/2]
void ug::bridge::RegisterGridBridge_Balancing (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_class_().
Referenced by RegisterBridge_Grid().
RegisterGridBridge_Debug() [1/2]
void ug::bridge::RegisterGridBridge_Debug (Registry & reg, std::string parentGroup)
RegisterGridBridge_Debug() [2/2]
void ug::bridge::RegisterGridBridge_Debug (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_function(), ug::CheckDistributedObjectConstraintTypes(), ug::CheckDistributedParentTypes(), ug::CheckElementConsistency(), ug::CheckForUnconnectedSides(), ug::CheckHangingNodeConsistency(), and ug::CheckMultiGridConsistency().
Referenced by RegisterBridge_Grid().
RegisterGridBridge_FileIO() [1/2]
void ug::bridge::RegisterGridBridge_FileIO (Registry & reg, std::string parentGroup)
RegisterGridBridge_FileIO() [2/2]
void ug::bridge::RegisterGridBridge_FileIO (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_function(), LoadGrid(), SaveGrid(), SaveGridHierarchy(), ug::SaveGridHierarchyTransformed(), ug::SaveGridLevelToFile(), ug::SaveParallelGridLayout(), and ug::SaveSurfaceViewTransformed().
Referenced by RegisterBridge_Grid().
RegisterGridBridge_Grid() [1/2]
void ug::bridge::RegisterGridBridge_Grid (Registry & reg, std::string parentGroup)
RegisterGridBridge_Grid() [2/2]
void ug::bridge::RegisterGridBridge_Grid (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_function(), and boost::num_vertices().
Referenced by RegisterBridge_Grid().
RegisterGridBridge_Layers() [1/2]
void ug::bridge::RegisterGridBridge_Layers (Registry & reg, std::string parentGroup)
Referenced by RegisterBridge_Grid().
RegisterGridBridge_Layers() [2/2]
void ug::bridge::RegisterGridBridge_Layers (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_function(), and ug::LoadHeightfieldFromASC().
RegisterGridBridge_Misc() [1/2]
void ug::bridge::RegisterGridBridge_Misc (Registry & reg, std::string parentGroup)
Referenced by RegisterBridge_Grid().
RegisterGridBridge_Misc() [2/2]
void ug::bridge::RegisterGridBridge_Misc (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_function(), create(), ug::PrintAttachmentInfo(), ug::PrintGridElementNumbers(), and TestNTree().
RegisterGridBridge_Refinement() [1/2]
void ug::bridge::RegisterGridBridge_Refinement (Registry & reg, std::string parentGroup)
Referenced by RegisterBridge_Grid().
RegisterGridBridge_Refinement() [2/2]
void ug::bridge::RegisterGridBridge_Refinement (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), ug::bridge::Registry::add_function(), CreateHierarchy(), CreateSmoothHierarchy(), and name.
RegisterGridBridge_Selector() [1/2]
void ug::bridge::RegisterGridBridge_Selector (Registry & reg, std::string parentGroup)
Referenced by RegisterBridge_Grid().
RegisterGridBridge_Selector() [2/2]
void ug::bridge::RegisterGridBridge_Selector (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_class_().
RegisterGridBridge_SubsetHandler() [1/2]
void ug::bridge::RegisterGridBridge_SubsetHandler (Registry & reg, std::string parentGroup)
Referenced by RegisterBridge_Grid().
RegisterGridBridge_SubsetHandler() [2/2]
void ug::bridge::RegisterGridBridge_SubsetHandler (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_function(), AssignSubsetColors(), AssignSubsetsByElementType(), and ug::AssignSubsetsByLevel().
RegisterInfoCommands()
UG_API bool ug::bridge::RegisterInfoCommands (Registry & reg, const char * parentGroup)
registers info commands TypeInfo, ClassUsage and others
References ug::bridge::Registry::add_function(), ClassInstantiations(), EnableLUA2C(), EnableLUA2VM(), ug::GetLoadedPlugins(), InitSignals(), LuaList(), LuaList_cfunctions(), LuaList_classes(), LuaList_classInstantiations(), LuaList_internalFunctions(), LuaList_luaObjects(), LuaList_scriptFunctions(), LuaStackTrace(), ug::PluginLoaded(), RegisterSerializationCommands(), ScriptHasClass(), ScriptHasClassGroup(), ScriptPrintClassHierarchy(), ScriptPrintClassUsage(), UG_REGISTRY_CATCH_THROW, and UGTypeInfo().
Referenced by ug::script::RegisterDefaultLuaBridge().
RegisterLuaUserData() [1/2]
void ug::bridge::RegisterLuaUserData (Registry & reg, std::string grp)
RegisterLuaUserData() [2/2]
void ug::bridge::RegisterLuaUserData (Registry & reg, string grp)
References UG_REGISTRY_CATCH_THROW.
Referenced by ug::script::RegisterDefaultLuaBridge().
RegisterRaster()
template<class TValue , int TDIM> static void ug::bridge::RegisterRaster (Registry & reg, string name, string grp) static
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), create(), dim, and name.
RegisterRasterUserData()
template<class TValue , int dim> static void ug::bridge::RegisterRasterUserData (Registry & reg, string name, string grp) static
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), and name.
RegisterSerializationCommands()
bool ug::bridge::RegisterSerializationCommands (Registry & reg, const char * parentGroup)
References ug::bridge::Registry::add_function(), LuaWrite(), LuaWriteCout(), and UG_REGISTRY_CATCH_THROW.
Referenced by RegisterInfoCommands().
RegisterStandardBridges()
void ug::bridge::RegisterStandardBridges (Registry & reg, string parentGroup)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_function(), append(), GetUGDim(), InitUG(), RegisterBridge_AdaptiveTools(), RegisterBridge_AlgebraCommon(), RegisterBridge_AlgebraOrdering(), RegisterBridge_Constraints(), RegisterBridge_DiscAlgebra(), RegisterBridge_DiscCommon(), RegisterBridge_Domain(), RegisterBridge_DomainDependentPreconditioner(), RegisterBridge_DomainDisc(), RegisterBridge_DomainRayTracing(), RegisterBridge_Eigensolver(), RegisterBridge_ElemDiscs(), RegisterBridge_Evaluate(), RegisterBridge_FiniteVolume(), RegisterBridge_Grid(), RegisterBridge_GridFunction(), RegisterBridge_Integrate(), RegisterBridge_Interpolate(), RegisterBridge_LoadBalancing(), RegisterBridge_ManifoldUtil(), RegisterBridge_MaxError(), RegisterBridge_Misc(), RegisterBridge_MultiGrid(), RegisterBridge_Obstacle(), RegisterBridge_Ordering(), RegisterBridge_OrthoPoly(), RegisterBridge_Output(), RegisterBridge_PCL(), RegisterBridge_PeriodicBoundary(), RegisterBridge_PILUT(), RegisterBridge_Preconditioner(), RegisterBridge_Profiler(), RegisterBridge_Raster(), RegisterBridge_ReferenceMappingTest(), RegisterBridge_Refinement(), RegisterBridge_Restart(), RegisterBridge_Schur(), RegisterBridge_Selection(), RegisterBridge_Solver(), RegisterBridge_Transform(), RegisterBridge_UserData(), RegisterBridge_Util(), RegisterBridge_VecMath(), ug::bridge::Registry::registry_changed(), UG_CATCH_THROW, and UG_REGISTRY_CATCH_THROW.
Referenced by InitBridge().
RunShell()
int ug::bridge::RunShell (const char * prompt)
References ug::UGError::get_file(), ug::UGError::get_line(), ug::UGError::get_msg(), ug::UGError::num_msg(), ug::script::ParseAndExecuteBuffer(), PROFILE_BEGIN, SetOtherCompletions(), ug::script::LuaError::show_msg(), ug_cacheline(), UG_LOG, UG_PROMPT, ug_readline(), and UGTypeInfo().
Referenced by ugshell_main().
SaveGrid() [1/3]
bool ug::bridge::SaveGrid (Grid & grid, const char * filename)
References PROFILE_FUNC_GROUP, and ug::SaveGridToFile().
SaveGrid() [2/3]
bool ug::bridge::SaveGrid (Grid & grid, const ISubsetHandler & sh, const char * filename)
References PROFILE_FUNC_GROUP, and ug::SaveGridToFile().
Referenced by RegisterGridBridge_FileIO().
SaveGrid() [3/3]
bool ug::bridge::SaveGrid (Grid & grid, ISubsetHandler & sh, const char * filename)
References PROFILE_FUNC_GROUP, and ug::SaveGridToFile().
SaveGridHierarchy()
bool ug::bridge::SaveGridHierarchy (MultiGrid & mg, const char * filename)
References ug::MultiGrid::get_hierarchy_handler(), PROFILE_FUNC_GROUP, and ug::SaveGridToFile().
Referenced by RegisterGridBridge_FileIO().
ScriptHasClass()
bool ug::bridge::ScriptHasClass (const char * classname)
References ug::bridge::Registry::get_class(), and GetUGRegistry().
Referenced by RegisterInfoCommands().
ScriptHasClassGroup()
bool ug::bridge::ScriptHasClassGroup (const char * classname)
References ug::bridge::Registry::get_class_group(), and GetUGRegistry().
Referenced by RegisterInfoCommands().
ScriptPrintClassHierarchy()
void ug::bridge::ScriptPrintClassHierarchy (const char * classname)
References ClassHierarchyString(), GetUGRegistry(), and UG_LOG.
Referenced by RegisterInfoCommands().
ScriptPrintClassUsage()
void ug::bridge::ScriptPrintClassUsage (const char * classname)
References ClassUsage(), and UG_LOG.
Referenced by RegisterInfoCommands().
SetLuaNamespace()
void ug::bridge::SetLuaNamespace (string name, string value)
References ug::script::GetDefaultLuaState(), LUA_STACK_CHECK, name, SetLuaNamespaceInTable(), and UG_LOGN.
SetLuaNamespaceInTable()
void ug::bridge::SetLuaNamespaceInTable (string name, string value)
References ug::script::GetDefaultLuaState(), LUA_STACK_CHECK, name, and UG_LOGN.
Referenced by SetLuaNamespace().
TestNTree()
bool ug::bridge::TestNTree (const char * filename)
References ug::aPosition, ug::FindContainingElement(), ug::FindLowestLeafNodeLevel(), ug::GetMinMaxNumElements(), ug::LoadGridFromFile(), p, PROFILE_BEGIN, PROFILE_END, PROFILE_FUNC_GROUP, UG_LOG, ug::Grid::volumes_begin(), and ug::Grid::volumes_end().
Referenced by RegisterGridBridge_Misc().
ug_cacheline()
void ug::bridge::ug_cacheline (string str)
Referenced by DebugShell(), and RunShell().
ug_readline()
string ug::bridge::ug_readline (const char * prompt, bool & quit)
Referenced by DebugShell(), and RunShell().
UGTypeInfo()
UG_API int ug::bridge::UGTypeInfo (const char * p)
Prints info to a lua type.
Parameters
p the name of the object in lua. you can use class names, function names or the names of an object
TypeInfo("class") prints all member functions+parameters of this class and its parents
TypeInfo("Function") prints all member functions+parameters
TypeInfo("variable") prints class information if variable is a object of a ug class, otherwise what type in lua it is
References ug::bridge::IExportedClass::class_names(), ClassHierarchyString(), ClassInfo(), ClassInstantiations(), FunctionInfo(), ug::bridge::ClassGroupDesc::get_class(), ug::bridge::Registry::get_class(), ug::bridge::Registry::get_class_group(), ug::bridge::ClassGroupDesc::get_default_class(), ug::script::GetDefaultLuaState(), GetLuaNamespace(), GetLuaTypeString(), GetUGRegistry(), LUA_STACK_CHECK, LuaPrintTable(), ug::bridge::IExportedClass::name(), ug::bridge::ClassGroupDesc::num_classes(), p, and UG_LOG.
Referenced by DebugShell(), GetClassesCompletitions(), GetGlobalsCompletitions(), GetNamespaceCompletitions(), RegisterInfoCommands(), and RunShell().
WriteLUAObject()
void ug::bridge::WriteLUAObject (lua_State * L, std::string name, std::ostream & s)
References name, s, and WriteLUAObject2().
Referenced by LuaWrite(), and LuaWriteCout().
WriteLUAObject2()
void ug::bridge::WriteLUAObject2 (lua_State * L, std::string name, std::ostream & s)
References ug::bridge::ParameterInfo::class_name(), func(), ug::bridge::Registry::get_exported_function_group(), ug::bridge::ExportedFunctionGroup::get_overload(), GetLuaTypeString(), GetUGRegistry(), LUAStringEscape(), name, ug::bridge::ExportedFunctionGroup::num_overloads(), p, ug::bridge::ParameterStack::push(), PushLuaStackPointerEntryToParamStack(), and s.
Referenced by WriteLUAObject().
Variable Documentation
iOtherCompletitionsLength
int ug::bridge::iOtherCompletitionsLength
Referenced by GetOtherCompletitions(), and SetOtherCompletions().
pOtherCompletitions
const char** ug::bridge::pOtherCompletitions =NULL
Referenced by GetOtherCompletitions(), and SetOtherCompletions().
UG4_DIM
int ug::bridge::UG4_DIM = -1 static
the dimension to which ug was initialized through InitUG
This dimension can be accessed through GetUGDim()
Referenced by GetUGDim(), and InitUG().