ug4: ug::ConnectionViewer Namespace Reference
ug::ConnectionViewer Namespace Reference
Functions
bool AddMarkers (string filename, string markfilename)
bool AddMarkers (std::string filename, std::string markfilename)
string GetParallelName (string name, const pcl::ProcessCommunicator &pc, bool bWriteHeader)
std::string GetParallelName (std::string name, const pcl::ProcessCommunicator &pc, bool bWriteHeader=true)
std::string GetParallelName (std::string name)
template<typename T >
std::string GetParallelName (T &t, std::string name)
template<typename matrix_type >
bool ReadMatrix (std::string filename, matrix_type &matrix, std::vector< MathVector< 3 > > &grid, int &dimension)
template<typename vector_type >
bool ReadVector (std::string filename, vector_type &vec)
template<typename TPosition >
bool WriteGridHeader (std::ostream &f, const TPosition &positions, size_t N, int dimension)
template<typename TPosition >
bool WriteGridHeader (std::ostream &f, const TPosition &positions, int dimension)
bool WriteMarkers (std::string markfilename, std::vector< bool > markers, float r, float g, float b, float alpha, int size)
bool WriteMarkers (string markfilename, vector< bool > markers, float r, float g, float b, float alpha, int size)
template<typename Matrix_type , typename postype >
void WriteMatrix (std::ostream &file, const Matrix_type &A, postype *positions, int dimensions)
writes to a file in somewhat SparseMatrix-market format (for connection viewer)
template<typename Matrix_type , typename postype >
void WriteMatrix (std::string filename, const Matrix_type &A, postype *positions, int dimensions)
template<typename Matrix_type , typename postype >
bool WriteMatrix (std::string filename, const Matrix_type &A, const std::vector< postype > &positionsFrom, const std::vector< postype > &positionsTo, size_t dimensions)
template<typename Matrix_type , typename postype >
void WriteMatrixPar (std::string name, const Matrix_type &A, const postype *positions, int dimensions)
template<typename Matrix_type , typename postype >
bool WriteMatrixPar (std::string filename, const Matrix_type &A, const std::vector< postype > &positionsFrom, const std::vector< postype > &positionsTo, size_t dimensions)
template<typename Vector_type , typename postype >
void WriteVector (std::string filename, const Vector_type &b, const postype *positions, int dimensions, const Vector_type *compareVec=NULL)
writes to a file in somewhat SparseMatrix-market format (for connection viewer)
template<typename Matrix_type , typename Vector_type , typename postype >
void WriteVector (std::string filename, const Matrix_type &A, const Vector_type &v, postype *positions, int dimensions, const Vector_type *compareVec=NULL)
template<typename Vector_type , typename postype >
void WriteVectorPar (std::string filename, const Vector_type &b, const postype *positions, int dimensions, const Vector_type *compareVec=NULL)
template<typename Matrix_type , typename Vector_type , typename postype >
void WriteVectorPar (std::string filename, const Matrix_type &A, const Vector_type &v, postype *positions, int dimensions, const Vector_type *compareVec=NULL)
Variables
bool g_parallelConnectionViewer =false
Function Documentation
AddMarkers() [1/2]
bool ug::ConnectionViewer::AddMarkers (string filename, string markfilename)
Referenced by GetParallelName().
AddMarkers() [2/2]
bool ug::ConnectionViewer::AddMarkers (std::string filename, std::string markfilename)
GetParallelName() [1/4]
string ug::ConnectionViewer::GetParallelName (string name, const pcl::ProcessCommunicator & pc, bool bWriteHeader)
References pcl::ProcessCommunicator::get_proc_id(), pcl::NumProcs(), pcl::ProcRank(), pcl::ProcessCommunicator::size(), and sprintf().
Referenced by GetParallelName(), ug::WriteAlgebraIndices(), WriteMatrixPar(), WriteVector(), and WriteVectorPar().
GetParallelName() [2/4]
std::string ug::ConnectionViewer::GetParallelName (std::string name, const pcl::ProcessCommunicator & pc, bool bWriteHeader = true)
extends the filename (add p000X extension in parallel) and writes a parallel pvec/pmat "header" file
GetParallelName() [3/4]
std::string ug::ConnectionViewer::GetParallelName (std::string name) inline
References GetParallelName().
GetParallelName() [4/4]
template<typename T > std::string ug::ConnectionViewer::GetParallelName (T & t, std::string name) inline
References AddMarkers(), alpha, GetParallelName(), and WriteMarkers().
ReadMatrix()
template<typename matrix_type > bool ug::ConnectionViewer::ReadMatrix (std::string filename, matrix_type & matrix, std::vector< MathVector< 3 > > & grid, int & dimension)
References PROGRESS_START, and PROGRESS_UPDATE.
ReadVector()
template<typename vector_type > bool ug::ConnectionViewer::ReadVector (std::string filename, vector_type & vec)
References PROGRESS_START, and PROGRESS_UPDATE.
WriteGridHeader() [1/2]
template<typename TPosition > bool ug::ConnectionViewer::WriteGridHeader (std::ostream & f, const TPosition & positions, size_t N, int dimension)
Referenced by WriteGridHeader(), WriteMatrix(), and WriteVector().
WriteGridHeader() [2/2]
template<typename TPosition > bool ug::ConnectionViewer::WriteGridHeader (std::ostream & f, const TPosition & positions, int dimension)
References WriteGridHeader().
WriteMarkers() [1/2]
bool ug::ConnectionViewer::WriteMarkers (std::string markfilename, std::vector< bool > markers, float r, float g, float b, float alpha, int size)
WriteMarkers() [2/2]
bool ug::ConnectionViewer::WriteMarkers (string markfilename, vector< bool > markers, float r, float g, float b, float alpha, int size)
Referenced by GetParallelName().
WriteMatrix() [1/3]
template<typename Matrix_type , typename postype > void ug::ConnectionViewer::WriteMatrix (std::ostream & file, const Matrix_type & A, postype * positions, int dimensions)
writes to a file in somewhat SparseMatrix-market format (for connection viewer)
Parameters
filename Filename to write matrix to
A SparseMatrix A.
positions Positions, there has to be one position for each i in (0, ..., max(A.num_rows(), A.num_cols())).
dimensions Dimension of positions
References PROFILE_FUNC_GROUP, PROGRESS_START, PROGRESS_UPDATE, and WriteGridHeader().
Referenced by WriteMatrix(), and WriteMatrixPar().
WriteMatrix() [2/3]
template<typename Matrix_type , typename postype > void ug::ConnectionViewer::WriteMatrix (std::string filename, const Matrix_type & A, postype * positions, int dimensions)
References WriteMatrix().
WriteMatrix() [3/3]
template<typename Matrix_type , typename postype > bool ug::ConnectionViewer::WriteMatrix (std::string filename, const Matrix_type & A, const std::vector< postype > & positionsFrom, const std::vector< postype > & positionsTo, size_t dimensions)
** this version can handle different from and to spaces
References CONNECTION_VIEWER_VERSION, PROFILE_FUNC_GROUP, PROGRESS_START, PROGRESS_UPDATE, and UG_LOG.
WriteMatrixPar() [1/2]
template<typename Matrix_type , typename postype > void ug::ConnectionViewer::WriteMatrixPar (std::string name, const Matrix_type & A, const postype * positions, int dimensions)
References pcl::ParallelArchive::create_stringstream_file(), ug::FilenameWithoutExtension(), pcl::ProcessCommunicator::get_proc_id(), ug::GetFilenameExtension(), GetParallelName(), pcl::NumProcs(), pcl::ProcRank(), pcl::ProcessCommunicator::size(), sprintf(), and WriteMatrix().
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_matrix(), and ug::WriteMatrixToConnectionViewer().
WriteMatrixPar() [2/2]
template<typename Matrix_type , typename postype > bool ug::ConnectionViewer::WriteMatrixPar (std::string filename, const Matrix_type & A, const std::vector< postype > & positionsFrom, const std::vector< postype > & positionsTo, size_t dimensions)
References GetParallelName(), and WriteMatrix().
WriteVector() [1/2]
template<typename Vector_type , typename postype > void ug::ConnectionViewer::WriteVector (std::string filename, const Vector_type & b, const postype * positions, int dimensions, const Vector_type * compareVec = NULL)
writes to a file in somewhat SparseMatrix-market format (for connection viewer)
Parameters
filename Filename to write matrix to
b Vector
positions Positions, there has to be one position for each i in (0, ..., max(A.num_rows(), A.num_cols())).
dimensions Dimensions of Positions
References PROFILE_FUNC_GROUP, and WriteGridHeader().
Referenced by WriteVectorPar().
WriteVector() [2/2]
template<typename Matrix_type , typename Vector_type , typename postype > void ug::ConnectionViewer::WriteVector (std::string filename, const Matrix_type & A, const Vector_type & v, postype * positions, int dimensions, const Vector_type * compareVec = NULL)
References GetParallelName(), PROFILE_FUNC_GROUP, PROGRESS_START, PROGRESS_UPDATE, UG_LOG, and WriteGridHeader().
WriteVectorPar() [1/2]
template<typename Vector_type , typename postype > void ug::ConnectionViewer::WriteVectorPar (std::string filename, const Vector_type & b, const postype * positions, int dimensions, const Vector_type * compareVec = NULL)
References GetParallelName(), and WriteVector().
Referenced by ug::GridFunctionDebugWriter< TDomain, TAlgebra >::write_vector_to_conn_viewer(), and ug::WriteVectorToConnectionViewer().
WriteVectorPar() [2/2]
template<typename Matrix_type , typename Vector_type , typename postype > void ug::ConnectionViewer::WriteVectorPar (std::string filename, const Matrix_type & A, const Vector_type & v, postype * positions, int dimensions, const Vector_type * compareVec = NULL)
References ug::BlockNorm(), CONNECTION_VIEWER_VERSION, GetParallelName(), PROFILE_FUNC_GROUP, and WriteVector().
Variable Documentation
g_parallelConnectionViewer
bool ug::ConnectionViewer::g_parallelConnectionViewer =false