ug4: boost Namespace Reference
boost Namespace Reference
Namespaces
mpl
serialization
Classes
class bglp_matrix_index_map
struct BS_traversal_tag
class bucket_sorter
class degree_property_map< ug::UndirectedMatrix< T > >
struct graph_traits< ug::BGLParallelMatrix< ug::ParallelMatrix< T > > >
struct graph_traits< ug::BidirectionalMatrix< T > >
struct graph_traits< ug::ParallelMatrix< ug::SparseMatrix< T > > >
struct graph_traits< ug::SparseMatrix< T > >
struct graph_traits< ug::UndirectedMatrix< T > >
struct pointee< ConstSmartPtr< T > >
struct pointee< SmartPtr< T > >
struct property_map< ug::BGLParallelMatrix< T >, vertex_index_t >
struct property_map< ug::BidirectionalMatrix< ug::SparseMatrix< T > >, vertex_index_t >
struct property_map< ug::ParallelMatrix< T >, vertex_index_t >
struct property_map< ug::SparseMatrix< T >, Tag >
struct property_map< ug::SparseMatrix< T >, vertex_index_t >
struct property_map< ug::UndirectedMatrix< T >, vertex_index_t >
class SM_adjacency_iterator
class SM_edge
class SM_edge_weight_map
class SM_out_edge_iterator
struct SM_traversal_tag
class sparse_matrix_index_map
class UM_out_edge_iterator
Functions
template<class T >
std::pair< typename graph_traits< T >::adjacency_iterator, typename graph_traits< T >::adjacency_iterator > adjacent_vertices (size_t v, ug::BidirectionalMatrix< T > const &M)
template<class T >
std::pair< typename graph_traits< ug::SparseMatrix< T > >::adjacency_iterator, typename graph_traits< ug::SparseMatrix< T > >::adjacency_iterator > adjacent_vertices (size_t v, ug::SparseMatrix< T > const &M)
template<class T >
std::pair< typename ug::UndirectedMatrix< T >::adjacency_iterator, typename ug::UndirectedMatrix< T >::adjacency_iterator > adjacent_vertices (size_t v, ug::UndirectedMatrix< T > const &M)
template<class T >
std::pair< typename ug::BGLParallelMatrix< T >::adjacency_iterator, typename ug::BGLParallelMatrix< T >::adjacency_iterator > adjacent_vertices (typename ug::BGLParallelMatrix< T >::vertex_descriptor v, ug::BGLParallelMatrix< T > const &M)
template<class T >
std::pair< typename graph_traits< T >::adjacency_iterator, typename graph_traits< T >::adjacency_iterator > coadjacent_vertices (size_t v, ug::BidirectionalMatrix< T > const &M)
template<class T >
int degree (int v, ug::BidirectionalMatrix< T > const &M)
template<class T >
int degree (int v, ug::UndirectedMatrix< T > const &M)
template<class T >
SM_edge_weight_map< T > get (edge_weight_t, ug::BGLParallelMatrix< T > const &g)
template<class T >
SM_edge_weight_map< typename T::value_type, ug::BidirectionalMatrix< T > > get (edge_weight_t, ug::BidirectionalMatrix< T > const &g)
template<class T >
SM_edge_weight_map< T > get (edge_weight_t, ug::SparseMatrix< T > const &g)
template<class T >
property_map< ug::BGLParallelMatrix< T >, vertex_index_t >::const_type get (vertex_index_t, ug::BGLParallelMatrix< T > const &m)
template<class T >
property_map< ug::BidirectionalMatrix< ug::SparseMatrix< T > >, vertex_index_t >::const_type get (vertex_index_t, ug::BidirectionalMatrix< T > const &m)
template<class T >
property_map< ug::SparseMatrix< T >, vertex_index_t >::const_type get (vertex_index_t, ug::SparseMatrix< T > const &m)
template<class T >
property_map< ug::UndirectedMatrix< T >, vertex_index_t >::const_type get (vertex_index_t, ug::UndirectedMatrix< T > const &m)
template<class T >
int in_degree (int v, ug::BidirectionalMatrix< T > const &M)
template<class T >
int in_degree (int v, ug::UndirectedMatrix< T > const &M)
template<class T >
std::pair< SM_out_edge_iterator< typename T::value_type, false >, SM_out_edge_iterator< typename T::value_type, false > > in_edges (size_t v, ug::BidirectionalMatrix< T > const &g)
template<class T >
degree_property_map< ug::UndirectedMatrix< T > > make_degree_map (const ug::UndirectedMatrix< T > &g)
template<class T >
size_t num_vertices (ug::BGLParallelMatrix< T > const &)
template<class T >
int num_vertices (ug::BidirectionalMatrix< T > const &M)
template<class T >
int num_vertices (ug::SparseMatrix< T > const &M)
template<class T >
int num_vertices (ug::UndirectedMatrix< T > const &M)
template<class T >
int out_degree (int v, ug::BidirectionalMatrix< T > const &M)
template<class T >
int out_degree (int v, ug::SparseMatrix< T > const &M)
template<class T >
int out_degree (int v, ug::UndirectedMatrix< T > const &M)
template<class T >
int out_degree (typename ug::BGLParallelMatrix< T >::vertex_descriptor v, ug::BGLParallelMatrix< T > const &M)
template<class T >
std::pair< SM_out_edge_iterator< T >, SM_out_edge_iterator< T > > out_edges (int v, ug::SparseMatrix< T > const &g)
template<class T >
std::pair< UM_out_edge_iterator< T >, UM_out_edge_iterator< T > > out_edges (int v, ug::UndirectedMatrix< T > const &M)
template<class T >
std::pair< SM_out_edge_iterator< typename T::value_type >, SM_out_edge_iterator< typename T::value_type > > out_edges (size_t v, ug::BidirectionalMatrix< T > const &g)
template<class T >
std::pair< typename ug::BGLParallelMatrix< T >::out_edge_iterator, typename ug::BGLParallelMatrix< T >::out_edge_iterator > out_edges (typename ug::BGLParallelMatrix< T >::vertex_descriptor v, ug::BGLParallelMatrix< T > const &M)
template<class T , class M >
int source (SM_edge< T > const &e, M const &)
template<class T >
size_t source (SM_edge< typename T::value_type > const &e, ug::BidirectionalMatrix< T > const &)
template<class T >
int source (typename T::edge const &e, T const &)
template<class T >
ug::BGLParallelMatrix< T >::vertex_descriptor source (typename ug::BGLParallelMatrix< T >::edge const &e, ug::BGLParallelMatrix< T > const &)
template<class T , class M >
int target (SM_edge< T > const &e, M const &)
template<class T >
size_t target (SM_edge< typename T::value_type > const &e, ug::BidirectionalMatrix< T > const &m)
template<class T >
int target (typename T::edge const &e, T const &)
template<class T >
ug::BGLParallelMatrix< T >::vertex_descriptor target (typename ug::BGLParallelMatrix< T >::edge const &e, ug::BGLParallelMatrix< T > const &)
template<class T >
std::pair< typename ug::BGLParallelMatrix< T >::vertex_iterator, typename ug::BGLParallelMatrix< T >::vertex_iterator > vertices (ug::BGLParallelMatrix< T > const &M)
template<class T >
std::pair< counting_iterator< size_t >, counting_iterator< size_t > > vertices (ug::BidirectionalMatrix< T > const &M)
template<class T >
std::pair< counting_iterator< size_t >, counting_iterator< size_t > > vertices (ug::ParallelMatrix< ug::SparseMatrix< T >> const &M)
template<class T >
std::pair< counting_iterator< size_t >, counting_iterator< size_t > > vertices (ug::SparseMatrix< T > const &M)
template<class T >
std::pair< counting_iterator< size_t >, counting_iterator< size_t > > vertices (ug::UndirectedMatrix< T > const &M)
Function Documentation
adjacent_vertices() [1/4]
template<class T > std::pair<typename graph_traits<T>::adjacency_iterator, typename graph_traits<T>::adjacency_iterator> boost::adjacent_vertices (size_t v, ug::BidirectionalMatrix< T > const & M)
References ug::BidirectionalMatrix< T >::begin_row(), and ug::BidirectionalMatrix< T >::end_row().
Referenced by ug::BGLParallelMatrix< T >::begin_adjacent_vertices(), ug::UndirectedMatrix< T >::begin_row(), ug::SCCOrdering< TAlgebra, O_t >::compute(), ug::BGLParallelMatrix< T >::end_adjacent_vertices(), ug::UndirectedMatrix< T >::end_row(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::get_source_vertex(), out_edges(), ug::UndirectedMatrix< T >::refresh(), and ug::topological_ordering_core_directed().
adjacent_vertices() [2/4]
template<class T > std::pair<typename graph_traits<ug::SparseMatrix<T> >::adjacency_iterator, typename graph_traits<ug::SparseMatrix<T> >::adjacency_iterator> boost::adjacent_vertices (size_t v, ug::SparseMatrix< T > const & M) inline
References ug::SparseMatrix< TValueType >::begin_row(), ug::SparseMatrix< TValueType >::end_row(), and ug::SparseMatrix< TValueType >::num_rows().
adjacent_vertices() [3/4]
template<class T > std::pair<typename ug::UndirectedMatrix<T>::adjacency_iterator, typename ug::UndirectedMatrix<T>::adjacency_iterator > boost::adjacent_vertices (size_t v, ug::UndirectedMatrix< T > const & M)
References ug::UndirectedMatrix< T >::begin_row(), and ug::UndirectedMatrix< T >::end_row().
adjacent_vertices() [4/4]
template<class T > std::pair<typename ug::BGLParallelMatrix<T>::adjacency_iterator, typename ug::BGLParallelMatrix<T>::adjacency_iterator> boost::adjacent_vertices (typename ug::BGLParallelMatrix< T >::vertex_descriptor v, ug::BGLParallelMatrix< T > const & M) inline
References ug::BGLParallelMatrix< T >::begin_adjacent_vertices(), ug::BGLParallelMatrix< T >::end_adjacent_vertices(), and ug::detail::local().
coadjacent_vertices()
template<class T > std::pair<typename graph_traits<T>::adjacency_iterator, typename graph_traits<T>::adjacency_iterator> boost::coadjacent_vertices (size_t v, ug::BidirectionalMatrix< T > const & M)
References ug::BidirectionalMatrix< T >::begin_col(), and ug::BidirectionalMatrix< T >::end_col().
Referenced by in_edges().
degree() [1/2]
template<class T > int boost::degree (int v, ug::BidirectionalMatrix< T > const & M)
References ug::BidirectionalMatrix< T >::degree(), and untested.
Referenced by ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::compute(), in_degree(), boost::degree_property_map< ug::UndirectedMatrix< T > >::operator[](), and out_degree().
degree() [2/2]
template<class T > int boost::degree (int v, ug::UndirectedMatrix< T > const & M)
References ug::UndirectedMatrix< T >::degree().
get() [1/7]
template<class T > SM_edge_weight_map<T> boost::get (edge_weight_t , ug::BGLParallelMatrix< T > const & g) inline
References incomplete.
get() [2/7]
template<class T > SM_edge_weight_map<typename T::value_type, ug::BidirectionalMatrix<T> > boost::get (edge_weight_t , ug::BidirectionalMatrix< T > const & g) inline
Referenced by ug::ActiveSet< TDomain, TAlgebra >::active_index_elem(), ug::IDomain< TGrid, TSubsetHandler >::broadcast_refinement_projector(), ug::ActiveSet< TDomain, TAlgebra >::check_conv_elem(), ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::compute(), ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::compute(), ug::SCCOrdering< TAlgebra, O_t >::compute(), ug::bridge::UserDataBridge::Functionality::Dimension(), ug::bridge::Ordering::Functionality::DomainAlgebra(), ug::ComPol_GatherSurfaceStates< TLayout >::extract(), ug::DistInfoSupplier::get(), ug::DistInfoSupplier::get_debug_info(), ug::IApproximationSpace::IApproximationSpace(), ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::init_all_line_sss(), ug::FVSingularSourcesAndSinks< dim, TPointData, TLineData >::init_all_point_sss(), ug::vrl::jobjectArray2ParamStack(), ug::ActiveSet< TDomain, TAlgebra >::lagrange_mat_inv_elem(), ug::bridge::lua::ParameterStackString(), ug::FV1InnerBoundaryElemDisc< TImpl, TDomain >::prep_err_est_elem(), ug::FV1InnerBoundaryElemDisc< TImpl, TDomain >::prep_err_est_elem_loop(), ug::IApproximationSpace::print_statistic(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push_back(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::push_back(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::push_front(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::stack_< Iter_, IndexValueMap_ >::push_front(), ug::bridge::RegisterBridge_Util(), boost::bucket_sorter< BucketType, ValueType, Bucket, ValueIndexMap >::remove(), ug::PProcessChain< TVector >::remove(), ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::update_elem_discs(), and ug::DomainDiscretizationBase< TDomain, TAlgebra, TGlobAssembler >::update_elem_errors().
get() [3/7]
template<class T > SM_edge_weight_map<T> boost::get (edge_weight_t , ug::SparseMatrix< T > const & g) inline
get() [4/7]
template<class T > property_map<ug::BGLParallelMatrix<T>, vertex_index_t>::const_type boost::get (vertex_index_t , ug::BGLParallelMatrix< T > const & m)
get() [5/7]
template<class T > property_map<ug::BidirectionalMatrix<ug::SparseMatrix<T> >, vertex_index_t>::const_type boost::get (vertex_index_t , ug::BidirectionalMatrix< T > const & m) inline
get() [6/7]
template<class T > property_map<ug::SparseMatrix<T>, vertex_index_t>::const_type boost::get (vertex_index_t , ug::SparseMatrix< T > const & m)
get() [7/7]
template<class T > property_map<ug::UndirectedMatrix<T>, vertex_index_t>::const_type boost::get (vertex_index_t , ug::UndirectedMatrix< T > const & m) inline
in_degree() [1/2]
template<class T > int boost::in_degree (int v, ug::BidirectionalMatrix< T > const & M)
References ug::BidirectionalMatrix< T >::in_degree().
Referenced by ug::RiverOrdering< TAlgebra, TDomain, O_t >::get_source_vertex().
in_degree() [2/2]
template<class T > int boost::in_degree (int v, ug::UndirectedMatrix< T > const & M)
References degree().
in_edges()
template<class T > std::pair<SM_out_edge_iterator<typename T::value_type, false>, SM_out_edge_iterator<typename T::value_type, false> > boost::in_edges (size_t v, ug::BidirectionalMatrix< T > const & g) inline
References coadjacent_vertices().
Referenced by ug::topological_ordering_core_bidirectional().
make_degree_map()
template<class T > degree_property_map< ug::UndirectedMatrix<T> > boost::make_degree_map (const ug::UndirectedMatrix< T > & g)
Referenced by ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::compute().
num_vertices() [1/4]
template<class T > size_t boost::num_vertices (ug::BGLParallelMatrix< T > const &)
References incomplete.
num_vertices() [2/4]
template<class T > int boost::num_vertices (ug::BidirectionalMatrix< T > const & M)
References ug::BidirectionalMatrix< T >::num_rows().
Referenced by ug::AdaptSurfaceGridToCylinder(), ug::CalculateSmoothCreaseManifoldPosInParentLevelLoopScheme(), ug::CalculateSmoothManifoldPosInParentLevelButterflyScheme(), ug::CalculateSmoothManifoldPosInParentLevelLoopScheme(), ug::BoostCuthillMcKeeOrdering< TAlgebra, O_t >::compute(), ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::compute(), ug::SCCOrdering< TAlgebra, O_t >::compute(), ug::CreateVolumesFromElementIndexList(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::get_source_vertex(), ug::GetVertex(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::init(), ug::MakeDelaunay(), ug::MinimizeEdgeLength_SwapsOnly(), ug::MultiEdgeSplit(), ug::SubdivisionProjector::new_vertex(), ug::Face::num_edges(), ug::OrientationMatches(), ug::bridge::RegisterGridBridge_Grid(), ug::IVertexGroup::size(), ug::FaceVertices::size(), ug::VolumeVertices::size(), ug::SwapEdge(), ug::RiverOrdering< TAlgebra, TDomain, O_t >::topological_ordering(), ug::topological_ordering_core_bidirectional(), ug::topological_ordering_core_directed(), and ug::TrySwap().
num_vertices() [3/4]
template<class T > int boost::num_vertices (ug::SparseMatrix< T > const & M)
References ug::SparseMatrix< TValueType >::num_cols(), and ug::SparseMatrix< TValueType >::num_rows().
num_vertices() [4/4]
template<class T > int boost::num_vertices (ug::UndirectedMatrix< T > const & M)
References ug::UndirectedMatrix< T >::num_rows().
out_degree() [1/4]
template<class T > int boost::out_degree (int v, ug::BidirectionalMatrix< T > const & M)
References ug::BidirectionalMatrix< T >::out_degree().
Referenced by ug::BidirectionalMatrix< T >::in_degree(), ug::BGLParallelMatrix< T >::in_degree(), ug::UndirectedMatrix< T >::in_degree(), ug::BidirectionalMatrix< T >::out_degree(), and ug::topological_ordering_core_bidirectional().
out_degree() [2/4]
template<class T > int boost::out_degree (int v, ug::SparseMatrix< T > const & M)
References out_edges().
out_degree() [3/4]
template<class T > int boost::out_degree (int v, ug::UndirectedMatrix< T > const & M)
References degree().
out_degree() [4/4]
template<class T > int boost::out_degree (typename ug::BGLParallelMatrix< T >::vertex_descriptor v, ug::BGLParallelMatrix< T > const & M)
References incomplete.
out_edges() [1/4]
template<class T > std::pair<SM_out_edge_iterator<T>, SM_out_edge_iterator<T> > boost::out_edges (int v, ug::SparseMatrix< T > const & g) inline
References adjacent_vertices(), and ug::SparseMatrix< TValueType >::num_rows().
out_edges() [2/4]
template<class T > std::pair<UM_out_edge_iterator<T>, UM_out_edge_iterator<T> > boost::out_edges (int v, ug::UndirectedMatrix< T > const & M)
References ug::UndirectedMatrix< T >::begin_row(), and ug::UndirectedMatrix< T >::end_row().
out_edges() [3/4]
template<class T > std::pair<SM_out_edge_iterator<typename T::value_type>, SM_out_edge_iterator<typename T::value_type> > boost::out_edges (size_t v, ug::BidirectionalMatrix< T > const & g) inline
References adjacent_vertices().
Referenced by ug::BGLParallelMatrix< T >::begin_out_edges(), ug::BGLParallelMatrix< T >::end_out_edges(), and out_degree().
out_edges() [4/4]
template<class T > std::pair<typename ug::BGLParallelMatrix<T>::out_edge_iterator, typename ug::BGLParallelMatrix<T>::out_edge_iterator> boost::out_edges (typename ug::BGLParallelMatrix< T >::vertex_descriptor v, ug::BGLParallelMatrix< T > const & M) inline
References ug::BGLParallelMatrix< T >::begin_out_edges(), ug::BGLParallelMatrix< T >::end_out_edges(), and ug::detail::local().
source() [1/4]
template<class T , class M > int boost::source (SM_edge< T > const & e, M const &)
References boost::SM_edge< T >::source(), and untested.
source() [2/4]
template<class T > size_t boost::source (SM_edge< typename T::value_type > const & e, ug::BidirectionalMatrix< T > const &)
References boost::SM_edge< T >::source().
Referenced by ug::script::AddBreakpoint(), ug::script::LuaCallHook(), ug::script::luaDebug(), ug::BGLParallelMatrix< T >::out_edge_iterator::operator*(), ug::topological_ordering_core_bidirectional(), and ug::VecCopy().
source() [3/4]
template<class T > int boost::source (typename T::edge const & e, T const &)
source() [4/4]
template<class T > ug::BGLParallelMatrix<T>::vertex_descriptor boost::source (typename ug::BGLParallelMatrix< T >::edge const & e, ug::BGLParallelMatrix< T > const &)
References ug::BGLParallelMatrix< T >::edge::source().
target() [1/4]
template<class T , class M > int boost::target (SM_edge< T > const & e, M const &)
References boost::SM_edge< T >::target(), and untested.
target() [2/4]
template<class T > size_t boost::target (SM_edge< typename T::value_type > const & e, ug::BidirectionalMatrix< T > const & m)
References boost::SM_edge< T >::target().
Referenced by ug::CollapseEdge(), ug::ComPol_MatAddSetZeroInnerInterfaceCouplings< TMatrix >::collect(), ug::BoolMarker::edges_to_be_merged(), ug::ISelector::edges_to_be_merged(), ug::ISubsetHandler::edges_to_be_merged(), ug::ISelector::elems_to_be_merged(), ug::ISubsetHandler::elems_to_be_merged(), ug::BoolMarker::faces_to_be_merged(), ug::ISelector::faces_to_be_merged(), ug::ISubsetHandler::faces_to_be_merged(), ug::GridSubsetHandler::join_subset_lists(), ug::MultiGridSubsetHandler::join_subset_lists(), ug::Grid::objects_will_be_merged(), ug::BGLParallelMatrix< T >::out_edge_iterator::operator*(), ug::vrl::replaceAll(), ug::ReplaceAll(), ug::SlopeSmooth(), ug::VecCopy(), ug::BoolMarker::vertices_to_be_merged(), ug::ISelector::vertices_to_be_merged(), ug::ISubsetHandler::vertices_to_be_merged(), ug::BoolMarker::volumes_to_be_merged(), ug::ISelector::volumes_to_be_merged(), and ug::ISubsetHandler::volumes_to_be_merged().
target() [3/4]
template<class T > int boost::target (typename T::edge const & e, T const &)
target() [4/4]
template<class T > ug::BGLParallelMatrix<T>::vertex_descriptor boost::target (typename ug::BGLParallelMatrix< T >::edge const & e, ug::BGLParallelMatrix< T > const &)
References ug::BGLParallelMatrix< T >::edge::target().
vertices() [1/5]
template<class T > std::pair<typename ug::BGLParallelMatrix<T>::vertex_iterator, typename ug::BGLParallelMatrix<T>::vertex_iterator> boost::vertices (ug::BGLParallelMatrix< T > const & M)
References ug::BGLParallelMatrix< T >::begin_vertices(), and ug::BGLParallelMatrix< T >::end_vertices().
vertices() [2/5]
template<class T > std::pair<counting_iterator<size_t>, counting_iterator<size_t> > boost::vertices (ug::BidirectionalMatrix< T > const & M)
References ug::BidirectionalMatrix< T >::num_rows().
Referenced by ug::BGLParallelMatrix< T >::begin_vertices(), ug::ParallelHangingNodeRefiner_MultiGrid::broadcast_marks_horizontally(), ug::ParallelHangingNodeRefiner_MultiGrid::broadcast_marks_vertically(), ug::SimpleGrid::clear(), ug::BoostMinimumDegreeOrdering< TAlgebra, O_t >::compute(), ug::ParallelHangingNodeRefiner_MultiGrid::copy_marks_to_vmasters(), ug::ParallelHangingNodeRefiner_MultiGrid::copy_marks_to_vslaves(), ug::GridReaderVTU::create_cells(), ug::BGLParallelMatrix< T >::end_vertices(), ug::FillCornerCoordinates(), ug::FindClosestVertexInPointSet(), ug::GridReaderUGX::grid(), ug::GridReaderVTU::grid(), ug::topological_ordering_core_bidirectional(), and ug::topological_ordering_core_directed().
vertices() [3/5]
template<class T > std::pair<counting_iterator<size_t>, counting_iterator<size_t> > boost::vertices (ug::ParallelMatrix< ug::SparseMatrix< T >> const & M)
vertices() [4/5]
template<class T > std::pair<counting_iterator<size_t>, counting_iterator<size_t> > boost::vertices (ug::SparseMatrix< T > const & M)
References ug::SparseMatrix< TValueType >::num_rows().
vertices() [5/5]
template<class T > std::pair<counting_iterator<size_t>, counting_iterator<size_t> > boost::vertices (ug::UndirectedMatrix< T > const & M)
References ug::UndirectedMatrix< T >::num_rows().