ug4: ug::bridge::Evaluate Namespace Reference
ug::bridge::Evaluate Namespace Reference
Classes
struct Functionality
class NumberValuedUserDataEvaluator
class NumberValuedUserDataPointEvaluator
class PointEvaluatorBase
struct PointEvaluatorFactory
This is a factory for creating a 'PointEvaluatorBase' object from user data.
class VectorValuedUserDataEvaluator
class VectorValuedUserDataPointEvaluator
Functions
template<typename TDomain >
bool CloseVertexExists (const MathVector< TDomain::dim > &globPos, TDomain *dom, const char *subsets, SmartPtr< typename TDomain::subset_handler_type > sh, number maxDist)
template<typename TGridFunction >
number EvaluateAtClosestVertex (const MathVector< TGridFunction::dim > &pos, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, SmartPtr< typename TGridFunction::domain_type::subset_handler_type > sh)
template<typename TGridFunction >
number EvaluateAtClosestVertexAllProcs (const MathVector< TGridFunction::dim > &pos, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, SmartPtr< typename TGridFunction::domain_type::subset_handler_type > sh)
template<typename TGridFunction >
number EvaluateAtVertex (const MathVector< TGridFunction::dim > &globPos, SmartPtr< TGridFunction > spGridFct, size_t fct, const SubsetGroup &ssGrp, typename TGridFunction::domain_type::subset_handler_type *sh, bool minimizeOverAllProcs=false)
Function Documentation
CloseVertexExists()
template<typename TDomain > bool ug::bridge::Evaluate::CloseVertexExists (const MathVector< TDomain::dim > & globPos, TDomain * dom, const char * subsets, SmartPtr< typename TDomain::subset_handler_type > sh, number maxDist)
References ug::SubsetGroup::add(), ug::SubsetGroup::add_all(), ug::DistributedGridManager::contains_status(), ug::INT_H_SLAVE, ug::DistributedGridManager::is_ghost(), ug::SubsetGroup::size(), ug::sq(), ug::TokenizeString(), and ug::VecDistanceSq().