ug4: ug::vrl Namespace Reference
ug::vrl Namespace Reference
Namespaces
invocation
threading
Classes
class BasicTest
struct Functionality
class MessageBuffer
class NumberArray
class PrintCondUserData2d
class PrintUserData2d
class SmartPtrCls
class TestClass
struct TypeAndArray
struct vrl_traits
struct vrl_traits< number >
struct vrl_traits< ug::MathMatrix< dim, dim > >
struct vrl_traits< ug::MathVector< dim > >
class VRLCondUserNumber
class VRLUserData
class VRLUserLinker
class VTest
Functions
jboolean boolC2J (bool b)
jobject boolean2JObject (JNIEnv *env, jboolean value)
bool boolJ2C (jboolean b)
jobject boolVector2JObject (JNIEnv *env, const std::vector< bool > &bv)
bool checkException (JNIEnv *env, std::string msg, bool throwCPPException)
void ChrisPoliTest ()
void ChrisPoliTest (int i)
void ChrisPoliTest (bool array[])
void ChrisPoliTest (std::vector< bool > vec)
void ChrisPoliTestCreateFile ()
std::string ChrisPoliTestCreateFile (std::string path)
std::string ChrisPoliTestCreateFile (std::string inPath, std::string outPath)
std::vector< bool > ChrisPoliTestReturn (std::vector< bool > vec)
jobjectArray classes2NativeClasses (JNIEnv *env, const ug::bridge::Registry *reg)
jobjectArray classGroups2NativeClassGroups (JNIEnv *env, const ug::bridge::Registry *reg)
bool compareParamTypes (JNIEnv *env, jobjectArray params, ug::bridge::Registry *reg, ug::bridge::ParameterInfo const &paramStack, bool allowSmartToRawPtrConversion)
jobject constPointer2JObject (JNIEnv *env, const void *value)
jobject constPtrVector2JObject (JNIEnv *env, const std::vector< const void *> &pv)
jobject constructor2NativeConstructor (JNIEnv *env, const ug::bridge::ExportedConstructor *constructor)
jobjectArray constructors2NativeConstructors (JNIEnv *env, const ug::bridge::IExportedClass &eCls)
jobject constSmartPointer2JObject (JNIEnv *env, ConstSmartPtr< void > value)
jobject constSmartPtrVector2JObject (JNIEnv *env, const std::vector< ConstSmartPtr< void > > &pv)
int ConstSmartTestFunction (ConstSmartPtr< TestClass > test)
bool contains (std::string str, std::string search)
template<std::size_t dim>
jdoubleArray ConvertParametersToJava (JNIEnv *env, const MathVector< dim > &x, const number time)
jobjectArray createEmptyJavaArray (JNIEnv *env, std::string className)
jobjectArray createEmptyJavaArray (JNIEnv *env, jclass elementClass)
jobject createEmptyString (JNIEnv *env)
jobject cStringVector2JObject (JNIEnv *env, const std::vector< const char *> &sv)
jobject double2JObject (JNIEnv *env, jdouble value)
jobject function2NativeFunction (JNIEnv *env, const ug::bridge::ExportedFunction &func)
jobjectArray functions2NativeGroups (JNIEnv *env, ug::bridge::Registry *reg)
std::vector< const char * > getBaseClassNames (const ug::bridge::ClassNameNode *node)
jobject getClass (JNIEnv *env, jobject obj)
std::string getClassName (JNIEnv *env, jobject obj)
template<typename TVector >
SmartPtr< NumberArray > getDefects (const ug::StdConvCheck< TVector > *convCheck)
std::string getExceptionMessageString (JNIEnv *env, jthrowable exception)
SmartPtr< BasicTest > getInstanceBySmartPtr (std::string name)
JavaVM * getJavaVM ()
std::string getParamClassName (JNIEnv *env, jobject obj)
std::string getParamTypeAsString (const uint type)
std::string getParamTypesAsString (JNIEnv *env, jobjectArray const &array)
const std::vector< const ug::bridge::IExportedClass * > getParentClasses (ug::bridge::Registry *reg, const ug::bridge::IExportedClass *clazz)
void initJavaVM (JNIEnv *env)
jobject int2JObject (JNIEnv *env, jint value)
jobject intVector2JObject (JNIEnv *env, const std::vector< int > &iv)
void invalidateJConstSmartPointer (JNIEnv *env, jobject obj)
void invalidateJSmartPointer (JNIEnv *env, jobject obj)
bool isConstJPtr (JNIEnv *env, jobject obj)
bool isJObjectAnArray (JNIEnv *env, jobject value)
bool isJSmartPointerConst (JNIEnv *env, jobject ptr)
jboolean jObject2Boolean (JNIEnv *env, jobject obj)
void jObject2BoolVector (JNIEnv *env, jobject object, std::vector< bool > &bv)
ConstSmartPtr< void > jObject2ConstSmartPointer (JNIEnv *env, jobject obj)
void jObject2ConstSmartPtrVector (JNIEnv *env, jobject object, ug::Variant::Type jo_type, ug::bridge::Registry *reg, std::vector< std::pair< ConstSmartPtr< void >, const ug::bridge::ClassNameNode *> > &pv)
jdouble jObject2Double (JNIEnv *env, jobject obj)
jint jObject2Int (JNIEnv *env, jobject obj)
void jObject2IntVector (JNIEnv *env, jobject object, std::vector< int > &iv)
void jObject2NumberVector (JNIEnv *env, jobject object, std::vector< number > &nv)
void * jObject2Pointer (JNIEnv *env, jobject obj)
void jObject2PtrVector (JNIEnv *env, jobject object, ug::Variant::Type jo_type, ug::bridge::Registry *reg, std::vector< std::pair< void *, const ug::bridge::ClassNameNode *> > &pv)
void jObject2SizetVector (JNIEnv *env, jobject object, std::vector< size_t > &stv)
SmartPtr< void > jObject2SmartPointer (JNIEnv *env, jobject obj)
void jObject2SmartPtrVector (JNIEnv *env, jobject object, ug::bridge::Registry *reg, std::vector< std::pair< SmartPtr< void >, const ug::bridge::ClassNameNode *> > &pv)
void jObject2stdStringVector (JNIEnv *env, jobject object, std::vector< std::string > &sv)
std::string jObject2String (JNIEnv *env, jobject obj)
void jobjectArray2ParamStack (JNIEnv *env, ug::bridge::Registry *reg, ug::bridge::ParameterStack &paramsOut, const ug::bridge::ParameterInfo &paramsTemplate, jobjectArray const &array)
std::string jPointerGetName (JNIEnv *env, jobject obj)
void Log (std::string s)
void Logln (std::string s)
jobject method2NativeMethod (JNIEnv *env, const ug::bridge::ExportedMethod *method)
jobjectArray methods2NativeGroups (JNIEnv *env, const ug::bridge::IExportedClass &eCls, bool constMethods)
jobject numberVector2JObject (JNIEnv *env, const std::vector< number > &nv)
jobject param2JObject (JNIEnv *env, ug::bridge::ParameterStack &params, size_t index)
TypeAndArray paramClass2ParamType (JNIEnv *env, jobject obj)
jobjectArray params2NativeParams (JNIEnv *env, const ug::bridge::ExportedFunctionBase &func)
jobjectArray params2NativeParams (JNIEnv *env, const ug::bridge::ExportedConstructor &constructor)
int paramType2Int (const ug::bridge::ParameterInfo &params, size_t index)
jobject pointer2JObject (JNIEnv *env, void *value)
void printParamType (const uint type, size_t index)
jobject ptrVector2JObject (JNIEnv *env, const std::vector< void *> &pv)
void registerBasicTest (ug::bridge::Registry &reg)
void registerMessaging (ug::bridge::Registry &reg)
void registerNumberArray (ug::bridge::Registry &reg)
void registerPlayground (ug::bridge::Registry &reg)
void registerThrowUtil (ug::bridge::Registry &reg)
void registerUGFinalize (ug::bridge::Registry &reg)
template<int dim>
void RegisterUserData (ug::bridge::Registry &reg, const char *parentGroup)
template<typename TData , int dim>
void RegisterUserDataType (ug::bridge::Registry &reg, const std::string &grp)
void RegisterVRLFunctionality (ug::bridge::Registry &reg, std::string grp)
jobject registry2NativeAPI (JNIEnv *env, ug::bridge::Registry *reg)
std::string replaceAll (std::string target, const std::string oldstr, const std::string newstr)
jobject retVal2NativeParam (JNIEnv *env, const ug::bridge::ExportedFunctionBase &func)
void serrPrintln (std::string msg)
void SetVRLRegistry (ug::bridge::Registry *pReg)
jobject sizetVector2JObject (JNIEnv *env, const std::vector< size_t > &iv)
jobject smartPointer2JObject (JNIEnv *env, SmartPtr< void > value)
jobject smartPtrVector2JObject (JNIEnv *env, const std::vector< SmartPtr< void > > &pv)
int SmartTestFunction (SmartPtr< TestClass > test)
void soutPrintln (std::string msg)
std::vector< std::string > split (const std::string &str, const char delimiter)
bool startsWith (std::string str, std::string search)
jobject stdStringVector2JObject (JNIEnv *env, const std::vector< std::string > &sv)
jobject string2JObject (JNIEnv *env, const char *value)
jobjectArray stringArrayC2J (JNIEnv *env, const std::string *strings, const size_t array_length)
jobjectArray stringArrayC2J (JNIEnv *env, const char *const *strings, const unsigned int array_length)
jobjectArray stringArrayC2J (JNIEnv *env, const std::string *strings)
jobjectArray stringArrayC2J (JNIEnv *env, std::vector< std::string > const &strings)
jobjectArray stringArrayC2J (JNIEnv *env, const std::vector< const char *> *strings)
jobjectArray stringArrayC2J (JNIEnv *env, const std::vector< const char *> strings)
std::vector< std::string > stringArrayJ2C (JNIEnv *env, jobjectArray const &array)
jstring stringC2J (JNIEnv *env, const char *s)
std::string stringJ2C (JNIEnv *env, jstring const &s)
std::string svnRevision ()
void TestSmartPtr2ConstPtr (const TestClass *t)
void ThrowIf (bool b, std::string s)
void ThrowIfNot (bool b, std::string s)
void throwUgErrorAsJavaException (JNIEnv *env, ug::UGError error)
void throwUgErrorAsJavaException (JNIEnv *env, std::string error)
Variables
static JavaVM * javaVM = NULL
static ug::bridge::Registry * vrlRegistry = NULL
Function Documentation
boolC2J()
jboolean ug::vrl::boolC2J (bool b) inline
Converts a native boolean to a Java boolean.
Parameters
b native boolean to convert
Returns
Java boolean
References boolean2JObject(), boolVector2JObject(), compareParamTypes(), constPointer2JObject(), constPtrVector2JObject(), constSmartPointer2JObject(), constSmartPtrVector2JObject(), createEmptyJavaArray(), cStringVector2JObject(), double2JObject(), getBaseClassNames(), getClass(), getClassName(), getParamClassName(), getParamTypeAsString(), getParamTypesAsString(), getParentClasses(), int2JObject(), intVector2JObject(), invalidateJConstSmartPointer(), invalidateJSmartPointer(), isConstJPtr(), isJObjectAnArray(), isJSmartPointerConst(), jObject2Boolean(), jObject2BoolVector(), jObject2ConstSmartPtrVector(), jObject2Double(), jObject2Int(), jObject2IntVector(), jObject2NumberVector(), jObject2Pointer(), jObject2PtrVector(), jObject2SizetVector(), jObject2SmartPtrVector(), jObject2stdStringVector(), jObject2String(), jobjectArray2ParamStack(), jPointerGetName(), numberVector2JObject(), param2JObject(), paramClass2ParamType(), pointer2JObject(), ptrVector2JObject(), registry2NativeAPI(), sizetVector2JObject(), smartPointer2JObject(), smartPtrVector2JObject(), stdStringVector2JObject(), string2JObject(), throwUgErrorAsJavaException(), and ug::vrl::TypeAndArray::type.
Referenced by classes2NativeClasses(), constPointer2JObject(), constSmartPointer2JObject(), function2NativeFunction(), pointer2JObject(), and smartPointer2JObject().
boolean2JObject()
jobject ug::vrl::boolean2JObject (JNIEnv * env, jboolean value)
Converts a jboolean to a Java object (jobject).
Parameters
env JVM environment to operate on
value value to convert
Returns
Java object (jobject)
Referenced by boolC2J(), boolVector2JObject(), and param2JObject().
boolJ2C()
bool ug::vrl::boolJ2C (jboolean b) inline
Converts a Java boolean to a native boolean.
Parameters
b Java boolean to convert
Returns
native boolean
Referenced by getParamClassName(), isJSmartPointerConst(), Java_edu_gcsc_vrl_ug_UG__1getExportedClassPtrByName(), and Java_edu_gcsc_vrl_ug_UG__1invokeMethod().
boolVector2JObject()
jobject ug::vrl::boolVector2JObject (JNIEnv * env, const std::vector< bool > & bv)
Converts a bool vector to a Java object (jobject).
Parameters
env JVM environment to operate on
bv vector to convert
Returns
Java object (jobject)
References boolean2JObject().
Referenced by boolC2J(), and param2JObject().
checkException()
bool ug::vrl::checkException (JNIEnv * env, std::string msg = "", bool throwCPPException = true)
Checks whether an exception has occured. And logs available exception messages.
Parameters
env JVM environment
msg custom error message (shown if exception occurs)
throwCPPException defines whether to throw a C++ exception (default true)
Returns
true if no exception has occured; false otherwise
References getExceptionMessageString(), UG_LOG, and UG_THROW.
Referenced by ug::vrl::vrl_traits< number >::call(), ug::vrl::vrl_traits< ug::MathVector< dim > >::call(), ug::vrl::vrl_traits< ug::MathMatrix< dim, dim > >::call(), ConvertParametersToJava(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_deriv(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_value(), ug::vrl::VRLCondUserNumber< dim >::evaluate(), ug::vrl::VRLCondUserNumber< dim >::getCondUserDataRunMethod(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::getUserDataRunMethod(), ug::vrl::VRLUserData< TData, dim >::getUserDataRunMethod(), ug::vrl::VRLUserData< TData, dim >::set_vrl_callback(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_deriv_callback(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
ChrisPoliTest() [1/4]
void ug::vrl::ChrisPoliTest ()
ChrisPoliTest() [2/4]
void ug::vrl::ChrisPoliTest (int i)
ChrisPoliTest() [3/4]
void ug::vrl::ChrisPoliTest (bool array[])
ChrisPoliTest() [4/4]
void ug::vrl::ChrisPoliTest (std::vector< bool > vec)
ChrisPoliTestCreateFile() [1/3]
void ug::vrl::ChrisPoliTestCreateFile ()
Referenced by registerPlayground().
ChrisPoliTestCreateFile() [2/3]
std::string ug::vrl::ChrisPoliTestCreateFile (std::string path)
ChrisPoliTestCreateFile() [3/3]
std::string ug::vrl::ChrisPoliTestCreateFile (std::string inPath, std::string outPath)
ChrisPoliTestReturn()
std::vector<bool> ug::vrl::ChrisPoliTestReturn (std::vector< bool > vec)
Referenced by registerPlayground().
classes2NativeClasses()
jobjectArray ug::vrl::classes2NativeClasses (JNIEnv * env, const ug::bridge::Registry * reg)
References boolC2J(), ug::bridge::IExportedClass::class_names(), constructors2NativeConstructors(), ug::bridge::Registry::get_class(), ug::bridge::IExportedClass::group(), ug::bridge::IExportedClass::is_instantiable(), methods2NativeGroups(), ug::bridge::IExportedClass::name(), ug::bridge::Registry::num_classes(), stringArrayC2J(), and stringC2J().
Referenced by registry2NativeAPI().
classGroups2NativeClassGroups()
jobjectArray ug::vrl::classGroups2NativeClassGroups (JNIEnv * env, const ug::bridge::Registry * reg)
References ug::bridge::ClassGroupDesc::empty(), ug::bridge::ClassGroupDesc::get_class(), ug::bridge::Registry::get_class_group(), ug::bridge::ClassGroupDesc::get_default_class(), ug::bridge::ClassGroupDesc::name(), ug::bridge::IExportedClass::name(), ug::bridge::Registry::num_class_groups(), ug::bridge::ClassGroupDesc::num_classes(), stringArrayC2J(), and stringC2J().
Referenced by registry2NativeAPI().
compareParamTypes()
bool ug::vrl::compareParamTypes (JNIEnv * env, jobjectArray params, ug::bridge::Registry * reg, const ug::bridge::ParameterInfo & paramStack, bool allowSmartToRawPtrConversion = false)
Compares the parameter types of a Java object array and a paramter stack. It ignores differences regarding constness. This is checked by Java via interface types.
Parameters
env JVM environment to operate on
params array of Java objects
reg ug registry
paramStack parameter stack
Returns
true if parameter types are equal; false otherwise
References ug::bridge::ParameterInfo::class_name(), ug::bridge::ClassNameTreeContains(), ug::vrl::invocation::getClassNodePtrByName(), getParamClassName(), ug::bridge::ParameterInfo::is_vector(), paramClass2ParamType(), ug::bridge::ParameterInfo::size(), throwUgErrorAsJavaException(), ug::bridge::ParameterInfo::type(), ug::Variant::VT_CONST_POINTER, ug::Variant::VT_CONST_SMART_POINTER, ug::Variant::VT_CSTRING, ug::Variant::VT_INT, ug::Variant::VT_POINTER, ug::Variant::VT_SIZE_T, ug::Variant::VT_SMART_POINTER, and ug::Variant::VT_STDSTRING.
Referenced by boolC2J(), ug::vrl::invocation::getConstructorBySignature(), ug::vrl::invocation::getFunctionBySignature(), and ug::vrl::invocation::getMethodBySignature().
constPointer2JObject()
jobject ug::vrl::constPointer2JObject (JNIEnv * env, const void * value)
Converts a native const pointer to a Java object (jobject).
Parameters
env JVM environment to operate on
value const pointer to convert
Returns
a Java object (jobject)
References boolC2J(), and JNULL.
Referenced by boolC2J(), constPtrVector2JObject(), and param2JObject().
constPtrVector2JObject()
jobject ug::vrl::constPtrVector2JObject (JNIEnv * env, const std::vector< const void * > & pv)
Converts a const-void-pointer vector to a Java object (jobject).
Parameters
env JVM environment to operate on
pv vector to convert
Returns
Java object (jobject)
References constPointer2JObject().
Referenced by boolC2J(), and param2JObject().
constructor2NativeConstructor()
jobject ug::vrl::constructor2NativeConstructor (JNIEnv * env, const ug::bridge::ExportedConstructor * constructor)
References ug::bridge::ExportedConstructor::help(), ug::bridge::ExportedConstructor::options(), params2NativeParams(), stringC2J(), and ug::bridge::ExportedConstructor::tooltip().
Referenced by constructors2NativeConstructors().
constructors2NativeConstructors()
jobjectArray ug::vrl::constructors2NativeConstructors (JNIEnv * env, const ug::bridge::IExportedClass & eCls)
References constructor2NativeConstructor(), ug::bridge::IExportedClass::get_constructor(), and ug::bridge::IExportedClass::num_constructors().
Referenced by classes2NativeClasses().
constSmartPointer2JObject()
jobject ug::vrl::constSmartPointer2JObject (JNIEnv * env, ConstSmartPtr< void > value)
Converts a native const smart-pointer to a Java object (jobject).
Parameters
env JVM environment to operate on
value const smart-pointer to convert
Returns
a Java object (jobject)
References boolC2J(), ConstSmartPtr< void >::get(), and JNULL.
Referenced by boolC2J(), constSmartPtrVector2JObject(), and param2JObject().
constSmartPtrVector2JObject()
jobject ug::vrl::constSmartPtrVector2JObject (JNIEnv * env, const std::vector< ConstSmartPtr< void > > & pv)
Converts a ConstSmartPtr vector to a Java object (jobject).
Parameters
env JVM environment to operate on
pv vector to convert
Returns
Java object (jobject)
References constSmartPointer2JObject().
Referenced by boolC2J(), and param2JObject().
ConstSmartTestFunction()
int ug::vrl::ConstSmartTestFunction (ConstSmartPtr< TestClass > test)
References ConstSmartPtr< T, FreePolicy >::refcount(), and UG_LOG.
Referenced by registerPlayground().
contains()
bool ug::vrl::contains (std::string str, std::string search)
Checks whether str contains search.
Parameters
str string
search string to search
Returns
true if str contains search; false otherwise
Referenced by ug::GetElemDiscOnSubset(), ug::SurfaceView::mark_shadowing(), and ug::bridge::RegisterDegeneratedLayerManager().
ConvertParametersToJava()
template<std::size_t dim> jdoubleArray ug::vrl::ConvertParametersToJava (JNIEnv * env, const MathVector< dim > & x, const number time) inline
References checkException(), and dim.
Referenced by ug::vrl::VRLUserData< TData, dim >::evaluate(), and ug::vrl::VRLCondUserNumber< dim >::evaluate().
createEmptyJavaArray() [1/2]
jobjectArray ug::vrl::createEmptyJavaArray (JNIEnv * env, std::string className)
Creates an empty Java array using the specified class as element type.
Parameters
env JVM environment to operate on
className name of the element class
Returns
emtpy Java array
Referenced by boolC2J().
createEmptyJavaArray() [2/2]
jobjectArray ug::vrl::createEmptyJavaArray (JNIEnv * env, jclass elementClass)
Creates an empty Java array using the specified class as element type.
Parameters
env JVM environment to operate on
elementClass element class
Returns
emtpy Java array
createEmptyString()
jobject ug::vrl::createEmptyString (JNIEnv * env)
Referenced by stringArrayC2J().
cStringVector2JObject()
jobject ug::vrl::cStringVector2JObject (JNIEnv * env, const std::vector< const char * > & sv)
Converts a c-string vector to a Java object (jobject).
Parameters
env JVM environment to operate on
sv vector to convert
Returns
Java object (jobject)
References string2JObject().
Referenced by boolC2J(), and param2JObject().
double2JObject()
jobject ug::vrl::double2JObject (JNIEnv * env, jdouble value)
Converts a double to a Java object (jobject).
Parameters
env JVM environment to operate on
value value to convert
Returns
a Java object (jobject)
Referenced by boolC2J(), numberVector2JObject(), and param2JObject().
function2NativeFunction()
jobject ug::vrl::function2NativeFunction (JNIEnv * env, const ug::bridge::ExportedFunction & func)
References boolC2J(), ug::bridge::ExportedFunction::group(), ug::bridge::ExportedFunctionBase::help(), ug::bridge::ExportedFunctionBase::name(), ug::bridge::ExportedFunctionBase::options(), params2NativeParams(), retVal2NativeParam(), and stringC2J().
Referenced by functions2NativeGroups().
functions2NativeGroups()
jobjectArray ug::vrl::functions2NativeGroups (JNIEnv * env, ug::bridge::Registry * reg)
References function2NativeFunction(), ug::bridge::Registry::get_function_group(), ug::bridge::ExportedFunctionGroup::get_overload(), ug::bridge::Registry::num_functions(), and ug::bridge::ExportedFunctionGroup::num_overloads().
Referenced by registry2NativeAPI().
getBaseClassNames()
std::vector< const char * > ug::vrl::getBaseClassNames (const ug::bridge::ClassNameNode * node)
Returns the base classes of the given class name node.
Returns
the base classes of the given class name node
References ug::bridge::ExtractClassNameVec().
Referenced by boolC2J(), params2NativeParams(), and retVal2NativeParam().
getClass()
jobject ug::vrl::getClass (JNIEnv * env, jobject obj)
Returns the class object of the specified Java object.
Parameters
env JVM environment to operate on
obj Java object
Returns
class object of the specified Java object
Referenced by boolC2J().
getClassName()
std::string ug::vrl::getClassName (JNIEnv * env, jobject obj)
Returns the class name of the specified Java object.
Parameters
env JVM environment to operate on
obj Java object
Returns
class name of the specified Java object
References jObject2String().
Referenced by boolC2J(), isJObjectAnArray(), and paramClass2ParamType().
getDefects()
template<typename TVector > SmartPtr<NumberArray> ug::vrl::getDefects (const ug::StdConvCheck< TVector > * convCheck)
References ug::StdConvCheck< TVector >::get_defects(), and ug::vrl::NumberArray::NumberArray().
getExceptionMessageString()
std::string ug::vrl::getExceptionMessageString (JNIEnv * env, jthrowable ex)
Returns the message string of the specified Java exception. If no exception occured, an empty String will be returned.
Parameters
env JVM environment
ex Java exception
Returns
the message string of the specified Java exception or an empty string if no exception occured
References stringJ2C().
Referenced by checkException().
getInstanceBySmartPtr()
SmartPtr< BasicTest > ug::vrl::getInstanceBySmartPtr (std::string name)
References ug::vrl::BasicTest::BasicTest().
Referenced by registerBasicTest().
getJavaVM()
JavaVM * ug::vrl::getJavaVM ()
References javaVM.
Referenced by ug::vrl::MessageBuffer::addMessage(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_deriv(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_value(), ug::vrl::VRLUserData< TData, dim >::evaluate(), ug::vrl::VRLCondUserNumber< dim >::evaluate(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::releaseGlobalRefs(), ug::vrl::VRLUserData< TData, dim >::releaseGlobalRefs(), ug::vrl::VRLCondUserNumber< dim >::releaseGlobalRefs(), ug::vrl::VRLUserData< TData, dim >::set_vrl_callback(), ug::vrl::VRLCondUserNumber< dim >::set_vrl_callback(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_deriv_callback(), and ug::vrl::VRLUserLinker< TData, dim, TDataIn >::set_vrl_value_callback().
getParamClassName()
std::string ug::vrl::getParamClassName (JNIEnv * env, jobject obj)
Returns the class name of the specified param object (class UGObject).
Parameters
env JVM environment to operate on
obj param object
Returns
class name of the specified param object
References boolJ2C(), and jObject2String().
Referenced by boolC2J(), compareParamTypes(), and getParamTypesAsString().
getParamTypeAsString()
std::string ug::vrl::getParamTypeAsString (const uint type)
Returns the the name of the specified parameter type.
Returns
the the name of the specified parameter type
References ug::Variant::VT_BOOL, ug::Variant::VT_CONST_POINTER, ug::Variant::VT_CONST_SMART_POINTER, ug::Variant::VT_CSTRING, ug::Variant::VT_DOUBLE, ug::Variant::VT_FLOAT, ug::Variant::VT_INT, ug::Variant::VT_INVALID, ug::Variant::VT_POINTER, ug::Variant::VT_SMART_POINTER, and ug::Variant::VT_STDSTRING.
Referenced by boolC2J(), and getParamTypesAsString().
getParamTypesAsString()
std::string ug::vrl::getParamTypesAsString (JNIEnv * env, jobjectArray const & array)
Returns the the names of the specified parameter types.
Returns
the the names of the specified parameter types
References getParamClassName(), getParamTypeAsString(), jobjectArray2ParamStack(), paramClass2ParamType(), ug::vrl::TypeAndArray::type, ug::Variant::VT_CONST_POINTER, ug::Variant::VT_CONST_SMART_POINTER, ug::Variant::VT_POINTER, and ug::Variant::VT_SMART_POINTER.
Referenced by boolC2J(), Java_edu_gcsc_vrl_ug_UG__1invokeFunction(), Java_edu_gcsc_vrl_ug_UG__1invokeMethod(), and Java_edu_gcsc_vrl_ug_UG__1newInstance().
getParentClasses()
const std::vector< const ug::bridge::IExportedClass * > ug::vrl::getParentClasses (ug::bridge::Registry * reg, const ug::bridge::IExportedClass * clazz)
Returns parent classes (super classes) of an exported class.
Parameters
reg registry to search
clazz exported class
Returns
a vector containing all parent classes of the given class
References ug::bridge::IExportedClass::class_names(), and ug::vrl::invocation::getExportedClassPtrByName().
Referenced by boolC2J(), and ug::vrl::invocation::getMethodBySignature().
initJavaVM()
void ug::vrl::initJavaVM (JNIEnv * env)
Defines the JVM to operate on based on the specified JNI environment. The JVM can only be initialized once.
Parameters
env JVM environment
References UG_LOG.
Referenced by Java_edu_gcsc_vrl_ug_UG__1ugInit().
int2JObject()
jobject ug::vrl::int2JObject (JNIEnv * env, jint value)
Converts an integer to a Java object (jobject).
Parameters
env JVM environment to operate on
value value to convert
Returns
Java object (jobject)
Referenced by boolC2J(), intVector2JObject(), param2JObject(), and sizetVector2JObject().
intVector2JObject()
jobject ug::vrl::intVector2JObject (JNIEnv * env, const std::vector< int > & iv)
Converts an int vector to a Java object (jobject).
Parameters
env JVM environment to operate on
iv vector to convert
Returns
Java object (jobject)
References int2JObject().
Referenced by boolC2J(), and param2JObject().
invalidateJConstSmartPointer()
void ug::vrl::invalidateJConstSmartPointer (JNIEnv * env, jobject obj)
Invalidates the native equivalent of the specified Java smart pointer. TODO what about error handling???
Parameters
env JVM environment to operate on
obj smart pointer to invalidate
Referenced by boolC2J(), and Java_edu_gcsc_vrl_ug_UG__1invalidate().
invalidateJSmartPointer()
void ug::vrl::invalidateJSmartPointer (JNIEnv * env, jobject obj)
Invalidates the native equivalent of the specified Java smart pointer. TODO what about error handling???
Parameters
env JVM environment to operate on
obj smart pointer to invalidate
Referenced by boolC2J(), and Java_edu_gcsc_vrl_ug_UG__1invalidate().
isConstJPtr()
bool ug::vrl::isConstJPtr (JNIEnv * env, jobject obj)
Finds out whether a java pointer wrapper is const.
Parameters
env JVM environment to operate on
obj pointer type to check for constness
Returns
true iff pointer wrapper's readOnly member is true
Referenced by boolC2J(), and paramClass2ParamType().
isJObjectAnArray()
bool ug::vrl::isJObjectAnArray (JNIEnv * env, jobject value)
References getClassName().
Referenced by boolC2J(), Java_edu_gcsc_vrl_ug_UG__1getBinaryLicense(), and paramClass2ParamType().
isJSmartPointerConst()
bool ug::vrl::isJSmartPointerConst (JNIEnv * env, jobject ptr)
Indicates whether the specified smart pointer is const, i.e., if the specified Java object represents a const smart pointer.
Parameters
env JVM environment to operate on
ptr smart pointer to check
Returns
true if the specified smart pointer is const; false otherwise
References boolJ2C().
Referenced by boolC2J(), Java_edu_gcsc_vrl_ug_UG__1invalidate(), and jObject2ConstSmartPointer().
jObject2Boolean()
jboolean ug::vrl::jObject2Boolean (JNIEnv * env, jobject obj)
Converts a Java object to a native boolean value.
Parameters
env JVM environment to operate on
obj object to convert
Returns
a native boolean value
Referenced by boolC2J(), jObject2BoolVector(), and jobjectArray2ParamStack().
jObject2BoolVector()
void ug::vrl::jObject2BoolVector (JNIEnv * env, jobject object, std::vector< bool > & bv)
References jObject2Boolean().
Referenced by boolC2J(), and jobjectArray2ParamStack().
jObject2ConstSmartPointer()
ConstSmartPtr<void> ug::vrl::jObject2ConstSmartPointer (JNIEnv * env, jobject obj)
References isJSmartPointerConst(), and jObject2SmartPointer().
Referenced by jObject2ConstSmartPtrVector(), jObject2PtrVector(), and jobjectArray2ParamStack().
jObject2ConstSmartPtrVector()
void ug::vrl::jObject2ConstSmartPtrVector (JNIEnv * env, jobject object, ug::Variant::Type jo_type, ug::bridge::Registry * reg, std::vector< std::pair< ConstSmartPtr< void >, const ug::bridge::ClassNameNode *> > & pv)
References ug::vrl::invocation::getClassNodePtrByName(), jObject2ConstSmartPointer(), jObject2SmartPointer(), jPointerGetName(), and ug::Variant::VT_SMART_POINTER.
Referenced by boolC2J(), jObject2SmartPtrVector(), and jobjectArray2ParamStack().
jObject2Double()
jdouble ug::vrl::jObject2Double (JNIEnv * env, jobject obj)
Converts a Java object (jobject) to a native double value.
Parameters
env JVM environment to operate on
obj object to convert
Returns
a native double value
Referenced by boolC2J(), jObject2NumberVector(), and jobjectArray2ParamStack().
jObject2Int()
jint ug::vrl::jObject2Int (JNIEnv * env, jobject obj)
Converts a Java object (jobject) to a native int value.
Parameters
env JVM environment to operate on
obj object to convert
Returns
a native int value
Referenced by boolC2J(), jObject2IntVector(), jObject2SizetVector(), and jobjectArray2ParamStack().
jObject2IntVector()
void ug::vrl::jObject2IntVector (JNIEnv * env, jobject object, std::vector< int > & iv)
References jObject2Int().
Referenced by boolC2J(), and jobjectArray2ParamStack().
jObject2NumberVector()
void ug::vrl::jObject2NumberVector (JNIEnv * env, jobject object, std::vector< number > & nv)
References jObject2Double().
Referenced by boolC2J(), and jobjectArray2ParamStack().
jObject2Pointer()
void * ug::vrl::jObject2Pointer (JNIEnv * env, jobject obj)
Converts a Java object (jobject) to a native pointer.
Parameters
env JVM environment to operate on
obj object to convert
Returns
a native pointer
Referenced by boolC2J(), jObject2PtrVector(), and jobjectArray2ParamStack().
jObject2PtrVector()
void ug::vrl::jObject2PtrVector (JNIEnv * env, jobject object, ug::Variant::Type jo_type, ug::bridge::Registry * reg, std::vector< std::pair< void *, const ug::bridge::ClassNameNode *> > & pv)
References ug::vrl::invocation::getClassNodePtrByName(), jObject2ConstSmartPointer(), jObject2Pointer(), jObject2SmartPointer(), jObject2SmartPtrVector(), jPointerGetName(), ug::Variant::VT_CONST_SMART_POINTER, and ug::Variant::VT_SMART_POINTER.
Referenced by boolC2J(), jObject2stdStringVector(), and jobjectArray2ParamStack().
jObject2SizetVector()
void ug::vrl::jObject2SizetVector (JNIEnv * env, jobject object, std::vector< size_t > & stv)
References jObject2Int().
Referenced by boolC2J(), and jobjectArray2ParamStack().
jObject2SmartPointer()
SmartPtr<void> ug::vrl::jObject2SmartPointer (JNIEnv * env, jobject obj)
Referenced by jObject2ConstSmartPointer(), jObject2ConstSmartPtrVector(), jObject2PtrVector(), jObject2SmartPtrVector(), and jobjectArray2ParamStack().
jObject2SmartPtrVector()
void ug::vrl::jObject2SmartPtrVector (JNIEnv * env, jobject object, ug::bridge::Registry * reg, std::vector< std::pair< SmartPtr< void >, const ug::bridge::ClassNameNode *> > & pv)
References ug::vrl::invocation::getClassNodePtrByName(), jObject2ConstSmartPtrVector(), jObject2SmartPointer(), and jPointerGetName().
Referenced by boolC2J(), jObject2PtrVector(), and jobjectArray2ParamStack().
jObject2stdStringVector()
void ug::vrl::jObject2stdStringVector (JNIEnv * env, jobject object, std::vector< std::string > & sv)
References jObject2PtrVector(), and jObject2String().
Referenced by boolC2J(), and jobjectArray2ParamStack().
jObject2String()
std::string ug::vrl::jObject2String (JNIEnv * env, jobject obj)
Converts a Java object (jobject) to a native string.
Parameters
env JVM environment to operate on
obj object to convert
Returns
a native string
References stringJ2C().
Referenced by boolC2J(), getClassName(), getParamClassName(), jObject2stdStringVector(), and jobjectArray2ParamStack().
jobjectArray2ParamStack()
void ug::vrl::jobjectArray2ParamStack (JNIEnv * env, ug::bridge::Registry * reg, ug::bridge::ParameterStack & paramsOut, const ug::bridge::ParameterInfo & paramsTemplate, jobjectArray const & array)
Converts an array of Java objects to a parameter stack.
Parameters
env JVM environment to operate on
reg ug registry
paramsOut converted parameter stack (return value)
paramsTemplate template parameter stack used to get correct parameter type
array object array to convert
References SmartPtr< T, FreePolicy >::get(), ug::vrl::invocation::getClassNodePtrByName(), ug::bridge::ParameterInfo::is_vector(), jObject2Boolean(), jObject2BoolVector(), jObject2ConstSmartPointer(), jObject2ConstSmartPtrVector(), jObject2Double(), jObject2Int(), jObject2IntVector(), jObject2NumberVector(), jObject2Pointer(), jObject2PtrVector(), jObject2SizetVector(), jObject2SmartPointer(), jObject2SmartPtrVector(), jObject2stdStringVector(), jObject2String(), jPointerGetName(), paramClass2ParamType(), ug::bridge::ParameterStack::push(), ug::bridge::ParameterInfo::size(), ug::vrl::TypeAndArray::type, ug::bridge::ParameterInfo::type(), UG_THROW, ug::Variant::VT_BOOL, ug::Variant::VT_CONST_POINTER, ug::Variant::VT_CONST_SMART_POINTER, ug::Variant::VT_CSTRING, ug::Variant::VT_DOUBLE, ug::Variant::VT_FLOAT, ug::Variant::VT_INT, ug::Variant::VT_INVALID, ug::Variant::VT_POINTER, ug::Variant::VT_SIZE_T, ug::Variant::VT_SMART_POINTER, and ug::Variant::VT_STDSTRING.
Referenced by boolC2J(), getParamTypesAsString(), Java_edu_gcsc_vrl_ug_UG__1invokeFunction(), Java_edu_gcsc_vrl_ug_UG__1invokeMethod(), and Java_edu_gcsc_vrl_ug_UG__1newInstance().
jPointerGetName()
std::string ug::vrl::jPointerGetName (JNIEnv * env, jobject obj)
Pendant of javas getName().
Parameters
env JVM environment to operate on
obj object which class name we want to know
Returns
the class name of the jobject
References stringJ2C().
Referenced by boolC2J(), jObject2ConstSmartPtrVector(), jObject2PtrVector(), jObject2SmartPtrVector(), and jobjectArray2ParamStack().
Log()
void ug::vrl::Log (std::string s)
References UG_LOG.
Referenced by registerMessaging().
Logln()
void ug::vrl::Logln (std::string s)
References UG_LOG.
Referenced by registerMessaging().
method2NativeMethod()
jobject ug::vrl::method2NativeMethod (JNIEnv * env, const ug::bridge::ExportedMethod * method)
References ug::bridge::ExportedFunctionBase::help(), ug::bridge::ExportedFunctionBase::name(), ug::bridge::ExportedFunctionBase::options(), params2NativeParams(), retVal2NativeParam(), and stringC2J().
Referenced by methods2NativeGroups().
methods2NativeGroups()
jobjectArray ug::vrl::methods2NativeGroups (JNIEnv * env, const ug::bridge::IExportedClass & eCls, bool constMethods)
References ug::bridge::IExportedClass::get_const_overload(), ug::bridge::IExportedClass::get_overload(), method2NativeMethod(), ug::bridge::IExportedClass::num_const_methods(), ug::bridge::IExportedClass::num_const_overloads(), ug::bridge::IExportedClass::num_methods(), and ug::bridge::IExportedClass::num_overloads().
Referenced by classes2NativeClasses().
numberVector2JObject()
jobject ug::vrl::numberVector2JObject (JNIEnv * env, const std::vector< number > & nv)
Converts a number vector to a Java object (jobject).
Parameters
env JVM environment to operate on
nv vector to convert
Returns
Java object (jobject)
References double2JObject().
Referenced by boolC2J(), and param2JObject().
param2JObject()
jobject ug::vrl::param2JObject (JNIEnv * env, ug::bridge::ParameterStack & params, size_t index)
Converts a parameter stack entry to a Java object.
Parameters
env JVM environment to operate on
params parameter stack to convert
index index of the element to convert
Returns
a Java object (jobject)
References boolean2JObject(), boolVector2JObject(), constPointer2JObject(), constPtrVector2JObject(), constSmartPointer2JObject(), constSmartPtrVector2JObject(), cStringVector2JObject(), double2JObject(), int2JObject(), intVector2JObject(), ug::bridge::ParameterInfo::is_vector(), numberVector2JObject(), pointer2JObject(), ptrVector2JObject(), sizetVector2JObject(), smartPointer2JObject(), smartPtrVector2JObject(), stdStringVector2JObject(), string2JObject(), ug::bridge::ParameterStack::to(), ug::bridge::ParameterInfo::type(), UG_THROW, ug::Variant::VT_BOOL, ug::Variant::VT_CONST_POINTER, ug::Variant::VT_CONST_SMART_POINTER, ug::Variant::VT_CSTRING, ug::Variant::VT_DOUBLE, ug::Variant::VT_FLOAT, ug::Variant::VT_INT, ug::Variant::VT_INVALID, ug::Variant::VT_POINTER, ug::Variant::VT_SIZE_T, ug::Variant::VT_SMART_POINTER, and ug::Variant::VT_STDSTRING.
Referenced by boolC2J(), Java_edu_gcsc_vrl_ug_UG__1invokeFunction(), and Java_edu_gcsc_vrl_ug_UG__1invokeMethod().
paramClass2ParamType()
TypeAndArray ug::vrl::paramClass2ParamType (JNIEnv * env, jobject obj)
Returns the parameter type (ug::bridge::ParameterTypes) of the specified Java object.
Parameters
env JVM environment to operate on
obj Java object
Returns
parameter type (ug::bridge::ParameterTypes) of the specified Java object
References getClassName(), ug::vrl::TypeAndArray::isArray, isConstJPtr(), isJObjectAnArray(), ug::vrl::TypeAndArray::type, UG_LOG, ug::Variant::VT_BOOL, ug::Variant::VT_CONST_POINTER, ug::Variant::VT_CONST_SMART_POINTER, ug::Variant::VT_DOUBLE, ug::Variant::VT_INT, ug::Variant::VT_INVALID, ug::Variant::VT_POINTER, ug::Variant::VT_SMART_POINTER, and ug::Variant::VT_STDSTRING.
Referenced by boolC2J(), compareParamTypes(), getParamTypesAsString(), and jobjectArray2ParamStack().
params2NativeParams() [1/2]
jobjectArray ug::vrl::params2NativeParams (JNIEnv * env, const ug::bridge::ExportedFunctionBase & func)
References ug::bridge::ParameterInfo::class_name(), ug::bridge::ParameterInfo::class_name_node(), getBaseClassNames(), ug::bridge::ParameterInfo::is_vector(), ug::bridge::ExportedFunctionBase::name(), ug::bridge::ExportedFunctionBase::num_parameter(), ug::bridge::ExportedFunctionBase::parameter_info_vec(), ug::bridge::ExportedFunctionBase::params_in(), paramType2Int(), stringArrayC2J(), stringC2J(), ug::bridge::ParameterInfo::type(), ug::Variant::VT_CONST_POINTER, ug::Variant::VT_CONST_SMART_POINTER, ug::Variant::VT_POINTER, and ug::Variant::VT_SMART_POINTER.
Referenced by constructor2NativeConstructor(), function2NativeFunction(), and method2NativeMethod().
params2NativeParams() [2/2]
jobjectArray ug::vrl::params2NativeParams (JNIEnv * env, const ug::bridge::ExportedConstructor & constructor)
References ug::bridge::ParameterInfo::class_name(), ug::bridge::ParameterInfo::class_name_node(), getBaseClassNames(), ug::bridge::ParameterInfo::is_vector(), ug::bridge::ExportedConstructor::num_parameter(), ug::bridge::ExportedConstructor::parameter_info_vec(), ug::bridge::ExportedConstructor::params_in(), paramType2Int(), stringArrayC2J(), and stringC2J().
paramType2Int()
int ug::vrl::paramType2Int (const ug::bridge::ParameterInfo & params, size_t index)
References ug::bridge::ParameterInfo::type().
Referenced by params2NativeParams(), and retVal2NativeParam().
pointer2JObject()
jobject ug::vrl::pointer2JObject (JNIEnv * env, void * value)
Converts a native pointer to a Java object (jobject).
Parameters
env JVM environment to operate on
value pointer to convert
Returns
a Java object (jobject)
References boolC2J(), and JNULL.
Referenced by boolC2J(), Java_edu_gcsc_vrl_ug_UG__1newInstance(), param2JObject(), and ptrVector2JObject().
printParamType()
void ug::vrl::printParamType (const uint type, size_t index)
References UG_LOG, ug::Variant::VT_BOOL, ug::Variant::VT_CONST_POINTER, ug::Variant::VT_CONST_SMART_POINTER, ug::Variant::VT_CSTRING, ug::Variant::VT_DOUBLE, ug::Variant::VT_FLOAT, ug::Variant::VT_INT, ug::Variant::VT_INVALID, ug::Variant::VT_POINTER, ug::Variant::VT_SIZE_T, ug::Variant::VT_SMART_POINTER, and ug::Variant::VT_STDSTRING.
ptrVector2JObject()
jobject ug::vrl::ptrVector2JObject (JNIEnv * env, const std::vector< void * > & pv)
Converts a void-pointer vector to a Java object (jobject).
Parameters
env JVM environment to operate on
pv vector to convert
Returns
Java object (jobject)
References pointer2JObject().
Referenced by boolC2J(), and param2JObject().
registerBasicTest()
void ug::vrl::registerBasicTest (ug::bridge::Registry & reg)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_function(), ug::vrl::BasicTest::get(), getInstanceBySmartPtr(), and ug::vrl::BasicTest::size().
Referenced by RegisterVRLFunctionality().
registerMessaging()
void ug::vrl::registerMessaging (ug::bridge::Registry & reg)
References ug::bridge::Registry::add_function(), Log(), and Logln().
Referenced by RegisterVRLFunctionality().
registerNumberArray()
void ug::vrl::registerNumberArray (ug::bridge::Registry & reg)
References ug::bridge::Registry::add_class_(), ug::vrl::NumberArray::get(), and ug::vrl::NumberArray::size().
Referenced by RegisterVRLFunctionality().
registerPlayground()
void ug::vrl::registerPlayground (ug::bridge::Registry & reg)
References ug::vrl::TestClass::add(), ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_function(), ChrisPoliTestCreateFile(), ChrisPoliTestReturn(), ConstSmartTestFunction(), ug::vrl::TestClass::constSmartTestImpl(), ug::vrl::SmartPtrCls::create_data(), ug::vrl::TestClass::getRev(), ug::vrl::TestClass::getString(), ug::vrl::TestClass::print(), ug::vrl::SmartPtrCls::print_name(), SmartTestFunction(), ug::vrl::TestClass::smartTestImpl(), and TestSmartPtr2ConstPtr().
registerThrowUtil()
void ug::vrl::registerThrowUtil (ug::bridge::Registry & reg)
References ug::bridge::Registry::add_function(), ThrowIf(), and ThrowIfNot().
Referenced by RegisterVRLFunctionality().
registerUGFinalize()
void ug::vrl::registerUGFinalize (ug::bridge::Registry & reg)
References ug::bridge::Registry::add_function(), and ug::UGFinalize().
Referenced by RegisterVRLFunctionality().
RegisterUserData()
template<int dim> void ug::vrl::RegisterUserData (ug::bridge::Registry & reg, const char * parentGroup)
References dim, and ug::bridge::print().
Referenced by RegisterVRLFunctionality().
RegisterUserDataType()
template<typename TData , int dim> void ug::vrl::RegisterUserDataType (ug::bridge::Registry & reg, const std::string & grp)
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), dim, and ug::bridge::print().
RegisterVRLFunctionality()
void ug::vrl::RegisterVRLFunctionality (ug::bridge::Registry & reg, std::string grp)
References ug::vrl::VTest::hello(), registerBasicTest(), registerMessaging(), registerNumberArray(), registerThrowUtil(), registerUGFinalize(), and RegisterUserData().
Referenced by Java_edu_gcsc_vrl_ug_UG__1ugInit().
registry2NativeAPI()
jobject ug::vrl::registry2NativeAPI (JNIEnv * env, ug::bridge::Registry * reg)
Converts registry information to Java objects.
Parameters
env JVM environment to operate on
reg registry to convert
Returns
native api info
References ug::bridge::Registry::check_consistency(), classes2NativeClasses(), classGroups2NativeClassGroups(), ug::LogAssistant::flush_error_log(), functions2NativeGroups(), ug::GetLogAssistant(), and UG_LOG.
Referenced by boolC2J(), and Java_edu_gcsc_vrl_ug_UG__1convertRegistryInfo().
replaceAll()
std::string ug::vrl::replaceAll (std::string target, const std::string oldstr, const std::string newstr)
Replaces each substring of target string that is equal to oldstr with newstr
Parameters
target string to modify
oldstr string to raplace
newstr replacement string
Returns
a copy of the specified target string where all occurences of oldstr are replaced with newstr
Referenced by ug::vrl::MessageBuffer::addMessage().
retVal2NativeParam()
jobject ug::vrl::retVal2NativeParam (JNIEnv * env, const ug::bridge::ExportedFunctionBase & func)
References ug::bridge::ParameterInfo::class_name(), ug::bridge::ParameterInfo::class_name_node(), getBaseClassNames(), ug::bridge::ParameterInfo::is_vector(), ug::bridge::ExportedFunctionBase::params_out(), paramType2Int(), ug::bridge::ExportedFunctionBase::return_info_vec(), ug::bridge::ParameterInfo::size(), stringArrayC2J(), and stringC2J().
Referenced by function2NativeFunction(), and method2NativeMethod().
serrPrintln()
void ug::vrl::serrPrintln (std::string msg)
DO NOT USE THIS METHOD! (totally broken)
Parameters
msg
SetVRLRegistry()
void ug::vrl::SetVRLRegistry (ug::bridge::Registry * pReg)
Defines the registry to use for VRL.
Parameters
pReg registry
Referenced by Java_edu_gcsc_vrl_ug_UG__1ugInit().
sizetVector2JObject()
jobject ug::vrl::sizetVector2JObject (JNIEnv * env, const std::vector< size_t > & iv)
Converts a size_t vector to a Java object (jobject).
Parameters
env JVM environment to operate on
iv vector to convert
Returns
Java object (jobject)
References int2JObject().
Referenced by boolC2J(), and param2JObject().
smartPointer2JObject()
jobject ug::vrl::smartPointer2JObject (JNIEnv * env, SmartPtr< void > value)
Converts a native smart-pointer to a Java object (jobject).
Parameters
env JVM environment to operate on
value smart-pointer to convert
Returns
a Java object (jobject)
References boolC2J(), SmartPtr< void >::get(), and JNULL.
Referenced by boolC2J(), Java_edu_gcsc_vrl_ug_UG__1newInstance(), param2JObject(), and smartPtrVector2JObject().
smartPtrVector2JObject()
jobject ug::vrl::smartPtrVector2JObject (JNIEnv * env, const std::vector< SmartPtr< void > > & pv)
Converts a SmartPtr vector to a Java object (jobject).
Parameters
env JVM environment to operate on
pv vector to convert
Returns
Java object (jobject)
References smartPointer2JObject().
Referenced by boolC2J(), and param2JObject().
SmartTestFunction()
int ug::vrl::SmartTestFunction (SmartPtr< TestClass > test)
References SmartPtr< T, FreePolicy >::refcount(), and UG_LOG.
Referenced by registerPlayground().
soutPrintln()
void ug::vrl::soutPrintln (std::string msg)
DO NOT USE THIS METHOD! (totally broken)
Parameters
msg
split()
std::vector< std::string > ug::vrl::split (const std::string & str, const char delimiter)
Splits string around given delimiter.
Parameters
str string to split
delimiter delimiter
Returns
vector of strings computed by splitting this string around matches of the given delimiter
Referenced by ug::QualityGridGeneration(), ug::MatrixIOMtx::query_matrix_characteristics(), ug::MatrixIOMtx::read_entry(), and svnRevision().
startsWith()
bool ug::vrl::startsWith (std::string str, std::string search)
Checks whether str starts with search.
Parameters
str string
search string to search
Returns
true if str starts with search; false otherwise
stdStringVector2JObject()
jobject ug::vrl::stdStringVector2JObject (JNIEnv * env, const std::vector< std::string > & sv)
Converts a std::string vector to a Java object (jobject).
Parameters
env JVM environment to operate on
sv vector to convert
Returns
Java object (jobject)
References string2JObject().
Referenced by boolC2J(), and param2JObject().
string2JObject()
jobject ug::vrl::string2JObject (JNIEnv * env, const char * value)
Converts a string to a Java object (jobject).
Parameters
env JVM environment to operate on
value value to convert
Returns
a Java object (jobject)
Referenced by boolC2J(), cStringVector2JObject(), param2JObject(), and stdStringVector2JObject().
stringArrayC2J() [1/6]
jobjectArray ug::vrl::stringArrayC2J (JNIEnv * env, const std::string * strings, const size_t array_length)
Referenced by classes2NativeClasses(), classGroups2NativeClassGroups(), params2NativeParams(), retVal2NativeParam(), and stringArrayC2J().
stringArrayC2J() [2/6]
jobjectArray ug::vrl::stringArrayC2J (JNIEnv * env, const char *const * strings, const unsigned int array_length)
stringArrayC2J() [3/6]
jobjectArray ug::vrl::stringArrayC2J (JNIEnv * env, const std::string * strings)
Converts a native string array to a Java object array.
Parameters
env JVM environment to operate on
strings array to convert
Returns
a java object array
stringArrayC2J() [4/6]
jobjectArray ug::vrl::stringArrayC2J (JNIEnv * env, std::vector< std::string > const & strings)
Converts a native string array to a java object array.
Parameters
env JVM environment to operate on
strings array to convert
Returns
a java object array
References createEmptyString(), and stringArrayC2J().
stringArrayC2J() [5/6]
jobjectArray ug::vrl::stringArrayC2J (JNIEnv * env, const std::vector< const char *> * strings)
References createEmptyString(), and stringArrayC2J().
stringArrayC2J() [6/6]
jobjectArray ug::vrl::stringArrayC2J (JNIEnv * env, const std::vector< const char *> strings)
References createEmptyString(), and stringArrayC2J().
stringArrayJ2C()
std::vector< std::string > ug::vrl::stringArrayJ2C (JNIEnv * env, jobjectArray const & array)
Converts a Java string array to a native string array.
Note: this function must not be used to convert large amounts of strings because of inefficient memory handling.
Parameters
env JVM environment to operate on
array array to convert
Returns
a native string array
References stringJ2C().
Referenced by Java_edu_gcsc_vrl_ug_UG__1ugInit().
stringC2J()
jstring ug::vrl::stringC2J (JNIEnv * env, const char * s)
Converts a native string to a Java string.
Parameters
env JVM environment to operate on
s string to convert
Returns
a java string
Referenced by ug::vrl::MessageBuffer::addMessage(), classes2NativeClasses(), classGroups2NativeClassGroups(), ug::vrl::VRLCondUserNumber< dim >::compileCondUserDataString(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::compileUserDataString(), ug::vrl::VRLUserData< TData, dim >::compileUserDataString(), constructor2NativeConstructor(), function2NativeFunction(), Java_edu_gcsc_vrl_ug_UG__1getAuthors(), Java_edu_gcsc_vrl_ug_UG__1getBinaryLicense(), Java_edu_gcsc_vrl_ug_UG__1getCompileDate(), Java_edu_gcsc_vrl_ug_UG__1getDefaultClassNameFromGroup(), Java_edu_gcsc_vrl_ug_UG__1getDescription(), Java_edu_gcsc_vrl_ug_UG__1getSvnRevision(), Java_edu_gcsc_vrl_ug_UG__1getUGVersion(), method2NativeMethod(), params2NativeParams(), and retVal2NativeParam().
stringJ2C()
std::string ug::vrl::stringJ2C (JNIEnv * env, jstring const & s)
Converts a Java string to a native string.
Note: this function must not be used to convert large amounts of strings because of inefficient memory handling.
Parameters
env JVM environment to operate on
s string to convert
Returns
a native string
Referenced by getExceptionMessageString(), Java_edu_gcsc_vrl_ug_UG__1getBinaryLicense(), Java_edu_gcsc_vrl_ug_UG__1getDefaultClassNameFromGroup(), Java_edu_gcsc_vrl_ug_UG__1getExportedClassPtrByName(), Java_edu_gcsc_vrl_ug_UG__1invokeFunction(), Java_edu_gcsc_vrl_ug_UG__1invokeMethod(), jObject2String(), jPointerGetName(), and stringArrayJ2C().
svnRevision()
std::string ug::vrl::svnRevision () inline
Returns the global SVN revision of this build.
Returns
global SVN revision of this build
References split(), and ug::UGSvnRevision().
Referenced by ug::vrl::TestClass::getRev(), and Java_edu_gcsc_vrl_ug_UG__1getSvnRevision().
TestSmartPtr2ConstPtr()
void ug::vrl::TestSmartPtr2ConstPtr (const TestClass * t)
References ug::vrl::TestClass::print2().
Referenced by registerPlayground().
ThrowIf()
void ug::vrl::ThrowIf (bool b, std::string s)
Referenced by registerThrowUtil().
ThrowIfNot()
void ug::vrl::ThrowIfNot (bool b, std::string s)
Referenced by registerThrowUtil().
throwUgErrorAsJavaException() [1/2]
void ug::vrl::throwUgErrorAsJavaException (JNIEnv * env, ug::UGError error)
Converts the specified ug error to its equivalent Java representation and throws it as Java exception.
Parameters
env JVM environment to operate on
error the error to convert/throw
References ug::UGError::get_file(), ug::UGError::get_line(), ug::UGError::get_msg(), and ug::UGError::num_msg().
Referenced by boolC2J(), compareParamTypes(), Java_edu_gcsc_vrl_ug_UG__1invokeFunction(), Java_edu_gcsc_vrl_ug_UG__1invokeMethod(), and Java_edu_gcsc_vrl_ug_UG__1newInstance().
throwUgErrorAsJavaException() [2/2]
void ug::vrl::throwUgErrorAsJavaException (JNIEnv * env, std::string error)
Converts the specified message to its equivalent Java representation and throws it as Java exception.
Parameters
env JVM environment to operate on
error the error to convert/throw
Variable Documentation
javaVM
JavaVM* ug::vrl::javaVM = NULL static
Referenced by getJavaVM().
vrlRegistry
ug::bridge::Registry* ug::vrl::vrlRegistry = NULL static
Referenced by Java_edu_gcsc_vrl_ug_UG__1convertRegistryInfo(), Java_edu_gcsc_vrl_ug_UG__1getDefaultClassNameFromGroup(), Java_edu_gcsc_vrl_ug_UG__1getExportedClassPtrByName(), Java_edu_gcsc_vrl_ug_UG__1invokeFunction(), Java_edu_gcsc_vrl_ug_UG__1invokeMethod(), Java_edu_gcsc_vrl_ug_UG__1newInstance(), and Java_edu_gcsc_vrl_ug_UG__1ugInit().