ug4: ug::bridge::AlgebraCommon Namespace Reference
ug::bridge::AlgebraCommon Namespace Reference
Classes
struct Functionality
class VecScaleAddClass
Functions
template<typename TAlgebra >
void Assign (SmartPtr< typename TAlgebra::vector_type > p, SmartPtr< VecScaleAddClass< TAlgebra > > vsac)
template<typename TAlgebra >
SmartPtr< typename TAlgebra::vector_type > Eval (SmartPtr< VecScaleAddClass< TAlgebra > > vsac)
template<typename TAlgebra >
double VecMaxNorm (SmartPtr< typename TAlgebra::vector_type > v)
template<typename TAlgebra >
double VecNorm (SmartPtr< typename TAlgebra::vector_type > v)
template<typename TAlgebra >
double VecProd2 (SmartPtr< typename TAlgebra::vector_type > v1, SmartPtr< typename TAlgebra::vector_type > v2)
template<typename T >
SmartPtr< T > VecProdOp (SmartPtr< ILinearOperator< T, T > > op, SmartPtr< T > v)
template<typename vector_t >
void VecScaleAdd2 (vector_t &dest, double alpha1, const vector_t &v1, double alpha2, const vector_t &v2)
calculates dest = alpha1*v1 + alpha2*v2
template<typename vector_t >
void VecScaleAdd3 (vector_t &dest, double alpha1, const vector_t &v1, double alpha2, const vector_t &v2, double alpha3, const vector_t &v3)
calculates dest = alpha1*v1 + alpha2*v2 + alpha3*v3
template<typename TAlgebra >
double VecScaleAddNorm (SmartPtr< VecScaleAddClass< TAlgebra > > vsac)
template<typename TAlgebra >
double VecScaleAddProd1 (SmartPtr< typename TAlgebra::vector_type > v1, SmartPtr< VecScaleAddClass< TAlgebra > > vsac)
template<typename TAlgebra >
double VecScaleAddProd2 (SmartPtr< VecScaleAddClass< TAlgebra > > vsac, SmartPtr< typename TAlgebra::vector_type > v1)
Function Documentation
Assign()
template<typename TAlgebra > void ug::bridge::AlgebraCommon::Assign (SmartPtr< typename TAlgebra::vector_type > p, SmartPtr< VecScaleAddClass< TAlgebra > > vsac)
References p.
Eval()
template<typename TAlgebra > SmartPtr<typename TAlgebra::vector_type> ug::bridge::AlgebraCommon::Eval (SmartPtr< VecScaleAddClass< TAlgebra > > vsac)
Referenced by ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleDefect(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleDefect(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleErrorEstimator(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleJacobian(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleJacobian(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleLinear(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleLinear(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleMassMatrix(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleMassMatrix(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleRhs(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::AssembleStiffnessMatrix(), ug::StdGlobAssembler< TDomain, TAlgebra >::AssembleStiffnessMatrix(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::FinishTimestep(), ug::StdGlobAssembler< TDomain, TAlgebra >::FinishTimestep(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::FinishTimestepElem(), ug::StdGlobAssembler< TDomain, TAlgebra >::FinishTimestepElem(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::PrepareTimestep(), ug::StdGlobAssembler< TDomain, TAlgebra >::PrepareTimestep(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::PrepareTimestepElem(), and ug::StdGlobAssembler< TDomain, TAlgebra >::PrepareTimestepElem().
VecMaxNorm()
template<typename TAlgebra > double ug::bridge::AlgebraCommon::VecMaxNorm (SmartPtr< typename TAlgebra::vector_type > v)
VecNorm()
template<typename TAlgebra > double ug::bridge::AlgebraCommon::VecNorm (SmartPtr< typename TAlgebra::vector_type > v)
VecProd2()
template<typename TAlgebra > double ug::bridge::AlgebraCommon::VecProd2 (SmartPtr< typename TAlgebra::vector_type > v1, SmartPtr< typename TAlgebra::vector_type > v2)
VecProdOp()
template<typename T > SmartPtr<T> ug::bridge::AlgebraCommon::VecProdOp (SmartPtr< ILinearOperator< T, T > > op, SmartPtr< T > v)
References ug::PST_CONSISTENT.
VecScaleAdd2()
template<typename vector_t > void ug::bridge::AlgebraCommon::VecScaleAdd2 (vector_t & dest, double alpha1, const vector_t & v1, double alpha2, const vector_t & v2) inline
calculates dest = alpha1*v1 + alpha2*v2
References ug::VecScaleAdd().
VecScaleAdd3()
template<typename vector_t > void ug::bridge::AlgebraCommon::VecScaleAdd3 (vector_t & dest, double alpha1, const vector_t & v1, double alpha2, const vector_t & v2, double alpha3, const vector_t & v3) inline
calculates dest = alpha1*v1 + alpha2*v2 + alpha3*v3
References ug::VecScaleAdd().
VecScaleAddNorm()
template<typename TAlgebra > double ug::bridge::AlgebraCommon::VecScaleAddNorm (SmartPtr< VecScaleAddClass< TAlgebra > > vsac)
VecScaleAddProd1()
template<typename TAlgebra > double ug::bridge::AlgebraCommon::VecScaleAddProd1 (SmartPtr< typename TAlgebra::vector_type > v1, SmartPtr< VecScaleAddClass< TAlgebra > > vsac)
VecScaleAddProd2()
template<typename TAlgebra > double ug::bridge::AlgebraCommon::VecScaleAddProd2 (SmartPtr< VecScaleAddClass< TAlgebra > > vsac, SmartPtr< typename TAlgebra::vector_type > v1)