ug4: scripts/util/raster_util.lua File Reference
raster_util.lua File Reference
Functions
function util raster CreateRasterMatrixCallbackFromDesc (desc, dim)
function util raster CreateRasterNumberData (desc)
function util raster CreateRasterValueCallbackFromDesc (desc, dim)
function func (x, y, z, t, si)
function util raster GetRasterFileDimension (filename)
Function Documentation
CreateRasterMatrixCallbackFromDesc()
function util raster CreateRasterMatrixCallbackFromDesc (desc , dim)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / raster_util.lua :137-158
CreateRasterNumberData()
function util raster CreateRasterNumberData (desc)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / raster_util.lua :36-77
CreateRasterValueCallbackFromDesc()
function util raster CreateRasterValueCallbackFromDesc (desc , dim)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / raster_util.lua :96-117
func()
function func (x , y , z , t , si)
/**
/**
/**
/**
/**
/**
/**
/**
/** location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / raster_util.lua :241-251
      func =  function(x, y, z, t, si)
            raster:set_cursor(0, x);
            raster:set_cursor(1, y);
            raster:set_cursor(2, z);
            return raster:interpolate_at_cursor(interpOrder)
          end
    end
  end
  return func, raster
end
/**
/**
/**
/**
/**
/**
/**
/**
/** location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / raster_util.lua :340-351
      func =  function(x, y, z, t, si)
            raster:set_cursor(0, x);
            raster:set_cursor(1, y);
            raster:set_cursor(2, z);
            local d = raster:interpolate_at_cursor(interpOrder)
            return d, 0, 0, 0, d, 0, 0, 0, d
          end
    end
  end
  return func, raster
end
Referenced by ug::IObstacleConstraint< TDomain, TAlgebra >::add(), ug::DirichletBoundary< TDomain, TAlgebra >::add(), ug::bridge::Registry::add_and_get_function(), ug::bridge::Registry::add_function(), ug::bridge::ExportedClass< TClass >::add_method(), ug::bridge::ExportedMethodGroup::add_overload(), ug::bridge::ExportedFunctionGroup::add_overload(), ug::bridge::FunctionProxy< TFunc, TRet >::apply(), ug::bridge::FunctionProxy< TFunc, void >::apply(), ug::Archivar< TArchive, TBase, TPairSeq >::Archivar(), available_terminals(), ug::DataExport< TData, dim >::eval_and_deriv(), ug::bridge::lua::ExecuteMethod(), ug::Factory< TBase, TPairSeq >::Factory(), ug::vrl::function2NativeFunction(), ug::vrl::functions2NativeGroups(), ug::vrl::invocation::getFunctionBySignature(), Java_edu_gcsc_vrl_ug_UG__1invokeFunction(), ug::bridge::lua::LuaProxyFunction(), ug::vrl::params2NativeParams(), ug::node_tree::Traverser::register_handler_function(), ug::CplUserData< TData, dim, TRet >::register_storage_callback(), ug::IConvectionShapes< dim >::register_update_func(), ug::vrl::retVal2NativeParam(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_add_def_A_elem_fct(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_add_def_A_expl_elem_fct(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_add_def_M_elem_fct(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_add_jac_A_elem_fct(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_add_jac_M_elem_fct(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_add_rhs_elem_fct(), ug::IElemEstimatorFuncs< TLeaf, TDomain >::set_compute_err_est_M_elem(), ug::IElemEstimatorFuncs< TLeaf, TDomain >::set_compute_err_est_rhs_elem(), ug::LSGFDomainDiscretization< TDomain, TAlgebra, TExtrapolation >::set_Dirichlet_on_if_for(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::set_Dirichlet_on_if_for(), ug::DataImport< TData, dim >::set_fct(), ug::DataExport< TData, dim >::set_fct(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_fsh_elem_loop_fct(), ug::IElemEstimatorFuncs< TLeaf, TDomain >::set_fsh_err_est_elem_loop(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_fsh_timestep_elem_fct(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_fsh_timestep_fct(), ug::LSGFDomainDiscretization< TDomain, TAlgebra, TExtrapolation >::set_plain_Dirichlet_on_if_for(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::set_plain_Dirichlet_on_if_for(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_prep_elem_fct(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_prep_elem_loop_fct(), ug::IElemEstimatorFuncs< TLeaf, TDomain >::set_prep_err_est_elem(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_prep_timestep_elem_fct(), ug::IElemAssembleFuncs< TLeaf, TDomain >::set_prep_timestep_fct(), and ug::bridge::WriteLUAObject2().
GetRasterFileDimension()
function util raster GetRasterFileDimension (filename)
location: /home/runner/work/docs/docs/ug4/ugcore/scripts/util / raster_util.lua :353-377