ug4: ugbase/lib_algebra/interface/sparsematrix_interface.h File Reference
sparsematrix_interface.h File Reference
Classes
class SparseMatrix< T >
Typedefs
typedef T value_type
Functions
const_row_iterator begin_row (size_t row) const
template<typename AB_type , typename A_type , typename B_type >
void CreateAsMultiplyOf (AB_type &M, const A_type &A, const B_type &B)
Calculates M = A*B.
template<typename T >
class SparseMatrix CreateAsProductOf (ABC_type &M, const A_type &A, const B_type &B, const C_type &C)
void defragment ()
const_row_iterator end_row (size_t row) const
const_row_iterator get_connection (size_t r, size_t c) const
const_row_iterator get_connection (size_t r, size_t c, bool &bFound) const
template<typename matrix_type >
void MatAdd (matrix_type &M, number &alpha1, const matrix_type &A, number &alpha2, const matrix_type &B)
Calculates M = A + B.
size_t num_cols () const
size_t num_connections (size_t row) const
size_t num_rows () const
value_type & operator() (size_t r, size_t c)
bool resize (size_t newRows, size_t newCols)
SparseMatrix ()
size_t total_num_connections () const
virtual ~SparseMatrix ()
Variables
class SparseMatrix A_type
class SparseMatrix ABC_type
Calculates M = A*B*C.
class SparseMatrix B_type
Typedef Documentation
value_type
typedef T value_type
Function Documentation
begin_row()
row_iterator begin_row (size_t row) const
Referenced by ug::SparseMatrix< TValueType >::apply_transposed_ignore_zero_rows(), ug::MapSparseMatrix< TValueType >::axpy(), ug::MapSparseMatrix< TValueType >::axpy_transposed(), ug::SparseMatrix< TValueType >::is_isolated(), ug::GPUSparseMatrix< TValueType >::is_isolated(), ug::MapSparseMatrix< TValueType >::is_isolated(), ug::GPUSparseMatrix< TValueType >::mat_mult_add_row(), ug::MapSparseMatrix< TValueType >::mat_mult_add_row(), ug::SparseMatrix< TValueType >::printrow(), ug::GPUSparseMatrix< TValueType >::printrow(), ug::MapSparseMatrix< TValueType >::printrow(), ug::SparseMatrix< TValueType >::scale(), ug::GPUSparseMatrix< TValueType >::scale(), ug::MapSparseMatrix< TValueType >::scale(), ug::SparseMatrix< TValueType >::set(), ug::GPUSparseMatrix< TValueType >::set(), and ug::MapSparseMatrix< TValueType >::set().
CreateAsMultiplyOf()
template<typename AB_type , typename A_type , typename B_type > void CreateAsMultiplyOf (AB_type & M, const A_type & A, const B_type & B)
Calculates M = A*B.
Parameters
M (out) Matrix M, M = A*B$
A (in) Matrix A
B (in) Matrix B
CreateAsProductOf()
template<typename T > class SparseMatrix CreateAsProductOf (ABC_type & M, const A_type & A, const B_type & B, const C_type & C)
defragment()
void CreateAsProductOf::defragment ()
Referenced by ug::SparseMatrix< TValueType >::check_fragmentation().
end_row()
row_iterator end_row (size_t row) const
Referenced by ug::SparseMatrix< TValueType >::apply_transposed_ignore_zero_rows(), ug::MapSparseMatrix< TValueType >::axpy(), ug::MapSparseMatrix< TValueType >::axpy_transposed(), ug::SparseMatrix< TValueType >::is_isolated(), ug::GPUSparseMatrix< TValueType >::is_isolated(), ug::MapSparseMatrix< TValueType >::is_isolated(), ug::GPUSparseMatrix< TValueType >::mat_mult_add_row(), ug::MapSparseMatrix< TValueType >::mat_mult_add_row(), ug::SparseMatrix< TValueType >::printrow(), ug::GPUSparseMatrix< TValueType >::printrow(), ug::MapSparseMatrix< TValueType >::printrow(), ug::SparseMatrix< TValueType >::scale(), ug::GPUSparseMatrix< TValueType >::scale(), ug::MapSparseMatrix< TValueType >::scale(), ug::SparseMatrix< TValueType >::set(), ug::GPUSparseMatrix< TValueType >::set(), and ug::MapSparseMatrix< TValueType >::set().
get_connection() [1/2]
row_iterator get_connection (size_t r, size_t c) const
get_connection() [2/2]
row_iterator get_connection (size_t r, size_t c, bool & bFound) const
MatAdd()
template<typename matrix_type > void MatAdd (matrix_type & M, number & alpha1, const matrix_type & A, number & alpha2, const matrix_type & B)
Calculates M = A + B.
Parameters
M (out) Matrix M, M = A + B
A (in) Matrix A
B (in) Matrix B note: A and/or B may be equal to M.
num_cols()
size_t CreateAsProductOf::num_cols () const
Referenced by ug::Jacobi< TAlgebra >::apply(), ug::AssembledLinearOperator< TAlgebra >::apply(), ug::AssembledLinearOperator< TAlgebra >::apply_sub(), ug::GPUSparseMatrix< TValueType >::axpy(), ug::Table< std::string >::num_cols(), ScalarMatrixAdapter< AT, ST >::operator()(), ug::Table< T >::operator()(), ug::DenseMatrix< VariableArray2< LocalCplMatrix > >::operator*(), ug::DenseMatrix< TStorage >::operator*(), ug::DenseMatrix< VariableArray2< LocalCplMatrix > >::operator*=(), ug::DenseMatrix< TStorage >::operator+(), ug::DenseMatrix< TStorage >::operator-(), ug::DenseMatrix< TStorage >::operator-=(), ug::DenseMatrix< VariableArray2< LocalCplMatrix > >::operator-=(), ug::DenseMatrix< TStorage >::operator/=(), ug::DenseMatrix< TStorage >::operator=(), ug::DenseMatrix< TStorage >::operator==(), ug::GPUSparseMatrix< TValueType >::print(), ug::MapSparseMatrix< TValueType >::print(), ug::bridge::RegisterBridge_Util(), ug::SparseMatrix< TValueType >::set_as_transpose_of2(), ug::Table< T >::stream(), ug::DenseMatrix< TStorage >::subassign(), ug::DenseMatrix< TStorage >::T(), ug::Table< T >::to_csv(), and ug::Table< T >::to_latex().
num_connections()
size_t CreateAsProductOf::num_connections (size_t row) const inline
Referenced by ug::DeserializeMatrix(), ug::DeserializeRow(), ug::RowSendingScheme< matrix_type >::issue_send(), ug::RowSendingScheme< matrix_type >::process(), ug::ReceiveMatrix(), ug::SerializeMatrix(), and ug::SerializeRow().
num_rows()
size_t CreateAsProductOf::num_rows () const
Referenced by ug::Jacobi< TAlgebra >::apply(), ug::AssembledLinearOperator< TAlgebra >::apply(), ug::SparseMatrix< TValueType >::apply_ignore_zero_rows(), ug::AssembledLinearOperator< TAlgebra >::apply_sub(), ug::SparseMatrix< TValueType >::apply_transposed_ignore_zero_rows(), ug::GPUSparseMatrix< TValueType >::axpy(), ug::SparseMatrix< TValueType >::axpy(), ug::MapSparseMatrix< TValueType >::axpy(), ug::SparseMatrix< TValueType >::axpy_transposed(), ug::MapSparseMatrix< TValueType >::axpy_transposed(), ug::BlockGaussSeidel< TAlgebra, backward, forward >::block_preprocess(), ug::SparseBlockGaussSeidel< TAlgebra, backward, forward >::block_preprocess(), ug::SparseBlockGaussSeidel2< TAlgebra, backward, forward >::block_preprocess(), ug::GPUSparseMatrix< TValueType >::copyToNewSize(), ug::SparseMatrix< TValueType >::get_nnz_max_cols(), ug::GPUSparseMatrix< TValueType >::get_nnz_max_cols(), ug::SparseMatrix< TValueType >::is_isolated(), ug::GPUSparseMatrix< TValueType >::is_isolated(), ug::MapSparseMatrix< TValueType >::is_isolated(), ug::Table< std::string >::num_cols(), ScalarMatrixAdapter< AT, ST >::operator()(), ug::Table< T >::operator()(), ug::DenseMatrix< VariableArray2< LocalCplMatrix > >::operator*(), ug::DenseMatrix< TStorage >::operator*(), ug::DenseMatrix< VariableArray2< LocalCplMatrix > >::operator*=(), ug::DenseMatrix< TStorage >::operator+(), ug::DenseMatrix< TStorage >::operator-(), ug::DenseMatrix< VariableArray2< LocalCplMatrix > >::operator-=(), ug::DenseMatrix< TStorage >::operator-=(), ug::DenseMatrix< TStorage >::operator/=(), ug::DenseMatrix< TStorage >::operator=(), ug::DenseMatrix< TStorage >::operator==(), ug::PILUTPreconditioner< TAlgebra >::preprocess(), ug::GPUSparseMatrix< TValueType >::print(), ug::MapSparseMatrix< TValueType >::print(), ug::bridge::RegisterBridge_Util(), ug::GPUSparseMatrix< TValueType >::resize_and_keep_values(), ug::SparseMatrix< TValueType >::scale(), ug::GPUSparseMatrix< TValueType >::scale(), ug::MapSparseMatrix< TValueType >::scale(), ug::SparseMatrix< TValueType >::set(), ug::GPUSparseMatrix< TValueType >::set(), ug::MapSparseMatrix< TValueType >::set(), ug::SparseMatrix< TValueType >::set_as_transpose_of2(), ug::Table< T >::stream(), ug::DenseMatrix< TStorage >::subassign(), ug::DenseMatrix< TStorage >::T(), ug::Table< T >::to_csv(), and ug::Table< T >::to_latex().
operator()()
const value_type & operator() (size_t r, size_t c)
operator() (size_t r, size_t c) const access connection (r, c)
Parameters
r row
c column
Note
it is assert'ed that connection (r,c) is there use operator()(r,c,bConnectionFound) to check.
Returns
SparseMat(r, c)
operator() (size_t r, size_t c) const access or create connection (r, c)
Parameters
r row
c column
Note
(r,c) is added to sparsity pattern if not already there use operator()(r,c,bConnectionFound) to prevent
Returns
SparseMat(r, c)=0.0 if connection created, otherwise SparseMat(r, c)
Referenced by ug::DenseMatrix< TStorage >::entry(), ug::GPUSparseMatrix< TValueType >::set_as_copy_of(), ug::MapSparseMatrix< TValueType >::set_as_copy_of(), ug::SparseMatrix< TValueType >::set_as_copy_of(), ug::GPUSparseMatrix< TValueType >::set_as_transpose_of(), ug::MapSparseMatrix< TValueType >::set_as_transpose_of(), and ug::TestHorizontalAlgebraLayouts().
resize()
bool CreateAsProductOf::resize (size_t newRows, size_t newCols)
Referenced by ug::GMRES< TVector >::apply_return_defect(), ug::BinaryStreamBuffer::clear(), ug::PageContainer< T, MAX_PAGE_SIZE, Allocator >::clear(), ug::DoFCount::DoFCount(), ug::RasterLayers::load_from_files(), ug::DenseVector< TStorage >::operator=(), ug::DenseMatrix< VariableArray2< LocalCplMatrix > >::operator=(), ug::Vector< TValueType >::operator=(), ug::ReservableArray2< T, T_ordering >::ReservableArray2(), ug::DataImport< TData, dim >::resize_defect_array(), ug::DependentUserData< TData, dim >::resize_deriv_array(), ug::MapSparseMatrix< TValueType >::set_as_copy_of(), ug::MapSparseMatrix< TValueType >::set_as_transpose_of(), ug::VariableArray1< T >::VariableArray1(), and ug::VariableArray2< T, T_ordering >::VariableArray2().
SparseMatrix()
CreateAsProductOf::SparseMatrix ()
total_num_connections()
size_t CreateAsProductOf::total_num_connections () const
~SparseMatrix()
virtual CreateAsProductOf::~SparseMatrix () virtual
Variable Documentation
A_type
class SparseMatrix A_type
ABC_type
class SparseMatrix ABC_type
Calculates M = A*B*C.
Parameters
M (out) Matrix M, M = A*B*C$
A (in) Matrix A
B (in) Matrix B
C (in) Matrix C
B_type
class SparseMatrix B_type