ug4: ug::bridge::GridFunction::Functionality Struct Reference
ug::bridge::GridFunction::Functionality Struct Reference
ugbase » Bridge » Discretization Bridge » Grid Function Bridge
Static Public Member Functions
template<typename TAlgebra >
static void Algebra (Registry &reg, string grp)
static void Common (Registry &reg, string grp)
template<int dim>
static void Dimension (Registry &reg, string grp)
template<typename TDomain >
static void Domain (Registry &reg, string grp)
template<typename TDomain , typename TAlgebra >
static void DomainAlgebra (Registry &reg, string grp)
Detailed Description
Class exporting the functionality. All functionality that is to be used in scripts or visualization must be registered here.
Member Function Documentation
Algebra()
template<typename TAlgebra > static void ug::bridge::GridFunction::Functionality::Algebra (Registry & reg, string grp) inline static
Function called for the registration of Algebra dependent parts. All Functions and Classes depending on Algebra are to be placed here when registering. The method is called for all available Algebra types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
Common()
static void ug::bridge::GridFunction::Functionality::Common (Registry & reg, string grp) inline static
Function called for the registration of Domain and Algebra independent parts. All Functions and Classes not depending on Domain and Algebra are to be placed here when registering.
Parameters
reg registry
parentGroup group for sorting of functionality
References ug::bridge::Registry::add_class_(), dim, and name.
Dimension()
template<int dim> static void ug::bridge::GridFunction::Functionality::Dimension (Registry & reg, string grp) inline static
Function called for the registration of Dimension dependent parts. All Functions and Classes depending on the Dimension are to be placed here when registering. The method is called for all available Dimension types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
Domain()
template<typename TDomain > static void ug::bridge::GridFunction::Functionality::Domain (Registry & reg, string grp) inline static
Function called for the registration of Domain dependent parts. All Functions and Classes depending on the Domain are to be placed here when registering. The method is called for all available Domain types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), and name.
DomainAlgebra()
template<typename TDomain , typename TAlgebra > static void ug::bridge::GridFunction::Functionality::DomainAlgebra (Registry & reg, string grp) inline static
Function called for the registration of Domain and Algebra dependent parts. All Functions and Classes depending on both Domain and Algebra are to be placed here when registering. The method is called for all available Domain and Algebra types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), ug::bridge::Registry::add_function(), dim, ug::EDGE, and name.
The documentation for this struct was generated from the following file:
ugbase/bridge/disc_bridges/grid_function_bridge.cpp