ug4: ug::fv1_traits_ReferenceFace2d Struct Reference
ug::fv1_traits_ReferenceFace2d Struct Reference
#include <fv_util.h>
Static Public Member Functions
static void NormalOnBF (MathVector< 2 > &outNormal, const MathVector< 2 > *vSCVFCorner, const MathVector< 2 > *vElemCorner)
static void NormalOnSCVF (MathVector< 2 > &outNormal, const MathVector< 2 > *vSCVFCorner, const MathVector< 2 > *vElemCorner)
Additional Inherited Members
Public Types inherited from ug::fv1_traits_ReferenceFace
typedef ReferenceEdge bf_type
typedef ReferenceQuadrilateral scv_type
typedef ReferenceEdge scvf_type
Static Public Attributes inherited from ug::fv1_traits_ReferenceFace
static const size_t maxNSH = maxNumSCV
static const size_t maxNumSCV = 4
static const size_t maxNumSCVF = 4
static const size_t NumCornersOfBF = 2
static const size_t NumCornersOfSCV = 4
static const size_t NumCornersOfSCVF = 2
Member Function Documentation
NormalOnBF()
static void ug::fv1_traits_ReferenceFace2d::NormalOnBF (MathVector< 2 > & outNormal, const MathVector< 2 > * vSCVFCorner, const MathVector< 2 > * vElemCorner) inline static
References NormalOnSCVF().
NormalOnSCVF()
static void ug::fv1_traits_ReferenceFace2d::NormalOnSCVF (MathVector< 2 > & outNormal, const MathVector< 2 > * vSCVFCorner, const MathVector< 2 > * vElemCorner) inline static
References ug::ElementNormal< ReferenceEdge, 2 >().
Referenced by NormalOnBF().
The documentation for this struct was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv_util.h