ug4: ug::IElementMarkingStrategy< TDomain > Struct Template Reference
ug::IElementMarkingStrategy< TDomain > Struct Template Reference abstract
Abstract base class for element marking (in adaptive refinement)
#include <error_elem_marking_strategy.h>
Public Types
typedef MultiGrid::AttachmentAccessor< elem_type, ug::Attachment< number > > elem_accessor_type
typedef domain_traits< dim >::element_type elem_type
element type to be marked
Public Member Functions
virtual void mark (elem_accessor_type &aaError, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd)=0
virtual ~IElementMarkingStrategy ()
Static Public Attributes
static const int dim = TDomain::dim
world dimension
Detailed Description
template<typename TDomain>
struct ug::IElementMarkingStrategy< TDomain >
Abstract base class for element marking (in adaptive refinement)
Member Typedef Documentation
template<typename TDomain > typedef MultiGrid::AttachmentAccessor<elem_type, ug::Attachment<number> > ug::IElementMarkingStrategy< TDomain >::elem_accessor_type
template<typename TDomain > typedef domain_traits<dim>::element_type ug::IElementMarkingStrategy< TDomain >::elem_type
element type to be marked
Constructor & Destructor Documentation
template<typename TDomain > virtual ug::IElementMarkingStrategy< TDomain >::~IElementMarkingStrategy () inline virtual
References ug::IElementMarkingStrategy< TDomain >::mark().
Member Function Documentation
template<typename TDomain > virtual void ug::IElementMarkingStrategy< TDomain >::mark (elem_accessor_type & aaError, IRefiner & refiner, ConstSmartPtr< DoFDistribution > dd) pure virtual
Implemented in ug::AbsoluteMarking< TDomain >, ug::EquilibrationMarkingStrategy< TDomain >, ug::MeanValueMarking< TDomain >, ug::VarianceMarkingEta< TDomain >, ug::VarianceMarking< TDomain >, ug::MaximumMarking< TDomain >, and ug::StdMarkingStrategy< TDomain >.
Referenced by ug::AbsoluteMarking< TDomain >::AbsoluteMarking(), ug::EquilibrationMarkingStrategy< TDomain >::EquilibrationMarkingStrategy(), ug::MaximumMarking< TDomain >::MaximumMarking(), ug::MeanValueMarking< TDomain >::MeanValueMarking(), ug::StdMarkingStrategy< TDomain >::StdMarkingStrategy(), ug::VarianceMarking< TDomain >::VarianceMarking(), ug::VarianceMarkingEta< TDomain >::VarianceMarkingEta(), and ug::IElementMarkingStrategy< TDomain >::~IElementMarkingStrategy().
Member Data Documentation
template<typename TDomain > const int ug::IElementMarkingStrategy< TDomain >::dim = TDomain::dim static
world dimension
The documentation for this struct was generated from the following file:
ugbase/lib_disc/function_spaces/error_elem_marking_strategy.h