ug4: ug::bridge::lua::UserDataWrapper Struct Reference
ug::bridge::lua::UserDataWrapper Struct Reference
#include <bindings_lua.h>
Public Member Functions
bool is_const ()
bool is_raw_ptr ()
bool is_smart_ptr ()
Public Attributes
byte type
Member Function Documentation
is_const()
bool ug::bridge::lua::UserDataWrapper::is_const () inline
References ug::bridge::lua::IS_CONST, and type.
Referenced by ug::bridge::lua::LuaParsing< const void * >::checkAndGet(), ug::bridge::lua::LuaParsing< SmartPtr< void > >::checkAndGet(), and ug::bridge::lua::LuaParsing< void * >::checkAndGet().
is_raw_ptr()
bool ug::bridge::lua::UserDataWrapper::is_raw_ptr () inline
References ug::bridge::lua::RAW_POINTER, and type.
Referenced by ug::bridge::lua::LuaParsing< const void * >::checkAndGet(), and ug::bridge::lua::LuaParsing< void * >::checkAndGet().
is_smart_ptr()
bool ug::bridge::lua::UserDataWrapper::is_smart_ptr () inline
References ug::bridge::lua::SMART_POINTER, and type.
Referenced by ug::bridge::lua::LuaParsing< const void * >::checkAndGet(), ug::bridge::lua::LuaParsing< ConstSmartPtr< void > >::checkAndGet(), ug::bridge::lua::LuaParsing< SmartPtr< void > >::checkAndGet(), and ug::bridge::lua::LuaParsing< void * >::checkAndGet().
Member Data Documentation
type
byte ug::bridge::lua::UserDataWrapper::type
Referenced by ug::bridge::lua::CreateNewUserData(), is_const(), is_raw_ptr(), and is_smart_ptr().
The documentation for this struct was generated from the following file:
ugbase/bindings/lua/bindings_lua.h