ug4: ug::bridge::ParameterInfo::PushType< ConstSmartPtr< TClass > > Struct Template Reference
ug::bridge::ParameterInfo::PushType< ConstSmartPtr< TClass > > Struct Template Reference
ugbase » Bridge » Registry
#include <parameter_stack.h>
Static Public Member Functions
static void push (ParameterInfo *This)
Member Function Documentation
push()
template<typename TClass > static void ug::bridge::ParameterInfo::PushType< ConstSmartPtr< TClass > >::push (ParameterInfo * This) inline static
References ug::bridge::ParameterInfo::_push_type(), and push().
Referenced by push().
The documentation for this struct was generated from the following file:
ugbase/registry/parameter_stack.h