ug4: ug::ElementSideRayIntersectionWrapper< TRefElem, 3, 3 > Struct Template Reference
ug::ElementSideRayIntersectionWrapper< TRefElem, 3, 3 > Struct Template Reference
#include <geometry_util.h>
Static Public Member Functions
static bool apply (size_t &sideOut, MathVector< 3 > &GlobalIntersectionPointOut, MathVector< TRefElem::dim > &LocalIntersectionPoint, const MathVector< 3 > &From, const MathVector< 3 > &Direction, bool bPositiv, const MathVector< 3 > *vCornerCoords)
Member Function Documentation
template<typename TRefElem > static bool ug::ElementSideRayIntersectionWrapper< TRefElem, 3, 3 >::apply (size_t & sideOut, MathVector< 3 > & GlobalIntersectionPointOut, MathVector< TRefElem::dim > & LocalIntersectionPoint, const MathVector< 3 > & From, const MathVector< 3 > & Direction, bool bPositiv, const MathVector< 3 > * vCornerCoords) inline static
References dim, ug::Provider< TClass >::get(), ug::RayTriangleIntersection(), UG_THROW, and ug::VecScaleAdd().
The documentation for this struct was generated from the following file:
ugbase/lib_disc/common/geometry_util.h