ug4: ug::AlgebraID Struct Reference
ug::AlgebraID Struct Reference
this type is used to identify distributed objects.
#include <algebra_id.h>
Public Member Functions
AlgebraID ()
AlgebraID (int _masterProc, size_t _indexOnMaster)
size_t index_on_master () const
bool is_master () const
bool is_slave () const
int master_proc () const
Detailed Description
this type is used to identify distributed objects.
Constructor & Destructor Documentation
AlgebraID() [1/2]
ug::AlgebraID::AlgebraID () inline
AlgebraID() [2/2]
ug::AlgebraID::AlgebraID (int _masterProc, size_t _indexOnMaster) inline
Member Function Documentation
index_on_master()
size_t ug::AlgebraID::index_on_master () const inline
Referenced by ug::hash_key< AlgebraID >(), ug::NewLayoutCreator::process(), and ug::ParallelNodes::process().
is_master()
bool ug::AlgebraID::is_master () const inline
References master_proc(), and pcl::ProcRank().
is_slave()
bool ug::AlgebraID::is_slave () const inline
References master_proc(), and pcl::ProcRank().
master_proc()
int ug::AlgebraID::master_proc () const inline
Referenced by ug::NewLayoutCreator::create_node(), ug::ParallelNodes::create_node(), ug::NewLayoutCreator::create_slave_node(), ug::ParallelNodes::create_slave_node(), ug::hash_key< AlgebraID >(), is_master(), is_slave(), ug::NewLayoutCreator::process(), ug::ParallelNodes::process(), ug::ReceiveMatrix(), and ug::SerializeRow().
The documentation for this struct was generated from the following file:
ugbase/lib_algebra/parallelization/algebra_id.h