ug4: ug::fv1_traits_ReferenceFace3d Struct Reference
ug::fv1_traits_ReferenceFace3d Struct Reference
#include <fv_util.h>
Static Public Member Functions
static void NormalOnBF (MathVector< 3 > &outNormal, const MathVector< 3 > *vSCVFCorner, const MathVector< 3 > *vElemCorner)
static void NormalOnSCVF (MathVector< 3 > &outNormal, const MathVector< 3 > *vSCVFCorner, const MathVector< 3 > *vElemCorner)
template<typename TElem >
static void NormalOnSCVF_Face (MathVector< 3 > &outNormal, const MathVector< 3 > *vSCVFCorner, const MathVector< 3 > *vElemCorner)
Additional Inherited Members
Public Types inherited from ug::fv1_traits_ReferenceFace
typedef ReferenceEdge bf_type
typedef ReferenceQuadrilateral scv_type
typedef ReferenceEdge scvf_type
Static Public Attributes inherited from ug::fv1_traits_ReferenceFace
static const size_t maxNSH = maxNumSCV
static const size_t maxNumSCV = 4
static const size_t maxNumSCVF = 4
static const size_t NumCornersOfBF = 2
static const size_t NumCornersOfSCV = 4
static const size_t NumCornersOfSCVF = 2
Member Function Documentation
NormalOnBF()
static void ug::fv1_traits_ReferenceFace3d::NormalOnBF (MathVector< 3 > & outNormal, const MathVector< 3 > * vSCVFCorner, const MathVector< 3 > * vElemCorner) inline static
References UG_THROW.
NormalOnSCVF()
static void ug::fv1_traits_ReferenceFace3d::NormalOnSCVF (MathVector< 3 > & outNormal, const MathVector< 3 > * vSCVFCorner, const MathVector< 3 > * vElemCorner) inline static
References UG_THROW.
NormalOnSCVF_Face()
template<typename TElem > static void ug::fv1_traits_ReferenceFace3d::NormalOnSCVF_Face (MathVector< 3 > & outNormal, const MathVector< 3 > * vSCVFCorner, const MathVector< 3 > * vElemCorner) inline static
References ug::ElementNormal< ReferenceTriangle, 3 >(), p, ug::VecAdd(), ug::VecDistance(), ug::VecNormalize(), and ug::VecScale().
The documentation for this struct was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv_util.h