ug4: ug::fv1_dim_traits_base< TDim, TWorldDim > Struct Template Reference
ug::fv1_dim_traits_base< TDim, TWorldDim > Struct Template Reference
Base for the Traits for Finite Volumes for a generic element of the fixed dimensionalities.
#include <fv_util.h>
Public Types
typedef DimReferenceElement< dim > ref_elem_type
generic reference element type
Static Public Member Functions
static void dim_get_num_SCV_and_SCVF (const ref_elem_type &refElem, ReferenceObjectID roid, size_t &numSCV, size_t &numSCVF)
returns the number of the SCV
static size_t dim_scv_node_id (const ref_elem_type &refElem, ReferenceObjectID roid, size_t i)
returns the node id for a scv
static void get_dim_scvf_from_to (const ref_elem_type &refElem, ReferenceObjectID roid, size_t i, size_t &From, size_t &To)
returns the 'from' and 'to' corner indices for a scvf
Static Public Attributes
static const int dim = TDim
dimension of reference element
Detailed Description
template<int TDim, int TWorldDim>
struct ug::fv1_dim_traits_base< TDim, TWorldDim >
Base for the Traits for Finite Volumes for a generic element of the fixed dimensionalities.
Member Typedef Documentation
ref_elem_type
template<int TDim, int TWorldDim> typedef DimReferenceElement<dim> ug::fv1_dim_traits_base< TDim, TWorldDim >::ref_elem_type
generic reference element type
Member Function Documentation
dim_get_num_SCV_and_SCVF()
template<int TDim, int TWorldDim> static void ug::fv1_dim_traits_base< TDim, TWorldDim >::dim_get_num_SCV_and_SCVF (const ref_elem_type & refElem, ReferenceObjectID roid, size_t & numSCV, size_t & numSCVF) inline static
returns the number of the SCV
Parameters
refElem reference element object
roid reference element object id
numSCV to write the number of the SCVs
numSCVF to write the number of the SCVFs
References ug::fv1_dim_traits_base< TDim, TWorldDim >::dim, ug::ReferenceElement::num(), ug::ROID_OCTAHEDRON, ug::ROID_PYRAMID, UG_THROW, and UG_WARNING.
dim_scv_node_id()
template<int TDim, int TWorldDim> static size_t ug::fv1_dim_traits_base< TDim, TWorldDim >::dim_scv_node_id (const ref_elem_type & refElem, ReferenceObjectID roid, size_t i) inline static
returns the node id for a scv
Parameters
refElem reference element object
roid reference element object id
i index of the scv
References ug::fv1_dim_traits_base< TDim, TWorldDim >::dim, ug::ROID_OCTAHEDRON, ug::ROID_PYRAMID, ug::fv1_traits_ReferenceOctahedron::scv_node_id(), ug::fv1_traits_ReferencePyramid::scv_node_id(), and UG_THROW.
get_dim_scvf_from_to()
template<int TDim, int TWorldDim> static void ug::fv1_dim_traits_base< TDim, TWorldDim >::get_dim_scvf_from_to (const ref_elem_type & refElem, ReferenceObjectID roid, size_t i, size_t & From, size_t & To) inline static
returns the 'from' and 'to' corner indices for a scvf
Parameters
refElem reference element object
roid reference element object id
i index of the scvf
From to write the from-index
To to write the to-index
References ug::fv1_dim_traits_base< TDim, TWorldDim >::dim, ug::ReferenceElement::id(), ug::ROID_OCTAHEDRON, ug::ROID_PYRAMID, ug::fv1_traits_ReferenceOctahedron::scvf_from_to(), ug::fv1_traits_ReferencePyramid::scvf_from_to(), and UG_THROW.
Member Data Documentation
dim
template<int TDim, int TWorldDim> const int ug::fv1_dim_traits_base< TDim, TWorldDim >::dim = TDim static
dimension of reference element
Referenced by ug::fv1_dim_traits_base< TDim, TWorldDim >::dim_get_num_SCV_and_SCVF(), ug::fv1_dim_traits_base< TDim, TWorldDim >::dim_scv_node_id(), and ug::fv1_dim_traits_base< TDim, TWorldDim >::get_dim_scvf_from_to().
The documentation for this struct was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv_util.h