ug4: ug::DoFCount::Cnt::PCnt Struct Reference
ug::DoFCount::Cnt::PCnt Struct Reference
#include <dof_count.h>
Public Member Functions
void collect_values (std::vector< uint64 > &vNum) const
uint64 num (byte is) const
uint64 num_contains (byte is) const
PCnt ()
void set_values (const std::vector< uint64 > &vNum, size_t &cnt)
Public Attributes
std::vector< uint64 > vNumIS
Constructor & Destructor Documentation
ug::DoFCount::Cnt::PCnt::PCnt ()
References ug::DoFCount::ES_MAX.
Member Function Documentation
void ug::DoFCount::Cnt::PCnt::collect_values (std::vector< uint64 > & vNum) const
References ug::ES_H_MASTER, ug::ES_H_SLAVE, ug::DoFCount::ES_MAX, and PROFILE_FUNC.
Referenced by ug::DoFCount::DoFCount().
uint64 ug::DoFCount::Cnt::PCnt::num (byte is) const
References ug::DoFCount::ALL_ES, ug::ES_H_MASTER, ug::DoFCount::ES_MAX, ug::ES_NONE, ug::ES_V_MASTER, ug::ES_V_SLAVE, ug::DoFCount::num(), ug::DoFCount::num_contains(), and ug::DoFCount::UNIQUE_ES.
Referenced by ug::DoFCount::grid_level().
uint64 ug::DoFCount::Cnt::PCnt::num_contains (byte is) const
References ug::DoFCount::ALL_ES, ug::ES_H_MASTER, ug::DoFCount::ES_MAX, ug::ES_NONE, ug::ES_V_MASTER, ug::ES_V_SLAVE, ug::DoFCount::num(), ug::DoFCount::num_contains(), and ug::DoFCount::UNIQUE_ES.
Referenced by ug::DoFCount::grid_level().
void ug::DoFCount::Cnt::PCnt::set_values (const std::vector< uint64 > & vNum, size_t & cnt)
References ug::ES_H_MASTER, ug::ES_H_SLAVE, ug::DoFCount::ES_MAX, and PROFILE_FUNC.
Referenced by ug::DoFCount::DoFCount().
Member Data Documentation
std::vector<uint64> ug::DoFCount::Cnt::PCnt::vNumIS
The documentation for this struct was generated from the following files:
ugbase/lib_disc/dof_manager/dof_count.h
ugbase/lib_disc/dof_manager/dof_count.cpp