ug4: ug::SweepLineEdge Struct Reference
ug::SweepLineEdge Struct Reference
Public Member Functions
bool contains (const SweepLineVertex *v)
vector2 direction () const
SweepLineVertex * get_connected (const SweepLineVertex *v) const
SweepLineEdge (SweepLineVertex *v1, SweepLineVertex *v2)
Public Attributes
SweepLineVertex * m_helper
int m_numConnectedPolygons
unsigned char m_status
SweepLineVertex * m_v1
SweepLineVertex * m_v2
Detailed Description
Please note that edges do not automatically register them selves at their vertices connections array. This would make problems with temporary edge objects and copy-construction.
Constructor & Destructor Documentation
SweepLineEdge()
ug::SweepLineEdge::SweepLineEdge (SweepLineVertex * v1, SweepLineVertex * v2) inline
Member Function Documentation
contains()
bool ug::SweepLineEdge::contains (const SweepLineVertex * v) inline
direction()
vector2 ug::SweepLineEdge::direction () const inline
Referenced by ug::CalculateRightBendVal(), ug::GetEdgeOnTheLeft(), ug::SweepLine_CreateMonotones(), and ug::SweepLineEdgeIntersectsSweepLine().
get_connected()
SweepLineVertex* ug::SweepLineEdge::get_connected (const SweepLineVertex * v) const inline
Referenced by ug::CreateSweepLineStructs(), ug::SweepLine_CreateMonotones(), and ug::TriangleFill_SweepLine().
Member Data Documentation
m_helper
SweepLineVertex* ug::SweepLineEdge::m_helper
Referenced by ug::SweepLine_CreateMonotones().
m_numConnectedPolygons
int ug::SweepLineEdge::m_numConnectedPolygons
Referenced by ug::TriangleFill_SweepLine().
m_status
unsigned char ug::SweepLineEdge::m_status
Referenced by ug::CreateSweepLineStructs(), ug::SweepLine_CreateMonotones(), and ug::TriangleFill_SweepLine().
m_v1
SweepLineVertex* ug::SweepLineEdge::m_v1
Referenced by ug::CalculateRightBendVal(), ug::CreateSweepLineStructs(), ug::SweepLine_CreateMonotones(), ug::SweepLineEdgeIntersectsSweepLine(), and ug::TriangleFill_SweepLine().
m_v2
SweepLineVertex* ug::SweepLineEdge::m_v2
Referenced by ug::CreateSweepLineStructs(), ug::SweepLineEdgeIntersectsSweepLine(), and ug::TriangleFill_SweepLine().
The documentation for this struct was generated from the following file:
ugbase/lib_grid/algorithms/grid_generation/triangle_fill_sweep_line.cpp