ug4: ug::MGFaceInfo Struct Reference
ug::MGFaceInfo Struct Reference
Holds information about face relations. Used internally.
#include <multi_grid_child_info.h>
Public Member Functions
void add_child (Edge *elem)
void add_child (Face *elem)
void add_child (Vertex *elem)
void add_child (Volume *)
Edge * child_edge (size_t i) const
Face * child_face (size_t i) const
Vertex * child_vertex () const
void clear_children ()
bool has_children () const
MGFaceInfo ()
size_t num_child_edges () const
size_t num_child_faces () const
size_t num_child_vertices () const
void remove_child (Edge *elem)
void remove_child (Face *elem)
void remove_child (Vertex *elem)
void remove_child (Volume *)
void replace_child (Edge *elem, Edge *child)
void replace_child (Face *elem, Face *child)
void replace_child (Vertex *elem, Vertex *child)
void unregister_from_children (MultiGrid &mg)
Private Attributes
byte m_numEdgeChildren
byte m_numFaceChildren
Edge * m_pEdgeChild [MG_FACE_MAX_EDGE_CHILDREN]
Face * m_pFaceChild [MG_FACE_MAX_FACE_CHILDREN]
Vertex * m_pVrtChild
Detailed Description
Holds information about face relations. Used internally.
No parent included, since MGFaceInfos are not stored for surface elements.
Constructor & Destructor Documentation
MGFaceInfo()
ug::MGFaceInfo::MGFaceInfo () inline
Member Function Documentation
add_child() [1/4]
void ug::MGFaceInfo::add_child (Edge * elem) inline
References m_numEdgeChildren, m_pEdgeChild, and ug::MG_FACE_MAX_EDGE_CHILDREN.
add_child() [2/4]
void ug::MGFaceInfo::add_child (Face * elem) inline
References m_numFaceChildren, m_pFaceChild, and ug::MG_FACE_MAX_FACE_CHILDREN.
add_child() [3/4]
void ug::MGFaceInfo::add_child (Vertex * elem) inline
References m_pVrtChild.
Referenced by ug::MultiGrid::face_created().
add_child() [4/4]
void ug::MGFaceInfo::add_child (Volume *) inline
References UG_THROW.
child_edge()
Edge* ug::MGFaceInfo::child_edge (size_t i) const inline
References m_pEdgeChild, and num_child_edges().
Referenced by ug::MultiGrid::face_created().
child_face()
Face* ug::MGFaceInfo::child_face (size_t i) const inline
References m_pFaceChild, and num_child_faces().
Referenced by ug::MultiGrid::face_created().
child_vertex()
Vertex* ug::MGFaceInfo::child_vertex () const inline
References m_pVrtChild.
Referenced by ug::MultiGrid::face_created().
clear_children()
void ug::MGFaceInfo::clear_children () inline
References m_numEdgeChildren, m_numFaceChildren, and m_pVrtChild.
Referenced by unregister_from_children().
has_children()
bool ug::MGFaceInfo::has_children () const inline
References m_numEdgeChildren, m_numFaceChildren, and m_pVrtChild.
num_child_edges()
size_t ug::MGFaceInfo::num_child_edges () const inline
References m_numEdgeChildren.
Referenced by child_edge(), and ug::MultiGrid::face_created().
num_child_faces()
size_t ug::MGFaceInfo::num_child_faces () const inline
References m_numFaceChildren.
Referenced by child_face(), and ug::MultiGrid::face_created().
num_child_vertices()
size_t ug::MGFaceInfo::num_child_vertices () const inline
References m_pVrtChild.
remove_child() [1/4]
void ug::MGFaceInfo::remove_child (Edge * elem) inline
References ug::ArrayEraseEntry(), m_numEdgeChildren, and m_pEdgeChild.
remove_child() [2/4]
void ug::MGFaceInfo::remove_child (Face * elem) inline
References ug::ArrayEraseEntry(), m_numFaceChildren, and m_pFaceChild.
remove_child() [3/4]
void ug::MGFaceInfo::remove_child (Vertex * elem) inline
References m_pVrtChild.
remove_child() [4/4]
void ug::MGFaceInfo::remove_child (Volume *) inline
References UG_THROW.
replace_child() [1/3]
void ug::MGFaceInfo::replace_child (Edge * elem, Edge * child) inline
References ug::ArrayReplaceEntry(), m_numEdgeChildren, and m_pEdgeChild.
replace_child() [2/3]
void ug::MGFaceInfo::replace_child (Face * elem, Face * child) inline
References ug::ArrayReplaceEntry(), m_numFaceChildren, and m_pFaceChild.
replace_child() [3/3]
void ug::MGFaceInfo::replace_child (Vertex * elem, Vertex * child) inline
References m_pVrtChild.
unregister_from_children()
void ug::MGFaceInfo::unregister_from_children (MultiGrid & mg)
References clear_children(), m_numEdgeChildren, m_numFaceChildren, m_pEdgeChild, m_pFaceChild, m_pVrtChild, and ug::MultiGrid::set_parent().
Member Data Documentation
m_numEdgeChildren
byte ug::MGFaceInfo::m_numEdgeChildren private
Referenced by add_child(), clear_children(), has_children(), num_child_edges(), remove_child(), replace_child(), and unregister_from_children().
m_numFaceChildren
byte ug::MGFaceInfo::m_numFaceChildren private
Referenced by add_child(), clear_children(), has_children(), num_child_faces(), remove_child(), replace_child(), and unregister_from_children().
m_pEdgeChild
Edge* ug::MGFaceInfo::m_pEdgeChild[MG_FACE_MAX_EDGE_CHILDREN] private
Referenced by add_child(), child_edge(), remove_child(), replace_child(), and unregister_from_children().
m_pFaceChild
Face* ug::MGFaceInfo::m_pFaceChild[MG_FACE_MAX_FACE_CHILDREN] private
Referenced by add_child(), child_face(), remove_child(), replace_child(), and unregister_from_children().
m_pVrtChild
Vertex* ug::MGFaceInfo::m_pVrtChild private
Referenced by add_child(), child_vertex(), clear_children(), has_children(), num_child_vertices(), remove_child(), replace_child(), and unregister_from_children().
The documentation for this struct was generated from the following files:
ugbase/lib_grid/multi_grid_child_info.h
ugbase/lib_grid/multi_grid.cpp