ug4: ug::MGVolumeInfo Struct Reference
ug::MGVolumeInfo Struct Reference
Holds information about volume relations. Used internally.
#include <multi_grid_child_info.h>
Public Member Functions
void add_child (Edge *elem)
void add_child (Face *elem)
void add_child (Vertex *elem)
void add_child (Volume *elem)
Edge * child_edge (size_t i) const
Face * child_face (size_t i) const
Vertex * child_vertex () const
Volume * child_volume (size_t i) const
void clear_children ()
bool has_children () const
MGVolumeInfo ()
size_t num_child_edges () const
size_t num_child_faces () const
size_t num_child_vertices () const
size_t num_child_volumes () const
void remove_child (Edge *elem)
void remove_child (Face *elem)
void remove_child (Vertex *elem)
void remove_child (Volume *elem)
void replace_child (Edge *elem, Edge *child)
void replace_child (Face *elem, Face *child)
void replace_child (Vertex *elem, Vertex *child)
void replace_child (Volume *elem, Volume *child)
void unregister_from_children (MultiGrid &mg)
Private Attributes
std::vector< Edge * > m_edgeChildren
std::vector< Face * > m_faceChildren
Vertex * m_pVrtChild
std::vector< Volume * > m_volumeChildren
Detailed Description
Holds information about volume relations. Used internally.
No parent included, since MGFaceInfos are not stored for surface elements.
Constructor & Destructor Documentation
MGVolumeInfo()
ug::MGVolumeInfo::MGVolumeInfo () inline
Member Function Documentation
add_child() [1/4]
void ug::MGVolumeInfo::add_child (Edge * elem) inline
References m_edgeChildren.
add_child() [2/4]
void ug::MGVolumeInfo::add_child (Face * elem) inline
References m_faceChildren.
add_child() [3/4]
void ug::MGVolumeInfo::add_child (Vertex * elem) inline
References m_pVrtChild.
Referenced by ug::MultiGrid::volume_created().
add_child() [4/4]
void ug::MGVolumeInfo::add_child (Volume * elem) inline
References m_volumeChildren.
child_edge()
Edge* ug::MGVolumeInfo::child_edge (size_t i) const inline
References m_edgeChildren, and num_child_edges().
Referenced by ug::MultiGrid::volume_created().
child_face()
Face* ug::MGVolumeInfo::child_face (size_t i) const inline
References m_faceChildren, and num_child_faces().
Referenced by ug::MultiGrid::volume_created().
child_vertex()
Vertex* ug::MGVolumeInfo::child_vertex () const inline
References m_pVrtChild.
Referenced by ug::MultiGrid::volume_created().
child_volume()
Volume* ug::MGVolumeInfo::child_volume (size_t i) const inline
References m_volumeChildren, and num_child_volumes().
Referenced by ug::MultiGrid::volume_created().
clear_children()
void ug::MGVolumeInfo::clear_children () inline
References m_edgeChildren, m_faceChildren, m_pVrtChild, and m_volumeChildren.
Referenced by unregister_from_children().
has_children()
bool ug::MGVolumeInfo::has_children () const inline
References m_edgeChildren, m_faceChildren, m_pVrtChild, and m_volumeChildren.
num_child_edges()
size_t ug::MGVolumeInfo::num_child_edges () const inline
References m_edgeChildren.
Referenced by child_edge(), and ug::MultiGrid::volume_created().
num_child_faces()
size_t ug::MGVolumeInfo::num_child_faces () const inline
References m_faceChildren.
Referenced by child_face(), and ug::MultiGrid::volume_created().
num_child_vertices()
size_t ug::MGVolumeInfo::num_child_vertices () const inline
References m_pVrtChild.
num_child_volumes()
size_t ug::MGVolumeInfo::num_child_volumes () const inline
References m_volumeChildren.
Referenced by child_volume(), and ug::MultiGrid::volume_created().
remove_child() [1/4]
void ug::MGVolumeInfo::remove_child (Edge * elem) inline
References ug::ArraySwapWithLast(), and m_edgeChildren.
remove_child() [2/4]
void ug::MGVolumeInfo::remove_child (Face * elem) inline
References ug::ArraySwapWithLast(), and m_faceChildren.
remove_child() [3/4]
void ug::MGVolumeInfo::remove_child (Vertex * elem) inline
References m_pVrtChild.
remove_child() [4/4]
void ug::MGVolumeInfo::remove_child (Volume * elem) inline
References ug::ArraySwapWithLast(), and m_volumeChildren.
replace_child() [1/4]
void ug::MGVolumeInfo::replace_child (Edge * elem, Edge * child) inline
References ug::ArrayReplaceEntry(), and m_edgeChildren.
replace_child() [2/4]
void ug::MGVolumeInfo::replace_child (Face * elem, Face * child) inline
References ug::ArrayReplaceEntry(), and m_faceChildren.
replace_child() [3/4]
void ug::MGVolumeInfo::replace_child (Vertex * elem, Vertex * child) inline
References m_pVrtChild.
replace_child() [4/4]
void ug::MGVolumeInfo::replace_child (Volume * elem, Volume * child) inline
References ug::ArrayReplaceEntry(), and m_volumeChildren.
unregister_from_children()
void ug::MGVolumeInfo::unregister_from_children (MultiGrid & mg)
References clear_children(), m_edgeChildren, m_faceChildren, m_pVrtChild, m_volumeChildren, and ug::MultiGrid::set_parent().
Member Data Documentation
m_edgeChildren
std::vector<Edge*> ug::MGVolumeInfo::m_edgeChildren private
Referenced by add_child(), child_edge(), clear_children(), has_children(), num_child_edges(), remove_child(), replace_child(), and unregister_from_children().
m_faceChildren
std::vector<Face*> ug::MGVolumeInfo::m_faceChildren private
Referenced by add_child(), child_face(), clear_children(), has_children(), num_child_faces(), remove_child(), replace_child(), and unregister_from_children().
m_pVrtChild
Vertex* ug::MGVolumeInfo::m_pVrtChild private
Referenced by add_child(), child_vertex(), clear_children(), has_children(), num_child_vertices(), remove_child(), replace_child(), and unregister_from_children().
m_volumeChildren
std::vector<Volume*> ug::MGVolumeInfo::m_volumeChildren private
Referenced by add_child(), child_volume(), clear_children(), has_children(), num_child_volumes(), remove_child(), replace_child(), and unregister_from_children().
The documentation for this struct was generated from the following files:
ugbase/lib_grid/multi_grid_child_info.h
ugbase/lib_grid/multi_grid.cpp