ug4: ug::DoFCount::Cnt Struct Reference
ug::DoFCount::Cnt Struct Reference
#include <dof_count.h>
Classes
struct PCnt
Public Member Functions
void add (uint64 num, SurfaceView::SurfaceState ss, byte is)
Cnt ()
void collect_values (std::vector< uint64 > &vNum) const
uint64 num (SurfaceView::SurfaceState ss, byte is) const
uint64 num_contains (SurfaceView::SurfaceState ss, byte is) const
void set_values (const std::vector< uint64 > &vNum, size_t &cnt)
Public Attributes
std::vector< PCnt > vNumSS
Constructor & Destructor Documentation
Cnt()
ug::DoFCount::Cnt::Cnt ()
References ug::DoFCount::SS_MAX, and vNumSS.
Member Function Documentation
add()
void ug::DoFCount::Cnt::add (uint64 num, SurfaceView::SurfaceState ss, byte is)
References ug::DoFCount::ES_MAX, ug::DoFCount::num(), ug::DoFCount::SS_MAX, and UG_THROW.
collect_values()
void ug::DoFCount::Cnt::collect_values (std::vector< uint64 > & vNum) const
References ug::SurfaceView::MG_SHADOW_PURE, ug::SurfaceView::MG_SHADOW_RIM_COPY, ug::SurfaceView::MG_SHADOW_RIM_NONCOPY, ug::SurfaceView::MG_SURFACE_PURE, ug::SurfaceView::MG_SURFACE_RIM, and PROFILE_FUNC.
num()
uint64 ug::DoFCount::Cnt::num (SurfaceView::SurfaceState ss, byte is) const
References ug::DoFCount::ALL_SS, ug::SurfaceView::MG_SHADOW_PURE, ug::SurfaceView::MG_SHADOW_RIM_NONCOPY, ug::SurfaceView::MG_SURFACE_PURE, ug::SurfaceView::MG_SURFACE_RIM, ug::DoFCount::num(), ug::DoFCount::SS_MAX, and ug::DoFCount::UNIQUE_SS.
num_contains()
uint64 ug::DoFCount::Cnt::num_contains (SurfaceView::SurfaceState ss, byte is) const
References ug::DoFCount::ALL_SS, ug::SurfaceView::MG_SHADOW_PURE, ug::SurfaceView::MG_SHADOW_RIM_NONCOPY, ug::SurfaceView::MG_SURFACE_PURE, ug::SurfaceView::MG_SURFACE_RIM, ug::DoFCount::num_contains(), ug::DoFCount::SS_MAX, and ug::DoFCount::UNIQUE_SS.
set_values()
void ug::DoFCount::Cnt::set_values (const std::vector< uint64 > & vNum, size_t & cnt)
References ug::SurfaceView::MG_SHADOW_PURE, ug::SurfaceView::MG_SHADOW_RIM_COPY, ug::SurfaceView::MG_SHADOW_RIM_NONCOPY, ug::SurfaceView::MG_SURFACE_PURE, ug::SurfaceView::MG_SURFACE_RIM, and PROFILE_FUNC.
Member Data Documentation
vNumSS
std::vector<PCnt> ug::DoFCount::Cnt::vNumSS
Referenced by Cnt().
The documentation for this struct was generated from the following files:
ugbase/lib_disc/dof_manager/dof_count.h
ugbase/lib_disc/dof_manager/dof_count.cpp