ug4: ug::AABox< vector_t > Struct Template Reference
ug::AABox< vector_t > Struct Template Reference
#include <shapes.h>
Public Member Functions
AABox ()
AABox (const vector_t &nMin, const vector_t &nMax)
AABox (const vector_t *points, size_t numPoints)
calculates the bounding box to the given set of points.
AABox (const AABox &b1, const AABox &b2)
calculates the bounding box of two given bounding boxes
AABox (const Sphere< vector_t > &s)
calculates the bounding box of the given sphere
AABox (const AABox &b, const vector_t &v)
calculates the bounding box of a given box and an additional point
vector_t center () const
returns the center of the box
bool contains_point (const vector_t &point) const
returns true if the given point lies in the box or on its boundary
vector_t extension () const
returns the extension (width/height/depth) of the box
bool overlaps_line (const vector_t &point1, const vector_t &point2) const
return true if the given line (segment) and the box overlap
Public Attributes
vector_t max
vector_t min
Constructor & Destructor Documentation
template<class vector_t> ug::AABox< vector_t >::AABox () inline
template<class vector_t> ug::AABox< vector_t >::AABox (const vector_t & nMin, const vector_t & nMax) inline
References ug::Sphere< vector_t >::center, and ug::Sphere< vector_t >::contains_point().
template<class vector_t > ug::AABox< vector_t >::AABox (const vector_t * points, size_t numPoints)
calculates the bounding box to the given set of points.
References ug::VecSet().
template<class vector_t > ug::AABox< vector_t >::AABox (const AABox< vector_t > & b1, const AABox< vector_t > & b2)
calculates the bounding box of two given bounding boxes
References ug::AABox< vector_t >::max, and ug::AABox< vector_t >::min.
template<class vector_t > ug::AABox< vector_t >::AABox (const Sphere< vector_t > & s)
calculates the bounding box of the given sphere
References ug::Sphere< vector_t >::center, ug::Sphere< vector_t >::radius, ug::VecAdd(), and ug::VecSubtract().
template<class vector_t > ug::AABox< vector_t >::AABox (const AABox< vector_t > & b, const vector_t & v)
calculates the bounding box of a given box and an additional point
References ug::AABox< vector_t >::max, and ug::AABox< vector_t >::min.
Member Function Documentation
template<class vector_t > vector_t ug::AABox< vector_t >::center () const
returns the center of the box
References ug::VecAdd(), and ug::VecScale().
template<class vector_t > bool ug::AABox< vector_t >::contains_point (const vector_t & point) const
returns true if the given point lies in the box or on its boundary
References ug::BoxBoundProbe().
Referenced by ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::box_contains_point(), and ug::SingularSourcesAndSinks< dim, 1 >::get_contrib_of_scv().
template<class vector_t > vector_t ug::AABox< vector_t >::extension () const
returns the extension (width/height/depth) of the box
References ug::VecSubtract().
Referenced by ug::UGXFileInfo::parse_file().
template<class vector_t > bool ug::AABox< vector_t >::overlaps_line (const vector_t & point1, const vector_t & point2) const
return true if the given line (segment) and the box overlap
References ug::BoxBoxIntersection().
Referenced by ug::SingularSourcesAndSinks< dim, 1 >::get_contrib_of_scv().
Member Data Documentation
template<class vector_t> vector_t ug::AABox< vector_t >::max
Referenced by ug::AABox< vector_t >::AABox(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::box_box_intersection(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::box_diagonal(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::calculate_bounding_box(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::grow_box(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::ray_box_intersection(), ug::ntree_traits< 1, 1, elem_t, NTreeGridData< 1 > >::split_box(), ug::ntree_traits< 1, 2, elem_t, NTreeGridData< 2 > >::split_box(), ug::ntree_traits< 2, 2, elem_t, NTreeGridData< 2 > >::split_box(), ug::ntree_traits< 2, 3, elem_t, NTreeGridData< 3 > >::split_box(), ug::ntree_traits< 3, 3, elem_t, NTreeGridData< 3 > >::split_box(), and ug::TIKZElem::TIKZElem().
template<class vector_t> vector_t ug::AABox< vector_t >::min
Referenced by ug::AABox< vector_t >::AABox(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::box_box_intersection(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::box_diagonal(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::calculate_bounding_box(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::grow_box(), ug::lg_ntree_traits_base< 1, 2, elem_t, NTreeGridData< 2 > >::ray_box_intersection(), ug::ntree_traits< 1, 1, elem_t, NTreeGridData< 1 > >::split_box(), ug::ntree_traits< 1, 2, elem_t, NTreeGridData< 2 > >::split_box(), ug::ntree_traits< 2, 2, elem_t, NTreeGridData< 2 > >::split_box(), ug::ntree_traits< 2, 3, elem_t, NTreeGridData< 3 > >::split_box(), ug::ntree_traits< 3, 3, elem_t, NTreeGridData< 3 > >::split_box(), and ug::TIKZElem::TIKZElem().
The documentation for this struct was generated from the following files:
ugbase/common/math/misc/shapes.h
ugbase/common/math/misc/shapes_impl.h