ug4: ug::bridge::AlgebraTypeIDProvider Struct Reference
ug::bridge::AlgebraTypeIDProvider Struct Reference
ugbase » Bridge
#include <util_algebra_dependent.h>
Classes
struct AlgebraID
struct AlgebraIDBase
struct RegisterAlgebraIndices
Public Member Functions
template<typename TAlgebra >
size_t id ()
template<typename TAlgebra >
void reg ()
Static Public Member Functions
static AlgebraTypeIDProvider & instance ()
Private Member Functions
AlgebraTypeIDProvider ()
AlgebraTypeIDProvider (AlgebraTypeIDProvider const &)
void operator= (AlgebraTypeIDProvider const &)
Private Attributes
AlgebraIDBase * m_aid [NUM_ALGEBRA_TYPES]
size_t n
Constructor & Destructor Documentation
AlgebraTypeIDProvider() [1/2]
ug::bridge::AlgebraTypeIDProvider::AlgebraTypeIDProvider () inline private
References n.
AlgebraTypeIDProvider() [2/2]
ug::bridge::AlgebraTypeIDProvider::AlgebraTypeIDProvider (AlgebraTypeIDProvider const &) private
Member Function Documentation
id()
template<typename TAlgebra > size_t ug::bridge::AlgebraTypeIDProvider::id () inline
References m_aid, ug::bridge::NUM_ALGEBRA_TYPES, and UG_THROW.
Referenced by ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::FinishTimestep(), ug::StdGlobAssembler< TDomain, TAlgebra >::FinishTimestep(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::PrepareTimestep(), ug::StdGlobAssembler< TDomain, TAlgebra >::PrepareTimestep(), and ug::FV1InnerBoundaryElemDisc< TImpl, TDomain >::RegisterPrepTimestep< List >::RegNext::RegNext().
instance()
static AlgebraTypeIDProvider& ug::bridge::AlgebraTypeIDProvider::instance () inline static
Referenced by ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::FinishTimestep(), ug::StdGlobAssembler< TDomain, TAlgebra >::FinishTimestep(), ug::LSGFGlobAssembler< TDomain, TAlgebra, TExtrapolation >::PrepareTimestep(), ug::StdGlobAssembler< TDomain, TAlgebra >::PrepareTimestep(), and ug::FV1InnerBoundaryElemDisc< TImpl, TDomain >::RegisterPrepTimestep< List >::RegNext::RegNext().
operator=()
void ug::bridge::AlgebraTypeIDProvider::operator= (AlgebraTypeIDProvider const &) private
reg()
template<typename TAlgebra > void ug::bridge::AlgebraTypeIDProvider::reg () inline
References m_aid, and n.
Referenced by ug::bridge::AlgebraTypeIDProvider::RegisterAlgebraIndices< List >::RegNext::RegNext().
Member Data Documentation
m_aid
AlgebraIDBase* ug::bridge::AlgebraTypeIDProvider::m_aid[NUM_ALGEBRA_TYPES] private
Referenced by id(), and reg().
n
size_t ug::bridge::AlgebraTypeIDProvider::n private
Referenced by AlgebraTypeIDProvider(), and reg().
The documentation for this struct was generated from the following file:
ugbase/bridge/util_algebra_dependent.h