ug4: ug::MGVertexInfo Struct Reference
ug::MGVertexInfo Struct Reference
Holds information about vertex relations. Used internally.
#include <multi_grid_child_info.h>
Public Member Functions
void add_child (Edge *)
void add_child (Face *)
void add_child (Vertex *elem)
void add_child (Volume *)
Vertex * child_vertex () const
void clear_children ()
bool has_children () const
MGVertexInfo ()
size_t num_child_vertices () const
void remove_child (Edge *)
void remove_child (Face *)
void remove_child (Vertex *elem)
void remove_child (Volume *)
void replace_child (Vertex *elem, Vertex *child)
void unregister_from_children (MultiGrid &mg)
Public Attributes
GridObject * m_pParent
Private Attributes
Vertex * m_pVrtChild
Detailed Description
Holds information about vertex relations. Used internally.
a vertex can have one of the following states: MGES_NORMAL, MGES_CONSTRAINED, MGES_FIXED the following should always hold true: children of a constrained node are constrained, too. children of a fixed node are fixed, too.
Constructor & Destructor Documentation
MGVertexInfo()
ug::MGVertexInfo::MGVertexInfo () inline
Member Function Documentation
add_child() [1/4]
void ug::MGVertexInfo::add_child (Edge *) inline
References UG_THROW.
add_child() [2/4]
void ug::MGVertexInfo::add_child (Face *) inline
References UG_THROW.
add_child() [3/4]
void ug::MGVertexInfo::add_child (Vertex * elem) inline
References m_pVrtChild.
Referenced by ug::MultiGrid::add_child(), and ug::MultiGrid::vertex_created().
add_child() [4/4]
void ug::MGVertexInfo::add_child (Volume *) inline
References UG_THROW.
child_vertex()
Vertex* ug::MGVertexInfo::child_vertex () const inline
References m_pVrtChild.
Referenced by ug::MultiGrid::get_child_vertex(), and ug::MultiGrid::vertex_created().
clear_children()
void ug::MGVertexInfo::clear_children () inline
References m_pVrtChild.
Referenced by unregister_from_children().
has_children()
bool ug::MGVertexInfo::has_children () const inline
References m_pVrtChild.
Referenced by ug::MultiGrid::has_children().
num_child_vertices()
size_t ug::MGVertexInfo::num_child_vertices () const inline
References m_pVrtChild.
Referenced by ug::MultiGrid::num_child_vertices().
remove_child() [1/4]
void ug::MGVertexInfo::remove_child (Edge *) inline
References UG_THROW.
remove_child() [2/4]
void ug::MGVertexInfo::remove_child (Face *) inline
References UG_THROW.
remove_child() [3/4]
void ug::MGVertexInfo::remove_child (Vertex * elem) inline
References m_pVrtChild.
Referenced by ug::MultiGrid::remove_child().
remove_child() [4/4]
void ug::MGVertexInfo::remove_child (Volume *) inline
References UG_THROW.
replace_child()
void ug::MGVertexInfo::replace_child (Vertex * elem, Vertex * child) inline
References m_pVrtChild.
unregister_from_children()
void ug::MGVertexInfo::unregister_from_children (MultiGrid & mg)
References clear_children(), m_pVrtChild, and ug::MultiGrid::set_parent().
Referenced by ug::MultiGrid::clear_child_connections(), and ug::MultiGrid::element_to_be_erased().
Member Data Documentation
m_pParent
GridObject* ug::MGVertexInfo::m_pParent
Referenced by ug::MultiGrid::get_parent(), and ug::MultiGrid::set_parent().
m_pVrtChild
Vertex* ug::MGVertexInfo::m_pVrtChild private
Referenced by add_child(), child_vertex(), clear_children(), has_children(), num_child_vertices(), remove_child(), replace_child(), and unregister_from_children().
The documentation for this struct was generated from the following files:
ugbase/lib_grid/multi_grid_child_info.h
ugbase/lib_grid/multi_grid.cpp