ug4: ug::bridge::lua::LuaParsing< SmartPtr< void > > Struct Reference
ug::bridge::lua::LuaParsing< SmartPtr< void > > Struct Reference
#include <lua_parsing.h>
Static Public Member Functions
static bool checkAndGet (std::pair< SmartPtr< void >, const ClassNameNode * > &res, lua_State *L, int index, const char *baseClassName)
static void push (lua_State *L, SmartPtr< void > data, const char *className)
Member Function Documentation
checkAndGet()
static bool ug::bridge::lua::LuaParsing< SmartPtr< void > >::checkAndGet (std::pair< SmartPtr< void >, const ClassNameNode * > & res, lua_State * L, int index, const char * baseClassName) inline static
References ug::bridge::ClassNameTreeContains(), ug::bridge::ClassNameNode::empty(), ug::bridge::lua::UserDataWrapper::is_const(), and ug::bridge::lua::UserDataWrapper::is_smart_ptr().
push()
static void ug::bridge::lua::LuaParsing< SmartPtr< void > >::push (lua_State * L, SmartPtr< void > data, const char * className) inline static
References ug::bridge::lua::CreateNewUserData().
The documentation for this struct was generated from the following file:
ugbase/bindings/lua/lua_parsing.h