ug4: ug::fv1_traits< TRefElem, TWorldDim > Struct Template Reference
ug::fv1_traits< TRefElem, TWorldDim > Struct Template Reference
Traits for Finite Volumes (dummy implementation)
#include <fv_util.h>
Public Types
typedef void bf_type
typedef void scv_type
typedef void scvf_type
Static Public Member Functions
static void NormalOnBF (MathVector< TWorldDim > &outNormal, const MathVector< TWorldDim > *vSCVFCorner, const MathVector< TWorldDim > *vElemCorner)
static void NormalOnSCVF (MathVector< TWorldDim > &outNormal, const MathVector< TWorldDim > *vSCVFCorner, const MathVector< TWorldDim > *vElemCorner)
Static Public Attributes
static const size_t maxNSH
static const size_t maxNumSCV
static const size_t maxNumSCVF
static const size_t NumCornersOfBF
static const size_t NumCornersOfSCV
static const size_t NumCornersOfSCVF
Detailed Description
template<typename TRefElem, int TWorldDim>
struct ug::fv1_traits< TRefElem, TWorldDim >
Traits for Finite Volumes (dummy implementation)
Member Typedef Documentation
template<typename TRefElem, int TWorldDim> typedef void ug::fv1_traits< TRefElem, TWorldDim >::bf_type
template<typename TRefElem, int TWorldDim> typedef void ug::fv1_traits< TRefElem, TWorldDim >::scv_type
template<typename TRefElem, int TWorldDim> typedef void ug::fv1_traits< TRefElem, TWorldDim >::scvf_type
Member Function Documentation
template<typename TRefElem, int TWorldDim> static void ug::fv1_traits< TRefElem, TWorldDim >::NormalOnBF (MathVector< TWorldDim > & outNormal, const MathVector< TWorldDim > * vSCVFCorner, const MathVector< TWorldDim > * vElemCorner) static
Referenced by ug::FV1Geometry< TElem, TWorldDim >::update_boundary_faces(), and ug::DimFV1Geometry< TDim, TWorldDim >::update_boundary_faces().
template<typename TRefElem, int TWorldDim> static void ug::fv1_traits< TRefElem, TWorldDim >::NormalOnSCVF (MathVector< TWorldDim > & outNormal, const MathVector< TWorldDim > * vSCVFCorner, const MathVector< TWorldDim > * vElemCorner) static
Referenced by ug::fv1_traits< ReferenceEdge, 1 >::NormalOnBF(), ug::fv1_traits< ReferenceEdge, 2 >::NormalOnBF(), ug::fv1_traits< ReferenceEdge, 3 >::NormalOnBF(), ug::fv1_traits_ReferenceFace2d::NormalOnBF(), ug::fv1_traits< ReferenceTriangle, 3 >::NormalOnBF(), ug::fv1_traits< ReferenceQuadrilateral, 3 >::NormalOnBF(), ug::fv1_traits_ReferenceVolume::NormalOnBF(), ug::FV1Geometry< TElem, TWorldDim >::update(), ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::FVGeometry< TOrder, TElem, TWorldDim, TQuadOrder >::update_boundary_faces().
Member Data Documentation
template<typename TRefElem, int TWorldDim> const size_t ug::fv1_traits< TRefElem, TWorldDim >::maxNSH static
template<typename TRefElem, int TWorldDim> const size_t ug::fv1_traits< TRefElem, TWorldDim >::maxNumSCV static
template<typename TRefElem, int TWorldDim> const size_t ug::fv1_traits< TRefElem, TWorldDim >::maxNumSCVF static
template<typename TRefElem, int TWorldDim> const size_t ug::fv1_traits< TRefElem, TWorldDim >::NumCornersOfBF static
template<typename TRefElem, int TWorldDim> const size_t ug::fv1_traits< TRefElem, TWorldDim >::NumCornersOfSCV static
template<typename TRefElem, int TWorldDim> const size_t ug::fv1_traits< TRefElem, TWorldDim >::NumCornersOfSCVF static
The documentation for this struct was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv_util.h