ug4: ug::SCVFofSCVRayIntersectionWrapper< 2, 2 > Struct Reference
ug::SCVFofSCVRayIntersectionWrapper< 2, 2 > Struct Reference
#include <geometry_util.h>
Static Public Member Functions
static bool apply (size_t &sideOut, number &bc, MathVector< 2 > &GlobalIntersectionPointOut, MathVector< 2 > &LocalIntersectionPoint, const MathVector< 2 > &From, const MathVector< 2 > &Direction, bool bPositiv, const MathVector< 2 > *vCornerCoords)
Member Function Documentation
apply()
static bool ug::SCVFofSCVRayIntersectionWrapper< 2, 2 >::apply (size_t & sideOut, number & bc, MathVector< 2 > & GlobalIntersectionPointOut, MathVector< 2 > & LocalIntersectionPoint, const MathVector< 2 > & From, const MathVector< 2 > & Direction, bool bPositiv, const MathVector< 2 > * vCornerCoords) inline static
References ug::DimReferenceElement< d >::corner(), dim, ug::Provider< TClass >::get(), ug::ReferenceElement::id(), ug::ReferenceElement::num(), ug::RayLineIntersection2d(), UG_THROW, and ug::VecScaleAdd().
The documentation for this struct was generated from the following file:
ugbase/lib_disc/common/geometry_util.h