ug4: ug::linker_traits< TData, TDataIn, TRet > Struct Template Reference
ug::linker_traits< TData, TDataIn, TRet > Struct Template Reference
Linker Traits.
#include <linker_traits.h>
Static Public Member Functions
static void mult_add (TData &out, const TData &in1, const TDataIn &s)
computes out += s * in1 (with appropriate '*')
Detailed Description
template<typename TData, typename TDataIn, typename TRet = TData>
struct ug::linker_traits< TData, TDataIn, TRet >
Linker Traits.
Member Function Documentation
mult_add()
template<typename TData , typename TDataIn , typename TRet = TData> static void ug::linker_traits< TData, TDataIn, TRet >::mult_add (TData & out, const TData & in1, const TDataIn & s) static
computes out += s * in1 (with appropriate '*')
Referenced by ug::LuaUserFunction< TData, dim, TDataIn >::eval_and_deriv(), ug::vrl::VRLUserLinker< TData, dim, TDataIn >::eval_and_deriv(), ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::eval_and_deriv(), and ug::ScaleAddLinker< TData, dim, TDataScale, TRet >::evaluate().
The documentation for this struct was generated from the following file:
ugbase/lib_disc/spatial_disc/user_data/linker/linker_traits.h