ug4: ug::bridge::lua::LuaParsing< void * > Struct Template Reference
ug::bridge::lua::LuaParsing< void * > Struct Template Reference
#include <lua_parsing.h>
Static Public Member Functions
static bool checkAndGet (std::pair< void *, const ClassNameNode * > &res, lua_State *L, int index, const char *baseClassName)
static void push (lua_State *L, void *data, const char *className)
Member Function Documentation
static bool ug::bridge::lua::LuaParsing< void * >::checkAndGet (std::pair< void *, const ClassNameNode * > & res, lua_State * L, int index, const char * baseClassName) inline static
References ug::bridge::ClassNameTreeContains(), ug::bridge::ClassNameNode::empty(), ug::bridge::lua::IMLPICIT_SMART_PTR_TO_PTR_CONVERSION, ug::bridge::lua::UserDataWrapper::is_const(), ug::bridge::lua::UserDataWrapper::is_raw_ptr(), and ug::bridge::lua::UserDataWrapper::is_smart_ptr().
static void ug::bridge::lua::LuaParsing< void * >::push (lua_State * L, void * data, const char * className) inline static
References ug::bridge::lua::CreateNewUserData().
The documentation for this struct was generated from the following file:
ugbase/bindings/lua/lua_parsing.h