ug4: ug::fv1_traits_ReferencePyramid Struct Reference
ug::fv1_traits_ReferencePyramid Struct Reference
Pyramids: dimension-independent part of the FV1 traits.
#include <fv_util.h>
Public Types
typedef ReferenceQuadrilateral bf_type
typedef ReferenceTetrahedron scv_type
typedef ReferenceTriangle scvf_type
Public Types inherited from ug::fv1_traits_ReferenceVolume
typedef ReferenceQuadrilateral bf_type
typedef ReferenceHexahedron scv_type
typedef ReferenceQuadrilateral scvf_type
Static Public Member Functions
static void scv_mid_id (const ReferencePyramid &refElem, MidID *vMidID, size_t i)
Calculates array vMidID for scv i.
static size_t scv_node_id (const ReferencePyramid &refElem, size_t i)
returns the node id for a scv (overridden function from fv1_traits_most_common)
static size_t scvf_from_to (const ReferencePyramid &refElem, size_t i, size_t ft)
returns the 'from' and 'to' corner indices for a scvf (overridden function from fv1_traits_most_common)
static void scvf_mid_id (const ReferencePyramid &refElem, MidID *vMidID, size_t i)
Calculates array vMidID for scvf i.
Static Public Member Functions inherited from ug::fv1_traits_ReferenceVolume
static void NormalOnBF (MathVector< 3 > &outNormal, const MathVector< 3 > *vSCVFCorner, const MathVector< 3 > *vElemCorner)
static void NormalOnSCVF (MathVector< 3 > &outNormal, const MathVector< 3 > *vSCVFCorner, const MathVector< 3 > *vElemCorner)
Static Public Attributes
static const size_t NumCornersOfBF = 4
static const size_t NumCornersOfSCV = 4
static const size_t NumCornersOfSCVF = 3
static const size_t numSCV = 4 * ReferencePyramid::numEdges
overridden field from fv1_traits_most_common
static const size_t numSCVF = 2 * ReferencePyramid::numEdges
overridden field from fv1_traits_most_common
Static Public Attributes inherited from ug::fv1_traits_ReferenceVolume
static const size_t maxNSH = 8
static const size_t maxNumSCV = 32
static const size_t maxNumSCVF = 24
static const size_t NumCornersOfBF = 4
static const size_t NumCornersOfSCV = 8
static const size_t NumCornersOfSCVF = 4
Detailed Description
Pyramids: dimension-independent part of the FV1 traits.
For Pyramids we use triangular scvf, since the quadrilateral scvf would not be flat in general by the positions where its corners are placed
Member Typedef Documentation
bf_type
typedef ReferenceQuadrilateral ug::fv1_traits_ReferencePyramid::bf_type
scv_type
typedef ReferenceTetrahedron ug::fv1_traits_ReferencePyramid::scv_type
scvf_type
typedef ReferenceTriangle ug::fv1_traits_ReferencePyramid::scvf_type
Member Function Documentation
scv_mid_id()
static void ug::fv1_traits_ReferencePyramid::scv_mid_id (const ReferencePyramid & refElem, MidID * vMidID, size_t i) inline static
Calculates array vMidID for scv i.
Parameters
refElem the reference element object
vMidID array vMidID for scvf i
i index of the scvf
References dim, and ug::ReferenceElement::id().
Referenced by ug::ComputeSCVMidID().
scv_node_id()
static size_t ug::fv1_traits_ReferencePyramid::scv_node_id (const ReferencePyramid & refElem, size_t i) inline static
returns the node id for a scv (overridden function from fv1_traits_most_common)
Parameters
refElem the reference element object
i index of the scv
References ug::ReferenceElement::id().
Referenced by ug::fv1_dim_traits_base< TDim, TWorldDim >::dim_scv_node_id().
scvf_from_to()
static size_t ug::fv1_traits_ReferencePyramid::scvf_from_to (const ReferencePyramid & refElem, size_t i, size_t ft) inline static
returns the 'from' and 'to' corner indices for a scvf (overridden function from fv1_traits_most_common)
Parameters
refElem the reference element object
i index of the scvf
ft 0 = from, 1 = to
References ug::ReferenceElement::id().
Referenced by ug::fv1_dim_traits_base< TDim, TWorldDim >::get_dim_scvf_from_to().
scvf_mid_id()
static void ug::fv1_traits_ReferencePyramid::scvf_mid_id (const ReferencePyramid & refElem, MidID * vMidID, size_t i) inline static
Calculates array vMidID for scvf i.
Parameters
refElem the reference element object
vMidID array vMidID for scvf i
i index of the scvf
References dim, and ug::ReferenceElement::id().
Referenced by ug::ComputeSCVFMidID().
Member Data Documentation
NumCornersOfBF
const size_t ug::fv1_traits_ReferencePyramid::NumCornersOfBF = 4 static
NumCornersOfSCV
const size_t ug::fv1_traits_ReferencePyramid::NumCornersOfSCV = 4 static
NumCornersOfSCVF
const size_t ug::fv1_traits_ReferencePyramid::NumCornersOfSCVF = 3 static
numSCV
const size_t ug::fv1_traits_ReferencePyramid::numSCV = 4 * ReferencePyramid::numEdges static
overridden field from fv1_traits_most_common
numSCVF
const size_t ug::fv1_traits_ReferencePyramid::numSCVF = 2 * ReferencePyramid::numEdges static
overridden field from fv1_traits_most_common
The documentation for this struct was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv_util.h