ug4: ug::ParallelNodes::OverlapType Struct Reference
ug::ParallelNodes::OverlapType Struct Reference
#include <parallel_nodes.h>
Public Types
enum eOverlapType { OT_MASTER , OT_SLAVE , OT_OUTER }
Public Member Functions
size_t distance_to_master_or_inner () const
bool is_inner () const
bool is_master () const
bool is_master_or_inner () const
bool is_slave () const
OverlapType ()
OverlapType (int distanceToMasterOrInner)
void set_distance_to_master_or_inner (size_t i)
void set_inner ()
void set_master ()
void set_slave ()
Public Attributes
int type
Friends
std::ostream & operator<< (std::ostream &out, const OverlapType &o)
Member Enumeration Documentation
eOverlapType
enum ug::ParallelNodes::OverlapType::eOverlapType
Enumerator
OT_MASTER
OT_SLAVE
OT_OUTER
Constructor & Destructor Documentation
OverlapType() [1/2]
ug::ParallelNodes::OverlapType::OverlapType () inline
References set_inner().
OverlapType() [2/2]
ug::ParallelNodes::OverlapType::OverlapType (int distanceToMasterOrInner) inline
References set_distance_to_master_or_inner().
Member Function Documentation
distance_to_master_or_inner()
size_t ug::ParallelNodes::OverlapType::distance_to_master_or_inner () const inline
References type.
is_inner()
bool ug::ParallelNodes::OverlapType::is_inner () const inline
References OT_INNER_FLAG, and type.
Referenced by is_master_or_inner().
is_master()
bool ug::ParallelNodes::OverlapType::is_master () const inline
References OT_MASTER_FLAG, and type.
Referenced by is_master_or_inner().
is_master_or_inner()
bool ug::ParallelNodes::OverlapType::is_master_or_inner () const inline
References is_inner(), and is_master().
is_slave()
bool ug::ParallelNodes::OverlapType::is_slave () const inline
References OT_SLAVE_FLAG, and type.
set_distance_to_master_or_inner()
void ug::ParallelNodes::OverlapType::set_distance_to_master_or_inner (size_t i) inline
References type.
Referenced by OverlapType().
set_inner()
void ug::ParallelNodes::OverlapType::set_inner () inline
References OT_INNER_FLAG, and type.
Referenced by OverlapType().
set_master()
void ug::ParallelNodes::OverlapType::set_master () inline
References OT_MASTER_FLAG, and type.
set_slave()
void ug::ParallelNodes::OverlapType::set_slave () inline
References OT_SLAVE_FLAG, and type.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const OverlapType & o) friend
Member Data Documentation
type
int ug::ParallelNodes::OverlapType::type
Referenced by distance_to_master_or_inner(), is_inner(), is_master(), is_slave(), set_distance_to_master_or_inner(), set_inner(), set_master(), and set_slave().
The documentation for this struct was generated from the following file:
ugbase/lib_algebra/parallelization/parallel_nodes.h