ug4: ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo Struct Reference
ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo Struct Reference
Public Member Functions
size_t child_edge (size_t i) const
bool is_hanging () const
NatEdgeInfo ()
size_t node_id () const
size_t num_child_edges () const
Private Attributes
size_t childEdge [2]
size_t nodeId
size_t numChildEdges
Friends
class DimHFV1Geometry< TDim, TWorldDim >
Constructor & Destructor Documentation
NatEdgeInfo()
template<int TDim, int TWorldDim = TDim> ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::NatEdgeInfo () inline
References ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::childEdge.
Member Function Documentation
child_edge()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::child_edge (size_t i) const inline
References ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::childEdge, ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::num_child_edges(), and UG_ASSERT.
is_hanging()
template<int TDim, int TWorldDim = TDim> bool ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::is_hanging () const inline
References ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::numChildEdges.
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::node_id().
node_id()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::node_id () const inline
References ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::is_hanging(), ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::nodeId, and UG_ASSERT.
num_child_edges()
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::num_child_edges () const inline
References ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::numChildEdges.
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::child_edge().
Friends And Related Function Documentation
DimHFV1Geometry< TDim, TWorldDim >
template<int TDim, int TWorldDim = TDim> friend class DimHFV1Geometry< TDim, TWorldDim > friend
Member Data Documentation
childEdge
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::childEdge[2] private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::child_edge(), and ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::NatEdgeInfo().
nodeId
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::nodeId private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::node_id().
numChildEdges
template<int TDim, int TWorldDim = TDim> size_t ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::numChildEdges private
Referenced by ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::is_hanging(), and ug::DimHFV1Geometry< TDim, TWorldDim >::NatEdgeInfo::num_child_edges().
The documentation for this struct was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/hfv1_geom.h