ug4: ug::mat_operations_class< vector_t, matrix_t, MATRIX_USE_GLOBAL_FUNCTIONS > Struct Template Reference
ug::mat_operations_class< vector_t, matrix_t, MATRIX_USE_GLOBAL_FUNCTIONS > Struct Template Reference
#include <matrix_use_global_functions.h>
Static Public Member Functions
static bool MatMult (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1)
calculates dest = beta1 * A1;
static bool MatMultAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &alpha2, const vector_t &v2, const number &beta1, const matrix_t &A1, const vector_t &w1)
calculates dest = alpha1*v1 + beta1 * A1 *w1 + alpha2*v2;
static bool MatMultAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const matrix_t &A1, const vector_t &w1)
calculates dest = alpha1*v1 + beta1 * A1 *w1;
static bool MatMultAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const matrix_t &A1, const vector_t &w1, const number &beta2, const matrix_t &A2, const vector_t &w2)
calculates dest = beta1 * A1 *w1 + beta2 * A2*w2 + alpha1*v1;
static bool MatMultAdd (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1, const number &beta2, const matrix_t &A2, const vector_t &w2)
calculates dest = beta1 * A1 *w1 + beta2 * A2*w2;
static bool MatMultTransposed (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1)
calculates dest = beta1 * A1^T *w1;
static bool MatMultTransposedAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const matrix_t &A1, const vector_t &w1)
calculates dest = alpha1*v1 + beta1 * A1^T *w1;
Member Function Documentation
MatMult()
template<typename vector_t , typename matrix_t > static bool ug::mat_operations_class< vector_t, matrix_t, MATRIX_USE_GLOBAL_FUNCTIONS >::MatMult (vector_t & dest, const number & beta1, const matrix_t & A1, const vector_t & w1) inline static
calculates dest = beta1 * A1;
References ug::MatMultDirect().
MatMultAdd() [1/4]
template<typename vector_t , typename matrix_t > static bool ug::mat_operations_class< vector_t, matrix_t, MATRIX_USE_GLOBAL_FUNCTIONS >::MatMultAdd (vector_t & dest, const number & alpha1, const vector_t & v1, const number & alpha2, const vector_t & v2, const number & beta1, const matrix_t & A1, const vector_t & w1) inline static
calculates dest = alpha1*v1 + beta1 * A1 *w1 + alpha2*v2;
References ug::MatMultAddDirect().
MatMultAdd() [2/4]
template<typename vector_t , typename matrix_t > static bool ug::mat_operations_class< vector_t, matrix_t, MATRIX_USE_GLOBAL_FUNCTIONS >::MatMultAdd (vector_t & dest, const number & alpha1, const vector_t & v1, const number & beta1, const matrix_t & A1, const vector_t & w1) inline static
calculates dest = alpha1*v1 + beta1 * A1 *w1;
References ug::MatMultAddDirect().
MatMultAdd() [3/4]
template<typename vector_t , typename matrix_t > static bool ug::mat_operations_class< vector_t, matrix_t, MATRIX_USE_GLOBAL_FUNCTIONS >::MatMultAdd (vector_t & dest, const number & alpha1, const vector_t & v1, const number & beta1, const matrix_t & A1, const vector_t & w1, const number & beta2, const matrix_t & A2, const vector_t & w2) inline static
calculates dest = beta1 * A1 *w1 + beta2 * A2*w2 + alpha1*v1;
References ug::MatMultAddDirect().
MatMultAdd() [4/4]
template<typename vector_t , typename matrix_t > static bool ug::mat_operations_class< vector_t, matrix_t, MATRIX_USE_GLOBAL_FUNCTIONS >::MatMultAdd (vector_t & dest, const number & beta1, const matrix_t & A1, const vector_t & w1, const number & beta2, const matrix_t & A2, const vector_t & w2) inline static
calculates dest = beta1 * A1 *w1 + beta2 * A2*w2;
References ug::MatMultAddDirect().
MatMultTransposed()
template<typename vector_t , typename matrix_t > static bool ug::mat_operations_class< vector_t, matrix_t, MATRIX_USE_GLOBAL_FUNCTIONS >::MatMultTransposed (vector_t & dest, const number & beta1, const matrix_t & A1, const vector_t & w1) inline static
calculates dest = beta1 * A1^T *w1;
References ug::MatMultTransposed().
MatMultTransposedAdd()
template<typename vector_t , typename matrix_t > static bool ug::mat_operations_class< vector_t, matrix_t, MATRIX_USE_GLOBAL_FUNCTIONS >::MatMultTransposedAdd (vector_t & dest, const number & alpha1, const vector_t & v1, const number & beta1, const matrix_t & A1, const vector_t & w1) inline static
calculates dest = alpha1*v1 + beta1 * A1^T *w1;
The documentation for this struct was generated from the following file:
ugbase/lib_algebra/common/operations_mat/matrix_use_global_functions.h