ug4: ug::TarHeader Struct Reference
ug::TarHeader Struct Reference
#include <tar.h>
Public Member Functions
void set_checksum ()
void set_filename (std::string name)
void set_filesize (size_t size)
TarHeader ()
Public Attributes
char checksum [8]
char filemode [8]
char filename [100]
char groupID [8]
char linkedFilename [100]
char linkIndicator
char octalFileSize [12]
char octalModificationTimeStamp [12]
char padding [12]
char userID [8]
char ustarDeviceMajorNumber [8]
char ustarDeviceMinorNumber [8]
char ustarFilenamePrefix [155]
char ustarIndicator [6]
char ustarOwnerGroupName [32]
char ustarOwnerUserName [32]
char ustarVersion [2]
Constructor & Destructor Documentation
TarHeader()
ug::TarHeader::TarHeader () inline
References filemode, groupID, linkIndicator, octalModificationTimeStamp, sprintf(), userID, ustarDeviceMajorNumber, ustarDeviceMinorNumber, ustarIndicator, ustarOwnerGroupName, ustarOwnerUserName, and ustarVersion.
Referenced by set_checksum().
Member Function Documentation
set_checksum()
void ug::TarHeader::set_checksum () inline
References checksum, p, sprintf(), and TarHeader().
Referenced by pcl::WriteParallelArchive().
set_filename()
void ug::TarHeader::set_filename (std::string name) inline
References filename, and name.
Referenced by pcl::WriteParallelArchive().
set_filesize()
void ug::TarHeader::set_filesize (size_t size) inline
References octalFileSize, and sprintf().
Referenced by pcl::WriteParallelArchive().
Member Data Documentation
checksum
char ug::TarHeader::checksum[8]
Referenced by set_checksum().
filemode
char ug::TarHeader::filemode[8]
Referenced by TarHeader().
filename
char ug::TarHeader::filename[100]
Referenced by set_filename().
groupID
char ug::TarHeader::groupID[8]
Referenced by TarHeader().
linkedFilename
char ug::TarHeader::linkedFilename[100]
linkIndicator
char ug::TarHeader::linkIndicator
Referenced by TarHeader().
octalFileSize
char ug::TarHeader::octalFileSize[12]
Referenced by set_filesize().
octalModificationTimeStamp
char ug::TarHeader::octalModificationTimeStamp[12]
Referenced by TarHeader().
padding
char ug::TarHeader::padding[12]
userID
char ug::TarHeader::userID[8]
Referenced by TarHeader().
ustarDeviceMajorNumber
char ug::TarHeader::ustarDeviceMajorNumber[8]
Referenced by TarHeader().
ustarDeviceMinorNumber
char ug::TarHeader::ustarDeviceMinorNumber[8]
Referenced by TarHeader().
ustarFilenamePrefix
char ug::TarHeader::ustarFilenamePrefix[155]
ustarIndicator
char ug::TarHeader::ustarIndicator[6]
Referenced by TarHeader().
ustarOwnerGroupName
char ug::TarHeader::ustarOwnerGroupName[32]
Referenced by TarHeader().
ustarOwnerUserName
char ug::TarHeader::ustarOwnerUserName[32]
Referenced by TarHeader().
ustarVersion
char ug::TarHeader::ustarVersion[2]
Referenced by TarHeader().
The documentation for this struct was generated from the following file:
ugbase/common/util/tar.h