ug4: ug::NeumannBoundaryFE< TDomain >::NumberData Struct Reference
ug::NeumannBoundaryFE< TDomain >::NumberData Struct Reference
Unconditional scalar user data.
#include <neumann_boundary_fe.h>
Public Member Functions
template<typename TElem , typename TFEGeom >
void extract_bip (const TFEGeom &geo)
template<typename TElem , typename TFEGeom >
void lin_def (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
NumberData (SmartPtr< CplUserData< number, dim > > data, std::string BndSubsets, std::string InnerSubsets, NeumannBoundaryFE *this_)
Public Member Functions inherited from ug::NeumannBoundaryBase< TDomain >::Data
Data (std::string BndSubsets_, std::string InnerSubsets_)
Public Attributes
DataImport< number, dim > import
NeumannBoundaryFE * This
std::vector< MathVector< dim > > vGloIP
std::vector< MathVector< dim > > vLocIP
Public Attributes inherited from ug::NeumannBoundaryBase< TDomain >::Data
SubsetGroup BndSSGrp
std::string BndSubsetNames
SubsetGroup InnerSSGrp
std::string InnerSubsetNames
Detailed Description
template<typename TDomain>
struct ug::NeumannBoundaryFE< TDomain >::NumberData
Unconditional scalar user data.
Constructor & Destructor Documentation
NumberData()
template<typename TDomain > ug::NeumannBoundaryFE< TDomain >::NumberData::NumberData (SmartPtr< CplUserData< number, dim > > data, std::string BndSubsets, std::string InnerSubsets, NeumannBoundaryFE * this_) inline
References ug::NeumannBoundaryFE< TDomain >::NumberData::extract_bip(), and ug::NeumannBoundaryFE< TDomain >::NumberData::lin_def().
Member Function Documentation
extract_bip()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::NeumannBoundaryFE< TDomain >::NumberData::extract_bip (const TFEGeom & geo)
References ug::NeumannBoundaryFE< TDomain >::register_all_funcs().
Referenced by ug::NeumannBoundaryFE< TDomain >::NumberData::lin_def(), and ug::NeumannBoundaryFE< TDomain >::NumberData::NumberData().
lin_def()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::NeumannBoundaryFE< TDomain >::NumberData::lin_def (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
References ug::NeumannBoundaryFE< TDomain >::_C_, ug::NeumannBoundaryFE< TDomain >::NumberData::extract_bip(), and ug::GeomProvider< TGeom >::get().
Referenced by ug::NeumannBoundaryFE< TDomain >::finish_elem_loop(), and ug::NeumannBoundaryFE< TDomain >::NumberData::NumberData().
Member Data Documentation
import
template<typename TDomain > DataImport<number, dim> ug::NeumannBoundaryFE< TDomain >::NumberData::import
This
template<typename TDomain > NeumannBoundaryFE* ug::NeumannBoundaryFE< TDomain >::NumberData::This
vGloIP
template<typename TDomain > std::vector<MathVector<dim> > ug::NeumannBoundaryFE< TDomain >::NumberData::vGloIP
vLocIP
template<typename TDomain > std::vector<MathVector<dim> > ug::NeumannBoundaryFE< TDomain >::NumberData::vLocIP
The documentation for this struct was generated from the following files:
ugbase/lib_disc/spatial_disc/elem_disc/neumann_boundary/fe/neumann_boundary_fe.h
ugbase/lib_disc/spatial_disc/elem_disc/neumann_boundary/fe/neumann_boundary_fe.cpp