ug4: ug::bridge::Refinement::Functionality Struct Reference
ug::bridge::Refinement::Functionality Struct Reference
ugbase » Bridge » Domain Bridge » Refinement Bridge
Static Public Member Functions
static void Common (Registry &reg, string grp)
template<typename TDomain >
static void Domain (Registry &reg, string grp)
Detailed Description
Class exporting the functionality. All functionality that is to be used in scripts or visualization must be registered here.
Member Function Documentation
Common()
static void ug::bridge::Refinement::Functionality::Common (Registry & reg, string grp) inline static
Function called for the registration of Domain and Algebra independent parts. All Functions and Classes not depending on Domain and Algebra are to be placed here when registering.
Parameters
reg registry
parentGroup group for sorting of functionality
References ug::bridge::Registry::add_function(), ug::ApplyConstrainedSmoothSubdivisionVolumesToTopLevel(), ug::ApplySmoothSubdivisionSurfacesToTopLevel(), ug::ApplySmoothSubdivisionVolumesToTopLevel(), ug::CheckValences(), ug::MarkForRefinement_All(), ug::MarkNeighborsForAnisotropicRefinement(), ug::MarkNeighborsForFullRefinement(), ug::ProjectHierarchyToLimitSubdivisionVolume(), ug::SetSmoothSubdivisionVolumesBoundaryRefinementRule(), ug::SetTetRefinementRule(), and ug::TetrahedralizeHybridTetOctGrid().
Domain()
template<typename TDomain > static void ug::bridge::Refinement::Functionality::Domain (Registry & reg, string grp) inline static
Function called for the registration of Domain dependent parts. All Functions and Classes depending on the Domain are to be placed here when registering. The method is called for all available Domain types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
References ug::bridge::Registry::add_function(), and ug::MarkForRefinement_ElementsInSubset().
The documentation for this struct was generated from the following file:
ugbase/bridge/domain_bridges/refinement_bridge.cpp