ug4: ug::MGEdgeInfo Struct Reference
ug::MGEdgeInfo Struct Reference
Holds information about edge relations. Used internally.
#include <multi_grid_child_info.h>
Public Member Functions
void add_child (Edge *elem)
void add_child (Face *)
void add_child (Vertex *elem)
void add_child (Volume *)
Edge * child_edge (size_t i) const
Vertex * child_vertex () const
void clear_children ()
bool has_children () const
MGEdgeInfo ()
size_t num_child_edges () const
size_t num_child_vertices () const
void remove_child (Edge *elem)
void remove_child (Face *)
void remove_child (Vertex *elem)
void remove_child (Volume *)
void replace_child (Edge *elem, Edge *child)
void replace_child (Vertex *elem, Vertex *child)
void unregister_from_children (MultiGrid &mg)
Public Attributes
GridObject * m_pParent
Private Attributes
byte m_numEdgeChildren
Edge * m_pEdgeChild [MG_EDGE_MAX_EDGE_CHILDREN]
Vertex * m_pVrtChild
Detailed Description
Holds information about edge relations. Used internally.
an edge can have one of the following states: MGES_NORMAL, MGES_CONSTRAINING, MGES_CONSTRAINED the following should always hold true: children of a constraining edge are constrained. children of a constrained edge are constrained.
Constructor & Destructor Documentation
MGEdgeInfo()
ug::MGEdgeInfo::MGEdgeInfo () inline
Member Function Documentation
add_child() [1/4]
void ug::MGEdgeInfo::add_child (Edge * elem) inline
References m_numEdgeChildren, m_pEdgeChild, and ug::MG_EDGE_MAX_EDGE_CHILDREN.
add_child() [2/4]
void ug::MGEdgeInfo::add_child (Face *) inline
References UG_THROW.
add_child() [3/4]
void ug::MGEdgeInfo::add_child (Vertex * elem) inline
References m_pVrtChild.
Referenced by ug::MultiGrid::edge_created().
add_child() [4/4]
void ug::MGEdgeInfo::add_child (Volume *) inline
References UG_THROW.
child_edge()
Edge* ug::MGEdgeInfo::child_edge (size_t i) const inline
References m_pEdgeChild, and num_child_edges().
Referenced by ug::MultiGrid::edge_created().
child_vertex()
Vertex* ug::MGEdgeInfo::child_vertex () const inline
References m_pVrtChild.
Referenced by ug::MultiGrid::edge_created().
clear_children()
void ug::MGEdgeInfo::clear_children () inline
References m_numEdgeChildren, and m_pVrtChild.
Referenced by unregister_from_children().
has_children()
bool ug::MGEdgeInfo::has_children () const inline
References m_numEdgeChildren, and m_pVrtChild.
num_child_edges()
size_t ug::MGEdgeInfo::num_child_edges () const inline
References m_numEdgeChildren.
Referenced by child_edge(), and ug::MultiGrid::edge_created().
num_child_vertices()
size_t ug::MGEdgeInfo::num_child_vertices () const inline
References m_pVrtChild.
remove_child() [1/4]
void ug::MGEdgeInfo::remove_child (Edge * elem) inline
References ug::ArrayEraseEntry(), m_numEdgeChildren, and m_pEdgeChild.
remove_child() [2/4]
void ug::MGEdgeInfo::remove_child (Face *) inline
References UG_THROW.
remove_child() [3/4]
void ug::MGEdgeInfo::remove_child (Vertex * elem) inline
References m_pVrtChild.
remove_child() [4/4]
void ug::MGEdgeInfo::remove_child (Volume *) inline
References UG_THROW.
replace_child() [1/2]
void ug::MGEdgeInfo::replace_child (Edge * elem, Edge * child) inline
References ug::ArrayReplaceEntry(), m_numEdgeChildren, and m_pEdgeChild.
replace_child() [2/2]
void ug::MGEdgeInfo::replace_child (Vertex * elem, Vertex * child) inline
References m_pVrtChild.
unregister_from_children()
void ug::MGEdgeInfo::unregister_from_children (MultiGrid & mg)
References clear_children(), m_numEdgeChildren, m_pEdgeChild, m_pVrtChild, and ug::MultiGrid::set_parent().
Member Data Documentation
m_numEdgeChildren
byte ug::MGEdgeInfo::m_numEdgeChildren private
Referenced by add_child(), clear_children(), has_children(), num_child_edges(), remove_child(), replace_child(), and unregister_from_children().
m_pEdgeChild
Edge* ug::MGEdgeInfo::m_pEdgeChild[MG_EDGE_MAX_EDGE_CHILDREN] private
Referenced by add_child(), child_edge(), remove_child(), replace_child(), and unregister_from_children().
m_pParent
GridObject* ug::MGEdgeInfo::m_pParent
m_pVrtChild
Vertex* ug::MGEdgeInfo::m_pVrtChild private
Referenced by add_child(), child_vertex(), clear_children(), has_children(), num_child_vertices(), remove_child(), replace_child(), and unregister_from_children().
The documentation for this struct was generated from the following files:
ugbase/lib_grid/multi_grid_child_info.h
ugbase/lib_grid/multi_grid.cpp