ug4: ug::impl::LuaTableHandle_ Struct Reference
ug::impl::LuaTableHandle_ Struct Reference
Public Member Functions
ug::Variant get (int const &key) const
ug::Variant get (std::string const &key) const
LuaTableHandle_ (lua_State *, int)
bool operator!= (LuaTableHandle_ const &o) const
bool operator== (LuaTableHandle_ const &o) const
size_t size () const
~LuaTableHandle_ ()
Static Public Member Functions
static void attach (LuaTableHandle_ *c, LuaTableHandle_ **to)
static void detach (LuaTableHandle_ **from)
Public Attributes
int _index {0}
lua_State * _L {nullptr}
int _ref {0}
Private Attributes
int _attach_count {0}
Constructor & Destructor Documentation
LuaTableHandle_()
ug::impl::LuaTableHandle_::LuaTableHandle_ (lua_State * L, int index)
References _attach_count, _index, _L, and _ref.
~LuaTableHandle_()
ug::impl::LuaTableHandle_::~LuaTableHandle_ ()
References _attach_count, _L, _ref, and untested.
Member Function Documentation
attach()
static void ug::impl::LuaTableHandle_::attach (LuaTableHandle_ * c, LuaTableHandle_ ** to) inline static
References _attach_count, detach(), and untested.
Referenced by ug::LuaTableHandle::LuaTableHandle(), and ug::LuaTableHandle::operator=().
detach()
static void ug::impl::LuaTableHandle_::detach (LuaTableHandle_ ** from) inline static
References untested.
Referenced by attach(), ug::LuaTableHandle::LuaTableHandle(), ug::LuaTableHandle::operator=(), and ug::LuaTableHandle::~LuaTableHandle().
get() [1/2]
ug::Variant ug::impl::LuaTableHandle_::get (int const & key) const inline
References _index, _L, _ref, and ug::impl::pop2var().
Referenced by ug::LuaTableHandle::get().
get() [2/2]
ug::Variant ug::impl::LuaTableHandle_::get (std::string const & key) const inline
References _index, _L, _ref, and ug::impl::pop2var().
operator!=()
bool ug::impl::LuaTableHandle_::operator!= (LuaTableHandle_ const & o) const inline
References operator==().
operator==()
bool ug::impl::LuaTableHandle_::operator== (LuaTableHandle_ const & o) const inline
References _ref.
Referenced by operator!=().
size()
size_t ug::impl::LuaTableHandle_::size () const inline
References _index, _L, and untested.
Referenced by ug::LuaTableHandle::size().
Member Data Documentation
_attach_count
int ug::impl::LuaTableHandle_::_attach_count {0} private
Referenced by attach(), LuaTableHandle_(), and ~LuaTableHandle_().
_index
int ug::impl::LuaTableHandle_::_index {0}
Referenced by get(), LuaTableHandle_(), and size().
_L
lua_State* ug::impl::LuaTableHandle_::_L {nullptr}
Referenced by get(), LuaTableHandle_(), size(), and ~LuaTableHandle_().
_ref
int ug::impl::LuaTableHandle_::_ref {0}
Referenced by get(), LuaTableHandle_(), operator==(), and ~LuaTableHandle_().
The documentation for this struct was generated from the following file:
ugbase/bindings/lua/lua_table_handle.cpp