ug4: ug::Partitioner_DynamicBisection< TElem, dim >::ElemList Struct Reference
ug::Partitioner_DynamicBisection< TElem, dim >::ElemList Struct Reference
Public Member Functions
void add (size_t entryInd)
void clear ()
elem_t * elem (size_t entryInd) const
ElemList ()
ElemList (std::vector< Entry > *entries)
bool empty () const
std::vector< Entry > * entries ()
size_t first () const
size_t last () const
size_t next (size_t entryInd) const
void set_entry_list (std::vector< Entry > *entries)
size_t size () const
Private Attributes
std::vector< Entry > * m_entries
size_t m_first
size_t m_last
size_t m_num
Constructor & Destructor Documentation
ElemList() [1/2]
template<class TElem , int dim> ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::ElemList () inline
ElemList() [2/2]
template<class TElem , int dim> ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::ElemList (std::vector< Entry > * entries) inline
Member Function Documentation
add()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::add (size_t entryInd) inline
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_first, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_last, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_num, and ug::Partitioner_DynamicBisection< TElem, dim >::s_invalidIndex.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), and ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection().
clear()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::clear () inline
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_first, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_last, ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_num, and ug::Partitioner_DynamicBisection< TElem, dim >::s_invalidIndex.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), and ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection().
elem()
template<class TElem , int dim> elem_t* ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::elem (size_t entryInd) const inline
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_entries.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::Partitioner_DynamicBisection< TElem, dim >::control_bisection(), and ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values().
empty()
template<class TElem , int dim> bool ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::empty () const inline
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_num.
entries()
template<class TElem , int dim> std::vector<Entry>* ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::entries () inline
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_entries.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::set_entry_list().
first()
template<class TElem , int dim> size_t ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::first () const inline
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_first.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::Partitioner_DynamicBisection< TElem, dim >::control_bisection(), and ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values().
last()
template<class TElem , int dim> size_t ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::last () const inline
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_last.
next()
template<class TElem , int dim> size_t ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::next (size_t entryInd) const inline
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_entries.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::bisect_elements(), ug::Partitioner_DynamicBisection< TElem, dim >::calculate_global_dimensions(), ug::Partitioner_DynamicBisection< TElem, dim >::control_bisection(), and ug::Partitioner_DynamicBisection< TElem, dim >::improve_split_values().
set_entry_list()
template<class TElem , int dim> void ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::set_entry_list (std::vector< Entry > * entries) inline
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::entries(), and ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_entries.
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::control_bisection(), and ug::Partitioner_DynamicBisection< TElem, dim >::perform_bisection().
size()
template<class TElem , int dim> size_t ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::size () const inline
References ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_num.
Member Data Documentation
m_entries
template<class TElem , int dim> std::vector<Entry>* ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_entries private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::elem(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::entries(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::next(), and ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::set_entry_list().
m_first
template<class TElem , int dim> size_t ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_first private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::add(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::clear(), and ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::first().
m_last
template<class TElem , int dim> size_t ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_last private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::add(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::clear(), and ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::last().
m_num
template<class TElem , int dim> size_t ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::m_num private
Referenced by ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::add(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::clear(), ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::empty(), and ug::Partitioner_DynamicBisection< TElem, dim >::ElemList::size().
The documentation for this struct was generated from the following file:
ugbase/lib_grid/parallelization/partitioner_dynamic_bisection.h