ug4: ug::attachment_io_traits< TAttachment > Struct Template Reference
ug::attachment_io_traits< TAttachment > Struct Template Reference
#include <attachment_io_traits.h>
Public Types
typedef attachment_value_traits< value_type >::const_reference const_reference_type
typedef attachment_value_traits< value_type >::reference reference_type
typedef TAttachment::ValueType value_type
Static Public Member Functions
static void read_value (std::istream &in, reference_type v)
static void write_value (std::ostream &out, const_reference_type v)
Member Typedef Documentation
const_reference_type
template<class TAttachment > typedef attachment_value_traits<value_type>::const_reference ug::attachment_io_traits< TAttachment >::const_reference_type
reference_type
template<class TAttachment > typedef attachment_value_traits<value_type>::reference ug::attachment_io_traits< TAttachment >::reference_type
value_type
template<class TAttachment > typedef TAttachment::ValueType ug::attachment_io_traits< TAttachment >::value_type
Member Function Documentation
read_value()
template<class TAttachment > static void ug::attachment_io_traits< TAttachment >::read_value (std::istream & in, reference_type v) inline static
Referenced by ug::GlobalAttachments::read_attachment_from_stream(), and ug::attachment_io_traits< Attachment< std::vector< T > > >::read_value().
write_value()
template<class TAttachment > static void ug::attachment_io_traits< TAttachment >::write_value (std::ostream & out, const_reference_type v) inline static
Referenced by ug::GridWriterUGX::add_attachment(), ug::GlobalAttachments::write_attachment_to_stream(), and ug::attachment_io_traits< Attachment< std::vector< T > > >::write_value().
The documentation for this struct was generated from the following file:
ugbase/lib_grid/attachments/attachment_io_traits.h