ug4: ug::GlobalAttachments::IFunctionEntry Struct Reference
ug::GlobalAttachments::IFunctionEntry Struct Reference
Public Member Functions
IFunctionEntry ()
Public Attributes
void(* addSerializer)(GridDataSerializationHandler &, Grid &, IAttachment &)
void(* attach)(Grid &, IAttachment &)
void(* readFunc)(std::istream &, Grid &, IAttachment &)
void(* writeFunc)(std::ostream &, Grid &, IAttachment &)
Constructor & Destructor Documentation
IFunctionEntry()
ug::GlobalAttachments::IFunctionEntry::IFunctionEntry () inline
Member Data Documentation
addSerializer
void(* ug::GlobalAttachments::IFunctionEntry::addSerializer) (GridDataSerializationHandler &, Grid &, IAttachment &)
Referenced by ug::GlobalAttachments::add_data_serializer(), and ug::GlobalAttachments::FunctionEntry< TElem, TAttachment >::FunctionEntry().
attach
void(* ug::GlobalAttachments::IFunctionEntry::attach) (Grid &, IAttachment &)
Referenced by ug::GlobalAttachments::attach(), and ug::GlobalAttachments::FunctionEntry< TElem, TAttachment >::FunctionEntry().
readFunc
void(* ug::GlobalAttachments::IFunctionEntry::readFunc) (std::istream &, Grid &, IAttachment &)
Referenced by ug::GlobalAttachments::FunctionEntry< TElem, TAttachment >::FunctionEntry(), and ug::GlobalAttachments::read_attachment_values().
writeFunc
void(* ug::GlobalAttachments::IFunctionEntry::writeFunc) (std::ostream &, Grid &, IAttachment &)
Referenced by ug::GlobalAttachments::FunctionEntry< TElem, TAttachment >::FunctionEntry().
The documentation for this struct was generated from the following file:
ugbase/lib_grid/global_attachments.h