ug4: ug::fv1_traits_ReferenceVolume Struct Reference
ug::fv1_traits_ReferenceVolume Struct Reference
#include <fv_util.h>
Public Types
typedef ReferenceQuadrilateral bf_type
typedef ReferenceHexahedron scv_type
typedef ReferenceQuadrilateral scvf_type
Static Public Member Functions
static void NormalOnBF (MathVector< 3 > &outNormal, const MathVector< 3 > *vSCVFCorner, const MathVector< 3 > *vElemCorner)
static void NormalOnSCVF (MathVector< 3 > &outNormal, const MathVector< 3 > *vSCVFCorner, const MathVector< 3 > *vElemCorner)
Static Public Attributes
static const size_t maxNSH = 8
static const size_t maxNumSCV = 32
static const size_t maxNumSCVF = 24
static const size_t NumCornersOfBF = 4
static const size_t NumCornersOfSCV = 8
static const size_t NumCornersOfSCVF = 4
Member Typedef Documentation
bf_type
typedef ReferenceQuadrilateral ug::fv1_traits_ReferenceVolume::bf_type
scv_type
typedef ReferenceHexahedron ug::fv1_traits_ReferenceVolume::scv_type
scvf_type
typedef ReferenceQuadrilateral ug::fv1_traits_ReferenceVolume::scvf_type
Member Function Documentation
NormalOnBF()
static void ug::fv1_traits_ReferenceVolume::NormalOnBF (MathVector< 3 > & outNormal, const MathVector< 3 > * vSCVFCorner, const MathVector< 3 > * vElemCorner) inline static
References NormalOnSCVF().
NormalOnSCVF()
static void ug::fv1_traits_ReferenceVolume::NormalOnSCVF (MathVector< 3 > & outNormal, const MathVector< 3 > * vSCVFCorner, const MathVector< 3 > * vElemCorner) inline static
References ug::ElementNormal< ReferenceQuadrilateral, 3 >().
Referenced by NormalOnBF().
Member Data Documentation
maxNSH
const size_t ug::fv1_traits_ReferenceVolume::maxNSH = 8 static
maxNumSCV
const size_t ug::fv1_traits_ReferenceVolume::maxNumSCV = 32 static
maxNumSCVF
const size_t ug::fv1_traits_ReferenceVolume::maxNumSCVF = 24 static
NumCornersOfBF
const size_t ug::fv1_traits_ReferenceVolume::NumCornersOfBF = 4 static
NumCornersOfSCV
const size_t ug::fv1_traits_ReferenceVolume::NumCornersOfSCV = 8 static
NumCornersOfSCVF
const size_t ug::fv1_traits_ReferenceVolume::NumCornersOfSCVF = 4 static
The documentation for this struct was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv_util.h