ug4: ug::std_number_vector_attachment_reduce_traits Struct Reference
ug::std_number_vector_attachment_reduce_traits Struct Reference
#include <compol_attachment_reduce.h>
Public Types
typedef std::vector< number > value_t
Static Public Member Functions
static value_t band (value_t v1, value_t v2)
static value_t bor (value_t v1, value_t v2)
static void check_length (value_t &v1, value_t &v2)
static value_t land (value_t v1, value_t v2)
static value_t lor (value_t v1, value_t v2)
static value_t max (value_t v1, value_t v2)
static value_t min (value_t v1, value_t v2)
static value_t prod (value_t v1, value_t v2)
static value_t sum (value_t v1, value_t v2)
Member Typedef Documentation
value_t
typedef std::vector<number> ug::std_number_vector_attachment_reduce_traits::value_t
Member Function Documentation
band()
static value_t ug::std_number_vector_attachment_reduce_traits::band (value_t v1, value_t v2) inline static
References UG_THROW.
bor()
static value_t ug::std_number_vector_attachment_reduce_traits::bor (value_t v1, value_t v2) inline static
References UG_THROW.
check_length()
static void ug::std_number_vector_attachment_reduce_traits::check_length (value_t & v1, value_t & v2) inline static
Referenced by land(), lor(), max(), min(), prod(), and sum().
land()
static value_t ug::std_number_vector_attachment_reduce_traits::land (value_t v1, value_t v2) inline static
References check_length().
lor()
static value_t ug::std_number_vector_attachment_reduce_traits::lor (value_t v1, value_t v2) inline static
References check_length().
max()
static value_t ug::std_number_vector_attachment_reduce_traits::max (value_t v1, value_t v2) inline static
References check_length().
min()
static value_t ug::std_number_vector_attachment_reduce_traits::min (value_t v1, value_t v2) inline static
References check_length().
prod()
static value_t ug::std_number_vector_attachment_reduce_traits::prod (value_t v1, value_t v2) inline static
References check_length().
sum()
static value_t ug::std_number_vector_attachment_reduce_traits::sum (value_t v1, value_t v2) inline static
References check_length().
The documentation for this struct was generated from the following file:
ugbase/lib_grid/parallelization/util/compol_attachment_reduce.h