ug4: ug::fv1_traits< ReferenceEdge, 1 > Struct Template Reference
ug::fv1_traits< ReferenceEdge, 1 > Struct Template Reference
#include <fv_util.h>
Static Public Member Functions
static void NormalOnBF (MathVector< 1 > &outNormal, const MathVector< 1 > *vSCVFCorner, const MathVector< 1 > *vElemCorner)
static void NormalOnSCVF (MathVector< 1 > &outNormal, const MathVector< 1 > *vSCVFCorner, const MathVector< 1 > *vElemCorner)
Additional Inherited Members
Public Types inherited from ug::fv1_traits_ReferenceEdge
typedef ReferenceVertex bf_type
typedef ReferenceEdge scv_type
typedef ReferenceVertex scvf_type
Static Public Attributes inherited from ug::fv1_traits_ReferenceEdge
static const size_t maxNSH = maxNumSCV
static const size_t maxNumSCV = 2
static const size_t maxNumSCVF = 1
static const size_t NumCornersOfBF = 1
static const size_t NumCornersOfSCV = 2
static const size_t NumCornersOfSCVF = 1
Member Function Documentation
static void ug::fv1_traits< ReferenceEdge, 1 >::NormalOnBF (MathVector< 1 > & outNormal, const MathVector< 1 > * vSCVFCorner, const MathVector< 1 > * vElemCorner) inline static
References ug::fv1_traits< TRefElem, TWorldDim >::NormalOnSCVF().
static void ug::fv1_traits< ReferenceEdge, 1 >::NormalOnSCVF (MathVector< 1 > & outNormal, const MathVector< 1 > * vSCVFCorner, const MathVector< 1 > * vElemCorner) inline static
References ug::ElementNormal< ReferenceVertex, 1 >(), and ug::VecNormalize().
The documentation for this struct was generated from the following file:
ugbase/lib_disc/spatial_disc/disc_util/fv_util.h