ug4: ugbase/common/util/variant.cpp File Reference
variant.cpp File Reference
#include "common/error.h"
#include "variant.h"
#include <iostream>
Namespaces
ug
the ug namespace
Macros
#define untested()
Functions
std::ostream & operator<< (std::ostream &outStream, const ug::Variant &v)
Macro Definition Documentation
untested
#define untested ()
Value:
          ( std::cerr <<  "@@#\n@@@:"<< __FILE__ << ":"<< __LINE__ \
          <<":" << __func__ << "\n" )
Function Documentation
operator<<()
std::ostream& operator<< (std::ostream & outStream, const ug::Variant & v)
References ug::Variant::to_bool(), ug::Variant::to_c_string(), ug::Variant::to_double(), ug::Variant::to_float(), ug::Variant::to_int(), ug::Variant::to_size_t(), ug::Variant::to_std_string(), ug::Variant::type(), ug::Variant::VT_BOOL, ug::Variant::VT_CSTRING, ug::Variant::VT_DOUBLE, ug::Variant::VT_FLOAT, ug::Variant::VT_INT, ug::Variant::VT_SIZE_T, and ug::Variant::VT_STDSTRING.