ug4: ugbase/common/util/variant.h File Reference
variant.h File Reference
#include <string>
#include "smart_pointer.h"
#include "common/types.h"
#include "common/ug_config.h"
Classes
class ug::Variant
A variant can represent variables of different types.
Namespaces
ug
the ug namespace
Functions
UG_API std::ostream & operator<< (std::ostream &outStream, const ug::Variant &v)
const std::string & ug::Variant::to< const std::string & > () const
std::string ug::Variant::to< std::string > () const
Variant::Type ug::Variant::type< const std::string & > ()
Variant::Type ug::Variant::type< std::string > ()
Function Documentation
UG_API std::ostream& operator<< (std::ostream & outStream, const ug::Variant & v)
References ug::Variant::to_bool(), ug::Variant::to_c_string(), ug::Variant::to_double(), ug::Variant::to_float(), ug::Variant::to_int(), ug::Variant::to_size_t(), ug::Variant::to_std_string(), ug::Variant::type(), ug::Variant::VT_BOOL, ug::Variant::VT_CSTRING, ug::Variant::VT_DOUBLE, ug::Variant::VT_FLOAT, ug::Variant::VT_INT, ug::Variant::VT_SIZE_T, and ug::Variant::VT_STDSTRING.