var searchData=
[
  ['natedgeinfo_19033',['NatEdgeInfo',['../structug_1_1_dim_h_f_v1_geometry_1_1_nat_edge_info.html',1,'ug::DimHFV1Geometry&lt; TDim, TWorldDim &gt;::NatEdgeInfo'],['../structug_1_1_h_f_v1_geometry_1_1_nat_edge_info.html',1,'ug::HFV1Geometry&lt; TElem, TWorldDim &gt;::NatEdgeInfo'],['../structug_1_1_h_f_v1_manifold_geometry_1_1_nat_edge_info.html',1,'ug::HFV1ManifoldGeometry&lt; TElem, TWorldDim &gt;::NatEdgeInfo']]],
  ['nativcmpinfo_19034',['NativCmpInfo',['../structug_1_1_composite_conv_check_1_1_nativ_cmp_info.html',1,'ug::CompositeConvCheck']]],
  ['nativecuthillmckeeordering_19035',['NativeCuthillMcKeeOrdering',['../classug_1_1_native_cuthill_mc_kee_ordering.html',1,'ug']]],
  ['navierstokesbase_19036',['NavierStokesBase',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_base.html',1,'ug::NavierStokes']]],
  ['navierstokesfe_19037',['NavierStokesFE',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_f_e.html',1,'ug::NavierStokes']]],
  ['navierstokesfieldsstabilization_19038',['NavierStokesFIELDSStabilization',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_f_i_e_l_d_s_stabilization.html',1,'ug::NavierStokes']]],
  ['navierstokesflowstabilization_19039',['NavierStokesFLOWStabilization',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_f_l_o_w_stabilization.html',1,'ug::NavierStokes']]],
  ['navierstokesfullupwind_19040',['NavierStokesFullUpwind',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_full_upwind.html',1,'ug::NavierStokes']]],
  ['navierstokesfv_19041',['NavierStokesFV',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_f_v.html',1,'ug::NavierStokes']]],
  ['navierstokesfv1_19042',['NavierStokesFV1',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_f_v1.html',1,'ug::NavierStokes']]],
  ['navierstokesfv1withoutstabilization_19043',['NavierStokesFV1WithoutStabilization',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_f_v1_without_stabilization.html',1,'ug::NavierStokes']]],
  ['navierstokesfvcr_19044',['NavierStokesFVCR',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_f_v_c_r.html',1,'ug::NavierStokes']]],
  ['navierstokesinflowbase_19045',['NavierStokesInflowBase',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_inflow_base.html',1,'ug::NavierStokes']]],
  ['navierstokesinflowfe_19046',['NavierStokesInflowFE',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_e.html',1,'ug::NavierStokes']]],
  ['navierstokesinflowfv_19047',['NavierStokesInflowFV',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_v.html',1,'ug::NavierStokes']]],
  ['navierstokesinflowfv1_19048',['NavierStokesInflowFV1',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_v1.html',1,'ug::NavierStokes']]],
  ['navierstokesinflowfvcr_19049',['NavierStokesInflowFVCR',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_v_c_r.html',1,'ug::NavierStokes']]],
  ['navierstokeslinearprofileskewedupwind_19050',['NavierStokesLinearProfileSkewedUpwind',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_linear_profile_skewed_upwind.html',1,'ug::NavierStokes']]],
  ['navierstokesnonormalstressoutflowbase_19051',['NavierStokesNoNormalStressOutflowBase',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_base.html',1,'ug::NavierStokes']]],
  ['navierstokesnonormalstressoutflowfv_19052',['NavierStokesNoNormalStressOutflowFV',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_f_v.html',1,'ug::NavierStokes']]],
  ['navierstokesnonormalstressoutflowfv1_19053',['NavierStokesNoNormalStressOutflowFV1',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_f_v1.html',1,'ug::NavierStokes']]],
  ['navierstokesnonormalstressoutflowfvcr_19054',['NavierStokesNoNormalStressOutflowFVCR',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_f_v_c_r.html',1,'ug::NavierStokes']]],
  ['navierstokesnoupwind_19055',['NavierStokesNoUpwind',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_no_upwind.html',1,'ug::NavierStokes']]],
  ['navierstokespositiveupwind_19056',['NavierStokesPositiveUpwind',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_positive_upwind.html',1,'ug::NavierStokes']]],
  ['navierstokesregularupwind_19057',['NavierStokesRegularUpwind',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_regular_upwind.html',1,'ug::NavierStokes']]],
  ['navierstokesskewedupwind_19058',['NavierStokesSkewedUpwind',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_skewed_upwind.html',1,'ug::NavierStokes']]],
  ['navierstokessymbcfv1_19059',['NavierStokesSymBCFV1',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_sym_b_c_f_v1.html',1,'ug::NavierStokes']]],
  ['navierstokesupwindregister_19060',['NavierStokesUpwindRegister',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'ug::NavierStokes']]],
  ['navierstokesupwindregister_3c_20crfvgeometry_2c_20dim_2c_20navierstokesfullupwind_3c_20dim_20_3e_20_3e_19061',['NavierStokesUpwindRegister&lt; CRFVGeometry, dim, NavierStokesFullUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokesupwindregister_3c_20crfvgeometry_2c_20dim_2c_20navierstokeslinearprofileskewedupwind_3c_20dim_20_3e_20_3e_19062',['NavierStokesUpwindRegister&lt; CRFVGeometry, dim, NavierStokesLinearProfileSkewedUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokesupwindregister_3c_20crfvgeometry_2c_20dim_2c_20navierstokesnoupwind_3c_20dim_20_3e_20_3e_19063',['NavierStokesUpwindRegister&lt; CRFVGeometry, dim, NavierStokesNoUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokesupwindregister_3c_20crfvgeometry_2c_20dim_2c_20navierstokesskewedupwind_3c_20dim_20_3e_20_3e_19064',['NavierStokesUpwindRegister&lt; CRFVGeometry, dim, NavierStokesSkewedUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokesupwindregister_3c_20fv1geometry_2c_20dim_2c_20navierstokesfullupwind_3c_20dim_20_3e_20_3e_19065',['NavierStokesUpwindRegister&lt; FV1Geometry, dim, NavierStokesFullUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokesupwindregister_3c_20fv1geometry_2c_20dim_2c_20navierstokeslinearprofileskewedupwind_3c_20dim_20_3e_20_3e_19066',['NavierStokesUpwindRegister&lt; FV1Geometry, dim, NavierStokesLinearProfileSkewedUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokesupwindregister_3c_20fv1geometry_2c_20dim_2c_20navierstokesnoupwind_3c_20dim_20_3e_20_3e_19067',['NavierStokesUpwindRegister&lt; FV1Geometry, dim, NavierStokesNoUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokesupwindregister_3c_20fv1geometry_2c_20dim_2c_20navierstokespositiveupwind_3c_20dim_20_3e_20_3e_19068',['NavierStokesUpwindRegister&lt; FV1Geometry, dim, NavierStokesPositiveUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokesupwindregister_3c_20fv1geometry_2c_20dim_2c_20navierstokesregularupwind_3c_20dim_20_3e_20_3e_19069',['NavierStokesUpwindRegister&lt; FV1Geometry, dim, NavierStokesRegularUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokesupwindregister_3c_20fv1geometry_2c_20dim_2c_20navierstokesskewedupwind_3c_20dim_20_3e_20_3e_19070',['NavierStokesUpwindRegister&lt; FV1Geometry, dim, NavierStokesSkewedUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokesupwindregister_3c_20hcrfvgeometry_2c_20dim_2c_20navierstokesfullupwind_3c_20dim_20_3e_20_3e_19071',['NavierStokesUpwindRegister&lt; HCRFVGeometry, dim, NavierStokesFullUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokesupwindregister_3c_20hcrfvgeometry_2c_20dim_2c_20navierstokesnoupwind_3c_20dim_20_3e_20_3e_19072',['NavierStokesUpwindRegister&lt; HCRFVGeometry, dim, NavierStokesNoUpwind&lt; dim &gt; &gt;',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html',1,'']]],
  ['navierstokeswall_19073',['NavierStokesWall',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_wall.html',1,'ug::NavierStokes']]],
  ['navierstokeswsbcfv1_19074',['NavierStokesWSBCFV1',['../../plugins/classug_1_1_navier_stokes_1_1_navier_stokes_w_s_b_c_f_v1.html',1,'ug::NavierStokes']]],
  ['nedeleccurldata_19075',['NedelecCurlData',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_curl_data.html',1,'ug::Electromagnetism']]],
  ['nedelecdirichletbc_19076',['NedelecDirichletBC',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_dirichlet_b_c.html',1,'ug::Electromagnetism']]],
  ['nedelecgridfunctiondata_19077',['NedelecGridFunctionData',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_grid_function_data.html',1,'ug::Electromagnetism']]],
  ['nedelecinterpolation_19078',['NedelecInterpolation',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_interpolation.html',1,'ug::Electromagnetism']]],
  ['nedelecinterpolation_3c_20tdomain_2c_202_2c_202_20_3e_19079',['NedelecInterpolation&lt; TDomain, 2, 2 &gt;',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_interpolation_3_01_t_domain_00_012_00_012_01_4.html',1,'ug::Electromagnetism']]],
  ['nedelecinterpolation_3c_20tdomain_2c_203_2c_203_20_3e_19080',['NedelecInterpolation&lt; TDomain, 3, 3 &gt;',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_interpolation_3_01_t_domain_00_013_00_013_01_4.html',1,'ug::Electromagnetism']]],
  ['nedeleclds_19081',['NedelecLDS',['../classug_1_1_nedelec_l_d_s.html',1,'ug']]],
  ['nedeleclds_3c_20referencetetrahedron_20_3e_19082',['NedelecLDS&lt; ReferenceTetrahedron &gt;',['../classug_1_1_nedelec_l_d_s.html',1,'ug']]],
  ['nedeleclds_3c_20referencetriangle_20_3e_19083',['NedelecLDS&lt; ReferenceTriangle &gt;',['../classug_1_1_nedelec_l_d_s.html',1,'ug']]],
  ['nedelecloopcurrent_19084',['NedelecLoopCurrent',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_loop_current.html',1,'ug::Electromagnetism']]],
  ['nedeleclsfs_19085',['NedelecLSFS',['../classug_1_1_nedelec_l_s_f_s.html',1,'ug']]],
  ['nedeleclsfs_3c_20referencetetrahedron_20_3e_19086',['NedelecLSFS&lt; ReferenceTetrahedron &gt;',['../classug_1_1_nedelec_l_s_f_s_3_01_reference_tetrahedron_01_4.html',1,'ug']]],
  ['nedeleclsfs_3c_20referencetriangle_20_3e_19087',['NedelecLSFS&lt; ReferenceTriangle &gt;',['../classug_1_1_nedelec_l_s_f_s_3_01_reference_triangle_01_4.html',1,'ug']]],
  ['nedelecproject_19088',['NedelecProject',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_project.html',1,'ug::Electromagnetism']]],
  ['nedelecprolongationmatrixhelper_19089',['NedelecProlongationMatrixHelper',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_prolongation_matrix_helper.html',1,'ug::Electromagnetism']]],
  ['nedelecprolongationmatrixhelper_3c_20tdomain_2c_20talgebra_2c_20regularedge_20_3e_19090',['NedelecProlongationMatrixHelper&lt; TDomain, TAlgebra, RegularEdge &gt;',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_prolongation_matrix_helper_3_01_t_domain_00_01_t_algebra_00_01_regular_edge_01_4.html',1,'ug::Electromagnetism']]],
  ['nedelecsigmaedata_19091',['NedelecSigmaEData',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_sigma_e_data.html',1,'ug::Electromagnetism']]],
  ['nedelect1_5fldisc_19092',['NedelecT1_LDisc',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc.html',1,'ug::Electromagnetism']]],
  ['nedelect1_5fldisc_3c_20tdomain_2c_20tetrahedron_20_3e_19093',['NedelecT1_LDisc&lt; TDomain, Tetrahedron &gt;',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc_3_01_t_domain_00_01_tetrahedron_01_4.html',1,'ug::Electromagnetism']]],
  ['nedelect1_5fldisc_3c_20tdomain_2c_20triangle_20_3e_19094',['NedelecT1_LDisc&lt; TDomain, Triangle &gt;',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc_3_01_t_domain_00_01_triangle_01_4.html',1,'ug::Electromagnetism']]],
  ['nedelect1_5fldisc_5fforsimplex_19095',['NedelecT1_LDisc_forSimplex',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc__for_simplex.html',1,'ug::Electromagnetism']]],
  ['nedelect1_5fldisc_5fforsimplex_3c_20tdomain_2c_20tetrahedron_20_3e_19096',['NedelecT1_LDisc_forSimplex&lt; TDomain, Tetrahedron &gt;',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc__for_simplex.html',1,'']]],
  ['nedelect1_5fldisc_5fforsimplex_3c_20tdomain_2c_20triangle_20_3e_19097',['NedelecT1_LDisc_forSimplex&lt; TDomain, Triangle &gt;',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc__for_simplex.html',1,'']]],
  ['nedelectransfer_19098',['NedelecTransfer',['../../plugins/classug_1_1_electromagnetism_1_1_nedelec_transfer.html',1,'ug::Electromagnetism']]],
  ['neighborinfo_19099',['NeighborInfo',['../structug_1_1_subdiv_rules___p_loop_1_1_neighbor_info.html',1,'ug::SubdivRules_PLoop']]],
  ['nestediterationsolver_19100',['NestedIterationSolver',['../classug_1_1_nested_iteration_solver.html',1,'ug']]],
  ['neumannboundarybase_19101',['NeumannBoundaryBase',['../classug_1_1_neumann_boundary_base.html',1,'ug']]],
  ['neumannboundaryfe_19102',['NeumannBoundaryFE',['../classug_1_1_neumann_boundary_f_e.html',1,'ug']]],
  ['neumannboundaryfv_19103',['NeumannBoundaryFV',['../classug_1_1_neumann_boundary_f_v.html',1,'ug']]],
  ['neumannboundaryfv1_19104',['NeumannBoundaryFV1',['../classug_1_1_neumann_boundary_f_v1.html',1,'ug']]],
  ['neurite_19105',['Neurite',['../structug_1_1_neurite_projector_1_1_neurite.html',1,'ug::NeuriteProjector']]],
  ['neuriteprojector_19106',['NeuriteProjector',['../classug_1_1_neurite_projector.html',1,'ug']]],
  ['newedgeinfo_19107',['NewEdgeInfo',['../structug_1_1_dim_h_f_v1_geometry_1_1_new_edge_info.html',1,'ug::DimHFV1Geometry&lt; TDim, TWorldDim &gt;::NewEdgeInfo'],['../structug_1_1_h_f_v1_geometry_1_1_new_edge_info.html',1,'ug::HFV1Geometry&lt; TElem, TWorldDim &gt;::NewEdgeInfo'],['../structug_1_1_h_f_v1_manifold_geometry_1_1_new_edge_info.html',1,'ug::HFV1ManifoldGeometry&lt; TElem, TWorldDim &gt;::NewEdgeInfo']]],
  ['newlayoutcreator_19108',['NewLayoutCreator',['../classug_1_1_new_layout_creator.html',1,'ug']]],
  ['newslavenotification_19109',['NewSlaveNotification',['../structug_1_1_new_layout_creator_1_1_new_slave_notification.html',1,'ug::NewLayoutCreator::NewSlaveNotification'],['../structug_1_1_parallel_nodes_1_1_new_slave_notification.html',1,'ug::ParallelNodes::NewSlaveNotification']]],
  ['newtoncotes_19110',['NewtonCotes',['../classug_1_1_newton_cotes.html',1,'ug']]],
  ['newtonsolver_19111',['NewtonSolver',['../classug_1_1_newton_solver.html',1,'ug']]],
  ['nlgaussseidelsolver_19112',['NLGaussSeidelSolver',['../classug_1_1_n_l_gauss_seidel_solver.html',1,'ug']]],
  ['nljacobisolver_19113',['NLJacobiSolver',['../classug_1_1_n_l_jacobi_solver.html',1,'ug']]],
  ['node_19114',['Node',['../structug_1_1_k_d_tree_1_1_node.html',1,'ug::KDTree&lt; point_t, data_t, real_t &gt;::Node'],['../classug_1_1_k_d_tree_static_1_1_node.html',1,'ug::KDTreeStatic&lt; TPositionAttachment, numDimensions, TVector &gt;::Node'],['../classug_1_1node__tree_1_1_node.html',1,'ug::node_tree::Node'],['../structug_1_1ntree_1_1_node.html',1,'ug::ntree&lt; tree_dim, world_dim, TElem, TCommonData &gt;::Node']]],
  ['nodetype_19115',['nodeType',['../structnode_type.html',1,'']]],
  ['non_5fdirichlet_5fiterator_19116',['non_dirichlet_iterator',['../classug_1_1non__dirichlet__iterator.html',1,'ug']]],
  ['nonallowedname1_19117',['NonAllowedName1',['../classug_1_1bridge_1_1_non_allowed_name1.html',1,'ug::bridge']]],
  ['nonallowedname2_19118',['NonAllowedName2',['../classug_1_1bridge_1_1_non_allowed_name2.html',1,'ug::bridge']]],
  ['nonallowedname3_19119',['NonAllowedName3',['../classug_1_1bridge_1_1_non_allowed_name3.html',1,'ug::bridge']]],
  ['nonallowedname4_19120',['NonAllowedName4',['../classug_1_1bridge_1_1_non_allowed_name4.html',1,'ug::bridge']]],
  ['norm2estimator_19121',['Norm2Estimator',['../../plugins/classug_1_1_norm2_estimator.html',1,'ug']]],
  ['norminfestimator_19122',['NormInfEstimator',['../../plugins/classug_1_1_norm_inf_estimator.html',1,'ug']]],
  ['normrelestimator_19123',['NormRelEstimator',['../../plugins/classug_1_1_norm_rel_estimator.html',1,'ug']]],
  ['ntree_19124',['ntree',['../classug_1_1ntree.html',1,'ug']]],
  ['ntree_3c_20tree_5fdim_2c_20world_5fdim_2c_20grid_5felem_5ft_20_2a_2c_20ntreegriddata_3c_20world_5fdim_20_3e_20_3e_19125',['ntree&lt; tree_dim, world_dim, grid_elem_t *, NTreeGridData&lt; world_dim &gt; &gt;',['../classug_1_1ntree.html',1,'ug']]],
  ['ntree_5ftraits_19126',['ntree_traits',['../structug_1_1ntree__traits.html',1,'ug']]],
  ['ntree_5ftraits_3c_201_2c_201_2c_20elem_5ft_2c_20ntreegriddata_3c_201_20_3e_20_3e_19127',['ntree_traits&lt; 1, 1, elem_t, NTreeGridData&lt; 1 &gt; &gt;',['../structug_1_1ntree__traits_3_011_00_011_00_01elem__t_00_01_n_tree_grid_data_3_011_01_4_01_4.html',1,'ug']]],
  ['ntree_5ftraits_3c_201_2c_202_2c_20elem_5ft_2c_20ntreegriddata_3c_202_20_3e_20_3e_19128',['ntree_traits&lt; 1, 2, elem_t, NTreeGridData&lt; 2 &gt; &gt;',['../structug_1_1ntree__traits_3_011_00_012_00_01elem__t_00_01_n_tree_grid_data_3_012_01_4_01_4.html',1,'ug']]],
  ['ntree_5ftraits_3c_202_2c_202_2c_20elem_5ft_2c_20ntreegriddata_3c_202_20_3e_20_3e_19129',['ntree_traits&lt; 2, 2, elem_t, NTreeGridData&lt; 2 &gt; &gt;',['../structug_1_1ntree__traits_3_012_00_012_00_01elem__t_00_01_n_tree_grid_data_3_012_01_4_01_4.html',1,'ug']]],
  ['ntree_5ftraits_3c_202_2c_203_2c_20elem_5ft_2c_20ntreegriddata_3c_203_20_3e_20_3e_19130',['ntree_traits&lt; 2, 3, elem_t, NTreeGridData&lt; 3 &gt; &gt;',['../structug_1_1ntree__traits_3_012_00_013_00_01elem__t_00_01_n_tree_grid_data_3_013_01_4_01_4.html',1,'ug']]],
  ['ntree_5ftraits_3c_203_2c_203_2c_20elem_5ft_2c_20ntreegriddata_3c_203_20_3e_20_3e_19131',['ntree_traits&lt; 3, 3, elem_t, NTreeGridData&lt; 3 &gt; &gt;',['../structug_1_1ntree__traits_3_013_00_013_00_01elem__t_00_01_n_tree_grid_data_3_013_01_4_01_4.html',1,'ug']]],
  ['ntreedesc_19132',['NTreeDesc',['../structug_1_1_n_tree_desc.html',1,'ug']]],
  ['ntreegriddata_19133',['NTreeGridData',['../classug_1_1_n_tree_grid_data.html',1,'ug']]],
  ['nullsmartptr_19134',['NullSmartPtr',['../class_null_smart_ptr.html',1,'']]],
  ['numberarray_19135',['NumberArray',['../classug_1_1vrl_1_1_number_array.html',1,'ug::vrl']]],
  ['numberdata_19136',['NumberData',['../structug_1_1_dirichlet_boundary_1_1_number_data.html',1,'ug::DirichletBoundary&lt; TDomain, TAlgebra &gt;::NumberData'],['../structug_1_1_i_obstacle_constraint_1_1_number_data.html',1,'ug::IObstacleConstraint&lt; TDomain, TAlgebra &gt;::NumberData'],['../structug_1_1_neumann_boundary_f_e_1_1_number_data.html',1,'ug::NeumannBoundaryFE&lt; TDomain &gt;::NumberData'],['../structug_1_1_neumann_boundary_f_v1_1_1_number_data.html',1,'ug::NeumannBoundaryFV1&lt; TDomain &gt;::NumberData'],['../structug_1_1_neumann_boundary_f_v_1_1_number_data.html',1,'ug::NeumannBoundaryFV&lt; TDomain &gt;::NumberData']]],
  ['numbervalueduserdataevaluator_19137',['NumberValuedUserDataEvaluator',['../classug_1_1bridge_1_1_evaluate_1_1_number_valued_user_data_evaluator.html',1,'ug::bridge::Evaluate']]],
  ['numbervalueduserdatapointevaluator_19138',['NumberValuedUserDataPointEvaluator',['../classug_1_1bridge_1_1_evaluate_1_1_number_valued_user_data_point_evaluator.html',1,'ug::bridge::Evaluate']]]
];
