var searchData=
[
  ['c_5fbool_16087',['c_bool',['../../regdocu/classug4_bridge_1_1c__bool.html',1,'ug4Bridge']]],
  ['c_5fchar_16088',['c_char',['../../regdocu/classug4_bridge_1_1c__char.html',1,'ug4Bridge']]],
  ['c_5fconst_5fchar_5fptr_16089',['c_const_char_ptr',['../../regdocu/classug4_bridge_1_1c__const__char__ptr.html',1,'ug4Bridge']]],
  ['c_5fdouble_16090',['c_double',['../../regdocu/classug4_bridge_1_1c__double.html',1,'ug4Bridge']]],
  ['c_5ffloat_16091',['c_float',['../../regdocu/classug4_bridge_1_1c__float.html',1,'ug4Bridge']]],
  ['c_5fint_16092',['c_int',['../../regdocu/classug4_bridge_1_1c__int.html',1,'ug4Bridge']]],
  ['c_5fluafunctionhandle_16093',['c_LuaFunctionHandle',['../../regdocu/classug4_bridge_1_1c___lua_function_handle.html',1,'ug4Bridge']]],
  ['c_5fsize_5ft_16094',['c_size_t',['../../regdocu/classug4_bridge_1_1c__size__t.html',1,'ug4Bridge']]],
  ['c_5fstring_16095',['c_string',['../../regdocu/classug4_bridge_1_1c__string.html',1,'ug4Bridge']]],
  ['c_5fvoid_16096',['c_void',['../../regdocu/classug4_bridge_1_1c__void.html',1,'ug4Bridge']]],
  ['cake_16097',['Cake',['../../classug_1_1bridge_1_1_cake.html',1,'ug::bridge']]],
  ['calcvolpowerelemhelperclass_16098',['CalcVolPowerElemHelperClass',['../../../plugins/classug_1_1_electromagnetism_1_1_calc_vol_power_elem_helper_class.html',1,'ug::Electromagnetism']]],
  ['calcvolpowerhelperclass_16099',['CalcVolPowerHelperClass',['../../../plugins/classug_1_1_electromagnetism_1_1_calc_vol_power_helper_class.html',1,'ug::Electromagnetism']]],
  ['callbackentry_16100',['CallbackEntry',['../../structug_1_1_message_hub_1_1_callback_entry.html',1,'ug::MessageHub']]],
  ['callbackid_16101',['CallbackId',['../../classug_1_1_message_hub_1_1_callback_id.html',1,'ug::MessageHub']]],
  ['cd_5fline_5fsss_5fdata_16102',['cd_line_sss_data',['../../../plugins/classug_1_1_convection_diffusion_plugin_1_1cd__line__sss__data.html',1,'ug::ConvectionDiffusionPlugin']]],
  ['cd_5fpoint_5fsss_5fdata_16103',['cd_point_sss_data',['../../../plugins/classug_1_1_convection_diffusion_plugin_1_1cd__point__sss__data.html',1,'ug::ConvectionDiffusionPlugin']]],
  ['cd_5fsss_5fdata_16104',['cd_sss_data',['../../../plugins/classug_1_1_convection_diffusion_plugin_1_1cd__sss__data.html',1,'ug::ConvectionDiffusionPlugin']]],
  ['cdlinesourcessink_16105',['CDLineSourcesSink',['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_elem_disc_1_1_c_d_line_sources_sink.html',1,'ug4Bridge::SpatialDisc::ElemDisc']]],
  ['cdpointsourcessink_16106',['CDPointSourcesSink',['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_elem_disc_1_1_c_d_point_sources_sink.html',1,'ug4Bridge::SpatialDisc::ElemDisc']]],
  ['cdsingularsourcesandsinks_16107',['CDSingularSourcesAndSinks',['../../../plugins/classug_1_1_convection_diffusion_plugin_1_1_c_d_singular_sources_and_sinks.html',1,'ug::ConvectionDiffusionPlugin::CDSingularSourcesAndSinks&lt; dim &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_elem_disc_1_1_c_d_singular_sources_and_sinks.html',1,'ug4Bridge::SpatialDisc::ElemDisc::CDSingularSourcesAndSinks']]],
  ['cell_16108',['Cell',['../../structug_1_1fieldutil_1_1_cell.html',1,'ug::fieldutil']]],
  ['cellidx_16109',['CellIdx',['../../structug_1_1_cell_idx.html',1,'ug']]],
  ['cg_16110',['CG',['../../regdocu/classug4_bridge_1_1_algebra_1_1_solver_1_1_c_g.html',1,'ug4Bridge::Algebra::Solver::CG'],['../../classug_1_1_c_g.html',1,'ug::CG&lt; class &gt;']]],
  ['cgraph_16111',['cgraph',['../../classug_1_1cgraph.html',1,'ug']]],
  ['chaininfo_16112',['ChainInfo',['../../structug_1_1_chain_info.html',1,'ug']]],
  ['chunk_16113',['Chunk',['../../struct_fixed_allocator_1_1_chunk.html',1,'FixedAllocator']]],
  ['classcastprovider_16114',['ClassCastProvider',['../../classug_1_1bridge_1_1_class_cast_provider.html',1,'ug::bridge']]],
  ['classgroupdesc_16115',['ClassGroupDesc',['../../classug_1_1bridge_1_1_class_group_desc.html',1,'ug::bridge']]],
  ['classhierarchy_16116',['ClassHierarchy',['../../classug_1_1bridge_1_1_class_hierarchy.html',1,'ug::bridge']]],
  ['classhierarchyprovider_16117',['ClassHierarchyProvider',['../../../plugins/classug_1_1_docu_gen_1_1_class_hierarchy_provider.html',1,'ug::DocuGen']]],
  ['classinfo_16118',['ClassInfo',['../../structug_1_1_factory_1_1_class_info.html',1,'ug::Factory']]],
  ['classnamenode_16119',['ClassNameNode',['../../classug_1_1bridge_1_1_class_name_node.html',1,'ug::bridge']]],
  ['classnameprovider_16120',['ClassNameProvider',['../../classug_1_1bridge_1_1_class_name_provider.html',1,'ug::bridge']]],
  ['cleardivinconductors_16121',['ClearDivInConductors',['../../../plugins/structug_1_1_electromagnetism_1_1_nedelec_project_1_1_clear_div_in_conductors.html',1,'ug::Electromagnetism::NedelecProject']]],
  ['cli_5ffunctionality_16122',['CLI_Functionality',['../../structug_1_1bridge_1_1_c_l_i___functionality.html',1,'ug::bridge']]],
  ['clusterelementstacks_16123',['ClusterElementStacks',['../../classug_1_1_cluster_element_stacks.html',1,'ug']]],
  ['cmpinfo_16124',['CmpInfo',['../../structug_1_1_composite_conv_check_1_1_cmp_info.html',1,'ug::CompositeConvCheck::CmpInfo'],['../../structug_1_1_algebraic_conv_check_1_1_cmp_info.html',1,'ug::AlgebraicConvCheck&lt; class &gt;::CmpInfo']]],
  ['cmpvrtsbyhash_16125',['CmpVrtsByHash',['../../classug_1_1_cmp_vrts_by_hash.html',1,'ug']]],
  ['cnt_16126',['Cnt',['../../structug_1_1_do_f_count_1_1_cnt.html',1,'ug::DoFCount']]],
  ['collisionedgesnode_16127',['CollisionEdgesNode',['../../classug_1_1node__tree_1_1_collision_edges_node.html',1,'ug::node_tree']]],
  ['collisionelementid_16128',['CollisionElementID',['../../structug_1_1node__tree_1_1_collision_element_i_d.html',1,'ug::node_tree']]],
  ['collisiontreerootnode_16129',['CollisionTreeRootNode',['../../classug_1_1node__tree_1_1_collision_tree_root_node.html',1,'ug::node_tree']]],
  ['collisiontrianglesnode_16130',['CollisionTrianglesNode',['../../classug_1_1node__tree_1_1_collision_triangles_node.html',1,'ug::node_tree']]],
  ['combinedlineariterator_16131',['CombinedLinearIterator',['../../classug_1_1_combined_linear_iterator.html',1,'ug']]],
  ['commonlocaldofset_16132',['CommonLocalDoFSet',['../../classug_1_1_common_local_do_f_set.html',1,'ug']]],
  ['communicationscheme_16133',['CommunicationScheme',['../../classug_1_1_communication_scheme.html',1,'ug']]],
  ['communicationscheme_3c_20consistencycheckclass_3c_20tvec_2c_20tvalue_20_3e_2c_20tvalue_20_3e_16134',['CommunicationScheme&lt; ConsistencyCheckClass&lt; TVec, TValue &gt;, TValue &gt;',['../../classug_1_1_communication_scheme.html',1,'']]],
  ['communicationscheme_3c_20stdarraycommunicationscheme_3c_20tarray_20_3e_2c_20tarray_3a_3avalue_5ftype_20_3e_16135',['CommunicationScheme&lt; StdArrayCommunicationScheme&lt; TArray &gt;, TArray::value_type &gt;',['../../classug_1_1_communication_scheme.html',1,'']]],
  ['communicationscheme_3c_20tderived_2c_20bool_20_3e_16136',['CommunicationScheme&lt; TDerived, bool &gt;',['../../classug_1_1_communication_scheme_3_01_t_derived_00_01bool_01_4.html',1,'ug']]],
  ['commwrapper_16137',['CommWrapper',['../../structpcl_1_1_process_communicator_1_1_comm_wrapper.html',1,'pcl::ProcessCommunicator']]],
  ['comparebranchingregionends_16138',['CompareBranchingRegionEnds',['../../structug_1_1_neurite_projector_1_1_compare_branching_region_ends.html',1,'ug::NeuriteProjector']]],
  ['comparebyattachment_16139',['CompareByAttachment',['../../classug_1_1_compare_by_attachment.html',1,'ug']]],
  ['comparedeg_16140',['CompareDeg',['../../../plugins/structug_1_1_compare_deg.html',1,'ug']]],
  ['comparedegree_16141',['CompareDegree',['../../structug_1_1_compare_degree.html',1,'ug']]],
  ['comparefaceinfo_16142',['CompareFaceInfo',['../../structug_1_1_delaunay_info_1_1_compare_face_info.html',1,'ug::DelaunayInfo']]],
  ['compareindicesbyclass_16143',['CompareIndicesByClass',['../../class_compare_indices_by_class.html',1,'']]],
  ['compareindicesbyclass2_16144',['CompareIndicesByClass2',['../../class_compare_indices_by_class2.html',1,'']]],
  ['comparesections_16145',['CompareSections',['../../structug_1_1_neurite_projector_1_1_compare_sections.html',1,'ug::NeuriteProjector']]],
  ['comparesomabranchingregionsend_16146',['CompareSomaBranchingRegionsEnd',['../../structug_1_1_neurite_projector_1_1_compare_soma_branching_regions_end.html',1,'ug::NeuriteProjector']]],
  ['compiletimeassertion_16147',['CompileTimeAssertion',['../../struct_compile_time_assertion.html',1,'']]],
  ['compiletimeassertion_3c_20true_20_3e_16148',['CompileTimeAssertion&lt; true &gt;',['../../struct_compile_time_assertion_3_01true_01_4.html',1,'']]],
  ['compol_5fadjusttype_16149',['ComPol_AdjustType',['../../classug_1_1_com_pol___adjust_type.html',1,'ug']]],
  ['compol_5fattachmentreduce_16150',['ComPol_AttachmentReduce',['../../classug_1_1_com_pol___attachment_reduce.html',1,'ug']]],
  ['compol_5fboolmarker_5faddmarks_16151',['ComPol_BoolMarker_AddMarks',['../../classug_1_1_com_pol___bool_marker___add_marks.html',1,'ug']]],
  ['compol_5fboolmarker_5fremovemarks_16152',['ComPol_BoolMarker_RemoveMarks',['../../classug_1_1_com_pol___bool_marker___remove_marks.html',1,'ug']]],
  ['compol_5fbroadcastcoarsenmarks_16153',['ComPol_BroadcastCoarsenMarks',['../../classug_1_1_com_pol___broadcast_coarsen_marks.html',1,'ug']]],
  ['compol_5fbroadcastrefinemarks_16154',['ComPol_BroadcastRefineMarks',['../../classug_1_1_com_pol___broadcast_refine_marks.html',1,'ug']]],
  ['compol_5fcheckconsistency_16155',['ComPol_CheckConsistency',['../../classug_1_1_com_pol___check_consistency.html',1,'ug']]],
  ['compol_5fcheckdistributedparentstates_16156',['ComPol_CheckDistributedParentStates',['../../classug_1_1_com_pol___check_distributed_parent_states.html',1,'ug']]],
  ['compol_5fcopyattachment_16157',['ComPol_CopyAttachment',['../../classug_1_1_com_pol___copy_attachment.html',1,'ug']]],
  ['compol_5fenableselectionstatebits_16158',['ComPol_EnableSelectionStateBits',['../../classug_1_1_com_pol___enable_selection_state_bits.html',1,'ug']]],
  ['compol_5fgathersurfacestates_16159',['ComPol_GatherSurfaceStates',['../../classug_1_1_com_pol___gather_surface_states.html',1,'ug']]],
  ['compol_5fgathervecattachment_16160',['ComPol_GatherVecAttachment',['../../classug_1_1_com_pol___gather_vec_attachment.html',1,'ug']]],
  ['compol_5finterfacestatus_16161',['ComPol_InterfaceStatus',['../../classug_1_1_com_pol___interface_status.html',1,'ug']]],
  ['compol_5fmataddrowsoverlap0_16162',['ComPol_MatAddRowsOverlap0',['../../classug_1_1_com_pol___mat_add_rows_overlap0.html',1,'ug']]],
  ['compol_5fmataddsetzeroinnerinterfacecouplings_16163',['ComPol_MatAddSetZeroInnerInterfaceCouplings',['../../classug_1_1_com_pol___mat_add_set_zero_inner_interface_couplings.html',1,'ug']]],
  ['compol_5fmatcopydiag_16164',['ComPol_MatCopyDiag',['../../classug_1_1_com_pol___mat_copy_diag.html',1,'ug']]],
  ['compol_5fmatcopyrowsoverlap0_16165',['ComPol_MatCopyRowsOverlap0',['../../classug_1_1_com_pol___mat_copy_rows_overlap0.html',1,'ug']]],
  ['compol_5fmatcreateoverlap_16166',['ComPol_MatCreateOverlap',['../../classug_1_1_com_pol___mat_create_overlap.html',1,'ug']]],
  ['compol_5fmatdistributediag_16167',['ComPol_MatDistributeDiag',['../../classug_1_1_com_pol___mat_distribute_diag.html',1,'ug']]],
  ['compol_5fmemcopy_16168',['ComPol_MemCopy',['../../../plugins/classug_1_1_electromagnetism_1_1_com_pol___mem_copy.html',1,'ug::Electromagnetism']]],
  ['compol_5fmemop_16169',['ComPol_MemOp',['../../../plugins/classug_1_1_electromagnetism_1_1_com_pol___mem_op.html',1,'ug::Electromagnetism']]],
  ['compol_5fnewconstrainedverticals_16170',['ComPol_NewConstrainedVerticals',['../../classug_1_1_com_pol___new_constrained_verticals.html',1,'ug']]],
  ['compol_5fselection_16171',['ComPol_Selection',['../../classug_1_1_com_pol___selection.html',1,'ug']]],
  ['compol_5fsubset_16172',['ComPol_Subset',['../../classug_1_1_com_pol___subset.html',1,'ug']]],
  ['compol_5fsynchronizedistinfos_16173',['ComPol_SynchronizeDistInfos',['../../classug_1_1_com_pol___synchronize_dist_infos.html',1,'ug']]],
  ['compol_5fvecadd_16174',['ComPol_VecAdd',['../../classug_1_1_com_pol___vec_add.html',1,'ug']]],
  ['compol_5fvecaddsetzero_16175',['ComPol_VecAddSetZero',['../../classug_1_1_com_pol___vec_add_set_zero.html',1,'ug']]],
  ['compol_5fveccopy_16176',['ComPol_VecCopy',['../../classug_1_1_com_pol___vec_copy.html',1,'ug']]],
  ['compol_5fvecscaleadd_16177',['ComPol_VecScaleAdd',['../../classug_1_1_com_pol___vec_scale_add.html',1,'ug']]],
  ['compol_5fvecscalecopy_16178',['ComPol_VecScaleCopy',['../../classug_1_1_com_pol___vec_scale_copy.html',1,'ug']]],
  ['compol_5fvecsubtract_16179',['ComPol_VecSubtract',['../../classug_1_1_com_pol___vec_subtract.html',1,'ug']]],
  ['compol_5fvecsubtractonlyoneslave_16180',['ComPol_VecSubtractOnlyOneSlave',['../../classug_1_1_com_pol___vec_subtract_only_one_slave.html',1,'ug']]],
  ['componentgaussseidel_16181',['ComponentGaussSeidel',['../../regdocu/classug4_bridge_1_1_discretization_1_1_multi_grid_1_1_component_gauss_seidel.html',1,'ug4Bridge::Discretization::MultiGrid::ComponentGaussSeidel'],['../../classug_1_1_component_gauss_seidel.html',1,'ug::ComponentGaussSeidel&lt; class, class &gt;']]],
  ['compositeasstuner_16182',['CompositeAssTuner',['../../classug_1_1_composite_time_discretization_1_1_composite_ass_tuner.html',1,'ug::CompositeTimeDiscretization']]],
  ['compositeconvcheck_16183',['CompositeConvCheck',['../../regdocu/classug4_bridge_1_1_composite_conv_check.html',1,'ug4Bridge::CompositeConvCheck'],['../../classug_1_1_composite_conv_check.html',1,'ug::CompositeConvCheck&lt; class, class &gt;']]],
  ['compositespace_16184',['CompositeSpace',['../../classug_1_1_composite_space.html',1,'ug::CompositeSpace&lt; class &gt;'],['../../regdocu/classug4_bridge_1_1_discretization_1_1_approximation_space_1_1_composite_space.html',1,'ug4Bridge::Discretization::ApproximationSpace::CompositeSpace']]],
  ['compositetimediscretization_16185',['CompositeTimeDiscretization',['../../classug_1_1_composite_time_discretization.html',1,'ug::CompositeTimeDiscretization&lt; class &gt;'],['../../regdocu/classug4_bridge_1_1_discretization_1_1_time_disc_1_1_composite_time_discretization.html',1,'ug4Bridge::Discretization::TimeDisc::CompositeTimeDiscretization']]],
  ['compressiblenavierstokesbase_16186',['CompressibleNavierStokesBase',['../../../plugins/classug_1_1_navier_stokes_1_1_compressible_navier_stokes_base.html',1,'ug::NavierStokes::CompressibleNavierStokesBase&lt; class &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_navier_stokes_1_1_spatial_disc_1_1_compressible_navier_stok704cf5366b44eb7a04b555b4188aebf1.html',1,'ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::CompressibleNavierStokes::CompressibleNavierStokesBase']]],
  ['compressiblenavierstokesfv1_16187',['CompressibleNavierStokesFV1',['../../../plugins/classug_1_1_navier_stokes_1_1_compressible_navier_stokes_f_v1.html',1,'ug::NavierStokes::CompressibleNavierStokesFV1&lt; class &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_navier_stokes_1_1_spatial_disc_1_1_compressible_navier_stok15a2c1d49241497ba8b3579fd1effd3c.html',1,'ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::CompressibleNavierStokes::SpatialDisc::NavierStokes::CompressibleNavierStokesFV1']]],
  ['computeelemfluxhelper_16188',['ComputeElemFluxHelper',['../../../plugins/classug_1_1_electromagnetism_1_1_compute_elem_flux_helper.html',1,'ug::Electromagnetism']]],
  ['computeelemfluxhelper_3c_20tgridfunc_2c_20regularedge_20_3e_16189',['ComputeElemFluxHelper&lt; TGridFunc, RegularEdge &gt;',['../../../plugins/classug_1_1_electromagnetism_1_1_compute_elem_flux_helper_3_01_t_grid_func_00_01_regular_edge_01_4.html',1,'ug::Electromagnetism']]],
  ['computefluxhelper_16190',['ComputeFluxHelper',['../../../plugins/classug_1_1_electromagnetism_1_1_compute_flux_helper.html',1,'ug::Electromagnetism']]],
  ['condcplusermatrix_16191',['CondCplUserMatrix',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cond_cpl_user_matrix.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['condcplusernumber_16192',['CondCplUserNumber',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cond_cpl_user_number.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['condcplusertensor4_16193',['CondCplUserTensor4',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cond_cpl_user_tensor4.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['condcpluservector_16194',['CondCplUserVector',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cond_cpl_user_vector.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['condnumberdata_16195',['CondNumberData',['../../structug_1_1_i_obstacle_constraint_1_1_cond_number_data.html',1,'ug::IObstacleConstraint::CondNumberData'],['../../structug_1_1_dirichlet_boundary_1_1_cond_number_data.html',1,'ug::DirichletBoundary::CondNumberData']]],
  ['condusermatrix_16196',['CondUserMatrix',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cond_user_matrix.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['condusernumber_16197',['CondUserNumber',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cond_user_number.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['condusertensor4_16198',['CondUserTensor4',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cond_user_tensor4.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['conduservector_16199',['CondUserVector',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cond_user_vector.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['connectedtoonemarkedvrt_16200',['ConnectedToOneMarkedVrt',['../../structug_1_1_connected_to_one_marked_vrt.html',1,'ug']]],
  ['connection_16201',['connection',['../../structug_1_1_map_sparse_matrix_1_1connection.html',1,'ug::MapSparseMatrix']]],
  ['connodetype_16202',['conNodeType',['../../structcon_node_type.html',1,'']]],
  ['considerall_16203',['ConsiderAll',['../../classug_1_1_consider_all.html',1,'ug']]],
  ['considernone_16204',['ConsiderNone',['../../classug_1_1_consider_none.html',1,'ug']]],
  ['consistencycheckclass_16205',['ConsistencyCheckClass',['../../classug_1_1_consistency_check_class.html',1,'ug']]],
  ['consistencycheckclasssend_16206',['ConsistencyCheckClassSend',['../../classug_1_1_consistency_check_class_send.html',1,'ug']]],
  ['consistencycheckclasssend_3c_20tvec_2c_20bool_20_3e_16207',['ConsistencyCheckClassSend&lt; TVec, bool &gt;',['../../classug_1_1_consistency_check_class_send_3_01_t_vec_00_01bool_01_4.html',1,'ug']]],
  ['const_5fiterator_16208',['const_iterator',['../../classug_1_1_sparse_vector_1_1const__iterator.html',1,'ug::SparseVector']]],
  ['const_5flocalmatrix_5ffrom_5fmat_5fand_5farray_16209',['const_localMatrix_from_mat_and_array',['../../classug_1_1const__local_matrix__from__mat__and__array.html',1,'ug']]],
  ['const_5fntree_5felement_5fiterator_16210',['const_ntree_element_iterator',['../../classug_1_1const__ntree__element__iterator.html',1,'ug']]],
  ['const_5frow_5fiterator_16211',['const_row_iterator',['../../class_scalar_matrix_adapter_1_1const__row__iterator.html',1,'ScalarMatrixAdapter::const_row_iterator'],['../../class_scalar_sub_matrix_adapter_1_1const__row__iterator.html',1,'ScalarSubMatrixAdapter::const_row_iterator'],['../../classug_1_1_sparse_matrix_1_1const__row__iterator.html',1,'ug::SparseMatrix::const_row_iterator'],['../../classug_1_1_g_p_u_sparse_matrix_1_1const__row__iterator.html',1,'ug::GPUSparseMatrix::const_row_iterator'],['../../classug_1_1_map_sparse_matrix_1_1const__row__iterator.html',1,'ug::MapSparseMatrix::const_row_iterator']]],
  ['constantboxfilter_16212',['ConstantBoxFilter',['../../../plugins/classug_1_1_navier_stokes_1_1_constant_box_filter.html',1,'ug::NavierStokes::ConstantBoxFilter&lt; class &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_navier_stokes_1_1_spatial_disc_1_1_navier_stokes_1_1_constant_box_filter.html',1,'ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::ConstantBoxFilter']]],
  ['constantdamping_16213',['ConstantDamping',['../../classug_1_1_constant_damping.html',1,'ug']]],
  ['constattachedelementlistiterator_16214',['ConstAttachedElementListIterator',['../../classug_1_1_const_attached_element_list_iterator.html',1,'ug']]],
  ['constcharbuffer_16215',['ConstCharBuffer',['../../structpcl_1_1_parallel_archive_1_1_const_char_buffer.html',1,'pcl::ParallelArchive']]],
  ['constclass_16216',['ConstClass',['../../classug_1_1bridge_1_1_const_class.html',1,'ug::bridge']]],
  ['constgenericgridobjectiterator_16217',['ConstGenericGridObjectIterator',['../../classug_1_1_const_generic_grid_object_iterator.html',1,'ug']]],
  ['constmatrixrow_16218',['ConstMatrixRow',['../../classug_1_1_const_matrix_row.html',1,'ug']]],
  ['constnumberdata_16219',['ConstNumberData',['../../structug_1_1_i_obstacle_constraint_1_1_const_number_data.html',1,'ug::IObstacleConstraint::ConstNumberData'],['../../structug_1_1_dirichlet_boundary_1_1_const_number_data.html',1,'ug::DirichletBoundary::ConstNumberData']]],
  ['constrained_5fdof_16220',['CONSTRAINED_DOF',['../../classug_1_1_dim_c_r_f_v_geometry_1_1_c_o_n_s_t_r_a_i_n_e_d___d_o_f.html',1,'ug::DimCRFVGeometry::CONSTRAINED_DOF'],['../../classug_1_1_c_r_f_v_geometry_1_1_c_o_n_s_t_r_a_i_n_e_d___d_o_f.html',1,'ug::CRFVGeometry::CONSTRAINED_DOF'],['../../classug_1_1_h_c_r_f_v_geometry_1_1_c_o_n_s_t_r_a_i_n_e_d___d_o_f.html',1,'ug::HCRFVGeometry::CONSTRAINED_DOF']]],
  ['constrainededge_16221',['ConstrainedEdge',['../../classug_1_1_constrained_edge.html',1,'ug']]],
  ['constrainedface_16222',['ConstrainedFace',['../../classug_1_1_constrained_face.html',1,'ug']]],
  ['constrainedlineariterator_16223',['ConstrainedLinearIterator',['../../classug_1_1_constrained_linear_iterator.html',1,'ug']]],
  ['constrainedquadrilateral_16224',['ConstrainedQuadrilateral',['../../classug_1_1_constrained_quadrilateral.html',1,'ug']]],
  ['constrainedtriangle_16225',['ConstrainedTriangle',['../../classug_1_1_constrained_triangle.html',1,'ug']]],
  ['constrainedvertex_16226',['ConstrainedVertex',['../../classug_1_1_constrained_vertex.html',1,'ug']]],
  ['constrainingedge_16227',['ConstrainingEdge',['../../classug_1_1_constraining_edge.html',1,'ug']]],
  ['constrainingface_16228',['ConstrainingFace',['../../classug_1_1_constraining_face.html',1,'ug']]],
  ['constrainingquadrilateral_16229',['ConstrainingQuadrilateral',['../../classug_1_1_constraining_quadrilateral.html',1,'ug']]],
  ['constrainingtriangle_16230',['ConstrainingTriangle',['../../classug_1_1_constraining_triangle.html',1,'ug']]],
  ['constraint_5ftraits_16231',['constraint_traits',['../../structug_1_1constraint__traits.html',1,'ug']]],
  ['constraint_5ftraits_3c_20edge_20_3e_16232',['constraint_traits&lt; Edge &gt;',['../../structug_1_1constraint__traits_3_01_edge_01_4.html',1,'ug']]],
  ['constraint_5ftraits_3c_20face_20_3e_16233',['constraint_traits&lt; Face &gt;',['../../structug_1_1constraint__traits_3_01_face_01_4.html',1,'ug']]],
  ['constraint_5ftraits_3c_20quadrilateral_20_3e_16234',['constraint_traits&lt; Quadrilateral &gt;',['../../structug_1_1constraint__traits_3_01_quadrilateral_01_4.html',1,'ug']]],
  ['constraint_5ftraits_3c_20triangle_20_3e_16235',['constraint_traits&lt; Triangle &gt;',['../../structug_1_1constraint__traits_3_01_triangle_01_4.html',1,'ug']]],
  ['constraint_5ftraits_3c_20vertex_20_3e_16236',['constraint_traits&lt; Vertex &gt;',['../../structug_1_1constraint__traits_3_01_vertex_01_4.html',1,'ug']]],
  ['constructgridofscvfwrapper_16237',['ConstructGridOfSCVFWrapper',['../../structug_1_1_construct_grid_of_s_c_v_f_wrapper.html',1,'ug']]],
  ['constructgridofscvfwrapper_3c_20tfvgeom_2c_201_20_3e_16238',['ConstructGridOfSCVFWrapper&lt; TFVGeom, 1 &gt;',['../../structug_1_1_construct_grid_of_s_c_v_f_wrapper_3_01_t_f_v_geom_00_011_01_4.html',1,'ug']]],
  ['constructgridofscvfwrapper_3c_20tfvgeom_2c_202_20_3e_16239',['ConstructGridOfSCVFWrapper&lt; TFVGeom, 2 &gt;',['../../structug_1_1_construct_grid_of_s_c_v_f_wrapper_3_01_t_f_v_geom_00_012_01_4.html',1,'ug']]],
  ['constructgridofscvfwrapper_3c_20tfvgeom_2c_203_20_3e_16240',['ConstructGridOfSCVFWrapper&lt; TFVGeom, 3 &gt;',['../../structug_1_1_construct_grid_of_s_c_v_f_wrapper_3_01_t_f_v_geom_00_013_01_4.html',1,'ug']]],
  ['constructgridofscvwrapper_16241',['ConstructGridOfSCVWrapper',['../../structug_1_1_construct_grid_of_s_c_v_wrapper.html',1,'ug']]],
  ['constructgridofscvwrapper_3c_20tfvgeom_2c_201_20_3e_16242',['ConstructGridOfSCVWrapper&lt; TFVGeom, 1 &gt;',['../../structug_1_1_construct_grid_of_s_c_v_wrapper_3_01_t_f_v_geom_00_011_01_4.html',1,'ug']]],
  ['constructgridofscvwrapper_3c_20tfvgeom_2c_202_20_3e_16243',['ConstructGridOfSCVWrapper&lt; TFVGeom, 2 &gt;',['../../structug_1_1_construct_grid_of_s_c_v_wrapper_3_01_t_f_v_geom_00_012_01_4.html',1,'ug']]],
  ['constructgridofscvwrapper_3c_20tfvgeom_2c_203_20_3e_16244',['ConstructGridOfSCVWrapper&lt; TFVGeom, 3 &gt;',['../../structug_1_1_construct_grid_of_s_c_v_wrapper_3_01_t_f_v_geom_00_013_01_4.html',1,'ug']]],
  ['constructor_5ftraits_16245',['constructor_traits',['../../structug_1_1bridge_1_1constructor__traits.html',1,'ug::bridge']]],
  ['constructor_5ftraits_3c_20t_2c_20typelist_3c_20t1_20_3e_20_3e_16246',['constructor_traits&lt; T, TypeList&lt; T1 &gt; &gt;',['../../structug_1_1bridge_1_1constructor__traits_3_01_t_00_01_type_list_3_01_t1_01_4_01_4.html',1,'ug::bridge']]],
  ['constructor_5ftraits_3c_20t_2c_20typelist_3c_20t1_2c_20t2_20_3e_20_3e_16247',['constructor_traits&lt; T, TypeList&lt; T1, T2 &gt; &gt;',['../../structug_1_1bridge_1_1constructor__traits_3_01_t_00_01_type_list_3_01_t1_00_01_t2_01_4_01_4.html',1,'ug::bridge']]],
  ['constructor_5ftraits_3c_20t_2c_20typelist_3c_20t1_2c_20t2_2c_20t3_20_3e_20_3e_16248',['constructor_traits&lt; T, TypeList&lt; T1, T2, T3 &gt; &gt;',['../../structug_1_1bridge_1_1constructor__traits_3_01_t_00_01_type_list_3_01_t1_00_01_t2_00_01_t3_01_4_01_4.html',1,'ug::bridge']]],
  ['constructor_5ftraits_3c_20t_2c_20typelist_3c_20t1_2c_20t2_2c_20t3_2c_20t4_20_3e_20_3e_16249',['constructor_traits&lt; T, TypeList&lt; T1, T2, T3, T4 &gt; &gt;',['../../structug_1_1bridge_1_1constructor__traits_3_01_t_00_01_type_list_3_01_t1_00_01_t2_00_01_t3_00_01_t4_01_4_01_4.html',1,'ug::bridge']]],
  ['constructor_5ftraits_3c_20t_2c_20typelist_3c_20t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_20_3e_20_3e_16250',['constructor_traits&lt; T, TypeList&lt; T1, T2, T3, T4, T5 &gt; &gt;',['../../structug_1_1bridge_1_1constructor__traits_3_01_t_00_01_type_list_3_01_t1_00_01_t2_00_01_t3_00_01_t4_00_01_t5_01_4_01_4.html',1,'ug::bridge']]],
  ['constructor_5ftraits_3c_20t_2c_20typelist_3c_20t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_20_3e_20_3e_16251',['constructor_traits&lt; T, TypeList&lt; T1, T2, T3, T4, T5, T6 &gt; &gt;',['../../structug_1_1bridge_1_1constructor__traits_3_01_t_00_01_type_list_3_01_t1_00_01_t2_00_01_t3_00_01_t4_00_01_t5_00_01_t6_01_4_01_4.html',1,'ug::bridge']]],
  ['constructor_5ftraits_3c_20t_2c_20typelist_3c_20t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_2c_20t7_20_3e_20_3e_16252',['constructor_traits&lt; T, TypeList&lt; T1, T2, T3, T4, T5, T6, T7 &gt; &gt;',['../../structug_1_1bridge_1_1constructor__traits_3_01_t_00_01_type_list_3_01_t1_00_01_t2_00_01_t3_00_014444522ed260131677e64186550fc2e4.html',1,'ug::bridge']]],
  ['constructor_5ftraits_3c_20t_2c_20typelist_3c_20t1_2c_20t2_2c_20t3_2c_20t4_2c_20t5_2c_20t6_2c_20t7_2c_20t8_20_3e_20_3e_16253',['constructor_traits&lt; T, TypeList&lt; T1, T2, T3, T4, T5, T6, T7, T8 &gt; &gt;',['../../structug_1_1bridge_1_1constructor__traits_3_01_t_00_01_type_list_3_01_t1_00_01_t2_00_01_t3_00_01196fb1b4d2e68ffaa2a24016259bd2ff.html',1,'ug::bridge']]],
  ['constructor_5ftraits_3c_20t_2c_20typelist_3c_3e_20_3e_16254',['constructor_traits&lt; T, TypeList&lt;&gt; &gt;',['../../structug_1_1bridge_1_1constructor__traits_3_01_t_00_01_type_list_3_4_01_4.html',1,'ug::bridge']]],
  ['constructoroverload_16255',['ConstructorOverload',['../../structug_1_1bridge_1_1_exported_class_base_impl_1_1_constructor_overload.html',1,'ug::bridge::ExportedClassBaseImpl']]],
  ['constructorproxy_16256',['ConstructorProxy',['../../structug_1_1bridge_1_1_constructor_proxy.html',1,'ug::bridge']]],
  ['constscalarsubvectoradapter_16257',['ConstScalarSubVectorAdapter',['../../classug_1_1_const_scalar_sub_vector_adapter.html',1,'ug']]],
  ['constsmartptr_16258',['ConstSmartPtr',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20algebralayouts_20_3e_16259',['ConstSmartPtr&lt; AlgebraLayouts &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20approximationspace_3c_20tdomain_20_3e_20_3e_16260',['ConstSmartPtr&lt; ApproximationSpace&lt; TDomain &gt; &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20domain_5ftype_20_3e_16261',['ConstSmartPtr&lt; domain_type &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20functionpattern_20_3e_16262',['ConstSmartPtr&lt; FunctionPattern &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20inavierstokesupwind_3c_20dim_20_3e_20_3e_16263',['ConstSmartPtr&lt; INavierStokesUpwind&lt; dim &gt; &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20matrix_5ftype_20_3e_16264',['ConstSmartPtr&lt; matrix_type &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20tdomain_20_3e_16265',['ConstSmartPtr&lt; TDomain &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3aalgebralayouts_20_3e_16266',['ConstSmartPtr&lt; ug::AlgebraLayouts &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3aapproximationspace_3c_20tdomain_20_3e_20_3e_16267',['ConstSmartPtr&lt; ug::ApproximationSpace&lt; TDomain &gt; &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3aassemblingtuner_3c_20talgebra_20_3e_20_3e_16268',['ConstSmartPtr&lt; ug::AssemblingTuner&lt; TAlgebra &gt; &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3adataexport_3a_3afunctorbase_3c_20refdim_20_3e_20_3e_16269',['ConstSmartPtr&lt; ug::DataExport::FunctorBase&lt; refDim &gt; &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3adimlocaldofset_3c_20dim_20_3e_20_3e_16270',['ConstSmartPtr&lt; ug::DimLocalDoFSet&lt; dim &gt; &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3adofdistribution_20_3e_16271',['ConstSmartPtr&lt; ug::DoFDistribution &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3adofdistributioninfo_20_3e_16272',['ConstSmartPtr&lt; ug::DoFDistributionInfo &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3aelectromagnetism_3a_3aematerial_3c_20domain_5ftype_20_3e_20_3e_16273',['ConstSmartPtr&lt; ug::Electromagnetism::EMaterial&lt; domain_type &gt; &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3afunctionpattern_20_3e_16274',['ConstSmartPtr&lt; ug::FunctionPattern &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3agridfunction_20_3e_16275',['ConstSmartPtr&lt; ug::GridFunction &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3aisubsethandler_20_3e_16276',['ConstSmartPtr&lt; ug::ISubsetHandler &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3alocaldofset_20_3e_16277',['ConstSmartPtr&lt; ug::LocalDoFSet &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3alocalshapefunctionset_3c_20dim_2c_20tshape_2c_20tgrad_20_3e_20_3e_16278',['ConstSmartPtr&lt; ug::LocalShapeFunctionSet&lt; dim, TShape, TGrad &gt; &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3amultigrid_20_3e_16279',['ConstSmartPtr&lt; ug::MultiGrid &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3anavierstokes_3a_3ainavierstokesupwind_3c_20dim_20_3e_20_3e_16280',['ConstSmartPtr&lt; ug::NavierStokes::INavierStokesUpwind&lt; dim &gt; &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3asurfaceview_20_3e_16281',['ConstSmartPtr&lt; ug::SurfaceView &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20ug_3a_3auserdata_20_3e_16282',['ConstSmartPtr&lt; ug::UserData &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20userdata_3c_20number_2c_20worlddim_20_3e_20_3e_16283',['ConstSmartPtr&lt; UserData&lt; number, worldDim &gt; &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartptr_3c_20void_20_3e_16284',['ConstSmartPtr&lt; void &gt;',['../../class_const_smart_ptr_3_01void_01_4.html',1,'']]],
  ['constsmartptr_3c_20weight_5ftype_20_3e_16285',['ConstSmartPtr&lt; weight_type &gt;',['../../class_const_smart_ptr.html',1,'']]],
  ['constsmartuserdatawrapper_16286',['ConstSmartUserDataWrapper',['../../structug_1_1bridge_1_1lua_1_1_const_smart_user_data_wrapper.html',1,'ug::bridge::lua']]],
  ['constsurfaceviewelementiterator_16287',['ConstSurfaceViewElementIterator',['../../classug_1_1_surface_view_1_1_const_surface_view_element_iterator.html',1,'ug::SurfaceView']]],
  ['constusermatrix_16288',['ConstUserMatrix',['../../classug_1_1_const_user_matrix.html',1,'ug::ConstUserMatrix&lt; N, M, worldDim &gt;'],['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_const_user_matrix.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData::ConstUserMatrix']]],
  ['constusernumber_16289',['ConstUserNumber',['../../classug_1_1_const_user_number.html',1,'ug::ConstUserNumber&lt; dim &gt;'],['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_const_user_number.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData::ConstUserNumber']]],
  ['constusertensor_16290',['ConstUserTensor',['../../classug_1_1_const_user_tensor.html',1,'ug']]],
  ['constuservector_16291',['ConstUserVector',['../../classug_1_1_const_user_vector.html',1,'ug::ConstUserVector&lt; dim, worldDim &gt;'],['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_const_user_vector.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData::ConstUserVector']]],
  ['contactsmallstrainmechanics_16292',['ContactSmallStrainMechanics',['../../../plugins/classug_1_1_small_strain_mechanics_1_1_contact_small_strain_mechanics.html',1,'ug::SmallStrainMechanics::ContactSmallStrainMechanics&lt; class, class &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_small_strain_mechanics_1_1_contact_small_strain_mechanics.html',1,'ug4Bridge::SpatialDisc::SmallStrainMechanics::ContactSmallStrainMechanics']]],
  ['containercollection_16293',['ContainerCollection',['../../structug_1_1_grid_object_collection_1_1_container_collection.html',1,'ug::GridObjectCollection']]],
  ['contrained_5fdim_5ftraits_16294',['contrained_dim_traits',['../../../plugins/structug_1_1_small_strain_mechanics_1_1contrained__dim__traits.html',1,'ug::SmallStrainMechanics']]],
  ['contrained_5fdim_5ftraits_3c_202_20_3e_16295',['contrained_dim_traits&lt; 2 &gt;',['../../../plugins/structug_1_1_small_strain_mechanics_1_1contrained__dim__traits_3_012_01_4.html',1,'ug::SmallStrainMechanics']]],
  ['contrained_5fdim_5ftraits_3c_203_20_3e_16296',['contrained_dim_traits&lt; 3 &gt;',['../../../plugins/structug_1_1_small_strain_mechanics_1_1contrained__dim__traits_3_013_01_4.html',1,'ug::SmallStrainMechanics']]],
  ['convcheck_16297',['ConvCheck',['../../regdocu/classug4_bridge_1_1_algebra_1_1_conv_check.html',1,'ug4Bridge::Algebra']]],
  ['convectiondiffusionbase_16298',['ConvectionDiffusionBase',['../../../plugins/classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_base.html',1,'ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase&lt; TDomain &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_elem_disc_1_1_convection_diffusion_base.html',1,'ug4Bridge::SpatialDisc::ElemDisc::ConvectionDiffusionBase']]],
  ['convectiondiffusionfe_16299',['ConvectionDiffusionFE',['../../../plugins/classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_e.html',1,'ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE&lt; class &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_elem_disc_1_1_convection_diffusion_f_e.html',1,'ug4Bridge::SpatialDisc::ElemDisc::ConvectionDiffusionFE']]],
  ['convectiondiffusionfractfv1_16300',['ConvectionDiffusionFractFV1',['../../../plugins/classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_fract_f_v1.html',1,'ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1&lt; TDomain &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_elem_disc_1_1_convection_diffusion_fract_f_v1.html',1,'ug4Bridge::SpatialDisc::ElemDisc::ConvectionDiffusionFractFV1']]],
  ['convectiondiffusionfv_16301',['ConvectionDiffusionFV',['../../../plugins/classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_v.html',1,'ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV&lt; class &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_elem_disc_1_1_convection_diffusion_f_v.html',1,'ug4Bridge::SpatialDisc::ElemDisc::ConvectionDiffusionFV']]],
  ['convectiondiffusionfv1_16302',['ConvectionDiffusionFV1',['../../../plugins/classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_v1.html',1,'ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1&lt; TDomain &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_elem_disc_1_1_convection_diffusion_f_v1.html',1,'ug4Bridge::SpatialDisc::ElemDisc::ConvectionDiffusionFV1']]],
  ['convectiondiffusionfvcr_16303',['ConvectionDiffusionFVCR',['../../../plugins/classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_v_c_r.html',1,'ug::ConvectionDiffusionPlugin::ConvectionDiffusionFVCR&lt; TDomain &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_elem_disc_1_1_convection_diffusion_f_v_c_r.html',1,'ug4Bridge::SpatialDisc::ElemDisc::ConvectionDiffusionFVCR']]],
  ['convectiondiffusionstabfe_16304',['ConvectionDiffusionStabFE',['../../../plugins/classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_stab_f_e.html',1,'ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE&lt; class &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_elem_disc_1_1_convection_diffusion_stab_f_e.html',1,'ug4Bridge::SpatialDisc::ElemDisc::ConvectionDiffusionStabFE']]],
  ['convectionshapesfullupwind_16305',['ConvectionShapesFullUpwind',['../../classug_1_1_convection_shapes_full_upwind.html',1,'ug']]],
  ['convectionshapesnoupwind_16306',['ConvectionShapesNoUpwind',['../../classug_1_1_convection_shapes_no_upwind.html',1,'ug']]],
  ['convectionshapespartialupwind_16307',['ConvectionShapesPartialUpwind',['../../classug_1_1_convection_shapes_partial_upwind.html',1,'ug']]],
  ['convectionshapesweightedupwind_16308',['ConvectionShapesWeightedUpwind',['../../classug_1_1_convection_shapes_weighted_upwind.html',1,'ug']]],
  ['coordinate_16309',['Coordinate',['../../classug_1_1_raster_1_1_coordinate.html',1,'ug::Raster']]],
  ['coordwithindex_16310',['CoordWithIndex',['../../structstl__reader_1_1stl__reader__impl_1_1_coord_with_index.html',1,'stl_reader::stl_reader_impl']]],
  ['copyattachmenthandler_16311',['CopyAttachmentHandler',['../../classug_1_1_copy_attachment_handler.html',1,'ug']]],
  ['copyattachmenthandler_3c_20ug_3a_3avertex_2c_20ug_3a_3aattachment_3c_20ug_3a_3aneuriteprojector_3a_3asurfaceparams_20_3e_20_3e_16312',['CopyAttachmentHandler&lt; ug::Vertex, ug::Attachment&lt; ug::NeuriteProjector::SurfaceParams &gt; &gt;',['../../classug_1_1_copy_attachment_handler.html',1,'CopyAttachmentHandler&lt; ug::Vertex, ug::Attachment&lt; ug::NeuriteProjector::SurfaceParams &gt; &gt;'],['../../classug_1_1_copy_attachment_handler.html',1,'ug::CopyAttachmentHandler&lt; ug::Vertex, ug::Attachment&lt; ug::NeuriteProjector::SurfaceParams &gt; &gt;']]],
  ['count_16313',['Count',['../../classug_1_1raster__kernels_1_1_count.html',1,'ug::raster_kernels']]],
  ['cpluserdata_16314',['CplUserData',['../../classug_1_1_cpl_user_data.html',1,'ug']]],
  ['cpluserdata_3c_20mathmatrix_3c_20n_2c_20m_20_3e_2c_20dim_2c_20void_20_3e_16315',['CplUserData&lt; MathMatrix&lt; N, M &gt;, dim, void &gt;',['../../classug_1_1_cpl_user_data.html',1,'']]],
  ['cpluserdata_3c_20mathtensor_3c_20trank_2c_20dim_20_3e_2c_20dim_2c_20void_20_3e_16316',['CplUserData&lt; MathTensor&lt; TRank, dim &gt;, dim, void &gt;',['../../classug_1_1_cpl_user_data.html',1,'']]],
  ['cpluserdata_3c_20mathvector_3c_202_20_3e_2c_20dim_2c_20void_20_3e_16317',['CplUserData&lt; MathVector&lt; 2 &gt;, dim, void &gt;',['../../classug_1_1_cpl_user_data.html',1,'']]],
  ['cpluserdata_3c_20mathvector_3c_20dim_20_3e_2c_20dim_20_3e_16318',['CplUserData&lt; MathVector&lt; dim &gt;, dim &gt;',['../../classug_1_1_cpl_user_data.html',1,'']]],
  ['cpluserdata_3c_20mathvector_3c_20dim_20_3e_2c_20dim_2c_20void_20_3e_16319',['CplUserData&lt; MathVector&lt; dim &gt;, dim, void &gt;',['../../classug_1_1_cpl_user_data.html',1,'']]],
  ['cpluserdata_3c_20mathvector_3c_20tgridfunction_3a_3adim_20_3e_2c_20dim_20_3e_16320',['CplUserData&lt; MathVector&lt; TGridFunction::dim &gt;, dim &gt;',['../../classug_1_1_cpl_user_data.html',1,'']]],
  ['cpluserdata_3c_20mathvector_3c_20tgridfunction_3a_3adim_20_3e_2c_20dim_2c_20void_20_3e_16321',['CplUserData&lt; MathVector&lt; TGridFunction::dim &gt;, dim, void &gt;',['../../classug_1_1_cpl_user_data.html',1,'']]],
  ['cpluserdata_3c_20number_2c_202_2c_20bool_20_3e_16322',['CplUserData&lt; number, 2, bool &gt;',['../../classug_1_1_cpl_user_data.html',1,'CplUserData&lt; number, 2, bool &gt;'],['../../classug_1_1_cpl_user_data.html',1,'ug::CplUserData&lt; number, 2, bool &gt;']]],
  ['cpluserdata_3c_20number_2c_20dim_20_3e_16323',['CplUserData&lt; number, dim &gt;',['../../classug_1_1_cpl_user_data.html',1,'CplUserData&lt; number, dim &gt;'],['../../classug_1_1_cpl_user_data.html',1,'ug::CplUserData&lt; number, dim &gt;']]],
  ['cpluserdata_3c_20number_2c_20dim_2c_20bool_20_3e_16324',['CplUserData&lt; number, dim, bool &gt;',['../../classug_1_1_cpl_user_data.html',1,'CplUserData&lt; number, dim, bool &gt;'],['../../classug_1_1_cpl_user_data.html',1,'ug::CplUserData&lt; number, dim, bool &gt;']]],
  ['cpluserdata_3c_20number_2c_20dim_2c_20void_20_3e_16325',['CplUserData&lt; number, dim, void &gt;',['../../classug_1_1_cpl_user_data.html',1,'']]],
  ['cpluserdata_3c_20tdata_2c_202_20_3e_16326',['CplUserData&lt; TData, 2 &gt;',['../../classug_1_1_cpl_user_data.html',1,'CplUserData&lt; TData, 2 &gt;'],['../../classug_1_1_cpl_user_data.html',1,'ug::CplUserData&lt; TData, 2 &gt;']]],
  ['cpluserdata_3c_20tdata_2c_20dim_20_3e_16327',['CplUserData&lt; TData, dim &gt;',['../../classug_1_1_cpl_user_data.html',1,'CplUserData&lt; TData, dim &gt;'],['../../classug_1_1_cpl_user_data.html',1,'ug::CplUserData&lt; TData, dim &gt;']]],
  ['cpluserdata_3c_20tdata_2c_20dim_2c_20void_20_3e_16328',['CplUserData&lt; TData, dim, void &gt;',['../../classug_1_1_cpl_user_data.html',1,'']]],
  ['cpluserdata_3c_20tret_2c_20dim_20_3e_16329',['CplUserData&lt; TRet, dim &gt;',['../../classug_1_1_cpl_user_data.html',1,'']]],
  ['cpluserdata_3c_20ug_3a_3amathmatrix_3c_20dim_2c_20dim_20_3e_2c_20dim_20_3e_16330',['CplUserData&lt; ug::MathMatrix&lt; dim, dim &gt;, dim &gt;',['../../classug_1_1_cpl_user_data.html',1,'CplUserData&lt; ug::MathMatrix&lt; dim, dim &gt;, dim &gt;'],['../../classug_1_1_cpl_user_data.html',1,'ug::CplUserData&lt; ug::MathMatrix&lt; dim, dim &gt;, dim &gt;']]],
  ['cpluserdata_3c_20ug_3a_3amathvector_3c_20dim_20_3e_2c_20dim_20_3e_16331',['CplUserData&lt; ug::MathVector&lt; dim &gt;, dim &gt;',['../../classug_1_1_cpl_user_data.html',1,'CplUserData&lt; ug::MathVector&lt; dim &gt;, dim &gt;'],['../../classug_1_1_cpl_user_data.html',1,'ug::CplUserData&lt; ug::MathVector&lt; dim &gt;, dim &gt;']]],
  ['cplusermatrix_16332',['CplUserMatrix',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cpl_user_matrix.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['cplusernumber_16333',['CplUserNumber',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cpl_user_number.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['cplusertensor4_16334',['CplUserTensor4',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cpl_user_tensor4.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['cpluservector_16335',['CplUserVector',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_cpl_user_vector.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['cppgenerator_16336',['CppGenerator',['../../../plugins/classug_1_1_docu_gen_1_1_cpp_generator.html',1,'ug::DocuGen']]],
  ['cpualgebra_16337',['CPUAlgebra',['../../structug_1_1_c_p_u_algebra.html',1,'ug']]],
  ['cpublockalgebra_16338',['CPUBlockAlgebra',['../../structug_1_1_c_p_u_block_algebra.html',1,'ug']]],
  ['cpuvariableblockalgebra_16339',['CPUVariableBlockAlgebra',['../../structug_1_1_c_p_u_variable_block_algebra.html',1,'ug']]],
  ['crdynamicturbviscdata_16340',['CRDynamicTurbViscData',['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_navier_stokes_1_1_spatial_disc_1_1_navier_stokes_1_1_spatia92b94405411f39ccc25a8d1953458a1f.html',1,'ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::CRDynamicTurbViscData'],['../../../plugins/classug_1_1_navier_stokes_1_1_c_r_dynamic_turb_visc_data.html',1,'ug::NavierStokes::CRDynamicTurbViscData&lt; class &gt;']]],
  ['createparameterinfo_16341',['CreateParameterInfo',['../../structug_1_1bridge_1_1_create_parameter_info.html',1,'ug::bridge']]],
  ['createparameterinfo_3c_20typelist_3c_3e_20_3e_16342',['CreateParameterInfo&lt; TypeList&lt;&gt; &gt;',['../../structug_1_1bridge_1_1_create_parameter_info_3_01_type_list_3_4_01_4.html',1,'ug::bridge']]],
  ['createparameterinfoout_16343',['CreateParameterInfoOut',['../../structug_1_1bridge_1_1_create_parameter_info_out.html',1,'ug::bridge']]],
  ['createparameterinfoout_3c_20void_20_3e_16344',['CreateParameterInfoOut&lt; void &gt;',['../../structug_1_1bridge_1_1_create_parameter_info_out_3_01void_01_4.html',1,'ug::bridge']]],
  ['crfv_5ftraits_16345',['crfv_traits',['../../structug_1_1crfv__traits.html',1,'ug']]],
  ['crfv_5ftraits_3c_201_2c_201_20_3e_16346',['crfv_traits&lt; 1, 1 &gt;',['../../structug_1_1crfv__traits_3_011_00_011_01_4.html',1,'ug']]],
  ['crfv_5ftraits_3c_201_2c_202_20_3e_16347',['crfv_traits&lt; 1, 2 &gt;',['../../structug_1_1crfv__traits_3_011_00_012_01_4.html',1,'ug']]],
  ['crfv_5ftraits_3c_202_2c_202_20_3e_16348',['crfv_traits&lt; 2, 2 &gt;',['../../structug_1_1crfv__traits_3_012_00_012_01_4.html',1,'ug']]],
  ['crfv_5ftraits_3c_202_2c_203_20_3e_16349',['crfv_traits&lt; 2, 3 &gt;',['../../structug_1_1crfv__traits_3_012_00_013_01_4.html',1,'ug']]],
  ['crfv_5ftraits_3c_203_2c_203_20_3e_16350',['crfv_traits&lt; 3, 3 &gt;',['../../structug_1_1crfv__traits_3_013_00_013_01_4.html',1,'ug']]],
  ['crfv_5ftraits_3c_203_2c_204_20_3e_16351',['crfv_traits&lt; 3, 4 &gt;',['../../structug_1_1crfv__traits_3_013_00_014_01_4.html',1,'ug']]],
  ['crfvgeometry_16352',['CRFVGeometry',['../../classug_1_1_c_r_f_v_geometry.html',1,'ug']]],
  ['crilut_16353',['CRILUT',['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_navier_stokes_1_1_spatial_disc_1_1_navier_stokes_1_1_spatia60aa510d8067b2999b975a01e4fe766b.html',1,'ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes']]],
  ['crilutpreconditioner_16354',['CRILUTPreconditioner',['../../../plugins/classug_1_1_c_r_i_l_u_t_preconditioner.html',1,'ug']]],
  ['crnavierstokessymbc_16355',['CRNavierStokesSymBC',['../../../plugins/classug_1_1_navier_stokes_1_1_c_r_navier_stokes_sym_b_c.html',1,'ug::NavierStokes::CRNavierStokesSymBC&lt; class &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_navier_stokes_1_1_spatial_disc_1_1_navier_stokes_1_1_spatia487ddb114c1e25f0975a4ee0f37ab19e.html',1,'ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::CRNavierStokesSymBC']]],
  ['crouzeixraviartbase_16356',['CrouzeixRaviartBase',['../../classug_1_1_crouzeix_raviart_base.html',1,'ug']]],
  ['crouzeixraviartbase_3c_20referencehexahedron_20_3e_16357',['CrouzeixRaviartBase&lt; ReferenceHexahedron &gt;',['../../classug_1_1_crouzeix_raviart_base.html',1,'']]],
  ['crouzeixraviartbase_3c_20referenceprism_20_3e_16358',['CrouzeixRaviartBase&lt; ReferencePrism &gt;',['../../classug_1_1_crouzeix_raviart_base.html',1,'']]],
  ['crouzeixraviartbase_3c_20referencepyramid_20_3e_16359',['CrouzeixRaviartBase&lt; ReferencePyramid &gt;',['../../classug_1_1_crouzeix_raviart_base.html',1,'']]],
  ['crouzeixraviartbase_3c_20referencequadrilateral_20_3e_16360',['CrouzeixRaviartBase&lt; ReferenceQuadrilateral &gt;',['../../classug_1_1_crouzeix_raviart_base.html',1,'']]],
  ['crouzeixraviartbase_3c_20referencetetrahedron_20_3e_16361',['CrouzeixRaviartBase&lt; ReferenceTetrahedron &gt;',['../../classug_1_1_crouzeix_raviart_base.html',1,'']]],
  ['crouzeixraviartbase_3c_20referencetriangle_20_3e_16362',['CrouzeixRaviartBase&lt; ReferenceTriangle &gt;',['../../classug_1_1_crouzeix_raviart_base.html',1,'']]],
  ['crouzeixraviartelemtransfer_16363',['CrouzeixRaviartElemTransfer',['../../classug_1_1_crouzeix_raviart_elem_transfer.html',1,'ug']]],
  ['crouzeixraviartlsfs_16364',['CrouzeixRaviartLSFS',['../../classug_1_1_crouzeix_raviart_l_s_f_s.html',1,'ug']]],
  ['crouzeixraviartlsfs_3c_20referencehexahedron_20_3e_16365',['CrouzeixRaviartLSFS&lt; ReferenceHexahedron &gt;',['../../classug_1_1_crouzeix_raviart_l_s_f_s_3_01_reference_hexahedron_01_4.html',1,'ug']]],
  ['crouzeixraviartlsfs_3c_20referenceprism_20_3e_16366',['CrouzeixRaviartLSFS&lt; ReferencePrism &gt;',['../../classug_1_1_crouzeix_raviart_l_s_f_s_3_01_reference_prism_01_4.html',1,'ug']]],
  ['crouzeixraviartlsfs_3c_20referencepyramid_20_3e_16367',['CrouzeixRaviartLSFS&lt; ReferencePyramid &gt;',['../../classug_1_1_crouzeix_raviart_l_s_f_s_3_01_reference_pyramid_01_4.html',1,'ug']]],
  ['crouzeixraviartlsfs_3c_20referencequadrilateral_20_3e_16368',['CrouzeixRaviartLSFS&lt; ReferenceQuadrilateral &gt;',['../../classug_1_1_crouzeix_raviart_l_s_f_s_3_01_reference_quadrilateral_01_4.html',1,'ug']]],
  ['crouzeixraviartlsfs_3c_20referencetetrahedron_20_3e_16369',['CrouzeixRaviartLSFS&lt; ReferenceTetrahedron &gt;',['../../classug_1_1_crouzeix_raviart_l_s_f_s_3_01_reference_tetrahedron_01_4.html',1,'ug']]],
  ['crouzeixraviartlsfs_3c_20referencetriangle_20_3e_16370',['CrouzeixRaviartLSFS&lt; ReferenceTriangle &gt;',['../../classug_1_1_crouzeix_raviart_l_s_f_s_3_01_reference_triangle_01_4.html',1,'ug']]],
  ['crsmagorinskyturbviscdata_16371',['CRSmagorinskyTurbViscData',['../../../plugins/classug_1_1_navier_stokes_1_1_c_r_smagorinsky_turb_visc_data.html',1,'ug::NavierStokes::CRSmagorinskyTurbViscData&lt; class &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_navier_stokes_1_1_spatial_disc_1_1_navier_stokes_1_1_spatia771344b62df390e35c5ff1252fc01c72.html',1,'ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::CRSmagorinskyTurbViscData']]],
  ['cuckooclock_16372',['CuckooClock',['../../classug_1_1_cuckoo_clock.html',1,'ug::CuckooClock'],['../../regdocu/classug4_bridge_1_1_util_1_1_cuckoo_clock.html',1,'ug4Bridge::Util::CuckooClock']]],
  ['cudamanager_16373',['CUDAManager',['../../classug_1_1_c_u_d_a_manager.html',1,'ug']]],
  ['customquadrilateral_16374',['CustomQuadrilateral',['../../classug_1_1_custom_quadrilateral.html',1,'ug']]],
  ['customquadrilateral_3c_20constrainedquadrilateral_2c_20constrainedface_2c_20constrainedtriangle_2c_20constrainedquadrilateral_20_3e_16375',['CustomQuadrilateral&lt; ConstrainedQuadrilateral, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral &gt;',['../../classug_1_1_custom_quadrilateral.html',1,'']]],
  ['customquadrilateral_3c_20constrainingquadrilateral_2c_20constrainingface_2c_20constrainingtriangle_2c_20constrainingquadrilateral_20_3e_16376',['CustomQuadrilateral&lt; ConstrainingQuadrilateral, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral &gt;',['../../classug_1_1_custom_quadrilateral.html',1,'']]],
  ['customquadrilateral_3c_20quadrilateral_2c_20face_2c_20triangle_2c_20quadrilateral_20_3e_16377',['CustomQuadrilateral&lt; Quadrilateral, Face, Triangle, Quadrilateral &gt;',['../../classug_1_1_custom_quadrilateral.html',1,'']]],
  ['customtriangle_16378',['CustomTriangle',['../../classug_1_1_custom_triangle.html',1,'ug']]],
  ['customtriangle_3c_20constrainedtriangle_2c_20constrainedface_2c_20constrainedtriangle_2c_20constrainedquadrilateral_20_3e_16379',['CustomTriangle&lt; ConstrainedTriangle, ConstrainedFace, ConstrainedTriangle, ConstrainedQuadrilateral &gt;',['../../classug_1_1_custom_triangle.html',1,'']]],
  ['customtriangle_3c_20constrainingtriangle_2c_20constrainingface_2c_20constrainingtriangle_2c_20constrainingquadrilateral_20_3e_16380',['CustomTriangle&lt; ConstrainingTriangle, ConstrainingFace, ConstrainingTriangle, ConstrainingQuadrilateral &gt;',['../../classug_1_1_custom_triangle.html',1,'']]],
  ['customtriangle_3c_20triangle_2c_20face_2c_20triangle_2c_20quadrilateral_20_3e_16381',['CustomTriangle&lt; Triangle, Face, Triangle, Quadrilateral &gt;',['../../classug_1_1_custom_triangle.html',1,'']]],
  ['customvertexgroup_16382',['CustomVertexGroup',['../../classug_1_1_custom_vertex_group.html',1,'ug']]],
  ['cylindercutprojector_16383',['CylinderCutProjector',['../../classug_1_1_cylinder_cut_projector.html',1,'ug::CylinderCutProjector'],['../../regdocu/classug4_bridge_1_1_grid_1_1_cylinder_cut_projector.html',1,'ug4Bridge::Grid::CylinderCutProjector']]],
  ['cylinderprojector_16384',['CylinderProjector',['../../classug_1_1_cylinder_projector.html',1,'ug::CylinderProjector'],['../../regdocu/classug4_bridge_1_1_grid_1_1_cylinder_projector.html',1,'ug4Bridge::Grid::CylinderProjector']]]
];
