var searchData=
[
  ['raster_18034',['Raster',['../../classug_1_1_raster.html',1,'ug']]],
  ['rasterlayerdesc_18035',['RasterLayerDesc',['../../structug_1_1_raster_layer_desc.html',1,'ug::RasterLayerDesc'],['../../regdocu/classug4_bridge_1_1_grid_1_1_raster_layer_desc.html',1,'ug4Bridge::Grid::RasterLayerDesc']]],
  ['rasterlayers_18036',['RasterLayers',['../../regdocu/classug4_bridge_1_1_grid_1_1_raster_layers.html',1,'ug4Bridge::Grid::RasterLayers'],['../../classug_1_1_raster_layers.html',1,'ug::RasterLayers']]],
  ['rasterlayersprojector_18037',['RasterLayersProjector',['../../classug_1_1_raster_layers_projector.html',1,'ug']]],
  ['rasternumberdata_18038',['RasterNumberData',['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_raster_number_data.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['rasteruserdata_18039',['RasterUserData',['../../classug_1_1_raster_user_data.html',1,'ug']]],
  ['rawuserdatawrapper_18040',['RawUserDataWrapper',['../../structug_1_1bridge_1_1lua_1_1_raw_user_data_wrapper.html',1,'ug::bridge::lua']]],
  ['rayelemintersectionrecord_18041',['RayElemIntersectionRecord',['../../structug_1_1_ray_elem_intersection_record.html',1,'ug']]],
  ['record_18042',['Record',['../../structug_1_1impl_1_1_project_vertices_to_close_edges_1_1_record.html',1,'ug::impl::ProjectVerticesToCloseEdges']]],
  ['reduce_5ftraits_18043',['reduce_traits',['../../structpcl_1_1reduce__traits.html',1,'pcl']]],
  ['reduce_5ftraits_3c_20double_20_3e_18044',['reduce_traits&lt; double &gt;',['../../structpcl_1_1reduce__traits_3_01double_01_4.html',1,'pcl']]],
  ['reduce_5ftraits_3c_20float_20_3e_18045',['reduce_traits&lt; float &gt;',['../../structpcl_1_1reduce__traits_3_01float_01_4.html',1,'pcl']]],
  ['reducer_18046',['Reducer',['../../classpcl_1_1_reducer.html',1,'pcl']]],
  ['reference_5felement_5ftraits_18047',['reference_element_traits',['../../structug_1_1reference__element__traits.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainededge_20_3e_18048',['reference_element_traits&lt; ConstrainedEdge &gt;',['../../structug_1_1reference__element__traits_3_01_constrained_edge_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainedquadrilateral_20_3e_18049',['reference_element_traits&lt; ConstrainedQuadrilateral &gt;',['../../structug_1_1reference__element__traits_3_01_constrained_quadrilateral_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainedtriangle_20_3e_18050',['reference_element_traits&lt; ConstrainedTriangle &gt;',['../../structug_1_1reference__element__traits_3_01_constrained_triangle_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainedvertex_20_3e_18051',['reference_element_traits&lt; ConstrainedVertex &gt;',['../../structug_1_1reference__element__traits_3_01_constrained_vertex_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainingedge_20_3e_18052',['reference_element_traits&lt; ConstrainingEdge &gt;',['../../structug_1_1reference__element__traits_3_01_constraining_edge_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainingquadrilateral_20_3e_18053',['reference_element_traits&lt; ConstrainingQuadrilateral &gt;',['../../structug_1_1reference__element__traits_3_01_constraining_quadrilateral_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20constrainingtriangle_20_3e_18054',['reference_element_traits&lt; ConstrainingTriangle &gt;',['../../structug_1_1reference__element__traits_3_01_constraining_triangle_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20edge_20_3e_18055',['reference_element_traits&lt; Edge &gt;',['../../structug_1_1reference__element__traits_3_01_edge_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20hexahedron_20_3e_18056',['reference_element_traits&lt; Hexahedron &gt;',['../../structug_1_1reference__element__traits_3_01_hexahedron_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20octahedron_20_3e_18057',['reference_element_traits&lt; Octahedron &gt;',['../../structug_1_1reference__element__traits_3_01_octahedron_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20prism_20_3e_18058',['reference_element_traits&lt; Prism &gt;',['../../structug_1_1reference__element__traits_3_01_prism_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20pyramid_20_3e_18059',['reference_element_traits&lt; Pyramid &gt;',['../../structug_1_1reference__element__traits_3_01_pyramid_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20quadrilateral_20_3e_18060',['reference_element_traits&lt; Quadrilateral &gt;',['../../structug_1_1reference__element__traits_3_01_quadrilateral_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20regularedge_20_3e_18061',['reference_element_traits&lt; RegularEdge &gt;',['../../structug_1_1reference__element__traits_3_01_regular_edge_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20regularvertex_20_3e_18062',['reference_element_traits&lt; RegularVertex &gt;',['../../structug_1_1reference__element__traits_3_01_regular_vertex_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20tetrahedron_20_3e_18063',['reference_element_traits&lt; Tetrahedron &gt;',['../../structug_1_1reference__element__traits_3_01_tetrahedron_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20triangle_20_3e_18064',['reference_element_traits&lt; Triangle &gt;',['../../structug_1_1reference__element__traits_3_01_triangle_01_4.html',1,'ug']]],
  ['reference_5felement_5ftraits_3c_20vertex_20_3e_18065',['reference_element_traits&lt; Vertex &gt;',['../../structug_1_1reference__element__traits_3_01_vertex_01_4.html',1,'ug']]],
  ['referenceedge_18066',['ReferenceEdge',['../../classug_1_1_reference_edge.html',1,'ug']]],
  ['referenceelement_18067',['ReferenceElement',['../../classug_1_1_reference_element.html',1,'ug']]],
  ['referenceelementprovider_18068',['ReferenceElementProvider',['../../classug_1_1_reference_element_provider.html',1,'ug']]],
  ['referencehexahedron_18069',['ReferenceHexahedron',['../../classug_1_1_reference_hexahedron.html',1,'ug']]],
  ['referencemapping_18070',['ReferenceMapping',['../../classug_1_1_reference_mapping.html',1,'ug']]],
  ['referencemapping_3c_20ref_5felem_5ftype_2c_20worlddim_20_3e_18071',['ReferenceMapping&lt; ref_elem_type, worldDim &gt;',['../../classug_1_1_reference_mapping.html',1,'ReferenceMapping&lt; ref_elem_type, worldDim &gt;'],['../../classug_1_1_reference_mapping.html',1,'ug::ReferenceMapping&lt; ref_elem_type, worldDim &gt;']]],
  ['referencemapping_3c_20referenceedge_2c_20tworlddim_20_3e_18072',['ReferenceMapping&lt; ReferenceEdge, TWorldDim &gt;',['../../classug_1_1_reference_mapping_3_01_reference_edge_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencehexahedron_2c_20tworlddim_20_3e_18073',['ReferenceMapping&lt; ReferenceHexahedron, TWorldDim &gt;',['../../classug_1_1_reference_mapping_3_01_reference_hexahedron_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referenceoctahedron_2c_20tworlddim_20_3e_18074',['ReferenceMapping&lt; ReferenceOctahedron, TWorldDim &gt;',['../../classug_1_1_reference_mapping_3_01_reference_octahedron_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referenceprism_2c_20tworlddim_20_3e_18075',['ReferenceMapping&lt; ReferencePrism, TWorldDim &gt;',['../../classug_1_1_reference_mapping_3_01_reference_prism_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencepyramid_2c_20tworlddim_20_3e_18076',['ReferenceMapping&lt; ReferencePyramid, TWorldDim &gt;',['../../classug_1_1_reference_mapping_3_01_reference_pyramid_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencequadrilateral_2c_20tworlddim_20_3e_18077',['ReferenceMapping&lt; ReferenceQuadrilateral, TWorldDim &gt;',['../../classug_1_1_reference_mapping_3_01_reference_quadrilateral_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencetetrahedron_2c_20tworlddim_20_3e_18078',['ReferenceMapping&lt; ReferenceTetrahedron, TWorldDim &gt;',['../../classug_1_1_reference_mapping_3_01_reference_tetrahedron_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencetriangle_2c_20tworlddim_20_3e_18079',['ReferenceMapping&lt; ReferenceTriangle, TWorldDim &gt;',['../../classug_1_1_reference_mapping_3_01_reference_triangle_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemapping_3c_20referencevertex_2c_20tworlddim_20_3e_18080',['ReferenceMapping&lt; ReferenceVertex, TWorldDim &gt;',['../../classug_1_1_reference_mapping_3_01_reference_vertex_00_01_t_world_dim_01_4.html',1,'ug']]],
  ['referencemappingprovider_18081',['ReferenceMappingProvider',['../../classug_1_1_reference_mapping_provider.html',1,'ug']]],
  ['referenceoctahedron_18082',['ReferenceOctahedron',['../../classug_1_1_reference_octahedron.html',1,'ug']]],
  ['referenceprism_18083',['ReferencePrism',['../../classug_1_1_reference_prism.html',1,'ug']]],
  ['referencepyramid_18084',['ReferencePyramid',['../../classug_1_1_reference_pyramid.html',1,'ug']]],
  ['referencequadrilateral_18085',['ReferenceQuadrilateral',['../../classug_1_1_reference_quadrilateral.html',1,'ug']]],
  ['referencetetrahedron_18086',['ReferenceTetrahedron',['../../classug_1_1_reference_tetrahedron.html',1,'ug']]],
  ['referencetriangle_18087',['ReferenceTriangle',['../../classug_1_1_reference_triangle.html',1,'ug']]],
  ['referencevertex_18088',['ReferenceVertex',['../../classug_1_1_reference_vertex.html',1,'ug']]],
  ['refinementprojector_18089',['RefinementProjector',['../../classug_1_1_refinement_projector.html',1,'ug::RefinementProjector'],['../../regdocu/classug4_bridge_1_1_grid_1_1_refinement_projector.html',1,'ug4Bridge::Grid::RefinementProjector']]],
  ['regalgebra_18090',['RegAlgebra',['../../structug_1_1bridge_1_1_register_domain_algebra_dependent_1_1_reg_algebra.html',1,'ug::bridge::RegisterDomainAlgebraDependent']]],
  ['regend_18091',['RegEnd',['../../structug_1_1bridge_1_1_register_domain_algebra_dependent_1_1_reg_end.html',1,'ug::bridge::RegisterDomainAlgebraDependent::RegEnd'],['../../structug_1_1bridge_1_1_register_algebra_dependent_1_1_reg_end.html',1,'ug::bridge::RegisterAlgebraDependent::RegEnd'],['../../structug_1_1bridge_1_1_algebra_type_i_d_provider_1_1_register_algebra_indices_1_1_reg_end.html',1,'ug::bridge::AlgebraTypeIDProvider::RegisterAlgebraIndices&lt; class &gt;::RegEnd'],['../../structug_1_1bridge_1_1_register_domain_dependent_1_1_reg_end.html',1,'ug::bridge::RegisterDomainDependent::RegEnd']]],
  ['region_18092',['Region',['../../../plugins/structug_1_1_navier_stokes_1_1_region.html',1,'ug::NavierStokes']]],
  ['register_5fas_5fobserver_18093',['register_as_observer',['../../structug_1_1_copy_attachment_handler_1_1register__as__observer.html',1,'ug::CopyAttachmentHandler']]],
  ['register_5fas_5fobserver_3c_20edge_2c_20dummy_20_3e_18094',['register_as_observer&lt; Edge, Dummy &gt;',['../../structug_1_1_copy_attachment_handler_1_1register__as__observer_3_01_edge_00_01_dummy_01_4.html',1,'ug::CopyAttachmentHandler']]],
  ['register_5fas_5fobserver_3c_20face_2c_20dummy_20_3e_18095',['register_as_observer&lt; Face, Dummy &gt;',['../../structug_1_1_copy_attachment_handler_1_1register__as__observer_3_01_face_00_01_dummy_01_4.html',1,'ug::CopyAttachmentHandler']]],
  ['register_5fas_5fobserver_3c_20vertex_2c_20dummy_20_3e_18096',['register_as_observer&lt; Vertex, Dummy &gt;',['../../structug_1_1_copy_attachment_handler_1_1register__as__observer_3_01_vertex_00_01_dummy_01_4.html',1,'ug::CopyAttachmentHandler']]],
  ['register_5fas_5fobserver_3c_20volume_2c_20dummy_20_3e_18097',['register_as_observer&lt; Volume, Dummy &gt;',['../../structug_1_1_copy_attachment_handler_1_1register__as__observer_3_01_volume_00_01_dummy_01_4.html',1,'ug::CopyAttachmentHandler']]],
  ['registeralgebradependent_18098',['RegisterAlgebraDependent',['../../structug_1_1bridge_1_1_register_algebra_dependent.html',1,'ug::bridge']]],
  ['registeralgebraindices_18099',['RegisterAlgebraIndices',['../../structug_1_1bridge_1_1_algebra_type_i_d_provider_1_1_register_algebra_indices.html',1,'ug::bridge::AlgebraTypeIDProvider']]],
  ['registerdomain1dalgebradependent_18100',['RegisterDomain1dAlgebraDependent',['../../structug_1_1bridge_1_1_register_domain1d_algebra_dependent.html',1,'ug::bridge']]],
  ['registerdomain2d3dalgebradependent_18101',['RegisterDomain2d3dAlgebraDependent',['../../structug_1_1bridge_1_1_register_domain2d3d_algebra_dependent.html',1,'ug::bridge']]],
  ['registerdomain2dalgebradependent_18102',['RegisterDomain2dAlgebraDependent',['../../structug_1_1bridge_1_1_register_domain2d_algebra_dependent.html',1,'ug::bridge']]],
  ['registerdomain3dalgebradependent_18103',['RegisterDomain3dAlgebraDependent',['../../structug_1_1bridge_1_1_register_domain3d_algebra_dependent.html',1,'ug::bridge']]],
  ['registerdomainalgebradependent_18104',['RegisterDomainAlgebraDependent',['../../structug_1_1bridge_1_1_register_domain_algebra_dependent.html',1,'ug::bridge']]],
  ['registerdomaindependent_18105',['RegisterDomainDependent',['../../structug_1_1bridge_1_1_register_domain_dependent.html',1,'ug::bridge']]],
  ['registerfv1_18106',['RegisterFV1',['../../structug_1_1_f_v1_inner_boundary_elem_disc_1_1_register_f_v1.html',1,'ug::FV1InnerBoundaryElemDisc&lt; class &gt;::RegisterFV1'],['../../../plugins/structug_1_1_navier_stokes_1_1_navier_stokes_sym_b_c_f_v1_1_1_register_f_v1.html',1,'ug::NavierStokes::NavierStokesSymBCFV1&lt; class &gt;::RegisterFV1']]],
  ['registerlocaldiscr_18107',['RegisterLocalDiscr',['../../../plugins/structug_1_1_electromagnetism_1_1_nedelec_project_1_1_aux_laplace_loc_ass_1_1_register_local_discr.html',1,'ug::Electromagnetism::NedelecProject::AuxLaplaceLocAss::RegisterLocalDiscr'],['../../../plugins/structug_1_1_electromagnetism_1_1_eddy_current___e___nedelec_1_1_register_local_discr.html',1,'ug::Electromagnetism::EddyCurrent_E_Nedelec&lt; class, class &gt;::RegisterLocalDiscr'],['../../../plugins/structug_1_1_electromagnetism_1_1_nedelec_loop_current_1_1_aux_laplace_loc_ass_1_1_register_local_discr.html',1,'ug::Electromagnetism::NedelecLoopCurrent::AuxLaplaceLocAss::RegisterLocalDiscr'],['../../../plugins/structug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_fract_f_v1_1_1_register_local_discr.html',1,'ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1&lt; TDomain &gt;::RegisterLocalDiscr']]],
  ['registertypepairfunctor_18108',['RegisterTypePairFunctor',['../../structug_1_1detail_1_1_register_type_pair_functor.html',1,'ug::detail']]],
  ['registry_18109',['Registry',['../../classug_1_1bridge_1_1_registry.html',1,'ug::bridge']]],
  ['regnext_18110',['RegNext',['../../structug_1_1bridge_1_1_register_algebra_dependent_1_1_reg_next.html',1,'ug::bridge::RegisterAlgebraDependent&lt; class, class &gt;::RegNext'],['../../structug_1_1bridge_1_1_register_domain_dependent_1_1_reg_next.html',1,'ug::bridge::RegisterDomainDependent&lt; Functionality, List &gt;::RegNext'],['../../structug_1_1bridge_1_1_algebra_type_i_d_provider_1_1_register_algebra_indices_1_1_reg_next.html',1,'ug::bridge::AlgebraTypeIDProvider::RegisterAlgebraIndices&lt; class &gt;::RegNext']]],
  ['regnextdomain_18111',['RegNextDomain',['../../structug_1_1bridge_1_1_register_domain_algebra_dependent_1_1_reg_next_domain.html',1,'ug::bridge::RegisterDomainAlgebraDependent']]],
  ['regnextdomainalgebra_18112',['RegNextDomainAlgebra',['../../structug_1_1bridge_1_1_register_domain_algebra_dependent_1_1_reg_next_domain_algebra.html',1,'ug::bridge::RegisterDomainAlgebraDependent']]],
  ['regularedge_18113',['RegularEdge',['../../classug_1_1_regular_edge.html',1,'ug']]],
  ['regularvertex_18114',['RegularVertex',['../../classug_1_1_regular_vertex.html',1,'ug']]],
  ['relativedensityupdater_18115',['RelativeDensityUpdater',['../../../plugins/classug_1_1_small_strain_mechanics_1_1_relative_density_updater.html',1,'ug::SmallStrainMechanics::RelativeDensityUpdater&lt; class &gt;'],['../../regdocu/classug4_bridge_1_1_spatial_disc_1_1_small_strain_mechanics_1_1_relative_density_updater.html',1,'ug4Bridge::SpatialDisc::SmallStrainMechanics::RelativeDensityUpdater']]],
  ['repeatedcol_18116',['RepeatedCol',['../../structug_1_1_string_table_stream_1_1_repeated_col.html',1,'ug::StringTableStream']]],
  ['reservablearray2_18117',['ReservableArray2',['../../classug_1_1_reservable_array2.html',1,'ug']]],
  ['revisioncounter_18118',['RevisionCounter',['../../classug_1_1_revision_counter.html',1,'ug']]],
  ['rotatingcone2d_18119',['RotatingCone2d',['../../classug_1_1_rotating_cone2d.html',1,'ug::RotatingCone2d'],['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_rotating_cone2d.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData::RotatingCone2d']]],
  ['rotatingvelocity2d_18120',['RotatingVelocity2d',['../../classug_1_1_rotating_velocity2d.html',1,'ug::RotatingVelocity2d'],['../../regdocu/classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_rotating_velocity2d.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData::RotatingVelocity2d']]],
  ['row_5fiterator_18121',['row_iterator',['../../class_scalar_matrix_adapter_1_1row__iterator.html',1,'ScalarMatrixAdapter::row_iterator'],['../../class_scalar_sub_matrix_adapter_1_1row__iterator.html',1,'ScalarSubMatrixAdapter::row_iterator'],['../../classug_1_1_map_sparse_matrix_1_1row__iterator.html',1,'ug::MapSparseMatrix&lt; TValueType &gt;::row_iterator'],['../../classug_1_1_g_p_u_sparse_matrix_1_1row__iterator.html',1,'ug::GPUSparseMatrix&lt; TValueType &gt;::row_iterator'],['../../classug_1_1_sparse_matrix_1_1row__iterator.html',1,'ug::SparseMatrix::row_iterator']]],
  ['rowsendingscheme_18122',['RowSendingScheme',['../../classug_1_1_row_sending_scheme.html',1,'ug']]]
];
