var annotated_dup =
[
    [ "ug", "namespaceug.html", [
      [ "bridge", null, [
        [ "SuperLUBridge", "namespaceug_1_1bridge_1_1_super_l_u_bridge.html", [
          [ "Functionality", "structug_1_1bridge_1_1_super_l_u_bridge_1_1_functionality.html", "structug_1_1bridge_1_1_super_l_u_bridge_1_1_functionality" ]
        ] ],
        [ "func_traits< xp::xproperty< V, M > O::* >", "structug_1_1bridge_1_1func__traits_3_01xp_1_1xproperty_3_01_v_00_01_m_01_4_01_o_1_1_5_01_4.html", "structug_1_1bridge_1_1func__traits_3_01xp_1_1xproperty_3_01_v_00_01_m_01_4_01_o_1_1_5_01_4" ],
        [ "xproperty_traits", "structug_1_1bridge_1_1xproperty__traits.html", "structug_1_1bridge_1_1xproperty__traits" ]
      ] ],
      [ "ConvectionDiffusionPlugin", "namespaceug_1_1_convection_diffusion_plugin.html", [
        [ "cd_line_sss_data", "classug_1_1_convection_diffusion_plugin_1_1cd__line__sss__data.html", null ],
        [ "cd_point_sss_data", "classug_1_1_convection_diffusion_plugin_1_1cd__point__sss__data.html", null ],
        [ "cd_sss_data", "classug_1_1_convection_diffusion_plugin_1_1cd__sss__data.html", "classug_1_1_convection_diffusion_plugin_1_1cd__sss__data" ],
        [ "CDSingularSourcesAndSinks", "classug_1_1_convection_diffusion_plugin_1_1_c_d_singular_sources_and_sinks.html", "classug_1_1_convection_diffusion_plugin_1_1_c_d_singular_sources_and_sinks" ],
        [ "ConvectionDiffusionBase", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_base.html", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_base" ],
        [ "ConvectionDiffusionFE", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_e.html", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_e" ],
        [ "ConvectionDiffusionFractFV1", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_fract_f_v1.html", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_fract_f_v1" ],
        [ "ConvectionDiffusionFV", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_v.html", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_v" ],
        [ "ConvectionDiffusionFV1", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_v1.html", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_v1" ],
        [ "ConvectionDiffusionFVCR", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_v_c_r.html", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_f_v_c_r" ],
        [ "ConvectionDiffusionStabFE", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_stab_f_e.html", "classug_1_1_convection_diffusion_plugin_1_1_convection_diffusion_stab_f_e" ],
        [ "Functionality", "structug_1_1_convection_diffusion_plugin_1_1_functionality.html", "structug_1_1_convection_diffusion_plugin_1_1_functionality" ],
        [ "Functionality2d3d", "structug_1_1_convection_diffusion_plugin_1_1_functionality2d3d.html", "structug_1_1_convection_diffusion_plugin_1_1_functionality2d3d" ],
        [ "line_sss_marker", "classug_1_1_convection_diffusion_plugin_1_1line__sss__marker.html", "classug_1_1_convection_diffusion_plugin_1_1line__sss__marker" ],
        [ "point_sss_marker", "classug_1_1_convection_diffusion_plugin_1_1point__sss__marker.html", "classug_1_1_convection_diffusion_plugin_1_1point__sss__marker" ]
      ] ],
      [ "d3f", "namespaceug_1_1d3f.html", [
        [ "ConstantSohlGradient", "classug_1_1d3f_1_1_constant_sohl_gradient.html", "classug_1_1d3f_1_1_constant_sohl_gradient" ],
        [ "dd_line_sss_data", "classug_1_1d3f_1_1dd__line__sss__data.html", null ],
        [ "dd_point_sss_data", "classug_1_1d3f_1_1dd__point__sss__data.html", null ],
        [ "dd_sss_data", "classug_1_1d3f_1_1dd__sss__data.html", "classug_1_1d3f_1_1dd__sss__data" ],
        [ "DDSingularSourcesAndSinks", "classug_1_1d3f_1_1_d_d_singular_sources_and_sinks.html", null ],
        [ "DensityDrivenFlowBase", "classug_1_1d3f_1_1_density_driven_flow_base.html", "classug_1_1d3f_1_1_density_driven_flow_base" ],
        [ "DensityDrivenFlowFV", "classug_1_1d3f_1_1_density_driven_flow_f_v.html", "classug_1_1d3f_1_1_density_driven_flow_f_v" ],
        [ "DensityDrivenFlowFV1", "classug_1_1d3f_1_1_density_driven_flow_f_v1.html", "classug_1_1d3f_1_1_density_driven_flow_f_v1" ],
        [ "ExfiltrationFlux", "classug_1_1d3f_1_1_exfiltration_flux.html", "classug_1_1d3f_1_1_exfiltration_flux" ],
        [ "FlowVolStabData", "classug_1_1d3f_1_1_flow_vol_stab_data.html", "classug_1_1d3f_1_1_flow_vol_stab_data" ],
        [ "FractalField", "classug_1_1d3f_1_1_fractal_field.html", "classug_1_1d3f_1_1_fractal_field" ],
        [ "FractDDF_FV1", "classug_1_1d3f_1_1_fract_d_d_f___f_v1.html", "classug_1_1d3f_1_1_fract_d_d_f___f_v1" ],
        [ "FractDimadapt", "classug_1_1d3f_1_1_fract_dimadapt.html", "classug_1_1d3f_1_1_fract_dimadapt" ],
        [ "FractGFEval", "classug_1_1d3f_1_1_fract_g_f_eval.html", "classug_1_1d3f_1_1_fract_g_f_eval" ],
        [ "FractPF_FV1", "classug_1_1d3f_1_1_fract_p_f___f_v1.html", "classug_1_1d3f_1_1_fract_p_f___f_v1" ],
        [ "FractTHF_FV1", "classug_1_1d3f_1_1_fract_t_h_f___f_v1.html", "classug_1_1d3f_1_1_fract_t_h_f___f_v1" ],
        [ "FracturedFunctionality", "structug_1_1d3f_1_1_fractured_functionality.html", "structug_1_1d3f_1_1_fractured_functionality" ],
        [ "Functionality", "structug_1_1d3f_1_1_functionality.html", "structug_1_1d3f_1_1_functionality" ],
        [ "FVSingularSourcesAndSinksKD", "classug_1_1d3f_1_1_f_v_singular_sources_and_sinks_k_d.html", "classug_1_1d3f_1_1_f_v_singular_sources_and_sinks_k_d" ],
        [ "InOutFlowBC", "classug_1_1d3f_1_1_in_out_flow_b_c.html", "classug_1_1d3f_1_1_in_out_flow_b_c" ],
        [ "ISubmodule", "classug_1_1d3f_1_1_i_submodule.html", "classug_1_1d3f_1_1_i_submodule" ],
        [ "ISubmoduleBridge", "classug_1_1d3f_1_1_i_submodule_bridge.html", "classug_1_1d3f_1_1_i_submodule_bridge" ],
        [ "ISurjectiveInterface", "classug_1_1d3f_1_1_i_surjective_interface.html", "classug_1_1d3f_1_1_i_surjective_interface" ],
        [ "LevelSetFunctionality", "structug_1_1d3f_1_1_level_set_functionality.html", "structug_1_1d3f_1_1_level_set_functionality" ],
        [ "line_sss_marker", "classug_1_1d3f_1_1line__sss__marker.html", "classug_1_1d3f_1_1line__sss__marker" ],
        [ "LineBVHNode", "structug_1_1d3f_1_1_line_b_v_h_node.html", "structug_1_1d3f_1_1_line_b_v_h_node" ],
        [ "LineBVHTree", "classug_1_1d3f_1_1_line_b_v_h_tree.html", "classug_1_1d3f_1_1_line_b_v_h_tree" ],
        [ "LSPositionAtPoints", "classug_1_1d3f_1_1_l_s_position_at_points.html", "classug_1_1d3f_1_1_l_s_position_at_points" ],
        [ "LSPositionZ", "classug_1_1d3f_1_1_l_s_position_z.html", "classug_1_1d3f_1_1_l_s_position_z" ],
        [ "LSPosZCellToVrtData", "classug_1_1d3f_1_1_l_s_pos_z_cell_to_vrt_data.html", "classug_1_1d3f_1_1_l_s_pos_z_cell_to_vrt_data" ],
        [ "LSPosZData", "classug_1_1d3f_1_1_l_s_pos_z_data.html", "classug_1_1d3f_1_1_l_s_pos_z_data" ],
        [ "LSPosZData_ElemEvalPnt", "classug_1_1d3f_1_1_l_s_pos_z_data___elem_eval_pnt.html", "classug_1_1d3f_1_1_l_s_pos_z_data___elem_eval_pnt" ],
        [ "LSPosZData_ElemEvalPnt< WDim, TAAPos, RegularVertex >", "classug_1_1d3f_1_1_l_s_pos_z_data___elem_eval_pnt_3_01_w_dim_00_01_t_a_a_pos_00_01_regular_vertex_01_4.html", "classug_1_1d3f_1_1_l_s_pos_z_data___elem_eval_pnt_3_01_w_dim_00_01_t_a_a_pos_00_01_regular_vertex_01_4" ],
        [ "ManningRoughness1d", "classug_1_1d3f_1_1_manning_roughness1d.html", "classug_1_1d3f_1_1_manning_roughness1d" ],
        [ "OutFlowBC", "classug_1_1d3f_1_1_out_flow_b_c.html", "classug_1_1d3f_1_1_out_flow_b_c" ],
        [ "OutflowIntegrationObserver", "classug_1_1d3f_1_1_outflow_integration_observer.html", "classug_1_1d3f_1_1_outflow_integration_observer" ],
        [ "point_sss_marker", "classug_1_1d3f_1_1point__sss__marker.html", "classug_1_1d3f_1_1point__sss__marker" ],
        [ "PolygonalRegions", "classug_1_1d3f_1_1_polygonal_regions.html", "classug_1_1d3f_1_1_polygonal_regions" ],
        [ "RasterID", "classug_1_1d3f_1_1_raster_i_d.html", "classug_1_1d3f_1_1_raster_i_d" ],
        [ "RichardsFreeSurfaceHeight", "classug_1_1d3f_1_1_richards_free_surface_height.html", "classug_1_1d3f_1_1_richards_free_surface_height" ],
        [ "river_line_sss_data", "classug_1_1d3f_1_1river__line__sss__data.html", null ],
        [ "river_point_sss_data", "classug_1_1d3f_1_1river__point__sss__data.html", null ],
        [ "river_sss_data", "classug_1_1d3f_1_1river__sss__data.html", "classug_1_1d3f_1_1river__sss__data" ],
        [ "RiverFunctionality", "structug_1_1d3f_1_1_river_functionality.html", "structug_1_1d3f_1_1_river_functionality" ],
        [ "RiverFunctionality2d3d", "structug_1_1d3f_1_1_river_functionality2d3d.html", "structug_1_1d3f_1_1_river_functionality2d3d" ],
        [ "RiverFunctionality3d", "structug_1_1d3f_1_1_river_functionality3d.html", "structug_1_1d3f_1_1_river_functionality3d" ],
        [ "RiverObserver", "classug_1_1d3f_1_1_river_observer.html", "classug_1_1d3f_1_1_river_observer" ],
        [ "RiverSingularSourcesAndSinks", "classug_1_1d3f_1_1_river_singular_sources_and_sinks.html", null ],
        [ "RiverSSSManager", "classug_1_1d3f_1_1_river_s_s_s_manager.html", "classug_1_1d3f_1_1_river_s_s_s_manager" ],
        [ "SegmentNetwork", "classug_1_1d3f_1_1_segment_network.html", "classug_1_1d3f_1_1_segment_network" ],
        [ "Sohle", "classug_1_1d3f_1_1_sohle.html", "classug_1_1d3f_1_1_sohle" ],
        [ "StVenantElemDisc", "classug_1_1d3f_1_1_st_venant_elem_disc.html", "classug_1_1d3f_1_1_st_venant_elem_disc" ],
        [ "StVenantElemDiscFactory", "classug_1_1d3f_1_1_st_venant_elem_disc_factory.html", "classug_1_1d3f_1_1_st_venant_elem_disc_factory" ],
        [ "StVenantParameters", "structug_1_1d3f_1_1_st_venant_parameters.html", "structug_1_1d3f_1_1_st_venant_parameters" ],
        [ "StVenantSubmodule", "classug_1_1d3f_1_1_st_venant_submodule.html", "classug_1_1d3f_1_1_st_venant_submodule" ],
        [ "StVenantWallBndDir", "classug_1_1d3f_1_1_st_venant_wall_bnd_dir.html", "classug_1_1d3f_1_1_st_venant_wall_bnd_dir" ],
        [ "th_line_sss_data", "classug_1_1d3f_1_1th__line__sss__data.html", null ],
        [ "th_point_sss_data", "classug_1_1d3f_1_1th__point__sss__data.html", null ],
        [ "th_sss_data", "classug_1_1d3f_1_1th__sss__data.html", "classug_1_1d3f_1_1th__sss__data" ],
        [ "ThermohalineFlow", "classug_1_1d3f_1_1_thermohaline_flow.html", "classug_1_1d3f_1_1_thermohaline_flow" ],
        [ "THSingularSourcesAndSinks", "classug_1_1d3f_1_1_t_h_singular_sources_and_sinks.html", null ],
        [ "TimestepObserver", "classug_1_1d3f_1_1_timestep_observer.html", "classug_1_1d3f_1_1_timestep_observer" ],
        [ "UnionsOfBoxes", "classug_1_1d3f_1_1_unions_of_boxes.html", "classug_1_1d3f_1_1_unions_of_boxes" ],
        [ "ValSurfProjData", "classug_1_1d3f_1_1_val_surf_proj_data.html", "classug_1_1d3f_1_1_val_surf_proj_data" ],
        [ "ValueById", "classug_1_1d3f_1_1_value_by_id.html", "classug_1_1d3f_1_1_value_by_id" ],
        [ "VertexLowDimRecharge", "classug_1_1d3f_1_1_vertex_low_dim_recharge.html", "classug_1_1d3f_1_1_vertex_low_dim_recharge" ],
        [ "VertexRiverRecharge", "classug_1_1d3f_1_1_vertex_river_recharge.html", "classug_1_1d3f_1_1_vertex_river_recharge" ],
        [ "VertexWellRecharge", "classug_1_1d3f_1_1_vertex_well_recharge.html", "classug_1_1d3f_1_1_vertex_well_recharge" ]
      ] ],
      [ "d3f_util", "namespaceug_1_1d3f__util.html", [
        [ "FunctionalityUtil", "structug_1_1d3f__util_1_1_functionality_util.html", "structug_1_1d3f__util_1_1_functionality_util" ]
      ] ],
      [ "DemoPlugin", "namespaceug_1_1_demo_plugin.html", [
        [ "DemoClass", "classug_1_1_demo_plugin_1_1_demo_class.html", "classug_1_1_demo_plugin_1_1_demo_class" ]
      ] ],
      [ "df", "namespaceug_1_1df.html", [
        [ "DFAlgebraicLeftTransform", "classug_1_1df_1_1_d_f_algebraic_left_transform.html", "classug_1_1df_1_1_d_f_algebraic_left_transform" ],
        [ "DFLeftTransform", "classug_1_1df_1_1_d_f_left_transform.html", "classug_1_1df_1_1_d_f_left_transform" ],
        [ "DFTransform", "classug_1_1df_1_1_d_f_transform.html", "classug_1_1df_1_1_d_f_transform" ]
      ] ],
      [ "DocuGen", "namespaceug_1_1_docu_gen.html", [
        [ "ClassHierarchyProvider", "classug_1_1_docu_gen_1_1_class_hierarchy_provider.html", "classug_1_1_docu_gen_1_1_class_hierarchy_provider" ],
        [ "CppGenerator", "classug_1_1_docu_gen_1_1_cpp_generator.html", "classug_1_1_docu_gen_1_1_cpp_generator" ],
        [ "UGDocuClassDescription", "classug_1_1_docu_gen_1_1_u_g_docu_class_description.html", "classug_1_1_docu_gen_1_1_u_g_docu_class_description" ],
        [ "UGRegistryGroup", "classug_1_1_docu_gen_1_1_u_g_registry_group.html", "classug_1_1_docu_gen_1_1_u_g_registry_group" ]
      ] ],
      [ "Electromagnetism", "namespaceug_1_1_electromagnetism.html", [
        [ "CalcVolPowerElemHelperClass", "classug_1_1_electromagnetism_1_1_calc_vol_power_elem_helper_class.html", "classug_1_1_electromagnetism_1_1_calc_vol_power_elem_helper_class" ],
        [ "CalcVolPowerHelperClass", "classug_1_1_electromagnetism_1_1_calc_vol_power_helper_class.html", "classug_1_1_electromagnetism_1_1_calc_vol_power_helper_class" ],
        [ "ComPol_MemCopy", "classug_1_1_electromagnetism_1_1_com_pol___mem_copy.html", "classug_1_1_electromagnetism_1_1_com_pol___mem_copy" ],
        [ "ComPol_MemOp", "classug_1_1_electromagnetism_1_1_com_pol___mem_op.html", "classug_1_1_electromagnetism_1_1_com_pol___mem_op" ],
        [ "ComputeElemFluxHelper", "classug_1_1_electromagnetism_1_1_compute_elem_flux_helper.html", "classug_1_1_electromagnetism_1_1_compute_elem_flux_helper" ],
        [ "ComputeElemFluxHelper< TGridFunc, RegularEdge >", "classug_1_1_electromagnetism_1_1_compute_elem_flux_helper_3_01_t_grid_func_00_01_regular_edge_01_4.html", "classug_1_1_electromagnetism_1_1_compute_elem_flux_helper_3_01_t_grid_func_00_01_regular_edge_01_4" ],
        [ "ComputeFluxHelper", "classug_1_1_electromagnetism_1_1_compute_flux_helper.html", "classug_1_1_electromagnetism_1_1_compute_flux_helper" ],
        [ "EddyCurrent_E_Nedelec", "classug_1_1_electromagnetism_1_1_eddy_current___e___nedelec.html", "classug_1_1_electromagnetism_1_1_eddy_current___e___nedelec" ],
        [ "EddyCurrentCurlEDependentCmpUserData", "classug_1_1_electromagnetism_1_1_eddy_current_curl_e_dependent_cmp_user_data.html", "classug_1_1_electromagnetism_1_1_eddy_current_curl_e_dependent_cmp_user_data" ],
        [ "EddyCurrentHeat", "classug_1_1_electromagnetism_1_1_eddy_current_heat.html", "classug_1_1_electromagnetism_1_1_eddy_current_heat" ],
        [ "EddyCurrentImBofEUserData", "classug_1_1_electromagnetism_1_1_eddy_current_im_bof_e_user_data.html", "classug_1_1_electromagnetism_1_1_eddy_current_im_bof_e_user_data" ],
        [ "EddyCurrentReBofEUserData", "classug_1_1_electromagnetism_1_1_eddy_current_re_bof_e_user_data.html", "classug_1_1_electromagnetism_1_1_eddy_current_re_bof_e_user_data" ],
        [ "EddyCurrentTraits", "classug_1_1_electromagnetism_1_1_eddy_current_traits.html", "classug_1_1_electromagnetism_1_1_eddy_current_traits" ],
        [ "EMaterial", "classug_1_1_electromagnetism_1_1_e_material.html", "classug_1_1_electromagnetism_1_1_e_material" ],
        [ "EMDirichlet", "classug_1_1_electromagnetism_1_1_e_m_dirichlet.html", "classug_1_1_electromagnetism_1_1_e_m_dirichlet" ],
        [ "Functionality", "structug_1_1_electromagnetism_1_1_functionality.html", "structug_1_1_electromagnetism_1_1_functionality" ],
        [ "NedelecCurlData", "classug_1_1_electromagnetism_1_1_nedelec_curl_data.html", "classug_1_1_electromagnetism_1_1_nedelec_curl_data" ],
        [ "NedelecDirichletBC", "classug_1_1_electromagnetism_1_1_nedelec_dirichlet_b_c.html", "classug_1_1_electromagnetism_1_1_nedelec_dirichlet_b_c" ],
        [ "NedelecGridFunctionData", "classug_1_1_electromagnetism_1_1_nedelec_grid_function_data.html", "classug_1_1_electromagnetism_1_1_nedelec_grid_function_data" ],
        [ "NedelecInterpolation", "classug_1_1_electromagnetism_1_1_nedelec_interpolation.html", "classug_1_1_electromagnetism_1_1_nedelec_interpolation" ],
        [ "NedelecInterpolation< TDomain, 2, 2 >", "classug_1_1_electromagnetism_1_1_nedelec_interpolation_3_01_t_domain_00_012_00_012_01_4.html", "classug_1_1_electromagnetism_1_1_nedelec_interpolation_3_01_t_domain_00_012_00_012_01_4" ],
        [ "NedelecInterpolation< TDomain, 3, 3 >", "classug_1_1_electromagnetism_1_1_nedelec_interpolation_3_01_t_domain_00_013_00_013_01_4.html", "classug_1_1_electromagnetism_1_1_nedelec_interpolation_3_01_t_domain_00_013_00_013_01_4" ],
        [ "NedelecLoopCurrent", "classug_1_1_electromagnetism_1_1_nedelec_loop_current.html", "classug_1_1_electromagnetism_1_1_nedelec_loop_current" ],
        [ "NedelecProject", "classug_1_1_electromagnetism_1_1_nedelec_project.html", "classug_1_1_electromagnetism_1_1_nedelec_project" ],
        [ "NedelecProlongationMatrixHelper", "classug_1_1_electromagnetism_1_1_nedelec_prolongation_matrix_helper.html", "classug_1_1_electromagnetism_1_1_nedelec_prolongation_matrix_helper" ],
        [ "NedelecProlongationMatrixHelper< TDomain, TAlgebra, RegularEdge >", "classug_1_1_electromagnetism_1_1_nedelec_prolongation_matrix_helper_3_01_t_domain_00_01_t_algebra_00_01_regular_edge_01_4.html", "classug_1_1_electromagnetism_1_1_nedelec_prolongation_matrix_helper_3_01_t_domain_00_01_t_algebra_00_01_regular_edge_01_4" ],
        [ "NedelecSigmaEData", "classug_1_1_electromagnetism_1_1_nedelec_sigma_e_data.html", "classug_1_1_electromagnetism_1_1_nedelec_sigma_e_data" ],
        [ "NedelecT1_LDisc", "classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc.html", "classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc" ],
        [ "NedelecT1_LDisc< TDomain, Tetrahedron >", "classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc_3_01_t_domain_00_01_tetrahedron_01_4.html", null ],
        [ "NedelecT1_LDisc< TDomain, Triangle >", "classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc_3_01_t_domain_00_01_triangle_01_4.html", null ],
        [ "NedelecT1_LDisc_forSimplex", "classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc__for_simplex.html", "classug_1_1_electromagnetism_1_1_nedelec_t1___l_disc__for_simplex" ],
        [ "NedelecTransfer", "classug_1_1_electromagnetism_1_1_nedelec_transfer.html", "classug_1_1_electromagnetism_1_1_nedelec_transfer" ],
        [ "TimeHarmonicNedelecHybridSmoother", "classug_1_1_electromagnetism_1_1_time_harmonic_nedelec_hybrid_smoother.html", "classug_1_1_electromagnetism_1_1_time_harmonic_nedelec_hybrid_smoother" ]
      ] ],
      [ "JSONToolkit", "namespaceug_1_1_j_s_o_n_toolkit.html", [
        [ "custom_error_handler", "classug_1_1_j_s_o_n_toolkit_1_1custom__error__handler.html", "classug_1_1_j_s_o_n_toolkit_1_1custom__error__handler" ],
        [ "Functionality", "structug_1_1_j_s_o_n_toolkit_1_1_functionality.html", "structug_1_1_j_s_o_n_toolkit_1_1_functionality" ],
        [ "JSONSchemaValidator", "structug_1_1_j_s_o_n_toolkit_1_1_j_s_o_n_schema_validator.html", "structug_1_1_j_s_o_n_toolkit_1_1_j_s_o_n_schema_validator" ],
        [ "JSONTool", "structug_1_1_j_s_o_n_toolkit_1_1_j_s_o_n_tool.html", "structug_1_1_j_s_o_n_toolkit_1_1_j_s_o_n_tool" ],
        [ "ParameterSet", "classug_1_1_j_s_o_n_toolkit_1_1_parameter_set.html", "classug_1_1_j_s_o_n_toolkit_1_1_parameter_set" ],
        [ "ParameterValue", "structug_1_1_j_s_o_n_toolkit_1_1_parameter_value.html", "structug_1_1_j_s_o_n_toolkit_1_1_parameter_value" ]
      ] ],
      [ "Jupyter", "namespaceug_1_1_jupyter.html", [
        [ "Functionality", "structug_1_1_jupyter_1_1_functionality.html", "structug_1_1_jupyter_1_1_functionality" ],
        [ "XWidgetRegistryFacade", "structug_1_1_jupyter_1_1_x_widget_registry_facade.html", "structug_1_1_jupyter_1_1_x_widget_registry_facade" ]
      ] ],
      [ "LevelSet", "namespaceug_1_1_level_set.html", [
        [ "CRTwoPhaseSource", "classug_1_1_level_set_1_1_c_r_two_phase_source.html", "classug_1_1_level_set_1_1_c_r_two_phase_source" ],
        [ "DimScaledLSFGrad", "classug_1_1_level_set_1_1_dim_scaled_l_s_f_grad.html", "classug_1_1_level_set_1_1_dim_scaled_l_s_f_grad" ],
        [ "DimScaledLSFGrad< WDim, 0 >", "classug_1_1_level_set_1_1_dim_scaled_l_s_f_grad_3_01_w_dim_00_010_01_4.html", "classug_1_1_level_set_1_1_dim_scaled_l_s_f_grad_3_01_w_dim_00_010_01_4" ],
        [ "EikonalVel", "classug_1_1_level_set_1_1_eikonal_vel.html", "classug_1_1_level_set_1_1_eikonal_vel" ],
        [ "Functionality", "structug_1_1_level_set_1_1_functionality.html", "structug_1_1_level_set_1_1_functionality" ],
        [ "FV1_Convection", "classug_1_1_level_set_1_1_f_v1___convection.html", "classug_1_1_level_set_1_1_f_v1___convection" ],
        [ "FV1LevelSetDisc", "classug_1_1_level_set_1_1_f_v1_level_set_disc.html", "classug_1_1_level_set_1_1_f_v1_level_set_disc" ],
        [ "FVLSIntegral", "classug_1_1_level_set_1_1_f_v_l_s_integral.html", "classug_1_1_level_set_1_1_f_v_l_s_integral" ],
        [ "GridFuncLSGradientData", "classug_1_1_level_set_1_1_grid_func_l_s_gradient_data.html", "classug_1_1_level_set_1_1_grid_func_l_s_gradient_data" ],
        [ "GridFuncLSNumberData", "classug_1_1_level_set_1_1_grid_func_l_s_number_data.html", "classug_1_1_level_set_1_1_grid_func_l_s_number_data" ],
        [ "HiResFluxBasedLSM", "classug_1_1_level_set_1_1_hi_res_flux_based_l_s_m.html", "classug_1_1_level_set_1_1_hi_res_flux_based_l_s_m" ],
        [ "LevelSetAnalytic", "classug_1_1_level_set_1_1_level_set_analytic.html", "classug_1_1_level_set_1_1_level_set_analytic" ],
        [ "LevelSetCurvature", "classug_1_1_level_set_1_1_level_set_curvature.html", "classug_1_1_level_set_1_1_level_set_curvature" ],
        [ "LevelSetUserData", "classug_1_1_level_set_1_1_level_set_user_data.html", "classug_1_1_level_set_1_1_level_set_user_data" ],
        [ "LevelSetUserDataBase", "classug_1_1_level_set_1_1_level_set_user_data_base.html", "classug_1_1_level_set_1_1_level_set_user_data_base" ],
        [ "LevelSetUserVectorData", "classug_1_1_level_set_1_1_level_set_user_vector_data.html", "classug_1_1_level_set_1_1_level_set_user_vector_data" ],
        [ "LevSetGFlinearExtrapolation", "classug_1_1_level_set_1_1_lev_set_g_flinear_extrapolation.html", "classug_1_1_level_set_1_1_lev_set_g_flinear_extrapolation" ],
        [ "LevSetGFsimpleExtrapolation", "classug_1_1_level_set_1_1_lev_set_g_fsimple_extrapolation.html", "classug_1_1_level_set_1_1_lev_set_g_fsimple_extrapolation" ],
        [ "LSAveData", "classug_1_1_level_set_1_1_l_s_ave_data.html", "classug_1_1_level_set_1_1_l_s_ave_data" ],
        [ "LSBearScheidegger", "classug_1_1_level_set_1_1_l_s_bear_scheidegger.html", "classug_1_1_level_set_1_1_l_s_bear_scheidegger" ],
        [ "LSBearScheidegger2", "classug_1_1_level_set_1_1_l_s_bear_scheidegger2.html", "classug_1_1_level_set_1_1_l_s_bear_scheidegger2" ],
        [ "LSDarcyVelocityLinker", "classug_1_1_level_set_1_1_l_s_darcy_velocity_linker.html", "classug_1_1_level_set_1_1_l_s_darcy_velocity_linker" ],
        [ "LSElementSize", "classug_1_1_level_set_1_1_l_s_element_size.html", "classug_1_1_level_set_1_1_l_s_element_size" ],
        [ "LSElementSize< ReferenceEdge, WDim >", "classug_1_1_level_set_1_1_l_s_element_size_3_01_reference_edge_00_01_w_dim_01_4.html", "classug_1_1_level_set_1_1_l_s_element_size_3_01_reference_edge_00_01_w_dim_01_4" ],
        [ "LSElementSize< ReferencePrism, WDim >", "classug_1_1_level_set_1_1_l_s_element_size_3_01_reference_prism_00_01_w_dim_01_4.html", "classug_1_1_level_set_1_1_l_s_element_size_3_01_reference_prism_00_01_w_dim_01_4" ],
        [ "LSElementSize< ReferenceTetrahedron, WDim >", "classug_1_1_level_set_1_1_l_s_element_size_3_01_reference_tetrahedron_00_01_w_dim_01_4.html", "classug_1_1_level_set_1_1_l_s_element_size_3_01_reference_tetrahedron_00_01_w_dim_01_4" ],
        [ "LSElementSize< ReferenceTriangle, WDim >", "classug_1_1_level_set_1_1_l_s_element_size_3_01_reference_triangle_00_01_w_dim_01_4.html", "classug_1_1_level_set_1_1_l_s_element_size_3_01_reference_triangle_00_01_w_dim_01_4" ],
        [ "LSFbyRaster", "classug_1_1_level_set_1_1_l_s_fby_raster.html", "classug_1_1_level_set_1_1_l_s_fby_raster" ],
        [ "LSFilterLinker", "classug_1_1_level_set_1_1_l_s_filter_linker.html", "classug_1_1_level_set_1_1_l_s_filter_linker" ],
        [ "LSFilterLinker2", "classug_1_1_level_set_1_1_l_s_filter_linker2.html", "classug_1_1_level_set_1_1_l_s_filter_linker2" ],
        [ "LSGFlinearDomainDiscretization", "classug_1_1_level_set_1_1_l_s_g_flinear_domain_discretization.html", "classug_1_1_level_set_1_1_l_s_g_flinear_domain_discretization" ],
        [ "LSGFsimpleDomainDiscretization", "classug_1_1_level_set_1_1_l_s_g_fsimple_domain_discretization.html", "classug_1_1_level_set_1_1_l_s_g_fsimple_domain_discretization" ],
        [ "LSHeavisideIntegral", "classug_1_1_level_set_1_1_l_s_heaviside_integral.html", "classug_1_1_level_set_1_1_l_s_heaviside_integral" ],
        [ "LSIntegral", "classug_1_1_level_set_1_1_l_s_integral.html", "classug_1_1_level_set_1_1_l_s_integral" ],
        [ "LSVolume", "classug_1_1_level_set_1_1_l_s_volume.html", "classug_1_1_level_set_1_1_l_s_volume" ],
        [ "ScaledLSFGrad", "classug_1_1_level_set_1_1_scaled_l_s_f_grad.html", "classug_1_1_level_set_1_1_scaled_l_s_f_grad" ],
        [ "ScaledLSFGrad< WDim, RegularVertex >", "classug_1_1_level_set_1_1_scaled_l_s_f_grad_3_01_w_dim_00_01_regular_vertex_01_4.html", "classug_1_1_level_set_1_1_scaled_l_s_f_grad_3_01_w_dim_00_01_regular_vertex_01_4" ],
        [ "VelByNormalVel", "classug_1_1_level_set_1_1_vel_by_normal_vel.html", "classug_1_1_level_set_1_1_vel_by_normal_vel" ]
      ] ],
      [ "Limex", "namespaceug_1_1_limex.html", [
        [ "Functionality", "structug_1_1_limex_1_1_functionality.html", "structug_1_1_limex_1_1_functionality" ]
      ] ],
      [ "luashell", "namespaceug_1_1luashell.html", [
        [ "LuaShell", "classug_1_1luashell_1_1_lua_shell.html", "classug_1_1luashell_1_1_lua_shell" ]
      ] ],
      [ "NavierStokes", "namespaceug_1_1_navier_stokes.html", [
        [ "CompressibleNavierStokesBase", "classug_1_1_navier_stokes_1_1_compressible_navier_stokes_base.html", "classug_1_1_navier_stokes_1_1_compressible_navier_stokes_base" ],
        [ "CompressibleNavierStokesFV1", "classug_1_1_navier_stokes_1_1_compressible_navier_stokes_f_v1.html", "classug_1_1_navier_stokes_1_1_compressible_navier_stokes_f_v1" ],
        [ "ConstantBoxFilter", "classug_1_1_navier_stokes_1_1_constant_box_filter.html", "classug_1_1_navier_stokes_1_1_constant_box_filter" ],
        [ "CRDynamicTurbViscData", "classug_1_1_navier_stokes_1_1_c_r_dynamic_turb_visc_data.html", "classug_1_1_navier_stokes_1_1_c_r_dynamic_turb_visc_data" ],
        [ "CRNavierStokesSymBC", "classug_1_1_navier_stokes_1_1_c_r_navier_stokes_sym_b_c.html", "classug_1_1_navier_stokes_1_1_c_r_navier_stokes_sym_b_c" ],
        [ "CRSmagorinskyTurbViscData", "classug_1_1_navier_stokes_1_1_c_r_smagorinsky_turb_visc_data.html", "classug_1_1_navier_stokes_1_1_c_r_smagorinsky_turb_visc_data" ],
        [ "ElementBoxFilter", "classug_1_1_navier_stokes_1_1_element_box_filter.html", "classug_1_1_navier_stokes_1_1_element_box_filter" ],
        [ "FilterBaseClass", "classug_1_1_navier_stokes_1_1_filter_base_class.html", "classug_1_1_navier_stokes_1_1_filter_base_class" ],
        [ "FilterImplBaseClass", "classug_1_1_navier_stokes_1_1_filter_impl_base_class.html", "classug_1_1_navier_stokes_1_1_filter_impl_base_class" ],
        [ "Functionality", "structug_1_1_navier_stokes_1_1_functionality.html", "structug_1_1_navier_stokes_1_1_functionality" ],
        [ "FunctionalityComp", "structug_1_1_navier_stokes_1_1_functionality_comp.html", "structug_1_1_navier_stokes_1_1_functionality_comp" ],
        [ "FunctionalityCompFV1", "structug_1_1_navier_stokes_1_1_functionality_comp_f_v1.html", "structug_1_1_navier_stokes_1_1_functionality_comp_f_v1" ],
        [ "FunctionalityFE", "structug_1_1_navier_stokes_1_1_functionality_f_e.html", "structug_1_1_navier_stokes_1_1_functionality_f_e" ],
        [ "FunctionalityFV", "structug_1_1_navier_stokes_1_1_functionality_f_v.html", "structug_1_1_navier_stokes_1_1_functionality_f_v" ],
        [ "FunctionalityFV1", "structug_1_1_navier_stokes_1_1_functionality_f_v1.html", "structug_1_1_navier_stokes_1_1_functionality_f_v1" ],
        [ "FunctionalityFVCR", "structug_1_1_navier_stokes_1_1_functionality_f_v_c_r.html", "structug_1_1_navier_stokes_1_1_functionality_f_v_c_r" ],
        [ "FunctionalityIncomp", "structug_1_1_navier_stokes_1_1_functionality_incomp.html", "structug_1_1_navier_stokes_1_1_functionality_incomp" ],
        [ "FV1BoxFilter", "classug_1_1_navier_stokes_1_1_f_v1_box_filter.html", "classug_1_1_navier_stokes_1_1_f_v1_box_filter" ],
        [ "FV1DynamicTurbViscData", "classug_1_1_navier_stokes_1_1_f_v1_dynamic_turb_visc_data.html", "classug_1_1_navier_stokes_1_1_f_v1_dynamic_turb_visc_data" ],
        [ "FV1SmagorinskyTurbViscData", "classug_1_1_navier_stokes_1_1_f_v1_smagorinsky_turb_visc_data.html", "classug_1_1_navier_stokes_1_1_f_v1_smagorinsky_turb_visc_data" ],
        [ "FVCRBoxFilter", "classug_1_1_navier_stokes_1_1_f_v_c_r_box_filter.html", "classug_1_1_navier_stokes_1_1_f_v_c_r_box_filter" ],
        [ "INavierStokesFV1Stabilization", "classug_1_1_navier_stokes_1_1_i_navier_stokes_f_v1_stabilization.html", "classug_1_1_navier_stokes_1_1_i_navier_stokes_f_v1_stabilization" ],
        [ "INavierStokesSRFV1Stabilization", "classug_1_1_navier_stokes_1_1_i_navier_stokes_s_r_f_v1_stabilization.html", "classug_1_1_navier_stokes_1_1_i_navier_stokes_s_r_f_v1_stabilization" ],
        [ "INavierStokesUpwind", "classug_1_1_navier_stokes_1_1_i_navier_stokes_upwind.html", "classug_1_1_navier_stokes_1_1_i_navier_stokes_upwind" ],
        [ "IncompressibleNavierStokesBase", "classug_1_1_navier_stokes_1_1_incompressible_navier_stokes_base.html", "classug_1_1_navier_stokes_1_1_incompressible_navier_stokes_base" ],
        [ "NavierStokesBase", "classug_1_1_navier_stokes_1_1_navier_stokes_base.html", "classug_1_1_navier_stokes_1_1_navier_stokes_base" ],
        [ "NavierStokesFE", "classug_1_1_navier_stokes_1_1_navier_stokes_f_e.html", "classug_1_1_navier_stokes_1_1_navier_stokes_f_e" ],
        [ "NavierStokesFIELDSStabilization", "classug_1_1_navier_stokes_1_1_navier_stokes_f_i_e_l_d_s_stabilization.html", "classug_1_1_navier_stokes_1_1_navier_stokes_f_i_e_l_d_s_stabilization" ],
        [ "NavierStokesFLOWStabilization", "classug_1_1_navier_stokes_1_1_navier_stokes_f_l_o_w_stabilization.html", "classug_1_1_navier_stokes_1_1_navier_stokes_f_l_o_w_stabilization" ],
        [ "NavierStokesFullUpwind", "classug_1_1_navier_stokes_1_1_navier_stokes_full_upwind.html", "classug_1_1_navier_stokes_1_1_navier_stokes_full_upwind" ],
        [ "NavierStokesFV", "classug_1_1_navier_stokes_1_1_navier_stokes_f_v.html", "classug_1_1_navier_stokes_1_1_navier_stokes_f_v" ],
        [ "NavierStokesFV1", "classug_1_1_navier_stokes_1_1_navier_stokes_f_v1.html", "classug_1_1_navier_stokes_1_1_navier_stokes_f_v1" ],
        [ "NavierStokesFV1WithoutStabilization", "classug_1_1_navier_stokes_1_1_navier_stokes_f_v1_without_stabilization.html", "classug_1_1_navier_stokes_1_1_navier_stokes_f_v1_without_stabilization" ],
        [ "NavierStokesFVCR", "classug_1_1_navier_stokes_1_1_navier_stokes_f_v_c_r.html", "classug_1_1_navier_stokes_1_1_navier_stokes_f_v_c_r" ],
        [ "NavierStokesInflowBase", "classug_1_1_navier_stokes_1_1_navier_stokes_inflow_base.html", "classug_1_1_navier_stokes_1_1_navier_stokes_inflow_base" ],
        [ "NavierStokesInflowFE", "classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_e.html", "classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_e" ],
        [ "NavierStokesInflowFV", "classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_v.html", "classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_v" ],
        [ "NavierStokesInflowFV1", "classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_v1.html", "classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_v1" ],
        [ "NavierStokesInflowFVCR", "classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_v_c_r.html", "classug_1_1_navier_stokes_1_1_navier_stokes_inflow_f_v_c_r" ],
        [ "NavierStokesLinearProfileSkewedUpwind", "classug_1_1_navier_stokes_1_1_navier_stokes_linear_profile_skewed_upwind.html", "classug_1_1_navier_stokes_1_1_navier_stokes_linear_profile_skewed_upwind" ],
        [ "NavierStokesNoNormalStressOutflowBase", "classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_base.html", "classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_base" ],
        [ "NavierStokesNoNormalStressOutflowFV", "classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_f_v.html", "classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_f_v" ],
        [ "NavierStokesNoNormalStressOutflowFV1", "classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_f_v1.html", "classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_f_v1" ],
        [ "NavierStokesNoNormalStressOutflowFVCR", "classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_f_v_c_r.html", "classug_1_1_navier_stokes_1_1_navier_stokes_no_normal_stress_outflow_f_v_c_r" ],
        [ "NavierStokesNoUpwind", "classug_1_1_navier_stokes_1_1_navier_stokes_no_upwind.html", "classug_1_1_navier_stokes_1_1_navier_stokes_no_upwind" ],
        [ "NavierStokesPositiveUpwind", "classug_1_1_navier_stokes_1_1_navier_stokes_positive_upwind.html", "classug_1_1_navier_stokes_1_1_navier_stokes_positive_upwind" ],
        [ "NavierStokesRegularUpwind", "classug_1_1_navier_stokes_1_1_navier_stokes_regular_upwind.html", "classug_1_1_navier_stokes_1_1_navier_stokes_regular_upwind" ],
        [ "NavierStokesSkewedUpwind", "classug_1_1_navier_stokes_1_1_navier_stokes_skewed_upwind.html", "classug_1_1_navier_stokes_1_1_navier_stokes_skewed_upwind" ],
        [ "NavierStokesSymBCFV1", "classug_1_1_navier_stokes_1_1_navier_stokes_sym_b_c_f_v1.html", "classug_1_1_navier_stokes_1_1_navier_stokes_sym_b_c_f_v1" ],
        [ "NavierStokesUpwindRegister", "classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register.html", "classug_1_1_navier_stokes_1_1_navier_stokes_upwind_register" ],
        [ "NavierStokesWall", "classug_1_1_navier_stokes_1_1_navier_stokes_wall.html", "classug_1_1_navier_stokes_1_1_navier_stokes_wall" ],
        [ "NavierStokesWSBCFV1", "classug_1_1_navier_stokes_1_1_navier_stokes_w_s_b_c_f_v1.html", "classug_1_1_navier_stokes_1_1_navier_stokes_w_s_b_c_f_v1" ],
        [ "Region", "structug_1_1_navier_stokes_1_1_region.html", "structug_1_1_navier_stokes_1_1_region" ],
        [ "SeparatedPressureSource", "classug_1_1_navier_stokes_1_1_separated_pressure_source.html", "classug_1_1_navier_stokes_1_1_separated_pressure_source" ],
        [ "SeparatedPressureSourceInter", "classug_1_1_navier_stokes_1_1_separated_pressure_source_inter.html", "classug_1_1_navier_stokes_1_1_separated_pressure_source_inter" ],
        [ "StdTurbulentViscosityData", "classug_1_1_navier_stokes_1_1_std_turbulent_viscosity_data.html", "classug_1_1_navier_stokes_1_1_std_turbulent_viscosity_data" ],
        [ "StdTurbulentViscosityDataFV1", "classug_1_1_navier_stokes_1_1_std_turbulent_viscosity_data_f_v1.html", "classug_1_1_navier_stokes_1_1_std_turbulent_viscosity_data_f_v1" ],
        [ "VariableBoxFilter", "classug_1_1_navier_stokes_1_1_variable_box_filter.html", "classug_1_1_navier_stokes_1_1_variable_box_filter" ],
        [ "WallObject", "classug_1_1_navier_stokes_1_1_wall_object.html", "classug_1_1_navier_stokes_1_1_wall_object" ]
      ] ],
      [ "Poroelasticity", "namespaceug_1_1_poroelasticity.html", [
        [ "BarryMercerData", "structug_1_1_poroelasticity_1_1_barry_mercer_data.html", "structug_1_1_poroelasticity_1_1_barry_mercer_data" ],
        [ "BarryMercerErrorData", "classug_1_1_poroelasticity_1_1_barry_mercer_error_data.html", "classug_1_1_poroelasticity_1_1_barry_mercer_error_data" ],
        [ "BarryMercerNondimensional", "classug_1_1_poroelasticity_1_1_barry_mercer_nondimensional.html", "classug_1_1_poroelasticity_1_1_barry_mercer_nondimensional" ],
        [ "BarryMercerPointSource", "classug_1_1_poroelasticity_1_1_barry_mercer_point_source.html", "classug_1_1_poroelasticity_1_1_barry_mercer_point_source" ],
        [ "BarryMercerProblem", "classug_1_1_poroelasticity_1_1_barry_mercer_problem.html", "classug_1_1_poroelasticity_1_1_barry_mercer_problem" ],
        [ "BarryMercerRefDispX", "classug_1_1_poroelasticity_1_1_barry_mercer_ref_disp_x.html", "classug_1_1_poroelasticity_1_1_barry_mercer_ref_disp_x" ],
        [ "BarryMercerRefDispY", "classug_1_1_poroelasticity_1_1_barry_mercer_ref_disp_y.html", "classug_1_1_poroelasticity_1_1_barry_mercer_ref_disp_y" ],
        [ "BarryMercerRefPressure", "classug_1_1_poroelasticity_1_1_barry_mercer_ref_pressure.html", "classug_1_1_poroelasticity_1_1_barry_mercer_ref_pressure" ],
        [ "BiotDiscConfig", "structug_1_1_poroelasticity_1_1_biot_disc_config.html", "structug_1_1_poroelasticity_1_1_biot_disc_config" ],
        [ "BiotElemDisc", "classug_1_1_poroelasticity_1_1_biot_elem_disc.html", "classug_1_1_poroelasticity_1_1_biot_elem_disc" ],
        [ "BiotElemDiscFactory", "classug_1_1_poroelasticity_1_1_biot_elem_disc_factory.html", "classug_1_1_poroelasticity_1_1_biot_elem_disc_factory" ],
        [ "BiotProblem", "classug_1_1_poroelasticity_1_1_biot_problem.html", "classug_1_1_poroelasticity_1_1_biot_problem" ],
        [ "BiotProjection", "classug_1_1_poroelasticity_1_1_biot_projection.html", "classug_1_1_poroelasticity_1_1_biot_projection" ],
        [ "BiotSubsetParameters", "classug_1_1_poroelasticity_1_1_biot_subset_parameters.html", "classug_1_1_poroelasticity_1_1_biot_subset_parameters" ],
        [ "Functionality", "structug_1_1_poroelasticity_1_1_functionality.html", "structug_1_1_poroelasticity_1_1_functionality" ],
        [ "FunctionalityFor2D", "structug_1_1_poroelasticity_1_1_functionality_for2_d.html", "structug_1_1_poroelasticity_1_1_functionality_for2_d" ]
      ] ],
      [ "promesh", "namespaceug_1_1promesh.html", [
        [ "detail", "namespaceug_1_1promesh_1_1detail.html", [
          [ "ProMeshFunction", "classug_1_1promesh_1_1detail_1_1_pro_mesh_function.html", "classug_1_1promesh_1_1detail_1_1_pro_mesh_function" ]
        ] ],
        [ "AnisoElemInfo", "classug_1_1promesh_1_1_aniso_elem_info.html", "classug_1_1promesh_1_1_aniso_elem_info" ],
        [ "Box", "classug_1_1promesh_1_1_box.html", "classug_1_1promesh_1_1_box" ],
        [ "ElementIterator", "classug_1_1promesh_1_1_element_iterator.html", "classug_1_1promesh_1_1_element_iterator" ],
        [ "Mesh", "classug_1_1promesh_1_1_mesh.html", "classug_1_1promesh_1_1_mesh" ],
        [ "MeshObject", "classug_1_1promesh_1_1_mesh_object.html", "classug_1_1promesh_1_1_mesh_object" ],
        [ "ProMeshRegistry", "classug_1_1promesh_1_1_pro_mesh_registry.html", "classug_1_1promesh_1_1_pro_mesh_registry" ]
      ] ],
      [ "Richards", "namespaceug_1_1_richards.html", [
        [ "BrooksCoreyFunctions", "structug_1_1_richards_1_1_brooks_corey_functions.html", "structug_1_1_richards_1_1_brooks_corey_functions" ],
        [ "ConductivityAdapter", "structug_1_1_richards_1_1_conductivity_adapter.html", "structug_1_1_richards_1_1_conductivity_adapter" ],
        [ "ExponentialConductivity", "structug_1_1_richards_1_1_exponential_conductivity.html", "structug_1_1_richards_1_1_exponential_conductivity" ],
        [ "ExponentialModel", "classug_1_1_richards_1_1_exponential_model.html", "classug_1_1_richards_1_1_exponential_model" ],
        [ "ExponentialModelParameters", "structug_1_1_richards_1_1_exponential_model_parameters.html", "structug_1_1_richards_1_1_exponential_model_parameters" ],
        [ "ExponentialSaturation", "structug_1_1_richards_1_1_exponential_saturation.html", "structug_1_1_richards_1_1_exponential_saturation" ],
        [ "Functionality", "structug_1_1_richards_1_1_functionality.html", "structug_1_1_richards_1_1_functionality" ],
        [ "GardnerConductivity", "classug_1_1_richards_1_1_gardner_conductivity.html", "classug_1_1_richards_1_1_gardner_conductivity" ],
        [ "GardnerModel", "classug_1_1_richards_1_1_gardner_model.html", "classug_1_1_richards_1_1_gardner_model" ],
        [ "GardnerSaturation", "classug_1_1_richards_1_1_gardner_saturation.html", "classug_1_1_richards_1_1_gardner_saturation" ],
        [ "HaverkampConductivity", "classug_1_1_richards_1_1_haverkamp_conductivity.html", "classug_1_1_richards_1_1_haverkamp_conductivity" ],
        [ "HaverkampModel", "classug_1_1_richards_1_1_haverkamp_model.html", "classug_1_1_richards_1_1_haverkamp_model" ],
        [ "HaverkampParameters", "structug_1_1_richards_1_1_haverkamp_parameters.html", "structug_1_1_richards_1_1_haverkamp_parameters" ],
        [ "HaverkampSaturation", "classug_1_1_richards_1_1_haverkamp_saturation.html", "classug_1_1_richards_1_1_haverkamp_saturation" ],
        [ "IParameterizedModel", "structug_1_1_richards_1_1_i_parameterized_model.html", "structug_1_1_richards_1_1_i_parameterized_model" ],
        [ "IRichardsLinker", "structug_1_1_richards_1_1_i_richards_linker.html", "structug_1_1_richards_1_1_i_richards_linker" ],
        [ "IRichardsModel", "classug_1_1_richards_1_1_i_richards_model.html", "classug_1_1_richards_1_1_i_richards_model" ],
        [ "OnSurfaceCondition", "classug_1_1_richards_1_1_on_surface_condition.html", "classug_1_1_richards_1_1_on_surface_condition" ],
        [ "RichardsConductivity", "structug_1_1_richards_1_1_richards_conductivity.html", "structug_1_1_richards_1_1_richards_conductivity" ],
        [ "RichardsElemDisc", "classug_1_1_richards_1_1_richards_elem_disc.html", "classug_1_1_richards_1_1_richards_elem_disc" ],
        [ "RichardsElemDiscFactory", "classug_1_1_richards_1_1_richards_elem_disc_factory.html", "classug_1_1_richards_1_1_richards_elem_disc_factory" ],
        [ "RichardsLinker", "classug_1_1_richards_1_1_richards_linker.html", "classug_1_1_richards_1_1_richards_linker" ],
        [ "RichardsSaturation", "structug_1_1_richards_1_1_richards_saturation.html", "structug_1_1_richards_1_1_richards_saturation" ],
        [ "SaturationAdapter", "structug_1_1_richards_1_1_saturation_adapter.html", "structug_1_1_richards_1_1_saturation_adapter" ],
        [ "UserDataFactory", "classug_1_1_richards_1_1_user_data_factory.html", "classug_1_1_richards_1_1_user_data_factory" ],
        [ "VanGenuchtenFunctions", "structug_1_1_richards_1_1_van_genuchten_functions.html", "structug_1_1_richards_1_1_van_genuchten_functions" ],
        [ "VanGenuchtenModel", "classug_1_1_richards_1_1_van_genuchten_model.html", "classug_1_1_richards_1_1_van_genuchten_model" ],
        [ "VanGenuchtenParameters", "structug_1_1_richards_1_1_van_genuchten_parameters.html", "structug_1_1_richards_1_1_van_genuchten_parameters" ]
      ] ],
      [ "SmallStrainMechanics", "namespaceug_1_1_small_strain_mechanics.html", [
        [ "ContactSmallStrainMechanics", "classug_1_1_small_strain_mechanics_1_1_contact_small_strain_mechanics.html", "classug_1_1_small_strain_mechanics_1_1_contact_small_strain_mechanics" ],
        [ "contrained_dim_traits", "structug_1_1_small_strain_mechanics_1_1contrained__dim__traits.html", null ],
        [ "contrained_dim_traits< 2 >", "structug_1_1_small_strain_mechanics_1_1contrained__dim__traits_3_012_01_4.html", "structug_1_1_small_strain_mechanics_1_1contrained__dim__traits_3_012_01_4" ],
        [ "contrained_dim_traits< 3 >", "structug_1_1_small_strain_mechanics_1_1contrained__dim__traits_3_013_01_4.html", "structug_1_1_small_strain_mechanics_1_1contrained__dim__traits_3_013_01_4" ],
        [ "DamageFunctionUpdater", "classug_1_1_small_strain_mechanics_1_1_damage_function_updater.html", "classug_1_1_small_strain_mechanics_1_1_damage_function_updater" ],
        [ "DamageLaw", "classug_1_1_small_strain_mechanics_1_1_damage_law.html", "classug_1_1_small_strain_mechanics_1_1_damage_law" ],
        [ "face_type_traits", "structug_1_1_small_strain_mechanics_1_1face__type__traits.html", "structug_1_1_small_strain_mechanics_1_1face__type__traits" ],
        [ "face_type_traits< 1 >", "structug_1_1_small_strain_mechanics_1_1face__type__traits_3_011_01_4.html", "structug_1_1_small_strain_mechanics_1_1face__type__traits_3_011_01_4" ],
        [ "face_type_traits< 2 >", "structug_1_1_small_strain_mechanics_1_1face__type__traits_3_012_01_4.html", "structug_1_1_small_strain_mechanics_1_1face__type__traits_3_012_01_4" ],
        [ "face_type_traits< 3 >", "structug_1_1_small_strain_mechanics_1_1face__type__traits_3_013_01_4.html", "structug_1_1_small_strain_mechanics_1_1face__type__traits_3_013_01_4" ],
        [ "Functionality", "structug_1_1_small_strain_mechanics_1_1_functionality.html", "structug_1_1_small_strain_mechanics_1_1_functionality" ],
        [ "HookeLaw", "classug_1_1_small_strain_mechanics_1_1_hooke_law.html", "classug_1_1_small_strain_mechanics_1_1_hooke_law" ],
        [ "IMaterialLaw", "classug_1_1_small_strain_mechanics_1_1_i_material_law.html", "classug_1_1_small_strain_mechanics_1_1_i_material_law" ],
        [ "IScaledHookeLaw", "classug_1_1_small_strain_mechanics_1_1_i_scaled_hooke_law.html", "classug_1_1_small_strain_mechanics_1_1_i_scaled_hooke_law" ],
        [ "MechOutputWriter", "classug_1_1_small_strain_mechanics_1_1_mech_output_writer.html", "classug_1_1_small_strain_mechanics_1_1_mech_output_writer" ],
        [ "PrandtlReuss", "classug_1_1_small_strain_mechanics_1_1_prandtl_reuss.html", "classug_1_1_small_strain_mechanics_1_1_prandtl_reuss" ],
        [ "RelativeDensityUpdater", "classug_1_1_small_strain_mechanics_1_1_relative_density_updater.html", "classug_1_1_small_strain_mechanics_1_1_relative_density_updater" ],
        [ "SkinMaterialLaw", "classug_1_1_small_strain_mechanics_1_1_skin_material_law.html", "classug_1_1_small_strain_mechanics_1_1_skin_material_law" ],
        [ "SmallStrainMechanicsElemDisc", "classug_1_1_small_strain_mechanics_1_1_small_strain_mechanics_elem_disc.html", "classug_1_1_small_strain_mechanics_1_1_small_strain_mechanics_elem_disc" ],
        [ "TopologyOptimLaw", "classug_1_1_small_strain_mechanics_1_1_topology_optim_law.html", "classug_1_1_small_strain_mechanics_1_1_topology_optim_law" ],
        [ "VoigtianMatrix", "classug_1_1_small_strain_mechanics_1_1_voigtian_matrix.html", "classug_1_1_small_strain_mechanics_1_1_voigtian_matrix" ]
      ] ],
      [ "smile", "namespaceug_1_1smile.html", [
        [ "Cloud", "classug_1_1smile_1_1_cloud.html", "classug_1_1smile_1_1_cloud" ],
        [ "Functionality", "structug_1_1smile_1_1_functionality.html", "structug_1_1smile_1_1_functionality" ],
        [ "SmartKd", "classug_1_1smile_1_1_smart_kd.html", "classug_1_1smile_1_1_smart_kd" ],
        [ "SmartRescaler", "classug_1_1smile_1_1_smart_rescaler.html", "classug_1_1smile_1_1_smart_rescaler" ],
        [ "t_gamma", "structug_1_1smile_1_1t__gamma.html", "structug_1_1smile_1_1t__gamma" ]
      ] ],
      [ "TemplatePlugin", "namespaceug_1_1_template_plugin.html", [
        [ "Functionality", "structug_1_1_template_plugin_1_1_functionality.html", "structug_1_1_template_plugin_1_1_functionality" ],
        [ "TemplateSampleClass", "classug_1_1_template_plugin_1_1_template_sample_class.html", "classug_1_1_template_plugin_1_1_template_sample_class" ]
      ] ],
      [ "Util", "namespaceug_1_1_util.html", [
        [ "Functionality", "structug_1_1_util_1_1_functionality.html", "structug_1_1_util_1_1_functionality" ]
      ] ],
      [ "AitkenNevilleTimex", "classug_1_1_aitken_neville_timex.html", "classug_1_1_aitken_neville_timex" ],
      [ "BearScheidegger", "classug_1_1_bear_scheidegger.html", "classug_1_1_bear_scheidegger" ],
      [ "CompareDeg", "structug_1_1_compare_deg.html", "structug_1_1_compare_deg" ],
      [ "CompositeGridFunctionEstimator", "classug_1_1_composite_grid_function_estimator.html", "classug_1_1_composite_grid_function_estimator" ],
      [ "ConnectionViewerOutputObserver", "classug_1_1_connection_viewer_output_observer.html", "classug_1_1_connection_viewer_output_observer" ],
      [ "ConstStepLinearTimeIntegrator", "classug_1_1_const_step_linear_time_integrator.html", "classug_1_1_const_step_linear_time_integrator" ],
      [ "CRILUTPreconditioner", "classug_1_1_c_r_i_l_u_t_preconditioner.html", "classug_1_1_c_r_i_l_u_t_preconditioner" ],
      [ "DeltaSquareIntegrand", "classug_1_1_delta_square_integrand.html", "classug_1_1_delta_square_integrand" ],
      [ "DFAnisotropy", "classug_1_1_d_f_anisotropy.html", "classug_1_1_d_f_anisotropy" ],
      [ "DFPecletNumber", "classug_1_1_d_f_peclet_number.html", "classug_1_1_d_f_peclet_number" ],
      [ "DiscConstraintFVCR", "classug_1_1_disc_constraint_f_v_c_r.html", "classug_1_1_disc_constraint_f_v_c_r" ],
      [ "DiscontinuityIntegrator", "classug_1_1_discontinuity_integrator.html", "classug_1_1_discontinuity_integrator" ],
      [ "ElementExtensions", "classug_1_1_element_extensions.html", "classug_1_1_element_extensions" ],
      [ "FSFileMeasurer", "classug_1_1_f_s_file_measurer.html", "classug_1_1_f_s_file_measurer" ],
      [ "FSFileMeasurerFinishedObserver", "classug_1_1_f_s_file_measurer_finished_observer.html", "classug_1_1_f_s_file_measurer_finished_observer" ],
      [ "FSInEquilibriumFinishedCondition", "classug_1_1_f_s_in_equilibrium_finished_condition.html", "classug_1_1_f_s_in_equilibrium_finished_condition" ],
      [ "GridFunctionEstimator", "classug_1_1_grid_function_estimator.html", "classug_1_1_grid_function_estimator" ],
      [ "ILimexCostStrategy", "classug_1_1_i_limex_cost_strategy.html", "classug_1_1_i_limex_cost_strategy" ],
      [ "ILimexRefiner", "classug_1_1_i_limex_refiner.html", "classug_1_1_i_limex_refiner" ],
      [ "ILinearTimeIntegrator", "classug_1_1_i_linear_time_integrator.html", "classug_1_1_i_linear_time_integrator" ],
      [ "INonlinearTimeIntegrator", "classug_1_1_i_nonlinear_time_integrator.html", "classug_1_1_i_nonlinear_time_integrator" ],
      [ "IntegrationOutputObserver", "classug_1_1_integration_output_observer.html", "classug_1_1_integration_output_observer" ],
      [ "ISubDiagErrorEst", "classug_1_1_i_sub_diag_error_est.html", "classug_1_1_i_sub_diag_error_est" ],
      [ "ITimeDiscDependentObject", "classug_1_1_i_time_disc_dependent_object.html", "classug_1_1_i_time_disc_dependent_object" ],
      [ "ITimeIntegrator", "classug_1_1_i_time_integrator.html", "classug_1_1_i_time_integrator" ],
      [ "LeftTransformIterator", "classug_1_1_left_transform_iterator.html", "classug_1_1_left_transform_iterator" ],
      [ "LimexDefaultCost", "classug_1_1_limex_default_cost.html", "classug_1_1_limex_default_cost" ],
      [ "LimexNewtonSolver", "classug_1_1_limex_newton_solver.html", "classug_1_1_limex_newton_solver" ],
      [ "LimexNonlinearCost", "classug_1_1_limex_nonlinear_cost.html", "classug_1_1_limex_nonlinear_cost" ],
      [ "LimexTimeIntegrator", "classug_1_1_limex_time_integrator.html", "classug_1_1_limex_time_integrator" ],
      [ "LimexTimeIntegratorConfig", "classug_1_1_limex_time_integrator_config.html", "classug_1_1_limex_time_integrator_config" ],
      [ "LinearImplicitEuler", "classug_1_1_linear_implicit_euler.html", "classug_1_1_linear_implicit_euler" ],
      [ "LinearTimeIntegrator", "classug_1_1_linear_time_integrator.html", "classug_1_1_linear_time_integrator" ],
      [ "Norm2Estimator", "classug_1_1_norm2_estimator.html", "classug_1_1_norm2_estimator" ],
      [ "NormInfEstimator", "classug_1_1_norm_inf_estimator.html", "classug_1_1_norm_inf_estimator" ],
      [ "NormRelEstimator", "classug_1_1_norm_rel_estimator.html", "classug_1_1_norm_rel_estimator" ],
      [ "PCRILUTPreconditioner", "classug_1_1_p_c_r_i_l_u_t_preconditioner.html", "classug_1_1_p_c_r_i_l_u_t_preconditioner" ],
      [ "PlotRefOutputObserver", "classug_1_1_plot_ref_output_observer.html", "classug_1_1_plot_ref_output_observer" ],
      [ "ScaledGridFunctionEstimator", "classug_1_1_scaled_grid_function_estimator.html", "classug_1_1_scaled_grid_function_estimator" ],
      [ "SimpleTimeIntegrator", "classug_1_1_simple_time_integrator.html", "classug_1_1_simple_time_integrator" ],
      [ "SubsetUserData", "classug_1_1_subset_user_data.html", "classug_1_1_subset_user_data" ],
      [ "SuperLUConfiguration", "structug_1_1_super_l_u_configuration.html", "structug_1_1_super_l_u_configuration" ],
      [ "SuperLUImplementation", "classug_1_1_super_l_u_implementation.html", "classug_1_1_super_l_u_implementation" ],
      [ "SuperLUSolver", "classug_1_1_super_l_u_solver.html", "classug_1_1_super_l_u_solver" ],
      [ "SupErrorEvaluator", "classug_1_1_sup_error_evaluator.html", "classug_1_1_sup_error_evaluator" ],
      [ "TimeIntegratorLinearAdaptive", "classug_1_1_time_integrator_linear_adaptive.html", "classug_1_1_time_integrator_linear_adaptive" ],
      [ "TimeStepBounds", "classug_1_1_time_step_bounds.html", "classug_1_1_time_step_bounds" ],
      [ "UserDataSpace", "classug_1_1_user_data_space.html", "classug_1_1_user_data_space" ],
      [ "VTKOutputObserver", "classug_1_1_v_t_k_output_observer.html", "classug_1_1_v_t_k_output_observer" ],
      [ "XInflow", "classug_1_1_x_inflow.html", "classug_1_1_x_inflow" ]
    ] ],
    [ "RichardsFixtures", "struct_richards_fixtures.html", "struct_richards_fixtures" ],
    [ "UGTestInit", "struct_u_g_test_init.html", "struct_u_g_test_init" ]
];