Plugins: ug::NavierStokes::NavierStokesWSBCFV1< TDomain > Class Template Reference
ug::NavierStokes::NavierStokesWSBCFV1< TDomain > Class Template Reference
#include <wall_sliding_fv1.h>
Public Types
typedef base_type::domain_type domain_type
Domain type.
typedef base_type::position_type position_type
Position type.
Public Types inherited from ug::IElemDisc< TDomain >
typedef IElemAssembleFuncs< IElemDisc< TDomain >, TDomain > assemble_base_type
typedef IElemError< TDomain > base_type
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Public Types inherited from ug::IElemError< class >
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from ug::IElemDiscBase< class >
typedef TDomain domain_type
typedef TDomain::position_type position_type
Public Types inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Public Member Functions
void add (const char *subsets)
adds a boundary segment
template<typename TElem , typename TFVGeom >
void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
adds the stiffness part to the local defect
template<typename TElem , typename TFVGeom >
void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFVGeom >
void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
adds the stiffness part to the local jacobian
template<typename TElem , typename TFVGeom >
void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFVGeom >
void add_rhs_elem (LocalVector &d, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFVGeom >
void fsh_elem_loop ()
finishes the element loop
NavierStokesWSBCFV1 (SmartPtr< IncompressibleNavierStokesBase< TDomain > > spMaster)
Constructor (setting default values)
template<typename TElem , typename TFVGeom >
void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
prepares the element for evaluation
template<typename TElem , typename TFVGeom >
void prep_elem_loop (const ReferenceObjectID roid, const int si)
prepares the element loop
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegularGrid)
type of trial space for each function used
virtual bool requests_local_time_series ()
returns if local time series is needed
void set_density (SmartPtr< CplUserData< number, dim > > data)
sets the density
void set_kinematic_viscosity (SmartPtr< CplUserData< number, dim > > data)
sets the kinematic viscosity
void set_sliding_factor (number val)
sets the wall sliding factor
void set_sliding_limit (number val)
sets the sliding limit
Public Member Functions inherited from ug::IElemDisc< TDomain >
void add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier)
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > & get_elem_modifier ()
IElemDisc (const char *functions, const char *subsets)
IElemDisc (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
virtual void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_fsh_elem_loop ()
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_timestep (number future_time, const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void fsh_timestep (number time, VectorProxyBase *u)
virtual void fsh_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemAssembleFuncs ()
virtual void post_assemble_loop ()
virtual void prep_assemble_loop ()
virtual void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
virtual void prep_elem_loop (const ReferenceObjectID roid, const int si)
virtual void prep_timestep (number future_time, number time, VectorProxyBase *u)
virtual void prep_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemAssembleFuncs ()
Public Member Functions inherited from ug::IElemError< class >
IElemError (const char *functions, const char *subsets)
IElemError (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from ug::IElemDiscBase< class >
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
void check_setup (bool bNonRegularGrid)
void clear_imports ()
SmartPtr< TDomain > domain ()
ConstSmartPtr< TDomain > domain () const
const FunctionGroup & function_group () const
ConstSmartPtr< FunctionPattern > function_pattern () const
IDataImport< dim > & get_import (size_t i)
IElemDiscBase (const char *functions="", const char *subsets="")
IElemDiscBase (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
bool is_time_dependent () const
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
const FunctionIndexMapping & map () const
number mass_scale () const
number mass_scale () const
number mass_scale (const size_t timePoint) const
number mass_scale (const size_t timePoint) const
const std::vector< number > & mass_scales () const
const std::vector< number > & mass_scales () const
size_t num_fct () const
size_t num_imports () const
size_t num_subsets () const
void register_import (IDataImport< dim > &Imp)
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_functions (const std::string &functions)
void set_functions (const std::vector< std::string > &functions)
void set_stationary ()
void set_stationary (bool bStationaryForced=true)
void set_subsets (const std::string &subsets)
void set_subsets (const std::vector< std::string > &subsets)
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
void set_time_independent ()
void set_time_point (const size_t timePoint)
number stiff_scale () const
number stiff_scale () const
number stiff_scale (const size_t timePoint) const
number stiff_scale (const size_t timePoint) const
const std::vector< number > & stiff_scales () const
const std::vector< number > & stiff_scales () const
TDomain::subset_handler_type & subset_handler ()
const TDomain::subset_handler_type & subset_handler () const
const std::vector< std::string > & symb_fcts () const
const std::vector< std::string > & symb_subsets () const
number time () const
size_t time_point () const
virtual int type () const
virtual bool use_hanging () const
virtual ~IElemDiscBase ()
Public Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
virtual void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_err_est_elem_loop ()
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
virtual void fsh_err_est_elem_loop ()
IElemEstimatorFuncs ()
virtual void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemEstimatorFuncs ()
Static Public Attributes
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::IElemDisc< TDomain >
static const int dim
Static Public Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Static Public Attributes inherited from ug::IElemError< class >
static const int dim
Static Public Attributes inherited from ug::IElemDiscBase< class >
static const int dim
Static Public Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Protected Member Functions
void register_all_funcs (bool bHang)
template<typename TElem , typename TFVGeom >
void register_func ()
Protected Member Functions inherited from ug::IElemDisc< TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void set_default_add_fct ()
Protected Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_add_def_A_elem_fct (ReferenceObjectID id)
void remove_add_def_A_expl_elem_fct (ReferenceObjectID id)
void remove_add_def_M_elem_fct (ReferenceObjectID id)
void remove_add_jac_A_elem_fct (ReferenceObjectID id)
void remove_add_jac_M_elem_fct (ReferenceObjectID id)
void remove_add_rhs_elem_fct (ReferenceObjectID id)
void remove_fsh_elem_loop_fct (ReferenceObjectID id)
void remove_fsh_timestep_elem_fct (ReferenceObjectID id)
void remove_fsh_timestep_fct (size_t algebra_id)
void remove_prep_elem_fct (ReferenceObjectID id)
void remove_prep_elem_loop_fct (ReferenceObjectID id)
void remove_prep_timestep_elem_fct (ReferenceObjectID id)
void remove_prep_timestep_fct (size_t algebra_id)
void set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_fct (size_t algebra_id, TAssFunc func)
void set_prep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_fct (size_t algebra_id, TAssFunc func)
Protected Member Functions inherited from ug::IElemError< class >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
Protected Member Functions inherited from ug::IElemDiscBase< class >
virtual void approximation_space_changed ()
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
void update_function_index_mapping ()
Protected Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
Private Types
typedef IElemDisc< TDomain > base_type
Base class type.
typedef NavierStokesWSBCFV1< TDomain > this_type
own type
Private Member Functions
void extract_scheduled_data ()
Private Attributes
DataImport< number, dim > m_imDensity
Data import for density.
DataImport< number, dim > m_imKinViscosity
Data import for kinematic viscosity.
DataImport< number, dim > m_imSlidingFactor
Data import for sliding factor.
DataImport< number, dim > m_imSlidingLimit
Data import for sliding limit.
DataImport< MathVector< dim >, dim > m_imSourceSCVF
Data import for source.
SmartPtr< IncompressibleNavierStokesBase< TDomain > > m_spMaster
The master discretization:
std::vector< int > m_vBndSubSetIndex
std::vector< MathVector< dim > > m_vGloIP
std::vector< MathVector< dim > > m_vLocIP
Boundary integration points of the viscosity and the density.
std::vector< std::string > m_vScheduledBndSubSets
The boundary subsets:
Static Private Attributes
static const size_t _P_ = dim
abbreviation for pressure
Additional Inherited Members
Protected Attributes inherited from ug::IElemDisc< TDomain >
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > m_spElemModifier
Protected Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
Protected Attributes inherited from ug::IElemDiscBase< class >
bool m_bStationaryForced
FunctionGroup m_fctGrp
FunctionIndexMapping m_fctIndexMap
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
ConstSmartPtr< FunctionPattern > m_spFctPattern
size_t m_timePoint
std::vector< std::string > m_vFct
std::vector< IDataImport< dim > * > m_vIImport
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
std::vector< std::string > m_vSubset
Protected Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
Member Typedef Documentation
base_type
template<typename TDomain > typedef IElemDisc<TDomain> ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::base_type private
Base class type.
domain_type
template<typename TDomain > typedef base_type::domain_type ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::domain_type
Domain type.
position_type
template<typename TDomain > typedef base_type::position_type ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::position_type
Position type.
this_type
template<typename TDomain > typedef NavierStokesWSBCFV1<TDomain> ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::this_type private
own type
Constructor & Destructor Documentation
NavierStokesWSBCFV1()
template<typename TDomain > ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::NavierStokesWSBCFV1 (SmartPtr< IncompressibleNavierStokesBase< TDomain > > spMaster)
Constructor (setting default values)
References ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::dim, ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_imDensity, ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_imKinViscosity, ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_imSlidingFactor, ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_imSlidingLimit, ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_vBndSubSetIndex, ug::IElemDiscBase< class >::num_fct(), ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::register_all_funcs(), ug::IElemDiscBase< class >::register_import(), DataImport< number, dim >::set_data(), and UG_THROW.
Member Function Documentation
add()
template<typename TDomain > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::add (const char * subsets)
adds a boundary segment
The add method for the boundary subsets:
add_def_A_elem()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::add_def_A_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
adds the stiffness part to the local defect
References dim, ug::GeomProvider< class >::get(), normal, UG_ASSERT, ug::VecDot(), ug::VecLength(), ug::VecNormalize(), and ug::VecScaleAppend().
add_def_M_elem()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::add_def_M_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) inline
add_jac_A_elem()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::add_jac_A_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
adds the stiffness part to the local jacobian
References dim, ug::GeomProvider< class >::get(), ug::MatSet(), normal, UG_ASSERT, ug::VecDot(), ug::VecLength(), ug::VecNormalize(), ug::VecScaleAppend(), and ug::VecSet().
add_jac_M_elem()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::add_jac_M_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) inline
add_rhs_elem()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::add_rhs_elem (LocalVector & d, GridObject * elem, const MathVector< dim > vCornerCoords[]) inline
extract_scheduled_data()
template<typename TDomain > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::extract_scheduled_data private
converts the subset names where the BC is imposed to the corresponding subset indices (i.e. m_vScheduledBndSubSets -> m_vBndSubSetIndex):
References ug::ISubsetHandler::num_subsets(), ug::SubsetGroup::size(), UG_CATCH_THROW, and UG_LOG.
fsh_elem_loop()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::fsh_elem_loop virtual
finishes the element loop
Finalizes the element loop for a given element type.
Reimplemented from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >.
References ug::GeomProvider< class >::get().
prep_elem()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::prep_elem (const LocalVector & u, GridObject * elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
prepares the element for evaluation
General initializations of a given grid element for the assembling.
References ug::GeomProvider< class >::get(), subset_handler(), and UG_CATCH_THROW.
prep_elem_loop()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::prep_elem_loop (const ReferenceObjectID roid, const int si)
prepares the element loop
Prepares the element loop for a given element type: computes the FV-geo, ... Note that there are separate loops for every type of the grid elements.
References ug::GeomProvider< class >::get(), and UG_THROW.
prepare_setting()
template<typename TDomain > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::prepare_setting (const std::vector< LFEID > & vLfeID, bool bNonRegularGrid) virtual
type of trial space for each function used
Implements ug::IElemDiscBase< class >.
References dim, ug::LFEID::LAGRANGE, and UG_THROW.
register_all_funcs()
template<typename TDomain > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::register_all_funcs (bool bHang) protected
Referenced by ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::NavierStokesWSBCFV1().
register_func()
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::register_func protected
requests_local_time_series()
template<typename TDomain > virtual bool ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::requests_local_time_series () inline virtual
returns if local time series is needed
Reimplemented from ug::IElemDiscBase< class >.
set_density()
template<typename TDomain > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::set_density (SmartPtr< CplUserData< number, dim > > data) inline
sets the density
This method sets the density parameter.
Parameters
[in] data Density
References ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_imDensity, and DataImport< number, dim >::set_data().
set_kinematic_viscosity()
template<typename TDomain > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::set_kinematic_viscosity (SmartPtr< CplUserData< number, dim > > data) inline
sets the kinematic viscosity
This method sets the kinematic viscosity parameter.
Parameters
[in] data kinematic Viscosity
References ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_imKinViscosity, and DataImport< number, dim >::set_data().
set_sliding_factor()
template<typename TDomain > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::set_sliding_factor (number val)
sets the wall sliding factor
This method sets the wall sliding factor parameter.
Parameters
[in] data wall sliding factor
References make_sp().
set_sliding_limit()
template<typename TDomain > void ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::set_sliding_limit (number val)
sets the sliding limit
This method sets the sliding limit parameter.
Parameters
[in] data sliding limit
References make_sp().
Member Data Documentation
_P_
template<typename TDomain > const size_t ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::_P_ = dim static private
abbreviation for pressure
dim
template<typename TDomain > const int ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::dim = base_type::dim static
World dimension.
Referenced by ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::NavierStokesWSBCFV1().
m_imDensity
template<typename TDomain > DataImport<number, dim> ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_imDensity private
Data import for density.
Referenced by ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::NavierStokesWSBCFV1(), and ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::set_density().
m_imKinViscosity
template<typename TDomain > DataImport<number, dim> ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_imKinViscosity private
Data import for kinematic viscosity.
Referenced by ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::NavierStokesWSBCFV1(), and ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::set_kinematic_viscosity().
m_imSlidingFactor
template<typename TDomain > DataImport<number, dim> ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_imSlidingFactor private
Data import for sliding factor.
Referenced by ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::NavierStokesWSBCFV1().
m_imSlidingLimit
template<typename TDomain > DataImport<number, dim> ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_imSlidingLimit private
Data import for sliding limit.
Referenced by ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::NavierStokesWSBCFV1().
m_imSourceSCVF
template<typename TDomain > DataImport<MathVector<dim>, dim> ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_imSourceSCVF private
Data import for source.
m_spMaster
template<typename TDomain > SmartPtr< IncompressibleNavierStokesBase<TDomain> > ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_spMaster private
The master discretization:
m_vBndSubSetIndex
template<typename TDomain > std::vector<int> ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_vBndSubSetIndex private
Referenced by ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::NavierStokesWSBCFV1().
m_vGloIP
template<typename TDomain > std::vector<MathVector<dim> > ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_vGloIP private
m_vLocIP
template<typename TDomain > std::vector<MathVector<dim> > ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_vLocIP private
Boundary integration points of the viscosity and the density.
m_vScheduledBndSubSets
template<typename TDomain > std::vector<std::string> ug::NavierStokes::NavierStokesWSBCFV1< TDomain >::m_vScheduledBndSubSets private
The boundary subsets:
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/bnd/wall_sliding_fv1.h
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/bnd/wall_sliding_fv1.cpp