Plugins: ug::promesh::ProMeshFunction Class Reference
ug::promesh::ProMeshFunction Class Reference
Plugins » ProMesh
All functions registered in the ProMeshRegistry are encapsulated in a ProMeshFunction.
#include <promesh_registry.h>
Public Member Functions
bridge::ExportedFunction * exported_function ()
const bridge::ExportedFunction * exported_function () const
bool has_target (RegistryTargets t) const
bool operator< (const ProMeshFunction &f) const
int priority () const
ProMeshFunction (bridge::ExportedFunction *exportedFunction, int priority, unsigned int target)
Private Attributes
bridge::ExportedFunction * m_exportedFunction
int m_priority
unsigned int m_target
Detailed Description
All functions registered in the ProMeshRegistry are encapsulated in a ProMeshFunction.
Constructor & Destructor Documentation
ug::promesh::ProMeshFunction::ProMeshFunction (bridge::ExportedFunction * exportedFunction, int priority, unsigned int target) inline
Member Function Documentation
bridge::ExportedFunction* ug::promesh::ProMeshFunction::exported_function () inline
Referenced by operator<().
const bridge::ExportedFunction* ug::promesh::ProMeshFunction::exported_function () const inline
bool ug::promesh::ProMeshFunction::has_target (RegistryTargets t) const inline
bool ug::promesh::ProMeshFunction::operator< (const ProMeshFunction & f) const inline
References exported_function(), ug::bridge::ExportedFunctionBase::name(), ug::bridge::ExportedFunctionBase::num_parameter(), and priority().
int ug::promesh::ProMeshFunction::priority () const inline
Referenced by operator<().
Member Data Documentation
bridge::ExportedFunction* ug::promesh::ProMeshFunction::m_exportedFunction private
int ug::promesh::ProMeshFunction::m_priority private
unsigned int ug::promesh::ProMeshFunction::m_target private
The documentation for this class was generated from the following file:
/home/sreiter/projects/ug4-docu/plugins/ProMesh/promesh_registry.h