Plugins: ug::Richards::GardnerModel Class Reference
ug::Richards::GardnerModel Class Reference
Implements a van Genuchten model.
#include <van_genuchten.h>
Public Types
typedef IRichardsModel< GardnerModel > base_type
typedef VanGenuchtenParameters parameter_type
typedef IParameterizedModel< HaverkampParameters > parameterized_model_type
Public Member Functions
std::string config_string () const
GardnerModel (const VanGenuchtenParameters &p)
void get_conductivity (double H, double &K, double &dKdH) const
Conductivity K.
void get_saturation (double H, double &S, double &dSdH) const
Saturation.
Public Member Functions inherited from ug::Richards::IParameterizedModel< HaverkampParameters >
std::string config_string () const
const HaverkampParameters & get_parameters () const
IParameterizedModel ()
IParameterizedModel (const HaverkampParameters &p)
void set_parameters (const HaverkampParameters &p)
Public Member Functions inherited from ug::Richards::IRichardsModel< GardnerModel >
double Conductivity (double H)
Conductivity K = Ks*kr.
double dConductivity_dH (double H)
double dSaturation_dH (double H) const
void get_conductivities (const double *H, double *K, double *dKdH, size_t n) const
void get_conductivity (double H, double &K, double &dKdH) const
Calls Conductivity_.
void get_relative_permeabilities (const double *H, double *K, double *dKdH, size_t n) const
void get_relative_permeability (double H, double &Kr, double &dKrdH) const
Calls RelativePermeability_.
void get_saturation (double H, double &S, double &dSdH) const
Calls Saturation_.
void get_saturations (const double *H, double *S, double *dSdH, size_t n) const
double Saturation (double H) const
Static Protected Member Functions
static dual Conductivity_ (dual psi_, const VanGenuchtenParameters &p)
static dual EffSaturation_ (dual psi_, const VanGenuchtenParameters &p)
Normalisierter Wassergehalt (reduzierte Sättigung):
static dual Saturation_ (dual psi_, const VanGenuchtenParameters &p)
Rescaled Saturation.
Protected Attributes
VanGenuchtenParameters m_param
Static Protected Attributes
static double one
Additional Inherited Members
Public Attributes inherited from ug::Richards::IParameterizedModel< HaverkampParameters >
HaverkampParameters m_param
Protected Member Functions inherited from ug::Richards::IRichardsModel< GardnerModel >
void get_value_and_deriv (TFunc F, double H, double &f, double &df) const
GardnerModel * me ()
const GardnerModel * me () const
Detailed Description
Implements a van Genuchten model.
Member Typedef Documentation
base_type
typedef IRichardsModel<GardnerModel> ug::Richards::GardnerModel::base_type
parameter_type
typedef VanGenuchtenParameters ug::Richards::GardnerModel::parameter_type
parameterized_model_type
typedef IParameterizedModel<HaverkampParameters> ug::Richards::GardnerModel::parameterized_model_type
Constructor & Destructor Documentation
GardnerModel()
ug::Richards::GardnerModel::GardnerModel (const VanGenuchtenParameters & p) inline
Member Function Documentation
Conductivity_()
static dual ug::Richards::GardnerModel::Conductivity_ (dual psi_, const VanGenuchtenParameters & p) inline static protected
References EffSaturation_(), and p.
Referenced by get_conductivity().
config_string()
std::string ug::Richards::GardnerModel::config_string () const
EffSaturation_()
static dual ug::Richards::GardnerModel::EffSaturation_ (dual psi_, const VanGenuchtenParameters & p) inline static protected
Normalisierter Wassergehalt (reduzierte Sättigung):
0 \le (1/1+(alpha * psi)^n)^m \le 1
References p.
Referenced by Conductivity_(), and Saturation_().
get_conductivity()
void ug::Richards::GardnerModel::get_conductivity (double H, double & K, double & dKdH) const inline
Conductivity K.
References Conductivity_(), ug::Richards::IRichardsModel< GardnerModel >::get_value_and_deriv(), and m_param.
get_saturation()
void ug::Richards::GardnerModel::get_saturation (double H, double & S, double & dSdH) const inline
Saturation.
References ug::Richards::IRichardsModel< GardnerModel >::get_value_and_deriv(), m_param, ug::Richards::IRichardsModel< GardnerModel >::me(), and Saturation_().
Saturation_()
static dual ug::Richards::GardnerModel::Saturation_ (dual psi_, const VanGenuchtenParameters & p) inline static protected
Rescaled Saturation.
References EffSaturation_(), and p.
Referenced by get_saturation().
Member Data Documentation
m_param
VanGenuchtenParameters ug::Richards::GardnerModel::m_param protected
Referenced by get_conductivity(), and get_saturation().
one
double ug::Richards::GardnerModel::one static protected
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Richards/van_genuchten.h