Plugins: ug::Richards::RichardsElemDisc< TDomain > Class Template Reference
ug::Richards::RichardsElemDisc< TDomain > Class Template Reference
#include <richards_elem_disc.h>
Public Types
typedef ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain > base_type
typedef SmartPtr< CplUserData< number, dim > > NumberExport
typedef CplUserData< number, dim > TNumberData
typedef CplUserData< MathVector< dim >, dim > TVectorData
typedef SmartPtr< CplUserData< MathVector< dim >, dim > > VectorExport
Public Types inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
typedef SmartPtr< CplUserData< MathVector< dim >, dim > > GradExport
typedef SmartPtr< CplUserData< number, dim > > NumberExport
Public Types inherited from ug::IElemDisc< TDomain >
typedef IElemAssembleFuncs< IElemDisc< TDomain >, TDomain > assemble_base_type
typedef IElemError< TDomain > base_type
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Public Types inherited from ug::IElemError< class >
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from ug::IElemDiscBase< class >
typedef TDomain domain_type
typedef TDomain::position_type position_type
Public Types inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Public Member Functions
SmartPtr< TNumberData > get_conductivity_data ()
conductivity
SmartPtr< TVectorData > get_flux_data ()
returns the export of the darcy velocity
SmartPtr< TNumberData > get_storage_data ()
the export of storage terms
RichardsElemDisc (const char *functions, const char *subsets)
CTOR.
void set_conductivity_data (SmartPtr< TNumberData > myCond)
void set_flux_data (SmartPtr< TVectorData > myFlux)
void set_storage_data (SmartPtr< TNumberData > storage)
Public Member Functions inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >
bool condensed_FV ()
returns the 'condensed scvf ip' flag
ConvectionDiffusionFV1 (const char *functions, const char *subsets)
Constructor.
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegularGrid)
type of trial space for each function used
void set_condensed_FV (bool condensed)
activates/deactivates the condensed scvf ip's for the FV scheme
void set_sss_manager (SmartPtr< CDSingularSourcesAndSinks< dim > > sss_mngr)
set singular sources and sinks
void set_upwind (SmartPtr< IConvectionShapes< dim > > shapes)
set the upwind method
SmartPtr< CDSingularSourcesAndSinks< dim > > sss_manager ()
get singular sources and sinks
virtual bool use_hanging () const
returns if hanging nodes are needed
Public Member Functions inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
ConvectionDiffusionBase (const char *functions, const char *subsets)
Constructor.
virtual SmartPtr< CplUserData< MathVector< dim >, dim > > gradient ()
returns the export of the gradient of associated unknown function
void set_reaction_explicit (number val)
void set_reaction_explicit (SmartPtr< CplUserData< number, dim > > user)
void set_reaction_rate_explicit (number val)
void set_reaction_rate_explicit (SmartPtr< CplUserData< number, dim > > user)
void set_source_explicit (number val)
void set_source_explicit (SmartPtr< CplUserData< number, dim > > user)
virtual SmartPtr< CplUserData< number, dim > > value ()
returns the export of the value of associated unknown function
void set_diffusion (SmartPtr< CplUserData< MathMatrix< dim, dim >, dim > > user)
sets the diffusion tensor
void set_diffusion (number val)
sets the diffusion tensor
void set_velocity (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the velocity field
void set_velocity (const std::vector< number > &vVel)
sets the velocity field
void set_flux (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the flux
void set_flux (const std::vector< number > &vVel)
sets the flux
void set_reaction_rate (SmartPtr< CplUserData< number, dim > > user)
sets the reaction rate
void set_reaction_rate (number val)
sets the reaction rate
void set_reaction (SmartPtr< CplUserData< number, dim > > user)
sets the reaction
void set_reaction (number val)
sets the reaction
void set_source (SmartPtr< CplUserData< number, dim > > user)
sets the source / sink term
void set_source (number val)
sets the source / sink term
void set_vector_source (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the vector source term
void set_vector_source (const std::vector< number > &vVel)
sets the vector source term
void set_mass_scale (SmartPtr< CplUserData< number, dim > > user)
sets mass scale
void set_mass_scale (number val)
sets mass scale
void set_mass (SmartPtr< CplUserData< number, dim > > user)
sets mass
void set_mass (number val)
sets mass
Public Member Functions inherited from ug::IElemDisc< TDomain >
void add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier)
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > & get_elem_modifier ()
IElemDisc (const char *functions, const char *subsets)
IElemDisc (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
virtual void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_fsh_elem_loop ()
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_timestep (number future_time, const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void fsh_timestep (number time, VectorProxyBase *u)
virtual void fsh_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemAssembleFuncs ()
virtual void post_assemble_loop ()
virtual void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
virtual void prep_elem_loop (const ReferenceObjectID roid, const int si)
virtual void prep_timestep (number future_time, number time, VectorProxyBase *u)
virtual void prep_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemAssembleFuncs ()
Public Member Functions inherited from ug::IElemError< class >
IElemError (const char *functions, const char *subsets)
IElemError (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from ug::IElemDiscBase< class >
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
void check_setup (bool bNonRegularGrid)
void clear_imports ()
SmartPtr< TDomain > domain ()
ConstSmartPtr< TDomain > domain () const
const FunctionGroup & function_group () const
ConstSmartPtr< FunctionPattern > function_pattern () const
IDataImport< dim > & get_import (size_t i)
IElemDiscBase (const char *functions="", const char *subsets="")
IElemDiscBase (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
bool is_time_dependent () const
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
const FunctionIndexMapping & map () const
number mass_scale () const
number mass_scale () const
number mass_scale (const size_t timePoint) const
number mass_scale (const size_t timePoint) const
const std::vector< number > & mass_scales () const
const std::vector< number > & mass_scales () const
size_t num_fct () const
size_t num_imports () const
size_t num_subsets () const
void register_import (IDataImport< dim > &Imp)
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_functions (const std::string &functions)
void set_functions (const std::vector< std::string > &functions)
void set_stationary ()
void set_stationary (bool bStationaryForced=true)
void set_subsets (const std::string &subsets)
void set_subsets (const std::vector< std::string > &subsets)
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
void set_time_independent ()
void set_time_point (const size_t timePoint)
number stiff_scale () const
number stiff_scale () const
number stiff_scale (const size_t timePoint) const
number stiff_scale (const size_t timePoint) const
const std::vector< number > & stiff_scales () const
const std::vector< number > & stiff_scales () const
TDomain::subset_handler_type & subset_handler ()
const TDomain::subset_handler_type & subset_handler () const
const std::vector< std::string > & symb_fcts () const
const std::vector< std::string > & symb_subsets () const
number time () const
size_t time_point () const
virtual int type () const
virtual ~IElemDiscBase ()
Public Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
virtual void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_err_est_elem_loop ()
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
IElemEstimatorFuncs ()
virtual void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemEstimatorFuncs ()
Static Public Attributes
static const int dim = TDomain::dim
Static Public Attributes inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::IElemDisc< TDomain >
static const int dim
Static Public Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Static Public Attributes inherited from ug::IElemError< class >
static const int dim
Static Public Attributes inherited from ug::IElemDiscBase< class >
static const int dim
Static Public Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Protected Attributes
SmartPtr< TVectorData > m_spFlux
Export for the Darcy velocity.
SmartPtr< TNumberData > m_spStorage
Export for the brine mass fraction.
SmartPtr< TNumberData > m_spTotalConductivity
Export for absolute conductivity.
Protected Attributes inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >
bool m_bCondensedFV
if to use the 'condensed' FV scvf ip's
bool m_bNonRegularGrid
current regular grid flag
SmartPtr< IConvectionShapes< dim > > m_spConvShape
method to compute the upwind shapes
Protected Attributes inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
SmartPtr< DataExport< MathVector< dim >, dim > > m_exGrad
Export for the gradient of concentration.
SmartPtr< DataExport< number, dim > > m_exValue
Export for the concentration.
DataImport< MathMatrix< dim, dim >, dim > m_imDiffusion
Data import for Diffusion.
DataImport< MathVector< dim >, dim > m_imFlux
Data import for the Flux.
DataImport< number, dim > m_imMass
Data import for the mass scale.
DataImport< number, dim > m_imMassScale
Data import for the mass scale.
DataImport< number, dim > m_imReaction
Data import for the reaction term.
DataImport< number, dim > m_imReactionExpl
Data import for the reaction term explicit.
DataImport< number, dim > m_imReactionRate
Data import for the reaction term.
DataImport< number, dim > m_imReactionRateExpl
Data import for the reaction_rate term explicit.
DataImport< number, dim > m_imSource
Data import for the right-hand side (volume)
DataImport< number, dim > m_imSourceExpl
Data import for the source term explicit.
DataImport< MathVector< dim >, dim > m_imVectorSource
Data import for the right-hand side (vector)
DataImport< MathVector< dim >, dim > m_imVelocity
Data import for the Velocity field.
Protected Attributes inherited from ug::IElemDisc< TDomain >
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > m_spElemModifier
Protected Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
Protected Attributes inherited from ug::IElemDiscBase< class >
bool m_bStationaryForced
FunctionGroup m_fctGrp
FunctionIndexMapping m_fctIndexMap
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
ConstSmartPtr< FunctionPattern > m_spFctPattern
size_t m_timePoint
std::vector< std::string > m_vFct
std::vector< IDataImport< dim > * > m_vIImport
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
std::vector< std::string > m_vSubset
Protected Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
Additional Inherited Members
Protected Types inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >
typedef IConvectionShapes< dim > conv_shape_type
returns the updated convection shapes
Protected Member Functions inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >
template<typename TElem , typename TFVGeom >
void ex_grad (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< TFVGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< MathVector< dim > > > vvvDeriv[])
computes the gradient of the concentration
template<typename TElem , typename TFVGeom >
void ex_value (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< TFVGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< number > > vvvDeriv[])
computes the concentration
const IConvectionShapes< dim > & get_updated_conv_shapes (const FVGeometryBase &geo, bool compute_deriv)
template<typename TElem , typename TFVGeom >
void lin_def_diffusion (const LocalVector &u, std::vector< std::vector< MathMatrix< dim, dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the diffusion
template<typename TElem , typename TFVGeom >
void lin_def_flux (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the flux
template<typename TElem , typename TFVGeom >
void lin_def_mass (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the mass scale term
template<typename TElem , typename TFVGeom >
void lin_def_mass_scale (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the mass scale term
template<typename TElem , typename TFVGeom >
void lin_def_reaction (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the reaction
template<typename TElem , typename TFVGeom >
void lin_def_reaction_rate (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the reaction
template<typename TElem , typename TFVGeom >
void lin_def_source (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the source term
template<typename TElem , typename TFVGeom >
void lin_def_vector_source (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the vector source term
template<typename TElem , typename TFVGeom >
void lin_def_velocity (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the velocity
void register_all_funcs (bool bHang)
template<typename TElem >
void register_func_for_ (bool bHang)
template<typename TElem , typename TFVGeom >
void register_func ()
Protected Member Functions inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
void init_imports ()
Protected Member Functions inherited from ug::IElemDisc< TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void set_default_add_fct ()
Protected Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_add_def_A_elem_fct (ReferenceObjectID id)
void remove_add_def_A_expl_elem_fct (ReferenceObjectID id)
void remove_add_def_M_elem_fct (ReferenceObjectID id)
void remove_add_jac_A_elem_fct (ReferenceObjectID id)
void remove_add_jac_M_elem_fct (ReferenceObjectID id)
void remove_add_rhs_elem_fct (ReferenceObjectID id)
void remove_fsh_elem_loop_fct (ReferenceObjectID id)
void remove_fsh_timestep_elem_fct (ReferenceObjectID id)
void remove_fsh_timestep_fct (size_t algebra_id)
void remove_prep_elem_fct (ReferenceObjectID id)
void remove_prep_elem_loop_fct (ReferenceObjectID id)
void remove_prep_timestep_elem_fct (ReferenceObjectID id)
void remove_prep_timestep_fct (size_t algebra_id)
void set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_fct (size_t algebra_id, TAssFunc func)
void set_prep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_fct (size_t algebra_id, TAssFunc func)
Protected Member Functions inherited from ug::IElemError< class >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
Protected Member Functions inherited from ug::IElemDiscBase< class >
virtual void approximation_space_changed ()
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
void update_function_index_mapping ()
Protected Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
Member Typedef Documentation
base_type
template<typename TDomain > typedef ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1<TDomain> ug::Richards::RichardsElemDisc< TDomain >::base_type
NumberExport
template<typename TDomain > typedef SmartPtr<CplUserData<number, dim> > ug::Richards::RichardsElemDisc< TDomain >::NumberExport
TNumberData
template<typename TDomain > typedef CplUserData<number, dim> ug::Richards::RichardsElemDisc< TDomain >::TNumberData
TVectorData
template<typename TDomain > typedef CplUserData<MathVector<dim>, dim> ug::Richards::RichardsElemDisc< TDomain >::TVectorData
VectorExport
template<typename TDomain > typedef SmartPtr<CplUserData<MathVector<dim>, dim> > ug::Richards::RichardsElemDisc< TDomain >::VectorExport
Constructor & Destructor Documentation
RichardsElemDisc()
template<typename TDomain > ug::Richards::RichardsElemDisc< TDomain >::RichardsElemDisc (const char * functions, const char * subsets) inline
CTOR.
Member Function Documentation
get_conductivity_data()
template<typename TDomain > SmartPtr<TNumberData> ug::Richards::RichardsElemDisc< TDomain >::get_conductivity_data () inline
conductivity
References ug::Richards::RichardsElemDisc< TDomain >::m_spTotalConductivity.
get_flux_data()
template<typename TDomain > SmartPtr<TVectorData> ug::Richards::RichardsElemDisc< TDomain >::get_flux_data () inline
returns the export of the darcy velocity
References ug::Richards::RichardsElemDisc< TDomain >::m_spFlux.
get_storage_data()
template<typename TDomain > SmartPtr<TNumberData> ug::Richards::RichardsElemDisc< TDomain >::get_storage_data () inline
the export of storage terms
References ug::Richards::RichardsElemDisc< TDomain >::m_spStorage.
set_conductivity_data()
template<typename TDomain > void ug::Richards::RichardsElemDisc< TDomain >::set_conductivity_data (SmartPtr< TNumberData > myCond) inline
References ug::Richards::RichardsElemDisc< TDomain >::m_spTotalConductivity.
set_flux_data()
template<typename TDomain > void ug::Richards::RichardsElemDisc< TDomain >::set_flux_data (SmartPtr< TVectorData > myFlux) inline
References ug::Richards::RichardsElemDisc< TDomain >::m_spFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::set_diffusion(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::set_flux().
set_storage_data()
template<typename TDomain > void ug::Richards::RichardsElemDisc< TDomain >::set_storage_data (SmartPtr< TNumberData > storage) inline
References ug::Richards::RichardsElemDisc< TDomain >::m_spStorage, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::set_mass(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::set_mass_scale().
Member Data Documentation
dim
template<typename TDomain > const int ug::Richards::RichardsElemDisc< TDomain >::dim = TDomain::dim static
m_spFlux
template<typename TDomain > SmartPtr<TVectorData> ug::Richards::RichardsElemDisc< TDomain >::m_spFlux protected
Export for the Darcy velocity.
Referenced by ug::Richards::RichardsElemDisc< TDomain >::get_flux_data(), and ug::Richards::RichardsElemDisc< TDomain >::set_flux_data().
m_spStorage
template<typename TDomain > SmartPtr<TNumberData> ug::Richards::RichardsElemDisc< TDomain >::m_spStorage protected
Export for the brine mass fraction.
Referenced by ug::Richards::RichardsElemDisc< TDomain >::get_storage_data(), and ug::Richards::RichardsElemDisc< TDomain >::set_storage_data().
m_spTotalConductivity
template<typename TDomain > SmartPtr<TNumberData> ug::Richards::RichardsElemDisc< TDomain >::m_spTotalConductivity protected
Export for absolute conductivity.
Referenced by ug::Richards::RichardsElemDisc< TDomain >::get_conductivity_data(), and ug::Richards::RichardsElemDisc< TDomain >::set_conductivity_data().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Richards/richards_elem_disc.h