Plugins: ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction > Class Template Reference
ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction > Class Template Reference
#include <turbulent_viscosity_fvcr.h>
Public Member Functions
CRSmagorinskyTurbViscData (SmartPtr< ApproximationSpace< domain_type > > approxSpace, SmartPtr< TGridFunction > spGridFct, number c=0.05)
constructor
void set_model_parameter (number c)
void update ()
virtual ~CRSmagorinskyTurbViscData ()
Public Member Functions inherited from ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >
void addUiUjTerm (aSideTensor &aaDefTensor, const number factor, SmartPtr< TGridFunction > u, aSideDimVector *aaU)
void assembleDeformationTensor (aSideTensor &aaDefTensor, aSideNumber &aaVol, SmartPtr< TGridFunction > u, aSideDimVector *aaU)
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
void elementFilter (PeriodicAttachmentAccessor< side_type, Attachment< VType > > &aaUHat, aSideNumber &aaVol, SmartPtr< TGridFunction > u, PeriodicAttachmentAccessor< side_type, Attachment< VType > > *aaU)
void evaluate (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
void fillAttachment (aSideDimVector &aaU, SmartPtr< TGridFunction > u)
virtual void operator() (number &value, const MathVector< dim > &globIP, number time, int si) const
virtual void operator() (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
virtual bool requires_grid_fct () const
returns if grid function is needed for evaluation
void scaleTensorByNorm (aSideTensor &aaTensor)
void scvFilter (PeriodicAttachmentAccessor< side_type, Attachment< VType > > &aaUHat, aSideNumber &aaVol, SmartPtr< TGridFunction > u, PeriodicAttachmentAccessor< side_type, Attachment< VType > > *aaU)
void setTurbulenceZeroBoundaries (const char *subsets)
void transferToLowerLevels (aSideNumber &aaData, ApproximationSpace< domain_type > &approximationSpace)
void set_kinematic_viscosity (SmartPtr< CplUserData< number, dim > > user)
void set_kinematic_viscosity (number val)
Public Member Functions inherited from ug::StdUserData< class, class, dim, class, class >
virtual TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const=0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const=0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
Public Member Functions inherited from CplUserData< TData, dim, void >
bool defined (size_t s, size_t ip) const
size_t num_ip (size_t s) const
size_t num_series () const
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
void unregister_storage_callback (DataImport< TData, dim > *obj)
TData & value (size_t s, size_t ip)
const TData & value (size_t s, size_t ip) const
TData * values (size_t s)
const TData * values (size_t s) const
~CplUserData ()
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
virtual void check_setup () const
void clear ()
virtual bool constant () const
int dim_local_ips () const
ICplUserData ()
const MathVector< dim > & ip (size_t s, size_t ip) const
const MathVector< dim > * ips (size_t s) const
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
const MathVector< ldim > * local_ips (size_t s) const
virtual SmartPtr< ICplUserData > needed_data (size_t i)
size_t num_ip (size_t s) const
virtual size_t num_needed_data () const
size_t num_series () const
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
void set_subset (int si)
void set_time_point (const size_t seriesId, const int timePointSpec)
void set_time_point (size_t timePoint)
void set_times (const std::vector< number > &vTime)
int subset () const
number time () const
number time (size_t s) const
size_t time_point ()
size_t time_point (size_t s) const
int time_point_specification (size_t s) const
virtual void update_dof_sizes (const LocalIndices &ind)
virtual bool zero_derivative () const
virtual ~ICplUserData ()
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
const FunctionIndexMapping & map () const
size_t num_fct () const
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
virtual ~UserDataInfo ()
Public Member Functions inherited from UserData< TData, dim, void >
int get_dim () const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, Vertex *vrt) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const =0
std::string type () const
Public Member Functions inherited from ug::INewtonUpdate
virtual ~INewtonUpdate ()
Public Attributes
bool m_bAdaptive
Public Attributes inherited from ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >
aSideTensor m_acDeformation
aSideNumber m_acTurbulentViscosity
aSideNumber m_acVolume
ATensor m_aDeformation
ANumber m_aTurbulentViscosity
ANumber m_aVolume
grid_type * m_grid
Private Types
typedef TGridFunction::algebra_type algebra_type
algebra type
typedef PeriodicAttachmentAccessor< side_type, ANumber > aSideNumber
typedef PeriodicAttachmentAccessor< side_type, ATensor > aSideTensor
typedef Attachment< dimMat > ATensor
typedef StdTurbulentViscosityData< number, TGridFunction::dim, this_type, TGridFunction > base_type
base class type
typedef MathSymmetricMatrix< dim > dimMat
attachment accessor types
typedef TGridFunction::domain_type domain_type
domain type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef TGridFunction::template dim_traits< dim >::const_iterator ElemIterator
element iterator
typedef domain_type::grid_type grid_type
grid type
typedef domain_type::position_accessor_type position_accessor_type
position accessor type
typedef elem_type::side side_type
side type
typedef TGridFunction::template traits< side_type >::const_iterator SideIterator
side iterator
typedef CRSmagorinskyTurbViscData< TGridFunction > this_type
own type
Private Attributes
number m_c
PeriodicBoundaryManager * m_pbm
SmartPtr< ApproximationSpace< domain_type > > m_spApproxSpace
SmartPtr< TGridFunction > m_u
Static Private Attributes
static const int dim = domain_type::dim
world dimension
Additional Inherited Members
Public Types inherited from CplUserData< TData, dim, void >
typedef ICplUserData< dim > base_type
Public Types inherited from UserData< TData, dim, void >
typedef TData data_type
typedef void return_type
Static Public Attributes inherited from ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >
static const size_t max_number_of_ips
Protected Member Functions inherited from ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >
CRSmagorinskyTurbViscData< TGridFunction > & getImpl ()
access to implementation
const CRSmagorinskyTurbViscData< TGridFunction > & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::StdUserData< class, class, dim, class, class >
TImpl & getImpl ()
const TImpl & getImpl () const
Protected Member Functions inherited from CplUserData< TData, dim, void >
void call_storage_callback () const
void check_series (size_t s) const
void check_series_ip (size_t s, size_t ip) const
virtual void local_ip_series_added (const size_t seriesID)
virtual void local_ip_series_to_be_cleared ()
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
virtual void value_storage_changed (const size_t seriesID)
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
void check_s_ip (size_t s, size_t ip) const
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
Protected Attributes inherited from ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >
bool m_bAdaptive
SmartPtr< CplUserData< number, dim > > m_imKinViscosity
Data import for kinematic viscosity.
SubsetGroup m_turbZeroSg
SmartPtr< TGridFunction > m_uInfo
number m_viscosityNumber
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
int m_locPosDim
std::vector< const MathVector< 1 > * > m_pvLocIP1d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
size_t m_timePoint
std::vector< bool > m_vMayChange
std::vector< size_t > m_vNumIP
std::vector< number > m_vTime
std::vector< int > m_vTimePoint
std::vector< const MathVector< dim > * > m_vvGlobPos
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
FunctionIndexMapping m_map
Member Typedef Documentation
algebra_type
template<typename TGridFunction > typedef TGridFunction::algebra_type ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::algebra_type private
algebra type
aSideNumber
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<side_type,ANumber > ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::aSideNumber private
aSideTensor
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<side_type,ATensor > ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::aSideTensor private
ATensor
template<typename TGridFunction > typedef Attachment<dimMat> ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::ATensor private
base_type
template<typename TGridFunction > typedef StdTurbulentViscosityData<number,TGridFunction::dim,this_type,TGridFunction> ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::base_type private
base class type
dimMat
template<typename TGridFunction > typedef MathSymmetricMatrix<dim> ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::dimMat private
attachment accessor types
domain_type
template<typename TGridFunction > typedef TGridFunction::domain_type ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::domain_type private
domain type
elem_type
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::grid_base_object ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::elem_type private
element type
ElemIterator
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::const_iterator ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::ElemIterator private
element iterator
grid_type
template<typename TGridFunction > typedef domain_type::grid_type ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::grid_type private
grid type
position_accessor_type
template<typename TGridFunction > typedef domain_type::position_accessor_type ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::position_accessor_type private
position accessor type
side_type
template<typename TGridFunction > typedef elem_type::side ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::side_type private
side type
SideIterator
template<typename TGridFunction > typedef TGridFunction::template traits<side_type>::const_iterator ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::SideIterator private
side iterator
this_type
template<typename TGridFunction > typedef CRSmagorinskyTurbViscData<TGridFunction> ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::this_type private
own type
Constructor & Destructor Documentation
CRSmagorinskyTurbViscData()
template<typename TGridFunction > ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::CRSmagorinskyTurbViscData (SmartPtr< ApproximationSpace< domain_type > > approxSpace, SmartPtr< TGridFunction > spGridFct, number c = 0.05) inline
constructor
References ug::PeriodicAttachmentAccessor< class, class >::access(), SmartPtr< TGridFunction >::get(), grid(), ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >::m_acDeformation, ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >::m_acTurbulentViscosity, ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >::m_acVolume, ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >::m_aDeformation, ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >::m_aTurbulentViscosity, ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >::m_aVolume, ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::m_c, ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >::m_grid, ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::m_pbm, ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::m_spApproxSpace, and ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::m_u.
~CRSmagorinskyTurbViscData()
template<typename TGridFunction > virtual ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::~CRSmagorinskyTurbViscData () inline virtual
References SmartPtr< TGridFunction >::get(), grid(), ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >::m_aDeformation, ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >::m_aTurbulentViscosity, ug::NavierStokes::StdTurbulentViscosityData< number, TGridFunction::dim, CRSmagorinskyTurbViscData< TGridFunction >, TGridFunction >::m_aVolume, and ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::m_u.
Member Function Documentation
set_model_parameter()
template<typename TGridFunction > void ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::set_model_parameter (number c) inline
References ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::m_c.
update()
template<typename TGridFunction > void ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::update virtual
Implements ug::INewtonUpdate.
References dim, num_subsets(), and ug::SetAttachmentValues().
Member Data Documentation
dim
template<typename TGridFunction > const int ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::dim = domain_type::dim static private
world dimension
m_bAdaptive
template<typename TGridFunction > bool ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::m_bAdaptive
m_c
template<typename TGridFunction > number ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::m_c private
Referenced by ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::CRSmagorinskyTurbViscData(), and ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::set_model_parameter().
m_pbm
template<typename TGridFunction > PeriodicBoundaryManager* ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::m_pbm private
Referenced by ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::CRSmagorinskyTurbViscData().
m_spApproxSpace
template<typename TGridFunction > SmartPtr<ApproximationSpace<domain_type> > ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::m_spApproxSpace private
Referenced by ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::CRSmagorinskyTurbViscData().
m_u
template<typename TGridFunction > SmartPtr<TGridFunction> ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::m_u private
Referenced by ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::CRSmagorinskyTurbViscData(), and ug::NavierStokes::CRSmagorinskyTurbViscData< TGridFunction >::~CRSmagorinskyTurbViscData().
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fvcr/turbulent_viscosity_fvcr.h
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fvcr/turbulent_viscosity_fvcr_impl.h