Plugins: ug::ConvectionDiffusionPlugin::cd_sss_data< dim > Class Template Reference
ug::ConvectionDiffusionPlugin::cd_sss_data< dim > Class Template Reference
class for data for all the CD plugin sources and sinks
#include <convection_diffusion_sss.h>
Public Member Functions
cd_sss_data ()
class construction (there must exist a 'dummy' constructor!)
void compute (const MathVector< dim > &x, number time, int si)
computes the data from the user data object
number flux ()
returns the flux
void set (LuaFunctionHandle func)
set as a LUA function
void set (number flux)
sets the data
void set (SmartPtr< UserData< MathVector< 1 >, dim > > spData)
sets the data by an object
Private Attributes
SmartPtr< UserData< MathVector< 1 >, dim > > m_spData
an alternative method to specify the data
MathVector< 1 > m_values
Detailed Description
template<int dim>
class ug::ConvectionDiffusionPlugin::cd_sss_data< dim >
class for data for all the CD plugin sources and sinks
Constructor & Destructor Documentation
cd_sss_data()
template<int dim> ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::cd_sss_data () inline
class construction (there must exist a 'dummy' constructor!)
References ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::m_values.
Member Function Documentation
compute()
template<int dim> void ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::compute (const MathVector< dim > & x, number time, int si) inline
computes the data from the user data object
Parameters
x point where to evaluate
time time argument for the evaluation
si subset where to evaluate
References ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::m_spData, and ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::m_values.
flux()
template<int dim> number ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::flux () inline
returns the flux
References ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::m_values.
Referenced by ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::set().
set() [1/3]
template<int dim> void ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::set (LuaFunctionHandle func) inline
set as a LUA function
References dim, ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::m_spData, and make_sp().
set() [2/3]
template<int dim> void ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::set (number flux) inline
sets the data
References ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::flux(), ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::m_spData, ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::m_values, and SPNULL.
set() [3/3]
template<int dim> void ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::set (SmartPtr< UserData< MathVector< 1 >, dim > > spData) inline
sets the data by an object
References ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::m_spData.
Member Data Documentation
m_spData
template<int dim> SmartPtr<UserData<MathVector<1>, dim> > ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::m_spData private
an alternative method to specify the data
Referenced by ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::compute(), and ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::set().
m_values
template<int dim> MathVector<1> ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::m_values private
the data for the source/sink: [0]: total contaminant flux through the point
Referenced by ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::cd_sss_data(), ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::compute(), ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::flux(), and ug::ConvectionDiffusionPlugin::cd_sss_data< dim >::set().
The documentation for this class was generated from the following file:
/var/lib/jenkins/workspace/ug-docs/plugins/ConvectionDiffusion/convection_diffusion_sss.h