Plugins: ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem > Class Template Reference
ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem > Class Template Reference
Helper class for the specialization of NedelecT1_LDisc for simplices (triangles and tetrahedrons)
#include <nedelec_local_ass.h>
Public Types
typedef TDomain::grid_type grid_type
type of the grid
typedef TDomain::position_type position_type
type of the geometric positions (WDim-vectors)
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
type of reference element
typedef LagrangeP1< ref_elem_type > W0_shapes_type
shapes and derivatives of the Whitney-0 (Lagrange P1) shape functions
Static Public Member Functions
static void curl (const TDomain *domain, TElem *elem, const position_type *corners, const number dofs[], MathVector< WDim > &curl_vec)
computes the curl of the grid functions (in 2d represented as \((z, 0)\) instead of \((0, 0, z)\))
static void get_shapes (const TDomain *domain, TElem *elem, const position_type *corners, const MathVector< dim > local, MathVector< WDim > shapes[])
computes the Nedelec shapes at a given point
static void interpolate (const TDomain *domain, TElem *elem, const position_type *corners, const number dofs[], const MathVector< dim > local[], const size_t n_pnt, MathVector< WDim > values[])
computes of the values of the grid functions
static void local_div_matrix (const TDomain *domain, TElem *elem, const position_type *corners, number B[][numEdges])
assembles the discrete weak div operator
static void local_mass (const TDomain *domain, TElem *elem, const position_type *corners, number M[maxNumEdges][maxNumEdges])
assembles the local mass matrix of the Nedelec elements
static void local_stiffness_and_mass (const TDomain *domain, TElem *elem, const position_type *corners, number S[maxNumEdges][maxNumEdges], number M[maxNumEdges][maxNumEdges])
assembles the local stiffness and mass matrices of the rot-rot operator
Static Public Attributes
static const int dim = ref_elem_type::dim
dimension of reference element
static const size_t maxNumEdges = (size_t) element_list_traits<typename domain_traits<WDim>::DimElemList>::maxEdges
max. number of the edges of the full-dimensional elements in the domain
static const size_t numCorners = ref_elem_type::numCorners
total number of the corners
static const size_t numEdges = ref_elem_type::numEdges
total number of the edges
static const int WDim = TDomain::dim
world dimention
Static Private Member Functions
static void compute_W0_grads (const position_type *corners, MathVector< WDim > grad[numCorners])
computes the gradients of the Whitney-0 (Lagrange P1) shape functions
static void get_edge_corners (const TDomain *domain, TElem *elem, size_t edge_corner[numEdges][2])
gets the correspondence between the edge dof indices and the corners of the element
Detailed Description
template<typename TDomain, typename TElem>
class ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >
Helper class for the specialization of NedelecT1_LDisc for simplices (triangles and tetrahedrons)
This class template implements the Whitney-1 (Nedelec) elements for triangles and tetrahedrons (i.e. implements the classical variant of these elements),
See also
NedelecT1_LDisc.
Consider a grid element \(T\). Let \(w^{(0)}_i\) denote the linear (Lagrangian) shape functions equal to 1 at corner i and to 0 at the other corners of \(T\). These are the Whitney-0 shape functions. The Whitney-1-shape functions \(w^{(1)}_e\) (constituting the Nedelec element) are assigned to edges \(e\) of \(T\). For the edge \(e = (i, j)\), this function is given by formula
\[ w^{(1)}_e = w^{(0)}_i \mathbf{grad} w^{(0)}_j - w^{(0)}_j \mathbf{grad} w^{(0)}_i. \]
These are vector-valued shape functions. They are well-defined for simplices (i.e. for triangles in 2d and tetrahedra in 3d), whereas the corresponding physical problems are typically formulated only in 3d.
Functions \(w^{(1)}_e\) are used for discretization of the differential operators of type \(\mathbf{rot} \mu^{-1} \mathbf{rot}\) with the discretization error \(O(h) \). The physical parameters (like \(\mu \)) are then considered constant over \(T\), so that this tool kit sets the physical factors to 1. (The local matrices can be multiplied by these factors later.) The local stiffness matrix computed by this tool kit is
\[ (S_{h,T})_{e_1,e_2} = \int_T \mathbf{rot} w^{(1)}_{e_1} \cdot \mathbf{rot} w^{(1)}_{e_2} dx, \]
and the mass matrix is
\[ (M^{(1)}_{h,T})_{e_1,e_2} = \int \sigma w^{(1)}_{e_1} \cdot w^{(1)}_{e_2} dx. \]
The computation of the stiffness matrix is exact. (The integrand is a linear function.) But the computation of the mass matrix is implemented by an inexact quadrature formula.
Remarks
Note that the definition of the Whitney-1 function depends on the ordering of the nodes in the element. More precisely, for a different ordering, the shape function \(w^{(1)}_e\) may have a different sign. Thus, the ordering should be consistent in all the elements: If two elements \(T_1\) and \(T_2\) share the edge \(e\) with the ends at corners \(i\) and \(j\) (that are shared, too) then this edge should be \(e = (i, j)\) for both the elements (and not for example \(e = (i, j)\) for \(T_1\) but \(e = (j, i)\) for \(T_2\)). In all the other respects, the ordering does not play any essential role. In particular, the singes of the degrees of freedom in the solution depend on the global ordering of the corners (but the absolute values of these dofs are invariant). For this, the solution of the discretized system may be only considered in connection with the given ordering of the corners (in the edges).
References:
O. Sterz. Modellierung und Numerik zeitharmonischer Wirbelstromprobleme in 3D. PhD thesis, Heidelberg University, 2003.
A. Bossavit. Computational Electromagnetism. Academic Press (Boston), 1998
Template Parameters
TDomain Domain type
TElem Element type
Member Typedef Documentation
grid_type
template<typename TDomain , typename TElem > typedef TDomain::grid_type ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::grid_type
type of the grid
position_type
template<typename TDomain , typename TElem > typedef TDomain::position_type ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::position_type
type of the geometric positions (WDim-vectors)
ref_elem_type
template<typename TDomain , typename TElem > typedef reference_element_traits<TElem>::reference_element_type ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::ref_elem_type
type of reference element
W0_shapes_type
template<typename TDomain , typename TElem > typedef LagrangeP1<ref_elem_type> ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::W0_shapes_type
shapes and derivatives of the Whitney-0 (Lagrange P1) shape functions
Member Function Documentation
compute_W0_grads()
template<typename TDomain , typename TElem > void ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::compute_W0_grads (const position_type * corners, MathVector< WDim > grad[numCorners]) static private
computes the gradients of the Whitney-0 (Lagrange P1) shape functions
Computes the gradients of the Whitney-0 (Lagrange P1) shape functions.
Remarks
We assume that the reference mapping is linear: Here, the Nedelec elements are only implemented for simplices.
Parameters
[in] corners array of the global corner coordinates
[out] grad gradients of the Whitney-0 functions
References ug::Provider< class >::get(), BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >::grads(), ug::ReferenceMapping< class, TWorldDim >::jacobian_transposed_inverse(), ug::MatVecMult(), UG_ASSERT, and ug::ReferenceMapping< class, TWorldDim >::update().
curl()
template<typename TDomain , typename TElem > void ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::curl (const TDomain * domain, TElem * elem, const position_type * corners, const number dof[], MathVector< WDim > & curl_vec) static
computes the curl of the grid functions (in 2d represented as \((z, 0)\) instead of \((0, 0, z)\))
Computes the curl of the grid functions
Remarks
Note that curl is constant over the element.
In 2d, the value of the curl should have the form \((0, 0, z)\). But to keep the dimensionality of the output, it is represented as \((z, 0)\).
Parameters
[in] domain the domain
[in] elem element
[in] corners array of the global corner coordinates
[in] dof arrays of values of the Nedelec degrees of freedom
[out] curl_vec where to store the computed curl
References ug::GenVecCross(), and ug::VecScaleAppend().
get_edge_corners()
template<typename TDomain , typename TElem > void ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::get_edge_corners (const TDomain * domain, TElem * elem, size_t edge_corner[numEdges][2]) static private
gets the correspondence between the edge dof indices and the corners of the element
gets the correspondence between the edge dof indices and the corners of the element
The edge dof indices correspond to the order of the edges in the reference element. To every edge, two vertices (the corners of the element) are assigned. We need them to be ordered independently of the element. This function assignes to every edge (i.e. every edge dof index) two indices of the corners of the element in order that corresponds to the global order of the vertices associated with these corners.
Parameters
[in] domain the domain
[in] elem the element
[out] edge_corner edge dof -> corner of the element
References SmartPtr< class, FreePolicy >::get(), ug::Provider< class >::get(), grid(), UG_ASSERT, and ug::EdgeVertices::vertex().
get_shapes()
template<typename TDomain , typename TElem > void ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::get_shapes (const TDomain * domain, TElem * elem, const position_type * corners, const MathVector< dim > local, MathVector< WDim > shapes[]) static
computes the Nedelec shapes at a given point
Computes the Nedelec shapes at a given point
Remarks
If the dimensionality of the given element is lower than that of the world then the shapes are projected to the element.
Parameters
[in] domain the domain
[in] elem element
[in] corners array of the global corner coordinates
[in] local local coordinates of the point where to compute
[out] shapes array for the shapes
References ug::Provider< class >::get(), local(), BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >::shapes(), and ug::VecScaleAdd().
interpolate()
template<typename TDomain , typename TElem > void ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::interpolate (const TDomain * domain, TElem * elem, const position_type * corners, const number dof[], const MathVector< dim > local[], const size_t n_pnt, MathVector< WDim > values[]) static
computes of the values of the grid functions
Computes of the values of the grid functions.
The values of the DoFs are scalar, but the resulting function is a vector field.
Parameters
[in] domain the domain
[in] elem element
[in] corners array of the global corner coordinates
[in] dof arrays of values of the Nedelec degrees of freedom
[in] local local coordinates of the points where to compute
[in] n_pnt number of the points where to compute
[out] values where to store the computed n_pnt values
References ug::Provider< class >::get(), local(), BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >::shapes(), ug::VecScaleAdd(), and ug::VecScaleAppend().
local_div_matrix()
template<typename TDomain , typename TElem > void ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::local_div_matrix (const TDomain * domain, TElem * elem, const position_type * corners, number B[][numEdges]) static
assembles the discrete weak div operator
This function assembles the local weak divergence operator \(\mathbf{B} \):
\[ \mathbf{B}_{v,e} = - \int_T w^{(1)}_e \cdot \mathbf{grad} w^{(0)}_v \, dx, \]
where \(T\) is the element, \(v\) its corner and \(e\) its edge. The integration is perfomed by the midpoint rule which is exact because the integrand is linear. Thus, for \(e = [v_1, v_2]\)
\[ \mathbf{B}_{v,e} = - \frac{|T|}{N} \mathbf{grad} w^{(0)}_v \cdot (\mathbf{grad} w^{(0)}_{v_2} - \mathbf{grad} w^{(0)}_{v_1}) \, dx. \]
(with \(N\) being the number of corners of \(T\)).
Parameters
[in] domain the domain
[in] elem element
[in] corners array of the global corner coordinates
[out] B local weak divergence operator matrix
local_mass()
template<typename TDomain , typename TElem > void ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::local_mass (const TDomain * domain, TElem * elem, const position_type * corners, number M[maxNumEdges][maxNumEdges]) static
assembles the local mass matrix of the Nedelec elements
Assembles the local mass matrix of the Nedelec element (i.e. performs a part of the task of local_stiffness_and_mass).
Remarks
We assume that the reference mapping is linear: The Nedelec elements are only implemented for simplices.
Parameters
[in] domain the domain
[in] elem element
[in] corners array of the global corner coordinates
[out] M local mass matrix
References ug::VecSubtract().
local_stiffness_and_mass()
template<typename TDomain , typename TElem > void ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::local_stiffness_and_mass (const TDomain * domain, TElem * elem, const position_type * corners, number S[maxNumEdges][maxNumEdges], number M[maxNumEdges][maxNumEdges]) static
assembles the local stiffness and mass matrices of the rot-rot operator
Assembles the local stiffness and mass matrices of the rot-rot operator
The matrices are not premultiplied by any physical factors: these factors are assumed to be constant over the element and must be applied later.
Remarks
We assume that the reference mapping is linear: The Nedelec elements are only implemented for simplices.
Parameters
[in] domain the domain
[in] elem element
[in] corners array of the global corner coordinates
[out] S local stiffness matrix
[out] M local mass matrix
References ug::GenVecCross(), ug::VecDot(), and ug::VecSubtract().
Member Data Documentation
dim
template<typename TDomain , typename TElem > const int ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::dim = ref_elem_type::dim static
dimension of reference element
maxNumEdges
template<typename TDomain , typename TElem > const size_t ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::maxNumEdges = (size_t) element_list_traits<typename domain_traits<WDim>::DimElemList>::maxEdges static
max. number of the edges of the full-dimensional elements in the domain
numCorners
template<typename TDomain , typename TElem > const size_t ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::numCorners = ref_elem_type::numCorners static
total number of the corners
numEdges
template<typename TDomain , typename TElem > const size_t ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::numEdges = ref_elem_type::numEdges static
total number of the edges
WDim
template<typename TDomain , typename TElem > const int ug::Electromagnetism::NedelecT1_LDisc_forSimplex< TDomain, TElem >::WDim = TDomain::dim static
world dimention
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_local_ass.h
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_local_ass_impl.h