Plugins: ug::Electromagnetism::EddyCurrentHeat< TGridFunc > Class Template Reference
ug::Electromagnetism::EddyCurrentHeat< TGridFunc > Class Template Reference
#include <eddy_current_gf_user_data.h>
Public Types
typedef TGridFunc::domain_type domain_type
Type of domain.
typedef domain_type::position_type position_type
Type of position coordinates (e.g. position_type)
Public Member Functions
virtual bool continuous () const
The vector field retrieved from the Nedelec-type 1 (Whitney-1) dofs are not continuous.
EddyCurrentHeat (SmartPtr< TGridFunc > spGridFct, const char *cmp, SmartPtr< EMaterial< domain_type > > emMatherial)
constructor
template<int refDim>
void eval_and_deriv (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, bool bDeriv, int s, std::vector< std::vector< number > > vvvDeriv[], const MathMatrix< refDim, dim > *vJT=NULL) const
Performs the main computations:
virtual bool requires_grid_fct () const
Returns true to get the grid element in the evaluation routine.
Public Member Functions inherited from ug::StdDependentUserData< EddyCurrentHeat< TGridFunc >, number, TGridFunc::dim >
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< TGridFunc::dim > vCornerCoords[], bool bDeriv=false)
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< TGridFunc::dim > vCornerCoords[], bool bDeriv=false)
void eval_deriv (LocalVector *u, GridObject *elem, const MathVector< TGridFunc::dim > vCornerCoords[], bool bDeriv=false)
void eval_deriv (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< TGridFunc::dim > vCornerCoords[], bool bDeriv=false)
void evaluate (number vValue[], const MathVector< TGridFunc::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunc::dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, TGridFunc::dim > *vJT=NULL) const
virtual void operator() (number &value, const MathVector< TGridFunc::dim > &globIP, number time, int si) const
virtual void operator() (number vValue[], const MathVector< TGridFunc::dim > vGlobIP[], number time, int si, const size_t nip) const
StdDependentUserData ()
StdDependentUserData (const char *symbFct)
StdDependentUserData (const std::string &symbFct)
StdDependentUserData (const std::vector< std::string > &symbFct)
Public Member Functions inherited from ug::StdUserData< StdDependentUserData< EddyCurrentHeat< TGridFunc >, number, TGridFunc::dim >, number, TGridFunc::dim, void, DependentUserData< number, TGridFunc::dim > >
virtual void operator() (number vValue[], const MathVector< TGridFunc::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunc::dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, TGridFunc::dim > *vJT=NULL) const
virtual void operator() (number vValue[], const MathVector< TGridFunc::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunc::dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, TGridFunc::dim > *vJT=NULL) const
virtual void operator() (number vValue[], const MathVector< TGridFunc::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunc::dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, TGridFunc::dim > *vJT=NULL) const
virtual void operator() (number vValue[], const MathVector< TGridFunc::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunc::dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, TGridFunc::dim > *vJT=NULL) const
virtual void operator() (number vValue[], const MathVector< TGridFunc::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunc::dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, TGridFunc::dim > *vJT=NULL) const
virtual void operator() (number vValue[], const MathVector< TGridFunc::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunc::dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, TGridFunc::dim > *vJT=NULL) const
Static Public Attributes
static const int dim = domain_type::dim
World dimension.
Static Public Attributes inherited from ug::Electromagnetism::EddyCurrentTraits
static const size_t _Im_ = 1
index of the imaginary part in the grid functions
static const size_t _Re_ = 0
index of the real part in the grid functions
Private Attributes
size_t m_fct [2]
components (Re and Im) of the grid function
SmartPtr< EMaterial< domain_type > > m_spEMaterial
subdomain-dependent data (propertiels of the materials)
SmartPtr< TGridFunc > m_spGF
grid function for \(\mathbf{E} \)
Additional Inherited Members
Protected Member Functions inherited from ug::StdDependentUserData< EddyCurrentHeat< TGridFunc >, number, TGridFunc::dim >
EddyCurrentHeat< TGridFunc > & getImpl ()
const EddyCurrentHeat< TGridFunc > & getImpl () const
Protected Member Functions inherited from ug::StdUserData< StdDependentUserData< EddyCurrentHeat< TGridFunc >, number, TGridFunc::dim >, number, TGridFunc::dim, void, DependentUserData< number, TGridFunc::dim > >
StdDependentUserData< EddyCurrentHeat< TGridFunc >, number, TGridFunc::dim > & getImpl ()
const StdDependentUserData< EddyCurrentHeat< TGridFunc >, number, TGridFunc::dim > & getImpl () const
Detailed Description
template<typename TGridFunc>
class ug::Electromagnetism::EddyCurrentHeat< TGridFunc >
UserData based class that computes the field of the heat sources \(Q = \frac{1}{2} \sigma \mathbf{E} \overline{\mathbf{E}}\), where \(\overline{\mathbf{E}}\) is the complex conjugate to \(\mathbf{E}\). The electric field \(\mathbf{E}\) in the grid function should be represented by the Nedelec-type-1 elements.
Member Typedef Documentation
domain_type
template<typename TGridFunc > typedef TGridFunc::domain_type ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::domain_type
Type of domain.
position_type
template<typename TGridFunc > typedef domain_type::position_type ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::position_type
Type of position coordinates (e.g. position_type)
Constructor & Destructor Documentation
EddyCurrentHeat()
template<typename TGridFunc > ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::EddyCurrentHeat (SmartPtr< TGridFunc > spGridFct, const char * cmp, SmartPtr< EMaterial< domain_type > > emMatherial) inline
constructor
Parameters
spGridFct grid function with the DoFs
cmp the components (Re and Im) of the grid function keeping the scalar DoFs
emMatherial properties of the materials
References ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::m_fct, ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::m_spGF, ug::LFEID::NEDELEC, ug::RemoveWhitespaceFromString(), ug::TokenizeString(), UG_CATCH_THROW, and UG_THROW.
Member Function Documentation
continuous()
template<typename TGridFunc > virtual bool ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::continuous () const inline virtual
The vector field retrieved from the Nedelec-type 1 (Whitney-1) dofs are not continuous.
eval_and_deriv()
template<typename TGridFunc > template<int refDim> void ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::eval_and_deriv (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, bool bDeriv, int s, std::vector< std::vector< number > > vvvDeriv[], const MathMatrix< refDim, dim > * vJT = NULL) const inline
Performs the main computations:
Parameters
vValue for the computed value
References ug::Electromagnetism::EddyCurrentTraits::_Im_, ug::Electromagnetism::EddyCurrentTraits::_Re_, ug::DoFRef(), SmartPtr< T, FreePolicy >::get(), ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::m_fct, ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::m_spEMaterial, ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::m_spGF, UG_THROW, ug::Electromagnetism::NedelecInterpolation< TDomain, refDim, WDim >::value(), and ug::VecTwoNormSq().
requires_grid_fct()
template<typename TGridFunc > virtual bool ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::requires_grid_fct () const inline virtual
Returns true to get the grid element in the evaluation routine.
Member Data Documentation
dim
template<typename TGridFunc > const int ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::dim = domain_type::dim static
World dimension.
m_fct
template<typename TGridFunc > size_t ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::m_fct[2] private
components (Re and Im) of the grid function
Referenced by ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::EddyCurrentHeat(), and ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::eval_and_deriv().
m_spEMaterial
template<typename TGridFunc > SmartPtr<EMaterial<domain_type> > ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::m_spEMaterial private
subdomain-dependent data (propertiels of the materials)
Referenced by ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::eval_and_deriv().
m_spGF
template<typename TGridFunc > SmartPtr<TGridFunc> ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::m_spGF private
grid function for \(\mathbf{E} \)
Referenced by ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::EddyCurrentHeat(), and ug::Electromagnetism::EddyCurrentHeat< TGridFunc >::eval_and_deriv().
The documentation for this class was generated from the following file:
/var/lib/jenkins/workspace/ug-docs/plugins/Electromagnetism/EddyCurrent_E_Nedelec/eddy_current_gf_user_data.h