Plugins: ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::LocLaplaceA< TElem > Class Template Reference
ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::LocLaplaceA< TElem > Class Template Reference
Helper class for assembling the local stiffness matrix of Laplacian in various routines.
Public Types
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
Static Public Member Functions
static void stiffness (GridObject *elem, const position_type vCornerCoords[], number loc_A[numCorners][numCorners])
Computes the local discretization of the Laplace operator.
Static Public Attributes
static const int numCorners = ref_elem_type::numCorners
Detailed Description
template<typename TDomain, typename TAlgebra>
template<typename TElem>
class ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::LocLaplaceA< TElem >
Helper class for assembling the local stiffness matrix of Laplacian in various routines.
Member Typedef Documentation
ref_elem_type
template<typename TDomain , typename TAlgebra > template<typename TElem > typedef reference_element_traits<TElem>::reference_element_type ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::LocLaplaceA< TElem >::ref_elem_type
Member Function Documentation
stiffness()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::LocLaplaceA< TElem >::stiffness (GridObject * elem, const position_type vCornerCoords[], number loc_A[numCorners][numCorners]) static
Computes the local discretization of the Laplace operator.
Computes the local discretization of the Laplace operator
Parameters
[in] elem element to compute for
[in] vCornerCoords coordinates of the corners of the element
[out] loc_A the local stiffness matrix
References ug::GeomProvider< class >::get(), UG_ASSERT, and ug::VecDot().
Referenced by ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceLocAss::ass_JA_elem().
Member Data Documentation
numCorners
template<typename TDomain , typename TAlgebra > template<typename TElem > const int ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::LocLaplaceA< TElem >::numCorners = ref_elem_type::numCorners static
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_project.h
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_project_impl.h