Plugins: ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss Class Reference
ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss Class Reference
Class for local assembling of the auxiliary Laplace operator.
Classes
struct RegisterLocalDiscr
Public Member Functions
AuxLaplaceLocAss (NedelecLoopCurrent &master)
constructor
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegular)
switches between non-regular and regular grids
Public Member Functions inherited from ug::IElemDisc< TDomain >
void add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier)
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > & get_elem_modifier ()
IElemDisc (const char *functions, const char *subsets)
IElemDisc (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
virtual void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_fsh_elem_loop ()
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_timestep (number future_time, const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void fsh_elem_loop ()
virtual void fsh_timestep (number time, VectorProxyBase *u)
virtual void fsh_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemAssembleFuncs ()
virtual void post_assemble_loop ()
virtual void prep_assemble_loop ()
virtual void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
virtual void prep_elem_loop (const ReferenceObjectID roid, const int si)
virtual void prep_timestep (number future_time, number time, VectorProxyBase *u)
virtual void prep_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemAssembleFuncs ()
Public Member Functions inherited from ug::IElemError< class >
IElemError (const char *functions, const char *subsets)
IElemError (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from ug::IElemDiscBase< class >
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
void check_setup (bool bNonRegularGrid)
void clear_imports ()
SmartPtr< TDomain > domain ()
ConstSmartPtr< TDomain > domain () const
const FunctionGroup & function_group () const
ConstSmartPtr< FunctionPattern > function_pattern () const
IDataImport< dim > & get_import (size_t i)
IElemDiscBase (const char *functions="", const char *subsets="")
IElemDiscBase (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
bool is_time_dependent () const
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
const FunctionIndexMapping & map () const
number mass_scale () const
number mass_scale () const
number mass_scale (const size_t timePoint) const
number mass_scale (const size_t timePoint) const
const std::vector< number > & mass_scales () const
const std::vector< number > & mass_scales () const
size_t num_fct () const
size_t num_imports () const
size_t num_subsets () const
void register_import (IDataImport< dim > &Imp)
virtual bool requests_local_time_series ()
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_functions (const std::string &functions)
void set_functions (const std::vector< std::string > &functions)
void set_stationary ()
void set_stationary (bool bStationaryForced=true)
void set_subsets (const std::string &subsets)
void set_subsets (const std::vector< std::string > &subsets)
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
void set_time_independent ()
void set_time_point (const size_t timePoint)
number stiff_scale () const
number stiff_scale () const
number stiff_scale (const size_t timePoint) const
number stiff_scale (const size_t timePoint) const
const std::vector< number > & stiff_scales () const
const std::vector< number > & stiff_scales () const
TDomain::subset_handler_type & subset_handler ()
const TDomain::subset_handler_type & subset_handler () const
const std::vector< std::string > & symb_fcts () const
const std::vector< std::string > & symb_subsets () const
number time () const
size_t time_point () const
virtual int type () const
virtual bool use_hanging () const
virtual ~IElemDiscBase ()
Public Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
virtual void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_err_est_elem_loop ()
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
virtual void fsh_err_est_elem_loop ()
IElemEstimatorFuncs ()
virtual void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemEstimatorFuncs ()
Private Member Functions
template<typename TElem >
void prepare_element_loop (ReferenceObjectID roid, int si)
template<typename TElem >
void ass_JA_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const position_type vCornerCoords[])
transfer the local stiffness matrix to the global discretization
template<typename TElem >
void ass_rhs_elem (LocalVector &d, GridObject *elem, const position_type vCornerCoords[])
template<typename TElem >
void prepare_element (const LocalVector &u, GridObject *elem, ReferenceObjectID roid, const position_type vCornerCoords[])
template<typename TElem >
void finish_element_loop ()
template<typename TElem >
void ass_JM_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const position_type vCornerCoords[])
template<typename TElem >
void ass_dA_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const position_type vCornerCoords[])
template<typename TElem >
void ass_dM_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const position_type vCornerCoords[])
void register_all_loc_discr_funcs ()
template<typename TElem >
void register_loc_discr_func ()
Private Attributes
SubsetGroup m_cutSsGrp
group of the surfaces at the cut
bool m_in_pos_subset
whether we assemble in the subset specifying the positive direction
NedelecLoopCurrent & m_master
the master object of the projection
SubsetGroup m_posSsGrp
group of the positive direction subsets
Static Private Attributes
static const size_t _C_ = 0
a name for the component in the grid functions
static const size_t maxCorners = domain_traits<WDim>::MaxNumVerticesOfElem
maximum number of corners of an element
Additional Inherited Members
Public Types inherited from ug::IElemDisc< TDomain >
typedef IElemAssembleFuncs< IElemDisc< TDomain >, TDomain > assemble_base_type
typedef IElemError< TDomain > base_type
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Public Types inherited from ug::IElemError< class >
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from ug::IElemDiscBase< class >
typedef TDomain domain_type
typedef TDomain::position_type position_type
Public Types inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Static Public Attributes inherited from ug::IElemDisc< TDomain >
static const int dim
Static Public Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Static Public Attributes inherited from ug::IElemError< class >
static const int dim
Static Public Attributes inherited from ug::IElemDiscBase< class >
static const int dim
Static Public Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Protected Member Functions inherited from ug::IElemDisc< TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void set_default_add_fct ()
Protected Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_add_def_A_elem_fct (ReferenceObjectID id)
void remove_add_def_A_expl_elem_fct (ReferenceObjectID id)
void remove_add_def_M_elem_fct (ReferenceObjectID id)
void remove_add_jac_A_elem_fct (ReferenceObjectID id)
void remove_add_jac_M_elem_fct (ReferenceObjectID id)
void remove_add_rhs_elem_fct (ReferenceObjectID id)
void remove_fsh_elem_loop_fct (ReferenceObjectID id)
void remove_fsh_timestep_elem_fct (ReferenceObjectID id)
void remove_fsh_timestep_fct (size_t algebra_id)
void remove_prep_elem_fct (ReferenceObjectID id)
void remove_prep_elem_loop_fct (ReferenceObjectID id)
void remove_prep_timestep_elem_fct (ReferenceObjectID id)
void remove_prep_timestep_fct (size_t algebra_id)
void set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_fct (size_t algebra_id, TAssFunc func)
void set_prep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_fct (size_t algebra_id, TAssFunc func)
Protected Member Functions inherited from ug::IElemError< class >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
Protected Member Functions inherited from ug::IElemDiscBase< class >
virtual void approximation_space_changed ()
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
void update_function_index_mapping ()
Protected Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
Protected Attributes inherited from ug::IElemDisc< TDomain >
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > m_spElemModifier
Protected Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
Protected Attributes inherited from ug::IElemDiscBase< class >
bool m_bStationaryForced
FunctionGroup m_fctGrp
FunctionIndexMapping m_fctIndexMap
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
ConstSmartPtr< FunctionPattern > m_spFctPattern
size_t m_timePoint
std::vector< std::string > m_vFct
std::vector< IDataImport< dim > * > m_vIImport
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
std::vector< std::string > m_vSubset
Protected Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
Detailed Description
template<typename TDomain, typename TAlgebra>
class ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss
Class for local assembling of the auxiliary Laplace operator.
This class assembles the local discretization of the Laplace operator in the closure of the subdomain of the source. (Out of this closure, the constraint of class OutOfSource is used.)
Constructor & Destructor Documentation
AuxLaplaceLocAss()
template<typename TDomain , typename TAlgebra > ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::AuxLaplaceLocAss (NedelecLoopCurrent & master)
constructor
Class constructor that gets the master NedelecLoopCurrent object and extracts the data necessary for the base class:
Parameters
[in] master the master object
References ug::SubsetGroup::empty(), ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::m_cutSsGrp, ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::m_posSsGrp, ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::register_all_loc_discr_funcs(), and UG_THROW.
Member Function Documentation
ass_dA_elem()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::ass_dA_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const position_type vCornerCoords[]) inline private
assembling functions
References UG_THROW.
ass_dM_elem()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::ass_dM_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const position_type vCornerCoords[]) inline private
assembling functions
References UG_THROW.
ass_JA_elem()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::ass_JA_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const position_type vCornerCoords[]) private
transfer the local stiffness matrix to the global discretization
Parameters
[in] J the matrix to update
[in] u the local solution (not used here)
[in] elem element to prepare
[in] vCornerCoords coordinates of the corners of the element
References ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::LocLaplaceA< TElem >::stiffness().
ass_JM_elem()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::ass_JM_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const position_type vCornerCoords[]) inline private
assembling functions
References UG_THROW.
ass_rhs_elem()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::ass_rhs_elem (LocalVector & d, GridObject * elem, const position_type vCornerCoords[]) private
assembling functions
Parameters
[in] d the right-hand side to assemble
[in] elem element to prepare
[in] vCornerCoords coordinates of the corners of the element
References ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::LocLaplaceA< TElem >::stiffness().
finish_element_loop()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::finish_element_loop () inline private
assembling functions
prepare_element()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::prepare_element (const LocalVector & u, GridObject * elem, ReferenceObjectID roid, const position_type vCornerCoords[]) inline private
assembling functions
prepare_element_loop()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::prepare_element_loop (ReferenceObjectID roid, int si) private
assembling functions
References ug::SubsetGroup::contains(), and ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::m_posSsGrp.
prepare_setting()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::prepare_setting (const std::vector< LFEID > & vLfeID, bool bNonRegular) virtual
switches between non-regular and regular grids
Implements ug::IElemDiscBase< class >.
References ug::LFEID::LAGRANGE, type(), and UG_THROW.
register_all_loc_discr_funcs()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::register_all_loc_discr_funcs private
registration of the assembling functions
Referenced by ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::AuxLaplaceLocAss().
register_loc_discr_func()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::register_loc_discr_func private
registration of the assembling functions
Referenced by ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::RegisterLocalDiscr::operator()().
Member Data Documentation
_C_
template<typename TDomain , typename TAlgebra > const size_t ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::_C_ = 0 static private
a name for the component in the grid functions
m_cutSsGrp
template<typename TDomain , typename TAlgebra > SubsetGroup ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::m_cutSsGrp private
group of the surfaces at the cut
Referenced by ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::AuxLaplaceLocAss().
m_in_pos_subset
template<typename TDomain , typename TAlgebra > bool ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::m_in_pos_subset private
whether we assemble in the subset specifying the positive direction
m_master
template<typename TDomain , typename TAlgebra > NedelecLoopCurrent& ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::m_master private
the master object of the projection
m_posSsGrp
template<typename TDomain , typename TAlgebra > SubsetGroup ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::m_posSsGrp private
group of the positive direction subsets
Referenced by ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::AuxLaplaceLocAss().
maxCorners
template<typename TDomain , typename TAlgebra > const size_t ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::maxCorners = domain_traits<WDim>::MaxNumVerticesOfElem static private
maximum number of corners of an element
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_source.h
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_source_impl.h