Plugins: ug::DocuGen::UGDocuClassDescription Class Reference
ug::DocuGen::UGDocuClassDescription Class Reference
#include <ug_docu_class_description.h>
Public Member Functions
const std::string group_str () const
const std::string name () const
UGDocuClassDescription (const bridge::ClassGroupDesc *group)
UGDocuClassDescription (const bridge::IExportedClass *klass)
Public Attributes
const bridge::IExportedClass * mp_class
const bridge::ClassGroupDesc * mp_group
std::string tag
Constructor & Destructor Documentation
UGDocuClassDescription() [1/2]
ug::DocuGen::UGDocuClassDescription::UGDocuClassDescription (const bridge::IExportedClass * klass) inline
UGDocuClassDescription() [2/2]
ug::DocuGen::UGDocuClassDescription::UGDocuClassDescription (const bridge::ClassGroupDesc * group) inline
Member Function Documentation
group_str()
const std::string ug::DocuGen::UGDocuClassDescription::group_str () const inline
References ug::bridge::ClassGroupDesc::get_class(), ug::bridge::ClassGroupDesc::get_default_class(), ug::bridge::IExportedClass::group(), mp_class, mp_group, and ug::bridge::ClassGroupDesc::num_classes().
Referenced by ug::DocuGen::GroupNameSortFunction(), ug::DocuGen::WriteClassIndex(), and ug::DocuGen::WriteGroups().
name()
const std::string ug::DocuGen::UGDocuClassDescription::name () const inline
References mp_class, mp_group, ug::bridge::ClassGroupDesc::name(), and ug::bridge::IExportedClass::name().
Referenced by ug::DocuGen::GroupNameSortFunction(), ug::DocuGen::NameSortFunction(), ug::DocuGen::WriteClassIndex(), and ug::DocuGen::WriteGroups().
Member Data Documentation
mp_class
const bridge::IExportedClass* ug::DocuGen::UGDocuClassDescription::mp_class
Referenced by group_str(), name(), ug::DocuGen::WriteClassCompleter(), ug::DocuGen::WriteClassHTML(), ug::DocuGen::WriteClassIndex(), and ug::DocuGen::WriteGroups().
mp_group
const bridge::ClassGroupDesc* ug::DocuGen::UGDocuClassDescription::mp_group
Referenced by ug::DocuGen::GetClassGroup(), ug::DocuGen::GetClassGroupStd(), ug::DocuGen::GetGroups(), group_str(), name(), ug::DocuGen::WriteClassCompleter(), ug::DocuGen::WriteClassHTML(), ug::DocuGen::WriteClassIndex(), and ug::DocuGen::WriteGroups().
tag
std::string ug::DocuGen::UGDocuClassDescription::tag
Referenced by ug::DocuGen::GetGroups(), ug::DocuGen::WriteClassCompleter(), and ug::DocuGen::WriteClassHTML().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/DocuGen/src/ug_docu_class_description.h