Plugins: ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction > Class Template Reference
ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction > Class Template Reference
#include <pressure_separation.h>
Public Member Functions
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
template<int refDim>
void evaluate (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
virtual void operator() (MathVector< dim > &value, const MathVector< dim > &globIP, number time, int si) const
virtual void operator() (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
virtual bool requires_grid_fct () const
returns if grid function is needed for evaluation
SeparatedPressureSourceInter (SmartPtr< ApproximationSpace< domain_type > > approxSpace, SmartPtr< TGridFunction > spGridFct)
constructor
void set_source (SmartPtr< CplUserData< MathVector< dim >, dim > > data)
void set_source (number f_x)
void set_source (number f_x, number f_y)
void set_source (number f_x, number f_y, number f_z)
void update ()
virtual ~SeparatedPressureSourceInter ()
Public Member Functions inherited from ug::StdUserData< SeparatedPressureSourceInter< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >
virtual TRet operator() (MathVector< TGridFunction::dim > &value, const MathVector< TGridFunction::dim > &globIP, number time, int si) const =0
virtual void operator() (MathVector< TGridFunction::dim > vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, TGridFunction::dim > *vJT=NULL) const
virtual void operator() (MathVector< TGridFunction::dim > vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, TGridFunction::dim > *vJT=NULL) const
virtual void operator() (MathVector< TGridFunction::dim > vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, TGridFunction::dim > *vJT=NULL) const
virtual void operator() (MathVector< TGridFunction::dim > vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, TGridFunction::dim > *vJT=NULL) const
virtual void operator() (MathVector< TGridFunction::dim > vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, TGridFunction::dim > *vJT=NULL) const
virtual void operator() (MathVector< TGridFunction::dim > vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, TGridFunction::dim > *vJT=NULL) const
virtual void operator() (MathVector< TGridFunction::dim > vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, const size_t nip) const =0
Public Member Functions inherited from ug::INewtonUpdate
virtual ~INewtonUpdate ()
Private Types
typedef Grid::AttachmentAccessor< elem_type, ANumber > aElementNumber
typedef TGridFunction::algebra_type algebra_type
algebra type
typedef PeriodicAttachmentAccessor< Vertex, ANumber > aVertexNumber
MathVector<dim> attachment.
typedef TGridFunction::domain_type domain_type
domain type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef TGridFunction::template dim_traits< dim >::const_iterator ElemIterator
element iterator
typedef domain_type::grid_type grid_type
grid type
typedef domain_type::position_accessor_type position_accessor_type
position accessor type
typedef TGridFunction::template traits< Vertex >::const_iterator VertexIterator
vertex iterator
Private Attributes
ANumber m_aP
ANumber m_aPOld
ANumber m_aVol
grid_type * m_grid
SmartPtr< CplUserData< MathVector< dim >, dim > > m_imSource
Data import for source.
aVertexNumber m_p
aElementNumber m_pOld
SmartPtr< ApproximationSpace< domain_type > > m_spApproxSpace
SmartPtr< TGridFunction > m_u
aVertexNumber m_vol
Static Private Attributes
static const size_t _P_ = dim
static const int dim = domain_type::dim
world dimension
static const size_t max_number_of_ips = 20
Additional Inherited Members
Protected Member Functions inherited from ug::StdUserData< SeparatedPressureSourceInter< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >
SeparatedPressureSourceInter< TGridFunction > & getImpl ()
const SeparatedPressureSourceInter< TGridFunction > & getImpl () const
Member Typedef Documentation
aElementNumber
template<typename TGridFunction > typedef Grid::AttachmentAccessor<elem_type,ANumber > ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::aElementNumber private
algebra_type
template<typename TGridFunction > typedef TGridFunction::algebra_type ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::algebra_type private
algebra type
aVertexNumber
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<Vertex,ANumber > ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::aVertexNumber private
MathVector<dim> attachment.
attachment accessor
domain_type
template<typename TGridFunction > typedef TGridFunction::domain_type ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::domain_type private
domain type
elem_type
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::grid_base_object ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::elem_type private
element type
ElemIterator
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::const_iterator ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::ElemIterator private
element iterator
grid_type
template<typename TGridFunction > typedef domain_type::grid_type ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::grid_type private
grid type
position_accessor_type
template<typename TGridFunction > typedef domain_type::position_accessor_type ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::position_accessor_type private
position accessor type
VertexIterator
template<typename TGridFunction > typedef TGridFunction::template traits<Vertex>::const_iterator ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::VertexIterator private
vertex iterator
Constructor & Destructor Documentation
SeparatedPressureSourceInter()
template<typename TGridFunction > ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::SeparatedPressureSourceInter (SmartPtr< ApproximationSpace< domain_type > > approxSpace, SmartPtr< TGridFunction > spGridFct) inline
constructor
References ug::PeriodicAttachmentAccessor< class, class >::access(), SmartPtr< TGridFunction >::get(), grid(), ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_aP, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_aPOld, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_aVol, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source(), ug::SetAttachmentValues(), and ug::NavierStokes::SeparatedPressureSource< TGridFunction >::update().
~SeparatedPressureSourceInter()
template<typename TGridFunction > virtual ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::~SeparatedPressureSourceInter () inline virtual
Member Function Documentation
compute()
template<typename TGridFunction > virtual void ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::compute (LocalVector * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) inline virtual
References s.
continuous()
template<typename TGridFunction > virtual bool ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::continuous () const inline virtual
returns if provided data is continuous over geometric object boundaries
evaluate()
template<typename TGridFunction > template<int refDim> void ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::evaluate (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< refDim, dim > * vJT = NULL) const inline
References ug::NavierStokes::SeparatedPressureSource< TGridFunction >::dim, ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::from(), SmartPtr< TGridFunction >::get(), ug::LFEID::LAGRANGE, ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::local_ip(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::normal(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scv(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scvf(), ug::GridObject::reference_object_id(), ug::DimCRFVGeometry< TDim, TWorldDim >::scv(), ug::DimCRFVGeometry< TDim, TWorldDim >::scvf(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::to(), UG_ASSERT, and ug::DimCRFVGeometry< TDim, TWorldDim >::update().
operator()() [1/2]
template<typename TGridFunction > virtual void ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::operator() (MathVector< dim > & value, const MathVector< dim > & globIP, number time, int si) const inline virtual
References UG_THROW.
operator()() [2/2]
template<typename TGridFunction > virtual void ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::operator() (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const inline virtual
References UG_THROW.
requires_grid_fct()
template<typename TGridFunction > virtual bool ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::requires_grid_fct () const inline virtual
returns if grid function is needed for evaluation
set_source() [1/4]
template<typename TGridFunction > void ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::set_source (SmartPtr< CplUserData< MathVector< dim >, dim > > data) inline
set_source() [2/4]
template<typename TGridFunction > void ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::set_source (number f_x) inline
References ug::NavierStokes::SeparatedPressureSource< TGridFunction >::dim, and ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source().
set_source() [3/4]
template<typename TGridFunction > void ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::set_source (number f_x, number f_y) inline
References ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source(), and UG_THROW.
set_source() [4/4]
template<typename TGridFunction > void ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::set_source (number f_x, number f_y, number f_z) inline
References ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source(), and UG_THROW.
update()
template<typename TGridFunction > void ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::update () inline virtual
Implements ug::INewtonUpdate.
References ug::DoFRef(), SmartPtr< TGridFunction >::get(), ug::PeriodicBoundaryManager::is_slave(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::SetAttachmentValues(), and ug::DimFV1Geometry< TDim, TWorldDim >::update().
Member Data Documentation
_P_
template<typename TGridFunction > const size_t ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::_P_ = dim static private
dim
template<typename TGridFunction > const int ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::dim = domain_type::dim static private
world dimension
m_aP
template<typename TGridFunction > ANumber ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::m_aP private
m_aPOld
template<typename TGridFunction > ANumber ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::m_aPOld private
m_aVol
template<typename TGridFunction > ANumber ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::m_aVol private
m_grid
template<typename TGridFunction > grid_type* ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::m_grid private
m_imSource
template<typename TGridFunction > SmartPtr<CplUserData<MathVector<dim>,dim> > ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::m_imSource private
Data import for source.
m_p
template<typename TGridFunction > aVertexNumber ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::m_p private
m_pOld
template<typename TGridFunction > aElementNumber ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::m_pOld private
m_spApproxSpace
template<typename TGridFunction > SmartPtr<ApproximationSpace<domain_type> > ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::m_spApproxSpace private
m_u
template<typename TGridFunction > SmartPtr<TGridFunction> ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::m_u private
m_vol
template<typename TGridFunction > aVertexNumber ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::m_vol private
max_number_of_ips
template<typename TGridFunction > const size_t ug::NavierStokes::SeparatedPressureSourceInter< TGridFunction >::max_number_of_ips = 20 static private
The documentation for this class was generated from the following file:
/home/sreiter/ug4-docugen/plugins/NavierStokes/incompressible/fvcr/pressure_separation.h