Plugins: ug::NavierStokes::INavierStokesFV1Stabilization< dim > Class Template Reference
ug::NavierStokes::INavierStokesFV1Stabilization< dim > Class Template Reference
#include <stabilization.h>
Public Member Functions
INavierStokesFV1Stabilization ()
constructor
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shapes (corners)
template<typename TFVGeom , typename TAssFunc >
void register_update_func (TAssFunc func)
register a update function for a Geometry
template<typename TFVGeom >
void set_geometry_type ()
set the FV1 Geometry type to use for next updates
void set_upwind (SmartPtr< INavierStokesUpwind< dim > > spUpwind)
sets the upwind method
number stab_shape_p (size_t scvf, size_t compOut, size_t sh) const
computed stab shape for pressure.
number stab_shape_vel (size_t scvf, size_t compOut, size_t compIn, size_t sh) const
const MathVector< dim > & stab_vel (size_t scvf) const
stabilized velocity
void update (const FVGeometryBase *geo, const LocalVector &vCornerValue, const MathVector< dim > vStdVel[], const bool bStokes, const DataImport< number, dim > &kinVisco, const DataImport< number, dim > &density, const DataImport< MathVector< dim >, dim > *pSource, const LocalVector *pvCornerValueOldTime, number dt)
compute values for new geometry and corner velocities
const ConstSmartPtr< INavierStokesUpwind< dim > > & upwind () const
returns the upwind
bool upwind_valid () const
returns if the upwind pointer is valid
bool vel_comp_connected () const
returns if stab velocity comp depends on other vel components
Static Public Attributes
static const size_t maxNumSCV = traits::maxNumSCV
number of SubControlVolumes
static const size_t maxNumSCVF = traits::maxNumSCVF
max number of SubControlVolumeFaces
static const size_t maxNumSH = traits::maxNSH
max number of shape functions
Protected Types
typedef fv1_dim_traits< dim, dim > traits
used traits
typedef void(this_type::* UpdateFunc) (const FVGeometryBase *geo, const LocalVector &vCornerValue, const MathVector< dim > vStdVel[], const bool bStokes, const DataImport< number, dim > &kinVisco, const DataImport< number, dim > &density, const DataImport< MathVector< dim >, dim > *pSource, const LocalVector *pvCornerValueOldTime, number dt)
type of update function
Protected Member Functions
template<typename TFVGeom >
void compute_downwind (const TFVGeom &geo, const MathVector< dim > vStdVel[])
computes the downwind shapes
template<typename TFVGeom >
void compute_upwind (const TFVGeom &geo, const MathVector< dim > vStdVel[])
computes the upwind shapes
void set_vel_comp_connected (bool bVelCompConnected)
sets the vel comp connected flag
number & stab_shape_p (size_t scvf, size_t compOut, size_t sh)
computed stab shape for pressure.
number & stab_shape_vel (size_t scvf, size_t compOut, size_t compIn, size_t sh)
MathVector< dim > & stab_vel (size_t scvf)
stabilized velocity
Protected Attributes
std::vector< UpdateFunc > m_vUpdateFunc
Vector holding all update functions.
Private Types
typedef INavierStokesFV1Stabilization< dim > this_type
abbreviation for own type
Private Attributes
bool m_bVelCompConnected
flag if velocity components are interconnected
int m_id
id of current geometry type
size_t m_numScvf
number of current scvf
size_t m_numSh
number of current shape functions (usually in corners)
ConstSmartPtr< INavierStokesUpwind< dim > > m_spConstUpwind
Upwind object (if set), the same as m_spUpwind, but as a const.
SmartPtr< INavierStokesUpwind< dim > > m_spUpwind
Upwind object (if set)
MathVector< dim > m_vStabVel [maxNumSCVF]
values of stabilized velocity at ip
number m_vvvStabShapePressure [maxNumSCVF][dim][maxNumSH]
stab shapes w.r.t pressure
number m_vvvvStabShapeVel [maxNumSCVF][dim][dim][maxNumSH]
stab shapes w.r.t vel
Detailed Description
template<int dim>
class ug::NavierStokes::INavierStokesFV1Stabilization< dim >
Class for a general stabilization method for FV1-discretizations of the NS equations.
A general stabilization is a method that expresses the additional DoFs of the velocity (for the continuity equation) placed in the integration points in terms of the corner values of the velocity and the pressure. Thus, the the stabilization is a special interpolation of the velocity (involving the pressure) from the corners of the primary grid elements into the integration points of the secondary grid.
Template Parameters
dim dimension of the world
Member Typedef Documentation
this_type
template<int dim> typedef INavierStokesFV1Stabilization<dim> ug::NavierStokes::INavierStokesFV1Stabilization< dim >::this_type private
abbreviation for own type
traits
template<int dim> typedef fv1_dim_traits<dim, dim> ug::NavierStokes::INavierStokesFV1Stabilization< dim >::traits protected
used traits
UpdateFunc
template<int dim> typedef void(this_type::* ug::NavierStokes::INavierStokesFV1Stabilization< dim >::UpdateFunc) (const FVGeometryBase *geo, const LocalVector &vCornerValue, const MathVector< dim > vStdVel[], const bool bStokes, const DataImport< number, dim > &kinVisco, const DataImport< number, dim > &density, const DataImport< MathVector< dim >, dim > *pSource, const LocalVector *pvCornerValueOldTime, number dt) protected
type of update function
Constructor & Destructor Documentation
INavierStokesFV1Stabilization()
template<int dim> ug::NavierStokes::INavierStokesFV1Stabilization< dim >::INavierStokesFV1Stabilization () inline
constructor
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vUpdateFunc.
Member Function Documentation
compute_downwind()
template<int dim> template<typename TFVGeom > void ug::NavierStokes::INavierStokesFV1Stabilization< dim >::compute_downwind (const TFVGeom & geo, const MathVector< dim > vStdVel[]) inline protected
computes the downwind shapes
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_spUpwind, and UG_NSSTAB_ASSERT.
compute_upwind()
template<int dim> template<typename TFVGeom > void ug::NavierStokes::INavierStokesFV1Stabilization< dim >::compute_upwind (const TFVGeom & geo, const MathVector< dim > vStdVel[]) inline protected
computes the upwind shapes
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_spUpwind, and UG_NSSTAB_ASSERT.
num_ip()
template<int dim> size_t ug::NavierStokes::INavierStokesFV1Stabilization< dim >::num_ip () const inline
number of integration points
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numScvf.
Referenced by ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::diff_length_sq_inv().
num_sh()
template<int dim> size_t ug::NavierStokes::INavierStokesFV1Stabilization< dim >::num_sh () const inline
number of shapes (corners)
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numSh.
register_update_func()
template<int dim> template<typename TFVGeom , typename TAssFunc > void ug::NavierStokes::INavierStokesFV1Stabilization< dim >::register_update_func (TAssFunc func)
register a update function for a Geometry
set_geometry_type()
template<int dim> template<typename TFVGeom > void ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_geometry_type () inline
set the FV1 Geometry type to use for next updates
References ug::GeomProvider< class >::get(), ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_id, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numScvf, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numSh, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_spUpwind, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vUpdateFunc, and UG_THROW.
set_upwind()
template<int dim> void ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_upwind (SmartPtr< INavierStokesUpwind< dim > > spUpwind) inline
sets the upwind method
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_spConstUpwind, and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_spUpwind.
set_vel_comp_connected()
template<int dim> void ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_vel_comp_connected (bool bVelCompConnected) inline protected
sets the vel comp connected flag
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_bVelCompConnected.
Referenced by ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::NavierStokesFIELDSStabilization().
stab_shape_p() [1/2]
template<int dim> number& ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_shape_p (size_t scvf, size_t compOut, size_t sh) inline protected
computed stab shape for pressure.
References dim, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numScvf, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numSh, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vvvStabShapePressure, and UG_NSSTAB_ASSERT.
stab_shape_p() [2/2]
template<int dim> number ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_shape_p (size_t scvf, size_t compOut, size_t sh) const inline
computed stab shape for pressure.
References dim, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numScvf, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numSh, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vvvStabShapePressure, and UG_NSSTAB_ASSERT.
Referenced by ug::NavierStokes::NavierStokesFV1< TDomain >::add_jac_A_elem().
stab_shape_vel() [1/2]
template<int dim> number& ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_shape_vel (size_t scvf, size_t compOut, size_t compIn, size_t sh) inline protected
computed stab shape for velocity. This is: The stab_vel derivative w.r.t velocity unknowns in the corner for each component
References dim, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numScvf, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numSh, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vvvvStabShapeVel, and UG_NSSTAB_ASSERT.
stab_shape_vel() [2/2]
template<int dim> number ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_shape_vel (size_t scvf, size_t compOut, size_t compIn, size_t sh) const inline
computed stab shape for velocity. This is: The stab_vel derivative w.r.t velocity unknowns in the corner for each component
References dim, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numScvf, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numSh, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vvvvStabShapeVel, and UG_NSSTAB_ASSERT.
Referenced by ug::NavierStokes::NavierStokesFV1< TDomain >::add_jac_A_elem().
stab_vel() [1/2]
template<int dim> MathVector<dim>& ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_vel (size_t scvf) inline protected
stabilized velocity
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numScvf, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vStabVel, and UG_NSSTAB_ASSERT.
stab_vel() [2/2]
template<int dim> const MathVector<dim>& ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_vel (size_t scvf) const inline
stabilized velocity
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numScvf, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vStabVel, and UG_NSSTAB_ASSERT.
Referenced by ug::NavierStokes::NavierStokesFV1< TDomain >::add_def_A_elem(), and ug::NavierStokes::NavierStokesFV1< TDomain >::add_jac_A_elem().
update()
template<int dim> void ug::NavierStokes::INavierStokesFV1Stabilization< dim >::update (const FVGeometryBase * geo, const LocalVector & vCornerValue, const MathVector< dim > vStdVel[], const bool bStokes, const DataImport< number, dim > & kinVisco, const DataImport< number, dim > & density, const DataImport< MathVector< dim >, dim > * pSource, const LocalVector * pvCornerValueOldTime, number dt) inline
compute values for new geometry and corner velocities
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_id, and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vUpdateFunc.
upwind()
template<int dim> const ConstSmartPtr<INavierStokesUpwind<dim> >& ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind () const inline
returns the upwind
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_spConstUpwind.
Referenced by ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::downwind_conv_length(), ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::downwind_shape_ip(), ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::downwind_shape_sh(), ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::non_zero_shape_ip(), ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::upwind_conv_length(), ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::upwind_shape_ip(), and ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::upwind_shape_sh().
upwind_valid()
template<int dim> bool ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind_valid () const inline
returns if the upwind pointer is valid
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_spConstUpwind.
Referenced by ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::downwind_conv_length(), ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::downwind_shape_ip(), ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::downwind_shape_sh(), ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::non_zero_shape_ip(), ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::upwind_conv_length(), ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::upwind_shape_ip(), and ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::upwind_shape_sh().
vel_comp_connected()
template<int dim> bool ug::NavierStokes::INavierStokesFV1Stabilization< dim >::vel_comp_connected () const inline
returns if stab velocity comp depends on other vel components
References ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_bVelCompConnected.
Referenced by ug::NavierStokes::NavierStokesFV1< TDomain >::add_jac_A_elem().
Member Data Documentation
m_bVelCompConnected
template<int dim> bool ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_bVelCompConnected private
flag if velocity components are interconnected
Referenced by ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_vel_comp_connected(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::vel_comp_connected().
m_id
template<int dim> int ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_id private
id of current geometry type
Referenced by ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_geometry_type(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::update().
m_numScvf
template<int dim> size_t ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numScvf private
number of current scvf
Referenced by ug::NavierStokes::INavierStokesFV1Stabilization< dim >::num_ip(), ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_geometry_type(), ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_shape_p(), ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_shape_vel(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_vel().
m_numSh
template<int dim> size_t ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_numSh private
number of current shape functions (usually in corners)
Referenced by ug::NavierStokes::INavierStokesFV1Stabilization< dim >::num_sh(), ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_geometry_type(), ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_shape_p(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_shape_vel().
m_spConstUpwind
template<int dim> ConstSmartPtr<INavierStokesUpwind<dim> > ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_spConstUpwind private
Upwind object (if set), the same as m_spUpwind, but as a const.
Referenced by ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_upwind(), ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind_valid().
m_spUpwind
template<int dim> SmartPtr<INavierStokesUpwind<dim> > ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_spUpwind private
Upwind object (if set)
Referenced by ug::NavierStokes::INavierStokesFV1Stabilization< dim >::compute_downwind(), ug::NavierStokes::INavierStokesFV1Stabilization< dim >::compute_upwind(), ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_geometry_type(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_upwind().
m_vStabVel
template<int dim> MathVector<dim> ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vStabVel[maxNumSCVF] private
values of stabilized velocity at ip
Referenced by ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_vel().
m_vUpdateFunc
template<int dim> std::vector<UpdateFunc> ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vUpdateFunc protected
Vector holding all update functions.
Referenced by ug::NavierStokes::INavierStokesFV1Stabilization< dim >::INavierStokesFV1Stabilization(), ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_geometry_type(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::update().
m_vvvStabShapePressure
template<int dim> number ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vvvStabShapePressure[maxNumSCVF][dim][maxNumSH] private
stab shapes w.r.t pressure
Referenced by ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_shape_p().
m_vvvvStabShapeVel
template<int dim> number ug::NavierStokes::INavierStokesFV1Stabilization< dim >::m_vvvvStabShapeVel[maxNumSCVF][dim][dim][maxNumSH] private
stab shapes w.r.t vel
Referenced by ug::NavierStokes::INavierStokesFV1Stabilization< dim >::stab_shape_vel().
maxNumSCV
template<int dim> const size_t ug::NavierStokes::INavierStokesFV1Stabilization< dim >::maxNumSCV = traits::maxNumSCV static
number of SubControlVolumes
maxNumSCVF
template<int dim> const size_t ug::NavierStokes::INavierStokesFV1Stabilization< dim >::maxNumSCVF = traits::maxNumSCVF static
max number of SubControlVolumeFaces
maxNumSH
template<int dim> const size_t ug::NavierStokes::INavierStokesFV1Stabilization< dim >::maxNumSH = traits::maxNSH static
max number of shape functions
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/stabilization.h
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/stabilization.cpp