Plugins: ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl > Class Template Reference
ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl > Class Template Reference
#include <upwind_interface.h>
Public Types
typedef INavierStokesUpwind< dim > base_type
Base class.
Public Member Functions
NavierStokesUpwindRegister ()
constructor
Protected Member Functions
TImpl & getImpl ()
access to implementation
Static Protected Attributes
static const size_t maxNumSCVF = base_type::maxNumSCVF
static const size_t maxNumSH = base_type::maxNumSH
Private Member Functions
template<typename TElem >
void register_func ()
void register_func (Int2Type< 1 >)
void register_func (Int2Type< 2 >)
void register_func (Int2Type< 3 >)
Member Typedef Documentation
base_type
template<template< class Elem, int WorldDim > class TFVGeom, int dim, typename TImpl > typedef INavierStokesUpwind<dim> ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::base_type
Base class.
Constructor & Destructor Documentation
NavierStokesUpwindRegister()
template<template< class Elem, int WorldDim > class TFVGeom, int dim, typename TImpl > ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::NavierStokesUpwindRegister () inline
constructor
References ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::register_func().
Member Function Documentation
getImpl()
template<template< class Elem, int WorldDim > class TFVGeom, int dim, typename TImpl > TImpl& ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::getImpl () inline protected
access to implementation
Referenced by ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::register_func().
register_func() [1/4]
template<template< class Elem, int WorldDim > class TFVGeom, int dim, typename TImpl > template<typename TElem > void ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::register_func () inline private
References ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::getImpl(), ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::maxNumSCVF, and ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::maxNumSH.
Referenced by ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::NavierStokesUpwindRegister().
register_func() [2/4]
template<template< class Elem, int WorldDim > class TFVGeom, int dim, typename TImpl > void ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::register_func (Int2Type< 1 >) inline private
register_func() [3/4]
template<template< class Elem, int WorldDim > class TFVGeom, int dim, typename TImpl > void ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::register_func (Int2Type< 2 >) inline private
register_func() [4/4]
template<template< class Elem, int WorldDim > class TFVGeom, int dim, typename TImpl > void ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::register_func (Int2Type< 3 >) inline private
Member Data Documentation
maxNumSCVF
template<template< class Elem, int WorldDim > class TFVGeom, int dim, typename TImpl > const size_t ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::maxNumSCVF = base_type::maxNumSCVF static protected
Referenced by ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::register_func().
maxNumSH
template<template< class Elem, int WorldDim > class TFVGeom, int dim, typename TImpl > const size_t ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::maxNumSH = base_type::maxNumSH static protected
Referenced by ug::NavierStokes::NavierStokesUpwindRegister< TFVGeom, dim, TImpl >::register_func().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/upwind_interface.h