Plugins: ug::DeltaSquareIntegrand< TDataIn, TGridFunction > Class Template Reference
ug::DeltaSquareIntegrand< TDataIn, TGridFunction > Class Template Reference
#include <time_extrapolation.h>
Public Types
typedef TDataIn data_type
Public Types inherited from ug::StdIntegrand< number, TGridFunction::dim, DeltaSquareIntegrand< TDataIn, TGridFunction > >
typedef TData data_type
Public Types inherited from ug::IIntegrand< class, TWorldDim >
typedef TData data_type
Public Member Functions
DeltaSquareIntegrand (SmartPtr< UserData< TDataIn, worldDim > > spData, const TGridFunction *pGridFct1, const TGridFunction *pGridFct2, number time)
constructor
DeltaSquareIntegrand (SmartPtr< UserData< TDataIn, worldDim > > spData, number time)
constructor
template<int elemDim>
void evaluate (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP)
template<int elemDim>
void get_values (TDataIn vValue[], ConstSmartPtr< UserData< TDataIn, worldDim > > spData, const TGridFunction &gridFct, const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP)
Public Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, DeltaSquareIntegrand< TDataIn, TGridFunction > >
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 1 > vLocIP[], const MathMatrix< 1, worldDim > vJT[], const size_t numIP)
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 2 > vLocIP[], const MathMatrix< 2, worldDim > vJT[], const size_t numIP)
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)
virtual void values (TData vValue[], const MathVector< worldDim > vGlobIP[], GridObject *pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< 3 > vLocIP[], const MathMatrix< 3, worldDim > vJT[], const size_t numIP)
Public Member Functions inherited from ug::IIntegrand< class, TWorldDim >
virtual void set_subset (int si)
int subset () const
virtual ~IIntegrand ()
Static Public Attributes
static const int worldDim = TGridFunction::dim
Static Public Attributes inherited from ug::StdIntegrand< number, TGridFunction::dim, DeltaSquareIntegrand< TDataIn, TGridFunction > >
static const int worldDim
Static Public Attributes inherited from ug::IIntegrand< class, TWorldDim >
static const int worldDim
Static Private Member Functions
static number product (const MathVector< worldDim > &x, const MathVector< worldDim > &y)
static number product (const number &x, const number &y)
Private Attributes
const TGridFunction * m_pGridFct1
const TGridFunction * m_pGridFct2
SmartPtr< UserData< TDataIn, worldDim > > m_spData
number m_time
Additional Inherited Members
Protected Member Functions inherited from ug::StdIntegrand< number, TGridFunction::dim, DeltaSquareIntegrand< TDataIn, TGridFunction > >
TImpl & getImpl ()
const TImpl & getImpl () const
Protected Attributes inherited from ug::IIntegrand< class, TWorldDim >
int m_si
Detailed Description
template<typename TDataIn, typename TGridFunction>
class ug::DeltaSquareIntegrand< TDataIn, TGridFunction >
For arbitrary $\rho$, this class defines the integrand $|\rho(u_1)- \rho(u_2)|^2$. If the grid function $u_2$ is not provided, the class returns $|\rho(u_1)|^2$
Member Typedef Documentation
data_type
template<typename TDataIn , typename TGridFunction > typedef TDataIn ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::data_type
Constructor & Destructor Documentation
DeltaSquareIntegrand() [1/2]
template<typename TDataIn , typename TGridFunction > ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::DeltaSquareIntegrand (SmartPtr< UserData< TDataIn, worldDim > > spData, const TGridFunction * pGridFct1, const TGridFunction * pGridFct2, number time) inline
constructor
References ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::m_spData.
DeltaSquareIntegrand() [2/2]
template<typename TDataIn , typename TGridFunction > ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::DeltaSquareIntegrand (SmartPtr< UserData< TDataIn, worldDim > > spData, number time) inline
constructor
References ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::m_spData, and UG_THROW.
Member Function Documentation
evaluate()
template<typename TDataIn , typename TGridFunction > template<int elemDim> void ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::evaluate (number vValue[], const MathVector< worldDim > vGlobIP[], GridObject * pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP) inline
References ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::m_pGridFct1, ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::m_pGridFct2, ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::m_spData, and ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::product().
get_values()
template<typename TDataIn , typename TGridFunction > template<int elemDim> void ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::get_values (TDataIn vValue[], ConstSmartPtr< UserData< TDataIn, worldDim > > spData, const TGridFunction & gridFct, const MathVector< worldDim > vGlobIP[], GridObject * pElem, const MathVector< worldDim > vCornerCoords[], const MathVector< elemDim > vLocIP[], const MathMatrix< elemDim, worldDim > vJT[], const size_t numIP) inline
References ug::GetLocalVector(), ug::IIntegrand< class, TWorldDim >::m_si, ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::m_time, ug::LocalVector::resize(), and UG_CATCH_THROW.
product() [1/2]
template<typename TDataIn , typename TGridFunction > static number ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::product (const MathVector< worldDim > & x, const MathVector< worldDim > & y) inline static private
References ug::VecDot().
product() [2/2]
template<typename TDataIn , typename TGridFunction > static number ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::product (const number & x, const number & y) inline static private
Referenced by ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::evaluate().
Member Data Documentation
m_pGridFct1
template<typename TDataIn , typename TGridFunction > const TGridFunction* ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::m_pGridFct1 private
Referenced by ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::evaluate().
m_pGridFct2
template<typename TDataIn , typename TGridFunction > const TGridFunction* ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::m_pGridFct2 private
Referenced by ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::evaluate().
m_spData
template<typename TDataIn , typename TGridFunction > SmartPtr<UserData<TDataIn, worldDim> > ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::m_spData private
Referenced by ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::DeltaSquareIntegrand(), and ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::evaluate().
m_time
template<typename TDataIn , typename TGridFunction > number ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::m_time private
Referenced by ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::get_values().
worldDim
template<typename TDataIn , typename TGridFunction > const int ug::DeltaSquareIntegrand< TDataIn, TGridFunction >::worldDim = TGridFunction::dim static
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Limex/time_disc/time_extrapolation.h