Plugins: ug::TimeStepBounds Class Reference
ug::TimeStepBounds Class Reference
#include <time_integrator.hpp>
Public Member Functions
double get_dt_max ()
double get_dt_min ()
double get_increase_factor ()
double get_reduction_factor ()
void rescale (double alpha)
void set_dt_max (double max)
void set_dt_min (double min)
void set_increase_factor (double inc)
void set_reduction_factor (double dec)
TimeStepBounds ()
Protected Attributes
double m_dtMax
double m_dtMin
double m_incFac
double m_redFac
Constructor & Destructor Documentation
TimeStepBounds()
ug::TimeStepBounds::TimeStepBounds () inline
Member Function Documentation
get_dt_max()
double ug::TimeStepBounds::get_dt_max () inline
References m_dtMax.
Referenced by ug::INonlinearTimeIntegrator< TDomain, TAlgebra >::get_dt_max().
get_dt_min()
double ug::TimeStepBounds::get_dt_min () inline
References m_dtMin.
get_increase_factor()
double ug::TimeStepBounds::get_increase_factor () inline
References m_incFac.
Referenced by ug::INonlinearTimeIntegrator< TDomain, TAlgebra >::get_increase_factor().
get_reduction_factor()
double ug::TimeStepBounds::get_reduction_factor () inline
References m_redFac.
Referenced by ug::INonlinearTimeIntegrator< TDomain, TAlgebra >::get_reduction_factor().
rescale()
void ug::TimeStepBounds::rescale (double alpha) inline
References m_dtMax, and m_dtMin.
set_dt_max()
void ug::TimeStepBounds::set_dt_max (double max) inline
References m_dtMax.
Referenced by ug::INonlinearTimeIntegrator< TDomain, TAlgebra >::set_dt_max().
set_dt_min()
void ug::TimeStepBounds::set_dt_min (double min) inline
References m_dtMin.
Referenced by ug::INonlinearTimeIntegrator< TDomain, TAlgebra >::set_dt_min().
set_increase_factor()
void ug::TimeStepBounds::set_increase_factor (double inc) inline
References m_incFac.
Referenced by ug::INonlinearTimeIntegrator< TDomain, TAlgebra >::set_increase_factor().
set_reduction_factor()
void ug::TimeStepBounds::set_reduction_factor (double dec) inline
References m_redFac.
Referenced by ug::INonlinearTimeIntegrator< TDomain, TAlgebra >::set_reduction_factor().
Member Data Documentation
m_dtMax
double ug::TimeStepBounds::m_dtMax protected
Referenced by get_dt_max(), rescale(), and set_dt_max().
m_dtMin
double ug::TimeStepBounds::m_dtMin protected
Referenced by get_dt_min(), rescale(), and set_dt_min().
m_incFac
double ug::TimeStepBounds::m_incFac protected
Referenced by get_increase_factor(), and set_increase_factor().
m_redFac
double ug::TimeStepBounds::m_redFac protected
Referenced by get_reduction_factor(), and set_reduction_factor().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Limex/time_disc/time_integrator.hpp