Plugins: ug::AitkenNevilleTimex< TVector > Class Template Reference
ug::AitkenNevilleTimex< TVector > Class Template Reference
#include <time_extrapolation.h>
Public Types
typedef TVector vector_type
vector type of solutions
Public Member Functions
AitkenNevilleTimex (std::vector< size_t > nsteps)
AitkenNevilleTimex (std::vector< size_t > nsteps, SmartPtr< ISubDiagErrorEst< vector_type > > error)
void apply ()
apply for all stages
void apply (size_t nstages, bool with_error=true)
best error estimate
number get_error_estimate (int k) const
error estimate on stage k
const std::vector< number > & get_error_estimates () const
number get_global_stepsize ()
SmartPtr< vector_type > get_solution (size_t i)
get solution (on stage i)
void set_error_estimate (SmartPtr< ISubDiagErrorEst< vector_type > > subdiag)
set error estimator
void set_global_stepsize (number H)
void set_solution (SmartPtr< vector_type > soli, int i)
set solution (for stage i)
virtual ~AitkenNevilleTimex ()
Protected Member Functions
number substep (size_t i)
Private Attributes
std::vector< size_t > m_num_steps
std::vector< SmartPtr< vector_type > > m_solution
number m_stepsize
SmartPtr< ISubDiagErrorEst< vector_type > > m_subdiag
std::vector< number > m_subdiag_error_est
Static Private Attributes
static const int m_order =1
Member Typedef Documentation
vector_type
template<typename TVector > typedef TVector ug::AitkenNevilleTimex< TVector >::vector_type
vector type of solutions
Constructor & Destructor Documentation
AitkenNevilleTimex() [1/2]
template<typename TVector > ug::AitkenNevilleTimex< TVector >::AitkenNevilleTimex (std::vector< size_t > nsteps) inline
Aitken Neville scheme with a given number
References make_sp().
AitkenNevilleTimex() [2/2]
template<typename TVector > ug::AitkenNevilleTimex< TVector >::AitkenNevilleTimex (std::vector< size_t > nsteps, SmartPtr< ISubDiagErrorEst< vector_type > > error) inline
~AitkenNevilleTimex()
template<typename TVector > virtual ug::AitkenNevilleTimex< TVector >::~AitkenNevilleTimex () inline virtual
Member Function Documentation
apply() [1/2]
template<typename TVector > void ug::AitkenNevilleTimex< TVector >::apply () inline
apply for all stages
References ug::AitkenNevilleTimex< TVector >::m_num_steps.
apply() [2/2]
template<typename TVector > void ug::AitkenNevilleTimex< TVector >::apply (size_t nstages, bool with_error = true) inline
best error estimate
Triangular Aitken Neville extrapolation:
T_11 T_21 T_22
T_N1 T_NN
for T_ik
References ug::AitkenNevilleTimex< TVector >::m_num_steps, ug::AitkenNevilleTimex< TVector >::m_solution, ug::AitkenNevilleTimex< TVector >::m_subdiag, ug::AitkenNevilleTimex< TVector >::m_subdiag_error_est, UG_ASSERT, UG_LOG, and ug::VecScaleAdd().
Referenced by ug::LimexTimeIntegrator< TDomain, TAlgebra >::apply(), and ug::TimeIntegratorLinearAdaptive< TDomain, TAlgebra >::apply().
get_error_estimate()
template<typename TVector > number ug::AitkenNevilleTimex< TVector >::get_error_estimate (int k) const inline
error estimate on stage k
References ug::AitkenNevilleTimex< TVector >::m_subdiag_error_est.
get_error_estimates()
template<typename TVector > const std::vector<number>& ug::AitkenNevilleTimex< TVector >::get_error_estimates () const inline
References ug::AitkenNevilleTimex< TVector >::m_subdiag_error_est.
Referenced by ug::LimexTimeIntegrator< TDomain, TAlgebra >::apply(), and ug::TimeIntegratorLinearAdaptive< TDomain, TAlgebra >::apply().
get_global_stepsize()
template<typename TVector > number ug::AitkenNevilleTimex< TVector >::get_global_stepsize () inline
References ug::AitkenNevilleTimex< TVector >::m_stepsize.
get_solution()
template<typename TVector > SmartPtr<vector_type> ug::AitkenNevilleTimex< TVector >::get_solution (size_t i) inline
get solution (on stage i)
References ug::AitkenNevilleTimex< TVector >::m_solution.
Referenced by ug::LimexTimeIntegrator< TDomain, TAlgebra >::apply().
set_error_estimate()
template<typename TVector > void ug::AitkenNevilleTimex< TVector >::set_error_estimate (SmartPtr< ISubDiagErrorEst< vector_type > > subdiag) inline
set error estimator
References ug::AitkenNevilleTimex< TVector >::m_subdiag.
Referenced by ug::LimexTimeIntegrator< TDomain, TAlgebra >::apply().
set_global_stepsize()
template<typename TVector > void ug::AitkenNevilleTimex< TVector >::set_global_stepsize (number H) inline
References ug::AitkenNevilleTimex< TVector >::m_stepsize.
set_solution()
template<typename TVector > void ug::AitkenNevilleTimex< TVector >::set_solution (SmartPtr< vector_type > soli, int i) inline
set solution (for stage i)
References ug::AitkenNevilleTimex< TVector >::m_solution.
Referenced by ug::LimexTimeIntegrator< TDomain, TAlgebra >::apply(), and ug::TimeIntegratorLinearAdaptive< TDomain, TAlgebra >::apply().
substep()
template<typename TVector > number ug::AitkenNevilleTimex< TVector >::substep (size_t i) inline protected
References ug::AitkenNevilleTimex< TVector >::m_num_steps, and ug::AitkenNevilleTimex< TVector >::m_stepsize.
Member Data Documentation
m_num_steps
template<typename TVector > std::vector<size_t> ug::AitkenNevilleTimex< TVector >::m_num_steps private
n_i: number of intermediate steps (per stage)
Referenced by ug::AitkenNevilleTimex< TVector >::apply(), and ug::AitkenNevilleTimex< TVector >::substep().
m_order
template<typename TVector > const int ug::AitkenNevilleTimex< TVector >::m_order =1 static private
m_solution
template<typename TVector > std::vector<SmartPtr<vector_type> > ug::AitkenNevilleTimex< TVector >::m_solution private
vector of solutions (per stage)
Referenced by ug::AitkenNevilleTimex< TVector >::apply(), ug::AitkenNevilleTimex< TVector >::get_solution(), and ug::AitkenNevilleTimex< TVector >::set_solution().
m_stepsize
template<typename TVector > number ug::AitkenNevilleTimex< TVector >::m_stepsize private
time step
Referenced by ug::AitkenNevilleTimex< TVector >::get_global_stepsize(), ug::AitkenNevilleTimex< TVector >::set_global_stepsize(), and ug::AitkenNevilleTimex< TVector >::substep().
m_subdiag
template<typename TVector > SmartPtr<ISubDiagErrorEst<vector_type> > ug::AitkenNevilleTimex< TVector >::m_subdiag private
evaluation on last stage
Referenced by ug::AitkenNevilleTimex< TVector >::apply(), and ug::AitkenNevilleTimex< TVector >::set_error_estimate().
m_subdiag_error_est
template<typename TVector > std::vector<number> ug::AitkenNevilleTimex< TVector >::m_subdiag_error_est private
sub-diagonal error estimate (per stage)
Referenced by ug::AitkenNevilleTimex< TVector >::apply(), ug::AitkenNevilleTimex< TVector >::get_error_estimate(), and ug::AitkenNevilleTimex< TVector >::get_error_estimates().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Limex/time_disc/time_extrapolation.h