Plugins: ug::SupErrorEvaluator< TGridFunction > Class Template Reference
ug::SupErrorEvaluator< TGridFunction > Class Template Reference
#include <time_extrapolation.h>
Public Types
typedef IComponentSpace< TGridFunction > base_type
Public Types inherited from ug::IComponentSpace< TGridFunction >
typedef IGridFunctionSpace< TGridFunction > base_type
Public Types inherited from ug::IGridFunctionSpace< class >
typedef TGridFunction grid_function_type
typedef TGridFunction::vector_type vector_type
Public Member Functions
double distance (TGridFunction &uFine, TGridFunction &uCoarse)
double distance2 (TGridFunction &uFine, TGridFunction &uCoarse)
double norm (SmartPtr< TGridFunction > uFine)
double norm (TGridFunction &uFine)
double norm2 (TGridFunction &uFine)
SupErrorEvaluator (const char *fctNames)
SupErrorEvaluator (const char *fctNames, const char *ssNames)
~SupErrorEvaluator ()
Public Member Functions inherited from ug::IComponentSpace< TGridFunction >
virtual std::string config_string () const
IComponentSpace (const char *fctNames)
IComponentSpace (const char *fctNames, const char *ssNames, int order)
IComponentSpace (const char *fctNames, int order)
virtual ~IComponentSpace ()
Public Member Functions inherited from ug::IGridFunctionSpace< class >
virtual double distance (vector_type &x, vector_type &y)
virtual double norm (vector_type &x)
virtual double scaling () const
virtual ~IGridFunctionSpace ()
Public Member Functions inherited from IBanachSpace< TGridFunction::vector_type >
virtual ~IBanachSpace ()
Protected Member Functions
template<typename TBaseElem >
number findFctMaxOnSubset (const TGridFunction &u, int si) const
Additional Inherited Members
Static Public Attributes inherited from ug::IComponentSpace< TGridFunction >
static const int dim
Protected Attributes inherited from ug::IComponentSpace< TGridFunction >
std::string m_fctNames
int m_quadorder
const char * m_ssNames
Detailed Description
template<typename TGridFunction>
class ug::SupErrorEvaluator< TGridFunction >
Evaluates difference between two grid functions in L_inf norm
Member Typedef Documentation
base_type
template<typename TGridFunction > typedef IComponentSpace<TGridFunction> ug::SupErrorEvaluator< TGridFunction >::base_type
Constructor & Destructor Documentation
SupErrorEvaluator() [1/2]
template<typename TGridFunction > ug::SupErrorEvaluator< TGridFunction >::SupErrorEvaluator (const char * fctNames) inline
SupErrorEvaluator() [2/2]
template<typename TGridFunction > ug::SupErrorEvaluator< TGridFunction >::SupErrorEvaluator (const char * fctNames, const char * ssNames) inline
~SupErrorEvaluator()
template<typename TGridFunction > ug::SupErrorEvaluator< TGridFunction >::~SupErrorEvaluator () inline
Member Function Documentation
distance()
template<typename TGridFunction > double ug::SupErrorEvaluator< TGridFunction >::distance (TGridFunction & uFine, TGridFunction & uCoarse) inline virtual
Reimplemented from ug::IComponentSpace< TGridFunction >.
References ug::SupErrorEvaluator< TGridFunction >::norm(), and UG_COND_THROW.
Referenced by ug::SupErrorEvaluator< TGridFunction >::distance2().
distance2()
template<typename TGridFunction > double ug::SupErrorEvaluator< TGridFunction >::distance2 (TGridFunction & uFine, TGridFunction & uCoarse) inline virtual
Implements ug::IComponentSpace< TGridFunction >.
References ug::SupErrorEvaluator< TGridFunction >::distance().
findFctMaxOnSubset()
template<typename TGridFunction > template<typename TBaseElem > number ug::SupErrorEvaluator< TGridFunction >::findFctMaxOnSubset (const TGridFunction & u, int si) const inline protected
References ug::DoFRef(), ug::IComponentSpace< TGridFunction >::m_fctNames, and UG_CATCH_THROW.
norm() [1/2]
template<typename TGridFunction > double ug::SupErrorEvaluator< TGridFunction >::norm (SmartPtr< TGridFunction > uFine) inline
Referenced by ug::SupErrorEvaluator< TGridFunction >::distance(), and ug::SupErrorEvaluator< TGridFunction >::norm2().
norm() [2/2]
template<typename TGridFunction > double ug::SupErrorEvaluator< TGridFunction >::norm (TGridFunction & uFine) inline virtual
Reimplemented from ug::IComponentSpace< TGridFunction >.
References ug::SubsetGroup::add(), ug::SubsetGroup::add_all(), pcl::ProcessCommunicator::allreduce(), ug::SubsetGroup::dim(), ug::DIM_SUBSET_EMPTY_GRID, local(), ug::IComponentSpace< TGridFunction >::m_ssNames, pcl::NumProcs(), PCL_DT_DOUBLE, PCL_RO_MAX, ug::SubsetGroup::size(), ug::TokenizeString(), and UG_THROW.
norm2()
template<typename TGridFunction > double ug::SupErrorEvaluator< TGridFunction >::norm2 (TGridFunction & uFine) inline virtual
Implements ug::IComponentSpace< TGridFunction >.
References ug::SupErrorEvaluator< TGridFunction >::norm().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Limex/time_disc/time_extrapolation.h