Plugins: ug::promesh::detail::ProMeshFunction Class Reference
ug::promesh::detail::ProMeshFunction Class Reference
All functions registered in the ProMeshRegistry are encapsulated in a ProMeshFunction.
#include <promesh_registry.h>
Public Member Functions
bridge::ExportedFunction * exported_function ()
const bridge::ExportedFunction * exported_function () const
int group_priority () const
bool has_target (RegistryTargets t) const
bool operator< (const ProMeshFunction &f) const
int priority () const
ProMeshFunction (bridge::ExportedFunction *exportedFunction, int priority, int groupPriority, unsigned int target, int shortcutKey=0, ModifierKeys modifierKey=MK_NONE)
int shortcut_key () const
ModifierKeys shortcut_modifier_key () const
Private Attributes
bridge::ExportedFunction * m_exportedFunction
int m_groupPriority
ModifierKeys m_modifierKey
int m_priority
int m_shortcutKey
unsigned int m_target
Detailed Description
All functions registered in the ProMeshRegistry are encapsulated in a ProMeshFunction.
shortcut keys are specified as enumerated in ug::promesh::ShortcutKeys
Constructor & Destructor Documentation
ProMeshFunction()
ug::promesh::detail::ProMeshFunction::ProMeshFunction (bridge::ExportedFunction * exportedFunction, int priority, int groupPriority, unsigned int target, int shortcutKey = 0, ModifierKeys modifierKey = MK_NONE) inline
References target().
Member Function Documentation
exported_function() [1/2]
bridge::ExportedFunction* ug::promesh::detail::ProMeshFunction::exported_function () inline
Referenced by operator<().
exported_function() [2/2]
const bridge::ExportedFunction* ug::promesh::detail::ProMeshFunction::exported_function () const inline
group_priority()
int ug::promesh::detail::ProMeshFunction::group_priority () const inline
Referenced by operator<().
has_target()
bool ug::promesh::detail::ProMeshFunction::has_target (RegistryTargets t) const inline
operator<()
bool ug::promesh::detail::ProMeshFunction::operator< (const ProMeshFunction & f) const inline
References exported_function(), ug::bridge::ExportedFunction::group(), group_priority(), ug::bridge::ExportedFunctionBase::name(), ug::bridge::ExportedFunctionBase::num_parameter(), and priority().
priority()
int ug::promesh::detail::ProMeshFunction::priority () const inline
Referenced by operator<().
shortcut_key()
int ug::promesh::detail::ProMeshFunction::shortcut_key () const inline
shortcut_modifier_key()
ModifierKeys ug::promesh::detail::ProMeshFunction::shortcut_modifier_key () const inline
Member Data Documentation
m_exportedFunction
bridge::ExportedFunction* ug::promesh::detail::ProMeshFunction::m_exportedFunction private
m_groupPriority
int ug::promesh::detail::ProMeshFunction::m_groupPriority private
m_modifierKey
ModifierKeys ug::promesh::detail::ProMeshFunction::m_modifierKey private
m_priority
int ug::promesh::detail::ProMeshFunction::m_priority private
m_shortcutKey
int ug::promesh::detail::ProMeshFunction::m_shortcutKey private
m_target
unsigned int ug::promesh::detail::ProMeshFunction::m_target private
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/ProMesh/promesh_registry.h