Plugins: ug::NavierStokes::INavierStokesUpwind< dim > Class Template Reference
ug::NavierStokes::INavierStokesUpwind< dim > Class Template Reference
#include <upwind_interface.h>
Public Types
typedef INavierStokesUpwind< dim > this_type
Abbreviation for own type.
Public Member Functions
number downwind_conv_length (size_t scvf) const
Convection Length.
number downwind_shape_ip (size_t scvf, size_t scvf2) const
upwind shapes for ip vel
number downwind_shape_sh (size_t scvf, size_t sh) const
upwind shape for corner vel
INavierStokesUpwind ()
constructor
bool non_zero_shape_ip () const
returns if upwind shape w.r.t. ip vel is non-zero
size_t num_scvf () const
returns number of sub control volume faces
size_t num_sh () const
returns number of shapes
template<typename TFVGeom , typename TAssFunc >
void register_update_func (TAssFunc func)
register a update function for a Geometry
template<typename TFVGeom , typename TAssFunc >
void register_update_ip_vel_func (TAssFunc func)
register a update function for a Geometry
template<typename TFVGeom >
void set_geometry_type ()
set the Geometry type to use for next updates
void update (const FVGeometryBase *geo, const MathVector< dim > vStdVel[])
compute values for new geometry and corner velocities
void update_downwind (const FVGeometryBase *geo, const MathVector< dim > vStdVel[])
compute values for new geometry and corner velocities
void update_upwind (const FVGeometryBase *geo, const MathVector< dim > vStdVel[])
compute values for new geometry and corner velocities
number upwind_conv_length (size_t scvf) const
Convection Length.
number upwind_shape_ip (size_t scvf, size_t scvf2) const
upwind shapes for ip vel
number upwind_shape_sh (size_t scvf, size_t sh) const
upwind shape for corner vel
MathVector< dim > upwind_vel (const size_t scvf, const LocalVector &CornerVel, const MathVector< dim > vStdVel[]) const
returns the upwind velocity
Static Public Attributes
static const size_t maxNumSCVF = traits::maxNumSCVF + 10
max number of SubControlVolumeFaces
static const size_t maxNumSH = traits::maxNSH + 10
max number of shape functions
Protected Types
typedef void(* ComputeFunc) (const FVGeometryBase *obj, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF])
type of update function
typedef fv1_dim_traits< dim, dim > traits
used traits
Protected Member Functions
void compute (const FVGeometryBase *geo, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF])
compute values for new geometry and corner velocities
number & down_upwind_conv_length (size_t scvf)
non-const access to Convection Length
number & downwind_shape_ip (size_t scvf, size_t scvf2)
non-const access to upwind shapes for ip vel
number & downwind_shape_sh (size_t scvf, size_t sh)
non-const access to upwind shapes for corner vel
void set_shape_ip_flag (bool flag)
sets the shape ip flag
number & upwind_conv_length (size_t scvf)
non-const access to Convection Length
number & upwind_shape_ip (size_t scvf, size_t scvf2)
non-const access to upwind shapes for ip vel
number & upwind_shape_sh (size_t scvf, size_t sh)
non-const access to upwind shapes for corner vel
Protected Attributes
bool m_bNonZeroShapeIp
flag if ip shapes are non-zero
int m_id
id of current geometry type
size_t m_numScvf
number of current scvf
size_t m_numSh
number of current shape functions (usually in corners)
std::vector< ComputeFunc > m_vComputeFunc
Vector holding all update functions.
number m_vDownConvLength [maxNumSCVF]
number m_vUpConvLength [maxNumSCVF]
convection length
number m_vvDownShapeIp [maxNumSCVF][maxNumSCVF]
number m_vvDownShapeSh [maxNumSCVF][maxNumSH]
number m_vvUpShapeIp [maxNumSCVF][maxNumSCVF]
upwind shapes for ip vels
number m_vvUpShapeSh [maxNumSCVF][maxNumSH]
upwind shapes for corners shape functions
Member Typedef Documentation
ComputeFunc
template<int dim> typedef void(* ug::NavierStokes::INavierStokesUpwind< dim >::ComputeFunc) (const FVGeometryBase *obj, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF]) protected
type of update function
this_type
template<int dim> typedef INavierStokesUpwind<dim> ug::NavierStokes::INavierStokesUpwind< dim >::this_type
Abbreviation for own type.
traits
template<int dim> typedef fv1_dim_traits<dim, dim> ug::NavierStokes::INavierStokesUpwind< dim >::traits protected
used traits
Constructor & Destructor Documentation
INavierStokesUpwind()
template<int dim> ug::NavierStokes::INavierStokesUpwind< dim >::INavierStokesUpwind () inline
constructor
References ug::NavierStokes::INavierStokesUpwind< dim >::m_vComputeFunc.
Member Function Documentation
compute()
template<int dim> void ug::NavierStokes::INavierStokesUpwind< dim >::compute (const FVGeometryBase * geo, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF]) inline protected
compute values for new geometry and corner velocities
References ug::NavierStokes::INavierStokesUpwind< dim >::m_id, and ug::NavierStokes::INavierStokesUpwind< dim >::m_vComputeFunc.
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::update_downwind(), and ug::NavierStokes::INavierStokesUpwind< dim >::update_upwind().
down_upwind_conv_length()
template<int dim> number& ug::NavierStokes::INavierStokesUpwind< dim >::down_upwind_conv_length (size_t scvf) inline protected
non-const access to Convection Length
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_vDownConvLength, and UG_NSUPWIND_ASSERT.
downwind_conv_length()
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::downwind_conv_length (size_t scvf) const inline
Convection Length.
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_vDownConvLength, and UG_NSUPWIND_ASSERT.
downwind_shape_ip() [1/2]
template<int dim> number& ug::NavierStokes::INavierStokesUpwind< dim >::downwind_shape_ip (size_t scvf, size_t scvf2) inline protected
non-const access to upwind shapes for ip vel
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_vvDownShapeIp, and UG_NSUPWIND_ASSERT.
downwind_shape_ip() [2/2]
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::downwind_shape_ip (size_t scvf, size_t scvf2) const inline
upwind shapes for ip vel
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_vvDownShapeIp, and UG_NSUPWIND_ASSERT.
downwind_shape_sh() [1/2]
template<int dim> number& ug::NavierStokes::INavierStokesUpwind< dim >::downwind_shape_sh (size_t scvf, size_t sh) inline protected
non-const access to upwind shapes for corner vel
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_numSh, ug::NavierStokes::INavierStokesUpwind< dim >::m_vvDownShapeSh, and UG_NSUPWIND_ASSERT.
downwind_shape_sh() [2/2]
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::downwind_shape_sh (size_t scvf, size_t sh) const inline
upwind shape for corner vel
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_numSh, ug::NavierStokes::INavierStokesUpwind< dim >::m_vvDownShapeSh, and UG_NSUPWIND_ASSERT.
non_zero_shape_ip()
template<int dim> bool ug::NavierStokes::INavierStokesUpwind< dim >::non_zero_shape_ip () const inline
returns if upwind shape w.r.t. ip vel is non-zero
References ug::NavierStokes::INavierStokesUpwind< dim >::m_bNonZeroShapeIp.
Referenced by ug::NavierStokes::NavierStokesFVCR< TDomain >::add_jac_A_elem().
num_scvf()
template<int dim> size_t ug::NavierStokes::INavierStokesUpwind< dim >::num_scvf () const inline
returns number of sub control volume faces
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf.
num_sh()
template<int dim> size_t ug::NavierStokes::INavierStokesUpwind< dim >::num_sh () const inline
returns number of shapes
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numSh.
register_update_func()
template<int dim> template<typename TFVGeom , typename TAssFunc > void ug::NavierStokes::INavierStokesUpwind< dim >::register_update_func (TAssFunc func)
register a update function for a Geometry
register_update_ip_vel_func()
template<int dim> template<typename TFVGeom , typename TAssFunc > void ug::NavierStokes::INavierStokesUpwind< dim >::register_update_ip_vel_func (TAssFunc func)
register a update function for a Geometry
set_geometry_type()
template<int dim> template<typename TFVGeom > void ug::NavierStokes::INavierStokesUpwind< dim >::set_geometry_type
set the Geometry type to use for next updates
References ug::GeomProvider< class >::get(), UG_NSUPWIND_ASSERT, and UG_THROW.
set_shape_ip_flag()
template<int dim> void ug::NavierStokes::INavierStokesUpwind< dim >::set_shape_ip_flag (bool flag) inline protected
sets the shape ip flag
References ug::NavierStokes::INavierStokesUpwind< dim >::m_bNonZeroShapeIp.
Referenced by ug::NavierStokes::NavierStokesFullUpwind< dim >::NavierStokesFullUpwind(), ug::NavierStokes::NavierStokesLinearProfileSkewedUpwind< dim >::NavierStokesLinearProfileSkewedUpwind(), ug::NavierStokes::NavierStokesNoUpwind< dim >::NavierStokesNoUpwind(), ug::NavierStokes::NavierStokesPositiveUpwind< dim >::NavierStokesPositiveUpwind(), ug::NavierStokes::NavierStokesRegularUpwind< dim >::NavierStokesRegularUpwind(), and ug::NavierStokes::NavierStokesSkewedUpwind< dim >::NavierStokesSkewedUpwind().
update()
template<int dim> void ug::NavierStokes::INavierStokesUpwind< dim >::update (const FVGeometryBase * geo, const MathVector< dim > vStdVel[]) inline
compute values for new geometry and corner velocities
References ug::NavierStokes::INavierStokesUpwind< dim >::update_upwind().
Referenced by ug::NavierStokes::NavierStokesFVCR< TDomain >::add_def_A_elem(), and ug::NavierStokes::NavierStokesFVCR< TDomain >::add_jac_A_elem().
update_downwind()
template<int dim> void ug::NavierStokes::INavierStokesUpwind< dim >::update_downwind (const FVGeometryBase * geo, const MathVector< dim > vStdVel[]) inline
compute values for new geometry and corner velocities
References ug::NavierStokes::INavierStokesUpwind< dim >::compute(), ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_vDownConvLength, ug::NavierStokes::INavierStokesUpwind< dim >::m_vvDownShapeIp, ug::NavierStokes::INavierStokesUpwind< dim >::m_vvDownShapeSh, ug::NavierStokes::INavierStokesUpwind< dim >::maxNumSCVF, and ug::VecScale().
update_upwind()
template<int dim> void ug::NavierStokes::INavierStokesUpwind< dim >::update_upwind (const FVGeometryBase * geo, const MathVector< dim > vStdVel[]) inline
compute values for new geometry and corner velocities
References ug::NavierStokes::INavierStokesUpwind< dim >::compute(), ug::NavierStokes::INavierStokesUpwind< dim >::m_vUpConvLength, ug::NavierStokes::INavierStokesUpwind< dim >::m_vvUpShapeIp, and ug::NavierStokes::INavierStokesUpwind< dim >::m_vvUpShapeSh.
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::update().
upwind_conv_length() [1/2]
template<int dim> number& ug::NavierStokes::INavierStokesUpwind< dim >::upwind_conv_length (size_t scvf) inline protected
non-const access to Convection Length
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_vUpConvLength, and UG_NSUPWIND_ASSERT.
upwind_conv_length() [2/2]
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::upwind_conv_length (size_t scvf) const inline
Convection Length.
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_vUpConvLength, and UG_NSUPWIND_ASSERT.
upwind_shape_ip() [1/2]
template<int dim> number& ug::NavierStokes::INavierStokesUpwind< dim >::upwind_shape_ip (size_t scvf, size_t scvf2) inline protected
non-const access to upwind shapes for ip vel
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_vvUpShapeIp, and UG_NSUPWIND_ASSERT.
upwind_shape_ip() [2/2]
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::upwind_shape_ip (size_t scvf, size_t scvf2) const inline
upwind shapes for ip vel
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_vvUpShapeIp, and UG_NSUPWIND_ASSERT.
Referenced by ug::NavierStokes::NavierStokesFV1< TDomain >::add_jac_A_elem(), and ug::NavierStokes::NavierStokesFVCR< TDomain >::add_jac_A_elem().
upwind_shape_sh() [1/2]
template<int dim> number& ug::NavierStokes::INavierStokesUpwind< dim >::upwind_shape_sh (size_t scvf, size_t sh) inline protected
non-const access to upwind shapes for corner vel
References ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf, ug::NavierStokes::INavierStokesUpwind< dim >::m_numSh, ug::NavierStokes::INavierStokesUpwind< dim >::m_vvUpShapeSh, and UG_NSUPWIND_ASSERT.
upwind_shape_sh() [2/2]
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::upwind_shape_sh (size_t scvf, size_t sh) const inline
upwind shape for corner vel
References ug::NavierStokes::INavierStokesUpwind< dim >::m_vvUpShapeSh.
Referenced by ug::NavierStokes::NavierStokesFV1< TDomain >::add_jac_A_elem(), and ug::NavierStokes::NavierStokesFVCR< TDomain >::add_jac_A_elem().
upwind_vel()
template<int dim> MathVector< dim > ug::NavierStokes::INavierStokesUpwind< dim >::upwind_vel (const size_t scvf, const LocalVector & CornerVel, const MathVector< dim > vStdVel[]) const
returns the upwind velocity
upwind velocity
References dim, ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::NavierStokes::CompressibleNavierStokesFV1< TDomain >::add_def_A_elem(), ug::NavierStokes::NavierStokesFV1< TDomain >::add_def_A_elem(), ug::NavierStokes::NavierStokesFVCR< TDomain >::add_def_A_elem(), ug::NavierStokes::NavierStokesFV1< TDomain >::add_jac_A_elem(), and ug::NavierStokes::NavierStokesFVCR< TDomain >::add_jac_A_elem().
Member Data Documentation
m_bNonZeroShapeIp
template<int dim> bool ug::NavierStokes::INavierStokesUpwind< dim >::m_bNonZeroShapeIp protected
flag if ip shapes are non-zero
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::non_zero_shape_ip(), and ug::NavierStokes::INavierStokesUpwind< dim >::set_shape_ip_flag().
m_id
template<int dim> int ug::NavierStokes::INavierStokesUpwind< dim >::m_id protected
id of current geometry type
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::compute().
m_numScvf
template<int dim> size_t ug::NavierStokes::INavierStokesUpwind< dim >::m_numScvf protected
number of current scvf
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::down_upwind_conv_length(), ug::NavierStokes::INavierStokesUpwind< dim >::downwind_conv_length(), ug::NavierStokes::INavierStokesUpwind< dim >::downwind_shape_ip(), ug::NavierStokes::INavierStokesUpwind< dim >::downwind_shape_sh(), ug::NavierStokes::INavierStokesUpwind< dim >::num_scvf(), ug::NavierStokes::INavierStokesUpwind< dim >::update_downwind(), ug::NavierStokes::INavierStokesUpwind< dim >::upwind_conv_length(), ug::NavierStokes::INavierStokesUpwind< dim >::upwind_shape_ip(), and ug::NavierStokes::INavierStokesUpwind< dim >::upwind_shape_sh().
m_numSh
template<int dim> size_t ug::NavierStokes::INavierStokesUpwind< dim >::m_numSh protected
number of current shape functions (usually in corners)
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::downwind_shape_sh(), ug::NavierStokes::INavierStokesUpwind< dim >::num_sh(), and ug::NavierStokes::INavierStokesUpwind< dim >::upwind_shape_sh().
m_vComputeFunc
template<int dim> std::vector<ComputeFunc> ug::NavierStokes::INavierStokesUpwind< dim >::m_vComputeFunc protected
Vector holding all update functions.
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::compute(), and ug::NavierStokes::INavierStokesUpwind< dim >::INavierStokesUpwind().
m_vDownConvLength
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::m_vDownConvLength[maxNumSCVF] protected
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::down_upwind_conv_length(), ug::NavierStokes::INavierStokesUpwind< dim >::downwind_conv_length(), and ug::NavierStokes::INavierStokesUpwind< dim >::update_downwind().
m_vUpConvLength
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::m_vUpConvLength[maxNumSCVF] protected
convection length
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::update_upwind(), and ug::NavierStokes::INavierStokesUpwind< dim >::upwind_conv_length().
m_vvDownShapeIp
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::m_vvDownShapeIp[maxNumSCVF][maxNumSCVF] protected
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::downwind_shape_ip(), and ug::NavierStokes::INavierStokesUpwind< dim >::update_downwind().
m_vvDownShapeSh
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::m_vvDownShapeSh[maxNumSCVF][maxNumSH] protected
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::downwind_shape_sh(), and ug::NavierStokes::INavierStokesUpwind< dim >::update_downwind().
m_vvUpShapeIp
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::m_vvUpShapeIp[maxNumSCVF][maxNumSCVF] protected
upwind shapes for ip vels
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::update_upwind(), and ug::NavierStokes::INavierStokesUpwind< dim >::upwind_shape_ip().
m_vvUpShapeSh
template<int dim> number ug::NavierStokes::INavierStokesUpwind< dim >::m_vvUpShapeSh[maxNumSCVF][maxNumSH] protected
upwind shapes for corners shape functions
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::update_upwind(), and ug::NavierStokes::INavierStokesUpwind< dim >::upwind_shape_sh().
maxNumSCVF
template<int dim> const size_t ug::NavierStokes::INavierStokesUpwind< dim >::maxNumSCVF = traits::maxNumSCVF + 10 static
max number of SubControlVolumeFaces
Referenced by ug::NavierStokes::INavierStokesUpwind< dim >::update_downwind().
maxNumSH
template<int dim> const size_t ug::NavierStokes::INavierStokesUpwind< dim >::maxNumSH = traits::maxNSH + 10 static
max number of shape functions
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/upwind_interface.h