Plugins: ug::NavierStokes::INavierStokesSRFV1Stabilization< dim > Class Template Reference
ug::NavierStokes::INavierStokesSRFV1Stabilization< dim > Class Template Reference
#include <stabilization.h>
Public Member Functions
INavierStokesSRFV1Stabilization ()
constructor
void set_diffusion_length (std::string diffLength)
sets the type of diff length used for evaluation
Public Member Functions inherited from ug::NavierStokes::INavierStokesFV1Stabilization< dim >
INavierStokesFV1Stabilization ()
constructor
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shapes (corners)
template<typename TFVGeom , typename TAssFunc >
void register_update_func (TAssFunc func)
register a update function for a Geometry
template<typename TFVGeom >
void set_geometry_type ()
set the FV1 Geometry type to use for next updates
void set_upwind (SmartPtr< INavierStokesUpwind< dim > > spUpwind)
sets the upwind method
number stab_shape_p (size_t scvf, size_t compOut, size_t sh) const
computed stab shape for pressure.
number stab_shape_vel (size_t scvf, size_t compOut, size_t compIn, size_t sh) const
const MathVector< dim > & stab_vel (size_t scvf) const
stabilized velocity
void update (const FVGeometryBase *geo, const LocalVector &vCornerValue, const MathVector< dim > vStdVel[], const bool bStokes, const DataImport< number, dim > &kinVisco, const DataImport< number, dim > &density, const DataImport< MathVector< dim >, dim > *pSource, const LocalVector *pvCornerValueOldTime, number dt)
compute values for new geometry and corner velocities
const ConstSmartPtr< INavierStokesUpwind< dim > > & upwind () const
returns the upwind
bool upwind_valid () const
returns if the upwind pointer is valid
bool vel_comp_connected () const
returns if stab velocity comp depends on other vel components
Protected Types
enum DiffusionLength { RAW = 0 , FIVEPOINT , COR }
Protected Types inherited from ug::NavierStokes::INavierStokesFV1Stabilization< dim >
typedef fv1_dim_traits< dim, dim > traits
used traits
typedef void(this_type::* UpdateFunc) (const FVGeometryBase *geo, const LocalVector &vCornerValue, const MathVector< dim > vStdVel[], const bool bStokes, const DataImport< number, dim > &kinVisco, const DataImport< number, dim > &density, const DataImport< MathVector< dim >, dim > *pSource, const LocalVector *pvCornerValueOldTime, number dt)
type of update function
Protected Member Functions
template<typename TFVGeom >
void compute_diff_length (const TFVGeom &geo)
computes the diffusion length
number diff_length_sq_inv (size_t scvf) const
diff length
number downwind_conv_length (size_t scvf) const
Convection Length.
number downwind_shape_ip (size_t scvf, size_t scvf2) const
upwind shapes for ip vel
number downwind_shape_sh (size_t scvf, size_t sh) const
upwind shape for corner vel
bool non_zero_shape_ip () const
returns if upwind shape w.r.t. ip vel is non-zero
number upwind_conv_length (size_t scvf) const
Convection Length.
number upwind_shape_ip (size_t scvf, size_t scvf2) const
upwind shapes for ip vel
number upwind_shape_sh (size_t scvf, size_t sh) const
upwind shape for corner vel
Protected Member Functions inherited from ug::NavierStokes::INavierStokesFV1Stabilization< dim >
template<typename TFVGeom >
void compute_downwind (const TFVGeom &geo, const MathVector< dim > vStdVel[])
computes the downwind shapes
template<typename TFVGeom >
void compute_upwind (const TFVGeom &geo, const MathVector< dim > vStdVel[])
computes the upwind shapes
void set_vel_comp_connected (bool bVelCompConnected)
sets the vel comp connected flag
number & stab_shape_p (size_t scvf, size_t compOut, size_t sh)
computed stab shape for pressure.
number & stab_shape_vel (size_t scvf, size_t compOut, size_t compIn, size_t sh)
MathVector< dim > & stab_vel (size_t scvf)
stabilized velocity
Protected Attributes
DiffusionLength m_diffLengthType
type of diffusion length computation
number m_vDiffLengthSqInv [this_type::maxNumSCVF]
vector holding diffusion Length squared and inverted
Protected Attributes inherited from ug::NavierStokes::INavierStokesFV1Stabilization< dim >
std::vector< UpdateFunc > m_vUpdateFunc
Vector holding all update functions.
Private Types
typedef INavierStokesSRFV1Stabilization< dim > this_type
Abbreviation for own type.
Additional Inherited Members
Static Public Attributes inherited from ug::NavierStokes::INavierStokesFV1Stabilization< dim >
static const size_t maxNumSCV = traits::maxNumSCV
number of SubControlVolumes
static const size_t maxNumSCVF = traits::maxNumSCVF
max number of SubControlVolumeFaces
static const size_t maxNumSH = traits::maxNSH
max number of shape functions
Detailed Description
template<int dim>
class ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >
The base class for the Schneider-Raw-type stabilizations for FV1-discretizations of the NS equations.
Template Parameters
dim dimension of the world
Member Typedef Documentation
this_type
template<int dim> typedef INavierStokesSRFV1Stabilization<dim> ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::this_type private
Abbreviation for own type.
Member Enumeration Documentation
DiffusionLength
template<int dim> enum ug::NavierStokes::INavierStokesSRFV1Stabilization::DiffusionLength protected
Enumerator
RAW
FIVEPOINT
COR
Constructor & Destructor Documentation
INavierStokesSRFV1Stabilization()
template<int dim> ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::INavierStokesSRFV1Stabilization () inline
constructor
References ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::set_diffusion_length().
Member Function Documentation
compute_diff_length()
template<int dim> template<typename TFVGeom > void ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::compute_diff_length (const TFVGeom & geo) protected
computes the diffusion length
References ug::NavierStokes::NSDiffLengthCor(), ug::NavierStokes::NSDiffLengthFivePoint(), ug::NavierStokes::NSDiffLengthRaw(), and UG_THROW.
diff_length_sq_inv()
template<int dim> number ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::diff_length_sq_inv (size_t scvf) const inline protected
diff length
References ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::m_vDiffLengthSqInv, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::num_ip(), and UG_NSSTAB_ASSERT.
downwind_conv_length()
template<int dim> number ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::downwind_conv_length (size_t scvf) const inline protected
Convection Length.
References UG_NSSTAB_ASSERT, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind_valid().
downwind_shape_ip()
template<int dim> number ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::downwind_shape_ip (size_t scvf, size_t scvf2) const inline protected
upwind shapes for ip vel
References UG_NSSTAB_ASSERT, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind_valid().
downwind_shape_sh()
template<int dim> number ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::downwind_shape_sh (size_t scvf, size_t sh) const inline protected
upwind shape for corner vel
References UG_NSSTAB_ASSERT, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind_valid().
non_zero_shape_ip()
template<int dim> bool ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::non_zero_shape_ip () const inline protected
returns if upwind shape w.r.t. ip vel is non-zero
References UG_NSSTAB_ASSERT, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind_valid().
set_diffusion_length()
template<int dim> void ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::set_diffusion_length (std::string diffLength)
sets the type of diff length used for evaluation
References ug::TrimString(), and UG_THROW.
Referenced by ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::INavierStokesSRFV1Stabilization().
upwind_conv_length()
template<int dim> number ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::upwind_conv_length (size_t scvf) const inline protected
Convection Length.
References UG_NSSTAB_ASSERT, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind_valid().
upwind_shape_ip()
template<int dim> number ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::upwind_shape_ip (size_t scvf, size_t scvf2) const inline protected
upwind shapes for ip vel
References UG_NSSTAB_ASSERT, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind_valid().
upwind_shape_sh()
template<int dim> number ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::upwind_shape_sh (size_t scvf, size_t sh) const inline protected
upwind shape for corner vel
References UG_NSSTAB_ASSERT, ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::upwind_valid().
Member Data Documentation
m_diffLengthType
template<int dim> DiffusionLength ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::m_diffLengthType protected
type of diffusion length computation
m_vDiffLengthSqInv
template<int dim> number ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::m_vDiffLengthSqInv[this_type::maxNumSCVF] protected
vector holding diffusion Length squared and inverted
Referenced by ug::NavierStokes::INavierStokesSRFV1Stabilization< dim >::diff_length_sq_inv().
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/stabilization.h
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/stabilization.cpp