Plugins: ug::NavierStokes::NavierStokesFullUpwind< dim > Class Template Reference
ug::NavierStokes::NavierStokesFullUpwind< dim > Class Template Reference
#include <upwind.h>
Public Types
typedef INavierStokesUpwind< dim > base_type
Public Types inherited from ug::NavierStokes::INavierStokesUpwind< dim >
typedef INavierStokesUpwind< dim > this_type
Abbreviation for own type.
Public Types inherited from ug::NavierStokes::NavierStokesUpwindRegister< FV1Geometry, dim, NavierStokesFullUpwind< dim > >
typedef INavierStokesUpwind< dim > base_type
Base class.
Public Types inherited from ug::NavierStokes::NavierStokesUpwindRegister< CRFVGeometry, dim, NavierStokesFullUpwind< dim > >
typedef INavierStokesUpwind< dim > base_type
Base class.
Public Types inherited from ug::NavierStokes::NavierStokesUpwindRegister< HCRFVGeometry, dim, NavierStokesFullUpwind< dim > >
typedef INavierStokesUpwind< dim > base_type
Base class.
Public Member Functions
NavierStokesFullUpwind ()
constructor
Public Member Functions inherited from ug::NavierStokes::INavierStokesUpwind< dim >
number downwind_conv_length (size_t scvf) const
Convection Length.
number downwind_shape_ip (size_t scvf, size_t scvf2) const
upwind shapes for ip vel
number downwind_shape_sh (size_t scvf, size_t sh) const
upwind shape for corner vel
INavierStokesUpwind ()
constructor
bool non_zero_shape_ip () const
returns if upwind shape w.r.t. ip vel is non-zero
size_t num_scvf () const
returns number of sub control volume faces
size_t num_sh () const
returns number of shapes
template<typename TFVGeom , typename TAssFunc >
void register_update_func (TAssFunc func)
register a update function for a Geometry
template<typename TFVGeom , typename TAssFunc >
void register_update_ip_vel_func (TAssFunc func)
register a update function for a Geometry
template<typename TFVGeom >
void set_geometry_type ()
set the Geometry type to use for next updates
void update (const FVGeometryBase *geo, const MathVector< dim > vStdVel[])
compute values for new geometry and corner velocities
void update_downwind (const FVGeometryBase *geo, const MathVector< dim > vStdVel[])
compute values for new geometry and corner velocities
void update_upwind (const FVGeometryBase *geo, const MathVector< dim > vStdVel[])
compute values for new geometry and corner velocities
number upwind_conv_length (size_t scvf) const
Convection Length.
number upwind_shape_ip (size_t scvf, size_t scvf2) const
upwind shapes for ip vel
number upwind_shape_sh (size_t scvf, size_t sh) const
upwind shape for corner vel
MathVector< dim > upwind_vel (const size_t scvf, const LocalVector &CornerVel, const MathVector< dim > vStdVel[]) const
returns the upwind velocity
Public Member Functions inherited from ug::NavierStokes::NavierStokesUpwindRegister< FV1Geometry, dim, NavierStokesFullUpwind< dim > >
NavierStokesUpwindRegister ()
constructor
Public Member Functions inherited from ug::NavierStokes::NavierStokesUpwindRegister< CRFVGeometry, dim, NavierStokesFullUpwind< dim > >
NavierStokesUpwindRegister ()
constructor
Public Member Functions inherited from ug::NavierStokes::NavierStokesUpwindRegister< HCRFVGeometry, dim, NavierStokesFullUpwind< dim > >
NavierStokesUpwindRegister ()
constructor
Static Public Member Functions
template<typename TElem >
static void compute (const CRFVGeometry< TElem, dim > *geo, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF])
update of values for CRFVGeometry
template<typename TElem >
static void compute (const FV1Geometry< TElem, dim > *geo, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF])
update of values for FV1Geometry
template<typename TElem >
static void compute (const HCRFVGeometry< TElem, dim > *geo, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF])
update of values for CRFVGeometry
Static Public Attributes
static const size_t maxNumSCVF = base_type::maxNumSCVF
static const size_t maxNumSH = base_type::maxNumSH
Static Public Attributes inherited from ug::NavierStokes::INavierStokesUpwind< dim >
static const size_t maxNumSCVF = traits::maxNumSCVF + 10
max number of SubControlVolumeFaces
static const size_t maxNumSH = traits::maxNSH + 10
max number of shape functions
Additional Inherited Members
Protected Types inherited from ug::NavierStokes::INavierStokesUpwind< dim >
typedef void(* ComputeFunc) (const FVGeometryBase *obj, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF])
type of update function
typedef fv1_dim_traits< dim, dim > traits
used traits
Protected Member Functions inherited from ug::NavierStokes::INavierStokesUpwind< dim >
void compute (const FVGeometryBase *geo, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF])
compute values for new geometry and corner velocities
number & down_upwind_conv_length (size_t scvf)
non-const access to Convection Length
number & downwind_shape_ip (size_t scvf, size_t scvf2)
non-const access to upwind shapes for ip vel
number & downwind_shape_sh (size_t scvf, size_t sh)
non-const access to upwind shapes for corner vel
void set_shape_ip_flag (bool flag)
sets the shape ip flag
number & upwind_conv_length (size_t scvf)
non-const access to Convection Length
number & upwind_shape_ip (size_t scvf, size_t scvf2)
non-const access to upwind shapes for ip vel
number & upwind_shape_sh (size_t scvf, size_t sh)
non-const access to upwind shapes for corner vel
Protected Member Functions inherited from ug::NavierStokes::NavierStokesUpwindRegister< FV1Geometry, dim, NavierStokesFullUpwind< dim > >
NavierStokesFullUpwind< dim > & getImpl ()
access to implementation
Protected Member Functions inherited from ug::NavierStokes::NavierStokesUpwindRegister< CRFVGeometry, dim, NavierStokesFullUpwind< dim > >
NavierStokesFullUpwind< dim > & getImpl ()
access to implementation
Protected Member Functions inherited from ug::NavierStokes::NavierStokesUpwindRegister< HCRFVGeometry, dim, NavierStokesFullUpwind< dim > >
NavierStokesFullUpwind< dim > & getImpl ()
access to implementation
Protected Attributes inherited from ug::NavierStokes::INavierStokesUpwind< dim >
bool m_bNonZeroShapeIp
flag if ip shapes are non-zero
int m_id
id of current geometry type
size_t m_numScvf
number of current scvf
size_t m_numSh
number of current shape functions (usually in corners)
std::vector< ComputeFunc > m_vComputeFunc
Vector holding all update functions.
number m_vDownConvLength [maxNumSCVF]
number m_vUpConvLength [maxNumSCVF]
convection length
number m_vvDownShapeIp [maxNumSCVF][maxNumSCVF]
number m_vvDownShapeSh [maxNumSCVF][maxNumSH]
number m_vvUpShapeIp [maxNumSCVF][maxNumSCVF]
upwind shapes for ip vels
number m_vvUpShapeSh [maxNumSCVF][maxNumSH]
upwind shapes for corners shape functions
Static Protected Attributes inherited from ug::NavierStokes::NavierStokesUpwindRegister< FV1Geometry, dim, NavierStokesFullUpwind< dim > >
static const size_t maxNumSCVF
static const size_t maxNumSH
Static Protected Attributes inherited from ug::NavierStokes::NavierStokesUpwindRegister< CRFVGeometry, dim, NavierStokesFullUpwind< dim > >
static const size_t maxNumSCVF
static const size_t maxNumSH
Static Protected Attributes inherited from ug::NavierStokes::NavierStokesUpwindRegister< HCRFVGeometry, dim, NavierStokesFullUpwind< dim > >
static const size_t maxNumSCVF
static const size_t maxNumSH
Member Typedef Documentation
base_type
template<int dim> typedef INavierStokesUpwind<dim> ug::NavierStokes::NavierStokesFullUpwind< dim >::base_type
Constructor & Destructor Documentation
NavierStokesFullUpwind()
template<int dim> ug::NavierStokes::NavierStokesFullUpwind< dim >::NavierStokesFullUpwind () inline
constructor
References ug::NavierStokes::INavierStokesUpwind< dim >::set_shape_ip_flag().
Member Function Documentation
compute() [1/3]
template<int dim> template<typename TElem > void ug::NavierStokes::NavierStokesFullUpwind< dim >::compute (const CRFVGeometry< TElem, dim > * geo, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF]) static
update of values for CRFVGeometry
References ug::CRFVGeometry< class, TWorldDim >::SCVF::from(), ug::CRFVGeometry< class, TWorldDim >::SCVF::global_ip(), ug::CRFVGeometry< class, TWorldDim >::SCVF::normal(), ug::CRFVGeometry< class, TWorldDim >::num_scvf(), ug::CRFVGeometry< class, TWorldDim >::SCVF::num_sh(), ug::CRFVGeometry< class, TWorldDim >::scv_global_ips(), ug::CRFVGeometry< class, TWorldDim >::scvf(), ug::CRFVGeometry< class, TWorldDim >::SCVF::to(), ug::VecDistance(), and ug::VecDot().
compute() [2/3]
template<int dim> template<typename TElem > void ug::NavierStokes::NavierStokesFullUpwind< dim >::compute (const FV1Geometry< TElem, dim > * geo, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF]) static
update of values for FV1Geometry
References FV1Geometry_gen< TElem, TWorldDim, false >::corners(), FV1Geometry_gen< TElem, TWorldDim, false >::num_scvf(), FV1Geometry_gen< TElem, TWorldDim, false >::num_sh(), FV1Geometry_gen< TElem, TWorldDim, false >::scvf(), ug::VecDistance(), and ug::VecDot().
compute() [3/3]
template<int dim> template<typename TElem > void ug::NavierStokes::NavierStokesFullUpwind< dim >::compute (const HCRFVGeometry< TElem, dim > * geo, const MathVector< dim > vIPVel[maxNumSCVF], number vUpShapeSh[maxNumSCVF][maxNumSH], number vUpShapeIp[maxNumSCVF][maxNumSCVF], number vConvLength[maxNumSCVF]) static
update of values for CRFVGeometry
References ug::HCRFVGeometry< class, TWorldDim >::constrained_dof(), ug::HCRFVGeometry< class, TWorldDim >::SCVF::from(), ug::HCRFVGeometry< class, TWorldDim >::SCVF::normal(), ug::HCRFVGeometry< class, TWorldDim >::num_constrained_dofs(), ug::HCRFVGeometry< class, TWorldDim >::num_scv(), ug::HCRFVGeometry< class, TWorldDim >::num_scvf(), ug::HCRFVGeometry< class, TWorldDim >::SCVF::num_sh(), ug::HCRFVGeometry< class, TWorldDim >::num_sh(), ug::HCRFVGeometry< class, TWorldDim >::scvf(), ug::HCRFVGeometry< class, TWorldDim >::SCVF::to(), and ug::VecDot().
Member Data Documentation
maxNumSCVF
template<int dim> const size_t ug::NavierStokes::NavierStokesFullUpwind< dim >::maxNumSCVF = base_type::maxNumSCVF static
maxNumSH
template<int dim> const size_t ug::NavierStokes::NavierStokesFullUpwind< dim >::maxNumSH = base_type::maxNumSH static
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/upwind.h
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/upwind.cpp