Plugins: ug::PCRILUTPreconditioner< TAlgebra > Class Template Reference
ug::PCRILUTPreconditioner< TAlgebra > Class Template Reference
PCRILUTPreconditioner class.
#include <pcr_ilut.h>
Public Types
typedef TAlgebra algebra_type
typedef IPreconditioner< TAlgebra >::matrix_operator_type matrix_operator_type
Matrix Operator type.
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::IPreconditioner< TAlgebra >
typedef TAlgebra algebra_type
typedef MatrixOperator< matrix_type, vector_type > matrix_operator_type
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ILinearIterator< TAlgebra::vector_type >
typedef TAlgebra::vector_type codomain_function_type
typedef TAlgebra::vector_type domain_function_type
Public Types inherited from ug::DebugWritingObject< class >
typedef TAlgebra algebra_type
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from VectorDebugWritingObject< TAlgebra::vector_type >
typedef TAlgebra::vector_type vector_type
Public Member Functions
SmartPtr< ILinearIterator< vector_type > > clone ()
PCRILUTPreconditioner (double eps, bool info)
PCRILUTPreconditioner (double eps=1e-6)
PCRILUTPreconditioner (number threshvv, number thresh_vp_pv_pp)
PCRILUTPreconditioner (number threshvv, number thresh_vp_pv_pp, bool info)
PCRILUTPreconditioner (number threshvv, number threshvp, number threshpv, number threshpp)
PCRILUTPreconditioner (number threshvv, number threshvp, number threshpv, number threshpp, bool info)
void set_info (bool info)
sets storage information output to true or false
void set_threshold (number thresh)
void set_threshold (number threshvv, number thresh_vp_pv_pp)
sets threshold for incomplete LU factorisation
void set_threshold (number threshvv, number threshvp, number threshpv, number threshpp)
sets threshold for incomplete LU factorisation
virtual bool supports_parallel () const
returns if parallel solving is supported
virtual ~PCRILUTPreconditioner ()
Public Member Functions inherited from ug::IPreconditioner< TAlgebra >
virtual bool apply (vector_type &c, const vector_type &d)
virtual bool apply_update_defect (vector_type &c, vector_type &d)
SmartPtr< MatrixOperator< matrix_type, vector_type > > approx_operator ()
SmartPtr< MatrixOperator< matrix_type, vector_type > > defect_operator ()
virtual bool init (SmartPtr< ILinearOperator< vector_type > > J, const vector_type &u)
bool init (SmartPtr< ILinearOperator< vector_type > > L)
bool init (SmartPtr< MatrixOperator< matrix_type, vector_type > > Op)
IPreconditioner ()
IPreconditioner (const IPreconditioner< TAlgebra > &parent)
IPreconditioner (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_approximation (SmartPtr< MatrixOperator< matrix_type, vector_type > > approx)
virtual ~IPreconditioner ()
Public Member Functions inherited from ILinearIterator< TAlgebra::vector_type >
virtual std::string config_string () const
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > damping ()
ILinearIterator ()
ILinearIterator (const ILinearIterator< TAlgebra::vector_type, TAlgebra::vector_type > &parent)
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > J, const TAlgebra::vector_type &u)=0
virtual bool init (SmartPtr< ILinearOperator< TAlgebra::vector_type, TAlgebra::vector_type > > L)=0
void set_damp (number factor)
void set_damp (SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > spScaling)
virtual ~ILinearIterator ()
Public Member Functions inherited from ug::DebugWritingObject< class >
SmartPtr< IDebugWriter< algebra_type > > debug_writer ()
ConstSmartPtr< IDebugWriter< algebra_type > > debug_writer () const
bool debug_writer_valid () const
DebugWritingObject ()
DebugWritingObject (const DebugWritingObject< algebra_type > &parent)
DebugWritingObject (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual void set_debug (SmartPtr< IDebugWriter< algebra_type > > spDebugWriter)
virtual ~DebugWritingObject ()
Public Member Functions inherited from VectorDebugWritingObject< TAlgebra::vector_type >
virtual void set_debug (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
SmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer ()
ConstSmartPtr< IVectorDebugWriter< vector_type > > vector_debug_writer () const
bool vector_debug_writer_valid () const
VectorDebugWritingObject ()
VectorDebugWritingObject (SmartPtr< IVectorDebugWriter< vector_type > > spDebugWriter)
void write_debug (const vector_type &vec, const char *filename)
virtual ~VectorDebugWritingObject ()
Protected Member Functions
virtual const char * name () const
virtual bool postprocess ()
virtual bool preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp)
virtual bool step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type &c, const vector_type &d)
Protected Member Functions inherited from ug::DebugWritingObject< class >
void enter_debug_writer_section (const char *secDir)
void enter_debug_writer_section (std::string secDir)
void leave_debug_writer_section ()
void write_debug (const matrix_type &mat, const char *filename)
void write_debug (const matrix_type &mat, std::string name)
Protected Member Functions inherited from VectorDebugWritingObject< TAlgebra::vector_type >
void enter_vector_debug_writer_section (const char *secDir)
void enter_vector_debug_writer_section (std::string secDir)
void leave_vector_debug_writer_section ()
void print_debugger_message (const char *msg)
void print_debugger_message (std::string msg)
virtual void write_debug (const vector_type &vec, std::string name)
Protected Attributes
matrix_type m_A
number m_eps
number m_eps_pp
number m_eps_pv
number m_eps_vp
number m_eps_vv
bool m_info
matrix_type m_L
bool m_remove_zeros
matrix_type m_U
Protected Attributes inherited from ug::IPreconditioner< TAlgebra >
bool m_bInit
bool m_bOtherApproxOperator
SmartPtr< MatrixOperator< matrix_type, vector_type > > m_spApproxOperator
SmartPtr< ILinearOperator< vector_type > > m_spDefectOperator
Protected Attributes inherited from ILinearIterator< TAlgebra::vector_type >
SmartPtr< IDamping< TAlgebra::vector_type, TAlgebra::vector_type > > m_spDamping
Protected Attributes inherited from ug::DebugWritingObject< class >
SmartPtr< IDebugWriter< algebra_type > > m_spDebugWriter
Protected Attributes inherited from VectorDebugWritingObject< TAlgebra::vector_type >
SmartPtr< IVectorDebugWriter< vector_type > > m_spVectorDebugWriter
Static Protected Attributes
static const number m_small_lower = 1e-9
static const number m_small_upper = 1e-6
Private Types
typedef matrix_type::value_type block_type
Detailed Description
template<typename TAlgebra>
class ug::PCRILUTPreconditioner< TAlgebra >
PCRILUTPreconditioner class.
Member Typedef Documentation
algebra_type
template<typename TAlgebra > typedef TAlgebra ug::PCRILUTPreconditioner< TAlgebra >::algebra_type
block_type
template<typename TAlgebra > typedef matrix_type::value_type ug::PCRILUTPreconditioner< TAlgebra >::block_type private
matrix_operator_type
template<typename TAlgebra > typedef IPreconditioner<TAlgebra>::matrix_operator_type ug::PCRILUTPreconditioner< TAlgebra >::matrix_operator_type
Matrix Operator type.
matrix_type
template<typename TAlgebra > typedef TAlgebra::matrix_type ug::PCRILUTPreconditioner< TAlgebra >::matrix_type
vector_type
template<typename TAlgebra > typedef TAlgebra::vector_type ug::PCRILUTPreconditioner< TAlgebra >::vector_type
Constructor & Destructor Documentation
PCRILUTPreconditioner() [1/6]
template<typename TAlgebra > ug::PCRILUTPreconditioner< TAlgebra >::PCRILUTPreconditioner (double eps = 1e-6) inline
References ug::PCRILUTPreconditioner< TAlgebra >::m_info.
PCRILUTPreconditioner() [2/6]
template<typename TAlgebra > ug::PCRILUTPreconditioner< TAlgebra >::PCRILUTPreconditioner (number threshvv, number thresh_vp_pv_pp) inline
References ug::PCRILUTPreconditioner< TAlgebra >::m_info, and ug::PCRILUTPreconditioner< TAlgebra >::set_threshold().
PCRILUTPreconditioner() [3/6]
template<typename TAlgebra > ug::PCRILUTPreconditioner< TAlgebra >::PCRILUTPreconditioner (number threshvv, number threshvp, number threshpv, number threshpp) inline
References ug::PCRILUTPreconditioner< TAlgebra >::m_info, and ug::PCRILUTPreconditioner< TAlgebra >::set_threshold().
PCRILUTPreconditioner() [4/6]
template<typename TAlgebra > ug::PCRILUTPreconditioner< TAlgebra >::PCRILUTPreconditioner (double eps, bool info) inline
PCRILUTPreconditioner() [5/6]
template<typename TAlgebra > ug::PCRILUTPreconditioner< TAlgebra >::PCRILUTPreconditioner (number threshvv, number thresh_vp_pv_pp, bool info) inline
References ug::PCRILUTPreconditioner< TAlgebra >::m_info, and ug::PCRILUTPreconditioner< TAlgebra >::set_threshold().
PCRILUTPreconditioner() [6/6]
template<typename TAlgebra > ug::PCRILUTPreconditioner< TAlgebra >::PCRILUTPreconditioner (number threshvv, number threshvp, number threshpv, number threshpp, bool info) inline
References ug::PCRILUTPreconditioner< TAlgebra >::m_info, and ug::PCRILUTPreconditioner< TAlgebra >::set_threshold().
~PCRILUTPreconditioner()
template<typename TAlgebra > virtual ug::PCRILUTPreconditioner< TAlgebra >::~PCRILUTPreconditioner () inline virtual
Member Function Documentation
clone()
template<typename TAlgebra > SmartPtr<ILinearIterator<vector_type> > ug::PCRILUTPreconditioner< TAlgebra >::clone () inline virtual
Implements ILinearIterator< TAlgebra::vector_type >.
References ILinearIterator< TAlgebra::vector_type >::damping(), ug::DebugWritingObject< class >::debug_writer(), ug::PCRILUTPreconditioner< TAlgebra >::m_eps, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pp, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pv, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vp, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vv, and ug::PCRILUTPreconditioner< TAlgebra >::m_info.
name()
template<typename TAlgebra > virtual const char* ug::PCRILUTPreconditioner< TAlgebra >::name () const inline protected virtual
Implements ug::IPreconditioner< TAlgebra >.
postprocess()
template<typename TAlgebra > virtual bool ug::PCRILUTPreconditioner< TAlgebra >::postprocess () inline protected virtual
Implements ug::IPreconditioner< TAlgebra >.
preprocess()
template<typename TAlgebra > virtual bool ug::PCRILUTPreconditioner< TAlgebra >::preprocess (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp) inline protected virtual
Implements ug::IPreconditioner< TAlgebra >.
References ug::BlockNorm(), CollectUniqueElements(), ug::PCRILUTPreconditioner< TAlgebra >::m_A, ug::PCRILUTPreconditioner< TAlgebra >::m_eps, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pp, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pv, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vp, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vv, ug::PCRILUTPreconditioner< TAlgebra >::m_info, ug::PCRILUTPreconditioner< TAlgebra >::m_L, ug::PCRILUTPreconditioner< TAlgebra >::m_remove_zeros, ug::PCRILUTPreconditioner< TAlgebra >::m_U, ug::MatAddSlaveRowsToMasterRowOverlap0(), ug::SetDirichletRow(), STATIC_ASSERT, UG_ASSERT, and UG_LOG.
set_info()
template<typename TAlgebra > void ug::PCRILUTPreconditioner< TAlgebra >::set_info (bool info) inline
sets storage information output to true or false
References ug::PCRILUTPreconditioner< TAlgebra >::m_info.
set_threshold() [1/3]
template<typename TAlgebra > void ug::PCRILUTPreconditioner< TAlgebra >::set_threshold (number thresh) inline
References ug::PCRILUTPreconditioner< TAlgebra >::m_eps, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pp, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pv, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vp, and ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vv.
set_threshold() [2/3]
template<typename TAlgebra > void ug::PCRILUTPreconditioner< TAlgebra >::set_threshold (number threshvv, number thresh_vp_pv_pp) inline
sets threshold for incomplete LU factorisation
References ug::PCRILUTPreconditioner< TAlgebra >::m_eps, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pp, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pv, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vp, and ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vv.
set_threshold() [3/3]
template<typename TAlgebra > void ug::PCRILUTPreconditioner< TAlgebra >::set_threshold (number threshvv, number threshvp, number threshpv, number threshpp) inline
sets threshold for incomplete LU factorisation
References ug::PCRILUTPreconditioner< TAlgebra >::m_eps, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pp, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pv, ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vp, and ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vv.
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::PCRILUTPreconditioner().
step()
template<typename TAlgebra > virtual bool ug::PCRILUTPreconditioner< TAlgebra >::step (SmartPtr< MatrixOperator< matrix_type, vector_type > > pOp, vector_type & c, const vector_type & d) inline protected virtual
Implements ug::IPreconditioner< TAlgebra >.
References ug::BlockNorm(), ParallelVector< Vector< double > >::change_storage_type(), ug::InverseMatMult(), ug::PCRILUTPreconditioner< TAlgebra >::m_L, ug::PCRILUTPreconditioner< TAlgebra >::m_small_lower, ug::PCRILUTPreconditioner< TAlgebra >::m_small_upper, ug::PCRILUTPreconditioner< TAlgebra >::m_U, ug::MatMultAdd(), ug::PST_ADDITIVE, ug::PST_CONSISTENT, ug::PST_UNIQUE, s, UG_ASSERT, and UG_LOG.
supports_parallel()
template<typename TAlgebra > virtual bool ug::PCRILUTPreconditioner< TAlgebra >::supports_parallel () const inline virtual
returns if parallel solving is supported
Implements ILinearIterator< TAlgebra::vector_type >.
Member Data Documentation
m_A
template<typename TAlgebra > matrix_type ug::PCRILUTPreconditioner< TAlgebra >::m_A protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::preprocess().
m_eps
template<typename TAlgebra > number ug::PCRILUTPreconditioner< TAlgebra >::m_eps protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::clone(), ug::PCRILUTPreconditioner< TAlgebra >::preprocess(), and ug::PCRILUTPreconditioner< TAlgebra >::set_threshold().
m_eps_pp
template<typename TAlgebra > number ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pp protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::clone(), ug::PCRILUTPreconditioner< TAlgebra >::preprocess(), and ug::PCRILUTPreconditioner< TAlgebra >::set_threshold().
m_eps_pv
template<typename TAlgebra > number ug::PCRILUTPreconditioner< TAlgebra >::m_eps_pv protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::clone(), ug::PCRILUTPreconditioner< TAlgebra >::preprocess(), and ug::PCRILUTPreconditioner< TAlgebra >::set_threshold().
m_eps_vp
template<typename TAlgebra > number ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vp protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::clone(), ug::PCRILUTPreconditioner< TAlgebra >::preprocess(), and ug::PCRILUTPreconditioner< TAlgebra >::set_threshold().
m_eps_vv
template<typename TAlgebra > number ug::PCRILUTPreconditioner< TAlgebra >::m_eps_vv protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::clone(), ug::PCRILUTPreconditioner< TAlgebra >::preprocess(), and ug::PCRILUTPreconditioner< TAlgebra >::set_threshold().
m_info
template<typename TAlgebra > bool ug::PCRILUTPreconditioner< TAlgebra >::m_info protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::clone(), ug::PCRILUTPreconditioner< TAlgebra >::PCRILUTPreconditioner(), ug::PCRILUTPreconditioner< TAlgebra >::preprocess(), and ug::PCRILUTPreconditioner< TAlgebra >::set_info().
m_L
template<typename TAlgebra > matrix_type ug::PCRILUTPreconditioner< TAlgebra >::m_L protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::preprocess(), and ug::PCRILUTPreconditioner< TAlgebra >::step().
m_remove_zeros
template<typename TAlgebra > bool ug::PCRILUTPreconditioner< TAlgebra >::m_remove_zeros protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::preprocess().
m_small_lower
template<typename TAlgebra > const number ug::PCRILUTPreconditioner< TAlgebra >::m_small_lower = 1e-9 static protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::step().
m_small_upper
template<typename TAlgebra > const number ug::PCRILUTPreconditioner< TAlgebra >::m_small_upper = 1e-6 static protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::step().
m_U
template<typename TAlgebra > matrix_type ug::PCRILUTPreconditioner< TAlgebra >::m_U protected
Referenced by ug::PCRILUTPreconditioner< TAlgebra >::preprocess(), and ug::PCRILUTPreconditioner< TAlgebra >::step().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fvcr/pcr_ilut.h