Plugins: ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain > Class Template Reference
ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain > Class Template Reference
Discretization for the Convection-Diffusion Equation in fractures.
#include <convection_diffusion_fractfv1.h>
Classes
struct RegisterLocalDiscr
auxiliary class for registering functions
Public Types
typedef ConvectionDiffusionBase< TDomain > base_type
Base class type.
typedef base_type::domain_type domain_type
domain type
typedef DegeneratedLayerManager< dim > fract_manager_type
fracture manager type
typedef base_type::position_type position_type
position type
Public Types inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
typedef SmartPtr< CplUserData< MathVector< dim >, dim > > GradExport
typedef SmartPtr< CplUserData< number, dim > > NumberExport
Public Types inherited from ug::IElemDisc< TDomain >
typedef IElemAssembleFuncs< IElemDisc< TDomain >, TDomain > assemble_base_type
typedef IElemError< TDomain > base_type
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Public Types inherited from ug::IElemError< class >
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from ug::IElemDiscBase< class >
typedef TDomain domain_type
typedef TDomain::position_type position_type
Public Types inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Public Member Functions
ConvectionDiffusionFractFV1 (const char *functions, const char *subsets)
Constructor.
void set_aperture (number val)
void set_aperture (SmartPtr< CplUserData< number, dim > > user)
void set_fract_manager (SmartPtr< fract_manager_type > fract_manager)
sets the fracture manager
void set_ortho_diffusion (number val)
void set_ortho_diffusion (SmartPtr< CplUserData< number, dim > > user)
void set_ortho_velocity (number val)
void set_ortho_velocity (SmartPtr< CplUserData< number, dim > > user)
void set_sss_manager (SmartPtr< CDSingularSourcesAndSinks< dim > > sss_mngr)
set singular sources and sinks
void set_upwind (SmartPtr< conv_shape_type > shapes)
set the upwind method along the fracture
SmartPtr< CDSingularSourcesAndSinks< dim > > sss_manager ()
get singular sources and sinks
virtual bool use_hanging () const
hanging nodes are not allowed in this discretization
Public Member Functions inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
ConvectionDiffusionBase (const char *functions, const char *subsets)
Constructor.
virtual SmartPtr< CplUserData< MathVector< dim >, dim > > gradient ()
returns the export of the gradient of associated unknown function
void set_reaction_explicit (number val)
void set_reaction_explicit (SmartPtr< CplUserData< number, dim > > user)
void set_reaction_rate_explicit (number val)
void set_reaction_rate_explicit (SmartPtr< CplUserData< number, dim > > user)
void set_source_explicit (number val)
void set_source_explicit (SmartPtr< CplUserData< number, dim > > user)
virtual SmartPtr< CplUserData< number, dim > > value ()
returns the export of the value of associated unknown function
void set_diffusion (SmartPtr< CplUserData< MathMatrix< dim, dim >, dim > > user)
sets the diffusion tensor
void set_diffusion (number val)
sets the diffusion tensor
void set_velocity (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the velocity field
void set_velocity (const std::vector< number > &vVel)
sets the velocity field
void set_flux (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the flux
void set_flux (const std::vector< number > &vVel)
sets the flux
void set_reaction_rate (SmartPtr< CplUserData< number, dim > > user)
sets the reaction rate
void set_reaction_rate (number val)
sets the reaction rate
void set_reaction (SmartPtr< CplUserData< number, dim > > user)
sets the reaction
void set_reaction (number val)
sets the reaction
void set_source (SmartPtr< CplUserData< number, dim > > user)
sets the source / sink term
void set_source (number val)
sets the source / sink term
void set_vector_source (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the vector source term
void set_vector_source (const std::vector< number > &vVel)
sets the vector source term
void set_mass_scale (SmartPtr< CplUserData< number, dim > > user)
sets mass scale
void set_mass_scale (number val)
sets mass scale
void set_mass (SmartPtr< CplUserData< number, dim > > user)
sets mass
void set_mass (number val)
sets mass
Public Member Functions inherited from ug::IElemDisc< TDomain >
void add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier)
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > & get_elem_modifier ()
IElemDisc (const char *functions, const char *subsets)
IElemDisc (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
virtual void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_fsh_elem_loop ()
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_timestep (number future_time, const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void fsh_timestep (number time, VectorProxyBase *u)
virtual void fsh_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemAssembleFuncs ()
virtual void post_assemble_loop ()
virtual void prep_assemble_loop ()
virtual void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
virtual void prep_elem_loop (const ReferenceObjectID roid, const int si)
virtual void prep_timestep (number future_time, number time, VectorProxyBase *u)
virtual void prep_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemAssembleFuncs ()
Public Member Functions inherited from ug::IElemError< class >
IElemError (const char *functions, const char *subsets)
IElemError (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from ug::IElemDiscBase< class >
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
void check_setup (bool bNonRegularGrid)
void clear_imports ()
SmartPtr< TDomain > domain ()
ConstSmartPtr< TDomain > domain () const
const FunctionGroup & function_group () const
ConstSmartPtr< FunctionPattern > function_pattern () const
IDataImport< dim > & get_import (size_t i)
IElemDiscBase (const char *functions="", const char *subsets="")
IElemDiscBase (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
bool is_time_dependent () const
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
const FunctionIndexMapping & map () const
number mass_scale () const
number mass_scale () const
number mass_scale (const size_t timePoint) const
number mass_scale (const size_t timePoint) const
const std::vector< number > & mass_scales () const
const std::vector< number > & mass_scales () const
size_t num_fct () const
size_t num_imports () const
size_t num_subsets () const
void register_import (IDataImport< dim > &Imp)
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_functions (const std::string &functions)
void set_functions (const std::vector< std::string > &functions)
void set_stationary ()
void set_stationary (bool bStationaryForced=true)
void set_subsets (const std::string &subsets)
void set_subsets (const std::vector< std::string > &subsets)
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
void set_time_independent ()
void set_time_point (const size_t timePoint)
number stiff_scale () const
number stiff_scale () const
number stiff_scale (const size_t timePoint) const
number stiff_scale (const size_t timePoint) const
const std::vector< number > & stiff_scales () const
const std::vector< number > & stiff_scales () const
TDomain::subset_handler_type & subset_handler ()
const TDomain::subset_handler_type & subset_handler () const
const std::vector< std::string > & symb_fcts () const
const std::vector< std::string > & symb_subsets () const
number time () const
size_t time_point () const
virtual int type () const
virtual ~IElemDiscBase ()
Public Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
virtual void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_err_est_elem_loop ()
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
virtual void fsh_err_est_elem_loop ()
IElemEstimatorFuncs ()
virtual void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemEstimatorFuncs ()
Static Public Attributes
static const int dim = base_type::dim
World ('full') dimension.
static const int low_dim = dim - 1
Manifold ('low') dimension.
Static Public Attributes inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::IElemDisc< TDomain >
static const int dim
Static Public Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Static Public Attributes inherited from ug::IElemError< class >
static const int dim
Static Public Attributes inherited from ug::IElemDiscBase< class >
static const int dim
Static Public Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Protected Attributes
DataImport< number, dim > m_imAperture
the fracture width (constant per element)
DataImport< number, dim > m_imOrthoDiffusion
diffusion through the fracture-bulk interface
DataImport< number, dim > m_imOrthoFlux
flux through the fracture-bulk interface
DataImport< number, dim > m_imOrthoVectorSource
vector through the fracture-bulk interface
DataImport< number, dim > m_imOrthoVelocity
convection velocity through the fracture-bulk interface
SmartPtr< conv_shape_type > m_spConvShape
method to compute the upwind shapes
SmartPtr< fract_manager_type > m_spFractManager
degenerated fracture manager (may be SPNULL)
Protected Attributes inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
SmartPtr< DataExport< MathVector< dim >, dim > > m_exGrad
Export for the gradient of concentration.
SmartPtr< DataExport< number, dim > > m_exValue
Export for the concentration.
DataImport< MathMatrix< dim, dim >, dim > m_imDiffusion
Data import for Diffusion.
DataImport< MathVector< dim >, dim > m_imFlux
Data import for the Flux.
DataImport< number, dim > m_imMass
Data import for the mass scale.
DataImport< number, dim > m_imMassScale
Data import for the mass scale.
DataImport< number, dim > m_imReaction
Data import for the reaction term.
DataImport< number, dim > m_imReactionExpl
Data import for the reaction term explicit.
DataImport< number, dim > m_imReactionRate
Data import for the reaction term.
DataImport< number, dim > m_imReactionRateExpl
Data import for the reaction_rate term explicit.
DataImport< number, dim > m_imSource
Data import for the right-hand side (volume)
DataImport< number, dim > m_imSourceExpl
Data import for the source term explicit.
DataImport< MathVector< dim >, dim > m_imVectorSource
Data import for the right-hand side (vector)
DataImport< MathVector< dim >, dim > m_imVelocity
Data import for the Velocity field.
Protected Attributes inherited from ug::IElemDisc< TDomain >
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > m_spElemModifier
Protected Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
Protected Attributes inherited from ug::IElemDiscBase< class >
bool m_bStationaryForced
FunctionGroup m_fctGrp
FunctionIndexMapping m_fctIndexMap
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
ConstSmartPtr< FunctionPattern > m_spFctPattern
size_t m_timePoint
std::vector< std::string > m_vFct
std::vector< IDataImport< dim > * > m_vIImport
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
std::vector< std::string > m_vSubset
Protected Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
Private Types
typedef IConvectionShapes< dim > conv_shape_type
convection shapes type (for the upwind)
typedef fract_manager_type::side_type side_type
type of the sides of elements (als low-dimensional fracture elements)
typedef DimFV1Geometry< low_dim, dim > TFractFVGeom
FV geometry for the fractures.
typedef ConvectionDiffusionFractFV1< TDomain > this_type
Own type.
Private Member Functions
template<typename TElem >
void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const position_type vCornerCoords[])
assembles the stiffness part of the local defect
template<typename TElem >
void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const position_type vCornerCoords[])
assembles the stiffness part of the local defect explicit reaction, reaction_rate and source
template<typename TElem >
void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const position_type vCornerCoords[])
assembles the mass part of the local defect
template<typename TElem >
void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const position_type vCornerCoords[])
assembles the local stiffness matrix using a finite volume scheme
template<typename TElem >
void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const position_type vCornerCoords[])
assembles the local mass matrix using a finite volume scheme
template<typename TElem >
void add_rhs_elem (LocalVector &d, GridObject *elem, const position_type vCornerCoords[])
assembles the local right hand side
template<typename TElem >
void add_sss_def_elem (LocalVector &d, const LocalVector &u, TElem *pElem, size_t co, number flux)
assembles a singular source or sink in the defect
template<typename TElem >
void add_sss_jac_elem (LocalMatrix &J, const LocalVector &u, TElem *pElem, size_t co, number flux)
assembles a singular source or sink in the jacobian
template<typename TElem >
void fract_add_def_A_elem (LocalVector &d, const LocalVector &u, TElem *elem, const position_type vCornerCoords[])
computes the stiffness part of the local defect on a fracture element
template<typename TElem >
void fract_add_def_A_expl_elem (LocalVector &d, const LocalVector &u, TElem *elem, const position_type vCornerCoords[])
computes the stiffness part of the local defect on a fracture element
template<typename TElem >
void fract_add_jac_A_elem (LocalMatrix &J, const LocalVector &u, TElem *elem, const position_type vCornerCoords[])
computes the local stiffness matrix on a fracture element
template<typename TElem >
void fract_add_rhs_elem (LocalVector &b, TElem *elem, const position_type vCornerCoords[])
computes the right-hand side due to the sources on a fracture element
template<typename TElem >
void fract_bulk_add_def_A_elem (LocalVector &d, const LocalVector &u, TElem *elem, const position_type vCornerCoords[])
computes the stiffness fracture-bulk interaction terms of the local defect on a fracture element
template<typename TElem >
void fract_bulk_add_def_A_expl_elem (LocalVector &d, const LocalVector &u, TElem *elem, const position_type vCornerCoords[])
computes the stiffness fracture-bulk interaction terms of the local defect on a fracture element
template<typename TElem >
void fract_bulk_add_jac_A_elem (LocalMatrix &J, const LocalVector &u, TElem *elem, const position_type vCornerCoords[])
computes the local stiffness matrix of the fracture-bulk interaction terms on a fracture element
template<typename TElem >
void fract_bulk_add_rhs_elem (LocalVector &b, TElem *elem, const position_type vCornerCoords[])
computes the fracture-bulk interaction terms of the local rhs on a fracture element
template<typename TElem >
void fsh_elem_loop ()
finishes the loop over all elements
const conv_shape_type & get_updated_conv_shapes (bool computeDeriv)
returns the updated convection shapes
template<typename TElem >
void lin_def_diffusion (const LocalVector &u, std::vector< std::vector< MathMatrix< dim, dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t. to the fracture diffusion
template<typename TElem >
void lin_def_flux (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t. to the fracture flux
template<typename TElem >
void lin_def_mass (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the mass scale term
template<typename TElem >
void lin_def_mass_scale (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the mass scale term
template<typename TElem >
void lin_def_ortho_diffusion (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t. to the orthogonal diffusion
template<typename TElem >
void lin_def_ortho_flux (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t. to the orthogonal flux
template<typename TElem >
void lin_def_ortho_vector_source (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the vector source term
template<typename TElem >
void lin_def_ortho_velocity (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t. to the orthogonal velocity
template<typename TElem >
void lin_def_reaction (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t. to the reaction
template<typename TElem >
void lin_def_reaction_rate (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t. to the reaction
template<typename TElem >
void lin_def_source (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the source term
template<typename TElem >
void lin_def_vector_source (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the vector source term
template<typename TElem >
void lin_def_velocity (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t. to the fracture velocity
template<typename TElem >
void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const position_type vCornerCoords[])
prepares the element for assembling
template<typename TElem >
void prep_elem_loop (const ReferenceObjectID roid, const int si)
prepares the loop over all elements
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegularGrid)
check the grid and the type of trial space for each function used
void register_all_funcs ()
registers the interface function
template<typename TElem >
void register_func ()
registers the interface function for one element type
Private Attributes
size_t m_assCo [2 *maxFractSideCorners]
correspondence of the corners of the sides
side_type * m_innerFractSide
inner side of the fracture element
size_t m_innerFractSideIdx
index of the inner side in the ref. elem.
size_t m_innerSideCo [maxFractSideCorners]
inner side corner idx -> elem. corner idx
size_t m_numFractCo
number of corners of the fracture side
side_type * m_outerFractSide
outer side of the fracture element
size_t m_outerFractSideIdx
index of the outer side in the ref. elem.
size_t m_outerSideCo [maxFractSideCorners]
outer side corner idx -> elem. corner idx
TFractFVGeom * m_pFractGeo
FV geometry object of fracture elements.
SmartPtr< CDSingularSourcesAndSinks< dim > > m_sss_mngr
Static Private Attributes
static const size_t _C_ = 0
abbreviation for local function: brine mass fraction
static const size_t maxFractSideCorners = fract_manager_type::maxLayerSideCorners
max. number of corners of non-degenerated sides
Additional Inherited Members
Protected Member Functions inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
void init_imports ()
Protected Member Functions inherited from ug::IElemDisc< TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void set_default_add_fct ()
Protected Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_add_def_A_elem_fct (ReferenceObjectID id)
void remove_add_def_A_expl_elem_fct (ReferenceObjectID id)
void remove_add_def_M_elem_fct (ReferenceObjectID id)
void remove_add_jac_A_elem_fct (ReferenceObjectID id)
void remove_add_jac_M_elem_fct (ReferenceObjectID id)
void remove_add_rhs_elem_fct (ReferenceObjectID id)
void remove_fsh_elem_loop_fct (ReferenceObjectID id)
void remove_fsh_timestep_elem_fct (ReferenceObjectID id)
void remove_fsh_timestep_fct (size_t algebra_id)
void remove_prep_elem_fct (ReferenceObjectID id)
void remove_prep_elem_loop_fct (ReferenceObjectID id)
void remove_prep_timestep_elem_fct (ReferenceObjectID id)
void remove_prep_timestep_fct (size_t algebra_id)
void set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_fct (size_t algebra_id, TAssFunc func)
void set_prep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_fct (size_t algebra_id, TAssFunc func)
Protected Member Functions inherited from ug::IElemError< class >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
Protected Member Functions inherited from ug::IElemDiscBase< class >
virtual void approximation_space_changed ()
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
void update_function_index_mapping ()
Protected Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
Detailed Description
template<typename TDomain>
class ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >
Discretization for the Convection-Diffusion Equation in fractures.
This class implements the IElemDisc interface to provide element local assemblings for the convection diffusion equation in the low-dimensional fractures. using the degenerated elements. This module is complementary to ConvectionDiffusionFV1. Cf. ConvectionDiffusionBase base class for the problem setting.
See also
ConvectionDiffusionBase for the problem settings
ConvectionDiffusionFV1 for the FV discretization in the full-dim. domain
Template Parameters
TDomain Domain
Member Typedef Documentation
base_type
template<typename TDomain > typedef ConvectionDiffusionBase<TDomain> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::base_type
Base class type.
conv_shape_type
template<typename TDomain > typedef IConvectionShapes<dim> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::conv_shape_type private
convection shapes type (for the upwind)
domain_type
template<typename TDomain > typedef base_type::domain_type ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::domain_type
domain type
fract_manager_type
template<typename TDomain > typedef DegeneratedLayerManager<dim> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_manager_type
fracture manager type
position_type
template<typename TDomain > typedef base_type::position_type ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::position_type
position type
side_type
template<typename TDomain > typedef fract_manager_type::side_type ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::side_type private
type of the sides of elements (als low-dimensional fracture elements)
TFractFVGeom
template<typename TDomain > typedef DimFV1Geometry<low_dim, dim> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::TFractFVGeom private
FV geometry for the fractures.
this_type
template<typename TDomain > typedef ConvectionDiffusionFractFV1<TDomain> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::this_type private
Own type.
Constructor & Destructor Documentation
ConvectionDiffusionFractFV1()
template<typename TDomain > ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::ConvectionDiffusionFractFV1 (const char * functions, const char * subsets)
Constructor.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imAperture, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imOrthoDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imOrthoFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imOrthoVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imOrthoVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::register_all_funcs(), ug::IElemDiscBase< class >::register_import(), and ug::IDataImport< dim >::set_comp_lin_defect().
Member Function Documentation
add_def_A_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_def_A_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const position_type vCornerCoords[]) private
assembles the stiffness part of the local defect
computes the stiffness part of the local defect
Parameters
d the local defect to update
u current approximation of the solution
elem grid element
vCornerCoords corner coordinates of the grid element
add_def_A_expl_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_def_A_expl_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const position_type vCornerCoords[]) private
assembles the stiffness part of the local defect explicit reaction, reaction_rate and source
computes the stiffness part of the local defect
Parameters
d the local defect to update
u current approximation of the solution
elem grid element
vCornerCoords corner coordinates of the grid element
add_def_M_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_def_M_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const position_type vCornerCoords[]) private
assembles the mass part of the local defect
computes the mass part of the defect of a time-dependent problem
Parameters
d the local defect to update
u current approximation of the solution
elem grid element
vCornerCoords corner coordinates of the grid element
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
add_jac_A_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_jac_A_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const position_type vCornerCoords[]) private
assembles the local stiffness matrix using a finite volume scheme
computes the local stiffness matrix
Parameters
J the local matrix to update
u current approximation of the solution
elem grid element
vCornerCoords corner coordinates of the grid element
add_jac_M_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_jac_M_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const position_type vCornerCoords[]) private
assembles the local mass matrix using a finite volume scheme
computes the mass matrix of a time-dependent problem
Parameters
J the local matrix to update
u current approximation of the solution
elem grid element
vCornerCoords corner coordinates of the grid element
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
add_rhs_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_rhs_elem (LocalVector & d, GridObject * elem, const position_type vCornerCoords[]) private
assembles the local right hand side
computes the right-hand side due to the sources
Parameters
d the right-hand side to update
elem grid element
vCornerCoords corner coordinates of the grid element
add_sss_def_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_sss_def_elem (LocalVector & d, const LocalVector & u, TElem * pElem, size_t co, number flux) inline private
assembles a singular source or sink in the defect
Parameters
d the defect to update
u current solution
pElem the element
co corner for the source/sink
flux flux through the source/sink (premultiplied by the length for lines)
add_sss_jac_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_sss_jac_elem (LocalMatrix & J, const LocalVector & u, TElem * pElem, size_t co, number flux) inline private
assembles a singular source or sink in the jacobian
Parameters
J the matrix to update
u current solution
pElem the element
co corner for the source/sink
flux flux through the source/sink (premultiplied by the length for lines)
fract_add_def_A_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_add_def_A_elem (LocalVector & d, const LocalVector & u, TElem * pElem, const position_type vCornerCoords[]) inline private
computes the stiffness part of the local defect on a fracture element
Parameters
d the local defect to update
u current approximation of the solution
pElem grid element
vCornerCoords corner coordinates of the grid element
References ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::from(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::global_grad(), grid(), ug::MatVecMult(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::normal(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::to(), ug::VecDot(), ug::VecScaleAppend(), ug::VecSet(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
fract_add_def_A_expl_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_add_def_A_expl_elem (LocalVector & d, const LocalVector & u, TElem * pElem, const position_type vCornerCoords[]) inline private
computes the stiffness part of the local defect on a fracture element
Parameters
d the local defect to update
u current approximation of the solution
pElem grid element
vCornerCoords corner coordinates of the grid element
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
fract_add_jac_A_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_add_jac_A_elem (LocalMatrix & J, const LocalVector & u, TElem * pElem, const position_type vCornerCoords[]) inline private
computes the local stiffness matrix on a fracture element
Parameters
J the local matrix to update
u current approximation of the solution
pElem grid element
vCornerCoords corner coordinates of the grid element
References ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::from(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::global_grad(), grid(), ug::MatVecMult(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::normal(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::to(), ug::VecDot(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
fract_add_rhs_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_add_rhs_elem (LocalVector & d, TElem * pElem, const position_type vCornerCoords[]) inline private
computes the right-hand side due to the sources on a fracture element
Parameters
d the local defect to update
pElem grid element
vCornerCoords corner coordinates of the grid element
References ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::from(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::normal(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::to(), ug::VecDot(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
fract_bulk_add_def_A_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_bulk_add_def_A_elem (LocalVector & d, const LocalVector & u, TElem * pElem, const position_type vCornerCoords[]) inline private
computes the stiffness fracture-bulk interaction terms of the local defect on a fracture element
Parameters
d the local defect to update
u current approximation of the solution
pElem grid element
vCornerCoords corner coordinates of the grid element
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
fract_bulk_add_def_A_expl_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_bulk_add_def_A_expl_elem (LocalVector & d, const LocalVector & u, TElem * pElem, const position_type vCornerCoords[]) inline private
computes the stiffness fracture-bulk interaction terms of the local defect on a fracture element
Parameters
d the local defect to update
u current approximation of the solution
pElem grid element
vCornerCoords corner coordinates of the grid element
fract_bulk_add_jac_A_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_bulk_add_jac_A_elem (LocalMatrix & J, const LocalVector & u, TElem * pElem, const position_type vCornerCoords[]) inline private
computes the local stiffness matrix of the fracture-bulk interaction terms on a fracture element
Parameters
J the local matrix to update
u current approximation of the solution
pElem grid element
vCornerCoords corner coordinates of the grid element
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), s, and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
fract_bulk_add_rhs_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_bulk_add_rhs_elem (LocalVector & d, TElem * pElem, const position_type vCornerCoords[]) inline private
computes the fracture-bulk interaction terms of the local rhs on a fracture element
Parameters
d the local defect to update
pElem grid element
vCornerCoords corner coordinates of the grid element
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
fsh_elem_loop()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fsh_elem_loop private virtual
finishes the loop over all elements
Reimplemented from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >.
get_updated_conv_shapes()
template<typename TDomain > const ConvectionDiffusionFractFV1< TDomain >::conv_shape_type & ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::get_updated_conv_shapes (bool computeDeriv) private
returns the updated convection shapes
computes and returns the upwind shapes for the given velocity
Parameters
computeDeriv whether to compute the derivatives of the shapes
References UG_LOG.
lin_def_diffusion()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_diffusion (const LocalVector & u, std::vector< std::vector< MathMatrix< dim, dim > > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t. to the fracture diffusion
computes the linearized defect w.r.t to the fracture diffusion
References ug::IConvectionShapes< dim >::D_diffusion(), dim, ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::from(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::global_grad(), ug::MatAdd(), ug::IConvectionShapes< dim >::non_zero_deriv_diffusion(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::normal(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::num_sh(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::to(), ug::VecScaleAppend(), and ug::VecSet().
lin_def_flux()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_flux (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t. to the fracture flux
computes the linearized defect w.r.t to the fracture flux
References ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::from(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::normal(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::to().
lin_def_mass()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_mass (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t to the mass scale term
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
lin_def_mass_scale()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_mass_scale (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t to the mass scale term
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
lin_def_ortho_diffusion()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_ortho_diffusion (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t. to the orthogonal diffusion
computes the linearized defect w.r.t to the orthogonal diffusion
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
lin_def_ortho_flux()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_ortho_flux (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t. to the orthogonal flux
computes the linearized defect w.r.t to the orthogonal flux
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
lin_def_ortho_vector_source()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_ortho_vector_source (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t to the vector source term
computes the linearized defect w.r.t to the orthogonal flux
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
lin_def_ortho_velocity()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_ortho_velocity (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t. to the orthogonal velocity
computes the linearized defect w.r.t to the orthogonal velocity
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
lin_def_reaction()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_reaction (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t. to the reaction
computes the linearized defect w.r.t to the reaction source
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
lin_def_reaction_rate()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_reaction_rate (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t. to the reaction
computes the linearized defect w.r.t to the reaction rate
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
lin_def_source()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_source (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t to the source term
computes the linearized defect w.r.t to the source
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
lin_def_vector_source()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_vector_source (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t to the vector source term
computes the linearized defect w.r.t to the fracture flux
References ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::from(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::normal(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::to().
lin_def_velocity()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_velocity (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) private
computes the linearized defect w.r.t. to the fracture velocity
computes the linearized defect w.r.t to the fracture velocity
References ug::IConvectionShapes< dim >::D_vel(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::from(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::num_sh(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::to(), ug::VecScaleAppend(), and ug::VecSet().
prep_elem()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::prep_elem (const LocalVector & u, GridObject * elem, const ReferenceObjectID roid, const position_type vCornerCoords[]) private
prepares the element for assembling
Parameters
u local solution at the dofs associated with elem
elem element to prepare
vCornerCoords coordinates of the corners of the element
References dim, ug::Provider< class >::get(), ug::DimReferenceMapping< TDim, TWorldDim >::local_to_global(), subset_handler(), UG_CATCH_THROW, UG_THROW, and ug::DimReferenceMapping< TDim, TWorldDim >::update().
prep_elem_loop()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::prep_elem_loop (const ReferenceObjectID roid, const int si) private
prepares the loop over all elements
prepares the loop over the elements: checks whether the parameters are set, ...
This method prepares the loop over all elements. It resizes the Position array for the corner coordinates and schedules the local ip positions at the data imports.
Parameters
roid only elements with this roid are looped over
si and only in this subdomain
References ug::GeomProvider< class >::get(), ug::LFEID::LAGRANGE, and UG_THROW.
prepare_setting()
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::prepare_setting (const std::vector< LFEID > & vLfeID, bool bNonRegularGrid) private virtual
check the grid and the type of trial space for each function used
checks the grid and the shape functions
Implements ug::IElemDiscBase< class >.
References dim, ug::LFEID::LAGRANGE, and UG_THROW.
register_all_funcs()
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::register_all_funcs private
registers the interface function
registers the interface functions for all types of the elements
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::ConvectionDiffusionFractFV1().
register_func()
template<typename TDomain > template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::register_func private
registers the interface function for one element type
registers the local assembler functions for a given element
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::RegisterLocalDiscr::operator()().
set_aperture() [1/2]
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_aperture (number val) inline
References make_sp(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_aperture().
set_aperture() [2/2]
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_aperture (SmartPtr< CplUserData< number, dim > > user) inline
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imAperture, and DataImport< number, dim >::set_data().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_aperture().
set_fract_manager()
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_fract_manager (SmartPtr< fract_manager_type > fract_manager) inline
sets the fracture manager
This function sets the fracture manager object to recognize the fractures.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_spFractManager.
set_ortho_diffusion() [1/2]
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_ortho_diffusion (number val) inline
References make_sp(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_ortho_diffusion().
set_ortho_diffusion() [2/2]
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_ortho_diffusion (SmartPtr< CplUserData< number, dim > > user) inline
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imOrthoDiffusion, and DataImport< number, dim >::set_data().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_ortho_diffusion().
set_ortho_velocity() [1/2]
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_ortho_velocity (number val) inline
References make_sp(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_ortho_velocity().
set_ortho_velocity() [2/2]
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_ortho_velocity (SmartPtr< CplUserData< number, dim > > user) inline
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imOrthoVelocity, and DataImport< number, dim >::set_data().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_ortho_velocity().
set_sss_manager()
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_sss_manager (SmartPtr< CDSingularSourcesAndSinks< dim > > sss_mngr) inline
set singular sources and sinks
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_sss_mngr.
set_upwind()
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_upwind (SmartPtr< conv_shape_type > shapes) inline
set the upwind method along the fracture
This method sets the upwind method used to upwind the convection along the fracture.
Parameters
shapes upwind method
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_spConvShape.
sss_manager()
template<typename TDomain > SmartPtr<CDSingularSourcesAndSinks<dim> > ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::sss_manager () inline
get singular sources and sinks
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_sss_mngr.
use_hanging()
template<typename TDomain > virtual bool ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::use_hanging () const inline virtual
hanging nodes are not allowed in this discretization
Reimplemented from ug::IElemDiscBase< class >.
Member Data Documentation
_C_
template<typename TDomain > const size_t ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::_C_ = 0 static private
abbreviation for local function: brine mass fraction
dim
template<typename TDomain > const int ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::dim = base_type::dim static
World ('full') dimension.
low_dim
template<typename TDomain > const int ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::low_dim = dim - 1 static
Manifold ('low') dimension.
m_assCo
template<typename TDomain > size_t ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_assCo[2 *maxFractSideCorners] private
correspondence of the corners of the sides
m_imAperture
template<typename TDomain > DataImport<number, dim> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imAperture protected
the fracture width (constant per element)
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::ConvectionDiffusionFractFV1(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_aperture().
m_imOrthoDiffusion
template<typename TDomain > DataImport<number, dim> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imOrthoDiffusion protected
diffusion through the fracture-bulk interface
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::ConvectionDiffusionFractFV1(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_ortho_diffusion().
m_imOrthoFlux
template<typename TDomain > DataImport<number, dim> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imOrthoFlux protected
flux through the fracture-bulk interface
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::ConvectionDiffusionFractFV1().
m_imOrthoVectorSource
template<typename TDomain > DataImport<number, dim> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imOrthoVectorSource protected
vector through the fracture-bulk interface
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::ConvectionDiffusionFractFV1().
m_imOrthoVelocity
template<typename TDomain > DataImport<number, dim> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_imOrthoVelocity protected
convection velocity through the fracture-bulk interface
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::ConvectionDiffusionFractFV1(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_ortho_velocity().
m_innerFractSide
template<typename TDomain > side_type* ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_innerFractSide private
inner side of the fracture element
m_innerFractSideIdx
template<typename TDomain > size_t ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_innerFractSideIdx private
index of the inner side in the ref. elem.
m_innerSideCo
template<typename TDomain > size_t ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_innerSideCo[maxFractSideCorners] private
inner side corner idx -> elem. corner idx
m_numFractCo
template<typename TDomain > size_t ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_numFractCo private
number of corners of the fracture side
m_outerFractSide
template<typename TDomain > side_type* ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_outerFractSide private
outer side of the fracture element
m_outerFractSideIdx
template<typename TDomain > size_t ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_outerFractSideIdx private
index of the outer side in the ref. elem.
m_outerSideCo
template<typename TDomain > size_t ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_outerSideCo[maxFractSideCorners] private
outer side corner idx -> elem. corner idx
m_pFractGeo
template<typename TDomain > TFractFVGeom* ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_pFractGeo private
FV geometry object of fracture elements.
m_spConvShape
template<typename TDomain > SmartPtr<conv_shape_type> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_spConvShape protected
method to compute the upwind shapes
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_upwind().
m_spFractManager
template<typename TDomain > SmartPtr<fract_manager_type> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_spFractManager protected
degenerated fracture manager (may be SPNULL)
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_fract_manager().
m_sss_mngr
template<typename TDomain > SmartPtr<CDSingularSourcesAndSinks<dim> > ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::m_sss_mngr private
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::set_sss_manager(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::sss_manager().
maxFractSideCorners
template<typename TDomain > const size_t ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::maxFractSideCorners = fract_manager_type::maxLayerSideCorners static private
max. number of corners of non-degenerated sides
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/ConvectionDiffusion/fractfv1/convection_diffusion_fractfv1.h
/home/runner/work/docs/docs/ug4/plugins/ConvectionDiffusion/fractfv1/convection_diffusion_fractfv1.cpp