Plugins: ug::NavierStokes::VariableBoxFilter< TGridFunction > Class Template Reference
ug::NavierStokes::VariableBoxFilter< TGridFunction > Class Template Reference
#include <filter.h>
Public Types
typedef PeriodicAttachmentAccessor< side_type, ANumber > aSideNumber
typedef PeriodicAttachmentAccessor< vertex_type, ANumber > aVertexNumber
typedef FilterImplBaseClass< VariableBoxFilter< TGridFunction >, TGridFunction > base_type
typedef TGridFunction::domain_type domain_type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
typedef TGridFunction::template dim_traits< dim >::const_iterator ElemIterator
element iterator
typedef domain_type::grid_type grid_type
typedef domain_type::position_accessor_type position_accessor_type
typedef elem_type::side side_type
typedef TGridFunction::template traits< side_type >::const_iterator SideIterator
side iterator
typedef Vertex vertex_type
typedef TGridFunction::template traits< vertex_type >::const_iterator VertexIterator
vertex iterator
Public Types inherited from ug::NavierStokes::FilterImplBaseClass< VariableBoxFilter< TGridFunction >, TGridFunction >
typedef TGridFunction::domain_type domain_type
domain type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef domain_type::grid_type grid_type
grid type
typedef elem_type::side side_type
side type
typedef FilterBaseClass< TGridFunction >::type0 type0
typedef FilterBaseClass< TGridFunction >::type1 type1
typedef FilterBaseClass< TGridFunction >::type2 type2
typedef Vertex vertex_type
Public Types inherited from ug::NavierStokes::FilterBaseClass< TGridFunction >
typedef TGridFunction::domain_type domain_type
domain type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef domain_type::grid_type grid_type
grid type
typedef elem_type::side side_type
side type
typedef MathVector< dim > type0
typedef number type1
typedef MathSymmetricMatrix< dim > type2
typedef Vertex vertex_type
Public Member Functions
void add_wall (WallObject< TGridFunction > w)
template<typename VType >
void apply_filter (PeriodicAttachmentAccessor< side_type, Attachment< VType > > &aaUHat, SmartPtr< TGridFunction > u, PeriodicAttachmentAccessor< side_type, Attachment< VType > > &aaU)
template<typename VType >
void apply_filter (PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > &aaUHat, SmartPtr< TGridFunction > u)
template<typename VType >
void apply_filter (PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > &aaUHat, SmartPtr< TGridFunction > u, PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > &aaU)
template<typename VType , typename TElem >
void check_volume_sizes (PeriodicAttachmentAccessor< TElem, Attachment< VType > > &acUHat, SmartPtr< TGridFunction > u)
number compute_average_element_size (SmartPtr< TGridFunction > u)
template<typename TElem >
void init_width (number width)
template<typename TElem >
number max_width (number width)
VariableBoxFilter (SmartPtr< TGridFunction > u, SmartPtr< TGridFunction > fwidth, bool initWidth=false)
number width (side_type *side)
number width (vertex_type *vrt)
~VariableBoxFilter ()
Public Member Functions inherited from ug::NavierStokes::FilterImplBaseClass< VariableBoxFilter< TGridFunction >, TGridFunction >
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type0 > > &aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type0 > > &aaU)
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type0 > > &aaUHat, SmartPtr< TGridFunction > u)
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type1 > > &aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type1 > > &aaU)
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type2 > > &aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type2 > > &aaU)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > &aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > &aaU)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > &aaUHat, SmartPtr< TGridFunction > u)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type1 > > &aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type1 > > &aaU)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type2 > > &aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type2 > > &aaU)
void apply (SmartPtr< TGridFunction > u)
void apply_ (SmartPtr< TGridFunction > u)
void assignVal (MathSymmetricMatrix< 2 > &v, size_t ind, number value)
void assignVal (MathSymmetricMatrix< 3 > &v, size_t ind, number value)
void assignVal (MathVector< 2 > &v, size_t ind, number value)
void assignVal (MathVector< 3 > &v, size_t ind, number value)
void assignVal (number &v, size_t ind, number value)
void copyWallData (PeriodicAttachmentAccessor< TElem, Attachment< VType > > &acUHat, PeriodicAttachmentAccessor< TElem, Attachment< VType > > &acU, SmartPtr< TGridFunction > u, std::vector< WallObject< TGridFunction > > walls)
void copyWallData (PeriodicAttachmentAccessor< TElem, Attachment< VType > > &acUHat, SmartPtr< TGridFunction > u, std::vector< WallObject< TGridFunction > > walls)
Public Member Functions inherited from ug::NavierStokes::FilterBaseClass< TGridFunction >
virtual void compute_filterwidth ()
FilterBaseClass ()
virtual ~FilterBaseClass ()
Static Public Attributes
static const size_t dim = TGridFunction::dim
Static Public Attributes inherited from ug::NavierStokes::FilterImplBaseClass< VariableBoxFilter< TGridFunction >, TGridFunction >
static const size_t dim
dimension
Static Public Attributes inherited from ug::NavierStokes::FilterBaseClass< TGridFunction >
static const size_t dim = TGridFunction::dim
dimension
Private Member Functions
template<typename VType >
void collectSides (PeriodicAttachmentAccessor< side_type, Attachment< VType > > &acUHat, PeriodicAttachmentAccessor< side_type, Attachment< number > > &acVolume, std::vector< MathVector< dim > > &coord, VType values[DimFV1Geometry< dim >::maxNumSCV], number volumes[DimFV1Geometry< dim >::maxNumSCV], std::vector< side_type * > &sides)
Private Attributes
aSideNumber m_acSideVolume
aVertexNumber m_acVertexVolume
ANumber m_aSideVolume
ANumber m_aVertexVolume
number m_maxwidth
position_accessor_type m_posAcc
SmartPtr< TGridFunction > m_uInfo
std::vector< WallObject< TGridFunction > > m_walls
SmartPtr< TGridFunction > m_width
Additional Inherited Members
Protected Member Functions inherited from ug::NavierStokes::FilterImplBaseClass< VariableBoxFilter< TGridFunction >, TGridFunction >
VariableBoxFilter< TGridFunction > & getImpl ()
access to implementation
const VariableBoxFilter< TGridFunction > & getImpl () const
const access to implementation
Member Typedef Documentation
aSideNumber
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<side_type,ANumber > ug::NavierStokes::VariableBoxFilter< TGridFunction >::aSideNumber
aVertexNumber
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<vertex_type,ANumber > ug::NavierStokes::VariableBoxFilter< TGridFunction >::aVertexNumber
base_type
template<typename TGridFunction > typedef FilterImplBaseClass<VariableBoxFilter<TGridFunction>,TGridFunction> ug::NavierStokes::VariableBoxFilter< TGridFunction >::base_type
domain_type
template<typename TGridFunction > typedef TGridFunction::domain_type ug::NavierStokes::VariableBoxFilter< TGridFunction >::domain_type
elem_type
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::grid_base_object ug::NavierStokes::VariableBoxFilter< TGridFunction >::elem_type
ElemIterator
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::const_iterator ug::NavierStokes::VariableBoxFilter< TGridFunction >::ElemIterator
element iterator
grid_type
template<typename TGridFunction > typedef domain_type::grid_type ug::NavierStokes::VariableBoxFilter< TGridFunction >::grid_type
position_accessor_type
template<typename TGridFunction > typedef domain_type::position_accessor_type ug::NavierStokes::VariableBoxFilter< TGridFunction >::position_accessor_type
side_type
template<typename TGridFunction > typedef elem_type::side ug::NavierStokes::VariableBoxFilter< TGridFunction >::side_type
SideIterator
template<typename TGridFunction > typedef TGridFunction::template traits<side_type>::const_iterator ug::NavierStokes::VariableBoxFilter< TGridFunction >::SideIterator
side iterator
vertex_type
template<typename TGridFunction > typedef Vertex ug::NavierStokes::VariableBoxFilter< TGridFunction >::vertex_type
VertexIterator
template<typename TGridFunction > typedef TGridFunction::template traits<vertex_type>::const_iterator ug::NavierStokes::VariableBoxFilter< TGridFunction >::VertexIterator
vertex iterator
Constructor & Destructor Documentation
VariableBoxFilter()
template<typename TGridFunction > ug::NavierStokes::VariableBoxFilter< TGridFunction >::VariableBoxFilter (SmartPtr< TGridFunction > u, SmartPtr< TGridFunction > fwidth, bool initWidth = false) inline
References ug::PeriodicAttachmentAccessor< class, class >::access(), ug::NavierStokes::VariableBoxFilter< TGridFunction >::compute_average_element_size(), ug::LFEID::CROUZEIX_RAVIART, ug::NavierStokes::VariableBoxFilter< TGridFunction >::dim, SmartPtr< TGridFunction >::get(), ug::LFEID::LAGRANGE, ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_acSideVolume, ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_aSideVolume, ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_aVertexVolume, ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_uInfo, ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_width, and ug::NavierStokes::VariableBoxFilter< TGridFunction >::width().
~VariableBoxFilter()
template<typename TGridFunction > ug::NavierStokes::VariableBoxFilter< TGridFunction >::~VariableBoxFilter () inline
References SmartPtr< TGridFunction >::get(), ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_aSideVolume, ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_aVertexVolume, and ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_uInfo.
Member Function Documentation
add_wall()
template<typename TGridFunction > void ug::NavierStokes::VariableBoxFilter< TGridFunction >::add_wall (WallObject< TGridFunction > w) inline
References ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_walls.
apply_filter() [1/3]
template<typename TGridFunction > template<typename VType > void ug::NavierStokes::VariableBoxFilter< TGridFunction >::apply_filter (PeriodicAttachmentAccessor< side_type, Attachment< VType > > & aaUHat, SmartPtr< TGridFunction > u, PeriodicAttachmentAccessor< side_type, Attachment< VType > > & aaU)
References ug::NavierStokes::averageByVolume(), ug::LFEID::CROUZEIX_RAVIART, dim, ug::DoFRef(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::global_corner(), ug::PeriodicBoundaryManager::is_master(), ug::PeriodicBoundaryManager::is_slave(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::local_corner(), ug::PeriodicBoundaryManager::master(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::num_corners(), ug::DimFV1Geometry< TDim, TWorldDim >::num_scv(), num_subsets(), s, ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::SetAttachmentValues(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), MathVector< dim >::size(), ug::PeriodicBoundaryManager::slaves(), SPNULL, ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
apply_filter() [2/3]
template<typename TGridFunction > template<typename VType > void ug::NavierStokes::VariableBoxFilter< TGridFunction >::apply_filter (PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > & aaUHat, SmartPtr< TGridFunction > u) inline
References UG_THROW.
apply_filter() [3/3]
template<typename TGridFunction > template<typename VType > void ug::NavierStokes::VariableBoxFilter< TGridFunction >::apply_filter (PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > & aaUHat, SmartPtr< TGridFunction > u, PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > & aaU) inline
References UG_THROW.
check_volume_sizes()
template<typename TGridFunction > template<typename VType , typename TElem > void ug::NavierStokes::VariableBoxFilter< TGridFunction >::check_volume_sizes (PeriodicAttachmentAccessor< TElem, Attachment< VType > > & acUHat, SmartPtr< TGridFunction > u) inline
References SmartPtr< TGridFunction >::get(), and ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_width.
collectSides()
template<typename TGridFunction > template<typename VType > void ug::NavierStokes::VariableBoxFilter< TGridFunction >::collectSides (PeriodicAttachmentAccessor< side_type, Attachment< VType > > & acUHat, PeriodicAttachmentAccessor< side_type, Attachment< number > > & acVolume, std::vector< MathVector< dim > > & coord, VType values[DimFV1Geometry< dim >::maxNumSCV], number volumes[DimFV1Geometry< dim >::maxNumSCV], std::vector< side_type * > & sides) private
References ug::DoFRef(), ug::PeriodicBoundaryManager::is_slave(), s, and ug::NavierStokes::VecDistanceMaxNorm().
compute_average_element_size()
template<typename TGridFunction > number ug::NavierStokes::VariableBoxFilter< TGridFunction >::compute_average_element_size (SmartPtr< TGridFunction > u)
References ug::CollectCornerCoordinates(), and element_type().
Referenced by ug::NavierStokes::VariableBoxFilter< TGridFunction >::VariableBoxFilter().
init_width()
template<typename TGridFunction > template<typename TElem > void ug::NavierStokes::VariableBoxFilter< TGridFunction >::init_width (number width) inline
References ug::DoFRef(), SmartPtr< TGridFunction >::get(), ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_width, num_subsets(), and ug::NavierStokes::VariableBoxFilter< TGridFunction >::width().
max_width()
template<typename TGridFunction > template<typename TElem > number ug::NavierStokes::VariableBoxFilter< TGridFunction >::max_width (number width) inline
References ug::DoFRef(), SmartPtr< TGridFunction >::get(), ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_maxwidth, ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_width, and num_subsets().
width() [1/2]
template<typename TGridFunction > number ug::NavierStokes::VariableBoxFilter< TGridFunction >::width (side_type * side) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::DoFRef(), and ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_width.
width() [2/2]
template<typename TGridFunction > number ug::NavierStokes::VariableBoxFilter< TGridFunction >::width (vertex_type * vrt) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::DoFRef(), and ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_width.
Referenced by ug::NavierStokes::VariableBoxFilter< TGridFunction >::init_width(), and ug::NavierStokes::VariableBoxFilter< TGridFunction >::VariableBoxFilter().
Member Data Documentation
dim
template<typename TGridFunction > const size_t ug::NavierStokes::VariableBoxFilter< TGridFunction >::dim = TGridFunction::dim static
Referenced by ug::NavierStokes::VariableBoxFilter< TGridFunction >::VariableBoxFilter().
m_acSideVolume
template<typename TGridFunction > aSideNumber ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_acSideVolume private
Referenced by ug::NavierStokes::VariableBoxFilter< TGridFunction >::VariableBoxFilter().
m_acVertexVolume
template<typename TGridFunction > aVertexNumber ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_acVertexVolume private
m_aSideVolume
template<typename TGridFunction > ANumber ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_aSideVolume private
Referenced by ug::NavierStokes::VariableBoxFilter< TGridFunction >::VariableBoxFilter(), and ug::NavierStokes::VariableBoxFilter< TGridFunction >::~VariableBoxFilter().
m_aVertexVolume
template<typename TGridFunction > ANumber ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_aVertexVolume private
Referenced by ug::NavierStokes::VariableBoxFilter< TGridFunction >::VariableBoxFilter(), and ug::NavierStokes::VariableBoxFilter< TGridFunction >::~VariableBoxFilter().
m_maxwidth
template<typename TGridFunction > number ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_maxwidth private
Referenced by ug::NavierStokes::VariableBoxFilter< TGridFunction >::max_width().
m_posAcc
template<typename TGridFunction > position_accessor_type ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_posAcc private
m_uInfo
template<typename TGridFunction > SmartPtr<TGridFunction> ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_uInfo private
Referenced by ug::NavierStokes::VariableBoxFilter< TGridFunction >::VariableBoxFilter(), and ug::NavierStokes::VariableBoxFilter< TGridFunction >::~VariableBoxFilter().
m_walls
template<typename TGridFunction > std::vector<WallObject<TGridFunction> > ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_walls private
Referenced by ug::NavierStokes::VariableBoxFilter< TGridFunction >::add_wall().
m_width
template<typename TGridFunction > SmartPtr<TGridFunction> ug::NavierStokes::VariableBoxFilter< TGridFunction >::m_width private
Referenced by ug::NavierStokes::VariableBoxFilter< TGridFunction >::check_volume_sizes(), ug::NavierStokes::VariableBoxFilter< TGridFunction >::init_width(), ug::NavierStokes::VariableBoxFilter< TGridFunction >::max_width(), ug::NavierStokes::VariableBoxFilter< TGridFunction >::VariableBoxFilter(), and ug::NavierStokes::VariableBoxFilter< TGridFunction >::width().
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/filter.h
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/filter_impl.h