Plugins: ug::Richards::IRichardsModel< TDerived > Class Template Reference
ug::Richards::IRichardsModel< TDerived > Class Template Reference
This is the interface for a Richards-type model. All derived classes use CRTP for evaluation.
#include <van_genuchten.h>
Public Member Functions
double Conductivity (double H)
Conductivity K = Ks*kr.
double dConductivity_dH (double H)
double dSaturation_dH (double H) const
void get_conductivities (const double *H, double *K, double *dKdH, size_t n) const
void get_conductivity (double H, double &K, double &dKdH) const
Calls Conductivity_.
void get_relative_permeabilities (const double *H, double *K, double *dKdH, size_t n) const
void get_relative_permeability (double H, double &Kr, double &dKrdH) const
Calls RelativePermeability_.
void get_saturation (double H, double &S, double &dSdH) const
Calls Saturation_.
void get_saturations (const double *H, double *S, double *dSdH, size_t n) const
double Saturation (double H) const
Protected Member Functions
template<typename TFunc >
void get_value_and_deriv (TFunc F, double H, double &f, double &df) const
TDerived * me ()
const TDerived * me () const
Detailed Description
template<typename TDerived>
class ug::Richards::IRichardsModel< TDerived >
This is the interface for a Richards-type model. All derived classes use CRTP for evaluation.
Two non-dimensional quantities are returned
Saturation $ 0 \le S(\psi) \le 1$
Relative permeability 0 \le k_r(\psi) \le 1
For convenience, we also return
Conductitivity K = K_s *k_r(\psi)
Member Function Documentation
Conductivity()
template<typename TDerived > double ug::Richards::IRichardsModel< TDerived >::Conductivity (double H) inline
Conductivity K = Ks*kr.
References ug::Richards::IRichardsModel< TDerived >::me().
dConductivity_dH()
template<typename TDerived > double ug::Richards::IRichardsModel< TDerived >::dConductivity_dH (double H) inline
References ug::Richards::IRichardsModel< TDerived >::me().
dSaturation_dH()
template<typename TDerived > double ug::Richards::IRichardsModel< TDerived >::dSaturation_dH (double H) const inline
References ug::Richards::IRichardsModel< TDerived >::me().
get_conductivities()
template<typename TDerived > void ug::Richards::IRichardsModel< TDerived >::get_conductivities (const double * H, double * K, double * dKdH, size_t n) const inline
References ug::Richards::IRichardsModel< TDerived >::get_conductivity().
get_conductivity()
template<typename TDerived > void ug::Richards::IRichardsModel< TDerived >::get_conductivity (double H, double & K, double & dKdH) const inline
Calls Conductivity_.
References ug::Richards::IRichardsModel< TDerived >::get_value_and_deriv(), and ug::Richards::IRichardsModel< TDerived >::me().
Referenced by ug::Richards::IRichardsModel< TDerived >::get_conductivities().
get_relative_permeabilities()
template<typename TDerived > void ug::Richards::IRichardsModel< TDerived >::get_relative_permeabilities (const double * H, double * K, double * dKdH, size_t n) const inline
References ug::Richards::IRichardsModel< TDerived >::get_relative_permeability().
get_relative_permeability()
template<typename TDerived > void ug::Richards::IRichardsModel< TDerived >::get_relative_permeability (double H, double & Kr, double & dKrdH) const inline
Calls RelativePermeability_.
References ug::Richards::IRichardsModel< TDerived >::get_value_and_deriv(), and ug::Richards::IRichardsModel< TDerived >::me().
Referenced by ug::Richards::IRichardsModel< TDerived >::get_relative_permeabilities().
get_saturation()
template<typename TDerived > void ug::Richards::IRichardsModel< TDerived >::get_saturation (double H, double & S, double & dSdH) const inline
Calls Saturation_.
References ug::Richards::IRichardsModel< TDerived >::get_value_and_deriv(), and ug::Richards::IRichardsModel< TDerived >::me().
Referenced by ug::Richards::IRichardsModel< TDerived >::get_saturations().
get_saturations()
template<typename TDerived > void ug::Richards::IRichardsModel< TDerived >::get_saturations (const double * H, double * S, double * dSdH, size_t n) const inline
References ug::Richards::IRichardsModel< TDerived >::get_saturation().
get_value_and_deriv()
template<typename TDerived > template<typename TFunc > void ug::Richards::IRichardsModel< TDerived >::get_value_and_deriv (TFunc F, double H, double & f, double & df) const inline protected
Referenced by ug::Richards::IRichardsModel< TDerived >::get_conductivity(), ug::Richards::IRichardsModel< TDerived >::get_relative_permeability(), and ug::Richards::IRichardsModel< TDerived >::get_saturation().
me() [1/2]
template<typename TDerived > TDerived* ug::Richards::IRichardsModel< TDerived >::me () inline protected
me() [2/2]
template<typename TDerived > const TDerived* ug::Richards::IRichardsModel< TDerived >::me () const inline protected
Referenced by ug::Richards::IRichardsModel< TDerived >::Conductivity(), ug::Richards::IRichardsModel< TDerived >::dConductivity_dH(), ug::Richards::IRichardsModel< TDerived >::dSaturation_dH(), ug::Richards::IRichardsModel< TDerived >::get_conductivity(), ug::Richards::IRichardsModel< TDerived >::get_relative_permeability(), ug::Richards::IRichardsModel< TDerived >::get_saturation(), and ug::Richards::IRichardsModel< TDerived >::Saturation().
Saturation()
template<typename TDerived > double ug::Richards::IRichardsModel< TDerived >::Saturation (double H) const inline
References ug::Richards::IRichardsModel< TDerived >::me().
Referenced by BOOST_FIXTURE_TEST_CASE().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Richards/van_genuchten.h