Plugins: ug::Richards::HaverkampModel Class Reference
ug::Richards::HaverkampModel Class Reference
Implements a Haverkamp model.
#include <van_genuchten.h>
Public Types
typedef IRichardsModel< HaverkampModel > base_type
typedef HaverkampParameters parameter_type
typedef IParameterizedModel< HaverkampParameters > parameterized_model_type
Public Member Functions
HaverkampModel (const parameter_type &p)
Public Member Functions inherited from ug::Richards::IRichardsModel< HaverkampModel >
double Conductivity (double H)
Conductivity K = Ks*kr.
double dConductivity_dH (double H)
double dSaturation_dH (double H) const
void get_conductivities (const double *H, double *K, double *dKdH, size_t n) const
void get_conductivity (double H, double &K, double &dKdH) const
Calls Conductivity_.
void get_relative_permeabilities (const double *H, double *K, double *dKdH, size_t n) const
void get_relative_permeability (double H, double &Kr, double &dKrdH) const
Calls RelativePermeability_.
void get_saturation (double H, double &S, double &dSdH) const
Calls Saturation_.
void get_saturations (const double *H, double *S, double *dSdH, size_t n) const
double Saturation (double H) const
Public Member Functions inherited from ug::Richards::IParameterizedModel< HaverkampParameters >
std::string config_string () const
const HaverkampParameters & get_parameters () const
IParameterizedModel ()
IParameterizedModel (const HaverkampParameters &p)
void set_parameters (const HaverkampParameters &p)
Public Attributes
friend base_type
friend parameterized_model_type
Public Attributes inherited from ug::Richards::IParameterizedModel< HaverkampParameters >
HaverkampParameters m_param
Protected Member Functions
dual Conductivity_ (dual psi_) const
dual RelativePermeability_ (dual psi_) const
Relative permeability $0 \le k_r \le 1$.
dual Saturation_ (dual psi_) const
Rescaled Saturation $$ S:=\theta_r+ (\theta_s - \theta_r) * \hat S $$.
Protected Member Functions inherited from ug::Richards::IRichardsModel< HaverkampModel >
void get_value_and_deriv (TFunc F, double H, double &f, double &df) const
HaverkampModel * me ()
const HaverkampModel * me () const
Detailed Description
Implements a Haverkamp model.
Member Typedef Documentation
base_type
typedef IRichardsModel<HaverkampModel> ug::Richards::HaverkampModel::base_type
parameter_type
typedef HaverkampParameters ug::Richards::HaverkampModel::parameter_type
parameterized_model_type
typedef IParameterizedModel<HaverkampParameters> ug::Richards::HaverkampModel::parameterized_model_type
Constructor & Destructor Documentation
HaverkampModel()
ug::Richards::HaverkampModel::HaverkampModel (const parameter_type & p) inline
Member Function Documentation
Conductivity_()
dual ug::Richards::HaverkampModel::Conductivity_ (dual psi_) const inline protected
References ug::Richards::IParameterizedModel< HaverkampParameters >::get_parameters(), p, and RelativePermeability_().
RelativePermeability_()
dual ug::Richards::HaverkampModel::RelativePermeability_ (dual psi_) const inline protected
Relative permeability $0 \le k_r \le 1$.
References ug::Richards::VanGenuchtenFunctions::ComputeEffectiveSaturation(), ug::Richards::IParameterizedModel< HaverkampParameters >::get_parameters(), and p.
Referenced by Conductivity_().
Saturation_()
dual ug::Richards::HaverkampModel::Saturation_ (dual psi_) const inline protected
Rescaled Saturation $$ S:=\theta_r+ (\theta_s - \theta_r) * \hat S $$.
References ug::Richards::VanGenuchtenFunctions::ComputeEffectiveSaturation(), ug::Richards::IParameterizedModel< HaverkampParameters >::get_parameters(), and p.
Member Data Documentation
base_type
friend ug::Richards::HaverkampModel::base_type
parameterized_model_type
friend ug::Richards::HaverkampModel::parameterized_model_type
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Richards/van_genuchten.h