Plugins: ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain > Class Template Reference
ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain > Class Template Reference
lib_discretization » Elem Disc
The zero-stress (neutral) outflow boundary condition for the incompressible NS equation.
#include <no_normal_stress_outflow_fv.h>
Public Member Functions
template<typename TElem , typename VGeom , typename PGeom >
void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
adds the stiffness part to the local defect
template<typename TElem , typename VGeom , typename PGeom >
void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
adds the stiffness part to the local jacobian
template<typename TElem , typename VGeom , typename PGeom >
void fsh_elem_loop ()
finishes the element loop
NavierStokesNoNormalStressOutflowFV (SmartPtr< IncompressibleNavierStokesBase< TDomain > > spMaster)
Constructor (setting default values)
template<typename TElem , typename VGeom , typename PGeom >
void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
prepares the element for evaluation
template<typename TElem , typename VGeom , typename PGeom >
void prep_elem_loop (const ReferenceObjectID roid, const int si)
prepares the element loop
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegularGrid)
type of trial space for each function used
template<typename TElem , typename VGeom , typename PGeom >
void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename VGeom , typename PGeom >
void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename VGeom , typename PGeom >
void add_rhs_elem (LocalVector &d, GridObject *elem, const MathVector< dim > vCornerCoords[])
Public Member Functions inherited from ug::NavierStokes::NavierStokesNoNormalStressOutflowBase< TDomain >
void add (const char *subsets)
adds a boundary segment
NavierStokesNoNormalStressOutflowBase (SmartPtr< IncompressibleNavierStokesBase< TDomain > > spMaster)
Constructor (setting default values)
virtual bool requests_local_time_series ()
returns if local time series is needed
Public Member Functions inherited from ug::IElemDisc< TDomain >
void add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier)
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > & get_elem_modifier ()
IElemDisc (const char *functions, const char *subsets)
IElemDisc (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
virtual void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_fsh_elem_loop ()
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_timestep (number future_time, const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void fsh_timestep (number time, VectorProxyBase *u)
virtual void fsh_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemAssembleFuncs ()
virtual void post_assemble_loop ()
virtual void prep_assemble_loop ()
virtual void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
virtual void prep_elem_loop (const ReferenceObjectID roid, const int si)
virtual void prep_timestep (number future_time, number time, VectorProxyBase *u)
virtual void prep_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemAssembleFuncs ()
Public Member Functions inherited from ug::IElemError< class >
IElemError (const char *functions, const char *subsets)
IElemError (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from ug::IElemDiscBase< class >
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
void check_setup (bool bNonRegularGrid)
void clear_imports ()
SmartPtr< TDomain > domain ()
ConstSmartPtr< TDomain > domain () const
const FunctionGroup & function_group () const
ConstSmartPtr< FunctionPattern > function_pattern () const
IDataImport< dim > & get_import (size_t i)
IElemDiscBase (const char *functions="", const char *subsets="")
IElemDiscBase (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
bool is_time_dependent () const
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
const FunctionIndexMapping & map () const
number mass_scale () const
number mass_scale () const
number mass_scale (const size_t timePoint) const
number mass_scale (const size_t timePoint) const
const std::vector< number > & mass_scales () const
const std::vector< number > & mass_scales () const
size_t num_fct () const
size_t num_imports () const
size_t num_subsets () const
void register_import (IDataImport< dim > &Imp)
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_functions (const std::string &functions)
void set_functions (const std::vector< std::string > &functions)
void set_stationary ()
void set_stationary (bool bStationaryForced=true)
void set_subsets (const std::string &subsets)
void set_subsets (const std::vector< std::string > &subsets)
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
void set_time_independent ()
void set_time_point (const size_t timePoint)
number stiff_scale () const
number stiff_scale () const
number stiff_scale (const size_t timePoint) const
number stiff_scale (const size_t timePoint) const
const std::vector< number > & stiff_scales () const
const std::vector< number > & stiff_scales () const
TDomain::subset_handler_type & subset_handler ()
const TDomain::subset_handler_type & subset_handler () const
const std::vector< std::string > & symb_fcts () const
const std::vector< std::string > & symb_subsets () const
number time () const
size_t time_point () const
virtual int type () const
virtual bool use_hanging () const
virtual ~IElemDiscBase ()
Public Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
virtual void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_err_est_elem_loop ()
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
virtual void fsh_err_est_elem_loop ()
IElemEstimatorFuncs ()
virtual void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemEstimatorFuncs ()
Static Public Attributes
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::NavierStokes::NavierStokesNoNormalStressOutflowBase< TDomain >
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::IElemDisc< TDomain >
static const int dim
Static Public Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Static Public Attributes inherited from ug::IElemError< class >
static const int dim
Static Public Attributes inherited from ug::IElemDiscBase< class >
static const int dim
Static Public Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Protected Member Functions
void register_all_funcs (const LFEID &vLfeID, const LFEID &pLfeID)
register util
template<typename TElem , typename VGeom , typename PGeom >
void register_func ()
virtual void set_density (SmartPtr< CplUserData< number, dim > > data)
sets the density
virtual void set_kinematic_viscosity (SmartPtr< CplUserData< number, dim > > data)
sets the kinematic viscosity
Protected Member Functions inherited from ug::NavierStokes::NavierStokesNoNormalStressOutflowBase< TDomain >
void extract_scheduled_data ()
Protected Member Functions inherited from ug::IElemDisc< TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void set_default_add_fct ()
Protected Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_add_def_A_elem_fct (ReferenceObjectID id)
void remove_add_def_A_expl_elem_fct (ReferenceObjectID id)
void remove_add_def_M_elem_fct (ReferenceObjectID id)
void remove_add_jac_A_elem_fct (ReferenceObjectID id)
void remove_add_jac_M_elem_fct (ReferenceObjectID id)
void remove_add_rhs_elem_fct (ReferenceObjectID id)
void remove_fsh_elem_loop_fct (ReferenceObjectID id)
void remove_fsh_timestep_elem_fct (ReferenceObjectID id)
void remove_fsh_timestep_fct (size_t algebra_id)
void remove_prep_elem_fct (ReferenceObjectID id)
void remove_prep_elem_loop_fct (ReferenceObjectID id)
void remove_prep_timestep_elem_fct (ReferenceObjectID id)
void remove_prep_timestep_fct (size_t algebra_id)
void set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_fct (size_t algebra_id, TAssFunc func)
void set_prep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_fct (size_t algebra_id, TAssFunc func)
Protected Member Functions inherited from ug::IElemError< class >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
Protected Member Functions inherited from ug::IElemDiscBase< class >
virtual void approximation_space_changed ()
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
void update_function_index_mapping ()
Protected Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
Protected Attributes
DataImport< number, dim > m_imDensity
Data import for density.
DataImport< number, dim > m_imDensityP
DataImport< number, dim > m_imKinViscosity
Data import for kinematic viscosity.
LFEID m_pLFEID
int m_quadOrder
quadrature order
std::vector< MathVector< dim > > m_vGloIPp
std::vector< MathVector< dim > > m_vGloIPv
LFEID m_vLFEID
current shape function set
std::vector< MathVector< dim > > m_vLocIPp
std::vector< MathVector< dim > > m_vLocIPv
Boundary integration points of the viscosity and the density.
std::vector< std::vector< number > > m_vvVShape
Protected Attributes inherited from ug::NavierStokes::NavierStokesNoNormalStressOutflowBase< TDomain >
SmartPtr< IncompressibleNavierStokesBase< TDomain > > m_spMaster
The master discretization:
std::vector< int > m_vBndSubSetIndex
std::vector< std::string > m_vScheduledBndSubSets
The boundary subsets:
Protected Attributes inherited from ug::IElemDisc< TDomain >
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > m_spElemModifier
Protected Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
Protected Attributes inherited from ug::IElemDiscBase< class >
bool m_bStationaryForced
FunctionGroup m_fctGrp
FunctionIndexMapping m_fctIndexMap
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
ConstSmartPtr< FunctionPattern > m_spFctPattern
size_t m_timePoint
std::vector< std::string > m_vFct
std::vector< IDataImport< dim > * > m_vIImport
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
std::vector< std::string > m_vSubset
Protected Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
Static Protected Attributes
static const size_t _P_ = dim
abbreviation for pressure
Private Types
typedef NavierStokesNoNormalStressOutflowBase< TDomain > base_type
Base class type.
typedef NavierStokesNoNormalStressOutflowFV< TDomain > this_type
own type
Private Member Functions
template<typename BF >
void convective_flux_defect (const size_t i, const size_t ip, const BF &bf, LocalVector &d, const LocalVector &u)
adds the convective part of the local defect of the momentum equation
template<typename BF >
void convective_flux_Jac (const size_t i, const size_t ip, const BF &bf, LocalMatrix &J, const LocalVector &u)
adds the convective part of the local Jacobian of the momentum equation
template<typename BF >
void diffusive_flux_defect (const size_t i, const size_t ip, const BF &bf, LocalVector &d, const LocalVector &u)
adds the diffusive part of the local defect of the momentum equation
template<typename BF >
void diffusive_flux_Jac (const size_t i, const size_t ip, const BF &bf, LocalMatrix &J, const LocalVector &u)
adds the diffusive part of the local Jacobian of the momentum equation
Additional Inherited Members
Public Types inherited from ug::IElemDisc< TDomain >
typedef IElemAssembleFuncs< IElemDisc< TDomain >, TDomain > assemble_base_type
typedef IElemError< TDomain > base_type
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Public Types inherited from ug::IElemError< class >
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from ug::IElemDiscBase< class >
typedef TDomain domain_type
typedef TDomain::position_type position_type
Public Types inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Protected Types inherited from ug::NavierStokes::NavierStokesNoNormalStressOutflowBase< TDomain >
typedef IElemDisc< TDomain > base_type
Base class type.
typedef NavierStokesNoNormalStressOutflowBase< TDomain > this_type
own type
Detailed Description
template<typename TDomain>
class ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >
The zero-stress (neutral) outflow boundary condition for the incompressible NS equation.
This class implements the so-called neutral boundary condition for outflow boundaries. Note that this class can be used only with the stabilized vertex-centered discretization of the Navier-Stokes equations.
This boundary condition imposes two equations on the unknown functions at the outflow boundary \(F \):
\(\int_F p ds = 0 \), and
\(\sigma \vec{n} \cdot \vec{n} = 0 \) on \(F \).
where \(\vec{n} \) is the outer normal at \(F \) and \(\sigma = \mu (\nabla \vec{u} + (\nabla \vec{u})^T) \) the stress tensor.
Member Typedef Documentation
base_type
template<typename TDomain > typedef NavierStokesNoNormalStressOutflowBase<TDomain> ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::base_type private
Base class type.
this_type
template<typename TDomain > typedef NavierStokesNoNormalStressOutflowFV<TDomain> ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::this_type private
own type
Constructor & Destructor Documentation
NavierStokesNoNormalStressOutflowFV()
template<typename TDomain > ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::NavierStokesNoNormalStressOutflowFV (SmartPtr< IncompressibleNavierStokesBase< TDomain > > spMaster)
Constructor (setting default values)
References ug::IElemDisc< TDomain >::clear_add_fct(), ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_imDensity, ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_imDensityP, ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_imKinViscosity, ug::IElemDiscBase< class >::register_import(), ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::set_density(), and ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::set_kinematic_viscosity().
Member Function Documentation
add_def_A_elem()
template<typename TDomain > template<typename TElem , typename VGeom , typename PGeom > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::add_def_A_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
adds the stiffness part to the local defect
References dim, ug::GeomProvider< class >::get(), and ug::VecDot().
add_def_M_elem()
template<typename TDomain > template<typename TElem , typename VGeom , typename PGeom > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::add_def_M_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) inline
dummy implementations
add_jac_A_elem()
template<typename TDomain > template<typename TElem , typename VGeom , typename PGeom > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::add_jac_A_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[])
adds the stiffness part to the local jacobian
References dim, and ug::GeomProvider< class >::get().
add_jac_M_elem()
template<typename TDomain > template<typename TElem , typename VGeom , typename PGeom > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::add_jac_M_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) inline
dummy implementations
add_rhs_elem()
template<typename TDomain > template<typename TElem , typename VGeom , typename PGeom > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::add_rhs_elem (LocalVector & d, GridObject * elem, const MathVector< dim > vCornerCoords[]) inline
dummy implementations
convective_flux_defect()
template<typename TDomain > template<typename BF > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::convective_flux_defect (const size_t i, const size_t ip, const BF & bf, LocalVector & d, const LocalVector & u) inline private
adds the convective part of the local defect of the momentum equation
Assembling of the convective flux (due to the quadratic inertial term) in the defect of the momentum eq.
References dim, and ug::VecDot().
convective_flux_Jac()
template<typename TDomain > template<typename BF > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::convective_flux_Jac (const size_t i, const size_t ip, const BF & bf, LocalMatrix & J, const LocalVector & u) inline private
adds the convective part of the local Jacobian of the momentum equation
Assembling of the convective flux (due to the quadratic inertial term) in the Jacobian of the momentum eq.
References dim, and ug::VecDot().
diffusive_flux_defect()
template<typename TDomain > template<typename BF > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::diffusive_flux_defect (const size_t i, const size_t ip, const BF & bf, LocalVector & d, const LocalVector & u) inline private
adds the diffusive part of the local defect of the momentum equation
Assembling of the diffusive flux (due to the viscosity) in the defect of the momentum eq.
References dim, ug::MatVecMult(), ug::TransposedMatVecMultAdd(), ug::VecDot(), ug::VecNormalize(), and ug::VecScaleAppend().
diffusive_flux_Jac()
template<typename TDomain > template<typename BF > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::diffusive_flux_Jac (const size_t i, const size_t ip, const BF & bf, LocalMatrix & J, const LocalVector & u) inline private
adds the diffusive part of the local Jacobian of the momentum equation
Assembling of the diffusive flux (due to the viscosity) in the Jacobian of the momentum eq.
References dim, ug::MatDiagSet(), ug::MatSet(), ug::TransposedMatVecMult(), ug::VecDot(), and ug::VecNormalize().
fsh_elem_loop()
template<typename TDomain > template<typename TElem , typename VGeom , typename PGeom > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::fsh_elem_loop virtual
finishes the element loop
Finalizes the element loop for a given element type.
Reimplemented from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >.
References ug::GeomProvider< class >::get().
prep_elem()
template<typename TDomain > template<typename TElem , typename VGeom , typename PGeom > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::prep_elem (const LocalVector & u, GridObject * elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
prepares the element for evaluation
General initializations of a given grid element for the assembling.
References ug::GeomProvider< class >::get(), ug::LocalDoFSet::num_sh(), ug::GridObject::reference_object_id(), ug::LocalShapeFunctionSet< TDim, class, class >::shape(), subset_handler(), and UG_CATCH_THROW.
prep_elem_loop()
template<typename TDomain > template<typename TElem , typename VGeom , typename PGeom > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::prep_elem_loop (const ReferenceObjectID roid, const int si)
prepares the element loop
Prepares the element loop for a given element type: computes the FV-geo, ... Note that there are separate loops for every type of the grid elements.
References ug::GeomProvider< class >::get(), UG_CATCH_THROW, and UG_THROW.
prepare_setting()
template<typename TDomain > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::prepare_setting (const std::vector< LFEID > & vLfeID, bool bNonRegularGrid) virtual
type of trial space for each function used
Implements ug::IElemDiscBase< class >.
References dim, and UG_THROW.
register_all_funcs()
template<typename TDomain > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::register_all_funcs (const LFEID & vLfeID, const LFEID & pLfeID) protected
register util
register_func()
template<typename TDomain > template<typename TElem , typename VGeom , typename PGeom > void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::register_func protected
set_density()
template<typename TDomain > virtual void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::set_density (SmartPtr< CplUserData< number, dim > > data) inline protected virtual
sets the density
Implements ug::NavierStokes::NavierStokesNoNormalStressOutflowBase< TDomain >.
References ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_imDensity, ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_imDensityP, and DataImport< number, dim >::set_data().
Referenced by ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::NavierStokesNoNormalStressOutflowFV().
set_kinematic_viscosity()
template<typename TDomain > virtual void ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::set_kinematic_viscosity (SmartPtr< CplUserData< number, dim > > data) inline protected virtual
sets the kinematic viscosity
Implements ug::NavierStokes::NavierStokesNoNormalStressOutflowBase< TDomain >.
References ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_imKinViscosity, and DataImport< number, dim >::set_data().
Referenced by ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::NavierStokesNoNormalStressOutflowFV().
Member Data Documentation
_P_
template<typename TDomain > const size_t ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::_P_ = dim static protected
abbreviation for pressure
dim
template<typename TDomain > const int ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::dim = base_type::dim static
World dimension.
m_imDensity
template<typename TDomain > DataImport<number, dim> ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_imDensity protected
Data import for density.
Referenced by ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::NavierStokesNoNormalStressOutflowFV(), and ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::set_density().
m_imDensityP
template<typename TDomain > DataImport<number, dim> ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_imDensityP protected
Referenced by ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::NavierStokesNoNormalStressOutflowFV(), and ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::set_density().
m_imKinViscosity
template<typename TDomain > DataImport<number, dim> ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_imKinViscosity protected
Data import for kinematic viscosity.
Referenced by ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::NavierStokesNoNormalStressOutflowFV(), and ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::set_kinematic_viscosity().
m_pLFEID
template<typename TDomain > LFEID ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_pLFEID protected
m_quadOrder
template<typename TDomain > int ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_quadOrder protected
quadrature order
m_vGloIPp
template<typename TDomain > std::vector<MathVector<dim> > ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_vGloIPp protected
m_vGloIPv
template<typename TDomain > std::vector<MathVector<dim> > ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_vGloIPv protected
m_vLFEID
template<typename TDomain > LFEID ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_vLFEID protected
current shape function set
m_vLocIPp
template<typename TDomain > std::vector<MathVector<dim> > ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_vLocIPp protected
m_vLocIPv
template<typename TDomain > std::vector<MathVector<dim> > ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_vLocIPv protected
Boundary integration points of the viscosity and the density.
m_vvVShape
template<typename TDomain > std::vector<std::vector<number> > ug::NavierStokes::NavierStokesNoNormalStressOutflowFV< TDomain >::m_vvVShape protected
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv/bnd/no_normal_stress_outflow_fv.h
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv/bnd/no_normal_stress_outflow_fv.cpp