Plugins: ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp > Class Template Reference
ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp > Class Template Reference
#include <memreduce.h>
Public Types
typedef TArray array_type
typedef base_type::Interface Interface
typedef base_type::Layout Layout
typedef array_type::value_type value_type
Public Types inherited from pcl::ICommunicationPolicy< TLayout >
typedef Layout::Interface Interface
typedef TLayout Layout
Public Member Functions
virtual bool collect (ug::BinaryBuffer &buff, const Interface &interface)
writes the interface values into a buffer that will be sent
ComPol_MemOp ()
Default constructor.
ComPol_MemOp (TArray *pMemDst, const TArray *pMemSrc)
Constructor setting the arrays.
ComPol_MemOp (TArray *pVec)
Constructor setting the same arrays for the source and the destination.
virtual bool extract (ug::BinaryBuffer &buff, const Interface &interface)
writes values from a buffer into the interface
virtual int get_required_buffer_size (const Interface &interface)
returns the buffer size
void set_dst (TArray *pMemDst)
set the destination
void set_src (const TArray *pMem)
set the source array
Public Member Functions inherited from pcl::ICommunicationPolicy< TLayout >
virtual bool begin_layout_collection (const Layout *pLayout)
virtual bool begin_layout_extraction (const Layout *pLayout)
virtual void begin_level_extraction (int level)
virtual bool end_layout_collection (const Layout *pLayout)
virtual bool end_layout_extraction (const Layout *pLayout)
virtual ~ICommunicationPolicy ()
Private Types
typedef pcl::ICommunicationPolicy< TLayout > base_type
typedef ComPol_MemOp< TArray, TLayout, TOp > this_type
Private Attributes
TArray * m_pMemDst
const TArray * m_pMemSrc
Detailed Description
template<typename TArray, typename TLayout, typename TOp>
class ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >
Communication policy for the reduction of arrays represented by classes like std::vector or VariableArray1 using a generic operation. To perform the the operation, the template parameter class TOp must implement a STATIC function 'op' with the arguments of type TArray::value_type. During the reduction, the arguments are initialized with the data on the master and the current slave.
Template Parameters
TArray type of the array class (e.g. std::vector)
TLayout type of the parallel layout of the memory
TOp class of the operation
Member Typedef Documentation
array_type
template<typename TArray , typename TLayout , typename TOp > typedef TArray ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::array_type
base_type
template<typename TArray , typename TLayout , typename TOp > typedef pcl::ICommunicationPolicy<TLayout> ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::base_type private
Interface
template<typename TArray , typename TLayout , typename TOp > typedef base_type::Interface ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::Interface
Layout
template<typename TArray , typename TLayout , typename TOp > typedef base_type::Layout ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::Layout
this_type
template<typename TArray , typename TLayout , typename TOp > typedef ComPol_MemOp<TArray, TLayout, TOp> ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::this_type private
value_type
template<typename TArray , typename TLayout , typename TOp > typedef array_type::value_type ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::value_type
Constructor & Destructor Documentation
ComPol_MemOp() [1/3]
template<typename TArray , typename TLayout , typename TOp > ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::ComPol_MemOp () inline
Default constructor.
ComPol_MemOp() [2/3]
template<typename TArray , typename TLayout , typename TOp > ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::ComPol_MemOp (TArray * pVec) inline
Constructor setting the same arrays for the source and the destination.
ComPol_MemOp() [3/3]
template<typename TArray , typename TLayout , typename TOp > ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::ComPol_MemOp (TArray * pMemDst, const TArray * pMemSrc) inline
Constructor setting the arrays.
Member Function Documentation
collect()
template<typename TArray , typename TLayout , typename TOp > virtual bool ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::collect (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
writes the interface values into a buffer that will be sent
This function collects all entries of the vector into a buffer that are part of the interface.
Parameters
[out] buff Buffer
[in] interface Interface that will communicate
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::m_pMemSrc, and ug::Serialize().
extract()
template<typename TArray , typename TLayout , typename TOp > virtual bool ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::extract (ug::BinaryBuffer & buff, const Interface & interface) inline virtual
writes values from a buffer into the interface
This function writes the buffer values into the vector.
Parameters
[out] buff Buffer
[in] interface Interface that communicates
Implements pcl::ICommunicationPolicy< TLayout >.
References ug::Deserialize(), entry(), and ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::m_pMemDst.
get_required_buffer_size()
template<typename TArray , typename TLayout , typename TOp > virtual int ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::get_required_buffer_size (const Interface & interface) inline virtual
returns the buffer size
This function returns the size of the buffer needed for the communication of passed interface. If the vector has fixed size entries this is just the number of interface entries times the size of the entry. In case of a variable size entry type a negative value is returned to indicate that no buffer size can be determined in advanced.
Parameters
[in] interface Interface that will communicate
Reimplemented from pcl::ICommunicationPolicy< TLayout >.
set_dst()
template<typename TArray , typename TLayout , typename TOp > void ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::set_dst (TArray * pMemDst) inline
set the destination
References ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::m_pMemDst.
set_src()
template<typename TArray , typename TLayout , typename TOp > void ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::set_src (const TArray * pMem) inline
set the source array
References ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::m_pMemSrc.
Member Data Documentation
m_pMemDst
template<typename TArray , typename TLayout , typename TOp > TArray* ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::m_pMemDst private
Referenced by ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::extract(), and ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::set_dst().
m_pMemSrc
template<typename TArray , typename TLayout , typename TOp > const TArray* ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::m_pMemSrc private
Referenced by ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::collect(), and ug::Electromagnetism::ComPol_MemOp< TArray, TLayout, TOp >::set_src().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/memreduce.h