Plugins: ug::NavierStokes::FV1BoxFilter< TGridFunction > Class Template Reference
ug::NavierStokes::FV1BoxFilter< TGridFunction > Class Template Reference
#include <filter.h>
Public Types
typedef PeriodicAttachmentAccessor< side_type, ANumber > aSideNumber
typedef PeriodicAttachmentAccessor< vertex_type, ANumber > aVertexNumber
typedef FilterImplBaseClass< FV1BoxFilter< TGridFunction >, TGridFunction > base_type
typedef TGridFunction::domain_type domain_type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
typedef TGridFunction::template dim_traits< dim >::const_iterator ElemIterator
typedef domain_type::grid_type grid_type
typedef domain_type::position_accessor_type position_accessor_type
typedef elem_type::side side_type
typedef TGridFunction::template traits< side_type >::const_iterator SideIterator
typedef Vertex vertex_type
typedef TGridFunction::template traits< vertex_type >::const_iterator VertexIterator
Public Types inherited from ug::NavierStokes::FilterImplBaseClass< FV1BoxFilter< TGridFunction >, TGridFunction >
typedef TGridFunction::domain_type domain_type
domain type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef domain_type::grid_type grid_type
grid type
typedef elem_type::side side_type
side type
typedef FilterBaseClass< TGridFunction >::type0 type0
typedef FilterBaseClass< TGridFunction >::type1 type1
typedef FilterBaseClass< TGridFunction >::type2 type2
typedef Vertex vertex_type
Public Types inherited from ug::NavierStokes::FilterBaseClass< TGridFunction >
typedef TGridFunction::domain_type domain_type
domain type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef domain_type::grid_type grid_type
grid type
typedef elem_type::side side_type
side type
typedef MathVector< dim > type0
typedef number type1
typedef MathSymmetricMatrix< dim > type2
typedef Vertex vertex_type
Public Member Functions
void add_wall (WallObject< TGridFunction > w)
template<typename VType >
void apply_filter (PeriodicAttachmentAccessor< side_type, Attachment< VType > > &aaUHat, SmartPtr< TGridFunction > u, PeriodicAttachmentAccessor< side_type, Attachment< VType > > &aaU)
template<typename VType >
void apply_filter (PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > &aaUHat, SmartPtr< TGridFunction > u)
template<typename VType >
void apply_filter (PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > &aaUHat, SmartPtr< TGridFunction > u, PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > &aaU)
void compute_filterwidth ()
void compute_filterwidth_fv1 ()
void compute_filterwidth_fvcr ()
FV1BoxFilter (SmartPtr< TGridFunction > u)
number width (side_type *side)
number width (vertex_type *vrt)
~FV1BoxFilter ()
Public Member Functions inherited from ug::NavierStokes::FilterImplBaseClass< FV1BoxFilter< TGridFunction >, TGridFunction >
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type0 > > &aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type0 > > &aaU)
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type0 > > &aaUHat, SmartPtr< TGridFunction > u)
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type1 > > &aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type1 > > &aaU)
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type2 > > &aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type2 > > &aaU)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > &aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > &aaU)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > &aaUHat, SmartPtr< TGridFunction > u)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type1 > > &aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type1 > > &aaU)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type2 > > &aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type2 > > &aaU)
void apply (SmartPtr< TGridFunction > u)
void apply_ (SmartPtr< TGridFunction > u)
void assignVal (MathSymmetricMatrix< 2 > &v, size_t ind, number value)
void assignVal (MathSymmetricMatrix< 3 > &v, size_t ind, number value)
void assignVal (MathVector< 2 > &v, size_t ind, number value)
void assignVal (MathVector< 3 > &v, size_t ind, number value)
void assignVal (number &v, size_t ind, number value)
void copyWallData (PeriodicAttachmentAccessor< TElem, Attachment< VType > > &acUHat, PeriodicAttachmentAccessor< TElem, Attachment< VType > > &acU, SmartPtr< TGridFunction > u, std::vector< WallObject< TGridFunction > > walls)
void copyWallData (PeriodicAttachmentAccessor< TElem, Attachment< VType > > &acUHat, SmartPtr< TGridFunction > u, std::vector< WallObject< TGridFunction > > walls)
Public Member Functions inherited from ug::NavierStokes::FilterBaseClass< TGridFunction >
FilterBaseClass ()
virtual ~FilterBaseClass ()
Static Public Attributes
static const size_t dim = TGridFunction::dim
Static Public Attributes inherited from ug::NavierStokes::FilterImplBaseClass< FV1BoxFilter< TGridFunction >, TGridFunction >
static const size_t dim
dimension
Static Public Attributes inherited from ug::NavierStokes::FilterBaseClass< TGridFunction >
static const size_t dim = TGridFunction::dim
dimension
Private Attributes
aSideNumber m_acSideVolume
aVertexNumber m_acVertexVolume
ANumber m_aSideVolume
ANumber m_aVertexVolume
SmartPtr< TGridFunction > m_uInfo
std::vector< WallObject< TGridFunction > > m_walls
Additional Inherited Members
Protected Member Functions inherited from ug::NavierStokes::FilterImplBaseClass< FV1BoxFilter< TGridFunction >, TGridFunction >
FV1BoxFilter< TGridFunction > & getImpl ()
access to implementation
const FV1BoxFilter< TGridFunction > & getImpl () const
const access to implementation
Member Typedef Documentation
aSideNumber
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<side_type,ANumber > ug::NavierStokes::FV1BoxFilter< TGridFunction >::aSideNumber
aVertexNumber
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<vertex_type,ANumber > ug::NavierStokes::FV1BoxFilter< TGridFunction >::aVertexNumber
base_type
template<typename TGridFunction > typedef FilterImplBaseClass<FV1BoxFilter<TGridFunction>,TGridFunction> ug::NavierStokes::FV1BoxFilter< TGridFunction >::base_type
domain_type
template<typename TGridFunction > typedef TGridFunction::domain_type ug::NavierStokes::FV1BoxFilter< TGridFunction >::domain_type
elem_type
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::grid_base_object ug::NavierStokes::FV1BoxFilter< TGridFunction >::elem_type
ElemIterator
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::const_iterator ug::NavierStokes::FV1BoxFilter< TGridFunction >::ElemIterator
grid_type
template<typename TGridFunction > typedef domain_type::grid_type ug::NavierStokes::FV1BoxFilter< TGridFunction >::grid_type
position_accessor_type
template<typename TGridFunction > typedef domain_type::position_accessor_type ug::NavierStokes::FV1BoxFilter< TGridFunction >::position_accessor_type
side_type
template<typename TGridFunction > typedef elem_type::side ug::NavierStokes::FV1BoxFilter< TGridFunction >::side_type
SideIterator
template<typename TGridFunction > typedef TGridFunction::template traits<side_type>::const_iterator ug::NavierStokes::FV1BoxFilter< TGridFunction >::SideIterator
vertex_type
template<typename TGridFunction > typedef Vertex ug::NavierStokes::FV1BoxFilter< TGridFunction >::vertex_type
VertexIterator
template<typename TGridFunction > typedef TGridFunction::template traits<vertex_type>::const_iterator ug::NavierStokes::FV1BoxFilter< TGridFunction >::VertexIterator
Constructor & Destructor Documentation
FV1BoxFilter()
template<typename TGridFunction > ug::NavierStokes::FV1BoxFilter< TGridFunction >::FV1BoxFilter (SmartPtr< TGridFunction > u) inline
References ug::PeriodicAttachmentAccessor< class, class >::access(), ug::LFEID::CROUZEIX_RAVIART, ug::NavierStokes::FV1BoxFilter< TGridFunction >::dim, SmartPtr< TGridFunction >::get(), ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_acSideVolume, ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_aSideVolume, ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_aVertexVolume, and ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_uInfo.
~FV1BoxFilter()
template<typename TGridFunction > ug::NavierStokes::FV1BoxFilter< TGridFunction >::~FV1BoxFilter () inline
References SmartPtr< TGridFunction >::get(), ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_aSideVolume, ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_aVertexVolume, and ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_uInfo.
Member Function Documentation
add_wall()
template<typename TGridFunction > void ug::NavierStokes::FV1BoxFilter< TGridFunction >::add_wall (WallObject< TGridFunction > w) inline
References ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_walls.
apply_filter() [1/3]
template<typename TGridFunction > template<typename VType > void ug::NavierStokes::FV1BoxFilter< TGridFunction >::apply_filter (PeriodicAttachmentAccessor< side_type, Attachment< VType > > & aaUHat, SmartPtr< TGridFunction > u, PeriodicAttachmentAccessor< side_type, Attachment< VType > > & aaU)
References ug::NavierStokes::averageByVolume(), ug::LFEID::CROUZEIX_RAVIART, dim, ug::DoFRef(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::local_corner(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::num_corners(), ug::DimFV1Geometry< TDim, TWorldDim >::num_scv(), num_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::SetAttachmentValues(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), SPNULL, ug::DimFV1Geometry< TDim, TWorldDim >::update(), ug::VecDistance(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
apply_filter() [2/3]
template<typename TGridFunction > template<typename VType > void ug::NavierStokes::FV1BoxFilter< TGridFunction >::apply_filter (PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > & aaUHat, SmartPtr< TGridFunction > u) inline
References UG_THROW.
apply_filter() [3/3]
template<typename TGridFunction > template<typename VType > void ug::NavierStokes::FV1BoxFilter< TGridFunction >::apply_filter (PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > & aaUHat, SmartPtr< TGridFunction > u, PeriodicAttachmentAccessor< vertex_type, Attachment< VType > > & aaU)
References ug::NavierStokes::averageByVolume(), dim, ug::DoFRef(), ug::LFEID::LAGRANGE, ug::DimFV1Geometry< TDim, TWorldDim >::SCV::local_corner(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::num_corners(), ug::DimFV1Geometry< TDim, TWorldDim >::num_scv(), num_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::SetAttachmentValues(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), SPNULL, ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
compute_filterwidth()
template<typename TGridFunction > void ug::NavierStokes::FV1BoxFilter< TGridFunction >::compute_filterwidth () inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::NavierStokes::FV1BoxFilter< TGridFunction >::compute_filterwidth_fv1(), ug::NavierStokes::FV1BoxFilter< TGridFunction >::compute_filterwidth_fvcr(), ug::LFEID::CROUZEIX_RAVIART, ug::NavierStokes::FV1BoxFilter< TGridFunction >::dim, and ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_uInfo.
compute_filterwidth_fv1()
template<typename TGridFunction > void ug::NavierStokes::FV1BoxFilter< TGridFunction >::compute_filterwidth_fv1
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), ug::DimFV1Geometry< TDim, TWorldDim >::num_scv(), num_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::SetAttachmentValues(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
Referenced by ug::NavierStokes::FV1BoxFilter< TGridFunction >::compute_filterwidth().
compute_filterwidth_fvcr()
template<typename TGridFunction > void ug::NavierStokes::FV1BoxFilter< TGridFunction >::compute_filterwidth_fvcr
References ug::DimFV1Geometry< TDim, TWorldDim >::SCV::node_id(), ug::DimFV1Geometry< TDim, TWorldDim >::num_scv(), num_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::SetAttachmentValues(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), ug::VecDistance(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
Referenced by ug::NavierStokes::FV1BoxFilter< TGridFunction >::compute_filterwidth().
width() [1/2]
template<typename TGridFunction > number ug::NavierStokes::FV1BoxFilter< TGridFunction >::width (side_type * side) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::NavierStokes::FV1BoxFilter< TGridFunction >::dim, and ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_acSideVolume.
width() [2/2]
template<typename TGridFunction > number ug::NavierStokes::FV1BoxFilter< TGridFunction >::width (vertex_type * vrt) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::NavierStokes::FV1BoxFilter< TGridFunction >::dim, and ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_acVertexVolume.
Member Data Documentation
dim
template<typename TGridFunction > const size_t ug::NavierStokes::FV1BoxFilter< TGridFunction >::dim = TGridFunction::dim static
Referenced by ug::NavierStokes::FV1BoxFilter< TGridFunction >::compute_filterwidth(), ug::NavierStokes::FV1BoxFilter< TGridFunction >::FV1BoxFilter(), and ug::NavierStokes::FV1BoxFilter< TGridFunction >::width().
m_acSideVolume
template<typename TGridFunction > aSideNumber ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_acSideVolume private
Referenced by ug::NavierStokes::FV1BoxFilter< TGridFunction >::FV1BoxFilter(), and ug::NavierStokes::FV1BoxFilter< TGridFunction >::width().
m_acVertexVolume
template<typename TGridFunction > aVertexNumber ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_acVertexVolume private
Referenced by ug::NavierStokes::FV1BoxFilter< TGridFunction >::width().
m_aSideVolume
template<typename TGridFunction > ANumber ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_aSideVolume private
Referenced by ug::NavierStokes::FV1BoxFilter< TGridFunction >::FV1BoxFilter(), and ug::NavierStokes::FV1BoxFilter< TGridFunction >::~FV1BoxFilter().
m_aVertexVolume
template<typename TGridFunction > ANumber ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_aVertexVolume private
Referenced by ug::NavierStokes::FV1BoxFilter< TGridFunction >::FV1BoxFilter(), and ug::NavierStokes::FV1BoxFilter< TGridFunction >::~FV1BoxFilter().
m_uInfo
template<typename TGridFunction > SmartPtr<TGridFunction> ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_uInfo private
Referenced by ug::NavierStokes::FV1BoxFilter< TGridFunction >::compute_filterwidth(), ug::NavierStokes::FV1BoxFilter< TGridFunction >::FV1BoxFilter(), and ug::NavierStokes::FV1BoxFilter< TGridFunction >::~FV1BoxFilter().
m_walls
template<typename TGridFunction > std::vector<WallObject<TGridFunction> > ug::NavierStokes::FV1BoxFilter< TGridFunction >::m_walls private
Referenced by ug::NavierStokes::FV1BoxFilter< TGridFunction >::add_wall().
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/filter.h
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/filter_impl.h