Plugins: ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction > Class Template Reference
ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction > Class Template Reference
#include <filter.h>
Public Types
typedef TGridFunction::domain_type domain_type
domain type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef domain_type::grid_type grid_type
grid type
typedef elem_type::side side_type
side type
typedef FilterBaseClass< TGridFunction >::type0 type0
typedef FilterBaseClass< TGridFunction >::type1 type1
typedef FilterBaseClass< TGridFunction >::type2 type2
typedef Vertex vertex_type
Public Types inherited from ug::NavierStokes::FilterBaseClass< TGridFunction >
typedef TGridFunction::domain_type domain_type
domain type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef domain_type::grid_type grid_type
grid type
typedef elem_type::side side_type
side type
typedef MathVector< dim > type0
typedef number type1
typedef MathSymmetricMatrix< dim > type2
typedef Vertex vertex_type
Public Member Functions
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type0 > > &aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type0 > > &aaU)
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type0 > > &aaUHat, SmartPtr< TGridFunction > u)
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type1 > > &aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type1 > > &aaU)
void apply (PeriodicAttachmentAccessor< side_type, Attachment< type2 > > &aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type2 > > &aaU)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > &aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > &aaU)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > &aaUHat, SmartPtr< TGridFunction > u)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type1 > > &aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type1 > > &aaU)
void apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type2 > > &aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type2 > > &aaU)
void apply (SmartPtr< TGridFunction > u)
template<typename TElem >
void apply_ (SmartPtr< TGridFunction > u)
void assignVal (MathSymmetricMatrix< 2 > &v, size_t ind, number value)
void assignVal (MathSymmetricMatrix< 3 > &v, size_t ind, number value)
void assignVal (MathVector< 2 > &v, size_t ind, number value)
void assignVal (MathVector< 3 > &v, size_t ind, number value)
void assignVal (number &v, size_t ind, number value)
template<typename VType , typename TElem >
void copyWallData (PeriodicAttachmentAccessor< TElem, Attachment< VType > > &acUHat, PeriodicAttachmentAccessor< TElem, Attachment< VType > > &acU, SmartPtr< TGridFunction > u, std::vector< WallObject< TGridFunction > > walls)
template<typename VType , typename TElem >
void copyWallData (PeriodicAttachmentAccessor< TElem, Attachment< VType > > &acUHat, SmartPtr< TGridFunction > u, std::vector< WallObject< TGridFunction > > walls)
Public Member Functions inherited from ug::NavierStokes::FilterBaseClass< TGridFunction >
virtual void compute_filterwidth ()
FilterBaseClass ()
virtual number width (side_type *side)
virtual number width (vertex_type *vrt)
virtual ~FilterBaseClass ()
Static Public Attributes
static const size_t dim = TGridFunction::dim
dimension
Static Public Attributes inherited from ug::NavierStokes::FilterBaseClass< TGridFunction >
static const size_t dim = TGridFunction::dim
dimension
Protected Member Functions
TImpl & getImpl ()
access to implementation
const TImpl & getImpl () const
const access to implementation
Member Typedef Documentation
domain_type
template<typename TImpl , typename TGridFunction > typedef TGridFunction::domain_type ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::domain_type
domain type
elem_type
template<typename TImpl , typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::grid_base_object ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::elem_type
element type
grid_type
template<typename TImpl , typename TGridFunction > typedef domain_type::grid_type ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::grid_type
grid type
side_type
template<typename TImpl , typename TGridFunction > typedef elem_type::side ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::side_type
side type
type0
template<typename TImpl , typename TGridFunction > typedef FilterBaseClass<TGridFunction>::type0 ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::type0
type1
template<typename TImpl , typename TGridFunction > typedef FilterBaseClass<TGridFunction>::type1 ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::type1
type2
template<typename TImpl , typename TGridFunction > typedef FilterBaseClass<TGridFunction>::type2 ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::type2
vertex_type
template<typename TImpl , typename TGridFunction > typedef Vertex ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::vertex_type
Member Function Documentation
apply() [1/9]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply (PeriodicAttachmentAccessor< side_type, Attachment< type0 > > & aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type0 > > & aaU) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::getImpl(), and SPNULL.
apply() [2/9]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply (PeriodicAttachmentAccessor< side_type, Attachment< type0 > > & aaUHat, SmartPtr< TGridFunction > u) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::getImpl(), and UG_LOG.
apply() [3/9]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply (PeriodicAttachmentAccessor< side_type, Attachment< type1 > > & aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type1 > > & aaU) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::getImpl(), and SPNULL.
apply() [4/9]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply (PeriodicAttachmentAccessor< side_type, Attachment< type2 > > & aaUHat, PeriodicAttachmentAccessor< side_type, Attachment< type2 > > & aaU) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::getImpl(), and SPNULL.
apply() [5/9]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > & aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > & aaU) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::getImpl(), and SPNULL.
apply() [6/9]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type0 > > & aaUHat, SmartPtr< TGridFunction > u) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::LFEID::CROUZEIX_RAVIART, ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::dim, and ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::getImpl().
apply() [7/9]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type1 > > & aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type1 > > & aaU) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::getImpl(), and SPNULL.
apply() [8/9]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply (PeriodicAttachmentAccessor< vertex_type, Attachment< type2 > > & aaUHat, PeriodicAttachmentAccessor< vertex_type, Attachment< type2 > > & aaU) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::getImpl(), and SPNULL.
apply() [9/9]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply (SmartPtr< TGridFunction > u) inline virtual
Reimplemented from ug::NavierStokes::FilterBaseClass< TGridFunction >.
References ug::LFEID::CROUZEIX_RAVIART, and ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::dim.
apply_()
template<typename TImpl , typename TGridFunction > template<typename TElem > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply_ (SmartPtr< TGridFunction > u) inline
References ug::PeriodicAttachmentAccessor< class, class >::access(), SmartPtr< TGridFunction >::get(), ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::getImpl(), and grid().
assignVal() [1/5]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::assignVal (MathSymmetricMatrix< 2 > & v, size_t ind, number value) inline
assignVal() [2/5]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::assignVal (MathSymmetricMatrix< 3 > & v, size_t ind, number value) inline
assignVal() [3/5]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::assignVal (MathVector< 2 > & v, size_t ind, number value) inline
assignVal() [4/5]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::assignVal (MathVector< 3 > & v, size_t ind, number value) inline
assignVal() [5/5]
template<typename TImpl , typename TGridFunction > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::assignVal (number & v, size_t ind, number value) inline
Referenced by ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::copyWallData().
copyWallData() [1/2]
template<typename TImpl , typename TGridFunction > template<typename VType , typename TElem > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::copyWallData (PeriodicAttachmentAccessor< TElem, Attachment< VType > > & acUHat, PeriodicAttachmentAccessor< TElem, Attachment< VType > > & acU, SmartPtr< TGridFunction > u, std::vector< WallObject< TGridFunction > > walls) inline
References SmartPtr< TGridFunction >::get(), and ug::PeriodicBoundaryManager::is_slave().
copyWallData() [2/2]
template<typename TImpl , typename TGridFunction > template<typename VType , typename TElem > void ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::copyWallData (PeriodicAttachmentAccessor< TElem, Attachment< VType > > & acUHat, SmartPtr< TGridFunction > u, std::vector< WallObject< TGridFunction > > walls) inline
References ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::assignVal(), dim, ug::DoFRef(), SmartPtr< TGridFunction >::get(), and ug::PeriodicBoundaryManager::is_slave().
getImpl() [1/2]
template<typename TImpl , typename TGridFunction > TImpl& ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::getImpl () inline protected
access to implementation
Referenced by ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply(), and ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply_().
getImpl() [2/2]
template<typename TImpl , typename TGridFunction > const TImpl& ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::getImpl () const inline protected
const access to implementation
Member Data Documentation
dim
template<typename TImpl , typename TGridFunction > const size_t ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::dim = TGridFunction::dim static
dimension
Referenced by ug::NavierStokes::FilterImplBaseClass< TImpl, TGridFunction >::apply().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/filter.h