Plugins: ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain > Class Template Reference
ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain > Class Template Reference
Plugins » Small Strain Mechanics
#include <small_strain_mech.h>
Public Types
typedef base_type::domain_type domain_type
Domain type.
typedef SmartPtr< CplUserData< number, dim > > NumberExport
typedef base_type::position_type position_type
Position type.
typedef SmartPtr< CplUserData< MathVector< dim >, dim > > VectorExport
Public Types inherited from ug::IElemDisc< TDomain >
typedef TDomain domain_type
typedef TDomain::position_type position_type
Public Member Functions
std::string config_string () const
returns config information of small strain mechanics ElemDisc and material law
template<typename TElem >
void contact_forces_elem_ips_avg (LocalVector &locForce, GridObject *side, TElem *elem, const MathVector< dim > sideCoPos[], int numElemCorners, const LocalVector &locU, vector< DoFIndex > vActiveSetLoc)
template<typename TElem >
void contact_forces_elem_ips_avg (LocalVector &locForce, GridObject *side, TElem *elem, const MathVector< dim > sideCoPos[], int numElemCorners, const LocalVector &locU, std::vector< DoFIndex > vActiveSetLoc)
computing contact forces elementwise by averaging over all integration points
template<typename TSide , typename TElem >
void contact_forces_elem_midpoint (LocalVector &locForce, TSide *side, TElem *elem, const MathVector< dim > sideCoPos[], const LocalVector &locU, vector< DoFIndex > vActiveSetLoc)
template<typename TSide , typename TElem >
void contact_forces_elem_midpoint (LocalVector &locForce, TSide *side, TElem *elem, const MathVector< dim > sideCoPos[], const LocalVector &locU, std::vector< DoFIndex > vActiveSetLoc)
computing contact forces elementwise at every element midpoint
VectorExport displacement ()
NumberExport divergence ()
SmartPtr< IMaterialLaw< TDomain > > get_material_law ()
gets the material law
int get_quad_order ()
gets the quad order
void init_state_variables (const size_t order)
initialize state/"inner" variables
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegularGrid)
type of trial space for each function used
void set_mass_scale (double val)
void set_material_law (SmartPtr< IMaterialLaw< TDomain > > spMatLaw)
adds a material law
void set_output_writer (SmartPtr< MechOutputWriter< TDomain > > spOutWriter)
set an output writer
void set_quad_order (const size_t order)
sets the quad order
template<>
void set_volume_forces (number vel_x, number vel_y)
template<>
void set_volume_forces (number vel_x, number vel_y, number vel_z)
SmallStrainMechanicsElemDisc (const char *functions, const char *subsets)
constructor
virtual ~SmallStrainMechanicsElemDisc ()
destructor
void set_volume_forces (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
void set_volume_forces (number vel)
void set_volume_forces (number vel_x, number vel_y)
void set_volume_forces (number vel_x, number vel_y, number vel_z)
void set_div_factor (SmartPtr< CplUserData< number, dim > > user)
void set_div_factor (number val)
void set_viscous_forces (SmartPtr< CplUserData< MathVector< dim >, dim > > user0, SmartPtr< CplUserData< MathVector< dim >, dim > > user1)
Public Member Functions inherited from ug::IElemDisc< TDomain >
virtual void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier)
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
void check_setup (bool bNonRegularGrid)
void clear_imports ()
virtual void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_elem_loop ()
void do_fsh_elem_loop ()
void do_fsh_err_est_elem_loop ()
void do_fsh_err_est_elem_loop ()
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
ConstSmartPtr< TDomain > domain () const
SmartPtr< TDomain > domain ()
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
virtual void fsh_err_est_elem_loop ()
virtual void fsh_timestep (number time, VectorProxyBase *u)
const FunctionGroup & function_group () const
ConstSmartPtr< FunctionPattern > function_pattern () const
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > & get_elem_modifier ()
IDataImport< dim > & get_import (size_t i)
IElemDisc (const char *functions="", const char *subsets="")
IElemDisc (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
bool is_time_dependent () const
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
const FunctionIndexMapping & map () const
number mass_scale (const size_t timePoint) const
number mass_scale () const
number mass_scale (const size_t timePoint) const
number mass_scale () const
const std::vector< number > & mass_scales () const
const std::vector< number > & mass_scales () const
size_t num_fct () const
size_t num_imports () const
size_t num_subsets () const
virtual void post_assemble_loop ()
virtual void prep_assemble_loop ()
virtual void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
virtual void prep_timestep (number time, VectorProxyBase *u)
void register_import (IDataImport< dim > &Imp)
virtual bool requests_local_time_series ()
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
void set_functions (const std::string &functions)
void set_functions (const std::vector< std::string > &functions)
void set_roid (ReferenceObjectID id, int discType)
void set_stationary (bool bStationaryForced=true)
void set_stationary ()
void set_subsets (const std::vector< std::string > &subsets)
void set_subsets (const std::string &subsets)
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
void set_time_independent ()
void set_time_point (const size_t timePoint)
number stiff_scale (const size_t timePoint) const
number stiff_scale () const
number stiff_scale (const size_t timePoint) const
number stiff_scale () const
const std::vector< number > & stiff_scales () const
const std::vector< number > & stiff_scales () const
const TDomain::subset_handler_type & subset_handler () const
TDomain::subset_handler_type & subset_handler ()
const std::vector< std::string > & symb_fcts () const
const std::vector< std::string > & symb_subsets () const
number time () const
size_t time_point () const
virtual int type () const
virtual bool use_hanging () const
virtual ~IElemDisc ()
Static Public Attributes
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::IElemDisc< TDomain >
static const int dim
Protected Member Functions
template<typename TElem , typename TFEGeom >
void ex_displacement (const LocalVector &u, const MathVector< dim > vGlobIP[], const MathVector< TFEGeom::Type::dim > vLocIP[], const size_t nip, MathVector< dim > vValue[], bool bDeriv, std::vector< std::vector< MathVector< dim > > > vvvDeriv[])
computes the displacements (and derivatives)
template<typename TElem , typename TFEGeom >
void ex_displacement_fe (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< TFEGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< MathVector< dim > > > vvvDeriv[])
computes the displacement
template<typename TElem , typename TFEGeom >
void ex_divergence_fe (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< TFEGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< number > > vvvDeriv[])
computes the divergence of displacement
template<typename TElem , typename TFEGeom >
void lin_def_pressure (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
template<typename TElem , typename TFEGeom >
void lin_def_viscous_forces0 (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
template<typename TElem , typename TFEGeom >
void lin_def_viscous_forces1 (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
template<typename TElem , typename TFEGeom >
void lin_def_volume_forces (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
Protected Member Functions inherited from ug::IElemDisc< TDomain >
virtual void approximation_space_changed ()
void clear_add_fct (ReferenceObjectID id)
void clear_add_fct ()
void remove_add_def_A_elem_fct (ReferenceObjectID id)
void remove_add_def_A_expl_elem_fct (ReferenceObjectID id)
void remove_add_def_M_elem_fct (ReferenceObjectID id)
void remove_add_jac_A_elem_fct (ReferenceObjectID id)
void remove_add_jac_M_elem_fct (ReferenceObjectID id)
void remove_add_rhs_elem_fct (ReferenceObjectID id)
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_elem_loop_fct (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_fsh_timestep_elem_fct (ReferenceObjectID id)
void remove_fsh_timestep_fct (size_t algebra_id)
void remove_prep_elem_fct (ReferenceObjectID id)
void remove_prep_elem_loop_fct (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_timestep_elem_fct (ReferenceObjectID id)
void remove_prep_timestep_fct (size_t algebra_id)
void set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_fct (size_t algebra_id, TAssFunc func)
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
void set_prep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_fct (size_t algebra_id, TAssFunc func)
void update_function_index_mapping ()
Protected Attributes
SmartPtr< DataExport< MathVector< dim >, dim > > m_exDisplacement
Export.
SmartPtr< DataExport< number, dim > > m_exDivergence
Protected Attributes inherited from ug::IElemDisc< TDomain >
bool m_bStationaryForced
FunctionGroup m_fctGrp
FunctionIndexMapping m_fctIndexMap
ReferenceObjectID m_id
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > m_spElemModifier
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
ConstSmartPtr< FunctionPattern > m_spFctPattern
size_t m_timePoint
std::vector< std::string > m_vFct
std::vector< IDataImport< dim > *> m_vIImport
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
std::vector< std::string > m_vSubset
Private Types
typedef IElemDisc< TDomain > base_type
Base class type.
typedef domain_traits< TDomain::dim >::grid_base_object TBaseElem
base element type of associated domain
typedef SmallStrainMechanicsElemDisc< TDomain > this_type
own type
Private Member Functions
template<typename TElem , typename TFEGeom >
void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFEGeom >
void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFEGeom >
void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFEGeom >
void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFEGeom >
void add_rhs_elem (LocalVector &d, GridObject *elem, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFEGeom >
void fsh_elem_loop ()
template<typename TElem , typename TFEGeom >
void fsh_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
size_t num_fct () const
template<typename TElem , typename TFEGeom >
void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
template<typename TElem , typename TFEGeom >
void prep_elem_loop (const ReferenceObjectID roid, const int si)
template<typename TElem , typename TFEGeom >
void prep_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assemble methods
void print_mat_constants (const number lambda, const number mu, const number E, const number v)
prints material constants
void register_all_fe_funcs (int order, int quadOrder)
template<typename TElem , typename TFEGeom >
void register_fe_func ()
void set_assemble_funcs ()
sets the requested assembling routines
void update_geo_elem (TBaseElem *elem, DimFEGeometry< dim > &geo)
updates the geometry for a given element
Private Attributes
bool m_bMatLawPassedToOutWriter
bool m_bOutWriter
bool m_bQuadOrderUserDef
current integration order
DataImport< number, dim > m_imDivergence
Data import for the reaction term.
DataImport< MathVector< dim >, dim > m_imViscousForces [2]
data import for viscous forces
DataImport< MathVector< dim >, dim > m_imVolForce
data import for volume forces
LFEID m_lfeID
current shape function set
double m_massScale
int m_order
current order of disc scheme
int m_quadOrder
SmartPtr< MathTensor4< dim, dim, dim, dim > > m_spElastTensor
elasticity tensor
SmartPtr< IMaterialLaw< TDomain > > m_spMatLaw
material law
SmartPtr< MechOutputWriter< TDomain > > m_spOutWriter
output writer
Detailed Description
template<typename TDomain>
class ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >
This class assembles the equation of the static linear elasticity problem:
(1) - div(sigma) = f (2) sigma = C : epsilon (3) epsilon = 1/2 (nabla_u + nabla_u^T)
boundary conditions.
As common in the linear theory we identify the deformed configuration with the undeformed configuration. Therefore we do not have to distinguish between different stress measures. Here we use a pure displacement-ansatz to solve the coupled system above, i.e. the kinematic equation for the linearized strain tensor epsilon (3) is inserted in the material law (2) and the resulting stress tensor sigma is introduced in the momentum balance equation (1). Therein, the computation of the strain and the stress tensor is performed at the integration points! Following this approach, the only remaining unknown function is the displacement field u!
: in case of linear elasticity one can implement the voigt notation (exploiting symmetry of sigma and epsilon)
In order to compute the eigenfrequencies of a system by means of the eigenvalue problem the second time derivatives of u
rho * {^2 u}{^2 t}
are considered in the momentum equation (1) and deliver a contribution to the mass matrix.
References:
D. Braess. Finite Elemente. Theorie, schnelle Loeser und Anwendungen in der
Elastizitaetstheorie, Springer
R. Prohl. Ein verallgemeinerter Plastizitaetsalgorithmus zur numerischen Behandlung von elasto-plastischen Materialmodellen unter groen Deformationen. Dissertation, Universitt Frankfurt (2015).
M. Rupp. Berechnung der Resonanzschwingungen einer Gitarrendecke.
(Diplomarbeit, 2009, Universitaet Heidelberg)
Member Typedef Documentation
base_type
template<typename TDomain> typedef IElemDisc<TDomain> ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::base_type private
Base class type.
domain_type
template<typename TDomain> typedef base_type::domain_type ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::domain_type
Domain type.
NumberExport
template<typename TDomain> typedef SmartPtr<CplUserData<number, dim> > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::NumberExport
position_type
template<typename TDomain> typedef base_type::position_type ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::position_type
Position type.
TBaseElem
template<typename TDomain> typedef domain_traits<TDomain::dim>::grid_base_object ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::TBaseElem private
base element type of associated domain
this_type
template<typename TDomain> typedef SmallStrainMechanicsElemDisc<TDomain> ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::this_type private
own type
VectorExport
template<typename TDomain> typedef SmartPtr<CplUserData<MathVector<dim>, dim> > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::VectorExport
Constructor & Destructor Documentation
SmallStrainMechanicsElemDisc()
template<typename TDomain > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc (const char * functions, const char * subsets)
constructor
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::dim, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_bQuadOrderUserDef, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_imDivergence, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_imViscousForces, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_imVolForce, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_massScale, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_order, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_quadOrder, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct(), ug::IElemDisc< TDomain >::register_import(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_assemble_funcs(), ug::IDataImport< dim >::set_rhs_part(), UG_THROW, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::~SmallStrainMechanicsElemDisc().
~SmallStrainMechanicsElemDisc()
template<typename TDomain > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::~SmallStrainMechanicsElemDisc () virtual
destructor
References ug::IElemDisc< TDomain >::domain(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_displacement_fe(), grid(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_spMatLaw.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc().
Member Function Documentation
add_def_A_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::add_def_A_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
Reimplemented from ug::IElemDisc< TDomain >.
References dim, and SMALL_STRAIN_MECH_PROFILE_BEGIN.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
add_def_M_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::add_def_M_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
Reimplemented from ug::IElemDisc< TDomain >.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
add_jac_A_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::add_jac_A_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
Reimplemented from ug::IElemDisc< TDomain >.
References dim, and SMALL_STRAIN_MECH_PROFILE_BEGIN.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
add_jac_M_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::add_jac_M_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
Reimplemented from ug::IElemDisc< TDomain >.
References dim.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
add_rhs_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::add_rhs_elem (LocalVector & d, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
Reimplemented from ug::IElemDisc< TDomain >.
References VecDot().
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
config_string()
template<typename TDomain> std::string ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::config_string () const inline
returns config information of small strain mechanics ElemDisc and material law
References ug::ConfigShift(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_bQuadOrderUserDef, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_lfeID, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_massScale, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_order, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_quadOrder, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_spMatLaw.
contact_forces_elem_ips_avg() [1/2]
template<typename TDomain> template<typename TElem > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::contact_forces_elem_ips_avg (LocalVector & locForce, GridObject * side, TElem * elem, const MathVector< dim > sideCoPos[], int numElemCorners, const LocalVector & locU, vector< DoFIndex > vActiveSetLoc)
References dim, ug::LFEID::LAGRANGE, normal, ug::GridObject::reference_object_id(), UG_CATCH_THROW, ug::VecLength(), and ug::VecScale().
contact_forces_elem_ips_avg() [2/2]
template<typename TDomain> template<typename TElem > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::contact_forces_elem_ips_avg (LocalVector & locForce, GridObject * side, TElem * elem, const MathVector< dim > sideCoPos[], int numElemCorners, const LocalVector & locU, std::vector< DoFIndex > vActiveSetLoc)
computing contact forces elementwise by averaging over all integration points
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_mass_scale().
contact_forces_elem_midpoint() [1/2]
template<typename TDomain> template<typename TSide , typename TElem > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::contact_forces_elem_midpoint (LocalVector & locForce, TSide * side, TElem * elem, const MathVector< dim > sideCoPos[], const LocalVector & locU, vector< DoFIndex > vActiveSetLoc)
References ug::CollectCornerCoordinates(), dim, ug::LocalFiniteElementProvider::get(), ug::ReferenceMappingProvider::get(), ug::LFEID::LAGRANGE, normal, ug::ROID_TRIANGLE, UG_THROW, ug::VecLength(), and ug::VecScale().
contact_forces_elem_midpoint() [2/2]
template<typename TDomain> template<typename TSide , typename TElem > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::contact_forces_elem_midpoint (LocalVector & locForce, TSide * side, TElem * elem, const MathVector< dim > sideCoPos[], const LocalVector & locU, std::vector< DoFIndex > vActiveSetLoc)
computing contact forces elementwise at every element midpoint
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_mass_scale().
displacement()
template<typename TDomain> VectorExport ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::displacement () inline
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_exDisplacement.
divergence()
template<typename TDomain> NumberExport ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::divergence () inline
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_exDivergence.
ex_displacement()
template<typename TDomain> template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_displacement (const LocalVector & u, const MathVector< dim > vGlobIP[], const MathVector< TFEGeom::Type::dim > vLocIP[], const size_t nip, MathVector< dim > vValue[], bool bDeriv, std::vector< std::vector< MathVector< dim > > > vvvDeriv[]) protected
computes the displacements (and derivatives)
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
ex_displacement_fe()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_displacement_fe (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< TFEGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< MathVector< dim > > > vvvDeriv[]) protected
computes the displacement
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::dim, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_divergence_fe(), ug::GeomProvider< TGeom >::get(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_lfeID, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_quadOrder, ug::LocalDoFSet::num_sh(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), UG_CATCH_THROW, and ug::VecSet().
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::~SmallStrainMechanicsElemDisc().
ex_divergence_fe()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_divergence_fe (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< TFEGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< number > > vvvDeriv[]) protected
computes the divergence of displacement
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::dim, ug::GeomProvider< TGeom >::get(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_lfeID, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_quadOrder, ug::MatVecMult(), ug::LocalDoFSet::num_sh(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::register_all_fe_funcs(), UG_CATCH_THROW, ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_displacement_fe().
fsh_elem_loop()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::fsh_elem_loop () private virtual
Reimplemented from ug::IElemDisc< TDomain >.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
fsh_timestep_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::fsh_timestep_elem (const number time, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
Reimplemented from ug::IElemDisc< TDomain >.
References SMALL_STRAIN_MECH_PROFILE_BEGIN, and UG_CATCH_THROW.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
get_material_law()
template<typename TDomain> SmartPtr<IMaterialLaw<TDomain> > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::get_material_law () inline
gets the material law
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_spMatLaw.
Referenced by ug::SmallStrainMechanics::plastic_ip_elem().
get_quad_order()
template<typename TDomain> int ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::get_quad_order () inline
gets the quad order
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_quadOrder.
Referenced by ug::SmallStrainMechanics::plastic_ip_elem().
init_state_variables()
template<typename TDomain > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::init_state_variables (const size_t order)
initialize state/"inner" variables
References dim, grid(), ug::DimFEGeometry< TWorldDim, TRefDim >::num_ip(), SMALL_STRAIN_MECH_PROFILE_BEGIN, SMALL_STRAIN_MECH_PROFILE_END, and UG_LOG.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_mass_scale().
lin_def_pressure()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::lin_def_pressure (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the pressure: $$ { d(u,I_1), ... d(u,I_n)}{ I_i} $$ (since d is a vector, we obtain a bunch of vectors)
References UG_ASSERT.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
lin_def_viscous_forces0()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::lin_def_viscous_forces0 (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the volume forces $$ { d(u,I_1), ... d(u,I_n)}{ I_i} $$ (since d is a vector, we obtain a bunch of diagonal matrices)
References UG_ASSERT, VecDot(), and VecScale().
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
lin_def_viscous_forces1()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::lin_def_viscous_forces1 (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the volume forces $$ { d(u,I_1), ... d(u,I_n)}{ I_i} $$ (since d is a vector, we obtain a bunch of diagonal matrices)
References UG_ASSERT, VecDot(), and VecScale().
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
lin_def_volume_forces()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::lin_def_volume_forces (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the volume forces $$ { d(u,I_1), ... d(u,I_n)}{ I_i} $$ (since d is a vector, we obtain a bunch of diagonal matrices)
References UG_ASSERT.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
num_fct()
template<typename TDomain> size_t ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct () const inline private
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::add_def_A_elem(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::add_def_M_elem(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::add_jac_A_elem(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::add_jac_M_elem(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::add_rhs_elem(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::dim, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_displacement(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::fsh_elem_loop(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::fsh_timestep_elem(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::lin_def_pressure(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::lin_def_viscous_forces0(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::lin_def_viscous_forces1(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::lin_def_volume_forces(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::prep_elem(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::prep_elem_loop(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::prep_timestep_elem(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::print_mat_constants(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::register_all_fe_funcs(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::register_fe_func(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_assemble_funcs(), ug::IElemDisc< TDomain >::time(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::update_geo_elem().
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc().
prep_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::prep_elem (const LocalVector & u, GridObject * elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[]) private virtual
Reimplemented from ug::IElemDisc< TDomain >.
References UG_CATCH_THROW.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
prep_elem_loop()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::prep_elem_loop (const ReferenceObjectID roid, const int si) private virtual
Reimplemented from ug::IElemDisc< TDomain >.
References dim, UG_CATCH_THROW, and UG_THROW.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
prep_timestep_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::prep_timestep_elem (const number time, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
assemble methods
Reimplemented from ug::IElemDisc< TDomain >.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
prepare_setting()
template<typename TDomain> virtual void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::prepare_setting (const std::vector< LFEID > & vLfeID, bool bNonRegularGrid) inline virtual
type of trial space for each function used
Implements ug::IElemDisc< TDomain >.
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_lfeID, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_order, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_assemble_funcs(), and UG_THROW.
print_mat_constants()
template<typename TDomain> void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::print_mat_constants (const number lambda, const number mu, const number E, const number v) private
prints material constants
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
register_all_fe_funcs()
template<typename TDomain> void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::register_all_fe_funcs (int order, int quadOrder) private
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_divergence_fe(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
register_fe_func()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::register_fe_func () private
References ug::IElemDisc< TDomain >::clear_add_fct(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_exDisplacement, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_exDivergence, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_imDivergence, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_imViscousForces, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_imVolForce, ug::IElemDisc< TDomain >::set_add_def_A_elem_fct(), ug::IElemDisc< TDomain >::set_add_def_M_elem_fct(), ug::IElemDisc< TDomain >::set_add_jac_A_elem_fct(), ug::IElemDisc< TDomain >::set_add_jac_M_elem_fct(), ug::IElemDisc< TDomain >::set_add_rhs_elem_fct(), ug::DataImport< TData, dim >::set_fct(), ug::IElemDisc< TDomain >::set_fsh_elem_loop_fct(), ug::IElemDisc< TDomain >::set_fsh_timestep_elem_fct(), ug::IElemDisc< TDomain >::set_prep_elem_fct(), ug::IElemDisc< TDomain >::set_prep_elem_loop_fct(), and ug::IElemDisc< TDomain >::set_prep_timestep_elem_fct().
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
set_assemble_funcs()
template<typename TDomain > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_assemble_funcs () private
sets the requested assembling routines
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::prepare_setting(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc().
set_div_factor() [1/2]
template<typename TDomain > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_div_factor (SmartPtr< CplUserData< number, dim > > user)
This method sets a pressure term for rhs. A zero value is assumed as default. p * sum dx_i Phi_sh,i
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_output_writer().
set_div_factor() [2/2]
template<typename TDomain > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_div_factor (number val)
This method sets a pressure term for rhs. A zero value is assumed as default. p * sum dx_i Phi_sh,i
References make_sp().
set_mass_scale()
template<typename TDomain> void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_mass_scale (double val) inline
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::contact_forces_elem_ips_avg(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::contact_forces_elem_midpoint(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::init_state_variables(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_massScale.
set_material_law()
template<typename TDomain> void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_material_law (SmartPtr< IMaterialLaw< TDomain > > spMatLaw) inline
adds a material law
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_spMatLaw.
set_output_writer()
template<typename TDomain> void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_output_writer (SmartPtr< MechOutputWriter< TDomain > > spOutWriter) inline
set an output writer
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_bOutWriter, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_spOutWriter, ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_div_factor(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_viscous_forces(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_volume_forces().
set_quad_order()
template<typename TDomain> void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_quad_order (const size_t order) inline
sets the quad order
References ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_bQuadOrderUserDef, and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_quadOrder.
set_viscous_forces()
template<typename TDomain > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_viscous_forces (SmartPtr< CplUserData< MathVector< dim >, dim > > user0, SmartPtr< CplUserData< MathVector< dim >, dim > > user1)
This methods sets rhs for "viscous stresses" v0^T (gradPhi +gradPhi^T) v1
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_output_writer().
set_volume_forces() [1/6]
template<> void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< Domain2d >::set_volume_forces (number vel_x, number vel_y)
set_volume_forces() [2/6]
template<> void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< Domain3d >::set_volume_forces (number vel_x, number vel_y, number vel_z)
References dim.
set_volume_forces() [3/6]
template<typename TDomain > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_volume_forces (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
set volume forces for rhs: Phi * F = Phi * (grad p)
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_output_writer().
set_volume_forces() [4/6]
template<typename TDomain > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_volume_forces (number vel)
set volume forces for rhs: Phi * F = Phi * (grad p)
set_volume_forces() [5/6]
template<typename TDomain > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_volume_forces (number vel_x, number vel_y)
set volume forces for rhs: Phi * F = Phi * (grad p)
References dim, and UG_THROW.
set_volume_forces() [6/6]
template<typename TDomain > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_volume_forces (number vel_x, number vel_y, number vel_z)
set volume forces for rhs: Phi * F = Phi * (grad p)
References dim, and UG_THROW.
update_geo_elem()
template<typename TDomain > void ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::update_geo_elem (TBaseElem * elem, DimFEGeometry< dim > & geo) private
updates the geometry for a given element
References UG_CATCH_THROW, and ug::DimFEGeometry< TWorldDim, TRefDim >::update().
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct().
Member Data Documentation
dim
template<typename TDomain> const int ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::dim = base_type::dim static
World dimension.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_displacement_fe(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_divergence_fe(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::num_fct(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc().
m_bMatLawPassedToOutWriter
template<typename TDomain> bool ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_bMatLawPassedToOutWriter private
m_bOutWriter
template<typename TDomain> bool ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_bOutWriter private
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_output_writer().
m_bQuadOrderUserDef
template<typename TDomain> bool ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_bQuadOrderUserDef private
current integration order
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::config_string(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_quad_order(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc().
m_exDisplacement
template<typename TDomain> SmartPtr<DataExport<MathVector<dim>, dim> > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_exDisplacement protected
Export.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::displacement(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::register_fe_func().
m_exDivergence
template<typename TDomain> SmartPtr<DataExport<number, dim> > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_exDivergence protected
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::divergence(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::register_fe_func().
m_imDivergence
template<typename TDomain> DataImport<number, dim> ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_imDivergence private
Data import for the reaction term.
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::register_fe_func(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc().
m_imViscousForces
template<typename TDomain> DataImport<MathVector<dim>, dim > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_imViscousForces[2] private
data import for viscous forces
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::register_fe_func(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc().
m_imVolForce
template<typename TDomain> DataImport<MathVector<dim>, dim > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_imVolForce private
data import for volume forces
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::register_fe_func(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc().
m_lfeID
template<typename TDomain> LFEID ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_lfeID private
current shape function set
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::config_string(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_displacement_fe(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_divergence_fe(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::prepare_setting().
m_massScale
template<typename TDomain> double ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_massScale private
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::config_string(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_mass_scale(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc().
m_order
template<typename TDomain> int ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_order private
current order of disc scheme
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::config_string(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::prepare_setting(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc().
m_quadOrder
template<typename TDomain> int ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_quadOrder private
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::config_string(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_displacement_fe(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::ex_divergence_fe(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::get_quad_order(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_quad_order(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::SmallStrainMechanicsElemDisc().
m_spElastTensor
template<typename TDomain> SmartPtr<MathTensor4<dim,dim,dim,dim> > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_spElastTensor private
elasticity tensor
m_spMatLaw
template<typename TDomain> SmartPtr<IMaterialLaw<TDomain> > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_spMatLaw private
material law
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::config_string(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::get_material_law(), ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_material_law(), and ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::~SmallStrainMechanicsElemDisc().
m_spOutWriter
template<typename TDomain> SmartPtr<MechOutputWriter<TDomain> > ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::m_spOutWriter private
output writer
Referenced by ug::SmallStrainMechanics::SmallStrainMechanicsElemDisc< TDomain >::set_output_writer().
The documentation for this class was generated from the following files:
/home/sreiter/ug4-docs/plugins/SmallStrainMechanics/small_strain_mech.h
/home/sreiter/ug4-docs/plugins/SmallStrainMechanics/contact/contact_impl.h
/home/sreiter/ug4-docs/plugins/SmallStrainMechanics/small_strain_mech.cpp