Plugins: ug::promesh::Mesh Class Reference
ug::promesh::Mesh Class Reference
Plugins » ProMesh
#include <mesh.h>
Public Types
typedef ElementIterator< Edge > edge_iter_t
typedef ElementIterator< Face > face_iter_t
typedef Grid::FaceAttachmentAccessor< normal_attachment_t > normal_accessor_t
typedef ANormal normal_attachment_t
typedef Grid::VertexAttachmentAccessor< position_attachment_t > position_accessor_t
typedef APosition position_attachment_t
typedef SmartPtr< edge_iter_t > sp_edge_iter_t
typedef SmartPtr< face_iter_t > sp_face_iter_t
typedef SmartPtr< vertex_iter_t > sp_vertex_iter_t
typedef SmartPtr< volume_iter_t > sp_volume_iter_t
typedef ElementIterator< Vertex > vertex_iter_t
typedef Grid::VolumeAttachmentAccessor< volume_constraint_attachment_t > volume_constraint_accessor_t
typedef ANumber volume_constraint_attachment_t
typedef ElementIterator< Volume > volume_iter_t
Public Member Functions
void clear_volume_constraints ()
clears the volume constraints (removes the attachment)
SubsetHandler & crease_handler ()
Edge * create_edge (Vertex *v0, Vertex *v1)
Volume * create_hexahedron (Vertex *v0, Vertex *v1, Vertex *v2, Vertex *v3, Vertex *v4, Vertex *v5, Vertex *v6, Vertex *v7)
Volume * create_octahedron (Vertex *v0, Vertex *v1, Vertex *v2, Vertex *v3, Vertex *v4, Vertex *v5)
Volume * create_prism (Vertex *v0, Vertex *v1, Vertex *v2, Vertex *v3, Vertex *v4, Vertex *v5)
Volume * create_pyramid (Vertex *v0, Vertex *v1, Vertex *v2, Vertex *v3, Vertex *v4)
Face * create_quadrilateral (Vertex *v0, Vertex *v1, Vertex *v2, Vertex *v3)
Volume * create_tetrahedron (Vertex *v0, Vertex *v1, Vertex *v2, Vertex *v3)
Face * create_triangle (Vertex *v0, Vertex *v1, Vertex *v2)
Vertex * create_vertex (const vector3 &p)
element creation and deletion
SmartPtr< Geometry< 3, 3 > > geometry ()
ConstSmartPtr< Geometry< 3, 3 > > geometry () const
Grid & grid ()
Mesh ()
Mesh (const Mesh &m)
normal_accessor_t & normal_accessor ()
returns accessor to face normals
normal_attachment_t & normal_attachment ()
vector3 & pivot ()
vector3 & position (Vertex *v)
position_accessor_t & position_accessor ()
returns accessor to vertex positions
position_attachment_t & position_attachment ()
ProjectionHandler & projection_handler ()
Selector & selector ()
void set_pivot (const vector3 &pivot)
void set_position (Vertex *v, const vector3 &p)
SubsetHandler & subset_handler ()
volume_constraint_accessor_t & volume_constraint_accessor ()
returns accessor to volume constraints.
volume_constraint_attachment_t & volume_constraint_attachment ()
returns the volume constraint attachment
virtual ~Mesh ()
template<class TElem >
SmartPtr< ElementIterator< typename TElem::grid_base_object > > begin ()
returns an iterator to the first element of the specified type
template<class TElem >
SmartPtr< ElementIterator< typename TElem::grid_base_object > > selection_begin ()
returns an iterator to the first element of the specified type
template<class TElem >
SmartPtr< ElementIterator< typename TElem::grid_base_object > > subset_begin (int si)
returns an iterator to the first element of the specified type
template<class TElem >
SmartPtr< ElementIterator< typename TElem::grid_base_object > > end ()
returns an iterator to the position behind the last element of the specified type
template<class TElem >
SmartPtr< ElementIterator< typename TElem::grid_base_object > > selection_end ()
returns an iterator to the position behind the last element of the specified type
template<class TElem >
SmartPtr< ElementIterator< typename TElem::grid_base_object > > subset_end (int si)
returns an iterator to the position behind the last element of the specified type
Protected Member Functions
void init ()
void volume_constraints_required ()
Protected Attributes
normal_accessor_t m_aaNorm
position_accessor_t m_aaPos
volume_constraint_accessor_t m_aaVolumeConstraint
volume_constraint_attachment_t m_aVolumeConstraint
SubsetHandler m_creaseHandler
SmartPtr< Geometry< 3, 3 > > m_geometry
Grid m_grid
vector3 m_pivot
ProjectionHandler m_projectionHandler
Selector m_selector
SubsetHandler m_subsetHandler
Member Typedef Documentation
edge_iter_t
typedef ElementIterator<Edge> ug::promesh::Mesh::edge_iter_t
face_iter_t
typedef ElementIterator<Face> ug::promesh::Mesh::face_iter_t
normal_accessor_t
typedef Grid::FaceAttachmentAccessor<normal_attachment_t> ug::promesh::Mesh::normal_accessor_t
normal_attachment_t
typedef ANormal ug::promesh::Mesh::normal_attachment_t
position_accessor_t
typedef Grid::VertexAttachmentAccessor<position_attachment_t> ug::promesh::Mesh::position_accessor_t
position_attachment_t
typedef APosition ug::promesh::Mesh::position_attachment_t
sp_edge_iter_t
typedef SmartPtr<edge_iter_t> ug::promesh::Mesh::sp_edge_iter_t
sp_face_iter_t
typedef SmartPtr<face_iter_t> ug::promesh::Mesh::sp_face_iter_t
sp_vertex_iter_t
typedef SmartPtr<vertex_iter_t> ug::promesh::Mesh::sp_vertex_iter_t
sp_volume_iter_t
typedef SmartPtr<volume_iter_t> ug::promesh::Mesh::sp_volume_iter_t
vertex_iter_t
typedef ElementIterator<Vertex> ug::promesh::Mesh::vertex_iter_t
volume_constraint_accessor_t
typedef Grid::VolumeAttachmentAccessor<volume_constraint_attachment_t> ug::promesh::Mesh::volume_constraint_accessor_t
volume_constraint_attachment_t
typedef ANumber ug::promesh::Mesh::volume_constraint_attachment_t
volume_iter_t
typedef ElementIterator<Volume> ug::promesh::Mesh::volume_iter_t
Constructor & Destructor Documentation
Mesh() [1/2]
ug::promesh::Mesh::Mesh ()
References init().
Mesh() [2/2]
ug::promesh::Mesh::Mesh (const Mesh & m)
References init(), and m_grid.
~Mesh()
virtual ug::promesh::Mesh::~Mesh () inline virtual
Member Function Documentation
begin()
template<class TElem > SmartPtr<ElementIterator<typename TElem::grid_base_object> > ug::promesh::Mesh::begin () inline
returns an iterator to the first element of the specified type
Note
This iterator is intended for use through bindings only! If you're actually writing C++ code, please use the iterators of the Grid/Selector/SubsetHandler classes directly.
References grid(), and make_sp().
Referenced by ug::promesh::CreateShrinkGeometry().
clear_volume_constraints()
void ug::promesh::Mesh::clear_volume_constraints () inline
clears the volume constraints (removes the attachment)
References ug::Grid::detach_from_volumes(), ug::AttachmentAccessor< class, class, class >::invalidate(), m_aaVolumeConstraint, m_aVolumeConstraint, m_grid, and ug::AttachmentAccessor< class, class, class >::valid().
Referenced by ug::promesh::ClearVolumeConstraints().
crease_handler()
SubsetHandler& ug::promesh::Mesh::crease_handler () inline
References m_creaseHandler.
Referenced by ug::promesh::AdjustEdgeLength(), ug::promesh::AdjustEdgeLengthExtended(), ug::promesh::ClearMarks(), ug::promesh::CopySelectedElements(), ug::promesh::CopySelection(), ug::promesh::LoadMesh(), ug::promesh::MarkCornersOfMarkedEdges(), ug::promesh::MarkCreaseEdges(), ug::promesh::MarkSelection(), ug::promesh::RefineSmooth(), ug::promesh::Retriangulate(), ug::promesh::SaveMesh(), ug::promesh::SelectMarkedEdges(), ug::promesh::SelectMarkedFaces(), ug::promesh::SelectMarkedVertices(), and ug::promesh::UnmarkSelection().
create_edge()
Edge * ug::promesh::Mesh::create_edge (Vertex * v0, Vertex * v1)
References ug::Grid::create(), and grid().
create_hexahedron()
Volume * ug::promesh::Mesh::create_hexahedron (Vertex * v0, Vertex * v1, Vertex * v2, Vertex * v3, Vertex * v4, Vertex * v5, Vertex * v6, Vertex * v7)
References ug::Grid::create(), and grid().
create_octahedron()
Volume * ug::promesh::Mesh::create_octahedron (Vertex * v0, Vertex * v1, Vertex * v2, Vertex * v3, Vertex * v4, Vertex * v5)
References ug::Grid::create(), and grid().
create_prism()
Volume * ug::promesh::Mesh::create_prism (Vertex * v0, Vertex * v1, Vertex * v2, Vertex * v3, Vertex * v4, Vertex * v5)
References ug::Grid::create(), and grid().
create_pyramid()
Volume * ug::promesh::Mesh::create_pyramid (Vertex * v0, Vertex * v1, Vertex * v2, Vertex * v3, Vertex * v4)
References ug::Grid::create(), and grid().
create_quadrilateral()
Face * ug::promesh::Mesh::create_quadrilateral (Vertex * v0, Vertex * v1, Vertex * v2, Vertex * v3)
References ug::Grid::create(), and grid().
create_tetrahedron()
Volume * ug::promesh::Mesh::create_tetrahedron (Vertex * v0, Vertex * v1, Vertex * v2, Vertex * v3)
References ug::Grid::create(), and grid().
create_triangle()
Face * ug::promesh::Mesh::create_triangle (Vertex * v0, Vertex * v1, Vertex * v2)
References ug::Grid::create(), and grid().
create_vertex()
Vertex * ug::promesh::Mesh::create_vertex (const vector3 & p)
element creation and deletion
References ug::Grid::create(), grid(), p, and set_position().
end()
template<class TElem > SmartPtr<ElementIterator<typename TElem::grid_base_object> > ug::promesh::Mesh::end () inline
returns an iterator to the position behind the last element of the specified type
Note
This iterator is intended for use through bindings only! If you're actually writing C++ code, please use the iterators of the Grid/Selector/SubsetHandler classes directly.
References grid(), and make_sp().
geometry() [1/2]
SmartPtr<Geometry<3, 3> > ug::promesh::Mesh::geometry () inline
References m_geometry.
Referenced by ug::promesh::ExtrudeLayersAndAddProjector().
geometry() [2/2]
ConstSmartPtr<Geometry<3, 3> > ug::promesh::Mesh::geometry () const inline
References m_geometry.
grid()
Grid& ug::promesh::Mesh::grid () inline
References m_grid.
Referenced by ug::promesh::AdaptSurfaceToCylinder(), ug::promesh::AdjustEdgeLength(), ug::promesh::AdjustEdgeLengthExtended(), ug::promesh::AdjustEdgeOrientation(), ug::promesh::AdjustSubsetsForUG3(), ug::promesh::AssignSubsetsByAspectRatio(), ug::promesh::AssignSubsetsByQuality(), ug::promesh::AssignSubsetsFromRaster_IMPL(), begin(), ug::promesh::CollapseEdge(), ug::promesh::ConvertToQuadrilaterals(), ug::promesh::ConvertToTetrahedra(), ug::promesh::ConvertToTriangles(), ug::promesh::CopySelectedElements(), ug::promesh::CopySelection(), create_edge(), create_hexahedron(), create_octahedron(), create_prism(), create_pyramid(), create_quadrilateral(), create_tetrahedron(), create_triangle(), create_vertex(), ug::promesh::CreateBox(), ug::promesh::CreateCircle(), ug::promesh::CreateEdge(), ug::promesh::CreateFace(), ug::promesh::CreateHexahedraFromSelectedPrisms(), ug::promesh::CreatePlane(), ug::promesh::CreatePrism(), ug::promesh::CreatePyramid(), ug::promesh::CreateShrinkElements(), ug::promesh::CreateShrinkGeometry(), ug::promesh::CreateSphere(), ug::promesh::CreateTetrahedron(), ug::promesh::CreateTKD(), ug::promesh::CreateTKDWithOuterLayer(), ug::promesh::CreateVertex(), ug::promesh::CreateVolume(), ug::promesh::CSGFaceOperation(), ug::promesh::Duplicate(), end(), ug::promesh::EraseSelectedElements(), ug::promesh::EraseSubset(), ug::promesh::ExportToUG3(), ug::promesh::ExtrudeAlongNormal(), ug::promesh::ExtrudeAndMove(), ug::promesh::ExtrudeAndScale(), ug::promesh::ExtrudeCylinders(), ug::promesh::ExtrudeFacesWithTets(), ug::promesh::ExtrudeLayers(), ug::promesh::ExtrudeLayersAndAddProjector(), ug::promesh::ExtrudeToThickness(), ug::promesh::FixFaceOrientation(), ug::promesh::FixFaceSubsetOrientations(), ug::promesh::FixVolumeOrientation(), ug::promesh::GetBoundingBox(), ug::promesh::HangingNodeRefine(), ug::promesh::InsertCenter(), ug::promesh::IntersectCloseEdges(), ug::promesh::InvertFaceOrientation(), ug::promesh::InvertSelection(), ug::promesh::LaplacianSmooth(), ug::promesh::LoadMesh(), ug::promesh::MarkCornersOfMarkedEdges(), ug::promesh::MarkCreaseEdges(), ug::promesh::MeasureGridArea(), ug::promesh::MeasureGridLength(), ug::promesh::MeasureGridVolume(), ug::promesh::MergeAtCenter(), ug::promesh::MergeAtFirst(), ug::promesh::MergeAtLast(), ug::promesh::MeshLayerBoundaries(), ug::promesh::MeshLayers(), ug::promesh::Mirror(), ug::promesh::MoveAlongNormal(), ug::promesh::MoveMeshTo(), ug::promesh::MoveVerticesAlongEdges(), ug::promesh::MoveVerticesToEdgeLength(), ug::promesh::MoveVerticesToProjectedEdgeLength(), ug::promesh::PrintAspectRatioHistogram(), ug::promesh::PrintAspectRatios(), ug::promesh::ProjectToLayer(), ug::promesh::ProjectToLimitPLoop(), ug::promesh::ProjectToLimitSmoothBoundary(), ug::promesh::ProjectToTopLayer(), ug::promesh::ProjectVerticesToCloseEdges(), ug::promesh::ProjectVerticesToCloseFaces(), ug::promesh::Refine(), ug::promesh::RefineSmooth(), ug::promesh::RefineWithSnapPointsOrtho(), ug::promesh::RegularizingRefinement(), ug::promesh::RegularizingRefinement_IMPL(), ug::promesh::RemoveDoubleEdges(), ug::promesh::RemoveDoubleFaces(), ug::promesh::RemoveDoubles(), ug::promesh::ReplaceLowValenceVertices(), ug::promesh::ReplaceValence3Vertices(), ug::promesh::ResolveEdgeIntersection(), ug::promesh::ResolveSelfIntersections(), ug::promesh::ResolveTriangleIntersections(), ug::promesh::Retetrahedralize(), ug::promesh::Retriangulate(), ug::promesh::SaveMesh(), ug::promesh::SelectAll(), ug::promesh::SelectAllEdges(), ug::promesh::SelectAllFaces(), ug::promesh::SelectAllVertices(), ug::promesh::SelectAllVolumes(), ug::promesh::SelectAnisotropicElements(), ug::promesh::SelectBentQuadrilaterals(), ug::promesh::SelectBoundaryEdges(), ug::promesh::SelectBoundaryFaces(), ug::promesh::SelectBoundaryVertices(), ug::promesh::SelectClosestEdge(), ug::promesh::SelectCreaseEdges(), ug::promesh::SelectDegenerateFaces(), ug::promesh::SelectEdgeByIndex(), ug::promesh::SelectElemByCoordinate(), ug::promesh::SelectElementsBySplitPlane(), ug::promesh::SelectElementsInBox(), ug::promesh::SelectElementsInCoordinateRange(), ug::promesh::SelectElementsInCylinder(), ug::promesh::SelectFaceByIndex(), ug::promesh::SelectFacesByNormal(), ug::promesh::SelectInnerEdges(), ug::promesh::SelectInnerFaces(), ug::promesh::SelectInnerVertices(), ug::promesh::SelectInterfaceElements(), ug::promesh::SelectIntersectingTriangles(), ug::promesh::SelectLinkedBoundaryEdges(), ug::promesh::SelectLinkedBoundaryFaces(), ug::promesh::SelectLinkedManifoldFaces(), ug::promesh::SelectLongEdges(), ug::promesh::SelectNonManifoldEdges(), ug::promesh::SelectShortEdges(), ug::promesh::SelectSlivers(), ug::promesh::SelectSubset(), ug::promesh::SelectSubsetKinkVertices(), ug::promesh::SelectUnassignedElements(), ug::promesh::SelectUnconnectedVertices(), ug::promesh::SelectUnorientableVolumes(), ug::promesh::SelectVertexByIndex(), ug::promesh::SelectVolumeByIndex(), ug::promesh::SelectVolumesByType(), ug::promesh::SeparateDegeneratedBoundaryFaceSubsets(), ug::promesh::SeparateFacesByEdgeSubsets(), ug::promesh::SeparateFacesBySelectedEdges(), ug::promesh::SeparateFaceSubsetByNormal(), ug::promesh::SeparateFaceSubsetsByNormal(), ug::promesh::SeparateVolumesByFaceSubsets(), ug::promesh::SeparateVolumesBySelectedFaces(), ug::promesh::SetPivotToMeshCenter(), ug::promesh::SimplifyPolylines(), ug::promesh::SimplifySmoothedPolylines(), ug::promesh::SlopeSmooth(), ug::promesh::SnapToHorizontalRaster(), ug::promesh::SnapVerticesToVertices(), ug::promesh::SplitEdge(), ug::promesh::SwapEdge(), ug::promesh::TangentialSmooth(), ug::promesh::Tetrahedralize(), ug::promesh::TriangleFill(), ug::promesh::WeightedEdgeSmooth(), ug::promesh::WeightedFaceSmooth(), and ug::promesh::WeightedNormalSmooth().
init()
void ug::promesh::Mesh::init () protected
References AttachmentAccessor< Vertex, TAttachment >::access(), ug::aNormal, ug::aPosition, ug::Selector::assign_grid(), ug::GridSubsetHandler::assign_grid(), ug::Grid::attach_to_faces(), ug::Grid::attach_to_vertices(), ug::ISubsetHandler::enable_strict_inheritance(), m_aaNorm, m_aaPos, m_creaseHandler, m_geometry, m_grid, m_pivot, m_projectionHandler, m_selector, m_subsetHandler, make_sp(), ug::SubsetInfo::name, ug::REM_CREASE, ug::REM_FIXED, ug::ProjectionHandler::set_geometry(), ug::ProjectionHandler::set_subset_handler(), and ug::ISubsetHandler::subset_info().
Referenced by Mesh().
normal_accessor()
normal_accessor_t& ug::promesh::Mesh::normal_accessor () inline
returns accessor to face normals
References m_aaNorm.
normal_attachment()
normal_attachment_t& ug::promesh::Mesh::normal_attachment () inline
References ug::aNormal.
pivot()
vector3& ug::promesh::Mesh::pivot () inline
References m_pivot.
Referenced by ug::promesh::ExtrudeAndScale(), ug::promesh::MoveMeshTo(), ug::promesh::RotateAroundPivot(), ug::promesh::ScaleAroundPivot(), and set_pivot().
position()
vector3& ug::promesh::Mesh::position (Vertex * v) inline
References m_aaPos.
position_accessor()
position_accessor_t& ug::promesh::Mesh::position_accessor () inline
returns accessor to vertex positions
References m_aaPos.
Referenced by ug::promesh::AdaptSurfaceToCylinder(), ug::promesh::AssignSubsetsByAspectRatio(), ug::promesh::AssignSubsetsFromRaster_IMPL(), ug::promesh::CollapseEdge(), ug::promesh::ConeTransform(), ug::promesh::ConvertToQuadrilaterals(), ug::promesh::ConvertToTriangles(), ug::promesh::CopySelection(), ug::promesh::CreateBox(), ug::promesh::CreateCircle(), ug::promesh::CreatePlane(), ug::promesh::CreatePrism(), ug::promesh::CreatePyramid(), ug::promesh::CreateShrinkElements(), ug::promesh::CreateTetrahedron(), ug::promesh::CreateVertex(), ug::promesh::CSGFaceOperation(), ug::promesh::ExtendSelectionInDirection(), ug::promesh::ExtrudeAlongNormal(), ug::promesh::ExtrudeAndScale(), ug::promesh::ExtrudeCylinders(), ug::promesh::ExtrudeFacesWithTets(), ug::promesh::ExtrudeLayers(), ug::promesh::ExtrudeLayersAndAddProjector(), ug::promesh::ExtrudeToThickness(), ug::promesh::FixVolumeOrientation(), ug::promesh::FlattenBentQuadrilaterals(), ug::promesh::GetBoundingBox(), ug::promesh::GetSelectionCenter(), ug::promesh::IntersectCloseEdges(), ug::promesh::LaplacianSmooth(), ug::promesh::MeasureGridArea(), ug::promesh::MeasureGridLength(), ug::promesh::MeasureGridVolume(), ug::promesh::MeasureSelectionArea(), ug::promesh::MeasureSelectionLength(), ug::promesh::MeasureSelectionVolume(), ug::promesh::MeasureSubsetArea(), ug::promesh::MeasureSubsetLength(), ug::promesh::MeasureSubsetVolume(), ug::promesh::MergeAtCenter(), ug::promesh::MergeAtFirst(), ug::promesh::MergeAtLast(), ug::promesh::MeshLayerBoundaries(), ug::promesh::MeshLayers(), ug::promesh::Mirror(), ug::promesh::Move(), ug::promesh::MoveAlongNormal(), ug::promesh::MoveMeshTo(), ug::promesh::MoveSelectionTo(), ug::promesh::MoveVerticesAlongEdges(), ug::promesh::MoveVerticesToEdgeLength(), ug::promesh::MoveVerticesToProjectedEdgeLength(), ug::promesh::PrintAspectRatioHistogram(), ug::promesh::PrintAspectRatios(), ug::promesh::ProjectedDistance(), ug::promesh::ProjectToLayer(), ug::promesh::ProjectToPlane(), ug::promesh::ProjectToTopLayer(), ug::promesh::RefineWithSnapPointsOrtho(), ug::promesh::RegularizingRefinement_IMPL(), ug::promesh::ReplaceLowValenceVertices(), ug::promesh::ReplaceValence3Vertices(), ug::promesh::ResolveEdgeIntersection(), ug::promesh::ResolveSelfIntersections(), ug::promesh::Retriangulate(), ug::promesh::RotateAroundCenter(), ug::promesh::RotateAroundPivot(), ug::promesh::ScaleAroundCenter(), ug::promesh::ScaleAroundPivot(), ug::promesh::ScaleAroundPoint(), ug::promesh::SelectAnisotropicElements(), ug::promesh::SelectClosestEdge(), ug::promesh::SelectDegenerateFaces(), ug::promesh::SelectEdgesByDirection(), ug::promesh::SelectElemByCoordinate(), ug::promesh::SelectElementsBySplitPlane(), ug::promesh::SelectElementsInBox(), ug::promesh::SelectElementsInCoordinateRange(), ug::promesh::SelectElementsInCylinder(), ug::promesh::SelectIntersectingTriangles(), ug::promesh::SelectLongEdges(), ug::promesh::SelectSelectionKinkVertices(), ug::promesh::SelectShortEdges(), ug::promesh::SelectShortPolychains(), ug::promesh::SelectSlivers(), ug::promesh::SelectSubsetEdgesByDirection(), ug::promesh::SelectSubsetKinkVertices(), ug::promesh::SeparateDegeneratedBoundaryFaceSubsets(), ug::promesh::SetPivotToMeshCenter(), ug::promesh::SetPivotToSelectionCenter(), ug::promesh::SimplifyPolylines(), ug::promesh::SimplifySmoothedPolylines(), ug::promesh::SlopeSmooth(), ug::promesh::SnapToHorizontalRaster(), ug::promesh::SnapVerticesToVertices(), ug::promesh::SplitEdge(), ug::promesh::TangentialSmooth(), ug::promesh::TriangleFill(), ug::promesh::WeightedEdgeSmooth(), ug::promesh::WeightedFaceSmooth(), and ug::promesh::WeightedNormalSmooth().
position_attachment()
position_attachment_t& ug::promesh::Mesh::position_attachment () inline
References ug::aPosition.
Referenced by ug::promesh::CreateSphere(), ug::promesh::CreateTKD(), ug::promesh::CreateTKDWithOuterLayer(), ug::promesh::CSGFaceOperation(), ug::promesh::Duplicate(), ug::promesh::ExtrudeAlongNormal(), ug::promesh::ExtrudeAndMove(), ug::promesh::ExtrudeAndScale(), ug::promesh::ExtrudeToThickness(), ug::promesh::LoadMesh(), ug::promesh::MarkCornersOfMarkedEdges(), ug::promesh::ProjectToLimitPLoop(), ug::promesh::ProjectToLimitSmoothBoundary(), ug::promesh::ProjectVerticesToCloseEdges(), ug::promesh::ProjectVerticesToCloseFaces(), ug::promesh::RemoveDoubles(), ug::promesh::ResolveEdgeIntersection(), ug::promesh::ResolveSelfIntersections(), ug::promesh::ResolveTriangleIntersections(), ug::promesh::Retetrahedralize(), ug::promesh::SaveMesh(), ug::promesh::SelectCreaseEdges(), ug::promesh::SelectIntersectingTriangles(), ug::promesh::SeparateFaceSubsetByNormal(), ug::promesh::SnapVerticesToVertices(), ug::promesh::Tetrahedralize(), and ug::promesh::TriangleFill().
projection_handler()
ProjectionHandler& ug::promesh::Mesh::projection_handler () inline
References m_projectionHandler.
Referenced by ug::promesh::ExtrudeLayersAndAddProjector(), ug::promesh::LoadMesh(), ug::promesh::Refine(), and ug::promesh::SaveMesh().
selection_begin()
template<class TElem > SmartPtr<ElementIterator<typename TElem::grid_base_object> > ug::promesh::Mesh::selection_begin () inline
returns an iterator to the first element of the specified type
Note
This iterator is intended for use through bindings only! If you're actually writing C++ code, please use the iterators of the Grid/Selector/SubsetHandler classes directly.
References make_sp(), and selector().
selection_end()
template<class TElem > SmartPtr<ElementIterator<typename TElem::grid_base_object> > ug::promesh::Mesh::selection_end () inline
returns an iterator to the position behind the last element of the specified type
Note
This iterator is intended for use through bindings only! If you're actually writing C++ code, please use the iterators of the Grid/Selector/SubsetHandler classes directly.
References make_sp(), and selector().
selector()
Selector& ug::promesh::Mesh::selector () inline
References m_selector.
Referenced by ug::promesh::AdaptSurfaceToCylinder(), ug::promesh::AdjustEdgeOrientation(), ug::promesh::AssignNewSubset(), ug::promesh::AssignSubset(), ug::promesh::AssignSubsetsByAspectRatio(), ug::promesh::AssignSubsetsByElementType(), ug::promesh::AssignSubsetsByQuality(), ug::promesh::AssignVolumeConstraints(), ug::promesh::ClearSelection(), ug::promesh::CloseSelection(), ug::promesh::CollapseEdge(), ug::promesh::ConeTransform(), ug::promesh::ConvertToQuadrilaterals(), ug::promesh::ConvertToTetrahedra(), ug::promesh::ConvertToTriangles(), ug::promesh::CopySelectedElements(), ug::promesh::CopySelection(), ug::promesh::CopySubsetIndicesToSides(), ug::promesh::CreateBox(), ug::promesh::CreateCircle(), ug::promesh::CreateEdge(), ug::promesh::CreateFace(), ug::promesh::CreateHexahedraFromSelectedPrisms(), ug::promesh::CreatePlane(), ug::promesh::CreatePrism(), ug::promesh::CreatePyramid(), ug::promesh::CreateSphere(), ug::promesh::CreateTetrahedron(), ug::promesh::CreateTKD(), ug::promesh::CreateTKDWithOuterLayer(), ug::promesh::CreateVertex(), ug::promesh::CreateVolume(), ug::promesh::CSGFaceOperation(), ug::promesh::DeselectAllEdges(), ug::promesh::DeselectAllFaces(), ug::promesh::DeselectAllVertices(), ug::promesh::DeselectAllVolumes(), ug::promesh::Duplicate(), ug::promesh::EdgeSelectionFill(), ug::promesh::EraseSelectedElements(), ug::promesh::ExtendSelection(), ug::promesh::ExtendSelectionInDirection(), ug::promesh::ExtrudeAlongNormal(), ug::promesh::ExtrudeAndMove(), ug::promesh::ExtrudeAndScale(), ug::promesh::ExtrudeCylinders(), ug::promesh::ExtrudeFacesWithTets(), ug::promesh::ExtrudeToThickness(), ug::promesh::FaceSelectionFill(), ug::promesh::FixFaceOrientation(), ug::promesh::FixVolumeOrientation(), ug::promesh::FlattenBentQuadrilaterals(), ug::promesh::GetSelectionCenter(), ug::promesh::HangingNodeRefine(), ug::promesh::InsertCenter(), ug::promesh::IntersectCloseEdges(), ug::promesh::InvertFaceOrientation(), ug::promesh::InvertSelection(), ug::promesh::LaplacianSmooth(), ug::promesh::LoadMesh(), ug::promesh::MarkSelection(), ug::promesh::MeasureSelectionArea(), ug::promesh::MeasureSelectionLength(), ug::promesh::MeasureSelectionVolume(), ug::promesh::MergeAtCenter(), ug::promesh::MergeAtFirst(), ug::promesh::MergeAtLast(), ug::promesh::Mirror(), ug::promesh::Move(), ug::promesh::MoveAlongNormal(), ug::promesh::MoveSelectionTo(), ug::promesh::MoveVerticesAlongEdges(), ug::promesh::MoveVerticesToEdgeLength(), ug::promesh::MoveVerticesToProjectedEdgeLength(), ug::promesh::PlaneCut(), ug::promesh::PrintAspectRatioHistogram(), ug::promesh::PrintAspectRatios(), ug::promesh::ProjectedDistance(), ug::promesh::ProjectToPlane(), ug::promesh::ProjectVerticesToCloseEdges(), ug::promesh::ProjectVerticesToCloseFaces(), ug::promesh::Refine(), ug::promesh::RefineSmooth(), ug::promesh::RefineWithSnapPointsOrtho(), ug::promesh::RemoveDoubleEdges(), ug::promesh::RemoveDoubleFaces(), ug::promesh::RemoveDoubles(), ug::promesh::ReplaceLowValenceVertices(), ug::promesh::ReplaceValence3Vertices(), ug::promesh::ResolveEdgeIntersection(), ug::promesh::ResolveSelfIntersections(), ug::promesh::ResolveTriangleIntersections(), ug::promesh::RestrictSelectionToSubset(), ug::promesh::Retriangulate(), ug::promesh::RotateAroundCenter(), ug::promesh::RotateAroundPivot(), ug::promesh::SaveMesh(), ug::promesh::ScaleAroundCenter(), ug::promesh::ScaleAroundPivot(), ug::promesh::ScaleAroundPoint(), ug::promesh::SelectAll(), ug::promesh::SelectAllEdges(), ug::promesh::SelectAllFaces(), ug::promesh::SelectAllVertices(), ug::promesh::SelectAllVolumes(), ug::promesh::SelectAnisotropicElements(), ug::promesh::SelectAssociatedEdges(), ug::promesh::SelectAssociatedFaces(), ug::promesh::SelectAssociatedVertices(), ug::promesh::SelectBentQuadrilaterals(), ug::promesh::SelectBoundaryEdges(), ug::promesh::SelectBoundaryFaces(), ug::promesh::SelectBoundaryVertices(), ug::promesh::SelectClosestEdge(), ug::promesh::SelectCreaseEdges(), ug::promesh::SelectDegenerateFaces(), ug::promesh::SelectEdgeByIndex(), ug::promesh::SelectEdgesByDirection(), ug::promesh::SelectElemByCoordinate(), ug::promesh::SelectElementsByIndexRange(), ug::promesh::SelectElementsBySplitPlane(), ug::promesh::SelectElementsInBox(), ug::promesh::SelectElementsInCoordinateRange(), ug::promesh::SelectElementsInCylinder(), ug::promesh::SelectFaceByIndex(), ug::promesh::SelectFacesByNormal(), ug::promesh::SelectInnerEdges(), ug::promesh::SelectInnerFaces(), ug::promesh::SelectInnerVertices(), ug::promesh::SelectInterfaceElements(), ug::promesh::SelectIntersectingTriangles(), selection_begin(), selection_end(), ug::promesh::SelectLinkedBoundaryEdges(), ug::promesh::SelectLinkedBoundaryFaces(), ug::promesh::SelectLinkedElements(), ug::promesh::SelectLinkedFlatFaces(), ug::promesh::SelectLinkedManifoldFaces(), ug::promesh::SelectLongEdges(), ug::promesh::SelectMarkedEdges(), ug::promesh::SelectMarkedFaces(), ug::promesh::SelectMarkedVertices(), ug::promesh::SelectNonManifoldEdges(), ug::promesh::SelectSelectionBoundary(), ug::promesh::SelectSelectionKinkVertices(), ug::promesh::SelectShortEdges(), ug::promesh::SelectShortPolychains(), ug::promesh::SelectSlivers(), ug::promesh::SelectSmoothEdgePath(), ug::promesh::SelectSubset(), ug::promesh::SelectSubsetBoundary(), ug::promesh::SelectSubsetEdgesByDirection(), ug::promesh::SelectSubsetKinkVertices(), ug::promesh::SelectUnassignedElements(), ug::promesh::SelectUnconnectedVertices(), ug::promesh::SelectUnorientableVolumes(), ug::promesh::SelectVertexByIndex(), ug::promesh::SelectVolumeByIndex(), ug::promesh::SelectVolumesByType(), ug::promesh::SeparateFacesBySelectedEdges(), ug::promesh::SeparateVolumesBySelectedFaces(), ug::promesh::SetPivotToSelectionCenter(), ug::promesh::SimplifyPolylines(), ug::promesh::SimplifySmoothedPolylines(), ug::promesh::SlopeSmooth(), ug::promesh::SnapVerticesToVertices(), ug::promesh::SplitEdge(), ug::promesh::SwapEdge(), ug::promesh::TangentialSmooth(), ug::promesh::TriangleFill(), ug::promesh::UnmarkSelection(), ug::promesh::VolumeSelectionFill(), ug::promesh::WeightedEdgeSmooth(), ug::promesh::WeightedFaceSmooth(), and ug::promesh::WeightedNormalSmooth().
set_pivot()
void ug::promesh::Mesh::set_pivot (const vector3 & pivot) inline
References m_pivot, and pivot().
Referenced by ug::promesh::MoveMeshTo(), ug::promesh::SetPivot(), ug::promesh::SetPivotToMeshCenter(), and ug::promesh::SetPivotToSelectionCenter().
set_position()
void ug::promesh::Mesh::set_position (Vertex * v, const vector3 & p) inline
References m_aaPos, and p.
Referenced by create_vertex().
subset_begin()
template<class TElem > SmartPtr<ElementIterator<typename TElem::grid_base_object> > ug::promesh::Mesh::subset_begin (int si) inline
returns an iterator to the first element of the specified type
Note
This iterator is intended for use through bindings only! If you're actually writing C++ code, please use the iterators of the Grid/Selector/SubsetHandler classes directly.
References make_sp(), and subset_handler().
subset_end()
template<class TElem > SmartPtr<ElementIterator<typename TElem::grid_base_object> > ug::promesh::Mesh::subset_end (int si) inline
returns an iterator to the position behind the last element of the specified type
Note
This iterator is intended for use through bindings only! If you're actually writing C++ code, please use the iterators of the Grid/Selector/SubsetHandler classes directly.
References make_sp(), and subset_handler().
subset_handler()
SubsetHandler& ug::promesh::Mesh::subset_handler () inline
References m_subsetHandler.
Referenced by ug::promesh::AdjustEdgeLength(), ug::promesh::AdjustEdgeLengthExtended(), ug::promesh::AdjustSubsetsForUG3(), ug::promesh::AdjustSubsetsForUG4(), ug::promesh::AssignNewSubset(), ug::promesh::AssignSubset(), ug::promesh::AssignSubsetColors(), ug::promesh::AssignSubsetsByAspectRatio(), ug::promesh::AssignSubsetsByElementType(), ug::promesh::AssignSubsetsByQuality(), ug::promesh::AssignSubsetsFromRaster_IMPL(), ug::promesh::CopySelectedElements(), ug::promesh::CopySelection(), ug::promesh::CopySubsetIndicesToSides(), ug::promesh::CreateBox(), ug::promesh::CreateCircle(), ug::promesh::CreateEdge(), ug::promesh::CreateFace(), ug::promesh::CreatePlane(), ug::promesh::CreatePrism(), ug::promesh::CreatePyramid(), ug::promesh::CreateSphere(), ug::promesh::CreateTetrahedron(), ug::promesh::CreateTKD(), ug::promesh::CreateTKDWithOuterLayer(), ug::promesh::CreateVertex(), ug::promesh::CreateVolume(), ug::promesh::CSGFaceOperation(), ug::promesh::EraseEmptySubsets(), ug::promesh::EraseSubset(), ug::promesh::ExportToUG3(), ug::promesh::ExtrudeAlongNormal(), ug::promesh::ExtrudeAndMove(), ug::promesh::ExtrudeAndScale(), ug::promesh::ExtrudeCylinders(), ug::promesh::ExtrudeFacesWithTets(), ug::promesh::ExtrudeLayers(), ug::promesh::ExtrudeLayersAndAddProjector(), ug::promesh::ExtrudeToThickness(), ug::promesh::FixFaceSubsetOrientations(), ug::promesh::HangingNodeRefine(), ug::promesh::InsertCenter(), ug::promesh::JoinSubsets(), ug::promesh::LoadMesh(), ug::promesh::MeasureSubsetArea(), ug::promesh::MeasureSubsetLength(), ug::promesh::MeasureSubsetVolume(), ug::promesh::MeshLayerBoundaries(), ug::promesh::MeshLayers(), ug::promesh::MoveSubset(), ug::promesh::Refine(), ug::promesh::RefineSmooth(), ug::promesh::RestrictSelectionToSubset(), ug::promesh::Retetrahedralize(), ug::promesh::Retriangulate(), ug::promesh::SaveMesh(), ug::promesh::SelectInterfaceElements(), ug::promesh::SelectSubset(), ug::promesh::SelectSubsetBoundary(), ug::promesh::SelectSubsetEdgesByDirection(), ug::promesh::SelectSubsetKinkVertices(), ug::promesh::SelectUnassignedElements(), ug::promesh::SeparateDegeneratedBoundaryFaceSubsets(), ug::promesh::SeparateFacesByEdgeSubsets(), ug::promesh::SeparateFacesBySelectedEdges(), ug::promesh::SeparateFaceSubsetByNormal(), ug::promesh::SeparateFaceSubsetsByNormal(), ug::promesh::SeparateIrregularManifoldSubsets(), ug::promesh::SeparateVolumesByFaceSubsets(), ug::promesh::SeparateVolumesBySelectedFaces(), ug::promesh::SetSubsetName(), subset_begin(), subset_end(), ug::promesh::SwapSubsets(), ug::promesh::Tetrahedralize(), and ug::promesh::TriangleFill().
volume_constraint_accessor()
volume_constraint_accessor_t& ug::promesh::Mesh::volume_constraint_accessor () inline
returns accessor to volume constraints.
References m_aaVolumeConstraint, and volume_constraints_required().
Referenced by ug::promesh::AssignVolumeConstraints().
volume_constraint_attachment()
volume_constraint_attachment_t& ug::promesh::Mesh::volume_constraint_attachment () inline
returns the volume constraint attachment
References m_aVolumeConstraint, and volume_constraints_required().
Referenced by ug::promesh::Retetrahedralize().
volume_constraints_required()
void ug::promesh::Mesh::volume_constraints_required () inline protected
References AttachmentAccessor< Volume, TAttachment >::access(), ug::Grid::attach_to_volumes_dv(), m_aaVolumeConstraint, m_aVolumeConstraint, m_grid, and ug::AttachmentAccessor< class, class, class >::valid().
Referenced by volume_constraint_accessor(), and volume_constraint_attachment().
Member Data Documentation
m_aaNorm
normal_accessor_t ug::promesh::Mesh::m_aaNorm protected
Referenced by init(), and normal_accessor().
m_aaPos
position_accessor_t ug::promesh::Mesh::m_aaPos protected
Referenced by init(), position(), position_accessor(), and set_position().
m_aaVolumeConstraint
volume_constraint_accessor_t ug::promesh::Mesh::m_aaVolumeConstraint protected
Referenced by clear_volume_constraints(), volume_constraint_accessor(), and volume_constraints_required().
m_aVolumeConstraint
volume_constraint_attachment_t ug::promesh::Mesh::m_aVolumeConstraint protected
Referenced by clear_volume_constraints(), volume_constraint_attachment(), and volume_constraints_required().
m_creaseHandler
SubsetHandler ug::promesh::Mesh::m_creaseHandler protected
Referenced by crease_handler(), and init().
m_geometry
SmartPtr<Geometry<3, 3> > ug::promesh::Mesh::m_geometry protected
Referenced by geometry(), and init().
m_grid
Grid ug::promesh::Mesh::m_grid protected
Referenced by clear_volume_constraints(), grid(), init(), Mesh(), and volume_constraints_required().
m_pivot
vector3 ug::promesh::Mesh::m_pivot protected
Referenced by init(), pivot(), and set_pivot().
m_projectionHandler
ProjectionHandler ug::promesh::Mesh::m_projectionHandler protected
Referenced by init(), and projection_handler().
m_selector
Selector ug::promesh::Mesh::m_selector protected
Referenced by init(), and selector().
m_subsetHandler
SubsetHandler ug::promesh::Mesh::m_subsetHandler protected
Referenced by init(), and subset_handler().
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/ProMesh/mesh.h
/home/runner/work/docs/docs/ug4/plugins/ProMesh/mesh.cpp