Plugins: ug::NavierStokes::WallObject< TGridFunction > Class Template Reference
ug::NavierStokes::WallObject< TGridFunction > Class Template Reference
#include <filter.h>
Public Member Functions
number coord ()
size_t direction ()
number dist (MathVector< TGridFunction::dim > co)
int si ()
WallObject (SmartPtr< TGridFunction > u, size_t direction, number coord, const char *subset)
Private Attributes
number m_coord
size_t m_direction
int m_subset_index
Constructor & Destructor Documentation
WallObject()
template<typename TGridFunction > ug::NavierStokes::WallObject< TGridFunction >::WallObject (SmartPtr< TGridFunction > u, size_t direction, number coord, const char * subset) inline
References ug::NavierStokes::WallObject< TGridFunction >::coord(), ug::NavierStokes::WallObject< TGridFunction >::direction(), ug::NavierStokes::WallObject< TGridFunction >::m_coord, ug::NavierStokes::WallObject< TGridFunction >::m_direction, and ug::NavierStokes::WallObject< TGridFunction >::m_subset_index.
Member Function Documentation
coord()
template<typename TGridFunction > number ug::NavierStokes::WallObject< TGridFunction >::coord () inline
References ug::NavierStokes::WallObject< TGridFunction >::m_coord.
Referenced by ug::NavierStokes::WallObject< TGridFunction >::WallObject().
direction()
template<typename TGridFunction > size_t ug::NavierStokes::WallObject< TGridFunction >::direction () inline
References ug::NavierStokes::WallObject< TGridFunction >::m_direction.
Referenced by ug::NavierStokes::WallObject< TGridFunction >::WallObject().
dist()
template<typename TGridFunction > number ug::NavierStokes::WallObject< TGridFunction >::dist (MathVector< TGridFunction::dim > co) inline
References ug::NavierStokes::WallObject< TGridFunction >::m_coord, and ug::NavierStokes::WallObject< TGridFunction >::m_direction.
si()
template<typename TGridFunction > int ug::NavierStokes::WallObject< TGridFunction >::si () inline
References ug::NavierStokes::WallObject< TGridFunction >::m_subset_index.
Member Data Documentation
m_coord
template<typename TGridFunction > number ug::NavierStokes::WallObject< TGridFunction >::m_coord private
Referenced by ug::NavierStokes::WallObject< TGridFunction >::coord(), ug::NavierStokes::WallObject< TGridFunction >::dist(), and ug::NavierStokes::WallObject< TGridFunction >::WallObject().
m_direction
template<typename TGridFunction > size_t ug::NavierStokes::WallObject< TGridFunction >::m_direction private
Referenced by ug::NavierStokes::WallObject< TGridFunction >::direction(), ug::NavierStokes::WallObject< TGridFunction >::dist(), and ug::NavierStokes::WallObject< TGridFunction >::WallObject().
m_subset_index
template<typename TGridFunction > int ug::NavierStokes::WallObject< TGridFunction >::m_subset_index private
Referenced by ug::NavierStokes::WallObject< TGridFunction >::si(), and ug::NavierStokes::WallObject< TGridFunction >::WallObject().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/filter.h