Plugins: ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain > Class Template Reference
ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain > Class Template Reference
Plugins » Convection Diffusion
Discretization for the Convection-Diffusion Equation.
#include <convection_diffusion_fv1.h>
Classes
struct ShapeValues
struct holding values of shape functions in IPs
Public Member Functions
ConvectionDiffusionFV1 (const char *functions, const char *subsets)
Constructor.
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegularGrid)
type of trial space for each function used
void set_sss (SmartPtr< SingularSourcesAndSinks< dim, 1 > > sss)
set singular sources and sinks
void set_upwind (SmartPtr< IConvectionShapes< dim > > shapes)
set the upwind method
virtual bool use_hanging () const
returns if hanging nodes are needed
Public Member Functions inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
ConvectionDiffusionBase (const char *functions, const char *subsets)
Constructor.
virtual SmartPtr< CplUserData< MathVector< dim >, dim > > gradient ()
returns the export of the gradient of associated unknown function
void set_reaction_explicit (SmartPtr< CplUserData< number, dim > > user)
void set_reaction_explicit (number val)
void set_reaction_rate_explicit (SmartPtr< CplUserData< number, dim > > user)
void set_reaction_rate_explicit (number val)
void set_source_explicit (SmartPtr< CplUserData< number, dim > > user)
void set_source_explicit (number val)
virtual SmartPtr< CplUserData< number, dim > > value ()
returns the export of the value of associated unknown function
void set_diffusion (SmartPtr< CplUserData< MathMatrix< dim, dim >, dim > > user)
sets the diffusion tensor
void set_diffusion (number val)
sets the diffusion tensor
void set_velocity (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the velocity field
void set_velocity (const std::vector< number > &vVel)
sets the velocity field
void set_flux (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the flux
void set_flux (const std::vector< number > &vVel)
sets the flux
void set_reaction_rate (SmartPtr< CplUserData< number, dim > > user)
sets the reaction rate
void set_reaction_rate (number val)
sets the reaction rate
void set_reaction (SmartPtr< CplUserData< number, dim > > user)
sets the reaction
void set_reaction (number val)
sets the reaction
void set_source (SmartPtr< CplUserData< number, dim > > user)
sets the source / sink term
void set_source (number val)
sets the source / sink term
void set_vector_source (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the vector source term
void set_vector_source (const std::vector< number > &vVel)
sets the vector source term
void set_mass_scale (SmartPtr< CplUserData< number, dim > > user)
sets mass scale
void set_mass_scale (number val)
sets mass scale
void set_mass (SmartPtr< CplUserData< number, dim > > user)
sets mass
void set_mass (number val)
sets mass
Public Member Functions inherited from ug::IElemDisc< TDomain >
void add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier)
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
void check_setup (bool bNonRegularGrid)
void clear_imports ()
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_elem_loop ()
void do_fsh_elem_loop ()
void do_fsh_err_est_elem_loop ()
void do_fsh_err_est_elem_loop ()
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
ConstSmartPtr< TDomain > domain () const
SmartPtr< TDomain > domain ()
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
virtual void fsh_timestep (number time, VectorProxyBase *u)
virtual void fsh_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
const FunctionGroup & function_group () const
ConstSmartPtr< FunctionPattern > function_pattern () const
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > & get_elem_modifier ()
IDataImport< dim > & get_import (size_t i)
IElemDisc (const char *functions="", const char *subsets="")
IElemDisc (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
bool is_time_dependent () const
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
const FunctionIndexMapping & map () const
number mass_scale (const size_t timePoint) const
number mass_scale () const
number mass_scale (const size_t timePoint) const
number mass_scale () const
const std::vector< number > & mass_scales () const
const std::vector< number > & mass_scales () const
size_t num_fct () const
size_t num_imports () const
size_t num_subsets () const
virtual void post_assemble_loop ()
virtual void prep_timestep (number time, VectorProxyBase *u)
virtual void prep_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void register_import (IDataImport< dim > &Imp)
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
void set_functions (const std::string &functions)
void set_functions (const std::vector< std::string > &functions)
void set_roid (ReferenceObjectID id, int discType)
void set_stationary (bool bStationaryForced=true)
void set_stationary ()
void set_subsets (const std::vector< std::string > &subsets)
void set_subsets (const std::string &subsets)
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
void set_time_independent ()
void set_time_point (const size_t timePoint)
number stiff_scale (const size_t timePoint) const
number stiff_scale () const
number stiff_scale (const size_t timePoint) const
number stiff_scale () const
const std::vector< number > & stiff_scales () const
const std::vector< number > & stiff_scales () const
const TDomain::subset_handler_type & subset_handler () const
TDomain::subset_handler_type & subset_handler ()
const std::vector< std::string > & symb_fcts () const
const std::vector< std::string > & symb_subsets () const
number time () const
size_t time_point () const
virtual int type () const
virtual ~IElemDisc ()
Static Public Attributes
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::IElemDisc< TDomain >
static const int dim
Protected Types
typedef IConvectionShapes< dim > conv_shape_type
returns the updated convection shapes
Protected Member Functions
template<typename TElem , typename TFVGeom >
void ex_grad (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< TFVGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< MathVector< dim > > > vvvDeriv[])
computes the gradient of the concentration
template<typename TElem , typename TFVGeom >
void ex_value (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< TFVGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< number > > vvvDeriv[])
computes the concentration
const IConvectionShapes< dim > & get_updated_conv_shapes (const FVGeometryBase &geo)
template<typename TElem , typename TFVGeom >
void lin_def_diffusion (const LocalVector &u, std::vector< std::vector< MathMatrix< dim, dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the velocity
template<typename TElem , typename TFVGeom >
void lin_def_flux (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the velocity
template<typename TElem , typename TFVGeom >
void lin_def_mass (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the mass scale term
template<typename TElem , typename TFVGeom >
void lin_def_mass_scale (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the mass scale term
template<typename TElem , typename TFVGeom >
void lin_def_reaction (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the reaction
template<typename TElem , typename TFVGeom >
void lin_def_reaction_rate (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the reaction
template<typename TElem , typename TFVGeom >
void lin_def_source (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the source term
template<typename TElem , typename TFVGeom >
void lin_def_vector_source (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the vector source term
template<typename TElem , typename TFVGeom >
void lin_def_velocity (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the velocity
void register_all_funcs (bool bHang)
template<typename TElem , typename TFVGeom >
void register_func ()
Protected Member Functions inherited from ug::IElemDisc< TDomain >
virtual void approximation_space_changed ()
void clear_add_fct (ReferenceObjectID id)
void clear_add_fct ()
void remove_add_def_A_elem_fct (ReferenceObjectID id)
void remove_add_def_A_expl_elem_fct (ReferenceObjectID id)
void remove_add_def_M_elem_fct (ReferenceObjectID id)
void remove_add_jac_A_elem_fct (ReferenceObjectID id)
void remove_add_jac_M_elem_fct (ReferenceObjectID id)
void remove_add_rhs_elem_fct (ReferenceObjectID id)
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_elem_loop_fct (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_fsh_timestep_elem_fct (ReferenceObjectID id)
void remove_fsh_timestep_fct (size_t algebra_id)
void remove_prep_elem_fct (ReferenceObjectID id)
void remove_prep_elem_loop_fct (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_timestep_elem_fct (ReferenceObjectID id)
void remove_prep_timestep_fct (size_t algebra_id)
void set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_fct (size_t algebra_id, TAssFunc func)
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
void set_prep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_fct (size_t algebra_id, TAssFunc func)
void update_function_index_mapping ()
Protected Attributes
bool m_bNonRegularGrid
current regular grid flag
SmartPtr< IConvectionShapes< dim > > m_spConvShape
method to compute the upwind shapes
Protected Attributes inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
SmartPtr< DataExport< MathVector< dim >, dim > > m_exGrad
Export for the gradient of concentration.
SmartPtr< DataExport< number, dim > > m_exValue
Export for the concentration.
DataImport< MathMatrix< dim, dim >, dim > m_imDiffusion
Data import for Diffusion.
DataImport< MathVector< dim >, dim > m_imFlux
Data import for the Flux.
DataImport< number, dim > m_imMass
Data import for the mass scale.
DataImport< number, dim > m_imMassScale
Data import for the mass scale.
DataImport< number, dim > m_imReaction
Data import for the reaction term.
DataImport< number, dim > m_imReactionExpl
Data import for the reaction term explicit.
DataImport< number, dim > m_imReactionRate
Data import for the reaction term.
DataImport< number, dim > m_imReactionRateExpl
Data import for the reaction_rate term explicit.
DataImport< number, dim > m_imSource
Data import for the right-hand side (volume)
DataImport< number, dim > m_imSourceExpl
Data import for the source term explicit.
DataImport< MathVector< dim >, dim > m_imVectorSource
Data import for the right-hand side (vector)
DataImport< MathVector< dim >, dim > m_imVelocity
Data import for the Velocity field.
Protected Attributes inherited from ug::IElemDisc< TDomain >
bool m_bStationaryForced
FunctionGroup m_fctGrp
FunctionIndexMapping m_fctIndexMap
ReferenceObjectID m_id
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > m_spElemModifier
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
ConstSmartPtr< FunctionPattern > m_spFctPattern
size_t m_timePoint
std::vector< std::string > m_vFct
std::vector< IDataImport< dim > * > m_vIImport
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
std::vector< std::string > m_vSubset
Private Types
typedef ConvectionDiffusionBase< TDomain > base_type
Base class type.
typedef SideAndElemErrEstData< TDomain > err_est_type
error estimator type
typedef ConvectionDiffusionFV1< TDomain > this_type
Own type.
Private Member Functions
template<typename TElem , typename TFVGeom >
void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the stiffness part of the local defect
template<typename TElem , typename TFVGeom >
void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the stiffness part of the local defect explicit reaction, reaction_rate and source
template<typename TElem , typename TFVGeom >
void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the mass part of the local defect
template<typename TElem , typename TFVGeom >
void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the local stiffness matrix using a finite volume scheme
template<typename TElem , typename TFVGeom >
void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the local mass matrix using a finite volume scheme
template<typename TElem , typename TFVGeom >
void add_rhs_elem (LocalVector &d, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the local right hand side
template<typename TElem , typename TFVGeom >
void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
computes the error estimator contribution for one element
template<typename TElem , typename TFVGeom >
void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
computes the error estimator contribution for one element
template<typename TElem , typename TFVGeom >
void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
computes the error estimator contribution for one element
template<typename TElem , typename TFVGeom >
void fsh_elem_loop ()
finishes the loop over all elements
template<typename TElem , typename TFVGeom >
void fsh_err_est_elem_loop ()
postprocesses the loop over all elements of one type in the computation of the error estimator
virtual void prep_assemble_loop ()
prepares assembling
template<typename TElem , typename TFVGeom >
void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
prepares the element for assembling
template<typename TElem , typename TFVGeom >
void prep_elem_loop (const ReferenceObjectID roid, const int si)
prepares the loop over all elements
template<typename TElem , typename TFVGeom >
void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
prepares the element for assembling the error estimator
template<typename TElem , typename TFVGeom >
void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
prepares the loop over all elements of one type for the computation of the error estimator
Private Attributes
struct ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1::ShapeValues m_shapeValues
SmartPtr< SingularSourcesAndSinks< dim, 1 > > m_sss
singular sources and sinks
Static Private Attributes
static const size_t _C_ = 0
abbreviation for the local solution
Additional Inherited Members
Public Types inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
typedef SmartPtr< CplUserData< MathVector< dim >, dim > > GradExport
typedef SmartPtr< CplUserData< number, dim > > NumberExport
Public Types inherited from ug::IElemDisc< TDomain >
typedef TDomain domain_type
typedef TDomain::position_type position_type
Detailed Description
template<typename TDomain>
class ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >
Discretization for the Convection-Diffusion Equation.
This class implements the IElemDisc interface to provide element local assemblings for the convection diffusion equation. The Equation has the form
\[ \partial_t (m1*c + m2) - \nabla \left(D \nabla c - \vec{v} c \right - \vec{F}) + r1 \cdot c + r2 = f + f2 \]
with
\(c \) is the unknown solution
\(m1 \equiv m(\vec{x},t) \) is the Mass Scaling Term
\(m2 \equiv m(\vec{x},t) \) is the Mass Term
\(D \equiv D(\vec{x},t) \) is the Diffusion Tensor
\(v \equiv \vec{v}(\vec{x},t) \) is the Velocity Field
\(F \equiv \vec{F}(\vec{x},t) \) is the Flux
\(r1 \equiv r(\vec{x},t) \) is the Reaction Rate
\(r2 \equiv r(\vec{x},t) \) is a Reaction Term
\(f \equiv f(\vec{x},t) \) is a Source Term
\(f2 \equiv f_2(\vec{x},t) \) is a Vector Source Term
Template Parameters
TDomain Domain
TAlgebra Algebra
Member Typedef Documentation
template<typename TDomain> typedef ConvectionDiffusionBase<TDomain> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::base_type private
Base class type.
template<typename TDomain> typedef IConvectionShapes<dim> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::conv_shape_type protected
returns the updated convection shapes
template<typename TDomain> typedef SideAndElemErrEstData<TDomain> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::err_est_type private
error estimator type
template<typename TDomain> typedef ConvectionDiffusionFV1<TDomain> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::this_type private
Own type.
Constructor & Destructor Documentation
template<typename TDomain > ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ConvectionDiffusionFV1 (const char * functions, const char * subsets)
Constructor.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_bNonRegularGrid, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prepare_setting(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::register_all_funcs().
Member Function Documentation
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
assembles the stiffness part of the local defect
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_expl_elem(), ug::DataImport< TData, dim >::data_given(), ug::IElemDisc< TDomain >::domain(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::get_updated_conv_shapes(), grid(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_sss, ug::MatVecMult(), ug::IConvectionShapes< dim >::num_sh(), ug::IElemDisc< TDomain >::time(), ug::VecDot(), ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_M_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_expl_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
assembles the stiffness part of the local defect explicit reaction, reaction_rate and source
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_M_elem(), ug::DataImport< TData, dim >::data_given(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRateExpl, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSourceExpl.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_M_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
assembles the mass part of the local defect
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_rhs_elem(), ug::DataImport< TData, dim >::data_given(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_expl_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_A_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
assembles the local stiffness matrix using a finite volume scheme
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_M_elem(), ug::GridObject::base_object_id(), ug::ConvectionDiffusionPlugin::CalculateCenter(), ug::DataImport< TData, dim >::data_given(), ug::ConvectionDiffusionPlugin::DID_CONV_DIFF_FV1, ug::IElemDisc< TDomain >::domain(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::get_updated_conv_shapes(), grid(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_sss, ug::MatVecMult(), ug::LocalMatrix::num_col_dof(), ug::LocalMatrix::num_row_dof(), ug::IConvectionShapes< dim >::num_sh(), ug::IElemDisc< TDomain >::time(), UG_ASSERT, UG_DLOG, ug::VecDot(), and ug::VecLength().
Referenced by ug::ConvectionDiffusionPlugin::CalculateCenter(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_M_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
assembles the local mass matrix using a finite volume scheme
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_elem(), ug::DataImport< TData, dim >::data_given(), ug::GeomProvider< TGeom >::get(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_A_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_rhs_elem (LocalVector & d, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
assembles the local right hand side
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::DataImport< TData, dim >::data_given(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem_loop(), and ug::VecDot().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_M_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_A_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) private virtual
computes the error estimator contribution for one element
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::Grid::associated_elements_sorted(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_M_elem(), ug::DataImport< TData, dim >::data_given(), ug::IElemDisc< TDomain >::err_est_data(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_shapeValues, ug::IElemDisc< TDomain >::m_spErrEstData, ug::MatVecScaleMultAppend(), normal, ug::SideAndElemErrEstData< TDomain >::num_elem_ips(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ShapeValues::num_sh(), ug::SideAndElemErrEstData< TDomain >::num_side_ips(), ug::GridObject::reference_object_id(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ShapeValues::shapeAtElemIP(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ShapeValues::shapeAtSideIP(), ug::SideAndElemErrEstData< TDomain >::surface_view(), UG_CATCH_THROW, UG_THROW, ug::VecAppend(), ug::VecDot(), ug::VecNormalize(), ug::VecScale(), ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_M_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) private virtual
computes the error estimator contribution for one element
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::Grid::associated_elements_sorted(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_rhs_elem(), ug::DataImport< TData, dim >::data_given(), ug::IElemDisc< TDomain >::err_est_data(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_shapeValues, ug::IElemDisc< TDomain >::m_spErrEstData, ug::SideAndElemErrEstData< TDomain >::num_elem_ips(), ug::GridObject::reference_object_id(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ShapeValues::shapeAtElemIP(), ug::SideAndElemErrEstData< TDomain >::surface_view(), UG_CATCH_THROW, and UG_THROW.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_A_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_rhs_elem (GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) private virtual
computes the error estimator contribution for one element
Reimplemented from ug::IElemDisc< TDomain >.
References ug::Grid::associated_elements_sorted(), ug::DataImport< TData, dim >::data_given(), ug::IElemDisc< TDomain >::err_est_data(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::fsh_err_est_elem_loop(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::IElemDisc< TDomain >::m_spErrEstData, normal, ug::SideAndElemErrEstData< TDomain >::num_elem_ips(), ug::SideAndElemErrEstData< TDomain >::num_side_ips(), ug::GridObject::reference_object_id(), ug::SideAndElemErrEstData< TDomain >::surface_view(), UG_CATCH_THROW, UG_THROW, ug::VecDot(), and ug::VecNormalize().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_M_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ex_grad (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< TFVGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< MathVector< dim > > > vvvDeriv[]) protected
computes the gradient of the concentration
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, dim, ug::GeomProvider< TGeom >::get(), BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >::grads(), ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::MatVecMult(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_upwind(), ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ex_value().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ex_value (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< TFVGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< number > > vvvDeriv[]) protected
computes the concentration
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ex_grad(), ug::GeomProvider< TGeom >::get(), and BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >::shapes().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_mass().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::fsh_elem_loop () private virtual
finishes the loop over all elements
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_elem().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_elem_loop(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::fsh_err_est_elem_loop () private virtual
postprocesses the loop over all elements of one type in the computation of the error estimator
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_velocity().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_rhs_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > const ConvectionDiffusionFV1< TDomain >::conv_shape_type & ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::get_updated_conv_shapes (const FVGeometryBase & geo) protected
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_spConvShape, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::register_all_funcs(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::register_func(), and UG_LOG.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_diffusion(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_velocity(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_upwind().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_diffusion (const LocalVector & u, std::vector< std::vector< MathMatrix< dim, dim > > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the velocity
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::IConvectionShapes< dim >::D_diffusion(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::dim, ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::get_updated_conv_shapes(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_flux(), ug::MatAdd(), ug::IConvectionShapes< dim >::non_zero_deriv_diffusion(), ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_velocity(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_flux (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the velocity
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_reaction_rate().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_diffusion(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_mass (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the mass scale term
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ex_value(), ug::GeomProvider< TGeom >::get(), and UG_ASSERT.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_mass_scale(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_mass_scale (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the mass scale term
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_mass(), and UG_ASSERT.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_vector_source(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_reaction (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the reaction
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_source().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_reaction_rate(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_reaction_rate (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the reaction
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_reaction().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_flux(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_source (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the source term
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_vector_source().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_reaction(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_vector_source (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the vector source term
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_mass_scale().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_source(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_velocity (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the velocity
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_, ug::IConvectionShapes< dim >::D_vel(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::get_updated_conv_shapes(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_diffusion(), ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::fsh_err_est_elem_loop(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_assemble_loop () private virtual
prepares assembling
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_sss, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_elem_loop().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::use_hanging().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_elem (const LocalVector & u, GridObject * elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[]) private virtual
prepares the element for assembling
This methods prepares an element for the assembling. The Positions of the Element Corners are read and the Finite Volume Geometry is updated. The global ip positions are scheduled at the data imports.
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::DID_CONV_DIFF_FV1, dim, ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRateExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSourceExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_spConvShape, ug::IElemDisc< TDomain >::subset_handler(), UG_CATCH_THROW, UG_DLOG, and UG_THROW.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::fsh_elem_loop(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_elem_loop (const ReferenceObjectID roid, const int si) private virtual
prepares the loop over all elements
This method prepares the loop over all elements. It resizes the Position array for the corner coordinates and schedules the local ip positions at the data imports.
Reimplemented from ug::IElemDisc< TDomain >.
References dim, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::fsh_elem_loop(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRateExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSourceExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_spConvShape, and UG_THROW.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_assemble_loop(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private virtual
prepares the element for assembling the error estimator
Reimplemented from ug::IElemDisc< TDomain >.
References ug::SideAndElemErrEstData< TDomain >::all_side_global_ips(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_A_elem(), dim, ug::SideAndElemErrEstData< TDomain >::elem_global_ips(), ug::IElemDisc< TDomain >::err_est_data(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_shapeValues, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_spConvShape, ug::IElemDisc< TDomain >::m_spErrEstData, ug::SideAndElemErrEstData< TDomain >::num_all_side_ips(), ug::SideAndElemErrEstData< TDomain >::num_elem_ips(), ug::LagrangeP1< TRefElem >::num_sh(), ug::GridObject::reference_object_id(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ShapeValues::resize(), BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >::shapes(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ShapeValues::shapesAtElemIP(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ShapeValues::shapesAtSideIP(), ug::IElemDisc< TDomain >::subset_handler(), UG_CATCH_THROW, and UG_THROW.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem_loop(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem_loop (const ReferenceObjectID roid, const int si) private virtual
prepares the loop over all elements of one type for the computation of the error estimator
Reimplemented from ug::IElemDisc< TDomain >.
References dim, ug::IElemDisc< TDomain >::err_est_data(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_shapeValues, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_spConvShape, ug::IElemDisc< TDomain >::m_spErrEstData, ug::SideAndElemErrEstData< TDomain >::num_all_side_ips(), ug::SideAndElemErrEstData< TDomain >::num_elem_ips(), ug::LagrangeP1< TRefElem >::num_sh(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ShapeValues::resize(), BaseLSFS< LagrangeP1< TRefElem >, TRefElem::dim >::shapes(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ShapeValues::shapesAtElemIP(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ShapeValues::shapesAtSideIP(), UG_CATCH_THROW, and UG_THROW.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_rhs_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prepare_setting (const std::vector< LFEID > & vLfeID, bool bNonRegularGrid) virtual
type of trial space for each function used
Implements ug::IElemDisc< TDomain >.
References ug::LFEID::LAGRANGE, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_bNonRegularGrid, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::register_all_funcs(), UG_THROW, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::use_hanging().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ConvectionDiffusionFV1().
template<typename TDomain> void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::register_all_funcs (bool bHang) protected
register utils
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ConvectionDiffusionFV1(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::get_updated_conv_shapes(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prepare_setting().
template<typename TDomain > template<typename TElem , typename TFVGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::register_func () protected
register utils
References ug::IElemDisc< TDomain >::clear_add_fct(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_exGrad, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_exValue, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::IElemDisc< TDomain >::set_add_def_A_elem_fct(), ug::IElemDisc< TDomain >::set_add_def_A_expl_elem_fct(), ug::IElemDisc< TDomain >::set_add_def_M_elem_fct(), ug::IElemDisc< TDomain >::set_add_jac_A_elem_fct(), ug::IElemDisc< TDomain >::set_add_jac_M_elem_fct(), ug::IElemDisc< TDomain >::set_add_rhs_elem_fct(), ug::IElemDisc< TDomain >::set_compute_err_est_A_elem(), ug::IElemDisc< TDomain >::set_compute_err_est_M_elem(), ug::IElemDisc< TDomain >::set_compute_err_est_rhs_elem(), ug::DataImport< TData, dim >::set_fct(), ug::IElemDisc< TDomain >::set_fsh_elem_loop_fct(), ug::IElemDisc< TDomain >::set_fsh_err_est_elem_loop(), ug::IElemDisc< TDomain >::set_prep_elem_fct(), ug::IElemDisc< TDomain >::set_prep_elem_loop_fct(), ug::IElemDisc< TDomain >::set_prep_err_est_elem(), and ug::IElemDisc< TDomain >::set_prep_err_est_elem_loop().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::get_updated_conv_shapes().
template<typename TDomain> void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss (SmartPtr< SingularSourcesAndSinks< dim, 1 > > sss) inline
set singular sources and sinks
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_expl_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_rhs_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_rhs_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::fsh_elem_loop(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::fsh_err_est_elem_loop(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_diffusion(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_flux(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_mass(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_mass_scale(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_reaction(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_reaction_rate(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_vector_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_velocity(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_sss, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_assemble_loop(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_elem_loop(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem_loop().
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_upwind (SmartPtr< IConvectionShapes< dim > > shapes)
set the upwind method
This method sets the upwind method used to upwind the convection.
Parameters
shapes upwind method
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::get_updated_conv_shapes(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_spConvShape.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ex_grad().
template<typename TDomain > bool ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::use_hanging () const virtual
returns if hanging nodes are needed
Reimplemented from ug::IElemDisc< TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_assemble_loop().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prepare_setting().
Member Data Documentation
template<typename TDomain> const size_t ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::_C_ = 0 static private
abbreviation for the local solution
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_expl_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_rhs_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ex_grad(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ex_value(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_diffusion(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_flux(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_mass(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_mass_scale(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_reaction(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_reaction_rate(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_vector_source(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_velocity().
template<typename TDomain> const int ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::dim = base_type::dim static
World dimension.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::lin_def_diffusion().
template<typename TDomain> bool ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_bNonRegularGrid protected
current regular grid flag
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::ConvectionDiffusionFV1(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prepare_setting().
template<typename TDomain> struct ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1::ShapeValues ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_shapeValues private
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::compute_err_est_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem_loop().
template<typename TDomain> SmartPtr<IConvectionShapes<dim> > ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_spConvShape protected
method to compute the upwind shapes
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::get_updated_conv_shapes(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_elem_loop(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_err_est_elem_loop(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_upwind().
template<typename TDomain> SmartPtr<SingularSourcesAndSinks<dim, 1> > ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::m_sss private
singular sources and sinks
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_def_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_assemble_loop(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::set_sss().
The documentation for this class was generated from the following files:
/home/sreiter/projects/ug4-docu/plugins/ConvectionDiffusion/fv1/convection_diffusion_fv1.h
/home/sreiter/projects/ug4-docu/plugins/ConvectionDiffusion/fv1/convection_diffusion_fv1.cpp