Plugins: ug::NavierStokes::NavierStokesFIELDSStabilization< TDim > Class Template Reference
ug::NavierStokes::NavierStokesFIELDSStabilization< TDim > Class Template Reference
#include <stabilization.h>
Public Types
typedef INavierStokesSRFV1Stabilization< TDim > base_type
Base class.
typedef NavierStokesFIELDSStabilization< TDim > this_type
This class.
Public Member Functions
NavierStokesFIELDSStabilization ()
constructor
template<typename TElem >
void update (const FV1Geometry< TElem, dim > *geo, const LocalVector &vCornerValue, const MathVector< dim > vStdVel[], const bool bStokes, const DataImport< number, dim > &kinVisco, const DataImport< number, dim > &density, const DataImport< MathVector< dim >, dim > *pSource, const LocalVector *pvCornerValueOldTime, number dt)
update of values for FV1Geometry
Public Member Functions inherited from ug::NavierStokes::INavierStokesSRFV1Stabilization< TDim >
INavierStokesSRFV1Stabilization ()
constructor
void set_diffusion_length (std::string diffLength)
sets the type of diff length used for evaluation
Public Member Functions inherited from ug::NavierStokes::INavierStokesFV1Stabilization< dim >
INavierStokesFV1Stabilization ()
constructor
size_t num_ip () const
number of integration points
size_t num_sh () const
number of shapes (corners)
template<typename TFVGeom , typename TAssFunc >
void register_update_func (TAssFunc func)
register a update function for a Geometry
template<typename TFVGeom >
void set_geometry_type ()
set the FV1 Geometry type to use for next updates
void set_upwind (SmartPtr< INavierStokesUpwind< dim > > spUpwind)
sets the upwind method
number stab_shape_p (size_t scvf, size_t compOut, size_t sh) const
computed stab shape for pressure.
number stab_shape_vel (size_t scvf, size_t compOut, size_t compIn, size_t sh) const
const MathVector< dim > & stab_vel (size_t scvf) const
stabilized velocity
void update (const FVGeometryBase *geo, const LocalVector &vCornerValue, const MathVector< dim > vStdVel[], const bool bStokes, const DataImport< number, dim > &kinVisco, const DataImport< number, dim > &density, const DataImport< MathVector< dim >, dim > *pSource, const LocalVector *pvCornerValueOldTime, number dt)
compute values for new geometry and corner velocities
const ConstSmartPtr< INavierStokesUpwind< dim > > & upwind () const
returns the upwind
bool upwind_valid () const
returns if the upwind pointer is valid
bool vel_comp_connected () const
returns if stab velocity comp depends on other vel components
Static Public Attributes
static const int dim = TDim
Dimension.
Static Public Attributes inherited from ug::NavierStokes::INavierStokesFV1Stabilization< dim >
static const size_t maxNumSCV = traits::maxNumSCV
number of SubControlVolumes
static const size_t maxNumSCVF = traits::maxNumSCVF
max number of SubControlVolumeFaces
static const size_t maxNumSH = traits::maxNSH
max number of shape functions
Private Member Functions
void register_func ()
void register_func ()
void register_func ()
void register_func ()
template<typename TElem >
void register_func ()
Additional Inherited Members
Protected Types inherited from ug::NavierStokes::INavierStokesSRFV1Stabilization< TDim >
enum DiffusionLength
Protected Types inherited from ug::NavierStokes::INavierStokesFV1Stabilization< dim >
typedef fv1_dim_traits< dim, dim > traits
used traits
typedef void(this_type::* UpdateFunc) (const FVGeometryBase *geo, const LocalVector &vCornerValue, const MathVector< dim > vStdVel[], const bool bStokes, const DataImport< number, dim > &kinVisco, const DataImport< number, dim > &density, const DataImport< MathVector< dim >, dim > *pSource, const LocalVector *pvCornerValueOldTime, number dt)
type of update function
Protected Member Functions inherited from ug::NavierStokes::INavierStokesSRFV1Stabilization< TDim >
void compute_diff_length (const TFVGeom &geo)
computes the diffusion length
number diff_length_sq_inv (size_t scvf) const
diff length
number downwind_conv_length (size_t scvf) const
Convection Length.
number downwind_shape_ip (size_t scvf, size_t scvf2) const
upwind shapes for ip vel
number downwind_shape_sh (size_t scvf, size_t sh) const
upwind shape for corner vel
bool non_zero_shape_ip () const
returns if upwind shape w.r.t. ip vel is non-zero
number upwind_conv_length (size_t scvf) const
Convection Length.
number upwind_shape_ip (size_t scvf, size_t scvf2) const
upwind shapes for ip vel
number upwind_shape_sh (size_t scvf, size_t sh) const
upwind shape for corner vel
Protected Member Functions inherited from ug::NavierStokes::INavierStokesFV1Stabilization< dim >
template<typename TFVGeom >
void compute_downwind (const TFVGeom &geo, const MathVector< dim > vStdVel[])
computes the downwind shapes
template<typename TFVGeom >
void compute_upwind (const TFVGeom &geo, const MathVector< dim > vStdVel[])
computes the upwind shapes
void set_vel_comp_connected (bool bVelCompConnected)
sets the vel comp connected flag
number & stab_shape_p (size_t scvf, size_t compOut, size_t sh)
computed stab shape for pressure.
number & stab_shape_vel (size_t scvf, size_t compOut, size_t compIn, size_t sh)
MathVector< dim > & stab_vel (size_t scvf)
stabilized velocity
Protected Attributes inherited from ug::NavierStokes::INavierStokesSRFV1Stabilization< TDim >
DiffusionLength m_diffLengthType
type of diffusion length computation
number m_vDiffLengthSqInv [this_type::maxNumSCVF]
vector holding diffusion Length squared and inverted
Protected Attributes inherited from ug::NavierStokes::INavierStokesFV1Stabilization< dim >
std::vector< UpdateFunc > m_vUpdateFunc
Vector holding all update functions.
Detailed Description
template<int TDim>
class ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >
Implementation of the FIELDS stabilization
Member Typedef Documentation
base_type
template<int TDim> typedef INavierStokesSRFV1Stabilization<TDim> ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::base_type
Base class.
this_type
template<int TDim> typedef NavierStokesFIELDSStabilization<TDim> ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::this_type
This class.
Constructor & Destructor Documentation
NavierStokesFIELDSStabilization()
template<int TDim> ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::NavierStokesFIELDSStabilization () inline
constructor
References ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::register_func(), and ug::NavierStokes::INavierStokesFV1Stabilization< dim >::set_vel_comp_connected().
Member Function Documentation
register_func() [1/5]
void ug::NavierStokes::NavierStokesFIELDSStabilization< 1 >::register_func () private
register_func() [2/5]
void ug::NavierStokes::NavierStokesFIELDSStabilization< 2 >::register_func () private
register_func() [3/5]
void ug::NavierStokes::NavierStokesFIELDSStabilization< 3 >::register_func () private
register_func() [4/5]
template<int TDim> void ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::register_func () private
Referenced by ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::NavierStokesFIELDSStabilization().
register_func() [5/5]
template<int TDim> template<typename TElem > void ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::register_func () inline private
References ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::dim.
update()
template<int TDim> template<typename TElem > void ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::update (const FV1Geometry< TElem, dim > * geo, const LocalVector & vCornerValue, const MathVector< dim > vStdVel[], const bool bStokes, const DataImport< number, dim > & kinVisco, const DataImport< number, dim > & density, const DataImport< MathVector< dim >, dim > * pSource, const LocalVector * pvCornerValueOldTime, number dt)
update of values for FV1Geometry
need to solve system
References dim, FV1Geometry_gen< TElem, TWorldDim, false >::num_sh(), FV1Geometry_gen< TElem, TWorldDim, false >::scvf(), and ug::VecTwoNorm().
Member Data Documentation
dim
template<int TDim> const int ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::dim = TDim static
Dimension.
Referenced by ug::NavierStokes::NavierStokesFIELDSStabilization< TDim >::register_func().
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/stabilization.h
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/stabilization.cpp