Plugins: ug::DocuGen::ClassHierarchyProvider Class Reference
ug::DocuGen::ClassHierarchyProvider Class Reference
#include <class_hierarchy_provider.h>
Public Member Functions
ClassHierarchyProvider ()
ClassHierarchyProvider (const ClassHierarchyProvider &other)
string get_group (const string class_name)
void init (bridge::Registry &reg)
ClassHierarchyProvider & operator= (const ClassHierarchyProvider &other)
Private Attributes
map< string, string > class_to_group
Constructor & Destructor Documentation
ClassHierarchyProvider() [1/2]
ug::DocuGen::ClassHierarchyProvider::ClassHierarchyProvider ()
ClassHierarchyProvider() [2/2]
ug::DocuGen::ClassHierarchyProvider::ClassHierarchyProvider (const ClassHierarchyProvider & other)
References class_to_group.
Member Function Documentation
get_group()
string ug::DocuGen::ClassHierarchyProvider::get_group (const string class_name)
References class_to_group.
Referenced by ug::DocuGen::CppGenerator::generate_class_constructors(), ug::DocuGen::CppGenerator::generate_class_cpp(), ug::DocuGen::CppGenerator::generate_class_docu(), ug::DocuGen::CppGenerator::generate_class_group(), ug::DocuGen::CppGenerator::generate_cpp_files(), and ug::DocuGen::CppGenerator::parameter_to_string().
init()
void ug::DocuGen::ClassHierarchyProvider::init (bridge::Registry & reg)
References class_to_group, ug::bridge::ClassGroupDesc::get_class(), ug::bridge::Registry::get_class_group(), ug::bridge::ClassGroupDesc::name(), ug::bridge::IExportedClass::name(), ug::bridge::Registry::num_class_groups(), ug::bridge::ClassGroupDesc::num_classes(), UG_LOG, and UG_WARNING.
Referenced by ug::GenerateScriptReferenceDocu().
operator=()
ClassHierarchyProvider & ug::DocuGen::ClassHierarchyProvider::operator= (const ClassHierarchyProvider & other)
References class_to_group.
Member Data Documentation
class_to_group
map< string, string > ug::DocuGen::ClassHierarchyProvider::class_to_group private
Referenced by ClassHierarchyProvider(), get_group(), init(), and operator=().
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/DocuGen/src/class_hierarchy_provider.h
/home/runner/work/docs/docs/ug4/plugins/DocuGen/src/class_hierarchy_provider.cpp