Plugins: ug::Richards::UserDataFactory< dim > Class Template Reference
ug::Richards::UserDataFactory< dim > Class Template Reference
Factory class. This constructs appropriate "UserData" from suitable models.
#include <richards_linker.h>
Public Types
typedef SmartPtr< CplUserData< number, dim > > input_type
typedef SmartPtr< TUserDataNumber > return_type
typedef CplUserData< number, dim > TUserDataNumber
Public Member Functions
return_type create_conductivity (const ExponentialModel &m)
return_type create_conductivity (const VanGenuchtenModel &m)
return_type create_saturation (const ExponentialModel &m)
Exponential models.
return_type create_saturation (const VanGenuchtenModel &m)
UserDataFactory (input_type capillary)
Protected Attributes
input_type m_capillary
Detailed Description
template<int dim>
class ug::Richards::UserDataFactory< dim >
Factory class. This constructs appropriate "UserData" from suitable models.
Member Typedef Documentation
input_type
template<int dim> typedef SmartPtr<CplUserData<number, dim> > ug::Richards::UserDataFactory< dim >::input_type
return_type
template<int dim> typedef SmartPtr<TUserDataNumber> ug::Richards::UserDataFactory< dim >::return_type
TUserDataNumber
template<int dim> typedef CplUserData<number, dim> ug::Richards::UserDataFactory< dim >::TUserDataNumber
Constructor & Destructor Documentation
UserDataFactory()
template<int dim> ug::Richards::UserDataFactory< dim >::UserDataFactory (input_type capillary) inline
Member Function Documentation
create_conductivity() [1/2]
template<int dim> return_type ug::Richards::UserDataFactory< dim >::create_conductivity (const ExponentialModel & m) inline
References ug::Richards::UserDataFactory< dim >::m_capillary, and make_sp().
create_conductivity() [2/2]
template<int dim> return_type ug::Richards::UserDataFactory< dim >::create_conductivity (const VanGenuchtenModel & m) inline
References ug::Richards::UserDataFactory< dim >::m_capillary, and make_sp().
create_saturation() [1/2]
template<int dim> return_type ug::Richards::UserDataFactory< dim >::create_saturation (const ExponentialModel & m) inline
Exponential models.
References ug::Richards::UserDataFactory< dim >::m_capillary, and make_sp().
create_saturation() [2/2]
template<int dim> return_type ug::Richards::UserDataFactory< dim >::create_saturation (const VanGenuchtenModel & m) inline
References ug::Richards::UserDataFactory< dim >::m_capillary, and make_sp().
Member Data Documentation
m_capillary
template<int dim> input_type ug::Richards::UserDataFactory< dim >::m_capillary protected
Referenced by ug::Richards::UserDataFactory< dim >::create_conductivity(), and ug::Richards::UserDataFactory< dim >::create_saturation().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Richards/richards_linker.h