Plugins: ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::LocLaplaceA< TElem > Class Template Reference
ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::LocLaplaceA< TElem > Class Template Reference
Helper class for assembling the local stiffness matrix of Laplacian in various routines.
Public Types
typedef reference_element_traits< TElem >::reference_element_type ref_elem_type
Static Public Member Functions
static bool bnd_corners (GridObject *elem, const SubsetGroup &bndGrp, bool bnd_flag[numCorners])
Checks whether corners are on boundary (returns true if yes)
static void stiffness (GridObject *elem, const position_type vCornerCoords[], number loc_A[numCorners][numCorners])
Computes the local discretization of the Laplace operator.
Static Public Attributes
static const int numCorners = ref_elem_type::numCorners
Detailed Description
template<typename TDomain, typename TAlgebra>
template<typename TElem>
class ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::LocLaplaceA< TElem >
Helper class for assembling the local stiffness matrix of Laplacian in various routines.
Member Typedef Documentation
ref_elem_type
template<typename TDomain , typename TAlgebra > template<typename TElem > typedef reference_element_traits<TElem>::reference_element_type ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::LocLaplaceA< TElem >::ref_elem_type
Member Function Documentation
bnd_corners()
template<typename TDomain , typename TAlgebra > template<typename TElem > bool ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::LocLaplaceA< TElem >::bnd_corners (GridObject * elem, const SubsetGroup & bndGrp, bool bnd_flag[numCorners]) static
Checks whether corners are on boundary (returns true if yes)
Checks whether corners are on boundary (returns true if yes)
Parameters
[in] elem element to compute for
[in] bndGrp boundary subsets
[out] bnd_flag true for bnd nodes, false for others
References ug::SubsetGroup::contains(), ug::ISubsetHandler::get_subset_index(), and ug::SubsetGroup::subset_handler().
stiffness()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::LocLaplaceA< TElem >::stiffness (GridObject * elem, const position_type vCornerCoords[], number loc_A[numCorners][numCorners]) static
Computes the local discretization of the Laplace operator.
Computes the local discretization of the Laplace operator
Parameters
[in] elem element to compute for
[in] vCornerCoords coordinates of the corners of the element
[out] loc_A the local stiffness matrix
References ug::GeomProvider< class >::get(), UG_ASSERT, and ug::VecDot().
Referenced by ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::ass_JA_elem(), ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::AuxLaplaceLocAss::ass_rhs_elem(), and ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::get_flux_of_pot().
Member Data Documentation
numCorners
template<typename TDomain , typename TAlgebra > template<typename TElem > const int ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::LocLaplaceA< TElem >::numCorners = ref_elem_type::numCorners static
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_source.h
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_source_impl.h