Plugins: ug::luashell::LuaShell Class Reference
ug::luashell::LuaShell Class Reference
Plugins » Lua Shell
#include <lua_shell.h>
Public Member Functions
void abort_run (const char *message)
template<class TVal >
TVal get_val (const char *name)
LuaShell ()
void parse_file (const char *filename)
void reset ()
void run (const char *buffer)
void set (const char *name, const void *pval, const char *className)
void set (const char *name, ConstSmartPtr< void > pval, const char *className)
void set (const char *name, SmartPtr< void > pval, const char *className)
template<class TVal >
void set (const char *name, TVal value)
void set (const char *name, void *pval, const char *className)
Private Member Functions
void init_lua_state ()
Private Attributes
lua_State * m_luaState
Constructor & Destructor Documentation
LuaShell()
ug::luashell::LuaShell::LuaShell ()
Member Function Documentation
abort_run()
void ug::luashell::LuaShell::abort_run (const char * message)
References AbortRun().
get_val()
template<class TVal > TVal ug::luashell::LuaShell::get_val (const char * name) inline
References m_luaState, and UG_THROW.
init_lua_state()
void ug::luashell::LuaShell::init_lua_state () private
References GetDefaultLuaState(), SetLuaUGArgs(), UGLuaPrint(), UGLuaPrintAllProcs(), and UGLuaWrite().
parse_file()
void ug::luashell::LuaShell::parse_file (const char * filename)
References ReadFile().
reset()
void ug::luashell::LuaShell::reset ()
References ReleaseDefaultLuaState().
run()
void ug::luashell::LuaShell::run (const char * buffer)
References ClearAbortRunFlag(), ug::UGError::get_msg(), ug::luashell::LuaCallStackError(), PROFILE_FUNC, and UG_LOG.
set() [1/5]
void ug::luashell::LuaShell::set (const char * name, const void * pval, const char * className)
set() [2/5]
void ug::luashell::LuaShell::set (const char * name, ConstSmartPtr< void > pval, const char * className)
set() [3/5]
void ug::luashell::LuaShell::set (const char * name, SmartPtr< void > pval, const char * className)
set() [4/5]
template<class TVal > void ug::luashell::LuaShell::set (const char * name, TVal value) inline
References m_luaState.
set() [5/5]
void ug::luashell::LuaShell::set (const char * name, void * pval, const char * className)
Member Data Documentation
m_luaState
lua_State* ug::luashell::LuaShell::m_luaState private
Referenced by get_val(), and set().
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/LuaShell/lua_shell.h
/home/runner/work/docs/docs/ug4/plugins/LuaShell/lua_shell.cpp