Plugins: ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain > Class Template Reference
ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain > Class Template Reference
Plugins » Convection Diffusion
Discretization for the Convection-Diffusion Equation.
#include <convection_diffusion_fe.h>
Classes
struct ShapeValues
struct holding values of shape functions in IPs
Public Member Functions
ConvectionDiffusionFE (const char *functions, const char *subsets)
Constructor.
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegularGrid)
type of trial space for each function used
void set_quad_order (size_t order)
sets the quad order
virtual bool use_hanging () const
returns if hanging nodes are needed
Public Member Functions inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
ConvectionDiffusionBase (const char *functions, const char *subsets)
Constructor.
virtual SmartPtr< CplUserData< MathVector< dim >, dim > > gradient ()
returns the export of the gradient of associated unknown function
void set_reaction_explicit (SmartPtr< CplUserData< number, dim > > user)
void set_reaction_explicit (number val)
void set_reaction_rate_explicit (SmartPtr< CplUserData< number, dim > > user)
void set_reaction_rate_explicit (number val)
void set_source_explicit (SmartPtr< CplUserData< number, dim > > user)
void set_source_explicit (number val)
virtual SmartPtr< CplUserData< number, dim > > value ()
returns the export of the value of associated unknown function
void set_diffusion (SmartPtr< CplUserData< MathMatrix< dim, dim >, dim > > user)
sets the diffusion tensor
void set_diffusion (number val)
sets the diffusion tensor
void set_velocity (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the velocity field
void set_velocity (const std::vector< number > &vVel)
sets the velocity field
void set_flux (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the flux
void set_flux (const std::vector< number > &vVel)
sets the flux
void set_reaction_rate (SmartPtr< CplUserData< number, dim > > user)
sets the reaction rate
void set_reaction_rate (number val)
sets the reaction rate
void set_reaction (SmartPtr< CplUserData< number, dim > > user)
sets the reaction
void set_reaction (number val)
sets the reaction
void set_source (SmartPtr< CplUserData< number, dim > > user)
sets the source / sink term
void set_source (number val)
sets the source / sink term
void set_vector_source (SmartPtr< CplUserData< MathVector< dim >, dim > > user)
sets the vector source term
void set_vector_source (const std::vector< number > &vVel)
sets the vector source term
void set_mass_scale (SmartPtr< CplUserData< number, dim > > user)
sets mass scale
void set_mass_scale (number val)
sets mass scale
void set_mass (SmartPtr< CplUserData< number, dim > > user)
sets mass
void set_mass (number val)
sets mass
Public Member Functions inherited from ug::IElemDisc< TDomain >
void add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier)
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > & get_elem_modifier ()
IElemDisc (const char *functions, const char *subsets)
IElemDisc (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
virtual void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_fsh_elem_loop ()
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_timestep (number future_time, const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void fsh_timestep (number time, VectorProxyBase *u)
virtual void fsh_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemAssembleFuncs ()
virtual void post_assemble_loop ()
virtual void prep_assemble_loop ()
virtual void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
virtual void prep_elem_loop (const ReferenceObjectID roid, const int si)
virtual void prep_timestep (number future_time, number time, VectorProxyBase *u)
virtual void prep_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemAssembleFuncs ()
Public Member Functions inherited from ug::IElemError< class >
IElemError (const char *functions, const char *subsets)
IElemError (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from ug::IElemDiscBase< class >
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
void check_setup (bool bNonRegularGrid)
void clear_imports ()
SmartPtr< TDomain > domain ()
ConstSmartPtr< TDomain > domain () const
const FunctionGroup & function_group () const
ConstSmartPtr< FunctionPattern > function_pattern () const
IDataImport< dim > & get_import (size_t i)
IElemDiscBase (const char *functions="", const char *subsets="")
IElemDiscBase (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
bool is_time_dependent () const
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
const FunctionIndexMapping & map () const
number mass_scale (const size_t timePoint) const
number mass_scale () const
number mass_scale (const size_t timePoint) const
number mass_scale () const
const std::vector< number > & mass_scales () const
const std::vector< number > & mass_scales () const
size_t num_fct () const
size_t num_imports () const
size_t num_subsets () const
void register_import (IDataImport< dim > &Imp)
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_functions (const std::vector< std::string > &functions)
void set_functions (const std::string &functions)
void set_stationary (bool bStationaryForced=true)
void set_stationary ()
void set_subsets (const std::string &subsets)
void set_subsets (const std::vector< std::string > &subsets)
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
void set_time_independent ()
void set_time_point (const size_t timePoint)
number stiff_scale () const
number stiff_scale () const
number stiff_scale (const size_t timePoint) const
number stiff_scale (const size_t timePoint) const
const std::vector< number > & stiff_scales () const
const std::vector< number > & stiff_scales () const
const TDomain::subset_handler_type & subset_handler () const
TDomain::subset_handler_type & subset_handler ()
const std::vector< std::string > & symb_fcts () const
const std::vector< std::string > & symb_subsets () const
number time () const
size_t time_point () const
virtual int type () const
virtual ~IElemDiscBase ()
Public Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
virtual void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_err_est_elem_loop ()
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
IElemEstimatorFuncs ()
virtual void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemEstimatorFuncs ()
Static Public Attributes
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::IElemDisc< TDomain >
static const int dim
Static Public Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Static Public Attributes inherited from ug::IElemError< class >
static const int dim
Static Public Attributes inherited from ug::IElemDiscBase< class >
static const int dim
Static Public Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Protected Member Functions
template<typename TElem , typename TFEGeom >
void ex_grad (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< TFEGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< MathVector< dim > > > vvvDeriv[])
computes the gradient of the concentration
template<typename TElem , typename TFEGeom >
void ex_value (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< TFEGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< number > > vvvDeriv[])
computes the concentration
template<typename TElem , typename TFEGeom >
void lin_def_diffusion (const LocalVector &u, std::vector< std::vector< MathMatrix< dim, dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the velocity
template<typename TElem , typename TFEGeom >
void lin_def_flux (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the flux
template<typename TElem , typename TFEGeom >
void lin_def_mass (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the mass scale term
template<typename TElem , typename TFEGeom >
void lin_def_mass_scale (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the mass scale term
template<typename TElem , typename TFEGeom >
void lin_def_reaction (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the reaction
template<typename TElem , typename TFEGeom >
void lin_def_reaction_rate (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the reaction
template<typename TElem , typename TFEGeom >
void lin_def_source (const LocalVector &u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the source term
template<typename TElem , typename TFEGeom >
void lin_def_vector_source (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the vector source term
template<typename TElem , typename TFEGeom >
void lin_def_velocity (const LocalVector &u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip)
computes the linearized defect w.r.t to the velocity
void register_all_funcs (const LFEID &lfeid, const int quadOrder)
template<typename TElem , typename TFEGeom >
void register_func ()
Protected Member Functions inherited from ug::IElemDisc< TDomain >
void clear_add_fct (ReferenceObjectID id)
void clear_add_fct ()
void set_default_add_fct ()
Protected Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct (ReferenceObjectID id)
void clear_add_fct ()
void remove_add_def_A_elem_fct (ReferenceObjectID id)
void remove_add_def_A_expl_elem_fct (ReferenceObjectID id)
void remove_add_def_M_elem_fct (ReferenceObjectID id)
void remove_add_jac_A_elem_fct (ReferenceObjectID id)
void remove_add_jac_M_elem_fct (ReferenceObjectID id)
void remove_add_rhs_elem_fct (ReferenceObjectID id)
void remove_fsh_elem_loop_fct (ReferenceObjectID id)
void remove_fsh_timestep_elem_fct (ReferenceObjectID id)
void remove_fsh_timestep_fct (size_t algebra_id)
void remove_prep_elem_fct (ReferenceObjectID id)
void remove_prep_elem_loop_fct (ReferenceObjectID id)
void remove_prep_timestep_elem_fct (ReferenceObjectID id)
void remove_prep_timestep_fct (size_t algebra_id)
void set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_fct (size_t algebra_id, TAssFunc func)
void set_prep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_fct (size_t algebra_id, TAssFunc func)
Protected Member Functions inherited from ug::IElemError< class >
void clear_add_fct (ReferenceObjectID id)
void clear_add_fct ()
Protected Member Functions inherited from ug::IElemDiscBase< class >
virtual void approximation_space_changed ()
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
void update_function_index_mapping ()
Protected Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct (ReferenceObjectID id)
void clear_add_fct ()
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
Protected Attributes
bool m_bQuadOrderUserDef
current integration order
LFEID m_lfeID
current shape function set
int m_quadOrder
Protected Attributes inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
SmartPtr< DataExport< MathVector< dim >, dim > > m_exGrad
Export for the gradient of concentration.
SmartPtr< DataExport< number, dim > > m_exValue
Export for the concentration.
DataImport< MathMatrix< dim, dim >, dim > m_imDiffusion
Data import for Diffusion.
DataImport< MathVector< dim >, dim > m_imFlux
Data import for the Flux.
DataImport< number, dim > m_imMass
Data import for the mass scale.
DataImport< number, dim > m_imMassScale
Data import for the mass scale.
DataImport< number, dim > m_imReaction
Data import for the reaction term.
DataImport< number, dim > m_imReactionExpl
Data import for the reaction term explicit.
DataImport< number, dim > m_imReactionRate
Data import for the reaction term.
DataImport< number, dim > m_imReactionRateExpl
Data import for the reaction_rate term explicit.
DataImport< number, dim > m_imSource
Data import for the right-hand side (volume)
DataImport< number, dim > m_imSourceExpl
Data import for the source term explicit.
DataImport< MathVector< dim >, dim > m_imVectorSource
Data import for the right-hand side (vector)
DataImport< MathVector< dim >, dim > m_imVelocity
Data import for the Velocity field.
Protected Attributes inherited from ug::IElemDisc< TDomain >
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > m_spElemModifier
Protected Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
Protected Attributes inherited from ug::IElemDiscBase< class >
bool m_bStationaryForced
FunctionGroup m_fctGrp
FunctionIndexMapping m_fctIndexMap
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
ConstSmartPtr< FunctionPattern > m_spFctPattern
size_t m_timePoint
std::vector< std::string > m_vFct
std::vector< IDataImport< dim > *> m_vIImport
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
std::vector< std::string > m_vSubset
Protected Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
Private Types
typedef ConvectionDiffusionBase< TDomain > base_type
Base class type.
typedef SideAndElemErrEstData< TDomain > err_est_type
error estimator type
typedef ConvectionDiffusionFE< TDomain > this_type
Own type.
Private Member Functions
template<typename TElem , typename TFEGeom >
void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the stiffness part of the local defect
template<typename TElem , typename TFEGeom >
void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the mass part of the local defect
template<typename TElem , typename TFEGeom >
void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the local stiffness matrix using a finite volume scheme
template<typename TElem , typename TFEGeom >
void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the local mass matrix using a finite volume scheme
template<typename TElem , typename TFEGeom >
void add_rhs_elem (LocalVector &d, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the local right hand side
template<typename TElem , typename TFEGeom >
void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
computes the error estimator contribution for one element
template<typename TElem , typename TFEGeom >
void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
computes the error estimator contribution for one element
template<typename TElem , typename TFEGeom >
void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
computes the error estimator contribution for one element
template<typename TElem , typename TFEGeom >
void fsh_elem_loop ()
finishes the loop over all elements
template<typename TElem , typename TFEGeom >
void fsh_err_est_elem_loop ()
postprocesses the loop over all elements of one type in the computation of the error estimator
template<typename TElem , typename TFEGeom >
void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
prepares the element for assembling
template<typename TElem , typename TFEGeom >
void prep_elem_loop (const ReferenceObjectID roid, const int si)
prepares the loop over all elements
template<typename TElem , typename TFEGeom >
void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
prepares the element for assembling the error estimator
template<typename TElem , typename TFEGeom >
void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
prepares the loop over all elements of one type for the computation of the error estimator
Private Attributes
struct ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE::ShapeValues m_shapeValues
Static Private Attributes
static const size_t _C_ = 0
abbreviation for the local solution
Additional Inherited Members
Public Types inherited from ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >
typedef SmartPtr< CplUserData< MathVector< dim >, dim > > GradExport
typedef SmartPtr< CplUserData< number, dim > > NumberExport
Public Types inherited from ug::IElemDisc< TDomain >
typedef IElemAssembleFuncs< IElemDisc< TDomain >, TDomain > assemble_base_type
typedef IElemError< TDomain > base_type
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Public Types inherited from ug::IElemError< class >
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from ug::IElemDiscBase< class >
typedef TDomain domain_type
typedef TDomain::position_type position_type
Public Types inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Detailed Description
template<typename TDomain>
class ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >
Discretization for the Convection-Diffusion Equation.
This class implements the IElemDisc interface to provide element local assemblings for the convection diffusion equation. The Equation has the form
\[ \partial_t (m1*c + m2) - \nabla \left(D \nabla c - \vec{v} c \right + \vec{F}) + r1 \cdot c + r2 = f + f2 \]
with
\(c \) is the unknown solution
\(m1 \equiv m(\vec{x},t) \) is the Mass Scaling Term
\(m2 \equiv m(\vec{x},t) \) is the Mass Term
\(D \equiv D(\vec{x},t) \) is the Diffusion Tensor
\(v \equiv \vec{v}(\vec{x},t) \) is the Velocity Field
\(F \equiv \vec{F}(\vec{x},t) \) is the Flux
\(r1 \equiv r(\vec{x},t) \) is the Reaction Rate
\(r2 \equiv r(\vec{x},t) \) is a Reaction Term
\(f \equiv f(\vec{x},t) \) is a Source Term
\(f2 \equiv f_2(\vec{x},t) \) is a Vector Source Term
Template Parameters
TDomain Domain
TAlgebra Algebra
Member Typedef Documentation
base_type
template<typename TDomain > typedef ConvectionDiffusionBase<TDomain> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::base_type private
Base class type.
err_est_type
template<typename TDomain > typedef SideAndElemErrEstData<TDomain> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::err_est_type private
error estimator type
this_type
template<typename TDomain > typedef ConvectionDiffusionFE<TDomain> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::this_type private
Own type.
Constructor & Destructor Documentation
ConvectionDiffusionFE()
template<typename TDomain > ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ConvectionDiffusionFE (const char * functions, const char * subsets)
Constructor.
References ug::IElemDisc< TDomain >::clear_add_fct().
Member Function Documentation
add_def_A_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_A_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private
assembles the stiffness part of the local defect
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_M_elem(), ug::DataImport< TData, dim >::data_given(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, ug::MatVecMult(), ug::VecDot(), ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_M_elem().
add_def_M_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_M_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private
assembles the mass part of the local defect
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_rhs_elem(), ug::DataImport< TData, dim >::data_given(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_A_elem().
add_jac_A_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_A_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private
assembles the local stiffness matrix using a finite volume scheme
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_M_elem(), ug::DataImport< TData, dim >::data_given(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, ug::MatVecMult(), ug::VecDot(), ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_elem().
add_jac_M_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_M_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private
assembles the local mass matrix using a finite volume scheme
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_A_elem(), ug::DataImport< TData, dim >::data_given(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_A_elem().
add_rhs_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_rhs_elem (LocalVector & d, GridObject * elem, const MathVector< dim > vCornerCoords[]) private
assembles the local right hand side
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::DataImport< TData, dim >::data_given(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_err_est_elem_loop(), and ug::VecDot().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_M_elem().
compute_err_est_A_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_A_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) private
computes the error estimator contribution for one element
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::Grid::associated_elements_sorted(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_M_elem(), ug::DataImport< TData, dim >::data_given(), IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::err_est_data(), ug::GeomProvider< TGeom >::get(), SmartPtr< T, FreePolicy >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_shapeValues, IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::m_spErrEstData, ug::MatVecScaleMultAppend(), normal, ug::SideAndElemErrEstData< TDomain >::num_elem_ips(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ShapeValues::num_sh(), ug::SideAndElemErrEstData< TDomain >::num_side_ips(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ShapeValues::shapeAtElemIP(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ShapeValues::shapeAtSideIP(), ug::SideAndElemErrEstData< TDomain >::surface_view(), UG_CATCH_THROW, UG_THROW, ug::VecAppend(), ug::VecDot(), ug::VecNormalize(), ug::VecScale(), ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_err_est_elem().
compute_err_est_M_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_M_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) private
computes the error estimator contribution for one element
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::Grid::associated_elements_sorted(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_rhs_elem(), ug::DataImport< TData, dim >::data_given(), IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::err_est_data(), SmartPtr< T, FreePolicy >::get(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_shapeValues, IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::m_spErrEstData, ug::SideAndElemErrEstData< TDomain >::num_elem_ips(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ShapeValues::shapeAtElemIP(), ug::SideAndElemErrEstData< TDomain >::surface_view(), UG_CATCH_THROW, and UG_THROW.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_A_elem().
compute_err_est_rhs_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_rhs_elem (GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) private
computes the error estimator contribution for one element
References ug::Grid::associated_elements_sorted(), ug::DataImport< TData, dim >::data_given(), IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::err_est_data(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::fsh_err_est_elem_loop(), SmartPtr< T, FreePolicy >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::m_spErrEstData, normal, ug::SideAndElemErrEstData< TDomain >::num_elem_ips(), ug::SideAndElemErrEstData< TDomain >::num_side_ips(), ug::SideAndElemErrEstData< TDomain >::surface_view(), UG_CATCH_THROW, UG_THROW, ug::VecDot(), and ug::VecNormalize().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_M_elem().
ex_grad()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_grad (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< TFEGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< MathVector< dim > > > vvvDeriv[]) protected
computes the gradient of the concentration
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::grads(), ug::ReferenceMapping< TRefElem, TWorldDim >::jacobian_transposed_inverse(), ug::LFEID::LAGRANGE, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, ug::MatVecMult(), ug::LocalDoFSet::num_sh(), ug::LFEID::order(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::register_all_funcs(), ug::LFEID::type(), UG_CATCH_THROW, ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_value().
ex_value()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_value (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< TFEGeom::dim > vLocIP[], const size_t nip, bool bDeriv, std::vector< std::vector< number > > vvvDeriv[]) protected
computes the concentration
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_grad(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, ug::LocalDoFSet::num_sh(), ug::LocalShapeFunctionSet< TDim, TShape, TGrad >::shapes(), and UG_CATCH_THROW.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass().
fsh_elem_loop()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::fsh_elem_loop () private virtual
finishes the loop over all elements
Reimplemented from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_elem().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_elem_loop().
fsh_err_est_elem_loop()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::fsh_err_est_elem_loop () private virtual
postprocesses the loop over all elements of one type in the computation of the error estimator
Reimplemented from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_velocity().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_rhs_elem().
lin_def_diffusion()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_diffusion (const LocalVector & u, std::vector< std::vector< MathMatrix< dim, dim > > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the velocity
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::dim, ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, ug::VecScaleAppend(), and ug::VecSet().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_flux().
lin_def_flux()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_flux (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the flux
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_diffusion(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, and ug::VecScale().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_velocity().
lin_def_mass()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the mass scale term
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_value(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass_scale().
lin_def_mass_scale()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass_scale (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the mass scale term
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_vector_source().
lin_def_reaction()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the reaction
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction_rate(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_diffusion().
lin_def_reaction_rate()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction_rate (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the reaction
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction().
lin_def_source()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_source (const LocalVector & u, std::vector< std::vector< number > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the source term
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_vector_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction_rate().
lin_def_vector_source()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_vector_source (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the vector source term
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass_scale(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, and ug::VecScale().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_source().
lin_def_velocity()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_velocity (const LocalVector & u, std::vector< std::vector< MathVector< dim > > > vvvLinDef[], const size_t nip) protected
computes the linearized defect w.r.t to the velocity
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_, ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_flux(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, and ug::VecScale().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::fsh_err_est_elem_loop().
prep_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_elem (const LocalVector & u, GridObject * elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[]) private
prepares the element for assembling
This methods prepares an element for the assembling. The Positions of the Element Corners are read and the Finite Volume Geometry is updated. The global ip positions are scheduled at the data imports.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_A_elem(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, ug::DataImport< TData, dim >::set_global_ips(), and UG_CATCH_THROW.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::fsh_elem_loop().
prep_elem_loop()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_elem_loop (const ReferenceObjectID roid, const int si) private
prepares the loop over all elements
This method prepares the loop over all elements. It resizes the Position array for the corner coordinates and schedules the local ip positions at the data imports.
References ug::DataImport< TData, dim >::data_given(), dim, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::fsh_elem_loop(), ug::GeomProvider< TGeom >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRateExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSourceExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, UG_CATCH_THROW, and UG_THROW.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::use_hanging().
prep_err_est_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_err_est_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private
prepares the element for assembling the error estimator
References ug::SideAndElemErrEstData< TDomain >::all_side_global_ips(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_A_elem(), ug::SideAndElemErrEstData< TDomain >::elem_global_ips(), IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::err_est_data(), ug::GeomProvider< TGeom >::get(), SmartPtr< T, FreePolicy >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::m_spErrEstData, ug::SideAndElemErrEstData< TDomain >::num_all_side_ips(), ug::SideAndElemErrEstData< TDomain >::num_elem_ips(), ug::GridObject::reference_object_id(), and UG_CATCH_THROW.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_err_est_elem_loop().
prep_err_est_elem_loop()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_err_est_elem_loop (const ReferenceObjectID roid, const int si) private
prepares the loop over all elements of one type for the computation of the error estimator
References dim, IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::err_est_data(), SmartPtr< T, FreePolicy >::get(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_shapeValues, IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::m_spErrEstData, ug::SideAndElemErrEstData< TDomain >::num_all_side_ips(), ug::SideAndElemErrEstData< TDomain >::num_elem_ips(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_err_est_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ShapeValues::resize(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ShapeValues::shapesAtElemIP(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ShapeValues::shapesAtSideIP(), UG_CATCH_THROW, and UG_THROW.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_rhs_elem().
prepare_setting()
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prepare_setting (const std::vector< LFEID > & vLfeID, bool bNonRegularGrid) virtual
type of trial space for each function used
Implements ug::IElemDiscBase< class >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_bQuadOrderUserDef, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, ug::LFEID::order(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::register_all_funcs(), UG_THROW, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::use_hanging().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::set_quad_order().
register_all_funcs()
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::register_all_funcs (const LFEID & lfeid, const int quadOrder) protected
register utils
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_grad(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prepare_setting().
register_func()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::register_func () protected
register utils
References ug::IElemDisc< TDomain >::clear_add_fct(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_exGrad, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_exValue, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::set_add_def_A_elem_fct(), IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::set_add_def_M_elem_fct(), IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::set_add_jac_A_elem_fct(), IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::set_add_jac_M_elem_fct(), IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::set_add_rhs_elem_fct(), IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::set_compute_err_est_A_elem(), IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::set_compute_err_est_M_elem(), IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::set_compute_err_est_rhs_elem(), IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::set_fsh_elem_loop_fct(), IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::set_fsh_err_est_elem_loop(), IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::set_prep_elem_fct(), IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >::set_prep_elem_loop_fct(), IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::set_prep_err_est_elem(), and IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::set_prep_err_est_elem_loop().
set_quad_order()
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::set_quad_order (size_t order)
sets the quad order
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_bQuadOrderUserDef, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder, and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prepare_setting().
use_hanging()
template<typename TDomain > bool ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::use_hanging () const virtual
returns if hanging nodes are needed
Reimplemented from ug::IElemDiscBase< class >.
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_elem_loop().
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prepare_setting().
Member Data Documentation
_C_
template<typename TDomain > const size_t ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::_C_ = 0 static private
abbreviation for the local solution
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_rhs_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_grad(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_value(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_diffusion(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_flux(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass_scale(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction_rate(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_vector_source(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_velocity().
dim
template<typename TDomain > const int ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::dim = base_type::dim static
World dimension.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_diffusion().
m_bQuadOrderUserDef
template<typename TDomain > bool ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_bQuadOrderUserDef protected
current integration order
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prepare_setting(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::set_quad_order().
m_lfeID
template<typename TDomain > LFEID ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_lfeID protected
current shape function set
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_rhs_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_grad(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_value(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_diffusion(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_flux(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass_scale(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction_rate(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_vector_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_velocity(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_elem_loop(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_err_est_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prepare_setting().
m_quadOrder
template<typename TDomain > int ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_quadOrder protected
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_def_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_jac_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::add_rhs_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_grad(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::ex_value(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_diffusion(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_flux(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_mass_scale(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_reaction_rate(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_vector_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::lin_def_velocity(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_elem_loop(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_err_est_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prepare_setting(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::set_quad_order().
m_shapeValues
template<typename TDomain > struct ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE::ShapeValues ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::m_shapeValues private
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::compute_err_est_M_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFE< TDomain >::prep_err_est_elem_loop().
The documentation for this class was generated from the following files:
/home/sreiter/ug4-docugen/plugins/ConvectionDiffusion/fe/convection_diffusion_fe.h
/home/sreiter/ug4-docugen/plugins/ConvectionDiffusion/fe/convection_diffusion_fe.cpp