Plugins: ug::Electromagnetism::NedelecProlongationMatrixHelper< TDomain, TAlgebra, RegularEdge > Class Template Reference
ug::Electromagnetism::NedelecProlongationMatrixHelper< TDomain, TAlgebra, RegularEdge > Class Template Reference
#include <nedelec_transfer.h>
Static Public Member Functions
static void assemble_prolongation_matrix (const domain_type &domain, const DoFDistribution &coarseDD, const DoFDistribution &fineDD, matrix_type &mat, std::vector< bool > &vIsRestricted)
assembles the prolongation matrix for one type of the grid elements
Private Types
typedef TAlgebra algebra_type
Type of algebra.
typedef TDomain domain_type
Type of Domain.
typedef TAlgebra::matrix_type matrix_type
Type of Vector.
Static Private Attributes
static const int WDim = TDomain::dim
world dimention
Detailed Description
template<typename TDomain, typename TAlgebra>
class ug::Electromagnetism::NedelecProlongationMatrixHelper< TDomain, TAlgebra, RegularEdge >
Helper class for assembling the prolongation matrix: Instantiation for edges.
Member Typedef Documentation
algebra_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra ug::Electromagnetism::NedelecProlongationMatrixHelper< TDomain, TAlgebra, RegularEdge >::algebra_type private
Type of algebra.
domain_type
template<typename TDomain , typename TAlgebra > typedef TDomain ug::Electromagnetism::NedelecProlongationMatrixHelper< TDomain, TAlgebra, RegularEdge >::domain_type private
Type of Domain.
matrix_type
template<typename TDomain , typename TAlgebra > typedef TAlgebra::matrix_type ug::Electromagnetism::NedelecProlongationMatrixHelper< TDomain, TAlgebra, RegularEdge >::matrix_type private
Type of Vector.
Member Function Documentation
assemble_prolongation_matrix()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecProlongationMatrixHelper< TDomain, TAlgebra, RegularEdge >::assemble_prolongation_matrix (const domain_type & domain, const DoFDistribution & coarseDD, const DoFDistribution & fineDD, matrix_type & mat, std::vector< bool > & vIsRestricted) static
assembles the prolongation matrix for one type of the grid elements
Assembles the prolongation matrix for the DoFs between the edges for one type of the grid elements. (This instantiation works with edges.) To get the total prolongation matrix, the functions for all the types should be called.
Note that we assume here that the father edge is subdivided into two edges with equal length (or is not subdivided at all). At least, the prolongation coefficients are computed for the regular refinement.
Parameters
[in] domain the domain
[in] coarseDD the coarse grid DD
[in] fineDD the fine grid DD
[out] mat the interpolation matrix
[out] vIsRestricted whether a coarse grid DoF has children
References ug::DoFRef(), SmartPtr< MultiGrid >::get(), grid(), ug::DoFDistribution::inner_dof_indices(), ug::DoFDistribution::multi_grid(), ug::DoFDistributionInfoProvider::num_fct(), ug::DoFDistributionInfoProvider::num_subsets(), UG_ASSERT, UG_THROW, and ug::EdgeVertices::vertex().
Member Data Documentation
WDim
template<typename TDomain , typename TAlgebra > const int ug::Electromagnetism::NedelecProlongationMatrixHelper< TDomain, TAlgebra, RegularEdge >::WDim = TDomain::dim static private
world dimention
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_transfer.h
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_transfer_impl.h