Plugins: ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS Class Reference
ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS Class Reference
Constraint that assembles the rhs und the bc for the auxiliary problems.
Classes
struct SetIdentityOnSubset
Helper class for 'set_value_on_subset'.
struct SetValueOnSubset
Helper class for 'set_value_on_subset'.
Public Member Functions
void adjust_defect (pot_vector_type &d, const pot_vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< pot_vector_type > > vSol=SPNULL, const std::vector< number > *vScaleMass=NULL, const std::vector< number > *vScaleStiff=NULL)
sets a zero value in the defect for all conductor indices
void adjust_jacobian (pot_matrix_type &J, const pot_vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< pot_vector_type > > vSol=SPNULL, const number s_a0=1.0)
sets a unity row for all conductor indices
void adjust_linear (pot_matrix_type &A, pot_vector_type &b, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
sets unity rows in A and dirichlet values in right-hand side b
void adjust_rhs (pot_vector_type &b, const pot_vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
sets the dirichlet value in the right-hand side
void adjust_solution (pot_vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
sets the value in the solution for all conductor indices
AuxLaplaceRHS (NedelecProject &master)
constructor
void set_base_conductor (int base_cond=-1)
sets the base conductor index (or -1 for the divergence correction)
int type () const
returns the type of the constraints
Public Member Functions inherited from ug::IDomainConstraint< TDomain, TPotAlgebra >
SmartPtr< ApproximationSpace< TDomain > > approximation_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approximation_space () const
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
IDomainConstraint ()
virtual void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_ass_tuner (ConstSmartPtr< AssemblingTuner< TAlgebra > > spAssemblingTuner=NULL)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
Public Member Functions inherited from ug::IConstraint< class >
virtual void adjust_correction (vector_type &c, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
virtual void adjust_defect (vector_type &d, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol=SPNULL, const std::vector< number > *vScaleMass=NULL, const std::vector< number > *vScaleStiff=NULL)=0
virtual void adjust_error (const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol=SPNULL, const std::vector< number > *vScaleMass=NULL, const std::vector< number > *vScaleStiff=NULL)
virtual void adjust_jacobian (matrix_type &J, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol=SPNULL, const number s_a0=1.0)=0
virtual void adjust_linear (matrix_type &mat, vector_type &rhs, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)=0
virtual void adjust_linear_residual (vector_type &d, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
virtual void adjust_prolongation (matrix_type &P, ConstSmartPtr< DoFDistribution > ddFine, ConstSmartPtr< DoFDistribution > ddCoarse, int type, number time=0.0)
virtual void adjust_prolongation (vector_type &uFine, GridLevel fineLvl, const vector_type &uCoarse, GridLevel coarseLvl, int type)
virtual void adjust_restriction (matrix_type &R, ConstSmartPtr< DoFDistribution > ddCoarse, ConstSmartPtr< DoFDistribution > ddFine, int type, number time=0.0)
virtual void adjust_restriction (vector_type &uCoarse, GridLevel coarseLvl, const vector_type &uFine, GridLevel fineLvl, int type)
virtual void adjust_rhs (vector_type &rhs, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)=0
virtual void adjust_solution (vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)=0
virtual void modify_solution (SmartPtr< VectorTimeSeries< vector_type > > vSolMod, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd, int type)
virtual void modify_solution (vector_type &uMod, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type)
virtual ~IConstraint ()
Private Types
typedef DoFDistribution::traits< Edge >::const_iterator t_edge_iterator
Iterator over edges.
typedef DoFDistribution::traits< Vertex >::const_iterator t_vert_iterator
Iterator over vertices.
Private Member Functions
void set_identity_Dirichlet (pot_matrix_type &A, const DoFDistribution *dd)
sets identity matrix on the whole Dirichlet boundary
template<typename TElem >
void set_identity_on_subset (int si, pot_matrix_type &A, const DoFDistribution *dd)
sets identity matrix on the closure of a full-dimensional subset
template<typename TElem >
void set_value_on_subset (int si, number val, pot_vector_type &u, const DoFDistribution *dd)
sets constant value on the closure of a full-dimensional subset
void set_zero_Dirichlet (pot_vector_type &u, const DoFDistribution *dd)
sets zero values on the whole Dirichlet boundary
Private Attributes
int m_base_cond
the base conductor index (or -1 for insulators)
NedelecProject & m_master
the master object of the projection
Static Private Attributes
static const size_t maxCorners = (size_t) element_list_traits<typename domain_traits<WDim>::DimElemList>::maxCorners
maximum number of corners of an element
Additional Inherited Members
Public Types inherited from ug::IDomainConstraint< TDomain, TPotAlgebra >
typedef TAlgebra algebra_type
typedef TDomain domain_type
typedef algebra_type::matrix_type matrix_type
typedef algebra_type::vector_type vector_type
Public Types inherited from ug::IConstraint< class >
typedef TAlgebra algebra_type
typedef algebra_type::matrix_type matrix_type
typedef algebra_type::vector_type vector_type
Protected Member Functions inherited from ug::IDomainConstraint< TDomain, TPotAlgebra >
ConstSmartPtr< DoFDistribution > dd (const GridLevel &gl) const
Protected Attributes inherited from ug::IDomainConstraint< TDomain, TPotAlgebra >
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
ConstSmartPtr< AssemblingTuner< TAlgebra > > m_spAssTuner
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
Detailed Description
template<typename TDomain, typename TAlgebra>
class ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS
Constraint that assembles the rhs und the bc for the auxiliary problems.
Member Typedef Documentation
t_edge_iterator
template<typename TDomain , typename TAlgebra > typedef DoFDistribution::traits<Edge>::const_iterator ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::t_edge_iterator private
Iterator over edges.
t_vert_iterator
template<typename TDomain , typename TAlgebra > typedef DoFDistribution::traits<Vertex>::const_iterator ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::t_vert_iterator private
Iterator over vertices.
Constructor & Destructor Documentation
AuxLaplaceRHS()
template<typename TDomain , typename TAlgebra > ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::AuxLaplaceRHS (NedelecProject & master)
constructor
Class constructor:
Parameters
[in] master the master object
Member Function Documentation
adjust_defect()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_defect (pot_vector_type & d, const pot_vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0, ConstSmartPtr< VectorTimeSeries< pot_vector_type > > vSol = SPNULL, const std::vector< number > * vScaleMass = NULL, const std::vector< number > * vScaleStiff = NULL)
sets a zero value in the defect for all conductor indices
Sets the conductor-entries of a given defect vector to 0.
References ConstSmartPtr< class, FreePolicy >::get().
adjust_jacobian()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_jacobian (pot_matrix_type & J, const pot_vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0, ConstSmartPtr< VectorTimeSeries< pot_vector_type > > vSol = SPNULL, const number s_a0 = 1.0)
sets a unity row for all conductor indices
Sets the conductor-rows of a given Jacobian to the identity.
References ConstSmartPtr< class, FreePolicy >::get().
Referenced by ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_linear().
adjust_linear()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_linear (pot_matrix_type & A, pot_vector_type & b, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0) inline
sets unity rows in A and dirichlet values in right-hand side b
References ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_jacobian(), ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_solution(), ug::IDomainConstraint< TDomain, TPotAlgebra >::dd(), and ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::type().
adjust_rhs()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_rhs (pot_vector_type & b, const pot_vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0) inline
sets the dirichlet value in the right-hand side
References ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_solution(), ug::IDomainConstraint< TDomain, TPotAlgebra >::dd(), and ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::type().
adjust_solution()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_solution (pot_vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0)
sets the value in the solution for all conductor indices
Sets the conductor-entries of a given solution vector to the boundary values.
References ConstSmartPtr< class, FreePolicy >::get().
Referenced by ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_linear(), and ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_rhs().
set_base_conductor()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::set_base_conductor (int base_cond = -1) inline
sets the base conductor index (or -1 for the divergence correction)
Parameters
base_cond index of the base conductor
References ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::m_base_cond.
set_identity_Dirichlet()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::set_identity_Dirichlet (pot_matrix_type & A, const DoFDistribution * dd) private
sets identity matrix on the whole Dirichlet boundary
Sets identity matrix on the whole Dirichlet boundary.
Parameters
A the matrix to set
dd the vert.-based DoF distribution
References ug::DoFDistribution::begin(), ug::DoFDistribution::end(), ug::DoFDistribution::inner_algebra_indices(), ug::SetDirichletRow(), ug::SubsetGroup::size(), UG_THROW, and ug::EdgeVertices::vertex().
set_identity_on_subset()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::set_identity_on_subset (int si, pot_matrix_type & A, const DoFDistribution * dd) private
sets identity matrix on the closure of a full-dimensional subset
Sets identity matrix on the closure of a full-dimensional subset.
Parameters
si the subset
A the matrix to set
dd the vert.-based DoF distribution
References ug::DoFDistribution::begin(), ug::DoFDistribution::end(), ug::DoFDistribution::inner_algebra_indices(), ug::SetDirichletRow(), and UG_THROW.
set_value_on_subset()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::set_value_on_subset (int si, number val, pot_vector_type & u, const DoFDistribution * dd) private
sets constant value on the closure of a full-dimensional subset
Sets constant value on the closure of a full-dimensional subset.
Parameters
si the subset
val the value to set
u the vector where to set
dd the vert.-based DoF distribution
References ug::DoFDistribution::begin(), ug::DoFDistribution::end(), ug::DoFDistribution::inner_algebra_indices(), and UG_THROW.
set_zero_Dirichlet()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::set_zero_Dirichlet (pot_vector_type & u, const DoFDistribution * dd) private
sets zero values on the whole Dirichlet boundary
Sets zero values on the whole Dirichlet boundary.
Parameters
u the vector where to set zeros
dd the vert.-based DoF distribution
References ug::DoFDistribution::begin(), ug::DoFDistribution::end(), ug::DoFDistribution::inner_algebra_indices(), ug::SubsetGroup::size(), UG_THROW, and ug::EdgeVertices::vertex().
type()
template<typename TDomain , typename TAlgebra > int ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::type () const inline virtual
returns the type of the constraints
Implements ug::IDomainConstraint< TDomain, TPotAlgebra >.
References ug::CT_DIRICHLET.
Referenced by ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_linear(), and ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::adjust_rhs().
Member Data Documentation
m_base_cond
template<typename TDomain , typename TAlgebra > int ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::m_base_cond private
the base conductor index (or -1 for insulators)
Referenced by ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::set_base_conductor().
m_master
template<typename TDomain , typename TAlgebra > NedelecProject& ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::m_master private
the master object of the projection
maxCorners
template<typename TDomain , typename TAlgebra > const size_t ug::Electromagnetism::NedelecProject< TDomain, TAlgebra >::AuxLaplaceRHS::maxCorners = (size_t) element_list_traits<typename domain_traits<WDim>::DimElemList>::maxCorners static private
maximum number of corners of an element
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_project.h
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_project_impl.h