Plugins: ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain > Class Template Reference
ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain > Class Template Reference
#include <damage.h>
Public Types
typedef contrained_dim_traits< dim >::contrained_side_type TContrainedSide
typedef contrained_dim_traits< dim >::contraining_side_type TContrainingSide
typedef grid_dim_traits< dim >::element_type TElem
typedef TDomain::grid_type TGrid
typedef TDomain::position_accessor_type TPositionAccessor
typedef grid_dim_traits< dim >::side_type TSide
Public Member Functions
DamageFunctionUpdater ()
int last_num_iterations () const
void set_debug (SmartPtr< GridFunctionDebugWriter< TDomain, CPUAlgebra > > spDebugWriter)
void set_disc_type (const std::string &type)
void set_quad_rule (int quadRuleType)
bool solve (SmartPtr< GridFunction< TDomain, CPUAlgebra > > spF, SmartPtr< GridFunction< TDomain, CPUAlgebra > > spPsi0, const number beta, const number r, const number eps, const int maxIter, const number dampNewton)
Static Public Attributes
static const int dim = TDomain::dim
Protected Types
enum DiscType { _LEAST_SQUARES_ , _TAYLOR_EXPANSION_ , _PARTIAL_INTEGRATION_ , _TAYLOR_DIRECT_ }
Protected Member Functions
number DLambda (size_t i)
number Lambda (size_t i, SmartPtr< GridFunction< TDomain, CPUAlgebra > > spF)
void write_debug (SmartPtr< GridFunction< TDomain, CPUAlgebra > > spGF, std::string name, int call, int iter)
void write_stencil_matrix_debug (SmartPtr< GridFunction< TDomain, CPUAlgebra > > spGF, std::string name, int call)
Protected Attributes
RevisionCounter m_ApproxSpaceRevision
int m_discType
int m_lastNumIters
int m_quadRuleType
SmartPtr< GridFunctionDebugWriter< TDomain, CPUAlgebra > > m_spDebugWriter
std::vector< std::vector< size_t > > m_vIndex
std::vector< std::vector< number > > m_vStencil
Member Typedef Documentation
TContrainedSide
template<typename TDomain > typedef contrained_dim_traits<dim>::contrained_side_type ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::TContrainedSide
TContrainingSide
template<typename TDomain > typedef contrained_dim_traits<dim>::contraining_side_type ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::TContrainingSide
TElem
template<typename TDomain > typedef grid_dim_traits<dim>::element_type ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::TElem
TGrid
template<typename TDomain > typedef TDomain::grid_type ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::TGrid
TPositionAccessor
template<typename TDomain > typedef TDomain::position_accessor_type ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::TPositionAccessor
TSide
template<typename TDomain > typedef grid_dim_traits<dim>::side_type ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::TSide
Member Enumeration Documentation
DiscType
template<typename TDomain > enum ug::SmallStrainMechanics::DamageFunctionUpdater::DiscType protected
Enumerator
_LEAST_SQUARES_
_TAYLOR_EXPANSION_
_PARTIAL_INTEGRATION_
_TAYLOR_DIRECT_
Constructor & Destructor Documentation
DamageFunctionUpdater()
template<typename TDomain > ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::DamageFunctionUpdater () inline
Member Function Documentation
DLambda()
template<typename TDomain > number ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::DLambda (size_t i) inline protected
References ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_vStencil.
Lambda()
template<typename TDomain > number ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::Lambda (size_t i, SmartPtr< GridFunction< TDomain, CPUAlgebra > > spF) inline protected
References ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_vIndex, and ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_vStencil.
last_num_iterations()
template<typename TDomain > int ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::last_num_iterations () const inline
References ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_lastNumIters.
set_debug()
template<typename TDomain > void ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::set_debug (SmartPtr< GridFunctionDebugWriter< TDomain, CPUAlgebra > > spDebugWriter)
set_disc_type()
template<typename TDomain > void ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::set_disc_type (const std::string & type)
References ug::TrimString(), type(), UG_LOG, and UG_THROW.
set_quad_rule()
template<typename TDomain > void ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::set_quad_rule (int quadRuleType) inline
References ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_quadRuleType.
solve()
template<typename TDomain > bool ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::solve (SmartPtr< GridFunction< TDomain, CPUAlgebra > > spF, SmartPtr< GridFunction< TDomain, CPUAlgebra > > spPsi0, const number beta, const number r, const number eps, const int maxIter, const number dampNewton)
References ug::SmallStrainMechanics::InitLaplacian_LeastSquares(), ug::SmallStrainMechanics::InitLaplacian_PartialIntegration(), ug::SmallStrainMechanics::InitLaplacian_TaylorDirect(), ug::SmallStrainMechanics::InitLaplacian_TaylorExpansion(), PROFILE_BEGIN_GROUP, UG_LOG, and UG_THROW.
write_debug()
template<typename TDomain > void ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::write_debug (SmartPtr< GridFunction< TDomain, CPUAlgebra > > spGF, std::string name, int call, int iter) protected
write_stencil_matrix_debug()
template<typename TDomain > void ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::write_stencil_matrix_debug (SmartPtr< GridFunction< TDomain, CPUAlgebra > > spGF, std::string name, int call) protected
Member Data Documentation
dim
template<typename TDomain > const int ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::dim = TDomain::dim static
m_ApproxSpaceRevision
template<typename TDomain > RevisionCounter ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_ApproxSpaceRevision protected
m_discType
template<typename TDomain > int ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_discType protected
m_lastNumIters
template<typename TDomain > int ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_lastNumIters protected
Referenced by ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::last_num_iterations().
m_quadRuleType
template<typename TDomain > int ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_quadRuleType protected
Referenced by ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::set_quad_rule().
m_spDebugWriter
template<typename TDomain > SmartPtr<GridFunctionDebugWriter<TDomain, CPUAlgebra> > ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_spDebugWriter protected
m_vIndex
template<typename TDomain > std::vector< std::vector<size_t> > ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_vIndex protected
Referenced by ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::Lambda().
m_vStencil
template<typename TDomain > std::vector< std::vector< number > > ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::m_vStencil protected
Referenced by ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::DLambda(), and ug::SmallStrainMechanics::DamageFunctionUpdater< TDomain >::Lambda().
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/SmallStrainMechanics/damage.h
/home/runner/work/docs/docs/ug4/plugins/SmallStrainMechanics/damage_impl.h