Plugins: ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction > Class Template Reference
ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction > Class Template Reference
#include <turbulent_viscosity_fv1.h>
Public Member Functions
void addUiUjTerm (aVertexTensor &aaDefTensor, const number factor, aVertexDimVector aaU)
void addUiUjTerm (aVertexTensor &aaDefTensor, const number factor, SmartPtr< TGridFunction > u)
void assembleDeformationTensor (aVertexTensor &aaDefTensor, aVertexNumber &aaVol, aVertexDimVector aaU)
void assembleDeformationTensor (aVertexTensor &aaDefTensor, aVertexNumber &aaVol, SmartPtr< TGridFunction > u)
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
void elementFilter (aVertexDimVector &aaUHat, aVertexNumber &aaVol, SmartPtr< TGridFunction > u)
template<typename VType >
void elementFilter (PeriodicAttachmentAccessor< Vertex, Attachment< VType > > &aaUHat, aVertexNumber &aaVol, const PeriodicAttachmentAccessor< Vertex, Attachment< VType > > &aaU)
template<int refDim>
void evaluate (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
void fillAttachment (aVertexDimVector &aaU, SmartPtr< TGridFunction > u)
number FNorm (MathMatrix< dim, dim > M)
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
virtual bool requires_grid_fct () const
returns if grid function is needed for evaluation
void scaleTensorByNorm (aVertexTensor &aaTensor)
void scvFilter (aVertexDimVector &aaUHat, aVertexNumber &aaVol, SmartPtr< TGridFunction > u)
template<typename VType >
void scvFilter (PeriodicAttachmentAccessor< Vertex, Attachment< VType > > &aaUHat, aVertexNumber &aaVol, const PeriodicAttachmentAccessor< Vertex, Attachment< VType > > &aaU)
void setTurbulenceZeroBoundaries (const char *subsets)
void transferToLowerLevels (aVertexNumber &aaData, ApproximationSpace< domain_type > &approximationSpace)
Public Member Functions inherited from ug::StdUserData< StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >, TData, dim >
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
Public Member Functions inherited from CplUserData< TData, dim, void >
bool defined (size_t s, size_t ip) const
size_t num_ip (size_t s) const
size_t num_series () const
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
void unregister_storage_callback (DataImport< TData, dim > *obj)
TData & value (size_t s, size_t ip)
const TData & value (size_t s, size_t ip) const
TData * values (size_t s)
const TData * values (size_t s) const
~CplUserData ()
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
virtual void check_setup () const
void clear ()
virtual bool constant () const
int dim_local_ips () const
ICplUserData ()
const MathVector< dim > & ip (size_t s, size_t ip) const
const MathVector< dim > * ips (size_t s) const
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
const MathVector< ldim > * local_ips (size_t s) const
virtual SmartPtr< ICplUserData > needed_data (size_t i)
size_t num_ip (size_t s) const
virtual size_t num_needed_data () const
size_t num_series () const
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
void set_subset (int si)
void set_time_point (const size_t seriesId, const int timePointSpec)
void set_time_point (size_t timePoint)
void set_times (const std::vector< number > &vTime)
int subset () const
number time () const
number time (size_t s) const
size_t time_point ()
size_t time_point (size_t s) const
int time_point_specification (size_t s) const
virtual void update_dof_sizes (const LocalIndices &ind)
virtual bool zero_derivative () const
virtual ~ICplUserData ()
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
const FunctionIndexMapping & map () const
size_t num_fct () const
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
virtual ~UserDataInfo ()
Public Member Functions inherited from UserData< TData, dim, void >
int get_dim () const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, Vertex *vrt) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const =0
std::string type () const
Protected Member Functions
TImpl & getImpl ()
access to implementation
const TImpl & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::StdUserData< StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >, TData, dim >
TImpl & getImpl ()
const TImpl & getImpl () const
Protected Member Functions inherited from CplUserData< TData, dim, void >
void call_storage_callback () const
void check_series (size_t s) const
void check_series_ip (size_t s, size_t ip) const
virtual void local_ip_series_added (const size_t seriesID)
virtual void local_ip_series_to_be_cleared ()
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
virtual void value_storage_changed (const size_t seriesID)
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
void check_s_ip (size_t s, size_t ip) const
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
Protected Attributes
SubsetGroup m_turbZeroSg
SmartPtr< TGridFunction > m_uInfo
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
int m_locPosDim
std::vector< const MathVector< 1 > * > m_pvLocIP1d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
size_t m_timePoint
std::vector< bool > m_vMayChange
std::vector< size_t > m_vNumIP
std::vector< number > m_vTime
std::vector< int > m_vTimePoint
std::vector< const MathVector< dim > * > m_vvGlobPos
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
FunctionIndexMapping m_map
Private Types
typedef TGridFunction::algebra_type algebra_type
algebra type
typedef Attachment< vecDim > AMathVectorDim
typedef Attachment< dimMat > ATensor
typedef PeriodicAttachmentAccessor< Vertex, AMathVectorDim > aVertexDimVector
typedef PeriodicAttachmentAccessor< Vertex, ANumber > aVertexNumber
typedef PeriodicAttachmentAccessor< Vertex, ATensor > aVertexTensor
typedef MathMatrix< dim, dim > dimMat
attachment accessor types
typedef TGridFunction::domain_type domain_type
domain type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef TGridFunction::template dim_traits< dim >::const_iterator ElemIterator
element iterator
typedef domain_type::grid_type grid_type
grid type
typedef domain_type::position_accessor_type position_accessor_type
position accessor type
typedef MathVector< dim > vecDim
typedef TGridFunction::template traits< Vertex >::const_iterator VertexIterator
vertex iterator
Additional Inherited Members
Public Types inherited from CplUserData< TData, dim, void >
typedef ICplUserData< dim > base_type
Public Types inherited from UserData< TData, dim, void >
typedef TData data_type
typedef void return_type
Detailed Description
template<typename TData, int dim, typename TImpl, typename TGridFunction>
class ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >
concept derived from grid_function_user_data.h
Member Typedef Documentation
algebra_type
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef TGridFunction::algebra_type ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::algebra_type private
algebra type
AMathVectorDim
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef Attachment<vecDim> ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::AMathVectorDim private
ATensor
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef Attachment<dimMat> ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::ATensor private
aVertexDimVector
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef PeriodicAttachmentAccessor<Vertex,AMathVectorDim > ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::aVertexDimVector private
aVertexNumber
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef PeriodicAttachmentAccessor<Vertex,ANumber > ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::aVertexNumber private
aVertexTensor
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef PeriodicAttachmentAccessor<Vertex,ATensor > ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::aVertexTensor private
dimMat
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef MathMatrix<dim,dim> ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::dimMat private
attachment accessor types
domain_type
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef TGridFunction::domain_type ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::domain_type private
domain type
elem_type
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::grid_base_object ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::elem_type private
element type
ElemIterator
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::const_iterator ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::ElemIterator private
element iterator
grid_type
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef domain_type::grid_type ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::grid_type private
grid type
position_accessor_type
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef domain_type::position_accessor_type ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::position_accessor_type private
position accessor type
vecDim
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef MathVector<dim> ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::vecDim private
VertexIterator
template<typename TData , int dim, typename TImpl , typename TGridFunction > typedef TGridFunction::template traits<Vertex>::const_iterator ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::VertexIterator private
vertex iterator
Member Function Documentation
addUiUjTerm() [1/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::addUiUjTerm (aVertexTensor & aaDefTensor, const number factor, aVertexDimVector aaU)
References dim, and ug::PeriodicBoundaryManager::is_slave().
addUiUjTerm() [2/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::addUiUjTerm (aVertexTensor & aaDefTensor, const number factor, SmartPtr< TGridFunction > u)
References dim, ug::DoFRef(), and ug::PeriodicBoundaryManager::is_slave().
assembleDeformationTensor() [1/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::assembleDeformationTensor (aVertexTensor & aaDefTensor, aVertexNumber & aaVol, aVertexDimVector aaU)
References ug::DimFV1Geometry< TDim, TWorldDim >::add_boundary_subset(), ug::DimFV1Geometry< TDim, TWorldDim >::bf(), dim, ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::from(), ug::PeriodicBoundaryManager::is_slave(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::normal(), ug::DimFV1Geometry< TDim, TWorldDim >::num_bf(), ug::DimFV1Geometry< TDim, TWorldDim >::num_scvf(), num_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::DimFV1Geometry< TDim, TWorldDim >::scvf(), ug::SetAttachmentValues(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::shape(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::to(), UG_ASSERT, ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
assembleDeformationTensor() [2/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::assembleDeformationTensor (aVertexTensor & aaDefTensor, aVertexNumber & aaVol, SmartPtr< TGridFunction > u)
References ug::DimFV1Geometry< TDim, TWorldDim >::add_boundary_subset(), ug::DimFV1Geometry< TDim, TWorldDim >::bf(), dim, ug::DoFRef(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::from(), SmartPtr< TGridFunction >::get(), ug::PeriodicBoundaryManager::is_slave(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::normal(), ug::DimFV1Geometry< TDim, TWorldDim >::num_bf(), ug::DimFV1Geometry< TDim, TWorldDim >::num_scvf(), num_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::DimFV1Geometry< TDim, TWorldDim >::scvf(), ug::SetAttachmentValues(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::shape(), ug::DimFV1Geometry< TDim, TWorldDim >::SCVF::to(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
compute() [1/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > virtual void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::compute (LocalVector * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) inline virtual
Implements ug::ICplUserData< dim >.
References ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::getImpl(), ug::ICplUserData< dim >::ips(), CplUserData< TData, dim, void >::num_ip(), CplUserData< TData, dim, void >::num_series(), s, ug::ICplUserData< dim >::subset(), ug::ICplUserData< dim >::time(), and CplUserData< TData, dim, void >::values().
compute() [2/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > virtual void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::compute (LocalVectorTimeSeries * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) inline virtual
Implements ug::ICplUserData< dim >.
References ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::getImpl(), ug::ICplUserData< dim >::ips(), CplUserData< TData, dim, void >::num_ip(), CplUserData< TData, dim, void >::num_series(), s, ug::LocalVectorTimeSeries::solution(), ug::ICplUserData< dim >::subset(), ug::ICplUserData< dim >::time(), and CplUserData< TData, dim, void >::values().
continuous()
template<typename TData , int dim, typename TImpl , typename TGridFunction > virtual bool ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::continuous () const inline virtual
returns if provided data is continuous over geometric object boundaries
Implements UserData< TData, dim, void >.
elementFilter() [1/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::elementFilter (aVertexDimVector & aaUHat, aVertexNumber & aaVol, SmartPtr< TGridFunction > u)
References dim, ug::DoFRef(), ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::PeriodicBoundaryManager::is_slave(), ug::LFEID::LAGRANGE, num_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::SetAttachmentValues(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
elementFilter() [2/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > template<typename VType > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::elementFilter (PeriodicAttachmentAccessor< Vertex, Attachment< VType > > & aaUHat, aVertexNumber & aaVol, const PeriodicAttachmentAccessor< Vertex, Attachment< VType > > & aaU)
References dim, ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::LFEID::LAGRANGE, num_subsets(), ug::SetAttachmentValues(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), UG_ASSERT, and ug::DimFV1Geometry< TDim, TWorldDim >::update().
evaluate()
template<typename TData , int dim, typename TImpl , typename TGridFunction > template<int refDim> void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::evaluate (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< refDim, dim > * vJT = NULL) const inline
References ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::getImpl(), and ug::ICplUserData< dim >::time().
fillAttachment()
template<typename TData , int dim, typename TImpl , typename TGridFunction > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::fillAttachment (aVertexDimVector & aaU, SmartPtr< TGridFunction > u)
References dim, ug::DoFRef(), SmartPtr< TGridFunction >::get(), and num_subsets().
FNorm()
template<typename TData , int dim, typename TImpl , typename TGridFunction > number ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::FNorm (MathMatrix< dim, dim > M)
References dim.
getImpl() [1/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > TImpl& ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::getImpl () inline protected
access to implementation
Referenced by ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::compute(), and ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::evaluate().
getImpl() [2/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > const TImpl& ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::getImpl () const inline protected
const access to implementation
operator()() [1/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > virtual void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::operator() (TData & value, const MathVector< dim > & globIP, number time, int si) const inline virtual
Implements ug::StdUserData< StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >, TData, dim >.
References UG_THROW.
operator()() [2/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > virtual void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const inline virtual
Implements ug::StdUserData< StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >, TData, dim >.
References UG_THROW.
requires_grid_fct()
template<typename TData , int dim, typename TImpl , typename TGridFunction > virtual bool ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::requires_grid_fct () const inline virtual
returns if grid function is needed for evaluation
Implements UserData< TData, dim, void >.
scaleTensorByNorm()
template<typename TData , int dim, typename TImpl , typename TGridFunction > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::scaleTensorByNorm (aVertexTensor & aaTensor)
References ug::PeriodicBoundaryManager::is_slave().
scvFilter() [1/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::scvFilter (aVertexDimVector & aaUHat, aVertexNumber & aaVol, SmartPtr< TGridFunction > u)
References dim, ug::DoFRef(), ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::PeriodicBoundaryManager::is_slave(), ug::LFEID::LAGRANGE, ug::DimFV1Geometry< TDim, TWorldDim >::SCV::local_corner(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::num_corners(), num_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::SetAttachmentValues(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
scvFilter() [2/2]
template<typename TData , int dim, typename TImpl , typename TGridFunction > template<typename VType > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::scvFilter (PeriodicAttachmentAccessor< Vertex, Attachment< VType > > & aaUHat, aVertexNumber & aaVol, const PeriodicAttachmentAccessor< Vertex, Attachment< VType > > & aaU)
References dim, ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::PeriodicBoundaryManager::is_slave(), ug::LFEID::LAGRANGE, ug::DimFV1Geometry< TDim, TWorldDim >::SCV::num_corners(), num_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::SetAttachmentValues(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
setTurbulenceZeroBoundaries()
template<typename TData , int dim, typename TImpl , typename TGridFunction > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::setTurbulenceZeroBoundaries (const char * subsets) inline
References ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::m_turbZeroSg, ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::m_uInfo, and UG_CATCH_THROW.
transferToLowerLevels()
template<typename TData , int dim, typename TImpl , typename TGridFunction > void ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::transferToLowerLevels (aVertexNumber & aaData, ApproximationSpace< domain_type > & approximationSpace)
References ug::IApproximationSpace::dof_distribution(), ug::ApproximationSpace< class >::domain(), grid(), ug::GridLevel::LEVEL, ug::DoFDistribution::multi_grid(), ug::IApproximationSpace::num_levels(), num_subsets(), and subset_handler().
Member Data Documentation
m_turbZeroSg
template<typename TData , int dim, typename TImpl , typename TGridFunction > SubsetGroup ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::m_turbZeroSg protected
Referenced by ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::setTurbulenceZeroBoundaries().
m_uInfo
template<typename TData , int dim, typename TImpl , typename TGridFunction > SmartPtr<TGridFunction> ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::m_uInfo protected
Referenced by ug::NavierStokes::StdTurbulentViscosityDataFV1< TData, dim, TImpl, TGridFunction >::setTurbulenceZeroBoundaries().
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/turbulent_viscosity_fv1.h
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/turbulent_viscosity_fv1_impl.h