Plugins: ug::Electromagnetism::NedelecInterpolation< TDomain, 3, 3 > Class Template Reference
ug::Electromagnetism::NedelecInterpolation< TDomain, 3, 3 > Class Template Reference
A specialization of NedelecInterpolation for 3d,.
#include <nedelec_local_ass.h>
Public Types
typedef TDomain::position_type position_type
type of the geometric positions (WDim-vectors)
Static Public Member Functions
static void curl (const TDomain *domain, GridObject *elem, const position_type corners[], const number dofs[], MathVector< 3 > &curl_vec)
computes curl of the function
static number curl_flux (const TDomain *domain, GridObject *elem, const position_type corners[], const number dofs[], const MathVector< 3 > &normal, const position_type pnt, number &flux)
computes flux of the curl through a given plane in an element
static void value (const TDomain *domain, GridObject *elem, const position_type corners[], const number dofs[], const MathVector< 3 > local[], const size_t n_pnt, MathVector< 3 > values[])
computes the values at given points
Static Public Attributes
static const size_t maxNumEdges = (size_t) element_list_traits<typename domain_traits<3>::DimElemList>::maxEdges
max. number of the edges of the full-dimensional elements in the domain
Detailed Description
template<typename TDomain>
class ug::Electromagnetism::NedelecInterpolation< TDomain, 3, 3 >
A specialization of NedelecInterpolation for 3d,.
See also
NedelecInterpolation
Member Typedef Documentation
position_type
template<typename TDomain > typedef TDomain::position_type ug::Electromagnetism::NedelecInterpolation< TDomain, 3, 3 >::position_type
type of the geometric positions (WDim-vectors)
Member Function Documentation
curl()
template<typename TDomain > static void ug::Electromagnetism::NedelecInterpolation< TDomain, 3, 3 >::curl (const TDomain * domain, GridObject * elem, const position_type corners[], const number dofs[], MathVector< 3 > & curl_vec) inline static
computes curl of the function
This function computes the value of the curl operator for the Nedelec representation. Curl is constant over elements. Note that the result is represented as a vector, not as a Whitney-2-form.
Parameters
[in] domain the domain
[in] elem element
[in] corners array of the global corner coordinates
[in] dofs arrays of values of the Nedelec degrees of freedom
[out] curl_vec where to store the computed n_pnt values
References ug::Electromagnetism::NedelecT1_LDisc< TDomain, TElem >::curl(), ug::GridObject::reference_object_id(), ug::ROID_TETRAHEDRON, and UG_THROW.
curl_flux()
template<typename TDomain > number ug::Electromagnetism::NedelecInterpolation< TDomain, 3, 3 >::curl_flux (const TDomain * domain, GridObject * elem, const position_type corners[], const number dofs[], const MathVector< 3 > & normal, const position_type pnt, number & flux) static
computes flux of the curl through a given plane in an element
This function computes the flux of the curl through a given plane inside of a given grid element. The plane is identified by a point on it and the normal. The flux is multiplied by the norm of the given normal vector (i.e. specify the unit normal to get the standard flux). The function returns the area of the intersection if the element is intersected by the plane. Otherwise the function returns exactly 0.0.
Parameters
[in] domain the domain
[in] elem element
[in] corners array of the global corner coordinates
[in] dofs arrays of values of the Nedelec degrees of freedom
[in] normal normal to the plane
[in] pnt point on the plane (identifying the plane)
[out] flux the flux
References ug::Electromagnetism::NedelecT1_LDisc< TDomain, TElem >::curl(), ug::IntersectPlaneWithTetrahedron(), normal, ug::GridObject::reference_object_id(), ug::ROID_TETRAHEDRON, ug::TriangleArea(), UG_THROW, and ug::VecDot().
value()
template<typename TDomain > static void ug::Electromagnetism::NedelecInterpolation< TDomain, 3, 3 >::value (const TDomain * domain, GridObject * elem, const position_type corners[], const number dofs[], const MathVector< 3 > local[], const size_t n_pnt, MathVector< 3 > values[]) inline static
computes the values at given points
Parameters
[in] domain the domain
[in] elem element
[in] corners array of the global corner coordinates
[in] dofs arrays of values of the Nedelec degrees of freedom
[in] local local coordinates of the points where to compute
[in] n_pnt number of the points where to compute
[out] values where to store the computed n_pnt values
References ug::Electromagnetism::NedelecT1_LDisc< TDomain, TElem >::interpolate(), ug::GridObject::reference_object_id(), ug::ROID_TETRAHEDRON, and UG_THROW.
Member Data Documentation
maxNumEdges
template<typename TDomain > const size_t ug::Electromagnetism::NedelecInterpolation< TDomain, 3, 3 >::maxNumEdges = (size_t) element_list_traits<typename domain_traits<3>::DimElemList>::maxEdges static
max. number of the edges of the full-dimensional elements in the domain
The documentation for this class was generated from the following files:
/var/lib/jenkins/workspace/ug-docs/plugins/Electromagnetism/nedelec_local_ass.h
/var/lib/jenkins/workspace/ug-docs/plugins/Electromagnetism/nedelec_local_ass_impl.h