Plugins: ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction > Class Template Reference
ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction > Class Template Reference
#include <turbulent_viscosity_fv1.h>
Public Member Functions
template<int refDim>
void evaluate (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
FV1SmagorinskyTurbViscData (SmartPtr< ApproximationSpace< domain_type > > approxSpace, SmartPtr< TGridFunction > spGridFct, number c=0.05)
constructor
void set_model_parameter (number c)
void update ()
virtual ~FV1SmagorinskyTurbViscData ()
void set_kinematic_viscosity (SmartPtr< CplUserData< number, dim > > user)
void set_kinematic_viscosity (number val)
Public Member Functions inherited from ug::NavierStokes::StdTurbulentViscosityDataFV1< number, TGridFunction::dim, FV1SmagorinskyTurbViscData< TGridFunction >, TGridFunction >
void addUiUjTerm (aVertexTensor &aaDefTensor, const number factor, aVertexDimVector aaU)
void addUiUjTerm (aVertexTensor &aaDefTensor, const number factor, SmartPtr< TGridFunction > u)
void assembleDeformationTensor (aVertexTensor &aaDefTensor, aVertexNumber &aaVol, aVertexDimVector aaU)
void assembleDeformationTensor (aVertexTensor &aaDefTensor, aVertexNumber &aaVol, SmartPtr< TGridFunction > u)
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
void elementFilter (aVertexDimVector &aaUHat, aVertexNumber &aaVol, SmartPtr< TGridFunction > u)
void elementFilter (PeriodicAttachmentAccessor< Vertex, Attachment< VType > > &aaUHat, aVertexNumber &aaVol, const PeriodicAttachmentAccessor< Vertex, Attachment< VType > > &aaU)
void evaluate (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
void fillAttachment (aVertexDimVector &aaU, SmartPtr< TGridFunction > u)
number FNorm (MathMatrix< dim, dim > M)
virtual void operator() (number &value, const MathVector< dim > &globIP, number time, int si) const
virtual void operator() (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
virtual bool requires_grid_fct () const
returns if grid function is needed for evaluation
void scaleTensorByNorm (aVertexTensor &aaTensor)
void scvFilter (aVertexDimVector &aaUHat, aVertexNumber &aaVol, SmartPtr< TGridFunction > u)
void scvFilter (PeriodicAttachmentAccessor< Vertex, Attachment< VType > > &aaUHat, aVertexNumber &aaVol, const PeriodicAttachmentAccessor< Vertex, Attachment< VType > > &aaU)
void setTurbulenceZeroBoundaries (const char *subsets)
void transferToLowerLevels (aVertexNumber &aaData, ApproximationSpace< domain_type > &approximationSpace)
Public Member Functions inherited from ug::StdUserData< class, class, dim, class, class >
virtual TRet operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const=0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const=0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const
Public Member Functions inherited from CplUserData< TData, dim, void >
bool defined (size_t s, size_t ip) const
size_t num_ip (size_t s) const
size_t num_series () const
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
void unregister_storage_callback (DataImport< TData, dim > *obj)
TData & value (size_t s, size_t ip)
const TData & value (size_t s, size_t ip) const
TData * values (size_t s)
const TData * values (size_t s) const
~CplUserData ()
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
virtual void check_setup () const
void clear ()
virtual bool constant () const
int dim_local_ips () const
ICplUserData ()
const MathVector< dim > & ip (size_t s, size_t ip) const
const MathVector< dim > * ips (size_t s) const
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
const MathVector< ldim > * local_ips (size_t s) const
virtual SmartPtr< ICplUserData > needed_data (size_t i)
size_t num_ip (size_t s) const
virtual size_t num_needed_data () const
size_t num_series () const
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
void set_subset (int si)
void set_time_point (const size_t seriesId, const int timePointSpec)
void set_time_point (size_t timePoint)
void set_times (const std::vector< number > &vTime)
int subset () const
number time () const
number time (size_t s) const
size_t time_point ()
size_t time_point (size_t s) const
int time_point_specification (size_t s) const
virtual void update_dof_sizes (const LocalIndices &ind)
virtual bool zero_derivative () const
virtual ~ICplUserData ()
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
const FunctionIndexMapping & map () const
size_t num_fct () const
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
virtual ~UserDataInfo ()
Public Member Functions inherited from UserData< TData, dim, void >
int get_dim () const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, Vertex *vrt) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const =0
std::string type () const
Public Member Functions inherited from ug::INewtonUpdate
virtual ~INewtonUpdate ()
Static Public Attributes
static const size_t max_number_of_ips = 20
Private Types
typedef TGridFunction::algebra_type algebra_type
algebra type
typedef Attachment< dimMat > ATensor
typedef PeriodicAttachmentAccessor< Vertex, ANumber > aVertexNumber
typedef PeriodicAttachmentAccessor< Vertex, ATensor > aVertexTensor
typedef MathMatrix< dim, dim > dimMat
attachment accessor types
typedef TGridFunction::domain_type domain_type
domain type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef TGridFunction::template dim_traits< dim >::const_iterator ElemIterator
element iterator
typedef domain_type::grid_type grid_type
grid type
typedef domain_type::position_accessor_type position_accessor_type
position accessor type
typedef TGridFunction::template traits< Vertex >::const_iterator VertexIterator
vertex iterator
Private Attributes
aVertexTensor m_acDeformation
aVertexNumber m_acTurbulentViscosity
aVertexNumber m_acVolume
ATensor m_aDeformation
ANumber m_aTurbulentViscosity
ANumber m_aVolume
number m_c
grid_type * m_grid
SmartPtr< CplUserData< number, dim > > m_imKinViscosity
Data import for kinematic viscosity.
PeriodicBoundaryManager * m_pbm
SmartPtr< ApproximationSpace< domain_type > > m_spApproxSpace
SmartPtr< TGridFunction > m_u
Static Private Attributes
static const int dim = domain_type::dim
world dimension
Additional Inherited Members
Public Types inherited from CplUserData< TData, dim, void >
typedef ICplUserData< dim > base_type
Public Types inherited from UserData< TData, dim, void >
typedef TData data_type
typedef void return_type
Protected Member Functions inherited from ug::NavierStokes::StdTurbulentViscosityDataFV1< number, TGridFunction::dim, FV1SmagorinskyTurbViscData< TGridFunction >, TGridFunction >
FV1SmagorinskyTurbViscData< TGridFunction > & getImpl ()
access to implementation
const FV1SmagorinskyTurbViscData< TGridFunction > & getImpl () const
const access to implementation
Protected Member Functions inherited from ug::StdUserData< class, class, dim, class, class >
TImpl & getImpl ()
const TImpl & getImpl () const
Protected Member Functions inherited from CplUserData< TData, dim, void >
void call_storage_callback () const
void check_series (size_t s) const
void check_series_ip (size_t s, size_t ip) const
virtual void local_ip_series_added (const size_t seriesID)
virtual void local_ip_series_to_be_cleared ()
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
virtual void value_storage_changed (const size_t seriesID)
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
void check_s_ip (size_t s, size_t ip) const
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
Protected Attributes inherited from ug::NavierStokes::StdTurbulentViscosityDataFV1< number, TGridFunction::dim, FV1SmagorinskyTurbViscData< TGridFunction >, TGridFunction >
SubsetGroup m_turbZeroSg
SmartPtr< TGridFunction > m_uInfo
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
int m_locPosDim
std::vector< const MathVector< 1 > * > m_pvLocIP1d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
size_t m_timePoint
std::vector< bool > m_vMayChange
std::vector< size_t > m_vNumIP
std::vector< number > m_vTime
std::vector< int > m_vTimePoint
std::vector< const MathVector< dim > * > m_vvGlobPos
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
FunctionIndexMapping m_map
Member Typedef Documentation
algebra_type
template<typename TGridFunction > typedef TGridFunction::algebra_type ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::algebra_type private
algebra type
ATensor
template<typename TGridFunction > typedef Attachment<dimMat> ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::ATensor private
aVertexNumber
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<Vertex,ANumber > ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::aVertexNumber private
aVertexTensor
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<Vertex,ATensor > ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::aVertexTensor private
dimMat
template<typename TGridFunction > typedef MathMatrix<dim,dim> ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::dimMat private
attachment accessor types
domain_type
template<typename TGridFunction > typedef TGridFunction::domain_type ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::domain_type private
domain type
elem_type
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::grid_base_object ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::elem_type private
element type
ElemIterator
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::const_iterator ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::ElemIterator private
element iterator
grid_type
template<typename TGridFunction > typedef domain_type::grid_type ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::grid_type private
grid type
position_accessor_type
template<typename TGridFunction > typedef domain_type::position_accessor_type ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::position_accessor_type private
position accessor type
VertexIterator
template<typename TGridFunction > typedef TGridFunction::template traits<Vertex>::const_iterator ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::VertexIterator private
vertex iterator
Constructor & Destructor Documentation
FV1SmagorinskyTurbViscData()
template<typename TGridFunction > ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::FV1SmagorinskyTurbViscData (SmartPtr< ApproximationSpace< domain_type > > approxSpace, SmartPtr< TGridFunction > spGridFct, number c = 0.05) inline
constructor
References ug::PeriodicAttachmentAccessor< class, class >::access(), SmartPtr< TGridFunction >::get(), grid(), ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_acDeformation, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_acTurbulentViscosity, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_acVolume, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_aDeformation, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_aTurbulentViscosity, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_aVolume, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_c, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_grid, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_pbm, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_u, and ug::NavierStokes::StdTurbulentViscosityDataFV1< number, TGridFunction::dim, FV1SmagorinskyTurbViscData< TGridFunction >, TGridFunction >::m_uInfo.
~FV1SmagorinskyTurbViscData()
template<typename TGridFunction > virtual ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::~FV1SmagorinskyTurbViscData () inline virtual
References SmartPtr< TGridFunction >::get(), grid(), ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_aDeformation, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_aTurbulentViscosity, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_aVolume, and ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_u.
Member Function Documentation
evaluate()
template<typename TGridFunction > template<int refDim> void ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::evaluate (number vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< refDim, dim > * vJT = NULL) const inline
References ug::ICplUserData< dim >::ip(), ug::LFEID::LAGRANGE, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_acTurbulentViscosity, ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::max_number_of_ips, ug::GridObject::reference_object_id(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), ug::ICplUserData< dim >::time(), UG_ASSERT, and UG_CATCH_THROW.
set_kinematic_viscosity() [1/2]
template<typename TGridFunction > void ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::set_kinematic_viscosity (number val) inline
This method sets the kinematic viscosity value. Kinematic viscosity is added to turbulent viscosity in evaluation routine.
Parameters
[in] data kinematic Viscosity
References make_sp(), and ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::set_kinematic_viscosity().
set_kinematic_viscosity() [2/2]
template<typename TGridFunction > void ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::set_kinematic_viscosity (SmartPtr< CplUserData< number, dim > > user) inline
This method sets the kinematic viscosity value. Kinematic viscosity is added to turbulent viscosity in evaluation routine.
Parameters
[in] data kinematic Viscosity
References ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_imKinViscosity.
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::set_kinematic_viscosity().
set_model_parameter()
template<typename TGridFunction > void ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::set_model_parameter (number c) inline
References ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_c.
update()
template<typename TGridFunction > void ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::update virtual
Implements ug::INewtonUpdate.
References dim, num_subsets(), and ug::SetAttachmentValues().
Member Data Documentation
dim
template<typename TGridFunction > const int ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::dim = domain_type::dim static private
world dimension
m_acDeformation
template<typename TGridFunction > aVertexTensor ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_acDeformation private
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::FV1SmagorinskyTurbViscData().
m_acTurbulentViscosity
template<typename TGridFunction > aVertexNumber ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_acTurbulentViscosity private
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::evaluate(), and ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::FV1SmagorinskyTurbViscData().
m_acVolume
template<typename TGridFunction > aVertexNumber ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_acVolume private
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::FV1SmagorinskyTurbViscData().
m_aDeformation
template<typename TGridFunction > ATensor ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_aDeformation private
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::FV1SmagorinskyTurbViscData(), and ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::~FV1SmagorinskyTurbViscData().
m_aTurbulentViscosity
template<typename TGridFunction > ANumber ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_aTurbulentViscosity private
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::FV1SmagorinskyTurbViscData(), and ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::~FV1SmagorinskyTurbViscData().
m_aVolume
template<typename TGridFunction > ANumber ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_aVolume private
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::FV1SmagorinskyTurbViscData(), and ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::~FV1SmagorinskyTurbViscData().
m_c
template<typename TGridFunction > number ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_c private
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::FV1SmagorinskyTurbViscData(), and ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::set_model_parameter().
m_grid
template<typename TGridFunction > grid_type* ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_grid private
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::FV1SmagorinskyTurbViscData().
m_imKinViscosity
template<typename TGridFunction > SmartPtr<CplUserData<number,dim> > ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_imKinViscosity private
Data import for kinematic viscosity.
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::set_kinematic_viscosity().
m_pbm
template<typename TGridFunction > PeriodicBoundaryManager* ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_pbm private
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::FV1SmagorinskyTurbViscData().
m_spApproxSpace
template<typename TGridFunction > SmartPtr<ApproximationSpace<domain_type> > ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_spApproxSpace private
m_u
template<typename TGridFunction > SmartPtr<TGridFunction> ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::m_u private
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::FV1SmagorinskyTurbViscData(), and ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::~FV1SmagorinskyTurbViscData().
max_number_of_ips
template<typename TGridFunction > const size_t ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::max_number_of_ips = 20 static
Referenced by ug::NavierStokes::FV1SmagorinskyTurbViscData< TGridFunction >::evaluate().
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/turbulent_viscosity_fv1.h
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fv1/turbulent_viscosity_fv1_impl.h