Plugins: ug::Richards::VanGenuchtenModel Class Reference
ug::Richards::VanGenuchtenModel Class Reference
Implements a van Genuchten-Mualem model.
#include <van_genuchten.h>
Public Types
typedef IRichardsModel< VanGenuchtenModel > base_type
typedef VanGenuchtenParameters parameter_type
typedef IParameterizedModel< VanGenuchtenParameters > parameterized_model_type
Public Member Functions
VanGenuchtenModel (const parameter_type &p)
Public Member Functions inherited from ug::Richards::IRichardsModel< VanGenuchtenModel >
double Conductivity (double H)
Conductivity K = Ks*kr.
double dConductivity_dH (double H)
double dSaturation_dH (double H) const
void get_conductivities (const double *H, double *K, double *dKdH, size_t n) const
void get_conductivity (double H, double &K, double &dKdH) const
Calls Conductivity_.
void get_relative_permeabilities (const double *H, double *K, double *dKdH, size_t n) const
void get_relative_permeability (double H, double &Kr, double &dKrdH) const
Calls RelativePermeability_.
void get_saturation (double H, double &S, double &dSdH) const
Calls Saturation_.
void get_saturations (const double *H, double *S, double *dSdH, size_t n) const
double Saturation (double H) const
Public Member Functions inherited from ug::Richards::IParameterizedModel< VanGenuchtenParameters >
std::string config_string () const
const VanGenuchtenParameters & get_parameters () const
IParameterizedModel ()
IParameterizedModel (const VanGenuchtenParameters &p)
void set_parameters (const VanGenuchtenParameters &p)
Public Attributes
friend base_type
friend parameterized_model_type
Public Attributes inherited from ug::Richards::IParameterizedModel< VanGenuchtenParameters >
VanGenuchtenParameters m_param
Protected Member Functions
dual Conductivity_ (dual psi_) const
dual EffSaturation_ (dual psi_) const
Effective saturation: $0 \le \hat S \le 1$.
dual RelativePermeability_ (dual psi_) const
Relative permeability: $0 \le k_r \le 1$.
dual Saturation_ (dual psi_) const
Rescaled Saturation: $$ S:=\theta_r+ (\theta_s - \theta_r) * \hat S$$.
Protected Member Functions inherited from ug::Richards::IRichardsModel< VanGenuchtenModel >
void get_value_and_deriv (TFunc F, double H, double &f, double &df) const
VanGenuchtenModel * me ()
const VanGenuchtenModel * me () const
Detailed Description
Implements a van Genuchten-Mualem model.
Member Typedef Documentation
base_type
typedef IRichardsModel<VanGenuchtenModel> ug::Richards::VanGenuchtenModel::base_type
parameter_type
typedef VanGenuchtenParameters ug::Richards::VanGenuchtenModel::parameter_type
parameterized_model_type
typedef IParameterizedModel<VanGenuchtenParameters> ug::Richards::VanGenuchtenModel::parameterized_model_type
Constructor & Destructor Documentation
VanGenuchtenModel()
ug::Richards::VanGenuchtenModel::VanGenuchtenModel (const parameter_type & p) inline
Member Function Documentation
Conductivity_()
dual ug::Richards::VanGenuchtenModel::Conductivity_ (dual psi_) const inline protected
References ug::Richards::IParameterizedModel< VanGenuchtenParameters >::m_param, p, and RelativePermeability_().
EffSaturation_()
dual ug::Richards::VanGenuchtenModel::EffSaturation_ (dual psi_) const inline protected
Effective saturation: $0 \le \hat S \le 1$.
References ug::Richards::VanGenuchtenFunctions::ComputeEffectiveSaturation(), ug::Richards::IParameterizedModel< VanGenuchtenParameters >::m_param, and p.
Referenced by RelativePermeability_(), and Saturation_().
RelativePermeability_()
dual ug::Richards::VanGenuchtenModel::RelativePermeability_ (dual psi_) const inline protected
Relative permeability: $0 \le k_r \le 1$.
References EffSaturation_(), ug::Richards::IParameterizedModel< VanGenuchtenParameters >::m_param, p, and ug::Richards::UGCheckValues().
Referenced by Conductivity_().
Saturation_()
dual ug::Richards::VanGenuchtenModel::Saturation_ (dual psi_) const inline protected
Rescaled Saturation: $$ S:=\theta_r+ (\theta_s - \theta_r) * \hat S$$.
References EffSaturation_(), ug::Richards::IParameterizedModel< VanGenuchtenParameters >::m_param, p, and ug::Richards::UGCheckValues().
Member Data Documentation
base_type
friend ug::Richards::VanGenuchtenModel::base_type
parameterized_model_type
friend ug::Richards::VanGenuchtenModel::parameterized_model_type
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Richards/van_genuchten.h