Plugins: ug::promesh::ElementIterator< TElem > Class Template Reference
ug::promesh::ElementIterator< TElem > Class Template Reference
#include <mesh.h>
Public Types
typedef Grid::traits< TElem >::iterator iterator_t
Public Member Functions
void advance ()
void assign (ElementIterator &i)
SmartPtr< ElementIterator< TElem > > clone ()
ElementIterator (iterator_t i)
bool equal (ElementIterator &i)
bool unequal (ElementIterator &i)
TElem * value ()
Private Attributes
iterator_t m_iter
Member Typedef Documentation
iterator_t
template<class TElem > typedef Grid::traits<TElem>::iterator ug::promesh::ElementIterator< TElem >::iterator_t
Constructor & Destructor Documentation
ElementIterator()
template<class TElem > ug::promesh::ElementIterator< TElem >::ElementIterator (iterator_t i) inline
Referenced by ug::promesh::ElementIterator< TElem >::clone().
Member Function Documentation
advance()
template<class TElem > void ug::promesh::ElementIterator< TElem >::advance () inline
References ug::promesh::ElementIterator< TElem >::m_iter.
assign()
template<class TElem > void ug::promesh::ElementIterator< TElem >::assign (ElementIterator< TElem > & i) inline
References ug::promesh::ElementIterator< TElem >::m_iter.
clone()
template<class TElem > SmartPtr<ElementIterator<TElem> > ug::promesh::ElementIterator< TElem >::clone () inline
References ug::promesh::ElementIterator< TElem >::ElementIterator(), ug::promesh::ElementIterator< TElem >::m_iter, and make_sp().
equal()
template<class TElem > bool ug::promesh::ElementIterator< TElem >::equal (ElementIterator< TElem > & i) inline
References ug::promesh::ElementIterator< TElem >::m_iter.
unequal()
template<class TElem > bool ug::promesh::ElementIterator< TElem >::unequal (ElementIterator< TElem > & i) inline
References ug::promesh::ElementIterator< TElem >::m_iter.
value()
template<class TElem > TElem* ug::promesh::ElementIterator< TElem >::value () inline
References ug::promesh::ElementIterator< TElem >::m_iter.
Member Data Documentation
m_iter
template<class TElem > iterator_t ug::promesh::ElementIterator< TElem >::m_iter private
Referenced by ug::promesh::ElementIterator< TElem >::advance(), ug::promesh::ElementIterator< TElem >::assign(), ug::promesh::ElementIterator< TElem >::clone(), ug::promesh::ElementIterator< TElem >::equal(), ug::promesh::ElementIterator< TElem >::unequal(), and ug::promesh::ElementIterator< TElem >::value().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/ProMesh/mesh.h