Plugins: ug::SmallStrainMechanics::IMaterialLaw< TDomain > Class Template Reference
ug::SmallStrainMechanics::IMaterialLaw< TDomain > Class Template Reference abstract
#include <mat_law_interface.h>
Public Types
typedef domain_traits< TDomain::dim >::grid_base_object TBaseElem
base element type of associated domain
Public Member Functions
virtual void attach_internal_vars (typename TDomain::grid_type &grid)
virtual void clear_attachments (typename TDomain::grid_type &grid)
template<typename TFEGeom >
void DisplacementGradient (MathMatrix< dim, dim > &GradU, const size_t ip, const TFEGeom &geo, const LocalVector &u)
virtual SmartPtr< MathTensor4< dim, dim, dim, dim > > elasticityTensor ()
virtual SmartPtr< MathTensor4< dim, dim, dim, dim > > elasticityTensor (const size_t ip, const MathMatrix< dim, dim > &GradU)=0
virtual SmartPtr< MathTensor4< dim, dim, dim, dim > > elasticityTensor (const size_t ip, const MathVector< dim > &x, const MathMatrix< dim, dim > &GradU)
bool elastTensIsConstant ()
virtual number hardening_parameter (const size_t ip)
IMaterialLaw ()
constructor
virtual SmartPtr< MathMatrix< dim, dim > > inelastic_strain_tensor (const size_t ip)
virtual void init ()=0
virtual void init_internal_vars (TBaseElem *elem, const size_t numIP)
virtual void internal_vars (TBaseElem *elem)
bool is_initialized ()
virtual bool needs_to_add_jac_m ()
virtual number plastic_multiplier (const size_t ip, const MathMatrix< dim, dim > &GradU)
virtual void stressTensor (MathMatrix< dim, dim > &stressTens, const size_t ip, const MathMatrix< dim, dim > &GradU)=0
virtual void stressTensor (MathMatrix< dim, dim > &stressTens, const size_t ip, const MathVector< dim > &x, const MathMatrix< dim, dim > &GradU)
virtual void update_internal_vars (const size_t ip, const MathMatrix< dim, dim > &GradU)
virtual void write_data_to_console (const number t)
virtual ~IMaterialLaw ()
destructor
Public Attributes
std::string m_materialConfiguration
Static Public Attributes
static const int dim = TDomain::dim
World dimension.
Protected Attributes
bool m_bConstElastTens
flag indicating, if elasticity tensor is constant
bool m_bInit
flag indicating, if material law has been initialized
Member Typedef Documentation
TBaseElem
template<typename TDomain > typedef domain_traits<TDomain::dim>::grid_base_object ug::SmallStrainMechanics::IMaterialLaw< TDomain >::TBaseElem
base element type of associated domain
Constructor & Destructor Documentation
IMaterialLaw()
template<typename TDomain > ug::SmallStrainMechanics::IMaterialLaw< TDomain >::IMaterialLaw () inline
constructor
~IMaterialLaw()
template<typename TDomain > virtual ug::SmallStrainMechanics::IMaterialLaw< TDomain >::~IMaterialLaw () inline virtual
destructor
Member Function Documentation
attach_internal_vars()
template<typename TDomain > virtual void ug::SmallStrainMechanics::IMaterialLaw< TDomain >::attach_internal_vars (typename TDomain::grid_type & grid) inline virtual
Reimplemented in ug::SmallStrainMechanics::PrandtlReuss< TDomain >.
clear_attachments()
template<typename TDomain > virtual void ug::SmallStrainMechanics::IMaterialLaw< TDomain >::clear_attachments (typename TDomain::grid_type & grid) inline virtual
Reimplemented in ug::SmallStrainMechanics::PrandtlReuss< TDomain >.
DisplacementGradient()
template<typename TDomain > template<typename TFEGeom > void ug::SmallStrainMechanics::IMaterialLaw< TDomain >::DisplacementGradient (MathMatrix< dim, dim > & GradU, const size_t ip, const TFEGeom & geo, const LocalVector & u)
References dim.
elasticityTensor() [1/3]
template<typename TDomain > virtual SmartPtr<MathTensor4<dim,dim,dim,dim> > ug::SmallStrainMechanics::IMaterialLaw< TDomain >::elasticityTensor () inline virtual
Reimplemented in ug::SmallStrainMechanics::SkinMaterialLaw< TDomain >, and ug::SmallStrainMechanics::HookeLaw< TDomain >.
References UG_THROW.
Referenced by ug::SmallStrainMechanics::IMaterialLaw< TDomain >::elasticityTensor().
elasticityTensor() [2/3]
template<typename TDomain > virtual SmartPtr<MathTensor4<dim,dim,dim,dim> > ug::SmallStrainMechanics::IMaterialLaw< TDomain >::elasticityTensor (const size_t ip, const MathMatrix< dim, dim > & GradU) pure virtual
Implemented in ug::SmallStrainMechanics::SkinMaterialLaw< TDomain >, ug::SmallStrainMechanics::PrandtlReuss< TDomain >, and ug::SmallStrainMechanics::HookeLaw< TDomain >.
elasticityTensor() [3/3]
template<typename TDomain > virtual SmartPtr<MathTensor4<dim,dim,dim,dim> > ug::SmallStrainMechanics::IMaterialLaw< TDomain >::elasticityTensor (const size_t ip, const MathVector< dim > & x, const MathMatrix< dim, dim > & GradU) inline virtual
Reimplemented in ug::SmallStrainMechanics::SkinMaterialLaw< TDomain >.
References ug::SmallStrainMechanics::IMaterialLaw< TDomain >::elasticityTensor().
elastTensIsConstant()
template<typename TDomain > bool ug::SmallStrainMechanics::IMaterialLaw< TDomain >::elastTensIsConstant () inline
References ug::SmallStrainMechanics::IMaterialLaw< TDomain >::m_bConstElastTens.
hardening_parameter()
template<typename TDomain > virtual number ug::SmallStrainMechanics::IMaterialLaw< TDomain >::hardening_parameter (const size_t ip) inline virtual
Reimplemented in ug::SmallStrainMechanics::PrandtlReuss< TDomain >.
inelastic_strain_tensor()
template<typename TDomain > virtual SmartPtr<MathMatrix<dim, dim> > ug::SmallStrainMechanics::IMaterialLaw< TDomain >::inelastic_strain_tensor (const size_t ip) inline virtual
Reimplemented in ug::SmallStrainMechanics::PrandtlReuss< TDomain >.
init()
template<typename TDomain > virtual void ug::SmallStrainMechanics::IMaterialLaw< TDomain >::init () pure virtual
Implemented in ug::SmallStrainMechanics::SkinMaterialLaw< TDomain >, ug::SmallStrainMechanics::PrandtlReuss< TDomain >, and ug::SmallStrainMechanics::HookeLaw< TDomain >.
init_internal_vars()
template<typename TDomain > virtual void ug::SmallStrainMechanics::IMaterialLaw< TDomain >::init_internal_vars (TBaseElem * elem, const size_t numIP) inline virtual
Reimplemented in ug::SmallStrainMechanics::IScaledHookeLaw< TDomain >, and ug::SmallStrainMechanics::PrandtlReuss< TDomain >.
internal_vars()
template<typename TDomain > virtual void ug::SmallStrainMechanics::IMaterialLaw< TDomain >::internal_vars (TBaseElem * elem) inline virtual
Reimplemented in ug::SmallStrainMechanics::IScaledHookeLaw< TDomain >, and ug::SmallStrainMechanics::PrandtlReuss< TDomain >.
is_initialized()
template<typename TDomain > bool ug::SmallStrainMechanics::IMaterialLaw< TDomain >::is_initialized () inline
References ug::SmallStrainMechanics::IMaterialLaw< TDomain >::m_bInit.
needs_to_add_jac_m()
template<typename TDomain > virtual bool ug::SmallStrainMechanics::IMaterialLaw< TDomain >::needs_to_add_jac_m () inline virtual
Reimplemented in ug::SmallStrainMechanics::PrandtlReuss< TDomain >.
plastic_multiplier()
template<typename TDomain > virtual number ug::SmallStrainMechanics::IMaterialLaw< TDomain >::plastic_multiplier (const size_t ip, const MathMatrix< dim, dim > & GradU) inline virtual
Reimplemented in ug::SmallStrainMechanics::PrandtlReuss< TDomain >.
stressTensor() [1/2]
template<typename TDomain > virtual void ug::SmallStrainMechanics::IMaterialLaw< TDomain >::stressTensor (MathMatrix< dim, dim > & stressTens, const size_t ip, const MathMatrix< dim, dim > & GradU) pure virtual
Implemented in ug::SmallStrainMechanics::SkinMaterialLaw< TDomain >, ug::SmallStrainMechanics::PrandtlReuss< TDomain >, and ug::SmallStrainMechanics::HookeLaw< TDomain >.
Referenced by ug::SmallStrainMechanics::IMaterialLaw< TDomain >::stressTensor().
stressTensor() [2/2]
template<typename TDomain > virtual void ug::SmallStrainMechanics::IMaterialLaw< TDomain >::stressTensor (MathMatrix< dim, dim > & stressTens, const size_t ip, const MathVector< dim > & x, const MathMatrix< dim, dim > & GradU) inline virtual
Reimplemented in ug::SmallStrainMechanics::SkinMaterialLaw< TDomain >.
References ug::SmallStrainMechanics::IMaterialLaw< TDomain >::stressTensor().
update_internal_vars()
template<typename TDomain > virtual void ug::SmallStrainMechanics::IMaterialLaw< TDomain >::update_internal_vars (const size_t ip, const MathMatrix< dim, dim > & GradU) inline virtual
Reimplemented in ug::SmallStrainMechanics::PrandtlReuss< TDomain >.
write_data_to_console()
template<typename TDomain > virtual void ug::SmallStrainMechanics::IMaterialLaw< TDomain >::write_data_to_console (const number t) inline virtual
Reimplemented in ug::SmallStrainMechanics::PrandtlReuss< TDomain >.
Member Data Documentation
dim
template<typename TDomain > const int ug::SmallStrainMechanics::IMaterialLaw< TDomain >::dim = TDomain::dim static
World dimension.
m_bConstElastTens
template<typename TDomain > bool ug::SmallStrainMechanics::IMaterialLaw< TDomain >::m_bConstElastTens protected
flag indicating, if elasticity tensor is constant
Referenced by ug::SmallStrainMechanics::IMaterialLaw< TDomain >::elastTensIsConstant(), ug::SmallStrainMechanics::HookeLaw< TDomain >::HookeLaw(), ug::SmallStrainMechanics::PrandtlReuss< TDomain >::PrandtlReuss(), and ug::SmallStrainMechanics::SkinMaterialLaw< TDomain >::SkinMaterialLaw().
m_bInit
template<typename TDomain > bool ug::SmallStrainMechanics::IMaterialLaw< TDomain >::m_bInit protected
flag indicating, if material law has been initialized
Referenced by ug::SmallStrainMechanics::IScaledHookeLaw< TDomain >::init_internal_vars(), and ug::SmallStrainMechanics::IMaterialLaw< TDomain >::is_initialized().
m_materialConfiguration
template<typename TDomain > std::string ug::SmallStrainMechanics::IMaterialLaw< TDomain >::m_materialConfiguration
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/SmallStrainMechanics/material_laws/mat_law_interface.h
/home/runner/work/docs/docs/ug4/plugins/SmallStrainMechanics/material_laws/mat_law_interface_impl.h