Plugins: ug::Richards::ExponentialModel Class Reference
ug::Richards::ExponentialModel Class Reference
Implement a simple exponential model.
#include <van_genuchten.h>
Public Types
typedef IRichardsModel< ExponentialModel > base_type
typedef ExponentialModelParameters parameter_type
typedef IParameterizedModel< ExponentialModelParameters > parameterized_model_type
Public Member Functions
ExponentialModel (const parameter_type &p)
Public Member Functions inherited from ug::Richards::IRichardsModel< ExponentialModel >
double Conductivity (double H)
Conductivity K = Ks*kr.
double dConductivity_dH (double H)
double dSaturation_dH (double H) const
void get_conductivities (const double *H, double *K, double *dKdH, size_t n) const
void get_conductivity (double H, double &K, double &dKdH) const
Calls Conductivity_.
void get_relative_permeabilities (const double *H, double *K, double *dKdH, size_t n) const
void get_relative_permeability (double H, double &Kr, double &dKrdH) const
Calls RelativePermeability_.
void get_saturation (double H, double &S, double &dSdH) const
Calls Saturation_.
void get_saturations (const double *H, double *S, double *dSdH, size_t n) const
double Saturation (double H) const
Public Member Functions inherited from ug::Richards::IParameterizedModel< ExponentialModelParameters >
std::string config_string () const
const ExponentialModelParameters & get_parameters () const
IParameterizedModel ()
IParameterizedModel (const ExponentialModelParameters &p)
void set_parameters (const ExponentialModelParameters &p)
Public Attributes
friend base_type
friend parameterized_model_type
Public Attributes inherited from ug::Richards::IParameterizedModel< ExponentialModelParameters >
ExponentialModelParameters m_param
Protected Member Functions
dual Conductivity_ (dual pc) const
dual EffSaturation_ (dual pc) const
Effective saturation: $0 \le \hat S \le 1$.
dual RelativePermeability_ (dual pc) const
Relative permeability: $0 \le k_r \le 1$.
dual Saturation_ (dual pc) const
Rescaled Saturation: $$ S:=\theta_r+ (\theta_s - \theta_r) * \hat S$$.
Protected Member Functions inherited from ug::Richards::IRichardsModel< ExponentialModel >
void get_value_and_deriv (TFunc F, double H, double &f, double &df) const
ExponentialModel * me ()
const ExponentialModel * me () const
Detailed Description
Implement a simple exponential model.
Member Typedef Documentation
base_type
typedef IRichardsModel<ExponentialModel> ug::Richards::ExponentialModel::base_type
parameter_type
typedef ExponentialModelParameters ug::Richards::ExponentialModel::parameter_type
parameterized_model_type
typedef IParameterizedModel<ExponentialModelParameters> ug::Richards::ExponentialModel::parameterized_model_type
Constructor & Destructor Documentation
ExponentialModel()
ug::Richards::ExponentialModel::ExponentialModel (const parameter_type & p) inline
Member Function Documentation
Conductivity_()
dual ug::Richards::ExponentialModel::Conductivity_ (dual pc) const inline protected
References ug::Richards::IParameterizedModel< ExponentialModelParameters >::get_parameters(), ug::Richards::ExponentialModelParameters::Ksat, and RelativePermeability_().
EffSaturation_()
dual ug::Richards::ExponentialModel::EffSaturation_ (dual pc) const inline protected
Effective saturation: $0 \le \hat S \le 1$.
References ug::Richards::IParameterizedModel< ExponentialModelParameters >::get_parameters(), and p.
Referenced by Saturation_().
RelativePermeability_()
dual ug::Richards::ExponentialModel::RelativePermeability_ (dual pc) const inline protected
Relative permeability: $0 \le k_r \le 1$.
References ug::Richards::IParameterizedModel< ExponentialModelParameters >::get_parameters(), p, and ug::Richards::UGCheckValues().
Referenced by Conductivity_().
Saturation_()
dual ug::Richards::ExponentialModel::Saturation_ (dual pc) const inline protected
Rescaled Saturation: $$ S:=\theta_r+ (\theta_s - \theta_r) * \hat S$$.
References EffSaturation_(), ug::Richards::IParameterizedModel< ExponentialModelParameters >::get_parameters(), p, and ug::Richards::UGCheckValues().
Member Data Documentation
base_type
friend ug::Richards::ExponentialModel::base_type
parameterized_model_type
friend ug::Richards::ExponentialModel::parameterized_model_type
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Richards/van_genuchten.h