Plugins: ug::DiscConstraintFVCR< TGridFunction > Class Template Reference
ug::DiscConstraintFVCR< TGridFunction > Class Template Reference
#include <disc_constraint_fvcr.h>
Public Types
typedef TAlgebra algebra_type
Algebra type.
typedef Attachment< dimMat > AMathDimMat
typedef Attachment< std::vector< MathVector< dim > > > ANumberArray
typedef PeriodicAttachmentAccessor< side_type, AMathDimMat > aSideDimMat
typedef PeriodicAttachmentAccessor< side_type, ANumber > aSideNumber
typedef PeriodicAttachmentAccessor< side_type, ANumberArray > aSideNumberArray
typedef PeriodicAttachmentAccessor< side_type, ASizetArray > aSideSizetArray
typedef Attachment< std::vector< DoFIndex > > ASizetArray
typedef MathMatrix< dim, dim > dimMat
typedef TDomain domain_type
Type of Domain.
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef TGridFunction::template dim_traits< dim >::const_iterator ElemIterator
element iterator
typedef face_type_traits< dim >::face_type0 face_type0
typedef face_type_traits< dim >::face_type1 face_type1
typedef domain_traits< TDomain::dim >::grid_base_object grid_base_object
Type of geometric base object.
typedef domain_type::grid_type grid_type
grid type
typedef std::pair< MathVector< dim >, MathVector< dim > > MathVector_Pair
typedef algebra_type::matrix_type matrix_type
Type of algebra matrix.
typedef domain_type::position_accessor_type position_accessor_type
position accessor
typedef elem_type::side side_type
side type
typedef TGridFunction::template traits< side_type >::const_iterator SideIterator
side iterator
typedef TGridFunction::algebra_type TAlgebra
typedef TGridFunction::domain_type TDomain
typedef algebra_type::vector_type vector_type
Type of algebra vector.
typedef std::vector< std::pair< DoFIndex, MathVector< dim > > > vIndexPosPair
typedef std::vector< std::vector< std::pair< DoFIndex, MathVector< dim > > > > vvIndexPosPair
Public Types inherited from ug::IDomainConstraint< TGridFunction::domain_type, TGridFunction::algebra_type >
typedef TAlgebra algebra_type
typedef TDomain domain_type
typedef algebra_type::matrix_type matrix_type
typedef algebra_type::vector_type vector_type
Public Types inherited from ug::IConstraint< class >
typedef TAlgebra algebra_type
typedef algebra_type::matrix_type matrix_type
typedef algebra_type::vector_type vector_type
Public Member Functions
virtual void add_defect (vector_type &d, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, const number time=0.0, const number s_a=1.0)
virtual void add_pressure_defect (vector_type &d, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, const number time=0.0, const number s_a=1.0)
virtual void adjust_jacobian (matrix_type &J, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol=NULL, const number s_a0=1.0)
void compute_grad_shapes ()
compute gradient shapes for velocity on rotated elements
DiscConstraintFVCR (SmartPtr< TGridFunction > u)
constructor
DiscConstraintFVCR (SmartPtr< TGridFunction > u, bool bLinUpConvDefect, bool bLinUpConvJacobian, bool bLinPressureDefect, bool bLinPressureJacobian, bool bAdaptive)
DiscConstraintFVCR (SmartPtr< TGridFunction > u, bool bLinUpConvDefect, bool bLinUpConvJacobian, bool bLinPressureDefect, bool bLinPressureJacobian, bool bAdaptive, bool bLimiter)
DiscConstraintFVCR (SmartPtr< TGridFunction > u, bool bLinUpConvDefect, bool bLinUpConvJacobian, bool bLinPressureDefect, bool bLinPressureJacobian, bool bAdaptive, bool bLimiter, const char *subsets)
DiscConstraintFVCR (SmartPtr< TGridFunction > u, bool bLinUpConvDefect, bool bLinUpConvJacobian, bool bLinPressureDefect, bool bLinPressureJacobian, bool bAdaptive, const char *subsets)
void init (SmartPtr< TGridFunction > u, bool bLinUpConvDefect, bool bLinUpConvJacobian, bool bLinPressureDefect, bool bLinPressureJacobian, bool bAdaptive, bool bLimiter)
void set_limiter (bool bLimiter)
void set_zero_grad_bnd (const char *subsets)
set boundaries, in associated elements there is no linear pressure and no linear velocity upwind
bool zeroGradBndElem (typename grid_type::template traits< side_type >::secure_container sides)
~DiscConstraintFVCR ()
destructor
virtual void adjust_defect (vector_type &d, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol=SPNULL, const std::vector< number > *vScaleMass=NULL, const std::vector< number > *vScaleStiff=NULL)
virtual void adjust_linear (matrix_type &mat, vector_type &rhs, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
virtual void adjust_rhs (vector_type &rhs, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
virtual void adjust_solution (vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
virtual int type () const
returns the type of the constraints
Public Member Functions inherited from ug::IDomainConstraint< TGridFunction::domain_type, TGridFunction::algebra_type >
SmartPtr< ApproximationSpace< TDomain > > approximation_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approximation_space () const
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
IDomainConstraint ()
virtual void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_ass_tuner (ConstSmartPtr< AssemblingTuner< TAlgebra > > spAssemblingTuner=NULL)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
Public Member Functions inherited from ug::IConstraint< class >
virtual void adjust_correction (vector_type &c, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
virtual void adjust_error (const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol=SPNULL, const std::vector< number > *vScaleMass=NULL, const std::vector< number > *vScaleStiff=NULL)
virtual void adjust_linear_residual (vector_type &d, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
virtual void adjust_prolongation (matrix_type &P, ConstSmartPtr< DoFDistribution > ddFine, ConstSmartPtr< DoFDistribution > ddCoarse, int type, number time=0.0)
virtual void adjust_prolongation (vector_type &uFine, GridLevel fineLvl, const vector_type &uCoarse, GridLevel coarseLvl, int type)
virtual void adjust_restriction (matrix_type &R, ConstSmartPtr< DoFDistribution > ddCoarse, ConstSmartPtr< DoFDistribution > ddFine, int type, number time=0.0)
virtual void adjust_restriction (vector_type &uCoarse, GridLevel coarseLvl, const vector_type &uFine, GridLevel fineLvl, int type)
virtual void modify_solution (SmartPtr< VectorTimeSeries< vector_type > > vSolMod, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd, int type)
virtual void modify_solution (vector_type &uMod, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type)
virtual ~IConstraint ()
Public Attributes
aSideDimMat acGrad
aSideNumberArray acGradSh
aSideSizetArray acGradShInd
aSideNumber acVol
AMathDimMat aGrad
ANumberArray aGradSh
ASizetArray aGradShInd
ANumber aVol
Static Public Attributes
static const size_t _P_ = dim
static const int blockSize = algebra_type::blockSize
blockSize of used algebra
static const int dim = TDomain::dim
world Dimension
static const size_t maxShapeSize = 2*DimCRFVGeometry<dim>::maxNumSCV-1
Private Attributes
bool m_bAdaptive
bool m_bLinPressureDefect
bool m_bLinPressureJacobian
bool m_bLinUpConvDefect
bool m_bLinUpConvJacobian
grid_type * m_grid
ISubsetHandler * m_ish
bool m_limiter
SmartPtr< TGridFunction > m_u
SubsetGroup m_zeroGradSg
Additional Inherited Members
Protected Member Functions inherited from ug::IDomainConstraint< TGridFunction::domain_type, TGridFunction::algebra_type >
ConstSmartPtr< DoFDistribution > dd (const GridLevel &gl) const
Protected Attributes inherited from ug::IDomainConstraint< TGridFunction::domain_type, TGridFunction::algebra_type >
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
ConstSmartPtr< AssemblingTuner< TAlgebra > > m_spAssTuner
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
Member Typedef Documentation
algebra_type
template<typename TGridFunction > typedef TAlgebra ug::DiscConstraintFVCR< TGridFunction >::algebra_type
Algebra type.
AMathDimMat
template<typename TGridFunction > typedef Attachment<dimMat> ug::DiscConstraintFVCR< TGridFunction >::AMathDimMat
ANumberArray
template<typename TGridFunction > typedef Attachment<std::vector< MathVector<dim> > > ug::DiscConstraintFVCR< TGridFunction >::ANumberArray
aSideDimMat
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<side_type,AMathDimMat > ug::DiscConstraintFVCR< TGridFunction >::aSideDimMat
aSideNumber
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<side_type,ANumber > ug::DiscConstraintFVCR< TGridFunction >::aSideNumber
aSideNumberArray
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<side_type,ANumberArray> ug::DiscConstraintFVCR< TGridFunction >::aSideNumberArray
aSideSizetArray
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<side_type,ASizetArray> ug::DiscConstraintFVCR< TGridFunction >::aSideSizetArray
ASizetArray
template<typename TGridFunction > typedef Attachment<std::vector< DoFIndex > > ug::DiscConstraintFVCR< TGridFunction >::ASizetArray
dimMat
template<typename TGridFunction > typedef MathMatrix<dim,dim> ug::DiscConstraintFVCR< TGridFunction >::dimMat
domain_type
template<typename TGridFunction > typedef TDomain ug::DiscConstraintFVCR< TGridFunction >::domain_type
Type of Domain.
elem_type
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::grid_base_object ug::DiscConstraintFVCR< TGridFunction >::elem_type
element type
ElemIterator
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::const_iterator ug::DiscConstraintFVCR< TGridFunction >::ElemIterator
element iterator
face_type0
template<typename TGridFunction > typedef face_type_traits<dim>::face_type0 ug::DiscConstraintFVCR< TGridFunction >::face_type0
face_type1
template<typename TGridFunction > typedef face_type_traits<dim>::face_type1 ug::DiscConstraintFVCR< TGridFunction >::face_type1
grid_base_object
template<typename TGridFunction > typedef domain_traits<TDomain::dim>::grid_base_object ug::DiscConstraintFVCR< TGridFunction >::grid_base_object
Type of geometric base object.
grid_type
template<typename TGridFunction > typedef domain_type::grid_type ug::DiscConstraintFVCR< TGridFunction >::grid_type
grid type
MathVector_Pair
template<typename TGridFunction > typedef std::pair<MathVector<dim>, MathVector<dim> > ug::DiscConstraintFVCR< TGridFunction >::MathVector_Pair
matrix_type
template<typename TGridFunction > typedef algebra_type::matrix_type ug::DiscConstraintFVCR< TGridFunction >::matrix_type
Type of algebra matrix.
position_accessor_type
template<typename TGridFunction > typedef domain_type::position_accessor_type ug::DiscConstraintFVCR< TGridFunction >::position_accessor_type
position accessor
side_type
template<typename TGridFunction > typedef elem_type::side ug::DiscConstraintFVCR< TGridFunction >::side_type
side type
SideIterator
template<typename TGridFunction > typedef TGridFunction::template traits<side_type>::const_iterator ug::DiscConstraintFVCR< TGridFunction >::SideIterator
side iterator
TAlgebra
template<typename TGridFunction > typedef TGridFunction::algebra_type ug::DiscConstraintFVCR< TGridFunction >::TAlgebra
TDomain
template<typename TGridFunction > typedef TGridFunction::domain_type ug::DiscConstraintFVCR< TGridFunction >::TDomain
vector_type
template<typename TGridFunction > typedef algebra_type::vector_type ug::DiscConstraintFVCR< TGridFunction >::vector_type
Type of algebra vector.
vIndexPosPair
template<typename TGridFunction > typedef std::vector<std::pair<DoFIndex, MathVector<dim> > > ug::DiscConstraintFVCR< TGridFunction >::vIndexPosPair
vvIndexPosPair
template<typename TGridFunction > typedef std::vector<std::vector<std::pair<DoFIndex, MathVector<dim> > > > ug::DiscConstraintFVCR< TGridFunction >::vvIndexPosPair
Constructor & Destructor Documentation
DiscConstraintFVCR() [1/5]
template<typename TGridFunction > ug::DiscConstraintFVCR< TGridFunction >::DiscConstraintFVCR (SmartPtr< TGridFunction > u) inline
constructor
References ug::DiscConstraintFVCR< TGridFunction >::init().
DiscConstraintFVCR() [2/5]
template<typename TGridFunction > ug::DiscConstraintFVCR< TGridFunction >::DiscConstraintFVCR (SmartPtr< TGridFunction > u, bool bLinUpConvDefect, bool bLinUpConvJacobian, bool bLinPressureDefect, bool bLinPressureJacobian, bool bAdaptive) inline
References ug::DiscConstraintFVCR< TGridFunction >::init().
DiscConstraintFVCR() [3/5]
template<typename TGridFunction > ug::DiscConstraintFVCR< TGridFunction >::DiscConstraintFVCR (SmartPtr< TGridFunction > u, bool bLinUpConvDefect, bool bLinUpConvJacobian, bool bLinPressureDefect, bool bLinPressureJacobian, bool bAdaptive, bool bLimiter) inline
References ug::DiscConstraintFVCR< TGridFunction >::init().
DiscConstraintFVCR() [4/5]
template<typename TGridFunction > ug::DiscConstraintFVCR< TGridFunction >::DiscConstraintFVCR (SmartPtr< TGridFunction > u, bool bLinUpConvDefect, bool bLinUpConvJacobian, bool bLinPressureDefect, bool bLinPressureJacobian, bool bAdaptive, const char * subsets) inline
References ug::DiscConstraintFVCR< TGridFunction >::init(), and ug::DiscConstraintFVCR< TGridFunction >::set_zero_grad_bnd().
DiscConstraintFVCR() [5/5]
template<typename TGridFunction > ug::DiscConstraintFVCR< TGridFunction >::DiscConstraintFVCR (SmartPtr< TGridFunction > u, bool bLinUpConvDefect, bool bLinUpConvJacobian, bool bLinPressureDefect, bool bLinPressureJacobian, bool bAdaptive, bool bLimiter, const char * subsets) inline
References ug::DiscConstraintFVCR< TGridFunction >::init(), and ug::DiscConstraintFVCR< TGridFunction >::set_zero_grad_bnd().
~DiscConstraintFVCR()
template<typename TGridFunction > ug::DiscConstraintFVCR< TGridFunction >::~DiscConstraintFVCR () inline
destructor
Member Function Documentation
add_defect()
template<typename TGridFunction > virtual void ug::DiscConstraintFVCR< TGridFunction >::add_defect (vector_type & d, const vector_type & u, ConstSmartPtr< DoFDistribution > dd, const number time = 0.0, const number s_a = 1.0) inline virtual
References ug::DiscConstraintFVCR< TGridFunction >::_P_, ug::DiscConstraintFVCR< TGridFunction >::acGrad, ug::DiscConstraintFVCR< TGridFunction >::acVol, ug::CollectCornerCoordinates(), ug::IDomainConstraint< TGridFunction::domain_type, TGridFunction::algebra_type >::dd(), ug::DiscConstraintFVCR< TGridFunction >::dim, ug::DoFRef(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::from(), SmartPtr< TGridFunction >::get(), ug::DimCRFVGeometry< TDim, TWorldDim >::global_bary(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_grad(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_ip(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::global_ip(), ug::PeriodicBoundaryManager::is_slave(), ug::DiscConstraintFVCR< TGridFunction >::m_bAdaptive, ug::DiscConstraintFVCR< TGridFunction >::m_bLinPressureDefect, ug::DiscConstraintFVCR< TGridFunction >::m_grid, ug::DiscConstraintFVCR< TGridFunction >::m_limiter, ug::DiscConstraintFVCR< TGridFunction >::m_u, ug::DiscConstraintFVCR< TGridFunction >::m_zeroGradSg, ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::node_id(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::normal(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::normal(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_constrained_dofs(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scv(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scvf(), num_subsets(), s, ug::DimCRFVGeometry< TDim, TWorldDim >::scv(), ug::DimCRFVGeometry< TDim, TWorldDim >::scvf(), ug::SetAttachmentValues(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::shape(), ug::SubsetGroup::size(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::to(), UG_ASSERT, ug::DimCRFVGeometry< TDim, TWorldDim >::update(), ug::DimCRFVGeometry< TDim, TWorldDim >::update_hanging(), ug::VecProd(), ug::VecSet(), ug::VecSubtract(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::volume(), and ug::DiscConstraintFVCR< TGridFunction >::zeroGradBndElem().
Referenced by ug::DiscConstraintFVCR< TGridFunction >::adjust_defect().
add_pressure_defect()
template<typename TGridFunction > virtual void ug::DiscConstraintFVCR< TGridFunction >::add_pressure_defect (vector_type & d, const vector_type & u, ConstSmartPtr< DoFDistribution > dd, const number time = 0.0, const number s_a = 1.0) inline virtual
References ug::DiscConstraintFVCR< TGridFunction >::_P_, ug::CollectCornerCoordinates(), ug::IDomainConstraint< TGridFunction::domain_type, TGridFunction::algebra_type >::dd(), ug::DiscConstraintFVCR< TGridFunction >::dim, ug::DoFRef(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::from(), SmartPtr< TGridFunction >::get(), ug::DimCRFVGeometry< TDim, TWorldDim >::global_bary(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::global_ip(), ug::DiscConstraintFVCR< TGridFunction >::m_bAdaptive, ug::DiscConstraintFVCR< TGridFunction >::m_grid, ug::DiscConstraintFVCR< TGridFunction >::m_u, ug::DiscConstraintFVCR< TGridFunction >::m_zeroGradSg, ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::node_id(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::normal(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::normal(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_constrained_dofs(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scv(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scvf(), num_subsets(), s, ug::DimCRFVGeometry< TDim, TWorldDim >::scv(), ug::DimCRFVGeometry< TDim, TWorldDim >::scvf(), ug::SubsetGroup::size(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::to(), ug::DimCRFVGeometry< TDim, TWorldDim >::update(), ug::DimCRFVGeometry< TDim, TWorldDim >::update_hanging(), ug::VecSet(), ug::VecSubtract(), and ug::DiscConstraintFVCR< TGridFunction >::zeroGradBndElem().
Referenced by ug::DiscConstraintFVCR< TGridFunction >::adjust_defect().
adjust_defect()
template<typename TGridFunction > virtual void ug::DiscConstraintFVCR< TGridFunction >::adjust_defect (vector_type & d, const vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol = SPNULL, const std::vector< number > * vScaleMass = NULL, const std::vector< number > * vScaleStiff = NULL) inline virtual
adapts defect to enforce constraints
Implements ug::IConstraint< class >.
References ug::DiscConstraintFVCR< TGridFunction >::add_defect(), ug::DiscConstraintFVCR< TGridFunction >::add_pressure_defect(), ug::IDomainConstraint< TGridFunction::domain_type, TGridFunction::algebra_type >::dd(), ug::DiscConstraintFVCR< TGridFunction >::m_bLinUpConvDefect, and SPNULL.
adjust_jacobian()
template<typename TGridFunction > virtual void ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian (matrix_type & J, const vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol = NULL, const number s_a0 = 1.0) inline virtual
handle convection
handle pressure
Implements ug::IConstraint< class >.
References ug::DiscConstraintFVCR< TGridFunction >::_P_, ug::DiscConstraintFVCR< TGridFunction >::acGradSh, ug::DiscConstraintFVCR< TGridFunction >::acGradShInd, ug::CollectCornerCoordinates(), ug::DiscConstraintFVCR< TGridFunction >::compute_grad_shapes(), ug::IDomainConstraint< TGridFunction::domain_type, TGridFunction::algebra_type >::dd(), ug::DiscConstraintFVCR< TGridFunction >::dim, ug::DoFRef(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::from(), SmartPtr< TGridFunction >::get(), ug::DimCRFVGeometry< TDim, TWorldDim >::global_bary(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_ip(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::global_ip(), ug::DiscConstraintFVCR< TGridFunction >::m_bAdaptive, ug::DiscConstraintFVCR< TGridFunction >::m_bLinPressureJacobian, ug::DiscConstraintFVCR< TGridFunction >::m_bLinUpConvJacobian, ug::DiscConstraintFVCR< TGridFunction >::m_grid, ug::DiscConstraintFVCR< TGridFunction >::m_u, ug::DiscConstraintFVCR< TGridFunction >::m_zeroGradSg, ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::normal(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::normal(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scvf(), num_subsets(), s, ug::DimCRFVGeometry< TDim, TWorldDim >::scv(), ug::DimCRFVGeometry< TDim, TWorldDim >::scvf(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::shape(), ug::SubsetGroup::size(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::to(), ug::DimCRFVGeometry< TDim, TWorldDim >::update(), ug::VecProd(), ug::VecSet(), ug::VecSubtract(), and ug::DiscConstraintFVCR< TGridFunction >::zeroGradBndElem().
adjust_linear()
template<typename TGridFunction > virtual void ug::DiscConstraintFVCR< TGridFunction >::adjust_linear (matrix_type & mat, vector_type & rhs, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0) inline virtual
adapts matrix and rhs (linear case) to enforce constraints
Implements ug::IConstraint< class >.
adjust_rhs()
template<typename TGridFunction > virtual void ug::DiscConstraintFVCR< TGridFunction >::adjust_rhs (vector_type & rhs, const vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0) inline virtual
adapts a rhs to enforce constraints
Implements ug::IConstraint< class >.
adjust_solution()
template<typename TGridFunction > virtual void ug::DiscConstraintFVCR< TGridFunction >::adjust_solution (vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0) inline virtual
sets the constraints in a solution vector
Implements ug::IConstraint< class >.
compute_grad_shapes()
template<typename TGridFunction > void ug::DiscConstraintFVCR< TGridFunction >::compute_grad_shapes () inline
compute gradient shapes for velocity on rotated elements
References ug::DiscConstraintFVCR< TGridFunction >::acGradSh, ug::DiscConstraintFVCR< TGridFunction >::acGradShInd, ug::DiscConstraintFVCR< TGridFunction >::acVol, ug::CollectCornerCoordinates(), ug::DiscConstraintFVCR< TGridFunction >::dim, SmartPtr< TGridFunction >::get(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_grad(), ug::PeriodicBoundaryManager::is_slave(), ug::DiscConstraintFVCR< TGridFunction >::m_grid, ug::DiscConstraintFVCR< TGridFunction >::m_u, ug::DimCRFVGeometry< TDim, TWorldDim >::num_scv(), num_subsets(), s, ug::DimCRFVGeometry< TDim, TWorldDim >::scv(), ug::SetAttachmentValues(), UG_ASSERT, ug::DimCRFVGeometry< TDim, TWorldDim >::update(), and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::volume().
Referenced by ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian(), and ug::DiscConstraintFVCR< TGridFunction >::init().
init()
template<typename TGridFunction > void ug::DiscConstraintFVCR< TGridFunction >::init (SmartPtr< TGridFunction > u, bool bLinUpConvDefect, bool bLinUpConvJacobian, bool bLinPressureDefect, bool bLinPressureJacobian, bool bAdaptive, bool bLimiter) inline
References ug::PeriodicAttachmentAccessor< class, class >::access(), ug::DiscConstraintFVCR< TGridFunction >::acGrad, ug::DiscConstraintFVCR< TGridFunction >::acGradSh, ug::DiscConstraintFVCR< TGridFunction >::acGradShInd, ug::DiscConstraintFVCR< TGridFunction >::acVol, ug::DiscConstraintFVCR< TGridFunction >::aGrad, ug::DiscConstraintFVCR< TGridFunction >::aGradSh, ug::DiscConstraintFVCR< TGridFunction >::aGradShInd, ug::DiscConstraintFVCR< TGridFunction >::aVol, ug::DiscConstraintFVCR< TGridFunction >::compute_grad_shapes(), SmartPtr< TGridFunction >::get(), grid(), ug::DiscConstraintFVCR< TGridFunction >::m_bAdaptive, ug::DiscConstraintFVCR< TGridFunction >::m_bLinPressureDefect, ug::DiscConstraintFVCR< TGridFunction >::m_bLinPressureJacobian, ug::DiscConstraintFVCR< TGridFunction >::m_bLinUpConvDefect, ug::DiscConstraintFVCR< TGridFunction >::m_bLinUpConvJacobian, ug::DiscConstraintFVCR< TGridFunction >::m_grid, ug::DiscConstraintFVCR< TGridFunction >::m_ish, ug::DiscConstraintFVCR< TGridFunction >::m_limiter, and ug::DiscConstraintFVCR< TGridFunction >::m_u.
Referenced by ug::DiscConstraintFVCR< TGridFunction >::DiscConstraintFVCR().
set_limiter()
template<typename TGridFunction > void ug::DiscConstraintFVCR< TGridFunction >::set_limiter (bool bLimiter) inline
References ug::DiscConstraintFVCR< TGridFunction >::m_limiter.
set_zero_grad_bnd()
template<typename TGridFunction > void ug::DiscConstraintFVCR< TGridFunction >::set_zero_grad_bnd (const char * subsets) inline
set boundaries, in associated elements there is no linear pressure and no linear velocity upwind
References ug::DiscConstraintFVCR< TGridFunction >::m_u, ug::DiscConstraintFVCR< TGridFunction >::m_zeroGradSg, and UG_CATCH_THROW.
Referenced by ug::DiscConstraintFVCR< TGridFunction >::DiscConstraintFVCR().
type()
template<typename TGridFunction > virtual int ug::DiscConstraintFVCR< TGridFunction >::type () const inline virtual
returns the type of the constraints
Implements ug::IDomainConstraint< TGridFunction::domain_type, TGridFunction::algebra_type >.
References ug::CT_CONSTRAINTS.
zeroGradBndElem()
template<typename TGridFunction > bool ug::DiscConstraintFVCR< TGridFunction >::zeroGradBndElem (typename grid_type::template traits< side_type >::secure_container sides) inline
References ug::SubsetGroup::contains(), ug::ISubsetHandler::get_subset_index(), ug::DiscConstraintFVCR< TGridFunction >::m_ish, and ug::DiscConstraintFVCR< TGridFunction >::m_zeroGradSg.
Referenced by ug::DiscConstraintFVCR< TGridFunction >::add_defect(), ug::DiscConstraintFVCR< TGridFunction >::add_pressure_defect(), and ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian().
Member Data Documentation
_P_
template<typename TGridFunction > const size_t ug::DiscConstraintFVCR< TGridFunction >::_P_ = dim static
Referenced by ug::DiscConstraintFVCR< TGridFunction >::add_defect(), ug::DiscConstraintFVCR< TGridFunction >::add_pressure_defect(), and ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian().
acGrad
template<typename TGridFunction > aSideDimMat ug::DiscConstraintFVCR< TGridFunction >::acGrad
Referenced by ug::DiscConstraintFVCR< TGridFunction >::add_defect(), and ug::DiscConstraintFVCR< TGridFunction >::init().
acGradSh
template<typename TGridFunction > aSideNumberArray ug::DiscConstraintFVCR< TGridFunction >::acGradSh
Referenced by ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian(), ug::DiscConstraintFVCR< TGridFunction >::compute_grad_shapes(), and ug::DiscConstraintFVCR< TGridFunction >::init().
acGradShInd
template<typename TGridFunction > aSideSizetArray ug::DiscConstraintFVCR< TGridFunction >::acGradShInd
Referenced by ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian(), ug::DiscConstraintFVCR< TGridFunction >::compute_grad_shapes(), and ug::DiscConstraintFVCR< TGridFunction >::init().
acVol
template<typename TGridFunction > aSideNumber ug::DiscConstraintFVCR< TGridFunction >::acVol
Referenced by ug::DiscConstraintFVCR< TGridFunction >::add_defect(), ug::DiscConstraintFVCR< TGridFunction >::compute_grad_shapes(), and ug::DiscConstraintFVCR< TGridFunction >::init().
aGrad
template<typename TGridFunction > AMathDimMat ug::DiscConstraintFVCR< TGridFunction >::aGrad
Referenced by ug::DiscConstraintFVCR< TGridFunction >::init().
aGradSh
template<typename TGridFunction > ANumberArray ug::DiscConstraintFVCR< TGridFunction >::aGradSh
Referenced by ug::DiscConstraintFVCR< TGridFunction >::init().
aGradShInd
template<typename TGridFunction > ASizetArray ug::DiscConstraintFVCR< TGridFunction >::aGradShInd
Referenced by ug::DiscConstraintFVCR< TGridFunction >::init().
aVol
template<typename TGridFunction > ANumber ug::DiscConstraintFVCR< TGridFunction >::aVol
Referenced by ug::DiscConstraintFVCR< TGridFunction >::init().
blockSize
template<typename TGridFunction > const int ug::DiscConstraintFVCR< TGridFunction >::blockSize = algebra_type::blockSize static
blockSize of used algebra
dim
template<typename TGridFunction > const int ug::DiscConstraintFVCR< TGridFunction >::dim = TDomain::dim static
world Dimension
Referenced by ug::DiscConstraintFVCR< TGridFunction >::add_defect(), ug::DiscConstraintFVCR< TGridFunction >::add_pressure_defect(), ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian(), and ug::DiscConstraintFVCR< TGridFunction >::compute_grad_shapes().
m_bAdaptive
template<typename TGridFunction > bool ug::DiscConstraintFVCR< TGridFunction >::m_bAdaptive private
Referenced by ug::DiscConstraintFVCR< TGridFunction >::add_defect(), ug::DiscConstraintFVCR< TGridFunction >::add_pressure_defect(), ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian(), and ug::DiscConstraintFVCR< TGridFunction >::init().
m_bLinPressureDefect
template<typename TGridFunction > bool ug::DiscConstraintFVCR< TGridFunction >::m_bLinPressureDefect private
Referenced by ug::DiscConstraintFVCR< TGridFunction >::add_defect(), and ug::DiscConstraintFVCR< TGridFunction >::init().
m_bLinPressureJacobian
template<typename TGridFunction > bool ug::DiscConstraintFVCR< TGridFunction >::m_bLinPressureJacobian private
Referenced by ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian(), and ug::DiscConstraintFVCR< TGridFunction >::init().
m_bLinUpConvDefect
template<typename TGridFunction > bool ug::DiscConstraintFVCR< TGridFunction >::m_bLinUpConvDefect private
Referenced by ug::DiscConstraintFVCR< TGridFunction >::adjust_defect(), and ug::DiscConstraintFVCR< TGridFunction >::init().
m_bLinUpConvJacobian
template<typename TGridFunction > bool ug::DiscConstraintFVCR< TGridFunction >::m_bLinUpConvJacobian private
Referenced by ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian(), and ug::DiscConstraintFVCR< TGridFunction >::init().
m_grid
template<typename TGridFunction > grid_type* ug::DiscConstraintFVCR< TGridFunction >::m_grid private
Referenced by ug::DiscConstraintFVCR< TGridFunction >::add_defect(), ug::DiscConstraintFVCR< TGridFunction >::add_pressure_defect(), ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian(), ug::DiscConstraintFVCR< TGridFunction >::compute_grad_shapes(), and ug::DiscConstraintFVCR< TGridFunction >::init().
m_ish
template<typename TGridFunction > ISubsetHandler* ug::DiscConstraintFVCR< TGridFunction >::m_ish private
Referenced by ug::DiscConstraintFVCR< TGridFunction >::init(), and ug::DiscConstraintFVCR< TGridFunction >::zeroGradBndElem().
m_limiter
template<typename TGridFunction > bool ug::DiscConstraintFVCR< TGridFunction >::m_limiter private
Referenced by ug::DiscConstraintFVCR< TGridFunction >::add_defect(), ug::DiscConstraintFVCR< TGridFunction >::init(), and ug::DiscConstraintFVCR< TGridFunction >::set_limiter().
m_u
template<typename TGridFunction > SmartPtr<TGridFunction> ug::DiscConstraintFVCR< TGridFunction >::m_u private
Referenced by ug::DiscConstraintFVCR< TGridFunction >::add_defect(), ug::DiscConstraintFVCR< TGridFunction >::add_pressure_defect(), ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian(), ug::DiscConstraintFVCR< TGridFunction >::compute_grad_shapes(), ug::DiscConstraintFVCR< TGridFunction >::init(), and ug::DiscConstraintFVCR< TGridFunction >::set_zero_grad_bnd().
m_zeroGradSg
template<typename TGridFunction > SubsetGroup ug::DiscConstraintFVCR< TGridFunction >::m_zeroGradSg private
Referenced by ug::DiscConstraintFVCR< TGridFunction >::add_defect(), ug::DiscConstraintFVCR< TGridFunction >::add_pressure_defect(), ug::DiscConstraintFVCR< TGridFunction >::adjust_jacobian(), ug::DiscConstraintFVCR< TGridFunction >::set_zero_grad_bnd(), and ug::DiscConstraintFVCR< TGridFunction >::zeroGradBndElem().
maxShapeSize
template<typename TGridFunction > const size_t ug::DiscConstraintFVCR< TGridFunction >::maxShapeSize = 2*DimCRFVGeometry<dim>::maxNumSCV-1 static
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fvcr/disc_constraint_fvcr.h