Plugins: ug::SimpleTimeIntegrator< TDomain, TAlgebra > Class Template Reference
ug::SimpleTimeIntegrator< TDomain, TAlgebra > Class Template Reference
Integrate (a non-linear problem) over a given time interval.
#include <simple_integrator.hpp>
Public Types
typedef INonlinearTimeIntegrator< TDomain, TAlgebra > base_type
typedef IGridFunctionSpace< grid_function_type > grid_function_space_type
typedef base_type::grid_function_type grid_function_type
typedef ITimeDiscretization< TAlgebra > time_disc_type
typedef VectorTimeSeries< typename base_type::vector_type > vector_time_series_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::INonlinearTimeIntegrator< TDomain, TAlgebra >
typedef AssembledOperator< TAlgebra > assembled_operator_type
typedef ITimeIntegrator< TDomain, TAlgebra > base_type
typedef IOperatorInverse< vector_type > solver_type
typedef base_type::vector_type vector_type
Public Types inherited from ug::ITimeIntegrator< TDomain, TAlgebra >
typedef TAlgebra algebra_type
typedef TDomain domain_type
typedef GridFunction< TDomain, TAlgebra > grid_function_type
typedef TAlgebra::matrix_type matrix_type
typedef TAlgebra::vector_type vector_type
Public Types inherited from ug::IOperator< GridFunction< TDomain, TAlgebra > >
typedef Y codomain_function_type
typedef X domain_function_type
Public Types inherited from ug::TimeIntegratorSubject< TDomain, TAlgebra >
typedef ITimeIntegratorStageObserver_end< TDomain, TAlgebra > end_observer_type
typedef ITimeIntegratorStageObserver_finalize< TDomain, TAlgebra > finalize_observer_type
typedef GridFunction< TDomain, TAlgebra > grid_function_type
typedef ITimeIntegratorStageObserver_init< TDomain, TAlgebra > init_observer_type
enum observer_group_type
typedef ITimeIntegratorStageObserver_postprocess< TDomain, TAlgebra > postprocess_observer_type
typedef ITimeIntegratorStageObserver_preprocess< TDomain, TAlgebra > preprocess_observer_type
typedef std::vector< SmartPtr< process_observer_type > > process_observer_container_type
typedef ITimeIntegratorObserver< TDomain, TAlgebra > process_observer_type
typedef ITimeIntegratorStageObserver_rewind< TDomain, TAlgebra > rewind_observer_type
typedef ITimeIntegratorStageObserver_start< TDomain, TAlgebra > start_observer_type
Public Types inherited from ug::ITimeDiscDependentObject< TAlgebra >
typedef ITimeDiscretization< TAlgebra > time_disc_type
Public Member Functions
bool apply (SmartPtr< grid_function_type > u1, number t1, ConstSmartPtr< grid_function_type > u0, number t0)
number get_consistency_error () const
SmartPtr< grid_function_type > get_derivative ()
void set_banach_space (SmartPtr< IGridFunctionSpace< grid_function_type > > spSpace)
void set_derivative (SmartPtr< grid_function_type > udot)
SimpleTimeIntegrator (SmartPtr< time_disc_type > tDisc)
SimpleTimeIntegrator (SmartPtr< time_disc_type > tDisc, SmartPtr< grid_function_space_type > spSpace)
Public Member Functions inherited from ug::INonlinearTimeIntegrator< TDomain, TAlgebra >
double get_dt_max ()
double get_dt_min ()
double get_increase_factor ()
double get_reduction_factor ()
SmartPtr< solver_type > get_solver ()
ConstSmartPtr< solver_type > get_solver () const
INonlinearTimeIntegrator ()
void set_dt_max (double max)
void set_dt_min (double min)
void set_increase_factor (double inc)
void set_reduction_factor (double dec)
void set_solver (SmartPtr< solver_type > solver)
Public Member Functions inherited from ug::ITimeIntegrator< TDomain, TAlgebra >
void apply (grid_function_type &u1, const grid_function_type &u0)
Apply operator.
double get_time_step ()
void init ()
init operator
virtual void init (grid_function_type const &u)
init operator depending on a function u
ITimeIntegrator ()
void prepare (grid_function_type &u)
prepares functions for application
void set_no_log_out (bool bNoLogOut)
void set_precision_bound (double precisionBound)
void set_time_step (double dt)
Set initial time step.
virtual ~ITimeIntegrator ()
virtual destructor
Public Member Functions inherited from ug::IOperator< GridFunction< TDomain, TAlgebra > >
virtual void apply (Y &d, const X &u)=0
virtual void prepare (X &u)=0
virtual ~IOperator ()
Public Member Functions inherited from ug::TimeIntegratorSubject< TDomain, TAlgebra >
void attach_end_observer (SmartPtr< process_observer_type > obs)
void attach_finalize_observer (SmartPtr< process_observer_type > obs)
void attach_init_observer (SmartPtr< process_observer_type > obs)
void attach_observer (SmartPtr< process_observer_type > obs)
void attach_postprocess_observer (SmartPtr< process_observer_type > obs)
void attach_preprocess_observer (SmartPtr< process_observer_type > obs)
void attach_rewind_observer (SmartPtr< process_observer_type > obs)
void attach_start_observer (SmartPtr< process_observer_type > obs)
void reset_observers ()
Public Member Functions inherited from ug::ITimeDiscDependentObject< TAlgebra >
SmartPtr< time_disc_type > get_time_disc ()
ITimeDiscDependentObject (SmartPtr< time_disc_type > spTimeDisc)
Protected Types
typedef ITimeDiscDependentObject< TAlgebra > tdisc_dep_type
Protected Member Functions
bool apply_multi_stage (SmartPtr< grid_function_type > u1, number t1, ConstSmartPtr< grid_function_type > u0, number t0)
bool apply_single_stage (SmartPtr< grid_function_type > u1, number t1, ConstSmartPtr< grid_function_type > u0, number t0)
bool hasTerminated (double tCurrent, double tStart, double tFinal) const
Protected Member Functions inherited from ug::TimeIntegratorSubject< TDomain, TAlgebra >
void attach_to_group (int tGroup, SmartPtr< process_observer_type > obs)
void attach_to_group (SmartPtr< process_observer_type > obs)
bool notify_group (SmartPtr< grid_function_type > u, int step, number time, number dt)
Protected Attributes
number m_initial_consistency_error
SmartPtr< IGridFunctionSpace< grid_function_type > > m_spBanachSpace
metric
SmartPtr< grid_function_type > m_spDerivative
Protected Attributes inherited from ug::INonlinearTimeIntegrator< TDomain, TAlgebra >
TimeStepBounds m_dtBounds
SmartPtr< solver_type > m_spSolver
Protected Attributes inherited from ug::ITimeIntegrator< TDomain, TAlgebra >
bool m_bNoLogOut
double m_dt
double m_lower_tim
double m_precisionBound
double m_upper_tim
Protected Attributes inherited from ug::TimeIntegratorSubject< TDomain, TAlgebra >
std::vector< SmartPtr< end_observer_type > > m_vEndObservers
std::vector< SmartPtr< finalize_observer_type > > m_vFinalizeObservers
std::vector< SmartPtr< init_observer_type > > m_vInitObservers
std::vector< SmartPtr< postprocess_observer_type > > m_vPostprocessObservers
std::vector< SmartPtr< preprocess_observer_type > > m_vPreprocessObservers
process_observer_container_type m_vProcessObservers [TIO_GROUP_SIZE]
std::vector< SmartPtr< rewind_observer_type > > m_vRewindObservers
std::vector< SmartPtr< start_observer_type > > m_vStartObservers
Protected Attributes inherited from ug::ITimeDiscDependentObject< TAlgebra >
SmartPtr< time_disc_type > m_spTimeDisc
Additional Inherited Members
Public Attributes inherited from ug::TimeIntegratorSubject< TDomain, TAlgebra >
TIO_GROUP_END
TIO_GROUP_FINALIZE_STEP
TIO_GROUP_INIT_STEP
TIO_GROUP_POSTPROCESS_STEP
TIO_GROUP_PREPROCESS_STEP
TIO_GROUP_REWIND_STEP
TIO_GROUP_SIZE
TIO_GROUP_START
Detailed Description
template<class TDomain, class TAlgebra>
class ug::SimpleTimeIntegrator< TDomain, TAlgebra >
Integrate (a non-linear problem) over a given time interval.
Member Typedef Documentation
base_type
template<class TDomain , class TAlgebra > typedef INonlinearTimeIntegrator<TDomain, TAlgebra> ug::SimpleTimeIntegrator< TDomain, TAlgebra >::base_type
grid_function_space_type
template<class TDomain , class TAlgebra > typedef IGridFunctionSpace<grid_function_type> ug::SimpleTimeIntegrator< TDomain, TAlgebra >::grid_function_space_type
grid_function_type
template<class TDomain , class TAlgebra > typedef base_type::grid_function_type ug::SimpleTimeIntegrator< TDomain, TAlgebra >::grid_function_type
tdisc_dep_type
template<class TDomain , class TAlgebra > typedef ITimeDiscDependentObject<TAlgebra> ug::SimpleTimeIntegrator< TDomain, TAlgebra >::tdisc_dep_type protected
time_disc_type
template<class TDomain , class TAlgebra > typedef ITimeDiscretization<TAlgebra> ug::SimpleTimeIntegrator< TDomain, TAlgebra >::time_disc_type
vector_time_series_type
template<class TDomain , class TAlgebra > typedef VectorTimeSeries<typename base_type::vector_type> ug::SimpleTimeIntegrator< TDomain, TAlgebra >::vector_time_series_type
vector_type
template<class TDomain , class TAlgebra > typedef TAlgebra::vector_type ug::SimpleTimeIntegrator< TDomain, TAlgebra >::vector_type
Constructor & Destructor Documentation
SimpleTimeIntegrator() [1/2]
template<class TDomain , class TAlgebra > ug::SimpleTimeIntegrator< TDomain, TAlgebra >::SimpleTimeIntegrator (SmartPtr< time_disc_type > tDisc) inline
SimpleTimeIntegrator() [2/2]
template<class TDomain , class TAlgebra > ug::SimpleTimeIntegrator< TDomain, TAlgebra >::SimpleTimeIntegrator (SmartPtr< time_disc_type > tDisc, SmartPtr< grid_function_space_type > spSpace) inline
Member Function Documentation
apply()
template<class TDomain , class TAlgebra > bool ug::SimpleTimeIntegrator< TDomain, TAlgebra >::apply (SmartPtr< grid_function_type > u1, number t1, ConstSmartPtr< grid_function_type > u0, number t0) inline virtual
Implements ug::ITimeIntegrator< TDomain, TAlgebra >.
References ug::SimpleTimeIntegrator< TDomain, TAlgebra >::apply_multi_stage(), ug::SimpleTimeIntegrator< TDomain, TAlgebra >::apply_single_stage(), ug::ITimeDiscDependentObject< TAlgebra >::m_spTimeDisc, and ug::ITimeDiscretization< class >::num_stages().
Referenced by ug::LimexTimeIntegrator< TDomain, TAlgebra >::apply_integrator_threads().
apply_multi_stage()
template<typename TDomain , typename TAlgebra > bool ug::SimpleTimeIntegrator< TDomain, TAlgebra >::apply_multi_stage (SmartPtr< grid_function_type > u1, number t1, ConstSmartPtr< grid_function_type > u0, number t0) protected
References ug::IOperatorInverse< class, class >::apply(), ug::ITimeDiscretization< class >::future_time(), ug::IOperatorInverse< class, class >::init(), LIMEX_PROFILE_FUNC, make_sp(), ug::ITimeDiscretization< class >::num_stages(), ug::IOperatorInverse< class, class >::prepare(), ug::ITimeDiscretization< class >::prepare_step(), s, ug::ITimeDiscretization< class >::set_stage(), UG_COND_THROW, UG_LOG, and ug::VecAssign().
Referenced by ug::SimpleTimeIntegrator< TDomain, TAlgebra >::apply().
apply_single_stage()
template<typename TDomain , typename TAlgebra > bool ug::SimpleTimeIntegrator< TDomain, TAlgebra >::apply_single_stage (SmartPtr< grid_function_type > u1, number t1, ConstSmartPtr< grid_function_type > u0, number t0) protected
< contains all solutions compute so far
References ug::IOperatorInverse< class, class >::apply(), ug::IOperatorInverse< class, class >::init(), LIMEX_PROFILE_FUNC, make_sp(), ug::IOperatorInverse< class, class >::prepare(), ug::ITimeDiscretization< class >::prepare_step(), UG_ASSERT, UG_COND_THROW, UG_LOG, and ug::VecScaleAdd().
Referenced by ug::SimpleTimeIntegrator< TDomain, TAlgebra >::apply().
get_consistency_error()
template<class TDomain , class TAlgebra > number ug::SimpleTimeIntegrator< TDomain, TAlgebra >::get_consistency_error () const inline
References ug::SimpleTimeIntegrator< TDomain, TAlgebra >::m_initial_consistency_error.
Referenced by ug::LimexTimeIntegrator< TDomain, TAlgebra >::apply_integrator_threads().
get_derivative()
template<class TDomain , class TAlgebra > SmartPtr<grid_function_type> ug::SimpleTimeIntegrator< TDomain, TAlgebra >::get_derivative () inline
References ug::SimpleTimeIntegrator< TDomain, TAlgebra >::m_spDerivative.
hasTerminated()
template<class TDomain , class TAlgebra > bool ug::SimpleTimeIntegrator< TDomain, TAlgebra >::hasTerminated (double tCurrent, double tStart, double tFinal) const inline protected
References ug::ITimeIntegrator< TDomain, TAlgebra >::m_precisionBound.
set_banach_space()
template<class TDomain , class TAlgebra > void ug::SimpleTimeIntegrator< TDomain, TAlgebra >::set_banach_space (SmartPtr< IGridFunctionSpace< grid_function_type > > spSpace) inline
References ug::SimpleTimeIntegrator< TDomain, TAlgebra >::m_spBanachSpace.
Referenced by ug::LimexTimeIntegrator< TDomain, TAlgebra >::apply_integrator_threads().
set_derivative()
template<class TDomain , class TAlgebra > void ug::SimpleTimeIntegrator< TDomain, TAlgebra >::set_derivative (SmartPtr< grid_function_type > udot) inline
References ug::SimpleTimeIntegrator< TDomain, TAlgebra >::m_spDerivative.
Referenced by ug::LimexTimeIntegrator< TDomain, TAlgebra >::apply_integrator_threads().
Member Data Documentation
m_initial_consistency_error
template<class TDomain , class TAlgebra > number ug::SimpleTimeIntegrator< TDomain, TAlgebra >::m_initial_consistency_error protected
Referenced by ug::SimpleTimeIntegrator< TDomain, TAlgebra >::get_consistency_error().
m_spBanachSpace
template<class TDomain , class TAlgebra > SmartPtr<IGridFunctionSpace<grid_function_type> > ug::SimpleTimeIntegrator< TDomain, TAlgebra >::m_spBanachSpace protected
metric
Referenced by ug::SimpleTimeIntegrator< TDomain, TAlgebra >::set_banach_space().
m_spDerivative
template<class TDomain , class TAlgebra > SmartPtr<grid_function_type> ug::SimpleTimeIntegrator< TDomain, TAlgebra >::m_spDerivative protected
Referenced by ug::SimpleTimeIntegrator< TDomain, TAlgebra >::get_derivative(), and ug::SimpleTimeIntegrator< TDomain, TAlgebra >::set_derivative().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Limex/time_disc/simple_integrator.hpp