Plugins: ug::promesh::AnisoElemInfo Class Reference
ug::promesh::AnisoElemInfo Class Reference
Public Member Functions
AnisoElemInfo ()
bool has_short_edges () const
bool is_short_edge (size_t edgeIndex) const
template<class TAAPos , class TElem >
void refresh (TElem *elem, number aspectThreshold, TAAPos aaPos)
Private Attributes
bool m_hasShortEdges
vector< bool > m_isShort
vector< number > m_tmpLen
Constructor & Destructor Documentation
AnisoElemInfo()
ug::promesh::AnisoElemInfo::AnisoElemInfo () inline
Member Function Documentation
has_short_edges()
bool ug::promesh::AnisoElemInfo::has_short_edges () const inline
Referenced by ug::promesh::RegularizingRefinement_IMPL().
is_short_edge()
bool ug::promesh::AnisoElemInfo::is_short_edge (size_t edgeIndex) const inline
Referenced by ug::promesh::RegularizingRefinement_IMPL().
refresh()
template<class TAAPos , class TElem > void ug::promesh::AnisoElemInfo::refresh (TElem * elem, number aspectThreshold, TAAPos aaPos) inline
References VecDistance(), and ug::EdgeVertices::vertex().
Referenced by ug::promesh::RegularizingRefinement_IMPL().
Member Data Documentation
m_hasShortEdges
bool ug::promesh::AnisoElemInfo::m_hasShortEdges private
m_isShort
vector<bool> ug::promesh::AnisoElemInfo::m_isShort private
m_tmpLen
vector<number> ug::promesh::AnisoElemInfo::m_tmpLen private
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/ProMesh/tools/refinement_tools.cpp