Plugins: ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain > Class Template Reference
ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain > Class Template Reference
Plugins » Convection Diffusion
Discretization for the Convection-Diffusion Equation.
#include <convection_diffusion_stab_fe.h>
Public Member Functions
ConvectionDiffusionStabFE (const char *functions, const char *subsets)
Constructor.
ConvectionDiffusionStabFE (const char *functions, const char *subsets, number stabM)
ConvectionDiffusionStabFE (const char *functions, const char *subsets, number stabM, number stabA)
virtual void prepare_setting (const std::vector< LFEID > &vLfeID, bool bNonRegularGrid)
type of trial space for each function used
void set_quad_order (size_t order)
sets the quad order
virtual bool use_hanging () const
returns if hanging nodes are needed
virtual ~ConvectionDiffusionStabFE ()
Destructor.
Public Member Functions inherited from ug::IElemDisc< TDomain >
void add_elem_modifier (SmartPtr< IElemDiscModifier< TDomain > > elemModifier)
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > & get_elem_modifier ()
IElemDisc (const char *functions, const char *subsets)
IElemDisc (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
virtual void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_A_expl_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
void do_add_def_A_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_A_expl_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_def_M_elem (LocalVector &d, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_A_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_jac_M_elem (LocalMatrix &J, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_add_rhs_elem (LocalVector &rhs, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_fsh_elem_loop ()
void do_fsh_timestep (const number time, VectorProxyBase *u, size_t algebra_id)
void do_fsh_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_elem (LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
void do_prep_elem_loop (const ReferenceObjectID roid, const int si)
void do_prep_timestep (number future_time, const number time, VectorProxyBase *u, size_t algebra_id)
void do_prep_timestep_elem (const number time, LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void fsh_timestep (number time, VectorProxyBase *u)
virtual void fsh_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
IElemAssembleFuncs ()
virtual void post_assemble_loop ()
virtual void prep_assemble_loop ()
virtual void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
virtual void prep_elem_loop (const ReferenceObjectID roid, const int si)
virtual void prep_timestep (number future_time, number time, VectorProxyBase *u)
virtual void prep_timestep_elem (const number time, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemAssembleFuncs ()
Public Member Functions inherited from ug::IElemError< class >
IElemError (const char *functions, const char *subsets)
IElemError (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
Public Member Functions inherited from ug::IElemDiscBase< class >
SmartPtr< ApproximationSpace< TDomain > > approx_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approx_space () const
void check_setup (bool bNonRegularGrid)
void clear_imports ()
SmartPtr< TDomain > domain ()
ConstSmartPtr< TDomain > domain () const
const FunctionGroup & function_group () const
ConstSmartPtr< FunctionPattern > function_pattern () const
IDataImport< dim > & get_import (size_t i)
IElemDiscBase (const char *functions="", const char *subsets="")
IElemDiscBase (const std::vector< std::string > &vFct, const std::vector< std::string > &vSubset)
bool is_time_dependent () const
bool local_time_series_needed ()
const LocalVectorTimeSeries * local_time_solutions () const
const FunctionIndexMapping & map () const
number mass_scale () const
number mass_scale () const
number mass_scale (const size_t timePoint) const
number mass_scale (const size_t timePoint) const
const std::vector< number > & mass_scales () const
const std::vector< number > & mass_scales () const
size_t num_fct () const
size_t num_imports () const
size_t num_subsets () const
void register_import (IDataImport< dim > &Imp)
virtual bool requests_local_time_series ()
void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_functions (const std::string &functions)
void set_functions (const std::vector< std::string > &functions)
void set_stationary ()
void set_stationary (bool bStationaryForced=true)
void set_subsets (const std::string &subsets)
void set_subsets (const std::vector< std::string > &subsets)
void set_time_dependent (LocalVectorTimeSeries &locTimeSeries, const std::vector< number > &vScaleMass, const std::vector< number > &vScaleStiff)
void set_time_independent ()
void set_time_point (const size_t timePoint)
number stiff_scale () const
number stiff_scale () const
number stiff_scale (const size_t timePoint) const
number stiff_scale (const size_t timePoint) const
const std::vector< number > & stiff_scales () const
const std::vector< number > & stiff_scales () const
TDomain::subset_handler_type & subset_handler ()
const TDomain::subset_handler_type & subset_handler () const
const std::vector< std::string > & symb_fcts () const
const std::vector< std::string > & symb_subsets () const
number time () const
size_t time_point () const
virtual int type () const
virtual ~IElemDiscBase ()
Public Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
IElemDisc< TDomain > & asLeaf ()
void check_roid (ReferenceObjectID roid, int discType)
virtual void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
virtual void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_A_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_M_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
void do_fsh_err_est_elem_loop ()
void do_prep_err_est_elem (LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
void do_prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
IElemEstimatorFuncs ()
virtual void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
virtual void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
void set_roid (ReferenceObjectID id, int discType)
virtual ~IElemEstimatorFuncs ()
Static Public Attributes
static const int dim = base_type::dim
World dimension.
Static Public Attributes inherited from ug::IElemDisc< TDomain >
static const int dim
Static Public Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Static Public Attributes inherited from ug::IElemError< class >
static const int dim
Static Public Attributes inherited from ug::IElemDiscBase< class >
static const int dim
Static Public Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
static const int dim
Protected Member Functions
void register_all_funcs (const LFEID &lfeid, const int quadOrder)
template<typename TElem , typename TFEGeom >
void register_func ()
Protected Member Functions inherited from ug::IElemDisc< TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void set_default_add_fct ()
Protected Member Functions inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_add_def_A_elem_fct (ReferenceObjectID id)
void remove_add_def_A_expl_elem_fct (ReferenceObjectID id)
void remove_add_def_M_elem_fct (ReferenceObjectID id)
void remove_add_jac_A_elem_fct (ReferenceObjectID id)
void remove_add_jac_M_elem_fct (ReferenceObjectID id)
void remove_add_rhs_elem_fct (ReferenceObjectID id)
void remove_fsh_elem_loop_fct (ReferenceObjectID id)
void remove_fsh_timestep_elem_fct (ReferenceObjectID id)
void remove_fsh_timestep_fct (size_t algebra_id)
void remove_prep_elem_fct (ReferenceObjectID id)
void remove_prep_elem_loop_fct (ReferenceObjectID id)
void remove_prep_timestep_elem_fct (ReferenceObjectID id)
void remove_prep_timestep_fct (size_t algebra_id)
void set_add_def_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_A_expl_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_def_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_A_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_jac_M_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_add_rhs_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_fsh_timestep_fct (size_t algebra_id, TAssFunc func)
void set_prep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_elem_loop_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_elem_fct (ReferenceObjectID id, TAssFunc func)
void set_prep_timestep_fct (size_t algebra_id, TAssFunc func)
Protected Member Functions inherited from ug::IElemError< class >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
Protected Member Functions inherited from ug::IElemDiscBase< class >
virtual void approximation_space_changed ()
void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
void update_function_index_mapping ()
Protected Member Functions inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
void clear_add_fct ()
void clear_add_fct (ReferenceObjectID id)
void remove_compute_err_est_A_elem (ReferenceObjectID id)
void remove_compute_err_est_M_elem (ReferenceObjectID id)
void remove_compute_err_est_rhs_elem (ReferenceObjectID id)
void remove_fsh_err_est_elem_loop (ReferenceObjectID id)
void remove_prep_err_est_elem (ReferenceObjectID id)
void remove_prep_err_est_elem_loop (ReferenceObjectID id)
void set_compute_err_est_A_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_M_elem (ReferenceObjectID id, TAssFunc func)
void set_compute_err_est_rhs_elem (ReferenceObjectID id, TAssFunc func)
void set_default_add_fct ()
void set_fsh_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem (ReferenceObjectID id, TAssFunc func)
void set_prep_err_est_elem_loop (ReferenceObjectID id, TAssFunc func)
Protected Attributes
bool m_bQuadOrderUserDef
current integration order
LFEID m_lfeID
current shape function set
int m_quadOrder
Protected Attributes inherited from ug::IElemDisc< TDomain >
std::vector< SmartPtr< IElemDiscModifier< TDomain > > > m_spElemModifier
Protected Attributes inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
Protected Attributes inherited from ug::IElemDiscBase< class >
bool m_bStationaryForced
FunctionGroup m_fctGrp
FunctionIndexMapping m_fctIndexMap
LocalVectorTimeSeries * m_pLocalVectorTimeSeries
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
ConstSmartPtr< FunctionPattern > m_spFctPattern
size_t m_timePoint
std::vector< std::string > m_vFct
std::vector< IDataImport< dim > * > m_vIImport
std::vector< number > m_vScaleMass
std::vector< number > m_vScaleStiff
std::vector< std::string > m_vSubset
Protected Attributes inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
ReferenceObjectID m_roid
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
Private Types
typedef IElemDisc< TDomain > base_type
Base class type.
typedef ConvectionDiffusionStabFE< TDomain > this_type
Own type.
Private Member Functions
template<typename TElem , typename TFEGeom >
void add_def_A_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the stiffness part of the local defect
template<typename TElem , typename TFEGeom >
void add_def_M_elem (LocalVector &d, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the mass part of the local defect
template<typename TElem , typename TFEGeom >
void add_jac_A_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the local stiffness matrix using a finite volume scheme
template<typename TElem , typename TFEGeom >
void add_jac_M_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the local mass matrix using a finite volume scheme
template<typename TElem , typename TFEGeom >
void add_jac_X_elem (LocalMatrix &J, const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], double stab)
template<typename TElem , typename TFEGeom >
void add_rhs_elem (LocalVector &d, GridObject *elem, const MathVector< dim > vCornerCoords[])
assembles the local right hand side
template<typename TElem , typename TFEGeom >
void compute_err_est_A_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
computes the error estimator contribution for one element
template<typename TElem , typename TFEGeom >
void compute_err_est_M_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
computes the error estimator contribution for one element
template<typename TElem , typename TFEGeom >
void compute_err_est_rhs_elem (GridObject *elem, const MathVector< dim > vCornerCoords[], const number &scale)
computes the error estimator contribution for one element
template<typename TElem , typename TFEGeom >
void fsh_elem_loop ()
finishes the loop over all elements
template<typename TElem , typename TFEGeom >
void fsh_err_est_elem_loop ()
postprocesses the loop over all elements of one type in the computation of the error estimator
template<typename TElem , typename TFEGeom >
void prep_elem (const LocalVector &u, GridObject *elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[])
prepares the element for assembling
template<typename TElem , typename TFEGeom >
void prep_elem_loop (const ReferenceObjectID roid, const int si)
prepares the loop over all elements
template<typename TElem , typename TFEGeom >
void prep_err_est_elem (const LocalVector &u, GridObject *elem, const MathVector< dim > vCornerCoords[])
prepares the element for assembling the error estimator
template<typename TElem , typename TFEGeom >
void prep_err_est_elem_loop (const ReferenceObjectID roid, const int si)
prepares the loop over all elements of one type for the computation of the error estimator
Private Attributes
double m_stabParamA
double m_stabParamM
struct holding values of shape functions in IPs
Static Private Attributes
static const size_t _C_ = 0
abbreviation for the local solution
Additional Inherited Members
Public Types inherited from ug::IElemDisc< TDomain >
typedef IElemAssembleFuncs< IElemDisc< TDomain >, TDomain > assemble_base_type
typedef IElemError< TDomain > base_type
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Public Types inherited from ug::IElemError< class >
typedef TDomain domain_type
typedef IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain > estimator_base_type
Public Types inherited from ug::IElemDiscBase< class >
typedef TDomain domain_type
typedef TDomain::position_type position_type
Public Types inherited from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >
typedef TDomain domain_type
typedef IElemDisc< TDomain > leaf_type
Detailed Description
template<typename TDomain>
class ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >
Discretization for the Convection-Diffusion Equation.
This class implements the IElemDisc interface to provide element local assemblings for the convection diffusion equation.
Template Parameters
TDomain Domain
TAlgebra Algebra
Member Typedef Documentation
base_type
template<typename TDomain > typedef IElemDisc<TDomain> ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::base_type private
Base class type.
this_type
template<typename TDomain > typedef ConvectionDiffusionStabFE<TDomain> ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::this_type private
Own type.
Constructor & Destructor Documentation
ConvectionDiffusionStabFE() [1/3]
template<typename TDomain > ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::ConvectionDiffusionStabFE (const char * functions, const char * subsets)
Constructor.
References ug::IElemDisc< TDomain >::clear_add_fct().
ConvectionDiffusionStabFE() [2/3]
template<typename TDomain > ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::ConvectionDiffusionStabFE (const char * functions, const char * subsets, number stabM)
References ug::IElemDisc< TDomain >::clear_add_fct().
ConvectionDiffusionStabFE() [3/3]
template<typename TDomain > ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::ConvectionDiffusionStabFE (const char * functions, const char * subsets, number stabM, number stabA)
References ug::IElemDisc< TDomain >::clear_add_fct().
~ConvectionDiffusionStabFE()
template<typename TDomain > virtual ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::~ConvectionDiffusionStabFE () inline virtual
Destructor.
Member Function Documentation
add_def_A_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::add_def_A_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) inline private
assembles the stiffness part of the local defect
add_def_M_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::add_def_M_elem (LocalVector & d, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private
assembles the mass part of the local defect
Assemble contribution: \sigma \int_{tau} \sum h_i^2 \partial_i u^k \partial_i v
References dim, ug::GeomProvider< TGeom >::get(), ug::NumVertices(), ug::VecDot(), ug::VecScaleAppend(), and ug::VecSet().
add_jac_A_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::add_jac_A_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private
assembles the local stiffness matrix using a finite volume scheme
add_jac_M_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::add_jac_M_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) private
assembles the local mass matrix using a finite volume scheme
add_jac_X_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::add_jac_X_elem (LocalMatrix & J, const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], double stab) private
References dim, ug::GeomProvider< TGeom >::get(), ug::NumVertices(), and ug::VecDot().
add_rhs_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::add_rhs_elem (LocalVector & d, GridObject * elem, const MathVector< dim > vCornerCoords[]) inline private
assembles the local right hand side
compute_err_est_A_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::compute_err_est_A_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) inline private
computes the error estimator contribution for one element
compute_err_est_M_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::compute_err_est_M_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) inline private
computes the error estimator contribution for one element
compute_err_est_rhs_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::compute_err_est_rhs_elem (GridObject * elem, const MathVector< dim > vCornerCoords[], const number & scale) inline private
computes the error estimator contribution for one element
fsh_elem_loop()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::fsh_elem_loop () private virtual
finishes the loop over all elements
Reimplemented from IElemAssembleFuncs< IElemDisc< TDomain >, TDomain >.
fsh_err_est_elem_loop()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::fsh_err_est_elem_loop () inline private virtual
postprocesses the loop over all elements of one type in the computation of the error estimator
Reimplemented from IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >.
prep_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::prep_elem (const LocalVector & u, GridObject * elem, const ReferenceObjectID roid, const MathVector< dim > vCornerCoords[]) private
prepares the element for assembling
This methods prepares an element for the assembling. The Positions of the Element Corners are read and the Finite Volume Geometry is updated. The global ip positions are scheduled at the data imports.
References ug::GeomProvider< TGeom >::get(), and UG_CATCH_THROW.
prep_elem_loop()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::prep_elem_loop (const ReferenceObjectID roid, const int si) private
prepares the loop over all elements
This method prepares the loop over all elements. It resizes the Position array for the corner coordinates and schedules the local ip positions at the data imports.
References ug::GeomProvider< TGeom >::get(), and UG_CATCH_THROW.
prep_err_est_elem()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::prep_err_est_elem (const LocalVector & u, GridObject * elem, const MathVector< dim > vCornerCoords[]) inline private
prepares the element for assembling the error estimator
prep_err_est_elem_loop()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::prep_err_est_elem_loop (const ReferenceObjectID roid, const int si) inline private
prepares the loop over all elements of one type for the computation of the error estimator
prepare_setting()
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::prepare_setting (const std::vector< LFEID > & vLfeID, bool bNonRegularGrid) virtual
type of trial space for each function used
Implements ug::IElemDiscBase< class >.
References UG_THROW.
register_all_funcs()
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::register_all_funcs (const LFEID & lfeid, const int quadOrder) protected
register utils
register_func()
template<typename TDomain > template<typename TElem , typename TFEGeom > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::register_func () protected
register utils
set_quad_order()
template<typename TDomain > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::set_quad_order (size_t order)
sets the quad order
use_hanging()
template<typename TDomain > bool ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::use_hanging () const virtual
returns if hanging nodes are needed
Reimplemented from ug::IElemDiscBase< class >.
Member Data Documentation
_C_
template<typename TDomain > const size_t ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::_C_ = 0 static private
abbreviation for the local solution
dim
template<typename TDomain > const int ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::dim = base_type::dim static
World dimension.
m_bQuadOrderUserDef
template<typename TDomain > bool ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::m_bQuadOrderUserDef protected
current integration order
m_lfeID
template<typename TDomain > LFEID ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::m_lfeID protected
current shape function set
m_quadOrder
template<typename TDomain > int ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::m_quadOrder protected
m_stabParamA
template<typename TDomain > double ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::m_stabParamA private
m_stabParamM
template<typename TDomain > double ug::ConvectionDiffusionPlugin::ConvectionDiffusionStabFE< TDomain >::m_stabParamM private
struct holding values of shape functions in IPs
The documentation for this class was generated from the following files:
/var/lib/jenkins/workspace/ug-docs/plugins/ConvectionDiffusion/fe/convection_diffusion_stab_fe.h
/var/lib/jenkins/workspace/ug-docs/plugins/ConvectionDiffusion/fe/convection_diffusion_stab_fe.cpp