Plugins: ug::Electromagnetism::ComputeElemFluxHelper< TGridFunc, TElem > Class Template Reference
ug::Electromagnetism::ComputeElemFluxHelper< TGridFunc, TElem > Class Template Reference
Helper class for computation of the flux in elements. (Helper for ComputeFlux.)
#include <nedelec_aux_cmd_impl.h>
Static Public Member Functions
static number compute_flux (TGridFunc *pGF, size_t fct, SubsetGroup &volSSG, SubsetGroup &faceSSG)
Computation of the flux through the sides of all elements of one type.
Static Private Member Functions
static number compute_elem_flux (TGridFunc *pGF, size_t fct, TElem *pElem, SubsetGroup &faceSSG)
Computation of the flux through sides of an element.
Detailed Description
template<typename TGridFunc, typename TElem>
class ug::Electromagnetism::ComputeElemFluxHelper< TGridFunc, TElem >
Helper class for computation of the flux in elements. (Helper for ComputeFlux.)
Member Function Documentation
compute_elem_flux()
template<typename TGridFunc , typename TElem > static number ug::Electromagnetism::ComputeElemFluxHelper< TGridFunc, TElem >::compute_elem_flux (TGridFunc * pGF, size_t fct, TElem * pElem, SubsetGroup & faceSSG) inline static private
Computation of the flux through sides of an element.
Parameters
pGF grid function of the Nedelec-DoFs of the vector field
fct index of the function in the grid function
pElem the element
faceSSG the surface (the low-dim. subsets)
References ug::SubsetGroup::contains(), dim, ug::DoFRef(), ug::Provider< class >::get(), ug::Grid::get_side(), ug::ISubsetHandler::get_subset_index(), ug::ISubsetHandler::grid(), normal, UG_ASSERT, UG_THROW, ug::Electromagnetism::NedelecInterpolation< TDomain, refDim, WDim >::value(), and ug::VecDot().
Referenced by ug::Electromagnetism::ComputeElemFluxHelper< TGridFunc, TElem >::compute_flux().
compute_flux()
template<typename TGridFunc , typename TElem > static number ug::Electromagnetism::ComputeElemFluxHelper< TGridFunc, TElem >::compute_flux (TGridFunc * pGF, size_t fct, SubsetGroup & volSSG, SubsetGroup & faceSSG) inline static
Computation of the flux through the sides of all elements of one type.
Parameters
pGF grid function of the Nedelec-DoFs of the vector field
fct index of the function in the grid function
volSSG full-dim. subsets (adjacent to the surface) to indicate the negative direction
faceSSG the surface (the low-dim. subsets)
References ug::Electromagnetism::ComputeElemFluxHelper< TGridFunc, TElem >::compute_elem_flux(), and ug::SubsetGroup::size().
Referenced by ug::Electromagnetism::ComputeFluxHelper< TGridFunc >::operator()().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_aux_cmd_impl.h