Plugins: ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource Class Reference
ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource Class Reference
Constraint that sets the problem to 0-identity out of the source.
Classes
struct MarkSourceVertices
Helper class for marking the vertices in the closure of the source subdomain.
Public Member Functions
void adjust_defect (pot_vector_type &d, const pot_vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< pot_vector_type > > vSol=SPNULL, const std::vector< number > *vScaleMass=NULL, const std::vector< number > *vScaleStiff=NULL)
sets a zero value in the defect for all conductor indices
void adjust_jacobian (pot_matrix_type &J, const pot_vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< pot_vector_type > > vSol=SPNULL, const number s_a0=1.0)
sets a unity row for all conductor indices
void adjust_linear (pot_matrix_type &A, pot_vector_type &b, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
sets unity rows in A and dirichlet values in right-hand side b
void adjust_rhs (pot_vector_type &b, const pot_vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
sets the dirichlet value in the right-hand side
void adjust_solution (pot_vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
sets the value in the solution for all conductor indices
void init (domain_type *dom, a_vert_flag_type &a_in_source)
initializer
OutOfSource (NedelecLoopCurrent &master)
constructor
void set_zero_average (const DoFDistribution &vertDD, pot_vector_type &u)
sets the arithmetic average of the solution vector to zero
int type () const
returns the type of the constraints
Public Member Functions inherited from ug::IDomainConstraint< TDomain, TPotAlgebra >
SmartPtr< ApproximationSpace< TDomain > > approximation_space ()
ConstSmartPtr< ApproximationSpace< TDomain > > approximation_space () const
virtual SmartPtr< IErrEstData< TDomain > > err_est_data ()
bool err_est_enabled () const
IDomainConstraint ()
virtual void set_approximation_space (SmartPtr< ApproximationSpace< TDomain > > approxSpace)
void set_ass_tuner (ConstSmartPtr< AssemblingTuner< TAlgebra > > spAssemblingTuner=NULL)
void set_error_estimator (SmartPtr< IErrEstData< TDomain > > ee)
Public Member Functions inherited from ug::IConstraint< class >
virtual void adjust_correction (vector_type &c, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
virtual void adjust_defect (vector_type &d, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol=SPNULL, const std::vector< number > *vScaleMass=NULL, const std::vector< number > *vScaleStiff=NULL)=0
virtual void adjust_error (const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol=SPNULL, const std::vector< number > *vScaleMass=NULL, const std::vector< number > *vScaleStiff=NULL)
virtual void adjust_jacobian (matrix_type &J, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol=SPNULL, const number s_a0=1.0)=0
virtual void adjust_linear (matrix_type &mat, vector_type &rhs, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)=0
virtual void adjust_linear_residual (vector_type &d, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)
virtual void adjust_prolongation (matrix_type &P, ConstSmartPtr< DoFDistribution > ddFine, ConstSmartPtr< DoFDistribution > ddCoarse, int type, number time=0.0)
virtual void adjust_prolongation (vector_type &uFine, GridLevel fineLvl, const vector_type &uCoarse, GridLevel coarseLvl, int type)
virtual void adjust_restriction (matrix_type &R, ConstSmartPtr< DoFDistribution > ddCoarse, ConstSmartPtr< DoFDistribution > ddFine, int type, number time=0.0)
virtual void adjust_restriction (vector_type &uCoarse, GridLevel coarseLvl, const vector_type &uFine, GridLevel fineLvl, int type)
virtual void adjust_rhs (vector_type &rhs, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)=0
virtual void adjust_solution (vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type, number time=0.0)=0
virtual void modify_solution (SmartPtr< VectorTimeSeries< vector_type > > vSolMod, ConstSmartPtr< VectorTimeSeries< vector_type > > vSol, ConstSmartPtr< DoFDistribution > dd, int type)
virtual void modify_solution (vector_type &uMod, const vector_type &u, ConstSmartPtr< DoFDistribution > dd, int type)
virtual ~IConstraint ()
Private Types
typedef DoFDistribution::traits< Vertex >::const_iterator t_vert_iterator
Iterator over vertices.
Private Member Functions
void adjust_matrix (const DoFDistribution &vertDD, pot_matrix_type &A)
sets to identity all the matrix rows that do not belong to the closure of the source subdomain
void adjust_vector (const DoFDistribution &vertDD, pot_vector_type &u)
sets to 0 all the entries of a vector that do not belong to the closure of the source subdomain
void mark_source_vertices (const TDomain *dom)
marks the vertices belonging to elements in the source (for all element types)
template<typename TElem >
void mark_source_vertices_elem_type (const TDomain *dom)
marks the vertices belonging to elements in the source (for one element type)
Private Attributes
aa_vert_flag_type m_in_source
attachment accessor for the current vertex flags
NedelecLoopCurrent & m_master
the master object of the projection
Static Private Attributes
static const size_t maxCorners = (size_t) element_list_traits<typename domain_traits<WDim>::DimElemList>::maxCorners
maximum number of corners of an element
Additional Inherited Members
Public Types inherited from ug::IDomainConstraint< TDomain, TPotAlgebra >
typedef TAlgebra algebra_type
typedef TDomain domain_type
typedef algebra_type::matrix_type matrix_type
typedef algebra_type::vector_type vector_type
Public Types inherited from ug::IConstraint< class >
typedef TAlgebra algebra_type
typedef algebra_type::matrix_type matrix_type
typedef algebra_type::vector_type vector_type
Protected Member Functions inherited from ug::IDomainConstraint< TDomain, TPotAlgebra >
ConstSmartPtr< DoFDistribution > dd (const GridLevel &gl) const
Protected Attributes inherited from ug::IDomainConstraint< TDomain, TPotAlgebra >
SmartPtr< ApproximationSpace< TDomain > > m_spApproxSpace
ConstSmartPtr< AssemblingTuner< TAlgebra > > m_spAssTuner
SmartPtr< IErrEstData< TDomain > > m_spErrEstData
Detailed Description
template<typename TDomain, typename TAlgebra>
class ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource
Constraint that sets the problem to 0-identity out of the source.
This class restricts the discretized Laplace equation to the subsets of the source: In the parts of the domain that do not belong to the closure of the source, the discretization matrix is set to identity, and the right-hand side is set to zero.
Member Typedef Documentation
t_vert_iterator
template<typename TDomain , typename TAlgebra > typedef DoFDistribution::traits<Vertex>::const_iterator ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::t_vert_iterator private
Iterator over vertices.
Constructor & Destructor Documentation
OutOfSource()
template<typename TDomain , typename TAlgebra > ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::OutOfSource (NedelecLoopCurrent & master)
constructor
Class constructor:
Parameters
[in] master the master object
Member Function Documentation
adjust_defect()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_defect (pot_vector_type & d, const pot_vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0, ConstSmartPtr< VectorTimeSeries< pot_vector_type > > vSol = SPNULL, const std::vector< number > * vScaleMass = NULL, const std::vector< number > * vScaleStiff = NULL) inline
sets a zero value in the defect for all conductor indices
References ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_vector(), and ug::IDomainConstraint< TDomain, TPotAlgebra >::dd().
adjust_jacobian()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_jacobian (pot_matrix_type & J, const pot_vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0, ConstSmartPtr< VectorTimeSeries< pot_vector_type > > vSol = SPNULL, const number s_a0 = 1.0) inline
sets a unity row for all conductor indices
References ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_matrix(), and ug::IDomainConstraint< TDomain, TPotAlgebra >::dd().
adjust_linear()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_linear (pot_matrix_type & A, pot_vector_type & b, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0) inline
sets unity rows in A and dirichlet values in right-hand side b
References ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_matrix(), ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_vector(), and ug::IDomainConstraint< TDomain, TPotAlgebra >::dd().
adjust_matrix()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_matrix (const DoFDistribution & vertDD, pot_matrix_type & A) private
sets to identity all the matrix rows that do not belong to the closure of the source subdomain
Sets to identity all the matrix rows that do not belong to the closure of the source subdomain
Parameters
vertDD the vertex DD
A the matrix to adjust
References ug::DoFDistribution::begin(), ug::DoFDistribution::end(), ug::DoFDistribution::inner_algebra_indices(), ug::SetDirichletRow(), and UG_THROW.
Referenced by ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_jacobian(), and ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_linear().
adjust_rhs()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_rhs (pot_vector_type & b, const pot_vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0) inline
sets the dirichlet value in the right-hand side
References ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_vector(), and ug::IDomainConstraint< TDomain, TPotAlgebra >::dd().
adjust_solution()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_solution (pot_vector_type & u, ConstSmartPtr< DoFDistribution > dd, int type, number time = 0.0) inline
sets the value in the solution for all conductor indices
References ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_vector(), and ug::IDomainConstraint< TDomain, TPotAlgebra >::dd().
adjust_vector()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_vector (const DoFDistribution & vertDD, pot_vector_type & u) private
sets to 0 all the entries of a vector that do not belong to the closure of the source subdomain
Sets to 0 all the entries of a vector that do not belong to the closure of the source subdomain
Parameters
vertDD the vertex DD
u the vector to adjust
References ug::DoFDistribution::begin(), ug::DoFDistribution::end(), ug::DoFDistribution::inner_algebra_indices(), and UG_THROW.
Referenced by ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_defect(), ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_linear(), ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_rhs(), and ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::adjust_solution().
init()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::init (domain_type * dom, a_vert_flag_type & a_in_source) inline
initializer
Parameters
[in] dom the domain
a_in_source the attachment for the flags
References AttachmentAccessor< Vertex, TAttachment >::access(), ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::m_in_source, ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::mark_source_vertices(), and PCL_RO_LOR.
mark_source_vertices()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::mark_source_vertices (const TDomain * dom) private
marks the vertices belonging to elements in the source (for all element types)
Marks the vertices belonging to elements in the source (for all element types)
Parameters
[in] dom the domain
References ug::MultiGrid::begin(), ug::MultiGrid::end(), and ug::SetAttachmentValues().
Referenced by ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::init().
mark_source_vertices_elem_type()
template<typename TDomain , typename TAlgebra > template<typename TElem > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::mark_source_vertices_elem_type (const TDomain * dom) private
marks the vertices belonging to elements in the source (for one element type)
Marks the vertices belonging to elements in the source (for one element type)
Parameters
[in] dom the domain
References ug::MultiGrid::num_levels().
set_zero_average()
template<typename TDomain , typename TAlgebra > void ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::set_zero_average (const DoFDistribution & vertDD, pot_vector_type & u)
sets the arithmetic average of the solution vector to zero
Sets the arithmetic average of the solution vector to zero
Parameters
vertDD the vertex DD
u the vector to adjust
References pcl::ProcessCommunicator::allreduce(), ug::DoFDistribution::begin(), ug::DoFDistribution::end(), ug::DoFDistribution::inner_algebra_indices(), PCL_RO_SUM, and UG_THROW.
type()
template<typename TDomain , typename TAlgebra > int ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::type () const inline virtual
returns the type of the constraints
Implements ug::IDomainConstraint< TDomain, TPotAlgebra >.
References ug::CT_DIRICHLET.
Member Data Documentation
m_in_source
template<typename TDomain , typename TAlgebra > aa_vert_flag_type ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::m_in_source private
attachment accessor for the current vertex flags
Referenced by ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::init().
m_master
template<typename TDomain , typename TAlgebra > NedelecLoopCurrent& ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::m_master private
the master object of the projection
maxCorners
template<typename TDomain , typename TAlgebra > const size_t ug::Electromagnetism::NedelecLoopCurrent< TDomain, TAlgebra >::OutOfSource::maxCorners = (size_t) element_list_traits<typename domain_traits<WDim>::DimElemList>::maxCorners static private
maximum number of corners of an element
The documentation for this class was generated from the following files:
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_source.h
/home/runner/work/docs/docs/ug4/plugins/Electromagnetism/nedelec_source_impl.h