Plugins: ug::promesh::MeshObject Class Reference
ug::promesh::MeshObject Class Reference
#include <mesh_object.h>
Public Types
typedef Grid::FaceAttachmentAccessor< normal_attachment_t > normal_accessor_t
typedef ANormal normal_attachment_t
typedef Grid::VertexAttachmentAccessor< position_attachment_t > position_accessor_t
typedef APosition position_attachment_t
typedef Grid::VolumeAttachmentAccessor< volume_constraint_attachment_t > volume_constraint_accessor_t
typedef ANumber volume_constraint_attachment_t
Public Member Functions
void clear_volume_constraints ()
clears the volume constraints (removes the attachment)
SubsetHandler & crease_handler ()
SubsetHandler & get_crease_handler ()
Grid & get_grid ()
const vector3 & get_pivot () const
Selector & get_selector ()
SubsetHandler & get_subset_handler ()
Grid & grid ()
MeshObject ()
normal_accessor_t & normal_accessor ()
returns accessor to face normals
normal_attachment_t & normal_attachment ()
vector3 & pivot ()
const vector3 & pivot () const
position_accessor_t & position_accessor ()
returns accessor to vertex positions
position_attachment_t & position_attachment ()
Selector & selector ()
void set_pivot (const vector3 &pivot)
SubsetHandler & subset_handler ()
volume_constraint_accessor_t & volume_constraint_accessor ()
returns accessor to volume constraints.
volume_constraint_attachment_t & volume_constraint_attachment ()
returns the volume constraint attachment
virtual ~MeshObject ()
Protected Member Functions
void volume_constraints_required ()
Protected Attributes
normal_accessor_t m_aaNorm
position_accessor_t m_aaPos
volume_constraint_accessor_t m_aaVolumeConstraint
volume_constraint_attachment_t m_aVolumeConstraint
SubsetHandler m_creaseHandler
Grid m_grid
vector3 m_pivot
Selector m_selector
SubsetHandler m_subsetHandler
Member Typedef Documentation
normal_accessor_t
typedef Grid::FaceAttachmentAccessor<normal_attachment_t> ug::promesh::MeshObject::normal_accessor_t
normal_attachment_t
typedef ANormal ug::promesh::MeshObject::normal_attachment_t
position_accessor_t
typedef Grid::VertexAttachmentAccessor<position_attachment_t> ug::promesh::MeshObject::position_accessor_t
position_attachment_t
typedef APosition ug::promesh::MeshObject::position_attachment_t
volume_constraint_accessor_t
typedef Grid::VolumeAttachmentAccessor<volume_constraint_attachment_t> ug::promesh::MeshObject::volume_constraint_accessor_t
volume_constraint_attachment_t
typedef ANumber ug::promesh::MeshObject::volume_constraint_attachment_t
Constructor & Destructor Documentation
MeshObject()
ug::promesh::MeshObject::MeshObject () inline
References AttachmentAccessor< Vertex, TAttachment >::access(), ug::aNormal, ug::aPosition, ug::Selector::assign_grid(), ug::GridSubsetHandler::assign_grid(), ug::Grid::attach_to_faces(), ug::Grid::attach_to_vertices(), ug::ISubsetHandler::enable_strict_inheritance(), m_aaNorm, m_aaPos, m_creaseHandler, m_grid, m_pivot, m_selector, m_subsetHandler, ug::SubsetInfo::name, ug::REM_CREASE, ug::REM_FIXED, and ug::ISubsetHandler::subset_info().
~MeshObject()
virtual ug::promesh::MeshObject::~MeshObject () inline virtual
Member Function Documentation
clear_volume_constraints()
void ug::promesh::MeshObject::clear_volume_constraints () inline
clears the volume constraints (removes the attachment)
References ug::Grid::detach_from_volumes(), ug::AttachmentAccessor< class, class, class >::invalidate(), m_aaVolumeConstraint, m_aVolumeConstraint, m_grid, and ug::AttachmentAccessor< class, class, class >::valid().
crease_handler()
SubsetHandler& ug::promesh::MeshObject::crease_handler () inline
References m_creaseHandler.
get_crease_handler()
SubsetHandler& ug::promesh::MeshObject::get_crease_handler () inline
References m_creaseHandler.
get_grid()
Grid& ug::promesh::MeshObject::get_grid () inline
References m_grid.
get_pivot()
const vector3& ug::promesh::MeshObject::get_pivot () const inline
References m_pivot.
get_selector()
Selector& ug::promesh::MeshObject::get_selector () inline
References m_selector.
get_subset_handler()
SubsetHandler& ug::promesh::MeshObject::get_subset_handler () inline
References m_subsetHandler.
grid()
Grid& ug::promesh::MeshObject::grid () inline
References m_grid.
normal_accessor()
normal_accessor_t& ug::promesh::MeshObject::normal_accessor () inline
returns accessor to face normals
References m_aaNorm.
normal_attachment()
normal_attachment_t& ug::promesh::MeshObject::normal_attachment () inline
References ug::aNormal.
pivot() [1/2]
vector3& ug::promesh::MeshObject::pivot () inline
References m_pivot.
Referenced by set_pivot().
pivot() [2/2]
const vector3& ug::promesh::MeshObject::pivot () const inline
References m_pivot.
position_accessor()
position_accessor_t& ug::promesh::MeshObject::position_accessor () inline
returns accessor to vertex positions
References m_aaPos.
position_attachment()
position_attachment_t& ug::promesh::MeshObject::position_attachment () inline
References ug::aPosition.
selector()
Selector& ug::promesh::MeshObject::selector () inline
References m_selector.
set_pivot()
void ug::promesh::MeshObject::set_pivot (const vector3 & pivot) inline
References m_pivot, and pivot().
subset_handler()
SubsetHandler& ug::promesh::MeshObject::subset_handler () inline
References m_subsetHandler.
volume_constraint_accessor()
volume_constraint_accessor_t& ug::promesh::MeshObject::volume_constraint_accessor () inline
returns accessor to volume constraints.
References m_aaVolumeConstraint, and volume_constraints_required().
volume_constraint_attachment()
volume_constraint_attachment_t& ug::promesh::MeshObject::volume_constraint_attachment () inline
returns the volume constraint attachment
References m_aVolumeConstraint, and volume_constraints_required().
volume_constraints_required()
void ug::promesh::MeshObject::volume_constraints_required () inline protected
References AttachmentAccessor< Volume, TAttachment >::access(), ug::Grid::attach_to_volumes(), m_aaVolumeConstraint, m_aVolumeConstraint, m_grid, and ug::AttachmentAccessor< class, class, class >::valid().
Referenced by volume_constraint_accessor(), and volume_constraint_attachment().
Member Data Documentation
m_aaNorm
normal_accessor_t ug::promesh::MeshObject::m_aaNorm protected
Referenced by MeshObject(), and normal_accessor().
m_aaPos
position_accessor_t ug::promesh::MeshObject::m_aaPos protected
Referenced by MeshObject(), and position_accessor().
m_aaVolumeConstraint
volume_constraint_accessor_t ug::promesh::MeshObject::m_aaVolumeConstraint protected
Referenced by clear_volume_constraints(), volume_constraint_accessor(), and volume_constraints_required().
m_aVolumeConstraint
volume_constraint_attachment_t ug::promesh::MeshObject::m_aVolumeConstraint protected
Referenced by clear_volume_constraints(), volume_constraint_attachment(), and volume_constraints_required().
m_creaseHandler
SubsetHandler ug::promesh::MeshObject::m_creaseHandler protected
Referenced by crease_handler(), get_crease_handler(), and MeshObject().
m_grid
Grid ug::promesh::MeshObject::m_grid protected
Referenced by clear_volume_constraints(), get_grid(), grid(), MeshObject(), and volume_constraints_required().
m_pivot
vector3 ug::promesh::MeshObject::m_pivot protected
Referenced by get_pivot(), MeshObject(), pivot(), and set_pivot().
m_selector
Selector ug::promesh::MeshObject::m_selector protected
Referenced by get_selector(), MeshObject(), and selector().
m_subsetHandler
SubsetHandler ug::promesh::MeshObject::m_subsetHandler protected
Referenced by get_subset_handler(), MeshObject(), and subset_handler().
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/ProMesh/mesh_object.h