Plugins: ug::NavierStokes::SeparatedPressureSource< TGridFunction > Class Template Reference
ug::NavierStokes::SeparatedPressureSource< TGridFunction > Class Template Reference
#include <pressure_separation.h>
Public Member Functions
virtual void compute (LocalVector *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
virtual void compute (LocalVectorTimeSeries *u, GridObject *elem, const MathVector< dim > vCornerCoords[], bool bDeriv=false)
virtual bool continuous () const
returns if provided data is continuous over geometric object boundaries
template<int refDim>
void evaluate (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< refDim, dim > *vJT=NULL) const
virtual void operator() (MathVector< dim > &value, const MathVector< dim > &globIP, number time, int si) const
virtual void operator() (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const
virtual bool requires_grid_fct () const
returns if grid function is needed for evaluation
SeparatedPressureSource (SmartPtr< ApproximationSpace< domain_type > > approxSpace, SmartPtr< TGridFunction > spGridFct)
constructor
void set_source (number f_x)
void set_source (number f_x, number f_y)
void set_source (number f_x, number f_y, number f_z)
void set_source (SmartPtr< CplUserData< MathVector< dim >, dim > > data)
void update ()
virtual ~SeparatedPressureSource ()
Public Member Functions inherited from ug::StdUserData< SeparatedPressureSource< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >
virtual TRet operator() (TData &value, const MathVector< TGridFunction::dim > &globIP, number time, int si) const =0
virtual void operator() (TData vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, const size_t nip) const =0
virtual void operator() (TData vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, TGridFunction::dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, TGridFunction::dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, TGridFunction::dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, TGridFunction::dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, TGridFunction::dim > *vJT=NULL) const
virtual void operator() (TData vValue[], const MathVector< TGridFunction::dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< TGridFunction::dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, TGridFunction::dim > *vJT=NULL) const
Public Member Functions inherited from ug::CplUserData< class, dim, class >
bool defined (size_t s, size_t ip) const
size_t num_ip (size_t s) const
size_t num_series () const
void register_storage_callback (DataImport< TData, dim > *obj, void(DataImport< TData, dim >::*func)())
void unregister_storage_callback (DataImport< TData, dim > *obj)
TData & value (size_t s, size_t ip)
const TData & value (size_t s, size_t ip) const
TData * values (size_t s)
const TData * values (size_t s) const
~CplUserData ()
Public Member Functions inherited from ug::ICplUserData< dim >
bool at_current_time (size_t s) const
virtual void check_setup () const
void clear ()
virtual bool constant () const
int dim_local_ips () const
ICplUserData ()
const MathVector< dim > & ip (size_t s, size_t ip) const
const MathVector< dim > * ips (size_t s) const
const MathVector< ldim > & local_ip (size_t s, size_t ip) const
const MathVector< ldim > * local_ips (size_t s) const
virtual SmartPtr< ICplUserData > needed_data (size_t i)
size_t num_ip (size_t s) const
virtual size_t num_needed_data () const
size_t num_series () const
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, bool bMayChange=true)
size_t register_local_ip_series (const MathVector< ldim > *vPos, const size_t numIP, const int timePointSpec, bool bMayChange=true)
void set_global_ips (size_t s, const MathVector< dim > *vPos, size_t numIP)
void set_local_ips (const size_t seriesId, const MathVector< ldim > *vPos, const size_t numIP)
void set_subset (int si)
void set_time_point (const size_t seriesId, const int timePointSpec)
void set_time_point (size_t timePoint)
void set_times (const std::vector< number > &vTime)
int subset () const
number time () const
number time (size_t s) const
size_t time_point ()
size_t time_point (size_t s) const
int time_point_specification (size_t s) const
virtual void update_dof_sizes (const LocalIndices &ind)
virtual bool zero_derivative () const
virtual ~ICplUserData ()
Public Member Functions inherited from ug::UserDataInfo
const FunctionGroup & function_group () const
const FunctionIndexMapping & map () const
size_t num_fct () const
virtual void set_function_pattern (ConstSmartPtr< FunctionPattern > fctPatt)
virtual ~UserDataInfo ()
Public Member Functions inherited from UserData< TData, dim, void >
int get_dim () const
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si) const =0
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > &locIP, LocalVector *u) const
virtual void operator() (TData &value, const MathVector< dim > &globIP, number time, int si, Vertex *vrt) const
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 1 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 1, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 2 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 2, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const =0
virtual void operator() (TData vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject *elem, const MathVector< dim > vCornerCoords[], const MathVector< 3 > vLocIP[], const size_t nip, LocalVector *u, const MathMatrix< 3, dim > *vJT=NULL) const =0
std::string type () const
Public Member Functions inherited from ug::INewtonUpdate
virtual ~INewtonUpdate ()
Private Types
typedef Grid::AttachmentAccessor< elem_type, ANumber > aElementNumber
typedef TGridFunction::algebra_type algebra_type
algebra type
typedef PeriodicAttachmentAccessor< Vertex, ANumber > aVertexNumber
MathVector<dim> attachment.
typedef TGridFunction::domain_type domain_type
domain type
typedef TGridFunction::template dim_traits< dim >::grid_base_object elem_type
element type
typedef TGridFunction::template dim_traits< dim >::const_iterator ElemIterator
element iterator
typedef domain_type::grid_type grid_type
grid type
typedef domain_type::position_accessor_type position_accessor_type
position accessor type
typedef TGridFunction::template traits< Vertex >::const_iterator VertexIterator
vertex iterator
Private Attributes
ANumber m_aP
ANumber m_aPOld
ANumber m_aVol
grid_type * m_grid
SmartPtr< CplUserData< MathVector< dim >, dim > > m_imSource
Data import for source.
aVertexNumber m_p
aElementNumber m_pOld
SmartPtr< ApproximationSpace< domain_type > > m_spApproxSpace
SmartPtr< TGridFunction > m_u
aVertexNumber m_vol
Static Private Attributes
static const size_t _P_ = dim
static const int dim = domain_type::dim
world dimension
static const size_t max_number_of_ips = 20
Additional Inherited Members
Public Types inherited from ug::CplUserData< class, dim, class >
typedef ICplUserData< dim > base_type
Public Types inherited from UserData< TData, dim, void >
typedef TData data_type
typedef void return_type
Protected Member Functions inherited from ug::StdUserData< SeparatedPressureSource< TGridFunction >, MathVector< TGridFunction::dim >, TGridFunction::dim >
TImpl & getImpl ()
const TImpl & getImpl () const
Protected Member Functions inherited from ug::CplUserData< class, dim, class >
void call_storage_callback () const
void check_series (size_t s) const
void check_series_ip (size_t s, size_t ip) const
virtual void local_ip_series_added (const size_t seriesID)
virtual void local_ip_series_to_be_cleared ()
virtual void local_ips_changed (const size_t seriesID, const size_t newNumIP)
virtual void value_storage_changed (const size_t seriesID)
Protected Member Functions inherited from ug::ICplUserData< dim >
void check_s (size_t s) const
void check_s_ip (size_t s, size_t ip) const
std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >)
const std::vector< const MathVector< 1 > * > & get_local_ips (Int2Type< 1 >) const
std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >)
const std::vector< const MathVector< 2 > * > & get_local_ips (Int2Type< 2 >) const
std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >)
const std::vector< const MathVector< 3 > * > & get_local_ips (Int2Type< 3 >) const
virtual void global_ips_changed (const size_t seriesID, const MathVector< dim > *vPos, const size_t numIP)
Protected Attributes inherited from ug::ICplUserData< dim >
int m_defaultTimePoint
int m_locPosDim
std::vector< const MathVector< 1 > * > m_pvLocIP1d
std::vector< const MathVector< 2 > * > m_pvLocIP2d
std::vector< const MathVector< 3 > * > m_pvLocIP3d
int m_si
size_t m_timePoint
std::vector< bool > m_vMayChange
std::vector< size_t > m_vNumIP
std::vector< number > m_vTime
std::vector< int > m_vTimePoint
std::vector< const MathVector< dim > * > m_vvGlobPos
Protected Attributes inherited from ug::UserDataInfo
FunctionGroup m_fctGrp
FunctionIndexMapping m_map
Detailed Description
template<typename TGridFunction>
class ug::NavierStokes::SeparatedPressureSource< TGridFunction >
concept derived from grid_function_user_data.h
Member Typedef Documentation
aElementNumber
template<typename TGridFunction > typedef Grid::AttachmentAccessor<elem_type,ANumber > ug::NavierStokes::SeparatedPressureSource< TGridFunction >::aElementNumber private
algebra_type
template<typename TGridFunction > typedef TGridFunction::algebra_type ug::NavierStokes::SeparatedPressureSource< TGridFunction >::algebra_type private
algebra type
aVertexNumber
template<typename TGridFunction > typedef PeriodicAttachmentAccessor<Vertex,ANumber > ug::NavierStokes::SeparatedPressureSource< TGridFunction >::aVertexNumber private
MathVector<dim> attachment.
attachment accessor
domain_type
template<typename TGridFunction > typedef TGridFunction::domain_type ug::NavierStokes::SeparatedPressureSource< TGridFunction >::domain_type private
domain type
elem_type
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::grid_base_object ug::NavierStokes::SeparatedPressureSource< TGridFunction >::elem_type private
element type
ElemIterator
template<typename TGridFunction > typedef TGridFunction::template dim_traits<dim>::const_iterator ug::NavierStokes::SeparatedPressureSource< TGridFunction >::ElemIterator private
element iterator
grid_type
template<typename TGridFunction > typedef domain_type::grid_type ug::NavierStokes::SeparatedPressureSource< TGridFunction >::grid_type private
grid type
position_accessor_type
template<typename TGridFunction > typedef domain_type::position_accessor_type ug::NavierStokes::SeparatedPressureSource< TGridFunction >::position_accessor_type private
position accessor type
VertexIterator
template<typename TGridFunction > typedef TGridFunction::template traits<Vertex>::const_iterator ug::NavierStokes::SeparatedPressureSource< TGridFunction >::VertexIterator private
vertex iterator
Constructor & Destructor Documentation
SeparatedPressureSource()
template<typename TGridFunction > ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource (SmartPtr< ApproximationSpace< domain_type > > approxSpace, SmartPtr< TGridFunction > spGridFct) inline
constructor
References ug::PeriodicAttachmentAccessor< class, class >::access(), SmartPtr< TGridFunction >::get(), grid(), ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_aP, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_aPOld, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_aVol, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_grid, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_p, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_pOld, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_spApproxSpace, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_u, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_vol, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source(), ug::SetAttachmentValues(), and ug::NavierStokes::SeparatedPressureSource< TGridFunction >::update().
~SeparatedPressureSource()
template<typename TGridFunction > virtual ug::NavierStokes::SeparatedPressureSource< TGridFunction >::~SeparatedPressureSource () inline virtual
Member Function Documentation
compute() [1/2]
template<typename TGridFunction > virtual void ug::NavierStokes::SeparatedPressureSource< TGridFunction >::compute (LocalVector * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) inline virtual
Implements ug::ICplUserData< dim >.
References ug::ICplUserData< dim >::ips(), ug::CplUserData< class, dim, class >::num_ip(), ug::CplUserData< class, dim, class >::num_series(), s, ug::ICplUserData< dim >::subset(), ug::ICplUserData< dim >::time(), and ug::CplUserData< class, dim, class >::values().
compute() [2/2]
template<typename TGridFunction > virtual void ug::NavierStokes::SeparatedPressureSource< TGridFunction >::compute (LocalVectorTimeSeries * u, GridObject * elem, const MathVector< dim > vCornerCoords[], bool bDeriv = false) inline virtual
Implements ug::ICplUserData< dim >.
References ug::ICplUserData< dim >::ips(), ug::CplUserData< class, dim, class >::num_ip(), ug::CplUserData< class, dim, class >::num_series(), s, ug::LocalVectorTimeSeries::solution(), ug::ICplUserData< dim >::subset(), ug::ICplUserData< dim >::time(), ug::ICplUserData< dim >::time_point(), and ug::CplUserData< class, dim, class >::values().
continuous()
template<typename TGridFunction > virtual bool ug::NavierStokes::SeparatedPressureSource< TGridFunction >::continuous () const inline virtual
returns if provided data is continuous over geometric object boundaries
Implements UserData< TData, dim, void >.
evaluate()
template<typename TGridFunction > template<int refDim> void ug::NavierStokes::SeparatedPressureSource< TGridFunction >::evaluate (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, GridObject * elem, const MathVector< dim > vCornerCoords[], const MathVector< refDim > vLocIP[], const size_t nip, LocalVector * u, const MathMatrix< refDim, dim > * vJT = NULL) const inline
References ug::NavierStokes::SeparatedPressureSource< TGridFunction >::dim, ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::from(), SmartPtr< TGridFunction >::get(), ug::ICplUserData< dim >::ip(), ug::LFEID::LAGRANGE, ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::local_ip(), ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_p, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_u, ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::normal(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scv(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scvf(), ug::GridObject::reference_object_id(), ug::DimCRFVGeometry< TDim, TWorldDim >::scv(), ug::DimCRFVGeometry< TDim, TWorldDim >::scvf(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), ug::ICplUserData< dim >::time(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCVF::to(), UG_ASSERT, ug::DimCRFVGeometry< TDim, TWorldDim >::update(), and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::volume().
operator()() [1/2]
template<typename TGridFunction > virtual void ug::NavierStokes::SeparatedPressureSource< TGridFunction >::operator() (MathVector< dim > & value, const MathVector< dim > & globIP, number time, int si) const inline virtual
References UG_THROW.
operator()() [2/2]
template<typename TGridFunction > virtual void ug::NavierStokes::SeparatedPressureSource< TGridFunction >::operator() (MathVector< dim > vValue[], const MathVector< dim > vGlobIP[], number time, int si, const size_t nip) const inline virtual
References UG_THROW.
requires_grid_fct()
template<typename TGridFunction > virtual bool ug::NavierStokes::SeparatedPressureSource< TGridFunction >::requires_grid_fct () const inline virtual
returns if grid function is needed for evaluation
Implements UserData< TData, dim, void >.
set_source() [1/4]
template<typename TGridFunction > void ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source (number f_x) inline
References ug::NavierStokes::SeparatedPressureSource< TGridFunction >::dim, and ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source().
set_source() [2/4]
template<typename TGridFunction > void ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source (number f_x, number f_y) inline
References ug::NavierStokes::SeparatedPressureSource< TGridFunction >::dim, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source(), and UG_THROW.
set_source() [3/4]
template<typename TGridFunction > void ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source (number f_x, number f_y, number f_z) inline
References ug::NavierStokes::SeparatedPressureSource< TGridFunction >::dim, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source(), and UG_THROW.
set_source() [4/4]
template<typename TGridFunction > void ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source (SmartPtr< CplUserData< MathVector< dim >, dim > > data) inline
References ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_imSource.
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource(), and ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source().
update()
template<typename TGridFunction > void ug::NavierStokes::SeparatedPressureSource< TGridFunction >::update () inline virtual
Implements ug::INewtonUpdate.
References ug::NavierStokes::SeparatedPressureSource< TGridFunction >::_P_, ug::DoFRef(), SmartPtr< TGridFunction >::get(), ug::PeriodicBoundaryManager::is_slave(), ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_p, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_pOld, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_u, ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_vol, num_subsets(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), ug::SetAttachmentValues(), ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource().
Member Data Documentation
_P_
template<typename TGridFunction > const size_t ug::NavierStokes::SeparatedPressureSource< TGridFunction >::_P_ = dim static private
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::update().
dim
template<typename TGridFunction > const int ug::NavierStokes::SeparatedPressureSource< TGridFunction >::dim = domain_type::dim static private
world dimension
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::evaluate(), and ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source().
m_aP
template<typename TGridFunction > ANumber ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_aP private
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource().
m_aPOld
template<typename TGridFunction > ANumber ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_aPOld private
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource().
m_aVol
template<typename TGridFunction > ANumber ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_aVol private
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource().
m_grid
template<typename TGridFunction > grid_type* ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_grid private
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource().
m_imSource
template<typename TGridFunction > SmartPtr<CplUserData<MathVector<dim>,dim> > ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_imSource private
Data import for source.
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::set_source().
m_p
template<typename TGridFunction > aVertexNumber ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_p private
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::evaluate(), ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource(), and ug::NavierStokes::SeparatedPressureSource< TGridFunction >::update().
m_pOld
template<typename TGridFunction > aElementNumber ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_pOld private
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource(), and ug::NavierStokes::SeparatedPressureSource< TGridFunction >::update().
m_spApproxSpace
template<typename TGridFunction > SmartPtr<ApproximationSpace<domain_type> > ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_spApproxSpace private
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource().
m_u
template<typename TGridFunction > SmartPtr<TGridFunction> ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_u private
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::evaluate(), ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource(), and ug::NavierStokes::SeparatedPressureSource< TGridFunction >::update().
m_vol
template<typename TGridFunction > aVertexNumber ug::NavierStokes::SeparatedPressureSource< TGridFunction >::m_vol private
Referenced by ug::NavierStokes::SeparatedPressureSource< TGridFunction >::SeparatedPressureSource(), and ug::NavierStokes::SeparatedPressureSource< TGridFunction >::update().
max_number_of_ips
template<typename TGridFunction > const size_t ug::NavierStokes::SeparatedPressureSource< TGridFunction >::max_number_of_ips = 20 static private
The documentation for this class was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/fvcr/pressure_separation.h