Plugins: Apps_ugdocu
Apps_ugdocu
Classes
class ug::DocuGen::CppGenerator
Generator to produce valid but dummy C++ files from registered classes and functions.
class ug::DocuGen::UGRegistryGroup
Functions
void ug::DocuGen::AddLuaDebugCompletions (ostream &f)
bool ug::DocuGen::ClassGroupDescSort (const ClassGroupDesc *i, const ClassGroupDesc *j)
std::string ug::DocuGen::ConstructorInfoHTML (std::string classname, const bridge::ExportedConstructor &thefunc, std::string group)
bool ug::DocuGen::ExportedClassSort (const IExportedClass *i, const IExportedClass *j)
bool ug::DocuGen::ExportedFunctionsGroupSort (const bridge::ExportedFunction *i, const bridge::ExportedFunction *j)
bool ug::DocuGen::ExportedFunctionsSort (const bridge::ExportedFunctionBase *i, const bridge::ExportedFunctionBase *j)
string ug::DocuGen::FunctionInfoHTML (const bridge::ExportedFunctionBase &thefunc, const char *group)
string ug::DocuGen::FunctionInfoHTML (const bridge::ExportedFunctionBase &thefunc, const IExportedClass *c, bool bConst)
std::string ug::DocuGen::GetBeautifiedTag (std::string tag)
std::string ug::DocuGen::GetFilenameForGroup (std::string s, std::string dir="")
bool ug::DocuGen::IsPluginGroup (std::string g)
void ug::DocuGen::ParameterToString (std::ostream &file, const bridge::ParameterInfo &par, int i, bool bHTML)
void ug::DocuGen::PrintClassFunctionsHMTL (std::ostream &file, const bridge::IExportedClass *c, bool bInherited)
std::string ug::DocuGen::tohtmlstring (const std::string &str)
void ug::DocuGen::WriteClassCompleter (ostream &classhtml, UGDocuClassDescription *d, ClassHierarchy &hierarchy)
void ug::DocuGen::WriteClassHierarchy (const char *dir, ClassHierarchy &hierarchy)
void ug::DocuGen::WriteClassHierarchy (std::ostream &file, bridge::ClassHierarchy &c)
void ug::DocuGen::WriteClassHTML (const char *dir, UGDocuClassDescription *d, ClassHierarchy &hierarchy)
void ug::DocuGen::WriteClassIndex (const char *dir, std::vector< UGDocuClassDescription > &classesAndGroups, bool bGroup)
bool ug::DocuGen::WriteClassUsageExact (const std::string &preamble, std::ostream &file, const char *classname, bool OutParameters)
void ug::DocuGen::WriteCompletionList (std::vector< UGDocuClassDescription > classesAndGroupsAndImplementations, bool bSilent)
void ug::DocuGen::WriteConstructorCompleter (ostream &f, string classname, const bridge::ExportedConstructor &thefunc, string group)
void ug::DocuGen::WriteFooter (std::fstream &file)
void ug::DocuGen::WriteFunctionCompleter (ostream &f, const char *desc, const bridge::ExportedFunctionBase &thefunc, string group, const char *pClass=NULL, bool bConst=false)
void ug::DocuGen::WriteFunctionHTMLCompleter (ostream &file, const bridge::ExportedFunctionBase &thefunc, const char *group, const char *pClass)
void ug::DocuGen::WriteHeader (std::fstream &file, const std::string &title)
void ug::DocuGen::WriteHTMLDocu (std::vector< UGDocuClassDescription > &classes, std::vector< UGDocuClassDescription > &classesAndGroups, const char *dir, ClassHierarchy &hierarchy)
template<typename T >
static void ug::DocuGen::WriteParametersIn (std::ostream &file, const T &thefunc, bool bHTML=true)
template<typename T >
static void ug::DocuGen::WriteParametersOut (std::ostream &file, const T &thefunc, bool bHTML=true)
void ug::DocuGen::WriteUGDocuCSS (const char *dir)
Detailed Description
Function Documentation
AddLuaDebugCompletions()
void ug::DocuGen::AddLuaDebugCompletions (ostream & f)
References ug::DebugIDManager::get_registered_debug_IDs_arr(), instance(), s, and UG_CATCH_THROW_FUNC.
Referenced by ug::DocuGen::WriteCompletionList().
ClassGroupDescSort()
bool ug::DocuGen::ClassGroupDescSort (const ClassGroupDesc * i, const ClassGroupDesc * j)
References ug::bridge::ClassGroupDesc::name().
ConstructorInfoHTML()
std::string ug::DocuGen::ConstructorInfoHTML (std::string classname, const bridge::ExportedConstructor & thefunc, std::string group)
ExportedClassSort()
bool ug::DocuGen::ExportedClassSort (const IExportedClass * i, const IExportedClass * j)
References ug::bridge::IExportedClass::name().
ExportedFunctionsGroupSort()
bool ug::DocuGen::ExportedFunctionsGroupSort (const bridge::ExportedFunction * i, const bridge::ExportedFunction * j)
References ug::bridge::ExportedFunction::group(), and ug::bridge::ExportedFunctionBase::name().
Referenced by ug::DocuGen::WriteHTMLDocu().
ExportedFunctionsSort()
bool ug::DocuGen::ExportedFunctionsSort (const bridge::ExportedFunctionBase * i, const bridge::ExportedFunctionBase * j)
References ug::bridge::ExportedFunctionBase::name().
Referenced by ug::DocuGen::GetGroups(), ug::DocuGen::PrintClassFunctionsHMTL(), and ug::DocuGen::WriteHTMLDocu().
FunctionInfoHTML() [1/2]
std::string ug::DocuGen::FunctionInfoHTML (const bridge::ExportedFunctionBase & thefunc, const char * group)
References ug::bridge::ExportedFunctionBase::help(), ug::bridge::ExportedFunctionBase::name(), ug::bridge::ExportedFunctionBase::return_name(), ug::bridge::ExportedFunctionBase::tooltip(), UG_CATCH_THROW_FUNC, ug::DocuGen::WriteParametersIn(), ug::DocuGen::WriteParametersOut(), and XMLStringEscape().
Referenced by ug::DocuGen::PrintClassFunctionsHMTL(), ug::DocuGen::WriteClassUsageExact(), ug::DocuGen::WriteGlobalFunctions(), and ug::DocuGen::WriteGroups().
FunctionInfoHTML() [2/2]
std::string ug::DocuGen::FunctionInfoHTML (const bridge::ExportedFunctionBase & thefunc, const IExportedClass * c, bool bConst)
References ug::DocuGen::GetClassGroup(), ug::bridge::ExportedFunctionBase::help(), ug::bridge::ExportedFunctionBase::name(), ug::bridge::IExportedClass::name(), ug::bridge::ExportedFunctionBase::return_name(), ug::bridge::ExportedFunctionBase::tooltip(), UG_CATCH_THROW_FUNC, ug::DocuGen::WriteParametersIn(), ug::DocuGen::WriteParametersOut(), and XMLStringEscape().
GetBeautifiedTag()
std::string ug::DocuGen::GetBeautifiedTag (std::string tag)
GetFilenameForGroup()
std::string ug::DocuGen::GetFilenameForGroup (std::string s, std::string dir = "")
IsPluginGroup()
bool ug::DocuGen::IsPluginGroup (std::string g)
ParameterToString()
void ug::DocuGen::ParameterToString (std::ostream & file, const bridge::ParameterInfo & par, int i, bool bHTML)
PrintClassFunctionsHMTL()
void ug::DocuGen::PrintClassFunctionsHMTL (std::ostream & file, const bridge::IExportedClass * c, bool bInherited)
tohtmlstring()
std::string ug::DocuGen::tohtmlstring (const std::string & str)
WriteClassCompleter()
void ug::DocuGen::WriteClassCompleter (ostream & classhtml, UGDocuClassDescription * d, ClassHierarchy & hierarchy)
References ug::bridge::IExportedClass::class_names(), ug::bridge::Registry::get_class(), ug::bridge::ClassGroupDesc::get_default_class(), GetUGRegistry(), ug::bridge::IExportedClass::group(), ug::bridge::IExportedClass::is_instantiable(), ug::DocuGen::UGDocuClassDescription::mp_class, ug::DocuGen::UGDocuClassDescription::mp_group, ug::bridge::ClassGroupDesc::name(), ug::bridge::IExportedClass::name(), ug::DocuGen::PrintClassFunctionsHMTL(), ug::DocuGen::UGDocuClassDescription::tag, ug::bridge::IExportedClass::tooltip(), UG_CATCH_THROW_FUNC, and ug::DocuGen::WriteClassUsageExact().
Referenced by ug::DocuGen::WriteCompletionList().
WriteClassHierarchy() [1/2]
void ug::DocuGen::WriteClassHierarchy (const char * dir, ClassHierarchy & hierarchy)
References ug::bridge::ClassHierarchy::subclasses, UG_CATCH_THROW_FUNC, ug::DocuGen::WriteFooter(), and ug::DocuGen::WriteHeader().
Referenced by ug::DocuGen::WriteClassHTML(), and ug::DocuGen::WriteHTMLDocu().
WriteClassHierarchy() [2/2]
void ug::DocuGen::WriteClassHierarchy (std::ostream & file, bridge::ClassHierarchy & c)
WriteClassHTML()
void ug::DocuGen::WriteClassHTML (const char * dir, UGDocuClassDescription * d, ClassHierarchy & hierarchy)
References ug::bridge::IExportedClass::class_names(), ug::bridge::ClassHierarchy::find_class(), ug::bridge::Registry::get_class(), ug::bridge::ClassGroupDesc::get_class(), ug::bridge::ClassGroupDesc::get_class_tag(), ug::bridge::ClassGroupDesc::get_default_class(), ug::DocuGen::GetBeautifiedTag(), ug::DocuGen::GetClassGroup(), ug::DocuGen::GetFilenameForGroup(), GetUGRegistry(), ug::bridge::IExportedClass::group(), ug::bridge::IExportedClass::is_instantiable(), ug::DocuGen::UGDocuClassDescription::mp_class, ug::DocuGen::UGDocuClassDescription::mp_group, ug::bridge::ClassGroupDesc::name(), ug::bridge::IExportedClass::name(), ug::bridge::ClassGroupDesc::num_classes(), ug::DocuGen::PrintClassFunctionsHMTL(), ug::bridge::ClassHierarchy::subclasses, ug::DocuGen::UGDocuClassDescription::tag, ug::bridge::IExportedClass::tooltip(), UG_CATCH_THROW_FUNC, ug::DocuGen::WriteClassHierarchy(), ug::DocuGen::WriteClassUsageExact(), ug::DocuGen::WriteFooter(), ug::DocuGen::WriteHeader(), and XMLStringEscape().
Referenced by ug::DocuGen::WriteHTMLDocu().
WriteClassIndex()
void ug::DocuGen::WriteClassIndex (const char * dir, std::vector< UGDocuClassDescription > & classesAndGroups, bool bGroup)
References ug::DocuGen::classesAndGroups, ug::bridge::ClassGroupDesc::get_default_class(), ug::DocuGen::UGDocuClassDescription::group_str(), ug::DocuGen::GroupNameSortFunction(), ug::DocuGen::UGDocuClassDescription::mp_class, ug::DocuGen::UGDocuClassDescription::mp_group, ug::DocuGen::UGDocuClassDescription::name(), ug::bridge::ClassGroupDesc::name(), ug::bridge::IExportedClass::name(), ug::DocuGen::NameSortFunction(), UG_CATCH_THROW_FUNC, UG_LOG, ug::DocuGen::WriteFooter(), and ug::DocuGen::WriteHeader().
Referenced by ug::DocuGen::WriteHTMLDocu().
WriteClassUsageExact()
bool ug::DocuGen::WriteClassUsageExact (const std::string & preamble, std::ostream & file, const char * classname, bool OutParameters)
WriteCompletionList()
void ug::DocuGen::WriteCompletionList (std::vector< UGDocuClassDescription > classesAndGroupsAndImplementations, bool bSilent)
Referenced by ug::GenerateScriptReferenceDocu().
WriteConstructorCompleter()
void ug::DocuGen::WriteConstructorCompleter (ostream & f, string classname, const bridge::ExportedConstructor & thefunc, string group)
References ug::bridge::ExportedConstructor::help(), ug::bridge::ExportedConstructor::tooltip(), UG_CATCH_THROW_FUNC, and ug::DocuGen::WriteParametersIn().
Referenced by ug::DocuGen::WriteCompletionList().
WriteFooter()
void ug::DocuGen::WriteFooter (std::fstream & file)
WriteFunctionCompleter()
void ug::DocuGen::WriteFunctionCompleter (ostream & f, const char * desc, const bridge::ExportedFunctionBase & thefunc, string group, const char * pClass = NULL, bool bConst = false)
References ug::bridge::ExportedFunctionBase::name(), ParameterToString(), ug::bridge::ExportedFunctionBase::params_out(), ug::bridge::ParameterInfo::size(), UG_CATCH_THROW_FUNC, ug::DocuGen::WriteFunctionHTMLCompleter(), ug::DocuGen::WriteParametersIn(), and ug::DocuGen::WriteParametersOut().
Referenced by ug::DocuGen::WriteCompletionList().
WriteFunctionHTMLCompleter()
void ug::DocuGen::WriteFunctionHTMLCompleter (ostream & file, const bridge::ExportedFunctionBase & thefunc, const char * group, const char * pClass)
References ug::bridge::ExportedFunctionBase::help(), ug::bridge::ExportedFunctionBase::name(), ug::bridge::ExportedFunctionBase::return_name(), ug::bridge::ExportedFunctionBase::tooltip(), UG_CATCH_THROW_FUNC, ug::DocuGen::WriteParametersIn(), and ug::DocuGen::WriteParametersOut().
Referenced by ug::DocuGen::WriteFunctionCompleter().
WriteHeader()
void ug::DocuGen::WriteHeader (std::fstream & file, const std::string & title)
WriteHTMLDocu()
void ug::DocuGen::WriteHTMLDocu (std::vector< UGDocuClassDescription > & classes, std::vector< UGDocuClassDescription > & classesAndGroups, const char * dir, ClassHierarchy & hierarchy)
References ug::DocuGen::classes, ug::DocuGen::classesAndGroups, ug::DocuGen::ExportedFunctionsGroupSort(), ug::DocuGen::ExportedFunctionsSort(), ug::bridge::Registry::get_class(), ug::DocuGen::GetUGDocuClassDescription(), GetUGRegistry(), ug::bridge::Registry::num_classes(), UG_CATCH_THROW_FUNC, UG_LOG, ug::DocuGen::WriteClassHierarchy(), ug::DocuGen::WriteClassHTML(), ug::DocuGen::WriteClassIndex(), ug::DocuGen::WriteGlobalFunctions(), ug::DocuGen::WriteGroups(), and ug::DocuGen::WriteUGDocuCSS().
Referenced by ug::GenerateScriptReferenceDocu().
WriteParametersIn()
template<typename T > static void ug::DocuGen::WriteParametersIn (std::ostream & file, const T & thefunc, bool bHTML = true) static
References ug::DocuGen::ParameterToString().
Referenced by ug::DocuGen::ConstructorInfoHTML(), ug::DocuGen::FunctionInfoHTML(), ug::DocuGen::WriteConstructorCompleter(), ug::DocuGen::WriteFunctionCompleter(), and ug::DocuGen::WriteFunctionHTMLCompleter().
WriteParametersOut()
template<typename T > static void ug::DocuGen::WriteParametersOut (std::ostream & file, const T & thefunc, bool bHTML = true) static
References ug::DocuGen::ParameterToString().
Referenced by ug::DocuGen::FunctionInfoHTML(), ug::DocuGen::WriteFunctionCompleter(), and ug::DocuGen::WriteFunctionHTMLCompleter().
WriteUGDocuCSS()
void ug::DocuGen::WriteUGDocuCSS (const char * dir)
References UG_CATCH_THROW_FUNC, UG_LOG, ugdocu_css, and ugdocu_css_len.
Referenced by ug::DocuGen::WriteHTMLDocu().