Plugins: Jupyter
Jupyter
Plugins
Classes
struct ug::Jupyter::Functionality
struct ug::Jupyter::XWidgetRegistryFacade< XWidget >
Functions
void ug::Jupyter::CrashFct (const string &reason)
void ug::Jupyter::CrashFctFatal (const string &reason)
void ug::Jupyter::XWidgetsCrashes ()
void ug::Jupyter::XWidgetsCrashesFatal ()
void ug::Jupyter::XWidgetsSaysHello ()
Detailed Description
This is a small sample plugin.
Function Documentation
CrashFct()
void ug::Jupyter::CrashFct (const string & reason)
References UG_THROW.
Referenced by ug::Jupyter::XWidgetsCrashes().
CrashFctFatal()
void ug::Jupyter::CrashFctFatal (const string & reason)
References UG_THROW.
Referenced by ug::Jupyter::XWidgetsCrashesFatal().
XWidgetsCrashes()
void ug::Jupyter::XWidgetsCrashes ()
References ug::Jupyter::CrashFct(), UG_CATCH_THROW, and UG_LOG.
Referenced by ug::Jupyter::Functionality::Common().
XWidgetsCrashesFatal()
void ug::Jupyter::XWidgetsCrashesFatal ()
References ug::Jupyter::CrashFctFatal(), UG_CATCH_THROW, and UG_LOG.
Referenced by ug::Jupyter::Functionality::Common().
XWidgetsSaysHello()
void ug::Jupyter::XWidgetsSaysHello ()
References pcl::ProcRank(), pcl::SynchronizeProcesses(), and UG_LOG.
Referenced by ug::Jupyter::Functionality::Common().