Plugins: ProMesh
ProMesh
Plugins
Classes
class ug::promesh::Box
class ug::promesh::Mesh
class ug::promesh::ProMeshRegistry
Register functions for ug-script and ProMesh through this class.
Enumerations
enum ug::promesh::CSGOperation { ug::promesh::CSG_UNION , ug::promesh::CSG_INTERSECTION , ug::promesh::CSG_DIFFERENCE }
enum ug::promesh::RegistryTargets {
ug::promesh::RT_NONE = 0 , ug::promesh::RT_UGSCRIPT = 1 , ug::promesh::RT_PROMESH = 1 << 1 , ug::promesh::RT_DEFAULT = RT_UGSCRIPT | RT_PROMESH ,
ug::promesh::RT_NO_PROMESH = RT_UGSCRIPT , ug::promesh::RT_NO_UGSCRIPT = RT_PROMESH
}
Functions
void ug::promesh::AdaptSurfaceToCylinder (Mesh *obj, number radius, number threshold)
void ug::promesh::AdjustEdgeLength (Mesh *obj, number minEdgeLen, number maxEdgeLen, int numIterations, bool adaptive, bool automarkBoundaries)
void ug::promesh::AdjustEdgeLengthExtended (Mesh *obj, number minEdgeLen, number maxEdgeLen, number approximation, number triQuality, int numIterations, bool automarkBoundaries)
void ug::promesh::AdjustEdgeOrientation (Mesh *obj)
void ug::promesh::AdjustSubsetsForUG3 (Mesh *obj, bool keepIntfSubs)
void ug::promesh::AdjustSubsetsForUG4 (Mesh *obj, bool preserveExistingSubsets)
void ug::promesh::AssignNewSubset (Mesh *obj, const char *name, bool vertices, bool edges, bool faces, bool volumes)
void ug::promesh::AssignSubset (Mesh *obj, int newIndex)
void ug::promesh::AssignSubset (Mesh *obj, int newIndex, bool vertices, bool edges, bool faces, bool volumes)
void ug::promesh::AssignSubsetColors (Mesh *obj)
template<class elem_t >
void ug::promesh::AssignSubsetsByAspectRatio (Mesh *msh, int numHistoSecs, bool eraseOldSubsets)
void ug::promesh::AssignSubsetsByElementType (Mesh *obj)
void ug::promesh::AssignSubsetsByQuality (Mesh *obj, int numSections)
void ug::promesh::AssignSubsetsFromRaster (Mesh *obj, const char *rasterFileName, int rasterDimension, bool vertices, bool edges, bool faces, bool volumes)
void ug::promesh::AssignVolumeConstraints (Mesh *obj, number volConstraint)
void ug::promesh::ClearMarks (Mesh *obj)
void ug::promesh::ClearSelection (Mesh *obj)
void ug::promesh::ClearVolumeConstraints (Mesh *obj)
SmartPtr< Mesh > ug::promesh::CloneMesh (Mesh *mesh)
void ug::promesh::CloseSelection (Mesh *obj)
void ug::promesh::CollapseEdge (Mesh *obj)
void ug::promesh::ConeTransform (Mesh *obj, const vector3 &base, const vector3 &axis, number scaleAtTip)
void ug::promesh::ConvertToQuadrilaterals (Mesh *obj)
void ug::promesh::ConvertToTetrahedra (Mesh *obj)
void ug::promesh::ConvertToTriangles (Mesh *obj)
void ug::promesh::CopySelection (Mesh *srcMesh, Mesh *destMesh)
void ug::promesh::CopySubsetIndicesToSides (Mesh *obj, bool selectionOnly, bool toUnassignedOnly)
void ug::promesh::CreateBox (Mesh *obj, const vector3 &boxMin, const vector3 &boxMax, int subsetInd, bool fill)
void ug::promesh::CreateCircle (Mesh *obj, const vector3 &center, number radius, int numRimVertices, int subsetInd, bool fill)
Edge * ug::promesh::CreateEdge (Mesh *obj, int subsetInd)
Face * ug::promesh::CreateFace (Mesh *obj, int subsetInd)
void ug::promesh::CreateHexahedraFromSelectedPrisms (Mesh *obj)
void ug::promesh::CreatePlane (Mesh *obj, const vector3 &upLeft, const vector3 &upRight, const vector3 &lowLeft, const vector3 &lowRight, int subsetInd, bool fill)
void ug::promesh::CreatePlane (Mesh *obj, number width, number height, const vector3 &center, int subsetInd, bool fill)
void ug::promesh::CreatePrism (Mesh *obj, int subsetInd, bool fill)
void ug::promesh::CreatePyramid (Mesh *obj, int subsetInd, bool fill)
template<class TElemIter >
void ug::promesh::CreateShrinkElements (Mesh *obj, number scale, TElemIter elemsBegin, TElemIter elemsEnd)
void ug::promesh::CreateShrinkGeometry (Mesh *obj, number scale)
void ug::promesh::CreateSphere (Mesh *obj, const vector3 &center, number radius, int numRefinements, int subsetInd)
void ug::promesh::CreateTetrahedron (Mesh *obj, int subsetInd, bool fill)
void ug::promesh::CreateTKD (Mesh *obj, int subsetInd, number a, number w, number h)
void ug::promesh::CreateTKDWithOuterLayer (Mesh *obj, int innerSubsetInd, int outerSubsetInd, number a, number w, number h, number d)
Vertex * ug::promesh::CreateVertex (Mesh *obj, const vector3 &pos, int subsetInd)
Volume * ug::promesh::CreateVolume (Mesh *obj, int subsetInd)
void ug::promesh::CSGFaceDifference (Mesh *obj, int subsetIndex0, int subsetIndex1, number snapThreshold)
void ug::promesh::CSGFaceIntersection (Mesh *obj, int subsetIndex0, int subsetIndex1, number snapThreshold)
void ug::promesh::CSGFaceOperation (Mesh *obj, CSGOperation op, int subsetIndex0, int subsetIndex1, number snapThreshold)
void ug::promesh::CSGFaceUnion (Mesh *obj, int subsetIndex0, int subsetIndex1, number snapThreshold)
void ug::promesh::DeselectAllEdges (Mesh *obj)
void ug::promesh::DeselectAllFaces (Mesh *obj)
void ug::promesh::DeselectAllVertices (Mesh *obj)
void ug::promesh::DeselectAllVolumes (Mesh *obj)
void ug::promesh::Duplicate (Mesh *obj, const vector3 &offset, bool deselectOld, bool selectNew)
void ug::promesh::EdgeSelectionFill (Mesh *obj)
void ug::promesh::EraseEmptySubsets (Mesh *obj)
void ug::promesh::EraseSelectedElements (Mesh *obj, bool eraseUnusedVrts, bool eraseUnusedEdges, bool eraseUnusedFaces)
void ug::promesh::EraseSubset (Mesh *obj, int si, bool eraseGeometry)
bool ug::promesh::ExportToUG3 (Mesh *obj, const char *filenamePrefix, const char *lgmName, const char *problemName)
void ug::promesh::ExtendSelection (Mesh *obj, int neighborhoodSize)
void ug::promesh::ExtendSelectionInDirection (Mesh *obj, int neighborhoodSize, const vector3 &dir, number minAngle, number maxAngle)
void ug::promesh::ExtrudeAlongNormal (Mesh *obj, number totalLength, int numSteps, bool createFaces, bool createVolumes)
void ug::promesh::ExtrudeAndMove (Mesh *obj, const vector3 &totalDir, int numSteps, bool createFaces, bool createVolumes)
void ug::promesh::ExtrudeAndScale (Mesh *obj, number totalScale, bool scaleAroundPivot, int numSteps, bool createFaces, bool createVolumes)
void ug::promesh::ExtrudeCylinders (Mesh *obj, number height, number radius, number snapThreshold)
void ug::promesh::ExtrudeFacesWithTets (Mesh *obj, int fromSi, int toSi, const number factor)
void ug::promesh::ExtrudeLayers (Mesh *obj, RasterLayers &layers, bool allowForTetsAndPyras)
void ug::promesh::ExtrudeLayersAndAddProjector (Mesh *obj, SPRasterLayers layers, bool allowForTetsAndPyras)
void ug::promesh::ExtrudeToThickness (Mesh *obj, number thickness, int numSteps, bool createFaces, bool createVolumes)
void ug::promesh::FaceSelectionFill (Mesh *obj)
void ug::promesh::FixFaceOrientation (Mesh *obj)
void ug::promesh::FixFaceSubsetOrientations (Mesh *obj)
int ug::promesh::FixVolumeOrientation (Mesh *obj)
void ug::promesh::FlattenBentQuadrilaterals (Mesh *obj, number stepSize, int numIterations)
SmartPtr< Box > ug::promesh::GetBoundingBox (Mesh *obj)
ProMeshRegistry & ug::promesh::GetProMeshRegistry ()
bool ug::promesh::GetSelectionCenter (Mesh *obj, vector3 &centerOut)
void ug::promesh::HangingNodeRefine (Mesh *obj, bool anisotropic)
void ug::promesh::HangingNodeRefine (Mesh *obj, bool strictSubsetInheritance, bool anisotropic)
void ug::promesh::InsertCenter (Mesh *obj)
void ug::promesh::InsertCenter (Mesh *obj, bool strictSubsetInheritance)
void ug::promesh::IntersectCloseEdges (Mesh *obj, number snapThreshold)
void ug::promesh::InvertFaceOrientation (Mesh *obj)
void ug::promesh::InvertSelection (Mesh *obj, bool invVrts, bool invEdges, bool invFaces, bool invVols)
void ug::promesh::JoinSubsets (Mesh *obj, int target, int si1, int si2, bool eraseUnused)
void ug::promesh::LaplacianSmooth (Mesh *obj, number alpha, int numIterations)
bool ug::promesh::LoadMesh (Mesh *obj, const char *filename)
void ug::promesh::MarkCornersOfMarkedEdges (Mesh *obj, number angle)
void ug::promesh::MarkCreaseEdges (Mesh *obj, number minAngle, bool clearMarks)
void ug::promesh::MarkSelection (Mesh *obj)
number ug::promesh::MeasureGridArea (Mesh *obj)
number ug::promesh::MeasureGridLength (Mesh *obj)
number ug::promesh::MeasureGridVolume (Mesh *obj)
number ug::promesh::MeasureSelectionArea (Mesh *obj)
number ug::promesh::MeasureSelectionLength (Mesh *obj)
number ug::promesh::MeasureSelectionVolume (Mesh *obj)
number ug::promesh::MeasureSubsetArea (Mesh *obj, int subsetInd)
number ug::promesh::MeasureSubsetLength (Mesh *obj, int subsetInd)
number ug::promesh::MeasureSubsetVolume (Mesh *obj, int subsetInd)
void ug::promesh::MergeAtCenter (Mesh *obj)
void ug::promesh::MergeAtFirst (Mesh *obj)
void ug::promesh::MergeAtLast (Mesh *obj)
void ug::promesh::MeshLayerBoundaries (Mesh *m, const RasterLayers &layers)
void ug::promesh::MeshLayers (Mesh *m, const RasterLayers &layers)
void ug::promesh::Mirror (Mesh *obj, const vector3 &axisOrig, const vector3 &origin)
void ug::promesh::Move (Mesh *obj, const vector3 &offset)
void ug::promesh::MoveAlongNormal (Mesh *obj, number offset)
void ug::promesh::MoveMeshTo (Mesh *obj, const vector3 &newPos)
bool ug::promesh::MoveSelectionTo (Mesh *obj, const vector3 &center)
void ug::promesh::MoveSubset (Mesh *obj, int oldIndex, int newIndex)
void ug::promesh::MoveVerticesAlongEdges (Mesh *obj, number relVal)
void ug::promesh::MoveVerticesToEdgeLength (Mesh *obj, number edgeLen)
void ug::promesh::MoveVerticesToProjectedEdgeLength (Mesh *obj, number projEdgeLen, const vector3 &projNormal)
void ug::promesh::PlaneCut (Mesh *obj, const vector3 &p, const vector3 &n)
number ug::promesh::ProjectedDistance (Mesh *obj, const vector3 &projectionNormal)
void ug::promesh::ProjectToLayer (Mesh *obj, RasterLayers &layers, int layerIndex)
void ug::promesh::ProjectToLimitPLoop (Mesh *obj)
void ug::promesh::ProjectToLimitSmoothBoundary (Mesh *obj)
void ug::promesh::ProjectToPlane (Mesh *obj, const vector3 &planeCenter, const vector3 &planeNormal)
void ug::promesh::ProjectToTopLayer (Mesh *obj, RasterLayers &layers)
void ug::promesh::ProjectVerticesToCloseEdges (Mesh *obj, number snapThreshold)
void ug::promesh::ProjectVerticesToCloseFaces (Mesh *obj, number snapThreshold)
void ug::promesh::Refine (Mesh *obj)
void ug::promesh::Refine (Mesh *obj, bool strictSubsetInheritance, bool useSnapPoints)
void ug::promesh::RefineSmooth (Mesh *obj)
void ug::promesh::RefineSmooth (Mesh *obj, bool strictSubsetInheritance)
void ug::promesh::RefineWithSnapPoints (Mesh *obj)
void ug::promesh::RefineWithSnapPointsOrtho (Mesh *obj)
void ug::promesh::RegularizingRefinement (Mesh *obj, const number aspectRatio)
size_t ug::promesh::RemoveDoubleEdges (Mesh *obj)
size_t ug::promesh::RemoveDoubleFaces (Mesh *obj)
size_t ug::promesh::RemoveDoubles (Mesh *obj, number threshold)
returns the number of removed vertices
void ug::promesh::ReplaceLowValenceVertices (Mesh *obj, number maxSquaredHeightToBaseAreaRatio)
void ug::promesh::ReplaceValence3Vertices (Mesh *obj, number maxSquaredHeightToBaseAreaRatio)
void ug::promesh::ResolveEdgeIntersection (Mesh *obj, number snapThreshold)
void ug::promesh::ResolveSelfIntersections (Mesh *obj, number snapThreshold)
void ug::promesh::ResolveTriangleIntersections (Mesh *obj, number snapThreshold)
void ug::promesh::RestrictSelectionToSubset (Mesh *obj, int si)
void ug::promesh::Retetrahedralize (Mesh *obj, number quality, bool preserveOuter, bool preserveAll, bool applyVolumeConstraint, int verbosity)
void ug::promesh::Retriangulate (Mesh *obj, number minAngle)
void ug::promesh::RotateAroundCenter (Mesh *obj, const vector3 &rotRad)
void ug::promesh::RotateAroundPivot (Mesh *obj, const vector3 &rotRad)
bool ug::promesh::SaveMesh (Mesh *obj, const char *filename)
void ug::promesh::ScaleAroundCenter (Mesh *obj, const vector3 &scale)
void ug::promesh::ScaleAroundPivot (Mesh *obj, const vector3 &scale)
void ug::promesh::ScaleAroundPoint (Mesh *obj, const vector3 &scale, const vector3 &point)
void ug::promesh::SelectAll (Mesh *obj)
void ug::promesh::SelectAllEdges (Mesh *obj)
void ug::promesh::SelectAllFaces (Mesh *obj)
void ug::promesh::SelectAllVertices (Mesh *obj)
void ug::promesh::SelectAllVolumes (Mesh *obj)
template<class TElem >
void ug::promesh::SelectAnisotropicElements (Mesh *obj, number minEdgeRatio)
void ug::promesh::SelectAssociatedEdges (Mesh *obj)
void ug::promesh::SelectAssociatedFaces (Mesh *obj)
void ug::promesh::SelectAssociatedVertices (Mesh *obj)
size_t ug::promesh::SelectBentQuadrilaterals (Mesh *obj, number dotThreshold)
void ug::promesh::SelectBoundaryEdges (Mesh *obj)
void ug::promesh::SelectBoundaryFaces (Mesh *obj)
void ug::promesh::SelectBoundaryVertices (Mesh *obj)
Edge * ug::promesh::SelectClosestEdge (Mesh *m, const vector3 &coord)
void ug::promesh::SelectCreaseEdges (Mesh *obj, number minAngle)
void ug::promesh::SelectDegenerateFaces (Mesh *obj, number maxHeight)
bool ug::promesh::SelectEdgeByIndex (Mesh *obj, int index)
void ug::promesh::SelectEdgesByDirection (Mesh *m, const vector3 &dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
template<class TElem >
TElem * ug::promesh::SelectElemByCoordinate (Mesh *obj, const vector3 &coord)
template<class TElem >
TElem * ug::promesh::SelectElemByCylindricalCoordinate (Mesh *obj, number rho, number phi, number z)
void ug::promesh::SelectElementsByIndexRange (Mesh *obj, const char *vrtRanges, const char *edgeRanges, const char *faceRanges, const char *volRanges, bool clearSelection)
void ug::promesh::SelectElementsBySplitPlane (Mesh *obj, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVols, const vector3 &pivot, const vector3 &normal)
template<class TElem >
void ug::promesh::SelectElementsInBox (Mesh *obj, const vector3 &min, const vector3 &max)
Selects elements whose center lie in a box.
template<int icoord, int selFlag>
void ug::promesh::SelectElementsInCoordinateRange (Mesh *mesh, number min, number max, bool vrts, bool edges, bool faces, bool vols)
template<int icoord, int selFlag, class TElem >
void ug::promesh::SelectElementsInCoordinateRange (Mesh *obj, number min, number max)
template<class TElem >
void ug::promesh::SelectElementsInCylinder (Mesh *obj, const vector3 &cylBase, const vector3 &cylTop, number radius)
Selects elements whose center lie in a cylinder.
bool ug::promesh::SelectFaceByIndex (Mesh *obj, int index)
void ug::promesh::SelectFacesByNormal (Mesh *obj, const vector3 &refNormal, number maxDeviationAngle)
void ug::promesh::SelectFacesByNormal (Mesh *obj, const vector3 &refNormal, number minDeviationAngle, number maxDeviationAngle, bool noInnerFaces)
void ug::promesh::SelectInnerEdges (Mesh *obj)
void ug::promesh::SelectInnerFaces (Mesh *obj)
void ug::promesh::SelectInnerVertices (Mesh *obj)
template<class TElem >
void ug::promesh::SelectInterfaceElements (Mesh *obj, bool regardSelectedNbrsOnly)
void ug::promesh::SelectIntersectingTriangles (Mesh *obj)
void ug::promesh::SelectLinkedBoundaryEdges (Mesh *obj, bool stopAtSelectedVrts)
void ug::promesh::SelectLinkedBoundaryFaces (Mesh *obj, bool stopAtSelectedEdges)
template<class TElem >
void ug::promesh::SelectLinkedElements (Mesh *obj)
void ug::promesh::SelectLinkedFlatFaces (Mesh *obj, number maxDeviationAngle, bool ignoreOrientation, bool traverseDegeneratedFaces, bool stopAtSelectedEdges)
void ug::promesh::SelectLinkedManifoldFaces (Mesh *obj)
void ug::promesh::SelectLongEdges (Mesh *obj, number minLength)
void ug::promesh::SelectMarkedEdges (Mesh *obj)
void ug::promesh::SelectMarkedFaces (Mesh *obj)
void ug::promesh::SelectMarkedVertices (Mesh *obj)
void ug::promesh::SelectNonManifoldEdges (Mesh *obj)
void ug::promesh::SelectSelectionBoundary (Mesh *obj)
size_t ug::promesh::SelectSelectionKinkVertices (Mesh *obj, number thresholdAngle, bool selectDarts)
void ug::promesh::SelectShortEdges (Mesh *obj, number maxLength)
void ug::promesh::SelectShortPolychains (Mesh *m, number maxChainLength, bool closedChainsOnly)
int ug::promesh::SelectSlivers (Mesh *obj, number thresholdRatio)
void ug::promesh::SelectSmoothEdgePath (Mesh *obj, number maxDeviation, number normalWeight, bool stopAtSelectedVrts)
void ug::promesh::SelectSubset (Mesh *obj, int si, bool selVrts, bool selEdges, bool selFaces, bool selVols)
void ug::promesh::SelectSubsetBoundary (Mesh *obj, int si, bool edgeBnds, bool faceBnds, bool volBnds)
void ug::promesh::SelectSubsetEdgesByDirection (Mesh *m, int subsetIndex, const vector3 &dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
size_t ug::promesh::SelectSubsetKinkVertices (Mesh *obj, int subsetIndex, number thresholdAngle, bool selectDarts)
void ug::promesh::SelectUnassignedElements (Mesh *obj, bool selVrts, bool selEdges, bool selFaces, bool selVols)
size_t ug::promesh::SelectUnconnectedVertices (Mesh *obj, bool edgeCons, bool faceCons, bool volCons)
int ug::promesh::SelectUnorientableVolumes (Mesh *obj)
bool ug::promesh::SelectVertexByIndex (Mesh *obj, int index)
bool ug::promesh::SelectVolumeByIndex (Mesh *obj, int index)
void ug::promesh::SelectVolumesByType (Mesh *obj, bool selHexahedra, bool selOctahedra, bool selPrisms, bool selPyramids, bool selTetrahedra)
void ug::promesh::SeparateDegeneratedBoundaryFaceSubsets (Mesh *obj, number angle)
void ug::promesh::SeparateFacesByEdgeSubsets (Mesh *obj)
void ug::promesh::SeparateFacesBySelectedEdges (Mesh *obj)
void ug::promesh::SeparateFaceSubsetByNormal (Mesh *obj, int si)
void ug::promesh::SeparateFaceSubsetsByNormal (Mesh *obj)
void ug::promesh::SeparateIrregularManifoldSubsets (Mesh *obj)
void ug::promesh::SeparateVolumesByFaceSubsets (Mesh *obj)
void ug::promesh::SeparateVolumesBySelectedFaces (Mesh *obj)
void ug::promesh::SetPivot (Mesh *obj, const vector3 &pos)
void ug::promesh::SetPivotToMeshCenter (Mesh *obj)
void ug::promesh::SetPivotToSelectionCenter (Mesh *obj)
void ug::promesh::SetSubsetName (Mesh *obj, int si, const char *name)
void ug::promesh::SimplifyPolylines (Mesh *m, number curvatureThreshold)
void ug::promesh::SimplifySmoothedPolylines (Mesh *m, number curvatureThreshold, number smoothingAlpha, int smoothingIterations)
void ug::promesh::SlopeSmooth (Mesh *obj, number alpha, int numIterations)
void ug::promesh::SnapToHorizontalRaster (Mesh *obj, SPRasterLayers layers)
void ug::promesh::SnapVerticesToVertices (Mesh *obj, Mesh *targetMesh)
void ug::promesh::SplitEdge (Mesh *obj)
void ug::promesh::SwapEdge (Mesh *obj)
void ug::promesh::SwapSubsets (Mesh *obj, int oldIndex, int newIndex)
void ug::promesh::TangentialSmooth (Mesh *obj, number alpha, int numIterations)
void ug::promesh::Tetrahedralize (Mesh *obj, number quality, bool preserveOuter, bool preserveAll, bool separateVolumes, bool appendSubsetsAtEnd, int verbosity)
void ug::promesh::TriangleFill (Mesh *obj, bool qualityGeneration, number minAngle, int si)
void ug::promesh::UnassignSubsets (Mesh *obj, bool vertices, bool edges, bool faces, bool volumes)
void ug::promesh::UnmarkSelection (Mesh *obj)
void ug::promesh::VolumeSelectionFill (Mesh *obj)
void ug::promesh::WeightedEdgeSmooth (Mesh *obj, number alpha, int numIterations)
void ug::promesh::WeightedFaceSmooth (Mesh *obj, number alpha, int numIterations)
void ug::promesh::WeightedNormalSmooth (Mesh *obj, number alpha, number dotThreshold, int numIterations)
Detailed Description
This plugin provides an interface to lib_grid's meshing algorithms.
Enumeration Type Documentation
CSGOperation
enum ug::promesh::CSGOperation
Enumerator
CSG_UNION
CSG_INTERSECTION
CSG_DIFFERENCE
RegistryTargets
enum ug::promesh::RegistryTargets
Enumerator
RT_NONE
RT_UGSCRIPT
RT_PROMESH
RT_DEFAULT
RT_NO_PROMESH
RT_NO_UGSCRIPT
Function Documentation
AdaptSurfaceToCylinder()
void ug::promesh::AdaptSurfaceToCylinder (Mesh * obj, number radius, number threshold)
References ug::AdaptSurfaceGridToCylinder(), ug::Selector::begin(), ug::CalculateVertexNormal(), ug::Selector::end(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), and UG_LOG.
Referenced by ug::promesh::RegisterMeshingTools().
AdjustEdgeLength()
void ug::promesh::AdjustEdgeLength (Mesh * obj, number minEdgeLen, number maxEdgeLen, int numIterations, bool adaptive, bool automarkBoundaries)
References ug::GridSubsetHandler::assign_subset(), ug::promesh::CopySubsetIndicesToSides(), ug::promesh::Mesh::crease_handler(), ug::promesh::Mesh::grid(), grid(), ug::IsBoundaryEdge2D(), ug::REM_CREASE, and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::AdjustEdgeLengthExtended().
AdjustEdgeLengthExtended()
void ug::promesh::AdjustEdgeLengthExtended (Mesh * obj, number minEdgeLen, number maxEdgeLen, number approximation, number triQuality, int numIterations, bool automarkBoundaries)
References ug::promesh::AdjustEdgeLength(), ug::AdjustEdgeLengthDesc::approximation, ug::GridSubsetHandler::assign_subset(), ug::promesh::CopySubsetIndicesToSides(), ug::promesh::Mesh::crease_handler(), ug::promesh::Mesh::grid(), grid(), ug::IsBoundaryEdge2D(), ug::AdjustEdgeLengthDesc::maxEdgeLen, ug::AdjustEdgeLengthDesc::minEdgeLen, ug::REM_CREASE, ug::promesh::Mesh::subset_handler(), and ug::AdjustEdgeLengthDesc::triQuality.
Referenced by ug::promesh::RegisterMeshingTools().
AdjustEdgeOrientation()
void ug::promesh::AdjustEdgeOrientation (Mesh * obj)
References AdjustEdgeOrientationToFaceOrientation(), ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools().
AdjustSubsetsForUG3()
void ug::promesh::AdjustSubsetsForUG3 (Mesh * obj, bool keepIntfSubs)
References ug::AdjustSubsetsForLgmNg(), ug::promesh::Mesh::grid(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSubsetTools().
AdjustSubsetsForUG4()
void ug::promesh::AdjustSubsetsForUG4 (Mesh * obj, bool preserveExistingSubsets)
References ug::AdjustSubsetsForSimulation(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSubsetTools().
AssignNewSubset()
void ug::promesh::AssignNewSubset (Mesh * obj, const char * name, bool vertices, bool edges, bool faces, bool volumes)
References ug::GridSubsetHandler::assign_subset(), ug::Selector::begin(), ug::Selector::end(), ug::SubsetInfo::name, ug::ISubsetHandler::num_subsets(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), ug::ISubsetHandler::subset_info(), and vertices().
Referenced by ug::promesh::RegisterSubsetTools().
AssignSubset() [1/2]
void ug::promesh::AssignSubset (Mesh * obj, int newIndex)
References ug::GridSubsetHandler::assign_subset(), ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSubsetTools(), and ug::promesh::UnassignSubsets().
AssignSubset() [2/2]
void ug::promesh::AssignSubset (Mesh * obj, int newIndex, bool vertices, bool edges, bool faces, bool volumes)
References ug::GridSubsetHandler::assign_subset(), ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), and vertices().
AssignSubsetColors()
void ug::promesh::AssignSubsetColors (Mesh * obj)
References ug::promesh::Mesh::subset_handler().
AssignSubsetsByAspectRatio()
template<class elem_t > void ug::promesh::AssignSubsetsByAspectRatio (Mesh * msh, int numHistoSecs, bool eraseOldSubsets)
References ug::GridSubsetHandler::assign_subset(), ug::AssignSubsetColorsBlueToGreen(), ug::Grid::attach_to(), ug::Grid::begin(), ug::Selector::begin(), ug::ISubsetHandler::clear(), ug::Grid::detach_from(), ug::Selector::end(), ug::Grid::end(), ug::GetAspectRatioHistogram(), ug::promesh::Mesh::grid(), mkstr, ug::SubsetInfo::name, ug::Selector::num(), ug::Grid::num(), ug::ISubsetHandler::num_subsets(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), ug::ISubsetHandler::subset_info(), Table< std::stringstream >::to_string(), and UG_LOG.
AssignSubsetsByElementType()
void ug::promesh::AssignSubsetsByElementType (Mesh * obj)
References ug::GridSubsetHandler::empty(), ug::ISubsetHandler::erase_subset(), ug::Selector::get_grid_objects(), ug::ISubsetHandler::num_subsets(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
AssignSubsetsByQuality()
void ug::promesh::AssignSubsetsByQuality (Mesh * obj, int numSections)
References ug::AssignSubsetsByQuality(), ug::Selector::begin(), ug::Selector::end(), ug::ISubsetHandler::get_subset_index(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), and UG_LOG.
AssignSubsetsFromRaster()
void ug::promesh::AssignSubsetsFromRaster (Mesh * obj, const char * rasterFileName, int rasterDimension, bool vertices, bool edges, bool faces, bool volumes)
References UG_THROW, and vertices().
Referenced by ug::promesh::RegisterSubsetTools().
AssignVolumeConstraints()
void ug::promesh::AssignVolumeConstraints (Mesh * obj, number volConstraint)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::volume_constraint_accessor().
Referenced by ug::promesh::RegisterMeshingTools().
ClearMarks()
void ug::promesh::ClearMarks (Mesh * obj)
References ug::ISubsetHandler::clear(), and ug::promesh::Mesh::crease_handler().
Referenced by ug::promesh::RegisterSelectionTools().
ClearSelection()
void ug::promesh::ClearSelection (Mesh * obj)
References ug::Selector::clear(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
ClearVolumeConstraints()
void ug::promesh::ClearVolumeConstraints (Mesh * obj)
References ug::promesh::Mesh::clear_volume_constraints().
Referenced by ug::promesh::RegisterMeshingTools().
CloneMesh()
SmartPtr< Mesh > ug::promesh::CloneMesh (Mesh * mesh)
References make_sp().
Referenced by ug::promesh::RegisterMeshingTools().
CloseSelection()
void ug::promesh::CloseSelection (Mesh * obj)
References ug::promesh::Mesh::selector().
Referenced by ug::promesh::CreateTKD(), ug::promesh::CreateTKDWithOuterLayer(), ug::promesh::Retriangulate(), and ug::promesh::TriangleFill().
CollapseEdge()
void ug::promesh::CollapseEdge (Mesh * obj)
References ug::Selector::begin(), CollectEdges(), CollectFaces(), ug::promesh::Mesh::grid(), grid(), ug::ISelector::is_selected(), ug::Selector::num(), ug::Face::num_edges(), ug::promesh::Mesh::position_accessor(), ug::ISelector::select(), ug::promesh::Mesh::selector(), VecAdd(), VecScale(), and ug::EdgeVertices::vertex().
ConeTransform()
void ug::promesh::ConeTransform (Mesh * obj, const vector3 & base, const vector3 & axis, number scaleAtTip)
References CollectVerticesTouchingSelection(), ug::promesh::Mesh::position_accessor(), ProjectPointToRay(), s, ug::promesh::Mesh::selector(), VecAdd(), VecScale(), and VecSubtract().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
ConvertToQuadrilaterals()
void ug::promesh::ConvertToQuadrilaterals (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::Selector::num(), ug::promesh::Mesh::position_accessor(), ug::ReplaceByQuadrilaterals_EdgeBased(), ug::ReplaceByQuadrilaterals_FaceBased(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools().
ConvertToTetrahedra()
void ug::promesh::ConvertToTetrahedra (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), and ug::promesh::Mesh::selector().
ConvertToTriangles()
void ug::promesh::ConvertToTriangles (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), and ug::Triangulate().
Referenced by ug::promesh::RegisterMeshingTools().
CopySelection()
void ug::promesh::CopySelection (Mesh * srcMesh, Mesh * destMesh)
References ug::GridSubsetHandler::assign_subset(), ug::Grid::attach_to_vertices(), ug::Selector::begin(), ug::SubsetInfo::color, ug::promesh::Mesh::crease_handler(), ug::Grid::create_by_cloning(), ug::Grid::detach_from_vertices(), ug::Selector::end(), ug::ISubsetHandler::get_subset_index(), ug::promesh::Mesh::grid(), ug::SubsetInfo::name, ug::ISubsetHandler::num_subsets(), ug::promesh::Mesh::position_accessor(), ug::SelectAssociatedGridObjects(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), and ug::ISubsetHandler::subset_info().
Referenced by ug::promesh::CSGFaceOperation().
CopySubsetIndicesToSides()
void ug::promesh::CopySubsetIndicesToSides (Mesh * obj, bool selectionOnly, bool toUnassignedOnly)
References ug::Selector::get_grid_objects(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::AdjustEdgeLength(), ug::promesh::AdjustEdgeLengthExtended(), ug::promesh::Retetrahedralize(), ug::promesh::Retriangulate(), ug::promesh::Tetrahedralize(), and ug::promesh::TriangleFill().
CreateBox()
void ug::promesh::CreateBox (Mesh * obj, const vector3 & boxMin, const vector3 & boxMax, int subsetInd, bool fill)
References ug::GridSubsetHandler::assign_subset(), ug::ISelector::autoselection_enabled(), ug::Selector::begin(), ug::Selector::clear(), ug::Hexahedron::create_face(), ug::ISelector::enable_autoselection(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::Hexahedron::num_faces(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
CreateCircle()
void ug::promesh::CreateCircle (Mesh * obj, const vector3 & center, number radius, int numRimVertices, int subsetInd, bool fill)
References ug::GridSubsetHandler::assign_subset(), ug::ISelector::autoselection_enabled(), ug::Selector::begin(), ug::Selector::clear(), ug::ISelector::enable_autoselection(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::PI, ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), ug::VecAdd(), and ug::VecScale().
Referenced by ug::promesh::RegisterMeshingTools().
CreateEdge()
Edge * ug::promesh::CreateEdge (Mesh * obj, int subsetInd)
References ug::GridSubsetHandler::assign_subset(), ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::Selector::num(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), and UG_LOG.
Referenced by ug::promesh::RegisterMeshingTools().
CreateFace()
Face * ug::promesh::CreateFace (Mesh * obj, int subsetInd)
References ug::GridSubsetHandler::assign_subset(), ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::Selector::num(), ug::promesh::Mesh::selector(), ug::FaceDescriptor::set_vertex(), ug::promesh::Mesh::subset_handler(), and UG_LOG.
Referenced by ug::promesh::RegisterMeshingTools().
CreateHexahedraFromSelectedPrisms()
void ug::promesh::CreateHexahedraFromSelectedPrisms (Mesh * obj)
References ug::Selector::begin(), ug::Selector::clear(), CreateHexahedronFromPrisms(), ug::ISelector::deselect(), ug::Selector::end(), ug::promesh::EraseSelectedElements(), ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools().
CreatePlane() [1/2]
void ug::promesh::CreatePlane (Mesh * obj, const vector3 & upLeft, const vector3 & upRight, const vector3 & lowLeft, const vector3 & lowRight, int subsetInd, bool fill)
References ug::GridSubsetHandler::assign_subset(), ug::ISelector::autoselection_enabled(), ug::Selector::begin(), ug::Selector::clear(), ug::ISelector::enable_autoselection(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::CreatePlane(), and ug::promesh::RegisterMeshingTools().
CreatePlane() [2/2]
void ug::promesh::CreatePlane (Mesh * obj, number width, number height, const vector3 & center, int subsetInd, bool fill)
References ug::promesh::CreatePlane().
CreatePrism()
void ug::promesh::CreatePrism (Mesh * obj, int subsetInd, bool fill)
References ug::GridSubsetHandler::assign_subset(), ug::ISelector::autoselection_enabled(), ug::Selector::begin(), ug::Selector::clear(), ug::Prism::create_face(), ug::ISelector::enable_autoselection(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::Prism::num_faces(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
CreatePyramid()
void ug::promesh::CreatePyramid (Mesh * obj, int subsetInd, bool fill)
References ug::GridSubsetHandler::assign_subset(), ug::ISelector::autoselection_enabled(), ug::Selector::begin(), ug::Selector::clear(), ug::Pyramid::create_face(), ug::ISelector::enable_autoselection(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::Pyramid::num_faces(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
CreateShrinkElements()
template<class TElemIter > void ug::promesh::CreateShrinkElements (Mesh * obj, number scale, TElemIter elemsBegin, TElemIter elemsEnd)
For each element of type TElem in obj this method creates a new element with separate corners. The new element will be scaled by 'scale'. All original elements will be deleted before the method terminates. It should thus be called for 'Volumes' first, then for 'Faces' and finally for 'Edges'.
References ug::CalculateCenter(), ug::CustomVertexGroup::clear(), ug::Grid::create_by_cloning(), ug::Grid::erase(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::CustomVertexGroup::push_back(), and ug::VecScaleAdd().
Referenced by ug::promesh::CreateShrinkGeometry().
CreateShrinkGeometry()
void ug::promesh::CreateShrinkGeometry (Mesh * obj, number scale)
For each element in obj this method creates a new element with separate corners. The new element will be scaled by 'scale'. All original elements will be deleted before the method terminates.
References ug::promesh::Mesh::begin(), ug::Grid::begin(), ug::promesh::CreateShrinkElements(), ug::Grid::end(), and ug::promesh::Mesh::grid().
Referenced by ug::promesh::RegisterMeshingTools().
CreateSphere()
void ug::promesh::CreateSphere (Mesh * obj, const vector3 & center, number radius, int numRefinements, int subsetInd)
References ug::GridSubsetHandler::assign_subset(), ug::Selector::begin(), ug::Selector::end(), ug::GenerateIcosphere(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_attachment(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
CreateTetrahedron()
void ug::promesh::CreateTetrahedron (Mesh * obj, int subsetInd, bool fill)
References ug::GridSubsetHandler::assign_subset(), ug::ISelector::autoselection_enabled(), ug::Selector::begin(), ug::Selector::clear(), ug::Tetrahedron::create_face(), ug::ISelector::enable_autoselection(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::Tetrahedron::num_faces(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
CreateTKD()
void ug::promesh::CreateTKD (Mesh * obj, int subsetInd, number a, number w, number h)
References ug::AssignSelectionToSubset(), ug::Selector::clear(), ug::promesh::CloseSelection(), ug::promesh::Mesh::grid(), grid(), ug::TKDInfo::num_inner_elements(), ug::TKDInfo::NUM_INNER_ELEMENTS, ug::promesh::Mesh::position_attachment(), ug::ISelector::select(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
CreateTKDWithOuterLayer()
void ug::promesh::CreateTKDWithOuterLayer (Mesh * obj, int innerSubsetInd, int outerSubsetInd, number a, number w, number h, number d)
References ug::AssignSelectionToSubset(), ug::Selector::clear(), ug::promesh::CloseSelection(), ug::promesh::Mesh::grid(), grid(), ug::TKDInfo::NUM_ELEMENTS, ug::TKDInfo::num_inner_elements(), ug::TKDInfo::num_outer_elements(), ug::promesh::Mesh::position_attachment(), ug::ISelector::select(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
CreateVertex()
Vertex * ug::promesh::CreateVertex (Mesh * obj, const vector3 & pos, int subsetInd)
References ug::GridSubsetHandler::assign_subset(), ug::Selector::clear(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), ug::ISelector::select(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
CreateVolume()
Volume * ug::promesh::CreateVolume (Mesh * obj, int subsetInd)
References ug::aPosition, ug::GridSubsetHandler::assign_subset(), ug::Selector::begin(), ug::CheckOrientation(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::Selector::num(), ug::promesh::Mesh::selector(), ug::VolumeDescriptor::set_vertex(), ug::promesh::Mesh::subset_handler(), and UG_LOG.
Referenced by ug::promesh::RegisterMeshingTools().
CSGFaceDifference()
void ug::promesh::CSGFaceDifference (Mesh * obj, int subsetIndex0, int subsetIndex1, number snapThreshold)
References ug::promesh::CSG_DIFFERENCE, and ug::promesh::CSGFaceOperation().
Referenced by ug::promesh::RegisterMeshingTools().
CSGFaceIntersection()
void ug::promesh::CSGFaceIntersection (Mesh * obj, int subsetIndex0, int subsetIndex1, number snapThreshold)
References ug::promesh::CSG_INTERSECTION, and ug::promesh::CSGFaceOperation().
Referenced by ug::promesh::RegisterMeshingTools().
CSGFaceOperation()
void ug::promesh::CSGFaceOperation (Mesh * obj, CSGOperation op, int subsetIndex0, int subsetIndex1, number snapThreshold)
References AttachmentAccessor< Vertex, TAttachment >::access(), ug::Grid::attach_to_vertices(), ug::Grid::begin(), ug::GridSubsetHandler::begin(), ug::CalculateCenter(), ug::Selector::clear(), ug::promesh::CopySelection(), ug::promesh::CSG_DIFFERENCE, ug::promesh::CSG_UNION, ug::Grid::end(), ug::GridSubsetHandler::end(), ug::promesh::EraseSelectedElements(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::position_attachment(), ug::RayElementIntersections(), ug::promesh::ResolveSelfIntersections(), ug::ISelector::select(), ug::promesh::Mesh::selector(), ug::SMALL, ug::RayElemIntersectionRecord< class >::smax, ug::RayElemIntersectionRecord< class >::smin, ug::promesh::Mesh::subset_handler(), ug::Triangulate(), ug::VecLengthSq(), and ug::VecNormalize().
Referenced by ug::promesh::CSGFaceDifference(), ug::promesh::CSGFaceIntersection(), and ug::promesh::CSGFaceUnion().
CSGFaceUnion()
void ug::promesh::CSGFaceUnion (Mesh * obj, int subsetIndex0, int subsetIndex1, number snapThreshold)
References ug::promesh::CSG_UNION, and ug::promesh::CSGFaceOperation().
Referenced by ug::promesh::RegisterMeshingTools().
DeselectAllEdges()
void ug::promesh::DeselectAllEdges (Mesh * obj)
References ug::ISelector::deselect(), ug::Selector::edges_begin(), ug::Selector::edges_end(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
DeselectAllFaces()
void ug::promesh::DeselectAllFaces (Mesh * obj)
References ug::ISelector::deselect(), ug::Selector::faces_begin(), ug::Selector::faces_end(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
DeselectAllVertices()
void ug::promesh::DeselectAllVertices (Mesh * obj)
References ug::ISelector::deselect(), ug::promesh::Mesh::selector(), ug::Selector::vertices_begin(), and ug::Selector::vertices_end().
Referenced by ug::promesh::RegisterSelectionTools().
DeselectAllVolumes()
void ug::promesh::DeselectAllVolumes (Mesh * obj)
References ug::ISelector::deselect(), ug::promesh::Mesh::selector(), ug::Selector::volumes_begin(), and ug::Selector::volumes_end().
Referenced by ug::promesh::RegisterSelectionTools().
Duplicate()
void ug::promesh::Duplicate (Mesh * obj, const vector3 & offset, bool deselectOld, bool selectNew)
References ug::Duplicate(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_attachment(), and ug::promesh::Mesh::selector().
EdgeSelectionFill()
void ug::promesh::EdgeSelectionFill (Mesh * obj)
References ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
EraseEmptySubsets()
void ug::promesh::EraseEmptySubsets (Mesh * obj)
References ug::GridSubsetHandler::empty(), ug::ISubsetHandler::erase_subset(), ug::ISubsetHandler::num_subsets(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSubsetTools().
EraseSelectedElements()
void ug::promesh::EraseSelectedElements (Mesh * obj, bool eraseUnusedVrts, bool eraseUnusedEdges, bool eraseUnusedFaces)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), SelectAssociatedEdges(), SelectAssociatedFaces(), SelectAssociatedVolumes(), SelectInnerSelectionEdges(), SelectInnerSelectionFaces(), SelectInnerSelectionVertices(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::CreateHexahedraFromSelectedPrisms(), ug::promesh::CSGFaceOperation(), and ug::promesh::RegisterMeshingTools().
EraseSubset()
void ug::promesh::EraseSubset (Mesh * obj, int si, bool eraseGeometry)
References ug::GridSubsetHandler::begin(), ug::GridSubsetHandler::end(), ug::ISubsetHandler::erase_subset(), ug::promesh::Mesh::grid(), grid(), ug::ISubsetHandler::num_subsets(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSubsetTools().
ExportToUG3()
bool ug::promesh::ExportToUG3 (Mesh * obj, const char * filenamePrefix, const char * lgmName, const char * problemName)
References ug::GridSubsetHandler::assign_subset(), ug::GridSubsetHandler::begin(), ug::GridSubsetHandler::end(), ug::ExportGridToUG(), ug::ExportGridToUG_2D(), ug::promesh::Mesh::grid(), ug::ISubsetHandler::num_subsets(), ug::Grid::num_volumes(), ug::SHE_FACE, ug::SHE_VOLUME, and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMisc().
ExtendSelection()
void ug::promesh::ExtendSelection (Mesh * obj, int neighborhoodSize)
References ug::promesh::Mesh::selector().
ExtendSelectionInDirection()
void ug::promesh::ExtendSelectionInDirection (Mesh * obj, int neighborhoodSize, const vector3 & dir, number minAngle, number maxAngle)
References ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
ExtrudeAlongNormal()
void ug::promesh::ExtrudeAlongNormal (Mesh * obj, number totalLength, int numSteps, bool createFaces, bool createVolumes)
References ug::CalculateNormal(), ug::Selector::clear(), ug::Selector::edges_begin(), ug::Selector::edges_end(), ug::ISubsetHandler::enable_strict_inheritance(), ug::EO_CREATE_FACES, ug::EO_CREATE_VOLUMES, ug::Extrude(), ug::Selector::faces_begin(), ug::Selector::faces_end(), ug::promesh::Mesh::grid(), grid(), ug::ISelector::is_selected(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::position_attachment(), ug::ISelector::select(), ug::SelectAssociatedGridObjects(), ug::promesh::Mesh::selector(), ug::PointerConstArray< class >::size(), ug::ISubsetHandler::strict_inheritance_enabled(), ug::promesh::Mesh::subset_handler(), ug::VecLengthSq(), ug::VecNormalize(), ug::VecScaleAdd(), ug::VecSubtract(), ug::EdgeVertices::vertex(), ug::Selector::vertices_begin(), and ug::Selector::vertices_end().
Referenced by ug::promesh::RegisterMeshingTools().
ExtrudeAndMove()
void ug::promesh::ExtrudeAndMove (Mesh * obj, const vector3 & totalDir, int numSteps, bool createFaces, bool createVolumes)
References ug::Selector::clear(), ug::Selector::edges_begin(), ug::Selector::edges_end(), ug::ISubsetHandler::enable_strict_inheritance(), ug::EO_CREATE_FACES, ug::EO_CREATE_VOLUMES, ug::Extrude(), ug::Selector::faces_begin(), ug::Selector::faces_end(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_attachment(), ug::ISelector::select(), ug::SelectAssociatedGridObjects(), ug::promesh::Mesh::selector(), ug::ISubsetHandler::strict_inheritance_enabled(), ug::promesh::Mesh::subset_handler(), ug::VecScale(), ug::Selector::vertices_begin(), and ug::Selector::vertices_end().
Referenced by ug::promesh::RegisterMeshingTools().
ExtrudeAndScale()
void ug::promesh::ExtrudeAndScale (Mesh * obj, number totalScale, bool scaleAroundPivot, int numSteps, bool createFaces, bool createVolumes)
References ug::CalculateCenter(), ug::Selector::clear(), ug::Selector::edges_begin(), ug::Selector::edges_end(), ug::ISubsetHandler::enable_strict_inheritance(), ug::EO_CREATE_FACES, ug::EO_CREATE_VOLUMES, ug::Extrude(), ug::Selector::faces_begin(), ug::Selector::faces_end(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::pivot(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::position_attachment(), ug::ISelector::select(), ug::SelectAssociatedGridObjects(), ug::promesh::Mesh::selector(), ug::ISubsetHandler::strict_inheritance_enabled(), ug::promesh::Mesh::subset_handler(), ug::VecScaleAdd(), ug::VecSubtract(), ug::Selector::vertices_begin(), and ug::Selector::vertices_end().
Referenced by ug::promesh::RegisterMeshingTools().
ExtrudeCylinders()
void ug::promesh::ExtrudeCylinders (Mesh * obj, number height, number radius, number snapThreshold)
References ug::Selector::begin(), ug::CalculateVertexNormal(), ug::Selector::end(), ug::ExtrudeCylinder(), ug::promesh::Mesh::grid(), ug::ISubsetHandler::num_subsets(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), and UG_LOG.
Referenced by ug::promesh::RegisterMeshingTools().
ExtrudeFacesWithTets()
void ug::promesh::ExtrudeFacesWithTets (Mesh * obj, int fromSi, int toSi, const number factor)
References ug::GridSubsetHandler::assign_subset(), ug::ISelector::autoselection_enabled(), ug::Selector::begin(), ug::GridSubsetHandler::begin(), ug::CalculateCenter(), ug::CalculateTriangleNormal(), ug::Selector::clear(), ug::Tetrahedron::create_face(), ug::ISelector::enable_autoselection(), ug::Selector::end(), ug::GridSubsetHandler::end(), ug::FaceArea(), ug::promesh::Mesh::grid(), grid(), ug::Tetrahedron::num_faces(), ug::FaceVertices::num_vertices(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), UG_LOG, ug::VecAdd(), and ug::FaceVertices::vertex().
Referenced by ug::promesh::RegisterMeshingTools().
ExtrudeLayers()
void ug::promesh::ExtrudeLayers (Mesh * obj, RasterLayers & layers, bool allowForTetsAndPyras)
References ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::ExtrudeLayersAndAddProjector(), and ug::promesh::RegisterMeshingTools().
ExtrudeLayersAndAddProjector()
void ug::promesh::ExtrudeLayersAndAddProjector (Mesh * obj, SPRasterLayers layers, bool allowForTetsAndPyras)
References ug::promesh::ExtrudeLayers(), ug::promesh::Mesh::geometry(), ug::promesh::Mesh::grid(), make_sp(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::projection_handler(), ug::ProjectionHandler::set_default_projector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
ExtrudeToThickness()
void ug::promesh::ExtrudeToThickness (Mesh * obj, number thickness, int numSteps, bool createFaces, bool createVolumes)
References ug::CalculateCenter(), ug::CalculateNormal(), ug::Selector::clear(), ug::Selector::edges_begin(), ug::Selector::edges_end(), ug::ISubsetHandler::enable_strict_inheritance(), ug::EO_CREATE_FACES, ug::EO_CREATE_VOLUMES, ug::Extrude(), ug::Selector::faces_begin(), ug::Selector::faces_end(), ug::promesh::Mesh::grid(), grid(), ug::ISelector::is_selected(), p, ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::position_attachment(), ug::ISelector::select(), ug::SelectAssociatedGridObjects(), ug::promesh::Mesh::selector(), ug::PointerConstArray< class >::size(), ug::ISubsetHandler::strict_inheritance_enabled(), ug::promesh::Mesh::subset_handler(), ug::VecDot(), ug::VecNormalize(), ug::VecScaleAdd(), ug::VecSubtract(), ug::EdgeVertices::vertex(), ug::Selector::vertices_begin(), and ug::Selector::vertices_end().
Referenced by ug::promesh::RegisterMeshingTools().
FaceSelectionFill()
void ug::promesh::FaceSelectionFill (Mesh * obj)
References ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
FixFaceOrientation()
void ug::promesh::FixFaceOrientation (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::FixFaceSubsetOrientations(), and ug::promesh::RegisterMeshingTools().
FixFaceSubsetOrientations()
void ug::promesh::FixFaceSubsetOrientations (Mesh * obj)
References ug::GridSubsetHandler::begin(), ug::GridSubsetHandler::end(), ug::promesh::FixFaceOrientation(), ug::promesh::Mesh::grid(), grid(), ug::ISubsetHandler::num_subsets(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
FixVolumeOrientation()
int ug::promesh::FixVolumeOrientation (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), FixOrientation(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools().
FlattenBentQuadrilaterals()
void ug::promesh::FlattenBentQuadrilaterals (Mesh * obj, number stepSize, int numIterations)
References ug::Selector::begin(), ug::Selector::end(), FindClosestPlane(), p, ug::promesh::Mesh::position_accessor(), ProjectPointToPlane(), ug::promesh::Mesh::selector(), VecScaleAdd(), and CustomQuadrilateral< Quadrilateral, Face, Triangle, Quadrilateral >::vertex().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
GetBoundingBox()
SmartPtr<Box> ug::promesh::GetBoundingBox (Mesh * obj) inline
References ug::CalculateBoundingBox(), ug::promesh::Mesh::grid(), make_sp(), ug::promesh::Mesh::position_accessor(), ug::Grid::vertices_begin(), and ug::Grid::vertices_end().
Referenced by ug::promesh::RegisterMisc().
GetProMeshRegistry()
UG_API ProMeshRegistry & ug::promesh::GetProMeshRegistry ()
References ug::promesh::g_promeshRegistry.
Referenced by ug::InitUGPlugin_ProMesh().
GetSelectionCenter()
bool ug::promesh::GetSelectionCenter (Mesh * obj, vector3 & centerOut)
References CalculateCenter(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::MoveSelectionTo(), and ug::promesh::RegisterCoordinateTransformTools().
HangingNodeRefine() [1/2]
void ug::promesh::HangingNodeRefine (Mesh * obj, bool anisotropic)
HangingNodeRefine() [2/2]
void ug::promesh::HangingNodeRefine (Mesh * obj, bool strictSubsetInheritance, bool anisotropic)
References ug::Selector::edges_begin(), ug::Selector::edges_end(), ug::ISubsetHandler::enable_strict_inheritance(), ug::Selector::faces_begin(), ug::Selector::faces_end(), ug::promesh::Mesh::grid(), grid(), ug::HangingNodeRefiner_Grid::mark(), ug::IRefiner::refine(), RM_ANISOTROPIC, RM_REFINE, ug::promesh::Mesh::selector(), ug::IRefiner::set_adjusted_marks_debug_filename(), ug::ISubsetHandler::strict_inheritance_enabled(), ug::promesh::Mesh::subset_handler(), UG_LOG, ug::Selector::volumes_begin(), and ug::Selector::volumes_end().
Referenced by ug::promesh::RegisterMeshingTools().
InsertCenter() [1/2]
void ug::promesh::InsertCenter (Mesh * obj)
InsertCenter() [2/2]
void ug::promesh::InsertCenter (Mesh * obj, bool strictSubsetInheritance)
References aPosition, ug::Selector::begin(), CalculateCenter(), ug::ISubsetHandler::enable_strict_inheritance(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), InsertCenterVertex(), ug::Selector::num(), ug::promesh::Mesh::selector(), ug::ISubsetHandler::strict_inheritance_enabled(), ug::promesh::Mesh::subset_handler(), and UG_LOG.
Referenced by ug::promesh::RegisterMeshingTools().
IntersectCloseEdges()
void ug::promesh::IntersectCloseEdges (Mesh * obj, number snapThreshold)
References ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools(), ug::promesh::ResolveEdgeIntersection(), and ug::promesh::ResolveSelfIntersections().
InvertFaceOrientation()
void ug::promesh::InvertFaceOrientation (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), InvertOrientation(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools().
InvertSelection()
void ug::promesh::InvertSelection (Mesh * obj, bool invVrts, bool invEdges, bool invFaces, bool invVols)
References ug::promesh::Mesh::grid(), grid(), and ug::promesh::Mesh::selector().
JoinSubsets()
void ug::promesh::JoinSubsets (Mesh * obj, int target, int si1, int si2, bool eraseUnused)
References ug::ISubsetHandler::join_subsets(), ug::promesh::Mesh::subset_handler(), and target().
Referenced by ug::promesh::RegisterSubsetTools().
LaplacianSmooth()
void ug::promesh::LaplacianSmooth (Mesh * obj, number alpha, int numIterations)
References ug::Grid::begin(), CollectVerticesTouchingSelection(), ug::promesh::Mesh::grid(), LaplacianSmooth(), ug::LaplacianSmooth(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
LoadMesh()
bool ug::promesh::LoadMesh (Mesh * obj, const char * filename)
References ug::promesh::Mesh::crease_handler(), ug::FindFileInStandardPaths(), ug::promesh::Mesh::grid(), ug::GridReaderUGX::grid(), ug::LoadGridFromFile(), ug::GridReaderUGX::num_grids(), ug::GridReaderUGX::num_projection_handlers(), ug::GridReaderUGX::num_selectors(), ug::GridReaderUGX::num_subset_handlers(), ug::GridReaderUGX::parse_file(), ug::promesh::Mesh::position_attachment(), ug::promesh::Mesh::projection_handler(), ug::GridReaderUGX::projection_handler(), ug::promesh::Mesh::selector(), ug::GridReaderUGX::selector(), ug::promesh::Mesh::subset_handler(), ug::GridReaderUGX::subset_handler(), and UG_LOG.
Referenced by ug::promesh::RegisterMisc().
MarkCornersOfMarkedEdges()
void ug::promesh::MarkCornersOfMarkedEdges (Mesh * obj, number angle)
References ug::promesh::Mesh::crease_handler(), ug::promesh::Mesh::grid(), grid(), MarkCorners(), ug::promesh::Mesh::position_attachment(), ug::REM_CREASE, and ug::REM_FIXED.
Referenced by ug::promesh::RegisterSelectionTools().
MarkCreaseEdges()
void ug::promesh::MarkCreaseEdges (Mesh * obj, number minAngle, bool clearMarks)
References ug::Grid::begin(), ug::ISubsetHandler::clear(), ug::promesh::Mesh::crease_handler(), ug::Grid::end(), ug::promesh::Mesh::grid(), MarkFixedCreaseVertices(), REM_CREASE, and REM_FIXED.
Referenced by ug::promesh::RegisterSelectionTools().
MarkSelection()
void ug::promesh::MarkSelection (Mesh * obj)
References ug::GridSubsetHandler::assign_subset(), ug::Selector::begin(), ug::promesh::Mesh::crease_handler(), ug::Selector::end(), ug::REM_CREASE, ug::REM_FIXED, and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
MeasureGridArea()
number ug::promesh::MeasureGridArea (Mesh * obj) inline
References ug::Grid::begin(), ug::CalculateVolume(), ug::Grid::end(), ug::promesh::Mesh::grid(), and ug::promesh::Mesh::position_accessor().
Referenced by ug::promesh::RegisterMisc().
MeasureGridLength()
number ug::promesh::MeasureGridLength (Mesh * obj) inline
References ug::Grid::begin(), ug::CalculateVolume(), ug::Grid::end(), ug::promesh::Mesh::grid(), and ug::promesh::Mesh::position_accessor().
Referenced by ug::promesh::RegisterMisc().
MeasureGridVolume()
number ug::promesh::MeasureGridVolume (Mesh * obj) inline
References ug::Grid::begin(), ug::CalculateVolume(), ug::Grid::end(), ug::promesh::Mesh::grid(), and ug::promesh::Mesh::position_accessor().
Referenced by ug::promesh::RegisterMisc().
MeasureSelectionArea()
number ug::promesh::MeasureSelectionArea (Mesh * obj) inline
References ug::Selector::begin(), ug::CalculateVolume(), ug::Selector::end(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMisc().
MeasureSelectionLength()
number ug::promesh::MeasureSelectionLength (Mesh * obj) inline
References ug::Selector::begin(), ug::CalculateVolume(), ug::Selector::end(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMisc().
MeasureSelectionVolume()
number ug::promesh::MeasureSelectionVolume (Mesh * obj) inline
References ug::Selector::begin(), ug::CalculateVolume(), ug::Selector::end(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMisc().
MeasureSubsetArea()
number ug::promesh::MeasureSubsetArea (Mesh * obj, int subsetInd) inline
References ug::GridSubsetHandler::begin(), ug::CalculateVolume(), ug::GridSubsetHandler::end(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMisc().
MeasureSubsetLength()
number ug::promesh::MeasureSubsetLength (Mesh * obj, int subsetInd) inline
References ug::GridSubsetHandler::begin(), ug::CalculateVolume(), ug::GridSubsetHandler::end(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMisc().
MeasureSubsetVolume()
number ug::promesh::MeasureSubsetVolume (Mesh * obj, int subsetInd) inline
References ug::GridSubsetHandler::begin(), ug::CalculateVolume(), ug::GridSubsetHandler::end(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMisc().
MergeAtCenter()
void ug::promesh::MergeAtCenter (Mesh * obj)
References CalculateCenter(), ug::promesh::Mesh::grid(), grid(), MergeMultipleVertices(), ug::promesh::Mesh::position_accessor(), SelectAssociatedGridObjects(), ug::promesh::Mesh::selector(), ug::Selector::vertices_begin(), and ug::Selector::vertices_end().
Referenced by ug::promesh::RegisterMeshingTools().
MergeAtFirst()
void ug::promesh::MergeAtFirst (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), MergeMultipleVertices(), ug::promesh::Mesh::position_accessor(), SelectAssociatedGridObjects(), ug::promesh::Mesh::selector(), ug::Selector::vertices_begin(), and ug::Selector::vertices_end().
Referenced by ug::promesh::RegisterMeshingTools().
MergeAtLast()
void ug::promesh::MergeAtLast (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), MergeMultipleVertices(), ug::promesh::Mesh::position_accessor(), SelectAssociatedGridObjects(), ug::promesh::Mesh::selector(), ug::Selector::vertices_begin(), and ug::Selector::vertices_end().
Referenced by ug::promesh::RegisterMeshingTools().
MeshLayerBoundaries()
void ug::promesh::MeshLayerBoundaries (Mesh * m, const RasterLayers & layers)
References ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
MeshLayers()
void ug::promesh::MeshLayers (Mesh * m, const RasterLayers & layers)
References ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
Mirror()
void ug::promesh::Mirror (Mesh * obj, const vector3 & axisOrig, const vector3 & origin)
References ug::Grid::begin(), CollectVerticesTouchingSelection(), ug::promesh::Mesh::grid(), p, ug::promesh::Mesh::position_accessor(), ProjectPointToPlane(), ug::promesh::Mesh::selector(), UG_COND_THROW, VecAdd(), VecLengthSq(), VecNormalize(), and VecSubtract().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
Move()
void ug::promesh::Move (Mesh * obj, const vector3 & offset)
References ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), and TranslateSelection().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
MoveAlongNormal()
void ug::promesh::MoveAlongNormal (Mesh * obj, number offset)
References CalculateNormal(), CollectVerticesTouchingSelection(), ug::promesh::Mesh::grid(), grid(), p, ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), ug::PointerConstArray< class >::size(), VecAdd(), VecNormalize(), and VecScaleAdd().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
MoveMeshTo()
void ug::promesh::MoveMeshTo (Mesh * obj, const vector3 & newPos)
References ug::Grid::begin(), ug::Grid::end(), ug::promesh::Mesh::grid(), MoveVertices(), ug::promesh::Mesh::pivot(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::set_pivot(), and VecSubtract().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
MoveSelectionTo()
bool ug::promesh::MoveSelectionTo (Mesh * obj, const vector3 & center)
References ug::promesh::GetSelectionCenter(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), TranslateSelection(), and VecSubtract().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
MoveSubset()
void ug::promesh::MoveSubset (Mesh * obj, int oldIndex, int newIndex)
References ug::ISubsetHandler::move_subset(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSubsetTools().
MoveVerticesAlongEdges()
void ug::promesh::MoveVerticesAlongEdges (Mesh * obj, number relVal)
References end_for, for_each_in_vec, ug::promesh::Mesh::grid(), grid(), ug::ISelector::is_selected(), lg_end_for, lg_for_each, ug::Selector::num(), ug::promesh::Mesh::position_accessor(), ug::PointerConstArray< class >::reserve(), ug::promesh::Mesh::selector(), VecAppend(), VecScaleAppend(), VecSubtract(), and ug::EdgeVertices::vertex().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
MoveVerticesToEdgeLength()
void ug::promesh::MoveVerticesToEdgeLength (Mesh * obj, number edgeLen)
References end_for, for_each_in_vec, ug::promesh::Mesh::grid(), grid(), ug::ISelector::is_selected(), lg_end_for, lg_for_each, ug::Selector::num(), ug::promesh::Mesh::position_accessor(), ug::PointerConstArray< class >::reserve(), ug::promesh::Mesh::selector(), VecAppend(), VecLength(), VecScaleAppend(), VecSubtract(), and ug::EdgeVertices::vertex().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
MoveVerticesToProjectedEdgeLength()
void ug::promesh::MoveVerticesToProjectedEdgeLength (Mesh * obj, number projEdgeLen, const vector3 & projNormal)
References end_for, for_each_in_vec, ug::promesh::Mesh::grid(), grid(), ug::ISelector::is_selected(), lg_end_for, lg_for_each, ug::Selector::num(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), VecAppend(), VecDot(), VecLength(), VecNormalize(), VecScale(), VecScaleAppend(), VecSubtract(), and ug::EdgeVertices::vertex().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
PlaneCut()
void ug::promesh::PlaneCut (Mesh * obj, const vector3 & p, const vector3 & n)
References CutEdgesWithPlane(), p, and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools().
ProjectedDistance()
number ug::promesh::ProjectedDistance (Mesh * obj, const vector3 & projectionNormal)
References ug::Selector::begin(), ug::Selector::num(), p, ug::promesh::Mesh::position_accessor(), ug::ProjectPointToPlane(), ug::promesh::Mesh::selector(), UG_THROW, and ug::VecDistance().
Referenced by ug::promesh::RegisterMisc().
ProjectToLayer()
void ug::promesh::ProjectToLayer (Mesh * obj, RasterLayers & layers, int layerIndex)
References ug::promesh::Mesh::grid(), and ug::promesh::Mesh::position_accessor().
Referenced by ug::promesh::ProjectToTopLayer(), and ug::promesh::RegisterMeshingTools().
ProjectToLimitPLoop()
void ug::promesh::ProjectToLimitPLoop (Mesh * obj)
References ug::promesh::Mesh::grid(), and ug::promesh::Mesh::position_attachment().
ProjectToLimitSmoothBoundary()
void ug::promesh::ProjectToLimitSmoothBoundary (Mesh * obj)
References ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_attachment(), and ProjectToLimitSubdivBoundary().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
ProjectToPlane()
void ug::promesh::ProjectToPlane (Mesh * obj, const vector3 & planeCenter, const vector3 & planeNormal)
References CollectVerticesTouchingSelection(), ug::promesh::Mesh::position_accessor(), ProjectPointToPlane(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
ProjectToTopLayer()
void ug::promesh::ProjectToTopLayer (Mesh * obj, RasterLayers & layers)
References ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::promesh::ProjectToLayer(), ug::RasterLayers::size(), and UG_COND_THROW.
Referenced by ug::promesh::RegisterMeshingTools().
ProjectVerticesToCloseEdges()
void ug::promesh::ProjectVerticesToCloseEdges (Mesh * obj, number snapThreshold)
References ug::Selector::begin(), ug::Selector::end(), ug::Selector::get_grid_objects(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_attachment(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools(), ug::promesh::ResolveEdgeIntersection(), ug::promesh::ResolveSelfIntersections(), and ug::promesh::ResolveTriangleIntersections().
ProjectVerticesToCloseFaces()
void ug::promesh::ProjectVerticesToCloseFaces (Mesh * obj, number snapThreshold)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_attachment(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools(), and ug::promesh::ResolveSelfIntersections().
Refine() [1/2]
void ug::promesh::Refine (Mesh * obj)
Referenced by ug::promesh::Refine(), ug::promesh::RefineSmooth(), ug::promesh::RefineWithSnapPoints(), and ug::promesh::RefineWithSnapPointsOrtho().
Refine() [2/2]
void ug::promesh::Refine (Mesh * obj, bool strictSubsetInheritance, bool useSnapPoints)
References ug::ISubsetHandler::enable_strict_inheritance(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::projection_handler(), ug::promesh::Refine(), ug::promesh::Mesh::selector(), ug::ISubsetHandler::strict_inheritance_enabled(), and ug::promesh::Mesh::subset_handler().
RefineSmooth() [1/2]
void ug::promesh::RefineSmooth (Mesh * obj)
RefineSmooth() [2/2]
void ug::promesh::RefineSmooth (Mesh * obj, bool strictSubsetInheritance)
References aPosition, ug::Selector::begin(), ug::promesh::Mesh::crease_handler(), ug::ISubsetHandler::enable_strict_inheritance(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), MakeGeometry3d(), ug::promesh::Refine(), REM_CREASE, ug::promesh::Mesh::selector(), ug::ISubsetHandler::strict_inheritance_enabled(), ug::promesh::Mesh::subset_handler(), and Triangulate().
Referenced by ug::promesh::RegisterMeshingTools().
RefineWithSnapPoints()
void ug::promesh::RefineWithSnapPoints (Mesh * obj)
References ug::promesh::Refine().
Referenced by ug::promesh::RegisterMeshingTools().
RefineWithSnapPointsOrtho()
void ug::promesh::RefineWithSnapPointsOrtho (Mesh * obj)
References ug::Grid::associated_elements(), ug::TElemSelector< class >::begin(), ug::Selector::begin(), CalculateCenter(), ug::ISelector::enable_autoselection(), ug::Selector::end(), ug::promesh::Mesh::grid(), ug::ISelector::is_selected(), ug::Selector::num(), ug::FaceVertices::num_vertices(), p, ug::promesh::Mesh::position_accessor(), ProjectPointToRay(), ug::promesh::Refine(), ug::promesh::Mesh::selector(), ug::PointerConstArray< class >::size(), UG_COND_THROW, VecSubtract(), ug::EdgeVertices::vertex(), and ug::FaceVertices::vertex().
Referenced by ug::promesh::RegisterMeshingTools().
RegularizingRefinement()
void ug::promesh::RegularizingRefinement (Mesh * obj, const number aspectRatio)
References ug::promesh::Mesh::grid(), and ug::Grid::num().
Referenced by ug::promesh::RegisterMeshingTools().
RemoveDoubleEdges()
size_t ug::promesh::RemoveDoubleEdges (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), RemoveDuplicates(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools().
RemoveDoubleFaces()
size_t ug::promesh::RemoveDoubleFaces (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), RemoveDuplicates(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools().
RemoveDoubles()
size_t ug::promesh::RemoveDoubles (Mesh * obj, number threshold)
returns the number of removed vertices
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_attachment(), and ug::promesh::Mesh::selector().
ReplaceLowValenceVertices()
void ug::promesh::ReplaceLowValenceVertices (Mesh * obj, number maxSquaredHeightToBaseAreaRatio)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::ReplaceLowValenceVertices(), and ug::promesh::Mesh::selector().
ReplaceValence3Vertices()
void ug::promesh::ReplaceValence3Vertices (Mesh * obj, number maxSquaredHeightToBaseAreaRatio)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::ReplaceValence3Vertices(), and ug::promesh::Mesh::selector().
ResolveEdgeIntersection()
void ug::promesh::ResolveEdgeIntersection (Mesh * obj, number snapThreshold)
References ug::Selector::begin(), ug::Selector::end(), ug::Selector::get_grid_objects(), ug::promesh::Mesh::grid(), grid(), ug::promesh::IntersectCloseEdges(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::position_attachment(), ug::promesh::ProjectVerticesToCloseEdges(), SelectAssociatedVertices(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools().
ResolveSelfIntersections()
void ug::promesh::ResolveSelfIntersections (Mesh * obj, number snapThreshold)
References ug::Selector::begin(), ug::Selector::end(), ug::Selector::get_grid_objects(), ug::promesh::Mesh::grid(), grid(), ug::promesh::IntersectCloseEdges(), ug::Selector::num(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::position_attachment(), ug::promesh::ProjectVerticesToCloseEdges(), ug::promesh::ProjectVerticesToCloseFaces(), ug::ResolveTriangleIntersections(), SelectAssociatedEdges(), SelectAssociatedVertices(), ug::promesh::Mesh::selector(), and Triangulate().
Referenced by ug::promesh::CSGFaceOperation(), and ug::promesh::RegisterMeshingTools().
ResolveTriangleIntersections()
void ug::promesh::ResolveTriangleIntersections (Mesh * obj, number snapThreshold)
References ug::Selector::begin(), ug::Selector::end(), ug::Selector::get_grid_objects(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_attachment(), ug::promesh::ProjectVerticesToCloseEdges(), ug::ResolveTriangleIntersections(), SelectAssociatedEdges(), SelectAssociatedVertices(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterMeshingTools().
RestrictSelectionToSubset()
void ug::promesh::RestrictSelectionToSubset (Mesh * obj, int si)
References ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Retetrahedralize()
void ug::promesh::Retetrahedralize (Mesh * obj, number quality, bool preserveOuter, bool preserveAll, bool applyVolumeConstraint, int verbosity)
References ug::promesh::CopySubsetIndicesToSides(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_attachment(), ug::Retetrahedralize(), ug::promesh::Mesh::subset_handler(), UG_LOG, and ug::promesh::Mesh::volume_constraint_attachment().
Retriangulate()
void ug::promesh::Retriangulate (Mesh * obj, number minAngle)
References ug::Selector::begin(), ug::promesh::CloseSelection(), ug::promesh::CopySubsetIndicesToSides(), ug::promesh::Mesh::crease_handler(), ug::Selector::end(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::QualityGridGeneration(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterMeshingTools().
RotateAroundCenter()
void ug::promesh::RotateAroundCenter (Mesh * obj, const vector3 & rotRad)
References CalculateCenter(), CollectVerticesTouchingSelection(), deg_to_rad(), MatRotationYawPitchRoll(), MatVecMult(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), VecAdd(), and VecSubtract().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
RotateAroundPivot()
void ug::promesh::RotateAroundPivot (Mesh * obj, const vector3 & rotRad)
References CollectVerticesTouchingSelection(), deg_to_rad(), MatRotationYawPitchRoll(), MatVecMult(), ug::promesh::Mesh::pivot(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), VecAdd(), and VecSubtract().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
SaveMesh()
bool ug::promesh::SaveMesh (Mesh * obj, const char * filename)
References ug::GridWriterUGX::add_grid(), ug::GridWriterUGX::add_projection_handler(), ug::GridWriterUGX::add_selector(), ug::GridWriterUGX::add_subset_handler(), ug::promesh::Mesh::crease_handler(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_attachment(), ug::promesh::Mesh::projection_handler(), ug::SaveGridToFile(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), and ug::GridWriterUGX::write_to_file().
Referenced by ug::promesh::RegisterMisc().
ScaleAroundCenter()
void ug::promesh::ScaleAroundCenter (Mesh * obj, const vector3 & scale)
References CalculateCenter(), CollectVerticesTouchingSelection(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), VecAdd(), and VecSubtract().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
ScaleAroundPivot()
void ug::promesh::ScaleAroundPivot (Mesh * obj, const vector3 & scale)
References CollectVerticesTouchingSelection(), ug::promesh::Mesh::pivot(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), VecAdd(), and VecSubtract().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
ScaleAroundPoint()
void ug::promesh::ScaleAroundPoint (Mesh * obj, const vector3 & scale, const vector3 & point)
References CollectVerticesTouchingSelection(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), VecAdd(), and VecSubtract().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
SelectAll()
void ug::promesh::SelectAll (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectAllEdges()
void ug::promesh::SelectAllEdges (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectAllFaces()
void ug::promesh::SelectAllFaces (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectAllVertices()
void ug::promesh::SelectAllVertices (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectAllVolumes()
void ug::promesh::SelectAllVolumes (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectAnisotropicElements()
template<class TElem > void ug::promesh::SelectAnisotropicElements (Mesh * obj, number minEdgeRatio)
References ug::Grid::begin(), ug::Grid::end(), ug::promesh::Mesh::grid(), ug::MarkForAnisotropicRefinement(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
SelectAssociatedEdges()
void ug::promesh::SelectAssociatedEdges (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), and ug::promesh::Mesh::selector().
SelectAssociatedFaces()
void ug::promesh::SelectAssociatedFaces (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::SelectLinkedManifoldFaces().
SelectAssociatedVertices()
void ug::promesh::SelectAssociatedVertices (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), and ug::promesh::Mesh::selector().
SelectBentQuadrilaterals()
size_t ug::promesh::SelectBentQuadrilaterals (Mesh * obj, number dotThreshold)
References aPosition, CalculateTriangleNormal(), ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), ug::promesh::Mesh::selector(), VecDot(), and CustomQuadrilateral< Quadrilateral, Face, Triangle, Quadrilateral >::vertex().
Referenced by ug::promesh::RegisterSelectionTools().
SelectBoundaryEdges()
void ug::promesh::SelectBoundaryEdges (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), SelectBoundaryElements(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectBoundaryFaces()
void ug::promesh::SelectBoundaryFaces (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), SelectBoundaryElements(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectBoundaryVertices()
void ug::promesh::SelectBoundaryVertices (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), ug::SelectBoundaryElements(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectClosestEdge()
Edge * ug::promesh::SelectClosestEdge (Mesh * m, const vector3 & coord)
References DistancePointToLine(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectCreaseEdges()
void ug::promesh::SelectCreaseEdges (Mesh * obj, number minAngle)
References ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_attachment(), and ug::promesh::Mesh::selector().
SelectDegenerateFaces()
void ug::promesh::SelectDegenerateFaces (Mesh * obj, number maxHeight)
References DistancePointToLine(), ug::Face::edge_desc(), ug::promesh::Mesh::grid(), grid(), ug::Face::num_edges(), ug::FaceVertices::num_vertices(), p, ug::promesh::Mesh::position_accessor(), ug::ISelector::select(), ug::promesh::Mesh::selector(), VecDistanceSq(), ug::FaceVertices::vertex(), and ug::EdgeVertices::vertex().
Referenced by ug::promesh::RegisterSelectionTools().
SelectEdgeByIndex()
bool ug::promesh::SelectEdgeByIndex (Mesh * obj, int index)
References ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectEdgesByDirection()
void ug::promesh::SelectEdgesByDirection (Mesh * m, const vector3 & dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
References ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
SelectElemByCoordinate()
template<class TElem > TElem* ug::promesh::SelectElemByCoordinate (Mesh * obj, const vector3 & coord)
References ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
SelectElemByCylindricalCoordinate()
template<class TElem > TElem* ug::promesh::SelectElemByCylindricalCoordinate (Mesh * obj, number rho, number phi, number z)
SelectElementsByIndexRange()
void ug::promesh::SelectElementsByIndexRange (Mesh * obj, const char * vrtRanges, const char * edgeRanges, const char * faceRanges, const char * volRanges, bool clearSelection)
References ug::Selector::clear(), RangeStringToIndexList(), ug::SelectElementsByIndex< Edge >(), ug::SelectElementsByIndex< Face >(), ug::SelectElementsByIndex< Vertex >(), ug::SelectElementsByIndex< Volume >(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectElementsBySplitPlane()
void ug::promesh::SelectElementsBySplitPlane (Mesh * obj, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVols, const vector3 & pivot, const vector3 & normal)
References ug::promesh::Mesh::grid(), normal, ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectElementsInBox()
template<class TElem > void ug::promesh::SelectElementsInBox (Mesh * obj, const vector3 & min, const vector3 & max)
Selects elements whose center lie in a box.
References ug::BoxBoundProbe(), ug::CalculateCenter(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
SelectElementsInCoordinateRange() [1/2]
template<int icoord, int selFlag> void ug::promesh::SelectElementsInCoordinateRange (Mesh * mesh, number min, number max, bool vrts, bool edges, bool faces, bool vols)
SelectElementsInCoordinateRange() [2/2]
template<int icoord, int selFlag, class TElem > void ug::promesh::SelectElementsInCoordinateRange (Mesh * obj, number min, number max)
References ug::Grid::begin(), ug::CalculateCenter(), ug::Grid::end(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
SelectElementsInCylinder()
template<class TElem > void ug::promesh::SelectElementsInCylinder (Mesh * obj, const vector3 & cylBase, const vector3 & cylTop, number radius)
Selects elements whose center lie in a cylinder.
References ug::CalculateCenter(), ug::promesh::Mesh::grid(), grid(), p, ug::promesh::Mesh::position_accessor(), ug::ProjectPointToRay(), s, ug::ISelector::select(), ug::promesh::Mesh::selector(), ug::SMALL, ug::sq(), ug::VecDistanceSq(), and ug::VecSubtract().
SelectFaceByIndex()
bool ug::promesh::SelectFaceByIndex (Mesh * obj, int index)
References ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectFacesByNormal() [1/2]
void ug::promesh::SelectFacesByNormal (Mesh * obj, const vector3 & refNormal, number maxDeviationAngle)
References aPosition, CalculateNormal(), deg_to_rad(), ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), ug::promesh::Mesh::selector(), VecDot(), and VecNormalize().
Referenced by ug::promesh::RegisterSelectionTools().
SelectFacesByNormal() [2/2]
void ug::promesh::SelectFacesByNormal (Mesh * obj, const vector3 & refNormal, number minDeviationAngle, number maxDeviationAngle, bool noInnerFaces)
References aPosition, CalculateNormal(), deg_to_rad(), ug::promesh::Mesh::grid(), grid(), NumAssociatedVolumes(), ug::ISelector::select(), ug::promesh::Mesh::selector(), SMALL, VecDot(), and VecNormalize().
SelectInnerEdges()
void ug::promesh::SelectInnerEdges (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), SelectInnerElements(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectInnerFaces()
void ug::promesh::SelectInnerFaces (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), SelectInnerElements(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectInnerVertices()
void ug::promesh::SelectInnerVertices (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), SelectInnerElements(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectInterfaceElements()
template<class TElem > void ug::promesh::SelectInterfaceElements (Mesh * obj, bool regardSelectedNbrsOnly)
References ug::Grid::begin(), ug::Grid::end(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
SelectIntersectingTriangles()
void ug::promesh::SelectIntersectingTriangles (Mesh * obj)
References ug::node_tree::Traverser_IntersectFaces::clear_ignore_list(), CollectNeighbors(), CreateOctree(), ug::promesh::Mesh::grid(), grid(), ug::node_tree::Traverser_IntersectFaces::ignore_element(), ug::node_tree::Traverser_IntersectFaces::intersect_tri(), NHT_VERTEX_NEIGHBORS, ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::position_attachment(), ug::ISelector::select(), ug::promesh::Mesh::selector(), UG_LOG, SmartPtr< class, FreePolicy >::valid(), and CustomTriangle< Triangle, Face, Triangle, Quadrilateral >::vertex().
Referenced by ug::promesh::RegisterSelectionTools().
SelectLinkedBoundaryEdges()
void ug::promesh::SelectLinkedBoundaryEdges (Mesh * obj, bool stopAtSelectedVrts)
References ug::promesh::Mesh::grid(), grid(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectLinkedBoundaryFaces()
void ug::promesh::SelectLinkedBoundaryFaces (Mesh * obj, bool stopAtSelectedEdges)
References ug::promesh::Mesh::grid(), grid(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectLinkedElements()
template<class TElem > void ug::promesh::SelectLinkedElements (Mesh * obj)
References ug::promesh::Mesh::selector().
SelectLinkedFlatFaces()
void ug::promesh::SelectLinkedFlatFaces (Mesh * obj, number maxDeviationAngle, bool ignoreOrientation, bool traverseDegeneratedFaces, bool stopAtSelectedEdges)
References ug::SelectLinkedFlatAndDegeneratedFaces(), ug::SelectLinkedFlatFaces(), and ug::promesh::Mesh::selector().
SelectLinkedManifoldFaces()
void ug::promesh::SelectLinkedManifoldFaces (Mesh * obj)
References CollectEdges(), ug::Selector::edges_begin(), ug::Selector::edges_end(), ug::Selector::faces_begin(), ug::Selector::faces_end(), GetAssociatedFaces(), ug::promesh::Mesh::grid(), grid(), ug::ISelector::is_selected(), ug::ISelector::select(), ug::promesh::SelectAssociatedFaces(), ug::promesh::Mesh::selector(), ug::Selector::vertices_begin(), ug::Selector::vertices_end(), ug::Selector::volumes_begin(), and ug::Selector::volumes_end().
Referenced by ug::promesh::RegisterSelectionTools().
SelectLongEdges()
void ug::promesh::SelectLongEdges (Mesh * obj, number minLength)
References ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), ug::ISelector::select(), ug::promesh::Mesh::selector(), VecDistanceSq(), and ug::EdgeVertices::vertex().
Referenced by ug::promesh::RegisterSelectionTools().
SelectMarkedEdges()
void ug::promesh::SelectMarkedEdges (Mesh * obj)
References ug::GridSubsetHandler::begin(), ug::promesh::Mesh::crease_handler(), ug::GridSubsetHandler::end(), REM_CREASE, ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectMarkedFaces()
void ug::promesh::SelectMarkedFaces (Mesh * obj)
References ug::GridSubsetHandler::begin(), ug::promesh::Mesh::crease_handler(), ug::GridSubsetHandler::end(), REM_CREASE, ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectMarkedVertices()
void ug::promesh::SelectMarkedVertices (Mesh * obj)
References ug::GridSubsetHandler::begin(), ug::promesh::Mesh::crease_handler(), ug::GridSubsetHandler::end(), REM_FIXED, ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectNonManifoldEdges()
void ug::promesh::SelectNonManifoldEdges (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), NumAssociatedFaces(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectSelectionBoundary()
void ug::promesh::SelectSelectionBoundary (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), ug::Selector::num(), SelectAreaBoundary(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectSelectionKinkVertices()
size_t ug::promesh::SelectSelectionKinkVertices (Mesh * obj, number thresholdAngle, bool selectDarts)
References ug::Selector::begin(), CollectVerticesTouchingSelection(), ug::Selector::num(), ug::promesh::Mesh::position_accessor(), SelectKinkVertices(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectShortEdges()
void ug::promesh::SelectShortEdges (Mesh * obj, number maxLength)
References ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), ug::ISelector::select(), ug::promesh::Mesh::selector(), VecDistanceSq(), and ug::EdgeVertices::vertex().
Referenced by ug::promesh::RegisterSelectionTools().
SelectShortPolychains()
void ug::promesh::SelectShortPolychains (Mesh * m, number maxChainLength, bool closedChainsOnly)
References ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
SelectSlivers()
int ug::promesh::SelectSlivers (Mesh * obj, number thresholdRatio)
References ug::Grid::begin(), ug::Grid::end(), FindSlivers(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectSmoothEdgePath()
void ug::promesh::SelectSmoothEdgePath (Mesh * obj, number maxDeviation, number normalWeight, bool stopAtSelectedVrts)
References ug::promesh::Mesh::selector().
SelectSubset()
void ug::promesh::SelectSubset (Mesh * obj, int si, bool selVrts, bool selEdges, bool selFaces, bool selVols)
References ug::GridSubsetHandler::begin(), ug::GridSubsetHandler::end(), ug::ISubsetHandler::get_subset_index(), ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
SelectSubsetBoundary()
void ug::promesh::SelectSubsetBoundary (Mesh * obj, int si, bool edgeBnds, bool faceBnds, bool volBnds)
References ug::GridSubsetHandler::begin(), ug::GridSubsetHandler::end(), SelectAreaBoundary(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSelectionTools().
SelectSubsetEdgesByDirection()
void ug::promesh::SelectSubsetEdgesByDirection (Mesh * m, int subsetIndex, const vector3 & dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
References ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
SelectSubsetKinkVertices()
size_t ug::promesh::SelectSubsetKinkVertices (Mesh * obj, int subsetIndex, number thresholdAngle, bool selectDarts)
References ug::Selector::begin(), ug::GridSubsetHandler::begin(), ug::GridSubsetHandler::end(), ug::promesh::Mesh::grid(), grid(), ug::Selector::num(), ug::promesh::Mesh::position_accessor(), SelectKinkVertices(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), and ug::EdgeVertices::vertex().
Referenced by ug::promesh::RegisterSelectionTools().
SelectUnassignedElements()
void ug::promesh::SelectUnassignedElements (Mesh * obj, bool selVrts, bool selEdges, bool selFaces, bool selVols)
References ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSelectionTools().
SelectUnconnectedVertices()
size_t ug::promesh::SelectUnconnectedVertices (Mesh * obj, bool edgeCons, bool faceCons, bool volCons)
References ug::promesh::Mesh::grid(), grid(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectUnorientableVolumes()
int ug::promesh::SelectUnorientableVolumes (Mesh * obj)
References aPosition, CheckOrientation(), ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectVertexByIndex()
bool ug::promesh::SelectVertexByIndex (Mesh * obj, int index)
References ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectVolumeByIndex()
bool ug::promesh::SelectVolumeByIndex (Mesh * obj, int index)
References ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SelectVolumesByType()
void ug::promesh::SelectVolumesByType (Mesh * obj, bool selHexahedra, bool selOctahedra, bool selPrisms, bool selPyramids, bool selTetrahedra)
References ug::promesh::Mesh::grid(), grid(), ug::ISelector::select(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
SeparateDegeneratedBoundaryFaceSubsets()
void ug::promesh::SeparateDegeneratedBoundaryFaceSubsets (Mesh * obj, number angle)
References ug::GridSubsetHandler::assign_subset(), ug::Grid::begin(), ug::Grid::begin_marking(), ug::CollectAssociated(), ug::deg_to_rad(), ug::Grid::end(), ug::Grid::end_marking(), ug::ISubsetHandler::get_subset_index(), ug::promesh::Mesh::grid(), ug::Grid::is_marked(), ug::IsDegenerated(), ug::IsVolumeBoundaryFace(), ug::Grid::mark(), ug::ISubsetHandler::num_subsets(), ug::promesh::Mesh::position_accessor(), ug::SMALL, ug::promesh::Mesh::subset_handler(), ug::VecDistanceSq(), ug::VecDot(), ug::VecNormalize(), ug::VecSubtract(), and ug::EdgeVertices::vertex().
Referenced by ug::promesh::RegisterSubsetTools().
SeparateFacesByEdgeSubsets()
void ug::promesh::SeparateFacesByEdgeSubsets (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSubsetTools().
SeparateFacesBySelectedEdges()
void ug::promesh::SeparateFacesBySelectedEdges (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSubsetTools().
SeparateFaceSubsetByNormal()
void ug::promesh::SeparateFaceSubsetByNormal (Mesh * obj, int si)
References ug::promesh::Mesh::grid(), num_subsets(), ug::promesh::Mesh::position_attachment(), ug::promesh::SeparateFaceSubsetsByNormal(), ug::promesh::Mesh::subset_handler(), and subset_handler().
Referenced by ug::promesh::RegisterSubsetTools().
SeparateFaceSubsetsByNormal()
void ug::promesh::SeparateFaceSubsetsByNormal (Mesh * obj)
References ug::promesh::Mesh::grid(), ug::SeparateFaceSubsetsByNormal(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::SeparateFaceSubsetByNormal().
SeparateIrregularManifoldSubsets()
void ug::promesh::SeparateIrregularManifoldSubsets (Mesh * obj)
References ug::ISubsetHandler::num_subsets(), ug::SplitIrregularManifoldSubset(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSubsetTools().
SeparateVolumesByFaceSubsets()
void ug::promesh::SeparateVolumesByFaceSubsets (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSubsetTools().
SeparateVolumesBySelectedFaces()
void ug::promesh::SeparateVolumesBySelectedFaces (Mesh * obj)
References ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::subset_handler().
Referenced by ug::promesh::RegisterSubsetTools().
SetPivot()
void ug::promesh::SetPivot (Mesh * obj, const vector3 & pos)
References ug::promesh::Mesh::set_pivot().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
SetPivotToMeshCenter()
void ug::promesh::SetPivotToMeshCenter (Mesh * obj)
References ug::Grid::begin(), CalculateCenter(), ug::Grid::end(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::set_pivot().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
SetPivotToSelectionCenter()
void ug::promesh::SetPivotToSelectionCenter (Mesh * obj)
References CalculateCenter(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), and ug::promesh::Mesh::set_pivot().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
SetSubsetName()
void ug::promesh::SetSubsetName (Mesh * obj, int si, const char * name)
References ug::SubsetInfo::name, ug::promesh::Mesh::subset_handler(), and ug::ISubsetHandler::subset_info().
Referenced by ug::promesh::RegisterSubsetTools().
SimplifyPolylines()
void ug::promesh::SimplifyPolylines (Mesh * m, number curvatureThreshold)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
SimplifySmoothedPolylines()
void ug::promesh::SimplifySmoothedPolylines (Mesh * m, number curvatureThreshold, number smoothingAlpha, int smoothingIterations)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
SlopeSmooth()
void ug::promesh::SlopeSmooth (Mesh * obj, number alpha, int numIterations)
References ug::Grid::begin(), CollectVerticesTouchingSelection(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), SlopeSmooth(), and ug::SlopeSmooth().
SnapToHorizontalRaster()
void ug::promesh::SnapToHorizontalRaster (Mesh * obj, SPRasterLayers layers)
References ug::promesh::Mesh::grid(), and ug::promesh::Mesh::position_accessor().
Referenced by ug::promesh::RegisterMeshingTools().
SnapVerticesToVertices()
void ug::promesh::SnapVerticesToVertices (Mesh * obj, Mesh * targetMesh)
References ug::Selector::begin(), ug::KDTreeStatic< class, numDimensions, class >::create_from_grid(), ug::Selector::end(), ug::KDTreeStatic< class, numDimensions, class >::get_neighbourhood(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::position_attachment(), and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterCoordinateTransformTools().
SplitEdge()
void ug::promesh::SplitEdge (Mesh * obj)
References ug::Selector::begin(), CalculateCenter(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::selector().
SwapEdge()
void ug::promesh::SwapEdge (Mesh * obj)
References ug::Selector::begin(), ug::Selector::end(), GetAssociatedFaces(), ug::promesh::Mesh::grid(), grid(), num_vertices(), and ug::promesh::Mesh::selector().
SwapSubsets()
void ug::promesh::SwapSubsets (Mesh * obj, int oldIndex, int newIndex)
References ug::ISubsetHandler::num_subsets(), ug::promesh::Mesh::subset_handler(), and ug::ISubsetHandler::swap_subsets().
Referenced by ug::promesh::RegisterSubsetTools().
TangentialSmooth()
void ug::promesh::TangentialSmooth (Mesh * obj, number alpha, int numIterations)
References ug::Grid::begin(), CollectVerticesTouchingSelection(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), TangentialSmooth(), and ug::TangentialSmooth().
Tetrahedralize()
void ug::promesh::Tetrahedralize (Mesh * obj, number quality, bool preserveOuter, bool preserveAll, bool separateVolumes, bool appendSubsetsAtEnd, int verbosity)
References ug::GridSubsetHandler::assign_subset(), ug::promesh::CopySubsetIndicesToSides(), ug::promesh::Mesh::grid(), grid(), ug::SubsetInfo::name, ug::ISubsetHandler::num_subsets(), ug::promesh::Mesh::position_attachment(), ug::promesh::Mesh::subset_handler(), ug::ISubsetHandler::subset_info(), ug::Tetrahedralize(), and UG_LOG.
TriangleFill()
void ug::promesh::TriangleFill (Mesh * obj, bool qualityGeneration, number minAngle, int si)
References ug::ISelector::autoselection_enabled(), ug::TElemSelector< class >::begin(), ug::Selector::begin(), ug::Selector::clear(), ug::promesh::CloseSelection(), ug::promesh::CopySubsetIndicesToSides(), ug::Selector::edges_begin(), ug::Selector::edges_end(), ug::ISelector::enable_autoselection(), ug::TElemSelector< class >::end(), ug::Selector::end(), ug::promesh::Mesh::grid(), grid(), ug::Selector::num(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::position_attachment(), ug::QualityGridGeneration(), ug::RemoveDuplicates(), ug::ISelector::select(), ug::promesh::Mesh::selector(), ug::promesh::Mesh::subset_handler(), ug::TriangleFill_SweepLine(), and UG_LOG.
UnassignSubsets()
void ug::promesh::UnassignSubsets (Mesh * obj, bool vertices, bool edges, bool faces, bool volumes)
References ug::promesh::AssignSubset(), and vertices().
Referenced by ug::promesh::RegisterSubsetTools().
UnmarkSelection()
void ug::promesh::UnmarkSelection (Mesh * obj)
References ug::GridSubsetHandler::assign_subset(), ug::Selector::begin(), ug::promesh::Mesh::crease_handler(), ug::Selector::end(), ug::REM_NONE, and ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
VolumeSelectionFill()
void ug::promesh::VolumeSelectionFill (Mesh * obj)
References ug::promesh::Mesh::selector().
Referenced by ug::promesh::RegisterSelectionTools().
WeightedEdgeSmooth()
void ug::promesh::WeightedEdgeSmooth (Mesh * obj, number alpha, int numIterations)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), WeightedEdgeSmooth(), and ug::WeightedEdgeSmooth().
WeightedFaceSmooth()
void ug::promesh::WeightedFaceSmooth (Mesh * obj, number alpha, int numIterations)
References ug::Selector::begin(), ug::Selector::end(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), WeightedFaceSmooth(), and ug::WeightedFaceSmooth().
WeightedNormalSmooth()
void ug::promesh::WeightedNormalSmooth (Mesh * obj, number alpha, number dotThreshold, int numIterations)
References ug::Grid::begin(), CollectVerticesTouchingSelection(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), WeightedNormalSmooth(), and ug::WeightedNormalSmooth().