Plugins: UGRegistry Documentation
UGRegistry Documentation
Plugins
Plugin for generating documentation of registered classes and methods.
Functions
void ug::DocuGen::WriteCompletionList (std::vector< UGDocuClassDescription > &classesAndGroupsAndImplementations, bool bSilent, ClassHierarchy &hierarchy)
Variables
vector< UGDocuClassDescription > ug::DocuGen::classes
vector< UGDocuClassDescription > ug::DocuGen::classesAndGroups
vector< UGDocuClassDescription > ug::DocuGen::classesAndGroupsAndImplementations
Detailed Description
Plugin for generating documentation of registered classes and methods.
This plugin generates the documentation of all registered classes and methods of the linked libug4. Depending on command line parameters either HTML or C++ files are generated.
Usage:
ugshell -call GenerateScriptReferenceDocu\\‍(\\"regdocu\\", true, false, true, false\\‍)
Parameters:
string outputPath
path of the output directory for the html, cpp files and completion list
bool silent
don't print verbose progress info, only warnings
bool generateHTML
generates legacy HTML docu
bool generateCPP
generates dummy C++ code from registered functions ready to be parsed by Doxygen
bool generateList
generates completion list
Function Documentation
WriteCompletionList()
void ug::DocuGen::WriteCompletionList (std::vector< UGDocuClassDescription > & classesAndGroupsAndImplementations, bool bSilent, ClassHierarchy & hierarchy)
References ug::DocuGen::AddLuaDebugCompletions(), ug::bridge::IExportedClass::class_names(), ug::DocuGen::classesAndGroupsAndImplementations, ug::LogAssistant::enable_terminal_output(), ug::bridge::IExportedClass::get_const_method_group(), ug::bridge::IExportedClass::get_constructor(), ug::bridge::Registry::get_function_group(), ug::bridge::IExportedClass::get_method_group(), ug::bridge::ExportedFunctionGroup::get_overload(), ug::bridge::ExportedMethodGroup::get_overload(), GetLogAssistant(), GetUGRegistry(), ug::bridge::ExportedFunction::group(), ug::bridge::IExportedClass::group(), ug::bridge::IExportedClass::name(), ug::bridge::IExportedClass::num_const_methods(), ug::bridge::IExportedClass::num_constructors(), ug::bridge::Registry::num_functions(), ug::bridge::IExportedClass::num_methods(), ug::bridge::ExportedFunctionGroup::num_overloads(), ug::bridge::ExportedMethodGroup::num_overloads(), ROOT_PATH, UG_CATCH_THROW_FUNC, UG_LOG, ug::DocuGen::WriteClassCompleter(), ug::DocuGen::WriteConstructorCompleter(), and ug::DocuGen::WriteFunctionCompleter().
Variable Documentation
classes
vector< UGDocuClassDescription > ug::DocuGen::classes
Referenced by ug::DocuGen::GetClassGroup(), ug::DocuGen::GetClassGroupStd(), ug::DocuGen::GetGroups(), ug::DocuGen::GetUGDocuClassDescription(), and ug::DocuGen::WriteHTMLDocu().
classesAndGroups
vector< UGDocuClassDescription > ug::DocuGen::classesAndGroups
Referenced by ug::GenerateScriptReferenceDocu(), ug::DocuGen::GetGroups(), ug::DocuGen::WriteClassIndex(), and ug::DocuGen::WriteHTMLDocu().
classesAndGroupsAndImplementations
vector< UGDocuClassDescription > ug::DocuGen::classesAndGroupsAndImplementations
Referenced by ug::GenerateScriptReferenceDocu(), ug::DocuGen::GetGroups(), and ug::DocuGen::WriteCompletionList().