var modules =
[
    [ "Plugins", "group__plugins.html", "group__plugins" ],
    [ "Apps_ugdocu", "group__apps__ugdocu.html", "group__apps__ugdocu" ],
    [ "DocuGen", "group___docu_gen.html", null ],
    [ "Algebra Bridge", "../group__algebra__bridge.html", null ],
    [ "Domain Dependend Preconditioner Bridge", "../group__domdepprecond__bridge.html", null ],
    [ "Eigensolver Bridge", "../group__eigensolver__bridge.html", null ],
    [ "Preconditioner Bridge", "../group__precond__bridge.html", "group__precond__bridge" ],
    [ "Obstacle Bridge", "../group__obstacle__bridge.html", null ],
    [ "Solver Bridge", "../group__solver__bridge.html", null ],
    [ "Bridge", "../group__bridge.html", "group__bridge" ],
    [ "Adaptive Tools Bridge", "../group__adaptivetools__bridge.html", null ],
    [ "Discretization Algebra Bridge", "../group__discalgebra__bridge.html", null ],
    [ "Common Discretization Bridge", "../group__disccommon__bridge.html", "group__disccommon__bridge" ],
    [ "Constraints Bridge", "../group__constraints__bridge.html", null ],
    [ "Discretization Bridge", "../group__disc__bridge.html", null ],
    [ "Domain Discretization Bridge", "../group__domaindisc__bridge.html", null ],
    [ "Element Discretization Bridge", "../group__elemdisc__bridge.html", null ],
    [ "Interpolation Bridge", "../group__interpolate__bridge.html", "group__interpolate__bridge" ],
    [ "Finite Volume Bridge", "../group__finitvolume__bridge.html", null ],
    [ "Grid Function Bridge", "../group__gridfnct__bridge.html", null ],
    [ "Integration Bridge", "../group__integrate__bridge.html", null ],
    [ "Multi Grid Bridge", "../group__multigrid__bridge.html", null ],
    [ "Ordering Bridge", "../group__ordering__bridge.html", null ],
    [ "Output Bridge", "../group__output__bridge.html", "group__output__bridge" ],
    [ "User Data Bridge", "../group__userdata__bridge.html", "group__userdata__bridge" ],
    [ "Domain Bridge", "../group__domain__bridge.html", "group__domain__bridge" ],
    [ "Load Balancing Bridge", "../group__loadbalance__bridge.html", "group__loadbalance__bridge" ],
    [ "Periodic Bounadry Bridge", "../group__periodic__bridge.html", "group__periodic__bridge" ],
    [ "Refinement Bridge", "../group__refinement__bridge.html", "group__refinement__bridge" ],
    [ "Selection Bridge", "../group__selection__bridge.html", "group__selection__bridge" ],
    [ "Transformation Bridge", "../group__transform__bridge.html", "group__transform__bridge" ],
    [ "libGrid Bridge", "../group__libgrid__bridge.html", null ],
    [ "Misc Bridge", "../group__misc__bridge.html", "group__misc__bridge" ],
    [ "PCL Bridge", "../group__pcl__bridge.html", "group__pcl__bridge" ],
    [ "Profiler Bridge", "../group__profiler__bridge.html", "group__profiler__bridge" ],
    [ "Test Bridge", "../group__test__bridge.html", "group__test__bridge" ],
    [ "Utility Bridge", "../group__util__bridge.html", "group__util__bridge" ],
    [ "VecMath Bridge", "../group__vecmath__bridge.html", "group__vecmath__bridge" ],
    [ "Common", "../group__ugbase__common.html", "group__ugbase__common" ],
    [ "Matrix", "../group__math__matrix.html", "group__math__matrix" ],
    [ "Tensor", "../group__math__tensor.html", "group__math__tensor" ],
    [ "Vectors", "../group__vectors.html", "group__vectors" ],
    [ "Math Utilities", "../group__ugbase__mathutil.html", "group__ugbase__mathutil" ],
    [ "Math", "../group__ugbase__math.html", "group__ugbase__math" ],
    [ "String Utilities", "../group__ugbase__common__util__strings.html", "group__ugbase__common__util__strings" ],
    [ "Common Utilities", "../group__ugbase__common__util.html", "group__ugbase__common__util" ],
    [ "Common IO", "../group__ugbase__common__io.html", "group__ugbase__common__io" ],
    [ "Common Types", "../group__ugbase__common__types.html", "group__ugbase__common__types" ],
    [ "CompileInfo", "../group__ugbase__compileinfo.html", "group__ugbase__compileinfo" ],
    [ "MatrixIO", "../group__matrixio.html", null ],
    [ "CPU Algebra", "../group__cpu__algebra.html", "group__cpu__algebra" ],
    [ "CRS Algebra", "../group__crs__algebra.html", "group__crs__algebra" ],
    [ "lib_algebra", "../group__lib__algebra.html", "group__lib__algebra" ],
    [ "lib_algebra Common", "../group__lib__algebra__common.html", null ],
    [ "Parallel Algebra Communication Policies", "../group__lib__algebra__parallelization__policies.html", null ],
    [ "Parallel Algebra Communication Scheme", "../group__lib__algebra__parallelization__scheme.html", "group__lib__algebra__parallelization__scheme" ],
    [ "Parallel Algebra Consistency Check", "../group__lib__algebra__parallel__consistencycheck.html", "group__lib__algebra__parallel__consistencycheck" ],
    [ "Parallel Algebra", "../group__lib__algebra__parallelization.html", "group__lib__algebra__parallelization" ],
    [ "Parallel Algebra Util", "../group__lib__algebra__parallelization__util.html", "group__lib__algebra__parallelization__util" ],
    [ "Small Algebra", "../group__small__algebra.html", "group__small__algebra" ],
    [ "Assembling", "../group__lib__disc__assemble.html", null ],
    [ "Domain", "../group__lib__disc__domain.html", "group__lib__disc__domain" ],
    [ "lib_discretization", "../group__lib__discretization.html", "group__lib__discretization" ],
    [ "Local Finite Elements", "../group__lib__disc__local__finite__elements.html", null ],
    [ "Quadrature Rules", "../group__lib__discretization__quadrature__rules.html", null ],
    [ "Elem Disc", "../group__lib__disc__elem__disc.html", null ],
    [ "User Data", "../group__lib__disc__user__data.html", "group__lib__disc__user__data" ],
    [ "algorithms", "../group__lib__grid__algorithms.html", null ],
    [ "refinement", "../group__lib__grid__algorithms__refinement.html", "group__lib__grid__algorithms__refinement" ],
    [ "remeshing", "../group__lib__grid__algorithms__remeshing.html", "group__lib__grid__algorithms__remeshing" ],
    [ "trees", "../group__lib__grid__algorithms__trees.html", "group__lib__grid__algorithms__trees" ],
    [ "subdivision", "../group__lib__grid__algorithms__refinement__subdivision.html", "group__lib__grid__algorithms__refinement__subdivision" ],
    [ "grid generation", "../group__lib__grid__algorithms__grid__generation.html", "group__lib__grid__algorithms__grid__generation" ],
    [ "attachment util", "../group__lib__grid__algorithms__attachment__util.html", "group__lib__grid__algorithms__attachment__util" ],
    [ "log util", "../group__lib__grid__algorithms__log__util.html", "group__lib__grid__algorithms__log__util" ],
    [ "extrusion", "../group__lib__grid__algorithms__extrusion.html", "group__lib__grid__algorithms__extrusion" ],
    [ "edge util", "../group__lib__grid__algorithms__edge__util.html", "group__lib__grid__algorithms__edge__util" ],
    [ "face util", "../group__lib__grid__algorithms__face__util.html", "group__lib__grid__algorithms__face__util" ],
    [ "misc geometric object util", "../group__lib__grid__algorithms__geom__obj__misc.html", "group__lib__grid__algorithms__geom__obj__misc" ],
    [ "vertex util", "../group__lib__grid__algorithms__vertex__util.html", "group__lib__grid__algorithms__vertex__util" ],
    [ "volume util", "../group__lib__grid__algorithms__volume__util.html", "group__lib__grid__algorithms__volume__util" ],
    [ "normal_calculation", "../group__lib__grid__algorithms__normal__calculation.html", "group__lib__grid__algorithms__normal__calculation" ],
    [ "polygonal-chain util", "../group__lib__grid__algorithms__polychain__util.html", "group__lib__grid__algorithms__polychain__util" ],
    [ "selection util", "../group__lib__grid__algorithms__selection__util.html", "group__lib__grid__algorithms__selection__util" ],
    [ "serialization", "../group__lib__grid__algorithms__serialization.html", "group__lib__grid__algorithms__serialization" ],
    [ "subset util", "../group__lib__grid__algorithms__subset__util.html", "group__lib__grid__algorithms__subset__util" ],
    [ "volume_calculation", "../group__lib__grid__algorithms__volume__calculation.html", "group__lib__grid__algorithms__volume__calculation" ],
    [ "element_callbacks", "../group__lib__grid__element__callbacks.html", null ],
    [ "grid", "../group__lib__grid__grid.html", "group__lib__grid__grid" ],
    [ "geometric objects", "../group__lib__grid__grid__objects.html", null ],
    [ "neighborhood util", "../group__lib__grid__algorithms__neighborhood__util.html", "group__lib__grid__algorithms__neighborhood__util" ],
    [ "lib_grid", "../group__lib__grid.html", "group__lib__grid" ],
    [ "parallelization", "../group__lib__grid__parallelization.html", "group__lib__grid__parallelization" ],
    [ "parallel refinement", "../group__lib__grid__parallelization__refinement.html", "group__lib__grid__parallelization__refinement" ],
    [ "parallel distribution", "../group__lib__grid__parallelization__distribution.html", "group__lib__grid__parallelization__distribution" ],
    [ "parallel utilities", "../group__lib__grid__parallelization__util.html", null ],
    [ "grid-tools", "../group__lib__grid__tools.html", "group__lib__grid__tools" ],
    [ "PCL", "../group__pcl.html", "group__pcl" ],
    [ "Registry", "../group__registry.html", "group__registry" ],
    [ "UGShell", "../group__ugbase__ugshell.html", "group__ugbase__ugshell" ],
    [ "ugbase", "../group__ugbase.html", null ],
    [ "Algebracommon_bridge", "../group__algebracommon__bridge.html", null ]
];