Plugins: ug::DocuGen Namespace Reference
ug::DocuGen Namespace Reference
App for generating documentation of registered classes and methods.
Namespaces
Doxygen
Organization unit for Doxygen commands.
Classes
class ClassHierarchyProvider
class CppGenerator
Generator to produce valid but dummy C++ files from registered classes and functions.
class UGDocuClassDescription
class UGRegistryGroup
Functions
void AddLuaDebugCompletions (ostream &f)
bool ClassGroupDescSort (const ClassGroupDesc *i, const ClassGroupDesc *j)
std::string ConstructorInfoHTML (std::string classname, const bridge::ExportedConstructor &thefunc, std::string group)
string ConstructorInfoHTML (string classname, const bridge::ExportedConstructor &thefunc, string group)
bool ExportedClassSort (const IExportedClass *i, const IExportedClass *j)
bool ExportedFunctionsGroupSort (const bridge::ExportedFunction *i, const bridge::ExportedFunction *j)
bool ExportedFunctionsSort (const bridge::ExportedFunctionBase *i, const bridge::ExportedFunctionBase *j)
string FunctionInfoHTML (const bridge::ExportedFunctionBase &thefunc, const char *group)
string FunctionInfoHTML (const bridge::ExportedFunctionBase &thefunc, const IExportedClass *c, bool bConst)
std::string GetBeautifiedTag (std::string tag)
string GetBeautifiedTag (string tag)
string GetClassGroup (string classname)
string GetClassGroupStd (string classname)
std::string GetFilenameForGroup (std::string s, std::string dir="")
string GetFilenameForGroup (string s, string dir)
void GetGroups (std::map< string, UGRegistryGroup > &g)
void GetGroups (std::vector< UGDocuClassDescription > &classes, std::vector< UGDocuClassDescription > &classesAndGroups, std::vector< UGDocuClassDescription > &classesAndGroupsAndImplementations)
UGDocuClassDescription * GetUGDocuClassDescription (std::vector< UGDocuClassDescription > &classes, const IExportedClass *c)
bool GroupNameSortFunction (const UGDocuClassDescription &i, const UGDocuClassDescription &j)
bool IsPluginGroup (std::string g)
bool IsPluginGroup (string g)
bool NameSortFunction (const UGDocuClassDescription &i, const UGDocuClassDescription &j)
void ParameterToString (ostream &file, const bridge::ParameterInfo &par, int i, bool bHTML)
void ParameterToString (std::ostream &file, const bridge::ParameterInfo &par, int i, bool bHTML)
void PrintClassFunctionsHMTL (ostream &file, const IExportedClass *c, bool bInherited)
void PrintClassFunctionsHMTL (std::ostream &file, const bridge::IExportedClass *c, bool bInherited)
template<typename T >
void remove_doubles (vector< T > &v)
std::string tohtmlstring (const std::string &str)
string tohtmlstring (const string &str)
void WriteClassCompleter (ostream &classhtml, UGDocuClassDescription *d, ClassHierarchy &hierarchy)
void WriteClassHierarchy (const char *dir, ClassHierarchy &hierarchy)
void WriteClassHierarchy (ostream &file, ClassHierarchy &c)
void WriteClassHierarchy (std::ostream &file, bridge::ClassHierarchy &c)
void WriteClassHTML (const char *dir, UGDocuClassDescription *d, ClassHierarchy &hierarchy)
void WriteClassIndex (const char *dir, std::vector< UGDocuClassDescription > &classesAndGroups, bool bGroup)
bool WriteClassUsageExact (const std::string &preamble, std::ostream &file, const char *classname, bool OutParameters)
bool WriteClassUsageExact (const string &preamble, ostream &file, const char *classname, bool OutParameters)
void WriteCompletionList (std::vector< UGDocuClassDescription > &classesAndGroupsAndImplementations, bool bSilent, ClassHierarchy &hierarchy)
void WriteCompletionList (std::vector< UGDocuClassDescription > classesAndGroupsAndImplementations, bool bSilent)
void WriteConstructorCompleter (ostream &f, string classname, const bridge::ExportedConstructor &thefunc, string group)
void WriteFooter (fstream &file)
void WriteFooter (std::fstream &file)
void WriteFunctionCompleter (ostream &f, const char *desc, const bridge::ExportedFunctionBase &thefunc, string group, const char *pClass=NULL, bool bConst=false)
void WriteFunctionHTMLCompleter (ostream &file, const bridge::ExportedFunctionBase &thefunc, const char *group, const char *pClass)
template<typename TSortFunction >
void WriteGlobalFunctions (const char *dir, const char *filename, TSortFunction sortFunction)
void WriteGroups (const char *dir, std::vector< UGDocuClassDescription > &classesAndGroups)
void WriteHeader (fstream &file, const string &title)
void WriteHeader (std::fstream &file, const std::string &title)
void WriteHTMLDocu (std::vector< UGDocuClassDescription > &classes, std::vector< UGDocuClassDescription > &classesAndGroups, const char *dir, ClassHierarchy &hierarchy)
template<typename T >
static void WriteParametersIn (std::ostream &file, const T &thefunc, bool bHTML=true)
template<typename T >
static void WriteParametersOut (std::ostream &file, const T &thefunc, bool bHTML=true)
void WriteUGDocuCSS (const char *dir)
Variables
vector< UGDocuClassDescription > classes
vector< UGDocuClassDescription > classesAndGroups
vector< UGDocuClassDescription > classesAndGroupsAndImplementations
Detailed Description
App for generating documentation of registered classes and methods.
Function Documentation
ConstructorInfoHTML()
string ug::DocuGen::ConstructorInfoHTML (string classname, const bridge::ExportedConstructor & thefunc, string group)
References ug::bridge::ExportedConstructor::help(), ug::bridge::ExportedConstructor::tooltip(), UG_CATCH_THROW_FUNC, WriteParametersIn(), and XMLStringEscape().
Referenced by PrintClassFunctionsHMTL().
GetBeautifiedTag()
string ug::DocuGen::GetBeautifiedTag (string tag)
References ReplaceAll().
Referenced by WriteClassHTML().
GetClassGroup()
string ug::DocuGen::GetClassGroup (string classname)
References classes, ug::bridge::Registry::get_class(), GetUGDocuClassDescription(), GetUGRegistry(), ug::DocuGen::UGDocuClassDescription::mp_group, and ug::bridge::ClassGroupDesc::name().
Referenced by FunctionInfoHTML(), PrintClassFunctionsHMTL(), WriteClassHierarchy(), and WriteClassHTML().
GetClassGroupStd()
string ug::DocuGen::GetClassGroupStd (string classname)
References classes, ug::bridge::Registry::get_class(), ug::bridge::ClassGroupDesc::get_default_class(), GetUGDocuClassDescription(), GetUGRegistry(), ug::DocuGen::UGDocuClassDescription::mp_group, and ug::bridge::IExportedClass::name().
GetFilenameForGroup()
string ug::DocuGen::GetFilenameForGroup (string s, string dir)
References IsPluginGroup(), ReplaceAll(), and s.
Referenced by WriteClassHTML(), and WriteGroups().
GetGroups() [1/2]
void ug::DocuGen::GetGroups (std::map< string, UGRegistryGroup > & g)
References classesAndGroups, ExportedFunctionsSort(), ug::bridge::Registry::get_function_group(), ug::bridge::ExportedFunctionGroup::get_overload(), GetUGRegistry(), ug::bridge::ExportedFunction::group(), ug::bridge::ExportedFunctionBase::name(), ug::bridge::Registry::num_functions(), ug::bridge::ExportedFunctionGroup::num_overloads(), UG_CATCH_THROW_FUNC, and UG_LOG.
Referenced by ug::GenerateScriptReferenceDocu(), and WriteGroups().
GetGroups() [2/2]
void ug::DocuGen::GetGroups (std::vector< UGDocuClassDescription > & classes, std::vector< UGDocuClassDescription > & classesAndGroups, std::vector< UGDocuClassDescription > & classesAndGroupsAndImplementations)
References classes, classesAndGroups, classesAndGroupsAndImplementations, ug::bridge::Registry::get_class(), ug::bridge::ClassGroupDesc::get_class(), ug::bridge::Registry::get_class_group(), ug::bridge::ClassGroupDesc::get_class_tag(), GetUGDocuClassDescription(), GetUGRegistry(), ug::DocuGen::UGDocuClassDescription::mp_group, NameSortFunction(), ug::bridge::Registry::num_class_groups(), ug::bridge::Registry::num_classes(), ug::bridge::ClassGroupDesc::num_classes(), ug::DocuGen::UGDocuClassDescription::tag, and UG_CATCH_THROW_FUNC.
GetUGDocuClassDescription()
UGDocuClassDescription * ug::DocuGen::GetUGDocuClassDescription (std::vector< UGDocuClassDescription > & classes, const IExportedClass * c)
References classes, and NameSortFunction().
Referenced by GetClassGroup(), GetClassGroupStd(), GetGroups(), and WriteHTMLDocu().
GroupNameSortFunction()
bool ug::DocuGen::GroupNameSortFunction (const UGDocuClassDescription & i, const UGDocuClassDescription & j)
References ug::DocuGen::UGDocuClassDescription::group_str(), and ug::DocuGen::UGDocuClassDescription::name().
Referenced by WriteClassIndex().
IsPluginGroup()
bool ug::DocuGen::IsPluginGroup (string g)
References StartsWith().
Referenced by GetFilenameForGroup(), and WriteGroups().
NameSortFunction()
bool ug::DocuGen::NameSortFunction (const UGDocuClassDescription & i, const UGDocuClassDescription & j)
References ug::DocuGen::UGDocuClassDescription::name().
Referenced by GetGroups(), GetUGDocuClassDescription(), and WriteClassIndex().
ParameterToString()
void ug::DocuGen::ParameterToString (ostream & file, const bridge::ParameterInfo & par, int i, bool bHTML)
References XMLStringEscape().
Referenced by WriteParametersIn(), and WriteParametersOut().
PrintClassFunctionsHMTL()
void ug::DocuGen::PrintClassFunctionsHMTL (ostream & file, const IExportedClass * c, bool bInherited)
References ConstructorInfoHTML(), ExportedFunctionsSort(), FunctionInfoHTML(), ug::bridge::IExportedClass::get_const_method_group(), ug::bridge::IExportedClass::get_constructor(), ug::bridge::IExportedClass::get_method_group(), ug::bridge::ExportedMethodGroup::get_overload(), GetClassGroup(), ug::bridge::IExportedClass::group(), ug::bridge::IExportedClass::name(), ug::bridge::IExportedClass::num_const_methods(), ug::bridge::IExportedClass::num_constructors(), ug::bridge::IExportedClass::num_methods(), ug::bridge::ExportedMethodGroup::num_overloads(), and UG_CATCH_THROW_FUNC.
Referenced by WriteClassCompleter(), and WriteClassHTML().
remove_doubles()
template<typename T > void ug::DocuGen::remove_doubles (vector< T > & v)
Referenced by WriteClassUsageExact(), WriteGlobalFunctions(), and WriteGroups().
tohtmlstring()
string ug::DocuGen::tohtmlstring (const string & str)
Referenced by WriteHeader().
WriteClassHierarchy()
void ug::DocuGen::WriteClassHierarchy (ostream & file, ClassHierarchy & c)
References ug::bridge::ClassHierarchy::bGroup, GetClassGroup(), ug::bridge::ClassHierarchy::name, and ug::bridge::ClassHierarchy::subclasses.
WriteClassUsageExact()
bool ug::DocuGen::WriteClassUsageExact (const string & preamble, ostream & file, const char * classname, bool OutParameters)
Parameters
classname the class (and only this class) to print usage in functions/member functions of.
References FunctionInfoHTML(), ug::bridge::Registry::get_class(), ug::bridge::IExportedClass::get_const_method_group(), ug::bridge::Registry::get_function(), ug::bridge::IExportedClass::get_method_group(), ug::bridge::ExportedMethodGroup::get_overload(), GetUGRegistry(), IsClassInParameters(), ug::bridge::Registry::num_classes(), ug::bridge::IExportedClass::num_const_methods(), ug::bridge::Registry::num_functions(), ug::bridge::IExportedClass::num_methods(), ug::bridge::ExportedMethodGroup::num_overloads(), ug::bridge::ExportedFunctionBase::params_in(), ug::bridge::ExportedFunctionBase::params_out(), remove_doubles(), and UG_CATCH_THROW_FUNC.
Referenced by WriteClassCompleter(), and WriteClassHTML().
WriteFooter()
void ug::DocuGen::WriteFooter (fstream & file)
Referenced by WriteClassHierarchy(), WriteClassHTML(), WriteClassIndex(), WriteGlobalFunctions(), and WriteGroups().
WriteGlobalFunctions()
template<typename TSortFunction > void ug::DocuGen::WriteGlobalFunctions (const char * dir, const char * filename, TSortFunction sortFunction)
References FunctionInfoHTML(), ug::bridge::Registry::get_function_group(), ug::bridge::ExportedFunctionGroup::get_overload(), GetUGRegistry(), ug::bridge::Registry::num_functions(), ug::bridge::ExportedFunctionGroup::num_overloads(), remove_doubles(), UG_CATCH_THROW_FUNC, UG_LOG, WriteFooter(), and WriteHeader().
Referenced by WriteHTMLDocu().
WriteGroups()
void ug::DocuGen::WriteGroups (const char * dir, std::vector< UGDocuClassDescription > & classesAndGroups)
References FunctionInfoHTML(), ug::bridge::ClassGroupDesc::get_default_class(), GetFilenameForGroup(), GetGroups(), ug::DocuGen::UGDocuClassDescription::group_str(), IsPluginGroup(), ug::DocuGen::UGDocuClassDescription::mp_class, ug::DocuGen::UGDocuClassDescription::mp_group, ug::DocuGen::UGDocuClassDescription::name(), ug::bridge::ClassGroupDesc::name(), ug::bridge::IExportedClass::name(), remove_doubles(), UG_CATCH_THROW_FUNC, UG_LOG, WriteFooter(), and WriteHeader().
Referenced by WriteHTMLDocu().
WriteHeader()
void ug::DocuGen::WriteHeader (fstream & file, const string & title)
References clickEventHandler_txt, local(), tohtmlstring(), and UGSvnRevision().
Referenced by WriteClassHierarchy(), WriteClassHTML(), WriteClassIndex(), WriteGlobalFunctions(), and WriteGroups().