Plugins: ug::ConvectionDiffusionPlugin Namespace Reference
ug::ConvectionDiffusionPlugin Namespace Reference
Classes
class cd_line_sss_data
class cd_point_sss_data
class cd_sss_data
class for data for all the CD plugin sources and sinks
class CDSingularSourcesAndSinks
class ConvectionDiffusionBase
Discretization for the Convection-Diffusion Equation.
class ConvectionDiffusionFE
Discretization for the Convection-Diffusion Equation.
class ConvectionDiffusionFractFV1
Discretization for the Convection-Diffusion Equation in fractures.
class ConvectionDiffusionFV
Discretization for the Convection-Diffusion Equation.
class ConvectionDiffusionFV1
FV Discretization for the Convection-Diffusion Equation.
class ConvectionDiffusionFVCR
Discretization for the Convection-Diffusion Equation.
class ConvectionDiffusionStabFE
Discretization for the Convection-Diffusion Equation.
struct Functionality
struct Functionality2d3d
class line_sss_marker
class point_sss_marker
Functions
template<class TVector >
static TVector CalculateCenter (GridObject *o, const TVector *coords)
Variables
DebugID DID_CONV_DIFF_FV1 ("CONV_DIFF_FV1")
Function Documentation
CalculateCenter()
template<class TVector > static TVector ug::ConvectionDiffusionPlugin::CalculateCenter (GridObject * o, const TVector * coords) static
References ug::GridObject::base_object_id(), ug::EDGE, ug::FACE, num_vertices(), UG_THROW, ug::VecAdd(), ug::VecScale(), ug::VecSet(), ug::VERTEX, and ug::VOLUME.
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_A_elem().
Variable Documentation
DID_CONV_DIFF_FV1
DebugID ug::ConvectionDiffusionPlugin::DID_CONV_DIFF_FV1("CONV_DIFF_FV1") ("CONV_DIFF_FV1")
Referenced by ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::add_jac_A_elem(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFV1< TDomain >::prep_elem().