Plugins: ug::DemoPlugin Namespace Reference
ug::DemoPlugin Namespace Reference
Classes
class DemoClass
A basic class used to demonstrate registration of classes for scripting.
Typedefs
typedef CPUAlgebra::matrix_type matrix_type
Sparse matrix type as defined in lib_algebra/cpu_algebra/sparsematrix.h.
typedef CPUAlgebra::vector_type vector_type
Vector type as defined in lib_algebra/cpu_algebra/vector.h.
Functions
number DemoMatCompSumFast (matrix_type &m)
number DemoMatCompSumSlow (matrix_type &m)
Calculates the sum of all coefficients of the given matrix and returns it.
void DemoPluginSaysHi ()
Prints a welcome message.
number DemoVecCompSum (vector_type &v)
Calculates the sum of all coefficients of the given vector and returns it.
Typedef Documentation
matrix_type
typedef CPUAlgebra::matrix_type ug::DemoPlugin::matrix_type
Sparse matrix type as defined in lib_algebra/cpu_algebra/sparsematrix.h.
vector_type
typedef CPUAlgebra::vector_type ug::DemoPlugin::vector_type
Vector type as defined in lib_algebra/cpu_algebra/vector.h.
Function Documentation
DemoMatCompSumFast()
number ug::DemoPlugin::DemoMatCompSumFast (matrix_type & m)
This implementation has O(n) if the underlying matrix has a sparse structure.
Referenced by ug::InitUGPlugin_DemoPlugin().
DemoMatCompSumSlow()
number ug::DemoPlugin::DemoMatCompSumSlow (matrix_type & m)
Calculates the sum of all coefficients of the given matrix and returns it.
This implementation has O(n^2), even if the underlying matrix has a sparse structure. Have a look at DemoMatCompSumFast for a O(n) variant (for sparse matrices).
Referenced by ug::InitUGPlugin_DemoPlugin().
DemoPluginSaysHi()
void ug::DemoPlugin::DemoPluginSaysHi ()
Prints a welcome message.
Referenced by ug::InitUGPlugin_DemoPlugin().
DemoVecCompSum()
number ug::DemoPlugin::DemoVecCompSum (vector_type & v)
Calculates the sum of all coefficients of the given vector and returns it.
References ug::Vector< class >::size().
Referenced by ug::InitUGPlugin_DemoPlugin().