Plugins: ug Namespace Reference
ug Namespace Reference
Namespaces
BGLParallelMatrix
bridge
CompositeConvCheck
CompositeTimeDiscretization
ConnectionViewer
ConstrainedLinearIterator
ConvectionDiffusionPlugin
CRFVGeometry
DelaunayInfo
DemoPlugin
detail
DimCRFVGeometry
DimFEGeometry
DimFV1Geometry
DimFV1IBGeometry
DimFVGeometry
DirichletBoundary
DistributedGridManager
DocuGen
App for generating documentation of registered classes and methods.
DoFCount
DoFDistribution
domain_wrappers
Electromagnetism
element_list_traits
Factory
fieldutil
FunctionPattern
FV1Geometry_gen
FV1IBGeometry
FV1ManifoldGeometry
FVGeometry
GlobalAttachments
GPUSparseMatrix
Grid
grid_intersection_impl
grid_unit_tests
GridFunction
GridObjectCollection
GridReaderUGX
GridReaderVTU
GridWriterUGX
Hash
HCRFVGeometry
hex_rules
HFV1ManifoldGeometry
IDWUserData
impl
IObstacleConstraint
Jupyter
KDTree
Limex
LocalFiniteElementProvider
luashell
MapSparseMatrix
MessageHub
MGSelector
MGStats
NavierStokes
NeumannBoundaryBase
NeumannBoundaryFE
NeumannBoundaryFV
NeumannBoundaryFV1
NeuriteProjector
node_tree
ntree
ObstacleInNormalDir
oct_rules
ParallelNodes
Partitioner_DynamicBisection
PeriodicBoundaryManager
prism_rules
ProcessHierarchy
promesh
pyra_rules
Raster
raster_kernels
RasterLayers
Richards
script
SectionContainer
shared_rules
SideAndElemErrEstData
SliceIndexView
SmallStrainMechanics
SparseMatrix
SparseVector
StringTableStream
SubdivRules_PLoop
SurfaceView
swc_types
TemplatePlugin
tet_rules
tools
UGXFileInfo
UndirectedMatrix
util
VectorTimeSeries
vrl
Classes
struct AABox
struct ab
class AbsoluteMarking
class ActiveSet
class AdaptionSurfaceGridFunction
class AdaptiveRegularRefiner_MultiGrid
struct AdjustEdgeLengthDesc
class AgglomeratingBase
class AgglomeratingIterator
class AgglomeratingPreconditioner
class AgglomeratingSolver
class AitkenNevilleTimex
class AlgebraDebugWriter
class AlgebraicConnection
class AlgebraicConvCheck
class AlgebraicSpace
struct AlgebraID
class AlgebraLayouts
class AlgebraType
class AlphaMat_Expression
class AlphaMatVec_X_Expression
class AlphaVec_Expression
class AnalyzingSolver
class AnisotropicBalanceWeights
class APosterioriCoarsening
class ApproximationSpace
class Archivar
struct ArchiveInfo
struct AspectRatioInfo
class AssembledLinearOperator
class AssembledMultiGridCycle
class AssembledOperator
class AssembledTransformingSmoother
class AssemblingTuner
class AssocElemIter
class AttachedElementList
class AttachedElementListIterator
class Attachment
struct attachment_info_traits
struct attachment_io_traits
struct attachment_io_traits< Attachment< bool > >
struct attachment_io_traits< Attachment< std::vector< T > > >
struct attachment_io_traits< Attachment< vector1 > >
struct attachment_io_traits< Attachment< vector2 > >
struct attachment_io_traits< Attachment< vector3 > >
struct attachment_io_traits< Attachment< vector4 > >
struct attachment_reduce_traits
struct attachment_reduce_traits< double >
struct attachment_reduce_traits< float >
struct attachment_reduce_traits< MathVector< 1 > >
struct attachment_reduce_traits< MathVector< 2 > >
struct attachment_reduce_traits< MathVector< 3 > >
struct attachment_reduce_traits< MathVector< 4 > >
struct attachment_reduce_traits< std::vector< number > >
class attachment_traits
class attachment_traits< Edge *, ElementStorage< Edge > >
class attachment_traits< Face *, ElementStorage< Face > >
class attachment_traits< Vertex *, ElementStorage< Vertex > >
class attachment_traits< Volume *, ElementStorage< Volume > >
struct attachment_value_traits
struct attachment_value_traits< bool >
class AttachmentAccessor
class AttachmentDataContainer
struct AttachmentEntry
class AttachmentPipe
class AttachmentUnequal
class AutoLinearSolver
class AverageComponent
class BackwardGaussSeidel
class BalanceWeightsLuaCallback
class BalanceWeightsRefMarks
class Base64FileWriter
class BaseLSFS
class BaseReferenceMapping
class BDF
class BGLParallelMatrix
class BiCGStab
class BidirectionalMatrix
class BinaryBuffer
class BinaryStream
class BinaryStreamBuffer
class BinghamViscosityLinker
struct BinomialCoefficient
struct BinomialCoefficient< n, 0 >
struct BinomialCoefficient< n,-1 >
struct BinomialCoefficient< n,-2 >
struct BinomialCoefficient< n,-3 >
struct BinomialCoefficient< n,-4 >
struct block_multiply_traits
struct block_multiply_traits< DenseMatrix< T >, DenseMatrix< T > >
struct block_multiply_traits< DenseMatrix< T1 >, DenseVector< T2 > >
struct block_multiply_traits< number, number >
struct block_multiply_traits< number, T >
struct block_multiply_traits< T, number >
struct block_multiply_traits< T1, T2 >
struct block_traits
struct block_traits< DenseMatrix< FixedArray2< number, 1, 1, TOrdering > > >
struct block_traits< DenseMatrix< FixedArray2< number, 2, 2, TOrdering > > >
struct block_traits< DenseMatrix< FixedArray2< number, 3, 3, TOrdering > > >
struct block_traits< DenseMatrix< FixedArray2< number, TBlockSize, TBlockSize, TOrdering > > >
struct block_traits< DenseMatrix< FixedArray2< TValue, TBlockSize, TBlockSize, TOrdering > > >
struct block_traits< DenseMatrix< T > >
struct block_traits< DenseMatrix< VariableArray2< number, TOrdering > > >
struct block_traits< DenseMatrix< VariableArray2< TValue, TOrdering > > >
struct block_traits< DenseVector< T > >
struct block_traits< number >
struct block_traits< T >
struct block_traits< vector< int > >
class BlockGaussSeidel
class BlockGaussSeidelIterative
class BlockSliceIndexView
class BOOL
class BoolMarker
class BoostCuthillMcKeeOrdering
class BoostMinimumDegreeOrdering
class BoundedEquidistantLagrange1D
class BoxPriorityQueue
class BoxPriorityQueue2
struct CellIdx
class CG
class cgraph
struct ChainInfo
class ClusterElementStacks
class CmpVrtsByHash
class CombinedLinearIterator
class CommonLocalDoFSet
class CommunicationScheme
class CommunicationScheme< TDerived, bool >
class CompareByAttachment
struct CompareDeg
struct CompareDegree
class ComPol_AdjustType
class ComPol_AttachmentReduce
class ComPol_BoolMarker_AddMarks
class ComPol_BoolMarker_RemoveMarks
class ComPol_BroadcastCoarsenMarks
class ComPol_BroadcastRefineMarks
class ComPol_CheckConsistency
class ComPol_CheckDistributedParentStates
class ComPol_CopyAttachment
class ComPol_EnableSelectionStateBits
class ComPol_GatherSurfaceStates
class ComPol_GatherVecAttachment
class ComPol_InterfaceStatus
class ComPol_MatAddRowsOverlap0
class ComPol_MatAddSetZeroInnerInterfaceCouplings
class ComPol_MatCopyDiag
class ComPol_MatCopyRowsOverlap0
class ComPol_MatCreateOverlap
class ComPol_MatDistributeDiag
class ComPol_NewConstrainedVerticals
class ComPol_Selection
class ComPol_Subset
class ComPol_SynchronizeDistInfos
class ComPol_VecAdd
class ComPol_VecAddSetZero
class ComPol_VecCopy
class ComPol_VecScaleAdd
class ComPol_VecScaleCopy
class ComPol_VecSubtract
class ComPol_VecSubtractOnlyOneSlave
class ComponentGaussSeidel
class CompositeConvCheck
class CompositeGridFunctionEstimator
Evaluate difference between two functions (w.r.t various norms)
class CompositeSpace
class CompositeTimeDiscretization
class CompositeUserData
struct ConnectedToOneMarkedVrt
class ConnectionViewerOutputObserver
Sample class for integration observer: Output to VTK.
class ConsiderAll
class ConsiderNone
class ConsistencyCheckClass
class ConsistencyCheckClassSend
class ConsistencyCheckClassSend< TVec, bool >
class const_localMatrix_from_mat_and_array
class const_ntree_element_iterator
class ConstantDamping
class ConstAttachedElementListIterator
class ConstGenericGridObjectIterator
class ConstMatrixRow
class ConstrainedEdge
class ConstrainedFace
class ConstrainedLinearIterator
class ConstrainedQuadrilateral
class ConstrainedTriangle
class ConstrainedVertex
class ConstrainingEdge
class ConstrainingFace
class ConstrainingQuadrilateral
class ConstrainingTriangle
struct constraint_traits
struct constraint_traits< Edge >
struct constraint_traits< Face >
struct constraint_traits< Quadrilateral >
struct constraint_traits< Triangle >
struct constraint_traits< Vertex >
struct ConstructGridOfSCVFWrapper
struct ConstructGridOfSCVFWrapper< TFVGeom, 1 >
struct ConstructGridOfSCVFWrapper< TFVGeom, 2 >
struct ConstructGridOfSCVFWrapper< TFVGeom, 3 >
struct ConstructGridOfSCVWrapper
struct ConstructGridOfSCVWrapper< TFVGeom, 1 >
struct ConstructGridOfSCVWrapper< TFVGeom, 2 >
struct ConstructGridOfSCVWrapper< TFVGeom, 3 >
class ConstScalarSubVectorAdapter
class ConstStepLinearTimeIntegrator
Integrate over a given time interval (for a linear problem)
class ConstUserMatrix
class ConstUserNumber
class ConstUserTensor
class ConstUserVector
class ConvectionShapesFullUpwind
class ConvectionShapesNoUpwind
class ConvectionShapesPartialUpwind
class ConvectionShapesWeightedUpwind
class CopyAttachmentHandler
class CplUserData
struct CPUAlgebra
struct CPUBlockAlgebra
struct CPUVariableBlockAlgebra
struct crfv_traits
struct crfv_traits< 1, 1 >
struct crfv_traits< 1, 2 >
struct crfv_traits< 2, 2 >
struct crfv_traits< 2, 3 >
struct crfv_traits< 3, 3 >
struct crfv_traits< 3, 4 >
class CRFVGeometry
class CRILUTPreconditioner
CRILUTPreconditioner class.
class CrouzeixRaviartBase
class CrouzeixRaviartElemTransfer
class CrouzeixRaviartLSFS
class CrouzeixRaviartLSFS< ReferenceHexahedron >
class CrouzeixRaviartLSFS< ReferencePrism >
class CrouzeixRaviartLSFS< ReferencePyramid >
class CrouzeixRaviartLSFS< ReferenceQuadrilateral >
class CrouzeixRaviartLSFS< ReferenceTetrahedron >
class CrouzeixRaviartLSFS< ReferenceTriangle >
class CuckooClock
class CUDAManager
class customLexLess
class CustomQuadrilateral
class CustomTriangle
class CustomVertexGroup
class CylinderCutProjector
class CylinderProjector
class DarcyVelocityLinker
class DataEvaluator
class DataEvaluatorBase
class DataExport
class DataImport
class DebugID
class DebugIDManager
class DebugIterator
class DebugWriterContext
class DebugWritingObject
class DefaultAlgebra
class DegeneratedLayerManager
class DelaunayDebugSaver
class DelaunayInfo
class DeltaSquareIntegrand
class DenseMatrix
struct DenseMatrixFromSparseMatrix
class DenseMatrixInverse
class DenseVector
class DependentUserData
class DiagVanka
class DimCRFVGeometry
class DimFEGeometry
class DimFV1Geometry
class DimFV1IBGeometry
class DimFVGeometry
class DimHFV1Geometry
class DimLocalDoFSet
class DimReferenceElement
class DimReferenceMapping
class DimReferenceMappingWrapper
class DiracSourceDisc
class DirectionalOrdering
class dirichlet_iterator
class DirichletBoundary
class DiscConstraintFVCR
class DiscontinuityIntegrator
This class integrates (t0, t1] with stops at intermediate points tk.
class DistInfoSupplier
class DistributedGridManager
class DistroAdjuster
class DoFCount
class DoFDistribution
class DoFDistributionInfo
class DoFDistributionInfoProvider
class DoFIndexStorage
class Domain
struct domain_traits
struct domain_traits< 0 >
struct domain_traits< 1 >
struct domain_traits< 2 >
struct domain_traits< 3 >
class DomainBalanceWeights
class DomainCommunicationCostWeights
class DomainDiscretization
class DomainDiscretizationBase
class DomainInfo
class DomainLoadBalancer
class DomainPartitioner
class DomainRayTracer
class DualGraphNeighborCollector
class Edge
class EdgeDescriptor
class EdgeOrientation
class EdgeVertices
class element_list_traits
class ElementCallback
class ElementGaussSeidel
struct ElementSideRayIntersectionWrapper
struct ElementSideRayIntersectionWrapper< TRefElem, 2, 2 >
struct ElementSideRayIntersectionWrapper< TRefElem, 3, 3 >
class ElementStorage
struct ElementStorageSelector
struct ElementStorageSelector< Edge >
struct ElementStorageSelector< Face >
struct ElementStorageSelector< Vertex >
struct ElementStorageSelector< Volume >
struct ElemErrorSortDesc
class ElemProlongationBase
class ElemRestrictionBase
class EllipticCylinderProjector
class EmptyOStream
class EmptyStreamBuffer
struct EmptyType
struct end_boost_list
class EnergyConvCheck
class EquidistantLagrange1D
class EquilibrationMarkingStrategy
class ErrorEvaluator
class ExpectedErrorMarkingStrategy
class ExplicitGridFunctionGradient
class ExplicitGridFunctionValue
class ExplicitGridFunctionVector
class Face
struct face_type_traits
struct face_type_traits< 1 >
struct face_type_traits< 2 >
struct face_type_traits< 3 >
class FaceDescriptor
class FaceVertices
struct Factorial
struct Factorial< 1 >
class Factory
class FEGeometry
class FetiLayouts
class FETISolver
class Field
class FileReaderASC
class FileReaderSWC
class FileWriterSWC
class FinishedTester
class FixedArray1
class FixedArray1< T, 1 >
class FixedArray1< T, 2 >
class FixedArray1< T, 3 >
class FixedArray1< T, 4 >
class FixedArray2
class FixedConvergenceCheck
class Flag
class FlexGaussQuadrature
class FlexLagrangeLSFS
class FlexLagrangeLSFS< ReferenceEdge >
class FlexLagrangeLSFS< ReferenceHexahedron >
class FlexLagrangeLSFS< ReferencePrism >
class FlexLagrangeLSFS< ReferenceQuadrilateral >
class FlexLagrangeLSFS< ReferenceTetrahedron >
class FlexLagrangeLSFS< ReferenceTriangle >
class FlexLagrangeLSFS< ReferenceVertex >
class FracturedMediaRefiner
struct FractureInfo
class FullVertexCover
class FunctionGroup
class FunctionIndexMapping
class FunctionPattern
struct fv1_dim_traits
struct fv1_dim_traits< 1, 1 >
struct fv1_dim_traits< 1, 2 >
struct fv1_dim_traits< 1, 3 >
struct fv1_dim_traits< 2, 2 >
struct fv1_dim_traits< 2, 3 >
struct fv1_dim_traits< 3, 3 >
struct fv1_dim_traits_base
struct fv1_traits
struct fv1_traits< ReferenceEdge, 1 >
struct fv1_traits< ReferenceEdge, 2 >
struct fv1_traits< ReferenceEdge, 3 >
struct fv1_traits< ReferenceHexahedron, 3 >
struct fv1_traits< ReferenceOctahedron, 3 >
struct fv1_traits< ReferencePrism, 3 >
struct fv1_traits< ReferencePyramid, 3 >
struct fv1_traits< ReferenceQuadrilateral, 2 >
struct fv1_traits< ReferenceQuadrilateral, 3 >
struct fv1_traits< ReferenceTetrahedron, 3 >
struct fv1_traits< ReferenceTriangle, 2 >
struct fv1_traits< ReferenceTriangle, 3 >
struct fv1_traits_most_common
struct fv1_traits_ReferenceEdge
struct fv1_traits_ReferenceFace
struct fv1_traits_ReferenceFace2d
struct fv1_traits_ReferenceFace3d
struct fv1_traits_ReferenceOctahedron
struct fv1_traits_ReferencePyramid
struct fv1_traits_ReferenceVolume
class FV1CondensedGeometry
class FV1Geometry
class FV1Geometry_gen
class FV1IBGeometry
class FV1InnerBoundaryElemDisc
class FV1ManifoldGeometry
class FVGeometry
class FVGeometryBase
struct fvho_traits
class FVLineSourceOrSink
class FVLineSourceOrSink< 1, TData >
class FVPointSourceOrSink
class FVSingularSourcesAndSinks
class GaussJacobi10
class GaussJacobi20
class GaussLegendre
class GaussQuadBase
class GaussQuadrature
class GaussQuadrature< ReferenceEdge, 0 >
class GaussQuadrature< ReferenceEdge, 1 >
class GaussQuadrature< ReferenceEdge, 10 >
class GaussQuadrature< ReferenceEdge, 11 >
class GaussQuadrature< ReferenceEdge, 12 >
class GaussQuadrature< ReferenceEdge, 13 >
class GaussQuadrature< ReferenceEdge, 14 >
class GaussQuadrature< ReferenceEdge, 15 >
class GaussQuadrature< ReferenceEdge, 16 >
class GaussQuadrature< ReferenceEdge, 17 >
class GaussQuadrature< ReferenceEdge, 18 >
class GaussQuadrature< ReferenceEdge, 19 >
class GaussQuadrature< ReferenceEdge, 2 >
class GaussQuadrature< ReferenceEdge, 3 >
class GaussQuadrature< ReferenceEdge, 4 >
class GaussQuadrature< ReferenceEdge, 5 >
class GaussQuadrature< ReferenceEdge, 6 >
class GaussQuadrature< ReferenceEdge, 7 >
class GaussQuadrature< ReferenceEdge, 8 >
class GaussQuadrature< ReferenceEdge, 9 >
class GaussQuadrature< ReferenceHexahedron, 0 >
class GaussQuadrature< ReferenceHexahedron, 1 >
class GaussQuadrature< ReferenceHexahedron, 10 >
class GaussQuadrature< ReferenceHexahedron, 11 >
class GaussQuadrature< ReferenceHexahedron, 2 >
class GaussQuadrature< ReferenceHexahedron, 3 >
class GaussQuadrature< ReferenceHexahedron, 4 >
class GaussQuadrature< ReferenceHexahedron, 5 >
class GaussQuadrature< ReferenceHexahedron, 6 >
class GaussQuadrature< ReferenceHexahedron, 7 >
class GaussQuadrature< ReferenceHexahedron, 8 >
class GaussQuadrature< ReferenceHexahedron, 9 >
class GaussQuadrature< ReferenceOctahedron, 0 >
class GaussQuadrature< ReferenceOctahedron, 1 >
class GaussQuadrature< ReferenceOctahedron, 2 >
class GaussQuadrature< ReferencePrism, 0 >
class GaussQuadrature< ReferencePrism, 1 >
class GaussQuadrature< ReferencePrism, 2 >
class GaussQuadrature< ReferencePyramid, 0 >
class GaussQuadrature< ReferencePyramid, 1 >
class GaussQuadrature< ReferencePyramid, 2 >
class GaussQuadrature< ReferenceQuadrilateral, 0 >
class GaussQuadrature< ReferenceQuadrilateral, 1 >
class GaussQuadrature< ReferenceQuadrilateral, 10 >
class GaussQuadrature< ReferenceQuadrilateral, 11 >
class GaussQuadrature< ReferenceQuadrilateral, 12 >
class GaussQuadrature< ReferenceQuadrilateral, 13 >
class GaussQuadrature< ReferenceQuadrilateral, 2 >
class GaussQuadrature< ReferenceQuadrilateral, 3 >
class GaussQuadrature< ReferenceQuadrilateral, 4 >
class GaussQuadrature< ReferenceQuadrilateral, 5 >
class GaussQuadrature< ReferenceQuadrilateral, 6 >
class GaussQuadrature< ReferenceQuadrilateral, 7 >
class GaussQuadrature< ReferenceQuadrilateral, 8 >
class GaussQuadrature< ReferenceQuadrilateral, 9 >
class GaussQuadrature< ReferenceTetrahedron, 0 >
class GaussQuadrature< ReferenceTetrahedron, 1 >
class GaussQuadrature< ReferenceTetrahedron, 2 >
class GaussQuadrature< ReferenceTetrahedron, 3 >
class GaussQuadrature< ReferenceTetrahedron, 4 >
class GaussQuadrature< ReferenceTetrahedron, 5 >
class GaussQuadrature< ReferenceTetrahedron, 6 >
class GaussQuadrature< ReferenceTetrahedron, 7 >
class GaussQuadrature< ReferenceTetrahedron, 8 >
class GaussQuadrature< ReferenceTriangle, 0 >
class GaussQuadrature< ReferenceTriangle, 1 >
class GaussQuadrature< ReferenceTriangle, 10 >
class GaussQuadrature< ReferenceTriangle, 11 >
class GaussQuadrature< ReferenceTriangle, 12 >
class GaussQuadrature< ReferenceTriangle, 2 >
class GaussQuadrature< ReferenceTriangle, 3 >
class GaussQuadrature< ReferenceTriangle, 4 >
class GaussQuadrature< ReferenceTriangle, 5 >
class GaussQuadrature< ReferenceTriangle, 6 >
class GaussQuadrature< ReferenceTriangle, 7 >
class GaussQuadrature< ReferenceTriangle, 8 >
class GaussQuadrature< ReferenceTriangle, 9 >
class GaussQuadrature< ReferenceVertex, 0 >
class GaussQuadrature< ReferenceVertex, 1 >
class GaussQuadrature< ReferenceVertex, 10 >
class GaussQuadrature< ReferenceVertex, 11 >
class GaussQuadrature< ReferenceVertex, 12 >
class GaussQuadrature< ReferenceVertex, 13 >
class GaussQuadrature< ReferenceVertex, 14 >
class GaussQuadrature< ReferenceVertex, 15 >
class GaussQuadrature< ReferenceVertex, 16 >
class GaussQuadrature< ReferenceVertex, 17 >
class GaussQuadrature< ReferenceVertex, 18 >
class GaussQuadrature< ReferenceVertex, 19 >
class GaussQuadrature< ReferenceVertex, 2 >
class GaussQuadrature< ReferenceVertex, 3 >
class GaussQuadrature< ReferenceVertex, 4 >
class GaussQuadrature< ReferenceVertex, 5 >
class GaussQuadrature< ReferenceVertex, 6 >
class GaussQuadrature< ReferenceVertex, 7 >
class GaussQuadrature< ReferenceVertex, 8 >
class GaussQuadrature< ReferenceVertex, 9 >
class GaussQuadratureHexahedron
class GaussQuadratureOctahedron
class GaussQuadraturePrism
class GaussQuadraturePyramid
class GaussQuadratureQuadrilateral
class GaussQuadratureTetrahedron
class GaussQuadratureTriangle
class GaussQuadratureVertex
class GaussSeidel
class GaussSeidelBase
class GenerateOverlapClass
class GenericGridObjectIterator
class Geometry
class geometry_traits
class geometry_traits< ConstrainedEdge >
class geometry_traits< ConstrainedQuadrilateral >
class geometry_traits< ConstrainedTriangle >
class geometry_traits< ConstrainedVertex >
class geometry_traits< ConstrainingEdge >
class geometry_traits< ConstrainingQuadrilateral >
class geometry_traits< ConstrainingTriangle >
class geometry_traits< Edge >
class geometry_traits< Face >
class geometry_traits< GridObject >
class geometry_traits< Hexahedron >
class geometry_traits< Octahedron >
class geometry_traits< Prism >
class geometry_traits< Pyramid >
class geometry_traits< Quadrilateral >
class geometry_traits< RegularEdge >
class geometry_traits< RegularVertex >
class geometry_traits< Tetrahedron >
class geometry_traits< Triangle >
class geometry_traits< Vertex >
class geometry_traits< Volume >
class GeomObjAttachmentSerializer
struct GeomObjBaseTypeByDim
struct GeomObjBaseTypeByDim< 0 >
struct GeomObjBaseTypeByDim< 1 >
struct GeomObjBaseTypeByDim< 2 >
struct GeomObjBaseTypeByDim< 3 >
class GeomObjDataSerializer
class GeomProvider
class GlobalAttachments
class GlobalFracturedMediaRefiner
class GlobalGridFunctionGradientData
class GlobalGridFunctionNumberData
class GlobalMarking
class GlobalMultiGridRefiner
class GlobalSubdivisionMultiGridRefiner
class GlobAttachmentElementUserData
class GMRES
class GPUSparseMatrix
class GPUVector
class GradientDataExport
class GradientEvaluator_LagrangeP1
class Grid
struct grid_dim_traits
struct grid_dim_traits< 0 >
struct grid_dim_traits< 1 >
struct grid_dim_traits< 2 >
struct grid_dim_traits< 3 >
class grid_global_debug_info_provider
class GridDataSerializationHandler
class GridDataSerializer
class GridFunction
class GridFunctionComponentSpace
class GridFunctionDebugWriter
class GridFunctionEstimator
Evaluate using continuous norms.
class GridFunctionGradientComponentData
class GridFunctionGradientData
class GridFunctionNumberData
class GridFunctionOrdering
class GridFunctionPositionProvider
class GridFunctionVectorData
class GridFunctionVectorWriter
class GridFunctionVectorWriterDirichlet0
struct GridHeader
class GridLayoutMap
class GridLevel
class GridMessage_Adaption
class GridMessage_Creation
class GridMessage_Distribution
class GridMessage_MultiGridChanged
class GridObject
class GridObjectCollection
struct GridObjectInfo
class GridObserver
class GridPointsOrdering
class GridReaderUGX
class GridReaderVTU
class GridSubsetHandler
class GridWriterUGX
class GridWriterVTU
class H1ComponentSpace
class H1DistIntegrand
class H1EnergyComponentSpace
class H1EnergyDistIntegrand
class H1EnergyIntegrand
class H1ErrorIntegrand
class H1NormIntegrand
class H1SemiComponentSpace
class H1SemiDistIntegrand
class H1SemiIntegrand
class HangingNodeRefiner_Grid
class HangingNodeRefiner_MultiGrid
class HangingNodeRefinerBase
class Hash
class hash_iterator
struct hcrfv_traits
struct hcrfv_traits< 2, 2 >
struct hcrfv_traits< 2, 3 >
struct hcrfv_traits< 3, 3 >
struct hcrfv_traits< 3, 4 >
class HCRFVGeometry
struct hdimfv1_traits
struct hdimfv1_traits< 1 >
struct hdimfv1_traits< 2 >
struct hdimfv1_traits< 3 >
class Heightfield
class Hexahedron
class HexahedronClass
class HexahedronDescriptor
struct hfv1_traits
struct hfv1_traits< ReferenceEdge, 1 >
struct hfv1_traits< ReferenceEdge, 2 >
struct hfv1_traits< ReferenceEdge, 3 >
struct hfv1_traits< ReferenceHexahedron, 3 >
struct hfv1_traits< ReferenceOctahedron, 3 >
struct hfv1_traits< ReferencePrism, 3 >
struct hfv1_traits< ReferencePyramid, 3 >
struct hfv1_traits< ReferenceQuadrilateral, 2 >
struct hfv1_traits< ReferenceQuadrilateral, 3 >
struct hfv1_traits< ReferenceTetrahedron, 3 >
struct hfv1_traits< ReferenceTriangle, 2 >
struct hfv1_traits< ReferenceTriangle, 3 >
struct hfv1_traits_ReferenceEdge
struct hfv1_traits_ReferenceFace
struct hfv1_traits_ReferenceVolume
class HFV1Geometry
class HFV1ManifoldGeometry
class HorizontalAlgebraLayouts
class HorizontalAnisotropyAdjuster
class IApproximationSpace
class IAssemble
class IAttachment
class IAttachmentDataContainer
class IBalanceWeights
class IBanachSpace
class IBlockJacobiPreconditioner
class ICommunicationWeights
class IComponentSpace
class IConstraint
class IConvectionShapes
class IConvergenceCheck
class ICplUserData
class IDamping
class IDataImport
class IDebugWriter
class IDiscretizationItem
class IDomain
class IDomainConstraint
class IDomainDiscretization
class IDomainErrorIndicator
class IDomainMarker
class IDWInterpolation
class IDWUserData
class IEigensolver
class IElemAssembleFuncs
class IElemDisc
class IElemDiscBase
class IElemDiscModifier
class IElementMarkingStrategy
class IElemError
class IElemEstimatorFuncs
class IElemProlongation
class IElemRestriction
class IErrEstData
class IExternalSolver
class IExternalSolverImplementation
class IFinishedCondition
class IFunction
class IGeometry
class IGridFunction
class IGridFunctionSpace
class IIdentifier
class IIntegrand
class IInterfaceExtrapolation
class ILagrangeMultiplierDisc
class ILevelPreconditioner
class ILimexCostStrategy
Abstract class for the cost of a limex stage.
class ILimexRefiner
class ILinearIterator
class ILinearOperator
class ILinearOperatorInverse
class ILinearTimeIntegrator
integration of linear systems
class ILineSearch
class ILocalRemesher
class ILocalSubspace
class ILocalToGlobalMapper
class ILU
class ILUTPreconditioner
class ILUTScalarPreconditioner
class IMatrixOperatorInverse
class IMultigridElementIndicators
struct IndCmp
class IndexView
class INewtonUpdate
struct InnerBoundaryConstants
struct InnerBoundaryFluxCond
struct InnerBoundaryFluxDerivCond
class INonlinearTimeIntegrator
integration of non-linear systems (with bounds on dt)
struct Int2Type
class IntegrationOutputObserver
Integration observer: Output using Lua callback.
class InterSubsetPartitionWeighting
class IntervalNumberLinker
class InverseLinker
class IObjectWithWeights
class IObstacleConstraint
class IOperator
class IOperatorInverse
class IOrderingAlgorithm
class IPartitioner
class IPartitionPostProcessor
class IPartitionPreProcessor
class IPatchRemesher
class IPositionProvider
class IPProcessVector
class IPreconditionedLinearOperatorInverse
class IPreconditioner
class IProjGaussSeidel
class IRefiner
class IRefMarkAdjuster
class IsBoundaryOrManifodFace
class ISchurComplementInverse
class ISelector
class IsInSubGrid
class IsInSubset
class IsMarked
class IsNotBoundaryOrManifodFace
class IsNotInSubGrid
class IsNotInSubset
class IsNotMarked
class IsNotOnBoundary
class IsNotSelected
class IsOnBoundary
class ISpaceDecomposition
class IsRegularSurfaceElem
class IsSelected
class ISubDiagErrorEst
Interface for sub-diagonal error estimator (w.r.t time in Aitken-Neville scheme)
class ISubGrid
class ISubsetHandler
struct IteratorProvider
struct IteratorProvider< MGSubsetHandler >
class ITimeDiscDependentObject
ITimeDiscDependentObject.
class ITimeDiscretization
class ITimeIntegrator
Integrates over a given time interval [a,b] with step size dt.
class ITimeIntegratorObserver
class ITransferOperator
class ITransferPostProcess
class ITransformingIteration
class IVector
class IVector_AlgebraDownCastTo
class IVectorDebugWriter
class IVectorWriter
class IVertexGroup
class Jacobi
class KDTree
struct KDTreeDesc
class KDTreeStatic
class KDVertexDistance
class L2ComponentSpace
class L2DistIntegrand
class L2ErrorIntegrand
class L2Integrand
class L2QuotientSpace
class Lagrange1D
class LagrangeLDS
class LagrangeLSFS
class LagrangeLSFS< ReferenceEdge, TOrder >
class LagrangeLSFS< ReferenceHexahedron, TOrder >
class LagrangeLSFS< ReferenceOctahedron, TOrder >
class LagrangeLSFS< ReferencePrism, TOrder >
class LagrangeLSFS< ReferencePyramid, TOrder >
class LagrangeLSFS< ReferenceQuadrilateral, TOrder >
class LagrangeLSFS< ReferenceTetrahedron, TOrder >
class LagrangeLSFS< ReferenceTriangle, TOrder >
class LagrangeLSFS< ReferenceVertex, TOrder >
class LagrangeP1
class LexOrdering
class LFEID
class lg_ntree
struct lg_ntree_traits_base
class LimexDefaultCost
Cost is identical to (summation over) number of steps.
class LimexNewtonSolver
Newton solver for assembling-based discretizations solved using Limex.
class LimexNonlinearCost
For.
class LimexTimeIntegrator
Base class for LIMEX time integrator.
class LimexTimeIntegratorConfig
class LinearImplicitEuler
class LinearIteratorProduct
class LinearIteratorSum
class LinearSolver
class LinearTimeIntegrator
Integrate over a given time interval (for a linear problem)
class LineGaussSeidel
class LineVanka
struct linker_traits
struct linker_traits< MathMatrix< dim, dim >, number >
struct linker_traits< MathTensor< 4, dim >, number >
struct linker_traits< MathVector< dim >, MathMatrix< dim, dim > >
struct linker_traits< MathVector< dim >, MathVector< dim >, number >
struct linker_traits< MathVector< dim >, number >
struct linker_traits< number, number >
class LoadBalancer
class LoaderObj
class LocalDoF
class LocalDoFSet
class LocalDoFSubspace
class LocalFiniteElementProvider
class LocalIndexSubspace
class LocalIndices
class LocalMarkAdjuster
class LocalMatrix
class localMatrix_from_col_major_and_array
class localMatrix_from_mat_and_array
class localMatrix_from_row_major_and_array
class LocalSchurComplement
class LocalShapeFunctionSet
class LocalShapeFunctionSetWrapper
class LocalToGlobalMapper
class LocalToGlobalMapperNLGS
class LocalVector
class localVector_from_array
class LocalVectorTimeSeries
class LogAssistant
class LognormalRandomField
class LSGFConstraint
class LSGFDomainDiscretization
class LSGFGlobAssembler
class LU
struct lua_traits
struct lua_traits< bool >
struct lua_traits< int >
struct lua_traits< MathMatrix< dim, dim > >
struct lua_traits< number >
struct lua_traits< ug::MathVector< dim > >
struct lua_traits< void >
class LuaCallbackObserver
class LuaFunction
class LuaFunctionHandle
class LUAParserClass
class LuaTableHandle
class LuaUserData
class LuaUserDataFactory
class LuaUserFunction
class LuaUserNumberNumberFunction
class MapSparseMatrix
class MapVector
struct MarkerPoint
class MarkerPointManager
struct mat_operations_class
struct mat_operations_class< vector_t, matrix_t, MATRIX_USE_GLOBAL_FUNCTIONS >
struct mat_operations_class< vector_t, matrix_t, MATRIX_USE_MEMBER_FUNCTIONS >
struct mat_operations_class< vector_t, matrix_t, MATRIX_USE_OPERATORS >
struct mat_operations_class< vector_t, matrix_t, MATRIX_USE_ROW_FUNCTIONS >
class MathMatrix
class MathMatrix< 0, 0, T >
class MathMatrix< 0, N, T >
class MathMatrix< N, 0, T >
class MathSymmetricMatrix
class MathTensor
class MathTensor1
class MathTensor2
class MathTensor3
class MathTensor4
class MathTensor< 1, N, T >
class MathTensorX
class MathVector
class MathVector< 0, T >
class MathVector< 1, T >
class MathVector< 2, T >
class MathVector< 3, T >
class MathVector< 4, T >
struct matrix_algebra_type_traits
struct matrix_algebra_type_traits< DenseMatrix< T > >
struct matrix_algebra_type_traits< DenseMatrixInverse< T > >
struct matrix_algebra_type_traits< GPUSparseMatrix< T > >
struct matrix_algebra_type_traits< MapSparseMatrix< T > >
struct matrix_algebra_type_traits< MatrixOperator< M, X, Y > >
struct matrix_algebra_type_traits< ParallelMatrix< T > >
struct matrix_algebra_type_traits< SparseMatrix< T > >
class MatrixDiagonal
class MatrixDiagonalInverse
class MatrixFileType
class MatrixIO
class MatrixIOMtx
class MatrixOperator
class MatrixRow
class MatVec_Expression
class maxheap
class MaximumDistIntegrand
class MaximumMarking
class MaxStepsFinishedCondition
class MeanValueMarking
class MemInfo
class MemTrackerStruct
class MessageHub
struct MGEdgeInfo
struct MGFaceInfo
class MGHNodeAdjuster
class mginfo_traits
class mginfo_traits< Edge >
class mginfo_traits< Face >
class mginfo_traits< Vertex >
class mginfo_traits< Volume >
class MGSelector
class MGStats
struct MGVertexInfo
struct MGVolumeInfo
class MGWrapper
class MGWrapper< Grid >
class MGWrapper< MultiGrid >
struct MidID
class MiniBubbleLDS
class MiniBubbleLSFS
class MiniBubbleLSFS< ReferenceEdge >
class MiniBubbleLSFS< ReferenceHexahedron >
class MiniBubbleLSFS< ReferenceQuadrilateral >
class MiniBubbleLSFS< ReferenceTetrahedron >
class MiniBubbleLSFS< ReferenceTriangle >
class MinimalEnergyDamping
class MinimalResiduumDamping
class MMTypeCode
class MultiElementAttachmentAccessor
class MultiGrid
class MultiGridSubsetHandler
class MultiIndex
class MultiIndex< 1, size_t >
class MultiIndex< 2, size_t >
class MultiIndex< 3, size_t >
class MultipleErrEstData
class MultipleSideAndElemErrEstData
class MultiStepTimeDiscretization
struct MyVectorTraits
struct MyVectorTraits< TVector, typename boost::enable_if_c< TVector::value_type::is_static >::type >
class NativeCuthillMcKeeOrdering
class NedelecLDS
class NedelecLSFS
class NedelecLSFS< ReferenceTetrahedron >
class NedelecLSFS< ReferenceTriangle >
class NestedIterationSolver
class NeumannBoundaryBase
class NeumannBoundaryFE
class NeumannBoundaryFV
class NeumannBoundaryFV1
class NeuriteProjector
class NewLayoutCreator
class NewtonCotes
class NewtonSolver
class NLGaussSeidelSolver
class NLJacobiSolver
class non_dirichlet_iterator
class Norm2Estimator
Evaluate using (algebraic) L2 norm.
class NormInfEstimator
Evaluate using (algebraic) infinity norm.
class NormRelEstimator
Evaluate using (algebraic) L2 norm.
class ntree
struct ntree_traits
struct ntree_traits< 1, 1, elem_t, NTreeGridData< 1 > >
struct ntree_traits< 1, 2, elem_t, NTreeGridData< 2 > >
struct ntree_traits< 2, 2, elem_t, NTreeGridData< 2 > >
struct ntree_traits< 2, 3, elem_t, NTreeGridData< 3 > >
struct ntree_traits< 3, 3, elem_t, NTreeGridData< 3 > >
struct NTreeDesc
class NTreeGridData
struct OBJMaterial
class ObstacleInNormalDir
class Octahedron
class OctahedronClass
class OctahedronDescriptor
class OneSideP1Constraints
struct operation_add
struct operation_sub
class OperatorInverseIterator
class OStreamBufferSplitter
class OutNormCmp
class OverlapWriter
class OverlyingSubsetFinder
class OwnedPtr
class P1LagrangeElemTransfer
class PageContainer
class ParallelColoring
class ParallelDualGraph
class ParallelGlobalFracturedMediaRefiner
class ParallelGlobalSubdivisionRefiner
class ParallelHangingNodeRefiner_MultiGrid
class ParallelHNodeAdjuster
class ParallelMatrix
class ParallelNodes
class ParallelProgress
class ParallelShiftIdentifier
class ParallelVector
class Partitioner_DynamicBisection
class PartitionMap
class PartitionWeighting
class PartPreProc_RasterProjectorCoordinates
class PathProvider
class PCRILUTPreconditioner
PCRILUTPreconditioner class.
class PeriodicAttachmentAccessor
class PeriodicBoundaryManager
class PiecewiseConstantElemTransfer
class PiecewiseConstantLSFS
class PILUTPreconditioner
class PINVIT
class PlaneCutProjector
class PlotRefOutputObserver
struct Pointer2Value
struct Pointer2Value< T * >
class PointerConstArray
class Polynomial1D
struct PosAndIndex
struct Pow
struct Pow< n, 0 >
class PowerMethod
class PPP_ReplaceCoordinate
class PProcessChain
struct PrimalConnection
class PrimalSubassembledMatrixInverse
class Prism
class PrismClass
class PrismDescriptor
class ProcessHierarchy
class Progress
class ProjBackwardGaussSeidel
class ProjectionHandler
class ProjectionLinker
class ProjGaussSeidel
class ProjSymmetricGaussSeidel
class ProtectSubsetPartitionWeighting
class Provider
struct PtrToValueType
struct PtrToValueType< Edge * >
struct PtrToValueType< Face * >
struct PtrToValueType< Vertex * >
struct PtrToValueType< Volume * >
class Pyramid
class PyramidClass
class PyramidDescriptor
class QuadratureRule
class QuadratureRuleProvider
class Quadrilateral
class QuadrilateralDescriptor
class Raster
struct RasterLayerDesc
class RasterLayers
class RasterLayersProjector
class RasterUserData
struct RayElemIntersectionRecord
struct reference_element_traits
struct reference_element_traits< ConstrainedEdge >
struct reference_element_traits< ConstrainedQuadrilateral >
struct reference_element_traits< ConstrainedTriangle >
struct reference_element_traits< ConstrainedVertex >
struct reference_element_traits< ConstrainingEdge >
struct reference_element_traits< ConstrainingQuadrilateral >
struct reference_element_traits< ConstrainingTriangle >
struct reference_element_traits< Edge >
struct reference_element_traits< Hexahedron >
struct reference_element_traits< Octahedron >
struct reference_element_traits< Prism >
struct reference_element_traits< Pyramid >
struct reference_element_traits< Quadrilateral >
struct reference_element_traits< RegularEdge >
struct reference_element_traits< RegularVertex >
struct reference_element_traits< Tetrahedron >
struct reference_element_traits< Triangle >
struct reference_element_traits< Vertex >
class ReferenceEdge
class ReferenceElement
class ReferenceElementProvider
class ReferenceHexahedron
class ReferenceMapping
class ReferenceMapping< ReferenceEdge, TWorldDim >
class ReferenceMapping< ReferenceHexahedron, TWorldDim >
class ReferenceMapping< ReferenceOctahedron, TWorldDim >
class ReferenceMapping< ReferencePrism, TWorldDim >
class ReferenceMapping< ReferencePyramid, TWorldDim >
class ReferenceMapping< ReferenceQuadrilateral, TWorldDim >
class ReferenceMapping< ReferenceTetrahedron, TWorldDim >
class ReferenceMapping< ReferenceTriangle, TWorldDim >
class ReferenceMapping< ReferenceVertex, TWorldDim >
class ReferenceMappingProvider
class ReferenceOctahedron
class ReferencePrism
class ReferencePyramid
class ReferenceQuadrilateral
class ReferenceTetrahedron
class ReferenceTriangle
class ReferenceVertex
class RefinementProjector
class RegularEdge
class RegularVertex
class ReservableArray2
class RevisionCounter
class RiverOrdering
class RotatingCone2d
class RotatingVelocity2d
class RowSendingScheme
class ScalarGridFunctionData
class ScalarLowerObstacle
class ScalarSubVectorAdapter
class ScalarUpperObstacle
class ScaleAddLinker
class ScaledGridFunctionEstimator
Evaluate difference between two functions (w.r.t various norms)
class SCCOrdering
class SchurComplementMatrixOperator
class SchurComplementOperator
class SchurInverseWithAGammaGamma
class SchurInverseWithAutoFullMatrix
class SchurInverseWithFullMatrix
class SchurInverseWithOperator
class SchurPrecond
struct SCVFofSCVRayIntersectionWrapper
struct SCVFofSCVRayIntersectionWrapper< 2, 2 >
class SDIRK
class SectionContainer
struct SectionContainerSelector
struct SectionContainerSelector< Edge >
struct SectionContainerSelector< Face >
struct SectionContainerSelector< Vertex >
struct SectionContainerSelector< Volume >
class Selector
class SequentialSubspaceCorrection
class ShadowCopyAdjuster
class SideAndElemErrEstData
class SideFluxErrEstData
class SimpleGrid
class SimpleTimeIntegrator
Integrate (a non-linear problem) over a given time interval.
class SliceIndexView
class SlicingData
class SmartPtrVector
class SmoothPartitionBounds
class SmoothProjector
class SoftAbort
class SomaProjector
class SortedGridFunctionOrdering
struct sortStruct
struct SortVertexPos
class SparseBlockGaussSeidel
class SparseBlockGaussSeidel2
class SparseMatrix
class SparseVector
class Sphere
class SphereProjector
class StandardLineSearch
struct static_type
struct std_number_vector_attachment_reduce_traits
class StdArrayCommunicationScheme
class StdBalanceWeights
class StdCoarseningMarkingStrategy
class StdConstData
class StdConvCheck
class StdDataLinker
class StdDependentUserData
class StdExplicitGridFunctionData
class StdFuncIntegrand
class StdGlobAssembler
class StdGlobPosData
class StdHNodeAdjuster
class StdInjection
class StdIntegrand
class StdLagrangeElemTransfer
class StdLinConsistentGravity
class StdLinConsistentGravityX
class StdRefinementMarkingStrategy
class StdTransfer
class StdUserData
class stdvector
class Stopwatch
struct storage_traits1
struct storage_traits1< FixedArray1< T, N > >
struct storage_traits1< VariableArray1< T > >
class StringTableStream
class StrongNegativeConnectionsByBlockNorm
class SubdivisionProjector
class SubdivRules_PLoop
class SubGrid
class SubLocalDoFSet
class SubsetGroup
class SubsetHandlerSerializer
class SubsetIndicatorUserData
struct SubsetInfo
struct SuperLUConfiguration
class SuperLUImplementation
class SuperLUSolver
class SupErrorEvaluator
class SurfaceView
struct SweepLineEdge
struct SweepLineVertex
class SymmetricGaussSeidel
class SymP1Constraints
class Table
struct TargetProcInfo
struct TarHeader
class TE_AlphaVec
class TE_AMV_X
class TE_TRANSPOSED
class TE_VecAdd2
class TE_VecAdd3
class TE_VecScale
class TE_Vector
class TElemSelector
class TemporalFinishedCondition
class Tetrahedron
class TetrahedronClass
class TetrahedronDescriptor
class THangingNodeRefiner
class THangingNodeRefiner< Grid >
class THangingNodeRefiner< MultiGrid >
class ThetaTimeStep
struct TIKZElem
struct TikzExportDesc
class TimeDependentSpace
class TimeIntegratorLinearAdaptive
Integrate over a given time interval (for a linear problem)
class TimeIntegratorSubject
class TimeStepBounds
class TKDInfo
class ToElementPosition
class TopologicalOrdering
class TParallelGlobalRefiner
class TransferValueAccessor
class TRANSPOSED
class Traverser_FindContainingElement
class Traverser_FindElementsInIntersectingNodes
class Traverser_FindLowestLeafNodeLevel
class Traverser_MinMaxNumElements
class Traverser_RayElementIntersection
struct TRI
class Triangle
class TriangleDescriptor
class TruncatedEquidistantLagrange1D
class TruncatedMonotoneTransfer
struct TypeList
struct TypeList< EmptyType, EmptyType, EmptyType, EmptyType, EmptyType, EmptyType, EmptyType, EmptyType, EmptyType, EmptyType, EmptyType, EmptyType >
struct TypeValueList
struct TypeValueList< TypeList<> >
class UGError
struct UGError_ReferenceElementMissing
class UGProfileNode
class UGProfileNodeNull
class UGXFileInfo
class UID
class UndirectedMatrix
class UniqueFVGeomIDProvider
class UniqueTypeIDProvider
class UnsortedSparseVector
class unvisited_iterator
class UpdateableMatrixOperator
struct user_data_traits
struct user_data_traits< MathMatrix< dim, dim > >
struct user_data_traits< MathTensor< 4, dim > >
struct user_data_traits< MathVector< dim > >
struct user_data_traits< number >
class UserData
class UserDataDistIntegrandSq
class UserDataInfo
class UserDataIntegrand
class UserDataIntegrandSq
class UserDataSpace
Evaluate the difference for a (dependent) UserData type induced by different grid functions.
class UserVectorEntryAdapter
class UzawaBase
class UzawaSlicing
class ValueDataExport
class ValueIndicatorUserData
class Vanka
struct variable_type
class VariableArray1
class VariableArray2
class VarianceMarking
class VarianceMarkingEta
class Variant
class Vector
struct vector_attachment_reduce_traits
class VectorDataExport
class VectorDebugWritingObject
struct VectorProxy
struct VectorProxyBase
class VectorTimeSeries
class Vertex
class VertexBasedSubspace
class VertexCenteredVankaSubspace
class VertexDescriptor
class VMAdd
class Volume
class VolumeDescriptor
class VolumeVertices
class VTKOutput
class VTKOutputObserver
Sample class for integration observer: Output to VTK.
struct xy
struct xyz
class ZRayTracer
Typedefs
typedef Attachment< bool > ABool
typedef Attachment< byte > AByte
typedef Attachment< char > AChar
typedef Attachment< vector< TargetProcInfo > > ADistInfo
typedef Attachment< double > ADouble
typedef Attachment< Edge * > AEdge
typedef Attachment< Face * > AFace
typedef Attachment< float > AFloat
typedef Attachment< GeomObjID > AGeomObjID
typedef Attachment< int > AInt
typedef Hash< AlgebraID, size_t > AlgebraIDHashList
typedef std::vector< AlgebraID > AlgebraIDVec
typedef ANormal3 ANormal
typedef AVector3 ANormal2
typedef AVector3 ANormal3
typedef Attachment< number > ANumber
typedef APosition3 APosition
typedef AVector1 APosition1
typedef AVector2 APosition2
typedef AVector3 APosition3
typedef AVector2 ATexCoord
typedef Attachment< uint > AUInt
typedef Attachment< vector1 > AVector1
typedef Attachment< vector2 > AVector2
typedef Attachment< vector3 > AVector3
typedef Attachment< vector4 > AVector4
typedef Attachment< Vertex * > AVertex
typedef Attachment< Volume * > AVolume
typedef std::vector< bool > binary_grouping_vector
typedef geometry_traits< ConstrainedEdge >::const_iterator ConstConstrainedEdgeIterator
typedef geometry_traits< ConstrainedQuadrilateral >::const_iterator ConstConstrainedQuadrilateralIterator
typedef geometry_traits< ConstrainedTriangle >::const_iterator ConstConstrainedTriangleIterator
typedef geometry_traits< ConstrainedVertex >::const_iterator ConstConstrainedVertexIterator
typedef geometry_traits< ConstrainingEdge >::const_iterator ConstConstrainingEdgeIterator
typedef geometry_traits< ConstrainingQuadrilateral >::const_iterator ConstConstrainingQuadrilateralIterator
typedef geometry_traits< ConstrainingTriangle >::const_iterator ConstConstrainingTriangleIterator
typedef ElementStorage< Edge >::SectionContainer::const_iterator ConstEdgeIterator
typedef ElementStorage< Face >::SectionContainer::const_iterator ConstFaceIterator
typedef geometry_traits< Hexahedron >::const_iterator ConstHexahedronIterator
typedef geometry_traits< Octahedron >::const_iterator ConstOctahedronIterator
typedef geometry_traits< Prism >::const_iterator ConstPrismIterator
typedef geometry_traits< Pyramid >::const_iterator ConstPyramidIterator
typedef geometry_traits< Quadrilateral >::const_iterator ConstQuadrilateralIterator
typedef geometry_traits< ConstrainedEdge >::iterator ConstrainedEdgeIterator
typedef geometry_traits< ConstrainedQuadrilateral >::iterator ConstrainedQuadrilateralIterator
typedef geometry_traits< ConstrainedTriangle >::iterator ConstrainedTriangleIterator
typedef geometry_traits< ConstrainedVertex >::iterator ConstrainedVertexIterator
typedef geometry_traits< ConstrainingEdge >::iterator ConstrainingEdgeIterator
typedef geometry_traits< ConstrainingQuadrilateral >::iterator ConstrainingQuadrilateralIterator
typedef geometry_traits< ConstrainingTriangle >::iterator ConstrainingTriangleIterator
typedef geometry_traits< RegularEdge >::const_iterator ConstRegularEdgeIterator
typedef geometry_traits< RegularVertex >::const_iterator ConstRegularVertexIterator
typedef ConstSmartPtr< ProcessHierarchy > ConstSPProcessHierarchy
typedef geometry_traits< Tetrahedron >::const_iterator ConstTetrahedronIterator
typedef geometry_traits< Triangle >::const_iterator ConstTriangleIterator
typedef ElementStorage< Vertex >::SectionContainer::const_iterator ConstVertexIterator
typedef ElementStorage< Volume >::SectionContainer::const_iterator ConstVolumeIterator
typedef MultiIndex< 2 > DoFIndex
typedef Domain< 1, MultiGrid, MGSubsetHandler > Domain1d
typedef Domain< 2, MultiGrid, MGSubsetHandler > Domain2d
typedef Domain< 3, MultiGrid, MGSubsetHandler > Domain3d
typedef void * DynLibHandle
typedef GeomObjDataSerializer< Edge > EdgeDataSerializer
typedef ElementStorage< Edge > EdgeElementStorage
typedef ElementStorage< Edge >::SectionContainer::iterator EdgeIterator
typedef pcl::MultiLevelLayout< pcl::OrderedInterface< Edge, std::list > > EdgeLayout
typedef TElemSelector< Edge > EdgeSelector
typedef TElemSelector< Edge > EdgeSelector
typedef GeomObjDataSerializer< Face > FaceDataSerializer
typedef ElementStorage< Face > FaceElementStorage
typedef ElementStorage< Face >::SectionContainer::iterator FaceIterator
typedef pcl::MultiLevelLayout< pcl::OrderedInterface< Face, std::list > > FaceLayout
typedef TElemSelector< Face > FaceSelector
typedef TElemSelector< Face > FaceSelector
typedef std::pair< int, size_t > GeomObjID
typedef std::map< int, std::vector< AlgebraID > > GlobalLayout
typedef boost::adjacency_list< boost::vecS, boost::vecS, boost::undirectedS, boost::property< boost::vertex_color_t, boost::default_color_type, boost::property< boost::vertex_degree_t, int > > > Graph_t
typedef geometry_traits< Hexahedron >::iterator HexahedronIterator
typedef IGeometry< 1 > IGeometry1d
typedef IGeometry< 2 > IGeometry2d
typedef IGeometry< 3 > IGeometry3d
typedef pcl::SingleLevelLayout< pcl::OrderedInterface< size_t, std::vector > > IndexLayout
typedef std::list< KDVertexDistance > KDVertexDistanceList
typedef double lapack_double
typedef float lapack_float
typedef int lapack_ftnlen
typedef int lapack_int
typedef multimap< number, SweepLineEdge * > MapEdgeCuts
typedef MathMatrix< 2, 2, number > matrix22
typedef MathMatrix< 3, 3, number > matrix33
typedef MathMatrix< 4, 4, number > matrix44
typedef map< void *, MemTrackerStruct > MemTrackerMap
typedef MultiGridSubsetHandler MGSubsetHandler
typedef MultiGridSubsetHandler MGSubsetHandler
typedef geometry_traits< Octahedron >::iterator OctahedronIterator
typedef TParallelGlobalRefiner< GlobalMultiGridRefiner > ParallelGlobalRefiner_MultiGrid
typedef vector< string > ParameterList
typedef std::pair< byte, int > ParentInfo
typedef geometry_traits< Prism >::iterator PrismIterator
typedef boost::mpl::tmp::ProjectorTypes ProjectorTypes
typedef geometry_traits< Pyramid >::iterator PyramidIterator
typedef geometry_traits< Quadrilateral >::iterator QuadrilateralIterator
typedef geometry_traits< RegularEdge >::iterator RegularEdgeIterator
typedef geometry_traits< RegularVertex >::iterator RegularVertexIterator
typedef std::vector< schur_slice_desc_type > SchurSliceDescVector
typedef SlicingData< SchurSliceDescVector, 2 > SchurSlicingData
typedef SmartPtr< IBalanceWeights > SPBalanceWeights
typedef SmartPtr< ICommunicationWeights > SPCommunicationWeights
typedef SmartPtr< EdgeDataSerializer > SPEdgeDataSerializer
typedef SmartPtr< ElementCallback > SPElementCallback
typedef SmartPtr< FaceDataSerializer > SPFaceDataSerializer
typedef SmartPtr< GridDataSerializer > SPGridDataSerializer
typedef SmartPtr< IGeometry1d > SPIGeometry1d
typedef SmartPtr< IGeometry2d > SPIGeometry2d
typedef SmartPtr< IGeometry3d > SPIGeometry3d
typedef SmartPtr< IRefMarkAdjuster > SPIRefMarkAdjuster
typedef SmartPtr< LocalMarkAdjuster > SPLocalMarkAdjuster
typedef SmartPtr< MessageHub > SPMessageHub
typedef SmartPtr< MGHNodeAdjuster > SPMGHNodeAdjuster
typedef node_tree::SPCollisionTreeRootNode SPOctree
typedef SmartPtr< ParallelHNodeAdjuster > SPParallelHNodeAdjuster
typedef SmartPtr< IPartitioner > SPPartitioner
typedef SmartPtr< PartitionMap > SPPartitionMap
typedef SmartPtr< IPartitionPostProcessor > SPPartitionPostProcessor
typedef SmartPtr< IPartitionPreProcessor > SPPartitionPreProcessor
typedef SmartPtr< ProcessHierarchy > SPProcessHierarchy
typedef SmartPtr< ProjectionHandler > SPProjectionHandler
typedef SmartPtr< RasterLayerDesc > SPRasterLayerDesc
typedef SmartPtr< RasterLayers > SPRasterLayers
typedef SmartPtr< RasterLayersProjector > SPRasterLayersProjector
typedef SmartPtr< RefinementProjector > SPRefinementProjector
typedef SmartPtr< StdHNodeAdjuster > SPStdHNodeAdjuster
typedef SmartPtr< VertexDataSerializer > SPVertexDataSerializer
typedef SmartPtr< VolumeDataSerializer > SPVolumeDataSerializer
typedef Table< std::stringstream > StringStreamTable
typedef Table< std::string > StringTable
typedef GridSubsetHandler SubsetHandler
typedef GridSubsetHandler SubsetHandler
typedef SweepLineEdgeList::iterator SweepLineEdgeIter
typedef list< SweepLineEdge > SweepLineEdgeList
typedef geometry_traits< Tetrahedron >::iterator TetrahedronIterator
typedef geometry_traits< Triangle >::iterator TriangleIterator
typedef MathVector< 1, number > vector1
typedef MathVector< 2, number > vector2
typedef MathVector< 3, number > vector3
typedef MathVector< 4, number > vector4
typedef GeomObjDataSerializer< Vertex > VertexDataSerializer
typedef ElementStorage< Vertex > VertexElementStorage
typedef ElementStorage< Vertex >::SectionContainer::iterator VertexIterator
typedef pcl::MultiLevelLayout< pcl::OrderedInterface< Vertex, std::list > > VertexLayout
typedef TElemSelector< Vertex > VertexSelector
typedef TElemSelector< Vertex > VertexSelector
typedef GeomObjDataSerializer< Volume > VolumeDataSerializer
typedef ElementStorage< Volume > VolumeElementStorage
typedef ElementStorage< Volume >::SectionContainer::iterator VolumeIterator
typedef pcl::MultiLevelLayout< pcl::OrderedInterface< Volume, std::list > > VolumeLayout
typedef TElemSelector< Volume > VolumeSelector
typedef TElemSelector< Volume > VolumeSelector
typedef Base64FileWriter VTKFileWriter
Enumerations
enum AnisotropyState
enum ArchiveType
enum ATTACHMENT_CONSTANTS
enum ConstraintType
enum ConstraintTypes
enum DiscPart
enum EdgeContainerSections
enum EdgeOptions
enum ElemDiscType
enum ElementStatusTypes
enum eMatrixOrdering
enum eTransposeMode
enum ExtrusionOptions
enum FaceContainerSections
enum FaceOptions
enum GlobalBoundaryRefinementRule
enum GridBaseObjectId
enum GridHeaderConstants
enum GridHeaderReadOptions
enum GridMessageAdaptionType
enum GridMessageCreationType
enum GridMessageDistributionType
enum GridMessageMultiGridChangedType
enum GridObjectID
enum GridOptions
enum GridSerializationID
enum InterfaceNodeTypes
enum InterfaceStates
enum KDSplitDimension
enum KDTreeSplitStrategy
enum LGBConstants
enum matrix_algebra_type
enum NeighborhoodType
enum ObserverType
enum ParallelStorageType
enum PathTypes
enum PolyChainTypes
enum ProcessType
enum ReferenceObjectID
enum RefinementMark
enum RemeshingElementMarks
enum schur_slice_desc_type
enum SelectorElements
enum SelectorElements
enum SubsetHandlerElements
enum SubsetHandlerElements
enum SubsetState
enum SubsetState
enum SweepLineEdgeStatus
enum SweepLineVertexStatus
enum TraversalStates
enum VertexContainerSections
enum VertexOptions
enum VolumeContainerSections
enum VolumeOptions
enum VTKCellTypes
Functions
void AbortRun ()
bool absCompare (double a, double b)
bool AdaptSurfaceGridToCylinder (Selector &selOut, Grid &grid, Vertex *vrtCenter, const vector3 &normal, number radius, number rimSnapThreshold, AInt &aInt, APosition &aPos=aPosition)
bool AdaptSurfaceGridToCylinder (Selector &selOut, Grid &grid, Vertex *vrtCenter, const vector3 &normal, number radius, number rimSnapThreshold, APosition &aPos=aPosition)
void AddAllFromInterface (std::set< size_t > &s, const IndexLayout::Interface &interface)
void AddAllFromLayout (std::set< size_t > &s, const IndexLayout &layout)
void AddConnectionsBetweenSlaves (pcl::InterfaceCommunicator< IndexLayout > &communicator, IndexLayout &masterLayout, IndexLayout &slaveLayout, IndexLayout &allToAllSend, IndexLayout &allToAllReceive)
bool AddEntriesToIndexLayout_DomainDecomposition (IndexLayout &processLayoutOut, IndexLayout &subdomainLayoutOut, DoFDistribution &dofDistr, TLayout &elemLayout, pcl::IDomainDecompositionInfo *ddInfoIn)
bool AddEntriesToLevelIndexLayout (IndexLayout &indexLayoutOut, DoFDistribution &dofDistr, TLayout &elemLayout, const std::map< int, std::vector< bool > > *pIgnoreMap=NULL)
bool AddEntriesToSurfaceIndexLayout (IndexLayout &indexLayoutOut, DoFDistribution &dofDistr, TLayout &elemLayout, MultiGrid &mg, DistributedGridManager &dGrMgr)
bool AddExtraProcessEntriesToSubdomainLayout (size_t numIDs, IndexLayout &processMasterLayoutIn, IndexLayout &processSlaveLayoutIn, IndexLayout &subdomainMasterLayoutInOut, IndexLayout &subdomainSlaveLayoutInOut)
void AddFunctionValuesToGridCoordinatesP1 (SmartPtr< TGridFunction > spGridFct, const char *cmp, size_t coordInd)
void AddFunctionValuesToGridCoordinatesP1 (SmartPtr< TGridFunction > spGridFct, const char *cmp, size_t coordInd, number timestep)
void AddFunctionValuesToGridCoordinatesP1 (SmartPtr< TGridFunction > spGridFct, size_t fct, size_t coordInd, const SubsetGroup &ssGrp, number timestep)
static void AddGlobalAttachmentsToSerializer (GridDataSerializationHandler &handler, Grid &grid)
static SPIRefMarkAdjuster AddHorizontalAnisotropyAdjuster (IRefiner *ref, TDomain *dom)
void AddIfUnique (IndexLayout::Interface &interface, size_t i)
void AdditiveToConsistent (TVector *pVec, const IndexLayout &masterLayout, const IndexLayout &slaveLayout, pcl::InterfaceCommunicator< IndexLayout > *pCom=NULL)
void AdditiveToUnique (TVector *pVec, const IndexLayout &masterLayout, const IndexLayout &slaveLayout, pcl::InterfaceCommunicator< IndexLayout > *pCom=NULL)
void AddLayoutFromGlobalLayout (IndexLayout &layout, GlobalLayout &globalLayout, TGlobalToLocal &globalToLocal, bool bRemoveDoubles=true)
bool AddLocalMatrix (TGlobalMatrix &mat, const TLocalMatrix &localMat)
bool AddLocalMatrix (TGlobalMatrix &mat, const TLocalMatrix &localMat, const size_t *rowIndices, const size_t *colIndices)
void AddLocalMatrixToGlobal (TMatrix &mat, const LocalMatrix &lmat)
void AddLocalVector (TVector &vec, const LocalVector &lvec)
void AddMult (A &dest, const A &vec, const double &b)
void AddMult (A &dest, const B &b, const C &vec)
void AddMult (DenseMatrix< A > &dest, const DenseMatrix< B > &mA, const DenseMatrix< C > &mB)
void AddMult (DenseMatrix< A > &dest, const double &alpha, const DenseMatrix< B > &mat)
void AddMult (DenseVector< A > &dest, const DenseMatrix< B > &mat, const DenseVector< C > &vec)
void AddMult (DenseVector< A > &dest, const double &b, const A &vec)
void AddMult (number &dest, const number &b, const number &vec)
void AddMultiplyOf (ABC_type &M, const A_type &A, const B_type &B, const C_type &C, double epsilonTruncation=0.0)
static SPIRefMarkAdjuster AddShadowCopyAdjuster (IRefiner *ref)
static void AddTargetProcToDistInfos (MGSelector &msel, DistInfoSupplier &distInfos, int targetProc)
bool AdjustEdgeLength (Grid &grid, SubsetHandler &shMarks, const AdjustEdgeLengthDesc &desc, int numIterations)
bool AdjustEdgeLength (Grid &grid, SubsetHandler &shMarks, number minEdgeLen, number maxEdgeLen, int numIterations, bool projectPoints, bool adaptive)
UG_API void AdjustEdgeOrientationToFaceOrientation (Grid &grid, TEdgeIterator edgesBegin, TEdgeIterator edgesEnd)
UG_API void AdjustEdgeOrientationToFaceOrientation (Grid &grid, TEdgeIterator edgesBegin, TEdgeIterator edgesEnd, Grid::face_traits::callback considerFace)
void AdjustMeanValue (SmartPtr< TGridFunction > spGF, const std::string &fcts)
void AdjustMeanValue (SmartPtr< TGridFunction > spGF, const std::string &fcts, number mean)
void AdjustMeanValue (SmartPtr< TGridFunction > spGF, const std::vector< std::string > &vCmp)
void AdjustMeanValue (SmartPtr< TGridFunction > spGF, const std::vector< std::string > &vCmp, number mean)
static void AdjustSelection (Grid &grid, Selector &sel)
void AdjustSubsetsForLgmNg (Grid &grid, SubsetHandler &sh, bool keepExistingInterfaceSubsets=false)
void AdjustSubsetsForSimulation (TSubsetHandler &sh, bool preserveExistingSubsets)
void AllGatherGrid (Grid &gridOut, Selector &sel, GridDataSerializationHandler &serializer, GridDataSerializationHandler &deserializer, const pcl::ProcessCommunicator &procCom=pcl::ProcessCommunicator())
UG_API void AppendCounterToString (std::string &str, std::string indicator, int counter, int maxCounter=-1)
void AppendCounterToString (string &str, string indicator, int counter, int maxCounter)
bool AppendInterface (TLayout &layout, int pidSource, int pidAppendTo)
UG_API std::string AppendSpacesToString (std::string &str, int totalLength)
string AppendSpacesToString (string &str, int totalLength)
void ApplyConstrainedSmoothSubdivisionVolumesToTopLevel (MultiGrid &mg, MGSubsetHandler &sh, MGSubsetHandler &markSH, const char *linearManifoldSubsets)
bool ApplyLinearSolver (SmartPtr< ILinearOperator< vector_type > > A, vector_type &u, vector_type &b, SmartPtr< ILinearOperatorInverse< vector_type > > solver)
void ApplySmoothManifoldPosToTopLevelAveragingScheme (MultiGrid &mg, TAPosition &aPos, MGSubsetHandler &markSH, MGSubsetHandler &linearManifoldSH)
void ApplySmoothManifoldPosToTopLevelButterflyScheme (MultiGrid &mg, TAPosition &aPos, MGSubsetHandler &markSH, MGSubsetHandler &linearManifoldSH)
void ApplySmoothManifoldPosToTopLevelLoopScheme (MultiGrid &mg, TAPosition &aPos, MGSubsetHandler &markSH, MGSubsetHandler &linearManifoldSH, bool bCreaseSurf)
void ApplySmoothSubdivisionSurfacesToTopLevel (MultiGrid &mg, TAPosition &aPos, MGSubsetHandler &sh, MGSubsetHandler &markSH, const char *linearManifoldSubsets, bool bCreaseSurf)
void ApplySmoothSubdivisionSurfacesToTopLevel (MultiGrid &mg, TAPosition &aPos, MGSubsetHandler &sh, MGSubsetHandler &markSH, MGSubsetHandler &linearManifoldSH, bool bCreaseSurf)
template void ApplySmoothSubdivisionSurfacesToTopLevel< APosition > (MultiGrid &mg, APosition &aPos, MGSubsetHandler &sh, MGSubsetHandler &markSH, const char *linearManifoldSubsets, bool bCreaseSurf)
template void ApplySmoothSubdivisionSurfacesToTopLevel< APosition1 > (MultiGrid &mg, APosition1 &aPos, MGSubsetHandler &sh, MGSubsetHandler &markSH, const char *linearManifoldSubsets, bool bCreaseSurf)
template void ApplySmoothSubdivisionSurfacesToTopLevel< APosition2 > (MultiGrid &mg, APosition2 &aPos, MGSubsetHandler &sh, MGSubsetHandler &markSH, const char *linearManifoldSubsets, bool bCreaseSurf)
void ApplySmoothSubdivisionVolumesToTopLevel (MultiGrid &mg, MGSubsetHandler &sh, MGSubsetHandler &markSH, const char *linearManifoldSubsets)
void ApplySmoothSubdivisionVolumesToTopLevel (MultiGrid &mg, MGSubsetHandler &sh, MGSubsetHandler &markSH, MGSubsetHandler &linearManifoldSH, bool bConstrained)
void ApplySmoothVolumePosToTopLevel (MultiGrid &mg, MGSubsetHandler &markSH, bool bConstrained)
UG_API number AreaFaceQuality (TIterator facesBegin, TIterator facesEnd, Grid::VertexAttachmentAccessor< APosition > &aaPos)
int ArrayEraseEntry (TType *array, const TType &entry, size_t size)
bool ArrayReplaceEntry (TType *array, const TType &newEntry, const TType &oldEntry, size_t size)
void ArraySwapWithLast (TType *array, const TType &entry, size_t size)
number AspectRatio (FaceVertices *f, TAAPos &aaPos)
number AspectRatio (Volume *vol, TAAPos &aaPos)
void AssembleInjectionByAverageOfChildren (typename TAlgebra::matrix_type &mat, const DoFDistribution &coarseDD, const DoFDistribution &fineDD)
void AssembleInjectionForP1Lagrange (typename TAlgebra::matrix_type &mat, const DoFDistribution &coarseDD, const DoFDistribution &fineDD)
void AssembleLinearOperatorRhsAndSolution (AssembledLinearOperator< TAlgebra > &op, typename TAlgebra::vector_type &u, typename TAlgebra::vector_type &b)
void AssignAssociatedEdgesToSubsets (TSubsetHandler &sh, const ISubsetHandler &srcIndHandler)
void AssignAssociatedFacesToSubsets (TSubsetHandler &sh, const ISubsetHandler &srcIndHandler)
void AssignAssociatedLowerDimElemsToSubsets (TSubsetHandlerDest &sh, const TSubsetHandlerSrc &srcIndHandler)
void AssignAssociatedLowerDimElemsToSubsets (TSubsetHandlerDest &sh, const TSubsetHandlerSrc &srcIndHandler, const Edge &)
void AssignAssociatedLowerDimElemsToSubsets (TSubsetHandlerDest &sh, const TSubsetHandlerSrc &srcIndHandler, const Face &)
void AssignAssociatedLowerDimElemsToSubsets (TSubsetHandlerDest &sh, const TSubsetHandlerSrc &srcIndHandler, const Volume &)
void AssignAssociatedSidesToSubsets (TSubsetHandlerDest &sh, const TSubsetHandlerSrc &srcIndHandler)
void AssignAssociatedVerticesToSubset (ISubsetHandler &sh, TIterator elemsBegin, TIterator elemsEnd, int subsetIndex)
void AssignAssociatedVerticesToSubsets (TSubsetHandler &sh, const ISubsetHandler &srcIndHandler)
static void AssignCreaseVertices (Grid &grid, SubsetHandler &shMarks)
void AssignDefaultSubsetColors (ISubsetHandler &sh)
void AssignFaceInterfaceEdgesToSubsets (Grid &grid, SubsetHandler &sh)
static void AssignFixedVertices (Grid &grid, SubsetHandler &shMarks)
void AssignGridToSubset (Grid &g, ISubsetHandler &sh, int subsetInd)
void AssignIndices (TIterator begin, TIterator end, TAAInt &aaInt, int baseIndex=0)
void AssignIndices (typename geometry_traits< TElem >::iterator iterBegin, typename geometry_traits< TElem >::iterator iterEnd, Grid::AttachmentAccessor< TElem, AInt > &aaInt)
void AssignInnerAndBoundarySubsets (Grid &grid, ISubsetHandler &shOut, int inSubset, int bndSubset)
void AssignMult (A &dest, const A &vec, const double &b)
void AssignMult (A &dest, const B &b, const C &vec)
void AssignMult (DenseMatrix< A > &dest, const DenseMatrix< B > &mA, const DenseMatrix< C > &mB)
void AssignMult (DenseMatrix< A > &dest, const double &alpha, const DenseMatrix< B > &mat)
void AssignMult (DenseVector< A > &dest, const DenseMatrix< B > &mat, const DenseVector< C > &vec)
void AssignMult (DenseVector< A > &dest, const double &b, const DenseVector< B > &vec)
void AssignMult (number &dest, const number &b, const number &vec)
void AssignRegionToSubset (Grid &grid, ISubsetHandler &shVolsOut, const ISubsetHandler &shFaces, Volume *proxyVol, int newSubsetIndex)
void AssignSelectionStateToSides (TSelector &sel, bool recursive)
void AssignSelectionToSubset (ISelector &sel, ISubsetHandler &sh, int subsetInd)
void AssignSidesToSubsets (ISubsetHandler &sh, ISelector *psel=NULL)
template void AssignSidesToSubsets< Edge > (ISubsetHandler &, ISelector *)
template void AssignSidesToSubsets< Face > (ISubsetHandler &, ISelector *)
template void AssignSidesToSubsets< Volume > (ISubsetHandler &, ISelector *)
void AssignSubset_VerticesInCube (TDomain &dom, const typename TDomain::position_type &min, const typename TDomain::position_type &max, int si)
void AssignSubset_VerticesInSphere (TDomain &dom, const typename TDomain::position_type &center, const number radius, int si)
void AssignSubsetColors (ISubsetHandler &sh)
void AssignSubsetColorsBlueToGreen (ISubsetHandler &sh, int firstSi, int numSi)
void AssignSubsetColorsRedToGreen (ISubsetHandler &sh, int firstSi, int numSi)
void AssignSubsetsByElementQuality (Grid &grid, SubsetHandler &sh, int dim, int numSecs)
void AssignSubsetsByElementQuality (MultiGrid &mg, MGSubsetHandler &sh, int dim, int numSecs)
void AssignSubsetsByElementQuality3d (MultiGrid &grid, MGSubsetHandler &sh, int numSecs)
void AssignSubsetsByElementType (ISubsetHandler &sh)
void AssignSubsetsByElementType (ISubsetHandler &sh, GridObjectCollection g)
static void AssignSubsetsByInterfaceType (SubsetHandler &sh, MultiGrid &mg)
static void AssignSubsetsByLevel (SubsetHandler &sh, MultiGrid &mg)
bool AssignSubsetsByQuality (Grid &grid, SubsetHandler &sh, TIterator elemsBegin, TIterator elemsEnd, std::vector< number > intervals)
static void AssignSubsetsBySurfaceViewState (SubsetHandler &sh, const SurfaceView &sv, MultiGrid &mg)
void AssignSubsetToElementWithSmallestMinAngle (MultiGrid &grid, MGSubsetHandler &sh, int dim, const char *roid, int si)
void AssignSubsetToElementWithSmallestMinAngle2d (MultiGrid &grid, MGSubsetHandler &sh, const char *roid, int si)
void AssignSubsetToElementWithSmallestMinAngle3d (MultiGrid &grid, MGSubsetHandler &sh, const char *roid, int si)
bool AssignTetrahedronAttributesByAspectRatio (Grid &grid, SubsetHandler &shVolume, AInt &aTetrahedronAspectRatioClass, std::vector< double > &offsets, Grid::VertexAttachmentAccessor< APosition > &aaPos)
bool AssignTetrahedronAttributesByAspectRatio (Grid &grid, SubsetHandler &shVolume, AInt &aTetrahedronAspectRatioClass, vector< double > &offsets, Grid::VertexAttachmentAccessor< APosition > &aaPos)
void AssignUnassignedElemsToSubset (TSubsetHandler &sh, int si)
static void AssignVerticalMasterAndSlaveStates (MGSelector &msel, bool partitionForLocalProc)
void AssignVolumeInterfaceFacesToSubsets (Grid &grid, SubsetHandler &sh)
bool AttachAct (Grid &grid, const char *filename, string name)
void AttachmentAllReduce (Grid &grid, AType aValue, pcl::ReduceOperation op)
bool AttachProperty (Grid &grid, const char *filename, string name)
number AverageFunctionDifference (SmartPtr< GridFunction< TDomain, TAlgebra > > spGridFct, std::string subset, std::string fct1, std::string fct2)
void AveragePositions (TPosition &vOut, const TPosition *vCornerCoords, size_t num)
bool Axpy_transposedCommonSparseMatrix (const TSparseMatrix &A, vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const vector_t &w1)
bool AxpyCommonSparseMatrix (const TSparseMatrix &A, vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const vector_t &w1)
void backward_gs_step (Vector_type &c, const Matrix_type &A, const Vector_type &d, const size_t i, const number relaxFactor)
void baseName (std::string &nameOut, const std::string &nameIn)
static int Bevel2d (const vector3 &p)
static int Bevel3d (const vector3 &p)
int BinomCoeff (int n, int k)
bool BlockDeserialize (std::istream &buff, const DenseMatrix< FixedArray2< number, Tr, Tc > > &mat)
bool BlockMatrixFiniteAndNotTooBig (TBlock &m, double tooBigValue=1e24)
void BlockMatrixToDoubleMatrix (DenseMatrix< VariableArray2< double > > &Ad, TMatrix &Ab)
double BlockMaxNorm (const DenseVector< A > &v)
number BlockMaxNorm (const number &a)
number BlockMaxNorm (const T &t)
number BlockNorm (const number &a)
number BlockNorm (const T &t)
double BlockNorm (const TYPE &v)
double BlockNorm2 (const DenseMatrix< A > &mat)
double BlockNorm2 (const DenseVector< A > &v)
number BlockNorm2 (const number &a)
number BlockNorm2 (const T &t)
double BlockNorm2 (const TYPE &v)
const number & BlockRef (const number &m, size_t i)
const number & BlockRef (const number &m, size_t i, size_t j)
const double & BlockRef (const T &mat, size_t i, size_t j)
const double & BlockRef (const T &vec, size_t i)
number & BlockRef (number &m, size_t i)
number & BlockRef (number &m, size_t i, size_t j)
double & BlockRef (T &mat, size_t i, size_t j)
double & BlockRef (T &vec, size_t i)
bool BlockSerialize (const DenseMatrix< FixedArray2< number, Tr, Tc > > &mat, std::ostream &buff)
bool BlockVectorFiniteAndNotTooBig (TBlock &v, double tooBigValue=1e24)
void BlurField (Field< T > &field, number alpha, size_t numIterations, const T &noDataValue)
bool BoxBoundProbe (const vector_t &v, const vector_t &boxMin, const vector_t &boxMax)
bool BoxBoxIntersection (const vector_t &box1Min, const vector_t &box1Max, const vector_t &box2Min, const vector_t &box2Max)
static void bp_defect_and_gradient (number &defectOut, vector3 &gradientOut, const std::vector< NeuriteProjector::BPProjectionHelper > &bpList, const vector3 &x, number rad, const vector3 &constAngleSurfNormal, const NeuriteProjector *np)
static void bp_newton_start_pos (vector3 &initOut, uint32_t neuriteID, float t, float angle, float rad, const vector3 &constAngleSurfaceNormal, const IVertexGroup *parent, const NeuriteProjector *np)
void BroadcastGrid (Grid &gridOut, Selector &sel, GridDataSerializationHandler &serializer, GridDataSerializationHandler &deserializer, int root, const pcl::ProcessCommunicator &procCom=pcl::ProcessCommunicator())
void BroadcastVectorFromOne (HorizontalAlgebraLayouts &agglomerationLayout, ParallelVector< T > &vec, const ParallelVector< T > &collectedVec, ParallelStorageType type)
void BroadcastVectorFromOne (IndexLayout &agglomeratedMaster, IndexLayout &agglomeratedSlave, pcl::InterfaceCommunicator< IndexLayout > &com, ParallelVector< T > &vec, const ParallelVector< T > &collectedVec, ParallelStorageType type, bool bRoot)
void BuildDomainDecompositionLayouts (IndexLayout &subdomMastersOut, IndexLayout &subdomSlavesOut, IndexLayout &processMastersOut, IndexLayout &processSlavesOut, IndexLayout &deltaNbrMastersOut, IndexLayout &deltaNbrSlavesOut, IndexLayout &crossPointMastersOut, IndexLayout &crossPointSlavesOut, const IndexLayout &standardMasters, const IndexLayout &standardSlaves, int highestReferencedIndex, IDomainDecompositionInfo &ddinfo)
int BuildOneToManyLayout (IndexLayout &masterLayoutOut, IndexLayout &slaveLayoutOut, int rootProcID, IndexLayout &masterLayout, IndexLayout &slaveLayout, pcl::ProcessCommunicator procComm, std::vector< int > *pNewMasterIDsOut)
void CalcTotalMem (const Shiny::ProfileNode *p)
void CalculateAngles (vector< number > &vAnglesOut, Grid &grid, Face *f, TAAPosVRT &aaPos)
number CalculateAngles (vector< number > &vAnglesOut, Grid &grid, TElem *elem, TAAPosVRT &aaPos)
void CalculateAngles (vector< number > &vAnglesOut, Grid &grid, Volume *v, TAAPosVRT &aaPos)
number CalculateAspectRatio (Grid &grid, Face *face, TAAPosVRT &aaPos)
number CalculateAspectRatio (Grid &grid, Hexahedron *hex, TAAPosVRT &aaPos)
number CalculateAspectRatio (Grid &grid, Pyramid *pyr, TAAPosVRT &aaPos)
number CalculateAspectRatio (Grid &grid, Quadrilateral *quad, TAAPosVRT &aaPos)
number CalculateAspectRatio (Grid &grid, TElem *elem, TAAPosVRT &aaPos)
number CalculateAspectRatio (Grid &grid, Tetrahedron *tet, TAAPosVRT &aaPos)
number CalculateAspectRatio (Grid &grid, Triangle *tri, TAAPosVRT &aaPos)
number CalculateAspectRatio (Grid &grid, Volume *vol, TAAPosVRT &aaPos)
number CalculateAverageCurvature (Grid &grid, SubsetHandler &shMarks, Edge *e, TAAPosVRT &aaPos)
number CalculateAverageEdgeLength (Grid &grid, TAAPosVRT &aaPos)
UG_API TAPosition::ValueType CalculateBarycenter (TVrtIter vrtsBegin, TVrtIter vrtsEnd, Grid::VertexAttachmentAccessor< TAPosition > &aaPos)
UG_API void CalculateBoundaryVertexNormal2D (typename TAAPosVRT::ValueType &nOut, Grid &grid, Vertex *vrt, TAAPosVRT &aaPos)
UG_API void CalculateBoundaryVertexNormal3D (vector3 &nOut, Grid &grid, Vertex *vrt, TAAPosVRT &aaPos)
void CalculateBoundingBox (size_t npoints, const MathVector< dim > points[], MathVector< dim > &vMinBB, MathVector< dim > &vMaxBB)
AABox< typename TAAPos::ValueType > CalculateBoundingBox (TElem *e, TAAPos aaPos)
UG_API void CalculateBoundingBox (typename TAPosition::ValueType &vMinOut, typename TAPosition::ValueType &vMaxOut, TVrtIter vrtsBegin, TVrtIter vrtsEnd, Grid::AttachmentAccessor< Vertex, TAPosition > &aaPos)
UG_API void CalculateBoundingBox (vector_t &vMinOut, vector_t &vMaxOut, TIterator begin, TIterator end, TAAPos &aaPos)
AABox< typename TAAPos::ValueType > CalculateBoundingBox (Vertex *e, TAAPos aaPos)
Sphere< typename TAAPos::ValueType > CalculateBoundingSphere (FaceVertices *face, TAAPos aaPos)
UG_API TVertexPositionAttachmentAccessor::ValueType CalculateCenter (const Edge *e, TVertexPositionAttachmentAccessor &aaPosVRT)
UG_API TAAPosVRT::ValueType CalculateCenter (const EdgeVertices *e, TAAPosVRT &aaPos, TAAWeightVRT &aaWeight)
UG_API TAAPosVRT::ValueType CalculateCenter (const FaceVertices *f, TAAPosVRT &aaPos, TAAWeightVRT &aaWeight)
TVertexPositionAttachmentAccessor::ValueType CalculateCenter (const FaceVertices *f, TVertexPositionAttachmentAccessor &aaPosVRT)
UG_API TAAPosVRT::ValueType CalculateCenter (const Vertex *v, TAAPosVRT &aaPos, TAAWeightVRT &aaWeight)
TVertexPositionAttachmentAccessor::ValueType CalculateCenter (const Vertex *v, TVertexPositionAttachmentAccessor &aaPosVRT)
UG_API TAAPosVRT::ValueType CalculateCenter (const VolumeVertices *vol, TAAPosVRT &aaPos, TAAWeightVRT &aaWeight)
UG_API TVertexPositionAttachmentAccessor::ValueType CalculateCenter (const VolumeVertices *vol, TVertexPositionAttachmentAccessor &aaPosVRT)
UG_API TAAPosVRT::ValueType CalculateCenter (TIterator begin, TIterator end, TAAPosVRT &aaPos)
UG_API TAPosition::ValueType CalculateCenter (TVrtIter vrtsBegin, TVrtIter vrtsEnd, Grid::AttachmentAccessor< Vertex, TAPosition > &aaPos)
bool CalculateCenter (typename TAAPosVRT::ValueType &centerOut, Selector &sel, TAAPosVRT &aaPos)
void CalculateCenter (vector_t &centerOut, const vector_t *pointSet, size_t numPoints)
void CalculateConstrainedSmoothVolumePosInTopLevel (MultiGrid &mg, MGSubsetHandler &markSH, APosition &aSmoothVolPos_toc)
void CalculateCovarianceMatrix (matrix33 &matOut, const vector3 *pointSet, const vector3 &center, size_t numPoints)
TAAPosVRT::ValueType CalculateCreaseNormal (Grid &grid, Face *f, Vertex *vrt, Grid::edge_traits::callback funcIsCreaseEdge, TAAPosVRT &aaPos)
TAAPosVRT::ValueType CalculateCreaseNormal (Grid &grid, Volume *vol, Vertex *vrt, Grid::face_traits::callback funcIsCreaseFace, TAAPosVRT &aaPos)
bool CalculateEigenvalues (const ug::matrix33 &mat, number &lambdaMinOut, number &lambdaMedOut, number &lambdaMaxOut, ug::vector3 &evMinOut, ug::vector3 &evMedOut, ug::vector3 &evMaxOut)
void CalculateFaceNormals (Grid &grid, const FaceIterator &facesBegin, const FaceIterator &facesEnd, AVector3 &aPos, AVector3 &aNorm)
UG_API TAAPosVRT::ValueType CalculateGridObjectCenter (const GridObject *o, TAAPosVRT &aaPosVRT)
UG_API TAAPosVRT::ValueType CalculateGridObjectCenter (const GridObject *o, TAAPosVRT &aaPosVRT, TAAWeightVRT &aaWeight)
number CalculateHexahedronAspectRatio (Grid &grid, Hexahedron *tet, Grid::VertexAttachmentAccessor< APosition > &aaPos)
UG_API number CalculateHexahedronVolToRMSFaceAreaRatio (Grid &grid, Hexahedron *hex, Grid::VertexAttachmentAccessor< APosition > &aaPos)
number CalculateHexahedronVolume (const vector3 &a, const vector3 &b, const vector3 &c, const vector3 &d, const vector3 &e, const vector3 &f, const vector3 &g, const vector3 &h)
number CalculateLengthFac (Grid &grid, SubsetHandler &shMarks, Edge *e, TAAPosVRT &aaPos)
number CalculateMaxAngle (Grid &grid, Face *f, TAAPosVRT &aaPos)
number CalculateMaxAngle (Grid &grid, Prism *prism, TAAPosVRT &aaPos)
number CalculateMaxAngle (Grid &grid, Pyramid *pyr, TAAPosVRT &aaPos)
number CalculateMaxAngle (Grid &grid, TElem *elem, TAAPosVRT &aaPos)
number CalculateMaxAngle (Grid &grid, Tetrahedron *tet, TAAPosVRT &aaPos)
number CalculateMaxAngle (Grid &grid, Volume *vol, TAAPosVRT &aaPos)
number CalculateMaxDihedral (Grid &grid, Prism *prism, TAAPosVRT &aaPos)
number CalculateMaxDihedral (Grid &grid, Pyramid *pyr, TAAPosVRT &aaPos)
number CalculateMaxDihedral (Grid &grid, TElem *elem, TAAPosVRT &aaPos)
number CalculateMaxDihedral (Grid &grid, Tetrahedron *tet, TAAPosVRT &aaPos)
number CalculateMaxDihedral (Grid &grid, Volume *v, TAAPosVRT &aaPos)
number CalculateMinAngle (Grid &grid, Face *f, TAAPosVRT &aaPos)
number CalculateMinAngle (Grid &grid, Hexahedron *hex, TAAPosVRT &aaPos)
number CalculateMinAngle (Grid &grid, Prism *prism, TAAPosVRT &aaPos)
number CalculateMinAngle (Grid &grid, Pyramid *pyr, TAAPosVRT &aaPos)
number CalculateMinAngle (Grid &grid, TElem *elem, TAAPosVRT &aaPos)
number CalculateMinAngle (Grid &grid, Tetrahedron *tet, TAAPosVRT &aaPos)
number CalculateMinAngle (Grid &grid, Volume *vol, TAAPosVRT &aaPos)
number CalculateMinCurvature (Grid &grid, SubsetHandler &shMarks, Vertex *vrt, TAAPosVRT &aaPos)
number CalculateMinDihedral (Grid &grid, Hexahedron *hex, TAAPosVRT &aaPos)
number CalculateMinDihedral (Grid &grid, Prism *prism, TAAPosVRT &aaPos)
number CalculateMinDihedral (Grid &grid, Pyramid *pyr, TAAPosVRT &aaPos)
number CalculateMinDihedral (Grid &grid, TElem *elem, TAAPosVRT &aaPos)
number CalculateMinDihedral (Grid &grid, Tetrahedron *tet, TAAPosVRT &aaPos)
number CalculateMinDihedral (Grid &grid, Volume *v, TAAPosVRT &aaPos)
number CalculateMinTriangleHeight (Face *face, TAAPosVRT &aaPos)
number CalculateMinVolumeHeight (Tetrahedron *tet, Grid::VertexAttachmentAccessor< APosition > &aaPos)
vector2 CalculateNormal (EdgeVertices *edge, Grid::AttachmentAccessor< Vertex, APosition2 > &aaPos)
vector2 CalculateNormal (EdgeVertices *edge, Grid::AttachmentAccessor< Vertex, Attachment< vector2 > > &aaPos)
vector3 CalculateNormal (FaceVertices *face, Grid::AttachmentAccessor< Vertex, APosition > &aaPos)
vector3 CalculateNormal (FaceVertices *face, Grid::AttachmentAccessor< Vertex, Attachment< vector3 > > &aaPos)
void CalculateNormal (vector3 &vNormOut, const FaceVertices *face, Grid::AttachmentAccessor< Vertex, APosition > &aaPos)
int CalculateNormal (vector3 &vNormOut, Grid &grid, Edge *e, Grid::AttachmentAccessor< Vertex, APosition > &aaPos, Grid::AttachmentAccessor< Face, ANormal > *paaNormFACE=NULL)
number CalculateNormalDot (TriangleDescriptor &td1, TriangleDescriptor &td2, TVertexPositionAccessor &aaPos)
void CalculateNormalNoNormalize (vector3 &vNormOut, FaceVertices *face, Grid::AttachmentAccessor< Vertex, APosition > &aaPos)
int CalculateNormalNoNormalize (vector3 &vNormOut, Grid &grid, Edge *e, Grid::VertexAttachmentAccessor< APosition > &aaPos, Grid::FaceAttachmentAccessor< ANormal > *paaNormFACE=NULL)
void CalculateNumElemsVertexAttachmentInTopLevel (MultiGrid &mg, AInt &aNumElems_toc, AInt &aNumElems_prism, AInt &aNumElems_hex)
void CalculateNumManifoldEdgesVertexAttachmentInParentLevel (MultiGrid &mg, MGSubsetHandler &markSH, AInt &aNumManifoldEdges, bool bCreaseSurf)
void CalculateNumManifoldFacesVertexAttachmentInTopLevel (MultiGrid &mg, MGSubsetHandler &markSH, AInt &aNumManifoldFaces_tri, AInt &aNumManifoldFaces_quad)
number CalculateOctahedronVolume (const vector3 &a, const vector3 &b, const vector3 &c, const vector3 &d, const vector3 &e, const vector3 &f)
TAAPos::ValueType CalculateOuterNormal (Edge *v, int sideIndex, TAAPos aaPos)
TAAPos::ValueType CalculateOuterNormal (Face *v, int sideIndex, TAAPos aaPos)
TAAPos::ValueType CalculateOuterNormal (GridObject *v, int sideIndex, TAAPos aaPos)
TAAPos::ValueType CalculateOuterNormal (Vertex *v, int sideIndex, TAAPos aaPos)
TAAPos::ValueType CalculateOuterNormal (Volume *v, int sideIndex, TAAPos aaPos)
void CalculatePolychainEdgeNormals (vector2 *edgeNormalsOut, vector2 *polyChain, size_t polyChainSize, bool bOuterNormals)
number CalculatePrismVolume (const vector3 &a, const vector3 &b, const vector3 &c, const vector3 &d, const vector3 &e, const vector3 &f)
number CalculatePyramidAspectRatio (Grid &grid, Pyramid *pyr, Grid::VertexAttachmentAccessor< APosition > &aaPos)
number CalculatePyramidVolume (const vector3 &a, const vector3 &b, const vector3 &c, const vector3 &d, const vector3 &e)
number CalculateRightBendVal (vector2 &dirOut, number &normDotOut, SweepLineEdge &e, SweepLineVertex *firstVrt, vector2 lastDir, bool lastDirNormalized=false)
void CalculateSmoothCreaseManifoldPosInParentLevelLoopScheme (MultiGrid &mg, TAPosition &aPos, MGSubsetHandler &markSH, MGSubsetHandler &linearManifoldSH, TAPosition &aSmoothBndPosEvenVrt, TAPosition &aSmoothBndPosOddVrt, AInt &aNumManifoldEdges)
void CalculateSmoothManifoldPosInParentLevelButterflyScheme (MultiGrid &mg, TAPosition &aPos, MGSubsetHandler &markSH, MGSubsetHandler &linearManifoldSH, TAPosition &aSmoothBndPosOddVrt, AInt &aNumManifoldEdges)
void CalculateSmoothManifoldPosInParentLevelLoopScheme (MultiGrid &mg, TAPosition &aPos, MGSubsetHandler &markSH, MGSubsetHandler &linearManifoldSH, TAPosition &aSmoothBndPosEvenVrt, TAPosition &aSmoothBndPosOddVrt, AInt &aNumManifoldEdges)
void CalculateSmoothManifoldPosInTopLevelAveragingScheme (MultiGrid &mg, TAPosition &aPos, MGSubsetHandler &markSH, MGSubsetHandler &linearManifoldSH, TAPosition &aSmoothBndPos_tri, TAPosition &aSmoothBndPos_quad)
void CalculateSmoothVolumePosInTopLevel (MultiGrid &mg, MGSubsetHandler &markSH, APosition &aSmoothVolPos_toc, APosition &aSmoothVolPos_prism, APosition &aSmoothVolPos_hex)
number CalculateSubsetSurfaceArea (MultiGrid &mg, int subsetIndex, MGSubsetHandler &sh)
number CalculateSubsetVolume (MultiGrid &mg, int subsetIndex, MGSubsetHandler &sh)
number CalculateTetrahedronAspectRatio (Grid &grid, Tetrahedron *tet, Grid::VertexAttachmentAccessor< APosition > &aaPos)
UG_API number CalculateTetrahedronRootMeanSquareFaceArea (Grid &grid, Tetrahedron *tet, Grid::VertexAttachmentAccessor< APosition > &aaPos)
UG_API number CalculateTetrahedronVolToRMSFaceAreaRatio (Grid &grid, Tetrahedron *tet, Grid::VertexAttachmentAccessor< APosition > &aaPos)
number CalculateTetrahedronVolume (const vector3 &a, const vector3 &b, const vector3 &c, const vector3 &d)
void CalculateTriangleNormal (SimpleGrid &sg, int triIndex)
void CalculateTriangleNormal (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3)
void CalculateTriangleNormalNoNormalize (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3)
void CalculateTriangleNormals (SimpleGrid &sg)
UG_API void CalculateVertexNormal (vector3 &nOut, Grid &grid, Vertex *vrt, TAAPosVRT &aaPos)
bool CalculateVertexNormals (Grid &grid, APosition &aPos, ANormal &aNorm)
bool CalculateVertexNormals (Grid &grid, Grid::AttachmentAccessor< Vertex, APosition > &aaPos, Grid::AttachmentAccessor< Vertex, ANormal > &aaNorm)
number CalculateVolToRMSFaceAreaRatio (Grid &grid, Face *face, TAAPosVRT &aaPos)
number CalculateVolToRMSFaceAreaRatio (Grid &grid, Hexahedron *hex, TAAPosVRT &aaPos)
number CalculateVolToRMSFaceAreaRatio (Grid &grid, TElem *elem, TAAPosVRT &aaPos)
number CalculateVolToRMSFaceAreaRatio (Grid &grid, Tetrahedron *tet, TAAPosVRT &aaPos)
number CalculateVolToRMSFaceAreaRatio (Grid &grid, Volume *vol, TAAPosVRT &aaPos)
number CalculateVolume (EdgeVertices *elem, TAAPos aaPos)
number CalculateVolume (FaceVertices *elem, TAAPos aaPos)
number CalculateVolume (Hexahedron *elem, TAAPos aaPos)
number CalculateVolume (Octahedron *elem, TAAPos aaPos)
number CalculateVolume (Prism *elem, TAAPos aaPos)
number CalculateVolume (Pyramid *elem, TAAPos aaPos)
number CalculateVolume (Tetrahedron *elem, TAAPos aaPos)
number CalculateVolume (TIterator begin, TIterator end, TAAPos aaPos)
number CalculateVolume (Vertex *elem, TAAPos aaPos)
number CalculateVolume (Volume *elem, TAAPos aaPos)
template<typename TGridFunction >
void cflNumber (TGridFunction &u, number deltaT)
void cgetrf_ (lapack_int *m, lapack_int *n, std::complex< lapack_float > *pColMajorMatrix, lapack_int *lda, lapack_int *ipiv, lapack_int *info)
void cgetrs_ (char *trans, lapack_int *n, lapack_int *nrhs, const std::complex< lapack_float > *pColMajorMatrix, lapack_int *lda, const lapack_int *ipiv, std::complex< lapack_float > *b, lapack_int *ldb, lapack_int *info)
UG_API void ChangeDirectory (std::string dir)
number Chebyshev1Poly (size_t k, number x)
number Chebyshev2Poly (size_t k, number x)
void check_subset_strings (std::vector< std::string > s)
bool CheckDiagonalInvertible (const ParallelMatrix< TSparseMatrix > &m)
bool CheckDiagonalInvertible (const TSparseMatrix &A)
bool CheckDirection (TElem1 *e1, TElem2 *e2, const TAAPos &aaPos, const typename TAAPos::ValueType &dir, number minAngle, number maxAngle)
static bool CheckDistributedObjectConstraintTypes (MultiGrid &mg)
bool CheckDistributedParentTypes (MultiGrid &mg)
bool CheckDoFElem (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, std::vector< MathVector< TDomain::dim > > &vPos)
bool CheckDoFPositions (const TFunction &u)
bool CheckDoFPositions (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd)
bool CheckElementConsistency (MultiGrid &mg, Edge *e)
bool CheckElementConsistency (MultiGrid &mg, Face *f)
bool CheckElementConsistency (MultiGrid &mg, Vertex *v)
bool CheckEnoughTimePassedToNow (ProfileCall &pc, Shiny::tick_t tnow)
bool CheckForUnconnectedSides (Grid &grid)
static bool CheckForUnconnectedSidesIMPL (Grid &grid)
bool CheckGFforNaN (const TGridFunction *u, const char *fct_names)
bool CheckGFforNaN (const TGridFunction *u, const FunctionGroup &fctGroup)
bool CheckGFforNaN (const TGridFunction *u, size_t fct)
bool CheckGFValuesWithinBounds (ConstSmartPtr< TGridFunction > u, const char *fctNames, number lowerBnd, number upperBnd)
bool CheckGFValuesWithinBounds (ConstSmartPtr< TGridFunction > u, size_t cmp, number lowerBnd, number upperBnd)
bool CheckHangingNodeConsistency (Grid &g)
bool CheckHangingNodeConsistency (MultiGrid &mg)
void CheckHangingNodeConstrainingFace (bool isConsistent, Grid &g, T iter, T end)
static int CheckLine (const vector3 &p1, const vector3 &p2, int outcode_diff)
bool CheckLocalParentTypes (MultiGrid &mg)
bool CheckLuaCallbackName (const char *name)
void CheckMultiGridConsistency (MultiGrid &mg)
static void CheckMultiGridConsistencyImpl (MultiGrid &mg)
bool CheckOrientation (Volume *vol, TAAPosVRT &aaPosVRT)
bool CheckPermutationBijective (const std::vector< size_t > &perm)
static int CheckPoint (const vector3 &p1, const vector3 &p2, number alpha, long mask)
bool CheckRowIterators (const TSparseMatrix &A)
void checksub (const CPUAlgebra::matrix_type &A)
void CheckValences (MultiGrid &mg, MGSubsetHandler &markSH, const char *filename)
bool CheckVectorInvertible (const ParallelVector< TVector > &v)
bool CheckVectorInvertible (const TVector &v)
void ClearAbortRunFlag ()
TNumber clip (TNumber val, TNumber lowerBound, TNumber upperBound)
bool CloneVector (ParallelVector< TVector > &dest, const ParallelVector< TVector > &src)
void CloneVector (Vector< TValueType > &dest, const Vector< TValueType > &src)
AnisotropyState close_sides_of_anisotropic_elem (Edge *elem, Grid &grid, const TAAPos &aaPos, number thresholdRatio, std::vector< Vertex * > &sidesOut)
AnisotropyState close_sides_of_anisotropic_elem (Face *elem, Grid &grid, const TAAPos &aaPos, number thresholdRatio, std::vector< Edge * > &sidesOut)
AnisotropyState close_sides_of_anisotropic_elem (Volume *elem, Grid &grid, const TAAPos &aaPos, number thresholdRatio, std::vector< Face * > &sidesOut)
bool CloseLibrary (DynLibHandle h)
void CloseSelection (TSelector &sel)
template void CloseSelection< MGSelector > (MGSelector &sel)
template void CloseSelection< Selector > (Selector &sel)
bool CloseToZero (double d)
bool cmp_slv (const SweepLineVertex &v1, const SweepLineVertex &v2)
static bool cmpQPairs (const std::pair< number, number > &a, const std::pair< number, number > &b)
bool CollapseEdge (Grid &grid, Edge *e, Vertex *newVrt)
bool CollapseEdge (SimpleGrid &sg)
static bool CollectAllVerticesForNG (Grid &grid, VertexSelector &NgVrtSel, VertexSelector &SurfVrtSel, VertexSelector &InnVrtSel)
template<class TIterator , class TAAPosVRT >
void CollectAspectRatios (Grid &grid, TIterator elementsBegin, TIterator elementsEnd, TAAPosVRT &aaPos, vector< number > &aspectRatios)
void CollectAssociated (std::vector< Edge * > &vEdgesOut, Grid &grid, Edge *e, bool clearContainer=true)
void CollectAssociated (std::vector< Edge * > &vEdgesOut, Grid &grid, Face *f, bool clearContainer=true)
void CollectAssociated (std::vector< Edge * > &vEdgesOut, Grid &grid, GridObject *obj, bool clearContainer=true)
void CollectAssociated (std::vector< Edge * > &vEdgesOut, Grid &grid, Vertex *vrt, bool clearContainer=true)
void CollectAssociated (std::vector< Edge * > &vEdgesOut, Grid &grid, Volume *v, bool clearContainer=true)
void CollectAssociated (std::vector< Face * > &vFacesOut, Grid &grid, Edge *e, bool clearContainer=true)
void CollectAssociated (std::vector< Face * > &vFacesOut, Grid &grid, Face *vol, bool clearContainer=true)
void CollectAssociated (std::vector< Face * > &vFacesOut, Grid &grid, GridObject *obj, bool clearContainer=true)
void CollectAssociated (std::vector< Face * > &vFacesOut, Grid &grid, Vertex *vrt, bool clearContainer=true)
void CollectAssociated (std::vector< Face * > &vFacesOut, Grid &grid, Volume *v, bool clearContainer=true)
UG_API void CollectAssociated (std::vector< Vertex * > &vVertexOut, Grid &grid, Edge *e, bool clearContainer=true)
UG_API void CollectAssociated (std::vector< Vertex * > &vVertexOut, Grid &grid, Face *f, bool clearContainer=true)
UG_API void CollectAssociated (std::vector< Vertex * > &vVertexOut, Grid &grid, GridObject *obj, bool clearContainer=true)
UG_API void CollectAssociated (std::vector< Vertex * > &vVertexOut, Grid &grid, Vertex *v, bool clearContainer=true)
void CollectAssociated (std::vector< Vertex * > &vVertexOut, Grid &grid, Volume *v, bool clearContainer=true)
void CollectAssociated (std::vector< Volume * > &vVolumesOut, Grid &grid, Edge *e, bool clearContainer=true)
void CollectAssociated (std::vector< Volume * > &vVolumesOut, Grid &grid, Face *f, bool clearContainer=true, bool ignoreAssociatedVolumes=false)
void CollectAssociated (std::vector< Volume * > &vVolumesOut, Grid &grid, FaceDescriptor &fd, bool clearContainer=true)
void CollectAssociated (std::vector< Volume * > &vVolumesOut, Grid &grid, GridObject *obj, bool clearContainer=true)
void CollectAssociated (std::vector< Volume * > &vVolumesOut, Grid &grid, Vertex *vrt, bool clearContainer=true)
void CollectAssociated (std::vector< Volume * > &vVolumesOut, Grid &grid, Volume *vol, bool clearContainer=true)
UG_API void CollectAssociatedSides (Edge *sidesOut[2], Grid &grid, Face *f, Vertex *vrt)
UG_API void CollectAssociatedSides (Face *sidesOut[2], Grid &grid, Volume *v, Edge *e)
void CollectConstraining (std::vector< Vertex * > &vConstrainingVrt, const Grid &grid, ConstrainedVertex *hgVrt, bool bClearContainer)
void CollectCornerCoordinates (int base_object_id, std::vector< typename TDomain::position_type > &vCornerCoordsOut, GridObject &elem, const TDomain &domain, bool clearContainer)
void CollectCornerCoordinates (std::vector< typename TAAPos::ValueType > &vCornerCoordsOut, const TElem &elem, const TAAPos &aaPos, bool clearContainer=true)
void CollectCornerCoordinates (std::vector< typename TAAPos::ValueType > &vCornerCoordsOut, TElem *elem, const TAAPos &aaPos, bool clearContainer)
void CollectCornerCoordinates (std::vector< typename TDomain::position_type > &vCornerCoordsOut, const TElem &elem, const TDomain &domain, bool clearContainer=true)
UG_API void CollectEdges (std::vector< Edge * > &vEdgesOut, Grid &grid, Edge *e, bool clearContainer=true)
UG_API void CollectEdges (std::vector< Edge * > &vEdgesOut, Grid &grid, Face *f, bool clearContainer=true)
void CollectEdges (std::vector< Edge * > &vEdgesOut, Grid &grid, Vertex *vrt, bool clearContainer)
UG_API void CollectEdges (std::vector< Edge * > &vEdgesOut, Grid &grid, Volume *v, bool clearContainer=true)
void CollectEdges (vector< Edge * > &vEdgesOut, Grid &grid, Edge *e, bool clearContainer)
void CollectEdges (vector< Edge * > &vEdgesOut, Grid &grid, Face *f, bool clearContainer)
void CollectEdges (vector< Edge * > &vEdgesOut, Grid &grid, Volume *v, bool clearContainer)
UG_API void CollectEdgesSorted (std::vector< Edge * > &vEdgesOut, Grid &grid, Edge *e, bool clearContainer=true)
UG_API void CollectEdgesSorted (std::vector< Edge * > &vEdgesOut, Grid &grid, Face *f, bool clearContainer=true)
void CollectEdgesSorted (std::vector< Edge * > &vEdgesOut, Grid &grid, GridObject *obj, bool clearContainer=true)
UG_API void CollectEdgesSorted (std::vector< Edge * > &vEdgesOut, Grid &grid, Vertex *v, bool clearContainer=true)
UG_API void CollectEdgesSorted (std::vector< Edge * > &vEdgesOut, Grid &grid, Volume *v, bool clearContainer=true)
void CollectEdgesSorted (vector< Edge * > &vEdgesOut, Grid &grid, Edge *e, bool clearContainer)
void CollectEdgesSorted (vector< Edge * > &vEdgesOut, Grid &grid, Face *f, bool clearContainer)
void CollectEdgesSorted (vector< Edge * > &vEdgesOut, Grid &grid, Vertex *v, bool clearContainer)
void CollectEdgesSorted (vector< Edge * > &vEdgesOut, Grid &grid, Volume *v, bool clearContainer)
void CollectFaces (std::vector< Face * > &vFacesOut, Grid &grid, Edge *e, bool clearContainer)
UG_API void CollectFaces (std::vector< Face * > &vFacesOut, Grid &grid, Face *v, bool clearContainer=true)
void CollectFaces (std::vector< Face * > &vFacesOut, Grid &grid, Vertex *vrt, bool clearContainer)
UG_API void CollectFaces (std::vector< Face * > &vFacesOut, Grid &grid, Volume *v, bool clearContainer=true)
void CollectFaces (vector< Face * > &vFacesOut, Grid &grid, Face *e, bool clearContainer)
void CollectFaces (vector< Face * > &vFacesOut, Grid &grid, Volume *v, bool clearContainer)
UG_API void CollectFacesSorted (std::vector< Face * > &vFacesOut, Grid &grid, Edge *e, bool clearContainer=true)
UG_API void CollectFacesSorted (std::vector< Face * > &vFacesOut, Grid &grid, Face *f, bool clearContainer=true)
void CollectFacesSorted (std::vector< Face * > &vFacesOut, Grid &grid, GridObject *obj, bool clearContainer=true)
UG_API void CollectFacesSorted (std::vector< Face * > &vFacesOut, Grid &grid, Vertex *v, bool clearContainer=true)
UG_API void CollectFacesSorted (std::vector< Face * > &vFacesOut, Grid &grid, Volume *v, bool clearContainer=true)
void CollectFacesSorted (vector< Face * > &vFacesOut, Grid &grid, Edge *e, bool clearContainer)
void CollectFacesSorted (vector< Face * > &vFacesOut, Grid &grid, Face *f, bool clearContainer)
void CollectFacesSorted (vector< Face * > &vFacesOut, Grid &grid, Vertex *v, bool clearContainer)
void CollectFacesSorted (vector< Face * > &vFacesOut, Grid &grid, Volume *v, bool clearContainer)
void CollectIErrEstData (std::vector< IErrEstData< TDomain > * > &vErrEstData, const T &vElemDisc)
static bool CollectInnerVertices (Grid &grid, VertexSelector &InnVrtSel, VertexSelector &SurfVrtSel)
static bool CollectLines (Grid &grid, const SubsetHandler &shFace, EdgeSelector &LineSel)
void CollectMatrixOnOneProc (const matrix_type &A, matrix_type &collectedA, IndexLayout &masterLayout, IndexLayout &slaveLayout)
template<class TIterator , class TAAPosVRT >
void CollectMaxAngles (Grid &grid, TIterator elementsBegin, TIterator elementsEnd, TAAPosVRT &aaPos, vector< number > &maxAngles)
template<class TIterator , class TAAPosVRT >
void CollectMinAngles (Grid &grid, TIterator elementsBegin, TIterator elementsEnd, TAAPosVRT &aaPos, vector< number > &minAngles)
void CollectNeighborhood (std::vector< Face * > &facesOut, Grid &grid, Vertex *vrt, size_t range, bool clearContainer=true)
void CollectNeighbors (std::vector< Edge * > &vNeighborsOut, Edge *e, Grid &grid, NeighborhoodType nbhType=NHT_VERTEX_NEIGHBORS)
void CollectNeighbors (std::vector< Face * > &vNeighborsOut, Face *f, Grid &grid, NeighborhoodType nbhType=NHT_EDGE_NEIGHBORS)
void CollectNeighbors (std::vector< Vertex * > &vNeighborsOut, Grid &grid, Vertex *vrt, uint nbhType=NHT_EDGE_NEIGHBORS, Grid::edge_traits::callback considerEdge=ConsiderAll(), Grid::face_traits::callback considerFace=ConsiderAll(), Grid::volume_traits::callback considerVol=ConsiderAll())
void CollectNeighbors (std::vector< Volume * > &vNeighboursOut, Volume *v, Grid &grid, NeighborhoodType nbhType=NHT_FACE_NEIGHBORS)
void collectStretchedElementIndices (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, std::vector< size_t > &indarray, number alpha)
bool CollectSurfaceNeighborsSorted (std::vector< Vertex * > &vNeighborsOut, Grid &grid, Vertex *v)
static bool CollectSurfaceVertices (Grid &grid, const SubsetHandler &shFace, VertexSelector &SurfVrtSel)
void CollectSurfaceViewElements (ISubsetHandler &surfaceViewOut, DistributedGridManager &distGridMgr, MultiGridSubsetHandler &mgsh, bool clearContainer)
void CollectSurfaceViewElements (ISubsetHandler &surfaceViewOut, MultiGrid &mg, MGSubsetHandler &mgsh, bool clearContainer=true)
size_t CollectUnconnectedSides (std::vector< typename TSideIterator::value_type > &elemsOut, Grid &grid, TSideIterator begin, TSideIterator end)
static void CollectUniqueObjects (vector< TType > &vecOut, const vector< TType > &vecIn)
void CollectVertices (std::vector< Vertex * > &vVertexOut, Grid &grid, Edge *e, bool clearContainer)
void CollectVertices (std::vector< Vertex * > &vVertexOut, Grid &grid, Face *f, bool clearContainer)
UG_API void CollectVertices (std::vector< Vertex * > &vVertexOut, Grid &grid, GridObject *obj, bool clearContainer=true)
void CollectVertices (std::vector< Vertex * > &vVertexOut, Grid &grid, Vertex *v, bool clearContainer)
void CollectVertices (std::vector< Vertex * > &vVertexOut, Grid &grid, Volume *v, bool clearContainer)
size_t CollectVerticesTouchingSelection (std::vector< Vertex * > &vrtsOut, ISelector &sel)
template<class TIterator , class TAAPosVRT >
void CollectVolToRMSFaceAreaRatios (Grid &grid, TIterator elementsBegin, TIterator elementsEnd, TAAPosVRT &aaPos, vector< number > &ratios)
void CollectVolumes (std::vector< Volume * > &vVolumesOut, Grid &grid, Edge *e, bool clearContainer)
void CollectVolumes (std::vector< Volume * > &vVolumesOut, Grid &grid, Face *f, bool clearContainer, bool ignoreAssociatedVolumes)
void CollectVolumes (std::vector< Volume * > &vVolumesOut, Grid &grid, FaceDescriptor &fd, bool clearContainer)
void CollectVolumes (std::vector< Volume * > &vVolumesOut, Grid &grid, Vertex *vrt, bool clearContainer=true)
UG_API void CollectVolumes (std::vector< Volume * > &vVolumesOut, Grid &grid, Volume *v, bool clearContainer=true)
void CollectVolumes (vector< Volume * > &vVolumesOut, Grid &grid, Volume *v, bool clearContainer)
void ColorControlVolume (ISubsetHandler &shOut)
int ColorProcessorGraph (pcl::InterfaceCommunicator< IndexLayout > &com, std::set< int > &pids, std::vector< int > &processesWithLowerColor, std::vector< int > &processesWithHigherColor)
void ColorSubControlVolume (ISubsetHandler &shOut)
void ColorSubControlVolumeFaces (ISubsetHandler &shOut)
vector< nodeType * > CommaListToVector (nodeType *a)
void CommunicateConnections (std::vector< std::vector< int > > &connectionsToProcsOut, std::vector< std::vector< int > > &connectionsToSubDomsOut, IndexLayout &masterLayout, IndexLayout &slaveLayout, int highestReferencedIndex, pcl::IDomainDecompositionInfo &ddinfo)
void CommunicateConnections (vector< vector< int > > &connectionsToProcsOut, vector< vector< int > > &connectionsToSubDomsOut, const IndexLayout &masterLayout, const IndexLayout &slaveLayout, int highestReferencedIndex, pcl::IDomainDecompositionInfo &ddinfo)
void CommunicateFromMasterToSlave (HorizontalAlgebraLayouts &layouts, TCommunicationScheme &scheme)
void CommunicateFromSlaveToMaster (HorizontalAlgebraLayouts &layouts, TCommunicationScheme &scheme)
void CommunicateOnInterfaces (pcl::InterfaceCommunicator< IndexLayout > &communicator, const IndexLayout &sendingLayout, const IndexLayout &receivingLayout, TCommunicationScheme &scheme)
bool ComparePosDim (const std::pair< MathVector< dim >, size_t > &p1, const std::pair< MathVector< dim >, size_t > &p2)
bool ComparePosDim< 1, 0 > (const std::pair< MathVector< 1 >, size_t > &p1, const std::pair< MathVector< 1 >, size_t > &p2)
bool ComparePosDim< 2, 0 > (const std::pair< MathVector< 2 >, size_t > &p1, const std::pair< MathVector< 2 >, size_t > &p2)
bool ComparePosDim< 2, 1 > (const std::pair< MathVector< 2 >, size_t > &p1, const std::pair< MathVector< 2 >, size_t > &p2)
bool ComparePosDim< 3, 0 > (const std::pair< MathVector< 3 >, size_t > &p1, const std::pair< MathVector< 3 >, size_t > &p2)
bool ComparePosDim< 3, 1 > (const std::pair< MathVector< 3 >, size_t > &p1, const std::pair< MathVector< 3 >, size_t > &p2)
bool ComparePosDim< 3, 2 > (const std::pair< MathVector< 3 >, size_t > &p1, const std::pair< MathVector< 3 >, size_t > &p2)
bool ComparePosDimDec (const std::pair< MathVector< dim >, size_t > &p1, const std::pair< MathVector< dim >, size_t > &p2)
bool ComparePosDimDec< 1, 0 > (const std::pair< MathVector< 1 >, size_t > &p1, const std::pair< MathVector< 1 >, size_t > &p2)
bool ComparePosDimDec< 2, 0 > (const std::pair< MathVector< 2 >, size_t > &p1, const std::pair< MathVector< 2 >, size_t > &p2)
bool ComparePosDimDec< 2, 1 > (const std::pair< MathVector< 2 >, size_t > &p1, const std::pair< MathVector< 2 >, size_t > &p2)
bool ComparePosDimDec< 3, 0 > (const std::pair< MathVector< 3 >, size_t > &p1, const std::pair< MathVector< 3 >, size_t > &p2)
bool ComparePosDimDec< 3, 1 > (const std::pair< MathVector< 3 >, size_t > &p1, const std::pair< MathVector< 3 >, size_t > &p2)
bool ComparePosDimDec< 3, 2 > (const std::pair< MathVector< 3 >, size_t > &p1, const std::pair< MathVector< 3 >, size_t > &p2)
bool ComparePosDimYDir (const std::pair< MathVector< dim >, size_t > &p1, const std::pair< MathVector< dim >, size_t > &p2)
bool ComparePosDimYDir< 1 > (const std::pair< MathVector< 1 >, size_t > &p1, const std::pair< MathVector< 1 >, size_t > &p2)
bool ComparePosDimYDir< 2 > (const std::pair< MathVector< 2 >, size_t > &p1, const std::pair< MathVector< 2 >, size_t > &p2)
bool ComparePosDimYDir< 3 > (const std::pair< MathVector< 3 >, size_t > &p1, const std::pair< MathVector< 3 >, size_t > &p2)
bool ComparePosDimZDir (const std::pair< MathVector< dim >, size_t > &p1, const std::pair< MathVector< dim >, size_t > &p2)
bool ComparePosDimZDir< 1 > (const std::pair< MathVector< 1 >, size_t > &p1, const std::pair< MathVector< 1 >, size_t > &p2)
bool ComparePosDimZDir< 2 > (const std::pair< MathVector< 2 >, size_t > &p1, const std::pair< MathVector< 2 >, size_t > &p2)
bool ComparePosDimZDir< 3 > (const std::pair< MathVector< 3 >, size_t > &p1, const std::pair< MathVector< 3 >, size_t > &p2)
bool CompareScalar (const std::pair< number, size_t > &p1, const std::pair< number, size_t > &p2)
UG_API bool CompareVertexContainer (const TVrtContainer1 &con1, const TVrtContainer2 &con2)
UG_API bool CompareVertices (const EdgeVertices *ev1, const EdgeVertices *ev2)
bool CompareVertices (const FaceVertices *fv1, const FaceVertices *fv2)
bool CompareVertices (const VolumeVertices *vv1, const VolumeVertices *vv2)
static number compute_angle (const vector3 &axis, const vector3 &secondAxis, const vector3 &thirdAxis, const vector3 &posFromAxis)
static void compute_first_section_end_points (vector3 &pos0Out, vector3 &pos1Out, std::vector< NeuriteProjector::Section >::const_iterator secIt)
static void compute_ONB (vector3 &firstOut, vector3 &secondOut, vector3 &thirdOut, const vector3 &firstIn, const vector3 &refDir)
static void compute_position_and_velocity_in_section (vector3 &posAxOut, vector3 &velOut, number &radiusOut, std::vector< NeuriteProjector::Section >::const_iterator secIt, float t)
static void compute_radius_in_section (number &radiusOut, std::vector< NeuriteProjector::Section >::const_iterator secIt, float t)
number ComputeAvg (MultiGrid::AttachmentAccessor< TElem, ug::Attachment< number > > &aaError2, ConstSmartPtr< DoFDistribution > dd, number &min, number &max, number &sum, number &errSq, size_t &numElem, number &minLocal, number &maxLocal, number &sumLocal, size_t &numElemLocal)
static void ComputeBFMidID (const TRefElem &rRefElem, int side, MidID vMidID[], int co)
void ComputeCRCuthillMcKeeOrder (std::vector< size_t > &vNewIndex, std::vector< std::vector< size_t > > &vvConnections, size_t minpind, bool bReverse)
void ComputeCuthillMcKeeOrder (std::vector< size_t > &vNewIndex, std::vector< std::vector< size_t > > &vvNeighbour, bool bReverse=true, bool bPreserveConsec=true)
void computeDegree (std::vector< size_t > &degree, std::vector< std::vector< size_t > > &vvConnections, size_t minpind)
void ComputeDifferenceOnDelta (TVector &diff, const TVector &u, IndexLayout &dualMasterLayoutIn, IndexLayout &dualSlaveLayoutIn, IndexLayout &dualNbrMasterLayoutIn, IndexLayout &dualNbrSlaveLayoutIn)
void ComputeDifferenceOnDeltaTransposed (TVector &f, const TVector &diff, const std::vector< IndexLayout::Element > &vDualMasterIndex, const std::vector< IndexLayout::Element > &vDualSlaveIndex, const std::vector< IndexLayout::Element > &vDualNbrSlaveIndex)
void ComputeDirectionYOrder (std::vector< std::pair< MathVector< dim >, size_t > > &vPos, std::vector< size_t > &indY)
void ComputeDirectionZOrder (std::vector< std::pair< MathVector< dim >, size_t > > &vPos, std::vector< size_t > &indZ)
void ComputeElementExtensionsSq (const MathVector< TWorldDim > *vCornerCoords, MathVector< TWorldDim > &ext)
void ComputeElementExtensionsSqForEdges (const TVector *vCornerCoords, TVector &ext)
void ComputeGradientCrouzeixRaviart (TFunction &u, size_t fct, MultiGrid::AttachmentAccessor< typename TFunction::element_type, ug::Attachment< number > > &aaError)
void computeGradientJump (TFunction &u, MultiGrid::AttachmentAccessor< typename TFunction::element_type, ug::Attachment< number > > &aaGrad, MultiGrid::AttachmentAccessor< typename TFunction::element_type, ug::Attachment< number > > &aaError)
void ComputeGradientLagrange1 (TFunction &u, size_t fct, MultiGrid::AttachmentAccessor< typename TFunction::element_type, ug::Attachment< number > > &aaError)
void ComputeGradientPiecewiseConstant (TFunction &u, size_t fct, MultiGrid::AttachmentAccessor< typename TFunction::element_type, ug::Attachment< number > > &aaError)
void ComputeLexicographicOrder (std::vector< size_t > &vNewIndex, std::vector< std::pair< MathVector< dim >, size_t > > &vPos, size_t orderDim, bool increasing)
void ComputeLocalSubsetDimensions (ISubsetHandler &sh, AChar aDimension, bool includeUnassigned)
static void ComputeMidPoints (const TRefElem &rRefElem, const MathVector< dim > vCorner[], MathVector< dim > vvMid[][maxMid])
void ComputeMinMax (MultiGrid::AttachmentAccessor< TElem, ug::Attachment< number > > &aaError, ConstSmartPtr< DoFDistribution > dd, number &min, number &max, number &totalErr, size_t &numElem, number &minLocal, number &maxLocal, number &totalErrLocal, size_t &numElemLocal)
void ComputeMinMaxTotal (MultiGrid::AttachmentAccessor< TElem, ug::Attachment< number > > &aaError2, ConstSmartPtr< DoFDistribution > dd, number &min, number &max, number &totalErr, size_t &numElem)
void ComputeMultiIndicesOfSubElement (std::vector< MathVector< dim, int > > *vvMultiIndex, bool *vIsBndElem, std::vector< int > *vElemBndSide, std::vector< size_t > *vIndex, ReferenceObjectID roid, int p)
void ComputeMultiIndicesOfSubElement< 1 > (std::vector< MathVector< 1, int > > *vvMultiIndex, bool *vIsBndElem, std::vector< int > *vElemBndSide, std::vector< size_t > *vIndex, ReferenceObjectID roid, int p)
void ComputeMultiIndicesOfSubElement< 2 > (std::vector< MathVector< 2, int > > *vvMultiIndex, bool *vIsBndElem, std::vector< int > *vElemBndSide, std::vector< size_t > *vIndex, ReferenceObjectID roid, int p)
void ComputeMultiIndicesOfSubElement< 3 > (std::vector< MathVector< 3, int > > *vvMultiIndex, bool *vIsBndElem, std::vector< int > *vElemBndSide, std::vector< size_t > *vIndex, ReferenceObjectID roid, int p)
void computeNewIndicesFromPIndexset (std::vector< std::vector< size_t > > &vvConnection, std::vector< size_t > &newIndex, size_t pmin, const std::vector< int > &inv_perm, bool bseparate)
void computeNewIndicesFromVIndexset (std::vector< std::vector< size_t > > &vvConnection, std::vector< size_t > &newIndex, size_t pmin, size_t dim, const std::vector< int > &inv_perm, bool bseparate, size_t strategy)
void ComputeOrientationOffset (std::vector< size_t > &vOrientOffset, Face *face, Edge *edge, size_t nrEdge, const LFEID &lfeid)
void ComputeOrientationOffset (std::vector< size_t > &vOrientOffset, GridObject *Elem, GridObject *SubElem, size_t nrSub, const LFEID &lfeid)
void ComputeOrientationOffset (std::vector< size_t > &vOrientOffset, Volume *vol, Edge *edge, size_t nrEdge, const LFEID &lfeid)
void ComputeOrientationOffset (std::vector< size_t > &vOrientOffset, Volume *vol, Face *face, size_t nrFace, const LFEID &lfeid)
void ComputeOrientationOffsetGeneric (std::vector< size_t > &vOrientOffset, TBaseElem *elem, TSubBaseElem *sub, size_t nrSub, const LFEID &lfeid)
void ComputeOrientationOffsetLagrange (std::vector< size_t > &vOrientOffset, EdgeDescriptor &ed, EdgeVertices *edge, const size_t p)
void ComputeOrientationOffsetLagrange (std::vector< size_t > &vOrientOffset, Face *face, Edge *edge, size_t nrEdge, const size_t p)
void ComputeOrientationOffsetLagrange (std::vector< size_t > &vOrientOffset, GridObject *volume, GridObject *face, size_t nrFace, const size_t p)
void ComputeOrientationOffsetLagrange (std::vector< size_t > &vOrientOffset, Volume *vol, Edge *edge, size_t nrEdge, const size_t p)
void ComputeOrientationOffsetLagrange (std::vector< size_t > &vOrientOffset, Volume *volume, Face *face, size_t nrFace, const size_t p)
static void ComputeSCVFMidID (const TRefElem &rRefElem, MidID vMidID[], int i)
static void ComputeSCVMidID (const TRefElem &rRefElem, MidID vMidID[], int i)
UG_API std::string ConfigShift (std::string s)
string ConfigShift (string s)
char ConfigShiftRotation (char c)
void ConsistencyCheck (const TVec &vec, const HorizontalAlgebraLayouts &layout, std::string name="")
void ConsistencyCheck (const TVec &vec, pcl::InterfaceCommunicator< IndexLayout > &com, const pcl::ProcessCommunicator &pc, const IndexLayout &masterLayout, const IndexLayout &slaveLayout, std::string name="")
void ConsistentToUnique (TVector *pVec, const IndexLayout &slaveLayout)
template<typename TGridFunction , typename side_type , typename constraining_side_type , typename VType >
void constrainingSideAveraging (PeriodicAttachmentAccessor< side_type, Attachment< VType > > &aaData, SmartPtr< TGridFunction > m_uInfo)
void ConstructDualGraph (std::vector< TIndexType > &adjacencyMapStructureOut, std::vector< TIndexType > &adjacencyMapOut, Grid &grid, Attachment< TIndexType > *paIndex=NULL, TGeomBaseObj **pGeomObjsOut=NULL, NeighborhoodType nbhType=NHT_DEFAULT, const GridObjectCollection *pgoc=NULL)
void ConstructDualGraphMG (std::vector< TIndexType > &adjacencyMapStructureOut, std::vector< TIndexType > &adjacencyMapOut, std::vector< TIndexType > *pEdgeWeightsOut, MultiGrid &mg, size_t baseLevel=0, int hWeight=1, int vWeight=1, Attachment< TIndexType > *paIndex=NULL, TGeomBaseObj **pGeomObjsOut=NULL, NeighborhoodType nbhType=NHT_DEFAULT)
void ConstructDualGraphMGLevel (std::vector< TIndexType > &adjacencyMapStructureOut, std::vector< TIndexType > &adjacencyMapOut, MultiGrid &mg, size_t level, Attachment< TIndexType > *paIndex=NULL, TGeomBaseObj **pGeomObjsOut=NULL, NeighborhoodType nbhType=NHT_DEFAULT, DualGraphNeighborCollector< TGeomBaseObj > *neighborCollector=NULL)
void ConstructGridOfSCV (ISubsetHandler &shOut, const SurfaceView &surfView, const Grid::VertexAttachmentAccessor< Attachment< MathVector< TWorldDim > > > &aaPos, Grid::VertexAttachmentAccessor< Attachment< MathVector< TWorldDim > > > &aaPosOut, int si)
void ConstructGridOfSCV (ISubsetHandler &shOut, const SurfaceView &surfView, const Grid::VertexAttachmentAccessor< Attachment< MathVector< TWorldDim > > > &aaPos, Grid::VertexAttachmentAccessor< Attachment< MathVector< TWorldDim > > > &aaPosOut, int si, int siDim)
void ConstructGridOfSCVF (ISubsetHandler &shOut, const SurfaceView &surfView, const Grid::VertexAttachmentAccessor< Attachment< MathVector< TWorldDim > > > &aaPos, Grid::VertexAttachmentAccessor< Attachment< MathVector< TWorldDim > > > &aaPosOut, int si)
void ConstructGridOfSCVF (ISubsetHandler &shOut, const SurfaceView &surfView, const Grid::VertexAttachmentAccessor< Attachment< MathVector< TWorldDim > > > &aaPos, Grid::VertexAttachmentAccessor< Attachment< MathVector< TWorldDim > > > &aaPosOut, int si, int siDim)
bool ConstructOrthonormalSystem (matrix33 &matOut, const vector3 &v, size_t vColInd)
void ConstructParallelDualGraphMGLevel (std::vector< TIndexType > &adjacencyMapStructureOut, std::vector< TIndexType > &adjacencyMapOut, std::vector< TIndexType > &nodeOffsetMapOut, MultiGrid &mg, size_t level, pcl::ProcessCommunicator procCom, Attachment< TIndexType > *paIndex=NULL, TGeomBaseObj **pGeomObjsOut=NULL, NeighborhoodType nbhType=NHT_DEFAULT)
UG_API bool Contains (const std::string &str, const std::string &search)
bool Contains (const string &str, const string &search)
static bool ContainsInterfaceElem (const TStdVector &elems, DistributedGridManager &distGridMgr)
UG_API bool ContainsPoint (const EdgeVertices *e, const vector_t &p, TAAPos aaPos)
UG_API bool ContainsPoint (const FaceVertices *f, const vector_t &p, TAAPos aaPos)
UG_API bool ContainsPoint (const Vertex *v, const vector_t &p, TAAPos aaPos)
UG_API bool ContainsPoint (Volume *vol, const vector3 &p, TAAPos aaPos)
static void ContinuousDebugSave (ISelector &sel)
bool ConvertMathVectorAttachmentValues (Grid &grid, TSrcAttachment &srcAttachment, TDestAttachment &destAttachment)
std::string ConvertNumber (uint64_t size, unsigned int width, unsigned int numDisplayedDigits)
std::string ConvertNumberSI (uint64_t size, unsigned int width, unsigned int numDisplayedDigits)
LFEID ConvertStringToLFEID (const char *type, int dim)
LFEID ConvertStringToLFEID (const char *type, int dim, int order)
void ConvertToTetrahedra (Grid &grid, TVolIter volsBegin, TVolIter volsEnd)
bool CopyAttachments (Grid &grid, TElemIter elemsBegin, TElemIter elemsEnd, TAttachment &aSrc, TAttachment &aDest)
bool CopyAttachments (Grid &srcGrid, TAttachment &aSrc, Grid &destGrid, TAttachment &aDest)
static void CopyCornerByMidID (MathVector< dim > vCorner[], const MidID vMidID[], MathVector< dim > vvMidPos[][maxMid], const size_t numCo)
template void CopyGrid (Grid &, Grid &, ISubsetHandler &, ISubsetHandler &, APosition1)
template void CopyGrid (Grid &, Grid &, ISubsetHandler &, ISubsetHandler &, APosition2)
template void CopyGrid (Grid &, Grid &, ISubsetHandler &, ISubsetHandler &, APosition3)
void CopyGrid (Grid &srcGrid, Grid &destGrid, ISubsetHandler &srcSH, ISubsetHandler &destSH, TAPos aPos)
void CopyGridElements (Grid &srcGrid, Grid &destGrid, ISubsetHandler &srcSH, ISubsetHandler &destSH, Attachment< Vertex * > &aNewVrt)
void CopyGridLevel (MultiGrid &srcMG, Grid &destGrid, ISubsetHandler &srcSH, ISubsetHandler &destSH, int lvl, TAPos aPos)
void CopyGridLevelElements (MultiGrid &srcMG, Grid &destGrid, ISubsetHandler &srcSH, ISubsetHandler &destSH, int lvl, AVertex &aNewVrt)
static void CopyInterfaceEntrysToDomainDecompositionLayouts (IndexLayout &subdomLayoutOut, IndexLayout &processLayoutOut, IndexLayout &deltaNbrLayoutOut, IndexLayout &crossPointLayoutOut, const IndexLayout &standardLayout, vector< int > &flags, IDomainDecompositionInfo &ddinfo)
void CopyOffDiagEntries (const TMatrixType &A, size_t i, TRowType &row, bool enforceNew=false)
void CopySelected (SmartPtr< TDomain > destDom, SmartPtr< TDomain > srcDom, Selector &sel)
void CopySelectedElements (Selector &srcSel, Grid &destGrid, AVertex aNewVrt)
void CopySelectedElements (SmartPtr< TDomain > destDom, SmartPtr< TDomain > srcDom, Selector &sel, AVertex &aNewVrt)
void CopySelection (Selector &srcSel, Grid &destGrid, TAAPosSrc aaPosSrc, TAAPosDest aaPosDest)
void CopySelectionStatus (Selector &selOut, Grid &gridOut, Selector &selIn, Grid &gridIn)
static void CopySubsetFromHigherDimNbr (ISubsetHandler &sh, TIterator elemsBegin, TIterator elemsEnd, AChar aDimension)
static void CopySubsetIndices (ISubsetHandler &dest, const ISubsetHandler &src, TIterator destIterBegin, TIterator destIterEnd, TIterator srcIterBegin, TIterator srcIterEnd)
void CopySubsetIndicesToSides (ISubsetHandler &sh, bool toUnassignedOnly)
void CopySubsetIndicesToSides (ISubsetHandler &sh, GridObjectCollection goc, bool toUnassignedOnly)
void CopySubsetIndicesToSides (ISubsetHandler &sh, ISelector &sel, bool toUnassignedOnly)
void CopySubsetIndicesToSides (ISubsetHandler &sh, TIterator elemsBegin, TIterator elemsEnd, bool toUnassignedOnly)
void CopyValues (TVector *pVec, const IndexLayout &sourceLayout, const IndexLayout &targetLayout, pcl::InterfaceCommunicator< IndexLayout > *pCom=NULL)
std::string CPPString (const DenseMatrix< TStorage > &A, const char *name)
template<typename TElem , typename TGridFunction >
void cr_get_connections (std::vector< std::vector< size_t > > &vvConnection, size_t &minpind, DoFDistribution &dd, TGridFunction &u)
uint32 crc32 (const char *str)
void CRCuthillMcKee (std::vector< size_t > &newIndex, std::vector< std::vector< size_t > > &vvConnection, size_t dim, size_t minpind, bool bReverse, bool bseparate, bool orderp, bool orderv)
orders the dof distribution using Cuthill-McKee
static SmartPtr< IRefiner > CreateAdaptiveRegularDomainRefiner (TDomain *dom)
void CreateAllToAllFromMasterSlave (pcl::InterfaceCommunicator< IndexLayout > &communicator, IndexLayout &OLCoarseningSendLayout, IndexLayout &OLCoarseningReceiveLayout, IndexLayout &OL1MasterLayout, IndexLayout &OL1SlaveLayout)
void CreateAndDistributeGlobalIDs (Grid &g, GridLayoutMap &glm, AGeomObjID &aID=aGeomObjID)
void CreateAsMultiplyOf (AB_type &M, const A_type &A, const B_type &B)
void CreateAsMultiplyOf (ABC_type &M, const A_type &A, const B_type &B, const C_type &C, double epsilonTruncation=0.0)
SmartPtr< CplUserData< MathMatrix< dim, dim >, dim > > CreateConstUserData (number val, MathMatrix< dim, dim >)
SmartPtr< CplUserData< MathTensor< 4, dim >, dim > > CreateConstUserData (number val, MathTensor< 4, dim >)
SmartPtr< CplUserData< MathVector< dim >, worldDim > > CreateConstUserData (number val, MathVector< dim >)
SmartPtr< CplUserData< number, dim > > CreateConstUserData (number val, number)
SmartPtr< CplUserData< TData, dim > > CreateConstUserData (number val, TData dummy)
void CreateControlVolumeDomain (TDomain &domOut, const TDomain &domIn, const SurfaceView &surfView, int si=-1)
UG_API bool CreateDirectory (const char *directory)
UG_API bool CreateDirectory (const char *directory, int mode)
static bool CreateDirectory (std::string directory)
UG_API bool CreateDirectoryTMP (const char *directory)
bool CreateEdgeSplitGeometry (Grid &destGrid, Grid &srcGrid, Edge *e, Vertex *newVertex, AVertex *paAssociatedVertices=NULL)
void CreateElementQualityHistogram (vector< int > &histOut, const std::vector< number > &vQualities, int numSections)
void CreateFunctionIndexMapping (FunctionIndexMapping &map, const FunctionGroup &grpFrom, ConstSmartPtr< FunctionPattern > fctPattern)
void CreateFunctionIndexMapping (FunctionIndexMapping &map, const FunctionGroup &grpFromSmall, const FunctionGroup &grpToLarge)
static SmartPtr< GlobalFracturedMediaRefiner > CreateGlobalFracturedDomainRefiner (TDomain *dom)
void CreateGlobalLayout (GlobalLayout &globalLayout, const IndexLayout &layout, const TLocalToGlobal &localToGlobal)
void CreateGridFromField (Grid &grid, const Field< number > &field, const vector2 &cellSize, const vector2 &offset, number noDataValue, Grid::VertexAttachmentAccessor< APosition > aaPos)
void CreateGridFromField (Grid &grid, const Heightfield &hfield, Grid::VertexAttachmentAccessor< APosition > aaPos)
void CreateGridFromFieldBoundary (Grid &grid, const Field< number > &field, const vector2 &cellSize, const vector2 &offset, number noDataValue, Grid::VertexAttachmentAccessor< APosition > aaPos)
void CreateGridFromFieldBoundary (Grid &grid, const Heightfield &hfield, Grid::VertexAttachmentAccessor< APosition > aaPos)
void CreateGridOfControlVolumes (ISubsetHandler &shOut, TAAPosition &aaPosOut, TAPosition &aPosOut, const ISubsetHandler &sh, const TAAPosition &aaPos, const SurfaceView &surfView, int si=-1)
void CreateGridOfSubControlVolumeFaces (ISubsetHandler &shOut, TAAPosition &aaPosOut, const ISubsetHandler &sh, const TAAPosition &aaPos, const SurfaceView &surfView, int si=-1)
void CreateGridOfSubControlVolumes (ISubsetHandler &shOut, TAAPosition &aaPosOut, const ISubsetHandler &sh, const TAAPosition &aaPos, const SurfaceView &surfView, int si=-1)
Hexahedron * CreateHexahedronFromPrisms (Grid &grid, Prism *p0, Prism *p1)
bool CreateIndexLayouts_DomainDecomposition (IndexLayout &processLayoutOut, IndexLayout &subdomainLayoutOut, DoFDistribution &dofDistr, GridLayoutMap &layoutMap, int keyType, int level, pcl::IDomainDecompositionInfo *ddInfoIn)
void CreateLayoutFromGlobalLayout (IndexLayout &layout, GlobalLayout &globalLayout, TGlobalToLocal &globalToLocal, bool bRemoveDoubles=true)
static void CreateLayoutsFromDistInfos (MultiGrid &mg, GridLayoutMap &glm, DistInfoSupplier &distInfos, AGeomObjID &aGID)
bool CreateLevelIndexLayout (IndexLayout &layoutOut, DoFDistribution &dofDistr, GridLayoutMap &layoutMap, int keyType, int level)
number CreateListOfElemWeights (Grid::AttachmentAccessor< TElem, ug::Attachment< number > > &aaError, typename DoFDistribution::traits< TElem >::const_iterator iterBegin, const typename DoFDistribution::traits< TElem >::const_iterator iterEnd, std::vector< double > &etaSq)
SmartPtr< AlgebraLayouts > CreateLocalAlgebraLayouts ()
SPOctree CreateOctree (Grid &grid, TIterator elemsBegin, TIterator elemsEnd, int maxDepth, int elemThreshold, bool bLoose, APosition &aPos=aPosition)
void CreateOverlap (TMatrix &matInOut)
bool CreatePolyChain (std::vector< Vertex * > &polyChainOut, Grid &grid, TEdgeIter edgesBegin, TEdgeIter edgesEnd)
static Prism * CreatePrism (Grid &grid, vector< Triangle * > &vTris, vector< Quadrilateral * > &vQuads, Grid::VertexAttachmentAccessor< APosition > &aaPos)
SPProcessHierarchy CreateProcessHierarchy (size_t *numElemsOnLvl, size_t numLvls, size_t minNumElemsPerProcPerLvl, size_t maxNumRedistProcs, size_t maxNumProcs, int minDistLvl, int maxLvlsWithoutRedist)
SPProcessHierarchy CreateProcessHierarchy (TDomain &dom, size_t minNumElemsPerProcPerLvl, size_t maxNumRedistProcs, size_t maxNumProcs, int minDistLvl, int maxLevelsWithoutRedist)
SPProcessHierarchy CreateProcessHierarchy (TDomain &dom, size_t minNumElemsPerProcPerLvl, size_t maxNumRedistProcs, size_t maxNumProcs, int minDistLvl, int maxLevelsWithoutRedist, IRefiner *refiner)
static Pyramid * CreatePyramid (Grid &grid, vector< Triangle * > &vTris, vector< Quadrilateral * > &vQuads, Grid::VertexAttachmentAccessor< APosition > &aaPos)
Quadrilateral * CreateQuadrilateral (Grid &g, Face *tri1, Face *tri2)
Quadrilateral * CreateQuadrilateral_NoRegistration (Grid &g, Face *tri1, Face *tri2)
void CreateSCV (const TElem &elem, TFVGeom< TElem, TWorldDim > &geo, ISubsetHandler &shOut, Grid::VertexAttachmentAccessor< Attachment< MathVector< TWorldDim > > > &aaPosOut)
void CreateSCVF (const TElem &elem, TFVGeom< TElem, TWorldDim > &geo, ISubsetHandler &shOut, Grid::VertexAttachmentAccessor< Attachment< MathVector< TWorldDim > > > &aaPosOut)
number CreateSortedListOfElems (Grid::AttachmentAccessor< TElem, ug::Attachment< number > > &aaError, typename DoFDistribution::traits< TElem >::const_iterator iterBegin, const typename DoFDistribution::traits< TElem >::const_iterator iterEnd, std::vector< std::pair< double, TElem * > > &etaSqList)
void CreateStrongConnectionGraphForSystems (const matrix_type &A, cgraph &graph, double theta)
void CreateSubControlVolumeDomain (TDomain &domOut, const TDomain &domIn, const SurfaceView &surfView, int si=-1)
void CreateSubControlVolumeFaceDomain (TDomain &domOut, const TDomain &domIn, const SurfaceView &surfView, int si=-1)
void CreateSubsetGroups (std::vector< SubsetGroup > &vSSGrp, SubsetGroup &unionSSGrp, std::vector< TElemIn * > vElemDisc, ConstSmartPtr< ISubsetHandler > pSH)
IExternalSolverImplementation * CreateSuperLUImplementation (SuperLUConfiguration &config)
bool CreateSurfaceIndexLayout (IndexLayout &layoutOut, DoFDistribution &dofDistr, GridLayoutMap &layoutMap, int keyType, MultiGrid &mg, DistributedGridManager &dGrMgr)
void CreateSurfaceView (TSurfaceView &surfaceViewOut, DistributedGridManager &distGridMgr, MultiGridSubsetHandler &mgsh)
void CreateSurfaceView (TSurfaceView &surfaceViewOut, MultiGrid &mg, MGSubsetHandler &mgsh)
bool CreateSweepLineStructs (vector< SweepLineVertex > &vrtsOut, SweepLineEdgeList &edgesOut, const vector< vector2 > &vrtsIn, const vector< int > &edgesIn)
static Tetrahedron * CreateTetrahedron (Grid &grid, vector< Triangle * > &vTris, Grid::VertexAttachmentAccessor< APosition > &aaPos)
void CreateTKD (const TKDInfo &tkdInfo, Grid &g, APosition3 &aPos, Volume **volsOut=NULL)
void CreateTKDVertices (const TKDInfo &tkdInfo, Grid &g, APosition3 &aPos, Vertex **vrtsOut)
void CreateTKDWithOuterLayer (const TKDInfo &tkdInfo, Grid &g, APosition3 &aPos, Volume **volsOut=NULL)
void CreateUnionOfFunctionGroups (FunctionGroup &fctGrp, const std::vector< const FunctionGroup * > &vFctGrp, bool sortFct=false)
void CreateUnionOfFunctionGroups (FunctionGroup &fctGrp, const vector< const FunctionGroup * > &vFctGrp, bool sortFct)
static void CreateVolumesFromElementIndexList (Grid &g, const int *elemIndexList, int numElements, Vertex *const *vrts, Volume **volsOut=NULL)
static void CreateVolumesFromElementIndexList (vector< Volume * > &volsOut, int *elemIndexList, int elemIndexListSize, Vertex **vrts)
void CRKing (std::vector< size_t > &newIndex, std::vector< std::vector< size_t > > &vvConnection, size_t dim, size_t minpind, bool bReverse, bool bseparate, bool orderp, bool orderv)
orders the dof distribution using King
void CRMinimumDegree (std::vector< size_t > &newIndex, std::vector< std::vector< size_t > > &vvConnection, size_t dim, size_t minpind, bool bseparate, bool orderp, bool orderv)
orders the dof distribution using minimum degree algorithm
template<typename TDomain , typename TGridFunction >
void CROrderCuthillMcKee (ApproximationSpace< TDomain > &approxSpace, TGridFunction &u, bool bReverse, bool bseparate, bool orderp, bool orderv)
orders the all DofDistributions of the ApproximationSpace using Cuthill-McKee
template<typename TDomain , typename TGridFunction >
void CROrderKing (ApproximationSpace< TDomain > &approxSpace, TGridFunction &u, bool bReverse, bool bseparate, bool orderp, bool orderv)
orders the all DofDistributions of the ApproximationSpace using Cuthill-McKee
template<typename TDomain , typename TGridFunction >
void CROrderMinimumDegree (ApproximationSpace< TDomain > &approxSpace, TGridFunction &u, bool bseparate, bool orderp, bool orderv)
orders the all DofDistributions of the ApproximationSpace using minimum degree algorithm
template<typename TDomain , typename TGridFunction >
void CROrderSloan (ApproximationSpace< TDomain > &approxSpace, TGridFunction &u, bool bseparate, bool orderp, bool orderv)
orders the all DofDistributions of the ApproximationSpace using Sloan
void CRSloan (std::vector< size_t > &newIndex, std::vector< std::vector< size_t > > &vvConnection, size_t dim, size_t minpind, bool bseparate, bool orderp, bool orderv)
orders the dof distribution using Sloan
T CUDA_GetElementFromDevice (T *p, size_t i=0)
void CudaCheckStatus (T status, const char *file, int line)
void CudaCpyToDevice (typename T::value_type *dest, T &vec)
void CudaCpyToHost (T &dest, typename T::value_type *src)
T::value_type * CudaCreateAndCopyToDevice (T &vec)
const char * CUDAError (int err)
std::string CurrentWorkingDirectory ()
bool CutEdgesWithPlane (Selector &sel, const vector3 &p, const vector3 &n, APosition &aPos=aPosition)
std::string cutString (double d, size_t width)
double dabs (double a)
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< bool >, "bool")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< byte >, "byte")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< char >, "char")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< double >, "double")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< float >, "float")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< int >, "int")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< NeuriteProjector::Mapping >, "Mapping")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< NeuriteProjector::SurfaceParams >, "NeuriteProjectorSurfaceParams")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< uint >, "uint")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< vector1 >, "vector1")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< vector2 >, "vector2")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< vector3 >, "vector3")
DECLARE_ATTACHMENT_INFO_TRAITS (Attachment< vector4 >, "vector4")
bool Decomp (DenseMatrix< VariableArray2< double > > &A, DenseVector< VariableArray1< double > > &rhs, size_t &iNonNullRows, double deficitTolerance)
bool Decomp (DenseMatrix< VariableArray2< double > > &A, DenseVector< VariableArray1< double > > &rhs, size_t &iNonNullRows, std::vector< size_t > &xinterchange, double deficitTolerance)
TNumber deg_to_rad (TNumber deg)
static void DelaunayDebugSave (Grid &g, const char *msg, DelaunayInfo< TAAPos > &dinfo)
static bool DelaunayLineLineIntersection (vector3 &vOut, const vector3 &lineFrom, const vector3 &lineTo, const vector3 &edgeVrt1, const vector3 &edgeVrt2, vector3 areaNormal, number smallsq=SMALL_SQ)
string demangle (const char *str)
string demangle_block (const char *str)
void DeselectBoundarySelectionEdges (TSelector &sel)
template void DeselectBoundarySelectionEdges< MGSelector > (MGSelector &)
template void DeselectBoundarySelectionEdges< Selector > (Selector &)
void DeselectBoundarySelectionFaces (TSelector &sel)
template void DeselectBoundarySelectionFaces< MGSelector > (MGSelector &)
template void DeselectBoundarySelectionFaces< Selector > (Selector &)
void DeselectBoundarySelectionVertices (TSelector &sel)
template void DeselectBoundarySelectionVertices< MGSelector > (MGSelector &)
template void DeselectBoundarySelectionVertices< Selector > (Selector &)
static void DeselectFamily (ISelector &sel, MultiGrid &mg, Edge *elem)
static void DeselectFamily (ISelector &sel, MultiGrid &mg, Face *elem)
static void DeselectFamily (ISelector &sel, MultiGrid &mg, GridObject *elem)
static void DeselectFamily (ISelector &sel, MultiGrid &mg, Vertex *elem)
static void DeselectFamily (ISelector &sel, MultiGrid &mg, Volume *elem)
void Deserialize (std::istream &buff, const DenseMatrix< VariableArray2< T > > &mat)
void Deserialize (std::istream &buff, DenseVector< FixedArray1< number, n > > &vec)
void Deserialize (std::istream &buff, DenseVector< VariableArray1< double > > &vec)
void Deserialize (TIStream &buf, IndexLayout &layout)
void Deserialize (TIStream &buf, IndexLayout::Interface &interface)
void Deserialize (TIStream &buf, ParallelVector< T > &v)
void Deserialize (TIStream &buf, pcl::InterfaceCommunicator< IndexLayout > &ic)
void Deserialize (TIStream &buf, pcl::ProcessCommunicator &ic)
void Deserialize (TIStream &buf, std::map< Key, T > &m)
void Deserialize (TIStream &buf, std::pair< T1, T2 > &v)
void Deserialize (TIStream &buf, std::set< T > &myset)
void Deserialize (TIStream &buf, std::string &str)
void Deserialize (TIStream &buf, std::vector< bool > &vec)
void Deserialize (TIStream &buf, std::vector< bool >::reference boolRef)
void Deserialize (TIStream &buf, std::vector< T > &vec)
void Deserialize (TIStream &buf, Variant &v)
void Deserialize (TIStream &buf, Vector< TValueType > &v)
T Deserialize (TIStream &stream)
void Deserialize (TStream &buf, const T &valOut)
void Deserialize (TStream &buf, T &valOut)
void Deserialize (TStream &out, MathVector< N, T > &valOut)
void DeserializeAndAddGlobalInterface (BinaryBuffer &stream, std::vector< AlgebraID > &interface)
void DeserializeAndAddGlobalLayout (BinaryBuffer &stream, GlobalLayout &globalLayout)
bool DeserializeAttachment (Grid &grid, TAttachment &attachment, BinaryBuffer &in)
bool DeserializeAttachment (Grid &grid, TAttachment &attachment, typename geometry_traits< TElem >::iterator iterBegin, typename geometry_traits< TElem >::iterator iterEnd, BinaryBuffer &in)
bool DeserializeGridElements (Grid &grid, BinaryBuffer &in, bool readGridHeader=true)
void DeserializeInterface (BinaryBuffer &stream, IndexLayout::Interface &interface, const TGlobalToLocal &globalToLocal)
void DeserializeLayout (BinaryBuffer &stream, IndexLayout &layout, const TGlobalToLocal &globalToLocal)
void DeserializeMatrix (TIStream &buf, TSparseMatrix &A)
bool DeserializeMultiGridElements (MultiGrid &mg, BinaryBuffer &in, std::vector< Vertex * > *pvVrts=NULL, std::vector< Edge * > *pvEdges=NULL, std::vector< Face * > *pvFaces=NULL, std::vector< Volume * > *pvVols=NULL, MultiElementAttachmentAccessor< AGeomObjID > *paaID=NULL)
void DeserializeParallelData (TIStream &buf, T &t, IndexLayout &masterLayout, IndexLayout &slaveLayout, pcl::InterfaceCommunicator< IndexLayout > &ic, pcl::ProcessCommunicator &pc)
void DeserializeProjectionHandler (BinaryBuffer &in, ProjectionHandler &ph)
SPRefinementProjector DeserializeProjector (BinaryBuffer &in)
size_t DeserializeRow (BinaryBuffer &stream, stdvector< TConnectionType > &cons, ParallelNodes &PN)
bool DeserializeSelector (Grid &grid, ISelector &sel, BinaryBuffer &in)
bool DeserializeSelector (Grid &grid, ISelector &sel, GridObjectCollection goc, BinaryBuffer &in)
bool DeserializeSubsetHandler (Grid &grid, ISubsetHandler &sh, BinaryBuffer &in, bool readPropertyMap=true)
bool DeserializeSubsetHandler (Grid &grid, ISubsetHandler &sh, GridObjectCollection goc, BinaryBuffer &in, bool readPropertyMap=true)
void DeserializeUniquePart (TIStream &buf, ParallelMatrix< T > &A)
void DeserializeUniquePart (TIStream &buf, ParallelVector< TValueType > &v)
MathMatrix< 0, 0, T >::value_type Determinant (const MathMatrix< 0, 0, T > &m)
MathMatrix< 1, 1, T >::value_type Determinant (const MathMatrix< 1, 1, T > &m)
MathMatrix< 2, 2, T >::value_type Determinant (const MathMatrix< 2, 2, T > &m)
MathMatrix< 3, 3, T >::value_type Determinant (const MathMatrix< 3, 3, T > &m)
MathMatrix< 4, 4, T >::value_type Determinant (const MathMatrix< 4, 4, T > &m)
MathMatrix< N, N, T >::value_type Determinant (const MathMatrix< N, N, T > &m)
void dgetrf_ (lapack_int *m, lapack_int *n, lapack_double *pColMajorMatrix, lapack_int *lda, lapack_int *ipiv, lapack_int *info)
void dgetri_ (lapack_int *n, lapack_double *pColMajorMatrix, lapack_int *lda, const lapack_int *ipiv, lapack_double *pWork, lapack_int *worksize, lapack_int *info)
void dgetrs_ (char *trans, lapack_int *n, lapack_int *nrhs, const lapack_double *pColMajorMatrix, lapack_int *lda, const lapack_int *ipiv, lapack_double *b, lapack_int *ldb, lapack_int *info)
void diag_step (const Matrix_type &A, Vector_type &c, const Vector_type &d, number damp)
bool Diag_Vanka_step (const Matrix_type &A, Vector_type &x, const Vector_type &b, number relax)
int DimensionOfSubset (const ISubsetHandler &sh, int si)
int DimensionOfSubsets (const ISubsetHandler &sh)
UG_API bool DirectoryExists (const char *dirname)
static bool DirectoryExists (std::string filename)
void DisplayVacantMemory ()
number DistanceLineToLine (const vector3 &a1, const vector3 &a2, const vector3 &b1, const vector3 &b2)
number DistancePointToLine (const vector_t &v, const vector_t &v1, const vector_t &v2)
number DistancePointToLine (number &tOut, const vector_t &v, const vector_t &v1, const vector_t &v2)
number DistancePointToPlane (const vector_t &v, const vector_t &p, const vector_t &n)
number DistancePointToRay (const vector_t &v, const vector_t &from, const vector_t &dir)
number DistancePointToRay (number &tOut, const vector_t &v, const vector_t &from, const vector_t &dir)
number DistancePointToRay (vector_t &vOut, number &tOut, const vector_t &v, const vector_t &from, const vector_t &dir)
number DistancePointToTriangle (vector_t &vOut, number &bc1Out, number &bc2Out, const vector_t &p, const vector_t &v1, const vector_t &v2, const vector_t &v3, const vector_t &n)
static bool DistributeDomain (TDomain &domainOut, PartitionMap &partitionMap, bool createVerticalInterfaces)
static void DistributeExpansionMarks3D (Grid &grid, SubsetHandler &sh, Selector &sel, const vector< FractureInfo > &fracInfos, bool expandInnerFracBnds, bool expandOuterFracBnds, Grid::VertexAttachmentAccessor< AInt > &aaMarkVRT, Grid::EdgeAttachmentAccessor< AInt > &aaMarkEDGE, Grid::FaceAttachmentAccessor< AInt > &aaMarkFACE)
bool DistributeGrid (MultiGrid &mg, SubsetHandler &shPartition, GridDataSerializationHandler &serializer, bool createVerticalInterfaces, const std::vector< int > *processMap=NULL, const pcl::ProcessCommunicator &procComm=pcl::ProcessCommunicator())
std::string DistributionPercentage (std::vector< double > values)
bool DoFPosition (std::vector< MathVector< dim > > &vPos, const ReferenceObjectID roid, const std::vector< MathVector< dim > > &vCornerCoord, const LFEID &lfeID)
bool DoFPosition (std::vector< MathVector< TDomain::dim > > &vPos, GridObject *elem, const TDomain &domain, const LFEID &lfeID)
bool DoFPositionElem (std::vector< MathVector< dim > > &vPos, const ReferenceObjectID roid, const std::vector< MathVector< dim > > &vVertPos, const LFEID &lfeID)
bool DoFPositionVertex (std::vector< MathVector< dim > > &vPos, const ReferenceObjectID roid, const std::vector< MathVector< dim > > &vVertPos, const LFEID &lfeID)
const number & DoFRef (const TMatrix &mat, const DoFIndex &iInd, const DoFIndex &jInd)
const number & DoFRef (const TVector &vec, const DoFIndex &ind)
number & DoFRef (TMatrix &mat, const DoFIndex &iInd, const DoFIndex &jInd)
number & DoFRef (TVector &vec, const DoFIndex &ind)
TTo & DownCast (const TTo &pfrom, const TFrom &p)
TTo & DownCast (const TTo &pfrom, TFrom &p)
template<typename TGridFunction >
std::vector< number > DragLift (SmartPtr< TGridFunction > spGridFct, const char *vCmp, const char *BndSubsets, const char *InnerSubsets, number kinVisco, number density, int quadOrder)
template<typename TGridFunction >
void DrivenCavityEvalAtPoints (const std::vector< MathVector< 2 > > &vPos, GlobalGridFunctionNumberData< TGridFunction > &GFEval, const number vReferenceValue[])
template<typename TGridFunction >
void DrivenCavityLinesEval (SmartPtr< TGridFunction > u, std::vector< std::string > vVelCmp, size_t Re)
number DropAPerpendicular (vector_t &vOut, const vector_t &v, const vector_t &v0, const vector_t &v1)
bool Duplicate (Grid &grid, Selector &sel, const typename TAPos::ValueType &offset, TAPos &aPos, bool deselectOld=true, bool selectNew=true)
bool EdgeCollapseIsValid (Grid &grid, Edge *e)
bool EdgeContains (EdgeVertices *e, Vertex *vrt)
bool EdgeContains (EdgeVertices *e, Vertex *vrt1, Vertex *vrt2)
bool EdgeExists (SweepLineVertex *v0, SweepLineVertex *v1)
UG_API number EdgeLength (const EdgeVertices *e, TAAPosVRT &aaPos)
UG_API number EdgeLengthSq (const EdgeVertices *e, TAAPosVRT &aaPos)
bool EdgeOrientationMatches (EdgeVertices *ev, Face *f)
void EdgeReferenceMappingTest (std::vector< number > vCornerCoord0, std::vector< number > vCornerCoord1, std::vector< number > vGlobPos)
std::string ElementDebugInfo (const Grid &grid, GridObject *e)
static std::string ElementDebugInfo_IMPL (const Grid &grid, TElem *e)
number ElementDiameter (const TElem &elem, TDomain &domain)
number ElementDiameter (Grid &grid, TAAPos &aaPos, TElem *elem)
number ElementDiameter (TElem &elem, TDomain &domain)
number ElementDiameterSq (const TElem &elem, TDomain &domain)
number ElementDiameterSq (Grid &grid, TAAPos &aaPos, GridObject *elem)
number ElementDiameterSq (Grid &grid, TAAPos &aaPos, TElem *elem)
number ElementDiameterSq (TElem &elem, TDomain &domain)
void ElementExtensionsSq (ReferenceObjectID roid, MathVector< dim > &ext, const MathVector< dim > *vCornerCoords)
void ElementExtensionsSq< 1 > (ReferenceObjectID roid, MathVector< 1 > &ext, const MathVector< 1 > *vCornerCoords)
void ElementExtensionsSq< 2 > (ReferenceObjectID roid, MathVector< 2 > &ext, const MathVector< 2 > *vCornerCoords)
void ElementExtensionsSq< 3 > (ReferenceObjectID roid, MathVector< 3 > &ext, const MathVector< 3 > *vCornerCoords)
void ElementGaussSeidelStep (const typename TAlgebra::matrix_type &A, GridFunction< TDomain, TAlgebra > &c, const typename TAlgebra::vector_type &d, number relax, const std::vector< std::string > &cmp, number alpha, bool elim_off_diag=false)
void ElementNormal (MathVector< TWorldDim > &normalOut, const MathVector< TWorldDim > *vCornerCoords)
void ElementNormal (ReferenceObjectID roid, MathVector< dim > &normalOut, const MathVector< dim > *vCornerCoords)
void ElementNormal< 1 > (ReferenceObjectID roid, MathVector< 1 > &normalOut, const MathVector< 1 > *vCornerCoords)
void ElementNormal< 2 > (ReferenceObjectID roid, MathVector< 2 > &normalOut, const MathVector< 2 > *vCornerCoords)
void ElementNormal< 3 > (ReferenceObjectID roid, MathVector< 3 > &normalOut, const MathVector< 3 > *vCornerCoords)
void ElementNormal< ReferenceEdge, 2 > (MathVector< 2 > &normalOut, const MathVector< 2 > *vCornerCoords)
void ElementNormal< ReferenceEdge, 3 > (MathVector< 3 > &normalOut, const MathVector< 3 > *vCornerCoords)
void ElementNormal< ReferenceQuadrilateral, 3 > (MathVector< 3 > &normalOut, const MathVector< 3 > *vCornerCoords)
void ElementNormal< ReferenceTriangle, 3 > (MathVector< 3 > &normalOut, const MathVector< 3 > *vCornerCoords)
void ElementNormal< ReferenceVertex, 1 > (MathVector< 1 > &normalOut, const MathVector< 1 > *vCornerCoords)
void ElementNormal< ReferenceVertex, 2 > (MathVector< 2 > &normalOut, const MathVector< 2 > *vCornerCoords)
void ElementNormal< ReferenceVertex, 3 > (MathVector< 3 > &normalOut, const MathVector< 3 > *vCornerCoords)
void ElementQualityStatistics (Grid &grid, int dim)
void ElementQualityStatistics (Grid &grid, int dim, number angleHistStepSize, number aspectRatioHistStepSize, bool bWriteHistograms)
void ElementQualityStatistics (MultiGrid &mg, int dim)
void ElementQualityStatistics (MultiGrid &mg, int dim, number angleHistStepSize, number aspectRatioHistStepSize, bool bWriteHistograms)
void ElementQualityStatistics2d (Grid &grid, GridObjectCollection goc, number angleHistStepSize, number aspectRatioHistStepSize, bool bWriteHistograms)
void ElementQualityStatistics3d (Grid &grid, GridObjectCollection goc, number angleHistStepSize, number aspectRatioHistStepSize, bool bWriteHistograms)
bool ElementSideRayIntersection (size_t &sideOut, MathVector< TWorldDim > &GlobalIntersectionPointOut, MathVector< TRefElem::dim > &LocalIntersectionPoint, const MathVector< TWorldDim > &From, const MathVector< TWorldDim > &Direction, bool bPositiv, const MathVector< TWorldDim > *vCornerCoords)
number ElementSize (const MathVector< TWorldDim > *vCornerCoords)
number ElementSize (const TElem &elem, const Grid::VertexAttachmentAccessor< Attachment< TPosition > > &aaPos)
number ElementSize (const TElem &elem, const TDomain &domain)
number ElementSize (ReferenceObjectID roid, const MathVector< dim > *vCornerCoords)
number ElementSize< 1 > (ReferenceObjectID roid, const MathVector< 1 > *vCornerCoords)
number ElementSize< 2 > (ReferenceObjectID roid, const MathVector< 2 > *vCornerCoords)
number ElementSize< 3 > (ReferenceObjectID roid, const MathVector< 3 > *vCornerCoords)
number ElementSize< ReferenceEdge, 1 > (const MathVector< 1 > *vCornerCoords)
number ElementSize< ReferenceEdge, 2 > (const MathVector< 2 > *vCornerCoords)
number ElementSize< ReferenceEdge, 3 > (const MathVector< 3 > *vCornerCoords)
number ElementSize< ReferenceHexahedron, 3 > (const MathVector< 3 > *vCornerCoords)
number ElementSize< ReferenceOctahedron, 3 > (const MathVector< 3 > *vCornerCoords)
number ElementSize< ReferencePrism, 3 > (const MathVector< 3 > *vCornerCoords)
number ElementSize< ReferencePyramid, 3 > (const MathVector< 3 > *vCornerCoords)
number ElementSize< ReferenceQuadrilateral, 2 > (const MathVector< 2 > *vCornerCoords)
number ElementSize< ReferenceQuadrilateral, 3 > (const MathVector< 3 > *vCornerCoords)
number ElementSize< ReferenceTetrahedron, 3 > (const MathVector< 3 > *vCornerCoords)
number ElementSize< ReferenceTriangle, 2 > (const MathVector< 2 > *vCornerCoords)
number ElementSize< ReferenceTriangle, 3 > (const MathVector< 3 > *vCornerCoords)
bool EliminateInvalidCells (Field< T > &field, const T &noDataValue)
static void EnableDelaunayDebugSave (bool enable=true)
bool EnableMemTracker (bool b)
double EnergyNorm (vector_type &x, matrix_type &A)
double EnergyNorm (vector_type &x, matrix_type &A, vector_type &tmp)
double EnergyProd (const T1 &v1, const DenseMatrix< T2 > &M, const T1 &v2)
double EnergyProd (double v1, double M, double v2)
double EnergyProd (vector_type &v1, matrix_type &A, vector_type &v2)
double EnergyProd (vector_type &v1, matrix_type &A, vector_type &v2, vector_type &tmp)
std::string EntryToString (const Table< std::string > &table, size_t rowInd, size_t colInd)
std::string EntryToString (const Table< std::stringstream > &table, size_t rowInd, size_t colInd)
std::string EntryToString (const Table< T > &table, size_t rowInd, size_t colInd)
void EraseConnectingElements (Grid &grid, Vertex *v1, Vertex *v2)
UG_API void EraseElements (Grid &grid, typename geometry_traits< TElem >::iterator iterBegin, typename geometry_traits< TElem >::iterator iterEnd)
void EraseEmptySubsets (ISubsetHandler &sh)
void EraseSelectedObjects (TSelector &sel)
template void EraseSelectedObjects< MGSelector > (MGSelector &)
template void EraseSelectedObjects< Selector > (Selector &)
std::string ErrorStringFromStdException (const std::exception *pex)
void EvaluateGradientJump_Norm (TFunction &u, size_t fct, MultiGrid::AttachmentAccessor< typename TFunction::element_type, ug::Attachment< number > > &aaError)
void EvaluateGradientJump_SideIntegral (TFunction &u, size_t fct, MultiGrid::AttachmentAccessor< typename TFunction::element_type, ug::Attachment< number > > &aaError, bool addErrSquareToAAError=false)
void EvaluateResidualErrorP1 (SmartPtr< TFunction > u, SmartPtr< UserData< number, TFunction::dim > > f, const char *cmp, number time, int quadOrder, std::string quadType, MultiGrid::AttachmentAccessor< typename TFunction::element_type, ug::Attachment< number > > &aaError)
void ExchangeAndAdjustSideErrors (TFunction &u, ANumber aSideError, ANumber aNumElems)
bool ExpandFractures2d (Grid &grid, SubsetHandler &sh, const std::vector< FractureInfo > &fracInfos, bool expandInnerFracBnds, bool expandOuterFracBnds)
bool ExpandFractures2d (Grid &grid, SubsetHandler &sh, const vector< FractureInfo > &fracInfos, bool expandInnerFracBnds, bool expandOuterFracBnds)
bool ExpandFractures3d (Grid &grid, SubsetHandler &sh, const std::vector< FractureInfo > &fracInfos, bool expandInnerFracBnds, bool expandOuterFracBnds)
bool ExpandFractures3d (Grid &grid, SubsetHandler &sh, const vector< FractureInfo > &fracInfos, bool expandInnerFracBnds, bool expandOuterFracBnds)
bool ExportGridToSMESH (Grid &grid, const char *filename, AVector3 &aPos, ISubsetHandler *psh=NULL, std::vector< AFloat > *pvNodeAttributes=NULL, std::vector< vector3 > *pvHoles=NULL, std::vector< vector3 > *pvRegionPositions=NULL, std::vector< int > *pvRegionAttributes=NULL, std::vector< float > *pvRegionVolumeConstraints=NULL)
bool ExportGridToSMESH (Grid &grid, const char *filename, AVector3 &aPos, std::vector< AFloat > *pvNodeAttributes=NULL, AInt *paNodeBoundaryMarker=NULL, AInt *paFaceBoundaryMarker=NULL, std::vector< vector3 > *pvHoles=NULL, std::vector< vector3 > *pvRegionPositions=NULL, std::vector< int > *pvRegionAttributes=NULL, std::vector< float > *pvRegionVolumeConstraints=NULL)
bool ExportGridToSWC (Grid &g, ISubsetHandler *pSH, const char *fileName, AVector3 &aPos)
bool ExportGridToTETGEN (Grid &grid, const char *filename, AVector3 &aPos, std::vector< AFloat > *pvNodeAttributes, AInt *paNodeBoundaryMarker, AInt *paFaceBoundaryMarker, AInt *paElementAttribute, ANumber *paVolumeConstraint)
bool ExportGridToTIKZ (Grid &grid, const char *filename, const ISubsetHandler *psh, APosition aPos, TikzExportDesc desc)
bool ExportGridToUG (const Grid &g, const SubsetHandler &shFace, const SubsetHandler &shVolume, const char *fileNamePrefix, const char *lgmName, const char *problemName, int convex)
bool ExportGridToUG_2D (Grid &grid, const char *fileName, const char *lgmName, const char *problemName, int convex, SubsetHandler *psh=NULL)
void ExtendSelection (TSelector &sel, size_t extSize, ISelector::status_t status)
template void ExtendSelection< MGSelector > (MGSelector &sel, size_t extSize, ISelector::status_t status)
template void ExtendSelection< Selector > (Selector &sel, size_t extSize, ISelector::status_t status)
void ExtendSelectionInDirection (TSelector &sel, size_t extSize, const typename TAAPos::ValueType &dir, number minAngle, number maxAngle, const TAAPos &aaPos, ISelector::status_t status)
void extract_by_grouping (std::vector< std::vector< DoFIndex > > &vvDoFIndex, const GF &c, const std::vector< size_t > &vFullRowCmp, const std::vector< size_t > &vRemainCmp)
string extract_path (const string &filename)
void ExtractAlgebraIndices (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, std::vector< size_t > &fctIndex)
void ExtractAlgebraIndices2 (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, std::vector< size_t > &fctIndex)
void ExtractByObject (std::vector< DoFIndex > &vIndex, const TGridFunction &c, const std::vector< size_t > &vFullRowCmp, const std::vector< size_t > &vRemainCmp)
template<class TGraph >
void extractPGraph (TGraph &G, std::vector< std::vector< size_t > > &vvConnection, size_t pmin, size_t dim, bool directed)
void ExtractPositions (const TFunction &u, std::vector< MathVector< TFunction::domain_type::dim > > &vPos)
void ExtractPositions (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, const size_t fct, std::vector< std::pair< MathVector< TDomain::dim >, size_t > > &vPosPair)
void ExtractPositions (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, std::vector< MathVector< TDomain::dim > > &vPos)
void ExtractPositions (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, std::vector< std::pair< MathVector< TDomain::dim >, size_t > > &vPosPair)
void ExtractPositionsElem (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, const size_t fct, std::vector< std::pair< MathVector< TDomain::dim >, size_t > > &vPosPair)
void ExtractPositionsElem (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, std::vector< MathVector< TDomain::dim > > &vPos)
void ExtractPositionsElem (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, std::vector< std::pair< MathVector< TDomain::dim >, size_t > > &vPosPair)
void ExtractPositionsVertex (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, std::vector< MathVector< TDomain::dim > > &vPos)
void ExtractPositionsVertex (ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd, std::vector< std::pair< MathVector< TDomain::dim >, size_t > > &vPosPair)
template<class TGraph >
void extractVGraph (TGraph &G, std::vector< std::vector< size_t > > &vvConnection, size_t pmin, size_t dim, bool directed)
void Extrude (Grid &grid, std::vector< Vertex * > *pvVerticesInOut, std::vector< Edge * > *pvEdgesInOut, std::vector< Face * > *pvFacesInOut, const typename TAAPos::ValueType &direction, TAAPos aaPos, uint extrusionOptions, std::vector< Volume * > *pvVolsOut)
void Extrude (Grid &grid, std::vector< Vertex * > *pvVerticesInOut, std::vector< Edge * > *pvEdgesInOut, std::vector< Face * > *pvFacesInOut, const vector_t &direction, uint extrusionOptions=EO_DEFAULT, Attachment< vector_t > &aPos=aPosition, std::vector< Volume * > *pvVolsOut=NULL)
template void Extrude< Grid::VertexAttachmentAccessor< Attachment< vector1 > > > (Grid &, std::vector< Vertex * > *, std::vector< Edge * > *, std::vector< Face * > *, const vector1 &, Grid::VertexAttachmentAccessor< Attachment< vector1 > >, uint, std::vector< Volume * > *)
template void Extrude< Grid::VertexAttachmentAccessor< Attachment< vector2 > > > (Grid &, std::vector< Vertex * > *, std::vector< Edge * > *, std::vector< Face * > *, const vector2 &, Grid::VertexAttachmentAccessor< Attachment< vector2 > >, uint, std::vector< Volume * > *)
template void Extrude< Grid::VertexAttachmentAccessor< Attachment< vector3 > > > (Grid &, std::vector< Vertex * > *, std::vector< Edge * > *, std::vector< Face * > *, const vector3 &, Grid::VertexAttachmentAccessor< Attachment< vector3 > >, uint, std::vector< Volume * > *)
template void Extrude< vector1 > (Grid &, std::vector< Vertex * > *, std::vector< Edge * > *, std::vector< Face * > *, const vector1 &, uint, Attachment< vector1 > &, std::vector< Volume * > *)
template void Extrude< vector2 > (Grid &, std::vector< Vertex * > *, std::vector< Edge * > *, std::vector< Face * > *, const vector2 &, uint, Attachment< vector2 > &, std::vector< Volume * > *)
template void Extrude< vector3 > (Grid &, std::vector< Vertex * > *, std::vector< Edge * > *, std::vector< Face * > *, const vector3 &, uint, Attachment< vector3 > &, std::vector< Volume * > *)
bool ExtrudeCylinder (Grid &grid, SubsetHandler &sh, Vertex *vrt, const vector3 &direction, number height, number radius, number rimSnapThreshold, Grid::VertexAttachmentAccessor< APosition > &aaPos, int bottomSubInd=-1, int cylSubInd=-1, Selector *pSel=NULL)
static bool ExtrudeCylinder (Grid &grid, SubsetHandler *sh, Vertex *vrt, const vector3 &direction, number height, number radius, number rimSnapThreshold, Grid::VertexAttachmentAccessor< APosition > &aaPos, int bottomSubInd, int cylSubInd, Selector *pSel)
bool ExtrudeCylinder (Grid &grid, Vertex *vrt, const vector3 &direction, number height, number radius, number rimSnapThreshold, Grid::VertexAttachmentAccessor< APosition > &aaPos, Selector *pSel=NULL)
void ExtrudeLayers (Grid &grid, const RasterLayers &layers, Grid::VertexAttachmentAccessor< AVector3 > aaPos, ISubsetHandler &sh, bool allowForTetsAndPyras, const ANumber *aRelZOut)
void ExtrudeLayersMixed (Grid &grid, const RasterLayers &layers, Grid::VertexAttachmentAccessor< AVector3 > aaPos, ISubsetHandler &sh, const ANumber *aRelZOut)
static bool ExtrusionHelper_CheckOrientation (Volume *v, Grid::VertexAttachmentAccessor< Attachment< vector1 > > &aaPos)
static bool ExtrusionHelper_CheckOrientation (Volume *v, Grid::VertexAttachmentAccessor< Attachment< vector2 > > &aaPos)
static bool ExtrusionHelper_CheckOrientation (Volume *v, Grid::VertexAttachmentAccessor< Attachment< vector3 > > &aaPos)
UG_API number FaceArea (FaceVertices *f, TAAPosVRT &aaPos)
UG_API number FaceArea (ISelector &sel, TAAPosVRT &aaPos)
UG_API number FaceArea (ISubsetHandler &sh, int si, size_t lvl, TAAPosVRT &aaPos)
static number FaceArea (TDomain &dom, int si)
static number FaceArea (TDomain &dom, int si, size_t lvl)
static number FaceArea (TDomain &dom, ISelector &sel)
static number FaceArea (TDomain &dom, ISubsetHandler &sh, int si, size_t lvl)
UG_API number FaceArea (TIterator facesBegin, TIterator facesEnd, TAAPosVRT &aaPos)
bool FaceContains (Face *f, EdgeVertices *ev)
bool FaceContains (FaceVertices *f, Vertex *v)
static bool FaceIsOnRightSide (Face *f, Edge *e)
static int FacePlane (const vector3 &p)
number FaceQuality (FaceVertices *f, Grid::VertexAttachmentAccessor< APosition > aaPos)
bool FactorizeILU (Matrix_type &A)
bool FactorizeILUBeta (Matrix_type &A, number beta)
bool FactorizeILUSorted (Matrix_type &A, const number eps=1e-50)
UG_API bool FileCompare (const char *file1, const char *file2)
UG_API bool FileExists (const char *filename)
static bool FileExists (std::string filename)
UG_API std::string FilenameAndPathWithoutExtension (std::string str)
string FilenameAndPathWithoutExtension (string str)
UG_API std::string FilenameWithoutExtension (std::string str)
string FilenameWithoutExtension (string str)
UG_API std::string FilenameWithoutPath (const std::string &str)
string FilenameWithoutPath (const string &str)
UG_API size_t FileSize (const char *filename)
static size_t FileSize (std::string filename)
bool FileTypeIs (const char *filename, const char *extension)
void FillCornerCoordinates (typename TDomain::position_type vCornerCoordsOut[], const RegularVertex &vtx, const TDomain &domain)
void FillCornerCoordinates (typename TDomain::position_type vCornerCoordsOut[], const TElem &elem, const TDomain &domain)
static void FillDistInfos (MultiGrid &mg, SubsetHandler &shPartition, MGSelector &msel, DistInfoSupplier &distInfos, const std::vector< int > *processMap, const pcl::ProcessCommunicator &procComm, bool createVerticalInterfaces, vector< bool > &partitionIsEmpty)
UG_API void FinalizeUGPlugin_Jupyter ()
UG_API void FinalizeUGPlugin_Limex ()
UG_API void FinalizeUGPlugin_Richards ()
IndexLayout::Interface::iterator find (IndexLayout::Interface &interface, size_t i)
TLayout::iterator find_pid (TLayout &layout, int pid)
static size_t findBlockSize (const std::vector< std::vector< size_t > > &vvConnection)
void FindBoundsForStiffnesMatrixMaxEigenvalue (MultiGrid &mg, MGSubsetHandler &shOut)
UG_API TElem * FindClosestByCoordinate (const typename TVertexPositionAttachmentAccessor::ValueType &coord, typename geometry_traits< TElem >::iterator iterBegin, typename geometry_traits< TElem >::iterator iterEnd, TVertexPositionAttachmentAccessor &aaPosVRT)
bool FindClosestPlane (vector3 &centerOut, vector3 &normalOut, const vector3 *pointSet, size_t numPoints)
int FindClosestVertexInArray (const std::vector< Vertex * > &array, const Vertex *p, TAAPosVRT &aaPos, number snapThreshold)
int FindClosestVertexInArray (std::vector< Vertex * > &array, const Vertex *p, TAAPosVRT &aaPos, number snapThreshold)
int FindClosestVertexInPointSet (const vector_t *pointSet, const Vertex *p, TAAPosVRT &aaPos, number snapThreshold, size_t numPoints)
int FindCloseVertexInArray (const std::vector< Vertex * > &array, const typename TAAPosVRT::ValueType &p, TAAPosVRT &aaPos, number snapThreshold)
int FindCloseVertexInArray (std::vector< Vertex * > &array, const typename TAAPosVRT::ValueType &p, TAAPosVRT &aaPos, number snapThreshold)
bool FindContainingElement (typename tree_t::elem_t &elemOut, const tree_t &tree, const typename tree_t::vector_t &point)
std::string FindDirInStandardPaths (const char *dirname)
UG_API std::vector< std::string > FindDuplicates (const std::vector< std::string > &vec)
vector< string > FindDuplicates (const vector< string > &vec)
TIterator FindElementByValue (TIterator begin, TIterator end, const typename TAttAcc::ValueType &val, TAttAcc &aa)
bool FindElementsInIntersectingNodes (std::vector< typename tree_t::elem_t > &elemsOut, const tree_t &tree, const typename tree_t::box_t &bbox)
TIterator::value_type FindElementWithLargestAspectRatio (Grid &grid, TIterator elemsBegin, TIterator elemsEnd, TAAPosVRT &aaPos)
TIterator::value_type FindElementWithLargestMaxAngle (Grid &grid, TIterator elementsBegin, TIterator elementsEnd, TAAPosVRT &aaPos)
TIterator::value_type FindElementWithLargestVolToRMSFaceAreaRatio (Grid &grid, TIterator elemsBegin, TIterator elemsEnd, TAAPosVRT &aaPos)
TIterator::value_type FindElementWithSmallestAspectRatio (Grid &grid, TIterator elemsBegin, TIterator elemsEnd, TAAPosVRT &aaPos)
TIterator::value_type FindElementWithSmallestMinAngle (Grid &grid, TIterator elementsBegin, TIterator elementsEnd, TAAPosVRT &aaPos)
TIterator::value_type FindElementWithSmallestVolToRMSFaceAreaRatio (Grid &grid, TIterator elemsBegin, TIterator elemsEnd, TAAPosVRT &aaPos)
std::string FindFileInStandardPaths (const char *filename)
Face * FindLargestFace (TIterator facesBegin, TIterator facesEnd, TAAPosVRT &aaPos)
TIterator::value_type FindLargestVolume (TIterator volumesBegin, TIterator volumesEnd, TAAPosVRT &aaPos)
Edge * FindLongestEdge (TEdgeIterator edgesBegin, TEdgeIterator edgesEnd, TAAPosVRT &aaPos)
size_t FindLowestLeafNodeLevel (const tree_t &tree)
bool FindNormal (vector3 &normOut, const vector3 &v)
bool FindParam (const char *param, int argc, const char *const *argv)
void FindPositionInInterfaces (std::vector< std::pair< int, size_t > > &vIndexInterface, const IndexLayout &layout, size_t index)
UG_API Edge * FindShortestEdge (TEdgeIterator edgesBegin, TEdgeIterator edgesEnd, TAAPosVRT &aaPos)
size_t FindSlivers (std::vector< typename TIter::value_type > &sliversOut, TIter elemsBegin, TIter elemsEnd, number thresholdRatio, TAAPos aaPos, bool clearContainer=true)
UG_API Face * FindSmallestFace (TIterator facesBegin, TIterator facesEnd, TAAPosVRT &aaPos)
TIterator::value_type FindSmallestVolume (TIterator volumesBegin, TIterator volumesEnd, TAAPosVRT &aaPos)
void FindSubsetGroups (std::vector< int > &minCondInd, const std::vector< bool > &isMarked, const ISubsetHandler &sh, const NeighborhoodType nbhType=NHT_VERTEX_NEIGHBORS)
Vertex * FindVertexByCoordiante (vector3 &coord, VertexIterator iterBegin, VertexIterator iterEnd, Grid::VertexAttachmentAccessor< APosition > &aaPos)
int FindVertexByCoordinate (const MathVector< dim > &coord, size_t ncoords, const MathVector< dim > vCoords[])
void FinishShinyCallLogging ()
UG_API void FixEdgeOrientation (Grid &grid, TEdgeIterator edgesBegin, TEdgeIterator edgesEnd)
void FixFaceOrientation (Grid &grid, TFaceIterator facesBegin, TFaceIterator facesEnd)
int FixOrientation (Grid &grid, TVolIterator volsBegin, TVolIterator volsEnd, TAAPosVRT &aaPosVRT)
void forward_gs_step (Vector_type &c, const Matrix_type &A, const Vector_type &d, const size_t i, const number relaxFactor)
void GatherGrid (Grid &gridOut, Selector &sel, GridDataSerializationHandler &serializer, GridDataSerializationHandler &deserializer, int root, const pcl::ProcessCommunicator &procCom=pcl::ProcessCommunicator())
void GatherVectorOnOne (HorizontalAlgebraLayouts &agglomerationLayout, ParallelVector< T > &collectedVec, const ParallelVector< T > &vec, ParallelStorageType type)
void GatherVectorOnOne (IndexLayout &agglomeratedMaster, IndexLayout &agglomeratedSlave, pcl::InterfaceCommunicator< IndexLayout > &com, ParallelVector< T > &collectedVec, const ParallelVector< T > &vec, ParallelStorageType type, bool bRoot)
static size_t gcd (size_t a, size_t b)
int GeneralizedEigenvalueProblemComplex (DenseMatrix< A_type > &A, DenseMatrix< A_type > &X, TLambdaVectorType &lambda, DenseMatrix< A_type > &B, bool bSortEigenvalues=false)
void GenerateAlgebraIDHashList (AlgebraIDHashList &hash, AlgebraIDVec &algebraIDs)
void GenerateGlobalAlgebraIDs (pcl::InterfaceCommunicator< TLayout > &communicator, std::vector< AlgebraID > &idsOut, size_t numIDs, const TLayout &masterLayout, const TLayout &slaveLayout)
void GenerateGlobalConsecutiveIndices (TIndVec &indsOut, size_t numLocalInds, const AlgebraLayouts &layouts)
void GenerateIcosahedron (Grid &grid, const vector3 &center, number radius, AVector3 &aPos)
void GenerateIcosphere (Grid &grid, const vector3 &center, number radius, int numRefinements, AVector3 &aPos, Selector *psel=NULL)
void GenerateIcosphere (std::vector< vector3 > &trisOut, const vector3 &center, number radius, size_t refinements)
int GenerateScriptReferenceDocu (const char *baseDir, bool silent, bool genHtml, bool genCpp, bool genList)
void GenVecCross (MathVector< dim > &result, const MathVector< dim > &v_1, const MathVector< dim > &v_2)
void GenVecCross< 2 > (MathVector< 2 > &result, const MathVector< 2 > &v_1, const MathVector< 2 > &v_2)
void GenVecCross< 3 > (MathVector< 3 > &result, const MathVector< 3 > &v_1, const MathVector< 3 > &v_2)
number GeometricApproximationDegree (SimpleGrid &sg)
number GeometricApproximationDegree (SimpleGrid &sg, int triIndex)
number GeometricApproximationDegree (vector_t &n1, vector_t &n2, vector_t &n3, vector_t &tn)
void get_algebra_indices (ConstSmartPtr< DoFDistribution > dd, ConstrainedVertex *hgVrt, std::vector< Vertex * > &vConstrainingVrt, std::vector< size_t > &constrainedInd, std::vector< std::vector< size_t > > &vConstrainingInd)
void get_algebra_indices (ConstSmartPtr< DoFDistribution > dd, ConstrainedVertex *hgVrt, std::vector< Vertex * > &vConstrainingVrt, std::vector< size_t > &constrainedInd, std::vector< std::vector< size_t > > &vConstrainingInd, const SortVertexPos< TDomain::dim > &sortVertexPos)
double get_clock_s ()
template<typename side_type , typename secure_container , typename TGridFunction >
void get_constrained_sides_cr (secure_container &sides, const TGridFunction &u, std::vector< MultiIndex< 2 > > multInd, size_t fct=0)
void * get_mem (size_t size)
number get_number_on_coords (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, typename TGridFunction::domain_type::position_type pos, number time, const int si)
size_t get_val (const T &t)
size_t get_val (size_t i)
void GetAct (string str, vector< size_t > &act)
void GetAspectRatioHistogram (std::vector< int > &histoOut, TElemIter elemsBegin, TElemIter elemsEnd, int histoSecs, TAAPos &aaPos, Grid::AttachmentAccessor< typename PtrToValueType< typename TElemIter::value_type >::base_type, Attachment< int > > *paaHistoSec=NULL)
AspectRatioInfo GetAspectRatioInfo (TElemIter elemsBegin, TElemIter elemsEnd, TAAPos &aaPos)
int GetAssociatedFaces (Face **facesOut, Grid &grid, Edge *e, int maxNumFaces)
int GetAssociatedInterfaceType (int interfaceType)
void GetBlockGSCorrection (const TSparseMatrixType &A, TVectorType &x, TVectorType &b, DenseMatrix< VariableArray2< double > > &AlocInv, std::vector< size_t > &indices)
void GetBlockGSCorrection (const TSparseMatrixType &A, TVectorType &x, TVectorType &b, DenseMatrix< VariableArray2< double > > &AlocInv, std::vector< size_t > &indices, DenseVector< VariableArray1< double > > &tmp, DenseVector< VariableArray1< double > > &tmp2)
void GetBlockGSCorrectionILUT (const TSparseMatrixType &A, TVectorType &x, TVectorType &b, SmartPtr< ILUTPreconditioner< CPUAlgebra > > &ilut, std::vector< size_t > &indices, CPUAlgebra::vector_type &tmp, CPUAlgebra::vector_type &tmp2)
GlobalBoundaryRefinementRule GetBoundaryRefinementRule ()
string GetBytesSizeString (size_t s, int length)
vector3 GetColorFromDefaultPalette (int index)
vector3 GetColorFromStandardPalette (int index)
size_t GetCols (const DenseMatrix< T > &t)
size_t GetCols (const number &t)
size_t GetCols (const T &t)
Edge * GetConnectedEdge (Grid &g, Vertex *vrt, Face *tri)
TBaseElem * GetConnectedNeighbor (Grid &g, typename TBaseElem::side *face, TBaseElem *elem)
template Edge * GetConnectedNeighbor< Edge > (Grid &, Vertex *, Edge *)
template Face * GetConnectedNeighbor< Face > (Grid &, Edge *, Face *)
template Volume * GetConnectedNeighbor< Volume > (Grid &, Face *, Volume *)
Vertex * GetConnectedVertex (Edge *e, Vertex *v)
Vertex * GetConnectedVertex (EdgeVertices *e, Face *f)
int GetConnectedVertexIndex (Face *f, const EdgeDescriptor &ed)
int GetConnectedVertexIndex (Face *f, const EdgeVertices *e)
Edge * GetConnectingEdge (Grid &grid, Face *f1, Face *f2)
void GetCoord (string str, vector< double > &coord)
void GetCuthillMcKeeOrder (const TSparseMatrix &mat, std::vector< size_t > &newIndex, bool reverse=true, bool bPreserveConsec=false)
const T * GetDataPtr (const std::vector< T > &v)
T * GetDataPtr (std::vector< T > &v)
DebugIDManager & GetDebugIDManager ()
UG_API TAttachment & GetDefaultPositionAttachment ()
APosition & GetDefaultPositionAttachment< APosition > ()
APosition1 & GetDefaultPositionAttachment< APosition1 > ()
APosition2 & GetDefaultPositionAttachment< APosition2 > ()
size_t GetDenseDoubleFromSparse (TDenseType &A, const TSparseMatrix &S)
DenseMatrixFromSparseMatrix< TSparseMatrix >::type & GetDenseFromSparse (typename DenseMatrixFromSparseMatrix< TSparseMatrix >::type &A, const TSparseMatrix &S)
double GetDet2 (const DenseMatrix< T > &mat)
double GetDet3 (const DenseMatrix< T > &mat)
void GetDiag (double &a, double b)
void GetDiag (T1 &m1, const T2 &m)
void GetDiagSqrt (double &a, double b)
void GetDiagSqrt (T1 &v, const T2 &m)
void GetDim (string str, vector< size_t > &dim)
TAAPos::ValueType GetDirection (TElem1 *e1, TElem2 *e2, const TAAPos &aaPos)
UG_API bool GetDirectoriesInDirectory (std::vector< std::string > &dirsOut, const char *dir)
std::string::size_type GetDirectorySeperatorPos (const std::string &str)
string::size_type GetDirectorySeperatorPos (const string &str)
TDomain::position_attachment_type & GetDomainPositionAttachment (TDomain &dom)
void GetDoubleFromSparseBlock (TDoubleType &A, const TSparseMatrix &S)
size_t GetDoubleSize (const TSparseMatrix &S)
size_t GetDoubleSparseFromBlockSparse (TDoubleSparse &A, const TSparseMatrix &S)
const char * GetDynamicLibraryPrefix ()
const char * GetDynamicLibrarySuffix ()
int GetEdgeIndex (Face *f, Edge *e)
int GetEdgeIndex (Volume *vol, Edge *e)
SweepLineEdge * GetEdgeOnTheLeft (MapEdgeCuts &edgeCuts, SweepLineVertex &v)
void GetElemDiscItemOnSubset (std::vector< TElemOut * > &vSubsetElemDiscOut, const std::vector< TElemIn * > &vElemDiscIn, const std::vector< SubsetGroup > &vSSGrp, int si, bool clearVec=true)
void GetElemDiscOnSubset (std::vector< IElemDisc< TDomain > * > &vSubsetElemDisc, const std::vector< IElemDisc< TDomain > * > &vElemDisc, const std::vector< SubsetGroup > &vSSGrp, int si, bool clearVec)
static TElem * GetElementByCoordinate (TDomain &dom, number x, number y, number z)
int GetFaceIndex (Volume *vol, Face *f)
string GetFileLine (const char *filename, size_t line)
string GetFileLines (const char *filename, size_t fromline, size_t toline, bool includeLineNumbers)
string GetFileLinesParallel (string filename, size_t fromline, size_t toline, bool includeLineNumbers, const pcl::ProcessCommunicator &pc=pcl::ProcessCommunicator())
UG_API std::string GetFilenameExtension (const std::string &str)
string GetFilenameExtension (const string &str)
UG_API bool GetFilesInDirectory (std::vector< std::string > &filesOut, const char *dir)
int GetFirstFreeSubset (const ISubsetHandler &sh)
static int GetFirstRegularVertex (Grid &grid, const SubsetHandler &sh, Face *q)
std::pair< Vertex *, Edge * > GetFirstSectionOfPolyChain (Grid &grid, TEdgeIterator edgesBegin, TEdgeIterator edgesEnd, Grid::edge_traits::callback cbEdgeIsInPolyChain)
vector3 GetGridObjectCenter (Grid &g, GridObject *elem)
vector3 GetGridObjectCenter (Grid &g, TElem *elem)
int GetGridObjectIndex (Grid &g, TElem *elem)
int GetHighestReferencedIndex (IndexLayout &layout)
void GetInnerEdgesOfFaceSoup (std::vector< Edge * > &edgesOut, Grid &g, face_iter_t facesBegin, face_iter_t facesEnd)
bool GetInverse (block_traits< T >::inverse_type &inv, const T &m)
bool GetInverse (DenseMatrix< FixedArray2< double, 1, 1 > > &inv, const DenseMatrix< FixedArray2< double, 1, 1 > > &mat)
bool GetInverse (DenseMatrix< FixedArray2< double, 2, 2 > > &inv, const DenseMatrix< FixedArray2< double, 2, 2 > > &mat)
bool GetInverse (DenseMatrix< FixedArray2< double, 3, 3 > > &inv, const DenseMatrix< FixedArray2< double, 3, 3 > > &mat)
bool GetInverse (DenseMatrixInverse< FixedArray2< T, TBlockSize, TBlockSize, TOrdering > > &inv, const DenseMatrix< FixedArray2< T, TBlockSize, TBlockSize, TOrdering > > &mat)
bool GetInverse (DenseMatrixInverse< VariableArray2< T, TOrdering > > &inv, const DenseMatrix< VariableArray2< T, TOrdering > > &mat)
bool GetInverse (number &inv, const number &m)
bool GetInverse1 (DenseMatrix< T > &inv, const DenseMatrix< T > &mat)
bool GetInverse2 (DenseMatrix< T > &inv, const DenseMatrix< T > &mat)
bool GetInverse3 (DenseMatrix< T > &inv, const DenseMatrix< T > &mat)
bool GetInversePermutation (const std::vector< size_t > &perm, std::vector< size_t > &invPerm)
void GetLayoutTargetProcs (std::vector< int > &procsOut, const TLayout &layout)
void * GetLibraryProcedure (DynLibHandle h, const char *procName)
UG_API std::vector< std::string > GetLoadedPlugins ()
bool GetLocalMatrix (const TGlobalMatrix &mat, TLocalMatrix &localMat)
bool GetLocalMatrix (const TGlobalMatrix &mat, TLocalMatrix &localMat, const size_t *rowIndices, const size_t *colIndices)
void GetLocalVector (LocalVector &lvec, const TVector &vec)
LogAssistant & GetLogAssistant ()
size_t GetMaxConnections (const TSparseMatrix &A)
static number GetMaxEdgeLength (TDomain &dom)
number GetMaxEdgeLength (Volume *vol, TAAPos &aaPos)
int GetMaxSubsetIndex (SubsetHandler &sh)
number GetMinimum (TGridFunction &gridFct, const char *cmp, const char *subsets)
std::pair< size_t, size_t > GetMinMaxNumElements (const tree_t &tree, size_t lvl)
ug::ParallelStorageType GetMultType (const ParallelMatrix< matrix_type > &A1, const ParallelVector< vector_type > &x)
void GetNeighborhood (const TSparseMatrix &A, size_t node, size_t depth, std::vector< size_t > &indices)
void GetNeighborhood (const TSparseMatrix &A, size_t node, size_t depth, std::vector< size_t > &indices, std::vector< bool > &bVisited, bool bResetVisitedFlags=true)
void GetNeighborhood (Grid &grid, size_t extSize, TElem *elem, typename geometry_traits< TElem >::const_iterator &begin, typename geometry_traits< TElem >::const_iterator &end)
void GetNeighborhood_worker (const TSparseMatrix &A, size_t node, size_t depth, std::vector< size_t > &indices, std::vector< bool > &bVisited)
void GetNeighborhoodHierachy (const TSparseMatrix &A, size_t node, size_t depth, std::vector< std::vector< size_t > > &indices)
void GetNeighborhoodHierachy (const TSparseMatrix &A, size_t node, size_t depth, std::vector< std::vector< size_t > > &indices, std::vector< bool > &bVisited, bool bResetVisitedFlags=true)
void GetNeighborhoodHierachy_worker (const TSparseMatrix &A, size_t node, size_t depth, size_t maxdepth, std::vector< std::vector< size_t > > &indices, std::vector< bool > &bVisited)
void GetNeighbours (std::vector< Face * > &vFacesOut, Grid &grid, Face *f, int side, bool clearContainer=true)
void GetNeighbours (std::vector< Volume * > &vVolsOut, Grid &grid, Volume *v, int side, bool clearContainer=true)
std::pair< Vertex *, Edge * > GetNextSectionOfPolyChain (Grid &grid, std::pair< Vertex *, Edge * > lastSection, Grid::edge_traits::callback cbEdgeIsInPolyChain)
size_t GetNNZs (const TSparseMatrix &A)
unsigned int GetNumberOfDigits (uint64_t i)
size_t GetNumberOfDoFsOfPyramid (int p)
Vertex * GetOpposingSide (Grid &g, Edge *elem, Vertex *side)
Edge * GetOpposingSide (Grid &g, Face *elem, Edge *side)
Face * GetOpposingSide (Grid &g, Volume *elem, Face *side)
int GetParamIndex (const char *param, int argc, const char *const *argv)
static pair< GridObject *, char > GetParent (BinaryBuffer &in, const vector< Vertex * > &vVrts, const vector< Edge * > &vEdges, const vector< Face * > &vFaces, const vector< Volume * > &vVols)
const char * GetPathSeparator ()
size_t GetPolyChainType (Grid &grid, TEdgeIterator edgesBegin, TEdgeIterator edgesEnd, Grid::edge_traits::callback cbEdgeIsInPolyChain)
UG_API int GetPositionAttachmentDimension ()
const UGProfileNode * GetProfileNode (const char *name)
const UGProfileNode * GetProfileNode (const char *name, const UGProfileNode *node)
bool GetProfilerAvailable ()
void GetProperty (string str, vector< double > &prop)
QuadType GetQuadratureType (const std::string &name)
std::string GetRegistryIdentifierMessage ()
lapack_int getrf (lapack_int rows, lapack_int cols, lapack_double *pColMajorMatrix, lapack_int lda, lapack_int *pPivot)
lapack_int getrf (lapack_int rows, lapack_int cols, lapack_float *pColMajorMatrix, lapack_int lda, lapack_int *pPivot)
lapack_int getrf (lapack_int rows, lapack_int cols, std::complex< lapack_double > *pColMajorMatrix, lapack_int lda, lapack_int *pPivot)
lapack_int getrf (lapack_int rows, lapack_int cols, std::complex< lapack_float > *pColMajorMatrix, lapack_int lda, lapack_int *pPivot)
lapack_int getri (lapack_int n, lapack_double *pColMajorMatrix, lapack_int lda, const int *pPivot, lapack_double *pWork, lapack_int worksize)
lapack_int getri (lapack_int n, lapack_float *pColMajorMatrix, lapack_int lda, const int *pPivot, lapack_float *pWork, lapack_int worksize)
static bool GetRightLeftUnitIndex (int &rightIndex, int &leftIndex, Grid &grid, Face *face, const SubsetHandler &shVolume)
size_t GetRows (const DenseMatrix< T > &t)
size_t GetRows (const number &t)
size_t GetRows (const T &t)
lapack_int getrs (eTransposeMode transposeMode, lapack_int n, lapack_int nrOfRHS, const double *pColMajorMatrix, lapack_int lda, const lapack_int *pPivot, lapack_double *pRHS, lapack_int ldb)
lapack_int getrs (eTransposeMode transposeMode, lapack_int n, lapack_int nrOfRHS, const float *pColMajorMatrix, lapack_int lda, const lapack_int *pPivot, lapack_float *pRHS, lapack_int ldb)
double getScaling (const AlphaVec_Expression< T > &t)
double getScaling (const T &t)
void GetSelectedElementIndices (const ISelector &sel, std::vector< int > &indsOut)
void GetSelectedElementIndices (const ISelector &sel, std::vector< size_t > &indsOut)
void GetSelectedElementIndices (const ISelector &sel, std::vector< size_t > &vrtIndsOut, std::vector< size_t > &edgeIndsOut, std::vector< size_t > &faceIndsOut, std::vector< size_t > &volIndsOut)
size_t GetSelfMem (const Shiny::ProfileNode *p)
UG_API TElem::side * GetSharedSide (Grid &grid, TElem *e1, TElem *e2)
Vertex * GetSharedVertex (IVertexGroup *vrts0, IVertexGroup *vrts1)
size_t GetSharedVertices (std::vector< Vertex * > &vrtsOut, IVertexGroup *vrts0, IVertexGroup *vrts1)
size_t GetSize (const DenseVector< T > &t)
size_t GetSize (const number &t)
size_t GetSize (const T &t)
void GetSliceDenseInverse (const TSparseMatrixType &A, const std::vector< size_t > &indices, DenseMatrix< VariableArray2< double > > &AlocInv)
void GetSliceDenseInverse (const TSparseMatrixType &A, const std::vector< size_t > &indices, DenseMatrix< VariableArray2< double > > &AlocInv, DenseMatrix< VariableArray2< typename TSparseMatrixType::value_type > > &tmp)
void GetSliceSparse (const TSparseMatrixType &A, const std::vector< size_t > &indices, CPUAlgebra::matrix_type &R)
static char GetSmallestLocalSubsetDimension (typename Grid::traits< TElem >::secure_container &nbrs, MultiElementAttachmentAccessor< AChar > &aaDim)
SmartPtr< IElemProlongation< TDomain > > GetStandardElementProlongation (const LFEID &lfeid)
SmartPtr< IElemRestriction< TDomain > > GetStandardElementRestriction (const LFEID &lfeid)
UG_API std::string GetTmpPath ()
size_t GetTotalMem (const Shiny::ProfileNode *p)
size_t GetUniqueFVGeomID ()
size_t GetUniqueTypeID ()
const T & getVector (const AlphaVec_Expression< T > &t)
const TAlgebra::vector_type & getVector (const GridFunction< TDomain, TAlgebra > &t)
const T & getVector (const T &t)
Vertex * GetVertex (Edge *e, size_t i)
Vertex * GetVertex (Face *f, size_t i)
Vertex * GetVertex (Vertex *v, size_t i)
Vertex * GetVertex (Volume *v, size_t i)
int GetVertexIndex (EdgeVertices *e, Vertex *v)
int GetVertexIndex (FaceVertices *f, Vertex *v)
int GetVertexIndex (VolumeVertices *vol, Vertex *v)
void GetZcorn (string str, vector< double > &zcorn)
void GivensMatVecMult (matrix_t &A, vector_t &v)
static SmartPtr< IRefiner > GlobalDomainRefiner (TDomain *dom)
static SmartPtr< GlobalSubdivisionMultiGridRefiner< typename TDomain::position_attachment_type > > GlobalSubdivisionDomainRefiner (TDomain *dom, const char *linearManifoldSubsets, bool constrained)
MathMatrix< 0, 0, T >::value_type GramDeterminant (const MathMatrix< 0, 0, T > &m)
MathMatrix< 0, M, T >::value_type GramDeterminant (const MathMatrix< 0, M, T > &m)
MathMatrix< 1, 1, T >::value_type GramDeterminant (const MathMatrix< 1, 1, T > &m)
MathMatrix< 2, 2, T >::value_type GramDeterminant (const MathMatrix< 2, 2, T > &m)
MathMatrix< 3, 3, T >::value_type GramDeterminant (const MathMatrix< 3, 3, T > &m)
MathMatrix< N, 0, T >::value_type GramDeterminant (const MathMatrix< N, 0, T > &m)
MathMatrix< N, M, T >::value_type GramDeterminant (const MathMatrix< N, M, T > &m)
number GridFunctionDistance2 (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets)
number GridFunctionDistance2 (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets, ConstSmartPtr< typename TDistIntegrand::weight_type > spWeights)
number GridFunctionDistance2 (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets, ConstSmartPtr< typename TDistIntegrand::weight_type > spWeights, number distAvg12)
std::string GridLevelAppendix (const GridLevel &gl, int minfill=2)
void gs_step_LL (const Matrix_type &A, Vector_type &c, const Vector_type &d, const number relaxFactor)
bool gs_step_LL (const Matrix_type &A, Vector_type &x, const Vector_type &b)
void gs_step_UR (const Matrix_type &A, Vector_type &c, const Vector_type &d, const number relaxFactor)
bool gs_step_UR (const Matrix_type &A, Vector_type &x, const Vector_type &b)
number H1Distance (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets=NULL)
number H1Distance2 (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets=NULL)
number H1EnergyDistance (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets, ConstSmartPtr< typename H1SemiDistIntegrand< TGridFunction >::weight_type > weights)
number H1EnergyDistance (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, ConstSmartPtr< typename H1SemiDistIntegrand< TGridFunction >::weight_type > weights)
number H1EnergyDistance2 (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets, ConstSmartPtr< typename H1SemiDistIntegrand< TGridFunction >::weight_type > weights)
number H1EnergyDistance2 (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, ConstSmartPtr< typename H1SemiDistIntegrand< TGridFunction >::weight_type > weights)
number H1EnergyNorm (SmartPtr< TGridFunction > spGridFct, const char *cmp, int quadOrder)
number H1EnergyNorm (SmartPtr< TGridFunction > spGridFct, const char *cmp, int quadOrder, const char *subsets, ConstSmartPtr< typename H1SemiIntegrand< TGridFunction >::weight_type > weights=SPNULL)
number H1EnergyNorm (SmartPtr< TGridFunction > spGridFct, const char *cmp, int quadOrder, ConstSmartPtr< typename H1SemiIntegrand< TGridFunction >::weight_type > weights)
number H1EnergyNorm (TGridFunction &gridFct, const char *cmp, int quadOrder, const char *subsets=NULL, ConstSmartPtr< typename H1SemiIntegrand< TGridFunction >::weight_type > weights=SPNULL)
number H1EnergyNorm2 (TGridFunction &gridFct, const char *cmp, int quadOrder, const char *subsets=NULL, ConstSmartPtr< typename H1SemiIntegrand< TGridFunction >::weight_type > weights=SPNULL)
number H1Error (SmartPtr< TGridFunction > spGridFct1, const char *cmp1, SmartPtr< TGridFunction > spGridFct2, const char *cmp2, int quadOrder)
number H1Error (SmartPtr< TGridFunction > spGridFct1, const char *cmp1, SmartPtr< TGridFunction > spGridFct2, const char *cmp2, int quadOrder, const char *subsets)
number H1Error (SmartPtr< UserData< number, TGridFunction::dim > > spExactSol, SmartPtr< UserData< MathVector< TGridFunction::dim >, TGridFunction::dim > > spExactGrad, SmartPtr< TGridFunction > spGridFct, const char *cmp, number time, int quadOrder)
number H1Error (SmartPtr< UserData< number, TGridFunction::dim > > spExactSol, SmartPtr< UserData< MathVector< TGridFunction::dim >, TGridFunction::dim > > spExactGrad, SmartPtr< TGridFunction > spGridFct, const char *cmp, number time, int quadOrder, const char *subsets)
number H1Norm (SmartPtr< TGridFunction > spGridFct, const char *cmp, int quadOrder)
number H1Norm (SmartPtr< TGridFunction > spGridFct, const char *cmp, int quadOrder, const char *subsets)
number H1Norm (TGridFunction &u, const char *cmp, int quadOrder, const char *subsets=NULL)
number H1Norm2 (TGridFunction &u, const char *cmp, int quadOrder, const char *subsets=NULL)
number H1SemiDistance (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets, ConstSmartPtr< typename H1SemiDistIntegrand< TGridFunction >::weight_type > weights)
number H1SemiDistance (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, ConstSmartPtr< typename H1SemiDistIntegrand< TGridFunction >::weight_type > weights)
number H1SemiDistance2 (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets, ConstSmartPtr< typename H1SemiDistIntegrand< TGridFunction >::weight_type > weights)
number H1SemiDistance2 (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, ConstSmartPtr< typename H1SemiDistIntegrand< TGridFunction >::weight_type > weights)
number H1SemiError (SmartPtr< TGridFunction > spGridFct1, const char *cmp1, SmartPtr< TGridFunction > spGridFct2, const char *cmp2, int quadOrder)
number H1SemiError (SmartPtr< TGridFunction > spGridFct1, const char *cmp1, SmartPtr< TGridFunction > spGridFct2, const char *cmp2, int quadOrder, const char *subsets)
number H1SemiError2 (SmartPtr< TGridFunction > spGridFct1, const char *cmp1, SmartPtr< TGridFunction > spGridFct2, const char *cmp2, int quadOrder, const char *subsets)
number H1SemiNorm (SmartPtr< TGridFunction > spGridFct, const char *cmp, int quadOrder)
number H1SemiNorm (SmartPtr< TGridFunction > spGridFct, const char *cmp, int quadOrder, const char *subsets)
number H1SemiNorm (SmartPtr< TGridFunction > spGridFct, const char *cmp, int quadOrder, const char *subsets, ConstSmartPtr< typename H1SemiIntegrand< TGridFunction >::weight_type > weights=SPNULL)
number H1SemiNorm (SmartPtr< TGridFunction > spGridFct, const char *cmp, int quadOrder, ConstSmartPtr< typename H1SemiIntegrand< TGridFunction >::weight_type > weights)
number H1SemiNorm (TGridFunction &gridFct, const char *cmp, int quadOrder, const char *subsets=NULL, ConstSmartPtr< typename H1SemiIntegrand< TGridFunction >::weight_type > weights=SPNULL)
number H1SemiNorm2 (TGridFunction &gridFct, const char *cmp, int quadOrder, const char *subsets=NULL, ConstSmartPtr< typename H1SemiIntegrand< TGridFunction >::weight_type > weights=SPNULL)
static SmartPtr< IRefiner > HangingNodeDomainRefiner (TDomain *dom)
void HangingNormalOnSCVF (MathVector< TWorldDim > &outNormal, const MathVector< TWorldDim > *vCornerCoords)
size_t hash_key (const EdgeVertices *key)
size_t hash_key (const FaceVertices *key)
UG_API size_t hash_key (const std::string &str)
size_t hash_key (const string &key)
size_t hash_key (const TKey &key)
size_t hash_key (const VolumeVertices *key)
size_t hash_key (Edge *key)
size_t hash_key (EdgeDescriptor *key)
size_t hash_key (EdgeVertices *key)
size_t hash_key (Face *key)
size_t hash_key (FaceDescriptor *key)
size_t hash_key (FaceVertices *key)
size_t hash_key (Vertex *key)
size_t hash_key (Volume *key)
size_t hash_key (VolumeDescriptor *key)
size_t hash_key (VolumeVertices *key)
size_t hash_key< AlgebraID > (const AlgebraID &key)
size_t hash_key< GeomObjID > (const GeomObjID &key)
static unsigned long HashKey (const EdgeVertices *key)
static unsigned long HashKey (const FaceVertices *key)
static unsigned long HashKey (const VolumeVertices *key)
bool HasMemTracking ()
std::string HistogrammString (std::vector< double > values)
void IdentifySubsets (TDomain &dom, const char *sName1, const char *sName2)
void IdentifySubsets (TDomain &dom, int sInd1, int sInd2)
bool ImportGridFromLGM (Grid &grid, const char *filename, AVector3 &aPos, ISubsetHandler *pSurfaceHandler)
bool ImportGridFromNG (Grid &grid, const char *filename, AVector3 &aPos, ISubsetHandler *pSubdomainHandler)
bool ImportGridFromTETGEN (Grid &grid, const char *nodesFilename, const char *facesFilename, const char *elemsFilename, AVector3 &aPos, ISubsetHandler *psh, std::vector< AFloat > *pvNodeAttributes)
bool ImportGridFromTETGEN (Grid &grid, const char *nodesFilename, const char *facesFilename, const char *elemsFilename, AVector3 &aPos, std::vector< AFloat > *pvNodeAttributes, AInt *paNodeBoundaryMarker, AInt *paFaceBoundaryMarker, AInt *paElementAttribute)
std::string IndexListToRangeString (const std::vector< ind_t > &inds)
void induced_subgraph (G_t &ind_g, M_t *A, const std::vector< size_t > &inv_map)
void Init___CompressibleNavierStokes (bridge::Registry *reg, std::string grp)
void Init___CompressibleNavierStokes (Registry *reg, string grp)
void Init___CompressibleNavierStokes___FV1 (Registry *reg, string grp)
void Init___CompressibleNavierStokes___FV1 (ug::bridge::Registry *reg, std::string grp)
void Init___IncompressibleNavierStokes (bridge::Registry *reg, std::string grp)
void Init___IncompressibleNavierStokes (Registry *reg, string grp)
void Init___NavierStokes___FE (Registry *reg, string grp)
void Init___NavierStokes___FE (ug::bridge::Registry *reg, std::string grp)
void Init___NavierStokes___FV (Registry *reg, string grp)
void Init___NavierStokes___FV (ug::bridge::Registry *reg, std::string grp)
void Init___NavierStokes___FV1 (Registry *reg, string grp)
void Init___NavierStokes___FV1 (ug::bridge::Registry *reg, std::string grp)
void Init___NavierStokes___FVCR (Registry *reg, string grp)
void Init___NavierStokes___FVCR (ug::bridge::Registry *reg, std::string grp)
void InitLinearManifoldSubsetHandler (MultiGrid &mg, MGSubsetHandler &sh, MGSubsetHandler &linearManifoldSH, const char *linearManifoldSubsets)
bool InitPaths (const char *argv0)
void InitUGPlugin_ConvectionDiffusion (ug::bridge::Registry *reg, string grp)
This function is called when the plugin is loaded.
void InitUGPlugin_DemoPlugin (Registry *reg, string grp)
void InitUGPlugin_DocuGen (Registry *reg, string grp)
void InitUGPlugin_Electromagnetism (Registry *reg, string grp)
void InitUGPlugin_Jupyter (Registry *reg, string grp)
void InitUGPlugin_Limex (Registry *reg, string grp)
void InitUGPlugin_LuaShell (Registry *reg, string grp)
void InitUGPlugin_NavierStokes (Registry *reg, string grp)
void InitUGPlugin_ProMesh (Registry *reg, string grp)
void InitUGPlugin_Richards (Registry *reg, string grp)
void InitUGPlugin_SmallStrainMechanics (Registry *reg, string grp)
void InitUGPlugin_TemplatePlugin (Registry *reg, string grp)
bool InnerDoFPosition (std::vector< MathVector< dim > > &vPos, const ReferenceObjectID roid, const std::vector< MathVector< dim > > &vCornerCoord, const LFEID &lfeID)
bool InnerDoFPosition (std::vector< MathVector< TDomain::dim > > &vPos, GridObject *elem, const TDomain &domain, const LFEID &lfeID)
bool InnerDoFPositionElem (std::vector< MathVector< dim > > &vPos, const ReferenceObjectID roid, const std::vector< MathVector< dim > > &vVertPos, const LFEID &lfeID)
bool InnerDoFPositionVertex (std::vector< MathVector< dim > > &vPos, const ReferenceObjectID roid, const std::vector< MathVector< dim > > &vVertPos, const LFEID &lfeID)
void InsertCenterVertex (Grid &g, Face *f, Vertex *vrt, bool eraseOldFace)
void InsertCenterVertex (Grid &g, Volume *vol, Vertex *vrt, bool eraseOldVol)
number Integral (number val, SmartPtr< TGridFunction > spGridFct)
number Integral (number val, SmartPtr< TGridFunction > spGridFct, const char *subsets)
number Integral (number val, SmartPtr< TGridFunction > spGridFct, const char *subsets, number time)
number Integral (number val, SmartPtr< TGridFunction > spGridFct, const char *subsets, number time, int quadOrder)
number Integral (number val, SmartPtr< TGridFunction > spGridFct, number time)
number Integral (SmartPtr< TGridFunction > spGridFct, const char *cmp)
number Integral (SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets)
number Integral (SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, int quadOrder)
number Integral (SmartPtr< UserData< number, TGridFunction::dim > > spData, SmartPtr< TGridFunction > spGridFct)
number Integral (SmartPtr< UserData< number, TGridFunction::dim > > spData, SmartPtr< TGridFunction > spGridFct, const char *subsets)
number Integral (SmartPtr< UserData< number, TGridFunction::dim > > spData, SmartPtr< TGridFunction > spGridFct, const char *subsets, number time)
number Integral (SmartPtr< UserData< number, TGridFunction::dim > > spData, SmartPtr< TGridFunction > spGridFct, const char *subsets, number time, int order)
number Integral (SmartPtr< UserData< number, TGridFunction::dim > > spData, SmartPtr< TGridFunction > spGridFct, const char *subsets, number time, int quadOrder, std::string quadType)
number Integral (SmartPtr< UserData< number, TGridFunction::dim > > spData, SmartPtr< TGridFunction > spGridFct, number time)
number Integral (SmartPtr< UserData< number, TGridFunction::dim > > spData, TGridFunction &spGridFct, const char *subsets, number time, int quadOrder, std::string quadType)
number Integral (TGridFunction &gridFct, const char *cmp, const char *subsets, int quadOrder)
number IntegralNormalComponentOnManifold (SmartPtr< UserData< MathVector< TGridFunction::dim >, TGridFunction::dim > > spData, SmartPtr< TGridFunction > spGridFct, const char *BndSubset)
number IntegralNormalComponentOnManifold (SmartPtr< UserData< MathVector< TGridFunction::dim >, TGridFunction::dim > > spData, SmartPtr< TGridFunction > spGridFct, const char *BndSubset, const char *InnerSubset)
number IntegralNormalComponentOnManifold (SmartPtr< UserData< MathVector< TGridFunction::dim >, TGridFunction::dim > > spData, SmartPtr< TGridFunction > spGridFct, const char *BndSubset, const char *InnerSubset, number time)
number IntegralNormalComponentOnManifold (SmartPtr< UserData< MathVector< TGridFunction::dim >, TGridFunction::dim > > spData, SmartPtr< TGridFunction > spGridFct, const char *BndSubset, const char *InnerSubset, number time, int quadOrder)
number IntegralNormalComponentOnManifold (SmartPtr< UserData< MathVector< TGridFunction::dim >, TGridFunction::dim > > spData, SmartPtr< TGridFunction > spGridFct, const char *BndSubset, number time)
number IntegralNormalComponentOnManifoldGeneral (TConstIterator iterBegin, TConstIterator iterEnd, typename domain_traits< WorldDim >::position_accessor_type &aaPos, const ISubsetHandler *ish, IIntegrand< MathVector< WorldDim >, WorldDim > &integrand, const SubsetGroup &bndSSGrp, int quadOrder, Grid &grid)
number IntegralNormalComponentOnManifoldSubset (SmartPtr< IIntegrand< MathVector< TGridFunction::dim >, TGridFunction::dim > > spIntegrand, SmartPtr< TGridFunction > spGridFct, int si, const SubsetGroup &bndSSGrp, int quadOrder)
number IntegralNormalComponentOnManifoldSubsets (SmartPtr< IIntegrand< MathVector< TGridFunction::dim >, TGridFunction::dim > > spIntegrand, SmartPtr< TGridFunction > spGridFct, const char *BndSubsets, const char *InnerSubsets, int quadOrder)
number IntegralNormalComponentOnManifoldUsingFV1Geom (TConstIterator iterBegin, TConstIterator iterEnd, typename domain_traits< WorldDim >::position_accessor_type &aaPos, const ISubsetHandler *ish, IIntegrand< MathVector< WorldDim >, WorldDim > &integrand, const SubsetGroup &bndSSGrp)
number Integrate (TConstIterator iterBegin, TConstIterator iterEnd, typename domain_traits< WorldDim >::position_accessor_type &aaPos, IIntegrand< number, WorldDim > &integrand, int quadOrder, std::string quadType, Grid::AttachmentAccessor< typename domain_traits< dim >::grid_base_object, ANumber > *paaElemContribs=NULL)
number IntegrateDiscFlux (SmartPtr< IAssemble< typename TGridFunction::algebra_type > > spAssemble, SmartPtr< TGridFunction > spGridFct, const char *pCmps, const char *subsets)
void IntegrateDiscFlux (std::vector< number > &vValue, const TGridFunction &rDefect, const FunctionGroup &fctGrp, int si)
number IntegrateNormalComponentOnManifold (TGridFunction &u, const char *cmp, const char *BndSubset)
number IntegrateNormalGradientOnManifold (TGridFunction &u, const char *cmp, const char *BndSubset, const char *InnerSubset=NULL)
number IntegrateSubset (IIntegrand< number, TGridFunction::dim > &spIntegrand, TGridFunction &spGridFct, int si, int quadOrder, std::string quadType)
number IntegrateSubsets (IIntegrand< number, TGridFunction::dim > &spIntegrand, TGridFunction &spGridFct, const char *subsets, int quadOrder, std::string quadType=std::string())
void Interpolate (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp)
void Interpolate (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets)
void Interpolate (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, number time)
void Interpolate (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, number time, const SmartPtr< CplUserData< MathVector< TGridFunction::dim >, TGridFunction::dim > > m_diff_pos)
void Interpolate (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp, number time)
void Interpolate (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp)
void Interpolate (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets)
void Interpolate (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, number time)
void Interpolate (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, number time, const MathVector< TGridFunction::dim > diff_pos)
void Interpolate (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, const MathVector< TGridFunction::dim > &m_diff_pos)
void Interpolate (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, number time)
void Interpolate (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const size_t fct, const char *subsets, number time, const MathVector< TGridFunction::dim > diff_pos)
void Interpolate (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const size_t fct, const SubsetGroup &ssGrp, number time, const MathVector< TGridFunction::dim > diff_pos)
void interpolate_from_original_fct (SmartPtr< TGridFunction > u_new, const TGGFND &u_orig, size_t fct, const LFEID &lfeid)
template<typename TGridFunction >
void interpolateCRToLagrange (TGridFunction &uLagrange, TGridFunction &uCR)
void InterpolateInner (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp)
void InterpolateInner (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets)
void InterpolateInner (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, number time)
void InterpolateInner (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp, number time)
void InterpolateInner (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp)
void InterpolateInner (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets)
void InterpolateInner (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, number time)
void InterpolateInner (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, number time)
void InterpolateInnerDiff (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, number time, const SmartPtr< CplUserData< MathVector< TGridFunction::dim >, TGridFunction::dim > > m_diff_pos)
void InterpolateOnDiffElements (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, int si, number time, const MathVector< TGridFunction::dim > diff_pos)
void InterpolateOnDiffElements (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, number time, const SubsetGroup &ssGrp, const MathVector< TGridFunction::dim > diff_pos)
void InterpolateOnDiffVertices (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, number time, const SubsetGroup &ssGrp, const MathVector< TGridFunction::dim > diff_pos)
void InterpolateOnElements (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, int si, number time)
void InterpolateOnElements (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, number time, const SubsetGroup &ssGrp)
void InterpolateOnElementsInner (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, int si, number time)
void InterpolateOnElementsInner (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, int si, number time, const MathVector< TGridFunction::dim > diff_pos)
void InterpolateOnElementsInner (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, number time, const SubsetGroup &ssGrp)
void InterpolateOnVertices (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, number time, const SubsetGroup &ssGrp)
void InterpolateValues (TVector &u, std::vector< size_t > &constrainedIndex, std::vector< std::vector< size_t > > &vConstrainingIndex)
bool IntersectCloseEdges (Grid &grid, TObjectCollection &elems, TAAPosVRT &aaPos, number snapThreshold)
bool IntersectCoplanarTriangles (std::vector< typename TAAPos::ValueType > &edgesOut, FaceVertices *tri1, FaceVertices *tri2, TAAPos aaPos)
bool IntersectCoplanarTriangles (std::vector< vector2 > &edgesOut, const vector2 &p00, const vector2 &p01, const vector2 &p02, const vector2 &p10, const vector2 &p11, const vector2 &p12)
bool IntersectCoplanarTriangles (std::vector< vector3 > &edgesOut, const vector3 &p00, const vector3 &p01, const vector3 &p02, const vector3 &p10, const vector3 &p11, const vector3 &p12)
size_t IntersectPlaneWithTetrahedron (vector3 intsOut[4], const vector3 &planePoint, const vector3 &planeNormal, const vector3 t[4])
void InvalidateSmallLenses (Field< T > &field, size_t thresholdCellCount, const T &noDataValue)
MathMatrix< 1, 1, T >::value_type Inverse (MathMatrix< 1, 1, T > &mOut, const MathMatrix< 1, 1, T > &m)
MathMatrix< 2, 2, T >::value_type Inverse (MathMatrix< 2, 2, T > &mOut, const MathMatrix< 2, 2, T > &m)
MathMatrix< 3, 3, T >::value_type Inverse (MathMatrix< 3, 3, T > &mOut, const MathMatrix< 3, 3, T > &m)
MathMatrix< N, M, T >::value_type Inverse (MathMatrix< N, M, T > &mOut, const MathMatrix< M, N, T > &m)
void InverseFromInverseType (TMatrix &mat, TInverseMatrixType &inv, TVector &x, TVector &e)
void InverseFromInverseType (TMatrix &mat, TMatrix &inv, TVector &x, TVector &e)
bool InverseMatMult (DenseVector< FixedArray1< double, 1 > > &dest, double beta1, const DenseMatrix< FixedArray2< double, 1, 1 > > &A1, const DenseVector< FixedArray1< double, 1 > > &w1)
bool InverseMatMult (DenseVector< FixedArray1< double, 2 > > &dest, double beta, const DenseMatrix< FixedArray2< double, 2, 2 > > &mat, const DenseVector< FixedArray1< double, 2 > > &vec)
bool InverseMatMult (DenseVector< FixedArray1< double, 3 > > &dest, double beta, const DenseMatrix< FixedArray2< double, 3, 3 > > &mat, const DenseVector< FixedArray1< double, 3 > > &vec)
bool InverseMatMult (DenseVector< vector_t > &dest, double beta, const DenseMatrix< matrix_t > &mat, const DenseVector< vector_t > &vec)
bool InverseMatMult (number &dest, const double &beta, const number &mat, const number &vec)
bool InverseMatMult (number &dest, const double &beta, const TMat &mat, const TVec &vec)
bool InverseMatMult1 (DenseVector< vector_t > &dest, double beta1, const DenseMatrix< matrix_t > &A1, const DenseVector< vector_t > &w1)
bool InverseMatMult2 (DenseVector< vector_t > &dest, double beta, const DenseMatrix< matrix_t > &mat, const DenseVector< vector_t > &vec)
bool InverseMatMult3 (DenseVector< vector_t > &dest, double beta, const DenseMatrix< matrix_t > &mat, const DenseVector< vector_t > &vec)
bool InverseMatMultN (DenseVector< vector_t > &dest, double beta, const DenseMatrix< matrix_t > &mat, const DenseVector< vector_t > &vec)
MathMatrix< 1, 1, T >::value_type InverseTransposed (MathMatrix< 1, 1, T > &mOut, const MathMatrix< 1, 1, T > &m)
MathMatrix< 2, 2, T >::value_type InverseTransposed (MathMatrix< 2, 2, T > &mOut, const MathMatrix< 2, 2, T > &m)
MathMatrix< 3, 3, T >::value_type InverseTransposed (MathMatrix< 3, 3, T > &mOut, const MathMatrix< 3, 3, T > &m)
MathMatrix< N, M, T >::value_type InverseTransposed (MathMatrix< N, M, T > &mOut, const MathMatrix< M, N, T > &m)
bool Invert (DenseMatrix< FixedArray2< double, 1, 1 > > &mat)
bool Invert (DenseMatrix< FixedArray2< double, 2, 2 > > &mat)
bool Invert (DenseMatrix< FixedArray2< double, 3, 3 > > &mat)
bool Invert (DenseMatrix< FixedArray2< T, TUnknowns, TUnknowns > > &mat)
bool Invert (DenseMatrix< T > &mat)
bool Invert (number &m)
bool Invert (T &m)
bool Invert1 (DenseMatrix< T > &mat)
bool Invert2 (DenseMatrix< T > &mat)
bool Invert3 (DenseMatrix< FixedArray2< double, 3, 3 > > &mat)
bool Invert3 (DenseMatrix< VariableArray2< double > > &mat)
bool invert_L (const Matrix_type &A, Vector_type &x, const Vector_type &b)
bool invert_U (const Matrix_type &A, Vector_type &x, const Vector_type &b, const number eps=1e-8)
bool InvertNdyn (DenseMatrix< T > &mat)
void InvertOrientation (Grid &grid, iter_t elemsBegin, iter_t elemsEnd)
void InvertSelection (TSelector &sel)
void InvertSelection (TSelector &sel, TIterator begin, TIterator end)
template void InvertSelection< MGSelector > (MGSelector &)
template void InvertSelection< Selector > (Selector &)
void InvertTensor4 (MathTensor4< TDim, TDim, TDim, TDim > &tens4_out, const MathTensor4< TDim, TDim, TDim, TDim > &tens4)
void InvMatVecMult_byGivens (matrix_t &A, vector_t &v)
AnisotropyState is_anisotropic (Edge *elem, const TAAPos &aaPos, number thresholdRatio)
AnisotropyState is_anisotropic (Face *elem, const TAAPos &aaPos, number thresholdRatio)
static AnisotropyState is_anisotropic (Hexahedron *hex, const TAAPos &aaPos, number thresholdRatio)
static AnisotropyState is_anisotropic (Prism *p, const TAAPos &aaPos, number thresholdRatio)
static AnisotropyState is_anisotropic (Quadrilateral *q, const TAAPos &aaPos, number thresholdRatio)
AnisotropyState is_anisotropic (Volume *elem, const TAAPos &aaPos, number thresholdRatio)
bool is_permutation (O_t &o)
bool IsBigEndian ()
bool IsBoundaryEdge (Grid &grid, Edge *e, Grid::face_traits::callback funcIsSurfFace)
bool IsBoundaryEdge2D (Grid &grid, Edge *e)
bool IsBoundaryEdge3D (Grid &grid, Edge *e)
UG_API bool IsBoundaryFace3D (Grid &grid, TFace *f)
bool IsBoundaryVertex1D (Grid &grid, Vertex *v, Grid::edge_traits::callback cbConsiderEdge=ConsiderAll())
bool IsBoundaryVertex2D (Grid &grid, Vertex *v)
bool IsBoundaryVertex3D (Grid &grid, Vertex *v)
bool IsCloseToBoundary (const TSparseMatrix &A, size_t node, size_t distance)
bool IsDegenerated (Face *f, TAAPosVRT &aaPos, number threshold)
bool IsDirichletRow (const TSparseMatrix &A, size_t i, size_t alpha)
bool IsFinite (const ParallelVector< TVector > &v)
bool IsFiniteAndNotTooBig (const DenseMatrix< T > &m)
bool IsFiniteAndNotTooBig (const DenseVector< T > &v)
bool IsFiniteAndNotTooBig (const MathMatrix< N, M, T > &m)
bool IsFiniteAndNotTooBig (const MathTensor< TRank, N, T > &t)
bool IsFiniteAndNotTooBig (const MathTensorX< TData, N > &t)
bool IsFiniteAndNotTooBig (const MathVector< N, T > &m)
bool IsFiniteAndNotTooBig (const ParallelVector< TVector > &v)
bool IsFiniteAndNotTooBig (const std::vector< TData > &t)
bool IsFiniteAndNotTooBig (const TVector &v, double tooBigValue=1e24)
bool IsFiniteAndNotTooBig (double d)
bool IsInInterface (IndexLayout::Interface &interface, size_t i)
bool IsLittleEndian ()
UG_API bool IsLonger (const std::string &a, const std::string &b)
bool IsLonger (const string &a, const string &b)
bool IsMemTrackerEnabled ()
bool IsRegularSurfaceVertex (Grid &grid, Vertex *v)
bool IsShiftChar (char c)
int IsSliver (const vector3 &v0, const vector3 &v1, const vector3 &v2, const vector3 &v3, number thresholdRatio)
bool IsSubSurfaceElement (MultiGrid &mg, TElem *e, bool checkSides=false)
bool IsValidRegistryIdentifier (const std::string &name)
bool IsVectorFiniteAndNotTooBig (const T &t)
static bool IsVertical (const vector1 &, const vector1 &)
static bool IsVertical (const vector2 &from, const vector2 &to)
static bool IsVertical (const vector3 &from, const vector3 &to)
bool IsVolumeBoundaryFace (Grid &grid, ConstrainedFace *f)
bool IsVolumeBoundaryFace (Grid &grid, ConstrainingFace *f)
bool IsVolumeBoundaryFace (Grid &grid, Face *f)
bool iszero (__T __val)
TIterDest iterator_cast (const TIterSrc &iter)
std::string JuliaString (const DenseMatrix< TStorage > &A, const char *name)
template<typename TGridFunction >
number kineticEnergy (TGridFunction &u)
number L2Distance (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets)
number L2Distance2 (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets)
number L2Distance2 (TGridFunction &spGridFct1, const char *cmp1, TGridFunction &spGridFct2, const char *cmp2, int quadOrder, const char *subsets, ConstSmartPtr< typename L2Integrand< TGridFunction >::weight_type > spWeight, number avgDist12=0.0)
number L2Error (SmartPtr< TGridFunction > spGridFct1, const char *cmp1, SmartPtr< TGridFunction > spGridFct2, const char *cmp2, int quadOrder)
number L2Error (SmartPtr< TGridFunction > spGridFct1, const char *cmp1, SmartPtr< TGridFunction > spGridFct2, const char *cmp2, int quadOrder, const char *subsets)
number L2Error (SmartPtr< UserData< number, TGridFunction::dim > > spExactSol, SmartPtr< TGridFunction > spGridFct, const char *cmp, number time, int quadOrder)
number L2Error (SmartPtr< UserData< number, TGridFunction::dim > > spExactSol, SmartPtr< TGridFunction > spGridFct, const char *cmp, number time, int quadOrder, const char *subsets)
number L2Error (SmartPtr< UserData< number, TGridFunction::dim > > spExactSol, TGridFunction &gridFct, const char *cmp, number time, int quadOrder, const char *subsets)
number L2Norm (SmartPtr< TGridFunction > spGridFct, const char *cmp, int quadOrder)
number L2Norm (SmartPtr< TGridFunction > spGridFct, const char *cmp, int quadOrder, const char *subsets)
number L2Norm (TGridFunction &gridFct, const char *cmp, int quadOrder)
number L2Norm (TGridFunction &u, const char *cmp, int quadOrder, const char *subsets)
number L2Norm2 (TGridFunction &u, const char *cmp, int quadOrder, const char *subsets)
number L2Norm2 (TGridFunction &u, const char *cmp, int quadOrder, const char *subsets, ConstSmartPtr< typename L2Integrand< TGridFunction >::weight_type > spWeight)
size_t LagrangeNumDoFOnSub (const ReferenceObjectID elem, const ReferenceObjectID sub, const size_t p)
size_t LagrangeNumDoFs (const ReferenceObjectID elem, const size_t p)
void LaplacianSmooth (Grid &grid, TIterator vrtsBegin, TIterator vrtsEnd, AAPosVRT &aaPos, number alpha, int numIterations)
MathMatrix< 1, 1, T >::value_type LeftInverse (MathMatrix< 1, 1 > &mOut, const MathMatrix< 1, 1 > &m)
MathMatrix< 2, 2, T >::value_type LeftInverse (MathMatrix< 2, 2 > &mOut, const MathMatrix< 2, 2 > &m)
MathMatrix< 3, 3, T >::value_type LeftInverse (MathMatrix< 3, 3 > &mOut, const MathMatrix< 3, 3 > &m)
MathMatrix< N, M, T >::value_type LeftInverse (MathMatrix< N, M, T > &mOut, const MathMatrix< M, N, T > &m)
number LegendrePoly (size_t k, number x)
UG_API size_t LevenshteinDistance (const std::string &s1, const std::string &s2)
size_t LevenshteinDistance (const string &s1, const string &s2)
bool LiesOnBoundary (Grid &grid, Edge *e)
UG_API bool LiesOnBoundary (Grid &grid, TFace *f)
bool LiesOnBoundary (Grid &grid, Vertex *v)
bool LineBoxIntersection (const vector_t &v1, const vector_t &v2, const vector_t &boxMin, const vector_t &boxMax)
bool LineLineIntersection2d (vector_t &vOut, number &t0Out, number &t1Out, const vector_t &from0, const vector_t &to0, const vector_t &from1, const vector_t &to1, const number threshold=0)
bool LineLineIntersection3d (vector3 &aOut, vector3 &bOut, const vector3 &a1, const vector3 &a2, const vector3 &b1, const vector3 &b2)
bool LineLineProjection (number &t1Out, number &t2Out, const vector_t &a1, const vector_t &a2, const vector_t &b1, const vector_t &b2)
int LineSphereIntersection (number &s1Out, number &s2Out, const vector_t &v1, const vector_t &v2, const vector_t &center, number radius)
static void LoadAndRefineDomain (TDomain &domain, const char *filename, int numRefs)
void LoadDomain (TDomain &domain, const char *filename)
void LoadDomain (TDomain &domain, const char *filename, int procId)
template void LoadDomain< Domain1d > (Domain1d &domain, const char *filename)
template void LoadDomain< Domain1d > (Domain1d &domain, const char *filename, int procId)
template void LoadDomain< Domain2d > (Domain2d &domain, const char *filename)
template void LoadDomain< Domain2d > (Domain2d &domain, const char *filename, int procId)
template void LoadDomain< Domain3d > (Domain3d &domain, const char *filename)
template void LoadDomain< Domain3d > (Domain3d &domain, const char *filename, int procId)
static bool LoadGrid (Grid &grid, ISubsetHandler *psh, const char *filename, TAPos &aPos, int procId)
static bool LoadGrid (Grid &grid, SPProjectionHandler *ph, size_t &num_ph, ISubsetHandler *psh, std::vector< std::string > additionalSHNames, std::vector< SmartPtr< ISubsetHandler >> ash, const char *filename, TAPos &aPos, int procId)
static bool LoadGrid3d (Grid &grid, ISubsetHandler *psh, const char *filename, APosition1 &aPos)
static bool LoadGrid3d (Grid &grid, ISubsetHandler *psh, const char *filename, APosition2 &aPos)
static bool LoadGrid3d (Grid &grid, ISubsetHandler *psh, const char *filename, APosition3 &aPos)
static bool LoadGrid3d_IMPL (Grid &grid, ISubsetHandler *pSH, const char *filename, AVector3 &aPos)
bool LoadGridFrom2DF (Grid &grid, const char *filename, ISubsetHandler *psh, AVector3 &aPos)
bool LoadGridFromART (Grid &grid, const char *filename, ISubsetHandler *pSH=NULL, AVector3 &aPos=aPosition)
bool LoadGridFromASC (Grid &grid, const char *filename, AVector3 &aPos)
bool LoadGridFromDUMP (Grid &grid, const char *filename, ISubsetHandler *pSH=NULL, AVector3 &aPos=aPosition)
bool LoadGridFromELE (Grid &grid, const char *filename, ISubsetHandler *pSH, APosition &aPos)
template bool LoadGridFromFile (Grid &, const char *, AVector1 &, int)
template bool LoadGridFromFile (Grid &, const char *, AVector2 &, int)
template bool LoadGridFromFile (Grid &, const char *, AVector3 &, int)
template bool LoadGridFromFile (Grid &, ISubsetHandler &, const char *, AVector1 &, int)
template bool LoadGridFromFile (Grid &, ISubsetHandler &, const char *, AVector2 &, int)
template bool LoadGridFromFile (Grid &, ISubsetHandler &, const char *, AVector3 &, int)
template bool LoadGridFromFile (Grid &, SPProjectionHandler &, size_t &, ISubsetHandler &, std::vector< std::string >, std::vector< SmartPtr< ISubsetHandler >>, const char *, AVector1 &, int)
template bool LoadGridFromFile (Grid &, SPProjectionHandler &, size_t &, ISubsetHandler &, std::vector< std::string >, std::vector< SmartPtr< ISubsetHandler >>, const char *, AVector2 &, int)
template bool LoadGridFromFile (Grid &, SPProjectionHandler &, size_t &, ISubsetHandler &, std::vector< std::string >, std::vector< SmartPtr< ISubsetHandler >>, const char *, AVector3 &, int)
bool LoadGridFromFile (Grid &grid, const char *filename, int procId)
bool LoadGridFromFile (Grid &grid, const char *filename, TAPos &aPos, int procId)
bool LoadGridFromFile (Grid &grid, ISubsetHandler &sh, const char *filename, int procId=-1)
bool LoadGridFromFile (Grid &grid, ISubsetHandler &sh, const char *filename, TAPos &aPos, int procId)
UG_API bool LoadGridFromFile (Grid &grid, SPProjectionHandler &ph, size_t &num_ph, ISubsetHandler &sh, std::vector< std::string > additionalSHNames, std::vector< SmartPtr< ISubsetHandler >> ash, const char *filename, TAPos &aPos, int procId=-1)
bool LoadGridFromFile (Grid &grid, SPProjectionHandler &ph, size_t &num_ph, ISubsetHandler &sh, vector< string > additionalSHNames, vector< SmartPtr< ISubsetHandler >> ash, const char *filename, TAPos &aPos, int procId)
bool LoadGridFromGRDECL (Grid &grid, const char *filename, AVector3 &aPos=aPosition)
bool LoadGridFromLGB (Grid &grid, const char *filename, ISubsetHandler **ppSH, int numSHs, ISelector **ppSel, int numSels, ProjectionHandler *pPH, APosition aPos)
bool LoadGridFromLGB (Grid &grid, const char *filename, ISubsetHandler **ppSH, int numSHs, ProjectionHandler *pPH, APosition aPos)
bool LoadGridFromMSH (Grid &grid, const char *filename, ISubsetHandler *psh=NULL, AVector3 &aPos=aPosition)
bool LoadGridFromOBJ (Grid &grid, const char *filename, AVector3 &aPos, AVector2 *paTexCoord, ISubsetHandler *pSubsetHandler, std::vector< OBJMaterial > *pvMaterials)
bool LoadGridFromSMESH (Grid &grid, const char *filename, AVector3 &aPos, ISubsetHandler *psh)
bool LoadGridFromSTL (Grid &grid, const char *filename, ISubsetHandler *pSH=NULL, AVector3 &aPos=aPosition, AVector3 &aNormFACE=aNormal)
bool LoadGridFromSTL_ASCII (Grid &grid, const char *filename, ISubsetHandler *pSH=NULL, AVector3 &aPos=aPosition, AVector3 &aNormFACE=aNormal)
bool LoadGridFromSTL_BINARY (Grid &grid, const char *filename, ISubsetHandler *pSH=NULL, AVector3 &aPos=aPosition, AVector3 &aNormFACE=aNormal)
bool LoadGridFromSWC (Grid &g, ISubsetHandler *pSH, const char *fileName, AVector3 &aPos)
bool LoadGridFromTXT (Grid &grid, const char *filename, AVector3 &aPos=aPosition)
bool LoadGridFromUGX (Grid &grid, ISubsetHandler &sh, const char *filename)
bool LoadGridFromUGX (Grid &grid, ISubsetHandler &sh, const char *filename, APosition &aPos)
bool LoadGridFromUGX (Grid &grid, ISubsetHandler &sh, const char *filename, TAPosition &aPos)
bool LoadGridFromUGX (Grid &grid, SPProjectionHandler &ph, size_t &num_ph, ISubsetHandler &sh, std::vector< std::string > additionalSHNames, std::vector< SmartPtr< ISubsetHandler >> ash, const char *filename, TAPosition &aPos)
bool LoadGridFromVTU (Grid &grid, ISubsetHandler &sh, const char *filename)
bool LoadGridFromVTU (Grid &grid, ISubsetHandler &sh, const char *filename, APosition &aPos)
bool LoadGridFromVTU (Grid &grid, ISubsetHandler &sh, const char *filename, TAPosition &aPos)
void LoadHeightfieldFromASC (Heightfield &hfield, const char *filename)
bool LoadMarkerPointsFromFile (MarkerPointManager &manager, const char *filename)
UG_API bool LoadPlugins (const char *pluginPath, std::string parentGroup, bridge::Registry &reg, bool bPrefixGroup=false)
bool LoadPlugins (const char *pluginPath, string parentGroup, bridge::Registry &reg, bool bPrefixGroup)
void LoadVector (TGridFunction &u, const char *filename)
void LogIndexLayout (IndexLayout &layout, int depth=0)
void LogIndexLayoutOnAllProcs (IndexLayout &layout, int depth=0)
AnisotropyState long_edges_of_anisotropic_elem (Edge *elem, Grid &grid, const TAAPos &aaPos, number thresholdRatio, std::vector< Edge * > &longEdges)
AnisotropyState long_edges_of_anisotropic_elem (Face *elem, Grid &grid, const TAAPos &aaPos, number thresholdRatio, std::vector< Edge * > &longEdges)
AnisotropyState long_edges_of_anisotropic_elem (Volume *elem, Grid &grid, const TAAPos &aaPos, number thresholdRatio, std::vector< Edge * > &longEdges)
bool LUDecomp (DenseMatrix< matrix_t > &A, size_t *pInterchange)
bool LUDecompIKJ (DenseMatrix< matrix_t > &A, size_t *pInterchange)
std::tuple< dirichlet_iterator< TAlgebra >, dirichlet_iterator< TAlgebra > > make_dirichlet_iterator (typename TAlgebra::matrix_type &mat)
std::tuple< non_dirichlet_iterator< TAlgebra >, non_dirichlet_iterator< TAlgebra > > make_non_dirichlet_iterator (typename TAlgebra::matrix_type &mat)
bool MakeConsistent (const ParallelMatrix< matrix_type > &_mat, ParallelMatrix< matrix_type > &newMat)
template bool MakeDelaunay (DelaunayInfo< Grid::VertexAttachmentAccessor< AVector3 > > &)
bool MakeDelaunay (DelaunayInfo< TAAPos > &info)
SPIGeometry3d MakeGeometry3d (Grid &grid, TAPos aPos)
GeomObjID MakeGeomObjID (int procRank, size_t localGeomObjID)
void MakeSubsetsConsecutive (SubsetHandler &sh)
UG_API std::string MakeTmpFile (std::string filename, const std::string &extension, bool &bSuccess)
string MakeTmpFile (string filename, const string &extension, bool &bSuccess)
static SmartPtr< vector1 > MakeVec (number x)
static SmartPtr< vector2 > MakeVec (number x, number y)
static SmartPtr< vector3 > MakeVec (number x, number y, number z)
static SmartPtr< vector4 > MakeVec (number x, number y, number z, number w)
void MapLagrangeMultiIndexQuad (std::vector< size_t > &vOrientOffset, const int id0, bool sameOrientation, const size_t pOuter)
void MapLagrangeMultiIndexTriangle (std::vector< size_t > &vOrientOffset, const int id0, bool sameOrientation, const size_t pOuter)
void MaplePrint (const DenseMatrix< TStorage > &A, const char *name)
static void mark_if_periodic (IRefiner &ref, TElem *e)
static void MarkAllElemsForAssemblyButHSlaves (Grid &grid, BoolMarker &bMarker)
static void MarkAllElemsForAssemblyButHSlaves (SmartPtr< IAssemble< TAlgebra > > ass, Grid &grid)
void MarkAllFromInterface (std::vector< bool > &mark, const IndexLayout::Interface &interface)
void MarkAllFromInterface (std::vector< T > &mark, const IndexLayout::Interface &interface, const T &default_val)
void MarkAllFromLayout (std::vector< bool > &mark, const IndexLayout &layout)
void MarkAllFromLayout (std::vector< T > &mark, const IndexLayout &layout, const T &default_val)
void MarkAlongSurface (SmartPtr< IRefiner > refiner, SmartPtr< TDomain > domain, const std::vector< std::string > &surfaceSubsets, const std::vector< std::string > &volumeSubsets)
void MarkAnisotropic (SmartPtr< IRefiner > refiner, SmartPtr< TDomain > domain, number thresholdRatio)
void MarkAnisotropic_LongEdges (TDomain &dom, IRefiner &refiner, number minLen)
void MarkAnisotropicOnlyX (SmartPtr< IRefiner > refiner, SmartPtr< TDomain > domain, number thresholdRatio)
UG_API void MarkCorners (Grid &grid, ISubsetHandler &sh, TVertexIterator vrtsBegin, TVertexIterator vrtsEnd, Grid::edge_traits::callback cbPathEdge, int subsetIndex, number angle, TAPosition &aPos)
void MarkCreaseEdges (Grid &grid, ISubsetHandler &sh, TEdgeIterator edgesBegin, TEdgeIterator edgesEnd, int subsetIndex, number angle, APosition &aPos, ANormal *paFaceNormal)
void MarkElements (MultiGrid::AttachmentAccessor< TElem, ug::Attachment< number > > &aaError, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd, number TOL, number refineFrac, number coarseFrac, int maxLevel)
void MarkElementsAbsolute (MultiGrid::AttachmentAccessor< TElem, ug::Attachment< number > > &aaError, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd, number refTol, number coarsenTol, int minLevel, int maxLevel, bool refTopLvlOnly=false)
void MarkElementsForCoarsening (MultiGrid::AttachmentAccessor< TElem, ug::Attachment< number > > &aaError, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd, number TOL, number safety, int minLevel=0)
void MarkElementsForRefinement (MultiGrid::AttachmentAccessor< TElem, ug::Attachment< number > > &aaError, IRefiner &refiner, ConstSmartPtr< DoFDistribution > dd, number tol, int maxLevel)
void MarkFixedCreaseVertices (Grid &grid, SubsetHandler &sh, int creaseSI, int fixedSI)
void MarkForAdaption_AbsoluteGradientIndicator (IRefiner &refiner, GridFunction< TDomain, TAlgebra > &u, const char *fctName, number refTol, number coarsenTol, int minLvl, int maxLevel)
void MarkForAdaption_AbsoluteGradientJumpIndicator (IRefiner &refiner, GridFunction< TDomain, TAlgebra > &u, const char *fctName, number refTol, number coarsenTol, int minLvl, int maxLevel)
void MarkForAdaption_ElementsContainingPoint (TDomain &dom, IRefiner &refiner, number x, number y, number z, std::string markType)
void MarkForAdaption_ElementsTouchingSubset (TDomain &dom, IRefiner &refiner, ISubsetHandler &sh, int subsetIndex, std::string markType)
void MarkForAdaption_ElementsTouchingSubsets (TDomain &dom, IRefiner &refiner, const char *subsets, std::string markType)
void MarkForAdaption_GradientAverage (IRefiner &refiner, SmartPtr< GridFunction< TDomain, TAlgebra > > u, const char *cmp, number refFrac, int minLvl, int maxLvl)
void MarkForAdaption_GradientIndicator (IRefiner &refiner, GridFunction< TDomain, TAlgebra > &u, const char *fctName, number TOL, number refineFrac, number coarseFrac, int maxLevel)
void MarkForAdaption_GradientJump (IRefiner &refiner, SmartPtr< GridFunction< TDomain, TAlgebra > > u, const char *cmp, number refFrac, int minLvl, int maxLvl, std::string jumpType)
void MarkForAdaption_GradientJumpIndicator (IRefiner &refiner, GridFunction< TDomain, TAlgebra > &u, const char *fctName, number TOL, number refineFrac, number coarseFrac, int maxLevel)
void MarkForAdaption_L2ErrorExact (IRefiner &refiner, SmartPtr< GridFunction< TDomain, TAlgebra > > u, SmartPtr< UserData< number, TDomain::dim > > spExactSol, const char *cmp, number minL2Error, number maxL2Error, number refFrac, int minLvl, int maxLvl, number time, int quadOrder)
number MarkForAdaption_ResidualErrorP1Absolute (IRefiner &refiner, SmartPtr< GridFunction< TDomain, TAlgebra > > u, SmartPtr< UserData< number, TDomain::dim > > f, const char *cmp, number time, number refTol, number coarsenTol, int maxLvl, int quadOrder, std::string quadType, bool refTopLvlOnly=false)
void MarkForAdaption_ResidualErrorP1Relative (IRefiner &refiner, SmartPtr< GridFunction< TDomain, TAlgebra > > u, SmartPtr< UserData< number, TDomain::dim > > f, const char *cmp, number time, number refFrac, int minLvl, int maxLvl, int quadOrder, std::string quadType)
void MarkForAdaption_VerticesInCube (TDomain &dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type &min, const typename TDomain::position_type &max, std::string markType)
void MarkForAdaption_VerticesInSphere (TDomain &dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type &center, number radius, std::string markType)
void MarkForAdaption_VerticesInSphereMaxLvl (TDomain &dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type &center, number radius, std::string markType, int maxLvl)
void MarkForAnisotropicRefinement (Grid &grid, TRef &ref, number minEdgeRatio, TIter elemsBegin, TIter elemsEnd, TAAPos aaPos)
void MarkForCoarsen_ElementsByLuaCallback (TDomain &dom, SmartPtr< IRefiner > refiner, double time, const char *luaCallbackName)
void MarkForCoarsenening_SurfaceLayer (const GridFunction< TDomain, TAlgebra > &u, IRefiner &refiner)
static void MarkForRefinement_All (SmartPtr< IRefiner > ref)
static void MarkForRefinement_AllAnisotropic (SmartPtr< IRefiner > ref)
void MarkForRefinement_AnisotropicDirection (TDomain &dom, IRefiner &refiner, MathVector< TDomain::dim > &dir, number minEdgeRatio)
void MarkForRefinement_AnisotropicElements (TDomain &dom, IRefiner &refiner, number minEdgeRatio)
void MarkForRefinement_CloseToSurface (TDomain &dom, SmartPtr< IRefiner > refiner, double time, size_t maxLvl, const TDomain &surfaceDomain)
void MarkForRefinement_ContainsSurfaceNode (TDomain &dom, SmartPtr< IRefiner > refiner, double time, size_t maxLvl, const TDomain &surfaceDomain)
void MarkForRefinement_EdgeDirection (TDomain &dom, IRefiner &refiner, MathVector< TDomain::dim > &dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
void MarkForRefinement_ElementsByLuaCallback (TDomain &dom, SmartPtr< IRefiner > refiner, double time, size_t maxLvl, const char *luaCallbackName)
void MarkForRefinement_ElementsInSphere (TDomain &dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type &center, number radius)
void MarkForRefinement_ElementsInSubset (TDomain &dom, IRefiner &refiner, TSubsetHandler &sh, int subsetIndex)
void MarkForRefinement_SubsetInterfaceElements (IRefiner &refiner, ISubsetHandler &sh)
void MarkForRefinement_SubsetInterfaceElements (TDomain &dom, IRefiner &refiner)
void MarkForRefinement_VerticesInCube (TDomain &dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type &min, const typename TDomain::position_type &max)
void MarkForRefinement_VerticesInSphere (TDomain &dom, SmartPtr< IRefiner > refiner, const typename TDomain::position_type &center, number radius)
void MarkForRefinementByDirection (TRef &ref, TAAPos aaPos, TEdgeIter edgesBegin, TEdgeIter edgesEnd, const typename TAAPos::ValueType &dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
void MarkGlobal (SmartPtr< IRefiner > refiner, SmartPtr< TDomain > domain)
void MarkNeighbors (const TSparseMatrix &A, size_t node, size_t depth, std::vector< bool > &bVisited)
void MarkNeighborsForAnisotropicRefinement (IRefiner &refiner, bool sideNbrsOnly)
void MarkNeighborsForFullRefinement (IRefiner &refiner, bool sideNbrsOnly)
unsigned long MarkOutOfRangeElems (SmartPtr< IRefiner > refiner, ConstSmartPtr< TGridFunction > u, size_t cmp, number lowerBnd, number upperBnd)
void MarkSubsets (SmartPtr< IRefiner > refiner, SmartPtr< TDomain > domain, const std::vector< std::string > &vSubset)
void MatAdd (matrix_t &mOut, const matrix_t &m, typename matrix_t::value_type s)
void MatAdd (matrix_t &mOut, const matrix_t &m1, const matrix_t &m2)
void MatAdd (matrix_type &M, number alpha1, const matrix_type &A, number alpha2, const matrix_type &B)
void MatAdd (MatrixOperator< M, X, Y > &res, number alpha1, MatrixOperator< M, X, Y > &A1, number alpha2, MatrixOperator< M, X, Y > &A2)
void MatAdditiveToConsistentOnDiag (typename TAlgebra::matrix_type *pMat, const IndexLayout &masterLayout, const IndexLayout &slaveLayout, pcl::InterfaceCommunicator< IndexLayout > *pCom=NULL)
void MatAddNonDirichlet (matrix_type &M, number alpha1, const matrix_type &A, number alpha2, const matrix_type &B)
void MatAddSlaveRowsToMasterRowOverlap0 (TMatrix &mat)
matrix_t::value_type MatContraction (const matrix_t &m1, const matrix_t &m2)
matrix_t::value_type MatDeviatorTrace (const matrix_t &m, matrix_t &dev)
double matDiagMax (const DenseMatrix< T1 > &mat)
double matDiagMax (const double d)
void MatDiagSet (matrix_t &mInOut, typename matrix_t::value_type s)
void MatDivide (matrix_t &mOut, const matrix_t &m, typename matrix_t::value_type s)
void MatExtractDiagOnLayout (TVector *pDiagVector, const TMatrix *pMatrix, const IndexLayout &Layout)
matrix_t::value_type MatFrobeniusNorm (matrix_t &m)
matrix_t::value_type MatFrobeniusNormSq (matrix_t &m)
void MatHouseholder (matrix_t &mOut, const vector_t &orthoVec)
MathVector< toN, T > MathVectorFrom (const MathVector< fromN, T > &v)
MathVector< N, T > MathVectorFrom (const MathVector< N, T > &v)
void MatIdentity (matrix_t &mOut)
void MatIdentity (MatrixOperator< M, X, Y > &opOut)
matrix_t::value_type MatInftyNorm (matrix_t &m)
std::string MatlabString (const DenseMatrix< TStorage > &A, const char *name)
void MatMakeConsistentOverlap0 (TMatrix &mat)
matrix_t::value_type MatMaxNorm (matrix_t &m)
void MatMult (DenseVector< vector_t > &dest, const number &beta1, const DenseMatrix< matrix_t > &A1, const DenseVector< vector_t > &w1)
void MatMult (DenseVector< vector_t > &dest, const number &beta1, const DenseMatrixInverse< matrix_t > &A1, const DenseVector< vector_t > &w1)
bool MatMult (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1)
void MatMultAdd (DenseVector< vector_t > &dest, const number &alpha1, const DenseVector< vector_t > &v1, const number &beta1, const DenseMatrix< matrix_t > &A1, const DenseVector< vector_t > &w1)
void MatMultAdd (DenseVector< vector_t > &dest, const number &alpha1, const DenseVector< vector_t > &v1, const number &beta1, const DenseMatrixInverse< matrix_t > &A1, const DenseVector< vector_t > &w1)
bool MatMultAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &alpha2, const vector_t &v2, const number &beta1, const matrix_t &A1, const vector_t &w1)
bool MatMultAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const matrix_t &A1, const vector_t &w1)
bool MatMultAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const matrix_t &A1, const vector_t &w1, const number &beta2, const matrix_t &A2, const vector_t &w2)
bool MatMultAdd (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1, const number &beta2, const matrix_t &A2, const vector_t &w2)
bool MatMultAddDirect (ParallelVector< vector_type > &dest, const number &alpha1, const ParallelVector< vector_type > &v1, const number &alpha2, const ParallelVector< vector_type > &v2, const number &beta1, const ParallelMatrix< matrix_type > &A1, const ParallelVector< vector_type > &w1)
bool MatMultAddDirect (ParallelVector< vector_type > &dest, const number &alpha1, const ParallelVector< vector_type > &v1, const number &beta1, const ParallelMatrix< matrix_type > &A1, const ParallelVector< vector_type > &w1)
bool MatMultAddDirect (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1, const number &alpha1, const vector_t &v1)
bool MatMultAddDirect (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1, const number &alpha1, const vector_t &v1, const number &alpha2, const vector_t &v2)
bool MatMultAddDirect (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1, const number &beta2, const matrix_t &A2, const vector_t &w2)
bool MatMultAddDirect (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1, const number &beta2, const matrix_t &A2, const vector_t &w2, const number &alpha1, const vector_t &v1)
bool MatMultDirect (ParallelVector< vector_type > &dest, const number &beta1, const ParallelMatrix< matrix_type > &A1, const ParallelVector< vector_type > &w1)
void MatMultiply (MathMatrix< N, M, T > &mOut, const MathMatrix< N, L, T > &m1, const MathMatrix< L, M, T > &m2)
void MatMultiply (MathMatrix< N, M, T > &mOut, const MathMatrix< N, L, T > &m1, const MathMatrix< L, P, T > &m2, const MathMatrix< P, M, T > &m3)
void MatMultiply (matrix_t &mOut, const matrix_t &m, typename matrix_t::value_type s)
void MatMultiplyMBMT (MathMatrix< N, N, T > &mOut, const MathMatrix< N, M, T > &m1, const MathMatrix< M, M, T > &m2)
void MatMultiplyMBT (MathMatrix< N, M, T > &mOut, const MathMatrix< N, L, T > &m1, const MathMatrix< M, L, T > &m2)
void MatMultiplyMMT (MathMatrix< M, M, T > &mOut, const MathMatrix< M, N, T > &m)
void MatMultiplyMTB (MathMatrix< N, M, T > &mOut, const MathMatrix< L, N, T > &m1, const MathMatrix< L, M, T > &m2)
void MatMultiplyMTBM (MathMatrix< N, N, T > &mOut, const MathMatrix< M, N, T > &m1, const MathMatrix< M, M, T > &m2)
void MatMultiplyMTM (MathMatrix< N, N, T > &mOut, const MathMatrix< M, N, T > &m)
void MatMultiplyTransposed (MathMatrix< N, M, T > &mOut, const MathMatrix< L, N, T > &m1, const MathMatrix< M, L, T > &m2)
bool MatMultTransposed (vector_t &dest, const number &beta1, const matrix_t &A1, const vector_t &w1)
void MatMultTransposedAdd (DenseVector< vector_t > &dest, const number &alpha1, const DenseVector< vector_t > &v1, const number &beta1, const DenseMatrix< matrix_t > &A1, const DenseVector< vector_t > &w1)
void MatMultTransposedAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const GPUSparseMatrix< matrix_t > &A1, const vector_t &w1)
void MatMultTransposedAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const MapSparseMatrix< matrix_t > &A1, const vector_t &w1)
bool MatMultTransposedAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const matrix_t &A1, const vector_t &w1)
void MatMultTransposedAdd (vector_t &dest, const number &alpha1, const vector_t &v1, const number &beta1, const SparseMatrix< matrix_t > &A1, const vector_t &w1)
void MatMultTransposedDirect (ParallelVector< vector_type > &dest, const number &beta1, const ParallelMatrix< matrix_type > &A1, const ParallelVector< vector_type > &w1)
matrix_t::value_type MatOneNorm (matrix_t &m)
DenseMatrix< TStorage > MatrixTranspose (const DenseMatrix< TStorage > &A)
double MatrixTranspose (const double &b)
void MatRotationX (matrix_t &mOut, typename matrix_t::value_type rads)
void MatRotationY (matrix_t &mOut, typename matrix_t::value_type rads)
void MatRotationYawPitchRoll (matrix_t &mOut, typename matrix_t::value_type yaw, typename matrix_t::value_type pitch, typename matrix_t::value_type roll)
void MatRotationZ (matrix_t &mOut, typename matrix_t::value_type rads)
void MatScale (matrix_t &mOut, typename matrix_t::value_type s, const matrix_t &m)
void MatScale (MatrixOperator< M, X, Y > &A, number alpha)
void MatScaleAppend (matrix_t &mOut, typename matrix_t::value_type s, const matrix_t &m)
void MatSet (matrix_t &mInOut, typename matrix_t::value_type s)
void MatSubtract (matrix_t &mOut, const matrix_t &m, typename matrix_t::value_type s)
void MatSubtract (matrix_t &mOut, const matrix_t &m1, const matrix_t &m2)
void matSum (double &erg, double alpha, double vec)
T1 matSum (double alpha, T2 &mat)
void matSum (T1 &erg, double alpha, T2 &mat)
void MatToTens4 (MathTensor4< TDim, TDim, TDim, TDim > &tens4, const DenseMatrixInverse< FixedArray2< number, TDimSQ, TDimSQ > > &mat)
double matTrace (const DenseMatrix< T1 > &mat)
double matTrace (const double d)
void MatTranspose (MatrixOperator< M, X, Y > &AT, MatrixOperator< M, X, Y > &A)
void MatVecMult (vector_t_out &vOut, const matrix_t &m, const vector_t_in &v)
void MatVecMultAppend (vector_t_out &vOut, const matrix_t &m, const vector_t_in &v)
void MatVecScaleMultAppend (vector_t_out &vOut, typename vector_t_out::value_type s, const matrix_t &m, const vector_t_in &v)
void MatWriteDiagOnLayout (TMatrix *pMatrix, const TVector *pDiagVector, const IndexLayout &Layout)
MathMatrix< 1, 1, T >::value_type MaxAbsEigenvalue (const MathMatrix< 1, 1, T > &m)
MathMatrix< 2, 2, T >::value_type MaxAbsEigenvalue (const MathMatrix< 2, 2, T > &m)
MathMatrix< N, M, T >::value_type MaxAbsEigenvalue (const MathMatrix< M, N, T > &m)
number MaxElementDiameter (Grid &grid, TAAPos &aaPos, TIterator iterBegin, TIterator iterEnd)
number MaxElementDiameter (TDomain &domain, int level)
template number MaxElementDiameter< Domain1d > (Domain1d &domain, int level)
template number MaxElementDiameter< Domain2d > (Domain2d &domain, int level)
template number MaxElementDiameter< Domain3d > (Domain3d &domain, int level)
number MaxError (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp)
number MaxError (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets)
number MaxError (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, number time)
number MaxError (number val, SmartPtr< TGridFunction > spGridFct, const char *cmp, number time)
number MaxError (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp)
number MaxError (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets)
number MaxError (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets, number time)
number MaxError (SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, const char *cmp, number time)
void MaxErrorOnElements (number &globalMaxError, SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, int si, number time)
void MaxErrorOnElements (number &globalMaxError, SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, number time, const SubsetGroup &ssGrp)
void MaxErrorOnVertices (number &globalMaxError, SmartPtr< UserData< number, TGridFunction::dim > > spInterpolFunction, SmartPtr< TGridFunction > spGridFct, size_t fct, number time, const SubsetGroup &ssGrp)
void MeasureTetrahedronWithSmallestMinAngle (MultiGrid &grid)
void MemSwap (T &a, T &b)
void MergeGlobalLayout (GlobalLayout &globalLayout, const std::map< int, int > &merge)
template void MergeGrids (Grid &, Grid &, ISubsetHandler &, ISubsetHandler &, APosition1, bool)
template void MergeGrids (Grid &, Grid &, ISubsetHandler &, ISubsetHandler &, APosition2, bool)
template void MergeGrids (Grid &, Grid &, ISubsetHandler &, ISubsetHandler &, APosition3, bool)
void MergeGrids (Grid &mrgGrid, Grid &grid, ISubsetHandler &mrgSh, ISubsetHandler &sh, TAPos aPos, bool joinSubsets)
void MergeInterfaces (TLayout &layout, const std::map< int, int > merge)
void MergeInterfaces (TLayout &layout, const std::vector< int > pidSources, int pidAppendTo)
UG_API Vertex * MergeMultipleVertices (Grid &grid, TVrtIterator vrtsBegin, TVrtIterator vrtsEnd)
void MergeVertices (Grid &grid, Vertex *v1, Vertex *v2)
void MeshLayerBoundaries (Grid &grid, const RasterLayers &layers, Grid::VertexAttachmentAccessor< AVector3 > aaPos, ISubsetHandler *pSH)
void MeshLayers (Grid &grid, const RasterLayers &layers, Grid::VertexAttachmentAccessor< AVector3 > aaPos, ISubsetHandler *pSH)
bool MightContainGhosts (const GridLayoutMap &layoutMap, int lvl)
MathMatrix< N, M, T >::value_type MinAbsEigenvalue (const MathMatrix< M, N, T > &m)
matrix_t::value_type MinAbsEigenvalue (matrix_t &m)
number MinElementDiameter (Grid &grid, TAAPos &aaPos, TIterator iterBegin, TIterator iterEnd)
number MinElementDiameter (TDomain &domain, int level)
template number MinElementDiameter< Domain1d > (Domain1d &domain, int level)
template number MinElementDiameter< Domain2d > (Domain2d &domain, int level)
template number MinElementDiameter< Domain3d > (Domain3d &domain, int level)
UG_API void MinimizeEdgeLength_SwapsOnly (Grid &grid, EdgeIterator edgesBegin, EdgeIterator edgesEnd, TAAPos &aaPos)
static void MinimizeMemoryFootprint (TDomain &dom)
number Minimum (SmartPtr< TGridFunction > spGridFct, const char *cmp, const char *subsets)
void MoveVertices (TIterator vrtsBegin, TIterator vrtsEnd, TAAPos aaPos, const typename TAAPos::ValueType &offset)
void MultiEdgeSplit (Grid &grid, Edge *edge, TVrtIter vrtsBegin, TVrtIter vrtsEnd, TAAPos aaPos)
void MultiEnergyProd (matrix_type &A, SmartPtrVector< vector_type > &px, DenseMatrix< densematrix_type > &rA, size_t n)
void MultiScalProd (vector_type &px, DenseMatrix< densematrix_type > &rA, size_t n)
T * MyCudaAlloc (size_t N)
static void MyPrintError (UGError &err)
static bool NbrIsInSubset (ISubsetHandler &sh, typename Grid::traits< TElem >::secure_container &nbrs, int si)
static void newton_for_bp_projection (vector3 &posOut, const std::vector< NeuriteProjector::BPProjectionHelper > &vProjHelp, float rad, const vector3 &constAngleSurfNormal, const NeuriteProjector *np)
static std::string NextValid2DFLine (ifstream &in)
std::string NonzeroString (const DenseMatrix< TStorage > &A, const char *brackets, const char *seperator, int base, const char *name)
number NormalizedChebyshev1Poly (size_t k, number x)
number NormalizedChebyshev2Poly (size_t k, number x)
number NormalizedLegendrePoly (size_t k, number x)
static bool NotVertical (const vector1 &, const vector1 &)
static bool NotVertical (const vector2 &from, const vector2 &to)
static bool NotVertical (const vector3 &from, const vector3 &to)
int NumAssociatedEdges (Grid &grid, Vertex *v)
int NumAssociatedFaces (Grid &grid, Edge *e)
int NumAssociatedFaces (Grid &grid, Vertex *v)
int NumAssociatedVolumes (Grid &grid, Face *f)
int NumberOfDigits (int n)
void NumeriereKnoten (const std::vector< std::vector< size_t > > &vvConnections, std::vector< bool > &vVisited, std::vector< size_t > &vAncestorsCount, std::vector< size_t > &vNewIndex, size_t &N, size_t v)
static size_t NumIndices (const IndexLayout &Layout)
UG_API size_t NumSharedVertices (Grid &grid, TElemPtr1 elem1, TElemPtr2 elem2)
size_t NumSharedVertices (IVertexGroup *vrts0, IVertexGroup *vrts1)
size_t NumVertices (Edge *elem)
size_t NumVertices (Face *elem)
size_t NumVertices (Vertex *elem)
size_t NumVertices (Volume *elem)
bool ObtainSimpleGrid (SimpleGrid &sgOut, Grid &grid, Vertex *vrt1, Vertex *vrt2, size_t size, TPosAcc &aaPos, TNormAcc &aaNorm, TIntAcc &aaInt)
bool ObtainSimpleGrid_CollapseEdge (SimpleGrid &sgOut, Grid &grid, Edge *e, size_t size, TPosAcc &aaPos, TNormAcc &aaNorm, TIntAcc &aaInt)
void OctReferenceMappingTest (std::vector< number > vCornerCoord0, std::vector< number > vCornerCoord1, std::vector< number > vCornerCoord2, std::vector< number > vCornerCoord3, std::vector< number > vCornerCoord4, std::vector< number > vCornerCoord5, std::vector< number > vGlobPos)
const char * OnOffString (bool b)
DynLibHandle OpenLibrary (const char *fileName)
bool operator!= (const MathVector< N, T > &v, const MathVector< N, T > &w)
ParallelStorageType operator& (const ParallelStorageType &a, const ParallelStorageType &b)
MatVec_Expression< L, R > operator* (const AlphaMat_Expression< L > &l, const R &r)
TE_AlphaVec< typename T::vector_type > operator* (const TE_AlphaVec< T > &l, double alpha)
TE_VecAdd2< T > operator* (const TE_VecAdd2< T > &t, double alpha)
TE_VecAdd3< T > operator* (const TE_VecAdd3< T > &t, double alpha)
double operator* (const TRANSPOSED< Vector< value_type > > &x, const Vector< value_type > &y)
DenseVector< TStorage > operator* (double alpha, const DenseVector< TStorage > &vec)
TE_VecScale< typename T::vector_type > operator* (double alpha, const TE_AlphaVec< T > &r)
TE_VecAdd2< T > operator* (double alpha, const TE_VecAdd2< T > &t)
DenseMatrix< TStorage > operator* (number a, const DenseMatrix< TStorage > &b)
TE_VecAdd2< typename L::vector_type > operator+ (const TE_AlphaVec< L > &l, const TE_AlphaVec< R > &r)
TE_VecAdd3< typename L::vector_type > operator+ (const TE_AlphaVec< R > &r, const TE_VecAdd2< L > &l)
AlphaMatVec_X_Expression< L, operation_add, R > operator+ (const TE_AMV_X< L > &l, const TE_AMV_X< R > &r)
TE_VecAdd3< typename L::vector_type > operator+ (const TE_VecAdd2< L > &l, const TE_AlphaVec< R > &r)
ReferenceObjectID operator++ (ReferenceObjectID &roid, int)
TE_VecAdd2< typename L::vector_type > operator- (const TE_AlphaVec< L > &l, const TE_AlphaVec< R > &r)
TE_VecAdd3< typename L::vector_type > operator- (const TE_AlphaVec< R > &r, const TE_VecAdd2< L > &l)
AlphaMatVec_X_Expression< L, operation_sub, R > operator- (const TE_AMV_X< L > &l, const TE_AMV_X< R > &r)
TE_VecAdd3< typename L::vector_type > operator- (const TE_VecAdd2< L > &l, const TE_AlphaVec< R > &r)
UG_API bool operator< (const GeomObjID &gid1, const GeomObjID &gid2)
bool operator< (const MathVector< N, T > &v, const MathVector< N, T > &w)
bool operator< (double alpha, const DenseVector< TStorage > &vec)
std::ostream & operator<< (std::ostream &os, const NeuriteProjector::Mapping &mapping)
std::ostream & operator<< (std::ostream &os, const NeuriteProjector::SurfaceParams &surfParams)
std::ostream & operator<< (std::ostream &os, const StringTableStream &sts)
std::ostream & operator<< (std::ostream &os, const Table< T > &table)
std::ostream & operator<< (std::ostream &out, const AABox< vector_t > &box)
std::ostream & operator<< (std::ostream &out, const AlgebraID &ID)
std::ostream & operator<< (std::ostream &out, const AlgebraLayouts &layouts)
std::ostream & operator<< (std::ostream &out, const AlgebraType &v)
std::ostream & operator<< (std::ostream &out, const CommonLocalDoFSet &v)
std::ostream & operator<< (std::ostream &out, const DenseMatrix< TStorage > &mat)
std::ostream & operator<< (std::ostream &out, const DenseMatrixInverse< T > &mat)
std::ostream & operator<< (std::ostream &out, const DenseVector< TStorage > &vec)
template std::ostream & operator<< (std::ostream &out, const DimLocalDoFSet< 0 > &v)
template std::ostream & operator<< (std::ostream &out, const DimLocalDoFSet< 1 > &v)
template std::ostream & operator<< (std::ostream &out, const DimLocalDoFSet< 2 > &v)
template std::ostream & operator<< (std::ostream &out, const DimLocalDoFSet< 3 > &v)
std::ostream & operator<< (std::ostream &out, const DimLocalDoFSet< dim > &v)
std::ostream & operator<< (std::ostream &out, const FixedArray1< T, n > &arr)
std::ostream & operator<< (std::ostream &out, const FixedArray2< T, rowsT, colsT, T_ordering > &arr)
UG_API std::ostream & operator<< (std::ostream &out, const GeomObjID &goId)
std::ostream & operator<< (std::ostream &out, const GridLevel &v)
std::ostream & operator<< (std::ostream &out, const HorizontalAlgebraLayouts &layouts)
std::ostream & operator<< (std::ostream &out, const IndexLayout &layout)
std::ostream & operator<< (std::ostream &out, const LFEID &v)
std::ostream & operator<< (std::ostream &out, const LocalDoF &v)
std::ostream & operator<< (std::ostream &out, const LocalDoFSet &v)
std::ostream & operator<< (std::ostream &out, const QuadType &v)
std::ostream & operator<< (std::ostream &out, const ReservableArray2< T, T_ordering > &arr)
std::ostream & operator<< (std::ostream &out, const VariableArray1< T > &arr)
std::ostream & operator<< (std::ostream &out, const VariableArray2< T, T_ordering > &arr)
std::ostream & operator<< (std::ostream &outStream, const GridFunction< TDomain, TAlgebra > &v)
std::ostream & operator<< (std::ostream &outStream, const ParallelStorageType &type)
std::ostream & operator<< (std::ostream &outStream, const ug::FunctionGroup &grp)
std::ostream & operator<< (std::ostream &outStream, const ug::FunctionIndexMapping &map)
std::ostream & operator<< (std::ostream &outStream, const ug::LocalMatrix &mat)
std::ostream & operator<< (std::ostream &outStream, const ug::LocalVector &vec)
std::ostream & operator<< (std::ostream &outStream, const ug::MathMatrix< 2, 2 > &m)
std::ostream & operator<< (std::ostream &outStream, const ug::MathMatrix< 2, 3 > &m)
std::ostream & operator<< (std::ostream &outStream, const ug::MathMatrix< 3, 2 > &m)
std::ostream & operator<< (std::ostream &outStream, const ug::MathMatrix< 3, 3 > &m)
std::ostream & operator<< (std::ostream &outStream, const ug::MathMatrix< N, M > &m)
std::ostream & operator<< (std::ostream &outStream, const ug::MathSymmetricMatrix< 2 > &m)
std::ostream & operator<< (std::ostream &outStream, const ug::MathSymmetricMatrix< 3 > &m)
std::ostream & operator<< (std::ostream &outStream, const ug::MathSymmetricMatrix< N > &m)
std::ostream & operator<< (std::ostream &outStream, const ug::MathTensor< TRank, N, T > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathTensorX< TEntry, 1 > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathTensorX< TEntry, N > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathVector< 0, T > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathVector< 1 > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathVector< 1, T > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathVector< 2 > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathVector< 2, T > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathVector< 3 > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathVector< 3, T > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathVector< 4 > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathVector< 4, T > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MathVector< N, T > &v)
std::ostream & operator<< (std::ostream &outStream, const ug::MultiIndex< N > &v)
std::ostream & operator<< (std::ostream &outStream, DiscPart part)
std::ostream & operator<< (std::ostream &outStream, Polynomial1D &v)
std::ostream & operator<< (std::ostream &outStream, ReferenceObjectID type)
std::string operator<< (std::string a, const char *s)
std::string operator<< (std::string a, std::string b)
std::string operator<< (std::string a, T t)
bool operator<= (double alpha, const DenseVector< TStorage > &vec)
bool operator== (const MathVector< 0, T > &v, const MathVector< 0, T > &w)
bool operator== (const MathVector< N, T > &v, const MathVector< N, T > &w)
bool operator> (double alpha, const DenseVector< TStorage > &vec)
bool operator>= (double alpha, const DenseVector< TStorage > &vec)
std::istream & operator>> (std::istream &in, NeuriteProjector::Mapping &mapping)
std::istream & operator>> (std::istream &in, NeuriteProjector::SurfaceParams &surfParams)
template<typename TDomain , typename TGridFunction >
void OrderCRCuthillMcKee (ApproximationSpace< TDomain > &approxSpace, TGridFunction &u, bool bReverse)
orders the all DofDistributions of the ApproximationSpace using Cuthill-McKee
void OrderCuthillMcKee (ApproximationSpace< TDomain > &approxSpace, bool bReverse)
void OrderCuthillMcKee (DoFDistribution &dofDistr, bool bReverse)
void OrderDirectionYForDofDist (SmartPtr< DoFDistribution > dd, ConstSmartPtr< TDomain > domain, std::vector< size_t > &indY)
void OrderDirectionZForDofDist (SmartPtr< DoFDistribution > dd, ConstSmartPtr< TDomain > domain, std::vector< size_t > &indZ)
void OrderDownwind (ApproximationSpace< TDomain > &approxSpace, const std::vector< number > &vVel)
void OrderDownwind (ApproximationSpace< TDomain > &approxSpace, const std::vector< number > &vVel, number threshold)
void OrderDownwind (ApproximationSpace< TDomain > &approxSpace, SmartPtr< UserData< MathVector< TDomain::dim >, TDomain::dim > > spVelocity)
void OrderDownwind (ApproximationSpace< TDomain > &approxSpace, SmartPtr< UserData< MathVector< TDomain::dim >, TDomain::dim > > spVelocity, number threshold)
void OrderDownwindForDofDist (SmartPtr< DoFDistribution > dd, ConstSmartPtr< TDomain > domain, SmartPtr< UserData< MathVector< TDomain::dim >, TDomain::dim > > spVelocity, number time, int si, number threshold)
void OrderDownwindForDofDist (SmartPtr< DoFDistribution > spDd, ConstSmartPtr< TDomain > spDomain, SmartPtr< UserData< MathVector< TDomain::dim >, TDomain::dim > > spVelocity, number threshold)
void OrderLex (ApproximationSpace< TDomain > &approxSpace, const char *order)
void OrderLexForDofDist (SmartPtr< DoFDistribution > dd, ConstSmartPtr< TDomain > domain, size_t orderDim, bool increasing)
bool OrientationMatches (const EdgeVertices &e1, const EdgeVertices &e2)
bool OrientationMatches (EdgeVertices *ev, Face *f)
UG_API bool OrientationMatches (FaceVertices *fv, Volume *v)
void OrthogProjectVec (vector_t &v, const matrix_t &A)
std::string OstreamShift (const T &t)
static void ParallelLayoutDebugSave (MultiGrid &mg)
void ParallelSubspaceCorrectionLoop (const typename TAlgebra::matrix_type &A, GridFunction< TDomain, TAlgebra > &c, const typename TAlgebra::vector_type &d, number omega_relax, ILocalSubspace< TDomain, TAlgebra, TGroupObj > &subspace, typename GridFunction< TDomain, TAlgebra >::template traits< TGroupObj >::const_iterator objIterBegin, typename GridFunction< TDomain, TAlgebra >::template traits< TGroupObj >::const_iterator objIterEnd)
double ParamToDouble (const char *param, int argc, const char *const *argv, double dDefault)
bool ParamToDouble (double &dOut, const char *param, int argc, const char *const *argv)
int ParamToInt (const char *param, int argc, const char *const *argv, int iDefault)
bool ParamToInt (int &iOut, const char *param, int argc, const char *const *argv)
bool ParamToString (const char **strOut, const char *param, int argc, const char *const *argv)
static bool PartitionDistributedDomain_LevelBased (TDomain &domain, PartitionMap &partitionMap, int numPartitions, size_t level)
static bool PartitionDomain_Bisection (TDomain &domain, PartitionMap &partitionMap, int firstAxisToCut)
static bool PartitionDomain_LevelBased (TDomain &domain, PartitionMap &partitionMap, int numPartitions, size_t level)
static bool PartitionDomain_MetisKWay (TDomain &domain, PartitionMap &partitionMap, int numPartitions, size_t baseLevel, int hWeight, int vWeight)
static bool PartitionDomain_MetisKWay (TDomain &domain, PartitionMap &partitionMap, int numPartitions, size_t baseLevel, SmartPtr< PartitionWeighting > weightFct)
static bool PartitionDomain_RegularGrid (TDomain &domain, PartitionMap &partitionMap, int numCellsX, int numCellsY, int numCellsZ, bool surfaceOnly)
bool PartitionElements_RegularGrid (SubsetHandler &shOut, TIterator begin, TIterator end, int numCellsX, int numCellsY, int numCellsZ, TAAPos &aaPos, typename Grid::traits< TElem >::callback cbConsiderElem=ConsiderAll(), int bucketSubset=-1)
bool PartitionGrid_MetisKway (SubsetHandler &shPartitionOut, Grid &grid, int numParts)
template bool PartitionGrid_MetisKway< Edge > (SubsetHandler &, Grid &, int)
template bool PartitionGrid_MetisKway< Face > (SubsetHandler &, Grid &, int)
template bool PartitionGrid_MetisKway< Volume > (SubsetHandler &, Grid &, int)
bool PartitionMultiGrid_MetisKway (SubsetHandler &shPartitionOut, MultiGrid &grid, int numParts, size_t baseLevel, boost::function< int(TGeomBaseObj *, TGeomBaseObj *)> &weightFct)
bool PartitionMultiGrid_MetisKway (SubsetHandler &shPartitionOut, MultiGrid &grid, int numParts, size_t baseLevel=0, int hWeight=1, int vWeight=1)
template bool PartitionMultiGrid_MetisKway< Edge > (SubsetHandler &, MultiGrid &, int, size_t, boost::function< int(Edge *, Edge *)> &)
template bool PartitionMultiGrid_MetisKway< Edge > (SubsetHandler &, MultiGrid &, int, size_t, int, int)
template bool PartitionMultiGrid_MetisKway< Face > (SubsetHandler &, MultiGrid &, int, size_t, boost::function< int(Face *, Face *)> &)
template bool PartitionMultiGrid_MetisKway< Face > (SubsetHandler &, MultiGrid &, int, size_t, int, int)
template bool PartitionMultiGrid_MetisKway< Volume > (SubsetHandler &, MultiGrid &, int, size_t, boost::function< int(Volume *, Volume *)> &)
template bool PartitionMultiGrid_MetisKway< Volume > (SubsetHandler &, MultiGrid &, int, size_t, int, int)
bool PartitionMultiGridLevel_MetisKway (SubsetHandler &shPartitionOut, MultiGrid &mg, int numParts, size_t level)
template bool PartitionMultiGridLevel_MetisKway< Edge > (SubsetHandler &, MultiGrid &, int, size_t)
template bool PartitionMultiGridLevel_MetisKway< Face > (SubsetHandler &, MultiGrid &, int, size_t)
template bool PartitionMultiGridLevel_MetisKway< Volume > (SubsetHandler &, MultiGrid &, int, size_t)
bool PartitionMultiGridLevel_ParmetisKway (SubsetHandler &shPartitionOut, MultiGrid &mg, int numParts, size_t level)
template bool PartitionMultiGridLevel_ParmetisKway< Edge > (SubsetHandler &, MultiGrid &, int, size_t)
template bool PartitionMultiGridLevel_ParmetisKway< Face > (SubsetHandler &, MultiGrid &, int, size_t)
template bool PartitionMultiGridLevel_ParmetisKway< Volume > (SubsetHandler &, MultiGrid &, int, size_t)
UG_API std::string PathFromFilename (const std::string &str)
string PathFromFilename (const string &str)
static bool PerformCollapses (const AdjustEdgeLengthDesc &desc, Grid &grid, SubsetHandler &shMarks, EdgeSelector &esel, TAAPosVRT &aaPos, TAANormVRT &aaNorm, TAAIntVRT &aaInt)
bool PerformCollapses (Grid &grid, SubsetHandler &shMarks, EdgeSelector &esel, number minEdgeLen, TAAPosVRT &aaPos, TAANormVRT &aaNorm, TAAIntVRT &aaInt, bool adaptive=true)
static bool PerformRetetrahedralization (Grid &grid, SubsetHandler &sh, number quality, bool preserveBnds, bool preserveAll, APosition &aPos, ANumber &aVolCon, bool applyVolumeConstraint, int verbosity)
static bool PerformSplits (const AdjustEdgeLengthDesc &desc, Grid &grid, SubsetHandler &shMarks, EdgeSelector &esel, TAAPosVRT &aaPos, TAANormVRT &aaNorm)
bool PerformSplits (Grid &grid, SubsetHandler &shMarks, EdgeSelector &esel, number maxEdgeLen, TAAPosVRT &aaPos, TAANormVRT &aaNorm, bool adaptive=true)
bool PerformSwaps (Grid &grid, SubsetHandler &shMarks, EdgeSelector &esel, TAAPosVRT &aaPos, TAANormVRT &aaNorm, TAAIntVRT &aaInt)
static bool PerformTetrahedralization (Grid &grid, ISubsetHandler *pSH, number quality, bool preserveBnds, bool preserveAll, APosition &aPos, int verbosity)
void PermuteIndicesInIndexLayout (IndexLayout &layout, const std::vector< size_t > &vIndNew)
UG_API bool PluginLoaded (const std::string &name)
bool PluginLoaded (const string &name)
UG_API int PointFaceTest (vector3 &v, Face *f, TAAPosVRT &aaPos)
bool PointIsInsideQuadrilateral (const MathVector< 3 > &v, const MathVector< 3 > &v0, const MathVector< 3 > &v1, const MathVector< 3 > &v2, const MathVector< 3 > &v3)
bool PointIsInsideQuadrilateral (const vector_t &v, const vector_t &v0, const vector_t &v1, const vector_t &v2, const vector_t &v3)
UG_API bool PointIsInsideTetrahedron (const vector3 &v, Tetrahedron *tet, Grid::VertexAttachmentAccessor< APosition > &aaPos)
bool PointIsInsideTetrahedron (const vector_t &v, const vector_t &v0, const vector_t &v1, const vector_t &v2, const vector_t &v3)
bool PointIsInsideTriangle (const MathVector< 3 > &v, const MathVector< 3 > &v0, const MathVector< 3 > &v1, const MathVector< 3 > &v2)
bool PointIsInsideTriangle (const vector_t &v, const vector_t &v0, const vector_t &v1, const vector_t &v2)
bool PointIsInsideTriangle_HighAcc (const vector_t &v, const vector_t &v0, const vector_t &v1, const vector_t &v2)
vector_t PointOnRay (const vector_t &from, const vector_t &dir, number s)
static int PointTriangleIntersection (const vector3 &p, const TRI &t)
static void pos_in_bp (vector3 &posOut, const NeuriteProjector::Neurite &neurite, uint32_t neuriteID, float &t, float &angle, float rad, std::vector< NeuriteProjector::BranchingRegion >::const_iterator &it, const IVertexGroup *parent, const NeuriteProjector *np)
static void pos_in_neurite (vector3 &posOut, const NeuriteProjector::Neurite &neurite, size_t neuriteID, float t, float angle, float rad)
static void pos_on_surface_tip (vector3 &posOut, const NeuriteProjector::Neurite &neurite, const IVertexGroup *parent, const NeuriteProjector *np, number rad)
static void post_assemble_loop (std::vector< TElemDisc * > vElemDisc)
static void PostProcessDistInfos (MultiGrid &mg, DistInfoSupplier &distInfos)
static void prep_assemble_loop (std::vector< TElemDisc * > vElemDisc)
static void print_mark (int &posNow, int length)
void PrintAngleHistogram (vector< number > &locAngles, number stepSize, ug::Table< std::stringstream > &outTable)
template<class TAAPosVRT >
void PrintAngleStatistics2d (Grid &grid, GridObjectCollection &goc, int level, TAAPosVRT &aaPos)
template<class TAAPosVRT >
void PrintAngleStatistics3d (Grid &grid, GridObjectCollection &goc, int level, TAAPosVRT &aaPos)
void PrintAspectRatioHistogram (vector< number > &locAspectRatios, number stepSize, ug::Table< std::stringstream > &outTable)
void PrintAttachmentInfo (Grid &grid)
void PrintCondUserDataValue (const UserData< TData, dim, bool > &ud, const MathVector< dim > &globIP, number time, int si)
void PrintDebugInfos (const vector< SweepLineVertex > &vrts, const list< SweepLineEdge > &edges)
void PrintDoFCount (const vector< DoFCount > &vDC, const string &sInfo, const string &sAlgebra, const string &sflags)
void PrintElementEdgeRatios (Grid &grid, TIterator elemsBegin, TIterator elemsEnd, TAAPos aaPos)
static void PrintElementEdgeRatios (TDomain &dom)
void PrintElementNumbers (const GridObjectCollection &goc)
void PrintGlobalLayout (const GlobalLayout &globalLayout, const char *name)
void PrintGridElementNumbers (Grid &grid)
void PrintGridElementNumbers (GridSubsetHandler &sh)
void PrintGridElementNumbers (MultiGrid &mg)
bool PrintLayouts (const HorizontalAlgebraLayouts &layout)
void PrintLUA ()
void PrintMaple (const matrix_type &mat, const char *name)
void PrintMatrix (const matrix_type &mat, const char *name)
void PrintQuadRule (const QuadratureRule< 2 > &q)
void PrintSimpleGrid (SimpleGrid &sg)
void PrintStorageType (const tvector &v)
void PrintSubdivisionVolumesRefinementMask ()
void PrintUserDataValue (const UserData< TData, dim > &ud, const MathVector< dim > &globIP, number time, int si)
void PrintVector (const T &v, std::string desc="")
void PrintVertexVolumeValence (MultiGrid &mg, SubsetHandler &sh, int subsetIndex)
template void ProjectHierarchyToSubdivisionLimit (MultiGrid &mg, APosition &aPos)
template void ProjectHierarchyToSubdivisionLimit (MultiGrid &mg, APosition1 &aPos)
template void ProjectHierarchyToSubdivisionLimit (MultiGrid &mg, APosition2 &aPos)
void ProjectHierarchyToSubdivisionLimit (MultiGrid &mg, TAPosition &aPos)
number ProjectPointToLine (vector_t &vOut, const vector_t &v, const vector_t &from, const vector_t &to)
void ProjectPointToPlane (vector_t &vOut, const vector_t &v, const vector_t &p, const vector_t &n)
number ProjectPointToRay (vector_t &vOut, const vector_t &v, const vector_t &from, const vector_t &dir)
bool ProjectPointToSurface (vector3 &vOut, const vector3 &v, const vector3 &n, TTriangleIterator trisBegin, TTriangleIterator trisEnd, TAAPosVRT &aaPos, bool compareNormals)
void ProjectToLayer (Grid &grid, const RasterLayers &layers, int layerIndex, Grid::VertexAttachmentAccessor< AVector3 > aaPos)
bool ProjectToLimitLoop (Grid &grid, APosition &aProjPos)
void ProjectToLimitPLoop (Grid &grid, TAVrtPos aPos, TAVrtPos aProjPos)
void ProjectToLimitSubdivBoundary (Grid &grid, TAVrtPos aPos, TAVrtPos aProjPos)
bool ProjectVerticesToCloseEdges (Grid &grid, GridObjectCollection elems, TAAPosVRT &aaPos, number snapThreshold)
bool ProjectVerticesToCloseEdges (Grid &grid, GridObjectCollection elems, TAPos &aPos, number snapThreshold)
bool ProjectVerticesToCloseFaces (Grid &grid, TObjectCollection &elems, TAPos &aPos, number snapThreshold)
static void ProjectVerticesToSphere (TDomain &dom, std::vector< number > center, number radius, number eps)
void Prolongate (GridFunction< TDomain, TAlgebra > &uFine, const GridFunction< TDomain, TAlgebra > &uCoarse)
void ProlongateElemwise (GridFunction< TDomain, TAlgebra > &uFine, const GridFunction< TDomain, TAlgebra > &uCoarse)
void ProlongateP1 (GridFunction< TDomain, TAlgebra > &uFine, const GridFunction< TDomain, TAlgebra > &uCoarse)
bool QuadDiagonalIsValid (const vector3 &c0, const vector3 &c1, const vector3 &c2, const vector3 &c3)
number QuadrilateralArea (const vector_t &p1, const vector_t &p2, const vector_t &p3, const vector_t &p4)
number QuadrilateralAspectRatio (FaceVertices *f, TAAPos &aaPos)
template bool QualityGridGeneration (Grid &, DelaunayInfo< Grid::VertexAttachmentAccessor< AVector3 > > &, number, int)
bool QualityGridGeneration (Grid &grid, DelaunayInfo< TAAPos > &info, number minAngle=0, int maxSteps=-1)
bool QualityGridGeneration (Grid &grid, TriIter trisBegin, TriIter trisEnd, TAAPos &aaPos, number minAngle=0, Grid::edge_traits::callback cbConstrainedEdge=ConsiderNone(), int maxSteps=-1)
TNumber rad_to_deg (TNumber rad)
static void RandomizeDomain (TDomain &dom, number dx, number dy, number dz)
void RangeStringToIndexList (std::vector< ind_t > &indsOut, const char *rangeString)
bool RayBoxIntersection (const vector_t &rayFrom, const vector_t &rayDir, const vector_t &boxMin, const vector_t &boxMax, number *tNearOut=NULL, number *tFarOut=NULL)
bool RayCylinderIntersection (number &tMinOut, number &tMaxOut, const vector3 &rayFrom, const vector3 &rayDir, const vector3 &cylCenter, const vector3 &cylAxis, number cylRadius)
bool RayElementIntersection (number &sminOut, number &smaxOut, const vector2 &from, const vector2 &dir, Edge *e, Grid &g, Grid::VertexAttachmentAccessor< AVector2 > aaPos, number sml=SMALL)
bool RayElementIntersection (number &sminOut, number &smaxOut, const vector2 &from, const vector2 &dir, Face *f, Grid &g, Grid::VertexAttachmentAccessor< AVector2 > aaPos, number sml=SMALL)
bool RayElementIntersection (number &sminOut, number &smaxOut, const vector3 &from, const vector3 &dir, Edge *e, Grid &g, Grid::VertexAttachmentAccessor< AVector3 > aaPos, number sml=SMALL)
bool RayElementIntersection (number &sminOut, number &smaxOut, const vector3 &from, const vector3 &dir, Face *f, Grid &g, Grid::VertexAttachmentAccessor< AVector3 > aaPos, number sml=SMALL)
bool RayElementIntersection (number &sminOut, number &smaxOut, const vector3 &from, const vector3 &dir, Volume *v, Grid &g, Grid::VertexAttachmentAccessor< AVector3 > aaPos, number sml=SMALL)
static bool RayElementIntersectionImpl (number &sminOut, number &smaxOut, const vector_t &from, const vector_t &dir, TElem *e, Grid &g, Grid::VertexAttachmentAccessor< Attachment< vector_t > > aaPos, number sml)
bool RayElementIntersections (std::vector< RayElemIntersectionRecord< typename tree_t::elem_t > > &intersectionsOut, const tree_t &tree, const typename tree_t::vector_t &rayFrom, const typename tree_t::vector_t &rayDir, const number small=1.e-12)
bool RayLineIntersection2d (vector_t &vOut, number &bcOut, number &tOut, const vector_t &p0, const vector_t &p1, const vector_t &vFrom, const vector_t &vDir, number sml=0)
bool RayPlaneIntersection (vector_t &vOut, number &tOut, const vector_t &rayFrom, const vector_t &rayDir, const vector_t &p, const vector_t &n)
bool RayRayIntersection2d (vector_t &vOut, number &t0Out, number &t1Out, const vector_t &p0, const vector_t &dir0, const vector_t &p1, const vector_t &dir1)
bool RayRayIntersection3d (vector3 &aOut, vector3 &bOut, const vector3 &p0, const vector3 &dir0, const vector3 &p1, const vector3 &dir1)
bool RayRayProjection (number &t1Out, number &t2Out, const vector_t &from1, const vector_t &dir1, const vector_t &from2, const vector_t &dir2)
int RaySphereIntersection (number &s1Out, number &s2Out, const vector_t &v, const vector_t &dir, const vector_t &center, number radius)
bool RayTriangleIntersection (vector_t &vOut, const vector_t &p0, const vector_t &p1, const vector_t &p2, const vector_t &vFrom, const vector_t &vDir)
bool RayTriangleIntersection (vector_t &vOut, number &bc1Out, number &bc2Out, number &tOut, const vector_t &p0, const vector_t &p1, const vector_t &p2, const vector_t &vFrom, const vector_t &vDir, const number small=SMALL)
std::istream & read_plain_txt (std::istream &inStream, ug::MathVector< 1 > &v)
std::istream & read_plain_txt (std::istream &inStream, ug::MathVector< 2 > &v)
std::istream & read_plain_txt (std::istream &inStream, ug::MathVector< 3 > &v)
std::istream & read_plain_txt (std::istream &inStream, ug::MathVector< 4 > &v)
UG_API bool ReadFile (const char *filename, std::vector< char > &file, bool bText)
bool ReadFile (const char *filename, vector< char > &file, bool bText)
void ReadFromFile (T &v, std::string filename)
static bool ReadGridHeader (GridHeader &gridHeader, BinaryBuffer &in)
static void ReadIndices (vector< int > &vIndsOut, char *buffer, const char *delim, bool newTokBuff=true)
static void ReadSelectionStatesFromStream (TElemIter iterBegin, TElemIter iterEnd, ISelector &sel, BinaryBuffer &in)
static void ReadSubsetIndicesFromStream (TElemIter iterBegin, TElemIter iterEnd, ISubsetHandler &sh, BinaryBuffer &in)
static bool ReadTetrahedrons (Grid &grid, ifstream &in, Grid::VertexAttachmentAccessor< APosition > &aaPos, int &lineCount)
static bool ReadTriangles (Grid &grid, ifstream &in, Grid::VertexAttachmentAccessor< APosition > &aaPos, int &lineCount)
bool ReadVector (std::string filename, vector_type &vec, int dim)
void ReceiveGlobalLayout (pcl::InterfaceCommunicator< IndexLayout > &comm, const std::vector< int > &srcprocs, GlobalLayout &globalMasterLayout, GlobalLayout &globalSlaveLayout)
void ReceiveMatrix (const matrix_type &A, matrix_type &M, IndexLayout &verticalMasterLayout, const std::vector< int > &srcprocs, ParallelNodes &PN)
void ReceiveOnInterfaces (pcl::InterfaceCommunicator< IndexLayout > &communicator, TPIDs &pids, IndexLayout &layout, TReceiveScheme &receiver)
MathVector< dim > ReferenceElementCenter (ReferenceObjectID roid)
MathVector< 1 > ReferenceElementCenter< 1 > (ReferenceObjectID roid)
MathVector< 2 > ReferenceElementCenter< 2 > (ReferenceObjectID roid)
MathVector< 3 > ReferenceElementCenter< 3 > (ReferenceObjectID roid)
int ReferenceElementDimension (ReferenceObjectID roid)
bool Refine (Grid &grid, Selector &sel, AInt &aInt, RefinementProjector *projector=NULL, bool useSnapPoints=false)
bool Refine (Grid &grid, Selector &sel, RefinementProjector *projector=NULL, bool useSnapPoints=false)
static bool Refine (std::vector< Volume * > &vNewVolumesOut, Vertex **ppNewVertexOut, Vertex **newEdgeVertices, Vertex **newFaceVertices, Vertex *newVolumeVertex, const Vertex &prototypeVertex, Vertex **vrts, int(*funcRefine)(int *, int *, bool &, vector3 *, bool *), vector3 *corners=NULL, bool *isSnapPoint=NULL)
void ReflectVectorAtPlane (vector_t &vReflectedOut, const vector_t &v, const vector_t &n, const vector_t &r0)
void release_mem (void *p)
void RemoveDoubles (Grid &grid, const TVrtIterator &iterBegin, const TVrtIterator &iterEnd, Attachment< MathVector< dim > > &aPos, number threshold)
void RemoveDoubles (Grid &grid, const TVrtIterator &iterBegin, const TVrtIterator &iterEnd, TAAPos aaPos, number threshold)
void RemoveDuplicates (Grid &grid, TElemIter elemsBegin, TElemIter elemsEnd)
static void RemoveEmptyInterfaces (typename GridLayoutMap::Types< TGeomObj >::Map &map)
bool RemoveInterface (TLayout &layout, int pid)
void RemoveInterfaces (TLayout &layout, std::vector< int > group)
void RemoveLowerDimSubsets (SubsetGroup &subsetGroup)
void RemoveWhitespaceFromString (std::string &string)
static bool ReorderCornersCCW (Vertex **cornersOut, Vertex **const cornersIn, int numCorners, int firstCorner)
string repeat (char c, int nr)
bool RepeatedEdgeExtrusion (Grid &grid, TIterator iterBegin, TIterator iterEnd, int numSteps, const ug::vector3 &stepDir)
bool RepeatedFaceExtrusion (Grid &grid, TIterator iterBegin, TIterator iterEnd, int numSteps, const ug::vector3 &stepDir)
bool RepeatedVertexExtrusion (Grid &grid, TIterator iterBegin, TIterator iterEnd, int numSteps, const ug::vector3 &stepDir)
string replace_chars (string &str, char cToR, char cNew)
UG_API std::string ReplaceAll (std::string target, const std::string &oldstr, const std::string &newstr)
string ReplaceAll (string target, const string &oldstr, const string &newstr)
static void ReplaceByConstrained (MultiGrid &mg, Edge *e)
static void ReplaceByConstrained (MultiGrid &mg, Face *f)
static void ReplaceByConstrained (MultiGrid &mg, Vertex *v)
static void ReplaceByConstraining (MultiGrid &, Vertex *)
static void ReplaceByConstraining (MultiGrid &mg, Edge *e)
static void ReplaceByConstraining (MultiGrid &mg, Face *f)
static void ReplaceByNormal (MultiGrid &mg, Edge *e)
static void ReplaceByNormal (MultiGrid &mg, Face *f)
static void ReplaceByNormal (MultiGrid &mg, Vertex *v)
Quadrilateral * ReplaceByQuadrilateral (Grid &g, Face *tri1, Face *tri2)
void ReplaceByQuadrilaterals_EdgeBased (Grid &g, edge_iter_t edgesBegin, edge_iter_t edgesEnd, TAAPos aaPos)
void ReplaceByQuadrilaterals_EdgeBasedNoSort (Grid &g, edge_iter_t edgesBegin, edge_iter_t edgesEnd)
void ReplaceByQuadrilaterals_FaceBased (Grid &g, face_iter_t facesBegin, face_iter_t facesEnd, TAAPos aaPos)
void ReplaceByQuadrilaterals_FaceBasedNoSort (Grid &g, face_iter_t facesBegin, face_iter_t facesEnd)
void ReplaceIndicesInLayout (IndexLayout &layout, const std::vector< int > &vMap)
void ReplaceLowValenceVertices (Grid &g, TVrtIter vrtsBegin, TVrtIter vrtsEnd, number maxSquaredHeightToBaseAreaRatio, TAAPos aaPos)
void ReplaceValence3Vertices (Grid &g, TVrtIter vrtsBegin, TVrtIter vrtsEnd, number maxSquaredHeightToBaseAreaRatio, TAAPos aaPos)
static std::ios_base & reset_floats (std::ios_base &o)
static void ResetSubsetIndices (Grid *pGrid, TAAInd &aaInd)
Vertex * ResolveEdgeEdgeIntersection (Grid &grid, Edge *e1, Edge *e2, TAAPosVRT &aaPos, number snapThreshold)
bool ResolveEdgeFaceIntersection (Grid &grid, Edge *e, Face *f, TAAPosVRT &aaPos, number snapThreshold)
bool ResolveTriangleIntersections (Grid &grid, TriangleIterator trisBegin, TriangleIterator trisEnd, number snapThreshold, TAPos &aPos)
Vertex * ResolveVertexEdgeIntersection (Grid &grid, Vertex *v, Edge *e, TAAPosVRT &aaPos, number snapThreshold)
bool ResolveVertexFaceIntersection (Grid &grid, Vertex *v, Face *f, TAAPosVRT &aaPos, number snapThreshold, std::vector< Face * > *pNewFacesOut)
void Restrict (GridFunction< TDomain, TAlgebra > &uCoarse, const GridFunction< TDomain, TAlgebra > &uFine)
void RestrictElemwise (GridFunction< TDomain, TAlgebra > &uCoarse, const GridFunction< TDomain, TAlgebra > &uFine)
void RestrictP1 (GridFunction< TDomain, TAlgebra > &uCoarse, const GridFunction< TDomain, TAlgebra > &uFine)
bool Retetrahedralize (Grid &grid, SubsetHandler &sh, ANumber &aVolumeConstraint, number quality=5, bool preserveBnds=false, bool preserveAll=false, APosition &aPos=aPosition, bool applyVolumeConstraint=true, int verbosity=0)
number ReturnValueToBool (lua_State *L, int index)
int ReturnValueToInteger (lua_State *L, int index)
number ReturnValueToNumber (lua_State *L, int index)
MathMatrix< 1, 1, T >::value_type RightInverse (MathMatrix< 1, 1 > &mOut, const MathMatrix< 1, 1 > &m)
MathMatrix< 2, 2, T >::value_type RightInverse (MathMatrix< 2, 2 > &mOut, const MathMatrix< 2, 2 > &m)
MathMatrix< 3, 3, T >::value_type RightInverse (MathMatrix< 3, 3 > &mOut, const MathMatrix< 3, 3 > &m)
MathMatrix< N, M, T >::value_type RightInverse (MathMatrix< N, M, T > &mOut, const MathMatrix< M, N, T > &m)
static void rot (number A[3][3], const number s, const number tau, const int i, const int j, const int k, const int l)
bool SameDimensionsInAllSubsets (const SubsetGroup &subsetGroup)
static void SaveCoarsenMarksToFile (ISelector &sel, const char *filename)
void SaveDomain (TDomain &domain, const char *filename)
template void SaveDomain< Domain1d > (Domain1d &domain, const char *filename)
template void SaveDomain< Domain2d > (Domain2d &domain, const char *filename)
template void SaveDomain< Domain3d > (Domain3d &domain, const char *filename)
static bool SaveGrid (Grid &grid, ISubsetHandler *psh, const char *filename, TAPos &aPos)
static bool SaveGrid3d (Grid &grid, ISubsetHandler *psh, const char *filename, APosition1 &aPos)
static bool SaveGrid3d (Grid &grid, ISubsetHandler *psh, const char *filename, APosition2 &aPos)
static bool SaveGrid3d (Grid &grid, ISubsetHandler *psh, const char *filename, APosition3 &aPos)
static bool SaveGrid3d_IMPL (Grid &grid, ISubsetHandler *pSH, const char *filename, AVector3 &aPos)
bool SaveGridHierarchyTransformed (MultiGrid &mg, const char *filename, number offset)
bool SaveGridHierarchyTransformed (MultiGrid &mg, ISubsetHandler &sh, const char *filename, number offset)
bool SaveGridLevel (MultiGrid &srcMG, ISubsetHandler &srcSH, int lvl, const char *filename, TAPos aPos)
bool SaveGridLevelToFile (MultiGrid &srcMG, ISubsetHandler &srcSH, int lvl, const char *filename)
bool SaveGridTo2DF (Grid &grid, const char *filename, ISubsetHandler *psh, AVector3 &aPos)
bool SaveGridToART (Grid &grid, const char *filename, ISubsetHandler *pSH=NULL, AVector3 &aPos=aPosition)
bool SaveGridToELE (Grid &grid, const char *filename, ISubsetHandler *pSH, APosition &aPos, ANumber *paVolumeConstraint)
template bool SaveGridToFile (Grid &, const char *, AVector1 &)
template bool SaveGridToFile (Grid &, const char *, AVector2 &)
template bool SaveGridToFile (Grid &, const char *, AVector3 &)
template bool SaveGridToFile (Grid &, ISubsetHandler &, const char *, AVector1 &)
template bool SaveGridToFile (Grid &, ISubsetHandler &, const char *, AVector2 &)
template bool SaveGridToFile (Grid &, ISubsetHandler &, const char *, AVector3 &)
bool SaveGridToFile (Grid &grid, const char *filename)
bool SaveGridToFile (Grid &grid, const char *filename, TAPos &aPos)
bool SaveGridToFile (Grid &grid, ISubsetHandler &sh, const char *filename)
bool SaveGridToFile (Grid &grid, ISubsetHandler &sh, const char *filename, TAPos &aPos)
bool SaveGridToLGB (Grid &grid, const char *filename, ISubsetHandler **ppSH, int numSHs, ISelector **ppSel, int numSels, ProjectionHandler *pPH, APosition aPos)
bool SaveGridToLGB (Grid &grid, const char *filename, ISubsetHandler **ppSH, int numSHs, ProjectionHandler *pPH, APosition aPos)
bool SaveGridToNCDF (Grid &grid, const char *filename, ISubsetHandler *pSH, APosition aPos)
bool SaveGridToOBJ (Grid &grid, const char *filename, AVector3 &aPos=aPosition, AVector2 *paTexCoord=NULL, ISubsetHandler *pSubsetHandler=NULL, std::vector< OBJMaterial > *pvMaterials=NULL)
bool SaveGridToSTL (Grid &grid, const char *filename, ISubsetHandler *pSH, AVector3 &aPos)
bool SaveGridToTXT (Grid &grid, const char *filename, AVector3 &aPos=aPosition)
bool SaveGridToUGX (Grid &grid, ISubsetHandler &sh, const char *filename)
bool SaveGridToUGX (Grid &grid, ISubsetHandler &sh, const char *filename, TAPosition &aPos)
bool SaveGridToVTU (Grid &grid, ISubsetHandler *psh, const char *filename, TAPosition &aPos)
void SaveMatrixForConnectionViewer (TGridFunction &u, MatrixOperator< typename TGridFunction::algebra_type::matrix_type, typename TGridFunction::vector_type > &A, const char *filename)
void SaveMatrixToMTX (const char *filename, MatrixOperator< CPUAlgebra::matrix_type, CPUAlgebra::vector_type > &A, std::string comment="%Generated with ug4.")
bool SaveParallelGridLayout (MultiGrid &mg, const char *filename, number offset=0.1)
static bool SavePartitionMap (PartitionMap &pmap, TDomain &domain, const char *filename)
bool SavePartitionMapToFile (PartitionMap &pm, const char *filename, TAPos &aPos)
bool SaveSurfaceViewTransformed (MultiGrid &mg, const SurfaceView &sv, const char *filename, number offset=0.1)
void SaveToFile (const T &v, std::string filename)
void SaveVectorCSV (TGridFunction &b, const char *filename)
void SaveVectorDiffForConnectionViewer (TGridFunction &b, TGridFunction &bCompare, const char *filename)
void SaveVectorDiffForConnectionViewer (TGridFunction &u, TGridFunction &compareVec, MatrixOperator< typename TGridFunction::algebra_type::matrix_type, typename TGridFunction::vector_type > &A, const char *filename)
void SaveVectorForConnectionViewer (TGridFunction &b, const char *filename)
void SaveVectorForConnectionViewer (TGridFunction &u, MatrixOperator< typename TGridFunction::algebra_type::matrix_type, typename TGridFunction::vector_type > &A, const char *filename)
void ScaleDomain (TDomain &dom, const vector3 &center, const vector3 &scale)
void ScaleDomain (TDomain &dom, ISelector &sel, const vector3 &center, const vector3 &scale)
static void ScaleDomain (TDomain &dom, number sx, number sy, number sz)
void ScaleDomainSqrtWeighting (TDomain &dom, ISelector &sel, const vector3 &center, const vector3 &scale)
void ScaleDomainSquaredWeighting (TDomain &dom, ISelector &sel, const vector3 &center, const vector3 &scale)
void ScaleDomainWeighting (TDomain &dom, ISelector &sel, const vector3 &center, const vector3 &scale)
void ScaleGF (SmartPtr< TGridFunction > scaledVecOut, ConstSmartPtr< TGridFunction > vecIn, const std::vector< number > &scalingFactors)
static void ScaleGFOnElems (ConstSmartPtr< DoFDistribution > dd, SmartPtr< TGridFunction > vecOut, ConstSmartPtr< TGridFunction > vecIn, const std::vector< number > &vScale)
void ScaleLayoutValues (TVector *pVec, const IndexLayout &layout, number scale)
void ScaleRow (TSparseMatrix &A, size_t i, number fac)
void ScaleSparseMatrixCommon (TSparseMatrix &A, double d)
std::string scientificStr (double d, size_t width)
bool SCVFofSCVRayIntersection (size_t &sideOut, number &bc, MathVector< TWorldDim > &GlobalIntersectionPointOut, MathVector< TDim > &LocalIntersectionPoint, const MathVector< TWorldDim > &Root, const MathVector< TWorldDim > &Direction, bool bPositiv, const MathVector< TWorldDim > *vCornerCoords)
void SelectAreaBoundary (ISelector &sel, const TIter begin, const TIter end)
void SelectAssociated (ISelector &sel, TIterator begin, TIterator end, ISelector::status_t status=ISelector::SELECTED)
static void SelectAssociatedConstrainedElements (MGSelector &msel, ISelector::status_t status=ISelector::SELECTED)
void SelectAssociatedEdges (TSelector &sel, TElemIterator elemsBegin, TElemIterator elemsEnd, ISelector::status_t status=ISelector::SELECTED)
void SelectAssociatedElements (ISelector &sel, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces)
void SelectAssociatedFaces (TSelector &sel, TElemIterator elemsBegin, TElemIterator elemsEnd, ISelector::status_t status=ISelector::SELECTED)
void SelectAssociatedGenealogy (MGSelector &msel, bool selectAssociatedElements)
void SelectAssociatedGridObjects (TSelector &sel, ISelector::status_t status)
template void SelectAssociatedGridObjects< MGSelector > (MGSelector &sel, ISelector::status_t status)
template void SelectAssociatedGridObjects< Selector > (Selector &sel, ISelector::status_t status)
static void SelectAssociatedSides (MGSelector &msel, TElem *e, ISelector::status_t status=ISelector::SELECTED)
void SelectAssociatedVertices (TSelector &sel, TElemIterator elemsBegin, TElemIterator elemsEnd, ISelector::status_t status=ISelector::SELECTED)
void SelectAssociatedVolumes (TSelector &sel, TElemIterator elemsBegin, TElemIterator elemsEnd, ISelector::status_t status=ISelector::SELECTED)
void SelectBoundaryElements (ISelector &sel, TElemIterator elemsBegin, TElemIterator elemsEnd)
static void SelectChildrenOfSelectedShadowRimEdges (MGSelector &msel, ISelector::status_t status=ISelector::SELECTED)
static void SelectChildrenOfSelectedShadowRimFaces (MGSelector &msel, ISelector::status_t status=ISelector::SELECTED)
static void SelectChildrenOfSelectedShadowVertices (MGSelector &msel, ISelector::status_t status=ISelector::SELECTED)
void SelectCreaseEdges (ISelector &sel, TEdgeIterator edgesBegin, TEdgeIterator edgesEnd, number minAngle, APosition aVrtPos, bool ignoreBoundaryEdges=true, ISelector::status_t state=ISelector::SELECTED)
void SelectDomainElements (ISelector &sel, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVolumes)
void SelectDomainSubset (ISelector &sel, TDomain &dom, int subsetIndex, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVolumes)
void SelectEdgesByDirection (Selector &sel, TAAPos &aaPos, const vector3 &dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
void SelectElementsByIndex (ISelector &sel, const std::vector< size_t > &inds)
void SelectElementsByIndex (ISelector &sel, const std::vector< size_t > &vrtInds, const std::vector< size_t > &edgeInds, const std::vector< size_t > &faceInds, const std::vector< size_t > &volInds)
template void SelectElementsByIndex< Edge > (ISelector &sel, const std::vector< size_t > &inds)
template void SelectElementsByIndex< Face > (ISelector &sel, const std::vector< size_t > &inds)
template void SelectElementsByIndex< Vertex > (ISelector &sel, const std::vector< size_t > &inds)
template void SelectElementsByIndex< Volume > (ISelector &sel, const std::vector< size_t > &inds)
static void SelectElementsForTargetPartition (MGSelector &msel, SubsetHandler &shPartition, int partitionIndex, bool partitionForLocalProc, bool createVerticalInterfaces)
void SelectInnerElements (ISelector &sel, TElemIterator elemsBegin, TElemIterator elemsEnd)
void SelectInnerSelectionEdges (TSelector &sel)
template void SelectInnerSelectionEdges< MGSelector > (MGSelector &)
template void SelectInnerSelectionEdges< Selector > (Selector &)
void SelectInnerSelectionFaces (TSelector &sel)
template void SelectInnerSelectionFaces< MGSelector > (MGSelector &)
template void SelectInnerSelectionFaces< Selector > (Selector &)
void SelectInnerSelectionVertices (TSelector &sel)
template void SelectInnerSelectionVertices< MGSelector > (MGSelector &)
template void SelectInnerSelectionVertices< Selector > (Selector &)
void SelectInterfaceElements (ISelector &sel, ISubsetHandler &sh, const TIter begin, const TIter end, bool regardSelectedNbrsOnly=false)
void SelectionFill (Selector &sel, typename Grid::traits< typename TGeomObj::side >::callback cbRegionBoundary)
template void SelectionFill< Edge > (Selector &, Grid::vertex_traits::callback)
template void SelectionFill< Face > (Selector &, Grid::edge_traits::callback)
template void SelectionFill< Volume > (Selector &, Grid::face_traits::callback)
void SelectKinkVertices (Grid &grid, TVrtIter vrtsBegin, TVrtIter vrtsEnd, number thresholdAngle, bool selectDarts, TAAPos aaPos, Grid::edge_traits::callback cbConsiderEdge=ConsiderAll())
void SelectKinkVertices (Selector &sel, TVrtIter vrtsBegin, TVrtIter vrtsEnd, number thresholdAngle, bool selectDarts, TAAPos aaPos, Grid::edge_traits::callback cbConsiderEdge)
void SelectLinkedElements (ISelector &sel, typename Grid::traits< TElem >::callback cbIsSelectable=ConsiderAll(), typename Grid::traits< typename TElem::side >::callback cbIsTraversable=ConsiderAll())
void SelectLinkedFlatAndDegeneratedFaces (Selector &sel, number maxDeviationAngle, bool ignoreOrientation=false, bool stopAtSelectedEdges=false, number degThreshold=SMALL, APosition &aPos=aPosition)
void SelectLinkedFlatFaces (Selector &sel, number maxDeviationAngle, bool ignoreOrientation=false, bool stopAtSelectedEdges=false, APosition &aPos=aPosition)
void SelectNonShadowsAdjacentToShadowsOnLevel (BoolMarker &sel, const SurfaceView &surfView, int level)
static void SelectParents (MultiGrid &mg, MGSelector &msel, TIterator iterBegin, TIterator iterEnd)
bool SelectRegion (Selector &sel, const typename TAAPos::ValueType &p, TAAPos &aaPos, typename Grid::traits< typename TGeomObj::side >::callback cbRegionBoundary)
static void SelectSelectedRootElementsAsVSlaves (MGSelector &msel)
void SelectShortPolychains (ISelector &sel, number maxLength, bool closedChainsOnly, TAAPos aaPos)
void SelectSmoothEdgePath (Selector &sel, number thresholdDegree, number normalWeight, bool stopAtSelVrts=true, APosition &aPos=aPosition)
void SelectSubset (ISelector &sel, const ISubsetHandler &sh, int si, ISelector::status_t status)
void SelectSubsetEdgesByDirection (Selector &sel, SubsetHandler &sh, int subsetIndex, TAAPos &aaPos, const vector3 &dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
void SelectSubsetElements (ISelector &sel, ISubsetHandler &sh, int subsetIndex, ISelector::status_t status=ISelector::SELECTED)
static void SelectUnselectedRootElementsAsVMasters (MGSelector &msel)
void SendGlobalLayout (pcl::InterfaceCommunicator< IndexLayout > &comm, const GlobalLayout &globalMasterLayout, const GlobalLayout &globalSlaveLayout, int pid)
void SendMatrix (const matrix_type &A, IndexLayout &verticalSlaveLayout, int destproc, ParallelNodes &PN)
void SendOnInterfaces (pcl::InterfaceCommunicator< IndexLayout > &communicator, TPIDs &pids, IndexLayout &layout, TSendingScheme &sender)
void SeparateFaceSubsetsByNormal (Grid &grid, SubsetHandler &sh, APosition aPos=aPosition, ANormal *paNorm=NULL, int applyToSubset=-2)
void SeparateFaceSubsetsByNormal (Grid &grid, SubsetHandler &sh, std::vector< vector3 > vNormals, APosition aPos=aPosition, ANormal *paNorm=NULL, int applyToSubset=-2)
bool SeparateRegions (Grid &grid, ISubsetHandler &shVolsOut, const ISubsetHandler &shFaces, const MarkerPointManager &mpm, int firstSubsetIndex)
void SeparateSubsetsByLowerDimSelection (Grid &grid, SubsetHandler &sh, Selector &sel, bool appendAtEnd=false)
void SeparateSubsetsByLowerDimSeparators (Grid &grid, SubsetHandler &sh, bool appendAtEnd, boost::function< bool(typename TElem::lower_dim_base_object *)> cbIsSeparator)
void SeparateSubsetsByLowerDimSubsets (Grid &grid, SubsetHandler &sh, bool appendAtEnd=false)
void SequentialSubspaceCorrectionLoop (const typename TAlgebra::matrix_type &A, GridFunction< TDomain, TAlgebra > &c, const typename TAlgebra::vector_type &d, number omega_relax, ILocalSubspace< TDomain, TAlgebra, TGroupObj > &subspace, TGroupObjIter objIterBegin, TGroupObjIter objIterEnd)
void SequentialSubspaceCorrectionLoopBackward (const typename TAlgebra::matrix_type &A, GridFunction< TDomain, TAlgebra > &c, const typename TAlgebra::vector_type &d, number omega_relax, ILocalSubspace< TDomain, TAlgebra, TGroupObj > &subspace, typename GridFunction< TDomain, TAlgebra >::template traits< TGroupObj >::const_iterator objIterBegin, typename GridFunction< TDomain, TAlgebra >::template traits< TGroupObj >::const_iterator objIterEnd)
void Serialize (std::ostream &buff, const DenseMatrix< VariableArray2< T > > &mat)
void Serialize (std::ostream &buff, const DenseVector< FixedArray1< number, n > > &vec)
void Serialize (std::ostream &buff, const DenseVector< VariableArray1< T > > &vec)
void Serialize (TIStream &buf, const std::vector< bool > &vec)
void Serialize (TOStream &buf, const IndexLayout &layout)
void Serialize (TOStream &buf, const IndexLayout::Interface &interface)
void Serialize (TOStream &buf, const ParallelVector< T > &v)
void Serialize (TOStream &buf, const pcl::InterfaceCommunicator< IndexLayout > &ic)
void Serialize (TOStream &buf, const pcl::ProcessCommunicator &ic)
void Serialize (TOStream &buf, const std::map< Key, T > &m)
void Serialize (TOStream &buf, const std::pair< T1, T2 > &v)
void Serialize (TOStream &buf, const std::set< T > &m)
void Serialize (TOStream &buf, const std::string &str)
void Serialize (TOStream &buf, const std::vector< bool >::reference &boolRef)
void Serialize (TOStream &buf, const std::vector< T > &vec)
void Serialize (TOStream &buf, const Variant &v)
void Serialize (TOStream &buf, const Vector< TValueType > &v)
void Serialize (TStream &buf, const T &val)
void Serialize (TStream &out, const MathVector< N, T > &val)
bool SerializeAttachment (Grid &grid, TAttachment &attachment, BinaryBuffer &out)
bool SerializeAttachment (Grid &grid, TAttachment &attachment, typename geometry_traits< TElem >::iterator iterBegin, typename geometry_traits< TElem >::iterator iterEnd, BinaryBuffer &out)
void SerializeGlobalLayout (BinaryBuffer &stream, const GlobalLayout &globalLayout)
bool SerializeGridElements (Grid &grid, BinaryBuffer &out)
bool SerializeGridElements (Grid &grid, GridObjectCollection goc, AInt &aIntVRT, BinaryBuffer &out)
bool SerializeGridElements (Grid &grid, GridObjectCollection goc, BinaryBuffer &out)
void SerializeInterface (BinaryBuffer &stream, const IndexLayout::Interface &interface, const TLocalToGlobal &localToGlobal)
void SerializeLayout (BinaryBuffer &stream, const IndexLayout &layout, const TLocalToGlobal &localToGlobal)
void SerializeMatrix (TOStream &buf, const TSparseMatrix &A)
bool SerializeMultiGridElements (MultiGrid &mg, BinaryBuffer &out)
bool SerializeMultiGridElements (MultiGrid &mg, GridObjectCollection goc, BinaryBuffer &out)
bool SerializeMultiGridElements (MultiGrid &mg, GridObjectCollection goc, MultiElementAttachmentAccessor< AInt > &aaInt, BinaryBuffer &out, MultiElementAttachmentAccessor< AGeomObjID > *paaID=NULL)
void SerializeParallelData (TOStream &buf, T &t)
void SerializeProjectionHandler (BinaryBuffer &out, ProjectionHandler &ph)
void SerializeProjector (BinaryBuffer &out, RefinementProjector &proj)
size_t SerializerGetLastID ()
void SerializeRow (BinaryBuffer &stream, const matrix_type &mat, size_t localRowIndex, ParallelNodes &PN)
bool SerializeSelector (Grid &grid, ISelector &sel, BinaryBuffer &out)
bool SerializeSelector (Grid &grid, ISelector &sel, GridObjectCollection goc, BinaryBuffer &out)
bool SerializeSubsetHandler (Grid &grid, ISubsetHandler &sh, BinaryBuffer &out)
bool SerializeSubsetHandler (Grid &grid, ISubsetHandler &sh, GridObjectCollection goc, BinaryBuffer &out)
void SerializeUniquePart (TOStream &buf, const ParallelMatrix< T > &A)
void SerializeUniquePart (TOStream &buf, const ParallelVector< TValueType > &v)
void SetAppsPath (const char *c_strApps)
void SetAppsPath (const std::string &strApps)
void SetAttachmentValues (TAttachmentAccessor &aaVal, TIter elemsBegin, TIter elemsEnd, const TVal &val)
void SetBoundaryRefinementRule (GlobalBoundaryRefinementRule refRule)
void SetCol (TSparseMatrix &A, size_t i, size_t alpha, number val=0.0)
void SetDirichletRow (TMatrix &mat, const DoFIndex &ind)
void SetDirichletRow (TSparseMatrix &A, const std::vector< size_t > vIndex)
void SetDirichletRow (TSparseMatrix &A, size_t i)
void SetDirichletRow (TSparseMatrix &A, size_t i, size_t alpha)
static void SetFrequency (const std::string &csvFile)
void SetInterfaceValues (TVector *pVec, const IndexLayout::Interface &interface, typename TVector::value_type val)
void SetInterpolation (TMatrix &A, std::vector< size_t > &constrainedIndex, std::vector< std::vector< size_t > > &vConstrainingIndex, bool assembleLinearProblem=true)
void SetLagrangeEdgeLocalDoFs (std::vector< LocalDoF > &vLocalDoF, const ReferenceElement &rRef, const size_t p)
void SetLagrangeEdgeMultiIndex (MathVector< TRefElem::dim, int > *vMultiIndex, const TRefElem &rRef, size_t p, size_t &index)
void SetLagrangeFaceLocalDoFs (std::vector< LocalDoF > &vLocalDoF, const ReferenceElement &rRef, const size_t p)
void SetLagrangeFaceMultiIndex (MathVector< TRefElem::dim, int > *vMultiIndex, const TRefElem &rRef, size_t p, size_t &index)
void SetLagrangeLocalDoFs (std::vector< LocalDoF > &vLocalDoF, const ReferenceElement &rRef, const size_t p)
void SetLagrangeMultiIndex (MathVector< TRefElem::dim, int > *vMultiIndex, const TRefElem &rRef, size_t p)
void SetLagrangeVertexLocalDoFs (std::vector< LocalDoF > &vLocalDoF, const ReferenceElement &rRef, const size_t p)
void SetLagrangeVertexMultiIndex (MathVector< TRefElem::dim, int > *vMultiIndex, const TRefElem &rRef, size_t p, size_t &index)
void SetLagrangeVolumeLocalDoFs (std::vector< LocalDoF > &vLocalDoF, const ReferenceElement &rRef, const size_t p)
void SetLagrangeVolumeMultiIndex (MathVector< TRefElem::dim, int > *vMultiIndex, const TRefElem &rRef, size_t p, size_t &index)
void SetLayoutValues (TVector *pVec, const IndexLayout &layout, typename TVector::value_type val)
bool SetLocalMatrix (TGlobalMatrix &mat, const TLocalMatrix &localMat)
bool SetLocalMatrix (TGlobalMatrix &mat, TLocalMatrix &localMat, const size_t *rowIndices, const size_t *colIndices)
static void SetMatrixAsPermutation (TMatrix &PA, const TMatrix &A, const std::vector< size_t > &perm)
void SetParallelData (T &t, IndexLayout &masterLayout, IndexLayout &slaveLayout, pcl::InterfaceCommunicator< IndexLayout > &ic, pcl::ProcessCommunicator &pc)
void SetPluginPath (const char *c_strPlugin)
void SetPluginPath (const std::string &strPlugin)
void SetRootPath (const char *c_strRoot)
void SetRootPath (const std::string &strRoot)
void SetRow (TMatrix &mat, const DoFIndex &ind, number val=0.0)
void SetRow (TSparseMatrix &A, size_t i, number val=0.0)
void SetRow (TSparseMatrix &A, size_t i, size_t alpha, number val=0.0)
void SetScriptPath (const char *c_strScript)
void SetScriptPath (const std::string &strScript)
static void SetShinyCallLoggingMaxFrequency (int maxFreq)
void SetSize (DenseMatrix< T > &t, size_t a, size_t b)
void SetSize (DenseVector< T > &t, size_t a)
void SetSize (number &d, size_t a)
void SetSize (number &d, size_t a, size_t b)
void SetSize (T &t, size_t a)
void SetSize (T &t, size_t a, size_t b)
void SetSmoothSubdivisionVolumesBoundaryRefinementRule (std::string bndRefRule)
void SetTetRefinementRule (std::string ruleName)
static void SetVectorAsPermutation (TVector &Pv, const TVector &v, const std::vector< size_t > &perm)
void sgetrf_ (lapack_int *m, lapack_int *n, lapack_float *pColMajorMatrix, lapack_int *lda, lapack_int *ipiv, lapack_int *info)
void sgetri_ (lapack_int *n, lapack_float *pColMajorMatrix, lapack_int *lda, const lapack_int *ipiv, lapack_float *pWork, lapack_int *worksize, lapack_int *info)
void sgetrs_ (char *trans, lapack_int *n, lapack_int *nrhs, const lapack_float *pColMajorMatrix, lapack_int *lda, const lapack_int *ipiv, lapack_float *b, lapack_int *ldb, lapack_int *info)
void sgs_step (const Matrix_type &A, Vector_type &c, const Vector_type &d, const number relaxFactor)
bool sgs_step (const Matrix_type &A, Vector_type &x, const Vector_type &b)
number ShapeQualityDegree (SimpleGrid &sg)
number ShapeQualityDegree (SimpleGrid &sg, int triIndex)
void ShapesAtGlobalPosition (std::vector< std::vector< number > > &vvShape, const std::vector< MathVector< dim > > &vGlobPos, const ReferenceObjectID roid, const std::vector< MathVector< dim > > &vCornerCoord, const LFEID &lfeID)
void ShapesAtGlobalPosition (std::vector< std::vector< number > > &vvShape, const std::vector< MathVector< TDomain::dim > > &vGlobPos, GridObject *elem, const TDomain &domain, const LFEID &lfeID)
void ShapesAtGlobalPositionElem (std::vector< std::vector< number > > &vvShape, const std::vector< MathVector< dim > > &vGlobPos, const ReferenceObjectID roid, const std::vector< MathVector< dim > > &vCornerCoord, const LFEID &lfeID)
void ShapesAtGlobalPositionVertex (std::vector< std::vector< number > > &vvShape, const std::vector< MathVector< dim > > &vGlobPos, const LFEID &lfeID)
void ShinyCallLoggingEnd ()
void ShinyCallLoggingStart ()
void SideNormal (MathVector< TWorldDim > &normalOut, int side, const MathVector< TWorldDim > *vCornerCoords)
void SideNormal (ReferenceObjectID roid, MathVector< dim > &normalOut, int side, const MathVector< dim > *vCornerCoords)
void SideNormal< 1 > (ReferenceObjectID roid, MathVector< 1 > &normalOut, int side, const MathVector< 1 > *vCornerCoords)
void SideNormal< 2 > (ReferenceObjectID roid, MathVector< 2 > &normalOut, int side, const MathVector< 2 > *vCornerCoords)
void SideNormal< 3 > (ReferenceObjectID roid, MathVector< 3 > &normalOut, int side, const MathVector< 3 > *vCornerCoords)
void SimplifyPolylines (Grid &grid, TEdgeIter edgesBegin, TEdgeIter edgesEnd, number curvatureThreshold, TAAPos aaPos)
void SimplifySmoothedPolylines (Grid &grid, TEdgeIter edgesBegin, TEdgeIter edgesEnd, number curvatureThreshold, TAAPos aaPos, number smoothingAlpha, int smoothingIterations)
void SlopeSmooth (Grid &grid, TIterator vrtsBegin, TIterator vrtsEnd, AAPosVRT &aaPos, number alpha, const vector3 &up, int numIterations)
void SnapMarkerPointToGridVertex (MarkerPoint &markerInOut, Grid &grid, number normalOffset, Grid::VertexAttachmentAccessor< APosition > &aaPos, Grid::VertexAttachmentAccessor< ANormal > *paaNorm=NULL)
void SnapToHorizontalRaster (Grid &grid, const RasterLayers &layers, Grid::VertexAttachmentAccessor< AVector3 > aaPos)
UG_API std::string SnipString (const std::string &str, size_t totalSize, size_t replaceLast=0, const char replace='.')
string SnipString (const string &str, size_t totalSize, size_t replaceLast, const char replace)
UG_API std::string SnipStringFront (const std::string &str, size_t totalSize, size_t replaceFront=0, const char replace='.')
string SnipStringFront (const string &str, size_t totalSize, size_t replaceFirst, const char replace)
bool SolveDeficit (DenseMatrix< VariableArray2< double > > &A, DenseVector< VariableArray1< double > > &x, DenseVector< VariableArray1< double > > &rhs, double deficitTolerance)
bool SolveLU (const DenseMatrix< matrix_t > &A, DenseVector< vector_t > &x, const size_t *pInterchange)
void SolveTensorMatrixEquation (MathMatrix< TDim, TDim > &X, const MathTensor4< TDim, TDim, TDim, TDim > &A, const MathMatrix< TDim, TDim > &rhs)
bool SortDD (SmartPtr< DoFDistribution > spDD1, SmartPtr< DoFDistribution > spDD2)
void SpacialVertexSort (std::multimap< number, Vertex * > &vrtsOut, const TVrtIter vrtsBegin, const TVrtIter vrtsEnd, const typename TAAPos::ValueType &rayFrom, const typename TAAPos::ValueType &rayDir, TAAPos aaPos, bool clearContainer=true)
static void split_parameters (ParameterList *pParamList, const char *pParamString)
void split_parameters (std::vector< std::string > &paramsOut, char *strParams, const char *delims=" ")
void SplitAddRhs_OneSide (TVector &rhs, std::vector< size_t > &constrainedIndex, std::vector< std::vector< size_t > > &vConstrainingIndex)
void SplitAddRhs_Symmetric (TVector &rhs, std::vector< size_t > &constrainedIndex, std::vector< std::vector< size_t > > &vConstrainingIndex)
void SplitAddRow_OneSide (TMatrix &A, std::vector< size_t > &constrainedIndex, std::vector< std::vector< size_t > > &vConstrainingIndex)
void SplitAddRow_Symmetric (TMatrix &A, std::vector< size_t > &constrainedIndex, std::vector< std::vector< size_t > > &vConstrainingIndex)
TVertex * SplitEdge (Grid &destGrid, Grid &srcGrid, Edge *e, AVertex *paAssociatedVertices=NULL, bool bConservative=false)
TVertex * SplitEdge (Grid &grid, Edge *e, bool bConservative=false)
bool SplitEdge (SimpleGrid &sg)
bool SplitIrregularManifoldSubset (SubsetHandler &sh, int srcIndex, int targetIndex, bool strictSplitting=false)
bool SplitIrregularPolyChain (SubsetHandler &sh, int srcIndex, int targetIndex)
void SplitOctahedronToTetrahedrons (Grid &grid, Octahedron *oct, Volume *parentVol, std::vector< Tetrahedron * > &vTetsOut, int bestDiag)
TNumber sq (TNumber val)
number SqNormOfChebyshev1Poly (size_t k)
number SqNormOfChebyshev2Poly (size_t k)
number SqNormOfLegendrePoly (size_t k)
MathMatrix< 0, 0, T >::value_type SqrtGramDeterminant (const MathMatrix< 0, 0, T > &m)
MathMatrix< 0, M, T >::value_type SqrtGramDeterminant (const MathMatrix< 0, M, T > &m)
MathMatrix< 1, 1, T >::value_type SqrtGramDeterminant (const MathMatrix< 1, 1, T > &m)
MathMatrix< 2, 2, T >::value_type SqrtGramDeterminant (const MathMatrix< 2, 2, T > &m)
MathMatrix< 3, 3, T >::value_type SqrtGramDeterminant (const MathMatrix< 3, 3, T > &m)
MathMatrix< N, 0, T >::value_type SqrtGramDeterminant (const MathMatrix< N, 0, T > &m)
MathMatrix< N, M, T >::value_type SqrtGramDeterminant (const MathMatrix< N, M, T > &m)
UG_API bool StartsWith (const std::string &str, const std::string &search)
bool StartsWith (const string &str, const string &begin)
number StdFuncIntegralOnVertex (SmartPtr< TGridFunction > spGridFct, size_t fct, int si)
number StdFuncIntegralOnVertex (TGridFunction &gridFct, size_t fct, int si)
bool STLFileHasASCIIFormat (const char *filename)
static RefinementMark StringToRefinementMark (std::string markType)
void SubMult (A &dest, const A &vec, const double &b)
void SubMult (A &dest, const B &b, const C &vec)
void SubMult (DenseMatrix< A > &dest, const double &alpha, const DenseMatrix< B > &mat)
void SubMult (DenseVector< A > &dest, const DenseMatrix< B > &mat, const DenseVector< C > &vec)
void SubMult (DenseVector< A > &dest, const double &b, const DenseVector< B > &vec)
void SubMult (number &dest, const number &b, const number &vec)
bool SubsetIsRegularGrid (const ISubsetHandler &ish, int si)
bool SubsetIsRegularGrid (const MGSubsetHandler &sh, int si)
bool SubsetIsRegularGrid (const SubsetHandler &sh, int si)
void SubtractValueFromComponent (SmartPtr< TGridFunction > spGF, size_t fct, number sub)
DenseMatrix< T1 >::value_type Sum1Mat1 (const DenseMatrix< T1 > &mat)
double Sum1Mat1 (double d)
number SumGFValuesAt (TGridFunction *u, const char *fct_names)
number SumGFValuesAt (TGridFunction *u, const char *fct_names, const char *subset_names)
number SumGFValuesAt (TGridFunction *u, size_t fct)
number SumGFValuesAt (TGridFunction *u, size_t fct, SubsetGroup &ssGroup)
Edge * SwapEdge (Grid &grid, Edge *e)
bool SwapEdge (SimpleGrid &sg)
bool SweepLine_CreateMonotones (vector< SweepLineVertex > &vrts, list< SweepLineEdge > &edges)
bool SweepLineEdgeIntersectsSweepLine (number &xOut, const SweepLineEdge &edge, number sweepLineY)
static void SynchronizeAttachedGlobalAttachments (Grid &g, const pcl::ProcessCommunicator &procComm)
static void SynchronizeDistInfos (MultiGrid &mg, DistInfoSupplier &distInfos)
void TangentialSmooth (Grid &g, TVrtIter vrtsBegin, TVrtIter vrtsEnd, TAAPos3 aaPos, number alpha, size_t numIterations)
void TangentialSmoothSimple (Grid &g, TVrtIter vrtsBegin, TVrtIter vrtsEnd, TAAPos3 aaPos, number alpha, size_t numIterations)
const double & te_transpose (const double &t)
TE_TRANSPOSED< T > te_transpose (const T &t)
double & te_transpose (double &t)
void Tens2ToVec (DenseVector< FixedArray1< number, TDimSQ > > &vec, const MathMatrix< TDim, TDim > &tens2)
void Tens4Add (MathTensor4< TDim, TDim, TDim, TDim > &tens4_out, const MathTensor4< TDim, TDim, TDim, TDim > &tens4a, const MathTensor4< TDim, TDim, TDim, TDim > &tens4b)
void Tens4Contract (MathMatrix< TDim, TDim > &tens2_out, const MathTensor4< TDim, TDim, TDim, TDim > &tens4, const MathMatrix< TDim, TDim > &tens2)
void Tens4Contract (MathTensor4< TDim, TDim, TDim, TDim > &tens4_out, const MathTensor4< TDim, TDim, TDim, TDim > &tens4a, const MathTensor4< TDim, TDim, TDim, TDim > &tens4b)
void Tens4Contract (MathTensor4< TDim, TDim, TDim, TDim > &tens4_out, const MathTensor4< TDim, TDim, TDim, TDim > &tens4a, const MathTensor4< TDim, TDim, TDim, TDim > &tens4b, const MathTensor4< TDim, TDim, TDim, TDim > &tens4c)
void Tens4Identity (MathTensor4< TDim, TDim, TDim, TDim > &Ident)
void Tens4IdentitySym (MathTensor4< TDim, TDim, TDim, TDim > &Ident)
void Tens4Subtract (MathTensor4< TDim, TDim, TDim, TDim > &tens4_out, const MathTensor4< TDim, TDim, TDim, TDim > &tens4a, const MathTensor4< TDim, TDim, TDim, TDim > &tens4b)
void Tens4ToMat (DenseMatrix< FixedArray2< number, TDimSQ, TDimSQ > > &mat, const MathTensor4< TDim, TDim, TDim, TDim > &tens4)
void Tens4Zero (MathTensor4< TDim, TDim, TDim, TDim > &tensOut)
void TerminateAbortedRun ()
static bool TestDomainInterfaces (TDomain *dom)
static bool TestDomainInterfaces (TDomain *dom, bool verbose)
bool TestGridLayoutMap (MultiGrid &mg, GridLayoutMap &glm, bool verbose=true)
bool TestGridLayoutMap (MultiGrid &mg, GridLayoutMap &glm, TAPos &aPos, bool verbose=true)
void TestHorizontalAlgebraLayouts (const TMatrix &mat, std::vector< AlgebraID > *algebraIDs=NULL, bool verbose=false)
void TestQuadRule ()
bool Tetrahedralize (Grid &grid, ISubsetHandler &sh, number quality, bool preserveBnds, bool preserveAll, APosition &aPos, int verbosity)
bool Tetrahedralize (Grid &grid, number quality=5, bool preserveBnds=false, bool preserveAll=false, APosition &aPos=aPosition, int verbosity=0)
void TetrahedralizeHybridTetOctGrid (MultiGrid &mg, int bestDiag)
number TetrahedronAspectRatio (Volume *vol, TAAPos &aaPos)
void TetReferenceMappingTest (std::vector< number > vCornerCoord0, std::vector< number > vCornerCoord1, std::vector< number > vCornerCoord2, std::vector< number > vCornerCoord3, std::vector< number > vGlobPos)
bool ThrowIfIsVectorNanOrTooBig (const T &t, const char *callerName)
void ThrowMissingVirtualMethod (const char *method)
void ThrowMissingVirtualMethod (const char *method, const ReferenceObjectID roid)
vector< string > TokenizeString (const char *str, const char delimiter=',')
UG_API std::vector< std::string > TokenizeString (const std::string &str, const char delimiter=',')
UG_API void TokenizeString (const std::string &str, std::vector< std::string > &vToken, const char delimiter=',')
vector< string > TokenizeString (const string &str, const char delimiter)
void TokenizeString (const string &str, vector< string > &vToken, const char delimiter)
UG_API std::vector< std::string > TokenizeTrimString (const std::string &str, const char delimiter=',')
UG_API void TokenizeTrimString (const std::string &str, std::vector< std::string > &vToken, const char delimiter=',')
vector< string > TokenizeTrimString (const string &str, const char delimiter)
void TokenizeTrimString (const string &str, vector< string > &vToken, const char delimiter)
UG_API std::string ToLower (std::string str)
string ToLower (string str)
void topological_ordering_core_bidirectional (O_t &o, G_t &g, bool inverse)
void topological_ordering_core_directed (O_t &o, G_t &g, bool inverse)
std::string ToString (const T &t)
UG_API std::string ToUpper (std::string str)
string ToUpper (string str)
MathMatrix< 1, 1, T >::value_type Trace (const MathMatrix< 1, 1, T > &m)
MathMatrix< 2, 2, T >::value_type Trace (const MathMatrix< 2, 2, T > &m)
MathMatrix< 3, 3, T >::value_type Trace (const MathMatrix< 3, 3, T > &m)
bool TransformPointSetTo2D (vector2 *pointSetOut, const vector3 *pointSet, size_t numPoints)
UG_API void TransformVertex (Vertex *vrt, matrix33 &m, TAAPos &aaPos)
UG_API void TransformVertices (TIterator vrtsBegin, TIterator vrtsEnd, matrix33 &m, TAAPos &aaPos)
void TranslateDomain (TDomain &dom, ISelector &sel, const vector3 &offset)
static void TranslateDomain (TDomain &dom, number tx, number ty, number tz)
void TranslateSelection (Selector &sel, const typename TAAPosVRT::ValueType &offset, TAAPosVRT &aaPos)
void Transpose (MathMatrix< N, M, T > &mOut, const MathMatrix< M, N, T > &m)
void Transpose (matrix_t &m)
void TransposedMatVecMult (vector_t_out &vOut, const matrix_t &m, const vector_t_in &v)
void TransposedMatVecMultAdd (vector_t_out &vOut, const matrix_t &m, const vector_t_in &v)
char TransposeModeToChar (eTransposeMode t, bool isComplex)
void TransTens4 (MathTensor4< TDim, TDim, TDim, TDim > &tens4_out, const MathTensor4< TDim, TDim, TDim, TDim > &tens4)
void TraverseBreadthFirst (const tree_t &tree, traverser_t &traverser)
void TraverseDepthFirst (const tree_t &tree, traverser_t &traverser)
int TraverseDepthFirstRecursion (const tree_t &tree, traverser_t &traverser, int curNode)
number TriangleArea (const vector_t &p1, const vector_t &p2, const vector_t &p3)
number TriangleAspectRatio (FaceVertices *f, TAAPos &aaPos)
vector_t TriangleBarycenter (const vector_t &p1, const vector_t &p2, const vector_t &p3)
UG_API bool TriangleBoxIntersection (const MathVector< 3 > &p0, const MathVector< 3 > &p1, const MathVector< 3 > &p2, const MathVector< 3 > &boxMin, const MathVector< 3 > &boxMax)
bool TriangleCircumcenter (vector2 &centerOut, const vector2 &p1, const vector2 &p2, const vector2 &p3)
bool TriangleCircumcenter (vector3 &centerOut, const vector3 &p1, const vector3 &p2, const vector3 &p3)
bool TriangleFill (Grid &grid, EdgeIterator edgesBegin, EdgeIterator edgesEnd, bool bTriangulateInside=true)
bool TriangleFill (std::vector< int > &vTriIndsOut, vector2 *polyChain, size_t polyChainSize, bool bTriangulateInside=true)
bool TriangleFill_SweepLine (Grid &grid, TIterator edgesBegin, TIterator edgesEnd, APosition &aPosVRT, AInt &aIntVRT, SubsetHandler *pSH=NULL, int newSubsetIndex=-1)
UG_API bool TriangleFill_SweepLine (std::vector< int > &facesOut, const std::vector< vector2 > &srcVrts, std::vector< int > &srcEdges)
bool TriangleFill_SweepLine (std::vector< int > &facesOut, const std::vector< vector3 > &srcVrts, std::vector< int > &srcEdges)
bool TriangleFill_SweepLine (vector< int > &facesOut, const vector< vector2 > &srcVrtsOrig, vector< int > &srcEdges)
number TriangleQuality (vector3 &v1, vector3 &v2, vector3 &v3)
number TriangleQuality_Area (const vector_t &p1, const vector_t &p2, const vector_t &p3)
UG_API bool TriangleTriangleIntersection (const MathVector< 3 > &p0, const MathVector< 3 > &p1, const MathVector< 3 > &p2, const MathVector< 3 > &q0, const MathVector< 3 > &q1, const MathVector< 3 > &q2, MathVector< 3 > *ip1Out=NULL, MathVector< 3 > *ip2Out=NULL, number snapThreshold=SMALL)
UG_API void Triangulate (Grid &grid, Grid::VertexAttachmentAccessor< APosition > *paaPos=NULL)
void Triangulate (Grid &grid, Quadrilateral *q, Grid::VertexAttachmentAccessor< APosition > *paaPos=NULL)
void Triangulate (Grid &grid, QuadrilateralIterator iterBegin, QuadrilateralIterator iterEnd, Grid::VertexAttachmentAccessor< APosition > *paaPos=NULL)
static int TriCubeIntersection (const TRI &t)
UG_API std::string TrimString (const std::string &str)
string TrimString (const string &str)
const char * TrueFalseString (bool b)
static vector2 trunk (const vector2 &v, number smallestVal)
static Vertex * TryCollapse (const AdjustEdgeLengthDesc &desc, Grid &grid, Edge *e, TAAPosVRT &aaPos, TAANormVRT &aaNorm, TAAIntVRT &aaInt, SubsetHandler *pshMarks=NULL, EdgeSelector *pCandidates=NULL)
Vertex * TryCollapse (Grid &grid, Edge *e, TAAPosVRT &aaPos, TAANormVRT &aaNorm, TAAIntVRT &aaInt, SubsetHandler *pshMarks=NULL, EdgeSelector *pCandidates=NULL)
bool TrySplit (Grid &grid, Edge *e, TAAPosVRT &aaPos, TAANormVRT &aaNorm, EdgeSelector *pCandidates=NULL, SubsetHandler *pshMarks=NULL)
bool TrySwap (Grid &grid, Edge *e, TAAPosVRT &aaPos, TAANormVRT &aaNorm, TAAIntVRT &aaInt, SubsetHandler *pshMarks=NULL, EdgeSelector *pCandidates=NULL)
std::string TypeName ()
std::string TypeName (const T &t)
void UG_LOG_Matrix (const MT &A)
void UG_LOG_Vector (const VT &vec)
const char * UGBuildHost ()
const char * UGCompileDate ()
int UGFinalize ()
int UGFinalizeNoPCLFinalize ()
void UGForceExit ()
UG_API std::string UGGetVersionString ()
const char * UGGitRevision ()
int UGInit (int *argcp, char ***argvp, int parallelOutputProcRank)
bool UGInitPlugins ()
void UGOutputProfileStatsOnExit (bool bEnable)
const char * UGSvnRevision ()
void UniqueToConsistent (TVector *pVec, const IndexLayout &masterLayout, const IndexLayout &slaveLayout, pcl::InterfaceCommunicator< IndexLayout > *pCom=NULL)
UG_API bool UnloadPlugins ()
void UpdateChainInfo (ChainInfo &ci, vector2 *polyChain, vector2 *edgeNormals)
static void UpdateProfiler_BridgeImpl (number damping)
void UpdateTotalMem ()
TNumber urand (TNumber lowerBound, TNumber upperBound)
bool Valence3VertexIsObsolete (const vector3 &p, const vector3 &c0, const vector3 &c1, const vector3 &c2, number maxSquaredHeightToBaseAreaRatio)
bool Valence4VertexIsObsolete (const vector3 &p, const vector3 &c0, const vector3 &c1, const vector3 &c2, const vector3 &c3, number maxSquaredHeightToBaseAreaRatio)
bool Vanka_step (const Matrix_type &A, Vector_type &x, const Vector_type &b, number relax)
const std::string & Variant::to< const std::string & > () const
std::string Variant::to< std::string > () const
Variant::Type Variant::type< const std::string & > ()
Variant::Type Variant::type< std::string > ()
bool VecAbsIsLess (const vector_t &v1, const typename vector_t::value_type s)
bool VecAbsIsLess (const vector_t &v1, const vector_t &v2)
void VecAdd (vector_t &vOut, const vector_t &v, typename vector_t::value_type s)
void VecAdd (vector_t &vOut, const vector_t &v1, const vector_t &v2)
void VecAdd (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3)
void VecAdd (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3, const vector_t &v4)
vector_t::value_type VecAngle (const vector_t &v1, const vector_t &v2)
vector_t::value_type VecAngleNorm (const vector_t &v1, const vector_t &v2)
void VecAppend (vector_t &vOut, const vector_t &v1)
void VecAppend (vector_t &vOut, const vector_t &v1, const vector_t &v2)
void VecAppend (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3)
void VecAppend (vector_t &vOut, const vector_t &v1, const vector_t &v2, const vector_t &v3, const vector_t &v4)
void VecAssign (GPUVector< T > &dest, const GPUVector< T > &v1)
void VecAssign (ParallelVector< T > &dest, const ParallelVector< T > &v1)
void VecAssign (vector_t &dest, const vector_t &v1)
void VecBroadcast (TVector *pVecDest, const TVector *pVecSrc, const IndexLayout &slaveLayoutDest, const IndexLayout &masterLayoutSrc, pcl::InterfaceCommunicator< IndexLayout > *pCom=NULL)
void VecCopy (TVector *pVec, const IndexLayout &masterLayout, const IndexLayout &slaveLayout, pcl::InterfaceCommunicator< IndexLayout > *pCom=NULL)
void VecCopy (vector_target_t &target, const vector_source_t &source, typename vector_target_t::value_type fill)
void VecCross (vector_t &vOut, const vector_t &v1, const vector_t &v2)
vector_t::value_type VecDistance (const vector_t &v1, const vector_t &v2)
TVector::value_type VecDistanceSq (const TVector &v1, const TVector &v2, const TMatrix &M)
vector_t::value_type VecDistanceSq (const vector_t &v1, const vector_t &v2)
vector_t::value_type VecDot (const vector_t &v1, const vector_t &v2)
void VecElemProd (vector_t &vOut, const vector_t &v1, const vector_t &v2)
void VecElemSqrt (vector_t &vOut, const vector_t &v1)
void VecExp (double &dest, const double &v)
void VecExp (ParallelVector< T > &dest, const ParallelVector< T > &v)
void VecExp (vector_t &dest, const vector_t &v)
void VecGather (TVector *pVecDest, const TVector *pVecSrc, const IndexLayout &masterLayoutDest, const IndexLayout &slaveLayoutSrc, pcl::InterfaceCommunicator< IndexLayout > *pCom=NULL)
void VecHadamardProd (double &dest, const double &v1, const double &v2)
void VecHadamardProd (ParallelVector< T > &dest, const ParallelVector< T > &v1, const ParallelVector< T > &v2)
void VecHadamardProd (vector_t &dest, const vector_t &v1, const vector_t &v2)
vector_t::value_type VecInftyNorm (const vector_t &v)
void VecInterpolateLinear (vector_t &vOut, const vector_t &v1, const vector_t &v2, typename vector_t::value_type interpAmount)
vector_t::value_type VecLength (const vector_t &v)
vector_t::value_type VecLengthSq (const vector_t &v)
void VecLog (double &dest, const double &v)
void VecLog (ParallelVector< T > &dest, const ParallelVector< T > &v)
void VecLog (vector_t &dest, const vector_t &v)
vector_t::value_type VecMaxNorm (const vector_t &v)
static number VecNorm (const vector3 &a)
void VecNormalize (vector_t &vOut, const vector_t &v)
double VecNormSquared (const double &a)
double VecNormSquared (const GPUVector< T > &a, const GPUVector< T > &b)
static number VecNormSquared (const vector3 &a)
double VecNormSquared (const vector_t &a)
number VecNormSquared (const vector_t &a, const vector_t &b, const std::vector< size_t > vIndex)
void VecNormSquaredAdd (const double &a, double &s)
void VecNormSquaredAdd (const GPUVector< T > &a, const GPUVector< T > &b, double &sum)
void VecNormSquaredAdd (const vector_t &a, const vector_t &b, number &sum, const std::vector< size_t > vIndex)
void VecNormSquaredAdd (const vector_t &a, double &sum)
vector_t::value_type VecOneNorm (const vector_t &v)
vector_t::value_type VecPNorm (const vector_t &v, unsigned int p)
void VecPow (vector_t &vOut, const vector_t &v1, typename vector_t::value_type s)
double VecProd (const double &a, const double &b)
void VecProd (const double &a, const double &b, double &s)
double VecProd (const GPUVector< T > &v1, const GPUVector< T > &v2)
void VecProd (const GPUVector< T > &v1, const GPUVector< T > &v2, double &res)
double VecProd (const ParallelVector< T > &a, const ParallelVector< T > &b)
static number VecProd (const vector3 &a, const vector3 &b)
double VecProd (const vector_t &a, const vector_t &b)
number VecProd (const vector_t &a, const vector_t &b, const std::vector< size_t > vIndex)
void VecProd (const vector_t &a, const vector_t &b, double &sum)
void VecProd (const vector_t &a, const vector_t &b, number &sum, const std::vector< size_t > vIndex)
void VecProdAdd (const double &a, const double &b, double &s)
void VecProdAdd (const vector_t &a, const vector_t &b, double &s)
void VecScale (vector_t &vOut, const vector_t &v, typename vector_t::value_type s)
void VecScaleAdd (double &dest, double alpha1, const double &v1, double alpha2, const double &v2)
void VecScaleAdd (double &dest, double alpha1, const double &v1, double alpha2, const double &v2, double alpha3, const double &v3)
void VecScaleAdd (GPUVector< T > &dest, double alpha1, const GPUVector< T > &v1, double alpha2, const GPUVector< T > &v2)
void VecScaleAdd (GPUVector< T > &dest, double alpha1, const GPUVector< T > &v1, double alpha2, const GPUVector< T > &v2, double alpha3, const GPUVector< T > &v3)
void VecScaleAdd (ParallelVector< T > &dest, double alpha1, const ParallelVector< T > &v1, double alpha2, const ParallelVector< T > &v2)
void VecScaleAdd (ParallelVector< T > &dest, double alpha1, const ParallelVector< T > &v1, double alpha2, const ParallelVector< T > &v2, double alpha3, const ParallelVector< T > &v3)
void VecScaleAdd (TE_VEC< vector_t > &dest, double alpha1, const TE_VEC< vector_t > &v1, double alpha2, const TE_VEC< vector_t > &v2)
void VecScaleAdd (TE_VEC< vector_t > &dest, double alpha1, const TE_VEC< vector_t > &v1, double alpha2, const TE_VEC< vector_t > &v2, double alpha3, const TE_VEC< vector_t > &v3)
void VecScaleAdd (vector_t &dest, number alpha1, const vector_t &v1, number alpha2, const vector_t &v2, const std::vector< size_t > vIndex)
void VecScaleAdd (vector_t &dest, number alpha1, const vector_t &v1, number alpha2, const vector_t &v2, number alpha3, const vector_t &v3, const std::vector< size_t > vIndex)
void VecScaleAdd (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2)
void VecScaleAdd (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2, typename vector_t::value_type s3, const vector_t &v3)
void VecScaleAdd (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2, typename vector_t::value_type s3, const vector_t &v3, typename vector_t::value_type s4, const vector_t &v4)
void VecScaleAppend (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1)
void VecScaleAppend (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2)
void VecScaleAppend (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2, typename vector_t::value_type s3, const vector_t &v3)
void VecScaleAppend (vector_t &vOut, typename vector_t::value_type s1, const vector_t &v1, typename vector_t::value_type s2, const vector_t &v2, typename vector_t::value_type s3, const vector_t &v3, typename vector_t::value_type s4, const vector_t &v4)
void VecScaleAssign (double &dest, double alpha1, const double &v1)
void VecScaleAssign (GPUVector< T > &dest, double alpha1, const GPUVector< T > &v1)
void VecScaleAssign (ParallelVector< T > &dest, double alpha1, const ParallelVector< T > &v1)
void VecScaleAssign (vector_t &dest, double alpha1, const vector_t &v1)
void VecScaleAssign (vector_t &dest, number alpha1, const vector_t &v1, const std::vector< size_t > vIndex)
void VecSet (vector_t &dest, number alpha, const std::vector< size_t > vIndex)
void VecSet (vector_t &vInOut, typename vector_t::value_type s)
void VecSubtract (vector_t &vOut, const vector_t &v, typename vector_t::value_type s)
void VecSubtract (vector_t &vOut, const vector_t &v1, const vector_t &v2)
void VecSubtractOneSlaveFromMaster (TVector *pVec, const IndexLayout &masterLayout, const IndexLayout &slaveLayout, pcl::InterfaceCommunicator< IndexLayout > *pCom=NULL)
void VecSubtractOnLayout (TVector *pVec, const IndexLayout &masterLayout, const IndexLayout &slaveLayout, pcl::InterfaceCommunicator< IndexLayout > *pCom=NULL)
void vecSum (double &erg, double alpha, double vec)
T::value_type vecSum (double alpha, const T &vec)
double vecSum (double alpha, double vec)
void vecSum (typename T::value_type &erg, double alpha, const T &vec)
void VectorAdd (vector_t &dest, const T1 &t1)
void VectorAssign (vector_t &dest, const AlphaMatVec_X_Expression< T1, operation, T2 > &t)
void VectorAssign (vector_t &dest, const MatVec_Expression< matrix_t, vector_t > &m1)
void VectorAssign (vector_t &dest, const vector_t2 &v1)
void VectorAssign (vector_t &dest, double alpha0, const T0 &t0, double alpha1, const vector_t2 &v1, double alpha2, const MatVec_Expression< matrix_t, vector_t > &m2)
void VectorAssign (vector_t &dest, double alpha1, const AlphaMatVec_X_Expression< T1, operation, T2 > &t1, double alpha2, const T3 &t2)
void VectorAssign (vector_t &dest, double alpha1, const MatVec_Expression< matrix_t, vector_t > &m1, double alpha2, const MatVec_Expression< matrix_t, vector_t > &m2)
void VectorAssign (vector_t &dest, double alpha1, const MatVec_Expression< matrix_t, vector_t > &m1, double alpha2, const MatVec_Expression< matrix_t, vector_t > &m2, double alpha3, const vector_t2 &v3)
void VectorAssign (vector_t &dest, double alpha1, const MatVec_Expression< matrix_t, vector_t > &m1, double alpha2, const vector_t2 &v2)
void VectorAssign (vector_t &dest, double alpha1, const MatVec_Expression< matrix_t, vector_t > &m1, double alpha2, const vector_t2 &v2, double alpha3, const vector_t3 &v3)
void VectorAssign (vector_t &dest, double alpha1, const T1 &t1, double alpha2, const AlphaMatVec_X_Expression< T2, operation, T3 > &t2)
void VectorAssign (vector_t &dest, double alpha1, const vector_t &v1, double alpha2, const MatVec_Expression< matrix_t, vector_t > &m2)
void VectorAssign (vector_t &dest, double alpha1, const vector_t1 &v1, double alpha2, const vector_t2 &v2, double alpha3, const vector_t3 &v3)
void VectorAssign (vector_t &dest, double alpha1, const vector_t2 &v1, double alpha2, const MatVec_Expression< matrix_t, vector_t > &m2, double alpha3, const T3 &t3)
void VectorAssign (vector_t &dest, double alpha1, const vector_t2 &v1, double alpha2, const vector_t3 &v2)
void VectorSub (vector_t &dest, const T1 &t1)
void VecToTens2 (MathMatrix< TDim, TDim > &tens2, const DenseVector< FixedArray1< number, TDimSQ > > &vec)
vector_t::value_type VecTwoNorm (const vector_t &v)
vector_t::value_type VecTwoNormSq (const vector_t &v)
UG_API number VertexDistance (Vertex *v0, Vertex *v1, TAAPos &aaPos)
UG_API number VertexDistanceSq (Vertex *v0, Vertex *v1, TAAPos &aaPos)
bool VertexGroupsMatch (const IVertexGroup *elem, const IVertexGroup &desc)
bool VertexGroupsMatch (const Vertex *elem, const IVertexGroup &desc)
void VisitAll (const TIter begin, const TIter end, boost::function< void(typename TIter::value_type)> visitorCallback)
void VisitAreaBoundary (Grid &g, const TIter begin, const TIter end, boost::function< bool(typename TIter::value_type)> cbBelongsToArea, boost::function< void(typename Pointer2Value< typename TIter::value_type >::type::side)> cbVisitSide)
bool VolumeContains (Volume *v, EdgeVertices *ev)
bool VolumeContains (Volume *v, FaceVertices *fv)
bool VolumeContains (VolumeVertices *v, Vertex *vrt)
template<typename TGridFunction >
void vorticity (TGridFunction &vort, TGridFunction &u)
template<typename TGridFunction >
void vorticityFV1 (TGridFunction &vort, TGridFunction &u)
template<typename TGridFunction >
void vorticityFVCR (TGridFunction &vort, TGridFunction &u)
void vtk_export_ho (SmartPtr< TGridFunction > u, const std::vector< std::string > &vFct, size_t order, SmartPtr< VTKOutput< TGridFunction::domain_type::dim > > vtkOutput, const char *filename)
void vtk_export_ho (SmartPtr< TGridFunction > u, const std::vector< std::string > &vFct, size_t order, SmartPtr< VTKOutput< TGridFunction::domain_type::dim > > vtkOutput, const char *filename, const std::vector< std::string > &vSubset)
void vtk_export_ho (SmartPtr< TGridFunction > u, const std::vector< std::string > &vFct, size_t order, SmartPtr< VTKOutput< TGridFunction::domain_type::dim > > vtkOutput, const char *filename, size_t step, number time)
void vtk_export_ho (SmartPtr< TGridFunction > u, const std::vector< std::string > &vFct, size_t order, SmartPtr< VTKOutput< TGridFunction::domain_type::dim > > vtkOutput, const char *filename, size_t step, number time, const std::vector< std::string > &vSubset)
void vtk_export_ho (SmartPtr< TGridFunction > u, const std::vector< std::string > &vFct, size_t order, SmartPtr< VTKOutput< TGridFunction::domain_type::dim > > vtkOutput, const char *filename, size_t step, number time, const SubsetGroup &ssg)
bool WarnIfIsVectorNanOrTooBig (const T &t, const char *callerName)
void WeightedEdgeSmooth (Grid &grid, TIterator vrtsBegin, TIterator vrtsEnd, AAPosVRT &aaPos, number alpha, int numIterations, Grid::vertex_traits::callback cbSmoothVertex)
void WeightedFaceSmooth (Grid &grid, TIterator vrtsBegin, TIterator vrtsEnd, AAPosVRT &aaPos, number alpha, int numIterations, Grid::vertex_traits::callback cbSmoothVertex)
void WeightedNormalSmooth (Grid &grid, TIterator vrtsBegin, TIterator vrtsEnd, AAPosVRT &aaPos, number alpha, number dotThreshold, int numIterations)
bool WildcardMatch (const char *str, const char *pattern)
std::ostream & write_plain_txt (std::ostream &outStream, const ug::MathVector< 1 > &v)
std::ostream & write_plain_txt (std::ostream &outStream, const ug::MathVector< 2 > &v)
std::ostream & write_plain_txt (std::ostream &outStream, const ug::MathVector< 3 > &v)
std::ostream & write_plain_txt (std::ostream &outStream, const ug::MathVector< 4 > &v)
void WriteAlgebraIndices (std::string name, ConstSmartPtr< TDomain > domain, ConstSmartPtr< DoFDistribution > dd)
void WriteCallLog (const char *filename)
void WriteCallLog (const char *filename, int procId)
void WriteDebugValuesToFile (const char *filename, Grid &grid, TAValue &aVal, bool levelWise)
static void WriteEdges (ofstream &out, EdgeIterator edgesBegin, EdgeIterator edgesEnd, int indexDimension, Grid::VertexAttachmentAccessor< AInt > &aaInt)
static void WriteFaces (ofstream &out, FaceIterator facesBegin, FaceIterator facesEnd, int indexDimension, Grid::VertexAttachmentAccessor< AInt > &aaInt)
static void WriteGridHeader (const GridHeader &gridHeader, BinaryBuffer &out)
static bool WriteLGM (Grid &grid, const char *lgmFilename, const char *problemName, const char *lgmName, int convex, const SubsetHandler &shFaces, const SubsetHandler &shVolumes, EdgeSelector &LineSel, VertexSelector &SurfVrtSel, Grid::EdgeAttachmentAccessor< AInt > &aaLineIndex, Grid::VertexAttachmentAccessor< AInt > &aaSurfVrtIndex, Grid::VertexAttachmentAccessor< AVector3 > &aaPos)
void WriteMatrixToConnectionViewer (const char *filename, const typename TFunction::algebra_type::matrix_type &A, const TFunction &u)
static bool WriteNG (Grid &grid, const SubsetHandler &shFaces, const SubsetHandler &shVolumes, const char *ngFilename, VertexSelector &SurfVrtSel, VertexSelector &InnVrtSel, VertexSelector &NgVrtSel, EdgeSelector &LineSel, Grid::EdgeAttachmentAccessor< AInt > &aaLineIndex, Grid::VertexAttachmentAccessor< AInt > &aaInnVrtIndex, Grid::VertexAttachmentAccessor< AInt > &aaNgVrtIndex, Grid::FaceAttachmentAccessor< AInt > &aaFaceIndex, Grid::VertexAttachmentAccessor< AVector3 > &aaPos)
static void WriteParent (MultiGrid &mg, TElem *pElem, MultiElementAttachmentAccessor< AInt > &aaInt, BinaryBuffer &out)
void WriteProfileDataXML (const char *filename)
void WriteProfileDataXML (const char *filename, int procId)
static void WriteSelectionStatesToStream (TElemIter iterBegin, TElemIter iterEnd, ISelector &sel, BinaryBuffer &out)
static void WriteSubsetIndicesToStream (TElemIter iterBegin, TElemIter iterEnd, ISubsetHandler &sh, BinaryBuffer &out)
void WriteVectorCSV (const char *filename, const typename TFunction::algebra_type::vector_type &b, const TFunction &u)
void WriteVectorCSV (const char *filename, const Vector_type &b, postype *positions, int dimensions)
void WriteVectorToConnectionViewer (const char *filename, const typename TFunction::algebra_type::matrix_type &A, const typename TFunction::algebra_type::vector_type &b, const TFunction &u, const typename TFunction::algebra_type::vector_type *pCompareVec=NULL)
void WriteVectorToConnectionViewer (const char *filename, const typename TFunction::algebra_type::vector_type &b, const TFunction &u, const typename TFunction::algebra_type::vector_type *pCompareVec=NULL)
UG_API std::string XMLStringEscape (std::string s)
string XMLStringEscape (string s)
void zgetrf_ (lapack_int *m, lapack_int *n, std::complex< lapack_double > *pColMajorMatrix, lapack_int *lda, lapack_int *ipiv, lapack_int *info)
void zgetrs_ (char *trans, lapack_int *n, lapack_int *nrhs, const std::complex< lapack_double > *pColMajorMatrix, lapack_int *lda, const lapack_int *ipiv, std::complex< lapack_double > *b, lapack_int *ldb, lapack_int *info)
Variables
ABORT_TRAVERSAL
AGeomObjID aGeomObjID ("globalID", false)
AGeomObjID aGeomObjID
size_t allocated
ANormal aNormal ("normal", true)
APosition aPosition ("position", true)
APosition1 aPosition1 ("position2", true)
APosition2 aPosition2 ("position2", true)
DebugID APP ("APP")
DebugID APP
APPS_PATH
AT_DATA
AT_GUI
BIN_PATH
bool bMemTracker
const int BOXPRIORITYQUEUE2_MAXIMAL_VALUE
const int BOXPRIORITYQUEUE_MAXIMAL_VALUE
std::vector< ProfileCall > callsOnHold
ColMajor
const unsigned int cost_del
const unsigned int cost_ins
const unsigned int cost_sub
CSEDGE_CONSTRAINED_EDGE
CSEDGE_CONSTRAINING_EDGE
CSEDGE_NONE
CSEDGE_REGULAR_EDGE
CSFACE_CONSTRAINED_QUADRILATERAL
CSFACE_CONSTRAINED_TRIANGLE
CSFACE_CONSTRAINING_QUADRILATERAL
CSFACE_CONSTRAINING_TRIANGLE
CSFACE_NONE
CSFACE_QUADRILATERAL
CSFACE_TRIANGLE
CSFACE_USER
CSVOL_HEXAHEDRON
CSVOL_NONE
CSVOL_OCTAHEDRON
CSVOL_PRISM
CSVOL_PYRAMID
CSVOL_TETRAHEDRON
CSVRT_CONSTRAINED_VERTEX
CSVRT_NONE
CSVRT_REGULAR_VERTEX
CT_ALL
CT_ASSEMBLED
CT_CONSTRAINED
CT_CONSTRAINING
CT_CONSTRAINTS
CT_DIRICHLET
CT_HANGING
CT_MAY_DEPEND_ON_HANGING
CT_NONE
CT_NONE
DebugID DBG_COLORING ("ParallelColoring")
DebugID DBG_MATRIX_OVERLAP ("Algebra.MatrixOverlap")
DebugID DID_CUDA ("CUDA")
DebugID DID_DATA_EVALUATOR ("DATA_EVALUATOR")
DebugID DID_ELEM_DISC_ASSEMBLE_UTIL ("ELEM_DISC_ASSEMBLE_UTIL")
DebugID DID_FV1_GEOM ("FV1_GEOM")
DebugID DID_LOCAL_FINITE_ELEMENT_PROVIDER ("LOCAL_FINITE_ELEMENT_PROVIDER")
DebugID DID_LUACOMPILER ("LUACompiler")
DebugID DID_REFERENCE_MAPPING ("REFERENCE_MAPPING")
DebugID DID_REFERENCE_MAPPING
DebugID DID_REFERENCE_MAPPING_GLOB_TO_LOC ("REFERENCE_MAPPING_GLOB_TO_LOC")
DebugID DID_REFERENCE_MAPPING_GLOB_TO_LOC
DIM_SUBSET_EMPTY_GRID
DONT_TRAVERSE_CHILDREN
EDGE
EDGEOPT_NONE
EDGEOPT_STORE_ASSOCIATED_FACES
EDGEOPT_STORE_ASSOCIATED_VOLUMES
EDT_ALL
EDT_BND
EDT_ELEM
EDT_NONE
EDT_SIDE
EO_CREATE_FACES
EO_CREATE_VOLUMES
EO_DEFAULT
ES_H_MASTER
ES_H_SLAVE
ES_IN_INTERFACE
ES_NONE
ES_SCHEDULED_FOR_INTERFACE
ES_V_MASTER
ES_V_SLAVE
EXPL
FACE
FACEOPT_AUTOGENERATE_EDGES
FACEOPT_NONE
FACEOPT_STORE_ASSOCIATED_EDGES
FACEOPT_STORE_ASSOCIATED_VOLUMES
bool g_bNoNANCheck
static GlobalBoundaryRefinementRule g_boundaryRefinementRule
size_t g_minSecondUntilProgress
int g_ShinyCallLoggingMaxFreq
GHC_HEADER_BEGIN
GHC_HEADER_END
GHC_READ_OPTIONS
GHRO_READ_DEFAULT
GHRO_READ_LEVELS
GHRO_READ_PARENTS
GMAT_GLOBAL_ADAPTION_BEGINS
GMAT_GLOBAL_ADAPTION_ENDS
GMAT_GLOBAL_COARSENING_BEGINS
GMAT_GLOBAL_COARSENING_ENDS
GMAT_GLOBAL_REFINEMENT_BEGINS
GMAT_GLOBAL_REFINEMENT_ENDS
GMAT_HNODE_ADAPTION_BEGINS
GMAT_HNODE_ADAPTION_ENDS
GMAT_HNODE_COARSENING_BEGINS
GMAT_HNODE_COARSENING_ENDS
GMAT_HNODE_REFINEMENT_BEGINS
GMAT_HNODE_REFINEMENT_ENDS
GMAT_UNKNOWN
GMCT_CREATION_STARTS
GMCT_CREATION_STOPS
GMCT_NONE
GMDT_DISTRIBUTION_STARTS
GMDT_DISTRIBUTION_STOPS
GMDT_NONE
GMMGCT_LEVEL_ADDED
GMMGCT_REMOVED
GOID_EDGE
GOID_HEXAHEDRON
GOID_NUM_GRID_OBJECT_IDS
GOID_OCTAHEDRON
GOID_PRISM
GOID_PYRAMID
GOID_QUADRILATERAL
GOID_TETRAHEDRON
GOID_TRIANGLE
GOID_VERTEX
const char * GRID_BASE_OBJECT_PLURAL_NAMES []
const char * GRID_BASE_OBJECT_SINGULAR_NAMES []
GRIDOPT_AUTOGENERATE_SIDES
GRIDOPT_DEFAULT
GRIDOPT_FULL_INTERCONNECTION
GRIDOPT_NO_INTERCONNECTION
GRIDOPT_NONE
GRIDOPT_STANDARD_INTERCONNECTION
GRIDOPT_VERTEXCENTRIC_INTERCONNECTION
GSID_CONSTRAINED_EDGE
GSID_CONSTRAINED_QUADRILATERAL
GSID_CONSTRAINED_TRIANGLE
GSID_CONSTRAINING_EDGE
GSID_CONSTRAINING_QUADRILATERAL
GSID_CONSTRAINING_TRIANGLE
GSID_EDGE
GSID_EDGE_BASE
GSID_END_OF_GRID
GSID_FACE
GSID_GEOMETRIC_OBJECT
GSID_HANGING_VERTEX
GSID_HEXAHEDRON
GSID_INVALID
GSID_NEW_LEVEL
GSID_OCTAHEDRON
GSID_PRISM
GSID_PYRAMID
GSID_QUADRILATERAL
GSID_TETRAHEDRON
GSID_TRIANGLE
GSID_VERTEX
GSID_VERTEX_BASE
GSID_VOLUME
HAS_PARENT
HEX_SHORTX
HEX_SHORTXY
HEX_SHORTXZ
HEX_SHORTY
HEX_SHORTYZ
HEX_SHORTZ
static const int INNER_TKD_ELEMENT_INDICES []
INT_H_MASTER
INT_H_SLAVE
INT_NONE
INT_V_MASTER
INT_V_SLAVE
INVALID_ATTACHMENT_INDEX
IS_DUMMY
IS_NORMAL
IS_UNASSIGNED
IS_VMASTER
IS_VSLAVE
ISOTROPIC
KDSD_CIRCULAR
KDSD_LARGEST
KDTSS_CIRCULAR
KDTSS_LARGEST
static DebugID LG_DIST ("LG_DIST")
LGBC_NONE
LGBC_POS2D
LGBC_POS3D
LGBC_PROJECTION_HANDLER
LGBC_SELECTOR
LGBC_SUBSET_HANDLER
DebugID LIB_ALG_AMG ("LIB_ALG_AMG")
DebugID LIB_ALG_AMG
DebugID LIB_ALG_LINEAR_OPERATOR ("LIB_ALG_LINEAR_OPERATOR")
DebugID LIB_ALG_LINEAR_OPERATOR
DebugID LIB_ALG_LINEAR_SOLVER
DebugID LIB_ALG_LINEAR_SOLVER ("LIB_ALG_LINEAR_SOLVER")
DebugID LIB_ALG_MATRIX ("LIB_ALG_MATRIX")
DebugID LIB_ALG_MATRIX
DebugID LIB_ALG_VECTOR
DebugID LIB_ALG_VECTOR ("LIB_ALG_VECTOR")
DebugID LIB_DISC ("LIB_DISC")
DebugID LIB_DISC
DebugID LIB_DISC_ASSEMBLE
DebugID LIB_DISC_ASSEMBLE ("LIB_DISC_ASSEMBLE")
DebugID LIB_DISC_D3F
DebugID LIB_DISC_D3F ("LIB_DISC_D3F")
DebugID LIB_DISC_DISCRETE_FUNCTION
DebugID LIB_DISC_DISCRETE_FUNCTION ("LIB_DISC_DISCRETE_FUNCTION")
DebugID LIB_DISC_LINKER ("LIB_DISC_LINKER")
DebugID LIB_DISC_LINKER
DebugID LIB_DISC_MULTIGRID ("LIB_DISC_MULTIGRID")
DebugID LIB_DISC_MULTIGRID
DebugID LIB_DISC_NEWTON ("LIB_DISC_NEWTON")
DebugID LIB_DISC_NEWTON
DebugID LIB_DISC_OPERATOR_INVERSE
DebugID LIB_DISC_OPERATOR_INVERSE ("LIB_DISC_OPERATOR_INVERSE")
DebugID LIB_DISC_ORDER ("LIB_DISC_ORDER")
DebugID LIB_DISC_OUTPUT ("LIB_DISC_OUTPUT")
DebugID LIB_DISC_OUTPUT
DebugID LIB_DISC_TRANSFER ("LIB_DISC_TRANSFER")
DebugID LIB_DISC_TRANSFER
DebugID LIB_GRID ("LIB_GRID")
DebugID LIB_GRID
DebugID LIB_GRID_REFINER
DebugID LIB_GRID_REFINER ("LIB_GRID_REFINER")
DebugID LIB_LIMEX ("LIB_LIMEX")
DebugID LIB_PCL ("LIB_PCL")
DebugID LIB_PCL
LINEAR
DebugID MAIN ("MAIN")
DebugID MAIN
MASS
MATRIX_USE_GLOBAL_FUNCTIONS
MATRIX_USE_MEMBER_FUNCTIONS
MATRIX_USE_OPERATORS
MATRIX_USE_ROW_FUNCTIONS
const int MAX_FACE_VERTICES
MAX_PART
MAX_PATH_CONSTANT
MAX_PROCESS
const int MAX_VOLUME_VERTICES
static const size_t MAXBLOCKSIZE
MemTrackerMap memTracker
const int MG_EDGE_MAX_EDGE_CHILDREN
const int MG_FACE_MAX_EDGE_CHILDREN
const int MG_FACE_MAX_FACE_CHILDREN
ModeConjTranspose
ModeNoTrans
ModeTranspose
NHT_ALL
NHT_DEFAULT
NHT_EDGE_NEIGHBORS
NHT_FACE_NEIGHBORS
NHT_VERTEX_NEIGHBORS
NHT_VOLUME_NEIGHBORS
NONE
NUM_GEOMETRIC_BASE_OBJECTS
NUM_REFERENCE_OBJECTS
OT_EDGE_OBSERVER
OT_FACE_OBSERVER
OT_FULL_OBSERVER
OT_GRID_OBSERVER
OT_NONE
OT_VERTEX_OBSERVER
OT_VOLUME_OBSERVER
static const int OUTER_TKD_ELEMENT_INDICES []
PCT_CLOSED
PCT_EMPTY
PCT_IRREGULAR
PCT_OPEN
PCT_SEPARATED
PCT_UNKNOWN
const number PI
PLUGIN_PATH
PRISM_FLAT
PRISM_LONG
std::vector< ProfileCall > profileCalls
PST_ADDITIVE
PST_CONSISTENT
PST_UNDEFINED
PST_UNIQUE
PT_ALL
PT_INSTATIONARY
PT_STATIONARY
QUAD_SHORTX
QUAD_SHORTY
REM_CREASE
REM_FIXED
REM_NONE
RHS
RM_ANISOTROPIC
RM_CLOSURE
RM_COARSEN
RM_COPY
RM_DUMMY
RM_FULL
RM_LOCAL
RM_MAX
RM_NONE
RM_REFINE
ROID_EDGE
ROID_HEXAHEDRON
ROID_OCTAHEDRON
ROID_PRISM
ROID_PYRAMID
ROID_QUADRILATERAL
ROID_TETRAHEDRON
ROID_TRIANGLE
ROID_UNKNOWN
ROID_VERTEX
ROOT_PATH
RowMajor
static bool s_abortRun
DebugID SchurDebug
DebugID SchurDebug ("SchurComplementDebug")
SCRIPT_PATH
SD_INNER
SD_SKELETON
SE_ALL
SE_ALL
SE_EDGE
SE_EDGE
SE_FACE
SE_FACE
SE_NONE
SE_NONE
SE_VERTEX
SE_VERTEX
SE_VOLUME
SE_VOLUME
map< const Shiny::ProfileNode *, size_t > selfmem
SHE_ALL
SHE_ALL
SHE_EDGE
SHE_EDGE
SHE_FACE
SHE_FACE
SHE_NONE
SHE_NONE
SHE_VERTEX
SHE_VERTEX
SHE_VOLUME
SHE_VOLUME
static const char shiftCharacters []
static const size_t shiftCharactersLength
SLES_RIM
SLES_UNKNOWN
SLICE_DESC_SIZE
SLVS_END
SLVS_MERGE
SLVS_NONE
SLVS_REGULAR
SLVS_SPLIT
SLVS_START
const number SMALL
const number SMALL_SQ
SS_NONE
SS_NONE
SS_USER_STATE
SS_USER_STATE
STIFF
SUBDIV_SURF_AVERAGING_SCHEME
SUBDIV_SURF_BUTTERFLY_SCHEME
SUBDIV_SURF_LOOP_SCHEME
SUBDIV_VOL
map< const Shiny::ProfileNode *, size_t > totalmem
TRAVERSE_CHILDREN
static std::string UG_AUTHORS
static std::string UG_BINARY_LICENSE
const char * UG_BUILD_HOST
const char * UG_COMPILE_DATE
const char * UG_GIT_REVISION
const char * UG_SVN_REVISION
const int ugRefObjIdToVTKCellType []
const uint64 UNIT_EXA
const uint64 UNIT_EXA_SI
const uint64 UNIT_GIGA
const uint64 UNIT_GIGA_SI
const uint64 UNIT_KILO
const uint64 UNIT_KILO_SI
const uint64 UNIT_MEGA
const uint64 UNIT_MEGA_SI
const uint64 UNIT_PETA
const uint64 UNIT_PETA_SI
const uint64 UNIT_TERA
const uint64 UNIT_TERA_SI
bool useLua2VM
bool useLuaCompiler
VERTEX
VOLOPT_AUTOGENERATE_EDGES
VOLOPT_AUTOGENERATE_FACES
VOLOPT_NONE
VOLOPT_STORE_ASSOCIATED_EDGES
VOLOPT_STORE_ASSOCIATED_FACES
VOLUME
VRTOPT_NONE
VRTOPT_STORE_ASSOCIATED_EDGES
VRTOPT_STORE_ASSOCIATED_FACES
VRTOPT_STORE_ASSOCIATED_VOLUMES
VTK_HEXAHEDRON
VTK_LINE
VTK_NUM_TYPES
VTK_PIXEL
VTK_POLY_LINE
VTK_POLY_VERTEX
VTK_POLYGON
VTK_PYRAMID
VTK_QUAD
VTK_QUADRATIC_EDGE
VTK_QUADRATIC_HEXAHEDRON
VTK_QUADRATIC_QUAD
VTK_QUADRATIC_TETRA
VTK_QUADRATIC_TRIANGLE
VTK_TETRA
VTK_TRIANGLE
VTK_TRIANGLE_STRIP
VTK_VERTEX
VTK_VOXEL
VTK_WEDGE
const char * VTKCellNames []
Detailed Description
Base classes for problem settings for the Maxwell equations.
Implementation of base classes for problem settings for the Maxwell equations.
Implementation of a syncronization of arrays of generic memory structures distributed among processes on a parallel machine.
Computation of the vector of the Nedelec-element DoFs from a given vector field.
UserData class for convertion of the Nedelec-based data into the vector field.
nedelec_project_impl.h - implementation of class members of the classes for the projection of the functions based on the Nedelec element to the space of the divergence-free functions.
nedelec_source.h - classes for computation of divergence-free sources in form of Nedelec-type-1 element DoFs.
nedelec_source_impl.h - implementation of class members for computation of divergence-free sources in form of Nedelec-type-1 element DoFs.
nedelec_transfer.h - class of the transfer operators for the Nelelec (Whitney-1) elements.
nedelec_transfer_impl.h - implementation of class members of the transfer operators for the Nelelec (Whitney-1) elements.
Function Documentation
AssignSubsetsByElementQuality() [1/2]
void ug::AssignSubsetsByElementQuality (Grid & grid, SubsetHandler & sh, int dim, int numSecs)
References dim, and UG_THROW.
AssignSubsetsByElementQuality() [2/2]
void ug::AssignSubsetsByElementQuality (MultiGrid & mg, MGSubsetHandler & sh, int dim, int numSecs)
References AssignSubsetsByElementQuality3d(), dim, and UG_THROW.
Referenced by InitUGPlugin_ElementQualityStatistics().
AssignSubsetsByElementQuality3d()
void ug::AssignSubsetsByElementQuality3d (MultiGrid & grid, MGSubsetHandler & sh, int numSecs)
References aPosition, ug::MultiGridSubsetHandler::assign_subset(), CalculateMinDihedral(), ug::SubsetInfo::color, CreateElementQualityHistogram(), grid(), mkstr, ug::ISubsetHandler::num_subsets(), ug::ISubsetHandler::set_subset_name(), and ug::ISubsetHandler::subset_info().
Referenced by AssignSubsetsByElementQuality().
AssignSubsetToElementWithSmallestMinAngle()
void ug::AssignSubsetToElementWithSmallestMinAngle (MultiGrid & grid, MGSubsetHandler & sh, int dim, const char * roid, int si)
References AssignSubsetToElementWithSmallestMinAngle2d(), AssignSubsetToElementWithSmallestMinAngle3d(), dim, grid(), and UG_THROW.
Referenced by InitUGPlugin_ElementQualityStatistics().
AssignSubsetToElementWithSmallestMinAngle2d()
void ug::AssignSubsetToElementWithSmallestMinAngle2d (MultiGrid & grid, MGSubsetHandler & sh, const char * roid, int si)
References aPosition2, ug::MultiGridSubsetHandler::assign_subset(), AssignSubsetColors(), ug::Selector::begin(), ug::GridObjectCollection::begin(), CloseSelection(), ug::Selector::end(), ug::GridObjectCollection::end(), FindElementWithSmallestMinAngle(), grid(), ug::GridObjectCollection::num_levels(), ug::ISelector::select(), ug::ISubsetHandler::set_subset_name(), and UG_THROW.
Referenced by AssignSubsetToElementWithSmallestMinAngle().
AssignSubsetToElementWithSmallestMinAngle3d()
void ug::AssignSubsetToElementWithSmallestMinAngle3d (MultiGrid & grid, MGSubsetHandler & sh, const char * roid, int si)
References aPosition, ug::MultiGridSubsetHandler::assign_subset(), AssignSubsetColors(), ug::Selector::begin(), ug::GridObjectCollection::begin(), CloseSelection(), ug::Selector::end(), ug::GridObjectCollection::end(), FindElementWithSmallestMinAngle(), grid(), ug::GridObjectCollection::num_levels(), ug::ISelector::select(), ug::ISubsetHandler::set_subset_name(), and UG_THROW.
Referenced by AssignSubsetToElementWithSmallestMinAngle().
CalculateSubsetSurfaceArea()
number ug::CalculateSubsetSurfaceArea (MultiGrid & mg, int subsetIndex, MGSubsetHandler & sh)
References pcl::ProcessCommunicator::allreduce(), aPosition, ug::MultiGridSubsetHandler::begin(), ug::DistributedGridManager::contains_status(), ug::Grid::distributed_grid_manager(), ug::MultiGridSubsetHandler::end(), ES_H_SLAVE, FaceArea(), ug::DistributedGridManager::is_ghost(), pcl::NumProcs(), and PCL_RO_SUM.
Referenced by InitUGPlugin_ElementQualityStatistics().
CalculateSubsetVolume()
number ug::CalculateSubsetVolume (MultiGrid & mg, int subsetIndex, MGSubsetHandler & sh)
References pcl::ProcessCommunicator::allreduce(), aPosition, ug::MultiGridSubsetHandler::begin(), CalculateVolume(), ug::Grid::distributed_grid_manager(), ug::MultiGridSubsetHandler::end(), ug::DistributedGridManager::is_ghost(), pcl::NumProcs(), and PCL_RO_SUM.
Referenced by InitUGPlugin_ElementQualityStatistics().
cflNumber()
template<typename TGridFunction > void ug::cflNumber (TGridFunction & u, number deltaT)
domain type
world dimension
element iterator
element type
side type
grid type
References ug::LFEID::CROUZEIX_RAVIART, dim, DoFRef(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_ip(), ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scv(), num_subsets(), s, ug::DimCRFVGeometry< TDim, TWorldDim >::scv(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), UG_ASSERT, UG_LOG, ug::DimCRFVGeometry< TDim, TWorldDim >::update(), VecSubtract(), and VecTwoNormSq().
Referenced by ug::NavierStokes::FunctionalityIncomp::DomainAlgebra().
CollectAspectRatios()
template<class TIterator , class TAAPosVRT > void ug::CollectAspectRatios (Grid & grid, TIterator elementsBegin, TIterator elementsEnd, TAAPosVRT & aaPos, vector< number > & aspectRatios)
References CalculateAspectRatio(), ug::DistributedGridManager::contains_status(), ES_H_SLAVE, grid(), ug::DistributedGridManager::is_ghost(), and UG_LOG.
Referenced by ElementQualityStatistics3d().
CollectMaxAngles()
template<class TIterator , class TAAPosVRT > void ug::CollectMaxAngles (Grid & grid, TIterator elementsBegin, TIterator elementsEnd, TAAPosVRT & aaPos, vector< number > & maxAngles)
References CalculateMaxAngle(), ug::DistributedGridManager::contains_status(), ES_H_SLAVE, grid(), ug::DistributedGridManager::is_ghost(), and UG_LOG.
Referenced by ElementQualityStatistics3d().
CollectMinAngles()
template<class TIterator , class TAAPosVRT > void ug::CollectMinAngles (Grid & grid, TIterator elementsBegin, TIterator elementsEnd, TAAPosVRT & aaPos, vector< number > & minAngles)
References CalculateMinAngle(), ug::DistributedGridManager::contains_status(), ES_H_SLAVE, grid(), ug::DistributedGridManager::is_ghost(), and UG_LOG.
Referenced by ElementQualityStatistics3d().
CollectVolToRMSFaceAreaRatios()
template<class TIterator , class TAAPosVRT > void ug::CollectVolToRMSFaceAreaRatios (Grid & grid, TIterator elementsBegin, TIterator elementsEnd, TAAPosVRT & aaPos, vector< number > & ratios)
References CalculateVolToRMSFaceAreaRatio(), ug::DistributedGridManager::contains_status(), ES_H_SLAVE, grid(), ug::DistributedGridManager::is_ghost(), UG_LOG, and UG_LOGN.
Referenced by ElementQualityStatistics3d().
ComputeCRCuthillMcKeeOrder()
void ug::ComputeCRCuthillMcKeeOrder (std::vector< size_t > & vNewIndex, std::vector< std::vector< size_t > > & vvConnections, size_t minpind, bool bReverse)
References degree(), and find().
Referenced by OrderCRCuthillMcKee().
computeDegree()
void ug::computeDegree (std::vector< size_t > & degree, std::vector< std::vector< size_t > > & vvConnections, size_t minpind)
References degree().
Referenced by cr_get_connections().
computeNewIndicesFromPIndexset()
void ug::computeNewIndicesFromPIndexset (std::vector< std::vector< size_t > > & vvConnection, std::vector< size_t > & newIndex, size_t pmin, const std::vector< int > & inv_perm, bool bseparate)
Referenced by CRCuthillMcKee(), CRKing(), CRMinimumDegree(), and CRSloan().
computeNewIndicesFromVIndexset()
void ug::computeNewIndicesFromVIndexset (std::vector< std::vector< size_t > > & vvConnection, std::vector< size_t > & newIndex, size_t pmin, size_t dim, const std::vector< int > & inv_perm, bool bseparate, size_t strategy)
References dim.
Referenced by CRCuthillMcKee(), CRKing(), CRMinimumDegree(), and CRSloan().
constrainingSideAveraging()
template<typename TGridFunction , typename side_type , typename constraining_side_type , typename VType > void ug::constrainingSideAveraging (PeriodicAttachmentAccessor< side_type, Attachment< VType > > & aaData, SmartPtr< TGridFunction > m_uInfo)
side iterator
References CollectCornerCoordinates(), ug::DimCRFVGeometry< TDim, TWorldDim >::constrained_dof(), dim, SmartPtr< TGridFunction >::get(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_constrained_dofs(), ug::SurfaceView::SHADOW_RIM, and ug::DimCRFVGeometry< TDim, TWorldDim >::update_hanging().
cr_get_connections()
template<typename TElem , typename TGridFunction > void ug::cr_get_connections (std::vector< std::vector< size_t > > & vvConnection, size_t & minpind, DoFDistribution & dd, TGridFunction & u)
domain type
world dimension
References ug::DoFDistribution::begin(), computeDegree(), degree(), dim, ug::DoFDistribution::end(), find(), ug::LocalIndices::index(), ug::DoFDistribution::indices(), and ug::DoFDistribution::num_indices().
CRCuthillMcKee()
void ug::CRCuthillMcKee (std::vector< size_t > & newIndex, std::vector< std::vector< size_t > > & vvConnection, size_t dim, size_t minpind, bool bReverse, bool bseparate, bool orderp, bool orderv)
orders the dof distribution using Cuthill-McKee
References computeNewIndicesFromPIndexset(), computeNewIndicesFromVIndexset(), dim, extractPGraph(), extractVGraph(), boost::get(), boost::make_degree_map(), and PROFILE_FUNC.
Referenced by CROrderCuthillMcKee().
CreateElementQualityHistogram()
void ug::CreateElementQualityHistogram (vector< int > & histOut, const std::vector< number > & vQualities, int numSections)
Referenced by AssignSubsetsByElementQuality3d().
CreateSuperLUImplementation()
IExternalSolverImplementation * ug::CreateSuperLUImplementation (SuperLUConfiguration & config)
Referenced by ug::SuperLUSolver< TAlgebra >::SuperLUSolver().
CRKing()
void ug::CRKing (std::vector< size_t > & newIndex, std::vector< std::vector< size_t > > & vvConnection, size_t dim, size_t minpind, bool bReverse, bool bseparate, bool orderp, bool orderv)
orders the dof distribution using King
References computeNewIndicesFromPIndexset(), computeNewIndicesFromVIndexset(), dim, extractPGraph(), extractVGraph(), and PROFILE_FUNC.
Referenced by CROrderKing().
CRMinimumDegree()
void ug::CRMinimumDegree (std::vector< size_t > & newIndex, std::vector< std::vector< size_t > > & vvConnection, size_t dim, size_t minpind, bool bseparate, bool orderp, bool orderv)
orders the dof distribution using minimum degree algorithm
References computeNewIndicesFromPIndexset(), computeNewIndicesFromVIndexset(), degree(), dim, extractPGraph(), extractVGraph(), get(), PROFILE_FUNC, and type().
Referenced by CROrderMinimumDegree().
CROrderCuthillMcKee()
template<typename TDomain , typename TGridFunction > void ug::CROrderCuthillMcKee (ApproximationSpace< TDomain > & approxSpace, TGridFunction & u, bool bReverse, bool bseparate, bool orderp, bool orderv)
orders the all DofDistributions of the ApproximationSpace using Cuthill-McKee
domain type
world dimension
element type
References CRCuthillMcKee(), ug::LFEID::CROUZEIX_RAVIART, dim, ug::IApproximationSpace::dof_distributions(), ug::LFEID::PIECEWISE_CONSTANT, and UG_THROW.
Referenced by ug::NavierStokes::FunctionalityFVCR::DomainAlgebra().
CROrderKing()
template<typename TDomain , typename TGridFunction > void ug::CROrderKing (ApproximationSpace< TDomain > & approxSpace, TGridFunction & u, bool bReverse, bool bseparate, bool orderp, bool orderv)
orders the all DofDistributions of the ApproximationSpace using Cuthill-McKee
domain type
world dimension
element type
References CRKing(), ug::LFEID::CROUZEIX_RAVIART, dim, ug::IApproximationSpace::dof_distributions(), ug::LFEID::PIECEWISE_CONSTANT, and UG_THROW.
Referenced by ug::NavierStokes::FunctionalityFVCR::DomainAlgebra().
CROrderMinimumDegree()
template<typename TDomain , typename TGridFunction > void ug::CROrderMinimumDegree (ApproximationSpace< TDomain > & approxSpace, TGridFunction & u, bool bseparate, bool orderp, bool orderv)
orders the all DofDistributions of the ApproximationSpace using minimum degree algorithm
domain type
world dimension
element type
References CRMinimumDegree(), ug::LFEID::CROUZEIX_RAVIART, dim, ug::IApproximationSpace::dof_distributions(), ug::LFEID::PIECEWISE_CONSTANT, and UG_THROW.
Referenced by ug::NavierStokes::FunctionalityFVCR::DomainAlgebra().
CROrderSloan()
template<typename TDomain , typename TGridFunction > void ug::CROrderSloan (ApproximationSpace< TDomain > & approxSpace, TGridFunction & u, bool bseparate, bool orderp, bool orderv)
orders the all DofDistributions of the ApproximationSpace using Sloan
domain type
world dimension
element type
References ug::LFEID::CROUZEIX_RAVIART, CRSloan(), dim, ug::IApproximationSpace::dof_distributions(), ug::LFEID::PIECEWISE_CONSTANT, and UG_THROW.
Referenced by ug::NavierStokes::FunctionalityFVCR::DomainAlgebra().
CRSloan()
void ug::CRSloan (std::vector< size_t > & newIndex, std::vector< std::vector< size_t > > & vvConnection, size_t dim, size_t minpind, bool bseparate, bool orderp, bool orderv)
orders the dof distribution using Sloan
References computeNewIndicesFromPIndexset(), computeNewIndicesFromVIndexset(), degree(), dim, extractPGraph(), extractVGraph(), boost::get(), get(), PROFILE_FUNC, s, type(), and vertices().
Referenced by CROrderSloan().
DragLift()
template<typename TGridFunction > std::vector<number> ug::DragLift (SmartPtr< TGridFunction > spGridFct, const char * vCmp, const char * BndSubsets, const char * InnerSubsets, number kinVisco, number density, int quadOrder)
References ug::SubsetGroup::add(), ug::SubsetGroup::add_all(), pcl::ProcessCommunicator::allreduce(), CollectCornerCoordinates(), ug::SubsetGroup::contains(), DimReferenceElement< dim >::corner(), dim, ug::SubsetGroup::dim(), DIM_SUBSET_EMPTY_GRID, DoFRef(), SmartPtr< TGridFunction >::get(), ug::ReferenceMappingProvider::get(), ug::QuadratureRuleProvider< TDim >::get(), ug::ISubsetHandler::get_subset_index(), ug::LocalShapeFunctionSet< TDim, class, class >::grads(), grid(), ug::ReferenceElement::id(), Inverse(), ug::DimReferenceMapping< TDim, TWorldDim >::jacobian_transposed(), local(), ug::DimReferenceMapping< TDim, TWorldDim >::local_to_global(), MatVecMult(), ug::ReferenceElement::num(), pcl::NumProcs(), PCL_DT_DOUBLE, PCL_RO_SUM, RemoveLowerDimSubsets(), SameDimensionsInAllSubsets(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), ug::FunctionGroup::size(), ug::MathVector< N, class >::size(), ug::SubsetGroup::size(), ug::PointerConstArray< class >::size(), SqrtGramDeterminant(), TokenizeString(), UG_THROW, VecDot(), VecNormalize(), and VecScale().
DrivenCavityEvalAtPoints()
template<typename TGridFunction > void ug::DrivenCavityEvalAtPoints (const std::vector< MathVector< 2 > > & vPos, GlobalGridFunctionNumberData< TGridFunction > & GFEval, const number vReferenceValue[])
References ug::GlobalGridFunctionNumberData< class, elemDim >::evaluate_global(), table(), and UG_LOG.
DrivenCavityLinesEval()
template<typename TGridFunction > void ug::DrivenCavityLinesEval (SmartPtr< TGridFunction > u, std::vector< std::string > vVelCmp, size_t Re)
References UG_LOG.
ElementQualityStatistics() [1/4]
void ug::ElementQualityStatistics (Grid & grid, int dim)
References dim, ElementQualityStatistics2d(), ElementQualityStatistics3d(), grid(), and UG_THROW.
ElementQualityStatistics() [2/4]
void ug::ElementQualityStatistics (Grid & grid, int dim, number angleHistStepSize, number aspectRatioHistStepSize, bool bWriteHistograms)
References dim, ElementQualityStatistics2d(), ElementQualityStatistics3d(), grid(), and UG_THROW.
ElementQualityStatistics() [3/4]
void ug::ElementQualityStatistics (MultiGrid & mg, int dim)
References dim, ElementQualityStatistics2d(), ElementQualityStatistics3d(), ug::MultiGrid::get_grid_objects(), and UG_THROW.
ElementQualityStatistics() [4/4]
void ug::ElementQualityStatistics (MultiGrid & mg, int dim, number angleHistStepSize, number aspectRatioHistStepSize, bool bWriteHistograms)
References dim, ElementQualityStatistics2d(), ElementQualityStatistics3d(), ug::MultiGrid::get_grid_objects(), and UG_THROW.
Referenced by InitUGPlugin_ElementQualityStatistics().
ElementQualityStatistics2d()
void ug::ElementQualityStatistics2d (Grid & grid, GridObjectCollection goc, number angleHistStepSize, number aspectRatioHistStepSize, bool bWriteHistograms)
References aPosition2, ug::GridObjectCollection::begin(), CalculateAspectRatio(), CalculateMaxAngle(), CalculateMinAngle(), EdgeLength(), ug::GridObjectCollection::end(), FaceArea(), FindElementWithLargestAspectRatio(), FindElementWithLargestMaxAngle(), FindElementWithSmallestAspectRatio(), FindElementWithSmallestMinAngle(), FindLargestFace(), FindLongestEdge(), FindShortestEdge(), FindSmallestFace(), grid(), ug::GridObjectCollection::num(), ug::GridObjectCollection::num_faces(), ug::GridObjectCollection::num_levels(), ug::GridObjectCollection::num_vertices(), ug::GridObjectCollection::num_volumes(), PrintAngleStatistics2d(), table(), and UG_LOG.
Referenced by ElementQualityStatistics().
ElementQualityStatistics3d()
void ug::ElementQualityStatistics3d (Grid & grid, GridObjectCollection goc, number angleHistStepSize, number aspectRatioHistStepSize, bool bWriteHistograms)
References pcl::ProcessCommunicator::allreduce(), aPosition, ug::GridObjectCollection::begin(), CalculateAspectRatio(), CalculateMaxAngle(), CalculateMinAngle(), CalculateVolToRMSFaceAreaRatio(), CalculateVolume(), ug::Table< class >::clear(), CollectAspectRatios(), CollectMaxAngles(), CollectMinAngles(), CollectVolToRMSFaceAreaRatios(), ug::DistributedGridManager::contains_status(), EdgeLength(), ug::GridObjectCollection::end(), ES_H_SLAVE, FaceArea(), FindElementWithLargestAspectRatio(), FindElementWithLargestMaxAngle(), FindElementWithLargestVolToRMSFaceAreaRatio(), FindElementWithSmallestAspectRatio(), FindElementWithSmallestMinAngle(), FindElementWithSmallestVolToRMSFaceAreaRatio(), FindLargestFace(), FindLargestVolume(), FindLongestEdge(), FindShortestEdge(), FindSmallestFace(), FindSmallestVolume(), grid(), ug::DistributedGridManager::is_ghost(), ug::GridObjectCollection::num(), ug::GridObjectCollection::num_levels(), ug::GridObjectCollection::num_volumes(), pcl::NumProcs(), PCL_RO_MAX, PCL_RO_MIN, PCL_RO_SUM, PrintAngleHistogram(), PrintAngleStatistics3d(), PrintAspectRatioHistogram(), pcl::ProcRank(), table(), ug::Table< class >::to_csv(), UG_LOG, ug::GridObjectCollection::volumes_begin(), and ug::GridObjectCollection::volumes_end().
Referenced by ElementQualityStatistics().
extractPGraph()
template<class TGraph > void ug::extractPGraph (TGraph & G, std::vector< std::vector< size_t > > & vvConnection, size_t pmin, size_t dim, bool directed)
References dim, and s.
Referenced by CRCuthillMcKee(), CRKing(), CRMinimumDegree(), and CRSloan().
extractVGraph()
template<class TGraph > void ug::extractVGraph (TGraph & G, std::vector< std::vector< size_t > > & vvConnection, size_t pmin, size_t dim, bool directed)
References dim, and s.
Referenced by CRCuthillMcKee(), CRKing(), CRMinimumDegree(), and CRSloan().
FinalizeUGPlugin_Jupyter()
UG_API void ug::FinalizeUGPlugin_Jupyter ()
FinalizeUGPlugin_Limex()
UG_API void ug::FinalizeUGPlugin_Limex ()
FinalizeUGPlugin_Richards()
UG_API void ug::FinalizeUGPlugin_Richards ()
FindBoundsForStiffnesMatrixMaxEigenvalue()
void ug::FindBoundsForStiffnesMatrixMaxEigenvalue (MultiGrid & mg, MGSubsetHandler & shOut)
References aPosition, ug::MultiGridSubsetHandler::assign_subset(), AssignSubsetColors(), ug::Grid::attach_to_vertices_dv(), ug::MultiGrid::begin(), ug::Selector::begin(), CalculateTetrahedronVolToRMSFaceAreaRatio(), CalculateVolume(), ug::Selector::clear(), CloseSelection(), ug::Selector::end(), ug::MultiGrid::end(), ug::VolumeVertices::num_vertices(), ug::ISelector::select(), ug::MultiGrid::top_level(), UG_LOG, and ug::VolumeVertices::vertex().
Referenced by InitUGPlugin_ElementQualityStatistics().
GenerateScriptReferenceDocu()
int ug::GenerateScriptReferenceDocu (const char * baseDir, bool silent, bool genHtml, bool genCpp, bool genList)
References ug::DocuGen::classesAndGroups, ug::DocuGen::classesAndGroupsAndImplementations, dim, ug::LogAssistant::enable_terminal_output(), ug::DocuGen::CppGenerator::generate_cpp_files(), ug::UGError::get_file(), ug::UGError::get_line(), ug::UGError::get_msg(), GetClassHierarchy(), ug::DocuGen::GetGroups(), GetLogAssistant(), GetUGRegistry(), ug::DocuGen::ClassHierarchyProvider::init(), InitUG(), LOG, ug::bridge::Registry::num_class_groups(), ug::UGError::num_msg(), ug::script::RegisterDefaultLuaBridge(), ug::bridge::ClassHierarchy::subclasses, UG_ERR_LOG, UG_LOG, ug::DocuGen::WriteCompletionList(), and ug::DocuGen::WriteHTMLDocu().
Referenced by InitUGPlugin_DocuGen().
get_constrained_sides_cr()
template<typename side_type , typename secure_container , typename TGridFunction > void ug::get_constrained_sides_cr (secure_container & sides, const TGridFunction & u, std::vector< MultiIndex< 2 > > multInd, size_t fct = 0)
domain type
world dimension
create Multiindex
References ug::ConstrainingEdge::constrained_edge(), ug::ConstrainingFace::constrained_face(), dim, ug::ConstrainingEdge::num_constrained_edges(), and ug::ConstrainingFace::num_constrained_faces().
Init___CompressibleNavierStokes() [1/2]
void ug::Init___CompressibleNavierStokes (bridge::Registry * reg, std::string grp)
Init___CompressibleNavierStokes() [2/2]
void ug::Init___CompressibleNavierStokes (Registry * reg, string grp)
This function is called when the plugin is loaded.
References Init___CompressibleNavierStokes___FV1(), and UG_REGISTRY_CATCH_THROW.
Referenced by InitUGPlugin_NavierStokes().
Init___CompressibleNavierStokes___FV1() [1/2]
void ug::Init___CompressibleNavierStokes___FV1 (Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
Referenced by Init___CompressibleNavierStokes().
Init___CompressibleNavierStokes___FV1() [2/2]
void ug::Init___CompressibleNavierStokes___FV1 (ug::bridge::Registry * reg, std::string grp)
Init___IncompressibleNavierStokes() [1/2]
void ug::Init___IncompressibleNavierStokes (bridge::Registry * reg, std::string grp)
Init___IncompressibleNavierStokes() [2/2]
void ug::Init___IncompressibleNavierStokes (Registry * reg, string grp)
This function is called when the plugin is loaded.
References Init___NavierStokes___FE(), Init___NavierStokes___FV(), Init___NavierStokes___FV1(), Init___NavierStokes___FVCR(), and UG_REGISTRY_CATCH_THROW.
Referenced by InitUGPlugin_NavierStokes().
Init___NavierStokes___FE() [1/2]
void ug::Init___NavierStokes___FE (Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
Referenced by Init___IncompressibleNavierStokes().
Init___NavierStokes___FE() [2/2]
void ug::Init___NavierStokes___FE (ug::bridge::Registry * reg, std::string grp)
Init___NavierStokes___FV() [1/2]
void ug::Init___NavierStokes___FV (Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
Referenced by Init___IncompressibleNavierStokes().
Init___NavierStokes___FV() [2/2]
void ug::Init___NavierStokes___FV (ug::bridge::Registry * reg, std::string grp)
Init___NavierStokes___FV1() [1/2]
void ug::Init___NavierStokes___FV1 (Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
Referenced by Init___IncompressibleNavierStokes().
Init___NavierStokes___FV1() [2/2]
void ug::Init___NavierStokes___FV1 (ug::bridge::Registry * reg, std::string grp)
Init___NavierStokes___FVCR() [1/2]
void ug::Init___NavierStokes___FVCR (Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
Referenced by Init___IncompressibleNavierStokes().
Init___NavierStokes___FVCR() [2/2]
void ug::Init___NavierStokes___FVCR (ug::bridge::Registry * reg, std::string grp)
InitUGPlugin_ConvectionDiffusion()
void ug::InitUGPlugin_ConvectionDiffusion (ug::bridge::Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
InitUGPlugin_DemoPlugin()
void ug::InitUGPlugin_DemoPlugin (Registry * reg, string grp)
This function is called when the plugin is loaded. Make sure that it's name is 'InitUGPlugin_YOURPLUGINNAME', where YOURPLUGINNAME has to match the name you chose for your plugin in the plugin's CMakeLists.txt file.
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_function(), ug::DemoPlugin::DemoMatCompSumFast(), ug::DemoPlugin::DemoMatCompSumSlow(), ug::DemoPlugin::DemoPluginSaysHi(), ug::DemoPlugin::DemoVecCompSum(), and UG_REGISTRY_CATCH_THROW.
InitUGPlugin_DocuGen()
void ug::InitUGPlugin_DocuGen (Registry * reg, string grp)
References ug::bridge::Registry::add_function(), and GenerateScriptReferenceDocu().
InitUGPlugin_Electromagnetism()
void ug::InitUGPlugin_Electromagnetism (Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
InitUGPlugin_Jupyter()
void ug::InitUGPlugin_Jupyter (Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
InitUGPlugin_Limex()
void ug::InitUGPlugin_Limex (Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
InitUGPlugin_LuaShell()
void ug::InitUGPlugin_LuaShell (Registry * reg, string grp)
References ug::bridge::Registry::add_class_(), RegisterDefaultLuaBridge(), and set().
InitUGPlugin_NavierStokes()
void ug::InitUGPlugin_NavierStokes (Registry * reg, string grp)
This function is called when the plugin is loaded.
References Init___CompressibleNavierStokes(), Init___IncompressibleNavierStokes(), and UG_REGISTRY_CATCH_THROW.
InitUGPlugin_ProMesh()
void ug::InitUGPlugin_ProMesh (Registry * reg, string grp)
This function is called when the plugin is loaded.
References ug::promesh::g_promeshRegistry, ug::promesh::GetProMeshRegistry(), ug::promesh::RegisterCoordinateTransformTools(), ug::promesh::RegisterMesh(), ug::promesh::RegisterMeshingTools(), ug::promesh::RegisterMisc(), ug::promesh::RegisterSelectionTools(), ug::promesh::RegisterSubsetTools(), and UG_REGISTRY_CATCH_THROW.
InitUGPlugin_Richards()
void ug::InitUGPlugin_Richards (Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
InitUGPlugin_SmallStrainMechanics()
void ug::InitUGPlugin_SmallStrainMechanics (Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
InitUGPlugin_TemplatePlugin()
void ug::InitUGPlugin_TemplatePlugin (Registry * reg, string grp)
This function is called when the plugin is loaded.
References UG_REGISTRY_CATCH_THROW.
interpolateCRToLagrange()
template<typename TGridFunction > void ug::interpolateCRToLagrange (TGridFunction & uLagrange, TGridFunction & uCR)
domain type
grid type
world dimension
element type
side type
element iterator
vertex iterator
References ug::LFEID::CROUZEIX_RAVIART, dim, DoFRef(), grid(), ug::PeriodicBoundaryManager::is_slave(), ug::LFEID::LAGRANGE, ug::DimFV1Geometry< TDim, TWorldDim >::SCV::local_ip(), s, ug::DimFV1Geometry< TDim, TWorldDim >::scv(), SetAttachmentValues(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), UG_ASSERT, UG_THROW, ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
Referenced by ug::NavierStokes::FunctionalityIncomp::DomainAlgebra().
kineticEnergy()
template<typename TGridFunction > number ug::kineticEnergy (TGridFunction & u)
domain type
world dimension
element iterator
element type
side type
grid type
References ug::LFEID::CROUZEIX_RAVIART, dim, DoFRef(), ug::DimReferenceMapping< TDim, TWorldDim >::global_to_local(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scv(), num_subsets(), s, ug::DimCRFVGeometry< TDim, TWorldDim >::scv(), ug::LocalShapeFunctionSet< TDim, class, class >::shapes(), UG_ASSERT, UG_LOG, ug::DimCRFVGeometry< TDim, TWorldDim >::update(), and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::volume().
Referenced by ug::NavierStokes::FunctionalityIncomp::DomainAlgebra().
MeasureTetrahedronWithSmallestMinAngle()
void ug::MeasureTetrahedronWithSmallestMinAngle (MultiGrid & grid)
References aPosition, ug::MultiGridSubsetHandler::assign_subset(), ug::Selector::begin(), ug::MultiGridSubsetHandler::begin(), ug::GridObjectCollection::begin(), CalculateVolume(), CloseSelection(), ug::Selector::end(), ug::MultiGridSubsetHandler::end(), ug::GridObjectCollection::end(), FindElementWithSmallestMinAngle(), grid(), ug::GridObjectCollection::num_levels(), ug::ISelector::select(), ug::ISubsetHandler::set_subset_name(), and UG_LOG.
Referenced by InitUGPlugin_ElementQualityStatistics().
MyPrintError()
static void ug::MyPrintError (UGError & err) static
References ug::UGError::get_file(), ug::UGError::get_line(), ug::UGError::get_msg(), ug::UGError::num_msg(), and UG_LOG.
Referenced by ug::LimexTimeIntegrator< TDomain, TAlgebra >::apply_integrator_threads().
OrderCRCuthillMcKee()
template<typename TDomain , typename TGridFunction > void ug::OrderCRCuthillMcKee (ApproximationSpace< TDomain > & approxSpace, TGridFunction & u, bool bReverse)
orders the all DofDistributions of the ApproximationSpace using Cuthill-McKee
domain type
world dimension
element type
References ComputeCRCuthillMcKeeOrder(), ug::LFEID::CROUZEIX_RAVIART, dim, ug::IApproximationSpace::dof_distributions(), ug::LFEID::PIECEWISE_CONSTANT, and UG_THROW.
Referenced by ug::NavierStokes::FunctionalityFVCR::DomainAlgebra().
PrintAngleHistogram()
void ug::PrintAngleHistogram (vector< number > & locAngles, number stepSize, ug::Table< std::stringstream > & outTable)
References ug::Table< class >::add_cols(), ug::Table< class >::add_rows(), pcl::ProcessCommunicator::allgatherv(), and UG_LOG.
Referenced by ElementQualityStatistics3d().
PrintAngleStatistics2d()
template<class TAAPosVRT > void ug::PrintAngleStatistics2d (Grid & grid, GridObjectCollection & goc, int level, TAAPosVRT & aaPos)
References pcl::ProcessCommunicator::allreduce(), ug::GridObjectCollection::begin(), CalculateAngles(), ug::DistributedGridManager::contains_status(), ug::GridObjectCollection::end(), ES_H_SLAVE, grid(), ug::DistributedGridManager::is_ghost(), ug::GridObjectCollection::num(), pcl::NumProcs(), PCL_RO_SUM, ug::Face::reference_object_id(), ROID_QUADRILATERAL, ROID_TRIANGLE, and UG_LOG.
Referenced by ElementQualityStatistics2d().
PrintAngleStatistics3d()
template<class TAAPosVRT > void ug::PrintAngleStatistics3d (Grid & grid, GridObjectCollection & goc, int level, TAAPosVRT & aaPos)
References pcl::ProcessCommunicator::allreduce(), ug::GridObjectCollection::begin(), CalculateAngles(), ug::DistributedGridManager::contains_status(), ug::GridObjectCollection::end(), ES_H_SLAVE, grid(), ug::DistributedGridManager::is_ghost(), ug::GridObjectCollection::num(), pcl::NumProcs(), PCL_RO_SUM, ug::Volume::reference_object_id(), ug::Face::reference_object_id(), ROID_HEXAHEDRON, ROID_OCTAHEDRON, ROID_QUADRILATERAL, ROID_TETRAHEDRON, ROID_TRIANGLE, and UG_LOG.
Referenced by ElementQualityStatistics3d().
PrintAspectRatioHistogram()
void ug::PrintAspectRatioHistogram (vector< number > & locAspectRatios, number stepSize, ug::Table< std::stringstream > & outTable)
References ug::Table< class >::add_cols(), ug::Table< class >::add_rows(), pcl::ProcessCommunicator::allgatherv(), and UG_LOG.
Referenced by ElementQualityStatistics3d().
PrintVertexVolumeValence()
void ug::PrintVertexVolumeValence (MultiGrid & mg, SubsetHandler & sh, int subsetIndex)
References aPosition, ug::Grid::attach_to_vertices_dv(), ug::MultiGrid::begin(), ug::MultiGrid::end(), ug::ISubsetHandler::get_subset_index(), ug::VolumeVertices::num_vertices(), ug::MultiGrid::top_level(), UG_LOG, and ug::VolumeVertices::vertex().
Referenced by InitUGPlugin_ElementQualityStatistics().
vorticity()
template<typename TGridFunction > void ug::vorticity (TGridFunction & vort, TGridFunction & u)
References ug::LFEID::CROUZEIX_RAVIART, dim, ug::LFEID::LAGRANGE, and UG_LOG.
Referenced by ug::NavierStokes::FunctionalityIncomp::DomainAlgebra().
vorticityFV1()
template<typename TGridFunction > void ug::vorticityFV1 (TGridFunction & vort, TGridFunction & u)
domain type
grid type
world dimension
element type
element iterator
side iterator
References dim, DoFRef(), ug::DimFV1Geometry< TDim, TWorldDim >::SCV::global_grad(), grid(), ug::PeriodicBoundaryManager::is_slave(), ug::LFEID::LAGRANGE, ug::DimFV1Geometry< TDim, TWorldDim >::SCV::num_sh(), ug::DimFV1Geometry< TDim, TWorldDim >::scv(), SetAttachmentValues(), UG_THROW, ug::DimFV1Geometry< TDim, TWorldDim >::update(), and ug::DimFV1Geometry< TDim, TWorldDim >::SCV::volume().
vorticityFVCR()
template<typename TGridFunction > void ug::vorticityFVCR (TGridFunction & vort, TGridFunction & u)
domain type
grid type
world dimension
element type
side type
element iterator
side iterator
References ug::LFEID::CROUZEIX_RAVIART, dim, DoFRef(), ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::global_grad(), grid(), ug::PeriodicBoundaryManager::is_slave(), ug::DimCRFVGeometry< TDim, TWorldDim >::num_scv(), s, ug::DimCRFVGeometry< TDim, TWorldDim >::scv(), SetAttachmentValues(), UG_ASSERT, UG_THROW, ug::DimCRFVGeometry< TDim, TWorldDim >::update(), and ug::DimCRFVGeometry< TDim, TWorldDim >::SCV::volume().
Variable Documentation
LIB_LIMEX
DebugID ug::LIB_LIMEX ("LIB_LIMEX")
Referenced by ug::LinearImplicitEuler< TAlgebra >::adjust_solution(), ug::LimexTimeIntegrator< TDomain, TAlgebra >::apply(), ug::LinearImplicitEuler< TAlgebra >::assemble_defect(), ug::LinearImplicitEuler< TAlgebra >::assemble_jacobian(), ug::LinearImplicitEuler< TAlgebra >::assemble_linear(), ug::LinearImplicitEuler< TAlgebra >::finish_step_elem(), ug::LinearImplicitEuler< TAlgebra >::prepare_step(), and ug::LinearImplicitEuler< TAlgebra >::prepare_step_elem().