Plugins: ug::Richards Namespace Reference
ug::Richards Namespace Reference
Classes
struct BrooksCoreyFunctions
struct ConductivityAdapter
Returns conductivities (note: corresponds to relative permeability, iff Ksat=1.0).
struct ExponentialConductivity
class ExponentialModel
Implement a simple exponential model.
struct ExponentialModelParameters
struct ExponentialSaturation
struct Functionality
class GardnerConductivity
class GardnerModel
Implements a van Genuchten model.
class GardnerSaturation
class HaverkampConductivity
class HaverkampModel
Implements a Haverkamp model.
struct HaverkampParameters
class HaverkampSaturation
struct IParameterizedModel
Base class for a parameterized model. Provides serialization.
struct IRichardsLinker
This is a 'dummy' base class. It indicates a pressure dependent linker.
class IRichardsModel
This is the interface for a Richards-type model. All derived classes use CRTP for evaluation.
class OnSurfaceCondition
struct RichardsConductivity
class RichardsElemDisc
class RichardsElemDiscFactory
! Factory for creating elem discs.
class RichardsLinker
Prototype of a linker. Returns values depending on the Functor class.
struct RichardsSaturation
van Genuchten classes. (ideally, those could be type-def'ed as well..)
struct SaturationAdapter
Returns saturations.
class UserDataFactory
Factory class. This constructs appropriate "UserData" from suitable models.
struct VanGenuchtenFunctions
class VanGenuchtenModel
Implements a van Genuchten-Mualem model.
struct VanGenuchtenParameters
Typedefs
typedef autodiff::dual dual
typedef ConductivityAdapter< GardnerModel > GardnerConductivityAdapter
typedef SaturationAdapter< GardnerModel > GardnerSaturationAdapter
typedef ConductivityAdapter< HaverkampModel > HaverkampConductivityAdapter
typedef SaturationAdapter< HaverkampModel > HaverkampSaturationAdapter
template<int dim>
using VanGenuchtenConductivity = RichardsLinker< dim, vanGenuchtenConductivityAdapter >
typedef ConductivityAdapter< VanGenuchtenModel > vanGenuchtenConductivityAdapter
template<int dim>
using VanGenuchtenSaturation = RichardsLinker< dim, vanGenuchtenSaturationAdapter >
typedef SaturationAdapter< VanGenuchtenModel > vanGenuchtenSaturationAdapter
Shortcuts for van Genuchten.
Functions
void CrashFct (const string &reason)
void CrashFctFatal (const string &reason)
void RichardsCrashes ()
void RichardsCrashesFatal ()
void RichardsSaysHello ()
template<typename TDomain >
void SelectVTKData (SmartPtr< VTKOutput< TDomain::dim > > spVtk, SmartPtr< RichardsElemDisc< TDomain > > spElemDisc, const char *myTag)
void UGCheckValues (const dual &number)
Typedef Documentation
dual
typedef autodiff::dual ug::Richards::dual
GardnerConductivityAdapter
typedef ConductivityAdapter<GardnerModel> ug::Richards::GardnerConductivityAdapter
GardnerSaturationAdapter
typedef SaturationAdapter<GardnerModel> ug::Richards::GardnerSaturationAdapter
HaverkampConductivityAdapter
typedef ConductivityAdapter<HaverkampModel> ug::Richards::HaverkampConductivityAdapter
HaverkampSaturationAdapter
typedef SaturationAdapter<HaverkampModel> ug::Richards::HaverkampSaturationAdapter
VanGenuchtenConductivity
template<int dim> using ug::Richards::VanGenuchtenConductivity = typedef RichardsLinker<dim,vanGenuchtenConductivityAdapter>
vanGenuchtenConductivityAdapter
typedef ConductivityAdapter<VanGenuchtenModel> ug::Richards::vanGenuchtenConductivityAdapter
VanGenuchtenSaturation
template<int dim> using ug::Richards::VanGenuchtenSaturation = typedef RichardsLinker<dim,vanGenuchtenSaturationAdapter>
vanGenuchtenSaturationAdapter
typedef SaturationAdapter<VanGenuchtenModel> ug::Richards::vanGenuchtenSaturationAdapter
Shortcuts for van Genuchten.
Function Documentation
SelectVTKData()
template<typename TDomain > void ug::Richards::SelectVTKData (SmartPtr< VTKOutput< TDomain::dim > > spVtk, SmartPtr< RichardsElemDisc< TDomain > > spElemDisc, const char * myTag)
References dim.
UGCheckValues()
void ug::Richards::UGCheckValues (const dual & number) inline
References UG_ASSERT.
Referenced by ug::Richards::BrooksCoreyFunctions::ComputeEffectiveSaturation(), ug::Richards::VanGenuchtenFunctions::ComputeEffectiveSaturation(), ug::Richards::ExponentialModel::RelativePermeability_(), ug::Richards::VanGenuchtenModel::RelativePermeability_(), ug::Richards::ExponentialModel::Saturation_(), and ug::Richards::VanGenuchtenModel::Saturation_().