Plugins: ug::tools Namespace Reference
ug::tools Namespace Reference
Functions
void VecScaleAddWithNorm2 (double &vUpdate, double alpha2, const double &vFine, double alpha3, const double &vCoarse, double &norm)
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse. for doubles
template<typename vector_t , template< class T > class TE_VEC>
void VecScaleAddWithNorm2 (TE_VEC< vector_t > &vUpdate, double alpha2, const TE_VEC< vector_t > &vFine, double alpha3, const TE_VEC< vector_t > &vCoarse, double &norm, const int delta=1, const int offset=0)
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse
void VecScaleAddWithNormInf (double &vUpdate, double alpha2, const double &vFine, double alpha3, const double &vCoarse, double &norm)
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse. for doubles
template<typename vector_t , template< class T > class TE_VEC>
void VecScaleAddWithNormInf (TE_VEC< vector_t > &vUpdate, double alpha2, const TE_VEC< vector_t > &vFine, double alpha3, const TE_VEC< vector_t > &vCoarse, double &norm, const int delta=1, const int offset=0)
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse
void VecScaleAddWithNormRel (double &vUpdate, double alpha2, const double &vFine, double alpha3, const double &vCoarse, double &norm)
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse. for doubles
template<typename vector_t , template< class T > class TE_VEC>
void VecScaleAddWithNormRel (TE_VEC< vector_t > &vUpdate, double alpha2, const TE_VEC< vector_t > &vFine, double alpha3, const TE_VEC< vector_t > &vCoarse, double &norm)
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse
Function Documentation
VecScaleAddWithNorm2() [1/2]
void ug::tools::VecScaleAddWithNorm2 (double & vUpdate, double alpha2, const double & vFine, double alpha3, const double & vCoarse, double & norm) inline
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse. for doubles
Referenced by ug::Norm2Estimator< TVector >::update(), and VecScaleAddWithNorm2().
VecScaleAddWithNorm2() [2/2]
template<typename vector_t , template< class T > class TE_VEC> void ug::tools::VecScaleAddWithNorm2 (TE_VEC< vector_t > & vUpdate, double alpha2, const TE_VEC< vector_t > & vFine, double alpha3, const TE_VEC< vector_t > & vCoarse, double & norm, const int delta = 1, const int offset = 0) inline
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse
References VecScaleAddWithNorm2().
VecScaleAddWithNormInf() [1/2]
void ug::tools::VecScaleAddWithNormInf (double & vUpdate, double alpha2, const double & vFine, double alpha3, const double & vCoarse, double & norm) inline
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse. for doubles
Referenced by ug::NormInfEstimator< TVector >::update(), and VecScaleAddWithNormInf().
VecScaleAddWithNormInf() [2/2]
template<typename vector_t , template< class T > class TE_VEC> void ug::tools::VecScaleAddWithNormInf (TE_VEC< vector_t > & vUpdate, double alpha2, const TE_VEC< vector_t > & vFine, double alpha3, const TE_VEC< vector_t > & vCoarse, double & norm, const int delta = 1, const int offset = 0) inline
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse
References VecScaleAddWithNormInf().
VecScaleAddWithNormRel() [1/2]
void ug::tools::VecScaleAddWithNormRel (double & vUpdate, double alpha2, const double & vFine, double alpha3, const double & vCoarse, double & norm) inline
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse. for doubles
Referenced by ug::NormRelEstimator< TVector >::update(), and VecScaleAddWithNormRel().
VecScaleAddWithNormRel() [2/2]
template<typename vector_t , template< class T > class TE_VEC> void ug::tools::VecScaleAddWithNormRel (TE_VEC< vector_t > & vUpdate, double alpha2, const TE_VEC< vector_t > & vFine, double alpha3, const TE_VEC< vector_t > & vCoarse, double & norm) inline
calculates vUpdate = vUpdate + alpha2*vFine + alpha3*vCoarse
References VecScaleAddWithNormRel().