Plugins: ug::promesh Namespace Reference
ug::promesh Namespace Reference
Namespaces
detail
Classes
class AnisoElemInfo
class Box
class ElementIterator
class Mesh
class MeshObject
class ProMeshRegistry
Register functions for ug-script and ProMesh through this class.
Enumerations
enum CSGOperation { CSG_UNION , CSG_INTERSECTION , CSG_DIFFERENCE }
enum ModifierKeys { MK_NONE = 0 , MK_CTRL = 1 , MK_SHIFT = 2 , MK_ALT = 4 }
enum RegistryTargets {
RT_NONE = 0 , RT_UGSCRIPT = 1 , RT_PROMESH = 1 << 1 , RT_DEFAULT = RT_UGSCRIPT | RT_PROMESH ,
RT_NO_PROMESH = RT_UGSCRIPT , RT_NO_UGSCRIPT = RT_PROMESH
}
enum ShortcutKeys {
Key_Escape = 0x01000000 , Key_Tab = 0x01000001 , Key_Backtab = 0x01000002 , Key_Backspace = 0x01000003 ,
Key_Return = 0x01000004 , Key_Enter = 0x01000005 , Key_Insert = 0x01000006 , Key_Delete = 0x01000007 ,
Key_Pause = 0x01000008 , Key_Print = 0x01000009 , Key_SysReq = 0x0100000a , Key_Clear = 0x0100000b ,
Key_Home = 0x01000010 , Key_End = 0x01000011 , Key_Left = 0x01000012 , Key_Up = 0x01000013 ,
Key_Right = 0x01000014 , Key_Down = 0x01000015 , Key_PageUp = 0x01000016 , Key_PageDown = 0x01000017 ,
Key_Shift = 0x01000020 , Key_Control = 0x01000021 , Key_Meta = 0x01000022 , Key_Alt = 0x01000023 ,
Key_AltGr = 0x01001103 , Key_CapsLock = 0x01000024 , Key_NumLock = 0x01000025 , Key_ScrollLock = 0x01000026 ,
Key_F1 = 0x01000030 , Key_F2 = 0x01000031 , Key_F3 = 0x01000032 , Key_F4 = 0x01000033 ,
Key_F5 = 0x01000034 , Key_F6 = 0x01000035 , Key_F7 = 0x01000036 , Key_F8 = 0x01000037 ,
Key_F9 = 0x01000038 , Key_F10 = 0x01000039 , Key_F11 = 0x0100003a , Key_F12 = 0x0100003b ,
Key_F13 = 0x0100003c , Key_F14 = 0x0100003d , Key_F15 = 0x0100003e , Key_F16 = 0x0100003f ,
Key_F17 = 0x01000040 , Key_F18 = 0x01000041 , Key_F19 = 0x01000042 , Key_F20 = 0x01000043 ,
Key_F21 = 0x01000044 , Key_F22 = 0x01000045 , Key_F23 = 0x01000046 , Key_F24 = 0x01000047 ,
Key_F25 = 0x01000048 , Key_F26 = 0x01000049 , Key_F27 = 0x0100004a , Key_F28 = 0x0100004b ,
Key_F29 = 0x0100004c , Key_F30 = 0x0100004d , Key_F31 = 0x0100004e , Key_F32 = 0x0100004f ,
Key_F33 = 0x01000050 , Key_F34 = 0x01000051 , Key_F35 = 0x01000052 , Key_Super_L = 0x01000053 ,
Key_Super_R = 0x01000054 , Key_Menu = 0x01000055 , Key_Hyper_L = 0x01000056 , Key_Hyper_R = 0x01000057 ,
Key_Help = 0x01000058 , Key_Direction_L = 0x01000059 , Key_Direction_R = 0x01000060 , Key_Space = 0x20 ,
Key_Any = 0x20 , Key_Exclam = 0x21 , Key_QuoteDbl = 0x22 , Key_NumberSign = 0x23 ,
Key_Dollar = 0x24 , Key_Percent = 0x25 , Key_Ampersand = 0x26 , Key_Apostrophe = 0x27 ,
Key_ParenLeft = 0x28 , Key_ParenRight = 0x29 , Key_Asterisk = 0x2a , Key_Plus = 0x2b ,
Key_Comma = 0x2c , Key_Minus = 0x2d , Key_Period = 0x2e , Key_Slash = 0x2f ,
Key_0 = 0x30 , Key_1 = 0x31 , Key_2 = 0x32 , Key_3 = 0x33 ,
Key_4 = 0x34 , Key_5 = 0x35 , Key_6 = 0x36 , Key_7 = 0x37 ,
Key_8 = 0x38 , Key_9 = 0x39 , Key_Colon = 0x3a , Key_Semicolon = 0x3b ,
Key_Less = 0x3c , Key_Equal = 0x3d , Key_Greater = 0x3e , Key_Question = 0x3f ,
Key_At = 0x40 , Key_A = 0x41 , Key_B = 0x42 , Key_C = 0x43 ,
Key_D = 0x44 , Key_E = 0x45 , Key_F = 0x46 , Key_G = 0x47 ,
Key_H = 0x48 , Key_I = 0x49 , Key_J = 0x4a , Key_K = 0x4b ,
Key_L = 0x4c , Key_M = 0x4d , Key_N = 0x4e , Key_O = 0x4f ,
Key_P = 0x50 , Key_Q = 0x51 , Key_R = 0x52 , Key_S = 0x53 ,
Key_T = 0x54 , Key_U = 0x55 , Key_V = 0x56 , Key_W = 0x57 ,
Key_X = 0x58 , Key_Y = 0x59 , Key_Z = 0x5a , Key_BracketLeft = 0x5b ,
Key_Backslash = 0x5c
}
Functions
void AdaptSurfaceToCylinder (Mesh *obj, number radius, number threshold)
void AdjustEdgeLength (Mesh *obj, number minEdgeLen, number maxEdgeLen, int numIterations, bool adaptive, bool automarkBoundaries)
void AdjustEdgeLengthExtended (Mesh *obj, number minEdgeLen, number maxEdgeLen, number approximation, number triQuality, int numIterations, bool automarkBoundaries)
void AdjustEdgeOrientation (Mesh *obj)
void AdjustSubsetsForUG3 (Mesh *obj, bool keepIntfSubs)
void AdjustSubsetsForUG4 (Mesh *obj, bool preserveExistingSubsets)
void AssignNewSubset (Mesh *obj, const char *name, bool vertices, bool edges, bool faces, bool volumes)
void AssignSubset (Mesh *obj, int newIndex)
void AssignSubset (Mesh *obj, int newIndex, bool vertices, bool edges, bool faces, bool volumes)
void AssignSubsetColors (Mesh *obj)
template<class elem_t >
void AssignSubsetsByAspectRatio (Mesh *msh, int numHistoSecs, bool eraseOldSubsets)
template void AssignSubsetsByAspectRatio< Face > (Mesh *, int, bool)
template void AssignSubsetsByAspectRatio< Volume > (Mesh *, int, bool)
void AssignSubsetsByElementType (Mesh *obj)
void AssignSubsetsByQuality (Mesh *obj, int numSections)
void AssignSubsetsFromRaster (Mesh *obj, const char *rasterFileName, int rasterDimension, bool vertices, bool edges, bool faces, bool volumes)
template<int dim, class elem_t >
void AssignSubsetsFromRaster_IMPL (Mesh *obj, const char *rasterFileName)
template<int dim>
void AssignSubsetsFromRaster_IMPL (Mesh *obj, const char *rasterFileName, bool vertices, bool edges, bool faces, bool volumes)
void AssignVolumeConstraints (Mesh *obj, number volConstraint)
void ClearMarks (Mesh *obj)
void ClearSelection (Mesh *obj)
void ClearVolumeConstraints (Mesh *obj)
SmartPtr< Mesh > CloneMesh (Mesh *mesh)
void CloseSelection (Mesh *obj)
void CollapseEdge (Mesh *obj)
void ConeTransform (Mesh *obj, const vector3 &base, const vector3 &axis, number scaleAtTip)
void ConvertToQuadrilaterals (Mesh *obj)
void ConvertToTetrahedra (Mesh *obj)
void ConvertToTriangles (Mesh *obj)
template<class TElem >
void CopySelectedElements (Mesh *srcMesh, Mesh *destMesh, AVertex aNewVrt)
void CopySelection (Mesh *srcMesh, Mesh *destMesh)
void CopySubsetIndicesToSides (Mesh *obj, bool selectionOnly, bool toUnassignedOnly)
void CreateBox (Mesh *obj, const vector3 &boxMin, const vector3 &boxMax, int subsetInd, bool fill)
void CreateCircle (Mesh *obj, const vector3 &center, number radius, int numRimVertices, int subsetInd, bool fill)
Edge * CreateEdge (Mesh *obj, int subsetInd)
Face * CreateFace (Mesh *obj, int subsetInd)
void CreateHexahedraFromSelectedPrisms (Mesh *obj)
void CreatePlane (Mesh *obj, const vector3 &upLeft, const vector3 &upRight, const vector3 &lowLeft, const vector3 &lowRight, int subsetInd, bool fill)
void CreatePlane (Mesh *obj, number width, number height, const vector3 &center, int subsetInd, bool fill)
void CreatePrism (Mesh *obj, int subsetInd, bool fill)
void CreatePyramid (Mesh *obj, int subsetInd, bool fill)
template<class TElemIter >
void CreateShrinkElements (Mesh *obj, number scale, TElemIter elemsBegin, TElemIter elemsEnd)
void CreateShrinkGeometry (Mesh *obj, number scale)
void CreateSphere (Mesh *obj, const vector3 &center, number radius, int numRefinements, int subsetInd)
void CreateTetrahedron (Mesh *obj, int subsetInd, bool fill)
void CreateTKD (Mesh *obj, int subsetInd, number a, number w, number h)
void CreateTKDWithOuterLayer (Mesh *obj, int innerSubsetInd, int outerSubsetInd, number a, number w, number h, number d)
Vertex * CreateVertex (Mesh *obj, const vector3 &pos, int subsetInd)
Volume * CreateVolume (Mesh *obj, int subsetInd)
void CSGFaceDifference (Mesh *obj, int subsetIndex0, int subsetIndex1, number snapThreshold)
void CSGFaceIntersection (Mesh *obj, int subsetIndex0, int subsetIndex1, number snapThreshold)
void CSGFaceOperation (Mesh *obj, CSGOperation op, int subsetIndex0, int subsetIndex1, number snapThreshold)
void CSGFaceUnion (Mesh *obj, int subsetIndex0, int subsetIndex1, number snapThreshold)
void DeselectAllEdges (Mesh *obj)
void DeselectAllFaces (Mesh *obj)
void DeselectAllVertices (Mesh *obj)
void DeselectAllVolumes (Mesh *obj)
void Duplicate (Mesh *obj, const vector3 &offset, bool deselectOld, bool selectNew)
void EdgeSelectionFill (Mesh *obj)
void EraseEmptySubsets (Mesh *obj)
void EraseSelectedElements (Mesh *obj, bool eraseUnusedVrts, bool eraseUnusedEdges, bool eraseUnusedFaces)
void EraseSubset (Mesh *obj, int si, bool eraseGeometry)
bool ExportToUG3 (Mesh *obj, const char *filenamePrefix, const char *lgmName, const char *problemName)
void ExtendSelection (Mesh *obj, int neighborhoodSize)
void ExtendSelectionInDirection (Mesh *obj, int neighborhoodSize, const vector3 &dir, number minAngle, number maxAngle)
void ExtrudeAlongNormal (Mesh *obj, number totalLength, int numSteps, bool createFaces, bool createVolumes)
void ExtrudeAndMove (Mesh *obj, const vector3 &totalDir, int numSteps, bool createFaces, bool createVolumes)
void ExtrudeAndScale (Mesh *obj, number totalScale, bool scaleAroundPivot, int numSteps, bool createFaces, bool createVolumes)
void ExtrudeCylinders (Mesh *obj, number height, number radius, number snapThreshold)
void ExtrudeFacesWithTets (Mesh *obj, int fromSi, int toSi, const number factor)
void ExtrudeLayers (Mesh *obj, RasterLayers &layers, bool allowForTetsAndPyras)
void ExtrudeLayersAndAddProjector (Mesh *obj, SPRasterLayers layers, bool allowForTetsAndPyras)
void ExtrudeToThickness (Mesh *obj, number thickness, int numSteps, bool createFaces, bool createVolumes)
void FaceSelectionFill (Mesh *obj)
void FixFaceOrientation (Mesh *obj)
void FixFaceSubsetOrientations (Mesh *obj)
template<class elem_t , class vrt_iter_t >
static void FixMirrorOrientation (Grid &g, vrt_iter_t vrtsBegin, vrt_iter_t vrtsEnd)
int FixVolumeOrientation (Mesh *obj)
void FlattenBentQuadrilaterals (Mesh *obj, number stepSize, int numIterations)
SmartPtr< Box > GetBoundingBox (Mesh *obj)
ProMeshRegistry & GetProMeshRegistry ()
bool GetSelectionCenter (Mesh *obj, vector3 &centerOut)
void HangingNodeRefine (Mesh *obj, bool anisotropic)
void HangingNodeRefine (Mesh *obj, bool strictSubsetInheritance, bool anisotropic)
void InsertCenter (Mesh *obj)
void InsertCenter (Mesh *obj, bool strictSubsetInheritance)
void IntersectCloseEdges (Mesh *obj, number snapThreshold)
void InvertFaceOrientation (Mesh *obj)
void InvertSelection (Mesh *obj, bool invVrts, bool invEdges, bool invFaces, bool invVols)
void JoinSubsets (Mesh *obj, int target, int si1, int si2, bool eraseUnused)
void LaplacianSmooth (Mesh *obj, number alpha, int numIterations)
bool LoadMesh (Mesh *obj, const char *filename)
void MarkCornersOfMarkedEdges (Mesh *obj, number angle)
void MarkCreaseEdges (Mesh *obj, number minAngle, bool clearMarks)
void MarkSelection (Mesh *obj)
number MeasureGridArea (Mesh *obj)
number MeasureGridLength (Mesh *obj)
number MeasureGridVolume (Mesh *obj)
number MeasureSelectionArea (Mesh *obj)
number MeasureSelectionLength (Mesh *obj)
number MeasureSelectionVolume (Mesh *obj)
number MeasureSubsetArea (Mesh *obj, int subsetInd)
number MeasureSubsetLength (Mesh *obj, int subsetInd)
number MeasureSubsetVolume (Mesh *obj, int subsetInd)
void MergeAtCenter (Mesh *obj)
void MergeAtFirst (Mesh *obj)
void MergeAtLast (Mesh *obj)
void MeshLayerBoundaries (Mesh *m, const RasterLayers &layers)
void MeshLayers (Mesh *m, const RasterLayers &layers)
void Mirror (Mesh *obj, const vector3 &axisOrig, const vector3 &origin)
void Move (Mesh *obj, const vector3 &offset)
void MoveAlongNormal (Mesh *obj, number offset)
void MoveMeshTo (Mesh *obj, const vector3 &newPos)
bool MoveSelectionTo (Mesh *obj, const vector3 &center)
void MoveSubset (Mesh *obj, int oldIndex, int newIndex)
void MoveVerticesAlongEdges (Mesh *obj, number relVal)
void MoveVerticesToEdgeLength (Mesh *obj, number edgeLen)
void MoveVerticesToProjectedEdgeLength (Mesh *obj, number projEdgeLen, const vector3 &projNormal)
void PlaneCut (Mesh *obj, const vector3 &p, const vector3 &n)
template<class elem_t >
void PrintAspectRatioHistogram (Mesh *msh, int numHistoSecs)
template void PrintAspectRatioHistogram< Face > (Mesh *msh, int numHistoSecs)
template void PrintAspectRatioHistogram< Volume > (Mesh *msh, int numHistoSecs)
template<class elem_t >
void PrintAspectRatios (Mesh *msh)
template void PrintAspectRatios< Face > (Mesh *)
template void PrintAspectRatios< Volume > (Mesh *)
number ProjectedDistance (Mesh *obj, const vector3 &projectionNormal)
void ProjectToLayer (Mesh *obj, RasterLayers &layers, int layerIndex)
void ProjectToLimitPLoop (Mesh *obj)
void ProjectToLimitSmoothBoundary (Mesh *obj)
void ProjectToPlane (Mesh *obj, const vector3 &planeCenter, const vector3 &planeNormal)
void ProjectToTopLayer (Mesh *obj, RasterLayers &layers)
void ProjectVerticesToCloseEdges (Mesh *obj, number snapThreshold)
void ProjectVerticesToCloseFaces (Mesh *obj, number snapThreshold)
void Refine (Mesh *obj)
void Refine (Mesh *obj, bool strictSubsetInheritance, bool useSnapPoints)
void RefineSmooth (Mesh *obj)
void RefineSmooth (Mesh *obj, bool strictSubsetInheritance)
void RefineWithSnapPoints (Mesh *obj)
void RefineWithSnapPointsOrtho (Mesh *obj)
void RegisterCoordinateTransformTools (ProMeshRegistry &reg, std::string grp)
void RegisterCoordinateTransformTools (ProMeshRegistry &reg, string baseGrp)
template<class TElem >
static void RegisterElementIterators (ProMeshRegistry &reg, string name, string grp)
helper function to register mesh-element-iterators
void RegisterMesh (ProMeshRegistry &reg, std::string grp)
void RegisterMesh (ProMeshRegistry &reg, string baseGrp)
void RegisterMeshingTools (ProMeshRegistry &reg, std::string grp)
void RegisterMeshingTools (ProMeshRegistry &reg, string baseGrp)
template<class TElem >
static void RegisterMeshIteratorMethods (ExportedClass< Mesh > &cls, string elemName)
static void RegisterMisc (ProMeshRegistry &reg, string baseGrp)
void RegisterSelectionTools (ProMeshRegistry &reg, std::string grp)
void RegisterSelectionTools (ProMeshRegistry &reg, string baseGrp)
void RegisterSubsetTools (ProMeshRegistry &reg, std::string baseGrp)
void RegularizingRefinement (Mesh *obj, const number aspectRatio)
template<class TElem >
void RegularizingRefinement_IMPL (Mesh *obj, const number aspectRatio)
size_t RemoveDoubleEdges (Mesh *obj)
size_t RemoveDoubleFaces (Mesh *obj)
size_t RemoveDoubles (Mesh *obj, number threshold)
returns the number of removed vertices
void ReplaceLowValenceVertices (Mesh *obj, number maxSquaredHeightToBaseAreaRatio)
void ReplaceValence3Vertices (Mesh *obj, number maxSquaredHeightToBaseAreaRatio)
void ResolveEdgeIntersection (Mesh *obj, number snapThreshold)
void ResolveSelfIntersections (Mesh *obj, number snapThreshold)
void ResolveTriangleIntersections (Mesh *obj, number snapThreshold)
void RestrictSelectionToSubset (Mesh *obj, int si)
template<class TElem >
void RestrictSelectionToSubset (Selector &sel, const SubsetHandler &sh, int si)
void Retetrahedralize (Mesh *obj, number quality, bool preserveOuter, bool preserveAll, bool applyVolumeConstraint, int verbosity)
void Retriangulate (Mesh *obj, number minAngle)
void RotateAroundCenter (Mesh *obj, const vector3 &rotRad)
void RotateAroundPivot (Mesh *obj, const vector3 &rotRad)
bool SaveMesh (Mesh *obj, const char *filename)
void ScaleAroundCenter (Mesh *obj, const vector3 &scale)
void ScaleAroundPivot (Mesh *obj, const vector3 &scale)
void ScaleAroundPoint (Mesh *obj, const vector3 &scale, const vector3 &point)
void SelectAll (Mesh *obj)
void SelectAllEdges (Mesh *obj)
void SelectAllFaces (Mesh *obj)
void SelectAllVertices (Mesh *obj)
void SelectAllVolumes (Mesh *obj)
template<class TElem >
void SelectAnisotropicElements (Mesh *obj, number minEdgeRatio)
void SelectAssociatedEdges (Mesh *obj)
void SelectAssociatedFaces (Mesh *obj)
void SelectAssociatedVertices (Mesh *obj)
size_t SelectBentQuadrilaterals (Mesh *obj, number dotThreshold)
void SelectBoundaryEdges (Mesh *obj)
void SelectBoundaryFaces (Mesh *obj)
void SelectBoundaryVertices (Mesh *obj)
Edge * SelectClosestEdge (Mesh *m, const vector3 &coord)
void SelectCreaseEdges (Mesh *obj, number minAngle)
void SelectDegenerateFaces (Mesh *obj, number maxHeight)
bool SelectEdgeByIndex (Mesh *obj, int index)
void SelectEdgesByDirection (Mesh *m, const vector3 &dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
template<class TElem >
TElem * SelectElemByCoordinate (Mesh *obj, const vector3 &coord)
template<class TElem >
TElem * SelectElemByCylindricalCoordinate (Mesh *obj, number rho, number phi, number z)
void SelectElementsByIndexRange (Mesh *obj, const char *vrtRanges, const char *edgeRanges, const char *faceRanges, const char *volRanges, bool clearSelection)
void SelectElementsBySplitPlane (Mesh *obj, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVols, const vector3 &pivot, const vector3 &normal)
template<class elem_t , class vector_t , class AAPos >
static void SelectElementsBySplitPlane_IMPL (Grid &g, Selector &sel, const vector_t &pivot, const vector_t &normal, AAPos aaPos)
template<class TElem >
void SelectElementsInBox (Mesh *obj, const vector3 &min, const vector3 &max)
Selects elements whose center lie in a box.
template<int icoord, int selFlag>
void SelectElementsInCoordinateRange (Mesh *mesh, number min, number max, bool vrts, bool edges, bool faces, bool vols)
template<int icoord, int selFlag, class TElem >
void SelectElementsInCoordinateRange (Mesh *obj, number min, number max)
template<class TElem >
void SelectElementsInCylinder (Mesh *obj, const vector3 &cylBase, const vector3 &cylTop, number radius)
Selects elements whose center lie in a cylinder.
bool SelectFaceByIndex (Mesh *obj, int index)
void SelectFacesByNormal (Mesh *obj, const vector3 &refNormal, number maxDeviationAngle)
void SelectFacesByNormal (Mesh *obj, const vector3 &refNormal, number minDeviationAngle, number maxDeviationAngle, bool noInnerFaces)
void SelectInnerEdges (Mesh *obj)
void SelectInnerFaces (Mesh *obj)
void SelectInnerVertices (Mesh *obj)
template<class TElem >
void SelectInterfaceElements (Mesh *obj, bool regardSelectedNbrsOnly)
void SelectIntersectingTriangles (Mesh *obj)
void SelectLinkedBoundaryEdges (Mesh *obj, bool stopAtSelectedVrts)
void SelectLinkedBoundaryFaces (Mesh *obj, bool stopAtSelectedEdges)
template<class TElem >
void SelectLinkedElements (Mesh *obj)
void SelectLinkedFlatFaces (Mesh *obj, number maxDeviationAngle, bool ignoreOrientation, bool traverseDegeneratedFaces, bool stopAtSelectedEdges)
void SelectLinkedManifoldFaces (Mesh *obj)
void SelectLongEdges (Mesh *obj, number minLength)
void SelectMarkedEdges (Mesh *obj)
void SelectMarkedFaces (Mesh *obj)
void SelectMarkedVertices (Mesh *obj)
void SelectNonManifoldEdges (Mesh *obj)
void SelectSelectionBoundary (Mesh *obj)
size_t SelectSelectionKinkVertices (Mesh *obj, number thresholdAngle, bool selectDarts)
void SelectShortEdges (Mesh *obj, number maxLength)
void SelectShortPolychains (Mesh *m, number maxChainLength, bool closedChainsOnly)
int SelectSlivers (Mesh *obj, number thresholdRatio)
void SelectSmoothEdgePath (Mesh *obj, number maxDeviation, number normalWeight, bool stopAtSelectedVrts)
void SelectSubset (Mesh *obj, int si, bool selVrts, bool selEdges, bool selFaces, bool selVols)
void SelectSubsetBoundary (Mesh *obj, int si, bool edgeBnds, bool faceBnds, bool volBnds)
void SelectSubsetEdgesByDirection (Mesh *m, int subsetIndex, const vector3 &dir, number minDeviationAngle, number maxDeviationAngle, bool selectFlipped)
size_t SelectSubsetKinkVertices (Mesh *obj, int subsetIndex, number thresholdAngle, bool selectDarts)
void SelectUnassignedElements (Mesh *obj, bool selVrts, bool selEdges, bool selFaces, bool selVols)
template<class TGeomObj >
static void SelectUnassignedElementsHelper (Grid &grid, SubsetHandler &sh, Selector &sel)
size_t SelectUnconnectedVertices (Mesh *obj, bool edgeCons, bool faceCons, bool volCons)
template<class TElem >
static size_t SelectUnconnectedVerticesHelper (Grid &grid, Selector &sel)
int SelectUnorientableVolumes (Mesh *obj)
bool SelectVertexByIndex (Mesh *obj, int index)
bool SelectVolumeByIndex (Mesh *obj, int index)
void SelectVolumesByType (Mesh *obj, bool selHexahedra, bool selOctahedra, bool selPrisms, bool selPyramids, bool selTetrahedra)
void SeparateDegeneratedBoundaryFaceSubsets (Mesh *obj, number angle)
void SeparateFacesByEdgeSubsets (Mesh *obj)
void SeparateFacesBySelectedEdges (Mesh *obj)
void SeparateFaceSubsetByNormal (Mesh *obj, int si)
void SeparateFaceSubsetsByNormal (Mesh *obj)
void SeparateIrregularManifoldSubsets (Mesh *obj)
void SeparateVolumesByFaceSubsets (Mesh *obj)
void SeparateVolumesBySelectedFaces (Mesh *obj)
void SetPivot (Mesh *obj, const vector3 &pos)
void SetPivotToMeshCenter (Mesh *obj)
void SetPivotToSelectionCenter (Mesh *obj)
void SetSubsetName (Mesh *obj, int si, const char *name)
void SimplifyPolylines (Mesh *m, number curvatureThreshold)
void SimplifySmoothedPolylines (Mesh *m, number curvatureThreshold, number smoothingAlpha, int smoothingIterations)
void SlopeSmooth (Mesh *obj, number alpha, int numIterations)
void SnapToHorizontalRaster (Mesh *obj, SPRasterLayers layers)
void SnapVerticesToVertices (Mesh *obj, Mesh *targetMesh)
void SplitEdge (Mesh *obj)
void SwapEdge (Mesh *obj)
void SwapSubsets (Mesh *obj, int oldIndex, int newIndex)
void TangentialSmooth (Mesh *obj, number alpha, int numIterations)
void Tetrahedralize (Mesh *obj, number quality, bool preserveOuter, bool preserveAll, bool separateVolumes, bool appendSubsetsAtEnd, int verbosity)
void TriangleFill (Mesh *obj, bool qualityGeneration, number minAngle, int si)
void UnassignSubsets (Mesh *obj, bool vertices, bool edges, bool faces, bool volumes)
void UnmarkSelection (Mesh *obj)
void VolumeSelectionFill (Mesh *obj)
void WeightedEdgeSmooth (Mesh *obj, number alpha, int numIterations)
void WeightedFaceSmooth (Mesh *obj, number alpha, int numIterations)
void WeightedNormalSmooth (Mesh *obj, number alpha, number dotThreshold, int numIterations)
Variables
static ProMeshRegistry * g_promeshRegistry = NULL
Enumeration Type Documentation
ModifierKeys
enum ug::promesh::ModifierKeys
Enumerator
MK_NONE
MK_CTRL
MK_SHIFT
MK_ALT
ShortcutKeys
enum ug::promesh::ShortcutKeys
Enumerator
Key_Escape
Key_Tab
Key_Backtab
Key_Backspace
Key_Return
Key_Enter
Key_Insert
Key_Delete
Key_Pause
Key_Print
Key_SysReq
Key_Clear
Key_Home
Key_End
Key_Left
Key_Up
Key_Right
Key_Down
Key_PageUp
Key_PageDown
Key_Shift
Key_Control
Key_Meta
Key_Alt
Key_AltGr
Key_CapsLock
Key_NumLock
Key_ScrollLock
Key_F1
Key_F2
Key_F3
Key_F4
Key_F5
Key_F6
Key_F7
Key_F8
Key_F9
Key_F10
Key_F11
Key_F12
Key_F13
Key_F14
Key_F15
Key_F16
Key_F17
Key_F18
Key_F19
Key_F20
Key_F21
Key_F22
Key_F23
Key_F24
Key_F25
Key_F26
Key_F27
Key_F28
Key_F29
Key_F30
Key_F31
Key_F32
Key_F33
Key_F34
Key_F35
Key_Super_L
Key_Super_R
Key_Menu
Key_Hyper_L
Key_Hyper_R
Key_Help
Key_Direction_L
Key_Direction_R
Key_Space
Key_Any
Key_Exclam
Key_QuoteDbl
Key_NumberSign
Key_Dollar
Key_Percent
Key_Ampersand
Key_Apostrophe
Key_ParenLeft
Key_ParenRight
Key_Asterisk
Key_Plus
Key_Comma
Key_Minus
Key_Period
Key_Slash
Key_0
Key_1
Key_2
Key_3
Key_4
Key_5
Key_6
Key_7
Key_8
Key_9
Key_Colon
Key_Semicolon
Key_Less
Key_Equal
Key_Greater
Key_Question
Key_At
Key_A
Key_B
Key_C
Key_D
Key_E
Key_F
Key_G
Key_H
Key_I
Key_J
Key_K
Key_L
Key_M
Key_N
Key_O
Key_P
Key_Q
Key_R
Key_S
Key_T
Key_U
Key_V
Key_W
Key_X
Key_Y
Key_Z
Key_BracketLeft
Key_Backslash
Function Documentation
AssignSubsetsByAspectRatio< Face >()
template void ug::promesh::AssignSubsetsByAspectRatio< Face > (Mesh * , int , bool)
Referenced by RegisterSubsetTools().
AssignSubsetsByAspectRatio< Volume >()
template void ug::promesh::AssignSubsetsByAspectRatio< Volume > (Mesh * , int , bool)
Referenced by RegisterSubsetTools().
AssignSubsetsFromRaster_IMPL() [1/2]
template<int dim, class elem_t > void ug::promesh::AssignSubsetsFromRaster_IMPL (Mesh * obj, const char * rasterFileName)
References ug::GridSubsetHandler::assign_subset(), ug::Grid::begin(), ug::CalculateCenter(), dim, ug::Grid::end(), ug::promesh::Mesh::grid(), ug::promesh::Mesh::position_accessor(), and ug::promesh::Mesh::subset_handler().
AssignSubsetsFromRaster_IMPL() [2/2]
template<int dim> void ug::promesh::AssignSubsetsFromRaster_IMPL (Mesh * obj, const char * rasterFileName, bool vertices, bool edges, bool faces, bool volumes)
References vertices().
CopySelectedElements()
template<class TElem > void ug::promesh::CopySelectedElements (Mesh * srcMesh, Mesh * destMesh, AVertex aNewVrt)
Make sure that aNewVrt is attached to srcMesh->grid() and contains a pointer to a valid vertex in destMesh for each selected vertex in srcMesh. Also make sure that all vertices belonging to a selected element have been selected, too.
References ug::GridSubsetHandler::assign_subset(), ug::Selector::begin(), ug::promesh::Mesh::crease_handler(), ug::Grid::create_by_cloning(), dim, ug::Selector::end(), ug::ISubsetHandler::get_subset_index(), ug::promesh::Mesh::grid(), ug::CustomVertexGroup::resize(), ug::promesh::Mesh::selector(), ug::CustomVertexGroup::set_vertex(), and ug::promesh::Mesh::subset_handler().
FixMirrorOrientation()
template<class elem_t , class vrt_iter_t > static void ug::promesh::FixMirrorOrientation (Grid & g, vrt_iter_t vrtsBegin, vrt_iter_t vrtsEnd) static
call this method for edges, faces, and volumes after you performed mirroring. The method mirrors all elements of a grid which are connected to at least one of the given vertices. \WARNING The method may produce invalid results if only a subset of vertices of a given element was mirrored. \NOTE The method uses Grid::mark
References ug::Grid::associated_elements(), ug::Grid::begin_marking(), ug::Grid::end_marking(), ug::Grid::flip_orientation(), ug::Grid::is_marked(), ug::Grid::mark(), and ug::PointerConstArray< class >::size().
PrintAspectRatioHistogram()
template<class elem_t > void ug::promesh::PrintAspectRatioHistogram (Mesh * msh, int numHistoSecs)
References ug::Grid::begin(), ug::Selector::begin(), ug::Selector::end(), ug::Grid::end(), ug::GetAspectRatioHistogram(), ug::promesh::Mesh::grid(), ug::GRID_BASE_OBJECT_PLURAL_NAMES, ug::Grid::num(), ug::Selector::num(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), Table< std::stringstream >::to_string(), and UG_LOG.
PrintAspectRatioHistogram< Face >()
template void ug::promesh::PrintAspectRatioHistogram< Face > (Mesh * msh, int numHistoSecs)
Referenced by RegisterMisc().
PrintAspectRatioHistogram< Volume >()
template void ug::promesh::PrintAspectRatioHistogram< Volume > (Mesh * msh, int numHistoSecs)
Referenced by RegisterMisc().
PrintAspectRatios()
template<class elem_t > void ug::promesh::PrintAspectRatios (Mesh * msh)
References ug::Grid::begin(), ug::Selector::begin(), ug::Selector::end(), ug::Grid::end(), ug::GetAspectRatioInfo(), ug::promesh::Mesh::grid(), ug::GRID_BASE_OBJECT_PLURAL_NAMES, ug::Grid::num(), ug::Selector::num(), ug::promesh::Mesh::position_accessor(), ug::promesh::Mesh::selector(), ug::AspectRatioInfo::to_string(), and UG_LOG.
PrintAspectRatios< Face >()
template void ug::promesh::PrintAspectRatios< Face > (Mesh *)
Referenced by RegisterMisc().
PrintAspectRatios< Volume >()
template void ug::promesh::PrintAspectRatios< Volume > (Mesh *)
Referenced by RegisterMisc().
RegisterCoordinateTransformTools() [1/2]
void ug::promesh::RegisterCoordinateTransformTools (ProMeshRegistry & reg, std::string grp)
RegisterCoordinateTransformTools() [2/2]
void ug::promesh::RegisterCoordinateTransformTools (ProMeshRegistry & reg, string baseGrp)
References ug::promesh::ProMeshRegistry::add_function(), ConeTransform(), FlattenBentQuadrilaterals(), GetSelectionCenter(), LaplacianSmooth(), Mirror(), Move(), MoveAlongNormal(), MoveMeshTo(), MoveSelectionTo(), MoveVerticesAlongEdges(), MoveVerticesToEdgeLength(), MoveVerticesToProjectedEdgeLength(), ProjectToLimitPLoop(), ProjectToLimitSmoothBoundary(), ProjectToPlane(), RotateAroundCenter(), RotateAroundPivot(), RT_NO_PROMESH, ScaleAroundCenter(), ScaleAroundPivot(), ScaleAroundPoint(), SetPivot(), SetPivotToMeshCenter(), SetPivotToSelectionCenter(), SlopeSmooth(), SnapVerticesToVertices(), TangentialSmooth(), TOOLTIP_CONE_TRANSFORM, TOOLTIP_FLATTEN_BENT_QUADRILATERALS, TOOLTIP_GET_SELECTION_CENTER, TOOLTIP_LAPLACIAN_SMOOTH, TOOLTIP_MIRROR, TOOLTIP_MOVE, TOOLTIP_MOVE_ALONG_NORMAL, TOOLTIP_MOVE_MESH_TO, TOOLTIP_MOVE_SELECTION_TO, TOOLTIP_MOVE_VERTICES_ALONG_EDGES, TOOLTIP_MOVE_VERTICES_TO_EDGE_LENGTH, TOOLTIP_MOVE_VERTICES_TO_PROJECTED_EDGE_LENGTH, TOOLTIP_PROJECT_TO_LIMIT_PLOOP, TOOLTIP_PROJECT_TO_LIMIT_SMOOTH_BOUNDARY, TOOLTIP_ROTATE_AROUND_CENTER, TOOLTIP_ROTATE_AROUND_PIVOT, TOOLTIP_RPOJECT_TO_PLANE, TOOLTIP_SCALE_AROUND_CENTER, TOOLTIP_SCALE_AROUND_PIVOT, TOOLTIP_SCALE_AROUND_POINT, TOOLTIP_SET_PIVOT, TOOLTIP_SET_PIVOT_TO_MESH_CENTER, TOOLTIP_SET_PIVOT_TO_SELECTION_CENTER, TOOLTIP_SLOPE_SMOOTH, TOOLTIP_SNAP_VERTICES_TO_VERTICES, TOOLTIP_TANGENTIAL_SMOOTH, and UG_REGISTRY_CATCH_THROW.
Referenced by ug::InitUGPlugin_ProMesh().
RegisterElementIterators()
template<class TElem > static void ug::promesh::RegisterElementIterators (ProMeshRegistry & reg, string name, string grp) static
helper function to register mesh-element-iterators
References ug::promesh::ProMeshRegistry::add_class_(), assign(), clone(), and TOOLTIP_ITERATOR.
RegisterMesh() [1/2]
void ug::promesh::RegisterMesh (ProMeshRegistry & reg, std::string grp)
RegisterMesh() [2/2]
void ug::promesh::RegisterMesh (ProMeshRegistry & reg, string baseGrp)
References ug::promesh::ProMeshRegistry::add_class_(), ug::bridge::ExportedClass< class >::add_constructor(), grid(), position_attachment(), subset_handler(), TOOLTIP_MESH, and UG_REGISTRY_CATCH_THROW.
Referenced by ug::InitUGPlugin_ProMesh().
RegisterMeshingTools() [1/2]
void ug::promesh::RegisterMeshingTools (ProMeshRegistry & reg, std::string grp)
RegisterMeshingTools() [2/2]
void ug::promesh::RegisterMeshingTools (ProMeshRegistry & reg, string baseGrp)
References AdaptSurfaceToCylinder(), ug::promesh::ProMeshRegistry::add_function(), AdjustEdgeLength(), AdjustEdgeLengthExtended(), AdjustEdgeOrientation(), AssignVolumeConstraints(), ClearVolumeConstraints(), CloneMesh(), CollapseEdge(), ConvertToQuadrilaterals(), ConvertToTetrahedra(), ConvertToTriangles(), CopySelection(), CreateBox(), CreateCircle(), CreateEdge(), CreateFace(), CreateHexahedraFromSelectedPrisms(), CreatePlane(), CreatePrism(), CreatePyramid(), CreateShrinkGeometry(), CreateSphere(), CreateTetrahedron(), CreateTKD(), CreateTKDWithOuterLayer(), CreateVertex(), CreateVolume(), CSGFaceDifference(), CSGFaceIntersection(), CSGFaceUnion(), Duplicate(), EraseSelectedElements(), ExtrudeAlongNormal(), ExtrudeAndMove(), ExtrudeAndScale(), ExtrudeCylinders(), ExtrudeFacesWithTets(), ExtrudeLayers(), ExtrudeLayersAndAddProjector(), ExtrudeToThickness(), FixFaceOrientation(), FixFaceSubsetOrientations(), FixVolumeOrientation(), HangingNodeRefine(), InsertCenter(), IntersectCloseEdges(), InvertFaceOrientation(), Key_D, Key_Delete, Key_E, Key_Q, Key_R, Key_W, MergeAtCenter(), MergeAtFirst(), MergeAtLast(), MeshLayerBoundaries(), MeshLayers(), PlaneCut(), ProjectToLayer(), ProjectToTopLayer(), ProjectVerticesToCloseEdges(), ProjectVerticesToCloseFaces(), Refine(), RefineSmooth(), RefineWithSnapPoints(), RefineWithSnapPointsOrtho(), RegularizingRefinement(), RemoveDoubleEdges(), RemoveDoubleFaces(), RemoveDoubles(), ReplaceLowValenceVertices(), ReplaceValence3Vertices(), ResolveEdgeIntersection(), ResolveSelfIntersections(), ResolveTriangleIntersections(), Retetrahedralize(), Retriangulate(), RT_DEFAULT, RT_NO_PROMESH, SimplifyPolylines(), SimplifySmoothedPolylines(), SnapToHorizontalRaster(), SplitEdge(), SwapEdge(), Tetrahedralize(), TOOLTIP_ADAPT_SURFACE_TO_CYLINDER, TOOLTIP_ADJUST_EDGE_LENGTH, TOOLTIP_ADJUST_EDGE_ORIENTATION, TOOLTIP_ASSIGN_VOLUME_CONSTRAINTS, TOOLTIP_CLEAR_VOLUME_CONSTRAINTS, TOOLTIP_CLONE_MESH, TOOLTIP_COLLAPSE_EDGE, TOOLTIP_CONVERT_TO_QUADRILATERALS, TOOLTIP_CONVERT_TO_TETRAHEDRA, TOOLTIP_CONVERT_TO_TRIANGLES, TOOLTIP_COPY_SELECTION, TOOLTIP_CREATE_BOX, TOOLTIP_CREATE_CIRCLE, TOOLTIP_CREATE_EDGE, TOOLTIP_CREATE_FACE, TOOLTIP_CREATE_HEXAHEDRA_FROM_SELECTED_PRISMS, TOOLTIP_CREATE_PLANE, TOOLTIP_CREATE_PRISM, TOOLTIP_CREATE_PYRAMID, TOOLTIP_CREATE_SHRINK_GEOMETRY, TOOLTIP_CREATE_SPHERE, TOOLTIP_CREATE_TETRAHEDRON, TOOLTIP_CREATE_TKD, TOOLTIP_CREATE_TKD_WITH_OUTER_LAYER, TOOLTIP_CREATE_VERTEX, TOOLTIP_CREATE_VOLUME, TOOLTIP_CSG_FACE_DIFFERENCE, TOOLTIP_CSG_FACE_INTERSECTION, TOOLTIP_CSG_FACE_UNION, TOOLTIP_DUPLICATE, TOOLTIP_ERASE_SELECTED_ELEMENTS, TOOLTIP_EXTRUDE_ALONG_NORMAL, TOOLTIP_EXTRUDE_AND_MOVE, TOOLTIP_EXTRUDE_AND_SCALE, TOOLTIP_EXTRUDE_CYLINDERS, TOOLTIP_EXTRUDE_FACES_WITH_TETS, TOOLTIP_EXTRUDE_LAYERS, TOOLTIP_EXTRUDE_LAYERS_AND_ADD_PROJECTOR, TOOLTIP_EXTRUDE_TO_TICKNESS, TOOLTIP_FIX_FACE_ORIENTATION, TOOLTIP_FIX_FACE_SUBSET_ORIENTATIONS, TOOLTIP_FIX_VOLUME_ORIENTATION, TOOLTIP_HANGING_NODE_REFINE, TOOLTIP_INSERT_CENTER, TOOLTIP_INTERSECT_CLOSE_EDGES, TOOLTIP_INVERT_FACE_ORIENTATION, TOOLTIP_MERGE_AT_CENTER, TOOLTIP_MERGE_AT_FIRST, TOOLTIP_MERGE_AT_LAST, TOOLTIP_MESH_LAYER_BOUNDARIES, TOOLTIP_MESH_LAYERS, TOOLTIP_PLANE_CUT, TOOLTIP_PROJECT_TO_LAYER, TOOLTIP_PROJECT_TO_TOP_LAYER, TOOLTIP_PROJECT_VERTICES_TO_CLOSE_EDGES, TOOLTIP_PROJECT_VERTICES_TO_CLOSE_FACES, TOOLTIP_REFINE, TOOLTIP_REFINE_SMOOTH, TOOLTIP_REFINE_WITH_SNAP_POINTS, TOOLTIP_REFINE_WITH_SNAP_POINTS_ORTHO, TOOLTIP_REGULARIZING_REFINEMENT, TOOLTIP_REMOVE_DOUBLE_EDGES, TOOLTIP_REMOVE_DOUBLE_FACES, TOOLTIP_REMOVE_DOUBLES, TOOLTIP_REPLACE_LOW_VALENCE_VERTICES, TOOLTIP_REPLACE_VALENCE_3_VERTICES, TOOLTIP_RESOLVE_EDGE_INTERSECTIONS, TOOLTIP_RESOLVE_SELF_INTERSECTIONS, TOOLTIP_RESOLVE_TRIANGLE_INTERSECTIONS, TOOLTIP_RETETRAHEDRALIZE, TOOLTIP_RETRIANGULATE, TOOLTIP_SIMPLIFY_POLYLINES, TOOLTIP_SIMPLIFY_SMOOTHED_POLYLINES, TOOLTIP_SNAP_TO_HORIZONTAL_RASTER, TOOLTIP_SPLIT_EDGE, TOOLTIP_SWAP_EDGE, TOOLTIP_TETRAHEDRALIZE, TOOLTIP_TRIANGLE_FILL, TriangleFill(), and UG_REGISTRY_CATCH_THROW.
Referenced by ug::InitUGPlugin_ProMesh().
RegisterMeshIteratorMethods()
template<class TElem > static void ug::promesh::RegisterMeshIteratorMethods (ExportedClass< Mesh > & cls, string elemName) static
References ug::bridge::ExportedClass< class >::add_method().
RegisterMisc()
static void ug::promesh::RegisterMisc (ProMeshRegistry & reg, string baseGrp) static
References ug::promesh::ProMeshRegistry::add_class_(), ug::promesh::ProMeshRegistry::add_function(), ExportToUG3(), GetBoundingBox(), LoadMesh(), MeasureGridArea(), MeasureGridLength(), MeasureGridVolume(), MeasureSelectionArea(), MeasureSelectionLength(), MeasureSelectionVolume(), MeasureSubsetArea(), MeasureSubsetLength(), MeasureSubsetVolume(), PrintAspectRatioHistogram< Face >(), PrintAspectRatioHistogram< Volume >(), PrintAspectRatios< Face >(), PrintAspectRatios< Volume >(), ProjectedDistance(), RT_NO_PROMESH, SaveMesh(), TOOLTIP_EXPORT_TO_UG3, TOOLTIP_GET_BOUNDING_BOX, TOOLTIP_LOAD_MESH, TOOLTIP_MEASURE_GRID_AREA, TOOLTIP_MEASURE_GRID_LENGTH, TOOLTIP_MEASURE_GRID_VOLUME, TOOLTIP_MEASURE_SELECTION_AREA, TOOLTIP_MEASURE_SELECTION_LENGTH, TOOLTIP_MEASURE_SELECTION_VOLUME, TOOLTIP_MEASURE_SUBSET_AREA, TOOLTIP_MEASURE_SUBSET_LENGTH, TOOLTIP_MEASURE_SUBSET_VOLUME, TOOLTIP_PRINT_FACE_ASPECT_RATIO_HISTOGRAM, TOOLTIP_PRINT_FACE_ASPECT_RATIOS, TOOLTIP_PRINT_VOLUME_ASPECT_RATIO_HISTOGRAM, TOOLTIP_PRINT_VOLUME_ASPECT_RATIOS, TOOLTIP_PROJECTED_DISTANCE, and TOOLTIP_SAVE_MESH.
Referenced by ug::InitUGPlugin_ProMesh().
RegisterSelectionTools() [1/2]
void ug::promesh::RegisterSelectionTools (ProMeshRegistry & reg, std::string grp)
RegisterSelectionTools() [2/2]
void ug::promesh::RegisterSelectionTools (ProMeshRegistry & reg, string baseGrp)
References ug::promesh::ProMeshRegistry::add_function(), ClearMarks(), ClearSelection(), CloseSelection(), DeselectAllEdges(), DeselectAllFaces(), DeselectAllVertices(), DeselectAllVolumes(), EdgeSelectionFill(), ExtendSelection(), ExtendSelectionInDirection(), FaceSelectionFill(), InvertSelection(), Key_C, Key_M, MarkCornersOfMarkedEdges(), MarkCreaseEdges(), MarkSelection(), RestrictSelectionToSubset(), RT_DEFAULT, RT_NO_PROMESH, SelectAll(), SelectAllEdges(), SelectAllFaces(), SelectAllVertices(), SelectAllVolumes(), SelectAssociatedEdges(), SelectAssociatedFaces(), SelectAssociatedVertices(), SelectBentQuadrilaterals(), SelectBoundaryEdges(), SelectBoundaryFaces(), SelectBoundaryVertices(), SelectClosestEdge(), SelectCreaseEdges(), SelectDegenerateFaces(), SelectEdgeByIndex(), SelectEdgesByDirection(), SelectElementsByIndexRange(), SelectElementsBySplitPlane(), SelectFaceByIndex(), SelectFacesByNormal(), SelectInnerEdges(), SelectInnerFaces(), SelectInnerVertices(), SelectIntersectingTriangles(), SelectLinkedBoundaryEdges(), SelectLinkedBoundaryFaces(), SelectLinkedFlatFaces(), SelectLinkedManifoldFaces(), SelectLongEdges(), SelectMarkedEdges(), SelectMarkedFaces(), SelectMarkedVertices(), SelectNonManifoldEdges(), SelectSelectionBoundary(), SelectSelectionKinkVertices(), SelectShortEdges(), SelectShortPolychains(), SelectSlivers(), SelectSmoothEdgePath(), SelectSubset(), SelectSubsetBoundary(), SelectSubsetEdgesByDirection(), SelectSubsetKinkVertices(), SelectUnassignedElements(), SelectUnconnectedVertices(), SelectUnorientableVolumes(), SelectVertexByIndex(), SelectVolumeByIndex(), SelectVolumesByType(), TOOLTIP_CLEAR_MARKS, TOOLTIP_CLEAR_SELECTION, TOOLTIP_CLOSE_SELECTION, TOOLTIP_DESELECT_ALL_EDGES, TOOLTIP_DESELECT_ALL_FACES, TOOLTIP_DESELECT_ALL_VERTICES, TOOLTIP_DESELECT_ALL_VOLUMES, TOOLTIP_DESELECT_ELEMENTS_IN_COORDINATE_RANGE, TOOLTIP_EDGE_SELECTION_FILL, TOOLTIP_EXTEND_SELECTION, TOOLTIP_EXTEND_SELECTION_IN_DIRECTION, TOOLTIP_FACE_SELECTION_FILL, TOOLTIP_INVERT_SELECTION, TOOLTIP_MARK_CORNERS_OF_MARKED_EDGES, TOOLTIP_MARK_CREASE_EDGES, TOOLTIP_MARK_SELECTION, TOOLTIP_RESTRICT_SELECTION_TO_SUBSET, TOOLTIP_SELECT_ALL, TOOLTIP_SELECT_ALL_EDGES, TOOLTIP_SELECT_ALL_FACES, TOOLTIP_SELECT_ALL_VERTICES, TOOLTIP_SELECT_ALL_VOLUMES, TOOLTIP_SELECT_ANISOTROPIC_ELEMENTS, TOOLTIP_SELECT_ASSOCIATED_EDGES, TOOLTIP_SELECT_ASSOCIATED_FACES, TOOLTIP_SELECT_ASSOCIATED_VERTICES, TOOLTIP_SELECT_BENT_QUADRILATERALS, TOOLTIP_SELECT_BOUNDARY_EDGES, TOOLTIP_SELECT_BOUNDARY_FACES, TOOLTIP_SELECT_BOUNDARY_VERTICES, TOOLTIP_SELECT_CLOSEST_EDGE, TOOLTIP_SELECT_CREASE_EDGES, TOOLTIP_SELECT_DEGENERATE_FACES, TOOLTIP_SELECT_EDGE_BY_COORDINATE, TOOLTIP_SELECT_EDGE_BY_CYL_COORDINATE, TOOLTIP_SELECT_EDGE_BY_INDEX, TOOLTIP_SELECT_EDGE_IN_BOX, TOOLTIP_SELECT_EDGE_IN_CYLINDER, TOOLTIP_SELECT_EDGES_BY_DIRECTION, TOOLTIP_SELECT_ELEMENTS_BY_INDEX_RANGE, TOOLTIP_SELECT_ELEMENTS_BY_SPLIT_PLANE, TOOLTIP_SELECT_ELEMENTS_IN_COORDINATE_RANGE, TOOLTIP_SELECT_FACE_BY_COORDINATE, TOOLTIP_SELECT_FACE_BY_CYL_COORDINATE, TOOLTIP_SELECT_FACE_BY_INDEX, TOOLTIP_SELECT_FACE_IN_BOX, TOOLTIP_SELECT_FACE_IN_CYLINDER, TOOLTIP_SELECT_FACES_BY_NORMAL, TOOLTIP_SELECT_INNER_EDGES, TOOLTIP_SELECT_INNER_FACES, TOOLTIP_SELECT_INNER_VERTICES, TOOLTIP_SELECT_INTERFACE_ELEMENTS, TOOLTIP_SELECT_INTERSECTING_TRIANGLES, TOOLTIP_SELECT_LINKED_BOUNDARY_EDGES, TOOLTIP_SELECT_LINKED_BOUNDARY_FACES, TOOLTIP_SELECT_LINKED_EDGES, TOOLTIP_SELECT_LINKED_FACES, TOOLTIP_SELECT_LINKED_FLAT_FACES, TOOLTIP_SELECT_LINKED_MANIFOLD_FACES, TOOLTIP_SELECT_LINKED_VOLUMES, TOOLTIP_SELECT_LONG_EDGES, TOOLTIP_SELECT_MARKED_EDGES, TOOLTIP_SELECT_MARKED_FACES, TOOLTIP_SELECT_MARKED_VERTICES, TOOLTIP_SELECT_NON_MANIFOLD_EDGES, TOOLTIP_SELECT_SELECTION_BOUNDARY, TOOLTIP_SELECT_SELECTION_KINK_VERTICES, TOOLTIP_SELECT_SHORT_EDGES, TOOLTIP_SELECT_SHORT_POLYCHAINS, TOOLTIP_SELECT_SLIVERS, TOOLTIP_SELECT_SMOOTH_EDGE_PATH, TOOLTIP_SELECT_SUBSET, TOOLTIP_SELECT_SUBSET_BOUNDARY, TOOLTIP_SELECT_SUBSET_EDGES_BY_DIRECTION, TOOLTIP_SELECT_SUBSET_KINK_VERTICES, TOOLTIP_SELECT_UNASSIGNED_ELEMENTS, TOOLTIP_SELECT_UNCONNECTED_VERTICES, TOOLTIP_SELECT_UNORIENTABLE_VOLUMES, TOOLTIP_SELECT_VERTEX_BY_COORDINATE, TOOLTIP_SELECT_VERTEX_BY_CYL_COORDINATE, TOOLTIP_SELECT_VERTEX_BY_INDEX, TOOLTIP_SELECT_VERTEX_IN_BOX, TOOLTIP_SELECT_VERTEX_IN_CYLINDER, TOOLTIP_SELECT_VOLUME_BY_COORDINATE, TOOLTIP_SELECT_VOLUME_BY_CYL_COORDINATE, TOOLTIP_SELECT_VOLUME_BY_INDEX, TOOLTIP_SELECT_VOLUME_IN_BOX, TOOLTIP_SELECT_VOLUME_IN_CYLINDER, TOOLTIP_SELECT_VOLUMES_BY_TYPE, TOOLTIP_UNMARK_SELECTION, TOOLTIP_VOLUME_SELECTION_FILL, UG_REGISTRY_CATCH_THROW, UnmarkSelection(), and VolumeSelectionFill().
Referenced by ug::InitUGPlugin_ProMesh().
RegisterSubsetTools()
void ug::promesh::RegisterSubsetTools (ProMeshRegistry & reg, std::string baseGrp)
References ug::promesh::ProMeshRegistry::add_function(), AdjustSubsetsForUG3(), AdjustSubsetsForUG4(), AssignNewSubset(), AssignSubset(), AssignSubsetColors(), AssignSubsetsByAspectRatio< Face >(), AssignSubsetsByAspectRatio< Volume >(), AssignSubsetsByElementType(), AssignSubsetsByQuality(), AssignSubsetsFromRaster(), CopySubsetIndicesToSides(), EraseEmptySubsets(), EraseSubset(), JoinSubsets(), MoveSubset(), RT_NO_PROMESH, SeparateDegeneratedBoundaryFaceSubsets(), SeparateFacesByEdgeSubsets(), SeparateFacesBySelectedEdges(), SeparateFaceSubsetByNormal(), SeparateFaceSubsetsByNormal(), SeparateIrregularManifoldSubsets(), SeparateVolumesByFaceSubsets(), SeparateVolumesBySelectedFaces(), SetSubsetName(), SwapSubsets(), TOOLTIP_ADJUST_SUBSETS_FOR_UG3, TOOLTIP_ADJUST_SUBSETS_FOR_UG4, TOOLTIP_ASSIGN_NEW_SUBSET, TOOLTIP_ASSIGN_SUBSET, TOOLTIP_ASSIGN_SUBSET_COLORS, TOOLTIP_ASSIGN_SUBSETS_BY_ASPECT_RATIO, TOOLTIP_ASSIGN_SUBSETS_BY_ELEMENT_TYPE, TOOLTIP_ASSIGN_SUBSETS_BY_QUALITY, TOOLTIP_ASSIGN_SUBSETS_FROM_RASTER, TOOLTIP_COPY_SUBSET_INDICES_TO_SIDES, TOOLTIP_ERASE_EMPTY_SUBSETS, TOOLTIP_ERASE_SUBSET, TOOLTIP_JOIN_SUBSETS, TOOLTIP_MOVE_SUBSET, TOOLTIP_SEPARATE_DEGENERATED_BOUNDARY_FACE_SUBSETS, TOOLTIP_SEPARATE_FACE_SUBSET_BY_NORMAL, TOOLTIP_SEPARATE_FACE_SUBSETS_BY_NORMAL, TOOLTIP_SEPARATE_FACES_BY_EDGE_SUBSETS, TOOLTIP_SEPARATE_FACES_BY_SELECTED_EDGES, TOOLTIP_SEPARATE_IRREGULAR_MANIFOLD_SUBSETS, TOOLTIP_SEPARATE_VOLUMES_BY_FACE_SUBSETS, TOOLTIP_SEPARATE_VOLUMES_BY_SELECTED_FACES, TOOLTIP_SET_SUBSET_NAME, TOOLTIP_SWAP_SUBSETS, TOOLTIP_UNASSIGN_SUBSETS, and UnassignSubsets().
Referenced by ug::InitUGPlugin_ProMesh().
RegularizingRefinement_IMPL()
template<class TElem > void ug::promesh::RegularizingRefinement_IMPL (Mesh * obj, const number aspectRatio)
References ug::Grid::begin(), HangingNodeRefinerBase< Selector >::enable_node_dependency_order_1(), ug::Grid::end(), ug::promesh::Mesh::grid(), ug::promesh::AnisoElemInfo::has_short_edges(), ug::promesh::AnisoElemInfo::is_short_edge(), ug::HangingNodeRefiner_Grid::mark_local(), ug::promesh::Mesh::position_accessor(), ug::IRefiner::refine(), ug::promesh::AnisoElemInfo::refresh(), ug::IRefiner::set_adjusted_marks_debug_filename(), and UG_LOG.
RestrictSelectionToSubset()
template<class TElem > void ug::promesh::RestrictSelectionToSubset (Selector & sel, const SubsetHandler & sh, int si)
References ug::Selector::begin(), ug::ISelector::deselect(), ug::Selector::end(), and ug::ISubsetHandler::get_subset_index().
Referenced by RegisterSelectionTools().
SelectElementsBySplitPlane_IMPL()
template<class elem_t , class vector_t , class AAPos > static void ug::promesh::SelectElementsBySplitPlane_IMPL (Grid & g, Selector & sel, const vector_t & pivot, const vector_t & normal, AAPos aaPos) static
References ug::Grid::begin(), CalculateCenter(), ug::Grid::end(), normal, p, ug::ISelector::select(), VecDot(), and VecSubtract().
SelectUnassignedElementsHelper()
template<class TGeomObj > static void ug::promesh::SelectUnassignedElementsHelper (Grid & grid, SubsetHandler & sh, Selector & sel) static
References ug::ISubsetHandler::get_subset_index(), grid(), and ug::ISelector::select().
SelectUnconnectedVerticesHelper()
template<class TElem > static size_t ug::promesh::SelectUnconnectedVerticesHelper (Grid & grid, Selector & sel) static
References grid(), ug::ISelector::is_selected(), ug::ISelector::select(), and ug::PointerConstArray< class >::size().
Variable Documentation
g_promeshRegistry
ProMeshRegistry* ug::promesh::g_promeshRegistry = NULL static
Referenced by GetProMeshRegistry(), and ug::InitUGPlugin_ProMesh().