Plugins: /home/runner/work/docs/docs/ug4/plugins/ElementQualityStatistics/plugin_main.cpp File Reference
plugin_main.cpp File Reference
#include "registry/registry.h"
#include "common/ug_config.h"
#include "common/error.h"
#include "lib_disc/domain.h"
#include "lib_grid/lib_grid.h"
#include "element_quality_statistics.h"
#include "elem_stat_util.h"
#include <string>
Functions
UG_API void InitUGPlugin_ElementQualityStatistics (ug::bridge::Registry *reg, string parentGroup)
Function Documentation
InitUGPlugin_ElementQualityStatistics()
UG_API void InitUGPlugin_ElementQualityStatistics (ug::bridge::Registry * reg, string parentGroup)
References ug::bridge::Registry::add_function(), ug::AssignSubsetsByElementQuality(), ug::AssignSubsetToElementWithSmallestMinAngle(), ug::CalculateSubsetSurfaceArea(), ug::CalculateSubsetVolume(), ug::ElementQualityStatistics(), ug::FindBoundsForStiffnesMatrixMaxEigenvalue(), ug::MeasureTetrahedronWithSmallestMinAngle(), and ug::PrintVertexVolumeValence().