Plugins: ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::RegisterLocalDiscr Struct Reference
ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::RegisterLocalDiscr Struct Reference
auxiliary class for registering functions
Public Member Functions
template<typename TElem >
void operator() (TElem &)
RegisterLocalDiscr (this_type *pThis)
Public Attributes
this_type * m_pThis
Detailed Description
template<typename TDomain>
struct ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::RegisterLocalDiscr
auxiliary class for registering functions
Constructor & Destructor Documentation
RegisterLocalDiscr()
template<typename TDomain> ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::RegisterLocalDiscr::RegisterLocalDiscr (this_type * pThis) inline
Member Function Documentation
operator()()
template<typename TDomain> template<typename TElem > void ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::RegisterLocalDiscr::operator() (TElem &) inline
References ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_def_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_def_A_expl_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_def_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_jac_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_jac_M_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::add_rhs_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_add_def_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_add_def_A_expl_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_add_jac_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_add_rhs_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_bulk_add_def_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_bulk_add_def_A_expl_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_bulk_add_jac_A_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fract_bulk_add_rhs_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::fsh_elem_loop(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::get_updated_conv_shapes(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_diffusion(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_flux(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_mass(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_mass_scale(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_ortho_diffusion(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_ortho_flux(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_ortho_vector_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_ortho_velocity(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_reaction(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_reaction_rate(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_vector_source(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::lin_def_velocity(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_exGrad, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_exValue, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imDiffusion, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imFlux, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMass, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imMassScale, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReaction, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRate, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imReactionRateExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imSourceExpl, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVectorSource, ug::ConvectionDiffusionPlugin::ConvectionDiffusionBase< TDomain >::m_imVelocity, ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::prep_elem(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::prep_elem_loop(), ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::prepare_setting(), and ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::register_func().
Member Data Documentation
m_pThis
template<typename TDomain> this_type* ug::ConvectionDiffusionPlugin::ConvectionDiffusionFractFV1< TDomain >::RegisterLocalDiscr::m_pThis
The documentation for this struct was generated from the following file:
/home/sreiter/ug4-docugen/plugins/ConvectionDiffusion/fractfv1/convection_diffusion_fractfv1.h