Plugins: UGTestInit Struct Reference
UGTestInit Struct Reference
#include <UGTest.h>
Public Member Functions
UGTestInit ()
~UGTestInit ()
Constructor & Destructor Documentation
UGTestInit()
UGTestInit::UGTestInit () inline
initialzes ug for further use in tests using the paramteters given to the executable
References exitHandler(), and ug::UGInit().
~UGTestInit()
UGTestInit::~UGTestInit () inline
calls UGFinalize for the used ug instance
References ug::UGFinalize().
The documentation for this struct was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/UGTest/UGTest.h