Plugins: ug::NavierStokes::FunctionalityIncomp Struct Reference
ug::NavierStokes::FunctionalityIncomp Struct Reference
Static Public Member Functions
template<typename TAlgebra >
static void Algebra (Registry &reg, string grp)
static void Common (Registry &reg, string grp)
template<int dim>
static void Dimension (Registry &reg, string grp)
template<typename TDomain >
static void Domain (Registry &reg, string grp)
template<typename TDomain , typename TAlgebra >
static void DomainAlgebra (Registry &reg, string grp)
Detailed Description
Class exporting the functionality of the plugin. All functionality that is to be used in scripts or visualization must be registered here.
Member Function Documentation
Algebra()
template<typename TAlgebra > static void ug::NavierStokes::FunctionalityIncomp::Algebra (Registry & reg, string grp) inline static
Function called for the registration of Algebra dependent parts. All Functions and Classes depending on Algebra are to be placed here when registering. The method is called for all available Algebra types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
Common()
static void ug::NavierStokes::FunctionalityIncomp::Common (Registry & reg, string grp) inline static
Dimension()
template<int dim> static void ug::NavierStokes::FunctionalityIncomp::Dimension (Registry & reg, string grp) inline static
Function called for the registration of Dimension dependent parts of the plugin. All Functions and Classes depending on the Dimension are to be placed here when registering. The method is called for all available Dimension types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
Domain()
template<typename TDomain > static void ug::NavierStokes::FunctionalityIncomp::Domain (Registry & reg, string grp) inline static
Function called for the registration of Domain dependent parts of the plugin. All Functions and Classes depending on the Domain are to be placed here when registering. The method is called for all available Domain types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), and dim.
DomainAlgebra()
template<typename TDomain , typename TAlgebra > static void ug::NavierStokes::FunctionalityIncomp::DomainAlgebra (Registry & reg, string grp) inline static
Function called for the registration of Domain and Algebra dependent parts of the plugin. All Functions and Classes depending on both Domain and Algebra are to be placed here when registering. The method is called for all available Domain and Algebra types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), ug::bridge::Registry::add_function(), ug::cflNumber(), dim, ug::interpolateCRToLagrange(), ug::kineticEnergy(), and ug::vorticity().
The documentation for this struct was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/NavierStokes/incompressible/incompressible_navier_stokes_plugin.cpp