Plugins: ug::Sample::Functionality Struct Reference
ug::Sample::Functionality Struct Reference
Plugins » Sample
Static Public Member Functions
template<typename TAlgebra >
static void Algebra (Registry &reg, string grp)
static void Common (Registry &reg, string grp)
template<int dim>
static void Dimension (Registry &reg, string grp)
template<typename TDomain >
static void Domain (Registry &reg, string grp)
template<typename TDomain , typename TAlgebra >
static void DomainAlgebra (Registry &reg, string grp)
Detailed Description
Class exporting the functionality of the plugin. All functionality that is to be used in scripts or visualization must be registered here.
Member Function Documentation
template<typename TAlgebra > static void ug::Sample::Functionality::Algebra (Registry & reg, string grp) inline static
Function called for the registration of Algebra dependent parts of the plugin. All Functions and Classes depending on Algebra are to be placed here when registering. The method is called for all available Algebra types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
static void ug::Sample::Functionality::Common (Registry & reg, string grp) inline static
Function called for the registration of Domain and Algebra independent parts of the plugin. All Functions and Classes not depending on Domain and Algebra are to be placed here when registering.
Parameters
reg registry
parentGroup group for sorting of functionality
References ug::bridge::Registry::add_function(), ug::Sample::PluginCrashes(), ug::Sample::PluginCrashesFatal(), and ug::Sample::PluginSaysHello().
template<int dim> static void ug::Sample::Functionality::Dimension (Registry & reg, string grp) inline static
Function called for the registration of Dimension dependent parts of the plugin. All Functions and Classes depending on the Dimension are to be placed here when registering. The method is called for all available Dimension types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
template<typename TDomain > static void ug::Sample::Functionality::Domain (Registry & reg, string grp) inline static
Function called for the registration of Domain dependent parts of the plugin. All Functions and Classes depending on the Domain are to be placed here when registering. The method is called for all available Domain types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
template<typename TDomain , typename TAlgebra > static void ug::Sample::Functionality::DomainAlgebra (Registry & reg, string grp) inline static
Function called for the registration of Domain and Algebra dependent parts of the plugin. All Functions and Classes depending on both Domain and Algebra are to be placed here when registering. The method is called for all available Domain and Algebra types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
The documentation for this struct was generated from the following file:
/home/sreiter/projects/ug4-docu/plugins/Sample/sample_plugin.cpp