Plugins: ug::Richards::VanGenuchtenFunctions Struct Reference
ug::Richards::VanGenuchtenFunctions Struct Reference
#include <van_genuchten.h>
Static Public Member Functions
static dual ComputeEffectiveSaturation (dual psi_, double alpha, double n)
Two argument version.
static dual ComputeEffectiveSaturation (dual psi_, double alpha, double n, double m)
Effective (reduced) saturation $0 \le \hat S \le 1$.
Member Function Documentation
ComputeEffectiveSaturation() [1/2]
static dual ug::Richards::VanGenuchtenFunctions::ComputeEffectiveSaturation (dual psi_, double alpha, double n) inline static
Two argument version.
References ComputeEffectiveSaturation().
ComputeEffectiveSaturation() [2/2]
static dual ug::Richards::VanGenuchtenFunctions::ComputeEffectiveSaturation (dual psi_, double alpha, double n, double m) inline static
Effective (reduced) saturation $0 \le \hat S \le 1$.
\hat S:= (1/1+(alpha * psi)^n)^m,
References ug::Richards::UGCheckValues().
Referenced by ComputeEffectiveSaturation(), ug::Richards::VanGenuchtenModel::EffSaturation_(), ug::Richards::HaverkampModel::RelativePermeability_(), and ug::Richards::HaverkampModel::Saturation_().
The documentation for this struct was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/Richards/van_genuchten.h