Plugins: ug::SmallStrainMechanics::Functionality Struct Reference
ug::SmallStrainMechanics::Functionality Struct Reference
Plugins » Small Strain Mechanics
Static Public Member Functions
template<typename TDomain >
static void Domain (Registry &reg, string grp)
template<typename TDomain , typename TAlgebra >
static void DomainAlgebra (Registry &reg, string grp)
Detailed Description
Class exporting the functionality of the plugin. All functionality that is to be used in scripts or visualization must be registered here.
Member Function Documentation
Domain()
template<typename TDomain > static void ug::SmallStrainMechanics::Functionality::Domain (Registry & reg, string grp) inline static
Function called for the registration of Domain dependent parts of the plugin. All Functions and Classes depending on the Domain are to be placed here when registering. The method is called for all available Domain types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), ug::bridge::Registry::add_function(), dim, and OVERLOADED_METHOD_PTR.
DomainAlgebra()
template<typename TDomain , typename TAlgebra > static void ug::SmallStrainMechanics::Functionality::DomainAlgebra (Registry & reg, string grp) inline static
Function called for the registration of Domain and Algebra dependent parts. All Functions and Classes depending on both Domain and Algebra are to be placed here when registering. The method is called for all available Domain and Algebra types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), and ug::bridge::Registry::add_function().
The documentation for this struct was generated from the following file:
/home/runner/work/docs/docs/ug4/plugins/SmallStrainMechanics/small_strain_mech_plugin.cpp