Plugins: ug::ConvectionDiffusionPlugin::Functionality Struct Reference
ug::ConvectionDiffusionPlugin::Functionality Struct Reference
Plugins » Convection Diffusion
Static Public Member Functions
template<int dim>
static void Dimension (Registry &reg, string grp)
template<typename TDomain >
static void Domain (Registry &reg, string grp)
Detailed Description
Class exporting the functionality of the plugin. All functionality that is to be used in scripts or visualization must be registered here.
Member Function Documentation
Dimension()
template<int dim> static void ug::ConvectionDiffusionPlugin::Functionality::Dimension (Registry & reg, string grp) inline static
References ug::bridge::Registry::add_class_(), and ug::bridge::Registry::add_class_to_group().
Domain()
template<typename TDomain > static void ug::ConvectionDiffusionPlugin::Functionality::Domain (Registry & reg, string grp) inline static
Function called for the registration of Domain dependent parts of the plugin. All Functions and Classes depending on the Domain are to be placed here when registering. The method is called for all available Domain types, based on the current build options.
Parameters
reg registry
parentGroup group for sorting of functionality
References ug::bridge::Registry::add_class_(), ug::bridge::Registry::add_class_to_group(), and dim.
The documentation for this struct was generated from the following file:
/home/sreiter/ug4-docugen/plugins/ConvectionDiffusion/convection_diffusion_plugin.cpp