Plugins: /home/runner/work/docs/docs/ug4/plugins/UGTest/tests/common/util/tst_string_util.cpp File Reference
tst_string_util.cpp File Reference
#include "common/util/string_util.h"
#include "UGTest.h"
Functions
BOOST_AUTO_TEST_CASE (tst_string_util_AppendCounterToString)
BOOST_AUTO_TEST_CASE (tst_string_util_AppendSpacesToString)
BOOST_AUTO_TEST_CASE (tst_string_util_ConfigShift)
BOOST_AUTO_TEST_CASE (tst_string_util_Contains)
BOOST_AUTO_TEST_CASE (tst_string_util_FilenameAndPathWithoutExtension)
BOOST_AUTO_TEST_CASE (tst_string_util_FilenameWithoutExtension)
BOOST_AUTO_TEST_CASE (tst_string_util_FilenameWithoutPath)
BOOST_AUTO_TEST_CASE (tst_string_util_FindDuplicates)
BOOST_AUTO_TEST_CASE (tst_string_util_GetBytesSizeString)
BOOST_AUTO_TEST_CASE (tst_string_util_GetDirectorySeperatorPos)
BOOST_AUTO_TEST_CASE (tst_string_util_GetFileLine)
BOOST_AUTO_TEST_CASE (tst_string_util_GetFileLines)
BOOST_AUTO_TEST_CASE (tst_string_util_GetFilenameExtension)
BOOST_AUTO_TEST_CASE (tst_string_util_hash_key)
BOOST_AUTO_TEST_CASE (tst_string_util_IsLonger)
BOOST_AUTO_TEST_CASE (tst_string_util_LevenshteinDistance)
BOOST_AUTO_TEST_CASE (tst_string_util_NumberOfDigits)
BOOST_AUTO_TEST_CASE (tst_string_util_OnOffString)
BOOST_AUTO_TEST_CASE (tst_string_util_PathFromFilename)
BOOST_AUTO_TEST_CASE (tst_string_util_RemoveWhitespaceFromString)
BOOST_AUTO_TEST_CASE (tst_string_util_repeat)
BOOST_AUTO_TEST_CASE (tst_string_util_ReplaceAll)
BOOST_AUTO_TEST_CASE (tst_string_util_SnipString)
BOOST_AUTO_TEST_CASE (tst_string_util_SnipStringFront)
BOOST_AUTO_TEST_CASE (tst_string_util_StartsWith)
BOOST_AUTO_TEST_CASE (tst_string_util_TokenizeString)
BOOST_AUTO_TEST_CASE (tst_string_util_TokenizeTrimString)
BOOST_AUTO_TEST_CASE (tst_string_util_ToLower)
BOOST_AUTO_TEST_CASE (tst_string_util_ToString)
BOOST_AUTO_TEST_CASE (tst_string_util_ToUpper)
BOOST_AUTO_TEST_CASE (tst_string_util_TrimString)
BOOST_AUTO_TEST_CASE (tst_string_util_TrueFalseString)
BOOST_AUTO_TEST_CASE (tst_string_util_WildcardMatch)
BOOST_AUTO_TEST_CASE (tst_string_util_XMLStringEscape)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/34]
BOOST_AUTO_TEST_CASE (tst_string_util_AppendCounterToString)
BOOST_AUTO_TEST_CASE() [2/34]
BOOST_AUTO_TEST_CASE (tst_string_util_AppendSpacesToString)
References ug::AppendSpacesToString(), and s.
BOOST_AUTO_TEST_CASE() [3/34]
BOOST_AUTO_TEST_CASE (tst_string_util_ConfigShift)
BOOST_AUTO_TEST_CASE() [4/34]
BOOST_AUTO_TEST_CASE (tst_string_util_Contains)
BOOST_AUTO_TEST_CASE() [5/34]
BOOST_AUTO_TEST_CASE (tst_string_util_FilenameAndPathWithoutExtension)
BOOST_AUTO_TEST_CASE() [6/34]
BOOST_AUTO_TEST_CASE (tst_string_util_FilenameWithoutExtension)
BOOST_AUTO_TEST_CASE() [7/34]
BOOST_AUTO_TEST_CASE (tst_string_util_FilenameWithoutPath)
BOOST_AUTO_TEST_CASE() [8/34]
BOOST_AUTO_TEST_CASE (tst_string_util_FindDuplicates)
BOOST_AUTO_TEST_CASE() [9/34]
BOOST_AUTO_TEST_CASE (tst_string_util_GetBytesSizeString)
References ug::GetBytesSizeString().
BOOST_AUTO_TEST_CASE() [10/34]
BOOST_AUTO_TEST_CASE (tst_string_util_GetDirectorySeperatorPos)
BOOST_AUTO_TEST_CASE() [11/34]
BOOST_AUTO_TEST_CASE (tst_string_util_GetFileLine)
BOOST_AUTO_TEST_CASE() [12/34]
BOOST_AUTO_TEST_CASE (tst_string_util_GetFileLines)
BOOST_AUTO_TEST_CASE() [13/34]
BOOST_AUTO_TEST_CASE (tst_string_util_GetFilenameExtension)
BOOST_AUTO_TEST_CASE() [14/34]
BOOST_AUTO_TEST_CASE (tst_string_util_hash_key)
BOOST_AUTO_TEST_CASE() [15/34]
BOOST_AUTO_TEST_CASE (tst_string_util_IsLonger)
References ug::IsLonger().
BOOST_AUTO_TEST_CASE() [16/34]
BOOST_AUTO_TEST_CASE (tst_string_util_LevenshteinDistance)
References ug::LevenshteinDistance().
BOOST_AUTO_TEST_CASE() [17/34]
BOOST_AUTO_TEST_CASE (tst_string_util_NumberOfDigits)
References ug::NumberOfDigits().
BOOST_AUTO_TEST_CASE() [18/34]
BOOST_AUTO_TEST_CASE (tst_string_util_OnOffString)
References ug::OnOffString().
BOOST_AUTO_TEST_CASE() [19/34]
BOOST_AUTO_TEST_CASE (tst_string_util_PathFromFilename)
BOOST_AUTO_TEST_CASE() [20/34]
BOOST_AUTO_TEST_CASE (tst_string_util_RemoveWhitespaceFromString)
References ug::RemoveWhitespaceFromString(), and s.
BOOST_AUTO_TEST_CASE() [21/34]
BOOST_AUTO_TEST_CASE (tst_string_util_repeat)
References ug::repeat().
BOOST_AUTO_TEST_CASE() [22/34]
BOOST_AUTO_TEST_CASE (tst_string_util_ReplaceAll)
BOOST_AUTO_TEST_CASE() [23/34]
BOOST_AUTO_TEST_CASE (tst_string_util_SnipString)
BOOST_AUTO_TEST_CASE() [24/34]
BOOST_AUTO_TEST_CASE (tst_string_util_SnipStringFront)
BOOST_AUTO_TEST_CASE() [25/34]
BOOST_AUTO_TEST_CASE (tst_string_util_StartsWith)
BOOST_AUTO_TEST_CASE() [26/34]
BOOST_AUTO_TEST_CASE (tst_string_util_TokenizeString)
BOOST_AUTO_TEST_CASE() [27/34]
BOOST_AUTO_TEST_CASE (tst_string_util_TokenizeTrimString)
BOOST_AUTO_TEST_CASE() [28/34]
BOOST_AUTO_TEST_CASE (tst_string_util_ToLower)
BOOST_AUTO_TEST_CASE() [29/34]
BOOST_AUTO_TEST_CASE (tst_string_util_ToString)
BOOST_AUTO_TEST_CASE() [30/34]
BOOST_AUTO_TEST_CASE (tst_string_util_ToUpper)
BOOST_AUTO_TEST_CASE() [31/34]
BOOST_AUTO_TEST_CASE (tst_string_util_TrimString)
References s, and ug::TrimString().
BOOST_AUTO_TEST_CASE() [32/34]
BOOST_AUTO_TEST_CASE (tst_string_util_TrueFalseString)
References ug::TrueFalseString().
BOOST_AUTO_TEST_CASE() [33/34]
BOOST_AUTO_TEST_CASE (tst_string_util_WildcardMatch)
BOOST_AUTO_TEST_CASE() [34/34]
BOOST_AUTO_TEST_CASE (tst_string_util_XMLStringEscape)
References ug::XMLStringEscape().