Registry: VTKOutput Class Reference
VTKOutput Class Reference
Public Member Functions
void clear_data_selection ()
clears the selected UserData output
void clear_selection ()
clears the selected output
void select_all (bool unnamed)
schedules that all components of the passed discrete functions will be written to file
VTKOutput ()
Public Attributes
fctName = "p"
selects a value of a grid function value to be written. example:
name
Detailed Description
Note
default specialization is VTKOutput2d
See also
ug::VTKOutput
Constructor & Destructor Documentation
VTKOutput()
VTKOutput ()
Member Function Documentation
clear_data_selection()
void clear_data_selection () inline
clears the selected UserData output
References VTKOutput< TDim >::clear_data_selection().
clear_selection()
void clear_selection () inline
clears the selected output
References VTKOutput< TDim >::clear_selection().
select_all()
void select_all (bool unnamed) inline
schedules that all components of the passed discrete functions will be written to file
Parameters
[in] unnamed
References VTKOutput< TDim >::select_all().
Member Data Documentation
fctName
fctName = "p"
selects a value of a grid function value to be written. example:
name
name
Initial value:
= "pressure"
fctNames = "u,v,w"