Registry: ManifoldPartitioner_DynamicBisection Class Reference
ManifoldPartitioner_DynamicBisection Class Reference
Public Member Functions
bool clustered_siblings_enabled ()
void enable_clustered_siblings (bool unnamed)
void enable_longest_split_axis (bool unnamed)
void enable_split_axis (int unnamed, bool unnamed)
void enable_static_partitioning (bool unnamed)
ManifoldPartitioner_DynamicBisection (Domain *unnamed)
int num_split_improvement_iterations () const
bool partition (size_t unnamed, size_t unnamed)
void set_balance_weights (SmartPtr< IBalanceWeights > unnamed)
void set_communication_weights (SmartPtr< ICommunicationWeights > unnamed)
void set_next_process_hierarchy (SmartPtr< ProcessHierarchy > unnamed)
void set_num_split_improvement_iterations (int unnamed)
void set_partition_post_processor (SmartPtr< IPartitionPostProcessor > unnamed)
void set_partition_pre_processor (SmartPtr< IPartitionPreProcessor > unnamed)
void set_start_split_axis (int unnamed)
void set_subset_handler (SmartPtr< SubsetHandler > unnamed)
void set_verbose (bool unnamed)
bool static_partitioning_enabled () const
bool supports_balance_weights () const
bool supports_communication_weights () const
Detailed Description
Note
default specialization is EdgePartitioner_DynamicBisection2d
See also
ug::ManifoldPartitioner_DynamicBisection
Constructor & Destructor Documentation
ManifoldPartitioner_DynamicBisection()
ManifoldPartitioner_DynamicBisection (Domain * unnamed)
Parameters
[in] unnamed
Member Function Documentation
clustered_siblings_enabled()
bool clustered_siblings_enabled () inline inherited
References IPartitioner::clustered_siblings_enabled().
enable_clustered_siblings()
void enable_clustered_siblings (bool unnamed) inline inherited
Parameters
[in] unnamed
References IPartitioner::enable_clustered_siblings().
enable_longest_split_axis()
void enable_longest_split_axis (bool unnamed) inline
Parameters
[in] unnamed
enable_split_axis()
void enable_split_axis (int unnamed, bool unnamed) inline
Parameters
[in] unnamed
[in] unnamed
enable_static_partitioning()
void enable_static_partitioning (bool unnamed) inline
Parameters
[in] unnamed
num_split_improvement_iterations()
int num_split_improvement_iterations () const inline
partition()
bool partition (size_t unnamed, size_t unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References IPartitioner::partition().
set_balance_weights()
void set_balance_weights (SmartPtr< IBalanceWeights > unnamed) inline inherited
Parameters
[in] unnamed
References IPartitioner::set_balance_weights().
set_communication_weights()
void set_communication_weights (SmartPtr< ICommunicationWeights > unnamed) inline inherited
Parameters
[in] unnamed
References IPartitioner::set_communication_weights().
set_next_process_hierarchy()
void set_next_process_hierarchy (SmartPtr< ProcessHierarchy > unnamed) inline inherited
Parameters
[in] unnamed
References IPartitioner::set_next_process_hierarchy().
set_num_split_improvement_iterations()
void set_num_split_improvement_iterations (int unnamed) inline
Parameters
[in] unnamed
set_partition_post_processor()
void set_partition_post_processor (SmartPtr< IPartitionPostProcessor > unnamed) inline inherited
Parameters
[in] unnamed
References IPartitioner::set_partition_post_processor().
set_partition_pre_processor()
void set_partition_pre_processor (SmartPtr< IPartitionPreProcessor > unnamed) inline inherited
Parameters
[in] unnamed
References IPartitioner::set_partition_pre_processor().
set_start_split_axis()
void set_start_split_axis (int unnamed) inline
Parameters
[in] unnamed
set_subset_handler()
void set_subset_handler (SmartPtr< SubsetHandler > unnamed) inline
Parameters
[in] unnamed
set_verbose()
void set_verbose (bool unnamed) inline inherited
Parameters
[in] unnamed
References IPartitioner::set_verbose().
static_partitioning_enabled()
bool static_partitioning_enabled () const inline
supports_balance_weights()
bool supports_balance_weights () const inline inherited
References IPartitioner::supports_balance_weights().
supports_communication_weights()
bool supports_communication_weights () const inline inherited
References IPartitioner::supports_communication_weights().