Registry: IElemDisc Class Reference
IElemDisc Class Reference
Public Member Functions
void add_elem_modifier (SmartPtr< IElemDiscModifier > unnamed)
void set_error_estimator (SmartPtr< ErrEstData > unnamed)
void set_stationary ()
Private Member Functions
IElemDisc ()=delete
Constructor hidden / deactivated.
Detailed Description
Note
default specialization is IElemDisc2d
See also
ug::IElemDisc
Constructor & Destructor Documentation
IElemDisc()
IElemDisc () private delete
Constructor hidden / deactivated.
Member Function Documentation
add_elem_modifier()
void add_elem_modifier (SmartPtr< IElemDiscModifier > unnamed) inline
Parameters
[in] unnamed
References IElemDisc< TDomain >::add_elem_modifier().
set_error_estimator()
void set_error_estimator (SmartPtr< ErrEstData > unnamed) inline inherited
Parameters
[in] unnamed
References IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::set_error_estimator().
set_stationary()
void set_stationary () inline inherited
References IElemDiscBase< class >::set_stationary().