Registry: ConvectionDiffusionFVCR Class Reference
ConvectionDiffusionFVCR Class Reference
Public Member Functions
void add_elem_modifier (SmartPtr< IElemDiscModifier > unnamed)
ConvectionDiffusionFVCR (const char *Function(s), const char *Subset(s))
SmartPtr< CplUserVector > gradient ()
void set_diffusion (SmartPtr< CplUserMatrix > Diffusion)
void set_error_estimator (SmartPtr< ErrEstData > unnamed)
void set_flux (SmartPtr< CplUserVector > Flux)
void set_mass (SmartPtr< CplUserNumber > Mass)
void set_mass_scale (SmartPtr< CplUserNumber > Mass_Scale)
void set_reaction (SmartPtr< CplUserNumber > Reaction)
void set_reaction_explicit (SmartPtr< CplUserNumber > Reaction_Explicit)
void set_reaction_rate (SmartPtr< CplUserNumber > Reaction_Rate)
void set_reaction_rate_explicit (SmartPtr< CplUserNumber > Reaction_Rate_Explicit)
void set_source (SmartPtr< CplUserNumber > Source)
void set_source_explicit (SmartPtr< CplUserNumber > Source_Explicit)
void set_stationary ()
void set_upwind (SmartPtr< IConvectionShapes > unnamed)
void set_vector_source (SmartPtr< CplUserVector > Vector_Source)
void set_velocity (SmartPtr< CplUserVector > Velocity_Field)
SmartPtr< CplUserNumber > value ()
Detailed Description
Note
default specialization is ConvectionDiffusionFVCR2d
See also
ug::ConvectionDiffusionFVCR
Constructor & Destructor Documentation
ConvectionDiffusionFVCR()
ConvectionDiffusionFVCR (const char * Functions, const char * Subsets)
Parameters
[in] Function(s)
[in] Subset(s)
Member Function Documentation
add_elem_modifier()
void add_elem_modifier (SmartPtr< IElemDiscModifier > unnamed) inline inherited
Parameters
[in] unnamed
References IElemDisc< TDomain >::add_elem_modifier().
gradient()
SmartPtr<CplUserVector> gradient () inline inherited
set_diffusion()
void set_diffusion (SmartPtr< CplUserMatrix > Diffusion) inline inherited
Parameters
[in] Diffusion
set_error_estimator()
void set_error_estimator (SmartPtr< ErrEstData > unnamed) inline inherited
Parameters
[in] unnamed
References IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::set_error_estimator().
set_flux()
void set_flux (SmartPtr< CplUserVector > Flux) inline inherited
Parameters
[in] Flux
set_mass()
void set_mass (SmartPtr< CplUserNumber > Mass) inline inherited
Parameters
[in] Mass
set_mass_scale()
void set_mass_scale (SmartPtr< CplUserNumber > Mass_Scale) inline inherited
Parameters
[in] Mass_Scale
set_reaction()
void set_reaction (SmartPtr< CplUserNumber > Reaction) inline inherited
Parameters
[in] Reaction
set_reaction_explicit()
void set_reaction_explicit (SmartPtr< CplUserNumber > Reaction_Explicit) inline inherited
Parameters
[in] Reaction_Explicit
set_reaction_rate()
void set_reaction_rate (SmartPtr< CplUserNumber > Reaction_Rate) inline inherited
Parameters
[in] Reaction_Rate
set_reaction_rate_explicit()
void set_reaction_rate_explicit (SmartPtr< CplUserNumber > Reaction_Rate_Explicit) inline inherited
Parameters
[in] Reaction_Rate_Explicit
set_source()
void set_source (SmartPtr< CplUserNumber > Source) inline inherited
Parameters
[in] Source
set_source_explicit()
void set_source_explicit (SmartPtr< CplUserNumber > Source_Explicit) inline inherited
Parameters
[in] Source_Explicit
set_stationary()
void set_stationary () inline inherited
References IElemDiscBase< class >::set_stationary().
set_upwind()
void set_upwind (SmartPtr< IConvectionShapes > unnamed) inline
Parameters
[in] unnamed
set_vector_source()
void set_vector_source (SmartPtr< CplUserVector > Vector_Source) inline inherited
Parameters
[in] Vector_Source
set_velocity()
void set_velocity (SmartPtr< CplUserVector > Velocity_Field) inline inherited
Parameters
[in] Velocity_Field
value()
SmartPtr<CplUserNumber> value () inline inherited