Registry: SmoothProjector Class Reference
SmoothProjector Class Reference
Public Member Functions
double change_rate () const
SmartPtr< IGeometry > geometry () const
int iterations () const
void set_change_rate (double changeRate)
void set_geometry (SmartPtr< IGeometry > geometry)
void set_iterations (int iterations)
SmoothProjector ()
SmoothProjector (int unnamed, double unnamed)
SmoothProjector (SmartPtr< IGeometry > unnamed, int unnamed, double unnamed)
Constructor & Destructor Documentation
SmoothProjector() [1/3]
SmoothProjector ()
SmoothProjector() [2/3]
SmoothProjector (int unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
SmoothProjector() [3/3]
SmoothProjector (SmartPtr< IGeometry > unnamed, int unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
Member Function Documentation
change_rate()
double change_rate () const inline
Returns
changeRate
References SmoothProjector::change_rate().
geometry()
SmartPtr<IGeometry> geometry () const inline inherited
Returns
geometry
References RefinementProjector::geometry().
iterations()
int iterations () const inline
Returns
iterations
References SmoothProjector::iterations().
set_change_rate()
void set_change_rate (double changeRate) inline
Parameters
[in] changeRate
References SmoothProjector::set_change_rate().
set_geometry()
void set_geometry (SmartPtr< IGeometry > geometry) inline inherited
Parameters
[in] geometry
References RefinementProjector::set_geometry().
set_iterations()
void set_iterations (int iterations) inline
Parameters
[in] iterations
References SmoothProjector::set_iterations().