Registry: CuckooClock Class Reference
CuckooClock Class Reference
Public Member Functions
double cuckoo ()
CuckooClock ()
void tic ()
double toc ()
Constructor & Destructor Documentation
CuckooClock()
CuckooClock ()
Member Function Documentation
cuckoo()
double cuckoo () inline
References CuckooClock::cuckoo().
tic()
void tic () inline
References CuckooClock::tic().
toc()
double toc () inline
References CuckooClock::toc().