Registry: AssembledLinearOperator Class Reference
AssembledLinearOperator Class Reference
Public Member Functions
AssembledLinearOperator ()
AssembledLinearOperator (SmartPtr< IAssemble > Assembling_Routine)
AssembledLinearOperator (SmartPtr< IAssemble > AssemblingRoutine, const GridLevel *GridLevel)
void init_op_and_rhs (Vector *unnamed)
const GridLevel * level () const
void set_dirichlet_values (Vector *unnamed)
void set_discretization (SmartPtr< IAssemble > unnamed)
void set_level (const GridLevel *unnamed)
Detailed Description
Note
default specialization is AssembledLinearOperatorCPU1
See also
ug::AssembledLinearOperator
Constructor & Destructor Documentation
AssembledLinearOperator ()
AssembledLinearOperator (SmartPtr< IAssemble > Assembling_Routine)
Parameters
[in] Assembling_Routine
AssembledLinearOperator (SmartPtr< IAssemble > AssemblingRoutine, const GridLevel * GridLevel)
Parameters
[in] AssemblingRoutine
[in] GridLevel
Member Function Documentation
void init_op_and_rhs (Vector * unnamed) inline
Parameters
[in] unnamed
References AssembledLinearOperator< TAlgebra >::init_op_and_rhs().
const GridLevel* level () const inline
References AssembledLinearOperator< TAlgebra >::level().
void set_dirichlet_values (Vector * unnamed) inline
Parameters
[in] unnamed
References AssembledLinearOperator< TAlgebra >::set_dirichlet_values().
void set_discretization (SmartPtr< IAssemble > unnamed) inline
Parameters
[in] unnamed
References AssembledLinearOperator< TAlgebra >::set_discretization().
void set_level (const GridLevel * unnamed) inline
Parameters
[in] unnamed
References AssembledLinearOperator< TAlgebra >::set_level().