Registry: HookeLaw Class Reference
HookeLaw Class Reference
Public Member Functions
HookeLaw ()
void set_elasticity_tensor_orthotropic (double C11, double C12, double C13, double C22, double C23, double C33, double C44, double C55, double C66)
void set_elasticity_tensor_orthotropic_E_G_nu (double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed)
void set_elasticity_tensor_orthotropic_plain_strain_E_G_nu (double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed)
void set_elasticity_tensor_orthotropic_plain_stress_E_G_nu (double unnamed, double unnamed, double unnamed, double unnamed)
void set_hooke_elasticity_tensor (double lambda, double mu)
void set_hooke_elasticity_tensor_E_nu (double E, double nu)
void set_hooke_elasticity_tensor_plain_strain_E_nu (double E, double nu)
void set_hooke_elasticity_tensor_plain_stress_E_nu (double E, double nu)
Detailed Description
Note
default specialization is HookeLaw2d
See also
ug::HookeLaw
Constructor & Destructor Documentation
HookeLaw()
HookeLaw ()
Member Function Documentation
set_elasticity_tensor_orthotropic()
void set_elasticity_tensor_orthotropic (double C11, double C12, double C13, double C22, double C23, double C33, double C44, double C55, double C66) inline
Parameters
[in] C11
[in] C12
[in] C13
[in] C22
[in] C23
[in] C33
[in] C44
[in] C55
[in] C66
References set_elasticity_tensor_orthotropic().
set_elasticity_tensor_orthotropic_E_G_nu()
void set_elasticity_tensor_orthotropic_E_G_nu (double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References set_elasticity_tensor_orthotropic_E_G_nu().
set_elasticity_tensor_orthotropic_plain_strain_E_G_nu()
void set_elasticity_tensor_orthotropic_plain_strain_E_G_nu (double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed, double unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References set_elasticity_tensor_orthotropic_plain_strain_E_G_nu().
set_elasticity_tensor_orthotropic_plain_stress_E_G_nu()
void set_elasticity_tensor_orthotropic_plain_stress_E_G_nu (double unnamed, double unnamed, double unnamed, double unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References set_elasticity_tensor_orthotropic_plain_stress_E_G_nu().
set_hooke_elasticity_tensor()
void set_hooke_elasticity_tensor (double lambda, double mu) inline
Parameters
[in] lambda
[in] mu
References mu, and set_hooke_elasticity_tensor().
set_hooke_elasticity_tensor_E_nu()
void set_hooke_elasticity_tensor_E_nu (double E, double nu) inline
Parameters
[in] E
[in] nu
References set_hooke_elasticity_tensor_E_nu().
set_hooke_elasticity_tensor_plain_strain_E_nu()
void set_hooke_elasticity_tensor_plain_strain_E_nu (double E, double nu) inline
Parameters
[in] E
[in] nu
References set_hooke_elasticity_tensor_plain_strain_E_nu().
set_hooke_elasticity_tensor_plain_stress_E_nu()
void set_hooke_elasticity_tensor_plain_stress_E_nu (double E, double nu) inline
Parameters
[in] E
[in] nu
References set_hooke_elasticity_tensor_plain_stress_E_nu().