Registry: DirichletBoundary Class Reference
DirichletBoundary Class Reference
Public Member Functions
void add (SmartPtr< CondUserNumber > Value, const char *Function, const char *Subsets)
void clear ()
DirichletBoundary ()
DirichletBoundary (bool unnamed)
void set_approximation_space (SmartPtr< ApproximationSpace > ApproximationSpace)
void set_error_estimator (SmartPtr< ErrEstData > error_estimator_data_object)
Detailed Description
Note
default specialization is DirichletBoundary2dCPU1
See also
ug::DirichletBoundary
Constructor & Destructor Documentation
DirichletBoundary ()
DirichletBoundary (bool unnamed)
Parameters
[in] unnamed
Member Function Documentation
void add (SmartPtr< CondUserNumber > Value, const char * Function, const char * Subsets) inline
Parameters
[in] Value
[in] Function
[in] Subsets
References DirichletBoundary< class, class >::add().
void clear () inline
References DirichletBoundary< class, class >::clear().
void set_approximation_space (SmartPtr< ApproximationSpace > ApproximationSpace) inline
Parameters
[in] ApproximationSpace
References DirichletBoundary< class, class >::set_approximation_space().
void set_error_estimator (SmartPtr< ErrEstData > error_estimator_data_object) inline inherited
Parameters
[in] error_estimator_data_object
References IDomainConstraint< class, class >::set_error_estimator().