Registry: IApproximationSpace Class Reference
IApproximationSpace Class Reference
Public Member Functions
void add_fct (const char *Name, const char *Type, int Order, const char *Subsets)
Adds a function to the Function Pattern.
void clear ()
int dim (size_t unnamed) const
void init_levels ()
void init_surfaces ()
void init_top_surface ()
const LFEID * lfeid (size_t unnamed) const
std::string name (size_t unnamed) const
std::vector< std::string > names () const
size_t num_fct () const
size_t num_levels () const
void print_layout_statistic () const
void print_local_dof_statistic (int unnamed) const
void print_statistic (std::string unnamed) const
Private Member Functions
IApproximationSpace ()=delete
Constructor hidden / deactivated.
Constructor & Destructor Documentation
IApproximationSpace()
IApproximationSpace () private delete
Constructor hidden / deactivated.
Member Function Documentation
add_fct()
void add_fct (const char * Name, const char * Type, int Order, const char * Subsets) inline
Adds a function to the Function Pattern.
currently no help available
Parameters
[in] Name
[in] Type
[in] Order
[in] Subsets
clear()
void clear () inline
References IApproximationSpace::clear().
dim()
int dim (size_t unnamed) const inline inherited
Parameters
[in] unnamed
References DoFDistributionInfoProvider::dim().
init_levels()
void init_levels () inline
References IApproximationSpace::init_levels().
init_surfaces()
void init_surfaces () inline
References IApproximationSpace::init_surfaces().
init_top_surface()
void init_top_surface () inline
References IApproximationSpace::init_top_surface().
lfeid()
const LFEID* lfeid (size_t unnamed) const inline inherited
Parameters
[in] unnamed
References DoFDistributionInfoProvider::lfeid().
name()
std::string name (size_t unnamed) const inline inherited
Parameters
[in] unnamed
References DoFDistributionInfoProvider::name().
names()
std::vector< std::string > names () const inline inherited
References DoFDistributionInfoProvider::names().
num_fct()
size_t num_fct () const inline inherited
References DoFDistributionInfoProvider::num_fct().
num_levels()
size_t num_levels () const inline
References IApproximationSpace::num_levels().
print_layout_statistic()
void print_layout_statistic () const inline
References IApproximationSpace::print_layout_statistic().
print_local_dof_statistic()
void print_local_dof_statistic (int unnamed) const inline inherited
Parameters
[in] unnamed
References DoFDistributionInfoProvider::print_local_dof_statistic().
print_statistic()
void print_statistic (std::string unnamed) const inline
Parameters
[in] unnamed
References IApproximationSpace::print_statistic().