Registry: Domain Class Reference
Domain Class Reference
Public Member Functions
SmartPtr< MGSubsetHandler > additional_subset_handler (std::string unnamed)
std::vector< std::string > additional_subset_handler_names () const
bool create_additional_subset_handler (std::string unnamed)
Domain ()
const DomainInfo * domain_info () const
bool empty () const
int get_dim () const
SmartPtr< MultiGrid > grid ()
const APosition2 * position_attachment () const
SmartPtr< MGSubsetHandler > subset_handler ()
Detailed Description
Note
default specialization is Domain2d
See also
ug::Domain
Constructor & Destructor Documentation
Domain ()
Member Function Documentation
SmartPtr<MGSubsetHandler> additional_subset_handler (std::string unnamed) inline inherited
Parameters
[in] unnamed
Returns
SubsetHandler
References IDomain< TGrid, TSubsetHandler >::additional_subset_handler().
std::vector< std::string > additional_subset_handler_names () const inline inherited
Returns
vector<string>
References IDomain< TGrid, TSubsetHandler >::additional_subset_handler_names().
bool create_additional_subset_handler (std::string unnamed) inline inherited
Parameters
[in] unnamed
Returns
bool
References IDomain< TGrid, TSubsetHandler >::create_additional_subset_handler().
const DomainInfo* domain_info () const inline inherited
Returns
DomainInfo
References IDomain< TGrid, TSubsetHandler >::domain_info().
bool empty () const inline
References IDomain< TGrid, TSubsetHandler >::empty().
int get_dim () const inline inherited
References IDomain< TGrid, TSubsetHandler >::get_dim().
SmartPtr<MultiGrid> grid () inline inherited
Returns
grid
References IDomain< TGrid, TSubsetHandler >::grid().
const APosition2* position_attachment () const inline
References Domain< d, TGrid, TSubsetHandler >::position_attachment().
SmartPtr<MGSubsetHandler> subset_handler () inline inherited
References IDomain< TGrid, TSubsetHandler >::subset_handler().