Registry: ISelector Class Reference
ISelector Class Reference
Public Member Functions
void deselect (Vertex *unnamed)
bool is_selected (Vertex *unnamed) const
void select (Vertex *unnamed)
Private Member Functions
ISelector ()=delete
Constructor hidden / deactivated.
Constructor & Destructor Documentation
ISelector()
ISelector () private delete
Constructor hidden / deactivated.
Member Function Documentation
deselect()
void deselect (Vertex * unnamed) inline
Parameters
[in] unnamed
References ISelector::deselect().
is_selected()
bool is_selected (Vertex * unnamed) const inline
Parameters
[in] unnamed
References ISelector::is_selected().
select()
void select (Vertex * unnamed) inline
Parameters
[in] unnamed
References ISelector::select().