Registry: RasterLayers Class Reference
RasterLayers Class Reference
Stack of 2d raster data.
Public Member Functions
void blur_layers (double alpha, size_t num_iterations)
Blurs the values in each layer by averaging between neighbored cells on the same layer.
void construct_relative_to_global_height_table (size_t iterations, double alpha)
Prepares a table for improved height value reconstructions in no-data-regions.
void eliminate_invalid_cells ()
void invalidate_flat_cells ()
Marks all cells as invalid that belong to a small lense regarding its horizontal area.
void invalidate_small_lenses (double min_area)
Marks all cells as invalid which are closer to the next higher valid cell than the given min height.
void load_from_files (std::vector< std::string > filenames, double unnamed)
Loads raster data from the specified .asc files. Specify the bottom layer first and the surface layer last.
RasterLayers ()
void remove_small_holes (double max_area, _min_height)
removes small holes by expanding the layer in those regions to the specified height
void snap_cells_to_higher_layers ()
sets invalid or flat cells to the value of the corresponding cell in the level above.
Detailed Description
Stack of 2d raster data.
Constructor & Destructor Documentation
RasterLayers()
RasterLayers ()
Member Function Documentation
blur_layers()
void blur_layers (double alpha, size_t num_iterations) inline
Blurs the values in each layer by averaging between neighbored cells on the same layer.
Parameters
[in] alpha
[in] num_iterations
References RasterLayers::blur_layers().
construct_relative_to_global_height_table()
void construct_relative_to_global_height_table (size_t iterations, double alpha) inline
Prepares a table for improved height value reconstructions in no-data-regions.
Parameters
[in] iterations
[in] alpha
References RasterLayers::construct_relative_to_global_height_table().
eliminate_invalid_cells()
void eliminate_invalid_cells () inline
References RasterLayers::eliminate_invalid_cells().
invalidate_flat_cells()
void invalidate_flat_cells () inline
Marks all cells as invalid that belong to a small lense regarding its horizontal area.
References RasterLayers::invalidate_flat_cells().
invalidate_small_lenses()
void invalidate_small_lenses (double min_area) inline
Marks all cells as invalid which are closer to the next higher valid cell than the given min height.
Parameters
[in] min_area
References RasterLayers::invalidate_small_lenses().
load_from_files()
void load_from_files (std::vector< std::string > filenames, double unnamed) inline
Loads raster data from the specified .asc files. Specify the bottom layer first and the surface layer last.
Parameters
[in] filenames
[in] unnamed
References RasterLayers::load_from_files().
remove_small_holes()
void remove_small_holes (double max_area, _min_height) inline
removes small holes by expanding the layer in those regions to the specified height
Parameters
[in] max_area,_min_height
References RasterLayers::remove_small_holes().
snap_cells_to_higher_layers()
void snap_cells_to_higher_layers () inline
sets invalid or flat cells to the value of the corresponding cell in the level above.
References RasterLayers::snap_cells_to_higher_layers().