Registry: CompositeSpace Class Reference
CompositeSpace Class Reference
Public Member Functions
void add (SmartPtr< IComponentSpace > unnamed)
CompositeSpace ()
std::string config_string () const
bool is_time_dependent () const
void update_time_data (double unnamed)
Detailed Description
Note
default specialization is CompositeSpace2dCPU1
See also
ug::CompositeSpace
Constructor & Destructor Documentation
CompositeSpace()
CompositeSpace ()
Member Function Documentation
add()
void add (SmartPtr< IComponentSpace > unnamed) inline
Parameters
[in] unnamed
References CompositeSpace< class >::add().
config_string()
std::string config_string () const inline inherited
References IGridFunctionSpace< TGridFunction >::config_string().
is_time_dependent()
bool is_time_dependent () const inline
References CompositeSpace< class >::is_time_dependent().
update_time_data()
void update_time_data (double unnamed) inline
Parameters
[in] unnamed
References CompositeSpace< class >::update_time_data().