Registry: Variant Class Reference
Variant Class Reference
Public Member Functions
bool to_bool () const
double to_double () const
float to_float () const
int to_int () const
double to_number () const
size_t to_size_t () const
const char * to_string () const
Variant ()
Variant (bool unnamed)
Variant (const char *unnamed)
Variant (const Variant *unnamed)
Variant (double unnamed)
Variant (float unnamed)
Variant (int unnamed)
Variant (size_t unnamed)
Constructor & Destructor Documentation
Variant() [1/8]
Variant ()
Variant() [2/8]
Variant (bool unnamed)
Parameters
[in] unnamed
Variant() [3/8]
Variant (int unnamed)
Parameters
[in] unnamed
Variant() [4/8]
Variant (size_t unnamed)
Parameters
[in] unnamed
Variant() [5/8]
Variant (float unnamed)
Parameters
[in] unnamed
Variant() [6/8]
Variant (double unnamed)
Parameters
[in] unnamed
Variant() [7/8]
Variant (const char * unnamed)
Parameters
[in] unnamed
Variant() [8/8]
Variant (const Variant * unnamed)
Parameters
[in] unnamed
Member Function Documentation
to_bool()
bool to_bool () const inline
References Variant::to_bool().
to_double()
double to_double () const inline
References Variant::to_double().
to_float()
float to_float () const inline
References Variant::to_float().
to_int()
int to_int () const inline
References Variant::to_int().
to_number()
double to_number () const inline
References Variant::to_number().
to_size_t()
size_t to_size_t () const inline
References Variant::to_size_t().
to_string()
const char* to_string () const inline
References to_string().