Registry: FixedConvergenceCheck Class Reference
FixedConvergenceCheck Class Reference
Convergence Check.
Public Member Functions
double avg_rate () const
std::string config_string () const
double defect () const
returns the current defect
FixedConvergenceCheck (double unnamed)
bool iteration_ended ()
double reduction () const
returns the current relative reduction
int step () const
returns the current number of steps
Detailed Description
Convergence Check.
Note
default specialization is FixedConvergenceCheckCPU1
See also
ug::FixedConvergenceCheck
Constructor & Destructor Documentation
FixedConvergenceCheck()
FixedConvergenceCheck (double unnamed)
Parameters
[in] unnamed
Member Function Documentation
avg_rate()
double avg_rate () const inline inherited
References IConvergenceCheck< TVector >::avg_rate().
config_string()
std::string config_string () const inline inherited
References IConvergenceCheck< TVector >::config_string().
defect()
double defect () const inline inherited
returns the current defect
Returns
defect
References IConvergenceCheck< TVector >::defect().
iteration_ended()
bool iteration_ended () inline inherited
References IConvergenceCheck< TVector >::iteration_ended().
reduction()
double reduction () const inline inherited
returns the current relative reduction
Returns
reduction
References IConvergenceCheck< TVector >::reduction().
step()
int step () const inline inherited
returns the current number of steps
Returns
step
References IConvergenceCheck< TVector >::step().