Registry: SphereProjector Class Reference
SphereProjector Class Reference
Public Member Functions
const Vec * center () const
SmartPtr< IGeometry > geometry () const
double influence_radius () const
double radius () const
void set_center (const Vec *center)
void set_geometry (SmartPtr< IGeometry > geometry)
void set_influence_radius (double influenceRadius)
void set_radius (double radius)
SphereProjector ()
SphereProjector (const Vec *unnamed)
SphereProjector (const Vec *unnamed, double unnamed)
SphereProjector (const Vec *unnamed, double unnamed, double unnamed)
SphereProjector (SmartPtr< IGeometry > unnamed, const Vec *unnamed, double unnamed, double unnamed)
Constructor & Destructor Documentation
SphereProjector() [1/5]
SphereProjector ()
SphereProjector() [2/5]
SphereProjector (const Vec * unnamed)
Parameters
[in] unnamed
SphereProjector() [3/5]
SphereProjector (const Vec * unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
SphereProjector() [4/5]
SphereProjector (const Vec * unnamed, double unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
SphereProjector() [5/5]
SphereProjector (SmartPtr< IGeometry > unnamed, const Vec * unnamed, double unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
Member Function Documentation
center()
const Vec* center () const inline
Returns
center
References SphereProjector::center().
geometry()
SmartPtr<IGeometry> geometry () const inline inherited
Returns
geometry
References RefinementProjector::geometry().
influence_radius()
double influence_radius () const inline
Returns
influenceRadius
References SphereProjector::influence_radius().
radius()
double radius () const inline
Returns
radius
References SphereProjector::radius().
set_center()
void set_center (const Vec * center) inline
Parameters
[in] center
References SphereProjector::set_center().
set_geometry()
void set_geometry (SmartPtr< IGeometry > geometry) inline inherited
Parameters
[in] geometry
References RefinementProjector::set_geometry().
set_influence_radius()
void set_influence_radius (double influenceRadius) inline
Parameters
[in] influenceRadius
References SphereProjector::set_influence_radius().
set_radius()
void set_radius (double radius) inline
Parameters
[in] radius
References SphereProjector::set_radius().