Registry: DomainDiscretization Class Reference
DomainDiscretization Class Reference
Public Member Functions
void add (SmartPtr< IDomainConstraint > Post_Process)
void add_elem_error_indicator (SmartPtr< IElemError > OPTIONAL:_Add_element-wise_error_indicator)
void adjust_solution (GridFunction *unnamed)
void adjust_solution (Vector *unnamed)
SmartPtr< ApproximationSpace > approximation_space ()
get this domain discretization's approximation space
ConstSmartPtr< ApproximationSpace > approximation_space () const
get this domain discretization's approximation space
SmartPtr< AssTuner > ass_tuner ()
get this domain discretization's assembling tuner
void assemble_defect (Vector *d(u), const Vector *u)
Assembles Defect on surface grid.
void assemble_jacobian (Matrix *J(u), const Vector *u)
assembles jacobian on surface grid
void assemble_jacobian (Matrix *unnamed, ConstSmartPtr< SolutionTimeSeries > unnamed, double unnamed)
void assemble_linear (Matrix *A, Vector *b)
Assembles Matrix and rhs on surface grid.
void assemble_linear (Matrix *unnamed, GridFunction *unnamed)
void assemble_mass_matrix (Matrix *M, const Vector *u)
assembles mass matrix on surface grid
void assemble_rhs (Vector *rhs, const Vector *u)
assembles right-hand side on surface grid
void assemble_rhs (Vector *unnamed, GridFunction *unnamed)
void assemble_stiffness_matrix (Matrix *A, const Vector *u)
assembles stiffness matrix on surface grid
void calc_error (const GridFunction *Calculate_element-wise_error_indicators_from_error_estimator)
DomainDiscretization (SmartPtr< ApproximationSpace > ApproximationSpace)
void invalidate_error ()
bool is_error_valid ()
void mark_with_strategy (IRefiner *unnamed, SmartPtr< IElementMarkingStrategy > unnamed)
void remove (SmartPtr< IDomainConstraint > Post_Process)
void remove_elem_error_indicator (SmartPtr< IElemError > OPTIONAL:_Remove_element-wise_error_indicator)
Detailed Description
Note
default specialization is DomainDiscretization2dCPU1
See also
ug::DomainDiscretization
Constructor & Destructor Documentation
DomainDiscretization()
DomainDiscretization (SmartPtr< ApproximationSpace > ApproximationSpace)
Parameters
[in] ApproximationSpace
Member Function Documentation
add()
void add (SmartPtr< IDomainConstraint > Post_Process) inline
Parameters
[in] Post_Process
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::add().
add_elem_error_indicator()
void add_elem_error_indicator (SmartPtr< IElemError > OPTIONAL:_Add_element- wise_error_indicator) inline
Parameters
[in] OPTIONAL:_Add_element-wise_error_indicator
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::add_elem_error_indicator().
adjust_solution() [1/2]
void adjust_solution (GridFunction * unnamed) inline
Parameters
[in] unnamed
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::adjust_solution().
adjust_solution() [2/2]
void adjust_solution (Vector * unnamed) inline inherited
Parameters
[in] unnamed
References IAssemble< TAlgebra >::adjust_solution().
approximation_space() [1/2]
SmartPtr<ApproximationSpace> approximation_space () inline
get this domain discretization's approximation space
Returns
approximation space
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::approximation_space().
approximation_space() [2/2]
ConstSmartPtr<ApproximationSpace> approximation_space () const inline
get this domain discretization's approximation space
Returns
approximation space
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::approximation_space().
ass_tuner()
SmartPtr<AssTuner> ass_tuner () inline
get this domain discretization's assembling tuner
Returns
assembling tuner
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::ass_tuner().
assemble_defect()
void assemble_defect (Vector * du, const Vector * u) inline inherited
Assembles Defect on surface grid.
Parameters
[in] d(u)
[in] u
References IAssemble< TAlgebra >::assemble_defect().
assemble_jacobian() [1/2]
void assemble_jacobian (Matrix * Ju, const Vector * u) inline inherited
assembles jacobian on surface grid
Parameters
[in] J(u)
[in] u
References IAssemble< TAlgebra >::assemble_jacobian().
assemble_jacobian() [2/2]
void assemble_jacobian (Matrix * unnamed, ConstSmartPtr< SolutionTimeSeries > unnamed, double unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References IDomainDiscretization< class >::assemble_jacobian().
assemble_linear() [1/2]
void assemble_linear (Matrix * A, Vector * b) inline inherited
Assembles Matrix and rhs on surface grid.
Parameters
[in] A
[in] b
References IAssemble< TAlgebra >::assemble_linear().
assemble_linear() [2/2]
void assemble_linear (Matrix * unnamed, GridFunction * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::assemble_linear().
assemble_mass_matrix()
void assemble_mass_matrix (Matrix * M, const Vector * u) inline inherited
assembles mass matrix on surface grid
Parameters
[in] M
[in] u
References IAssemble< TAlgebra >::assemble_mass_matrix().
assemble_rhs() [1/2]
void assemble_rhs (Vector * rhs, const Vector * u) inline inherited
assembles right-hand side on surface grid
Parameters
[in] rhs
[in] u
References IAssemble< TAlgebra >::assemble_rhs().
assemble_rhs() [2/2]
void assemble_rhs (Vector * unnamed, GridFunction * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::assemble_rhs().
assemble_stiffness_matrix()
void assemble_stiffness_matrix (Matrix * A, const Vector * u) inline inherited
assembles stiffness matrix on surface grid
Parameters
[in] A
[in] u
References IAssemble< TAlgebra >::assemble_stiffness_matrix().
calc_error()
void calc_error (const GridFunction *Calculate_element- wise_error_indicators_from_error_estimator) inline
Parameters
[in] Calculate_element-wise_error_indicators_from_error_estimator
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::calc_error().
invalidate_error()
void invalidate_error () inline
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::invalidate_error().
is_error_valid()
bool is_error_valid () inline
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::is_error_valid().
mark_with_strategy()
void mark_with_strategy (IRefiner * unnamed, SmartPtr< IElementMarkingStrategy > unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::mark_with_strategy().
remove()
void remove (SmartPtr< IDomainConstraint > Post_Process) inline
Parameters
[in] Post_Process
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::remove().
remove_elem_error_indicator()
void remove_elem_error_indicator (SmartPtr< IElemError > OPTIONAL:_Remove_element- wise_error_indicator) inline
Parameters
[in] OPTIONAL:_Remove_element-wise_error_indicator
References DomainDiscretizationBase< TDomain, TAlgebra, StdGlobAssembler< TDomain, TAlgebra > >::remove_elem_error_indicator().