Registry: CylinderProjector Class Reference
CylinderProjector Class Reference
Public Member Functions
const Vec * axis () const
const Vec * center () const
CylinderProjector ()
CylinderProjector (const Vec *unnamed, const Vec *unnamed)
CylinderProjector (const Vec *unnamed, const Vec *unnamed, double unnamed)
CylinderProjector (const Vec *unnamed, const Vec *unnamed, double unnamed, double unnamed)
CylinderProjector (SmartPtr< IGeometry > unnamed, const Vec *unnamed, const Vec *unnamed, double unnamed, double unnamed)
SmartPtr< IGeometry > geometry () const
double influence_radius () const
double radius () const
void set_axis (const Vec *axis)
void set_center (const Vec *center)
void set_geometry (SmartPtr< IGeometry > geometry)
void set_influence_radius (double influenceRadius)
void set_radius (double radius)
Constructor & Destructor Documentation
CylinderProjector() [1/5]
CylinderProjector ()
CylinderProjector() [2/5]
CylinderProjector (const Vec * unnamed, const Vec * unnamed)
Parameters
[in] unnamed
[in] unnamed
CylinderProjector() [3/5]
CylinderProjector (const Vec * unnamed, const Vec * unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
CylinderProjector() [4/5]
CylinderProjector (const Vec * unnamed, const Vec * unnamed, double unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
CylinderProjector() [5/5]
CylinderProjector (SmartPtr< IGeometry > unnamed, const Vec * unnamed, const Vec * unnamed, double unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
Member Function Documentation
axis()
const Vec* axis () const inline
Returns
axis
References CylinderProjector::axis().
Referenced by CylinderProjector::set_axis().
center()
const Vec* center () const inline
Returns
center
References CylinderProjector::center().
Referenced by CylinderProjector::set_center().
geometry()
SmartPtr<IGeometry> geometry () const inline inherited
Returns
geometry
References RefinementProjector::geometry().
Referenced by RefinementProjector::set_geometry(), and ProjectionHandler::set_geometry_all().
influence_radius()
double influence_radius () const inline
Returns
influenceRadius
References CylinderProjector::influence_radius().
radius()
double radius () const inline
Returns
radius
References CylinderProjector::radius().
Referenced by CylinderProjector::set_radius().
set_axis()
void set_axis (const Vec * axis) inline
Parameters
[in] axis
References CylinderProjector::axis(), and CylinderProjector::set_axis().
set_center()
void set_center (const Vec * center) inline
Parameters
[in] center
References CylinderProjector::center(), and CylinderProjector::set_center().
set_geometry()
void set_geometry (SmartPtr< IGeometry > geometry) inline inherited
Parameters
[in] geometry
References RefinementProjector::geometry(), and RefinementProjector::set_geometry().
set_influence_radius()
void set_influence_radius (double influenceRadius) inline
Parameters
[in] influenceRadius
References CylinderProjector::set_influence_radius().
set_radius()
void set_radius (double radius) inline
Parameters
[in] radius
References CylinderProjector::radius(), and CylinderProjector::set_radius().