Registry: MultiStepTimeDiscretization Class Reference
MultiStepTimeDiscretization Class Reference
Public Member Functions
void calc_error (const Vector *unnamed)
calculate error indicators for elements from error estimators of the elemDiscs
void finish_step (SmartPtr< SolutionTimeSeries > unnamed)
finishes the assembling of defect/Jacobian for a time step
void finish_step_elem (SmartPtr< SolutionTimeSeries > unnamed)
double future_time () const
void invalidate_error ()
bool is_error_valid ()
void mark_for_coarsening (IRefiner *mark_elements_for_coarsening_according_to_calculated_error_indicators, double unnamed, double unnamed, int unnamed)
void mark_for_refinement (IRefiner *mark_elements_for_refinement_according_to_calculated_error_indicators, double unnamed, double unnamed, int unnamed)
size_t num_prev_steps () const
size_t num_stages () const
void prepare_step (SmartPtr< SolutionTimeSeries > unnamed, double unnamed)
prepares the assembling of defect/Jacobian for a time step
void prepare_step_elem (SmartPtr< SolutionTimeSeries > unnamed, double unnamed)
void set_stage (size_t stage)
Private Member Functions
MultiStepTimeDiscretization ()=delete
Constructor hidden / deactivated.
Detailed Description
Note
default specialization is MultiStepTimeDiscretizationCPU1
See also
ug::MultiStepTimeDiscretization
Constructor & Destructor Documentation
MultiStepTimeDiscretization () private delete
Constructor hidden / deactivated.
Member Function Documentation
void calc_error (const Vector * unnamed) inline
calculate error indicators for elements from error estimators of the elemDiscs
Parameters
[in] unnamed
References MultiStepTimeDiscretization< class >::calc_error().
void finish_step (SmartPtr< SolutionTimeSeries > unnamed) inline inherited
finishes the assembling of defect/Jacobian for a time step
Parameters
[in] unnamed
References ITimeDiscretization< class >::finish_step().
void finish_step_elem (SmartPtr< SolutionTimeSeries > unnamed) inline inherited
Parameters
[in] unnamed
References ITimeDiscretization< class >::finish_step_elem().
double future_time () const inline inherited
Returns
the future time point (i.e. the one that will be computed)
References ITimeDiscretization< class >::future_time().
void invalidate_error () inline
References MultiStepTimeDiscretization< class >::invalidate_error().
bool is_error_valid () inline
References MultiStepTimeDiscretization< class >::is_error_valid().
void mark_for_coarsening (IRefiner * mark_elements_for_coarsening_according_to_calculated_error_indicators, double unnamed, double unnamed, int unnamed) inline
Parameters
[in] mark_elements_for_coarsening_according_to_calculated_error_indicators
[in] unnamed
[in] unnamed
[in] unnamed
References MultiStepTimeDiscretization< class >::mark_for_coarsening().
void mark_for_refinement (IRefiner * mark_elements_for_refinement_according_to_calculated_error_indicators, double unnamed, double unnamed, int unnamed) inline
Parameters
[in] mark_elements_for_refinement_according_to_calculated_error_indicators
[in] unnamed
[in] unnamed
[in] unnamed
References MultiStepTimeDiscretization< class >::mark_for_refinement().
size_t num_prev_steps () const inline inherited
References ITimeDiscretization< class >::num_prev_steps().
size_t num_stages () const inline inherited
Returns
the number of stages
References ITimeDiscretization< class >::num_stages().
void prepare_step (SmartPtr< SolutionTimeSeries > unnamed, double unnamed) inline inherited
prepares the assembling of defect/Jacobian for a time step
Parameters
[in] unnamed
[in] unnamed
References ITimeDiscretization< class >::prepare_step().
void prepare_step_elem (SmartPtr< SolutionTimeSeries > unnamed, double unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ITimeDiscretization< class >::prepare_step_elem().
void set_stage (size_t stage) inline inherited
Parameters
[in] stage
References ITimeDiscretization< class >::set_stage().