Registry: LoadBalancer Class Reference
LoadBalancer Class Reference
Public Member Functions
void create_quality_record (const char *unnamed)
void enable_vertical_interface_creation (bool unnamed)
double estimate_distribution_quality ()
void print_quality_records () const
bool problems_occurred ()
bool rebalance ()
void set_balance_threshold (double unnamed)
void set_balance_weights (SmartPtr< IBalanceWeights > unnamed)
void set_element_threshold (size_t unnamed)
void set_next_process_hierarchy (SmartPtr< ProcessHierarchy > unnamed)
void set_partitioner (SmartPtr< IPartitioner > unnamed)
Private Member Functions
LoadBalancer ()=delete
Constructor hidden / deactivated.
Constructor & Destructor Documentation
LoadBalancer () private delete
Constructor hidden / deactivated.
Member Function Documentation
void create_quality_record (const char * unnamed) inline
Parameters
[in] unnamed
References LoadBalancer::create_quality_record().
void enable_vertical_interface_creation (bool unnamed) inline
Parameters
[in] unnamed
References LoadBalancer::enable_vertical_interface_creation().
double estimate_distribution_quality () inline
References LoadBalancer::estimate_distribution_quality().
void print_quality_records () const inline
References LoadBalancer::print_quality_records().
bool problems_occurred () inline
References LoadBalancer::problems_occurred().
bool rebalance () inline
References LoadBalancer::rebalance().
void set_balance_threshold (double unnamed) inline
Parameters
[in] unnamed
References LoadBalancer::set_balance_threshold().
void set_balance_weights (SmartPtr< IBalanceWeights > unnamed) inline
Parameters
[in] unnamed
References LoadBalancer::set_balance_weights().
void set_element_threshold (size_t unnamed) inline
Parameters
[in] unnamed
References LoadBalancer::set_element_threshold().
void set_next_process_hierarchy (SmartPtr< ProcessHierarchy > unnamed) inline
Parameters
[in] unnamed
References LoadBalancer::set_next_process_hierarchy().
void set_partitioner (SmartPtr< IPartitioner > unnamed) inline
Parameters
[in] unnamed
References LoadBalancer::set_partitioner().