Registry: BackwardGaussSeidel Class Reference
BackwardGaussSeidel Class Reference
Backward Gauss Seidel Preconditioner.
Public Member Functions
bool apply (Vector *unnamed, const Vector *unnamed)
bool apply_update_defect (Vector *unnamed, Vector *unnamed)
BackwardGaussSeidel ()
SmartPtr< ILinearIterator > clone ()
returns a clone of the object which can be modified independently
std::string config_string () const
string to display configuration of the linear iterator
void enable_consistent_interfaces (bool enable)
makes the matrix and defect consistent at the proc. interfaces
void enable_overlap (bool enable)
Enables matrix overlap. This also means that interfaces are consistent.
bool init (SmartPtr< ILinearOperator > unnamed)
const char * name () const
void set_damp (double damp)
set the damping to a number
void set_sor_relax (double sor_relaxation)
sets sor relaxation parameter
Detailed Description
Backward Gauss Seidel Preconditioner.
Note
default specialization is BackwardGaussSeidelCPU1
See also
ug::BackwardGaussSeidel
Constructor & Destructor Documentation
BackwardGaussSeidel()
BackwardGaussSeidel ()
Member Function Documentation
apply()
bool apply (Vector * unnamed, const Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply().
apply_update_defect()
bool apply_update_defect (Vector * unnamed, Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply_update_defect().
clone()
SmartPtr<ILinearIterator> clone () inline inherited
returns a clone of the object which can be modified independently
Returns
SmartPointer to a copy of this object
References ILinearIterator< X, Y >::clone().
config_string()
std::string config_string () const inline inherited
string to display configuration of the linear iterator
Returns
strConfiguration
References ILinearIterator< X, Y >::config_string().
enable_consistent_interfaces()
void enable_consistent_interfaces (bool enable) inline inherited
makes the matrix and defect consistent at the proc. interfaces
Parameters
[in] enable
References GaussSeidelBase< TAlgebra >::enable_consistent_interfaces().
enable_overlap()
void enable_overlap (bool enable) inline inherited
Enables matrix overlap. This also means that interfaces are consistent.
Parameters
[in] enable
References GaussSeidelBase< TAlgebra >::enable_overlap().
init()
bool init (SmartPtr< ILinearOperator > unnamed) inline inherited
Parameters
[in] unnamed
References ILinearIterator< X, Y >::init().
name()
const char* name () const inline inherited
References ILinearIterator< X, Y >::name().
set_damp()
void set_damp (double damp) inline inherited
set the damping to a number
Parameters
[in] damp
References ILinearIterator< X, Y >::set_damp().
set_sor_relax()
void set_sor_relax (double sor_relaxation) inline inherited
sets sor relaxation parameter
Parameters
[in] sor_relaxation
References GaussSeidelBase< TAlgebra >::set_sor_relax().