Registry: UGXFileInfo Class Reference
UGXFileInfo Class Reference
Public Member Functions
bool grid_has_edges (size_t gridInd) const
bool grid_has_faces (size_t gridInd) const
bool grid_has_vertices (size_t gridInd) const
bool grid_has_volumes (size_t gridInd) const
std::string grid_name (size_t gridInd) const
size_t grid_world_dimension (size_t gridInd) const
size_t num_grids () const
size_t num_subset_handlers (size_t unnamed) const
size_t num_subsets (size_t unnamed, size_t unnamed) const
bool parse_file (const char *filename)
size_t physical_grid_dimension (size_t gridInd) const
std::string subset_handler_name (size_t gridInd, size_t shInd) const
std::string subset_name (size_t gridInd, size_t shInd, size_t subsetInd) const
size_t topological_grid_dimension (size_t gridInd) const
UGXFileInfo ()
Constructor & Destructor Documentation
UGXFileInfo()
UGXFileInfo ()
Member Function Documentation
grid_has_edges()
bool grid_has_edges (size_t gridInd) const inline
Parameters
[in] gridInd
References UGXFileInfo::grid_has_edges().
grid_has_faces()
bool grid_has_faces (size_t gridInd) const inline
Parameters
[in] gridInd
References UGXFileInfo::grid_has_faces().
grid_has_vertices()
bool grid_has_vertices (size_t gridInd) const inline
Parameters
[in] gridInd
References UGXFileInfo::grid_has_vertices().
grid_has_volumes()
bool grid_has_volumes (size_t gridInd) const inline
Parameters
[in] gridInd
References UGXFileInfo::grid_has_volumes().
grid_name()
std::string grid_name (size_t gridInd) const inline
Parameters
[in] gridInd
Returns
grid name
References UGXFileInfo::grid_name().
grid_world_dimension()
size_t grid_world_dimension (size_t gridInd) const inline
Parameters
[in] gridInd
References UGXFileInfo::grid_world_dimension().
num_grids()
size_t num_grids () const inline
References UGXFileInfo::num_grids().
num_subset_handlers()
size_t num_subset_handlers (size_t unnamed) const inline
Parameters
[in] unnamed
References UGXFileInfo::num_subset_handlers().
num_subsets()
size_t num_subsets (size_t unnamed, size_t unnamed) const inline
Parameters
[in] unnamed
[in] unnamed
References UGXFileInfo::num_subsets().
parse_file()
bool parse_file (const char * filename) inline
Parameters
[in] filename
References UGXFileInfo::parse_file().
physical_grid_dimension()
size_t physical_grid_dimension (size_t gridInd) const inline
Parameters
[in] gridInd
References UGXFileInfo::physical_grid_dimension().
subset_handler_name()
std::string subset_handler_name (size_t gridInd, size_t shInd) const inline
Parameters
[in] gridInd
[in] shInd
References UGXFileInfo::subset_handler_name().
subset_name()
std::string subset_name (size_t gridInd, size_t shInd, size_t subsetInd) const inline
Parameters
[in] gridInd
[in] shInd
[in] subsetInd
References UGXFileInfo::subset_name().
topological_grid_dimension()
size_t topological_grid_dimension (size_t gridInd) const inline
Parameters
[in] gridInd
References UGXFileInfo::topological_grid_dimension().