Registry: NewtonSolver Class Reference
NewtonSolver Class Reference
Public Member Functions
void add_inner_step_update (SmartPtr< INewtonUpdate > unnamed)
void add_step_update (SmartPtr< INewtonUpdate > unnamed)
bool apply (Vector *u)
double average_linear_steps (size_t iNewtonStep) const
void clear_average_convergence ()
void clear_inner_step_update (SmartPtr< INewtonUpdate > unnamed)
void clear_step_update (SmartPtr< INewtonUpdate > unnamed)
std::string config_string () const
void disable_line_search ()
bool init (SmartPtr< IOperator > op)
int last_num_newton_steps () const
SmartPtr< ILineSearch > line_search ()
NewtonSolver ()
NewtonSolver (SmartPtr< IOperator > Operator)
NewtonSolver (SmartPtr< IAssemble > AssemblingRoutine)
int num_linsolver_calls (size_t iNewtonStep) const
int num_linsolver_steps (size_t iNewtonStep) const
size_t num_newton_steps () const
bool prepare (Vector *u)
void print_average_convergence () const
void set_convergence_check (SmartPtr< IConvergenceCheck > convCheck)
void set_line_search (SmartPtr< ILineSearch > lineSeach)
void set_linear_solver (SmartPtr< ILinearOperatorInverse > linSolver)
double total_average_linear_steps () const
int total_linsolver_calls () const
int total_linsolver_steps () const
Detailed Description
Note
default specialization is NewtonSolverCPU1
See also
ug::NewtonSolver
Constructor & Destructor Documentation
NewtonSolver() [1/3]
NewtonSolver ()
NewtonSolver() [2/3]
NewtonSolver (SmartPtr< IOperator > Operator)
Parameters
[in] Operator
NewtonSolver() [3/3]
NewtonSolver (SmartPtr< IAssemble > AssemblingRoutine)
Parameters
[in] AssemblingRoutine
Member Function Documentation
add_inner_step_update()
void add_inner_step_update (SmartPtr< INewtonUpdate > unnamed) inline
Parameters
[in] unnamed
References NewtonSolver< class >::add_inner_step_update().
add_step_update()
void add_step_update (SmartPtr< INewtonUpdate > unnamed) inline
Parameters
[in] unnamed
References NewtonSolver< class >::add_step_update().
apply()
bool apply (Vector * u) inline
Parameters
[in] u
Returns
success
References NewtonSolver< class >::apply().
average_linear_steps()
double average_linear_steps (size_t iNewtonStep) const inline
Parameters
[in] iNewtonStep
Returns
average number of linsolver steps per linsolver call in newton step iNewtonStep
References NewtonSolver< class >::average_linear_steps().
clear_average_convergence()
void clear_average_convergence () inline
References NewtonSolver< class >::clear_average_convergence().
clear_inner_step_update()
void clear_inner_step_update (SmartPtr< INewtonUpdate > unnamed) inline
Parameters
[in] unnamed
References NewtonSolver< class >::clear_inner_step_update().
clear_step_update()
void clear_step_update (SmartPtr< INewtonUpdate > unnamed) inline
Parameters
[in] unnamed
References NewtonSolver< class >::clear_step_update().
config_string()
std::string config_string () const inline
References NewtonSolver< class >::config_string().
disable_line_search()
void disable_line_search () inline
References NewtonSolver< class >::disable_line_search().
init()
bool init (SmartPtr< IOperator > op) inline
Parameters
[in] op
Returns
success
References NewtonSolver< class >::init().
last_num_newton_steps()
int last_num_newton_steps () const inline
Returns
Number of newton steps performed in last iteration
References NewtonSolver< class >::last_num_newton_steps().
line_search()
SmartPtr<ILineSearch> line_search () inline
Returns
lineSeach
References NewtonSolver< class >::line_search().
num_linsolver_calls()
int num_linsolver_calls (size_t iNewtonStep) const inline
Parameters
[in] iNewtonStep
Returns
number of linsolver calls in iNewtonStep
References NewtonSolver< class >::num_linsolver_calls().
num_linsolver_steps()
int num_linsolver_steps (size_t iNewtonStep) const inline
Parameters
[in] iNewtonStep
Returns
number of linsolver steps in newton step iNewtonStep
References NewtonSolver< class >::num_linsolver_steps().
num_newton_steps()
size_t num_newton_steps () const inline
Returns
number of newton steps in history
References NewtonSolver< class >::num_newton_steps().
prepare()
bool prepare (Vector * u) inline
Parameters
[in] u
Returns
success
References NewtonSolver< class >::prepare().
print_average_convergence()
void print_average_convergence () const inline
References NewtonSolver< class >::print_average_convergence().
set_convergence_check()
void set_convergence_check (SmartPtr< IConvergenceCheck > convCheck) inline
Parameters
[in] convCheck
References NewtonSolver< class >::set_convergence_check().
set_line_search()
void set_line_search (SmartPtr< ILineSearch > lineSeach) inline
Parameters
[in] lineSeach
References NewtonSolver< class >::set_line_search().
set_linear_solver()
void set_linear_solver (SmartPtr< ILinearOperatorInverse > linSolver) inline
Parameters
[in] linSolver
References NewtonSolver< class >::set_linear_solver().
total_average_linear_steps()
double total_average_linear_steps () const inline
Returns
total average number of linsolver steps per linsolver call
References NewtonSolver< class >::total_average_linear_steps().
total_linsolver_calls()
int total_linsolver_calls () const inline
Returns
total number of linsolver calls
References NewtonSolver< class >::total_linsolver_calls().
total_linsolver_steps()
int total_linsolver_steps () const inline
Returns
total number of linsolver steps
References NewtonSolver< class >::total_linsolver_steps().