Registry: ConvCheck Class Reference
ConvCheck Class Reference
Convergence Check.
Public Member Functions
double avg_rate () const
std::string config_string () const
ConvCheck ()
ConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction, bool Verbosity)
ConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction, bool Verbositysupress_unsuccessful_return, bool unnamed)
ConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction)
double defect () const
returns the current defect
bool iteration_ended ()
double previous_defect () const
double reduction () const
returns the current relative reduction
void set_maximum_steps (int Maximum_Steps)
maximum number of steps to do
void set_minimum_defect (double Minimum_Defect)
void set_reduction (double Relative_Reduction)
void set_supress_unsuccessful (bool supress_false_return)
void set_verbose (bool Verbosity)
int step () const
returns the current number of steps
Detailed Description
Convergence Check.
Note
default specialization is ConvCheckCPU1
See also
ug::ConvCheck
Constructor & Destructor Documentation
ConvCheck() [1/4]
ConvCheck ()
ConvCheck() [2/4]
ConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction, bool Verbosity)
Parameters
[in] Maximum_Steps
[in] Minimum_Defect
[in] Relative_Reduction
[in] Verbosity
ConvCheck() [3/4]
ConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction, bool Verbositysupress_unsuccessful_return, bool unnamed)
Parameters
[in] Maximum_Steps
[in] Minimum_Defect
[in] Relative_Reduction
[in] Verbositysupress_unsuccessful_return
[in] unnamed
ConvCheck() [4/4]
ConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction)
Parameters
[in] Maximum_Steps
[in] Minimum_Defect
[in] Relative_Reduction
Member Function Documentation
avg_rate()
double avg_rate () const inline inherited
References IConvergenceCheck< TVector >::avg_rate().
config_string()
std::string config_string () const inline inherited
References IConvergenceCheck< TVector >::config_string().
defect()
double defect () const inline inherited
returns the current defect
Returns
defect
References IConvergenceCheck< TVector >::defect().
iteration_ended()
bool iteration_ended () inline inherited
References IConvergenceCheck< TVector >::iteration_ended().
previous_defect()
double previous_defect () const inline
reduction()
double reduction () const inline inherited
returns the current relative reduction
Returns
reduction
References IConvergenceCheck< TVector >::reduction().
set_maximum_steps()
void set_maximum_steps (int Maximum_Steps) inline
maximum number of steps to do
Parameters
[in] Maximum_Steps
set_minimum_defect()
void set_minimum_defect (double Minimum_Defect) inline
Parameters
[in] Minimum_Defect
set_reduction()
void set_reduction (double Relative_Reduction) inline
Parameters
[in] Relative_Reduction
set_supress_unsuccessful()
void set_supress_unsuccessful (bool supress_false_return) inline
Parameters
[in] supress_false_return
set_verbose()
void set_verbose (bool Verbosity) inline
Parameters
[in] Verbosity
step()
int step () const inline inherited
returns the current number of steps
Returns
step
References IConvergenceCheck< TVector >::step().