Registry: ConstUserVector Class Reference
ConstUserVector Class Reference
Public Member Functions
ConstUserVector ()
ConstUserVector (double Values)
ConstUserVector (std::vector< double > Values)
int get_dim () const
void print () const
void set_all_entries (double unnamed)
void set_entry (size_t unnamed, double unnamed)
std::string type () const
Detailed Description
Note
default specialization is ConstUserVector2d
See also
ug::ConstUserVector
Constructor & Destructor Documentation
ConstUserVector() [1/3]
ConstUserVector ()
ConstUserVector() [2/3]
ConstUserVector (double Values)
Parameters
[in] Values
ConstUserVector() [3/3]
ConstUserVector (std::vector< double > Values)
Parameters
[in] Values
Member Function Documentation
get_dim()
int get_dim () const inline inherited
References get_dim().
print()
void print () const inline
References ConstUserVector< dim, worldDim >::print().
set_all_entries()
void set_all_entries (double unnamed) inline
Parameters
[in] unnamed
References ConstUserVector< dim, worldDim >::set_all_entries().
set_entry()
void set_entry (size_t unnamed, double unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References ConstUserVector< dim, worldDim >::set_entry().
type()
std::string type () const inline inherited
References type().