Registry: IVectorDebugWriter Class Reference
IVectorDebugWriter Class Reference
Public Member Functions
void enter_section (const char *dirName)
SmartPtr< DebugWriterContext > get_context ()
void leave_section ()
void set_base_dir (const char *dir)
void set_context (SmartPtr< DebugWriterContext > context)
Private Member Functions
IVectorDebugWriter ()=delete
Constructor hidden / deactivated.
Detailed Description
Note
default specialization is IVectorDebugWriterCPU1
See also
ug::IVectorDebugWriter
Constructor & Destructor Documentation
IVectorDebugWriter()
IVectorDebugWriter () private delete
Constructor hidden / deactivated.
Member Function Documentation
enter_section()
void enter_section (const char * dirName) inline
Parameters
[in] dirName
References IVectorDebugWriter< TVector >::enter_section().
get_context()
SmartPtr<DebugWriterContext> get_context () inline
Returns
Gets the debugger writer context
References IVectorDebugWriter< TVector >::get_context().
leave_section()
void leave_section () inline
References IVectorDebugWriter< TVector >::leave_section().
set_base_dir()
void set_base_dir (const char * dir) inline
Parameters
[in] dir
References IVectorDebugWriter< TVector >::set_base_dir().
set_context()
void set_context (SmartPtr< DebugWriterContext > context) inline
Parameters
[in] context
References IVectorDebugWriter< TVector >::set_context().