Registry: NestedIterationSolver Class Reference
NestedIterationSolver Class Reference
Public Member Functions
bool apply (Vector *u)
int base_level () const
std::string config_string () const
void disable_adaptive_refinement ()
void enable_adaptive_refinement ()
bool init (SmartPtr< IOperator > op)
double last_error () const
NestedIterationSolver ()
NestedIterationSolver (SmartPtr< IAssemble > AssemblingRoutine)
NestedIterationSolver (SmartPtr< IAssemble > AssemblingRoutine, SmartPtr< IAssemble > ErrorRoutine)
NestedIterationSolver (SmartPtr< IOperator > Operator)
bool prepare (Vector *u)
void set_absolute_tolerance (double unnamed)
void set_associated_space (SmartPtr< IGridFunctionSpace > unnamed)
void set_base_level (int unnamed)
void set_debug_elem_error (SmartPtr< GridFunction > unnamed)
void set_linear_solver (SmartPtr< ILinearOperatorInverse > linSolver)
void set_max_steps (int unnamed)
void set_refinement_marking (SmartPtr< IElementMarkingStrategy > unnamed)
void set_refiner (SmartPtr< IRefiner > unnamed)
void set_tolerance (double unnamed)
void set_top_level (int unnamed)
int top_level () const
bool use_adaptive_refinement () const
Detailed Description
Note
default specialization is NestedIterationSolver2dCPU1
See also
ug::NestedIterationSolver
Constructor & Destructor Documentation
NestedIterationSolver() [1/4]
NestedIterationSolver ()
NestedIterationSolver() [2/4]
NestedIterationSolver (SmartPtr< IOperator > Operator)
Parameters
[in] Operator
NestedIterationSolver() [3/4]
NestedIterationSolver (SmartPtr< IAssemble > AssemblingRoutine)
Parameters
[in] AssemblingRoutine
NestedIterationSolver() [4/4]
NestedIterationSolver (SmartPtr< IAssemble > AssemblingRoutine, SmartPtr< IAssemble > ErrorRoutine)
Parameters
[in] AssemblingRoutine
[in] ErrorRoutine
Member Function Documentation
apply()
bool apply (Vector * u) inline
Parameters
[in] u
Returns
success
References NestedIterationSolver< class, class >::apply().
base_level()
int base_level () const inline
References NestedIterationSolver< class, class >::base_level().
config_string()
std::string config_string () const inline
References NestedIterationSolver< class, class >::config_string().
disable_adaptive_refinement()
void disable_adaptive_refinement () inline
References NestedIterationSolver< class, class >::disable_adaptive_refinement().
enable_adaptive_refinement()
void enable_adaptive_refinement () inline
References NestedIterationSolver< class, class >::enable_adaptive_refinement().
init()
bool init (SmartPtr< IOperator > op) inline
Parameters
[in] op
Returns
success
References NestedIterationSolver< class, class >::init().
last_error()
double last_error () const inline
References NestedIterationSolver< class, class >::last_error().
prepare()
bool prepare (Vector * u) inline
Parameters
[in] u
Returns
success
References NestedIterationSolver< class, class >::prepare().
set_absolute_tolerance()
void set_absolute_tolerance (double unnamed) inline
Parameters
[in] unnamed
References NestedIterationSolver< class, class >::set_absolute_tolerance().
set_associated_space()
void set_associated_space (SmartPtr< IGridFunctionSpace > unnamed) inline
Parameters
[in] unnamed
References NestedIterationSolver< class, class >::set_associated_space().
set_base_level()
void set_base_level (int unnamed) inline
Parameters
[in] unnamed
References NestedIterationSolver< class, class >::set_base_level().
set_debug_elem_error()
void set_debug_elem_error (SmartPtr< GridFunction > unnamed) inline
Parameters
[in] unnamed
References NestedIterationSolver< class, class >::set_debug_elem_error().
set_linear_solver()
void set_linear_solver (SmartPtr< ILinearOperatorInverse > linSolver) inline
Parameters
[in] linSolver
References NestedIterationSolver< class, class >::set_linear_solver().
set_max_steps()
void set_max_steps (int unnamed) inline
Parameters
[in] unnamed
References NestedIterationSolver< class, class >::set_max_steps().
set_refinement_marking()
void set_refinement_marking (SmartPtr< IElementMarkingStrategy > unnamed) inline
Parameters
[in] unnamed
References NestedIterationSolver< class, class >::set_refinement_marking().
set_refiner()
void set_refiner (SmartPtr< IRefiner > unnamed) inline
Parameters
[in] unnamed
References NestedIterationSolver< class, class >::set_refiner().
set_tolerance()
void set_tolerance (double unnamed) inline
Parameters
[in] unnamed
References NestedIterationSolver< class, class >::set_tolerance().
set_top_level()
void set_top_level (int unnamed) inline
Parameters
[in] unnamed
References NestedIterationSolver< class, class >::set_top_level().
top_level()
int top_level () const inline
References NestedIterationSolver< class, class >::top_level().
use_adaptive_refinement()
bool use_adaptive_refinement () const inline
References NestedIterationSolver< class, class >::use_adaptive_refinement().