Registry: PowerMethod Class Reference
PowerMethod Class Reference
Public Member Functions
int calculate_max_eigenvalue ()
int calculate_min_eigenvalue ()
size_t get_iterations ()
double get_max_eigenvalue ()
double get_min_eigenvalue ()
PowerMethod ()
void print_eigenvector ()
void print_matrix_A ()
void print_matrix_B ()
void set_linear_operator_A (SmartPtr< ILinearOperator > LinearOperatorA)
void set_linear_operator_B (SmartPtr< ILinearOperator > LinearOperatorB)
void set_max_iterations (size_t iterations)
void set_precision (double precision)
void set_solver (SmartPtr< ILinearOperatorInverse > Solver)
void set_start_vector (SmartPtr< Vector > start_vector)
Detailed Description
Note
default specialization is PowerMethodCPU1
See also
ug::PowerMethod
Constructor & Destructor Documentation
PowerMethod()
PowerMethod ()
Member Function Documentation
calculate_max_eigenvalue()
int calculate_max_eigenvalue () inline
References PowerMethod< class >::calculate_max_eigenvalue().
calculate_min_eigenvalue()
int calculate_min_eigenvalue () inline
References PowerMethod< class >::calculate_min_eigenvalue().
get_iterations()
size_t get_iterations () inline
References PowerMethod< class >::get_iterations().
get_max_eigenvalue()
double get_max_eigenvalue () inline
References PowerMethod< class >::get_max_eigenvalue().
get_min_eigenvalue()
double get_min_eigenvalue () inline
References PowerMethod< class >::get_min_eigenvalue().
print_eigenvector()
void print_eigenvector () inline
References PowerMethod< class >::print_eigenvector().
print_matrix_A()
void print_matrix_A () inline
References PowerMethod< class >::print_matrix_A().
print_matrix_B()
void print_matrix_B () inline
References PowerMethod< class >::print_matrix_B().
set_linear_operator_A()
void set_linear_operator_A (SmartPtr< ILinearOperator > LinearOperatorA) inline
Parameters
[in] LinearOperatorA
References PowerMethod< class >::set_linear_operator_A().
set_linear_operator_B()
void set_linear_operator_B (SmartPtr< ILinearOperator > LinearOperatorB) inline
Parameters
[in] LinearOperatorB
References PowerMethod< class >::set_linear_operator_B().
set_max_iterations()
void set_max_iterations (size_t iterations) inline
Parameters
[in] iterations
References PowerMethod< class >::set_max_iterations().
set_precision()
void set_precision (double precision) inline
Parameters
[in] precision
References PowerMethod< class >::set_precision().
set_solver()
void set_solver (SmartPtr< ILinearOperatorInverse > Solver) inline
Parameters
[in] Solver
References PowerMethod< class >::set_solver().
set_start_vector()
void set_start_vector (SmartPtr< Vector > start_vector) inline
Parameters
[in] start_vector
References PowerMethod< class >::set_start_vector().