Registry: IDomain Class Reference
IDomain Class Reference
Public Member Functions
SmartPtr< MGSubsetHandler > additional_subset_handler (std::string unnamed)
std::vector< std::string > additional_subset_handler_names () const
bool create_additional_subset_handler (std::string unnamed)
const DomainInfo * domain_info () const
SmartPtr< IGeometry > geometry3d () const
int get_dim () const
SmartPtr< MultiGrid > grid ()
SmartPtr< RefinementProjector > refinement_projector () const
void set_refinement_projector (SmartPtr< RefinementProjector > projector)
SmartPtr< MGSubsetHandler > subset_handler ()
Private Member Functions
IDomain ()=delete
Constructor hidden / deactivated.
Constructor & Destructor Documentation
IDomain()
IDomain () private delete
Constructor hidden / deactivated.
Member Function Documentation
additional_subset_handler()
SmartPtr<MGSubsetHandler> additional_subset_handler (std::string unnamed) inline
Parameters
[in] unnamed
Returns
SubsetHandler
References IDomain< TGrid, TSubsetHandler >::additional_subset_handler().
additional_subset_handler_names()
std::vector< std::string > additional_subset_handler_names () const inline
Returns
vector<string>
References IDomain< TGrid, TSubsetHandler >::additional_subset_handler_names().
create_additional_subset_handler()
bool create_additional_subset_handler (std::string unnamed) inline
Parameters
[in] unnamed
Returns
bool
References IDomain< TGrid, TSubsetHandler >::create_additional_subset_handler().
domain_info()
const DomainInfo* domain_info () const inline
Returns
DomainInfo
References IDomain< TGrid, TSubsetHandler >::domain_info().
geometry3d()
SmartPtr<IGeometry> geometry3d () const inline
Returns
geometry3d
References IDomain< TGrid, TSubsetHandler >::geometry3d().
get_dim()
int get_dim () const inline
References IDomain< TGrid, TSubsetHandler >::get_dim().
grid()
SmartPtr<MultiGrid> grid () inline
Returns
grid
References IDomain< TGrid, TSubsetHandler >::grid().
refinement_projector()
SmartPtr<RefinementProjector> refinement_projector () const inline
Returns
projector
References IDomain< TGrid, TSubsetHandler >::refinement_projector().
set_refinement_projector()
void set_refinement_projector (SmartPtr< RefinementProjector > projector) inline
Parameters
[in] projector
References IDomain< TGrid, TSubsetHandler >::set_refinement_projector().
subset_handler()
SmartPtr<MGSubsetHandler> subset_handler () inline
References IDomain< TGrid, TSubsetHandler >::subset_handler().