Registry: LognormalRandomField Class Reference
LognormalRandomField Class Reference
Public Member Functions
int get_dim () const
LognormalRandomField ()
LognormalRandomField (size_t LognormalRandomField, double unnamed, double unnamed, double unnamed)
N::mean_f::sigma_f::sigma.
void set_config (size_t N, double mean_f, double sigma_f, double sigma)
void set_no_exp ()
use this for display of log of the field
std::string type () const
Detailed Description
Note
default specialization is LognormalRandomField2d
See also
ug::LognormalRandomField
Constructor & Destructor Documentation
LognormalRandomField() [1/2]
LognormalRandomField ()
LognormalRandomField() [2/2]
LognormalRandomField (size_t LognormalRandomField, double unnamed, double unnamed, double unnamed)
N::mean_f::sigma_f::sigma.
Parameters
[in] LognormalRandomField
[in] unnamed
[in] unnamed
[in] unnamed
Member Function Documentation
get_dim()
int get_dim () const inline inherited
References get_dim().
set_config()
void set_config (size_t N, double mean_f, double sigma_f, double sigma) inline
Parameters
[in] N
[in] mean_f
[in] sigma_f
[in] sigma
References LognormalRandomField< class, dim, class >::set_config().
set_no_exp()
void set_no_exp () inline
use this for display of log of the field
References LognormalRandomField< class, dim, class >::set_no_exp().
type()
std::string type () const inline inherited
References type().