Registry: H1ComponentSpace Class Reference
H1ComponentSpace Class Reference
Public Member Functions
std::string config_string () const
double distance (GridFunction *unnamed, GridFunction *unnamed)
H1ComponentSpace (const char *fctNames)
H1ComponentSpace (const char *fctNames, _order, int unnamed)
H1ComponentSpace (const char *fctNames, _subsetNames, _order, const char *unnamed, int unnamed)
double norm (GridFunction *unnamed)
Detailed Description
Note
default specialization is H1ComponentSpace2dCPU1
See also
ug::H1ComponentSpace
Constructor & Destructor Documentation
H1ComponentSpace() [1/3]
H1ComponentSpace (const char * fctNames)
Parameters
[in] fctNames
H1ComponentSpace() [2/3]
H1ComponentSpace (const char * fctNames, _order , int unnamed)
Parameters
[in] fctNames,_order
[in] unnamed
H1ComponentSpace() [3/3]
H1ComponentSpace (const char * fctNames, _subsetNames , _order , const char * unnamed, int unnamed)
Parameters
[in] fctNames,_subsetNames,_order
[in] unnamed
[in] unnamed
Member Function Documentation
config_string()
std::string config_string () const inline inherited
References IGridFunctionSpace< TGridFunction >::config_string().
distance()
double distance (GridFunction * unnamed, GridFunction * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References IComponentSpace< class >::distance().
norm()
double norm (GridFunction * unnamed) inline inherited
Parameters
[in] unnamed
References IComponentSpace< class >::norm().