Registry: CylinderCutProjector Class Reference
CylinderCutProjector Class Reference
Public Member Functions
const Vec3d * axis () const
const Vec3d * center () const
CylinderCutProjector ()
CylinderCutProjector (const Vec3d *unnamed, const Vec3d *unnamed, double unnamed)
CylinderCutProjector (SmartPtr< IGeometry > unnamed, const Vec3d *unnamed, const Vec3d *unnamed, double unnamed)
SmartPtr< IGeometry > geometry () const
double radius () const
void set_axis (const Vec3d *axis)
void set_center (const Vec3d *center)
void set_geometry (SmartPtr< IGeometry > geometry)
void set_radius (double radius)
Constructor & Destructor Documentation
CylinderCutProjector() [1/3]
CylinderCutProjector ()
CylinderCutProjector() [2/3]
CylinderCutProjector (const Vec3d * unnamed, const Vec3d * unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
CylinderCutProjector() [3/3]
CylinderCutProjector (SmartPtr< IGeometry > unnamed, const Vec3d * unnamed, const Vec3d * unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
Member Function Documentation
axis()
const Vec3d* axis () const inline
Returns
axis
References CylinderCutProjector::axis().
center()
const Vec3d* center () const inline
Returns
center
References CylinderCutProjector::center().
geometry()
SmartPtr<IGeometry> geometry () const inline inherited
Returns
geometry
References RefinementProjector::geometry().
radius()
double radius () const inline
Returns
radius
References CylinderCutProjector::radius().
set_axis()
void set_axis (const Vec3d * axis) inline
Parameters
[in] axis
References CylinderCutProjector::set_axis().
set_center()
void set_center (const Vec3d * center) inline
Parameters
[in] center
References CylinderCutProjector::set_center().
set_geometry()
void set_geometry (SmartPtr< IGeometry > geometry) inline inherited
Parameters
[in] geometry
References RefinementProjector::set_geometry().
set_radius()
void set_radius (double radius) inline
Parameters
[in] radius
References CylinderCutProjector::set_radius().