Registry: Selector Class Reference
Selector Class Reference
Public Member Functions
void deselect (Vertex *unnamed)
bool is_selected (Vertex *unnamed) const
size_t num_edges () const
size_t num_faces () const
size_t num_hexahedrons () const
size_t num_prisms () const
size_t num_pyramids () const
size_t num_quadrilaterals () const
size_t num_tetrahedrons () const
size_t num_triangles () const
size_t num_vertices () const
size_t num_volumes () const
void select (Vertex *unnamed)
Selector (Grid *unnamed)
Constructor & Destructor Documentation
Selector()
Selector (Grid * unnamed)
Parameters
[in] unnamed
Member Function Documentation
deselect()
void deselect (Vertex * unnamed) inline inherited
Parameters
[in] unnamed
References ISelector::deselect().
is_selected()
bool is_selected (Vertex * unnamed) const inline inherited
Parameters
[in] unnamed
References ISelector::is_selected().
num_edges()
size_t num_edges () const inline
num_faces()
size_t num_faces () const inline
num_hexahedrons()
size_t num_hexahedrons () const inline
num_prisms()
size_t num_prisms () const inline
num_pyramids()
size_t num_pyramids () const inline
num_quadrilaterals()
size_t num_quadrilaterals () const inline
num_tetrahedrons()
size_t num_tetrahedrons () const inline
num_triangles()
size_t num_triangles () const inline
num_vertices()
size_t num_vertices () const inline
num_volumes()
size_t num_volumes () const inline
select()
void select (Vertex * unnamed) inline inherited
Parameters
[in] unnamed
References ISelector::select().