Registry: ILU_c Class Reference
ILU_c Class Reference
ILU preconditioner respecting constraints.
Public Member Functions
bool apply (Vector *unnamed, const Vector *unnamed)
bool apply_update_defect (Vector *unnamed, Vector *unnamed)
SmartPtr< ILinearIterator > clone ()
returns a clone of the object which can be modified independently
std::string config_string () const
string to display configuration of the linear iterator
ILU_c (SmartPtr< IDomainDiscretization > domain_discretization)
bool init (SmartPtr< ILinearOperator > unnamed)
const char * name () const
void set_beta (double beta)
void set_damp (double damp)
set the damping to a number
void set_disable_preprocessing (bool disable)
set whether preprocessing (notably, LU factorization) is to be disabled - usable when the operator has not changed; use with care
void set_inversion_eps (double eps)
void set_sort (bool bSort)
if bSort=true, use a cuthill-mckey sorting to reduce fill-in. default false
void set_sort_eps (double eps)
void set_time (double time)
Detailed Description
ILU preconditioner respecting constraints.
Note
default specialization is ILU_c2dCPU1
See also
ug::ILU_c
Constructor & Destructor Documentation
ILU_c()
ILU_c (SmartPtr< IDomainDiscretization > domain_discretization)
Parameters
[in] domain_discretization
Member Function Documentation
apply()
bool apply (Vector * unnamed, const Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply().
apply_update_defect()
bool apply_update_defect (Vector * unnamed, Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply_update_defect().
clone()
SmartPtr<ILinearIterator> clone () inline inherited
returns a clone of the object which can be modified independently
Returns
SmartPointer to a copy of this object
References ILinearIterator< X, Y >::clone().
config_string()
std::string config_string () const inline inherited
string to display configuration of the linear iterator
Returns
strConfiguration
References ILinearIterator< X, Y >::config_string().
init()
bool init (SmartPtr< ILinearOperator > unnamed) inline inherited
Parameters
[in] unnamed
References ILinearIterator< X, Y >::init().
name()
const char* name () const inline inherited
References ILinearIterator< X, Y >::name().
set_beta()
void set_beta (double beta) inline inherited
Parameters
[in] beta
References ILU< TAlgebra >::set_beta().
set_damp()
void set_damp (double damp) inline inherited
set the damping to a number
Parameters
[in] damp
References ILinearIterator< X, Y >::set_damp().
set_disable_preprocessing()
void set_disable_preprocessing (bool disable) inline inherited
set whether preprocessing (notably, LU factorization) is to be disabled - usable when the operator has not changed; use with care
Parameters
[in] disable
References ILU< TAlgebra >::set_disable_preprocessing().
set_inversion_eps()
void set_inversion_eps (double eps) inline inherited
Parameters
[in] eps
References ILU< TAlgebra >::set_inversion_eps().
set_sort()
void set_sort (bool bSort) inline inherited
if bSort=true, use a cuthill-mckey sorting to reduce fill-in. default false
Parameters
[in] bSort
References ILU< TAlgebra >::set_sort().
set_sort_eps()
void set_sort_eps (double eps) inline inherited
Parameters
[in] eps
References ILU< TAlgebra >::set_sort_eps().
set_time()
void set_time (double time) inline
Parameters
[in] time