Registry: CompositeConvCheck Class Reference
CompositeConvCheck Class Reference
Public Member Functions
double avg_rate (size_t function_index) const
returns the averaged convergence rate for a function
CompositeConvCheck (SmartPtr< ApproximationSpace > ApproximationSpace)
CompositeConvCheck (SmartPtr< ApproximationSpace > ApproximationSpace, int maxSteps, double minDefect, double relReduction)
double defect (size_t function_index) const
returns the current defect
void disable_rest_check ()
bool iteration_ended ()
double rate (size_t function_index) const
returns the current convergence rate for a function
double reduction (size_t function_index) const
returns the current relative reduction for a function
void set_adaptive (bool unnamed)
whether adaptive meshing is used or not
void set_all_component_check (double minDefect, double relReduction)
void set_component_check (std::string Components, std::vector< double > minDefect, std::vector< double > relReduction)
void set_group_check (std::vector< std::string > ComponentGroup, double minDefect, double relReduction)
void set_level (int grid_level)
sets grid level where defect vectors come from
void set_maximum_steps (int maximum_steps)
void set_rest_check (double minDefect, double relReduction)
void set_supress_unsuccessful (bool unnamed)
whether to always report success when iteration is finished
void set_time_measurement (bool unnamed)
whether to perform a time measurement or not
void set_verbose (bool verbosity)
int step () const
returns the current number of steps
Detailed Description
Note
default specialization is CompositeConvCheck2dCPU1
See also
ug::CompositeConvCheck
Constructor & Destructor Documentation
CompositeConvCheck() [1/2]
CompositeConvCheck (SmartPtr< ApproximationSpace > ApproximationSpace)
Parameters
[in] ApproximationSpace
CompositeConvCheck() [2/2]
CompositeConvCheck (SmartPtr< ApproximationSpace > ApproximationSpace, int maxSteps, double minDefect, double relReduction)
Parameters
[in] ApproximationSpace
[in] maxSteps
[in] minDefect
[in] relReduction
Member Function Documentation
avg_rate()
double avg_rate (size_t function_index) const inline
returns the averaged convergence rate for a function
Parameters
[in] function_index
Returns
avg_rate
References CompositeConvCheck< class, class >::avg_rate().
defect()
double defect (size_t function_index) const inline
returns the current defect
Parameters
[in] function_index
Returns
defect
References CompositeConvCheck< class, class >::defect().
disable_rest_check()
void disable_rest_check () inline
References CompositeConvCheck< class, class >::disable_rest_check().
iteration_ended()
bool iteration_ended () inline
References CompositeConvCheck< class, class >::iteration_ended().
rate()
double rate (size_t function_index) const inline
returns the current convergence rate for a function
Parameters
[in] function_index
Returns
rate
References CompositeConvCheck< class, class >::rate().
reduction()
double reduction (size_t function_index) const inline
returns the current relative reduction for a function
Parameters
[in] function_index
Returns
reduction
References CompositeConvCheck< class, class >::reduction().
set_adaptive()
void set_adaptive (bool unnamed) inline
whether adaptive meshing is used or not
Parameters
[in] unnamed
References CompositeConvCheck< class, class >::set_adaptive().
set_all_component_check()
void set_all_component_check (double minDefect, double relReduction) inline
Parameters
[in] minDefect
[in] relReduction
References CompositeConvCheck< class, class >::set_all_component_check().
set_component_check()
void set_component_check (std::string Components, std::vector< double > minDefect, std::vector< double > relReduction) inline
Parameters
[in] Components
[in] minDefect
[in] relReduction
References CompositeConvCheck< class, class >::set_component_check().
set_group_check()
void set_group_check (std::vector< std::string > ComponentGroup, double minDefect, double relReduction) inline
Parameters
[in] ComponentGroup
[in] minDefect
[in] relReduction
References CompositeConvCheck< class, class >::set_group_check().
set_level()
void set_level (int grid_level) inline
sets grid level where defect vectors come from
Parameters
[in] grid_level
References CompositeConvCheck< class, class >::set_level().
set_maximum_steps()
void set_maximum_steps (int maximum_steps) inline
Parameters
[in] maximum_steps
References CompositeConvCheck< class, class >::set_maximum_steps().
set_rest_check()
void set_rest_check (double minDefect, double relReduction) inline
Parameters
[in] minDefect
[in] relReduction
References CompositeConvCheck< class, class >::set_rest_check().
set_supress_unsuccessful()
void set_supress_unsuccessful (bool unnamed) inline
whether to always report success when iteration is finished
Parameters
[in] unnamed
References CompositeConvCheck< class, class >::set_supress_unsuccessful().
set_time_measurement()
void set_time_measurement (bool unnamed) inline
whether to perform a time measurement or not
Parameters
[in] unnamed
References CompositeConvCheck< class, class >::set_time_measurement().
set_verbose()
void set_verbose (bool verbosity) inline
Parameters
[in] verbosity
References CompositeConvCheck< class, class >::set_verbose().
step()
int step () const inline
returns the current number of steps
Returns
step
References CompositeConvCheck< class, class >::step().