Registry: ConstUserNumber Class Reference
ConstUserNumber Class Reference
Public Member Functions
ConstUserNumber ()
ConstUserNumber (double Value)
double get () const
int get_dim () const
void print () const
void set (double Value)
std::string type () const
Detailed Description
Note
default specialization is ConstUserNumber2d
See also
ug::ConstUserNumber
Constructor & Destructor Documentation
ConstUserNumber() [1/2]
ConstUserNumber ()
ConstUserNumber() [2/2]
ConstUserNumber (double Value)
Parameters
[in] Value
Member Function Documentation
get()
double get () const inline
References ConstUserNumber< dim >::get().
get_dim()
int get_dim () const inline inherited
References get_dim().
print()
void print () const inline
References ConstUserNumber< dim >::print().
set()
void set (double Value) inline
Parameters
[in] Value
References ConstUserNumber< dim >::set().
type()
std::string type () const inline inherited
References type().