Registry: UGProfileNode Class Reference
UGProfileNode Class Reference
Public Member Functions
std::string call_tree () const
std::string child_self_memory_sorted () const
childs are sorted by self memory
std::string child_self_time_sorted () const
childs are sorted by self time
std::string entry_count_sorted () const
childs are sorted by entry count
double get_avg_entry_count () const
double get_avg_self_time_ms () const
double get_avg_total_time_ms () const
std::string groups () const
bool is_valid () const
std::string total_memory_sorted () const
childs are sorted by total memory
std::string total_time_sorted () const
childs are sorted by total time
Private Member Functions
UGProfileNode ()=delete
Constructor hidden / deactivated.
Constructor & Destructor Documentation
UGProfileNode()
UGProfileNode () private delete
Constructor hidden / deactivated.
Member Function Documentation
call_tree()
std::string call_tree () const inline
Returns
string with call tree
References UGProfileNode::call_tree().
child_self_memory_sorted()
std::string child_self_memory_sorted () const inline
childs are sorted by self memory
Returns
string with sorted childs
References UGProfileNode::child_self_memory_sorted().
child_self_time_sorted()
std::string child_self_time_sorted () const inline
childs are sorted by self time
Returns
string with sorted childs
References UGProfileNode::child_self_time_sorted().
entry_count_sorted()
std::string entry_count_sorted () const inline
childs are sorted by entry count
Returns
string with sorted childs
References UGProfileNode::entry_count_sorted().
get_avg_entry_count()
double get_avg_entry_count () const inline
Returns
number of entries in this profiler node
References UGProfileNode::get_avg_entry_count().
get_avg_self_time_ms()
double get_avg_self_time_ms () const inline
Returns
time in milliseconds spend in this node excluding subnodes
References UGProfileNode::get_avg_self_time_ms().
get_avg_total_time_ms()
double get_avg_total_time_ms () const inline
Returns
time in milliseconds spend in this node including subnodes
References UGProfileNode::get_avg_total_time_ms().
groups()
std::string groups () const inline
References UGProfileNode::groups().
is_valid()
bool is_valid () const inline
Returns
true if node has been found
total_memory_sorted()
std::string total_memory_sorted () const inline
childs are sorted by total memory
Returns
string with sorted childs
References UGProfileNode::total_memory_sorted().
total_time_sorted()
std::string total_time_sorted () const inline
childs are sorted by total time
Returns
string with sorted childs
References UGProfileNode::total_time_sorted().