Registry: IPartitioner Class Reference
IPartitioner Class Reference
Public Member Functions
bool clustered_siblings_enabled ()
void enable_clustered_siblings (bool unnamed)
bool partition (size_t unnamed, size_t unnamed)
void set_balance_weights (SmartPtr< IBalanceWeights > unnamed)
void set_communication_weights (SmartPtr< ICommunicationWeights > unnamed)
void set_next_process_hierarchy (SmartPtr< ProcessHierarchy > unnamed)
void set_partition_post_processor (SmartPtr< IPartitionPostProcessor > unnamed)
void set_partition_pre_processor (SmartPtr< IPartitionPreProcessor > unnamed)
void set_verbose (bool unnamed)
bool supports_balance_weights () const
bool supports_communication_weights () const
Private Member Functions
IPartitioner ()=delete
Constructor hidden / deactivated.
Constructor & Destructor Documentation
IPartitioner()
IPartitioner () private delete
Constructor hidden / deactivated.
Member Function Documentation
clustered_siblings_enabled()
bool clustered_siblings_enabled () inline
References IPartitioner::clustered_siblings_enabled().
enable_clustered_siblings()
void enable_clustered_siblings (bool unnamed) inline
Parameters
[in] unnamed
References IPartitioner::enable_clustered_siblings().
partition()
bool partition (size_t unnamed, size_t unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References IPartitioner::partition().
set_balance_weights()
void set_balance_weights (SmartPtr< IBalanceWeights > unnamed) inline
Parameters
[in] unnamed
References IPartitioner::set_balance_weights().
set_communication_weights()
void set_communication_weights (SmartPtr< ICommunicationWeights > unnamed) inline
Parameters
[in] unnamed
References IPartitioner::set_communication_weights().
set_next_process_hierarchy()
void set_next_process_hierarchy (SmartPtr< ProcessHierarchy > unnamed) inline
Parameters
[in] unnamed
References IPartitioner::set_next_process_hierarchy().
set_partition_post_processor()
void set_partition_post_processor (SmartPtr< IPartitionPostProcessor > unnamed) inline
Parameters
[in] unnamed
References IPartitioner::set_partition_post_processor().
set_partition_pre_processor()
void set_partition_pre_processor (SmartPtr< IPartitionPreProcessor > unnamed) inline
Parameters
[in] unnamed
References IPartitioner::set_partition_pre_processor().
set_verbose()
void set_verbose (bool unnamed) inline
Parameters
[in] unnamed
References IPartitioner::set_verbose().
supports_balance_weights()
bool supports_balance_weights () const inline
References IPartitioner::supports_balance_weights().
supports_communication_weights()
bool supports_communication_weights () const inline
References IPartitioner::supports_communication_weights().