Registry: NeumannBoundaryFV Class Reference
NeumannBoundaryFV Class Reference
Public Member Functions
void add (SmartPtr< CplUserNumber > unnamed, const char *unnamed, const char *unnamed)
void add_elem_modifier (SmartPtr< IElemDiscModifier > unnamed)
NeumannBoundaryFV (const char *Function)
void set_error_estimator (SmartPtr< ErrEstData > unnamed)
void set_stationary ()
Detailed Description
Note
default specialization is NeumannBoundaryFV2d
See also
ug::NeumannBoundaryFV
Constructor & Destructor Documentation
NeumannBoundaryFV()
NeumannBoundaryFV (const char * Function)
Parameters
[in] Function
Member Function Documentation
add()
void add (SmartPtr< CplUserNumber > unnamed, const char * unnamed, const char * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References NeumannBoundaryBase< class >::add().
add_elem_modifier()
void add_elem_modifier (SmartPtr< IElemDiscModifier > unnamed) inline inherited
Parameters
[in] unnamed
References IElemDisc< TDomain >::add_elem_modifier().
set_error_estimator()
void set_error_estimator (SmartPtr< ErrEstData > unnamed) inline inherited
Parameters
[in] unnamed
References IElemEstimatorFuncs< IElemDisc< TDomain >, TDomain >::set_error_estimator().
set_stationary()
void set_stationary () inline inherited
References IElemDiscBase< class >::set_stationary().