Registry: DebugWriterContext Class Reference
DebugWriterContext Class Reference
Public Member Functions
void compose_file_path ()
DebugWriterContext ()
void enter_section (const char *unnamed)
std::string get_base_dir ()
void leave_section ()
void print_message ()
void set_base_dir (const char *unnamed)
Constructor & Destructor Documentation
DebugWriterContext()
DebugWriterContext ()
Member Function Documentation
compose_file_path()
void compose_file_path () inline
References DebugWriterContext::compose_file_path().
enter_section()
void enter_section (const char * unnamed) inline
Parameters
[in] unnamed
References DebugWriterContext::enter_section().
get_base_dir()
std::string get_base_dir () inline
References DebugWriterContext::get_base_dir().
leave_section()
void leave_section () inline
References DebugWriterContext::leave_section().
print_message()
void print_message () inline
References DebugWriterContext::print_message().
set_base_dir()
void set_base_dir (const char * unnamed) inline
Parameters
[in] unnamed
References DebugWriterContext::set_base_dir().