Registry: H1SemiComponentSpace Class Reference
H1SemiComponentSpace Class Reference
Public Member Functions
std::string config_string () const
double distance (GridFunction *unnamed, GridFunction *unnamed)
ConstSmartPtr< UserMatrix > get_weight ()
H1SemiComponentSpace (const char *fctNames)
H1SemiComponentSpace (const char *fctNames, _order, _weight, _ssNames, int unnamed, const char *unnamed, ConstSmartPtr< UserMatrix > unnamed)
H1SemiComponentSpace (const char *fctNames, _order, _weight, _ssNames, int unnamed, double unnamed, const char *unnamed)
H1SemiComponentSpace (const char *fctNames, _order, _weight, int unnamed, ConstSmartPtr< UserMatrix > unnamed)
H1SemiComponentSpace (const char *fctNames, _order, _weight, int unnamed, double unnamed)
H1SemiComponentSpace (const char *fctNames, _order, int unnamed)
double norm (GridFunction *unnamed)
void set_weight (ConstSmartPtr< UserMatrix > unnamed)
Detailed Description
Note
default specialization is H1SemiComponentSpace2dCPU1
See also
ug::H1SemiComponentSpace
Constructor & Destructor Documentation
H1SemiComponentSpace() [1/6]
H1SemiComponentSpace (const char * fctNames)
Parameters
[in] fctNames
H1SemiComponentSpace() [2/6]
H1SemiComponentSpace (const char * fctNames, _order , int unnamed)
Parameters
[in] fctNames,_order
[in] unnamed
H1SemiComponentSpace() [3/6]
H1SemiComponentSpace (const char * fctNames, _order , _weight , int unnamed, double unnamed)
Parameters
[in] fctNames,_order,_weight
[in] unnamed
[in] unnamed
H1SemiComponentSpace() [4/6]
H1SemiComponentSpace (const char * fctNames, _order , _weight , _ssNames , int unnamed, double unnamed, const char * unnamed)
Parameters
[in] fctNames,_order,_weight,_ssNames
[in] unnamed
[in] unnamed
[in] unnamed
H1SemiComponentSpace() [5/6]
H1SemiComponentSpace (const char * fctNames, _order , _weight , int unnamed, ConstSmartPtr< UserMatrix > unnamed)
Parameters
[in] fctNames,_order,_weight
[in] unnamed
[in] unnamed
H1SemiComponentSpace() [6/6]
H1SemiComponentSpace (const char * fctNames, _order , _weight , _ssNames , int unnamed, const char * unnamed, ConstSmartPtr< UserMatrix > unnamed)
Parameters
[in] fctNames,_order,_weight,_ssNames
[in] unnamed
[in] unnamed
[in] unnamed
Member Function Documentation
config_string()
std::string config_string () const inline inherited
References IGridFunctionSpace< TGridFunction >::config_string().
distance()
double distance (GridFunction * unnamed, GridFunction * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References IComponentSpace< class >::distance().
get_weight()
ConstSmartPtr<UserMatrix> get_weight () inline
References H1SemiComponentSpace< class >::get_weight().
norm()
double norm (GridFunction * unnamed) inline
Parameters
[in] unnamed
References IComponentSpace< class >::norm().
set_weight()
void set_weight (ConstSmartPtr< UserMatrix > unnamed) inline
Parameters
[in] unnamed
References H1SemiComponentSpace< class >::set_weight().