Registry: GridFunction Class Reference
GridFunction Class Reference
Public Types
typedef TValueType value_type
typedef Vector< TValueType > vector_type
Public Member Functions
bool add (const V &u)
void assign (const Vector *Vector)
SmartPtr< GridFunction > clone () const
void defragment ()
double dotprod (const Vector &w)
void enable_redistribution (bool unnamed)
bool get (V &u) const
const GridLevel * grid_level () const
GridFunction (SmartPtr< ApproximationSpace > ApproximationSpace)
GridFunction (SmartPtr< ApproximationSpace > ApproximationSpace, int Level)
double norm () const
size_t num_dofs () const
bool operator*= (const number &a)
void operator+= (const Vector &v)
void operator-= (const Vector &v)
value_type & operator[] (size_t i)
const value_type & operator[] (size_t i) const
bool redistribution_enabled () const
bool resize (size_t new_length, bool bCopyValues=true)
bool set (const V &u)
bool set (double d)
bool set_random (double from, double to)
size_t size ()
Detailed Description
Note
default specialization is GridFunction2dCPU1
See also
ug::GridFunction
Constructor & Destructor Documentation
GridFunction() [1/2]
GridFunction (SmartPtr< ApproximationSpace > ApproximationSpace)
Parameters
[in] ApproximationSpace
GridFunction() [2/2]
GridFunction (SmartPtr< ApproximationSpace > ApproximationSpace, int Level)
Parameters
[in] ApproximationSpace
[in] Level
Member Function Documentation
assign()
void assign (const Vector * Vector) inline
Parameters
[in] Vector
References GridFunction< TDomain, TAlgebra >::assign().
clone()
SmartPtr<GridFunction> clone () const inline
References GridFunction< TDomain, TAlgebra >::clone().
enable_redistribution()
void enable_redistribution (bool unnamed) inline
Parameters
[in] unnamed
References GridFunction< TDomain, TAlgebra >::enable_redistribution().
grid_level()
const GridLevel* grid_level () const inline
References GridFunction< TDomain, TAlgebra >::grid_level().
num_dofs()
size_t num_dofs () const inline
References GridFunction< TDomain, TAlgebra >::num_dofs().
redistribution_enabled()
bool redistribution_enabled () const inline
References GridFunction< TDomain, TAlgebra >::redistribution_enabled().