Registry: LU Class Reference
LU Class Reference
LU-Decomposition exact solver.
Public Member Functions
bool apply (Vector *u, const Vector *f)
Solve A*u = f, such that u = A^{-1} f by iterating u := u + B(f - A*u), f remains constant.
bool apply_return_defect (Vector *u, Vector *f)
Solve A*u = f, such that u = A^{-1} f by iterating u := u + B(f - A*u), f := f - A*u becomes new defect.
bool apply_update_defect (Vector *unnamed, Vector *unnamed)
SmartPtr< ILinearIterator > clone ()
returns a clone of the object which can be modified independently
std::string config_string () const
ConstSmartPtr< IConvergenceCheck > convergence_check () const
double defect () const
bool init (SmartPtr< ILinearOperator > unnamed)
LU ()
const char * name () const
double reduction () const
void set_convergence_check (SmartPtr< IConvergenceCheck > unnamed)
void set_damp (double damp)
set the damping to a number
void set_info (bool bInfo)
if true, sparse LU prints some fill-in info
void set_minimum_for_sparse (size_t N)
void set_sort_sparse (bool bSort)
if bSort=true, use a cuthill-mckey sorting to reduce fill-in in sparse LU. default true
int step () const
Detailed Description
LU-Decomposition exact solver.
Note
default specialization is LUCPU1
See also
ug::LU
Constructor & Destructor Documentation
LU()
LU ()
Member Function Documentation
apply()
bool apply (Vector * u, const Vector * f) inline inherited
Solve A*u = f, such that u = A^{-1} f by iterating u := u + B(f - A*u), f remains constant.
Parameters
[in] u
[in] f
Returns
Success
References ILinearOperatorInverse< X, Y >::apply().
apply_return_defect()
bool apply_return_defect (Vector * u, Vector * f) inline inherited
Solve A*u = f, such that u = A^{-1} f by iterating u := u + B(f - A*u), f := f - A*u becomes new defect.
Parameters
[in] u
[in] f
Returns
Success
References ILinearOperatorInverse< X, Y >::apply_return_defect().
apply_update_defect()
bool apply_update_defect (Vector * unnamed, Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply_update_defect().
clone()
SmartPtr<ILinearIterator> clone () inline inherited
returns a clone of the object which can be modified independently
Returns
SmartPointer to a copy of this object
References ILinearIterator< X, Y >::clone().
config_string()
std::string config_string () const inline inherited
References ILinearOperatorInverse< X, Y >::config_string().
convergence_check()
ConstSmartPtr<IConvergenceCheck> convergence_check () const inline inherited
References ILinearOperatorInverse< X, Y >::convergence_check().
defect()
double defect () const inline inherited
Returns
the current defect
References ILinearOperatorInverse< X, Y >::defect().
init()
bool init (SmartPtr< ILinearOperator > unnamed) inline inherited
Parameters
[in] unnamed
References ILinearOperatorInverse< X, Y >::init().
name()
const char* name () const inline inherited
References ILinearIterator< X, Y >::name().
reduction()
double reduction () const inline inherited
Returns
the current relative reduction
References ILinearOperatorInverse< X, Y >::reduction().
set_convergence_check()
void set_convergence_check (SmartPtr< IConvergenceCheck > unnamed) inline inherited
Parameters
[in] unnamed
References ILinearOperatorInverse< X, Y >::set_convergence_check().
set_damp()
void set_damp (double damp) inline inherited
set the damping to a number
Parameters
[in] damp
References ILinearIterator< X, Y >::set_damp().
set_info()
void set_info (bool bInfo) inline
if true, sparse LU prints some fill-in info
Parameters
[in] bInfo
References LU< class >::set_info().
set_minimum_for_sparse()
void set_minimum_for_sparse (size_t N) inline
Parameters
[in] N
References LU< class >::set_minimum_for_sparse().
set_sort_sparse()
void set_sort_sparse (bool bSort) inline
if bSort=true, use a cuthill-mckey sorting to reduce fill-in in sparse LU. default true
Parameters
[in] bSort
References LU< class >::set_sort_sparse().
step()
int step () const inline inherited
Returns
the current number of steps
References ILinearOperatorInverse< X, Y >::step().