Registry: ILinearIterator Class Reference
ILinearIterator Class Reference
Public Member Functions
bool apply (Vector *unnamed, const Vector *unnamed)
bool apply_update_defect (Vector *unnamed, Vector *unnamed)
SmartPtr< ILinearIterator > clone ()
returns a clone of the object which can be modified independently
std::string config_string () const
string to display configuration of the linear iterator
bool init (SmartPtr< ILinearOperator > unnamed)
const char * name () const
void set_damp (double damp)
set the damping to a number
Private Member Functions
ILinearIterator ()=delete
Constructor hidden / deactivated.
Detailed Description
Note
default specialization is ILinearIteratorCPU1
See also
ug::ILinearIterator
Constructor & Destructor Documentation
ILinearIterator()
ILinearIterator () private delete
Constructor hidden / deactivated.
Member Function Documentation
apply()
bool apply (Vector * unnamed, const Vector * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply().
apply_update_defect()
bool apply_update_defect (Vector * unnamed, Vector * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply_update_defect().
clone()
SmartPtr<ILinearIterator> clone () inline
returns a clone of the object which can be modified independently
Returns
SmartPointer to a copy of this object
References ILinearIterator< X, Y >::clone().
config_string()
std::string config_string () const inline
string to display configuration of the linear iterator
Returns
strConfiguration
References ILinearIterator< X, Y >::config_string().
init()
bool init (SmartPtr< ILinearOperator > unnamed) inline
Parameters
[in] unnamed
References ILinearIterator< X, Y >::init().
name()
const char* name () const inline
References ILinearIterator< X, Y >::name().
set_damp()
void set_damp (double damp) inline
set the damping to a number
Parameters
[in] damp
References ILinearIterator< X, Y >::set_damp().