Registry: NLGaussSeidelSolver Class Reference
NLGaussSeidelSolver Class Reference
Public Member Functions
bool apply (Vector *u)
std::string config_string () const
bool init (SmartPtr< IOperator > op)
NLGaussSeidelSolver ()
NLGaussSeidelSolver (SmartPtr< ApproximationSpace > ApproxSpaceConvCheck, SmartPtr< IConvergenceCheck > unnamed)
bool prepare (Vector *u)
void set_approximation_space (SmartPtr< ApproximationSpace > approxSpace)
void set_constraint (const Vector *setConstraint)
void set_convergence_check (SmartPtr< IConvergenceCheck > convCheck)
void set_damp (double setDampingFactor)
Detailed Description
Note
default specialization is NLGaussSeidelSolver2dCPU1
See also
ug::NLGaussSeidelSolver
Constructor & Destructor Documentation
NLGaussSeidelSolver() [1/2]
NLGaussSeidelSolver ()
NLGaussSeidelSolver() [2/2]
NLGaussSeidelSolver (SmartPtr< ApproximationSpace > ApproxSpaceConvCheck, SmartPtr< IConvergenceCheck > unnamed)
Parameters
[in] ApproxSpaceConvCheck
[in] unnamed
Member Function Documentation
apply()
bool apply (Vector * u) inline
Parameters
[in] u
Returns
success
References NLGaussSeidelSolver< class, class >::apply().
config_string()
std::string config_string () const inline
References NLGaussSeidelSolver< class, class >::config_string().
init()
bool init (SmartPtr< IOperator > op) inline
Parameters
[in] op
Returns
success
References NLGaussSeidelSolver< class, class >::init().
prepare()
bool prepare (Vector * u) inline
Parameters
[in] u
Returns
success
References NLGaussSeidelSolver< class, class >::prepare().
set_approximation_space()
void set_approximation_space (SmartPtr< ApproximationSpace > approxSpace) inline
Parameters
[in] approxSpace
References NLGaussSeidelSolver< class, class >::set_approximation_space().
set_constraint()
void set_constraint (const Vector * setConstraint) inline
Parameters
[in] setConstraint
References NLGaussSeidelSolver< class, class >::set_constraint().
set_convergence_check()
void set_convergence_check (SmartPtr< IConvergenceCheck > convCheck) inline
Parameters
[in] convCheck
References NLGaussSeidelSolver< class, class >::set_convergence_check().
set_damp()
void set_damp (double setDampingFactor) inline
Parameters
[in] setDampingFactor
References NLGaussSeidelSolver< class, class >::set_damp().