Registry: ProcessHierarchy Class Reference
ProcessHierarchy Class Reference
Public Member Functions
void add_hierarchy_level (size_t unnamed, size_t unnamed)
void add_partition_hint (int unnamed, std::string unnamed, const Variant *unnamed)
std::vector< int > cluster_procs (size_t unnamed) const
bool empty () const
size_t grid_base_level (size_t unnamed) const
size_t hierarchy_level_from_grid_level (size_t unnamed) const
size_t num_global_procs_involved (size_t unnamed) const
size_t num_hierarchy_levels () const
bool partition_hint (Variant *unnamed, int unnamed, std::string unnamed) const
ProcessHierarchy ()
std::string to_string () const
Constructor & Destructor Documentation
ProcessHierarchy()
ProcessHierarchy ()
Member Function Documentation
add_hierarchy_level()
void add_hierarchy_level (size_t unnamed, size_t unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References ProcessHierarchy::add_hierarchy_level().
add_partition_hint()
void add_partition_hint (int unnamed, std::string unnamed, const Variant * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References ProcessHierarchy::add_partition_hint().
cluster_procs()
std::vector< int > cluster_procs (size_t unnamed) const inline
Parameters
[in] unnamed
References ProcessHierarchy::cluster_procs().
empty()
bool empty () const inline
References ProcessHierarchy::empty().
grid_base_level()
size_t grid_base_level (size_t unnamed) const inline
Parameters
[in] unnamed
References ProcessHierarchy::grid_base_level().
hierarchy_level_from_grid_level()
size_t hierarchy_level_from_grid_level (size_t unnamed) const inline
Parameters
[in] unnamed
References ProcessHierarchy::hierarchy_level_from_grid_level().
num_global_procs_involved()
size_t num_global_procs_involved (size_t unnamed) const inline
Parameters
[in] unnamed
References ProcessHierarchy::num_global_procs_involved().
num_hierarchy_levels()
size_t num_hierarchy_levels () const inline
References ProcessHierarchy::num_hierarchy_levels().
partition_hint()
bool partition_hint (Variant * unnamed, int unnamed, std::string unnamed) const inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References ProcessHierarchy::partition_hint().
to_string()
std::string to_string () const inline
References ProcessHierarchy::to_string().