Registry: DebugWritingObject Class Reference
DebugWritingObject Class Reference
Public Member Functions
SmartPtr< IDebugWriter > debug_writer ()
ConstSmartPtr< IDebugWriter > debug_writer () const
void set_debug (SmartPtr< IDebugWriter > dbgWriter)
sets a debug writer
void set_debug (SmartPtr< IVectorDebugWriter > dbgWriter)
sets a debug writer
SmartPtr< IVectorDebugWriter > vector_debug_writer ()
ConstSmartPtr< IVectorDebugWriter > vector_debug_writer () const
Private Member Functions
DebugWritingObject ()=delete
Constructor hidden / deactivated.
Detailed Description
Note
default specialization is DebugWritingObjectCPU1
See also
ug::DebugWritingObject
Constructor & Destructor Documentation
DebugWritingObject()
DebugWritingObject () private delete
Constructor hidden / deactivated.
Member Function Documentation
debug_writer() [1/2]
SmartPtr<IDebugWriter> debug_writer () inline
References DebugWritingObject< TAlgebra >::debug_writer().
debug_writer() [2/2]
ConstSmartPtr<IDebugWriter> debug_writer () const inline
References DebugWritingObject< TAlgebra >::debug_writer().
set_debug() [1/2]
void set_debug (SmartPtr< IDebugWriter > dbgWriter) inline
sets a debug writer
Parameters
[in] dbgWriter
References DebugWritingObject< TAlgebra >::set_debug().
set_debug() [2/2]
void set_debug (SmartPtr< IVectorDebugWriter > dbgWriter) inline inherited
sets a debug writer
Parameters
[in] dbgWriter
References VectorDebugWritingObject< TVector >::set_debug().
vector_debug_writer() [1/2]
SmartPtr<IVectorDebugWriter> vector_debug_writer () inline inherited
References VectorDebugWritingObject< TVector >::vector_debug_writer().
vector_debug_writer() [2/2]
ConstSmartPtr<IVectorDebugWriter> vector_debug_writer () const inline inherited
References VectorDebugWritingObject< TVector >::vector_debug_writer().