Registry: StringTable Class Reference
StringTable Class Reference
Public Member Functions
std::string __tostring () const
void add_cols (size_t unnamed)
void add_rows (size_t unnamed)
std::string get (size_t unnamed, size_t unnamed) const
size_t num_cols () const
size_t num_rows () const
void set (size_t unnamed, size_t unnamed, std::string unnamed)
void set_col_alignment (size_t unnamed, const char *unnamed)
void set_col_alignments (std::string unnamed)
void set_col_seperator (size_t unnamed, const char *unnamed)
void set_col_seperators (std::string unnamed)
void set_default_col_alignment (const char *unnamed)
void set_default_col_seperator (const char *unnamed)
void set_default_row_seperator (const char *unnamed)
void set_row_seperator (size_t unnamed, const char *unnamed)
void set_row_seperators (std::string unnamed)
StringTable ()
StringTable (size_t unnamed, size_t unnamed)
std::string to_csv (const char *unnamed) const
std::string to_latex () const
void transpose ()
Constructor & Destructor Documentation
StringTable() [1/2]
StringTable ()
StringTable() [2/2]
StringTable (size_t unnamed, size_t unnamed)
Parameters
[in] unnamed
[in] unnamed
Member Function Documentation
__tostring()
std::string __tostring () const inline
add_cols()
void add_cols (size_t unnamed) inline
Parameters
[in] unnamed
References Table< std::string >::add_cols().
add_rows()
void add_rows (size_t unnamed) inline
Parameters
[in] unnamed
References Table< std::string >::add_rows().
get()
std::string get (size_t unnamed, size_t unnamed) const inline
Parameters
[in] unnamed
[in] unnamed
References Table< std::string >::get().
num_cols()
size_t num_cols () const inline
References Table< std::string >::num_cols().
num_rows()
size_t num_rows () const inline
References Table< std::string >::num_rows().
set()
void set (size_t unnamed, size_t unnamed, std::string unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References Table< std::string >::set().
set_col_alignment()
void set_col_alignment (size_t unnamed, const char * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References Table< std::string >::set_col_alignment().
set_col_alignments()
void set_col_alignments (std::string unnamed) inline
Parameters
[in] unnamed
References Table< std::string >::set_col_alignments().
set_col_seperator()
void set_col_seperator (size_t unnamed, const char * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References Table< std::string >::set_col_seperator().
set_col_seperators()
void set_col_seperators (std::string unnamed) inline
Parameters
[in] unnamed
References Table< std::string >::set_col_seperators().
set_default_col_alignment()
void set_default_col_alignment (const char * unnamed) inline
Parameters
[in] unnamed
References Table< std::string >::set_default_col_alignment().
set_default_col_seperator()
void set_default_col_seperator (const char * unnamed) inline
Parameters
[in] unnamed
References Table< std::string >::set_default_col_seperator().
set_default_row_seperator()
void set_default_row_seperator (const char * unnamed) inline
Parameters
[in] unnamed
References Table< std::string >::set_default_row_seperator().
set_row_seperator()
void set_row_seperator (size_t unnamed, const char * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References Table< std::string >::set_row_seperator().
set_row_seperators()
void set_row_seperators (std::string unnamed) inline
Parameters
[in] unnamed
References Table< std::string >::set_row_seperators().
to_csv()
std::string to_csv (const char * unnamed) const inline
Parameters
[in] unnamed
References Table< std::string >::to_csv().
to_latex()
std::string to_latex () const inline
References Table< std::string >::to_latex().
transpose()
void transpose () inline
References Table< std::string >::transpose().