Registry: PartitionMap Class Reference
PartitionMap Class Reference
Public Member Functions
void add_target_proc (int unnamed)
void add_target_procs (int unnamed, int unnamed)
void clear ()
SmartPtr< SubsetHandler > get_partition_handler ()
int get_target_proc (size_t unnamed)
size_t num_target_procs ()
PartitionMap ()
void shift_target_procs (int unnamed)
Constructor & Destructor Documentation
PartitionMap ()
Member Function Documentation
void add_target_proc (int unnamed) inline
Parameters
[in] unnamed
References PartitionMap::add_target_proc().
void add_target_procs (int unnamed, int unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References PartitionMap::add_target_procs().
void clear () inline
References PartitionMap::clear().
SmartPtr<SubsetHandler> get_partition_handler () inline
References PartitionMap::get_partition_handler().
int get_target_proc (size_t unnamed) inline
Parameters
[in] unnamed
References PartitionMap::get_target_proc().
size_t num_target_procs () inline
References PartitionMap::num_target_procs().
void shift_target_procs (int unnamed) inline
Parameters
[in] unnamed
References PartitionMap::shift_target_procs().