Registry: DegeneratedLayerManager Class Reference
DegeneratedLayerManager Class Reference
Public Member Functions
void add (const char *subset(s))
int assign_middle_subset (int subset_index_of_the_layer, int subset_index_for_the_middle_manifold)
void close ()
bool contains (int subset(s))
DegeneratedLayerManager (SmartPtr< MGSubsetHandler > MultiGridSubsetHandler)
void init_refiner (SmartPtr< GlobalFracturedMediumRefiner > refiner, bool as_low_dim)
size_t num_subsets ()
void remove (const char *subset(s))
int subset (size_t index_in_the_manager)
Detailed Description
Note
default specialization is DegeneratedLayerManager2d
See also
ug::DegeneratedLayerManager
Constructor & Destructor Documentation
DegeneratedLayerManager()
DegeneratedLayerManager (SmartPtr< MGSubsetHandler > MultiGridSubsetHandler)
Parameters
[in] MultiGridSubsetHandler
Member Function Documentation
add()
void add (const char * subsets) inline
Parameters
[in] subset(s)
References DegeneratedLayerManager< dim >::add(), s, and DegeneratedLayerManager::subset().
assign_middle_subset()
int assign_middle_subset (int subset_index_of_the_layer, int subset_index_for_the_middle_manifold) inline
Parameters
[in] subset_index_of_the_layer
[in] subset_index_for_the_middle_manifold
Returns
Assigns the subset index to the middle manifold
References DegeneratedLayerManager< dim >::assign_middle_subset().
close()
void close () inline
References DegeneratedLayerManager< dim >::close().
contains()
bool contains (int subsets) inline
Parameters
[in] subset(s)
Returns
Is subset registered in the manager
References DegeneratedLayerManager< dim >::contains(), s, and DegeneratedLayerManager::subset().
init_refiner()
void init_refiner (SmartPtr< GlobalFracturedMediumRefiner > refiner, bool as_low_dim) inline
Parameters
[in] refiner
[in] as_low_dim
References DegeneratedLayerManager< dim >::init_refiner().
num_subsets()
size_t num_subsets () inline
Returns
Number of subsets in the manager
References DegeneratedLayerManager< dim >::num_subsets().
remove()
void remove (const char * subsets) inline
Parameters
[in] subset(s)
References DegeneratedLayerManager< dim >::remove(), s, and DegeneratedLayerManager::subset().
subset()
int subset (size_t index_in_the_manager) inline
Parameters
[in] index_in_the_manager
Returns
Subset index for a given index in the manager
References DegeneratedLayerManager< dim >::subset().
Referenced by DegeneratedLayerManager::add(), DegeneratedLayerManager::contains(), and DegeneratedLayerManager::remove().