Registry: PlaneCutProjector Class Reference
PlaneCutProjector Class Reference
Public Member Functions
SmartPtr< IGeometry > geometry () const
const Vec3d * normal () const
PlaneCutProjector ()
PlaneCutProjector (const Vec3d *unnamed, const Vec3d *unnamed)
PlaneCutProjector (SmartPtr< IGeometry > unnamed, const Vec3d *unnamed, const Vec3d *unnamed)
const Vec3d * position () const
void set_geometry (SmartPtr< IGeometry > geometry)
void set_normal (const Vec3d *normal)
void set_position (const Vec3d *position)
Constructor & Destructor Documentation
PlaneCutProjector() [1/3]
PlaneCutProjector ()
PlaneCutProjector() [2/3]
PlaneCutProjector (const Vec3d * unnamed, const Vec3d * unnamed)
Parameters
[in] unnamed
[in] unnamed
PlaneCutProjector() [3/3]
PlaneCutProjector (SmartPtr< IGeometry > unnamed, const Vec3d * unnamed, const Vec3d * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
Member Function Documentation
geometry()
SmartPtr<IGeometry> geometry () const inline inherited
Returns
geometry
References RefinementProjector::geometry().
normal()
const Vec3d* normal () const inline
Returns
normal
References PlaneCutProjector::normal().
position()
const Vec3d* position () const inline
Returns
position
References PlaneCutProjector::position().
set_geometry()
void set_geometry (SmartPtr< IGeometry > geometry) inline inherited
Parameters
[in] geometry
References RefinementProjector::set_geometry().
set_normal()
void set_normal (const Vec3d * normal) inline
Parameters
[in] normal
References PlaneCutProjector::set_normal().
set_position()
void set_position (const Vec3d * position) inline
Parameters
[in] position
References PlaneCutProjector::set_position().