Registry: StdTransfer Class Reference
StdTransfer Class Reference
Public Member Functions
void add_constraint (SmartPtr< IConstraint > unnamed)
void enable_p1_lagrange_optimization (bool unnamed)
bool p1_lagrange_optimization_enabled () const
void set_debug (SmartPtr< IDebugWriter > unnamed)
void set_prolongation_damping (double unnamed)
void set_restriction_damping (double unnamed)
void set_use_transposed (bool unnamed)
StdTransfer ()
Detailed Description
Note
default specialization is StdTransfer2dCPU1
See also
ug::StdTransfer
Constructor & Destructor Documentation
StdTransfer()
StdTransfer ()
Member Function Documentation
add_constraint()
void add_constraint (SmartPtr< IConstraint > unnamed) inline
Parameters
[in] unnamed
References ITransferOperator< class, class >::add_constraint().
enable_p1_lagrange_optimization()
void enable_p1_lagrange_optimization (bool unnamed) inline
Parameters
[in] unnamed
References StdTransfer< class, class >::enable_p1_lagrange_optimization().
p1_lagrange_optimization_enabled()
bool p1_lagrange_optimization_enabled () const inline
References StdTransfer< class, class >::p1_lagrange_optimization_enabled().
set_debug()
void set_debug (SmartPtr< IDebugWriter > unnamed) inline
Parameters
[in] unnamed
References StdTransfer< class, class >::set_debug().
set_prolongation_damping()
void set_prolongation_damping (double unnamed) inline
Parameters
[in] unnamed
References StdTransfer< class, class >::set_prolongation_damping().
set_restriction_damping()
void set_restriction_damping (double unnamed) inline
Parameters
[in] unnamed
References StdTransfer< class, class >::set_restriction_damping().
set_use_transposed()
void set_use_transposed (bool unnamed) inline
Parameters
[in] unnamed
References StdTransfer< class, class >::set_use_transposed().