Registry: IDomainDiscretization Class Reference
IDomainDiscretization Class Reference
Public Member Functions
void adjust_solution (Vector *unnamed)
void assemble_defect (Vector *d(u), const Vector *u)
Assembles Defect on surface grid.
void assemble_jacobian (Matrix *J(u), const Vector *u)
assembles jacobian on surface grid
void assemble_jacobian (Matrix *unnamed, ConstSmartPtr< SolutionTimeSeries > unnamed, double unnamed)
void assemble_linear (Matrix *A, Vector *b)
Assembles Matrix and rhs on surface grid.
void assemble_mass_matrix (Matrix *M, const Vector *u)
assembles mass matrix on surface grid
void assemble_rhs (Vector *rhs, const Vector *u)
assembles right-hand side on surface grid
void assemble_stiffness_matrix (Matrix *A, const Vector *u)
assembles stiffness matrix on surface grid
Private Member Functions
IDomainDiscretization ()=delete
Constructor hidden / deactivated.
Detailed Description
Note
default specialization is IDomainDiscretizationCPU1
See also
ug::IDomainDiscretization
Constructor & Destructor Documentation
IDomainDiscretization()
IDomainDiscretization () private delete
Constructor hidden / deactivated.
Member Function Documentation
adjust_solution()
void adjust_solution (Vector * unnamed) inline inherited
Parameters
[in] unnamed
References IAssemble< TAlgebra >::adjust_solution().
assemble_defect()
void assemble_defect (Vector * du, const Vector * u) inline inherited
Assembles Defect on surface grid.
Parameters
[in] d(u)
[in] u
References IAssemble< TAlgebra >::assemble_defect().
assemble_jacobian() [1/2]
void assemble_jacobian (Matrix * Ju, const Vector * u) inline inherited
assembles jacobian on surface grid
Parameters
[in] J(u)
[in] u
References IAssemble< TAlgebra >::assemble_jacobian().
assemble_jacobian() [2/2]
void assemble_jacobian (Matrix * unnamed, ConstSmartPtr< SolutionTimeSeries > unnamed, double unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References IDomainDiscretization< class >::assemble_jacobian().
assemble_linear()
void assemble_linear (Matrix * A, Vector * b) inline inherited
Assembles Matrix and rhs on surface grid.
Parameters
[in] A
[in] b
References IAssemble< TAlgebra >::assemble_linear().
assemble_mass_matrix()
void assemble_mass_matrix (Matrix * M, const Vector * u) inline inherited
assembles mass matrix on surface grid
Parameters
[in] M
[in] u
References IAssemble< TAlgebra >::assemble_mass_matrix().
assemble_rhs()
void assemble_rhs (Vector * rhs, const Vector * u) inline inherited
assembles right-hand side on surface grid
Parameters
[in] rhs
[in] u
References IAssemble< TAlgebra >::assemble_rhs().
assemble_stiffness_matrix()
void assemble_stiffness_matrix (Matrix * A, const Vector * u) inline inherited
assembles stiffness matrix on surface grid
Parameters
[in] A
[in] u
References IAssemble< TAlgebra >::assemble_stiffness_matrix().