Registry: ComponentGaussSeidel Class Reference
ComponentGaussSeidel Class Reference
Vanka Preconditioner.
Public Member Functions
ComponentGaussSeidel (std::vector< std::string > Cmps)
ComponentGaussSeidel (double relax, std::vector< std::string > Cmps)
ComponentGaussSeidel (double relax, std::vector< std::string > Cmps, std::vector< int > unnamed, std::vector< double > unnamed)
void set_alpha (double alpha)
void set_beta (double beta)
void set_weights (bool weights)
Detailed Description
Vanka Preconditioner.
Note
default specialization is ComponentGaussSeidel2dCPU1
See also
ug::ComponentGaussSeidel
Constructor & Destructor Documentation
ComponentGaussSeidel() [1/3]
ComponentGaussSeidel (std::vector< std::string > Cmps)
Parameters
[in] Cmps
ComponentGaussSeidel() [2/3]
ComponentGaussSeidel (double relax, std::vector< std::string > Cmps)
Parameters
[in] relax
[in] Cmps
ComponentGaussSeidel() [3/3]
ComponentGaussSeidel (double relax, std::vector< std::string > Cmps, std::vector< int > unnamed, std::vector< double > unnamed)
Parameters
[in] relax
[in] Cmps
[in] unnamed
[in] unnamed
Member Function Documentation
set_alpha()
void set_alpha (double alpha) inline
Parameters
[in] alpha
References ComponentGaussSeidel< class, class >::set_alpha().
set_beta()
void set_beta (double beta) inline
Parameters
[in] beta
References ComponentGaussSeidel< class, class >::set_beta().
set_weights()
void set_weights (bool weights) inline
Parameters
[in] weights
References ComponentGaussSeidel< class, class >::set_weights().