Registry: DomainRayTracer Class Reference
DomainRayTracer Class Reference
Public Member Functions
DomainRayTracer (Domain *unnamed)
void init (std::vector< int > subsetIndices)
size_t num_trace_points () const
void set_small (double small)
const Vec3d * trace_point (size_t index) const
double trace_point_x (size_t index) const
double trace_point_y (size_t index) const
double trace_point_z (size_t index) const
size_t trace_ray (const Vec3d *rayFrom, const Vec3d *rayTo)
Constructor & Destructor Documentation
DomainRayTracer()
DomainRayTracer (Domain * unnamed)
Parameters
[in] unnamed
Member Function Documentation
init()
void init (std::vector< int > subsetIndices) inline
Parameters
[in] subsetIndices
References DomainRayTracer::init().
num_trace_points()
size_t num_trace_points () const inline
Returns
numPoints
References DomainRayTracer::num_trace_points().
set_small()
void set_small (double small) inline
Parameters
[in] small
References DomainRayTracer::set_small().
trace_point()
const Vec3d* trace_point (size_t index) const inline
Parameters
[in] index
Returns
point
References DomainRayTracer::trace_point().
trace_point_x()
double trace_point_x (size_t index) const inline
Parameters
[in] index
Returns
xCoord
References DomainRayTracer::trace_point_x().
trace_point_y()
double trace_point_y (size_t index) const inline
Parameters
[in] index
Returns
yCoord
References DomainRayTracer::trace_point_y().
trace_point_z()
double trace_point_z (size_t index) const inline
Parameters
[in] index
Returns
zCoord
References DomainRayTracer::trace_point_z().
trace_ray()
size_t trace_ray (const Vec3d * rayFrom, const Vec3d * rayTo) inline
Parameters
[in] rayFrom
[in] rayTo
References DomainRayTracer::trace_ray().