Registry: NLJacobiSolver Class Reference
NLJacobiSolver Class Reference
Public Member Functions
bool apply (Vector *u)
std::string config_string () const
bool init (SmartPtr< IOperator > op)
NLJacobiSolver ()
NLJacobiSolver (SmartPtr< IConvergenceCheck > ConvCheck)
bool prepare (Vector *u)
void set_convergence_check (SmartPtr< IConvergenceCheck > convCheck)
void set_damp (double setDampingFactor)
Detailed Description
Note
default specialization is NLJacobiSolverCPU1
See also
ug::NLJacobiSolver
Constructor & Destructor Documentation
NLJacobiSolver() [1/2]
NLJacobiSolver ()
NLJacobiSolver() [2/2]
NLJacobiSolver (SmartPtr< IConvergenceCheck > ConvCheck)
Parameters
[in] ConvCheck
Member Function Documentation
apply()
bool apply (Vector * u) inline
Parameters
[in] u
Returns
success
References NLJacobiSolver< class >::apply().
config_string()
std::string config_string () const inline
References NLJacobiSolver< class >::config_string().
init()
bool init (SmartPtr< IOperator > op) inline
Parameters
[in] op
Returns
success
References NLJacobiSolver< class >::init().
prepare()
bool prepare (Vector * u) inline
Parameters
[in] u
Returns
success
References NLJacobiSolver< class >::prepare().
set_convergence_check()
void set_convergence_check (SmartPtr< IConvergenceCheck > convCheck) inline
Parameters
[in] convCheck
References NLJacobiSolver< class >::set_convergence_check().
set_damp()
void set_damp (double setDampingFactor) inline
Parameters
[in] setDampingFactor
References NLJacobiSolver< class >::set_damp().