Registry: Vector Class Reference
Vector Class Reference
Public Member Functions
void check_storage_type () const
void enforce_consistent_type ()
void print ()
void set (double Number)
void set_random (double Number, double unnamed)
size_t size () const
Vector ()
Detailed Description
Note
default specialization is VectorCPU1
See also
ug::Vector
Constructor & Destructor Documentation
Vector()
Vector ()
Member Function Documentation
check_storage_type()
void check_storage_type () const inline
enforce_consistent_type()
void enforce_consistent_type () inline
print()
void print () inline
References Vector< TValueType >::print().
set()
void set (double Number) inline
Parameters
[in] Number
References Vector< TValueType >::set().
set_random()
void set_random (double Number, double unnamed) inline
Parameters
[in] Number
[in] unnamed
References Vector< TValueType >::set_random().
size()
size_t size () const inline
Returns
Size
References Vector< TValueType >::size().