Registry: DebugIterator Class Reference
DebugIterator Class Reference
DebugIterator.
Public Member Functions
bool apply (Vector *unnamed, const Vector *unnamed)
bool apply_update_defect (Vector *unnamed, Vector *unnamed)
SmartPtr< ILinearIterator > clone ()
returns a clone of the object which can be modified independently
std::string config_string () const
string to display configuration of the linear iterator
DebugIterator ()
DebugIterator (SmartPtr< ILinearIterator > precond, SmartPtr< IPreconditionedLinearOperatorInverse > solver)
bool init (SmartPtr< ILinearOperator > unnamed)
const char * name () const
void set_damp (double damp)
set the damping to a number
void set_debug (SmartPtr< IVectorDebugWriter > unnamed)
void set_preconditioner (SmartPtr< ILinearIterator > unnamed)
void set_random_bounds (double unnamed, double unnamed)
void set_solution (SmartPtr< Vector > unnamed)
void set_solver (SmartPtr< IPreconditionedLinearOperatorInverse > unnamed)
Detailed Description
DebugIterator.
Note
default specialization is DebugIteratorCPU1
See also
ug::DebugIterator
Constructor & Destructor Documentation
DebugIterator() [1/2]
DebugIterator ()
DebugIterator() [2/2]
DebugIterator (SmartPtr< ILinearIterator > precond, SmartPtr< IPreconditionedLinearOperatorInverse > solver)
Parameters
[in] precond
[in] solver
Member Function Documentation
apply()
bool apply (Vector * unnamed, const Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply().
apply_update_defect()
bool apply_update_defect (Vector * unnamed, Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply_update_defect().
clone()
SmartPtr<ILinearIterator> clone () inline inherited
returns a clone of the object which can be modified independently
Returns
SmartPointer to a copy of this object
References ILinearIterator< X, Y >::clone().
config_string()
std::string config_string () const inline inherited
string to display configuration of the linear iterator
Returns
strConfiguration
References ILinearIterator< X, Y >::config_string().
init()
bool init (SmartPtr< ILinearOperator > unnamed) inline inherited
Parameters
[in] unnamed
References ILinearIterator< X, Y >::init().
name()
const char* name () const inline inherited
References ILinearIterator< X, Y >::name().
set_damp()
void set_damp (double damp) inline inherited
set the damping to a number
Parameters
[in] damp
References ILinearIterator< X, Y >::set_damp().
set_debug()
void set_debug (SmartPtr< IVectorDebugWriter > unnamed) inline
Parameters
[in] unnamed
References VectorDebugWritingObject< TAlgebra::vector_type >::set_debug().
set_preconditioner()
void set_preconditioner (SmartPtr< ILinearIterator > unnamed) inline
Parameters
[in] unnamed
References DebugIterator< class >::set_preconditioner().
set_random_bounds()
void set_random_bounds (double unnamed, double unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References DebugIterator< class >::set_random_bounds().
set_solution()
void set_solution (SmartPtr< Vector > unnamed) inline
Parameters
[in] unnamed
References DebugIterator< class >::set_solution().
set_solver()
void set_solver (SmartPtr< IPreconditionedLinearOperatorInverse > unnamed) inline
Parameters
[in] unnamed
References DebugIterator< class >::set_solver().