Registry: EigenSolver Class Reference
EigenSolver Class Reference
Public Member Functions
void add_vector (SmartPtr< Vector > vector)
int apply ()
SmartPtr< IDebugWriter > debug_writer ()
ConstSmartPtr< IDebugWriter > debug_writer () const
EigenSolver ()
double get_defect (size_t unnamed, size_t unnamed)
double get_eigenvalue (size_t i)
SmartPtr< Vector > get_eigenvector (size_t i)
size_t get_iterations ()
double get_lambda (size_t unnamed, size_t unnamed)
void get_max_deflection_of_a_mode (Vector *composed_mode_and_eigenvectors,, Vector *unnamed, const Vector *unnamed, const Matrix *unnamed)
size_t num_eigenvalues ()
void set_additional_eigenvectors_to_keep (size_t i)
additional i smallest ritz-eigenvectors are added to the test space
void set_debug (SmartPtr< IDebugWriter > dbgWriter)
sets a debug writer
void set_debug (SmartPtr< IVectorDebugWriter > dbgWriter)
sets a debug writer
void set_debug_calc_projected_eigenvalues (bool b)
void set_laplacian (bool unnamed)
void set_linear_dependent_eps (double unnamed)
void set_linear_operator_A (SmartPtr< ILinearOperator > LinearOperatorA)
void set_linear_operator_B (MatrixOperator *LinearOperatorB)
void set_max_iterations (size_t precision)
void set_pinvit (size_t iPINVIT)
1 = preconditioned inverse block iteration, 2 = preconditioned block gradient descent, 3 = LOBPCG
void set_precision (double precision)
void set_preconditioner (SmartPtr< ILinearIterator > Preconditioner)
void set_print_projected_eigenproblem (bool b)
void set_print_projected_eigenvalues (bool b)
void set_print_projected_eigenvectors (bool b)
void set_print_used_testvectors (bool b)
void set_relative_precision (double precision)
void set_store_defects (bool unnamed)
void set_store_lambdas (bool unnamed)
void set_use_additional_corrections (bool b)
SmartPtr< IVectorDebugWriter > vector_debug_writer ()
ConstSmartPtr< IVectorDebugWriter > vector_debug_writer () const
Detailed Description
Note
default specialization is EigenSolverCPU1
See also
ug::EigenSolver
Constructor & Destructor Documentation
EigenSolver()
EigenSolver ()
Member Function Documentation
add_vector()
void add_vector (SmartPtr< Vector > vector) inline
Parameters
[in] vector
apply()
int apply () inline
debug_writer() [1/2]
SmartPtr<IDebugWriter> debug_writer () inline inherited
References DebugWritingObject< TAlgebra >::debug_writer().
debug_writer() [2/2]
ConstSmartPtr<IDebugWriter> debug_writer () const inline inherited
References DebugWritingObject< TAlgebra >::debug_writer().
get_defect()
double get_defect (size_t unnamed, size_t unnamed) inline
Parameters
[in] unnamed
[in] unnamed
get_eigenvalue()
double get_eigenvalue (size_t i) inline
Parameters
[in] i
Returns
eigenvalue i
get_eigenvector()
SmartPtr<Vector> get_eigenvector (size_t i) inline
Parameters
[in] i
Returns
eigenvector i
get_iterations()
size_t get_iterations () inline
get_lambda()
double get_lambda (size_t unnamed, size_t unnamed) inline
Parameters
[in] unnamed
[in] unnamed
get_max_deflection_of_a_mode()
void get_max_deflection_of_a_mode (Vector * composed_mode_and_eigenvectors, Vector * unnamed, const Vector * unnamed, const Matrix * unnamed) inline
Parameters
[in] composed_mode_and_eigenvectors
num_eigenvalues()
size_t num_eigenvalues () inline
Returns
number of eigenvalues
set_additional_eigenvectors_to_keep()
void set_additional_eigenvectors_to_keep (size_t i) inline
additional i smallest ritz-eigenvectors are added to the test space
Parameters
[in] i
set_debug() [1/2]
void set_debug (SmartPtr< IDebugWriter > dbgWriter) inline inherited
sets a debug writer
Parameters
[in] dbgWriter
References DebugWritingObject< TAlgebra >::set_debug().
set_debug() [2/2]
void set_debug (SmartPtr< IVectorDebugWriter > dbgWriter) inline inherited
sets a debug writer
Parameters
[in] dbgWriter
References VectorDebugWritingObject< TVector >::set_debug().
set_debug_calc_projected_eigenvalues()
void set_debug_calc_projected_eigenvalues (bool b) inline
Parameters
[in] b
set_laplacian()
void set_laplacian (bool unnamed) inline
Parameters
[in] unnamed
set_linear_dependent_eps()
void set_linear_dependent_eps (double unnamed) inline
Parameters
[in] unnamed
set_linear_operator_A()
void set_linear_operator_A (SmartPtr< ILinearOperator > LinearOperatorA) inline
Parameters
[in] LinearOperatorA
set_linear_operator_B()
void set_linear_operator_B (MatrixOperator * LinearOperatorB) inline
Parameters
[in] LinearOperatorB
set_max_iterations()
void set_max_iterations (size_t precision) inline
Parameters
[in] precision
set_pinvit()
void set_pinvit (size_t iPINVIT) inline
1 = preconditioned inverse block iteration, 2 = preconditioned block gradient descent, 3 = LOBPCG
Parameters
[in] iPINVIT
set_precision()
void set_precision (double precision) inline
Parameters
[in] precision
set_preconditioner()
void set_preconditioner (SmartPtr< ILinearIterator > Preconditioner) inline
Parameters
[in] Preconditioner
set_print_projected_eigenproblem()
void set_print_projected_eigenproblem (bool b) inline
Parameters
[in] b
set_print_projected_eigenvalues()
void set_print_projected_eigenvalues (bool b) inline
Parameters
[in] b
set_print_projected_eigenvectors()
void set_print_projected_eigenvectors (bool b) inline
Parameters
[in] b
set_print_used_testvectors()
void set_print_used_testvectors (bool b) inline
Parameters
[in] b
set_relative_precision()
void set_relative_precision (double precision) inline
Parameters
[in] precision
set_store_defects()
void set_store_defects (bool unnamed) inline
Parameters
[in] unnamed
set_store_lambdas()
void set_store_lambdas (bool unnamed) inline
Parameters
[in] unnamed
set_use_additional_corrections()
void set_use_additional_corrections (bool b) inline
Parameters
[in] b
vector_debug_writer() [1/2]
SmartPtr<IVectorDebugWriter> vector_debug_writer () inline inherited
References VectorDebugWritingObject< TVector >::vector_debug_writer().
vector_debug_writer() [2/2]
ConstSmartPtr<IVectorDebugWriter> vector_debug_writer () const inline inherited
References VectorDebugWritingObject< TVector >::vector_debug_writer().