Registry: IDWUserData Class Reference
IDWUserData Class Reference
Public Member Functions
int get_dim () const
IDWUserData ()
IDWUserData (double order, double radius)
void load_data_from (const char *file_name)
void set_order (double order)
void set_radius (double radius)
std::string type () const
Detailed Description
Note
default specialization is IDWUserData2d
See also
ug::IDWUserData
Constructor & Destructor Documentation
IDWUserData() [1/2]
IDWUserData ()
IDWUserData() [2/2]
IDWUserData (double order, double radius)
Parameters
[in] order
[in] radius
Member Function Documentation
get_dim()
int get_dim () const inline inherited
References get_dim().
load_data_from()
void load_data_from (const char * file_name) inline
Parameters
[in] file_name
References IDWUserData< WDim, class >::load_data_from().
set_order()
void set_order (double order) inline
Parameters
[in] order
References IDWUserData< WDim, class >::set_order().
set_radius()
void set_radius (double radius) inline
Parameters
[in] radius
References IDWUserData< WDim, class >::set_radius().
type()
std::string type () const inline inherited
References type().