Registry: SchurComplement Class Reference
SchurComplement Class Reference
Schur complement preconditioner.
Public Member Functions
bool apply (Vector *unnamed, const Vector *unnamed)
bool apply_update_defect (Vector *unnamed, Vector *unnamed)
SmartPtr< ILinearIterator > clone ()
returns a clone of the object which can be modified independently
std::string config_string () const
string to display configuration of the linear iterator
bool init (SmartPtr< ILinearOperator > unnamed)
const char * name () const
size_t num_global_skeleton ()
size_t num_local_skeleton ()
SchurComplement ()
void set_damp (double damp)
set the damping to a number
void set_dirichlet_solver (SmartPtr< ILinearOperatorInverse > Dirichlet_solver)
void set_skeleton_solver (SmartPtr< ISchurComplementInverse > Skeleton_solver)
Detailed Description
Schur complement preconditioner.
Note
default specialization is SchurComplementCPU1
See also
ug::SchurComplement
Constructor & Destructor Documentation
SchurComplement()
SchurComplement ()
Member Function Documentation
apply()
bool apply (Vector * unnamed, const Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply().
apply_update_defect()
bool apply_update_defect (Vector * unnamed, Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply_update_defect().
clone()
SmartPtr<ILinearIterator> clone () inline inherited
returns a clone of the object which can be modified independently
Returns
SmartPointer to a copy of this object
References ILinearIterator< X, Y >::clone().
config_string()
std::string config_string () const inline inherited
string to display configuration of the linear iterator
Returns
strConfiguration
References ILinearIterator< X, Y >::config_string().
init()
bool init (SmartPtr< ILinearOperator > unnamed) inline inherited
Parameters
[in] unnamed
References ILinearIterator< X, Y >::init().
name()
const char* name () const inline inherited
References ILinearIterator< X, Y >::name().
num_global_skeleton()
size_t num_global_skeleton () inline
num_local_skeleton()
size_t num_local_skeleton () inline
set_damp()
void set_damp (double damp) inline inherited
set the damping to a number
Parameters
[in] damp
References ILinearIterator< X, Y >::set_damp().
set_dirichlet_solver()
void set_dirichlet_solver (SmartPtr< ILinearOperatorInverse > Dirichlet_solver) inline
Parameters
[in] Dirichlet_solver
set_skeleton_solver()
void set_skeleton_solver (SmartPtr< ISchurComplementInverse > Skeleton_solver) inline
Parameters
[in] Skeleton_solver