Registry: BDF Class Reference
BDF Class Reference
Public Member Functions
BDF (SmartPtr< IDomainDiscretization > Domain_Discretization)
BDF (SmartPtr< IDomainDiscretization > Domain_Discretization, int Order)
void calc_error (const Vector *unnamed)
calculate error indicators for elements from error estimators of the elemDiscs
void finish_step (SmartPtr< SolutionTimeSeries > unnamed)
finishes the assembling of defect/Jacobian for a time step
void finish_step_elem (SmartPtr< SolutionTimeSeries > unnamed)
double future_time () const
void invalidate_error ()
bool is_error_valid ()
size_t num_prev_steps () const
size_t num_stages () const
void prepare_step (SmartPtr< SolutionTimeSeries > unnamed, double unnamed)
prepares the assembling of defect/Jacobian for a time step
void prepare_step_elem (SmartPtr< SolutionTimeSeries > unnamed, double unnamed)
void set_order (size_t Order)
void set_stage (size_t stage)
Detailed Description
Note
default specialization is BDFCPU1
See also
ug::BDF
Constructor & Destructor Documentation
BDF() [1/2]
BDF (SmartPtr< IDomainDiscretization > Domain_Discretization)
Parameters
[in] Domain_Discretization
BDF() [2/2]
BDF (SmartPtr< IDomainDiscretization > Domain_Discretization, int Order)
Parameters
[in] Domain_Discretization
[in] Order
Member Function Documentation
calc_error()
void calc_error (const Vector * unnamed) inline inherited
calculate error indicators for elements from error estimators of the elemDiscs
Parameters
[in] unnamed
References MultiStepTimeDiscretization< class >::calc_error().
finish_step()
void finish_step (SmartPtr< SolutionTimeSeries > unnamed) inline inherited
finishes the assembling of defect/Jacobian for a time step
Parameters
[in] unnamed
References ITimeDiscretization< class >::finish_step().
finish_step_elem()
void finish_step_elem (SmartPtr< SolutionTimeSeries > unnamed) inline inherited
Parameters
[in] unnamed
References ITimeDiscretization< class >::finish_step_elem().
future_time()
double future_time () const inline inherited
Returns
the future time point (i.e. the one that will be computed)
References ITimeDiscretization< class >::future_time().
invalidate_error()
void invalidate_error () inline inherited
References MultiStepTimeDiscretization< class >::invalidate_error().
is_error_valid()
bool is_error_valid () inline inherited
References MultiStepTimeDiscretization< class >::is_error_valid().
num_prev_steps()
size_t num_prev_steps () const inline inherited
References ITimeDiscretization< class >::num_prev_steps().
num_stages()
size_t num_stages () const inline inherited
Returns
the number of stages
References ITimeDiscretization< class >::num_stages().
prepare_step()
void prepare_step (SmartPtr< SolutionTimeSeries > unnamed, double unnamed) inline inherited
prepares the assembling of defect/Jacobian for a time step
Parameters
[in] unnamed
[in] unnamed
References ITimeDiscretization< class >::prepare_step().
prepare_step_elem()
void prepare_step_elem (SmartPtr< SolutionTimeSeries > unnamed, double unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ITimeDiscretization< class >::prepare_step_elem().
set_order()
void set_order (size_t Order) inline
Parameters
[in] Order
References BDF< class >::set_order().
set_stage()
void set_stage (size_t stage) inline inherited
Parameters
[in] stage
References ITimeDiscretization< class >::set_stage().