Registry: PrandtlReuss Class Reference
PrandtlReuss Class Reference
Public Member Functions
PrandtlReuss ()
void set_bulk_modulus (double bulkModulus)
void set_hardening_behavior (int hardeningBehavior)
void set_hardening_exponent (double hardeningExponent)
void set_hardening_modulus (double hardeningModulus)
void set_initial_flow_stress (double initialFlowStress)
void set_residual_flow_stress (double residualFlowStress)
void set_shear_modulus (double shearModulus)
void set_tangent_precision (double tangentPrecision)
Detailed Description
Note
default specialization is PrandtlReuss2d
See also
ug::PrandtlReuss
Constructor & Destructor Documentation
PrandtlReuss ()
Member Function Documentation
void set_bulk_modulus (double bulkModulus) inline
Parameters
[in] bulkModulus
References set_bulk_modulus().
void set_hardening_behavior (int hardeningBehavior) inline
Parameters
[in] hardeningBehavior
References set_hardening_behavior().
void set_hardening_exponent (double hardeningExponent) inline
Parameters
[in] hardeningExponent
References set_hardening_exponent().
void set_hardening_modulus (double hardeningModulus) inline
Parameters
[in] hardeningModulus
References set_hardening_modulus().
void set_initial_flow_stress (double initialFlowStress) inline
Parameters
[in] initialFlowStress
References set_initial_flow_stress().
void set_residual_flow_stress (double residualFlowStress) inline
Parameters
[in] residualFlowStress
References set_residual_flow_stress().
void set_shear_modulus (double shearModulus) inline
Parameters
[in] shearModulus
References set_shear_modulus().
void set_tangent_precision (double tangentPrecision) inline
Parameters
[in] tangentPrecision
References set_tangent_precision().