Registry: CG Class Reference
CG Class Reference
Conjugate Gradient Solver.
Public Member Functions
bool apply (Vector *u, const Vector *f)
Solve A*u = f, such that u = A^{-1} f by iterating u := u + B(f - A*u), f remains constant.
bool apply_return_defect (Vector *u, Vector *f)
Solve A*u = f, such that u = A^{-1} f by iterating u := u + B(f - A*u), f := f - A*u becomes new defect.
bool apply_update_defect (Vector *unnamed, Vector *unnamed)
CG ()
CG (SmartPtr< ILinearIterator > precond)
CG (SmartPtr< ILinearIterator > precond, SmartPtr< IConvergenceCheck > convCheck)
SmartPtr< ILinearIterator > clone ()
returns a clone of the object which can be modified independently
std::string config_string () const
ConstSmartPtr< IConvergenceCheck > convergence_check () const
double defect () const
bool init (SmartPtr< ILinearOperator > unnamed)
const char * name () const
double reduction () const
void set_compute_fresh_defect_when_finished (bool unnamed)
void set_convergence_check (SmartPtr< IConvergenceCheck > unnamed)
void set_damp (double damp)
set the damping to a number
void set_preconditioner (SmartPtr< ILinearIterator > Preconditioner)
int step () const
Detailed Description
Conjugate Gradient Solver.
Note
default specialization is CGCPU1
See also
ug::CG
Constructor & Destructor Documentation
CG ()
CG (SmartPtr< ILinearIterator > precond)
Parameters
[in] precond
CG (SmartPtr< ILinearIterator > precond, SmartPtr< IConvergenceCheck > convCheck)
Parameters
[in] precond
[in] convCheck
Member Function Documentation
bool apply (Vector * u, const Vector * f) inline inherited
Solve A*u = f, such that u = A^{-1} f by iterating u := u + B(f - A*u), f remains constant.
Parameters
[in] u
[in] f
Returns
Success
References ILinearOperatorInverse< X, Y >::apply().
bool apply_return_defect (Vector * u, Vector * f) inline inherited
Solve A*u = f, such that u = A^{-1} f by iterating u := u + B(f - A*u), f := f - A*u becomes new defect.
Parameters
[in] u
[in] f
Returns
Success
References ILinearOperatorInverse< X, Y >::apply_return_defect().
bool apply_update_defect (Vector * unnamed, Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply_update_defect().
SmartPtr<ILinearIterator> clone () inline inherited
returns a clone of the object which can be modified independently
Returns
SmartPointer to a copy of this object
References ILinearIterator< X, Y >::clone().
std::string config_string () const inline inherited
References ILinearOperatorInverse< X, Y >::config_string().
ConstSmartPtr<IConvergenceCheck> convergence_check () const inline inherited
References ILinearOperatorInverse< X, Y >::convergence_check().
double defect () const inline inherited
Returns
the current defect
References ILinearOperatorInverse< X, Y >::defect().
bool init (SmartPtr< ILinearOperator > unnamed) inline inherited
Parameters
[in] unnamed
References ILinearOperatorInverse< X, Y >::init().
const char* name () const inline inherited
References ILinearIterator< X, Y >::name().
double reduction () const inline inherited
Returns
the current relative reduction
References ILinearOperatorInverse< X, Y >::reduction().
void set_compute_fresh_defect_when_finished (bool unnamed) inline inherited
Parameters
[in] unnamed
References IPreconditionedLinearOperatorInverse< X >::set_compute_fresh_defect_when_finished().
void set_convergence_check (SmartPtr< IConvergenceCheck > unnamed) inline inherited
Parameters
[in] unnamed
References ILinearOperatorInverse< X, Y >::set_convergence_check().
void set_damp (double damp) inline inherited
set the damping to a number
Parameters
[in] damp
References ILinearIterator< X, Y >::set_damp().
void set_preconditioner (SmartPtr< ILinearIterator > Preconditioner) inline inherited
Parameters
[in] Preconditioner
References IPreconditionedLinearOperatorInverse< X >::set_preconditioner().
int step () const inline inherited
Returns
the current number of steps
References ILinearOperatorInverse< X, Y >::step().