Registry: ActiveSet Class Reference
ActiveSet Class Reference
Public Member Functions
bool active_index (GridFunction *unnamed, GridFunction *unnamed, GridFunction *unnamed, GridFunction *unnamed)
is index active or not, stores activeSetList
ActiveSet ()
bool check_conv (GridFunction *unnamed, const GridFunction *unnamed, size_t unnamed)
activeIndexSet changed or not
bool check_ineq (const Matrix *unnamed, const Vector *unnamed, const Vector *unnamed, const Vector *unnamed)
check if all inequalities are fulfilled
void lagrange_multiplier (GridFunction *unnamed, const GridFunction *unnamed)
computes lagrange multiplier
void prepare (GridFunction *prepare)
void residual_lagrange_mult (Vector *unnamed, const Matrix *unnamed, const Vector *unnamed, Vector *unnamed)
computes lagrange multiplier
void set_dirichlet_rows (Matrix *unnamed)
sets dirichlet rows for active DoFs
void set_lagrange_multiplier_disc (SmartPtr< ILagrangeMultiplierDisc > discretization_to_compute_the_lagrange_multiplier)
void set_obstacle (ConstSmartPtr< GridFunction > sets_limiting_obstacle_constraint)
Detailed Description
Note
default specialization is ActiveSet2dCPU1
See also
ug::ActiveSet
Constructor & Destructor Documentation
ActiveSet()
ActiveSet ()
Member Function Documentation
active_index()
bool active_index (GridFunction * unnamed, GridFunction * unnamed, GridFunction * unnamed, GridFunction * unnamed) inline
is index active or not, stores activeSetList
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References ActiveSet< class, class >::active_index().
check_conv()
bool check_conv (GridFunction * unnamed, const GridFunction * unnamed, size_t unnamed) inline
activeIndexSet changed or not
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References ActiveSet< class, class >::check_conv().
check_ineq()
bool check_ineq (const Matrix * unnamed, const Vector * unnamed, const Vector * unnamed, const Vector * unnamed) inline
check if all inequalities are fulfilled
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
lagrange_multiplier()
void lagrange_multiplier (GridFunction * unnamed, const GridFunction * unnamed) inline
computes lagrange multiplier
Parameters
[in] unnamed
[in] unnamed
References ActiveSet< class, class >::lagrange_multiplier().
prepare()
void prepare (GridFunction * prepare) inline
Parameters
[in] prepare
References ActiveSet< class, class >::prepare().
residual_lagrange_mult()
void residual_lagrange_mult (Vector * unnamed, const Matrix * unnamed, const Vector * unnamed, Vector * unnamed) inline
computes lagrange multiplier
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References ActiveSet< class, class >::residual_lagrange_mult().
set_dirichlet_rows()
void set_dirichlet_rows (Matrix * unnamed) inline
sets dirichlet rows for active DoFs
Parameters
[in] unnamed
References ActiveSet< class, class >::set_dirichlet_rows().
set_lagrange_multiplier_disc()
void set_lagrange_multiplier_disc (SmartPtr< ILagrangeMultiplierDisc > discretization_to_compute_the_lagrange_multiplier) inline
Parameters
[in] discretization_to_compute_the_lagrange_multiplier
References ActiveSet< class, class >::set_lagrange_multiplier_disc().
set_obstacle()
void set_obstacle (ConstSmartPtr< GridFunction > sets_limiting_obstacle_constraint) inline
Parameters
[in] sets_limiting_obstacle_constraint
References ActiveSet< class, class >::set_obstacle().