Registry: MGStats Class Reference
MGStats Class Reference
Public Member Functions
void clear ()
MGStats ()
void print ()
void save_stats_to_file ()
void set_active_stages (std::vector< int > activeStages)
void set_exit_on_error (bool exitOnError)
void set_filename_prefix (const char *filename)
void set_write_err_diffs (bool writeErrDiffs)
void set_write_err_vecs (bool writeErrVecs)
Detailed Description
Note
default specialization is MGStats2dCPU1
See also
ug::MGStats
Constructor & Destructor Documentation
MGStats()
MGStats ()
Member Function Documentation
clear()
void clear () inline
References MGStats< class, class >::clear().
print()
void print () inline
References MGStats< class, class >::print().
save_stats_to_file()
void save_stats_to_file () inline
References MGStats< class, class >::save_stats_to_file().
set_active_stages()
void set_active_stages (std::vector< int > activeStages) inline
Parameters
[in] activeStages
References MGStats< class, class >::set_active_stages().
set_exit_on_error()
void set_exit_on_error (bool exitOnError) inline
Parameters
[in] exitOnError
References MGStats< class, class >::set_exit_on_error().
set_filename_prefix()
void set_filename_prefix (const char * filename) inline
Parameters
[in] filename
References MGStats< class, class >::set_filename_prefix().
set_write_err_diffs()
void set_write_err_diffs (bool writeErrDiffs) inline
Parameters
[in] writeErrDiffs
References MGStats< class, class >::set_write_err_diffs().
set_write_err_vecs()
void set_write_err_vecs (bool writeErrVecs) inline
Parameters
[in] writeErrVecs
References MGStats< class, class >::set_write_err_vecs().