Registry: MultiGrid Class Reference
MultiGrid Class Reference
Public Member Functions
void clear ()
void clear_geometry ()
MultiGrid ()
size_t num_edges () const
size_t num_edges (int unnamed) const
size_t num_faces () const
size_t num_faces (int unnamed) const
size_t num_hexahedrons () const
size_t num_hexahedrons (int unnamed) const
size_t num_levels () const
size_t num_prisms () const
size_t num_prisms (int unnamed) const
size_t num_pyramids () const
size_t num_pyramids (int unnamed) const
size_t num_quadrilaterals () const
size_t num_quadrilaterals (int unnamed) const
size_t num_tetrahedrons () const
size_t num_tetrahedrons (int unnamed) const
size_t num_triangles () const
size_t num_triangles (int unnamed) const
size_t num_vertices () const
size_t num_vertices (int unnamed) const
size_t num_volumes () const
size_t num_volumes (int unnamed) const
void reserve_edges (size_t num)
void reserve_faces (size_t num)
void reserve_vertices (size_t num)
void reserve_volumes (size_t num)
Constructor & Destructor Documentation
MultiGrid()
MultiGrid ()
Member Function Documentation
clear()
void clear () inline inherited
References Grid::clear().
clear_geometry()
void clear_geometry () inline inherited
References Grid::clear_geometry().
num_edges() [1/2]
size_t num_edges () const inline inherited
References Grid::num_edges().
num_edges() [2/2]
size_t num_edges (int unnamed) const inline
Parameters
[in] unnamed
References Grid::num_edges().
num_faces() [1/2]
size_t num_faces () const inline inherited
References Grid::num_faces().
num_faces() [2/2]
size_t num_faces (int unnamed) const inline
Parameters
[in] unnamed
References Grid::num_faces().
num_hexahedrons() [1/2]
size_t num_hexahedrons () const inline inherited
num_hexahedrons() [2/2]
size_t num_hexahedrons (int unnamed) const inline
Parameters
[in] unnamed
num_levels()
size_t num_levels () const inline
References MultiGrid::num_levels().
num_prisms() [1/2]
size_t num_prisms () const inline inherited
num_prisms() [2/2]
size_t num_prisms (int unnamed) const inline
Parameters
[in] unnamed
num_pyramids() [1/2]
size_t num_pyramids () const inline inherited
num_pyramids() [2/2]
size_t num_pyramids (int unnamed) const inline
Parameters
[in] unnamed
num_quadrilaterals() [1/2]
size_t num_quadrilaterals () const inline inherited
num_quadrilaterals() [2/2]
size_t num_quadrilaterals (int unnamed) const inline
Parameters
[in] unnamed
num_tetrahedrons() [1/2]
size_t num_tetrahedrons () const inline inherited
num_tetrahedrons() [2/2]
size_t num_tetrahedrons (int unnamed) const inline
Parameters
[in] unnamed
num_triangles() [1/2]
size_t num_triangles () const inline inherited
num_triangles() [2/2]
size_t num_triangles (int unnamed) const inline
Parameters
[in] unnamed
num_vertices() [1/2]
size_t num_vertices () const inline inherited
References Grid::num_vertices().
num_vertices() [2/2]
size_t num_vertices (int unnamed) const inline
Parameters
[in] unnamed
References Grid::num_vertices().
num_volumes() [1/2]
size_t num_volumes () const inline inherited
References Grid::num_volumes().
num_volumes() [2/2]
size_t num_volumes (int unnamed) const inline
Parameters
[in] unnamed
References Grid::num_volumes().
reserve_edges()
void reserve_edges (size_t num) inline inherited
Parameters
[in] num
reserve_faces()
void reserve_faces (size_t num) inline inherited
Parameters
[in] num
reserve_vertices()
void reserve_vertices (size_t num) inline inherited
Parameters
[in] num
reserve_volumes()
void reserve_volumes (size_t num) inline inherited
Parameters
[in] num