Registry: ProjectionHandler Class Reference
ProjectionHandler Class Reference
Public Member Functions
SmartPtr< IGeometry > geometry () const
ProjectionHandler ()
ProjectionHandler (ISubsetHandler *unnamed)
ProjectionHandler (SmartPtr< ISubsetHandler > unnamed)
ProjectionHandler (SmartPtr< IGeometry > unnamed, ISubsetHandler *unnamed)
ProjectionHandler (SmartPtr< IGeometry > unnamed, SmartPtr< ISubsetHandler > unnamed)
void set_geometry (SmartPtr< IGeometry > geometry)
void set_geometry_all (SmartPtr< IGeometry > geometry)
void set_projector (int subsetIndex, SmartPtr< RefinementProjector > projector)
Constructor & Destructor Documentation
ProjectionHandler() [1/5]
ProjectionHandler ()
ProjectionHandler() [2/5]
ProjectionHandler (ISubsetHandler * unnamed)
Parameters
[in] unnamed
ProjectionHandler() [3/5]
ProjectionHandler (SmartPtr< ISubsetHandler > unnamed)
Parameters
[in] unnamed
ProjectionHandler() [4/5]
ProjectionHandler (SmartPtr< IGeometry > unnamed, ISubsetHandler * unnamed)
Parameters
[in] unnamed
[in] unnamed
ProjectionHandler() [5/5]
ProjectionHandler (SmartPtr< IGeometry > unnamed, SmartPtr< ISubsetHandler > unnamed)
Parameters
[in] unnamed
[in] unnamed
Member Function Documentation
geometry()
SmartPtr<IGeometry> geometry () const inline inherited
Returns
geometry
References RefinementProjector::geometry().
set_geometry()
void set_geometry (SmartPtr< IGeometry > geometry) inline inherited
Parameters
[in] geometry
References RefinementProjector::set_geometry().
set_geometry_all()
void set_geometry_all (SmartPtr< IGeometry > geometry) inline
Parameters
[in] geometry
References ProjectionHandler::set_geometry_all().
set_projector()
void set_projector (int subsetIndex, SmartPtr< RefinementProjector > projector) inline
Parameters
[in] subsetIndex
[in] projector
References ProjectionHandler::set_projector().