Registry: Grid Class Reference
Grid Class Reference
Public Member Functions
void clear ()
void clear_geometry ()
Grid ()
size_t num_edges () const
size_t num_faces () const
size_t num_hexahedrons () const
size_t num_prisms () const
size_t num_pyramids () const
size_t num_quadrilaterals () const
size_t num_tetrahedrons () const
size_t num_triangles () const
size_t num_vertices () const
size_t num_volumes () const
void reserve_edges (size_t num)
void reserve_faces (size_t num)
void reserve_vertices (size_t num)
void reserve_volumes (size_t num)
Constructor & Destructor Documentation
Grid()
Grid ()
Member Function Documentation
clear()
void clear () inline
References Grid::clear().
clear_geometry()
void clear_geometry () inline
References Grid::clear_geometry().
num_edges()
size_t num_edges () const inline
References Grid::num_edges().
num_faces()
size_t num_faces () const inline
References Grid::num_faces().
num_hexahedrons()
size_t num_hexahedrons () const inline
num_prisms()
size_t num_prisms () const inline
num_pyramids()
size_t num_pyramids () const inline
num_quadrilaterals()
size_t num_quadrilaterals () const inline
num_tetrahedrons()
size_t num_tetrahedrons () const inline
num_triangles()
size_t num_triangles () const inline
num_vertices()
size_t num_vertices () const inline
References Grid::num_vertices().
num_volumes()
size_t num_volumes () const inline
References Grid::num_volumes().
reserve_edges()
void reserve_edges (size_t num) inline
Parameters
[in] num
reserve_faces()
void reserve_faces (size_t num) inline
Parameters
[in] num
reserve_vertices()
void reserve_vertices (size_t num) inline
Parameters
[in] num
reserve_volumes()
void reserve_volumes (size_t num) inline
Parameters
[in] num