Registry: SymmetricBlockGaussSeidelIterative Class Reference
SymmetricBlockGaussSeidelIterative Class Reference
SymmetricBlockGaussSeidelIterative.
Public Member Functions
bool apply (Vector *unnamed, const Vector *unnamed)
bool apply_update_defect (Vector *unnamed, Vector *unnamed)
SmartPtr< ILinearIterator > clone ()
returns a clone of the object which can be modified independently
std::string config_string () const
string to display configuration of the linear iterator
bool init (SmartPtr< ILinearOperator > unnamed)
const char * name () const
void set_damp (double damp)
set the damping to a number
void set_depth (size_t unnamed)
void set_iterative_steps (size_t unnamed)
SymmetricBlockGaussSeidelIterative ()
SymmetricBlockGaussSeidelIterative (int depth, int steps)
Detailed Description
SymmetricBlockGaussSeidelIterative.
Note
default specialization is SymmetricBlockGaussSeidelIterativeCPU1
See also
ug::SymmetricBlockGaussSeidelIterative
Constructor & Destructor Documentation
SymmetricBlockGaussSeidelIterative ()
SymmetricBlockGaussSeidelIterative (int depth, int steps)
Parameters
[in] depth
[in] steps
Member Function Documentation
bool apply (Vector * unnamed, const Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply().
bool apply_update_defect (Vector * unnamed, Vector * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ILinearIterator< X, Y >::apply_update_defect().
SmartPtr<ILinearIterator> clone () inline inherited
returns a clone of the object which can be modified independently
Returns
SmartPointer to a copy of this object
References ILinearIterator< X, Y >::clone().
std::string config_string () const inline inherited
string to display configuration of the linear iterator
Returns
strConfiguration
References ILinearIterator< X, Y >::config_string().
bool init (SmartPtr< ILinearOperator > unnamed) inline inherited
Parameters
[in] unnamed
References ILinearIterator< X, Y >::init().
const char* name () const inline inherited
References ILinearIterator< X, Y >::name().
void set_damp (double damp) inline inherited
set the damping to a number
Parameters
[in] damp
References ILinearIterator< X, Y >::set_damp().
void set_depth (size_t unnamed) inline
Parameters
[in] unnamed
void set_iterative_steps (size_t unnamed) inline
Parameters
[in] unnamed