Registry: IConvergenceCheck Class Reference
IConvergenceCheck Class Reference
Public Member Functions
double avg_rate () const
std::string config_string () const
double defect () const
returns the current defect
bool iteration_ended ()
double reduction () const
returns the current relative reduction
int step () const
returns the current number of steps
Private Member Functions
IConvergenceCheck ()=delete
Constructor hidden / deactivated.
Detailed Description
Note
default specialization is IConvergenceCheckCPU1
See also
ug::IConvergenceCheck
Constructor & Destructor Documentation
IConvergenceCheck () private delete
Constructor hidden / deactivated.
Member Function Documentation
double avg_rate () const inline
References IConvergenceCheck< TVector >::avg_rate().
std::string config_string () const inline
References IConvergenceCheck< TVector >::config_string().
double defect () const inline
returns the current defect
Returns
defect
References IConvergenceCheck< TVector >::defect().
bool iteration_ended () inline
References IConvergenceCheck< TVector >::iteration_ended().
double reduction () const inline
returns the current relative reduction
Returns
reduction
References IConvergenceCheck< TVector >::reduction().
int step () const inline
returns the current number of steps
Returns
step
References IConvergenceCheck< TVector >::step().