Registry: LogAssistant Class Reference
LogAssistant Class Reference
Public Member Functions
bool enable_file_output (bool bEnable, const char *filename)
Please note that only the filename given at the first call is considered.
bool enable_terminal_output (bool bEnable)
enables or disables terminal output (enabled by default)
void flush ()
flush all buffers, especially the file buffer.
std::string get_debug_IDs ()
int get_debug_level (const char *tag) const
gets the debug level of Tag 'tag'
int get_output_process ()
Returns the process which outputs its data.
void is_output_process (int procRank)
Returns whether the process outputs its data.
bool rename_log_file (const char *filename)
Renames previously opened logfile to the name given.
bool set_debug_level (const char *tag, int lev)
sets the debug level of Tag 'tag' to level 'lev'
bool set_debug_levels (int lev)
sets the debug level of all tags to 'lev'
void set_output_process (int procRank)
Sets the process which shall output its data.
Private Member Functions
LogAssistant ()=delete
Constructor hidden / deactivated.
Constructor & Destructor Documentation
LogAssistant()
LogAssistant () private delete
Constructor hidden / deactivated.
Member Function Documentation
enable_file_output()
bool enable_file_output (bool bEnable, const char * filename) inline
Please note that only the filename given at the first call is considered.
Parameters
[in] bEnable
[in] filename
References LogAssistant::enable_file_output().
enable_terminal_output()
bool enable_terminal_output (bool bEnable) inline
enables or disables terminal output (enabled by default)
Parameters
[in] bEnable
References LogAssistant::enable_terminal_output().
flush()
void flush () inline
flush all buffers, especially the file buffer.
References LogAssistant::flush().
get_debug_IDs()
std::string get_debug_IDs () inline
Returns
debug IDs
get_debug_level()
int get_debug_level (const char * tag) const inline
gets the debug level of Tag 'tag'
Parameters
[in] tag
References LogAssistant::get_debug_level().
get_output_process()
int get_output_process () inline
Returns the process which outputs its data.
References LogAssistant::get_output_process().
is_output_process()
void is_output_process (int procRank) inline
Returns whether the process outputs its data.
Parameters
[in] procRank
References LogAssistant::is_output_process().
rename_log_file()
bool rename_log_file (const char * filename) inline
Renames previously opened logfile to the name given.
Parameters
[in] filename
References LogAssistant::rename_log_file().
set_debug_level()
bool set_debug_level (const char * tag, int lev) inline
sets the debug level of Tag 'tag' to level 'lev'
Parameters
[in] tag
[in] lev
References LogAssistant::set_debug_level().
set_debug_levels()
bool set_debug_levels (int lev) inline
sets the debug level of all tags to 'lev'
Parameters
[in] lev
References LogAssistant::set_debug_levels().
set_output_process()
void set_output_process (int procRank) inline
Sets the process which shall output its data.
Parameters
[in] procRank
References LogAssistant::set_output_process().