Registry: EnergyConvCheck Class Reference
EnergyConvCheck Class Reference
Energy Convergence Check.
Public Member Functions
double avg_rate () const
std::string config_string () const
double defect () const
returns the current defect
EnergyConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction, bool Verbosity)
EnergyConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction, bool Verbositysupress_unsuccessful_return, bool unnamed)
EnergyConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction)
bool iteration_ended ()
double reduction () const
returns the current relative reduction
void set_linear_operator (SmartPtr< ILinearOperator > unnamed)
int step () const
returns the current number of steps
Detailed Description
Energy Convergence Check.
Note
default specialization is EnergyConvCheckCPU1
See also
ug::EnergyConvCheck
Constructor & Destructor Documentation
EnergyConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction, bool Verbosity)
Parameters
[in] Maximum_Steps
[in] Minimum_Defect
[in] Relative_Reduction
[in] Verbosity
EnergyConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction, bool Verbositysupress_unsuccessful_return, bool unnamed)
Parameters
[in] Maximum_Steps
[in] Minimum_Defect
[in] Relative_Reduction
[in] Verbositysupress_unsuccessful_return
[in] unnamed
EnergyConvCheck (int Maximum_Steps, double Minimum_Defect, double Relative_Reduction)
Parameters
[in] Maximum_Steps
[in] Minimum_Defect
[in] Relative_Reduction
Member Function Documentation
double avg_rate () const inline inherited
References IConvergenceCheck< TVector >::avg_rate().
std::string config_string () const inline inherited
References IConvergenceCheck< TVector >::config_string().
double defect () const inline inherited
returns the current defect
Returns
defect
References IConvergenceCheck< TVector >::defect().
bool iteration_ended () inline inherited
References IConvergenceCheck< TVector >::iteration_ended().
double reduction () const inline inherited
returns the current relative reduction
Returns
reduction
References IConvergenceCheck< TVector >::reduction().
void set_linear_operator (SmartPtr< ILinearOperator > unnamed) inline
Parameters
[in] unnamed
References EnergyConvCheck< class >::set_linear_operator().
int step () const inline inherited
returns the current number of steps
Returns
step
References IConvergenceCheck< TVector >::step().