Registry: StandardLineSearch Class Reference
StandardLineSearch Class Reference
Public Member Functions
void set_accept_best (bool bAcceptBest)
void set_check_all (bool bCheckAll)
void set_lambda_start (double start)
void set_maximum_defect (double maxDef)
void set_maximum_steps (int steps)
void set_offset (std::string strOffset)
void set_reduce_factor (double factor)
void set_suff_descent_factor (double factor)
void set_verbose (bool verboseLevel)
StandardLineSearch ()
StandardLineSearch (int unnamed, double unnamed, double unnamed, bool unnamed)
StandardLineSearch (int unnamed, double unnamed, double unnamed, bool unnamed, bool unnamed)
Detailed Description
Note
default specialization is StandardLineSearchCPU1
See also
ug::StandardLineSearch
Constructor & Destructor Documentation
StandardLineSearch() [1/3]
StandardLineSearch ()
StandardLineSearch() [2/3]
StandardLineSearch (int unnamed, double unnamed, double unnamed, bool unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
StandardLineSearch() [3/3]
StandardLineSearch (int unnamed, double unnamed, double unnamed, bool unnamed, bool unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
Member Function Documentation
set_accept_best()
void set_accept_best (bool bAcceptBest) inline
Parameters
[in] bAcceptBest
References StandardLineSearch< class >::set_accept_best().
set_check_all()
void set_check_all (bool bCheckAll) inline
Parameters
[in] bCheckAll
References StandardLineSearch< class >::set_check_all().
set_lambda_start()
void set_lambda_start (double start) inline
Parameters
[in] start
References StandardLineSearch< class >::set_lambda_start().
set_maximum_defect()
void set_maximum_defect (double maxDef) inline
Parameters
[in] maxDef
References StandardLineSearch< class >::set_maximum_defect().
set_maximum_steps()
void set_maximum_steps (int steps) inline
Parameters
[in] steps
References StandardLineSearch< class >::set_maximum_steps().
set_offset()
void set_offset (std::string strOffset) inline
Parameters
[in] strOffset
References StandardLineSearch< class >::set_offset().
set_reduce_factor()
void set_reduce_factor (double factor) inline
Parameters
[in] factor
References StandardLineSearch< class >::set_reduce_factor().
set_suff_descent_factor()
void set_suff_descent_factor (double factor) inline
Parameters
[in] factor
References StandardLineSearch< class >::set_suff_descent_factor().
set_verbose()
void set_verbose (bool verboseLevel) inline
Parameters
[in] verboseLevel
References StandardLineSearch< class >::set_verbose().