Registry: ISubsetHandler Class Reference
ISubsetHandler Class Reference
Public Member Functions
void assign_subset (Vertex *unnamed, int unnamed)
void get_default_subset_index (int unnamed)
int get_subset_index (Vertex *unnamed) const
const char * get_subset_name (int subsetIndex) const
int num_subsets () const
void set_default_subset_index (int subsetIndex)
void set_subset_name (const char *name, int subsetIndex)
Private Member Functions
ISubsetHandler ()=delete
Constructor hidden / deactivated.
Constructor & Destructor Documentation
ISubsetHandler()
ISubsetHandler () private delete
Constructor hidden / deactivated.
Member Function Documentation
assign_subset()
void assign_subset (Vertex * unnamed, int unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References ISubsetHandler::assign_subset().
get_default_subset_index()
void get_default_subset_index (int unnamed) inline
Parameters
[in] unnamed
References ISubsetHandler::get_default_subset_index().
get_subset_index()
int get_subset_index (Vertex * unnamed) const inline
Parameters
[in] unnamed
References ISubsetHandler::get_subset_index().
get_subset_name()
const char* get_subset_name (int subsetIndex) const inline
Parameters
[in] subsetIndex
Returns
subset name
References ISubsetHandler::get_subset_name().
num_subsets()
int num_subsets () const inline
References ISubsetHandler::num_subsets().
set_default_subset_index()
void set_default_subset_index (int subsetIndex) inline
Parameters
[in] subsetIndex
References ISubsetHandler::set_default_subset_index().
set_subset_name()
void set_subset_name (const char * name, int subsetIndex) inline
Parameters
[in] name
[in] subsetIndex
References ISubsetHandler::set_subset_name().