Registry: DoFDistributionInfoProvider Class Reference
DoFDistributionInfoProvider Class Reference
Public Member Functions
int dim (size_t unnamed) const
const LFEID * lfeid (size_t unnamed) const
std::string name (size_t unnamed) const
std::vector< std::string > names () const
size_t num_fct () const
void print_local_dof_statistic (int unnamed) const
Private Member Functions
DoFDistributionInfoProvider ()=delete
Constructor hidden / deactivated.
Constructor & Destructor Documentation
DoFDistributionInfoProvider()
DoFDistributionInfoProvider () private delete
Constructor hidden / deactivated.
Member Function Documentation
dim()
int dim (size_t unnamed) const inline
Parameters
[in] unnamed
References DoFDistributionInfoProvider::dim().
lfeid()
const LFEID* lfeid (size_t unnamed) const inline
Parameters
[in] unnamed
References DoFDistributionInfoProvider::lfeid().
name()
std::string name (size_t unnamed) const inline
Parameters
[in] unnamed
References DoFDistributionInfoProvider::name().
names()
std::vector< std::string > names () const inline
References DoFDistributionInfoProvider::names().
num_fct()
size_t num_fct () const inline
References DoFDistributionInfoProvider::num_fct().
print_local_dof_statistic()
void print_local_dof_statistic (int unnamed) const inline
Parameters
[in] unnamed
References DoFDistributionInfoProvider::print_local_dof_statistic().