Registry: IRefiner Class Reference
IRefiner Class Reference
Public Member Functions
void clear_marks ()
bool coarsen ()
void enable_debugging (bool unnamed)
void mark_neighborhood (size_t numIterations)
size_t num_marked_edges ()
size_t num_marked_elements ()
size_t num_marked_faces ()
size_t num_marked_volumes ()
void refine ()
bool save_marks_to_file (const char *filename)
void set_adjusted_marks_debug_filename (const char *filename)
void set_projector (SmartPtr< RefinementProjector > unnamed)
Private Member Functions
IRefiner ()=delete
Constructor hidden / deactivated.
Constructor & Destructor Documentation
IRefiner()
IRefiner () private delete
Constructor hidden / deactivated.
Member Function Documentation
clear_marks()
void clear_marks () inline
References IRefiner::clear_marks().
coarsen()
bool coarsen () inline
References IRefiner::coarsen().
enable_debugging()
void enable_debugging (bool unnamed) inline
Parameters
[in] unnamed
References IRefiner::enable_debugging().
mark_neighborhood()
void mark_neighborhood (size_t numIterations) inline
Parameters
[in] numIterations
References IRefiner::mark_neighborhood().
num_marked_edges()
size_t num_marked_edges () inline
References IRefiner::num_marked_edges().
num_marked_elements()
size_t num_marked_elements () inline
References IRefiner::num_marked_elements().
num_marked_faces()
size_t num_marked_faces () inline
References IRefiner::num_marked_faces().
num_marked_volumes()
size_t num_marked_volumes () inline
References IRefiner::num_marked_volumes().
refine()
void refine () inline
References IRefiner::refine().
save_marks_to_file()
bool save_marks_to_file (const char * filename) inline
Parameters
[in] filename
References IRefiner::save_marks_to_file().
set_adjusted_marks_debug_filename()
void set_adjusted_marks_debug_filename (const char * filename) inline
Parameters
[in] filename
References IRefiner::set_adjusted_marks_debug_filename().
set_projector()
void set_projector (SmartPtr< RefinementProjector > unnamed) inline
Parameters
[in] unnamed
References IRefiner::set_projector().