Registry: BinghamViscosityLinker Class Reference
BinghamViscosityLinker Class Reference
Public Member Functions
BinghamViscosityLinker ()
int get_dim () const
void set_density (double unnamed)
void set_velocity_gradient (SmartPtr< CplUserMatrix > unnamed)
void set_viscosity (double unnamed)
void set_yield_stress (double unnamed)
std::string type () const
Detailed Description
Note
default specialization is BinghamViscosityLinker2d
See also
ug::BinghamViscosityLinker
Constructor & Destructor Documentation
BinghamViscosityLinker()
BinghamViscosityLinker ()
Member Function Documentation
get_dim()
int get_dim () const inline inherited
References get_dim().
set_density()
void set_density (double unnamed) inline
Parameters
[in] unnamed
References BinghamViscosityLinker< dim >::set_density().
set_velocity_gradient()
void set_velocity_gradient (SmartPtr< CplUserMatrix > unnamed) inline
Parameters
[in] unnamed
References BinghamViscosityLinker< dim >::set_velocity_gradient().
set_viscosity()
void set_viscosity (double unnamed) inline
Parameters
[in] unnamed
References BinghamViscosityLinker< dim >::set_viscosity().
set_yield_stress()
void set_yield_stress (double unnamed) inline
Parameters
[in] unnamed
References BinghamViscosityLinker< dim >::set_yield_stress().
type()
std::string type () const inline inherited
References type().