Registry: IElementMarkingStrategy Class Reference
IElementMarkingStrategy Class Reference
Public Member Functions
double global_estimated_error () const
double global_estimated_error_per_elem_max () const
double global_estimated_error_per_elem_min () const
Private Member Functions
IElementMarkingStrategy ()=delete
Constructor hidden / deactivated.
Detailed Description
Note
default specialization is IElementMarkingStrategy2d
See also
ug::IElementMarkingStrategy
Constructor & Destructor Documentation
IElementMarkingStrategy()
IElementMarkingStrategy () private delete
Constructor hidden / deactivated.
Member Function Documentation
global_estimated_error()
double global_estimated_error () const inline
References IElementMarkingStrategy< class >::global_estimated_error().
global_estimated_error_per_elem_max()
double global_estimated_error_per_elem_max () const inline
References IElementMarkingStrategy< class >::global_estimated_error_per_elem_max().
global_estimated_error_per_elem_min()
double global_estimated_error_per_elem_min () const inline
References IElementMarkingStrategy< class >::global_estimated_error_per_elem_min().