Registry: DomainInfo Class Reference
DomainInfo Class Reference
Public Member Functions
DomainInfo ()
int element_type () const
size_t num_elements () const
size_t num_elements_on_level (size_t unnamed) const
size_t num_levels () const
size_t num_local_elements_on_level (size_t unnamed) const
size_t num_local_ghosts_on_level (size_t unnamed) const
size_t num_subsets () const
size_t num_surface_elements () const
size_t subset_dim (int unnamed) const
std::string to_string () const
Constructor & Destructor Documentation
DomainInfo()
DomainInfo ()
Member Function Documentation
element_type()
int element_type () const inline
References DomainInfo::element_type().
num_elements()
size_t num_elements () const inline
References DomainInfo::num_elements().
num_elements_on_level()
size_t num_elements_on_level (size_t unnamed) const inline
Parameters
[in] unnamed
References DomainInfo::num_elements_on_level().
num_levels()
size_t num_levels () const inline
References DomainInfo::num_levels().
num_local_elements_on_level()
size_t num_local_elements_on_level (size_t unnamed) const inline
Parameters
[in] unnamed
References DomainInfo::num_local_elements_on_level().
num_local_ghosts_on_level()
size_t num_local_ghosts_on_level (size_t unnamed) const inline
Parameters
[in] unnamed
References DomainInfo::num_local_ghosts_on_level().
num_subsets()
size_t num_subsets () const inline
References DomainInfo::num_subsets().
num_surface_elements()
size_t num_surface_elements () const inline
References DomainInfo::num_surface_elements().
subset_dim()
size_t subset_dim (int unnamed) const inline
Parameters
[in] unnamed
References DomainInfo::subset_dim().
to_string()
std::string to_string () const inline
References DomainInfo::to_string().