Registry: IComponentSpace Class Reference
IComponentSpace Class Reference
Public Member Functions
std::string config_string () const
double distance (GridFunction *unnamed, GridFunction *unnamed)
double norm (GridFunction *unnamed)
Private Member Functions
IComponentSpace ()=delete
Constructor hidden / deactivated.
Detailed Description
Note
default specialization is IComponentSpace2dCPU1
See also
ug::IComponentSpace
Constructor & Destructor Documentation
IComponentSpace()
IComponentSpace () private delete
Constructor hidden / deactivated.
Member Function Documentation
config_string()
std::string config_string () const inline inherited
References IGridFunctionSpace< TGridFunction >::config_string().
distance()
double distance (GridFunction * unnamed, GridFunction * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References IComponentSpace< class >::distance().
norm()
double norm (GridFunction * unnamed) inline
Parameters
[in] unnamed
References IComponentSpace< class >::norm().