Registry: L2QuotientSpace Class Reference
L2QuotientSpace Class Reference
Public Member Functions
std::string config_string () const
double distance (GridFunction *unnamed, GridFunction *unnamed)
L2QuotientSpace (const char *fctNames)
L2QuotientSpace (const char *fctNames, _order, int unnamed)
L2QuotientSpace (const char *fctNames, _order, _weight, int unnamed, double unnamed)
L2QuotientSpace (const char *fctNames, _order, _weight, _ssNames, int unnamed, double unnamed, const char *unnamed)
L2QuotientSpace (const char *fctNames, _order, _weight, int unnamed, ConstSmartPtr< UserNumber > unnamed)
L2QuotientSpace (const char *fctNames, _order, _weight, _ssNames, int unnamed, ConstSmartPtr< UserNumber > unnamed, const char *unnamed)
double norm (GridFunction *unnamed)
Detailed Description
Note
default specialization is L2QuotientSpace2dCPU1
See also
ug::L2QuotientSpace
Constructor & Destructor Documentation
L2QuotientSpace() [1/6]
L2QuotientSpace (const char * fctNames)
Parameters
[in] fctNames
L2QuotientSpace() [2/6]
L2QuotientSpace (const char * fctNames, _order , int unnamed)
Parameters
[in] fctNames,_order
[in] unnamed
L2QuotientSpace() [3/6]
L2QuotientSpace (const char * fctNames, _order , _weight , int unnamed, double unnamed)
Parameters
[in] fctNames,_order,_weight
[in] unnamed
[in] unnamed
L2QuotientSpace() [4/6]
L2QuotientSpace (const char * fctNames, _order , _weight , _ssNames , int unnamed, double unnamed, const char * unnamed)
Parameters
[in] fctNames,_order,_weight,_ssNames
[in] unnamed
[in] unnamed
[in] unnamed
L2QuotientSpace() [5/6]
L2QuotientSpace (const char * fctNames, _order , _weight , int unnamed, ConstSmartPtr< UserNumber > unnamed)
Parameters
[in] fctNames,_order,_weight
[in] unnamed
[in] unnamed
L2QuotientSpace() [6/6]
L2QuotientSpace (const char * fctNames, _order , _weight , _ssNames , int unnamed, ConstSmartPtr< UserNumber > unnamed, const char * unnamed)
Parameters
[in] fctNames,_order,_weight,_ssNames
[in] unnamed
[in] unnamed
[in] unnamed
Member Function Documentation
config_string()
std::string config_string () const inline inherited
References IGridFunctionSpace< TGridFunction >::config_string().
distance()
double distance (GridFunction * unnamed, GridFunction * unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References IComponentSpace< class >::distance().
norm()
double norm (GridFunction * unnamed) inline inherited
Parameters
[in] unnamed
References IComponentSpace< class >::norm().