Registry: Heightfield Class Reference
Heightfield Class Reference
2d raster with number values
Public Member Functions
void blur (double alpha, _iterations, size_t unnamed)
Smoothens the field by adjusting the value of each pixel towards the average of its neighbours.
bool eliminate_invalid_cells ()
eliminates invalid cells by repeatedly filling those cells with averages of neighboring cells
Heightfield ()
double interpolate (double x, double y) const
returns the height at the given coordinate using piecewise constant interpolation
double no_data_value () const
returns the value which represents an invalid height
Detailed Description
2d raster with number values
Constructor & Destructor Documentation
Heightfield()
Heightfield ()
Member Function Documentation
blur()
void blur (double alpha, _iterations , size_t unnamed) inline
Smoothens the field by adjusting the value of each pixel towards the average of its neighbours.
Parameters
[in] alpha,_iterations
[in] unnamed
References alpha, and Heightfield::blur().
eliminate_invalid_cells()
bool eliminate_invalid_cells () inline
eliminates invalid cells by repeatedly filling those cells with averages of neighboring cells
Returns
success
References Heightfield::eliminate_invalid_cells().
interpolate()
double interpolate (double x, double y) const inline
returns the height at the given coordinate using piecewise constant interpolation
Parameters
[in] x
[in] y
Returns
height
References Heightfield::interpolate().
no_data_value()
double no_data_value () const inline
returns the value which represents an invalid height
Returns
noDataValue
References Heightfield::no_data_value().