Registry: SkinMaterialLaw Class Reference
SkinMaterialLaw Class Reference
Public Member Functions
void set_hooke_elasticity_tensor (double lambda, double mu)
void set_hooke_elasticity_tensor_E_nu (double E, double nu)
void set_hooke_elasticity_tensor_plain_strain_E_nu (double E, double nu)
void set_hooke_elasticity_tensor_plain_stress_E_nu (double E, double nu)
SkinMaterialLaw ()
Detailed Description
Note
default specialization is SkinMaterialLaw2d
See also
ug::SkinMaterialLaw
Constructor & Destructor Documentation
SkinMaterialLaw()
SkinMaterialLaw ()
Member Function Documentation
set_hooke_elasticity_tensor()
void set_hooke_elasticity_tensor (double lambda, double mu) inline
Parameters
[in] lambda
[in] mu
References mu, and set_hooke_elasticity_tensor().
set_hooke_elasticity_tensor_E_nu()
void set_hooke_elasticity_tensor_E_nu (double E, double nu) inline
Parameters
[in] E
[in] nu
References set_hooke_elasticity_tensor_E_nu().
set_hooke_elasticity_tensor_plain_strain_E_nu()
void set_hooke_elasticity_tensor_plain_strain_E_nu (double E, double nu) inline
Parameters
[in] E
[in] nu
References set_hooke_elasticity_tensor_plain_strain_E_nu().
set_hooke_elasticity_tensor_plain_stress_E_nu()
void set_hooke_elasticity_tensor_plain_stress_E_nu (double E, double nu) inline
Parameters
[in] E
[in] nu
References set_hooke_elasticity_tensor_plain_stress_E_nu().