Registry: Mesh Class Reference
Mesh Class Reference
The Mesh class stores a Grid, SubsetHandler and Selector. Nearly all algorithms in ProMesh operate on Meshes.
Public Member Functions
SubsetHandler * crease_handler ()
Edge * create_edge (Vertex *unnamed, Vertex *unnamed)
Volume * create_hexahedron (Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed)
Volume * create_octahedron (Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed)
Volume * create_prism (Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed)
Volume * create_pyramid (Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed)
Face * create_quadrilateral (Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed)
Volume * create_tetrahedron (Vertex *unnamed, Vertex *unnamed, Vertex *unnamed, Vertex *unnamed)
Face * create_triangle (Vertex *unnamed, Vertex *unnamed, Vertex *unnamed)
Vertex * create_vertex (const Vec3d *unnamed)
SmartPtr< EdgeIterator > edge_begin ()
SmartPtr< EdgeIterator > edge_end ()
SmartPtr< EdgeIterator > edge_selection_begin ()
SmartPtr< EdgeIterator > edge_selection_end ()
SmartPtr< EdgeIterator > edge_subset_begin (int unnamed)
SmartPtr< EdgeIterator > edge_subset_end (int unnamed)
SmartPtr< FaceIterator > face_begin ()
SmartPtr< FaceIterator > face_end ()
SmartPtr< FaceIterator > face_selection_begin ()
SmartPtr< FaceIterator > face_selection_end ()
SmartPtr< FaceIterator > face_subset_begin (int unnamed)
SmartPtr< FaceIterator > face_subset_end (int unnamed)
Grid * grid ()
SmartPtr< VolumeIterator > hexahedron_begin ()
SmartPtr< VolumeIterator > hexahedron_end ()
SmartPtr< VolumeIterator > hexahedron_selection_begin ()
SmartPtr< VolumeIterator > hexahedron_selection_end ()
SmartPtr< VolumeIterator > hexahedron_subset_begin (int unnamed)
SmartPtr< VolumeIterator > hexahedron_subset_end (int unnamed)
Mesh ()
SmartPtr< VolumeIterator > octahedron_begin ()
SmartPtr< VolumeIterator > octahedron_end ()
SmartPtr< VolumeIterator > octahedron_selection_begin ()
SmartPtr< VolumeIterator > octahedron_selection_end ()
SmartPtr< VolumeIterator > octahedron_subset_begin (int unnamed)
SmartPtr< VolumeIterator > octahedron_subset_end (int unnamed)
Vec3d * pivot ()
Vec3d * position (Vertex *unnamed)
APosition3 * position_attachment ()
SmartPtr< VolumeIterator > prism_begin ()
SmartPtr< VolumeIterator > prism_end ()
SmartPtr< VolumeIterator > prism_selection_begin ()
SmartPtr< VolumeIterator > prism_selection_end ()
SmartPtr< VolumeIterator > prism_subset_begin (int unnamed)
SmartPtr< VolumeIterator > prism_subset_end (int unnamed)
SmartPtr< VolumeIterator > pyramid_begin ()
SmartPtr< VolumeIterator > pyramid_end ()
SmartPtr< VolumeIterator > pyramid_selection_begin ()
SmartPtr< VolumeIterator > pyramid_selection_end ()
SmartPtr< VolumeIterator > pyramid_subset_begin (int unnamed)
SmartPtr< VolumeIterator > pyramid_subset_end (int unnamed)
SmartPtr< FaceIterator > quadrilateral_begin ()
SmartPtr< FaceIterator > quadrilateral_end ()
SmartPtr< FaceIterator > quadrilateral_selection_begin ()
SmartPtr< FaceIterator > quadrilateral_selection_end ()
SmartPtr< FaceIterator > quadrilateral_subset_begin (int unnamed)
SmartPtr< FaceIterator > quadrilateral_subset_end (int unnamed)
Selector * selector ()
void set_pivot (const Vec3d *unnamed)
void set_position (Vertex *unnamed, const Vec3d *unnamed)
SubsetHandler * subset_handler ()
SmartPtr< VolumeIterator > tetrahedron_begin ()
SmartPtr< VolumeIterator > tetrahedron_end ()
SmartPtr< VolumeIterator > tetrahedron_selection_begin ()
SmartPtr< VolumeIterator > tetrahedron_selection_end ()
SmartPtr< VolumeIterator > tetrahedron_subset_begin (int unnamed)
SmartPtr< VolumeIterator > tetrahedron_subset_end (int unnamed)
SmartPtr< FaceIterator > triangle_begin ()
SmartPtr< FaceIterator > triangle_end ()
SmartPtr< FaceIterator > triangle_selection_begin ()
SmartPtr< FaceIterator > triangle_selection_end ()
SmartPtr< FaceIterator > triangle_subset_begin (int unnamed)
SmartPtr< FaceIterator > triangle_subset_end (int unnamed)
SmartPtr< VertexIterator > vertex_begin ()
SmartPtr< VertexIterator > vertex_end ()
SmartPtr< VertexIterator > vertex_selection_begin ()
SmartPtr< VertexIterator > vertex_selection_end ()
SmartPtr< VertexIterator > vertex_subset_begin (int unnamed)
SmartPtr< VertexIterator > vertex_subset_end (int unnamed)
SmartPtr< VolumeIterator > volume_begin ()
SmartPtr< VolumeIterator > volume_end ()
SmartPtr< VolumeIterator > volume_selection_begin ()
SmartPtr< VolumeIterator > volume_selection_end ()
SmartPtr< VolumeIterator > volume_subset_begin (int unnamed)
SmartPtr< VolumeIterator > volume_subset_end (int unnamed)
Detailed Description
The Mesh class stores a Grid, SubsetHandler and Selector. Nearly all algorithms in ProMesh operate on Meshes.
Constructor & Destructor Documentation
Mesh()
Mesh ()
Member Function Documentation
crease_handler()
SubsetHandler* crease_handler () inline
create_edge()
Edge* create_edge (Vertex * unnamed, Vertex * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
create_hexahedron()
Volume* create_hexahedron (Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
create_octahedron()
Volume* create_octahedron (Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
create_prism()
Volume* create_prism (Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
create_pyramid()
Volume* create_pyramid (Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
create_quadrilateral()
Face* create_quadrilateral (Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
create_tetrahedron()
Volume* create_tetrahedron (Vertex * unnamed, Vertex * unnamed, Vertex * unnamed, Vertex * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
create_triangle()
Face* create_triangle (Vertex * unnamed, Vertex * unnamed, Vertex * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
create_vertex()
Vertex* create_vertex (const Vec3d * unnamed) inline
Parameters
[in] unnamed
edge_begin()
SmartPtr<EdgeIterator> edge_begin () inline
edge_end()
SmartPtr<EdgeIterator> edge_end () inline
edge_selection_begin()
SmartPtr<EdgeIterator> edge_selection_begin () inline
edge_selection_end()
SmartPtr<EdgeIterator> edge_selection_end () inline
edge_subset_begin()
SmartPtr<EdgeIterator> edge_subset_begin (int unnamed) inline
Parameters
[in] unnamed
edge_subset_end()
SmartPtr<EdgeIterator> edge_subset_end (int unnamed) inline
Parameters
[in] unnamed
face_begin()
SmartPtr<FaceIterator> face_begin () inline
face_end()
SmartPtr<FaceIterator> face_end () inline
face_selection_begin()
SmartPtr<FaceIterator> face_selection_begin () inline
face_selection_end()
SmartPtr<FaceIterator> face_selection_end () inline
face_subset_begin()
SmartPtr<FaceIterator> face_subset_begin (int unnamed) inline
Parameters
[in] unnamed
face_subset_end()
SmartPtr<FaceIterator> face_subset_end (int unnamed) inline
Parameters
[in] unnamed
grid()
Grid* grid () inline
References grid().
hexahedron_begin()
SmartPtr<VolumeIterator> hexahedron_begin () inline
hexahedron_end()
SmartPtr<VolumeIterator> hexahedron_end () inline
hexahedron_selection_begin()
SmartPtr<VolumeIterator> hexahedron_selection_begin () inline
hexahedron_selection_end()
SmartPtr<VolumeIterator> hexahedron_selection_end () inline
hexahedron_subset_begin()
SmartPtr<VolumeIterator> hexahedron_subset_begin (int unnamed) inline
Parameters
[in] unnamed
hexahedron_subset_end()
SmartPtr<VolumeIterator> hexahedron_subset_end (int unnamed) inline
Parameters
[in] unnamed
octahedron_begin()
SmartPtr<VolumeIterator> octahedron_begin () inline
octahedron_end()
SmartPtr<VolumeIterator> octahedron_end () inline
octahedron_selection_begin()
SmartPtr<VolumeIterator> octahedron_selection_begin () inline
octahedron_selection_end()
SmartPtr<VolumeIterator> octahedron_selection_end () inline
octahedron_subset_begin()
SmartPtr<VolumeIterator> octahedron_subset_begin (int unnamed) inline
Parameters
[in] unnamed
octahedron_subset_end()
SmartPtr<VolumeIterator> octahedron_subset_end (int unnamed) inline
Parameters
[in] unnamed
pivot()
Vec3d* pivot () inline
position()
Vec3d* position (Vertex * unnamed) inline
Parameters
[in] unnamed
position_attachment()
APosition3* position_attachment () inline
References position_attachment().
prism_begin()
SmartPtr<VolumeIterator> prism_begin () inline
prism_end()
SmartPtr<VolumeIterator> prism_end () inline
prism_selection_begin()
SmartPtr<VolumeIterator> prism_selection_begin () inline
prism_selection_end()
SmartPtr<VolumeIterator> prism_selection_end () inline
prism_subset_begin()
SmartPtr<VolumeIterator> prism_subset_begin (int unnamed) inline
Parameters
[in] unnamed
prism_subset_end()
SmartPtr<VolumeIterator> prism_subset_end (int unnamed) inline
Parameters
[in] unnamed
pyramid_begin()
SmartPtr<VolumeIterator> pyramid_begin () inline
pyramid_end()
SmartPtr<VolumeIterator> pyramid_end () inline
pyramid_selection_begin()
SmartPtr<VolumeIterator> pyramid_selection_begin () inline
pyramid_selection_end()
SmartPtr<VolumeIterator> pyramid_selection_end () inline
pyramid_subset_begin()
SmartPtr<VolumeIterator> pyramid_subset_begin (int unnamed) inline
Parameters
[in] unnamed
pyramid_subset_end()
SmartPtr<VolumeIterator> pyramid_subset_end (int unnamed) inline
Parameters
[in] unnamed
quadrilateral_begin()
SmartPtr<FaceIterator> quadrilateral_begin () inline
quadrilateral_end()
SmartPtr<FaceIterator> quadrilateral_end () inline
quadrilateral_selection_begin()
SmartPtr<FaceIterator> quadrilateral_selection_begin () inline
quadrilateral_selection_end()
SmartPtr<FaceIterator> quadrilateral_selection_end () inline
quadrilateral_subset_begin()
SmartPtr<FaceIterator> quadrilateral_subset_begin (int unnamed) inline
Parameters
[in] unnamed
quadrilateral_subset_end()
SmartPtr<FaceIterator> quadrilateral_subset_end (int unnamed) inline
Parameters
[in] unnamed
selector()
Selector* selector () inline
set_pivot()
void set_pivot (const Vec3d * unnamed) inline
Parameters
[in] unnamed
set_position()
void set_position (Vertex * unnamed, const Vec3d * unnamed) inline
Parameters
[in] unnamed
[in] unnamed
subset_handler()
SubsetHandler* subset_handler () inline
References subset_handler().
tetrahedron_begin()
SmartPtr<VolumeIterator> tetrahedron_begin () inline
tetrahedron_end()
SmartPtr<VolumeIterator> tetrahedron_end () inline
tetrahedron_selection_begin()
SmartPtr<VolumeIterator> tetrahedron_selection_begin () inline
tetrahedron_selection_end()
SmartPtr<VolumeIterator> tetrahedron_selection_end () inline
tetrahedron_subset_begin()
SmartPtr<VolumeIterator> tetrahedron_subset_begin (int unnamed) inline
Parameters
[in] unnamed
tetrahedron_subset_end()
SmartPtr<VolumeIterator> tetrahedron_subset_end (int unnamed) inline
Parameters
[in] unnamed
triangle_begin()
SmartPtr<FaceIterator> triangle_begin () inline
triangle_end()
SmartPtr<FaceIterator> triangle_end () inline
triangle_selection_begin()
SmartPtr<FaceIterator> triangle_selection_begin () inline
triangle_selection_end()
SmartPtr<FaceIterator> triangle_selection_end () inline
triangle_subset_begin()
SmartPtr<FaceIterator> triangle_subset_begin (int unnamed) inline
Parameters
[in] unnamed
triangle_subset_end()
SmartPtr<FaceIterator> triangle_subset_end (int unnamed) inline
Parameters
[in] unnamed
vertex_begin()
SmartPtr<VertexIterator> vertex_begin () inline
vertex_end()
SmartPtr<VertexIterator> vertex_end () inline
vertex_selection_begin()
SmartPtr<VertexIterator> vertex_selection_begin () inline
vertex_selection_end()
SmartPtr<VertexIterator> vertex_selection_end () inline
vertex_subset_begin()
SmartPtr<VertexIterator> vertex_subset_begin (int unnamed) inline
Parameters
[in] unnamed
vertex_subset_end()
SmartPtr<VertexIterator> vertex_subset_end (int unnamed) inline
Parameters
[in] unnamed
volume_begin()
SmartPtr<VolumeIterator> volume_begin () inline
volume_end()
SmartPtr<VolumeIterator> volume_end () inline
volume_selection_begin()
SmartPtr<VolumeIterator> volume_selection_begin () inline
volume_selection_end()
SmartPtr<VolumeIterator> volume_selection_end () inline
volume_subset_begin()
SmartPtr<VolumeIterator> volume_subset_begin (int unnamed) inline
Parameters
[in] unnamed
volume_subset_end()
SmartPtr<VolumeIterator> volume_subset_end (int unnamed) inline
Parameters
[in] unnamed