Registry: GridFunctionDebugWriter Class Reference
GridFunctionDebugWriter Class Reference
Public Member Functions
GridFunctionDebugWriter (SmartPtr< ApproximationSpace > unnamed)
void reset ()
void set_conn_viewer_indices (bool bIndicesOutput)
void set_conn_viewer_output (bool bCVOutput)
void set_grid_level (const GridLevel *GridLevel)
void set_print_consistent (bool printConsistent)
void set_vtk_output (bool bVtkOutput)
Detailed Description
Note
default specialization is GridFunctionDebugWriter2dCPU1
See also
ug::GridFunctionDebugWriter
Constructor & Destructor Documentation
GridFunctionDebugWriter()
GridFunctionDebugWriter (SmartPtr< ApproximationSpace > unnamed)
Parameters
[in] unnamed
Member Function Documentation
reset()
void reset () inline
References GridFunctionDebugWriter< class, class >::reset().
set_conn_viewer_indices()
void set_conn_viewer_indices (bool bIndicesOutput) inline
Parameters
[in] bIndicesOutput
References GridFunctionDebugWriter< class, class >::set_conn_viewer_indices().
set_conn_viewer_output()
void set_conn_viewer_output (bool bCVOutput) inline
Parameters
[in] bCVOutput
References GridFunctionDebugWriter< class, class >::set_conn_viewer_output().
set_grid_level()
void set_grid_level (const GridLevel * GridLevel) inline
Parameters
[in] GridLevel
References GridFunctionDebugWriter< class, class >::set_grid_level().
set_print_consistent()
void set_print_consistent (bool printConsistent) inline
Parameters
[in] printConsistent
References GridFunctionDebugWriter< class, class >::set_print_consistent().
set_vtk_output()
void set_vtk_output (bool bVtkOutput) inline
Parameters
[in] bVtkOutput
References GridFunctionDebugWriter< class, class >::set_vtk_output().