Registry: MatrixDiagonal Class Reference
MatrixDiagonal Class Reference
Public Member Functions
void apply (Vector *unnamed, const Vector *unnamed)
calculates f = Op(u)
void apply_sub (Vector *unnamed, const Vector *unnamed)
calculates f -= Op(u)
void init ()
MatrixDiagonal (SmartPtr< MatrixOperator > unnamed)
Detailed Description
Note
default specialization is MatrixDiagonalCPU1
See also
ug::MatrixDiagonal
Constructor & Destructor Documentation
MatrixDiagonal()
MatrixDiagonal (SmartPtr< MatrixOperator > unnamed)
Parameters
[in] unnamed
Member Function Documentation
apply()
void apply (Vector * unnamed, const Vector * unnamed) inline inherited
calculates f = Op(u)
Parameters
[in] unnamed
[in] unnamed
References ILinearOperator< X, Y >::apply().
apply_sub()
void apply_sub (Vector * unnamed, const Vector * unnamed) inline inherited
calculates f -= Op(u)
Parameters
[in] unnamed
[in] unnamed
References ILinearOperator< X, Y >::apply_sub().
init()
void init () inline inherited
References ILinearOperator< X, Y >::init().