Registry: GlobalMultiGridRefiner Class Reference
GlobalMultiGridRefiner Class Reference
Public Member Functions
void assign_grid (MultiGrid *mg)
void clear_marks ()
bool coarsen ()
void enable_debugging (bool unnamed)
GlobalMultiGridRefiner ()
void mark_neighborhood (size_t numIterations)
size_t num_marked_edges ()
size_t num_marked_elements ()
size_t num_marked_faces ()
size_t num_marked_volumes ()
void refine ()
bool save_marks_to_file (const char *filename)
void set_adjusted_marks_debug_filename (const char *filename)
void set_refinement_callback (IRefinementCallback *unnamed)
Constructor & Destructor Documentation
GlobalMultiGridRefiner ()
Member Function Documentation
void assign_grid (MultiGrid * mg) inline
Parameters
[in] mg
References GlobalMultiGridRefiner::assign_grid().
void clear_marks () inline inherited
References IRefiner::clear_marks().
bool coarsen () inline inherited
References IRefiner::coarsen().
void enable_debugging (bool unnamed) inline inherited
Parameters
[in] unnamed
References IRefiner::enable_debugging().
void mark_neighborhood (size_t numIterations) inline inherited
Parameters
[in] numIterations
References IRefiner::mark_neighborhood().
size_t num_marked_edges () inline inherited
References IRefiner::num_marked_edges().
size_t num_marked_elements () inline inherited
References IRefiner::num_marked_elements().
size_t num_marked_faces () inline inherited
References IRefiner::num_marked_faces().
size_t num_marked_volumes () inline inherited
References IRefiner::num_marked_volumes().
void refine () inline inherited
References IRefiner::refine().
bool save_marks_to_file (const char * filename) inline inherited
Parameters
[in] filename
References IRefiner::save_marks_to_file().
void set_adjusted_marks_debug_filename (const char * filename) inline inherited
Parameters
[in] filename
References IRefiner::set_adjusted_marks_debug_filename().
void set_refinement_callback (IRefinementCallback * unnamed) inline inherited
Parameters
[in] unnamed
References IRefiner::set_refinement_callback().