Registry: ITimeDiscretization Class Reference
ITimeDiscretization Class Reference
Public Member Functions
void finish_step (SmartPtr< SolutionTimeSeries > unnamed)
finishes the assembling of defect/Jacobian for a time step
void finish_step_elem (SmartPtr< SolutionTimeSeries > unnamed)
double future_time () const
size_t num_prev_steps () const
size_t num_stages () const
void prepare_step (SmartPtr< SolutionTimeSeries > unnamed, double unnamed)
prepares the assembling of defect/Jacobian for a time step
void prepare_step_elem (SmartPtr< SolutionTimeSeries > unnamed, double unnamed)
void set_stage (size_t stage)
Private Member Functions
ITimeDiscretization ()=delete
Constructor hidden / deactivated.
Detailed Description
Note
default specialization is ITimeDiscretizationCPU1
See also
ug::ITimeDiscretization
Constructor & Destructor Documentation
ITimeDiscretization()
ITimeDiscretization () private delete
Constructor hidden / deactivated.
Member Function Documentation
finish_step()
void finish_step (SmartPtr< SolutionTimeSeries > unnamed) inline
finishes the assembling of defect/Jacobian for a time step
Parameters
[in] unnamed
References ITimeDiscretization< class >::finish_step().
finish_step_elem()
void finish_step_elem (SmartPtr< SolutionTimeSeries > unnamed) inline
Parameters
[in] unnamed
References ITimeDiscretization< class >::finish_step_elem().
future_time()
double future_time () const inline
Returns
the future time point (i.e. the one that will be computed)
References ITimeDiscretization< class >::future_time().
num_prev_steps()
size_t num_prev_steps () const inline
References ITimeDiscretization< class >::num_prev_steps().
num_stages()
size_t num_stages () const inline
Returns
the number of stages
References ITimeDiscretization< class >::num_stages().
prepare_step()
void prepare_step (SmartPtr< SolutionTimeSeries > unnamed, double unnamed) inline
prepares the assembling of defect/Jacobian for a time step
Parameters
[in] unnamed
[in] unnamed
References ITimeDiscretization< class >::prepare_step().
prepare_step_elem()
void prepare_step_elem (SmartPtr< SolutionTimeSeries > unnamed, double unnamed) inline
Parameters
[in] unnamed
[in] unnamed
References ITimeDiscretization< class >::prepare_step_elem().
set_stage()
void set_stage (size_t stage) inline
Parameters
[in] stage
References ITimeDiscretization< class >::set_stage().