Registry: SubsetHandler Class Reference
SubsetHandler Class Reference
Public Member Functions
void assign_grid (Grid *g)
void assign_subset (Vertex *unnamed, int unnamed)
void get_default_subset_index (int unnamed)
int get_subset_index (Vertex *unnamed) const
const char * get_subset_name (int subsetIndex) const
int num_subsets () const
void set_default_subset_index (int subsetIndex)
void set_subset_name (const char *name, int subsetIndex)
SubsetHandler ()
Constructor & Destructor Documentation
SubsetHandler ()
Member Function Documentation
void assign_grid (Grid * g) inline
Parameters
[in] g
References GridSubsetHandler::assign_grid().
void assign_subset (Vertex * unnamed, int unnamed) inline inherited
Parameters
[in] unnamed
[in] unnamed
References ISubsetHandler::assign_subset().
void get_default_subset_index (int unnamed) inline inherited
Parameters
[in] unnamed
References ISubsetHandler::get_default_subset_index().
int get_subset_index (Vertex * unnamed) const inline inherited
Parameters
[in] unnamed
References ISubsetHandler::get_subset_index().
const char* get_subset_name (int subsetIndex) const inline inherited
Parameters
[in] subsetIndex
Returns
subset name
References ISubsetHandler::get_subset_name().
int num_subsets () const inline inherited
References ISubsetHandler::num_subsets().
void set_default_subset_index (int subsetIndex) inline inherited
Parameters
[in] subsetIndex
References ISubsetHandler::set_default_subset_index().
void set_subset_name (const char * name, int subsetIndex) inline inherited
Parameters
[in] name
[in] subsetIndex
References ISubsetHandler::set_subset_name().