Registry: AssembledOperator Class Reference
AssembledOperator Class Reference
Public Member Functions
AssembledOperator ()
AssembledOperator (SmartPtr< IAssemble > AssemblingRoutine)
AssembledOperator (SmartPtr< IAssemble > AssemblingRoutine, const GridLevel *GridLevel)
void init ()
const GridLevel * level () const
void set_discretization (SmartPtr< IAssemble > ass)
void set_level (const GridLevel *gridLevel)
Detailed Description
Note
default specialization is AssembledOperatorCPU1
See also
ug::AssembledOperator
Constructor & Destructor Documentation
AssembledOperator() [1/3]
AssembledOperator ()
AssembledOperator() [2/3]
AssembledOperator (SmartPtr< IAssemble > AssemblingRoutine)
Parameters
[in] AssemblingRoutine
AssembledOperator() [3/3]
AssembledOperator (SmartPtr< IAssemble > AssemblingRoutine, const GridLevel * GridLevel)
Parameters
[in] AssemblingRoutine
[in] GridLevel
Member Function Documentation
init()
void init () inline
References AssembledOperator< TAlgebra >::init().
level()
const GridLevel* level () const inline
Returns
gridLevel
References AssembledOperator< TAlgebra >::level().
set_discretization()
void set_discretization (SmartPtr< IAssemble > ass) inline
Parameters
[in] ass
References AssembledOperator< TAlgebra >::set_discretization().
set_level()
void set_level (const GridLevel * gridLevel) inline
Parameters
[in] gridLevel
References AssembledOperator< TAlgebra >::set_level().