Registry: MemInfo Class Reference
MemInfo Class Reference
Public Member Functions
double global_resident_memory () const
double global_virtual_memory () const
double local_resident_memory () const
double local_virtual_memory () const
double max_resident_memory () const
double max_virtual_memory () const
MemInfo ()
void memory_consumption ()
Constructor & Destructor Documentation
MemInfo()
MemInfo ()
Member Function Documentation
global_resident_memory()
double global_resident_memory () const inline
References MemInfo::global_resident_memory().
global_virtual_memory()
double global_virtual_memory () const inline
References MemInfo::global_virtual_memory().
local_resident_memory()
double local_resident_memory () const inline
References MemInfo::local_resident_memory().
local_virtual_memory()
double local_virtual_memory () const inline
References MemInfo::local_virtual_memory().
max_resident_memory()
double max_resident_memory () const inline
References MemInfo::max_resident_memory().
max_virtual_memory()
double max_virtual_memory () const inline
References MemInfo::max_virtual_memory().
memory_consumption()
void memory_consumption () inline
References MemInfo::memory_consumption().