Registry: ug4Bridge::SpatialDisc::SmallStrainMechanics Namespace Reference
ug4Bridge::SpatialDisc::SmallStrainMechanics Namespace Reference
Classes
class ContactSmallStrainMechanics
class HookeLaw
class IMaterialLaw
class MechOutputWriter
class PrandtlReuss
class SmallStrainMechanics
Functions
void equiv_plast_strain (GridFunction *unnamed, MechOutputWriter *unnamed, GridFunction *unnamed)
void normal_stresses_strains (MechOutputWriter *unnamed, GridFunction *unnamed, GridFunction *unnamed, GridFunction *unnamed, GridFunction *unnamed, GridFunction *unnamed)
void plast_ip (GridFunction *unnamed, MechOutputWriter *unnamed, GridFunction *unnamed)
Function Documentation
equiv_plast_strain()
void ug4Bridge::SpatialDisc::SmallStrainMechanics::equiv_plast_strain (GridFunction * unnamed, MechOutputWriter * unnamed, GridFunction * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References equiv_plast_strain().
normal_stresses_strains()
void ug4Bridge::SpatialDisc::SmallStrainMechanics::normal_stresses_strains (MechOutputWriter * unnamed, GridFunction * unnamed, GridFunction * unnamed, GridFunction * unnamed, GridFunction * unnamed, GridFunction * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References normal_stresses_strains().
plast_ip()
void ug4Bridge::SpatialDisc::SmallStrainMechanics::plast_ip (GridFunction * unnamed, MechOutputWriter * unnamed, GridFunction * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References plast_ip().