Registry: ug4Bridge::promesh::GridGeneration::Geometries::D Namespace Reference
ug4Bridge::promesh::GridGeneration::Geometries::D Namespace Reference
Functions
void CreateBox (Mesh *mesh, const Vec3d *min_corner, const Vec3d *max_corner, int subset, bool fill)
Creates a box.
void CreateCircle (Mesh *mesh, const Vec3d *center, double radius, int rim_vertices, int subset, bool fill)
Creates a circle.
void CreatePlane (Mesh *mesh, const Vec3d *upLeft, const Vec3d *upRight, const Vec3d *lowLeft, const Vec3d *lowRight, int subset, bool fill)
Creates a plane.
void CreatePrism (Mesh *mesh, int subset, bool fill)
Creates a prism.
void CreatePyramid (Mesh *mesh, int subset, bool fill)
Creates a pyramid.
void CreateSphere (Mesh *mesh, const Vec3d *center, double radius, int refinements, int subset)
Creates a sphere.
void CreateTetrahedron (Mesh *mesh, int subset, bool fill)
Creates a tetrahedron.
Function Documentation
CreateBox()
void ug4Bridge::promesh::GridGeneration::Geometries::D::CreateBox (Mesh * mesh, const Vec3d * min_corner, const Vec3d * max_corner, int subset, bool fill)
Creates a box.
Parameters
[in] mesh
[in] min_corner
[in] max_corner
[in] subset
[in] fill
References CreateBox().
CreateCircle()
void ug4Bridge::promesh::GridGeneration::Geometries::D::CreateCircle (Mesh * mesh, const Vec3d * center, double radius, int rim_vertices, int subset, bool fill)
Creates a circle.
Parameters
[in] mesh
[in] center
[in] radius
[in] rim_vertices
[in] subset
[in] fill
References CreateCircle().
CreatePlane()
void ug4Bridge::promesh::GridGeneration::Geometries::D::CreatePlane (Mesh * mesh, const Vec3d * upLeft, const Vec3d * upRight, const Vec3d * lowLeft, const Vec3d * lowRight, int subset, bool fill)
Creates a plane.
Parameters
[in] mesh
[in] upLeft
[in] upRight
[in] lowLeft
[in] lowRight
[in] subset
[in] fill
References CreatePlane().
CreatePrism()
void ug4Bridge::promesh::GridGeneration::Geometries::D::CreatePrism (Mesh * mesh, int subset, bool fill)
Creates a prism.
Parameters
[in] mesh
[in] subset
[in] fill
References CreatePrism().
CreatePyramid()
void ug4Bridge::promesh::GridGeneration::Geometries::D::CreatePyramid (Mesh * mesh, int subset, bool fill)
Creates a pyramid.
Parameters
[in] mesh
[in] subset
[in] fill
References CreatePyramid().
CreateSphere()
void ug4Bridge::promesh::GridGeneration::Geometries::D::CreateSphere (Mesh * mesh, const Vec3d * center, double radius, int refinements, int subset)
Creates a sphere.
Parameters
[in] mesh
[in] center
[in] radius
[in] refinements
[in] subset
References CreateSphere().
CreateTetrahedron()
void ug4Bridge::promesh::GridGeneration::Geometries::D::CreateTetrahedron (Mesh * mesh, int subset, bool fill)
Creates a tetrahedron.
Parameters
[in] mesh
[in] subset
[in] fill
References CreateTetrahedron().