Registry: ug4Bridge::promesh::Selection::Edges::CoordinateBased Namespace Reference
ug4Bridge::promesh::Selection::Edges::CoordinateBased Namespace Reference
Functions
Edge * SelectEdgeByCoordinate (Mesh *mesh, const Vec *coordinate)
Selects the edge whose center is closest to the specified coordinate.
Edge * SelectEdgeByCylindricalCoordinate (Mesh *mesh, double rho, double phi, double z)
Selects the edge whose center is closest to the specified cylindrical coordinate.
void SelectEdgesInBox (Mesh *mesh, const Vec *min, const Vec *max)
Selects all edges in the given box.
void SelectEdgesInCylinder (Mesh *mesh, const Vec *base, const Vec *top, double radius)
Selects all edges in the given cylinder.
Function Documentation
SelectEdgeByCoordinate()
Edge* ug4Bridge::promesh::Selection::Edges::CoordinateBased::SelectEdgeByCoordinate (Mesh * mesh, const Vec * coordinate)
Selects the edge whose center is closest to the specified coordinate.
Parameters
[in] mesh
[in] coordinate
References SelectEdgeByCoordinate().
Referenced by SelectEdgeByCoordinate().
SelectEdgeByCylindricalCoordinate()
Edge* ug4Bridge::promesh::Selection::Edges::CoordinateBased::SelectEdgeByCylindricalCoordinate (Mesh * mesh, double rho, double phi, double z)
Selects the edge whose center is closest to the specified cylindrical coordinate.
Parameters
[in] mesh
[in] rho
[in] phi
[in] z
References SelectEdgeByCylindricalCoordinate().
Referenced by SelectEdgeByCylindricalCoordinate().
SelectEdgesInBox()
void ug4Bridge::promesh::Selection::Edges::CoordinateBased::SelectEdgesInBox (Mesh * mesh, const Vec * min, const Vec * max)
Selects all edges in the given box.
Parameters
[in] mesh
[in] min
[in] max
References SelectEdgesInBox().
Referenced by SelectEdgesInBox().
SelectEdgesInCylinder()
void ug4Bridge::promesh::Selection::Edges::CoordinateBased::SelectEdgesInCylinder (Mesh * mesh, const Vec * base, const Vec * top, double radius)
Selects all edges in the given cylinder.
Parameters
[in] mesh
[in] base
[in] top
[in] radius
References SelectEdgesInCylinder().
Referenced by SelectEdgesInCylinder().