Registry: ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes Namespace Reference
ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes Namespace Reference
Namespaces
SpatialDisc
Classes
class ConstantBoxFilter
class ElementBoxFilter
class FV1BoxFilter
class FVCRBoxFilter
class IncompressibleNavierStokesBase
class NavierStokesInflowBase
class NavierStokesNoNormalStressOutflowBase
class NavierStokesWall
class VariableBoxFilter
class WallObject
Functions
void cflNumber (GridFunction *unnamed, double unnamed)
void CRToLagrange (GridFunction *unnamed, GridFunction *unnamed)
std::vector< double > DragLift (SmartPtr< GridFunction > unnamed, const char *unnamed, const char *unnamed, const char *unnamed, double unnamed, double unnamed, int unnamed)
void DrivenCavityLinesEval (SmartPtr< GridFunction > unnamed, std::vector< std::string > unnamed, size_t unnamed)
double kineticEnergy (GridFunction *unnamed)
void vorticity (GridFunction *unnamed, GridFunction *unnamed)
Function Documentation
cflNumber()
void ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::cflNumber (GridFunction * unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
References cflNumber().
CRToLagrange()
void ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::CRToLagrange (GridFunction * unnamed, GridFunction * unnamed)
Parameters
[in] unnamed
[in] unnamed
References CRToLagrange().
Referenced by CRToLagrange().
DragLift()
std::vector< double > ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::DragLift (SmartPtr< GridFunction > unnamed, const char * unnamed, const char * unnamed, const char * unnamed, double unnamed, double unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References DragLift().
DrivenCavityLinesEval()
void ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::DrivenCavityLinesEval (SmartPtr< GridFunction > unnamed, std::vector< std::string > unnamed, size_t unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References DrivenCavityLinesEval().
kineticEnergy()
double ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::kineticEnergy (GridFunction * unnamed)
Parameters
[in] unnamed
References kineticEnergy().
vorticity()
void ug4Bridge::SpatialDisc::NavierStokes::SpatialDisc::NavierStokes::vorticity (GridFunction * unnamed, GridFunction * unnamed)
Parameters
[in] unnamed
[in] unnamed
References vorticity().