Registry: ug4Bridge::Discretization Namespace Reference
ug4Bridge::Discretization Namespace Reference
Namespaces
Adaptive
ApproximationSpace
MultiGrid
Nonlinear
Output
SpatialDisc
TimeDisc
Classes
class AssembledLinearOperator
class AssTuner
class DoFDistributionInfoProvider
class GridLevel
class IApproximationSpace
class IDomainDecompositionInfo
class LFEID
class MultiIndex2
class StandardDomainDecompositionInfo
Functions
void AssembleLinearOperatorRhsAndSolution (AssembledLinearOperator *unnamed, Vector *unnamed, Vector *unnamed)
void CreateControlVolumeDomain_FV1 (Domain *unnamed, const Domain *unnamed, const SurfaceView *unnamed, int unnamed)
void CreateControlVolumeDomain_HFV1 (Domain *unnamed, const Domain *unnamed, const SurfaceView *unnamed, int unnamed)
void CreateSubControlVolumeDomain_FV1 (Domain *unnamed, const Domain *unnamed, const SurfaceView *unnamed, int unnamed)
void CreateSubControlVolumeDomain_HFV1 (Domain *unnamed, const Domain *unnamed, const SurfaceView *unnamed, int unnamed)
void CreateSubControlVolumeFaceDomain_FV1 (Domain *unnamed, const Domain *unnamed, const SurfaceView *unnamed, int unnamed)
void CreateSubControlVolumeFaceDomain_HFV1 (Domain *unnamed, const Domain *unnamed, const SurfaceView *unnamed, int unnamed)
void EdgeReferenceMappingTest (std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed)
double H1Error (SmartPtr< GridFunction > unnamed, const char *unnamed, SmartPtr< GridFunction > unnamed, const char *unnamed, int unnamed, const char *unnamed)
double Integral (SmartPtr< UserNumber > Data, SmartPtr< GridFunction > GridFunction, const char *Subsets, double Time, int QuadOrder)
double IntegralNormalComponentOnManifold (SmartPtr< UserVector > Data, SmartPtr< GridFunction > GridFunction, const char *BoundarySubsets, const char *InnerSubsets, double Time, int QuadOrder)
double IntegrateDiscFlux (SmartPtr< IAssemble > unnamed, SmartPtr< GridFunction > unnamed, const char *unnamed, const char *unnamed)
double IntegrateNormalGradientOnManifold (GridFunction *GridFunction, const char *Component, const char *BoundarySubset, const char *InnerSubset)
void Interpolate (SmartPtr< UserNumber > Data, SmartPtr< GridFunction > GridFunction, const char *Component, const char *Subsets, double Time)
void InterpolateInner (SmartPtr< UserNumber > Data, SmartPtr< GridFunction > GridFunction, const char *Component, const char *Subsets, double Time)
double L2Error (SmartPtr< GridFunction > unnamed, const char *unnamed, SmartPtr< GridFunction > unnamed, const char *unnamed, int unnamed, const char *unnamed)
double L2Norm (SmartPtr< GridFunction > unnamed, const char *unnamed, int unnamed, const char *unnamed)
double MaxError (SmartPtr< UserNumber > Data, SmartPtr< GridFunction > GridFunction, const char *Component, const char *Subsets, double Time)
void OctReferenceMappingTest (std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed)
void Prolongate (GridFunction *unnamed, const GridFunction *unnamed)
void Restrict (GridFunction *unnamed, const GridFunction *unnamed)
void TetReferenceMappingTest (std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed)
Function Documentation
AssembleLinearOperatorRhsAndSolution()
void ug4Bridge::Discretization::AssembleLinearOperatorRhsAndSolution (AssembledLinearOperator * unnamed, Vector * unnamed, Vector * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References Algebra(), and AssembleLinearOperatorRhsAndSolution().
CreateControlVolumeDomain_FV1()
void ug4Bridge::Discretization::CreateControlVolumeDomain_FV1 (Domain * unnamed, const Domain * unnamed, const SurfaceView * unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References CreateControlVolumeDomain_FV1(), and Domain().
Referenced by CreateControlVolumeDomain_FV1().
CreateControlVolumeDomain_HFV1()
void ug4Bridge::Discretization::CreateControlVolumeDomain_HFV1 (Domain * unnamed, const Domain * unnamed, const SurfaceView * unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References CreateControlVolumeDomain_HFV1(), and Domain().
Referenced by CreateControlVolumeDomain_HFV1().
CreateSubControlVolumeDomain_FV1()
void ug4Bridge::Discretization::CreateSubControlVolumeDomain_FV1 (Domain * unnamed, const Domain * unnamed, const SurfaceView * unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References CreateSubControlVolumeDomain_FV1(), and Domain().
Referenced by CreateSubControlVolumeDomain_FV1().
CreateSubControlVolumeDomain_HFV1()
void ug4Bridge::Discretization::CreateSubControlVolumeDomain_HFV1 (Domain * unnamed, const Domain * unnamed, const SurfaceView * unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References CreateSubControlVolumeDomain_HFV1(), and Domain().
Referenced by CreateSubControlVolumeDomain_HFV1().
CreateSubControlVolumeFaceDomain_FV1()
void ug4Bridge::Discretization::CreateSubControlVolumeFaceDomain_FV1 (Domain * unnamed, const Domain * unnamed, const SurfaceView * unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References CreateSubControlVolumeFaceDomain_FV1(), and Domain().
Referenced by CreateSubControlVolumeFaceDomain_FV1().
CreateSubControlVolumeFaceDomain_HFV1()
void ug4Bridge::Discretization::CreateSubControlVolumeFaceDomain_HFV1 (Domain * unnamed, const Domain * unnamed, const SurfaceView * unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References CreateSubControlVolumeFaceDomain_HFV1(), and Domain().
Referenced by CreateSubControlVolumeFaceDomain_HFV1().
EdgeReferenceMappingTest()
void ug4Bridge::Discretization::EdgeReferenceMappingTest (std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References EdgeReferenceMappingTest(), and Init().
H1Error()
double ug4Bridge::Discretization::H1Error (SmartPtr< GridFunction > unnamed, const char * unnamed, SmartPtr< GridFunction > unnamed, const char * unnamed, int unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References H1Error().
Integral()
double ug4Bridge::Discretization::Integral (SmartPtr< UserNumber > Data, SmartPtr< GridFunction > GridFunction, const char * Subsets, double Time, int QuadOrder)
Parameters
[in] Data
[in] GridFunction
[in] Subsets
[in] Time
[in] QuadOrder
Returns
Integral
References Integral().
IntegralNormalComponentOnManifold()
double ug4Bridge::Discretization::IntegralNormalComponentOnManifold (SmartPtr< UserVector > Data, SmartPtr< GridFunction > GridFunction, const char * BoundarySubsets, const char * InnerSubsets, double Time, int QuadOrder)
Parameters
[in] Data
[in] GridFunction
[in] BoundarySubsets
[in] InnerSubsets
[in] Time
[in] QuadOrder
Returns
Integral
References IntegralNormalComponentOnManifold().
IntegrateDiscFlux()
double ug4Bridge::Discretization::IntegrateDiscFlux (SmartPtr< IAssemble > unnamed, SmartPtr< GridFunction > unnamed, const char * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
Returns
Integral
References IntegrateDiscFlux().
IntegrateNormalGradientOnManifold()
double ug4Bridge::Discretization::IntegrateNormalGradientOnManifold (GridFunction * GridFunction, const char * Component, const char * BoundarySubset, const char * InnerSubset)
Parameters
[in] GridFunction
[in] Component
[in] BoundarySubset
[in] InnerSubset
Returns
Integral
References IntegrateNormalGradientOnManifold().
Interpolate()
void ug4Bridge::Discretization::Interpolate (SmartPtr< UserNumber > Data, SmartPtr< GridFunction > GridFunction, const char * Component, const char * Subsets, double Time)
Parameters
[in] Data
[in] GridFunction
[in] Component
[in] Subsets
[in] Time
References Interpolate().
InterpolateInner()
void ug4Bridge::Discretization::InterpolateInner (SmartPtr< UserNumber > Data, SmartPtr< GridFunction > GridFunction, const char * Component, const char * Subsets, double Time)
Parameters
[in] Data
[in] GridFunction
[in] Component
[in] Subsets
[in] Time
References InterpolateInner().
L2Error()
double ug4Bridge::Discretization::L2Error (SmartPtr< GridFunction > unnamed, const char * unnamed, SmartPtr< GridFunction > unnamed, const char * unnamed, int unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References L2Error().
L2Norm()
double ug4Bridge::Discretization::L2Norm (SmartPtr< GridFunction > unnamed, const char * unnamed, int unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References L2Norm().
MaxError()
double ug4Bridge::Discretization::MaxError (SmartPtr< UserNumber > Data, SmartPtr< GridFunction > GridFunction, const char * Component, const char * Subsets, double Time)
Parameters
[in] Data
[in] GridFunction
[in] Component
[in] Subsets
[in] Time
Returns
Integral
References MaxError().
OctReferenceMappingTest()
void ug4Bridge::Discretization::OctReferenceMappingTest (std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References OctReferenceMappingTest().
Prolongate()
void ug4Bridge::Discretization::Prolongate (GridFunction * unnamed, const GridFunction * unnamed)
Parameters
[in] unnamed
[in] unnamed
References Prolongate().
Restrict()
void ug4Bridge::Discretization::Restrict (GridFunction * unnamed, const GridFunction * unnamed)
Parameters
[in] unnamed
[in] unnamed
References Restrict().
TetReferenceMappingTest()
void ug4Bridge::Discretization::TetReferenceMappingTest (std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed, std::vector< double > unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References TetReferenceMappingTest().