Registry: ug4Bridge::promesh::Remeshing::MergeVertices Namespace Reference
ug4Bridge::promesh::Remeshing::MergeVertices Namespace Reference
Functions
void MergeAtCenter (Mesh *mesh)
Merges all selected objects into a single vertex at the center of the selection.
void MergeAtFirst (Mesh *mesh)
Merges all selected objects into a single vertex at the first selected vertex.
void MergeAtLast (Mesh *mesh)
Merges all selected objects into a single vertex at the last selected vertex.
Function Documentation
MergeAtCenter()
void ug4Bridge::promesh::Remeshing::MergeVertices::MergeAtCenter (Mesh * mesh)
Merges all selected objects into a single vertex at the center of the selection.
Parameters
[in] mesh
References MergeAtCenter(), and MergeVertices().
MergeAtFirst()
void ug4Bridge::promesh::Remeshing::MergeVertices::MergeAtFirst (Mesh * mesh)
Merges all selected objects into a single vertex at the first selected vertex.
Parameters
[in] mesh
References MergeAtFirst(), and MergeVertices().
MergeAtLast()
void ug4Bridge::promesh::Remeshing::MergeVertices::MergeAtLast (Mesh * mesh)
Merges all selected objects into a single vertex at the last selected vertex.
Parameters
[in] mesh
References MergeAtLast().