Registry: ug4Bridge::Discretization::Output Namespace Reference
ug4Bridge::Discretization::Output Namespace Reference
Classes
class GridFunctionDebugWriter
class GridFunctionPositionProvider
class GridFunctionVectorWriter
class GridFunctionVectorWriterDirichlet0
class VTKOutput
Functions
void LoadVector (GridFunction *vec, const char *Filename)
save vector as .vec for ConnectionViewer
void SaveDomainToVTK (const char *filename, Domain *Domain)
void SaveMatrixForConnectionViewer (GridFunction *u, MatrixOperator *A, const char *Filename)
void SaveMatrixToMTX (const char *filename.mtx, MatrixOperator *mat, std::string comment)
Save the assembled matrix of a matrix operator to MatrixMarket format.
void SaveVectorCSV (GridFunction *b, const char *filename)
void SaveVectorDiffForConnectionViewer (GridFunction *vecA, GridFunction *vecB, const char *Filename)
compare two vectors a and b and save difference in .vec for ConnectionViewer
void SaveVectorForConnectionViewer (GridFunction *vec, const char *Filename)
save vector as .vec for ConnectionViewer
void WriteGridFunctionToVTK (GridFunction *GridFunction, const char *Filename)
Saves GridFunction to *.vtk file.
Function Documentation
void ug4Bridge::Discretization::Output::LoadVector (GridFunction * vec, const char * Filename)
save vector as .vec for ConnectionViewer
Parameters
[in] vec
[in] Filename
References LoadVector(), and Output().
void ug4Bridge::Discretization::Output::SaveDomainToVTK (const char * filename, Domain * Domain)
Parameters
[in] filename
[in] Domain
References Output(), and SaveDomainToVTK().
void ug4Bridge::Discretization::Output::SaveMatrixForConnectionViewer (GridFunction * u, MatrixOperator * A, const char * Filename)
Parameters
[in] u
[in] A
[in] Filename
References Output(), and SaveMatrixForConnectionViewer().
void ug4Bridge::Discretization::Output::SaveMatrixToMTX (const char *filename. mtx, MatrixOperator * mat, std::string comment)
Save the assembled matrix of a matrix operator to MatrixMarket format.
Parameters
[in] filename.mtx
[in] mat
[in] comment
References Output(), and SaveMatrixToMTX().
void ug4Bridge::Discretization::Output::SaveVectorCSV (GridFunction * b, const char * filename)
Parameters
[in] b
[in] filename
References SaveVectorCSV().
void ug4Bridge::Discretization::Output::SaveVectorDiffForConnectionViewer (GridFunction * vecA, GridFunction * vecB, const char * Filename)
compare two vectors a and b and save difference in .vec for ConnectionViewer
Parameters
[in] vecA
[in] vecB
[in] Filename
References Output(), and SaveVectorDiffForConnectionViewer().
void ug4Bridge::Discretization::Output::SaveVectorForConnectionViewer (GridFunction * vec, const char * Filename)
save vector as .vec for ConnectionViewer
Parameters
[in] vec
[in] Filename
References Output(), and SaveVectorForConnectionViewer().
void ug4Bridge::Discretization::Output::WriteGridFunctionToVTK (GridFunction * GridFunction, const char * Filename)
Saves GridFunction to *.vtk file.
No help
Parameters
[in] GridFunction
[in] Filename
References Output(), and WriteGridFunctionToVTK().