Registry: ug4Bridge::Selection Namespace Reference
ug4Bridge::Selection Namespace Reference
Functions
void SelectAssociatedElements (ISelector *sel, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces)
void SelectDomainElements (ISelector *sel, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVolumes)
void SelectDomainSubset (ISelector *sel, Domain *dom, int subsetIndex, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVolumes)
Function Documentation
SelectAssociatedElements()
void ug4Bridge::Selection::SelectAssociatedElements (ISelector * sel, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces)
Parameters
[in] sel
[in] bSelect
[in] selectVrts
[in] selectEdges
[in] selectFaces
References SelectAssociatedElements().
SelectDomainElements()
void ug4Bridge::Selection::SelectDomainElements (ISelector * sel, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVolumes)
Parameters
[in] sel
[in] bSelect
[in] selectVrts
[in] selectEdges
[in] selectFaces
[in] selectVolumes
References SelectDomainElements().
SelectDomainSubset()
void ug4Bridge::Selection::SelectDomainSubset (ISelector * sel, Domain * dom, int subsetIndex, bool bSelect, bool selectVrts, bool selectEdges, bool selectFaces, bool selectVolumes)
Parameters
[in] sel
[in] dom
[in] subsetIndex
[in] bSelect
[in] selectVrts
[in] selectEdges
[in] selectFaces
[in] selectVolumes
References Domain(), and SelectDomainSubset().