Registry: ug4Bridge::promesh::Selection Namespace Reference
ug4Bridge::promesh::Selection Namespace Reference
Namespaces
CoordinateRange
Edges
Faces
Marks
SubsetBased
Vertices
Volumes
Functions
void ClearSelection (Mesh *mesh)
Clears the selection.
void CloseSelection (Mesh *mesh)
Selects all associated elements of lower dimensions.
void ExtendSelection (Mesh *mesh, int neighborhood_size)
Selects neighbors of selected elements.
void ExtendSelectionInDirection (Mesh *mesh, int neighborhood_size, const Vec *direction, double minAngle, double maxAngle)
Selects neighbors of selected elements whose center can be reached in the given direction from the center of already selected elements.
void InvertSelection (Mesh *mesh, bool vertices, bool edges, bool faces, bool volumes)
Inverts current selection.
void SelectAll (Mesh *mesh)
Selects all vertices, edges ,faces and volumes of the current grid.
void SelectElementsByIndexRange (Mesh *mesh, const char *vertex_inds, const char *edge_inds, const char *face_inds, const char *volume_inds, bool clear_selection)
Selects elements by the given index ranges (e.g.: "0,1,2-5,9,11-23").
void SelectSelectionBoundary (Mesh *mesh)
Selects the boundary of the current selection.
Function Documentation
ClearSelection()
void ug4Bridge::promesh::Selection::ClearSelection (Mesh * mesh)
Clears the selection.
Parameters
[in] mesh
References ClearSelection().
CloseSelection()
void ug4Bridge::promesh::Selection::CloseSelection (Mesh * mesh)
Selects all associated elements of lower dimensions.
Parameters
[in] mesh
References CloseSelection().
ExtendSelection()
void ug4Bridge::promesh::Selection::ExtendSelection (Mesh * mesh, int neighborhood_size)
Selects neighbors of selected elements.
Parameters
[in] mesh
[in] neighborhood_size
References ExtendSelection().
ExtendSelectionInDirection()
void ug4Bridge::promesh::Selection::ExtendSelectionInDirection (Mesh * mesh, int neighborhood_size, const Vec * direction, double minAngle, double maxAngle)
Selects neighbors of selected elements whose center can be reached in the given direction from the center of already selected elements.
Parameters
[in] mesh
[in] neighborhood_size
[in] direction
[in] minAngle
[in] maxAngle
References ExtendSelectionInDirection().
InvertSelection()
void ug4Bridge::promesh::Selection::InvertSelection (Mesh * mesh, bool vertices, bool edges, bool faces, bool volumes)
Inverts current selection.
Parameters
[in] mesh
[in] vertices
[in] edges
[in] faces
[in] volumes
References InvertSelection().
SelectAll()
void ug4Bridge::promesh::Selection::SelectAll (Mesh * mesh)
Selects all vertices, edges ,faces and volumes of the current grid.
Parameters
[in] mesh
References SelectAll().
SelectElementsByIndexRange()
void ug4Bridge::promesh::Selection::SelectElementsByIndexRange (Mesh * mesh, const char * vertex_inds, const char * edge_inds, const char * face_inds, const char * volume_inds, bool clear_selection)
Selects elements by the given index ranges (e.g.: "0,1,2-5,9,11-23").
Parameters
[in] mesh
[in] vertex_inds
[in] edge_inds
[in] face_inds
[in] volume_inds
[in] clear_selection
References SelectElementsByIndexRange().
SelectSelectionBoundary()
void ug4Bridge::promesh::Selection::SelectSelectionBoundary (Mesh * mesh)
Selects the boundary of the current selection.
Parameters
[in] mesh
References SelectSelectionBoundary().