Registry: ug4Bridge::promesh::CoordinateTransform::SubdivisionProjection Namespace Reference
ug4Bridge::promesh::CoordinateTransform::SubdivisionProjection Namespace Reference
Functions
void ProjectToLimitPiecewiseLoop (Mesh *mesh)
Projects all vertices in the grid to their limit positions as defined by the piecewise loop scheme.
void ProjectToLimitSmoothBoundary (Mesh *mesh)
Projects all boundary-vertices in the grid to their limit positions as defined by the b-spline subdivision scheme.
Function Documentation
ProjectToLimitPiecewiseLoop()
void ug4Bridge::promesh::CoordinateTransform::SubdivisionProjection::ProjectToLimitPiecewiseLoop (Mesh * mesh)
Projects all vertices in the grid to their limit positions as defined by the piecewise loop scheme.
Parameters
[in] mesh
References ProjectToLimitPiecewiseLoop().
Referenced by ProjectToLimitPiecewiseLoop().
ProjectToLimitSmoothBoundary()
void ug4Bridge::promesh::CoordinateTransform::SubdivisionProjection::ProjectToLimitSmoothBoundary (Mesh * mesh)
Projects all boundary-vertices in the grid to their limit positions as defined by the b-spline subdivision scheme.
Parameters
[in] mesh
References ProjectToLimitSmoothBoundary().