Registry: ug4Bridge::promesh::Selection::Volumes Namespace Reference
ug4Bridge::promesh::Selection::Volumes Namespace Reference
Functions
void DeselectAllVolumes (Mesh *mesh)
Deselects all volumes of the current grid.
void SelectAllVolumes (Mesh *mesh)
Selects all volumes of the current grid.
void SelectAnisotropicVolumes (Mesh *mesh, double minEdgeRation)
Selects elements and associated long edges wich have a shortest-to-longest edge ratio smaller than the specified one.
void SelectLinkedVolumes (Mesh *mesh)
Repeatedly selects all volumes which are face-neighbors of selected volumes.
int SelectSlivers (Mesh *mesh, double threshold_ratio)
Selects flat tetrahedrons. Threshold-ratio specifies the minimal ratio between the distance of two opposing edges to the length of the longest edge.
int SelectUnorientableVolumes (Mesh *mesh)
Selects all volumes whose orientation can not be determined.
Volume * SelectVolumeByCoordinate (Mesh *mesh, const Vec3d *coordinate)
Selects the volume whose center is closest to the specified coordinate.
Volume * SelectVolumeByCylindricalCoordinate (Mesh *mesh, double rho, double phi, double z)
Selects the volume whose center is closest to the specified cylindrical coordinate.
bool SelectVolumeByIndex (Mesh *mesh, int index)
Selects a volume given its index.
void SelectVolumesInBox (Mesh *mesh, const Vec3d *min, const Vec3d *max)
Selects all volumes in the given box.
void SelectVolumesInCylinder (Mesh *mesh, const Vec3d *base, const Vec3d *top, double radius)
Selects all volumes in the given cylinder.
void VolumeSelectionFill (Mesh *mesh)
Selects neighbours of selected volumes over non-selected faces.
Function Documentation
void ug4Bridge::promesh::Selection::Volumes::DeselectAllVolumes (Mesh * mesh)
Deselects all volumes of the current grid.
Parameters
[in] mesh
References DeselectAllVolumes().
void ug4Bridge::promesh::Selection::Volumes::SelectAllVolumes (Mesh * mesh)
Selects all volumes of the current grid.
Parameters
[in] mesh
References SelectAllVolumes().
void ug4Bridge::promesh::Selection::Volumes::SelectAnisotropicVolumes (Mesh * mesh, double minEdgeRation)
Selects elements and associated long edges wich have a shortest-to-longest edge ratio smaller than the specified one.
Parameters
[in] mesh
[in] minEdgeRation
References SelectAnisotropicVolumes().
Referenced by SelectAnisotropicVolumes().
void ug4Bridge::promesh::Selection::Volumes::SelectLinkedVolumes (Mesh * mesh)
Repeatedly selects all volumes which are face-neighbors of selected volumes.
Parameters
[in] mesh
References SelectLinkedVolumes().
Referenced by SelectLinkedVolumes().
int ug4Bridge::promesh::Selection::Volumes::SelectSlivers (Mesh * mesh, double threshold_ratio)
Selects flat tetrahedrons. Threshold-ratio specifies the minimal ratio between the distance of two opposing edges to the length of the longest edge.
Parameters
[in] mesh
[in] threshold_ratio
References SelectSlivers().
int ug4Bridge::promesh::Selection::Volumes::SelectUnorientableVolumes (Mesh * mesh)
Selects all volumes whose orientation can not be determined.
Parameters
[in] mesh
References SelectUnorientableVolumes().
Volume* ug4Bridge::promesh::Selection::Volumes::SelectVolumeByCoordinate (Mesh * mesh, const Vec3d * coordinate)
Selects the volume whose center is closest to the specified coordinate.
Parameters
[in] mesh
[in] coordinate
References SelectVolumeByCoordinate().
Referenced by SelectVolumeByCoordinate().
Volume* ug4Bridge::promesh::Selection::Volumes::SelectVolumeByCylindricalCoordinate (Mesh * mesh, double rho, double phi, double z)
Selects the volume whose center is closest to the specified cylindrical coordinate.
Parameters
[in] mesh
[in] rho
[in] phi
[in] z
References SelectVolumeByCylindricalCoordinate().
Referenced by SelectVolumeByCylindricalCoordinate().
bool ug4Bridge::promesh::Selection::Volumes::SelectVolumeByIndex (Mesh * mesh, int index)
Selects a volume given its index.
Parameters
[in] mesh
[in] index
References SelectVolumeByIndex().
void ug4Bridge::promesh::Selection::Volumes::SelectVolumesInBox (Mesh * mesh, const Vec3d * min, const Vec3d * max)
Selects all volumes in the given box.
Parameters
[in] mesh
[in] min
[in] max
References SelectVolumesInBox().
Referenced by SelectVolumesInBox().
void ug4Bridge::promesh::Selection::Volumes::SelectVolumesInCylinder (Mesh * mesh, const Vec3d * base, const Vec3d * top, double radius)
Selects all volumes in the given cylinder.
Parameters
[in] mesh
[in] base
[in] top
[in] radius
References SelectVolumesInCylinder().
Referenced by SelectVolumesInCylinder().
void ug4Bridge::promesh::Selection::Volumes::VolumeSelectionFill (Mesh * mesh)
Selects neighbours of selected volumes over non-selected faces.
Parameters
[in] mesh
References VolumeSelectionFill().