Registry: ug4Bridge::promesh::CoordinateTransform::Move Namespace Reference
ug4Bridge::promesh::CoordinateTransform::Move Namespace Reference
Functions
void Move (Mesh *mesh, const Vec *offset)
Moves selected vertices.
void MoveAlongNormal (Mesh *mesh, double offset)
Moves selected vertices along their normal by the specified offset.
void MoveMeshTo (Mesh *mesh, const Vec *new_position)
Moves the active mesh and its pivot, so that the pivot will be located on the specified position.
bool MoveSelectionTo (Mesh *mesh, const Vec *center)
Moves the selected elements so that the new selection center will lie at the specified position.
void MoveVerticesAlongEdges (Mesh *mesh, double relative_offset)
Moves selected vertices along selected edges by an offset relative to those selected edges. If a selected vertex is connected to multiple selected edges, the new position will be averaged between the individual offsets.
void MoveVerticesToEdgeLength (Mesh *mesh, double edge_length)
Moves selected vertices along selected edges so that those edges obtain the specified length. If a selected vertex is connected to multiple selected edges, the new position will be averaged between the individual new positions.
void MoveVerticesToProjectedEdgeLength (Mesh *mesh, double projcted_edge_length, const Vec *projection_normal)
Moves selected vertices along selected edges so that the projection of those edges into the plain with the specified normal obtain the specified length. If a selected vertex is connected to multiple selected edges, the new position will be averaged between the individual new positions.
Function Documentation
Move()
void ug4Bridge::promesh::CoordinateTransform::Move::Move (Mesh * mesh, const Vec * offset)
Moves selected vertices.
Parameters
[in] mesh
[in] offset
References Move().
MoveAlongNormal()
void ug4Bridge::promesh::CoordinateTransform::Move::MoveAlongNormal (Mesh * mesh, double offset)
Moves selected vertices along their normal by the specified offset.
Parameters
[in] mesh
[in] offset
References Move(), and MoveAlongNormal().
MoveMeshTo()
void ug4Bridge::promesh::CoordinateTransform::Move::MoveMeshTo (Mesh * mesh, const Vec * new_position)
Moves the active mesh and its pivot, so that the pivot will be located on the specified position.
Parameters
[in] mesh
[in] new_position
References Move(), and MoveMeshTo().
MoveSelectionTo()
bool ug4Bridge::promesh::CoordinateTransform::Move::MoveSelectionTo (Mesh * mesh, const Vec * center)
Moves the selected elements so that the new selection center will lie at the specified position.
Parameters
[in] mesh
[in] center
References Move(), and MoveSelectionTo().
MoveVerticesAlongEdges()
void ug4Bridge::promesh::CoordinateTransform::Move::MoveVerticesAlongEdges (Mesh * mesh, double relative_offset)
Moves selected vertices along selected edges by an offset relative to those selected edges. If a selected vertex is connected to multiple selected edges, the new position will be averaged between the individual offsets.
Parameters
[in] mesh
[in] relative_offset
References Move(), and MoveVerticesAlongEdges().
MoveVerticesToEdgeLength()
void ug4Bridge::promesh::CoordinateTransform::Move::MoveVerticesToEdgeLength (Mesh * mesh, double edge_length)
Moves selected vertices along selected edges so that those edges obtain the specified length. If a selected vertex is connected to multiple selected edges, the new position will be averaged between the individual new positions.
Parameters
[in] mesh
[in] edge_length
References Move(), and MoveVerticesToEdgeLength().
MoveVerticesToProjectedEdgeLength()
void ug4Bridge::promesh::CoordinateTransform::Move::MoveVerticesToProjectedEdgeLength (Mesh * mesh, double projcted_edge_length, const Vec * projection_normal)
Moves selected vertices along selected edges so that the projection of those edges into the plain with the specified normal obtain the specified length. If a selected vertex is connected to multiple selected edges, the new position will be averaged between the individual new positions.
Parameters
[in] mesh
[in] projcted_edge_length
[in] projection_normal
References MoveVerticesToProjectedEdgeLength().