Registry: ug4Bridge::promesh::CoordinateTransform::Pivot Namespace Reference
ug4Bridge::promesh::CoordinateTransform::Pivot Namespace Reference
Functions
void SetPivot (Mesh *mesh, const Vec3d *position)
Sets the pivot point of the selected object.
void SetPivotToMeshCenter (Mesh *mesh)
Sets the pivot to the center of the active mesh.
void SetPivotToSelectionCenter (Mesh *mesh)
Sets the pivot to the center of the current selection.
Function Documentation
SetPivot()
void ug4Bridge::promesh::CoordinateTransform::Pivot::SetPivot (Mesh * mesh, const Vec3d * position)
Sets the pivot point of the selected object.
Parameters
[in] mesh
[in] position
References SetPivot().
SetPivotToMeshCenter()
void ug4Bridge::promesh::CoordinateTransform::Pivot::SetPivotToMeshCenter (Mesh * mesh)
Sets the pivot to the center of the active mesh.
Parameters
[in] mesh
References SetPivotToMeshCenter().
SetPivotToSelectionCenter()
void ug4Bridge::promesh::CoordinateTransform::Pivot::SetPivotToSelectionCenter (Mesh * mesh)
Sets the pivot to the center of the current selection.
Parameters
[in] mesh
References SetPivotToSelectionCenter().