Registry: ug4Bridge::OrthoPoly Namespace Reference
ug4Bridge::OrthoPoly Namespace Reference
Functions
double Chebyshev1Poly (size_t unnamed, double unnamed)
Returns the value of the n-th Chebyshev polynomial of the first kind at x.
double Chebyshev2Poly (size_t unnamed, double unnamed)
Returns the value of the n-th Chebyshev polynomial of the second kind at x.
double LegendrePoly (size_t unnamed, double unnamed)
Returns the value of the n-th Legendre polynomial at x.
double NormalizedChebyshev1Poly (size_t unnamed, double unnamed)
Returns the value of the normalized n-th Chebyshev polynomial of the first kind at x.
double NormalizedChebyshev2Poly (size_t unnamed, double unnamed)
Returns the value of the normalized n-th Chebyshev polynomial of the second kind at x.
double NormalizedLegendrePoly (size_t unnamed, double unnamed)
Returns the value of the normalized n-th Legendre polynomial at x.
double SqNormOfChebyshev1Poly (size_t unnamed)
Returns the scalar square of the n-th Chebyshev polynomial of the first kind.
double SqNormOfChebyshev2Poly (size_t unnamed)
Returns the scalar square of the n-th Chebyshev polynomial of the second kind.
double SqNormOfLegendrePoly (size_t unnamed)
Returns the scalar square of the n-th Legendre polynomial.
Function Documentation
Chebyshev1Poly()
double ug4Bridge::OrthoPoly::Chebyshev1Poly (size_t unnamed, double unnamed)
Returns the value of the n-th Chebyshev polynomial of the first kind at x.
Parameters
[in] unnamed
[in] unnamed
Returns
n::x
References Chebyshev1Poly().
Chebyshev2Poly()
double ug4Bridge::OrthoPoly::Chebyshev2Poly (size_t unnamed, double unnamed)
Returns the value of the n-th Chebyshev polynomial of the second kind at x.
Parameters
[in] unnamed
[in] unnamed
Returns
n::x
References Chebyshev2Poly().
LegendrePoly()
double ug4Bridge::OrthoPoly::LegendrePoly (size_t unnamed, double unnamed)
Returns the value of the n-th Legendre polynomial at x.
Parameters
[in] unnamed
[in] unnamed
Returns
n::x
References LegendrePoly().
NormalizedChebyshev1Poly()
double ug4Bridge::OrthoPoly::NormalizedChebyshev1Poly (size_t unnamed, double unnamed)
Returns the value of the normalized n-th Chebyshev polynomial of the first kind at x.
Parameters
[in] unnamed
[in] unnamed
Returns
n::x
References NormalizedChebyshev1Poly().
NormalizedChebyshev2Poly()
double ug4Bridge::OrthoPoly::NormalizedChebyshev2Poly (size_t unnamed, double unnamed)
Returns the value of the normalized n-th Chebyshev polynomial of the second kind at x.
Parameters
[in] unnamed
[in] unnamed
Returns
n::x
References NormalizedChebyshev2Poly().
NormalizedLegendrePoly()
double ug4Bridge::OrthoPoly::NormalizedLegendrePoly (size_t unnamed, double unnamed)
Returns the value of the normalized n-th Legendre polynomial at x.
Parameters
[in] unnamed
[in] unnamed
Returns
n::x
References NormalizedLegendrePoly().
SqNormOfChebyshev1Poly()
double ug4Bridge::OrthoPoly::SqNormOfChebyshev1Poly (size_t unnamed)
Returns the scalar square of the n-th Chebyshev polynomial of the first kind.
Parameters
[in] unnamed
Returns
n
References SqNormOfChebyshev1Poly().
SqNormOfChebyshev2Poly()
double ug4Bridge::OrthoPoly::SqNormOfChebyshev2Poly (size_t unnamed)
Returns the scalar square of the n-th Chebyshev polynomial of the second kind.
Parameters
[in] unnamed
Returns
n
References SqNormOfChebyshev2Poly().
SqNormOfLegendrePoly()
double ug4Bridge::OrthoPoly::SqNormOfLegendrePoly (size_t unnamed)
Returns the scalar square of the n-th Legendre polynomial.
Parameters
[in] unnamed
Returns
n
References SqNormOfLegendrePoly().