Registry: ug4Bridge::promesh::Remeshing::BooleanOperations Namespace Reference
ug4Bridge::promesh::Remeshing::BooleanOperations Namespace Reference
Functions
void FaceDifference (Mesh *mesh, int subset_1, int subset_2, double snap_threshold)
Performs a difference operation on the geometry of the two specifed subsets. IMPORTANT: Both subsets have to be closed manifolds, i.e., homeomorphic to the sphere.
void FaceIntersection (Mesh *mesh, int subset_1, int subset_2, double snap_threshold)
Performs an intersection operation on the geometry of the two specifed subsets. IMPORTANT: Both subsets have to be closed manifolds, i.e., homeomorphic to the sphere.
void FaceUnion (Mesh *mesh, int subset_1, int subset_2, double snap_threshold)
Performs a union operation on the geometry of the two specifed subsets. IMPORTANT: Both subsets have to be closed manifolds, i.e., homeomorphic to the sphere.
Function Documentation
FaceDifference()
void ug4Bridge::promesh::Remeshing::BooleanOperations::FaceDifference (Mesh * mesh, int subset_1, int subset_2, double snap_threshold)
Performs a difference operation on the geometry of the two specifed subsets. IMPORTANT: Both subsets have to be closed manifolds, i.e., homeomorphic to the sphere.
Parameters
[in] mesh
[in] subset_1
[in] subset_2
[in] snap_threshold
References FaceDifference().
Referenced by FaceDifference().
FaceIntersection()
void ug4Bridge::promesh::Remeshing::BooleanOperations::FaceIntersection (Mesh * mesh, int subset_1, int subset_2, double snap_threshold)
Performs an intersection operation on the geometry of the two specifed subsets. IMPORTANT: Both subsets have to be closed manifolds, i.e., homeomorphic to the sphere.
Parameters
[in] mesh
[in] subset_1
[in] subset_2
[in] snap_threshold
References FaceIntersection().
Referenced by FaceIntersection().
FaceUnion()
void ug4Bridge::promesh::Remeshing::BooleanOperations::FaceUnion (Mesh * mesh, int subset_1, int subset_2, double snap_threshold)
Performs a union operation on the geometry of the two specifed subsets. IMPORTANT: Both subsets have to be closed manifolds, i.e., homeomorphic to the sphere.
Parameters
[in] mesh
[in] subset_1
[in] subset_2
[in] snap_threshold
References FaceUnion().
Referenced by FaceUnion().