Registry: ug4Bridge::promesh::Remeshing::Triangles Namespace Reference
ug4Bridge::promesh::Remeshing::Triangles Namespace Reference
Functions
void AdaptSurfaceToCylinder (Mesh *mesh, double radius, double threshold)
Introduces edges in a grid around a selected vertex which roughly correspond to the intersection of a cylinder with the surface.
void AdjustEdgeLength (Mesh *mesh, double min_edge_length, double max_edge_length, int num_iterations, bool adaptive, bool automark_boundaries)
Remeshes the active grid so that all edges approximatly have a certain length.
void AdjustEdgeLengthExtended (Mesh *mesh, double min_edge_length, double max_edge_length, double approximation, double triangle_quality, int num_iterations, bool automark_boundaries)
Remeshes the active grid so that all edges approximatly have a certain length.
void ConvertToTriangles (Mesh *mesh)
Converts selected quadrilaterals to triangles.
void ReplaceLowValenceVertices (Mesh *mesh, double max_relative_height)
Replaces selected valence-3 and valence-4 vertices by triangles, if the curvature of associated triangles is low.
void ReplaceValence3Vertices (Mesh *mesh, double max_relative_height)
Replaces selected valence-3 vertices by triangles, if the curvature of associated triangles is low.
void Retriangulate (Mesh *mesh, double min_angle)
Inserts vertices as required and performs Constrained Delaunay triangulation.
void TriangleFill (Mesh *mesh, bool quality_generation, double min_angle, int subset)
Performs triangle fill using the sweep-line algorithm followed by an optional Constrained Delaunay retriangulation.
Function Documentation
AdaptSurfaceToCylinder()
void ug4Bridge::promesh::Remeshing::Triangles::AdaptSurfaceToCylinder (Mesh * mesh, double radius, double threshold)
Introduces edges in a grid around a selected vertex which roughly correspond to the intersection of a cylinder with the surface.
Parameters
[in] mesh
[in] radius
[in] threshold
References AdaptSurfaceToCylinder().
AdjustEdgeLength()
void ug4Bridge::promesh::Remeshing::Triangles::AdjustEdgeLength (Mesh * mesh, double min_edge_length, double max_edge_length, int num_iterations, bool adaptive, bool automark_boundaries)
Remeshes the active grid so that all edges approximatly have a certain length.
Parameters
[in] mesh
[in] min_edge_length
[in] max_edge_length
[in] num_iterations
[in] adaptive
[in] automark_boundaries
References AdjustEdgeLength().
AdjustEdgeLengthExtended()
void ug4Bridge::promesh::Remeshing::Triangles::AdjustEdgeLengthExtended (Mesh * mesh, double min_edge_length, double max_edge_length, double approximation, double triangle_quality, int num_iterations, bool automark_boundaries)
Remeshes the active grid so that all edges approximatly have a certain length.
Parameters
[in] mesh
[in] min_edge_length
[in] max_edge_length
[in] approximation
[in] triangle_quality
[in] num_iterations
[in] automark_boundaries
References AdjustEdgeLengthExtended().
ConvertToTriangles()
void ug4Bridge::promesh::Remeshing::Triangles::ConvertToTriangles (Mesh * mesh)
Converts selected quadrilaterals to triangles.
Parameters
[in] mesh
References ConvertToTriangles().
ReplaceLowValenceVertices()
void ug4Bridge::promesh::Remeshing::Triangles::ReplaceLowValenceVertices (Mesh * mesh, double max_relative_height)
Replaces selected valence-3 and valence-4 vertices by triangles, if the curvature of associated triangles is low.
Parameters
[in] mesh
[in] max_relative_height
References ReplaceLowValenceVertices().
ReplaceValence3Vertices()
void ug4Bridge::promesh::Remeshing::Triangles::ReplaceValence3Vertices (Mesh * mesh, double max_relative_height)
Replaces selected valence-3 vertices by triangles, if the curvature of associated triangles is low.
Parameters
[in] mesh
[in] max_relative_height
References ReplaceValence3Vertices().
Retriangulate()
void ug4Bridge::promesh::Remeshing::Triangles::Retriangulate (Mesh * mesh, double min_angle)
Inserts vertices as required and performs Constrained Delaunay triangulation.
Parameters
[in] mesh
[in] min_angle
References Retriangulate().
TriangleFill()
void ug4Bridge::promesh::Remeshing::Triangles::TriangleFill (Mesh * mesh, bool quality_generation, double min_angle, int subset)
Performs triangle fill using the sweep-line algorithm followed by an optional Constrained Delaunay retriangulation.
Parameters
[in] mesh
[in] quality_generation
[in] min_angle
[in] subset
References TriangleFill().