Registry: ug4Bridge::Grid Namespace Reference
ug4Bridge::Grid Namespace Reference
Classes
class AdaptiveRegularRefiner_MultiGrid
class DegeneratedLayerManager
class Edge
class ExpandLayersDesc
class Face
class FractureInfoVec
class GlobalFracturedMediumRefiner
class GlobalMultiGridRefiner
class Grid
class GridObject
class HangingNodeRefiner_Grid
class HangingNodeRefiner_MultiGrid
class Heightfield
2d raster with number values
class InterSubsetPartitionWeighting
class IRefinementCallback
class IRefiner
class ISelector
class ISubsetHandler
class MGSubsetHandler
class MultiGrid
class ParallelHangingNodeRefiner_MultiGrid
class PartitionMap
class PartitionWeighting
class ProtectSubsetPartitionWeighting
class RasterLayerDesc
Layer Desc for RasterLayers class.
class RasterLayers
Stack of 2d raster data.
class Selector
class SubsetHandler
class SurfaceView
class UGXFileInfo
class Vertex
class Volume
Functions
void AdjustSubsetsForSimulation (SubsetHandler *unnamed, bool unnamed)
bool CheckDistributedObjectConstraintTypes (MultiGrid *unnamed)
bool CheckDistributedParentTypes (MultiGrid *unnamed)
bool CheckElementConsistency (MultiGrid *unnamed, Vertex *unnamed)
bool CheckHangingNodeConsistency (MultiGrid *unnamed)
void CheckMultiGridConsistency (MultiGrid *unnamed)
bool CreateFractal (Grid *unnamed, HangingNodeRefiner_Grid *unnamed, double unnamed, size_t unnamed)
bool CreateHierarchy (MultiGrid *unnamed, size_t unnamed)
bool CreateSemiSmoothHierarchy (MultiGrid *unnamed, size_t unnamed)
bool CreateSmoothHierarchy (MultiGrid *unnamed, size_t unnamed)
bool CreateSmoothVolumeHierarchy (MultiGrid *unnamed, size_t unnamed, bool unnamed, bool unnamed)
bool IsValid (Vertex *unnamed)
bool LoadGrid (Grid *grid, ISubsetHandler *sh, const char *filename)
void LoadHeightfieldFromASC (Heightfield *heightfield, const char *filename)
Loads a heightfield from the specified file.
void PrintAttachmentInfo (Grid *unnamed)
void PrintGridElementNumbers (MultiGrid *unnamed)
bool SaveGrid (Grid *grid, const ISubsetHandler *sh, const char *filename)
bool SaveGridHierarchy (MultiGrid *mg, const char *filename)
bool SaveGridHierarchyTransformed (MultiGrid *mg, ISubsetHandler *sh, const char *filename, double offset)
bool SaveParallelGridLayout (MultiGrid *mg, const char *filename, double offset)
void SubdivisionVolumes (MultiGrid *unnamed, bool unnamed, bool unnamed)
bool TestNTree (const char *unnamed)
void TestSubdivision (const char *unnamed, const char *unnamed, int unnamed)
Function Documentation
void ug4Bridge::Grid::AdjustSubsetsForSimulation (SubsetHandler * unnamed, bool unnamed)
Parameters
[in] unnamed
[in] unnamed
References AdjustSubsetsForSimulation().
bool ug4Bridge::Grid::CheckDistributedObjectConstraintTypes (MultiGrid * unnamed)
Parameters
[in] unnamed
References CheckDistributedObjectConstraintTypes().
bool ug4Bridge::Grid::CheckDistributedParentTypes (MultiGrid * unnamed)
Parameters
[in] unnamed
References CheckDistributedParentTypes().
bool ug4Bridge::Grid::CheckElementConsistency (MultiGrid * unnamed, Vertex * unnamed)
Parameters
[in] unnamed
[in] unnamed
References CheckElementConsistency().
bool ug4Bridge::Grid::CheckHangingNodeConsistency (MultiGrid * unnamed)
Parameters
[in] unnamed
References CheckHangingNodeConsistency().
void ug4Bridge::Grid::CheckMultiGridConsistency (MultiGrid * unnamed)
Parameters
[in] unnamed
References CheckMultiGridConsistency().
bool ug4Bridge::Grid::CreateFractal (Grid * unnamed, HangingNodeRefiner_Grid * unnamed, double unnamed, size_t unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References CreateFractal().
bool ug4Bridge::Grid::CreateHierarchy (MultiGrid * unnamed, size_t unnamed)
Parameters
[in] unnamed
[in] unnamed
References CreateHierarchy().
bool ug4Bridge::Grid::CreateSemiSmoothHierarchy (MultiGrid * unnamed, size_t unnamed)
Parameters
[in] unnamed
[in] unnamed
References CreateSemiSmoothHierarchy().
bool ug4Bridge::Grid::CreateSmoothHierarchy (MultiGrid * unnamed, size_t unnamed)
Parameters
[in] unnamed
[in] unnamed
References CreateSmoothHierarchy().
bool ug4Bridge::Grid::CreateSmoothVolumeHierarchy (MultiGrid * unnamed, size_t unnamed, bool unnamed, bool unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References CreateSmoothVolumeHierarchy().
bool ug4Bridge::Grid::IsValid (Vertex * unnamed)
Parameters
[in] unnamed
References IsValid().
Referenced by IsValid().
bool ug4Bridge::Grid::LoadGrid (Grid * grid, ISubsetHandler * sh, const char * filename)
Parameters
[in] grid
[in] sh
[in] filename
References LoadGrid().
void ug4Bridge::Grid::LoadHeightfieldFromASC (Heightfield * heightfield, const char * filename)
Loads a heightfield from the specified file.
Parameters
[in] heightfield
[in] filename
References LoadHeightfieldFromASC().
void ug4Bridge::Grid::PrintAttachmentInfo (Grid * unnamed)
Parameters
[in] unnamed
References PrintAttachmentInfo().
void ug4Bridge::Grid::PrintGridElementNumbers (MultiGrid * unnamed)
Parameters
[in] unnamed
References PrintGridElementNumbers().
bool ug4Bridge::Grid::SaveGrid (Grid * grid, const ISubsetHandler * sh, const char * filename)
Parameters
[in] grid
[in] sh
[in] filename
References SaveGrid().
bool ug4Bridge::Grid::SaveGridHierarchy (MultiGrid * mg, const char * filename)
Parameters
[in] mg
[in] filename
References SaveGridHierarchy().
bool ug4Bridge::Grid::SaveGridHierarchyTransformed (MultiGrid * mg, ISubsetHandler * sh, const char * filename, double offset)
Parameters
[in] mg
[in] sh
[in] filename
[in] offset
References SaveGridHierarchyTransformed().
bool ug4Bridge::Grid::SaveParallelGridLayout (MultiGrid * mg, const char * filename, double offset)
Parameters
[in] mg
[in] filename
[in] offset
References SaveParallelGridLayout().
void ug4Bridge::Grid::SubdivisionVolumes (MultiGrid * unnamed, bool unnamed, bool unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References SubdivisionVolumes().
bool ug4Bridge::Grid::TestNTree (const char * unnamed)
Parameters
[in] unnamed
References TestNTree().
void ug4Bridge::Grid::TestSubdivision (const char * unnamed, const char * unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References TestSubdivision().