Registry: ug4Bridge::promesh::Info::Qualities Namespace Reference
ug4Bridge::promesh::Info::Qualities Namespace Reference
Functions
void PrintFaceAspectRatioHistogram (Mesh *mesh, int histogram_sections)
Prints a histogram of aspect ratios of selected faces.
void PrintFaceAspectRatios (Mesh *mesh)
Prints information on aspect ratios of selected faces.
void PrintVolumeAspectRatioHistogram (Mesh *mesh, int histogram_sections)
Prints a histogram of aspect ratios of selected volumes.
void PrintVolumeAspectRatios (Mesh *mesh)
Prints information on aspect ratios of selected volumes.
Function Documentation
PrintFaceAspectRatioHistogram()
void ug4Bridge::promesh::Info::Qualities::PrintFaceAspectRatioHistogram (Mesh * mesh, int histogram_sections)
Prints a histogram of aspect ratios of selected faces.
Parameters
[in] mesh
[in] histogram_sections
References PrintFaceAspectRatioHistogram().
Referenced by PrintFaceAspectRatioHistogram().
PrintFaceAspectRatios()
void ug4Bridge::promesh::Info::Qualities::PrintFaceAspectRatios (Mesh * mesh)
Prints information on aspect ratios of selected faces.
Parameters
[in] mesh
References PrintFaceAspectRatios().
Referenced by PrintFaceAspectRatios().
PrintVolumeAspectRatioHistogram()
void ug4Bridge::promesh::Info::Qualities::PrintVolumeAspectRatioHistogram (Mesh * mesh, int histogram_sections)
Prints a histogram of aspect ratios of selected volumes.
Parameters
[in] mesh
[in] histogram_sections
References MeasureGridArea(), MeasureGridLength(), MeasureGridVolume(), MeasureSelectionArea(), MeasureSelectionLength(), MeasureSelectionVolume(), MeasureSubsetArea(), MeasureSubsetLength(), MeasureSubsetVolume(), and PrintVolumeAspectRatioHistogram().
Referenced by PrintVolumeAspectRatioHistogram().
PrintVolumeAspectRatios()
void ug4Bridge::promesh::Info::Qualities::PrintVolumeAspectRatios (Mesh * mesh)
Prints information on aspect ratios of selected volumes.
Parameters
[in] mesh
References PrintVolumeAspectRatios().
Referenced by PrintVolumeAspectRatios().