Registry: ug4Bridge::Domain Namespace Reference
ug4Bridge::Domain Namespace Reference
Classes
class Domain
class DomainInfo
class IDomain
Functions
bool DistributeDomain (Domain *unnamed, PartitionMap *unnamed, bool unnamed)
double FaceArea (Domain *Domain, ISubsetHandler *Subset_handler, int Subset_index, size_t Grid_level)
Edge * GetEdgeByCoordinate (Domain *unnamed, double unnamed, double unnamed, double unnamed)
Face * GetFaceByCoordinate (Domain *unnamed, double unnamed, double unnamed, double unnamed)
double GetMaxEdgeLength (Domain *unnamed)
Vertex * GetVertexByCoordinate (Domain *unnamed, double unnamed, double unnamed, double unnamed)
Volume * GetVolumeByCoordinate (Domain *unnamed, double unnamed, double unnamed, double unnamed)
void LoadAndRefineDomain (Domain *Domain, const char *Filename, int NumRefines)
Loads a domain and performs global refinement.
void LoadDomain (Domain *Domain, const char *Filename)
Loads a domain.
double MaxElementDiameter (Domain *unnamed, int unnamed)
void MinimizeMemoryFootprint (Domain *unnamed)
bool PartitionDistributedDomain_LevelBased (Domain *domain, PartitionMap *partitionMap, int numPartitions, size_t level)
bool PartitionDomain_LevelBased (Domain *domain, PartitionMap *partitionMap, int numPartitions, size_t level)
bool PartitionDomain_MetisKWay (Domain *unnamed, PartitionMap *unnamed, int unnamed, size_t unnamed, int unnamed, int unnamed)
bool PartitionDomain_RegularGrid (Domain *unnamed, PartitionMap *unnamed, int unnamed, int unnamed, int unnamed, bool unnamed)
void PrintElementEdgeRatios (Domain *unnamed)
void ProjectVerticesToSphere (Domain *dom, std::vector< double > center, double radius, double eps)
void RandomizeDomain (Domain *dom, double dx, double dy, double dz)
void SaveDomain (Domain *Domain, const char *Filename)
Saves a domain.
bool SavePartitionMap (PartitionMap *PartitionMap, Domain *Domain, const char *Filename)
Saves a partition map.
void ScaleDomain (Domain *dom, double sx, double sy, double sz)
bool TestDomainInterfaces (Domain *unnamed)
void TranslateDomain (Domain *dom, double tx, double ty, double tz)
Function Documentation
DistributeDomain()
bool ug4Bridge::Domain::DistributeDomain (Domain * unnamed, PartitionMap * unnamed, bool unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References DistributeDomain().
Referenced by DistributeDomain().
FaceArea()
double ug4Bridge::Domain::FaceArea (Domain * Domain, ISubsetHandler * Subset_handler, int Subset_index, size_t Grid_level)
Parameters
[in] Domain
[in] Subset_handler
[in] Subset_index
[in] Grid_level
Returns
Area sum
References FaceArea().
GetEdgeByCoordinate()
Edge* ug4Bridge::Domain::GetEdgeByCoordinate (Domain * unnamed, double unnamed, double unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References GetEdgeByCoordinate().
Referenced by GetEdgeByCoordinate().
GetFaceByCoordinate()
Face* ug4Bridge::Domain::GetFaceByCoordinate (Domain * unnamed, double unnamed, double unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References GetFaceByCoordinate().
Referenced by GetFaceByCoordinate().
GetMaxEdgeLength()
double ug4Bridge::Domain::GetMaxEdgeLength (Domain * unnamed)
Parameters
[in] unnamed
References GetMaxEdgeLength().
GetVertexByCoordinate()
Vertex* ug4Bridge::Domain::GetVertexByCoordinate (Domain * unnamed, double unnamed, double unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References GetVertexByCoordinate().
Referenced by GetVertexByCoordinate().
GetVolumeByCoordinate()
Volume* ug4Bridge::Domain::GetVolumeByCoordinate (Domain * unnamed, double unnamed, double unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References GetVolumeByCoordinate().
Referenced by GetVolumeByCoordinate().
LoadAndRefineDomain()
void ug4Bridge::Domain::LoadAndRefineDomain (Domain * Domain, const char * Filename, int NumRefines)
Loads a domain and performs global refinement.
No help
Parameters
[in] Domain
[in] Filename
[in] NumRefines
References LoadAndRefineDomain().
LoadDomain()
void ug4Bridge::Domain::LoadDomain (Domain * Domain, const char * Filename)
Loads a domain.
No help
Parameters
[in] Domain
[in] Filename
References LoadDomain().
MaxElementDiameter()
double ug4Bridge::Domain::MaxElementDiameter (Domain * unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
References MaxElementDiameter().
MinimizeMemoryFootprint()
void ug4Bridge::Domain::MinimizeMemoryFootprint (Domain * unnamed)
Parameters
[in] unnamed
References MinimizeMemoryFootprint().
PartitionDistributedDomain_LevelBased()
bool ug4Bridge::Domain::PartitionDistributedDomain_LevelBased (Domain * domain, PartitionMap * partitionMap, int numPartitions, size_t level)
Parameters
[in] domain
[in] partitionMap
[in] numPartitions
[in] level
References PartitionDistributedDomain_LevelBased().
Referenced by PartitionDistributedDomain_LevelBased().
PartitionDomain_LevelBased()
bool ug4Bridge::Domain::PartitionDomain_LevelBased (Domain * domain, PartitionMap * partitionMap, int numPartitions, size_t level)
Parameters
[in] domain
[in] partitionMap
[in] numPartitions
[in] level
References PartitionDomain_LevelBased().
Referenced by PartitionDomain_LevelBased().
PartitionDomain_MetisKWay()
bool ug4Bridge::Domain::PartitionDomain_MetisKWay (Domain * unnamed, PartitionMap * unnamed, int unnamed, size_t unnamed, int unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References PartitionDomain_MetisKWay().
Referenced by PartitionDomain_MetisKWay().
PartitionDomain_RegularGrid()
bool ug4Bridge::Domain::PartitionDomain_RegularGrid (Domain * unnamed, PartitionMap * unnamed, int unnamed, int unnamed, int unnamed, bool unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References PartitionDomain_RegularGrid().
Referenced by PartitionDomain_RegularGrid().
PrintElementEdgeRatios()
void ug4Bridge::Domain::PrintElementEdgeRatios (Domain * unnamed)
Parameters
[in] unnamed
References PrintElementEdgeRatios().
ProjectVerticesToSphere()
void ug4Bridge::Domain::ProjectVerticesToSphere (Domain * dom, std::vector< double > center, double radius, double eps)
Parameters
[in] dom
[in] center
[in] radius
[in] eps
References ProjectVerticesToSphere().
RandomizeDomain()
void ug4Bridge::Domain::RandomizeDomain (Domain * dom, double dx, double dy, double dz)
Parameters
[in] dom
[in] dx
[in] dy
[in] dz
References RandomizeDomain().
SaveDomain()
void ug4Bridge::Domain::SaveDomain (Domain * Domain, const char * Filename)
Saves a domain.
No help
Parameters
[in] Domain
[in] Filename
References SaveDomain().
SavePartitionMap()
bool ug4Bridge::Domain::SavePartitionMap (PartitionMap * PartitionMap, Domain * Domain, const char * Filename)
Saves a partition map.
No help
Parameters
[in] PartitionMap
[in] Domain
[in] Filename
Returns
Success
References SavePartitionMap().
ScaleDomain()
void ug4Bridge::Domain::ScaleDomain (Domain * dom, double sx, double sy, double sz)
Parameters
[in] dom
[in] sx
[in] sy
[in] sz
References ScaleDomain().
TestDomainInterfaces()
bool ug4Bridge::Domain::TestDomainInterfaces (Domain * unnamed)
Parameters
[in] unnamed
References TestDomainInterfaces().
TranslateDomain()
void ug4Bridge::Domain::TranslateDomain (Domain * dom, double tx, double ty, double tz)
Parameters
[in] dom
[in] tx
[in] ty
[in] tz
References TranslateDomain().