Registry: ug4Bridge::promesh::Remeshing::RemoveDoubles Namespace Reference
ug4Bridge::promesh::Remeshing::RemoveDoubles Namespace Reference
Functions
size_t RemoveDoubleEdges (Mesh *mesh)
Removes selected duplicates of selected edges.
size_t RemoveDoubleFaces (Mesh *mesh)
Removes selected duplicates of selected faces.
size_t RemoveDoubles (Mesh *mesh, double threshold)
Removes selected vertices that are close to each other.
Function Documentation
size_t ug4Bridge::promesh::Remeshing::RemoveDoubles::RemoveDoubleEdges (Mesh * mesh)
Removes selected duplicates of selected edges.
Parameters
[in] mesh
References RemoveDoubleEdges(), and RemoveDoubles().
size_t ug4Bridge::promesh::Remeshing::RemoveDoubles::RemoveDoubleFaces (Mesh * mesh)
Removes selected duplicates of selected faces.
Parameters
[in] mesh
References RemoveDoubleFaces().
size_t ug4Bridge::promesh::Remeshing::RemoveDoubles::RemoveDoubles (Mesh * mesh, double threshold)
Removes selected vertices that are close to each other.
Parameters
[in] mesh
[in] threshold
References RemoveDoubles().