Registry: ug4Bridge::promesh::Subsets Namespace Reference
ug4Bridge::promesh::Subsets Namespace Reference
Namespaces
Separate
Functions
void AdjustSubsetsForUG3 (Mesh *mesh, bool keep_interface_subsets)
Assigns face and edge indices so that the geometry can be used with ug3.
void AdjustSubsetsForUG4 (Mesh *mesh, bool preserve_existing_subsets)
Adjusts subsets for simulation with ug4.
void AssignFaceSubsetsByAspectRatio (Mesh *mesh, int histogram_sections, bool erase_old_subsets)
Assigns subsets according to an aspect ratio histogram.
void AssignNewSubset (Mesh *mesh, const char *name, bool assign_vertices, bool assign_edges, bool assign_faces, bool assign_volumes)
Assigns selected elements to a new subset.
void AssignSubset (Mesh *mesh, int subset_index)
Assigns the selected elements to a subset.
void AssignSubsetsByQuality (Mesh *mesh, int num_sections)
Assigns the selected to a subset depending on their quality.
void AssignSubsetsFromRaster (Mesh *mesh, const char *raster_file, int raster_dimension, bool vertices, bool edges, bool faces, bool volumes)
Assigns the subset index for each element from the raster-cell in which the center of the element lies.
void AssignVolumeSubsetsByAspectRatio (Mesh *mesh, int histogram_sections, bool erase_old_subsets)
Assigns subsets according to an aspect ratio histogram.
void CopySubsetIndicesToSides (Mesh *mesh, bool selection_only, bool to_unassigned_elements_only)
Copies subset indices of selected elements to sides of those elements.
void EraseEmptySubsets (Mesh *mesh)
Erases Subsets, which do not contain any elements at all.
void EraseSubset (Mesh *mesh, int subset_index, bool erase_geometry)
Erases a subset, but not its associated geometry.
void JoinSubsets (Mesh *mesh, int target_subset_index, int subset_index_1, int subset_index_2, bool unnamed)
Joins two subsets.
void MoveSubset (Mesh *mesh, int old_subset_index, int new_subset_index)
Moves a subset to another index.
void SetSubsetName (Mesh *mesh, int subset_index, const char *name)
void SwapSubsets (Mesh *mesh, int subset_index_1, int subset_index_2)
Swaps two subsets.
void UnassignSubsets (Mesh *mesh, bool unassign_vertices, bool unassign_edges, bool unassign_faces, bool unassign_volumes)
Unassigns selected elements from any subset.
Function Documentation
AdjustSubsetsForUG3()
void ug4Bridge::promesh::Subsets::AdjustSubsetsForUG3 (Mesh * mesh, bool keep_interface_subsets)
Assigns face and edge indices so that the geometry can be used with ug3.
Parameters
[in] mesh
[in] keep_interface_subsets
References AdjustSubsetsForUG3().
AdjustSubsetsForUG4()
void ug4Bridge::promesh::Subsets::AdjustSubsetsForUG4 (Mesh * mesh, bool preserve_existing_subsets)
Adjusts subsets for simulation with ug4.
Parameters
[in] mesh
[in] preserve_existing_subsets
References AdjustSubsetsForUG4().
AssignFaceSubsetsByAspectRatio()
void ug4Bridge::promesh::Subsets::AssignFaceSubsetsByAspectRatio (Mesh * mesh, int histogram_sections, bool erase_old_subsets)
Assigns subsets according to an aspect ratio histogram.
Parameters
[in] mesh
[in] histogram_sections
[in] erase_old_subsets
References AssignFaceSubsetsByAspectRatio().
Referenced by AssignFaceSubsetsByAspectRatio().
AssignNewSubset()
void ug4Bridge::promesh::Subsets::AssignNewSubset (Mesh * mesh, const char * name, bool assign_vertices, bool assign_edges, bool assign_faces, bool assign_volumes)
Assigns selected elements to a new subset.
Parameters
[in] mesh
[in] name
[in] assign_vertices
[in] assign_edges
[in] assign_faces
[in] assign_volumes
References AssignNewSubset().
AssignSubset()
void ug4Bridge::promesh::Subsets::AssignSubset (Mesh * mesh, int subset_index)
Assigns the selected elements to a subset.
Parameters
[in] mesh
[in] subset_index
References AssignSubset().
AssignSubsetsByQuality()
void ug4Bridge::promesh::Subsets::AssignSubsetsByQuality (Mesh * mesh, int num_sections)
Assigns the selected to a subset depending on their quality.
Parameters
[in] mesh
[in] num_sections
References AssignSubsetsByQuality().
AssignSubsetsFromRaster()
void ug4Bridge::promesh::Subsets::AssignSubsetsFromRaster (Mesh * mesh, const char * raster_file, int raster_dimension, bool vertices, bool edges, bool faces, bool volumes)
Assigns the subset index for each element from the raster-cell in which the center of the element lies.
Parameters
[in] mesh
[in] raster_file
[in] raster_dimension
[in] vertices
[in] edges
[in] faces
[in] volumes
References AssignSubsetsFromRaster().
AssignVolumeSubsetsByAspectRatio()
void ug4Bridge::promesh::Subsets::AssignVolumeSubsetsByAspectRatio (Mesh * mesh, int histogram_sections, bool erase_old_subsets)
Assigns subsets according to an aspect ratio histogram.
Parameters
[in] mesh
[in] histogram_sections
[in] erase_old_subsets
References AssignVolumeSubsetsByAspectRatio().
Referenced by AssignVolumeSubsetsByAspectRatio().
CopySubsetIndicesToSides()
void ug4Bridge::promesh::Subsets::CopySubsetIndicesToSides (Mesh * mesh, bool selection_only, bool to_unassigned_elements_only)
Copies subset indices of selected elements to sides of those elements.
Parameters
[in] mesh
[in] selection_only
[in] to_unassigned_elements_only
References CopySubsetIndicesToSides().
EraseEmptySubsets()
void ug4Bridge::promesh::Subsets::EraseEmptySubsets (Mesh * mesh)
Erases Subsets, which do not contain any elements at all.
Parameters
[in] mesh
References EraseEmptySubsets().
EraseSubset()
void ug4Bridge::promesh::Subsets::EraseSubset (Mesh * mesh, int subset_index, bool erase_geometry)
Erases a subset, but not its associated geometry.
Parameters
[in] mesh
[in] subset_index
[in] erase_geometry
References EraseSubset().
JoinSubsets()
void ug4Bridge::promesh::Subsets::JoinSubsets (Mesh * mesh, int target_subset_index, int subset_index_1, int subset_index_2, bool unnamed)
Joins two subsets.
Parameters
[in] mesh
[in] target_subset_index
[in] subset_index_1
[in] subset_index_2
[in] unnamed
References JoinSubsets().
MoveSubset()
void ug4Bridge::promesh::Subsets::MoveSubset (Mesh * mesh, int old_subset_index, int new_subset_index)
Moves a subset to another index.
Parameters
[in] mesh
[in] old_subset_index
[in] new_subset_index
References MoveSubset().
SetSubsetName()
void ug4Bridge::promesh::Subsets::SetSubsetName (Mesh * mesh, int subset_index, const char * name)
Parameters
[in] mesh
[in] subset_index
[in] name
References SetSubsetName().
SwapSubsets()
void ug4Bridge::promesh::Subsets::SwapSubsets (Mesh * mesh, int subset_index_1, int subset_index_2)
Swaps two subsets.
Parameters
[in] mesh
[in] subset_index_1
[in] subset_index_2
References SwapSubsets().
UnassignSubsets()
void ug4Bridge::promesh::Subsets::UnassignSubsets (Mesh * mesh, bool unassign_vertices, bool unassign_edges, bool unassign_faces, bool unassign_volumes)
Unassigns selected elements from any subset.
Parameters
[in] mesh
[in] unassign_vertices
[in] unassign_edges
[in] unassign_faces
[in] unassign_volumes
References UnassignSubsets().