Registry: ug4Bridge::promesh::RasterLayers Namespace Reference
ug4Bridge::promesh::RasterLayers Namespace Reference
Functions
void ExtrudeLayers (Mesh *mesh, RasterLayers *layers, bool allow_for_tets_and_pyras)
Creates volumes for a given stack of raster-layers and an initial triangulation of the surface.
void ExtrudeLayersAndAddProjector (Mesh *mesh, SmartPtr< RasterLayers > layers, bool allow_for_tets_and_pyras)
Creates volumes for a given stack of raster-layers and an initial triangulation of the surface. It also generates a raster-based refinement-projector for the whole geometry.
void MeshLayerBoundaries (Mesh *mesh, const RasterLayers *layers)
Creates boundary grids for the given raster-layers.
void MeshLayers (Mesh *mesh, const RasterLayers *layers)
Creates triangle/quadrilateral grids for the given raster-layers.
void ProjectToLayer (Mesh *mesh, RasterLayers *layers, int layer_index)
Projects a (surface-)mesh to the specified raster-layer. Only height values in valid regions are adjusted.
void ProjectToTopLayer (Mesh *mesh, RasterLayers *layers)
Projects a (surface-)mesh to the top-layer of the specified raster-stack. Only height values in valid regions are adjusted.
void SnapToHorizontalRaster (Mesh *mesh, SmartPtr< RasterLayers > layers)
Snaps all vertices of the given (surface) grid horizontally to the closest raster-node.
Function Documentation
ExtrudeLayers()
void ug4Bridge::promesh::RasterLayers::ExtrudeLayers (Mesh * mesh, RasterLayers * layers, bool allow_for_tets_and_pyras)
Creates volumes for a given stack of raster-layers and an initial triangulation of the surface.
Parameters
[in] mesh
[in] layers
[in] allow_for_tets_and_pyras
References ExtrudeLayers().
ExtrudeLayersAndAddProjector()
void ug4Bridge::promesh::RasterLayers::ExtrudeLayersAndAddProjector (Mesh * mesh, SmartPtr< RasterLayers > layers, bool allow_for_tets_and_pyras)
Creates volumes for a given stack of raster-layers and an initial triangulation of the surface. It also generates a raster-based refinement-projector for the whole geometry.
Parameters
[in] mesh
[in] layers
[in] allow_for_tets_and_pyras
References ExtrudeLayersAndAddProjector().
MeshLayerBoundaries()
void ug4Bridge::promesh::RasterLayers::MeshLayerBoundaries (Mesh * mesh, const RasterLayers * layers)
Creates boundary grids for the given raster-layers.
Parameters
[in] mesh
[in] layers
References MeshLayerBoundaries().
MeshLayers()
void ug4Bridge::promesh::RasterLayers::MeshLayers (Mesh * mesh, const RasterLayers * layers)
Creates triangle/quadrilateral grids for the given raster-layers.
Parameters
[in] mesh
[in] layers
References MeshLayers().
ProjectToLayer()
void ug4Bridge::promesh::RasterLayers::ProjectToLayer (Mesh * mesh, RasterLayers * layers, int layer_index)
Projects a (surface-)mesh to the specified raster-layer. Only height values in valid regions are adjusted.
Parameters
[in] mesh
[in] layers
[in] layer_index
References ProjectToLayer().
ProjectToTopLayer()
void ug4Bridge::promesh::RasterLayers::ProjectToTopLayer (Mesh * mesh, RasterLayers * layers)
Projects a (surface-)mesh to the top-layer of the specified raster-stack. Only height values in valid regions are adjusted.
Parameters
[in] mesh
[in] layers
References ProjectToTopLayer().
SnapToHorizontalRaster()
void ug4Bridge::promesh::RasterLayers::SnapToHorizontalRaster (Mesh * mesh, SmartPtr< RasterLayers > layers)
Snaps all vertices of the given (surface) grid horizontally to the closest raster-node.
Parameters
[in] mesh
[in] layers
References SnapToHorizontalRaster().