Registry: ug4Bridge::Algebra::Operation Namespace Reference
ug4Bridge::Algebra::Operation Namespace Reference
Functions
void MatAdd (MatrixOperator *res, double alpha1, MatrixOperator *A1, double alpha2, MatrixOperator *A2)
calculates res = alpha1*A1 + alpha2*A2
void MatIdentity (MatrixOperator *opOut)
sets matrix to identity
void MatScale (MatrixOperator *mat, double alpha)
calculates mat = mat*alpha
void MatTranspose (MatrixOperator *matTranspose, MatrixOperator *mat)
calculates matTranspose = mat^T
Function Documentation
MatAdd()
void ug4Bridge::Algebra::Operation::MatAdd (MatrixOperator * res, double alpha1, MatrixOperator * A1, double alpha2, MatrixOperator * A2)
calculates res = alpha1*A1 + alpha2*A2
Parameters
[in] res
[in] alpha1
[in] A1
[in] alpha2
[in] A2
References Algebra(), and MatAdd().
MatIdentity()
void ug4Bridge::Algebra::Operation::MatIdentity (MatrixOperator * opOut)
sets matrix to identity
Parameters
[in] opOut
References Algebra(), and MatIdentity().
MatScale()
void ug4Bridge::Algebra::Operation::MatScale (MatrixOperator * mat, double alpha)
calculates mat = mat*alpha
Parameters
[in] mat
[in] alpha
References Algebra(), and MatScale().
MatTranspose()
void ug4Bridge::Algebra::Operation::MatTranspose (MatrixOperator * matTranspose, MatrixOperator * mat)
calculates matTranspose = mat^T
Parameters
[in] matTranspose
[in] mat
References MatTranspose().