Registry: ug4Bridge::promesh::Remeshing::Extrusion Namespace Reference
ug4Bridge::promesh::Remeshing::Extrusion Namespace Reference
Functions
void Extrude (Mesh *mesh, const Vec3d *total_direction, int num_steps, bool create_faces, bool create_volumes)
Extrudes selected geometry (vertices, edges, faces) and moves new vertices by the specified offset.
void ExtrudeAlongNormal (Mesh *mesh, double total_length, int num_steps, bool create_faces, bool create_volumes)
Extrudes selected geometry (vertices, edges, faces) and moves new vertices along their normal.
void ExtrudeAndMove (Mesh *mesh, const Vec3d *total_direction, int num_steps, bool create_faces, bool create_volumes)
Extrudes selected geometry (vertices, edges, faces) and moves new vertices by the specified offset.
void ExtrudeAndScale (Mesh *mesh, double total_scale, bool scale_around_pivot, int num_steps, bool create_faces, bool create_volumes)
Extrudes selected geometry (vertices, edges, faces) and scales new vertices by the specified scale.
void ExtrudeCylinders (Mesh *mesh, double height, double radius, double snap_threshold)
Extrudes cylinders around selected points of a 2d manifold.
Function Documentation
Extrude()
void ug4Bridge::promesh::Remeshing::Extrusion::Extrude (Mesh * mesh, const Vec3d * total_direction, int num_steps, bool create_faces, bool create_volumes)
Extrudes selected geometry (vertices, edges, faces) and moves new vertices by the specified offset.
Parameters
[in] mesh
[in] total_direction
[in] num_steps
[in] create_faces
[in] create_volumes
References Extrude().
ExtrudeAlongNormal()
void ug4Bridge::promesh::Remeshing::Extrusion::ExtrudeAlongNormal (Mesh * mesh, double total_length, int num_steps, bool create_faces, bool create_volumes)
Extrudes selected geometry (vertices, edges, faces) and moves new vertices along their normal.
Parameters
[in] mesh
[in] total_length
[in] num_steps
[in] create_faces
[in] create_volumes
References ExtrudeAlongNormal().
ExtrudeAndMove()
void ug4Bridge::promesh::Remeshing::Extrusion::ExtrudeAndMove (Mesh * mesh, const Vec3d * total_direction, int num_steps, bool create_faces, bool create_volumes)
Extrudes selected geometry (vertices, edges, faces) and moves new vertices by the specified offset.
Parameters
[in] mesh
[in] total_direction
[in] num_steps
[in] create_faces
[in] create_volumes
References ExtrudeAndMove().
ExtrudeAndScale()
void ug4Bridge::promesh::Remeshing::Extrusion::ExtrudeAndScale (Mesh * mesh, double total_scale, bool scale_around_pivot, int num_steps, bool create_faces, bool create_volumes)
Extrudes selected geometry (vertices, edges, faces) and scales new vertices by the specified scale.
Parameters
[in] mesh
[in] total_scale
[in] scale_around_pivot
[in] num_steps
[in] create_faces
[in] create_volumes
References ExtrudeAndScale().
ExtrudeCylinders()
void ug4Bridge::promesh::Remeshing::Extrusion::ExtrudeCylinders (Mesh * mesh, double height, double radius, double snap_threshold)
Extrudes cylinders around selected points of a 2d manifold.
Parameters
[in] mesh
[in] height
[in] radius
[in] snap_threshold
References ExtrudeCylinders().