Registry: ug4Bridge::promesh::Selection::CoordinateRange Namespace Reference
ug4Bridge::promesh::Selection::CoordinateRange Namespace Reference
Functions
void DeselectElementsByRangeX (Mesh *mesh, double min, double max, bool deselect_vrts, bool deselect_edges, bool deselect_faces, bool deselect_volumes)
Deselects all elements whose center lies in the specified range.
void DeselectElementsByRangeY (Mesh *mesh, double min, double max, bool deselect_vrts, bool deselect_edges, bool deselect_faces, bool deselect_volumes)
Deselects all elements whose center lies in the specified range.
void DeselectElementsByRangeZ (Mesh *mesh, double min, double max, bool deselect_vrts, bool deselect_edges, bool deselect_faces, bool deselect_volumes)
Deselects all elements whose center lies in the specified range.
void SelectElementsByRangeX (Mesh *mesh, double min, double max, bool select_vrts, bool select_edges, bool select_faces, bool select_volumes)
Selects all elements whose center lies in the specified range.
void SelectElementsByRangeY (Mesh *mesh, double min, double max, bool select_vrts, bool select_edges, bool select_faces, bool select_volumes)
Selects all elements whose center lies in the specified range.
void SelectElementsByRangeZ (Mesh *mesh, double min, double max, bool select_vrts, bool select_edges, bool select_faces, bool select_volumes)
Selects all elements whose center lies in the specified range.
void SelectElementsBySplitPlane (Mesh *mesh, bool select_vrts, bool select_edges, bool select_faces, bool select_volumes, const Vec *pivot, const Vec *normal)
Selects elements whose center lies in front of the specified plane.
Function Documentation
DeselectElementsByRangeX()
void ug4Bridge::promesh::Selection::CoordinateRange::DeselectElementsByRangeX (Mesh * mesh, double min, double max, bool deselect_vrts, bool deselect_edges, bool deselect_faces, bool deselect_volumes)
Deselects all elements whose center lies in the specified range.
Parameters
[in] mesh
[in] min
[in] max
[in] deselect_vrts
[in] deselect_edges
[in] deselect_faces
[in] deselect_volumes
References DeselectElementsByRangeX().
Referenced by DeselectElementsByRangeX().
DeselectElementsByRangeY()
void ug4Bridge::promesh::Selection::CoordinateRange::DeselectElementsByRangeY (Mesh * mesh, double min, double max, bool deselect_vrts, bool deselect_edges, bool deselect_faces, bool deselect_volumes)
Deselects all elements whose center lies in the specified range.
Parameters
[in] mesh
[in] min
[in] max
[in] deselect_vrts
[in] deselect_edges
[in] deselect_faces
[in] deselect_volumes
References DeselectElementsByRangeY().
Referenced by DeselectElementsByRangeY().
DeselectElementsByRangeZ()
void ug4Bridge::promesh::Selection::CoordinateRange::DeselectElementsByRangeZ (Mesh * mesh, double min, double max, bool deselect_vrts, bool deselect_edges, bool deselect_faces, bool deselect_volumes)
Deselects all elements whose center lies in the specified range.
Parameters
[in] mesh
[in] min
[in] max
[in] deselect_vrts
[in] deselect_edges
[in] deselect_faces
[in] deselect_volumes
References DeselectElementsByRangeZ().
Referenced by DeselectElementsByRangeZ().
SelectElementsByRangeX()
void ug4Bridge::promesh::Selection::CoordinateRange::SelectElementsByRangeX (Mesh * mesh, double min, double max, bool select_vrts, bool select_edges, bool select_faces, bool select_volumes)
Selects all elements whose center lies in the specified range.
Parameters
[in] mesh
[in] min
[in] max
[in] select_vrts
[in] select_edges
[in] select_faces
[in] select_volumes
References SelectElementsByRangeX().
Referenced by SelectElementsByRangeX().
SelectElementsByRangeY()
void ug4Bridge::promesh::Selection::CoordinateRange::SelectElementsByRangeY (Mesh * mesh, double min, double max, bool select_vrts, bool select_edges, bool select_faces, bool select_volumes)
Selects all elements whose center lies in the specified range.
Parameters
[in] mesh
[in] min
[in] max
[in] select_vrts
[in] select_edges
[in] select_faces
[in] select_volumes
References SelectElementsByRangeY().
Referenced by SelectElementsByRangeY().
SelectElementsByRangeZ()
void ug4Bridge::promesh::Selection::CoordinateRange::SelectElementsByRangeZ (Mesh * mesh, double min, double max, bool select_vrts, bool select_edges, bool select_faces, bool select_volumes)
Selects all elements whose center lies in the specified range.
Parameters
[in] mesh
[in] min
[in] max
[in] select_vrts
[in] select_edges
[in] select_faces
[in] select_volumes
References SelectElementsByRangeZ().
Referenced by SelectElementsByRangeZ().
SelectElementsBySplitPlane()
void ug4Bridge::promesh::Selection::CoordinateRange::SelectElementsBySplitPlane (Mesh * mesh, bool select_vrts, bool select_edges, bool select_faces, bool select_volumes, const Vec * pivot, const Vec * normal)
Selects elements whose center lies in front of the specified plane.
Parameters
[in] mesh
[in] select_vrts
[in] select_edges
[in] select_faces
[in] select_volumes
[in] pivot
[in] normal
References SelectElementsBySplitPlane().