Registry: ug4Bridge::promesh::Remeshing::ResolveIntersections::Advanced Namespace Reference
ug4Bridge::promesh::Remeshing::ResolveIntersections::Advanced Namespace Reference
Functions
void IntersectCloseEdges (Mesh *mesh, double snap_threshold)
Performs intersections between selected close edges.
void ProjectVerticesToCloseEdges (Mesh *mesh, double snap_threshold)
Projects selected vertices to selected close edges.
void ProjectVerticesToCloseFaces (Mesh *mesh, double snap_threshold)
Projects selected vertices to selected close faces.
void ResolveEdgeIntersection (Mesh *mesh, double snap_threshold)
Makes sure that all edge intersections are represented by a vertex.
void ResolveTriangleIntersections (Mesh *mesh, double snap_threshold)
Makes sure that all triangle intersections are represented by an edge and vertices.
Function Documentation
IntersectCloseEdges()
void ug4Bridge::promesh::Remeshing::ResolveIntersections::Advanced::IntersectCloseEdges (Mesh * mesh, double snap_threshold)
Performs intersections between selected close edges.
Parameters
[in] mesh
[in] snap_threshold
References IntersectCloseEdges().
ProjectVerticesToCloseEdges()
void ug4Bridge::promesh::Remeshing::ResolveIntersections::Advanced::ProjectVerticesToCloseEdges (Mesh * mesh, double snap_threshold)
Projects selected vertices to selected close edges.
Parameters
[in] mesh
[in] snap_threshold
References ProjectVerticesToCloseEdges().
ProjectVerticesToCloseFaces()
void ug4Bridge::promesh::Remeshing::ResolveIntersections::Advanced::ProjectVerticesToCloseFaces (Mesh * mesh, double snap_threshold)
Projects selected vertices to selected close faces.
Parameters
[in] mesh
[in] snap_threshold
References ProjectVerticesToCloseFaces().
ResolveEdgeIntersection()
void ug4Bridge::promesh::Remeshing::ResolveIntersections::Advanced::ResolveEdgeIntersection (Mesh * mesh, double snap_threshold)
Makes sure that all edge intersections are represented by a vertex.
Parameters
[in] mesh
[in] snap_threshold
References ResolveEdgeIntersection().
ResolveTriangleIntersections()
void ug4Bridge::promesh::Remeshing::ResolveIntersections::Advanced::ResolveTriangleIntersections (Mesh * mesh, double snap_threshold)
Makes sure that all triangle intersections are represented by an edge and vertices.
Parameters
[in] mesh
[in] snap_threshold
References ResolveTriangleIntersections().