Registry: ug4Bridge::promesh::Selection::Faces::CoordinateBased Namespace Reference
ug4Bridge::promesh::Selection::Faces::CoordinateBased Namespace Reference
Functions
Face * SelectFaceByCoordinate (Mesh *mesh, const Vec3d *coordinate)
Selects the face whose center is closest to the specified coordinate.
Face * SelectFaceByCylindricalCoordinate (Mesh *mesh, double rho, double phi, double z)
Selects the face whose center is closest to the specified cylindrical coordinate.
void SelectFacesInBox (Mesh *mesh, const Vec3d *min, const Vec3d *max)
Selects all faces in the given box.
void SelectFacesInCylinder (Mesh *mesh, const Vec3d *base, const Vec3d *top, double radius)
Selects all faces in the given cylinder.
Function Documentation
SelectFaceByCoordinate()
Face* ug4Bridge::promesh::Selection::Faces::CoordinateBased::SelectFaceByCoordinate (Mesh * mesh, const Vec3d * coordinate)
Selects the face whose center is closest to the specified coordinate.
Parameters
[in] mesh
[in] coordinate
References SelectFaceByCoordinate().
Referenced by SelectFaceByCoordinate().
SelectFaceByCylindricalCoordinate()
Face* ug4Bridge::promesh::Selection::Faces::CoordinateBased::SelectFaceByCylindricalCoordinate (Mesh * mesh, double rho, double phi, double z)
Selects the face whose center is closest to the specified cylindrical coordinate.
Parameters
[in] mesh
[in] rho
[in] phi
[in] z
References SelectFaceByCylindricalCoordinate().
Referenced by SelectFaceByCylindricalCoordinate().
SelectFacesInBox()
void ug4Bridge::promesh::Selection::Faces::CoordinateBased::SelectFacesInBox (Mesh * mesh, const Vec3d * min, const Vec3d * max)
Selects all faces in the given box.
Parameters
[in] mesh
[in] min
[in] max
References SelectFacesInBox().
Referenced by SelectFacesInBox().
SelectFacesInCylinder()
void ug4Bridge::promesh::Selection::Faces::CoordinateBased::SelectFacesInCylinder (Mesh * mesh, const Vec3d * base, const Vec3d * top, double radius)
Selects all faces in the given cylinder.
Parameters
[in] mesh
[in] base
[in] top
[in] radius
References SelectFacesInCylinder().
Referenced by SelectFacesInCylinder().