Registry: ug4Bridge::promesh::FileIO Namespace Reference
ug4Bridge::promesh::FileIO Namespace Reference
Functions
bool ExportToUG3 (Mesh *mesh, const char *filenamePrefix, const char *lgmName, const char *problemName)
Writes a mesh to the UG3 legacy format (.lgm and .ng)
bool LoadMesh (Mesh *mesh, const char *filename)
Loads a Mesh from File. The format is automatically recognized by the filname's suffix. Supported formats are: (ugx, vtu (ascii), obj, stl (ascii and binary), lgm, ng, ele, msh, asc, net, art).
bool SaveMesh (Mesh *mesh, const char *filename)
Saves a Mesh to File. The format is automatically recognized by the filname's suffix. Supported formats are: (ugx, vtu (ascii), obj, stl (ascii), ncdf, smesh, ele, tikz/tex, asc, net, art).
Function Documentation
ExportToUG3()
bool ug4Bridge::promesh::FileIO::ExportToUG3 (Mesh * mesh, const char * filenamePrefix, const char * lgmName, const char * problemName)
Writes a mesh to the UG3 legacy format (.lgm and .ng)
Parameters
[in] mesh
[in] filenamePrefix
[in] lgmName
[in] problemName
References ExportToUG3().
LoadMesh()
bool ug4Bridge::promesh::FileIO::LoadMesh (Mesh * mesh, const char * filename)
Loads a Mesh from File. The format is automatically recognized by the filname's suffix. Supported formats are: (ugx, vtu (ascii), obj, stl (ascii and binary), lgm, ng, ele, msh, asc, net, art).
Parameters
[in] mesh
[in] filename
References LoadMesh().
SaveMesh()
bool ug4Bridge::promesh::FileIO::SaveMesh (Mesh * mesh, const char * filename)
Saves a Mesh to File. The format is automatically recognized by the filname's suffix. Supported formats are: (ugx, vtu (ascii), obj, stl (ascii), ncdf, smesh, ele, tikz/tex, asc, net, art).
Parameters
[in] mesh
[in] filename
References SaveMesh().