Registry: ug4Bridge::promesh::GridGeneration::Geometries Namespace Reference
ug4Bridge::promesh::GridGeneration::Geometries Namespace Reference
Functions
void CreateBox (Mesh *mesh, const Vec3d *boxMin, const Vec3d *boxMax, int subset_index, bool create_volume)
Creates a box.
void CreateCircle (Mesh *mesh, const Vec3d *center, double radius, int num_rim_vertices, int subset_index, bool fill)
Creates a circle.
void CreatePlane (Mesh *mesh, const Vec3d *upLeft, const Vec3d *upRight, const Vec3d *lowLeft, const Vec3d *lowRight, int subset_index, bool fill)
Creates a plane.
void CreatePrism (Mesh *mesh, int subset_index, bool create_volume)
Creates a prism.
void CreatePyramid (Mesh *mesh, int subset_index, bool create_volume)
Creates a pyramid.
void CreateSphere (Mesh *mesh, const Vec3d *center, double radius, int num_refinements, int subset_index)
Creates a sphere.
void CreateTetrahedron (Mesh *mesh, int subset_index, bool create_volume)
Creates a tetrahedron.
Function Documentation
void ug4Bridge::promesh::GridGeneration::Geometries::CreateBox (Mesh * mesh, const Vec3d * boxMin, const Vec3d * boxMax, int subset_index, bool create_volume)
Creates a box.
Parameters
[in] mesh
[in] boxMin
[in] boxMax
[in] subset_index
[in] create_volume
References CreateBox().
void ug4Bridge::promesh::GridGeneration::Geometries::CreateCircle (Mesh * mesh, const Vec3d * center, double radius, int num_rim_vertices, int subset_index, bool fill)
Creates a circle.
Parameters
[in] mesh
[in] center
[in] radius
[in] num_rim_vertices
[in] subset_index
[in] fill
References CreateCircle().
void ug4Bridge::promesh::GridGeneration::Geometries::CreatePlane (Mesh * mesh, const Vec3d * upLeft, const Vec3d * upRight, const Vec3d * lowLeft, const Vec3d * lowRight, int subset_index, bool fill)
Creates a plane.
Parameters
[in] mesh
[in] upLeft
[in] upRight
[in] lowLeft
[in] lowRight
[in] subset_index
[in] fill
References CreatePlane().
void ug4Bridge::promesh::GridGeneration::Geometries::CreatePrism (Mesh * mesh, int subset_index, bool create_volume)
Creates a prism.
Parameters
[in] mesh
[in] subset_index
[in] create_volume
References CreatePrism().
void ug4Bridge::promesh::GridGeneration::Geometries::CreatePyramid (Mesh * mesh, int subset_index, bool create_volume)
Creates a pyramid.
Parameters
[in] mesh
[in] subset_index
[in] create_volume
References CreatePyramid().
void ug4Bridge::promesh::GridGeneration::Geometries::CreateSphere (Mesh * mesh, const Vec3d * center, double radius, int num_refinements, int subset_index)
Creates a sphere.
Parameters
[in] mesh
[in] center
[in] radius
[in] num_refinements
[in] subset_index
References CreateSphere().
void ug4Bridge::promesh::GridGeneration::Geometries::CreateTetrahedron (Mesh * mesh, int subset_index, bool create_volume)
Creates a tetrahedron.
Parameters
[in] mesh
[in] subset_index
[in] create_volume
References CreateTetrahedron().