Registry: ug4Bridge::Util::Log Namespace Reference
ug4Bridge::Util::Log Namespace Reference
Classes
class LogAssistant
Functions
void errlog (const char *msg)
prints the specified message to the error-stream.
double GetClockS ()
use this instead of os.clock() since os.clock only returns CPU time.
LogAssistant * GetLogAssistant ()
void PrintLUA ()
Function Documentation
errlog()
void ug4Bridge::Util::Log::errlog (const char * msg)
prints the specified message to the error-stream.
Parameters
[in] msg
References errlog().
GetClockS()
double ug4Bridge::Util::Log::GetClockS ()
use this instead of os.clock() since os.clock only returns CPU time.
Returns
seconds since 1970
References GetClockS(), and Log().
GetLogAssistant()
LogAssistant* ug4Bridge::Util::Log::GetLogAssistant ()
Returns
the log assistant
References GetLogAssistant(), and Log().
PrintLUA()
void ug4Bridge::Util::Log::PrintLUA ()
References Log(), and PrintLUA().