Registry: ug4Bridge::promesh::Selection::Vertices Namespace Reference
ug4Bridge::promesh::Selection::Vertices Namespace Reference
Functions
void DeselectAllVertices (Mesh *mesh)
Deselects all vertices of the current grid.
void SelectAllVertices (Mesh *mesh)
Selects all vertices of the current grid.
void SelectAssociatedVertices (Mesh *mesh)
Selects vertices that belong to selected edges, faces and volumes.
void SelectBoundaryVertices (Mesh *mesh)
Selects vertices that lie on the boundary of the geometry.
void SelectInnerVertices (Mesh *mesh)
Selects vertices that do not lie on the boundary of the geometry.
void SelectInterfaceVertices (Mesh *mesh, bool regard_selected_neighbors_only)
Selects elements which are adjacent to higher dimensional elements of different subsets.
void SelectMarkedVertices (Mesh *mesh)
Selects vertices which are marked.
size_t SelectSelectionKinkVertices (Mesh *mesh, double threshold_angle, bool select_darts)
Selects kink vertices in selected paths.
size_t SelectSubsetKinkVertices (Mesh *mesh, int subset_index, double threshold_angle, bool select_darts)
Selects kink vertices in subset-paths.
size_t SelectUnconnectedVertices (Mesh *mesh, bool unconnected_to_edges, bool unconnected_to_faces, bool unconnected_to_volumes)
Selects vertices which are not connected to the given element type.
Vertex * SelectVertexByCoordinate (Mesh *mesh, const Vec3d *coordinate)
Selects a vertex given a coordinate.
Vertex * SelectVertexByCylindricalCoordinate (Mesh *mesh, double rho, double phi, double z)
Selects a vertex given a cylindrical coordinate.
bool SelectVertexByIndex (Mesh *mesh, int index)
Selects a vertex given its index.
void SelectVerticesInBox (Mesh *mesh, const Vec3d *min, const Vec3d *max)
Selects all vertices in the given box.
void SelectVerticesInCylinder (Mesh *mesh, const Vec3d *base, const Vec3d *top, double radius)
Selects all vertices in the given cylinder.
Function Documentation
void ug4Bridge::promesh::Selection::Vertices::DeselectAllVertices (Mesh * mesh)
Deselects all vertices of the current grid.
Parameters
[in] mesh
References DeselectAllVertices().
void ug4Bridge::promesh::Selection::Vertices::SelectAllVertices (Mesh * mesh)
Selects all vertices of the current grid.
Parameters
[in] mesh
References SelectAllVertices().
void ug4Bridge::promesh::Selection::Vertices::SelectAssociatedVertices (Mesh * mesh)
Selects vertices that belong to selected edges, faces and volumes.
Parameters
[in] mesh
References SelectAssociatedVertices().
void ug4Bridge::promesh::Selection::Vertices::SelectBoundaryVertices (Mesh * mesh)
Selects vertices that lie on the boundary of the geometry.
Parameters
[in] mesh
References SelectBoundaryVertices().
void ug4Bridge::promesh::Selection::Vertices::SelectInnerVertices (Mesh * mesh)
Selects vertices that do not lie on the boundary of the geometry.
Parameters
[in] mesh
References SelectInnerVertices().
void ug4Bridge::promesh::Selection::Vertices::SelectInterfaceVertices (Mesh * mesh, bool regard_selected_neighbors_only)
Selects elements which are adjacent to higher dimensional elements of different subsets.
Parameters
[in] mesh
[in] regard_selected_neighbors_only
References SelectInterfaceVertices().
Referenced by SelectInterfaceVertices().
void ug4Bridge::promesh::Selection::Vertices::SelectMarkedVertices (Mesh * mesh)
Selects vertices which are marked.
Parameters
[in] mesh
References SelectMarkedVertices().
size_t ug4Bridge::promesh::Selection::Vertices::SelectSelectionKinkVertices (Mesh * mesh, double threshold_angle, bool select_darts)
Selects kink vertices in selected paths.
Parameters
[in] mesh
[in] threshold_angle
[in] select_darts
Returns
num selected
References SelectSelectionKinkVertices().
size_t ug4Bridge::promesh::Selection::Vertices::SelectSubsetKinkVertices (Mesh * mesh, int subset_index, double threshold_angle, bool select_darts)
Selects kink vertices in subset-paths.
Parameters
[in] mesh
[in] subset_index
[in] threshold_angle
[in] select_darts
Returns
num selected
References SelectSubsetKinkVertices().
size_t ug4Bridge::promesh::Selection::Vertices::SelectUnconnectedVertices (Mesh * mesh, bool unconnected_to_edges, bool unconnected_to_faces, bool unconnected_to_volumes)
Selects vertices which are not connected to the given element type.
Parameters
[in] mesh
[in] unconnected_to_edges
[in] unconnected_to_faces
[in] unconnected_to_volumes
Returns
size_t
References SelectUnconnectedVertices().
Vertex* ug4Bridge::promesh::Selection::Vertices::SelectVertexByCoordinate (Mesh * mesh, const Vec3d * coordinate)
Selects a vertex given a coordinate.
Parameters
[in] mesh
[in] coordinate
References SelectVertexByCoordinate().
Referenced by SelectVertexByCoordinate().
Vertex* ug4Bridge::promesh::Selection::Vertices::SelectVertexByCylindricalCoordinate (Mesh * mesh, double rho, double phi, double z)
Selects a vertex given a cylindrical coordinate.
Parameters
[in] mesh
[in] rho
[in] phi
[in] z
References SelectVertexByCylindricalCoordinate().
Referenced by SelectVertexByCylindricalCoordinate().
bool ug4Bridge::promesh::Selection::Vertices::SelectVertexByIndex (Mesh * mesh, int index)
Selects a vertex given its index.
Parameters
[in] mesh
[in] index
Returns
bool
References SelectVertexByIndex().
void ug4Bridge::promesh::Selection::Vertices::SelectVerticesInBox (Mesh * mesh, const Vec3d * min, const Vec3d * max)
Selects all vertices in the given box.
Parameters
[in] mesh
[in] min
[in] max
References SelectVerticesInBox().
Referenced by SelectVerticesInBox().
void ug4Bridge::promesh::Selection::Vertices::SelectVerticesInCylinder (Mesh * mesh, const Vec3d * base, const Vec3d * top, double radius)
Selects all vertices in the given cylinder.
Parameters
[in] mesh
[in] base
[in] top
[in] radius
References SelectVerticesInCylinder().
Referenced by SelectVerticesInCylinder().