Registry: ug4Bridge::promesh::Selection::Edges Namespace Reference
ug4Bridge::promesh::Selection::Edges Namespace Reference
Functions
void DeselectAllEdges (Mesh *mesh)
Deselects all edges of the current grid.
void EdgeSelectionFill (Mesh *mesh)
Selects neighbours of selected edges over non-selected vertices.
void SelectAllEdges (Mesh *mesh)
Selects all edges of the current grid.
void SelectAssociatedEdges (Mesh *mesh)
Selects edges that belong to selected faces and volumes.
void SelectBoundaryEdges (Mesh *mesh)
Selects edges that lie on the boundary of the geometry.
void SelectCreaseEdges (Mesh *mesh, double min_angle)
Selects edges that at which triangles meet in a given angle.
Edge * SelectEdgeByCoordinate (Mesh *mesh, const Vec3d *coordinate)
Selects the edge whose center is closest to the specified coordinate.
Edge * SelectEdgeByCylindricalCoordinate (Mesh *mesh, double rho, double phi, double z)
Selects the edge whose center is closest to the specified cylindrical coordinate.
bool SelectEdgeByIndex (Mesh *mesh, int index)
Selects a edge given its index.
void SelectEdgesInBox (Mesh *mesh, const Vec3d *min, const Vec3d *max)
Selects all edges in the given box.
void SelectEdgesInCylinder (Mesh *mesh, const Vec3d *base, const Vec3d *top, double radius)
Selects all edges in the given cylinder.
void SelectInnerEdges (Mesh *mesh)
Selects edges that do not lie on the boundary of the geometry.
void SelectInterfaceEdges (Mesh *mesh, bool regard_selected_neighbors_only)
Selects elements which are adjacent to higher dimensional elements of different subsets.
void SelectLinkedBoundaryEdges (Mesh *mesh, bool stop_at_selected_vertices)
Selects linked boundary edges of selected edges.
void SelectLinkedEdges (Mesh *mesh)
Repeatedly selects all edges which are vertex-neighbors of selected edges.
void SelectLongEdges (Mesh *mesh, double min_length)
Selects edges that are longer than a given threshold.
void SelectMarkedEdges (Mesh *mesh)
Selects edges which are marked.
void SelectNonManifoldEdges (Mesh *mesh)
Selects edges with more than 2 associated faces.
void SelectShortEdges (Mesh *mesh, double max_length)
Selects edges that are shorter than a given threshold.
void SelectShortPolychains (Mesh *mesh, double maxChainLength, bool closedChainsOnly)
Selects polygonal chains which are shorter than the given threshold.
void SelectSmoothEdgePath (Mesh *mesh, double max_deviation_angle, double normal_weight, bool stop_at_selected_vertices)
Selects a smooth edge path.
Function Documentation
void ug4Bridge::promesh::Selection::Edges::DeselectAllEdges (Mesh * mesh)
Deselects all edges of the current grid.
Parameters
[in] mesh
References DeselectAllEdges().
void ug4Bridge::promesh::Selection::Edges::EdgeSelectionFill (Mesh * mesh)
Selects neighbours of selected edges over non-selected vertices.
Parameters
[in] mesh
References EdgeSelectionFill().
void ug4Bridge::promesh::Selection::Edges::SelectAllEdges (Mesh * mesh)
Selects all edges of the current grid.
Parameters
[in] mesh
References SelectAllEdges().
void ug4Bridge::promesh::Selection::Edges::SelectAssociatedEdges (Mesh * mesh)
Selects edges that belong to selected faces and volumes.
Parameters
[in] mesh
References SelectAssociatedEdges().
void ug4Bridge::promesh::Selection::Edges::SelectBoundaryEdges (Mesh * mesh)
Selects edges that lie on the boundary of the geometry.
Parameters
[in] mesh
References SelectBoundaryEdges().
void ug4Bridge::promesh::Selection::Edges::SelectCreaseEdges (Mesh * mesh, double min_angle)
Selects edges that at which triangles meet in a given angle.
Parameters
[in] mesh
[in] min_angle
References SelectCreaseEdges().
Edge* ug4Bridge::promesh::Selection::Edges::SelectEdgeByCoordinate (Mesh * mesh, const Vec3d * coordinate)
Selects the edge whose center is closest to the specified coordinate.
Parameters
[in] mesh
[in] coordinate
References SelectEdgeByCoordinate().
Referenced by SelectEdgeByCoordinate().
Edge* ug4Bridge::promesh::Selection::Edges::SelectEdgeByCylindricalCoordinate (Mesh * mesh, double rho, double phi, double z)
Selects the edge whose center is closest to the specified cylindrical coordinate.
Parameters
[in] mesh
[in] rho
[in] phi
[in] z
References SelectEdgeByCylindricalCoordinate().
Referenced by SelectEdgeByCylindricalCoordinate().
bool ug4Bridge::promesh::Selection::Edges::SelectEdgeByIndex (Mesh * mesh, int index)
Selects a edge given its index.
Parameters
[in] mesh
[in] index
References SelectEdgeByIndex().
void ug4Bridge::promesh::Selection::Edges::SelectEdgesInBox (Mesh * mesh, const Vec3d * min, const Vec3d * max)
Selects all edges in the given box.
Parameters
[in] mesh
[in] min
[in] max
References SelectEdgesInBox().
Referenced by SelectEdgesInBox().
void ug4Bridge::promesh::Selection::Edges::SelectEdgesInCylinder (Mesh * mesh, const Vec3d * base, const Vec3d * top, double radius)
Selects all edges in the given cylinder.
Parameters
[in] mesh
[in] base
[in] top
[in] radius
References SelectEdgesInCylinder().
Referenced by SelectEdgesInCylinder().
void ug4Bridge::promesh::Selection::Edges::SelectInnerEdges (Mesh * mesh)
Selects edges that do not lie on the boundary of the geometry.
Parameters
[in] mesh
References SelectInnerEdges().
void ug4Bridge::promesh::Selection::Edges::SelectInterfaceEdges (Mesh * mesh, bool regard_selected_neighbors_only)
Selects elements which are adjacent to higher dimensional elements of different subsets.
Parameters
[in] mesh
[in] regard_selected_neighbors_only
References SelectInterfaceEdges().
Referenced by SelectInterfaceEdges().
void ug4Bridge::promesh::Selection::Edges::SelectLinkedBoundaryEdges (Mesh * mesh, bool stop_at_selected_vertices)
Selects linked boundary edges of selected edges.
Parameters
[in] mesh
[in] stop_at_selected_vertices
References SelectLinkedBoundaryEdges().
void ug4Bridge::promesh::Selection::Edges::SelectLinkedEdges (Mesh * mesh)
Repeatedly selects all edges which are vertex-neighbors of selected edges.
Parameters
[in] mesh
References SelectLinkedEdges().
Referenced by SelectLinkedEdges().
void ug4Bridge::promesh::Selection::Edges::SelectLongEdges (Mesh * mesh, double min_length)
Selects edges that are longer than a given threshold.
Parameters
[in] mesh
[in] min_length
References SelectLongEdges().
void ug4Bridge::promesh::Selection::Edges::SelectMarkedEdges (Mesh * mesh)
Selects edges which are marked.
Parameters
[in] mesh
References SelectMarkedEdges().
void ug4Bridge::promesh::Selection::Edges::SelectNonManifoldEdges (Mesh * mesh)
Selects edges with more than 2 associated faces.
Parameters
[in] mesh
References SelectNonManifoldEdges().
void ug4Bridge::promesh::Selection::Edges::SelectShortEdges (Mesh * mesh, double max_length)
Selects edges that are shorter than a given threshold.
Parameters
[in] mesh
[in] max_length
References SelectShortEdges().
void ug4Bridge::promesh::Selection::Edges::SelectShortPolychains (Mesh * mesh, double maxChainLength, bool closedChainsOnly)
Selects polygonal chains which are shorter than the given threshold.
Parameters
[in] mesh
[in] maxChainLength
[in] closedChainsOnly
References SelectShortPolychains().
void ug4Bridge::promesh::Selection::Edges::SelectSmoothEdgePath (Mesh * mesh, double max_deviation_angle, double normal_weight, bool stop_at_selected_vertices)
Selects a smooth edge path.
Parameters
[in] mesh
[in] max_deviation_angle
[in] normal_weight
[in] stop_at_selected_vertices
References SelectSmoothEdgePath().