Registry: ug4Bridge::promesh::Remeshing::Refinement Namespace Reference
ug4Bridge::promesh::Remeshing::Refinement Namespace Reference
Functions
void HangingNodeRefine (Mesh *mesh, bool anisotropic)
Refines selected elements using hanging nodes.
void InsertCenter (Mesh *mesh)
Inserts a central vertex in all selected elements.
void PlaneCut (Mesh *mesh, const Vec *plane_center, const Vec *plane_normal)
Cuts selected edges along the given plane.
void Refine (Mesh *mesh)
Refines selected elements and builds a regular closure.
void RefineSmooth (Mesh *mesh)
Refines selected elements using piecewise smooth refinement.
void RefineWithSnapPoints (Mesh *mesh)
Refines selected elements so that new edges are built between midpoints of selected edges and selected vertices, if possible.
void RefineWithSnapPointsOrtho (Mesh *mesh)
Refines selected elements so that new edges are built between midpoints of selected edges and selected vertices, if possible. New vertices are placed so that their connecting edge to the snap point is orthogonal to their parent edge.
void RegularizingRefinement (Mesh *mesh, double aspect_ratio)
Marks and refines elements with small aspect ratios, trying to improves said aspect ratios.
Function Documentation
HangingNodeRefine()
void ug4Bridge::promesh::Remeshing::Refinement::HangingNodeRefine (Mesh * mesh, bool anisotropic)
Refines selected elements using hanging nodes.
Parameters
[in] mesh
[in] anisotropic
References HangingNodeRefine().
InsertCenter()
void ug4Bridge::promesh::Remeshing::Refinement::InsertCenter (Mesh * mesh)
Inserts a central vertex in all selected elements.
Parameters
[in] mesh
References InsertCenter().
PlaneCut()
void ug4Bridge::promesh::Remeshing::Refinement::PlaneCut (Mesh * mesh, const Vec * plane_center, const Vec * plane_normal)
Cuts selected edges along the given plane.
Parameters
[in] mesh
[in] plane_center
[in] plane_normal
References PlaneCut().
Refine()
void ug4Bridge::promesh::Remeshing::Refinement::Refine (Mesh * mesh)
Refines selected elements and builds a regular closure.
Parameters
[in] mesh
References Refine().
RefineSmooth()
void ug4Bridge::promesh::Remeshing::Refinement::RefineSmooth (Mesh * mesh)
Refines selected elements using piecewise smooth refinement.
Parameters
[in] mesh
References RefineSmooth().
RefineWithSnapPoints()
void ug4Bridge::promesh::Remeshing::Refinement::RefineWithSnapPoints (Mesh * mesh)
Refines selected elements so that new edges are built between midpoints of selected edges and selected vertices, if possible.
Parameters
[in] mesh
References RefineWithSnapPoints().
RefineWithSnapPointsOrtho()
void ug4Bridge::promesh::Remeshing::Refinement::RefineWithSnapPointsOrtho (Mesh * mesh)
Refines selected elements so that new edges are built between midpoints of selected edges and selected vertices, if possible. New vertices are placed so that their connecting edge to the snap point is orthogonal to their parent edge.
Parameters
[in] mesh
References RefineWithSnapPointsOrtho().
RegularizingRefinement()
void ug4Bridge::promesh::Remeshing::Refinement::RegularizingRefinement (Mesh * mesh, double aspect_ratio)
Marks and refines elements with small aspect ratios, trying to improves said aspect ratios.
Parameters
[in] mesh
[in] aspect_ratio
References RegularizingRefinement().