Registry: ug4Bridge::promesh::GridGeneration::BasicElements Namespace Reference
ug4Bridge::promesh::GridGeneration::BasicElements Namespace Reference
Functions
Edge * CreateEdge (Mesh *mesh, int subset_index)
Creates an edge between two selected vertices.
Face * CreateFace (Mesh *mesh, int subset_index)
Creates a face between selected vertices.
Vertex * CreateVertex (Mesh *mesh, const Vec3d *position, int subset_index)
Creates a new vertex.
Volume * CreateVolume (Mesh *mesh, int subset_index)
Creates a volume between selected vertices.
Function Documentation
Edge* ug4Bridge::promesh::GridGeneration::BasicElements::CreateEdge (Mesh * mesh, int subset_index)
Creates an edge between two selected vertices.
Parameters
[in] mesh
[in] subset_index
References CreateEdge().
Face* ug4Bridge::promesh::GridGeneration::BasicElements::CreateFace (Mesh * mesh, int subset_index)
Creates a face between selected vertices.
Parameters
[in] mesh
[in] subset_index
References CreateFace().
Vertex* ug4Bridge::promesh::GridGeneration::BasicElements::CreateVertex (Mesh * mesh, const Vec3d * position, int subset_index)
Creates a new vertex.
Parameters
[in] mesh
[in] position
[in] subset_index
References CreateVertex().
Volume* ug4Bridge::promesh::GridGeneration::BasicElements::CreateVolume (Mesh * mesh, int subset_index)
Creates a volume between selected vertices.
Parameters
[in] mesh
[in] subset_index
References CreateVolume().