Registry: ug4Bridge::Info Namespace Reference
ug4Bridge::Info Namespace Reference
Functions
void ClassHierarchy (const char *typeName)
print the class hierachy of type
bool ClassInstantiations (const char *typeName)
print all objects of the type
void ClassUsage (const char *typeName)
print information about the usage of a type
void EnableLUA2C (bool bEnable)
void EnableLUA2VM (bool bEnable)
bool HasClass (const char *className)
use only if you know that you're not using a class group, otherwise HasClassGroup
bool HasClassGroup (const char *classGroupName)
can be used before instantiating a class
void InitSignals ()
void list_cfunctions ()
list all cfunctions
void list_classes ()
list all classes
void list_internalFunctions ()
list all of LUAs internal functions
void list_luaObjects ()
list all created LUA objects
void list_objects ()
list all LUA class objects
void list_scriptFunctions ()
list all LUA script functions
void ls ()
list all objects
bool PluginLoaded (std::string pluginName)
pluginName as listed when using cmake ..
bool PluginRequired (const char *pluginName)
throws an error if plugin not loaded, displays help string how to enable plugins via cmake -DpluginName=ON ..
void Stacktrace (int unnamed)
prints the LUA function stack, that is which functions are called up to this point
int TypeInfo (const char *typeName)
print information about a type
Function Documentation
void ug4Bridge::Info::ClassHierarchy (const char * typeName)
print the class hierachy of type
Parameters
[in] typeName
References ClassHierarchy().
Referenced by ClassHierarchy().
bool ug4Bridge::Info::ClassInstantiations (const char * typeName)
print all objects of the type
Parameters
[in] typeName
References ClassInstantiations().
void ug4Bridge::Info::ClassUsage (const char * typeName)
print information about the usage of a type
Parameters
[in] typeName
References ClassUsage().
void ug4Bridge::Info::EnableLUA2C (bool bEnable)
Parameters
[in] bEnable
References EnableLUA2C().
void ug4Bridge::Info::EnableLUA2VM (bool bEnable)
Parameters
[in] bEnable
References EnableLUA2VM().
bool ug4Bridge::Info::HasClass (const char * className)
use only if you know that you're not using a class group, otherwise HasClassGroup
Parameters
[in] className
Returns
true if class exists
References HasClass().
Referenced by HasClass().
bool ug4Bridge::Info::HasClassGroup (const char * classGroupName)
can be used before instantiating a class
Parameters
[in] classGroupName
Returns
true if class oder classGroup exists
References HasClassGroup().
Referenced by HasClassGroup().
void ug4Bridge::Info::InitSignals ()
References InitSignals().
void ug4Bridge::Info::list_cfunctions ()
list all cfunctions
References list_cfunctions().
Referenced by list_cfunctions().
void ug4Bridge::Info::list_classes ()
list all classes
References list_classes().
Referenced by list_classes().
void ug4Bridge::Info::list_internalFunctions ()
list all of LUAs internal functions
References list_internalFunctions().
Referenced by list_internalFunctions().
void ug4Bridge::Info::list_luaObjects ()
list all created LUA objects
References list_luaObjects().
Referenced by list_luaObjects().
void ug4Bridge::Info::list_objects ()
list all LUA class objects
References list_objects().
Referenced by list_objects().
void ug4Bridge::Info::list_scriptFunctions ()
list all LUA script functions
References list_scriptFunctions().
Referenced by list_scriptFunctions().
void ug4Bridge::Info::ls ()
list all objects
References ls().
Referenced by ls().
bool ug4Bridge::Info::PluginLoaded (std::string pluginName)
pluginName as listed when using cmake ..
Parameters
[in] pluginName
Returns
true if plugin loaded
References PluginLoaded().
bool ug4Bridge::Info::PluginRequired (const char * pluginName)
throws an error if plugin not loaded, displays help string how to enable plugins via cmake -DpluginName=ON ..
Parameters
[in] pluginName
Returns
true if plugin loaded
References PluginRequired().
Referenced by PluginRequired().
void ug4Bridge::Info::Stacktrace (int unnamed)
prints the LUA function stack, that is which functions are called up to this point
Parameters
[in] unnamed
References Stacktrace().
Referenced by Stacktrace().
int ug4Bridge::Info::TypeInfo (const char * typeName)
print information about a type
Parameters
[in] typeName
References TypeInfo().
Referenced by TypeInfo().