Registry: ug4Bridge::promesh::Selection::Vertices::CoordinateBased Namespace Reference
ug4Bridge::promesh::Selection::Vertices::CoordinateBased Namespace Reference
Functions
Vertex * SelectVertexByCoordinate (Mesh *mesh, const Vec3d *coordinate)
Selects a vertex given a coordinate.
Vertex * SelectVertexByCylindricalCoordinate (Mesh *mesh, double rho, double phi, double z)
Selects a vertex given a cylindrical coordinate.
void SelectVerticesInBox (Mesh *mesh, const Vec3d *min, const Vec3d *max)
Selects all vertices in the given box.
void SelectVerticesInCylinder (Mesh *mesh, const Vec3d *base, const Vec3d *top, double radius)
Selects all vertices in the given cylinder.
Function Documentation
SelectVertexByCoordinate()
Vertex* ug4Bridge::promesh::Selection::Vertices::CoordinateBased::SelectVertexByCoordinate (Mesh * mesh, const Vec3d * coordinate)
Selects a vertex given a coordinate.
Parameters
[in] mesh
[in] coordinate
References SelectVertexByCoordinate().
Referenced by SelectVertexByCoordinate().
SelectVertexByCylindricalCoordinate()
Vertex* ug4Bridge::promesh::Selection::Vertices::CoordinateBased::SelectVertexByCylindricalCoordinate (Mesh * mesh, double rho, double phi, double z)
Selects a vertex given a cylindrical coordinate.
Parameters
[in] mesh
[in] rho
[in] phi
[in] z
References SelectVertexByCylindricalCoordinate().
Referenced by SelectVertexByCylindricalCoordinate().
SelectVerticesInBox()
void ug4Bridge::promesh::Selection::Vertices::CoordinateBased::SelectVerticesInBox (Mesh * mesh, const Vec3d * min, const Vec3d * max)
Selects all vertices in the given box.
Parameters
[in] mesh
[in] min
[in] max
References SelectVerticesInBox().
Referenced by SelectVerticesInBox().
SelectVerticesInCylinder()
void ug4Bridge::promesh::Selection::Vertices::CoordinateBased::SelectVerticesInCylinder (Mesh * mesh, const Vec3d * base, const Vec3d * top, double radius)
Selects all vertices in the given cylinder.
Parameters
[in] mesh
[in] base
[in] top
[in] radius
References SelectVerticesInCylinder().
Referenced by SelectVerticesInCylinder().