Registry: ug4Bridge::pcl Namespace Reference
ug4Bridge::pcl Namespace Reference
Functions
bool AllProcsTrue (bool boolean)
Returns true if all processes call the method with true.
void DisableMPIInit ()
Tells PCL to not call MPI_Init and MPI_Finalize.
int NumProcs ()
Returns the number of active processes.
double ParallelMax (double t)
returns the maximum of t over all processes. note: you have to assure that all processes call this function.
double ParallelMin (double t)
returns the minimum of t over all processes. note: you have to assure that all processes call this function.
double ParallelSum (double t)
returns the sum of t over all processes. note: you have to assure that all processes call this function.
std::vector< double > ParallelVecMax (std::vector< double > t)
returns the maximum of t over all processes. note: you have to assure that all processes call this function.
std::vector< double > ParallelVecMin (std::vector< double > t)
returns the minimum of t over all processes. note: you have to assure that all processes call this function.
std::vector< double > ParallelVecSum (std::vector< double > t)
returns the sum of t over all processes. note: you have to assure that all processes call this function.
void PclDebugBarrierAll ()
Synchronizes all parallel processes if the executablehas been compiled with PCL_DEBUG_BARRIER=ON.
bool PclDebugBarrierEnabled ()
Returns the whether debug barriers are enabled.
int ProcRank ()
Returns the rank of the current process.
void SynchronizeProcesses ()
Waits until all active processes reached this point.
Function Documentation
AllProcsTrue()
bool ug4Bridge::pcl::AllProcsTrue (bool boolean)
Returns true if all processes call the method with true.
Parameters
[in] boolean
Returns
boolean
References AllProcsTrue().
DisableMPIInit()
void ug4Bridge::pcl::DisableMPIInit ()
Tells PCL to not call MPI_Init and MPI_Finalize.
References DisableMPIInit().
NumProcs()
int ug4Bridge::pcl::NumProcs ()
Returns the number of active processes.
Returns
NumProcs
References NumProcs().
ParallelMax()
double ug4Bridge::pcl::ParallelMax (double t)
returns the maximum of t over all processes. note: you have to assure that all processes call this function.
Parameters
[in] t
Returns
tmin
References ParallelMax().
ParallelMin()
double ug4Bridge::pcl::ParallelMin (double t)
returns the minimum of t over all processes. note: you have to assure that all processes call this function.
Parameters
[in] t
Returns
tmax
References ParallelMin().
ParallelSum()
double ug4Bridge::pcl::ParallelSum (double t)
returns the sum of t over all processes. note: you have to assure that all processes call this function.
Parameters
[in] t
Returns
tsum
References ParallelSum().
ParallelVecMax()
std::vector< double > ug4Bridge::pcl::ParallelVecMax (std::vector< double > t)
returns the maximum of t over all processes. note: you have to assure that all processes call this function.
Parameters
[in] t
Returns
tmin
References ParallelVecMax().
ParallelVecMin()
std::vector< double > ug4Bridge::pcl::ParallelVecMin (std::vector< double > t)
returns the minimum of t over all processes. note: you have to assure that all processes call this function.
Parameters
[in] t
Returns
tmax
References ParallelVecMin().
ParallelVecSum()
std::vector< double > ug4Bridge::pcl::ParallelVecSum (std::vector< double > t)
returns the sum of t over all processes. note: you have to assure that all processes call this function.
Parameters
[in] t
Returns
tsum
References ParallelVecSum().
PclDebugBarrierAll()
void ug4Bridge::pcl::PclDebugBarrierAll ()
Synchronizes all parallel processes if the executablehas been compiled with PCL_DEBUG_BARRIER=ON.
References PclDebugBarrierAll().
PclDebugBarrierEnabled()
bool ug4Bridge::pcl::PclDebugBarrierEnabled ()
Returns the whether debug barriers are enabled.
Returns
Enabled
References PclDebugBarrierEnabled().
ProcRank()
int ug4Bridge::pcl::ProcRank ()
Returns the rank of the current process.
Returns
ProcRank
References ProcRank().
SynchronizeProcesses()
void ug4Bridge::pcl::SynchronizeProcesses ()
Waits until all active processes reached this point.
References SynchronizeProcesses().