Registry: ug4Bridge::Util::Internal Namespace Reference
ug4Bridge::Util::Internal Namespace Reference
Functions
void AbortRun ()
Sets an internal variable to true, to indicate that the run should be aborted on the next call to TerminateAbortedRun.
void ClearAbortRunFlag ()
Clear the abort-run-flag.
bool DefinedUG_DEBUG ()
bool DefinedUG_ENABLE_DEBUG_LOGS ()
std::string FilenameStringEscape (std::string str)
std::string GetBuildHostname ()
std::string GetCompileDate ()
std::string GetOperatingSystem ()
std::string GetSVNRevision ()
bool IsDefinedBLAS_AVAILABLE ()
bool IsDefinedLAPACK_AVAILABLE ()
bool IsDefinedUG_CPU_1 ()
bool IsDefinedUG_CPU_2 ()
bool IsDefinedUG_CPU_3 ()
bool IsDefinedUG_DEBUG ()
bool IsDefinedUG_DIM_1 ()
bool IsDefinedUG_DIM_2 ()
bool IsDefinedUG_DIM_3 ()
bool IsDefinedUG_ENABLE_DEBUG_LOGS ()
bool IsDefinedUG_HLIBPRO ()
bool IsDefinedUG_HYPRE ()
bool IsDefinedUG_PARALLEL ()
size_t LevenshteinDistance (std::string s1, std::string s2)
void PrintBuildConfiguration ()
void PrintBuildConfigurationExtended ()
std::string ReplaceAll (std::string target, std::string old, std::string new)
void TerminateAbortedRun ()
Terminates the current run if AbortRun() has been called before.
void ug_backtrace ()
prints lua/shiny/gcc backtrace information
bool WildcardMatch (const char *str, const char *pattern)
std::string XMLStringEscape (std::string str)
Function Documentation
void ug4Bridge::Util::Internal::AbortRun ()
Sets an internal variable to true, to indicate that the run should be aborted on the next call to TerminateAbortedRun.
References AbortRun().
void ug4Bridge::Util::Internal::ClearAbortRunFlag ()
Clear the abort-run-flag.
References ClearAbortRunFlag().
bool ug4Bridge::Util::Internal::DefinedUG_DEBUG ()
References DefinedUG_DEBUG().
Referenced by DefinedUG_DEBUG().
bool ug4Bridge::Util::Internal::DefinedUG_ENABLE_DEBUG_LOGS ()
References DefinedUG_ENABLE_DEBUG_LOGS().
Referenced by DefinedUG_ENABLE_DEBUG_LOGS().
std::string ug4Bridge::Util::Internal::FilenameStringEscape (std::string str)
Parameters
[in] str
Returns
string usable as filename
References FilenameStringEscape().
std::string ug4Bridge::Util::Internal::GetBuildHostname ()
References GetBuildHostname().
std::string ug4Bridge::Util::Internal::GetCompileDate ()
References GetCompileDate().
std::string ug4Bridge::Util::Internal::GetOperatingSystem ()
References GetOperatingSystem().
std::string ug4Bridge::Util::Internal::GetSVNRevision ()
References GetSVNRevision().
bool ug4Bridge::Util::Internal::IsDefinedBLAS_AVAILABLE ()
References IsDefinedBLAS_AVAILABLE().
bool ug4Bridge::Util::Internal::IsDefinedLAPACK_AVAILABLE ()
References IsDefinedLAPACK_AVAILABLE().
bool ug4Bridge::Util::Internal::IsDefinedUG_CPU_1 ()
References IsDefinedUG_CPU_1().
bool ug4Bridge::Util::Internal::IsDefinedUG_CPU_2 ()
References IsDefinedUG_CPU_2().
bool ug4Bridge::Util::Internal::IsDefinedUG_CPU_3 ()
References IsDefinedUG_CPU_3().
bool ug4Bridge::Util::Internal::IsDefinedUG_DEBUG ()
References IsDefinedUG_DEBUG().
bool ug4Bridge::Util::Internal::IsDefinedUG_DIM_1 ()
References IsDefinedUG_DIM_1().
bool ug4Bridge::Util::Internal::IsDefinedUG_DIM_2 ()
References IsDefinedUG_DIM_2().
bool ug4Bridge::Util::Internal::IsDefinedUG_DIM_3 ()
References IsDefinedUG_DIM_3().
bool ug4Bridge::Util::Internal::IsDefinedUG_ENABLE_DEBUG_LOGS ()
References IsDefinedUG_ENABLE_DEBUG_LOGS().
bool ug4Bridge::Util::Internal::IsDefinedUG_HLIBPRO ()
References IsDefinedUG_HLIBPRO().
bool ug4Bridge::Util::Internal::IsDefinedUG_HYPRE ()
References IsDefinedUG_HYPRE().
bool ug4Bridge::Util::Internal::IsDefinedUG_PARALLEL ()
References IsDefinedUG_PARALLEL().
size_t ug4Bridge::Util::Internal::LevenshteinDistance (std::string s1, std::string s2)
Parameters
[in] s1
[in] s2
Returns
Levenshtein distance of s1 and s2
References LevenshteinDistance().
void ug4Bridge::Util::Internal::PrintBuildConfiguration ()
References PrintBuildConfiguration().
void ug4Bridge::Util::Internal::PrintBuildConfigurationExtended ()
References PrintBuildConfigurationExtended().
std::string ug4Bridge::Util::Internal::ReplaceAll (std::string target, std::string old, std::string new)
Parameters
[in] target
[in] old
[in] new
Returns
replace string
References ReplaceAll().
void ug4Bridge::Util::Internal::TerminateAbortedRun ()
Terminates the current run if AbortRun() has been called before.
References TerminateAbortedRun().
void ug4Bridge::Util::Internal::ug_backtrace ()
prints lua/shiny/gcc backtrace information
References ug_backtrace().
bool ug4Bridge::Util::Internal::WildcardMatch (const char * str, const char * pattern)
Parameters
[in] str
[in] pattern
Returns
true if match
References WildcardMatch().
std::string ug4Bridge::Util::Internal::XMLStringEscape (std::string str)
Parameters
[in] str
Returns
string usable in XML files
References XMLStringEscape().