Registry: ug4Bridge::Discretization::ApproximationSpace Namespace Reference
ug4Bridge::Discretization::ApproximationSpace Namespace Reference
Classes
class ApproximationSpace
class CompositeSpace
class ExplicitGridFunctionGradient
class ExplicitGridFunctionValue
class GlobalEdgeGridFunctionNumberData
class GlobalGridFunctionGradientData
class GlobalGridFunctionNumberData
class GridFunction
class GridFunctionGradientComponentData
class GridFunctionGradientData
class GridFunctionNumberData
class GridFunctionVectorData
class H1ComponentSpace
class H1SemiComponentSpace
class IComponentSpace
class IGridFunctionSpace
class L2ComponentSpace
class L2QuotientSpace
class TimeDependentSpace
class VelEnergyComponentSpace
Functions
void AddFunctionValuesToGridCoordinatesP1 (SmartPtr< GridFunction > unnamed, const char *unnamed, size_t unnamed)
void AdjustMeanValue (SmartPtr< GridFunction > unnamed, std::vector< std::string > unnamed, double unnamed)
double AverageFunctionDifference (SmartPtr< GridFunction > unnamed, std::string unnamed, std::string unnamed, std::string unnamed)
bool CheckDoFPositions (const GridFunction *unnamed)
bool CheckGFValuesAtEdges (const GridFunction *unnamed, const char *unnamed)
bool CheckGFValuesAtFaces (const GridFunction *unnamed, const char *unnamed)
bool CheckGFValuesAtVertices (const GridFunction *unnamed, const char *unnamed)
bool CheckGFValuesAtVolumes (const GridFunction *unnamed, const char *unnamed)
void OrderCuthillMcKee (ApproximationSpace *unnamed, bool unnamed)
void OrderDownwind (ApproximationSpace *unnamed, SmartPtr< UserVector > unnamed)
void OrderLex (ApproximationSpace *unnamed, const char *unnamed)
double SumGFValuesAtVertices (GridFunction *unnamed, const char *unnamed, const char *unnamed)
Function Documentation
AddFunctionValuesToGridCoordinatesP1()
void ug4Bridge::Discretization::ApproximationSpace::AddFunctionValuesToGridCoordinatesP1 (SmartPtr< GridFunction > unnamed, const char * unnamed, size_t unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References AddFunctionValuesToGridCoordinatesP1().
AdjustMeanValue()
void ug4Bridge::Discretization::ApproximationSpace::AdjustMeanValue (SmartPtr< GridFunction > unnamed, std::vector< std::string > unnamed, double unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References AdjustMeanValue().
AverageFunctionDifference()
double ug4Bridge::Discretization::ApproximationSpace::AverageFunctionDifference (SmartPtr< GridFunction > unnamed, std::string unnamed, std::string unnamed, std::string unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References AverageFunctionDifference().
CheckDoFPositions()
bool ug4Bridge::Discretization::ApproximationSpace::CheckDoFPositions (const GridFunction * unnamed)
Parameters
[in] unnamed
References CheckDoFPositions().
CheckGFValuesAtEdges()
bool ug4Bridge::Discretization::ApproximationSpace::CheckGFValuesAtEdges (const GridFunction * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
References CheckGFValuesAtEdges().
Referenced by CheckGFValuesAtEdges().
CheckGFValuesAtFaces()
bool ug4Bridge::Discretization::ApproximationSpace::CheckGFValuesAtFaces (const GridFunction * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
References CheckGFValuesAtFaces().
Referenced by CheckGFValuesAtFaces().
CheckGFValuesAtVertices()
bool ug4Bridge::Discretization::ApproximationSpace::CheckGFValuesAtVertices (const GridFunction * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
References CheckGFValuesAtVertices().
Referenced by CheckGFValuesAtVertices().
CheckGFValuesAtVolumes()
bool ug4Bridge::Discretization::ApproximationSpace::CheckGFValuesAtVolumes (const GridFunction * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
References CheckGFValuesAtVolumes().
Referenced by CheckGFValuesAtVolumes().
OrderCuthillMcKee()
void ug4Bridge::Discretization::ApproximationSpace::OrderCuthillMcKee (ApproximationSpace * unnamed, bool unnamed)
Parameters
[in] unnamed
[in] unnamed
References OrderCuthillMcKee().
OrderDownwind()
void ug4Bridge::Discretization::ApproximationSpace::OrderDownwind (ApproximationSpace * unnamed, SmartPtr< UserVector > unnamed)
Parameters
[in] unnamed
[in] unnamed
References OrderDownwind().
OrderLex()
void ug4Bridge::Discretization::ApproximationSpace::OrderLex (ApproximationSpace * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
References OrderLex().
SumGFValuesAtVertices()
double ug4Bridge::Discretization::ApproximationSpace::SumGFValuesAtVertices (GridFunction * unnamed, const char * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References SumGFValuesAtVertices().
Referenced by SumGFValuesAtVertices().