Registry: ug4Bridge::promesh::Remeshing::Tetrahedra Namespace Reference
ug4Bridge::promesh::Remeshing::Tetrahedra Namespace Reference
Functions
void AssignVolumeConstraints (Mesh *mesh, double volume_constraint)
Assigns volume constraints to selected tetrahedra.
void ClearVolumeConstraints (Mesh *mesh)
Clears all assigned volume constraints.
void ConvertToTetrahedra (Mesh *mesh)
Converts selected volume elements to tetrahedra.
void ExtrudeFacesWithTets (Mesh *mesh, int from_subset, int to_subset, double factor)
Experimental function to create 'plaque'-like geometry based on extruding faces with tetrahedra.
void Retetrahedralize (Mesh *mesh, double quality, bool preserve_outer, bool preserve_all, bool apply_volume_constraint, int verbosity)
Given a tetrahedralization and volume constraints, this method adapts the tetrahedra using TetGen.
void Tetrahedralize (Mesh *mesh, double quality, bool preserve_outer, bool preserve_all, bool separate_volumes, bool append_subsets_at_end, int verbosity)
Fills a closed surface with tetrahedra using TetGen.
Function Documentation
AssignVolumeConstraints()
void ug4Bridge::promesh::Remeshing::Tetrahedra::AssignVolumeConstraints (Mesh * mesh, double volume_constraint)
Assigns volume constraints to selected tetrahedra.
Parameters
[in] mesh
[in] volume_constraint
References AssignVolumeConstraints().
ClearVolumeConstraints()
void ug4Bridge::promesh::Remeshing::Tetrahedra::ClearVolumeConstraints (Mesh * mesh)
Clears all assigned volume constraints.
Parameters
[in] mesh
References ClearVolumeConstraints().
ConvertToTetrahedra()
void ug4Bridge::promesh::Remeshing::Tetrahedra::ConvertToTetrahedra (Mesh * mesh)
Converts selected volume elements to tetrahedra.
Parameters
[in] mesh
References ConvertToTetrahedra().
ExtrudeFacesWithTets()
void ug4Bridge::promesh::Remeshing::Tetrahedra::ExtrudeFacesWithTets (Mesh * mesh, int from_subset, int to_subset, double factor)
Experimental function to create 'plaque'-like geometry based on extruding faces with tetrahedra.
Parameters
[in] mesh
[in] from_subset
[in] to_subset
[in] factor
References ExtrudeFacesWithTets().
Retetrahedralize()
void ug4Bridge::promesh::Remeshing::Tetrahedra::Retetrahedralize (Mesh * mesh, double quality, bool preserve_outer, bool preserve_all, bool apply_volume_constraint, int verbosity)
Given a tetrahedralization and volume constraints, this method adapts the tetrahedra using TetGen.
Parameters
[in] mesh
[in] quality
[in] preserve_outer
[in] preserve_all
[in] apply_volume_constraint
[in] verbosity
References Retetrahedralize().
Tetrahedralize()
void ug4Bridge::promesh::Remeshing::Tetrahedra::Tetrahedralize (Mesh * mesh, double quality, bool preserve_outer, bool preserve_all, bool separate_volumes, bool append_subsets_at_end, int verbosity)
Fills a closed surface with tetrahedra using TetGen.
Parameters
[in] mesh
[in] quality
[in] preserve_outer
[in] preserve_all
[in] separate_volumes
[in] append_subsets_at_end
[in] verbosity
References Tetrahedralize().