Registry: ug4Bridge::lua Namespace Reference
ug4Bridge::lua Namespace Reference
Functions
void breakpoint (const char *unnamed, int unnamed)
void DebugBacktrace (int unnamed)
void print_breakpoints ()
void ProfileLUA (bool unnamed)
bool ug_load_script (const char *unnamed)
ONLY IF ALL CORES INVOLVED! Loads and parses a script and returns whether it succeeded.
bool ug_load_script_single (const char *unnamed)
Loads and parses a script and returns whether it succeeded.
Function Documentation
breakpoint()
void ug4Bridge::lua::breakpoint (const char * unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
References breakpoint().
DebugBacktrace()
void ug4Bridge::lua::DebugBacktrace (int unnamed)
Parameters
[in] unnamed
References DebugBacktrace().
print_breakpoints()
void ug4Bridge::lua::print_breakpoints ()
References print_breakpoints().
Referenced by print_breakpoints().
ProfileLUA()
void ug4Bridge::lua::ProfileLUA (bool unnamed)
Parameters
[in] unnamed
References ProfileLUA().
ug_load_script()
bool ug4Bridge::lua::ug_load_script (const char * unnamed)
ONLY IF ALL CORES INVOLVED! Loads and parses a script and returns whether it succeeded.
Parameters
[in] unnamed
Returns
success
References ug_load_script().
Referenced by ug_load_script().
ug_load_script_single()
bool ug4Bridge::lua::ug_load_script_single (const char * unnamed)
Loads and parses a script and returns whether it succeeded.
Parameters
[in] unnamed
Returns
success
References ug_load_script_single().
Referenced by ug_load_script_single().