Registry: ug4Bridge::promesh::Remeshing Namespace Reference
ug4Bridge::promesh::Remeshing Namespace Reference
Namespaces
BooleanOperations
Edges
Extrusion
MergeVertices
Orientation
Quadrilaterals
Refinement
RemoveDoubles
ResolveIntersections
Tetrahedra
Triangles
Functions
void CreateShrinkGeometry (Mesh *mesh, double scale)
Creates new elements from existing ones, providing each with a unique set of corner vertices. Those corners are scaled towards the center using the given scale-parameter.
void Duplicate (Mesh *mesh, const Vec3d *offset, bool deselect_old, bool select_new)
Duplicates the selected geometry.
void EraseSelectedElements (Mesh *mesh, bool erase_unused_vertices, bool erase_unused_edges, bool erase_unused_faces)
Erases selected elements and associated unreferenced geometry.
Function Documentation
CreateShrinkGeometry()
void ug4Bridge::promesh::Remeshing::CreateShrinkGeometry (Mesh * mesh, double scale)
Creates new elements from existing ones, providing each with a unique set of corner vertices. Those corners are scaled towards the center using the given scale-parameter.
Parameters
[in] mesh
[in] scale
References CreateShrinkGeometry().
Duplicate()
void ug4Bridge::promesh::Remeshing::Duplicate (Mesh * mesh, const Vec3d * offset, bool deselect_old, bool select_new)
Duplicates the selected geometry.
Parameters
[in] mesh
[in] offset
[in] deselect_old
[in] select_new
References Duplicate().
EraseSelectedElements()
void ug4Bridge::promesh::Remeshing::EraseSelectedElements (Mesh * mesh, bool erase_unused_vertices, bool erase_unused_edges, bool erase_unused_faces)
Erases selected elements and associated unreferenced geometry.
Parameters
[in] mesh
[in] erase_unused_vertices
[in] erase_unused_edges
[in] erase_unused_faces
References EraseSelectedElements().