Registry: ug4Bridge::Algebra Namespace Reference
ug4Bridge::Algebra Namespace Reference
Namespaces
Obstacle
Operation
Preconditioner
Restart
Solver
Classes
class ConvCheck
Convergence Check.
class DebugWritingObject
class EnergyConvCheck
Energy Convergence Check.
class IConvergenceCheck
class IDebugWriter
class ILinearIterator
class ILinearOperator
class ILinearOperatorInverse
class IMatrixOperatorInverse
class IOperator
class IOperatorInverse
class IPositionProvider
class IPreconditionedLinearOperatorInverse
class IPreconditioner
class IVectorDebugWriter
class IVectorWriter
class Matrix
class MatrixDiagonal
class MatrixDiagonalInverse
class MatrixOperator
class VecScaleAddClass
class Vector
class VectorDebugWritingObject
Functions
bool ApplyLinearSolver (SmartPtr< ILinearOperator > unnamed, Vector *unnamed, Vector *unnamed, SmartPtr< ILinearOperatorInverse > unnamed)
void Assign (SmartPtr< Vector > unnamed, SmartPtr< VecScaleAddClass > unnamed)
SmartPtr< Vector > Eval (SmartPtr< VecScaleAddClass > unnamed)
void VecAssign (Vector *dest, const Vector *vec)
dest <- vec
void VecHadamardProd (Vector *dst, const Vector *vec1, const Vector *vec2)
vec1 * vec2 (elementwise)
void VecScaleAdd2 (Vector *dest, double alpha1, const Vector *vec1, double alpha2, const Vector *vec2)
void VecScaleAdd3 (Vector *dest, double alpha1, const Vector *vec1, double alpha2, const Vector *vec2, double alpha3, const Vector *vec3)
void VecScaleAssign (Vector *dest, double alpha, const Vector *vec)
dest <- alpha * vec
Function Documentation
ApplyLinearSolver()
bool ug4Bridge::Algebra::ApplyLinearSolver (SmartPtr< ILinearOperator > unnamed, Vector * unnamed, Vector * unnamed, SmartPtr< ILinearOperatorInverse > unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References Algebra(), and ApplyLinearSolver().
Assign()
void ug4Bridge::Algebra::Assign (SmartPtr< Vector > unnamed, SmartPtr< VecScaleAddClass > unnamed)
Parameters
[in] unnamed
[in] unnamed
References Algebra(), and Assign().
Eval()
SmartPtr<Vector> ug4Bridge::Algebra::Eval (SmartPtr< VecScaleAddClass > unnamed)
Parameters
[in] unnamed
References Algebra(), and Eval().
VecAssign()
void ug4Bridge::Algebra::VecAssign (Vector * dest, const Vector * vec)
dest <- vec
Parameters
[in] dest
[in] vec
References Algebra(), and VecAssign().
VecHadamardProd()
void ug4Bridge::Algebra::VecHadamardProd (Vector * dst, const Vector * vec1, const Vector * vec2)
vec1 * vec2 (elementwise)
Parameters
[in] dst
[in] vec1
[in] vec2
References Algebra(), and VecHadamardProd().
VecScaleAdd2()
void ug4Bridge::Algebra::VecScaleAdd2 (Vector * dest, double alpha1, const Vector * vec1, double alpha2, const Vector * vec2)
Parameters
[in] dest
[in] alpha1
[in] vec1
[in] alpha2
[in] vec2
References Algebra(), and VecScaleAdd2().
VecScaleAdd3()
void ug4Bridge::Algebra::VecScaleAdd3 (Vector * dest, double alpha1, const Vector * vec1, double alpha2, const Vector * vec2, double alpha3, const Vector * vec3)
Parameters
[in] dest
[in] alpha1
[in] vec1
[in] alpha2
[in] vec2
[in] alpha3
[in] vec3
References VecScaleAdd3().
VecScaleAssign()
void ug4Bridge::Algebra::VecScaleAssign (Vector * dest, double alpha, const Vector * vec)
dest <- alpha * vec
Parameters
[in] dest
[in] alpha
[in] vec
References Algebra(), and VecScaleAssign().