Registry: ug4Bridge::promesh::Remeshing::Orientation Namespace Reference
ug4Bridge::promesh::Remeshing::Orientation Namespace Reference
Functions
void AdjustEdgeOrientation (Mesh *mesh)
Adjusts the orientation of boundary edges to associated faces.
void FixFaceOrientation (Mesh *mesh)
Tries to change orientation of selected faces so that all neighbouring faces point into the same direction. Only works correctly for manifold selections.
void FixFaceSubsetOrientations (Mesh *mesh)
Iterates over all subset and tries to fix face orientation for each. Only works correctly for manifold subsets.
int FixVolumeOrientation (Mesh *mesh)
Changes orientation of selected volumes, so that they are oriented correctly.
void InvertFaceOrientation (Mesh *mesh)
Inverts the orientation of all selected faces.
Function Documentation
void ug4Bridge::promesh::Remeshing::Orientation::AdjustEdgeOrientation (Mesh * mesh)
Adjusts the orientation of boundary edges to associated faces.
Parameters
[in] mesh
References AdjustEdgeOrientation().
void ug4Bridge::promesh::Remeshing::Orientation::FixFaceOrientation (Mesh * mesh)
Tries to change orientation of selected faces so that all neighbouring faces point into the same direction. Only works correctly for manifold selections.
Parameters
[in] mesh
References FixFaceOrientation().
void ug4Bridge::promesh::Remeshing::Orientation::FixFaceSubsetOrientations (Mesh * mesh)
Iterates over all subset and tries to fix face orientation for each. Only works correctly for manifold subsets.
Parameters
[in] mesh
References FixFaceSubsetOrientations().
int ug4Bridge::promesh::Remeshing::Orientation::FixVolumeOrientation (Mesh * mesh)
Changes orientation of selected volumes, so that they are oriented correctly.
Parameters
[in] mesh
References FixVolumeOrientation().
void ug4Bridge::promesh::Remeshing::Orientation::InvertFaceOrientation (Mesh * mesh)
Inverts the orientation of all selected faces.
Parameters
[in] mesh
References InvertFaceOrientation().