Registry: ug4Bridge::Transform Namespace Reference
ug4Bridge::Transform Namespace Reference
Functions
void ScaleDomainSqrtWeighting (Domain *dom, ISelector *sel, const Vec *center, const Vec *scale)
void ScaleDomainSquaredWeighting (Domain *dom, ISelector *sel, const Vec *center, const Vec *scale)
void ScaleDomainWeighting (Domain *dom, ISelector *sel, const Vec *center, const Vec *scale)
Function Documentation
ScaleDomainSqrtWeighting()
void ug4Bridge::Transform::ScaleDomainSqrtWeighting (Domain * dom, ISelector * sel, const Vec * center, const Vec * scale)
Parameters
[in] dom
[in] sel
[in] center
[in] scale
References Domain().
ScaleDomainSquaredWeighting()
void ug4Bridge::Transform::ScaleDomainSquaredWeighting (Domain * dom, ISelector * sel, const Vec * center, const Vec * scale)
Parameters
[in] dom
[in] sel
[in] center
[in] scale
References Domain().
ScaleDomainWeighting()
void ug4Bridge::Transform::ScaleDomainWeighting (Domain * dom, ISelector * sel, const Vec * center, const Vec * scale)
Parameters
[in] dom
[in] sel
[in] center
[in] scale
References Domain().