Registry: ug4Bridge::promesh::Remeshing::Edges Namespace Reference
ug4Bridge::promesh::Remeshing::Edges Namespace Reference
Functions
void CollapseEdge (Mesh *mesh)
Collapses the edge and removes adjacent triangles.
void SimplifyPolylines (Mesh *mesh, double max_curvature_angle)
Removes vertices from the selected polyline which have a smaller curvature than the specified angle.
void SimplifySmoothedPolylines (Mesh *mesh, double max_curvature_angle, double smoothing_alpha, int smoothing_iterations)
Removes vertices from the selected polyline which have a smaller smoothed curvature than the specified angle.
void SplitEdge (Mesh *mesh)
Splits the edge and inserts new triangles.
void SwapEdge (Mesh *mesh)
Swaps selected edges that are adjacent to exactly two triangles.
Function Documentation
CollapseEdge()
void ug4Bridge::promesh::Remeshing::Edges::CollapseEdge (Mesh * mesh)
Collapses the edge and removes adjacent triangles.
Parameters
[in] mesh
References CollapseEdge().
SimplifyPolylines()
void ug4Bridge::promesh::Remeshing::Edges::SimplifyPolylines (Mesh * mesh, double max_curvature_angle)
Removes vertices from the selected polyline which have a smaller curvature than the specified angle.
Parameters
[in] mesh
[in] max_curvature_angle
References SimplifyPolylines().
SimplifySmoothedPolylines()
void ug4Bridge::promesh::Remeshing::Edges::SimplifySmoothedPolylines (Mesh * mesh, double max_curvature_angle, double smoothing_alpha, int smoothing_iterations)
Removes vertices from the selected polyline which have a smaller smoothed curvature than the specified angle.
Parameters
[in] mesh
[in] max_curvature_angle
[in] smoothing_alpha
[in] smoothing_iterations
References SimplifySmoothedPolylines().
SplitEdge()
void ug4Bridge::promesh::Remeshing::Edges::SplitEdge (Mesh * mesh)
Splits the edge and inserts new triangles.
Parameters
[in] mesh
References SplitEdge().
SwapEdge()
void ug4Bridge::promesh::Remeshing::Edges::SwapEdge (Mesh * mesh)
Swaps selected edges that are adjacent to exactly two triangles.
Parameters
[in] mesh
References SwapEdge().