Registry: ug4Bridge::Algebra::Restart Namespace Reference
ug4Bridge::Algebra::Restart Namespace Reference
Functions
void ReadFromFile (Vector *unnamed, std::string unnamed)
void SaveToFile (const Vector *unnamed, std::string unnamed)
Function Documentation
ReadFromFile()
void ug4Bridge::Algebra::Restart::ReadFromFile (Vector * unnamed, std::string unnamed)
Parameters
[in] unnamed
[in] unnamed
References ReadFromFile().
SaveToFile()
void ug4Bridge::Algebra::Restart::SaveToFile (const Vector * unnamed, std::string unnamed)
Parameters
[in] unnamed
[in] unnamed
References Algebra(), and SaveToFile().