Registry: ug4Bridge::Refinement Namespace Reference
ug4Bridge::Refinement Namespace Reference
Functions
SmartPtr< IRefiner > AdaptiveRegularDomainRefiner (Domain *dom)
SmartPtr< IRefMarkAdjuster > AddHorizontalAnisotropyAdjuster (IRefiner *refiner, Domain *dom)
void ApplyConstrainedSmoothSubdivisionVolumesToTopLevel (MultiGrid *unnamed, MGSubsetHandler *unnamed, MGSubsetHandler *unnamed, const char *unnamed)
void ApplySmoothSubdivisionSurfacesToTopLevel2d (MultiGrid *unnamed, MGSubsetHandler *unnamed, MGSubsetHandler *unnamed, const char *unnamed)
void ApplySmoothSubdivisionSurfacesToTopLevel3d (MultiGrid *unnamed, MGSubsetHandler *unnamed, MGSubsetHandler *unnamed, const char *unnamed)
void ApplySmoothSubdivisionVolumesToTopLevel (MultiGrid *unnamed, MGSubsetHandler *unnamed, MGSubsetHandler *unnamed, const char *unnamed)
void CheckValences (MultiGrid *unnamed, MGSubsetHandler *unnamed, const char *unnamed)
SmartPtr< IRefiner > GlobalDomainRefiner (Domain *dom)
SmartPtr< GlobalFracturedMediumRefiner > GlobalFracturedDomainRefiner (Domain *dom)
SmartPtr< IRefiner > HangingNodeDomainRefiner (Domain *dom)
void MarkAnisotropic_LongEdges (Domain *dom, IRefiner *refiner, double maxEdgeLen)
void MarkForAdaption_AbsoluteGradientIndicator (IRefiner *unnamed, GridFunction *unnamed, const char *unnamed, double unnamed, double unnamed, int unnamed, int unnamed)
void MarkForAdaption_AbsoluteGradientJumpIndicator (IRefiner *unnamed, GridFunction *unnamed, const char *unnamed, double unnamed, double unnamed, int unnamed, int unnamed)
void MarkForAdaption_ElementsTouchingSubset (Domain *dom, IRefiner *refiner, ISubsetHandler *subsetHandler, int subsetIndex, std::string strMark)
void MarkForAdaption_ElementsTouchingSubsets (Domain *dom, IRefiner *refiner, const char *subsetHandler, std::string subsetNames)
void MarkForAdaption_GradientAverage (IRefiner *unnamed, SmartPtr< GridFunction > unnamed, const char *unnamed, double unnamed, int unnamed, int unnamed)
void MarkForAdaption_GradientIndicator (IRefiner *unnamed, GridFunction *unnamed, const char *unnamed, double unnamed, double unnamed, double unnamed, int unnamed)
void MarkForAdaption_GradientJump (IRefiner *unnamed, SmartPtr< GridFunction > unnamed, const char *unnamed, double unnamed, int unnamed, int unnamed, std::string unnamed)
void MarkForAdaption_GradientJumpIndicator (IRefiner *unnamed, GridFunction *unnamed, const char *unnamed, double unnamed, double unnamed, double unnamed, int unnamed)
void MarkForAdaption_L2ErrorExact (IRefiner *unnamed, SmartPtr< GridFunction > unnamed, SmartPtr< UserNumber > unnamed, const char *unnamed, double unnamed, double unnamed, double unnamed, int unnamed, int unnamed, double unnamed, int unnamed)
double MarkForAdaption_ResidualErrorP1Absolute (IRefiner *unnamed, SmartPtr< GridFunction > unnamed, SmartPtr< UserNumber > unnamed, const char *unnamed, double unnamed, double unnamed, double unnamed, int unnamed, int unnamed, std::string unnamed, bool unnamed)
void MarkForAdaption_ResidualErrorP1Relative (IRefiner *unnamed, SmartPtr< GridFunction > unnamed, SmartPtr< UserNumber > unnamed, const char *unnamed, double unnamed, double unnamed, int unnamed, int unnamed, int unnamed, std::string unnamed)
void MarkForAdaption_VerticesInCube (Domain *dom, SmartPtr< IRefiner > refiner, const Vec *min, const Vec *max, std::string adaption_type)
void MarkForAdaption_VerticesInSphere (Domain *dom, SmartPtr< IRefiner > refiner, const Vec *center, double radius, std::string adaption_type)
void MarkForCoarsen_ElementsByLuaCallback (Domain *dom, SmartPtr< IRefiner > refiner, double time, const char *callbackName)
void MarkForCoarsenening_SurfaceLayer (const GridFunction *unnamed, IRefiner *unnamed)
void MarkForRefinement_All (SmartPtr< IRefiner > ref)
void MarkForRefinement_AllVolumesAnisotropic (SmartPtr< IRefiner > ref)
void MarkForRefinement_AnisotropicDirection (Domain *dom, IRefiner *refiner, Vec *dir, double minEdgeRatio)
void MarkForRefinement_AnisotropicElements (Domain *dom, IRefiner *refiner, double minEdgeRatio)
void MarkForRefinement_CloseToSurface (Domain *unnamed, SmartPtr< IRefiner > unnamed, double unnamed, size_t unnamed, const Domain *unnamed)
void MarkForRefinement_ContainsSurfaceNode (Domain *unnamed, SmartPtr< IRefiner > unnamed, double unnamed, size_t unnamed, const Domain *unnamed)
void MarkForRefinement_EdgeDirection (Domain *dom, IRefiner *refiner, Vec *dir, double minDeviationAngle, double maxDeviationAngle, bool selectFlipped)
void MarkForRefinement_EdgesInSphere (Domain *dom, SmartPtr< IRefiner > refiner, const Vec *center, double radius)
void MarkForRefinement_EdgesInSubset (Domain *dom, IRefiner *refiner, MGSubsetHandler *subsetHandler, int subsetIndex)
void MarkForRefinement_ElementsByLuaCallback (Domain *dom, SmartPtr< IRefiner > refiner, double time, size_t callbackName, const char *unnamed)
void MarkForRefinement_ElementsInSubset (Domain *dom, IRefiner *refiner, MGSubsetHandler *subsetHandler, int subsetIndex)
void MarkForRefinement_FacesInSphere (Domain *dom, SmartPtr< IRefiner > refiner, const Vec *center, double radius)
void MarkForRefinement_FacesInSubset (Domain *dom, IRefiner *refiner, MGSubsetHandler *subsetHandler, int subsetIndex)
void MarkForRefinement_SubsetInterfaceEdges (Domain *unnamed, IRefiner *unnamed)
void MarkForRefinement_SubsetInterfaceFaces (Domain *unnamed, IRefiner *unnamed)
void MarkForRefinement_SubsetInterfaceVertices (Domain *unnamed, IRefiner *unnamed)
void MarkForRefinement_VerticesInCube (Domain *dom, SmartPtr< IRefiner > refiner, const Vec *min, const Vec *max)
void MarkForRefinement_VerticesInSphere (Domain *dom, SmartPtr< IRefiner > refiner, const Vec *center, double radius)
void MarkForRefinement_VerticesInSubset (Domain *dom, IRefiner *refiner, MGSubsetHandler *subsetHandler, int subsetIndex)
void MarkForRefinement_VolumesInSphere (Domain *dom, SmartPtr< IRefiner > refiner, const Vec *center, double radius)
void MarkForRefinement_VolumesInSubset (Domain *dom, IRefiner *refiner, MGSubsetHandler *subsetHandler, int subsetIndex)
void MarkNeighborsForAnisotropicRefinement (IRefiner *refiner, bool sideNeighborsOnly)
void MarkNeighborsForFullRefinement (IRefiner *refiner, bool sideNeighborsOnly)
void ProjectHierarchyToLimitSubdivisionSurface (MultiGrid *unnamed)
void ProjectHierarchyToLimitSubdivisionVolume (MultiGrid *unnamed)
void SetSmoothSubdivisionVolumesBoundaryRefinementRule (std::string bndRefRule)
Sets the boundary refinement rule used during Subdivision Volumes smoothing. Possible parameters: 'linear', 'subdiv_surf_loop_scheme', 'subdiv_surf_averaging_scheme' or 'subdiv_vol'.
void SetTetRefinementRule (std::string refRuleName)
Sets the refinement rule which is used to refine tetrahedrons. Possible parameters: 'standard', 'hybrid_tet_oct.
void TetrahedralizeHybridTetOctGrid (MultiGrid *unnamed, int unnamed)
Function Documentation
AdaptiveRegularDomainRefiner()
SmartPtr<IRefiner> ug4Bridge::Refinement::AdaptiveRegularDomainRefiner (Domain * dom)
Parameters
[in] dom
Returns
AdaptiveRegularDomainRefiner
References AdaptiveRegularDomainRefiner(), and Domain().
Referenced by AdaptiveRegularDomainRefiner().
AddHorizontalAnisotropyAdjuster()
SmartPtr<IRefMarkAdjuster> ug4Bridge::Refinement::AddHorizontalAnisotropyAdjuster (IRefiner * refiner, Domain * dom)
Parameters
[in] refiner
[in] dom
References AddHorizontalAnisotropyAdjuster(), and Domain().
ApplyConstrainedSmoothSubdivisionVolumesToTopLevel()
void ug4Bridge::Refinement::ApplyConstrainedSmoothSubdivisionVolumesToTopLevel (MultiGrid * unnamed, MGSubsetHandler * unnamed, MGSubsetHandler * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References ApplyConstrainedSmoothSubdivisionVolumesToTopLevel().
ApplySmoothSubdivisionSurfacesToTopLevel2d()
void ug4Bridge::Refinement::ApplySmoothSubdivisionSurfacesToTopLevel2d (MultiGrid * unnamed, MGSubsetHandler * unnamed, MGSubsetHandler * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References ApplySmoothSubdivisionSurfacesToTopLevel2d().
ApplySmoothSubdivisionSurfacesToTopLevel3d()
void ug4Bridge::Refinement::ApplySmoothSubdivisionSurfacesToTopLevel3d (MultiGrid * unnamed, MGSubsetHandler * unnamed, MGSubsetHandler * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References ApplySmoothSubdivisionSurfacesToTopLevel3d().
ApplySmoothSubdivisionVolumesToTopLevel()
void ug4Bridge::Refinement::ApplySmoothSubdivisionVolumesToTopLevel (MultiGrid * unnamed, MGSubsetHandler * unnamed, MGSubsetHandler * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References ApplySmoothSubdivisionVolumesToTopLevel().
CheckValences()
void ug4Bridge::Refinement::CheckValences (MultiGrid * unnamed, MGSubsetHandler * unnamed, const char * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
References CheckValences().
GlobalDomainRefiner()
SmartPtr<IRefiner> ug4Bridge::Refinement::GlobalDomainRefiner (Domain * dom)
Parameters
[in] dom
Returns
GlobalDomainRefiner
References Domain(), and GlobalDomainRefiner().
GlobalFracturedDomainRefiner()
SmartPtr<GlobalFracturedMediumRefiner> ug4Bridge::Refinement::GlobalFracturedDomainRefiner (Domain * dom)
Parameters
[in] dom
Returns
GlobalFracturedDomainRefiner
References Domain(), and GlobalFracturedDomainRefiner().
Referenced by GlobalFracturedDomainRefiner().
HangingNodeDomainRefiner()
SmartPtr<IRefiner> ug4Bridge::Refinement::HangingNodeDomainRefiner (Domain * dom)
Parameters
[in] dom
Returns
HangingNodeDomainRefiner
References Domain(), and HangingNodeDomainRefiner().
MarkAnisotropic_LongEdges()
void ug4Bridge::Refinement::MarkAnisotropic_LongEdges (Domain * dom, IRefiner * refiner, double maxEdgeLen)
Parameters
[in] dom
[in] refiner
[in] maxEdgeLen
References Domain(), and MarkAnisotropic_LongEdges().
MarkForAdaption_AbsoluteGradientIndicator()
void ug4Bridge::Refinement::MarkForAdaption_AbsoluteGradientIndicator (IRefiner * unnamed, GridFunction * unnamed, const char * unnamed, double unnamed, double unnamed, int unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References MarkForAdaption_AbsoluteGradientIndicator().
MarkForAdaption_AbsoluteGradientJumpIndicator()
void ug4Bridge::Refinement::MarkForAdaption_AbsoluteGradientJumpIndicator (IRefiner * unnamed, GridFunction * unnamed, const char * unnamed, double unnamed, double unnamed, int unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References MarkForAdaption_AbsoluteGradientJumpIndicator().
MarkForAdaption_ElementsTouchingSubset()
void ug4Bridge::Refinement::MarkForAdaption_ElementsTouchingSubset (Domain * dom, IRefiner * refiner, ISubsetHandler * subsetHandler, int subsetIndex, std::string strMark)
Parameters
[in] dom
[in] refiner
[in] subsetHandler
[in] subsetIndex
[in] strMark
References Domain(), and MarkForAdaption_ElementsTouchingSubset().
MarkForAdaption_ElementsTouchingSubsets()
void ug4Bridge::Refinement::MarkForAdaption_ElementsTouchingSubsets (Domain * dom, IRefiner * refiner, const char * subsetHandler, std::string subsetNames)
Parameters
[in] dom
[in] refiner
[in] subsetHandler
[in] subsetNames
References Domain(), and MarkForAdaption_ElementsTouchingSubsets().
MarkForAdaption_GradientAverage()
void ug4Bridge::Refinement::MarkForAdaption_GradientAverage (IRefiner * unnamed, SmartPtr< GridFunction > unnamed, const char * unnamed, double unnamed, int unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References MarkForAdaption_GradientAverage().
MarkForAdaption_GradientIndicator()
void ug4Bridge::Refinement::MarkForAdaption_GradientIndicator (IRefiner * unnamed, GridFunction * unnamed, const char * unnamed, double unnamed, double unnamed, double unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References MarkForAdaption_GradientIndicator().
MarkForAdaption_GradientJump()
void ug4Bridge::Refinement::MarkForAdaption_GradientJump (IRefiner * unnamed, SmartPtr< GridFunction > unnamed, const char * unnamed, double unnamed, int unnamed, int unnamed, std::string unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References MarkForAdaption_GradientJump().
MarkForAdaption_GradientJumpIndicator()
void ug4Bridge::Refinement::MarkForAdaption_GradientJumpIndicator (IRefiner * unnamed, GridFunction * unnamed, const char * unnamed, double unnamed, double unnamed, double unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References MarkForAdaption_GradientJumpIndicator().
MarkForAdaption_L2ErrorExact()
void ug4Bridge::Refinement::MarkForAdaption_L2ErrorExact (IRefiner * unnamed, SmartPtr< GridFunction > unnamed, SmartPtr< UserNumber > unnamed, const char * unnamed, double unnamed, double unnamed, double unnamed, int unnamed, int unnamed, double unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References MarkForAdaption_L2ErrorExact().
MarkForAdaption_ResidualErrorP1Absolute()
double ug4Bridge::Refinement::MarkForAdaption_ResidualErrorP1Absolute (IRefiner * unnamed, SmartPtr< GridFunction > unnamed, SmartPtr< UserNumber > unnamed, const char * unnamed, double unnamed, double unnamed, double unnamed, int unnamed, int unnamed, std::string unnamed, bool unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References MarkForAdaption_ResidualErrorP1Absolute().
MarkForAdaption_ResidualErrorP1Relative()
void ug4Bridge::Refinement::MarkForAdaption_ResidualErrorP1Relative (IRefiner * unnamed, SmartPtr< GridFunction > unnamed, SmartPtr< UserNumber > unnamed, const char * unnamed, double unnamed, double unnamed, int unnamed, int unnamed, int unnamed, std::string unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References MarkForAdaption_ResidualErrorP1Relative().
MarkForAdaption_VerticesInCube()
void ug4Bridge::Refinement::MarkForAdaption_VerticesInCube (Domain * dom, SmartPtr< IRefiner > refiner, const Vec * min, const Vec * max, std::string adaption_type)
Parameters
[in] dom
[in] refiner
[in] min
[in] max
[in] adaption_type
References Domain(), and MarkForAdaption_VerticesInCube().
MarkForAdaption_VerticesInSphere()
void ug4Bridge::Refinement::MarkForAdaption_VerticesInSphere (Domain * dom, SmartPtr< IRefiner > refiner, const Vec * center, double radius, std::string adaption_type)
Parameters
[in] dom
[in] refiner
[in] center
[in] radius
[in] adaption_type
References Domain(), and MarkForAdaption_VerticesInSphere().
MarkForCoarsen_ElementsByLuaCallback()
void ug4Bridge::Refinement::MarkForCoarsen_ElementsByLuaCallback (Domain * dom, SmartPtr< IRefiner > refiner, double time, const char * callbackName)
Parameters
[in] dom
[in] refiner
[in] time
[in] callbackName
References Domain(), and MarkForCoarsen_ElementsByLuaCallback().
MarkForCoarsenening_SurfaceLayer()
void ug4Bridge::Refinement::MarkForCoarsenening_SurfaceLayer (const GridFunction * unnamed, IRefiner * unnamed)
Parameters
[in] unnamed
[in] unnamed
References MarkForCoarsenening_SurfaceLayer().
MarkForRefinement_All()
void ug4Bridge::Refinement::MarkForRefinement_All (SmartPtr< IRefiner > ref)
Parameters
[in] ref
References MarkForRefinement_All().
MarkForRefinement_AllVolumesAnisotropic()
void ug4Bridge::Refinement::MarkForRefinement_AllVolumesAnisotropic (SmartPtr< IRefiner > ref)
Parameters
[in] ref
References MarkForRefinement_AllVolumesAnisotropic().
Referenced by MarkForRefinement_AllVolumesAnisotropic().
MarkForRefinement_AnisotropicDirection()
void ug4Bridge::Refinement::MarkForRefinement_AnisotropicDirection (Domain * dom, IRefiner * refiner, Vec * dir, double minEdgeRatio)
Parameters
[in] dom
[in] refiner
[in] dir
[in] minEdgeRatio
References Domain(), and MarkForRefinement_AnisotropicDirection().
MarkForRefinement_AnisotropicElements()
void ug4Bridge::Refinement::MarkForRefinement_AnisotropicElements (Domain * dom, IRefiner * refiner, double minEdgeRatio)
Parameters
[in] dom
[in] refiner
[in] minEdgeRatio
References Domain(), and MarkForRefinement_AnisotropicElements().
MarkForRefinement_CloseToSurface()
void ug4Bridge::Refinement::MarkForRefinement_CloseToSurface (Domain * unnamed, SmartPtr< IRefiner > unnamed, double unnamed, size_t unnamed, const Domain * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References Domain(), and MarkForRefinement_CloseToSurface().
MarkForRefinement_ContainsSurfaceNode()
void ug4Bridge::Refinement::MarkForRefinement_ContainsSurfaceNode (Domain * unnamed, SmartPtr< IRefiner > unnamed, double unnamed, size_t unnamed, const Domain * unnamed)
Parameters
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
[in] unnamed
References Domain(), and MarkForRefinement_ContainsSurfaceNode().
MarkForRefinement_EdgeDirection()
void ug4Bridge::Refinement::MarkForRefinement_EdgeDirection (Domain * dom, IRefiner * refiner, Vec * dir, double minDeviationAngle, double maxDeviationAngle, bool selectFlipped)
Parameters
[in] dom
[in] refiner
[in] dir
[in] minDeviationAngle
[in] maxDeviationAngle
[in] selectFlipped
References Domain(), and MarkForRefinement_EdgeDirection().
MarkForRefinement_EdgesInSphere()
void ug4Bridge::Refinement::MarkForRefinement_EdgesInSphere (Domain * dom, SmartPtr< IRefiner > refiner, const Vec * center, double radius)
Parameters
[in] dom
[in] refiner
[in] center
[in] radius
References Domain(), and MarkForRefinement_EdgesInSphere().
Referenced by MarkForRefinement_EdgesInSphere().
MarkForRefinement_EdgesInSubset()
void ug4Bridge::Refinement::MarkForRefinement_EdgesInSubset (Domain * dom, IRefiner * refiner, MGSubsetHandler * subsetHandler, int subsetIndex)
Parameters
[in] dom
[in] refiner
[in] subsetHandler
[in] subsetIndex
References Domain(), and MarkForRefinement_EdgesInSubset().
Referenced by MarkForRefinement_EdgesInSubset().
MarkForRefinement_ElementsByLuaCallback()
void ug4Bridge::Refinement::MarkForRefinement_ElementsByLuaCallback (Domain * dom, SmartPtr< IRefiner > refiner, double time, size_t callbackName, const char * unnamed)
Parameters
[in] dom
[in] refiner
[in] time
[in] callbackName
[in] unnamed
References Domain(), and MarkForRefinement_ElementsByLuaCallback().
MarkForRefinement_ElementsInSubset()
void ug4Bridge::Refinement::MarkForRefinement_ElementsInSubset (Domain * dom, IRefiner * refiner, MGSubsetHandler * subsetHandler, int subsetIndex)
Parameters
[in] dom
[in] refiner
[in] subsetHandler
[in] subsetIndex
References Domain(), and MarkForRefinement_ElementsInSubset().
MarkForRefinement_FacesInSphere()
void ug4Bridge::Refinement::MarkForRefinement_FacesInSphere (Domain * dom, SmartPtr< IRefiner > refiner, const Vec * center, double radius)
Parameters
[in] dom
[in] refiner
[in] center
[in] radius
References Domain(), and MarkForRefinement_FacesInSphere().
Referenced by MarkForRefinement_FacesInSphere().
MarkForRefinement_FacesInSubset()
void ug4Bridge::Refinement::MarkForRefinement_FacesInSubset (Domain * dom, IRefiner * refiner, MGSubsetHandler * subsetHandler, int subsetIndex)
Parameters
[in] dom
[in] refiner
[in] subsetHandler
[in] subsetIndex
References Domain(), and MarkForRefinement_FacesInSubset().
Referenced by MarkForRefinement_FacesInSubset().
MarkForRefinement_SubsetInterfaceEdges()
void ug4Bridge::Refinement::MarkForRefinement_SubsetInterfaceEdges (Domain * unnamed, IRefiner * unnamed)
Parameters
[in] unnamed
[in] unnamed
References Domain(), and MarkForRefinement_SubsetInterfaceEdges().
Referenced by MarkForRefinement_SubsetInterfaceEdges().
MarkForRefinement_SubsetInterfaceFaces()
void ug4Bridge::Refinement::MarkForRefinement_SubsetInterfaceFaces (Domain * unnamed, IRefiner * unnamed)
Parameters
[in] unnamed
[in] unnamed
References Domain(), and MarkForRefinement_SubsetInterfaceFaces().
Referenced by MarkForRefinement_SubsetInterfaceFaces().
MarkForRefinement_SubsetInterfaceVertices()
void ug4Bridge::Refinement::MarkForRefinement_SubsetInterfaceVertices (Domain * unnamed, IRefiner * unnamed)
Parameters
[in] unnamed
[in] unnamed
References Domain(), and MarkForRefinement_SubsetInterfaceVertices().
Referenced by MarkForRefinement_SubsetInterfaceVertices().
MarkForRefinement_VerticesInCube()
void ug4Bridge::Refinement::MarkForRefinement_VerticesInCube (Domain * dom, SmartPtr< IRefiner > refiner, const Vec * min, const Vec * max)
Parameters
[in] dom
[in] refiner
[in] min
[in] max
References Domain(), and MarkForRefinement_VerticesInCube().
MarkForRefinement_VerticesInSphere()
void ug4Bridge::Refinement::MarkForRefinement_VerticesInSphere (Domain * dom, SmartPtr< IRefiner > refiner, const Vec * center, double radius)
Parameters
[in] dom
[in] refiner
[in] center
[in] radius
References Domain(), and MarkForRefinement_VerticesInSphere().
MarkForRefinement_VerticesInSubset()
void ug4Bridge::Refinement::MarkForRefinement_VerticesInSubset (Domain * dom, IRefiner * refiner, MGSubsetHandler * subsetHandler, int subsetIndex)
Parameters
[in] dom
[in] refiner
[in] subsetHandler
[in] subsetIndex
References Domain(), and MarkForRefinement_VerticesInSubset().
Referenced by MarkForRefinement_VerticesInSubset().
MarkForRefinement_VolumesInSphere()
void ug4Bridge::Refinement::MarkForRefinement_VolumesInSphere (Domain * dom, SmartPtr< IRefiner > refiner, const Vec * center, double radius)
Parameters
[in] dom
[in] refiner
[in] center
[in] radius
References Domain(), and MarkForRefinement_VolumesInSphere().
Referenced by MarkForRefinement_VolumesInSphere().
MarkForRefinement_VolumesInSubset()
void ug4Bridge::Refinement::MarkForRefinement_VolumesInSubset (Domain * dom, IRefiner * refiner, MGSubsetHandler * subsetHandler, int subsetIndex)
Parameters
[in] dom
[in] refiner
[in] subsetHandler
[in] subsetIndex
References Domain(), and MarkForRefinement_VolumesInSubset().
Referenced by MarkForRefinement_VolumesInSubset().
MarkNeighborsForAnisotropicRefinement()
void ug4Bridge::Refinement::MarkNeighborsForAnisotropicRefinement (IRefiner * refiner, bool sideNeighborsOnly)
Parameters
[in] refiner
[in] sideNeighborsOnly
References MarkNeighborsForAnisotropicRefinement().
MarkNeighborsForFullRefinement()
void ug4Bridge::Refinement::MarkNeighborsForFullRefinement (IRefiner * refiner, bool sideNeighborsOnly)
Parameters
[in] refiner
[in] sideNeighborsOnly
References MarkNeighborsForFullRefinement().
ProjectHierarchyToLimitSubdivisionSurface()
void ug4Bridge::Refinement::ProjectHierarchyToLimitSubdivisionSurface (MultiGrid * unnamed)
Parameters
[in] unnamed
References ProjectHierarchyToLimitSubdivisionSurface().
ProjectHierarchyToLimitSubdivisionVolume()
void ug4Bridge::Refinement::ProjectHierarchyToLimitSubdivisionVolume (MultiGrid * unnamed)
Parameters
[in] unnamed
References ProjectHierarchyToLimitSubdivisionVolume().
SetSmoothSubdivisionVolumesBoundaryRefinementRule()
void ug4Bridge::Refinement::SetSmoothSubdivisionVolumesBoundaryRefinementRule (std::string bndRefRule)
Sets the boundary refinement rule used during Subdivision Volumes smoothing. Possible parameters: 'linear', 'subdiv_surf_loop_scheme', 'subdiv_surf_averaging_scheme' or 'subdiv_vol'.
Parameters
[in] bndRefRule
References SetSmoothSubdivisionVolumesBoundaryRefinementRule().
SetTetRefinementRule()
void ug4Bridge::Refinement::SetTetRefinementRule (std::string refRuleName)
Sets the refinement rule which is used to refine tetrahedrons. Possible parameters: 'standard', 'hybrid_tet_oct.
Parameters
[in] refRuleName
References SetTetRefinementRule().
TetrahedralizeHybridTetOctGrid()
void ug4Bridge::Refinement::TetrahedralizeHybridTetOctGrid (MultiGrid * unnamed, int unnamed)
Parameters
[in] unnamed
[in] unnamed
References TetrahedralizeHybridTetOctGrid().