Registry: ug4Bridge::promesh::CoordinateTransform Namespace Reference
ug4Bridge::promesh::CoordinateTransform Namespace Reference
Namespaces
Move
Pivot
Rotate
Scale
Smoothing
SubdivisionProjection
Functions
void ConeTransform (Mesh *mesh, const Vec3d *base, const Vec3d *axis, double scaleAtTip)
Transforms the vertices with the given cone transformation.
void FlattenBentQuadrilaterals (Mesh *mesh, double step_size, int num_iterations)
Flattens bent quadrilaterals using an iterative flattening scheme.
bool GetSelectionCenter (Mesh *mesh, Vec3d *centerOut)
void Mirror (Mesh *mesh, const Vec3d *axis, const Vec3d *origin)
Mirrors the geometry at the given point along the given axis.
void ProjectToPlane (Mesh *mesh, const Vec3d *plane_point, const Vec3d *plane_normal)
Projects all selected elements to the specified plane.
void SnapVerticesToVertices (Mesh *mesh, Mesh *targetMesh)
Snaps the selected vertices of the specified mesh to the selected vertices of the target mesh.
Function Documentation
ConeTransform()
void ug4Bridge::promesh::CoordinateTransform::ConeTransform (Mesh * mesh, const Vec3d * base, const Vec3d * axis, double scaleAtTip)
Transforms the vertices with the given cone transformation.
Parameters
[in] mesh
[in] base
[in] axis
[in] scaleAtTip
References ConeTransform().
FlattenBentQuadrilaterals()
void ug4Bridge::promesh::CoordinateTransform::FlattenBentQuadrilaterals (Mesh * mesh, double step_size, int num_iterations)
Flattens bent quadrilaterals using an iterative flattening scheme.
Parameters
[in] mesh
[in] step_size
[in] num_iterations
References FlattenBentQuadrilaterals().
GetSelectionCenter()
bool ug4Bridge::promesh::CoordinateTransform::GetSelectionCenter (Mesh * mesh, Vec3d * centerOut)
Parameters
[in] mesh
[in] centerOut
References GetSelectionCenter().
Mirror()
void ug4Bridge::promesh::CoordinateTransform::Mirror (Mesh * mesh, const Vec3d * axis, const Vec3d * origin)
Mirrors the geometry at the given point along the given axis.
Parameters
[in] mesh
[in] axis
[in] origin
References Mirror().
ProjectToPlane()
void ug4Bridge::promesh::CoordinateTransform::ProjectToPlane (Mesh * mesh, const Vec3d * plane_point, const Vec3d * plane_normal)
Projects all selected elements to the specified plane.
Parameters
[in] mesh
[in] plane_point
[in] plane_normal
References ProjectToPlane().
SnapVerticesToVertices()
void ug4Bridge::promesh::CoordinateTransform::SnapVerticesToVertices (Mesh * mesh, Mesh * targetMesh)
Snaps the selected vertices of the specified mesh to the selected vertices of the target mesh.
Parameters
[in] mesh
[in] targetMesh
References SnapVerticesToVertices().