Registry: ug4Bridge::promesh::Subsets::Separate Namespace Reference
ug4Bridge::promesh::Subsets::Separate Namespace Reference
Functions
void SeparateDegeneratedBoundaryFaceSubsets (Mesh *mesh, double angle)
Separates degenerated boundary face subsets at sharp creases.
void SeparateFacesByEdgeSubsets (Mesh *mesh)
Assigns faces that are surrounded by a set of edge-subsets to a common subset.
void SeparateFacesBySelectedEdges (Mesh *mesh)
Assigns faces that are surrounded by a set of selected edges to a common subset.
void SeparateFaceSubsetByNormal (Mesh *mesh, int subset_index)
Collects faces of a given subset that have a similar normal and assigns them to new subsets.
void SeparateFaceSubsetsByNormal (Mesh *mesh)
Collects faces of each subset that have a similar normal and assigns them to new subsets.
void SeparateIrregularManifoldSubsets (Mesh *mesh)
After this algorithm all face-subsets are regular manifolds.
void SeparateVolumesByFaceSubsets (Mesh *mesh)
Assigns volumes that are surrounded by a set of face-subsets to a common subset.
void SeparateVolumesBySelectedFaces (Mesh *mesh)
Assigns volumes that are surrounded by a set of selected faces to a common subset.
Function Documentation
SeparateDegeneratedBoundaryFaceSubsets()
void ug4Bridge::promesh::Subsets::Separate::SeparateDegeneratedBoundaryFaceSubsets (Mesh * mesh, double angle)
Separates degenerated boundary face subsets at sharp creases.
Parameters
[in] mesh
[in] angle
References SeparateDegeneratedBoundaryFaceSubsets().
SeparateFacesByEdgeSubsets()
void ug4Bridge::promesh::Subsets::Separate::SeparateFacesByEdgeSubsets (Mesh * mesh)
Assigns faces that are surrounded by a set of edge-subsets to a common subset.
Parameters
[in] mesh
References SeparateFacesByEdgeSubsets().
SeparateFacesBySelectedEdges()
void ug4Bridge::promesh::Subsets::Separate::SeparateFacesBySelectedEdges (Mesh * mesh)
Assigns faces that are surrounded by a set of selected edges to a common subset.
Parameters
[in] mesh
References SeparateFacesBySelectedEdges().
SeparateFaceSubsetByNormal()
void ug4Bridge::promesh::Subsets::Separate::SeparateFaceSubsetByNormal (Mesh * mesh, int subset_index)
Collects faces of a given subset that have a similar normal and assigns them to new subsets.
Parameters
[in] mesh
[in] subset_index
References SeparateFaceSubsetByNormal().
SeparateFaceSubsetsByNormal()
void ug4Bridge::promesh::Subsets::Separate::SeparateFaceSubsetsByNormal (Mesh * mesh)
Collects faces of each subset that have a similar normal and assigns them to new subsets.
Parameters
[in] mesh
References SeparateFaceSubsetsByNormal().
SeparateIrregularManifoldSubsets()
void ug4Bridge::promesh::Subsets::Separate::SeparateIrregularManifoldSubsets (Mesh * mesh)
After this algorithm all face-subsets are regular manifolds.
Parameters
[in] mesh
References SeparateIrregularManifoldSubsets().
SeparateVolumesByFaceSubsets()
void ug4Bridge::promesh::Subsets::Separate::SeparateVolumesByFaceSubsets (Mesh * mesh)
Assigns volumes that are surrounded by a set of face-subsets to a common subset.
Parameters
[in] mesh
References SeparateVolumesByFaceSubsets().
SeparateVolumesBySelectedFaces()
void ug4Bridge::promesh::Subsets::Separate::SeparateVolumesBySelectedFaces (Mesh * mesh)
Assigns volumes that are surrounded by a set of selected faces to a common subset.
Parameters
[in] mesh
References SeparateVolumesBySelectedFaces().