Registry: ug4Bridge::promesh::Selection::SubsetBased Namespace Reference
ug4Bridge::promesh::Selection::SubsetBased Namespace Reference
Functions
void SelectSubset (Mesh *mesh, int subset_index, bool vertices, bool edges, bool faces, bool volumes)
Selects all elements of a subset.
void SelectSubsetBoundary (Mesh *mesh, int subset_index, bool boundaries_of_edges, bool boundaries_of_faces, bool boundaries_of_volumes)
Selects the boundary of a subset.
void SelectUnassignedElements (Mesh *mesh, bool vertices, bool edges, bool faces, bool volumes)
Selects all elements not assigned to any subset.
Function Documentation
SelectSubset()
void ug4Bridge::promesh::Selection::SubsetBased::SelectSubset (Mesh * mesh, int subset_index, bool vertices, bool edges, bool faces, bool volumes)
Selects all elements of a subset.
Parameters
[in] mesh
[in] subset_index
[in] vertices
[in] edges
[in] faces
[in] volumes
References SelectSubset().
SelectSubsetBoundary()
void ug4Bridge::promesh::Selection::SubsetBased::SelectSubsetBoundary (Mesh * mesh, int subset_index, bool boundaries_of_edges, bool boundaries_of_faces, bool boundaries_of_volumes)
Selects the boundary of a subset.
Parameters
[in] mesh
[in] subset_index
[in] boundaries_of_edges
[in] boundaries_of_faces
[in] boundaries_of_volumes
References SelectSubsetBoundary().
SelectUnassignedElements()
void ug4Bridge::promesh::Selection::SubsetBased::SelectUnassignedElements (Mesh * mesh, bool vertices, bool edges, bool faces, bool volumes)
Selects all elements not assigned to any subset.
Parameters
[in] mesh
[in] vertices
[in] edges
[in] faces
[in] volumes
References SelectUnassignedElements().