Apps: /home/runner/work/docs/docs/ug4/apps/navier_stokes/MovingParticle/Sedimenting Particle - stationary/many_radii/SedimentingDisc_stationary_many_radii.lua File Reference
SedimentingDisc_stationary_many_radii.lua File Reference
Functions
function Density (x, y, t)
function Pressure_StartValue2d (x, y, t) return 0.0 end
function VelX_StartValue2d (x, y, t) return 0.0 end
function VelY_StartValue2d (x, y, t) return 0.0 end
function ZeroSolution (x, y, t)
Variables
parameterNumber dim = 2
world dimension
parameterString grid = "grids/channel_4x12_irregular_tri_PrsBndCond.ugx"
parameterNumber newtonMinDef = 1e
parameterNumber newtonRed = 1e
parameterNumber numPreRefs = 5
number of prerefinements (parallel)
parameterNumber numRefs = 5
number of grid refinements
Function Documentation
Density()
function Density (x , y , t)
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes/MovingParticle/Sedimenting Particle - stationary/many_radii / SedimentingDisc_stationary_many_radii.lua :215-218
function Density(x, y, t)
    dens = densityFluid
    return dens
end
References for().
Pressure_StartValue2d()
function Pressure_StartValue2d (x , y , t)
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes/MovingParticle/Sedimenting Particle - stationary/many_radii / SedimentingDisc_stationary_many_radii.lua :369
function Pressure_StartValue2d(x, y, t) return 0.0 end
VelX_StartValue2d()
function VelX_StartValue2d (x , y , t)
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes/MovingParticle/Sedimenting Particle - stationary/many_radii / SedimentingDisc_stationary_many_radii.lua :370
function VelX_StartValue2d(x, y, t)     return 0.0 end
References if().
VelY_StartValue2d()
function VelY_StartValue2d (x , y , t)
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes/MovingParticle/Sedimenting Particle - stationary/many_radii / SedimentingDisc_stationary_many_radii.lua :371
function VelY_StartValue2d(x, y, t)     return 0.0 end
ZeroSolution()
function ZeroSolution (x , y , t)
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes/MovingParticle/Sedimenting Particle - stationary/many_radii / SedimentingDisc_stationary_many_radii.lua :166-168
function ZeroSolution(x, y, t)
    return 0.0
end
References for().
Variable Documentation
dim
parameterNumber dim = 2
world dimension
grid
parameterString grid = "grids/channel_4x12_irregular_tri_PrsBndCond.ugx"
newtonMinDef
parameterNumber newtonMinDef = 1e
newtonRed
parameterNumber newtonRed = 1e
numPreRefs
parameterNumber numPreRefs = 5
number of prerefinements (parallel)
numRefs
parameterNumber numRefs = 5
number of grid refinements