Apps: /home/runner/work/docs/docs/ug4/apps/navier_stokes/navier_stokes_util.lua File Reference
navier_stokes_util.lua File Reference
Functions
function util gmg create (approxSpace, smoother, numPreSmooth, numPostSmooth, cycle, baseSolver, baseLev, bRAP)
function util smooth create (smooth)
function util solver create (sol, precond)
function util ns CreateApproxSpace (dom, type, vorder, porder)
function util ns parseParams ()
Function Documentation
create() [1/3]
function util gmg create (approxSpace , smoother , numPreSmooth , numPostSmooth , cycle , baseSolver , baseLev , bRAP)
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes / navier_stokes_util.lua :82-96
function util.gmg.create(approxSpace, smoother, numPreSmooth, numPostSmooth,
  local gmg = GeometricMultiGrid(approxSpace)
  gmg:set_base_level(baseLev)
  gmg:set_base_solver(baseSolver)
  gmg:set_gathered_base_solver_if_ambiguous(true)
  gmg:set_smoother(smoother)
  gmg:set_cycle_type(cycle)
  gmg:set_num_presmooth(numPreSmooth)
  gmg:set_num_postsmooth(numPostSmooth)
  gmg:set_rap(bRAP)
  return gmg
end
create() [2/3]
function util smooth create (smooth)
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes / navier_stokes_util.lua :108-130
References local().
create() [3/3]
function util solver create (sol , precond)
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes / navier_stokes_util.lua :141-183
CreateApproxSpace()
function util ns CreateApproxSpace (dom , type , vorder , porder)
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes / navier_stokes_util.lua :27-58
References local().
parseParams()
function util ns parseParams ()
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes / navier_stokes_util.lua :5-25
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes / navier_stokes_util.lua :63-79
function util.gmg.parseParams()
  local numPreSmooth, numPostSmooth
  if util.HasParamOption("-numSmooth") then
    numPreSmooth  = util.GetParamNumber("-numSmooth", 8, "Number pre/post-smoothing")
    numPostSmooth = numPreSmooth
  else
    numPreSmooth  = util.GetParamNumber("-numPreSmooth", 8, "Number pre-smoothing")
    numPostSmooth = util.GetParamNumber("-numPostSmooth", 8, "Number post-smoothing")
  end
  local baseLev = util.GetParamNumber("-baseLev", 0, "Base level")
  local cycle =  util.GetParam("-cycle", "V", "gmg-cycle type", {"V","W","F"})
  local bRAP = util.HasParamOption("-rap", "use rap product as level matrices")
  return numPreSmooth, numPostSmooth, baseLev, cycle, bRAP
end
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes / navier_stokes_util.lua :101-106
function util.smooth.parseParams()
  local smooth = util.GetParam("-smooth", "cgs", "Smoother Type",
          {"jac","ilu","ilut","egs","gs","sgs", "cgs", "ssc"})
  return smooth
end
location: /home/runner/work/docs/docs/ug4/apps/navier_stokes / navier_stokes_util.lua :135-139
function util.solver.parseParams()
  local solver = util.GetParam("-solver", "bicgstab", "Linear Solver Type",
                {"ls","bicgstab","cg","lu","schur", "gmres"})
  return solver
end
References local().