var searchData=
[
  ['eddycurrent_5fe_5fnedelec_16614',['EddyCurrent_E_Nedelec',['../../plugins/classug_1_1_electromagnetism_1_1_eddy_current___e___nedelec.html',1,'EddyCurrent_E_Nedelec&lt; class, class &gt;'],['../classug4_bridge_1_1_spatial_disc_1_1_electromagnetism_1_1_eddy_current___e___nedelec.html',1,'EddyCurrent_E_Nedelec']]],
  ['eddycurrentcurledependentcmpuserdata_16615',['EddyCurrentCurlEDependentCmpUserData',['../../plugins/classug_1_1_electromagnetism_1_1_eddy_current_curl_e_dependent_cmp_user_data.html',1,'ug::Electromagnetism']]],
  ['eddycurrentcurledependentcmpuserdata_3c_20eddycurrentimbofeuserdata_3c_20tgridfunc_20_3e_2c_20eddycurrenttraits_3a_3a_5fre_5f_2c_20tgridfunc_20_3e_16616',['EddyCurrentCurlEDependentCmpUserData&lt; EddyCurrentImBofEUserData&lt; TGridFunc &gt;, EddyCurrentTraits::_Re_, TGridFunc &gt;',['../../plugins/classug_1_1_electromagnetism_1_1_eddy_current_curl_e_dependent_cmp_user_data.html',1,'']]],
  ['eddycurrentcurledependentcmpuserdata_3c_20eddycurrentrebofeuserdata_3c_20tgridfunc_20_3e_2c_20eddycurrenttraits_3a_3a_5fim_5f_2c_20tgridfunc_20_3e_16617',['EddyCurrentCurlEDependentCmpUserData&lt; EddyCurrentReBofEUserData&lt; TGridFunc &gt;, EddyCurrentTraits::_Im_, TGridFunc &gt;',['../../plugins/classug_1_1_electromagnetism_1_1_eddy_current_curl_e_dependent_cmp_user_data.html',1,'']]],
  ['eddycurrentheat_16618',['EddyCurrentHeat',['../../plugins/classug_1_1_electromagnetism_1_1_eddy_current_heat.html',1,'EddyCurrentHeat&lt; class &gt;'],['../classug4_bridge_1_1_spatial_disc_1_1_electromagnetism_1_1_eddy_current_heat.html',1,'EddyCurrentHeat']]],
  ['eddycurrentimbofeuserdata_16619',['EddyCurrentImBofEUserData',['../../plugins/classug_1_1_electromagnetism_1_1_eddy_current_im_bof_e_user_data.html',1,'EddyCurrentImBofEUserData&lt; class &gt;'],['../classug4_bridge_1_1_spatial_disc_1_1_electromagnetism_1_1_eddy_current_im_bof_e_user_data.html',1,'EddyCurrentImBofEUserData']]],
  ['eddycurrentrebofeuserdata_16620',['EddyCurrentReBofEUserData',['../classug4_bridge_1_1_spatial_disc_1_1_electromagnetism_1_1_eddy_current_re_bof_e_user_data.html',1,'EddyCurrentReBofEUserData'],['../../plugins/classug_1_1_electromagnetism_1_1_eddy_current_re_bof_e_user_data.html',1,'EddyCurrentReBofEUserData&lt; class &gt;']]],
  ['eddycurrenttraits_16621',['EddyCurrentTraits',['../../plugins/classug_1_1_electromagnetism_1_1_eddy_current_traits.html',1,'ug::Electromagnetism']]],
  ['edge_16622',['Edge',['../../classug_1_1_edge.html',1,'Edge'],['../classug4_bridge_1_1_grid_1_1_edge.html',1,'Edge']]],
  ['edgeattachmentaccessor_16623',['EdgeAttachmentAccessor',['../../classug_1_1_grid_1_1_edge_attachment_accessor.html',1,'ug::Grid']]],
  ['edgeattachmentaccessor_3c_20attachment_3c_20edgeinfo_20_3e_20_3e_16624',['EdgeAttachmentAccessor&lt; Attachment&lt; EdgeInfo &gt; &gt;',['../../classug_1_1_grid_1_1_edge_attachment_accessor.html',1,'']]],
  ['edgeattachmentaccessor_3c_20attachment_3c_20eleminfoedge_20_3e_20_3e_16625',['EdgeAttachmentAccessor&lt; Attachment&lt; ElemInfoEdge &gt; &gt;',['../../classug_1_1_grid_1_1_edge_attachment_accessor.html',1,'']]],
  ['edgeattachmentaccessor_3c_20attachment_3c_20int_20_3e_20_3e_16626',['EdgeAttachmentAccessor&lt; Attachment&lt; int &gt; &gt;',['../../classug_1_1_grid_1_1_edge_attachment_accessor.html',1,'']]],
  ['edgeattachmentaccessor_3c_20ug_3a_3aattachment_20_3e_16627',['EdgeAttachmentAccessor&lt; ug::Attachment &gt;',['../../classug_1_1_grid_1_1_edge_attachment_accessor.html',1,'']]],
  ['edgedescriptor_16628',['EdgeDescriptor',['../../classug_1_1_edge_descriptor.html',1,'ug']]],
  ['edgeiterator_16629',['EdgeIterator',['../classug4_bridge_1_1promesh_1_1_edge_iterator.html',1,'ug4Bridge::promesh']]],
  ['edgetoquadinfo_16630',['EdgeToQuadInfo',['../../structug_1_1detail_1_1quad_util_1_1_edge_to_quad_info.html',1,'ug::detail::quadUtil']]],
  ['edgevertices_16631',['EdgeVertices',['../../classug_1_1_edge_vertices.html',1,'ug']]],
  ['eigensolver_16632',['EigenSolver',['../classug4_bridge_1_1_algebra_1_1_solver_1_1_eigen_solver.html',1,'ug4Bridge::Algebra::Solver']]],
  ['elemdata_16633',['ElemData',['../../plugins/structug_1_1_small_strain_mechanics_1_1_prandtl_reuss_1_1_elem_data.html',1,'ug::SmallStrainMechanics::PrandtlReuss']]],
  ['element_16634',['Element',['../../classug_1_1_k_d_tree_1_1_element.html',1,'ug::KDTree']]],
  ['element_5flist_5ftraits_16635',['element_list_traits',['../../classug_1_1element__list__traits.html',1,'ug']]],
  ['elementboxfilter_16636',['ElementBoxFilter',['../classug4_bridge_1_1_spatial_disc_1_1_navier_stokes_1_1_spatial_disc_1_1_navier_stokes_1_1_element_box_filter.html',1,'ElementBoxFilter'],['../../plugins/classug_1_1_navier_stokes_1_1_element_box_filter.html',1,'ElementBoxFilter&lt; class &gt;']]],
  ['elementcallback_16637',['ElementCallback',['../../classug_1_1_element_callback.html',1,'ug']]],
  ['elementgaussseidel_16638',['ElementGaussSeidel',['../classug4_bridge_1_1_discretization_1_1_multi_grid_1_1_element_gauss_seidel.html',1,'ElementGaussSeidel'],['../../classug_1_1_element_gauss_seidel.html',1,'ElementGaussSeidel&lt; class, class &gt;']]],
  ['elementinfo_16639',['ElementInfo',['../../classug_1_1_distributed_grid_manager_1_1_element_info.html',1,'ug::DistributedGridManager']]],
  ['elementiterator_16640',['ElementIterator',['../../plugins/classug_1_1promesh_1_1_element_iterator.html',1,'ug::promesh']]],
  ['elementsiderayintersectionwrapper_16641',['ElementSideRayIntersectionWrapper',['../../structug_1_1_element_side_ray_intersection_wrapper.html',1,'ug']]],
  ['elementsiderayintersectionwrapper_3c_20trefelem_2c_202_2c_202_20_3e_16642',['ElementSideRayIntersectionWrapper&lt; TRefElem, 2, 2 &gt;',['../../structug_1_1_element_side_ray_intersection_wrapper_3_01_t_ref_elem_00_012_00_012_01_4.html',1,'ug']]],
  ['elementsiderayintersectionwrapper_3c_20trefelem_2c_203_2c_203_20_3e_16643',['ElementSideRayIntersectionWrapper&lt; TRefElem, 3, 3 &gt;',['../../structug_1_1_element_side_ray_intersection_wrapper_3_01_t_ref_elem_00_013_00_013_01_4.html',1,'ug']]],
  ['elementstorage_16644',['ElementStorage',['../../classug_1_1_element_storage.html',1,'ug']]],
  ['elementstorage_3c_20edge_20_3e_16645',['ElementStorage&lt; Edge &gt;',['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; Edge &gt;'],['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; Edge &gt;']]],
  ['elementstorage_3c_20face_20_3e_16646',['ElementStorage&lt; Face &gt;',['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; Face &gt;'],['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; Face &gt;']]],
  ['elementstorage_3c_20ug_3a_3aedge_20_3e_16647',['ElementStorage&lt; ug::Edge &gt;',['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; ug::Edge &gt;'],['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; ug::Edge &gt;']]],
  ['elementstorage_3c_20ug_3a_3aface_20_3e_16648',['ElementStorage&lt; ug::Face &gt;',['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; ug::Face &gt;'],['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; ug::Face &gt;']]],
  ['elementstorage_3c_20ug_3a_3avertex_20_3e_16649',['ElementStorage&lt; ug::Vertex &gt;',['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; ug::Vertex &gt;'],['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; ug::Vertex &gt;']]],
  ['elementstorage_3c_20ug_3a_3avolume_20_3e_16650',['ElementStorage&lt; ug::Volume &gt;',['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; ug::Volume &gt;'],['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; ug::Volume &gt;']]],
  ['elementstorage_3c_20vertex_20_3e_16651',['ElementStorage&lt; Vertex &gt;',['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; Vertex &gt;'],['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; Vertex &gt;']]],
  ['elementstorage_3c_20volume_20_3e_16652',['ElementStorage&lt; Volume &gt;',['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; Volume &gt;'],['../../classug_1_1_element_storage.html',1,'ElementStorage&lt; Volume &gt;']]],
  ['elementstorageselector_16653',['ElementStorageSelector',['../../structug_1_1_element_storage_selector.html',1,'ug']]],
  ['elementstorageselector_3c_20edge_20_3e_16654',['ElementStorageSelector&lt; Edge &gt;',['../../structug_1_1_element_storage_selector_3_01_edge_01_4.html',1,'ug']]],
  ['elementstorageselector_3c_20face_20_3e_16655',['ElementStorageSelector&lt; Face &gt;',['../../structug_1_1_element_storage_selector_3_01_face_01_4.html',1,'ug']]],
  ['elementstorageselector_3c_20vertex_20_3e_16656',['ElementStorageSelector&lt; Vertex &gt;',['../../structug_1_1_element_storage_selector_3_01_vertex_01_4.html',1,'ug']]],
  ['elementstorageselector_3c_20volume_20_3e_16657',['ElementStorageSelector&lt; Volume &gt;',['../../structug_1_1_element_storage_selector_3_01_volume_01_4.html',1,'ug']]],
  ['elemerrorsortdesc_16658',['ElemErrorSortDesc',['../../structug_1_1_elem_error_sort_desc.html',1,'ug']]],
  ['elemlist_16659',['ElemList',['../../structug_1_1_partitioner___dynamic_bisection_1_1_elem_list.html',1,'ug::Partitioner_DynamicBisection']]],
  ['elemprolongationbase_16660',['ElemProlongationBase',['../../classug_1_1_elem_prolongation_base.html',1,'ug']]],
  ['elemprolongationbase_3c_20tdomain_2c_20crouzeixraviartelemtransfer_3c_20tdomain_20_3e_20_3e_16661',['ElemProlongationBase&lt; TDomain, CrouzeixRaviartElemTransfer&lt; TDomain &gt; &gt;',['../../classug_1_1_elem_prolongation_base.html',1,'']]],
  ['elemprolongationbase_3c_20tdomain_2c_20p1lagrangeelemtransfer_3c_20tdomain_20_3e_20_3e_16662',['ElemProlongationBase&lt; TDomain, P1LagrangeElemTransfer&lt; TDomain &gt; &gt;',['../../classug_1_1_elem_prolongation_base.html',1,'']]],
  ['elemprolongationbase_3c_20tdomain_2c_20piecewiseconstantelemtransfer_3c_20tdomain_20_3e_20_3e_16663',['ElemProlongationBase&lt; TDomain, PiecewiseConstantElemTransfer&lt; TDomain &gt; &gt;',['../../classug_1_1_elem_prolongation_base.html',1,'']]],
  ['elemprolongationbase_3c_20tdomain_2c_20stdlagrangeelemtransfer_3c_20tdomain_20_3e_20_3e_16664',['ElemProlongationBase&lt; TDomain, StdLagrangeElemTransfer&lt; TDomain &gt; &gt;',['../../classug_1_1_elem_prolongation_base.html',1,'']]],
  ['elemrestrictionbase_16665',['ElemRestrictionBase',['../../classug_1_1_elem_restriction_base.html',1,'ug']]],
  ['elemrestrictionbase_3c_20tdomain_2c_20crouzeixraviartelemtransfer_3c_20tdomain_20_3e_20_3e_16666',['ElemRestrictionBase&lt; TDomain, CrouzeixRaviartElemTransfer&lt; TDomain &gt; &gt;',['../../classug_1_1_elem_restriction_base.html',1,'']]],
  ['elemrestrictionbase_3c_20tdomain_2c_20p1lagrangeelemtransfer_3c_20tdomain_20_3e_20_3e_16667',['ElemRestrictionBase&lt; TDomain, P1LagrangeElemTransfer&lt; TDomain &gt; &gt;',['../../classug_1_1_elem_restriction_base.html',1,'']]],
  ['elemrestrictionbase_3c_20tdomain_2c_20piecewiseconstantelemtransfer_3c_20tdomain_20_3e_20_3e_16668',['ElemRestrictionBase&lt; TDomain, PiecewiseConstantElemTransfer&lt; TDomain &gt; &gt;',['../../classug_1_1_elem_restriction_base.html',1,'']]],
  ['elemrestrictionbase_3c_20tdomain_2c_20stdlagrangeelemtransfer_3c_20tdomain_20_3e_20_3e_16669',['ElemRestrictionBase&lt; TDomain, StdLagrangeElemTransfer&lt; TDomain &gt; &gt;',['../../classug_1_1_elem_restriction_base.html',1,'']]],
  ['ellipticcylinderprojector_16670',['EllipticCylinderProjector',['../../classug_1_1_elliptic_cylinder_projector.html',1,'ug']]],
  ['ematerial_16671',['EMaterial',['../../plugins/classug_1_1_electromagnetism_1_1_e_material.html',1,'EMaterial&lt; TDomain &gt;'],['../classug4_bridge_1_1_spatial_disc_1_1_electromagnetism_1_1_e_material.html',1,'EMaterial']]],
  ['ematerial_3c_20domain_5ftype_20_3e_16672',['EMaterial&lt; domain_type &gt;',['../../plugins/classug_1_1_electromagnetism_1_1_e_material.html',1,'EMaterial&lt; domain_type &gt;'],['../../plugins/classug_1_1_electromagnetism_1_1_e_material.html',1,'EMaterial&lt; domain_type &gt;']]],
  ['emdirichlet_16673',['EMDirichlet',['../../plugins/classug_1_1_electromagnetism_1_1_e_m_dirichlet.html',1,'EMDirichlet&lt; class, class &gt;'],['../classug4_bridge_1_1_spatial_disc_1_1_electromagnetism_1_1_e_m_dirichlet.html',1,'EMDirichlet']]],
  ['emdirichlet_3c_20tdomain_2c_20talgebra_20_3e_16674',['EMDirichlet&lt; TDomain, TAlgebra &gt;',['../../plugins/classug_1_1_electromagnetism_1_1_e_m_dirichlet.html',1,'ug::Electromagnetism']]],
  ['empty_3c_20list1_3c_20ug_3a_3aend_5fboost_5flist_20_3e_20_3e_16675',['empty&lt; list1&lt; ug::end_boost_list &gt; &gt;',['../../structboost_1_1mpl_1_1empty_3_01list1_3_01ug_1_1end__boost__list_01_4_01_4.html',1,'boost::mpl']]],
  ['empty_3c_20list_3c_20ug_3a_3aend_5fboost_5flist_20_3e_20_3e_16676',['empty&lt; list&lt; ug::end_boost_list &gt; &gt;',['../../structboost_1_1mpl_1_1empty_3_01list_3_01ug_1_1end__boost__list_01_4_01_4.html',1,'boost::mpl']]],
  ['emptyostream_16677',['EmptyOStream',['../../classug_1_1_empty_o_stream.html',1,'ug']]],
  ['emptystreambuffer_16678',['EmptyStreamBuffer',['../../classug_1_1_empty_stream_buffer.html',1,'ug']]],
  ['emptytype_16679',['EmptyType',['../../structug_1_1_empty_type.html',1,'ug']]],
  ['end_5fboost_5flist_16680',['end_boost_list',['../../structug_1_1end__boost__list.html',1,'ug']]],
  ['energyconvcheck_16681',['EnergyConvCheck',['../classug4_bridge_1_1_algebra_1_1_energy_conv_check.html',1,'EnergyConvCheck'],['../../classug_1_1_energy_conv_check.html',1,'EnergyConvCheck&lt; class &gt;']]],
  ['entry_16682',['Entry',['../../structug_1_1_attached_element_list_1_1_entry.html',1,'AttachedElementList&lt; class &gt;::Entry'],['../../structug_1_1_grid_writer_u_g_x_1_1_entry.html',1,'Entry'],['../../structug_1_1_com_pol___new_constrained_verticals_1_1_entry.html',1,'ComPol_NewConstrainedVerticals&lt; class &gt;::Entry'],['../../structug_1_1_distributed_grid_manager_1_1_element_info_1_1_entry.html',1,'DistributedGridManager::ElementInfo&lt; TGeomObj &gt;::Entry'],['../../structug_1_1_partitioner___dynamic_bisection_1_1_entry.html',1,'Entry'],['../../structug_1_1ntree_1_1_entry.html',1,'Entry'],['../../structug_1_1_hash_1_1_entry.html',1,'Entry']]],
  ['entrytype_16683',['EntryType',['../../structug_1_1bridge_1_1_parameter_info_1_1_entry_type.html',1,'ug::bridge::ParameterInfo']]],
  ['equidistantlagrange1d_16684',['EquidistantLagrange1D',['../../classug_1_1_equidistant_lagrange1_d.html',1,'ug']]],
  ['equilibrationmarking_16685',['EquilibrationMarking',['../classug4_bridge_1_1_discretization_1_1_adaptive_1_1_equilibration_marking.html',1,'ug4Bridge::Discretization::Adaptive']]],
  ['equilibrationmarkingstrategy_16686',['EquilibrationMarkingStrategy',['../../classug_1_1_equilibration_marking_strategy.html',1,'ug']]],
  ['errestdata_16687',['ErrEstData',['../classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_err_est_data.html',1,'ug4Bridge::Discretization::SpatialDisc']]],
  ['error_16688',['Error',['../../classug_1_1_message_hub_1_1_error.html',1,'ug::MessageHub']]],
  ['errorevaluator_16689',['ErrorEvaluator',['../../classug_1_1_error_evaluator.html',1,'ug']]],
  ['expandlayersdesc_16690',['ExpandLayersDesc',['../classug4_bridge_1_1_grid_1_1_expand_layers_desc.html',1,'ExpandLayersDesc'],['../../classug_1_1bridge_1_1_expand_layers_desc.html',1,'ExpandLayersDesc']]],
  ['expectederrormarkingstrategy_16691',['ExpectedErrorMarkingStrategy',['../classug4_bridge_1_1_discretization_1_1_adaptive_1_1_expected_error_marking_strategy.html',1,'ExpectedErrorMarkingStrategy'],['../../classug_1_1_expected_error_marking_strategy.html',1,'ExpectedErrorMarkingStrategy&lt; class &gt;']]],
  ['explicitgridfunctiongradient_16692',['ExplicitGridFunctionGradient',['../classug4_bridge_1_1_discretization_1_1_approximation_space_1_1_explicit_grid_function_gradient.html',1,'ExplicitGridFunctionGradient'],['../../classug_1_1_explicit_grid_function_gradient.html',1,'ExplicitGridFunctionGradient&lt; class &gt;']]],
  ['explicitgridfunctionvalue_16693',['ExplicitGridFunctionValue',['../classug4_bridge_1_1_discretization_1_1_approximation_space_1_1_explicit_grid_function_value.html',1,'ExplicitGridFunctionValue'],['../../classug_1_1_explicit_grid_function_value.html',1,'ExplicitGridFunctionValue&lt; class &gt;']]],
  ['explicitgridfunctionvector_16694',['ExplicitGridFunctionVector',['../classug4_bridge_1_1_discretization_1_1_approximation_space_1_1_explicit_grid_function_vector.html',1,'ExplicitGridFunctionVector'],['../../classug_1_1_explicit_grid_function_vector.html',1,'ExplicitGridFunctionVector&lt; class &gt;']]],
  ['exportedclass_16695',['ExportedClass',['../../classug_1_1bridge_1_1_exported_class.html',1,'ug::bridge']]],
  ['exportedclassbaseimpl_16696',['ExportedClassBaseImpl',['../../classug_1_1bridge_1_1_exported_class_base_impl.html',1,'ug::bridge']]],
  ['exportedconstructor_16697',['ExportedConstructor',['../../classug_1_1bridge_1_1_exported_constructor.html',1,'ug::bridge']]],
  ['exportedfunction_16698',['ExportedFunction',['../../classug_1_1bridge_1_1_exported_function.html',1,'ug::bridge']]],
  ['exportedfunctionbase_16699',['ExportedFunctionBase',['../../classug_1_1bridge_1_1_exported_function_base.html',1,'ug::bridge']]],
  ['exportedfunctiongroup_16700',['ExportedFunctionGroup',['../../classug_1_1bridge_1_1_exported_function_group.html',1,'ug::bridge']]],
  ['exportedmethod_16701',['ExportedMethod',['../../classug_1_1bridge_1_1_exported_method.html',1,'ug::bridge']]],
  ['exportedmethodgroup_16702',['ExportedMethodGroup',['../../classug_1_1bridge_1_1_exported_method_group.html',1,'ug::bridge']]],
  ['extcon_16703',['ExtCon',['../../structug_1_1_com_pol___mat_create_overlap_1_1_ext_con.html',1,'ug::ComPol_MatCreateOverlap']]],
  ['externalsolvercpu1_16704',['ExternalSolverCPU1',['../classug4_bridge_1_1_algebra_1_1_solver_1_1_external_solver_c_p_u1.html',1,'ug4Bridge::Algebra::Solver']]],
  ['externalsolvercpu2_16705',['ExternalSolverCPU2',['../classug4_bridge_1_1_algebra_1_1_solver_1_1_external_solver_c_p_u2.html',1,'ug4Bridge::Algebra::Solver']]],
  ['externalsolvercpu3_16706',['ExternalSolverCPU3',['../classug4_bridge_1_1_algebra_1_1_solver_1_1_external_solver_c_p_u3.html',1,'ug4Bridge::Algebra::Solver']]],
  ['extractorinfo_16707',['ExtractorInfo',['../../structpcl_1_1_interface_communicator_1_1_extractor_info.html',1,'pcl::InterfaceCommunicator']]]
];
