var searchData=
[
  ['damagefunctionupdater_16497',['DamageFunctionUpdater',['../classug4_bridge_1_1_spatial_disc_1_1_small_strain_mechanics_1_1_damage_function_updater.html',1,'DamageFunctionUpdater'],['../../plugins/classug_1_1_small_strain_mechanics_1_1_damage_function_updater.html',1,'DamageFunctionUpdater&lt; class &gt;']]],
  ['damagelaw_16498',['DamageLaw',['../../plugins/classug_1_1_small_strain_mechanics_1_1_damage_law.html',1,'DamageLaw&lt; class &gt;'],['../classug4_bridge_1_1_spatial_disc_1_1_small_strain_mechanics_1_1_damage_law.html',1,'DamageLaw']]],
  ['darcyvelocitylinker_16499',['DarcyVelocityLinker',['../../classug_1_1_darcy_velocity_linker.html',1,'DarcyVelocityLinker&lt; dim &gt;'],['../classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_darcy_velocity_linker.html',1,'DarcyVelocityLinker']]],
  ['data_16500',['Data',['../../structug_1_1_neumann_boundary_base_1_1_data.html',1,'Data'],['../../structug_1_1_distributed_grid_manager_1_1_element_info_1_1_data.html',1,'Data']]],
  ['data_5fitem_16501',['data_item',['../../structug_1_1_i_d_w_user_data_1_1data__item.html',1,'ug::IDWUserData']]],
  ['dataevaluator_16502',['DataEvaluator',['../../classug_1_1_data_evaluator.html',1,'ug']]],
  ['dataevaluatorbase_16503',['DataEvaluatorBase',['../../classug_1_1_data_evaluator_base.html',1,'ug']]],
  ['dataevaluatorbase_3c_20tdomain_2c_20ielemdisc_3c_20tdomain_20_3e_20_3e_16504',['DataEvaluatorBase&lt; TDomain, IElemDisc&lt; TDomain &gt; &gt;',['../../classug_1_1_data_evaluator_base.html',1,'']]],
  ['dataevaluatorbase_3c_20tdomain_2c_20ielemerror_3c_20tdomain_20_3e_20_3e_16505',['DataEvaluatorBase&lt; TDomain, IElemError&lt; TDomain &gt; &gt;',['../../classug_1_1_data_evaluator_base.html',1,'']]],
  ['dataexport_16506',['DataExport',['../../classug_1_1_data_export.html',1,'ug']]],
  ['dataexport_3c_20number_2c_20dim_20_3e_16507',['DataExport&lt; number, dim &gt;',['../../classug_1_1_data_export.html',1,'ug']]],
  ['dataexport_3c_20ug_3a_3amathmatrix_3c_20dim_2c_20dim_20_3e_2c_20dim_20_3e_16508',['DataExport&lt; ug::MathMatrix&lt; dim, dim &gt;, dim &gt;',['../../classug_1_1_data_export.html',1,'ug']]],
  ['dataexport_3c_20ug_3a_3amathvector_3c_20dim_20_3e_2c_20dim_20_3e_16509',['DataExport&lt; ug::MathVector&lt; dim &gt;, dim &gt;',['../../classug_1_1_data_export.html',1,'ug']]],
  ['dataimport_16510',['DataImport',['../../classug_1_1_data_import.html',1,'ug']]],
  ['dataimport_3c_20number_2c_20dim_20_3e_16511',['DataImport&lt; number, dim &gt;',['../../classug_1_1_data_import.html',1,'DataImport&lt; number, dim &gt;'],['../../classug_1_1_data_import.html',1,'DataImport&lt; number, dim &gt;']]],
  ['dataimport_3c_20ug_3a_3amathmatrix_3c_20dim_2c_20dim_20_3e_2c_20dim_20_3e_16512',['DataImport&lt; ug::MathMatrix&lt; dim, dim &gt;, dim &gt;',['../../classug_1_1_data_import.html',1,'ug']]],
  ['dataimport_3c_20ug_3a_3amathvector_3c_20dim_20_3e_2c_20dim_20_3e_16513',['DataImport&lt; ug::MathVector&lt; dim &gt;, dim &gt;',['../../classug_1_1_data_import.html',1,'ug']]],
  ['datatypedirectlysupported_16514',['DataTypeDirectlySupported',['../../classpcl_1_1_data_type_directly_supported.html',1,'pcl']]],
  ['datatypeindirectlysupported_16515',['DataTypeIndirectlySupported',['../../classpcl_1_1_data_type_indirectly_supported.html',1,'pcl']]],
  ['datatypetraits_16516',['DataTypeTraits',['../../classpcl_1_1_data_type_traits.html',1,'pcl']]],
  ['datatypetraits_3c_20char_20_3e_16517',['DataTypeTraits&lt; char &gt;',['../../classpcl_1_1_data_type_traits_3_01char_01_4.html',1,'pcl']]],
  ['datatypetraits_3c_20double_20_3e_16518',['DataTypeTraits&lt; double &gt;',['../../classpcl_1_1_data_type_traits_3_01double_01_4.html',1,'pcl']]],
  ['datatypetraits_3c_20float_20_3e_16519',['DataTypeTraits&lt; float &gt;',['../../classpcl_1_1_data_type_traits_3_01float_01_4.html',1,'pcl']]],
  ['datatypetraits_3c_20int_20_3e_16520',['DataTypeTraits&lt; int &gt;',['../../classpcl_1_1_data_type_traits_3_01int_01_4.html',1,'pcl']]],
  ['datatypetraits_3c_20long_20_3e_16521',['DataTypeTraits&lt; long &gt;',['../../classpcl_1_1_data_type_traits_3_01long_01_4.html',1,'pcl']]],
  ['datatypetraits_3c_20unsigned_20char_20_3e_16522',['DataTypeTraits&lt; unsigned char &gt;',['../../classpcl_1_1_data_type_traits_3_01unsigned_01char_01_4.html',1,'pcl']]],
  ['datatypetraits_3c_20unsigned_20long_20_3e_16523',['DataTypeTraits&lt; unsigned long &gt;',['../../classpcl_1_1_data_type_traits_3_01unsigned_01long_01_4.html',1,'pcl']]],
  ['datatypetraits_3c_20unsigned_20long_20long_20_3e_16524',['DataTypeTraits&lt; unsigned long long &gt;',['../../classpcl_1_1_data_type_traits_3_01unsigned_01long_01long_01_4.html',1,'pcl']]],
  ['debugid_16525',['DebugID',['../../classug_1_1_debug_i_d.html',1,'ug']]],
  ['debugidmanager_16526',['DebugIDManager',['../../classug_1_1_debug_i_d_manager.html',1,'ug']]],
  ['debugiterator_16527',['DebugIterator',['../../classug_1_1_debug_iterator.html',1,'DebugIterator&lt; class &gt;'],['../classug4_bridge_1_1_algebra_1_1_solver_1_1_debug_iterator.html',1,'DebugIterator']]],
  ['debugwritercontext_16528',['DebugWriterContext',['../classug4_bridge_1_1_algebra_1_1_debug_writer_context.html',1,'DebugWriterContext'],['../../classug_1_1_debug_writer_context.html',1,'DebugWriterContext']]],
  ['debugwritingobject_16529',['DebugWritingObject',['../../classug_1_1_debug_writing_object.html',1,'DebugWritingObject&lt; TAlgebra &gt;'],['../classug4_bridge_1_1_algebra_1_1_debug_writing_object.html',1,'DebugWritingObject']]],
  ['debugwritingobject_3c_20algebra_5ftype_20_3e_16530',['DebugWritingObject&lt; algebra_type &gt;',['../../classug_1_1_debug_writing_object.html',1,'']]],
  ['debugwritingobject_3c_20ug_3a_3acpualgebra_20_3e_16531',['DebugWritingObject&lt; ug::CPUAlgebra &gt;',['../../classug_1_1_debug_writing_object.html',1,'']]],
  ['defaultalgebra_16532',['DefaultAlgebra',['../../classug_1_1_default_algebra.html',1,'ug']]],
  ['degeneratedlayermanager_16533',['DegeneratedLayerManager',['../../classug_1_1_degenerated_layer_manager.html',1,'DegeneratedLayerManager&lt; dim &gt;'],['../classug4_bridge_1_1_grid_1_1_degenerated_layer_manager.html',1,'DegeneratedLayerManager']]],
  ['delaunaydebugsaver_16534',['DelaunayDebugSaver',['../../classug_1_1_delaunay_debug_saver.html',1,'ug']]],
  ['delaunayinfo_16535',['DelaunayInfo',['../../classug_1_1_delaunay_info.html',1,'ug']]],
  ['densematrix_16536',['DenseMatrix',['../../classug_1_1_dense_matrix.html',1,'ug']]],
  ['densematrix_3c_20ug_3a_3adensematrix_3c_20ug_3a_3avariablearray2_3c_20double_20_3e_20_3e_20_3e_16537',['DenseMatrix&lt; ug::DenseMatrix&lt; ug::VariableArray2&lt; double &gt; &gt; &gt;',['../../classug_1_1_dense_matrix.html',1,'DenseMatrix&lt; ug::DenseMatrix&lt; ug::VariableArray2&lt; double &gt; &gt; &gt;'],['../../classug_1_1_dense_matrix.html',1,'DenseMatrix&lt; ug::DenseMatrix&lt; ug::VariableArray2&lt; double &gt; &gt; &gt;']]],
  ['densematrix_3c_20ug_3a_3avariablearray2_3c_20number_20_3e_20_3e_16538',['DenseMatrix&lt; ug::VariableArray2&lt; number &gt; &gt;',['../../classug_1_1_dense_matrix.html',1,'ug']]],
  ['densematrix_3c_20variablearray2_3c_20localcplmatrix_20_2a_20_3e_20_3e_16539',['DenseMatrix&lt; VariableArray2&lt; LocalCplMatrix * &gt; &gt;',['../../classug_1_1_dense_matrix.html',1,'DenseMatrix&lt; VariableArray2&lt; LocalCplMatrix * &gt; &gt;'],['../../classug_1_1_dense_matrix.html',1,'DenseMatrix&lt; VariableArray2&lt; LocalCplMatrix * &gt; &gt;']]],
  ['densematrix_3c_20variablearray2_3c_20localcplmatrix_20_3e_20_3e_16540',['DenseMatrix&lt; VariableArray2&lt; LocalCplMatrix &gt; &gt;',['../../classug_1_1_dense_matrix.html',1,'DenseMatrix&lt; VariableArray2&lt; LocalCplMatrix &gt; &gt;'],['../../classug_1_1_dense_matrix.html',1,'DenseMatrix&lt; VariableArray2&lt; LocalCplMatrix &gt; &gt;']]],
  ['densematrix_3c_20variablearray2_3c_20number_20_3e_20_3e_16541',['DenseMatrix&lt; VariableArray2&lt; number &gt; &gt;',['../../classug_1_1_dense_matrix.html',1,'DenseMatrix&lt; VariableArray2&lt; number &gt; &gt;'],['../../classug_1_1_dense_matrix.html',1,'DenseMatrix&lt; VariableArray2&lt; number &gt; &gt;']]],
  ['densematrixfromsparsematrix_16542',['DenseMatrixFromSparseMatrix',['../../structug_1_1_dense_matrix_from_sparse_matrix.html',1,'ug']]],
  ['densematrixinverse_16543',['DenseMatrixInverse',['../../classug_1_1_dense_matrix_inverse.html',1,'ug']]],
  ['densematrixinverse_3c_20ug_3a_3adensematrix_3c_20ug_3a_3avariablearray2_3c_20double_20_3e_20_3e_20_3e_16544',['DenseMatrixInverse&lt; ug::DenseMatrix&lt; ug::VariableArray2&lt; double &gt; &gt; &gt;',['../../classug_1_1_dense_matrix_inverse.html',1,'DenseMatrixInverse&lt; ug::DenseMatrix&lt; ug::VariableArray2&lt; double &gt; &gt; &gt;'],['../../classug_1_1_dense_matrix_inverse.html',1,'DenseMatrixInverse&lt; ug::DenseMatrix&lt; ug::VariableArray2&lt; double &gt; &gt; &gt;']]],
  ['densevector_16545',['DenseVector',['../../classug_1_1_dense_vector.html',1,'ug']]],
  ['densevector_3c_20ug_3a_3avariablearray1_3c_20double_20_3e_20_3e_16546',['DenseVector&lt; ug::VariableArray1&lt; double &gt; &gt;',['../../classug_1_1_dense_vector.html',1,'DenseVector&lt; ug::VariableArray1&lt; double &gt; &gt;'],['../../classug_1_1_dense_vector.html',1,'DenseVector&lt; ug::VariableArray1&lt; double &gt; &gt;']]],
  ['densevector_3c_20ug_3a_3avariablearray1_3c_20number_20_3e_20_3e_16547',['DenseVector&lt; ug::VariableArray1&lt; number &gt; &gt;',['../../classug_1_1_dense_vector.html',1,'ug']]],
  ['densevector_3c_20variablearray1_3c_20number_20_3e_20_3e_16548',['DenseVector&lt; VariableArray1&lt; number &gt; &gt;',['../../classug_1_1_dense_vector.html',1,'DenseVector&lt; VariableArray1&lt; number &gt; &gt;'],['../../classug_1_1_dense_vector.html',1,'DenseVector&lt; VariableArray1&lt; number &gt; &gt;']]],
  ['dependentuserdata_16549',['DependentUserData',['../../classug_1_1_dependent_user_data.html',1,'ug']]],
  ['dependentuserdata_3c_20mathvector_3c_20dim_20_3e_2c_20dim_20_3e_16550',['DependentUserData&lt; MathVector&lt; dim &gt;, dim &gt;',['../../classug_1_1_dependent_user_data.html',1,'']]],
  ['dependentuserdata_3c_20mathvector_3c_20tgridfunction_3a_3adim_20_3e_2c_20dim_20_3e_16551',['DependentUserData&lt; MathVector&lt; TGridFunction::dim &gt;, dim &gt;',['../../classug_1_1_dependent_user_data.html',1,'']]],
  ['dependentuserdata_3c_20number_2c_20dim_20_3e_16552',['DependentUserData&lt; number, dim &gt;',['../../classug_1_1_dependent_user_data.html',1,'DependentUserData&lt; number, dim &gt;'],['../../classug_1_1_dependent_user_data.html',1,'DependentUserData&lt; number, dim &gt;']]],
  ['dependentuserdata_3c_20tret_2c_20dim_20_3e_16553',['DependentUserData&lt; TRet, dim &gt;',['../../classug_1_1_dependent_user_data.html',1,'']]],
  ['dependentuserdata_3c_20ug_3a_3amathmatrix_3c_20dim_2c_20dim_20_3e_2c_20dim_20_3e_16554',['DependentUserData&lt; ug::MathMatrix&lt; dim, dim &gt;, dim &gt;',['../../classug_1_1_dependent_user_data.html',1,'DependentUserData&lt; ug::MathMatrix&lt; dim, dim &gt;, dim &gt;'],['../../classug_1_1_dependent_user_data.html',1,'DependentUserData&lt; ug::MathMatrix&lt; dim, dim &gt;, dim &gt;']]],
  ['dependentuserdata_3c_20ug_3a_3amathvector_3c_20dim_20_3e_2c_20dim_20_3e_16555',['DependentUserData&lt; ug::MathVector&lt; dim &gt;, dim &gt;',['../../classug_1_1_dependent_user_data.html',1,'DependentUserData&lt; ug::MathVector&lt; dim &gt;, dim &gt;'],['../../classug_1_1_dependent_user_data.html',1,'DependentUserData&lt; ug::MathVector&lt; dim &gt;, dim &gt;']]],
  ['dependentuserdatamatrix_16556',['DependentUserDataMatrix',['../classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_dependent_user_data_matrix.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['dependentuserdatanumber_16557',['DependentUserDataNumber',['../classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_dependent_user_data_number.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['dependentuserdatapair_16558',['DependentUserDataPair',['../classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_dependent_user_data_pair.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['dependentuserdatatensor4_16559',['DependentUserDataTensor4',['../classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_dependent_user_data_tensor4.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['dependentuserdatavector_16560',['DependentUserDataVector',['../classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_user_data_1_1_dependent_user_data_vector.html',1,'ug4Bridge::Discretization::SpatialDisc::UserData']]],
  ['derived_16561',['Derived',['../../classug_1_1bridge_1_1_derived.html',1,'ug::bridge']]],
  ['diagvanka_16562',['DiagVanka',['../classug4_bridge_1_1_algebra_1_1_preconditioner_1_1_diag_vanka.html',1,'DiagVanka'],['../../classug_1_1_diag_vanka.html',1,'DiagVanka&lt; class &gt;']]],
  ['dim_5ftraits_16563',['dim_traits',['../../structug_1_1_do_f_distribution_1_1dim__traits.html',1,'dim_traits&lt; dim &gt;'],['../../structug_1_1_grid_function_1_1dim__traits.html',1,'dim_traits&lt; dim &gt;']]],
  ['dimcache_16564',['DimCache',['../../structug_1_1_component_gauss_seidel_1_1_dim_cache.html',1,'ug::ComponentGaussSeidel']]],
  ['dimcrfvgeometry_16565',['DimCRFVGeometry',['../../classug_1_1_dim_c_r_f_v_geometry.html',1,'ug']]],
  ['dimfegeometry_16566',['DimFEGeometry',['../../classug_1_1_dim_f_e_geometry.html',1,'ug']]],
  ['dimfv1geometry_16567',['DimFV1Geometry',['../../classug_1_1_dim_f_v1_geometry.html',1,'ug']]],
  ['dimfv1ibgeometry_16568',['DimFV1IBGeometry',['../../classug_1_1_dim_f_v1_i_b_geometry.html',1,'ug']]],
  ['dimfvgeometry_16569',['DimFVGeometry',['../../classug_1_1_dim_f_v_geometry.html',1,'ug']]],
  ['dimhfv1geometry_16570',['DimHFV1Geometry',['../../classug_1_1_dim_h_f_v1_geometry.html',1,'ug']]],
  ['dimlocaldofset_16571',['DimLocalDoFSet',['../../classug_1_1_dim_local_do_f_set.html',1,'ug']]],
  ['dimlocaldofset_3c_20dim_20_3e_16572',['DimLocalDoFSet&lt; dim &gt;',['../../classug_1_1_dim_local_do_f_set.html',1,'DimLocalDoFSet&lt; dim &gt;'],['../../classug_1_1_dim_local_do_f_set.html',1,'DimLocalDoFSet&lt; dim &gt;']]],
  ['dimlocaldofsets_16573',['DimLocalDoFSets',['../../structug_1_1_local_finite_element_provider_1_1_dim_local_do_f_sets.html',1,'ug::LocalFiniteElementProvider']]],
  ['dimreferenceelement_16574',['DimReferenceElement',['../../classug_1_1_dim_reference_element.html',1,'ug']]],
  ['dimreferenceelement_3c_200_20_3e_16575',['DimReferenceElement&lt; 0 &gt;',['../../classug_1_1_dim_reference_element.html',1,'']]],
  ['dimreferenceelement_3c_201_20_3e_16576',['DimReferenceElement&lt; 1 &gt;',['../../classug_1_1_dim_reference_element.html',1,'']]],
  ['dimreferenceelement_3c_202_20_3e_16577',['DimReferenceElement&lt; 2 &gt;',['../../classug_1_1_dim_reference_element.html',1,'']]],
  ['dimreferenceelement_3c_203_20_3e_16578',['DimReferenceElement&lt; 3 &gt;',['../../classug_1_1_dim_reference_element.html',1,'']]],
  ['dimreferenceelement_3c_20dim_20_3e_16579',['DimReferenceElement&lt; dim &gt;',['../../classug_1_1_dim_reference_element.html',1,'DimReferenceElement&lt; dim &gt;'],['../../classug_1_1_dim_reference_element.html',1,'DimReferenceElement&lt; dim &gt;']]],
  ['dimreferencemapping_16580',['DimReferenceMapping',['../../classug_1_1_dim_reference_mapping.html',1,'ug']]],
  ['dimreferencemapping_3c_20dim_2c_20worlddim_20_3e_16581',['DimReferenceMapping&lt; dim, worldDim &gt;',['../../classug_1_1_dim_reference_mapping.html',1,'DimReferenceMapping&lt; dim, worldDim &gt;'],['../../classug_1_1_dim_reference_mapping.html',1,'DimReferenceMapping&lt; dim, worldDim &gt;']]],
  ['dimreferencemapping_3c_20trefmapping_3a_3adim_2c_20trefmapping_3a_3aworlddim_20_3e_16582',['DimReferenceMapping&lt; TRefMapping::dim, TRefMapping::worldDim &gt;',['../../classug_1_1_dim_reference_mapping.html',1,'']]],
  ['dimreferencemappingwrapper_16583',['DimReferenceMappingWrapper',['../../classug_1_1_dim_reference_mapping_wrapper.html',1,'ug']]],
  ['diracsourcedisc_16584',['DiracSourceDisc',['../../classug_1_1_dirac_source_disc.html',1,'DiracSourceDisc&lt; class &gt;'],['../classug4_bridge_1_1_spatial_disc_1_1_elem_disc_1_1_dirac_source_disc.html',1,'DiracSourceDisc']]],
  ['dirichletboundary_16585',['DirichletBoundary',['../../classug_1_1_dirichlet_boundary.html',1,'DirichletBoundary&lt; class, class &gt;'],['../classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_dirichlet_boundary.html',1,'DirichletBoundary']]],
  ['dirichletboundary_3c_20tdomain_2c_20talgebra_20_3e_16586',['DirichletBoundary&lt; TDomain, TAlgebra &gt;',['../../classug_1_1_dirichlet_boundary.html',1,'ug']]],
  ['discconstraintfvcr_16587',['DiscConstraintFVCR',['../../plugins/classug_1_1_disc_constraint_f_v_c_r.html',1,'DiscConstraintFVCR&lt; class &gt;'],['../classug4_bridge_1_1_spatial_disc_1_1_navier_stokes_1_1_spatial_disc_1_1_navier_stokes_1_1_spatia4afde65ce40249a845031bcce1980ecb.html',1,'DiscConstraintFVCR']]],
  ['distinfosupplier_16588',['DistInfoSupplier',['../../classug_1_1_dist_info_supplier.html',1,'ug']]],
  ['distributedgridmanager_16589',['DistributedGridManager',['../../classug_1_1_distributed_grid_manager.html',1,'ug']]],
  ['distroadjuster_16590',['DistroAdjuster',['../../classug_1_1_distro_adjuster.html',1,'ug']]],
  ['dofcount_16591',['DoFCount',['../../classug_1_1_do_f_count.html',1,'ug']]],
  ['dofdistribution_16592',['DoFDistribution',['../../classug_1_1_do_f_distribution.html',1,'ug']]],
  ['dofdistributioninfo_16593',['DoFDistributionInfo',['../../classug_1_1_do_f_distribution_info.html',1,'ug']]],
  ['dofdistributioninfoprovider_16594',['DoFDistributionInfoProvider',['../classug4_bridge_1_1_discretization_1_1_do_f_distribution_info_provider.html',1,'DoFDistributionInfoProvider'],['../../classug_1_1_do_f_distribution_info_provider.html',1,'DoFDistributionInfoProvider']]],
  ['dofindexstorage_16595',['DoFIndexStorage',['../../classug_1_1_do_f_index_storage.html',1,'ug']]],
  ['domain_16596',['Domain',['../../classug_1_1_domain.html',1,'Domain&lt; d, TGrid, TSubsetHandler &gt;'],['../classug4_bridge_1_1_domain_1_1_domain.html',1,'Domain']]],
  ['domain_3c_20dim_2c_20ug_3a_3amultigrid_2c_20ug_3a_3amultigridsubsethandler_20_3e_16597',['Domain&lt; dim, ug::MultiGrid, ug::MultiGridSubsetHandler &gt;',['../../classug_1_1_domain.html',1,'Domain&lt; dim, ug::MultiGrid, ug::MultiGridSubsetHandler &gt;'],['../../classug_1_1_domain.html',1,'Domain&lt; dim, ug::MultiGrid, ug::MultiGridSubsetHandler &gt;']]],
  ['domain_5ftraits_16598',['domain_traits',['../../structug_1_1domain__traits.html',1,'ug']]],
  ['domain_5ftraits_3c_200_20_3e_16599',['domain_traits&lt; 0 &gt;',['../../structug_1_1domain__traits_3_010_01_4.html',1,'ug']]],
  ['domain_5ftraits_3c_201_20_3e_16600',['domain_traits&lt; 1 &gt;',['../../structug_1_1domain__traits_3_011_01_4.html',1,'ug']]],
  ['domain_5ftraits_3c_202_20_3e_16601',['domain_traits&lt; 2 &gt;',['../../structug_1_1domain__traits_3_012_01_4.html',1,'ug']]],
  ['domain_5ftraits_3c_203_20_3e_16602',['domain_traits&lt; 3 &gt;',['../../structug_1_1domain__traits_3_013_01_4.html',1,'ug']]],
  ['domainbalanceweights_16603',['DomainBalanceWeights',['../../classug_1_1_domain_balance_weights.html',1,'ug']]],
  ['domaincommunicationcostweights_16604',['DomainCommunicationCostWeights',['../../classug_1_1_domain_communication_cost_weights.html',1,'ug']]],
  ['domaindiscretization_16605',['DomainDiscretization',['../../classug_1_1_domain_discretization.html',1,'DomainDiscretization&lt; class, class &gt;'],['../classug4_bridge_1_1_discretization_1_1_spatial_disc_1_1_domain_discretization.html',1,'DomainDiscretization']]],
  ['domaindiscretization_3c_20tdomain_2c_20ug_3a_3acpualgebra_20_3e_16606',['DomainDiscretization&lt; TDomain, ug::CPUAlgebra &gt;',['../../classug_1_1_domain_discretization.html',1,'ug']]],
  ['domaindiscretizationbase_16607',['DomainDiscretizationBase',['../../classug_1_1_domain_discretization_base.html',1,'ug']]],
  ['domaindiscretizationbase_3c_20tdomain_2c_20talgebra_2c_20stdglobassembler_3c_20tdomain_2c_20talgebra_20_3e_20_3e_16608',['DomainDiscretizationBase&lt; TDomain, TAlgebra, StdGlobAssembler&lt; TDomain, TAlgebra &gt; &gt;',['../../classug_1_1_domain_discretization_base.html',1,'']]],
  ['domaininfo_16609',['DomainInfo',['../../classug_1_1_domain_info.html',1,'DomainInfo'],['../classug4_bridge_1_1_domain_1_1_domain_info.html',1,'DomainInfo']]],
  ['domainloadbalancer_16610',['DomainLoadBalancer',['../../classug_1_1_domain_load_balancer.html',1,'ug']]],
  ['domainpartitioner_16611',['DomainPartitioner',['../../classug_1_1_domain_partitioner.html',1,'ug']]],
  ['domainraytracer_16612',['DomainRayTracer',['../../classug_1_1_domain_ray_tracer.html',1,'DomainRayTracer'],['../classug4_bridge_1_1_ray_tracing_1_1_domain_ray_tracer.html',1,'DomainRayTracer']]],
  ['dualgraphneighborcollector_16613',['DualGraphNeighborCollector',['../../classug_1_1_dual_graph_neighbor_collector.html',1,'ug']]]
];
